### ISSUE TITLE
[ui_next] Custom Logos are not horizontally centered on Login Screen .main component

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#10006]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Custom Logos are not horizontally centered on Login Screen .main component

##### ENVIRONMENT
* AWX version: 04/23/21
* AWX install method: yolo'd

##### STEPS TO REPRODUCE
1. Upload a custom logo
2. Navigate to the login page

##### EXPECTED RESULTS
Logo to be centered above .main component

##### ACTUAL RESULTS
Logo left aligned to .main component

##### ADDITIONAL INFORMATION
<img width="1415" alt="Screen Shot 2021-04-22 at 11 53 59 PM" src="https://user-images.githubusercontent.com/12446869/115888370-d7b7fc80-a420-11eb-9985-b1e9586f7eec.png">

**Comment by jakemcdermott** [comment]
(This is expected behavior and working as designed by pf, I believe. - The logo is left-justified. )
