### ISSUE TITLE
Possibility to use custom users for services

### ISSUE THREAD

**Issue by zaskan** [ansible/awx#10018]
##### ISSUE TYPE
 - Feature Idea *

##### SUMMARY
The installer currently defines static users and groups when installing each component of automation platform, these being pulp/nginx/redis/postgres/awx.
This causes problems in environments where these users and groups are already reserved for other use cases, namely where Active Directory manages users across an enterprise.

The installer should be able to support specifying custom users and groups for these components ideally with either names or IDs.

**_Based in a customer use case_**

**Comment by wenottingham** [comment]
This isn't relevant for awx.
