### ISSUE TITLE
installer directory not found while cloning the repo with depth -50

### ISSUE THREAD

**Issue by gargpallavi** [ansible/awx#10015]
I am following the doc https://computingforgeeks.com/how-to-install-ansible-awx-on-ubuntu-linux/ to install ansible awx which says:
git clone --depth 50 https://github.com/ansible/awx.git

and Change to the AWX installer directory -- cd awx/installer/

I have cloned the repo, but I am unable to find the directory. Please help.

**Comment by shanemcd** [comment]
Hello. Please use the official install guide. https://github.com/ansible/awx/blob/devel/INSTALL.md
