### ISSUE TITLE
AWX UI not coming up

### ISSUE THREAD

**Issue by gargpallavi** [ansible/awx#10016]
I have followed the steps given in install.md. 
https://github.com/ansible/awx/blob/devel/INSTALL.md 
Minikube is up with all the pods running since last one hour. I could find the UI url too using the given command, however when I try to ping the url, it doesnt work. I get "Hmm.. cant reach this page."

also, when I do a curl for the http:url , I get message "You need to enable javascript to run this app."

Please help

**Comment by shanemcd** [comment]
What version of minikube? There's a known issue with 1.19.x https://github.com/ansible/awx-operator/issues/205

**Comment by shanemcd** [comment]
Going to assume this is an instance of the link above. Please reach out if you think it's something else.
