### ISSUE TITLE
Error: 'overlay' is not supported over overlayfs, a mount_program is required - Migration from 17.1.0 to 18.0.0

### ISSUE THREAD

**Issue by nscblauensteiner** [ansible/awx#10026]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY
When I migrate AWX 17.1.0 data to 18.0.0, following this [instructions](https://github.com/ansible/awx/blob/devel/tools/docker-compose/docs/data_migration.md), this error chain occurs after doing "make docker-compose".

##### ENVIRONMENT
* AWX version: 17.1.0
* AWX install method: operator, developer environment
* AWX deployment target: openshift, kubernetes, minikube
* Operating System: CentOS 8
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

Follow the instructions in the link above.

##### EXPECTED RESULTS

Docker service is going to start with all of its images.

##### ACTUAL RESULTS

Error Mesage:

[root@ansibledb awx]# make docker-compose

ansible-playbook -i tools/docker-compose/inventory tools/docker-compose/ansible/sources.yml \
    -e awx_image=gcr.io/ansible-tower-engineering/awx_devel \
    -e awx_image_tag=HEAD \
    -e cluster_node_count=1

PLAY [Render AWX Dockerfile and sources] *********************************************************************************************************************************************************

TASK [Create _sources directory] *****************************************************************************************************************************************************************
ok: [localhost]

TASK [sources : Detect secrets] ******************************************************************************************************************************************************************
skipping: [localhost] => (item=pg_password)
skipping: [localhost] => (item=secret_key)
ok: [localhost] => (item=broadcast_websocket_secret)

TASK [sources : Generate secrets if needed] ******************************************************************************************************************************************************
skipping: [localhost] => (item={'changed': False, 'skipped': True, 'skip_reason': 'Conditional result was False', 'item': 'pg_password', 'ansible_loop_var': 'item'})
skipping: [localhost] => (item={'changed': False, 'skipped': True, 'skip_reason': 'Conditional result was False', 'item': 'secret_key', 'ansible_loop_var': 'item'})
skipping: [localhost] => (item={'changed': False, 'stat': {'exists': True, 'path': '../_sources/secrets/broadcast_websocket_secret.yml', 'mode': '0600', 'isdir': False, 'ischr': False, 'isblk': False, 'isreg': True, 'isfifo': False, 'islnk': False, 'issock': False, 'uid': 0, 'gid': 0, 'size': 51, 'inode': 271230, 'dev': 64768, 'nlink': 1, 'atime': 1619519432.1562881, 'mtime': 1619519431.7472866, 'ctime': 1619519432.0462878, 'wusr': True, 'rusr': True, 'xusr': False, 'wgrp': False, 'rgrp': False, 'xgrp': False, 'woth': False, 'roth': False, 'xoth': False, 'isuid': False, 'isgid': False, 'blocks': 8, 'block_size': 4096, 'device_type': 0, 'readable': True, 'writeable': True, 'executable': False, 'pw_name': 'root', 'gr_name': 'root', 'checksum': '85c1704064cead1dfa933da0fbe9c1afa70699ae', 'mimetype': 'text/plain', 'charset': 'us-ascii', 'version': '3839278358', 'attributes': ['extents'], 'attr_flags': 'e'}, 'invocation': {'module_args': {'path': '../_sources/secrets/broadcast_websocket_secret.yml', 'follow': False, 'get_md5': False, 'get_checksum': True, 'get_mime': True, 'get_attributes': True, 'checksum_algorithm': 'sha1'}}, 'failed': False, 'item': 'broadcast_websocket_secret', 'ansible_loop_var': 'item'})

TASK [sources : Include generated secrets unless they are explicitly passed in] ******************************************************************************************************************
skipping: [localhost] => (item=None)
skipping: [localhost] => (item=None)
ok: [localhost] => (item=None)
ok: [localhost]

TASK [sources : Write out SECRET_KEY] ************************************************************************************************************************************************************
ok: [localhost]

TASK [sources : Render configuration templates] **************************************************************************************************************************************************
ok: [localhost] => (item=database.py)
ok: [localhost] => (item=websocket_secret.py)
ok: [localhost] => (item=haproxy.cfg)

TASK [sources : Delete old local_settings.py] ****************************************************************************************************************************************************
ok: [localhost]

TASK [sources : Copy local_settings.py] **********************************************************************************************************************************************************
ok: [localhost]

TASK [sources : Get OS info for sdb] *************************************************************************************************************************************************************
ok: [localhost]

TASK [sources : Get user UID] ********************************************************************************************************************************************************************
ok: [localhost]

TASK [sources : Set fact with user UID] **********************************************************************************************************************************************************
ok: [localhost]

TASK [sources : Set global version if not provided] **********************************************************************************************************************************************
skipping: [localhost]

TASK [sources : Render Docker-Compose] ***********************************************************************************************************************************************************
ok: [localhost]

PLAY RECAP ***************************************************************************************************************************************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0

docker-compose -f tools/docker-compose/_sources/docker-compose.yml  up
Starting tools_redis_1    ... done
Starting tools_postgres_1 ... done
Starting tools_awx_1      ... done
Attaching to tools_redis_1, tools_postgres_1, tools_awx_1
redis_1_1   | 1:C 27 Apr 2021 10:42:10.817 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1_1   | 1:C 27 Apr 2021 10:42:10.817 # Redis version=6.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1_1   | 1:C 27 Apr 2021 10:42:10.817 # Configuration loaded
postgres_1  |
postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1  |
postgres_1  | 2021-04-27 10:42:10.882 UTC [1] LOG:  starting PostgreSQL 12.6 (Debian 12.6-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
redis_1_1   | 1:M 27 Apr 2021 10:42:10.819 * Running mode=standalone, port=0.
postgres_1  | 2021-04-27 10:42:10.883 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2021-04-27 10:42:10.883 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2021-04-27 10:42:10.888 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2021-04-27 10:42:10.903 UTC [27] LOG:  database system was shut down at 2021-04-27 10:41:05 UTC
redis_1_1   | 1:M 27 Apr 2021 10:42:10.819 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1_1   | 1:M 27 Apr 2021 10:42:10.819 # Server initialized
redis_1_1   | 1:M 27 Apr 2021 10:42:10.819 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1_1   | 1:M 27 Apr 2021 10:42:10.819 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo madvise > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled (set to 'madvise' or 'never').
redis_1_1   | 1:M 27 Apr 2021 10:42:10.819 * The server is now ready to accept connections at /var/run/redis/redis.sock
postgres_1  | 2021-04-27 10:42:10.907 UTC [1] LOG:  database system is ready to accept connections
awx_1_1     | WARN[0000] Found deprecated file /etc/containers/libpod.conf, please remove. Use /etc/containers/containers.conf to override defaults.
awx_1_1     | WARN[0000] Found deprecated file /etc/containers/libpod.conf, please remove. Use /etc/containers/containers.conf to override defaults.
awx_1_1     | Error: 'overlay' is not supported over overlayfs, a mount_program is required: backing file system is unsupported for this graph driver
awx_1_1     | [ -d "/awx_devel/awx.egg-info" ] || python3 /awx_devel/setup.py egg_info_dev
awx_1_1     | cp -f /tmp/awx.egg-link /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx.egg-link
awx_1_1     | mkdir -p /var/lib/awx/; \
awx_1_1     | if [ "/var/lib/awx/venv/" ]; then \
awx_1_1     |   . /var/lib/awx/venv//awx/bin/activate; \
awx_1_1     | fi; \
awx_1_1     | python -c "import awx; print(awx.__version__)" > /var/lib/awx/.awx_version; \
awx_1_1     |
awx_1_1     | if [ "/var/lib/awx/venv/" ]; then \
awx_1_1     |   . /var/lib/awx/venv//awx/bin/activate; \
awx_1_1     | fi; \
awx_1_1     | awx-manage migrate --noinput
awx_1_1     | 2021-04-27 10:42:19,094 ERROR    [-] awx.main.utils.encryption Failed to decrypt `Setting(pk=19).value`; if you've recently restored from a database backup or are running in a clustered environment, check that your `SECRET_KEY` value is correct
awx_1_1     | Traceback (most recent call last):
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/fernet.py", line 104, in _verify_signature
awx_1_1     |     h.verify(data[-32:])
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/hazmat/primitives/hmac.py", line 66, in verify
awx_1_1     |     ctx.verify(signature)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
awx_1_1     |     raise InvalidSignature("Signature did not match digest.")
awx_1_1     | cryptography.exceptions.InvalidSignature: Signature did not match digest.
awx_1_1     |
awx_1_1     | During handling of the above exception, another exception occurred:
awx_1_1     |
awx_1_1     | Traceback (most recent call last):
awx_1_1     |   File "/awx_devel/awx/main/utils/encryption.py", line 170, in decrypt_field
awx_1_1     |     return smart_str(decrypt_value(key, value))
awx_1_1     |   File "/awx_devel/awx/main/utils/encryption.py", line 143, in decrypt_value
awx_1_1     |     value = f.decrypt(encrypted)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/fernet.py", line 75, in decrypt
awx_1_1     |     return self._decrypt_data(data, timestamp, ttl)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/fernet.py", line 117, in _decrypt_data
awx_1_1     |     self._verify_signature(data)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/fernet.py", line 106, in _verify_signature
awx_1_1     |     raise InvalidToken
awx_1_1     | cryptography.fernet.InvalidToken
awx_1_1     | Traceback (most recent call last):
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/fernet.py", line 104, in _verify_signature
awx_1_1     |     h.verify(data[-32:])
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/hazmat/primitives/hmac.py", line 66, in verify
awx_1_1     |     ctx.verify(signature)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
awx_1_1     |     raise InvalidSignature("Signature did not match digest.")
awx_1_1     | cryptography.exceptions.InvalidSignature: Signature did not match digest.
awx_1_1     |
awx_1_1     | During handling of the above exception, another exception occurred:
awx_1_1     |
awx_1_1     | Traceback (most recent call last):
awx_1_1     |   File "/usr/local/bin/awx-manage", line 9, in <module>
awx_1_1     |     load_entry_point('awx', 'console_scripts', 'awx-manage')()
awx_1_1     |   File "/awx_devel/awx/__init__.py", line 154, in manage
awx_1_1     |     execute_from_command_line(sys.argv)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
awx_1_1     |     utility.execute()
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
awx_1_1     |     self.fetch_command(subcommand).run_from_argv(self.argv)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
awx_1_1     |     self.execute(*args, **cmd_options)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 361, in execute
awx_1_1     |     self.check()
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 390, in check
awx_1_1     |     include_deployment_checks=include_deployment_checks,
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 65, in _run_checks
awx_1_1     |     issues.extend(super()._run_checks(**kwargs))
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 377, in _run_checks
awx_1_1     |     return checks.run_checks(**kwargs)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
awx_1_1     |     new_errors = check(app_configs=app_configs)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
awx_1_1     |     return check_resolver(resolver)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
awx_1_1     |     return check_method()
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/urls/resolvers.py", line 399, in check
awx_1_1     |     for pattern in self.url_patterns:
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
awx_1_1     |     res = instance.__dict__[self.name] = self.func(instance)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/urls/resolvers.py", line 584, in url_patterns
awx_1_1     |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
awx_1_1     |     res = instance.__dict__[self.name] = self.func(instance)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
awx_1_1     |     return import_module(self.urlconf_name)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib64/python3.6/importlib/__init__.py", line 126, in import_module
awx_1_1     |     return _bootstrap._gcd_import(name[level:], package, level)
awx_1_1     |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
awx_1_1     |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
awx_1_1     |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
awx_1_1     |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
awx_1_1     |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
awx_1_1     |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
awx_1_1     |   File "/awx_devel/awx/urls.py", line 20, in <module>
awx_1_1     |     url(r'^sso/', include('social_django.urls', namespace='social')),
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
awx_1_1     |     urlconf_module = import_module(urlconf_module)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib64/python3.6/importlib/__init__.py", line 126, in import_module
awx_1_1     |     return _bootstrap._gcd_import(name[level:], package, level)
awx_1_1     |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
awx_1_1     |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
awx_1_1     |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
awx_1_1     |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
awx_1_1     |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
awx_1_1     |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/social_django/urls.py", line 6, in <module>
awx_1_1     |     from . import views
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/social_django/views.py", line 10, in <module>
awx_1_1     |     from .utils import psa
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/social_django/utils.py", line 13, in <module>
awx_1_1     |     BACKENDS = settings.AUTHENTICATION_BACKENDS
awx_1_1     |   File "/awx_devel/awx/conf/settings.py", line 527, in __getattr_without_cache__
awx_1_1     |     return getattr(self._wrapped, name)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cachetools/decorators.py", line 22, in wrapper
awx_1_1     |     v = func(*args, **kwargs)
awx_1_1     |   File "/awx_devel/awx/conf/settings.py", line 440, in __getattr__
awx_1_1     |     value = self._get_local(name)
awx_1_1     |   File "/awx_devel/awx/conf/settings.py", line 355, in _get_local
awx_1_1     |     self._preload_cache()
awx_1_1     |   File "/awx_devel/awx/conf/settings.py", line 323, in _preload_cache
awx_1_1     |     value = decrypt_field(setting, 'value')
awx_1_1     |   File "/awx_devel/awx/main/utils/encryption.py", line 170, in decrypt_field
awx_1_1     |     return smart_str(decrypt_value(key, value))
awx_1_1     |   File "/awx_devel/awx/main/utils/encryption.py", line 143, in decrypt_value
awx_1_1     |     value = f.decrypt(encrypted)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/fernet.py", line 75, in decrypt
awx_1_1     |     return self._decrypt_data(data, timestamp, ttl)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/fernet.py", line 117, in _decrypt_data
awx_1_1     |     self._verify_signature(data)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/fernet.py", line 106, in _verify_signature
awx_1_1     |     raise InvalidToken
awx_1_1     | cryptography.fernet.InvalidToken
awx_1_1     | make: *** [Makefile:192: migrate] Error 1
awx_1_1     | if [ "/var/lib/awx/venv/" ]; then \
awx_1_1     |   . /var/lib/awx/venv//awx/bin/activate; \
awx_1_1     | fi; \
awx_1_1     | awx-manage provision_instance --hostname=awx_1; \
awx_1_1     | awx-manage register_queue --queuename=tower --instance_percent=100;\
awx_1_1     | if [ "tower" == "tower,thepentagon" ]; then \
awx_1_1     |   awx-manage provision_instance --hostname=isolated; \
awx_1_1     |   awx-manage register_queue --queuename='thepentagon' --hostnames=isolated --controller=tower; \
awx_1_1     |   awx-manage generate_isolated_key > /awx_devel/awx/main/isolated/authorized_keys; \

**Comment by shanemcd** [comment]
> `cryptography.fernet.InvalidToken`

You need to ensure you are using your old secret key. 

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
