### ISSUE TITLE
Two person confirmation to deploy job or workflow template

### ISSUE THREAD

**Issue by jopaik** [ansible/awx#1002]
- Feature Idea
##### COMPONENT NAME
 - API
 - UI
##### SUMMARY

With the latest  news about false missle launch alert in Hawaii and Japan.
They are deploying two man confirmation before alert can be sent out.
It would be a good idea to provide an option to have have two person confirmation as an option
before launching ansible jobs or workflow.

##### ENVIRONMENT
* AWX version: X.Y.Z

##### EXPECTED RESULTS
two person deployment confirmation as an option in teams.
when user1 in team1 deploys a job/workflow, another user2 in team1 must confirm before launching job/workflow

**Comment by wenottingham** [comment]
this is essentially a form of #968, closing as duplicate.
