### ISSUE TITLE
Installation Documentation not complete

### ISSUE THREAD

**Issue by wolfgangp-tak** [ansible/awx#10028]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME
 - Installer

##### SUMMARY
Installation Documentation doesn't work.

##### ENVIRONMENT
* AWX version: 1.18.1
* AWX install method: operator
* AWX deployment target: minikube
* Operating System: Redhat 8.0
* Web Browser: n/A

##### STEPS TO REPRODUCE

I followed steps according to 
https://github.com/ansible/awx/blob/devel/INSTALL.md

the pod's doesn't start if you follow the installation manual

##### EXPECTED RESULTS

is up and working

##### ACTUAL RESULTS

awx-b5f6cf4d4-hm95b                0/4     Pending   0          3h42m
awx-operator-f768499d-5mcnj   1/1     Running   1          4h8m
awx-postgres-0                           1/1     Running   1          3h42m

**Comment by shanemcd** [comment]
- What version of minikube?
- Please provide output of `kubectl describe pod awx-b5f6cf4d4-hm95b`

**Comment by wolfgangp-tak** [comment]
ah sorry this was my mistake ... 

but good idea to add the "kubectl describe" to the documentation for further diagnostics .. 
and also how to make  the "web" available to the public IP Address of the machine.

**Comment by Unamola** [comment]
Hey, i'm having the exact same issues,

can you please elaburate on how you fix them?

Tk u

**Comment by wolfgangp-tak** [comment]
have a look at the "kubectl describe" - in my case i provisoned and 2 cpu and 8 GB EC2 instance this was to less to get it run... changed the "size"of the EC2 to 4 cpu and 16 GB ram then it worked.

**Comment by Unamola** [comment]
Tk u for reply .
i did the discribe and i can see it says i lack cpu. i will now try and figure out how to add more.. novice K8's here...
can you also tell me how you fixed  the "web" available to the public IP Address of the machine?

**Comment by wolfgangp-tak** [comment]
honestly i didn't get a proxy to run .. tried half a day .. a the end i used the local firewall, but i'm missing still the https proxy... would be good to get this in the documentation .. how to fullfill a standard setup -- not everyone knows all the ins and outs of minikube ... 

sudo iptables -t nat -A PREROUTING -p tcp --dport 8080 -j DNAT --to-destination xxxx
sudo iptables -t nat -A POSTROUTING -j MASQUERADE
