### ISSUE TITLE
The installer should verify if ipv6 is disabled

### ISSUE THREAD

**Issue by zaskan** [ansible/awx#10020]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

During the installation of Automation Hub the nginx role creates /etc/nginx/nginx.conf and appends the lines:

```
listen [::]:443 default_server deferred ssl;
listen [::]:80 default_server;
```

On systems where ipv6 has been removed this results in the following error and a failure to start nginx:

```
Apr 23 12:36:41 XXXXXXXXXX nginx: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
Apr 23 12:36:41 XXXXXXXXXX nginx: nginx: [emerg] socket() [::]:443 failed (97: Address family not supported by protocol)
Apr 23 12:36:41 XXXXXXXXXX nginx: nginx: configuration file /etc/nginx/nginx.conf test failed
```

The Nginx role should validate that ipv4 and ipv6 are enabled before adding their respective configuration options.

**Comment by shanemcd** [comment]
This role does not exist upstream. Please open this issue in the appropriate repo.
