### ISSUE TITLE
how to install pysnow into awx 17.1.0

### ISSUE THREAD

**Issue by bobby0724** [ansible/awx#10046]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

We have several service now playbooks is there a procedure to install pysnow module ?
##### ENVIRONMENT
* AWX version: 17.1.0
* AWX install method: openshift

**Comment by wenottingham** [comment]
This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
