### ISSUE TITLE
Configurable fields on Jobs (and maybe others) page

### ISSUE THREAD

**Issue by emulanob** [ansible/awx#10051]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Currently (version 17.x and up) you can filter and sort the results on the Jobs page by many fields useful fields, but the columns in the results grid are fixed and unchangeable. Could that be added, maybe in a toggle fashion like AWS Console does? (screenshot for reference)
![image](https://user-images.githubusercontent.com/36779151/116543158-cf166900-a8ed-11eb-803a-272fda9709f9.png)

In my case at least, the "Launched By" field would be already super helpful, but I've seen other feature requests here about survey answers and more, e.g. https://github.com/ansible/awx/issues/8321.

Thanks in advance.

**Comment by AlexSCorey** [comment]
@emulanob the expanded view has the `Launched By` info, and more that you are looking for.  Let us know if this is does not solve your problem and I will reopen this issue.
![Screen Shot 2021-04-29 at 9 39 43 AM](https://user-images.githubusercontent.com/39280967/116559874-db3efe00-a8ce-11eb-8bd7-d79b4aca5630.png)

**Comment by emulanob** [comment]
Hey @AlexSCorey, thanks for the reply. Is that a > 19.0.0 feature? On 17.0.1 I don't see the down arrow.
![image](https://user-images.githubusercontent.com/36779151/116575880-5a542680-a90f-11eb-8c39-d79d7faed39d.png)

**Comment by AlexSCorey** [comment]
@emulanob my apologies.  This feature is only available in the devel branch right now and we brought in with this [PR](https://github.com/ansible/awx/pull/9933).  Look for it to be released soon.
