### ISSUE TITLE
Does collections_requirements.yml still work to add Galaxy packages during build/install

### ISSUE THREAD

**Issue by washburnjoe** [ansible/awx#10052]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME
 - Installer

##### SUMMARY
In the past I would add things to collection_requirements.yml that needed to be installed during install/build.  Once we have AWX up and running we cant get to the outside because of corp restrictions.  So when we need something new installed via Galaxy (for example: community.hashi_vault) I was told we would add it to collections_requirements.yml.  I am curious if this still works.  I have been tasked by my team to investigate.  

##### ENVIRONMENT
* AWX version: 19.0
* AWX install method: operator, developer environment
* AWX deployment target: kubernetes, minikube

**Comment by wenottingham** [comment]
This would no longer be done in a build of AWX, and would now be done in a build of the execution environment that you'd use. See https://ansible-builder.readthedocs.io/en/latest/
