### ISSUE TITLE
project_update.yml keeps on skipping taks despite changed requirements.yml

### ISSUE THREAD

**Issue by Bishwash-Pokhrel** [ansible/awx#10058]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 19.0.0
* AWX install method: minikube/docker on linux
* Ansible version:  2.9.13
* Operating System: Linux 
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Copy the playbook from [this](https://github.com/ansible/awx/blob/devel/awx/playbooks/project_update.yml) playbook. Import it as a project. Set up requirements.yml in your repo and also set it up in awx. Run the job. Make changes in the requirement.yml file and try running the job again.  

##### EXPECTED RESULTS

The job should be executed and installed its respective galaxy collections from requirements.yml.

##### ACTUAL RESULTS
In the task fetch galaxy collections from collections/requirements.(yml/yaml), despite changing the content of requirement.yml in the repository it keeps on skipping the task indicating that no changes were made in the file.  Following are the output of the task.
<img width="667" alt="screenshot3" src="https://user-images.githubusercontent.com/80824494/116675841-e32c9a00-a9c3-11eb-85d0-b1bc7c4f4443.PNG">
<img width="715" alt="screenshot2" src="https://user-images.githubusercontent.com/80824494/116675850-e6278a80-a9c3-11eb-85eb-b23954d8444b.PNG">

**Comment by shanemcd** [comment]
Hello. I think this is a bug that's been biting several people lately. Basically, you need to create a Galaxy credential and attach that to your organization. We'll look to see about updating / creating some docs around this. For now, see https://github.com/ansible/awx/issues/8341#issuecomment-707310633

**Comment by Bishwash-Pokhrel** [comment]
Hi, Even after following the steps from the [comment](https://github.com/ansible/awx/issues/8341#issuecomment-707310633). The job is still skipping. Here is what I did:
1. Created a new galaxy credential from  /api/v2/credentials/?credential_type__kind=galaxy.
2. POST /api/v2/organizations/1/galaxy_credentials/
{
    "id": 2,
    "associate": true
}
The output of  SELECT * FROM conf_setting WHERE key='PUBLIC_GALAXY_ENABLED'; : 

I have attached the screenshot of the output status. 
<img width="197" alt="awx-issue" src="https://user-images.githubusercontent.com/80824494/116969260-9999c300-acd3-11eb-810b-4db309182ffe.PNG">


awx=# SELECT * FROM conf_setting WHERE key='PUBLIC_GALAXY_ENABLED';
 id | created | modified | key | value | user_id 
----+---------+----------+-----+-------+---------
(0 rows)

Output: Same as previous skipping the tasks from requirements.yml.
