### ISSUE TITLE
No handler was ready to ERROR authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials

### ISSUE THREAD

**Issue by tianyuan848192** [ansible/awx#1005]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

My design is using ansible tower to manage file download to the slave node, and my original file is located is aws s3, so i trying to using ansible cloud mould. however, i trying to maintain my s3 authorization AK & SK in my Playbook, it is successed, however, if i try to use cloud credential which i maintain in the ansible credential module, the tower reports me an error "No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials", then i try using the same cloud credential to download file in my ansible tower local machine and it seems ok.

I just think the tower could not pass the credential parameter to the destination machine, and i am not sure why this will happen, could you help me to check for that ?

Thanks and best wishes   
##### ENVIRONMENT
* AWX version:3.1.5
* AWX install method: amazon Linux
* Ansible version:  2.3.1
* Operating System: Amazon Linux
* Web Browser:Chrome

##### STEPS TO REPRODUCE

1. maintain AK & SK in Playbook returns the Success Result
2. maintain and use cloud credential in job template , and download file to destination server it reports error like topic
3. maintain and use cloud credential in job template, and download file to ansible local server, it return Success 

##### EXPECTED RESULTS

Success Result
##### ACTUAL RESULTS

No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials

**Comment by cchurch** [comment]
Could you provide a sample playbook to show us what you're trying to do, specifically how you're passing AWS keys explicitly in the playbook?

**Comment by tianyuan848192** [comment]
scenario 1
when i trying to write the playbook like follow, the job running in tower is successed.
  - name: "download java jdk1.7"
    s3:
      bucket: ******************
      object: /MiddleWare/Language/Java/jdk-7u80-linux-x64.tar.gz
      dest: /tmp/jdk-7u80-linux-x64.tar.gz
      mode: get
      region: cn-north-1
      aws_access_key: *************************
      aws_secret_key: *******************


scenario 2:
when i trying write the playbook like follow, and i maintain cloud credential in template with amazon web service AK & SK, the tower shows me the error with authenticate. 
  - name: "download java jdk1.7"
    s3:
      bucket: ************
      object: /MiddleWare/Language/Java/jdk-7u80-linux-x64.tar.gz
      dest: /tmp/jdk-7u80-linux-x64.tar.gz
      mode: get
      region: cn-north-1

I was guessed the tower did not pass the AK &SK to the template, and i am not sure why it is happened or am i understand wrong the cloud credential could not used like that?

**Comment by wenottingham** [comment]
Please reopen if this persists on a current AWX releae (1.0.6, or similar.)
