### ISSUE TITLE
Proposal, Add back Custom virtual env fields in modules

### ISSUE THREAD

**Issue by sean-m-sullivan** [ansible/awx#10055]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Proposal:
Return the code to have custom virtual environments in their applicable modules that were removed in the update to 17 -> 18. 

The reason being is that there are tower users that use awx.awx because it contains the latest updates and feature improvements, the vast majority still work on Tower 3.7.x,3.8.x.

These would updated and noted in the docs that it is meant for older versions of awx, and will fail on newer. 

The expectation is that the options when used with the wrong version would fail, and it would be on the users to use the right one. I also thing putting depreciated on custom virtual environment options would be appropriate.

The idea is to make it so that users can use the same features and upgrades done to the collection regardless of the version they are using, and put the onus on them to use the correct ones that correspond to their instance. 

I would do the PR for this, but wanted to gather feedback before submitting it.

**Comment by weiyentan** [comment]
Hmm with execution enviroments I can add the collection version I want. And ansible runner will use that...ansible builder can do that. I supply a list of collections I want to pull and then ansible-builder bundles them up and when the job template runs, it executes in the environment using the correct collection version.

At the moment I have a execution environment with Ansible 2.9 (the one that goes bundled is 2.11) tower-configuration (i can choose version) and other stuff... 

Have I misunderstood what you are after?

**Comment by sean-m-sullivan** [comment]
This is for Older versions of Tower/Awx that don't have execution environments, making the modules compatible with both at the same time while people transition from one to the other.

**Comment by shanemcd** [comment]
I'd be interested in learning if we have a pattern in place for backwards compatibility.
