### ISSUE TITLE
[RFE] Tower node root user should not be allowed to self grant themself tower console admin privileges

### ISSUE THREAD

**Issue by pierre-amadio** [ansible/awx#10050]
Currently someone who is root on Tower node has the capability to become admin access on Ansible Console by running 
```
 awx-manage changepassword admin
```
and set the password to whatever he wants.
Tower assume local root user account should be used only by administrators.
However, some organisations grant root privileges on some nodes but do not wish the local admin to be Tower admin for all the organisation.

Would it be possible to set things so that the awx-manage changepassword admin feature take place over email exchange or something that would assure an existing tower admin approve the change ?

**Comment by wenottingham** [comment]
This is not something that can be restricted from the local root user, as it could be done by raw database connection regardless.

You should not have untrusted root users on systems where applications perform sensitive operations.
