### ISSUE TITLE
[ui_next] Testability needed for Wizards

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#10064]
Working on adding automation to some of our test suites, and I came across locators that are needed (without them I can't finish writing the tests).
The wizards for adding roles to teams, or users to teams, job template launch, schedule prompting, etc- many of the elements in these wizards are in need of better locators, especially the Next button

![image](https://user-images.githubusercontent.com/63685497/116741938-aa40f500-a9c4-11eb-8965-aeb5badab2de.png)

**Comment by mabashian** [comment]
The next button is a tough one.  For generic wizard's the footer buttons along with many other buttons/navigation items are all controlled by PF.  They expose props that let us specify the text that gets displayed but thats about it.  For things _inside_ this panel:

<img width="1318" alt="Screen Shot 2021-05-14 at 5 25 50 PM" src="https://user-images.githubusercontent.com/9889020/118333332-8360e380-b4d9-11eb-83df-44f297cffec6.png">

it's pretty easy for us to add identifiers because we control that content.

cc @akus062381 @tiagodread

**Comment by akus062381** [comment]
@mabashian noted on the Next button and thank you!
 
As far as other locators that we need updated (and please let me know if any of these that I'm asking for are too difficult, etc)

The sort button:
![image](https://user-images.githubusercontent.com/63685497/118540061-36218380-b71e-11eb-9ebc-18da64a799c8.png)

The search button:
![image](https://user-images.githubusercontent.com/63685497/118540093-3caffb00-b71e-11eb-96fa-13a381d1453c.png)

The input box here:
![image](https://user-images.githubusercontent.com/63685497/118540152-4c2f4400-b71e-11eb-9107-199c373e3205.png)

The page navigation buttons:
![image](https://user-images.githubusercontent.com/63685497/118540323-7c76e280-b71e-11eb-909d-e249e589eff2.png)

The check boxes here:
![image](https://user-images.githubusercontent.com/63685497/118540596-bc3dca00-b71e-11eb-92d1-2caabaf65ced.png)

The check boxes here:
![image](https://user-images.githubusercontent.com/63685497/118540660-cd86d680-b71e-11eb-887c-bc145e48b102.png)

All three of these buttons, if possible:
![image](https://user-images.githubusercontent.com/63685497/118540773-e98a7800-b71e-11eb-852d-cf9a94450461.png)

These two buttons:
![image](https://user-images.githubusercontent.com/63685497/118541356-94029b00-b71f-11eb-91cb-1306998b5561.png)

**Comment by AlexSCorey** [comment]
@akus062381 

- The sort, search, and input box, and pagination, _should_ all be updated via https://github.com/ansible/awx/pull/10180.  Check it out and let me know if those items don't provide what you need.  

- We can probably add ouiaID stuff to the check boxes with (Admin, Execute, Read) and to the Users and Teams buttons.  

- The Save, Back and Cancel button are all controlled by Patternfly and, as @mabashian mentioned above those are going to be hard for us to add the ouiaID stuff to.

**Comment by akus062381** [comment]
@AlexSCorey - the sort, search, input box, and pagination are great, thank you!
If you decide to add OUIA ids to the check boxes, let me know and I'll take a look
Noted on the Save/Next/Cancel buttons! :-)
