### ISSUE TITLE
documentation needed: how to upgrade an existing AWX in kubernetes without loosing all data

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx#10075]
##### ISSUE TYPE
 - documentation request: update guide needed

##### SUMMARY
There is no documentation about how to upgrade an existing AWX on kubernetes, i.e. from 19.0.0 to 19.1.0, without loosing the data in the database.

**Comment by duntonr** [comment]
bump

**Comment by shanemcd** [comment]
Please re-open this on awx-operator.
