### ISSUE TITLE
Cant delete managed_by_tower Execution Environments

### ISSUE THREAD

**Issue by amg-web** [ansible/awx#10078]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Deleted during update Default EE is still in a list and can not be removed

##### ENVIRONMENT
* AWX version: 19.0.0, 19.1.0
* AWX install method: AWX Operator
* Ansible version:  Who knows ?
* Operating System: Ubuntu 18.04
* Web Browser: Opera

##### STEPS TO REPRODUCE

Updated my minikube AWX setup:
kubectl delete -f myawx.yml
then 
minikube kubectl apply -- -f myawx.yml

After update the new EE v0.2 is installed 
Older EE is still in the list and can not be removed.
Screenshots

##### EXPECTED RESULTS

The only one available EE in the list

##### ACTUAL RESULTS

2 unavailable EE in the list. And 1 actual

##### ADDITIONAL INFORMATION

screenshots
![Ansible AWX - Opera 02 05 2021 10_47_40](https://user-images.githubusercontent.com/22151881/116806266-869cbc80-ab34-11eb-89bb-e94bc4936036.png)
![Ansible AWX - Opera 02 05 2021 10_47_31](https://user-images.githubusercontent.com/22151881/116806268-87355300-ab34-11eb-92a3-43907f8c9e94.png)

**Comment by daenney** [comment]
I field this same issue against AWX Operator instead: https://github.com/ansible/awx-operator/issues/255

**Comment by Zokormazo** [comment]
Verified. Thanks!
