### ISSUE TITLE
Unable to delete Execution Environments in UI

### ISSUE THREAD

**Issue by ryan012880** [ansible/awx#10083]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After upgrading from 19.0.0 to 19.1.0 I am unable to delete the old AWX EE created by the deployer/installer in the Execution Environment Section even using an admin user or a user with an admin role.

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: minikube
* Ansible version:  2.11.x
* Operating System: RHEL7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Upgrade AWX from 19.0.0 to 19.1.0 also awx-ee image from 0.1.1 to 0.2.0

##### EXPECTED RESULTS

If I have multiple AWX EE managed by tower I should be able to delete

##### ACTUAL RESULTS

The delete button is grayed out even if the row is selected, for AWX EE created from the UI delete by the user delete button is working.

<img width="1414" alt="Screen Shot 2021-05-03 at 9 26 27 PM" src="https://user-images.githubusercontent.com/10410660/116881800-46cdf600-ac56-11eb-828a-316798591294.png">

**Comment by shanemcd** [comment]
Let's track this in https://github.com/ansible/awx/issues/10078
