### ISSUE TITLE
Custom logo does not show properly

### ISSUE THREAD

**Issue by Yoiro** [ansible/awx#1008]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

When setting a custom logo from the UI, the freshly uploaded image does not show as header neither as favicon.

##### ENVIRONMENT
* AWX version: 1.0.2.337
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: RHEL 7.4 (AWX host), Windows 7 (Client)
* Web Browser: Google Chrome & Firefox

##### STEPS TO REPRODUCE

* Go into the "Settings" menu
* Click on "User Interface" button
* On logo, upload a custom one in .png.

##### EXPECTED RESULTS

The uploaded logo replaces the previous one everywhere

##### ACTUAL RESULTS

It only replaces the login logo.

##### ADDITIONAL INFORMATION

<!-- Include any links to sosreport, database dumps, screenshots or other>
![image](https://image.noelshack.com/fichiers/2018/03/4/1516280738-settings.png)

**Comment by mkempster22** [comment]
This isn't a bug. The option in the menu is only meant to change the login logo. Currently the only way to replace the header logo etc. is to go into awx and replace files described here: https://groups.google.com/forum/#!topic/awx-project/AGE_0pN4ViY

**Comment by Yoiro** [comment]
Oh ok so, my bad. Thanks for the information :).

**Comment by jkellerer** [comment]
The following workaround does the trick with not too much effort & changes (tested in AWX 1.0.7.2):

* Create a new SVG file `custom-logo.svg` with document size 200 x 110 px.
* Place your logo within the rectangle [48 x 55] TO [200 x 105]. Basically start from left at 48px and from top at 55px.
* Update volume bindings in the `awx_web` container to include `custom-logo.svg`:
  ```
  ./custom-logo.svg:/usr/lib/python2.7/site-packages/awx/ui/static/assets/logo-header.svg:ro
  ```
  E.g. when used with `docker-compose.yml`  (assuming `custom-logo.svg` is in the same folder):
  ``` .yaml
  web:
    image: ansible/awx_web:latest
    ...
    volumes:
      - ./custom-logo.svg:/usr/lib/python2.7/site-packages/awx/ui/static/assets/logo-header.svg:ro
      ...
  ```
   Afterwards do:
  ``` .sh
   docker-compose down
   docker-compose up -d 
  ```
   Done. New logo is used.

**Comment by ongsunglau** [comment]
> The following workaround does the trick with not too much effort & changes (tested in AWX 1.0.7.2):
> 
> * Create a new SVG file `custom-logo.svg` with document size 200 x 110 px.
> * Place your logo within the rectangle [48 x 55] TO [200 x 105]. Basically start from left at 48px and from top at 55px.
> * Update volume bindings in the `awx_web` container to include `custom-logo.svg`:
>   ```
>   ./custom-logo.svg:/usr/lib/python2.7/site-packages/awx/ui/static/assets/logo-header.svg:ro
>   ```
>   
>   
>   E.g. when used with `docker-compose.yml`  (assuming `custom-logo.svg` is in the same folder):
>   ```yaml
>   web:
>     image: ansible/awx_web:latest
>     ...
>     volumes:
>       - ./custom-logo.svg:/usr/lib/python2.7/site-packages/awx/ui/static/assets/logo-header.svg:ro
>       ...
>   ```
>   
>   
>   Afterwards do:
>   ```shell
>    docker-compose down
>    docker-compose up -d 
>   ```
>   
>   
>   Done. New logo is used.

Nice info, but how about if without docker, I understand that this will using docker but how if without docker the path is same?

**Comment by frsauvage** [comment]
Hi all,
Is it possible to redistribute AWX after changing the logo-header.svg as @ongsunglau said ? 
In other words, does Apache 2 license allows to change the AWX logo-header.svg and distribute the modified product ?
Regards,
Francine
