### ISSUE TITLE
Unable to make changes on AWX_TASK_ENV (19.1.0)

### ISSUE THREAD

**Issue by lsabalo** [ansible/awx#10091]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Unable to define AWX_TASK_ENV content using either GUI or API 

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: openshift
* Ansible version:  default on base image
* Operating System: OKD
* Web Browser: Safari / Chrome

##### STEPS TO REPRODUCE
I'm trying to add  **"GIT_SSL_NO_VERIFY": "True"** to **"AWX_TASK_ENV"** by running the following command:

```bash
curl --location --request PUT 'https://awx.apps.lab.okd.local/api/v2/settings/jobs' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic xxxxxxxxxxx' \
--header 'Cookie: xxxxxxxxx' \
--data-raw '{
    "AD_HOC_COMMANDS": [
        "command",
        "shell",
        "yum",
        "apt",
        "apt_key",
        "apt_repository",
        "apt_rpm",
        "service",
        "group",
        "user",
        "mount",
        "ping",
        "selinux",
        "setup",
        "win_ping",
        "win_service",
        "win_updates",
        "win_group",
        "win_user"
    ],
    "ALLOW_JINJA_IN_EXTRA_VARS": "template",
    "AWX_ISOLATION_BASE_PATH": "/tmp",
    "AWX_ISOLATION_SHOW_PATHS": [],
    "AWX_TASK_ENV": {
        "GIT_SSL_NO_VERIFY": "True"
    },
    "PROJECT_UPDATE_VVV": false,
    "AWX_ROLES_ENABLED": true,
    "AWX_COLLECTIONS_ENABLED": true,
    "AWX_SHOW_PLAYBOOK_LINKS": false,
    "GALAXY_IGNORE_CERTS": false,
    "STDOUT_MAX_BYTES_DISPLAY": 1048576,
    "EVENT_STDOUT_MAX_BYTES_DISPLAY": 1024,
    "SCHEDULE_MAX_JOBS": 10,
    "AWX_ANSIBLE_CALLBACK_PLUGINS": [],
    "DEFAULT_JOB_TIMEOUT": 0,
    "DEFAULT_INVENTORY_UPDATE_TIMEOUT": 0,
    "DEFAULT_PROJECT_UPDATE_TIMEOUT": 0,
    "ANSIBLE_FACT_CACHE_TIMEOUT": 0,
    "MAX_FORKS": 200
}'
```

##### EXPECTED RESULTS

```
...
    "AWX_TASK_ENV": {
        "GIT_SSL_NO_VERIFY": "True"
    },
...
```
##### ACTUAL RESULTS

```
...
    "AWX_TASK_ENV": {},
...
```

##### ADDITIONAL INFORMATION

I've even tried thru GUI > Settings > Jobs settings > Extra Environment Variables but when I click "Save", nothing happens.

**Comment by jbradberry** [comment]
After doing some experimenting, I've discovered that the `-L` or `--location` flag isn't enough to deal with the 301 Permanent Redirect that happens when we use one of our API URLs without a slash at the end.  I temporarily added a logging statement that demonstrated that the payload wound up always being empty after the redirect.  Adding the `--post301` flag to the curl command was sufficient to get it to `POST` or `PATCH` correctly.

So, either make sure to use a URL ending in `/`, or add `--post301` to your curl command (or both).

**Comment by jbradberry** [comment]
The problem with the Job settings page in the UI is captured by #10192 .  Closing.
