### ISSUE TITLE
Survey list missing edit icon

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#10095]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Survey list missing edit icon.

Current implementation:

![image](https://user-images.githubusercontent.com/9053044/116934066-72d78000-ac32-11eb-9055-0b0f19f6b60f.png)

Mockup:

![image](https://user-images.githubusercontent.com/9053044/116934007-5afffc00-ac32-11eb-9497-eee06c951658.png)

**Comment by Nitesh639** [comment]
I want to work on this issue.
