### ISSUE TITLE
User token tab bugs

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#10092]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
This is a follow up from https://github.com/ansible/awx/pull/10056

- [x] The token list is not using the new table component
- [x] When the user click on `Tokens` the `Tab` is not being displayed
![image](https://user-images.githubusercontent.com/12464858/116896141-4e67ad80-ac0a-11eb-8ad9-8eae5d34273c.png)

![image](https://user-images.githubusercontent.com/12464858/116895804-f0d36100-ac09-11eb-8f06-903eea0ca591.png)

**Comment by mabashian** [comment]
@tiagodread 

> The token list is not using the new table component

Is this still an issue?  I thought we had gotten through all the lists.

**Comment by mabashian** [comment]
Moving to high to address:

> When the user click on Tokens the Tab is not being displayed

**Comment by tiagodread** [comment]
> @tiagodread
> 
> > The token list is not using the new table component
> 
> Is this still an issue? I thought we had gotten through all the lists.

yep, this is being fixed by the remaining lists PR
![image](https://user-images.githubusercontent.com/12464858/122286308-166caf00-cec6-11eb-9538-1054a01d5d92.png)

**Comment by tiagodread** [comment]
Fixed
