### ISSUE TITLE
Mattermost notification not showing

### ISSUE THREAD

**Issue by Yoiro** [ansible/awx#1009]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

When asking for AWX sending notifications to mattermost on template execution, it doesn't send anything to it. 

##### ENVIRONMENT
* AWX version: 1.0.2.337
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: RHEL7.4 (host), Windows 7 (client)
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

Setup a new Mattermost Notification, add it to a project and a template, then run the template.

##### EXPECTED RESULTS

Two notifications should have been sent to Mattermost.

##### ACTUAL RESULTS

Mattermost only received a notification on SCM update (so I guess it is the one sent at Project level), and no notification on job ending (which is according to me corresponding to the template)

**Comment by wwitzel3** [comment]
Can you re-check? This may have been fixed by #1003

**Comment by matburt** [comment]
let us know if this comes back

**Comment by Yoiro** [comment]
Yes it works. Sorry for the delay, and thanks for your answer.
