### ISSUE TITLE
Jobs on systems missing EEs throw an error instead of failing

### ISSUE THREAD

**Issue by jbradberry** [ansible/awx#10118]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
If the user fails to have an execution environment available, the dispatcher will raise an error and a traceback will go to the logs, but the feedback provided to the user via the UI or API is mysterious.

##### ENVIRONMENT
* AWX version: 19.1.0

##### STEPS TO REPRODUCE

1. deliberately delete all EEs, including any installed managed-by-tower EEs
2. trigger a project update

##### EXPECTED RESULTS

If there are no EEs available, the job should fail with an explicit reason provided in the job output in the UI.

##### ACTUAL RESULTS

job output:
![image(4)](https://user-images.githubusercontent.com/685957/117202438-d17c3580-adbb-11eb-8d5e-ab255aefeacc.png)

in the logs:
```
tools_awx_1 | awx-dispatcher stdout | 2021-05-05 19:46:16,092 ERROR    [c77b9784] awx.main.tasks project_update 17 (running) Exception occurred while running task
tools_awx_1 | awx-dispatcher stdout | Traceback (most recent call last):
tools_awx_1 | awx-dispatcher stdout |   File "/awx_devel/awx/main/tasks.py", line 1316, in run
tools_awx_1 | awx-dispatcher stdout |     env = self.build_env(self.instance, private_data_dir, private_data_files=private_data_files)
tools_awx_1 | awx-dispatcher stdout |   File "/awx_devel/awx/main/tasks.py", line 1883, in build_env
tools_awx_1 | awx-dispatcher stdout |     env = super(RunProjectUpdate, self).build_env(project_update, private_data_dir, private_data_files=private_data_files)
tools_awx_1 | awx-dispatcher stdout |   File "/awx_devel/awx/main/tasks.py", line 997, in build_env
tools_awx_1 | awx-dispatcher stdout |     ee_cred = self.instance.execution_environment.credential
tools_awx_1 | awx-dispatcher stdout | AttributeError: 'NoneType' object has no attribute 'credential'
tools_awx_1 | awx-dispatcher stdout |
```

**Comment by kdelee** [comment]
Manually tested and coverage added in awx unit tests. Closing as verified
