### ISSUE TITLE
Install w/Minikube leaves AWX pod PENDING.

### ISSUE THREAD

**Issue by bandwiches** [ansible/awx#10117]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Can't install via minikube, same process fails over and over again.  AWX pods remain 0/4 PENDING even after an hour.  Nothing is accessible, no valuable logs anywhere, just a complete disaster.  This was all from scratch following the guide.

```json
{
    "level":"error",
    "ts":1620229749.932002,
    "logger":"controller-runtime.controller",
    "msg":"Reconciler error",
    "controller":"awx-controller",
    "request":"default/awx",
    "error":"event runner on failed",
    "stacktrace": 
        "github.com/go-logr/zapr.(*zapLogger).Error
            pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
        sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
            pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:258
        sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
            pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232
        sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
            pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211
        k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
            pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155
        k8s.io/apimachinery/pkg/util/wait.BackoffUntil
            pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156
        k8s.io/apimachinery/pkg/util/wait.JitterUntil
            pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133
        k8s.io/apimachinery/pkg/util/wait.Until
            pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90"
}
```

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: minikube
* Ansible version: n/a
* Operating System: ubuntu
* Web Browser: n/a

##### STEPS TO REPRODUCE

Follow INSTALL.md

##### EXPECTED RESULTS

Expected an instance of AWX, got nothing.

##### ACTUAL RESULTS

Operator and Postgres pods were fine, but the AWX pod failed to load (0/4 PENDING).

##### ADDITIONAL INFORMATION

After a lot of research, I'm pretty conflicted about the install methods suggested by AWX.  AWX recommends docker for development and pushes consumers to using minikube.  The majority of Google suggests that minikube should itself not be used in production.

At this point, it's tempting to stop beating my head against a wall and go back to docker-compose.

**Comment by Valvos420** [comment]
Same issue

**Comment by fourstepper** [comment]
What does `kubectl describe po <name-of-pod>` give you?

**Comment by Valvos420** [comment]
With the command: "minikube kubectl get events" and the issue was that i start the minikube with insufficient ram and cpu so i upgrade that, and now it's "awx is upgrading ..."

**Comment by bandwiches** [comment]
> What does `kubectl describe po <name-of-pod>` give you?

For clarity, I feel I should state that this is a minikube instance of K8S.  I do see a CPU warning on the pod, however it's tough to say what minimal system requirements are needed anymore.  This server is dedicated to Ansible and has successfully run v15 and v17 in a Docker environment.  Upgrading to v19 with the new install (minikube) all of a sudden it complains about resources.  I have to ask, what would be the recommended/minimal system requirements for v19?

**Comment by bandwiches** [comment]
For those running into this issue, it's related to the default system requirements in the `awx-orchestrator` being higher than the actual system itself.  You can specify these values when initializing the environment to get around this.

**Comment by bandwiches** [comment]
In addition to the above, you may find yourself unable to access resources externally.  It seems that IPTABLES does not get updated with the new service URL.

**Comment by solarisfire** [comment]
> For those running into this issue, it's related to the default system requirements in the `awx-orchestrator` being higher than the actual system itself. You can specify these values when initializing the environment to get around this.

Any instructions on how to do that? I ran into this issue today trying to upgrade AWX 18.0.0 to 19.1.0. Upgraded awx-orchestrator and it now just runs a failing playbook on repeat spitting out:

"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"awx-controller","request":"default/awx","error":"event runner on failed","stacktrace":"github.com/go-logr/zapr.

**Comment by bandwiches** [comment]
@solarisfire I'm not sure if this is better suited in `ansibe/awx-operator` or here, but the link is below in regards to the specific variables I modified.  Keep in mind that `awx-orchestrator v0.9.0` still requires "tower_" to be prepended to these variables despite what the documentation says at this time.

[Containers Resource Requirements](https://github.com/ansible/awx-operator#containers-resource-requirements)

These values go into your awx instance deployment template `my-awx.yml`.
