### ISSUE TITLE
RFE - Multi-Tenant Stakeholder Management and Governance

### ISSUE THREAD

**Issue by Saurabh-Thakre** [ansible/awx#10110]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

The customer currently has a multi-tenant Ansible tower with 8-10 tenants using the tower actively. 
Before scaling our Tower infrastructure, they wanted to know if there are better management/governance features on the Ansible tower. 

Need help with the consumption-based model for the tower, but currently, it has 0 features for that. 

It would be helpful if we had the following features

1. Usage patterns of the tower - Based on the No of users /organization/teams/Projects 
2. Licensing and maintenance costs for the tower
3. Resource Utilisation by the jobs (CPU, Memory, IO), No of jobs run, frequency of those jobs
4. Best practices for chargeback

**Comment by shanemcd** [comment]
This issue does not belong in the upstream project.
