### ISSUE TITLE
Inventory file box does not allow custom filename input.

### ISSUE THREAD

**Issue by yurtesen** [ansible/awx#10111]
I am sorry if this was reported before I tried to search the issues open and closed but could not find it. 
Also I am sorry that I am not using the latest version because upgrade process is broken -> https://github.com/ansible/awx/issues/9540

##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Before the new skin, I could type the name of the file there myself. Now it only allows me to select from the list which does not have all the inventory files in the project!
I wonder how it decides if a file is an inventory or not, because it shows some .sh scripts in that list but not actual .yml files.

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker
* Ansible version: 2.9.17
* Operating System: Ubuntu 20.04 LTSs
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Try to add a project as inventory source and write the inventory file name to the `Inventory file:` field.

##### EXPECTED RESULTS

It should allow me to write arbitrary file names in arbitrary paths.

##### ACTUAL RESULTS

There is only a drop down list and it does not allow custom input.

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/1926599/117120110-9b2ebe00-ad9b-11eb-8ed6-0b32c8577252.png)  

It says one can enter the file name still. But it does not allow it.

**Comment by Nemental** [comment]
I can confirm.  
**Workaround**: Open the web inspector tool of your browser and edit the `value` of one of the dropdown items. Then select the previously edited item and save.

**Comment by AlexSCorey** [comment]
@yurtesen This is fixed in the latest AWX version

**Comment by yurtesen** [comment]
@AlexSCorey Thank you, only if I could use the latest AWX.
https://github.com/ansible/awx/issues/9540
