### ISSUE TITLE
AWX 19.1.0 - Job settings cannot be saved (/worker-json.js returns 404)

### ISSUE THREAD

**Issue by fourstepper** [ansible/awx#10123]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Job settings cannot be saved, probably due to the `worker-json.js` returning 404.

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: minikube
* OS: Debian
* Browser: Chromium: 90.0.4430.93 (Official Build) (64-bit)

##### STEPS TO REPRODUCE

- Go the Settings > Jobs settings > Edit
- Tweak a setting
- Hit Save

##### EXPECTED RESULTS

- The settings are saved succesfully

##### ACTUAL RESULTS

- The settings never get updated, the save button doesn't do anything

##### ADDITIONAL INFORMATION

I am not sure what debug information would help, but I will be happy to provide any if required

**Comment by wenottingham** [comment]
We'd need more detail on the error from the browser console.

**Comment by tiagodread** [comment]
When the edit page is loaded for Job settings, there are some errors:

```Warning: Failed prop type: Invalid prop `groupTitle` of type `object` supplied to `NavExpandableGroup`, expected `string`.```

```Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of FindRefWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node```

```Warning: Failed prop type: The prop `config` is marked as required in `BooleanField`, but its value is `undefined`.```

```Warning: Failed prop type: The prop `config` is marked as required in `InputField`, but its value is `undefined`.```

Trying to save the form nothing happens.

**Comment by tiagodread** [comment]
This is a UI only problem I could patch the Job settings by the API

**Comment by fourstepper** [comment]
This is what shows up in the browser console during the whole operation

```
2.fe3515b6.chunk.js:2 I18nProvider did not render. A call to i18n.activate still needs to happen or forceRenderOnLocaleChange must be set to false.
worker-json.js:1 GET https://example.com/worker-json.js 404
worker-json.js:1 GET https://example.com/worker-json.js 404
worker-json.js:1 GET https://example.com/worker-json.js 404
worker-json.js:1 GET https://example.com/worker-json.js 404
worker-json.js:1 GET https://example.com/worker-json.js 404
worker-json.js:1 GET https://example.com/worker-json.js 404
worker-json.js:1 GET https://example.com/worker-json.js 404
worker-json.js:1 GET https://example.com/worker-json.js 404
```

**Comment by jakemcdermott** [comment]
I looked into this and believe I have a PR that will address the problem.  see: https://github.com/ansible/awx/pull/10171

We should fix the `worker-json.js` 404 at some point, but I don't actually think it's related to the form not saving.

**Comment by tiagodread** [comment]
> I looked into this and believe I have a PR that will address the problem. see: #10171
> 
> We should fix the `worker-json.js` 404 at some point, but I don't actually think it's related to the form not saving.

@jakemcdermott with your fix now the form can be save successfully, however the error `worker-json.js:1 GET https://example.com/worker-json.js 404` mentioned by @fourstepper is still being displayed on console.

![image](https://user-images.githubusercontent.com/12464858/118161163-a7e38f80-b3f5-11eb-8141-da1eb28fd64d.png)

**Comment by jakemcdermott** [comment]
@tiagodread 

Yes - let's use [this issue](https://github.com/ansible/awx/issues/10192) for the worker-json 404

**Comment by tiagodread** [comment]
Closing this issue in favour of https://github.com/ansible/awx/issues/10192 with the console errors

**Comment by stuieordie** [comment]
I just deployed AWX today with the AWX Operator 0.9.0 (https://github.com/ansible/awx-operator/releases/tag/0.9.0) and this issue appears to still exist.

It pulled these images
Image:         docker.io/redis:latest
Image:          quay.io/ansible/awx:19.1.0
Image:         quay.io/ansible/awx:19.1.0
Image:         quay.io/ansible/awx-ee:0.2.0

Should the PR  [#10171 ](https://github.com/ansible/awx/pull/10171) have fixed this too?

**Comment by jakemcdermott** [comment]
This will be fixed in 19.2, which hasn't been released yet.

**Comment by fourstepper** [comment]
@jakemcdermott I think it has been? https://github.com/ansible/awx/releases

**Comment by jakemcdermott** [comment]
@fourstepper Oh, you're right. In that case, I'd expect this to be resolved on latest.
