### ISSUE TITLE
Erroneous Multiple Choice Survey Validation on Launch

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#10129]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Survey with a Multiple choice multi select question does not properly validate that question
@tiagodread 
##### ENVIRONMENT
* AWX version: 19
* AWX install method:  docker for mac
* Operating System: Big Sur
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create a required survey question that is Multiple Choice mutli select that has no default values.  Launch the job that uses this survey.  Prompt on Launch wizard opens.  Without answering the Multiple choice survey question to to the preview step.

##### EXPECTED RESULTS
The Launch button should be disabled and the side nav of the survey should have a alert exclamation point

##### ACTUAL RESULTS

Neither of the 2 items above happen.  The launch fails

##### ADDITIONAL INFORMATION
![validation](https://user-images.githubusercontent.com/39280967/117318211-34230f00-ae58-11eb-974f-a77b3b240880.gif)

**Comment by akus062381** [comment]
this is resolved
