### ISSUE TITLE
docker exec tools_awx_1 make clean-ui ui-devel - Not completed fully. looks completed partial.

### ISSUE THREAD

**Issue by unixplex** [ansible/awx#10136]
# docker exec tools_awx_1 make clean-ui ui-devel

rm -rf node_modules
rm -rf awx/ui_next/node_modules
rm -rf awx/ui_next/build
rm -rf awx/ui_next/src/locales/_build
rm -rf awx/ui_next/.ui-built
npm --prefix awx/ui_next --loglevel warn --ignore-scripts install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsev...@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsev...@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsev...@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsev...@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsev...@1.2.13 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsev...@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsev...@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsev...@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 2048 packages from 889 contributors and audited 2056 packages in 34.135s

108 packages are looking for funding
  run `npm fund` for details

found 7 vulnerabilities (6 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
make[1]: Entering directory '/awx_devel'
npm --prefix awx/ui_next --loglevel warn run compile-strings

> ui_...@0.1.0 compile-strings /awx_devel/awx/ui_next
> lingui compile

Compiling message catalogs…
Done!
npm --prefix awx/ui_next --loglevel warn run build

> ui_...@0.1.0 build /awx_devel/awx/ui_next
> INLINE_RUNTIME_CHUNK=false react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  593 KB     build/static/js/2.9a495b89.chunk.js
  290.08 KB  build/static/js/main.3be14996.chunk.js
  61.94 KB   build/static/css/2.14fc25a3.chunk.css
  770 B      build/static/js/runtime-main.a1234c1a.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  bit.ly/CRA-deploy

mkdir -p awx/public/static/css
mkdir -p awx/public/static/js
mkdir -p awx/public/static/media
cp -r awx/ui_next/build/static/css/* awx/public/static/css
cp -r awx/ui_next/build/static/js/* awx/public/static/js
cp -r awx/ui_next/build/static/media/* awx/public/static/media
touch awx/ui_next/.ui-built
make[1]: Leaving directory '/awx_devel'

Pls assist. 
Pls don't say to post in https://groups.google.com/g/awx-project. I don't get proper response.

**Comment by wenottingham** [comment]
There doesn't seem to be a question here?

I realize you may be frustrated with the mailing list, but that
is the proper place for general questions and debugging of build issues.
