### ISSUE TITLE
Deleting a Project or Inventory mid sync throws error

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#10146]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
See https://github.com/ansible/awx/pull/10113#issuecomment-834683595

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Create a project.
Go to project list
click sync
while syncing try to delete the project

##### EXPECTED RESULTS

Project checkbox should be disabled so delete cannot happen

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/39280967/117502681-da9d0c00-af4d-11eb-925c-93d218445123.png)

##### ADDITIONAL INFORMATION
Same thing happens on the Inventory Source list

**Comment by AlexSCorey** [comment]
@tiagodread I filed this issue for the deleting issue https://github.com/ansible/awx/issues/10146

**Comment by mabashian** [comment]
Yea I guess the ideal UX is to indicate to the user that they cannot delete a project/inv source while it's syncing.  We do something similar on other delete confirmation modals.  Show this error is not bad though.

**Comment by InnocentK** [comment]
Resolved.

Note: We should probably add checks for this in our E2E tests
