### ISSUE TITLE
Display error when modifying allow_override on projects

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#10144]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Display error when modifying allow_override on projects being used by job templates.

Previous implementation:

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/9053044/117497831-fc46c500-af46-11eb-82bb-51bd22b3c15b.png">

Current implementation:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/9053044/117497949-2304fb80-af47-11eb-8ce9-091ec44b4875.png">

**Comment by akus062381** [comment]
all set
