### ISSUE TITLE
AWX 19.1: management jobs can not be scheduled

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx#10152]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I'm trying to edit the schedules for the management jobs, but the (existing) schedules are prefilled with values that can't be saved??

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: k3s on debian buster, deployed with awx-operator 0.9.0
* Ansible version:  n/a at this point
* Operating System: whatever is used inside the containers?
* Web Browser: any

##### STEPS TO REPRODUCE

1. click "management jobs"
2. click any one job of the four
3. edit or create a schedule
4. observe "start time" is prefilled with "NaN-NaN-NaNTNaN:NaN:NaN" even if the job had been edited and/or run before already
5. observe how it is impossible to save the schedule unless you manually change the start time to some value that makes sense

##### EXPECTED RESULTS

I'd expect the "start time" to be either 01-01-1970T00:00:00 or the time the AWX instance was deployed before its first run, then the time&date of the first run

##### ACTUAL RESULTS

Schedule can not be saved.

**Comment by jakemcdermott** [comment]
I wasn't able to reproduce this:

![mgmt-schedules](https://user-images.githubusercontent.com/9753817/117839289-1800e280-b249-11eb-9c54-21c4ae30c6e9.gif)

@lemmy04  I'd like to fix this, but so far I haven't found a way to reproduce the bug.

A few questions:

Are you able to reproduce this on a fresh install? 
Is it only on schedules migrated from a prior version?
Can you provide an example schedule that doesn't work just in case it's specific to certain values, etc.

Thank you

**Comment by lemmy04** [comment]
it seems we're not running the same AWX version: I don't have a date/time picker on the schedule page, just a text field.
this is what the page looks like for me on AWX 19.1.0: https://paste.pics/CG2E1

![image](https://user-images.githubusercontent.com/9053044/117863446-c7e24a00-b261-11eb-979d-c325b02a2fcf.png)

**Comment by jakemcdermott** [comment]
Hmm, :thinking:  are you using firefox by any chance? We have an existing bug for that datepicker in firefox that could be related: https://github.com/ansible/awx/issues/9871

When the datepicker doesn't load in firefox, it uses a raw text field as a fallback. It's possible that certain schedule values aren't handled correctly when the fallback is used, but so far all of the schedule input values I've tried seem to work properly.

**Comment by lemmy04** [comment]
d'oh. yep, its the firefox thing - in chrome the interface looks fine. BUT: when I try to edit a job with that "days" value I get #10153 :
Danger alert:Cannot create property 'days' on string '{"days":"30"}'

**Comment by lemmy04** [comment]
oh by the way, i just tried edge, and there's a similar problem with the datepicker there - the button to pick a date is there and works, but the preset value in the date/time field is garbage.

**Comment by tiagodread** [comment]
I Could successfully create/edit schedules with the new datepicker for chrome or firefox in management jobs or any other resource.

![image](https://user-images.githubusercontent.com/12464858/121413393-04c25f00-c93c-11eb-9700-ccecc065836b.png)
