### ISSUE TITLE
Filter option not available in job logs output

### ISSUE THREAD

**Issue by ahlawatvin** [ansible/awx#10154]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Filter option is not available in Job logs output on dashboard

##### ENVIRONMENT
* AWX version: 17.1.0
* AWX install method: docker on linux
* Ansible version:  2.10.8
* Operating System: Opensuse 15.1
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

Add a filter option to search anything from a larger job log output.

##### EXPECTED RESULTS

I want to filter failed logs from Ansible playbook output. 

##### ACTUAL RESULTS

As of now without the filter option it's impossible to search for one kind of logs in ansible output. 

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/83941719/117619746-4325fc00-b18d-11eb-992e-72c3a1fb2dee.png)

**Comment by jakemcdermott** [comment]
:wave: Hello.

 This was added in version 18.0.0, so you'll need to update to a later version in order to use it.
