### ISSUE TITLE
Use machine key for bastion host

### ISSUE THREAD

**Issue by dolgovas** [ansible/awx#10155]
I want to user my machine key - with "ask on run password" for identification on host through proxy_jump!  

##### SUMMARY
Default ansible variables do not work with ansible_ssh_common_args

For example
- work
```
  "ansible_ssh_common_args": "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand=\"ssh -W %h:%p user@xxx.xxx.xxx.xxx -p22 -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null\""
```
- don't work
```
  "ansible_ssh_common_args": "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand=\"ssh -W %h:%p {{ remote_user }}@xxx.xxx.xxx.xxx -p22 -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null\""
```
in which ansible vars or env_vars i can find user from Machine key for user with bastion proxy?

**Comment by wenottingham** [comment]
This is more a question for ansible (https://groups.google.com/g/ansible-project).

I suspect you want to use `ansible_user`, not `remote_user`.

**Comment by dolgovas** [comment]
```
ansible_user
remote_user
ansible_ssh_user
```

are undefined on this step
