### ISSUE TITLE
Notify the user when deleting all or last remain EE

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#10158]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Notify the user when deleting all or last remain EE from the system.

We do allow the system admin to remove all EEs from the system. Before this action we should notify the user that action could lead the system to be on undesirable state.

Probably a notification here.

![image](https://user-images.githubusercontent.com/9053044/117685594-115c6780-b184-11eb-8f35-83cd46591b19.png)

Related: https://github.com/ansible/awx/issues/10118

**Comment by AlexSCorey** [comment]
We already have a delete warning that shows up anytime someone is deleting an EE that is associated with a resource, or when they are deleting >1 EE. We could tack a warning message onto that pretty easily I think.

**Comment by nixocio** [comment]
Thanks @AlexSCorey, I will take look.

**Comment by mabashian** [comment]
@wenottingham mind chiming in on the priority on this one?

**Comment by wenottingham** [comment]
Medium/low - it's a nice UX, but it doesn't affect core must-ship functionality. Want to save high for MVP features/things that are broken.

**Comment by nixocio** [comment]
This issue is no longer accurate - since the user will not be able to delete all EEs from the system.

See: https://github.com/ansible/awx/pull/10378
