### ISSUE TITLE
Empty instance group "tower"

### ISSUE THREAD

**Issue by sfhl** [ansible/awx#10165]
Hi there.

as stated [here](https://github.com/ansible/awx-operator/issues/286), we are experiencing a weird behaviour, as task instances are registered to the web component, but are ungrouped and the main (default) instance group is empty.

Maybe somebody does know why the task component behaves in this way?

Thanks in adance!

**Comment by wenottingham** [comment]
Hi, please only file issues in one place. If you are only seeing this with the operator, the operator issue is the right place to track this.

**Comment by sfhl** [comment]
Hi @wenottingham,
at the moment i am not using the operator at all, thats why i opened an issue here.

**Comment by wenottingham** [comment]
You filed an issue in the awx-operator repo for this exact error, stating you were using k8s. If you're doing a non-operator deployment into k8s based on some custom thing you have done... that custom thing is the most likely source of the issue.

**Comment by sfhl** [comment]
> You filed an issue in the awx-operator repo for this exact error, stating you were using k8s. If you're doing a non-operator deployment into k8s based on some custom thing you have done... that custom thing is the most likely source of the issue.

@wenottingham 
Sorry to say that, but thats not really a prefessional answer. The deployment is exactly the same as the operator would do.
It is very sad that nowadays everybody uses "if you don't do it our way, you must be wrong" as an argument, but okay. thanks for nothing!
