### ISSUE TITLE
Multi-delete modal on jobs could be more clear

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#10164]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

When you have multiple job runs for a particular job, and select to delete some of them, the delete modal is ambiguous as to which run is being deleted.

Example:

![Screenshot from 2021-05-10 17-22-29](https://user-images.githubusercontent.com/5208768/117726388-8182e180-b1b4-11eb-85a1-2ece0242da53.png)

I can see behind the modal to know which of the various 'Demo Job Template' runs are being deleted, but the modal isn't clear on this.

Maybe use the same title as is used in the list that includes the ID?

##### ENVIRONMENT
* AWX version: current

**Comment by tiagodread** [comment]
Fixed!

![image](https://user-images.githubusercontent.com/12464858/122290981-b0365b00-ceca-11eb-84ea-c555582b1f94.png)
