### ISSUE TITLE
Unable to run the AWX Docker Container after pulling

### ISSUE THREAD

**Issue by Lucifergene** [ansible/awx#10188]
I had pulled the docker image of AWX from DockerHub. 
But I am not sure about the parameters that need to be passed in `docker run` command. 

Please provide the command to run the docker container.

**Comment by wenottingham** [comment]
Install docs are here. If you read them, you'll note it's not a simple `docker run`, that is not how the application is deployed.

https://github.com/ansible/awx/blob/devel/INSTALL.md

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
