### ISSUE TITLE
Host Groups Associate Modals Closes on Sort

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#10181]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The Associate modal closes when you sort the Host Groups names.

##### STEPS TO REPRODUCE

Click on Hosts --> Groups Tab --> Associate ---> Sort by name

##### EXPECTED RESULTS

Group names are returned in the modal in reverse alpha order

##### ACTUAL RESULTS

Modal Closes

##### ADDITIONAL INFORMATION
![modalcloses](https://user-images.githubusercontent.com/39280967/117996216-f6b6f980-b30f-11eb-9330-f17c546a5d53.gif)

**Comment by akus062381** [comment]
this issue is resolved
