### ISSUE TITLE
win_firewall is not disabling firewall

### ISSUE THREAD

**Issue by b3rgman** [ansible/awx#1020]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY

When running the win_firewall module.  status shows ok but firewall is still enabled on system.
##### ENVIRONMENT
* AWX version: 
* AWX install method:docker
* Ansible version:  2.4.0.0
* Operating System: CentOS 7.4 (awx) server 2012 r2 (client)
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Added win_firewall module code:

   - name: Disable Windows Firewall
     win_firewall:
       state: disabled
       Profiles:
       - Domain
       - Private
       - Public
     tags: disable_firewall

##### EXPECTED RESULTS
Windows firewall should be disabled

##### ACTUAL RESULTS
Windows firewall is not disabled

##### ADDITIONAL INFORMATION
WMF 5.1 was successfully installed with win_hotfix and the system was rebooted before win_firewall was run.  Here is the snipped from the completed task

{
    "_ansible_parsed": true,
    "Domain": {
        "considered": true,
        "enabled": false,
        "currentstate": 1
    },
    "_ansible_no_log": false,
    "changed": true,
    "Private": {
        "considered": true,
        "enabled": false,
        "currentstate": 1
    },
    "state": "disabled",
    "profiles": [
        "Domain",
        "Private",
        "Public"
    ],
    "Public": {
        "considered": true,
        "enabled": false,
        "currentstate": 1
    }
}

**Comment by wenottingham** [comment]
This reads as an issue with ansible itself. Please file at https://github.com/ansible/ansible/
