### ISSUE TITLE
Variables not removed from the inventory when removed from source

### ISSUE THREAD

**Issue by kuznetsovkk** [ansible/awx#10200]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After removing variables from the original SCM project they will still be present in the inventory variables.

##### ENVIRONMENT
* AWX version: 17.1.0
* AWX install method: docker on linux
* Ansible version:  2.9.18
* Operating System: RedHat 8
* Web Browser: Firefox 88.0.1

##### STEPS TO REPRODUCE

Same as https://github.com/ansible/awx/issues/5682

Create an SCM project, create an inventory sourced in that project (update options for the source: overwrite, overwrite variables, update on project update are checked).

Define few variables in group_vars/all.yml file.
update the project, sync the inventory. Variable is in the Details pane, under Variables.

Delete one variable from group_vars/all.yml file in the SCM.
Update the project, sync the inventory.

##### EXPECTED RESULTS

Variable is not defined anymore. Should not be in Details pane, under Variables.
Any play run against the playbook should not have access to the variable.

##### ACTUAL RESULTS

Variable is still there in Details pane, under Variables.
Any play run against the playbook still has access to the variable.

##### ADDITIONAL INFORMATION

To remove this variable from inventory I have to remove it manualy in awx/inventory/details.
@ianshaw quote: As you can imagine, if you're dealing with hundreds of inventories, this could be a painstaking and human-error-prone procedure.

I'm using docker-compose installation, so if you can, please release a fix for version 17, and not for version 19, which is already only for openshift.

**Comment by wenottingham** [comment]
We remove from groups, but not from the toplevel.  `all` vars can come from any source, and we don't have the mechanism to know that the var that is no longer in this SCM inventory source wasn't also explicitly set on the inventory, or set by another source.

Until we track variable provenance explicitly, we can't do this.

**Comment by kuznetsovkk** [comment]
This bug is not about only toplevel variables. AWX not removing from "inventory/group_vars/somegroup/somerole.yml:somevar: somevalue" too.

**Comment by shanemcd** [comment]
@AlanCoding thoughts?

**Comment by AlanCoding** [comment]
This is a handy script for testing these cases:

https://github.com/ansible/test-playbooks/blob/master/inventories/changes.py#L48

The group named `group_with_vars` is returned by the script. This group then has 2 variables, the first key is `static_group_key` and the second key is dynamic looking like `dynamic_group_2021_05_21_18_27_18.737356`.

So, create an SCM inventory source with that repo & inventory file. Set it to overwrite variables. Update it once, and look at the variables. Copy the dynamic variable for later reference. Now update it again, and check the group details again. The old key is deleted. This is how overwrite variables works, I tested it just now, and it works as expected.

**Comment by AlanCoding** [comment]
Now, you can compare to the inventory all-level variables. After 2 updates, that looks like this:

```json
{
  "dynamic_2021_05_21_18_27_08.099613": "inventory_static_value",
  "static_inventory_key": "inventory_dynamic_2021_05_21_18_27_18.737356",
  "dynamic_2021_05_21_18_27_18.737356": "inventory_static_value"
}
```

The group, on the other hand, only has 2 variables. This just goes to show how the group-level variables have overwrite variables functioning, but the inventory-level variables do not.

**Comment by hungpr0** [comment]
Just to confirm that I meet this bug with same AWX version 17.1.0 (ansible 2.9.18) as report of @kuznetsovkk
I have variables `inventories/production/group_vars/all/10_prometheus.yml`
`test_variable1: 1`
The inventory is from SCM. Deleting that variable from SCM code. It isn't deleted from AWX GUI (Inventories->Production->Details). Playbook run also confirms the variable isn't removed as well.

P/S: Update the value of variable is working, but delete doesn't work.
Please help to check and fix it.
