### ISSUE TITLE
Give better error details when receptor drops a job

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#10213]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Errors from the receptor network (the most obvious ones, details below) are surfaced in the API in a way that gives no really useful information.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Start a job with a sleep task.

Shell into the task container and run `receptorctl work cancel` manually.

Inspect the API detail of those jobs

##### EXPECTED RESULTS

Some kind of `job_explanation`, but failing that, some information in `result_traceback` which is minimally readable and actionable.

##### ACTUAL RESULTS

Get error and this traceback.

```
Traceback (most recent call last):
  File "/awx_devel/awx/main/tasks.py", line 1380, in run
    res = receptor_job.run()
  File "/awx_devel/awx/main/tasks.py", line 2911, in run
    return self._run_internal(receptor_ctl)
  File "/awx_devel/awx/main/tasks.py", line 2969, in _run_internal
    raise RuntimeError(detail)
RuntimeError: Running: PID 6122
```

**Comment by snooyen** [comment]
I've been trying to play with container groups in 19.2.2, but my jobs have been failing with no easily diagnosable error logs. At best I've been able to find things like


`
awx-ee: ERROR2021/08/12 16:04:25 Read error in control service: read unix /var/run/receptor/receptor.sock-u003e@: use of closed network connection
awx-task: WARNING  [556237baf394484a904f40f1558db897] awx.main.dispatch job 18 (error) encountered an error (rc=None), please see task stdout for details.
`

**Comment by AlanCoding** [comment]
Since this was filed we have added a lot more exception handling around this spot, we have a test for what is described, and expectations may change around this anyway.
