### ISSUE TITLE
Expose the output of the EE resolver in the job template detail API endpoints

### ISSUE THREAD

**Issue by jbradberry** [ansible/awx#10210]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

It seems like it would be useful and would mitigate some confusion to expose which EE would be used when executing a template that doesn't have an EE explicitly assigned.

**Clarification**: template detail endpoints.

**Comment by shanemcd** [comment]
Note: Meyers had some performance concerns here. Chat with him about that before implementing this.

**Comment by jbradberry** [comment]
Meyers' concern was the obvious one about not exposing potentially expensive calculated fields in the list views.

**Comment by thenets** [comment]
We made some tests and it's working.

Those are the coverage scenarios:

- **job_template without EE specified**
  - Endpoints
    - related.unified_job_template
    - job_templates
  - Result:
    - {'id': 5, 'name': 'tests @ 3:25:21 PM', 'description': '', 'image': 'test'}

- **job_template with explicit EE associated** (ee.id == 17)
  - Endpoints
    - related.unified_job_template
    - job_templates
  - Result: {'id': 17, 'name': 'EE - AppearanceAddress', 'description': '', 'image': 'quay.io/ansible/ansible-runner:devel'}

We also updated the automated tests.
