### ISSUE TITLE
UI does not link job runs to corresponding project sync

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#10216]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Due to clustering, when a job runs, a project update may be ran in advance of the job starting.

This is not a project update pull the latest source tree. It only pulls the last-seen revision of the project in the event that it is not present locally.

The new UI does not link jobs to this project update.

In many cases, jobs fail but error details are only present in the output of that project update.

##### STEPS TO REPRODUCE

Run the Demo Job Template.

Change the Demo Project to set `update_on_launch` to `False`

Shell into sever and `rm -rf /var/lib/awx/projects/*`

Re-run Demo Job Template and view Job Details in UI

##### EXPECTED RESULTS

Link to project update (or project "sync") as reported by the API

```json
{
    "id": 83,
    "type": "job",
    "url": "/api/v2/jobs/83/",
    "related": {
        "created_by": "/api/v2/users/2/",
        "labels": "/api/v2/jobs/83/labels/",
        "inventory": "/api/v2/inventories/1/",
        "project": "/api/v2/projects/6/",
        "organization": "/api/v2/organizations/1/",
        "credentials": "/api/v2/jobs/83/credentials/",
        "unified_job_template": "/api/v2/job_templates/7/",
        "stdout": "/api/v2/jobs/83/stdout/",
        "execution_environment": "/api/v2/execution_environments/1/",
        "job_events": "/api/v2/jobs/83/job_events/",
        "job_host_summaries": "/api/v2/jobs/83/job_host_summaries/",
        "activity_stream": "/api/v2/jobs/83/activity_stream/",
        "notifications": "/api/v2/jobs/83/notifications/",
        "create_schedule": "/api/v2/jobs/83/create_schedule/",
        "job_template": "/api/v2/job_templates/7/",
        "cancel": "/api/v2/jobs/83/cancel/",
        "project_update": "/api/v2/project_updates/84/",
        "relaunch": "/api/v2/jobs/83/relaunch/"
    },
```

##### ACTUAL RESULTS

No link, the half-green / half-white button next to "Demo Project" is not clickable. In prior UI, there was a green circle with a link.

##### ADDITIONAL INFORMATION

![Screenshot from 2021-05-18 10-51-38](https://user-images.githubusercontent.com/1385596/118673498-0da19400-b7c7-11eb-8f36-cf2129e4f7b2.png)

The "Demo Project" link is not what we need. We need a link to the project update (sync) that ran before the job started.

**Comment by mabashian** [comment]
@AlexSCorey im gonna remove you from this one for now - if you're actually working on it feel free to re-assign and move to in_progress.
