### ISSUE TITLE
No indication of "source" for inventory updates in list or detail views

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#10223]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The UI should give some indication of the type of inventory update that ran.

Right now, the only information the user gets is pretty much:
 - The fact that it is an inventory update
 - Its name

There is a lot more relevant information that is still left out.

##### STEPS TO REPRODUCE

Launch various inventory updates, like SCM inventory, gce, azure, etc.

##### EXPECTED RESULTS

At a glance, the ability to distinguish between the basic types, SCM / gce / azure, and so on

See the _inventory source_ detail view:

![Screenshot from 2021-05-18 14-07-37](https://user-images.githubusercontent.com/1385596/118702473-f7093600-b7e2-11eb-8a97-a38b060192f2.png)

The "Source" and "Inventory File" information here is extremely important information.

##### ACTUAL RESULTS

List view usability is dependent entirely on user naming:

![Screenshot from 2021-05-18 14-10-08](https://user-images.githubusercontent.com/1385596/118702387-db059480-b7e2-11eb-9ef5-7e5e540e8763.png)

Detail view:

![Screenshot from 2021-05-18 14-07-47](https://user-images.githubusercontent.com/1385596/118702571-17d18b80-b7e3-11eb-8578-ddabe85d4cac.png)

This is generic information for all job types (job / inventory / project).

It loses all the important inventory-specific information that you can see in the _inventory source_ view.

##### ADDITIONAL INFORMATION

The API provides these fields. By far the most important is the `source`

**Comment by mabashian** [comment]
To whoever picks this up I think Alan is talking specifically about exposing `summary_fields.inventory_source.source` in both the jobs list and job details view.  For the list I think it would need to go in the expanded row view.

**Comment by AlanCoding** [comment]
> To whoever picks this up I think Alan is talking specifically about exposing `summary_fields.inventory_source.source` in both the jobs list and job details view. For the list I think it would need to go in the expanded row view.

The field you mention gives the same data as the `source` field (and the direct field should be preferred). This is present for `/api/v2/inventory_updates/` and those same entries in `/api/v2/unified_jobs/`. It looks like `"source": "ec2"`. OPTIONS for the inventory updates endpoint gives choices & labels.

**Comment by tiagodread** [comment]
The `Source` data is now exposed on Job Details/List 

![Screenshot from 2021-08-23 13-58-19](https://user-images.githubusercontent.com/12464858/130487098-2716f6e5-f511-45aa-925a-36c0edec7502.png)


![Screenshot from 2021-08-23 13-58-44](https://user-images.githubusercontent.com/12464858/130487132-67cb74dc-c995-4ba8-bdb1-febba380fde2.png)
