### ISSUE TITLE
Parsing year is failing

### ISSUE THREAD

**Issue by jjasghar** [ansible/awx#10220]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
![2021-05-18 at 11 06 AM](https://user-images.githubusercontent.com/810824/118685944-27dc7180-b7c9-11eb-83f8-a6168f84a3c1.png)

##### ENVIRONMENT
* AWX version: 
```
 ______________ 
<  AWX 19.0.0  >
 -------------- 
          \
          \   ^__^
              (oo)\_______
              (__)      A )\
                  ||----w |
                  ||     ||
```
* AWX install method: operator on kubernetes

##### STEPS TO REPRODUCE

Looking for the version of awx, I noticed the copyright year miss-parsed.

/cc @moficodes @odrodrig

**Comment by wenottingham** [comment]
See https://github.com/ansible/awx/pull/9861 - this was fixed in 19.1.
