### ISSUE TITLE
“/users/add” don’t accept special characters

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#10224]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Users can't be created with special chars

##### STEPS TO REPRODUCE

1. Create a user with the name `Robert DROP TABLE students @.+-_` 

##### EXPECTED RESULTS

The user to be created
##### ACTUAL RESULTS

![Screenshot from 2021-05-18 15-41-45](https://user-images.githubusercontent.com/12464858/118707017-6a657480-b7f0-11eb-8bd4-d45bb0476025.png)

**Comment by wenottingham** [comment]
This is a django limitation, we can't fix this.

It should be allowed for other fields (firstname, lastname, etc)
