### ISSUE TITLE
Ansible collection not detected when running playbook on AWX 19.1.0

### ISSUE THREAD

**Issue by trinesh17** [ansible/awx#10236]
We have to limit this because of limited volunteer time to respond to issues! -->

##### ISSUE TYPE
 Getting the below error while executing a playbook from AWX which uses the modules from 3rd party collections
{"reason": "couldn't resolve module/action 'dellemc.openmanage.idrac_lifecycle_controller_status_info'. This often indicates a misspelling, missing collection, or incorrect module path.

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: kuberenets
* Ansible version:  
* Operating System: centos 8.3
* Web Browser:

##### STEPS TO REPRODUCE

I have installed the collections by going inside the awx-ee container and ran the job template from AWX

##### EXPECTED RESULTS

Playbook should be executed successfully

##### ACTUAL RESULTS
Getting the below error while executing a playbook from AWX which uses the modules from 3rd party collections
{"reason": "couldn't resolve module/action 'dellemc.openmanage.idrac_lifecycle_controller_status_info'. This often indicates a misspelling, missing collection, or incorrect module path.

##### ADDITIONAL INFORMATION
when i ran the ansible --version command  inside the awx-ee container, i got the below

ansible [core 2.11.0rc2]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 2.10.3
  libyaml = True

**Comment by trinesh17** [comment]
What is the ideal way to do when running the playbooks from awx( 19.1.0) containing modules from collections

**Comment by ckozler** [comment]
I am also seeing similar issues on 19.0.0. See attached. This is a stock AWX 19.0 deployment in AWS EKS. I have never been able to get collections to work prior and it was communicated that 19 would be better due to the new execution environments. Is there anything else that needs to be done besides having an SCM location with collections/requirements.yaml file?

![2021-05-24-105533_1204x791_scrot](https://user-images.githubusercontent.com/847400/119367040-91ec8f00-bc7f-11eb-823f-20be10ff481a.png)
![2021-05-24-104520_1822x457_scrot](https://user-images.githubusercontent.com/847400/119367044-91ec8f00-bc7f-11eb-961c-005f1637111a.png)
![2021-05-24-104937_794x530_scrot](https://user-images.githubusercontent.com/847400/119367045-92852580-bc7f-11eb-897a-ff35f459371b.png)

**Comment by ckozler** [comment]
Upgraded to 19.1 and still having the same issue. I tested and can confirm that the SCM update/refresh does detect when I add and remove the requirements.yml for both roles and collections but it does not process it and just logs skip and that the conditional result was false

![2021-05-24-140402_1024x355_scrot](https://user-images.githubusercontent.com/847400/119388941-ef410a00-bc98-11eb-90f9-89c7d4f909a2.png)
![2021-05-24-140244_1117x425_scrot](https://user-images.githubusercontent.com/847400/119388943-ef410a00-bc98-11eb-985b-7c6edb99013f.png)

**Comment by ckozler** [comment]
For anyone else who reads this - this is how I fixed it: Copy the default "Ansible Galaxy" credential that you cannot edit from the UI. Go to galaxy.ansible.com, login/link GH account, and then get your API token from your preferences in the top right. Copy that, edit the copied credential in AWX, add the API token you copied, assign your org to the token, then go to organizations and change the credentials to that of your copy. This worked for me

**Comment by trinesh17** [comment]
If it is for SCM atleast 19.1.0 should work for you. Once you add collection/requirements.yml under your project folder and do "sync for revision" it should do the needful. @ckozler

But I am using manual project and didn't find a way to download collections :|

**Comment by ckozler** [comment]
It won't work directly. You need to add credentials manually for galaxy API
and then assign it. Depending on how you deploy AWX will decide what you
need to do, so it appears. Deploying from operator, it appears, because
your org is created via API calls, you need to add credentials for galaxy
manually

**Comment by trinesh17** [comment]
correct

**Comment by ksquires** [comment]
I don't think using a new credential with an API key defined is the right "solution".  It shouldn't be needed, at least how I understand it.

According to:  https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#installing-collections-with-ansible-galaxy
![image](https://user-images.githubusercontent.com/14119434/120031245-2b88a900-bfbe-11eb-816b-0cdbb8731226.png)

the default Ansible Galaxy credential in AWX 19.1 uses Galaxy Server URL  https://galaxy.ansible.com  which, according to the documentation, does not "..need any further configuration".  So for SCM pulls where the repo contains collections/requirements.yml this should work by default but the task is getting skipped

in awx/playbooks/project_update.yml   the when: logic is
`
      when:        - "ansible_version.full is version_compare('2.9', '&gt;=')"        - collections_enabled|bool
`

I'm unsure where collections_enabled is getting set, though.

**Comment by ckozler** [comment]
I don't know what to say. It's the only thing that worked for me

I linked to another change that mentioned any orgs created through the API
will not have credentials setup. I use kubernetes latest and awx operator.
I presume awx operator when it executes the install will use the API to
create your organization. I had credentials setup but I could not modify
them and they had no password/api key associated so I created a new one,
got my API key from galaxy, used that, and then collections began to work

This was the only thing that fixed it for me

**Comment by ksquires** [comment]
this seems to be working now with AWX 19.2.0

**Comment by shanemcd** [comment]
Thanks for the update!

**Comment by nookseal** [comment]
Is there a possible way for manual type of project to load collections?

**Comment by Keith-Nowosielski-SJSU** [comment]
This seems to be broken again in AWX 23.0.0

**Comment by Keith-Nowosielski-SJSU** [comment]
Upgraded to AWX 23.2.0 and I'm still experiencing the same issue. The above workaround isn't working for me.
