### ISSUE TITLE
Activity Stream linkage not working

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#1023]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- UI

##### ENVIRONMENT
* AWX version: devel

##### STEPS TO REPRODUCE

* Create an inventory
* Edit the inventory so that an activity stream entry is created (change the name of the inv)
* Go to the activity stream for inventory
* Click on the blue link to the inventory

##### EXPECTED RESULTS

* To be taken to the inventory edit screen for that inv.

##### ACTUAL RESULTS

* Taken to tower home screen

##### ADDITIONAL INFORMATION
* Activity stream `Schedules` links also do not work
* Maybe the link points to `#/inventories/1/` vs. new `inventories/inventory/1` ?

![9wvy4dmab1](https://user-images.githubusercontent.com/722880/35160969-c93078b8-fd0c-11e7-95d4-e2def0c62332.gif)

**Comment by jakemcdermott** [comment]
see: https://github.com/ansible/awx/pull/1105
