### ISSUE TITLE
Upgrade failed: version 14.1.0 to 17.0.1 

### ISSUE THREAD

**Issue by simonmacpherson** [ansible/awx#10235]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Upgrade from version 14.1.0 to 17.0.1 failing. 

##### ENVIRONMENT
* AWX version: 14.1.0 
* AWX install method: docker on linux
* Ansible version: 2.9.18
* Operating System: NAME="Red Hat Enterprise Linux Server" VERSION="7.9 (Maipo)
* Web Browser: n/a

##### STEPS TO REPRODUCE

Rename ~/awx to awx.old
Navigate to ~/ and run git clone -b 17.1.0 https://github.com/ansible/awx.git
Update inventory file in awx/installer with required information 
Stop redis task web containers using docker-compose
Run ansible-playbook -i inventory install.yml

##### EXPECTED RESULTS

Upgrade to version 17.1.0. 
All containers started.
Configuration retained. 

##### ACTUAL RESULTS

The following tasks fail
TASK [local_docker : Check for existing Postgres data (run from inside the container for access to file)] 
TASK [local_docker : Run migrations in task container] fail. 

TASK [local_docker : Check for existing Postgres data (run from inside the container for access to file)] ******************************************************************************************************************************
task path: /root/awx/installer/roles/local_docker/tasks/upgrade_postgres.yml:16
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1621481039.84-17276-108322218268481 `" && echo ansible-tmp-1621481039.84-17276-108322218268481="` echo /root/.ansible/tmp/ansible-tmp-1621481039.84-17276-108322218268481 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
<localhost> PUT /root/.ansible/tmp/ansible-local-17008qAlpLS/tmplGaWVq TO /root/.ansible/tmp/ansible-tmp-1621481039.84-17276-108322218268481/AnsiballZ_command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1621481039.84-17276-108322218268481/ /root/.ansible/tmp/ansible-tmp-1621481039.84-17276-108322218268481/AnsiballZ_command.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/env python3 /root/.ansible/tmp/ansible-tmp-1621481039.84-17276-108322218268481/AnsiballZ_command.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1621481039.84-17276-108322218268481/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": true, 
    "cmd": "docker run --rm -v '/root/.awx/pgdocker:/var/lib/postgresql' centos:8 bash -c  \"[[ -f /var/lib/postgresql/10/data/PG_VERSION ]] && echo 'exists'\"\n", 
    "delta": "0:00:15.220847", 
    "end": "2021-05-20 05:24:15.405712", 
    "invocation": {
        "module_args": {
            "_raw_params": "docker run --rm -v '/root/.awx/pgdocker:/var/lib/postgresql' centos:8 bash -c  \"[[ -f /var/lib/postgresql/10/data/PG_VERSION ]] && echo 'exists'\"\n", 
            "_uses_shell": true, 
            "argv": null, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "stdin_add_newline": true, 
            "strip_empty_ends": true, 
            "warn": true
        }
    }, 
    "msg": "non-zero return code", 
    "rc": 125, 
    "start": "2021-05-20 05:24:00.184865", 
    "stderr": "Unable to find image 'centos:8' locally\ndocker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).\nSee 'docker run --help'.", 
    "stderr_lines": [
        "Unable to find image 'centos:8' locally", 
        "docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).", 
        "See 'docker run --help'."
    ], 
    "stdout": "", 
    "stdout_lines": []
}
...ignoring

TASK [local_docker : Run migrations in task container] *********************************************************************************************************************************************************************************
task path: /root/awx/installer/roles/local_docker/tasks/compose.yml:45
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1621481063.13-17623-232375261314589 `" && echo ansible-tmp-1621481063.13-17623-232375261314589="` echo /root/.ansible/tmp/ansible-tmp-1621481063.13-17623-232375261314589 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
<localhost> PUT /root/.ansible/tmp/ansible-local-17008qAlpLS/tmpwjwtIr TO /root/.ansible/tmp/ansible-tmp-1621481063.13-17623-232375261314589/AnsiballZ_command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1621481063.13-17623-232375261314589/ /root/.ansible/tmp/ansible-tmp-1621481063.13-17623-232375261314589/AnsiballZ_command.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/env python3 /root/.ansible/tmp/ansible-tmp-1621481063.13-17623-232375261314589/AnsiballZ_command.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1621481063.13-17623-232375261314589/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": true, 
    "cmd": "docker-compose run --rm --service-ports task awx-manage migrate --no-input", 
    "delta": "0:00:15.788639", 
    "end": "2021-05-20 05:24:39.145624", 
    "invocation": {
        "module_args": {
            "_raw_params": "docker-compose run --rm --service-ports task awx-manage migrate --no-input", 
            "_uses_shell": true, 
            "argv": null, 
            "chdir": "/root/.awx/awxcompose", 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "stdin_add_newline": true, 
            "strip_empty_ends": true, 
            "warn": true
        }
    }, 
    "msg": "non-zero return code", 
    "rc": 1, 
    "start": "2021-05-20 05:24:23.356985", 
    "stderr": "Pulling postgres (postgres:12)...\nGet https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)", 
    "stderr_lines": [
        "Pulling postgres (postgres:12)...", 
        "Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
    ], 
    "stdout": "", 
    "stdout_lines": []
}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************
localhost 

##### ADDITIONAL INFORMATION

Attempted upgrade from version 14.1.0 to 17.0.1.

**Comment by john-westcott-iv** [comment]
Sorry for taking so long to respond to this. If this is still an issue could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.
