### ISSUE TITLE
[Testability] Add better locators across components and pages

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#10241]
This issue is a combination of 10 other issues, to add better locator to pages/components, please refer to the closed issue below to get more details:

1. [JT survey prompt on launch modal](https://github.com/ansible/awx/issues/9702)
2. [Workflow Visualizer Node Tab](https://github.com/ansible/awx/issues/9667)
3. [schedules pages](https://github.com/ansible/awx/issues/9565)
4. [toolbar across pages (search fields, Add/Delete buttons)](https://github.com/ansible/awx/issues/9702)
5. [Job Output Details- Link to Associated Job Template](https://github.com/ansible/awx/issues/9517)
6. [Add Roles Wizard](https://github.com/ansible/awx/issues/9513)
7. [JT Lookup Modal for testability](https://github.com/ansible/awx/issues/9509)
8. [Inventories page for testability](https://github.com/ansible/awx/issues/9506)
9. [Dashboard locators](https://github.com/ansible/awx/issues/9502)
10. [Teams Access Tab- Add Teams Modal](https://github.com/ansible/awx/issues/9470)

**Comment by marshmalien** [comment]
Acceptance Criteria: 
1. Don't change existing `ouiaId` locators
2. For components without `ouiaId` prop, use `data-cy` instead

**Comment by akus062381** [comment]
@marshmalien has addressed all of these areas. closing this issue
