### ISSUE TITLE
isolated node

### ISSUE THREAD

**Issue by yaserdashti** [ansible/awx#10247]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

please let me know the reason of removing isolated node and by having isolated node gone, how we can have a runner node in remote location.

**Comment by shanemcd** [comment]
Hello. Isolated nodes were removed because we are moving towards a new architecture. We will be reintroducing the concept of remote nodes later this year. In the meantime, you may want to consider Container Groups.

**Comment by ghost** [comment]
Hi, when will this remote node feature be released?

**Comment by cidrbl0ck** [comment]
Hi there, Also wondering when/if this was brought back. I have a specific use case that Remote or Isolated Nodes would be perfect for.

**Comment by sorquan** [comment]
Any news?
