### ISSUE TITLE
Remove URL params when closing modal/wizard

### ISSUE THREAD

**Issue by keithjgrant** [ansible/awx#10240]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Clean up URL params when closing a modal. See https://github.com/ansible/awx/pull/10215#issuecomment-845202406 for details/examples. Ideally, closing and re-opening a modal should bring it back up in a "clean" state, without filters/search/or pagination applied to any list within the modal.

This might require a little brainstorming & thinking through specific examples to be sure we get the behavior we want everywhere. What about clicking through steps in a wizard—should filters remain if the user navigates back to a previous step where filters were applied?

##### STEPS TO REPRODUCE
Open any modal with a list of items. Run a filter on the list or change pagination options. Close the modal; the filters will remain in the URL params. Re-open the same modal, and the filters will still be applied (because they are read from the URL params)

##### EXPECTED RESULTS

Closing and re-opening a modal should _probably_ bring it back up in a "clean" state, without filters/search/or pagination applied to any list within the modal.

**Comment by keithjgrant** [comment]
Conceptually related (though the code involved is not): https://github.com/ansible/awx/issues/10093

**Comment by mabashian** [comment]
Before we dive into this one lets talk through the level of effort and determine whether this should be worked on over the next week.

**Comment by nixocio** [comment]
@kialam and I worked together verifying where this behavior would be evident.

The only place that this behavior was noticeable was on Credentials screen.

Credentials Edit
1. Password modal <- keeps url params when closed
2. SSH Private Key <- keeps url params when closed
3. Signed SSH Certificate <- keeps url params when closed
4. Private Key Passphrase <- keeps url params when closed
5. Privilege Escalation Username <- keeps url params when closed
6. Privilege Escalation Password <- keeps url params when closed

![image](https://user-images.githubusercontent.com/9053044/122472379-83e41280-cf8e-11eb-8b3a-a034d1cd0cd6.png)

Thank you @kialam !
