### ISSUE TITLE
Labels for Workflow Tasks

### ISSUE THREAD

**Issue by Klistel** [ansible/awx#10246]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

When configuring a workflow, oftentimes you're using  other workflows as building blocks, or even Job Templates that have customized inventories or extra variables. I think it would be very useful to allow a custom label in the workflow visualizer to be applied to an element in the workflow, so that - at a glance - you could see any customizations to the template/workflow you've set.

**Comment by AlexSCorey** [comment]
@Klistel does https://github.com/ansible/awx/issues/2032 also describe what you are seeking? If so we could close this issue in favor of that one because it has a bit more depth and background in it.

**Comment by Klistel** [comment]
Hi @AlexSCorey  - yes that issue does seem to cover the same ground. I've +1'd that issue. Please feel free to close this one.
