### ISSUE TITLE
Lookup Plugin Cannot Locate File

### ISSUE THREAD

**Issue by simonmacpherson** [ansible/awx#10254]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Playbook using the 'cp_mgmt_put_file' module that is part of the Checkpoint Ansible Mgmt Collection does not run correctly when launched within AWX. File cannot found in expected paths by the lookup plugin. 

##### ENVIRONMENT
* AWX version: 14.0.1
* AWX install method: docker
* Ansible version:  2.9.18
* Operating System: RHEL7
* Web Browser: n/a

##### STEPS TO REPRODUCE

Copy bash script to projects folder.
Run playbook using the following as an example

    - name: Put file on gateway
      check_point.mgmt.cp_mgmt_put_file:
        file_content: "{{ lookup('file', 'test.sh') }}"
        file_name: 'test.sh'
        file_path: /usr/tmp/scripts/
        targets:
          - "fw1"
          - "fw2"
    
##### EXPECTED RESULTS

Bash script to be found, ingested and copied to put on specified path on device. 

##### ACTUAL RESULTS

The following output is returned when the playbook is run in check mode. The task is looking for the file in the tmp location but is unable to locate it. 

ASK [Put file on gateway] *****************************************************
task path: /tmp/awx_2325_6tcdpncv/project/copy scripts/copy_scripts_final.yml:167
looking for "TopTalker.sh" at "/tmp/awx_2325_6tcdpncv/project/copy scripts/files/TopTalker.sh"
looking for "TopTalker.sh" at "/tmp/awx_2325_6tcdpncv/project/copy scripts/TopTalker.sh"
looking for "TopTalker.sh" at "/tmp/awx_2325_6tcdpncv/project/copy scripts/files/TopTalker.sh"
looking for "TopTalker.sh" at "/tmp/awx_2325_6tcdpncv/project/copy scripts/TopTalker.sh"
[WARNING]: Unable to find 'TopTalker.sh' in expected paths (use -vvvvv to see
paths)
File lookup using None as file
fatal: [10.1.2.51]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: TopTalker.sh"
}

##### ADDITIONAL INFORMATION

Playbook runs successfully when launched from Ansible command line.

**Comment by wenottingham** [comment]
Playbooks run under job isolation, which prevents them accessing certain paths on the host. Your data should live in the project itself.

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by simonmacpherson** [comment]
The scripts are located in the project folder.
