### ISSUE TITLE
New notification template auto fills

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#1025]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- UI

##### ENVIRONMENT
* AWX version: devel

##### STEPS TO REPRODUCE

* Create a new notification template

##### EXPECTED RESULTS

* For a blank notification template to appear

##### ACTUAL RESULTS

* pre-filled notification template with values from I have no idea.

##### ADDITIONAL INFORMATION

maybe related/duplicate #1022

I'm not sure of what I had to do to get the values "hello world" and "goodbye world" to pre-fill.

![iml1uexflj](https://user-images.githubusercontent.com/722880/35162366-1960f430-fd11-11e7-9ecb-e82b643d7e50.gif)

Seems to happen when adding a user also

![b34gji8ne4](https://user-images.githubusercontent.com/722880/35162730-305ac494-fd12-11e7-8d0e-6c3c99b22c1f.gif)

**Comment by wenottingham** [comment]
... turns out this was lastpass
