### ISSUE TITLE
imagePullPolicy for execution environment not applied

### ISSUE THREAD

**Issue by gstorme** [ansible/awx#10256]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

I've created a custom execution environment with ansible-builder, and added it in the AWX UI with the pull option set to "always pull".
This does not work, unless the image has the `latest` tag, and if it has the `latest` tag, the UI option doesn't even matter, it will always pull the image.
When the tag is not `latest`, the image will not always be pulled, because the imagePullPolicy is set to `IfNotPresent` on the awx-job pod.

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: minikube 1.20 with awx-operator 0.9.0
* Ansible version:  2.11
* Operating System: Debian 10

##### STEPS TO REPRODUCE

Add an execution environment to AWX, don't use the latest tag on your image.
Set the pull policy to always in the UI.
Run a job using this EE.

##### EXPECTED RESULTS

Container image will be pulled upon every job launch.

##### ACTUAL RESULTS

`Container image "git:4567/awx/ee-staging:2.11" already present on machine`

##### ADDITIONAL INFORMATION

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-05-25T11:21:09Z"
  generateName: awx-job-4966-
  labels:
    ansible-awx: 0795ae60-a586-41b5-b859-4292e1bd62a7
    ansible-awx-job-id: "4966"
  name: awx-job-4966-sgxkf
  namespace: default
  resourceVersion: "36741"
  uid: f16ff7ba-b93c-4d8e-8beb-c68f99eb5284
spec:
  containers:
  - args:
    - ansible-runner
    - worker
    - --private-data-dir=/runner
    image: git:4567/awx/ee-staging:2.11
    imagePullPolicy: IfNotPresent
    name: worker
```

**Comment by rooftopcellist** [comment]
I have found this to be the case too.   This will be fix as part of https://github.com/ansible/awx/pull/10204

**Comment by rooftopcellist** [comment]
@gstorme The fix for this has merged, please ping me here if you are still seeing this problem with the new changes.  Thanks!
