### ISSUE TITLE
Windows playbooks fail with "winrm or requests is not installed: No module named 'winrm' on awx-ee:0.2.0 and awx-ee:devel"

### ISSUE THREAD

**Issue by jurschel** [ansible/awx#10262]
ISSUE TYPE
Bug Report
SUMMARY
AWX 19.1.0 EE devel branch pywinrm is not in the standard location 

ENVIRONMENT
AWX version: 19.1.0
AWX install method: awx-operator
Ansible version: 2.11.0rc2
Operating System: Ubuntu 20.04
Web Browser: Firefox
STEPS TO REPRODUCE
Execute a job that requires ansible_connection of winrm
or
run win_ping on AWX-EE CLI.
EXPECTED RESULTS
Successful connection to Windows host.

ACTUAL RESULTS
On CLI, win_ping fails:

bash-4.4$ ansible windows_clients -i inventory/hosts.yml -m win_ping
win10ent-test1 | FAILED! => {
"msg": "winrm or requests is not installed: No module named 'winrm'"
}

AWX job fails with the same error when attempting to connect to Windows host.

ADDITIONAL INFORMATION
pywinrm is located in the devel build of awx-ee however it isn't in the default module location that awx 19.1 is looking for.
When looking in the awx-ee container the win-rm module is found at /usr/local/lib/python3.8/site-packages and not in /usr/local/lib/python3.8/site-packages/ansible which is where ansible is defaulting it's python module location.

ansible-playbook [core 2.11.0rc2] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 2.10.3
  libyaml = True

**Comment by wenottingham** [comment]
-> #10109

**Comment by jurschel** [comment]
Right it was closed.  So open the other one back up please...
