### ISSUE TITLE
Messed up nav bar

### ISSUE THREAD

**Issue by shanemcd** [ansible/awx#1026]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### ENVIRONMENT
* AWX version: awx: 1.0.2.69
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version: N/A
* Operating System: N/A
* Web Browser:

##### STEPS TO REPRODUCE

Pull devel. Look at the UI.
![image](https://user-images.githubusercontent.com/773186/35162372-1e9bff62-fd11-11e7-9c05-42025f46b83b.png)

**Comment by jaredevantabor** [comment]
This was fixed with https://github.com/ansible/awx/pull/1029. moving to QE

**Comment by jakemcdermott** [comment]
resolved by: https://github.com/ansible/awx/pull/1029.
