### ISSUE TITLE
[RFE] mail alert when tower admin password is changed.

### ISSUE THREAD

**Issue by pierre-amadio** [ansible/awx#10276]
This is related to Red Hat support ticket#02945448 and to awx's issue#10050 .
As there is no way to deny a local root user from changing the tower admin password with `awx-manage changepassword admin` , it would be interesting to be able to generate email alert when such an event occurs. 
It is currently possible to use the Tower Api to monitor such change and use that in a script to send alert email:
https://<YOUR_TOWER>/api/v2/activity_stream/?operation=update&object1=user&order_by=-timestamp

However, having this implemented as an official feature that could be activated/deactivated within the console would be appreciated.

**Comment by wenottingham** [comment]
We would not do this; there are no longer mail alerts in the application.

This is already available via the activity stream, which can be configured via logging integrations to send externally. An example of an activity_stream entry for an `awx-manage changepassword` initiated change:

```

{
    "id": 294,
    "type": "activity_stream",
    "url": "/api/v2/activity_stream/294/",
    "related": {
        "user": [
            "/api/v2/users/1/"
        ]
    },
    "summary_fields": {
        "user": [
            {
                "id": 1,
                "username": "admin",
                "first_name": "",
                "last_name": ""
            }
        ]
    },
    "timestamp": "2021-05-26T20:49:06.764563Z",
    "operation": "update",
    "changes": {
        "password": [
            "hidden",
            "hidden"
        ]
    },
    "object1": "user",
    "object2": "",
    "object_association": "",
    "action_node": "localhost",
    "object_type": ""
}
```
