### ISSUE TITLE
AWX Azure AD social login broke after a while

### ISSUE THREAD

**Issue by siwei-luo** [ansible/awx#10277]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I had a working setup with Azure AD SSO with social account integration which suddenly stopped working after a while.

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: operator (0.9.0)
* Ansible version:  X.Y.Z
* Operating System: Kubernetes
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Setup Azure AD with the required information: https://awx.***/#/settings/azure/details

##### EXPECTED RESULTS

After successfull login with Azure the dashboard page is shown.

##### ACTUAL RESULTS

Instead the login page is shown again.

##### ADDITIONAL INFORMATION

This is the error message I observed in the awx-web container:
`2021-05-26 09:06:59,596 ERROR    [e9020227228d4879950be425c6399ef4] social null value in column "credential_id" violates not-null constraint
DETAIL:  Failing row contains (54, null, null, 2).`

I am currently unable to identify the mentioned row in the Postgres database with the suspected NULL value. What I already tried is to find any rows with column name 'credential_id' or similar with a NOT NULL constraint definition.

What I also observed is that the column value '54' gets incremented after each attempt but the rest stays the same.

**Comment by siwei-luo** [comment]
I switched to LDAP to workaround this issue. Guess this ticket can be closed because I cannot contribute any insights anymore.

**Comment by snooyen** [comment]
Ran into this as well when attempting to use Social Auth Org/Team maps with GitHub Organization Auth #10879
