### ISSUE TITLE
Unable to edit prompted fields on job schedule

### ISSUE THREAD

**Issue by Akandou** [ansible/awx#10274]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Job schedule does not show the button to edit prompted fields.

##### ENVIRONMENT
* AWX version: 17.1.0
* AWX install method: docker on linux
* Ansible version:  2.9.18
* Operating System: Ubuntu 20.04 LTS
* Web Browser: Firefox

##### STEPS TO REPRODUCE

- Add new schedule for a job with a survey (or with prompted fields in general).

##### EXPECTED RESULTS

- Prompted fields can be edited
- Job schedule can be created

##### ACTUAL RESULTS

- Job Schedule can not be created.

##### ADDITIONAL INFORMATION

![grafik](https://user-images.githubusercontent.com/45037862/119617585-47dfe680-be02-11eb-9d5e-62c424daa470.png)

**Comment by wenottingham** [comment]
Hi - we believe this is fixed in the latest release of AWX with our new UI. Can you try this with 19.1?

**Comment by merickso** [comment]
By any chance is there a workaround without having to upgrade?

**Comment by Akandou** [comment]
> 
> 
> By any chance is there a workaround without having to upgrade?

We're using workflow schedules as a workaround.

**Comment by Raghavsfeb03** [comment]
> > By any chance is there a workaround without having to upgrade?
> 
> We're using workflow schedules as a workaround.

can you please explain the workflow schedules, how to configure..?

**Comment by AlexSCorey** [comment]
@merickso are you using firefox?

**Comment by shanemcd** [comment]
We don't support past versions of AWX, so you will need to backport the patch if you don't want to upgrade.

**Comment by Raghavsfeb03** [comment]
> @merickso are you using firefox?

it does not work in firefox, any other options..??

**Comment by Raghavsfeb03** [comment]
we need a workaround without having to upgrade ??

**Comment by AlexSCorey** [comment]
@Raghavsfeb03 it does work with Chrome.  If you are able to use Chrome that would resolve it.

**Comment by Raghavsfeb03** [comment]
> @Raghavsfeb03 it does work with Chrome. If you are able to use Chrome that would resolve it.

Issue still exists in Chrome too.

**Comment by Raghavsfeb03** [comment]
this is a Bug in AWX version: 17.1.0 , is there an option to override this Bug and still enable the Schedules..??

**Comment by skiruthi** [comment]
Any workaround to enable the prompt in schedule for 17.1.0
