### ISSUE TITLE
Management job schedule list not refreshed after save

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#1027]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- UI

##### SUMMARY

List view data not refreshed after editing schedule entry.

##### ENVIRONMENT
* AWX version: devel

##### STEPS TO REPRODUCE

* Create a management job schedule, give it a name and save
* Edit it, change the name and save.
* Note the new name/data is not updated in the list view

##### ADDITIONAL INFORMATION

![jrytyqpg8z](https://user-images.githubusercontent.com/722880/35162903-e39e8554-fd12-11e7-82fe-5d89da34368e.gif)

**Comment by jaredevantabor** [comment]
This is fixed in devel.
