### ISSUE TITLE
AWX won't be compatible with community.hashi_vault >= 2.0.0

### ISSUE THREAD

**Issue by infra-monkey** [ansible/awx#10275]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX doesn't support the new environment variables used by community.hashi_vault.hasi_vault lookup plugin.
As described [here](https://docs.ansible.com/ansible/latest/collections/community/hashi_vault/hashi_vault_lookup.html#ansible-collections-community-hashi-vault-hashi-vault-lookup) in their version 2.0.0 the support for environment variables VAULT_ADDR & co will be dropped. 
The new environment variable format (already supported as an alternative) is ANSIBLE_HASHI_VAULT_ADDR & co.
When setting a credential type with these new environment variables, AWX returns an error.

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: kubernetes
* Ansible version:  2.10
* Operating System: Fedora 34
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create a credential type with the following configuration:
Input configuration

> fields:
>   - id: vault_server
>     type: string
>     label: URL for Vault Server
>   - id: vault_role_id
>     type: string
>     label: Role ID
>   - id: vault_secret_id
>     type: string
>     label: Secret ID
>     secret: true
> required:
>   - vault_server
>   - vault_role_id
>   - vault_secret_id

Injector configuration:

> env:
>   ANSIBLE_HASHI_VAULT_ADDR: '{{ vault_server }}'
>   ANSIBLE_HASHI_VAULT_ROLE_ID: '{{ vault_role_id }}'
>   ANSIBLE_HASHI_VAULT_SECRET_ID: '{{ vault_secret_id }}'
>   ANSIBLE_HASHI_VAULT_AUTH_METHOD: approle

##### EXPECTED RESULTS

I expect the credential type to be created.

##### ACTUAL RESULTS

AWX fails to create the credential type and returns the error:
Environment variable ANSIBLE_HASHI_VAULT_ADDR may affect Ansible configuration so its use is not allowed in credentials.

##### ADDITIONAL INFORMATION

It still works with the original environment variable format. But at some point it will not be compatible anymore

**Comment by wenottingham** [comment]
Unfortunately, we can't let custom credentials override ANSIBLE_* variables - there are too many ways a user delegated access to run a particular playbook on a particular inventory could change ansible's behavior to do other things if arbitrary ANSIBLE_* variables are passed.

I've filed an issue with the collection to see if they'll reconsider the deprecation:
https://github.com/ansible-collections/community.hashi_vault/issues/85

**Comment by briantist** [comment]
I've responded in https://github.com/ansible-collections/community.hashi_vault/issues/85 but also see https://github.com/ansible-collections/community.hashi_vault/issues/49 and https://github.com/ansible-collections/community.hashi_vault/issues/10 for more information. I believe we have a way around using Ansible vars (not env vars) that should be introduced before 2.0.0.

Also want to point out that `VAULT_ADDR` is not going to be dropped (even in v2.0.0). See the linked issues for which vars will remain or not, and why.

Happy to continue discussions in those issues!

**Comment by infra-monkey** [comment]
Thank you for the clear answer.
As far as the case is taken into account, i'm good.
Legacy environment will be kept and the extra_vars option is nice.

I hope there will be a global solution found for other plugins that would want to use the ANSIBLE_* environment variables.

**Comment by briantist** [comment]
> I've responded in [ansible-collections/community.hashi_vault#85](https://github.com/ansible-collections/community.hashi_vault/issues/85) but also see [ansible-collections/community.hashi_vault#49](https://github.com/ansible-collections/community.hashi_vault/issues/49) and [ansible-collections/community.hashi_vault#10](https://github.com/ansible-collections/community.hashi_vault/issues/10) for more information. I believe we have a way around using Ansible vars (not env vars) that should be introduced before 2.0.0.
> 
> Also want to point out that `VAULT_ADDR` is not going to be dropped (even in v2.0.0). See the linked issues for which vars will remain or not, and why.
> 
> Happy to continue discussions in those issues!

The changes referenced above have been [released in v1.2.0](https://github.com/ansible-collections/community.hashi_vault/releases/tag/1.2.0).
