### ISSUE TITLE
local_path variable is being retained when changing project type to manual

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#10270]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Editing the source

##### ENVIRONMENT
Browser Used: 
     Google Chrome version 90.0.4430.93 on Mac Catalina

##### STEPS TO REPRODUCE

Project: create a project and choose Manual as the source control credential type. Save the project. Now, click the button to edit the project. Change the source control credential type to Subversion, enter required info, and save. You will notice that the project base path and playbook directory, both which apply to Manual but not to Subversion- still appear on the Details page for the project. 

![local_path](https://user-images.githubusercontent.com/63685497/119566791-8aa9ac00-bd79-11eb-8980-2f24a0a3b13c.gif)

**Comment by nixocio** [comment]
I looked at how we dealt with those changes in the previous UI implementation. It is exactly the same. Once we change from Git to Manual the previous `Playbook Directory` value is displayed as a choice.


<img width="1595" alt="image" src="https://user-images.githubusercontent.com/9053044/123847455-9b06f680-d8e4-11eb-9cd8-641014bb7f2c.png">

The main difference from the previous implementation is the we currently display `Project Base Path` and `Playbook Directory` as part of the details pages for different types of SCM.


<img width="1471" alt="image" src="https://user-images.githubusercontent.com/9053044/123848298-91ca5980-d8e5-11eb-87bc-04dfb7a9ffe0.png">


If I missed something, feel to re-open this issue.
