### ISSUE TITLE
Run job template against a selectable preset of hosts

### ISSUE THREAD

**Issue by themeatcrayon** [ansible/awx#1028]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY
Currently there is no way to run a job template against a subset of hosts in an inventory.
For instance, you can choose which hosts to run an add-hoc command against, But not a playbook.
OR you can run a job template against a predefined inventory - but not select only a portion of that inventories' hosts.
What we would like to do is choose a template to run, select inventory, tick hosts to run (if applicable) and then run the job against only those.

##### ENVIRONMENT
* AWX version: 2.1.13
* AWX install method: docker on linux
* Ansible version:  2.4
* Operating System: RHEL7
* Web Browser: Firefox 57

##### STEPS TO REPRODUCE
Select inventory > select hosts > run command > no option to run job template?
OR
Select portal > select job template > select inventory > no option to select hosts?

##### EXPECTED RESULTS
Select inventory > select hosts > run command > select job > run
OR
Select portal > select job template > select inventory > select hosts > run

##### ACTUAL RESULTS
Feature not currently available.

**Comment by wenottingham** [comment]
You can prompt for a limit to run the job with.

**Comment by themeatcrayon** [comment]
Hi Bill
Ok - I will give that a try

**Comment by themeatcrayon** [comment]
Hi - it seems there is a 1024 character limit on the "Limits" option?

**Comment by jaredevantabor** [comment]
@prinsb I would recommend checking out the docs on [job templates (specifically the section on limits)](http://docs.ansible.com/ansible-tower/2.2.0/html/userguide/job_templates.html) and [patterns](http://docs.ansible.com/ansible/latest/intro_patterns.html) for various strategies on how to group your hosts and define your host-limits. You could create a group and set the limit in the job template to that group. You could even go so far as passing a file with host names as your limit.

**Comment by themeatcrayon** [comment]
@jaredevantabor - thank you - i found extra vars which also works.
