### ISSUE TITLE
Advanced search lookup types forces value to activate search button

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#10283]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Advanced Searches require the Value to be entered before you can search, but we have “Lookup Types” like “isnull” which shouldn’t require a value but the search icon won’t activate unless a value is entered.  Technically “exact” and “iexact” should work with a blank value also, in case you are searching for a blank but not null value.

##### ENVIRONMENT
Chrome Version 90.0.4430.93

![advanced-search](https://user-images.githubusercontent.com/63685497/119690915-1d008d00-be18-11eb-836a-b1b3372416f1.gif)

**Comment by mabashian** [comment]
@akus062381 in your gif you haven't selected a key to search on.  You'll have to select that before the value before the input becomes enabled.

**Comment by akus062381** [comment]
@mabashian thank you!
