### ISSUE TITLE
Sysadmins can edit/delete managed_by_tower=true EE but can't then create new ones

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#10287]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

@jbradberry has more background on this.

Now that sysadmins are allowed to edit and delete `managed_by_tower=true` EE, it stands to reason that they should be able to modify the `managed_by_tower` attribute via the API.

This is necessary to fix your project updates if an overzelous sysadmin deletes all their `managed_by_tower=true` EEs....because if you do that there is no EE left to run project updates with.

##### STEPS TO REPRODUCE

Delete all your `managed_by_tower=true` EE
Run a project update
Everything is broken
Regret what you did
Try and recreate the default EE and set managed_by_tower=true

##### EXPECTED RESULTS

Able to fix mistake

##### ACTUAL RESULTS

Unable to modify `managed_by_tower` attribute via the API -- only way to do it is in `shell_plus`

**Comment by nixocio** [comment]
It would nice to add those changes to the UI also.

**Comment by shanemcd** [comment]
Should we allow this through the API? Or just tell people to re-run `awx-manage register_default_execution_environments`?

**Comment by jbradberry** [comment]
A good question.

**Comment by jbradberry** [comment]
related #10321 #9851

**Comment by jbradberry** [comment]
I think #10378 finishes this up.

**Comment by nixocio** [comment]
The final decision was to not allow the user to delete managed by tower EE. Then there is no need to update the UI.
<img width="1468" alt="image" src="https://user-images.githubusercontent.com/9053044/121432090-3b9e7200-c948-11eb-9486-be3bf469de8a.png">

**Comment by kdelee** [comment]
Now sysadmins can restore the control plane EE which is the only managed_by_tower=True EE via an awx-manage command. Going to close this as we have some other issues tracking other aspects of this
