### ISSUE TITLE
Q: Execution Environment versus Container Group

### ISSUE THREAD

**Issue by DiefBell** [ansible/awx#10296]
== Question ==

##### SUMMARY
There seems to be a lot of overlap between Execution Environments and Container Groups in that they both let you chose your image for running jobs, but it seems like you can't choose to _not_ use an Execution Environment even when using a Container Group. How are they both supposed to be used together and what are the use cases for each?

##### ENVIRONMENT
* AWX version: 18.0
* AWX install method: operator, developer environment
* AWX deployment target: kubernetes (Kurl)
* Operating System: CentOS 7

**Comment by wenottingham** [comment]
The older container groups implementation in earlier AWX:
- you define a container group, which contains both the k8s/OCP cluster to use (and any needed credentials), and the image to use within that cluster to run automation

The current container groups implmentation in AWX:
- you define a container group which contains the k8s/OCP cluster to use (and any needed credentials)
- you define the execution environment to use, which contains the image to use within that cluster to run automation

In essence, the current implementation splits the image spec out so you can just define your cluster to use once, and use it with any execution environment image you need.
