### ISSUE TITLE
awx_web: nginx no permissions to /var/lib/nginx

### ISSUE THREAD

**Issue by dscout87** [ansible/awx#10297]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
No permission to create request body (when body is big) in /var/lib/nginx/tmp/client_body/0000000005

##### ENVIRONMENT
* AWX version: all 17
* AWX install method: docker on linux
* Ansible version:  2.9
* Operating System: linux
* Web Browser: 

##### STEPS TO REPRODUCE
make inventory script using API with body size >= 16kb

##### EXPECTED RESULTS
inventory script created

##### ACTUAL RESULTS
POST /api/v2/inventory_scripts/ HTTP/1.1" 500 186 

##### ADDITIONAL INFORMATION
in container awx_web /var/lib/nginx onwed by root:root and has 770 permissions
to fix it: **docker exec -it awx_web chown nginx /var/lib/nginx**
but its bug and it must fixed in Dockerfile

**Comment by wenottingham** [comment]
This API endpoint has been removed in current AWX, as has the direct docker installation.
