### ISSUE TITLE
Error message in modal broken when deleting Project that is in use from List view

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#10303]
##### ISSUE TYPE
 - Bug Report

##### STEPS TO REPRODUCE

1) Create a project
2) Create JT that uses that project
3) Return to project list view
4) delete the project

##### EXPECTED RESULTS

A modal that warns me that the project is in use

##### ACTUAL RESULTS

Modal comes up, but it has errors

![Screenshot from 2021-05-27 14-18-42](https://user-images.githubusercontent.com/29239279/119877121-a7b7b980-bef6-11eb-9fcc-2112a624825d.png)
![Screenshot from 2021-05-27 14-20-42](https://user-images.githubusercontent.com/29239279/119877221-bf8f3d80-bef6-11eb-87a8-cb82f8814700.png)

**Comment by AlexSCorey** [comment]
We recently upgraded a dependency that should have resolved this issue
![Screen Shot 2021-06-02 at 9 24 57 AM](https://user-images.githubusercontent.com/39280967/120488003-6c007200-c384-11eb-87ef-a33ff63daa0b.png)

**Comment by yagomarques** [comment]
@kdelee @AlexSCorey

i gonna close this issue, I also did the test and it's working, thanks!
![image](https://user-images.githubusercontent.com/18562328/120534546-586efe80-c3b8-11eb-8d37-b871d687593c.png)
