### ISSUE TITLE
Inconsistent host enable/disable feature

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#1030]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- UI

##### ENVIRONMENT
* AWX version: devel

##### STEPS TO REPRODUCE

* Create a host manually
* Add the host to a smart inventory
* Note that you can toggle the active/inactive on the list view.
* Edit the host through the smart inventory

##### EXPECTED RESULTS

* to be able to enable/disable the host

##### ACTUAL RESULTS

* enable/disable host is blocked on the edit screen

##### ADDITIONAL INFORMATION
![9r9fijlbln](https://user-images.githubusercontent.com/722880/35168342-9ab5a9f8-fd26-11e7-9ad6-e948a554fa6a.gif)

**Comment by wenottingham** [comment]
Aren't hosts supposed to be entirely read-only via smart inventory?

**Comment by chrismeyersfsu** [comment]
Smart inventory just points at Hosts. The pointed to host resource can still be modified at `api/v2/hosts/<id>`

Hosts created/sourced from a non-manually created inventory source (dyn inv) we went back and forth at length as to the expected behavior. @wwitzel3 can you chime in.

**Comment by jaredevantabor** [comment]
This is now resolved.
