### ISSUE TITLE
Having a broken symlink anywhere in a project causes the inventory sync to never finish

### ISSUE THREAD

**Issue by DeLoWaN** [ansible/awx#10302]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Having a broken symlink anywhere in a project causes the inventory sync to never finish.

##### ENVIRONMENT
* AWX version: 19.0.1
* AWX install method: awx-operator
* Ansible version:  The one shipped with AWX 19.0.1
* Operating System: kubernetes
* Web Browser: Chrome

##### STEPS TO REPRODUCE

* Having a project (in my case hosted on git) with a broken symlink
* Configure an inventory with source reading this project
* Try to sync this inventory

##### EXPECTED RESULTS

The inventory is sync (or maybe AWX should throw an error if the broken symlink is in the inventory files).

##### ACTUAL RESULTS

The inventory sync get stucks in "running" for ever. There are no logs messages on the job.

Here is an extract from the aws-task container:

```
2021-05-27 15:37:01,302 DEBUG    [cbcb8555975d432585b0e7b688578f44] awx.analytics.job_lifecycle inventoryupdate-49 running playbook
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2972, in transmit
    ansible_runner.interface.run(streamer='transmit', _output=_socket.makefile('wb'), **self.runner_params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/ansible_runner/interface.py", line 249, in run
    r.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/ansible_runner/streaming.py", line 53, in run
    stream_dir(self.private_data_dir, self._output)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/ansible_runner/utils/streaming.py", line 20, in stream_dir
    archive.write(os.path.join(dirpath, fname), arcname=os.path.join(relpath, fname))
  File "/usr/lib64/python3.8/zipfile.py", line 1740, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "/usr/lib64/python3.8/zipfile.py", line 522, in from_file
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pdd_wrapper_49_zpjpzf3o/awx_49_vee8to_0/project/files/openvpn/nynas/ccd'
```

##### ADDITIONAL INFORMATION

It might be the same root cause as https://github.com/ansible/awx/issues/9952.

**Comment by wenottingham** [comment]
adding @sarabrajsingh since they're looking at the other linked issue

**Comment by sarabrajsingh** [comment]
could be related to #9952 - will investigate

**Comment by AlanCoding** [comment]
This is absolutely impacted by https://github.com/ansible/ansible-runner/pull/713

This test case should probably go on the testing agenda, but I do not think it is expected to fail anymore.

(after we bump versions, which should happen soon)

**Comment by yagomarques** [comment]
### It's working, we tested manually;

- [project](https://github.com/ansible/test-playbooks/tree/symlink-test)
- [broken symlink: ](https://github.com/ansible/test-playbooks/blob/symlink-test/symlink)

### project on awx:
![image](https://user-images.githubusercontent.com/18562328/121952555-cb6e6280-cd32-11eb-85a4-441396f9a2c2.png)


### Job:
![image](https://user-images.githubusercontent.com/18562328/121952430-95c97980-cd32-11eb-85d4-6e0f9a254461.png)
#### output
```
ok: [localhost]
TASK [Repository Version] ******************************************************
ok: [localhost] => {
    "msg": "Repository Version 5b4ca3cf25bdae7f5ef617c6255e7454bbf6cdd0"
}
PLAY [Install content with ansible-galaxy command if necessary] ****************
TASK [Check content sync settings] *********************************************
skipping: [localhost]
TASK [meta] ********************************************************************
skipping: [localhost]
TASK [fetch galaxy roles from requirements.(yml/yaml)] *************************
TASK [fetch galaxy collections from collections/requirements.(yml/yaml)] *******
[WARNING]: Unable to find '/var/lib/awx/projects/_6__demo_project/collections'
in expected paths (use -vvvvv to see paths)
PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
