### ISSUE TITLE
AWX-CLI can't edit CUSTOM_ENV_PATHS

### ISSUE THREAD

**Issue by BrandonALXEllisSS** [ansible/awx#10312]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 17.1.0
* AWX install method: Install Playbook on K8 Cluster
* Ansible version: 2.9.18
* Ansible CLI version: 19.1.0, also tried 17.1.0

##### STEPS TO REPRODUCE

Try modifying the "CUSTOM_VENV_PATHS" property using the awx cli.
i.e. `awx setting modify CUSTOM_VENV_PATHS "['/opt/custom/venv/']"`

##### EXPECTED RESULTS

CUSTOM_VENV_PATHS updates to the new specified value

##### ACTUAL RESULTS

Nothing updates, the error is returned: `{"CUSTOM_VENV_PATHS": ["Expected list of strings but got <class 'str'> instead."]}`

##### ADDITIONAL INFORMATION

Related: https://github.com/ansible/awx/issues/9767
Note: Using the old tower-cli and basic REST API via curl still work. It's just the awx-cli that fails.

**Comment by shanemcd** [comment]
Hello, custom virtual environments have been removed in newer versions of AWX. Please use the version of the CLI that matches your version of AWX.
