### ISSUE TITLE
Expose the output of the EE resolver in the job template detail

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#10327]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Expose the output of the EE resolver in the job template detail. See API issue: https://github.com/ansible/awx/issues/10210

**Comment by shanemcd** [comment]
@nixocio Are you actively working on this one? If so, can you move to in_progress?

**Comment by nixocio** [comment]
@shanemcd , not yet.

**Comment by nixocio** [comment]
Already done.
