### ISSUE TITLE
Ad-Hoc Commands credential list should just be machine creds

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#1032]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

- UI

##### SUMMARY
To run an Ad-Hoc command you have to select a machine credential. The pop-up to select a Credential includes ALL the credentials with no indication as to which ones are machine credentials.

So why not list machine credentials only?

##### ENVIRONMENT
* AWX version: devel

##### STEPS TO REPRODUCE

* Create a few credentials (at least one that isn't a machine cred)
* Run an ad-hoc command

##### ADDITIONAL INFORMATION

![heognsthny](https://user-images.githubusercontent.com/722880/35171832-248a65e0-fd33-11e7-8824-22257b045f41.gif)

**Comment by wenottingham** [comment]
Since other types aren't supported, marking as bug.

**Comment by jaredevantabor** [comment]
This is fixed in devel.
