### ISSUE TITLE
filter_plugins not working. in the custom EE image

### ISSUE THREAD

**Issue by vishnubraj** [ansible/awx#10330]
I build my AWX EE image because I needed to use a specific python package.  followed the steps in https://weiyentan.github.io/2021/creating-execution-environments/  . I copied my ansible-playbook folder to the container locally and ran the playbook and it worked fine. But when I use the container in AWX as Execution Environment and run the playbook, it says the
```
"AnsibleError: template error while templating string: no filter named 'nat_sorted'.
```
is it because the playbook not able to find the filter_plugins folder?
I have the folder path as mentioned below. is it due to the filter_pluugins folder path? where did it suppose to be there in AWX? Please help

```
playbooks/...
inventory
host_vars/...
group_vars/...
filter_plugins/...
```

**Comment by sivel** [comment]
You haven't provided much information for us to properly understand what you are doing.  However, it appears as though all of your playbook files are in the `playbooks/` dir, and then you have a `filter_plugins/` directory at the same level.  Ansible will automatically look for a `filter_plugins/` directory that is adjacent to a playbook _file_.

So unless you set an explicit configuration to point to your `filter_plugins/` directory, and will never know about it.  The other option is to move the `filter_plugins/` directory into the `playbooks/` directory.  I might also recommend making use of creating a collection to hold your custom plugins, as that may make dealing with execution environments easier in the long run.

**Comment by vishnubraj** [comment]
Thanks @sivel 

initially i solved this by copying the filter_plugins content to "/usr/share/ansible/plugins/filter/"
That fixed the issue.

Now I moved the filter_plugins under the playbooks directory to fix it.

my directory structure is like below now.

```
playbooks/filter_plugins/...
inventory
host_vars/...
group_vars/...
```
