### ISSUE TITLE
job event optimization - Do not null job event relationship when deleting

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#10337]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
There is a relationship from job_event -> host. This relationship is nulled when a host is deleted. The relationship is also updated when inventory is deleted. This can be an expensive operation. We should try and remove it. Related https://github.com/ansible/awx/issues/10331

### TODO Investigate
- [ ] From a technical perspective. Does this relationship need to be consistent?
- [ ] From a product perspective. What user-facing (i.e. UI or even API) features rely on this relationship being consistent? For example, do we do any queries that count or look at the last failed event for an inventory that changes when/if a related host' job events are deleted?

https://github.com/ansible/awx/blob/devel/awx/main/tasks.py#L741 Consider can/how to remove this. Even if we don't remove this, it seems inefficient to do this the way we are. Surely we do not need to loop over each host to perform the update.
https://github.com/ansible/awx/blob/devel/awx/main/models/events.py#L467 `on_delete=models.SET_NULL,` -> do nothing
https://github.com/ansible/awx/blob/devel/awx/main/models/events.py#L743 `on_delete=models.SET_NULL,` -> do nothing

**Comment by AlanCoding** [comment]
I believe this would address what happened here as well https://github.com/ansible/awx/issues/12176

Would also address slow host deletions described in https://github.com/ansible/awx/issues/12277... probably

I think I filed a duplicate issue with this, I'm looking for it.

**Comment by AlanCoding** [comment]
I wrote down some notes on the error related to this at https://gist.github.com/AlanCoding/b9919c1b1ebbb9ee6b5be2a584362200

**Comment by AlanCoding** [comment]
I keep failing to accurately search for this issue, because the exact syntax of models.DO_NOTHING was not used. Hopefully that is resolved now.

edit: DO_NOTHING

**Comment by AlanCoding** [comment]
Closing as @john-westcott-iv's merge appears to address this.
