### ISSUE TITLE
[Question] Why not use helm to install AWX in kubernetes instead of awx-operator

### ISSUE THREAD

**Issue by mo-saeed** [ansible/awx#10340]
This is just a question.

I am wondering why it was decided to create a separate application (awx-operator) to install AWX in kubernetes although we have official and easy way using helm for installing software on Kubernetes, are there any reasons why it was decided to go with this approach ?

Now to install AWX is more pain for us than before (with the installer directory in awx repo), now I need to install another application in my cluster just to install AWX. the problem is that awx-operator in really early stage and to deploy it we need to change things manually to have just the application started properly in our k8s cluster https://github.com/ansible/awx-operator/issues/360

Thanks a lot in advance

**Comment by matburt** [comment]
This fits in better for us when targeting deployments via operatorhub.

**Comment by mo-saeed** [comment]
I understand it fits better for you, but I believe it should also fit better for the end-users to have smoother installation of ansible-awx without pain by following the standards for deploying applications in kubernetes.

**Comment by shanemcd** [comment]
@mo-saeed We don't have a big enough team to maintain tooling that we don't use ourselves. Anyone is free to create and maintain their own AWX helm chart if they want.
