### ISSUE TITLE
job event cleanup - Drop unpartitioned table when empty.

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#10341]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
With the introduction of partitioned job event tables we keep the "old" unpartitioned job events via renaming the tables `main_jobevent` --> `_unpartitioned_main_jobevent`. Jobs that were ran before the partition migration are still accessible through this table. Cleanup jobs still take action on this table. Eventually, the old unpartitioned job events table will become empty. BUT, without a postgres full vacuum the storage will not be returned to the OS ("normal" autovacuum will only make the space available within the same table). As a nicety we should drop the old unpartitioned job events table when it becomes empty. The check for "is the table empty" must be done with care because counting the table can be expensive. Also note that code and queries may still rely on this table existing. There are two design decisions to be made (1) how and when to check if the unpartitioned table(s) are empty. (2) How to "drop" the old tables.

1a. (idea from @Ladas) After a cleanup job, if no jobs are cleaned up we can presume that the number of job events in the unpartitioned table is low. Do a count to verify. The counter argument to this, maybe the customer runs a cleanup for jobs older than 31 days and they have many unpartitioned jobs in the last 30 days. In this case, the count will still be very expensive.
1b. Maybe we get an approximate count and if it's < some number we can assume it's safe to do an absolute count `SELECT reltuples::BIGINT AS approximate_row_count FROM pg_class WHERE relname = 'job_events_fk'`
1c. Some other clever query i.e. `LIMIT 1` or a query on `pg_relation_size` `pg_table_size` to answer the question "Is there at least 1 record remaining?" if so, we know we can't drop the table.

2a.  Return disk space to customer via (in a single transaction) rename empty unpartitioned table(s), create new, empty table place of the renamed table, drop renamed table. This will require no (little) change to existing code.
2b. Return disk space to customer via dropping empty unpartitioned table(s). Modify code to deal with unpartitioned table(s) existing or not existing.
2c. In a future release, we may declare that "ok, all old job events should have been cleaned up by now". In this case, we delete all code that deals with old unpartitioned job events table(s) & drop the tables.

**Comment by DLV1810** [comment]
Having just hit this issue myself, why can't the cleanup mgmt jobs look for this table and delete old records based on the retention time until its empty? - The logic should already be there from AAP 1.2 (Tower 3.8.6) just add task to the cleanup job and update the table names it references? eventually the table will have 0 records

2c isn't very desirable - as you're making the assumption everyone has migrated to the new platform.

**Comment by AlanCoding** [comment]
The solution I have up takes the maximum `created` timestamp and drops the whole table if its older than the cleanup cutoff time. This avoids a lot of the technical discussion in the post here, because it's an indexed field, this should be efficient in any case. Then if this criteria is met there's no reason to keep the table around in any form.

**Comment by AlanCoding** [comment]
Closing as done
