### ISSUE TITLE
RFE: Username/Password for Proxy Environment Vars need to be masked in UI

### ISSUE THREAD

**Issue by hiyokotaisa** [ansible/awx#10352]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Currently, we need to specify extra environment variables for proxy configuration with username/password in plaintext as below:
```
{
HTTP_PROXY=http://username:password@proxy:8080
HTTPS_PROXY=http://username:password@proxy:8080
}
```

All of System Administrators are able to see that configuration in `Settings > Jobs > Extra Environment Variables`, which does not fit some use-cases, so it would be great if we have an option that redacts username/password.

**Comment by wenottingham** [comment]
This is akin to extra_vars on a job template, in that from the controller's perspective, we have no idea what may or may not be a secret - it's just data without any structure.

We're unlikely to do this.
