### ISSUE TITLE
Request loop trying to add users to a team

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#10350]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
This may be introduced by https://github.com/ansible/awx/commit/fef24355abd445312b4c939ea257bad8906540ff

##### STEPS TO REPRODUCE

1- Create a team
2- Go to Access tab for this team and try to add a user

https://user-images.githubusercontent.com/12464858/120703102-4316d480-c48b-11eb-8448-7e135a22a84d.mp4

**Comment by mabashian** [comment]
I'm not sure how/why but I think this came in with this commit https://github.com/ansible/awx/commit/fef24355abd445312b4c939ea257bad8906540ff
