### ISSUE TITLE
Wrong text in Missing Resource tooltip for Job Details/Jobs List

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#10355]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 19.1
* AWX install method: docker for mac
* Operating System:Mojave
* Web Browser:Chrome

##### STEPS TO REPRODUCE

Create a job template the uses an execution environment.  Run job.  delete execution environment

##### EXPECTED RESULTS

See below.
The `Missing resource` text appears but with the correct tooltip

##### ADDITIONAL INFORMATION

![image (1)](https://user-images.githubusercontent.com/39280967/120804756-05f62500-c513-11eb-96a1-b79a1166c634.png)

**Comment by akus062381** [comment]
https://github.com/ansible/tower-qa/pull/6423
issue resolved
