### ISSUE TITLE
Limits don't work in workflow on 19.1.0

### ISSUE THREAD

**Issue by chapai518** [ansible/awx#10353]
ISSUE TYPE
Bug Report
SUMMARY
Limits don't work in workflow
Limits work when launching individual templates, but do not work when launched in workflow

ENVIRONMENT
AWX version: 19.1.0
Operator version: 0.9.0
Kubernetes version: Openshift 4.6.26
AWX install method: openshift

STEPS TO REPRODUCE
create a workflow -
add a template specifying one host from the inventory -
start the workflow
as a result, the job is performed on all hosts in the inventory, there is no limits field in the description of the running job.
EXPECTED RESULTS
correct work of limits in workflow

ACTUAL RESULTS
limits work when launching individual templates, but do not work when launched in workflow

ADDITIONAL INFORMATION
I tried redeploying the AWX pods and restarting the database, it doesn't help.
The database was migrated by creating a secret according to the instructions, after updating the operator from 0.7.0 to 0.9.0 and then redeploying AWX to update from 18.0.0 to 19.1.0.
Prior to the update, this issue did not exist.

**Comment by nixocio** [comment]
Hello @chapai518 , this issue seems to be the same as https://github.com/ansible/awx/issues/9241 that was addressed on 19.2.0.
