### ISSUE TITLE
Changing filters on dashboard chart reloads most of the page

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#10356]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Changing the filter on the dashboard chart should only cause the dashboard chart to reload, not the counts at the top of the page.

##### STEPS TO REPRODUCE
- navigate to dashboard page
- change the filters on the dashboard chart

##### EXPECTED RESULTS
- only the chart reloads

##### ACTUAL RESULTS
- the chart *and* the counts at the top of the page, breadcrumbs, etc. reload

##### ADDITIONAL INFORMATION
![dash_reload](https://user-images.githubusercontent.com/9753817/120809647-4c01b780-c518-11eb-9bd2-23f8ec9385ee.gif)

**Comment by tiagodread** [comment]
Fixed with #10349
