### ISSUE TITLE
Give job templates (and other models) a slug

### ISSUE THREAD

**Issue by anlutro** [ansible/awx#1035]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
When setting up job template callbacks, I'm tightly coupling the curl command with the primary key of the job template I want to run. This is annoying because ideally I'd want to re-create the AWX database from scratch without anything breaking.

It would be nice if I could optionally specify a "slug" for a job template, which could then be used in place of the PK in the callback URL. For example:

    curl --data "host_config_key=..." https://awx.example.local/api/v2/job_templates/my-template/callback/

**Comment by ryanpetrello** [comment]
@anlutro I think what you're looking for might already exist in awx :)

If you visit a Job Template in the API, look for its `named_url` property, which is based on the name you give it:

`https://awx.example.local/api/v2/job_templates/5/`

```json
{
    "id": 5,
    "type": "job_template",
    "url": "/api/v2/job_templates/5/",
    "related": {
        "named_url": "/api/v2/job_templates/Demo Job Template/",
    ...
}
```

`curl --data "host_config_key=..." https://awx.example.local/api/v2/job_templates/Demo Job Template/callback/`

**Comment by anlutro** [comment]
Ah, nice, thanks!
