### ISSUE TITLE
Default Execution Environment not being update on settings page after EE deletion

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#10363]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Default Execution Environment not being update on settings page after EE deletion. 

##### STEPS TO REPRODUCE

1. Create a new EE
2. Go to settings page - Set as Default Execution Environment
3. Delete the EE from the step 1.
4. Id of the EE remains on the settings page.

##### EXPECTED RESULTS

Settings to be updated as per the EE deletion.

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/9053044/120859402-242f4580-c552-11eb-96ac-a20b87b20cd0.png)

![image](https://user-images.githubusercontent.com/9053044/120859429-2e514400-c552-11eb-9222-082c0d8e1745.png)

**Comment by yagomarques** [comment]
It's working, tested manually   :heavy_check_mark: 

Before delete: 
![image](https://user-images.githubusercontent.com/18562328/121940551-9e1ab800-cd24-11eb-9a95-f23b8e303f62.png)

After delete:
![image](https://user-images.githubusercontent.com/18562328/121940810-e20dbd00-cd24-11eb-8c03-d6917b3be59e.png)
