### ISSUE TITLE
Bring back ROOT GROUPS view

### ISSUE THREAD

**Issue by weiyentan** [ansible/awx#10367]
##### ISSUE TYPE
 -Root Groups View in Inventory

##### SUMMARY
Can this be brought back? Root group view existed in 12 where we could  transverse the inventory where it was easily viewable. Now we can't foreseeable way to see the inventory hierarchy in AWX 19.2

**Comment by nixocio** [comment]
hello @weiyentan, the root groups is a filter now.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/9053044/121703535-f17cd400-caa0-11eb-8a46-7603ee879403.png">
