### ISSUE TITLE
How to install AWX 19.2 using the ansible awx image from quay.io

### ISSUE THREAD

**Issue by nathanlin24** [ansible/awx#10369]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME

 - Installer

##### SUMMARY

Hi, is there a documentation on how to install AWX 19.2.0 using the Docker Compose method and the [ansible awx image from Quay.io](https://quay.io/repository/ansible/awx)? Thanks.

##### ENVIRONMENT
* AWX version: 19.2.0
* AWX install method: Docker Compose developer environment
* Operating System: RHEL8
* Web Browser: Chrome

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A

##### ADDITIONAL INFORMATION
N/A

**Comment by jheinitz** [comment]
Hello!

Good question. I tried it on my own, but I failed. I built my docker image locally using "make docker-compose-build" and run this image with docker-compose. Maybe the other people from the awx bubble have an idea.

Best regards

Jens

**Comment by wenottingham** [comment]
The legacy docker-compose installation method has been removed. The current docker-compose method is only for development, and works with building the image locally (not using the awx image).

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

Mailing list: https://groups.google.com/forum/#!forum/awx-project
IRC: ansible-awx on irc.libera.chat
