### ISSUE TITLE
Enable support for encrypted fields in Postgresql

### ISSUE THREAD

**Issue by tuxonfire** [ansible/awx#10374]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

  Functionality to support encrypted fields.

**Comment by wenottingham** [comment]
We already encrypt any sensitive fields (passwords, tokens, keys, etc) via non-Postgres methods at the application level, and have since the app's start. See https://docs.ansible.com/ansible-tower/latest/html/administration/secret_handling.html for technical details.
