### ISSUE TITLE
Workflow template- details tab shows missing EE resource when not required

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#10399]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When creating a workflow job template, the only field required is the name field. But when the workflow is launched, and the user views the details tab of that job, the EE shows as a missing resource for the WFJT. I then went back to my WFJT, and edited and assigned a specific EE. I then launched the WFJT again. In the job details page, the EE still showed as a missing resource, even though when the user looks at the template itself, it shows the EE that you assigned when you edited the template.

##### STEPS TO REPRODUCE

1. Create a WFJT. Only fill in required fields, leave all others blank.
2. Access the visualizer tab of the WFJT and add one node with a JT. Save.
3. Access the schedules tab of that same WFJT and create a schedule to run the WFJT. 
4. Access the Jobs list and wait until the job is triggered and finishes. Expand that job's hidden details line. You will see the warning icon next to the EE saying it is missing. Then click into that job's details page, and next to EE you will see Missing Resource. 

##### EXPECTED RESULTS

The WFJT should have the default EE assigned to it if the user doesn't pick one. Especially with it not being a required field.

##### ACTUAL RESULTS

User has the option not to associate an EE when creating a WFJT, and when they look at the job results after that template launches a job, it shows there is a missing resource.
Even if the user does designate a specific EE for the WFJT, the job details page still shows the EE as a missing resource.
##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/63685497/121250949-530c2b00-c874-11eb-88a7-28e6b6f7f9d0.png)
Launch this workflow, and visit the details screen for that job:
![image](https://user-images.githubusercontent.com/63685497/121251083-7931cb00-c874-11eb-9198-f57dc75d5acf.png)

**Comment by nixocio** [comment]
There is a new field `resolved_environment` that will display what execution environment will be used to run this job, even the execution environment was not explicit selected when creating the workflow, for example. This one seems to a replacement for this missing execution environment.

```
        "resolved_environment": {
            "id": 2,
            "name": "Control Plane Execution Environment",
            "description": "",
            "image": "quay.io/ansible/awx-ee:0.3.0"
        },

```

See: https://github.com/ansible/awx/issues/10327

I will attempt to solve both issues.

**Comment by nixocio** [comment]
I talked with @jbradberry about this issue, the issue is that job output for workflow job template does not have the execution environment field set to whatever EE was used to the execute the WFJT template itself.

<img width="1455" alt="image" src="https://user-images.githubusercontent.com/9053044/121576607-8971b380-c9f6-11eb-9fdc-9f8c6293a0d7.png">

**Comment by AlanCoding** [comment]
@nixocio I've only just now taken stock of this issue.

Showing the "Missing resource" warning when a workflow job does not have an EE sets an expectation that all jobs / inventory updates that run inside of a workflow share the same EE. This is not the case. If a JT has an EE set, then the workflow will not override that. Precedence is that the workflow's EE comes after the template's EE (either JT or inventory source), then project, organization, inventory's organization, and then the global default EE logic.

It would be _most_ common practice to not set the WFJT EE.

I really think the UI shouldn't show "Missing resource" when a workflow job doesn't have `execution_environment`

**Comment by nixocio** [comment]
@AlanCoding, thanks for your comment.  `Missing resource` it was supposed to be shown once  a previous existent/used EE was deleted - mainly for jobs already executed. It seems like the best option is to remove the EE field from Work Flow Jobs.

**Comment by nixocio** [comment]
Work completed.
