### ISSUE TITLE
Canceled job- icon visual continuity

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#10391]
Feature Idea

##### SUMMARY
I noticed in the UI, that the little icon on the details and output pages showing a job failed is the exact same for if a job was canceled.
But, on the jobs list page, a canceled job shows as a yellow warning triangle.
I feel like some visual continuity is missing here.

My suggestion is to have the yellow triangle icon that appears next to a canceled job on the jobs list also be the icon that appears for a canceled job on that job's detail page and output page (instead of the failed job icon)

Here is a canceled job on the details page or output page of a job:
![image](https://user-images.githubusercontent.com/63685497/121199790-360a3480-c841-11eb-962e-53191f97867b.png)

Here is a canceled job on the jobs list page:
![image](https://user-images.githubusercontent.com/63685497/121199872-47534100-c841-11eb-983d-5672f109e025.png)

**Comment by mabashian** [comment]
This will be covered in https://github.com/ansible/awx/issues/10496
