### ISSUE TITLE
Update instance groups to reflect distinct controlplane instance group 

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#10396]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Update instance groups to reflect distinct control plane instance group. Right now we do not allow the instance group named `tower` to be edited. Probably we will need to fetch those names from settings endpoint.

API work: https://github.com/ansible/awx/pull/10324

**Comment by akus062381** [comment]
resolved

**Comment by AlexSCorey** [comment]
@jakemcdermott can we close this?

**Comment by tiagodread** [comment]
This is now implemented
