### ISSUE TITLE
Smart Inventory Edit does not fetch new changes before redirect to Smart Inventory Details

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#10407]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Smart Inventory Edit does not fetch new changes before redirect to Smart Inventory Details.

1. Create a smart inventory, named foo.
1. Modify a smart inventory name to bar.
2. It will be redirect to the smart inventory details page with name from step 1. Refresh the page to get the latest changes.

New data needs to be fetched before redirect.

**Comment by wenottingham** [comment]
Is this only for smart inventories or for lists in general?

**Comment by nixocio** [comment]
> Is this only for smart inventories or for lists in general?

smart inventory only

**Comment by tiagodread** [comment]
Fixed
