### ISSUE TITLE
Advanced search by groups not working in hosts list

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#10400]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
While working on https://github.com/ansible/awx/issues/9232 I realized that the user can not use the OR operator with the key `Groups` the host_filter is not adding `or__`  I've found this in host lists, however, this may happen in other places with different keys.

##### STEPS TO REPRODUCE

1. Go to host list
2. Do an advanced search using the key `Groups` type the name of the group

##### EXPECTED RESULTS

To list all hosts within the group

##### ACTUAL RESULTS

The OR operator is not defined and the user can't filter by groups using advanced search

![image](https://user-images.githubusercontent.com/12464858/121255680-12b3a980-c882-11eb-8c13-036a8eee8e43.png)

this issue was reported here initially https://github.com/ansible/awx/issues/9389
Note that https://github.com/ansible/awx/pull/10347 is not addressing this.

**Comment by mabashian** [comment]
OK so this is pretty complicated and touches https://github.com/ansible/awx/issues/7834.  I think I'd like to propose a simplification of this interface under certain circumstances.  In the case of the host list there are a number of `related_search_fields` that are listed in the `Lookup Type` dropdown.  These fields can be searched on but only in two ways:

1) Directly `groups=1`
2) Via the search modifier `groups__search=somestring`

As best as I can tell, these keys do not support a prefix (and/or/not) when using the search modifier _and_ we don't currently support directly querying these fields (see item 1).

So, my proposal is to clear/disable the `Set Type` and `Lookup Type` dropdowns whenever one of these  `related_search_fields` is selected.  This way, users don't think that they can apply modifiers to these search keys (the UI is basically ignoring these fields for these fields at this point - it just uses the search modifier every time):

![adv_search](https://user-images.githubusercontent.com/9889020/121391645-9d48e700-c91c-11eb-9027-cf989475152a.gif)

Also of note: it seems like the default behavior is for these values to be `or`'d when you have multiple:
`groups__search=foo&groups_search=bar` returns hosts in `foo` or in `bar`.

So here's what the interface will look like when you select a related search key:

<img width="1393" alt="Screen Shot 2021-06-09 at 1 20 03 PM" src="https://user-images.githubusercontent.com/9889020/121400298-6b884e00-c925-11eb-9da2-9fcfc345f585.png">

but these fields will be enabled for search keys which can use them (ie non related search keys).

**Comment by mabashian** [comment]
Note that the actual implementation ended up being slightly different than the above comment.  See #10416

**Comment by tiagodread** [comment]
With #10416 now is possible use OR filters and create smart inventories
