### ISSUE TITLE
Inventory source first sync error

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#10411]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
First inventory source first sync error

##### STEPS TO REPRODUCE
1. Create a new inventory source - Sources - Sourced from a project.
<img width="1456" alt="image" src="https://user-images.githubusercontent.com/9053044/121542913-85359e00-c9d6-11eb-81c8-fb33b50f225d.png">
2. It will be redirect to 

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/9053044/121543539-fd9c5f00-c9d6-11eb-9cc7-cae122f5f87c.png">

3. Click `Sync`.
4. Immediately click `Back to Sources`
5. Error - That seems to occur just on the first ever sync of the the sources.

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/9053044/121543787-32a8b180-c9d7-11eb-956e-52fe160558ab.png">

**Comment by akus062381** [comment]
resolved
