### ISSUE TITLE
Hide user type field for users different than system admin

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#10427]
##### ISSUE TYPE
Disable User Type field for non system admin.

##### SUMMARY
If the the user is not system admin, we should hide the user type field.

Logged in as normal user.

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/9053044/121712795-1cb7f100-caaa-11eb-8613-bef706f038eb.png">

<img width="1449" alt="image" src="https://user-images.githubusercontent.com/9053044/121712718-0ca01180-caaa-11eb-99e5-85e289f68fc6.png">

**Comment by akus062381** [comment]
resolved
