### ISSUE TITLE
Run an Ansible Tower workflow serially

### ISSUE THREAD

**Issue by tuxonfire** [ansible/awx#10437]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Specify a workflow to execute an inventory serially without having to manually input the limit.

**Comment by wenottingham** [comment]
This is not something we'd do in this way - to do this in the existing ansible framework would be to spawn 100 workflows for a 100-node job, and the ansible-playbook execution engine can't be extracted enough to run it this way.
