### ISSUE TITLE
Expose read-only custom credential types to normal users in the UI

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#10432]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
I _think_ `/api/v2/credential_types` is available to all users to GET.  This means that we could expose the list/details for custom credential types to all authenticated users.  Some users won't be able to add custom credential types so we'll have to make sure we're hiding that button for those users.  Same with the edit button(s).

AFAIK this did not exist in the old UI.

**Comment by nixocio** [comment]
This one should be addressed once #4426 is resolved.
