### ISSUE TITLE
Validate Execution Environment `image` field

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#10431]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX should validate the image name (could have a tag) given for an Execution Environment.

##### STEPS TO REPRODUCE

Create an Execution Environment, and give it 🔥 for the image

![Screenshot from 2021-06-11 13-50-57](https://user-images.githubusercontent.com/1385596/121729115-1894cf00-cabc-11eb-876b-6c7d1091623a.png)

Launch the Demo Job Template

##### EXPECTED RESULTS

Demo Job Template runs

##### ACTUAL RESULTS

job fails with

> Error: invalid reference format

##### ADDITIONAL INFORMATION

https://docs.docker.com/engine/reference/commandline/tag/#:~:text=A%20tag%20name%20must%20be,a%20maximum%20of%20128%20characters.

> A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.

**Comment by fosterseth** [comment]
images can also be pulled by digest

`quay.io/fosterseth/awx-ee@sha256:cbb1256806ea16762ea157bfe52578070b900b607780eca196f57838dd2d7eff`

something to keep in mind

**Comment by AlanCoding** [comment]
For a first pass, I'd probably give up on the "128 characters" restriction too.

**Comment by yagomarques** [comment]
It's working, we ran it manually:

i got a 400 error as expected with the message:
![image](https://user-images.githubusercontent.com/18562328/122598379-2231b000-d043-11eb-8b34-cd71f6a35a3d.png)

UI is correctly displaying the error too:
![image](https://user-images.githubusercontent.com/18562328/122598102-c6672700-d042-11eb-9ce6-90ff16037c26.png)
