### ISSUE TITLE
Expose read-only applications to normal users in the UI

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#10433]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
I _think_ `/api/v2/applications` is available to all users to GET.  This means that we could expose the list/details for applications to all authenticated users.  Some users won't be able to add applications so we'll have to make sure we're hiding that button for those users.  Same with the edit button(s).

AFAIK this did not exist in the old UI.

**Comment by nixocio** [comment]
This one should be addressed once https://github.com/ansible/awx/issues/4426 is resolved.
