### ISSUE TITLE
Ad hoc command details does not show the module name

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#10440]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Launch an ad hoc command that runs the ping module. View the details in the UI.

![Screenshot from 2021-06-14 10-48-57](https://user-images.githubusercontent.com/1385596/121912115-4a957380-ccfe-11eb-95af-fb56623e1a7a.png)

At first, I was confused, because I thought I ran the "ping" module, not the "command" or "shell" modules. Then I see that the UI's meaning is that it was an ad hoc _command_.

However, the page gives no indication anywhere that I ran the "ping" module.

It should also probably show the module arguments. If I run a command that does `echo "Hello world"`, then I need to know:

 - that I ran the `command` module
 - the args passed to it (so I know why it printed "Hello world")

Otherwise, there's nothing to connect this job entry with the function of what actually happened.

**Comment by akus062381** [comment]
resolved
