### ISSUE TITLE
The Inventory File field in Inventories / Source is read only

### ISSUE THREAD

**Issue by milodanlso** [ansible/awx#10450]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
It is impossible to enter a file within the imput

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser: Chrome, Edge

##### STEPS TO REPRODUCE

Go to
![image](https://user-images.githubusercontent.com/52068250/122034383-c2809e00-cdd1-11eb-9ab5-1219d61abae1.png)

##### EXPECTED RESULTS

Be able to enter a path that is not offered 

##### ACTUAL RESULTS

It is impossible to enter a file within the imput as indicated in the help

##### ADDITIONAL INFORMATION

Subsidiary question: how is the proposed list updated and on what criteria? I did several tests and the list is not always updated

**Comment by AlexSCorey** [comment]
@milodanlso Thanks for reaching out.  If you upgrade to 19.1.0 you can type any file name inside this field and that change was brought in by this [PR](https://github.com/ansible/awx/pull/9120)

**Comment by milodanlso** [comment]
I'm not really ready to switch to a version without docker. Is it not possible to have a patch (I guess I'm dreaming)?

**Comment by AlexSCorey** [comment]
We may be able to offer a patch in the future, but right now the best I can offer is to re-sync the project to get all updated files represented in the dropdown.

**Comment by wenottingham** [comment]
Closing as this is fixed in the latest release.
