### ISSUE TITLE
Using job_metadata attribute in custom webhook notification body results in blank body

### ISSUE THREAD

**Issue by dsmaugy** [ansible/awx#10452]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

I have a webhook notification with a custom body for successful/failed runs:
```
        "success": {
            "message": "",
            "body": "{\"type\": \"{{ job.job_type }}\", \"changed\": \"{{ job.host_status_counts.changed | default(0) }}\", \"name\": \"{{ job.name }}\", \"url\": \"{{ url }}\", \"status\": \"{{ job.status }}\", \"ok\": \"{{ job.host_status_counts.ok | default(0)}}\", \"failed\": \"{{ job.host_status_counts.failures | default(0) }}\"}"
        }
```

This works fine. If I add `\"metadata\": \"{{ job_metadata }}\"` to the body however, notifications end up being blank.

```
        "success": {
            "message": "",
            "body": "{\"type\": \"{{ job.job_type }}\", \"changed\": \"{{ job.host_status_counts.changed | default(0) }}\", \"name\": \"{{ job.name }}\", \"url\": \"{{ url }}\", \"status\": \"{{ job.status }}\", \"ok\": \"{{ job.host_status_counts.ok | default(0)}}\", \"failed\": \"{{ job.host_status_counts.failures | default(0) }}\", \"metadata\": \"{{ job_metadata }}\"}"
        }
```

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: kubernetes
* Ansible version:  X.Y.Z
* Operating System: macOS
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create a webhook notification template that uses the `"{{ job_metadata }}"` attribute somewhere in the body.

##### EXPECTED RESULTS

The message notification to successfully return the correct notification along with the `"{{ job_metadata }}"` info

##### ACTUAL RESULTS

A blank notification is returned

##### ADDITIONAL INFORMATION

Possibly related to https://github.com/ansible/awx/issues/9168?

**Comment by dsmaugy** [comment]
EDIT: It seems like this issue is related to specific characters present within the `job_metadata` string. The string itself is successfully generated as `"metadata": "{{  job_metadata is string }}"` `"metadata": "{{  job_metadata | length }}"` return `True` and a sensible number respectively (escape sequences omitted for clarity).

I can even print out certain substrings by splicing the original `job_metadata` variable. 
For example, one run I had: 
```
"metadata": "{{  job_metadata[38:49] }}"
```
which resulted in a notification of `'metadata': 'st Template'`. My template name is "Fast Test Template" so I think that's what that splice was trying to say.

When I tried extending the splice to `{{  job_metadata[38:50] }}`, the notification was blank again. I think that character should be a single quotation mark seeing as how the metadata variable is a json string.

Maybe AWX is having trouble escaping quotes/other troublesome characters in the metadata string when using `{{ job_metadata }}` manually?

**Comment by wenottingham** [comment]
This looks like another effect of #10054, marking as a duplicate.

**Comment by dsmaugy** [comment]
Gotcha, thanks @wenottingham 

The reason I was looking at `job_metadata` was because I wanted to access the hosts that my templates ran on. Is there another way to access this data without going through `job_metadata`?

**Comment by agouaux** [comment]
Anything further on this since 2021? I'd just like to get a list of hosts processed in our AWX webhook notifications.
