### ISSUE TITLE
"Prompt on launch" ignored for verbosity in AWX 19.0.0 Web UI

### ISSUE THREAD

**Issue by kmtenhouse** [ansible/awx#10457]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

When running templates that allow "prompt on launch" verbosity in the Web UI, the user is able to select a custom verbosity as expected. The user's selected verbosity is also visible in the "review" section prior to launching the job.  However, when the job is actually executed, it reverts to using the default verbosity of the template instead. The job output will summarily show that the job was run with the default verbosity.

**Impact:** 
* User is unable to use "prompt on launch" for verbosity, leading to confusion.
* If a user has execute access only, they are unable to fix the verbosity without help from a template admin

##### ENVIRONMENT
* AWX version: 19.0.0
* AWX install method: operator
* AWX deployment target: kubernetes
* Client Web Browser: Edge 91.0.864.48

##### STEPS TO REPRODUCE

1. Create any template via the Web UI and select "prompt on launch" for verbosity. (Default verbosity is 0.)
2. Launch the template and select a custom verbosity (ex: 4).
3. Observe that your selection (4) is shown in the 'Preview' section (as expected).
4. Launch the playbook.
5. Observe the playbook results. 

##### EXPECTED RESULTS

It is expected that when a user selects a custom verbosity at 'prompt on launch', the job will run at their desired verbosity.

##### ACTUAL RESULTS

The job will always run at the "default" verbosity for the template, regardless of the user's selection.

##### ADDITIONAL INFORMATION

Detailed screenshots below:
1. Template setup: default verbosity is 0, prompt on launch selected:
![image](https://user-images.githubusercontent.com/40419337/122152355-009fb100-ce16-11eb-820d-c16691b9e5ff.png)

2. Begin the launch process. Receive the prompts as expected. Change verbosity to something else (ex: 3):
![image](https://user-images.githubusercontent.com/40419337/122152480-35ac0380-ce16-11eb-88fe-4e24f6f84f86.png)

3. Review your selections before launching. Notice that user selection is visible (3):
![image](https://user-images.githubusercontent.com/40419337/122152697-84599d80-ce16-11eb-8fc4-8f2296911956.png)

4. Launch the job - it will run at the incorrect verbosity. This can be confirmed by checking stdout, as well as the job details:
![image](https://user-images.githubusercontent.com/40419337/122152821-aeab5b00-ce16-11eb-9818-05bc76ab48a8.png)

**Comment by one-t** [comment]
Verified fixed

**Comment by kmtenhouse** [comment]
Hi @AlexSCorey - wondering if I might be able to confirm if this is verified as fixed in another version (ex: 19.2.0). I am likely going to move to 19.2.0 owing to other bug fixes.

**Comment by AlexSCorey** [comment]
It has been fixed, but not released yet.  It might be in 19.3.0 when that is released
