### ISSUE TITLE
Database is not created on fresh install

### ISSUE THREAD

**Issue by savealive** [ansible/awx#1046]
##### ISSUE TYPE

 - Bug Report
 - Documentation

##### COMPONENT NAME

 - Installer

##### SUMMARY

If I build distribution locally and start it in "local docker" mode it's unable to start due to database error.
In fact, database and user and not created so I have to create user and empty DB manually.

##### ENVIRONMENT
* AWX version: 1.0.2.73
* AWX install method: docker on linux
* Ansible version:  2.4.0
* Operating System: Centos 7

##### STEPS TO REPRODUCE
Specify necessary config in inventory:

```postgres_data_dir=/hcom/servers/awx-pgdocker
pg_username=awx
pg_password=password
pg_database=awx
pg_port=5432
```
and run 

`$ ansible-playbook -i inventory install.yml`

Once containers started check awx_task logs:
`
[osavchenko@chhlapphot830 installer]$ docker logs awx_task
Using /etc/ansible/ansible.cfg as config file
[DEPRECATION WARNING]: The sudo command line option has been deprecated in
favor of the "become" command line arguments. This feature will be removed in
version 2.6. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OperationalError: FATAL:  password authentication failed for user "awx"
127.0.0.1 | FAILED! => {
    "changed": false,
    "msg": "unable to connect to database: FATAL:  password authentication failed for user \"awx\"\n"
}
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==1.0.2.73', 'console_scripts', 'awx-manage')()
  File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/usr/lib/python2.7/site-packages/awx/conf/apps.py", line 18, in ready
    configure_external_logger(settings)
  File "/usr/lib/python2.7/site-packages/awx/main/utils/handlers.py", line 342, in configure_external_logger
    is_enabled = settings_module.LOG_AGGREGATOR_ENABLED
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 476, in __getattr_without_cache__
    return getattr(self._wrapped, name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 389, in __getattr__
    value = self._get_local(name)
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 66, in _log_database_error
    if get_tower_migration_version() < '310':
  File "/usr/lib/python2.7/site-packages/awx/main/utils/db.py", line 14, in get_tower_migration_version
    loader = MigrationLoader(connection, ignore_no_migrations=True)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/loader.py", line 209, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "awx"
`
Obviously, neither awx db or user were created so service couldn't run initial migrations.

##### EXPECTED RESULTS
Database and user should be created automatically by installer if they don't exist.

##### ACTUAL RESULTS
awx could not connect to database. DB user and DB instance don't exist.

##### ADDITIONAL INFORMATION
As a workaround user may create DB user and DB instance manually using following commands:

```$ docker exec -it postgres /bin/bash
root@dee124724d39:/# su - postgres
postgres@dee124724d39:/$ createuser awx
postgres@dee124724d39:/$ createdb awx
postgres@dee124724d39:/$ psql
psql (9.6.6)
Type "help" for help.

postgres=# alter user awx with encrypted password 'awxdbpasswordfrominventory';
ALTER ROLE
postgres=# grant all privileges on database awx to awx;
GRANT
```

**Comment by shanemcd** [comment]
I am unable to recreate this. I've pulled the latest from `devel` and run the standalone Docker path:

```
$ docker logs awx_task
Using /etc/ansible/ansible.cfg as config file
[DEPRECATION WARNING]: The sudo command line option has been deprecated in
favor of the "become" command line arguments. This feature will be removed in
version 2.6. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
127.0.0.1 | SUCCESS => {
    "changed": true,
    "db": "awx"
}
Operations to perform:
  Apply all migrations: auth, conf, contenttypes, django_celery_results, main, sessions, sites, social_django, sso, taggit
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying taggit.0001_initial... OK
  Applying taggit.0002_auto_20150616_2121... OK
  Applying main.0001_initial... OK
  Applying main.0002_squashed_v300_release... OK
......
```

I would recommend removing all containers and images and trying again. If you are still seeing the issue let us know.

**Comment by savealive** [comment]
@shanemcd Weird. I have definitely removed all containers and images on host. Will double check and report back.

**Comment by shanemcd** [comment]
@savealive Any updates?

**Comment by jamestutton** [comment]
I have had a similar issues when trying to specify and have the installer create a database via the [database] inventory section. Is this how you have done it perhaps?

If not sorry to hijack and will open a separate issue.

From a read of the code it appears that there may not even be support for this feature as doesn't appear to be a code branch to handle it anywhere i can spot.  

I would expect local_docker/tasks/standalone.yml to include some check on group_names or similar check but can see no checks in the AWX code at min.

**Comment by shanemcd** [comment]
@jamestutton The AWX installer will not "create" a database for you. You either use the containerized Postgres option (the default), or provide the hostname and credentials to an external database.

**Comment by jamestutton** [comment]
Apologies as slightly hijacking the original issue but may still be related.  So for clarification here as much as anywhere else.  Is there a major difference between AWX and tower here then with regard to clustering.  As for want of any better information I was under the impression that the flow document process from here should work:

[http://docs.ansible.com/ansible-tower/latest/html/administration/clustering.html#install-and-configure](url)

Namely:

The database group remains for specifying an external Postgres. If the database host is provisioned separately, this group should be empty

I have also seen this method referenced in other places and previous tower presentation.  And the impression has always been that the install playbook will provision the shared postgres instance if specified under this section.

**Comment by shanemcd** [comment]
You're looking at the Tower docs. Much of the documentation for Tower still applies to AWX, but you should not expect it to be exactly the same.

The AWX installer will not install and configure a postgres server for you outside of the container-based option. If you want to run an external db you will need to provision it yourself.

**Comment by shanemcd** [comment]
Closing this due to lack of response. If this is still an issue report back with more info and we will reopen.

**Comment by MVKozlov** [comment]
I meet this issue when try to use pg_password with ')' in it.

**Comment by anotherdish** [comment]
i just ran into this issue, and it seemed like there was an issue with my `tools_awx_db` docker volume (i may have exited out of the docker-compose command at a weird point, and the volume got scuffed). if you delete the volume with `docker volume rm tools_awx_db`, and rerun `make docker-compose`, it should recreate the volume for you and then you'll be good to go
