### ISSUE TITLE
[RFE] Feature to modify access_list using the API

### ISSUE THREAD

**Issue by zaskan** [ansible/awx#10462]
##### ISSUE TYPE
 - Feature Idea
Add a method to modify access_list for the different awx objects.

##### SUMMARY

Currently we are not providing a method in our API to modify the access_list for the different objects (Job templates, Projects, Inventories...). Creating this method would provide the ability of batch changes using scripting, making easy the modification of the permissions for the different objects.

**Comment by wenottingham** [comment]
This isn't a thing.

The access list is a manifestation of the RBAC system that traverses the roles assigned to users for an object to show who has access to that object.

To change that, you add or remove users/teams from roles. All of this is fully supported in the API, the CLI, and the awx collection.
