### ISSUE TITLE
awx-nginx stdout | nginx: [emerg] getpwnam("nginx") failed

### ISSUE THREAD

**Issue by Jacky2** [ansible/awx#10466]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Use:  make docker-compose

Error: nginx: [emerg] getpwnam("nginx") failed

##### ENVIRONMENT
* AWX version: devel
* AWX install method:  docker on CentOS7

##### ACTUAL RESULTS

awx-nginx stdout | nginx: [emerg] getpwnam("nginx") failed

##### SOLUTION
vi Makefile

```bash
nginx:
        useradd -g nginx nginx  # Add this line
        nginx -g "daemon off;"
```

**Comment by wenottingham** [comment]
-> #9552
