### ISSUE TITLE
Need additional search interface on Tower

### ISSUE THREAD

**Issue by garamirseokim** [ansible/awx#10471]
##### ISSUE TYPE
 - Feature Idea
Need an additional search function that able to search the entire processing result which is executed on a specific managed node.

![image](https://user-images.githubusercontent.com/58404577/122486164-dae3f900-d01b-11eb-8bfe-27c99f60b226.png)

##### SUMMARY

For exsample...

- Customer's windows vm got rebooted by ansible as per their troubleshooting and customer want to know how and who did this.
Below message found from Windows Event Log on the windows vm(managed node).

        shutdown /r /t 2 /c ""Reboot initiated by Ansible"

- Above message looks like from the ‘win_reboot’ module(https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_reboot_module.html) on the windows server(managed node) side and the windows server is not forwarding the below reboot message to Tower side. So, it is hard to find the specific Job Template which is related to the below message on Tower.

- Tried to narrow down the search results with the below command with Job search on the Tower and got few page results but not sure which one is related to the windows server(managed node).

       created:>=2021-01-01T012:00:00Z finished:<=2021-01-01T12:00:00Z

- Need to search the entire processing result executed on a specific node to be managed, but there is no appropriate interface on Tower.

**Comment by quincysting119** [comment]
![image](https://user-images.githubusercontent.com/77130598/122491486-7c247c80-d027-11eb-925f-31dbdfaed479.png)

What's missed for this case is it's a job run against the VM but from AT there is no history record for that completed job. It looks like some underlying transactions are not visible from AT UI. Would be great to fix it. Otherwise it's a potential security risk for us because people could do dangerous things without being recorded by AT.

**Comment by jakemcdermott** [comment]
Is this information available on the activity stream?

**Comment by wenottingham** [comment]
A job run against the host should show up in the completed jobs - that indicates either some sort of error, or that something unusual is going on with how the playbook is structured.

Can you give a redacted version of the playbook? Is `add_host` used?

**Comment by quincysting119** [comment]
![image](https://user-images.githubusercontent.com/77130598/122694513-e84ded00-d280-11eb-88cf-d19b415edc34.png)
It's a bit like chicken/eggs. If we can trace back that playbook, we woud not have this discussion here. 
From the event log of the host, we can see the job initiated by AT but we could not find the playbook against that host. 
There is no job history from AT as well. Such a bizarre. I also looked into /awx folder, not much luck for related info.

**Comment by wenottingham** [comment]
`Reboot initiated by ansible` could be a playbook run outside of AWX as well.

One thing to try - check ad-hoc commands run against the host. That would be in the API at `/api/v2/hosts/<host id>/ad_hoc_commands/`

**Comment by quincysting119** [comment]
Just tried with not much information. Does it mean any ad-hoc run againt the host from command line is not traceable? We would not be able to see who trigger the job?

![image](https://user-images.githubusercontent.com/77130598/123562214-a0831480-d7f0-11eb-843a-18d0f949e8d0.png)

Thanks,
Ian

**Comment by wenottingham** [comment]
The API is searched by the ID, not the name.

**Comment by wenottingham** [comment]
Please try what is suggested. Note that if you're having issues with Red Hat Ansible Automation Platform, contact your Red Hat support representative.
