### ISSUE TITLE
Job template credentials are not selected on job launch

### ISSUE THREAD

**Issue by machadovilaca** [ansible/awx#10474]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
In the Job Templates, I set credentials, that are supposed to be the defaults for that template job launches, and set 'Prompt on launch'.

![edit](https://user-images.githubusercontent.com/21959383/122571903-2232af80-d045-11eb-88e2-ef3f6c4e664a.png)

But when launching a job, in the "Credentials" section, they don't show up.

![launch](https://user-images.githubusercontent.com/21959383/122571922-265ecd00-d045-11eb-96ce-bde86a9850bf.png)

And if I try to run it without re-adding them, it throws an error.

![err](https://user-images.githubusercontent.com/21959383/122571943-2b238100-d045-11eb-8133-186221ec9c53.png)

This situation started happening in recent AWX versions. Previous releases with the old interface did not have this issue.

##### ENVIRONMENT
* AWX version: current version => 19.2.0, also happening on 18.0.0 
* AWX install method: AWX Operator 0.10.0
* Operating System: Linux
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

1. Create a job template with credentials and 'Prompt on launch'
2. Launch a new job
3. Verify that selected credentials are not selected.

##### EXPECTED RESULTS

Credentials defined in the template to be set when launching a new job

##### ACTUAL RESULTS

Credentials defined in the template are not selected when launching a new job

**Comment by tiagodread** [comment]
This is now fixed
