### ISSUE TITLE
partition not available when storing project update events

### ISSUE THREAD

**Issue by jladdjr** [ansible/awx#10487]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

postgres reports ` no partition of relation "main_projectupdateevent" found for row` when attempting to save job events for a project update.

##### ENVIRONMENT
* AWX version: 4.0.0.
* AWX install method: traditional cluster install

##### STEPS TO REPRODUCE

Schedule a workflow job to run every few minutes. The WF job should trigger a project update.

##### EXPECTED RESULTS

awx should create a new partition for `main_projectupdateevent` when a job runs and a partition does not exist. It should then be able to store job events successfully. The events and job details should be visible in the UI and API browser.

##### ACTUAL RESULTS

On the db instance, logs under `/var/lib/pgsql/data/pg_log` show:

```
< 2021-06-20 01:00:26.152 UTC ec2-184-72-123-3.compute-1.amazonaws.com-113525-/usr/bin/awx-ma >ERROR:  no partition of relation "main_projectupdateevent" found for row
< 2021-06-20 01:00:26.152 UTC ec2-184-72-123-3.compute-1.amazonaws.com-113525-/usr/bin/awx-ma >DETAIL:  Partition key of the failing row contains (job_created) = (2021-06-20 01:00:23.015708+00).
< 2021-06-20 01:00:26.152 UTC ec2-184-72-123-3.compute-1.amazonaws.com-113525-/usr/bin/awx-ma >STATEMENT:  INSERT INTO "main_projectupdateevent" ("event", "event_data", "failed", "changed", "uuid", "playbook", "play", "role", "task", "counter", "stdout", "verbosity", "start_line", "end_line", "created", "modified", "project_update_id", "job_created") VALUES ('playbook_on_start', '{"playbook": "project_update.yml", "playbook_uuid": "5252f16a-4b53-45cc-8bcf-90f0ac154449", "uuid": "5252f16a-4b53-45cc-8bcf-90f0ac154449", "guid": "6560a870687d47559dab8b1862eb78bc"}', false, false, '5252f16a-4b53-45cc-8bcf-90f0ac154449', 'project_update.yml', '', '', '', 1, '', 0, 0, 0, '2021-06-20T01:00:25.982318+00:00'::timestamptz, '2021-06-20T01:00:26.131199+00:00'::timestamptz, 37838, '2021-06-20T01:00:23.015708+00:00'::timestamptz) RETURNING "main_projectupdateevent"."id"
```

##### ADDITIONAL INFORMATION

* The same error is repeated multiple times, suggesting that awx is retrying the failed transaction.
* The same error happens for different project update events shortly after the initial failure. It appears that the issue prevents any events from the project update from being saved.
* The error only seems to affect projectupdate events.
* The error happens on the order of once a day.
* This has been observed three times on the same cluster. In each case, the failed job event errors started at the [top of the hour](https://gist.github.com/jladdjr/b19e77c3392f49324e98d90ba56bfe32). For example:

```
postgresql-Fri.log:< 2021-06-18 10:00:33.792 UTC ec2-184-72-123-3.compute-1.amazonaws.com-113525-/usr/bin/awx-ma >ERROR:  no partition of relation "main_projectupdateevent" found for row
```

When a project encounters this issue it is not shown in the UI's list of jobs. It can be retrieved by going directly to the job details page. The stdout for the project ends up being empty:

![image](https://user-images.githubusercontent.com/4440360/122813586-f6533c00-d287-11eb-8f9b-2f4a0ae53b98.png)

In the API browser, the project's jobevents endpoint is empty:
![image](https://user-images.githubusercontent.com/4440360/122813691-17b42800-d288-11eb-8f24-3efa492f1573.png)

**Comment by jladdjr** [comment]
@chrismeyersfsu @kdelee noting know issue in ~user guide~ release notes -> known issues:
https://github.com/ansible/product-docs/pull/1524

**Comment by jladdjr** [comment]
On https://github.com/ansible/tower/issues/5123, @AlanCoding reports that he's seeing this same error, but for `main_inventoryupdateevent`

**Comment by AlanCoding** [comment]
> The same error is repeated multiple times, suggesting that awx is retrying the failed transaction.

Aren't these logs from the callback receiver? A project update may generate ~15 events in a single run, so I'd expect the repetition simply because it hits the error for every event it tries (and fails) to save.

**Comment by AlanCoding** [comment]
@jladdjr 

> - The same error happens for different project update events shortly after the initial failure. It appears that the issue prevents any events from the project update from being saved.
> - The error happens on the order of once a day.
> - This has been observed three times on the same cluster. In each case, the failed job event errors started at the top of the hour. For example:

Replicating locally now - this happens specifically for project _syncs_. Those that run as a local sync of a project before a job starts. This is why you thought you only saw it happen ~once per day. Syncs are rare in standalone integration, because `factories.project()` will give you a project where the local source is up-to-date. Clusters sync more often because the project update can happen on node A and then a job can run on node B, so the latter won't have the checkout. That's when the sync runs.

The "scm" type inventory updates in https://github.com/ansible/tower/issues/5123 use the same mechanism, and are (unsurprisingly) afflicted by the same bug.

Even @kialam, working on showing the link to a job's project sync (independent of this) noted to me that the output was blank. It is _not_ blank for normal project updates, but it appears to _always_ be blank for project syncs.

Something in the DB partitioning work (ping @chrismeyersfsu) must be written so that partition prep is done for unified_jobs processed _through the task manager_, so that this work is not done for a job spawned out-of-the-blue, short-circulating the task manager.

**Comment by AlanCoding** [comment]
Maybe there is some flake to this, because I was hitting it consistently for these job types yesterday but this morning I'm not.

**Comment by AlanCoding** [comment]
@chrismeyersfsu had the answer

https://github.com/ansible/awx/blob/a6383e7f79d56d8d422870cb5720762f197cbd3a/awx/main/scheduler/task_manager.py#L306

**Comment by kdelee** [comment]
We've verified that the tests added https://github.com/ansible/tower-qa/pull/6519/files provoke the bug w/o the fix,and w/ the fix it ceases to happen. Going to close this
