### ISSUE TITLE
Add Ability to Configure Custom Start Point for Job IDs

### ISSUE THREAD

**Issue by imareporter** [ansible/awx#10485]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Per an user's request, they would like to be able to configure a custom start point for job IDs (e.g. PostgreSQL starts incrementing at 100, 200, 10000, etc.). The user is requesting this so they can better search for data within a centralized log aggregator.

**Comment by wenottingham** [comment]
If the intent is to avoid ID reuse between different clusters, what starting ID were they looking at? 1_000_000? More?

**Comment by shanemcd** [comment]
It's my understanding that this is due to overlapping job IDs between different clusters. If this is the case, a better way to do this would be to include the the cluster ID as a part of the search query / filter.
