### ISSUE TITLE
Give playbook authors the possibility to return custom values to a job/workflow

### ISSUE THREAD

**Issue by ericzolf** [ansible/awx#10492]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

The AWX API is fine to call a job/workflow and pass _input_ variables (through extra vars) from the calling process to the playbook. But there is no standard way to pass _output_ variables from the playbook to the calling process through the API.

John has written a Jenkins plugin which does exactly this but the approach chosen (chapter "Returning Data") is more a hack than a proper interface, and requires a lot of extra code to make it work with workflows:

* https://plugins.jenkins.io/ansible-tower/
* https://github.com/jenkinsci/ansible-tower-plugin

**Comment by wenottingham** [comment]
This already exists.

https://docs.ansible.com/ansible-tower/latest/html/userguide/workflows.html
which uses:
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/set_stats_module.html

**Comment by ericzolf** [comment]
Discussing with John I didn't get the impression that the API allows to grab the "stats" at the workflow level, you need to grab them painfully from each job.
