### ISSUE TITLE
Update Execution Environment Lookup 

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#10497]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Create new job template Select Execution Environment modal
Change title from “Select Execution Environments” to “Select Execution Environment”
![Screen Shot 2021-06-23 at 11 32 51 AM](https://user-images.githubusercontent.com/39280967/123125805-d736e480-d416-11eb-9a6c-c70116f71c59.png)

**Comment by akus062381** [comment]
resolved
