### ISSUE TITLE
Survey Form Should Not Show Job Template Tabs

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#10499]
##### ISSUE TYPE
-enhancement

##### SUMMARY
Current Survey Form:
![Screen Shot 2021-06-23 at 11 34 34 AM](https://user-images.githubusercontent.com/39280967/123126014-08171980-d417-11eb-80a3-fd98e30410cc.png)
Mock ups:
https://tower-mockups.testing.ansible.com/patternfly/templates/templates-survey-add/

**Comment by akus062381** [comment]
resolved
