### ISSUE TITLE
tower_license.py missing from 19.2.1 awx.awx collections

### ISSUE THREAD

**Issue by mgaredia** [ansible/awx#10493]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by AlanCoding** [comment]
These modules were renamed, like `tower_license` -> `controller_license`.

They are supposed to have redirects, but they didn't work for Ansible 2.9. A commit has been put in `devel` to add them.

https://github.com/ansible/awx/blob/devel/awx_collection/plugins/modules/tower_license.py

Closing, as I assume this will fix it for you in the next release.
