### ISSUE TITLE
Update Status Icon

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#10496]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Audit the UI for current status Icons
https://github.com/ansible/awx/issues/10216

They should be updated to use the new status icons
https://tower-mockups.testing.ansible.com/patternfly/jobs/jobs-detail/

related: https://github.com/ansible/tower/pull/5134.

**Comment by InnocentK** [comment]
Feature successfully added and issue resolved in (https://github.com/ansible/awx/pull/11561#pullrequestreview-861394586).
