### ISSUE TITLE
Use Table view for modals that show lists of items (delete modals)

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#10503]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Now that we have the table view implemented for all of our lists it would be nice to use that same table view on our multi delete modals, and other modals that show lists.

**Comment by tiagodread** [comment]
@AlexSCorey to add more context, examples, prototypes in this issue.

**Comment by AlexSCorey** [comment]
![Screen Shot 2021-12-07 at 9 47 32 AM](https://user-images.githubusercontent.com/39280967/145050939-0b610a4b-dc27-47cd-84fb-3d43cf721153.png)
This is an example of a delete modal that does not use a table view.  It is a list view.  I think that where applicable we should use a table view with column headers etc on modals to better match the list view.
![Screen Shot 2021-12-07 at 9 52 52 AM](https://user-images.githubusercontent.com/39280967/145051840-7330c044-6dc1-4930-a0a3-a733e8fea737.png)

This is a list view in a modal.

**Comment by AlexSCorey** [comment]
Whoever picks this up reach out to UXD and/or patternfly to flesh out the ideas of updating modals.

**Comment by keithjgrant** [comment]
This behavior is already implemented in the new UI framework. Since we're moving in that direction, I'll close this task here in AWX
