### ISSUE TITLE
documentation lacking on websocket authentication

### ISSUE THREAD

**Issue by phemmer** [ansible/awx#10507]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The [documentation on websocket authentication](https://github.com/ansible/awx/blob/devel/docs/websockets.md#protocol) is lacking details on how to perform authentication.

For example, it just says
> You must provide a valid Auth Token in the request URL.

Ok, I'm assuming this means as a query parameter. If so, what's the parameter name? And this is also a security concern, as the URL is typically considered insecure since it is commonly logged.

Secondly, for a client which is using [session authentication](https://github.com/ansible/awx/blob/devel/docs/auth/session.md), and thus has no token, how are they supposed to perform authentication?

Also as a side issue, the documentation states:
> You can connect to the AWX channels implementation using any standard websocket library by pointing it to `/websocket`. 

This is slightly incorrect. The URL must have a trailing slash (`/websocket/`). Failure to put the trailing slash will result in a 502 response.

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: minikube
* Ansible version:  n/a
* Operating System: debian buster
* Web Browser: n/a

**Comment by shanemcd** [comment]
PRs welcome.

**Comment by phemmer** [comment]
According to https://github.com/ansible/awx/issues/10764#issuecomment-887841421, the websocket is not supported for external use. Thus requests for documentation would seem to not make sense. Though I might argue in that case, the current documentation should be removed.
In any case, it seems this ticket should be closed.
