### ISSUE TITLE
Dynamic tagging

### ISSUE THREAD

**Issue by madeinindiadot** [ansible/awx#10500]
**problem statement:** we have a playbook that we're looking to use but do not own, playbook has a number of tags that we'll need to use to skip several tags that will impact our application.  
 
In order to enforce tower RBAC, we need to run workflow that includes another playbook prior to this one which will feed a list of  tags within file.

**Option 1:**

Tagging as a variable

Can we parameterize tagging? Meaning feed tags as a dynamic variable.

**Option 2:**

As an alternative to option1, if we cannot dynamically feed a tag as a variable, in a workflow that is being executed, if we update one of its template, will that newly saved template be run in the running workflow? Or will the original one be still running

 

WORKFLOW :: start >  template1            >>                template2                 >>               template3

                                               |                                                 |                                                      |

                         [ Update template2 via api ]      [ run updated template2? ]

						 
Here’s what we’re looking to achieve from the “generate list of tag”, we’re looking for the same results as executing``` ansible-playbook patch.yml --list-tags``` but from the ansible tower

$ ansible-playbook patch.yml --list-tags                                                                                                                                                
sample
------------
playbook: patch.yml

  play #1 (all): all    TAGS: []
      TASK TAGS: [aps_custom_repos, atlas_global_repo, builder_status_callback, clear_yum_cache, dell_firmware, eracent_agent, hardware_agents, hba_firmware, host_metadata, hp_firmware, itrc_key_value, ppstie_frozen_repo, pre_patch_reboot, prod_or_ula, remove_default_repos, update_packages, yum_conf]
						 
Any other ideas is welcome

**Comment by wenottingham** [comment]
Tags are passed from AWX to ansible via commandline args - trying to influence that from variables passed to the job isn't practical, as we'd have to be interpreting the variable namespace before job execution (vars can come from inventory, etc).

I'd follow option 2 - if you update the template the workflow node uses, the new definition will be used when it's kicked off. You will want to unset `allow_simultaneous` on the workflow, as this wouldn't be a workflow safe to run in parallel.
