### ISSUE TITLE
sync inventory broken in 19.2.1

### ISSUE THREAD

**Issue by AlekseiSaff** [ansible/awx#10505]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 19.2.1
* AWX install method: k8s
* Ansible version:  2.12
* Operating System: Linux
* Web Browser: Chrome

##### STEPS TO REPRODUCE

AWX inventory sync job loaded only 8 hosts and 4 groups, but dynamic script returning more records. That script worked fine in 17.X version

##### EXPECTED RESULTS

Load all hosts/groups into inventory

##### ADDITIONAL INFORMATION

[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.
ansible-inventory [core 2.12.0.dev0]
  config file = /runner/project/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True
Using /runner/project/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /runner/project/dns_inventory.py as it did not pass its verify_file() method
Parsed /runner/project/dns_inventory.py inventory source with script plugin
    7.477 INFO     Processing JSON output...
    7.477 DEBUG    Loaded group: all
    7.477 DEBUG    Loaded group: hk1_admin
    7.478 DEBUG    Adding child group hk1_admin to parent all
    7.478 DEBUG    Loaded group: hkg1_dev
    7.478 DEBUG    Adding child group hkg1_dev to parent all
    7.478 DEBUG    Loaded group: mum1_prod
    7.478 DEBUG    Adding child group mum1_prod to parent all
    7.479 DEBUG    Loaded group: mum2_prod
    7.479 DEBUG    Adding child group mum2_prod to parent all
    7.479 DEBUG    Loaded host: lt-hk1-asr03
    7.480 DEBUG    Adding host lt-hk1-asr03 to group hk1_admin
    7.480 DEBUG    Adding child group hk1_admin to parent all
    7.481 DEBUG    Loaded host: lt-hkg1-dws14
    7.481 DEBUG    Adding host lt-hkg1-dws14 to group hkg1_dev
    7.481 DEBUG    Loaded host: lt-hkg1-dws19
    7.481 DEBUG    Adding host lt-hkg1-dws19 to group hkg1_dev
    7.482 DEBUG    Adding child group hkg1_dev to parent all
    7.482 DEBUG    Loaded host: lt-mum1-psr04
    7.482 DEBUG    Adding host lt-mum1-psr04 to group mum1_prod
    7.482 DEBUG    Adding child group mum1_prod to parent all
    7.483 DEBUG    Loaded host: lt-mum2-psr01
    7.483 DEBUG    Adding host lt-mum2-psr01 to group mum2_prod
    7.510 DEBUG    Loaded host: lt-mum2-psr02
    7.510 DEBUG    Adding host lt-mum2-psr02 to group mum2_prod
    7.511 DEBUG    Loaded host: lt-mum2-psr05
    7.511 DEBUG    Adding host lt-mum2-psr05 to group mum2_prod
    7.511 DEBUG    Loaded host: lt-mum2-psr06
    7.511 DEBUG    Adding host lt-mum2-psr06 to group mum2_prod
    7.512 DEBUG    Adding child group mum2_prod to parent all
    7.512 INFO     Loaded 4 groups, 8 hosts
    7.513 DEBUG    Inventory variables unmodified
    7.516 DEBUG    Group "hk1_admin" variables unmodified
    7.516 DEBUG    Group "hkg1_dev" variables unmodified
    7.517 DEBUG    Group "mum1_prod" variables unmodified
    7.517 DEBUG    Group "mum2_prod" variables unmodified
    7.526 DEBUG    Host "lt-hk1-asr03" variables unmodified
    7.526 DEBUG    Host "lt-hkg1-dws14" variables unmodified
    7.526 DEBUG    Host "lt-mum1-psr04" variables unmodified
    7.527 DEBUG    Host "lt-mum2-psr02" variables unmodified
    7.527 DEBUG    Host "lt-mum2-psr05" variables unmodified
    7.533 DEBUG    Host "lt-hkg1-dws19" added
    7.536 DEBUG    Host "lt-mum2-psr01" added
    7.540 DEBUG    Host "lt-mum2-psr06" added
    7.548 DEBUG    Host "lt-hk1-asr03" added to group "hk1_admin"
    7.552 DEBUG    Host "lt-hkg1-dws14" already in group "hkg1_dev"
    7.554 DEBUG    Host "lt-hkg1-dws19" added to group "hkg1_dev"
    7.558 DEBUG    Host "lt-mum1-psr04" already in group "mum1_prod"
    7.565 DEBUG    Host "lt-mum2-psr02" already in group "mum2_prod"
    7.565 DEBUG    Host "lt-mum2-psr05" already in group "mum2_prod"
    7.567 DEBUG    Host "lt-mum2-psr01" added to group "mum2_prod"
    7.568 DEBUG    Host "lt-mum2-psr06" added to group "mum2_prod"
    7.626 INFO     Inventory import completed for DNS-sync in 0.2s

**Comment by AlekseiSaff** [comment]
I checked my script
./dns_inventory --list - it returns JSON - works

I checked 
ansible-inventory -i dns_inventory.py  --graph  - works fine returning all my hosts/groups

but sync process can load only 8 hosts/4 groups

**Comment by AlekseiSaff** [comment]
I can provide the full output of my dns_inventory.py if it helps
as well as ansible-inventory -i dns_inventory.py --graph

**Comment by AlekseiSaff** [comment]
any ideas on what to do here and how to troubleshoot?

**Comment by blindrood** [comment]
I had similar issue (already restored previous version). With 19.2.1 there's EE 0.4.0. I tried changing it but noticed that EE for Inventory project doesn't update EE for inventory update itself (there's still default). Try to remove EE 0.4.0 and see if this resolves it

**Comment by AlekseiSaff** [comment]
The problem with EE 0.4.0 it doesn't have needed libs (dnspython) so I've built my own EE. 
the version of python/ansible-inventory can be viewed from the original post.

**Comment by AlekseiSaff** [comment]
after removing EE 0.4.0
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1374, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2896, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2913, in _run_internal
    result = receptor_ctl.submit_work(worktype=self.work_type, payload=sockout.makefile('rb'), params=self.receptor_params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2991, in receptor_params
    spec_yaml = yaml.dump(self.pod_definition, explicit_start=True)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3039, in pod_definition
    default_pod_spec = get_default_pod_spec()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/utils/execution_environments.py", line 27, in get_default_pod_spec
    raise RuntimeError("Unable to find an execution environment.")
RuntimeError: Unable to find an execution environment.

**Comment by AlekseiSaff** [comment]
I'm struggling to find a solution, cause it's the only one stop factor from jumping docker 17.x into k8s 19.x

any ideas?

**Comment by shanemcd** [comment]
Forcing the operator to reconcile should recreate the default EEs. You could do that by just deleting something like the awx pod.

**Comment by AlekseiSaff** [comment]
thanks, but why do you think we should recreate the default EE? I did it several time POD recreation, but still the same issue

**Comment by AlekseiSaff** [comment]
> Forcing the operator to reconcile should recreate the default EEs. You could do that by just deleting something like the awx pod.

that's not an issue to recreate AWX pod. I'm more interested in resolving main issue. Any ideas @shanemcd ?

**Comment by fosterseth** [comment]
Can you please post the ansible-inventory or script output (please redact sensitive info)? also, which 8 of these are correctly synced when using awx?

**Comment by AlekseiSaff** [comment]
script output attached
ansible-inventory output attached

every time it can be different hostst. One run can be 7, next run 8 or 9 
here are two examples of two different sync jobs
[second_run.txt](https://github.com/ansible/awx/files/6720976/second_run.txt)
[first_run.txt](https://github.com/ansible/awx/files/6720977/first_run.txt)
[ans-inv.txt](https://github.com/ansible/awx/files/6720978/ans-inv.txt)
[script_output.txt](https://github.com/ansible/awx/files/6720979/script_output.txt)

**Comment by AlekseiSaff** [comment]
as I previosly mentioned that script worked well for me from AWX 14, 15 and 17

**Comment by AlekseiSaff** [comment]
not an AWX issue!

**Comment by AlekseiSaff** [comment]
an issue is related to how DNS  works in minikube 
finally I managed to add my own /etc/resolv1.conf file into EE image
COPY resolv.conf /etc/resolv1.conf

and during initialization of dnsresolver provide that file as argument

>>> my_resolver=dns.resolver.Resolver(filename='/etc/resolv1.conf',configure=True)

**Comment by wenottingham** [comment]
OK, thanks for letting us know.
