### ISSUE TITLE
Custom message banner about important information other than checking a log file

### ISSUE THREAD

**Issue by garamirseokim** [ansible/awx#10516]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Custom message banner to notify Users about important information(eg upgrades)/service interruptions etc other than checking a log file. This custom message should appear on all pages the top of the screen of Tower.

**Comment by DLV111** [comment]
I'd like this feature too, when running in an enterprise world being able to display a message to users about an upgrade or known issues is very helpful.

**Comment by wenottingham** [comment]
-> #1971
