### ISSUE TITLE
What is recommended method to install ca certs to get LDAP TLS to work? (minikube)

### ISSUE THREAD

**Issue by karezza** [ansible/awx#10519]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME
 - Installer

##### SUMMARY
LDAP on 389 with no TLS works, enabling causes cert errors.  Seeking recommended method to install ca certs.

##### ENVIRONMENT
* AWX version: AWX 19.2.0
* AWX install method: operator, developer environment
* AWX deployment target: minikube
* Operating System: CentOS8
* Web Browser: chromium-browser

##### STEPS TO REPRODUCE
Standard AWX Operator install using minikube.

##### ATTEMPTS TO RESOLVE
- in the past the ca certs could be installed via the container awx-task using update-ca-trust, but this utility is no longer present seemingly indicating this is no longer the correct strategy
- minikube has the following method to install certs, https://minikube.sigs.k8s.io/docs/handbook/untrusted_certs/, followed the steps and restarted the deployment using:  minikube kubectl -- rollout restart deployment itsawx

**Comment by wenottingham** [comment]
See https://github.com/ansible/awx-operator/issues/376
