### ISSUE TITLE
created_by null on scheduled job with custom notification

### ISSUE THREAD

**Issue by lucab85** [ansible/awx#10517]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The field `created_by` is **null** when invoked by a **scheduled job** on a custom notification.

In conjunction with that any sub attribute couldn't be referenced, such as `job.summary_fields.created_by.username`,  and then the whole message will not be constructed.

##### ENVIRONMENT
* AWX version: latest
* Ansible version:  2.9.15
* Operating System: Fedora 33
* Web Browser: Firefox 89.0 (64 bit)

##### STEPS TO REPRODUCE

`. Create a custom notification referencing `created_by`:
```
    "messages": {
        "started": {
            "message": null,
            "body": "{{ job.summary_fields.created_by.username }}"
        },
        "success": {
            "message": null,
            "body": "{{ job.summary_fields.created_by.username }}"
        },
        "error": {
            "message": null,
            "body": "{{ job.summary_fields.created_by.username }}"
        }
```
2. Assing the custom notification to a Job Template with scheduled time

##### EXPECTED RESULTS

I expect a notification with `created_by` content at the scheduled time.

##### ACTUAL RESULTS

Notification didn't show up at the scheduled time.

**Comment by sugitk** [comment]
Is it fixed on https://github.com/ansible/awx/issues/8677 ?

**Comment by dmzoneill** [comment]
Tentatively closing this out.
The user will get a warning when the template generation is empty
https://github.com/ansible/awx/pull/14839
