### ISSUE TITLE
Node Add Modal for Workflow Approval- Display Fix Needed

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#10515]
In this screen of the modal where a user adds  a Workflow Approval node, under Timeout, the min and sec characters are displaying in a stacked manner instead of left to right
![image](https://user-images.githubusercontent.com/63685497/123325913-9b7b4800-d506-11eb-81a6-96cc4a593bd4.png)

**Comment by nixocio** [comment]
Issue already addressed.
