### ISSUE TITLE
Can't export logs in logstash

### ISSUE THREAD

**Issue by chris93111** [ansible/awx#10526]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Any export logs to aggregator not work
after investigation awx_task try to restart rsyslog with supervisorctl but rsyslogd is absent in supervisor_task 

start manualy rsyslogd in awx_tasks solve the problem

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.9
* Operating System: redhat
* Web Browser: chrome

##### STEPS TO REPRODUCE

Set a aggregator to logstash http

##### EXPECTED RESULTS

logstash receive transaction

##### ACTUAL RESULTS

no transaction

##### ADDITIONAL INFORMATION

{
    "LOG_AGGREGATOR_HOST": "http://mylogstash:8085",
    "LOG_AGGREGATOR_PORT": "",
    "LOG_AGGREGATOR_TYPE": "logstash",
    "LOG_AGGREGATOR_USERNAME": "",
    "LOG_AGGREGATOR_PASSWORD": "",
    "LOG_AGGREGATOR_LOGGERS": [
        "awx",
        "activity_stream",
        "job_events",
        "system_tracking"
    ],
    "LOG_AGGREGATOR_INDIVIDUAL_FACTS": false,
    "LOG_AGGREGATOR_TOWER_UUID": "xxxxxxx",
    "LOG_AGGREGATOR_ENABLED": true
}

**Comment by chris93111** [comment]
2021-06-25 21:32:11,306 DEBUG    awx.main.utils.reload Issuing command to restart services, args=['supervisorctl', 'restart', 'tower-processes:awx-rsyslogd']
2021-06-25 21:32:11,542 ERROR    awx.main.utils.reload supervisorctl restart awx-rsyslogd errored with exit code `7`, stdout:
unix:///var/run/supervisor/supervisor.web.sock no such file

**Comment by shanemcd** [comment]
Hi - can you try on a more recent version of AWX?

```
unix:///var/run/supervisor/supervisor.web.sock no such file
```

^ This makes me think you've patched your deployment and missed something.

**Comment by chris93111** [comment]
migrate to kubernetes
