### ISSUE TITLE
AWX UI is not accessible when firewalld is enabled

### ISSUE THREAD

**Issue by ptrinesh** [ansible/awx#10531]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX UI is not accessible when firewalld is enabled

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: Kubernetes
* Ansible version:  2.11.1
* Operating System: Centos 8.3

##### STEPS TO REPRODUCE

Enable the firewalld and install awx

##### EXPECTED RESULTS

Ports to be opened should be mentioned in case if firewalld is enabled

##### ACTUAL RESULTS

UI is not accessible as the required ports are not opened.

##### ADDITIONAL INFORMATION

Please help me in identifying the firewalld ports to be opened if it is enabled

**Comment by shanemcd** [comment]
Hello,

This sounds like a Kubernetes configuration error to me.

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

#ansible-awx on https://libera.chat/
https://groups.google.com/forum/#!forum/awx-project
