### ISSUE TITLE
AWX Stuck on ansible.builtin.service steps

### ISSUE THREAD

**Issue by joaogl** [ansible/awx#10530]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - AWX

##### SUMMARY
Hey,
I have quite a few playbooks doing all sorts of things, from setting up VM's to installing software. I guess the usual.
I've recently started using AWX and more specifically AWX on docker through operator, and all playbooks are working just fine except one specific step.
I can't seem to understand why but all the playbooks I have that use  ansible.builtin.service to restart services are simply getting stuck without any kind of feedback.
I tried this in multiple playbooks, targeting multiple hosts even with multiple services and formats on the service step, all seem to get stuck.
Also the interesting part is that running this in my local machine works just fine.

##### ENVIRONMENT
* AWX version: 19.2.1
* AWX install method: operator
* AWX deployment target: kubernetes
* Operating System: Ubuntu
* Web Browser: Chrome

##### STEPS TO REPRODUCE
I have tried the  following:
`
- name: Restart HAProxy
  ansible.builtin.service:
    name: haproxy
    state: restarted

- name: Restart HAProxy
  service:
    name: haproxy
    state: restarted

- name: Restart HAProxy
  ansible.builtin.service: "name=haproxy state=restarted"

- name: Restart HAProxy
  service: "name=haproxy state=restarted"
`

RUnning this in my local env works just fine, running it in AWX get's the job stuck.

##### EXPECTED RESULTS

Service to be restarted.

##### ACTUAL RESULTS

Job stuck.

##### ADDITIONAL INFORMATION

I tried to enable Debug on AWX but the logs don't provide anything relevant, I'm not sure where else to look for to understand the issue.

**Comment by wenottingham** [comment]
You'd need debugging information on the server you're trying to restart services on; there's not enough here to go by, and may be an issue with ansible itself, not AWX.

**Comment by joaogl** [comment]
Hey, thanks for the reply and sorry for the delay.
So I went into the logs of the target host and re-ran the playbook from AWX.
The playbook in question updates haproxy configs (successfully) and then tries to restart haproxy which hangs for ever.

Here are the logs:
```
Jun 29 20:20:38 test01 systemd[1]: Created slice User Slice of UID 1002.
Jun 29 20:20:38 test01 systemd[1]: Starting User Runtime Directory /run/user/1002...
Jun 29 20:20:38 test01 systemd[1]: Finished User Runtime Directory /run/user/1002.
Jun 29 20:20:38 test01 systemd[1]: Starting User Manager for UID 1002...
Jun 29 20:20:38 test01 systemd[11783]: Reached target Paths.
Jun 29 20:20:38 test01 systemd[11783]: Reached target Timers.
Jun 29 20:20:38 test01 systemd[11783]: Starting D-Bus User Message Bus Socket.
Jun 29 20:20:38 test01 systemd[11783]: Listening on GnuPG network certificate management daemon.
Jun 29 20:20:38 test01 systemd[11783]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Jun 29 20:20:38 test01 systemd[11783]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Jun 29 20:20:38 test01 systemd[11783]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Jun 29 20:20:38 test01 systemd[11783]: Listening on GnuPG cryptographic agent and passphrase cache.
Jun 29 20:20:38 test01 systemd[11783]: Listening on debconf communication socket.
Jun 29 20:20:38 test01 systemd[11783]: Listening on REST API socket for snapd user session agent.
Jun 29 20:20:38 test01 systemd[11783]: Listening on D-Bus User Message Bus Socket.
Jun 29 20:20:38 test01 systemd[11783]: Reached target Sockets.
Jun 29 20:20:38 test01 systemd[11783]: Reached target Basic System.
Jun 29 20:20:38 test01 systemd[11783]: Reached target Main User Target.
Jun 29 20:20:38 test01 systemd[11783]: Startup finished in 54ms.
Jun 29 20:20:38 test01 systemd[1]: Started User Manager for UID 1002.
Jun 29 20:20:38 test01 systemd[1]: Started Session 93 of user testuser.
Jun 29 20:20:39 test01 python3[11885]: ansible-ansible.legacy.setup Invoked with gather_subset=['all'] gather_timeout=10 filter=[] fact_path=/etc/ansible/facts.d
Jun 29 20:20:40 test01 python3[11965]: ansible-ansible.legacy.stat Invoked with path=/etc/haproxy/haproxy.cfg follow=False get_checksum=True checksum_algorithm=sha1 get_md5=False get_mime=True get_attributes=True
Jun 29 20:20:41 test01 python3[11977]: ansible-ansible.legacy.file Invoked with owner=testuser mode=0600 dest=/etc/haproxy/haproxy.cfg _original_basename=haproxy.cfg.j2 recurse=False state=file path=/etc/haproxy/haproxy.cfg force=False follow=True modification_time_format=%Y%m%d%H%M.%S access_time_format=%Y%m%d%H%M.%S unsafe_writes=False _diff_peek=None src=None modification_time=None access_time=None group=None seuser=None serole=None selevel=None setype=None attributes=None
Jun 29 20:20:41 test01 python3[12000]: ansible-ansible.legacy.stat Invoked with path=/etc/haproxy/haproxy.cfg follow=False get_checksum=True checksum_algorithm=sha1 get_md5=False get_mime=True get_attributes=True
Jun 29 20:20:41 test01 python3[12012]: ansible-ansible.legacy.file Invoked with owner=testuser mode=0600 dest=/etc/haproxy/haproxy.cfg _original_basename=haproxy.cfg.j2 recurse=False state=file path=/etc/haproxy/haproxy.cfg force=False follow=True modification_time_format=%Y%m%d%H%M.%S access_time_format=%Y%m%d%H%M.%S unsafe_writes=False _diff_peek=None src=None modification_time=None access_time=None group=None seuser=None serole=None selevel=None setype=None attributes=None
Jun 29 20:20:42 test01 python3[12035]: ansible-ansible.legacy.systemd Invoked with name=haproxy state=stopped daemon_reload=False daemon_reexec=False scope=system no_block=False enabled=None force=None masked=None


Jun 29 20:21:15 test01 systemd[1]: Starting Message of the Day...
Jun 29 20:21:15 test01 50-motd-news[12074]:  * Super-optimized for small spaces - read how we shrank the memory
Jun 29 20:21:15 test01 50-motd-news[12074]:    footprint of MicroK8s to make it the smallest full K8s around.
Jun 29 20:21:15 test01 50-motd-news[12074]:    https://ubuntu.com/blog/microk8s-memory-optimisation
Jun 29 20:21:15 test01 systemd[1]: motd-news.service: Succeeded.
Jun 29 20:21:15 test01 systemd[1]: Finished Message of the Day.
```
To be honest looking at these logs it doesn't tell me anything :/ hopefully does to you.

Let me know if u need any more logs.
Thanks

**Comment by joaogl** [comment]
This is all my playbook does actually.

```
---

- name: Override fully HAProxy config
  template:
    src: etc/haproxy/haproxy.cfg.j2
    dest: "/etc/haproxy/haproxy.cfg"
    owner: "{{ ansible_user }}"
    mode: "0600"
  with_items:
    - "{{ haproxy_backends }}"
    - "{{ haproxy_frontends }}"

- name: Restart HAProxy
  ansible.builtin.service:
    name: haproxy
    state: stopped

- name: Restart HAProxy
  ansible.builtin.service:
    name: haproxy
    state: started

```

Currently I have the stopped and then started due to a test I was doing to see if it worked since restarted wasn't.

**Comment by joaogl** [comment]
So I 'solved' it by just not using service from ansible and doing it by shell command. Tbh a bit stupid of me to now have thought this before but anyway if you want to keep this issue open I can keep trying to help and provide info about it. If u don't have interest in fixing this I guess the responsible person can close it.

Anyhow, this made it work:
```
- name: Restart HAProxy service
  shell: "service haproxy restart"
```

**Comment by wenottingham** [comment]
That would point to an issue with ansible itself, which would be filed at https://github.com/ansible/ansible

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

Mailing list: https://groups.google.com/forum/#!forum/awx-project
IRC: ansible-awx on irc.libera.chat
