### ISSUE TITLE
Boolean type for surveys

### ISSUE THREAD

**Issue by gfichera** [ansible/awx#1053]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
It would be great if in survey editor if we could choose a boolean formular.

##### ENVIRONMENT
* AWX version: 1.0.2.285
* AWX install method: docker on linux, 
* Ansible version:  2.4.2.0
* Operating System: Linux
* Web Browser: chrome

##### STEPS TO REPRODUCE

In job_template > edit_survey > answer_type 
adding a boolean type.

**Comment by wenottingham** [comment]
covered by https://github.com/ansible/awx/issues/553
