### ISSUE TITLE
19.2.2 `Ansible Tower` credential type missing

### ISSUE THREAD

**Issue by acelinkio** [ansible/awx#10539]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

`Ansible Tower` credential type is missing.

##### ENVIRONMENT
* AWX version: 19.2.2
* AWX install method: awx-operator version: 19.2.2 on kubernetes v1.21.2+k3s1
* Ansible version:  4.1.0
* Operating System: Ubuntu 20.04
* Web Browser: Chrome

* awx.awx collection version: 19.2.2

##### STEPS TO REPRODUCE
* Navigate to Create New Credential page
* Call via ansible module awx.awx.tower_credential

##### EXPECTED RESULTS
* `Ansible Tower` credential type is listed on Create New Credential page
* wx.awx.tower_credential module creates `Ansible Tower` credential. 
successful pipeline reference: https://gitlab.com/acelinkit/monopipeline/-/jobs/1384500576
```
TASK [AWX Credentials] *********************************************************
changed: [localhost]
```

##### ACTUAL RESULTS
* `Ansible Tower` credential type is missing on Create New Credential page.
* awx.awx.tower_credential module fails creating `Ansible Tower` credential. 
failed pipeline reference: https://gitlab.com/acelinkit/monopipeline/-/jobs/1384500915
```
TASK [AWX Credentials] *********************************************************
fatal: [localhost]: FAILED! => changed=false 
  msg: Request to /api/v2/credential_types/?name=Ansible+Tower returned 0 items, expected 1
  query:
    name: Ansible Tower
  response:
    json:
      count: 0
      next: null
      previous: null
      results: []
    status_code: 200
  total_results: 0
  ```

##### ADDITIONAL INFORMATION
git compare between two above pipelines: 
https://gitlab.com/acelinkit/monopipeline/-/compare/main...awx19.2.2%2Foperator0.12.0?from_project_id=27349704

awx playbook for above pipelines: 
https://gitlab.com/acelinkit/monopipeline/-/blob/main/awx/playbook.yaml

**Comment by acelinkio** [comment]
https://github.com/ansible/awx/blob/19.2.2/awx/ui_next/src/screens/Credential/shared/data.credentialTypes.json#L48-L112

Looks like `Ansible Tower` credential type should still be showing

**Comment by wenottingham** [comment]
It should be there as 'Red Hat Ansible Automation Platform' (type: `controller`). Let us know if that doesn't work.

**Comment by acelinkio** [comment]
@wenottingham that worked, thanks.

I see in source code where this changed now. 
 https://github.com/ansible/awx/blob/19.2.2/awx/main/models/credential/__init__.py#L1020-L1072  

/awx/ui_next/src/screens/Credential/shared/data.credentialTypes.json is confusing
