### ISSUE TITLE
Using ansible.cfg

### ISSUE THREAD

**Issue by jovestefanovski** [ansible/awx#10540]
##### ENVIRONMENT
* AWX version: 19.2.1
* AWX install method:  fedora server 34 docker
* Operating System: fedora

##### SUMMARY
Hi everyone
I have successfully installed AWX on fedora using docker, created my project and did couple of tests and deployments and everything seems to be good so far.
I'm trying to find a way how can I make use of ansible.cfg inside the project container, since everytime I run the job template verbosely  it shows No config file. The purpose of this would be to implement SSH pipelining which I believe it's supported here and speed up role execution. 
Can someone point me what is the recommended and proper way to include ansible.cfg in my project.

##### STEPS TO REPRODUCE
Prepare the environment

Sync the project 

Run the template

##### ADDITIONAL INFORMATION
![image](https://user-images.githubusercontent.com/77723434/123785111-71e06900-d8d8-11eb-84ec-27f5f93a1790.png)

**Comment by shanemcd** [comment]
https://docs.ansible.com/ansible-tower/latest/html/administration/tipsandtricks.html#locate-and-configure-the-ansible-configuration-file

>While Ansible does not require a configuration file, OS packages often include a default one in /etc/ansible/ansible.cfg for possible customization. In order to use a custom ansible.cfg file, place it at the root of your project.
