### ISSUE TITLE
Job template Edit Form- Max character limit error handling not functioning as intended

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#10544]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When a user goes to the details page of a template and clicks Edit, and changes the name of the template to something that exceeds the max character limit of 512 characters, when they click save, the screen refreshes and brings back the original template name, and no error message appears. If you click on the API error message in the Network tab, and then click back in the name field and delete characters alternately while clicking outside of the field, the error message briefly appears and then disappears. see GIF

##### ENVIRONMENT
Chrome, e2 Cluster

##### STEPS TO REPRODUCE

![edit-form](https://user-images.githubusercontent.com/63685497/123851470-37cb9300-d8e9-11eb-8d16-10edd5acec29.gif)

**Comment by tiagodread** [comment]
Fixed
