### ISSUE TITLE
"ERROR! Unexpected Exception, this is probably a bug: HTTP Error 400: Bad Request", ????

### ISSUE THREAD

**Issue by duchri66** [ansible/awx#10553]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: installer
* AWX deployment target: Rhel 7 VM
* Operating System:
* Web Browser: mozilla

##### STEPS TO REPRODUCE

When I start my project to get source from gitlab, they need to fetch the galaxy collection, but I get this error:
{
  "msg": "non-zero return code",
  "cmd": [
    "ansible-galaxy",
    "collection",
    "install",
    "-r",
    "/var/lib/awx/projects/_9__ansible_f5/collections/requirements.yml",
    "--collections-path",
    "/var/lib/awx/projects/.__awx_cache/_9__ansible_f5/stage/requirements_collections"
  ],
  "stdout": "Process install dependency map\n|\b/\b-\b\\\b|\b/\b-\b\\\b|\b/\b-\b\\\b|\b/\b-\b\\\b|\b/\b-\b\\\b|\b/\b-\b\\\b|\b/\b-\b\\\b|\b/\b-\b\\\b|\b/\b-\b\\\b|\b/\b-\b\\\b|\b/\b-\b\\\b|\b/\b-\b\\\bto see the full traceback, use -vvv",
  "stderr": "ERROR! Unexpected Exception, this is probably a bug: HTTP Error 400: Bad Request",
  "rc": 250,
  "start": "2021-06-29 20:10:37.919357",
  "end": "2021-06-29 20:10:43.286513",
  "delta": "0:00:05.367156",
  "changed": false,
  "invocation": {
    "module_args": {
      "chdir": "/var/lib/awx/projects/_9__ansible_f5",
      "_raw_params": "ansible-galaxy collection install -r /var/lib/awx/projects/_9__ansible_f5/collections/requirements.yml --collections-path /var/lib/awx/projects/.__awx_cache/_9__ansible_f5/stage/requirements_collections \n",
      "warn": true,
      "_uses_shell": false,
      "stdin_add_newline": true,
      "strip_empty_ends": true,
      "argv": null,
      "executable": null,
      "creates": null,
      "removes": null,
      "stdin": null
    }
  },
  "stdout_lines": [
    "Process install dependency map",
    "|\b/\b-\b\\\b|\b/\b-\b\\\b|\b/\b-\b\\\b|\b/\b-\b\\\b|\b/\b-\b\\\b|\b/\b-\b\\\b|\b/\b-\b\\\b|\b/\b-\b\\\b|\b/\b-\b\\\b|\b/\b-\b\\\b|\b/\b-\b\\\b|\b/\b-\b\\\bto see the full traceback, use -vvv"
  ],
  "stderr_lines": [
    "ERROR! Unexpected Exception, this is probably a bug: HTTP Error 400: Bad Request"
  ],
  "_ansible_no_log": false,
  "item": {
    "changed": false,
    "stat": {
      "exists": true,
      "path": "/var/lib/awx/projects/_9__ansible_f5/collections/requirements.yml",
      "mode": "0644",
      "isdir": false,
      "ischr": false,
      "isblk": false,
      "isreg": true,
      "isfifo": false,
      "islnk": false,
      "issock": false,
      "uid": 0,
      "gid": 0,
      "size": 84,
      "inode": 41943169,
      "dev": 64771,
      "nlink": 1,
      "atime": 1624992890.3374925,
      "mtime": 1623437073.9349754,
      "ctime": 1623437073.9349754,
      "wusr": true,
      "rusr": true,
      "xusr": false,
      "wgrp": false,
      "rgrp": true,
      "xgrp": false,
      "woth": false,
      "roth": true,
      "xoth": false,
      "isuid": false,
      "isgid": false,
      "blocks": 8,
      "block_size": 4096,
      "device_type": 0,
      "readable": true,
      "writeable": true,
      "executable": false,
      "pw_name": "root",
      "gr_name": "root",
      "checksum": "6b07a90842adfd9de5835c3af635ca30428aabce",
      "mimetype": "unknown",
      "charset": "unknown",
      "version": null,
      "attributes": [],
      "attr_flags": ""
    },
    "invocation": {
      "module_args": {
        "path": "/var/lib/awx/projects/_9__ansible_f5/collections/requirements.yml",
        "follow": false,
        "get_md5": false,
        "get_checksum": true,
        "get_mime": true,
        "get_attributes": true,
        "checksum_algorithm": "sha1"
      }
    },
    "failed": false,
    "item": {
      "ext": ".yml"
    },
    "ansible_loop_var": "item"
  },
  "ansible_loop_var": "item",
  "_ansible_item_label": {
    "changed": false,
    "stat": {
      "exists": true,
      "path": "/var/lib/awx/projects/_9__ansible_f5/collections/requirements.yml",
      "mode": "0644",
      "isdir": false,
      "ischr": false,
      "isblk": false,
      "isreg": true,
      "isfifo": false,
      "islnk": false,
      "issock": false,
      "uid": 0,
      "gid": 0,
      "size": 84,
      "inode": 41943169,
      "dev": 64771,
      "nlink": 1,
      "atime": 1624992890.3374925,
      "mtime": 1623437073.9349754,
      "ctime": 1623437073.9349754,
      "wusr": true,
      "rusr": true,
      "xusr": false,
      "wgrp": false,
      "rgrp": true,
      "xgrp": false,
      "woth": false,
      "roth": true,
      "xoth": false,
      "isuid": false,
      "isgid": false,
      "blocks": 8,
      "block_size": 4096,
      "device_type": 0,
      "readable": true,
      "writeable": true,
      "executable": false,
      "pw_name": "root",
      "gr_name": "root",
      "checksum": "6b07a90842adfd9de5835c3af635ca30428aabce",
      "mimetype": "unknown",
      "charset": "unknown",
      "version": null,
      "attributes": [],
      "attr_flags": ""
    },
    "invocation": {
      "module_args": {
        "path": "/var/lib/awx/projects/_9__ansible_f5/collections/requirements.yml",
        "follow": false,
        "get_md5": false,
        "get_checksum": true,
        "get_mime": true,
        "get_attributes": true,
        "checksum_algorithm": "sha1"
      }
    },
    "failed": false,
    "item": {
      "ext": ".yml"
    },
    "ansible_loop_var": "item"
  }
}

IF I run the command from the VM or from the docker container everything run well

bash-4.4# ansible-galaxy collection install -r /var/lib/awx/projects/_9__ansible_f5/collections/requirements.yml --collections-path /var/lib/awx/projects/.__awx_cache/_9__ansible_f5/stage/requirements_collections
[WARNING]: The specified collections path '/var/lib/awx/projects/.__awx_cache/_9__ansible_f5/stage/requirements_collections' is not part of the
configured Ansible collections paths '/var/lib/awx/.ansible/collections:/usr/share/ansible/collections'. The installed collection won't be picked up in
an Ansible run.
Process install dependency map
Starting collection install process
Installing 'f5networks.f5_modules:1.10.1' to '/var/lib/awx/projects/.__awx_cache/_9__ansible_f5/stage/requirements_collections/ansible_collections/f5networks/f5_modules'
Installing 'ansible.netcommon:2.2.0' to '/var/lib/awx/projects/.__awx_cache/_9__ansible_f5/stage/requirements_collections/ansible_collections/ansible/netcommon'
Installing 'ansible.utils:2.3.0' to '/var/lib/awx/projects/.__awx_cache/_9__ansible_f5/stage/requirements_collections/ansible_collections/ansible/utils'
bash-4.4# 

##### EXPECTED RESULTS

 ![image](https://user-images.githubusercontent.com/44244102/123956052-490fb080-d978-11eb-8ac7-a8cba5d6ee17.png) 

##### ACTUAL RESULTS

 ![image](https://user-images.githubusercontent.com/44244102/123955861-1d8cc600-d978-11eb-890b-77fa0e7f3d17.png)

**Comment by wenottingham** [comment]
The 400 error is from the galaxy server you're talking to; there's nothing we can fix in AWX. It's likely just a service blip on the galaxy side (or possibly incorrect credentials).
