### ISSUE TITLE
AWX UI is not accessible when installed on a system in private network which is running behind a proxy_server

### ISSUE THREAD

**Issue by ptrinesh** [ansible/awx#10552]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX UI is not accessible when installed on a system in private network which is running behind a proxy_server

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: Kubernetes
* Ansible version:  2.11.2
* Operating System: Centos 8.3
* Web Browser:

##### STEPS TO REPRODUCE

Install awx on private network which is running behind a proxy server

##### EXPECTED RESULTS

AWX pods should be up and running with UI being accessible

##### ACTUAL RESULTS

AWX pods are running but neither UI is accessible nor check logs for the containers inside pod

##### ADDITIONAL INFORMATION

I tried declaring the proxy server details in awx.yml file with the below variables but the containers doesn't get the internet
tower_task_extra_env: |
	- name: HTTP_PROXY
	  value: http://ip:port/
	- name: http_proxy
	  value: http://ip:port/
	- name: https_proxy
	  value: http://ip:port/
	- name: HTTP_PROXY
	  value: http://ip:port/
	- name: no_proxy
	  value: 127.0.0.1,localhost,host_ip,10.96.0.0/12,10.244.0.0/16,.example.com
	- name: NO_PROXY
	  value: 127.0.0.1,localhost,host_ip,10.96.0.0/12,10.244.0.0/16,.example.com
tower_web_extra_env: |

**Comment by wenottingham** [comment]
Just to understand I'm reading this right - your deployment is setting proxy environment variables that the service will use when connecting to other services. It will not do anything about how your local web browser will access the UI.

You'd need to figure out how to handle your container networking and kubernetes ingress routes; that is not the way to do it.

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

Mailing list: https://groups.google.com/forum/#!forum/awx-project
IRC: ansible-awx on irc.libera.chat
