### ISSUE TITLE
Patch request for inventory groups-  multiple API requests being repeated

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#10551]
When the user edits a group inside of an inventory, and the PATCH request is made, the API responds with multiple repeated API requests. See 2 different GIFs I recorded.

![api-response (1)](https://user-images.githubusercontent.com/63685497/123866474-1ecbdd80-d8fb-11eb-892b-aac7dc1c11f6.gif)
![api-response](https://user-images.githubusercontent.com/63685497/123866485-225f6480-d8fb-11eb-85db-36d7fb8cff23.gif)

**Comment by nixocio** [comment]
I evaluated the amount of requests being made, and they are not affecting the performance of the app. They are not optimal, but they still do not affect the usability. Also there is another general issue tracking extra requests here - https://github.com/ansible/awx/issues/10655. Closing as dupe.
