### ISSUE TITLE
Missing rsync in the awx_task container

### ISSUE THREAD

**Issue by tdgroot** [ansible/awx#1056]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - Installer

##### SUMMARY

Missing rsync in the awx_task container. I fixed it by running `yum install rsync -y` within the container, but the synchronize module should work out of the box in AWX. 

Please let me know if this is intended behavior, or if I can make a PR regarding this issue.

##### ENVIRONMENT
* AWX version: quite recent (commit hash 09d63b48839736c377271ea47303d5a1e89f3c07)
* AWX install method: docker on linux
* Ansible version:  2.4.2
* Operating System: Fedora Workstation 27
* Web Browser: Chrome 63

##### STEPS TO REPRODUCE

Run a task within AWX using the [synchronize](http://docs.ansible.com/ansible/latest/synchronize_module.html) module.

##### EXPECTED RESULTS

The synchronize module uses rsync to synchronize files.

##### ACTUAL RESULTS

The synchronize module can't find rsync in path -- it's not installed.

**Comment by shanemcd** [comment]
PR would be appreciated.
