### ISSUE TITLE
Build AWX from source and start awx_task & awx_web

### ISSUE THREAD

**Issue by emailvenkatm** [ansible/awx#1057]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY
I am trying build the docker image from the source. I have used the below commands to build and start the containers successfully for awx .

make docker-compose-build
make docker-compose

One difference I found while building the AWX like this it is only starting one container "tools_awx_1" where as if you use the installer it has two images awx_task and awx_web. Can you please let me know how can I built these two images from source. I haven't find any references for awx_task and awx_web in the Makefile. Please help. 

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by shanemcd** [comment]
The make targets you have mentioned are for standing up the AWX development environment. The installer is intended to deploy AWX inside of OpenShift, Kubernetes, or a standalone Docker environment.

> Can you please let me know how can I built these two images from source.

See [these](https://github.com/ansible/awx/blob/devel/installer/inventory#L5-L6) lines in the inventory file for the installer for how to build the images locally.

I believe this answers your questions so I'm going to close this issue, but if I have misunderstood what you are asking for please follow up and we will re-open.

**Comment by emailvenkatm** [comment]
@shanemcd Thanks for the reply. So once after I make the changes in inventory file, do I have to use ansible-playbook to build the image? are there any options that I can use docker-compose. Please help

**Comment by emailvenkatm** [comment]
@shanemcd can you please help?

**Comment by shanemcd** [comment]
@emailvenkatm Please see the documentation here: https://github.com/ansible/awx/blob/devel/INSTALL.md#start-the-build-2

For docker-compose support see: https://github.com/ansible/awx/blob/devel/installer/inventory#L48-L51

GitHub Issues are for reporting bugs. For getting general help please see "WHERE CAN I FIND SUPPORT FOR AWX?" on this page: https://www.ansible.com/products/awx-project/faq
