### ISSUE TITLE
AWX 19.2.0 cant map LDAP groups to team

### ISSUE THREAD

**Issue by rdzielicki** [ansible/awx#10602]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

On AWX 19.2.0,
tried to map an organization and a team ( belong to this org) ad group as admin

### AWX version

AWX 19.2.0

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

Create an org and a team which it belongs
Map your group search

- Use LDAP organization map to map some admin ( AD group)
- Use LDAP Team map to map this group to team

LDAP Organization Map
{
  "ProjectA": {
    "admins": [
      "CN=Admins,OU=Administration,DC=ad,DC=integration,DC=int,DC=local"
    ],
    "remove_admins": true
  }
}

LDAP Team Map
{
  "ProjectA": {
    "organization": "ProjectA",
    "users": [
      ""CN=Admins,OU=Administration,DC=ad,DC=integration,DC=int,DC=local"
    ],
    "remove": true
  },
  "Other Team": {
    "organization": "Test Org 2",
    "users": "CN=Admins,OU=Administration,DC=ad,DC=integration,DC=int,DC=local",
    "remove": true
  }
}

### Expected results

User from those group is member of the team and the org and can create workflow & templates ie

### Actual results

User is not member from a team and cannot create something, doesnt see the objects that belongs to org team

**Comment by rdzielicki** [comment]
My AD user which belongs to "CN=Admins,OU=Administration,DC=ad,DC=integration,DC=int,DC=local" is neither belonging to team or organization whuch it should be mapped, it just display as normal user with no relationships

**Comment by rdzielicki** [comment]
Go a little bit further, AD is user is now part from org and Team but the organization LDAP mapping with admin rights doesnt work

**Comment by rdzielicki** [comment]
{
  "Org": {
    "remove_admins": false,
    "admins": "CN=Admins,OU=Administration,DC=ad,DC=integration,DC=int,DC=local",
    "remove_users": false,
    "users": true
  }
}

{
  "Org_Team": {
    "remove": true,
    "users": "CN=Admins,OU=Administration,DC=ad,DC=integration,DC=int,DC=local",
    "organization": "Org"
  }
}

**Comment by rdzielicki** [comment]
AD user is still a simple user ( member) not admin org cant figured out why

**Comment by shanemcd** [comment]
Hello. This seems like a problem with your configuration, and unfortunately we dont have the resources to help you debug this. You may have better luck troubleshooting on IRC or the mailing list.

#ansible-awx on https://libera.chat/
https://groups.google.com/forum/#!forum/awx-project

**Comment by rdzielicki** [comment]
Had the same behaviour at another setup with different AD, does someones had succesfully configured Team or admin member automatically with AWX AD configuration?
