### ISSUE TITLE
Assign user with sechedule  

### ISSUE THREAD

**Issue by riadhhamdi** [ansible/awx#10600]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Schedules launch job templates/workflow templates without assigning them a user. 

Can we define the **awx_user_id** or the **tower_user_id** of the job launched by a schedule as the user who creates the schedule

**Comment by aminst** [comment]
Hi,
I hope you are doing well.
As I have understood so far, Are you suggesting a created-by field in the scheduled jobs?
I assume I will need to add a new field to the `Schedule` model, do the migrations, and update the UI, am I right?
I would like to develop this feature, this is my first open-source contribution and I hope it goes well.

**Comment by aminst** [comment]
I think this feature can be implemented similar to the `by <owner>` field in the job detail.
Like below:
![image](https://user-images.githubusercontent.com/12907963/126355861-de59c678-f00b-497b-b9e5-42fb0662247c.png)

**Comment by briantist** [comment]
Hi @aminst I saw your message on IRC but you had already left. I'm not a contributor or user of AWX so hopefully you'll be able to chat with someone involved in the project (I recommend returning to IRC during European and/or North American daytime hours).

In the meantime, I'd say check out the general contributing advice on the project's README: https://github.com/ansible/awx#contributing

If you haven't already, start by forking the repository in GitHub so you can get your local copy set up and start to make changes, which you can then push up and create a Pull Request.

**Comment by aminst** [comment]
> Hi @aminst I saw your message on IRC but you had already left. I'm not a contributor or user of AWX so hopefully you'll be able to chat with someone involved in the project (I recommend returning to IRC during European and/or North American daytime hours).
> 
> In the meantime, I'd say check out the general contributing advice on the project's README: https://github.com/ansible/awx#contributing
> 
> If you haven't already, start by forking the repository in GitHub so you can get your local copy set up and start to make changes, which you can then push up and create a Pull Request.

Hi @briantist, hope you are doing well.
I would definitely check it out.
Thanks a lot for your response, It really helped. :+1:

**Comment by aminst** [comment]
Hello again, @riadhhamdi  I think this feature already exists.
AWX only assigns users to user-created schedules, as you can see in the attached picture I am assigned as the creator of the schedule.
If you mean this functionality, it's already there, please correct me if I understood your feature proposal wrong.

![image](https://user-images.githubusercontent.com/12907963/126525729-53aa481c-b7bb-4dd1-a1fd-65cb17ae1dc7.png)

**Comment by AlexSCorey** [comment]
This have been resolved in awx devel
![Screen Shot 2021-10-28 at 12 05 38 PM](https://user-images.githubusercontent.com/39280967/139293712-29d5f4f4-038e-4540-b7ec-801c6646152b.png)
![Screen Shot 2021-10-28 at 12 05 15 PM](https://user-images.githubusercontent.com/39280967/139293719-2fdd4ef4-4b3a-44c2-89d5-14dc0aa7e17f.png)
![Screen Shot 2021-10-28 at 12 04 57 PM](https://user-images.githubusercontent.com/39280967/139293809-340f925f-f873-423c-87e3-58ee8259d2b9.png)
