### ISSUE TITLE
how to uninstall awx?

### ISSUE THREAD

**Issue by razerzhang** [ansible/awx#10609]
i used playbook install awx.
command like this :

>  ansible-playbook -i inventory install.yml

but i want to change default ui language  'en-us' into 'zh' , so i would like to reinstall awx

**Comment by jakemcdermott** [comment]
Hello, I don't think you need to reinstall for this - please try changing the preferred language in your browser's settings.

**Comment by razerzhang** [comment]
> Hello, I don't think you need to reinstall for this - please try changing the preferred language in your browser's settings.

HI, I had changed the preferred  the setting of the language of the browser ,but the translation in browser is not exact.
so, I want to change the ### 

> LANGUAGE_CODE = 'en-us' 

into 

> LANGUAGE_CODE = 'zh'  which written in the default.py of the awx/setting.
In this case, I have to reinstall awx.
Whether there some better ways ？
Thank you！

**Comment by yangshuDBA** [comment]
LANGUAGE_CODE = 'zh-Hans‘
http://www.i18nguy.com/unicode/language-identifiers.html
