### ISSUE TITLE
how to use django.po change ui language?

### ISSUE THREAD

**Issue by razerzhang** [ansible/awx#10615]

**Comment by wenottingham** [comment]
You don't, the language to show is selected by the browser language settings.

If you'd like to contribute a new translation, that's done by contributing a new po file.

**Comment by razerzhang** [comment]
> You don't, the language to show is selected by the browser language settings.
> 
> If you'd like to contribute a new translation, that's done by contributing a new po file.

I use chrome as web browser，and I had change language setting as chinese but its still show English
Version: 17.1.0
System: centos 
Browser System: mac ox
 
DON`T kown which step is wrong
Thanks!

**Comment by razerzhang** [comment]
> You don't, the language to show is selected by the browser language settings.
> 
> If you'd like to contribute a new translation, that's done by contributing a new po file.

I use chrome as web browser，and I had change language setting as chinese but its still show English
Version: 17.1.0
System: centos
Browser System: mac ox

DON`T kown which step is wrong
Thanks!
