### ISSUE TITLE
No Convergence Data in Workflow Node Info Modal

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#10628]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

We need to include convergence data in a workflow node info modal

### AWX version

devel

### Installation method

docker for mac

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

Create a workflow node.  Hover over the node and click on the `i` icon.  

### Expected results

See all the data about the node including the convergence data.

### Actual results

No convergence data included

### Additional information

![Screen Shot 2021-07-12 at 3 33 43 PM](https://user-images.githubusercontent.com/39280967/125345467-94d23a80-e326-11eb-8f28-a9dd4f7d078b.png)
![Screen Shot 2021-07-12 at 3 33 38 PM](https://user-images.githubusercontent.com/39280967/125345473-96036780-e326-11eb-97cb-edf49d49402b.png)

**Comment by akus062381** [comment]
upon testing this, found a bug when clicking on the info button of a node. Wambugu is working on filing a bug.

**Comment by AlexSCorey** [comment]
@akus062381 Can we close this issue?

**Comment by akus062381** [comment]
@AlexSCorey because of the bug, I am unable to verify whether this particular issue has been solved, so i'd say we are blocked until https://github.com/ansible/awx/issues/11061 is fixed

**Comment by akus062381** [comment]
Duplicate: https://github.com/ansible/awx/issues/10945

**Comment by InnocentK** [comment]
Issue causing the block (#11061) was resolved

**Comment by InnocentK** [comment]
Successfully resolved
