### ISSUE TITLE
> You don't, the language to show is selected by the browser language settings.

### ISSUE THREAD

**Issue by razerzhang** [ansible/awx#10624]
> You don't, the language to show is selected by the browser language settings.
> 
> If you'd like to contribute a new translation, that's done by contributing a new po file.

I use chrome as web browser，and I had change language setting as chinese but its still show English
Version: 17.1.0
System: centos 
Browser System: mac ox
 
DON`T known which step  gets wrong
Thanks!

_Originally posted by @razerzhang in https://github.com/ansible/awx/issues/10615#issuecomment-877907090_

**Comment by wenottingham** [comment]
Hi, please don't spam the isuse tracker.

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

Mailing list: https://groups.google.com/forum/#!forum/awx-project
IRC: ansible-awx on irc.libera.chat
