### ISSUE TITLE
Can't make a path available in job isolation

### ISSUE THREAD

**Issue by pscudamore** [ansible/awx#10627]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

I rely heavily on ansible for automating vmware environments. I use modules such as vmware_deploy_ovf to do so. I have created a volume through the extra_volumes directive and mounted it with ee_extra_volume_mounts, tasks_extra_volume_mounts, and web_extra_volume_mounts. I have confirmed the mount is available in all of these containers. I have checked the permissions and made them 777 so that there should be no "permissions" issue. 

I have added /data (the mount point) as a job isolation in the gui, as well as through the CLI by modifying AWX_ISOLATION_SHOW_PATHS.

I have also tried changing the execution path from /tmp to /data. When I do this nothing works, which tells me I am still not connecting my /data to the actual execution environment.

### AWX version

19.2.2

### Installation method

kubernetes

### Modifications

yes

### Ansible version

2.11.2 (from the ee container)

### Operating system

Ubuntu 20.04

### Web browser

Firefox, Chrome

### Steps to reproduce

- Install AWX
-  configure an extra volume
- set awx isolation show path in gui
- set AWX_ISOLATION_SHOW_PATHS in awx cli 
- Configure any playbook which relies on making data such as isos available to the playbook
-  playbook reports that the file cannot be found

### Expected results

I expect to be able to make files in an extra volume available to my playbooks

### Actual results

file not found

### Additional information

ubuntu 20.04 running on XFS. External postgresql running on the ubuntu host.
awx-operator 0.12.0 installed on microk8s
using nodeport for service_type and controlling tls through nginx installed on the ubuntu host os.
/opt/ansible-data on the HOST OS has been added to all three containers as data-vol1 which has been mounted in all three containers by the (ee/awx/task)_extra_volume_mounts directive.

**Comment by shanemcd** [comment]
Hello. The variables you tried to use are specific to mounting volumes inside the control plane pods. Please look into customizing the pod definition on the default container group. You can use any volume method supported by your Kubernetes.
