### ISSUE TITLE
Email notification for selected Controller Node Admin Operations

### ISSUE THREAD

**Issue by pierre-amadio** [ansible/awx#10630]
This is a follow up of issue#10276
Loic Avenel (lavenel@redhat.com) invited to re open this issue under a new title.

This is related to Red Hat support ticket#2945448 and to awx's issue#10050 .
As there is no way to deny a local root user from changing the tower admin password with awx-manage changepassword admin , it would be interesting to be able to generate email alert when such an event occurs.

**Comment by wenottingham** [comment]
As noted in #10276, the recommendation in lieu of any product changes is to get these updates from the activity stream.

**Comment by shanemcd** [comment]
Thank you for the issue, we have been discussing this with other stakeholders and are looking at options for how handling this event type could be improved. Updates will be provided here when they are available.

**Comment by ffirg** [comment]
There is no change here to the original suggestion which is to use external logging to capture activity_stream events.
