### ISSUE TITLE
Receptor-based capacity checks / auto-discovery

### ISSUE THREAD

**Issue by jladdjr** [ansible/awx#10637]
Questions we're chewing on:
* controller nodes and execution nodes - how to manage heartbeats for different types of nodes?
  * currently, it does look like we're keying off of the work commands advertised by nodes. If the list of commands includes `ansible-runner`, we consider that an execution node.

Our current understanding of how a heartbeat happens:
* awx controller runs heartbeat task
* (fetches list of nodes sending advertisements)
* launches receptor job against receptor node
* which runs ansible-runner to call setup module and collect facts
* a custom event_handler then stores cpu, memory, and version info
* which then gets stored in the instance endpoint by the controller

**Comment by jladdjr** [comment]
Brought up cluster using `make docker-compose-cluster` and can see capacity + mem, cpu, version info on the three receptor execution nodes ✅ 
![image](https://user-images.githubusercontent.com/4440360/125537649-977c3927-d06f-4dff-a75f-824f190f81f4.png)

The awx_1 node does not have capacity .. even though it has an `ansible-runner` command listed in its receptor conf file ❌ 
.. and the receptor hop node is not listed as a node at all ✅

**Comment by jladdjr** [comment]
This looks like something we'll need to dig into:
![Screen Shot 2021-07-13 at 16 39 47](https://user-images.githubusercontent.com/4440360/125538893-f0f305c1-0966-48cb-b560-f1fa32b8521c.png)

**Comment by jladdjr** [comment]
Looked through startup logs for my cluster, not seeing an obvious sign why awx_1 specifically would not have received any capacity. I'm also not sure I'm seeing any evidence that there was a check for its capacity in the first place.

**Comment by AlanCoding** [comment]
@jladdjr I thought the last commit I pushed addressed the issue about `get_default_execution_environment` not being in imports.

Also, isn't the intent that "awx_1" is a control node? I believe this may have even been the intention in Ryan's PR. The current diff has the existing heartbeat logic removed, and this is something that I don't agree with. Control nodes should update their own capacity IMO. Using the receptor mesh for that is unwanted complexity.

For our first pass, I'm okay if we only support control-only nodes and execution-only nodes (abuse of the version field is sufficient for this). Later on after we merge with the other pod, we can add in support for control+execution nodes. This still implies that the 1 control node, "awx_1" should update its capacity with the current logic in devel. We need to bring that back in, but it will take some careful consideration of the periodic task structure.

**Comment by AlanCoding** [comment]
> launches receptor job against receptor node

Really important detail - it only launches the job if a new node is discovered.

That means that right now we don't have any kind of "heartbeat" for the execution-only nodes. That introduces a number of more granular challenges, and my card about handling "lost" instances is intended to cover that.
