### ISSUE TITLE
Enhance AWX support for PostgreSQL replication scenarios

### ISSUE THREAD

**Issue by ghost** [ansible/awx#1063]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Add support in AWX for a single write-only database instance and read from one of a number of replicated read-only database instances.

##### ENVIRONMENT
* AWX version: 1.0.1

##### STEPS TO REPRODUCE

This change would allow connection of a Tower instance to any one of a number of database instances distributed for performance or reliability.

**Comment by wenottingham** [comment]
This is not currently planned to be investigated for AWX at any point in the near future; the architecture for use in containerized AWX would likely be very different in any case.
