### ISSUE TITLE
Misaligned Icons on Template List

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#10642]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Misaligned icons on template list - see `Actions` text.

<img width="1480" alt="image" src="https://user-images.githubusercontent.com/9053044/125677863-04b64d79-6310-4dac-9ad7-6d645edb34d0.png">

### AWX version

devel

### Installation method

docker for mac

### Modifications

no

### Steps to reproduce

Go to template `https://localhost:3001/#/templates`

### Expected results

We will need to verify whether we want to align icons per `actions` word or to move `actions` to align with icons. Be consistent across the UI.

### Actual results

Misaligned icons and text.

**Comment by AlexSCorey** [comment]
I agree that this does look weird, however I don't really think this is a true misalignment.  If the user has a workflow template on the list the `Actions` label is aligned properly.  Perhaps there is some way to figure out whether there are workflow temples being rendered, and if not, change the alignment a little bit?
![Screen Shot 2021-08-12 at 1 14 10 PM](https://user-images.githubusercontent.com/39280967/129239682-f04201d2-defb-4f81-b00b-13de95244acd.png)

**Comment by keithjgrant** [comment]
I think the best answer here, if PF allows it, is to right align the word "Actions" inside its `<th>`, since the action buttons are also right-aligned in their cell

**Comment by nixocio** [comment]
I followed up about this with @trahman73. 

>we can align both the header (word) of just actions and icons to the right

We have several tables that we will need to update in order to make this consistent across the application. We will need to inspect the application.

To exemplify:

![image](https://user-images.githubusercontent.com/9053044/131358832-78b66a54-7d44-4b19-9c2f-4639c2755be0.png)


![image](https://user-images.githubusercontent.com/9053044/131358861-6a4fafa4-0e78-4305-a933-d7b2bb8c3afd.png)

**Comment by AlexSCorey** [comment]
This has `align-right` to all of the `Actions` headers on all of the lists.
