### ISSUE TITLE
Organizations Access tab does not show last name correctly

### ISSUE THREAD

**Issue by tvo318** [ansible/awx#10649]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

First name and last name shows up the same even though the user has different first and last names.
![image](https://user-images.githubusercontent.com/7514801/125722706-fc44e4a1-e897-4ede-8ebc-4613a32e0ebc.png)

### AWX version

Ansible Automation Platform 4.0.0

### Installation method

docker for mac

### Modifications

no

### Ansible version

2.10 ( I assume )

### Operating system

Mac OS Mojave

### Web browser

Chrome

### Steps to reproduce

1. Create a user with proper first and last name.
2. In the organization screen, click Access to add said user.
3. The access screen now shows that user but the last name is the same as first name.

### Expected results

The access screen with added user should have correct last name and first name.

### Actual results

Last name is the same as first name.

### Additional information

![image](https://user-images.githubusercontent.com/7514801/125723814-be0afdd8-e9e5-4a8b-8bab-90c61455c793.png)

**Comment by nixocio** [comment]
Hello @tvo318, this issue was fixed on devel. See: https://github.com/ansible/awx/pull/10543
