### ISSUE TITLE
Issue with migrate on existing Ansible Tower installation with awx-manage

### ISSUE THREAD

**Issue by dillonwelch** [ansible/awx#1064]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

`awx-manage migrate --noinput --fake-initial` gets stuck on `Applying main.0007_v320_data_migrations...`

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
not sure
* Ansible version:  X.Y.Z
* Operating System: Ubuntu
* Web Browser: CLI

##### STEPS TO REPRODUCE

This happened when trying to upgrade a Ansible Tower installation from 3.1.3 to 3.2.2.

##### EXPECTED RESULTS

Migration proceeds past this step or at least provides more output

##### ACTUAL RESULTS

Gets stuck on this step

**Comment by matburt** [comment]
For Ansible Tower you should contact your Red Hat support rep.
