### ISSUE TITLE
Normal User with admin rights can't add job template

### ISSUE THREAD

**Issue by davidoiknine** [ansible/awx#10650]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Hello everyone,

I am having a problem with the roles and permissions of users and teams in AWX.
I feel like there are many ways to do the same thing and I get a little confused.

To explain my problem, I created a new normal user. I assigned him all possible rights (I think) but the user still does not have the possibility to add a job template.

What is the right way to add rights to a team, then to a specific user please?
How can I activate the "add job template" option?

Thank you so much,

### AWX version

17.0.1

### Installation method

docker on linux

### Modifications

no

### Ansible version

2.9.17

### Operating system

Redhat 8.3

### Web browser

Chrome

### Steps to reproduce

**Assign a user to a team:**
Go to _Teams_ > Select the team
Go to _Access_ tab.
Click on _Add_
Select _Users_
Select the User
Select: Admin, read, and member roles

**Assign roles to a team:**
Go to _Teams_ > Select the team
Go to _Access_ tab.
Click on _Add_
Select _Teams_
Select the team
Select: Admin, read, and member roles

### Expected results

The expected result is a user with admin, member and read rights associated to a team with admin, member and read rights.
The user should be able to add a job template.

### Actual results

The user is not able to add a job template.

**Comment by AlexSCorey** [comment]
Might be related to https://github.com/ansible/awx/issues/10386

**Comment by davidoiknine** [comment]
> Might be related to #10386

Thank you

**Comment by davidoiknine** [comment]
Hello,

I found the issue. I needed to sync AWX with git first. Its working now.
Closing the case.

Thanks
