### ISSUE TITLE
Update SurveyList to use draggable data list as per mock ups

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#10654]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Mockup:

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/9053044/125801248-3285764c-41f0-4bf1-89c6-de0e1881addc.png">

This patternfly component was added after the first implementation of this screen.

https://www.patternfly.org/v4/components/data-list/#draggable

Current implementation:

<img width="1491" alt="image" src="https://user-images.githubusercontent.com/9053044/125801431-7e985daf-92e6-43ac-bdd7-697d7ed77abc.png">

**Comment by AlexSCorey** [comment]
After conversation with @trahman73 we think it makes the most sense to re-utilize the preview modal.  Currently that modal shows that same data as the list itself.  
With the new functionality we could rename the preview button to be `Edit Order` and the user would click on that to be able to reorder the survey questions using the drag and drop functionality.  This looks better, improves UX, and it means the user no longer has to be in `isLoading` each time they move a survey question up or down 1 row.  They can move all of the questions as many rows as they want, save the order, and see it reflected in the new list after they save.

**Comment by trahman73** [comment]
Updated flow:
List view - https://tower-mockups.testing.ansible.com/patternfly/templates/templates-survey/
Edit order modal - https://tower-mockups.testing.ansible.com/patternfly/templates/templates-survey-preview/

**Comment by akus062381** [comment]
implemented and looks great
