### ISSUE TITLE
AWX and Satellite Integration Not Syncing Properly

### ISSUE THREAD

**Issue by cira-jonathan** [ansible/awx#10652]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

When I set up the dynamic inventory in AWX to sync hosts from Satellite it will sync all my hosts but it only synced two groups. Specially the host groups on my satellite server. 

### AWX version

AWX 19.1.0

### Installation method

minishift

### Modifications

no

### Ansible version

Ansible 2.9.21

### Operating system

RHEL 7

### Steps to reproduce

1. Ensure the user account and role are appropriately created on the satellite server as per the documentation regarding dynamic inventory setup on awx with satellite.
2. Log into the awx server
3. Create a credential resource on the awx server for using the account created on satellite
4. Create an inventory that'll sync the hosts from the satellite server.
5. Initiate the sync between awx and satellite.

### Expected results

1. All hosts are synced in addition to hosts groups, lifecycle environments, organizations, content views, etc...

### Actual results

1. All hosts are synced and only the host groups are imported into the server.

### Additional information

Something noteworthy: Each hosts has all it's facts synced. I'm just missing the a number of groups to be synced.

**Comment by wenottingham** [comment]
Did you sent `want_host_groups`, `want_hostcollections` , and `want_organization` in the config?

See https://docs.ansible.com/ansible/latest/collections/theforeman/foreman/foreman_inventory.html#ansible-collections-theforeman-foreman-foreman-inventory for configuration parameters.

**Comment by cira-jonathan** [comment]
@wenottingham which config are you referring to? and is it on the awx server or the satellite server?

**Comment by wenottingham** [comment]
When configuring the inventory source in AWX, there's a field for entering the plugin configuration - YAML that describes how the plugin should act. Available parameters are in the above liked docs. Otherwise, it will just use whatever the plugin defaults are.

**Comment by cira-jonathan** [comment]
@wenottingham can you provide an example/screenshot as to where exactly that configuration would be created when setting up the inventory?

**Comment by wenottingham** [comment]
The "source variables box", as shown here: https://docs.ansible.com/ansible-tower/latest/html/userguide/inventories.html#ug-source-satellite

**Comment by cira-jonathan** [comment]
@wenottingham Ok perfect. So I tried that and it worked. Is there a way to get the lifecycle environment group?

**Comment by cira-jonathan** [comment]
@wenottingham I know I can use a host filter but I want to be able to grab the other groups in addition to lifecycle environments.

**Comment by wenottingham** [comment]
If it's not something covered by the plugin options here: https://docs.ansible.com/ansible/latest/collections/theforeman/foreman/foreman_inventory.html it would need added to the plugin itself.

We get the plugin from https://github.com/theforeman/foreman-ansible-modules/ - you'd file an RFE there.

Given your above comment, I'm closing this as working - glad it does.
