### ISSUE TITLE
/api/v2/metrics using Ansible Tower favicon

### ISSUE THREAD

**Issue by gabyfulchic** [ansible/awx#10653]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Differents favicons between AWX web_ui & api metrics endpoint.

### AWX version

19.2.2

### Installation method

kubernetes

### Modifications

no

### Web browser

Firefox, Chrome

### Steps to reproduce

Use your web browser (I tried with Chrome/Firefox) : 

reach : 
- http://your_awx_endpoint/
- http://your_awx_endpoint/api/v2/metrics

You will see when reaching the metrics path that the logo become the Ansible Tower one.
On the `devel` branch I can see on the api index file `awx/ui_next/public/index.html` the below code : 
```html
{% block style %}
<link href="{% static 'favicon.ico' %}?v={{tower_version}}" rel="shortcut icon" />
{{ block.super }}
{% endblock %}
```

Btw It seems to be voluntary. (it's written tower_version)
But is it normal ?

### Expected results

I don't have the context, but I think it could be good to have the same favicon for each awx instance's URNs. :+1: 

### Actual results

Currently, when reaching the api metrics endpoint I see the Tower logo. :+1: 

### Additional information

The `git blame` output : 
```bash
78ccf3c6743 awx/templates/rest_framework/api.html (Jeff Bradberry  2021-02-19 14:56:26 -0500 12) <link href="{% static 'favicon.ico' %}?v={{tower_version}}" rel="shortcut icon" />
```

The commit summary on github.com : https://github.com/ansible/awx/commit/78ccf3c674370b87d4f462a09e971e1ffc5ef588

**Comment by wenottingham** [comment]
This is what https://github.com/ansible/awx/pull/10578 is for

**Comment by gabyfulchic** [comment]
Ok so I can close I guess :+1: 
Ty for your response. :smile: 

Ps : I should had checked Issues & PR (closed/opened), mybad :+1:
