### ISSUE TITLE
When creating a new host auto-populate inventory field is not working

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#10663]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

When creating a new host auto-populate inventory field is not working.

### AWX version

devel

### Installation method

docker for mac

### Modifications

no

### Steps to reproduce

1 - Attempt to create a new host - when there is just one inventory available

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/9053044/125836821-12a80c51-250c-4e00-8a91-b7634bddb644.png">

<img width="1484" alt="image" src="https://user-images.githubusercontent.com/9053044/125836862-1d65b6ae-17fb-4948-b201-c8228c3c2457.png">

### Expected results

Inventory lookup field to be auto-populated

### Actual results

Inventory lookup field is not auto-populated

**Comment by tiagodread** [comment]
PR already merged
