### ISSUE TITLE
Move ui_next to non-temporary source location

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#10676]
requires https://github.com/ansible/awx/pull/10562
* Move `awx/ui_next` to its non-temporary source location `awx/ui`
  * Unify code paths, django config, etc. where needed
  * Update any `ui_next` references in docs
  * Update README.md: `AWX-PF` -> `AWX-UI`, code snippets, examples, etc.
  * `package.json` version should match awx version, or just remove the version
  * Update external testing pipelines, Dockerfiles, etc.

**Comment by akus062381** [comment]
Looks great!
