### ISSUE TITLE
Error handling for execution node capacity checks

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#10677]
When doing a remote ansible-runner run, errors can happen at a lot of different levels:

 - streaming errors from ansible-runner, or a runner version mismatch
 - podman errors
 - other receptor mesh problems

Right now, the `check_heartbeat` task (incorrectly named) checks the capacity of an execution-only node as it joins the mesh. It has no error handling.

Jobs, themselves, have very complex handling, which can in various cases lead to a `receptorctl work list` or a `receptorctl work results <unit_id>` type command.

The capacity discovery method needs to have error handling as good as jobs do, and if an error does occur, it needs to take an action that will leave the system in an easily recoverable state. Because we are _not_ running as a periodic task, it will register the instance with capacity=0. This leaves it in a state that is unusable and not correctable short of running `awx-manage` commands. If the capacity check fails, the node should not be added, or it should be put in some other sort of penalty box.

**Comment by jladdjr** [comment]
> check_heartbeat task (incorrectly named)

yep, seems like we should have heartbeat checks for control nodes
.. but _health_ checks for execution nodes

heartbeat => are you there?
healthcheck => can you do all the things needed in order to run a job?

**Comment by AlanCoding** [comment]
@AlexSCorey new idea:

What if we introduce a new field for instances, like `problem_details` for example, and if we hit one of these scenarios where we set `capacity=0` (meaning you can't run jobs on it), then we will populate this field with something similar to what we write in the logs today.

For example, say the execution node had the wrong version of Ansible runner. This instance should be greyed out in the UI, or somehow marked as unusable. In the detail views, the UI would show the text we save, which would be something like:

> Instance has ansible-runner version 2.0.0 installed, but version 2.1.2 is required for compatibility

**Comment by AlanCoding** [comment]
I was considering making a new issue

> When execution node capacity check fails, save error details in the model and surface in the UI.

If @AlexSCorey  agrees, I can split that out into a new issue

**Comment by AlanCoding** [comment]
A lot of this is addressed by https://github.com/ansible/awx/pull/10825

However, we still have an issue with tracking the `modified` times. There's a completely new paradigm for execution nodes, where the `modified` time will reflect the last checkin time from `receptorctl status`, not the last save time.

I left a TODO that we should include execution nodes in our loop where we mark instances as lost which do not update their `modified` time sufficiently frequently. However, we have an issue, from discussion with @fosterseth 

> How often is "Last Seen" updated in a cluster that is functionally normally (give me worst case scenario)?

```
// defaultServiceAdTime is the interval at which regular service advertisements will be sent.
const defaultServiceAdTime = 60 * time.Second
```

> it's hard coded to send once per minute
> Last Seen is based on that serviceAdTime

So I will leave this issue open to be closed when we have robust logic for identifying "lost" execution nodes.

----

There's yet another issue that I might need to spin off into another issue. We run the heartbeat too often. Back when we had isolated nodes, we had a field `last_isolated_check` which was used to coordinate the health checks between the controller nodes. We might need something like that, and we also might need to re-run health checks of broken nodes on a lower frequency.

**Comment by AlanCoding** [comment]
We have completed the things mentioned in this issue, closing.
