### ISSUE TITLE
Workflow Approval Minute and Second fields need attention

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#10682]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

The workflow approval nodes minute and second fields have some formatting issues.

### AWX version

devel

### Installation method

docker for mac

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

Create a workflow job template.
Create an approval node.
Go to 2nd stop of the wizard

### Expected results

The minute and second fields have proper spacing and proper labeling

### Actual results

see screen shot

### Additional information

![Screen Shot 2021-07-19 at 4 57 06 PM](https://user-images.githubusercontent.com/39280967/126226624-144c8541-3b67-42c1-bc88-477a2be8c28e.png)

**Comment by nixocio** [comment]
closing this one as duplicated - https://github.com/ansible/awx/issues/10515
