### ISSUE TITLE
Containerize remote execution node capacity checks

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#10686]
former title:

> Rethink execution-only images (re-use awx images to start with?)

I have started a WIP that uses the AWX image for execution nodes in the docker-compose-cluster environment - so that the checks can run containerized. Eventually, this is so that jobs can run containerized too.

However, there are snags in doing this. The CPU capacity metric works when ran inside of a container, but the current memory metric does not work. This might be fixable, or we might have to rethink some fundamentals of the design.

**Comment by jladdjr** [comment]
Pushed the new auto-merge button on https://github.com/ansible/awx/pull/10688

**Comment by jladdjr** [comment]
@AlanCoding we can close this, ya?

**Comment by AlanCoding** [comment]
still need to figure out how to merge it, but yes
