### ISSUE TITLE
make docker-compose-build error

### ISSUE THREAD

**Issue by dikaye** [ansible/awx#10697]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

$ make docker-compose-build
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
ansible-playbook tools/ansible/dockerfile.yml -e build_dev=True
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]. This feature will be 
removed from ansible-core in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
[WARNING]: An error occurred while calling ansible.utils.display.initialize_locale (unsupported locale setting). This may result in incorrectly calculated text widths that can cause Display to print incorrect line lengths

PLAY [Render AWX Dockerfile and sources] ************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [dockerfile : Create _build directory] *********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [dockerfile : Render supervisor configs] *******************************************************************************************************************************************************************************************
ok: [localhost] => (item=supervisor.conf)
ok: [localhost] => (item=supervisor_task.conf)

TASK [dockerfile : Render Dockerfile] ***************************************************************************************************************************************************************************************************
ok: [localhost]

PLAY RECAP ******************************************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

DOCKER_BUILDKIT=1 docker build -t quay.io/awx/awx_devel: \
    --build-arg BUILDKIT_INLINE_CACHE=1 \
    --cache-from=quay.io/awx/awx_devel: .
invalid argument "quay.io/awx/awx_devel:" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
make: *** [Makefile:504: docker-compose-build] Error 125

What's mean invalid argument "quay.io/awx/awx_devel:" for "-t, --tag" flag: invalid reference format?
How to fix it?

### AWX version

awx-19.2.2

### Installation method

docker on linux

### Modifications

no

### Steps to reproduce

make docker-compose-build

### Expected results

invalid argument "quay.io/awx/awx_devel:" for "-t, --tag" flag: invalid reference format

### Actual results

invalid argument "quay.io/awx/awx_devel:" for "-t, --tag" flag: invalid reference format

**Comment by shanemcd** [comment]
It looks like we derive the tag name from the current git branch, and you dont have git installed.

https://github.com/ansible/awx/blob/devel/Makefile#L523

https://github.com/ansible/awx/blob/devel/Makefile#L18
