### ISSUE TITLE
Error in "Activate AWX Web Container"

### ISSUE THREAD

**Issue by jains99** [ansible/awx#107]
### I am getting below error, can someone please help in this.

TASK [local_docker : Activate AWX Web Container] *****************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error starting container e1aafa9640be17735e06a62d849f162c8f37a4ecb313120cd15c648801443349: 500 Server Error: Internal Server Error (\"{\"message\":\"driver failed programming external connectivity on endpoint awx_web (341dfd8ec7a60b3a5ce95b5bb8c0ec7177cf4e79d55d940acfa89b36c331b02f): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use\"}\")"}

### Environment

* AWX version: awx-1.0.0.317
* Ansible version:  2.3.1.0
* Operating System: CentOS 7.3
* npm -v 
3.0.0
* node -v
v6.11.3

**Comment by jains99** [comment]
I changed the port to 8080 and executed ansible playbook again. It is working fine now.

**Comment by lousyd** [comment]
You changed what port to 8080? Where? inventory?

**Comment by amostech** [comment]
Having the same issue here. 

@jains99 where exactly can you change the port from 80 to 8080?
