### ISSUE TITLE
Settings Field Disappears

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#10706]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Disable the built-in authentication system field disappears when the confirmation modal is open, then reappears when the modal closes.  I would expect that field to remain rendered the whole time.

### AWX version

devel

### Installation method

docker for mac

### Modifications

no

### Steps to reproduce

Go to Settings -> Authentication Settings -> Edit -> Click on the `Disable the built-in authentication system` switch to turn it on..

### Expected results

Modal opens to confirm, and the field in question is rendered on the screen in the background.

### Actual results

Modal opens to confirm, and the field in question is not rendered on the screen in the background.

### Additional information

![disappearingfield](https://user-images.githubusercontent.com/39280967/126533360-43f7b96c-cb1c-47b2-a07b-d058eb59c549.gif)

**Comment by tiagodread** [comment]
This was fixed by #10722
