### ISSUE TITLE
cleanup unused execution environment images job not working as intended

### ISSUE THREAD

**Issue by fosterseth** [ansible/awx#10702]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

original PR here https://github.com/ansible/awx/pull/9907

This cleanup task only removes dangling (untagged) podman images. If a user removes an EE, those images left on the system will still be tagged, but ideally they would be removed too.

We need to revisit this.

### AWX version

awx: 19.2.2

### Installation method

docker on linux

### Modifications

no

### Steps to reproduce

- change the celerybeat_schedule in defaults.py for `cleanup_images` to run once per 30 seconds or so
- create EE images
- Associate them with EEs in awx
- Remove the EE in awx
- Wait 30 seconds to make sure cleanup job runs (will produce debug statement log as well)
- podman images -a will still show the disassociated images on the system

### Expected results

Images should be removed

### Actual results

not removed

**Comment by Zokormazo** [comment]
Seems fixed now
