### ISSUE TITLE
Cleanup unused images in execution nodes

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#10701]
We have this task:

https://github.com/ansible/awx/blob/68e309ee3281eb725f38b88ffa84959e1c007937/awx/main/tasks.py#L384-L399

That has a couple of problems when we introduce the control plane / execution plane split.

 - This task should not do anything if it is ran on a control-only node. Depending on installer changes, those nodes may not have podman installed.
 - This won't run at all on execution-only nodes.

**Comment by AlanCoding** [comment]
Marking as blocked, because we may hold off pending solution for https://github.com/ansible/awx/issues/10702

**Comment by jladdjr** [comment]
We could see this tying in to the work to clean up the private data dir via a background task - see https://github.com/ansible/awx/issues/10948

**Comment by jladdjr** [comment]
Wanted to note that this may have already be an issue with awx and hybrid nodes (before execution nodes were introduced).

**Comment by jladdjr** [comment]
We need to check on the existing behavior for this and make sure that at the very least we haven't regressed on this. On the latest release do we have containers / images that get left behind? What do we see happening today?

**Comment by AlanCoding** [comment]
You can't say we regressed, because we never removed images from deleted EEs to begin with.

I'm leaving the door open to addressing this in conjunction with https://github.com/ansible/ansible-runner/pull/846, but I'm not committing to it.
