### ISSUE TITLE
Editing a managed job schedule can return null fields

### ISSUE THREAD

**Issue by kialam** [ansible/awx#10718]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

It is possible to edit a managed job schedule and have the API return `null` for requisite fields.

Discovered when looking into #10587

![time_warp](https://user-images.githubusercontent.com/2293210/126654476-c840f34b-db6c-4d89-b27e-26b7e2952b89.gif)

### AWX version

AWX 19.2.2

### Installation method

docker for mac

### Modifications

no

### Steps to reproduce

1. Go to Management Jobs > Edit Job Schedule
2. Edit the start date of a management job
3. Select "On date" for when a management job ends
4. Enter end date
5. Observe that the UI shows "1970-01-01" for the start date section

Request payload is as follows:

```js
daysToKeep: "120"
description: "Automatically Generated Schedule"
extra_data: {days: "120"}
days: "120"
name: "Cleanup Job Schedule"
occurrences: 1
rrule: "DTSTART;TZID=Europe/Berlin:20210802T000100 RRULE:INTERVAL=1;FREQ=WEEKLY;BYDAY=SU;UNTIL=20210803T000600"
runOnTheOccurrence: 1
```

Response payload from API:
```js
created: "2021-07-06T20:50:04.085408Z"
description: "Automatically Generated Schedule"
diff_mode: null
dtend: null
dtstart: null
enabled: true
extra_data: {days: "120"}
id: 1
inventory: null
job_tags: null
job_type: null
limit: null
modified: "2021-07-22T14:09:24.333570Z"
name: "Cleanup Job Schedule"
next_run: null
related: {modified_by: "/api/v2/users/1/", credentials: "/api/v2/schedules/1/credentials/",…}
rrule: "DTSTART;TZID=Europe/Berlin:20210802T000100 RRULE:INTERVAL=1;FREQ=WEEKLY;BYDAY=SU;UNTIL=20210802T220600Z"
scm_branch: null
skip_tags: null
summary_fields: {,…}
timezone: "Europe/Berlin"
type: "schedule"
unified_job_template: 1
until: "2021-08-03T00:06:00"
url: "/api/v2/schedules/1/"
verbosity: null
```

### Expected results

The schedule should update successful when edited.

### Actual results

The API returns `null` vaues for `dtstart, dtend, etc` thus causing the UI to show incorrect dates.

**Comment by shanemcd** [comment]
@chrismeyersfsu Thinks this might be expected behavior. We need to look into this more.

**Comment by kialam** [comment]
Checked the existing behavior on the old UI - the start date is not tied to `dtstart` but is rather a local variable. We'll have to figure out a way to address/mirror this in the new UI.

**Comment by kialam** [comment]
PF does have an empty state for the date picker, so I think it's reasonable to display that if the api returns `null` for the `dtstart` value:

<img width="268" alt="Screen Shot 2021-08-09 at 12 17 48 PM" src="https://user-images.githubusercontent.com/2293210/128761982-fdb8736a-6c26-4408-9bdd-1d4857c5e07a.png">

**Comment by tiagodread** [comment]
Closing this issue with the merge of #10898
