### ISSUE TITLE
AWX UI not coming up

### ISSUE THREAD

**Issue by vinneh** [ansible/awx#10728]
Basically the exact same issue as this:
https://github.com/ansible/awx/issues/10016

Except I am not using minikube, i deployed the operator on an existing 3 node kubernetes cluster. Browser returns blank screen, using curl or inspecting the source in browser reveals: "You need to enable JavaScript to run this app."

awx-web logs dont show any errors, this is what gets written when i hit it with curl:
2021-07-22 20:17:12,775 DEBUG    [d8f6ff4cfac94d259723a6899d9b087c] awx.analytics.performance request: <WSGIRequest: GET '/'>, response_time: 0.043s
[pid: 27|app: 0|req: 10/49] 10.244.0.0 () {34 vars in 372 bytes} [Thu Jul 22 20:17:12 2021] GET / => generated 1190 bytes in 45 msecs (HTTP/1.1 200) 7 headers in 269 bytes (1 switches on core 0)
10.244.0.0 - - [22/Jul/2021:20:17:12 +0000] "GET / HTTP/1.1" 200 1190 "-" "curl/7.29.0" "-"

**Comment by shanemcd** [comment]
> "You need to enable JavaScript to run this app."

Do you have JavaScript disabled?

**Comment by vinneh** [comment]
Yes, it is enabled. This is also the same from different browsers and PC's

**Comment by tgdfool2** [comment]
Same issue here, AWX 19.2.2 running on a 3-nodes AKS cluster.

**Comment by jakemcdermott** [comment]
Are you building your own container image or using the one we publish on quay?

When building a custom container image, you need to remember to run `make ui-devel` _before_ building the image.

**Comment by vinneh** [comment]
Using the ones from quay. These are pulled by the awx-operator. Just following the instructions from github to do a basic install.

quay.io/ansible/awx-operator             0.12.0              767fcffb0a57        3 weeks ago         434 MB
quay.io/ansible/awx                      19.2.2              8312f3577f1d        3 weeks ago         1.05 GB
quay.io/ansible/awx-ee                   0.5.0               8075aa937d7d        3 weeks ago         1.3 GB

**Comment by tgdfool2** [comment]
Also using the official images from quay (for Operator, AWX and EE). Tried to change the Ingress configuration to use the "new" `networking.k8s.io/v1` API instead of `extensions/v1beta1`, but this did not help.

Basically, when the cluster is restarted, the AWX Pod come alive, but the UI is not coming up (blank screen). Deleting the Pod and waiting for it to be recreated solves the issue.

Any idea of what could be wrong here?

**Comment by sergei-rybakov** [comment]
All the same things here: awx 19.2.2, minikube, awx-operator 0.12.0 default installation.
All was working fine just before VM reload. After reload AWX UI is blank with such errors:

"You need to enable JavaScript to run this app."

GET http://10.10.22.125:31467/static/js/runtime-main.7202f99a.js [HTTP/1.1 404 Not Found 1ms]
GET http://10.10.22.125:31467/static/js/2.53c634ac.chunk.js [HTTP/1.1 404 Not Found 1ms]
GET http://10.10.22.125:31467/static/js/main.6ab990a9.chunk.js [HTTP/1.1 404 Not Found 0ms]
Loading failed for the <script> with source “http://10.10.22.125:31467/static/js/runtime-main.7202f99a.js”. 10.10.22.125:31467:1:1
GET http://10.10.22.125:31467/static/js/2.53c634ac.chunk.js [HTTP/1.1 404 Not Found 1ms]
Loading failed for the <script> with source “http://10.10.22.125:31467/static/js/2.53c634ac.chunk.js”. 10.10.22.125:31467:1:1
GET http://10.10.22.125:31467/static/js/main.6ab990a9.chunk.js [HTTP/1.1 404 Not Found 1ms]
Loading failed for the <script> with source “http://10.10.22.125:31467/static/js/main.6ab990a9.chunk.js”. 10.10.22.125:31467:1:1
Source map error: Error: request failed with status 404
Resource URL: http://10.10.22.125:31467/static/css/2.687a9035.chunk.css
Source Map URL: 2.687a9035.chunk.css.map

after pod creation we have next mounts:
bash-4.4$ cd /var/lib/awx/                                                                                                                                                                                                           
awxfifo     .configsha  .local/     projects/   public/     rsyslog/    venv/

and after reboot:
bash-4.4$ cd /var/lib/awx/
awxfifo   .local/   projects/ rsyslog/  venv/

and if you execute "kubectl describe pods awx-xxx" and search for mount /var/lib/awx/public, you will not find any

**Comment by vinneh** [comment]
> Also using the official images from quay (for Operator, AWX and EE). Tried to change the Ingress configuration to use the "new" `networking.k8s.io/v1` API instead of `extensions/v1beta1`, but this did not help.
> 
> Basically, when the cluster is restarted, the AWX Pod come alive, but the UI is not coming up (blank screen). Deleting the Pod and waiting for it to be recreated solves the issue.
> 
> Any idea of what could be wrong here?

Thanks for that tip/ workaround, deleting the pod works here also.

**Comment by shanemcd** [comment]
This might have been fixed by https://github.com/ansible/awx/pull/10583

**Comment by jakemcdermott** [comment]
Possibly related as well? https://github.com/ansible/awx/issues/10816 

^ Seems like it could be.

**Comment by shanemcd** [comment]
Closing due to lack of response.
