### ISSUE TITLE
Consider Moving the Instances List to a Top Level List

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#10721]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
With the Mesh Code work that is coming in 4.1 there will likely be UI work that will add a feature to notify the user of a new instance, when it comes on line so the user can act on it (See https://github.com/ansible/awx/issues/10720).  In response to that we may also want to consider moving the Instances List into a top level list in the UI.  This issue, right now, is meant to just start that conversation.

@wenottingham @trahman73 @AlanCoding

**Comment by AlanCoding** [comment]
We also discussed the idea of having a notification queue, or some sort of queue, for nodes that have been discovered, but not yet put into an instance group. The question seems to be more of an "either" choice. Either a global instance list, or some sort of queue for processing, would solve the problem.

New instances we discussed with need two actions:

1. set the `enabled` flag to True
2. assign to an instance group

However, this all might be irrelevant soon with decisions around the installer, ping @chrismeyersfsu

**Comment by AlexSCorey** [comment]
IMO, since one of the 2 actions needed to be taken will be to assign the new instance to an instance group, I'd say we leave the list where it is.  When a new instance comes online we can notify the user, and provide a link to the instance group list, or we could perhaps provide some sort of modal that will allow them to assign the new instance to an instance group from the alert.

**Comment by AlanCoding** [comment]
We should probably abandon this entirely. Instance group membership will be defined in the inventory, and it was my misunderstanding that it would not be.

**Comment by wenottingham** [comment]
There is the future case of standalone nodes connected to a OCP-hosted mesh.

**Comment by mabashian** [comment]
@ffirg based on https://github.com/ansible/awx/issues/10721#issuecomment-885158741 - is this issue still relevant or can it be closed?

**Comment by AlanCoding** [comment]
I understand the UI's navigation flow better now, and this seems like it has come together fine. I would say "close"

**Comment by ffirg** [comment]
We have no current need for this given we do everything through the installer. We might need some sort of functionality like this in the future, but as that's unknown and timescales undefined, we'll close it and re-raise as needed.
