### ISSUE TITLE
[Backport Request] Hashicorp Vault Credential Plugin : Support for namespace

### ISSUE THREAD

**Issue by lucab85** [ansible/awx#10734]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The issue ( https://github.com/ansible/awx/issues/7399 ) has been fixed upstream as below links and we can use plugin code for the issue.
However, our customer can't use the plugin due to their system limitation. Therefore I would like to open the back port request to use this fix with 3.8.x release.

Upstream issue:
https://github.com/ansible/awx/issues/7399
Pull Request:
https://github.com/ansible/awx/pull/9590

##### COMPONENT NAME
- awx/main/credential_plugins/hashivault.py

**Comment by wenottingham** [comment]
We do not do backports in AWX.
