### ISSUE TITLE
Convert Survey List to Tables

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#10739]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
This table should not be sortable since the order of the survey questions matter.  The user can manage the question ordering by using the up and down button on the left side of the screen.  Also need to remove the inline labels (ie. Type)

Also consider doing this work too when doing this https://github.com/ansible/awx/issues/10654

**Comment by akus062381** [comment]
implemented and looks great
