### ISSUE TITLE
Handle unresponsive instances (when joining, when trying to run a job in that instance, and coming back online)

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#10737]
I want to note that, as of now, when I test running against a node which has gone off the receptor network, then it gets stuck in the running state.

The dispatcher should never attempt to send a job to a node which `receptorctl status` does not currently recognize. Instead, we should mark the instance as lost and provide details.

**Comment by jladdjr** [comment]
Studied how we run heartbeats, handle reaping etc.

Starting to make some updates here:
https://github.com/ansible/awx/compare/mesh_code...mesh_code_healthchecks?expand=1

**Comment by AlanCoding** [comment]
Let me just echo that I still hit the case mentioned in this issue. I run against an instance that has a receptor name which is not in the mesh. The job will eventually have:

> Task was marked as running but was not present in the job queue, so it has been marked as failed.

This might be a pre-existing issue, but it becomes important with execution nodes. It may very well be the case that receptorctl is giving some useful feedback, but we're not recognizing it, so we just keep trying to read from the pipe. The whole transmit function is probably putting it in a pipe-to-nowhere. There's got to be some useful debugging we can do for this.

It's probably overkill to check the network before starting a job. There is almost certainly some useful feedback from receptor that we're _not seeing_.

For this feature, however, we also need to add some special handling for the instance when this occurs. We need error handling, and then maybe submit the task to re-run the instance's health check. That would make a ton of sense.

**Comment by jladdjr** [comment]
> I run against an instance that has a receptor name which is not in the mesh. The job will eventually have 'Task was marked as running but was not present in the job queue, so it has been marked as failed.' ... It may very well be the case that receptorctl is giving some useful feedback, but we're not recognizing it, so we just keep trying to read from the pipe.

> The whole transmit function is probably putting it in a pipe-to-nowhere. There's got to be some useful debugging we can do for this.

@AlanCoding Reading through `awx.main.tasks.py:AWXReceptorJob._run_internal()` I think I see a spot where awx may be vulnerable to the kind of hanging that you're describing. When we transmit the job, we have a join() that can potentially wait forever. If we're trying to transmit to a node that doesn't exist, perhaps this is where we're hanging.

I'm wondering if we should use a timeout here. Something like this:

https://github.com/ansible/awx/compare/mesh_code...mesh_code_healthchecks?expand=1#diff-6fb7bd98930ec6a05c1ae9296b41b63921e1813dcee53895f16769f910917c38R3144

> It's probably overkill to check the network before starting a job.

Agreed. If we do the timeout, we give the transmit section time to do the right thing, but we check up on it if things seem like they're going nowhere.

If the transmission goes through, then that seems like a good indication that (1) the receptor mesh is healthy (at least, insofar as our execution node is concerned) and (2) that the execution node is able to run ansible-runner. The [next block](https://github.com/ansible/awx/blob/mesh_code/awx/main/tasks.py#L3149-L3178) that executes keeps an eye out for the job being cancelled and handles the case where the job actually hits an error.

I'm hitting the end of the day, but I'd like to see if I can reproduce the scenario you're running into to see if this helps fix things.

**Comment by AlanCoding** [comment]
> I'm wondering if we should use a timeout here. Something like this:

Looks promising. I agree that the timeout value should be something less than infinity. This scenario should be easy to test, and I'll be happy to run the scenario with that branch when you're ready for review.

**Comment by AlanCoding** [comment]
I'd like to get @fosterseth to look at that diff. I'm worried that we might miss something fundamental. It seems wacky that we would have to _time out_ in the event that the target `node` for the work is not online.

**Comment by fosterseth** [comment]
> If we're trying to transmit to a node that doesn't exist, perhaps this is where we're hanging.

in tasks.py, submit_work really just sets up the locally running receptor process to, later on, submit work on a remote node. If you are on nodeA, and do `submit work(node=nodeB)`, it doesn't try to transmit payload directly to nodeB. So receptor doesn't care about the state of nodeB at this point. As long as the local node A receptor is healthy, transmit should work just fine.

Once transmit is finished in tasks.py, the receptor then ships that payload (which is now just saved as `stdin` file on disk) to nodeB and starts the work there.

It's possible that transmit thread could be hanging somewhere, but I wouldn't expect it to be related to the health of any remote node.

**Comment by fosterseth** [comment]
additionally, a locally running receptor process is fine to receive work that intended for a remote node, whether that remote node is down or up currently. It will just periodically attempt to reach out to that node and start the work there. There is a `ttl` option in the work submit command that, if set, will time out and cancel the work if it never starts after the specified duration.

**Comment by jladdjr** [comment]
> a locally running receptor process is fine to receive work that intended for a remote node, whether that remote node is down or up currently. It will just periodically attempt to reach out to that node and start the work there. There is a ttl option in the work submit command that, if set, will time out and cancel the work if it never starts after the specified duration.

It seems like maybe we should [set the ttl](https://github.com/ansible/receptor/blob/devel/receptorctl/receptorctl/cli.py#L257) when calling submit_work (I don't see us doing this anywhere), and maybe, as an extra precaution, keep a timeout on the `join`.

**Comment by jladdjr** [comment]
Added ttl, going to kick the tires after I'm through with a couple meetings

**Comment by fosterseth** [comment]
yes, and `ttl` will only start counting down after the transmit is complete. So we definitely need separate error handling / timeouts for the transmit thread

To summarize, we could have the following timeouts in task.py

`pod_pending_timeout` - for container groups. If a pod doesn't enter Running phase by this timeout period, the work is canceled and failed.

`ttl` - for remote receptor jobs. If a remote work unit doesn't enter Running state by this time, the work is canceled and failed.

`transmit_timeout` (or whatever it will be called) - the timeout period for transmitting payload to the local receptor process (applies to both local work and remote work).

**Comment by AlanCoding** [comment]
I wound up using a lot of lessons from this in https://github.com/ansible/awx/pull/10825, but it's the health check, and the mechanics are different from jobs.

**Comment by jladdjr** [comment]
@AlanCoding has an update for this, can outline some items we should still tackle.

**Comment by AlanCoding** [comment]
Discussed with Elijah

https://gist.github.com/AlanCoding/33f79993fcf08f3b2dac47e5c5ea45cc

Some ideas still outstanding

 - Proposal: Reduced checks for broken execution nodes 
 - Proposal: Save error details on Instance model
 - Proposal: Re-run health checks via a new endpoint

**Comment by AlanCoding** [comment]
Idea for the future:

receptor can report some latency information, might be helpful in health check data.

**Comment by AlanCoding** [comment]
I believe all items discussed here are addressed in the PR 11002, which I'll merge in a bit here, moving to needs_test

**Comment by jladdjr** [comment]
@AlanCoding could you update this with latest context for @thenets ?

**Comment by AlanCoding** [comment]
I was posting some details in https://gist.github.com/AlanCoding/33f79993fcf08f3b2dac47e5c5ea45cc#file-health_check_wrapup-md, but I can reduce those points to something that looks more like a test plan here.

 - test the new `/api/v2/instances/N/health_check/`
   - system auditor can GET but not POST
   - system admin can GET and POST
 - check that successful health check
   - will clear `errors` field
   - will update `last_health_check` field
   - returns 200 code
   - test health check for different instance types in cluster (finished - in integration test)
 - test execution nodes with errors (see gist about how to do this in dev environment)
   - run a health check and see that previously-working node changes to not working, sets capacity to 0
   - run a health check and see that previously-broken node with error fixed sets capacity to non-zero
   - with a successful node, break it, then run a job against it, verify that instance health check sets capacity to 0 (the failed job will trigger a health check)

**Comment by jladdjr** [comment]
From the description at top:
> I want to note that, as of now, when I test running against a node which has gone off the receptor network, then it gets stuck in the running state.

@thenets - wanted to note that ticket sounds like it is describing the second reaping scenario that you and I talked about today:
https://github.com/ansible/tower/issues/5321

Seems like we can mark one of the two issues as a duplicate after we have a chance to revisit the scenario to see what the current state is.

**Comment by thenets** [comment]
Job reaping is working properly, so I believe that this can be closed.
