### ISSUE TITLE
Login page contain External Authentication Providers that are not enabled

### ISSUE THREAD

**Issue by matusb** [ansible/awx#1073]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Login page of AWX contain "SIGN IN WITH" (Azure AD, Google, Github, Github teams and Github org) after fresh installation.

##### ENVIRONMENT
* AWX version: 1.0.2 and 1.0.1
* AWX install method: docker on linux
* Ansible version:  
* Operating System: Ubuntu 16.04
* Web Browser: Not relevant, but tested on Chrome and Firefox

##### STEPS TO REPRODUCE
Install awx and check the login page

##### EXPECTED RESULTS
Login page should not contain "SIGN IN WITH" icons (unless external authentication providers are enabled)

##### ACTUAL RESULTS
Login page of AWX contain "SIGN IN WITH" Azure AD, Google, Github, Github teams and Github org.
![screenshot from 2018-01-26 14-28-45](https://user-images.githubusercontent.com/8266857/35503875-4cdea8f0-04d9-11e8-9245-44e4cfe806ba.png)

##### ADDITIONAL INFORMATION
I have tested few dockerhub_versions and the last version that is working as expected is 1.0.1.167. The issue is occurring since version 1.0.1.203 (maybe even version 1.0.1.176, I having issues running this version).

**Comment by jaredevantabor** [comment]
@matusb Did you happen to notice if there were any console errors in the web console?

**Comment by jaredevantabor** [comment]
These SSO icons show up if the API responds with configurations from `/api/v2/auth/` which is why these are showing up on the UI. I checked my local dev environment and I too have SSO settings defined on this endpoint despite not setting them up intentionally. Pinging @matburt for further API triage.

**Comment by ryanpetrello** [comment]
@matusb thanks for reporting!  This should be fixed in `devel` now.
