### ISSUE TITLE
We want to prevent jobs from being executed on all the hosts from inventory

### ISSUE THREAD

**Issue by garamirseokim** [ansible/awx#10748]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
We want to restrict Ansible Tower to execute a job template unless users specify ‘ALL’ value in the LIMIT field in Ansible Tower(Tower Dashboard -> TEMPLATES -> LIMIT). 
Because our inventory has a huge list of servers. If we don't specify anything in inventory and just launch a job template but it can run it on all the hosts in inventory by mistake.

Aslo,  “Prompt on Launch” option is not exactly what we are looking for. We have already given a prompt on launch option for inventories but users can still execute it on all the hosts.

**Comment by wenottingham** [comment]
This should be done by creating appropriate delegated inventories such that users only have permission to run on hosts that they should.

If you want users to have access to all hosts, but only run on the full inventory with approval, check out creating workflows with approval nodes, and making those workflows with approvals the items that users have access to run. You can also perform these checks in an external system such as a services catalog.
