### ISSUE TITLE
Add auto-discovered instances to a (to-be-created) "default" instance group.

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#10746]
The `default` instance group currently only exists on OCP installs.

We will need to add logic to create this `default` instance group on other install types as well.

Any newly discovered execution nodes in the mesh should go into the default group, disabled. (NOTE: the `disabled` state may still need more discussion) There could maybe be a setting that auto-enables the instances by default.

The process of enabling and putting into another group can be a day 2 operation.

**Comment by AlanCoding** [comment]
Putting on the "small" label, for a near-term focus on these objectives:

 - enabling the "default" group for all install types
 - adding auto-provisioned nodes to this group
 - probably mention this in `docs/receptor_mesh.md`

Discussions and revisions can still happen after that, but these items are clear and relatively easy.

**Comment by AlanCoding** [comment]
I had a mis-understanding. The installer _will_ run `awx-manage provision_instance` for execution nodes listed in the inventory file. This command can be responsible for making the nodes enabled if they were specified by the user. So add to the work items:

 - Make auto-discovered nodes disabled by default

**Comment by AlanCoding** [comment]
We should have a meeting with people in the other pod and a few high-level people to establish expectations about group memberships. Where memberships are set, what expectations of the groups are, and so on. There is a lot more work than what is outlined here that we need to do.

For example, we need to stop using the `controlplane` as a fallback for jobs.

**Comment by AlexSCorey** [comment]
Related: https://github.com/ansible/awx/issues/10853

**Comment by jladdjr** [comment]
> The default instance group currently only exists on OCP installs.
> We will need to add logic to create this default instance group on other install types as well.

Just wanted to note that I confirmed with @tchellomello yesterday that the `default` IG is created in trad installs as well.

**Comment by jladdjr** [comment]
@AlanCoding I _think_ https://github.com/ansible/awx/pull/10937 does what we want. Need to add some tests for this, but ad hoc testing confirmed the following changes:

- [x] `default` instance group created
- [x] auto-discovered nodes marked as disabled by default
- [x] .. and assigned to `default` instance group (by way of `policy_instance_list` )

**Comment by tchellomello** [comment]
> > The default instance group currently only exists on OCP installs.
> > We will need to add logic to create this default instance group on other install types as well.
> 
> Just wanted to note that I confirmed with @tchellomello yesterday that the `default` IG is created in trad installs as well.

@jladdjr  just for the purposes of documentation, here is where we handle the registration piece at the installer level (https://github.com/ansible/automation-platform-collection/blob/devel/roles/receptor/tasks/main.yml#L100-L151) for non-partial inventories

**Comment by AlanCoding** [comment]
I was debugging with @thenets and he definitely hit the "disabled by default" behavior

**Comment by jladdjr** [comment]
I ran into that myself today, too 👍
