### ISSUE TITLE
Add expand all for hosts lists

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#10740]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add expand all for hosts lists.

<img width="1484" alt="image" src="https://user-images.githubusercontent.com/9053044/126792020-4b0ad09c-1284-49c4-9f68-773a51d569b4.png">

See: https://github.com/ansible/awx/issues/4208

**Comment by akus062381** [comment]
implemented and works great
