### ISSUE TITLE
Error "Failed to connect to the host via ssh:  PLEASE HELP

### ISSUE THREAD

**Issue by gRach1997** [ansible/awx#10750]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Good afternoon, colleagues. I'm trying to run the software version check playbook on the switch. But when I try to connect via ssh, I get the error "Failed to connect to the host via ssh:

### AWX version

17.1.0

### Installation method

docker on linux

### Modifications

no

### Ansible version

ansible 2.9.18

### Web browser

Chrome

### Steps to reproduce

I created a playbook show_version.yml in which I described the following:
---

- name: Showversion
   hosts: all
   gather_facts: no
   ignore_errors: true
   tasks:
     - name: Showversion
       raw: show version

### Expected results

I expected the output to be like this:
sh-4.4# ansible-playbook show_version.yml 

PLAY [Showversion] *******************************************************************************************

TASK [Showversion] *******************************************************************************************
sw0-ap#show version 
Unit 1
 Serial Number:           406000938
 Hardware Version:        R01
 Chip Device ID:          Marvell 98DX106-B0, 88E6095[F]
 EPLD Version:            0.07
 Number of Ports:         28
 Main Power Status:       Up
 Redundant Power Status:  Not present

Agent (Master)
 Unit ID:                 1
 Loader Version:          1.0.4.1
 Boot ROM Version:        1.2.1.3
 Operation Code Version:  1.4.20.32

PLAY RECAP ***************************************************************************************************
10.254.18.27               : ok=0    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

### Actual results

sh-4.4# ansible-playbook show_version.yml 

PLAY [Showversion] *******************************************************************************************

TASK [Showversion] *******************************************************************************************
fatal: [10.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: \r\n***************************************************************\r\nLANTRACE\r\nWARNING - MONITORED ACTIONS AND ACCESSES \r\nDATANET\r\n\r\n\r\nStation's information:\r\nZavokzalna_7a_str_p.2_Boryspil\r\n\r\n - \r\nFloor / Row / Rack / Sub-Rack\r\n /  /  / \r\nDC power supply:\r\nPower Source A: Floor / Row / Rack / Electrical circuit\r\n /  /  / \r\n\r\n\r\nNumber of LP: \r\nPosition MUX: \r\nIP LAN: \r\nNote: \r\n***************************************************************\r\nShared connection to 10.0.0.1 closed.", "unreachable": true}

PLAY RECAP ***************************************************************************************************
10.0.0.1               : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   

### Additional information

When executing a playbook with the -vvv switch, I get the following result:
sh-4.4# ansible-playbook show_version.yml -vvv
ansible-playbook 2.9.18
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
Skipping callback 'actionable', as we already have a stdout callback.
Skipping callback 'counter_enabled', as we already have a stdout callback.
Skipping callback 'debug', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'full_skip', as we already have a stdout callback.
Skipping callback 'json', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'null', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
Skipping callback 'selective', as we already have a stdout callback.
Skipping callback 'skippy', as we already have a stdout callback.
Skipping callback 'stderr', as we already have a stdout callback.
Skipping callback 'unixy', as we already have a stdout callback.
Skipping callback 'yaml', as we already have a stdout callback.

PLAYBOOK: show_version.yml ***********************************************************************************
1 plays in show_version.yml

PLAY [Showversion] *******************************************************************************************
META: ran handlers

TASK [Showversion] *******************************************************************************************
task path: /var/lib/awx/projects/show_version/show_version.yml:8
<10.0.0.1> ESTABLISH SSH CONNECTION FOR USER: asoxx
<10.0.0.1> SSH: EXEC sshpass -d9 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="asoxx"' -o ConnectTimeout=10 -o ControlPath=/var/lib/awx/.ansible/cp/a075732807 -tt 10.0.0.1 'show version'
<10.0.0.1> (255, b'', b"\r\n***************************************************************\r\nLANTRACE\r\nWARNING - MONITORED ACTIONS AND ACCESSES \r\nDATANET\r\n\r\n\r\nStation's information:\r\nZavokzalna_7a_str_p.2_Boryspil\r\n\r\n - \r\nFloor / Row / Rack / Sub-Rack\r\n /  /  / \r\nDC power supply:\r\nPower Source A: Floor / Row / Rack / Electrical circuit\r\n /  /  / \r\n\r\n\r\nNumber of LP: \r\nPosition MUX: \r\nIP LAN: \r\nNote: \r\n***************************************************************\r\nShared connection to 10.0.0.1 closed.\r\n")
fatal: [10.0.0.1]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: \r\n***************************************************************\r\nLANTRACE\r\nWARNING - MONITORED ACTIONS AND ACCESSES \r\nDATANET\r\n\r\n\r\nStation's information:\r\nZavokzalna_7a_str_p.2_Boryspil\r\n\r\n - \r\nFloor / Row / Rack / Sub-Rack\r\n /  /  / \r\nDC power supply:\r\nPower Source A: Floor / Row / Rack / Electrical circuit\r\n /  /  / \r\n\r\n\r\nNumber of LP: \r\nPosition MUX: \r\nIP LAN: \r\nNote: \r\n***************************************************************\r\nShared connection to 10.0.0.1 closed.",
    "unreachable": true
}

PLAY RECAP ***************************************************************************************************
10.0.0.1               : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

**Comment by wenottingham** [comment]
This issue tracker is for tracking feature enhancements and bugs to AWX itself.

This looks like an issue with your playbook that you'd need to debug.
If you need help troubleshooting an ansible playbook, try our mailing list or IRC channel:

Mailing list: https://groups.google.com/forum/#!forum/ansible-users
IRC: ansible on irc.libera.chat
