### ISSUE TITLE
Allow token auth on websocket

### ISSUE THREAD

**Issue by phemmer** [ansible/awx#10764]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Currently the AWX websocket only works with session auth (login cookie). This prevents being able to use it with token auth.

The feature request is to allow token auth to the websocket.

**Comment by wenottingham** [comment]
What is yout use case for token auth on the websocket interface? What are you using it for?

**Comment by wenottingham** [comment]
I ask because the websocket interface is mostly a UI<->API contract, and is not a defined API that we commit to keeping and versioning.

**Comment by phemmer** [comment]
Ah. The use case is for streaming the job events. Specifically from a command line utility as part of a CI/CD system as well as for human use

Due to all the issues with awxkit (#10194 #10201 #10264), we wrote our own utility for kicking off jobs and monitoring the output. Currently the only method of streaming the output is by dealing with polling and paging. It's not a huge issue, but it's cumbersome, and I just figured the websocket would be a simpler/cleaner solution. And not to offend, but all the issues in #10194 just shows that even you guys, the maintainers of AWX, have trouble getting it right. So what chance do us normal folks have? :-)

**Comment by wenottingham** [comment]
For job events, we already do not have the websockets as 100% reliable - we drop websocket events when there are too many to send with the system under high load (at which point the UI refreshes from the API), and there is a maximum limit at which the underlying infrastructure (django channels) drops them. So I don't think we'd support more general access to the websocket API, sorry.
