### ISSUE TITLE
Rebase and update mesh code logic after `node_type` migration lands

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#10769]
We have a lot of TODOs in the `mesh_code` branch, and these are things we can resolve after https://github.com/ansible/awx/pull/10757 lands.

**Comment by rebeccahhh** [comment]
is this still blocked?

**Comment by AlanCoding** [comment]
https://github.com/ansible/awx/pull/10802

**Comment by jladdjr** [comment]
(moved over to In Progress column)

**Comment by AlanCoding** [comment]
closing as finished
