### ISSUE TITLE
{min} displayed in form field validation on Management job node within workflows

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#10778]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Follow up issue from: https://github.com/ansible/awx/pull/10572
Some management jobs require the number of days of data to be retained, this value must be >=0 trying to add a value -1 the message on validate says `This field must be a number and have a value greater than {min}`

### AWX version

devel

### Installation method

docker on linux

### Modifications

no

### Operating system

Ubuntu LTS

### Web browser

Chrome

### Steps to reproduce

1. Create a workflow job
2. Add a management job node "Cleanup Activity Stream"
3. Add "-1" as the number of days to keep

### Expected results

the message to be: This field must be a number and have a value greater than 0

### Actual results

This field must be a number and have a value greater than {min}

### Additional information

![image](https://user-images.githubusercontent.com/12464858/127382295-ec9ab3d1-aff2-4bc8-881f-540dba7d3790.png)

**Comment by AlexSCorey** [comment]
this seems to be fixed
![Screen Shot 2021-08-05 at 10 11 03 AM](https://user-images.githubusercontent.com/39280967/128365108-d4c661d5-ea8e-494a-a3da-817df499a3fb.png)
![Screen Shot 2021-08-05 at 10 11 37 AM](https://user-images.githubusercontent.com/39280967/128365110-56c9d4b6-728d-45e3-8ddf-0b56fda81c8f.png)

**Comment by tiagodread** [comment]
This can be closed, was fixed with #10703
