### ISSUE TITLE
[object Object] on Settings main page

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#10775]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Accessing the /#/settings route, for each setting section where were supposed to display the name of the product is being showed [object Object]  instead.  

### AWX version

devel

### Installation method

docker on linux

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

1. Install tower
2. Acess the settings page

### Expected results

The name of the product/component to be displayed 

### Actual results

![image](https://user-images.githubusercontent.com/12464858/127369829-0acf832a-bffe-4f65-a57a-1eeaff0f8850.png)

**Comment by tiagodread** [comment]
@nixocio All places where the `${brandName}` is displayed, the value of this variable is not showed properly, look:
I think this may be related to translation in variables, I used an tower ec2 instance from devel.


![image](https://user-images.githubusercontent.com/12464858/127885509-b91a8be1-7a90-45d8-bb24-152c8fce8fb6.png)

![image](https://user-images.githubusercontent.com/12464858/127885686-fa2e68dc-9ef2-4382-93ca-d49b9c4a75e4.png)

![image](https://user-images.githubusercontent.com/12464858/127885738-b7f166f1-1c69-4d8e-83e0-8424479ec293.png)

![image](https://user-images.githubusercontent.com/12464858/127885837-8422ac5b-25c9-4c84-b84d-fd41cb148141.png)

**Comment by nixocio** [comment]
Thanks @tiagodread , I will take a look.

**Comment by tiagodread** [comment]
All fixed
