### ISSUE TITLE
doc error with inventory plugin for latest awx.awx inventory plugin 

### ISSUE THREAD

**Issue by IPvSean** [ansible/awx#10776]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

The documentation for the inventory plugin, awx.awx.controller, was malformed.

rendered webpage for docs is here: https://docs.ansible.com/ansible/latest/collections/awx/awx/controller_inventory.html#ansible-collections-awx-awx-controller-inventory

### AWX version

N/A

### Installation method

openshift

### Modifications

no

### Ansible version

n/a

### Operating system

n/a

### Web browser

Chrome

### Steps to reproduce

go to https://docs.ansible.com/ansible/latest/collections/awx/awx/controller_inventory.html#ansible-collections-awx-awx-controller-inventory

there is docs errors on the webpage 

>The documentation for the inventory plugin, awx.awx.controller, was malformed.

### Expected results

no errors

### Actual results

![image](https://user-images.githubusercontent.com/6537680/127372510-15ad611c-3428-42ba-b719-c3b1468dbf27.png)

### Additional information

fast track this to infamous Chris Meyers

**Comment by gundalow** [comment]
Please make sure you are running `ansible-test sanity` from `devel`, that should help catch these errors.

**Comment by AlanCoding** [comment]
@gundalow in https://github.com/ansible/awx/pull/10788 @beeankha put up some more fixes after running `ansible-test sanity` with recent `devel`. These don't look related to the docs rendering stuff. Do you think those are related to the docs error? If not, can you point us in some other direction for how to test/fix this?

**Comment by Zokormazo** [comment]
I continue seeing the error on https://docs.ansible.com/ansible/latest/collections/awx/awx/controller_inventory.html#ansible-collections-awx-awx-controller-inventory

@beeankha @tvo318 @IPvSean how should be proceed to update the docs page?

**Comment by beeankha** [comment]
@Zokormazo I'll try to push some more fixes to this.

**Comment by Zokormazo** [comment]
The error continues being there. Will try to fix the pipeline to update this tomorrow

**Comment by vrubiolo** [comment]
Hi there, I am also still seeing the error. Any news on the fix? Thanks much!

**Comment by AlanCoding** [comment]
I still have some friction running [ansible-test sanity](https://github.com/ansible/ansible/issues/66704#issuecomment-995969223) locally and we don't have this hooked up in any automated way for the `devel` Ansible branch.

If I install it, `ansible-doc -t inventory awx.awx.controller` works just fine (again, with Ansible `devel`).

Right now I don't feel like I have enough info to replicate these errors.

**Comment by bcoca** [comment]
`deprecated` is supposed to be a dictionary, not a list of dictionaries

https://github.com/ansible/awx/blob/devel/awx_collection/plugins/doc_fragments/auth_plugin.py#L22

**Comment by felixfontein** [comment]
Also `ansible-test sanity` won't help since validate-modules still does not check plugins (see https://github.com/ansible/ansible/pull/71734).
