### ISSUE TITLE
Execute playbooks on single hosts

### ISSUE THREAD

**Issue by twcurrie** [ansible/awx#1077]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI
 - API

##### SUMMARY
It'd be great if the ui was able to execute playbooks on single hosts from inventories (both dynamic and static), not just ad hoc commands. 

##### ENVIRONMENT
* AWX version: 1.23
* AWX install method: docker for mac
* Ansible version:  2.4.0
* Operating System: Mac OSX
* Web Browser: Chrome

**Comment by shanemcd** [comment]
Is this what you're looking for?

<img width="1792" alt="ansible awx demo job template 2018-01-29 21-47-49" src="https://user-images.githubusercontent.com/773186/35545650-21120e8c-053e-11e8-851f-d5288670c1c5.png">

**Comment by twcurrie** [comment]
I was looking to specify a specific host from the inventory on job launch, similar to the inventory drop-down.  Alternatively, I was looking to specify a playbook within the host level ad-hoc command input.

**Comment by ryanpetrello** [comment]
@twcurrie take a look at @shanemcd's screenshot; the limit field (which is available for Job Template and Ad Hoc Command launches) allows you to specify a comma-delimited list of hosts you want to limit the run to.  It works just like the `--limit` argument to `ansible` and `ansible-playbook`.

Take a look at http://docs.ansible.com/ansible/latest/intro_patterns.html for more examples.

**Comment by ayyappabani** [comment]
you can use survey in Job template to enter hostname or ip-address using "ansible_host" variable..it works..
while executing job, select a target inventory with single host (dummy) added as "ansible_host"
<img width="550" alt="image" src="https://user-images.githubusercontent.com/52236829/115681864-8d784200-a372-11eb-8f98-deaec1fafbd3.png">
