### ISSUE TITLE
Add job id as part of the job details screen

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#10786]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add job id as part of the job details screen.

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/9053044/127536060-26cf5324-69c6-4373-bad4-878d52d89b32.png">

>a little bit of feedback: it would be very useful to see the job id on the job details / project updates details pages. and other things that have an id.

**Comment by akus062381** [comment]
@nixocio can you please add good locators to the elements in this section of the app?

Examples of good locators:

- data-OUIA-component-ID
- data-cy
- ID

Places they need to be added:

- Each of the <dd> fields in the table with all the information on the Job Details screen
- the Details and Output buttons (data-OUIA would be preferred)

**Comment by akus062381** [comment]
PR approved and merged :-)
