### ISSUE TITLE
Hand in list of credentials for awx_collection/plugins/modules/schedule.py

### ISSUE THREAD

**Issue by lotaris-xx** [ansible/awx#10782]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Love the awx.awx.schedule module, but have to the need to pass in different credentials. Currently I have a JT per credential, but that is messy. Seems like API supports this.

**Comment by wenottingham** [comment]
Are there other JT promptable fields that you can't set for a schedule?

**Comment by lotaris-xx** [comment]
I just did a comparison and don't see any others missing.

**Comment by sean-m-sullivan** [comment]
@lotaris-xx I was just reviewing this, and I am not seeing where you pass in credentials via schedule, Can you post how you are Invoking things now, and want to invoke them? I know we did the job template to accept list of credentials in the past, but trying to figure out which field you want as a list input in which module.

**Comment by lotaris-xx** [comment]
Sure,

I used to look for this every time I want to use it, but I've used it so much lately no need. If the JT Credentials field has "Prompt at launch" clicked, when you create a schedule based on that JT you click the "PROMPT" button down beside Cancel/Save and it will walk through all of the fields you can prompt for.

Cheers,
-Allen

________________________________

**Comment by lotaris-xx** [comment]
Currently I create a lot of schedules where the main differences between them are Limit, Inventory and Credentials. Limit and Inventory are directly handled by the schedule module, but Credentials isn't so I have to have to maintain a set of JTs per credential combination and track/schedule those unique JTs.  Looking to have the schedule module handle JT Credentials as well so I can return to a single JT per playbook that needs this kind of thing.

**Comment by sean-m-sullivan** [comment]
This is exactly what was needed to clarify, most likely just need to dive deeper into the api of a created one, and find out how it post it there, then we can figure out how to put it in the module.

**Comment by AlanCoding** [comment]
Resolved

https://github.com/ansible/awx/blob/1d340c5b4e91399e98926b3a681ebcefc4d02697/awx_collection/plugins/modules/schedule.py#L77-L81
