### ISSUE TITLE
Split the database user into two users, one for installation,upgarde and restore and one for normal running of Tower

### ISSUE THREAD

**Issue by cesarfn4** [ansible/awx#1079]
##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

- Installer
- API

##### SUMMARY

The enhancement request is to separate the database "schema owner" required for installation, upgrades and restores, from the tower database "operational user" which is required for normal operations.
Eg.   The DB user which creates (and more importantly perhaps) can drop tables should not be the operational database user which the AWX / Tower process uses to connect for day-to-day running of Tower.

The operational database user should be able to insert, query, (if required by the application) update rows in the AWX / Tower database.   It ideally should not be able to delete database, delete tables, create users etc.

What is being requested is a least privileged model for database users, separating the privileged user which creates the database from the operational user which uses it.

**Comment by ryanpetrello** [comment]
Doing something like this is going to complicate the code for the installation process considerably.  The only time you need a "schema owner" is for installations and restores (for initial database creation) and upgrades (for schema migrations); for users that are concerned about this, we recommend that they remove schema-related privileges (specifically, `CREATEDB`) post-install and add them back on upgrades and restores.

**Comment by shanemcd** [comment]
We have no plans of doing this.
