### ISSUE TITLE
Org level EVENT_STDOUT_MAX_BYTES_DISPLAY

### ISSUE THREAD

**Issue by benjdudas** [ansible/awx#10793]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Customer request to have the `EVENT_STDOUT_MAX_BYTES_DISPLAY` configurable at the Org level.

**Comment by wenottingham** [comment]
Other than just 'make it configurable', what is the issue not having it configurable causes them?

**Comment by wenottingham** [comment]
If we were to do this, this would be part of a larger effort making many/most settings overridable in a per-org manner. That is not planned for the near-term future.

**Comment by spsingh1982** [comment]
@wenottingham 
Our customers are using ARISTA devices. They are running show commands which has huge output which is failing job for them. Is there any work around we can use to increase the output for our customers without impacting overall platform performance?
