### ISSUE TITLE
Build and Install documentation is mingled

### ISSUE THREAD

**Issue by trondhindenes** [ansible/awx#108]
### Summary

The docs don't clearly separate build and deploy documentation

### Additional Information:

The included documentation mixes the build and deploy documentation - start with the "installer" directory and end up with a set of running Docker containers. This requires a significant amount of reverse-engineering if deploying elsewhere than the scenarios specified.

I think everyone would be better off if the documentation was separated into:
1. Build the containers --> produces docker images
2. Deploy the containers: Documentation about required and optional environment variables, other configuration options, external requirements etc.

**Comment by matburt** [comment]
This is by-design right now. In the future we're likely to provide pre-baked images but beyond that we have no specific plans.
