### ISSUE TITLE
i am trying to install AWX on my centos machine, but while cloning the git hub link, i am unable to find the installer file inside it, could you please help me?

### ISSUE THREAD

**Issue by bibhuti2sol** [ansible/awx#10804]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

i am trying to install AWX on my centos machine, but while cloning the git hub link, i am unable to find the installer file inside it, could you please help me?

### AWX version

19.2.2

### Installation method

docker on linux

### Modifications

no

### Ansible version

ansible 2.4.2.0

### Steps to reproduce

root/awx
[root@bibhuti-container.omid awx]# ls
API_STANDARDS.md  awx_collection  awx-logos     config           DATA_MIGRATION.md  docs        ISSUES.md   Makefile   MANIFEST.in    pyproject.toml  README.md     setup.py  tox.ini
awx               awxkit          CHANGELOG.md  CONTRIBUTING.md  DCO_1_1.md         INSTALL.md  LICENSE.md  manage.py  pre-commit.sh  pytest.ini      requirements  tools     VERSION
[root@bibhuti-container.omid awx]# 

no Installer file available inside the awx dir

### Expected results

/awx/installer/ file should be there

### Actual results

root/awx
[root@bibhuti-container.omid awx]# ls
API_STANDARDS.md  awx_collection  awx-logos     config           DATA_MIGRATION.md  docs        ISSUES.md   Makefile   MANIFEST.in    pyproject.toml  README.md     setup.py  tox.ini
awx               awxkit          CHANGELOG.md  CONTRIBUTING.md  DCO_1_1.md         INSTALL.md  LICENSE.md  manage.py  pre-commit.sh  pytest.ini      requirements  tools     VERSION
[root@bibhuti-container.omid awx]#

**Comment by abcqwertz** [comment]
According to the [Install-Readme](https://github.com/ansible/awx/blob/devel/INSTALL.md) newer versions (since 18.0) of AWX are installed with the awx-operator for Kubernetes, however you can still use the docker installation method (only recommended for testing/development). Look [here](https://github.com/ansible/awx/blob/devel/tools/docker-compose/README.md) for more information.

**Comment by wenottingham** [comment]
Yes, that ^.
