### ISSUE TITLE
Newbie help for AWX ssh

### ISSUE THREAD

**Issue by shew01** [ansible/awx#10800]
##### ISSUE TYPE

 - Bug Report (this is actually more of a configuration issue, but I didn't see a better category to use)

##### COMPONENT NAME

 - UI

##### SUMMARY

I'm new to AWX, and I'm not sure if this is the appropriate place to post an issue like mine or not. Please point me to a better venue, if that is appropriate. I'm thinking that I don't have ssh configured properly somewhere inside AWX, but I don't know where to look.

##### ENVIRONMENT
* AWX version: (presumably) 3.8.3, but I'm not sure
* AWX install method: developer environment
* AWX deployment target: openshift, kubernetes, minikube; not sure; I was following https://www.howtoforge.com/ansible-awx-guide-basic-usage-and-configuration/
* Operating System: Ubuntu 21.04
* Web Browser: Chrome

##### STEPS TO REPRODUCE

I created an account (hakase) on my AWX server and my target Ubuntu server (userver1). I configured ssh so that I can connect from AWX server to userver1 without a password using:

ssh userver1

I created an AWX credential, named hakase, and pasted my SSH Private Key into the GUI.

Git seems to work fine, and I created a "hello_world.yml" file that works fine from the command line.

---
- name: This is a hello world example
  hosts: userver1
  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'
      copy:
        content: hello world
        dest: /tmp/testfile.txt

I created host2.ini containing:

[ubuntu]
userver1

From the command line, ansible seems to work fine.

ansible-playbook -i hosts2.ini hello_world.yml

PLAY [This is a hello world example] ********************************************************************************

TASK [Gathering Facts] **********************************************************************************************
[DEPRECATION WARNING]: Distribution Ubuntu 21.04 on host userver1 should use /usr/bin/python3, but is using
/usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to
using the discovered platform python for this host. See
https://docs.ansible.com/ansible/2.10/reference_appendices/interpreter_discovery.html for more information. This
feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False
in ansible.cfg.
ok: [userver1]

TASK [Create a file called '/tmp/testfile.txt' with the content 'hello world'] **************************************
changed: [userver1]

PLAY RECAP **********************************************************************************************************
userver1                   : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

However, I get the following using an AWX template.

PLAY [This is a hello world example] *******************************************
TASK [Gathering Facts] *********************************************************
fatal: [userver1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: root@192.168.1.161: Permission denied (publickey,password).", "unreachable": true}
PLAY RECAP *********************************************************************
userver1                   : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   

##### EXPECTED RESULTS

ssh should work under AWX without generating an error.

##### ACTUAL RESULTS

ssh generates a permission denied error.

**Comment by wenottingham** [comment]
This issue tracker is for tracking feature enhancements and bugs to AWX itself.

This is better discussed/debugged on the mailing list or IRC channel. 

Mailing list: https://groups.google.com/forum/#!forum/awx-project
IRC: ansible-awx on irc.libera.chat
