### ISSUE TITLE
SSH issue for dynamic inventory hosts

### ISSUE THREAD

**Issue by bsushant-athena** [ansible/awx#10814]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

hi, I'm getting `Failed to connect to the host via ssh: OpenSSH_8.0p1, OpenSSL 1.1.1g FIPS  21 Apr 2020\....` error while trying to run a command on a host...basically trying the dynamic inventory 

### AWX version

19.2.2

### Installation method

kubernetes

### Modifications

no

### Operating system

Linux

### Web browser

Chrome

### Steps to reproduce

my playbook >> https://pastebin.com/VjZaxGLx
create a template using this playbook

execution env image without creds:: quay.io/bsushant_athena/awx:latest

the host in the playbook will be different

### Expected results

successfully returns the namespace 

### Actual results

`<132.145.181.70> (255, b'', b'OpenSSH_8.0p1, OpenSSL 1.1.1g FIPS  21 Apr 2020\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug3: /etc/ssh/ssh_config line 52: Including file /etc/ssh/ssh_config.d/05-redhat.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/05-redhat.conf\r\ndebug2: checking match for \'final all\' host 132.145.181.70 originally 132.145.181.70\r\ndebug3: /etc/ssh/ssh_config.d/05-redhat.conf line 3: not matched \'final\'\r\ndebug2: match not found\r\ndebug3: /etc/ssh/ssh_config.d/05-redhat.conf line 5: Including file /etc/crypto-policies/back-ends/openssh.config depth 1 (parse only)\r\ndebug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config\r\ndebug3: gss kex names ok: [gss-curve25519-sha256-,gss-nistp256-sha256-,gss-group14-sha256-,gss-group16-sha512-,gss-gex-sha1-,gss-group14-sha1-]\r\ndebug3: kex names ok: [curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hell…
fatal: [132.145.181.70]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: OpenSSH_8.0p1, OpenSSL 1.1.1g FIPS  21 Apr 2020\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug3: /etc/ssh/ssh_config line 52: Including file /etc/ssh/ssh_config.d/05-redhat.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/05-redhat.conf\r\ndebug2: checking match for 'final all' host 132.145.181.70 originally 132.145.181.70\r\ndebug3: /etc/ssh/ssh_config.d/05-redhat.conf line 3: not matched 'final'\r\ndebug2: match not found\r\ndebug3: /etc/ssh/ssh_config.d/05-redhat.conf line 5: Including file /etc/crypto-policies/back-ends/openssh.config depth 1 (parse only)\r\ndebug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config\r\ndebug3: gss kex names ok: [gss-curve25519-sha256-,gss-nistp256-sha256-,gss-group14-sha256-,gss-group16-sha512-,gss-gex-sha1-,gss-group14-sha1-]\r\ndebug3: kex names ok: [curve2551…
PLAY RECAP *********************************************************************
132.145.181.70             : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   

> 

> `

**Comment by wenottingham** [comment]
This issue tracker is for tracking feature enhancements and bugs to AWX itself.

There's not enough issue here to determine what is going on - it reads as an issue
with either your template setup or your credentials.
If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

Mailing list: https://groups.google.com/forum/#!forum/awx-project
IRC: ansible-awx on irc.libera.chat
