### ISSUE TITLE
Dynamic AWX Survey

### ISSUE THREAD

**Issue by jangel97** [ansible/awx#10811]
Hello,

Currently we are using Ansible Tower to offer our customers a IaaS and CaaS approach to deploy cloud resources into AWS. In order to do so, they provide details before the provisioning using a Survey. The survey is created using AT REST API so we can introduce data of available options in a scripted way.

We are facing the following problematic. Let me quote an example, when a user has to fill the required data in the survey he is asked to fill two fields, one for VPC, another for Subnet. Each Subnet will always belong to a VPC, as the Subnet to be chosen depends on the previous election for VPC. We cannot know beforehand what Subnet VPC the client got to chose in the previous field, which is why, we cannot condition the Subnets to be displayed in the AT Survey.

Would it be possible to create new object "Dynamic Survey" in which one can condition the options to be displayed in following labels depending on the values introduced in the fields before?

Kind regards,

**Comment by wenottingham** [comment]
-> #20
