### ISSUE TITLE
Workflow Node Convergence Doesn't Update Properly

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#10827]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Between save the workflow node wizard (to close it) and actually saving/updating the workflow (when the request is made) the convergence data on the node does not get updated.

### AWX version

devel

### Installation method

docker for mac

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

Create a workflow with at least 1 node. Save it and then go back to the workflow visualizer.  Now go and edit that node to change the convergence status

### Expected results

Once the wizard is save, the convergence tag on the node and the convergence data inside the Info/View Modal should be updated

### Actual results

The data at those points is not updating properly

**Comment by akus062381** [comment]
Looks good. stubs already in place.
