### ISSUE TITLE
AWX Tower browser Error Failed to read /api. GET status: 500 A server error has occurred.

### ISSUE THREAD

**Issue by shajay12** [ansible/awx#1082]
##### ISSUE TYPE

 - Bug Report
##### COMPONENT NAME

 - API
 - UI
 ##### SUMMARY

##### ENVIRONMENT
* AWX version: Latest
* AWX install method: Github
* Ansible version: 2.4.2.0
* CentOS Linux release 7.4.1708 (Core) :
* Chrome:

##### ADDITIONAL INFORMATION

Used this blog for installation of AWX Tower
http://khmel.org/?p=1245
Used this link for debugging the project issue. 

https://github.com/ansible/awx/issues/857

**Comment by ryanpetrello** [comment]
@shajay12 the blog post you linked to is an unofficial method for installing awx - it may mostly work, but it's possible you'll run into quirks here and there.  Take a look at the installation documentation we have provided for a more reliable method:

https://github.com/ansible/awx/blob/devel/INSTALL.md

Do you have any additional information on the 500 error from your awx logs?  If you have a traceback you can share, we _might_ be able to point you in the right direction.

**Comment by matburt** [comment]
You should seek support from the person who wrote the blog post, we only support our official method.

**Comment by shajay12** [comment]
Hi Ryanpetrello, I will follow this https://github.com/ansible/awx/blob/devel/INSTALL.md link for again installing AWX tower. 
Though on this link https://github.com/geerlingguy/ansible-vagrant-examples/issues/41 solution is provided but i do not understand what this guy is saying. 

also let me know, in which folder can i get the AWX logs ?

and Matburt, i also want to work on the official version. I want to rectify my mistake. 

Thanks.

**Comment by leonzhangit** [comment]
Hi there just wondered did you find a way to fix this yet? my server has the same issue right now, thanks.

**Comment by sblackburncgi** [comment]
Same thing here.   When I remove containers and recreate them using "ansible-playbook -i inventory install.yml", I have a lot of error 500 from the dashboard or projects view, etc.

[pid: 134|app: 0|req: 11/40] 10.x.x.x () {42 vars in 2265 bytes} [Wed Sep 12 15:32:12 2018] GET /api/v2/dashboard/ => generated 41 bytes in 67 msecs (HTTP/1.1 500) 6 headers in 200 bytes (1 switches on core 0)
10.x.x.x - - [12/Sep/2018:15:32:12 +0000] "GET /api/v2/dashboard/ HTTP/1.1" 500 41 "http://___.___.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-"

[pid: 137|app: 0|req: 15/43] 10.x.x.x () {42 vars in 2316 bytes} [Wed Sep 12 15:42:15 2018] GET /api/v2/projects/?page_size=20&order_by=name => generated 41 bytes in 77 msecs (HTTP/1.1 500) 6 headers in 200 bytes (1 switches on core 0)
10.x.x.x - - [12/Sep/2018:15:42:15 +0000] "GET /api/v2/projects/?page_size=20&order_by=name HTTP/1.1" 500 41 "http://___.___.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-"
