### ISSUE TITLE
error 1 - => ERROR [internal] load metadata for quay.io/centos/centos:8

### ISSUE THREAD

**Issue by Mihgo** [ansible/awx#10824]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

I'm trying to install AWX on a redhat, on this "new" way to install since AWX 17.
And i'm standing on this error, which i cant find any solution to.  
Anyone who can help me, i do really appreciate it.  

### AWX version

the newest

### Installation method

docker on linux

### Modifications

no

### Ansible version

2.9.23

### Operating system

Red Hat Enterprise Linux Server 7.9

### Steps to reproduce

-

### Expected results

I want to install awx

### Actual results

I'm getting this error : 
ansible-playbook tools/ansible/dockerfile.yml -e build_dev=True

PLAY [Render AWX Dockerfile and sources] ***************************************************************************************************************************
TASK [Gathering Facts] *********************************************************************************************************************************************ok: [localhost]

TASK [dockerfile : Create _build directory] ************************************************************************************************************************ok: [localhost]

TASK [dockerfile : Render supervisor configs] **********************************************************************************************************************ok: [localhost] => (item=supervisor.conf)
ok: [localhost] => (item=supervisor_task.conf)

TASK [dockerfile : Render Dockerfile] ******************************************************************************************************************************ok: [localhost]

PLAY RECAP *********************************************************************************************************************************************************localhost                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

DOCKER_BUILDKIT=1 docker build -t quay.io/awx/awx_devel:devel \
    --build-arg BUILDKIT_INLINE_CACHE=1 \
    --cache-from=quay.io/awx/awx_devel:devel .
[+] Building 0.1s (3/3) FINISHED                                                                                                                                    
 => [internal] load build definition from Dockerfile                                                                                                           0.0s
 => => transferring dockerfile: 92B                                                                                                                            0.0s
 => [internal] load .dockerignore                                                                                                                              0.0s
 => => transferring context: 87B                                                                                                                               0.0s
 => ERROR [internal] load metadata for quay.io/centos/centos:8                                                                                                 0.0s
------
 > [internal] load metadata for quay.io/centos/centos:8:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head "https://quay.io/v2/centos/centos/manifests/8": EOF
make: *** [docker-compose-build] Error 1

**Comment by wenottingham** [comment]
This looks like either a temporary issue with quay.io, or an issue due to using RHEL 7 as the base, which isn't tested. 
See https://github.com/ansible/awx/blob/devel/tools/docker-compose/README.md#tested-operating-systems

This issue tracker is for tracking feature enhancements and bugs to AWX itself - things like this are better
debugged elsewhere.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

Mailing list: https://groups.google.com/forum/#!forum/awx-project
IRC: ansible-awx on irc.libera.chat

**Comment by Mihgo** [comment]
> This looks like either a temporary issue with quay.io, or an issue due to using RHEL 7 as the base, which isn't tested.
> See https://github.com/ansible/awx/blob/devel/tools/docker-compose/README.md#tested-operating-systems
> 
> This issue tracker is for tracking feature enhancements and bugs to AWX itself - things like this are better
> debugged elsewhere.
> 
> If you need help troubleshooting an AWX install, try our mailing list or IRC channel:
> 
> Mailing list: https://groups.google.com/forum/#!forum/awx-project
> IRC: ansible-awx on irc.libera.chat

I'm so sorry for comment the wrong place. Thanks a lot for you reply !
