### ISSUE TITLE
Editing idle_timeout and job_timeout for ansible-runner environment settings

### ISSUE THREAD

**Issue by felipe4334** [ansible/awx#10829]
So currently I'm having an issue were our windows patching playbook is failing because the working Kubernetes Pod gets terminated before the patching is completed. We believe this is because of the idle_timeout set inside ansible-runner environment settings

settings:
---
idle_timeout: 600
job_timeout: 3600
pexpect_timeout: 10

I'm currently building a custom AWX-EE image based out of quay.io/ansible/awx-ee:0.5.0, and that original image is being built from quay.io/ansible/ansible-runner:latest. I understand that I can build ansible/ansible-runner myself and edit the "ansible-runner/demo/env/settings" file and then build my own custom ansible/awx-ee:0.5.0 from that but is there a way to do this using awx-operator. I understand that awx-operator recommends customizing the Pod spec for custom EE but I dont see what specs I can provide the custom ansible/awx-ee:0.5.0 image since that image is not the one that gets idle_timeout: environment variable assigned.

![image](https://user-images.githubusercontent.com/13802820/128064041-3690072a-35d8-46db-a82a-7653e28dda53.png)

So to make the question above simpler, can I set the idle_timeout environment variable for ansible-runner inside the spec of a custom awx-ee image?

Or maybe include the idle_timeout ansible-runner envrionemnt variable when build the custom awx-ee image based out of ansible/awx-ee:0.5.0?

```
FROM quay.io/ansible/awx-ee:0.5.0

# Install Ansible requirements.
COPY requirements.yml ${HOME}/requirements.yml
RUN ansible-galaxy collection install -r ${HOME}/requirements.yml

# Version: 1.3.1
RUN pip3 install pandas

ENV idle_timeout=5000
```

**Comment by wenottingham** [comment]
Moving to the awx repo. The right way for this to work would be for AWX to pass this down via some setting, not via overriden env vars in a podspec or EE.

**Comment by tiagodread** [comment]
Verified setting `DEFAULT_JOB_IDLE_TIMEOUT` to 10s and running the playbook:
```
---

- name: 'Test playbook to sleep for a specified interval'
  hosts: all
  gather_facts: false
  vars:
    sleep_interval: 30

  tasks:
    - name: sleep for a specified interval
      command: sleep '{{ sleep_interval }}'
```

![image](https://user-images.githubusercontent.com/12464858/137484611-64760ec9-9c79-4229-a236-9bebaea92922.png)

**Comment by felipe4334** [comment]
@tiagodread where did you set the timeout? I added it to "Extra Environment Variables" under job settings but it does not work there.
{
  "ANSIBLE_WIN_ASYNC_STARTUP_TIMEOUT": "60",
  "DEFAULT_JOB_IDLE_TIMEOUT": "10"
}
![image](https://user-images.githubusercontent.com/13802820/143122152-156e976d-6e10-4039-bd36-935cb091cae8.png)

**Comment by felipe4334** [comment]
@tiagodread It looks like #10906 is not working properly
