### ISSUE TITLE
Ability to link Credential Objects to Inventories

### ISSUE THREAD

**Issue by msheermo** [ansible/awx#10836]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Credential objects can currently only be linked to Job Templates.

For example in a large (15.000 nodes +) Windows environment with multiple AD forests, you typically have a different credential per forest and/or domain, which means setting up a different Job Template for the same job run (for instance a security baseline that runs periodically) for each credential / inventory combination, 
This leads to clutter and the UI being unmanagable

You should be able to set Credential Objects at the level of Inventories, Dynamic Inventories and Smart Inventories
This would allow for the same job template to run against different AD forests with inventory level machine credentials

**Comment by wenottingham** [comment]
-> #286
