### ISSUE TITLE
AWX not accessible from outside localhost

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/awx#10839]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

AWX unaccessible from outside after executing `docker exec tools_awx_1 make clean-ui ui-devel`.

I am unable to to access the AWX web site with https://awx.ourdomain:8043 or http://awx.ourdomain:8043

Using localhost is not an option since using centos console only. 

Only containers tools_awx_1, tools_postgres_1 and tools_redis_1 are running. 

Not sure what to do here? 

### AWX version

19.2.2

### Installation method

docker on linux

### Modifications

no

### Ansible version

2.11.3

### Operating system

Centos 

### Steps to reproduce

Follow basic guide 

### Expected results

expect to awx to be accesible from outside localhost

### Actual results

not accessible

**Comment by wenottingham** [comment]
The developer environment (docker-compose) is not meant for production usage.
If you're trying to use it to serve external content, you'll have to familiarize yourself
with docker networking, exposing ports from a container to the internet, and so on.
Alternatively, you can use the production deployment method (kubernetes).

In any case, this issue tracker is for tracking feature enhancements and bugs to AWX itself,
and if you need help troubleshooting an AWX install, try our mailing list or IRC channel:

Mailing list: https://groups.google.com/forum/#!forum/awx-project
IRC: ansible-awx on irc.libera.chat

**Comment by nicolaibaralmueller** [comment]
> The developer environment (docker-compose) is not meant for production usage.
> If you're trying to use it to serve external content, you'll have to familiarize yourself
> with docker networking, exposing ports from a container to the internet, and so on.
> Alternatively, you can use the production deployment method (kubernetes).
> 
> In any case, this issue tracker is for tracking feature enhancements and bugs to AWX itself,
> and if you need help troubleshooting an AWX install, try our mailing list or IRC channel:
> 
> Mailing list: https://groups.google.com/forum/#!forum/awx-project
> IRC: ansible-awx on irc.libera.chat

Thanks for clearifying. A lot have changed since version 15.0.1.
