### ISSUE TITLE
Prevent control-only instances from being added to user-defined instance groups.

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#10830]
Users can now add nodes to the cluster that are not allowed to run jobs (they can still run project updates and some other things).

These instances should be added to the `controlplane` instance group, but they should not be allowed to be added to any other instance group.

---

Jotting down some acceptance criteria:

- control and hybrid instances should automatically be added to `controlplane` IG (this should happen during awx installation)
- user attempts to add/remove instance from `controlplane` IG => 400
- user attempts to _delete_ hybrid / control instance altogether => 400
- (in general, seems like `controlplane` IG's membership should be immutable after install - do we want to go so far as to disable POST/PUT/DELETE for instancegroups/<control plane IG>/instances endpoint? seems like maybe we don't want to go quite this far)
- deleting an execution node is maybe allowed?

**Comment by tchellomello** [comment]
PR https://github.com/ansible/automation-platform-collection/pull/128 should cover this

**Comment by AlanCoding** [comment]
@tchellomello instances can _also_ be added to instance groups through the API. If that is attempted, we should give a 400 error, and that's the primary thing we'd like to accomplish with this issue.

**Comment by tchellomello** [comment]
@AlanCoding alright, I will mention this for the team tomorrow so we can add that as well to this PR. Thanks for the heads up

**Comment by AlanCoding** [comment]
I intended this to be done by the mesh code pod, because it's on the server code side of things. You already did the installer part.

But if anyone wants to get this knocked out, go ahead. It would be several weeks out for us because it's not urgent.

**Comment by AlanCoding** [comment]
https://github.com/ansible/awx/pull/10985 will prevent them from being added by the policy rules. Once @jbradberry merges we should be done with this.

**Comment by jbradberry** [comment]
https://github.com/ansible/awx/pull/10929 has merged.

**Comment by jladdjr** [comment]
@thenets let us know if you need any additional context on this for testing.

**Comment by tiagodread** [comment]
Verified that:
1- User cannot change instance group membership of control-only type:
```
{
    "msg": "Cannot change instance group membership of control-only node: ec2-34-239-101-88.compute-1.amazonaws.com."
}
```
although the user can at lest try to do so via UI

https://user-images.githubusercontent.com/12464858/137398251-22e7836f-25e9-416f-addd-94d37ef5e1b9.mp4


2- Hybrid and control-only are added to controlplane automatically
3- Users are not allowed to remove hybrid/control instances

I'll close this issue and file a UI issue especifically to fix the item 1
