### ISSUE TITLE
Inventory Source Project being validated when not necessary

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#10831]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### AWX version

devel

### Installation method

docker for mac

### Modifications

no

### Steps to reproduce

1. Go to `https://localhost:3001/#/inventories/inventory/1/sources/add`
2. Select a project
3. Validation is being displayed. When the project is a valid one. 

Note: This just happens on the first time the project is selected. Selecting another project will clear the validation error.

<img width="1493" alt="image" src="https://user-images.githubusercontent.com/9053044/128560340-cddfd809-31b7-4491-9740-06f8c5a801f4.png">

### Expected results

No error being displayed for valid projects.

### Actual results

Error being displayed for valid projects.

**Comment by nixocio** [comment]
There is also an issue with Project lookup on the Job Templates screen.

https://user-images.githubusercontent.com/9053044/137807565-fe5d1be4-85df-4843-98e6-63ec18469b8c.mov

**Comment by jay-steurer** [comment]
The issue was resolved.
