### ISSUE TITLE
Feature idea: easier review of workflow output

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1084]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY

Right now, if you want to view the output of a workflow beyond success/failure at the job template level, the flow is:

1. Find workflow run in list
2. Click on it
3. Click on individual step
4. Read output
5. Hit back/up
6. Go to step 3
<loop until done>

This is a clunky workflow and requires many clicks to to progress through a full workflow. 
An alternate/different interface may make this easier.

##### ENVIRONMENT
* AWX version: any
* AWX install method: N/A
* Ansible version:  N/A
* Operating System: N/A
* Web Browser: N/A

**Comment by wenottingham** [comment]
As part of this, we should have a better way to show the full workflow graph when it's large (download/print).

**Comment by seansabour** [comment]
Would be nice to have a popup when you click on the details for that template that shows the output, instead of redirecting to another page.

**Comment by AlexSCorey** [comment]
There is also a bug in this workflow.  When the user clicks on the node it navigates them to the Job Template Details view when it should navigate Job Template Output page.

**Comment by trahman73** [comment]
Initial mockup idea. Need to iterate further...

![image](https://user-images.githubusercontent.com/13351591/175659107-06804ce7-73cb-4e02-b19a-17b3738ec3c9.png)

**Comment by InnocentK** [comment]
@akus062381 We will need to add some stubs to improve test coverage to include this feature for our E2E tests

**Comment by InnocentK** [comment]
Resolved
