### ISSUE TITLE
We want to have an option to make the limit field mandatory when creating a job template

### ISSUE THREAD

**Issue by garamirseokim** [ansible/awx#10846]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
We are currently using ansible tower 3.8.3.  When we create a job template, we want to limit the specified host when we execute the template. Currently the "Prompt on Launch" checkbox is selected.  But if we forget to fill any specific server name in the limit prompt box, the job will execute on all servers of the inventory which is too risky for us. 
So, we want to enforce the performer to fill the "limit" when executing a job template. 
We already have gone through the existing RFE(https://github.com/ansible/awx/issues/10748). However, the work around from the Red Hat engineering team is not suitable for us.  We want to have an option to make the limit field mandatory when creating a job template.

**Comment by shanemcd** [comment]
We are unlikely to do this. Please consider handling this validation logic in your playbook.
