### ISSUE TITLE
[RFE] Add a global host limit setting for jobs

### ISSUE THREAD

**Issue by mdinwoodie** [ansible/awx#10842]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
This RFE is to add a global, configurable limit that limits how many hosts a job can run against. For example, if the inventory (or smart inventory) has host over the set limit, the job will be cancelled automatically stating that you exceeded the host limit.

**Comment by wenottingham** [comment]
This isn't something we'd add to AWX/the controller. 

If this is driven by users running automation on hosts they shouldn't, that is best solved via RBAC and delegation.
If this is driven by users using too much capacity, execution capacity can be segmented by org and job to constraint those users (and a user with playbook control could bypass these limits).
This can also be accomplished by the use of workflows with approval, or by using a services catalog to front automation.
