### ISSUE TITLE
Disallow delete or edit of Control Instances

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#10853]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
In 4.1 the Mesh code POD will introduce different types of instances to include Controller, Executioner, and Hybrid( which will do both).  Control nodes are automatically added to the controlplane instance group when they come online.  We should not allow them to be deleted or edited. 

We will also need API validation.

**Comment by jbradberry** [comment]
https://github.com/ansible/awx/pull/10929 has merged.

**Comment by CFSNM** [comment]
Opened PR to add automated API tests for this feature: https://github.com/ansible/tower-qa/pull/6800

**Comment by CFSNM** [comment]
This issue has been tested from the API perspective. Need to test from the UI perspective as well. FYI @tiagodread @akus062381 @InnocentK

**Comment by akus062381** [comment]
resolved

**Comment by CFSNM** [comment]
Thanks @akus062381
