### ISSUE TITLE
[mesh code] Add setting which dictates whether auto-discovered execution nodes are enabled or not

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#10852]
Current auto-discovery behavior https://github.com/ansible/awx/blob/devel/docs/receptor_mesh.md#auto-discovery-of-execution-nodes

Let's give the setting a name `AWX_EXECUTION_NODES_AUTO_DISCOVER_CREATE_ENABLED = False` and set it to `False` by default.

* When `AWX_EXECUTION_NODES_AUTO_DISCOVER_CREATE_ENABLED = False` new `Instance` records created by auto-discovery will default to `enabled = False` (today's behavior)
* When `AWX_EXECUTION_NODES_AUTO_DISCOVER_CREATE_ENABLED = True` new `Instance` records created by auto-discovery will default to `enabled = True` (new feature behavior)

**Comment by AlexSCorey** [comment]
Link https://github.com/ansible/awx/issues/10853

**Comment by AlanCoding** [comment]
My only concern here is that this may have implications for the installer, because it doesn't make much sense unless you can give it a value in the install process.

**Comment by AlanCoding** [comment]
We removed auto-discovery entirely, so I'm closing this outright. FYI @jbradberry
