### ISSUE TITLE
GitLab self-signed server certificate issue 

### ISSUE THREAD

**Issue by HailsonJunior** [ansible/awx#10850]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

I have set "GIT_SSL_NO_VERIFY": "True" in AWX UI: "settings > jobs settings > Extra Environment Variables", but it keep getting error of SSL certificate.

### AWX version

19.2.2

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.9.6

### Operating system

Ubuntu 20.04.2 LTS

### Web browser

Firefox

### Steps to reproduce

Set Extra Environment Variables:

{
  "GIT_SSL_NO_VERIFY": "True"
}

and then tried to sync with git project

### Expected results

Sync with git project 

### Actual results

fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/git ls-remote 'https://$encrypted$:$encrypted$@gitlab.hst.br/infrastructure1/ansible-qts-h-nonpci.git' -h refs/heads/main", "msg": "fatal: unable to access 'https://gitlab.hst.br/infrastructure1/ansible-qts-h-nonpci.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to gitlab.hst.br:443", "rc": 128, "stderr": "fatal: unable to access 'https://gitlab.hst.br/infrastructure1/ansible-qts-h-nonpci.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to gitlab.hst.br:443 \n", "stderr_lines": ["fatal: unable to access 'https://gitlab.hst.br/infrastructure1/ansible-qts-h-nonpci.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to gitlab.hst.br:443 "], "stdout": "", "stdout_lines": []}

**Comment by wenottingham** [comment]
That's not due to the self-signed cert, that is due to an SSL protocol error and/or dropped connection. That env var won't help - you may need to diagnose something around:
-  the TLS/SSL version.
- proxies in the middle
- other errors you'd pull from  the server log on the other end

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

Mailing list: https://groups.google.com/forum/#!forum/awx-project
IRC: ansible-awx on irc.libera.chat

**Comment by HailsonJunior** [comment]
> That's not due to the self-signed cert, that is due to an SSL protocol error and/or dropped connection. That env var won't help - you may need to diagnose something around:
> 
>     * the TLS/SSL version.
> 
>     * proxies in the middle
> 
>     * other errors you'd pull from  the server log on the other end
> 
> 
> This issue tracker is for tracking feature enhancements and bugs to AWX itself.
> 
> If you need help troubleshooting an AWX install, try our mailing list or IRC channel:
> 
> Mailing list: https://groups.google.com/forum/#!forum/awx-project
> IRC: ansible-awx on irc.libera.chat

Ok, thanks @wenottingham
