### ISSUE TITLE
Give better error details when receptor can't start a job due to file permissions

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#10868]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

If the user that receptor is running under hits a file permission error while preparing the private_data_dir for running a job, then this is not reported to the user.

### AWX version

19.2.2

### Installation method

docker on linux

### Modifications

yes

### Ansible version

devel

### Operating system

RHEL

### Steps to reproduce

Do anything that will cause permission errors when ansible-runner tries to get ready to run the job. This could be that you pre-create the private_data_dir with permissions that exclude the user running receptor.

(this will surface much more commonly when execution nodes are an option)

### Expected results

```
(awx) [awx@ip-10-0-5-35 ~]$ receptorctl --socket=/var/run/receptor/receptor.sock work results kP1LmaF4
Traceback (most recent call last):
  File "/usr/bin/ansible-runner", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/ansible_runner/__main__.py", line 816, in main
    os.makedirs(vargs.get('private_data_dir'), mode=0o700)
  File "/usr/lib64/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/tmp/pdd_wrapper_369_jtrct1yq/awx_369_7byfuxre'
Remote unit failed: exit status 1
```

### Actual results

```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1406, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2935, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3000, in _run_internal
    raise RuntimeError(detail)
RuntimeError: exit status 1
```

### Additional information

Debugging for the health checks, I found that "exit status x" errors tend to have the details sent in the primary standard out stream.

So in this case, there's probably a socket somewhere that has the information but we never read from it.

This could potentially be fixable in ansible-runner, but not sure.

**Comment by AlanCoding** [comment]
Related to https://github.com/ansible/awx/issues/10213

**Comment by tchellomello** [comment]
Currently `receptor` service runs as `receptor` user and therefore, the `awx` user is also part of the `receptor` group. 

> PermissionError: [Errno 13] Permission denied: '/tmp/pdd_wrapper_369_jtrct1yq/awx_369_7byfuxre'
Remote unit failed: exit status 1

The given error seems to be related to this line: https://github.com/ansible/ansible-runner/blob/devel/ansible_runner/__main__.py#L815-L821 

```python
    try:
        os.makedirs(vargs.get('private_data_dir'), mode=0o700)
    except OSError as exc:
        if exc.errno == errno.EEXIST and os.path.isdir(vargs.get('private_data_dir')):
            pass
        else:
            raise
```

If the directory gets created by the `awx` user, then we should do a `770` instead of `700`. If we want to be more restrictive, we could create as `awx:receptor` but that still would require a `770` mask. 

```
(awx) [awx@ip-10-0-0-222 tmp]$ id receptor
uid=991(receptor) gid=987(receptor) groups=987(receptor)
(awx) [awx@ip-10-0-0-222 tmp]$ id awx
uid=992(awx) gid=988(awx) groups=988(awx),990(redis),989(nginx),987(receptor)
```

**Comment by kdelee** [comment]
https://github.com/ansible/awx/pull/10918 implements the better error message, but does not resolve the permissions issue

**Comment by shanemcd** [comment]
Closing this as it seems like we achieved the "better error" part of this issue.
