### ISSUE TITLE
Session expiration modal displaying after social auth

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#10860]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Session expiration modal displaying after social auth

### AWX version

devel

### Installation method

docker for mac

### Modifications

no

### Steps to reproduce

    1. Enable SSO - Github
    2. Try to authenticate using Github
    3. Log out
    4. Login in again

### Expected results

The user should be able to login successfully without session expiration modal

### Actual results

The user logs in successfully, however the awx-session-timeout storage is taking some seconds to be populated (I belive we are still fetching data) , during this period (~5 sec) the modal is displayed

**Comment by tiagodread** [comment]
The original issue was fixed, so now if a user attempt to login by the first time using SSO the modal is not displayed anymore, however, changing the IDLE timeout settings, the expiration modal is not displayed anymore in the last 10 seconds.


https://user-images.githubusercontent.com/12464858/129244369-a833c03d-c917-4333-a03b-d11e60c78b3e.mp4

**Comment by tiagodread** [comment]
This can be closed with the merge of #10859
