### ISSUE TITLE
Different Source Control Branch for Job Template does not restore original repository submodule state after run/launch

### ISSUE THREAD

**Issue by Kardi5** [ansible/awx#10867]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

We are using a large repository with many submodules as main project. Users are using different source control branches in their templates.

When an user starts their template with a different source control branch, we noticed that the submodules in the repository (in both the task and EE container) were correctly checked out to the committed state of the submodule (eg. commit aa00ff). 

But the following job templates are launched with the wrong submodule commit checked out in the repository. 

### AWX version

19.2.2 + Operator 0.12

### Installation method

kubernetes

### Modifications

yes

### Ansible version

core 2.11.3.post0

### Operating system

Azure Kubernetes Nodes using Ubuntu 18.04 LTS + OS specified in AWX containers

### Web browser

Chrome

### Steps to reproduce

1.  Create a new project, set default branch to "master" and default execution env to some image (probably not needed)
2.  Create a new inventory that is sourced from the SCM repo of 1)
3.  Create a job template that specifies no SCM branch
4.  Create a job template specifies the "test" SCM branch

In your SCM (Github, etc):
1. Have a master branch that uses some submodules
(Include submodules via 
git submodule add https://full/path/to/foobar.git path/to/foobar
git commit -m "added submodule foobar"
git push)
2. Create a new branch (we will call it "test"), checkout a different commit for the submodule; add, commit and push this new state of the branch to the remote

Back in AWX:
5. Start the job template with specified SCM branch
6. Start the job template without SCM branch

7. Check AWX task and EE container: Switch to /var/lib/awx/projects/_123_project/foobar
8. The checked out submodule will have the state of the committed submodule of the test branch and not the master branch. This results in code running that might not be meant to run against the host of the "no-SCM branch" job template. In our case it just resulted in some failures.

### Expected results

The correct submodule commit state is checked out and the job runs with the right version.

### Actual results

The incorrect submodule commit state from the job template with SCM branch is checked out. This results in an error when executing (or similiar).

**Comment by shanemcd** [comment]
@AlanCoding when you have a chance we could use your 👀 on this.

**Comment by AlanCoding** [comment]
This is probably valid, because before preparing the directory for a job (with branch override) we stash the prior branch. After the job prep is finished, we checkout that prior branch. We do not track the prior state of submodules in this way.

**Comment by Kardi5** [comment]
This issue ceased to exist after updating to newer AWX version
