### ISSUE TITLE
AWX not detect inventory file inside a directory unless being put at project root

### ISSUE THREAD

**Issue by ghost** [ansible/awx#10876]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

When sourced from a git, AWX does not detect inventory file if it is not at project root level.

### AWX version

16.0.0

### Installation method

docker on linux

### Modifications

no

### Ansible version

2.9.5

### Operating system

CentOS 7

### Web browser

Chrome

### Steps to reproduce

1. create a project on git
2. create inventory file in a second level directory: "environments/dev/inventory.ini"
3. create a project on AWX synced from the git
4. create an inventory on AWX with a source from a project
5. in the dropdown menu of "Inventory file", the inventory.ini file is not shown.

### Expected results

The invenroty.ini file is shown in the dropdown menu of Inventory file

### Actual results

The invenroty.ini file is not detected in the dropdown menu of Inventory file

### Additional information

the inventory.ini will be detected and shown in the dropdown menu if I move the inventory.ini to the project root level

**Comment by wenottingham** [comment]
You should be able to type in the path to the file. (I do see you're using an older AWX version - if you can't do that, you may need to upgrade to a recent version where that is fixed.)

**Comment by ghost** [comment]
@wenottingham starting from which version?

**Comment by wenottingham** [comment]
https://github.com/ansible/awx/blob/devel/CHANGELOG.md#1800-march-23-2021

```
Playbook, credential type, and inventory file inputs now support type-ahead and manual type-in! https://github.com/ansible/awx/pull/9120
```

**Comment by ghost** [comment]
@wenottingham ok thanks, we will try that out.

**Comment by BradKnowles** [comment]
I'm experiencing this exact same issue using the latest `devel` tag from Docker.
