### ISSUE TITLE
[AWX] "Source control branch" in Workflow Template does not take effect.

### ISSUE THREAD

**Issue by ghost** [ansible/awx#10873]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

After setting Source Control Branch value to "dev", the Project Sync job in launched Workflow Job Template still sync with "master branch".

So the "Source Control Branch" value does not make Workflow Job Template switch branches.

### AWX version

16.0.0

### Installation method

docker on linux

### Modifications

no

### Ansible version

2.9.5

### Operating system

CentOS 7

### Web browser

Chrome

### Steps to reproduce

2 branched in the git repo:
> master branch: contains a working playbook
> dev branch: the working playbook is missing.

1. Create a project pointing to a git repo.
> Leave the "Source Control Branch/Tag/Commit" blank in the created project.
> Check the option "Allow Branch Override" in the created project
> Check the option "Update Revision on Launch" in the created project

2. Create a Job Template and use a playbook associated with the project above.

3. Create a Workflow Job Template
> Check "Prompt on launch" for "Source control branch" and leave it blank OR set "dev" for "Source control branch"
> Add 1st Node "Project Sync" and 2nd Node "Job Template" created in the step 2 which is associated to the project.

4. Launch the Workflow Job Template
> Set the value of "Source control branch" to "dev" which is the branch with missing working playbook for subsequent Job Template.

### Expected results

The Project should sync with requested branch "dev" where the working playbook is missing and the subsequent Job Template Node in the Workflow Template Job should fail.

### Actual results

the Job Template still succeeded with the working playbook in the master branch. 

### Additional information

With multiple test and combination, here is the summary according to different value set to the "source control branch":

```
1. In project: source control branch=blank      +  In WFJ: source control branch="dev"      = Workflow still uses "master".
2. In project: source control branch="master" +  In WFJ: source control branch="dev"      = Workflow still uses "master"
3. In project: source control branch="dev"      +  In WFJ: source control branch="dev"      = Workflow uses "dev" 
4. In project: source control branch="dev"      +  In WFJ: source control branch="master" = Workflow still uses "dev" 
```

**So the value set to the "source control branch" in Workflow Job Template does not take effect.**

**Comment by wenottingham** [comment]
The value set on the workflow will *only* be used for job templates that have 'prompt on launch' set for the revision. Is it set on the job template for #2?

**Comment by ghost** [comment]
@wenottingham it is already mentioned in the "Steps to reproduce", step 3, that 'prompt on launch' is set.

**Comment by wenottingham** [comment]
In step number 3 you set it on the workflow. It *also* needs to be set on the job template itself from #2.

**Comment by ghost** [comment]
@wenottingham but there is no option for this setting in job template, it only exists in either project or workflow
![image](https://user-images.githubusercontent.com/81583999/129783823-8d270124-9e4c-40c4-a7cc-11c1434ca0c0.png)

**Comment by wenottingham** [comment]
It will only be offered if the project offers overrides. You won't see it when there's no project selected.

![Screenshot from 2021-08-17 15-25-16](https://user-images.githubusercontent.com/5208768/129788021-e4bb7928-0d74-42ed-a6d3-26201f794a74.png)

**Comment by ghost** [comment]
Ok I see... I created a new job template after enabling the overrides from the project side, it seems the existing job templates will needs to be recreated. 

I will test it out if it works this way and report back.

**Comment by ghost** [comment]
@wenottingham I tested. In your screenshot, once we save the job template and go back edit, the Source Control Branch field will just disappear, it's a one-time setting and does not allow subsequent actions to switch the branch. 

You can try it out by saving the job template in the screenshot.

**Comment by wenottingham** [comment]
I don't see this in my testing - it's a normal editable field like any others. My best guess is that it's an issue that has been fixed since 16.0.0. In the interim, you could post directly to the API.

**Comment by zyitingftnt** [comment]
ok, what is your version for testing? By the way, i notice that it disappear when editing back but it does give the opportunities to enter the branch name when launching the job template. 

With that being said, a side note here, is it a normal behavior that the launching a template with code on a branch will automatically sync the code with that branch? (Since this seems what I experienced during the test, i did not sync the project before launch and it seems the sync with the branch was done behind scene.)

thanks

**Comment by ghost** [comment]
I think I can close the issue. All good. Thanks @wenottingham
