### ISSUE TITLE
Inventory source from project does not work anymore in 19.3.0

### ISSUE THREAD

**Issue by chofstede** [ansible/awx#10878]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

After Updating from 19.2.2 to 19.3.0 the inventory sync sourced from a project does not work anymore using the same EE or the newer EE. I tested this multiple times with multiple inventories that are sourced from a project.

**Version 19.2.2**:
_ansible-inventory [core 2.11.2.post0] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
host_list declined parsing /runner/project/inventories/test-project/vmware.yml as it did not pass its verify_file() method
script declined parsing /runner/project/inventories/test-project/vmware.yml as it did not pass its verify_file() method
Parsed /runner/project/inventories/test-project/vmware.yml inventory source with auto plugin
   16.996 INFO     Processing JSON output...
   17.025 INFO     Loaded 9 groups, 39 hosts
   17.534 INFO     Inventory import completed for VMWare in 0.6s_

**Version 19.3.0**:
_ansible-inventory [core 2.11.2.post0] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
[WARNING]: Ignoring invalid path provided to plugin path:
'/runner/project/inventories/test-project' is not a directory
host_list declined parsing /runner/project/inventories/test-project/vmware.yml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /runner/project/inventories/test-project/vmware.yml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
auto declined parsing /runner/project/inventories/test-project/vmware.yml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /runner/project/inventories/test-project/vmware.yml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /runner/project/inventories/test-project/vmware.yml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /runner/project/inventories/test-project/vmware.yml as it did not pass its verify_file() method
[WARNING]: Unable to parse /runner/project/inventories/test-project/vmware.yml
as an inventory source
ERROR! No inventory was parsed, please check your configuration and options._

### AWX version

19.3.0

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.11.2

### Operating system

Debian GNU/Linux with Kubernetes v1.20.7

### Web browser

Chrome

### Steps to reproduce

- Update AWX to 19.3.0
- Sync an inventory which is sourced from a project

### Expected results

Inventory sync works

### Actual results

Inventory sync does not work and results in an error

**Comment by Kardi5** [comment]
I have the same configuration (newest AWX and inventory sourced from project) with the same problem

**Comment by shanemcd** [comment]
This looks like it might be legit, we should look into it.

**Comment by Randy29800** [comment]
Hi all, similar problem here

AWX version
19.3.0

Installation method
AWX Operator 0.13.0

Modifications
no

Ansible version
2.9.4

Operating system
AlmaLinux 8.4 minimal

**Comment by cljcoder** [comment]
I am also seeing this problem, on

AWX Version
19.3.0

Installation Method
AWX Operator 0.13.0

The one unique tidbit that I can add is that when looking at the logs from awx-task I can see the following log repeated on each iteration:


> 2021-09-10 06:34:18,469 DEBUG    [fe5856dedd59429896636683cd1e188f] awx.main.tasks Starting periodic scheduler
> 2021-09-10 06:34:18,473 DEBUG    [fe5856dedd59429896636683cd1e188f] awx.main.tasks Last scheduler run was: 2021-09-10 06:33:48.402047+00:00
> 2021-09-10 06:34:28,480 DEBUG    [b965ed91cc844aa895bc37af80f905bd] awx.main.dispatch task c30c211c-2fad-48bc-92ef-c9f48e949eb5 starting awx.main.scheduler.tasks.run_task_manager(*[])
> 2021-09-10 06:34:28,482 DEBUG    [b965ed91cc844aa895bc37af80f905bd] awx.main.scheduler Running task manager.
> 2021-09-10 06:34:28,499 DEBUG    [b965ed91cc844aa895bc37af80f905bd] awx.main.scheduler Starting Scheduler
> 2021-09-10 06:34:28,543 DEBUG    [b965ed91cc844aa895bc37af80f905bd] awx.main.dispatch task 4b663eb2-cfa3-451a-bc75-856b747e331f starting awx.main.analytics.analytics_tasks.send_subsystem_metrics(*[])
> 2021-09-10 06:34:28,591 DEBUG    [b965ed91cc844aa895bc37af80f905bd] awx.main.scheduler Skipping group controlplane, task cannot run on control plane
> 2021-09-10 06:34:28,597 DEBUG    [b965ed91cc844aa895bc37af80f905bd] awx.analytics.job_lifecycle inventoryupdate-9 needs capacity
> 2021-09-10 06:34:28,597 DEBUG    [b965ed91cc844aa895bc37af80f905bd] awx.main.scheduler inventory_update 9 (pending) couldn't be scheduled on graph, waiting for next cycle
> 2021-09-10 06:34:28,601 DEBUG    [b965ed91cc844aa895bc37af80f905bd] awx.main.scheduler Finishing Scheduler
> 

I am new enough to AWX to not know if the "inventoryupdate-9 needs capactity" is a clue or if it's a red herring, but I hope it helps!

**Comment by vrubiolo** [comment]
Hi there,

I think am encountering the same issue here:
```
[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.
ansible-inventory [core 2.12.0.dev0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
[WARNING]: Ignoring invalid path provided to plugin path:
'/runner/project/ansible/stacks/inventory' is not a directory
host_list declined parsing /runner/project/ansible/stacks/inventory/community_prod02_stack.yaml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /runner/project/ansible/stacks/inventory/community_prod02_stack.yaml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
auto declined parsing /runner/project/ansible/stacks/inventory/community_prod02_stack.yaml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /runner/project/ansible/stacks/inventory/community_prod02_stack.yaml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /runner/project/ansible/stacks/inventory/community_prod02_stack.yaml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /runner/project/ansible/stacks/inventory/community_prod02_stack.yaml as it did not pass its verify_file() method
[WARNING]: Unable to parse
/runner/project/ansible/stacks/inventory/community_prod02_stack.yaml as
an inventory source
ERROR! No inventory was parsed, please check your configuration and options.
```

The symptoms which ringed a bell for me what that, in the UI, when adding an inventory source, the dropdown for the 'inventory file' box does not show all files in the project repo as it should, rather an arbitrary, much shorter list (which seems to depend on which branch of the project repo is checked out):
![inventory_file](https://user-images.githubusercontent.com/8413245/134247023-ab1957f0-7693-4c0c-a508-57fdaf87e6c5.png). I have to manually enter the path to the inventory file I want to use, which is not found when syncing.

This is AWX 19.3.0 deployed via the AWX operator (0.13.0) running over Minikube `v1.23.1` and k8s `v1.21.3` on Fedora 34

**Comment by shanemcd** [comment]
Can someone try on 19.4.0 and let us know if the problem is still happening?

**Comment by infra-monkey** [comment]
@shanemcd doesn't work for me in 19.4.0. I still have the same issues
```
ansible-inventory [core 2.11.4] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
setting up inventory plugins
host_list declined parsing /runner/project/inventory.proxmox.yml as it did not pass its verify_file() method
script declined parsing /runner/project/inventory.proxmox.yml as it did not pass its verify_file() method
Loading collection community.general from /runner/requirements_collections/ansible_collections/community/general
/usr/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
toml declined parsing /runner/project/inventory.proxmox.yml as it did not pass its verify_file() method
[WARNING]:  * Failed to parse /runner/project/inventory.proxmox.yml with auto
```
Note: I am using a custom credential type that sets the environment variables. I don't think it would be an issue anyway as the inventory file is not recognized as yaml.
My inventory file:
```
---
plugin: community.general.proxmox
url: https://<ip>:<port>
validate_certs: false
cache: true
want_facts: true
keyed_groups:
  - key: proxmox_tags_parsed
    separator: ""
    prefix: ""
```

**Comment by cljcoder** [comment]
I have also had no joy with 19.4.0.   My first attempt to create the (git) project source would not allow me to select anything except for root as an inventory file, even though there were two inventory files in the project.  A second attempt allowed me to manually enter in an inventory file and attempt to sync it.   The sync job resulted in:


```
ansible-inventory [core 2.11.6rc1.post0] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
   15.702 INFO     Processing JSON output...
   15.712 INFO     Loaded 16 groups, 12 hosts
   15.843 INFO     Inventory import completed for GitNPHosts in 0.1s
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
host_list declined parsing /runner/project/nonprod-inventory.yml as it did not pass its verify_file() method
script declined parsing /runner/project/nonprod-inventory.yml as it did not pass its verify_file() method

```

Manually using these files with a similar version of ansible gives good results, so I believe that they are in fact parseable.

**Comment by mick1627** [comment]
Inventory source from project work for me in version 19.4.0.

I tested auto plugin :

```yaml
ansible-inventory [core 2.11.5] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
host_list declined parsing /runner/project/alicloud.yml as it did not pass its verify_file() method
script declined parsing /runner/project/alicloud.yml as it did not pass its verify_file() method
redirecting (type: doc_fragments) ansible.builtin.alicloud to community.general.alicloud
Parsed /runner/project/alicloud.yml inventory source with auto plugin
   11.911 INFO     Processing JSON output...
   11.919 INFO     Loaded 24 groups, 2 hosts
   12.181 INFO     Inventory import completed for test in 0.3s
```  

and  ini plugin

```yaml
ansible-inventory [core 2.11.5] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
host_list declined parsing /runner/project/test.ini as it did not pass its verify_file() method
script declined parsing /runner/project/test.ini as it did not pass its verify_file() method
auto declined parsing /runner/project/test.ini as it did not pass its verify_file() method
yaml declined parsing /runner/project/test.ini as it did not pass its verify_file() method
Parsed /runner/project/test.ini inventory source with ini plugin
   11.836 INFO     Processing JSON output...
   11.839 INFO     Loaded 1 groups, 1 hosts
   11.897 INFO     Inventory import completed for test in 0.1s
```

The dropdown inventory file list is not working.
Using the GUI, the Inventory file dropdown is empty (even if a project snyc is done before), I have to enter the file name manually.

**Comment by Kardi5** [comment]
Upgrading from 19.2.2 to 19.4, installed using Operator version 0.14 on Kubernetes v1.20, the inventory source works for me.

**Comment by vrubiolo** [comment]
HI there,

Running the same scenario on 19.4, I see the inventory file is now parsed:
```
ansible-inventory [core 2.11.6.post0] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
host_list declined parsing /runner/project/ansible/inventory/community_prod02_redpesk_stack.yaml as it did not pass its verify_file() method
script declined parsing /runner/project/ansible/inventory/community_prod02_redpesk_stack.yaml as it did not pass its verify_file() method
Parsed /runner/project/ansible/inventory/community_prod02_redpesk_stack.yaml inventory source with yaml plugin
    9.121 INFO     Processing JSON output...
    9.124 INFO     Loaded 2 groups, 9 hosts
    9.211 INFO     Inventory import completed for community in 0.1s
 ```

The dropdown menu in the UI still does not work though, I have to enter the path by hand.

This is AWX 19.4 on K3S `v1.19.15+k3s1 (e698d6d8)` deployed via `awx-operator 0.14.0`

**Comment by infra-monkey** [comment]
> @shanemcd doesn't work for me in 19.4.0. I still have the same issues
> 
> ```
> ansible-inventory [core 2.11.4] 
>   config file = None
>   configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
>   ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
>   ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
>   executable location = /usr/local/bin/ansible-inventory
>   python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
>   jinja version = 2.10.3
>   libyaml = True
> No config file found; using defaults
> setting up inventory plugins
> host_list declined parsing /runner/project/inventory.proxmox.yml as it did not pass its verify_file() method
> script declined parsing /runner/project/inventory.proxmox.yml as it did not pass its verify_file() method
> Loading collection community.general from /runner/requirements_collections/ansible_collections/community/general
> /usr/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   warnings.warn(
> toml declined parsing /runner/project/inventory.proxmox.yml as it did not pass its verify_file() method
> [WARNING]:  * Failed to parse /runner/project/inventory.proxmox.yml with auto
> ```
> 
> Note: I am using a custom credential type that sets the environment variables. I don't think it would be an issue anyway as the inventory file is not recognized as yaml. My inventory file:
> 
> ```
> ---
> plugin: community.general.proxmox
> url: https://<ip>:<port>
> validate_certs: false
> cache: true
> want_facts: true
> keyed_groups:
>   - key: proxmox_tags_parsed
>     separator: ""
>     prefix: ""
> ```

Correction , it works for me.
In fact I had the community.general collection set to 3.3.0 in my requirements going to the latest works.
@cljcoder can you check if you are in the same situation?

**Comment by chofstede** [comment]
I can confirm, that Inventory-Sync based from project works fine again in AWX 19.4.0
I think this issue can be closed.

**Comment by wedobetter** [comment]
I still have this issue with:

- awx-operator 0.14.0
- awx 19.4.0
- awx-ee 0.6.0

My inventory path is: inventory/dev/inventory.ini

Same symptoms, the inventory sync output shows:

```
config file = None
...
/runner/project/inventory/dev is not a directory

```

I have debugged the job container and it looks like the project is never git checked out, that's why complains of that missing directory. 

I have tried to use ssh-key and token authentication, which both work fine when sync'ing projects, but not for sync'ing inventories

**Comment by vrubiolo** [comment]
@wedobetter : good idea starting this thread up if you still experience the issue.
I am interested in getting more information on how you debugged the job container. Is there a doc on this?

**Comment by mick1627** [comment]
> I still have this issue with:
> 
> * awx-operator 0.14.0
> * awx 19.4.0
> * awx-ee 0.6.0
> 
> My inventory path is: inventory/dev/inventory.ini
> 
> Same symptoms, the inventory sync output shows:
> 
> ```
> config file = None
> ...
> /runner/project/inventory/dev is not a directory
> ```
> 
> I have debugged the job container and it looks like the project is never git checked out, that's why complains of that missing directory.
> 
> I have tried to use ssh-key and token authentication, which both work fine when sync'ing projects, but not for sync'ing inventories

Can you try with awx-ee:latest , awx-ee 0.6.0  does not work for me with awx 19.4.0 and awx 19.3.0

**Comment by kenichimilo** [comment]
awx - 19.5
operator - 0.15.0
EE - latest
running on openshift 3.11 
@shanemcd is there a way to add extra logging into the worker pod.. we cannot move to any version past 17.1.0.
The project gets updated in the task container and then the inventory sync is passed on to the EE, which i don't know if an extra project pull is done to have the code.
No logging whatsoever when i carry out an oc logs on the EE pod..
It works in ver 17.1.0 as everything is done in the same task pod..

**Comment by maveleo** [comment]
May I ask why the issue has been closed given that there is not a fix ?
@kenichimilo are you using 17.1.0 with the operation 0.15.0 ?
