### ISSUE TITLE
RFE: Template Admins able to modify permissions

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#1087]
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
API

##### SUMMARY
Client would like all users in an Org to be able to see Teams and grant them permissions on Job Templates that they are admins on.

**Comment by wenottingham** [comment]
This is not a UI issue, it's an API issue (and I think it's a bug).

**Comment by AlanCoding** [comment]
closing as resolved
