### ISSUE TITLE
Approval Node Allows Saving without Required Name Field Value 

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#10872]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

A workflow job template node has an active save button even with the name field being empty.  The User can save this node, and the modal will close and show a DELETED text on the node inside the visualizer

### AWX version

devel

### Installation method

docker for mac

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

Create a workflow job template.
Go to the visualizer and create a node.  Select Approval node.
Leave name field blank and click save

### Expected results

The save button should be disabled without a name field.  

### Actual results

The save button is enabled and the user can save, and then closed with wizard

**Comment by tiagodread** [comment]
Fixed with #10907
