### ISSUE TITLE
RFE: Launch a Job Template after the inventory source syncs

### ISSUE THREAD

**Issue by tuxonfire** [ansible/awx#10875]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Feature request to launch a Job Template after an inventory source syncs.

**Comment by wenottingham** [comment]
This can be accomplished today with a workflow. What is the use case that can't be handled in that way?

**Comment by wenottingham** [comment]
Closing, we don't plan to do this and there are other ways to accomplish this that we recommend.
