### ISSUE TITLE
AWX CLI --monitor truncated output

### ISSUE THREAD

**Issue by ghost** [ansible/awx#10880]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

I am using awx cli to launch template from a remote machine. While using the --monitor option, the output of the playbook run is not shown in its entirety.

### AWX version

16.0.0

### Installation method

docker on linux

### Modifications

no

### Ansible version

2.9.5

### Operating system

CentOS 7

### Web browser

Chrome

### Steps to reproduce

Launch a long enough ansible playbook with awx --monitor option

### Expected results

the entire playbook run result is shown on the standard output.

### Actual results

Only a portion of playbook run result is shown on the standard output and then cut off by the delimiter:

------End of Standard Out Stream--------

### Additional information

I did not use "--filter".

**Comment by phemmer** [comment]
see #10194

**Comment by ghost** [comment]
thanks phemmer.

**Comment by wenottingham** [comment]
Closing as a duplicate.
