### ISSUE TITLE
Inventory Level Surveys

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/awx#10882]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Add surveys at the inventory level which would prompt against jobs targeting that inventory.

**Comment by wenottingham** [comment]
This is something that would require some level of combining surveys, which isn't something we've implemented, and in terms of customer/user requests, would be below #20. At a level of a full automation platform, this is something that may be done in a services catalog that exposes automation to end users. 

I'm curious what sort of automation you're building that you'd want this for  - what is the survey items you'd want to ask at an inventory level? Especially if it's passwords, this is better solved by something like #286 when it gets to that point.

This isn't on the near or medium term roadmap for AWX, and we'd suggest looking at other workarounds for this.
