### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by neilcavendish** [ansible/awx#10881]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Hey All,

I am just starting out with Ansible and AWX, I have got a lot of playbooks working but I am stuck on the bellow with a error I am not sure how to fix
.
Im testing creating a host in AWX and I am getting connection refused, bellow is my play-book:

```
---  
- name: Create Host
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - awx.awx
  tasks:
  - name: Add host
    tower_host:
      name: Name
```

When I run this I get the following error:

```
TASK [Add host] ****************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "There was an unknown error when trying to connect to https://127.0.0.1/api/v2/inventories/?name=webservers: URLError <urlopen error [Errno 111] Connection refused>"}
      inventory: inventory
```

Any ideas how to get this to work?

### AWX version

Latest (I think)

### Installation method

kubernetes

### Modifications

no

### Ansible version

Latest (I think)

### Operating system

Rocky Linux

### Web browser

Chrome

### Steps to reproduce

Try and use the awx module to add to the inventory

### Expected results

Host added 

### Actual results

TASK [Add host] ****************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "There was an unknown error when trying to connect to https://127.0.0.1/api/v2/inventories/?name=webservers: URLError <urlopen error [Errno 111] Connection refused>"}
      inventory: inventory

**Comment by neilcavendish** [comment]
There is an inventory called webservers FYI

**Comment by neilcavendish** [comment]
I think its because I run this on a weird port. How to I pass the port into my Playbook?

**Comment by wenottingham** [comment]
See https://docs.ansible.com/ansible/2.9/inventory/implicit_localhost.html - this is a playbook issue, most likely.

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an ansilble playbookl, try our mailing list or IRC channel:

Mailing list: https://groups.google.com/forum/#!forum/ansible-users
IRC: ansible on irc.libera.chat
