### ISSUE TITLE
AWX delegate_to localhost use ssh instead local conection

### ISSUE THREAD

**Issue by rfarajro** [ansible/awx#10896]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### ENVIRONMENT
* AWX version: AWX 14.1.0 
* AWX install method:  developer environment
* AWX deployment target: openshift
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Run playbook using delegat_to localhost in a template.

##### EXPECTED RESULTS

Use sh comand instead sshpass

##### ACTUAL RESULTS

Failed to connect to the host via ssh: ssh: connect to host localhost port 22: Connection refused

##### ADDITIONAL INFORMATION

 We have 2 environments, in one of them works well without the var ansible_connection: local, but in the other fail with the mentioned error. Same playbook and same template in both environments.

**Comment by wenottingham** [comment]
This issue tracker is for tracking feature enhancements and bugs to AWX itself.
This looks like a playbook and/or inventory issue related to implicit localhost: https://docs.ansible.com/ansible/2.9/inventory/implicit_localhost.html

If you need help troubleshooting an AWX install or an ansible playbook, try our mailing list or IRC channel:

Mailing list: https://groups.google.com/forum/#!forum/awx-project
IRC: ansible-awx on irc.libera.chat

**Comment by rfarajro** [comment]
Hi,

This is not a playbook or inventory related issue, the same playbook and inventory works on another AWX installation with the same configuration and this local run was working in this environment 2 weeks ago.

 Thanks.

**Comment by rfarajro** [comment]
Issue solved. Thanks

**Comment by Nitish0292** [comment]
> Issue solved. Thanks

how did you fix this issue can you please share details, i am facing the same issue
