### ISSUE TITLE
job stdout not live updated in the last version awx 19.2.2

### ISSUE THREAD

**Issue by abdel-ops** [ansible/awx#10895]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Hello,
 We faced thes same issue in awx 17.1.0 , the answer was that we have to upgarde to 19.2.2 , but the result is always the same , the log is not live updated until the job finish even with the last version of awx.

### AWX version

19.2.2

### Installation method

docker on linux

### Modifications

no

### Ansible version

2.9.9

### Operating system

Linux

### Web browser

Chrome

### Steps to reproduce

Install awx version 19.2.2
launch job template

### Expected results

Log live updated

### Actual results

empty screen until the job finish

**Comment by shanemcd** [comment]
Hi - are you using the development environment or the operator?

**Comment by abdel-ops** [comment]
Hello
I'm using the development environment.

**Comment by mabashian** [comment]
There have been a number of changes to this area of the codebase in the past 9 months.  Give it a try with v20 and if you're still seeing this behavior, reopen or create a new issue.
