### ISSUE TITLE
Issue importing SSO users

### ISSUE THREAD

**Issue by gensi0** [ansible/awx#10905]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Hi, 

I'm trying to ugrade my AWX from 14.1.0 to 19.3.0. 

Before upgrading in production i first installed AWX 19.3.0 on my machine and used `awx` command to export then import orgs, templates, users, project... 

All users on 14.1.0 were created by using google Oauth2. On 19.3.0 I configured Oauth2 but when I'm trying to connect to an existing account with Oauth2 I get this error : 

Exception Value: | The given email address is associated with another account
-- | --

It seems to me that when using the SSO  on a fresh Install, it will try to create the account and no use the one already created. 

Is there another way to import SSO users ? 

Thanks for all the work,

### AWX version

19.3.0

### Installation method

docker on linux

### Modifications

no

### Ansible version

2.9.6

### Operating system

Ubuntu 20.04.2 LTS

### Web browser

Firefox

### Steps to reproduce

- Install AWX 19.3.0 with [docker-compose](https://github.com/ansible/awx/blob/devel/tools/docker-compose/README.md).
- Export from AWX 14.1.0 : `awx export --conf.host https://awx.fqdn --conf.username <user> --conf.password '<passwd>' > /tmp/export.json`
- Import to new local AWX 19.3.0 : `awx import --conf.user <user> --conf.password '<passwd>' --conf.insecure --conf.host https://127.0.0.1:8043/ < /tmp/export.json `
- Try to connect to AWX 19.3.0 with SSO account.

### Expected results

Connecting with expected SSO user.

### Actual results

![awx_error_sso](https://user-images.githubusercontent.com/71636603/129865691-1694dc20-cf7a-4e2d-80c1-15930a4dc25d.png)

**Comment by shanemcd** [comment]
When someone has a chance, can you verify that the exported users preserve the flag that signifies that they came from SSO?

**Comment by gensi0** [comment]
> When someone has a chance, can you verify that the exported users preserve the flag that signifies that they came from SSO?

Hello @shanemcd , after a reinstall of the whole minikube env and reinstallation of awx 19.3.0 it seems to be working. I need to do more tests and I will close this issue if it's fixed.

**Comment by gensi0** [comment]
Maybe it was a configuration issue on my part, but I can't find what I could have done on the first install.

**Comment by shanemcd** [comment]
Glad to hear it! If you see something weird in the future open a new issue.
