### ISSUE TITLE
Add support for indexer acknowledgment in a HEC

### ISSUE THREAD

**Issue by mrmibrown** [ansible/awx#10913]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
This is a request to add support for indexer acknowledgment in a https/http event collector:

"This capability on forwarders helps prevent loss of data when sending data to an indexer. With indexer acknowledgment, the forwarder resends any data not acknowledged as "received" by the indexer."

**Comment by wenottingham** [comment]
This would need to be done in the omhttp module of the operating system rsyslog... it's not something we can affect in AWX.
