### ISSUE TITLE
Modification to the credential plugin system to get an external credential for each host in the play

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#10924]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Similar/add-on request to #286 

Users can use Cyberark to manage and rotate ssh keys on a per-host basis.
This means all hosts have different ssh keys and therefore require an external lookup on a per-host basis.

**Comment by wenottingham** [comment]
Closing as a duplicate of #286.
