### ISSUE TITLE
Refactoring awx/api/views/__init__.py

### ISSUE THREAD

**Issue by x0r3ax3ax** [ansible/awx#10939]
I suggest refactoring api/views/__ init__.py, because this file with views is too large and inconvenient to navigate through it.
https://github.com/ansible/awx/blob/devel/awx/api/views/__init__.py

I could be do this.

##### ISSUE TYPE
 - Feature Idea

**Comment by shanemcd** [comment]
I'll just say that we are unlikely to do this. It's maybe a philosophical position, but there are better ways to browse code than to split things up in different files.
