### ISSUE TITLE
Fix EEs from protected registries on execution-only nodes

### ISSUE THREAD

**Issue by shanemcd** [ansible/awx#10944]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

![image](https://user-images.githubusercontent.com/773186/130968122-86616704-a64a-4836-92c0-f10117834c18.png)

### AWX version

devel sometime on 8/25

### Installation method

openshift

### Modifications

no

### Steps to reproduce

Try to run a job using an EE from an auth-protected registry.

### Expected results

💥 (see screenshot above)

### Actual results

🚀 😎

**Comment by AlanCoding** [comment]
Changes on the AWX side are code-complete.

We have 1 straggler on the runner side https://github.com/ansible/ansible-runner/pull/829, _but_, I don't think that affects any use case that integration testing currently hits (I only know of a means to _manually_ test). Anyway, it is expected that that should land by EOD today.

That's a bit of qualifier, but nonetheless moving to needs_test

**Comment by kdelee** [comment]
@AlanCoding That PR is still hanging out. I also know we are waiting on a few more PR's going into runner. Whats up with that?

**Comment by beeankha** [comment]
@kdelee we are working on getting in-progress Runner PRs merged in by hopefully the middle of next week! The main Runner PR related to this issue (https://github.com/ansible/ansible-runner/pull/817) has been merged; the remaining WIP stuff is not related to this particular "protected EE registries" issue.

**Comment by Zokormazo** [comment]
This is working properly now
