### ISSUE TITLE
Edit workflow nodes should display current convergence label

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#10945]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

When editing a workflow node the dropdown to select convergence label always show `ALL` as the selected choice. Even when `Any` was the previous selected choice when creating the node.

### AWX version

devel

### Installation method

docker for mac

### Modifications

no

### Steps to reproduce

1. Create and save a node with ALL convergence
2. Open visualizer
3. Change node to Any
4. Edit node again, dropdown says All

### Expected results

Dropdown should show the previous selected choice as the selected one.

### Actual results

Dropdown does not show the previous selected choice as the selected one.

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/9053044/130990431-c827ab75-b439-4080-9f81-4fb01058355a.png">
<img width="1516" alt="image" src="https://user-images.githubusercontent.com/9053044/130990490-af8e4aff-7b3f-4f2a-a109-c5efba2fdf1f.png">

**Comment by InnocentK** [comment]
Resolved
