### ISSUE TITLE
Background job to cleanup private_data_dir files left by interrupted job

### ISSUE THREAD

**Issue by jladdjr** [ansible/awx#10948]
When a job runs successfully on awx, the private_data_dir should be cleaned up, both on the controller instance where it was created and on the execution instance. This work should already be addressed by https://github.com/ansible/awx/issues/10687.

If a job fails abnormally (e.g. due to a network failure, tower services restarting unexpectedly, etc), we need to ensure that all copies of the private_data_dir are cleaned up.

## Acceptance Criteria

Create a new periodic task that
- [ ] prunes private_data_dirs  for inactive jobs on remote execution nodes
- [ ] prunes private_data_dirs  for inactive jobs on controller instances

**Comment by shanemcd** [comment]
A _little_ more context here would be good.

**Comment by jladdjr** [comment]
@shanemcd 👍  see updated description

**Comment by jladdjr** [comment]
We could see this also incorporating the task of cleaning up unused images - see https://github.com/ansible/awx/issues/10701

**Comment by AlanCoding** [comment]
I've created this doc to express what I'm trying to do

https://gist.github.com/AlanCoding/99de3b85031cae3b7f2c7c8f81560359#file-cleanup_demo-md

**Comment by AlanCoding** [comment]
> prunes private_data_dirs for inactive jobs on controller instances

We already have a mechanism for this and have no intention of changing anything with it.

**Comment by AlanCoding** [comment]
Recap of active PRs:

 - awx change: https://github.com/ansible/awx/pull/11160
 - runner change: https://github.com/ansible/ansible-runner/pull/846

**Comment by jladdjr** [comment]
@thenets - just checking in, do you need any info for testing this?
