### ISSUE TITLE
Empty survey list should follow same empty state pattern as rest of UI

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#10942]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Survey empty state should render a tool bar on top of empty state message.

### AWX version

devel

### Installation method

docker for mac

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

Go to template with no surveys

### Expected results

Normal list toolbar should be rendered

### Actual results

![Screen Shot 2021-08-25 at 1 43 28 PM](https://user-images.githubusercontent.com/39280967/130839399-48cd749a-98e2-4095-bd6a-2a54acf26bf0.png)

**Comment by InnocentK** [comment]
Successfully resolved in #11122
