### ISSUE TITLE
Create Instance Details View and Health Check

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#10951]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The instance details view should have standard detail data, but also should have an associate, disassociate, and health check button.  The health check button should POST to `/api/v2/instances/N/health_check/` and render whatever it returns. It could return a series of errors if the instance is having a problem.  In that case it may make sense to break those errors down and render them separately in the ui.  

We will also want to be sure the render the date/time of the last health check.

@trahman73 any other thoughts about this?  

I'm imagining something like https://tower-mockups.testing.ansible.com/patternfly/projects/projects-detail/, but the action buttons will be Associate, Disassociate, Health Check.

**Comment by trahman73** [comment]
**Updated Instance Groups / Instances list view mockup**
https://tower-mockups.testing.ansible.com/patternfly/instance-groups/instance-groups-instances/

- Instance names now have a link to an individual details view
- Status column added to list view
- Health check action button added to list view
- Potential to move some list view details off to the details view

**New preliminary Instance details view mockup**
https://tower-mockups.testing.ansible.com/patternfly/instance-groups/instance-groups-instances-detail/

- Instance name, status, and last updated areas added
- Placeholder for health check results
- Action button to re-run the health check

**Comment by AlexSCorey** [comment]
related https://github.com/ansible/awx/issues/10737#issuecomment-904864213

**Comment by AlanCoding** [comment]
The mockups look good. API work for the health check endpoint has been merged. This contains the `errors` field which can contain user-oriented messages.

One thing I want to note after looking at the mockup - healthy instances will usually have a blank `errors` field.

I don't think we have merged API changes to allow de-provisioning (deleting) instances, but it's on the agenda.
