### ISSUE TITLE
Webhook Notification does not allow for use of Jinja Statements

### ISSUE THREAD

**Issue by jw-maynard** [ansible/awx#10961]
### Please confirm the following

- [x] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

The server seems to validate that the payload of a Webhook notification is valid JSON *before* applying the Jinja template to the payload. This precludes using Jinja statements like conditionals or loops in the payload because the Jinja statments are detecting as invalid JSON.

### AWX version

19.3.0

### Installation method

kubernetes

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

Just create a Webhook notification and try to use a Jinja statement. Example:
`{% for key, value in job.host_status_counts.items() %}
 {
                                    "title": "{{ key }}",
                                    "value": "{{ value }}",
                                    "short": true
                                },
{% endfor %}`

### Expected results

The template should be rendered first with perhaps a dummy set of values and then validated as JSON.

### Actual results

AWX rejects the content and does not save th change to the webhook

**Comment by chrismeyersfsu** [comment]
@jw-maynard sounds like you pinpointed the problem. Do you think you could submit a PR fixing it?

**Comment by jw-maynard** [comment]
@chrismeyersfsu I'm not really familiar with the code base at all. I just determined what seemed to be happening based on the responses in the chrome console. If you could give me an idea of where in the code base I should start looking I could take a stab at it.

**Comment by jw-maynard** [comment]
@chrismeyersfsu See PR #11366

**Comment by AlanCoding** [comment]
To develop a test case, I had to pad the syntax you gave a bit. Firstly, it will only accept a dictionary (not other types like a list), and secondly, the trailing comma isn't allowed.

```
{"host_status_list": [{% for key, value in job.host_status_counts.items() %} {"title": "{{ key }}", "value": "{{ value }}"}, {% endfor %} ""]}
```

It is kind of hard to create a template that generates valid JSON due to fairly strict syntax rules. Ultimately, that is on the user to get right.
