### ISSUE TITLE
fmgr_dvmdb_script Module not working in Ansible 2.9.6

### ISSUE THREAD

**Issue by sanjay-chahar** [ansible/awx#10963]
SUMMARY

I have an Fortimanager 6.4.5 VM with trail license running on it. I'm trying to create script on fortimanager using fmgr_dvmdb_script module, but it is not working. 

ils/napi.py\", line 215, in get_system_status\n  File \"/tmp/ansible_fmgr_dvmdb_script_payload_8fb7avte/ansible_fmgr_dvmdb_script_payload.zip/ansible/module_utils/connection.py\", line 185, in __rpc__\nansible.module_utils.connection.ConnectionError: An attempt was made at communicating with a FMG with no valid session and an unexpected error was discovered.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

ISSUE TYPE

Bug Report
COMPONENT NAME
fmgr_dvmdb_script
fmgr_generic

ANSIBLE VERSION
ansible 2.9.6
  config file = /home/sanjay/ansible.cfg
  configured module search path = ['/home/sanjay/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]

CONFIGURATION
[defaults]
# some basic default values...
inventory      = /home/sanjay/hosts
#library        = /usr/share/my_modules/
module_utils   = ['/home/sanjay/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
keep_remote_files = true
#remote_tmp     = ~/.ansible/tmp
local_tmp      = ~/.ansible/tmp

OS / ENVIRONMENT
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"

STEPS TO REPRODUCE
Playbook:
---
- hosts: fortimanagers
  connection: httpapi
  collections:
  - fortinet.fortimanager
  vars:
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
   - name: Create a script on FortiManager.
     fmgr_dvmdb_script:
        adom: 'adom'
        state: 'present'
        dvmdb_script:
           desc: 'The script create via Ansible'
           type: 'cli'
           name: 'fooscript'
           content: |
                      config system global
                         set timezone 04
                      end

Inventory file:

[fortimanagers]
192.168.252.131 ansible_host=192.168.252.137 #ansible_user="admin" ansible_password="sanjay123"
[fortigates]
192.168.252.135 ansible_host=192.168.252.137 #ansible_user="admin" ansible_password="sanjay123"
[fortigates:vars]
ansible_network_os=fortinet.fortios.fortios
[fortimanagers:vars]
ansible_network_os=fortinet.fortimanager.fortimanager
ansible_user=root
ansible_password=xxxxxxxxx
ansible_become=no
ansible_become_method=disable
ansible_httpapi_use_ssl=true
ansible_httpapi_validate_certs=false
ansible_httpapi_timeout=300

[fortigates:vars]
ansible_network_os=fortinet.fortios.fortios

EXPECTED RESULTS
It should run script onForti manager device. I have alos tried other modules all the modules fail with same error.

ACTUAL RESULTS

ections/fortinet/fortimanager/plugins/modules/fmgr_dvmdb_script.py\", line 699, in <module>\n  File \"/tmp/ansible_fmgr_dvmdb_script_payload_8fb7avte/ansible_fmgr_dvmdb_script_payload.zip/ansible_collections/fortinet/fortimanager/plugins/modules/fmgr_dvmdb_script.py\", line 690, in main\n  File \"/tmp/ansible_fmgr_dvmdb_script_payload_8fb7avte/ansible_fmgr_dvmdb_script_payload.zip/ansible_collections/fortinet/fortimanager/plugins/module_utils/napi.py\", line 87, in __init__\n  File \"/tmp/ansible_fmgr_dvmdb_script_payload_8fb7avte/ansible_fmgr_dvmdb_script_payload.zip/ansible_collections/fortinet/fortimanager/plugins/module_utils/napi.py\", line 215, in get_system_status\n  File \"/tmp/ansible_fmgr_dvmdb_script_payload_8fb7avte/ansible_fmgr_dvmdb_script_payload.zip/ansible/module_utils/connection.py\", line 185, in __rpc__\nansible.module_utils.connection.ConnectionError: An attempt was made at communicating with a FMG with no valid session and an unexpected error was discovered.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by sanjay-chahar** [comment]
Please let me know if you need any further information

**Comment by chrismeyersfsu** [comment]
This is an Ansible issue. Please submit your question to the Ansible mailing list https://groups.google.com/g/ansible-project?pli=1
