### ISSUE TITLE
At ~/#metrics page, strings 'Time spent saving events to database' and 'Legend', needs to be marked for translations

### ISSUE THREAD

**Issue by sshedmake** [ansible/awx#10970]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

When in ja google-chrome, at ~/#metrics page, strings 'Time spent saving events to database' and 'Legend', needs to be marked for translations

### AWX version

19.3.0

### Installation method

docker on linux

### Modifications

yes

### Steps to reproduce

1. Launch UI in ja google-chrome
2. Visit the ~/#metrics url
3. Click 'Select a instance' dropdown
4. Click or select 'All' option
5. Click 'Select a metric' dropdown
6. Click or select 'callback_receiver_events_insert_db_seconds' option
7. Observe translation of label 'Legend' and 'Time spent saving events to database'

### Expected results

100% Translated (into Japanese)

### Actual results

Appears in English

### Additional information

1. When in ja google-chrome, to find strings obviously in English, just swapped the ~/ja/messages.js with dummy ja translation and rebuild the UI
2. Screenshot 1 highlighting the unmarked strings when in ja google-chrome
![Screenshot from 2021-08-29 21-43-53_2](https://user-images.githubusercontent.com/12151785/131337857-29eaad9f-409d-421b-927b-238660e2e04e.png)

**Comment by AlexSCorey** [comment]
A couple of the strings do come form the UI. However, the string `Time spent saving events to database` is a help text string that comes from the api.  I connected with @fosterseth to see if he could check this out.
