### ISSUE TITLE
Number getting converted to a completely something different under host variables in different formats.

### ISSUE THREAD

**Issue by Jamal-A-Mohamed** [ansible/awx#10976]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
when I save host variables in awx, it seems some numbers show up the wrong way in json and thus breaking playbook.

##### ENVIRONMENT
* AWX version: 19.2.2

* AWX install method: operator
* AWX deployment target: minikube
* Operating System: Redhat
* Web Browser: Firefox

##### STEPS TO REPRODUCE
under a host variable  enter the following 
v_instances: [0024] under yaml, switch to json by clicking on the json, you will see 20 instead of 0024,
Run a playbook with that variable and it shows up as 20.

##### EXPECTED RESULTS
The numbers should be the same regardless the format.

##### ACTUAL RESULTS
based on format change it numbers get converted to  a diffferent number.

##### ADDITIONAL INFORMATION

https://user-images.githubusercontent.com/37128483/131379313-c5aab50a-af47-4d22-afc1-b2a3bcd945c9.mov

**Comment by Jamal-A-Mohamed** [comment]
After bit more looking, this is a java-script issue,
It seems that in java-script if a number has leading zeros it will be  detected as an octal number and thus  converted to decimal equivalent. in my case 0024 was being detected as  octal(20)  and was being converted  into decimal (20) 
To resolve the issue you have to either remove the leading zeros or put it in quotes.

I think users shouldn't be expected to know this and fix should be made, easiest might be to disable the use of numbers with leading zeros.

<img width="456" alt="Screen Shot 2021-08-30 at 12 40 09 PM" src="https://user-images.githubusercontent.com/37128483/131381567-d5d7f412-982e-46ad-9dd5-1d3df0a76c2e.png">

**Comment by keithjgrant** [comment]
This is an interesting find. Is it acceptable to strip off the leading zeroes? They will remain stripped off if converted back to YAML

**Comment by Jamal-A-Mohamed** [comment]
Unfortunately, for our use we need the leading zeros.

**Comment by keithjgrant** [comment]
> Unfortunately, for our use we need the leading zeros.

This is interesting... I don't think there's technically a way to preserve leading zeros in JS, unless you can put it in quotes and use it as a string. (If you keep the input in YAML format, I think the whole value is stored internally as a string, which is why the YAML input can preserve it)

**Comment by keithjgrant** [comment]
@Jamal-A-Mohamed Okay, I looked a little closer at our implementation. The value is stored as a string in BOTH modes, it's only converted to an object briefly for the translation between the two. It _might_ be possible to intercept numbers with a leading zero and briefly treat them as strings.

**Comment by Jamal-A-Mohamed** [comment]
@keithjgrant  if you can do that, it would work for us and we would be happy to test it.

**Comment by keithjgrant** [comment]
@Jamal-A-Mohamed I've discussed this with the team a bit, and we're reluctant to take on the maintenance this would require (it's not trivial, and is likely bug-prone). Can you put those numbers in quotes and use them as a string as a workaround?

**Comment by Jamal-A-Mohamed** [comment]
Yes, that is what I am doing currently doing.
 If it's not feasible to stop the conversion then it might be worth calling it out in documentation.

Thank you  for your efforts @keithjgrant

**Comment by mabashian** [comment]
@tvo318 I don't think we're going to take any actions here but this might be worth a line or two in the docs to explain this behavior and what the workaround is.

**Comment by tvo318** [comment]
@mabashian, @keithjgrant - did this get fixed recently? I have a new instance (devel - 4.4) and I cannot recreate this issue:

[Recreate-yaml-json.webm](https://user-images.githubusercontent.com/7514801/230422473-73aae3af-d745-45e9-b79c-f1be76ee1ac3.webm)

I tried this for Templates, Inventories and Hosts in 4.3 also and cannot recreate this issue. Maybe no longer an issue?

**Comment by tvo318** [comment]
Closing because unable to recreate in 4.4 and 4.3; exists in 4.2 but that version is no longer maintained.
