### ISSUE TITLE
inventory with project as as source doesn't update on launch/refresh

### ISSUE THREAD

**Issue by quasd** [ansible/awx#10986]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Problems
1. When refreshing a inventory source that comes from project using git, the project is not updated. ( Update on launch: checked )
2. This  also applies to running anything using that inventory, no project update.  ( the projects for the template, and for the inventory are different. Project used for inventory does have: Update revision on job launch)

When comparing what is different between manually triggering the project update and triggering the update through inventory source I noticed the manual project update job is started with

```
            "job_type": "check",
            "job_tags": "update_git,install_roles,install_collections,delete"
```
and the job started from 1 or 2 is started with 

```
            "job_type": "run",
            "job_tags": "update_git"
```
and also if I edit pre_run_hook in class RunInventoryUpdate(BaseTask):
/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py
``` 
            local_project_sync = source_project.create_project_update(
                _eager_fields=dict(
                    launch_type="sync",
                    job_type='run',  
                    job_tags=','.join(sync_needs),
                    status='running',
                    execution_node=inventory_update.execution_node,
                    instance_group=inventory_update.instance_group,
                    celery_task_id=inventory_update.celery_task_id,
                )
            )

```
to (job_type='run' )
```
            local_project_sync = source_project.create_project_update(
                _eager_fields=dict(
                    launch_type="sync",
                    job_type='run',  
                    job_tags=','.join(sync_needs),
                    status='running',
                    execution_node=inventory_update.execution_node,
                    instance_group=inventory_update.instance_group,
                    celery_task_id=inventory_update.celery_task_id,
                )
            )

```
After doing these changes the inventory source update correctly updates the source project to latest commit. 

### AWX version

Ansible Automation Platform 4.0.0

### Installation method

docker on linux

### Modifications

yes

### Ansible version

core 2.11.2

### Operating system

Red Hat Enterprise Linux release 8.4 (Ootpa)

### Web browser

Chrome

### Steps to reproduce

A: Have 2 projects that use Source Control Type: git and have Enabled Options: Update revision on job launch
1. with the inventory
2. with any playbook

B: Configure inventory with source with type "Sourced from a Project" using 1 and Enabled Options: Update on launch

C: Check the git revision in projects
D: Commit something to git repository used in 1
E: Click "Start sync process" in inventory source configured in step B

### Expected results

Project 1 updates to revision commited in step D

### Actual results

Project 1 stays in the revision initially synced 

### Additional information

My previous pull request is applied:
https://github.com/ansible/awx/pull/10972#event-5227860337

**Comment by chrismeyersfsu** [comment]
I think this is the feature you are looking for. On the inventory -> sources -> edit screen

![image](https://user-images.githubusercontent.com/722880/134716339-8123ba95-4175-475a-b940-e6e57773731c.png)

**Comment by quasd** [comment]
I would think the "update on launch" is correct,since we want the inventory to update on launch? Since the inventory and the playbook are in separate projects, I don't see how "Update on project update" would ever trigger on template launch of a different project.

I did give it a go though, and no chance. 

Maybe I should try to rephrase the problem. 

When refreshing inventory that uses git as a source, the source project never gets updated.  Is this as intended or should the inventory refresh also make the source SCM project refresh?
```
ansible-inventory [core 2.11.4] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.6 (default, Jan 22 2021, 11:41:28) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /runner/project/inventory_dev.yaml as it did not pass its verify_file() method
script declined parsing /runner/project/inventory_dev.yaml as it did not pass its verify_file() method
Parsed /runner/project/inventory_dev.yaml inventory source with yaml plugin
   13.452 INFO     Processing JSON output...
   13.453 INFO     Loaded 9 groups, 5 hosts
   13.533 INFO     Inventory import completed for <retracted>/inventory-source in 0.1s
```
I

**Comment by TheBlaide** [comment]
I'm facing the same issue. My inventory that uses git as a source is not updated correctly, it displays the id of the last change on the git repository, but files are not updated.

**Comment by pawelbialasiewicz** [comment]
The workaround is to run a NOP job sourced from the repository with inventory. You can use workflows to achieve this. This is the best solution we found to fix this issue.

**Comment by chrismeyersfsu** [comment]
related to https://github.com/ansible/awx/issues/11336

**Comment by TheBlaide** [comment]
Hello,
@pawelbialasiewicz  What do you mean by a NOP job ?

**Comment by pawelbialasiewicz** [comment]
@TheBlaide a job that does nothing but is sourced from the repository that contains the inventory. This way the inventory gets refreshed. You can run any playbook and simply define a target that is not in the inventory. The job will not run as it does not have any targets, but it will get the inventory refreshed. Silly hack, but it gets the job done.

**Comment by AlanCoding** [comment]
I suggest this will be resolved with https://github.com/ansible/awx/pull/12073, and I will probably close this issue after that merges.
