### ISSUE TITLE
Slack Notifications not sent

### ISSUE THREAD

**Issue by twhiston** [ansible/awx#1101]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - Notifications

##### SUMMARY
I cannot get slack notifications to send from AWX currently. After entering a correct slack configuration and trying the test notification AWX reports that it is successful, however no message arrives in slack. In the logs I can see the job being sent to the task worker, and the job, but it seems to only open the websocket, and never post the message.
```
task_1       | [2018-02-01 13:47:48,505: DEBUG/MainProcess] Task accepted: awx.main.tasks.send_notifications[0af135fd-c497-4660-8dd0-6c0dff37bd6c] pid:166
task_1       | [2018-02-01 13:47:48,537: DEBUG/ForkPoolWorker-24] Starting new HTTPS connection (1): slack.com
task_1       | [2018-02-01 13:47:49,010: DEBUG/ForkPoolWorker-24] https://slack.com:443 "POST /api/rtm.start HTTP/1.1" 200 30868
task_1       | [2018-02-01 13:47:50,459: INFO/ForkPoolWorker-24] Task awx.main.tasks.send_notifications[0af135fd-c497-4660-8dd0-6c0dff37bd6c] succeeded in 1.955134352s: None
```
I would assume that after opening this socket it would actually need to post the message to it.

I have tested that the containers have connectivity by curl-ing a simple message to slack, which is received.

##### ENVIRONMENT
Fails in both our production environment (docker on linux with an nginx reverse proxy in front)and on a localhost setup (docker on mac, no proxy)

* AWX version: 1.0.2.75
* AWX install method: , docker on linux, docker for mac
* Ansible version:  2.4.2.0

##### STEPS TO REPRODUCE

Configure slack notifications with a working bot token, and a public channel, press the test notification button. 
##### EXPECTED RESULTS

A green 'Notification sent' message will be shown and a message is posted to the configured slack channel

##### ACTUAL RESULTS

A green 'Notification sent' message will be shown but no message is posted to slack

**Comment by tumluliu** [comment]
same problem here. can see the green sign, but got no message in slack.

**Comment by jaredevantabor** [comment]
I can confirm I'm seeing this in AWX (API returns "successful") but there is no slack notification. We'll definitely get this straightened out soon.  @matburt

**Comment by matburt** [comment]
cc @wwitzel3 I think we had done some work around this a little while ago.

**Comment by wwitzel3** [comment]
There is a fix for slack notifications that will be merged very soon.
