### ISSUE TITLE
Login redirect not working

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#11012]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

When on v2.0EA, the Login redirect override URL is set, the /#/login page can't be reached anymore. Even when a direct URL in put in the browser like https:///#/login, the page redirects to the SAML login page as defined in the redirect override.

This is issue always happens when the Login redirect override URL is set.

Users are unable to login to AAP as a non-social user like the admin user.

### AWX version

devel

### Installation method

docker for mac

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

When on v2.0EA, the Login redirect override URL is set, the /#/login page can't be reached anymore. Even when a direct URL in put in the browser like https:///#/login, the page redirects to the SAML login page as defined in the redirect override.

This issue always happens when the Login redirect override URL is set.

### Expected results

Users are able to login to AAP as a non-social user like the admin user.

### Actual results

Users are unable to login to AAP as a non-social user like the admin user.

**Comment by nixocio** [comment]
See: https://github.com/ansible/awx/pull/5479

**Comment by tiagodread** [comment]
@one-t can we close this issue?

**Comment by nixocio** [comment]
@tiagodread @one-t  this is a legit bug, I already worked on this, I will circle back to this one later.
