### ISSUE TITLE
Unable to use ansible_facts for smart inventory source

### ISSUE THREAD

**Issue by ivantomica** [ansible/awx#11017]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

One older article describes how ansible_facts can be used to create smart inventory within AWX/Ansible tower: https://www.ansible.com/blog/ansible-tower-advanced-smart-inventory-usage

Unfortunately this feature seems to be broken or not properly documented, as API doesn't seem to be recognizing field ansible_facts.

GET to /api/v2/hosts/?ansible_facts.ansible_distribution_version=18.04
```
HTTP 400 Bad Request
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
X-API-Node: awx-6bd564b87c-26bv6
X-API-Product-Name: AWX
X-API-Product-Version: 19.3.0
X-API-Time: 0.005s

{
    "error": "Host has no field named 'ansible_facts.ansible_distribution_version'"
}
```

### AWX version

19.3.0

### Installation method

kubernetes

### Modifications

no

### Web browser

Firefox

### Steps to reproduce

1. Go to Inventory
2. Add - Smart Inventory
3. Try to filter using "Smart host filter" field

Alternative:
1. Go to /api/v2/hosts/
2. try using query string with desired field (eg /api/v2/hosts/?ansible_facts.ansible_distribution_version=18.04)

### Expected results

API queries facts and displays hosts that only match those facts

### Actual results

API complains that the field is incorrect

### Additional information

Using any top-level field works normally:

eg. /api/v2/hosts/?id=302 (if host with ID 302 in AWX exists) returns properties for that host.

It would appear that since the ansible_facts is just a reference to additional page that the API is not able to query it.

**Comment by chrismeyersfsu** [comment]
`GET to /api/v2/hosts/?ansible_facts.ansible_distribution_version=18.04` should be `ansible_facts__ansible_distribution_version=18.04` see these examples https://docs.ansible.com/ansible-tower/latest/html/userguide/inventories.html#smart-host-filter

**Comment by ivantomica** [comment]
Thank you @chrismeyersfsu! I totally missed that part of docs. It helps a lot.

Unfortunately, there is still some sort of issue or lack of documentation in the UI part of the AWX. 


When I create "dummy" smart inventory with let's say "Inventory ID: 1", it sources all the hosts. and then I change that inventory via API to match host_filter to as you've noted. After that list of hosts is updated to only contain Ubuntu 18.04 hosts.

When I try to configure smart inventory via UI and try to set 

```
ansible_facts__ansible_distribution_version="18.04"
```
I get the following error in the UI:

```
GET /api/v2/hosts/ 400

No related model for field ansible_distribution_version.
```

In addition to that following errors get reported in awx-web container logs:

```
2021-09-06 14:54:55,767 WARNING  [e43c7e3f90f146aa9eb069c7bddaa749] awx.api.generics status 400 received by user ivantomica attempting to access /api/v2/hosts/ from xxx.xxx.xxx.xxx
2021-09-06 14:54:55,790 DEBUG    [e43c7e3f90f146aa9eb069c7bddaa749] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/hosts/?ansible_facts__ansible_distribution_version=14.04&inventory__organization=1&order_by=name&page=1&page_size=5'>, response_time: 0.156s
2021-09-06 14:54:55,795 WARNING  [e43c7e3f90f146aa9eb069c7bddaa749] django.request Bad Request: /api/v2/hosts/
2021-09-06 14:54:55,795 WARNING  [e43c7e3f90f146aa9eb069c7bddaa749] django.request Bad Request: /api/v2/hosts/
```

It would appear that it sends the request to the wrong URL, while in fact it should be 

```
/api/v2/hosts/?host_filter=ansible_facts__ansible_distribution_version="14.04"&inventory__organization=1&order_by=name&page=1&page_size=5
```

in my particular case.

While when I configure it manually via API as follows (update config in place with PUT/PATCH):

```json
{
    "name": "Ubuntu 18.04 hosts",
    "description": "",
    "organization": 1,
    "kind": "smart",
    "host_filter": "ansible_facts__ansible_distribution_version=\"18.04\"",
    "variables": "---"
}
```

It all works as expected:
```
"total_hosts": 46,
```

It is worth noting that when I set it via UI, and ignore the error receiving from search, after the save, host list is also populated properly. So it makes whole search process "hit and miss" and I'm kinda blind configuring it. For example, 18.04 would need to be quoted due to "." in the value, otherwise no results would match the filter.

**Comment by sebw** [comment]
I'm dealing with the same kind of UI problem. 

I haven't been able to figure out how to create a smart inventory filtering on local/custom facts using the web UI.

I can create a working smart inventory using the API just fine:

![image](https://user-images.githubusercontent.com/2285094/134166786-a4ca3e4f-d053-45c4-95d6-6b81301e6982.png)

If trying to edit the newly created smart inventory I'm getting errors:

![image](https://user-images.githubusercontent.com/2285094/134166901-131851c4-383b-4690-bceb-6de370f4abbc.png)

**Comment by chrismeyersfsu** [comment]
![image](https://user-images.githubusercontent.com/722880/134369370-a86f316b-5b08-4ef0-a951-403a5128ea23.png)

I agree, there is an issue in the UI, preventing you from querying `ansible_facts`. The two fields that appear in the drop down are not even meaningful for `ansible_facts`. Instead, I expect to NOT have to select anything from the `name__icontains` or `id` dropdown. I should just be able to type free-form into the last box i.e. `ansible_distribution_version="14.04"`

**Comment by nixocio** [comment]
Related to: https://github.com/ansible/awx/issues/5513

**Comment by nixocio** [comment]
Also: https://github.com/ansible/awx/issues/7850 and https://github.com/ansible/awx/issues/5513

**Comment by akus062381** [comment]
@nixocio I just wanted to check in and see what your plan is for this issue? I may need to meet with you to get a bit more context.

**Comment by nixocio** [comment]
Acceptance Criteria:

* User should be able to type a query - text input, and use ansible_facts
* Compound expressions would not be addressed by this issue, such as:
 ```
api/v2/hosts/?host_filter=(name=localhost or name=database) and (groups__name=east or groups__name="west coast") and ansible_facts__an
```
* Advanced Search remains the same for other keys different of ansible_facts

**Comment by ffirg** [comment]
related issue https://github.com/ansible/tower/issues/5279 hopefully fixed with this change as well.
