### ISSUE TITLE
Error message "/var/run/redis/redis.sock" no such file or directory

### ISSUE THREAD

**Issue by crystonesc** [ansible/awx#11024]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

I follow the doc in github to build the dev enviroment(AWX 17.1.0),when i run the "make docker compose" ,i got the error message "/var/run/redis/redis.sock no such file or directory",i found that the redis is not up because the docker-compose.yml is not correctly. finally  i add the "entrypoint: ["redis-server"]" in docker-compose.yml and the "make docker compose" run correctly

### AWX version

17.1.0

### Installation method

docker on linux

### Modifications

no

### Ansible version

4.8.5-44

### Operating system

centos 7

### Web browser

Firefox, Chrome, Safari, Edge

### Steps to reproduce

just follow the doc in version 17.1.0 (https://github.com/ansible/awx/blob/17.1.0/CONTRIBUTING.md)

### Expected results

Running awx-devel container normally

### Actual results

got the error message "/var/run/redis/redis.sock" no such file or directory

**Comment by shanemcd** [comment]
Given the age of this issue and lack of activity here I'm going to assume this is not a widespread problem and/or has been fixed.
