### ISSUE TITLE
Reopen issue- pluralization in translation- Schedules

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#11020]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Relates to https://github.com/ansible/awx/pull/10950

Jenkins run revealed a bug: (see the section "every minute for {0} times")
![image](https://user-images.githubusercontent.com/63685497/132047948-74d1d0a0-b444-4ee7-bff0-7a1a6e9eaed4.png)

### AWX version

4.0

### Installation method

docker for mac

### Modifications

no

### Steps to reproduce

run production environment on ec2 instance.
create template, and within it, create a schedule.
create the schedule to run every minute for 5 times.

### Expected results

UI would show "Every minute for 5 times"

### Actual results

UI shows "Every minute for {0} times"

**Comment by AlexSCorey** [comment]
Looks like this change might have gotten lost in the mix of all of the changes to `.po` files recently. https://github.com/ansible/awx/commit/40e5b70495e3e606a95f326b881ce50c3c2686d3#diff-18ed77e3cacc23d9ca94222c8dbf132bd3284bd1c516fa4ba71be709751bbcdeL2882

**Comment by AlexSCorey** [comment]
Looks like this has been resolved.  https://github.com/ansible/awx/blob/devel/awx/ui/src/locales/en/messages.po#L2981
![Screen Shot 2021-09-13 at 10 58 29 AM](https://user-images.githubusercontent.com/39280967/133107438-3184738a-89a4-43ed-b096-01f0cd634b3a.png)

**Comment by akus062381** [comment]
I have had these tests skipped. I will unskip them and trigger a Jenkins job run- will let you know the outcome

**Comment by akus062381** [comment]
fixed
