### ISSUE TITLE
Add setting so that auto-discovered nodes can be enabled by default

### ISSUE THREAD

**Issue by jladdjr** [ansible/awx#11031]

**Comment by AlanCoding** [comment]
Should this be in needs_test? I don't think this has been started on?

**Comment by jladdjr** [comment]
@AlanCoding fixed, good catch

**Comment by AlanCoding** [comment]
We also have https://github.com/ansible/awx/issues/10852

**Comment by jladdjr** [comment]
Sounds like this is a dup, closing
