### ISSUE TITLE
community.general module not recognized by awx (awx-ee) 

### ISSUE THREAD

**Issue by AdityaVishwekar** [ansible/awx#11045]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - awx-ee

##### SUMMARY

ERROR! couldn't resolve module/action 'mail'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/runner/project/ansible/vm_peer_review/peer_review.yml': line 315, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

community.general is installed in awx-ee container. 

bash-4.4$ ansible-galaxy collection verify community.general
Downloading https://galaxy.ansible.com/download/community-general-3.6.0.tar.gz to /home/runner/.ansible/tmp/ansible-local-4690igbvz7n6/tmp7bznnwns/community-general-3.6.0-afug7ata
Verifying 'community.general:3.6.0'.
Installed collection found at '/home/runner/.ansible/collections/ansible_collections/community/general'
MANIFEST.json hash: 282efc1fb10750cbc81806bd267129a6ad1e75a2c4a9ee81b9291d302e32738b
Successfully verified that checksums for 'community.general:3.6.0' match the remote collection.

##### ENVIRONMENT
* AWX version: 19.3.0
* AWX install method: operator,
* AWX deployment target: kubernetes
* Operating System: ubuntu (Linux astof-k8s01d 5.4.0-81-generic 91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux)
* Web Browse: Chrome

##### STEPS TO REPRODUCE

1. kubectl exec -it awx-7948bf7847-9czz7 -c awx-ee -- /bin/bash
2. ansible-galaxy collection install community.general -p /home/runner/.ansible/collections
3. Playbook task giving error - 
- name: Send email using email_template
   mail:
      host: mailrelay.dimension.com
      port: 25
      to: "{{ email_to }}"
      from: Ansible@dimension.com
      subject: "Peer review for: {{groups.final_hosts_group|join(',')}}"
      subtype: "{{ email_type }}"
      body: "{{ lookup('template', '{{ email_template }}') }}"
    delegate_to: localhost
    run_once: True
    ignore_errors: True

##### EXPECTED RESULTS

No errors are generated and ansible modules are recognized by AWX

##### ACTUAL RESULTS

redirecting (type: modules) ansible.builtin.mail to community.general.mail

**ERROR! couldn't resolve module/action 'mail'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/runner/project/ansible/vm_peer_review/peer_review.yml': line 315, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:
  - name: Send email using email_template
    ^ here**

##### ADDITIONAL INFORMATION

bash-4.4$ ansible --version
ansible [core 2.11.4.post0] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True

bash-4.4$ ansible-galaxy collection list                                                          

 /usr/share/ansible/collections/ansible_collections
Collection              Version
----------------------- -------
amazon.aws              1.5.0  
ansible.posix           1.3.0  
ansible.windows         1.7.2  
awx.awx                 19.2.2 
azure.azcollection      1.8.0  
community.vmware        1.13.0 
google.cloud            1.0.2  
kubernetes.core         2.1.1  
openstack.cloud         1.5.0  
ovirt.ovirt             1.6.0  
redhatinsights.insights 1.0.5  
theforeman.foreman      2.1.2  

 /home/runner/.ansible/collections/ansible_collections
Collection             Version
---------------------- -------
community.general      3.6.0  
netbox.netbox          3.1.1  
networktocode.nautobot 2.0.1

**Comment by chrismeyersfsu** [comment]
Try the fully qualified collection name i.e. `community.general.mail` instead of just `mail`. You also might get more replies by asking this question on the mailing list.
