### ISSUE TITLE
Chrome browser loosing focus in AWX surveys

### ISSUE THREAD

**Issue by nasjomach** [ansible/awx#11047]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

When using chrome browser with AWX, focus is lost on AWX surveys if you take too much time to input the data.
It seems that chrome is refreshing more than just the required elements in the page on auto-refresh cycles.

This does not happen with Firefox.

### AWX version

15.0.1

### Installation method

docker on linux

### Modifications

no

### Ansible version

N/A

### Operating system

N/A

### Web browser

Chrome

### Steps to reproduce

Launch a survey
Wait for some time

### Expected results

Survey frame disappears and inputted data are lost.

### Actual results

Idem

**Comment by nasjomach** [comment]
Chrome version: Version 92.0.4515.159

**Comment by AlexSCorey** [comment]
@nasjomach do you know if this is happening only on Chrome?

**Comment by nasjomach** [comment]
Yes for me only in Chrome, Firefox is fine.

**Comment by nixocio** [comment]
@nasjomach thanks for filing this issue. AWX surveys have been updated. Can you upgrade to latest version?

**Comment by mabashian** [comment]
Judging by the comments here this looks like it can be closed
