### ISSUE TITLE
Make Filtering More Obvious In The Jobs View

### ISSUE THREAD

**Issue by opticyclic** [ansible/awx#11041]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The Jobs view allows you to search for jobs by template name.
However, it _apparently_ doesn't let you filter it by anything else.
The options are there using a search syntax listed under the `KEY` button, but it isn't obvious that is where it is and it isn't even obvious that it is a button.

When you search with JIRA it gives you extra drop downs to select what you are filtering on.
When you go to the Advanced Filtering you click on the search box and it drops down with syntax you can use. There is even a help icon on the far right that you can click which takes you to the syntax guide.

A similar design is in YouTrack where the syntax options appear as you type highlighting to you that there is an advanced syntax to use.

An alternative way is to do it like online shops do with an initial search then filtering on the side by category.

Another way to do it that wouldn't require much change would be to put the `EXAMPLES:` from the `KEY` next to the button to indicate that there is extra syntax and hint that there is a button to click with more info.

**NB:** To give some perspective on how obscure it is, a small team I am working with has been using Tower for 2 years and only used the search and would moan about "how annoying it is to find information". I have been with the team for 6 months and only as I was writing this request did I notice that the `KEY` actually gave extra information to search with.

**Comment by AlexSCorey** [comment]
@opticyclic  In the latest of AWX there is an advanced search function that provides additional guidance for more complex searches.  What version of AWX are you using?

**Comment by opticyclic** [comment]
3.5.2

**Comment by AlexSCorey** [comment]
Upgrading to 4.0 will resolve this issue.

**Comment by nixocio** [comment]
@opticyclic, thanks for filing this issue, as @AlexSCorey pointed out the search was completely re-worked on the newer versions.
