### ISSUE TITLE
Make My View Customisable

### ISSUE THREAD

**Issue by opticyclic** [ansible/awx#11040]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
My "My View" shows 175 job templates which I probably have access to via groups.

I can search for the templates I am interested in because they are prefixed with the same name.
However, as soon as I leave the page and come back, all the templates are there.

Similarly I can see 4 jobs which are the ones I launched but I can't see the jobs that I am interested in, which come from a specific template.

To make this truly my view it should be customisable to show and save the information I am interested in as a view.

**Comment by mabashian** [comment]
My view was removed some time ago
