### ISSUE TITLE
Show The Change History For A Project

### ISSUE THREAD

**Issue by opticyclic** [ansible/awx#11049]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
This morning my job failed because someone changed the branch in the project.
However, I have no idea who changed it or when because there is no change history for the project.

Add a button in the project view called `HISTORY`
Add a list with Time/User/Change columns.
The "Change" column should either be expandable like the Job list or it should popup like log snippet view and show the change that has been made.

**Comment by AlanCoding** [comment]
Have you checked the activity stream for the project? Click the time icon with the circle arrow:

![Screenshot from 2021-09-08 11-08-31](https://user-images.githubusercontent.com/1385596/132535706-9424726b-dc74-4492-bd65-efcfdbb2184e.png)

Looks like this gives history for _all_ projects, which isn't ideal, but still works

![Screenshot from 2021-09-08 11-08-43](https://user-images.githubusercontent.com/1385596/132535719-0ba9e633-fca1-42c9-b31e-042be1caf6af.png)

Looks like the user "alan" made it fail by changing the branch

![Screenshot from 2021-09-08 11-08-49](https://user-images.githubusercontent.com/1385596/132535733-37c9e885-2ee3-4db6-abb9-ea8009f57651.png)

**Comment by opticyclic** [comment]
You are right. That shows what I was expecting.
It looks like I am on an older release where it isn't so obvious.
Sorry about that.
