### ISSUE TITLE
Save The URL On Session Timeout

### ISSUE THREAD

**Issue by opticyclic** [ansible/awx#11042]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
If the session times out and I log back in again from that page it takes me back to the home page and not the page I was on.
If I have multiple tabs open with various jobs I am looking at they all timeout and redirect back the home page.

It would be more useful to save the URL I was on before the session ended and then reload that page after I re-authenticate.

**Comment by AlexSCorey** [comment]
@opticyclic This issue is resolved in the latest version of AWX.  What version are you using?

**Comment by opticyclic** [comment]
3.5.2

**Comment by AlexSCorey** [comment]
I recommend that you upgrade to 4.0

**Comment by nixocio** [comment]
I just tested this on devel. It seems to be working as expected.
