### ISSUE TITLE
increase\change Session Timeout

### ISSUE THREAD

**Issue by TristisOris** [ansible/awx#11055]
##### ISSUE TYPE
Option to change\disable session timeout. It happens to often now.

##### SUMMARY
awx 19.3

**Comment by nixocio** [comment]
@TristisOris , you are able to change this value on `Idle Time Force Log Out`.

<img width="1486" alt="image" src="https://user-images.githubusercontent.com/9053044/132687107-df1a3863-2d74-40db-be77-3655ba5bfdc8.png">

**Comment by TristisOris** [comment]
oh thanks, missed it.
