### ISSUE TITLE
Workflow Node Info Button Displaying Error When Clicked

### ISSUE THREAD

**Issue by InnocentK** [ansible/awx#11061]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

A bug occurs after clicking the "Info" button on a workflow node (see gif in "Steps to reproduce")

### AWX version

devel

### Installation method

docker on linux

### Modifications

no

### Steps to reproduce

1. Go to templates and create a workflow node
2. Add a node
3. Click Info button on added node
4. Click "Details"
5. Bug occurs
![2021-09-09 12-21-25](https://user-images.githubusercontent.com/37008228/132724591-ba960f34-2fac-4a9d-a056-1f5c8fd9074e.gif)

### Expected results

Click on info and see a popup with information on the node

### Actual results

Error message displayed when info button is clicked

### Additional information

Found this bug while testing https://github.com/ansible/awx/issues/10628

**Comment by chris93111** [comment]
Hi same error with 19.3 

```
TypeError: Cannot read property 'toString' of null at WS (http://awx-demo/static/js/main.11ca6dfe.chunk.js:1:1169967) at Zo (http://awx-demo/static/js/2.11d97623.chunk.js:2:1358657) at Ba (http://awx-demo/static/js/2.11d97623.chunk.js:2:1367557) at Ss (http://awx-demo/static/js/2.11d97623.chunk.js:2:1406123) at vl (http://awx-demo/static/js/2.11d97623.chunk.js:2:1397614) at ml (http://awx-demo/static/js/2.11d97623.chunk.js:2:1397539) at sl (http://awx-demo/static/js/2.11d97623.chunk.js:2:1394548) at http://awx-demo/static/js/2.11d97623.chunk.js:2:1345919 at t.unstable_runWithPriority (http://awx-demo/static/js/2.11d97623.chunk.js:2:1421320) at qi (http://awx-demo/static/js/2.11d97623.chunk.js:2:1345628)
```

**Comment by InnocentK** [comment]
#11097 resolves this issue successfully
