### ISSUE TITLE
@rakh7 This fix will be in the next release of Ansible: 2.5.7 and 2.6.2.

### ISSUE THREAD

**Issue by JhwuGit** [ansible/awx#11067]
@rakh7 This fix will be in the next release of Ansible: 2.5.7 and 2.6.2.

_Originally posted by @samdoran in https://github.com/ansible/ansible/issues/41717#issuecomment-405291773_

I got the same error: 25, 'Inappropriate ioctl for device' with Ansible verison 2.9.14

**Comment by chrismeyersfsu** [comment]
Sounds like this is an Ansible issue. This is the AWX repo.
