### ISSUE TITLE
Offline control nodes get chosen to be control nodes resulting in job failing

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#11095]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Offline control nodes get chosen to be control nodes resulting in job failing

### AWX version

devel

### Installation method

docker on linux

### Modifications

no

### Operating system

Fedora 34

### Web browser

Chrome

### Steps to reproduce

* Have 2 hybrid nodes
* Kill / take offline 1 of the hybrid nodes, call this "offline hybrid", call the other node "online hybrid"
* Create an instance group with the "online hybrid"
* Create a JT & assign the instance group
* Launch the JT a bunch of times

### Expected results

* All jobs to succeed

### Actual results

* some jobs will fail

### Additional information

Controller will sometimes choose offline nodes as for `controller_node`. 

The "problem" code is https://github.com/ansible/awx/blob/devel/awx/main/models/ha.py#L154 It does not take into account the offline/online of the node, only the enabled/disabled attribute.

**Comment by AlanCoding** [comment]
I think everyone will agree that we can't reasonably do an integration test for this.

**Comment by Zokormazo** [comment]
Everything is working and we can't reasonably add more coverage for this, closing it
