### ISSUE TITLE
Template's branch override doesn't take effect

### ISSUE THREAD

**Issue by artm** [ansible/awx#11098]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

The project is set to allow branch override:
![image](https://user-images.githubusercontent.com/64227/134138020-75d4bdae-1c00-49ea-aded-6de3e0f34c52.png)

![image](https://user-images.githubusercontent.com/64227/134136024-27841b81-9dc5-46f4-96c4-e0d70c8dc656.png)

The template is set to an alternative branch + allow branch override is on:
![image](https://user-images.githubusercontent.com/64227/134137906-2d2a76c1-2ca1-4b96-8f1d-342b05017c48.png)

The project sync job triggered by starting a job from the template syncs with HEAD instead of the branch setup by the template:
![image](https://user-images.githubusercontent.com/64227/134136771-7ad56343-44fb-4b4a-a316-afc8f685f14d.png)

The actual job uses the code from HEAD.

### AWX version

1.9.3

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.11.3.post0 from awx-ee:0.6.0

### Operating system

-

### Web browser

Chrome

### Steps to reproduce

See summary

### Expected results

Project sync uses the branch requested by the template / user.

### Actual results

Project sync always uses the default version (HEAD)

### Additional information

When supplying a non-existent branch name on job launch the project sync succeeds with default version (HEAD), but the job from the template fails with:

```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1316, in run
    self.pre_run_hook(self.instance, private_data_dir)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1802, in pre_run_hook
    sync_task.run(local_project_sync.id)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 740, in _wrapped
    return f(self, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1453, in run
    raise AwxTaskError.TaskError(self.instance, rc)
Exception: project_update 8437 (failed) encountered an error (rc=None), please see task stdout for details.
```

**Comment by artm** [comment]
I was mistaken: the job created by the template uses the code from the overridden branch, our problem lies elsewhere.

**Comment by craph** [comment]
Hello, 

I have the same issue, in job I can't see the checkout of my branch.
Is it normal ?
