### ISSUE TITLE
ERROR! couldn't resolve module/action 'community.kubernetes.k8s'

### ISSUE THREAD

**Issue by eselvam** [ansible/awx#11108]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

When deploying k8 resources using awx 19.x we got below.

ERROR! couldn't resolve module/action 'community.kubernetes.k8s'

### AWX version

19.3

### Installation method

kubernetes

### Modifications

no

### Operating system

redhat

### Steps to reproduce

- name: Apply metrics-server manifest to the cluster.
  community.kubernetes.k8s:
    state: present
    src: ~/metrics-server.yaml

then create a job and run it and you get the error:  ERROR! couldn't resolve module/action 'community.kubernetes.k8s'

### Expected results

It should create a resources in k8

### Actual results

ERROR! couldn't resolve module/action 'community.kubernetes.k8s'

**Comment by acelinkio** [comment]
Should be using the kubernetes.core collection as community.kubernetes.k8s is now eol.  https://galaxy.ansible.com/kubernetes/core

Also you need to install the collection:
`ansible-galaxy collection install kubernetes.core` if from your workstation

otherwise you need to add a `collection/requirements.yaml` to your project for it to download in awx
example:  https://gitlab.com/acelinkit/monopipeline/-/blob/main/collections/requirements.yaml

**Comment by eselvam** [comment]
Thanks!
I am able to install the collection in AWX project using git collections/requirements.yml file.
The Ansible document helps me to understand how the collection works and now all looks good.
    On Saturday, September 25, 2021, 07:57:52 AM GMT+5:30, acelinkit ***@***.***> wrote:  
 
 


Should be using the kubernetes.core collection as community.kubernetes.k8s is now eol. https://galaxy.ansible.com/kubernetes/core

Also you need to install the collection:
ansible-galaxy collection install kubernetes.core if from your workstation

otherwise you need to add a collection/requirements.yaml to your project for it to download in awx
example: https://gitlab.com/acelinkit/monopipeline/-/blob/main/collections/requirements.yaml

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
