### ISSUE TITLE
Update Patternfly

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#11105]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Last time we updated Patternfly was about 4 months ago.

**Comment by nixocio** [comment]
Reopen this issue. Since upgrade is blocked until https://github.com/patternfly/patternfly-react/issues/6421 is sorted out.

**Comment by nixocio** [comment]
Also: https://github.com/ansible/awx/pull/11218
