### ISSUE TITLE
code input fields are showing refresh and styling issues

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#1110]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
This was most likely introduced by recent dependency bumps on devel (jquery-ui, ui-router, etc.). Code input fields on all forms throughout the app are no longer showing the expected syntax highlighting. Many fields (particularly those on the configuration view) are no longer showing their placeholder values or actual values (if available) from the backend on initial page load.

##### STEPS TO REPRODUCE
- navigate to `/#/inventories/inventory/add` (*note: the inventories view is used as an example - this bug impacts most/all code input fields throughout awx*)

##### EXPECTED RESULTS
<img width="703" alt="screen shot 2018-01-31 at 12 39 27 pm" src="https://user-images.githubusercontent.com/9753817/35696279-0e1cef22-0755-11e8-8fe0-9e439b313870.png">
---
<img width="710" alt="screen shot 2018-01-31 at 12 39 06 pm" src="https://user-images.githubusercontent.com/9753817/35696559-d32316ac-0755-11e8-9dde-5fa98d0e49dc.png">

##### ACTUAL RESULTS
<img width="702" alt="screen shot 2018-01-31 at 12 40 35 pm" src="https://user-images.githubusercontent.com/9753817/35696381-51d14f74-0755-11e8-970c-3d923f78159a.png">
---
<img width="719" alt="screen shot 2018-01-31 at 12 40 26 pm" src="https://user-images.githubusercontent.com/9753817/35696312-24f486ce-0755-11e8-8e62-fcac7df09e1e.png">

**Comment by jaredevantabor** [comment]
this is fixed in devel now
