### ISSUE TITLE
Expose the 'ALLOW_JINJA_IN_EXTRA_VARS' option in the GUI

### ISSUE THREAD

**Issue by mrmibrown** [ansible/awx#11103]
Expose the 'ALLOW_JINJA_IN_EXTRA_VARS' option in the GUI so that this option is available outside the the current API location.

##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add a GUI option for the 'ALLOW_JINJA_IN_EXTRA_VARS' variable in the job settings.

**Comment by AlexSCorey** [comment]
@mabashian  and @gamuniz spoke about this some time ago and decided not to surface these values to the UI.  @gamuniz is that still your suggestion?

**Comment by gamuniz** [comment]
If the setting is only read/write for system administrator, it would be good rather than having to send the same request to the api. Though this setting is expected to be set to never at some point in the future.
