### ISSUE TITLE
Execution node jobs canceled (via receptor) while in progress show as running forever

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#11110]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Jobs running on execution nodes appear to respond badly to disruption while in progress.

My first investigation of this was to cancel the job via `receptorctl work cancel <uint_id>` on the control node for the job (different that the execution_node) while the job was running.

### AWX version

19.2.2

### Installation method

docker on linux

### Modifications

no

### Ansible version

devel

### Operating system

N/A

### Web browser

Chrome

### Steps to reproduce

Launch a job targeting `receptor-1` node in the execution environment (verified by `execution_node`).

Make that job run a [sleep task](https://github.com/ansible/test-playbooks/blob/master/sleep.yml) to pause for 30 seconds.

Quickly after the job starts, shell into the control node (probably `awx_1`) and run `receptorctl work cancel <work_id>` where you can get the work id from the API.

Wait for >30 seconds after the job started and check on its details.

### Expected results

After 30 seconds, then regardless of whether the cancel command was successful or not, the job should not be running. Shelling into `receptor-1`, it's easy to confirm that, of course, it's not running.

### Actual results

Job stays in status of "running" indefinitely.

### Additional information

I see server logs like this:

```
tools_awx_1     | awx-receptor stdout | ERROR2021/09/22 14:02:38 Error updating status file /tmp/receptor/awx_1/jYpxwJ08/status: open /tmp/receptor/awx_1/jYpxwJ08/status.lock: no such file or directory.
```

This looks like it was caused by my reproduction steps. It could also be related to the AWX task that clears finished work units.

**Comment by jladdjr** [comment]
I can confirm that this behavior is still present. I took my test a step forward and killed the receptor process on the control node and noticed that the job was immediately aborted and marked with state `error` and gave the following traceback:

```
Traceback (most recent call last):
  File \"/awx_devel/awx/main/tasks.py\", line 3029, in run
    res = self._run_internal(receptor_ctl)
  File \"/awx_devel/awx/main/tasks.py\", line 3087, in _run_internal
    unit_status = receptor_ctl.simple_command(f'work status {self.unit_id}')
  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/receptorctl/socket_interface.py\", line 70, in simple_command
    self.connect()
  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/receptorctl/socket_interface.py\", line 90, in connect
    self.handshake()
  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/receptorctl/socket_interface.py\", line 43, in handshake
    m = re.compile(\"Receptor Control, node (.+)\").fullmatch(self.readstr())
  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/receptorctl/socket_interface.py\", line 36, in readstr
    return self._sockfile.readline().decode().strip()
  File \"/usr/lib64/python3.8/socket.py\", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File \"/awx_devel/awx/main/tasks.py\", line 1499, in run
    res = receptor_job.run()
  File \"/awx_devel/awx/main/tasks.py\", line 3034, in run
    receptor_ctl.simple_command(f\"work release {self.unit_id}\")
  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/receptorctl/socket_interface.py\", line 71, in simple_command
    self.writestr(f\"{command}\
\")
  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/receptorctl/socket_interface.py\", line 40, in writestr
    self._sockfile.flush()
  File \"/usr/lib64/python3.8/socket.py\", line 687, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe
```

So it looks like the more likely case (receptor process dies), is handled almost immediately by awx, although it looks like there is room for us to catch this scenario more gracefully.

The original scenario described is still possible with awx, however it requires a user knowingly issuing a receptor command. This specific scenario (properly cleaning up a receptor task w/out awx's knowledge) seems unlikely. I actually can't think of how this would accidentally happen without a user intentionally invoking this scenario.

**Comment by jladdjr** [comment]
In meeting with @ffirg sounded like we do not consider this a pressing issue at the time. @ffirg can you confirm that this work can be defered?

**Comment by ffirg** [comment]
I think it’s still something we should close off for completeness but a user should not be doing this (or need to) outside of the controller. You can continue to work on it but as the lowest priority case of those you’ve outlined.  If something else comes up more pressing then it can be deferred.

**Comment by jladdjr** [comment]
Have been looking at https://github.com/ansible/tower/pull/5351 with @beeankha, turning my attention back to this issue.

**Comment by AlanCoding** [comment]
@jladdjr we added a test case `test_receptor_removes_container_on_cancel`. This is what I wrote when originally discovering this issue. Latest information we have on that is that it's passing. This launches a job with a sleep of 600 seconds, and then cancels, and then confirms that the container is not running.

If you're focused on this new variant:

> I took my test a step forward and killed the receptor process on the control node and noticed that the job was immediately aborted and marked with state `error`

Then it might be good to break it off into a new issue and triage it separately. That sounds pretty valid, but I have not seen any testing content for it, so that will involve some net-new material (aside from prior manual testing you've done).

**Comment by jladdjr** [comment]
@AlanCoding this is the behavior I saw being discussed in this ticket:

> My first investigation of this was to cancel the job via receptorctl work cancel <uint_id> on the control node for the job (different that the execution_node) while the job was running.

.. and which I confirmed I could [still reproduce](https://github.com/ansible/awx/issues/11110#issuecomment-938421778). That update does talk about 'going a step further..' but ignore that for the moment. Calling `receptorctl work cancel` will still result in the job running indefinitely.

You mentioned [test_receptor_removes_container_on_cancel](https://github.com/ansible/tower-qa/blob/407d76c4091978cad2f7c7c779d070db129d8eb6/tests/api/cluster/test_execution_nodes.py#L286) -- that asserts that the container is not running, but does not assert that the job eventually enters an inactive state (failed or error). If we added that assertion to that test, we'd actually have a great reproducer / test we can use for verification.

cc @thenets (re: current state of ticket, some ideas on how we might have an easy way to test this scenario by adding assertion to existing test)

**Comment by AlanCoding** [comment]
When you said "killed the receptor process on the control node", I took it to mean that you killed the receptor service running on the control node. Sounds like I wasn't clear on that.

> You mentioned test_receptor_removes_container_on_cancel -- that asserts that the container is not running, but does not assert that the job eventually enters an inactive state (failed or error). If we added that assertion to that test, we'd actually have a great reproducer / test we can use for verification.

Agree, simple to add, we should do that. If the job is stuck running, then I don't want the test to be enabled in the first place.

**Comment by jladdjr** [comment]
> When you said "killed the receptor process on the control node", I took it to mean that you killed the receptor service running on the control node. Sounds like I wasn't clear on that.

oh, no, meant to say called `work cancel` on the receptor work unit. Sorry, my wording there wasn't right.

**Comment by AlanCoding** [comment]
We had problems with the patch for this reaping successful jobs, so the change has been backed out for now. We need to think more about how we avoid reaping functioning jobs, and we need to re-triage this issue.

**Comment by jladdjr** [comment]
I had a chance to catch up with @AlanCoding about what we saw here. Copying down some notes from our discussion:

**Why the original PR didn't work**

The PR we merged to fix this issue ([here](https://github.com/ansible/tower/pull/5354/files)) worked as follows:
* Periodic task `awx_receptor_workunit_reaper` looks at running jobs and tries to find their associated receptor work unit
* If the work unit cannot be found, then the job's [cancel flag](https://github.com/ansible/tower/pull/5354/files#diff-6fb7bd98930ec6a05c1ae9296b41b63921e1813dcee53895f16769f910917c38R675) is set
* The running job has a [cancel_watcher](https://github.com/ansible/awx/blob/69ae7318981d1bbf9525127bfe96f8fa53e5fddd/awx/main/tasks.py#L3207) that will stop the job if the cancel flag is set.

@AlanCoding noted that there are some jobs (inventory updates in particular) where the receptor task will finish and get [released](https://github.com/ansible/awx/blob/69ae7318981d1bbf9525127bfe96f8fa53e5fddd/awx/main/tasks.py#L3064), but then we will still have some [post-processing tasks](https://github.com/ansible/awx/blob/69ae7318981d1bbf9525127bfe96f8fa53e5fddd/awx/main/tasks.py#L1206-L1212) that we still need to run through before the job is considered finished. If the post-processing tasks take a non-trivial amount of time, then the reaper will look at the job, see that it has no receptor work unit, and reap it.

**What we could do instead**

@AlanCoding and I discussed a few ideas:

* :x:&nbsp;&nbsp;Add new task state? We have too much logic written around task states to do this.
* :x:&nbsp;&nbsp;Add a new task sub-state? Seems like this would add more complexity than it's worth.
* :thinking:&nbsp;&nbsp;Make the reaper responsible for cleaning up the work unit. Only clean up work units when the job is finished.

**When should we do this?**

Whereas:
* This scenario is triggered by an awx admin directly calling `receptorctl work release`
* and the user has an easy means of remediating (notices job has been running for a while, hits cancel)

Recommend:
* This work is not pressing and can be deferred.

**Comment by jladdjr** [comment]
@ffirg - let us know if you would have any concerns with deferring this work ^

**Comment by jladdjr** [comment]
Checked back in with @ffirg re: deferring work. Said he would have a chance to look at this tomorrow.

**Comment by jladdjr** [comment]
Setting to medium priority given that:
* the user would need admin access and would need to _deliberately_ put awx into this state via a receptor command
* the steps to remediate are trivial (cancel a job the user notes has been running too long)

**Comment by ffirg** [comment]
I’m happy to defer given we shouldn’t expect a user to hit this. Let’s wrap it up into any future reaper work where we can optimise and clean up further.

**Comment by AlanCoding** [comment]
In linked tower-qa PR above, I find that the test is passing, jobs flip to a canceled status. Hope to close this soon.

**Comment by AlanCoding** [comment]
Test is unskipped, no attention for a long time, closing.
