### ISSUE TITLE
Validate/Enforce Runner Version in Execution Nodes

### ISSUE THREAD

**Issue by beeankha** [ansible/awx#11114]
Due to the work that was done to fix https://github.com/ansible/awx/issues/10944, we will need to make sure that a compatible version of Runner is installed on execution nodes.

**Comment by rooftopcellist** [comment]
# Meeting notes (Sept 23)

## Where does ansible-runner get installed in AAP 2.1 2.0-2.1+?

* Alongside receptor on the execution node
* Inside the Execution Environment (EE)

## Problem
We can potentially end up with different versions of ansible-runner in those 2 places which could be incompatible.

## Solution
We add validation before using that EE that it will work with the runner version on the execution node.
We also decided we want to pin ansible-runner to the major version in the places where it is consumed
* pin version in awx/requirements.in
* pin in tower-packaging group_vars to match
* pin major version in Dockerfile for the EE's

**Runner Release Policy**: no breaking changes on minor or patch releases for Ansible-runner

We also talked about releasing ansible-runner 3.0.0 - before we do this, we need to talk to all stakeholders before making this decision.

**Comment by rooftopcellist** [comment]
We should also ensure that execution nodes and controller nodes have compatible versions of ansible-runner.
