### ISSUE TITLE
Job fails to find the playbook when running a job on an execution_node

### ISSUE THREAD

**Issue by tchellomello** [ansible/awx#11116]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

**cc**: @chrismeyersfsu++

We hit this problem while working on the PR https://github.com/ansible/awx/pull/11093. Thankks @chrismeyersfsu++ for all the assistance analyzing this issue

When submitting a job to an `execution_node`, the playbook will fail if the `controller_node` which dispatched the job does not have yet a `project` cached at `/var/lib/awx/projects` directory. 

The error will be:

```
Using /etc/ansible/ansible.cfg as config file
ERROR! the playbook: hello_world.yml could not be found
```

### AWX version

devel

### Installation method

docker on linux

### Modifications

no

### Ansible version

latest

### Operating system

rhel8

### Steps to reproduce

1. Deploy `devel` with 3 `automationcontroller` with `node_type=control`
2. Deploy 3 `execution_nodes` with `node_type=execution`
3. Create a project from https://github.com/ansible/ansible-tower-samples. Sync the project by hitting manually the button so sync so we can capture its git revision. Make sure to enable the `Delete` option on this repo as well
4. Create an instance group with only the `execution_nodes` members
5. Create a job template that is assigned for the instance group created above (ensure there are no `automationcontroller` members)

Now, at this point, if you look in all 3 `automationcontroller` nodes at `/var/lib/awx/projects` you will see that one 1 node has the git repo cached (which is expected). If you trigger a job now and the job is dispatched by the same controller (which has the cache) the playbook should work as expected, however, if the job is dispatched by any other `automationcontroller` node it will fail. 

Since the code path is different when manually syncing the job and forcing a `project_update` when needed, to be better reproduce this remove the `/var/lib/awx/projects/*` contents from all `automationcontroller` nodes and re-run the job template (not the project sync). 

### Expected results

Should work as expected

### Actual results

The project does not updated on the given controller because the task `execution_node` is pointing to the remote `execution_node` instead of pointing to self (for project updates)
https://github.com/ansible/awx/blob/devel/awx/main/tasks.py#L1866-L1868
```python
         if sync_needs:
             pu_ig = job.instance_group
             pu_en = Instance.objects.me().hostname   <--- this seems to fix the issue
 
             sync_metafields = dict(
                 launch_type="sync",
                 job_type='run',
                 job_tags=','.join(sync_needs),
                 status='running',
                 instance_group=pu_ig,
                 execution_node=pu_en,
                 celery_task_id=job.celery_task_id,
             )
```

**Comment by AlanCoding** [comment]
```python
pu_en = Instance.objects.me().hostname   <--- this seems to fix the issue
```

_approved_ :heavy_check_mark:

**Comment by thenets** [comment]
Should add the `needs_test` later.

**Comment by tchellomello** [comment]
PR# https://github.com/ansible/awx/pull/11118

**Comment by AlanCoding** [comment]
Looks like the related fixes were merged, moving to needs_test

**Comment by Zokormazo** [comment]
We need to verify this on a scenario where controlplane does not have hybrid nodes and those are failing on receptor right now. Blocked to verify this fix

**Comment by Zokormazo** [comment]
Verified with @tchellomello 's instructions.

After 5. I had a cache on controlplane02 node. Launched the job and it ended on controlplane3, project came properly here and did not hit the not found issue
