### ISSUE TITLE
Add Ability to find unified job templates by ID and Org

### ISSUE THREAD

**Issue by sean-m-sullivan** [ansible/awx#11124]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add ability to 
A. use workflow_job_template_node by giving a unified job template ID
B. Use a lookup organization to find a unified job template, right now if a project/job_template/inventory has the same name in multiple orgs, this is unusable, and because of A, cannot be fixed by the lookup plugin.

**Comment by chrismeyersfsu** [comment]
@beeankha @sean-m-sullivan can this card be closed since #11135 merged?

**Comment by sean-m-sullivan** [comment]
I think its read for needs test, as issues aren't closed till after that is signed off on.

**Comment by sean-m-sullivan** [comment]
Checked this, it is in the latest ansible.controller, so closing the issue.
