### ISSUE TITLE
Survey integer field minimum of 0 raises a validation error incorrectly

### ISSUE THREAD

**Issue by surfer190** [ansible/awx#11137]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

I create a survey field with the following info:

* Answer variable name: vm_count
* Anwer type: Integer
* Minimum: 0
* Maximum: 100
* Default answer: 

When launching the playbook with the `vm_count` field set to `0`...a vlaidation error is raised but no reason is shown on the survey step.
On the preview page the error is: `Some of the previous step(s) have errors`

<img width="1091" alt="Screen Shot 2021-09-27 at 08 36 49" src="https://user-images.githubusercontent.com/3285222/134858041-8b741952-ed28-4ae2-ae17-f1d4167d72e9.png">

<img width="1109" alt="Screen Shot 2021-09-27 at 08 38 51" src="https://user-images.githubusercontent.com/3285222/134858087-f2375ee3-6d04-491f-9926-310e1006e325.png">

<img width="1105" alt="Screen Shot 2021-09-27 at 08 38 58" src="https://user-images.githubusercontent.com/3285222/134858117-70b38d6d-8ecd-4c39-85f1-f3b37d834691.png">

### AWX version

19.2.2

### Installation method

kubernetes

### Modifications

no

### Web browser

Firefox

### Steps to reproduce

1. Create a survey field as above
2. Enable the survey
3. Launch the playbook and enter `0` in the survey field

### Expected results

I expect the play to luanch with the `vm_count` field set as 0

### Actual results

The playbook has a validation error.
No message is shown on the survey screen - only a red exclamation mark that something has gone wrong.

**Comment by nixocio** [comment]
I verified the previous UI implementation and allows the value of `0` as valid value - for integers, on the survey.
