### ISSUE TITLE
JobTemplate API ignoring extra_vars passed (ask_variables_on_launch: true)

### ISSUE THREAD

**Issue by Haagy** [ansible/awx#11139]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

When I want to lauch a job template with API, extra_vars are not getting paased to job.

Job Config:
`curl --location   --user me:secret https://awx/api/v2/job_templates/152`
Output:
```
{
...
  ,"ask_variables_on_launch":true
...
}
```

Post to Job Template:
```
curl --request POST  \
  --location \
  --headers "Content-Type: application/json"  \
  --data '{"extra_vars": "{\"version\": \"trunk\", \"update_fact_set\": \"false\"}"}'    
  --user me:secret
https://awx/api/v2/job_templates/152/launch
```

### AWX version

17.1.0 and 19.3.0

### Installation method

docker on linux

### Modifications

no

### Ansible version

2.9

### Operating system

CentOS

### Steps to reproduce

```
curl --request POST  \
  --location \
  --headers "Content-Type: application/json"  \
  --data '{"extra_vars": "{\"version\": \"trunk\", \"update_fact_set\": \"false\"}"}'    
  --user me:secret
https://awx/api/v2/job_templates/152/launch
```

### Expected results

```
{
...
  "ignored_fields": {},
...
  "extra_vars": "{version: trunk, update_fact_set: false}",
...
}
```

### Actual results

```
{
...
  "ignored_fields": {},
...
  "extra_vars": "{}",
...
}
```

**Comment by shanemcd** [comment]
I'm unable to reproduce this on devel. Can you try through the UI, look in your browser's dev tools Network tab, and cross check against what youre doing with curl?

**Comment by Haagy** [comment]
The UI is doing the job correctly and I get those variables in my job. 
I could bypass this issue by using [jenkins ansible tower pluging](https://plugins.jenkins.io/ansible-tower/) and that works as well.

Maybe `curl` losing data when forwarding with `--location` my AWX instance is behind a nginx.
I'll have a look at nginx logs.

**Comment by Haagy** [comment]
I was digging some deeper into this issue but still cant get it work.
Here is all that AWX is producing on logs:
```
[pid: 92|app: 0|req: 29/91] 123.4.5.6 () {42 vars in 588 bytes} [Mon Nov 22 09:54:22 2021] POST /api/v2/job_templates/162/launch => generated 0 bytes in 30 msecs (HTTP/1.1 301) 6 headers in 225 bytes (1 switches on core 0)
123.4.5.6 - haagadm [22/Nov/2021:09:54:22 +0000] "POST /api/v2/job_templates/162/launch HTTP/1.1" 301 0 "-" "curl/7.61.1" "-"
... some django_auth_ldap output ...
2021-11-22 09:54:22,384 INFO     awx.api.authentication User haagadm performed a POST to /api/v2/job_templates/162/launch/ through the API
[pid: 92|app: 0|req: 30/92] 123.4.5.6 () {40 vars in 563 bytes} [Mon Nov 22 09:54:22 2021] POST /api/v2/job_templates/162/launch/ => generated 3140 bytes in 378 msecs (HTTP/1.1 201) 11 headers in 330 bytes (1 switches on core 0)
123.4.5.6 - haagadm [22/Nov/2021:09:54:22 +0000] "POST /api/v2/job_templates/162/launch/ HTTP/1.1" 201 3140 "-" "curl/7.61.1" "-"
```
The only thing I see here is that the initial request commes with `{42 vars in 588 bytes}`, gets forwarded but ends up with `{40 vars in 563 bytes}`.
Maybe the two missing vars are the `extra_vars`.
But how is this happening?
Any ideas @shanemcd?

**Comment by shanemcd** [comment]
> The UI is doing the job correctly and I get those variables in my job.

This makes me think that you are doing something wrong when using the API directly. If you need help troubleshooting or are looking for help using AWX, try our mailing list or IRC channel:

#ansible-awx on https://libera.chat/
https://groups.google.com/forum/#!forum/awx-project
