### ISSUE TITLE
Isolated nodes in AWX 19.x ?

### ISSUE THREAD

**Issue by sebthebert** [ansible/awx#11146]
### Discussed in https://github.com/ansible/awx/discussions/11131

<div type='discussions-op-text'>

<sup>Originally posted by **sebthebert** September 24, 2021</sup>
Hello,

we were using isolated nodes feature in AWX 17.x.

This feature seems to be missing in AWX 19.x.
And we didn't see anything about that breaking change in [AWX Changelog](https://github.com/ansible/awx/blob/19.3.0/CHANGELOG.md).

Any idea ?</div>

**Comment by shanemcd** [comment]
Sorry, isolated nodes are no longer a feature. Container Groups allows for execution on a remote Kubernetes cluster.
