### ISSUE TITLE
Give migrations-pending page some love (aka Fix matburt's atrocity)

### ISSUE THREAD

**Issue by shanemcd** [ansible/awx#1115]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY
No summary needed

##### ENVIRONMENT
* AWX version: 1.0.2.98
* AWX install method: All
* Ansible version:  N/A
* Operating System: N/A
* Web Browser: N/A

##### STEPS TO REPRODUCE

Drop your db, start migrations, view app

##### EXPECTED RESULTS

To see a beautiful page.

##### ACTUAL RESULTS
![35705984-21b9d38e-0772-11e8-8063-09e6c1e50e89](https://user-images.githubusercontent.com/773186/35705984-21b9d38e-0772-11e8-8063-09e6c1e50e89.png)

##### ADDITIONAL INFORMATION

Take into account that the logo may be different. For AWX it could be the Angry Spud or the "official" logo. For Tower it will be the Tower logo.

@matburt is there a way to conditionally say "AWX" / "Tower" is upgrading?

**Comment by trahman73** [comment]
![image](https://user-images.githubusercontent.com/13351591/35707808-39e750d8-0779-11e8-8de3-abb61f525ae8.png)
![image](https://user-images.githubusercontent.com/13351591/35707846-6a6406ac-0779-11e8-87b7-53cc185f4900.png)
![image](https://user-images.githubusercontent.com/13351591/35707859-7823aefa-0779-11e8-88b0-50f8ce38b2ff.png)
