### ISSUE TITLE
o module named azure.cli.__main__; 'azure.cli' is a package and cannot be directly executed

### ISSUE THREAD

**Issue by vsalvipk** [ansible/awx#11177]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

I'm trying retrieve secrets in ansible and I have tried the most of solution out there like creating virtualenv and install the azure packages inside docker. 

Can someone please help with some solution.

### AWX version

17.1.0

### Installation method

docker on linux

### Modifications

no

### Steps to reproduce

Install AWX 17.1.0 using docker
Create a secret in cloud
run the yaml file in projects to retrieve

### Expected results

the value of secret

secret: XXXXXXXX

### Actual results

error:
No module named azure.cli.__main__; 'azure.cli' is a package and cannot be directly executed", "stderr_lines": ["/usr/bin/python3.6: No module named azure.cli.__main__; 'azure.cli' is a package and cannot be directly executed"]

**Comment by ffirg** [comment]
This repo is not a support forum, please head over to https://groups.google.com/g/awx-project and ask there.
