### ISSUE TITLE
REST API call missed because of "Missing a revision to run due to failed project update"

### ISSUE THREAD

**Issue by stefanpinter** [ansible/awx#11174]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Hi!
tonight a REST API POST was not creating a job like it should have.
project updates failed multiple times (for many hours) because we have some trouble reaching ansible-galaxy/Amazon AWS right now.
Why does it care for missing a revision?

Exception: Client error: `POST https://172.21.10.220/api/v2/job_templates/13/launch/` resulted in a `400 Bad Request` response:
{"playbook":["Missing a revision to run due to failed project update."]}

this affected scheduled jobs as well. see below.

### AWX version

19.3.0

### Installation method

minikube

### Modifications

no

### Steps to reproduce

Make project update fail multiple times (for hours)
Create Job via API

But also two scheduled jobs failed:
RuntimeError: The project revision for this job template is unknown due to a failed update.

### Expected results

receive job via API:
begin to execute it

job triggered via schedule:
begin to execute it

### Actual results

error from client perspective - does not show up in the AWX Jobs:
Exception: Client error: `POST https://172.21.10.220/api/v2/job_templates/13/launch/` resulted in a `400 Bad Request` response:
{"playbook":["Missing a revision to run due to failed project update."]}

error from AWX jobs from a scheduled Job:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1316, in run
    self.pre_run_hook(self.instance, private_data_dir)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1742, in pre_run_hook
    raise RuntimeError(msg)
RuntimeError: The project revision for this job template is unknown due to a failed update.

**Comment by shanemcd** [comment]
I think this is the intended behavior. Did the associated project's last update fail?

**Comment by stefanpinter** [comment]
yes, many failed... but this dependency is questionable to me (in this case Ansible-Galaxy/AWS connectiviy) when the job is just for copying files from one local server to another to be honest.
i wonder if there is an option to change/mitigate this

**Comment by shanemcd** [comment]
Do you have "Update on launch" checked on the project? Unchecking that is probably what you want. If you want us to consider changing the behavior here, please open another issue describing how you think it _should_ work.

**Comment by stefanpinter** [comment]
@shanemcd  no, it is NOT checked and never was!

**Comment by mcmx** [comment]
I don't understand how, 1 failure to update, stops every new job to launch without trying to update the revision, is this behavior documented somewhere?

This kept jobs from running until a manually 'Get latest SCM revision' was executed, there are no logs for either job creation or the update (or try to update the revision from the project) was actually retried.

**Comment by benoittgt** [comment]
> This kept jobs from running until a manually 'Get latest SCM revision' was executed, there are no logs for either job creation or the update (or try to update the revision from the project) was actually retried.

Isn't possible to auto-retry to fetch? At the moment we have to go manually to Project view when there was a downtime on Github/Gitlab. Otherwise we have "Missing a revision to run due to failed project update" for long time.

**Comment by monitoritoprod** [comment]
@benoittgt not that I know.
