### ISSUE TITLE
Credential Org Can't be removed

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#11172]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

A user is creating a credential.  If the credential type does not require an organization they should be able to remove the org without opening the Organization look up.

### AWX version

devel

### Installation method

docker for mac

### Modifications

no

### Steps to reproduce

Create a credential.  Select an Organization.  Close look up. 

### Expected results

The chip that has the credential name should be removable if the credential type does not require it.  If the credential type has not been selected yet, it should be removable and then change to non-removable if the user selects a credential type that requires an organization (like Ansible Galaxy/Automation Hub API Token)

### Actual results

Is isn't removeable

### Additional information

![Screen Shot 2021-09-29 at 4 47 23 PM](https://user-images.githubusercontent.com/39280967/135346619-197ccb05-2706-4911-9ed2-a073f63115a8.png)

**Comment by AlexSCorey** [comment]
Same applies for the Org look up in the Execution Environment form

**Comment by nixocio** [comment]
Good observation @AlexSCorey. But when we added the feature to type on the lookups, we removed the chip to render the removal.
