### ISSUE TITLE
Inventory updates should show `controller_node` field

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#11196]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Inventory updates can / will run remote now, so their serializer should surface the `controller_node` field.

**Comment by AlanCoding** [comment]
It's likely that we would move this field up to the `UnifiedJobSerializer` from the subclasses, so this would be good opportunity for a bit of refactoring of the serializers. More and more functionality has been promoted up to the unified class as time has gone on.

**Comment by mabashian** [comment]
Corresponding UI work tracked here: https://github.com/ansible/awx/issues/12132
