### ISSUE TITLE
Respect `AWX_CLEANUP_PATHS` on execution nodes

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#11197]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
If `settings.AWX_CLEANUP_PATHS` is `False`, then we should not add the `--delete` flag when submitting the remote work unit.

**Comment by Zokormazo** [comment]
Seems there are some more ongoing developments related to fix this one, moving back to `needs_devel`

**Comment by shanemcd** [comment]
@AlanCoding @Zokormazo What's the latest word on this one?

**Comment by AlanCoding** [comment]
I rebased https://github.com/ansible/ansible-runner/pull/887 after a few hickups, and CI is passing now. I'll check with Sam about what else he wants to get done.

**Comment by AlanCoding** [comment]
Adjusted labels to reflect that there is an unmerged PR for this.

**Comment by AlanCoding** [comment]
The fix should get in the ansible-runner nightly builds tonight.

**Comment by obaranov** [comment]
Now setting AWX_CLEANUP_PATHS to False works fine and awx stop folders cleanup in that case.
