### ISSUE TITLE
Presence of execution nodes will cause cluster to report as ha environment

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#11202]
##### ISSUE TYPE
 - Bug

##### SUMMARY

If an install has 1 hybrid or control node, but has 1 or more execution nodes, it will erroneously report as an ha environment.

https://github.com/ansible/awx/blob/a036363e85d5f774140a8f54adb8938011236728/awx/main/ha.py#L8-L15

This takes no account of `node_type`. It should not count execution nodes here, because they offer no contributions to server high-availability.

**Comment by Zokormazo** [comment]
@CFSNM could you check this one? Thanks :)
