### ISSUE TITLE
Workflow Visualizer Toolbar Issues

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#11203]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

The toolbar disappears and fit to screen doesn't work properly.

### AWX version

devel

### Installation method

docker for mac

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

Create a workflow template with 2 nodes fanned out from start.  Go to the visualizer.  Zoom in via 2 finger zoom in until the toolbar disappears.  Then 2 finger zoom out until the toolbar reappears.  

1) Notice, you have to go a long way out to get the toolbar to render again.  
2) The fit to screen button doesn't work as expected.

### Expected results

1) The toolbar never disappears
2) Clicking on the fit to screen button brings the nodes back into focus the first time you click it.

### Actual results

1) The toolbar can disappear if you zoom in enough
2) Must click the fit to screen button 2x in order to get the nodes to return

### Additional information

![Expand](https://user-images.githubusercontent.com/39280967/136056146-93f4569e-a3fe-4fcd-a8b7-15c765b42761.gif)

**Comment by kialam** [comment]
I am able to zoom in on any page within the app with pinch to zoom gesture, not just on the workflow viz section. 
![zoom](https://user-images.githubusercontent.com/2293210/160490908-0d2f20b5-af25-45e6-b55d-5f1999f1049c.gif)

As such, I _think_ this is a chrome browser pinch to zoom gesture thing rather than a bug.
