### ISSUE TITLE
Not able to load UI page beyond login page on Ansible AWX

### ISSUE THREAD

**Issue by ghost** [ansible/awx#11215]
I have installed AWX using docker-compose after cloning from GitHub. I am trying to run Ansible awx from behind nginx as a reverse proxy but on the web page, after entering the login credentials, it is redirecting itself to /api/login/ and showing error as 405 not allowed see the image for the error.
Can you please suggest if I am doing correctly.
`location /awx/ {
proxy_pass "http://backendawx/";
proxy_set_header   Host $host;
proxy_set_header   X-Real-IP $remote_addr;
proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header   X-Forwarded-Host $server_name;
proxy_redirect /awx/ //;
access_log /var/log/nginx/awx/access.log timed_combined;
error_log /var/log/nginx/awx/error.log error; `
![EC203A58-B7A5-4846-9003-D8DF7B6AB0B6](https://user-images.githubusercontent.com/91253573/136329457-8a4445f4-91a3-4076-8e0c-471b2b232e51.png)

**Comment by gauravsuryawanshi0806** [comment]
@imkr07 :+1: Kindly do the nginx configuration like below, as i configured the same and it works for me

**nginx configuration:**
upstream backendawx {
      server HOSTNAME:PORTNUMBER;
    }
  location /awx/ {
          proxy_pass "http://backendawx/#/login/";
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Host $server_name;
          proxy_redirect /awx/ /#/login/;
          access_log /var/log/nginx/awx/access.log timed_combined;
          error_log /var/log/nginx/awx/error.log error;
    }
location /api/ {
          proxy_pass "http://backendawx/api/";
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Host $server_name;
        }

**Comment by nixocio** [comment]
Hello,

If you need help troubleshooting or are looking for help using AWX, try our mailing list or IRC channel:

#ansible-awx on[ https://libera.chat/](https://libera.chat/)
https://groups.google.com/forum/#!forum/awx-project
