### ISSUE TITLE
 Ansible collection - job_template module unable to update survey spec

### ISSUE THREAD

**Issue by no-12** [ansible/awx#11229]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Using the job_template module, I am unable to update/add/delete "survey_spec.spec", when I only change the "survey_spec.spec" and nothing else.

If some other JobTemplate property changes, everthing works fine and the survey will update as well.

### AWX version

19.2.2

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

only add a single survey question with the job_template module to an existing job template

### Expected results

survey should have a new survey question and the task should be marked as changed

### Actual results

The new question is in the task output, but it is not added to the job template and the task is not marked as changed.

**Comment by chrismeyersfsu** [comment]
related to https://github.com/ansible/awx/pull/11230

**Comment by CFSNM** [comment]
Validated from QE side
