### ISSUE TITLE
AWX 17.1.0 doesnt apply limits on workflows

### ISSUE THREAD

**Issue by rsabadoAtSirti** [ansible/awx#11221]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Hi downloading the version 17.1.0 of awx i noticed an error or bug which make awx ignore the limits applied in the workflow
ill add screenshots and more details :

My Lab Structure 
-  1 server with rhel 8.4 with a developer subscription which has awx on it ;
-  2 servers with rhel 8.4 with also a developer subscription ;

so i have these two templates :

![image](https://user-images.githubusercontent.com/91897560/136531030-4c17b684-7663-445c-ab42-9df145644a55.png)

so the testDir.yml playbook just creates a file called automated.txt under /tmp

![image](https://user-images.githubusercontent.com/91897560/136531140-8ba3d12d-2377-4c8e-980c-c2b198a34b66.png)

the testDirDel.yml playbook deletes the automate.txt file created with the previous job template

![image](https://user-images.githubusercontent.com/91897560/136531330-f84416c0-a2f7-4cad-910c-529665b4c667.png)

![image](https://user-images.githubusercontent.com/91897560/136531447-9113092c-75a1-4f6a-a630-66675b43ba50.png)

this one is the workflow that i used 

my question is , is there any other version that doesnt have this bug ? or is there any other way to solve this problem ?

what happens when i run the workflow ? 

![image](https://user-images.githubusercontent.com/91897560/136533065-50388c55-12c7-473a-b07d-24aa8a623467.png)

this is what i see but if i click on the template jobs 
i see this 

![image](https://user-images.githubusercontent.com/91897560/136533453-ea5e5b27-8d43-4d38-9a23-5ba3f6baf48b.png)

how is it possible two have the second server if i put the limit on 

![image](https://user-images.githubusercontent.com/91897560/136533634-2d7e9327-61e0-4dd5-9b5f-82b7f372f21a.png)

can someone help me with this ? 

### AWX version

17.1.0

### Installation method

docker on linux

### Modifications

no

### Ansible version

2.9.26

### Operating system

RHEL 8.4 

### Web browser

Chrome

### Steps to reproduce

install via docker compose the version of awx 17.1.0  then run a workflow with two simple job on them , put a limit on one of the machines on one of the job templates youll see that it will ignore it and still apply the job on the other machines in the inventory 

### Expected results

i expected that it will apply the limit and  wont apply the job template on other machines in the inventory

### Actual results

the job template present in the workflow even with the limit on it still apply the playbook on the other machines in the

**Comment by nixocio** [comment]
@rsabadoAtSirti thanks for filing this issue, could you upgrade to the latest AWX version?

**Comment by rsabadoAtSirti** [comment]
hi nixocio , can i deploy the latest version with docker-compose ? im having trouble by setting up the latest AWX  version with minikube

**Comment by nixocio** [comment]
> hi nixocio , can i deploy the latest version with docker-compose ? im having trouble by setting up the latest AWX version with minikube

I believe so.

**Comment by rsabadoAtSirti** [comment]
ok ill try the deploy of the latest AWX and i'll tell you if the problem still remain

**Comment by chrismeyersfsu** [comment]
@rsabadoAtSirti did you get a chance to try the latest AWX ?

**Comment by nixocio** [comment]
It seems to be the same issue as: https://github.com/ansible/awx/issues/11221 reported on a newer version.

**Comment by nixocio** [comment]
Closing this one as a duplicated of https://github.com/ansible/awx/issues/11284
