### ISSUE TITLE
Intermittent logout/authentication failure

### ISSUE THREAD

**Issue by ghost** [ansible/awx#1122]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Using the latest build, though this is not unique to this build. After some time, as little as a few seconds, or up to a few minutes, my login session will apparently end, and every page will simply error with "Failed to get config. GET returned status: 401 Authentication credentials were not provided."

Cookie values:
sessionExpired: false
userLoggedIn: true
token_expires: 2018-02-02{continues}

edit: this portion of the post was typed on the first, well in advance of any session expiration issues based on the expiration date of the token.

I set the following in my settings.py:
USE_X_FORWARDED_PORT = True
USE_X_FORWARDED_HOST = True

In the settings menu I set remote host headers to: REMOTE_ADDR, REMOTE_HOST, HTTP_X_FORWARDED_FOR

I can still access the API, so I know that the session is still valid.

##### ENVIRONMENT
* AWX version: latest. 1.0.3, I think.
* AWX install method: docker deployed to AWS ECS.  ingress and SSL termination are handled by an Application Load Balancer.

##### STEPS TO REPRODUCE

Deploy awx into elastic container service fronted by an ALB. (ELBs do not support websockets, and also do not solve this problem)

Log in as normal, click around a little, wait a few minutes, and then try using the UI again.

##### EXPECTED RESULTS

A login session will remain valid until it expires, and the GUI will correctly interpret it as such.

##### ACTUAL RESULTS

The GUI incorrectly reports that the session is invalid, or was not sent at all.

##### ADDITIONAL INFORMATION

I didn't see anything obviously useful in the awx_web logs. It seems like a front-end issue, but I know almost nothing about diagnosing front-end stuff, so I could be way off.

The problem also doesn't seem to manifest in Edge. I've tested Chrome, Safari, and Firefox, and it does appear in all of them.

Would appreciate any insight, as I have been battling with this for quite some time, and am completely out of ideas.

**Comment by ghost** [comment]
After more testing, it seems the most prevalent on Chrome. I've still not seen it happen on Edge at all.

**Comment by ghost** [comment]
I figured it out.

awx/awx/main/models/organization.py -> get_request_hash combines secret key and the first header it finds in the list settings.REMOTE_HOST_HEADERS, so if x-forwarded-for is not the first entry and you use a highly available load balancer, you will have this experience, even if x-forwarded-for is being sent and is in the list.

Probably not a bug, but could probably be a better user experience. Now that I know the solution I'll poke at possible improvements.

**Comment by jaredevantabor** [comment]
Hi @Comradephate, thanks for your due diligence, I would recommend pinging @matburt in IRC to discuss any questions you might have about your solution. If you're ok with it, I'm going to close this issue since you figured it out. Ping me if you want me to reopen it. Thanks!
