### ISSUE TITLE
Please add OCI as a cred-type on awx

### ISSUE THREAD

**Issue by bsushant-athena** [ansible/awx#11220]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Add OCI as a cred type on awx so that it becomes easy for devs who are using awx on oci.
more info regarding cred type: https://blogs.oracle.com/cloud-infrastructure/post/using-oracle-cloud-infrastructure-with-ansible-tower-and-awx

**Comment by chrismeyersfsu** [comment]
We would be happy to review a PR that adds this support. Are you able to provide the infrastructure needed to verify this issue?

**Comment by bsushant-athena** [comment]
Yes I followed that document and it works on OCI. I think if we just add the OCI crude type that will reduce one manual step from that doc.

**Comment by ffirg** [comment]
As Chris stated, we'll happy accept a PR for that code. As you have a workaround and we don't see a lot of demand for this, closing this issue. Please open a PR with the code and it'll get reviewed.

**Comment by compgeniuses** [comment]
is oci fully supported
