### ISSUE TITLE
LDAP setting doesn't work

### ISSUE THREAD

**Issue by hungtran84** [ansible/awx#11237]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

I was able to enable LDAP authentication for the first time but after logout, it is no longer work.

### AWX version

19.3.0

### Installation method

kubernetes

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

LDAP GROUP TYPE
```
ActiveDirectoryGroupType
```

LDAP REQUIRE GROUP
```
CN=operators,OU=Mycompany.com,DC=abc,DC=xyz,DC=y,DC=net
```

LDAP User Search
```
[
  "DC=abc,DC=xyz,DC=y,DC=net",
  "SCOPE_SUBTREE",
  "(sAMAccountName=%(user)s)"
]
```

LDAP Group Search
```
[
  "OU=Groups,OU=Mycompany.com,DC=abc,DC=xyz,DC=y,DC=net",
  "SCOPE_SUBTREE",
  "(objectClass=group)"
]

LDAP User Attribute Map
```
{
  "first_name": "givenName",
  "last_name": "sn",
  "email": "mail"
}
```

LDAP Group Type Parameters
```
{
  "name_attr": "cn"
}
```

LDAP User Flags By Group
```
{
  "is_superuser": [
    "CN=DBAs,CN=Groups,OU=Mycompany.com,DC=abc,DC=xyz,DC=y,DC=net"
  ]
}
```

LDAP Organization Map
```
{
  "is_superuser": [
    "CN=DBAs,CN=Groups,OU=Mycompany.com,DC=abc,DC=xyz,DC=y,DC=net"
  ]
}
```

LDAP Organization Map
```
{
  "ABC": {
    "remove_admins": false,
    "users": true,
    "admins": "CN=DBAs,OU=Groups,OU=Mycompany.com,DC=abc,DC=xyz,DC=y,DC=net",
    "remove_users": false
  }
}
```

LDAP Team Map
```
{
  "DBA": {
    "remove": true,
    "users": "CN=DBAs,OU=Groups,OU=Mycompany.com,DC=abc,DC=xyz,DC=y,DC=net",
    "organization": "ABC"
  }
}

### Expected results

I should be able to login with my AD account persistently.

### Actual results

Was able to login at the fist time but failed after logout

### Additional information

The output log is quite verbose as below:
```
2021-10-12 04:27:27,857 WARNING  [e0f40d661dd341be8d5bda5ab597fd61] awx.api.generics Login failed for user xxx from x.x.x.x
2021-10-12 04:27:27,863 DEBUG    [e0f40d661dd341be8d5bda5ab597fd61] awx.analytics.performance request: <WSGIRequest: POST '/api/login/'>, response_time: 0.080s
2021-10-12 04:27:27,864 WARNING  [e0f40d661dd341be8d5bda5ab597fd61] django.request Unauthorized: /api/login/
2021-10-12 04:27:27,864 WARNING  [e0f40d661dd341be8d5bda5ab597fd61] django.request Unauthorized: /api/login/
```

**Comment by derhoeppi** [comment]
Please update to AWX 19.4.0. Its a know failure That was fixed. 
Look at https://github.com/ansible/awx/issues/10883 or https://github.com/ansible/awx/issues/11159
