### ISSUE TITLE
Add expand/collapse all to Job Output

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#11236]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

From mockup, see arrow on the left corner.

Add expand/collapse all to Job Output.

Related to: https://github.com/ansible/awx/issues/6613

<img width="1481" alt="image" src="https://user-images.githubusercontent.com/9053044/136847968-271c30b6-85ab-49e0-bdab-360c2a73b969.png">

**Comment by nixocio** [comment]
@akus062381, can we close this one?

**Comment by akus062381** [comment]
this is complete! closing
