### ISSUE TITLE
Project and Inventory update starts at the same time

### ISSUE THREAD

**Issue by marekvesely-direct** [ansible/awx#11233]
### Please confirm the following

- [x] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

I enabled in Inventory Source "Update on launch" and in Project "Update revision on job launch", but there is problem that both jobs starts at the same time. First executed must be Project update and after thath Inventory Sync. Because now there is old revision for inventory so users have to execute the job twice to get current changes from git. 

### AWX version

19.2.2

### Installation method

kubernetes

### Modifications

no

### Ansible version

4.1.0

### Operating system

default

### Web browser

Firefox

### Steps to reproduce

- create project from GIT and enable Update revision on job launch
- create inventory with source from GIT and enable Update on launch
- create some template
- launch template

### Expected results

First have to be executed Source Control Update of Project, after thaht Inventory Sync and last one Playbook executed via template.

### Actual results

![1](https://user-images.githubusercontent.com/56677711/136782221-4e8fa1d7-6b2c-4fb2-a608-28eb50b3dee0.PNG)

**Comment by marekvesely-direct** [comment]
19.4.0 version is the same problem

**Comment by chrismeyersfsu** [comment]
@marekvesely-direct can you try checking the "update on project change" in the inventory source?

Currently, this is what is happening:
![image](https://user-images.githubusercontent.com/722880/137528878-5c2ee479-c810-4f1e-86a7-76861c59446f.png)

You want this:
![image](https://user-images.githubusercontent.com/722880/137528956-5dc4ecff-c797-4107-8929-fba0ef796662.png)

We think that "update on project change" will give you what you want.

**Comment by marekvesely-direct** [comment]
Hello, I also tried "update on project change", but I have 23 inventories and it tooks a lot of time. So when I executed 1 playbook, it will update project and then all 23 inventories, after that it starts template. This is not ideal solution. From my perspective it has no sense to execute Inventory update before Project update. It should be as you draw on second picture. Thank you!

**Comment by marekvesely-direct** [comment]
Any news?

**Comment by chrismeyersfsu** [comment]
Possibly related https://github.com/ansible/awx/issues/11336

**Comment by shanemcd** [comment]
Closing this in favor of #11336, as that one has some more details and proposed solution.
