### ISSUE TITLE
Unable to ping remote host

### ISSUE THREAD

**Issue by sarman-tftsr** [ansible/awx#11250]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

If running ansible from the cli I can connect and do a simple ping:
`bash-4.4# ansible -m ping svn
[WARNING]:  * Failed to parse /etc/ansible/hosts with yaml plugin: We were unable to read either as JSON nor YAML,
these are the errors we got from each: JSON: Expecting value: line 1 column 2 (char 1)  Syntax Error while loading
YAML.   did not find expected <document start>  The error appears to be in '/etc/ansible/hosts': line 2, column 1,
but may be elsewhere in the file depending on the exact syntax problem.  The offending line appears to be:
[tower] awx.tftsr.com ansible_host=tftsr.com ^ here
[WARNING]:  * Failed to parse /etc/ansible/hosts with ini plugin: not enough values to unpack (expected 3, got 2)
[WARNING]: Unable to parse /etc/ansible/hosts as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not
match 'all'
ops.e911.io | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "ping": "pong"
}`

If running a command from AWX it fails to ping and complains about a missing directory:
`"msg": "Failed to set execute bit on remote files (rc: 1, err: Warning: Permanently added 'ops1e911.io,173.31.189.19' (ECDSA) to the list of known hosts.\r\nControlSocket /tmp/bwrap_72_7yly_ha4/awx_72_xtxl3nwk/cp already exists, disabling multiplexing\r\nchmod: cannot access '/var/services/homes/sarman/.ansible/tmp/ansible-tmp-1634515035.4552245-179-266757528386617/AnsiballZ_ping.py': No such file or directory\n)",
  "_ansible_no_log": false`

Here is my ansible.cfg:
`[defaults]
inventory      = /etc/ansible/hosts
gathering = implicit
gather_subset = all
roles_path    = /etc/ansible/roles:/home/ecw-ansible/roles:/var/lib/awx/projects/_8__callworks/roles
host_key_checking = False
fact_caching_connection=/var/lib/ansible/fact_cache

[ssh_connection]
ssh_args = -F /etc/ansible/ansible-ssh.cfg -C -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ForwardAgent=yes -o 'IdentityFile="/var/lib/awx/id_rsa"'
retries = 2

[persistent_connection]
command_timeout = 30`

My ansible-ssh.cfg:
` Host *
   User sarman
   StrictHostKeyChecking no
   PermitLocalCommand yes
   ForwardAgent yes
   GSSAPIAuthentication no
   IdentityFile /var/lib/awx/id_rsa
Host 127.0.0.10
        ProxyCommand ssh -A -W %h:%p -q host.domain.org
        HostName 127.0.0.1
        ForwardAgent yes
        AddKeysToAgent yes
        StrictHostKeyChecking no

Host 127.0.0.20
        ProxyCommand ssh -A -W %h:%p -q host.domain.org
        HostName 127.0.0.1
        ForwardAgent yes
        AddKeysToAgent yes
        StrictHostKeyChecking no`

Any suggestions? I have been looking through google all week. I have found some references to this issue on older versions, but even the fix's they mention are not working for me.

### AWX version

17.1.0

### Installation method

docker on linux

### Modifications

yes

### Ansible version

2.9.18

### Operating system

Rocky Linux 8 (Linux host.com 4.18.0-305.3.1.el8_4.x86_64)

### Web browser

Chrome

### Steps to reproduce

I navigate to the following:
Inventories | <INVENTORY> | Hosts
Select any given host, then elect to run a command
Select PING
No other options are selected (Except setting debug).
Select either local credentials, or SSH PKA

### Expected results

Ping successful like when I run `ansible -m ping svn` from the terminal

### Actual results

`<ops1e911.io> ESTABLISH SSH CONNECTION FOR USER: <USER>
<ops1e911.io> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="<USER>"' -o ConnectTimeout=10 -C -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ForwardAgent=yes -o ControlPath=/tmp/bwrap_72_7yly_ha4/awx_72_xtxl3nwk/cp ops1e911.io '/bin/sh -c '"'"'rm -f -r /var/services/homes/<USER>/.ansible/tmp/ansible-tmp-1634515035.4552245-179-266757528386617/ > /dev/null 2>&1 && sleep 0'"'"''
<ops1e911.io> (0, b'', b"Warning: Permanently added 'ops1e911.io,173.31.189.19' (ECDSA) to the list of known hosts.\r\nControlSocket /tmp/bwrap_72_7yly_ha4/awx_72_xtxl3nwk/cp already exists, disabling multiplexing\r\n")
ops1.e911.io | FAILED! => {
    "msg": "Failed to set execute bit on remote files (rc: 1, err: Warning: Permanently added 'ops1e911.io,173.31.189.19' (ECDSA) to the list of known hosts.\r\nControlSocket /tmp/bwrap_72_7yly_ha4/awx_72_xtxl3nwk/cp already exists, disabling multiplexing\r\nchmod: cannot access '/var/services/homes/<USER>/.ansible/tmp/ansible-tmp-1634515035.4552245-179-266757528386617/AnsiballZ_ping.py': No such file or directory\n)"
}`

**Comment by ffirg** [comment]
Bubblewrap, which does process isolation in this AWX release, is preventing you from accessing files outside certain areas. You may wish to look at turning bubblewrap protection off (in the GUI settings) to get round this, or fix by moving files. 

This repo is not for support issues, so closing. Please post such issues in the google groups forum for such issues.
