### ISSUE TITLE
Cannot validate Certificates from Custom CA when Job lauched from AWX GUI.

### ISSUE THREAD

**Issue by Alestor** [ansible/awx#11268]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Hello, I'm not 100% sure if it is actual a bug, but I'm kind of stuck with this issue and I couldn't get an answer to it from IRC. So sorry to bother you guys if I'm wrong.
I've deployed a fresh awx 19.4.0 instance on k3s and added some custom CAs to it, by the method it's described in the docs of awx-operator. Checking the awx related containers the ca-certificates are included. LDAPS Authentication for awx-web works fine as well. However, if I run a simple job from awx gui, the URI Module cannot validate the certificate of the webserver which has a certificate from my custom CA. Running exactly the same job directly from the awx-ee container using ansible-playbook command works fine. I'm using some custom filter plugins which also have the same issue, but only if the job is launched from awx-gui. Running these jobs from awx-ee container directly or as a pure python script have no issue to validate the SSL Connection.

Checking within the awx-ee container, my ca certificates are include in the files python uses to verify x509 server certificates.

```
python -c "import ssl; print(ssl.get_default_verify_paths())"        
DefaultVerifyPaths(cafile='/etc/pki/tls/cert.pem', capath='/etc/pki/tls/certs', openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/etc/pki/tls/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/etc/pki/tls/certs')
```

Same goes for the requests module

```
python -c "import requests; print(requests.certs.where())"           
/etc/pki/tls/certs/ca-bundle.crt
```
Only the certifi module uses another trust anchor, which has not my ca certificates included.
```
>>> print(certifi.where())
/usr/local/lib/python3.8/site-packages/certifi/cacert.pem
```

### AWX version

19.4.0

### Installation method

kubernetes

### Modifications

no

### Ansible version

core 2.11.6.post0 - shipped with awx-ee

### Operating system

Debian11

### Web browser

Firefox

### Steps to reproduce

Launch a simple job with a URI get request to an REST API with a certificate from a Custom CA. Ensure validate_certs is set to yes.

### Expected results

Request gets a status code of 200 in return.

### Actual results

Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1124)>")

### Additional information

Error Message from custom filter plugins, when job lauched through awx:

SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)

**Comment by Alestor** [comment]
Fixed by building a Custom EE. Looks like I misunderstood some concepts of the k8s deployment model.

**Comment by craph** [comment]
Hello @Alestor ,

Please could you give more details how did you fix your issue ?

Thank you very much.
Best regards,

**Comment by Alestor** [comment]
Hi craph, 

you have to build your own Execution Environment Container, include your private CA Certs and push it to a Container Repository. On AWX you can add it under Administration -> Execution Environment and use it in your Job Templates.
The EE can be build by using Ansible Builder. A good starting point are the [Docs](https://ansible-builder.readthedocs.io/en/latest/). I used the official [AWX-EE Repository](https://github.com/ansible/awx-ee) for a reference configuration. The file  execution-environment.yml  has a section for additional building steps where you can add your CA Files to the container.
