### ISSUE TITLE
Docker-compose upgrade fails because of missing docker-auth section in Makefile

### ISSUE THREAD

**Issue by stucksam** [ansible/awx#11289]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

We're trying to upgrade our docker development environment from 19.3.0 to 19.4.0. However, when we run "make docker-compose" as instructed by the upgrade section in the install guide, the operation stops immediately because the Makefile is missing the "docker-auth" section.

### AWX version

19.3.0

### Installation method

docker on linux

### Modifications

no

### Operating system

Debian 10

### Steps to reproduce

1. Clone GitHub repo of awx 19.4.0
2. populate inventory file
3. run make docker-compose

### Expected results

The upgrade from 19.3.0 to 19.4.0 should start

### Actual results

An error message saying make is missing a rule for "docker-auth" which is required by "docker-compose". 

### Additional information

The error message (it's in german). 
![error_message](https://user-images.githubusercontent.com/40593030/139211733-371a1280-cb30-4d6e-bc57-8f30d905b532.jpg)

When comparing the Makefiles of 19.3.0 and 19.4.0 the issue becomes apparent: The docker-auth section has been completely removed, docker-compose however, still depends on this section for whatever reason.
![comparison_makefile](https://user-images.githubusercontent.com/40593030/139211728-2b5fdf89-38a0-4cea-9741-2411e2f1f6c9.png)

**Comment by sadok-f** [comment]
I have the same issue, any update on it?

**Comment by shanemcd** [comment]
I think this was fixed in devel. We should be doing a new release soon. Sorry for the turbulence.

**Comment by Nihvel** [comment]
Same issue ):
![image](https://user-images.githubusercontent.com/24250443/141659595-37a6d87a-8636-46c2-8448-6cf7415a3b77.png)

Following the instructions from here https://github.com/ansible/awx/tree/devel/tools/docker-compose using the 19.4.0

**Comment by rwjack** [comment]
Bumperino. Exact same situation as @Nihvel 

Is there a bypass for this?

Update: Just copy pasted the missing part from 19.3.0's makefile.

Update 2: The bypass allowed the containers to startup, but I cannot reach the UI.

```
root in headquarters in tools/docker-compose/_sources on  HEAD (0736f4d) [!] via 🐍 v2.7.16 ❯ netstat -tupan|grep 8013
tcp        0      0 0.0.0.0:8013            0.0.0.0:*               LISTEN      16188/docker-proxy
tcp6       0      0 :::8013                 :::*                    LISTEN      16196/docker-proxy

root in headquarters in tools/docker-compose/_sources on  HEAD (0736f4d) [!] via 🐍 v2.7.16 ❯ netstat -tupan|grep 8043
tcp        0      0 0.0.0.0:8043            0.0.0.0:*               LISTEN      16155/docker-proxy
tcp6       0      0 :::8043                 :::*                    LISTEN      16164/docker-proxy
```

```
root in headquarters in tools/docker-compose/_sources on  HEAD (0736f4d) [!] via 🐍 v2.7.16 ❯ curl 127.0.0.1:8013
curl: (56) Recv failure: Connection reset by peer

root in headquarters in tools/docker-compose/_sources on  HEAD (0736f4d) [!] via 🐍 v2.7.16 ❯ curl 127.0.0.1:8043
curl: (56) Recv failure: Connection reset by peer

root in headquarters in tools/docker-compose/_sources on  HEAD (0736f4d) [!] via 🐍 v2.7.16 ❯ curl https://127.0.0.1:8043
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:8043

```

**Comment by atrawog** [comment]
That what happens if you read the documentation :) Things work fine in `devel` but if you do a `git clone -b 19.4.0 https://github.com/ansible/awx.git` this issue is the first thing you run across and it would be nice to have a new release that fixes this issue.

**Comment by stucksam** [comment]
We just upgraded to 19.5.0 and the error has indeed been fixed, just like @shanemcd said. Will close this issue now.

**Comment by ChemicalNRG** [comment]
And broken again in 21.0.0 so it seams
