### ISSUE TITLE
Limit of Job inside of a Workflow dont work 19.4.0

### ISSUE THREAD

**Issue by Geartwo** [ansible/awx#11284]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

No limit is set in a workflow.
Limits are set in the jobs inside of it the workflow.
Job limitation does not apply. 

### AWX version

19.4.0

### Installation method

kubernetes

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

Set no limit in a workflow.
Set limits in the jobs inside of it the workflow.

### Expected results

Playbook should only apply on selected machines.

### Actual results

Playbook get executed on all machines.

**Comment by chapai518** [comment]
I have the same problem on 19.4.0 deployed in OpenShift, limits work for regular templates, but do not work when set inside a workflow. This was the same problem with earlier versions of AWX.

**Comment by mikecurrancs** [comment]
I reported this in 17.0.1(it was only an issue in scheduled workflows then) and this completely breaks all of our workflows. It's almost as if the expectation is you should only run workflows based on all the servers being exactly the same. We provide services to customers and our workflows are built around customer servers as a grouping and not all servers are exactly the same application, but tie together as a group. The limit in the workflows associated job template should be the top level OVER the workflow template limit. This works as if the workflow is the top level limit and ignores the job template(which asks for a limit and your survey questions).

**Comment by mikecurrancs** [comment]
I originally reported this issue in https://github.com/ansible/awx/issues/9377 , and the ONLY solution so far is to execute workflows through an API call? There have been 10 releases (including 17.0.1) and this issue has not been addressed within the UI? 

Why are we reporting a bug then?

**Comment by nixocio** [comment]
I created an inventory with hosts: foo, bar, localhost, set the limit on the job template to bar, and run the job template.

![image](https://user-images.githubusercontent.com/9053044/140521159-d69b92f2-b971-4b89-bec3-f2cca7b7c3b2.png)
![image](https://user-images.githubusercontent.com/9053044/140521261-d8af3f64-6645-4338-b496-f9bef0dc7db0.png)
![image](https://user-images.githubusercontent.com/9053044/140521282-ac7e852f-49ae-4573-ba25-73dc322d3aa3.png)


1 - This one is working as expected

2 - Creating a workflowjob template using the job template above, and set the limit to localhost. The limit on the workflow is not respected.
![image](https://user-images.githubusercontent.com/9053044/140521354-7a945861-1647-43c1-b223-80fef2717fda.png)
![image](https://user-images.githubusercontent.com/9053044/140521399-d3c05634-b1cc-4190-a1a0-d6cab52876ee.png)


But on the API we have for workflow - limit set to localhost.

![image](https://user-images.githubusercontent.com/9053044/140521447-6be8e92d-e2b4-4d40-b5e0-06313c2f7668.png)

**Comment by mikecurrancs** [comment]
I went as a far as removing the inventory from the workflow template 
![image](https://user-images.githubusercontent.com/5721941/140536690-24165e1d-bceb-4a65-8c9c-1442db295c38.png)

Then ran the job template , which has a limit of just a couple specific dev servers


and the full vmware inventory was run through setup on the job template and the limit on the job template was ignored. Even though I did not tell the workflow template which inventory to use
![image](https://user-images.githubusercontent.com/5721941/140537080-ac40d448-e3d2-4b39-953a-1da82ce7b9e6.png)

**Comment by mikecurrancs** [comment]
Ill be more than happy to setup a screen share in MS Teams and go through a live test.

**Comment by mikecurrancs** [comment]
This solution from #9377 worked to fix workflows (although it should not be necessary). 

Update your workflow through AWX API:
https://docs.ansible.com/ansible-tower/latest/html/towerapi/api_ref.html#/Workflow_Job_Templates/Workflow_Job_Templates_workflow_job_templates_update

PUT http://{your_awx_url}/api/v2/workflow_job_templates/{your_workflow_id}/ HTTP/1.1
Authorization: Basic your_username:your_password
Content-Type: application/json

{
"name": "Your workflow name",
"limit": null,
"scm_branch": null,
"ask_variables_on_launch": true
}

Prior to API
![image](https://user-images.githubusercontent.com/5721941/140755816-75a5dea5-b86e-4c3f-bbbe-e98c106330ed.png)
After API
![image](https://user-images.githubusercontent.com/5721941/140755578-cd61ff60-ef4c-477b-8573-1bdbb8c7f866.png)

**Comment by mikecurrancs** [comment]
Update: I can confirm the API call works to make the workflow act correctly. However, if you update the workflow in the UI , then it will reset the values from null to "" 

Just have to be careful for getting this fixed.

**Comment by mikecurrancs** [comment]
I looked at the changes made based on ticket #9377 and the following 2 changes did not seem to carry forward. Could either of these be causing the issue?

This one for the workflowtemplateadd sets the limit to '' instead of null
![image](https://user-images.githubusercontent.com/5721941/140805461-f328c1db-b76f-4274-95a8-d90eef9c5d2c.png)

This one in workflowjobtemplateform also sets limit to '' as a fallback
![image](https://user-images.githubusercontent.com/5721941/140805749-6d2fef91-6dcd-4ca6-b5b5-35ee29dc4aee.png)

Our job templates are re-usable and are set to ask on launch for inventory with no defaults, could this be part of why an empty set is being used for either of these 2 js?

**Comment by mikecurrancs** [comment]
@nixocio Is this still being reviewed? I can clearly see the issue in my environment from a clean install of 19.4.0 and having to run an API call to fix the workflows is not an appropriate answer. 

Are you suggesting setting a bogus limit on the workflow, instead of letting the save process fill in an empty set for the limit?

**Comment by kladiv** [comment]
+1
In my opinion this should be high priority. Limits on Workflow jobs are quite important when making *blueprints*

**Comment by nixocio** [comment]
See: https://github.com/ansible/awx/issues/11080#issuecomment-991894100

**Comment by johnmillertech** [comment]
There seems to have been a regression of #10195 here: likely the change to WorkflowJobTemplateForm.jsx there did not persist when the /ui and /ui_next dirs were merged.  I just submitted https://github.com/ansible/awx/pull/11477 ; hopefully this can get approved and make it into 19.6.0.

**Comment by InnocentK** [comment]
Should now be resolved
