### ISSUE TITLE
Instances changes events not showing in activity stream (Instance group) filter

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#11285]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

This is a follow up from https://github.com/ansible/awx/issues/10897

All changes related to instance group itself is displayed when selecting the "Instance Groups" on select

![image](https://user-images.githubusercontent.com/12464858/139078173-d4857163-0a16-4bf4-8adf-92862d8fab88.png)

However, all the instances changes events are not been tracked in  "Instance Groups" option, but in "Dashboard (All activity)"

![image](https://user-images.githubusercontent.com/12464858/139078848-e44b1bb6-5986-4281-a81d-e67e737632c7.png)

![image](https://user-images.githubusercontent.com/12464858/139078760-a8963044-8c32-4a76-b4be-e1593e747de5.png)

### AWX version

19.4.0

### Installation method

docker on linux

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

1. Navigate to Instance Groups
2. Select controllplane group
3. Disable de instance
4. Click on Activity Stream button

### Expected results

We should show all Instance changes events as part of "Instance Group" item on select

OR

Create a new "Instances" item on select and direct the user to the correct place showing the instance events.

### Actual results

The instance changes events is only displayed on "Dashboard (all activity)" item

**Comment by InnocentK** [comment]
Resolved in https://github.com/ansible/tower/pull/5398

Note: This fix introduces new elements that affect activity stream tests. These tests will need to be updated in a future PR.
