### ISSUE TITLE
Google Compute Host metadata fields not accepted in keyed_groups

### ISSUE THREAD

**Issue by bschaeffer** [ansible/awx#11294]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

I have a source for an inventory backed by Google Compute Engine. Some of these hosts have a `metadata` field with various key values and look like so when viewing the JSON via AWX:

```json
{
  "labels": {
    "app": "bastion",
  },
  "metadata": {
    "enable-oslogin": "TRUE",
  }
}
```

When I try to use the following `keyed_groups` config:

```yaml
keyed_groups:
  - prefix: "tag"
    key: "labels.app"
  - prefix: "oslogin"
    key: "metadata.enable-oslogin"
```

We end up with only one group: `tag_bastion`.

### AWX version

19.3.0 

### Installation method

kubernetes

### Modifications

no

### Ansible version

Unsure

### Operating system

containeros

### Web browser

Firefox, Chrome

### Steps to reproduce

* Create a GCP backed inventory
* Configure keyed groups as above using metadata

### Expected results

Two groups:

```
tag_bastion
oslogin_TRUE
```

### Actual results

One group:

```
tag_bastion
```

**Comment by chrismeyersfsu** [comment]
@bschaeffer if you run this outside of AWX, what do you get? i.e. https://docs.ansible.com/ansible/latest/plugins/inventory.html#using-inventory-plugins

**Comment by shanemcd** [comment]
Closing due to lack of response. To me, this sounds like a problem with the plugin, which is not built-in to AWX. If you get around to doing what we asked for in the last comment and have reason to believe otherwise, please open a new issue.
