### ISSUE TITLE
Cancelling updates to an existing NEW survey prompt for a new job template goes back to the Template entry screen instead of the Add Survey screen

### ISSUE THREAD

**Issue by suchko** [ansible/awx#11298]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Cancelling updates to an existing NEW survey prompt for a new job template goes back to the Template entry screen instead of the Add Survey screen

### AWX version

Tower 3.7.5

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.6.4

### Operating system

RHEL 7.7 (3.10.0-1062.18.1.EL7.X86_64)

### Web browser

Chrome

### Steps to reproduce

1. Add new job template.
2. Enter all required fields so template can be saved (values do not matter).
3. Click blue "ADD SURVEY" button.
4. Enter survey prompts (values do not matter).
5. Click green "ADD" button.
6. Under PREVIEW, click PENCIL icon to edit survey prompt which was just entered (I was doing it to confirm values)
7. Click CANCEL button to cancel edit of current survey prompt.

### Expected results

I expected to return to EDIT screen from which Edit Survey Prompt was launched and with the single prompts prior state preserved.

### Actual results

It returns to ADD TEMPLATE SCREEN and loses the newly added survey prompt entirely.

**Comment by mabashian** [comment]
Hello,

This issue tracker is for the open source Ansible AWX project. If you've got questions or a support issue with Ansible Tower, please reach out directly to Red Hat.

As of AWX 16.0 the UI has been overhauled and the flow that you describe is quite different.
