### ISSUE TITLE
couldn't resolve bigip modules

### ISSUE THREAD

**Issue by navianmik** [ansible/awx#11292]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

same playbook runs well on awx 17.1 ansible 2.9.1
multiple f5/bigip impacted

### AWX version

19.3

### Installation method

minikube

### Modifications

no

### Ansible version

2.9

### Operating system

ubuntu 20.04

### Web browser

Chrome

### Steps to reproduce

launch playbook w/ bigip_* modules 

### Expected results

 modules are resolved

### Actual results

redirecting (type: modules) ansible.builtin.bigip_profile_client_ssl to f5networks.f5_modules.bigip_profile_client_ssl
ERROR! couldn't resolve module/action 'bigip_profile_client_ssl'. This often indicates a misspelling, missing collection, or incorrect module path.

**Comment by shanemcd** [comment]
Hello. It seems like you are depending on something that used to be provided by a previous version of Ansible. You'll probably want to build your own EE. Please see the docs for ansible-builder, and/or contact the AWX mailing list.

**Comment by arghab4481** [comment]
I am also facing the same problem, the only difference in INFRA for my case if i am using awx in Azure
