### ISSUE TITLE
Trying to SSH into the pod/container hosting the AWX  application

### ISSUE THREAD

**Issue by cira-jonathan** [ansible/awx#11299]
##### COMPONENT NAME

- Server

##### SUMMARY
I'm trying to access the folder the directory as to where all the job templates and project files are downloaded to when I run jobs on my AWX server.

In my job log I keep seeing this location mentioned  (/runner/project/roles) but when I log into my server it doesn't exist. 

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: operator
* AWX deployment target:  minikube
* Operating System: RHEL 7

##### STEPS TO REPRODUCE

1 - [awx@crp-awx-01 ~]$ kubectl get pods
NAME                            READY   STATUS    RESTARTS   AGE
awx-5b58db49c-8d5n9             4/4     Running   44         175d
awx-operator-5595d6fc57-7fqxh   1/1     Running   13         175d
awx-postgres-0                  1/1     Running   12         175d
dnstools

2 -  kubectl exec -it awx-5b58db49c-8d5n9 -- /bin/bash
3 - browse to /runner (doesn't exist), /var/lib/awx (doesn't exist)

**Comment by federico-manuel-trasande-kyndryl** [comment]
Hi,
 Did you tried `kubectl exec -it awx-5b58db49c-8d5n9 -c awx-ee -- /bin/bash` ?

By default, for me at least, if I don't specify which container, goes into "redis".

Regards,

**Comment by cira-jonathan** [comment]
I was missing the container flag. Thanks for the help :)
