### ISSUE TITLE
Feature idea: run project checkouts on all nodes

### ISSUE THREAD

**Issue by grahamneville** [ansible/awx#1129]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Have the option to select if a job template performs an SCM checkout/update. This can significantly reduce the amount of time it takes to run each job. It also means that jobs don't need to queue if they are using the same project.

##### ENVIRONMENT
* AWX version: X.Y.Z

##### STEPS TO REPRODUCE

When a project is added first time it downloads from source control, at that point all the source control files exist on the filesystem. A job template is then created and points to the playbooks on the filesystem. Could we not then be able to choose if we update the project on each job run? If we choose not to then it just uses the files downloaded earlier from the project setup?

If there are multiple AWX nodes then could there be a process that runs on project add/update that forces the other nodes to also perform and download/update? This will keep things in sync.

**Comment by wenottingham** [comment]
As noted, we wouldn't make this an option, as it just gives a checkbox that can immediately break execution.  

The better avenue, if we go down this road, is to consider fanout of project updates. Updating title accordingly.

**Comment by wenottingham** [comment]
Would involve:
- moving project checkout to a fanout task
- distributing it to nodes
- handling individual node failures
- what does this mean for newly provisioned nodes and/or nodes that were offline while updates happened

**Comment by AlanCoding** [comment]
Discussion overlaps with what's in #289

**Comment by jaredevantabor** [comment]
@wenottingham @AlanCoding are you cool w/ closing this since there is discussion in 289?

**Comment by wenottingham** [comment]
Yeah, I just missed that. Closing as duplicate.
