### ISSUE TITLE
awx cli user gives "The requested resource could not be found."

### ISSUE THREAD

**Issue by tonk** [ansible/awx#11296]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

In awx-cli version 3.8.4 with Ansible AWX 0.19.4 I issue the command

```
awx --conf.token <token> --conf.host=https://aaa.aaa.nl -k user list
```
the result is:

```
"The requested resource could not be found."
```

Whatever I try to do with the `user` resource, all commands end with the "unfound resource"

### AWX version

0.19.4

### Installation method

kubernetes

### Modifications

no

### Ansible version

Ansible 4.7.0

### Operating system

CentOS 8

### Web browser

Firefox

### Steps to reproduce

- Install AWX in K8s through the Ansible AWX operator 0.14.0
- Install Ansible (`pip3 install ansible`)
- Install the awx cli
- Login to AWX with the CLI
- Get the user list `awx user list`

### Expected results

A list if all configured users in AWX

### Actual results

```
{"detail": "The requested resource could not be found."}
```

**Comment by chrismeyersfsu** [comment]
@tonk `user` is plural `users`. By specifying `user` I _think_ that will request `/api/v2/users/?username=list` Check the nginx logs to see what request it issues or put a proxy between the client to see, or try with `-v` and include the logs.
