### ISSUE TITLE
Ansible LVM module issue

### ISSUE THREAD

**Issue by cira-jonathan** [ansible/awx#11305]
##### SUMMARY
I'm having an issue with an ansible module, specifically the LVM module (lvol). When I execute my Ansible code from my local system everythinig works according but when I try it from an AWX job template I get the following error:

"reason": "couldn't resolve module/action 'lvol'. This often indicates a misspelling, missing collection, or incorrect module path.\n\nThe error appears to be in '/runner/project/roles/base-linux/tasks/lvm.yml': line 11, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Extend the LV\n ^ here\n"

This is the specific code I'm trying to execute...

- name: Resize sda
  command: /usr/sbin/parted /dev/sda resizepart 2 100%

- name: Resize PV
  command: /usr/sbin/pvresize /dev/sda2

- debug:
    var: ansible_lvm

- name: Extend the LV
  lvol:
    vg: "{{ ansible_lvm['lvs']['root'].vg }}"
    lv: root
    size: 100%VG
    resizefs: true
  ignore_errors: yes

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: operator
* AWX deployment target:  minikube
* Operating System: RHEL 7

**Comment by ffirg** [comment]
Please consult the google groups mailing lists for such errors. That is where you can post such queries. Thanks.
