### ISSUE TITLE
ERROR! the role ROLE_NAME was not found in PATH when executing template

### ISSUE THREAD

**Issue by federico-manuel-trasande-kyndryl** [ansible/awx#11302]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

1. Created a project from a git repo with my playbooks and roles, with the standard directory tree:
```
playbooks/
    |_ my_playbook1.yml
    |_ my_playbook2.yml
roles/
    |_ my_role1/
    |_ my_role2/
```

my_playbook1.yml content:
```
---
# my_playbook1.yml

- name: Execute my_role1
  hosts: "localhost"
  gather_facts: no
  become: no
  roles:
    - role: my_role1
```

2. Created a template to execute "my_playbook1.yml".
3. Run the template on "AWX-EE (latest)" and "Control plane" execution environments.
4. Both fails with error:
```
ERROR! the role 'my_role1' was not found in /runner/project/playbooks/roles:/runner/requirements_roles:/home/runner/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/runner/project/playbooks
```
5. Also created a custom EE image with ansible.cfg copied into "/etc/ansible/ansible.cfg" with the same result.
```
[defaults]
roles_path = ~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:roles/
```
6. The only way to make it work is to copy the ansible.cfg on the project local folder on AWX pod "/var/lib/awx/projects/my_proyect_folder/", which seems kind of not the cleanest option.

### AWX version

AWX 19.4.0

### Installation method

kubernetes

### Modifications

no

### Ansible version

ansible [core 2.11.6.post0]

### Operating system

CentOS Linux release 8.4.2105

### Web browser

Safari

### Steps to reproduce

1. Create project from a git repository with the standard directory distribution as in "/usr/share/ansible" for a standalone environment.
```
playbooks/
  |_ my_playbook1.yml
roles/
  |_ my_role1/
```
2. Create a template for a playbook that uses a role from "roles" path.
3. Execute the template.

### Expected results

The playbook executes and the role is found.

### Actual results

The role can't be found at runtime.

### Additional information

The only way to make it work is to copy the ansible.cfg on the project local folder on AWX pod "/var/lib/awx/projects/my_proyect_folder/", which seems kind of not the cleanest option.

So what I'm missing config wise to make the playbooks execute from an EE as if I was running it like a standalone ansible installation. The EE setup documentation mentions ansible.cfg but only for building stage.

**Comment by federico-manuel-trasande-kyndryl** [comment]
Well, 

 After try and error, found a solution. Injecting ANSIBLE_ROLES_PATH variable into my custom EE image did the trick.

**Comment by sghosh29** [comment]
@FedeHAL : can you please share how you injecting  ANSIBLE_ROLES_PATH variable into my custom EE image, i am facing the same issue .
