### ISSUE TITLE
Jobs page Filtering by status should be OR operator

### ISSUE THREAD

**Issue by fosterseth** [ansible/awx#11309]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

![image](https://user-images.githubusercontent.com/8745776/140397002-975faa7e-b685-4bf8-a184-449b8b3a2979.png)

This is the job status page. Since jobs only have 1 status, then checking more than 1 should do an OR operator, instead of AND

the following API hit should work
```
/api/v2/unified_jobs/?not__launch_type=sync&order_by=-finished&page=1&page_size=20&or__status=failed&or__status=error
```

### AWX version

current

### Installation method

docker on linux

### Modifications

no

### Steps to reproduce

run jobs, to go Jobs page, and try to filter on more than one Status (e.g. pending and running)

### Expected results

both pending and running jobs should show

### Actual results

no jobs show

**Comment by rebeccahhh** [comment]
Acceptance criteria: in the UI when filtering based on more than one status, both statuses show up in the results
