### ISSUE TITLE
galaxy awx collection awx.awx.job_template module errors when using Labels parameter

### ISSUE THREAD

**Issue by bonzaii** [ansible/awx#11319]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Hi!
As the title explains, using "labels" parameter of "awx.awx.job_template" module causes an error.

### AWX version

N/A

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.11.6

### Operating system

Ubuntu 21.10

### Steps to reproduce

Install fresh Ansible Tower 3.8.4
Create any project
Create any inventory (empty inventory will work)
Make sure to sync project & ensure project has site.yml file in root
Install Ansible CLI 
Install awx.awx 19.4.0 collection from ansible-galaxy (including requirements.yml)

Configure admin credential on Tower and use either prompts or environmental variables to pass those credentials to below playbook:

```
---
- name: "Testing awx.awx.job_template Labels bug"
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: toweruser
      prompt: "Enter Tower admin username (default: admin)"
      default: "admin"
      private: no
    - name: towerpass
      prompt: "Enter Tower admin password"
      unsafe: yes
      private: yes
    - name: towerfqdn
      prompt: "Enter Tower FQDN"
      default: "localhost"
      private: no

  tasks:
  - name: "Testing with Tower"
    awx.awx.job_template:
      name: "[BUG293] Test template"
      project: "MyProject"
      playbook: "site.yml"
      inventory: "MyInventory"
      labels:
        - "test"

      validate_certs: no
      controller_host: "{{ lookup('env', 'TOWER_HOST') | default(towerhost) }}"
      controller_username: "{{ lookup('env', 'TOWER_USERNAME') | default(toweruser) }}"
      controller_password: "{{ lookup('env', 'TOWER_PASSWORD') | default(towerpass) }}"
```

Run playbook:
`ansible-playbook --limit localhost playbook.yml`

### Expected results

I expect the playbook to create a job_template with the following parameters:
name: "[BUG293] Test template"
project: "MyProject"
playbook: "site.yml"
inventory: "MyInventory"
labels: [ test ]

### Actual results

```
─$ ansible-playbook --limit localhost bug293.yml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
[WARNING]: packaging Python module unavailable; unable to validate collection Ansible version requirements
Enter Tower admin username (default: admin) [admin]: 
Enter Tower admin password: 
Enter Tower FQDN [localhost]: 

PLAY [Testing awx.awx.job_template Labels bug] *****************************************************************************************************************************************************************

TASK [Testing with Tower] **************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not subscriptable
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/xxx/.ansible/tmp/ansible-tmp-1636464525.7953029-15125-197763395320162/AnsiballZ_job_template.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/home/xxx/.ansible/tmp/ansible-tmp-1636464525.7953029-15125-197763395320162/AnsiballZ_job_template.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/xxx/.ansible/tmp/ansible-tmp-1636464525.7953029-15125-197763395320162/AnsiballZ_job_template.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.awx.awx.plugins.modules.job_template', init_globals=dict(_module_fqn='ansible_collections.awx.awx.plugins.modules.job_template', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_awx.awx.job_template_payload_z7lxfqwz/ansible_awx.awx.job_template_payload.zip/ansible_collections/awx/awx/plugins/modules/job_template.py\", line 593, in <module>\n  File \"/tmp/ansible_awx.awx.job_template_payload_z7lxfqwz/ansible_awx.awx.job_template_payload.zip/ansible_collections/awx/awx/plugins/modules/job_template.py\", line 541, in main\nTypeError: 'NoneType' object is not subscriptable\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *****************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

### Additional information

The above playbook works if I remove "labels" parameter.

**Comment by AlanCoding** [comment]
Looks legitimate

https://github.com/ansible/awx/blob/0ae67edaba5930d91b85e1b0c22c0d82c240f99f/awx_collection/plugins/modules/job_template.py#L540-L541

The `get_one` method seems to clearly allow returning `None`

https://github.com/ansible/awx/blob/0ae67edaba5930d91b85e1b0c22c0d82c240f99f/awx_collection/plugins/module_utils/controller_api.py#L418-L420

which would be in the obvious situation that the name did not hit a match.

For your situation, it looks like it can't find the "test" label for whatever reason. Permissions? I don't know.

We need to fix the handling of this situation on the collection side.

**Comment by bonzaii** [comment]
> For your situation, it looks like it can't find the "test" label for whatever reason. Permissions? I don't know.

It shouldn't be a problem since the sole job of the "labels" parameter in the module is to apply list of strings (not references) to the job template. As far as I understand, label, unlike tag, has no function other than organizational aspect. Looking at description of a label in tower:
> **LABELS**
> Optional labels that describe this job template, such as 'dev' or 'test'. Labels can be used to group and filter job templates and completed jobs.

The way I understand, I could put "ThisIsVeryUnhelpfulLabelThatDoesNotExistAnywhere" in there and this still should not fail, but I am happy to be corrected if my understanding is flawed?

**Comment by AlanCoding** [comment]
IIRC, there is a label module in this collection, so the idea is that you would drop a task in before the job_template task that creates a label with that name.

**Comment by bonzaii** [comment]
If you're referring to `awx.awx.label` then I don't believe this module has anything to do with `job_template` `labels`. Also when I discovered this issue, I had plenty of other job_templates configured and using labels `prod` and `snow` already, which were the labels causing my the original pain, before I trimmed this to MVP for bug reproduction purposes.

**Comment by sean-m-sullivan** [comment]
@bonzaii The 'awx.awx.labal' has Everything to do with the 'job_template' 'labels'. 

Labels are an object in tower. Just like you Cannot add a credential to a job template, where that credential doesn't exist. You cannot add a label to a job template where that label doesn't exist. 

I think that the error can be updated to be more clear in that regard, but this is how the underlying tower works. 

In the GUI this is all done under the hood when you add a label in a job template, it creates an object in api/v2/labels/, but we have to be a little more methodical when using the API directly.

**Comment by bonzaii** [comment]
I see. That makes sense. I guess it would be good idea to update the [documentation](https://docs.ansible.com/ansible/latest/collections/awx/awx/job_template_module.html) to reflect this too.

**Comment by sean-m-sullivan** [comment]
@bonzaii I just did a PR to improve the error and documentation to make it so this is more clear in the future.

**Comment by shanemcd** [comment]
The PR above got merged and even includes tests. Going to close this.
