### ISSUE TITLE
Add details about node on workflow addition

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#11325]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add details about node on workflow addition. On the old UI we had: 
<img width="490" alt="image" src="https://user-images.githubusercontent.com/9053044/140982697-ea613dc9-a3c8-40f4-8efe-9b149bcc9f16.png">

**Comment by InnocentK** [comment]
Feature has been added and issue resolved.
