### ISSUE TITLE
build docker release for docker-compose and other like

### ISSUE THREAD

**Issue by pythonwood** [ansible/awx#11331]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Use AWX for 1.5 year and it free my hands a lot. 

awx is a devops tool and not high available need for me. so i hope to run with docker-compose.yml simple. 
althought I am  k8s sre and use minikube easylly and powerfully.

**Comment by chrismeyersfsu** [comment]
We only have so many resources and supporting another deployment method uses a lot of those resources. We don't have plans to go back to supporting `docker-compose.yml`

**Comment by Rylon** [comment]
@chrismeyersfsu would you at least consider publishing the Docker images to a registry so others could make use of them via Compose, or other mechanism?

**Comment by chrismeyersfsu** [comment]
@Rylon the images are built and published here https://quay.io/repository/ansible/awx?tab=tags
