### ISSUE TITLE
Allow awx.awx.controller to give back hosts only without any extra data

### ISSUE THREAD

**Issue by HOSTED-POWER** [ansible/awx#11340]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Hi,

We want to use awx.awx.controller to get all hosts in an inventory and afterwards we want to enrich this data with other inventory sources and the constructed plugin. Unfortunately there is no way to only get the hosts without any host variables. 

Because of this, variables will always be returned and there is no way to remove "old" variables no longer belonging there which are previously enriched by the other inventory plugins.

Proposal: Add option to output only the hosts without any variables

**Comment by chrismeyersfsu** [comment]
@HOSTED-POWER are you wanting something kind of like `ansible-inventory source1 source2` where `source2` would get all the "output" from `source1` ?

**Comment by shanemcd** [comment]
Hello. After discussing with the team, this doesn't seem to fit the existing patterns used in the inventory plugin ecosystem. If you need help troubleshooting or are looking for help using AWX, try our mailing list or IRC channel:

#ansible-awx on https://libera.chat/
https://groups.google.com/forum/#!forum/awx-project
