### ISSUE TITLE
UI improvements to make changes more easy to look for

### ISSUE THREAD

**Issue by anlutro** [ansible/awx#1134]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
I think that being able to look for changes in your infrastructure is a top priority when it comes to configuration management.

If something's behaving differently today compared to yesterday, it would be very interesting to quickly find out if any scheduled Ansible plays made changes in the last 12-24 hours, for example. You could also correlate changes in infrastructure to metrics/statistics, to check if rolling out new configuration made an impact on performance or not, for example. Being able to do this retroactively instead of having an operator ready to hit the deploy button with the graphs on the second monitor makes life more comfortable.

Furthermore, seeing a large number of changes can be a good way of spotting configuration drift or lack of idempotency. Changes are expected when you're git pushing a new feature or fix, but unexpected changes can be something you might want to investigate, and plays that keep on reporting changes all the time might have a bug in them, or might conflict with anoter play.

Currently, it's tedious to find out if a job caused any changes on any of your hosts. It's possible through the API because you can filter on `event__changed`, but it's impossible in the traditional web UI - you basically have to click on each individual completed job and look at the summary to see if anything changed.

I have a few ideas on how changes could be added to the interface, but this is by no means an exhaustive list:

- On the dashboard, add a yellow symbol to indicate that at least 1 host reported changes from the job. Change the green symbol to mean "no changes".
- On the dashboard, show the number of "changed hosts" along with failed ones, to make it easy to spot when a play isn't idempotent or something is causing configuration drift.
- When listing completed jobs, add a column that specifies the number of hosts that had changes from this job.
- Add a checkbox in the list of completed jobs to only show jobs where something changed.

I also think that it would be a great idea if you could filter tasks when viewing the output of a single job/play, so that you can, only show tasks that made changes. Alternatively, making tasks that made no changes a light shade of grey instead of green/black, so it's easier to scroll through a play's output to spot tasks that have made changes.

**Comment by jakemcdermott** [comment]
Most of these use cases are covered by the external logging feature and system tracking. Have a look the tower docs to see what these are all about.

If you have any questions please drop us a line on the awx mailing list or stop by the awx irc channel on freenode. Thanks!
