### ISSUE TITLE
AWX Isolated node status check fail when node goes down.

### ISSUE THREAD

**Issue by rfarajro** [ansible/awx#11343]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

AWX Isolated node status check fail when node goes down.

### AWX version

17.1.0

### Installation method

openshift

### Modifications

no

### Ansible version

2.9.18

### Web browser

Chrome

### Steps to reproduce

When multiple isolated nodes are added to a queue and one of the nodes goes down, AWX continues to send jobs to that node and does not mark it as unreachable.

### Expected results

When the isolated node falls it should mark it as unreachable.

### Actual results

Add multiple isolated nodes and turn off the node.

**Comment by chrismeyersfsu** [comment]
This feature was never designed to be used in the scenario you are using it in i.e. control node in the container platform and iso node outside of the container platform.
