### ISSUE TITLE
GCP Credential does not provide extra var

### ISSUE THREAD

**Issue by mdujard1** [ansible/awx#11363]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Hello all,
We are trying to manage some action on our GCP instances like updating / deleting / adding GCE labels.
Therefore we need to authenticate at GCP with a service account.
So we use the GCP credential type provided by this stack.
But we are unable to retrieve value of variable defined in 
https://github.com/ansible/awx/blob/devel/awx/main/models/credential/injectors.py
like GCE_CREDENTIALS_FILE_PATH / GCP_SERVICE_ACCOUNT_FILE.
Is this a normal behaviour ? is there a way to retrieve them ?
Thanks,
Max

### AWX version

19.2.2

### Installation method

minikube

### Modifications

no

### Ansible version

2.11.4

### Operating system

Redhat

### Web browser

Firefox, Chrome, Safari, Edge

### Steps to reproduce

- Add GCP Credential to job template
- Fetch the variable into the playbook :

- name: "Ansible | Print a variable if defined"
  debug:
    msg: "The 'GCP_SERVICE_ACCOUNT_FILE' variable value is {{ GCP_SERVICE_ACCOUNT_FILE }}"
  when: GCP_SERVICE_ACCOUNT_FILE is defined

- name: "Ansible | Print a message if a variable is undefined"
  debug:
    msg: "The 'GCP_SERVICE_ACCOUNT_FILE' variable is undefined"
  when: GCP_SERVICE_ACCOUNT_FILE is not defined

### Expected results

Variable should be defined and give the good value to authenticate to GCP API.

### Actual results

Variable not defined.

**Comment by AlanCoding** [comment]
Is the issue just about environment variables versus extra vars? I you need the value in a playbook variable, then you could `set_fact`, using the env lookup plugin:

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/env_lookup.html

While it is possible to modify the injector to also put them in as extra_vars, this needs a lot of thought and collaboration with the content maintainers so that we adhere to the intended use cases.

**Comment by mdujard1** [comment]
Hello Alan,
That's all I wanted. I found how to fetch the needed values directly in the env of the executing pod.
Thanks a lot !
