### ISSUE TITLE
Job Output window is not updating to show play recap

### ISSUE THREAD

**Issue by IPvSean** [ansible/awx#11361]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

There is some issue with AAP 2.X with the DOM not being updated with the entire Ansible Playbook output... the job is finished but the play recap is not there->
![image](https://user-images.githubusercontent.com/6537680/142238029-c74d2316-b0db-49b4-9a4e-e11afd2769c7.png)

however if I go to Jobs-> and back to the same Job
![image](https://user-images.githubusercontent.com/6537680/142238964-10aa894f-c74b-4eb6-b487-3fa0db153c43.png)

the PLAY RECAP is shown, there is some issue with updates... this reliable happens in Automation controller for GLS learning classes

here is the version, this is AAP, not awx
![image](https://user-images.githubusercontent.com/6537680/142238911-25ca87e0-a3d1-4055-b181-87d65761b77c.png)

### AWX version

AAP 4.0.0 (from about window) Automation controller

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.11

### Operating system

RHEL 8.5

### Web browser

Firefox

### Steps to reproduce

just run any GLS lab that @jmighion @bonnevil

### Expected results

The entire Ansible Playbook output would be available to the user on the completion of a job

### Actual results

the Job Output window is not updated fully

### Additional information

This is part of course DO374 for GLS teaching advance automation, would be great to fix this error so students don't experience it

**Comment by nixocio** [comment]
There is a major re-factoring being done on this screen.  See: https://github.com/ansible/awx/pull/11312

**Comment by keithjgrant** [comment]
This issue has been partially mitigated with #11312 and #11670 but not entirely solved.

Further work is being tracked in #11424, so I'm closing this in favor of that issue.
