### ISSUE TITLE
Passing Source Variables to Inventory Script not working

### ISSUE THREAD

**Issue by jpc2350** [ansible/awx#1137]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

When using an Inventory Source (tested on Custom/EC2 Inventory Scripts), providing a custom environment variable through the UI doesn't get used when the script runs. For example:
Using EC2 Inventory Source, set envrionment variables `iam_role: <role_arn>` doesn't actually get passed to the script.

##### ENVIRONMENT
* AWX version: 1.0.3.5
* AWX install method: minishift
* Ansible version:  2.4.2.0
* Operating System: MacOS
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Login on UI, Inventories > Add > Fill out the primary details > Save > Sources > Add Source > name: test-ec2, Source: Amazon EC2, Select AWS creds, Select Region (eu-west-1), Blank Instance Filters, Blank Group By, Debug > Set Source Variables: iam_role:  <an IAM role>,  vpc_destination_variable: private_ip_address > Save
Run Inventory Sync (which fails)

##### EXPECTED RESULTS

Inventory Source to succeed and retrieve AWS Information

##### ACTUAL RESULTS

Failed with error: ERROR: "Error connecting to AWS backend."
Debug provides more output - ERROR: "Error connecting to AWS backend. Operation not permitted" 

Yet running the script from desktop (same ec2.py script) with ec2.ini and the same options set, works correctly.

My current work around requires me to copy the script for every iam_role change, and create a custom inventory script, placing the source variables directly into the file and not passing in any source variables through the UI

##### ADDITIONAL INFORMATION

<img width="1422" alt="screen shot 2018-02-06 at 11 03 48" src="https://user-images.githubusercontent.com/23191993/35856297-82a2861e-0b2d-11e8-86bb-6a35829fc84b.png">
<img width="1432" alt="screen shot 2018-02-06 at 11 05 11" src="https://user-images.githubusercontent.com/23191993/35856354-adb8624c-0b2d-11e8-851c-113d28dea2ef.png">

**Comment by jaredevantabor** [comment]
@jpc2350 to assist in triaging this, could you confirm that the source variables are getting included in the POST to the API? You can find this by opening your web console and going to the Network tab, and scrolling until you find a similar request like the one below: 
![image](https://user-images.githubusercontent.com/7010629/35995602-c070aca4-0cc8-11e8-9fd2-511c139c940f.png)


![image](https://user-images.githubusercontent.com/7010629/35995607-c4987c26-0cc8-11e8-8f01-62994a7fd4e5.png)

When I tested locally, the source vars are getting POST'd correctly, I believe there is either an issue with the inventory script, or possibly the AWX API.

**Comment by jaredevantabor** [comment]
@ryanpetrello @matburt does anything in this traceback suggest to you what could have caused this error?

**Comment by jpc2350** [comment]
Hi @jaredevantabor,

So I can see them getting posted to the API (as below) when saving:

![screen shot 2018-02-09 at 11 14 45 2](https://user-images.githubusercontent.com/23191993/36025418-defd3ad0-0d8a-11e8-948e-4d2313782be2.png)
![screen shot 2018-02-09 at 11 15 01 2](https://user-images.githubusercontent.com/23191993/36025562-654d80cc-0d8b-11e8-98c1-f3cf4dd68819.png)

And when trying to run inventory they also get posted to the API:

<img width="956" alt="screen shot 2018-02-09 at 11 24 34" src="https://user-images.githubusercontent.com/23191993/36025739-0e08b6aa-0d8c-11e8-89fb-7688ff648996.png">

But it comes back as failed.....

**Comment by jpc2350** [comment]
![screen shot 2018-02-09 at 11 37 20](https://user-images.githubusercontent.com/23191993/36026145-b4ce942c-0d8d-11e8-903f-a2800b517dd5.png)

**Comment by matburt** [comment]
Not sure what's going on here. I'd like to see the ini file generated by the AWX job if you can grab it during the job run. Otherwise this might take us a while before we can circle back around to it.

**Comment by christoph-kluge** [comment]
@jpc2350 I'm evaluating AWX right now for one of my clients and found your issue because I was searching for a way how to add ec2.ini settings into the AWX Inventory. Thanks for pointing me to this :)

Anyway I've tested your example and it worked for me. I'm am using AWX 1.0.3.58.

**Comment by jpc2350** [comment]
Hi @matburt, I'm just circling back around to this myself - How would I find where the INI file for the job is?

**Comment by wenottingham** [comment]
@jpc2350 that's generated by AWX itself for the job (and cleaned up afterwards). See the logic in awx/main/tasks.py.

**Comment by matburt** [comment]
No follow up in several months
