### ISSUE TITLE
How can I access the temp hosts/groups created by add_host in previous jobs within a workflow?

### ISSUE THREAD

**Issue by tumluliu** [ansible/awx#1138]
##### ISSUE TYPE

 - Usage question

##### COMPONENT NAME

 - API
 - UI

##### ENVIRONMENT
* AWX version: 1.0.3
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: Linux 3.10.0-693.2.2.el7.x86_64
* Web Browser: Google Chrome 63

##### STEPS TO REPRODUCE

First, import an existing Ansible project from git, where a couple of playbooks and an inventory file are already there. Then created a workflow template composed of three job templates each of which was created according to a playbook respectively. For simplicity, l take only two jobs for example:

1. Create an Azure VM
2. Install some softwares on the created VM

The last task in the first job is adding the created VM's ip address into a temporary group with the ansible module `add_host`. However, this newly added VM can not be seen in the second job. So I get a `[WARNING]: Could not match supplied host pattern, ignoring: da23334a-63cb-40c3
-b0eb-2bf0f8cbe892` where the uuid is the temp group name. 

Such issue won't happen if I combine the two jobs into a single playbook and run it in awx. So I guess the `add_host`'s result doesn't propagate to the subsequent jobs. Besides this, I found that it's also impossible to use `hostvars['PREVIOUS_HOST']` in the subsequent jobs. So my question is: what is the `add_host` result's scope? How can I access the variables in a whole workflow?

##### EXPECTED RESULTS

Let `add_host` result visible in subsequent jobs in a workflow.

##### ACTUAL RESULTS

`add_host` can only work within a playbook/job template.

Many thanks.

**Comment by wenottingham** [comment]
This is intentional.

Either post it to the actual inventory API (see http://docs.ansible.com/ansible/latest/tower_host_module.html), or schedule an inventory sync.
