### ISSUE TITLE
AWX - Missing backend "saml" entry

### ISSUE THREAD

**Issue by rfarajro** [ansible/awx#11382]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Hello,

  When SSO SAM is configured, the error "Missing backend" saml "entry" is obtained. 

I have tried setting it up with AWX versions 14, 17 and 19 and the result is the same error.

### AWX version

19.5.0

### Installation method

minikube

### Modifications

no

### Steps to reproduce

 Configure SAML settings.

### Expected results

 Load SAML backend module.

### Actual results

Missing backend" saml "entry.

 No bakend SAML active:

    "AUTHENTICATION_BACKENDS": [
        "awx.sso.backends.TACACSPlusBackend",
        "awx.main.backends.AWXModelBackend"
    ],

### Additional information

 Here are my SAML configuration:

HTTP 200 OK
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
X-API-Node: awx-demo-786447d7bc-zxr27
X-API-Product-Name: AWX
X-API-Product-Version: 19.5.0
X-API-Time: 0.009s

{
    "SAML_AUTO_CREATE_OBJECTS": false,
    "SOCIAL_AUTH_SAML_CALLBACK_URL": "https://awx-test.telcolab.local/sso/complete/saml/",
    "SOCIAL_AUTH_SAML_METADATA_URL": "https://awx-test.telcolab.local/sso/metadata/saml/",
    "SOCIAL_AUTH_SAML_SP_ENTITY_ID": "https://awx-test.telcolab.local",
    "SOCIAL_AUTH_SAML_SP_PUBLIC_CERT": "-----BEGIN CERTIFICATE-----\nMIIDyTCCArGgAwIBAgIUZoyeh0SEifn+TBu6IZPESQkVq+MwDQYJKoZIhvcNAQEL\nBQAwdDELMAkGA1UEBhMCRVMxDzANBgNVBAgMBk1hZHJpZDEPMA0GA1UEBwwGTWFk\ncmlkMSEwHwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQxIDAeBgNVBAMM\nF2F3eC10ZXN0LnRlbGNvbGFiLmxvY2FsMB4XDTIxMTEyMjE2MjI0OFoXDTIyMTEy\nMjE2MjI0OFowdDELMAkGA1UEBhMCRVMxDzANBgNVBAgMBk1hZHJpZDEPMA0GA1UE\nBwwGTWFkcmlkMSEwHwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQxIDAe\nBgNVBAMMF2F3eC10ZXN0LnRlbGNvbGFiLmxvY2FsMIIBIjANBgkqhkiG9w0BAQEF\nAAOCAQ8AMIIBCgKCAQEAsYTbDcxlHjDAyjcesRAi00W+bIUav3wFFx7bGSFKadEi\nzZmpS8xJs69p++AHIpJCltRkOIE3J063lBQbojtLVtp5VE6xNNxj6m12f6lxNb9W\nnd1tlfe26tt0NbJSN8DEuFxu1g+9r2BNl29h0C/9+sacbEKn2BLy07k3GO3fDZs/\np6Z2/psKud89jMTQB+33urz6o4G8o8BB4RLG4cU+/qLNpuQjsiNfgN19vHHSoQ+i\ndXZp6ep1mY7VYJc1DWBT21DODeIuElJIjCnRvjsAVuSH+yjTUesWQhNZCgryUBSG\n6xknfeYfKhGAhfh/0Pyxjj2SDZ1ZTfwYs6CV2JLb/QIDAQABo1MwUTAdBgNVHQ4E\nFgQUSWIx9i0Ux/Zzp+bG1Wpbf40c2JwwHwYDVR0jBBgwFoAUSWIx9i0Ux/Zzp+bG\n1Wpbf40c2JwwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAUQ3v\nxktXuBrxNgVGl0jyct3Te1B3NP/s2wmRbqazaySuIQP2JFn7i1cJ9vU1E8/RKlDc\n8K/cnmvBO0GsdAHJ7kNGEq1ub0uUK5MwBaxjxeJJNy21W5NSBEIqFxdCHZmpeTyz\nZ92/qsFVtNR2d54sf1lRm0S/X7RAueNPFW8k5iDox+g1dUtFcGIKnWsD0u8efg+3\ni+zTgLKUtCks6TfMNyyvpaQjlopDhUUbAdO2nWzY0wlwYqtgLMhnezW6X46S1og8\ncJMdYO5oTddDM9KcyNk2NkWGO6Noc7Iy+kcy0p9mRn/s87QQH2SYzs0HQpVNTDQ8\n3d5V6sPnYJBsb5Ndcw==\n-----END CERTIFICATE-----",
    "SOCIAL_AUTH_SAML_SP_PRIVATE_KEY": "$encrypted$",
    "SOCIAL_AUTH_SAML_ORG_INFO": {
        "es-ES": {
            "displayname": "AWX Ansible",
            "url": "https://awx-test.telcolab.local",
            "name": "awx-test"
        }
    },
    "SOCIAL_AUTH_SAML_TECHNICAL_CONTACT": {},
    "SOCIAL_AUTH_SAML_SUPPORT_CONTACT": {},
    "SOCIAL_AUTH_SAML_ENABLED_IDPS": {
        "idp": {
            "entity_id": "http://192.168.98.180:8080/simplesaml/saml2/idp/metadata.php",
            "x509cert": "MIICmjCCAYICCQDX5sKPsYV3+jANBgkqhkiG9w0BAQsFADAPMQ0wCwYDVQQDDAR0ZXN0MB4XDTE5MTIyMzA5MDI1MVoXDTIwMDEyMjA5MDI1MVowDzENMAsGA1UEAwwEdGVzdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMdtDJ278DQTp84O5Nq5F8s5YOR34GFOGI2Swb/3pU7X7918lVljiKv7WVM65S59nJSyXV+fa15qoXLfsdRnq3yw0hTSTs2YDX+jl98kK3ksk3rROfYh1LIgByj4/4NeNpExgeB6rQk5Ay7YS+ARmMzEjXa0favHxu5BOdB2y6WvRQyjPS2lirT/PKWBZc04QZepsZ56+W7bd557tdedcYdY/nKI1qmSQClG2qgslzgqFOv1KCOw43a3mcK/TiiD8IXyLMJNC6OFW3xTL/BG6SOZ3dQ9rjQOBga+6GIaQsDjC4Xp7Kx+FkSvgaw0sJV8gt1mlZy+27Sza6d+hHD2pWECAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAm2fk1+gd08FQxK7TL04O8EK1f0bzaGGUxWzlh98a3Dm8+OPhVQRi/KLsFHliLC86lsZQKunYdDB+qd0KUk2oqDG6tstG/htmRYD/S/jNmt8gyPAVi11dHUqW3IvQgJLwxZtoAv6PNs188hvT1WK3VWJ4YgFKYi5XQYnR5sv69Vsr91lYAxyrIlMKahjSW1jTD3ByRfAQghsSLk6fV0OyJHyhuF1TxOVBVf8XOdaqfmvD90JGIPGtfMLPUX4m35qaGAU48PwCL7L3cRHYs9wZWc0ifXZcBENLtHYCLi5txR8c5lyHB9d3AQHzKHMFNjLswn5HsckKg83RH7+eVqHqGw==",
            "attr_user_permanent_id": "name_id",
            "url": "http://192.168.98.180:8080/simplesaml/saml2/idp/SSOService.php"
        }
    },
    "SOCIAL_AUTH_SAML_SECURITY_CONFIG": {
        "requestedAuthnContext": false
    },
    "SOCIAL_AUTH_SAML_SP_EXTRA": null,
    "SOCIAL_AUTH_SAML_EXTRA_DATA": null,
    "SOCIAL_AUTH_SAML_ORGANIZATION_MAP": null,
    "SOCIAL_AUTH_SAML_TEAM_MAP": null,
    "SOCIAL_AUTH_SAML_ORGANIZATION_ATTR": {},
    "SOCIAL_AUTH_SAML_TEAM_ATTR": {}
}

 And my SAML metadata:

<?xml version="1.0"?>
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" entityID="http://192.168.98.180:8080/simplesaml/saml2/idp/metadata.php">
  <md:IDPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
    <md:KeyDescriptor use="signing">
      <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:X509Data>
          <ds:X509Certificate>MIICmjCCAYICCQDX5sKPsYV3+jANBgkqhkiG9w0BAQsFADAPMQ0wCwYDVQQDDAR0ZXN0MB4XDTE5MTIyMzA5MDI1MVoXDTIwMDEyMjA5MDI1MVowDzENMAsGA1UEAwwEdGVzdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMdtDJ278DQTp84O5Nq5F8s5YOR34GFOGI2Swb/3pU7X7918lVljiKv7WVM65S59nJSyXV+fa15qoXLfsdRnq3yw0hTSTs2YDX+jl98kK3ksk3rROfYh1LIgByj4/4NeNpExgeB6rQk5Ay7YS+ARmMzEjXa0favHxu5BOdB2y6WvRQyjPS2lirT/PKWBZc04QZepsZ56+W7bd557tdedcYdY/nKI1qmSQClG2qgslzgqFOv1KCOw43a3mcK/TiiD8IXyLMJNC6OFW3xTL/BG6SOZ3dQ9rjQOBga+6GIaQsDjC4Xp7Kx+FkSvgaw0sJV8gt1mlZy+27Sza6d+hHD2pWECAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAm2fk1+gd08FQxK7TL04O8EK1f0bzaGGUxWzlh98a3Dm8+OPhVQRi/KLsFHliLC86lsZQKunYdDB+qd0KUk2oqDG6tstG/htmRYD/S/jNmt8gyPAVi11dHUqW3IvQgJLwxZtoAv6PNs188hvT1WK3VWJ4YgFKYi5XQYnR5sv69Vsr91lYAxyrIlMKahjSW1jTD3ByRfAQghsSLk6fV0OyJHyhuF1TxOVBVf8XOdaqfmvD90JGIPGtfMLPUX4m35qaGAU48PwCL7L3cRHYs9wZWc0ifXZcBENLtHYCLi5txR8c5lyHB9d3AQHzKHMFNjLswn5HsckKg83RH7+eVqHqGw==</ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
    </md:KeyDescriptor>
    <md:KeyDescriptor use="encryption">
      <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:X509Data>
          <ds:X509Certificate>MIICmjCCAYICCQDX5sKPsYV3+jANBgkqhkiG9w0BAQsFADAPMQ0wCwYDVQQDDAR0ZXN0MB4XDTE5MTIyMzA5MDI1MVoXDTIwMDEyMjA5MDI1MVowDzENMAsGA1UEAwwEdGVzdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMdtDJ278DQTp84O5Nq5F8s5YOR34GFOGI2Swb/3pU7X7918lVljiKv7WVM65S59nJSyXV+fa15qoXLfsdRnq3yw0hTSTs2YDX+jl98kK3ksk3rROfYh1LIgByj4/4NeNpExgeB6rQk5Ay7YS+ARmMzEjXa0favHxu5BOdB2y6WvRQyjPS2lirT/PKWBZc04QZepsZ56+W7bd557tdedcYdY/nKI1qmSQClG2qgslzgqFOv1KCOw43a3mcK/TiiD8IXyLMJNC6OFW3xTL/BG6SOZ3dQ9rjQOBga+6GIaQsDjC4Xp7Kx+FkSvgaw0sJV8gt1mlZy+27Sza6d+hHD2pWECAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAm2fk1+gd08FQxK7TL04O8EK1f0bzaGGUxWzlh98a3Dm8+OPhVQRi/KLsFHliLC86lsZQKunYdDB+qd0KUk2oqDG6tstG/htmRYD/S/jNmt8gyPAVi11dHUqW3IvQgJLwxZtoAv6PNs188hvT1WK3VWJ4YgFKYi5XQYnR5sv69Vsr91lYAxyrIlMKahjSW1jTD3ByRfAQghsSLk6fV0OyJHyhuF1TxOVBVf8XOdaqfmvD90JGIPGtfMLPUX4m35qaGAU48PwCL7L3cRHYs9wZWc0ifXZcBENLtHYCLi5txR8c5lyHB9d3AQHzKHMFNjLswn5HsckKg83RH7+eVqHqGw==</ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
    </md:KeyDescriptor>
    <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://192.168.98.180:8080/simplesaml/saml2/idp/SingleLogoutService.php"/>
    <md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</md:NameIDFormat>
    <md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://192.168.98.180:8080/simplesaml/saml2/idp/SSOService.php"/>
  </md:IDPSSODescriptor>
  <md:ContactPerson contactType="technical">
    <md:GivenName>Administrator</md:GivenName>
    <md:EmailAddress>mailto:na@example.com</md:EmailAddress>
  </md:ContactPerson>
</md:EntityDescriptor>

**Comment by rfarajro** [comment]
Hi,

 Anyone can help me with this issue?

 Thanks and regards.

**Comment by zentavr** [comment]
I have the same issue with AWX 19.5.0

**Comment by rfarajro** [comment]
> I have the same issue with AWX 19.5.0

 Hi,

In my case the problem was that I was missing two fields for the SAML module to be activated. The documentation does not specify anything about it.

Missing fields:

SAML Service Provider Technical Contact
SAML Service Provider Support Contact

Remember, other necessary fields are certificate and private key.

 Issue closed.

 Regards.

**Comment by zentavr** [comment]
@rfarajro Thank you very much for your experience! That helped!
