### ISSUE TITLE
Azure AD Logout URL Setting

### ISSUE THREAD

**Issue by DaveIscodingALot** [ansible/awx#11383]
I have implemented AWX successfully with Azure Ad integration, but when I log off, it will remember the session, log in automatically and never ask for credentials. This can be solved by manually logging off with the URL provided by Azure or by closing the browser window. Would it be possible to have this setting in AWX so that I can insert the log off URL and redirect back to the login page?

Currently using the following:

AWX 17.1.0
CentOS 7.9
Docker CE 20.10.9-3

Thanks!
Dave

**Comment by nixocio** [comment]
@DaveIscodingALot, there were some changes on code related to this feature. Right now even when using third party SSO when logging out the user is redirect to the login page. Can you try the latest AWX version?

**Comment by shanemcd** [comment]
Closing due to lack of response.

**Comment by omnachiketa** [comment]
We face the same issue, and we are using the latest awx with the operator. Is there a logout URI that we can configure?
