### ISSUE TITLE
How to upgrade Awx from 17.x to 19.x operator method in K8

### ISSUE THREAD

**Issue by eselvam** [ansible/awx#11388]
We use K8 cluster to port awx 17.x.  We plan to upgrade from 17.x to 19.x k8 operator method.  I could not find any proper guide for upgrade.  Could some one help me here with proper document.  Thanks.

**Comment by ghost** [comment]
https://github.com/ansible/awx-operator/blob/devel/docs/migration.md

**Comment by shanemcd** [comment]
Correct, see the doc linked above.
