### ISSUE TITLE
With ja google-chrome, unwanted html code <br> is visible at the ~/settings/subscription/edit page, need to remove it

### ISSUE THREAD

**Issue by sshedmake** [ansible/awx#11397]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

When in ja google-chrome, unwanted html code \<br\> is visible at the Settings > Subscription > Edit Details page, need to be removed

### AWX version

19.3.0

### Installation method

docker on linux

### Modifications

no

### Ansible version

ansible [core 2.11.0]

### Operating system

RHEL-8.4

### Web browser

Chrome

### Steps to reproduce

1. Do a successful login in the preferred language (say Japanese)
2. Navigate to the Settings > Subscription > Edit Details page
3. Observe the tooltip beside the 'Red Hat subscription manifest' label

### Expected results

html code or \<br\> tag should not be visible (need to remove it)

### Actual results

html code or \<br\> tag is visible

### Additional information

1. Screenshot highlighting html code or \<br\> tag at the Settings > Subscription > Edit Details page , when in ja google-chrome:
![ja_bug_br-tag-remove_Screenshot from 2021-11-30 10-34-35](https://user-images.githubusercontent.com/12151785/144035083-dfca62b7-5059-42b5-9acd-37089c91c2bf.png)

2. https://github.com/ansible/awx/blob/ba324c73ceefa22d516d872527649d090d3bc0cc/awx/ui/src/locales/ja/messages.po#L115-L117

**Comment by AlexSCorey** [comment]
I am not able to reproduce this issue.  

![Screen Shot 2022-03-23 at 10 07 17 AM](https://user-images.githubusercontent.com/39280967/159718329-1012f5f8-e932-45eb-bcbd-7b8467bc6bbb.png)

**Comment by tiagodread** [comment]
I was also unable to reproduce it.
