### ISSUE TITLE
Toggle text 'of', at the Pagination of main lists - Job Templates, Projects, Inventory, Organization, Users, Teams, Notifications, Instance Groups, Execution Environments, etc., needs to be marked for translations

### ISSUE THREAD

**Issue by sshedmake** [ansible/awx#11396]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

This bug is continuation of https://github.com/ansible/awx/issues/6800, wherein pagination within the modals is fixed, but not with the main lists i.e. Resources (Job Templates, Projects, Inventory), Access (Organization, Users, Teams, Notifications), Administration (Instance Groups, Execution Environments).

This bug is filed separately to address pagination of main lists.

With Japanese google-chrome, Toggle text 'of', at the pagination of main lists, appears in English, instead of Japanese.

### AWX version

19.3.0

### Installation method

docker on linux

### Modifications

no

### Ansible version

ansible [core 2.11.0]

### Operating system

RHEL-8.4

### Web browser

Chrome

### Steps to reproduce

1. Do a successful login in the preferred language (say - Japanese)
2. Navigate to any of the main lists page i.e. Job Templates, Projects, Inventory, Organization, Users, Teams, Notifications, Instance Groups, Execution Environments, etc. (say - Job Templates)
3. Observe the toggle text 'of' at Pagination options menu

### Expected results

Toggle text 'of' should appear in Japanese

### Actual results

Toggle text 'of' appears in English

### Additional information

1. Screenshot highlighting toggle text 'of', at the pagination options, appearing in English:
![ja_pagination_templates_Screenshot from 2021-11-30 10-49-32_3](https://user-images.githubusercontent.com/12151785/144006005-29ffe9f0-4ea8-4ef4-88ab-ec510ba0af51.png)

2. Affects pagination nav of other forms (within the Resources, Access and Administration nav links) too

3. Please see https://github.com/ansible/awx/issues/6800 for more information

**Comment by mabashian** [comment]
http://patternfly-react.surge.sh/components/pagination looks like PF exposes a prop `ofWord` where we can pass in a translated version of `of`.
