### ISSUE TITLE
Add archive type to AWX collection when creating a project

### ISSUE THREAD

**Issue by Bentoto** [ansible/awx#11398]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

AWX Collection Version: 19.4
AWX Version: 15 and 17

Hi, i've been using the AWX collection, for my use case i need to create a project who needs an "archive" for the "scm_type", but this option is not available according to the documentation (https://docs.ansible.com/ansible/latest/collections/awx/awx/project_module.html#ansible-collections-awx-awx-project-module) :
![image](https://user-images.githubusercontent.com/28566634/144036458-dc21b248-2fb6-48da-a3e9-75f85c4a830a.png)

Can you please add it ?

**Comment by lutin-malin** [comment]
I'm also interested, use case is simply when you don't have access to source control to pull a project.
Thus spreading project is through a given artefact manager (let's say Nexus)
and AWX would get its project from a URL, pulling the project's archive stored in Nexus.

**Comment by AlanCoding** [comment]
@sean-m-sullivan resolved in https://github.com/ansible/awx/pull/12093
