### ISSUE TITLE
LDAP configuration should be more flexible

### ISSUE THREAD

**Issue by marvin0815** [ansible/awx#114]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT

 - API
 - UI

##### SUMMARY

The LDAP-Configuration should be able to get configured which _member_attr_ should be looked up.
member_attr='member' is hardcoded but some people use uniqueMember instead.

##### ENVIRONMENT

* AWX version: 1.0.0.317
* Ansible version:  any
* Operating System: any
* Web Browser: any

##### STEPS TO REPRODUCE

Logging in the first time, the user isn't added to any organisations or teams despite LDAP is otherwise correctly configured.

##### EXPECTED RESULTS

Logging in the first time, the user is added to any organisations or teams.

##### ACTUAL RESULTS

Logging in the first time, the user isn't added to any organisations or teams

**Comment by matburt** [comment]
This is a pretty well tested code path for AWX/Tower you may want to walk through this bit of the Tower docs:

http://docs.ansible.com/ansible-tower/latest/html/administration/ldap_auth.html#ag-ldap-org-team-maps

You didn't mention any settings you may have provided in the Tower Configuration interface but Org/Team mappings run through daily validations against an openldap system, so I'll mark this as needs-info. If you could provide some details on what you included in the tower configuration interface we can try to track the issue down.

**Comment by marvin0815** [comment]
Sorry for the lack of information.

This is our LDAP configuration:
```json
{
"AUTH_LDAP_SERVER_URI": "ldap://ldap.company.com",
  "AUTH_LDAP_BIND_DN": "uid=tower,ou=applications,o=company,o=com",
  "AUTH_LDAP_BIND_PASSWORD": "$encrypted$",
  "AUTH_LDAP_START_TLS": false,
  "AUTH_LDAP_CONNECTION_OPTIONS": {
    "OPT_NETWORK_TIMEOUT": 30,
    "OPT_REFERRALS": 0
  },
  "AUTH_LDAP_USER_SEARCH": [
    "ou=People,o=company,o=com",
    "SCOPE_SUBTREE",
    "(uid=%(user)s)"
  ],
  "AUTH_LDAP_USER_DN_TEMPLATE": null,
  "AUTH_LDAP_USER_ATTR_MAP": {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail"
  },
  "AUTH_LDAP_GROUP_SEARCH": [
    "ou=Groups,o=company,o=com",
    "SCOPE_SUBTREE",
    "(objectClass=groupOfUniqueNames)"
  ],
  "AUTH_LDAP_GROUP_TYPE": "MemberDNGroupType",
  "AUTH_LDAP_REQUIRE_GROUP": null,
  "AUTH_LDAP_DENY_GROUP": null,
  "AUTH_LDAP_USER_FLAGS_BY_GROUP": {},
  "AUTH_LDAP_ORGANIZATION_MAP": {
    "company": {
      "users": true,
      "admins": "cn=tower,ou=Groups,o=company,o=com",
      "remove_admins": false,
      "remove_users": false
    }
  },
  "AUTH_LDAP_TEAM_MAP": {
    "Unix": {
      "organization": "company",
      "users": "cn=Unix,ou=Groups,o=company,o=com",
      "remove": true
    },
    "Web": {
      "organization": "company",
      "users": "cn=Web,ou=Groups,o=company,o=com",
      "remove": true
    }
  }
}
```
This is the expample group:
```
dn: cn=tower,ou=Groups,o=company,o=com
objectClass: groupOfUniqueNames
objectClass: groupofurls
...
cn: tower
...
uniqueMember: uid=user.name,ou=People,o=company,o=com
```

If i modify https://github.com/ansible/awx/blob/devel/awx/sso/fields.py#L326 from:
```python
    def to_internal_value(self, data):
        data = super(LDAPGroupTypeField, self).to_internal_value(data)
        if not data:
            return None
        if data.endswith('MemberDNGroupType'):
            return getattr(django_auth_ldap.config, data)(member_attr='member')
        else:
            return getattr(django_auth_ldap.config, data)()
```
to
```python
    def to_internal_value(self, data):
        data = super(LDAPGroupTypeField, self).to_internal_value(data)
        if not data:
            return None
        if data.endswith('MemberDNGroupType'):
            return getattr(django_auth_ldap.config, data)(member_attr='uniqueMember')
        else:
            return getattr(django_auth_ldap.config, data)()
```

users get assigned to the Company and Teams.
I hope this clearifies out issue.

**Comment by jangsutsr** [comment]
Move back to devel for UI as a new LDAP configuration 'AUTH_LDAP_GROUP_TYPE_MEMBER_ATTR' is introduced.

**Comment by cchurch** [comment]
There's a `GroupOfUniqueNamesType` that uses the `uniqueMember` attribute instead of `member`.

**Comment by jangsutsr** [comment]
@marvin0815 Could you try the workaround provided by @cchurch ^ to see if it works so that we can revert the related PR if it does? Thanks!

**Comment by marvin0815** [comment]
We changed the group type to GroupOfUniqueNamesType and everything works as expected.

I read the django-auth-ldap reference over and over again to make sure this not a configuration error. I must have missed that.
Sorry for the extra work you guys did.

**Comment by matburt** [comment]
np, glad it worked out
