### ISSUE TITLE
Job Output- search results in no data- blank screen

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#11409]
On the job output screen, when a user searches for something and no results are found, only a blank screen results. There is nothing to tell the user that no results were found. The blank screen may lead the user to believe that something went wrong.

Adding some sort of message indicating no results found would be helpful here.

https://user-images.githubusercontent.com/63685497/144294236-bcc0170e-c618-4827-9a2e-bd14749b59e6.mp4

**Comment by trahman73** [comment]
Here is an example empty state with specs...

Icon: fa-search (React icon: SearchIcon)
Icon color: #6A6E73 (--pf-global--Color--200)

We can update the text further if needed...

![image](https://user-images.githubusercontent.com/13351591/153487275-bb3cc6b9-9d74-4a73-8528-f136a8e3ca51.png)

**Comment by akus062381** [comment]
@trahman73 I love this! Much nicer :-D

**Comment by trahman73** [comment]
Thanks! @akus062381

**Comment by akus062381** [comment]
I triggered the e2e tests. I will merge once they finish

**Comment by akus062381** [comment]
all set, PR merged
