### ISSUE TITLE
With ja google-chrome, ja translation "ページ" for the source string "pages", has an unwanted trailing char 's', visible at pagination options

### ISSUE THREAD

**Issue by sshedmake** [ansible/awx#11400]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

With ja google-chrome, ja translation `ページ` for the source string `pages`, has an unwanted trailing char 's', visible at the pagination options for main lists i.e. Job Templates, Projects, Inventory, etc., and pagination options within modals

### AWX version

19.3.0

### Installation method

docker on linux

### Modifications

no

### Ansible version

ansible [core 2.11.0]

### Operating system

RHEL-8.4

### Web browser

Chrome

### Steps to reproduce

1. Do a successful login in the preferred language (say Japanese)
2. Navigate to ~/activity_stream page
3. Observe ja translation `ページ` for the source string `pages`, visible at pagination options

### Expected results

no unwanted trailing char 's'

### Actual results

has an unwanted trailing char 's'

### Additional information

1. Screenshot highlighting ja translation `ページ` for the source string `pages`, visible at pagination options, for the main list
![ja_unwanted-char-s-main-list-Screenshot from 2021-11-30 10-48-06_1](https://user-images.githubusercontent.com/12151785/144048090-b7512978-187b-4f23-bbde-1770c80441e8.png)
 
2. Screenshot highlighting ja translation `ページ` for the source string `pages`, visible at pagination options, within modals
![ja_unwanted-char-s-within-modals-Screenshot from 2021-11-30 10-53-26_1](https://user-images.githubusercontent.com/12151785/144048109-8bf0dff8-92c1-4560-b178-97000a70cda4.png)

3. https://github.com/ansible/awx/blob/ba324c73ceefa22d516d872527649d090d3bc0cc/awx/ui/src/locales/ja/messages.po#L9750-L9752 

4. Not sure, if Plural-Forms in the ja PO file header, has any relation here
https://github.com/ansible/awx/blob/ba324c73ceefa22d516d872527649d090d3bc0cc/awx/ui/src/locales/ja/messages.po#L14

**Comment by AlexSCorey** [comment]
I believe that this is a PF issue where PF is overwriting our pluralization page title.  https://github.com/patternfly/patternfly-react/issues/7109

**Comment by sshedmake** [comment]
Could reproduce the said problem with 'Simplified Chinese' or zh-CN locale. Could be a problem with complex script locales, say CJK (Chinese Japanese Korean) locales.

**Comment by AlexSCorey** [comment]
I believe this issue is resolved.  TBH I'm not really sure what changed, but I tested it with Ja and with zh-CN.  the `S` is not appearing.  Moving to needs test for confirmation.
![Screen Shot 2022-04-29 at 11 38 10 AM](https://user-images.githubusercontent.com/39280967/165977653-a08be65a-3f5b-4d21-92b1-3130daad03bd.png)
I

**Comment by jay-steurer** [comment]
Issue is resolved. 
![image](https://user-images.githubusercontent.com/70719005/166065196-146b48b4-e0a1-4fa0-8a56-49de8add5bd3.png)
