### ISSUE TITLE
Error synchronising vmware inventory

### ISSUE THREAD

**Issue by rafabono** [ansible/awx#11418]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Hello, the awx-ee image on quay.io has been updated today. After the update, the vmware repository sync gives the following error:
[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.
ansible-inventory [core 2.13.0.dev0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.8 (default, Aug 25 2021, 16:13:02) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.0.3
  libyaml = True
No config file found; using defaults
setting up inventory plugins
redirecting (type: inventory) ansible.builtin.vmware_vm_inventory to community.vmware.vmware_vm_inventory
Loading collection community.vmware from /usr/share/ansible/collections/ansible_collections/community/vmware
[WARNING]:  * Failed to parse /runner/inventory/vmware_vm_inventory.yml with
auto plugin: _find_module_shim() got an unexpected keyword argument 'path' 

### AWX version

19.4.0

### Installation method

openshift

### Modifications

no

### Steps to reproduce

Configure a new inventory with source: VMWare.
Synchronise the inventory and an error will appear.

### Expected results

With the previous version of awx-ee, the result was:

 ansible-inventory [core 2.11.7rc1.post0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.8 (default, Aug 25 2021, 16:13:02) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
redirecting (type: inventory) ansible.builtin.vmware_vm_inventory to community.vmware.vmware_vm_inventory
Parsed /runner/inventory/vmware_vm_inventory.yml inventory source with auto plugin
    8.308 INFO     Processing JSON output...
    8.311 INFO     Loaded 0 groups, 35 hosts

### Actual results

[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.
ansible-inventory [core 2.13.0.dev0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.8 (default, Aug 25 2021, 16:13:02) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.0.3
  libyaml = True
No config file found; using defaults
setting up inventory plugins
redirecting (type: inventory) ansible.builtin.vmware_vm_inventory to community.vmware.vmware_vm_inventory
Loading collection community.vmware from /usr/share/ansible/collections/ansible_collections/community/vmware
[WARNING]:  * Failed to parse /runner/inventory/vmware_vm_inventory.yml with
auto plugin: _find_module_shim() got an unexpected keyword argument 'path' 

### Additional information

The error has started to occur after the update of https://quay.io/repository/ansible/awx-ee.

**Comment by coreydeli** [comment]
I have this same issue on 19.5.0

**Comment by rafabono** [comment]
A new change solved this problem.

**Comment by coreydeli** [comment]
What was the change because I have this issue still and can't seem to get around it.
