### ISSUE TITLE
How to enable the httpOnly attribute for current_user Cookie

### ISSUE THREAD

**Issue by swathit0717** [ansible/awx#11419]
Hi,

I am using AWX 15.0.0. 
In our Pen testing we found the  vulnerability: HTTPOnly and Secure attributes are not set for Cookies
I was able to enable to Secure attribute by adding these changes in the "settings.py" file.

settings.py
######
CSRF_COOKIE_SECURE= True
SESSION_COOKIE_SECURE= True
#######
Is there a way to enable httpOnly attribute for current_user cookie. Please suggest.

Thanks,
Swathi.

**Comment by mabashian** [comment]
@AlanCoding I see a linked PR here - can we close this one?

**Comment by mabashian** [comment]
Disregard - that was a dupe issue not a linked PR.  My mistake.

**Comment by anilreddy103** [comment]
@AlanCoding @mabashian Any update if this will be implemented? We are also facing this issue in pentest finding in Kyndryl.

**Comment by AlanCoding** [comment]
The "current_user" cookie was removed in https://github.com/ansible/awx/pull/12818
