### ISSUE TITLE
Workflow Tags Prompt on Launch

### ISSUE THREAD

**Issue by exp-hc** [ansible/awx#11423]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Workflows could accept parameters like `ask_job_tags_on_launch` and `ask_skip_tags_on_launch`. This would allow you to apply tags (skip tags) at the workflow level during launch without creating 2 separate workflow to use tagging.

**Comment by AlanCoding** [comment]
Link https://github.com/ansible/awx/issues/7859

@ffirg we have added these workflow "prompt" fields one-by-one, and my argument is that it will take considerably less time to do a refactor where we have workflow prompts be at full parity with JT prompts.

**Comment by AlanCoding** [comment]
Other recent prompting requests
 - prompting for EE (not tracked)
 - prompting for instance group or instance https://github.com/ansible/awx/issues/5711

It would be best to handle the workflow prompting as a separate issue from these two, which apply to jobs. Unless, of course, it is expected that the new job prompts would be available on workflows. In that case, it's most efficient to first add the prompting to jobs and then apply it to workflows.

**Comment by ffirg** [comment]
possibly related? https://github.com/ansible/awx/issues/10719

**Comment by mabashian** [comment]
Addressed by https://github.com/ansible/awx/pull/12875
