### ISSUE TITLE
Job logs broken when coming in live via websockets

### ISSUE THREAD

**Issue by apollo13** [ansible/awx#11424]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

The streaming job output creates broken output. I cannot figure out whether this is dependent on window size etc or not. Seems to affect at least Firefox & Chrome -- I do not have other browsers at hand to test. The browser window in this case was always in full screen. So there was no need to scroll or anything…

When correct the output looks like this:
![Screenshot from 2021-12-06 19-27-37](https://user-images.githubusercontent.com/81547/144901898-c8b8f85a-c13c-4b11-bf6e-fdacd1f8df0e.png)

The other two variants that I did observe:
![Screenshot from 2021-12-06 19-27-46](https://user-images.githubusercontent.com/81547/144901931-3a078479-de3a-40c1-9301-3882ba6ab135.png)
![Screenshot from 2021-12-06 19-27-27](https://user-images.githubusercontent.com/81547/144901956-915f2bac-f40a-4d48-90ed-80283b129151.png)

As you can see on the indexing on the left, some lines get shifted.

### AWX version

devel as of today

### Installation method

docker on linux

### Modifications

no

### Ansible version

Whatever comes with the devel container

### Operating system

Fedora 35

### Web browser

Firefox, Chrome

### Steps to reproduce

Run the "Demo Job Template" a few times

### Expected results

Proper output and no intermixed lines

### Actual results

Lines are intermixed

### Additional information

The data is properly in the database, reloading the page after the job finished will always show all lines properly.

Testenv is started via `CONTROL_PLANE_NODE_COUNT=1 EXECUTION_NODE_COUNT=0 COMPOSE_TAG=devel make docker-compose`

**Comment by denniswoot** [comment]
What do you see with developer tools? 

Visit start-page of AWX, open F12 -> Developer Console -> do you see errors?

**Comment by apollo13** [comment]
Nothing, and given my screenshots it seems like a simple miss calculation rather than an error. Did you try to reproduce the issue?

**Comment by mabashian** [comment]
@apollo13 we've made some changes in this area of the application recently.  Do you mind checking the latest AWX release and seeing if this behavior persists?

**Comment by apollo13** [comment]
@mabashian The output looks better now -- ie I no longer observe interleaving and duplicated outputs. What I do not see most of the times is the play recap.

**Comment by IPvSean** [comment]
I have also noticed, not sure if it is covered here, that when you want to sync your project (e.g. github) the job output will remain blank...
![image](https://user-images.githubusercontent.com/6537680/167949896-14ade71a-ba68-45bf-9a74-98f5d739c8ca.png)

there is no feedback to the user, so they think it is broken

**Comment by keithjgrant** [comment]
Comments here relate to a number of separate issues. The initial issue (duplicated output) has been fixed, so I am marking this as closed. Missing play recap has been largely mitigated, but a full fix depends on #12103
