### ISSUE TITLE
base64.py error on project sync

### ISSUE THREAD

**Issue by Zeek3000** [ansible/awx#11421]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

New install of AWX following the awx-operator (0.14.0) installation method, no modifications to any images although I did deploy using kubernetes rather than minikube.

Project sync fails due to python error "ValueError: bad base85 character at position 287". 

### AWX version

19.4.0

### Installation method

kubernetes

### Modifications

no

### Operating system

CentOS

### Steps to reproduce

Installing as recommended by the guide, using awx-operator, with the exception of using kubernetes rather than minikube
Adding a Git controlled project

### Expected results

Successful project sync

### Actual results

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/streaming.py", line 108, in run
    utils.unstream_dir(zip_data, self.private_data_dir)
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/utils.py", line 104, in unstream_dir
    data = base64.b85decode(data)
  File "/usr/lib64/python3.8/base64.py", line 463, in b85decode
    raise ValueError('bad base85 character at position %d'
ValueError: bad base85 character at position 287

**Comment by rverhe** [comment]
Anyone?

**Comment by ShaunBoughey** [comment]
Getting the same error. Be good to know why!

**Comment by BakaKiller** [comment]
Same error here after installing an EE and trying to run a project on it...

**Comment by shanemcd** [comment]
Very likely the same underlying problem as https://github.com/ansible/awx/issues/11390

**Comment by shanemcd** [comment]
Even though the symptoms are different, I'm going to close this in favor of the other issue.
