### ISSUE TITLE
De-complicating the installation process.

### ISSUE THREAD

**Issue by bitshiftnetau** [ansible/awx#11420]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Reading the installation docs made me want to die. It seems so unnecessarily complicated, which is weird as the entire idea is to simplify usage right? 

Is there a way this can be built native to a system and I can just run it up as a service?

**Comment by shanemcd** [comment]
This issue tracker is intended for bugs and actionable feature requests. If you have any real suggestions or advice, please let us know. Better yet, we'd love if you'd become a contributor. If you just want to vent, please go to the mailing list or IRC.

**Comment by bitshiftnetau** [comment]
"Is there any way this can be built as a native service" 

How much more 'actionable' or 'real' can I get?
