### ISSUE TITLE
AWX 19.2.2 Grafana Notifications dashboardId and panelId incorrect format

### ISSUE THREAD

**Issue by francoisv100** [ansible/awx#11426]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

AWX Grafana Notifications not sending the dashboardId and panelId in the correct format , AWX sending dashboardId and panelId in string format and Grafana is expecting value in integer format , basically the double quotes need to be removed,

Payload from AWX : 

{
    "isRegion": true,
    "dashboardId": "3",
    "panelId": "58",
    "tags": [
        "AWX ALARMS"
    ],
    "text": "Notification Test 3 https://example.co.za"
}

Expected Payload accepted by Grafana : (Grafana v8.2.5 (b57a137acd))

{
    "isRegion": true,
    "dashboardId": 3,
    "panelId": 58,
    "tags": [
        "AWX ALARMS"
    ],
    "text": "Notification Test 2 https://example.co.za"
}

### AWX version

AWX 19.2.2

### Installation method

kubernetes

### Modifications

no

### Ansible version

core 2.11.4.post0

### Operating system

macOS Monterey 12.0.1

### Web browser

Safari

### Steps to reproduce

When testing Grafana Notifications in AWX with dashboardId and panelId or without dashboardId and panelId to the Grafana annotations API error 400 is observed below

Traceback (most recent call last):
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 350, in send_notifications
sent = notification.notification_template.send(notification.subject, notification.body)
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/models/notifications.py", line 185, in send
return backend_obj.send_messages([notification_obj])
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/notifications/grafana_backend.py", line 102, in send_messages
raise Exception(smart_text(_("Error sending notification grafana: {}").format(r.status_code)))
Exception: Error sending notification grafana: 400

When looking at the payload when testing towards https://requestinspector.com I notice the dashboardId and panelId is being posted as text and not integers expected by Grafana(Grafana v8.2.5 (b57a137acd)),

When testing from a python script directly:

dashboardId and panelId in text format:

<Response [400]>
https://serverurl/api/annotations {'Accept': 'application/json', 'Content-Type': 'application/json', 'Authorization': 'Bearer apikey'} {'isRegion': 'true', 'dashboardId': '3', 'panelId': '58', 'tags': ['AWX ALARMS'], 'text': 'Notification Test 2 https://example.co.za'}
[{'classification': 'DeserializationError', 'message': 'json: cannot unmarshal string into Go struct field PostAnnotationsCmd.dashboardId of type int64'}]

dashboardId and panelId in integer format (no quotes around values)

<Response [200]>
https://serverurl/api/annotations {'Accept': 'application/json', 'Content-Type': 'application/json', 'Authorization': 'Bearer apikey'} {'isRegion': 'true', 'dashboardId': 3, 'panelId': 58, 'tags': ['AWX ALARMS'], 'text': 'Notification Test 2 https://exampleco.za'}
{'id': 10175, 'message': 'Annotation added'}

 

### Expected results

Test Notification to post successfully towards Grafana annotations API

### Actual results

getting error 400

Traceback (most recent call last):
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 350, in send_notifications
sent = notification.notification_template.send(notification.subject, notification.body)
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/models/notifications.py", line 185, in send
return backend_obj.send_messages([notification_obj])
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/notifications/grafana_backend.py", line 102, in send_messages
raise Exception(smart_text(_("Error sending notification grafana: {}").format(r.status_code)))
Exception: Error sending notification grafana: 400

### Additional information

![AWX Grafana Notifications Error 400](https://user-images.githubusercontent.com/95674398/145011444-66599fdb-11a7-4aa1-969a-44b6b7a0a737.png)
![AWX Grafana Notifications settings](https://user-images.githubusercontent.com/95674398/145011452-be2ee230-404b-4e7b-a812-afb18cd66c4d.png)

**Comment by bpedersen2** [comment]
See https://github.com/ansible/awx/pull/11083

**Comment by francoisv100** [comment]
Closing as this is related to pr #11083
