### ISSUE TITLE
Add new instance on AWX with k3s

### ISSUE THREAD

**Issue by gsfcosta** [ansible/awx#11437]
I implemented ansible awx through k3s (kubectl). But I have other servers that I would like to add as an instance to perform tasks in awx. I've already researched and looked in several places where to make the inclusion and I didn't find it. Can someone help me?

Thanks in advance!

**Comment by shanemcd** [comment]
Hello,

This issue tracker is for tracking feature enhancements and bugs.

If you need help troubleshooting or are looking for help using AWX, try our mailing list or IRC channel:

#ansible-awx on https://libera.chat/
https://groups.google.com/forum/#!forum/awx-project
