### ISSUE TITLE
Not able to assign job template access using awx.awx collection

### ISSUE THREAD

**Issue by zigford** [ansible/awx#11444]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
We configure our AWX instance 100% with awx.awx collection thus far.
One area that I haven't been able to configure is to assign a team or user access to a specific job.
We use the awx.awx.tower_settings to configure LDAP and teams based on groups. We would like to be able to add a team to a template job that they cannot access by default.

**Comment by tonk** [comment]
Following, I have the same issue

**Comment by john-westcott-iv** [comment]
Have you tried using the awx.awx.role module from the collection? This module should allow you to apply teams to assets within awx. i.e. add a team to execute role of a job template.

**Comment by zigford** [comment]
I was able to use awx.awx.role. For some reason it didn't stand out to me initially to use it.
