### ISSUE TITLE
Issue on connecting on inventory host

### ISSUE THREAD

**Issue by skyangeli** [ansible/awx#11445]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Hi,
I'm currently encountering issue on inventory host connection
Error output related to /usr/lib64/python3.6/http/ python script:
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/urllib/request.py", line 1349, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/tmp/ansible_bigip_device_info_payload_n4ozul51/ansible_bigip_device_info_pa…

Note that playbook works fine running from awx venv awx_task container 

If anyone can help that would be really appreciated. 
Many thanks.

### AWX version

17.1

### Installation method

docker on linux

### Modifications

no

### Ansible version

ansible 2.9.18

### Operating system

Red Hat 8.3.1-5

### Web browser

Firefox

### Steps to reproduce

-

### Expected results

output From awx_task container command ansible-playbook
task path: /var/lib/awx/projects/LTM/get_certs.yml:20
<10.173.68.2> Using network group action bigip for bigip_device_info
<10.173.68.2> connection transport is rest
<10.173.68.2> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.173.68.2> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.173.68.2> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1639133444.228411-3721-46122123123665 `" && echo ansible-tmp-1639133444.228411-3721-46122123123665="` echo /root/.ansible/tmp/ansible-tmp-1639133444.228411-3721-46122123123665 `" ) && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/network/f5/bigip_device_info.py
<10.173.68.2> PUT /var/lib/awx/.ansible/tmp/ansible-local-3697hick00oq/tmptm8ytgqh TO /root/.ansible/tmp/ansible-tmp-1639133444.228411-3721-46122123123665/AnsiballZ_bigip_device_info.py
<10.173.68.2> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1639133444.228411-3721-46122123123665/ /root/.ansible/tmp/ansible-tmp-1639133444.228411-3721-46122123123665/AnsiballZ_bigip_device_info.py && sleep 0'
<10.173.68.2> EXEC /bin/sh -c '/usr/bin/python3.6 /root/.ansible/tmp/ansible-tmp-1639133444.228411-3721-46122123123665/AnsiballZ_bigip_device_info.py && sleep 0'
<10.173.68.2> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1639133444.228411-3721-46122123123665/ > /dev/null 2>&1 && sleep 0'
ok: [10.173.68.2] => {

### Actual results

output From AWX Web app
<10.173.68.2> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.173.68.2> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.173.68.2> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1639130357.0844948-3567-156056127789040 `" && echo ansible-tmp-1639130357.0844948-3567-156056127789040="` echo /root/.ansible/tmp/ansible-tmp-1639130357.0844948-3567-156056127789040 `" ) && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/network/f5/bigip_device_info.py
<10.173.68.2> PUT /var/lib/awx/.ansible/tmp/ansible-local-3540mnodmezb/tmpdgngtg2u TO /root/.ansible/tmp/ansible-tmp-1639130357.0844948-3567-156056127789040/AnsiballZ_bigip_device_info.py
<10.173.68.2> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1639130357.0844948-3567-156056127789040/ /root/.ansible/tmp/ansible-tmp-1639130357.0844948-3567-156056127789040/AnsiballZ_bigip_device_info.py && sleep 0'
<10.173.68.2> EXEC /bin/sh -c '/usr/bin/python3.6 /root/.ansible/tmp/ansible-tmp-1639130357.0844948-3567-156056127789040/AnsiballZ_bigip_device_info.py && sleep 0'
<10.173.68.2> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1639130357.0844948-3567-156056127789040/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/urllib/request.py", line 1349, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/tmp/ansible_bigip_device_info_payload_n4ozul51/ansible_bigip_device_info_pa…

**Comment by AlanCoding** [comment]
That traceback is truncated, can you get the full output from somewhere? We could also use some more details about what task this fails on and what kind of host it's reaching out to (because I assume it gets to some connection-related error, but don't know).

**Comment by skyangeli** [comment]
Hi,
Many thanks for your answer:
Please find whole json output 
{
  "module_stdout": "",
  "module_stderr": "Traceback (most recent call last):\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 1349, in do_open\n    encode_chunked=req.has_header('Transfer-encoding'))\n  File \"/usr/lib64/python3.6/http/client.py\", line 1254, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n  File \"/usr/lib64/python3.6/http/client.py\", line 1300, in _send_request\n    self.end headers(body, encode_chunked=encode_chunked)\n  File \"/usr/lib64/python3.6/http/client.py\", line 1249, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File \"/usr/lib64/python3.6/http/client.py\", line 1036, in _send_output\n    self.send(msg)\n  File \"/usr/lib64/python3.6/http/client.py\", line 974, in send\n    self.connect()\n  File \"/usr/lib64/python3.6/http/client.py\", line 1422, in connect\n    server_hostname=server_hostname)\n  File \"/usr/lib64/python3.6/ssl.py\", line 365, in wrap_socket\n    _context=self, _session=session)\n  File \"/usr/lib64/python3.6/ssl.py\", line 776, in __init__\n    self.do_handshake()\n  File \"/usr/lib64/python3.6/ssl.py\", line 1036, in do_handshake\n    self._sslobj.do_handshake()\n  File \"/usr/lib64/python3.6/ssl.py\", line 648, in do_handshake\n    self._sslobj.do_handshake()\nOSError: [Errno 0] Error\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1639149441.3062203-175-2960510232002/AnsiballZ_bigip_device_info.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1639149441.3062203-175-2960510232002/AnsiballZ_bigip_device_info.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1639149441.3062203-175-2960510232002/AnsiballZ_bigip_device_info.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.f5.bigip_device_info', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_bigip_device_info_payload_krptz0fm/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 16266, in <module>\n  File \"/tmp/ansible_bigip_device_info_payload_krptz0fm/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 16259, in main\n  File \"/tmp/ansible_bigip_device_info_payload_krptz0fm/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 15999, in exec_module\n  File \"/tmp/ansible_bigip_device_info_payload_krptz0fm/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 16075, in execute_managers\n  File \"/tmp/ansible_bigip_device_info_payload_krptz0fm/ansible_bigip_device_info_payload.zip/ansible/module_utils/network/f5/icontrol.py\", line 598, in modules_provisioned\n  File \"/tmp/ansible_bigip_device_info_payload_krptz0fm/ansible_bigip_device_info_payload.zip/ansible/module_utils/network/f5/bigip.py\", line 34, in api\n  File \"/tmp/ansible_bigip_device_info_payload_krptz0fm/ansible_bigip_device_info_payload.zip/ansible/module_utils/network/f5/bigip.py\", line 58, in connect_via_token_auth\n  File \"/tmp/ansible_bigip_device_info_payload_krptz0fm/ansible_bigip_device_info_payload.zip/ansible/module_utils/network/f5/icontrol.py\", line 238, in post\n  File \"/tmp/ansible_bigip_device_info_payload_krptz0fm/ansible_bigip_device_info_payload.zip/ansible/module_utils/network/f5/icontrol.py\", line 193, in send\n  File \"/tmp/ansible_bigip_device_info_payload_krptz0fm/ansible_bigip_device_info_payload.zip/ansible/module_utils/urls.py\", line 1294, in open\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 223, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 526, in open\n    response = self._open(req, data)\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 544, in _open\n    '_open', req)\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 504, in _call_chain\n    result = func(*args)\n  File \"/tmp/ansible_bigip_device_info_payload_krptz0fm/ansible_bigip_device_info_payload.zip/ansible/module_utils/urls.py\", line 467, in https_open\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 1351, in do_open\n    raise URLError(err)\nurllib.error.URLError: <urlopen error [Errno 0] Error>\n",
  "exception": "Traceback (most recent call last):\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 1349, in do_open\n    encode_chunked=req.has_header('Transfer-encoding'))\n  File \"/usr/lib64/python3.6/http/client.py\", line 1254, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n  File \"/usr/lib64/python3.6/http/client.py\", line 1300, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n  File \"/usr/lib64/python3.6/http/client.py\", line 1249, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File \"/usr/lib64/python3.6/http/client.py\", line 1036, in _send_output\n    self.send(msg)\n  File \"/usr/lib64/python3.6/http/client.py\", line 974, in send\n    self.connect()\n  File \"/usr/lib64/python3.6/http/client.py\", line 1422, in connect\n    server_hostname=server_hostname)\n  File \"/usr/lib64/python3.6/ssl.py\", line 365, in wrap_socket\n    _context=self, _session=session)\n  File \"/usr/lib64/python3.6/ssl.py\", line 776, in __init__\n    self.do_handshake()\n  File \"/usr/lib64/python3.6/ssl.py\", line 1036, in do_handshake\n    self._sslobj.do_handshake()\n  File \"/usr/lib64/python3.6/ssl.py\", line 648, in do_handshake\n    self._sslobj.do_handshake()\nOSError: [Errno 0] Error\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1639149441.3062203-175-2960510232002/AnsiballZ_bigip_device_info.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1639149441.3062203-175-2960510232002/AnsiballZ_bigip_device_info.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1639149441.3062203-175-2960510232002/AnsiballZ_bigip_device_info.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.f5.bigip_device_info', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_bigip_device_info_payload_krptz0fm/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 16266, in <module>\n  File \"/tmp/ansible_bigip_device_info_payload_krptz0fm/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 16259, in main\n  File \"/tmp/ansible_bigip_device_info_payload_krptz0fm/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 15999, in exec_module\n  File \"/tmp/ansible_bigip_device_info_payload_krptz0fm/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 16075, in execute_managers\n  File \"/tmp/ansible_bigip_device_info_payload_krptz0fm/ansible_bigip_device_info_payload.zip/ansible/module_utils/network/f5/icontrol.py\", line 598, in modules_provisioned\n  File \"/tmp/ansible_bigip_device_info_payload_krptz0fm/ansible_bigip_device_info_payload.zip/ansible/module_utils/network/f5/bigip.py\", line 34, in api\n  File \"/tmp/ansible_bigip_device_info_payload_krptz0fm/ansible_bigip_device_info_payload.zip/ansible/module_utils/network/f5/bigip.py\", line 58, in connect_via_token_auth\n  File \"/tmp/ansible_bigip_device_info_payload_krptz0fm/ansible_bigip_device_info_payload.zip/ansible/module_utils/network/f5/icontrol.py\", line 238, in post\n  File \"/tmp/ansible_bigip_device_info_payload_krptz0fm/ansible_bigip_device_info_payload.zip/ansible/module_utils/network/f5/icontrol.py\", line 193, in send\n  File \"/tmp/ansible_bigip_device_info_payload_krptz0fm/ansible_bigip_device_info_payload.zip/ansible/module_utils/urls.py\", line 1294, in open\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 223, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 526, in open\n    response = self._open(req, data)\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 544, in _open\n    '_open', req)\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 504, in _call_chain\n    result = func(*args)\n  File \"/tmp/ansible_bigip_device_info_payload_krptz0fm/ansible_bigip_device_info_payload.zip/ansible/module_utils/urls.py\", line 467, in https_open\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 1351, in do_open\n    raise URLError(err)\nurllib.error.URLError: <urlopen error [Errno 0] Error>\n",
  "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
  "rc": 1,
  "_ansible_no_log": false,
  "changed": false
}

The host, awx trying to reach is a BigIP F5 appliance (v13.1.3.6)

Here is the playbook defined in the template
---
- name: Export certificate information
  hosts: all
  connection: local
  gather_facts: no
  
  vars:
     provider:
      user: "{{ LTM_user }}"
      password: "{{ LTM_pass }}"
      server: 10.173.68.2
      validate_certs: no
      server_port: 443

  tasks:
    - name: Generate ssl_report.csv
      shell: echo "Cert;Expiration;CN" > /var/lib/awx/projects/LTM/01.Report/cert_status.csv

    - name: Getting information SSL cert
      bigip_device_info:
        gather_subset:
            - ssl-certs
        provider: "{{ provider }}"
      #delegate_to: localhost
      register: sslcert
    #- debug:
    #    msg: "{{ sslcert }}"

    - name: Insert into csv
      shell: echo "{{ item.name }};{{ item.expiration_date }};{{ item.subject.split(',')[0].split('=')[1] }}" >> /var/lib/awx/projects/LTM/01.Report/cert_status.csv
      loop: "{{ sslcert.ssl_certs }}"

**Comment by shanemcd** [comment]
I see you are using AWX 17.1. We do not have the resources to support older versions. If you are seeing this on the latest version, please open a new issue.
