### ISSUE TITLE
Actionable feature request: running awx outside of kubectl as a system service

### ISSUE THREAD

**Issue by bitshiftnetau** [ansible/awx#11456]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
It would be much simpler to install, use, and maintain if there was an option to install this system as a native service. As it stands, the installation process is not just overly complicated but also dependant on very specific versions of kubectl.

**Comment by ffirg** [comment]
This will not be implemented By Red Hat, so I'm closing the request.
There are others that port to other platforms, and as different delivery options if this is not suitable as is.

**Comment by bitshiftnetau** [comment]
Ok cool, could you suggest who those others are?

**Comment by ffirg** [comment]
Join https://groups.google.com/g/awx-project and ask there.

**Comment by bitshiftnetau** [comment]
> Join https://groups.google.com/g/awx-project and ask there.

You can't just tell me here? Or do you not know.
