### ISSUE TITLE
Likely release problem with awx.awx collection

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#11460]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The AWX tags

https://github.com/ansible/awx/tags

are up to 19.5.0

But the last-released awx.awx collection is stuck on 19.4.0, from 2 months ago.

https://galaxy.ansible.com/awx/awx

The release pipeline is probably broken

**Comment by unixsysadmin** [comment]
Noticed that https://galaxy.ansible.com/awx/awx is now showing version 20.0.1, which matches the current AWX release.  Release pipeline now fixed?

**Comment by AlanCoding** [comment]
Correct, thanks for checking. Same with https://pypi.org/project/awxkit/#history. I believe the work was done in https://github.com/ansible/awx/pull/11834

Notifying @nixocio and @shanemcd here. Closing as fixed.
