### ISSUE TITLE
Unable to cancel system (management) jobs

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#11461]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

The cancel button appears to have no effect on Management Jobs started via the UI.

This affects things such as the "cleanup jobs" task, which often takes a very long time.

I have inserted a `time.sleep(60)` into the code and found that this delay is not sufficient to cancel it. It is probably not respecting cancel requests on any time scale.

### AWX version

19.5.0

### Installation method

docker on linux

### Modifications

no

### Ansible version

N/A

### Operating system

N/A

### Web browser

Chrome

### Steps to reproduce

Go to "Management Jobs" in the UI and launch a long-running job

try to cancel it once you are in the output details, or via the jobs list.

### Expected results

Job cancels.

### Actual results

The API request to cancel works normally, but the request is not respected by the task.

The task continues to completion. The purposed status in the UI of "canceled" changes to "successful" upon completion of the job, further demonstrating that the request was ignored.

**Comment by AlanCoding** [comment]
Note for QE:

I was only able to test this by adding a `time.sleep(60)` into the `handle` method of the cleanup jobs management command.

**Comment by tiagodread** [comment]
@thenets Closing this issue, since I ended up verifying the backport PR to 4.1.1.

I ran the chatty_task playbook on a schedule to generate events and ran the Cleanup Job Details, after cancelling the job while running the dispatcher logs was
```
2022-02-21 17:30:03,031 WARNING  [9c549156c9114750bd15cea482e095bf] awx.main.dispatch checking dispatcher running for ec2-3-83-1-236.compute-1.amazonaws.com
2022-02-21 17:30:03,049 WARNING  [bb9a7c1c03604977afffcf8e802ae383] awx.main.dispatch {'control': 'running', 'reply_to': 'reply_to_4973f0a9_6180_4c16_9939_234a53a5198d'}
2022-02-21 17:30:03,213 INFO     [bb9a7c1c03604977afffcf8e802ae383] awx.main.commands.run_callback_receiver Event processing is finished for Job 11, sending notifications
2022-02-21 17:30:03,252 WARNING  [bb9a7c1c03604977afffcf8e802ae383] awx.main.dispatch system_job 11 (canceled) was canceled (rc=254)
```

![image](https://user-images.githubusercontent.com/12464858/155004231-c147a41b-0e7c-437e-bf30-6da548d14e7d.png)

Last message on websocket connection:
```
{
    "unified_job_id": 115,
    "status": "canceled",
    "finished": "2022-02-21T19:21:34.058219Z",
    "group_name": "jobs",
    "unified_job_template_id": 1
}
```
