### ISSUE TITLE
there is no  cd /awx/installer/ after clonning the repo. neither install.yml

### ISSUE THREAD

**Issue by henmo009** [ansible/awx#11463]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

there is no  cd /awx/installer/ after clonning the repo. neither install.yml

### AWX version

latest

### Installation method

docker on linux

### Modifications

no

### Ansible version

n/a

### Operating system

n/a

### Steps to reproduce

n/a

### Expected results

n/a

### Actual results

n/a

### Additional information

n/a

**Comment by abcqwertz** [comment]
I guess you are looking for the install playbooks. Since AWX 18.0.0 the installation is done via the awx-operator. You can still install via AWX via Docker. For more info look here https://github.com/ansible/awx/blob/devel/INSTALL.md

**Comment by ffirg** [comment]
thanks @abcqwertz that is correct.
