### ISSUE TITLE
Unable to run more than one job in awx UI at a time

### ISSUE THREAD

**Issue by akcrisp** [ansible/awx#1146]
##### ISSUE TYPE

 - Bug Report
 

##### COMPONENT NAME

 - UI
 
##### SUMMARY
2 users execute jobs in ui - one immediately starts to run, other goes to pending state until first job finishes. 

The host holding the docker container has 16 gig of ram (circa 10 gig available). 

The job templates are using entirely different git repos (update on launch is not ticked), 

First job has 10 hosts in the inventory (forks at default)

second job has 4 hosts in the inventory (forks at 200)

##### ENVIRONMENT
* AWX version: 1,0.1.273
* AWX install method: docker on linux, 
* Ansible version:  2.4.2
* Operating System: rhel 7
* Web Browser: chrome 10

##### STEPS TO REPRODUCE

Configure 2 job templates, projects from git, inventory one using etcd, other is in awx internal inventory. 

one user executes their inventory in ui, other user executes, there one in ui, second one goes pending state.

##### EXPECTED RESULTS

both jobs should run simultanously

##### ACTUAL RESULTS
 first job runs,
second one remains in pending state until first finished.

**Comment by akcrisp** [comment]
Update: changing the forks from 200 to default - made by second job run in parrallel. So we need to determine why 200 caused an issue - according to the docs - it should be the limit of what is in the inventory anyway ie 4. 
From below referenced  doc - 
"The fork number is automatically limited to the number of possible hosts, so this is really a limit of how much network and CPU load you can handle. "

200 should not exceed the amount of ram if I follow the docs
http://docs.ansible.com/ansible-tower/latest/html/userguide/jobs.html

that calculates too 

2000 + ((16384 / 1024) - 2) * 75 = 3050 (I believe)

**Comment by akcrisp** [comment]
Ah so I think I've found the limit
node": "awx",
            "heartbeat": "2018-02-07T16:01:45.621128Z",
            "version": "1.0.1.273",
            "capacity": 1025

So is that 1025 being calculated by the above algorithms or is it hard coded ??

Setting forks 100 didn't work, but setting forks 50 did.

**Comment by akcrisp** [comment]
Actually I guess this is a usage question - so having searched the forums I found someone else asking the same thing - and they pointed at the code -

https://github.com/ansible/awx/blob/devel/awx/main/utils/common.py#L636 

So having run the commands by hand - on our host with 16 gig ram and 8 cpus - we get -

>>> import psutil
>>> from decimal import Decimal
>>> scale = Decimal(1.0)
>>> mem = psutil.virtual_memory().total
>>> cpu = psutil.cpu_count()
>>> cpu_cap = cpu * 4
>>> mem_cap = max(1, ((mem / 1024 / 1024) - 2048) / 100)
>>> cap = min(mem_cap, cpu_cap) + ((max(mem_cap, cpu_cap) - min(mem_cap, cpu_cap)) * scale)
>>> print cap
138

So the bit that now puzzles me is how the api is reporting 1025.

The other question is  - is this capacity dynamic or set statically on install ? ie if we add more ram to the box would it automatically increase the capacity ?

**Comment by matburt** [comment]
Tower capacity is a thing. For version 1.0.3.X I have updated the capacity algorithm a bit, see this documentation:  https://github.com/ansible/awx/blob/devel/docs/capacity.md

For 1.0.1 and current Tower releases you might be interested in a presentation I gave at Ansiblefest last year: https://www.youtube.com/watch?v=NiM4xNkauig  I go over capacity planning and algorithm in that video.

Also: http://docs.ansible.com/ansible-tower/latest/html/userguide/jobs.html#job-concurrency
