### ISSUE TITLE
AWX - No httponly flag for CSRF token

### ISSUE THREAD

**Issue by vandanakec** [ansible/awx#11479]
AWX -19.4.x
Minikube 1.23.2

I managed to add the CSRF token as httponly in setting.py file .
But the flag ( httponly) is still off for cookies CSRF userloggedin and currentuser token.
there is no httponly flag set in config js file .

Need to add this as a security feature.

![image](https://user-images.githubusercontent.com/41371948/146532714-acd64040-d642-4de5-b215-4c5327cc5e4e.png)

Can anyone help.

**Comment by AlanCoding** [comment]
Looks very similar https://github.com/ansible/awx/issues/11419

**Comment by shanemcd** [comment]
Closing in favor of https://github.com/ansible/awx/issues/11419
