### ISSUE TITLE
This document does not contains docker and docker compose, AWX tower installation steps

### ISSUE THREAD

**Issue by shajay12** [ansible/awx#1147]
##### ISSUE TYPE

  - Documentation

##### COMPONENT NAME

 - Installer

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: docker on linux
* Ansible version:  X.Y.Z
* Operating System: Centos 7
* Web Browser:

**Comment by jakemcdermott** [comment]
Documentation on docker and docker-compose based installation is found here: https://github.com/ansible/awx/blob/devel/INSTALL.md
