### ISSUE TITLE
Purge old stdout files in error

### ISSUE THREAD

**Issue by ReiNoIkari** [ansible/awx#11475]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Hello,

I have an AWX (17.0.1) setup and running using docker-compose method.

When parsing logs, I see that I have one task in failure, at ERROR level:

`Worker failed to run task awx.main.tasks.purge_old_stdout_files(*[], **{}`

Full error is as follow :

```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/dispatch/worker/task.py", line 86, in perform_work
    result = self.run_callable(body)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/dispatch/worker/task.py", line 62, in run_callable
    return _call(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 421, in purge_old_stdout_files
    for f in os.listdir(settings.JOBOUTPUT_ROOT):
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/awx/job_status'
```

No modification to the docker have been done, and it seems it have been happening for weeks now.

Could you please provide a way to fix the error ?
AWX logs are linked to a third party application that raise an alert regularly due to this.

Thanks.

### AWX version

17.0.1

### Installation method

docker on linux

### Modifications

no

### Ansible version

2.9.17

### Operating system

CentOS

### Steps to reproduce

1. Install AWX 17.0.1 using docker-compose method

### Expected results

No message at error level inside logs

### Actual results

I have an error rising in AWX logs every time purge is executed

**Comment by AlanCoding** [comment]
This method `purge_old_stdout_files` is only used when the user downloads the standard out file for a job to my knowledge. Does that match with your usage?

**Comment by shanemcd** [comment]
Hello. We do not have the resources to support older versions of AWX. If you upgrade and see this on the latest release, please open a new issue.
