### ISSUE TITLE
Job  running forever and empty output

### ISSUE THREAD

**Issue by kotnn** [ansible/awx#11473]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Hello. I just set up AWX-Ansible and trying to create ssh credential to access to my Git hosted on Azure Devops Server.
1) Generate SSH key pair, upload public key to Azure Devops Server
2) I create "Credential" object with type of "Source control", specify "SCM Private Key" and set private key generated on step 1
3) create project, specify SSH url to my Source Control Repo, select my credential object from previous step , set "Update Revision on Launch" -> save
4) in Jobs I se my  syncronization job , but it runs infinitely an without any output

### AWX version

19.5.0

### Installation method

kubernetes

### Modifications

yes

### Operating system

Windows Server 2019

### Web browser

Chrome

### Steps to reproduce

1) Generate SSH key pair, upload public key to Azure Devops Server
2) I create "Credential" object with type of "Source control", specify "SCM Private Key" and set private key generated on step 1
![image](https://user-images.githubusercontent.com/38759038/146266895-385502bd-4bb2-4a22-a19d-fb04b07e4300.png)

3) create project, specify SSH url to my Source Control Repo, select my credential object from previous step , set "Update Revision on Launch" -> save
![image](https://user-images.githubusercontent.com/38759038/146267084-2aa1d7c0-bea0-4cd0-9ef3-e8faf1d8ebd5.png)

4) in Jobs I se my  syncronization job , but it runs infinitely an without any output
![image](https://user-images.githubusercontent.com/38759038/146267182-0a77d673-8950-4882-96af-c7489293ac76.png)
![image](https://user-images.githubusercontent.com/38759038/146267211-47e52d75-db28-4bfd-8e02-71a326c09cf7.png)

### Expected results

at least see any output of job 

### Actual results

job runs infinitely and nothing in output

### Additional information

i set up Ansible with Flux:

mkdir C:\Deployment\awx-operator
git clone https://github.com/ansible/awx-operator.git
cd .\awx-operator\
git checkout 0.15.0
kustomize edit set image controller=quay.io/ansible/awx-operator:0.15.0
mkdir C:\Deployment\OS33K8S\clusters\os33dev\awx-operator\
kustomize build >> C:\Deployment\OS33K8S\clusters\os33dev\awx-operator\resources.yaml
git add -A ; git commit -m "Add awx operator initial setup files"; git push

then created AWX tin the same way: create file and then commit to git repo:

---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  namespace: awx
  name: awx
spec:
  service_type: nodeport  
  nodeport_port: 30080
  ingress_type: ingress
  ingress_path: /
  ingress_tls_secret: os33dev-net-tls-secret
  hostname: awx.os33dev.net  
  postgres_storage_requirements:
    requests:
      storage: 2Gi
    limits:
      storage: 4Gi    
  postgres_storage_class: ansible
  projects_persistence: true  
  projects_storage_class: ansible
  projects_storage_size: 2Gi    
  projects_storage_access_mode: ReadWriteMany

**Comment by stefanpinter** [comment]
oh yes, I am glad I found this thread, although no reply is in here yet.

i have the same problem but with a few differences:

- problem started out of the blue in the night from tuesday to wednesday

- using github repositoy with ssh
(tcpdump isnt showing anything happening related to port 22 when starting a project update-job)

- problem started with awx 19.3.0
project refresh was on "Running" forever, but clicking on it told me about error 500. digging deeper there was a postgre-error 
max_locks_per_transaction. 19.3.0 was installed using this method: https://raw.githubusercontent.com/aderusha/aderusha.github.io/master/

- killed 19.3.0 by trying to upgrade to 19.5.0 and setting this max_locks_per_transaction stuff.

- using a ubuntu 20.04 VM
set up fresh AWX 19.5.0 multiple times via https://github.com/kurokobo/awx-on-k3s

- empty project update job since 19.5.0 (previously error 500)

**Comment by stefanpinter** [comment]
@kotnn 
did you try giving the URL like this?
![image](https://user-images.githubusercontent.com/70375226/146565655-9b73e9b3-f6c3-4064-b876-32273bca2b5f.png)

**Comment by AlanCoding** [comment]
Did you see any relevant logs when this happened? If it's not too much, maybe you could run strace on a related dispatcher process (find running `awx-manage run_dispatcher --status`) to see if it's stuck on a read?

**Comment by kotnn** [comment]
I have no time for troubleshooting now, therefore i've set up docker version https://github.com/ansible/awx/blob/17.0.1/INSTALL.md 
and it works as expected

**Comment by stefanpinter** [comment]
ok, FINALLY most jobs run fine again... but some jobs do bad stuff.

job starts, no output while running, not even when refreshing via F5, then the job errors with either
- Logs stop in the middle of the run (no summary, stopped in the middle of a task)
or
- Error creating pod: timed out waiting for the condition, ImagePullBackOff
- no log at all


awx-manage run_dispatcher --status
Recorded at: 2021-12-22 13:24:33 UTC
awx-ff5bd7695-qw8zv[pid:31] workers total=4 min=4 max=20

.  worker[pid:4528] sent=5 finished=4 qsize=1 rss=133.012MB
     - running 44639df6-2aab-459a-b4ad-ab2edbd22a80 RunJob(*[131])
.  worker[pid:4549] sent=4 finished=4 qsize=0 rss=125.961MB [IDLE]
.  worker[pid:4571] sent=3 finished=2 qsize=1 rss=125.914MB
     - running 2b6e7447-c27a-4a9d-88a6-f64c30ed6861 awx_periodic_scheduler(*[])
.  worker[pid:4573] sent=1 finished=1 qsize=0 rss=125.719MB [IDLE]


how can I strace these pids? where can I find these processes? I can't find them anywhere

**Comment by stefanpinter** [comment]
i doubled up CPU count to 4 and RAM to 8GB, but it is still happening...
stops in the middle of a job, goes to "error", an the log just stops:


...
TASK [Test php7.0-fpm] *********************************************************
skipping: [aztjc001]
skipping: [aztjc002]
skipping: [vpadm001]
...


But there should be 30 hosts, not 3

**Comment by stefanpinter** [comment]
oh, this is what I experience as well https://github.com/ansible/awx/issues/11451

**Comment by shanemcd** [comment]
Closing as the original author of this issue says they dont have time to troubleshoot.

If someone is seeing this and can provide the information needed to help us diagnose, please open a new issue.
