### ISSUE TITLE
Missing libraries in awx_task container

### ISSUE THREAD

**Issue by geerlingguy** [ansible/awx#1148]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

After building the two Dockerfiles using the setup playbook, I ran into two issues with the task container when running it (it would never start the channels-worker):

* `ImportError: No module named coreapi.document` (fixed with `pip install coreapi` inside the container).
* `ImportError: No module named rest_framework_swagger` (fixed with `pip install django-rest-swagger` inside the container).

It seems like these dependencies were added in this commit: https://github.com/ansible/awx/commit/57c22c20b26aeaaa3230d61b384870ce8648985e

##### ENVIRONMENT
* AWX version: devel
* AWX install method: docker for linux
* Ansible version:  2.4.3
* Operating System: CentOS 7
* Web Browser: Safari

##### STEPS TO REPRODUCE

Build the containers.

##### EXPECTED RESULTS

The containers would boot properly.

##### ACTUAL RESULTS

The task container hit an endless loop of the two above fatal errors and would never start.

##### ADDITIONAL INFORMATION

N/A

**Comment by geerlingguy** [comment]
Hmm, looking through the past two days' commits, there are a number of commits mentioning fixing new imported libraries relating to swagger... I'll sync locally with the latest devel commits and see if I can get things to work just be rebuilding again.

Still, I don't see anything anywhere in the repo that requires `coreapi`...

**Comment by ryanpetrello** [comment]
@geerlingguy mind giving this another shot on `devel`?  This came about due to a change I made yesterday, and I believe it's fixed now.

**Comment by shanemcd** [comment]
(I'm pushing new images to dockerhub now.)

**Comment by geerlingguy** [comment]
@ryanpetrello - Thanks, will rebuild and see what happens.

**Comment by geerlingguy** [comment]
Rebuild worked great, new containers start up correctly. Feel free to close this is there are no new issues otherwise.

**Comment by geerlingguy** [comment]
Heh, or I just closed it... so feel free to open it back up if needed.
