### ISSUE TITLE
awx-operator ImagePullBackOff

### ISSUE THREAD

**Issue by Jonathan-Caruana** [ansible/awx#11493]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

On fresh install when i try to deploy awx-operator the status of the pod is : ImagePullBackOff

### AWX version

19.5.0

### Installation method

minikube

### Modifications

no

### Ansible version

2.9.27

### Operating system

CentOS 8

### Web browser

Chrome

### Steps to reproduce

1. dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
2. dnf update
3. dnf install docker-ce socat tc git curl conntrack -y
4. systemctl start docker.service
5. systemctl enable docker.service
6. curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
7. chmod +x kubectl && mv kubectl /usr/bin/
8. curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
9. chmod +x minikube && mv minikube /usr/bin/
10. disable swap in fstab + swapoff -a
11. echo “net.bridge.bridge-nf-call-iptables = 1”>> /etc/sysctl.conf
12. sysctl -p
13. minikube start --driver=none
14. systemctl enable kubelet.service
15. git clone https://github.com/ansible/awx-operator/
16. cd awx-operator/
17. git checkout -b 0.15.0
18. export NAMESPACE=test
19. make deploy

### Expected results

awx-operator pod should be in "Running" state

### Actual results

awx-operator pod is in "ImagePullBackOff" state

### Additional information

I think the main problem is link to the version that the pod tried to pull : 

Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  5m32s                  default-scheduler  Successfully assigned integration/awx-operator-controller-manager-57675b7b5c-46z8k 
  Normal   Pulled     5m29s                  kubelet            Container image "gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0" already present on machine
  Normal   Created    5m28s                  kubelet            Created container kube-rbac-proxy
  Normal   Started    5m27s                  kubelet            Started container kube-rbac-proxy
  Normal   Pulling    4m5s (x4 over 5m27s)   kubelet            Pulling image "quay.io/ansible/awx-operator:0.15.0-19-g4a43de5"
  Warning  Failed     4m3s (x4 over 5m26s)   kubelet            Failed to pull image "quay.io/ansible/awx-operator:0.15.0-19-g4a43de5": rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/ansible/awx-operator:0.15.0-19-g4a43de5 not found: manifest unknown: manifest unknown
  Warning  Failed     4m3s (x4 over 5m26s)   kubelet            Error: ErrImagePull
  Warning  Failed     3m52s (x5 over 5m25s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    26s (x20 over 5m25s)   kubelet            Back-off pulling image "quay.io/ansible/awx-operator:0.15.0-19-g4a43de5"

According to the quay.io directory, this image "awx-operator:0.15.0-19-g4a43de5" doesn't exist.

**Comment by haijeploeg** [comment]
I ran into this issue as well and found out that the makefile is using `git describe --tags` to determine the version it should pull. You cloned the repository and then did a checkout with the `-b` flag. This means you create a new branch called `0.15.0` locally, but this is not the upstream branch. The command will still return `0.15.0-19-g4a43de5` as the version.

You can fix this by running: `git checkout 0.15.0` (without the `-b` flag and run `make deploy` again. You should probably cleanup the namespace (**test**) in your case and remove the cloned folder and re-clone to start over clean.

**Comment by Jonathan-Caruana** [comment]
thank you @haijeploeg i will try your solution in the coming days !

**Comment by rimkov** [comment]
Hello 
i got the same error, but i did a git checkout without -b flag. i used this documentation https://github.com/ansible/awx-operator
i'm under ubuntu 20.04. In december everything gone fine...

what i did :

```
minik@pilot2:~$ cd awx-operator
minik@pilot2:~/awx-operator$ git switch -c 0.15.0
Switched to a new branch '0.15.0'
minik@pilot2:~/awx-operator$ git checkout
minik@pilot2:~/awx-operator$ git branch
* 0.15.0
  devel

minik@pilot2:~/awx-operator$ minikube start --cpus=4 --memory=3g --addons=ingress,dashboard
minik@pilot2:~/awx-operator$ make deploy
namespace/awx created
customresourcedefinition.apiextensions.k8s.io/awxbackups.awx.ansible.com created
....
....
configmap/awx-operator-awx-manager-config created
service/awx-operator-controller-manager-metrics-service created
deployment.apps/awx-operator-controller-manager created

minik@pilot2:~/awx-operator$ kubectl apply -f awx-demo.yml
awx.awx.ansible.com/awx-demo created

minik@pilot2:~/awx-operator$ kubectl get pods -n $NAMESPACE
NAME                                              READY   STATUS         RESTARTS   AGE
awx-operator-controller-manager-6f7f978c4-l2h7s   1/2     ErrImagePull   0          16s

```

Here is what i found with minikube logs

**ErrImagePull: rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/ansible/awx-operator:0.15.0-24-gcb9e44f not found: manifest unknown: manifest unknown**


`Jan 13 19:54:31 minikube kubelet[2098]: E0113 19:54:31.575160    2098 kuberuntime_manager.go:898] container &Container{Name:awx-manager,Image:quay.io/ansible/awx-operator:0.15.0-24-gcb9e44f,Command:[],Args:[--health-probe-bind-address=:6789 --metrics-bind-address=127.0.0.1:8080 --leader-elect --leader-election-id=awx-operator],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{EnvVar{Name:ANSIBLE_GATHERING,Value:explicit,ValueFrom:nil,},EnvVar{Name:ANSIBLE_DEBUG_LOGS,Value:false,ValueFrom:nil,},EnvVar{Name:WATCH_NAMESPACE,Value:,ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.namespace,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,},},},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:kube-api-access-j47q7,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:&Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/healthz,Port:{0 6789 },Host:,Scheme:HTTP,HTTPHeaders:[]HTTPHeader{},},TCPSocket:nil,},InitialDelaySeconds:15,TimeoutSeconds:1,PeriodSeconds:20,SuccessThreshold:1,FailureThreshold:3,TerminationGracePeriodSeconds:nil,},ReadinessProbe:&Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/readyz,Port:{0 6789 },Host:,Scheme:HTTP,HTTPHeaders:[]HTTPHeader{},},TCPSocket:nil,},InitialDelaySeconds:5,TimeoutSeconds:1,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,TerminationGracePeriodSeconds:nil,},Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:&SecurityContext{Capabilities:nil,Privileged:nil,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:*false,RunAsGroup:nil,ProcMount:nil,WindowsOptions:nil,SeccompProfile:nil,},Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,} start failed in pod awx-operator-controller-manager-6f7f978c4-l2h7s_awx(914686de-5ba1-4c39-9b38-67d591fe744f): ErrImagePull: rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/ansible/awx-operator:0.15.0-24-gcb9e44f not found: manifest unknown: manifest unknown`

thank you for your help

**Comment by rimkov** [comment]
update : it's ok with git checkout 0.15.0
I will warn you if I find the documentation where I saw the command git switch -c 0.15.0
sorry for the noise. thank you :)
