### ISSUE TITLE
UI - Credential usage 

### ISSUE THREAD

**Issue by Tioborto** [ansible/awx#11492]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
It would be interesting to identify the job templates using a credential at the credential level
Example : we have the list of job templates of a project at the project level

![awx-ui](https://user-images.githubusercontent.com/29703972/147461432-b75068c6-f2ae-44a9-baff-416680ffc862.png)

**Comment by shanemcd** [comment]
Dupe of https://github.com/ansible/awx/issues/5867
