### ISSUE TITLE
Getting HTTP Basic: Access denied on self-hosted Gitlab

### ISSUE THREAD

**Issue by terminalrally** [ansible/awx#11491]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

I've tried 3 different ways of syncing with a self-hosted GitLab repository and none work. I followed multiple different guides online from Red Hat, Ansible docs, and personal blogs. I've exhausted nearly every possible solution I could think of.

### AWX version

latest

### Installation method

minikube

### Modifications

no

### Ansible version

2.9.25

### Operating system

RHEL 8

### Steps to reproduce

1. Create internal user on self-hosted GitLab instance
2. Create personal access token for user
3. Generate keypair and add public SSH key to user
4. Create AWX credential with user:access_token
5. Create project to sync private repository over HTTPS
6. It doesn't work, try with private key, user password, SSH, git://, etc. They all don't work with different error messages relating to authentication.

### Expected results

The repository should sync over HTTPS or SSH using either username and password, access_token, or SSH key.

### Actual results

Over HTTPS with username + access_token or password:
```
remote: HTTP Basic: Access denied
Fatal: authentication failed for 'https://git.example.com/username/repository.git/'
```

Over SSH with private key:
```
Warning:********@git.example.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password,keyboard-interactive).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.
```

**Comment by ffirg** [comment]
You might want to try upgrading to ansible 2.11 and try that.

**Comment by terminalrally** [comment]
> You might want to try upgrading to ansible 2.11 and try that.

2.9.25 is the latest version supported on RHEL.

**Comment by agrisvv** [comment]
i can say what works today:
awx 19.4 with awx-ee (latest or 6.0) + gitlab 14.6 + user with username and password over HTTPS.

**Comment by ffirg** [comment]
@johnathonmatczak please try the working combo suggested by @agrisvv. Thanks both.

**Comment by shanemcd** [comment]
Going to close this, as it seems like this is working for others. If this is still a problem, please open a new issue.
