### ISSUE TITLE
Install fails on image-build due to UI dependencies

### ISSUE THREAD

**Issue by knechtionscoding** [ansible/awx#115]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT
 - Installer

##### SUMMARY
After doing a clean install of Centos 7.3.1, cloning the newest version of AWX, installing dependencies, and running the local_docker installer the following error occurs on image_build : Build AWX Distribution: 

`fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "npm --unsafe-perm --prefix awx/ui install awx/ui\nnpm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nmake: *** [awx/ui/.deps_built] Killed\nnpm --unsafe-perm --prefix awx/ui install awx/ui\nnpm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nmake: *** [awx/ui/.deps_built] Killed\nnpm --unsafe-perm --prefix awx/ui install awx/ui\nnpm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nmake: *** [awx/ui/.deps_built] Killed\n", "status": 2}
`

##### STEPS TO REPRODUCE

Install CentOS 7.3.1611, install prereqs, clone repo, run install.yml

##### EXPECTED RESULTS

complete install
##### ACTUAL RESULTS

`fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "npm --unsafe-perm --prefix awx/ui install awx/ui\nnpm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nmake: *** [awx/ui/.deps_built] Killed\nnpm --unsafe-perm --prefix awx/ui install awx/ui\nnpm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nmake: *** [awx/ui/.deps_built] Killed\nnpm --unsafe-perm --prefix awx/ui install awx/ui\nnpm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nmake: *** [awx/ui/.deps_built] Killed\n", "status": 2}`

##### ADDITIONAL INFORMATION

It appears to be an issue with one of the dependencies in the packages.json file. Not sure which one relies on minimatch.

**Comment by matburt** [comment]
Does the install hang or fail?

**Comment by BastienM** [comment]
See #78 for solutions.

**Comment by knechtionscoding** [comment]
@matburt It hard failed out.

@BastienM I'll read through that now.

**Comment by matburt** [comment]
can you re-pull and try the installer after this PR https://github.com/ansible/awx/pull/104 ?

This is an attempt to simplify local dependencies from those that we actually need to build AWX.

**Comment by knechtionscoding** [comment]
@matburt This was cloned this morning. I got it after 109 was merged, I believe, so I've got 104 in here already. Running a git pull tells me I'm up to date. I'm testing the changes mentioned in #78 (Specifically updating babel-istanbul) and seeing if that resolves it.

**Comment by knechtionscoding** [comment]
After running the suggested fixes in #78 the error still occurs:

`*
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "npm --unsafe-perm --prefix awx/ui install awx/ui\nnpm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nmake: *** [awx/ui/.deps_built] Killed\nnpm --unsafe-perm --prefix awx/ui install awx/ui\nnpm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nmake: *** [awx/ui/.deps_built] Killed\nnpm --unsafe-perm --prefix awx/ui install awx/ui\nnpm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nmake: *** [awx/ui/.deps_built] Killed\nnpm --unsafe-perm --prefix awx/ui install awx/ui\nnpm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nmake: *** [awx/ui/.deps_built] Killed\nnpm --unsafe-perm --prefix awx/ui install awx/ui\nnpm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nmake: *** [awx/ui/.deps_built] Killed\nnpm --unsafe-perm --prefix awx/ui install awx/ui\nnpm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nmake: *** [awx/ui/.deps_built] Killed\n", "status": 2}
`

I've confirmed that bzip is installed, and babel-instabul is updated in the awx/awx folder.

**Comment by matburt** [comment]
The `Killed` line leads me to believe you may be running into an out-of-memory scenario? Most of the npm errors there are just warnings and I'm not seeing the error stanzas out of npm either, but the `Killed` line is definitely something you'll see if the OS kills the process for OOM.

Note that building the UI is going to be a pretty memory/cpu intensive process.

**Comment by knechtionscoding** [comment]
Okay. I'll up the memory here and see if that resolves it.

**Comment by BastienM** [comment]
```
TASK [image_build : Build AWX distribution] *************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "npm --unsafe-perm --prefix awx/ui install awx/ui\nmake: *** [awx/ui/.deps_built] Killed\n", "status": 2}
```

I guess I will have to give my VM more ram ... damn it consumes even more than Chrome.

**Comment by knechtionscoding** [comment]
@matburt Bumping the Droplet up to 16GB of ram fixed the issue. I have a feeling that #78 is also resolved by increasing the base specs on the host.

I assume that the hardware requirements are the same as tower?

**Comment by shanemcd** [comment]
@KnechtionsCoding What were the specs of your droplet before bumping to 16 GB?

**Comment by knechtionscoding** [comment]
@shanemcd 1gb and 1 CPU. 

@matburt I added a Hardware Recommendation Section to the Install.md because I couldn't find any outside of the Tower Documentation, which I only looked at after you mentioned RAM amount.

**Comment by matburt** [comment]
well 1gb is probably too low but 16G is a bit overkill. Note that *building* is more expensive than running AWX... I think I have successfully built in something running in the 2g - 4g range.

**Comment by hsolomon** [comment]
I can confirm that I was able to build it with a minimum of 2GB RAM. Note that it also requires about 4G disk space under /var/lib/docker for the initial images.  One of the images is a postgres databse so add enough room  for growth.
