### ISSUE TITLE
Cannot create manual project in Japanese (possibly all non-English languages)

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#11505]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### AWX version

19.5.0

### Installation method

docker for mac

### Modifications

no

### Steps to reproduce

1. Compile strings
2. Start up AWX
3. Set default browser language to Japanese (UI should now render in Japanese for translated strings)
4. Attempt to create a manual project

### Expected results

A manual project is created

### Actual results

Project creation fails

### Additional information

I suspect that we are sending the translated string back to the API rather than `manual` which is what it is expecting.

**Comment by nixocio** [comment]
@mabashian I bumped the priority since with my initial tests any language different than English can not create a manual project. Since the subform is not being rendering.

**Comment by InnocentK** [comment]
Resolved
