### ISSUE TITLE
TypeError: super() takes at least 1 argument

### ISSUE THREAD

**Issue by bossi86** [ansible/awx#11502]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
When using a higher version auf awx.awx then 19.2.0 usage of some moduls fail with a python Error "TypeError: super() takes at least 1 argument (0 given)"

##### ENVIRONMENT
* Ansible Tower version: 3.8.4
* Operating System: RHEL 7.9
* Python Version: 2.7.5

##### STEPS TO REPRODUCE

`- name: "set the license"
  awx.awx.tower_license:
    tower_host: "localhost"
    manifest: "{{ license_file }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_admin_password }}"
    validate_certs: false
`

##### EXPECTED RESULTS

Set the license in Tower.

##### ACTUAL RESULTS

`TASK [configure_tower : set the license] ***************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: super() takes at lea                   st 1 argument (0 given)
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line                    102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr                   /lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", li                   ne 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, i                   n _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_awx.awx.tower_license_payload_poaTKh/ansible_awx.awx.tower_lice                   nse_payload.zip/ansible_collections/awx/awx/plugins/modules/tower_license.py\", line 93, in <module>\n  File \"/tmp/ansible_awx.                   awx.tower_license_payload_poaTKh/ansible_awx.awx.tower_license_payload.zip/ansible_collections/awx/awx/plugins/modules/tower_lic                   ense.py\", line 54, in main\n  File \"/tmp/ansible_awx.awx.tower_license_payload_poaTKh/ansible_awx.awx.tower_license_payload.zi                   p/ansible_collections/awx/awx/plugins/module_utils/controller_api.py\", line 307, in __init__\nTypeError: super() takes at least                    1 argument (0 given)\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
`

##### ADDITIONAL INFORMATION

The same happens with the credential module.
`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: super() takes at least 1 argument (0 given)
failed: [localhost] (item={u'path': u'community', u'name': u'community'}) => {"aah_remote_repo": {"name": "community", "path": "community"}, "ansible_loop_var": "aah_remote_repo", "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_awx.awx.credential_payload_mb0pwq/ansible_awx.awx.credential_payload.zip/ansible_collections/awx/awx/plugins/modules/credential.py\", line 300, in <module>\n  File \"/tmp/ansible_awx.awx.credential_payload_mb0pwq/ansible_awx.awx.credential_payload.zip/ansible_collections/awx/awx/plugins/modules/credential.py\", line 222, in main\n  File \"/tmp/ansible_awx.awx.credential_payload_mb0pwq/ansible_awx.awx.credential_payload.zip/ansible_collections/awx/awx/plugins/module_utils/controller_api.py\", line 307, in __init__\nTypeError: super() takes at least 1 argument (0 given)\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: super() takes at least 1 argument (0 given)
failed: [localhost] (item={u'path': u'rh-certified', u'name': u'Red Hat certified'}) => {"aah_remote_repo": {"name": "Red Hat certified", "path": "rh-certified"}, "ansible_loop_var": "aah_remote_repo", "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_awx.awx.credential_payload_NsbrYA/ansible_awx.awx.credential_payload.zip/ansible_collections/awx/awx/plugins/modules/credential.py\", line 300, in <module>\n  File \"/tmp/ansible_awx.awx.credential_payload_NsbrYA/ansible_awx.awx.credential_payload.zip/ansible_collections/awx/awx/plugins/modules/credential.py\", line 222, in main\n  File \"/tmp/ansible_awx.awx.credential_payload_NsbrYA/ansible_awx.awx.credential_payload.zip/ansible_collections/awx/awx/plugins/module_utils/controller_api.py\", line 307, in __init__\nTypeError: super() takes at least 1 argument (0 given)\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
`

**Comment by shanemcd** [comment]
Hello. This is an issue tracker for the upstream AWX project. If you are a Tower customer, please open up a support issue and they will help you out.

**Comment by bossi86** [comment]
Hello. This issue is not related to AWX or Tower. This is a problem that exists in Ansible regardless of AWX or Tower. Please reopen the issue.

**Comment by MLegkovskis** [comment]
Also having the same issue.

Ansible Tower version: 3.8.4
Operating System: RHEL 7.9
Python Version: 2.7
