### ISSUE TITLE
Upgrade to Python 3.9

### ISSUE THREAD

**Issue by shanemcd** [ansible/awx#11507]
The next major version of RHEL will only provide Python 3.9.

This ticket is meant to track the work needed to update the development environment and the upstream deployment.

As a part of this work, we may need to move to CentOS Stream.

Before merging anything here, we will need to engage with the productization team to ensure that downstream builds are functional.

**Comment by shanemcd** [comment]
I have assigned myself here because I plan to be involved in some here in some capacity as it will affect our development environment. If someone else wants to drive, let me know. Either way, I am happy to pair on this.

**Comment by dsavineau** [comment]
> The next major version of RHEL will only provide Python 3.10.

that's Python 3.9 not 3.10

**Comment by shanemcd** [comment]
@dsavineau Yep, seems like you left this comment 4 seconds after I changed the title 😅 Thank you.

**Comment by shanemcd** [comment]
PR has been merged. Nothing for QE to test here until the downstream packages have been updated to use python3.9 as well.
