### ISSUE TITLE
awx with nginx http auth

### ISSUE THREAD

**Issue by keith6014** [ansible/awx#11516]
Using nginx's http authentication is it possible to single sign on with AWX setup with LDAP? Similar to Grafana https://community.grafana.com/t/grafana-nginx-auth-proxy/215?

**Comment by shanemcd** [comment]
Hello,

This issue tracker is for tracking feature enhancements and bugs.

If you need help troubleshooting or are looking for help using AWX, try our mailing list or IRC channel:

#ansible-awx on https://libera.chat/
https://groups.google.com/forum/#!forum/awx-project
