### ISSUE TITLE
/api/v2/ping is returning wrong value in "heartbeat" field

### ISSUE THREAD

**Issue by mvalsecc** [ansible/awx#11523]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Summary:
I believe that this behavior where two endpoints ( `/api/v2/ping` and `/api/v2/instances/` ) return different values for the same "heartbeat" like field is not consistent, and I think that `/api/v2/ping` "heartbeat" field should be mapped to `last_health_check` field of `Instance` model.

Details:
In AAP1.2 (Tower 3.8.4) `/api/v2/ping` response, "heartbeat" field was mapped to `instance.modified` (*),  and the value "heartbeat" field in the response was returning a new updated value every minute. 

~~~
/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/views/root.py
class ApiV2PingView(APIView):
...
    def get(self, request, format=None):
...
        for instance in Instance.objects.all():
            response['instances'].append(dict(node=instance.hostname, uuid=instance.uuid, heartbeat=instance.modified, <===
                                              capacity=instance.capacity, version=instance.version))
~~~

This is not the case anymore in AAP2.1 (Ansible Automation Platform Controller 4.1.0).

I see that in AAP2.1 (Ansible Automation Platform Controller 4.1.0)  `/api/v2/ping` "heartbeat" field is **still** mapped to modified , and not to `last_seen` nor to `last_health_check` that have been introduced for this purpose. 

~~~
/var/lib/awx/venv/awx/lib/python3.8/site-packages/awx/api/views/root.py
    133 class ApiV2PingView(APIView):
    134     """A simple view that reports very basic information about this
    135     instance, which is acceptable to be public information.
    136     """
..
    143     def get(self, request, format=None):
...
    152         for instance in Instance.objects.all():
    153             response['instances'].append(
    154                 dict(
...
    158                     heartbeat=instance.modified, <=======
...
~~~

Because of that, `/api/v2/ping` will not return a new value every minute, it will return a new value only if the user fiddles manually with the instance properties (e.g. any change on Administration > Instance Group > "any instance group" > Instance Page, etc.).

Now, being said that in  AAP2.1 (Ansible Automation Platform Controller 4.1.0)  `/api/v2/instances/` **does** return correctly all the fields, including last_seen and last_health_check  which are updated every minute as expected.

(*) back then, there was no `last_seen` nor `last_health_check` field in the Instance model

### AWX version

Red Hat Downstream AAP2.1

### Installation method

docker on linux

### Modifications

no

### Ansible version

Ansible Automation Platform Controller 4.1.0 

### Operating system

Linux RHEL8.3

### Web browser

Firefox

### Steps to reproduce

Access `https://<awx-url>/api/v2/ping/` and compare the response with the one from `https://192.168.122.106/api/v2/instances/`.
"heartbeat" value from `ping` endpoint will be older than the same value from `instances` endpoint.

### Expected results

"heartbeat" value from `ping` endpoint should match "last_seen" and "last_health_check" values from `instances` endpoint results.
(Not sure about "last_seen", but in my tests, said field have always had the same value as "last_health_check" field so far)

### Actual results

"heartbeat" value from `ping` endpoint will be older than the same value from `instances` endpoint.

### Additional information

Likely related commit: https://github.com/ansible/tower/commit/6a17e5b65bf9421c2e650d23817c79ce81248c6f
Likely related issue: https://github.com/ansible/awx/issues/10737

**Comment by CFSNM** [comment]
Created PR to add new automated tests for this issue. 

Can I get some eyes, please? @nixocio @AlanCoding

**Comment by CFSNM** [comment]
The PR https://github.com/ansible/tower-qa/pull/7112 is ready to be merged to devel. Once the PR https://github.com/ansible/awx/pull/11539 is merged to devel, I will merge my PR too and will close the issue

**Comment by CFSNM** [comment]
Merged QE PR to devel. Closing
