### ISSUE TITLE
Inventory > Hosts > Run Command breaks if credential needs password

### ISSUE THREAD

**Issue by natedogith1** [ansible/awx#11529]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When Running a command over an inventory (via Inventory > Hosts > Run Command), if the selected credential needs a password (like if the credential is set to prompt for the private key passphrase), it fails without ever prompting.

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: don't know
* AWX deployment target: don't know
* Operating System: Web Browser is being used from Windows 10
* Web Browser: Microsoft Edge Version 97.0.1072.55 (Official build) (64-bit)

##### STEPS TO REPRODUCE
1. add a credential with an encrypted SSH Private Key
2. set Private Key Passphrase to Prompt on launch
3. navigate to the hosts tab in an inventory
4. select Run Command
5. select the ping command
6. select the added credential
7. click Launch

##### EXPECTED RESULTS
I expected a new "Credential passwords" item to show up, like it does when launching a template.

##### ACTUAL RESULTS
A message box with these contents:

Error!
Failed to launch job.

Details
POST /api/v2/inventories/23/ad_hoc_commands/ 400
ssh_key_unlock

##### ADDITIONAL INFORMATION
![image](https://user-images.githubusercontent.com/1638163/149237017-fe7251de-8653-4ab6-b2da-80b04fc44497.png)

**Comment by InnocentK** [comment]
Resolved

**Comment by sflotat** [comment]
Hi 
I'm using AWX 15.1. and I have same problem (instead of getting my ssh passphrase ask window, i get an error message). Do you think it is possible to modify my AWX 15.1 release with changes describe in #11598 ?
Actually we have not planned to upgrade to latest docker release (17).

**Comment by AlexSCorey** [comment]
@sflotat Thanks for reaching out to us.  We recommend that you upgrade to the latest version of AWX to get the patch for this bug.
