### ISSUE TITLE
fail to run vmware_guest_facts without uuid

### ISSUE THREAD

**Issue by gripenk** [ansible/awx#1155]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### ENVIRONMENT
* AWX version: 1.0.3.0
* AWX install method: docker on linux
* Ansible version:  2.4.3.3 (bundled in docker image)
* Operating System: centos 6.9
* Web Browser: Chrome

##### STEPS TO REPRODUCE

running the following playbook

- hosts: all
  vars:
    uname: <MASKED>
  tasks:
    - name: getfact
      vmware_guest_facts:
        hostname: <MASKED>
        username: "{{ uname }}"
        password: "{{ mypass }}"
        datacenter: "ITS Cloud"
        folder: <MASKED>
        validate_certs: no
        name: V6-WebCloud-template-6.5-php56-L02B1
      connection: local
    - debug: 
        var: vm_fact

##### EXPECTED RESULTS

it runs and print out the vm information

##### ACTUAL RESULTS

it fails with 
{
    "_ansible_parsed": true,
    "invocation": {
        "module_args": {
            "username": <MASKED>,
            "datacenter": "ITS Cloud",
            "name": "V6-WebCloud-template-6.5-php56-L02B1",
            "hostname": <MASKED>,
            "name_match": "first",
            "folder": <MASKED>,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "validate_certs": false,
            "uuid": null
        }
    },
    "changed": false,
    "_ansible_no_log": false,
    "msg": "Unable to gather facts for non-existing VM V6-WebCloud-template-6.5-php56-L02B1"
}

##### ADDITIONAL INFORMATION

If i update the playbook and pass corresponding uuid to vmware_guest_facts, it succeed.
However, from the API, UUID is not required if name is supplied. 

I don't know if it is the problem of the bundled ansible or something else.

ref: http://docs.ansible.com/ansible/latest/vmware_guest_facts_module.html

**Comment by jakemcdermott** [comment]
@gripenk 
This seems like an issue with the ansible module and not awx itself. You'll probably want to create an issue on the ansible repo for this.
