### ISSUE TITLE
Caching not working as expecting

### ISSUE THREAD

**Issue by ravindra-bhadti-cko** [ansible/awx#11553]
https://github.com/ansible/awx/blob/7fdf491c059552eac65b33ca2d106540c3e5f8a6/awx/main/tasks.py#L2407

It appears here in the post-hook that despite turning on caching the collections are downloaded for each project sync and then moved to a build specific folder (specific by instance.cache_id). After running this on a Kubernetes cluster with EFS, this is not a good solution. As each project sync takes around 5mins.

A better caching approach would be to download a new set of collections, if and only if they are updated or the cache timeout has expired.

**Comment by shanemcd** [comment]
@AlanCoding When you have a moment, would appreciate your thoughts here.

**Comment by AlanCoding** [comment]
This is not related to the cache timeout (we have no sort of timeout setting for this sort of cache). The cache_id in question here is the id of the last project update for the project in question, not a project sync. So if you re-run a job, it should not re-download Ansible content, but if you re-update a project or set `update_on_launch`, it is intended to re-download Ansible content. The cache is not trying to be any smarter than that at the moment. Before we go any further, I want to ask if this matches with the behavior you're seeing.

**Comment by shanemcd** [comment]
@ravindra-bhadti-cko Still waiting to hear back from you. We'll wait another week or so before we close this.

**Comment by nixocio** [comment]
We have not heard back from you in a while, if you still seen this issue, please, send a message to mail list.
