### ISSUE TITLE
Error pulling image postgres:9.6

### ISSUE THREAD

**Issue by RealLittleSherman** [ansible/awx#1156]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

Error when trying to install AWX

##### ENVIRONMENT
* AWX version: Latest (GIT Clone)
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: CentOS 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

git clone https://github.com/ansible/awx.git
cd awx/installer
ansible-playbook -i inventory install.yml

##### ACTUAL RESULTS

TASK [local_docker : Activate postgres container] ***********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error pulling image postgres:9.6 - 'module' object has no attribute 'get_config_header'"}

**Comment by RealLittleSherman** [comment]
Solved! The problem is executing this command "yum -y install git gettext ansible docker nodejs npm gcc-c++ bzip2 python-docker-py python-pip" without a "reboot" previous to disabling the SELinux

You can close the Issue

**Comment by arjunnambiartc** [comment]
@RealLittleSherman ..I encountered the same error..how did you fix it..
