### ISSUE TITLE
AWX believes facts are modified even when gather_facts=false

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#11560]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Jobs are no longer accurately determining if the fact cache should be updated. It is updated every time.

### AWX version

19.5.0

### Installation method

docker on linux

### Modifications

no

### Ansible version

devel

### Steps to reproduce

Run this playbook with extra vars

```yaml
set_fact_cacheable: true
```

https://github.com/ansible/test-playbooks/blob/master/gather_facts.yml

then run:

https://github.com/ansible/test-playbooks/blob/master/ping.yml

Inspect the hosts that this playbook targeted, and then look at the field `ansible_facts_modified`

### Expected results

The datetime value of `ansible_facts_modified` does not change with the second playbook run, because it does not affect facts

### Actual results

Every time every playbook is ran against any host `ansible_facts_modified` is updated to that job's time.

### Additional information

This isn't a very big problem for the case of jobs that don't gather facts.

It's a bigger problem for users who have large inventories and target 1 or a few hosts with the `limit` field, and have the fact cache enabled.

In these cases, we would spend a large amount of time updating facts for all hosts in the inventory, because there are a lot of hosts, and for each host, there are a lot of facts.

**Comment by AlanCoding** [comment]
The proposed solution is that we fix: https://github.com/ansible/ansible-runner/issues/964, which @jbradberry went over in general terms.

In addition to this, I believe we should create some dummy files to help us keep track of time stamps. At both the start and finish of `start_job_fact_cache` we should touch a file in the artifacts directory. By doing this, we can compare the host facts files modification time to the reference files. This will tell us whether that file was created from the cached DB facts or not.

@amolgautam25 I got really excited about this because it could greatly help to improve code structure of `tasks/jobs.py`. We pass this data structure `fact_modification_times` around at the highest level. If we did the reference files approach, we would no longer need this at all. Plus... it's not working to begin with.

**Comment by AlanCoding** [comment]
The ansible-runner PR is merged, unblocking this.

I feel very opinionated about the solution, and this is influenced by some discoveries I made doing the ansible-runner patch. The timestamps are only accurate to within 2 seconds. Yes, it has 2 seconds rounding, due to some standard from decades ago. For short jobs, we can't count on time deltas registering. Because of that, my proposed solution is to:

 - Inside of `Job.start_job_fact_cache`, _backdate_ the modification time of all files laid down to the same time (in the past). I have an example in the ansible-runner tests. How far you backdate by is subject to modification. 1 or 2 days would sound ideal because it would address any potential timezone issues while still not appearing weird. You might argue that job's `ansible_facts_modified` timestamp would be more expressive. Anything will probably work.
 - Create a reference file in the artifacts folder (but not the fact_cache folder) that has the same modification time applied
 - In `Job.finish_job_fact_cache`, read the modification time of the reference file, and compare other files to that time to determine if they have been updated.
 - Remove `modification_times`

**Comment by jbradberry** [comment]
@AlanCoding I don't know about this, any solution starting with the word 'backdate' seems iffy to me.

**Comment by AlanCoding** [comment]
@jbradberry facts are written when the gather facts task completes. It is probable that this sometimes occurs less than 2 seconds after the fact_cache is pre-populated by the control machine (particularly for hybrid nodes).

This explained the weird 2 second thing to me:

https://stackoverflow.com/questions/64048499/zipfile-lib-weird-behaviour-with-seconds-in-modified-time

Importantly, we don't have to do anything sensitive here. We _only_ wish to detect if a file (corresponding to a host name) was touched, and if so, we load that data and save it. If you have any alternative implementations, I'm interested to hear them. Right now, I don't see any reason this _won't_ work, and we have integration tests ready to verify it.

**Comment by AlanCoding** [comment]
I have not had time to return to this to work on the revised proposal in https://github.com/ansible/ansible-runner/issues/983, so someone else could pick it up.

**Comment by jay-steurer** [comment]
This issue has been reported on Jira as well:
https://issues.redhat.com/browse/AAP-4585

**Comment by AlanCoding** [comment]
I can no longer reproduce this issue. I have some related tests, I suggest that those be merged and this issue be closed.

**Comment by jay-steurer** [comment]
Testing PR has been merged. Closing this now.
