### ISSUE TITLE
make clean html reports an error about [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by huanghaiqing1** [ansible/awx#11563]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Hello, here I'm Building the CLI Documentation and when customize TOWER_HOST/TOWER_USERNAME/TOWER_PASSWORD related parameters, it reports below warnings:

 TOWER_HOST=https://awx.test.org TOWER_USERNAME=admin TOWER_PASSWORD=xxxxxxxx make clean html
Running Sphinx v4.4.0

Exception occurred:
  File "/Python3.8/lib64/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='awx.test.org', port=443): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f33654d0310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
The full traceback has been saved in /tmp/sphinx-err-mqkgtiab.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:20: html] Error 2

### AWX version

19.5.0

### Installation method

docker on linux

### Modifications

no

### Ansible version

ansible-2.9.27

### Operating system

CentOS 8.5 Stream

### Web browser

Firefox

### Steps to reproduce

Follow the KB: https://github.com/ansible/awx/blob/devel/INSTALL.md. Installing AWX has no error. When switch to "Installing the AWX CLI", just report below error everytime:

(Python3.8) [root@awx docs]# TOWER_HOST=https://awx.test.org TOWER_USERNAME=admin TOWER_PASSWORD=xxxxxxxx make clean html
Running Sphinx v4.4.0

Exception occurred:
  File "/Python3.8/lib64/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='awx.test.org', port=443): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f33654d0310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
The full traceback has been saved in /tmp/sphinx-err-mqkgtiab.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:20: html] Error 2
(Python3.8) [root@awx docs]# telnet localhost 8000
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
Trying ::1...

### Expected results

I hope I can go on next steps and enter web console mode for AWX after Installing the AWX CLI.

### Actual results

Everytime broke here with same error. Looks local contrains don't initiate a web console. When use telnet localhost 443 or so called 8000, both reports connection refused.

**Comment by shanemcd** [comment]
`Name or service not known`. Seems like your AWX server is not up / responding.
