### ISSUE TITLE
Missing metrics that capture latency of jobs

### ISSUE THREAD

**Issue by bjoydeep** [ansible/awx#11564]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
In order to be monitoring AAP as an application running on *KS, we need to capture the Golden Signals as per SRE best practices. (https://sre.google/sre-book/monitoring-distributed-systems/)
Out of the metrics that Golden Signals recommend, we have Traffic (awx_status_total), Error (awx_status_total again), Saturation (awx_instance_remaining_capacity{cluster="$cluster"}/awx_instance_capacity{cluster="$cluster"});
However, we have NO metrics that measure latency of Jobs. This of course can be seen in Ansible UI. If we can get this metric to be added, then we will have a good start.

**Comment by fosterseth** [comment]
@bjoydeep thanks for opening this feature idea. By latency do you mean job `started` - job `created`?

**Comment by bjoydeep** [comment]
@fosterseth I think this is for you guys to decide what is important, the goal being that this should give an hint to the SRE if everything is ok.
In spirit, in that google doc, it is how many requests come in, how many error out and how quickly do requests respond. In Ansible case, probably it is started-created like you said. Because the job itself depends on what is in it - and it could take several minutes/hours depending on what is in it.
However, what happens if the customer created a very long running job that hijacked all resources? How to detect that?

**Comment by kdelee** [comment]
@bjoydeep some metrics that that are already available on /api/v2/metrics  (that @fosterseth worked on addeding afaik) are metrics regarding the redis queue on each control plane pod and the callback receiver stats.

The redis queue is where events from jobs are stored in memory until they get processed by the callback receiver and written to the database. A redis queue that grows faster than the callback receiver can catch up can cause a pod to OOM. It is tolerable for the redis queue to temporarily grow faster than the callback receiver can process events, but if this continues for too long it can crash the whole pod. So a simple gauge of the `callback_receiver_events_in_memory` or `callback_receiver_events_queue_size_redis` could be useful if you can determine a danger level or calculate a rate over time and determine "too much events" (e.g. job output is overwhelming the cluster)

More advanced, you could track the event processing rate by using `callback_receiver_events_insert_db_seconds` with `callback_receiver_events_insert_db` -- @fosterseth may have an example of that closer on hand 
```
# HELP callback_receiver_events_queue_size_redis Current number of events in redis queue
# TYPE callback_receiver_events_queue_size_redis gauge
callback_receiver_events_queue_size_redis{node="tower-1643046191-5576855fc7-8sjzc"} 0
callback_receiver_events_queue_size_redis{node="tower-1643046191-5576855fc7-gwplg"} 0
callback_receiver_events_queue_size_redis{node="tower-1643046191-5576855fc7-zq45d"} 0
# HELP callback_receiver_events_popped_redis Number of events popped from redis
# TYPE callback_receiver_events_popped_redis gauge
callback_receiver_events_popped_redis{node="tower-1643046191-5576855fc7-8sjzc"} 201799
callback_receiver_events_popped_redis{node="tower-1643046191-5576855fc7-gwplg"} 2867831
callback_receiver_events_popped_redis{node="tower-1643046191-5576855fc7-zq45d"} 2391120
# HELP callback_receiver_events_in_memory Current number of events in memory (in transfer from redis to db)
# TYPE callback_receiver_events_in_memory gauge
callback_receiver_events_in_memory{node="tower-1643046191-5576855fc7-8sjzc"} 0
callback_receiver_events_in_memory{node="tower-1643046191-5576855fc7-gwplg"} 0
callback_receiver_events_in_memory{node="tower-1643046191-5576855fc7-zq45d"} 0
# HELP callback_receiver_batch_events_errors Number of times batch insertion failed
# TYPE callback_receiver_batch_events_errors gauge
callback_receiver_batch_events_errors{node="tower-1643046191-5576855fc7-8sjzc"} 0
callback_receiver_batch_events_errors{node="tower-1643046191-5576855fc7-gwplg"} 0
callback_receiver_batch_events_errors{node="tower-1643046191-5576855fc7-zq45d"} 0
# HELP callback_receiver_events_insert_db_seconds Time spent saving events to database
# TYPE callback_receiver_events_insert_db_seconds gauge
callback_receiver_events_insert_db_seconds{node="tower-1643046191-5576855fc7-8sjzc"} 502.0334282501135
callback_receiver_events_insert_db_seconds{node="tower-1643046191-5576855fc7-gwplg"} 20721.5046655091
callback_receiver_events_insert_db_seconds{node="tower-1643046191-5576855fc7-zq45d"} 15315.757276192307
# HELP callback_receiver_events_insert_db Number of events batch inserted into database
# TYPE callback_receiver_events_insert_db gauge
callback_receiver_events_insert_db{node="tower-1643046191-5576855fc7-8sjzc"} 201749
callback_receiver_events_insert_db{node="tower-1643046191-5576855fc7-gwplg"} 2866400
callback_receiver_events_insert_db{node="tower-1643046191-5576855fc7-zq45d"} 2390527
# HELP callback_receiver_batch_events_insert_db Number of events batch inserted into database
# TYPE callback_receiver_batch_events_insert_db histogram
callback_receiver_batch_events_insert_db_bucket{le="10",node="tower-1643046191-5576855fc7-8sjzc"} 11
callback_receiver_batch_events_insert_db_bucket{le="50",node="tower-1643046191-5576855fc7-8sjzc"} 77
callback_receiver_batch_events_insert_db_bucket{le="150",node="tower-1643046191-5576855fc7-8sjzc"} 335
callback_receiver_batch_events_insert_db_bucket{le="350",node="tower-1643046191-5576855fc7-8sjzc"} 1124
callback_receiver_batch_events_insert_db_bucket{le="650",node="tower-1643046191-5576855fc7-8sjzc"} 1124
callback_receiver_batch_events_insert_db_bucket{le="2000",node="tower-1643046191-5576855fc7-8sjzc"} 1124
callback_receiver_batch_events_insert_db_bucket{le="+Inf",node="tower-1643046191-5576855fc7-8sjzc"} 1124
callback_receiver_batch_events_insert_db_count{node="tower-1643046191-5576855fc7-8sjzc"} 1124
callback_receiver_batch_events_insert_db_sum{node="tower-1643046191-5576855fc7-8sjzc"} 201749
callback_receiver_batch_events_insert_db_bucket{le="10",node="tower-1643046191-5576855fc7-gwplg"} 1905
callback_receiver_batch_events_insert_db_bucket{le="50",node="tower-1643046191-5576855fc7-gwplg"} 5861
callback_receiver_batch_events_insert_db_bucket{le="150",node="tower-1643046191-5576855fc7-gwplg"} 16622
callback_receiver_batch_events_insert_db_bucket{le="350",node="tower-1643046191-5576855fc7-gwplg"} 23841
callback_receiver_batch_events_insert_db_bucket{le="650",node="tower-1643046191-5576855fc7-gwplg"} 23876
callback_receiver_batch_events_insert_db_bucket{le="2000",node="tower-1643046191-5576855fc7-gwplg"} 23876
callback_receiver_batch_events_insert_db_bucket{le="+Inf",node="tower-1643046191-5576855fc7-gwplg"} 23876
callback_receiver_batch_events_insert_db_count{node="tower-1643046191-5576855fc7-gwplg"} 23876
callback_receiver_batch_events_insert_db_sum{node="tower-1643046191-5576855fc7-gwplg"} 2866400
callback_receiver_batch_events_insert_db_bucket{le="10",node="tower-1643046191-5576855fc7-zq45d"} 520
callback_receiver_batch_events_insert_db_bucket{le="50",node="tower-1643046191-5576855fc7-zq45d"} 4965
callback_receiver_batch_events_insert_db_bucket{le="150",node="tower-1643046191-5576855fc7-zq45d"} 26662
callback_receiver_batch_events_insert_db_bucket{le="350",node="tower-1643046191-5576855fc7-zq45d"} 28561
callback_receiver_batch_events_insert_db_bucket{le="650",node="tower-1643046191-5576855fc7-zq45d"} 28561
callback_receiver_batch_events_insert_db_bucket{le="2000",node="tower-1643046191-5576855fc7-zq45d"} 28561
callback_receiver_batch_events_insert_db_bucket{le="+Inf",node="tower-1643046191-5576855fc7-zq45d"} 28561
callback_receiver_batch_events_insert_db_count{node="tower-1643046191-5576855fc7-zq45d"} 28561
callback_receiver_batch_events_insert_db_sum{node="tower-1643046191-5576855fc7-zq45d"} 2390527
# HELP subsystem_metrics_pipe_execute_seconds Time spent saving metrics to redis
# TYPE subsystem_metrics_pipe_execute_seconds gauge
subsystem_metrics_pipe_execute_seconds{node="tower-1643046191-5576855fc7-8sjzc"} 0.5127046119887382
subsystem_metrics_pipe_execute_seconds{node="tower-1643046191-5576855fc7-gwplg"} 17.465061452239752
subsystem_metrics_pipe_execute_seconds{node="tower-1643046191-5576855fc7-zq45d"} 14.625594843644649
# HELP subsystem_metrics_pipe_execute_calls Number of calls to pipe_execute
# TYPE subsystem_metrics_pipe_execute_calls gauge
subsystem_metrics_pipe_execute_calls{node="tower-1643046191-5576855fc7-8sjzc"} 295
subsystem_metrics_pipe_execute_calls{node="tower-1643046191-5576855fc7-gwplg"} 8816
subsystem_metrics_pipe_execute_calls{node="tower-1643046191-5576855fc7-zq45d"} 7321
# HELP subsystem_metrics_send_metrics_seconds Time spent sending metrics to other nodes
# TYPE subsystem_metrics_send_metrics_seconds gauge
subsystem_metrics_send_metrics_seconds{node="tower-1643046191-5576855fc7-8sjzc"} 2.6668942770920694
subsystem_metrics_send_metrics_seconds{node="tower-1643046191-5576855fc7-gwplg"} 84.55525641608983
subsystem_metrics_send_metrics_seconds{node="tower-1643046191-5576855fc7-zq45d"} 79.26047018589452
```

Another metric we sometimes measure in testing is the "event lag" between when the event is "created" (occurs in ansible) and when it is written to the database ("modified" time on the job) -- but this is not available from this view and searching for that on the api/v2/jobs endpoint could be disruptive if you were hammering the API too much. Maybe there would be some way to roll up an average for a certain time period here to the metrics page, but it seems like there is already a few metrics for you to go by

Just so you know -- as it currenlty stands on k8s deployments no capacity is consumed :upside_down_face:. this causes problems with awx then launching more jobs than it can handle. Check out https://github.com/ansible/awx/issues/10694 for some discussion on that

**Comment by shanemcd** [comment]
@bjoydeep When you have a chance, can you look at the information @kdelee has provided? Does that help you?

**Comment by bjoydeep** [comment]
Yes - it does. Sorry, missed this one @shanemcd @fosterseth @kdelee . Additionally @gamuniz has convinced me that time taken by job - to spin up or completion does not make much sense.

**Comment by shanemcd** [comment]
Ok, I'm going to close this then. Thank you for the update and let us know if you need anything in the future.

**Comment by aditki** [comment]
@bjoydeep 


> Additionally @gamuniz has convinced me that time taken by job - to spin up or completion does not make much sense.

Can you share the rationale behind that?
