### ISSUE TITLE
Jobs stuck in waiting state (can block other jobs forever)

### ISSUE THREAD

**Issue by moreiramarti** [ansible/awx#11572]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When a awx-pod (the one with web, task and redis containers) restarts, some jobs are stuck in waiting state.

##### ENVIRONMENT
* AWX version: 19.4.0
* Operator version: 0.14.0
* Kubernetes version: v1.19
* AWX install method: kubernetes

##### STEPS TO REPRODUCE

When a pod restart, the automation pods linked to it are stuck in waiting state and it's blocking for other jobs.

##### EXPECTED RESULTS

Orphan jobs should be killed

##### ACTUAL RESULTS

Jobs are stucked in waiting mode

##### ADDITIONAL INFORMATION

Linked to this issue https://github.com/ansible/awx/issues/11301

**Comment by kdelee** [comment]
Closing this as a duplicate of https://github.com/ansible/awx/issues/11301
-- the bug is in awx, not the operator
