### ISSUE TITLE
Project Sync Error Due to Missing Resource

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#11584]
I built a new ec2 instance against AWX devel. the initial project sync ended in Error status due to missing resource:
![image](https://user-images.githubusercontent.com/63685497/150571400-c23bef8b-357d-4cbf-851d-56f1ffc555c4.png)
![image](https://user-images.githubusercontent.com/63685497/150571421-8181d0d4-73a1-42f7-82b7-323868cc7891.png)

Subsequent project sync attempts were successful.

Linked issue:
https://github.com/ansible/awx/issues/11583

**Comment by nixocio** [comment]
I also started an ec2 instance using awx/devel and got the same error. This is not an UI issue. Same behavior as above.

![image](https://user-images.githubusercontent.com/9053044/150804396-7b62624a-4998-4259-bed0-7a11d406e4ab.png)

EE presents on the system

![image](https://user-images.githubusercontent.com/9053044/150805556-35d7406c-cff2-4e42-8c17-297d069403ba.png)

**Comment by tchellomello** [comment]
@shanemcd wasn't this error that we were getting during the `awx-operator` testing our the last PR?

**Comment by tchellomello** [comment]
@akus062381 @nixocio this issue should be fixed in devel now. Please let know if that still occurs for you guys.
