### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'contains')

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#11582]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Trying to visit instance details the error is being displayed in prod version:

```
Uncaught TypeError: Cannot read properties of null (reading 'contains')
    at HTMLDocument.e (AddDropDownButton.js:15:58)
```

Dev server:

![image](https://user-images.githubusercontent.com/12464858/150571248-8bf73191-e9c2-4688-9090-4196c9180160.png)

### AWX version

devel

### Installation method

docker on linux

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

1. Navigate to instance list
2. Click on a instance from the list

### Expected results

The error to not be thrown 

### Actual results

Page crashing on dev server and printing the error on the console for prod versions

### Additional information

Tests trying to visit instance details are failing due to https://docs.cypress.io/api/events/catalog-of-events#App-Events

**Comment by nixocio** [comment]
On a fresh installation visiting the
```https://localhost:3001/#/inventories/inventory/1/details```
sporadically also raises this error.

![image](https://user-images.githubusercontent.com/9053044/152178827-8a5aafc1-3f97-4b00-b116-cdf5c7b10c45.png)

**Comment by nixocio** [comment]
I got this error today several time when reviewing a PR, I will work on it.

**Comment by tiagodread** [comment]
This is now fixed, the E2E test failing because of this issue is now passing.
