### ISSUE TITLE
Add top-level Instances List Page

### ISSUE THREAD

**Issue by kialam** [ansible/awx#11588]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Similar to how we interpret Hosts and Inventories, we have top level list pages for both views as well as tabbed list views to represent their relationship. We would like to apply this to the Instances Groups and Instances page.

☐ Create top-level instances list page (between Instance Groups and Applications)
  ☐ Add search bar, health check buttons
  ☐ Promote "Node Type" detail to top level column view
  ☐ Remove "Running Jobs", "Total Jobs" from top level column view and put in expand/collapse detail area
  ☐ Include "hop" nodes/instances in Instances list page
  ☐ "Hop" nodes cannot be enabled or disabled via the toggle
  ☐ "Hop" nodes cannot be selected via the checkbox to be disassociated/health check
  ☐ User can see instance details page by clicking on an instance from the Instances List page
  ☐ Mesh viz will redirect users to Instances > Instance details page
  ☐ Only admins and auditors can see Instances list page

  Future scope
  ☐ add "associate" button to top level Instances page

**Comment by AlexSCorey** [comment]
related https://github.com/ansible/awx/issues/11425
