### ISSUE TITLE
the python NetApp-Lib module is required when using netapp collections ontap

### ISSUE THREAD

**Issue by eselvam** [ansible/awx#11585]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

when executing the playbook in awx 19.x, we get the python NetApp-Lib module is required.  The collections are downloaded successfully after project sync. Kindly help us here

### AWX version

19.5.0

### Installation method

kubernetes

### Modifications

no

### Ansible version

not sure how to check it in awx 19.5.0

### Operating system

rhel but it is running in k8

### Web browser

Chrome

### Steps to reproduce

create a playbook using ontap collections: 
crate template in awx
run it you will get the error: the python NetApp-Lib module is required
-
  name: Get Vserver
  hosts: localhost
  gather_facts: no
  tasks:

    -
      name: "Get Vserver List"
      netapp.ontap.na_ontap_command:
        hostname: "hostname01"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
        command: ['version']
        return_dict: true

### Expected results

we should not get the error.

### Actual results

The playbook should have run with success.

**Comment by ffirg** [comment]
Closing as posted to the mailing list as this is a bug
