### ISSUE TITLE
Filter out hop nodes from associate modal

### ISSUE THREAD

**Issue by kialam** [ansible/awx#11607]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

related #11591
Hop nodes now show up in the associate modal within instance groups -> associate button. We should filter them out since they cannot be associated to any instance group.

**Comment by AlanCoding** [comment]
"control" nodes also can't be associated with instance groups (they may already be filtered), so both types should be filtered out after this.

**Comment by kialam** [comment]
@AlanCoding that was already been [done](https://github.com/ansible/awx/commit/cde0df937f703d85ae5e92540f92f36bf6f5a189) as part of the last release.

**Comment by kialam** [comment]
cc @tiagodread @akus062381 ^ this is ready for QE

**Comment by shanemcd** [comment]
Moving to Needs Test...

**Comment by tiagodread** [comment]
Verified
