### ISSUE TITLE
Can't make a path available in job isolation

### ISSUE THREAD

**Issue by Sergiodcm00** [ansible/awx#11604]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

I have created a volume through the extra_volumes directive (awx-operator) and mounted it with ee_extra_volume_mounts, tasks_extra_volume_mounts, and web_extra_volume_mounts. I have confirmed the mount is available in all of these containers.
Playbook executed on local not find files in mounts.

### AWX version

19.5.1

### Installation method

minikube and awx-operator

### Modifications

no

### Ansible version

2.11.8 (EE)

### Operating system

CentOS Stream 8 (EE)

### Steps to reproduce

Install AWX
Configure an extra volume and check visibility inside containers ee/web/tasks.
Set awx isolation show path in gui ([ "/gevIT/SW:/gevIT/SW"] first, ["/gevIT/SW:/tmp/SW"] second test).
Delete POD to recreate anytime changed awx isolation show path.
Run a playbook on local to check directory:

```
   - name: Play
      hosts: all
      gather_facts: no
      tasks:
      - name: "comando {{ command_to_execute }}"
        register: salida
        local_action: shell {{ command_to_execute }}
    
      - name: salida comando
        debug:
          msg: "{{ salida.stdout_lines }}"
```

with command_to_execute equal to "ls -/gevIT/SW" or "/tmp/SW".

### Expected results

Playbook output show files inside directory /gevIT/SW" or /tmp/SW

### Actual results

Playboot exit with error (not directory exists)

**Comment by Sergiodcm00** [comment]
Investigating I found a solution to expose paths here:
[https://stackoverflow.com/questions/67747550/how-can-i-expose-local-data-path-to-the-temporary-job-container-awx-job-xxxxx](url)
Now I use functionality "Instance Groups" instead of the setting "Paths to expose to isolated jobs" to achieve my goal. It works perfect.

Perhaps it should be reviewed what exactly "Paths to expose to isolated jobs" setting does. Maybe it's related to this:
[https://github.com/ansible/ansible-runner/issues/757](url)
```
It would be helpful if the following two points were documented.
    The process_isolation_* options are only for bwrap and not for docker or podman.
    docker and podman should be able to use container_volume_mounts.
```

and it's a **documentation problem ¿?**.

**Comment by shanemcd** [comment]
Sorry for the confusion here. `ee_extra_volume_mounts` is for the EE inside the control plane, not the EEs launched by container groups. I've created a new issue here to rename that variable: https://github.com/ansible/awx-operator/issues/792
