### ISSUE TITLE
Smart Host Filter UX is potentially confusing

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#11610]
When a user clicks Add Smart Inventory from the Inventories List, and they see the following:
![image](https://user-images.githubusercontent.com/63685497/151057002-f9cd009d-9fa6-438f-afd1-25bcb9abc3e3.png)

This user experience is not easy to follow, due to these reasons:

1) The user is not informed that they need to select an organization in order to define a smart host filter

2) Having an input box next to the spyglass is confusing. Every other input box in the UI (that I can think of) allows the user to either search for a resource or type something by hand. Perhaps adding Placeholder text inside the input explaining that the user must first search for a smart host filter would be helpful.
![image](https://user-images.githubusercontent.com/63685497/151058053-44978a94-4331-4a7d-9f2a-2dd68798076c.png)

3) When the user gets to the Search Smart Host modal, it is not clear that they can search for a filter if none is showing up. My default behavior would be- if I see a list with no options, I would assume none were available and close the modal, feeling confused about what to do. I would not think to search for a name, see no results, and then click Select because I wouldn't think that doing so would create a new filter. This should be more clearly explained.
![image](https://user-images.githubusercontent.com/63685497/151058001-059bcb24-ad6d-485f-b885-0a1d62f350a7.png)

4) When the smart host filter is populated in the input field, there is no way to clear out the selection. The user is able to redefine the filter name by clicking the spyglass again, typing a new name, see no results, click select anyway, and then they will see the  new filter defined in the input field. BUT this functionality is not obvious and I believe could create confusion for many users.

**Comment by AlexSCorey** [comment]
@trahman73 can you chime in here?  I agree that this UX could be improved and if we need to add help text to do that I'm all for it, but I also thing some reconfiguring/redesigning might help too.

**Comment by trahman73** [comment]
Adding @tiyiprh to the convo...

1) We can potentially disable the smart host filter area until an org is selected. We can include a tooltip or add to the (?) popover explaining that an org must be first selected.

2) The input field for the Smart host filter can be disabled with placeholder text asking the user to click the lookup icon to initiate the filter.

![image](https://user-images.githubusercontent.com/13351591/151218554-612b15ce-7d88-4405-b010-59ca45f88eab.png)

3) The default state that was mocked out a populated list of hosts that can be filtered vs an empty state.

![image](https://user-images.githubusercontent.com/13351591/151220159-f8d7bbba-c3d9-488d-891b-7d0b836db5b6.png)

4) In the mockups, the filter is populated as a tag so it can be removed by clicking the "X" on the tag itself or replaced by initiating another filter.

![image](https://user-images.githubusercontent.com/13351591/151218876-8390aa82-da69-4e1e-bb4f-f9f3bb02805b.png)

If we can't return a tag in the input, we can add a remove action button as below...

![image](https://user-images.githubusercontent.com/13351591/151219631-94de8265-135f-44c4-bcdb-018062718766.png)

We can iterate on the suggestions above. Thanks all!

**Comment by ffirg** [comment]
closing in favour of #7850
