### ISSUE TITLE
Adding Credential to JT- Categories/Types aren't matching up

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#11615]
In the list of credential types, when you create a credential, you see:
https://user-images.githubusercontent.com/63685497/151233608-02d1f407-443c-44a3-aa3e-568d9c6f3599.mp4

In the Job Template form, when you click the Credential spyglass, the category types only show:
![image](https://user-images.githubusercontent.com/63685497/151234235-cc240468-1008-4d8f-96ff-4a4e96f327b7.png)

Why does the user not have all of the same options in both places?

**Comment by AlexSCorey** [comment]
There are only certain types of credentials that can be assigned to a JT.  Here are the docs, though I'm not sure these are 100% accurate because I don't know that we support Rackspace credentials any more.

**Comment by marshmalien** [comment]
This [line](https://github.com/ansible/awx/blob/devel/awx/ui/src/api/models/CredentialTypes.js#L10) is where we define the "acceptable kinds" of credential types: 

> acceptableKinds = ['machine', 'cloud', 'net', 'ssh', 'vault', 'kubernetes']

**Comment by infra-monkey** [comment]
I encountered this issue with "HashiCorp Vault Secret Lookup".
If I remember correctly, before (<17.0.0) it was possible to create the credential type and then add it to the job template. Now that this credential type is native, I would expect it to be allowed in job templates.

Is there something that changed that prevents allowing this type?

**Comment by AlexSCorey** [comment]
@ffirg @shanemcd do we want to modify which credentials can be added to a job template?

**Comment by AlexSCorey** [comment]
A user can add a credential with a custom credential type to a job template.  We'd need @shanemcd and @ffirg to chime in on whether we want to allow users to add credentials of additional credential types to a job template.

**Comment by shanemcd** [comment]
I think we'd need to go through each one and ask if they make sense in the context of a JT, I'm assuming there are some that dont.

**Comment by mabashian** [comment]
As far as I can tell, this is behaving as we intended it to.  Marly's comment sums it up: we deliberately filter some credentials type `kinds` out of the list.  This was likely done because we viewed some `kinds` as nonsensical within the context of a JT.  It's unclear to me what the action here is.  We should probably be aligning with whatever the API allows.  If there are restrictions on the kinds of credentials a user can add to the JT through the API then we should make the UI match.  If we do want to limit credential type kinds, we should identify which ones are white-listed and enforce that in both the UI and API.

**Comment by akus062381** [comment]
@mabashian if we do, in fact, do this on purpose, may I suggest that we should somehow make that clear to the user? From a user standpoint, they may not understand why a certain type of credential is not allowed to be added here.

**Comment by AlexSCorey** [comment]
We could add a help text either on the credential field or inside the credential modal, preferred because IMO it makes more sense contextually, that says something like `Some credential types are omitted because they do not apply to job templates or workflow job templates` .  What do we all think?

**Comment by hesmithrh** [comment]
this will be addressed in Docs, review and update to include reference to : acceptableKinds = ['machine', 'cloud', 'net', 'ssh', 'vault', 'kubernetes']

**Comment by tvo318** [comment]
@AlexSCorey this tooltip is ok except there is no **Credentials** field in the create WF template form. I've updated the JT docs to include the note and removed all references of Rackspace since it was removed since 3.2 😵
See PR https://github.com/ansible/product-docs/pull/1698.
