### ISSUE TITLE
TypeError when running a command on a host in a smart inventory

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#11611]
When a user accesses the hosts tab of a smart inventory, selects the host, and clicks Run Command, a type error occurs:

![image](https://user-images.githubusercontent.com/63685497/151060638-1badb545-ad13-456d-93b2-f888abde28ba.png)

![image](https://user-images.githubusercontent.com/63685497/151060666-9825f1f3-979c-468f-93c0-3133bd1dc978.png)

To be considered- does it make sense to have the Run Command button on this screen?

**Comment by AlexSCorey** [comment]
We want people to be able to run ad hoc commands on individual hosts, or group of hosts (inventories) so I do think it makes sense to have that functionality here.

**Comment by AlexSCorey** [comment]
@akus062381 can you provide details about the configuration of the job you ran to get this error?

**Comment by akus062381** [comment]
@AlexSCorey  sure!

Steps to follow:

1. Access Inventories list. Click Add Smart Inventory and fill in the required fields. When you get to the Smart Host Filter field, type localhost in the search box and click the spyglass. Then click select.
2. Save the inventory you just created
3. Click the host tab of the inventory
4. select localhost and click Run Command
5. See the error

**Comment by TyraelTLK** [comment]
I have the same issue for every host in a smart inventory:

TypeError: Cannot read properties of undefined (reading 'map') at dv (https://HIDDEN/static/js/main.7b1f208d.chunk.js:1:581426) at Zo (https://HIDDEN/static/js/2.97a1dff5.chunk.js:2:1419511) at Ss (https://HIDDEN/static/js/2.97a1dff5.chunk.js:2:1465741) at vl (https://HIDDEN/static/js/2.97a1dff5.chunk.js:2:1458468) at ml (https://HIDDEN/static/js/2.97a1dff5.chunk.js:2:1458393) at sl (https://HIDDEN/static/js/2.97a1dff5.chunk.js:2:1455402) at https://HIDDEN/static/js/2.97a1dff5.chunk.js:2:1406773 at t.unstable_runWithPriority (https://HIDDEN/static/js/2.97a1dff5.chunk.js:2:1482174) at qi (https://HIDDEN/static/js/2.97a1dff5.chunk.js:2:1406482) at Yi (https://HIDDEN/static/js/2.97a1dff5.chunk.js:2:1406718)

**Comment by InnocentK** [comment]
Resolved
