### ISSUE TITLE
Hop nodes instances can be modified

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#11622]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

After merging https://github.com/ansible/awx/pull/11591 the hop nodes are now exposed in `/api/v2/instances/`.

Example:

```
 {
      "id": 4,
      "type": "instance",
      "url": "/api/v2/instances/4/",
      "related": {
          "jobs": "/api/v2/instances/4/jobs/",
          "instance_groups": "/api/v2/instances/4/instance_groups/"
      },
      "uuid": "00000000-0000-0000-0000-000000000000",
      "hostname": "receptor-hop",
      "created": "2022-01-26T19:15:07.439405Z",
      "modified": "2022-01-26T19:27:58.447951Z",
      "last_seen": "2022-01-27T13:36:46.163205Z",
      "last_health_check": null,
      "errors": "",
      "capacity_adjustment": "1.00",
      "version": "",
      "capacity": 0,
      "consumed_capacity": 0,
      "percent_capacity_remaining": 0.0,
      "jobs_running": 0,
      "jobs_total": 0,
      "cpu": 0,
      "memory": 0,
      "cpu_capacity": 0,
      "mem_capacity": 0,
      "enabled": false,
      "managed_by_policy": false,
      "node_type": "hop"
}
```

and now is possible to `PUT` or `PATCH` the values through API

```
{
    "capacity_adjustment": "1.00",
    "enabled": false,
    "managed_by_policy": false
}
```
although setting capacity to 0 enabld to false is not making the job to faul, @jbradberry do we want allow users to patch/put on hop node instances?

### AWX version

devel

### Installation method

docker on linux

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

1. Go to /api/v2/instances/<id>/
2. patch any value:
```
{
    "capacity_adjustment": 1.0,
    "enabled": true,
    "managed_by_policy": true
}
```

### Expected results

These fields to be not modifyable for hop nodes?

### Actual results

1. The user can change those values
2. This is not making the job to fail
3. The hop nodes instances are showing as `disabled` in the mesh view (may confuse users)

**Comment by jbradberry** [comment]
I should point out that editing values on control-only nodes also probably doesn't make sense for a number of fields.

**Comment by jbradberry** [comment]
@shanemcd @AlanCoding We've shoehorned control-only nodes and now hop nodes into this model, and are fully exposing these types that cannot run user jobs to the instance api endpoints.  Perhaps it's time to have a discussion about what it means for users to modify values on them and how we want these endpoints to actually work.

**Comment by AlanCoding** [comment]
I agree with the expectation here. Just give a 400 code and say in the message that editing capacity fields for hop nodes doesn't make any sense.

> I should point out that editing values on control-only nodes also probably doesn't make sense for a number of fields.

I don't agree with this. We are not counting control_node selection against instance capacity, but this is currently a very high priority item that we have allocated resources for, and there are no major technical implementation questions about it.

**Comment by tiagodread** [comment]
Added tests in 7300 to verify that Hop nodes can't be modified

**Comment by thenets** [comment]
I still have the issue on the API side. I should not be able to patch `hop` instances on the following fields:
- capacity_adjustment
- enabled
- managed_by_policy

**Comment by thenets** [comment]
I reran tests. Probably was something off when the pipelines triggered, before some codebase change.
All passed.
