### ISSUE TITLE
[Research] Job Output performance

### ISSUE THREAD

**Issue by keithjgrant** [ansible/awx#11629]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
The job output page feels sluggish and could use some performance attention. The virtual scrolling in job output feels sluggish when a job is running, and fetching events while the user scrolls also could probably also be improved.

**Comment by AlexSCorey** [comment]
We should definitely look for ways to improve this in the UI, but there might also be ways to improve this in the API so that requests are quicker.  I wonder if there is data in the response that we don't need in the UI?

**Comment by keithjgrant** [comment]
#11944 is a big step in the right direction for performance on this page. It will take a little research to determine next steps

**Comment by AlexSCorey** [comment]
@keithjgrant please itemize your ideas and create smaller issues where appropriate.

**Comment by AlexSCorey** [comment]
@keithjgrant please itemize your ideas and create smaller issues where appropriate.

**Comment by keithjgrant** [comment]
With #11944 and #12555, I think we've taken a huge chunk out of this. Closing this for now and if anything else specifically actionable surfaces we can open a relevant issue.

Only possible thing that comes to mind at the moment is perhaps pre-fetching an extra page or two of job events below where the user has scrolled, but we probably don't need to worry about that unless we hear from users in that regard
