### ISSUE TITLE
Team Org Admin role- can't be added- should be disabled

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#11626]
1. Signed in as admin.
2. Add a team.
3. Add self (user) to team as an admin.
4. Click on the Roles tab, click Add.
5. Select Organizations.
6. Select Admin and Save.
7. You will see an error. Other roles can be assigned here, but not admin.
Conclusion: The admin option should be disabled so that a user can't click on it here, because it won't work for any of the organizations available.

![image](https://user-images.githubusercontent.com/63685497/151425081-8788301d-3931-49de-87fa-a8195196ccc2.png)

![image](https://user-images.githubusercontent.com/63685497/151425105-8ba9753d-0c05-4143-86d4-22b24dfe4b22.png)

**Comment by AlexSCorey** [comment]
My hunch here is that the options on this screen are coming from an OPTIONS request to the API.

**Comment by marshmalien** [comment]
Organization participation roles can’t be assigned to a team. A `user_only` flag was added to `object_roles` in this [PR](https://github.com/ansible/awx/pull/6438) to help the UI hide these roles. It looks like we’re not checking this flag before displaying roles in the User and Team Access wizard. 

```
"object_roles": {
    "admin_role": {
        "description": "Can manage all aspects of the organization",
        "name": "Admin",
        "id": 2,
        "user_only": true
    },
    "execute_role": {
        "description": "May run any executable resources in the organization",
        "name": "Execute",
        "id": 3
    },
    "project_admin_role": {
        "description": "Can manage all projects of the organization",
        "name": "Project Admin",
        "id": 4
    },
    "member_role": {
      "description": "User is a member of the organization",
      "name": "Member",
      "id": 11,
      "user_only": true
    },
   ...
}
```

Note: We are handling this correctly in the Resource Role wizard. See [related issue](https://github.com/ansible/awx/issues/6433). 
Organization → Access tab → Add button → Select Teams → Select a team → * No `user_only` roles shown *

**Comment by akus062381** [comment]
this is fixed. just waiting for e2e tests before merging PR.
