### ISSUE TITLE
Job output sometimes misses last line of output

### ISSUE THREAD

**Issue by keithjgrant** [ansible/awx#11637]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
When a job finishes with the job output page pulled up, the page hits the API to refresh job output data. There is a race condition where this sometimes comes back with the last event missing and/or the final count of events off by one, resulting in the final event (the job summary) not displaying.

Expected result: all job events consistently display when the job finishes running, including the job summary

**Comment by shanemcd** [comment]
Closing in favor of https://github.com/ansible/awx/issues/11424
