### ISSUE TITLE
Can't input the name starts with "default" in "Create new container group" screen

### ISSUE THREAD

**Issue by kurokobo** [ansible/awx#11634]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

In the "Create new container group" screen, if I enter "default" in the "Name" field, the field will be immediately disabled and cannot be edited.

![Animation](https://user-images.githubusercontent.com/2920259/151577165-52794190-527f-44e0-bafb-a121696d3f23.gif)

This is a problem when entering a name that starts with "default", such as "default instance for hoge team".

This will only happen if the string in the field is an exact match for "default".

This can be avoided as a workaround by typing "instance for hoge team" first and then adding "default" to the beginning, or by pasting the full name from the clipboard.

### AWX version

19.5.0

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.11.8rc1.post0 on quay.io/ansible/awx-ee:latest

### Operating system

CentOS 8.2.2004

### Web browser

Firefox, Chrome

### Steps to reproduce

1. Open "Instance Groups" > "Add" page.
2. Type "default" by hand in the "Name" field.

### Expected results

The field remains editable.

### Actual results

The field immediately disabled and cannot be edited.

### Additional information

Not tested on Safari or Edge.

**Comment by mabashian** [comment]
https://github.com/ansible/awx/blob/devel/awx/ui/src/screens/InstanceGroup/shared/ContainerGroupForm.js#L49.  We probably only want to disable this field when the value is `default` and the field is clean (untouched).

@kurokobo easiest workaround until we can get this fixed is to type out the name of your container group somewhere else and then paste it in the field.

**Comment by InnocentK** [comment]
Resolved
