### ISSUE TITLE
Double-clicking the "Launch" button creates two Jobs.

### ISSUE THREAD

**Issue by kurokobo** [ansible/awx#11633]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

If the user accidentally double clicks the "Launch" button of a Job Template, two jobs may be started. This is not an expected behavior and is not a natural user experience.

Immediately after the user clicks the "Launch" button, the button is deactivated once, but appears to be re-activated again once the Job is created. During the short time between when the button is re-activated and when the user get to the "Output" page of the Job, the user can click the "Launch" button again.

In the following animation, Jobs 68 and 69 are started by clicking the Launch button twice in a short period of time.

![Animation](https://user-images.githubusercontent.com/2920259/151572320-e5a8f88c-e4cd-4b4e-a4ab-e23b3d6eadfd.gif)

Once the "Launch" button is clicked, the button should remain disabled until the user get to the output screen.

### AWX version

19.5.0

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.11.8rc1.post0 on quay.io/ansible/awx-ee:latest

### Operating system

CentOS 8.2.2004

### Web browser

Firefox, Chrome

### Steps to reproduce

1. Open the "Templates" page.
2. Click one of the following repeatedly at high speed.
   - Launch icon on the list of the Job Templates page
   - Launch button on the Details page of the Job Template.
   - Launch button on the Propmt if some "Prompt on launch" stuff is enabled for the Job Template

### Expected results

Only one Job will be created.

### Actual results

Two or more Jobs will be created at the same time.

### Additional information

Not tested on Safari or Edge.

**Comment by mabashian** [comment]
Interesting - I thought we addressed this last year (see: https://github.com/ansible/awx/issues/4249) but maybe it's crept back in.  Thanks for filing an issue!

**Comment by InnocentK** [comment]
Resolved in: https://github.com/ansible/awx/pull/11649
