### ISSUE TITLE
control pods in k8s think they have capacity of whole k8s node

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#11640]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Control pods are reporting as if each one has the capacity of the entire underlying k8s node it is on.

For example, I have one node in my minikube cluster:
```
kubectl get nodes -o json | jq '.items[].status.capacity'
{
  "cpu": "8",
  "ephemeral-storage": "71711864Ki",
  "hugepages-1Gi": "0",
  "hugepages-2Mi": "0",
  "memory": "32475736Ki",
  "pods": "110"
}
```

And in my awx deployment I have 3 control pods, each one reporting the entire CPU and memory of the underlying node:
```
{
    "count": 3,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 11,
            "type": "instance",
            "url": "/api/v2/instances/11/",
            "related": {
                "jobs": "/api/v2/instances/11/jobs/",
                "instance_groups": "/api/v2/instances/11/instance_groups/",
                "health_check": "/api/v2/instances/11/health_check/"
            },
            "uuid": "adaab148-5636-4984-b36e-be901eeff068",
            "hostname": "awx-56fbfbb6c8-bw2ms",
            "created": "2022-01-28T22:42:02.019666Z",
            "modified": "2022-01-28T22:42:02.019770Z",
            "last_seen": "2022-01-28T22:43:02.187845Z",
            "last_health_check": "2022-01-28T22:43:02.187845Z",
            "errors": "",
            "capacity_adjustment": "1.00",
            "version": "12.0.0",
            "capacity": 296,
            "consumed_capacity": 0,
            "percent_capacity_remaining": 100.0,
            "jobs_running": 0,
            "jobs_total": 0,
            "cpu": 8,
            "memory": 33255153664,
            "cpu_capacity": 32,
            "mem_capacity": 296,
            "enabled": true,
            "managed_by_policy": true,
            "node_type": "control"
        },
        {
            "id": 7,
            "type": "instance",
            "url": "/api/v2/instances/7/",
            "related": {
                "jobs": "/api/v2/instances/7/jobs/",
                "instance_groups": "/api/v2/instances/7/instance_groups/",
                "health_check": "/api/v2/instances/7/health_check/"
            },
            "uuid": "841d750f-a8f9-4c13-a14b-365bdb079729",
            "hostname": "awx-56fbfbb6c8-m8s8p",
            "created": "2022-01-28T06:40:27.070514Z",
            "modified": "2022-01-28T06:40:27.070694Z",
            "last_seen": "2022-01-28T22:42:53.175415Z",
            "last_health_check": "2022-01-28T22:42:53.175415Z",
            "errors": "",
            "capacity_adjustment": "1.00",
            "version": "12.0.0",
            "capacity": 296,
            "consumed_capacity": 0,
            "percent_capacity_remaining": 100.0,
            "jobs_running": 0,
            "jobs_total": 14,
            "cpu": 8,
            "memory": 33255153664,
            "cpu_capacity": 32,
            "mem_capacity": 296,
            "enabled": true,
            "managed_by_policy": true,
            "node_type": "control"
        },
        {
            "id": 10,
            "type": "instance",
            "url": "/api/v2/instances/10/",
            "related": {
                "jobs": "/api/v2/instances/10/jobs/",
                "instance_groups": "/api/v2/instances/10/instance_groups/",
                "health_check": "/api/v2/instances/10/health_check/"
            },
            "uuid": "242d8af0-9482-4910-8d6c-729ef468ccb6",
            "hostname": "awx-56fbfbb6c8-m94jq",
            "created": "2022-01-28T22:41:54.635204Z",
            "modified": "2022-01-28T22:41:54.635716Z",
            "last_seen": "2022-01-28T22:42:54.171040Z",
            "last_health_check": "2022-01-28T22:42:54.171040Z",
            "errors": "",
            "capacity_adjustment": "1.00",
            "version": "12.0.0",
            "capacity": 296,
            "consumed_capacity": 0,
            "percent_capacity_remaining": 100.0,
            "jobs_running": 0,
            "jobs_total": 0,
            "cpu": 8,
            "memory": 33255153664,
            "cpu_capacity": 32,
            "mem_capacity": 296,
            "enabled": true,
            "managed_by_policy": true,
            "node_type": "control"
        }
    ]
}
```

I **think** we get this data from the health check, but its getting data from the whole underlying node.

If we want this to be dynamic, we need to get the CPU/memory data from the k8s api. OR....let the operator or some setting TELL us what it is when creating the pod, which I think is more KISS.

If we get and respect this information (e.g. we implement https://github.com/ansible/awx/issues/10694), we COULD set our memory/cpu requests equal to the limits in the pod definition, which would put the control nodes in the [Guaranteed QoS class ](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed). This would be great, because if we keep JUST requests on job pods they will be Burstable QoS class, and thus a lower priority. So if the k8s cluster does start to run out of resources, it will evict jobs before ever touching the control plane, which I think is the right thing to do as evicting the control plane pod ends up losing all events in flight and all jobs currently being controled by that node, so its a much worse situation that losing a couple of jobs to avert the whole k8s node going down.

### AWX version

devel

### Installation method

minikube

### Modifications

no

### Operating system

fedora

### Web browser

Chrome

### Steps to reproduce

run awx on k8s

### Expected results

we calculate the capacity of the control node to have something related to the resource request/limit on the pod

### Actual results

We calculate we can use the whole underlying node * however many pods are on the node....
2+2= 8!!!

**Comment by shanemcd** [comment]
Is this the same as https://github.com/ansible/awx/issues/11036 ?

**Comment by kdelee** [comment]
Only difference is https://github.com/ansible/awx/issues/11036 doesn't mention the CPU also being wrong
