### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by Jonathan-Caruana** [ansible/awx#11648]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

When a playbook is launched on CentOS 5 target i got an error from ansible_legacy_setup module

### AWX version

19.5.1

### Installation method

minikube

### Modifications

no

### Ansible version

2.11.7

### Operating system

CentOS 8

### Web browser

Chrome

### Steps to reproduce

Run any playbook on CentOS 5 server

### Expected results

ansible_legacy_setup module should work.

### Actual results

the JSON output said : 

```
ansible_facts": {},
  "msg": "The following modules failed to execute: ansible.legacy.setup\n",
  "failed_modules": {
    "ansible.legacy.setup": {
      "failed": true,
      "module_stdout": "  File \"/home/ansible/.ansible/tmp/ansible-tmp-1643629028.9983337-30-123665618305593/AnsiballZ_setup.py\", line 70\r\n    with open(args_path, 'rb') as f:\r\n            ^\r\nSyntaxError: invalid syntax\r\n",
      "module_stderr": "Shared connection to myserver closed.\r\n",
      "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
      "rc": 1,
      "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
      },
      "warnings": [
        "Platform linux on host vs-ics-prd-ste-de-501 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-core/2.11/reference_appendices/interpreter_discovery.html for more information."
```

**Comment by nixocio** [comment]
Hello,

This  is not a problem with AWX, please, verify the Ansible versions that targeted the OS that you are using.
