### ISSUE TITLE
Install AWX 2.1.2 on CentOS7.9

### ISSUE THREAD

**Issue by pxsc437** [ansible/awx#11652]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

TASK [local_docker : Activate postgres container] ******************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on url.intranet's Python /usr/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: No module named requests.exceptions"}

### AWX version

2.1.2

### Installation method

docker on linux

### Modifications

no

### Ansible version

2.9.25

### Operating system

CentOS Linux release 7.9.2009 (Core)

### Web browser

Firefox

### Steps to reproduce

\# tar xzvf awx-2.1.2.tar.gz -C /
\# cd /awx-2.1.2/installer/
\# ansible-playbook -i inventory install.yml

### Expected results

successfully installed 

### Actual results

\# cd /awx-2.1.2/installer/
\# ansible-playbook -i inventory install.yml

PLAY [Build and deploy AWX] ****************************************************

TASK [check_vars : include_tasks] **********************************************
skipping: [localhost]

TASK [check_vars : include_tasks] **********************************************
included: /awx-2.1.2/installer/roles/check_vars/tasks/check_docker.yml for localhost

TASK [check_vars : postgres_data_dir should be defined] ************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [check_vars : host_port should be defined] ********************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [image_build : Set global version if not provided] ************************
skipping: [localhost]

TASK [image_build : Verify awx-logos directory exists for official install] ****
skipping: [localhost]

TASK [image_build : Copy logos for inclusion in sdist] *************************
skipping: [localhost]

TASK [image_build : Set sdist file name] ***************************************
skipping: [localhost]

TASK [image_build : AWX Distribution] ******************************************
skipping: [localhost]

TASK [image_build : Stat distribution file] ************************************
skipping: [localhost]

TASK [image_build : Clean distribution] ****************************************
skipping: [localhost]

TASK [image_build : Build sdist builder image] *********************************
skipping: [localhost]

TASK [image_build : Build AWX distribution using container] ********************
skipping: [localhost]

TASK [image_build : Build AWX distribution locally] ****************************
skipping: [localhost]

TASK [image_build : Set docker build base path] ********************************
skipping: [localhost]

TASK [image_build : Set awx_web image name] ************************************
skipping: [localhost]

TASK [image_build : Set awx_task image name] ***********************************
skipping: [localhost]

TASK [image_build : Ensure directory exists] ***********************************
skipping: [localhost]

TASK [image_build : Stage sdist] ***********************************************
skipping: [localhost]

TASK [image_build : Template web Dockerfile] ***********************************
skipping: [localhost]

TASK [image_build : Template task Dockerfile] **********************************
skipping: [localhost]

TASK [image_build : Stage launch_awx] ******************************************
skipping: [localhost]

TASK [image_build : Stage launch_awx_task] *************************************
skipping: [localhost]

TASK [image_build : Stage nginx.conf] ******************************************
skipping: [localhost]

TASK [image_build : Stage supervisor.conf] *************************************
skipping: [localhost]

TASK [image_build : Stage supervisor_task.conf] ********************************
skipping: [localhost]

TASK [image_build : Stage settings.py] *****************************************
skipping: [localhost]

TASK [image_build : Stage requirements] ****************************************
skipping: [localhost]

TASK [image_build : Stage config watcher] **************************************
skipping: [localhost]

TASK [image_build : Stage Makefile] ********************************************
skipping: [localhost]

TASK [image_build : Stage ansible repo] ****************************************
skipping: [localhost]

TASK [image_build : Stage ansible repo key] ************************************
skipping: [localhost]

TASK [image_build : Build base web image] **************************************
skipping: [localhost]

TASK [image_build : Build base task image] *************************************
skipping: [localhost]

TASK [image_build : Tag task and web images as latest] *************************
skipping: [localhost]

TASK [image_build : Clean docker base directory] *******************************
skipping: [localhost]

TASK [image_push : Authenticate with Docker registry if registry password given] ***
skipping: [localhost]

TASK [image_push : Remove web image] *******************************************
skipping: [localhost]

TASK [image_push : Remove task image] ******************************************
skipping: [localhost]

TASK [image_push : Tag and push web image to registry] *************************
skipping: [localhost]

TASK [image_push : Tag and push task image to registry] ************************
skipping: [localhost]

TASK [image_push : Set full image path for Registry] ***************************
skipping: [localhost]

TASK [kubernetes : fail] *******************************************************
skipping: [localhost]

TASK [kubernetes : include_tasks] **********************************************
skipping: [localhost] => (item=openshift_auth.yml)
skipping: [localhost] => (item=openshift.yml)

TASK [kubernetes : include_tasks] **********************************************
skipping: [localhost] => (item=kubernetes_auth.yml)
skipping: [localhost] => (item=kubernetes.yml)

TASK [kubernetes : Use kubectl or oc] ******************************************
skipping: [localhost]

TASK [kubernetes : set_fact] ***************************************************
skipping: [localhost]

TASK [kubernetes : Record deployment size] *************************************
skipping: [localhost]

TASK [kubernetes : Set expected post-deployment Replicas value] ****************
skipping: [localhost]

TASK [kubernetes : Delete existing Deployment] *********************************
skipping: [localhost]

TASK [kubernetes : Get Postgres Service Detail] ********************************
skipping: [localhost]

TASK [kubernetes : Template PostgreSQL Deployment] *****************************
skipping: [localhost]

TASK [kubernetes : Deploy and Activate Postgres] *******************************
skipping: [localhost]

TASK [kubernetes : Deploy and Activate Postgres (Kubernetes)] ******************
skipping: [localhost]

TASK [kubernetes : Set postgresql hostname to helm package service] ************
skipping: [localhost]

TASK [kubernetes : Wait for Postgres to activate] ******************************
skipping: [localhost]

TASK [kubernetes : Set task image name] ****************************************
skipping: [localhost]

TASK [kubernetes : Set web image name] *****************************************
skipping: [localhost]

TASK [kubernetes : Render deployment templates] ********************************
skipping: [localhost] => (item=None)
skipping: [localhost] => (item=None)
skipping: [localhost] => (item=None)
skipping: [localhost]

TASK [kubernetes : Apply Deployment] *******************************************
skipping: [localhost]

TASK [kubernetes : Delete any existing management pod] *************************
skipping: [localhost]

TASK [kubernetes : Template management pod] ************************************
skipping: [localhost]

TASK [kubernetes : Create management pod] **************************************
skipping: [localhost]

TASK [kubernetes : Wait for management pod to start] ***************************
skipping: [localhost]

TASK [kubernetes : Migrate database] *******************************************
skipping: [localhost]

TASK [kubernetes : Check for Tower Super users] ********************************
skipping: [localhost]

TASK [kubernetes : create django super user if it does not exist] **************
skipping: [localhost]

TASK [kubernetes : update django super user password] **************************
skipping: [localhost]

TASK [kubernetes : Create the default organization if it is needed.] ***********
skipping: [localhost]

TASK [kubernetes : Delete management pod] **************************************
skipping: [localhost]

TASK [kubernetes : Scale up deployment] ****************************************
skipping: [localhost]

TASK [local_docker : Export Docker web image if it isnt local and there isnt a registry defined] ***
skipping: [localhost]

TASK [local_docker : Export Docker task image if it isnt local and there isnt a registry defined] ***
skipping: [localhost]

TASK [local_docker : Set docker base path] *************************************
skipping: [localhost]

TASK [local_docker : Ensure directory exists] **********************************
skipping: [localhost]

TASK [local_docker : Copy web image to docker execution] ***********************
skipping: [localhost]

TASK [local_docker : Copy task image to docker execution] **********************
skipping: [localhost]

TASK [local_docker : Load web image] *******************************************
skipping: [localhost]

TASK [local_docker : Load task image] ******************************************
skipping: [localhost]

TASK [local_docker : Set full image path for local install] ********************
skipping: [localhost]

TASK [local_docker : Set DockerHub Image Paths] ********************************
ok: [localhost]

TASK [local_docker : Activate postgres container] ******************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on url.intranet's Python /usr/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: No module named requests.exceptions"}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1    skipped=77   rescued=0    ignored=0

### Additional information

\# python --version
Python 2.7.5

\# yum install -y python3-pip

\# pip3 install --upgrade pip --proxy "http://user:pass@proxy:port"

\# pip --version
pip 21.3.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)

\# python3 --version
Python 3.6.8

\# yum install -y libselinux-python3

\# ll $(which python)*
lrwxrwxrwx. 1 root root     7 Jan 19 15:21 /usr/bin/python -> python2
lrwxrwxrwx. 1 root root     9 Jan 19 15:21 /usr/bin/python2 -> python2.7
-rwxr-xr-x. 1 root root  7144 Nov 16  2020 /usr/bin/python2.7
lrwxrwxrwx. 1 root root     9 Jan 31 17:21 /usr/bin/python3 -> python3.6
-rwxr-xr-x. 2 root root 11328 Nov 16  2020 /usr/bin/python3.6
-rwxr-xr-x. 2 root root 11328 Nov 16  2020 /usr/bin/python3.6m

\# docker --version
Docker version 20.10.9, build c2ea9bc

\# pip3 install docker-compose --proxy "http://user:pass@proxy:port"

\# docker-compose --version
docker-compose version 1.29.2, build unknown

\# which docker-compose
/usr/local/bin/docker-compose

\# ansible --version | head -n1

\# tar xzvf awx-2.1.2.tar.gz -C /
\# cd /awx-2.1.2/installer/
\# ansible-playbook -i inventory install.yml

**Comment by ffirg** [comment]
Sorry we cannot help you. This is not a support forum and that release is really, really old. Please try the latest release.
