### ISSUE TITLE
Non-string value found for env option. Ambiguous env options must be wrapped in quotes to avoid them being interpreted. Key: DATABASE_PORT

### ISSUE THREAD

**Issue by pxsc437** [ansible/awx#11657]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

I have the same problem as mentioned on the other thread. 
https://github.com/geerlingguy/ansible-role-awx/issues/31

### AWX version

2.1.2

### Installation method

docker on linux

### Modifications

no

### Ansible version

2.9.0

### Operating system

CentOS Linux release 7.9.2009 (Core)

### Web browser

Firefox

### Steps to reproduce

\# cd /awx-2.1.2/installer/
\# ansible-playbook -i inventory install.yml

### Expected results

install successfully

### Actual results

TASK [local_docker : Activate AWX Web Container] *******************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Non-string value found for env option. Ambiguous env options must be wrapped in quotes to avoid them being interpreted. Key: DATABASE_PORT"}

PLAY RECAP *********************************************************************
localhost                  : ok=10   changed=3    unreachable=0    failed=1    skipped=79   rescued=0    ignored=0

### Additional information

I don't know where DATABASE_PORT is defined?

**Comment by pxsc437** [comment]
I found the solution here:
https://github.com/ansible/awx/issues/3033

In inventory file in [all:vars] section
pg_port: 5432
I've change to pg_port="5432" , and this is resolve issue.

**Comment by CodyGuo** [comment]
DATABASE_PORT：“{{ pg_port | int }}”
