### ISSUE TITLE
Advanced search boolean keys- clarity needed for user

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#11667]
In the schedules list, if a user chooses advanced search, and then enters the search values as follows:
Set type: or    Key: enabled    Lookup type: exact   
the API wants the user to pass a boolean in the input box in order to understand how to return the desired resources- but there is no indication for the user that a boolean value is required, except for this:
![image](https://user-images.githubusercontent.com/63685497/152218591-c100f25d-c034-4fff-bfa9-f2aae554a006.png)

Suggested improvement: If the user selects a key that requires a boolean value to be input, whenever they select that key, placeholder text should pop up inside the input box that says something like "enter a boolean value".

This would improve user experience where advanced search is concerned across all resources.

**Comment by nixocio** [comment]
This is the same issue as https://github.com/ansible/awx/issues/9956

**Comment by nixocio** [comment]
Closing in favor https://github.com/ansible/awx/issues/9956
