### ISSUE TITLE
[Tech debt] Stop tracking instance group capacity in the task manager

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#11669]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
When allocating jobs to instance groups in the task manager, we incorrectly dock capacity from instance groups.

This proposal is that we stop bothering trying to track capacity in this way because it's already handled by the instance `remaining_capacity` in-memory field.

https://github.com/ansible/awx/blob/bff49f2a5fd8929808b2890bc2d16279c523cc53/awx/main/scheduler/task_manager.py#L603-L612

There is a major logical problem with this method, walk through:
 - I have instance groups `A` and `B`, created through the API
 - both of these instance groups have the same instance in them
 - a job is assigned to instance group `A` and the one instance mentioned
 - remaining capacity is docked from `A` in-loop, but remaining capacity of `B` is unaffected

This is not correct, if we were respecting the intent of the method, then capacity should be docked from all instance groups that the instance is a member of. But if it's not useful anyway, we shouldn't keep it.

When we "consider" an instance group to assign a job two, we look at the criteria:

1. Does the instance group have any remaining capacity (using the incorrect tracking of capacity). If not, this abort.
2. Do any of the instance in the instance group have enough remaining capacity to run the job? If so, then select this instance.
3. Are any of the instances in the instance group idle? If so, then select this instance.

This issue proposes that we drop (1) from this. It's not needed, because it's covered by 2 and 3.

Consider this another sub-issue of https://github.com/ansible/awx/issues/11306

Discovered by @kdelee

**Comment by AlanCoding** [comment]
We have lost our size label, but I wanted to mark this as a small issue. Compare to its companion issue, https://github.com/ansible/awx/issues/11671, this is much easier and a direct simplification. So this should be done first.

**Comment by kdelee** [comment]
I think after https://github.com/ansible/awx/pull/11665 goes in, there may not be anything actually checking the remaining capacity in the instance group. E.g. we can drop all of the tabulation on the instance group itself.

We can do this and keep the same https://github.com/ansible/awx/blob/15c7a3f85b5e948f011c67111c4433a38c4544e9/awx/main/scheduler/task_manager.py#L89 just drop https://github.com/ansible/awx/blob/15c7a3f85b5e948f011c67111c4433a38c4544e9/awx/main/scheduler/task_manager.py#L91-L95 and all the methods we use to maintain that data
https://github.com/ansible/awx/blob/15c7a3f85b5e948f011c67111c4433a38c4544e9/awx/main/scheduler/task_manager.py#L603
https://github.com/ansible/awx/blob/15c7a3f85b5e948f011c67111c4433a38c4544e9/awx/main/scheduler/task_manager.py#L600
https://github.com/ansible/awx/blob/15c7a3f85b5e948f011c67111c4433a38c4544e9/awx/main/managers.py#L228

and related tests for those specific methods

**Comment by kdelee** [comment]
I would do this BEFORE https://github.com/ansible/awx/issues/11671 because getting rid of the calls to `Instance.remaining_capacity` is going to be a bit trickier.

**Comment by AlanCoding** [comment]
> I think after https://github.com/ansible/awx/pull/11665 goes in, there may not be anything actually checking the remaining capacity in the instance group. E.g. we can drop all of the tabulation on the instance group itself.

Yes, this is why I didn't make a point of it in that PR. To be perfectly consistent about an "everything we create gets used" rule, that PR would remove all notions of "consumed_control_capacity". But after I realized how useless the capacity tracking was it become apparent that the easier and safer course of action is to delete these methods completely.

Surprisingly, I can't associate a concrete behavioral bug with how we handle instance group capacity. It's just... not needed.

There _used_ to be some nuance preventing us from doing this. Specifically, jobs in the "waiting" state were assigned to instance groups, but not assigned to instances. A lot of the weird structure of the logic you read is in an effort to deal with that weirdness. At some point the task manager changed so that it assigned `execution_node` (and now control node too) when it changed the status from pending to waiting. We have not harvested the dividends of simplifications that allows.

**Comment by AlanCoding** [comment]
I believe @kdelee's recent merges already effectively accomplish this.
