### ISSUE TITLE
Show "copy" in user_capabilities

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#1167]
This is a followup issue for https://github.com/ansible/awx/pull/903

The UI will need "copy" inside of summary_fields -> `user_capabilities` for at least some resources. The resources that have the copy endpoint are the following.

 - job templates
 - projects
 - inventories
 - workflows
 - credentials
 - notification templates
 - inventory scripts

The copy capability is a non-trivial calculation for at least some of these. Consider:

Inventories and projects have an associated `organization`. When a copy is made, the copy must have the same organization. That means that the necessary permission to copy the resource is exactly the admin_role to the related organization. This information is not available to the UI anywhere else.

There may be some trivial rule that the UI can key off of for some resources (like for inventory scripts, it might be the same as "edit" capability). So I don't want to say from the get-go that we will be adding this field for all the resources listed above.

Ping @jakemcdermott

**Comment by jakemcdermott** [comment]
> There may be some trivial rule that the UI can key off

👍 

Although a user capability summary field would be best, checking for the presence or value of an existing field or combination of fields for some of these resources works just fine as well - we'd just need to determine what those fields and corresponding rules are.

**Comment by AlanCoding** [comment]
Note:

Logic for copy capability will change with the merge of https://github.com/ansible/awx/pull/1123

Best to hold off of this issue until that is merged.

**Comment by AlanCoding** [comment]
Some revised notes on what permission is necessary for which

Job templates | Use role for projectUse role for inventory
-- | --
projects | Organization-project-admin for project’s organization,or system admin
inventories | Organization-inventory-admin for inventories organization,or system adminUnclear for smart inventories. Probably require org admin for this case.
workflows | Organization-workflow-admin for workflow’s organization,or system admin
credentials | Organization-credential-admin for credential’s organization,Admin for credential if organization is nullOr system admin
Notification templates | Organization-notification-admin for NT’s admin,Or system admin
Inventory scripts | Organization admin for script’s organization,Or system admin

Some of these can be prefetched, and with the new RBAC roles, this is definitely different from anything else currently available.
