### ISSUE TITLE
[External Logger] event called `session` is missing in `Ansible App` over Splunk GUI 

### ISSUE THREAD

**Issue by gabhishek627** [ansible/awx#11677]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
This issue is related to the following:

Event name `session` seems to be missing from Ansible App over Splunk GUI even though all the logging aggregators are defined properly in Tower. However, the other logs from Tower are pushing to splunk but while selecting Ansible App an event named 
session is missing. So, it can not generate the dashboard. 

Reference doc to enable Ansible App : https://splunkbase.splunk.com/app/4023/#/details

However, it can be achieved via using customized callback plugin with ansible CLI to get the data on "Ansible App" over Splunk GUI.
https://docs.ansible.com/ansible/latest/collections/community/general/splunk_callback.html

EXPECTED RESULTS
Events published for Ansible App over Splunk GUI when Tower integrated with Splunk via enable external logging only

**Comment by ffirg** [comment]
Hi. We don't maintain or own that app so sorry we are unable to assist here.
