### ISSUE TITLE
Docker installation doesn't work

### ISSUE THREAD

**Issue by e36Alex** [ansible/awx#11680]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Hello,

i wanted to try out AWX in docker.
I created an debian 11 lxc on a proxmox host (privileged and active nesting).
I followed the the steps in the docs but stuck at the point describes below.

Thanks in advance,
Alex

### AWX version

19.5.1

### Select the relevant components

- [ ] UI
- [ ] API
- [X] Docs

### Installation method

docker on linux

### Modifications

no

### Ansible version

2.12.2

### Operating system

Debian11

### Steps to reproduce

- Followed the steps described at prerequisites in docs
- cd /tmp
- git clone -b 19.5.1 https://github.com/ansible/awx.git
- cd awx
- docker-compose-build

### Expected results

`(host)$ docker images

REPOSITORY                                   TAG                 IMAGE ID            CREATED             SIZE
ansible/awx_devel                            latest              ba9ec3e8df74        26 minutes ago      1.42GB`

### Actual results

`root@kube01:/tmp/awx# make docker-compose-build
ansible-playbook tools/ansible/dockerfile.yml -e build_dev=True -e receptor_image=quay.io/ansible/receptor:devel
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
[WARNING]: An error occurred while calling ansible.utils.display.initialize_locale (unsupported locale setting). This may result in incorrectly calculated text widths that can
cause Display to print incorrect line lengths

PLAY [Render AWX Dockerfile and sources] ****************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************
ok: [localhost]

TASK [dockerfile : Create _build directory] *************************************************************************************************************************************
ok: [localhost]

TASK [dockerfile : Render supervisor configs] ***********************************************************************************************************************************
ok: [localhost] => (item=supervisor.conf)
ok: [localhost] => (item=supervisor_task.conf)

TASK [dockerfile : Render Dockerfile] *******************************************************************************************************************************************
ok: [localhost]

PLAY RECAP **********************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

DOCKER_BUILDKIT=1 docker build -t quay.io/awx/awx_devel:local \
    --build-arg BUILDKIT_INLINE_CACHE=1 \
    --cache-from=quay.io/awx/awx_devel:local .
[+] Building 1.6s (8/46)                                                                                                                                                         
 => [internal] load build definition from Dockerfile                                                                                                                        0.0s
 => => transferring dockerfile: 32B                                                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                                                           0.0s
 => => transferring context: 34B                                                                                                                                            0.0s
 => [internal] load metadata for quay.io/centos/centos:8                                                                                                                    0.6s
 => ERROR importing cache manifest from quay.io/awx/awx_devel:local                                                                                                         0.2s
 => [internal] load build context                                                                                                                                           0.0s
 => => transferring context: 20.35kB                                                                                                                                        0.0s
 => CANCELED FROM quay.io/ansible/receptor:devel                                                                                                                            0.6s
 => => resolve quay.io/ansible/receptor:devel                                                                                                                               0.3s
 => => sha256:164697e7e141be6792414c40248c8e38371cb6e8eef4efa5956391d6ac844367 7.23kB / 7.23kB                                                                              0.0s
 => => sha256:758c773fb4aa0f4fd0f3ca9c1e13b81c4eaa23d778ece6d85da0c059bb44e678 0B / 20.57MB                                                                                 0.6s
 => => sha256:e3ff3ac72de54e9c2a7cd37e244393ef33680384b30ac7f377824e3ac9ee42cb 1.88kB / 1.88kB                                                                              0.3s
 => => sha256:dd3ad7d1b11430a8b80c09197929332d0d9d09b07b1cbbe7880479a1c0fb992a 2.05kB / 2.05kB                                                                              0.0s
 => => sha256:203c612978b420640831f6a491adfa7eec07afeec38cc9a0d5e304d079da02dd 0B / 88.06MB                                                                                 0.6s
 => => sha256:5186e8704530cdee8a88e122a484f833c1a4b21ecdaac7007e474b546ba34c38 0B / 63.94MB                                                                                 0.6s
 => CACHED [stage-1  1/32] FROM quay.io/centos/centos:8@sha256:ec16f510e8cd1cceeddc6888fcb37c6d6b7c6863fbc70bdbe660a8ccad4bab6a                                             0.0s
 => ERROR [stage-1  2/32] RUN dnf -y module enable 'postgresql:12'                                                                                                          0.8s
------                                                                                                                                                                           
 > importing cache manifest from quay.io/awx/awx_devel:local:
------
------
 > [stage-1  2/32] RUN dnf -y module enable 'postgresql:12':
#6 0.325 /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
#6 0.744 CentOS Linux 8 - AppStream                      280  B/s |  38  B     00:00    
#6 0.747 Failed to set locale, defaulting to C.UTF-8
#6 0.747 Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
------
executor failed running [/bin/sh -c dnf -y module enable 'postgresql:12']: exit code: 1
make: *** [Makefile:491: docker-compose-build] Fehler 1`

**Comment by todd** [comment]
I'm also running into this. I'm trying to run this inside an Ubuntu 20.04 VM.

**Comment by ghost** [comment]
Ran into the same problem on a freshly installed Rocky Linux 8.5. 
Tried the 19.4.0, 19.5.0 and 19.5.1 but they all use the same image in the `Dockerfile.j2`.

CentOS 8 is still being used and it's EOL. They migrated the "yum URL's mirrorlists" to a vault, which breaks the initial deployment.
Workarround; I changed: https://github.com/ansible/awx/blob/19.5.1/tools/ansible/roles/dockerfile/templates/Dockerfile.j2

`FROM quay.io/centos/centos:8 as builder` to:
`FROM quay.io/centos/centos:stream8 as builder`

I suggest you try editing your `<awx-folder>/tools/ansible/roles/dockerfile/templates/Dockerfile.j2`

The `make docker-compose-build` finished succesfully and the image got created:
`quay.io/awx/awx_devel     HEAD        6e6d193d97fc  2 minutes ago      2.39 GB`

**Comment by nixocio** [comment]
We already update for `centos:stream8`  on awx/devel. It will be part of the next release. In the meantime we can run `make docker-compose-build` on devel.

**Comment by e36Alex** [comment]
Hi again and thanks for the replies and help.

One problem is solved, but now i got the next one:

`
root@awx:/tmp/awx# make docker-compose-build
ansible-playbook tools/ansible/dockerfile.yml -e build_dev=True -e receptor_image=quay.io/ansible/receptor:devel
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
[WARNING]: An error occurred while calling ansible.utils.display.initialize_locale (unsupported locale setting). This may result in incorrectly calculated text widths that can
cause Display to print incorrect line lengths

PLAY [Render AWX Dockerfile and sources] ****************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************
ok: [localhost]

TASK [dockerfile : Create _build directory] *************************************************************************************************************************************
ok: [localhost]

TASK [dockerfile : Render supervisor configs] ***********************************************************************************************************************************
ok: [localhost] => (item=supervisor.conf)
ok: [localhost] => (item=supervisor_task.conf)

TASK [dockerfile : Render Dockerfile] *******************************************************************************************************************************************
ok: [localhost]

PLAY RECAP **********************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

DOCKER_BUILDKIT=1 docker build -t quay.io/awx/awx_devel:devel \
    --build-arg BUILDKIT_INLINE_CACHE=1 \
    --cache-from=quay.io/awx/awx_devel:devel .
[+] Building 521.1s (50/50) FINISHED                                                                                                                                             
 => [internal] load build definition from Dockerfile                                                                                                                        0.1s
 => => transferring dockerfile: 7.57kB                                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                                           0.0s
 => => transferring context: 76B                                                                                                                                            0.0s
 => [internal] load metadata for quay.io/centos/centos:stream9                                                                                                              1.6s
 => importing cache manifest from quay.io/awx/awx_devel:devel                                                                                                               0.5s
 => https://raw.githubusercontent.com/containers/libpod/master/contrib/podmanimage/stable/containers.conf                                                                   0.0s
 => [internal] load build context                                                                                                                                           0.0s
 => => transferring context: 43.48kB                                                                                                                                        0.0s
 => https://raw.githubusercontent.com/containers/libpod/master/contrib/podmanimage/stable/podman-containers.conf                                                            0.0s
 => FROM quay.io/ansible/receptor:devel                                                                                                                                    89.8s
 => => resolve quay.io/ansible/receptor:devel                                                                                                                               0.9s
 => => sha256:e3ff3ac72de54e9c2a7cd37e244393ef33680384b30ac7f377824e3ac9ee42cb 1.88kB / 1.88kB                                                                              0.3s
 => => sha256:05b083182b3ee952ebe54353baa00852ea8a712258e70743f97bd0e92ce87a50 7.23kB / 7.23kB                                                                              0.0s
 => => sha256:203c612978b420640831f6a491adfa7eec07afeec38cc9a0d5e304d079da02dd 88.06MB / 88.06MB                                                                           43.5s
 => => sha256:eaa4fe314ea2a548f809300bfcf21f08f134d79f31ad4c111155a115b213383d 2.05kB / 2.05kB                                                                              0.0s
 => => sha256:758c773fb4aa0f4fd0f3ca9c1e13b81c4eaa23d778ece6d85da0c059bb44e678 20.57MB / 20.57MB                                                                            8.8s
 => => sha256:5186e8704530cdee8a88e122a484f833c1a4b21ecdaac7007e474b546ba34c38 63.94MB / 63.94MB                                                                           42.1s
 => => sha256:70ca33688a96d8aa85fbe6001195b0d3548977c519bd89edd7e3414d984b2e64 79.87MB / 79.87MB                                                                           54.6s
 => => extracting sha256:203c612978b420640831f6a491adfa7eec07afeec38cc9a0d5e304d079da02dd                                                                                   3.8s
 => => sha256:9fbd05b8a061cb774ea62d918e40c775d25a0158b57b01ab96c9a77d63731ab8 9.70kB / 9.70kB                                                                             46.3s
 => => sha256:b74ec2b6b3f17482d45a0dfdcc654830c9f61b9c612ef9e04d9030035f6b27d6 1.36kB / 1.36kB                                                                             46.5s
 => => sha256:fc21a915b5efa3ce53d4d521685c0e84228e0c0803c248c4afb04b31faf89b0b 57.39kB / 57.39kB                                                                           46.6s
 => => sha256:6902324784412aa194ecc0b20c0b44f638ae952403bddefd8c6466694bd9a909 286B / 286B                                                                                 46.8s
 => => sha256:144aeb5ada31e1155e0d6fd1cf3f9a726f13d598ec319eb85a8bf3602f9d91c8 327B / 327B                                                                                 46.9s
 => => sha256:ad5a0f069c54a888aa840ad6bf5fd135ddc49bd0046daa6a430bb9c637246ab5 18.27MB / 18.27MB                                                                           54.6s
 => => extracting sha256:e3ff3ac72de54e9c2a7cd37e244393ef33680384b30ac7f377824e3ac9ee42cb                                                                                   0.0s
 => => extracting sha256:758c773fb4aa0f4fd0f3ca9c1e13b81c4eaa23d778ece6d85da0c059bb44e678                                                                                   0.3s
 => => extracting sha256:5186e8704530cdee8a88e122a484f833c1a4b21ecdaac7007e474b546ba34c38                                                                                   2.9s
 => => extracting sha256:70ca33688a96d8aa85fbe6001195b0d3548977c519bd89edd7e3414d984b2e64                                                                                  10.2s
 => => extracting sha256:9fbd05b8a061cb774ea62d918e40c775d25a0158b57b01ab96c9a77d63731ab8                                                                                   0.0s
 => => extracting sha256:b74ec2b6b3f17482d45a0dfdcc654830c9f61b9c612ef9e04d9030035f6b27d6                                                                                   0.0s
 => => extracting sha256:fc21a915b5efa3ce53d4d521685c0e84228e0c0803c248c4afb04b31faf89b0b                                                                                   0.0s
 => => extracting sha256:6902324784412aa194ecc0b20c0b44f638ae952403bddefd8c6466694bd9a909                                                                                   0.0s
 => => extracting sha256:144aeb5ada31e1155e0d6fd1cf3f9a726f13d598ec319eb85a8bf3602f9d91c8                                                                                   0.0s
 => => extracting sha256:ad5a0f069c54a888aa840ad6bf5fd135ddc49bd0046daa6a430bb9c637246ab5                                                                                   0.3s
 => [builder 1/9] FROM quay.io/centos/centos:stream9@sha256:17976ee0d402bf7af576802efb50e3c7841a3e0a5721c6781cd51b5087e67160                                               26.7s
 => => resolve quay.io/centos/centos:stream9@sha256:17976ee0d402bf7af576802efb50e3c7841a3e0a5721c6781cd51b5087e67160                                                        0.0s
 => => sha256:306370400e87172c44062ec81fe82f3f3c893b6c27c845e0a45a13a2b7a41e07 55.37MB / 55.37MB                                                                           24.9s
 => => sha256:17976ee0d402bf7af576802efb50e3c7841a3e0a5721c6781cd51b5087e67160 970B / 970B                                                                                  0.0s
 => => sha256:013a08cd71d0cc7add9b9aab75a037f9098422584953c4d8af8db9632eb22c6b 429B / 429B                                                                                  0.0s
 => => sha256:b549cd888499ff84f4210dff9fab293dc58ca917dec595bcd9a78d2d1487797f 1.16kB / 1.16kB                                                                              0.0s
 => => extracting sha256:306370400e87172c44062ec81fe82f3f3c893b6c27c845e0a45a13a2b7a41e07                                                                                   1.5s
 => [builder 2/9] RUN dnf -y update && dnf install -y 'dnf-command(config-manager)' &&     dnf config-manager --set-enabled crb &&     dnf -y install     gcc     gcc-c+  157.7s
 => [stage-1  2/32] RUN dnf -y update && dnf install -y 'dnf-command(config-manager)' &&     dnf config-manager --set-enabled crb &&     dnf -y install acl     git-core   98.8s
 => [stage-1  3/32] RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 &&     chmod 700 get_helm.sh &&     ./get_helm.sh   8.1s
 => [stage-1  4/32] RUN curl -L -o /usr/bin/tini https://github.com/krallin/tini/releases/download/v0.19.0/tini-amd64 &&     chmod +x /usr/bin/tini                         1.2s
 => [stage-1  5/32] RUN pip3 install virtualenv supervisor                                                                                                                  4.3s
 => [stage-1  6/32] RUN rm -rf /root/.cache && rm -rf /tmp/*                                                                                                                3.1s
 => [stage-1  7/32] RUN dnf -y install     crun     gdb     gtk3     gettext     hostname     procps     alsa-lib     libX11-xcb     libXScrnSaver     iproute     strac  145.6s
 => [builder 3/9] RUN pip3 install virtualenv                                                                                                                               6.1s
 => [builder 4/9] ADD Makefile /tmp/Makefile                                                                                                                                0.0s
 => [builder 5/9] RUN mkdir /tmp/requirements                                                                                                                               1.7s
 => [builder 6/9] ADD requirements/requirements.txt     requirements/requirements_tower_uninstall.txt     requirements/requirements_git.txt     /tmp/requirements/          0.0s
 => [builder 7/9] RUN cd /tmp && make requirements_awx                                                                                                                    201.1s
 => [stage-1  8/32] RUN pip3 install black git+https://github.com/coderanger/supervisor-stdout                                                                              4.7s
 => [stage-1  9/32] RUN dnf --enablerepo=baseos-debug -y install python3-debuginfo || :                                                                                    10.1s
 => [builder 8/9] ADD requirements/requirements_dev.txt /tmp/requirements                                                                                                   0.0s
 => [builder 9/9] RUN cd /tmp && make requirements_awx_dev                                                                                                                 50.0s
 => [stage-1 10/32] COPY --from=builder /var/lib/awx /var/lib/awx                                                                                                          19.3s
 => [stage-1 11/32] RUN ln -s /var/lib/awx/venv/awx/bin/awx-manage /usr/bin/awx-manage                                                                                      0.3s
 => [stage-1 12/32] COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor                                                                          0.2s
 => [stage-1 13/32] RUN openssl req -nodes -newkey rsa:2048 -keyout /etc/nginx/nginx.key -out /etc/nginx/nginx.csr         -subj "/C=US/ST=North Carolina/L=Durham/O=Ansib  0.7s
 => [stage-1 14/32] RUN dnf install -y podman && rpm --restore shadow-utils 2>/dev/null                                                                                    42.9s
 => [stage-1 15/32] RUN sed -i -e 's|^#mount_program|mount_program|g' -e '/additionalimage.*/a "/var/lib/shared",' -e 's|^mountopt[[:space:]]*=.*$|mountopt = "nodev,fsync  0.4s
 => [stage-1 16/32] RUN mkdir -p /etc/containers/registries.conf.d/ && echo "unqualified-search-registries = []" >> /etc/containers/registries.conf.d/force-fully-qualifie  0.5s
 => [stage-1 17/32] ADD tools/ansible/roles/dockerfile/files/rsyslog.conf /var/lib/awx/rsyslog/rsyslog.conf                                                                 0.0s
 => [stage-1 18/32] ADD tools/ansible/roles/dockerfile/files/wait-for-migrations /usr/local/bin/wait-for-migrations                                                         0.0s
 => [stage-1 19/32] ADD tools/docker-compose/launch_awx.sh /usr/bin/launch_awx.sh                                                                                           0.1s
 => [stage-1 20/32] ADD tools/docker-compose/nginx.conf /etc/nginx/nginx.conf                                                                                               0.0s
 => [stage-1 21/32] ADD tools/docker-compose/nginx.vh.default.conf /etc/nginx/conf.d/nginx.vh.default.conf                                                                  0.0s
 => [stage-1 22/32] ADD tools/docker-compose/start_tests.sh /start_tests.sh                                                                                                 0.0s
 => [stage-1 23/32] ADD tools/docker-compose/bootstrap_development.sh /usr/bin/bootstrap_development.sh                                                                     0.0s
 => [stage-1 24/32] ADD tools/docker-compose/entrypoint.sh /entrypoint.sh                                                                                                   0.0s
 => [stage-1 25/32] ADD tools/scripts/config-watcher /usr/bin/config-watcher                                                                                                0.0s
 => [stage-1 26/32] ADD https://raw.githubusercontent.com/containers/libpod/master/contrib/podmanimage/stable/containers.conf /etc/containers/containers.conf               0.0s
 => [stage-1 27/32] ADD https://raw.githubusercontent.com/containers/libpod/master/contrib/podmanimage/stable/podman-containers.conf /var/lib/awx/.config/containers/conta  0.0s
 => [stage-1 28/32] ADD tools/docker-compose/awx.egg-link /tmp/awx.egg-link                                                                                                 0.1s
 => [stage-1 29/32] ADD tools/docker-compose/awx-manage /usr/local/bin/awx-manage                                                                                           0.0s
 => [stage-1 30/32] ADD tools/scripts/awx-python /usr/bin/awx-python                                                                                                        0.0s
 => [stage-1 31/32] RUN for dir in       /var/lib/awx       /var/lib/awx/rsyslog       /var/lib/awx/rsyslog/conf.d       /var/lib/awx/.local/share/containers/storage       0.4s
 => [stage-1 32/32] RUN for dir in       /etc/containers       /var/lib/awx/.config/containers       /var/lib/awx/.config/cni       /var/lib/awx/venv       /var/lib/awx/v  0.6s
 => exporting to image                                                                                                                                                      0.0s
 => => exporting layers                                                                                                                                                     0.0s
 => => writing image sha256:280ba80c438cb8d9ca4f34f5ee94613a454ba3455f73d34cf155293d60302576                                                                                0.0s
 => => naming to quay.io/awx/awx_devel:devel                                                                                                                                0.0s
 => exporting cache                                                                                                                                                         0.0s
 => => preparing build cache for export                                                                                                                                     0.0s
root@awx:/tmp/awx# docker images
REPOSITORY              TAG       IMAGE ID       CREATED          SIZE
quay.io/awx/awx_devel   devel     280ba80c438c   11 seconds ago   1.54GB
root@awx:/tmp/awx# make docker-compose
ansible-playbook -i tools/docker-compose/inventory tools/docker-compose/ansible/sources.yml \
    -e awx_image=quay.io/awx/awx_devel \
    -e awx_image_tag=devel \
    -e receptor_image=quay.io/ansible/receptor:devel \
    -e control_plane_node_count=1 \
    -e execution_node_count=2 \
    -e minikube_container_group=false \
    -e enable_keycloak=false
[WARNING]: An error occurred while calling ansible.utils.display.initialize_locale (unsupported locale setting). This may result in incorrectly calculated text widths that can
cause Display to print incorrect line lengths

PLAY [Render AWX Dockerfile and sources] ****************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************
ok: [localhost]

TASK [sources : Create _sources directories] ************************************************************************************************************************************
changed: [localhost] => (item=secrets)
changed: [localhost] => (item=receptor)

TASK [sources : Detect secrets] *************************************************************************************************************************************************
ok: [localhost] => (item=pg_password)
ok: [localhost] => (item=secret_key)
ok: [localhost] => (item=broadcast_websocket_secret)

TASK [sources : Generate secrets if needed] *************************************************************************************************************************************
changed: [localhost] => (item={'changed': False, 'stat': {'exists': False}, 'invocation': {'module_args': {'path': '../_sources/secrets/pg_password.yml', 'follow': False, 'get_md5': False, 'get_checksum': True, 'get_mime': True, 'get_attributes': True, 'checksum_algorithm': 'sha1'}}, 'failed': False, 'item': 'pg_password', 'ansible_loop_var': 'item'})
changed: [localhost] => (item={'changed': False, 'stat': {'exists': False}, 'invocation': {'module_args': {'path': '../_sources/secrets/secret_key.yml', 'follow': False, 'get_md5': False, 'get_checksum': True, 'get_mime': True, 'get_attributes': True, 'checksum_algorithm': 'sha1'}}, 'failed': False, 'item': 'secret_key', 'ansible_loop_var': 'item'})
changed: [localhost] => (item={'changed': False, 'stat': {'exists': False}, 'invocation': {'module_args': {'path': '../_sources/secrets/broadcast_websocket_secret.yml', 'follow': False, 'get_md5': False, 'get_checksum': True, 'get_mime': True, 'get_attributes': True, 'checksum_algorithm': 'sha1'}}, 'failed': False, 'item': 'broadcast_websocket_secret', 'ansible_loop_var': 'item'})

TASK [sources : Include generated secrets unless they are explicitly passed in] *************************************************************************************************
ok: [localhost] => (item=None)
ok: [localhost] => (item=None)
ok: [localhost] => (item=None)
ok: [localhost]

TASK [sources : Write out SECRET_KEY] *******************************************************************************************************************************************
changed: [localhost]

TASK [sources : Render configuration templates] *********************************************************************************************************************************
changed: [localhost] => (item=database.py)
changed: [localhost] => (item=websocket_secret.py)
changed: [localhost] => (item=haproxy.cfg)

TASK [sources : Delete old local_settings.py] ***********************************************************************************************************************************
ok: [localhost]

TASK [sources : Copy local_settings.py] *****************************************************************************************************************************************
changed: [localhost]

TASK [sources : Get OS info for sdb] ********************************************************************************************************************************************
ok: [localhost]

TASK [sources : Get user UID] ***************************************************************************************************************************************************
ok: [localhost]

TASK [sources : Set fact with user UID] *****************************************************************************************************************************************
ok: [localhost]

TASK [sources : Set global version if not provided] *****************************************************************************************************************************
skipping: [localhost]

TASK [sources : Generate Private RSA key for signing work] **********************************************************************************************************************
changed: [localhost]

TASK [sources : Generate public RSA key for signing work] ***********************************************************************************************************************
changed: [localhost]

TASK [sources : Render Docker-Compose] ******************************************************************************************************************************************
changed: [localhost]

TASK [sources : Render Receptor Config(s) for Control Plane] ********************************************************************************************************************
changed: [localhost] => (item=1)

TASK [sources : Render Receptor Hop Config] *************************************************************************************************************************************
changed: [localhost]

TASK [sources : Render Receptor Worker Config(s)] *******************************************************************************************************************************
changed: [localhost] => (item=1)
changed: [localhost] => (item=2)

PLAY RECAP **********************************************************************************************************************************************************************
localhost                  : ok=18   changed=11   unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   

docker-compose -f tools/docker-compose/_sources/docker-compose.yml  up  --remove-orphans
Creating network "_sources_default" with the default driver
Creating volume "tools_awx_db" with default driver
Creating volume "tools_redis_socket_1" with default driver
Pulling redis_1 (redis:latest)...
latest: Pulling from library/redis
5eb5b503b376: Pull complete
6530a7ea3479: Pull complete
91f5202c6d9b: Pull complete
9f1ac212e389: Pull complete
82c311187b72: Pull complete
da84aa65ce64: Pull complete
Digest: sha256:0d9c9aed1eb385336db0bc9b976b6b49774aee3d2b9c2788a0d0d9e239986cb3
Status: Downloaded newer image for redis:latest
Pulling postgres (postgres:12)...
12: Pulling from library/postgres
5eb5b503b376: Already exists
daa0467a6c48: Pull complete
7cf625de49ef: Pull complete
bb8afcc973b2: Pull complete
c74bf40d29ee: Pull complete
2ceaf201bb22: Pull complete
1255f255c0eb: Pull complete
d27501cd0cca: Pull complete
4db357d46c78: Pull complete
e650979b10f1: Pull complete
1adff8f1353b: Pull complete
83d894dc9c6c: Pull complete
7d18bcc85c2e: Pull complete
Digest: sha256:7984919d5b1d8bd22539118c671555b50cd3bb5fbc568645a49f61e5ab94b8f9
Status: Downloaded newer image for postgres:12
Pulling receptor-hop (quay.io/ansible/receptor:devel)...
devel: Pulling from ansible/receptor
203c612978b4: Already exists
e3ff3ac72de5: Already exists
758c773fb4aa: Already exists
5186e8704530: Already exists
70ca33688a96: Already exists
9fbd05b8a061: Already exists
b74ec2b6b3f1: Already exists
fc21a915b5ef: Already exists
690232478441: Already exists
144aeb5ada31: Already exists
ad5a0f069c54: Already exists
Digest: sha256:eaa4fe314ea2a548f809300bfcf21f08f134d79f31ad4c111155a115b213383d
Status: Downloaded newer image for quay.io/ansible/receptor:devel
Creating tools_postgres_1 ... done
Creating tools_redis_1    ... done
Creating tools_awx_1      ... error

ERROR: for tools_awx_1  Cannot start service awx_1: OCI runtime create failed: container_linux.go:367: starting container process caused: apply caps: operation not permitted: unknown

ERROR: for awx_1  Cannot start service awx_1: OCI runtime create failed: container_linux.go:367: starting container process caused: apply caps: operation not permitted: unknown
ERROR: Encountered errors while bringing up the project.
make: *** [Makefile:459: docker-compose] Fehler 1
`
