### ISSUE TITLE
Docker installation doesn't work - the 2nd

### ISSUE THREAD

**Issue by e36Alex** [ansible/awx#11686]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Hello again!

i wanted to try out AWX in docker.
I created an debian 11 lxc on a proxmox host (privileged and active nesting).
I followed the the steps in the docs but stuck at the point describes below.

I already opened an issue, that was already solved but now im am running into the next error.
https://github.com/ansible/awx/issues/11680

Thanks in advance,
Alex

### AWX version

devel

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs

### Installation method

docker on linux

### Modifications

no

### Ansible version

2.12.2

### Operating system

Debian11

### Steps to reproduce

- Followed the steps described at prerequisites in docs
- cd /tmp
- git clone -b devel https://github.com/ansible/awx.git
- cd awx
- docker-compose-build
- docker-compose

### Expected results

AWX container starts.

### Actual results

root@awx:/tmp/awx# sudo make docker-compose
ansible-playbook -i tools/docker-compose/inventory tools/docker-compose/ansible/sources.yml \
    -e awx_image=quay.io/awx/awx_devel \
    -e awx_image_tag=devel \
    -e receptor_image=quay.io/ansible/receptor:devel \
    -e control_plane_node_count=1 \
    -e execution_node_count=2 \
    -e minikube_container_group=false \
    -e enable_keycloak=false
[WARNING]: An error occurred while calling ansible.utils.display.initialize_locale (unsupported locale setting). This may result in incorrectly calculated text widths that can
cause Display to print incorrect line lengths

PLAY [Render AWX Dockerfile and sources] ****************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************
ok: [localhost]

TASK [sources : Create _sources directories] ************************************************************************************************************************************
ok: [localhost] => (item=secrets)
ok: [localhost] => (item=receptor)

TASK [sources : Detect secrets] *************************************************************************************************************************************************
ok: [localhost] => (item=pg_password)
ok: [localhost] => (item=secret_key)
ok: [localhost] => (item=broadcast_websocket_secret)

TASK [sources : Generate secrets if needed] *************************************************************************************************************************************
skipping: [localhost] => (item={'changed': False, 'stat': {'exists': True, 'path': '../_sources/secrets/pg_password.yml', 'mode': '0600', 'isdir': False, 'ischr': False, 'isblk': False, 'isreg': True, 'isfifo': False, 'islnk': False, 'issock': False, 'uid': 0, 'gid': 0, 'size': 36, 'inode': 324472, 'dev': 64794, 'nlink': 1, 'atime': 1644007748.9483984, 'mtime': 1644007747.6763413, 'ctime': 1644007747.9883554, 'wusr': True, 'rusr': True, 'xusr': False, 'wgrp': False, 'rgrp': False, 'xgrp': False, 'woth': False, 'roth': False, 'xoth': False, 'isuid': False, 'isgid': False, 'blocks': 8, 'block_size': 4096, 'device_type': 0, 'readable': True, 'writeable': True, 'executable': False, 'pw_name': 'root', 'gr_name': 'root', 'checksum': 'c00d20ae44e300c701d81356c84741cf1adfcb41', 'mimetype': 'text/plain', 'charset': 'us-ascii', 'version': '2664600286', 'attributes': ['extents'], 'attr_flags': 'e'}, 'invocation': {'module_args': {'path': '../_sources/secrets/pg_password.yml', 'follow': False, 'get_md5': False, 'get_checksum': True, 'get_mime': True, 'get_attributes': True, 'checksum_algorithm': 'sha1'}}, 'failed': False, 'item': 'pg_password', 'ansible_loop_var': 'item'}) 
skipping: [localhost] => (item={'changed': False, 'stat': {'exists': True, 'path': '../_sources/secrets/secret_key.yml', 'mode': '0600', 'isdir': False, 'ischr': False, 'isblk': False, 'isreg': True, 'isfifo': False, 'islnk': False, 'issock': False, 'uid': 0, 'gid': 0, 'size': 35, 'inode': 324473, 'dev': 64794, 'nlink': 1, 'atime': 1644007748.9723995, 'mtime': 1644007748.2563674, 'ctime': 1644007748.4363754, 'wusr': True, 'rusr': True, 'xusr': False, 'wgrp': False, 'rgrp': False, 'xgrp': False, 'woth': False, 'roth': False, 'xoth': False, 'isuid': False, 'isgid': False, 'blocks': 8, 'block_size': 4096, 'device_type': 0, 'readable': True, 'writeable': True, 'executable': False, 'pw_name': 'root', 'gr_name': 'root', 'checksum': '4b6ba176fa123314aeb324e7c8d79e049fcb6da0', 'mimetype': 'text/plain', 'charset': 'us-ascii', 'version': '1956454120', 'attributes': ['extents'], 'attr_flags': 'e'}, 'invocation': {'module_args': {'path': '../_sources/secrets/secret_key.yml', 'follow': False, 'get_md5': False, 'get_checksum': True, 'get_mime': True, 'get_attributes': True, 'checksum_algorithm': 'sha1'}}, 'failed': False, 'item': 'secret_key', 'ansible_loop_var': 'item'}) 
skipping: [localhost] => (item={'changed': False, 'stat': {'exists': True, 'path': '../_sources/secrets/broadcast_websocket_secret.yml', 'mode': '0600', 'isdir': False, 'ischr': False, 'isblk': False, 'isreg': True, 'isfifo': False, 'islnk': False, 'issock': False, 'uid': 0, 'gid': 0, 'size': 51, 'inode': 324475, 'dev': 64794, 'nlink': 1, 'atime': 1644007748.9924004, 'mtime': 1644007748.6923869, 'ctime': 1644007748.872395, 'wusr': True, 'rusr': True, 'xusr': False, 'wgrp': False, 'rgrp': False, 'xgrp': False, 'woth': False, 'roth': False, 'xoth': False, 'isuid': False, 'isgid': False, 'blocks': 8, 'block_size': 4096, 'device_type': 0, 'readable': True, 'writeable': True, 'executable': False, 'pw_name': 'root', 'gr_name': 'root', 'checksum': 'ebfc7d7174278d716ddb45cb85f696660b80be4f', 'mimetype': 'text/plain', 'charset': 'us-ascii', 'version': '1658367256', 'attributes': ['extents'], 'attr_flags': 'e'}, 'invocation': {'module_args': {'path': '../_sources/secrets/broadcast_websocket_secret.yml', 'follow': False, 'get_md5': False, 'get_checksum': True, 'get_mime': True, 'get_attributes': True, 'checksum_algorithm': 'sha1'}}, 'failed': False, 'item': 'broadcast_websocket_secret', 'ansible_loop_var': 'item'}) 

TASK [sources : Include generated secrets unless they are explicitly passed in] *************************************************************************************************
ok: [localhost] => (item=None)
ok: [localhost] => (item=None)
ok: [localhost] => (item=None)
ok: [localhost]

TASK [sources : Write out SECRET_KEY] *******************************************************************************************************************************************
ok: [localhost]

TASK [sources : Render configuration templates] *********************************************************************************************************************************
ok: [localhost] => (item=database.py)
ok: [localhost] => (item=websocket_secret.py)
ok: [localhost] => (item=haproxy.cfg)

TASK [sources : Delete old local_settings.py] ***********************************************************************************************************************************
ok: [localhost]

TASK [sources : Copy local_settings.py] *****************************************************************************************************************************************
ok: [localhost]

TASK [sources : Get OS info for sdb] ********************************************************************************************************************************************
ok: [localhost]

TASK [sources : Get user UID] ***************************************************************************************************************************************************
ok: [localhost]

TASK [sources : Set fact with user UID] *****************************************************************************************************************************************
ok: [localhost]

TASK [sources : Set global version if not provided] *****************************************************************************************************************************
skipping: [localhost]

TASK [sources : Generate Private RSA key for signing work] **********************************************************************************************************************
ok: [localhost]

TASK [sources : Generate public RSA key for signing work] ***********************************************************************************************************************
ok: [localhost]

TASK [sources : Render Docker-Compose] ******************************************************************************************************************************************
ok: [localhost]

TASK [sources : Render Receptor Config(s) for Control Plane] ********************************************************************************************************************
ok: [localhost] => (item=1)

TASK [sources : Render Receptor Hop Config] *************************************************************************************************************************************
ok: [localhost]

TASK [sources : Render Receptor Worker Config(s)] *******************************************************************************************************************************
ok: [localhost] => (item=1)
ok: [localhost] => (item=2)

PLAY RECAP **********************************************************************************************************************************************************************
localhost                  : ok=17   changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   

docker-compose -f tools/docker-compose/_sources/docker-compose.yml  up  --remove-orphans
tools_redis_1 is up-to-date
tools_postgres_1 is up-to-date
Starting tools_awx_1 ... error

ERROR: for tools_awx_1  Cannot start service awx_1: OCI runtime create failed: container_linux.go:367: starting container process caused: apply caps: operation not permitted: unknown

ERROR: for awx_1  Cannot start service awx_1: OCI runtime create failed: container_linux.go:367: starting container process caused: apply caps: operation not permitted: unknown
ERROR: Encountered errors while bringing up the project.
make: *** [Makefile:459: docker-compose] Fehler 1

**Comment by e36Alex** [comment]
Nobody an idea?

I this have (almost) the same error with acutual devel release...
`docker-compose -f tools/docker-compose/_sources/docker-compose.yml  up  --remove-orphans
tools_redis_1 is up-to-date
tools_postgres_1 is up-to-date
Starting tools_awx_1 ... error

ERROR: for tools_awx_1  Cannot start service awx_1: OCI runtime create failed: container_linux.go:367: starting container process caused: apply caps: operation not permitted: unknown

ERROR: for awx_1  Cannot start service awx_1: OCI runtime create failed: container_linux.go:367: starting container process caused: apply caps: operation not permitted: unknown
ERROR: Encountered errors while bringing up the project.
make: *** [Makefile:458: docker-compose] Fehler 1`

**Comment by liviozanol** [comment]
I'm installing it multiple times since yesterday and didn't had this problem...

```
git clone -b 19.5.1 https://github.com/ansible/awx.git
cd awx
sed -i 's/# pg_password=""/pg_password="bla"/g;s/# broadcast_websocket_secret=""/broadcast_websocket_secret="blabla"/g;s/# secret_key=""/secret_key="blablabla"/g' tools/docker-compose/inventory

echo "changing centos:8 to centos:stream8"
sed -i 's/centos:8/centos:stream8/' tools/ansible/roles/dockerfile/templates/Dockerfile.j2

EXECUTION_NODE_COUNT=1 COMPOSE_TAG=release_4.1 make docker-compose-build

EXECUTION_NODE_COUNT=1 COMPOSE_TAG=release_4.1 COMPOSE_UP_OPTS=-d make docker-compose
```

Having another problem after installation.... Jobs don't get executed (in fact no instance group is running).... Downgraded to 19.5.0 and awx_devel 3.5.6. Gonna try right now...

Ubuntu 20.04.3 LT
5.4.0-91-generic #102-Ubuntu

**Comment by liviozanol** [comment]
Nope....

```
 sudo docker logs tools_awx_1
 
awx-receiver stdout |   File "/awx_devel/awx/main/managers.py", line 114, in me
awx-receiver stdout |     raise RuntimeError("No instance found with the current cluster host id")
awx-receiver stdout | RuntimeError: No instance found with the current cluster host id

```

[EDIT]

Getting more info from logs on AWX container start, found this:

```
make: hostname: Command not found
if [ "/var/lib/awx/venv" ]; then \
        . /var/lib/awx/venv/awx/bin/activate; \
fi; \
awx-manage provision_instance --hostname= --node_type=hybrid; \
awx-manage register_queue --queuename=controlplane --instance_percent=100;\
awx-manage register_queue --queuename=default --instance_percent=100;
CommandError: Specify `--hostname` to use this command.
```

Seems like the script tries to get the hostname and use it to provision instance., but hostname command is not available at container O.S. It is safer to get this info from `/etc/hostname`... They should update this

Also this error: Error: open /etc/receptor/certs/ca.crt: no such file or directory, but I don't know if this specific error will cause trouble.

I'll continue to investigate and will try also "awx_devel:devel" that was updated 5 hours ago.

**[EDIT2 - SOLUTION]**

Ok.... Changing Makefile to get correct hostname from /etc/hostname solved the problem about instances running....

```sed -i 's/shell hostname/shell cat \/etc\/hostname/' Makefile```

Going to check everything else now way down to playbook execution.

Openend a new issue: https://github.com/ansible/awx/issues/11706

**Comment by e36Alex** [comment]
Thanks for your reply, testing and analyzing!

Today i tried again with actual devel - but without success.
Any ideas how to get closer to the issue of missing permissions? (I am running the commands as root)

**Comment by e36Alex** [comment]
Its still not running with actual devel - any ideas?

**Comment by shanemcd** [comment]
Please try the latest release or build from devel. This has been fixed.
