### ISSUE TITLE
Can't connect GitHub repository

### ISSUE THREAD

**Issue by s-cho-a** [ansible/awx#11683]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

After create a GitHub Personal Access Token and set it to AWX credential, on the project setting page
![0](https://user-images.githubusercontent.com/98935545/152499774-639873e1-323f-4670-9657-c98834c34559.png)
![1](https://user-images.githubusercontent.com/98935545/152499796-c13371e5-8040-4a26-91a3-d35afba40615.png)
On the project setting page, I can't find the credential created above
![2](https://user-images.githubusercontent.com/98935545/152499827-fc5cf515-cba0-4ad0-9e73-e2680f66af13.png)
![3](https://user-images.githubusercontent.com/98935545/152499848-3efbf725-5312-47a6-9d82-cc87a7785b24.png)
On the template setting page, from the credential dropdown list, I can't find the GitHub Personal Access Token, too.
![4](https://user-images.githubusercontent.com/98935545/152499872-8d50d8d3-1e66-4694-a903-27da4770fe1d.png)
If create a GitHub SSH Credential from Source Control type, it can be listed in the Select Source Control Credential of project setting page
![5](https://user-images.githubusercontent.com/98935545/152499889-019af6c0-087b-4afe-b70f-7d18982784ad.png)
![6](https://user-images.githubusercontent.com/98935545/152499904-d2db63e1-4ba3-4278-8b99-2a5a454b6dd4.png)
But when sync source in GitHub got this error:
```
fatal: unable to access 'https://github.com/my-org/awesome.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
```
If use the SCM Private Key on localhost to access GitHub repo, it works. But not work in AWX.

### AWX version

19.5.0

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

As summary above.

### Expected results

Can connect GitHub repository.

### Actual results

Can't connect.

### Additional information

Refs:
[22.1. GitHub webhook setup](https://docs.ansible.com/ansible-tower/latest/html/userguide/webhooks.html#github-webhook-setup)
[Connecting Ansible Tower and Github](https://murrahjm.github.io/Source-Control-and-the-Tower-Project/)

**Comment by AlanCoding** [comment]
@jbradberry correct me if I'm wrong, but I believe the github PAT was introduced in order to use for webhooks. We could (presumably) write injectors to make it usable for project updates, but this is new work which I don't know if we have an issue for anywhere else. If the intent is to plan that, I would like to make it clear. The SCM private key troubleshooting here is a very different topic.

**Comment by s-cho-a** [comment]
@AlanCoding 
I selected the wrong target. It should be **Source Control** type. If set a webhook should use **GitHub Personal Access Token** type.
This issue can be closed.

**Comment by jbradberry** [comment]
> @jbradberry correct me if I'm wrong, but I believe the github PAT was introduced in order to use for webhooks. We could (presumably) write injectors to make it usable for project updates, but this is new work which I don't know if we have an issue for anywhere else. If the intent is to plan that, I would like to make it clear. The SCM private key troubleshooting here is a very different topic.

That's correct.
