### ISSUE TITLE
Connecting rabbitmq is failing intermittently 

### ISSUE THREAD

**Issue by emailvenkatm** [ansible/awx#1168]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY
I am building the awx from the source code using make targets. When  I start the container using the image that I built from source getting the below error.   Can some please help me to find all the where the rabbitmq connection details are mentioned.  When I check the rabbitmq logs for the same user sometimes the  connection is established, sometimes it is failing. Please help!!!!

awx_devel_logs
==============
18:47:29 flower.1    | [W 180208 18:47:29 control:44] 'active' inspect method failed
18:47:29 flower.1    | [W 180208 18:47:29 control:44] 'reserved' inspect method failed
18:47:29 flower.1    | [W 180208 18:47:29 control:44] 'revoked' inspect method failed
18:47:29 flower.1    | [W 180208 18:47:29 control:44] 'conf' inspect method failed
18:47:39 daphne.1    | 2018-02-08 18:47:39,107 INFO     Starting server at tcp:port=8051:interface=127.0.0.1, channel layer awx.asgi:channel_layer.
18:47:39 daphne.1    | 2018-02-08 18:47:39,107 INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
18:47:39 daphne.1    | 2018-02-08 18:47:39,108 INFO     Using busy-loop synchronous mode on channel layer
18:47:39 daphne.1    | 2018-02-08 18:47:39,108 INFO     Listening on endpoint tcp:port=8051:interface=127.0.0.1
18:47:39 receiver.1  | 2018-02-08 18:47:39,204 INFO     awx.main.commands.run_callback_receiver Started worker 0
18:47:39 receiver.1  | 2018-02-08 18:47:39,204 INFO     awx.main.commands.run_callback_receiver Started worker 0
18:47:39 receiver.1  | 2018-02-08 18:47:39,210 INFO     awx.main.commands.run_callback_receiver Started worker 1
18:47:39 receiver.1  | 2018-02-08 18:47:39,210 INFO     awx.main.commands.run_callback_receiver Started worker 1
18:47:39 daphne.1    | 2018-02-08 18:47:39,300 ERROR    Error trying to receive messages: (0, 0): (403) ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.

18:47:40 runworker.1 | Traceback (most recent call last):
18:47:40 runworker.1 |   File "manage.py", line 8, in <module>
18:47:40 runworker.1 |     manage()
18:47:40 runworker.1 |   File "/awx_devel/awx/__init__.py", line 109, in manage
18:47:40 runworker.1 |     execute_from_command_line(sys.argv)
18:47:40 runworker.1 |   File "/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
18:47:40 runworker.1 |     utility.execute()
18:47:40 runworker.1 |   File "/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
18:47:40 runworker.1 |     self.fetch_command(subcommand).run_from_argv(self.argv)
18:47:40 runworker.1 |   File "/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
18:47:40 runworker.1 |     self.execute(*args, **cmd_options)
18:47:40 runworker.1 |   File "/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
18:47:40 runworker.1 |     output = self.handle(*args, **options)
18:47:40 runworker.1 |   File "/venv/awx/lib/python2.7/site-packages/channels/management/commands/runworker.py", line 83, in handle
18:47:40 runworker.1 |     worker.run()
18:47:40 runworker.1 |   File "/venv/awx/lib/python2.7/site-packages/channels/worker.py", line 87, in run
18:47:40 runworker.1 |     channel, content = self.channel_layer.receive_many(channels, block=True)
18:47:40 runworker.1 |   File "/venv/awx/lib/python2.7/site-packages/asgiref/base_layer.py", line 43, in receive_many
18:47:40 runworker.1 |     return self.receive(channels, block)

RabbitMq Logs:
==========

2018-02-08 18:47:27.402 [info] <0.13249.0> connection <0.13249.0> (127.0.0.1:37504 -> 127.0.0.1:5672): user 'awx' authenticated and granted access to vhost '/'
2018-02-08 18:47:27.402 [info] <0.13253.0> connection <0.13253.0> (127.0.0.1:37506 -> 127.0.0.1:5672): user 'awx' authenticated and granted access to vhost '/'
2018-02-08 18:47:39.209 [info] <0.13311.0> accepting AMQP connection <0.13311.0> (127.0.0.1:37534 -> 127.0.0.1:5672)
2018-02-08 18:47:39.225 [error] <0.13311.0> Error on AMQP connection <0.13311.0> (127.0.0.1:37534 -> 127.0.0.1:5672, state: starting):
AMQPLAIN login refused: user 'awx' - invalid credentials
2018-02-08 18:47:39.226 [info] <0.13311.0> closing AMQP connection <0.13311.0> (127.0.0.1:37534 -> 127.0.0.1:5672)
2018-02-08 18:47:39.315 [info] <0.13315.0> accepting AMQP connection <0.13315.0> (127.0.0.1:37536 -> 127.0.0.1:5672)
2018-02-08 18:47:39.319 [error] <0.13315.0> Error on AMQP connection <0.13315.0> (127.0.0.1:37536 -> 127.0.0.1:5672, state: starting):
AMQPLAIN login refused: user 'awx' - invalid credentials

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by matburt** [comment]
> I am building the awx from the source code using make targets.

The setup and configuration from the playbook (and the development containers) do a lot of work behind the scenes to make sure authentication is configured on the rabbitmq instance. It looks like you probably got this wrong. I'd recommend coming into the irc channel and chatting about it since you aren't using our installer.
