### ISSUE TITLE
How to pass Machine credentials as an extra vars to the job template? 

### ISSUE THREAD

**Issue by kTipSSIoYv** [ansible/awx#11690]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

The job template has an option for "Prompt on Launch" for credentials.

![image](https://user-images.githubusercontent.com/9666915/152789088-e3cb99b7-7ad6-409f-8144-b84bdf4d3950.png)
 
I want to pass the credentials name using extra vars. I'm launching these jobs through manageIQ and so I want the user to select the credentials and manageIQ should pass it as extra vars to AWX Tower.

![image](https://user-images.githubusercontent.com/9666915/152789288-b909e5f0-4fbd-4861-8d1e-f804ed008433.png)

Any idea what is the name for it? For example, in order to pass ssh username, we use "ansible_ssh_user".  I expect something similar is there for credentials? If that's possible would the value for the extra vars be just the credentials name? 

I tried `ansible_private_key_file` as the extra vars name with the value `Zabbix` but I get the error that no such file exists (Zabbix).

### AWX version

17.1.0

### Select the relevant components

- [x] UI
- [X] API
- [ ] Docs

### Installation method

docker on linux

### Modifications

no

### Operating system

2.9.18

### Web browser

Chrome

### Steps to reproduce

nil

### Expected results

nil

### Actual results

nil

**Comment by john-westcott-iv** [comment]
For clarity, are you attempting to add a credential to a job launched through the API? If so, you should be able to do that by POSTing a JSON body to the `/api/v2/jobs/<job id>/launch/` endpoint with a body like:
```
{
    "credentials": [
        <credential 1 id>,
        <credential 2 id>,
        ....
    ]
}
```

Be sure that the prompt on launch option is selected for the credential field. Also, note that this needs to be a list of IDs, not names. If all you have is the name you will need to use the API to lookup the ID from the name and organization (a credentials name is not unique).

Let me know if I misinterpreted what you have going on.

**Comment by john-westcott-iv** [comment]
Hi!

Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
