### ISSUE TITLE
Add playbook signature verification in Controller

### ISSUE THREAD

**Issue by yuji-watanabe-jp** [ansible/awx#11695]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

An AWX user prepares the content (playbooks and roles) in SCM repository, and runs a playbook in SCM by launching JobTemplate on Controller. The situation we are addressing in this feature extension is "The playbooks and the roles in SCM repository may be tampered with." If the compromised playbook is exeecuted without notice, it may cause damage to the target host configuration. Ansible becomes safer if tampering attempts can be detected and the execution of compromised playbooks is blocked.

At high-level, AWX user want to prevent anyone from running an ansible job if it is compromised. More concretely, contents (playbooks and roles) is signed on SCM repository, and the signature is verified at Controller before running it.

The proposed solution provides the following capabilities.

- An approver can sign content in SCM repo. 
- The Controller can verify the signature of the content during project update (sync from SCM repo to controller)
- A policy admin can configure feature flag to enable integrity check and public key per project via Controller API
- The Controller can block job execution if the signature of the content is not verified. 
- A policy admin can check how a project is configured, content integrity is verified via Controller API
- A job requester can find the reason for the block when the integrity check failed and the job run was blocked.

**Comment by yuji-watanabe-jp** [comment]
Detail requirement of this feature and initial design for the solution

https://gist.github.com/yuji-watanabe-jp/76286e0e1505801816c5edfa40cc7a14#integrity-verification-and-enforcement-for-playbooks-and-roles-from-scm-repository

**Comment by thenets** [comment]
Feature implemented. Tested.
cc: @InnocentK @jneedle
