### ISSUE TITLE
Allow direct job launches from v2 API (/api/v2/jobs/)

### ISSUE THREAD

**Issue by Xiol** [ansible/awx#1169]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
f3f10df361884d5060796f467181eeaab0309c51 disabled direct job launching via the v2 API. I'd like to propose this commit is reverted. 

Although I guess there was a good reason for disabling this, I've been unable to discover why.

##### ENVIRONMENT
* AWX version: devel (9bc0a0743b608add7cebfe7c976c666a2788a03d)
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: CentOS 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

POST a job object to `/api/v2/jobs/`

```json
{
	"name": "testrun1__job_080c5a9f-d574-4cce-b46b-1b5351d63722",
	"description": "[ED2] Apply roles ([testrole]) and/or playbooks ([]) to 1 hosts",
	"job_type": "run",
	"inventory": 5,
	"project": 6,
	"playbook": "de51657d-9c58-419e-ac70-bd1f5080e2d4.yml",
	"credential": 3,
}
```

##### EXPECTED RESULTS

The job runs as desired without the need for a job template.

##### ACTUAL RESULTS

405 Method Not Allowed
`{"error":"POST not allowed for Job launching in version 2 of the api"}`

##### ADDITIONAL INFORMATION

As you may be able to tell from the example POST, we are auto generating these requests to AWX as we're trying to use it to one-shot provision servers which then leave our control (so no need for permanent inventory/playbook configuration). While I could create an ephemeral job template for this I'd rather avoid the extra API call and management overhead.

**Comment by wenottingham** [comment]
This was intentional... that's actually been deprecated in `/api/v1` for a while. Essentially, allowing the system admin to construct things on the fly that have no linkage to any template is a problem from an RBAC and auditing perspective.

cc @matburt for more details.

**Comment by matburt** [comment]
Yeah unfortunately this just isn't good to carry forward in our new system. We may have something similar to support in a future release but it may be focused on running jobs outside of AWX and recording their details.
