### ISSUE TITLE
hostname shell command not available at awx container

### ISSUE THREAD

**Issue by liviozanol** [ansible/awx#11706]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Shell ```hostname``` command is not available on awx_devel container. 

#### 19.5.0
Since Makefile use it on ```COMPOSE_HOST ?= $(shell hostname)``` installation fails and awx can't correct provision instance inside container

I recommend that Makefile is changed to get this info from /etc/hostname (not using hostname command) since I think is more reliable.

So, change this:
```COMPOSE_HOST ?= $(shell hostname)```
for this:
```COMPOSE_HOST ?= $(shell cat /etc/hostname)```

#### 19.5.1
Since tools/docker-compose/bootstrap_development.sh use it on ```awx-manage provision_instance --hostname="$(hostname)" --node_type="$MAIN_NODE_TYPE"``` installation fails and AWX can't correct provsion instance inside container.

I recommend that file is changed to get this info from /etc/hostname (not using hostname command) since I think is more reliable.

So, change this:
```awx-manage provision_instance --hostname="$(hostname)" --node_type="$MAIN_NODE_TYPE"```
for this:
```awx-manage provision_instance --hostname="$(cat /etc/hostname)" --node_type="$MAIN_NODE_TYPE"```

### AWX version

19.5.1

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs

### Installation method

docker on linux

### Modifications

no

### Ansible version

ansible 2.9.6

### Operating system

Ubuntu 20.04.3 LT

### Web browser

Firefox, Chrome, Safari, Edge

### Steps to reproduce

```
git clone -b 19.5.1 https://github.com/ansible/awx.git
cd awx
sed -i 's/# pg_password=""/pg_password="bla"/g;s/# broadcast_websocket_secret=""/broadcast_websocket_secret="blabla"/g;s/# secret_key=""/secret_key="blablabla"/g' tools/docker-compose/inventory

#CURRENT BUGFIX ON ANOTHER ISSUE
#CURRENT BUGFIX ON ANOTHER ISSUE
echo "changing centos:8 to centos:stream8"
sed -i 's/centos:8/centos:stream8/' tools/ansible/roles/dockerfile/templates/Dockerfile.j2
#CURRENT BUGFIX ON ANOTHER ISSUE
#CURRENT BUGFIX ON ANOTHER ISSUE

EXECUTION_NODE_COUNT=1 COMPOSE_TAG=devel make docker-compose-build

EXECUTION_NODE_COUNT=1 COMPOSE_TAG=devel COMPOSE_UP_OPTS=-d make docker-compose
```

### Expected results

Correct AWX provision

### Actual results

AWX installation script couldn't provision instance....

Error below
```
make: hostname: Command not found
if [ "/var/lib/awx/venv" ]; then \
        . /var/lib/awx/venv/awx/bin/activate; \
fi; \
awx-manage provision_instance --hostname= --node_type=hybrid; \
awx-manage register_queue --queuename=controlplane --instance_percent=100;\
awx-manage register_queue --queuename=default --instance_percent=100;
CommandError: Specify `--hostname` to use this command.
```

### Additional information

```
$docker logs tools_awx_1

(...)
make: hostname: Command not found
if [ "/var/lib/awx/venv" ]; then \
        . /var/lib/awx/venv/awx/bin/activate; \
fi; \
awx-manage provision_instance --hostname= --node_type=hybrid; \
awx-manage register_queue --queuename=controlplane --instance_percent=100;\
awx-manage register_queue --queuename=default --instance_percent=100;
CommandError: Specify `--hostname` to use this command.
(...)
```

#### 19.5.0
If you change change ```hostname``` for ```cat /etc/hostname``` on Makefile everything works as expected:
```COMPOSE_HOST ?= $(shell cat /etc/hostname)```

#### 19.5.1
If you change change ```hostname``` for ```cat /etc/hostname``` on bootstrap_development.sh everything works as expected:
```awx-manage provision_instance --hostname="$(cat /etc/hostname)" --node_type="$MAIN_NODE_TYPE"```

Could also install hostname on container, but I think that getting this information from /etc file is more reliable

**Comment by shanemcd** [comment]
Fixed in https://github.com/ansible/awx/pull/11616 but has not gone out in a release. Should happen sometime next week. In the meantime you can build from devel.
