### ISSUE TITLE
Error on Instance Group List based on RBAC

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#11718]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Error on Instance Group List based on RBAC. There is a request for settings being done at the `InstanceGroupList`.

https://github.com/ansible/awx/blob/6f9d4d89cde79e47e9716b27b3bb515041417598/awx/ui/src/screens/InstanceGroup/InstanceGroupList/InstanceGroupList.js#L71

That leads to an error based on user RBAC.

![image](https://user-images.githubusercontent.com/9053044/153441625-1f664f96-8bf0-4910-98c4-b7db1c735543.png)

### AWX version

devel

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

docker for mac

### Modifications

no

### Steps to reproduce

1 - Login as Org Admin
2 - Go to Instance Group tab on side bar

### Expected results

1 - Display the instance groups list

### Actual results

Error due to lack of permissions to read settings.

**Comment by tiagodread** [comment]
Fixed with the merge of https://github.com/ansible/awx/pull/11839
