### ISSUE TITLE
Can disassociate a hybrid node from Control Plane instance group

### ISSUE THREAD

**Issue by kialam** [ansible/awx#11713]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

A user can disassociate a hybrid node from Control Plane instance group.

### AWX version

AWX 19.5.2

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs

### Installation method

docker for mac

### Modifications

no

### Steps to reproduce

1. Go to Instance Groups.
2. Click on controlplane instance group.
3. Select hybrid node and click Disassociate button.
4. Observe that the controlplane IG is now empty.

### Expected results

A user should not be able to have an empty controlplane IG.

### Actual results

Hybrid node is removed from controlplane IG and the group is now empty.

**Comment by jbradberry** [comment]
cc @AlanCoding @shanemcd

**Comment by AlanCoding** [comment]
@kialam is correct, someone can throw the logic in here:

https://github.com/ansible/awx/blob/709c439afc962b2526cb143813ba9623f69f5dfb/awx/api/views/__init__.py#L510-L514

This is a fast API fix. The control plane memberships should not be modified by the user, if any disagrees let me know. Putting it on-deck.

**Comment by akus062381** [comment]
resolved
