### ISSUE TITLE
Require password to change password

### ISSUE THREAD

**Issue by jaredevantabor** [ansible/awx#1172]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

Standard UI/UX paradigm for non-admin accounts is to require the current password to change a password.

Tower just lets you change your password.

##### ADDITIONAL INFORMATION

ansible-tower issue #3384

**Comment by ffirg** [comment]
This is not something we're looking to implement. We suggest using an external user management system to achieve this.
