### ISSUE TITLE
Add Deleted text to missing resources on Job Details page - Project and Inventory

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#11729]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Add `Deleted` text to missing resources on Job Details page - Project and Inventory

For job templates we have

![image](https://user-images.githubusercontent.com/9053044/153645627-47c625b7-1c39-418d-b78a-35f598943ecc.png)

### AWX version

devel

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

docker for mac

### Modifications

no

### Steps to reproduce

1 - Launch a job template
2 - See job details page
3 - Delete project or inventory associated with job template of step 1
4 - See job details page - We do not show any info about the previous project or inventory

### Expected results

Display `Deleted` when a resource is missing.

### Actual results

No data is shown.

### Additional information

There was a uni-test failing  on `JobDetail.test.js` when upgrading node. And the reason why is because this data is never shown.

See: https://github.com/ansible/awx/pull/11724

```bash
node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Error: Method “text” is meant to be run on 1 node. 0 found instead.".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

```  test('DELETED is shown for required Job resources that have been deleted', () => {
    const newMockData = {
      ...mockJobData,
      summary_fields: {
        ...mockJobData.summary_fields,
        inventory: null,
        project: null,
      },
    };
    wrapper = mountWithContexts(<JobDetail job={newMockData} />);
    const detail = wrapper.find('JobDetail');
    async function assertMissingDetail(label) {
      expect(detail.length).toBe(1);
      expect(detail.find(`Detail[label="${label}"] dt`).text()).toBe(label);
      expect(detail.find(`Detail[label="${label}"] dd`).text()).toBe('DELETED');
    }
    assertMissingDetail('Project');
    assertMissingDetail('Inventory');
  });
```

_No response_

**Comment by akus062381** [comment]
tested. looks good!
