### ISSUE TITLE
Research: Migrating from Enzyme to React Testing Library

### ISSUE THREAD

**Issue by kialam** [ansible/awx#11723]
The official React [docs](https://reactjs.org/docs/testing.html#tools) recommend using React Testing Library [RTL](https://testing-library.com/docs/react-testing-library/intro/). While we currently use Enzyme for our unit tests, it may be worth exploring a) if we want to migrate from Enzyme to RTL, and b) if a), then _how_ we should do this. Some considerations to note during this research phase:
- Why/If we should migrate (is Enzyme reaching EOL?). Are there advantages/disadvantages to staying with Enzyme until it is no longer supported?
- Which approach would be best if we were to migrate?
- Given a specific approach, what is the LOE?
- What approach have other teams taken wrt this migration (Enzyme -> RTL)
- What is the priority of this effort?
- Ways in which to decrease the amount of tech debt this effort could create as a result of moving away from Enzyme

**Comment by kialam** [comment]
Closing this as the research is essentially done. We've decided to write new unit tests using RTL moving forward.

**Comment by sr-shifu** [comment]
Hi, probably it's too late but for future visitors of this page I have written a tool to automate the monitoring of Enzyme deprecation: https://github.com/sr-shifu/eslint-plugin-enzyme-deprecation
You can find more details in my article: https://thesametech.com/migrate-away-from-enzyme/

Feel free to read it and leave your comments! Thank you!
