### ISSUE TITLE
It's no more possible to add template nodes to a workflow without specifying the inventory

### ISSUE THREAD

**Issue by TyraelTLK** [ansible/awx#11722]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

I have workflow where I set the inventory only in the workflow template and not in the single template nodes.
I don't remember when/which version of AWX was I running when I added those.

Now is no more possible to add template nodes without specifying an inventory.
I get an "An inventory must be selected" from the UI and I can't save the node.

![image](https://user-images.githubusercontent.com/1420456/153458798-4493aae6-a790-44f1-8734-393b23016f7d.png)

If I try to put the inventory to null with the API I get:
        "Job Template inventory is missing or undefined."

### AWX version

19.5.0

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs

### Installation method

minikube

### Modifications

no

### Steps to reproduce

Try to add a template node to a workflow without specifying an inventory is not possible.

### Expected results

I should be able to not specify an inventory in order to use the one defined in the workflow template.

### Actual results

I can't save the template node without selecting an inventory.
I can't edit and save the existing nodes that haven't an inventory and that are working correctly.

**Comment by kialam** [comment]
Per the docs `When launched, all job templates in the workflow that have ask_inventory_on_launch=true will use the workflow level inventory.` Looks like the wizard in the WF viz is not respecting the `ask_inventory_on_launch` boolean when asking for a inventory for a WF node.

**Comment by kialam** [comment]
Checking on 3.8, this has been the expected behavior and continues to be the way to create WF nodes in 4.0. To get around your issue you need to specify a default inventory before saving.
