### ISSUE TITLE
Unit test expansion- error handling in forms

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#11730]
There is a lack of consistency in the test cases written to check and verify form error handling. This issue is to track work to improve this.

It would be nice if we minimally apply the test cases below to all CRUD forms (if not implemented yet):

- The user can not save a form if a required field is missing information
- Checking input data using [field validation table](https://www.softwaretestinghelp.com/field-validation-table-fvt-testing/) or any other approach, i.e: can't type an alpha character

The following needs to be added as E2E test coverage:
- Cannot save resource using a name that already exists

**Comment by mabashian** [comment]
> cannot save resource using a name that already exists

This one is probably a better candidate for integration tests

Other ones could be unit tested

**Comment by tiagodread** [comment]
> > cannot save resource using a name that already exists
> 
> This one is probably a better candidate for integration tests
> 
> Other ones could be unit tested

I agree, although we can unit test the 400 behaviour from API to simulate server side validation.
