### ISSUE TITLE
Instances endpoint returning different payload order when sort is applied

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#11740]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

This issue came while working on https://github.com/ansible/awx/pull/11653

basically, whenever you sort the instance list by `Status` `/#/instances?instance.order_by=errors` and then, trying to disable/enable the instance, the payload order changes all the time.

### AWX version

devel

### Select the relevant components

- [X] API

### Installation method

docker on linux

### Modifications

no

### Operating system

Ubuntu LTS

### Web browser

Chrome

### Steps to reproduce

1. Go to top level instances list
2. Sort by Status
3. toggle the instance on the list (with the sort applied)

### Expected results

After patching to enable/disable the instance, the order of the list should respect the sorting applied and always bring the results in the same order

### Actual results

After toggling the instance it shows the instance in a different order

### Additional information

Uploading 152869116-8efcd252-8353-4a80-9cc0-cb6ab580066e.mp4…

**Comment by ikhan2010** [comment]
@rebeccahhh are you still working on this?

**Comment by CFSNM** [comment]
Assigning myself for QE validation

**Comment by rebeccahhh** [comment]
an example in which status hasn't changed but I have disabled and re-enabled a node.
![image](https://user-images.githubusercontent.com/11764497/157565039-85f2874d-4acf-4c2f-beb9-5ba4fbab8c07.png)

![image](https://user-images.githubusercontent.com/11764497/157565229-06f966d1-2fbe-4b79-9e71-415087d876c6.png)

**Comment by rebeccahhh** [comment]
@CFSNM I'm writing API tests for this as well but the actual coding has been completed and can be tested.
