### ISSUE TITLE
 awx17 版本，安装的时候出现报错。

### ISSUE THREAD

**Issue by meng7even** [ansible/awx#11751]
TASK [local_docker : Check for existing Postgres data (run from inside the container for access to file)] ***************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "docker run --rm -v '/root/.awx/pgdocker:/var/lib/postgresql' centos:8 bash -c  \"[[ -f /var/lib/postgresql/10/data/PG_VERSION ]] && echo 'exists'\"\n", "delta": "0:00:00.114973", "end": "2022-02-16 17:13:13.014224", "msg": "non-zero return code", "rc": 125, "start": "2022-02-16 17:13:12.899251", "stderr": "Unable to find image 'centos:8' locally\ndocker: Error response from daemon: Get \"https://registry-1.docker.io/v2/\": dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:39506->[::1]:53: read: connection refused.\nSee 'docker run --help'.", "stderr_lines": ["Unable to find image 'centos:8' locally", "docker: Error response from daemon: Get \"https://registry-1.docker.io/v2/\": dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:39506->[::1]:53: read: connection refused.", "See 'docker run --help'."], "stdout": "", "stdout_lines": []}

**Comment by meng7even** [comment]
我使用的是离线环境，在docker  hub上已经将postgreSQL镜像上传本地了。

**Comment by shanemcd** [comment]
Hello. We do not have resources to support older version of AWX. Please upgrade to the latest.

**Comment by meng7even** [comment]
OK，Thanks！
