### ISSUE TITLE
Calling Webhook from curl leaves webhook in non-working state

### ISSUE THREAD

**Issue by rumline** [ansible/awx#11753]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### AWX version

Ansible Automation Platform Controller 4.1.0

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs

### Installation method

docker on linux

### Modifications

no

### Steps to reproduce

Create a Job Template with a GitLab webhook configured.  The webhook works correctly when called from GitLab; however, it gets left in a non-working state when trying to call the webhook from curl.

The first time the webhook is called a job is generated and runs successfully
```
curl -k -X POST 'https://awx.mineral.lab/api/v2/job_templates/16/gitlab/' -H 'Content-Type: application/json' -H 'X-Gitlab-Token: secret'

{"message":"Job queued."} 
```   

```
Even after the job completes successfully, all subsequent calls fail with the following returned:
curl -k -X POST 'https://awx.mineral.lab/api/v2/job_templates/16/gitlab/' -H 'Content-Type: application/json' -H 'X-Gitlab-Token: secret'

{"message":"Webhook previously received, aborting."} 
```

### Expected results

To be able to call a Job Template's webhook repeatedly from curl successfully.  Is there an additional curl call that needs to be made to reset the webhook to a working state?

### Actual results

The first call succeeds.

```
curl -k -X POST 'https://awx.mineral.lab/api/v2/job_templates/16/gitlab/' -H 'Content-Type: application/json' -H 'X-Gitlab-Token: secret'

{"message":"Job queued."} 
```   

```
Even after the job completes successfully, all subsequent calls fail with the following returned:
curl -k -X POST 'https://awx.mineral.lab/api/v2/job_templates/16/gitlab/' -H 'Content-Type: application/json' -H 'X-Gitlab-Token: secret'

{"message":"Webhook previously received, aborting."} 
```

**Comment by john-westcott-iv** [comment]
We track GUIDs of webhooks that have been run before and don't allow duplicate GUIDs to run additional jobs. For GitLab the GUID is a hash of the POST body to the endpoint: https://github.com/ansible/awx/blob/devel/awx/api/views/webhooks.py#L202
Try changing your payload slightly and you should be able to run the webhook again by using curl against the endpoint. Let us know if that works or not.

**Comment by john-westcott-iv** [comment]
Hi!

Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!

**Comment by rimkov** [comment]
i ve the same issue, what do you mean by "Try changing your payload slightly " ? thank you for your help
