### ISSUE TITLE
Upgrade AWX kit to latest version in Pypi

### ISSUE THREAD

**Issue by mo-saeed** [ansible/awx#11779]
the latest version of AWX kit in pypi is 19.4.0 https://pypi.org/project/awxkit/

can you please update it to latest version 20.0.0

Thanks

**Comment by unixsysadmin** [comment]
Could this be related to https://github.com/ansible/awx/issues/11460 ?

**Comment by nixocio** [comment]
Thanks for reporting this issue.
 
Closing as duplicate of #11460
