### ISSUE TITLE
Unable to filter by multiple Labels

### ISSUE THREAD

**Issue by xenorites** [ansible/awx#11778]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

When attempting to search jobs, filtering by multiple labels with any conditions returns zero results. Many templates have overlapping labels, so being able to search for templates that match more than one label is a must to make the labeling system of use.

### AWX version

19.5.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

Create three templates with the following labels:

- Template 1: `test`, `test1`
- Template 2: `test`, `test1`, `test2`
- Template 3: `test1`, `test2`

Attempt a search for the templates with both `test1` and `test2` labels.

### Expected results

Template 2 and Template 3 should return in the results.

### Actual results

No templates are returned.

**Comment by AlexSCorey** [comment]
I created three job templates and each of them got a `job` label.  Indivudually each template got an individual label as well which was `temp1`, `temp2`, `temp3`.  When filter by `Label Name` using `job` and `temp` I got 0 results.  Should have gotten 1.
`api/v2/unified_jobs/?labels__name__icontains=job&labels__name__icontains=temp1&not__launch_type=sync&order_by=-finished&page=1&page_size=20`

When I go into advanced search and use `or` set type `labels` for key and `i_contains` for  lookup type and I search for `job` and `temp1` I get all templates that have a label `job` and `temp`, even though `temp` does not exist as a label

`api/v2/unified_jobs/?not__launch_type=sync&or__labels__name__icontains=job&or__labels__name__icontains=temp&order_by=-`finished&page=1&page_size=20

**Comment by marshmalien** [comment]
There is a way to filter by multiple labels in the current state of the UI, however we should make the search design more intuitively obvious. There are a couple of ways we could handle this. The first and simplest solution would be to add a hint via placeholder text whenever a user performs a fuzzy search on the labels key. A second and more complex solution would involve redesigning a portion of the advanced search input. This could include dropping in a special typeahead multi-select text input to handle converting multiple chips into a single comma-delimited search query.

_How to filter by multiple labels with a comma separated list_
![filter label](https://user-images.githubusercontent.com/15881645/161089506-461cfb38-e7d2-4692-b06d-51956922e3ab.gif)

_Solution one with placeholder text_
<img width="1310" alt="Screen Shot 2022-03-31 at 10 45 56 AM" src="https://user-images.githubusercontent.com/15881645/161089577-e3e94838-b2e4-4787-8215-0c6952a6fd41.png">

_Solution two with a multi-select text input (rough draft mockup)_
<img width="1412" alt="Screen Shot 2022-03-31 at 10 11 52 AM" src="https://user-images.githubusercontent.com/15881645/161089715-0772201f-bf0c-4656-9d0d-96ad9e2b8a71.png">

**Comment by akus062381** [comment]
@xenorites were you using advanced search for your original query?

**Comment by hesmithrh** [comment]
@akus062381 @marshmalien @mabashian can we close this issue since we have a separate issue to track the docs work? thanks!

**Comment by akus062381** [comment]
yes @hesmithrh
