### ISSUE TITLE
Allow <Detail/> to handle cases where there is no value

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#11786]
##### ISSUE TYPE
Task

##### SUMMARY
Along the same lines of this PR https://github.com/ansible/awx/pull/11776 I think we should pass a key to <Detail/> so that it can handle whether it renders. Doing so would allow us to remove alot of `&& ( <Detail/>` phrases in our detail views and make those more readable.

**Comment by shubhamranjan12** [comment]
Hello,
Can I work on this issue please ?

**Comment by InnocentK** [comment]
Resolved
