### ISSUE TITLE
Unable to create Manual SCM project on new Project on Ansible AWX 

### ISSUE THREAD

**Issue by TekTekkers** [ansible/awx#11781]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Hi All

I am a complete newbie to awx but was hoping to for some pointers and help.

I have my awx up and running on following this [guide](https://computingforgeeks.com/install-and-configure-ansible-awx-on-centos/)

I used Rocky Linux 8.5.
Client Version: v1.22.6+k3s1
Server Version: v1.22.6+k3s1
AWX version 20.0.0

I am unable to locate /var/lib/awx/projects
![Screenshot 2022-02-21 at 12 30 13](https://user-images.githubusercontent.com/57484045/154956208-3afe8326-8bc5-4064-8a67-09f99616b6d5.png)

I have cd into cd awx-operator/
awx-operator]# ll
total 104
drwxr-xr-x.  2 root root    44 Feb 18 10:18 ansible
-rw-r--r--.  1 root root   108 Feb 18 10:18 awx-demo.yml
-rw-r--r--.  1 root root   380 Feb 18 10:22 awx-instance-deployment.yml
drwxr-xr-x.  2 root root    23 Feb 18 10:20 bin
-rw-r--r--.  1 root root  3042 Feb 18 10:18 CHANGELOG.md
drwxr-xr-x. 11 root root   141 Feb 18 10:18 config
-rw-r--r--.  1 root root  6125 Feb 18 10:18 CONTRIBUTING.md
-rw-r--r--.  1 root root   384 Feb 18 10:18 Dockerfile
drwxr-xr-x.  2 root root    46 Feb 18 10:18 docs
-rw-r--r--.  1 root root 11357 Feb 18 10:18 LICENSE
-rw-r--r--.  1 root root  8306 Feb 18 10:18 Makefile
drwxr-xr-x.  4 root root    81 Feb 18 10:18 molecule
drwxr-xr-x.  2 root root    22 Feb 18 10:18 playbooks
-rw-r--r--.  1 root root   326 Feb 18 10:18 PROJECT
drwxr-xr-x.  2 root root    22 Feb 18 10:18 projects
-rw-r--r--.  1 root root   206 Feb 18 10:22 public-static-pvc.yaml
-rw-r--r--.  1 root root 39338 Feb 18 10:18 README.md
-rw-r--r--.  1 root root   115 Feb 18 10:18 requirements.yml
drwxr-xr-x.  5 root root    52 Feb 18 10:18 roles
drwxr-xr-x.  3 root root    32 Feb 18 10:18 vendor
-rw-r--r--.  1 root root   416 Feb 18 10:18 watches.yaml

 
How do I overcome this
Thanks

### AWX version

20.0.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Operating system

Rocky Linux

### Web browser

Firefox

### Steps to reproduce

 have cd into cd awx-operator/
awx-operator]# ll
total 104
drwxr-xr-x.  2 root root    44 Feb 18 10:18 ansible
-rw-r--r--.  1 root root   108 Feb 18 10:18 awx-demo.yml
-rw-r--r--.  1 root root   380 Feb 18 10:22 awx-instance-deployment.yml
drwxr-xr-x.  2 root root    23 Feb 18 10:20 bin
-rw-r--r--.  1 root root  3042 Feb 18 10:18 CHANGELOG.md
drwxr-xr-x. 11 root root   141 Feb 18 10:18 config
-rw-r--r--.  1 root root  6125 Feb 18 10:18 CONTRIBUTING.md
-rw-r--r--.  1 root root   384 Feb 18 10:18 Dockerfile
drwxr-xr-x.  2 root root    46 Feb 18 10:18 docs
-rw-r--r--.  1 root root 11357 Feb 18 10:18 LICENSE
-rw-r--r--.  1 root root  8306 Feb 18 10:18 Makefile
drwxr-xr-x.  4 root root    81 Feb 18 10:18 molecule
drwxr-xr-x.  2 root root    22 Feb 18 10:18 playbooks
-rw-r--r--.  1 root root   326 Feb 18 10:18 PROJECT
drwxr-xr-x.  2 root root    22 Feb 18 10:18 projects
-rw-r--r--.  1 root root   206 Feb 18 10:22 public-static-pvc.yaml
-rw-r--r--.  1 root root 39338 Feb 18 10:18 README.md
-rw-r--r--.  1 root root   115 Feb 18 10:18 requirements.yml
drwxr-xr-x.  5 root root    52 Feb 18 10:18 roles
drwxr-xr-x.  3 root root    32 Feb 18 10:18 vendor
-rw-r--r--.  1 root root   416 Feb 18 10:18 watches.yaml

### Expected results

To create playbooks

### Actual results

None at this stage

**Comment by ffirg** [comment]
Hi. This is repo is for bugs and feature tracking. Please head over to https://groups.google.com/g/awx-project and post your ask there and the community can help out. Thanks.
