### ISSUE TITLE
Hosts are not visible inside inventory groups, but hosts are present

### ISSUE THREAD

**Issue by Lakshmi-Patneedi** [ansible/awx#11789]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

When i try to add hosts to inventory groups, hosts are not visible, but hosts are present inside inventory.

<img width="491" alt="awx" src="https://user-images.githubusercontent.com/94051091/155139196-f0d983b3-f29e-4f8f-983d-f6cdfb7a1c02.PNG">

When i select the checkbox, host was getting selected, and host is appearing as selected.

### AWX version

19.4.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.11.8

### Operating system

Rocky 8.5

### Web browser

Firefox

### Steps to reproduce

Create inventory, then create group inside inventory. Add existing host to that group.

### Expected results

Hosts should be visible inside inventory groups

### Actual results

Hosts near the checkboxes were not visible

**Comment by nixocio** [comment]
hey @Lakshmi-Patneedi, I verified the latest version of AWX, and this issue seems to be fixed.

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/9053044/155166896-30924d18-98c4-47ae-9dbd-7a27cf8e07d5.png">
