### ISSUE TITLE
Joboutput Search: Put Event Dropdown Options in Alpha Order

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#11807]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The options pictured below are not in Alpha order and they should be.
![Screen Shot 2022-02-24 at 10 19 21 AM](https://user-images.githubusercontent.com/39280967/155553158-f1a71047-34c2-4a45-a5ee-0fab22e5ee81.png)

**Comment by shubhamranjan12** [comment]
Can I work on this issue please?

**Comment by AlexSCorey** [comment]
@shubhamranjan12 yes absolutely. Reach out if you need help!

**Comment by shubhamranjan12** [comment]
Thank You @AlexSCorey, I just need a small clarification, This has to be fixed from the api, which populates the dropdown options.

**Comment by AlexSCorey** [comment]
@shubhamranjan12 The actual query params come from the api, but on the ui side we use those to create our own strings which are rendered in the dropdown list.

**Comment by jtmelhorn** [comment]
@AlexSCorey Would you like the options hard-coded in Alpha order, or would it be better to use a sorting function to fix this in case more options are added? 

Adding `columns[1].options.sort((a,b) => 
  {
    return a[1].localeCompare(b[1]);
  });` sorts the drop-down, but it seems like it wouldn't be optimal to run that when the list can be manually updated.  It wouldn't be difficult to manually change it either. This is my first contribution to a non-university project, so I'm not sure what the best option would be here!

![image](https://user-images.githubusercontent.com/72679387/160470790-39a030a7-ec62-445a-8dc6-f86beaff8b3f.png)

Thanks!

**Comment by AlexSCorey** [comment]
The list items are already hard coded so I don't think we need to be able to handle them dynamically.  The only case that I can see where that would be helpful is if we get the keys and values directly from the api.
