### ISSUE TITLE
Too many symbolic links

### ISSUE THREAD

**Issue by bpartin2009** [ansible/awx#11806]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Installed fresh version of ansible tower and upon trying to build a new inventory I am getting an error.
[WARNING]: * Failed to parse
/tmp/bwrap_14_mwj4orug/awx_14_ov0v17x8/tmpdg25sj8s with script plugin:
Inventory script (/tmp/bwrap_14_mwj4orug/awx_14_ov0v17x8/tmpdg25sj8s) had an
execution error: /usr/bin/env: python: Too many levels of symbolic links
[WARNING]: Unable to parse /tmp/bwrap_14_mwj4orug/awx_14_ov0v17x8/tmpdg25sj8s as an inventory source
ERROR! No inventory was parsed, please check your configuration and options.

This was a Tower-bundle upgrade since our last tower DB broke. I get this error whether I try to import an inventory from a project or if I build an inventory from scratch. IDK if this is a bubblewrap error or not.  

### AWX version

3.8.5

### Select the relevant components

- [ ] UI
- [x] API
- [ ] Docs

### Installation method

openshift

### Modifications

no

### Ansible version

2.9.27

### Operating system

RHEL7.9

### Web browser

Firefox

### Steps to reproduce

Install tower-bundle-latest 3.8.5
create project from Git
try to create inventory by pulling in host file from project

### Expected results

Inventory is built

### Actual results

Fails.
[WARNING]: * Failed to parse
/tmp/bwrap_14_mwj4orug/awx_14_ov0v17x8/tmpdg25sj8s with script plugin:
Inventory script (/tmp/bwrap_14_mwj4orug/awx_14_ov0v17x8/tmpdg25sj8s) had an
execution error: /usr/bin/env: python: Too many levels of symbolic links
[WARNING]: Unable to parse /tmp/bwrap_14_mwj4orug/awx_14_ov0v17x8/tmpdg25sj8s as an inventory source
ERROR! No inventory was parsed, please check your configuration and options.

**Comment by nixocio** [comment]
Hey,

This is not the issue tracker for the downstream product, please, contact your Red Hat support contact.

They will help you to sort out this issue.
