### ISSUE TITLE
Can not select inventory directory for "Sourced from a Project" inventory.

### ISSUE THREAD

**Issue by kvaps** [ansible/awx#1180]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Can not select inventory directory for "Sourced from a Project" inventory.

##### ENVIRONMENT
* AWX version: 1.0.3.29
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: Archlinux
* Web Browser: Firefox 58.0

##### STEPS TO REPRODUCE

- Create project with directory where you put all inventory files. (I also have recursive directory structure there)
- Put your inventory files there.
- Create new "Sourced from a Project" inventory from UI
- Try to select your this directory there.

##### EXPECTED RESULTS

All directories from the project listed in the list and available for choose.

##### ACTUAL RESULTS

Only `/ (root)` directory listed there

**Comment by jaredevantabor** [comment]
@kvaps could you pass along the file names and directory paths that you're expecting/using for your inventory files? If you're able, could you include an example project that reproduces this issue?

**Comment by kvaps** [comment]
@jaredevantabor sure, example use case:

This is my project directory tree:
```
.
|-- ansible.cfg
|-- dhcp.yaml
|-- dns.yaml
|-- inventories
|   |-- auto
|   |   |-- moonshot_chassis
|   |   |-- moonshot_nodes
|   |   |   |-- moonshot1
|   |   |   |-- moonshot2
|   |   |   |-- moonshot3
|   |   |   `-- moonshot4
|   |   `-- moonshot_switches
|   `-- core
`-- moonshot-inventory.yaml
```

My ansible configured to use inventories directory (`ansible.cfg`):
```
[defaults]
inventory = inventories
```

I have few chassis, and many blade-servers inside each one.
Inside `inventories/core` file I write something like:
```
[moonshot_chassis]
moonshot1 first_ip=10.36.128.1
moonshot2 first_ip=10.36.128.46
moonshot3 first_ip=10.36.128.91
moonshot4 first_ip=10.36.128.136
```
Then, I have playbook that connecting to the chassis console and collecting data about each blade-server:
```
./moonshot-inventory.yam -l moonshot1
```

All collected data writes into `inventories/auto/moonshot_nodes/<chassis_name>` file, example records:
```
[moonshot_nodes]
m1c2 ip=10.36.128.2 mac='["94:57:a5:d3:d3:da", "94:57:a5:d3:d3:db"]'
m1c3 ip=10.36.128.3 mac='["94:57:a5:d3:ef:9e", "94:57:a5:d3:ef:9f"]'
m1c4 ip=10.36.128.4 mac='["94:57:a5:d3:ed:1e", "94:57:a5:d3:ed:1f"]'
```

Then, after I have needed inventory records, I can call another playbooks for add theese servers into my dhcp-server, for example:
```
./dhcp.yaml -l m1c*
```
And into dns-server:
```
./dns.yaml -l m1c*
```

**Comment by jaredevantabor** [comment]
@kvaps Thanks for the info. It looks like the directory structure is setup fine, what file type are you using for your inventory file? Tower will look for `.ini`, among [some other types of files, including files without an extension](https://github.com/ansible/awx/blob/devel/awx/main/utils/ansible.py#L61). 

I should mention that in the Tower UI you can type your own relative path into the drop down menu, if your files aren't showing up. 
![image](https://user-images.githubusercontent.com/7010629/36112068-41f016e0-0fdd-11e8-8c13-a0de47eb6fc3.png)

**Comment by kvaps** [comment]
I uses inventory files in ini format but their name have no extension, is it important for awx?

> I should mention that in the Tower UI you can type your own relative path into the drop down menu, if your files aren't showing up.

Hey, this is fully solves my issue. I was not found this opportunity earlier :)
Thanks!
Can I close it?

**Comment by jaredevantabor** [comment]
@kvaps Glad that solves your problem! I should lead with that next time :)

**Comment by danielo515** [comment]
> I should mention that in the Tower UI you can type your own relative path into the drop down menu, if your files aren't showing up.
> ![image](https://user-images.githubusercontent.com/7010629/36112068-41f016e0-0fdd-11e8-8c13-a0de47eb6fc3.png)

Is that the same for latest version of AWX? I can not type anything

**Comment by jpic** [comment]
> Is that the same for latest version of AWX? I can not type anything

Works here, but I don't see the same UI rendering, maybe upgrade your AWX?
