### ISSUE TITLE
Cannot save Miscellaneous System Settings on 19.4.0

### ISSUE THREAD

**Issue by al-lac** [ansible/awx#11810]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

I cannot save the Miscellaneous System Settings. Does not matter what i change, when i click Save, nothing happens. 
I also tried it via the API which returns 200 when changing something, but the setting did not change. 

This already happened once and was reported here #4481

Apparently this should already be fixed by #9653 but i still have the same issue on AWX 19.4.0.

### AWX version

19.4.0

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

- Go to Settings > 'Miscellaneous System settings'
- Click on Edit
- Change any Value
- Click Save

### Expected results

The changed value in the Miscellaneous System settings should be saved or an error should be shown if the value provided is not valid. 

### Actual results

Nothing happens and saving is not possible. Changing the value via the API returns 200 but the value in question remains unchanged.

**Comment by nixocio** [comment]
hey @al-lac, I just tried to update a couple values of `Miscellaneous System settings` using the latest AWX version, and I was able to.  Can you upgrade to latest version and confirm that issue remains?

**Comment by al-lac** [comment]
Hey @nixocio! Updating to AWX 20.0.0 solved the issue. Thanks! :-)
