### ISSUE TITLE
LDAP Settings cannot be saved when changing LDAP Group Type

### ISSUE THREAD

**Issue by fouram** [ansible/awx#11817]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

When attempting to save LDAP settings in AWX 20, everything seems to work except the LDAP Group Type dropdown. If I make a change to this menu, clicking Save does nothing, and the awx-web container logs show Bad Request to /api/v2/settings/all:

```
2022-02-27 21:59:48,795 WARNING  [f4fac6dcb6a745dca4253103eaef5eb0] awx.api.generics status 400 received by user admin attempting to access /api/v2/settings/all/ from 10.0.0.48
10.0.0.48 - - [27/Feb/2022:21:59:48 +0000] "PATCH /api/v2/settings/all/ HTTP/1.1" 400 68 "http://10.0.0.48:31616/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0" "-"
2022-02-27 21:59:48,918 DEBUG    [f4fac6dcb6a745dca4253103eaef5eb0] awx.analytics.performance request: <WSGIRequest: PATCH '/api/v2/settings/all/'>, response_time: 0.810s
2022-02-27 21:59:48,919 WARNING  [f4fac6dcb6a745dca4253103eaef5eb0] django.request Bad Request: /api/v2/settings/all/
2022-02-27 21:59:48,919 WARNING  [f4fac6dcb6a745dca4253103eaef5eb0] django.request Bad Request: /api/v2/settings/all/
```

Saving any other settings (and not touching the default value in LDAP Group Type) works as expected.

### AWX version

20.0.0

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Ansible version

core 2.12.3rc1.post0

### Operating system

Ubuntu 20.04 LTS

### Web browser

Firefox

### Steps to reproduce

Fresh install, using admin account: fill in the values for a default LDAP server except leave the default value LDAP Group Type, and Save. Return to the Edit screen and attempt to change LDAP Group Type, and click Save. 

### Expected results

The new LDAP Group Type is applied to the settings and I am returned to the main settings menu.

### Actual results

Nothing; the save is not completed and I am stuck on the Edit page. Logs show a bad request.

### Additional information

Clicking "Revert" to put the original value back into the LDAP Group Type menu allows the Save to process normally.

**Comment by fouram** [comment]
Update: I'm going through the menu and trying the different values one by one; one of them just worked. I'll make a list of which ones work and which ones fail. Possibly there are choices that are no longer valid to django that remain in the menu or something?

**Comment by nixocio** [comment]
@fouram, please, add the network requests being made from the UI to the API.

**Comment by john-westcott-iv** [comment]
Hi!

Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
