### ISSUE TITLE
[JobOutput Doc] Overview of Job Output Feature

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#11822]
Overview of the feature/screen.  Summary of what it does/is

- Elapsed time / unfollow button
- Page up and page down buttons
- Unique qualities of the different job types.  
         - Some don’t allow search by event data and thus Event is not an option in the drop down
         - Some don’t have expand, collapse
-Differences in the output from when a job is running and when a job is complete.  
         - Which features are enabled when it’s running and which aren’t.

**Comment by ffirg** [comment]
I'd like to see this go into the AAP2 docs as well, to explain the new behaviours in v2.

**Comment by mabashian** [comment]
This looks like it's done, going to close.  @tvo318 do you have what you need to track any changes on your end?  Reach out to me if you do not.

**Comment by tvo318** [comment]
Docs work tracked via https://github.com/ansible/product-docs/issues/1727
