### ISSUE TITLE
SAML authentification remove always superuser privilege

### ISSUE THREAD

**Issue by chris93111** [ansible/awx#11831]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Hello 

With configuration saml keycloak and awx the role superuser is always removed after login,
Organization map is empty all other privilege stay 
superuser needed for manage settings and administration

### AWX version

20.0.0

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.9.9

### Operating system

redhat 8.4

### Web browser

Chrome

### Steps to reproduce

configure awx with saml , login first , switch to admin account , set previous user saml to superuser , logout and login 

### Expected results

superuser and auditor user stay after logout

### Actual results

always set normal user

**Comment by chris93111** [comment]
with saml user attr is permanent
{
  "is_superuser_role": "awx_admins",
  "is_system_auditor_role": "awx_auditors"
}

**Comment by Tioborto** [comment]
Hello @chris93111 , 
Sorry to reopen this issue but we have the same issue from our side. 
What and where do you set this settings ?

**Comment by chris93111** [comment]
Hi @Tioborto  is in saml configuration of awx

SAML User Flags Attribute Mapping

**Comment by wiad** [comment]
We ran into the same problem after updating to 21.6.0 from 19.4. 

When I try to set the `SAML User Flags Attribute Mapping` field I get an error when saving:
`Expected a list of items but got type "str"`

With the following format I am able to save:
```
{
    "is_system_auditor_role": ["awx_auditors"],
    "is_superuser_role": ["awx_admins"]
}
```
But no difference in behaviour - when logging in using SAML my superuser privileges are automatically revoked. 
Am I missing something?

**Comment by wiad** [comment]
What I really wanted was
```
{
  "remove_superusers": false,
  "remove_system_auditors": false
}
```
i.e so user privileges set in UI is not revoked on SAML login. 

After setting this everything works as expected.
