### ISSUE TITLE
Unable to run playbook with ansible galaxy roles

### ISSUE THREAD

**Issue by miantianlai** [ansible/awx#11848]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Can't use ansible galaxy roles in AWX.

### AWX version

19.5.1

### Select the relevant components

- [x] UI
- [X] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Operating system

Amazon Linux 2

### Steps to reproduce

Here are some source in my root source repository:

# Galaxy Roles:

/roles/requirements.yml

    ---
    - src: geerlingguy.postgresql

# Collections:

/collections/requirements.yml

    ---
    roles:
      - src: geerlingguy.postgresql

# Playbook:

/playbook/project1/ec2.yaml

    - name: Server
      hosts: server1
      become: true
      roles:
        - geerlingguy.postgresql

### Expected results

Run playbook in AWX successfully.

### Actual results

After I sync the source from github in AWX projects, run template job, got error:

    ERROR! the role 'geerlingguy.postgresql' was not found in /runner/project/playbook/project1/roles:/runner/requirements_roles:/home/runner/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/runner/project/playbook/project1

    The error appears to be in '/runner/project/playbook/project1/ec2.yml': line 10, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:

        - geerlingguy.postgresql
          ^ here

### Additional information

I checked the AWX EE container. I installed the galaxy role manually in path /home/runner/.ansible/roles. But it still doesn't know the role.

Also I can't find the file /runner/project/playbook/project1/ec2.yml in EE container. Where is it?

**Comment by AlexSCorey** [comment]
We recommend that you build your own execution environment.  Please see the docs for [Ansible builder](https://ansible-builder.readthedocs.io/en/stable/)

**Comment by miantianlai** [comment]
@AlexSCorey 
Why doesn't the default **AWX EE (latest)** and **Control Plane Execution Environment** work for that?
I found AWX support Ansible Galaxy for easy using: https://docs.ansible.com/ansible-tower/latest/html/userguide/projects.html#ansible-galaxy-support
