### ISSUE TITLE
DNS Resolution issue while playbook execution

### ISSUE THREAD

**Issue by selkopb** [ansible/awx#11864]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### AWX version

20.0.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Operating system

Ubuntu 20.04

### Steps to reproduce

Hello, 

I am quite new to AWX installations with Kubernetes.
I installed AWX via k3s with the following commands: 

#curl -sfL https://get.k3s.io | sudo bash -
#git clone https://github.com/ansible/awx-operator.git
#cd awx-operator/
#git checkout 0.17.0
#make deploy
namespace/awx created
customresourcedefinition.apiextensions.k8s.io/awxbackups.awx.ansible.com created
customresourcedefinition.apiextensions.k8s.io/awxrestores.awx.ansible.com created
customresourcedefinition.apiextensions.k8s.io/awxs.awx.ansible.com created
serviceaccount/awx-operator-controller-manager created
role.rbac.authorization.k8s.io/awx-operator-awx-manager-role created
role.rbac.authorization.k8s.io/awx-operator-leader-election-role created
clusterrole.rbac.authorization.k8s.io/awx-operator-metrics-reader created
clusterrole.rbac.authorization.k8s.io/awx-operator-proxy-role created
rolebinding.rbac.authorization.k8s.io/awx-operator-awx-manager-rolebinding created
rolebinding.rbac.authorization.k8s.io/awx-operator-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/awx-operator-proxy-rolebinding created
configmap/awx-operator-awx-manager-config created
service/awx-operator-controller-manager-metrics-service created
deployment.apps/awx-operator-controller-manager created

#kubectl apply -f awx-demo.yml

The problem I am having is when running a playbook, the name resolution is not working.
We use an internal DNS resolver, the host manages to communicate with the target host via its DNS name, however the execution of the playbook fails with the following message: 

fatal: [***]: UNREACHABLE! => { "changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname ***: Name or service not known", "unreachable": true}

Does anyone have a resolution path so that the pods can resolve hostnames using our resolver ? 

Thanks in advance for your feedback. 

### Expected results

DNS resolution works

### Actual results

DNS resolution didn't work in the pods

**Comment by nixocio** [comment]
Hello @selkopb ,

This issue tracker is for tracking feature enhancements and bugs. This looks like an issue related to your environment.

If you need help troubleshooting or are looking for help using AWX, try our mailing list or IRC channel:

#ansible-awx on[ https://libera.chat/](https://libera.chat/)
https://groups.google.com/forum/#!forum/awx-project
