### ISSUE TITLE
Hop Node Error Status Not Being Shown for Deleted Hop Node

### ISSUE THREAD

**Issue by InnocentK** [ansible/awx#11877]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Hop node is not showing any errors in either the API (see `errors` field of the instances endpoint) or the UI (see `Status` on instances page) when it is stopped

### AWX version

devel

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs

### Installation method

docker on linux

### Modifications

yes

### Operating system

Fedora 34

### Web browser

Chrome

### Steps to reproduce

1. [On your terminal]  Start an AWX build locally using the configuration for hybrid cluster
2. [On your terminal]  Build the UI and navigate to the instances page in the UI of your local build
3. Confirm  the existence of (at least one) hop node and (at least one) receptor node through the API, the UI or through your AWX CLI
4. Confirm `Healthy` statuses for hop node(s) and receptor node(s) on the UI
5. Navigate to the instances page on the API and confirm `Healthy` statuses for hop node(s) and receptor node(s)
6. [On your terminal] Use docker to find/identify the name for the container holding the hop node (e.g. "tools_receptor_hop")
7. [On your terminal] Use docker to stop the container holding the hop node (e.g. docker stop tools_receptor_hop)
8. (After waiting some time) Confirm that the receptor node(s) and hop node(s) are having errors through the CLI on your terminal
9. Refresh the instances page on the UI
10. Confirm status of receptor node(s) show `Error` but Hop Node still showing `Healthy` status on the instances page
11. Navigate to the instances page on the API and confirm status of receptor node(s) show `Error` but Hop Node still showing `Healthy` status

### Expected results

Hop node(s) would also show `Error` status given that you stopped the container for the hop node(s)

### Actual results

Hop node(s) showing `Healthy` in UI and showing no errors in API

- UI:

![Screenshot from 2022-03-08 16-43-25](https://user-images.githubusercontent.com/37008228/157347938-d2acd179-bf8e-45c5-961e-e8dd6e13d297.png)

- API:

![Screenshot from 2022-03-08 16-44-06](https://user-images.githubusercontent.com/37008228/157347941-af10ea93-6715-44f6-8a20-3a72aa4bf81f.png)

### Additional information

You need to change your deployment topology to allow for hop node to be created (e.g. using a hybrid cluster deployment)

**Comment by InnocentK** [comment]
This bug blocks the work from https://github.com/ansible/awx/issues/11532 to be verified

**Comment by InnocentK** [comment]
This issue might be addressed by: https://github.com/ansible/awx/pull/11714
(Requiring further investigation)

**Comment by InnocentK** [comment]
A proposed solution to this issue: https://github.com/ansible/awx/pull/11898

**Comment by InnocentK** [comment]
Note: We will need to create a new test scenario in the API integration test suite for QE to test this scenario as well as the scenario in #11898
There are technically two different scenarios here:

1. Disable the hop node (hop nodes cannot be disabled directly so disable the machine the node it is running on) and confirm that the errors field is populated
2. Re-do scenario 1 and then re-enable the hop node, make sure it rejoins the mesh and then verify that the previous error is cleared

**Comment by AlanCoding** [comment]
These test cases would be very destructive. Yes, you could stop the receptor service on the hop node and this should get you what you want. These would also be very slow tests due to the poll intervals involved. I worry that would be impractical, as the time and reliability cost for the test suite may not be worth this coverage.

**Comment by AlanCoding** [comment]
I went ahead and merged the related fix.

**Comment by InnocentK** [comment]
> These test cases would be very destructive. Yes, you could stop the receptor service on the hop node and this should get you what you want. These would also be very slow tests due to the poll intervals involved. I worry that would be impractical, as the time and reliability cost for the test suite may not be worth this coverage.

This is a really good point that I had not considered before so thanks for bringing it up.
For now QE will just plan to create a test plan for manual testing of this functionality and not add it to our automated testing so that we can avoid the potential slow down

**Comment by InnocentK** [comment]
This has been resolved so closing. See above comments for followup
