### ISSUE TITLE
jobs settings edit form resulting in error

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#11891]
this week, multiple ec2 builds have shown that the edit form for Job Settings is not working properly, showing this error:
![image](https://user-images.githubusercontent.com/63685497/157759447-a0f0dd0e-b0de-4cc5-a56d-6c926753e286.png)

Important: this only occurs in a production environment, not a development environment.

To reproduce:
Build ec2 off AWX devel
Go to settings
Click Job Settings
Click Edit

**Comment by elcidger** [comment]
Facing the same issue on my self-hosted AWX instance on k3s:

![image](https://user-images.githubusercontent.com/53906625/157862621-c861bd43-553a-45b8-8be1-0fc0741af828.png)

Reproducing steps are the same as mentioned. 

Environment:

k3s version v1.22.7+k3s1 (8432d7f2)
go version go1.16.10

Running on Ubuntu 20.04 LTS.

**Comment by AlanCoding** [comment]
Can we get this re-tested with the AWX PR #11896?

**Comment by akus062381** [comment]
@AlanCoding I'll run tests now

**Comment by akus062381** [comment]
we are good!
