### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [ansible/awx#11899]
Hey there!

I belong to an open source security research community, and a member (@michaellrowley) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by shanemcd** [comment]
Hello. We do have this: 
![awx 2022-03-15 09-48-29](https://user-images.githubusercontent.com/773186/158392382-bdcf2983-8ab3-4292-8ec4-4e1ce4496d7f.png)


If someone wants to copy / paste the content from there into a new SECURITY.md, we'd be happy to approve and merge a PR.

**Comment by JamieSlome** [comment]
@shanemcd - sorted! 👍 

#11909

**Comment by JamieSlome** [comment]
Just for reference, the report in question can be found [here](https://huntr.dev/bounties/506ffd90-d8bf-4942-873b-d611b13b44e6/). It is private and only accessible to maintainers with repository write permissions.

If you aren't happy to sign-up to the platform, (for permission verification), we will send the details to the elected security policy e-mail in any case (no sign-up required 👍).

**Comment by shanemcd** [comment]
Thanks. I've responded there with a comment.

**Comment by JamieSlome** [comment]
Thanks, @shanemcd!
