### ISSUE TITLE
Dockerhub and Quay conflict latest tag

### ISSUE THREAD

**Issue by xbc1** [ansible/awx#11908]
Hi,
at my company we use a nexus server to proxy quay.io and hub.docker.com to pull Images.

There is a conflict because the ansible/awx:latest Image is located on Dockerhub and also Quay.
If I use the latest tag it pulls the one from Dockerhub.

Since the one on Dockerhub is in fact more than 1 year old and the one on Quay a few days old I would suggest to remove the latest Tag from Dockerhub.

-Daniel

**Comment by rebeccahhh** [comment]
hi @xbc1 we don't maintain Dockerhub anymore (which is why it's a year old). We should remove that. Thanks for the heads up.

**Comment by john-westcott-iv** [comment]
It looks like there all of the other AWX containers are there as well and could be removed:
- ansible/awx-operator (updated 2y ago)
- ansible/awx_task (updated 2y ago)
- ansible/awx_web (updated 2y ago)
- ansible/awx_rabbitmq (updated 2y ago)
- ansible/awx-dev (updated 4y ago)
- ansible/postresql (updated 5y ago)

**Comment by shanemcd** [comment]
For better or worse there are folks using super old versions of AWX. If we delete those images, be prepared to get roasted by the internet.

**Comment by shanemcd** [comment]
I've deleted the latest tag on dockerhub.
