### ISSUE TITLE
CLI import command have wrong return code on error condition

### ISSUE THREAD

**Issue by thenets** [ansible/awx#11919]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

The `awxkit` has an inconsistent `return code` when getting an error from `import` command.

I don't know if this extends to other CLI commands, but I believe that all commands should be reviewed.

### AWX version

devel

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs

### Installation method

docker on linux

### Modifications

no

### Steps to reproduce

- Create an invalid JSON to be imported
- Run `awx import < my_file.json`
- Check the return code `echo $?`

### Expected results

- Check the return code `echo $?`
  - It should not return 0 on an error condition

### Actual results

- Check the return code `echo $?`
  - Returns 0 on an error condition.

**Comment by ffirg** [comment]
@thenets still an open issue?

**Comment by thenets** [comment]
@ffirg the behavior changed:

#### Before

- I tried to import an invalid type, like replacing `users` by `coffee`.
- I got an error output, but `rc == 0`

#### Now

- I tried to import an invalid type, like replacing `users` by `coffee`.
- I got **NO** error output and `rc == 0`

So, yeah, we still have the `rc` not being `!= 0` for an invalid value.

You can ping me later if you need the payload that I used.

**Comment by jbradberry** [comment]
Closing as a duplicate issue, for which the PR has merged: https://github.com/ansible/awx/pull/12335
