### ISSUE TITLE
Encrypted password in surveys show up as plaintext in Edit Order page.

### ISSUE THREAD

**Issue by aydinguven** [ansible/awx#11915]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

In the survey page of a template, I added a default answer (as password field), and it shows up as ENCRYPTED, which is expected.

![image](https://user-images.githubusercontent.com/19193869/158795730-dad63f75-411e-4ff1-84ba-868a085fb940.png)

But, when I click "Edit Order", that password shows up in plain text.

![image](https://user-images.githubusercontent.com/19193869/158796141-a359f909-8314-4ed7-ba25-8623f41ccd91.png)

### AWX version

20.0.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Operating system

Red Hat Enterprise Linux 7

### Web browser

Firefox, Chrome, Edge

### Steps to reproduce

- Create a template
- Add a survey question, and define answer type as Password, then add a default answer.
- Click "Edit Order" in survey page to see the password in plaintext.

### Expected results

The form needs to say ENCRYPTED instead of password.

### Actual results

Survey field in "Edit Order" page shows the default survey answer (password) in plain text.

**Comment by tiagodread** [comment]
This is now fixed with the merge of #11917
