### ISSUE TITLE
Add filtering to oVirt/RHEV inventory import to allow selection of inventory host IP

### ISSUE THREAD

**Issue by ghost** [ansible/awx#1191]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Currently, the inventory import script for oVirt/RHEV always select the IP address of the first network interface as the inventory host ip.  This feature would add filtering to allow the ip address of an alternative interface to be used instead.

##### ENVIRONMENT
* AWX version: 1.0.1

##### STEPS TO REPRODUCE

Import an oVirt/RHEV inventory that contains hosts with multiple network interfaces.

##### EXPECTED RESULTS

Additional filtering options will allow for cases where the first interface is not the interface through which Ansible should connect to the host.

##### ACTUAL RESULTS

Only the first interface is available.

**Comment by wenottingham** [comment]
Not investigating this until such support exists upstream (and may way for inventory plugin work)

**Comment by smapjb** [comment]
I have just hit this while trying to manage OpenShift Reference Architecture install.. 
The docker0 interface comes first and so the primary interface of all my openshift hosts in my rhev inventory is the docker interface ip !  just sayin

Exploring a little further - looks like in the next version of RHEV there is an option you can add to the ovirt-guest-agent to stop it reporting certain interfaces
https://tinyurl.com/y7u98lby
Looks like ignoring docker0 is on by default

**Comment by ghost** [comment]
This reports a fix:
https://bugzilla.redhat.com/show_bug.cgi?id=1591646

Do we need to modify the inventory import script to request a network provider?

**Comment by wenottingham** [comment]
The ovirt4.py invnentory script has not been changed on the devel branch in Ansible.

**Comment by machacekondra** [comment]
Please replace old dynamic ovirt inventory by new ovirt inventory plugin, which supports the fature you ask

 https://github.com/ansible/ansible/pull/47565

**Comment by wenottingham** [comment]
this was fixed in an AWX release in mid-2020 when we moved to the inventory plugin
