### ISSUE TITLE
Dynamic inventory manipulation/add_host tasks do not behave properly

### ISSUE THREAD

**Issue by greg-hellings** [ansible/awx#1192]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Adding a host during playbook run will not associate that host with the run's variables.

##### ENVIRONMENT
* AWX version: 1.0.3 (also observed in Ansible Tower versions)
* AWX install method: development source docker deployment
* Ansible version:  2.4.2.0
* Operating System: Linux
* Web Browser: n/a

##### STEPS TO REPRODUCE

1. Create a new project, pulled from SCM at https://github.com/greg-hellings/test-awx-job
2. Create two new inventories - one from inventory/full and one from inventory/minimal at the above job
3. Create Job Templates, one using inventory/full and playbooks/full.yml, the other using inventory/minimal and playbooks/minimal_add_host.yml
4. Run the job with the full inventory
5. Run the job with the minimal inventory

##### EXPECTED RESULTS

Output from the full inventory:
```
PLAY [output test] *************************************************************

TASK [debug] *******************************************************************
ok: [bygroup] => {
    "test_var": "from group"
}
ok: [byhost] => {
    "test_var": "from host"
}
ok: [localhost] => {
    "test_var": "from all"
}

PLAY RECAP *********************************************************************
bygroup                    : ok=1    changed=0    unreachable=0    failed=0   
byhost                     : ok=1    changed=0    unreachable=0    failed=0   
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```
Output from running minimal inventory with minimal_add_hosts.yml playbook on the command line:
```
PLAY [configure hosts] **********************************************************************************

TASK [add bygroup host] *********************************************************************************
changed: [localhost]

TASK [add byhost host] **********************************************************************************
changed: [localhost]

TASK [debug] ********************************************************************************************
ok: [localhost] => {
    "test_var": "from all"
}

PLAY [test output] **************************************************************************************

TASK [output] *******************************************************************************************
ok: [localhost] => {
    "test_var": "from all"
}
ok: [bygroup] => {
    "test_var": "from group"
}
ok: [byhost] => {
    "test_var": "from host"
}

PLAY RECAP **********************************************************************************************
bygroup                    : ok=1    changed=0    unreachable=0    failed=0   
byhost                     : ok=1    changed=0    unreachable=0    failed=0   
localhost                  : ok=4    changed=2    unreachable=0    failed=0
```

##### ACTUAL RESULTS

Results from running minimal inventory and minimal_add_hosts.yml in AWX:
```
PLAY [configure hosts] *********************************************************

TASK [add bygroup host] ********************************************************
changed: [localhost]

TASK [add byhost host] *********************************************************
changed: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "test_var": "from all"
}

PLAY [test output] *************************************************************

TASK [output] ******************************************************************
ok: [bygroup] => {
    "test_var": "VARIABLE IS NOT DEFINED!"
}
ok: [localhost] => {
    "test_var": "from all"
}
ok: [byhost] => {
    "test_var": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP *********************************************************************
bygroup                    : ok=1    changed=0    unreachable=0    failed=0   
byhost                     : ok=1    changed=0    unreachable=0    failed=0   
localhost                  : ok=4    changed=2    unreachable=0    failed=0
```

##### ADDITIONAL INFORMATION

https://github.com/greg-hellings/test-awx-job

The playbooks behave as expected from the command line, but not when executed through AWX. There is an additional playbook that tests doing the same sort of work with the ansible-tower-cli package - which is my ultimate goal, but I did not bother to get that working and test it once the same results were demonstrated with the add_host command directly.

**Comment by greg-hellings** [comment]
In order to assure that this is not purely because the group being created is new, I've added inventory/partial, which includes a host already in the "testgroup" group, and executed it against playbooks/minimal_add_host.yml. Output from an AWX run properly catches variables for the "bygroup_static" host, but not for the dynamically added "bygroup" host.

```
PLAY [configure hosts] *********************************************************

TASK [add bygroup host] ********************************************************
changed: [bygroup_static]

TASK [add byhost host] *********************************************************
changed: [bygroup_static]

TASK [debug] *******************************************************************
ok: [bygroup_static] => {
    "test_var": "from group"
}
ok: [localhost] => {
    "test_var": "from all"
}

PLAY [test output] *************************************************************

TASK [output] ******************************************************************
ok: [bygroup_static] => {
    "test_var": "from group"
}
ok: [localhost] => {
    "test_var": "from all"
}
ok: [bygroup] => {
    "test_var": "VARIABLE IS NOT DEFINED!"
}
ok: [byhost] => {
    "test_var": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP *********************************************************************
bygroup                    : ok=1    changed=0    unreachable=0    failed=0   
bygroup_static             : ok=4    changed=2    unreachable=0    failed=0   
byhost                     : ok=1    changed=0    unreachable=0    failed=0   
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by chrismeyersfsu** [comment]
This is the expectable behavior given the behavior of `ansible-inventory`, which AWX relies on.

Look at the Makefile here https://github.com/chrismeyersfsu/test-awx-job/tree/moreinfo

The above example is closer to how AWX runs when considering the relative location of the dynamic inventory script. Note that `wrapper.sh` is OUTSIDE of the `inventory` directory. Thus, `ansible-playbook` does not pickup any `host_vars` or `group_vars` entries.

**Comment by greg-hellings** [comment]
OK, so it looks like the problem is that ansible-inventory is mashing everything into the hostvars segment instead of using the group construction that has been supported since a long time.

**Comment by wenottingham** [comment]
@greg-hellings see https://github.com/ansible/ansible/issues/30877

**Comment by greg-hellings** [comment]
@wenottingham Yes, more resolutions of that issue, please! Because it's seriously cramping my style not being able to create hosts on the fly.

**Comment by AlanCoding** [comment]
I want to make sure we have triaged the detailed technical parts of this issue correctly. The group vars issue with `ansible-inventory` is the primary reason this doesn't work, but there is a more nuanced issue around `add_host` with empty groups. There is an overlap between those two, but it only matters once the group vars issue has a resolution.

Filed issue for the empty groups gone missing here:

https://github.com/ansible/ansible/issues/36177

I can't guarantee that Ansible core will find this issue a true bug (the vars plugins make the discussion difficult), or that they will think it high enough priority to fix. We can talk more about workarounds or partial solutions on the AWX side for this issue after the group vars thing is working. This may involve a more detailed re-thinking of how users expect Ansible plugins to work with inventory updates, project updates, and subsequent playbook runs.

**Comment by AlanCoding** [comment]
Moving forward, I will prefer to close this issue and create a new AWX placeholder issue related to the empty groups and issue 36177 I filed in Ansible. There is a broader case to be made that vars plugins (and possibly other plugins) don't persist from inventory update -> JT playbook run. That's something I don't think we would consider tackling until a long ways out.

**Comment by greg-hellings** [comment]
This issue is not related to empty groups, as I showed with my first comment after the OP. It's purely related to the Ansible Core bug that eliminates all group vars from the flattened inventory.

**Comment by wenottingham** [comment]
Fixed with https://github.com/ansible/ansible/issues/30877 + https://github.com/ansible/awx/pull/1253

**Comment by AlanCoding** [comment]
The OP also mentioned a different bug from the group_vars, related to inheriting group vars from groups that are initially empty.

I touched base with Ansible core, current state of affairs is that there are no plans of fixing that.
