### ISSUE TITLE
CLI import for existent `application` shouldn't return `stderr` content

### ISSUE THREAD

**Issue by thenets** [ansible/awx#11926]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Try to import an existent `application` results in an unexpected `stderr` content:

```
"Related link 'organization' missing from /api/v2/applications/47/, attempting to reconstruct endpoint.\nUnable to infer endpoint for 'organization' on /api/v2/applications/47/.\n"
```

### AWX version

devel

### Select the relevant components

- [X] UI
- [X] API
- [X] Docs

### Installation method

docker on linux

### Modifications

no

### Steps to reproduce

- Create an application
- Export the application
- Delete the application
- Import the application
- Import the application again <---- the problem is here

### Expected results

- No `stderr` content

### Actual results

- Has `stderr` content:

```
"Related link 'organization' missing from /api/v2/applications/47/, attempting to reconstruct endpoint.\nUnable to infer endpoint for 'organization' on /api/v2/applications/47/.\n"
```

**Comment by AlanCoding** [comment]
This appears to no longer be a blocker for the testing, and otherwise it looks like a low-priority issue. Given its age, I'm closing.
