### ISSUE TITLE
credential- Org required- inconsistency? 

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#11936]
There are 26 different types of credentials that can be created. Only one of these shows Organization as a required field in the Add form. All the others leave it as optional. Is this intentional? If not, can we have consistency across all the credential types?

**Comment by akus062381** [comment]
I checked 3.8.6, and i see that none of the credential types required an organization to be added. I am thinking that perhaps this requirement should be removed here? @nixocio?

This is the credential that requires an organization: 
![image](https://user-images.githubusercontent.com/63685497/160023588-c487a0fa-40ed-4ee4-bf4c-4240d958bc5d.png)

**Comment by nixocio** [comment]
@akus062381, thanks for more details. I will try to understand this difference.

**Comment by nixocio** [comment]
@akus062381, the new UI aligned the required fields as per the API. If you attempt to create a new credential using the type of `Ansible Galaxy/Automation...` using only the API it will required to provide an Org. 

![image](https://user-images.githubusercontent.com/9053044/160130674-67cc4553-6aea-462d-b8c0-a190b684f88d.png)

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/9053044/160131111-7340921e-8cc2-4464-98b3-20f36d59a774.png">
