### ISSUE TITLE
Relink the new job id into the Workflow Visualizer after you restarted a job whis is marked as failed

### ISSUE THREAD

**Issue by chloepriceless** [ansible/awx#11931]
Hi together,

i have a Feature Request for the Workflow Job/Template Visualizer stuff..
It would be nice, if you could relink the new job id into the Workflow Visualizer after you restarted a job whis is marked as failed.
Either restart the full Job or only the Failed hosts, it would be nice if we could see that the failed Job was "restared" and the new job id is linked tho this Workflow Job in the Visualizer. 

So that you could see or someone else if the Workflow was completed successfully. Today you see only some succeded or failed jobs but not if you restarted the failed job and they were ok after the restart. The initial Workflow contains only the "old" ones which are in the failed state.
So even the Workflow and the Jobs was ok after all, the Workflow Visualizer shows that it wasn´t ok.

Hopefully you all get what i mean.

Best regard
Christin,

**Comment by rebeccahhh** [comment]
hi @red17x it's definitelys something we have discussed, but the way that workflows are designed would make this very difficult to do. As of now this is not something that we plan to do, but if that ever changes we will announce it on our mailing list. https://groups.google.com/g/awx-project
