### ISSUE TITLE
Credential Search Filter- Request Ability to Filter by Type

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#11930]
On the list of Credentials, the Type name is shown in the list next to each credential. However, a user cannot filter and just see Amazon Web Services, or Insights, or HashiCorp Vault Secret Lookup, for example. I think that this would be a helpful addition from a user experience perspective.

![image](https://user-images.githubusercontent.com/63685497/159350649-effa369b-ad68-43ff-a3f6-4b8c794afcf3.png)

**Comment by nixocio** [comment]
The API provides `"credential_type__search"` on the credentials endpoint.
