### ISSUE TITLE
Show `ansible` version inside `About` dialog

### ISSUE THREAD

**Issue by Commifreak** [ansible/awx#11948]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The minikube env makes it "hard" to see the used ansible version. It would be great to show the ansible version used in the environment.

![grafik](https://user-images.githubusercontent.com/87267/159855600-068dee60-22b2-4a54-a568-c51cf5758a52.png)

**Comment by AlanCoding** [comment]
This depends on which execution environment you use. Different jobs can use different Ansible versions.
