### ISSUE TITLE
ping shell command does not work

### ISSUE THREAD

**Issue by jangel97** [ansible/awx#11951]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Hello there,

I am working with Ansible Tower 3.8.4, RHEL 8.4 bare metal and I can't run ping via shell command.

```
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "ping [google.com](http://google.com/) -c 5", "delta": "0:00:00.005199", "end": "2022-03-24 09:59:23.286631", "msg": "non-zero return code", "rc": 2, "start": "2022-03-24 09:59:23.281432", "stderr": "ping: socket: Operation not permitted", "stderr_lines": ["ping: socket: Operation not permitted"], "stdout": "", "stdout_lines": []}
```
```
ls -lartZ /usr/bin/ping
-rwxr-xr-x. 1 root root system_u:object_r:ping_exec_t:s0 67680 Feb 22  2021 /usr/bin/ping
```
```
getcap /usr/bin/ping
/usr/bin/ping = cap_net_admin,cap_net_raw+p
```
```
sysctl -a | grep ping
net.ipv4.ping_group_range = 1   0
```
Is it possible that I am missing something? Is this intentional for some reason in Ansible Tower?

I am using isolated nodes and I have seen this issue https://github.com/ansible/awx/issues/2338, but I do not know why this should be disabled, what is the reason?

Thanks in advance,

### AWX version

Tower 3.8.4

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs

### Installation method

boot2docker

### Modifications

no

### Ansible version

2.9.11

### Operating system

RHEL 8.4

### Steps to reproduce

```
---
- name: test ping
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: ping
      shell: ping google.com -c 5
      register: ping
```

### Expected results

I would expect ping to ran as other shell commands

### Actual results

Ping returns "Operation not permitted"

**Comment by ffirg** [comment]
bubblewrap protection, as designed. remove connection:local for it to work

**Comment by jangel97** [comment]
I suppose when control node becomes execution node (when setting `connection: local`), ansible-runner runs from the bubblewrap directory, which is chrooted and therefore there are more constraints.
