### ISSUE TITLE
The dispatcher service fails to ever recover from a restart of the postgres pod

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#11960]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

After the postgres pod is manually deleted (and the awx-operator re-creates it), the dispatcher service is seen by `supervisord` as a `FATAL` process state.

The user-facing effect is that all jobs will stay in pending status after this event because nothing is running tasks anymore.

### AWX version

20.0.1

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs

### Installation method

openshift

### Modifications

no

### Ansible version

N/A

### Operating system

N/A

### Web browser

Chrome

### Steps to reproduce

Delete the postgres pod

```
kubectl delete pod awx-postgres-0
```

Wait for for a while, confirm that database is back up by navigating in the UI.

Now launch any job template

### Expected results

Any _new_ job launch should work fine after postgres has fully recovered

### Actual results

Dispatcher has a FATAL status, so it's not running

```
sh-5.1$ supervisorctl -c /etc/supervisord_task.conf status
tower-processes:callback-receiver   RUNNING   pid 36, uptime 0:44:58
tower-processes:dispatcher          FATAL     Exited too quickly (process log may have details)
```

### Additional information

While the database is unavailable, the dispatcher service is restarted 4 times (hand count, I may be off), and errors every time because the database is down. Then supervisord counts this as a failed service and gives up on it.

It should not do this.

**Comment by shanemcd** [comment]
Related: 
- https://github.com/ansible/awx/pull/11955

**Comment by AlanCoding** [comment]
I felt very confident that PR 11955 addressed this, moving to Needs Test

**Comment by CFSNM** [comment]
Validated from QE side. Closing this item
