### ISSUE TITLE
workflow limit does not limit

### ISSUE THREAD

**Issue by ikke-t** [ansible/awx#11967]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Workflow has limit option which does not limit the targets.

I created workflow of two tasks. First task unsubscribes target from Red Hat subs, insights and IdM. The second task deletes the VM from VMware. I removed the surveys and limitters from the task templates, as the workflow gui didn't allow me to add tasks without setting limit already at task workflow creation time. I set the limit to be queried at start of workflow.

When I started the workflow, it asked for a limit, and I gave it an inventory item. However when the tasks started, it unsubscribed all the hosts from inventory. So limit didn't work as the user interface says, nor how the docs say.

There are two options from my point of view:

1) this is a bug and should be fixed to limit the tasks if workflow has limit
2) Documentation and GUI should be fixed to say what it really does

As such, it gives horrible user experience.

if there is e.g. a requirement that limit only works if task templates have limit set to be asked, then the GUI should be the option renamed to something like "Limit tasks that have limit set to be promtped" or similar, as currently it just leads to errors. Also docs and tooltips should be changed.

Tooltip says now:
```
Provide a host pattern to further constrain the list of hosts that will be managed or affected by the playbook. Multiple patterns are allowed. Refer to Ansible documentation for more information and examples on patterns.
```

[Manual says](https://docs.ansible.com/automation-controller/latest/html/userguide/workflow_templates.html#create-a-workflow-template) now:
```
Limit: Optionally specify a limit for subset of servers that your workflow is going to run. This value is a host pattern to further constrain the list of hosts managed or affected by the playbook. Multiple patterns can be separated by colons (“:”). As with core Ansible, “a:b” means “in group a or b”, “a:b:&c” means “in a or b but must be in c”, and “a:!b” means “in a, and definitely not in b”.

        Prompt on Launch: If selected, even if a default value is supplied, you will be prompted upon launch to choose a limit.
```

And if you do as manual and GUI says, it won't limit.

I use the Ansible Automation Platform Controller 4.1.1, It is installed on RHEL8 VM. I don't have AWX at hand to test.

### AWX version

Ansible Automation Platform Controller 4.1.1

### Select the relevant components

- [X] UI
- [ ] API
- [X] Docs

### Installation method

docker on linux

### Modifications

no

### Ansible version

ansible [core 2.12.1]

### Operating system

RHEL8

### Web browser

Firefox

### Steps to reproduce

I created workflow of two tasks. First task unsubscribes target from Red Hat subs, insights and IdM. The second task deletes the VM from VMware. I removed the surveys and limitters from the task templates, as the workflow gui didn't allow me to add tasks without setting limit already at task workflow creation time. I set the limit to be queried at start of workflow.

When I started the workflow, it asked for a limit, and I gave it an inventory item. However when the tasks started, it unsubscribed all the hosts from inventory. So limit didn't work as the user interface says, nor how the docs say.

### Expected results

Run the tasks at limited target, and the latter vmware task on localhost.

### Actual results

It run away and unsubscribed all the hosts.

**Comment by ikke-t** [comment]
I tried it with simple ping test as task template. The first one had limit set to be prompted, and the other one didn't. The limit worked on the one that had it set.

It seems it applies limit to those tasks that had limit set to be queried.

However, then there is problem with workflow building. When you add task template with limit query to wf it prompts for the limit for the task. It doesn't seem to matter what you put there, it get's ignored.

So if it is ignored, it should not get asked in the first place. If it is asked, it should be then somehow utilized?

**Comment by AlexSCorey** [comment]
@ikke-t Can you elaborate a bit on where you set the limits?  It seems, that given your example you could have set it in 3 different places. 1) The Job template form (could be set, and/or prompt on launch) 2) The job template workflow form (could be set and/or prompt on launch) 3) On a particular node in the workflow visualizer that uses a job template that has the limit set, and/or has the limit prompt on launch set.

**Comment by ikke-t** [comment]
I set it in add workflow dialog.

Later on I tried it in different places to guess the logic. Seems that also inventory has such guess logic, it can be set in different places, and the workflow document doesn'texplain when is it applied and what takes precedence.

Add workflow is very frustrating experience as auch atm.

**Comment by AlexSCorey** [comment]
@ikke-t  
> I set it in add workflow dialog.
Did you set it using the CLI, or the UI?

**Comment by ikke-t** [comment]
GUI

**Comment by ikke-t** [comment]
My original issue above has link to documentation page of it. I followed that.

**Comment by fosterseth** [comment]
refinement note: needs some discussion, and possibly move to unplanned

**Comment by ffirg** [comment]
dup - fixed in https://github.com/ansible/awx/issues/11284
