### ISSUE TITLE
executor failed running [/bin/sh -c cd /tmp && make requirements_awx]: exit code: 127

### ISSUE THREAD

**Issue by alokispandey** [ansible/awx#11962]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

I was following this link (https://github.com/ansible/awx/blob/devel/tools/docker-compose/README.md) to  Installing AWX docker way but its  not working and falinig at " make docker-compose-build" with multiple erros like:
```
1: executor failed running [/bin/sh -c cd /tmp && make requirements_awx]: exit code: 127  
   - though make exists at  /usr/bin/make
 2: DNF packaegs install is also faling that no repo "crb" to enable
```

I tried to execute commdas mentioned in Dockerfile  manualy and then commenting those exexuted command in "tools/ansible/roles/dockerfile/templates/Dockerfile.j2" but no luck.

it seems make docker-compose is faling to excuete any insrutcion from Dockerfile starting with "RUN/ADD ..etc".

Any suggestion how  i can proceed, please?

### AWX version

default/latest

### Select the relevant components

- [X] UI
- [X] API
- [X] Docs

### Installation method

docker on linux

### Modifications

no

### Ansible version

ansible [core 2.12.2]   config file = /etc/ansible/ansible.cfg   configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']   ansible python module location = /usr/lib/python3.8/site-packages/ansible   ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections   executable location = /usr/bin/ansible   python version = 3.8.12 (default, Sep 21 2021, 00:10:52) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]   jinja version = 2.10.3   libyaml = True

### Operating system

centos 8 stream

### Web browser

Firefox

### Steps to reproduce

follow steps here "https://github.com/ansible/awx/blob/devel/tools/docker-compose/README.md"  to setup 

### Expected results

awx installation must complet

### Actual results

installins faling with multiple erros like:

 => ERROR [builder 5/7] RUN cd /tmp && make requirements_awx                                                                                            0.4s
------
 > importing cache manifest from quay.io/awx/awx_devel:HEAD:
------
------
 > [builder 5/7] RUN cd /tmp && make requirements_awx:
#16 0.314 /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
#16 0.314 /bin/sh: line 1: make: command not found
------
executor failed running [/bin/sh -c cd /tmp && make requirements_awx]: exit code: 127
make: *** [Makefile:491: docker-compose-build] Error 1

**Comment by akus062381** [comment]
We aren't seeing this on the latest version of devel; it might have been an intermittent issue with the Cent-OS image. If you are still seeing this issue, please send a message to the mailing list and we can reopen this. 
Reference:
#ansible-awx on[ https://libera.chat/](https://libera.chat/)
https://groups.google.com/forum/#!forum/awx-project
