### ISSUE TITLE
Paginate modal view after modal cancel and reopen remains the same

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#11975]
Situation:
User visits access tab inside of an Org, and goes to add a Team. The user paginates to the last page of the list of teams and then changes their mind, and clicks the cancel button. 
Then they change their mind again and reopen the Add modal. They select Team. Instead of seeing the beginning of the list, like one would expect, the user is brought right back to the last page where they had formerly paginated to before closing the modal.

Steps to reproduce:

Create an organization.
Create 6 teams.
Visit the Access tab of the organization and click Add.
Click Team.
When the list of teams appears, paginate to the last page of teams. Now click Cancel.
Click Add again and select team. You will see the last page you paginated to instead of the beginning of the list like one would expect.

**Comment by InnocentK** [comment]
This has been addressed by https://github.com/ansible/awx/pull/12229
