### ISSUE TITLE
Project status in jobs it's wrong

### ISSUE THREAD

**Issue by chris93111** [ansible/awx#11987]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Hello 

when job fail with project update error , the status of sync project is wrong in UI 

In output job
```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 449, in run
    self.pre_run_hook(self.instance, private_data_dir)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 955, in pre_run_hook
    sync_task.run(local_project_sync.id)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 92, in _wrapped
    return f(self, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 604, in run
    raise AwxTaskError.TaskError(self.instance, rc)
Exception: project_update 443522 (failed) encountered an error (rc=None), please see task stdout for details.
```

In job details ui 
<img width="211" alt="image" src="https://user-images.githubusercontent.com/27526373/161085818-6ecc265c-7ac8-4df4-8ab6-3b708d7dc688.png">

in project ui 
<img width="307" alt="image" src="https://user-images.githubusercontent.com/27526373/161085668-e85bd62d-009e-4276-984c-34305b835a68.png">

### AWX version

20.0.0

### Select the relevant components

- [X] UI
- [x] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.9.9

### Operating system

redhat

### Web browser

Chrome

### Steps to reproduce

launch job with sync project or override branch scm

### Expected results

good status in job details

### Actual results

wrong status

**Comment by fosterseth** [comment]
@chris93111 what happens when you refresh the page, does the status change to failed on the job detail page?

also what does the `/api/v2/project_updates/{id}/` show for that project update? also what does `/api/v2/jobs/{id}/` for the job that was launched show?

**Comment by chris93111** [comment]
Hi @fosterseth, sorry for the response time, the api api/v2/project_updates/451799/ return is good the job is failed 
```
"id": 451799,
    "type": "project_update",
    "url": "[/api/v2/project_updates/451799/](https://XXXX/api/v2/project_updates/451799/)",
    "summary_fields": {
        "organization": {
            "id": 1,
            "name": "Default",
            "description": ""
        },
        "execution_environment": {
            "id": 2,
            "name": "Control Plane Execution Environment",
            "description": "",
            "image": "quay.io/ansible/awx-ee:latest"
        },
        "project": {
            "id": 12,
            "name": "IAC_DEV",
            "description": "",
            "status": "successful",
            "scm_type": "git",
            "allow_override": true
        },
        "credential": {
            "id": 17,
            "name": "ctgit_dev",
            "description": "compte technique git",
            "kind": "scm",
            "cloud": false,
            "kubernetes": false,
            "credential_type_id": 2
        },
        "unified_job_template": {
            "id": 12,
            "name": "IAC_DEV",
            "description": "",
            "unified_job_type": "project_update"
        },
        "instance_group": {
            "id": 6,
            "name": "default",
            "is_container_group": true
        },
        "user_capabilities": {
            "delete": true,
            "start": true
        }
    },
    "created": "2022-04-07T10:25:48.398644Z",
    "modified": "2022-04-07T10:25:48.398666Z",
    "name": "IAC_DEV",
    "description": "",
    "local_path": "_12__iac_dev",
    "scm_type": "git",
    "scm_url": "git@git:Integ/iac.git",
    "scm_branch": "devel",
    "scm_refspec": "",
    "scm_clean": true,
    "scm_track_submodules": false,
    "scm_delete_on_update": false,
    "credential": 17,
    "timeout": 0,
    "scm_revision": "",
    "unified_job_template": 12,
    "launch_type": "sync",
    "status": "failed",
    "execution_environment": 2,
    "failed": true,
    "started": "2022-04-07T10:25:48.398431Z",
    "finished": "2022-04-07T10:25:51.733355Z",
```

and the api api/v2/jobs/451798/

```
    "failed": true,
    "started": "2022-04-07T10:25:48.286733Z",
    "finished": "2022-04-07T10:25:51.755683Z",
    "canceled_on": null,
    "elapsed": 3.469,
    "job_args": "",
    "job_cwd": "",
    "job_env": {},
    "job_explanation": "Previous Task Failed: {\"job_type\": \"project_update\", \"job_name\": \"IAC_DEV\", \"job_id\": \"451799\"}",
```

i thinks the ui return the status of last update project /api/v2/project_updates/451548/
on api/v2/projects/12
```
"default_environment": "[/api/v2/execution_environments/3/](https://XXX/api/v2/execution_environments/3/)",
                "last_update": "[/api/v2/project_updates/451548/](https://XXX/api/v2/project_updates/451548/)"
```

**Comment by lyutian** [comment]
I got the same issue.
My problem is that awx-ee execution environment image is not existing on running instance, and I set 'Never pull image' in AWX GUI.
Suggest checking your execution environment firstly.
- if using instance group, please check `podman image ls` in your instance
- if using container group, please check image in your kubelet cluster.

**Comment by chris93111** [comment]
@lyutian Hi , i not inderstand is not a problem with the EE, the problem is in UI, the display status is wrong

**Comment by hesmithrh** [comment]
@jbradberry and @nixocio can you all verify API and UI sides (or get others to help)

**Comment by djyasin** [comment]
@djyasin  tagging myself in this one- Seems like a great pair programming opportunity!

**Comment by nixocio** [comment]
PR was merged https://github.com/ansible/awx/pull/12348
