### ISSUE TITLE
invalid argument "quay.io/awx/awx_devel:" for "-t, --tag" flag: invalid reference format

### ISSUE THREAD

**Issue by okeyear** [ansible/awx#11986]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

When exec "make docker-compose-build",
Error:  
invalid argument "quay.io/awx/awx_devel:" for "-t, --tag" flag: invalid reference format

### AWX version

20.1.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs

### Installation method

docker on linux

### Modifications

no

### Steps to reproduce

```shell
https://github.com//ansible/awx/archive/refs/tags/${awx_ver}.tar.gz
tar -xf ${awx_ver}.tar.gz
cd awx-${awx_ver}

make docker-compose-build
````

### Expected results

No Error

## Error Message
invalid argument "quay.io/awx/awx_devel:" for "-t, --tag" flag: invalid reference format
the same with:
https://github.com/ansible/awx/issues/10697

## Root Cause
The Root Cause is missing COMPOSE_TAG in Makefile When download the release taball ${awx_ver}.tar.gz .
(When download via git "git clone -b ${awx_ver} https://github.com/ansible/awx.git" , the issue did not happen )

## Trouble Shooting
```shell
https://github.com//ansible/awx/archive/refs/tags/${awx_ver}.tar.gz
tar -xf ${awx_ver}.tar.gz
cd awx-${awx_ver}
````

I found something in Makefile:
```shell
COMPOSE_TAG ?= $(GIT_BRANCH)
GIT_BRANCH ?= $(shell git rev-parse --abbrev-ref HEAD) # when download from tarball, this line can not get GIT_BRANCH 

1. When 
git clone -b ${awx_ver} https://github.com/ansible/awx.git
The Makefile could get the GIT_BRANCH 

2. But when download the release,
tar -xf ${awx_ver}.tar.gz
the Makefile could not get the GIT_BRANCH 
```

**Comment by shanemcd** [comment]
Hello,

What this tells me is that you dont have git installed, or there was some other issue when it tried to run that `git rev-parse` command. 

This issue tracker is for tracking feature enhancements and bugs. If you need help troubleshooting or are looking for help using AWX, try our mailing list or IRC channel:

#ansible-awx on https://libera.chat/
https://groups.google.com/forum/#!forum/awx-project

**Comment by issacmark** [comment]
I think either you did not have git client install or you were in a offline environment. you could try to edit Makefile which in the root dir of awx folder  COMPOSE_TAG ?= $GIT_BRANCH -- > COMPOSE_TAG ?= latest
