### ISSUE TITLE
Filtering hosts by ansible facts doesn't work (anymore)

### ISSUE THREAD

**Issue by anxstj** [ansible/awx#11984]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

The advanced search isn't able to filter on ansible_facts anymore.

With AWX 15 the following URL was working:

```
https://awx.example.com/#/hosts?host_search=page_size:20;order_by:name;host_filter:ansible_facts__ansible_distribution%3DDebian%2520and%2520ansible_facts__ansible_lsb__codename%3Dbullseye
```

I can't produce a similar behavior with AWX 19.2 or AWX 20.1

### AWX version

20.1.0

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs

### Installation method

docker on linux

### Modifications

no

### Ansible version

2.12.2

### Operating system

Debian 11

### Web browser

Firefox

### Steps to reproduce

* Go to Hosts resources and change the search to advanced.
* Then create a new key `ansible_facts__ansible_distribution_release`, choose lookup type `exect` and set `Bullseye` as search key.
* The Search will then return 400: No related model for field ansible_distribution_release.

### Expected results

The hosts listed should match the search.

### Actual results

![grafik](https://user-images.githubusercontent.com/51952982/161043689-462c0348-67aa-4729-be10-5890a76c7bb1.png)

**Comment by nixocio** [comment]
hey @anxstj, thanks for filing this issue. The ansible_facts search was updated.

Can you try selecting `ansible_facts` as key in the dropdown then adding the value that you want to search for in the value? For instance, search below was selected `ansible_facts` and value `ansible_distribution_release="Core"`. 

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/9053044/161062656-9d09f12e-8e96-4911-a575-aa7cc8414b26.png">

**Comment by anxstj** [comment]
Thanks, that works.

But adding two queries doesn't. Example:
`https://awx.example.com/#/hosts?host.host_filter=ansible_facts__ansible_distribution_major_version%3D%2211%22&host.host_filter=ansible_facts__ansible_distribution%3D%22Debian%22`
* key: ansible_facts; value: ansible_distribution_major_version="11"
* key: ansible_facts; value: ansible_distribution="Debian"

This results in:
```
GI@https://awx.example.com/static/js/main.8113eda8.js:2:2151993
oo@https://awx.example.com/static/js/main.8113eda8.js:2:1274195
qo@https://awx.example.com/static/js/main.8113eda8.js:2:1283762
Ks@https://awx.example.com/static/js/main.8113eda8.js:2:1327486
Ol@https://awx.example.com/static/js/main.8113eda8.js:2:1313738
Tl@https://awx.example.com/static/js/main.8113eda8.js:2:1313666
El@https://awx.example.com/static/js/main.8113eda8.js:2:1313527
yl@https://awx.example.com/static/js/main.8113eda8.js:2:1310493
34463/Zi/<@https://awx.example.com/static/js/main.8113eda8.js:2:1259987
36813/t.unstable_runWithPriority@https://awx.example.com/static/js/main.8113eda8.js:2:1486212
Gi@https://awx.example.com/static/js/main.8113eda8.js:2:1259764
Zi@https://awx.example.com/static/js/main.8113eda8.js:2:1259934
Ki@https://awx.example.com/static/js/main.8113eda8.js:2:1259867
Re@https://awx.example.com/static/js/main.8113eda8.js:2:1331034
Jt@https://awx.example.com/static/js/main.8113eda8.js:2:1238487
```

**Comment by nixocio** [comment]
I believe search with multiple operators using ansible_facts is not yet implemented. ~There was an issue related. I will try to link here.~ I could not find a related issue.

**Comment by nixocio** [comment]
Here: https://github.com/ansible/awx/issues/7850
