### ISSUE TITLE
tower_inventory module throwing 'Connection refused' when controller_host not specified

### ISSUE THREAD

**Issue by cjsand** [ansible/awx#11992]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### AWX version

20.0.1

### Select the relevant components

- [ ] UI
- [ ] API
- [X] Docs

### Installation method

docker on linux

### Modifications

yes

### Ansible version

2.12.1

### Operating system

RHEL 8

### Steps to reproduce

User is using `tower_inventory` to add an inventory to their organization using the following snippet:
```yaml
- name: Add tower inventory
  tower_inventory:
    name: "{{dyn_inv}}"
    description: "Dynamic inv"
    organization: "{{organization}}"
    state: present
  register: inv_data
  delegate_to: localhost
```
where `dyn_inv` and `organization` are variables containing the name of the inventory and name of the organization to which it will be added, respectively.

### Expected results

The same snippet above, when run on ansible 2.9.13/tower 3.8.1/python 2.7.5, successfully creates an inventory and returns the inventory's new id:
```json
{
    "_ansible_no_log": false,
    "changed": false,
    "id": 3210,
    "state": "present",
    "inventory": "dyn_inv",
    ...
    },
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }
}
```

### Actual results

When run in ansible-core 2.12.1/AAP 2.1/python 3.8.8, we see the following error:
```json
{
  "msg": "There was an unknown error when trying to connect to https://127.0.0.1/api/v2/organizations/?name=organization: URLError <urlopen error [Errno 111] Connection refused>",
  "exception": "  File \"/tmp/ansible_tower_inventory_payload_g1_tgn39/ansible_tower_inventory_payload.zip/ansible_collections/awx/awx/plugins/module_utils/controller_api.py\", line 484, in make_request\n    response = self.session.open(method, url.geturl(), headers=headers, validate_certs=self.verify_ssl, follow_redirects=True, data=data)\n  File \"/tmp/ansible_tower_inventory_payload_g1_tgn39/ansible_tower_inventory_payload.zip/ansible/module_utils/urls.py\", line 1446, in open\n    return urllib_request.urlopen(request, None, timeout)\n  File \"/usr/lib64/python3.8/urllib/request.py\", line 222, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib64/python3.8/urllib/request.py\", line 525, in open\n    response = self._open(req, data)\n  File \"/usr/lib64/python3.8/urllib/request.py\", line 542, in _open\n    result = self._call_chain(self.handle_open, protocol, protocol +\n  File \"/usr/lib64/python3.8/urllib/request.py\", line 502, in _call_chain\n    result = func(*args)\n  File \"/tmp/ansible_tower_inventory_payload_g1_tgn39/ansible_tower_inventory_payload.zip/ansible/module_utils/urls.py\", line 558, in https_open\n    return self.do_open(\n  File \"/usr/lib64/python3.8/urllib/request.py\", line 1357, in do_open\n    raise URLError(err)\n",
  ...
  "_ansible_no_log": false,
  "changed": false,
  "_ansible_delegated_vars": {
    "ansible_host": "localhost",
    "ansible_port": null,
    "ansible_user": "root",
    "ansible_connection": "local"
  }
}
```

### Additional information

Seems that the issue could be related to the way that AAP 2.1 works, since all jobs run inside execution environments which are podman images, the implicit 127.0.0.1 used in the `tower_inventory` module might not be referring to the tower/controller itself.

**Comment by fosterseth** [comment]
> Seems that the issue could be related to the way that AAP 2.1 works, since all jobs run inside execution environments which are podman images, the implicit 127.0.0.1 used in the tower_inventory module might not be referring to the tower/controller itself.

This is right. controller_host (or the controller_config_file) will need to be explicitly provided in this case https://docs.ansible.com/ansible/latest/collections/awx/awx/inventory_module.html#parameters

**Comment by cjsand** [comment]
Thanks @fosterseth for your response. I will work with the end user to test.
