### ISSUE TITLE
azure_rm inventory should add "ansible_connection: winrm" in host_vars for windows hosts

### ISSUE THREAD

**Issue by themr0c** [ansible/awx#1199]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- Inventory Plugins

##### SUMMARY

azure_rm inventory should add "ansible_connection: winrm" in host_vars for windows hosts

##### ENVIRONMENT
* AWX version: AWX 1.0.2.327 
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: Linux
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Issue initially explained in https://github.com/ansible/ansible/issues/34689

- Given an inventory with sources using Microsoft Azure Resource Manager, including Windows hosts.
- Attempt to run the ansible-tower-samples playbook will fail on windows hosts because it will try to use ssh and not winrm which is the default transport for windows hosts.

##### EXPECTED RESULTS

azure_rm inventory should add "ansible_connection: winrm" in host_vars for windows hosts

##### ACTUAL RESULTS

inventory is using the default transport, ssh, which is unsuitable for windows.

##### ADDITIONAL INFORMATION

Fix proposed in this PR: https://github.com/ansible/ansible/pull/34691

**Comment by themr0c** [comment]
I added  the fix in this PR: https://github.com/ansible/awx/pull/1200/

**Comment by wenottingham** [comment]
See comments on PR - we take these fixes from Ansible.

**Comment by matburt** [comment]
Closing for upstream tracking

**Comment by wenottingham** [comment]
Since upstream landed, opening.

**Comment by wenottingham** [comment]
See https://github.com/ansible/awx/pull/1353
