### ISSUE TITLE
Display message for failed job with no events

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#11994]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Recently we were troubleshooting an issue where a project update would start and then fail but no events were generated (because of how ansible runner was failing). The job event page would should the failed block with no output:
![image](https://user-images.githubusercontent.com/32551173/161309686-2cd59d7d-15f9-4191-9729-a86dfae75aba.png)

It would be nice if we could instead show the user some sort of message indicating that the job never got events. That way they know there was an issue and something is just "not wrong" with the UI.

**Comment by trahman73** [comment]
We can use the PF empty state to show an error... The wording in the mockup below is just an example that can change to better fit the use case.
![image](https://user-images.githubusercontent.com/13351591/174188176-976e86c8-7d45-419b-bab7-b5c7f0e49f42.png)
