### ISSUE TITLE
Add help text popovers to /#/jobs details fields

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#11999]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
<img width="1384" alt="Screen Shot 2022-04-01 at 5 28 30 PM" src="https://user-images.githubusercontent.com/9889020/161343636-673336b7-36fc-4543-9cbb-e5ba599bf8e9.png">

None of the job details fields have help text popovers but I'm sure that many of them _could_.  I realized this when I was looking at https://github.com/ansible/awx/issues/346.  We correctly show the popover text in the adhoc wizard:

<img width="1249" alt="Screen Shot 2022-04-01 at 5 29 59 PM" src="https://user-images.githubusercontent.com/9889020/161343783-6cf6d45a-3fab-4d9b-8ad0-1dbc3ec2a8ef.png">

We should propagate a lot of that same behavior to the job details fields.

Please ensure that the first bullet point of https://github.com/ansible/awx/issues/346 is addressed as part of these fixes.

**Comment by InnocentK** [comment]
Resolved
