### ISSUE TITLE
DNS resolution works randomly

### ISSUE THREAD

**Issue by Jonathan-Caruana** [ansible/awx#12001]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### AWX version

20.1.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

minikube

### Modifications

no

### Ansible version

Provided by the container : 2.12.4rc1.post0

### Operating system

CentOS Stream release 8

### Steps to reproduce

What i have done : 

- Fresh install of CentOS Stream release 8 
- dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
- dnf update
- dnf install docker-ce socat tc git curl conntrack -y
- systemctl enable docker.service && systemctl start docker.service
- curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
- chmod +x kubectl && mv kubectl /usr/bin/
- curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
- chmod +x minikube && mv minikube /usr/bin/
- swapoff -a
- echo “net.bridge.bridge-nf-call-iptables = 1” >> /etc/sysctl.conf && sysctl -p
- minikube start --driver=none
- systemctl enable kubelet.service
- git clone https://github.com/ansible/awx-operator/ && cd awx-operator/
- git describe --tags (return "0.20.0")
- git checkout 0.20.0
- export NAMESPACE=prod
- make deploy
- kubectl config set-context --current --namespace=$NAMESPACE
- created /root/prod.yml : 

```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: prod
spec:
  service_type: nodeport
```
- kubectl apply -f /root/prod.yml

When the installation was done, i did a template that try for example to run "cat /etc/redhat-release" on a group which it contains several servers.

### Expected results

All servers should be reachable

### Actual results

Imagine you have 5 servers in "servergroupC7", if you run for the first time the template the result is : 

server1 : CentOS 7
server2 : CentOS 7
server3 : "Failed to connect to the host via ssh: ssh: Could not resolve hostname server3: Name or service not known"
server4 : "Failed to connect to the host via ssh: ssh: Could not resolve hostname server4: Name or service not known"
server5 : CentOS 7

Ok then you run it again : 

server1 : "Failed to connect to the host via ssh: ssh: Could not resolve hostname server1: Name or service not known"
server2 : CentOS 7
server3 : "Failed to connect to the host via ssh: ssh: Could not resolve hostname server3: Name or service not known"
server4 : CentOS 7
server5 : "Failed to connect to the host via ssh: ssh: Could not resolve hostname server5: Name or service not known"

As you can see, the servers in errors are not the same and if you run the template again, maybe it change again.

### Additional information

I have an old instance of AWX (AWX 9.0.1 with ansible 2.9.1) running directly on the OS (CentOS 7.7) and it doesn't have this behaviour so i think the problem is not related to my DNS servers.

All the servers have been tested and reply correctly on their FQDN or IP.

I have also open an issue on the mailing list in case of someone get the same behaviour but for now i didn't get any answer.

**Comment by Jonathan-Caruana** [comment]
More details in verbose mode : 

{
  "unreachable": true,
  "msg": "Failed to connect to the host via ssh: OpenSSH_8.0p1, OpenSSL 1.1.1k  FIPS 25 Mar 2021\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug3: /etc/ssh/ssh_config line 52: Including file /etc/ssh/ssh_config.d/05-redhat.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/05-redhat.conf\r\ndebug2: checking match for 'final all' host server1 originally server1\r\ndebug3: /etc/ssh/ssh_config.d/05-redhat.conf line 3: not matched 'final'\r\ndebug2: match not found\r\ndebug3: /etc/ssh/ssh_config.d/05-redhat.conf line 5: Including file /etc/crypto-policies/back-ends/openssh.config depth 1 (parse only)\r\ndebug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config\r\ndebug3: gss kex names ok: [gss-curve25519-sha256-,gss-nistp256-sha256-,gss-group14-sha256-,gss-group16-sha512-,gss-gex-sha1-,gss-group14-sha1-]\r\ndebug3: kex names ok: [curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1]\r\ndebug1: configuration requests final Match pass\r\ndebug1: re-parsing configuration\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug3: /etc/ssh/ssh_config line 52: Including file /etc/ssh/ssh_config.d/05-redhat.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/05-redhat.conf\r\ndebug2: checking match for 'final all' host server1 originally server1\r\ndebug3: /etc/ssh/ssh_config.d/05-redhat.conf line 3: matched 'final'\r\ndebug2: match found\r\ndebug3: /etc/ssh/ssh_config.d/05-redhat.conf line 5: Including file /etc/crypto-policies/back-ends/openssh.config depth 1\r\ndebug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config\r\ndebug3: gss kex names ok: [gss-curve25519-sha256-,gss-nistp256-sha256-,gss-group14-sha256-,gss-group16-sha512-,gss-gex-sha1-,gss-group14-sha1-]\r\ndebug3: kex names ok: [curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1]\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/runner/cp/42e26aa8c2\" does not exist\r\ndebug2: resolving \"server1\" port 22\r\nssh: Could not resolve hostname server1: Name or service not known",
  "changed": false
}

**Comment by ForcedHero** [comment]
I am having the same issue

**Comment by Jonathan-Caruana** [comment]
@ForcedHero I will try to install an old version of AWX to see if this behaviour exist or not.

**Comment by Jonathan-Caruana** [comment]
tried with awx-operator 0.15.0 who it deployed AWX 19.5.0 and this issue is still there.

For now, i don't have any clue to how resolv this. I keep trying.

If @shanemcd or maybe @AlanCoding have any ideas :)

**Comment by kurokobo** [comment]
I believe this is not AWX issue but totally your minikube/kubernetes/Docker/OS issue. AWX did nothing special about name resolution.

You should start investigation by digging into the pod and check resolv.conf inside the pod, DNS configuration for your Docker and your host OS.
Refer K8s guide: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

**Comment by Jonathan-Caruana** [comment]
Hi @kurokobo 

The local OS doesn't have any DNS resolution issue and i just followed the instruction to deploy awx app step by step without any modifications.

When in doubt I still tried to debug following the link you provided and nothing appear to be missing or missconfigured.

Regards

**Comment by abeastmal** [comment]
Im having the same issue in kubernetes with awx 24.4.0 

I added a config map that modifies resolv.conf. If I do a ping to any host without the fqdn, in any of the containers, it works just fine
From the task and web pods. And from the EE/runner container, it just works. but in the awx ui, it cannot resolv names. 
If I add the domain to the host manually, it works.

**Comment by arthur-lbchn** [comment]
Guys, anybody found any direct solution for this? I have the same problem with AWX 24.6.1.

**Comment by haifang-zh** [comment]
> Guys, anybody found any direct solution for this? I have the same problem with AWX 24.6.1.

I have the same issue on AWX 24.6.1 with K8s  v1.31.14 and flannel:v0.28.5. everything works fine from UI, but sometime it can't resolve db hostname. but when I test from awx web and task pod the db hostname can be connected.
