### ISSUE TITLE
Smart inventory for ansible_facts is not working as expected

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#12003]
User tried the following searches, following are some searches and their results:
(first, change to Advanced search and key to ansible_facts)

1. Failed: ansible_facts__ansible_product_name=foo
2. Succeeded: ansible_product_name=foo
3. Failed: ansible_product_name=foo bar
4. Failed: ansible_product_name=”foo bar”
5. Failed: ansible_product_name=/”foo bar/’”
6. Failed: ansible_product_name=’foo bar’
7. Failed: ansible_product_name=/’foo bar/’
8. Failed: ansible_product_name=\"foo\" or ansible_facts__ansible_product_name=\"bar\"
9. Failed: ansible_product_name="foo" or ansible_facts__ansible_product_name="bar"
10. Failed: ansible_product_name=foo or ansible_facts__ansible_product_name=bar

Also, user (Jeff Bird) could not create a smart inventory from the API using "or" or spaces in name

**Comment by shanemcd** [comment]
Is this the same as these?

- https://github.com/ansible/awx/issues/371
- https://github.com/ansible/awx/issues/8377

**Comment by akus062381** [comment]
https://github.com/ansible/awx/issues/7850
this issue will address 8-10 in the original issue

1-7 seems to be due to syntax issues or operator error. Closing this issue
