### ISSUE TITLE
Workflow job details shows erroneous fields

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#12008]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

<img width="1673" alt="Screen Shot 2022-04-05 at 1 14 58 PM" src="https://user-images.githubusercontent.com/9889020/161813234-72a8c128-5996-4675-af78-dda234d86dba.png">

In this case, I did not specify a wf level inventory so I would expect that field to empty and not say `Deleted`.  Also, workflows don't have a global project so I don't think we should be showing that field at all.

### AWX version

latest

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

docker for mac

### Modifications

no

### Steps to reproduce

1. Create a WFJT (only supply a name)
2. Launch the WFJT
3. Navigate over to the Details tab on the WF job

### Expected results

Inventory shows empty string or not shown at all
Project field should not be shown

### Actual results

See screenshot in summary

**Comment by nixocio** [comment]
Very similar to https://github.com/ansible/awx/issues/12006
