### ISSUE TITLE
How to delete everything?

### ISSUE THREAD

**Issue by costales** [ansible/awx#12000]
Hi,

I would like to reset AWX to a fresh state (just as it's after installation, only Demo playbooks, etc), for study purposes. Is it possible?

Thanks in advance!

**Comment by muldertbb** [comment]
delete the .pgdocker dir and restart the awx.

**Comment by mabashian** [comment]
You'll probably have better luck with the mailing list or IRC for these types of questions.  Issues are reserved for tracking feature requests, bugs, etc.
