### ISSUE TITLE
Only fetch child summary when job type is job

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#12011]
This issue is a spin off from https://github.com/ansible/awx/pull/11944#pullrequestreview-932128826. 
Due to being so close to code freeze, we decided to make this a separate issue to handle later.

Let's avoid calling this whenever the job.type is not job. The API returns a 404 response from /jobs/:id/job_events/children_summary whenever it is a project_update or system_job job.

![image](https://user-images.githubusercontent.com/63685497/161842776-764d15dd-3b13-4801-97c8-b48bcbeefc9c.png)

**Comment by keithjgrant** [comment]
Looks like Alex is addressing this in https://github.com/ansible/awx/pull/12078
