### ISSUE TITLE
Unable to sync projects

### ISSUE THREAD

**Issue by apiening** [ansible/awx#12025]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After a successful deployment, I can log into the AWX instance.
When I go to **Resources / Projects** and click on `Sync Project` for the `Demo Project` it fails after a while with the message:
**Failed to connect to github.com port 443: Connection timed out**

##### ENVIRONMENT
* AWX version: 20.1.0
* Operator version: 0.20.0
* Kubernetes version: v1.22.7+k3s1
* AWX install method: k3s

##### STEPS TO REPRODUCE

Click on `Sync Project` for the `Demo Project`.

##### EXPECTED RESULTS

The project repository should be synced from github.com.

##### ACTUAL RESULTS

The sync operation times out.

##### ADDITIONAL INFORMATION

I analyzed this issue for quite a while now, because I expected a general network issue to be the reason. However, I can access `github.com` with `curl` or `wget` without any issues when I run the command on the `k3s` node or on the host. But it does not work from within the pod / container.

I've filled an issue with `k3s` and tried a lot of things but I'm still not able to resolve this: https://github.com/k3s-io/k3s/issues/5349

Is it possible that the `awx-operator` does some configuration changes to the `CNI` that may cause this kind of issue?

**Comment by shanemcd** [comment]
Hmm. Maybe a docker networking issue? Not sure which container runtime is used in your k3s setup. I see this sometimes on my local system and fix it by restarting the docker service. FWIW I have not heard any other reports of this lately.

**Comment by apiening** [comment]
This issue was not related to `AWX` and it was solved in a different issue, see: https://github.com/k3s-io/k3s/issues/5349

Summary: The default port range for outgoing connections is `32768 to 60999` and there was a default firewall rule allowing `TCP` packets with the `ACK` flag from within this range.
Since `k3s` uses all possible ports for outgoing connections, some of them were below `32768` and the reply packets was blocked by the firewall.
