### ISSUE TITLE
Jobs fail due to underlying ssh connection problems, yet ssh works fine when tested from CLI

### ISSUE THREAD

**Issue by yoshinori-hardy** [ansible/awx#1202]
##### ISSUE TYPE
 - Bug Report
or 
 - Documentation
not sure if I just missed some config here

##### COMPONENT NAME
 - UI

##### SUMMARY
I've set up a fresh env and I'm attempting to run a job on a host from the inventory.  The job fails with an ssh error.  Investigation suggests to me that awx is attempting to connect as the root user (not the ec2-user configured in the cred).

##### ENVIRONMENT
* AWX version: 1.0.3
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
   Python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
* Operating System: Amazon linux
* Web Browser: chrome

##### STEPS TO REPRODUCE

Clean build following the install guide and then connect to the awx via browser.  Set up 3 credentials aws key/secret, ec2-user ssh key & git key.  

Setup an inventory & source then sync, verify ec2 instances are imported.  Setup a project from git.  Setup a template using the info from the previous steps and attempt to execute the job.  Set the ssh verbosity to debug.

##### EXPECTED RESULTS

Expected the job to complete.  The ssh key imported into the UI has been tested from my laptop and the server hosting the AWX containers.  

##### ACTUAL RESULTS

Job fails with the following:

"msg": "Failed to connect to the host via ssh: OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/tmp/awx_7_Oeu3CV/cp/ec2-**-**-**-**.eu-west-1.compute.amazonaws.com22root\" does not exist\r\ndebug2: resolving \"ec2-**-**-**-**.eu-west-1.compute.amazonaws.com\" port 22\r\ndebug2: ssh_connect_direct: needpriv 0\r\ndebug1: Connecting to ec2-**-**-**-**.eu-west-1.compute.amazonaws.com [**.**.**.**] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: fd 3 clearing O_NONBLOCK\r\ndebug1: Connection established.\r\ndebug3: timeout: 9999 ms remain after connect\r\ndebug1: permanently_set_uid: 0/0\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /root/.ssh…

##### ADDITIONAL INFORMATION

I've tested the ssh key I'm using from the server running the awx containers and the awx_task container itself using:

docker exec -ti  awx_task bash
ssh ec2-user@ec2-**-**-**-**.eu-west-1.compute.amazonaws.com -i ssh_key

this connection works fine.

From the logs it looks like ansible is attempting to use root to login, I've also checked the secure log on the remote host and see this

Feb 12 12:14:22 integration sshd[11773]: ROOT LOGIN REFUSED FROM 10.98.135.52
Feb 12 12:14:22 integration sshd[11773]: ROOT LOGIN REFUSED FROM 10.98.135.52 [preauth]
Feb 12 12:14:22 integration sshd[11773]: Connection closed by 10.98.135.52 [preauth]

I've double checked the USERNAME field in the credential and it's set to ec2-user.

many thanks for your help.

**Comment by wenottingham** [comment]
Please give the api output for the credential, the job template, and the host.... is ansible_user being overridden in host or group vars?

**Comment by yoshinori-hardy** [comment]
hello, please feel free to close this one, I went back over all my work and found that a remote_user var had been set to root in the playbook I was running.  Apologies for the mistake, but hopefully someone might benefit.
