### ISSUE TITLE
new awx cli import command stuck

### ISSUE THREAD

**Issue by jangel97** [ansible/awx#12035]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Hi,

I am trying to use [new cli](https://github.com/ansible/awx/tree/devel/awxkit/awxkit/cli) ,which uses awxkit package, to [import objects](https://docs.ansible.com/ansible-tower/latest/html/towercli/reference.html#awx-import) into Ansible Automation Platform.

When running the import command, the cli gets stuck and runs indefinitely. This is the output:
```
jmorenas-mac:awx-migrate jmorenas$ awx -k --conf.host https://aap --conf.user admin --conf.password passworrd import awx-data.json --verbose
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): aap:443
DEBUG:urllib3.connectionpool:https://aap:443 "GET /api/ HTTP/1.1" 200 186
DEBUG:awxkit.api.client:"GET https://aap/api/" elapsed: 0:00:00.834432
DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.api.ApiV2'> by url: /api/v2/
DEBUG:urllib3.connectionpool:https://aap:443 "GET /api/v2/ HTTP/1.1" 200 1663
DEBUG:awxkit.api.client:"GET https://aap/api/v2/" elapsed: 0:00:00.251457
<< no more output, just gets hanged >>
```
This is how my awx-data.json looks:
```
{
    "credentials": [
        {
            "name": "ansibletower-user",
            "description": "ansibletower SA",
            "inputs": {
                "password": "password",
                "username": "ansibletower",
                "ssh_key_data": "mysshkeydata",
                "become_method": ""
            },
            "organization": {
                "name": "test",
                "type": "organization"
            },
            "credential_type": {
                "name": "Machine",
                "kind": "ssh",
                "type": "credential_type"
            },
            "natural_key": {
                "organization": {
                    "name": "test",
                    "type": "organization"
                },
                "name": "ansibletower-user",
                "credential_type": {
                    "name": "Machine",
                    "kind": "ssh",
                    "type": "credential_type"
                },
                "type": "credential"
            }
        }
    ]
}
```
I have tried with the Ansible module [awx.awx.import](https://docs.ansible.com/ansible/latest/collections/awx/awx/import_module.html#ansible-collections-awx-awx-import-module) and it successfully imports the data into Ansible Automation Platform.

Is there any possible issue in the cli, in the import command? Why the Ansible module works and the cli does not, if they are both relying on the awxkit package.

Btw, this is bare metal installation of AAP 2.1, it is not deployed in any container platform or whatsoever.

Let me know if you need anymore information, thanks in advance!

### AWX version

AAP 2.1

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs

### Installation method

minishift

### Modifications

no

### Ansible version

2.9.27

### Operating system

RHEL

### Steps to reproduce

1. Create the data file:
```
cat <<EOF > awx-data.json
{
    "credentials": [
        {
            "name": "ansibletower-user",
            "description": "ansibletower SA",
            "inputs": {
                "password": "password",
                "username": "ansibletower",
                "ssh_key_data": "mysshkeydata",
                "become_method": ""
            },
            "organization": {
                "name": "test",
                "type": "organization"
            },
            "credential_type": {
                "name": "Machine",
                "kind": "ssh",
                "type": "credential_type"
            },
            "natural_key": {
                "organization": {
                    "name": "test",
                    "type": "organization"
                },
                "name": "ansibletower-user",
                "credential_type": {
                    "name": "Machine",
                    "kind": "ssh",
                    "type": "credential_type"
                },
                "type": "credential"
            }
        }
    ]
}
EOF
```
2. Try to import against an AWX instance (remember to run `awx login`):
```
awx import awx-data.json --verbose
```
3. Supposedly the previous command should hang

### Expected results

I would expect that the dummy credential gets created.

### Actual results

Command hangs.

### Additional information

This is bare metal installation of AAP

**Comment by fosterseth** [comment]
it's intended to be piped in

`cat awx-data.json | awx import -f json`

or

`awx import -f json < awx-data.json`

We need to make this more clear in the cli help text, as it doesn't mention this at all.

**Comment by jbradberry** [comment]
The change to the help output was done in https://github.com/ansible/awx/pull/12049, which has merged.  Closing.
