### ISSUE TITLE
Clean up React Warnings

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#12058]
##### SUMMARY
Clean up React Warnings.

I noticed a couple of react warnings on the dev env.

- [x] Go to https://localhost:3001/#/inventories/inventory/1/sources/add

![image](https://user-images.githubusercontent.com/9053044/163439307-7e0597b0-df92-4ba5-9513-2861bd25d355.png)

![image](https://user-images.githubusercontent.com/9053044/163439489-302ac7fe-79e6-4814-9bbe-5fbe79d5623c.png)

**Comment by kialam** [comment]
The first error should go away once we upgrade React to [v18](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#react). The other warnings should be fixed.

**Comment by AlexSCorey** [comment]
I am going to break this into 2 issues.  1 for the invalid prop type and 1 for React upgrade. Reason: We have to wait for Patternfly to get to react 18 before we can update.
