### ISSUE TITLE
Collection 20.1.0 displays warning claiming 0.0.1-devel

### ISSUE THREAD

**Issue by MallocArray** [ansible/awx#12060]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Upgraded my collection to version 20.1.0 to match AWX 20.1.0 that we are running on Openshift.

When I try to run a playbook to configure this AWX, I get a warning displayed that states
```
[WARNING]: You are running collection version 0.0.1-devel but connecting to AWX version 20.1.0
```
I have a line in my ansible.cfg that uses a path in my git repo for all collections and I verified that MANIFEST.json states `  "version": "20.1.0",`

Tried both ansible 2.10.17.post0 and core 2.12.4.  All running inside of an Execution Environment built by ansible-builder as well as locally installed 2.10

Playbook appears to work as expected. 

Same behavior with Collection 20.0.1, but downgrading to 19.2.2 shows the proper warning:
```
[WARNING]: You are running collection version 19.2.2 but connecting to AWX version 20.1.0
```

### AWX version

20.1.0

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

yes

### Ansible version

2.10.17.post0 and 2.12.4

### Operating system

Redhat

### Web browser

Edge

### Steps to reproduce

Have a playbook that configures some aspect of AWX, such as awx.awx.user:.
AWX running version 20.1.0 and collection version 20.0.1 or 20.1.0

### Expected results

If collection matches AWX version, no warning appears

### Actual results

Warning is present with incorrect version number for the collection:
```
[WARNING]: You are running collection version 0.0.1-devel but connecting to AWX version 20.1.0
```

**Comment by 12csw1** [comment]
Should this issue be labeled as priority:high?

We are doing research about “Issue Priority Prediction". We have developed a tool to automatically label the priority of an issue. The basic idea is to employ Bert model to encode the textual and code descriptions of the issue, and incorporate the issue’s attributes in the model, then apply multi-task learning to facilitate other information boosting the prediction performance. 
 We have conducted experiments on four GitHub projects with 21700 issues, and results show that [79 accuracy]() can be achieved.

Our tool shows that this issue has a very large possibility to be labeled as priority:high 
Could you please tell us whether it should be labeled as priority:high?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by MallocArray** [comment]
@12csw1 
I would not consider this particular issue as priority:high
While the warning message is inaccurate, it still functions as expected,.

**Comment by AlanCoding** [comment]
Confirmed issue.

```
$ grep -r "_COLLECTION_VERSION =" ~/.ansible/collections/ansible_collections/awx/awx/plugins/
/home/alancoding/.ansible/collections/ansible_collections/awx/awx/plugins/module_utils/controller_api.py:    _COLLECTION_VERSION = "0.0.1-devel"

$ ansible-galaxy collection list
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are
modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of code
and can become unstable at any point.

# /home/alancoding/.ansible/collections/ansible_collections
Collection                      Version
------------------------------- -------
awx.awx                         20.1.0 
```

We changed up some release tooling recently, so this is likely fallout from that.

**Comment by ricristian** [comment]
Problem still persists on 21.1.0 installed from ansible galaxy

**Comment by john-westcott-iv** [comment]
This fix unfortunately didn't get merged until after 21.1.0 was released but it should be in the next release. The system auto-closed this issue, I will reopen until we can confirm its working as expected.

**Comment by rgl** [comment]
I'm not sure if this is related, but this warning is not systematic. here are two different runs with two different results:

```console
$ nerdctl run --rm --net mynet -v /vagrant/playbooks:/runner -v /tmp/runner/artifacts:/runner/artifacts -v /etc/tower:/etc/tower:ro -e RUNNER_PLAYBOOK=awx.yml my-awx-ee

PLAY [localhost] ***************************************************************

TASK [Create the My Lab Organization] ******************************************
version 21.1.0
ok: [localhost]
```

```console
$ nerdctl run --rm --net mynet -v /vagrant/playbooks:/runner -v /tmp/runner/artifacts:/runner/artifacts -v /etc/tower:/etc/tower:ro -e RUNNER_PLAYBOOK=awx.yml my-awx-ee

PLAY [localhost] ***************************************************************

TASK [Create the My Lab Organization] ******************************************
[WARNING]: You are running collection version 0.0.1-devel but connecting to AWX
version 21.1.0
ok: [localhost]

```

**Comment by john-westcott-iv** [comment]
@MallocArray This fix should be published in the latest release. Can you test and confirm?

**Comment by john-westcott-iv** [comment]
@rgl, if you are seeing the message inconsistent across runs could you open another issue for that?

**Comment by rgl** [comment]
@john-westcott-iv, with the latest 21.2.0 it no longer shows that message. so I thing its good now. thx!

and the collection version list is also good:

```
    awx: + ansible-galaxy collection list
    awx: 
    awx: # /usr/share/ansible/collections/ansible_collections
    awx: Collection Version
    awx: ---------- -------
    awx: awx.awx    21.2.0
```

**Comment by john-westcott-iv** [comment]
Thanks for the confirmation!

**Comment by MallocArray** [comment]
> @MallocArray This fix should be published in the latest release. Can you test and confirm?

Confirmed as well
