### ISSUE TITLE
Safe upgrade path

### ISSUE THREAD

**Issue by jehutyy** [ansible/awx#12076]
##### ISSUE TYPE
 - Have a clear upgrade path between version
##### SUMMARY
I just came through an upgrade from version 3 to 17, and it was a real pain that actually didn't work in the end.

It could be real great to have a safe upgrade path much like gitlab do (https://docs.gitlab.com/ee/update/#upgrade-paths)  for instance.

**Comment by nixocio** [comment]
Hello, your question seems like a good one to ask on our mailing list at https://groups.google.com/g/awx-project. You can also join #ansible-awx on https://libera.chat/ and ask your question there.
