### ISSUE TITLE
Endless loading of Job log objects. High CPU consumption Chrome

### ISSUE THREAD

**Issue by dyudin0821** [ansible/awx#12080]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

After updating AWX to version 20.0.0 and younger, it is impossible to load Job execution logs (playbook launch)
![image](https://user-images.githubusercontent.com/28118687/164419764-c9af4034-83bf-40b2-a38d-ec408034bcc6.png)

In the developer console in the Google Chrome browser, in the network tab, cyclic requests to receive an event from the AWX API are displayed

![image](https://user-images.githubusercontent.com/28118687/164420204-a898f8d4-bcf8-4ac5-bba5-d5d965fbf74a.png)

This loop causes an increased CPU consumption of my computer

![image](https://user-images.githubusercontent.com/28118687/164421727-71e8667d-b2a9-4046-9604-41548d70c1af.png)

But if I request the AWX API directly, then I can get a detailed event that contains the log for this Job. From this I can conclude that the problem is contained in the Front-End part of the application, the Back-end and the database are working correctly

### AWX version

20.0.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.9.27

### Operating system

Debian 11

### Web browser

Chrome

### Steps to reproduce

1. Run the Job Template for more than 10 steps
2. Wait for the end of the Job execution
3. Go to the Jobs tab, find the Job Template you launched earlier
4. Go to the Output tab
5. Scroll logs to the end of the page
6. Wait for the last event to be displayed

### Expected results

Displaying all logs from Job Template(playbook)

### Actual results

- Endless loading,
- CPU consumption of my computer
- Chrome tab crash

**Comment by kurokobo** [comment]
Already addressed via #11765 and others (see comments and links in the issue), but not released yet. I hope the fix will be shipped with the next release.

**Comment by AlanCoding** [comment]
Thank you for the report, yes, this description sounds to me like what @keithjgrant addressed in a recent merge so I will close this as a duplicate.
