### ISSUE TITLE
Feature: add user to (multiple) teams in Users screen

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1208]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY

Currently, the 'Teams' tab on a User is a read-only list. It should have an 'Add' button and allow you to add a user to one or more teams.

##### ENVIRONMENT
* AWX version: current

**Comment by mabashian** [comment]
<img width="1663" alt="Screen Shot 2021-07-01 at 3 28 18 PM" src="https://user-images.githubusercontent.com/9889020/124179533-fbcb3600-da80-11eb-9774-94f551486803.png">

New UI lets you add a user to multiple teams (as a Member) from the Users -> Teams list

From the Teams -> Access list you can add multiple users with control over the role.

@wenottingham we can close this if the current behavior is sufficient.  If we want to allow for the selection of the role within the team from the Users -> Teams list then we should keep this open.
