### ISSUE TITLE
streaming job stuck with new children

### ISSUE THREAD

**Issue by chris93111** [ansible/awx#12087]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Hello

with the fix https://github.com/ansible/awx/issues/11765, the job output is correct when is finish but in execution, 
the stream stuck and they are no events , refresh the page is needed for recover output in live

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/27526373/164554477-21e5d18f-c8e6-43bb-ad49-03a8903ac590.png">

### AWX version

20.1.X

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.9.9

### Operating system

redhat

### Web browser

Chrome

### Steps to reproduce

launch job and see stream output

### Expected results

output is display in live

### Actual results

stuck

### Additional information

sometime is work but without the follow, is needed to scroll manualy

**Comment by 12csw12** [comment]
Should this issue be labeled as priority:medium?

We are doing research about “Issue Priority Prediction". We have developed a tool to automatically label the priority of an issue. The basic idea is to employ Bert model to encode the textual and code descriptions of the issue, and incorporate the issue’s attributes in the model, then apply multi-task learning to facilitate other information boosting the prediction performance. 
 We have conducted experiments on four GitHub projects with 21700 issues, and results show that 79 accuracy can be achieved.

Our tool shows that this issue has a very large possibility to be labeled as priority:medium 
Could you please tell us whether it should be labeled as priority:medium?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by 12csw13** [comment]
Should this issue be labeled as priority:medium?

We are doing research about “Issue Priority Prediction". We have developed a tool to automatically label the priority of an issue. The basic idea is to employ Bert model to encode the textual and code descriptions of the issue, and incorporate the issue’s attributes in the model, then apply multi-task learning to facilitate other information boosting the prediction performance. 
 We have conducted experiments on four GitHub projects with 21700 issues, and results show that 79 accuracy can be achieved.

Our tool shows that this issue has a very large possibility to be labeled as priority:medium 
Could you please tell us whether it should be labeled as priority:medium?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by keithjgrant** [comment]
Do you have an example playbook to reproduce the issue?

It looks like you're out of follow mode (the blue button near the top). A running job should begin in follow mode, but it will leave follow mode if you click the button or scroll upwards. Is that part of the issue?

**Comment by chris93111** [comment]
Hi @keithjgrant sorry for the time 

yes and no, the stream does not work even if I remain in follow, sometimes the stream work but the follow does not work
I have an example, here where for example there was no stream, but yet the browser has had the information that the job is finished

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/27526373/167265730-f480bd7a-447b-4693-a2a2-e911c44b687f.png">
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/27526373/167266002-6fa20c3d-4243-46c5-9aa1-7e09b0155bb8.png">

**Comment by chris93111** [comment]
@keithjgrant [keithjgrant](https://github.com/keithjgrant) do you have news about this issue ?

**Comment by keithjgrant** [comment]
@chris93111 We fixed a number of job output issues in version 21.0 and 21.2. Are you able to upgrade and see if the problem persists?

**Comment by chris93111** [comment]
fixed
