### ISSUE TITLE
AWX automation job not able to handle our playbook load

### ISSUE THREAD

**Issue by jocamp18** [ansible/awx#12085]
##### SUMMARY
We have a playbook that runs on about 2000 hosts at the same time, once we launch the template it is creating a job **automation-job-id-id**, but after some time, the job finishes with an error because it is not able to handle all of the load. Is it possible to implement HPA with these ephimeral pods? so a new replica is created when it gets some specific load?

##### ENVIRONMENT
* Operator version: 0.14.0
* Kubernetes version: 1.21.0

**Comment by kdelee** [comment]
@jocamp18 this sounds a lot like https://github.com/ansible/awx/issues/12019 to me.

I'd try the workarounds I discuss in that issue using sliced jobs and potentially a custom container group w/ larger resource requests to assign to this job template or the the inventory (that may be better if the JT is run against multiple inventories).

Please feel free to follow up in on that issue and +1 it if you'd like to see that implemented. I'm going to close this as a duplicate.
