### ISSUE TITLE
When configuring LDAP settings Save button never becomes active.

### ISSUE THREAD

**Issue by TemperingPick** [ansible/awx#121]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT

 - UI

##### SUMMARY

When trying to configure LDAP settings the Save button never becomes active preventing me from saving the settings. All boxes are filled out.

##### ENVIRONMENT

* AWX version: 1.0.0
* Ansible version:  2.3.2.0
* Operating System: RHEL7
* Web Browser: Chrome 60.0.3112.113

##### STEPS TO REPRODUCE

Enter information needed to configure LDAP and try to hit Save

##### EXPECTED RESULTS

I should be able to save and use LDAP settings.

##### ACTUAL RESULTS

Save button is greyed out and cannot be clicked.

**Comment by aoyawale** [comment]
hello,

This is currently the same issue reported in https://github.com/ansible/awx/issues/88

**Comment by TemperingPick** [comment]
Clearly my searching skills aren't great.
