### ISSUE TITLE
Merge/disambiguate Insights and Satellite 6 credentials, expose them for playbook usage

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1210]
##### ISSUE TYPE
 - Feature Idea
 - Documentation

##### COMPONENT NAME
 - API

##### SUMMARY

Satellite 6 credentials ('cloud' type) are only exposed as a file (foreman.ini), generally for use by inventory.
Insights credentials ('scm' type) are only exposed for projects, but also can be attached to inventories.

However, ansible modules exist (redhat_subscription, etc) that potentially could use one/both of these credential types.

We should fix this, ideally in a way that:
- allows for exposing them in a way that playbooks can be clearly written that use them
- does not just change both to expose them as the same extra/env vars, in ways that would conflict

##### ENVIRONMENT
* AWX version: any

**Comment by gamuniz** [comment]
closing this as we have moved to using env variables for credentials.
