### ISSUE TITLE
Random roles assigned to users

### ISSUE THREAD

**Issue by zeroone82** [ansible/awx#12109]
### Summary

Seemingly random roles are assigned to users when added in batch as members to a team or organization

### AWX version
20.1.0

### Installation method
kubernetes

### Web browser
Firefox

### Steps to reproduce

- Add a number of users to AWX, not super user, not auditor (I added them using the API, confirmed that there was no roles assigned after creation)
- Go to Team -> Access -> Add
- Select 5 or more users
- Select only "Member" role. Click Save (this can take a while when selecting lots of users)

### Expected results

- The users should only have the "Team (Member)" role assigned
- The team assigned should appear when selecting User -> Teams

### Actual results

- Go to any user and see that they have many roles assigned over different items (jobs, workflows, inventories, credentials, etc)
- Go to any user and see that they have no team assigned (Even though the role Team (Member) is present)

### Additional information

- Same steps and problem applies when adding users to an organization too.
- This seems to be worse when selecting more users, i.e. when selecting 20 users more roles where added than when selecting only 5.
- The roles are consistent across all users added in the same batch, but not the same across different batches.
- There seems to be no issues when adding only 1 user to the team

**Comment by akus062381** [comment]
Jessica and I looked at this and verified it is fixed

**Comment by 06seasparkle** [comment]
Hi 

Is there a schema where I can get the user and their roles on postgresql db?
