### ISSUE TITLE
Intermittent failed admin logins

### ISSUE THREAD

**Issue by DonaldKallman** [ansible/awx#12113]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

We are seeing intermittent failed login attempts for the admin user in the logs.  We do not see these logins going through the ingress and there are no tasks or cron jobs that we are aware of.  This is only happening on AWX and not on our Tower environments.

### AWX version

15.0.0

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

yes

### Ansible version

2.9.13

### Steps to reproduce

None, there is no behavior attributed to this.

### Expected results

N/A

### Actual results

N/A

### Additional information

The failed logins appear to happen in pairs and appear to be coming from within the awx pods themselves, since they are not traversing the nginx ingresses.

**Comment by nixocio** [comment]
Hello, this issue pertains to an older version of AWX. Try upgrading to the latest version and see if that resolves your issue.
