### ISSUE TITLE
Job timeout details not showing in UI

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#12129]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Jobs that failed due to the job timeout set `job_explanation` with details but these are not surfaced in the UI.

### AWX version

devel

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

docker on linux

### Modifications

no

### Ansible version

devel

### Operating system

N/A

### Web browser

Chrome

### Steps to reproduce

Create a job template the runs a sleep playbook, and sleeps for, say, 30 seconds.

Edit that job template to set the timeout to 2 seconds.

Launch that job template and watch.

Click refresh a few times just to be sure.

### Expected results

I see the API message

```json
    "job_explanation": "Job terminated due to timeout",
```

### Actual results

No mention of this in either of the 2 pages.

![Screenshot from 2022-04-28 14-43-50](https://user-images.githubusercontent.com/1385596/165824231-1bae08c8-591e-4c51-995b-46f9c1d9a294.png)
![Screenshot from 2022-04-28 14-42-51](https://user-images.githubusercontent.com/1385596/165824232-e9c655b3-7734-48fb-9352-5a0b6bd23aab.png)

**Comment by Secarius** [comment]
We have the same problem. 
Running the playbook with 5 hosts works, 
but with 30 just stops / freezes and saying error:
![image](https://user-images.githubusercontent.com/777486/167939316-5b60aeb8-9857-4ebc-a9d5-4a59b6d99315.png)
