### ISSUE TITLE
[RFE] [nl] Job Status graph could use 'dd-mm-yyyy' date format (currently uses 'mm/dd')

### ISSUE THREAD

**Issue by sshedmake** [ansible/awx#1213]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

In Dutch (Netherlands) google-chrome, Job Status graph could use 'dd-mm-yyyy' date format, as per [1] and [2]

##### ENVIRONMENT
* AWX version: 1.1.0
* AWX install method: docker on linux
* Ansible version:  2.3.1.0
* Operating System: Fedora 25
* Web Browser: google-chrome

### Steps To Reproduce:

1. In Dutch google-chrome, do a successful login and login into Tower
2. Post login, observe 'date' format on X axis (Time) of Job Status graph

### Expected Results:

dd-mm-yyyy

### Actual Results:

mm/dd

### Additional Information:

[1] https://en.wikipedia.org/wiki/Date_format_by_country 
[2] https://en.wikipedia.org/wiki/Date_and_time_notation_in_the_Netherlands
[3] Screenshot of the Job Status graph currently showing date in 'mm/dd' format on X axis (Time):
![30736608-0d0ec7b6-9fa1-11e7-8a89-67ebcd8eff17](https://user-images.githubusercontent.com/12151785/36148398-e2838092-10e1-11e8-9764-0c50087cc275.png)

**Comment by jaredevantabor** [comment]
If these dates aren't "moment-ized," then they definitely should be.

**Comment by candlerb** [comment]
I installed AWX yesterday (following the docker instructions under Ubuntu 16.04) and access it using with Chrome under macOS, with Chrome set to "English (United Kingdom)" as its preferred language.

I see the job status graph labelled with month name and day, e.g. "Feb 23"

![image](https://user-images.githubusercontent.com/44789/36592420-9b58979e-188d-11e8-9296-e61075a5b5b2.png)

So it's odd that you see numeric MM/DD instead - unless something has changed very recently?

**Comment by wenottingham** [comment]
Works for me:

![screenshot from 2018-06-01 14-12-04](https://user-images.githubusercontent.com/5208768/40856501-180dcf24-65a6-11e8-9905-70560b4931e9.png)
