### ISSUE TITLE
Job API shows you misleading information for execution environment

### ISSUE THREAD

**Issue by howardjones** [ansible/awx#12149]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Looking at a Job in the API, to find out which EE image it was run with, it turns out that the image name in the `summary_fields` section is just a "join" from the _current_ configuration for that EE, not the one used at the time the job was run.

### AWX version

20.1.0

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Ansible version

whatever is in the default awx-ee. The awx about box doesn't say anymore.

### Operating system

centos 8 stream

### Steps to reproduce

Run a job template.
Change the EE definition to point at a new image.
Fetch the Job from the API.
See that the image field shows the new image, not the one you ran with.

### Expected results

An accurate history of the job, or no image name at all.

(or maybe set an enviroment variable with the EE name and image, since those are logged with each job?)

### Actual results

The Job says it was run with an image that didn't exist when it ran.

**Comment by jbradberry** [comment]
This behavior is as intended.  The expectation is that if you need to bring in a new container image for your jobs, you ought to create a new EE entry to encapsulate it.  An EE is supposed to be a one-to-one representation of a particular image and is not really intended to be edited, though of course with sufficient user privileges you can edit it to refer to a completely different image.  As you have seen, though, doing this breaks your historical record of what image was used on jobs that refer to that EE.

Having said all of that, though, the information is not lost.  The `job_args` field on the Job captures the full podman command line used, which includes the image url.
