### ISSUE TITLE
RFE: add edge conflict tooltip to workflow graph

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1215]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY

Workflow graph edge conflicts should have a tool tip or help text displayed when present that instructs the user to go all or nothing success/fail nodes or always nodes. Without it, it's hard to know how to immediately resolve.

##### STEPS TO REPRODUCE

 Create a workflow like:

root -- on success --> node 1 -- always --> node 3
    \-- on success --> node 2

    delete node 1

##### EXPECTED RESULTS

The edge conflict text has a tooltip on hover that tells you to adjust the node connection type

##### ACTUAL RESULTS

No help

**Comment by mabashian** [comment]
Edge conflicts no longer exist, closing
