### ISSUE TITLE
Schedule date picker is not responsive

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#12167]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Schedule date picker is not responsive, I was not able to change months using drowpdown, neither arrows to left/right.

This issue was noticed when reviewing https://github.com/ansible/awx/issues/11978, behavior is also on awx/devel.

### AWX version

devel

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

docker for mac

### Modifications

no

### Steps to reproduce

1 - Attempt to create a schedule - associated with Job Template.
2 - Click on Date Picker 
3 - Attempt to use the dropdown to change the month.
4 - Attempt to use left/right arrow to change the month.

### Expected results

Able to use dropdown to select the month
Able to use arrow left/right to change month

### Actual results

Not able to use dropdown to select the month.
Not able to use arrow left/right to change month

**Comment by kialam** [comment]
Toggling year also does not work for the datepicker.
