### ISSUE TITLE
RFE: link project-based inventory update to inventory source

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1216]
##### ISSUE TYPE
 - Feature Idea - Documentation

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

The inventory update for a project-based source just says 'Sourced from a project' for the source type.

<img width="1439" alt="screen shot 2017-08-11 at 2 38 36 pm" src="https://user-images.githubusercontent.com/9889020/29227214-ff44ccc6-7ea2-11e7-8a3a-5173d6fd885b.png">

It should link to the actual project.

##### ENVIRONMENT
* AWX version: any

**Comment by AlanCoding** [comment]
The current UI now links this

![Screen Shot 2019-04-01 at 8 00 11 AM](https://user-images.githubusercontent.com/1385596/55327366-f3c25d00-5457-11e9-90d5-6b7fffe6ae01.png)

Closing as resolved, FYI @mabashian because there were no UI people linked on this issue before.
