### ISSUE TITLE
AWX isolated node unavailable after provisioning/registration and  dropping after 30 minutes

### ISSUE THREAD

**Issue by rhcalalo** [ansible/awx#12179]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Good day.  I was running  AWX 15.0.1 and I was trying to add an isolated node using the commands below:

# awx-manage provision_instance --hostname <hostname> --is-isolated
# awx-manage register_queue --queuename restricted --hostname <hostname> --controller tower
# awx-manage generate_isolated_key
then add this key to isolated node awx account /home/awx/.ssh/authorized_keys

awx-manage list_instances out will show the isolated node and group but the isolated node was unavailable, it was fixed by manually re-enabling the node in GUI however it dropped again after 30 minutes. I also noticed that isolated node heartbeat is not being check

 Please advise if anyone has encountered the same and how to fix this issue.

 Thanks a lot

### AWX version

15.0.1 

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs

### Installation method

docker on linux

### Modifications

no

### Ansible version

2.9.14

### Steps to reproduce

# awx-manage provision_instance --hostname <hostname> --is-isolated
# awx-manage register_queue --queuename restricted --hostname <hostname> --controller tower
# awx-manage generate_isolated_key
then add this key to isolated node awx account /home/awx/.ssh/authorized_keys

### Expected results

isolated node is available after provisioning/registration

### Actual results

awx-manage list_instances out will show the isolated node and group but the isolated node was unavailable, it was fixed by manually re-enabling the node in GUI however it dropped again after 30 minutes. I also noticed that isolated node heartbeat is not being check

**Comment by rebeccahhh** [comment]
Hello, this issue pertains to an older version of AWX, which we do not support. Try upgrading to the a newer version and see if that resolves your issue.
Also, your question seems like a good one to ask on our mailing list at https://groups.google.com/g/awx-project. You can also join #ansible-awx on https://libera.chat/ and ask your question there.
