### ISSUE TITLE
[Metrics&Observability]  Track (recent/sliding window) event processing lag in metrics

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#12171]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

The amount of time between when events are created in ansible and they get written to the database is a measure of how far behind the callback receiver is. Monitoring this metric can give administrators insight if they need to horizontally scale the control plane to get more event processing power/spread jobs over more control instances (right now we do not dynamically scale the callback receiver workers, there are always 4 per control instance).

I think there are two ways to do this. One is to query the database, relying on the fact that this should now be less atrocious since the events table is now partitioned. The other is to hook into what the subsystem metrics does.

### Option 1: query database

In this case we would add it to the "traditional" metrics  in awx/main/analytics/metrics.py or awx/main/analytics/collectors.py where we currently populate most of the "normal" metrics in we can add a function like:

```
# we need to import this above
from django.db.models import Avg, ExpressionWrapper, DurationField, F

def avg_event_processing_delta(lookback_seconds=60, event_limit=100):
    since = datetime.now() - timedelta(seconds=lookback_seconds)
    avg_delta = (
        JobEvent.objects.annotate(delta=ExpressionWrapper(F('modified') - F('created'), output_field=DurationField()))
        .filter(modified__gte=since)
        .only('modified', 'created')[:event_limit]
        .aggregate(Avg('delta'))
    )
    return avg_delta['delta__avg']
```

### Option 2: hook into subsystem metrics
I'm a bit more hazy on this one. But i think it would look like calculating the average delta/lag in each batch of events like we do with 
https://github.com/ansible/awx/blob/e3fe9010b73e613646be91f1618d4d1806ae1431/awx/main/dispatch/worker/callback.py#L145
which we just increment during this loop where we also actually compute `modified` -- so this would be a great time to just keep a running average of the delta between modified and created.
https://github.com/ansible/awx/blob/e3fe9010b73e613646be91f1618d4d1806ae1431/awx/main/dispatch/worker/callback.py#L149-L155
Right there we could capture the delta between the two.

Then we could bubble it up in the same way we do the other metrics
https://github.com/ansible/awx/blob/e3fe9010b73e613646be91f1618d4d1806ae1431/awx/main/dispatch/worker/callback.py#L179-L188

@fosterseth would be probably be a good resource on figuring out how to fit into this pattern

**Comment by fosterseth** [comment]
Certainly possible for subsystem metrics. We may consider generating a histogram of this data, to better capture the variance of the latency.

**Comment by kdelee** [comment]
for ideas on how to do option # 2 see https://github.com/ansible/awx/pull/12235

**Comment by kdelee** [comment]
closing as this is done
