### ISSUE TITLE
RFE: have API easily denote roles that don't make sense, so the UI can filter them

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1218]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

Example:
- [ ] update on Smart Inventory
- [ ] read on team
(add more here)

**Comment by AlanCoding** [comment]
Was talking to @benthomasson about how this might be used for some networking canvas objects, if they ever have roles added. But it might not make sense in the first development cycle of that.

**Comment by AlanCoding** [comment]
Also, if we get this, I would like to see about adding un-editable roles to certain resources. If we can just get a simplistic `read_role` for inventory sources that inherits from the inventory `read_role`, then we can avoid terrors like https://github.com/ansible/awx/pull/1214/files

**Comment by AlanCoding** [comment]
As of this moment, it still appears that there's only 1 good example where this matters - the update_role for smart/constructed inventory. That just doesn't seem worth it, as we should prioritize other major RBAC presentation issues.
