### ISSUE TITLE
Cant login to AWX

### ISSUE THREAD

**Issue by it-pappa** [ansible/awx#12193]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

When logging into AWX i get: 
GET /api/v2/auth/ 500
A server error has occurred.

After just pressing login many times it will log me in. 

### AWX version

17.1.0

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs

### Installation method

docker on linux

### Modifications

yes

### Ansible version

2.11 (devel)

### Operating system

Ubuntu 20.04

### Web browser

Chrome

### Steps to reproduce

Not sure.
Login? 

### Expected results

No error message and login nicly

### Actual results

Gets error and have to retry many times before i get to login

**Comment by WebSpider** [comment]
Do you have any kind of logging available from the webui or webserver ?

**Comment by it-pappa** [comment]
@WebSpider have not enabled any logging system. 
Only difference in the environment is that i upgraded ansible version. Dont know if that will break anything

**Comment by nixocio** [comment]
Hello, this issue pertains to an older version of AWX. Try upgrading to the latest version and see if that resolves your issue.

**Comment by zooterspin** [comment]
Pretty new to Linux as well as awx! Just trying to setup a lab! AWX version is 21.4.0! I followed the procedure for local docker migration and I can see all containers up and running but cant login to the UI! 
I am not sure what is the username and password, when I tried to use the one I had for version 17.1.0 it fails.
tools_awx_1     | 10.65.22.37 GET / - HTTP/1.1 200
tools_awx_1     | 10.65.22.37 GET /api/ - HTTP/1.1 200
tools_awx_1     | 10.65.22.37 GET /api/ - HTTP/1.1 200
tools_awx_1     | 10.65.22.37 GET /api/v2/auth/ - HTTP/1.1 200
tools_awx_1     | 10.65.22.37 GET /api/login/ - HTTP/1.1 200
tools_awx_1     | 2022-08-19 07:44:51,938 WARNING  [84e55a59] awx.api.generics Login failed for user awx from 10.65.22.37
tools_awx_1     | 2022-08-19 07:44:51,947 WARNING  [84e55a59] django.request Unauthorized: /api/login/
tools_awx_1     | 2022-08-19 07:44:51,947 WARNING  [84e55a59] django.request Unauthorized: /api/login/
