### ISSUE TITLE
patching credential on the workflow level

### ISSUE THREAD

**Issue by kTipSSIoYv** [ansible/awx#12192]
##### ISSUE TYPE
 - We have a requirement to patch and allow credentials in the workflow level.. We are using AWX to integrate with ManageIQ and we want to pass the credentials to workflow through ManageIQ. We can successfully pass credentials to `Job Template` through ManageIQ but not Workflow. We enable `Prompt on Launch` and then pass the creds through ManageIQ
  
 This has been requested [here ](https://github.com/ansible/awx/issues/7859)as well
 
I'm trying to find out if I can create a patch and PR request for this and build the custom docker image. I'd like to know what all components needs to patch in order for this to work.

I've patched the UI but I guess I may need to modify the schema or something to accept credentials. Can someone suggest what all components needs to be modified?

![image](https://user-images.githubusercontent.com/9666915/167358852-8b11c37d-6575-4f56-ae35-f987ee5cdb5f.png)

Things to do:

- The selection in the above screenshot doesn't work. The selection needs to work.
- During the Workflow Visualizer `Add Node`, the selected credentials needs be picked up from the Workflow selection (above screenshot).

**Comment by nixocio** [comment]
Hello, your question seems like a good one to ask on our mailing list at https://groups.google.com/g/awx-project. You can also join #ansible-awx on https://libera.chat/ and ask your question there.
