### ISSUE TITLE
Wrong paging on UI

### ISSUE THREAD

**Issue by sooslaca** [ansible/awx#12195]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Check a big enough job out at `/#/jobs/playbook/XXXX/output`
Start scrolling down slowly.
URLs in order
```
job_events/?order_by=counter&page=1&page_size=50
job_events/?order_by=counter&page=2&page_size=50
job_events/?order_by=counter&page=3&page_size=50
job_events/?order_by=counter&page=4&page_size=50
job_events/?order_by=counter&page=5&page_size=50
job_events/?order_by=counter&page=7&page_size=41
```
Last one is off with page number and page_size also shrinked.

If I do the same on API browser (open first job_events link) and use the buttons this is the last URL I end (which is the expected):
```
/job_events/?order_by=counter&page=6&page_size=50
```

### AWX version

AWX 21.0.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Ansible version

awx-ee:latest

### Operating system

linux

### Web browser

Chrome

### Steps to reproduce

Check a big enough job out at `/#/jobs/playbook/XXXX/output`
Start scrolling down slowly.
URLs in order
```
job_events/?order_by=counter&page=1&page_size=50
job_events/?order_by=counter&page=2&page_size=50
job_events/?order_by=counter&page=3&page_size=50
job_events/?order_by=counter&page=4&page_size=50
job_events/?order_by=counter&page=5&page_size=50
job_events/?order_by=counter&page=7&page_size=41
```
Last one is off with page number and page_size also shrinked.

If I do the same on API browser (open first job_events link) and use the buttons this is the last URL I end (which is the expected):
```
/job_events/?order_by=counter&page=6&page_size=50
```

### Expected results

Increased `page` number by one after each scroll. Exactly the same `page_size` all the time.

### Actual results

Last page load is off with `page` and `page_size` number

**Comment by keithjgrant** [comment]
That page calculates which data it needs to load based on the total number of records and how much it needs to display as you scroll. It's not expected to only use page size 50. The requests you're seeing should still fetch all necessary events:

```
job_events/?order_by=counter&page=1&page_size=50 // events 1–50
job_events/?order_by=counter&page=2&page_size=50 // events 51–100
job_events/?order_by=counter&page=3&page_size=50 // events 101–150
job_events/?order_by=counter&page=4&page_size=50 // events 151–200
job_events/?order_by=counter&page=5&page_size=50 // events 201–250
job_events/?order_by=counter&page=7&page_size=41 // events 247–287
```

As long as the job doesn't have any events beyond number 287 (or you haven't scrolled far enough down to need them), this should be fine.

This perhaps seems a little silly in this particular instance, but it allows the page to load a small number of events when it only needs a few. It's also helpful when you jump down rapidly and need, e.g. events 347 on. Instead of loading events 301–350 and 351–400 in two requests, it can get what it needs in one.

**Comment by keithjgrant** [comment]
If you have queries that are skipping an event that the UI is trying to display please let me know! But it sounds like this is working as intended, so I'm going to close
