### ISSUE TITLE
Remove already-deprecated `update_on_project_update` field

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#12206]
##### ISSUE TYPE
 - Feature Idea

(feature removal?)

##### SUMMARY
This field was deprecated in https://github.com/ansible/awx/pull/11989

See the comment chain here:

https://github.com/ansible/awx/issues/11336#issuecomment-970321742

This is filing that as a separate issue. We now have https://github.com/ansible/awx/pull/12073, which resolves what was discussed in https://github.com/ansible/awx/issues/11336 and more. We will want to encourage people to use this new, simpler, system.

To do that, we should add a migration which deletes the old field `update_on_project_update`.

How do we do that without breaking functionality? I would argue for the following migration script:

 - Loop over all inventory sources with `update_on_project_update=True`
 - Change the inventory source `update_on_launch` to `True`
 - For every one of those, check related `source_project`
 - If that project has `update_on_launch=False`, change its value to `True`

As users continue to make use of AWX, this will result in more timely inventory updates.

Only downside is that it may run _more updates_ than what the user wants. I find this to be a minor inconvenience, and is a trade-off that we should be willing to make.

**Comment by fosterseth** [comment]
also we can safely remove the scm_last_revision field on the inventory source model

**Comment by john-westcott-iv** [comment]
Blocked pending merge of #12073

**Comment by AlanCoding** [comment]
@fosterseth I saw this was marked as in-progress, are you working on it?

**Comment by hesmithrh** [comment]
@fosterseth can we close this since we are tracking the docs work in https://github.com/ansible/product-docs/issues/1722 (linked above) thanks!

**Comment by hesmithrh** [comment]
@fosterseth can we close this since we have a separate docs issue? thanks
