### ISSUE TITLE
workflow job with deleted nodes produces error on launch

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#12203]
If a user tries to launch a workflow job template that contains nodes that have all been deleted, the user gets an error when they try to launch it.

Steps to reproduce:

1. As an admin user, create 3 job templates.
2. Create a workflow job template. 
3. In the visualizer, add the three job templates as nodes.
4. Save the visualizer and launch the job. No problems..... 
5. Now, delete the 3 job templates (but not the workflow job template). 
6. Launch the workflow job template. You will see:

![image](https://user-images.githubusercontent.com/63685497/167687516-e43d77b2-2f3a-40b8-b7e6-5ea7b044ca3e.png)

This may also warrant some UX improvements for user.

Suggested possible results for user:

1. User receives a pop up showing that the nodes on the WFJT have been deleted, and therefore the job cannot run. 
2. The launch button is disabled and a help text appears to tell the user why it has been disabled.

**Comment by kialam** [comment]
I followed the steps to reproduce and no longer see this error message. It now takes me to the output screen where it displays a `failed` job status for the workflow.
![Screen Shot 2022-06-21 at 9 41 55 AM](https://user-images.githubusercontent.com/2293210/174853444-ce096890-d49b-4cb8-a28b-6781970af37d.png)

Closing, but feel free to reopen if this is still an issue.
