### ISSUE TITLE
Fix handling of isolated jobs when controller dies

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1222]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY

If a controller node dies for an isolated job, we lose track of the job. Currently, we mark it as failed.

However, we likely do have enough information on the job to resume monitoring from another node in the controller group. We just don't do it yet.

##### ENVIRONMENT
* AWX version: current

**Comment by shanemcd** [comment]
RIP isolated nodes.
