### ISSUE TITLE
UI does not show API message about why job is blocked

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#12231]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

The API will give a message for why a job is stuck in "pending"

This information is not surfaced in the UI

### AWX version

21.0.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

docker on linux

### Modifications

no

### Ansible version

devel

### Operating system

N/A

### Web browser

Chrome

### Steps to reproduce

Do this

 - Create a job template that has `allow_simultaneous` at the default value of `False`
 - Launch 65 versions of this job template
 - View one of the jobs that is not actively running

### Expected results

The API gives a message about why the job is not running

![Screenshot from 2022-05-13 10-33-20](https://user-images.githubusercontent.com/1385596/168306918-f481ebb3-983d-4246-a522-424dde9ad7bc.png)

I expect the UI to show this message.

### Actual results

UI does not show that message

![Screenshot from 2022-05-13 10-33-43](https://user-images.githubusercontent.com/1385596/168306916-69bdc631-0ae0-48cc-9789-c235b98dd9ff.png)
![Screenshot from 2022-05-13 10-33-32](https://user-images.githubusercontent.com/1385596/168306917-fcfa7fa0-ce3e-4604-970a-705b1b3c89de.png)

**Comment by fosterseth** [comment]
my main concern is whether job_explanation is properly translated

**Comment by keithjgrant** [comment]
This was (semi-inadvertently) removed from the UI here: https://github.com/ansible/awx/pull/11561/files#diff-b507feef6ba5a06df4a81180696761facbeda09f24b57d2389327009878b82f3L124

**Comment by hesmithrh** [comment]
@nixocio will look at this, we may have fixed it

**Comment by nixocio** [comment]
This issue was solved by https://github.com/ansible/awx/pull/12247
