### ISSUE TITLE
Log output doesn't follow browser

### ISSUE THREAD

**Issue by ybucci** [ansible/awx#12232]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

The browser does not follow the log, it is necessary to keep clicking the buttons to go down and when select Follow button or arrows don't work

AWX version: 21.0.0
Operator version: 0.21.0
Kubernetes version: 1.21.10
AWX install method: Kubernetes

##### STEPS TO REPRODUCE

Run job

Which browser window follows the log output

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/52977138/168079911-d407a698-407f-4eaf-9424-9d07080dc182.png)

**Comment by PaulVerhoeven1** [comment]
I think this is more a bug for awx self (https://github.com/ansible/awx/issues) and not the operator.

**Comment by chris93111** [comment]
same here https://github.com/ansible/awx/issues/12087

**Comment by matsonfruit** [comment]
I am also having this issue. has anyone found a fix or workaround?

**Comment by AaronJaegerVA** [comment]
I am experiencing this as well.

**Comment by anxstj** [comment]
I have the same issue, but additionally, the log doesn't update at all if the job runs on another execution node other than the controller node. In that case, I have to switch between the "output" and "details" tabs to see updates (opening the "output" tab causes a reload of the output).

AWX Version: 21.1.0
Install method: local docker

**Comment by AaronJaegerVA** [comment]
> I have the same issue, but additionally, the log doesn't update at all if the job runs on another execution node other than the controller node. In that case, I have to switch between the "output" and "details" tabs to see updates (opening the "output" tab causes a reload of the output).
> 
> AWX Version: 21.1.0 Install method: local docker

I also see this behavior.

**Comment by keithjgrant** [comment]
@anxstj @AaronJaegerVA Thanks for the report! I created an issue to track that problem at https://github.com/ansible/awx/issues/12539

**Comment by keithjgrant** [comment]
I'm having trouble reproducing this (though I'm fairly certain I've seen it in the past). Is this only happening for certain jobs or under heavy load? Does the problem persist in the most recent version of AWX?

**Comment by keithjgrant** [comment]
okay, this seems to occur if you navigate to the job output _after_ the job has begun, and not as often (if at all) when you navigate to the output page before the job begins

**Comment by shatteredsword** [comment]
I'm not sure if the bug I'm encountering even falls under the same scope as this, but for me, as long as I stay on the output page, the job output never appears, and the elapsed time never changes.

**Comment by keithjgrant** [comment]
@shatteredsword That sounds like your page isn't receiving websocket events at all. You might want to check out #12539 and #11346

Also, the elapsed time not updating is another known issue: #11555

**Comment by InnocentK** [comment]
Resolved
