### ISSUE TITLE
Credentials selection doesn't remove the existing credentials

### ISSUE THREAD

**Issue by kTipSSIoYv** [ansible/awx#12236]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

I'm trying to implement and add credentials to workflow job template. 

I've successfully added the Multicredentials lookup to the UI but during the selection process it doesn't remove the first credentials.  The credentials type is same but it doesn't remove. Any idea what the issue might be in the code that I need to check? 

`Zabbix` credential need to get removed when when `test` credentials is selected but it appends to the first credential.

![image](https://user-images.githubusercontent.com/9666915/168439466-26c9c609-4396-4f37-aef9-ec0572dcbd05.png)

![image](https://user-images.githubusercontent.com/9666915/168439433-0d93d275-db45-4ef0-865c-c10468eec041.png)

 

### AWX version

17.1.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

docker on linux

### Modifications

yes

### Ansible version

2.9.23

### Operating system

amazon linux

### Web browser

Chrome

### Steps to reproduce

nil

### Expected results

nil

### Actual results

Credentials is getting appended instead of getting removed.

**Comment by AlexSCorey** [comment]
Hello, this issue pertains to an older version of AWX. Try upgrading to the latest version and let us know if that resolves your issue.
