### ISSUE TITLE
Pagination widget cramped when > 1000 items

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1224]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

<img width="889" alt="screen shot 2017-09-13 at 2 31 56 pm" src="https://user-images.githubusercontent.com/5964417/30394279-a6a6f37a-9890-11e7-82bf-646b3caf76fb.png">

##### ENVIRONMENT
* AWX version: current

**Comment by ryanpetrello** [comment]
Closing due to age and UI rewrite.
