### ISSUE TITLE
Can not use token for gitlab or github

### ISSUE THREAD

**Issue by amg-web** [ansible/awx#12267]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Can not use token for gitlab or github
they do not appear in a credentials list,
only ssh token listed.

### AWX version

21.0.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

minikube

### Modifications

no

### Operating system

Ubuntu 22.04

### Web browser

Chrome

### Steps to reproduce

Create gitlab or github token in a **Credentials section**

go to project setting and try to assign token access for **Source Control Type: Git**
only ssh type is listed there.
![Screenshot from 2022-05-23 13-09-53](https://user-images.githubusercontent.com/22151881/169798752-354616a4-6cff-4891-a99c-dc2d6a12f901.png)
![Screenshot from 2022-05-23 13-10-58](https://user-images.githubusercontent.com/22151881/169799302-e1bd16c8-3a84-42e7-bc73-e78593e2cca6.png)

### Expected results

expected to have token credentials for projects with **Source Control Type: Git**
![Screenshot from 2022-05-23 13-11-04](https://user-images.githubusercontent.com/22151881/169798887-ea5ece3d-dfac-48d7-967d-2784e2a39e08.png)

### Actual results

only ssh type is listed in available credentials list.

**Comment by AlexSCorey** [comment]
@amg-web   Thanks for reaching out to us.  To use github and gitlab credentials you need to set them up at Credential Type: Source Control.  

Should you need more assistance please see https://github.com/ansible/awx/#get-involved for information for ways to connect with us.

**Comment by amg-web** [comment]
@AlexSCorey 
so where can I put token here ?
![image_2022-06-24_183626099](https://user-images.githubusercontent.com/22151881/175569194-6daa606d-6631-4ee2-be98-40a06c008807.png)

**Comment by kovacs-andras** [comment]
With GitLab the token equals to the password and use one of the following usernames:
- oauth2
- gitlab-ci-token

But I would consider to use a deploy token which can have a custom username too.
https://docs.gitlab.com/ee/user/project/deploy_tokens/index.html
