### ISSUE TITLE
"Cleanup Fact Details" doesn't

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1226]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY

The 'cleanup facts' management job cleans up old system tracking facts... which is not something AWX even collects.

It should be updated to purge the fact cache.

##### ENVIRONMENT
* AWX version: current

##### STEPS TO REPRODUCE

run 'cleanup facts' with any timeframe

##### EXPECTED RESULTS

Facts are cleaned up.

##### ACTUAL RESULTS

Nothing.

**Comment by ryanpetrello** [comment]
Fixed in 1.0.7.
