### ISSUE TITLE
Critical - Inventory update blocks AWX

### ISSUE THREAD

**Issue by Tioborto** [ansible/awx#12277]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

When we launch an update of an inventory source, after a while, our AWX instance is totally blocked. 
In other words, it is no longer possible to launch any job

Groups: 166
Hosts: 8614
Options: Overwrite enable

```
ansible-inventory 2.9.27.post0
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.12 (default, Sep 21 2021, 00:10:52) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
No config file found; using defaults
setting up inventory plugins
host_list declined parsing /runner/project/inventory.py as it did not pass its verify_file() method
Parsed /runner/project/inventory.py inventory source with script plugin

   30.068 INFO     Processing JSON output...
   30.069 DEBUG    Loaded group: all
   30.069 DEBUG    Loaded group: subgroup
   30.070 DEBUG    Adding child group subgroup parent all
   ...
   37.861 DEBUG    Adding child group subgroup2 to parent all
   37.867 INFO     Loaded 166 groups, 8614 hosts
   217.170 DEBUG    Deleted host "h1"
   383.312 DEBUG    Deleted host "h2"
   537.445 DEBUG    Deleted host "h3"
   715.064 DEBUG    Deleted host "h4"
   886.845 DEBUG    Deleted host "h5"
  1059.130 DEBUG    Deleted host "h6"
```

Everything goes well when adding hosts (7 seconds for all hosts) but when deleting hosts that no longer exist, it takes a long time (around 150 seconds per host)

### AWX version

21.0.0

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.9

### Operating system

k8s v1.21.10

### Web browser

Safari

### Steps to reproduce

Source a large number of hosts in inventory with variables

### Expected results

All works fine :

### Actual results

AWX blocked

**Comment by Tioborto** [comment]
More informations from database about lock
![Screenshot 2022-05-25 at 10 55 54](https://user-images.githubusercontent.com/29703972/170223986-50bc3199-a0c5-4b13-b80f-52b7f7b5734e.png)

**Comment by Tioborto** [comment]
@AlanCoding  or @keithjgrant, maybe, do you have any idea ? please

**Comment by AlanCoding** [comment]
It's known behavior that deleting hosts can take a long time (or even [error](https://github.com/ansible/awx/issues/12176)) due to the related job host summaries, as well as related events. The host summaries give the status of a host at the end of a playbook (think failed/successful/ok counts), and events link task results inside of a playbook to the host. However, 150 seconds per host is truly exceptional. Could you obtain the number of jobs that have ran against that inventory? You might be able to click around the API to find this, like `/api/v2/jobs/?inventory=<id>`. Then, for a representative job, what number of events does it produce, and how many of those ~8,000 hosts does it target? Roughly how many distinct hours have jobs ran against this inventory, and how long have the hosts persisted before getting deleted by the import?

I'm very interested to put together a reproducer, I ask these questions because with the number of hosts you have, it does suggest that this is scale-dependent, even if it's a bug triggered by a race condition or something like that.

When you say it's not possible to launch a job, what specifically happens? Does the status of those job remain as "pending"?

**Comment by Tioborto** [comment]
Hello @AlanCoding , 
Already a big thank you for responding to this issue.

When I go to see the number of events for this inventory, on the endpoint you provide, it is `17822`.
For this inventory, each job is day on about 7000 hosts. For information, it is about updating the configuration of network equipment, so we are constantly moving.

Indeed, during this blocking, each new job arriving is blocked in pending.
You can see on the associated screenshot the pending and running curves (only 1 automation pod running) during a block.
You can also observe that the CPU of the awx-task and awx-ee containers are stopped or almost stopped.

![pending-running](https://user-images.githubusercontent.com/29703972/171831707-311f543c-7b69-4f2c-95a6-dd07159d4c61.png)
![task-ee-cpu](https://user-images.githubusercontent.com/29703972/171831713-9c9bf5f7-2b77-4e9c-b5c0-acf568a7c719.png)

**Comment by AlanCoding** [comment]
To clarify by rewording, there were 17822 jobs ran against that inventory? That is a lot, and with the volume you're working with it may not be as surprising as I had thought to see such long deletion times.

We have been giving additional consideration to https://github.com/ansible/awx/issues/10337 lately, because there is pretty good confidence that it would address several reports related to inventory deletion sluggishness.

Could you look at `/api/v2/jobs/<id>/job_events/` and give a ballpark representative count of events produced by a single one of your jobs? This would clarify the relative ratio of job host summary entries relative to job events for a host.

**Comment by Tioborto** [comment]
Hello @AlanCoding , 
Sure, we have for this inventory, around 18000 jobs. We provide AWX for our customer and we don't have any idea they use our instance (like a SaaS).

On job_events API endpoint, for a single job, we have around 230 job events. 

Have you a workaround to help us to help our customer to continue to use InventoryUpdate (using external source) ?

**Comment by Tioborto** [comment]
I launched the same command like you and I found another number 

```shell
>>> inv = Inventory.objects.filter(id=1107).first()
>>> h = inv.hosts.first()
>>> h.job_events_as_primary_host.count()
588
```

I don't understand how I can read this result

**Comment by mick1627** [comment]
Same issue for me.
Removing a inventory source with about 200 hundreds of hosts and 8220 jobs ran against that inventory ends with AWX unreacheable after about 1 hours.

The following sql request seems to just overload our postgres DB :


```sql
SELECT pid, age(clock_timestamp(), query_start), usename, query 
FROM pg_stat_activity 
WHERE query != '<IDLE>' AND query NOT ILIKE '%pg_stat_activity%' 
ORDER BY query_start desc;
 
 
 
 26687 | 00:46:19.583359 | awx      | UPDATE "main_jobhostsummary" SET "host_id" = NULL WHERE "main_jobhostsummary"."id" IN (SELECT U0."id" FROM "main_jobhostsummary" U0 INNER JOIN "main_host" U1 ON (U0."host_id" = U1."id") INNER JOIN "main_host_inventory_sources" U2 ON (U1."id" = U2."host_id") WHERE U2."inventorysource_id" = 713)
 23146 | 00:49:31.351395 | awx      | SELECT "main_jobevent"."id", "main_jobevent"."event", "main_jobevent"."event_data", "main_jobevent"."failed", "main_jobevent"."changed", "main_jobevent"."uuid", "main_jobevent"."playbook", "main_jobevent"."play", "main_jobevent"."role", "main_jobevent"."task", "main_jobevent"."counter", "main_jobevent"."stdout", "main_jobevent"."verbosity
", "main_jobevent"."start_line", "main_jobevent"."end_line", "main_jobevent"."created", "main_jobevent"."modified", "main_jobevent"."job_id", "main_jobevent"."host_id", "main_jobevent"."host_name", "main_jobevent"."parent_uuid", "main_jobevent"."job_created" FROM "main_jobevent" WHERE "main_jobevent"."host_id" IN (25917, 25144, 25922, 21346, 15405, 2885, 14072, 24525, 21632,
25918, 20183, 25921, 21520, 2451, 25919, 25667, 25589, 23737, 22794, 23729, 2452, 2537, 2545, 2450, 2508, 2414, 25588, 25205, 25542, 25207, 20416, 22074, 21306, 22768, 2501, 23289, 14090, 12757, 22687, 15352, 23288, 21238, 14074, 12755, 12753, 1926, 3288, 22686, 19387, 12654, 21298, 21631, 14075, 2651, 25920, 25923, 25540, 21253, 21345, 13726, 12756, 23334, 21932, 14124, 2886
, 20184, 14077, 21256, 21759, 14118, 25666, 3291, 13508, 13504, 21344, 21259, 22073, 2884, 22629, 2825, 2544, 19499, 24521, 12653, 25271, 19712, 2152, 25272, 25539, 15413, 13597, 24538, 2543, 22462, 2536, 21257, 19386, 3289, 2546, 13598, 21784, 21827, 25204, 21826, 15414, 22142, 14073, 20287, 20316, 20277, 25541, 21785, 2482, 22010, 21712, 12697, 21885, 20288, 3286, 22689, 25
206, 21910, 21299, 24524, 24522, 14273, 23706, 13503, 22461, 19388, 14076, 13725, 20618, 22126, 22127, 21884, 22217, 2549, 22502, 22501, 14070, 13509, 3290, 21258, 21529, 15402, 13506, 22688, 22216, 3287, 15412, 21497, 19391, 14123, 21347, 15404, 12817, 22116, 2339, 2415, 2506, 21255, 15411, 14071, 21545, 2548, 25270, 21968, 22194, 2416, 20417, 19390, 19389, 19392, 13600, 192
7, 13602, 2502, 24542, 25077, 12759, 14825, 24526, 2535, 24541, 24543, 2507, 24540, 25076, 2533, 13505, 2629, 13601, 21530, 13599, 15294, 2650, 24917, 13507, 25273, 22072, 13510, 20617, 21688, 2481, 2480, 12696, 19393, 22767, 15403, 21496, 12760, 12758, 14078, 21305, 21300, 21288, 23158, 2135, 19500, 19365, 22466, 14186, 22011, 2199, 2150, 21713, 2538, 2449, 2503, 2151, 13724
, 14120, 2547) ORDER BY "main_jobevent"."id" ASC
 23145 | 00:49:31.351397 | awx      | SELECT "main_jobevent"."id", "main_jobevent"."event", "main_jobevent"."event_data", "main_jobevent"."failed", "main_jobevent"."changed", "main_jobevent"."uuid", "main_jobevent"."playbook", "main_jobevent"."play", "main_jobevent"."role", "main_jobevent"."task", "main_jobevent"."counter", "main_jobevent"."stdout", "main_jobevent"."verbosity
", "main_jobevent"."start_line", "main_jobevent"."end_line", "main_jobevent"."created", "main_jobevent"."modified", "main_jobevent"."job_id", "main_jobevent"."host_id", "main_jobevent"."host_name", "main_jobevent"."parent_uuid", "main_jobevent"."job_created" FROM "main_jobevent" WHERE "main_jobevent"."host_id" IN (25917, 25144, 25922, 21346, 15405, 2885, 14072, 24525, 21632,
25918, 20183, 25921, 21520, 2451, 25919, 25667, 25589, 23737, 22794, 23729, 2452, 2537, 2545, 2450, 2508, 2414, 25588, 25205, 25542, 25207, 20416, 22074, 21306, 22768, 2501, 23289, 14090, 12757, 22687, 15352, 23288, 21238, 14074, 12755, 12753, 1926, 3288, 22686, 19387, 12654, 21298, 21631, 14075, 2651, 25920, 25923, 25540, 21253, 21345, 13726, 12756, 23334, 21932, 14124, 2886
, 20184, 14077, 21256, 21759, 14118, 25666, 3291, 13508, 13504, 21344, 21259, 22073, 2884, 22629, 2825, 2544, 19499, 24521, 12653, 25271, 19712, 2152, 25272, 25539, 15413, 13597, 24538, 2543, 22462, 2536, 21257, 19386, 3289, 2546, 13598, 21784, 21827, 25204, 21826, 15414, 22142, 14073, 20287, 20316, 20277, 25541, 21785, 2482, 22010, 21712, 12697, 21885, 20288, 3286, 22689, 25
206, 21910, 21299, 24524, 24522, 14273, 23706, 13503, 22461, 19388, 14076, 13725, 20618, 22126, 22127, 21884, 22217, 2549, 22502, 22501, 14070, 13509, 3290, 21258, 21529, 15402, 13506, 22688, 22216, 3287, 15412, 21497, 19391, 14123, 21347, 15404, 12817, 22116, 2339, 2415, 2506, 21255, 15411, 14071, 21545, 2548, 25270, 21968, 22194, 2416, 20417, 19390, 19389, 19392, 13600, 192
7, 13602, 2502, 24542, 25077, 12759, 14825, 24526, 2535, 24541, 24543, 2507, 24540, 25076, 2533, 13505, 2629, 13601, 21530, 13599, 15294, 2650, 24917, 13507, 25273, 22072, 13510, 20617, 21688, 2481, 2480, 12696, 19393, 22767, 15403, 21496, 12760, 12758, 14078, 21305, 21300, 21288, 23158, 2135, 19500, 19365, 22466, 14186, 22011, 2199, 2150, 21713, 2538, 2449, 2503, 2151, 13724
, 14120, 2547) ORDER BY "main_jobevent"."id" ASC
 22579 | 00:49:31.351398 | awx      | SELECT "main_jobevent"."id", "main_jobevent"."event", "main_jobevent"."event_data", "main_jobevent"."failed", "main_jobevent"."changed", "main_jobevent"."uuid", "main_jobevent"."playbook", "main_jobevent"."play", "main_jobevent"."role", "main_jobevent"."task", "main_jobevent"."counter", "main_jobevent"."stdout", "main_jobevent"."verbosity
", "main_jobevent"."start_line", "main_jobevent"."end_line", "main_jobevent"."created", "main_jobevent"."modified", "main_jobevent"."job_id", "main_jobevent"."host_id", "main_jobevent"."host_name", "main_jobevent"."parent_uuid", "main_jobevent"."job_created" FROM "main_jobevent" WHERE "main_jobevent"."host_id" IN (25917, 25144, 25922, 21346, 15405, 2885, 14072, 24525, 21632,
25918, 20183, 25921, 21520, 2451, 25919, 25667, 25589, 23737, 22794, 23729, 2452, 2537, 2545, 2450, 2508, 2414, 25588, 25205, 25542, 25207, 20416, 22074, 21306, 22768, 2501, 23289, 14090, 12757, 22687, 15352, 23288, 21238, 14074, 12755, 12753, 1926, 3288, 22686, 19387, 12654, 21298, 21631, 14075, 2651, 25920, 25923, 25540, 21253, 21345, 13726, 12756, 23334, 21932, 14124, 2886
, 20184, 14077, 21256, 21759, 14118, 25666, 3291, 13508, 13504, 21344, 21259, 22073, 2884, 22629, 2825, 2544, 19499, 24521, 12653, 25271, 19712, 2152, 25272, 25539, 15413, 13597, 24538, 2543, 22462, 2536, 21257, 19386, 3289, 2546, 13598, 21784, 21827, 25204, 21826, 15414, 22142, 14073, 20287, 20316, 20277, 25541, 21785, 2482, 22010, 21712, 12697, 21885, 20288, 3286, 22689, 25
206, 21910, 21299, 24524, 24522, 14273, 23706, 13503, 22461, 19388, 14076, 13725, 20618, 22126, 22127, 21884, 22217, 2549, 22502, 22501, 14070, 13509, 3290, 21258, 21529, 15402, 13506, 22688, 22216, 3287, 15412, 21497, 19391, 14123, 21347, 15404, 12817, 22116, 2339, 2415, 2506, 21255, 15411, 14071, 21545, 2548, 25270, 21968, 22194, 2416, 20417, 19390, 19389, 19392, 13600, 192
7, 13602, 2502, 24542, 25077, 12759, 14825, 24526, 2535, 24541, 24543, 2507, 24540, 25076, 2533, 13505, 2629, 13601, 21530, 13599, 15294, 2650, 24917, 13507, 25273, 22072, 13510, 20617, 21688, 2481, 2480, 12696, 19393, 22767, 15403, 21496, 12760, 12758, 14078, 21305, 21300, 21288, 23158, 2135, 19500, 19365, 22466, 14186, 22011, 2199, 2150, 21713, 2538, 2449, 2503, 2151, 13724
, 14120, 2547) ORDER BY "main_jobevent"."id" ASC
```

**Comment by AlanCoding** [comment]
The part with

```sql
UPDATE "main_jobhostsummary" SET "host_id" = NULL WHERE ...
```

would probably rule out the possibility that this is fixed by https://github.com/ansible/awx/pull/12447, since that's only dealing with the event -> host relationship, not the job host summary -> host relationship.

From the sequence of queries you have, it's probably the UPDATE that's taking effectively forever, and the other SELECT statements are getting hung up on the lock from the transaction. If we could figure out how to reliably reproduce that situation, I suspect that we could get a cheaper kind of fix. @mick1627 what specifically did you do to remove the inventory source? Did you delete it in the UI? And did you delete imported hosts along with it?

**Comment by mick1627** [comment]
Yes, the inventory source was removed in the UI. That's the only thing I did. 

I first received this error in the UI :

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/36628449/183442808-0fa1aed7-5585-47e7-ab36-0e661f49649c.png)


About a hour after I have the issue with the UPDATE/SELECT query still ongoing. 
I had to remove this inventory source several time due to an other strange thnigs https://github.com/ansible/awx/issues/12491, it's always the same behavior.

**Comment by d-rupp** [comment]
I encountered this issue yesterday as we removed two hosts that were featured in a lot of runs from our inventories.

My solution after finding this ticket was to heavily reorganize the job history from 60 down to 10 days and after that the inventory update (mainly the SQL UPDATE statement) took only 25 minutes.

**Comment by AlanCoding** [comment]
It seems very likely that https://github.com/ansible/awx/pull/12447 could address this. I would like to get people to try that patch out.

**Comment by Tioborto** [comment]
All works fine since the upgrade to the version 21.5.0
Thank you for you help 👍
