### ISSUE TITLE
"Sourced from a Project" Inventory Source error message is incorrect. 

### ISSUE THREAD

**Issue by mneumarkidg** [ansible/awx#1227]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Won't Save Setting/Error on Enable "Update on Project Change" in Inventory Source

##### ENVIRONMENT
* AWX version: 
sh-4.2# awx-python --version
Python 2.7.5
sh-4.2# awx-manage --version
1.0.3.41
* AWX install method: docker on linux
* Ansible version:  
sh-4.2# ansible --version
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
* Operating System: CentOS Linux release 7.4.1708 (Core)
* Web Browser: Version 64.0.3282.140 (Official Build) (64-bit)

##### STEPS TO REPRODUCE

1) Edit "Inventory Source" called "Development Environment"
2) Click on sources
3) Edit source
4) Check/enable "Update on Project Change"
5) Click Save

##### EXPECTED RESULTS

Enable Update on Project Change

##### ACTUAL RESULTS

Error! Message
data : [object Object] status : 400 headers : function (name){if(headersObj||(headersObj=parseHeaders(headers)),name){var value=headersObj[lowercase(name)];return void 0===value&&(value=null),value}return headersObj} config : [object Object] statusText : Bad Request xhrStatus : complete

##### ADDITIONAL INFORMATION

![screen shot 2018-02-13 at 10 15 45 am](https://user-images.githubusercontent.com/25063770/36166708-3be37532-10a8-11e8-80d9-acb65cde2e3d.png)

**Comment by jaredevantabor** [comment]
@mneumarkidg I think the issue here is that the error message the UI is displaying is incorrect. It should say: `"Cannot update SCM-based inventory source on launch if set to update on project update. Instead, configure the corresponding source project to update on launch."` From the looks of your screenshot it looks like you have "Update On Launch" selected, which won't work with "Update on Project Change" selected also.

**Comment by jaredevantabor** [comment]
Repurposing this issue to fix the error message on the UI

**Comment by jaredevantabor** [comment]
This is a duplicate issue of #1295, so I'm going to close this issue in favor of that card.

**Comment by fajfer** [comment]
This is still the case
