### ISSUE TITLE
Create custom facts in awx

### ISSUE THREAD

**Issue by YonatanGolick** [ansible/awx#12276]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

I saw that I can create custom facts in ansible and store the fact in the fact cache.
I would like to use the same thing in awx but could not find anything about that.
I'm not sure if its a feature that exists or is that something that needed to be developed so I'm asking you.

### AWX version

3.8.4

### Select the relevant components

- [ ] UI
- [x] API
- [ ] Docs

### Installation method

docker on linux

### Modifications

no

### Ansible version

2.9.26

### Operating system

Linux

### Web browser

Chrome

### Steps to reproduce

-

### Expected results

Using custom facts in awx

### Actual results

No documentation found on this matter.

**Comment by fosterseth** [comment]
fact caching is supported at the job template level, please see the documentation here to enable fact caching https://docs.ansible.com/automation-controller/4.2.0/html/userguide/job_templates.html#benefits-of-fact-caching

**Comment by fosterseth** [comment]
closing issue for now @YonatanGolick let us know if that documentation is helpful
