### ISSUE TITLE
Configuring AWX with Keycloak

### ISSUE THREAD

**Issue by GereG13** [ansible/awx#12282]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME

 - Authentication

##### SUMMARY

Not able to get AWX to use SAML Authentication on Keycloak.

##### ENVIRONMENT
* AWX version: 6.0.0

##### STEPS TO REPRODUCE

Tried following this document: https://josh-tracy.github.io/Ansible_Tower_RedHatSSO/

##### EXPECTED RESULTS

I expected to get a login prompt from Keycloak where I can sign in.

##### ACTUAL RESULTS

AWX was showing "Sign in with S" at the login page after following the above instructions/page but when clicking on the S I get redirected to Keycloak page but it says "We are Sorry ... Page Not Found"

**Comment by tpanagoda** [comment]
I just wanted to check whether this is resolved as I have the same issue.

**Comment by GereG13** [comment]
Yes, it was but it's been a while.
Did you see this one : https://github.com/ansible/awx/pull/5577

If that doesn't work maybe share more details so I can troubleshoot and help hopefully.
