### ISSUE TITLE
RFE: Max concurrent forks/jobs on container group

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#12288]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Right now ContainerGroups don't have any concept of capacity. They therefore are sinks for jobs if any container group is in the preferred instance group list when jobs are going through the task manager. This can cause problems of sending too many jobs to a container group. Even if you DO assign some kind of limit to pods in a namespace and kubernetes sends back a 4xx response, we just re-submit the job to pending and we'll try and schedule it there again the next time around.

A KISS solution is to do something like the jenkins kubernetes plugin does, which is allow users to set a cap on how many concurrent jobs to schedule on a container group.

We could add "max_concurrent_jobs" to InstanceGroups that are ContainerGroups (not sure on how to do this conditionally, but we must be able to since we don't have pod_spec_override on all the InstanceGroups)

At startup of the task manager, we can look at the `jobs_running`  for container groups https://github.com/ansible/awx/blob/0c4ddc7f6fe2e52c7a8b44ec7e576929ea861a66/awx/main/models/ha.py#L342-L344

Then, we probably need to extend the models in to store this value for ContainerGroups and keep a running tab of how many left we have before we hit "max_concurrent_jobs" https://github.com/ansible/awx/blob/devel/awx/main/scheduler/task_manager_models.py#L25-L26 to account for ContainerGroups in particular needing to "consume_capacity" in a slightly different way -- for CG just count jobs, not task_impact

**Comment by adpavlov** [comment]
Limiting parallel jobs run levels out automation and ansible ideology.
I would state that It's real and dramatic degradation in performance comparing to AWX 15 and docker architecture.

Following my initially created issue #12088, I proceeded testing and experiencing very slow behavior. In my case few parallel jobs are running quite fast and fine.
However, if I need to launch more than 10 parallel jobs it will lead to 10 Pods/containers creation, which takes more than 2 minutes to create Pods and containers. I have a workflow with even 17 parallel templates and it's time increasing up to 7 minutes just for playbook to understand that no hosts matched:)

At the same time awx_task container memory usage goes to the sky up to 8Gb, server is lagging.
Sometimes jobs are going in Error state with different reasons like:

- Error creating pod: rpc error: code = Unknown desc = database is locked
- No output found for this job.
- Error opening pod stream: Get "https://ansible:10250/containerLogs/awx/automation-job-503-9j922/worker?follow=true": write tcp 10.50.78.37:6443->10.50.78.37:41436: i/o timeout

So as a conclusion, docker based single(!) awx-task container in release of AWX 15 handled the same load very fast and smooth without any load on server, whereas k8s architecture and AWX 21 almost killing the server and putting jobs in error state.

**Comment by kdelee** [comment]
Related to https://github.com/ansible/awx/issues/12019

**Comment by kdelee** [comment]
@adpavlov yes, creating jobs in pods puts stress on the k8s api server. @TheRealHaoLiu specifically was just talking about requirements we may want to consider documenting for the k8s master, etcd, etc. to enabe that the k8s api etc can keep up with the load of starting/controlling all of these pods for k8s itself.

Some benefits to using container groups over our previous approach of using bwrap to isolate jobs within the task container itself are:

- we can use different containers for different jobs that provide different system requirements, ansible versions, ansible content
- we no longer need privileged task container, which was a blocker for many people to run awx on openshift clusters where admins did not allow priviledged containers
- We open the door to awx playing nicely with ideas around horizontally scaling the underlying kubernetes as well as the awx control plane itself
- we open door to solving better problems of isolating job's resource consumption from the control plane. Although we don't do it out of the box, today it is possible to configure the control plane and job pods to run in different namespaces or different dedicated k8s worker nodes. Different organizations could have their own dedicated container groups that run in their own namespaces, on their own nodes. This allows admins to protect different workloads from each-other and be more judicious about where resources are used.

That said, the minimum requirements for a small awx installation are probably increased by this approach, so I can understand the frustration. However, our primary interest at this time is not optimizing the economy of small installations, but rather the ability to scale larger/more horizontally.
