### ISSUE TITLE
[Metrics&Observability] Surface DB connections in /api/v2/metrics

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#12299]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Surface the number of database connections awx is making to roll more of the data administrators need to track into /api/v2/metrics 

Users can track this now by creating some kind of exporter that directly queries PG, but this is in general hacky and not portable. We know if we exceed the max connections that things start to go bad, so it is a best practice to track this number.

Maybe we can follow pattern of https://github.com/ansible/awx/blob/4dc956c76f31accc3f57599d5e6df1735ffa2c16/awx/main/analytics/collectors.py#L255-L260

And create a `database_stats` function that returns a dictionary with a key for current connections by awx user. I say a dictionary so we can later expand that if desired, like adding number of idle vs active connections, or the max connections. These could then get surfaced like we do for guages like ORG_COUNT. https://github.com/ansible/awx/blob/4dc956c76f31accc3f57599d5e6df1735ffa2c16/awx/main/analytics/metrics.py#L18

**Comment by kdelee** [comment]
@jainnikhil30 expressed interest in doing this

**Comment by kdelee** [comment]
@Zokormazo in needs test now :D

**Comment by obaranov** [comment]
Validated from QE side. Added automated tests.
