### ISSUE TITLE
Add support for AWX Org/Team/Superuser mapping via github enterprize team names 

### ISSUE THREAD

**Issue by rupadhy3** [ansible/awx#12294]
We have to limit this because of limited volunteer time to respond to issues! -->

##### ISSUE TYPE
 - Add support for AWX Org/Team/Superuser mapping via github enterprize team names 

##### SUMMARY
Currently AWX Org/Team mapping via GitHub enterprise is done using individual GitHub enterprise team members or GitHub enterprise Org members.
Can the GitHub enterprise teams be directly mapped to an AWX team or Org rather than the members individually mapped to AWX team/Org.

**Comment by fosterseth** [comment]
This is currently supported, please see this section of the docs https://docs.ansible.com/automation-controller/4.1.0/html/administration/social_auth.html#organization-and-team-mapping

**Comment by fosterseth** [comment]
Let us know if what is described in the docs is helpful to you, if not feel free to open another issue. closing for now
