### ISSUE TITLE
AWX on windows

### ISSUE THREAD

**Issue by dberardo-com** [ansible/awx#12304]
before version 18, which introduced a breaking change in the installation, i was able to install AWX on windows using docker compose and a ansible/cygwin terminal. Now things got harder. Is there a way to install AWX using ansible like in the old days?

here for reference https://github.com/ansible/awx/blob/18.0.0/tools/docker-compose/README.md:

> Removed installer directory.
The Kubernetes installer has been removed in favor of [AWX Operator](https://github.com/ansible/awx-operator).
The "Local Docker" install method has been removed in favor of the development environment. Details can be found at: https://github.com/ansible/awx/blob/devel/tools/docker-compose/README.md

**Comment by nixocio** [comment]
Hello, your question seems like a good one to ask on our mailing list at https://groups.google.com/g/awx-project. You can also join #ansible-awx on https://libera.chat/ and ask your question there.
