### ISSUE TITLE
create table with AWX users and their roles

### ISSUE THREAD

**Issue by 06seasparkle** [ansible/awx#12310]
##### ISSUE TYPE
 - Feature Idea

**Comment by 06seasparkle** [comment]
Hi ,

Hi ,

How can I pull the table with the user and their roles on postgresql query on Ansible AWx 21.0.0?
Can you help us ?

**Comment by nixocio** [comment]
Hello, your question seems like a good one to ask on our mailing list at https://groups.google.com/g/awx-project. You can also join #ansible-awx on https://libera.chat/ and ask your question there.
