### ISSUE TITLE
Tower rest api job_templates launch endpoint is not working

### ISSUE THREAD

**Issue by samibinsami** [ansible/awx#12319]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

I have ansible tower api version: 3.7.0.

The [documentation](https://docs.ansible.com/ansible-tower/3.7.0/html/towerapi/api_ref.html#/Job_Templates/Job_Templates_job_templates_launch_create) says that it supports a **POST** to **api/v2/job_templates/id/launch/** see the screen shot attached for more clarity.

However, when i call to the POST mentioned above i am getting the same response as i get via GET request to job_templates endpoint.

Expectation:

- I want **POST api/v2/job_templates/id/launch/** to return http 201 status code and execute the job.

Actual:

- I see 200 http status code containing the response body same as GET api/v2/job_templates/id/launch and without the job_template being executed.

![image](https://user-images.githubusercontent.com/24696941/171879952-7367e776-ec13-45e6-8575-e647234709ef.png)

![ansible screen shot](https://user-images.githubusercontent.com/24696941/171872728-cae7469b-d856-410e-95f9-ab65a944660e.png)

### AWX version

3.7.0

### Select the relevant components

- [ ] UI
- [X] API
- [X] Docs

### Installation method

openshift

### Modifications

no

### Ansible version

2.9.13

### Operating system

Windows 10 Enterprise

### Web browser

Chrome

### Steps to reproduce

Install:
1. Ansible: 2.9.13
2. Ansible Tower: 3.7.0
3. Create a user xyz in ansible.
4. Add a PAT token to the user xyz
5. Create a job template.
6. From postman call the POST: api/v2/job_templates/id/launch/ with the Bearer <PAT>
7. You should see a 200 http status code being return and the response body the POST will be the same as of GET.

### Expected results

- I want **POST api/v2/job_templates/id/launch/** to return http 201 status code and execute the job.

### Actual results

- I see 200 http status code containing the response body same as GET api/v2/job_templates/id and without the job_template being executed.

**Comment by kialam** [comment]
The screenshot you provided is for job template details and not the launch endpoint. Sending a POST will return a 201 if successful to `/api/v2/job_templates/{id}/launch/`

![Screen Shot 2022-06-03 at 11 02 30 AM](https://user-images.githubusercontent.com/2293210/171921030-afdff0b3-a493-456b-abf2-9980a1173e31.png)

**Comment by samibinsami** [comment]
Agree
