### ISSUE TITLE
Jobs get marked as failed shortly after AWX Pod was restarted

### ISSUE THREAD

**Issue by Cl0udius** [ansible/awx#12326]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

When executing long running jobs on an AWX instance on K8S with container groups the jobs get marked as failed after we restart or recreate the AWX Pod. 
We were expecting that after a restart of the control plane the running jobs can still be managed by the new instance.

### AWX version

19.4.0

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

- Start a long running job on existing AWX node.
- Restart Pod of AWX instance
- Watch job getting status failed after 1 or 2 minutes

### Expected results

- Job continues to run and finished like without restarting the AWX Pod

### Actual results

- Job gets status failed after some minutes on the new AWX pod
- message in Logs of AWX pod: "2022-06-06 10:30:38,626 DEBUG    [30bb44ced9104b2e92dc9357398334dd] awx.main.tasks job 67 (failed) is no longer active, reaping orphaned k8s pod"
- Status of job in UI: "Task was marked as running but was not present in the job queue, so it has been marked as failed."

### Additional information

Is there a 1:1 binding between AWX Pod (Task container) and the automation-job pods?
If yes: What is the technical background for this. I would like to understand it.
I was expecting that after a needed recreating of the AWX pod (host failure, resizing deployment replicas....) the jobs can still be managed.
Currently if the AWX pod fails for a reason we loose all long running jobs.
I also tested this on version 21 with the same result.

**Comment by shanemcd** [comment]
This is unfortunately a known limitation.

Every job has a "controller" - one of the AWX control plane pods. This controller handles launching job pods, receiving events, processing them, and eventually persisting them to the database.

Each control plane pod has its own sidecar redis container that is used as a buffer for job events that are being emitted. This data lives entirely in memory. If you delete a control plane pod, all job data that is not yet persisted in the database will get lost. To solve this specific problem we might consider using a persistent volume for redis. But this would only fix the case where events are already in redis.

Things become even more complicated when you consider how we receive events back from the Kubernetes pods using the pod's logs. There is code in AWX that is actively streaming the pod logs as they are emitted. If you delete a control plane pod and the connection to the job pod is lost, Kubernetes does not allow us to pick back up where we left off, so we'd need to re-ingest _all_ events, which would have a huge hit on performance.

These are all things that we're actively thinking about as part of a larger initiative being tracked in https://github.com/ansible/awx/issues/11526. Any updates will be posted here or in that issue.

**Comment by Cl0udius** [comment]
Hi.
Thanks a lot for clarification. I will look into the issues to get some updates on the possible solutions.
