### ISSUE TITLE
Set browser timezone as default when creating a schedule

### ISSUE THREAD

**Issue by d-rupp** [ansible/awx#12336]
##### ISSUE TYPE
It would be great if when you add a new schedule for a template that the default initial timezone would be the users browser timezone (or something similar related to the user) and not the default "America/New_York".

##### SUMMARY
When you create a new schedule it shows your own timezone instead of the default "America/New_York" one.

The default is set here: https://github.com/ansible/awx/blob/9191079ddaaf3fa5bb6ad6221c2a2af982da455e/awx/ui/src/components/Schedule/shared/ScheduleForm.js#L410

**Comment by tvo318** [comment]
Not sure if work is related or can be updated to include this logic: https://github.com/ansible/awx/pull/12340

**Comment by john-westcott-iv** [comment]
#12340 would not address this but @keithjgrant is working on some other schedule page updates and may be able to address this at the same time.

**Comment by keithjgrant** [comment]
PR at #12445

**Comment by akus062381** [comment]
I see this is in needs_review, but the linked PR doesn't seem to include this change...?

**Comment by keithjgrant** [comment]
The pertinent change is at https://github.com/ansible/awx/pull/12445/files#diff-17dca043aaac54c1923ff315e95e8a1845e129f19d846c206906bb1a209b2b15L436

`timezone: schedule.timezone || now.zoneName` instead of 'America/New_York' being hard-coded as default
