### ISSUE TITLE
ERROR! couldn't resolve module/action 'community.vmware.vmware_content_deploy_ovf_template'. Ansible Tower

### ISSUE THREAD

**Issue by SureshUppelli** [ansible/awx#12347]
Trying to deploy vm from ovf template from content library in Ansible Tower job

ERROR! couldn't resolve module/action 'community.vmware.vmware_content_deploy_ovf_template'. This often indicates a misspelling, missing collection, or incorrect module path. The error appears to be in '/tmp/bwrap_3_39c7jx5j/awx_3_2vmpzxuh/project/deploy-ova-from-content-library.yml': line 8, column 9, but may be elsewhere in the file depending on the exact syntax problem. The offending line appears to be: tasks: - name: Deploy Virtual Machine from OVF template in content library ^ here

![image](https://user-images.githubusercontent.com/45890987/172669249-7d379a22-fcbd-40d3-870e-c3e8cdff9d6c.png)

![image](https://user-images.githubusercontent.com/45890987/172669270-7d1b3bec-61e9-46b1-917e-7155f9d3ed8b.png)

![image](https://user-images.githubusercontent.com/45890987/172669330-c2bb512d-5e5f-4f8a-ad89-f4eb45959a05.png)

pip install pyvmomi 
pip install --upgrade pip setuptools 
pip install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git 
ansible-galaxy collection install community.vmware

I installed all the dependencies but still having issue with ansible tower

**Comment by shanemcd** [comment]
Hello. This is an issue tracker for the upstream AWX project. If you are a Tower customer, please open up a support issue and they will help you out.
