### ISSUE TITLE
Ability to Configure hostname of awx host in inventory file. Not default to 'awx'. 

### ISSUE THREAD

**Issue by mneumarkidg** [ansible/awx#1234]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - Installer

##### SUMMARY
Ability to Configure hostname of awx host in inventory file. Not default to 'awx'.  Should use hostname and/or be configurable in the inventory.

##### ENVIRONMENT
* AWX install method: docker on linux

**Comment by okelet** [comment]
`awx_task_hostname`and `awx_web_hostname` inventory variables are your friends (https://github.com/ansible/awx/blob/devel/installer/inventory#L58), resolved in https://github.com/ansible/awx/pull/2131.
