### ISSUE TITLE
ERROR! [DEPRECATED]: community.general.docker_service has been removed.

### ISSUE THREAD

**Issue by amarbut24** [ansible/awx#12350]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Hello,

I'm running `15.0.1`, haven't really had a reason to look into upgrading to a newer version.
I went to run the [Docker Compose playbook for version 15.0.1 ](https://github.com/ansible/awx/blob/15.0.1/INSTALL.md#docker-compose)as I have many times and ran into a new error

```
ERROR! [DEPRECATED]: community.general.docker_service has been removed. Use community.docker.docker_compose instead. This feature was removed from community.general in version 2.0.0. Please update your playbooks.
```

Is there workaround for this error or am I stuck upgrading to a newer version?
If an upgrade is required, what version should I move to from 15.0.1? 

### AWX version

15.0.1

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs

### Installation method

docker on linux

### Modifications

no

### Ansible version

ansible [core 2.11.12]

### Operating system

Ubuntu

### Steps to reproduce

using these instructions -> https://github.com/ansible/awx/blob/15.0.1/INSTALL.md#docker-compose
ran `sudo ansible-playbook -i <args>`

### Expected results

No errors

### Actual results

`ERROR! [DEPRECATED]: community.general.docker_service has been removed. Use community.docker.docker_compose instead. This feature was removed from community.general in version 2.0.0. Please update your playbooks.`

**Comment by shanemcd** [comment]
Hello - we don't have the resources to support older versions of AWX. In more modern versions you would solve this by building your own Execution Environment (see Ansible Builder). If you want help hacking AWX 15, you might get more help on IRC or the mailing list:

#ansible-awx on https://libera.chat/
https://groups.google.com/forum/#!forum/awx-project

**Comment by amarbut24** [comment]
Hey @shanemcd 

Totally understand being unable to support such an older version. Does your team have any documentation on upgrading from version 15 to a newer (stable) version?

**Comment by amarbut24** [comment]
fwiw (in case someone runs into this issue and lands on this issue)
simply going from 15.0.1 -> 17.0.1 fixed the playbook error

If someone has some time question still stands on the recommended upgrade path from 17.0.1.
I see this doc -> https://github.com/ansible/awx/blob/devel/tools/docker-compose/docs/data_migration.md
Which _I think_ is what I would follow

Should I just go to the newest release?

**Comment by zikkuratti** [comment]
/awx/installer/roles/local_docker/tasks/main.yml change docker_service to docker_compose work for me also add python to alternatives of python3 on  next step and docker usermod -aG stuff to create it
