### ISSUE TITLE
Ansible playbook?

### ISSUE THREAD

**Issue by TinajaLabs** [ansible/awx#12362]
Irony?

I see all these complicated instructions for installing the application in Kubernetes, but wouldn't a playbook do it better?

Can I skip Kubernetes and just install in an instance of centos, or ubuntu?

Thank you.

**Comment by shanemcd** [comment]
Hi Chris. Sorry to see you appear to be frustrated. We have a small team and can only afford to maintain a single install path for the upstream community. If you look into how the operator works, it runs Ansible code internally. A lot of folks use it and we get just as many (if not more) contributions to that project as we did for our old install playbook. Give it a shot and maybe you’ll end up liking it. If not, that’s ok. It’s open source so you’re free to do whatever you want in terms of packaging. Have a nice weekend.

**Comment by TinajaLabs** [comment]
Thanks, Shane,

The single install path you recommend is via kubernetes, right?  and to do that it requires AWX Operator? 

Before posting I googled and just now get it that "operator" is a automation config model for kubernetes - "Kubernetes operator is an application-specific controller that extends the functionality of the Kubernetes API to create, configure, and manage instances of complex applications on behalf of a Kubernetes user."

Yeah, hard to understand why an "operator" thing for AWX when you don't even know it's a config component of kubernetes.

I guess I thought I was just installing a web app to manage all my ansible playbooks.  Currently I install all my apps and manage service restarts, updates, etc with ansible playbooks; from the command line.  I'm just looking for a web UI to manage and track them so I don't have to write it myself.  ;)

I would have expected to see ansible used to:
1 install AWX in an instance, (IMO, easiest because I don't have to learn containers first), or
2 install Kubernetes/Minikube, and 
3    install AWX into a container (perhaps framing the process as ansible building the operator)

BTW, isn't all this supposed to be about leveraging ansible to do our automation?  This is in the ansible github account.

I get it that you're a small team, so this is not a complaint but more of an observation.  Perhaps a little overview of why ansible, why containers, why operator, why complexity, for a relatively simple web monitoring app would be helpful.

Thank you,
Chris.
