### ISSUE TITLE
Project not updating in Template

### ISSUE THREAD

**Issue by chrisvanmeer** [ansible/awx#12379]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Whenever I try to change the project field of an existing template and save it, the changes are ignored. Changes to any other field are successfully updated.

### AWX version

17.1.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.9.18

### Operating system

RHEL 7

### Web browser

Firefox, Chrome, Edge

### Steps to reproduce

Open up an existing template, click on the magnify glass on the Project field, change the project selection and hit the Save button.

### Expected results

That the template is saved with the new project.

### Actual results

Project changes are ignored upon save.

**Comment by chrisvanmeer** [comment]
Ok found the issue, after changing the project, you need to re-select a playbook and if you don't, you won't get notified that you are missing a required field, but the change is just ignored.

I don't know if this is by design, or is missing a "required field" check.

**Comment by AlexSCorey** [comment]
You should have gotten a notification after trying to save the job template if you did not select a playbook.

**Comment by AlexSCorey** [comment]
![Screen Shot 2022-06-15 at 12 07 35 PM](https://user-images.githubusercontent.com/39280967/173874355-7ec2d3f0-72bb-42d1-b71b-2e1b163d19f3.png)

**Comment by chrisvanmeer** [comment]
It did show me the message below the selectbox, but apparently there is no further check if all required fields are filled while pressing the Save button.

**Comment by AlexSCorey** [comment]
I'll add that it looks like you are using an old version of Ansible and I recommend that you upgrade to the latest version.
