### ISSUE TITLE
Can I add Inventory automatically?

### ISSUE THREAD

**Issue by sohwaje** [ansible/awx#12388]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature Summary

1. Is Cutom Inventory Scripts missing? If so, what can I use to automatically add inventory in AWX?
2. How do I import and write the Inventory of Zabbix from Ansible?

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

**Comment by AlexSCorey** [comment]
@sohwaje Thanks for reaching out. I'm not sure what version of awx you are using, but Inventory Scripts was deprecated in  version 3.8.6.  For help with a workaround please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.

**Comment by sohwaje** [comment]
@AlexSCorey If Inventory Scripts disappeared, how do I dynamically add inventory in the version of AWX 20.1.0 I am not interested in integrating with Azure or AWS. I want to add my On-premis servers dynamically or automatically. Is there any way?

**Comment by AlexSCorey** [comment]
@sohwaje The mailing list is really the best place to get this type of help.  See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.

However, to get you started: You can use SCM inventory sources that use scripts inside the assigned file to dynamically add inventories.
