### ISSUE TITLE
Add supported awx-operator version in a release notes

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/awx#12387]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature Summary

As a user, I want to know what awx version(s) are compatible with a given awx-operator version.  

#### Context

Currently, in the awx-operator, on the `devel` branch, the awx image tag is set to latest.  But each released awx-operator image has the supported image version set as the version of awx it was released in conjunction with (also the supported version).  

If you check out a tag and run  `make deploy` to deploy the operator to your cluster, the version is [automatically parsed based](https://github.com/ansible/awx-operator/blob/devel/Makefile#L6) on the tag you are on, and the correct operator container for that version will be used.  The supported awx version tag is properly set in the operator container so that, by default, the supported version will be deployed when an AWX CR is created.  

The user can override the `image` and `image_version` via the spec if desired.  

#### Potential Solution

Although it can be found by inspecting the env vars in the awx-operator container for a given tag, it would be nice to include the "supported awx version" in the awx-operator release notes.  

This could be added to our github workflow automation.  I created this issue in the awx repo because that automation is run from here.  

#### Select the relevant components

- [X] Release Automation

#### Additional Info

Some context on how this works:
* Our release workflow injects the DEFAULT_AWX_VERSION variable when building the awx-operator image [here](https://github.com/ansible/awx/blob/devel/.github/workflows/stage.yml#L86).  
* It is used [here](https://github.com/ansible/awx-operator/blob/0983220fba279a76a6d39bc22cd4e86959c34c5a/roles/installer/defaults/main.yml#L128) inside the operator container, meaning that the awx version linked to the awx-operator version is automatically used.

**Comment by kurokobo** [comment]
For someone who needs this, [here is an _unofficial_ mapping table](https://github.com/kurokobo/awx-on-k3s/blob/main/tips/version-mapping.md) of past versions.

It would be so nice if the supported version is available on the release notes 😃

**Comment by JG127** [comment]
If I may be so bold to ask: can the ansible release version also be included ? 

This is for development & test reproducing purposes. Otherwise every developer needs an AWX environment to develop playbooks.

The unofficial mapping is spot on what I was looking for ! :-)

**Comment by kurokobo** [comment]
@JG127 
In my opinion, the version of Ansible that used to run playbook totally depends on which EE image is used. Therefore, I don't think including the Ansible version in the release notes will help much.

For development and reproducibility purposes, I think it would be more appropriate to run playbook on the same EE that AWX uses. To achieve this you can use Ansible Navigator or Ansible Runner.

**Comment by john-westcott-iv** [comment]
In the AWX release docs we added a task to cross link the releases of AWX and Operator and did this for the last releases.
