### ISSUE TITLE
Add help text to schedules in UI.

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#12399]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature Summary

In #12340 we added a waning when selecting a timezone that is a link to another timezone.

It was suggested that we add a help icon to the UI form to take people to:
https://docs.ansible.com/ansible-tower/latest/html/userguide/scheduling.html

And to modify the docs with a more detailed explanation of why they are seeing the error message with a possible link to https://lwn.net/Articles/870478/ for users to get more infomation.

### Select the relevant components

- [X] UI
- [ ] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

**Comment by InnocentK** [comment]
Resolved
