### ISSUE TITLE
RFE: allow for the same JT name in different organizations

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1239]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY

This is not currently allowed.
```
jobs.py:    SOFT_UNIQUE_TOGETHER = [('polymorphic_ctype', 'name')]
```
##### ENVIRONMENT
* AWX version: current

**Comment by john-westcott-iv** [comment]
Templates are related to organizations through a project and can now have the same name.
