### ISSUE TITLE
New warning about timezone being saved as something else not properly translated.

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#12398]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

A warning was added when selecting a timezone that is a link to another timezone in https://github.com/ansible/awx/pull/12340. The error message does not appear to be translated correctly in the UI.

### AWX version

devel

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

N/A

### Operating system

N/A

### Web browser

Chrome

### Steps to reproduce

Edit a schedule in the UI. Select a timezone of Europe/Sarajevo.
The warning pops up:
![image](https://user-images.githubusercontent.com/32551173/174829015-ddcbb4c0-295a-4ed9-b120-bf94c5c1319e.png)

Change browser to a different language, the warning is not translated:
![image](https://user-images.githubusercontent.com/32551173/174828882-28575f71-2b4d-4c0c-b244-91e445217560.png)

### Expected results

The warning string should be translated.

### Actual results

![image](https://user-images.githubusercontent.com/32551173/174828882-28575f71-2b4d-4c0c-b244-91e445217560.png)

**Comment by mabashian** [comment]
We should be able to close this once https://github.com/ansible/awx/pull/13198 merges
