### ISSUE TITLE
Execution environment field is updated autmatically into default value

### ISSUE THREAD

**Issue by lagunary** [ansible/awx#12434]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

The field (you may find in attached screenshot) has been updated by id: 0 (checked it at postgres DB) at night.

### AWX version

AWX 21.0.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

yes

### Steps to reproduce

We cant reproduce it, this was the first time when it was happened. But it is so strage.

### Expected results

X

### Actual results

Our ee has additional python packages, (eg: hvac) and it was not working.

### Additional information

![awx-bug](https://user-images.githubusercontent.com/12951104/176136572-ec736192-cb4e-401a-ad6b-270961788adc.png)
That field has been updated automatically.
id:0 was in the last update field in database. May a cleaner/maintenancer job could update it.
Please check it, or if you have any clue what did happen please contact us.
Thanks in advance.

**Comment by fosterseth** [comment]
the awx-operator might be overriding whatever changes you make in the UI

are you setting the default awx-ee using the `ee_images` field as described here

https://github.com/ansible/awx-operator#deploying-a-specific-version-of-awx ?

**Comment by lagunary** [comment]
Yes, you're right.  We tested, and it is fine.
Sorry for missed info.
