### ISSUE TITLE
Remove update_on_project_update

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#12436]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature Summary

The api has deprecated and removed `update_on_project_update` in the inventory sources form.  It should be removed.   It may exist elsewhere also to whoever picks this up should just be sure to remove it from all places.

See https://github.com/ansible/awx/pull/12366 and https://github.com/ansible/awx/issues/12206
### Select the relevant components

- [X] UI
- [ ] API
- [x] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

**Comment by nitishmalang** [comment]
Hey I want to work on this can I get started

**Comment by AlexSCorey** [comment]
@nitishmalang Yes, go for it!
