### ISSUE TITLE
[task_manager] loop over instances instead of tasks

### ISSUE THREAD

**Issue by fosterseth** [ansible/awx#12440]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Possible enhancement to task manager to prevent head of line blocking.

processing pending tasks loops over Pending tasks, ordered by creation date (oldest tasks are considered first)

However, imagine a bunch of these jobs just aren't ready to run yet due to unavailable capacity of their preferred instance groups.

Instead, sort by instances first (lowest capacity first) and start looking at tasks that could run on those instances. That way each task manager is productive in a sense that it can start more tasks since it first considers tasks that are ready to run.

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

**Comment by AlanCoding** [comment]
So this isn't the same as https://github.com/ansible/awx/issues/12201, because this seeks to reduce the number of jobs considered in the overall loop.

These aren't the same, but I consider the two solutions as competitors, because I believe they solve mostly the same problem.

**Comment by kdelee** [comment]
We've decided that we accomplished this in another fashion, so closing this
