### ISSUE TITLE
How to install/manage Dynamic Inventories through operator deployment

### ISSUE THREAD

**Issue by SomniVertix** [ansible/awx#12441]
##### ISSUE TYPE
 - Question / Concern

##### SUMMARY
We're looking to install Dynamic Inventories onto our AWX Operator and we're just not sure how that would work since, in the normal install, most of those have to be installed on the host itself. Not sure how to install Dynamic Inventories through the kubernetes operator. I don't see it documented anywhere, but please let me know if it is!

##### ENVIRONMENT
* AWX version: Latest
* Operator version: Latest
* Kubernetes version: 1.20
* AWX install method: docker on linux

**Comment by shanemcd** [comment]
Hello. Inventories are managed via the API or UI, not through the operator. You may get more help with usage questions like this on the mailing list or IRC: https://github.com/ansible/awx#get-involved
