### ISSUE TITLE
[Job output] clicking a line while running sometimes ends in "Something went wrong..." // `u.summary_fields is undefined`

### ISSUE THREAD

**Issue by Commifreak** [ansible/awx#12443]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Sometimes, when I hit a `changed` line while a jobs is running(!) the following error occurs:

```
Rae@http://ansible-qlb.host/static/js/main.ae6cdd21.js:2:3360251
oo@http://ansible-qlb.host/static/js/main.ae6cdd21.js:2:1095837
Ks@http://ansible-qlb.host/static/js/main.ae6cdd21.js:2:1148137
Ol@http://ansible-qlb.host/static/js/main.ae6cdd21.js:2:1135380
Tl@http://ansible-qlb.host/static/js/main.ae6cdd21.js:2:1135308
El@http://ansible-qlb.host/static/js/main.ae6cdd21.js:2:1135169
yl@http://ansible-qlb.host/static/js/main.ae6cdd21.js:2:1132135
4463/Ji/<@http://ansible-qlb.host/static/js/main.ae6cdd21.js:2:1081629
6813/t.unstable_runWithPriority@http://ansible-qlb.host/static/js/main.ae6cdd21.js:2:1177891
Vi@http://ansible-qlb.host/static/js/main.ae6cdd21.js:2:1081406
Ji@http://ansible-qlb.host/static/js/main.ae6cdd21.js:2:1081576
Ki@http://ansible-qlb.host/static/js/main.ae6cdd21.js:2:1081509
Re@http://ansible-qlb.host/static/js/main.ae6cdd21.js:2:1152676
Xt@http://ansible-qlb.host/static/js/main.ae6cdd21.js:2:1060129
```

Video:

https://user-images.githubusercontent.com/87267/176594589-37e124dc-3c8e-4566-8acf-9b58fe361d4d.mp4

JS error:

```
TypeError: u.summary_fields is undefined
    Rae HostEventModal.js:110
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
        Vi
        Ji
        Ki
        Re
        Xt
```

### AWX version

21.2.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

minikube

### Modifications

no

### Operating system

Ubuntu 20.04

### Web browser

Firefox

### Steps to reproduce

Run job
Wait until some hosts are getting processed
Hit a result line

### Expected results

Normally opened Modal with Host Task details

### Actual results

An JS error

**Comment by akus062381** [comment]
@Commifreak does this only happen while the job is running? have you noticed it happening after the completion of a job?

**Comment by mabashian** [comment]
@keithjgrant any thoughts on this one?  Not sure what the expected behavior is.  Will clicking a line while a job is running always have all the needed information?  If not, maybe we should disable the line until ready?

**Comment by Commifreak** [comment]
I have to test its just while running vut I velieve yes, because:

Job runs, some lines are there. Some new lines appear as the job runs.. click.. no error. But after some time I get a line which causes the error. Reloading the whole page and hit the exact line again (while still running) works perfectly. The error is reproducible as soon as new lines come in.

this was never an issue before, since I use this sometimes. Never stumbled upon this. The previous versions worked.

I also noticed a „please wait, loading“ grey line placeholder in between loaded lines, which were never there in previous versions neither (can take a screenshot of what I mean if unclear).

**Comment by Commifreak** [comment]
> I also noticed a „please wait, loading“ grey line placeholder in between loaded lines, which were never there in previous versions neither (can take a screenshot of what I mean if unclear).

=> 
![grafik](https://user-images.githubusercontent.com/87267/178899013-5c5272d5-3031-4503-908a-f5bf982ed647.png)

**Comment by rudesome** [comment]
We are experience the same issue after upgrading from 21.0 to 21.8

```
TypeError: u.summary_fields is undefined
bfe@https://example.domain/static/js/main.43dd0163.js:2:3328237
oo@https://example.domain/static/js/main.43dd0163.js:2:850659
Ks@https://example.domain/static/js/main.43dd0163.js:2:902959
Al@https://example.domain/static/js/main.43dd0163.js:2:890202
Tl@https://example.domain/static/js/main.43dd0163.js:2:890130
El@https://example.domain/static/js/main.43dd0163.js:2:889991
yl@https://example.domain/static/js/main.43dd0163.js:2:886957
4463/Yi/<@https://example.domain/static/js/main.43dd0163.js:2:836451
6813/t.unstable_runWithPriority@https://example.domain/static/js/main.43dd0163.js:2:932713
Vi@https://example.domain/static/js/main.43dd0163.js:2:836228
Yi@https://example.domain/static/js/main.43dd0163.js:2:836398
Ki@https://example.domain/static/js/main.43dd0163.js:2:836331
Ne@https://example.domain/static/js/main.43dd0163.js:2:907498
Jt@https://example.domain/static/js/main.43dd0163.js:2:814951
```

**Comment by rudesome** [comment]
What i think is causing this issue is:

![alt text](https://i.imgur.com/pmJ5Q2q.png)

as soon as this pop ups all the clicks for showing detailed output in the job is giving the error.

I don't have the issue after clicking "Reload output" in the popup.
Why not reload the output automatically?

 i have this issue also while jobs are still running

**Comment by mooky31** [comment]
> What i think is causing this issue is:
> 
> ![alt text](https://camo.githubusercontent.com/9a2be3067cf792886128d1df9f8c62a768c673a9b804c6d646e0bfb4a40a0da7/68747470733a2f2f692e696d6775722e636f6d2f706d4a355132712e706e67)
> 
> as soon as this pop ups all the clicks for showing detailed output in the job is giving the error.
> 
> I don't have the issue after clicking "Reload output" in the popup. Why not reload the output automatically?
> 
> i have this issue also while jobs are still running

Same error here in 21.7

**Comment by keithjgrant** [comment]
This sounds like it might be a duplicate of #13147, which just had a fix added in the last release. Does this still occur in 21.9?

**Comment by Commifreak** [comment]
Seems to be fixed with the mentioned change. Thanks! :)
