### ISSUE TITLE
[TaskManager] WorkflowManager research/refactor

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#12458]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature Summary

In the WorkflowManager we have some specific research and refactor items

- [x] Only build WorkflowDAG once for and loop once over the workflows
- [x] remove transistion of pending workflows to running workflows from TaskManager, do in WorkflowManager
- [x] Research ways to bail out if we are nearing our 5 min time limit
- [x] Research why/if we need to track allow_simultaneous blocking in both the dependency graph and in WorkflowManager. Seems like we should be able to drop one.
- [ ] Trigger workflowmanager schedule after a workflow job node completes
   - [ ] final_run_hook
     - [ ] at the end of task manager, only schedule workflowmanager if there are currently running workflow jobs without workflow job nodes in running, to handle cases where workflow job nodes were reaped, and thus final run hook didn't run.
     - [ ] get_workflow_job() and pass this id to .schedule
   - [ ] modify schedule to pass specific workflow job id to get_tasks to only consider that task
   - [ ] modify global lock to be specific to that workflow job
   - [x] get rid of the scheduled workflow manager task
   - [x] move timing out approval nodes out of workflow manager and only collect expired nodes https://github.com/ansible/awx/pull/12502/files

   - [ ] in task manager, when changing from pending to running for workflow job, start workflowmanager for that workflow job
     - [ ] to prevent specific workflowmanagers from conflicting with generalized workflowmanager, can use DB lock specific to that workflow job. So general WF manager should just skip if it cannot get the specific lock. The specific workflowmanager just bails if it cannot grab the lock. 
- [ ] Research if in WorkflowDAG if its better to do 3 queries to the workflow nodes or 1 query and filter in python using the django toolbar

### crazy idea section
- [ ] in final_run_hook, don't schedule workflow manager, instead just get a lock specific to that workflow job, and then execute the spawn_workflow_jobs() method in the same process that would normally run in a separate process
   -  the prevents situation where many workflowmanager are spawned at once
   - `WorkflowManager.spawn_workflow_graph_jobs(instance.get_workflow_job())`

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

**Comment by AlanCoding** [comment]
Can we close this?
