### ISSUE TITLE
AWX not reading submodule branch from .gitmodules file

### ISSUE THREAD

**Issue by ojc97** [ansible/awx#12465]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

AWX is defaulting to `origin/master` and ignoring the branch that is set inside .gitmodules. 

We are using a `main` branch and now a `master` branch so the git pull on a source control update continually fails with:
```
TASK [update project using git] ************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to determine hashes of submodules", "rc": 128, "stderr": "fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\nfatal: run_command returned non-zero status for api\n.\n", "stderr_lines": ["fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.", "Use '--' to separate paths from revisions, like this:", "'git <command> [<revision>...] -- [<file>...]'", "fatal: run_command returned non-zero status for api", "."], "stdout": "Entering 'api'\norigin/master\n", "stdout_lines": ["Entering 'api'", "origin/master"]}
```

### AWX version

21.1.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.12.4

### Operating system

Mac OS 12.4

### Web browser

Safari

### Steps to reproduce

Run a source control update on a git repo with a submodule configured that has a branch set.

### Expected results

source control should pull the submodule branch that has been specified in `.gitmodules`. 

### Actual results

Attempts to pull `origin/master` instead although this is not explicitly set anywhere.

**Comment by shanemcd** [comment]
Maybe related to https://github.com/ansible/awx/issues/12293

**Comment by ojc97** [comment]
Closing as duplicate of #77978 and #12293
