### ISSUE TITLE
Workflow Job with prompt credentials/inventory

### ISSUE THREAD

**Issue by maerlynn** [ansible/awx#1246]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When trying to add a Job inside a workflow with defaults values on Credentials and/or Inventory but with "Prompt on launch" box checked, i'm unable to save the new job to the workflow.

##### ENVIRONMENT
* AWX version: 1.0.2.92
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: CentOS
* Web Browser: FireFox

##### STEPS TO REPRODUCE

- Create a Job Template with some values for Inventory and Credential.
- Use the prompt on launch for either one or both.
- Create a Workflow Template and use the Editor.
- Job appears correclty when adding a new node and Credentials/Inventory prompt appears as well.
- Save the job.
- Close the Editor and restart it.

##### EXPECTED RESULTS

- Node saved.

##### ACTUAL RESULTS

- Node is not saved.

##### ADDITIONAL INFORMATION

When using the Firefox console, i got this error:

TypeError
columnNumber: 120535
fileName: "http://{My_Server_IP}/static/js/app.6a18453400d5f884d433.js"
lineNumber: 29
message: "params.node.unifiedJobTemplate.summary_fields.credential is undefined"

The documentation only state that : "Job templates with promptable credential and/or inventory, WITHOUT defaults, will not be available for inclusion in a workflow." But even with defaults values on those fields, i'm not able to add a node.

**Comment by awithrow9** [comment]
@maerlynn Can you retest with the latest?

**Comment by maerlynn** [comment]
Testing this today.

**Comment by maerlynn** [comment]
AWX Version : 1.0.4.91

Still not saving the job when using credentials and inventory with Prompt on launch.

**Comment by wenottingham** [comment]
Apologies, but there have been many fixes around these prompts in recent releases. Please try with 1.0.6+?

**Comment by matburt** [comment]
No follow up in several months
