### ISSUE TITLE
ERROR! couldn't resolve module/action 'community.general.telegram'

### ISSUE THREAD

**Issue by fnke752f** [ansible/awx#12469]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

![擷取](https://user-images.githubusercontent.com/108516166/177445904-c0f370ce-6099-4a5e-ac5e-56697a770bf2.PNG)

### AWX version

AWX 21.2.0 

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

ansible 2.10.8

### Operating system

ubuntu22.04 LTSa

### Steps to reproduce

- name: telegram notification
  community.general.telegram:
     token: '{{token}}'
     api_args:
      chat_id: "{{chat_id}}"
      parse_mode: "markdown"
      text: "[Hotok-]\n：develop\nIP    ：{{ ansible_default_ipv4.address }}\n：{{ Web_git_uri }}\n版本：{{Web_version}}\n"
      disable_web_page_preview: True
      disable_notification: True

### Expected results

no error

### Actual results

ERROR! couldn't resolve module/action 'community.general.telegram'. This often indicates a misspelling, missing collection, or incorrect module path.

**Comment by akus062381** [comment]
@fnke752f The awx-ee contains the collections and dependencies needed for supported AWX features to function. Anything beyond that will require you to build your own EE. For information on how to do that, see https://ansible-builder.readthedocs.io/en/stable/

Also just a heads up that the Ansible Community team is looking at building an EE that corresponds to [all of the collections inside the ansible package](https://github.com/ansible-community/ansible-build-data/blob/main/6/ansible.in). That may help you if and when it happens.
