### ISSUE TITLE
Get the error "Collection and role syncing disabled" even though related variables are set on

### ISSUE THREAD

**Issue by avalou** [ansible/awx#12463]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

AWX does not seem to take into account two variables (`AWX_ROLES_ENABLED` and `AWX_COLLECTIONS_ENABLED`) that should be set in `settings/jobs/details`. I tried to set them manually in the textbox "Extra Environment Variables", but it did not change anything.  
I am not sure this is a bug or only myself missing something ?

### AWX version

Ansible AWX 21.0.1.dev166[...]

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [x] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.12.5

### Web browser

Firefox, Chrome

### Steps to reproduce

* Write a complete playbook that imports roles from Gitlab as source control manager
* Setup project with newly created playbook as source
* Setup job template with this project
* Launch newly created job template
-> the error happens when AWX updated its sources from the scm.

### Expected results

`Source Control Update` job related to the playbook to update every roles imported from Gitlab.

### Actual results

```
TASK [debug] *******************************************************************
task path: /runner/project/project_update.yml:173
ok: [localhost] => {
    "msg": "Collection and role syncing disabled. Check the AWX_ROLES_ENABLED and AWX_COLLECTIONS_ENABLED settings and Galaxy credentials on the project's organization.\n"
}
```

### Additional information

I use an execution environment that I build with ansible-builder.

**Comment by john-westcott-iv** [comment]
Hello, thank you for your report.

The `Collection and role syncing disabled` is generated if both AWX_COLLECTIONS_ENABLED and AWX_ROLES_ENABLED are set too false and the project sync attempts to perform a sync the roles.

Note: this is not an error from the playbook, just a message indicating why the roles were not synced.

In your settings, are those options both False? That should be the only time you see this message.

These are AWX level settings (they can't be added to a job template or project or anywhere else). When you said you added them to "Extra Environment Variables" is that the one on the same job setting page? If so, they will have no affect here; instead, inside the environment your playbook is run in you would see the two environment variables set but they would not affect the project update job. 

Please let me know if this helps clarify what is happening on your system and if you have any follow up questions.

**Comment by avalou** [comment]
Hello and thanks for the answer.

I thought it was an error since the two tool boxes, `Enable collection(s) download` and `Enable role download` (in page #/settings/jobs/edit), are checked on. I got that these variables are not to be set in a playbook. And yes when I said I added these variables in the text box `Extra Environment Variables`, I meant in the same page (`#/settings/jobs/edit`). This is what I added:

```
{
  "AWX_ROLES_ENABLED": "true",
  "AWX_COLLECTIONS_ENABLED": "true"
}
```

Sadly it does not clarify much, I do not know what to do to solve this situation.

**Comment by john-westcott-iv** [comment]
If the checkboxes are turned on then downloading should be enabled. If you go to /api/v2/settings/jobs/ can you confirm that you see:
```
    "AWX_ROLES_ENABLED": true,
    "AWX_COLLECTIONS_ENABLED": true,
```

**Comment by kastyle** [comment]
@avalou 
I faced the same issue, AWX ROLES ENABLED and AWX_COLLECTIONS ENABLED = true.
The solution was to add to (Access > Organizations > your organization) the value Galaxy Credentials = Ansible Galaxy

**Comment by avalou** [comment]
@john-westcott-iv : yes both variables are on :
```
    "AWX_TASK_ENV": {
        "AWX_ROLES_ENABLED": "true",
        "AWX_COLLECTIONS_ENABLED": "true"
    },
 ```
 
 @kastyle : it seems that was it. Thanks a lot !

**Comment by Vesperino** [comment]
Try add galaxy credential to organization of project you have should fix it
