### ISSUE TITLE
Allow user to see the status of content signature verification

### ISSUE THREAD

**Issue by djyasin** [ansible/awx#12482]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature Summary

As a user I want to know if content signature verification is successful

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Acceptance Criteria 
Ensure that all new features in the api are also available in the cli.

**Comment by TheRealHaoLiu** [comment]
in project update if the content signature validation fail the project sync will fail and user can see the content signature validation failure in the project sync job log

**Comment by thenets** [comment]
Implemented and tested.

cc: @InnocentK @jneedle
