### ISSUE TITLE
[UI] Display content verification status for projects

### ISSUE THREAD

**Issue by djyasin** [ansible/awx#12484]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature Summary

As a user I want to be able to see content verification status for projects in the UI.

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

**Comment by mabashian** [comment]
Marking as blocked until some api changes land

**Comment by mabashian** [comment]
@djyasin what's the status on this one?  Is this still on your radar short term?

**Comment by djyasin** [comment]
Hi @mabashian! I am actually not 100% sure if we want this functionality based on the behavior changes in the API. I'm going to ping @TheRealHaoLiu here to confirm.

**Comment by djyasin** [comment]
This issue is no longer needed with our revised functionality.
