### ISSUE TITLE
Perform content integrity verification before running playbook

### ISSUE THREAD

**Issue by djyasin** [ansible/awx#12487]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature Summary

As a user i want the job run to fail if the playbook has been tampered with

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Acceptance Criteria 
Ensure that all new features in the api are also available in the cli.

**Comment by TheRealHaoLiu** [comment]
if content signature validation fail during project sync user will not be able to launch the job from the job template

**Comment by thenets** [comment]
Implemented and tested.

cc: @InnocentK @jneedle
