### ISSUE TITLE
content signing and verification utility

### ISSUE THREAD

**Issue by djyasin** [ansible/awx#12488]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature Summary

content signing and verification utility `ansible-sign`

the utility will provide a unified way to sign content across the ansible eco-system 

in the first iteration the utility will start with signing and verifying "projects"

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [x] CLI
- [ ] Other

**Comment by djyasin** [comment]
Have not come to a final decision with stakeholders within the organization for where this utility should live.

**Comment by TheRealHaoLiu** [comment]
decision has been reached in https://issues.redhat.com/browse/AAP-4954

we will be creating a new utility tentatively named `ansible-sign` 
in current release this utility will ONLY handle project signing

**Comment by TheRealHaoLiu** [comment]
https://github.com/ansible/ansible-sign is now functional thanks @relrod 
i think we achieved the desire functionality 

@relrod u mention that there's additional improvement you want to make can u outline what improvement is needed

**Comment by thenets** [comment]
`ansible-sign` tested by @relrod (thank you, man!)
AWX was also tested.

cc: @InnocentK @jneedle
