### ISSUE TITLE
Can't clone project from self-hosted gitlab instance

### ISSUE THREAD

**Issue by e36Alex** [ansible/awx#12499]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hello,

i created the gitlab credentials and project following exactly this tutorial after a fresh docker-build of awx:
https://baptiste.bouchereau.pro/tutorial/setup-awx-with-gitlab/

At the first sync of the project i just get an error.

### AWX version

21.2.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.12.7

### Operating system

Debian 11

### Web browser

Safari

### Steps to reproduce

Following this tutorial:
https://baptiste.bouchereau.pro/tutorial/setup-awx-with-gitlab/

### Expected results

Sync of the ansible-repo of gitlab

### Actual results

This error message / output:
`ERRO[0256] Unmounting /var/lib/containers/storage/overlay/ecc3cf4ffa81e2b65b82c07c9746a2cd55f7cf870c956bee72ac2f75dd839cc0/merged: invalid argument 
1
ERRO[0257] Preparing container 779358eb7d13b579b910d4f0605b474cf0e013ba57b0bfc9839d040196b78196: /usr/bin/slirp4netns failed: "open(\"/dev/net/tun\"): No such file or directory\nWARNING: Support for seccomp is experimental\nWARNING: Support for IPv6 is experimental\nchild failed(1)\nWARNING: Support for seccomp is experimental\nWARNING: Support for IPv6 is experimental\n" 
2
Error: error mounting storage for container 779358eb7d13b579b910d4f0605b474cf0e013ba57b0bfc9839d040196b78196: creating overlay mount to /var/lib/containers/storage/overlay/ecc3cf4ffa81e2b65b82c07c9746a2cd55f7cf870c956bee72ac2f75dd839cc0/merged, mount_data="lowerdir=/var/lib/containers/storage/overlay/l/GTU3LOOP7T26WNDM7MSVVEQJMS:/var/lib/containers/storage/overlay/l/4SZKNQ5JGLHSHNLIYNWXZIJETT:/var/lib/containers/storage/overlay/l/SZ2RW4Z55MEDJFZ6UQ2CMH6TO2:/var/lib/containers/storage/overlay/l/RD4RQOQNMSSML7DPWVK5NGT2RP:/var/lib/containers/storage/overlay/l/QILUL2TROF522GWMICLPTQOO2O:/var/lib/containers/storage/overlay/l/F4CFRHJCF4LVNL3YJN5QTLEFUM:/var/lib/containers/storage/overlay/l/7VCTVWFHP5L5DT4LAC55H235BN:/var/lib/containers/storage/overlay/l/3SMEVP7BIXDUMFUBC2PU22QVPP:/var/lib/containers/storage/overlay/l/QBBF3O6RILNGL6MGIHI3SHWEEN:/var/lib/containers/storage/overlay/l/H454JNUJXKRPKONVFZQKFEXGRO:/var/lib/containers/storage/overlay/l/SZIOGUCL74IEHTPJJ3EUSXIR7V:/var/lib/containers/storage/overlay/l/LQDA…
3
fuse-overlayfs: cannot mount: No such file or directory
4
: exit status 1`

**Comment by sarabrajsingh** [comment]
Hi @e36Alex - we only support running the development environment as per the instructions in this file - https://github.com/ansible/awx/blob/devel/tools/docker-compose/README.md

This appears to be an environment issue. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.

**Comment by e36Alex** [comment]
Thanks for your reply.
I could already solve the problem. It was on my docker installation in a lxc.
