### ISSUE TITLE
Issue with credential when launching a Job Template under Portal Mode

### ISSUE THREAD

**Issue by pipoe2h** [ansible/awx#1250]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

I have a job template with a credential based on a custom credential type. The different scenarios are:

- Launching from Portal Mode view
  - Job template with the credential as default and prompt disabled. Works okay
  - Job template with the no default credential and prompt enabled. Doesn't work, you can see the credential during the wizard and select it, but the "next" button doesn't turn green. If I choose the demo credential (machine type) along with the new credential (new credential type), the "next" button turns green.

- Launching from Templates view
  - Job template with the no default credential and prompt enabled. Works okay. The "next" button is always green even if you don't choose any credential.

##### ENVIRONMENT
* AWX version: 1.0.3.44
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: n/a
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Create a new credential types. I have used the example here [http://docs.ansible.com/ansible-tower/latest/html/userguide/credential_types.html](http://docs.ansible.com/ansible-tower/latest/html/userguide/credential_types.html)

2. Add a new credential using the credential type previously created.

3. Create a template with no default credential but enabling the prompt.
![awx error - templates view](https://user-images.githubusercontent.com/17649319/36212484-f8c32654-119b-11e8-860d-c294d2d8a568.png)

4. Launch the template through the Portal Mode view.

5. Select your new credential. At this point, the "next" button should turn green but it doesn't.
![awx error - portal mode view](https://user-images.githubusercontent.com/17649319/36212618-4d93c95e-119c-11e8-983b-8ecad115451e.png)

6. Add the default credential (machine type). With both credentials you will see the "next" button turning green.
![awx error - portal mode view demo credential](https://user-images.githubusercontent.com/17649319/36212701-91f53786-119c-11e8-9468-638c0b111907.png)

7. If you repeat from step 4 but on the Templates view, the process works okay.

##### EXPECTED RESULTS

After select the credential (based on a new credential type) the "next" button should turn green.

##### ACTUAL RESULTS

The next button doesn't turn green to continue.

**Comment by jaredevantabor** [comment]
This is fixed in devel.
