### ISSUE TITLE
Alter SAML adapter to not remove system admin and system auditor flags

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#12519]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature Summary

In the awx setting SOCIAL_AUTH_SAML_USER_FLAGS_BY_ATTR add a property like `remove_superuser` which would behave like the `remove_admins` in the team mapping; preventing users granted the superuser role through the UI from having that flag removed from their user. A smilier option for `remove_auditors` would also be present. 

### Select the relevant components

- [ ] UI
- [X] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

**Comment by jay-steurer** [comment]
Verified by QE. Approved.
