### ISSUE TITLE
AWX fail when i send files from localhost to remote host using synchronize module and sshpass command

### ISSUE THREAD

**Issue by RootKaizer** [ansible/awx#12518]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Greetings AWX development team

I want to report a bug that I have not found a solution on your platform or on the web.

The bug was reported as ID #3806 in 2019.
The development team reported that it was a bug in ansible and not in AWX, however the tests I carried out show the opposite, because when I run a playbook with the synchronizer module by AWX it fails due to permissions when transferring the file (rc:23 ), but if I run it with Ansible from my server the playbook runs successfully.

I did the test with AWX versions 17.1.0 and 21.2.0 but in both cases I got the same error. my execution playbook is as follows:

---
- name: Copy Backup folder
  hosts: '{{ HOSTS }}'
  tasks:
    - name: Transfer RMAN backup folder from localhost to '{{ HOSTS }}'
      synchronize:
        src: "{{ PATH_BACKUP_FILE }}"
        dest: "{{ APP_DIR }}/ansible-deploy/RmanBackup/Backup_Rman.sh"

Answer from AWX:
"msg": "Warning: Permanently added '10.60.70.85' (ECDSA) to the list of known hosts.\r\nrsync: change_dir \"/app/ansible-engine/client_conf/operations_deploy/base_de_datos/metodo_de_RMAN/backup\" failed: No such file or directory (2)\nrsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1189) [sender=3.1.3]\n",
  "rc": 23,

I also tried to use the shell module where I sent the password of the target user, but it also fails with code rc:23

---
- name: Copy Backup folder
  hosts: '{{ HOSTS }}'
  tasks:
    - name: Transfer RMAN backup folder from localhost to '{{ HOSTS }}'
      command: sshpass -d3 /usr/bin/rsync --delay-updates -F --compress --archive --rsh=/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null --out-format=<<CHANGED>>%i %n%L /app/ansible-engine/client_conf/operations_deploy/database/RMAN_method/backup/Backup_OPC_Rman_v2.sh oracle@##.##.##.85: /home/oracle/ansible-deploy/RmanBackup/Backup_Rman.sh
      delegate_to: 127.0.0.1

I want to know how AWX works to transfer files between the AWX server and the managed servers, since this functionality is the core of our work.

Thank you very much for your support

### AWX version

17.1.0 and 21.2.0

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Ansible version

2.9

### Operating system

7.9

### Web browser

Chrome

### Steps to reproduce

Run playbook with AWX >> answer is fail
Run playbook with ansible >> answer is OK

Playbook:
---
- name: Copy Backup folder
  hosts: ##.##.##.85
  tasks:
    - name: Transfer RMAN backup folder from localhost to ##.##.##.85
      synchronize:
        src: /app/ansible-engine/client_conf/operations_deploy/base_de_datos/metodo_de_RMAN/backup/Backup_OPC_Rman_v2.sh
        dest: /app/ansible-deploy/RmanBackup/Backup_Rman.sh

### Expected results

/app/ansible-engine/client_conf/operations_deploy/base_de_datos/metodo_de_RMAN/backup/Backup_OPC_Rman_v2.sh file sends to ##.##.##.85 hosts like as /app/ansible-deploy/RmanBackup/Backup_Rman.sh

### Actual results

Don´t send file

**Comment by shanemcd** [comment]
Does `/app` actually exist within the container? Or are you trying to access files on the host machine?

**Comment by john-westcott-iv** [comment]
In newer versions of AWX we use execution environments (containers) to run the automation in. These containers don't have access to the hosts filesystem unless specifically granted through:
  Settings => Job Settings => Paths to expose to isolated jobs
Try exposing your /app directory through that setting and let us know if that works for you or not.

**Comment by akus062381** [comment]
Hi @RootKaizer!

Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
