### ISSUE TITLE
host details > jobs don't show pending jobs

### ISSUE THREAD

**Issue by azrdev** [ansible/awx#12515]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

GUI > Hosts > Jobs and   Inventories > Hosts > Jobs  don't show pending jobs, only(?) finished ones.

### AWX version

19.5.1

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Web browser

Firefox

### Steps to reproduce

1. Create a project with a playbook and roles/collections in requirements.yml (so the project sync takes some time)
2. create a template for said playbook, and execute it on some host
3. shortly after, open/refresh the host details of said host and go to "Jobs"

### Expected results

the pending job to be listed

### Actual results

I see only successful and failed jobs, but not pending ones.

**Comment by fosterseth** [comment]
@azrdev Hi, pending jobs are not yet aware of the hosts that it will eventually run against (inventory can be dynamic), thus hosts are only linked to a job after the job is finished running.

therefore, this UI component is designed to only show completed jobs.
