### ISSUE TITLE
Credential type for containing GPG public key

### ISSUE THREAD

**Issue by djyasin** [ansible/awx#12536]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature Summary

As a user, I want to be able to select credential type for content verification. 
credential for the type is use for validating content signature during project sync.

Acceptance Criteria:
- Provide content type that allow user to store PGP public key
- content type must be added automatically on install and upgrade
- content type must be of kind "cryptography" (as agreed upon by UI/API team members)
- credential can be pass into project update when associated to the project

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

**Comment by TheRealHaoLiu** [comment]
@AlexSCorey can u post a example query from UI

**Comment by mabashian** [comment]
@TheRealHaoLiu is https://github.com/ansible/awx/issues/12483 tracking the UI side of this?  Can we remove the ui label from this issue?

**Comment by AlexSCorey** [comment]
@TheRealHaoLiu Here is the query for getting the proper credential type `ttps://192.168.0.2:3001/api/v2/credential_types/?kind=scm` and here is the query for getting the credentials of the type we want `/api/v2/credentials/?credential_type=2&order_by=name&page=1&page_size=5`
