### ISSUE TITLE
JobOutput: events not sent over websockets from some nodes

### ISSUE THREAD

**Issue by keithjgrant** [ansible/awx#12539]
##### ISSUE TYPE
 - Bug

##### COMPONENT NAME
 - API

##### SUMMARY
The JobOutput screen doesn't update as a job runs if the browser is connected to a different node than the node running the job. Most likely caused because websockets are not being sent. Job events display normally if the page is refreshed

See https://github.com/ansible/awx/issues/12232#issuecomment-1152063448

**Comment by anxstj** [comment]
I experienced this problem with AWX 21.1, but after the upgrade to AWX 21.2, it didn't appear again.
