### ISSUE TITLE
JobOutput scrolling to bottom doesn't stay at bottom

### ISSUE THREAD

**Issue by keithjgrant** [ansible/awx#12540]
##### ISSUE TYPE
 - Bug

##### COMPONENT NAME
 - UI

##### SUMMARY
Scrolling all the way to the bottom (via scrollbar or "scroll to bottom" button) usually doesn't stay at the bottom once the job output loads in. This is due to the fact we don't know the exact length of the job output and are relying on react-virtualized to calculate the expected height of all output.

As a workaround, we might be able to detect when the user has scrolled to the bottom, and automatically scroll again once the output loads

**Comment by keithjgrant** [comment]
while working on #12232, I realized this can be fixed fairly easily by using the existing "follow output" functionality, so I'll get this in the same PR

**Comment by InnocentK** [comment]
Resolved
