### ISSUE TITLE
Job output scroll position is off after events refresh

### ISSUE THREAD

**Issue by keithjgrant** [ansible/awx#12556]
##### ISSUE TYPE
 - Bug or Docs Fix

##### COMPONENT NAME
 - UI

##### SUMMARY
When a job finishes running, the events on the job output page are refreshed from the API to ensure displayed output is fully in sync. However, after this happens, the output generally doesn't scroll back to the same location the user was viewing beforehand.

We can either:
a) keep better track of the scroll position prior to the refresh and ensure we scroll back to that position and stay there as events load, or
b) re-think this full refresh idea, and only fetch specific events that may be missing in the browser view

Option _b)_ could probably be done in conjunction with #12543

**Comment by InnocentK** [comment]
Resolved via option _b)_ (along with https://github.com/ansible/awx/issues/12543) by the work completed in https://github.com/ansible/awx/pull/12689
