### ISSUE TITLE
Mixed languages when creating credentials (Spanish & English)

### ISSUE THREAD

**Issue by e-minguez** [ansible/awx#1256]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Using Tower latest release, the new credential form shows "Usuario" and "Contraseña" and everything else is in English.

##### ENVIRONMENT
* AWX version: ansible-tower-ui-3.2.2-1.el7.x86_64
* AWX install method: setup.sh
* Ansible version:  ansible 2.4.2.0
* Operating System: RHEL 7.4
* Web Browser: Chrome Version 64.0.3282.140 (Official Build) (64-bit)
* User Agent (just in case): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36

##### STEPS TO REPRODUCE
Go to "Settings" -> "Credentials" -> "Create Credential"

##### EXPECTED RESULTS
Show everything in English or Spanish, not mixed.

##### ACTUAL RESULTS
![screenshot from 2018-02-15 10-49-02](https://user-images.githubusercontent.com/346758/36250369-dcfe66b6-123d-11e8-9d59-259c599ad3c9.png)

**Comment by awithrow9** [comment]
Let's double check that this is properly marked for translation.

**Comment by aoyawale** [comment]
i'll start fixing this once we have the system we are going to use for translation.

**Comment by ryanpetrello** [comment]
Believe this is resolved now.  Please reopen if you're still seeing it.
