### ISSUE TITLE
[Feature request] Node Type support limit in Workflow_job

### ISSUE THREAD

**Issue by But4ler** [ansible/awx#12570]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Hello,
Currently, it is not possible to set a limit on the workflow_jobs.
It's only possible at the workflow level itself, or at the template level.

So you have to multiply the same templates or just the desired limit changes.
Example use case:
The same playbook is used to update different environments (integration, prp, prod).
We run this template on the next environment, only if the previous one is successful (ITG -> PRP -> PROD)

![image](https://user-images.githubusercontent.com/15019378/180953429-9c82a401-4503-412d-93bc-3c672ca063b9.png)

Adding a limit in the "node type" would bring a lot of flexibility 

![image](https://user-images.githubusercontent.com/15019378/180953941-8cd7edb6-aac1-4bc3-9773-26fb58495b40.png)

Thanks !

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

**Comment by AlanCoding** [comment]
Resolved https://github.com/ansible/awx/pull/12875, if not earlier. Confirmed in current UI.

![Screenshot from 2022-12-20 15-48-46](https://user-images.githubusercontent.com/1385596/208763919-4356b3f1-080d-4dbf-9f5d-95dc6a784213.png)
