### ISSUE TITLE
[UI] Submit project form with content signature credential selected and source control credential empty

### ISSUE THREAD

**Issue by vedaperi** [ansible/awx#12589]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When a credential is selected for the new Content Signature Verification Credential field on the Project Form page and there is no interaction with the Source Control Credential field, the form won't submit. In order to submit the form with only a Content Signature Verification Credential selected and the Source Control Credential empty, it is necessary to open the Source Control Credential lookup and empty out the field.

### AWX version

devel/feature-project-integrity

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Steps to reproduce

1. Edit an existing Project
2. On the Forms Page, select a credential in the Content Signature Verification Credential field
3. Trying to click submit (the form won't actually submit)
4. Click on the lookup for the Source Control Credential field
5. Select a source control credential
6. Remove the credential by clicking the 'X' next to it
7. Exit the credential lookup view
8. Click submit (the form will submit this time)

### Expected results

The form should successfully submit by the third step when only a Content Signature Verification Credential is selected without requiring any interaction with the Source Control Credential field.

### Actual results

The form required interaction with the Source Control Credential field to explicitly clear it out before allowing the user to submit the form with only a Content Signature Verification Credential selected. Hence, steps 4 through 8.

### Additional information

https://user-images.githubusercontent.com/52008241/181621962-04c33976-9c71-4afd-acf4-2d64cfa4ac71.mov

**Comment by InnocentK** [comment]
Feature implemented and tested
cc: @thenets @jneedle
