### ISSUE TITLE
update role plugin to provide better error messages

### ISSUE THREAD

**Issue by sean-m-sullivan** [ansible/awx#12598]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Currently if the role plugin fails to find an object to assign a role to, it fails with a python error. If you are submitting for a team and 100 job templates and workflows, this is nigh unworkable to find out which one is missing. This should be fixed. 

### AWX version

21.3.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

minikube

### Modifications

no

### Steps to reproduce

Run roles module with a team/job template/workflow, something that doesn't exist. 
```
    - name: Set user to admin over inventory
      awx.awx.role:
        team: Service Provisioning
        role: execute
        lookup_organization: Default
        state: present
        job_templates:
          - Azure
        workflows:
          - Azure Nothing
```

### Expected results

 "Unable to find workflows with name: Azure Nothing"

### Actual results

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not subscriptable
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):
  File \"/home/excalibrax/.ansible/tmp/ansible-tmp-1659290592.3939743-111457-226432510653785/AnsiballZ_role.py\", line 107, in <module>
    _ansiballz_main()
  File \"/home/excalibrax/.ansible/tmp/ansible-tmp-1659290592.3939743-111457-226432510653785/AnsiballZ_role.py\", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/home/excalibrax/.ansible/tmp/ansible-tmp-1659290592.3939743-111457-226432510653785/AnsiballZ_role.py\", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.awx.awx.plugins.modules.role', init_globals=dict(_module_fqn='ansible_collections.awx.awx.plugins.modules.role', _modlib_path=modlib_path),
  File \"/usr/lib64/python3.10/runpy.py\", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File \"/usr/lib64/python3.10/runpy.py\", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File \"/usr/lib64/python3.10/runpy.py\", line 86, in _run_code
    exec(code, run_globals)
  File \"/tmp/ansible_awx.awx.role_payload_inqi3kj4/ansible_awx.awx.role_payload.zip/ansible_collections/awx/awx/plugins/modules/role.py\", line 307, in <module>
  File \"/tmp/ansible_awx.awx.role_payload_inqi3kj4/ansible_awx.awx.role_payload.zip/ansible_collections/awx/awx/plugins/modules/role.py\", line 272, in main
TypeError: 'NoneType' object is not subscriptable
", "module_stdout": "", "msg": "MODULE FAILURE
See stdout/stderr for the exact error", "rc": 1}

**Comment by sean-m-sullivan** [comment]
close?

**Comment by AlanCoding** [comment]
yes, thanks for the contribution
