### ISSUE TITLE
[UI] Disable job launch button on job templates page if content signature verification fails

### ISSUE THREAD

**Issue by vedaperi** [ansible/awx#12590]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature Summary

If a user sets up content signature verification to be required on a project, and the content signature verification fails, the user should not be able to launch the job from the Job Templates Page, as the button should be disabled. 

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

**Comment by kialam** [comment]
Blocked until API changes land.

**Comment by mabashian** [comment]
@djyasin https://github.com/ansible/awx/issues/12484#issuecomment-1234629258 same question on this one.  Has the work on the api side been completed?

**Comment by djyasin** [comment]
This issue is no longer needed with our revised functionality.

**Comment by steelducky** [comment]
Can someone explain what functionality was revised? Because I still can't prevent job relaunches if the content signature verification fails. I don't want a job using admin credentials to run with different functionality because someone pushed new code in our repo.
