### ISSUE TITLE
svn command is missed in the awx_task image

### ISSUE THREAD

**Issue by gripenk** [ansible/awx#126]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT

 - Installer

##### SUMMARY

No svn command included in the docker image

##### STEPS TO REPRODUCE

Under "New Project" -> "choose an SCM Type" -> select "Subverion", input the correct URL, credential. But it failed to do "SCM update"

##### ADDITIONAL INFORMATION

Although we can use docker exec yum -y install subversion to inject the svn binary. The docker image should include all external binaries it will call

**Comment by matburt** [comment]
Can you show me the output of the project update run?

**Comment by gripenk** [comment]
image version is  awx_task:1.0.0.312 

OUTPUT of SCM Update 

Using /etc/ansible/ansible.cfg as config file

PLAY [all] *********************************************************************

TASK [delete project directory before update] **********************************
skipping: [localhost]

TASK [update project using git and accept hostkey] *****************************
skipping: [localhost]

TASK [Set the git repository version] ******************************************
skipping: [localhost]

TASK [update project using git] ************************************************
skipping: [localhost]

TASK [Set the git repository version] ******************************************
skipping: [localhost]

TASK [update project using hg] *************************************************
skipping: [localhost]

TASK [Set the hg repository version] *******************************************
skipping: [localhost]

TASK [update project using svn] ************************************************
skipping: [localhost]

TASK [Set the svn repository version] ******************************************
skipping: [localhost]

TASK [update project using svn with auth] **************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to find required executable svn in paths: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1

**Comment by matburt** [comment]
Fixed in #155
