### ISSUE TITLE
generate install bundle for adding remote execution node

### ISSUE THREAD

**Issue by TheRealHaoLiu** [ansible/awx#12612]
## Summary
As a user that want to add a remote execution node, I want AWX to generate a bundle of "Ansible goodness" (playbook with all the required variables) that I can use to easily provision a remote execution node and have AWX able to connect to the new remote execution node.

## Acceptance Criteria 
- [ ] install bundle must setup the correct TLS certificate for establishing connection between AWX control node and the targeted remote execution node.
- [ ] install bundle must setup the correct work-sigining to receive work from AWX controlplane
- [ ] at the end we should end up with a remote execution node that can receive and execute job from AWX controlplane

**Comment by TheRealHaoLiu** [comment]
the command for generating certificate for receptor 
```
receptor --cert-makereq bits=2048 commonname=$hostname dnsname=$hostname nodeid=$hostname outreq=/etc/receptor/tls/receptor.req outkey=/etc/receptor/tls/receptor.key

receptor --cert-signreq req=/etc/receptor/tls/receptor.req cacert=/etc/receptor/tls/ca/receptor-ca.crt cakey=/etc/receptor/tls/ca/receptor-ca.key outcert=/etc/receptor/tls/receptor.crt verify=yes
```

**Comment by fosterseth** [comment]
@shanemcd to make the certs the awx-web container would need the receptor binary present in the container. Are we okay doing that?

**Comment by TheRealHaoLiu** [comment]
mocked instance install bundle download endpoint PR merged into feature branch 
https://github.com/ansible/awx/pull/12643
behavior revised in 
https://github.com/ansible/awx/pull/12679

**Comment by CFSNM** [comment]
We are blocked to test until https://issues.redhat.com/browse/AAP-5543 and https://github.com/ansible/tower/issues/6081 are done

**Comment by CFSNM** [comment]
Validated from QE side. Closing
