### ISSUE TITLE
Allocate capacity for isolated controller jobs

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1262]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY

Sort of a bughancement. We don't currently allocate capacity for controller nodes controlling isolated jobs.

Notes from @AlanCoding:

There are 2 types of activities that have a hypothetical task impact

    job-related management playbooks
    the isolated heartbeat task

for those scenarios, we have 2 things to consider

    blocking the run of the task if there is insufficient capacity (I'll call "blocking")
    adding the action's task impact to consumed_capacity (I'll call "consuming")

For a rundown of what would be relatively easy to do - I have a concrete idea of how to do blocking for the heartbeat, and a concrete idea of how to do consuming for the job-related management tasks. The reverse (consuming in the heartbeat, blocking for jobs) would be relatively difficult, risking some hazards with the task manager.

##### ENVIRONMENT
* AWX version: current

**Comment by shanemcd** [comment]
RIP isolated nodes.
