### ISSUE TITLE
Many processes in defunct

### ISSUE THREAD

**Issue by boagg** [ansible/awx#12628]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hello,

It seems that the version of podman which is used in the current releases is impacted by the following bug: 

https://github.com/containers/podman/issues/13779

When version 4.2 of podman is released, can the version upgrade be possible?

Instead of podman, can we use the old binary (docker) used by EE?

Thank you in advance for your feedback

### AWX version

21.3.0 / 21.2.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.9

### Operating system

Debian 11

### Web browser

Firefox, Chrome

### Steps to reproduce

Normal use

### Expected results

I expect not to have defunct processes

### Actual results

Many processes in defunct

**Comment by akus062381** [comment]
Hi @boagg,

As soon as the fix is available in an RPM for Podman, we will consume it as a part of our daily build process. Thanks for your patience.
