### ISSUE TITLE
Error UI in docker

### ISSUE THREAD

**Issue by RemiZOffAlex** [ansible/awx#12631]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

After start

```
MAIN_NODE_TYPE=control COMPOSE_TAG=devel make docker-compose
```

In browser https://127.0.0.1:8043/ or https://localhost:8043/

```
<% if (process.env.NODE_ENV === 'production') { %> <% } %> <% if (process.env.NODE_ENV === 'production') { %> <% } else { %> <% } %> <% if (process.env.NODE_ENV === 'production') { %>
```

### AWX version

devel

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

devel

### Operating system

Fedora 36

### Steps to reproduce

```
git clone https://github.com/ansible/awx
cd awx
MAIN_NODE_TYPE=control COMPOSE_TAG=devel make docker-compose
```

In browser https://127.0.0.1:8043/ or https://localhost:8043/

### Expected results

AWX start page

### Actual results

In browser https://127.0.0.1:8043/ or https://localhost:8043/

```
<% if (process.env.NODE_ENV === 'production') { %> <% } %> <% if (process.env.NODE_ENV === 'production') { %> <% } else { %> <% } %> <% if (process.env.NODE_ENV === 'production') { %>
```

**Comment by sarabrajsingh** [comment]
Hi [RemiZOffAlex](https://github.com/RemiZOffAlex),

Please refer to the following documentation to build and generate the UI in the development environment.

https://github.com/ansible/awx/tree/devel/tools/docker-compose#clean-and-build-the-ui

Thanks,
AWX Team

**Comment by RemiZOffAlex** [comment]
```
$ docker exec tools_awx_1 make clean-ui ui-devel
rm -rf node_modules
rm -rf awx/ui/node_modules
rm -rf awx/ui/build
rm -rf awx/ui/src/locales/_build
rm -rf awx/ui/.ui-built
NODE_OPTIONS=--max-old-space-size=6144 npm --prefix awx/ui --loglevel warn ci
npm ERR! code ETIMEDOUT
npm ERR! syscall connect
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/yocto-queue/-/yocto-queue-0.1.0.tgz failed, reason: connect ETIMEDOUT 104.16.19.35:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/lib/awx/.npm/_logs/2022-08-11T20_56_51_346Z-debug-0.log
make: *** [Makefile:381: awx/ui/node_modules] Error 1
```

**Comment by DE110283** [comment]
Any findings / solutions for this network request to https://registry.npmjs.org/yocto-queue/-/yocto-queue-0.1.0.tgz issue?
