### ISSUE TITLE
forms with codemirror - save button should be disabled on detection of invalid yaml / json input 

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1264]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

We do not update save button status based on valid/invalid input.

##### ENVIRONMENT
* AWX version: current

##### STEPS TO REPRODUCE

- **[1]** go to `/#/inventories/smart/add`
- **[2]** fill out required fields
- **[3]** add invalid input to `Variables` field
- **[4]** remove invalid input from `Variables` field

##### EXPECTED RESULTS

- **[1]** save button is disabled
- **[2]** save button is enabled
- **[3]** save button is disabled
- **[4]** save button is enabled

##### ACTUAL RESULTS

- **[1]** save button is disabled ✅
- **[2]** save button is enabled ✅
- **[3]** save button is disabled ❌
- **[4]** save button is enabled ✅

##### ADDITIONAL INFORMATION

Per @mabashian:

Took a look at what it would take to get this working... I'm not sure we can make this work without touching https://github.com/ansible/angular-codemirror#1.0.4 in some way. I was hoping that I could find some reference to the error on scope. If that's the case then maybe we can just watch for changes there and invalidate the form when we detect errors. I wasn't able to find reference to these errors on scope though.

**Comment by ryanpetrello** [comment]
Closing due to age and UI rewrite.
