### ISSUE TITLE
Problem send mail ansible tower

### ISSUE THREAD

**Issue by aleyamayab** [ansible/awx#12652]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I need help with sending an email through ansible tower , since when attaching my file it gives me an error:

 "rc": 1,
    "msg": "Failed to send mail: can't attach file /tmp/user/user_jira_test.csv: [Errno 2] No such file or directory: '/tmp/user/user_jira_test.csv'",
    "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_mail_payload_b522pb82/ansible_mail_payload.zip/ansible/modules/notification/mail.py\", line 370, in main\nFileNotFoundError: [Errno 2] No such file or directory: '/tmp/user/user_jira_test.csv'\n",

Apparently it can't find the file in the path I'm using.

To send the mail I am using an aws endpoint of the SES service as smtp

### AWX version

N/A

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

N/A

### Modifications

no

### Operating system

Linux

### Steps to reproduce

  tasks:

  - name: Send e-mail to a bunch of users, attaching files
    mail: 
      host: email-smtp.eu-west-1.amazonaws.com
      port: xxxx
      username: xxxxxx
      password: xxxxx
      subject: Ansible-report-test
      body: Hello, this is an e-mail. I hope you like it ;-)
      from: nivel1soporte@domiand.com (Soporte Nivel 1)
      to:
      - alejandro bonilla <alejandro.bonilla@domiand>
      attach:
      - /tmp/user/user_jira_test.csv
      headers:
      - Reply-To=alejandro.bonilla@domiand.com
      - X-Special="Something or other"
      charset: us-ascii
    delegate_to: localhost

### Expected results

Send Mail

### Actual results

"rc": 1,
    "msg": "Failed to send mail: can't attach file /tmp/user/user_jira_test.csv: [Errno 2] No such file or directory: '/tmp/user/user_jira_test.csv'",
    "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_mail_payload_b522pb82/ansible_mail_payload.zip/ansible/modules/notification/mail.py\", line 370, in main\nFileNotFoundError: [Errno 2] No such file or directory: '/tmp/user/user_jira_test.csv'\n",

**Comment by akus062381** [comment]
Hi @ayamayab, this appears to be less of a bug report or feature request and more of a question. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.
