### ISSUE TITLE
Workflow Template - Convergence reverting to `ANY` on edit of step

### ISSUE THREAD

**Issue by whitej6** [ansible/awx#12651]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When creating a workflow template that has more than one job template converging on to the next step with the convergence set to `ALL` does not persist if the converged task is editing. Upon edit the converge task will default back to `ANY` and must be set on every edit.

### AWX version

AWX 21.4.0 

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

When creating a workflow template that has more than one job template converging on to the next step with the convergence set to `ALL` does not persist if the converged task is editing. Upon edit the converge task will default back to `ANY` and must be set on every edit.

### Expected results

Convergence should not have to be set back to `ALL` on every edit of the converged step.

### Actual results

Convergence must be set back to `ALL` on every edit of the converged step.

**Comment by mabashian** [comment]
Fixed by https://github.com/ansible/awx/pull/13693
