### ISSUE TITLE
Can Satellite 6.10 and AWX 20.1.0 integration??

### ISSUE THREAD

**Issue by CC-Kuoying** [ansible/awx#12665]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Is it possible that red hat satellite 6.10 and AWX 6.10.3 integration??

BTW, it is ok that Satellite 6.10 and Ansible Tower integration.

ref. https://www.redhat.com/en/blog/satellite-and-ansible-tower-integration-part-1-inventory-integration

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

**Comment by akus062381** [comment]
hi @CC-Kuoying, this issue pertains to an older version of AWX, which is no longer supported. Please try upgrading to the latest version and let us know if that resolves your issue. Thank you!

**Comment by CC-Kuoying** [comment]
Hi @akus062381 AWX Version is 20.1.0.

<img width="843" alt="截圖 2022-08-17 下午11 30 10" src="https://user-images.githubusercontent.com/71488933/185180552-b30c79d8-92d9-4444-8d02-fc0ae002131e.png">

**Comment by CC-Kuoying** [comment]
Error message. 

```
ansible-inventory [core 2.12.4.post0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.12 (default, Sep 21 2021, 00:10:52) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
[WARNING]:  * Failed to parse /runner/inventory/foreman.yml with auto plugin:
HTTPSConnectionPool(host='satellite.cloudcube.local', port=443): Max retries
exceeded with url: /api/v2/status?page=1&per_page=250 (Caused by
SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed: self signed certificate in certificate chain
(_ssl.c:1131)')))
  File "/usr/local/lib/python3.8/site-packages/ansible/inventory/manager.py", line 290, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/inventory/auto.py", line 58, in parse
    plugin.parse(inventory, loader, path, cache=cache)
  File "/usr/share/ansible/collections/ansible_collections/theforeman/foreman/plugins/inventory/foreman.py", line 662, in parse
    self._populate()
    if self._use_inventory_report():
  File "/usr/share/ansible/collections/ansible_collections/theforeman/foreman/plugins/inventory/foreman.py", line 378, in _use_inventory_report
    result = self._get_json(status_url)
  File "/usr/share/ansible/collections/ansible_collections/theforeman/foreman/plugins/inventory/foreman.py", line 243, in _get_json
    ret = s.get(url, params=params, verify=self.get_option('validate_certs'))

```

**Comment by ffirg** [comment]
I think you just need to set under the Satellite Inventory source Variables:
```
---
validate_certs: false
```

**Comment by ffirg** [comment]
If that doesn't work try verify_ssl (can't remember which it is off the top of my head)

**Comment by CC-Kuoying** [comment]
Hi @ffirg it doesn't work. (BTW, I run AWX on Openshift)

<img width="1038" alt="截圖 2022-08-18 上午12 19 30" src="https://user-images.githubusercontent.com/71488933/185191474-61d9e041-6c97-4d7b-bb70-f742fda2b717.png">

**Comment by CC-Kuoying** [comment]
Hi @ffirg yes, it's ok.  Thanks.

```
---
validate_certs: false
```
