### ISSUE TITLE
RFE: store/display last login of user 

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1266]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

In theory, if we store and display the last login of the user, the user could notice if their creds were used without them.

Request is to store this info and display it... somewhere.

##### ENVIRONMENT
* AWX version: current

**Comment by wenottingham** [comment]
One option, on the dashboard next to user name.

**Comment by unlikelyzero** [comment]
I'll take a look at testing this ticket

**Comment by dsesami** [comment]
Verified that this shows correctly on user pages, and that it persists correctly through different tabs.
