### ISSUE TITLE
jobs are hanging 

### ISSUE THREAD

**Issue by jangel97** [ansible/awx#12662]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hi,

I am using Ansible Automation platform 2.2 and I can see jobs running for several minutes after they have been completed. 

In the controller logs I can see the following messages:
`awx.main.managers Detected inventory_update 95822 (running) running inside lost instance, may still be waiting for reaper.`

If I run the `awx-manage list_instances` the node is there, so I do not know why it is lost. 

It took many minutes to update to Successful.  
### AWX version

AAP 2.2

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

openshift

### Modifications

no

### Steps to reproduce

Happens randomly or I dont know when i thappens exactly

### Expected results

I would expect that when a job is done, it is marked as done.

### Actual results

randomly job is not done

**Comment by shanemcd** [comment]
Maybe related: https://github.com/ansible/awx/issues/12491

**Comment by jangel97** [comment]
Hi,
We are seeing this also for jobs. When this happens, the dispatcher reports that the job is running, the remote work unit exists and the container also exists on the exec node. But for some reason, the container is sitting there and not progressing, stdout remains the same for hours. 
Any updates? Any information we can provide that could be helpful?
Kind regards,
