### ISSUE TITLE
Only Hop and and Execution Nodes Should have `links` url in related

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#12678]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

All instances have a link in the UI response for the install bundle, however only Execution and hop nodes should have that link in the related tabs.  See https://github.com/ansible/awx/blob/feature-mesh-scaling/awx/api/views/instance_install_bundle.py#L28

### AWX version

devel

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Steps to reproduce

In api gui click on on `instances` and then click on a control node, or a hybrid node.  You will see that in `related` there is a link for the install bundle.  Click on that

### Expected results

The link should not even exist

### Actual results

An error is rendered.  In the UI when a request is made to this end point the page crashes with no error

### Additional information

![Screen Shot 2022-08-17 at 1 26 21 PM](https://user-images.githubusercontent.com/39280967/185203637-bfdab72c-45ed-4066-9ece-721616a5408c.png)
![Screen Shot 2022-08-17 at 1 26 12 PM](https://user-images.githubusercontent.com/39280967/185203640-ec181732-1397-4d86-934b-ef8114f4bc96.png)
![Screen Shot 2022-08-17 at 1 25 59 PM](https://user-images.githubusercontent.com/39280967/185203650-cd8a5af8-15d9-4322-9d1e-702aa622c031.png)

**Comment by jay-steurer** [comment]
PR is merged. Verified by QE. Closing it
