### ISSUE TITLE
Error when attempting to connect to Windows hosts on one domain

### ISSUE THREAD

**Issue by m-hoskin-unisa** [ansible/awx#12681]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

We've had AWX running for about 6 months without issue, and have been using it to run playbooks against both RHEL and Windows servers. In the past few weeks playbooks run against one of our Windows domains have been failing with a vague error that doesn't provide much in the way of troubleshooting information.

Are there any other troubleshooting steps I should try?

### AWX version

21.4.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Operating system

RHEL 7

### Steps to reproduce

We have 3 domains; dev, test, and prod, and the issue is only occurring on servers connected to our test domain. I've also stood up a new AWX environment in a sandpit, and haven't been able to replicate the issue running against either AWX EE latest or our own custom EE. We've also updated AWX to 21.4.0 with no change.

Contents of the test playbook:
`---
- name: System summary is compiled
  hosts: "{{ hosts_var }}"

  tasks:
    - name: Test connection to Windows host
      ansible.windows.win_ping:
      when: ansible_os_family == "Windows"

    - name: Test connection to Linux host
      ansible.builtin.ping:
      when: ansible_os_family != "Windows"`

### Expected results

`/usr/local/lib/python3.8/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
ansible-playbook [core 2.12.5.post0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 2.11.3
  libyaml = True
No config file found; using defaults
SSH password: 
setting up inventory plugins
host_list declined parsing /runner/inventory/hosts as it did not pass its verify_file() method
Parsed /runner/inventory/hosts inventory source with script plugin
Loading collection ansible.windows from /usr/share/ansible/collections/ansible_collections/ansible/windows
Loading callback plugin awx_display of type stdout, v2.0 from /usr/local/lib/python3.8/site-packages/ansible_runner/callbacks/awx_display.py
Skipping callback 'awx_display', as we already have a stdout callback.
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: test_connection.yml **************************************************
Positional arguments: test_connection.yml
verbosity: 4
remote_user: <dev server>@<dev domain>
connection: smart
timeout: 10
ask_pass: True
become_method: sudo
tags: ('all',)
inventory: ('/runner/inventory/hosts',)
extra_vars: ('@/runner/env/tmpd6abxn0c', '@/runner/env/extravars')
forks: 5
1 plays in test_connection.yml

PLAY [System summary is compiled] **********************************************

TASK [Gathering Facts] *********************************************************
task path: /runner/project/test_connection.yml:2
redirecting (type: modules) ansible.builtin.setup to ansible.windows.setup
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/setup.ps1
Pipelining is enabled.
<<dev server>.<dev domain>> ESTABLISH WINRM CONNECTION FOR USER: <dev server>@<dev domain> on PORT 5985 TO <dev server>.<dev domain>
calling kinit with pexpect for principal <dev server>@<dev domain>
EXEC (via pipeline wrapper)
ok: [<dev server>.<dev domain>]
META: ran handlers

TASK [Test connection to Windows host] *****************************************
task path: /runner/project/test_connection.yml:6
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_ping.ps1
Pipelining is enabled.
<<dev server>.<dev domain>> ESTABLISH WINRM CONNECTION FOR USER: <dev server>@<dev domain> on PORT 5985 TO <dev server>.<dev domain>
calling kinit with pexpect for principal <dev server>@<dev domain>
EXEC (via pipeline wrapper)
ok: [<dev server>.<dev domain>] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": "pong"
        }
    },
    "ping": "pong"
}

TASK [Test connection to Linux host] *******************************************
task path: /runner/project/test_connection.yml:10
skipping: [<dev server>.<dev domain>] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************
<dev server>.<dev domain> : ok=2    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
`

### Actual results

`/usr/local/lib/python3.8/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
ansible-playbook [core 2.12.5.post0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 2.11.3
  libyaml = True
No config file found; using defaults
SSH password: 
setting up inventory plugins
host_list declined parsing /runner/inventory/hosts as it did not pass its verify_file() method
Parsed /runner/inventory/hosts inventory source with script plugin
Loading collection ansible.windows from /usr/share/ansible/collections/ansible_collections/ansible/windows
Loading callback plugin awx_display of type stdout, v2.0 from /usr/local/lib/python3.8/site-packages/ansible_runner/callbacks/awx_display.py
Skipping callback 'awx_display', as we already have a stdout callback.
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: test_connection.yml **************************************************
Positional arguments: test_connection.yml
verbosity: 4
remote_user: <ansible user>@<test domain>
connection: smart
timeout: 10
ask_pass: True
become_method: sudo
tags: ('all',)
inventory: ('/runner/inventory/hosts',)
extra_vars: ('@/runner/env/tmpnlt3biaf', '@/runner/env/extravars')
forks: 5
1 plays in test_connection.yml

PLAY [System summary is compiled] **********************************************

TASK [Gathering Facts] *********************************************************
task path: /runner/project/test_connection.yml:2
redirecting (type: modules) ansible.builtin.setup to ansible.windows.setup
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/setup.ps1
Pipelining is enabled.
<<test server>.<test domain>> ESTABLISH WINRM CONNECTION FOR USER: <ansible user>@<test domain> on PORT 5985 TO <test server>.<test domain>
calling kinit with pexpect for principal <ansible user>@<test domain>
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 158, in run
    res = self._execute()
  File "/usr/local/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 600, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/action/gather_facts.py", line 100, in run
    res = self._execute_module(module_name=fact_module, module_args=mod_args, task_vars=task_vars, wrap_async=False)
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/action/__init__.py", line 1100, in _execute_module
    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/action/__init__.py", line 1253, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/connection/winrm.py", line 573, in exec_command
    super(Connection, self).exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/connection/__init__.py", line 34, in wrapped
    self._connect()
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/connection/winrm.py", line 555, in _connect
    self.protocol = self._winrm_connect()
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/connection/winrm.py", line 436, in _winrm_connect
    self._kerb_auth(self._winrm_user, self._winrm_pass)
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/connection/winrm.py", line 364, in _kerb_auth
    child.expect(".*:")
  File "/usr/local/lib/python3.8/site-packages/pexpect/spawnbase.py", line 343, in expect
    return self.expect_list(compiled_pattern_list,
  File "/usr/local/lib/python3.8/site-packages/pexpect/spawnbase.py", line 372, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.8/site-packages/pexpect/expect.py", line 181, in expect_loop
    return self.timeout(e)
  File "/usr/local/lib/python3.8/site-packages/pexpect/expect.py", line 144, in timeout
    raise exc
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f39d0b544c0>
command: /usr/bin/kinit
args: ['/usr/bin/kinit', '<ansible user>@<test domain>']
buffer (last 100 chars): b''
before (last 100 chars): ''
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 26
child_fd: 13
closed: False
timeout: 60
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'.*:')
fatal: [<test server>.<test domain>]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

PLAY RECAP *********************************************************************
<test server>.<test domain> : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   `

**Comment by m-hoskin-unisa** [comment]
Manually running the playbook within an EE container doesn't show the same behaviour:

>bash-4.4# /usr/local/bin/ansible-runner run /runner/ -p test_connection.yml -vvvvv
ansible-playbook [core 2.12.5.post0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
setting up inventory plugins
host_list declined parsing /runner/inventory/hosts as it did not pass its verify_file() method
script declined parsing /runner/inventory/hosts as it did not pass its verify_file() method
auto declined parsing /runner/inventory/hosts as it did not pass its verify_file() method
Parsed /runner/inventory/hosts inventory source with yaml plugin
Loading collection ansible.windows from /usr/share/ansible/collections/ansible_collections/ansible/windows
Loading callback plugin awx_display of type stdout, v2.0 from /usr/local/lib/python3.8/site-packages/ansible_runner/callbacks/awx_display.py
Attempting to use 'awx_display' callback.
Skipping callback 'awx_display', as we already have a stdout callback.
Attempting to use 'default' callback.
Skipping callback 'default', as we already have a stdout callback.
Attempting to use 'junit' callback.
Attempting to use 'minimal' callback.
Skipping callback 'minimal', as we already have a stdout callback.
Attempting to use 'oneline' callback.
Skipping callback 'oneline', as we already have a stdout callback.
Attempting to use 'tree' callback.

>PLAYBOOK: test_connection.yml **************************************************
Positional arguments: test_connection.yml
verbosity: 5
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/runner/inventory',)
extra_vars: ('@/runner/env/extravars',)
forks: 5
1 plays in test_connection.yml

>PLAY [System summary is compiled] **********************************************

>TASK [Gathering Facts] *********************************************************
task path: /runner/project/test_connection.yml:2
redirecting (type: modules) ansible.builtin.setup to ansible.windows.setup
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/setup.ps1
Pipelining is enabled.
<test_host> ESTABLISH WINRM CONNECTION FOR USER: test_user@test_domain on PORT 5985 TO test_host
<test_host> WINRM CONNECT: transport=kerberos endpoint=http://test_host:5985/wsman
<test_host> WINRM OPEN SHELL: 462CA37E-3E0F-46E6-B410-91AE373E9E7B
EXEC (via pipeline wrapper)
<test_host> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Unrestricted', '-EncodedCommand', '...']
<test_host> WINRM RESULT '<Response code 0, out "{"changed":false,"in", err "#< CLIXML\r\n<Objs Ver">'
<test_host> WINRM CLOSE SHELL: 462CA37E-3E0F-46E6-B410-91AE373E9E7B
ok: [test_host]
META: ran handlers

>TASK [Test connection to Windows host] *****************************************
task path: /runner/project/test_connection.yml:6
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_ping.ps1
Pipelining is enabled.
<test_host> ESTABLISH WINRM CONNECTION FOR USER: test_user@test_domain on PORT 5985 TO test_host
<test_host> WINRM CONNECT: transport=kerberos endpoint=http://test_host:5985/wsman
<test_host> WINRM OPEN SHELL: 5A5960DB-CDC6-479C-B1B4-DC5BCEB131E2
EXEC (via pipeline wrapper)
<test_host> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Unrestricted', '-EncodedCommand', '...']
<test_host> WINRM RESULT '<Response code 0, out "{"changed":false,"in", err "#< CLIXML\r\n<Objs Ver">'
<test_host> WINRM CLOSE SHELL: 5A5960DB-CDC6-479C-B1B4-DC5BCEB131E2
ok: [test_host] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": "pong"
        }
    },
    "ping": "pong"
}

>TASK [Test connection to Linux host] *******************************************
task path: /runner/project/test_connection.yml:10
skipping: [test_host] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}
META: ran handlers
META: ran handlers

>PLAY RECAP *********************************************************************
test_host : ok=2    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0

**Comment by m-hoskin-unisa** [comment]
Have managed to resolve the issue, seems to be related to DNS within the Kubernetes cluster that was preventing kinit from resolving the KDC. For reference, to resolve the issue we did the following:

Added a config map with krb5.conf contents:
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: awx-extra-files
  namespace: awx
data:
  krb5.conf: |
    includedir /etc/krb5.conf.d/
    [logging]
    default = FILE:/var/log/krb5libs.log
    kdc = FILE:/var/log/krb5kdc.log
    admin_server = FILE:/var/log/kadmind.log
    [libdefaults]
    dns_lookup_realm = false
    dns_lookup_kdc = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true
    rdns = false
    pkinit_anchors = FILE:/etc/pki/tls/certs/ca-bundle.crt
    spake_preauth_groups = edwards25519
    [realms]
    <domain1_fqdn> = {
        kdc = <domain1_fqdn>:88
    }
    <domain2_fqdn> = {
        kdc = <domain2_fqdn>:88
    }
    <domain3_fqdn> = {
        kdc = <domain3_fqdn>:88
    }
    [domain_realm]
    <domain1_fqdn> = <domain1_fqdn>
    <domain2_fqdn> = <domain2_fqdn>
    <domain3_fqdn> = <domain3_fqdn>
```

Updated the awx kubernetes config to load the krb5.conf content (may not be strictly required but we did do it so putting it here anyway).
```yaml
  task_extra_volume_mounts: |
    - name: krb5
      mountPath: /etc/krb5.conf
      subPath: krb5.conf
  extra_volumes: |
    - name: krb5
      configMap:
        defaultMode: 420
        items:
          - key: krb5.conf
            path: krb5.conf
        name: awx-extra-files
```

Then added the following to the "default" instance group config in AWX:
```yaml
      volumeMounts:
        - name: krb5-conf
          mountPath: /etc/krb5.conf
          subPath: krb5.conf
  volumes:
    - name: krb5-conf
      configMap:
        name: awx-extra-files
```
This is based on a post on a google group I found after searching around:
https://groups.google.com/g/ansible-project/c/SDvLt3sBg3Y

Given the complexity of dealing with Kerberos authentication it might be worth updating the documentation and/or deployment process to clarify how the krb5.conf file can be configured and what the best practice is.

**Comment by akus062381** [comment]
Hi @m-hoskin-unisa,

Thanks for following up to let us know that you had found a resolution to this! If you feel led, please feel free to put a PR up to improve our docs in this area.

Thanks for contributing!
