### ISSUE TITLE
Remove Content Signing Enable/Disable Fields

### ISSUE THREAD

**Issue by djyasin** [ansible/awx#12687]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Removing the enable content verification field since that is no longer needed with the current functionality.

### Select the relevant components

- [x] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Acceptance Criteria 
Remove signature validation enabled field. No longer needed based on updated functionality. Ensure this field is not present.

**Comment by djyasin** [comment]
https://github.com/ansible/awx/pull/12695

**Comment by thenets** [comment]
Tested.
cc: @InnocentK @jneedle
