### ISSUE TITLE
Job output, not recognizing when job is done 

### ISSUE THREAD

**Issue by aheath1992** [ansible/awx#12688]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

SCM update jobs are not recognizing when the takes are complete, the job just sits there and keeps running even after the sync tasks are done. The sync tasks took 30 second, but the job ran for 31 mins

### AWX version

Ansible Automation Platform Controller 4.2.0

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Ansible version

2.13

### Operating system

RHEL 8

### Web browser

Firefox, Chrome

### Steps to reproduce

Kickoff an SCM sync job from the controller.

### Expected results

Job should end within a few seconds of the task's completing 

### Actual results

Jobs sit and keeps running for half an hour past when the tasks completed.

**Comment by mabashian** [comment]
@aheath1992 thanks for reporting this. I see you mentioned Controller/AAP. This bug tracker is for reporting issues in the open source AWX project, not Red Hat Ansible Controller/AAP. If you need help troubleshooting Controller/AAP, you should reach out to Red Hat support.

**Comment by aheath1992** [comment]
@mabashian Red Hat support and the Ansible/Automation platform product owners asked us to open issues in the upstream AWX project at this time.
