### ISSUE TITLE
enable content signature validation for all SCM types

### ISSUE THREAD

**Issue by TheRealHaoLiu** [ansible/awx#12691]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature Summary

As a user I want to be able to select all SCM types in the UI. At this time, only GitHub is an option in the UI. For the API and CLI any type can be used. The UI needs to reflect this functionality as well. 

Link to what Ansible-Galaxy ignores by default:
https://github.com/ansible/ansible/blob/ece85abbc46e087187caf6e05b1515b97c578531/lib/ansible/galaxy/collection/__init__.py#L1180-L1189

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

**Comment by akus062381** [comment]
looks good
