### ISSUE TITLE
Build AWX Failed due to SELinux context unchecked for volume mapping.

### ISSUE THREAD

**Issue by aizuddin85** [ansible/awx#127]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT
 - Installer

##### SUMMARY
Mounting ../awx:awx caused permission denied due to SELinux during ansible task:
TASK [image_build : Build AWX distribution]

##### ENVIRONMENT

* AWX version:1.0.0.333
* Ansible version:  2.3.1.0-1.el7.noarch
* Operating System: CentOS 7.3.1611

##### STEPS TO REPRODUCE

1. git clone devel branch
2. ansible-playbook -i inventory install.yml -e openshift_password=mypass-e docker_registry_password=$(oc whoami -t) -vvv

##### EXPECTED RESULTS

Installer should able to set the correct SELinux label on the host volume before running the container.

##### ACTUAL RESULTS

Installer mount without checking the SELinux context of the said file.

##### ADDITIONAL INFORMATION

N/A

**Comment by matburt** [comment]
This is already fixed here https://github.com/ansible/awx/pull/120

**Comment by aizuddin85** [comment]
@matburt, dont you think that using ansible sefcontext is possible in the playbook instead manual set context?

**Comment by aizuddin85** [comment]
Apologize, did not see the Z flag previously. All good to me.
