### ISSUE TITLE
Jobs not acknowledging global timeout

### ISSUE THREAD

**Issue by aheath1992** [ansible/awx#12712]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Jobs are in a running state / pending state longer than the global timeout we have set (10 Hours)

### AWX version

Ansible Automation Platform Controller 4.2.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

N/A

### Modifications

no

### Ansible version

2.13

### Operating system

RHEL 8

### Web browser

Firefox, Chrome

### Steps to reproduce

Have a job run longer than the global timeout time

### Expected results

If a job runs over the global timeout time, the system kills the job. 

### Actual results

Jobs get stuck in a running or pending state for over the global timeout and don't get stopped /canceled

**Comment by mabashian** [comment]
@aheath1992 thanks for reporting this.  I see you mentioned Controller/AAP.  This bug tracker is for reporting issues in the open source AWX project, not Red Hat Ansible Controller/AAP. If you need help troubleshooting Controller/AAP, you should reach out to Red Hat support.

**Comment by aheath1992** [comment]
@mabashian Red Hat support and the Ansible/Automation platform product owners asked us to open issues in the upstream AWX project at this time.
