### ISSUE TITLE
Stop forcing overwrite_vars=True for SCM inventory sources

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#1271]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Now that #1253 is in, we don't have to force people to use `overwrite_vars` on their inventory sources forever.

##### ENVIRONMENT
* AWX version: 1.0.3-162
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  at minimum users should try to have 2.5
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE
go to create an inventory source, and source it from a project

##### EXPECTED RESULTS
I should be able to uncheck `overwrite_vars`.

##### ACTUAL RESULTS
can't yet.

**Comment by wenottingham** [comment]
What do you mean by 'should be able to'?

**Comment by AlanCoding** [comment]
![screen shot 2018-02-16 at 7 49 49 am](https://user-images.githubusercontent.com/1385596/36308297-0322dab0-12ee-11e8-9e3f-6f6a77b611c7.png)

That box, they should be able to click it, and uncheck it now.

**Comment by wenottingham** [comment]
Oh, we forcibly block it. N/M.

**Comment by AlanCoding** [comment]
The UI should be free to remove the logic that forces the box to be checked.

**Comment by lingfish** [comment]
Hi, did this ever proceed?  Seems not?

To clarify; I'd like to store/merge vars in AWX, yet use an Infoblox inventory script, source from SCM.  Currently, this blows away anything stored "locally".

**Comment by AlanCoding** [comment]
For your purposes, you could change it in the API browser as a workaround. I put up a PR to allow it in the UI.

**Comment by lingfish** [comment]
Nice one, thanks Alan!

**Comment by abedwardsw** [comment]
I am running into this issue as well, I want to combine a satellite6 and scm inventory, but due to not being able to uncheck the flag, the SCM overwrites.   Would be great to see this feature merged.   thanks for your effort @AlanCoding  ([related forum post](https://groups.google.com/forum/#!topic/awx-project/Ruk3j-eyWQo))

**Comment by ryanpetrello** [comment]
We've just released a new version of awx (https://github.com/ansible/awx/releases/tag/3.0.0) which should resolve this issue.
