### ISSUE TITLE
Populate all available groups as options to the limit field on the job template creation.

### ISSUE THREAD

**Issue by e-tienne** [ansible/awx#1272]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY
Populate all available groups as options to the limit field with pattern matching on the job template creation or prompt on launch.

##### ACTUAL RESULTS

With a large dynamic inventory and multiple groups, we have to keep a printout of the group list and rely on correct typing into the limit field.

**Comment by wenottingham** [comment]
This has already been filed here https://github.com/ansible/awx/issues/1179
