### ISSUE TITLE
The inventory passed for the node of a workflow schema is ignored when using workflow_job_template.

### ISSUE THREAD

**Issue by db0** [ansible/awx#12720]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When using `workflow_job_template` nodes do not pass the inventory argument to the AWX API, causing the job to fail when the underlying job template requires an inventory

### AWX version

AAP 2.2.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Ansible version

2.13

### Operating system

RedHat 8

### Steps to reproduce

Create a job template which requests an inventory, but do not provide an inventory for it
Create a workflow job which uses that job template with a node that provides the required inventory

### Expected results

The workflow node should be created

### Actual results

When running the playbook, the job to create the workflow will fail when it comes to the point of creating that node, because the inventory is not handled properly

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to create workflow_job_template_node OS Baseline: {'resources_needed_to_start': ['Job Template inventory is missing or undefined.']}"}
```

### Additional information

I am running this against the official RedHat Ansible Automation Platform Controller collection, which is downstream, but the same issue exists here, so instead of opening  a case to RH, I thought I'll go straight to the source.

**Comment by sean-m-sullivan** [comment]
Can you post the schema you are using with the inputs, would help to recreate this and figure it out.

**Comment by db0** [comment]
@sean-m-sullivan , I've already fixed it. See the linked PR.

**Comment by sean-m-sullivan** [comment]
Sorry, I think I missed that last night, going over this, I am not sure how I missed this in the previous iteration. Thanks.
