### ISSUE TITLE
Is it posibble install AWX on podman-compose?

### ISSUE THREAD

**Issue by CC-Kuoying** [ansible/awx#12737]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### AWX version

20.1.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Steps to reproduce

no

### Expected results

no

### Actual results

no

**Comment by akus062381** [comment]
Hi @CC-Kuoying, there is an interesting community contribution around this topic. You may want to take a look! https://github.com/ansible/awx/pull/13337
