### ISSUE TITLE
enable health check to be run for remote execution node on kube deployment

### ISSUE THREAD

**Issue by TheRealHaoLiu** [ansible/awx#12739]
## Summary
currently health check relies on the awx web process to be able to use receptorctl to connect to the receptor mesh to initiate a healthcheck for the remote execution node 

in kubernetes deployment the receptor socket is not mounted into the awx-web container and health check will never be successful 

while we work on allowing use to add remote execution node to the kubernetes deployment of awx we need enable user to run health check on the node 

ideally we would not want to mount the receptor socket into the awx-web container because it introduces additioanl "coupling" between awx-web and receptor

## ISSUE TYPE
New or Enhanced Feature

## COMPONENT NAME
API

**Comment by CFSNM** [comment]
Validated from QE side. Closing
