### ISSUE TITLE
Add new optional variable to inventory_source called "update_on_project_launch" to match available UI options

### ISSUE THREAD

**Issue by cfawcett82** [ansible/awx#12730]
##### ISSUE TYPE
 - New or Enhanced Feature

##### COMPONENT NAME

 - Collection

##### SUMMARY
awx.awx.inventory_source is missing optional variable for "update on project update"

##### ENVIRONMENT
* AWX version: 21.4.0
* AWX install method: operator, developer environment
* AWX deployment target: openshift, kubernetes, minikube
* Operating System: rhel 8.6+
* Web Browser: chrome

##### STEPS TO REPRODUCE

- name: Add an inventory source
  inventory_source:
    name: "cool_project_incentory_source"
    description: Source from project inventory
    inventory: cool_project_inventory
    source: scm
    source_project: cool_project
    source_path: inventory/inventory.yml
    overwrite: True
    overwrite_vars: True
    update_on_launch: True
    update_on_prject_update: True
    organization: really_cool_org_name_here

**Comment by akus062381** [comment]
Hi @cfawcett82, thanks for your submission. Just to make you aware, in this case, we made a change deliberately here. We removed "update_on_project_update" from the API. Instead, you'd want to enable update_on_launch for the associated project. This is the equivalent to the old variable "update_on_project_update".
