### ISSUE TITLE
fix api/v2/metrics consumed capacity calcualtion to match how we do it elsewhere

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#12743]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

We Do this wrong in 
https://github.com/ansible/awx/blob/4fbf5e9e2f377ba2c419beb588c72eb26b77bf24/awx/main/analytics/collectors.py#L242

we need to do it in the same way we do it here:

https://github.com/ansible/awx/blob/4fbf5e9e2f377ba2c419beb588c72eb26b77bf24/awx/main/models/ha.py#L149-L161

ideally, we would just call that function...though we may want to consider what we do in 
https://github.com/ansible/awx/blob/4fbf5e9e2f377ba2c419beb588c72eb26b77bf24/awx/main/scheduler/task_manager_models.py#L47-L55

to avoid querying all running jobs for each instance

### AWX version

devel

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Steps to reproduce

look at /api/v2/metrics vs /api/v2/instances

### Expected results

same computed capacity consumed

### Actual results

not the same

**Comment by AlanCoding** [comment]
Closing as done right now because I don't think we need this to go through QE.
