### ISSUE TITLE
Job output: clear "follow mode" flag on search

### ISSUE THREAD

**Issue by keithjgrant** [ansible/awx#12756]
##### ISSUE TYPE
 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME
 - UI

##### SUMMARY
the job output screen sometimes jumps to the bottom of output when searching/clearing a search. This is probably due to the 'follow mode' flag being left on -- this flag should be cleared when the query params change

![cnO0PzoKD1](https://user-images.githubusercontent.com/410794/186968182-f2fca56f-1afc-419d-a3e3-d8a2aaf5c11f.gif)

**Comment by InnocentK** [comment]
Resolved
