### ISSUE TITLE
Artifacts not being set/persisted from AWX job_template runs

### ISSUE THREAD

**Issue by danxg87** [ansible/awx#12750]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When running a job template in AWX, we intermittently have failure modes where the tasks in a playbook successfully set_stats to generate artifacts, but upon completion not artifacts object/values are generated/persisted. This causes failures in workflow runs since later job_template_nodes rely on those artifacts.

We see 0 artifacts in the UI as well as the API of the job run in question even though it set values we expect to see in artifacts. 

Rerunning the same job/workflow seems to succeed most of the time; this behavior appears random/intermittent, but is concerning.

### AWX version

20.0.1

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

20.0.1

### Operating system

CentOS

### Web browser

Chrome

### Steps to reproduce

1. Create a job which generates artifacts
2. Create another job which relies on said artifacts
3. Create a workflow that has the artifact generator run and then runs the artifact user job
4. Run created workflow to see it (potentially) succeed on the artifact generator job, but fail on the user job as the artifacts were never generated as expected

Note that this behavior appears to occur roughly 30% of the time we run this.

### Expected results

We expect the artifacts object to be populated with the artifacts a job generates/sets.

### Actual results

The artifacts are never created/generated by the job_template even though the playbook tasks show the steps succeeding.

### Additional information

playbook task output:
```bash
{
  "changed": false,
  "ansible_stats": {
    "data": {
      "test_hostname": "testing01"
    },
    "per_host": false,
    "aggregate": true
  },
  "_ansible_no_log": false
}
```
artifacts from API:
```bash
"artifacts": {},
```
artifacts in UI:
```bash
---
```

**Comment by MalfuncEddie** [comment]
Hi, 

I had a similar issue with facts/ inventory artifacts. It was (in my case) a wrong ansible-runner version. (check out https://github.com/ansible/ansible-runner/pull/1093)

**Comment by danxg87** [comment]
We tried different runner versions (even built/ran 2.2.1 release) and that made no difference. 

*Oddly enough (and I still can't believe this lol) flipping the job_template verbosity to DEBUG seemingly has FIXED the issue, so to speak. We have run close to 20x of our test workflow and artifacts persist as expected every time. 

I wonder if the debug in the output somehow causes AWX background procs/funcs to run that set the artifact_data?

This is still def an issue for us (as we don't want to have DEBUG spitting out just to get artifacts set)

We have also tried just basic verbosity setting which appears to still fail sometimes... Though not as much as no verbosity.

**Comment by akus062381** [comment]
@danxg87-

Would you mind providing the following information to help us try to diagnose your problem?

- a job endpoint with the set_stats job
- the job API that uses the artifact

**Comment by akus062381** [comment]
Hi @danxg87, thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
