### ISSUE TITLE
/migrations_notran does not redirect if AWX is fully up

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1275]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY

Case 1. AWX is upgrading. Go to AWX.

1. You are redirected to /migrations_notran.
2. You wait
3. You are redirected to AWX when done.

Case 2: AWX is not upgrading. Go to awx/migrations_notran (by accident)

1. You see 'will redirect to AWX when done'
2. You wait
3. Nothing happens

##### ENVIRONMENT
* AWX version: current

**Comment by matburt** [comment]
This uses a javascript timer on the page is there something wrong with that? anything on the javascript console?

**Comment by wenottingham** [comment]
Hm. Refresh of containers fixed it. ¯\_(ツ)_/¯
