### ISSUE TITLE
[api] Confusing error when trying to sync project set to scm_type Manual

### ISSUE THREAD

**Issue by relrod** [ansible/awx#12761]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Creating a project and accidentally setting it to be `scm_type: manual` (the default in the awx collection), and then trying to do a project update on it, leads to a very confusing error:

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Cannot make a request with the POST method to this endpoint /api/v2/projects/8/update/"}
```

Although it is "technically" correct, it would be nice if we could show something nicer in this scenario (e.g. "Unable to trigger a project update because the project scm type (Manual) does not support it.")

### AWX version

devel

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Steps to reproduce

- Create a project, set its type to Manual
- Use the API (or `awx.awx.project_update`) to try to update it

### Expected results

An error explaining the problem

### Actual results

An error telling me that I can't POST to an endpoint that I expect to be able to POST to.

**Comment by nishipy** [comment]
Hi team. Can I work on this if none is doing it?
If I understand correctly, we need to fix around here.
https://github.com/ansible/awx/blob/e0b1274eee44bb47114b74c07c2ad5331f28cacf/awx_collection/plugins/modules/project_update.py#L114-L115

**Comment by darshanip** [comment]
I've started working on this issue.
