### ISSUE TITLE
Error running playbook migrate.yml  TASK [sources : Render Docker-Compose]  'execution_node_count' is undefined

### ISSUE THREAD

**Issue by JERUSO** [ansible/awx#12768]
##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - API
 - UI
 - Collection
 - Docs
 - CLI
 - Other --> execute playbook migrate.yml

##### SUMMARY

Error to migrated AWX v17.x to 18.x

When executing the migrate.yml in the Render Docker-Compose task, the following error is presented.

TASK [sources : Render Docker-Compose] ***************************************************************************************************************************************************************************
task path: /root/migraawx/awx/tools/docker-compose/ansible/roles/sources/tasks/main.yml:99
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1661761508.891268-51974-100882121210330 `" && echo ansible-tmp-1661761508.891268-51974-100882121210330="` echo /root/.ansible/tmp/ansible-tmp-1661761508.891268-51974-100882121210330 `" ) && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1661761508.891268-51974-100882121210330/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ansible/template/__init__.py", line 1156, in do_template
    res = j2_concat(rf)
  File "<template>", line 57, in root
  File "/usr/lib/python3.8/site-packages/ansible/template/__init__.py", line 298, in wrapper
    ret = func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/jinja2/filters.py", line 653, in do_int
    return int(value)
  File "/usr/lib/python3.8/site-packages/jinja2/runtime.py", line 630, in _fail_with_undefined_error
    raise self._undefined_exception(hint)
jinja2.exceptions.UndefinedError: 'execution_node_count' is undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ansible/plugins/action/template.py", line 150, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)
  File "/usr/lib/python3.8/site-packages/ansible/template/__init__.py", line 1193, in do_template
    raise AnsibleUndefinedVariable(e)
ansible.errors.AnsibleUndefinedVariable: 'execution_node_count' is undefined
fatal: [localhost]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'execution_node_count' is undefined"
}

PLAY RECAP *******************************************************************************************************************************************************************************************************
localhost                  : ok=14   changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0  

##### ENVIRONMENT
* AWX version: 17.1.0
* AWX install method: migrate old version
* AWX deployment target: kubernetes
* Operating System: Centos 8.x
* Web Browser: MS Edge/firefox

##### STEPS TO REPRODUCE

I have followed the steps indicated in the migration link, 
https://github.com/ansible/awx/blob/b4ef687b60efd345641770daf84708d524656816/tools/docker-compose/docs/data_migration.md

I have configured the inventory file with the requested data. I have executed the migration step and it shows me the indicated error.

##### EXPECTED RESULTS

I await the result according to what is indicated in the link

##### ACTUAL RESULTS

TASK [sources : Render Docker-Compose] ***************************************************************************************************************************************************************************
task path: /root/migraawx/awx/tools/docker-compose/ansible/roles/sources/tasks/main.yml:99
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1661761508.891268-51974-100882121210330 `" && echo ansible-tmp-1661761508.891268-51974-100882121210330="` echo /root/.ansible/tmp/ansible-tmp-1661761508.891268-51974-100882121210330 `" ) && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1661761508.891268-51974-100882121210330/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ansible/template/__init__.py", line 1156, in do_template
    res = j2_concat(rf)
  File "<template>", line 57, in root
  File "/usr/lib/python3.8/site-packages/ansible/template/__init__.py", line 298, in wrapper
    ret = func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/jinja2/filters.py", line 653, in do_int
    return int(value)
  File "/usr/lib/python3.8/site-packages/jinja2/runtime.py", line 630, in _fail_with_undefined_error
    raise self._undefined_exception(hint)
jinja2.exceptions.UndefinedError: 'execution_node_count' is undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ansible/plugins/action/template.py", line 150, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)
  File "/usr/lib/python3.8/site-packages/ansible/template/__init__.py", line 1193, in do_template
    raise AnsibleUndefinedVariable(e)
ansible.errors.AnsibleUndefinedVariable: 'execution_node_count' is undefined
fatal: [localhost]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'execution_node_count' is undefined"
}

##### ADDITIONAL INFORMATION
i have install in my server Python 3.6.8
The AWX Version 17.1.0 is installed in docker containers.

**Comment by djyasin** [comment]
Hello, 
The issue that you are describing pertains to a version of AWX that is no longer supported. Try upgrading to the latest version and let us know if that resolves your issue.

**Comment by JERUSO** [comment]
That's why I want to migrate to the recent version of AWX however I'm stuck in the process of executing the migrated.yml playbook... that's why I need support... please tell me what I should do...

**Comment by akus062381** [comment]
Hello @JERUSO, this appears to be less of a bug report or feature request and more of a question. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.

**Comment by fosterseth** [comment]
@JERUSO awx 18 no longer works with the older docker based deployment.

AWX 18+ uses the awx-operator, where the app will run on a k8s cluster. See github.com/ansible/awx-operator for documentation on that

if you need to migrate older data from a 17 deployment to 21.7.0, there are some instructions here https://github.com/ansible/awx-operator/blob/devel/docs/migration.md

please let us know if this helps

**Comment by akus062381** [comment]
Hi @JERUSO,
Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
