### ISSUE TITLE
Password fields are shown as cleartext in preview when launching a job with a survey

### ISSUE THREAD

**Issue by grahamneville** [ansible/awx#1278]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Password fields are shown as cleartext in preview when launching a job with a survey

##### ENVIRONMENT
* AWX version: 1.0.3.38
* AWX install method: docker on linux
* Ansible version:  2.4.0.3

##### STEPS TO REPRODUCE

1) create a new job template and add a survey. Within the survey have a password field.
2) run the job template and then once you get to the preview window you'll see your password in cleartext.

##### EXPECTED RESULTS

Password is shown as $encrypted$ in preview mode

##### ACTUAL RESULTS

Password is shown as cleartext in preview mode

**Comment by jaredevantabor** [comment]
This is fixed in devel.
