### ISSUE TITLE
Cannot use community.general.icinga2 as inventory source with vaulted password

### ISSUE THREAD

**Issue by MarcusCaepio** [ansible/awx#12783]
##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - Collection
 - Other

##### SUMMARY
Hello all,
we are using the inventory community.general.icinga2 inventory – Icinga2 inventory as source for our dynamic inventory. As the inventory config is stored in a repo, we have vaulted the necessary password. On CLI it is no problem to use the inventory with '--ask-vault-pass' but in AWX I always get 'Attempting to decrypt but no vault secrets found', because there is no way to configure a vault password for the inventory.
I tried several things to make it running:
- Define a Job Template where the Vault is configured and enabled Inventory Update on Job Run
- Replaced the vault config with a variable and tried to configure the variable in the inventory source variables

Nothing worked so far, I only get the inventory sync running, when the password is saved in plaintext in the x.icinga2.yml inventory file. 

##### ENVIRONMENT
* AWX version: 21.4.0
* AWX install method: operator
* AWX deployment target: kubernetes

##### STEPS TO REPRODUCE

- install community.general via requirements.yml file
- create an x.icinga2.yml with a vaulted password
- config the inventory in AWX
- Sync

##### EXPECTED RESULTS

As the inventory source has to be configured as "Sourced from a project", this source should be able to handle vaulted passwords.
Another option would be, to have the icinga2 source implemented in the AWX Source Dropdown menu, as it is a community maintained inventory plugin. 

##### ACTUAL RESULTS

Inventory sync only works with plaintext saved password in the x.icinga2.yml config

##### ADDITIONAL INFORMATION

See https://docs.ansible.com/ansible/latest/collections/community/general/icinga2_inventory.html#ansible-collections-community-general-icinga2-inventory for the inventory docs.

Thanks a lot,
Marcus

**Comment by AlanCoding** [comment]
> create an x.icinga2.yml with a vaulted password

This is the case that is not supported, and tracked in the primary issue https://github.com/ansible/awx/issues/4089, but from what you said you are trying to do, the existing solution may work.

https://docs.ansible.com/ansible/latest/user_guide/vault.html

See the section "Encrypting individual variables with Ansible Vault", and specifically note "individual variables" as opposed to the next section on "Encrypting files".

Try doing that, and putting the encrypted value in a valid yaml file where you were trying to encrypt the whole file. Where an individual variable has an encrypted value, the inventory update should pull in that value _in the encrypted form_ and then attaching a vault credential to the job template can get it to work. This may or may not address your particular use case, but it's what is available.

**Comment by MarcusCaepio** [comment]
What about adding the icinga2 inventory plugin as dedicated source like the vcenter, which also is a community maintained inventory plugin?

**Comment by akus062381** [comment]
Hi @MarcusCaepio, 

We only vendor certain modules within the EE that are very commonly used in order to keep the size of our execution environments small.

At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
