### ISSUE TITLE
The ipaddr filter requires python's netaddr be installed on the ansible controller

### ISSUE THREAD

**Issue by basift** [ansible/awx#12792]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

While running playbook that use ansible.utils.ipaddr,
I'm receiving the exception:
ansible.utils.ipaddr' failed. The error was: The ipaddr filter requires python's netaddr be installed on the ansible controller

### AWX version

21.5.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.12.5.post0

### Operating system

Ubuntu 20.04

### Web browser

Chrome

### Steps to reproduce

Install AWX with AWX-operator as described in the official manual.
Add official kubespary project.
Use the default AWX-EE
Run it.

### Expected results

Installing the new K8s cluster

### Actual results

task path: /runner/project/ansible_version.yml:20
fatal: [localhost]: FAILED! => {
    "msg": "The conditional check ''127.0.0.1' | ansible.utils.ipaddr' failed. The error was: The ipaddr filter requires python's netaddr be installed on the ansible controller"
}

### Additional information

By my check there is netaddr installed on AWX-EE image.
I connected to the AWX-EE container and this is what I got:
bash-4.4$ pip list | grep netaddr
WARNING: The directory '/home/runner/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with su
do, you should use sudo's -H flag.
netaddr                            0.8.0
WARNING: You are using pip version 22.0.4; however, version 22.2.2 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
bash-4.4$

**Comment by djyasin** [comment]
Hello. The problem you are reporting is with the EE, not the AWX container. The awx-ee contains the collections and dependencies needed for supported AWX features to function. Anything beyond that (like the community.general package) will require you to build your own EE. For information on how to do that, see https://ansible-builder.readthedocs.io/en/stable/

The Ansible Community is looking at building an EE that corresponds to all of the collections inside the ansible package. That may help you if and when it happens; see https://github.com/ansible-community/community-topics/issues/31 for details.

**Comment by akus062381** [comment]
Hi @basift,

Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
