### ISSUE TITLE
UI crash - Error to see task stdout

### ISSUE THREAD

**Issue by Tioborto** [ansible/awx#12793]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hello, 
When we want to show our task stdout, AWX totally crash.
We are in the last version of AWX and the problem was not present in version [19.4.0.]
Actually we doesn't see where is the problem.
Can you have a look please ? 

Wee have the problem with 2 different collections: 
* aruba: https://galaxy.ansible.com/arubanetworks/aos_switch
* cisco: https://galaxy.ansible.com/cisco/ios

Movie to reproduce error:
https://user-images.githubusercontent.com/29703972/187706046-c44853e9-1752-4873-bbcc-31c62587edcc.mov

Error in UI:
```
gP/<@https://awx/static/js/main.c9f2a36c.js:2:2173280
Fl@https://awx/static/js/main.c9f2a36c.js:2:1241367
36813/t.unstable_runWithPriority@https://awx/static/js/main.c9f2a36c.js:2:1407964
Gi@https://awx/static/js/main.c9f2a36c.js:2:1181686
Nl@https://awx/static/js/main.c9f2a36c.js:2:1240828
yl@https://awx/static/js/main.c9f2a36c.js:2:1232318
34463/Ji/<@https://awx/static/js/main.c9f2a36c.js:2:1181909
36813/t.unstable_runWithPriority@https://awx/static/js/main.c9f2a36c.js:2:1407964
Gi@https://awx/static/js/main.c9f2a36c.js:2:1181686
Ji@https://awx/static/js/main.c9f2a36c.js:2:1181856
Ki@https://awx/static/js/main.c9f2a36c.js:2:1181789
Re@https://awx/static/js/main.c9f2a36c.js:2:1252956
Yt@https://awx/static/js/main.c9f2a36c.js:2:1160409
```

Console Errors:
```
TypeError: e.match is not a function
    $detectNewLine ace.js:7139
    insert ace.js:7211
    setValue ace.js:7119
    setValue ace.js:9368
    componentDidMount ace.tsx:243
    React 2
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
react-dom.production.min.js:216:199
```

```
TypeError: p.current is null
    gP CodeEditor.js:96
    Fl React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
react-dom.production.min.js:216:199
```

### AWX version

21.5.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.9

### Web browser

Firefox, Chrome, Safari

### Steps to reproduce

Fetch data using collection aruba or cisco
Click to show on successful task

### Expected results

Show the expected result

### Actual results

UI crash

**Comment by marek1712** [comment]
I'm on 21.3.0 and see the same thing. Any update?

This is the simple task that makes the UI crash:
`  - name: "Display uptime - SSH"`
`    ios_command:`
`     commands:`
`      - show version | include uptime`
`    register: ssh_uptime`
`    when: ssh_enabled is succeeded`

**Comment by Tioborto** [comment]
Any help on this UI crash please ?

**Comment by akus062381** [comment]
Hi @Tioborto,

It appears that your work has resolved this issue, thanks so much for your contribution!
We are going to close this issue, and we look forward to seeing your name pop up here again!
