### ISSUE TITLE
AWX Collection Documentation Changes

### ISSUE THREAD

**Issue by djyasin** [ansible/awx#12816]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature Summary
We need to update the DOCUMENTATION block in the awx collection. We need to add GPG Public Key under credential_type where it shows the possible options, and we need to add gpg_public_key to the list that inputs describes. 

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

**Comment by djyasin** [comment]
Resolved in #12817

**Comment by thedoubl3j** [comment]
think we are good to close this yeah @djyasin?

**Comment by djyasin** [comment]
Thank you, @thedoubl3j I will do that now!
