### ISSUE TITLE
Inventory option to Prompt At Launch Not working as expected

### ISSUE THREAD

**Issue by tech-dad** [ansible/awx#1281]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
On a created Job, the option to prompt on launch will not work with the inventory field being empty in the job. It will only work if you define an inventory file in the job, and then select "Prompt on Launch"

See Screen Shots:
This will work:
https://pasteboard.co/H7X6Sar.png
![h7x6sar](https://user-images.githubusercontent.com/29238531/36327349-58874034-132c-11e8-909a-db0b3e2a0ffd.png)

This will not work:
https://pasteboard.co/H7X78pS.png
![h7x78ps](https://user-images.githubusercontent.com/29238531/36327371-6d3b3044-132c-11e8-9f50-a4e445b82c9d.png)

##### ENVIRONMENT
* AWX version: 1.0.3.55
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: Red Hat Enterprise Linux Server release 7.4 (Maipo)
* Web Browser: Chrome on Linux

##### STEPS TO REPRODUCE
Login to UI
Select Templates
Select Job "Install ClamAV Agent"
Ensure the inventory field is empty
Check box for "PROMPT ON LAUNCH"
Click Save
Go back to Templates
Click Rocket
Select Inventory "Development", hit next, specify limit "ss"
Click Launch

##### EXPECTED RESULTS

Job to run with variables passed at prompt

##### ACTUAL RESULTS

"ERROR!
Job Template inventory is missing or undefined."

**Comment by tech-dad** [comment]
I can confirm this is also happening on the default job included with the installation

"Demo Job Template"

**Comment by gservat** [comment]
Additionally, if you set an inventory in the template but then change it when you launch, it will still use the one defined in the template.

**Comment by NathalieCBC** [comment]
Additionally, if you launch the template from the "Recently used templates" section of the dashboard, this will work and use the other inventory.

**Comment by mabashian** [comment]
I've opened up a PR to fix this issue.  @NathalieCBC that's a good observation.  We're in the process of overhauling the launch logic across the entire app.  Launching from the templates list (`#/templates`) leverages this new logic which includes the preview step.  "Recently used templates" has not yet been migrated to this new launch logic and uses the old logic which is why you weren't experiencing that bug there.  In the coming weeks I'll be updating the rest of the launch points so that everything uses the same (new) logic.

**Comment by NathalieCBC** [comment]
Thank you @mabashian - makes sense - we'll be monitoring for update.

**Comment by mabashian** [comment]
PR has been merged - closing this for now.  Let me know if there are still issues selecting an inventory when launching from the templates list.

**Comment by shyheg01** [comment]
I am using 1.0.6.1 and it doesn't work for me. How can I fix this ?

**Comment by webtonize** [comment]
Having this issue on 1.0.6.16 docker images. Both on templates migrated with `awx-cli` and newly added templates

Issues only appears in Chrome, no issue in Firefox

**Comment by mnhuttner** [comment]
Having this issue on awx 1.0.4.0 with ansible 2.4.2, using Chrome
