### ISSUE TITLE
Feature idea: automatically split jobs across a cluster

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1283]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

Sometimes a user wants to run a job across a very very large number of endpoints. The current best practice is to 'size the number of forks based on available resources, and cycle until done'.

However, this still limits execution to a single AWX node.

It would be potentially useful to have AWX split a job into multiple `ansible-playbook` executions, each on a subset of inventory, that can be scheduled in parallel across a cluster.

Caveats:
- Not all playbooks work in the scenario. This would require explict per-job opt-in. (We would not attempt to discover whether or not a playbook would support this ... that way lies madness.)
- This may end up being a new template type, a la workflows, as it changes the playbook/inventory -> template -> job -> ansible-playbook run -> output 1:1 relationships
- There may need to be new output display paradigms for this, to find the individual playbook run where a particular host was handled
- How to break jobs up? Do we do it differently based on available resources?
- probably other things

##### ENVIRONMENT
* AWX version: current

##### ADDITIONAL INFORMATION

Strawman proposal:

A new unified job type, 'distributed job', is created.

A 'distributed job' consists of a job template, 1-N inventories, and a 'slice size' (integer, better names welcome).

When executed, a distributed job calculates the size of its linked inventories (1-N), and splits each inventory into a number of chunks of size 'slice size'.  It then queues jobs of ansible-playbook runs on each chunk of the appropriate inventory, using `limit` to specify it.  These jobs follow normal scheduling behavior (number of forks, queueing due to capacity, assignation to instance groups based on inventory mapping).

A 'distributed job' status is calculated in the same manner as workflow jobs; failure if there are any unhandled failures in its sub-jobs.

Display of distributed job status/runs is.... `¯\_(ツ)_/¯`. We may re-use workflow display, or come up with something else entirely.

Documentation should have VERY LARGE warnings that any job that intends to orchestrate across hosts (rather than just applying changes to individual hosts) should not be configured as a distributed job. Any job that does may fail, and we will not attempt to discover or account for playbooks that fail when run as distributed jobs.

**Comment by AlanCoding** [comment]
From conversation with @stoleas @gamuniz and others:

The capacity impact of these jobs will be an interesting thing to figure out. We have a shortcoming of our current logic that if you use a `limit` for a job, the task impact does not take into account the number of hosts the limit would target, and instead counts all the hosts in the inventory.

For this feature, it should be easy to work around, but we may want an issue for that general issue.

**Comment by matburt** [comment]
I think it's probably fine since we're still under `min(forks, numhosts)` this isn't unique to split jobs.

**Comment by jlmitch5** [comment]
UI implications:
- add new “shading” number to jt form
- launch starts workflow instead of template run
- workflow node within workflow maker
- workflow results shows node as a workflow

**Comment by AlanCoding** [comment]
> workflow node within workflow maker

I don't think any change is necessary here. At the point of WFJT creation, it's just a job template. It's fully indistinguishable, and integration tests are covering this.

> workflow results shows node as a workflow

Some form of this is a mutual requirement with the workflow enhancements feature, see: https://github.com/ansible/awx/issues/2252, ping @chrismeyersfsu. A more minimal approach might be to label "workflow" on the node and correctly link to the workflow job. I think that's sufficient.

We have an early start on these, but they all need serious jazzing up:

 - shard count toggle on JT form
 - link to JT from workflow job
 - shard info on job details

Additional UI notes:

 - recent jobs needs to conditionally link to workflow job, but I am open to changing the contract, depending on UI needs
 - icons in job list view indicating that workflow is shard container, or that jobs are partials
 - possibly styling changes to boxes in recent jobs to indicate shard container vs. partials

**Comment by jakemcdermott** [comment]
please see linked issues for additional info, user stories, etc. if needed.

**Comment by wenottingham** [comment]
This is pretty much done.
