### ISSUE TITLE
Unable to enable core plugins

### ISSUE THREAD

**Issue by dberardo-com** [ansible/awx#12838]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I am unable to enable standard plugins like tree and profile_tasks via editing the ansible.cfg file.

i have referred to this issue: https://github.com/ansible/awx/issues/1948
and this piece of doc: https://docs.ansible.com/ansible-tower/2.4.0/html/administration/troubleshooting.html#locate-and-configure-the-configuration-file

### AWX version

17

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.9

### Steps to reproduce

* login into container as default user (awx) 
* create a new config file in the home folder "ansible.cfg"
* include this content in that config file

`
[defaults]
callbacks_enabled = profile_tasks, tree
`

### Expected results

The play should create a tree information in the tree folder and provide profiling information at the end of the run

### Actual results

configs are not properly read in or plugins are not loaded

**Comment by fosterseth** [comment]
hi @dberardo-com you might play around with enabling certain plugins in your ansible.cfg, and place that ansible.cfg in the root of your scm project directory https://docs.ansible.com/ansible/latest/plugins/inventory.html#enabling-inventory-plugins

**Comment by dberardo-com** [comment]
> hi @dberardo-com you might play around with enabling certain plugins in your ansible.cfg, and place that ansible.cfg in the root of your scm project directory https://docs.ansible.com/ansible/latest/plugins/inventory.html#enabling-inventory-plugins

thanks for the answer. i have figured out that i have to place the setting `defaults.callback_whitelist` in the /etc/ansible/ansible.cfg file to enabled them (https://docs.ansible.com/ansible/2.9/reference_appendices/config.html#default-callback-whitelist). Is it possible to have a more selective configuration per job template instead of having to use a single global configuration file? Are configuration also loaded from other files within the awx_task docker container (awx version 17+).

thanks

**Comment by djyasin** [comment]
Hello, 
To answer your question, we do not believe that this is configurable on a per job template instance.

Please consider contributing a PR for this following our contributing guidelines: https://github.com/ansible/awx/blob/devel/CONTRIBUTING.md
