### ISSUE TITLE
Unable to use machine credentials in a variable inside a task

### ISSUE THREAD

**Issue by Rakesh2904** [ansible/awx#12852]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### AWX version

NA

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

N/A

### Modifications

no

### Ansible version

2.9.xxx

### Operating system

Windows

### Web browser

Chrome

### Steps to reproduce

--- 
- 
  gather_facts: true
  hosts: all
  ignore_errors: true
  name: "Mapping a Network drive"
  tasks: 
    - name: creating a workspace directory
      become: true
      become_flags: "logon_type=new_credentials logon_flags=netcredentials_only"
      become_method: runas
      name: "Creating workspace"
      vars: 
        ansible_become_pass: "{{ password }}"
        ansible_become_user: "{{ user }}"
      win_file: 
        path: \\server_name\share_name\directory_to_be_created
        state: directory
  vars: 
    machine: 
      password: "{{ ansible_password }}"
      user: "{{ ansible_user }}"

### Expected results

The above should be able to create a folder in the network drive for the user which has enough permissions to do, verified manually by logging in to the server

But if I enter the credentials directly in the playbook I'm able to achieve this task

PS: the id that I've to use is a service account which I would not have control of so I need to call that variable and then use it the required tasks

### Actual results

PLAY [Mapping a Network drive] *************************************************
TASK [Gathering Facts] *********************************************************
ok: []
TASK [Creating workspace] ******************************************************
fatal: []: FAILED! => {"msg": "The field 'become_user' has an invalid value, which includes an undefined variable. The error was: 'user' is undefined"}

### Additional information

Any help/suggestion would be really helpful please

**Comment by Rakesh2904** [comment]
Is there anyone who could shed some light on this please?

**Comment by djyasin** [comment]
Hello,
We would like to gather some more information from you. What   `ansible_winrm_transport` are you using to connect to your Windows machines?

**Comment by Rakesh2904** [comment]
I've tried Kerberos, NTLM and CredSSP, if this is what you meant

**Comment by Rakesh2904** [comment]
This is how the actual play looks like

images.githubusercontent.com/109726454/190201256-18f80f94-cc28-4bcb-8cf7-311779665f5f.png)

**Comment by Rakesh2904** [comment]
Apparently I missed the basic step to use this feature, this helps but make sure there is no_logs: true is enabled

    - name: Gathering machine username and password
      no_log: true
      set_fact:
        machine_user: "{{ ansible_user }}"
        machine_password: "{{ ansible_password }}"
