### ISSUE TITLE
[UI] "Run every" template string not interpolated when setting a JT/project schedule

### ISSUE THREAD

**Issue by relrod** [ansible/awx#12858]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Seeing this on devel (ran a fresh `make ui-devel` just to be safe, but this still appears).

![image](https://user-images.githubusercontent.com/43930/189293944-0bb3de48-349a-4f3f-8d88-3782efc49041.png)

### AWX version

devel

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Steps to reproduce

Create a JT or project schedule, enable repeat frequency, save.

### Expected results

A human readable, interpolated string.

### Actual results

An uninterpolated string appeared.

**Comment by AlexSCorey** [comment]
This may not be a bug.  It may simple show up that way because the strings have not yet been compiled.  
@keithjgrant can you confirm?
