### ISSUE TITLE
Jobs with a multiplechoice field in its survey spec do not launch in AWX 17.1.0

### ISSUE THREAD

**Issue by shaaga** [ansible/awx#12879]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Jobs with a mutliplechoice field in its survey spec do not launch, browser console throws error.

### AWX version

17.1.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

4.10.0

### Operating system

Ubuntu 18.04

### Web browser

Chrome

### Steps to reproduce

Create a job template with a survey spec that has a multiplechoice field. 

Click the launch icon to the right of the job name from the /templates screen.

### Expected results

Screen to launch the job should load.

### Actual results

A blank screen loads. The javascript console in Chrome shows the following error:

```
asyncToGenerator.js:6 Uncaught (in promise) TypeError: t.choices.split is not a function
    at gd (SurveyStep.jsx:109)
    at Xo (react-dom.production.min.js:153)
    at vs (react-dom.production.min.js:261)
    at cl (react-dom.production.min.js:246)
    at sl (react-dom.production.min.js:246)
    at Qs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Hi (react-dom.production.min.js:122)
    at Gi (react-dom.production.min.js:123)
```

**Comment by shaaga** [comment]
Found a similar issue reporting the same issue on AWX 16.x, the issue is closed without the fix mentioned in it.
https://github.com/ansible/awx/issues/9058

**Comment by Vesperino** [comment]
You should install with kubernetes ver 21+ doesn't have that issue

**Comment by shaaga** [comment]
Our deployment env uses docker-compose. Is it not possible to patch AWX v17 with the fix?

**Comment by ffirg** [comment]
Fixed in https://github.com/ansible/awx/pull/12038

**Comment by shaaga** [comment]
@djyasin please dont close incidents without the opener confirming prob is fixed.

I want to apply the patch in the https://github.com/ansible/awx/pull/12038 to AWX 17 but I cannot find the SurVeyQuestion* files in the awx_task container. Where are these files present?
