### ISSUE TITLE
AWX kubernetes awx-ee dont see new galaxy collection 

### ISSUE THREAD

**Issue by Vesperino** [ansible/awx#12880]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

```
ERROR! couldn't resolve module/action 'chocolatey.chocolatey.win_chocolatey'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/runner/project/playbooksWindows/Install_7zip.yml': line 19, column 7, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
    - name: install 7zip packages
      ^ here
```

galaxy collections on ee container :
```
# /home/runner/.ansible/collections/ansible_collections
Collection            Version
--------------------- -------
ansible.windows       1.11.1
chocolatey.chocolatey 1.3.0

# /usr/share/ansible/collections/ansible_collections
Collection              Version
----------------------- -------
amazon.aws              4.1.0
ansible.posix           1.4.0
ansible.windows         1.11.1
awx.awx                 21.5.0
azure.azcollection      1.13.0
community.vmware        2.9.1
google.cloud            1.0.2
kubernetes.core         2.3.2
openstack.cloud         1.9.1
ovirt.ovirt             2.2.3
redhatinsights.insights 1.0.7
theforeman.foreman      3.6.0
bash-4.4$
```

On old version 17.1 on docker everything works fine. 

### AWX version

21.5.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

ansible [core 2.12.5.post0]

### Operating system

Ubuntu 20.04

### Web browser

Chrome

### Steps to reproduce

Install AWX with kuberenetes

Create playbook:

```
---
- name: "Chocolatey"
  hosts: windows
  tasks:
    - name: Install chocolatey
      win_chocolatey:
          name:
           - chocolatey
           - chocolatey-core.extension
          state: present
```
install needed galaxy collection on awx-ee container

kubectl get pods -n awx  or kubectl get pods

copy name of pod with 4/4 containers 

kubectl --namespace=awx exec -ti name_of_pod -c awx-task -- /bin/bash

install collection -> ansible-galaxy collection install chocolatey.chocolatey

### Expected results

PLAY RECAP *********************************************************************
Windows workstationTEST    : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

### Actual results

ERROR! couldn't resolve module/action 'chocolatey.chocolatey.win_chocolatey'. This often indicates a misspelling, missing collection, or incorrect module path.

### Additional information

On ver 17.1 with docker works fine

**Comment by Vesperino** [comment]
Need just add folder to project -> collections -> requirements.yaml
Then add to organization of project credentials for galaxy

**Comment by r31mong** [comment]
> Need just add folder to project -> collections -> requirements.yaml Then add to organization of project credentials for galaxy

will this work also on AWX? can you elaborate?
