### ISSUE TITLE
stdout capture is missing in result_stdout of workflow_jobs

### ISSUE THREAD

**Issue by pravindmali** [ansible/awx#1289]
##### ISSUE TYPE
 - RFE

##### COMPONENT NAME

 - API

##### SUMMARY
When I run the workflow job in tower and from the interface, I can see on the interface is graphical presentation and status of job template.  But when I look at the (api/v2/workflow_jobs/job_id) "result_stdout" on workflow_jobs, the result is stdout out capture is missing.

##### ENVIRONMENT
* AWX version: 1.0.0
* Ansible version:  2.4.1
* Operating System: RHEL 7

##### STEPS TO REPRODUCE

1] Run workflow template on tower.
2] After job run, go to `https://<tower>/api/v2/workflow_jobs/job_id` and check for "result_stdout" it shows 
~~~
"result_stdout": "stdout capture is missing",
~~~

##### EXPECTED RESULTS

It should show complete successful/ failed output. 

##### ACTUAL RESULTS

But its showing :  "result_stdout": "stdout capture is missing",

**Comment by AlanCoding** [comment]
Workflow jobs are a container for other jobs, and using the result_stdout for this kind of thing would be an abuse of the field. Maybe it would be better to give a more specific error message?

Clients need to put together their own representation of the workflow job network, for an example, the CLI does a textual job-by-job summary with `tower-cli workflow_job summary`. But the idea that the API would construct this for the client is something I don't necessarily agree with.

**Comment by AlanCoding** [comment]
On second look, I'm not sure how you got to "result_stdout". I don't see either a field for this or a related link for this on endpoints like `/api/v2/workflow_jobs/8/`.
