### ISSUE TITLE
add validation for hostname field for the Instance object

### ISSUE THREAD

**Issue by TheRealHaoLiu** [ansible/awx#12936]
current hostname field for the instance table have no validation and this allows user to put invalidate value into the field

**Comment by TheRealHaoLiu** [comment]
`[a-z0-9]([-a-z0-9]*[a-z0-9])?` may be a good enough regex

**Comment by TheRealHaoLiu** [comment]
this warrants additional discussion due to potential impact for existing install

FYI @sarabrajsingh

**Comment by sarabrajsingh** [comment]
unit tests for supporting:
- [x] ipv4
- [x] ipv6
- [x] simple hostname
- [x] hostnames with domains or subdomains

**Comment by TheRealHaoLiu** [comment]
conversation with @Zokormazo and @AlanCoding confirm that i is save to add this validation to the API serializer 
and we should add it 

FYI @jbradberry

**Comment by AlanCoding** [comment]
I also want to link https://github.com/ansible/awx/issues/3384, as it may involve effectively the same or similar logic.
