### ISSUE TITLE
Workflow approval displays wrong variables in "Workflow job details" if multiple workflows are submitted

### ISSUE THREAD

**Issue by Zaephor** [ansible/awx#12930]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When multiple survey'd workflows containing an approval step are submitted, the approval details page provides the survey answers from the wrong workflow submission.
This can cause the reviewer to approve or deny the job under invalid pretense.

![Screenshot from 2022-09-20 13-14-54](https://user-images.githubusercontent.com/3262370/191355916-8fea518a-e156-4285-937f-1d919ce9d591.png)
![Screenshot from 2022-09-20 13-15-07](https://user-images.githubusercontent.com/3262370/191355920-ef46db59-9c6d-4d64-ba21-29dda1e0f3ed.png)

### AWX version

21.6.0

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

Setup:
* Create new workflow template
  * I left "Enable Concurrent Jobs" disabled, I suspect this would result in multiple Approvals with the same variables
* In the visual-editor, create an Approval node. Save the workflow
* Add a survey question to the new Workflow template
  * Contents again don't particularly matter
* Enable the Survey

Reproduce
* Launch the workflow X times
  * Set the value of the survey to something different each time, for example, which submission number it is. 1..2..3..etc
* Check first approval node, variables value will match the final submission, not the matching one.
* If the Workflow Approval is approved, the first submission will progress/execute with the original variables, and the next Workflow Approval will appear in the same state(wrong varaibles)
![Peek 2022-09-20 13-07](https://user-images.githubusercontent.com/3262370/191358906-94e73a22-39bd-49b6-8748-5a6e308a658b.gif)

![Screenshot from 2022-09-20 13-14-54](https://user-images.githubusercontent.com/3262370/191359171-e4558d3d-5104-4254-80aa-b01dc2c35a3c.png)
![Screenshot from 2022-09-20 13-15-07](https://user-images.githubusercontent.com/3262370/191359174-44fbdbfd-32f7-4d9d-8838-6deb2dafb65b.png)

### Expected results

Having submitted the same workflow 5 times with 5 different variable values, I would expect the variables displayed in the Workflow Approval prompt to match the workflow that triggered the approval.

For example, if I have a workflow for deploying something to deployment "X" requiring approval, so I queue the jobs up for "dev", "staging" and "prod". The approval screen will imply that the workflow is configured to deploy to prod in all cases.

### Actual results

![Screenshot from 2022-09-20 13-14-54](https://user-images.githubusercontent.com/3262370/191359986-3a6890e5-e2b9-43c6-886e-e7922d9ae897.png)
![Screenshot from 2022-09-20 13-15-07](https://user-images.githubusercontent.com/3262370/191359989-e7614676-87ec-48f7-88cb-bcb0f98a005a.png)

### Additional information

Following the API calls in the browser flow/logic feels like:
* page calls `/api/v2/workflow_approvals/11346/`, finds `37` for the `workflow_job_template` from `.summary_fields.workflow_job_template.id`
* page calls `/api/v2/workflow_job_templates/37/`, finds `11348` for the `workflow_job` from `.summary_fields.current_job.id`
* page calls `/api/v2/workflow_jobs/11348/`, which is the most recent submission, not the one that triggered the workflow approval
  * This data probably should be loaded from from the first API call's from `.summary_fields.source_workflow_job.id` or `.related.source_workflow_job` if it's using the API url's directly.

Where 11345 was my first workflow execution, 11346 is it's pending workflow approval, and 11348 was my last/third workflow execution.

**Comment by azrdev** [comment]
I do see the same problem on our AWX 21.1.0 installation

**Comment by lucasvivian** [comment]
Same here. Version: 21.1.11

**Comment by mlvgn** [comment]
Same problem 21.8.0
