### ISSUE TITLE
awxkit: TestOptions.test_actions_with_primary_key fails with Python 3.11

### ISSUE THREAD

**Issue by mgorny** [ansible/awx#12938]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When running the awxkit's test suite against Python 3.11, I get one failing test:

```
______________________________________________ TestOptions.test_actions_with_primary_key ______________________________________________
Traceback (most recent call last):
  File "/tmp/awx/awxkit/test/cli/test_options.py", line 180, in test_actions_with_primary_key
    ResourceOptionsParser(None, page, 'jobs', self.parser)
  File "/tmp/awx/awxkit/awxkit/cli/options.py", line 98, in __init__
    self.build_list_actions()
  File "/tmp/awx/awxkit/awxkit/cli/options.py", line 117, in build_list_actions
    parser = self.parser.add_parser(method, help='')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 1185, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
argparse.ArgumentError: argument {list,create,get,modify,delete,stdout,monitor}: conflicting subparser: list
```

While Python 3.11 has increased the strictness of argparse error reporting, the underlying problem probably affects all Python versions.

### AWX version

tested with 1b9326888e0b175abe0cd5c70aa8ad31431dc3e8

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Ansible version

n/a

### Operating system

Gentoo Linux

### Steps to reproduce

```
cd awxkit
sed -i '/basepython/d' tox.ini
tox -e py311
``

### Expected results

Tests passing ;-).

### Actual results

Test failure (pasted in summary).

### Additional information

_No response_

**Comment by fosterseth** [comment]
need to do some investigation around this

**Comment by fosterseth** [comment]
@mgorny it appears we currently only test on 3.9 as part of our test matrix. Have you ran these against 3.9 by chance?

**Comment by mgorny** [comment]
Yes, up to 3.10 the tests pass (or at least passed at the time).

**Comment by jbradberry** [comment]
PR: https://github.com/ansible/awx/pull/13174

**Comment by mgorny** [comment]
Thank you!

**Comment by mgorny** [comment]
I'm sorry for testing this late but the PR doesn't fix the problem, actually. The tests still fail with the same error as pasted above. I suspect it's because they're complaining about the duplicate "list" subparser, not "config".
