### ISSUE TITLE
Absence of Jobs LoadBalancer when scaling up the AWX pod

### ISSUE THREAD

**Issue by Yiadh** [ansible/awx#1294]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- AWX

##### SUMMARY
Unable to run more than 4 jobs simultaneously
Absence of Jobs LoadBalancer when scaling up the AWX pod

##### ENVIRONMENT
* AWX version: 1.0.3
* AWX install method: openshift
* Ansible version:  2.4.2.0 
* Operating System: Centos7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

I cannot run more than 4 jobs simultaneously: Always 4 jobs running and the others are in the waiting list. Whatever the amount of resources I have, I obtain the same result. I tried it with 4 and 10GB. Always the same result!

I scaled up the awx pod to 2. On the UI I can see the 2 instances, but always an only one instance is handling the jobs, the other one is idle. Sometimes they change the roles but they do not serve the jobs queue in the sametime.

##### EXPECTED RESULTS

Having 50 jobs running simultaniously (no jobs in the waiting queue)
Having two awx instances serving the jobs queue in the same time.

##### ACTUAL RESULTS

Whatever the resources quota, the awx instance handles 4 jobs simultaneously and puts the rest in the waiting queue.
The awx instances do not serve the jobs list in the sametime. Always one is working and the other one is idle.

##### ADDITIONAL INFORMATION

In order to run more than 4 jobs in the sametime, I tried the command:
awx-manage celery control pool_grow 50
I succeded to run 50 jobs in the sametime, and all of them succeded. I scheduled these jobs to run every 10 minutes. After one hour, the  instance become not able to run jobs. The logs do not show any problems.

**Comment by matburt** [comment]
Let me see if I can reproduce this.

For the record, you should not mess (or have to mess with) the celery pool. That would also likely only affect one host anyway.

**Comment by Yiadh** [comment]
Hello @matburt 
Any news about the mentionned above issue?

**Comment by matburt** [comment]
We've been hammering away on celery and stuff for the last few days... can you try the latest builds under 1.0.4?

**Comment by rfabbris** [comment]
We are facing the same issue, even with version 1.0.4. @Yiadh you managed to fix the problem?

**Comment by matburt** [comment]
This should be fixed with #1534
