### ISSUE TITLE
Jobs taking exceptionally long time after upgrading to AWX V17.1.0 from AWX v3.0

### ISSUE THREAD

**Issue by shaaga** [ansible/awx#12957]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Previous setup:

AWX v3.0 running on a Ubuntu16.04 vm with below configurations:
a. python 2.7
b. ansible 2.7.4
c. postgres: v7

Current setup:

AWX V17.1.0 running on an Ubuntu18.04 vm with below configurations:
a. python 3.6
b. ansible 4.10.0
c. postgres: v9.6
d. rabbitmq: v3.9
e. memcached: v1.6

Jobs which were completing under 15mins in the previous setup suddenly started taking more than 1hr. Almost all of the jobs are impacted. They pass eventually but are taking way longer time.

**Dockerfile of awx task and web containers:**

```
FROM ansible/awx:17.1.0

USER 0

# Fix for Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
RUN cd /etc/yum.repos.d/ && \
    sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

ADD yum-requirements.txt /tmp/yum-requirements.txt
RUN yum install -y $(cat /tmp/yum-requirements.txt) && \
    rm /tmp/yum-requirements.txt

# Install pip requirements
ARG PIP3_BUILD_PACKAGES="gcc python3-devel libxml2-devel libxslt-devel"
ADD requirements.txt /tmp/requirements.txt
# ansible cannot be upgraded from existing 2.x version to the required 4.x version, so uninstalling it first
RUN yum -y install $PIP3_BUILD_PACKAGES && \
    pip3 uninstall -y ansible && \ 
    /var/lib/awx/venv/ansible/bin/pip3 install --no-cache-dir -r /tmp/requirements.txt && \
    yum -y remove $PIP3_BUILD_PACKAGES && \
    yum clean all && \
    rm -rf /var/cache/yum
```

**yum-requirements.txt**

`expect`

**requirements.txt**

```
diskcache==4.1.0
ansible==4.10.0
ansible-core==2.11.12
ansible-cached-lookup==1.0.0
ansible-tower-cli==3.3.9
dnspython==1.16.0
future==0.17.0
nsxramlclient_py3==2.0.8
prettytable==0.7.2
psutil>=5.4.8
pymsteams==0.1.12
pyvmomi==6.7.3
# Azure requirements, coming from Ansible 2.8 (upcoming version)
packaging==21.3
requests[security]==2.27.1
random-password-generator
azure-cli-core==2.31.0
azure-cli-nspkg==3.0.2
azure-mgmt-authorization==1.0.0
azure-mgmt-batch==15.0.0
azure-mgmt-cdn==3.0.0
azure-mgmt-compute==4.4.0
azure-mgmt-containerinstance==1.4.0
azure-mgmt-containerregistry==2.0.0
azure-mgmt-containerservice==4.4.0
azure-mgmt-dns==2.1.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-monitor==0.5.2
azure-mgmt-network==2.3.0
azure-mgmt-nspkg==2.0.0
azure-mgmt-redis==5.0.0
azure-mgmt-resource==2.1.0
azure-mgmt-rdbms==1.4.1
azure-mgmt-servicebus==0.5.3
azure-mgmt-sql==0.10.0
azure-mgmt-storage==3.1.0
azure-mgmt-trafficmanager==0.50.0
azure-mgmt-web==0.41.0
azure-nspkg==2.0.0
azure-storage==0.35.1
msrest==0.6.1
msrestazure==0.5.0
azure-graphrbac==0.40.0
azure-mgmt-cosmosdb==0.5.2
azure-mgmt-hdinsight==0.1.0
azure-mgmt-devtestlabs==3.0.0
azure-mgmt-loganalytics==0.2.0
# Our local module Azure requirements, not in upstream:
azure-mgmt-msi==0.2.0
opencensus-ext-azure
opencensus-ext-logging
fluent-logger==0.9.6
```

### AWX version

17.1.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

yes

### Ansible version

4.10.0

### Operating system

Ubuntu 18.04

### Web browser

Chrome

### Steps to reproduce

Build the dockerfile and install the containers and then run jobs.

### Expected results

jobs taking almost same time or lesser than on the awx v3.x.

### Actual results

Job runtime increased by a factor of 4 times almost for all the jobs.

**Comment by djyasin** [comment]
Hello, this appears to be less of a bug report or feature request and more of a question. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.

**Comment by fosterseth** [comment]
Thanks for detailing your issue. Unfortunately, we don't support v17 or v3 anymore, so we'll close the issue for now. Please feel free to open a thread on the mailing list, as linked above.
