### ISSUE TITLE
awx-manage generateschema: coreapi pip package is missing

### ISSUE THREAD

**Issue by PaulVerhoeven1** [ansible/awx#12958]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I just installed awx 21.6.0 on K8S with the operator. When i jump into the awx-task pod (which uses the awx 21.6.0 image) and
run the following command: `awx-manage generateschema`
 
Then i got the following error:

```
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/__init__.py", line 201, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/rest_framework/management/commands/generateschema.py", line 35, in handle
    generator = generator_class(
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/rest_framework/schemas/coreapi.py", line 120, in __init__
    assert coreapi, '`coreapi` must be installed for schema support.'
AssertionError: `coreapi` must be installed for schema support.
```

As given in the error it's stated that awx is missing the coreapi pip package.

When i do a `pip list`, i can see that's also the case:
```
Package         Version
--------------- -----------
dbus-python     1.2.18
distlib         0.3.6
dumb-init       1.2.5.post1
filelock        3.8.0
gpg             1.15.1
libcomps        0.1.18
pip             21.2.3
platformdirs    2.5.2
psycopg2        2.8.6
python-dateutil 2.8.1
rpm             4.16.1.3
selinux         3.4
setuptools      53.0.0
six             1.15.0
supervisor      4.2.4
virtualenv      20.16.5`
```

### AWX version

21.6.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

As stated in the bug above ^

### Expected results

A working output of the API spec of awx

### Actual results

As stated in the bug above ^

**Comment by fosterseth** [comment]
@PaulVerhoeven1 were you able to resolve this?

what if you manually pip install `coreapi` and and re-run? they need to source the awx venv first

`source /var/lib/awx/venv/awx/bin/activate`

**Comment by akus062381** [comment]
Hi @PaulVerhoeven1,

Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
