### ISSUE TITLE
Deleting job from inventory's COMPLETED JOBS does not remove it from UI list

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#1296]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Clicking the trash bucket for an inventory's completed job in the UI does not remove it from the UI list, even though it is deleted on the backend.

##### ENVIRONMENT
* AWX version: 1.0.3-174
* AWX install method: docker for mac
* Ansible version:  N/A
* Operating System: Mac
* Web Browser: Chrome 64.0.3282.119 (Official Build) (64-bit)

##### STEPS TO REPRODUCE

Go to the COMPLETED JOBS tab for an inventory.

Delete a job.

##### EXPECTED RESULTS

Deleted job is deleted and removed from list.

##### ACTUAL RESULTS

Deleted but not removed from list.

![delete_completed_job](https://user-images.githubusercontent.com/1385596/36388339-863e35d4-1569-11e8-8091-abacfa207b50.gif)

Page refresh removes it

##### ADDITIONAL INFORMATION

Trash can button in the global JOBS list does remove it.

No errors in console.

**Comment by jaredevantabor** [comment]
This is fixed in devel.
