### ISSUE TITLE
AWX Applications - A server error has occured (errcode 500)

### ISSUE THREAD

**Issue by ecurti** [ansible/awx#12978]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hello,
I've deployed in my aks cluster AWX with awx-operator 0.28.0 with external postgres db configuration.
It's not a clean installation, I'm using a db from a previous AWX version (3.0.1.0).

When I click on Application menù I receive an internal server error:
```
2022-09-21 10:08:28,819 ERROR    [2f9c4cc6f70d45b4af66e8983b5f0624] django.request Internal Server Error: /api/v2/applications/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/cryptography/fernet.py", line 120, in _verify_signature
    h.verify(data[-32:])
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/cryptography/hazmat/primitives/hmac.py", line 69, in verify
    ctx.verify(signature)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 76, in verify
    raise InvalidSignature("Signature did not match digest.")
cryptography.exceptions.InvalidSignature: Signature did not match digest.
```

### AWX version

21.5.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

Install AWX with aewx-operator.

Specify "postgres_configuration_secret" in AWX spec for external db (previous AWX version) and create the secret in same namespaces.
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: nodeport
  postgres_configuration_secret: awx-db-postgres-configuration
```

```
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-db-postgres-configuration
  namespace: awx
stringData:
  host: '<host_url>'
  port: '5432'
  database: awx
  username: admin_awx
  password: '<pwd>'
  sslmode: require
  type: unmanaged
type: Opaque
```

### Expected results

List "Applications" configured in previous AWX version.

### Actual results

A server error has occured (errcode 500) from "Applications" menù.

**Comment by ecurti** [comment]
I've found a solution to this issue clearing "Applications" tables on awx database.

So I've deleted records for applications config in main table "main_oauth2application" but first related tables "main_oauth2accesstoken", "oauth2_provider_refreshtoken" only for the records affected. 

I had to re-insert applications configuration but now works fine.

**Comment by aimcod** [comment]
On a similar note, for a brand new installation of 21.5.0,  also with an external postgres database, that was upgraded to 21.8.0 earlier today, the Applications page became unavailable.

I don't know if this upgrade caused it, a previous one, or something else, as i only noticed today.


My issue was generated by something in the activity stream table for activities 
/api/v2/activity_stream/140/ and /api/v2/activity_stream/139/

There was a token created at some point for the _bash_ application. 

To resolve this, I deleted all relations for the token from the following tables:

```
main_activitystream_o_auth2_application

main_oauth2accesstoken

main_oauth2application 

oauth2_provider_refreshtoken

main_activitystream_o_auth2_access_token
```

This is also the API information as well as the token entry from the DB. Nothing looks bad…Also note that I had just upgraded AWX today and I was accessing applications after the upgrade. Before today, I can’t remember when I accessed that page for the last time, but it was probably on the 21nd of October. :)

```
HTTP 200 OK Allow: GET, HEAD, OPTIONS Content-Type: application/json Vary: Accept X-API-Node: loki-7cbd4888d6-hph4k X-API-Product-Name: AWX X-API-Product-Version: 21.8.0 X-API-Time: 0.034s  {     "id": 139,     "type": "activity_stream",     "url": "/api/v2/activity_stream/139/",     "related": {         "actor": "/api/v2/users/1/"     },     "summary_fields": {         "actor": {             "id": 1,             "username": "admin",             "first_name": "",             "last_name": ""         }     },     "timestamp": "2022-10-21T11:30:45.043907Z",     "operation": "create",     "changes": {         "name": "bash",         "description": "",         "client_type": "confidential",         "redirect_uris": "https://ansible.aimcorp.co.uk/",         "authorization_grant_type": "authorization-code",         "skip_authorization": false,         "organization": "Default-1",         "id": 1     },     "object1": "o_auth2_application",     "object2": "",     "object_association": "",     "action_node": "loki-dd4c549f4-pngzh",     "object_type": "" }
```

```
HTTP 200 OK Allow: GET, HEAD, OPTIONS Content-Type: application/json Vary: Accept X-API-Node: loki-7cbd4888d6-hph4k X-API-Product-Name: AWX X-API-Product-Version: 21.8.0 X-API-Time: 0.036s  {     "id": 140,     "type": "activity_stream",     "url": "/api/v2/activity_stream/140/",     "related": {         "actor": "/api/v2/users/1/"     },     "summary_fields": {         "actor": {             "id": 1,             "username": "admin",             "first_name": "",             "last_name": ""         }     },     "timestamp": "2022-10-21T11:31:30.549299Z",     "operation": "create",     "changes": {         "description": "",         "application": "bash",         "scope": "write",         "id": 1,         "token": "************"     },     "object1": "o_auth2_access_token",     "object2": "",     "object_association": "",     "action_node": "loki-dd4c549f4-pngzh",     "object_type": "" }
```

```
 id |             token              | access_token_id | application_id | user_id |            created            |            updated            | revoked 
----+--------------------------------+-----------------+----------------+---------+-------------------------------+-------------------------------+---------
  1 | CyiHOuzUhy4y25L4PnKRmFzuTnEbFX |               1 |              1 |       1 | 2022-10-21 13:31:30.568923+02 | 2022-10-21 13:31:30.568939+02 |

```
