### ISSUE TITLE
In AWX 15.0.0 when I click on completed jobs tab it gives Invalid search term entered. GET returned: 504 msg.

### ISSUE THREAD

**Issue by emran119** [ansible/awx#12972]
##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 
 - UI

##### SUMMARY

In AWX 15.0.0 when I click on completed jobs tab it gives Invalid search term entered. GET returned: 504 msg.
And from couple of days this error has become frequent which makes using AWX almost unusable for me and my team. It sometimes throws the same error for other tabs but for completed jobs tab its consistent and never moves forward. It keeps showing this error.

##### ENVIRONMENT
* AWX version: 15.0.0
* AWX install method: operator
* AWX deployment target: openshift,
* Operating System: RHEL
* Web Browser: Chrome and Firefox but mostly Chrome

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/1010868/192781388-48a38921-6d6f-424b-8ffe-4c05f1bcb5ac.png)
![invalid 504 error](https://user-images.githubusercontent.com/1010868/192781483-e5c27c59-5e7d-4a30-9d18-01458f517567.JPG)

**Comment by fosterseth** [comment]
Hello! thanks for including the screenshots, that is always helpful. This issue pertains to an older version of AWX that we don't support. Please try upgrading to the latest version and let us know if that resolves your issue.
