### ISSUE TITLE
LDAP refuses valid URL because of host

### ISSUE THREAD

**Issue by JumpIfBelow** [ansible/awx#12970]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When filling the LDAP URL, I am unable to save the settings as it detects the URL as wrongly formatted.
For example, I have such input: `ldap://subdomain.example.s`. As the root domain is too short in the eyes of AWX, it is simply refused while this URL is completely valid and known internally, and obviously working with several applications.

If I trick it to add another letter at the end of it, with `ldap://subdomain.example.ss`, it accepts the URL.

### AWX version

21.3.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

minikube

### Modifications

no

### Steps to reproduce

1. Go to "Settings" > "LDAP Settings"
2. Set a LDAP URL ending with only 1 character at the end of the host (domain) part
3. Save the form

### Expected results

The form is saved successfully and I can set up an LDAP with a domain ending with only one character as its root.

### Actual results

The URL is rejected as being wrongly formatted.

### Additional information

It looks like it only accepts any URL with a root domain name with at least 2 characters, no matter which ones you are using.

**Comment by djyasin** [comment]
Hello,
At this time there is a minimum of at least two characters for top-level domains. For more information, please see: https://www.icann.org/en/system/files/files/ua-factsheet-a4-17dec15-en.pdf

Please let us know if revising to two characters resolves this for you.

**Comment by fosterseth** [comment]
closing issue for now, please open a new one if you feel it is not resolved.
