### ISSUE TITLE
AWX connecting to RHEL host as root instead of username from credentials

### ISSUE THREAD

**Issue by Murf** [ansible/awx#12982]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When using "Run Command" on a target RHEL server in the inventory hosts using "command" module and parameter "id" the connection is made using user="root" instead of my credentials username

### AWX version

21.3.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

openshift

### Modifications

no

### Ansible version

Whatever AWX uses

### Operating system

Openshift/OKD (fedora coreOS)

### Web browser

Chrome

### Steps to reproduce

1. Create a machine credential with a non root username
2. Create an inventory item for a RHEL host
3. Select the host and use "RUN COMMAND"
4. Use "command" module and "id" argument, use same credential created in step 1 and set debug verbosity to level 3

In the job output you will see the following or similar:
<myhostname.local> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/home/runner/.ansible/cp/1e6060cc9b"' myhostname.local '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''

### Expected results

<myhostname.local> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'User="username_used_in_credential"' -o ConnectTimeout=10 -o 'ControlPath="/home/runner/.ansible/cp/1e6060cc9b"' myhostname.local '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''

### Actual results

<myhostname.local> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/home/runner/.ansible/cp/1e6060cc9b"' myhostname.local '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''

**Comment by Murf** [comment]
Updated to AWX 21.7 and still have the same issue.

This can also be explained as the following:

Here is my playbook, and the settings to use the machine credential username, yet it still does ssh as user=root


---
- name: Update Packages
  hosts: "{{ vm_inventory_group }}"
  become: yes
  become_method: sudo
  gather_facts: yes

  roles:
    - update_rhel_packages
  vars:
    machine:
      username: '{{ ansible_user }}'

**Comment by djyasin** [comment]
Hello, this appears to be less of a bug report or feature request and more of a question. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information on ways to connect with us.

**Comment by Murf** [comment]
@djyasin Sure I can do that, though i disagree with your classification. I look forward to being proven wrong.

**Comment by Murf** [comment]
For anyone else who ever has this problem dont put this in the Inventory Yaml :(
username: root
