### ISSUE TITLE
AWX SAML User Flags Attribute Mapping: Expect a list of elements

### ISSUE THREAD

**Issue by RogerSik** [ansible/awx#13014]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I wanted to configure the "SAML User Flags Attribute Mapping" like in descripted https://github.com/ansible/awx/blob/devel/docs/auth/saml.md but get following error: 

![07_13-40-13](https://user-images.githubusercontent.com/165814/194545101-b1f23e16-4d2f-40eb-b623-6e92f0b8cc07.png)

Not sure where / what i do wrong. The SAML login itself works fine but i have no (much more) permissions. 

### AWX version

21.7.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Operating system

AWS EKS

### Steps to reproduce

Setup SAML und than configure "SAML User Flags Attribute Mapping"

### Expected results

Successfull saving so user can login over SAML with more permissions.

### Actual results

Error message. See screenshot in description.

**Comment by RogerSik** [comment]
Same in SAML Organization Map:

![07_13-44-55](https://user-images.githubusercontent.com/165814/194545672-9150ec87-e4eb-49c9-b51a-af505d668eed.png)

**Comment by sarabrajsingh** [comment]
hi @RogerSik,

check out section 17 here - https://docs.ansible.com/automation-controller/latest/html/administration/ent_auth.html#saml-settings

specficially:
```
The role and value fields are lists and are or logic. So if you specify two roles: [ “Role 1”, “Role 2” ] and the SAML user has either role the logic will consider them to have the required role for the flag. This is the same with the value field, if you specify: [ “Value 1”, “Value 2”] and the SAML user has either value for their attribute the logic will consider their attribute value to have matched.
```

the `role` and `value` fields should be a list and not a string-type.

it seems like our documentation is out of date. we will take the appropriate steps to rectify that mistake on our end.

thanks,
AWX Team
