### ISSUE TITLE
failed to emit log to external aggregator

### ISSUE THREAD

**Issue by akcrisp** [ansible/awx#1301]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI
 - Installer

##### SUMMARY
Getting failed to emit log to external aggregator - even when there isn't one configured, I was testing splunk but have reverted all to defaults in UI.

Feb 20 11:18:41 HOSTNAME journal: 2018-02-20 11:18:41,702 ERROR    awx.main.utils.handlers failed to emit log to external aggregator. Its also attempting to then talk via our proxy (ReadTimeout: HTTPConnectionPool(host='xx.yy.zz.xx', port=8080)

##### ENVIRONMENT
* AWX version: 10.1.173
* AWX install method: docker on linux
* Ansible version:  2.4.3
* Operating System: RHEL 7.4
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Constant output in /var/log/messages

##### EXPECTED RESULTS

no error !

##### ACTUAL RESULTS

Output below sanitised.

Feb 20 11:18:41 HOSTNAME journal: 2018-02-20 11:18:41,702 ERROR    awx.main.utils.handlers failed to emit log to external aggregator
Feb 20 11:18:41 HOSTNAME journal: Traceback (most recent call last):
Feb 20 11:18:41 HOSTNAME journal:  File "/usr/lib/python2.7/site-packages/awx/main/utils/handlers.py", line 75, in _wrapped
Feb 20 11:18:41 HOSTNAME journal:    return func(*args, **kwargs)
Feb 20 11:18:41 HOSTNAME journal:  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/requests_futures/sessions.py", line 73, in wrap
Feb 20 11:18:41 HOSTNAME journal:    resp = sup(*args_, **kwargs_)
Feb 20 11:18:41 HOSTNAME journal:  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/requests/sessions.py", line 518, in request
Feb 20 11:18:41 HOSTNAME journal:    resp = self.send(prep, **send_kwargs)
Feb 20 11:18:41 HOSTNAME journal:  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/requests/sessions.py", line 639, in send
Feb 20 11:18:41 HOSTNAME journal:    r = adapter.send(request, **kwargs)
Feb 20 11:18:41 HOSTNAME journal:  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
Feb 20 11:18:41 HOSTNAME journal:    raise ReadTimeout(e, request=request)
Feb 20 11:18:41 HOSTNAME journal: ReadTimeout: HTTPConnectionPool(host='xx.yy.zz.xx', port=8080): Read timed out. (read timeout=5)
Feb 20 11:18:41 HOSTNAME journal: [2018-02-20 11:18:41,702: ERROR/ForkPoolWorker-98] failed to emit log to external aggregator
Feb 20 11:18:41 HOSTNAME journal: Traceback (most recent call last):
Feb 20 11:18:41 HOSTNAME journal:  File "/usr/lib/python2.7/site-packages/awx/main/utils/handlers.py", line 75, in _wrapped
Feb 20 11:18:41 HOSTNAME journal:    return func(*args, **kwargs)
Feb 20 11:18:41 HOSTNAME journal:  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/requests_futures/sessions.py", line 73, in wrap
Feb 20 11:18:41 HOSTNAME journal:    resp = sup(*args_, **kwargs_)
Feb 20 11:18:41 HOSTNAME journal:  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/requests/sessions.py", line 518, in request
Feb 20 11:18:41 HOSTNAME journal:    resp = self.send(prep, **send_kwargs)
Feb 20 11:18:41 HOSTNAME journal:  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/requests/sessions.py", line 639, in send
Feb 20 11:18:41 HOSTNAME journal:    r = adapter.send(request, **kwargs)
Feb 20 11:18:41 HOSTNAME journal:  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
Feb 20 11:18:41 HOSTNAME journal:    raise ReadTimeout(e, request=request)
Feb 20 11:18:41 HOSTNAME journal: ReadTimeout: HTTPConnectionPool(host='xx.yy.zz.xx', port=8080): Read timed out. (read timeout=5)

**Comment by ryanpetrello** [comment]
@akcrisp could you share (sanitized, if necessary) the contents of:

`HTTPS GET https://<towerhost>/api/v2/settings/logging/`

**Comment by akcrisp** [comment]
Good point - however I just logged back in and went to settings and logging showed everything back as it was before I hit revert to defaults (yes I did save it).

So I have reverted all again and saved it and api shows nothing. Will monitor

**Comment by akcrisp** [comment]
so far errors have gone... will close this for time being
