### ISSUE TITLE
include node type in awx_instance_info and/or awx_instance_*_capacity metrics

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#13019]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

Right now, we have information about nodes and their remaining capacity, but there is no data in the metrics endpoint that indicates what type of capacity the nodes have, e.g. is it a control node, hybrid, or execution, OR is the capacity control/execution capacity.

Right now I don't have a way of knowing that a node is a hybrid node from the metrics.

My feature request is either that we include node type in the instance_info and/or we include node type in `awx_instance_remaining_capacity`

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

see /api/v2/metrics

### Current results

no node type

### Current metric values
```
# TYPE awx_instance_info gauge
awx_instance_info{enabled="True",hostname="awx_2",instance_uuid="00000000-0000-0000-0000-000000000000",managed_by_policy="True",version="21.6.1.dev146+g1619462fb0"} 1.0
```

```
# HELP awx_instance_remaining_capacity Remaining capacity of each node in the system
# TYPE awx_instance_remaining_capacity gauge
awx_instance_remaining_capacity{hostname="awx_2",instance_uuid="00000000-0000-0000-0000-000000000000"} 619.0
```

### Sugested feature result

```
# TYPE awx_instance_info gauge
awx_instance_info{enabled="True",hostname="awx_2", node_type="hybrid", ,instance_uuid="00000000-0000-0000-0000-000000000000",managed_by_policy="True",version="21.6.1.dev146+g1619462fb0"} 1.0
```

```
# HELP awx_instance_remaining_capacity Remaining capacity of each node in the system
# TYPE awx_instance_remaining_capacity gauge
awx_instance_remaining_capacity{hostname="awx_2", node_type="hybrid", instance_uuid="00000000-0000-0000-0000-000000000000"} 619.0
```

The difference being that we now have `node_type="hybrid"` (same key/value as we show in /api/v2/instances)

This would apply to all the capacity metrics

**Comment by jbradberry** [comment]
There is also now a state field that may or may not be worthwhile to add to metrics as part of this work: https://github.com/ansible/awx/pull/12587

**Comment by AlanCoding** [comment]
It was brought to my attention that this changed the schema of the metrics data, but the version wasn't updated. This needs that version updated, and then can be moved to testing.

**Comment by AlanCoding** [comment]
https://github.com/ansible/awx/pull/13408 from @slemrmartin is up

**Comment by jbradberry** [comment]
@AlanCoding what should the state of this issue actually be in?

**Comment by AlanCoding** [comment]
from current metrics

```
# HELP awx_instance_consumed_capacity Consumed capacity of each node in the system
# TYPE awx_instance_consumed_capacity gauge
awx_instance_consumed_capacity{hostname="awx_1",instance_uuid="d77a18d7-84cb-4327-bddc-6daec2f7fbf1",node_type="hybrid"} 0.0
# HELP awx_instance_remaining_capacity Remaining capacity of each node in the system
# TYPE awx_instance_remaining_capacity gauge
```

Closing as done
