### ISSUE TITLE
Long running jobs go to failed state in AWX with the error "Job terminated due to timeout"

### ISSUE THREAD

**Issue by mani3887** [ansible/awx#13016]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Long running jobs go to failed state in AWX with the error "Job terminated due to timeout". Looking at the logs, we observe that all the tasks(but the last task) have run successfully, but AWX reports the status as failed in its' job details, with the error: "Job terminated due to timeout". I am running the playbook with 1 minute time interval loop for an hour. AWX EE CPU/Mem/Req: 100m/125Mi ; Limit: 2/2Gi.

### AWX version

21.4.0

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [X] Collection
- [X] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.12.1

### Operating system

Ubuntu(AWX task)

### Steps to reproduce

I ran this playbook:
```
---
  - name: "Hello world"
    hosts: "{{ ansible_play_hosts }}"
    connection: local
    vars_prompt:

      - name: mins
        prompt: How many minutes? 
        private: no

    gather_facts: false
    tasks:

    - name: check date at startup
      command: date
      register: out
    - debug: msg={{out.stdout}}

    - name: Wait for {{mins}} mins
      debug:
        msg: "Minute: {{item|int-1}}"
      with_sequence: count={{mins|int + 1}}
      loop_control:
        pause: 60

    - name: check date at end
      command: date
      register: out
    - debug: msg={{out.stdout}}

```
**Input: {mins: 60}**

We are running with AKS cluster 1.23.

### Expected results

Job completes successfully/ or print the status as error instead of the status printing as failed.

### Actual results

Tasks completed until the 60 second pause but it did not print the final task check date at end and errored out at this place.

**Comment by sarabrajsingh** [comment]
hi @mani3887,

you might be running into job timeouts. could you please take a look at your `settings` API endpoint at `<YOUR AWX URI>/api/v2/settings/all/` and see if there are job timeouts that conflict with the runtime of your playbook? your pause + loop conditions will give a runtime of +60min.

Thanks,
AWX Team

**Comment by mani3887** [comment]
Thanks, I stepped on to this configuration change few days back, changed it and it worked as intended.
