### ISSUE TITLE
Onboarding docs update

### ISSUE THREAD

**Issue by djyasin** [ansible/awx#13039]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

Updating internal documentation in GitLab.

### Select the relevant components

- [ ] UI
- [ ] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

n/a

### Current results

n/a

### Sugested feature result

n/a

**Comment by AlanCoding** [comment]
Is this done? should the issue be closed?

**Comment by djyasin** [comment]
@AlanCoding I finished adding the contributing guide which was what this ticket was created for. I do still have some new outstanding additions, but I thought I'd make specific tickets for those as we work on them.

Would it be preferrable to just leave this open until then? I wasn't sure about this one since it's more difficult to determine when this is truly considered done.

**Comment by djyasin** [comment]
"How to Contribute" and the onboarding section of these docs updated. Will create separate issues for future changes.
