### ISSUE TITLE
gcp source raise python exception

### ISSUE THREAD

**Issue by amaranto** [ansible/awx#1303]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Inventory Source for GCP raise python exception

##### ENVIRONMENT
* AWX version:  1.0.4.0
* AWX install method: kubernetes ( on gcp )
* Ansible version:   2.4.3.0
* Operating System: Docker container centOs | ansible/awx_web:latest 
* Web Browser: chrome/firefox

##### STEPS TO REPRODUCE
go to Inventory -> Sources -> +add sources -> Google compute engine.
##### EXPECTED RESULTS
Retrieve gcp instances.

##### ACTUAL RESULTS

`Plugin ini failed: /usr/lib/python2.7/site-packages/awx/plugins/inventory/gce.py:19: Error parsing host definition ''''': No closing quotation`

**Comment by ryanpetrello** [comment]
@amaranto could you paste the _entire_ traceback you see in the Job Output view?  There's likely a bunch of lines above this that could help provide some context.  Thanks!

**Comment by wenottingham** [comment]
Closing, please reopen if you can provide the requested information.
