### ISSUE TITLE
How to add isolated nodes on awx 21.7.0?

### ISSUE THREAD

**Issue by aaronray** [ansible/awx#13032]
##### ISSUE TYPE
 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME
 - CLI

##### SUMMARY
I have tried to add an execution node with awx-manage tool, but the node started failed after a while.

##### ENVIRONMENT
* AWX version: 21.7.o
* AWX install method: operator
* AWX deployment target: kubernetes
* Operating System: CentOS 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE
1.Enter awx-task and run awx-manage provision_instance --hostname host1 --node_type execution
2.awx-manage register_queue --queuename restricted --hostname host1
3.awx-manage generate_secret_key
4.Copy the key to the new node,/home/awx/.ssh/authorized_keys

##### ACTUAL RESULTS

The new node can be seen from UI but after a while it failed.Is there anything wrong of my steps?

**Comment by kurokobo** [comment]
There is a good guide to add execution node: https://github.com/ansible/awx/blob/devel/docs/execution_nodes.md

**Comment by sarabrajsingh** [comment]
Hello, this appears to be less of a bug report or feature request and more of a question. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.
