### ISSUE TITLE
awx.awx.tower_export - does't it export multiple assets for one type of asset

### ISSUE THREAD

**Issue by ArtsiomMusin** [ansible/awx#13055]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

This is a question about what tower_export is capable of doing. 

In the doc https://docs.ansible.com/ansible/3/collections/awx/awx/tower_export_module.html#parameters
all parameters are set in plural form. Is that possible to export two or more assets like that:
```
awx.awx.tower_export: 
        projects: project1,project2
        validate_certs: no
```
I see the asset output contains an empty array for projects. So I suppose the export can export multiple assets. Or not?
```
ok: [localhost] => {
    "msg": {
        "assets": {
            "projects": []
        },
        "changed": false,
        "failed": false
    }
}

```

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [x] CLI
- [ ] Other

### Installation method

openshift

### Modifications

no

### Steps to reproduce

Try to export multiple assets for projects in CSV format

### Expected results

tower_export can export multiple assets of one type

### Actual results

nothing is exported

**Comment by sean-m-sullivan** [comment]
@jbradberry I think this can be closed, its working and now in the collection proper?

**Comment by jbradberry** [comment]
pinging @john-westcott-iv , since I'm not currently on the Controller team.

**Comment by john-westcott-iv** [comment]
@ArtsiomMusin closing this from the merged PR. If this is still an issue please reach out and we can open it back up.
