### ISSUE TITLE
awx.awx.tower_export nothing exported on Ansible Automation Platform

### ISSUE THREAD

**Issue by ArtsiomMusin** [ansible/awx#13056]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

tower_export doesn't export any asserts on Ansible Automation Platform(AAP). However, the same export works fine on Ansible Tower.

The task below exports one organization:
```
      awx.awx.tower_export: 
        organizations: artem_test
        validate_certs: no
```
The exported assert is empty:
```
ok: [localhost] => {
    "assets": {
        "organizations": []
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "all": false,
            "controller_config_file": null,
            "controller_host": "https://myhostname",
            "controller_oauthtoken": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "controller_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "controller_username": null,
            "credential_types": null,
            "credentials": null,
            "execution_environments": null,
            "inventory": null,
            "inventory_sources": null,
            "job_templates": null,
            "notification_templates": null,
            "organizations": "artem_test",
            "projects": null,
            "teams": null,
            "users": null,
            "validate_certs": false,
            "workflow_job_templates": null
        }
    }
}

```

### AWX version

Ansible Automation Platform(AAP)

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

openshift

### Modifications

no

### Steps to reproduce

Simple export of assert on AAP

### Expected results

Asserts are exported in the same way as on Ansible Tower

### Actual results

Empty asserts

**Comment by ArtsiomMusin** [comment]
After some tests I found that this issue is related to ansible version installed on AAP. Will update the issue after I get more details on exact versions for ansible, where it works and where it fails

**Comment by akus062381** [comment]
Hi @ArtsiomMusin,

Thank you for posting. we are glad you figured it out!
