### ISSUE TITLE
stdout error during task gives error and to reload dashboard

### ISSUE THREAD

**Issue by bitsky6** [ansible/awx#13079]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

<img width="709" alt="image" src="https://user-images.githubusercontent.com/57507315/196649219-87dfef9c-15cd-429d-a316-8ecad0516650.png">

### AWX version

21.7.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.12.5

### Operating system

RHEL 8.6

### Web browser

Firefox, Chrome

### Steps to reproduce

If the task stops with error and select it, it will throw an error to refresh dashboard then it works

### Expected results

to how error details without refreshing the page before and dont show error

### Actual results

selecting the details on the task will throw error unless refreshed the page

**Comment by kialam** [comment]
@bitsky6 thanks for reporting this. The bug should be fixed by https://github.com/ansible/awx/pull/13148.
