### ISSUE TITLE
Modules not working

### ISSUE THREAD

**Issue by bitsky6** [ansible/awx#13087]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hey Guys,

I am not sure anymore if is a bug or not but I have tried everything to make it work and no luck.

- So I am trying to use for example the community.general.make and community.docker modules and whatever I try when the playbook runs gives me that can't find the module/action.
![image](https://user-images.githubusercontent.com/57507315/197187310-b54e9ed3-df32-4e8b-9a87-db72ed06edd7.png)

What I have already tried is:
- installed on the host with ansible-galaxy the modules
- installed on the host with pip docker-compose, docker and make
- installed inside the awx docker container manually with pip the docker,docker-compose make modules
- i have added to the requirements list awx/requirements/requirements.in/txt so on build to get installed
- I have mapped the collection modules from host collection in the docker awx path

Can anybody let me know if it is a bug or there es a sepcial way getting the collections into the image as from the documentation did not manage to figure it.

I really need some of the modules and can't make it work

Thanks

### AWX version

21.7.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.12.5

### Operating system

RHEL 8.6

### Web browser

Firefox, Chrome

### Steps to reproduce

build new image with make docker-compose-build
install with ansible-galaxy collection modules and try to use the playbook with a module

### Expected results

when i add the module installed inside the playbook to work dont give missing module

### Actual results

always giving me no module/action

**Comment by bitsky6** [comment]
All working good, figured it out, it is not a bug.
Thanks Anyway!

**Comment by RubyWanKenobi** [comment]
Would you please share what was the solution in your case ?

**Comment by bitsky6** [comment]
Found 2 ways to do it.
One is build your own environment executor with modules included and use that.

The other have a collections/requirements.yml with the modules to be installed on the root of your project, my case then gitsync will check on root and install them.

Then if you want also to be able to use the shortnames instead fcqn

Add collections paths in your playbook.

Ie. Collections: 
- Community.docker.docker_image

Some have already shortnames so even without will work bit i ls always recommended use fcqn.

**Comment by fahadshery** [comment]
> Found 2 ways to do it. One is build your own environment executor with modules included and use that.
> 
> The other have a collections/requirements.yml with the modules to be installed on the root of your project, my case then gitsync will check on root and install them.

can't believe this actually solved my problem...thanks
