### ISSUE TITLE
awxkit api: import_asserts cannot import schedules

### ISSUE THREAD

**Issue by ArtsiomMusin** [ansible/awx#13084]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

import_asserts from ApiV2 class cannot import schedules asserts as unified_job_template is not found:
```
/api/v2/schedules/ "myschedule": Bad Request (400) received - {'unified_job_template': ['This field may not be null.']}.

```

Seen this issue for latest versions awxkit 21.*. Maybe exists in prev releases as well

### AWX version

Ansible Tower/AAP

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [x] CLI
- [ ] Other

### Installation method

openshift

### Modifications

no

### Steps to reproduce

1. Install awxkit 21.7.0
1. Export a schedule
2. Import the schedule

### Expected results

A schedule is imported

### Actual results

Failed with 
/api/v2/schedules/ "myschedule": Bad Request (400) received - {'unified_job_template': ['This field may not be null.']}.

**Comment by jay-steurer** [comment]
Closing this since issue was fixed by merged PR.
