### ISSUE TITLE
Machine Credentials for SSH connections to Juniper Devices will not pass Password field.

### ISSUE THREAD

**Issue by GiuffreLab** [ansible/awx#13088]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Machine Credentials for SSH login appear to not be passing the password in the last few versions of AWX-Operator, last known working around version 0.20.0 / 20.1.0. The last three or four updates that have been tested all seem to have this issue. This does not appear to impact standard connections to Windows or Linux based endpoints with Machine credentials with non-privileged or privileged credentials.

Templates/Playbooks that previously worked have not worked anymore in newer versions of AWX.

This is when connecting to Juniper Appliances with a custom EE. The same playbooks work in older versions of AWX, and Ansible Core.

Here is an example of the JSON output of a failed connection. Jobs that do not require a password will work from AWX to the Juniper Device.

### AWX version

21.6.0

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

yes

### Ansible version

2.12.0-1

### Operating system

Ubuntu 22.04.1 LTS

### Web browser

Firefox, Chrome, Safari, Edge

### Steps to reproduce

Create Machine Credentials with just a username and password without privileged escalation. 

Run playbook to Juniper device that requires username/password login to access.

### Expected results

AWX would connect to the device and run the commands.

### Actual results

AWX throws a connection auth error

`{
  "msg": "Unable to make a PyEZ connection: ConnectAuthError(192.168.1.240)",
  "invocation": {
    "module_args": {
      "commands": [
        "show version"
      ],
      "host": "192.168.1.240",
      "user": "root",
      "port": 22,
      "return_output": true,
      "timeout": 30,
      "formats": null,
      "dest": null,
      "dest_dir": null,
      "ignore_warning": null,
      "passwd": null,
      "cs_user": null,
      "cs_passwd": null,
      "ssh_private_key_file": null,
      "ssh_config": null,
      "mode": null,
      "console": null,
      "baud": null,
      "attempts": null,
      "provider": null,
      "logfile": null,
      "logdir": null,
      "level": null
    }
  },
  "_ansible_no_log": null,
  "changed": false
}`

**Comment by rooftopcellist** [comment]
I think you may need to specify the ansible_connection for Juniper networking devices in your Inventory.  Try out these docs:
* https://docs.ansible.com/ansible/latest/network/user_guide/platform_junos.html#junos-os-platform-options
* https://www.juniper.net/documentation/us/en/software/junos-ansible/ansible/topics/topic-map/junos-ansible-connection-methods.html

You may need to specify this in the EE too.

**Comment by djyasin** [comment]
Hi!

Thank you very much for this issue. It means a lot to us that you have taken the time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without a response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed on the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for your time!

**Comment by GiuffreLab** [comment]
Sorry, I had not had a chance to circle back. 

The mentioned changes above had no effect on this issue.

I have not had a chance to update to the new version of AWX to see if something there inadvertently fixed it, but I'm guessing no, as this has been an issue for quite a few releases now.

Will update if I see a change.
