### ISSUE TITLE
Add explicit "localhost" to all jobs part of a sliced workflow job

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#13085]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

Motivation 1:

A host with name "localhost" behaves differently than any other host in Ansible. If it is not given in inventory, then, Ansible still adds it to the inventory - _implicit localhost_. If you include it in your inventory, then it's there and you can set variables on it, like (importantly) the Ansible python interpreter - _explicit localhost_.

On this basis alone, there is an argument that we're not handling sliced jobs in the most compatible way. If someone set the localhost interpreter, then only _1_ of the slices will operate with those variables.

Motivation 2:

The status of sliced jobs with limits don't work quite right. If you target a host pattern that doesn't match any hosts _in any given slice_ that will fail the overall workflow job.

Note that targeting "localhost" with `--limit` will fail if using _implicit_ locahost but not with _explicit_ locahost.

```
# fails
ansible-playbook -i alan, --limit=,alanlocalhost --connection=local hello_world.yml
# is successful
ansible-playbook -i alan,localhost --limit=localhost --connection=local hello_world.yml
```

If I wanted to denote "don't ever fail with limit-not-matched error", adding `,localhost` would be my gut reaction. However, this doesn't work because localhost isn't present in all slices.

Proposal:

When sliced jobs generate inventory, they should all include the explicit localhost, if present in the inventory.

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

Launch a sliced job with an unmatched limit.

### Current results

Fails, no apparent workaround.

### Sugested feature result

With this, a workaround would be possible by:

 - adding explicit localhost to the inventory
 - adding `,localhost` to the limit used for the job

**Comment by djyasin** [comment]
Closing per Alan.
