### ISSUE TITLE
Documentation for install in docker-compose don't work

### ISSUE THREAD

**Issue by yodatak** [ansible/awx#13096]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

If we use tagged release like the documentation say it don't work in master it works

https://wesley.sh/2022/08/

And podman-compose is not working because of this 
https://github.com/containers/podman/issues/15928#issuecomment-1259151121

### AWX version

master

### Select the relevant components

- [ ] UI
- [ ] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Steps to reproduce

just follow the documentation it dont' work 

### Expected results

works

### Actual results

it failled with 
Pulling awx_1 (ghcr.io/ansible/awx_devel:HEAD)...
ERROR: manifest unknown

**Comment by fosterseth** [comment]
try by setting `COMPOSE_TAG=devel make docker-compose`

does that work?

**Comment by rooftopcellist** [comment]
@yodatak if that didn't work for you, please open a new issue.  Thanks!

**Comment by swgATpj** [comment]
> try by setting `COMPOSE_TAG=devel make docker-compose`
> 
> does that work?

However it helped me, so...thanks! :D
