### ISSUE TITLE
Error on adding awx standalone execution node

### ISSUE THREAD

**Issue by Bergdolt** [ansible/awx#13105]
##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - AWX receptor

##### SUMMARY

In awx GUI after adding a new INstance, downlad 
##### ENVIRONMENT
* AWX version: 21.7.0
* AWX install method: operator
* AWX deployment target: kubernetes,
* Operating System: Linux
* Web Browser: Edge

##### STEPS TO REPRODUCE
Follow intruction in: https://github.com/ansible/awx/blob/devel/docs/execution_nodes.md

I.E.: Add news instance (type execution node) in AWX GUI, download install bundle, execute install bundle on new instance node

##### EXPECTED RESULTS

New instance should appear as "ready"

##### ACTUAL RESULTS

Instance status is "Not operationnal"

##### ADDITIONAL INFORMATION

Error message on this instance is:
"Remote error: ERROR: could not parse response: ERROR: could not verify signature: token is expired by 1m29.865700587s"

**Comment by kurokobo** [comment]
The token for work signing is valid for 1 minute by default.
Ensure the time is in sync on your AWX and Execution Node.

**Comment by Bergdolt** [comment]
Thanks, you get it right!!!
 I corrected ntp config on AWX and execution node and now its status is "Ready"
Regards,
