### ISSUE TITLE
LC_CTYPE: cannot change locale (C.UTF-8)

### ISSUE THREAD

**Issue by jakszk** [ansible/awx#13100]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

After upgrading AWX from 17.0.1 to 21.7.0 version, it is impossible to execute any yum module against RHEL 7.9 machines due to the following error:

{
  "module_stdout": "/etc/locale.conf: line 1: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8)\r\n/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8)\r\n/bin/sh: /usr/bin/python3: No such file or directory\r\n",
  "module_stderr": "Shared connection to .... closed.\r\n",
  "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error",
  "rc": 127,
  "_ansible_no_log": false,
  "changed": false
}

### AWX version

21.7.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

core 2.12.5.post0

### Operating system

AWX-EE based on CentOS Stream release 8, remote host: Red Hat Enterprise Linux Server release 7.8/7.9

### Steps to reproduce

Execution of the following error via AWX 21.7.0 against RHEL7.9 based host. (when I execute it via pure ansible, everything works fine - looks like something is trying to change locale to C.UTF-8 before running the actual yum module)
- hosts: all
  serial: 1
  gather_facts: false  
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  
  tasks:
    - name: Yum cache updates on {{ inventory_hostname }}
      become: yes
      yum:
        name: '*'
        state: latest
        download_only: yes
        use_backend: yum
        skip_broken: yes

### Expected results

Yum module executed fully without issues via usage of encoding available for RHEL7 systems.

### Actual results

{
  "module_stdout": "/etc/locale.conf: line 1: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8)\r\n/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8)\r\n/bin/sh: /usr/bin/python3: No such file or directory\r\n",
  "module_stderr": "Shared connection to .... closed.\r\n",
  "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error",
  "rc": 127,
  "_ansible_no_log": false,
  "changed": false
}

### Additional information

I am aware of the fact that C.UTF-8 is unavailable for Centos/RHEL 7 OS. Why does it try to use it against such systems even if it's not supported?

**Comment by fosterseth** [comment]
i think the bigger problem is this part of the error message `sh: /usr/bin/python3: No such file or directory` -- can you confirm that /usr/bin/python3 exists on both the rhel machine and the ee (I can't tell if this error msg relates to ansible, or the command that is being executed on the rhel machine)

**Comment by jakszk** [comment]
You are right. That was the main issue here. I made a soft link to match the python version on both ee and rhel vm. Many thanks for your help.
