### ISSUE TITLE
Failed to connect to the host via ssh: Bad owner or permissions on /etc/crypto-policies/back-ends/openssh.config

### ISSUE THREAD

**Issue by harleylrn** [ansible/awx#13108]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

While trying to run the templates on the client, getting the following error:
"Failed to connect to the host via ssh: Bad owner or permissions on /etc/crypto-policies/back-ends/openssh.config"
Checked on the pod, and the file has 777 permissions:
```
# kubectl -n awx exec --stdin --tty awx-7fb6896b48-7s64x -c awx-web -- /bin/bash
bash-5.1$ ls -la /etc/crypto-policies/back-ends/openssh.config
lrwxrwxrwx 1 root root 46 Sep 19 17:32 /etc/crypto-policies/back-ends/openssh.config -> /usr/share/crypto-policies/DEFAULT/openssh.txt
bash-5.1$ ls -la /usr/share/crypto-policies/DEFAULT/openssh.txt
-rwxrwxrwx 1 root root 1317 Aug 15 10:53 /usr/share/crypto-policies/DEFAULT/openssh.txt
bash-5.1$ 
exit
# kubectl -n awx exec --stdin --tty awx-7fb6896b48-7s64x -c awx-task -- /bin/bash
bash-5.1$ ls -la /etc/crypto-policies/back-ends/openssh.config
lrwxrwxrwx 1 root root 46 Sep 19 17:32 /etc/crypto-policies/back-ends/openssh.config -> /usr/share/crypto-policies/DEFAULT/openssh.txt
bash-5.1$ ls -la /usr/share/crypto-policies/DEFAULT/openssh.txt
-rwxrwxrwx 1 root root 1317 Aug 15 10:53 /usr/share/crypto-policies/DEFAULT/openssh.txt
```

In previous version (was 21.4) working fine

### AWX version

21.7

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

1. Add machine credentials
2. Run ad-hoc or any template on machine 
3. SSH connection will fail

### Expected results

SSH connection established

### Actual results

SSH connection failing with the error:
"Failed to connect to the host via ssh: Bad owner or permissions on /etc/crypto-policies/back-ends/openssh.config"

### Additional information

```
PLAY [Execute Patching Role] ***************************************************
TASK [Gathering Facts] *********************************************************
fatal: [test-idm01]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Bad owner or permissions on /etc/crypto-policies/back-ends/openssh.config", "unreachable": true}
PLAY RECAP *********************************************************************
test-idm01                 : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
```

**Comment by harleylrn** [comment]
Looks like I'm missed that the issue is on the EE and not on the AWX itself.

**Comment by nx2804** [comment]
what was the fix for this issue iam also facing the same error
