### ISSUE TITLE
workflow job results problem

### ISSUE THREAD

**Issue by lobosm** [ansible/awx#1310]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When i try to run workflow with more then 25 jobs nothing happend in browser but Workflow Job is runnig. Moreover I can't open worflow job  results in the browser - nothing happen after click. I suspect that websocket dosn't return any data to the browser.
After deleting jobs in workflow template editor to max 25 jobs, workflow results are fine - I can open it.

##### ENVIRONMENT
* AWX version: 1.0.1.223
* AWX install method: docker on linux
* Ansible version:  2.4.1.0
* Operating System: RHEL 7.2
* Web Browser: chrome 61.0.3163.100

##### STEPS TO REPRODUCE
1. create workflow templates and add there 26 or more related jobs
2. run workflow templates job (shoud be an error)
3. go to the JOBS and view the workflow job

##### EXPECTED RESULTS

page with workflow result should opened in 2 and 3

##### ACTUAL RESULTS

in 2 and 3 nothing happend. The page don't show.

**Comment by jaredevantabor** [comment]
I believe this is working now in devel. If you're still experiencing this issue after pulling in the latest changes in devel, please let us know @lobosm
