### ISSUE TITLE
Cascading/conditional menus for job template surveys 

### ISSUE THREAD

**Issue by AndyMcVey** [ansible/awx#13112]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

It would be very useful to have cascading or conditional menu entries for job template surveys.  This would allow a user to select from a subset of options based on a previous choice, e.g for a new VM provisioning workflow.
Question:
 - Select Location
 Options:
 - New York <- selected
 - San Jose
 - Tokyo

Question:
- Select subnet
Options:
- New York: subnet1
- New York: subnet2
- New York: subnet3
- San Jose: subnet1
- San Jose: subnet2
- San Jose: subnet3
- Tokyo: subnet1
- Tokyo: subnet2
- Tokyo: subnet3

Selecting "New York" should constrain the selection of subnets to those prefixed with "New York"

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

This is an enhancement request, not a bug report.

### Current results

Lists are limited to single or multi-select, not conditional

### Sugested feature result

Question:
 - Select Location
 Options:
 - New York <- selected
 - San Jose
 - Tokyo

Question:
- Select subnet
Options:
- New York: subnet1
- New York: subnet2
- New York: subnet3

**Comment by fosterseth** [comment]
Hi, great suggestion! thank you
this same idea was proposed here too https://github.com/ansible/awx/issues/20
we'll close this one in favor of that issue, so please go ahead and +1 that issue and drop a comment

**Comment by AndyMcVey** [comment]
Sounds good, sorry, #20 didn't show up when I was searching for this, but exactly covers what I was asking for.
