### ISSUE TITLE
Unable to create storage account just after successful creation of resource group on azurecloud

### ISSUE THREAD

**Issue by manikantavasupalli** [ansible/awx#13116]
##### ISSUE TYPE
 - Bug

##### COMPONENT NAME
 - Collection
 
##### SUMMARY
We are trying to create an azure resource_group followed by the creation of a storage account within that resource group using the block as shown below. Block1 is able to create the resource group and block2 is failing to create the storage account. This part is working for more than a year now and we started getting this issue in the past week only.

```---
- name: Create a resource group
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ project.resource_group_name }}"
    location: "{{ project.region }}"
    subscription_id: "{{ azure_env.ARM_SUBSCRIPTION_ID }}"
    tenant: "{{ azure_env.ARM_TENANT_ID }}"
    client_id: "{{ azure_env.ARM_CLIENT_ID }}"
    secret: "{{ azure_env.ARM_CLIENT_SECRET }}"
  tags:
    - init
    - never

- name: Create Storage account
  azure.azcollection.azure_rm_storageaccount:
    resource_group: "{{ project.resource_group_name }}"
    name: "{{ project.storage_account_name }}"
    type: Standard_RAGRS
    kind: BlobStorage
    access_tier: Cool
    subscription_id: "{{ azure_env.ARM_SUBSCRIPTION_ID }}"
    tenant: "{{ azure_env.ARM_TENANT_ID }}"
    client_id: "{{ azure_env.ARM_CLIENT_ID }}"
    secret: "{{ azure_env.ARM_CLIENT_SECRET }}"
  tags:
    - init
    - never
```

##### ENVIRONMENT
* Ansible install method: Ansible has been installed using pip module
* Ansible Versions:
`MarkupSafe-2.1.1 PyJWT-2.6.0 PySocks-1.7.1 PyYAML-6.0 adal-1.2.7 ansible-4.0.0 ansible-core-2.11.1 applicationinsights-0.11.10 argcomplete-1.12.3 azure-cli-core-2.35.0 azure-cli-telemetry-1.0.6 azure-common-1.1.11 azure-core-1.26.0 azure-graphrbac-0.61.1 azure-identity-1.7.0 azure-keyvault-1.0.0a1 azure-mgmt-apimanagement-0.2.0 azure-mgmt-authorization-0.51.1 azure-mgmt-automation-1.0.0 azure-mgmt-batch-5.0.1 azure-mgmt-cdn-3.0.0 azure-mgmt-compute-26.1.0 azure-mgmt-containerinstance-1.4.0 azure-mgmt-containerregistry-2.0.0 azure-mgmt-containerservice-9.1.0 azure-mgmt-core-1.3.2 azure-mgmt-cosmosdb-0.15.0 azure-mgmt-datafactory-2.0.0 azure-mgmt-datalake-nspkg-2.0.0 azure-mgmt-datalake-store-0.5.0 azure-mgmt-devtestlabs-3.0.0 azure-mgmt-dns-2.1.0 azure-mgmt-eventhub-2.0.0 azure-mgmt-hdinsight-0.1.0 azure-mgmt-iothub-0.7.0 azure-mgmt-keyvault-1.1.0 azure-mgmt-loganalytics-1.0.0 azure-mgmt-managedservices-1.0.0 azure-mgmt-managementgroups-0.2.0 azure-mgmt-marketplaceordering-0.1.0 azure-mgmt-monitor-3.0.0 azure-mgmt-network-19.1.0 azure-mgmt-notificationhubs-2.0.0 azure-mgmt-nspkg-2.0.0 azure-mgmt-privatedns-0.1.0 azure-mgmt-rdbms-1.9.0 azure-mgmt-recoveryservices-0.4.0 azure-mgmt-recoveryservicesbackup-0.6.0 azure-mgmt-redis-13.0.0 azure-mgmt-resource-10.2.0 azure-mgmt-search-3.0.0 azure-mgmt-servicebus-0.5.3 azure-mgmt-sql-3.0.1 azure-mgmt-storage-19.0.0 azure-mgmt-trafficmanager-0.50.0 azure-mgmt-web-0.41.0 azure-nspkg-2.0.0 azure-storage-0.35.1 bcrypt-4.0.1 certifi-2022.9.24 cffi-1.15.1 charset-normalizer-2.1.1 cryptography-38.0.1 humanfriendly-10.0 idna-3.4 importlib-metadata-4.13.0 isodate-0.6.1 jinja2-3.1.2 jmespath-1.0.1 knack-0.9.0 msal-1.20.0 msal-extensions-0.3.1 msrest-0.6.21 msrestazure-0.6.4 oauthlib-3.2.2 packaging-21.3 paramiko-2.11.0 pkginfo-1.8.3 portalocker-1.7.1 psutil-5.9.3 pycparser-2.21 pygments-2.13.0 pynacl-1.5.0 pyopenssl-22.1.0 pyparsing-3.0.9 python-dateutil-2.8.2 requests-2.28.1 requests-oauthlib-1.3.1 resolvelib-0.5.4 six-1.16.0 tabulate-0.9.0 typing-extensions-4.4.0 urllib3-1.26.12 xmltodict-0.13.0 zipp-3.10.0`

* Ansible deployment target: AzureCloud
* Operating System: Ubuntu: it's a Jenkin node(container)

##### STEPS TO REPRODUCE

Just execute the ansible playbook with tags

##### EXPECTED RESULTS

Resource group and storage account has to be created without fail...

```
TASK [azure_blob_backend : Create Storage account] *****************************
task path: /home/jenkins/workspace/Test-jobs/test_ad_access/azure_blob_backend/tasks/init.yml:14
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1666760433.7945178-2913-39937774618206 `" && echo ansible-tmp-1666760433.7945178-2913-39937774618206="` echo /root/.ansible/tmp/ansible-tmp-1666760433.7945178-2913-39937774618206 `" ) && sleep 0'
Using module file /home/jenkins/workspace/Test-jobs/test_ad_access/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageaccount.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-2678qy69kqjs/tmpv24glik6 TO /root/.ansible/tmp/ansible-tmp-1666760433.7945178-2913-39937774618206/AnsiballZ_azure_rm_storageaccount.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1666760433.7945178-2913-39937774618206/ /root/.ansible/tmp/ansible-tmp-1666760433.7945178-2913-39937774618206/AnsiballZ_azure_rm_storageaccount.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/jenkins/workspace/Test-jobs/test_ad_access/env/bin/python /root/.ansible/tmp/ansible-tmp-1666760433.7945178-2913-39937774618206/AnsiballZ_azure_rm_storageaccount.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1666760433.7945178-2913-39937774618206/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_azure.azcollection.azure_rm_storageaccount_payload_elb_6pwt/ansible_azure.azcollection.azure_rm_storageaccount_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageaccount.py", line 544, in check_name_availability
  File "/home/jenkins/workspace/Test-jobs/test_ad_access/env/lib/python3.7/site-packages/azure/mgmt/storage/v2021_06_01/operations/_storage_accounts_operations.py", line 100, in check_name_availability
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/jenkins/workspace/Test-jobs/test_ad_access/env/lib/python3.7/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "access_tier": "Cool",
            "account_type": "Standard_RAGRS",
            "ad_user": null,
            "adfs_authority_url": null,
            "allow_blob_public_access": null,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": "auto",
            "blob_cors": null,
            "cert_validation_mode": null,
            "client_id": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "cloud_environment": "AzureCloud",
            "custom_domain": null,
            "force_delete_nonempty": false,
            "https_only": null,
            "kind": "BlobStorage",
            "location": null,
            "log_mode": null,
            "log_path": null,
            "minimum_tls_version": null,
            "name": "testaclmanidev",
            "network_acls": null,
            "password": null,
            "profile": null,
            "resource_group": "testaclmani-dev-state",
            "secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "state": "present",
            "subscription_id": "XXXXX-XXXXX-XXXXXX-XXXXX",
            "tags": null,
            "tenant": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "type": "Standard_RAGRS"
        }
    },
    "msg": "Error checking name availability: (SubscriptionNotFound) Subscription XXXXX-XXXXX-XXXXXX-XXXXX was not found.\nCode: SubscriptionNotFound\nMessage: Subscription XXXXX-XXXXX-XXXXXX-XXXXX was not found."
```

##### ADDITIONAL INFORMATION
It used to been working in condition for the past 1 and half years and the issue was found in the last 10 days only and there is no recent change in the ansible code block.

**Comment by fosterseth** [comment]
Hi @manikantavasupalli this sounds like an ansible module issue, not AWX. Can you please contact the azure collection maintainers with this same error message and see if they can guide you?

can you verify that the same playbook works with just ansible (not using awx)?

**Comment by manikantavasupalli** [comment]
Sure, will reach out to azure collection maintainers. Thanks @fosterseth 
It's not related to AWX specifically, it's an ansible module-level issue or from the azure end.

**Comment by manikantavasupalli** [comment]
A workaround that we found is as below:

1. Create a dummy storage account on any new resource group in the same subscription manually (through the portal)
2. Now run the same ansible stuff

This time ansible code block was able to create a resource group and then a storage account inside the resource group.
