### ISSUE TITLE
Getting Failed to establish a new connection: [Errno 111] error while installing AWX cli on RHEL 7

### ISSUE THREAD

**Issue by SajanGone** [ansible/awx#13136]
##### ISSUE TYPE

 - Breaking Change

##### COMPONENT NAME

 - CLI

##### SUMMARY

I am working on installing AWX CLI on "Red Hat Enterprise Linux Server release 7.9 (Maipo)". I am blindly following the documentation on the page "https://github.com/ansible/awx/blob/devel/INSTALL.md" as I am relatively very new to using Ansible and AWX.  Getting the following error when attempting to run the "make clean html" command as shown below. 

[root@vsazdbaansct001 docs]# TOWER_HOST=https://vsazdbaansct001.xxx TOWER_USERNAME=example TOWER_PASSWORD=secret make clean html
Running Sphinx v5.2.3

Exception occurred:
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='vsazdbaansct001.xxx', port=443): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7e04edfa60>: Failed to establish a new connection: [Errno 111] Connection refused'))
The full traceback has been saved in /tmp/sphinx-err-uv45uw61.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2

       Any ideas on where to look at to find the issue and get past this error would be greatly appreciated. I apologize if I have not categorized this issue into the right bucket. The documentation I have been following for CLI installation is very vague, at least to  my brain and I would greatly appreciate if someone could point me to a page which is more descriptive :)

      Many thanks in advance. 

##### ENVIRONMENT
* AWX version: 
[root@vsazdbaansct001 etc]# awx --version
21.7.0

* AWX install method: AWX CLI
* AWX deployment target: openshift, kubernetes, minikube
* Operating System:  Red Hat Enterprise Linux Server release 7.9 (Maipo)
* Web Browser:

##### ADDITIONAL INFORMATION

Here is the output of the previous step:
==============================

[root@vsazdbaansct001 ~]# python -m pip install sphinx sphinxcontrib-autoprogram
WARNING: Running pip install with root privileges is generally not a good idea. Try `python -m pip install --user` instead.
Collecting sphinx
  Downloading https://files.pythonhosted.org/packages/27/55/9799046be6e9a02ff1955d74dffa2b096a2fe204d1004a8499d6953d62d2/sphinx-5.2.3-py3-none-any.whl (3.2MB)
     |████████████████████████████████| 3.2MB 2.0MB/s
Collecting sphinxcontrib-autoprogram
  Downloading https://files.pythonhosted.org/packages/1e/8b/d19bde42575942a4f97111c4eb28183776b619fd2f1e8df76a4d52f3caa7/sphinxcontrib_autoprogram-0.1.7-py2.py3-none-any.whl
Collecting alabaster<0.8,>=0.7
  Downloading https://files.pythonhosted.org/packages/10/ad/00b090d23a222943eb0eda509720a404f531a439e803f6538f35136cae9e/alabaster-0.7.12-py2.py3-none-any.whl
Collecting imagesize>=1.3
  Downloading https://files.pythonhosted.org/packages/ff/62/85c4c919272577931d407be5ba5d71c20f0b616d31a0befe0ae45bb79abd/imagesize-1.4.1-py2.py3-none-any.whl
Requirement already satisfied: requests>=2.5.0 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from sphinx) (2.28.1)
Collecting snowballstemmer>=2.0
  Downloading https://files.pythonhosted.org/packages/ed/dc/c02e01294f7265e63a7315fe086dd1df7dacb9f840a804da846b96d01b96/snowballstemmer-2.2.0-py2.py3-none-any.whl (93kB)
     |████████████████████████████████| 102kB 6.7MB/s
Collecting sphinxcontrib-devhelp
  Downloading https://files.pythonhosted.org/packages/c5/09/5de5ed43a521387f18bdf5f5af31d099605c992fd25372b2b9b825ce48ee/sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl (84kB)
     |████████████████████████████████| 92kB 124kB/s
Collecting importlib-metadata>=4.8; python_version < "3.10"
  Downloading https://files.pythonhosted.org/packages/b5/64/ef29a63cf08f047bb7fb22ab0f1f774b87eed0bb46d067a5a524798a4af8/importlib_metadata-5.0.0-py3-none-any.whl
Collecting sphinxcontrib-applehelp
  Downloading https://files.pythonhosted.org/packages/dc/47/86022665a9433d89a66f5911b558ddff69861766807ba685de2e324bd6ed/sphinxcontrib_applehelp-1.0.2-py2.py3-none-any.whl (121kB)
     |████████████████████████████████| 122kB 58.1MB/s
Requirement already satisfied: Jinja2>=3.0 in ./.local/lib/python3.8/site-packages (from sphinx) (3.1.2)
Collecting babel>=2.9
  Downloading https://files.pythonhosted.org/packages/2e/57/a4177e24f8ed700c037e1eca7620097fdfbb1c9b358601e40169adf6d364/Babel-2.10.3-py3-none-any.whl (9.5MB)
     |████████████████████████████████| 9.5MB 43.8MB/s
Requirement already satisfied: packaging>=21.0 in ./.local/lib/python3.8/site-packages (from sphinx) (21.3)
Collecting docutils<0.20,>=0.14
  Downloading https://files.pythonhosted.org/packages/93/69/e391bd51bc08ed9141ecd899a0ddb61ab6465309f1eb470905c0c8868081/docutils-0.19-py3-none-any.whl (570kB)
     |████████████████████████████████| 573kB 59.8MB/s
Collecting sphinxcontrib-serializinghtml>=1.1.5
  Downloading https://files.pythonhosted.org/packages/c6/77/5464ec50dd0f1c1037e3c93249b040c8fc8078fdda97530eeb02424b6eea/sphinxcontrib_serializinghtml-1.1.5-py2.py3-none-any.whl (94kB)
     |████████████████████████████████| 102kB 4.0MB/s
Collecting sphinxcontrib-qthelp
  Downloading https://files.pythonhosted.org/packages/2b/14/05f9206cf4e9cfca1afb5fd224c7cd434dcc3a433d6d9e4e0264d29c6cdb/sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl (90kB)
     |████████████████████████████████| 92kB 2.2MB/s
Collecting sphinxcontrib-jsmath
  Downloading https://files.pythonhosted.org/packages/c2/42/4c8646762ee83602e3fb3fbe774c2fac12f317deb0b5dbeeedd2d3ba4b77/sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl
Collecting sphinxcontrib-htmlhelp>=2.0.0
  Downloading https://files.pythonhosted.org/packages/63/40/c854ef09500e25f6432dcbad0f37df87fd7046d376272292d8654cc71c95/sphinxcontrib_htmlhelp-2.0.0-py2.py3-none-any.whl (100kB)
     |████████████████████████████████| 102kB 6.8MB/s
Collecting Pygments>=2.12
  Downloading https://files.pythonhosted.org/packages/4f/82/672cd382e5b39ab1cd422a672382f08a1fb3d08d9e0c0f3707f33a52063b/Pygments-2.13.0-py3-none-any.whl (1.1MB)
     |████████████████████████████████| 1.1MB 31.1MB/s
Collecting six
  Downloading https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
Requirement already satisfied: certifi>=2017.4.17 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from requests>=2.5.0->sphinx) (2022.9.24)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from requests>=2.5.0->sphinx) (1.26.12)
Requirement already satisfied: idna<4,>=2.5 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from requests>=2.5.0->sphinx) (3.4)
Requirement already satisfied: charset-normalizer<3,>=2 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from requests>=2.5.0->sphinx) (2.1.1)
Collecting zipp>=0.5
  Downloading https://files.pythonhosted.org/packages/f0/36/639d6742bcc3ffdce8b85c31d79fcfae7bb04b95f0e5c4c6f8b206a038cc/zipp-3.8.1-py3-none-any.whl
Requirement already satisfied: MarkupSafe>=2.0 in ./.local/lib/python3.8/site-packages (from Jinja2>=3.0->sphinx) (2.1.1)
Collecting pytz>=2015.7
  Downloading https://files.pythonhosted.org/packages/d8/66/309545413162bc8271c73e622499a41cdc37217b499febe26155ff9f93ed/pytz-2022.4-py2.py3-none-any.whl (500kB)
     |████████████████████████████████| 501kB 50.5MB/s
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./.local/lib/python3.8/site-packages (from packaging>=21.0->sphinx) (3.0.9)
Installing collected packages: alabaster, imagesize, snowballstemmer, sphinxcontrib-devhelp, zipp, importlib-metadata, sphinxcontrib-applehelp, pytz, babel, docutils, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, Pygments, sphinx, six, sphinxcontrib-autoprogram
  WARNING: The script pybabel is installed in '/opt/rh/rh-python38/root/usr/local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script docutils is installed in '/opt/rh/rh-python38/root/usr/local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pygmentize is installed in '/opt/rh/rh-python38/root/usr/local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts sphinx-apidoc, sphinx-autogen, sphinx-build and sphinx-quickstart are installed in '/opt/rh/rh-python38/root/usr/local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Pygments-2.13.0 alabaster-0.7.12 babel-2.10.3 docutils-0.19 imagesize-1.4.1 importlib-metadata-5.0.0 pytz-2022.4 six-1.16.0 snowballstemmer-2.2.0 sphinx-5.2.3 sphinxcontrib-applehelp-1.0.2 sphinxcontrib-autoprogram-0.1.7 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-2.0.0 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.3 sphinxcontrib-serializinghtml-1.1.5 zipp-3.8.1

Thanks,
Sajan Gone

**Comment by AlexSCorey** [comment]
@SajanGone `make clean html` is not necessary to install and use AWX CLI.  If that step is causing problems you can safely skip it.
