### ISSUE TITLE
Error using AWXkit with Python 3.11 using conf in CLI.

### ISSUE THREAD

**Issue by Smixi** [ansible/awx#13130]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

CLI args using --conf.* doesn't seems to work in Python 3.11 with multiple value

### AWX version

21.7.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Steps to reproduce

Hi,
I'm using AWXkit (v21.7.0)in pipelines. I updated python images to 3.11, and in my script, the following command is invoked :

``awx job_template launch ${template} ${AWX_CLI_ARGS}``

with `AWX_CLI_ARGS ` being `--conf.host ${AWX_HOST} --conf.insecure --conf.token ${AWX_TOKEN} --monitor`.

In Python 3.11, I got the following error : `argument resource: conflicting subparser: config`

I downgraded to Python 3.10 and it does works fine.

Is it not supported in 3.11 ? I couldn't find any breaking change in argparse ?

### Expected results

The same behavior as Python 3.10.

### Actual results

Error:  `argument resource: conflicting subparser: config`

**Comment by Smixi** [comment]
Related: #12938. I guess this is argparse. I will try to investigate if i have the time.

**Comment by jbradberry** [comment]
PR: https://github.com/ansible/awx/pull/13174

**Comment by jbradberry** [comment]
PR has merged.

**Comment by AlanCoding** [comment]
Minor note: I've marked this with the current release so that someone will get to it in the "Needs Test" queue.

**Comment by jbradberry** [comment]
@jay-steurer sorry, this is apparently one where the PR merged before getting QE sign-off.

**Comment by Smixi** [comment]
Should I close it then ?
