### ISSUE TITLE
events are not deleted from _unpartitioned_* tables

### ISSUE THREAD

**Issue by anxstj** [ansible/awx#13152]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

The "_unpartitioned_*" tables (e.g. "_unpartitioned_main_jobevent") which were created during the AWX 19 update (I think) are still containing a lot of data. The issue https://github.com/ansible/awx/issues/10341 and the code in https://github.com/ansible/awx/blob/devel/awx/main/management/commands/cleanup_jobs.py#L202 indicate that this shouldn't be the case and that the events should have been removed by now.

### AWX version

21.5.0

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.12.2

### Operating system

Debian 11

### Web browser

Firefox

### Steps to reproduce

Haven't tried this, but upgrading an older System (e.g. AWX 18) to a  recent version should move the existing events to the "_unpartitioned_" tables. And then starting a cleanup job shouldn't remove the data from there.

### Expected results

The "_unpartioned_*" tables are empty.

### Actual results

There is a lot of old data in those tables:
```
awx=# select count(*) from _unpartitioned_main_jobevent where created > timestamp '2022-06-01 00:00:00' limit 10;
 count 
-------
     0
awx=# select count(id) from _unpartitioned_main_jobevent where created > timestamp '2022-04-01 00:00:00' limit 10;
  count   
----------
 51360577
awx=# select count(id) from _unpartitioned_main_jobevent where created < timestamp '2022-02-15 00:00:00' limit 10;
  count   
----------
 15384905
```

The scheduler is configured to cleanup all data that is older than 120 days: 

`curl https://awx.example.com/api/v2/schedules/1/`
```
...
    "created": "2018-10-17T12:13:09.566943Z",
    "modified": "2022-09-15T16:22:41.282216Z",
    "name": "Cleanup Job Schedule",
    "description": "Automatically Generated Schedule",
    "extra_data": {
        "days": 120
    },
...
```

### Additional information

An update to AWX 19.2 was done on 15.02.2022. And the "_unpartitioned_main_jobevent" table was created on that date.

I'm not sure why it contains data that is younger (e.g. 2022-04-01) though.

**Comment by jbradberry** [comment]
@anxstj looking at the code involved, the first thing that comes to mind is that you might have a number of jobs in stuck in some of the non-completed states.  Can you run this command and show the results?

```sql
select j.status, count(1)
  from _unpartitioned_main_jobevent e
  inner join main_unifiedjob j
    on e.job_id = j.id
  group by j.status
  order by count(1) desc;
```

I can't entirely promise it is correct and not pathological in run time, since I don't have an instance with this table populated.

The second thing I wonder is if you get any output from the `cleanup_jobs` command that would shed any light on the situation.

**Comment by anxstj** [comment]
Hello @jbradberry.

Thanks for looking into this.

```
awx=# select j.status, count(1)
  from _unpartitioned_main_jobevent e
  inner join main_unifiedjob j
    on e.job_id = j.id
  group by j.status
  order by count(1) desc;
   status   |  count   
------------+----------
 failed     | 50227561
 successful | 29427869
 canceled   |   860992
 error      |     7193
(4 rows)
```

There's nothing obvious in the cleanup_jobs:
```
jobs: 0 deleted, 102810 skipped.
ad hoc commands: 0 deleted, 2 skipped.
project updates: 0 deleted, 182728 skipped.
inventory updates: 0 deleted, 91858 skipped.
management jobs: 0 deleted, 40 skipped.
workflow jobs: 0 deleted, 10400 skipped.
notifications: 0 deleted, 16284 skipped.
```

We were affected by the issue fixed with https://github.com/ansible/awx/pull/12447. To workaround that issue we had to decrease the cleanup interval to 14 days. And changed it back to 120 days when the fix was applied. We haven't reached 120 days yet so the database is still growing.

But I've got a backup from June and there I have some older system jobs. But it's the same there: nothing obvious.
https://pastebin.com/VcXa3Kw5

**Comment by jbradberry** [comment]
@anxstj Ok a few more, try these out please.

Exact timestamp of the migration that did the event table partitioning:
```sql
select id, name, applied from django_migrations where app = 'main' and name like '0144%';
```

Counts of the unpartitioned job events grouped by month:
```sql
select d, count(1)
  from (select to_char(created, 'YYYY-MM') as d from _unpartitioned_main_jobevent) as e
  group by d
  order by d desc;
```

Count of unpartitioned job events that are now missing a job:
```sql
select count(1)
  from _unpartitioned_main_jobevent e
  left outer join main_unifiedjob j
    on e.job_id = j.id
  where j.id is null;
```

**Comment by anxstj** [comment]
@jbradberry 

here we go:

```
awx=# select id, name, applied from django_migrations where app = 'main' and name like '0144%';
 id  |         name          |            applied            
-----+-----------------------+-------------------------------
 234 | 0144_event_partitions | 2022-05-23 15:43:30.481486+00
```

```
awx=# select d, count(1)
  from (select to_char(created, 'YYYY-MM') as d from _unpartitioned_main_jobevent) as e
  group by d
  order by d desc;
    d    |  count   
---------+----------
 2022-05 | 25397490
 2022-04 | 25963087
 2022-03 | 19580967
 2022-02 | 17076345
 2022-01 |  5580417
 2020-05 |       49
 2020-01 |   723359
(7 rows)
```

```
awx=# select count(1)
  from _unpartitioned_main_jobevent e
  left outer join main_unifiedjob j
    on e.job_id = j.id
  where j.id is null;
  count   
----------
 94321714
(1 row)
```

**Comment by jbradberry** [comment]
@anxstj yep, every single one of those job events is orphaned, the jobs corresponding to them do not exist any more.  I'd recommend just deleting everything from the `_unpartitioned*` tables manually.

It's less clear why the cleanup_jobs task failed so badly, but we'll look into it.

**Comment by jbradberry** [comment]
TODO:

- [ ] adjust cleanup_jobs to remove events (particularly from the unpartitioned tables) without necessarily having to tie them to an existing job

**Comment by AlanCoding** [comment]
To clarify the solution method in https://github.com/ansible/awx/pull/14055

> For that, I just check if created timestamps are all before the cutoff time given to awx-manage cleanup_jobs.

This will not solve the problem of cleaning up "orphan" events that are still within range of the cleanup_jobs retention time. However, once the retention time goes past the last unpartitioned event, then we drop the entire unpartitioned event table. This will, eventually, solve the problem for everyone and is forward-looking at less risky. I want to close this issue with the merge of that.

**Comment by AlanCoding** [comment]
Closing as resolved.
