### ISSUE TITLE
AWX_TASK_ENV is read-only in the base image

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#1315]
https://github.com/ansible/awx/blame/6163cc6b5c3a3c8f5bd173d121cafd15c5b75b17/installer/image_build/files/settings.py#L26 is set statically in the base image, and that makes the setting read-only from the Settings API.  We should come up with a way to set this value at install time that doesn't require setting the value in `settings.py` (via either an API call or via `awx-manage shell`).

**Comment by ryanpetrello** [comment]
related: https://github.com/ansible/awx/issues/490#issuecomment-367256149

**Comment by wenottingham** [comment]
Shouldn't that come from the user's homedir anyway?

**Comment by ryanpetrello** [comment]
@wenottingham that was my thought, but @shanemcd tinkered and without https://github.com/ansible/awx/blame/6163cc6b5c3a3c8f5bd173d121cafd15c5b75b17/installer/image_build/files/settings.py#L26, `$HOME` doesn't seem to be set.  So there must be a reason why we set this manually...

**Comment by ryanpetrello** [comment]
Looking into this more, awx and prod Tower installs don't set `HOME` explicitly via `AWX_TASK_ENV`, so I'm still stumped as to why this is necessary.  Going to spin up minishift install _without_ this line and see if I can troubleshoot.
