### ISSUE TITLE
Support for receptor node to initiate the tunnel connection

### ISSUE THREAD

**Issue by thg-jonnield** [ansible/awx#13165]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

Currently when scaling the receptor mesh the TCP tunnel is initiated from AWX to the newly created node.  There are situations where it would be nice for the node to initiate the connection of the tunnel back to AWX.  Examples would be if the receptor node is deployed behind a NAT firewall, or firewalls that restricts inbound connections.

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

N/A

### Current results

N/A

### Sugested feature result

The ability to scale the receptor mesh behind firewalls only allow for outbound connections

**Comment by fosterseth** [comment]
Hi,

Thank you for pointing this out, we are aware of this limitation and have plans to make the TCP directionality configurable.

This is a feature that we are tracking internally through a larger RFE. We'll close this issue, but stay tuned for an announcement whenever this feature lands into AWX.

Seth

**Comment by septatrix** [comment]
As long as this is not implemented I would like to vote for keeping this open so others can more easily find it and do not get confused by the status
