### ISSUE TITLE
Setting a custom logo doesn't replace AWX logo in top-left of UI

### ISSUE THREAD

**Issue by agaffney** [ansible/awx#1316]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When setting a custom logo, it only appears on the login screen. I would expect it also to replace the AWX logo that shows in the top-left of every screen (except the login screen) in the UI.

##### ENVIRONMENT
* AWX version: 1.0.4.3
* AWX install method: docker on linux
* Ansible version:  2.4.3
* Operating System: Ubuntu 16.04
* Web Browser: Chrome 64

##### STEPS TO REPRODUCE

1. Upload a custom logo
2. Become disappointed when it doesn't replace the AWX logo in the UI

##### EXPECTED RESULTS

Custom logo everywhere!

##### ACTUAL RESULTS

Custom logo only shows on the login screen.

##### ADDITIONAL INFORMATION

N/A

**Comment by wenottingham** [comment]
See #1008 , this is intentional.

**Comment by gravelander** [comment]
Congrats @wenottingham, you didn't answer the question in either thread. Why is it intentional? Can it be circumvented?

**Comment by wenottingham** [comment]
Custom logo is designed for people who need to brand their login screen (along with the custom login message).

In the downstream software (Tower), changing the top left logo is not allowed and will not be allowed, due to internal requirements, which is why custom logo isn't extended to that.

In the upstream AWX... if you're building your own thing you want to entirely rebrand... you've got the source.

**Comment by ratman** [comment]
> Custom logo is designed for people who need to brand their login screen (along with the custom login message).
> 
> In the downstream software (Tower), changing the top left logo is not allowed and will not be allowed, due to internal requirements, which is why custom logo isn't extended to that.
> 
> In the upstream AWX... if you're building your own thing you want to entirely rebrand... you've got the source.

Is that an insider joke or what? Most people would not care if there wasn't any logo or something neutral or just an AWX logo, not this terrible potato. Do I really have to fork the repo just to get rid of it? That does not sound sane.
