### ISSUE TITLE
Deprecate tower_* and other modules inside of AWX collection

### ISSUE THREAD

**Issue by thedoubl3j** [ansible/awx#13186]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

A few of the modules inside of the collection need to be deprecated. Primarily the tower_* modules as well as a few others.

### AWX version

21.5.1.dev397+g86b0a3d4f1

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Steps to reproduce

n/a

### Expected results

Modules marked for deprecation and removal in future version

### Actual results

Modules are not marked for deprecation.

**Comment by thedoubl3j** [comment]
This will require the symlinks to be removed so this will not only be a deprecation but also the removal. however, the redirects in the plugin_routing still work so users will not experience any change aside from the warning message saying to move to the new module name.

**Comment by sean-m-sullivan** [comment]
@thedoubl3j completed?

**Comment by thedoubl3j** [comment]
yup @sean-m-sullivan
