### ISSUE TITLE
awx-manage inventory_import does not handle overwrite option

### ISSUE THREAD

**Issue by avalou** [ansible/awx#13206]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### AWX version

Ansible AWX 21.5.1.dev0+gff49cc5636.d20220825

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

ansible [core 2.12.5]

### Operating system

Ubuntu server 22.04

### Steps to reproduce

1. Having a host file
2. `docker exec tools_awx_1 awx-manage inventory_import --source=/tmp/hosts --inventory-name="windows-hosts" --overwrite`

### Expected results

"windows-hosts" should only contain hosts listed in the host file, and note merge those from the file and those previously contained in the inventory.

### Actual results

"windows-hosts" is a merge of both the host file and the previously contained hosts.

### Additional information

Here are the logs I got from the command :
```
$ docker exec tools_awx_1 awx-manage inventory_import --source=/tmp/hosts --inventory-name="windows-hosts" --overwrite --force-color
    0.903 INFO     Updating inventory 25: windows-hosts
2022-11-17 08:03:36,342 INFO     [-] awx.analytics.job_lifecycle inventoryupdate-1823 created
    0.933 INFO     Reading Ansible inventory source: /tmp/hosts
    1.772 ERROR    ansible-inventory [core 2.12.5.post0]
    1.772 ERROR      config file = None
    1.772 ERROR      configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
    1.772 ERROR      ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
    1.772 ERROR      ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
    1.772 ERROR      executable location = /usr/local/bin/ansible-inventory
    1.772 ERROR      python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
    1.772 ERROR      jinja version = 2.11.3
    1.772 ERROR      libyaml = True
    1.772 ERROR    No config file found; using defaults
    1.772 ERROR    host_list declined parsing /tmp/hosts as it did not pass its verify_file() method
    1.772 ERROR    script declined parsing /tmp/hosts as it did not pass its verify_file() method
    1.772 ERROR    auto declined parsing /tmp/hosts as it did not pass its verify_file() method
    1.773 ERROR    Parsed /tmp/hosts inventory source with ini plugin
    1.776 INFO     Processing JSON output...
    1.777 INFO     Loaded 6 groups, 165 hosts
    1.777 WARNING  loading into database...
    1.874 WARNING  host deletions took 1 queries for 0 hosts
    1.877 WARNING  group deletions took 2 queries for 0 groups
    1.894 WARNING  group-group and group-host deletions took 19 queries for 0 relationships
    1.936 WARNING  group updates took 2 queries for 6 groups
    1.949 WARNING  host updates took 2 queries for 165 hosts
    1.949 WARNING  Group-group updates took 0 queries for 0 group-group relationships
    1.972 WARNING  Group-host updates took 11 queries for 188 group-host relationships
    1.980 WARNING  update computed fields took 8 queries
    1.980 WARNING  Inventory import completed for  (windows-hosts - 91) in 0.2s
    1.981 WARNING  Inventory import required 215 queries taking 0.021s
```

**Comment by fosterseth** [comment]
@avalou can you copy and paste your `/tmp/hosts` file? (redact any sensitive IPs)

**Comment by akus062381** [comment]
Hi @avalou,

Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!

**Comment by avalou** [comment]
> @avalou can you copy and paste your `/tmp/hosts` file? (redact any sensitive IPs)

Hi ! Sorry for the long delay.

Here is how looks my `/tmp/hosts` file :

```
[w2012]


[w2016]
hostname1.domain.fr
hostname2.domain.fr
hostname3.domain.fr
```
It is actually populated by more or less 300 hosts, with some empty group instances.
