### ISSUE TITLE
Custom awx operator images in helm chart

### ISSUE THREAD

**Issue by Audrius13** [ansible/awx#13205]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

Hello,

In closed environments there is no direct access to internet and images need to be pulled from local repos like artifactory or pulp.

Now helm chart awx operator deployment file deployment-awx-operator-controller-manager.yaml has hard-coded values for images:

image: [gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0](http://gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0)
name: kube-rbac-proxy

name: awx-manager
image: [quay.io/ansible/awx-operator:1.0.0](http://quay.io/ansible/awx-operator:1.0.0)

Would be great if these two images could be customized via values.yml

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Steps to reproduce

N/A

### Current results

N/A

### Sugested feature result

N/A

**Comment by Audrius13** [comment]
wrong project

**Comment by relrod** [comment]
I see you've re-filed this in awx-operator. Closing this out :)
