### ISSUE TITLE
awx workflow_job_templates modify unable to save extra vars as YAML

### ISSUE THREAD

**Issue by isuftin** [ansible/awx#13212]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I'm not sure if I'm using the command improperly, but while I am able to update a template's extra vars by passing in YAML, they are always saved in AWX/AAP as JSON. 

Specifically this is running against the Ansible Automation Platform but I am checking to see if this is also an issue in AWX and if this is an issue with the awx CLI.

### AWX version

21.8.0

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Ansible version

2.13.6

### Operating system

MacOS

### Web browser

Chrome

### Steps to reproduce

```sh
awx workflow_job_templates get  63 -f yaml | yq  e '.extra_vars' > vars.yaml

cat vars.yaml
---
hello: there

yq e '.secondary_key = "secondary_value"' -i vars.yaml

cat vars.yaml
---
hello: there
secondary_key: secondary_value

awx workflow_job_templates modify 63 --extra_vars @vars.yaml

awx workflow_job_templates get  63 -f yaml | yq  e '.extra_vars'
{"hello": "there", "secondary_key": "secondary_value"}

awx workflow_job_templates get  63 -f yaml | grep extra_vars
extra_vars: '{"hello": "there", "secondary_key": "secondary_value"}'

```

### Expected results

I would expect extra_vars would be stored in YAML format.

### Actual results

If I go into AAP and refresh, the variables come up as JSON in the JSON view and YAML in the YAML view but they seem to come out as only JSON in the awx output. Also interesting that if I go to edit the variables in AAP and try the YAML editor, the variables show up as `{"hello": "there", "secondary_key": "secondary_value"}` instead of as YAML.

**Comment by fosterseth** [comment]
|  they seem to come out as only JSON in the awx output. 

Not sure what you mean by this, can you please provide a screenshot of this? thank you!

**Comment by akus062381** [comment]
Hi @isuftin,

Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
