### ISSUE TITLE
awx.awx.workflow_job_template parameter ask_tags_on_launch doesn't work

### ISSUE THREAD

**Issue by MallocArray** [ansible/awx#13216]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

In the AWX Collection 21.7.0 the parameter ask_tags_on_launch is added to the module awx.awx.workflow_job_template, but trying to use it against AWX 21.7.0 or 21.8.0 does not work with an error that it is an unsupported parameter

### AWX version

21.7.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

ansible [core 2.13.6]

### Operating system

ansible-builder EE

### Steps to reproduce

- name: AWX Workflow Templates
  awx.awx.workflow_job_template:
    controller_host: "{{ inventory_hostname }}"
    controller_username: "{{ controller_username | default(omit) }}"
    controller_password: "{{ controller_password | default(omit) }}"
    controller_oauthtoken: "{{ controller_oauthtoken | default(omit) }}"
    validate_certs: "{{ validate_certs | default(yes) }}"
    organization: "{{ item.organization | default(default_org) }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default('') }}"
    inventory: "{{ item.inventory | default('') }}"
    ask_tags_on_launch: "{{ item.ask_tags_on_launch | default(false) }}"  # Documentation shows supported in 21.7.0 but erroring out
  loop: "{{ workflow_job_templates }}"

### Expected results

Workflow item will enable the option to prompt for tags on launch

### Actual results

"msg": "Unsupported parameters for (awx.awx.workflow_job_template) module: ask_tags_on_launch. Supported parameters include: workflow_nodes (schema), survey_enabled, new_name, validate_certs (tower_verify_ssl), notification_templates_approvals, webhook_service, webhook_credential, controller_password (tower_password), ask_inventory_on_launch, controller_oauthtoken (tower_oauthtoken), ask_skip_tags_on_launch (ask_skip_tags), ask_variables_on_launch, ask_limit_on_launch, name, controller_config_file (tower_config_file), scm_branch, description, ask_labels_on_launch (ask_labels), state, allow_simultaneous, copy_from, organization, notification_templates_started, extra_vars, job_tags, controller_host (tower_host), notification_templates_error, controller_username (tower_username), destroy_current_nodes (destroy_current_schema), ask_scm_branch_on_launch, labels, survey_spec (survey), skip_tags, notification_templates_success, inventory, limit."}

### Additional information

Tested both collection 21.7.0 and 21.8.0 against both AWX 21.7.0 and 21.8.0 with similar results

**Comment by fosterseth** [comment]
needs investigation from a developer

**Comment by AlanCoding** [comment]
Should be fixed with merge of https://github.com/ansible/awx/pull/13330, good find, thanks!
