### ISSUE TITLE
AWX inventory not support vault strings

### ISSUE THREAD

**Issue by Sergiodcm00** [ansible/awx#13227]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Its seems you can not include an string-vault on AWX inventory.
Example:
Password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62623238373433346461383939353233616438333739316439373134363662333938363063333837
          3439633765333163356137656637303261333539323433310a646238376233323563383566313230
          34626364643033663361656566666666333662396561396461353637346564306233306366663130
          3334316330383535340a623162636561633533343034303835656531633362326533366262633866
          3165

returns unknown tag !<!vault> at line 25, column 1: ^ and you cant't save it.

I've read somewhere (no remember) use __vault in place of !vault but then password value its used like a literal string.

### AWX version

19.5.1

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

minikube

### Modifications

no

### Operating system

CentOS8

### Web browser

Firefox

### Steps to reproduce

Create var in AWX inventory with a string-vault value.

### Expected results

You must save the var in AWX inventory and JT must use decrypt vault var value.

### Actual results

I cant save the inventory (error unknown tag !<!vault> at line 25, column 1: ^ and you cant't save it.) var with vault string var.

**Comment by AlanCoding** [comment]
> returns unknown tag !<!vault> at line 25, column 1: ^ and you cant't save it.

To be sure we understand the issue and categorize it correctly, do you mean that you are in the UI, in the host edit screen? In what way does it return that error? It is red text next to the field?

Has this ever worked for you before?

> I've read somewhere (no remember) use __vault in place of !vault but then password value its used like a literal string.

Yes, you have to change the vars format to JSON from YAML. There should be documentation in Ansible about this. This uses special keys in a sub-dictionary (as opposed to YAML native tags), so it's a different data structure. The JSON structure only uses native data types, so you should absolutely be able to use this with any client, without requiring changes to the JSON library it's using. That's the point of the feature.

**Comment by Sergiodcm00** [comment]
> > returns unknown tag !<!vault> at line 25, column 1: ^ and you cant't save it.
> 
> To be sure we understand the issue and categorize it correctly, do you mean that you are in the UI, in the host edit screen? In what way does it return that error? It is red text next to the field?

Yes, exactly. In the host edit screen appears red text error message.

> Has this ever worked for you before?
> 
> > I've read somewhere (no remember) use __vault in place of !vault but then password value its used like a literal string.
> 
> Yes, you have to change the vars format to JSON from YAML. There should be documentation in Ansible about this. This uses special keys in a sub-dictionary (as opposed to YAML native tags), so it's a different data structure. The JSON structure only uses native data types, so you should absolutely be able to use this with any client, without requiring changes to the JSON library it's using. That's the point of the feature.

Thanks for the explain. But when I use __vault in place of !vault password value its used like a literal string. It's not converted wik vault credential.
