### ISSUE TITLE
JT cannot select playbooks missing in main branch when using branch overrides

### ISSUE THREAD

**Issue by azrdev** [ansible/awx#13223]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When Creating/Editing a Job Template, the "Playbook" field only allows selecting from the provided choices, which are the recognized playbook *.yml files in the project on its default branch.
When using branch override and playbooks from said branch which are not on the default branch of the project, these cannot be selected in the GUI. The only way to create a JT with such a playbook is to select any other playbook and then PATCH the field using the API.

### AWX version

21.1.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

1. Create a (git) repository with a default branch (main/master)
2. Create a second branch "X", add a playbook "Y" there that does not exist on the default branch
3. add the project in AWX, enable branch overrides
4. sync the project
5. Create a job template, select this project, insert "X" into "Source Control Branch", try to select "Y" as "Playbook"

### Expected results

Playbooks from non-default branches are selectable, or the input allows inserting their name even though it's not part of the offered choices (IIRC AWX<17 did that)

### Actual results

Only playbooks from default branch can be selected

**Comment by fosterseth** [comment]
this was addressed with this PR https://github.com/ansible/awx/pull/13050

allows you to type in whatever playbook name you want in the playbook field on the job template

having to type in the name is a bit of a workaround, but at least you won't have to patch the API endpoint after creating the JT.

Please upgrade to AWX 21.9.0 and try out this change

**Comment by akus062381** [comment]
Hi @azrdev,

Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
