### ISSUE TITLE
awx.awx.group : preserve_existing_children doesn't work, only its alias preserve_existing_groups

### ISSUE THREAD

**Issue by mooky31** [ansible/awx#13231]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

awx.awx.group : preserve_existing_children doesn't work, only its alias preserve_existing_groups

### AWX version

21.7.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

minikube

### Modifications

no

### Ansible version

5.10

### Operating system

RHEL9

### Web browser

Firefox

### Steps to reproduce

Try to add subgroupB to a parentGroup with existing subgroupA, using preserve_existing_children

### Expected results

parentGroup contains SubgroupA and subgroupB

### Actual results

parentGroup only contains subgroupB

**Comment by djyasin** [comment]
PR #13374
