### ISSUE TITLE
Ansible-Builder fails cause of awx.awx pip requirements

### ISSUE THREAD

**Issue by davidgleiss** [ansible/awx#13235]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Building an execution environment hangs at installing the python requirements for awx.awx.
Issue seems to be the dependency resolver, as there are no versions specified for pytz and awxkit.

This is not an issue of ansible-builder, although there are open issues with the same results: https://github.com/ansible/ansible-builder/issues/425

Output of 'ansible-builder inspect':

```
---
python:
- 'pytz  # from collection awx.awx'
- 'python-dateutil>=2.7.0  # from collection awx.awx'
- 'awxkit  # from collection awx.awx'
system:
- 'python38-pytz [platform:centos-8 platform:rhel-8]  # from collection awx.awx'
- 'python38-requests [platform:centos-8 platform:rhel-8]  # from collection awx.awx'
- 'python38-pyyaml [platform:centos-8 platform:rhel-8]  # from collection awx.awx'
```

Current latest versions of these packages are:
```
pytz == 2022.6
python-dateutil == 2.8.2
```

### AWX version

21.8.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Steps to reproduce

Try to build an EE like in this example, but only with awx.awx collection: https://medium.com/@frederic.egmorte/awx-create-a-new-execution-environment-with-ansible-builder-aee127d5bbdd

### Expected results

pip should be able to install the dependencies for awx.awx, but there are no explicit versions specified in the requirements.

If you use these versions in the user requirements.txt the pip install works as expected:

```
# for collection awx.awx
awxkit == 21.8.0
pytz == 2022.6
python-dateutil == 2.8.2
```

### Actual results

Pip downloads all versions of pytz and awxkit and does not finish installation.

**Comment by shanemcd** [comment]
Hmmm. it looks like the most recent builds of awx-ee are working: https://github.com/ansible/awx-ee/actions/workflows/build-latest.yml. Do you have a reproducer? Please upload your ee definition and/or build context.

**Comment by davidgleiss** [comment]
Nope, can't reproduce it anymore.

Sorry, I thought I figured it out.
