### ISSUE TITLE
"make black" target doesn't actually fix something

### ISSUE THREAD

**Issue by thedoubl3j** [ansible/awx#13241]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

the pre commit check for black checks to see if anything needs to be reformatted then says to make 

### AWX version

awx: 21.5.1.dev434+g3ca14c43bb

### Select the relevant components

- [ ] UI
- [ ] API
- [X] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Ansible version

ansible [core 2.13.1]

### Operating system

Fedora 36

### Steps to reproduce

run `make black` at top level of the project with files that need to be reformatted. 

### Expected results

Files to be reformatted similar to targeting specific files with black. 

### Actual results

```
[thedoubl3j@localhost awx]$ git commit -m "commit msg"
would reformat awx_collection/plugins/lookup/schedule_rrule.py
would reformat awx_collection/plugins/lookup/schedule_rruleset.py

Oh no! 💥 💔 💥
2 files would be reformatted.
To fix this, run `make black` to auto-format your code prior to commit, or set AWX_IGNORE_BLACK=1
[thedoubl3j@localhost awx]$ make black
All done! ✨ 🍰 ✨
800 files left unchanged.
```

### Additional information

current versions locally installed and which is being used
```
[thedoubl3j@localhost awx]$ black --version
black, 22.10.0 (compiled: yes)
Python (CPython) 3.9.15
[thedoubl3j@localhost awx]$ which black
~/.local/bin/black
```

**Comment by relrod** [comment]
I think this is because the pre-commit check runs `black` on against all changed files, without respect to files that `black` is told to ignore:

https://github.com/ansible/awx/blob/fcdff8bdfb6b041cde04c35453a57b843cfd290f/pre-commit.sh#L2-L9

And then we configure `black` to ignore `awx_collection`:

https://github.com/ansible/awx/blob/fcdff8bdfb6b041cde04c35453a57b843cfd290f/pyproject.toml#L5

**Comment by thedoubl3j** [comment]
Is there any reason anyone could think of that we do not extend black to the collection?

**Comment by AlanCoding** [comment]
Yeah, we would be battling between black and pep8 and other things that `ansible-test` runs. I don't think it would be viable.

**Comment by AlanCoding** [comment]
Resolved with linked merge (hopefully)
