### ISSUE TITLE
Add 'Completed Jobs' to host display

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1325]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY

Completed jobs is an option at the inventory level:

![screenshot from 2018-02-22 12-08-11](https://user-images.githubusercontent.com/5208768/36552983-39787f36-17c9-11e8-8b12-bfb983508d82.png)

It is not an option at the host level:

![screenshot from 2018-02-22 12-08-29](https://user-images.githubusercontent.com/5208768/36552994-3dcb5e50-17c9-11e8-9e51-fc43b4fe8323.png)

It should be - as failures are often at the host level, and playbooks can be adjusted with limits, etc - users want to see the management history for a particular pet host.

##### ENVIRONMENT
* AWX version: current

##### ADDITIONAL INFORMATION

Looks like we have job_host_summaries on the API endpoint for the host, if we do not want to do a specific query of unified_jobs.

**Comment by wenottingham** [comment]
This was fixed downstream, and will appear in the next week or three.

**Comment by ryanpetrello** [comment]
Fixed in 1.0.7.
