### ISSUE TITLE
awx 21.6.0 ui - not working

### ISSUE THREAD

**Issue by angelo-cam** [ansible/awx#13269]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When the awx is deployed in docker i ahve the problem with ui 

process.env.NODE_ENV === 'production') { %> <% }

you have a solution?

### AWX version

21.6.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.9.6

### Operating system

Ubuntu 20.04.5 LTS

### Web browser

Chrome

### Steps to reproduce

install awx in docker 21.6.0

### Expected results

visualize Web UI

### Actual results

<% if (process.env.NODE_ENV === 'production') { %> <% } %> <% if (process.env.NODE_ENV === 'production') { %> <% } else { %> <% } %> <% if (process.env.NODE_ENV === 'production') { %>

### Additional information

 python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]

**Comment by akus062381** [comment]
Hi @angelo83rm,

Please make sure you have pulled down the latest code, open AWX inside a container and run make ui-devel to build off the latest code. If this still isn't working for you, please consult our mailing list for additional help with building:
See https://github.com/ansible/awx/#get-involved.

Thank you!
