### ISSUE TITLE
"TypeError: c is undefined" when trying to add or edit projects

### ISSUE THREAD

**Issue by RobinR1** [ansible/awx#13288]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I recently upgraded AWX to 21.8.0 using awx-operator 1.0.0 coming from awx-operator 0.28.0.
Since the upgrade I'm no longer able to add new or edit existing projects. The UI returns an error message "TypeError: c is undefined" but I see no errors in the logs of the awx-web pod nor in the awx-postgresql pod.

Meanwhile I upgraded again, from AWX to 21.8.0 using awx-operator 1.0.0 to AWX 21.9.0 using operator 1.1.0. But the problem remains.

### AWX version

21.9.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

yes

### Ansible version

core 2.12.5.post0

### Operating system

SUSE Linux Enterprise 15 SP4

### Web browser

Firefox

### Steps to reproduce

No idea on how to exactly reproduce and/or what could be the actual cause.
We had a working AWX deploy by awx-operator 0.28.0 where adding and editing projects worked correctly. (I think the existing projects where added in AWX deployed by  operator 0.26.0, but they could still be edited in AWX deployed by operator 0.28.0)
After upgrading awx-operator to 1.0.0 which upgraded AWX itself successfully (I don't remember seeing any noticeable errors), one day I suddenly noticed adding new or editing projects no longer worked. (I don't try that every day, but the upgrade was the only major event I can think of that could have caused this error to exists)

So for now the steps I can provide:
- Install AWX on kubernetes using operator 0.28.0
- Add a few projects using the web ui
- verify you can successfully add/edit projects
- upgrade to awx-operator 1.0.0
- verify AWX is upgraded
- edit an existing project or add a new project using the web ui

### Expected results

See the Add/edit Project web form

### Actual results

Error page is displayed:

```
TypeError: c is undefined
e/<@https://awx.****/static/js/main.43dd0163.js:2:2737683 u@[https://awx.****/static/js/main.43dd0163.js:2:923537 9727/c/a._invoke@https://awx.****/static/js/main.43dd0163.js:2:923326 9727/k/](https://awx.****/static/js/main.43dd0163.js:2:9235379727/c/a._invoke@https://awx.****/static/js/main.43dd0163.js:2:9233269727/k/)</<@https://awx.****/static/js/main.43dd0163.js:2:923966 fr@https://awx.****/static/js/main.43dd0163.js:2:1042669 o@https://awx.****/static/js/main.43dd0163.js:2:1042875 promise callback*fr@https://awx.****/static/js/main.43dd0163.js:2:1042740 o@[https://awx.****/static/js/main.43dd0163.js:2:1042875 mr/](https://awx.****/static/js/main.43dd0163.js:2:1042875mr/)</<@[https://awx.****/static/js/main.43dd0163.js:2:1042935 mr/](https://awx.****/static/js/main.43dd0163.js:2:1042935mr/)<@https://awx.****/static/js/main.43dd0163.js:2:1042813 Pte@[https://awx.****/static/js/main.43dd0163.js:2:2737792 zte/](https://awx.****/static/js/main.43dd0163.js:2:2737792zte/)</e/e/<@https://awx.****/static/js/main.43dd0163.js:2:2742801 u@[https://awx.****/static/js/main.43dd0163.js:2:923537 9727/c/a._invoke@https://awx.****/static/js/main.43dd0163.js:2:923326 9727/k/](https://awx.****/static/js/main.43dd0163.js:2:9235379727/c/a._invoke@https://awx.****/static/js/main.43dd0163.js:2:9233269727/k/)</<@https://awx.****/static/js/main.43dd0163.js:2:923966 fr@https://awx.****/static/js/main.43dd0163.js:2:1042669 o@[https://awx.****/static/js/main.43dd0163.js:2:1042875 mr/](https://awx.****/static/js/main.43dd0163.js:2:1042875mr/)</<@[https://awx.****/static/js/main.43dd0163.js:2:1042935 mr/](https://awx.****/static/js/main.43dd0163.js:2:1042935mr/)<@https://awx.****/static/js/main.43dd0163.js:2:1042813 e@[https://awx.****/static/js/main.43dd0163.js:2:2743234 zte/](https://awx.****/static/js/main.43dd0163.js:2:2743234zte/)</<@[https://awx.****/static/js/main.43dd0163.js:2:2743270 zte/](https://awx.****/static/js/main.43dd0163.js:2:2743270zte/)<@https://awx.****/static/js/main.43dd0163.js:2:2743292 Fl@[https://awx.****/static/js/main.43dd0163.js:2:895909 6813/t.unstable_runWithPriority@https://awx.****/static/js/main.43dd0163.js:2:932713](https://awx.****/static/js/main.43dd0163.js:2:8959096813/t.unstable_runWithPriority@https://awx.****/static/js/main.43dd0163.js:2:932713) Vi@https://awx.****/static/js/main.43dd0163.js:2:836228 Dl@[https://awx.****/static/js/main.43dd0163.js:2:895370 4463/Nl/](https://awx.****/static/js/main.43dd0163.js:2:8953704463/Nl/)<@https://awx.****/static/js/main.43dd0163.js:2:895281 M@[https://awx.****/static/js/main.43dd0163.js:2:931773 6813/_.port1.onmessage@https://awx.****/static/js/main.43dd0163.js:2:930495](https://awx.****/static/js/main.43dd0163.js:2:9317736813/_.port1.onmessage@https://awx.****/static/js/main.43dd0163.js:2:930495) EventHandlerNonNull*6813@https://awx.****/static/js/main.43dd0163.js:2:930419 r@https://awx.****/static/js/main.43dd0163.js:2:983338 5296@https://awx.****/static/js/main.43dd0163.js:2:933360 r@https://awx.****/static/js/main.43dd0163.js:2:983338 4463@https://awx.****/static/js/main.43dd0163.js:2:791372 r@https://awx.****/static/js/main.43dd0163.js:2:983338 4164@https://awx.****/static/js/main.43dd0163.js:2:910088 r@https://awx.****/static/js/main.43dd0163.js:2:983338 @https://awx.****/static/js/main.43dd0163.js:2:986668 @https://awx.****/static/js/main.43dd0163.js:2:3382085 @https://awx.****/static/js/main.43dd0163.js:2:3382088
```

### Additional information

A custom build awx-ee is used for jobs. However inventory refreshes use the default awx control plane ee and for the rest the operator/awx deployment/installation is default (not using helm)

**Comment by akus062381** [comment]
Hi @RobinR1,

This seems to be an issue with the upgrade or possibly your environment. Could you please reach out on our mailing list? 
See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.

**Comment by RobinR1** [comment]
I had actually reached out to the mailing list first (https://groups.google.com/g/awx-project/c/T6c0tfAHgqM/m/sbxSNMn8BAAJ). But there it was suggested to open a bug report here.

**Comment by rooftopcellist** [comment]
@keithjgrant @kialam are either of you able to reproduce this on fresh installs?

**Comment by akus062381** [comment]
Hi @RobinR1,

Are you still seeing this issue when using the latest version of awx-operator (1.1.4)?

**Comment by RobinR1** [comment]
Hi @akus062381 

The problem still remains the same with awx-operator 1.1.4, awx 21.11.0

**Comment by TheRealHaoLiu** [comment]
attempt to reproduce the issue 

provision OpenShfit cluster with the following version on AWS
```
Server Version: 4.11.20
Kubernetes Version: v1.24.6+5658434
```

install awx operator 1.1.4 via operator hub
https://operatorhub.io/operator/awx-operator

verify that I am able to create new project 
verify that I am able to update created project

**Comment by TheRealHaoLiu** [comment]
note: no project persistence or any additional setting is provided to AWX resource

**Comment by RobinR1** [comment]
can I do anything to debug this from my side ? database structures I can check ? more verbose logging I can enable to find out what is exactly going wrong here ?

**Comment by RobinR1** [comment]
This is what I see Firefox console:

```
Uncaught (in promise) TypeError: c is undefined
    e ProjectForm.js:56
    u runtime.js:63
    _invoke runtime.js:294
    k runtime.js:119
    Babel 6
    rne ProjectForm.js:29
    e ProjectForm.js:385
    u runtime.js:63
    _invoke runtime.js:294
    k runtime.js:119
    Babel 4
    e ProjectForm.js:381
    ane ProjectForm.js:381
    ane ProjectForm.js:410
    Fl React
    unstable_runWithPriority scheduler.production.min.js:18
    React 15
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    current Tooltip.tsx:259
    setTimeout handler*ae Tooltip.tsx:258
    ee Popper.tsx:223
    Yl Popper.tsx:233
    Fl React
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    M scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
```

Which seems to point to this line of `ProjectForm.js`:
```
cryptography: { typeId: cryptographyCredentialType.id },
```

**Comment by kialam** [comment]
@RobinR1 if you modify `ProjectForm.js` line `56` to include optional chaining, do you still see the error? 

```javascript
cryptography: { typeId: cryptographyCredentialType?.id },
```
Likewise it might be useful to have optional chaining for all the credentials in that block.

**Comment by RobinR1** [comment]
@kialam Sorry, I'm not sure how to modify that file ? I'm fairly new to kubernetes and even containers and only just deployed awx using instructions here. 
Is there an easy way to modify this in the live environment? Or should I look into how to set up a development environment like described in the Contributing guide ? (this may take me a while, including figuring out how to import the current live DB into that environment)

**Comment by RobinR1** [comment]
I noticed in the projects detail view that credentials are set to "SCM: Gitlab Ansible user", but in the credentials overview, I don't see that credential listed anymore.  I'm assuming this is the cause ?
However the projects still refresh successfully so the credentials must still be stored somewhere for the project refresh jobs to correctly identify to gitlab.

I investigated a bit further and connected manually to the embedded database and did a `select id, name from main_credential;` which returns 12 rows, while the UI only shows 5 credentials.
So I'm suspecting something went wrong during some update where 7 out of 12 credentials became 'corrupted' in some way ?

```
awx=# select id, name from main_credential;
 id |                name                 
----+-------------------------------------
  6 | Ansible Vault Systemen
  2 | Ansible Galaxy
 13 | filer1cl credentials
  3 | Gitlab Ansible user
 11 | Gitlab Container Registry
  5 | OVM Manager Inventory
 10 | Domain Join Credentials
  4 | vCenter Admin
 12 | Windows bootstrap password
  9 | Windows Server admin (domain)
  8 | Linux ops
  7 | Linux root (generic)
(12 rows)
```
While in the UI I only see:

- Ansible Vault Systemen
- Linux ops
- Linux root (generic)
- Domain Join Credentials
- Windows Server admin (domain)

**Comment by RobinR1** [comment]
nevermind previous comment. My user had no permission to see the 7 other credentials. When logged in as admin user I can see the other credentials.. but the error remains the same upon editing or adding a project.

**Comment by mabashian** [comment]
@RobinR1 looking at the code it seems like maybe there's no credential type where `kind` is `cryptography` which the UI expects to be there.  I'm not sure if it's missing due to a migration issue or what.  If you look at `/api/v2/credential_types` do you see a credential type that looks like:

```
        {
            "id": 19,
            "type": "credential_type",
            "url": "/api/v2/credential_types/19/",
            "related": {
                "credentials": "/api/v2/credential_types/19/credentials/",
                "activity_stream": "/api/v2/credential_types/19/activity_stream/"
            },
            "summary_fields": {
                "user_capabilities": {
                    "edit": true,
                    "delete": true
                }
            },
            "created": "2023-03-29T13:40:00.746563Z",
            "modified": "2023-03-29T13:40:00.746563Z",
            "name": "GPG Public Key",
            "description": "",
            "kind": "cryptography",
            "namespace": "gpg_public_key",
            "managed": true,
            "inputs": {
                "fields": [
                    {
                        "id": "gpg_public_key",
                        "label": "GPG Public Key",
                        "type": "string",
                        "secret": true,
                        "multiline": true,
                        "help_text": "GPG Public Key used to validate content signatures."
                    }
                ],
                "required": [
                    "gpg_public_key"
                ]
            },
            "injectors": {}
        },
```

My assumption would be that it's not there which is the source of the issue.

**Comment by RobinR1** [comment]
>  If you look at `/api/v2/credential_types` do you see a credential type that looks like:
> ...

Indeed I seem to be missing that credential_type. There is no credential_type with `"kind": "cryptography"` listed on `/api/v2/credential_types`. 

I have no idea how this could have happened. Can this be a type that should have been added during an update, but never was actually added on my instance? I'm assuming this should be a "built-in" credential type?
I never did any manual changes to the database that could wind me up into this situation.

Can I add it manually somehow ?

**Comment by RobinR1** [comment]
@mabashian 
Today I upgraded to latest (operator 2.1.0) and it seems this upgrade process created the missing credential type in my DB.
`/api/v2/credential_types` now displays the GPG Public Key with `"kind": "cryptography"` like in [your example](#issuecomment-1488893023) and I can edit and add projects again.

So this issue is resolved.

**Comment by mabashian** [comment]
@RobinR1 great!  Thanks for providing that update.
