### ISSUE TITLE
Getting inappropriate amount of hosts in smart inventory 

### ISSUE THREAD

**Issue by vudex** [ansible/awx#13282]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Getting inappropriate amount of hosts in smart inventory while being on search/filter page getting the correct amount.

### AWX version

21.2.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Operating system

Ubuntu 22.04

### Web browser

Chrome

### Steps to reproduce

1) I want to create smart inventory from a several inventories, to manage identical host groups in them. 
2) While creating a smart inventory I specify a filter, which shows exactly the number of hosts I need (I applied group name filter).
![2022-12-03_13-46](https://user-images.githubusercontent.com/2268164/205422674-896d93b9-7ca3-4952-9283-4939aabac981.png)

3) After saving inventory I get only 2 hosts out of 6.
![2022-12-03_13-47](https://user-images.githubusercontent.com/2268164/205422712-660b4f99-6b2a-4e60-afb4-0f88431c337f.png)
![2022-12-03_13-48](https://user-images.githubusercontent.com/2268164/205422718-d8d539c2-a71b-44ad-8bba-117e3a4c2ffc.png)

### Expected results

I get all the hosts listed on the search page in the inventory after save.

### Actual results

Not getting all the hosts.

### Additional information

I get such behaviour while creating a smart inventory either from WebUI or CLI. 
Additionally I can say that in my AWX there are two Organizations, but all inventories are still using the same source (python script that gets hosts from cloud provider). Also, 2 hosts that ending up in the final smart inventory are from the same inventory.
I tried to look for some differences in Organization objects and Inventories, but didn't find any, so I would gladly appreciate some hints on how to approach this problem.

**Comment by vudex** [comment]
So I actually found that inventories of Organization I'm trying to build smart inventory on are actually have as source that is based on Project from different organization. 

So I have a "dynamic-inventory" project, that is in Organization ORG1, but my sources and inventories that are based on that sources are in ORG2. And when I'm trying to build smart inventory on ORG2 I'm getting inconsistencies. Is it intended? I feel like if I'm getting hosts in search menu I should get them in them final inventory, or get a hint that something wrong with Organization referencing, therefore inv can't be built.

**Comment by AlanCoding** [comment]
Your report of getting different results in the edit/test screen versus the final host list after save appears to be a duplicate with the more technical issue of https://github.com/ansible/awx/issues/11985

From your screenshot, I wonder if you have duplicate host names. These will be de-duplicated after the final save, but perhaps not when editing it. Just a theory.

Smart inventory only returns hosts in the same organization as the smart inventory itself. Maybe that helps with some of your followup questions here.

**Comment by vudex** [comment]
@AlanCoding Yes, turns out I do indeed have duplicate names from different inventories, I did not attach importance at first glance. I guess this is the case, organization has nothing to do with it in my case.
