### ISSUE TITLE
tutorial on enabling https for awx gui

### ISSUE THREAD

**Issue by rmitura** [ansible/awx#13283]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

Hello,
I am new to k8s and infrastructure as code deployment.
I managed to install awx v18 using awx-operator since that process is well explained in README.md
However I am struggling to enable awx gui to work over https.
-do I need to install k8s load balancer service (what should I use, how do I do that)
-can I install x.509 cert on the host and bind awx to use it somehow (if so what do I do)
Can someone be so kind and elaborate a bit more on required steps please (please provide steps by step info of what needs to happen as if I was 5y old)?
Thanks,

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

n/a

### Current results

working awx app over tcp30080

### Sugested feature result

more detailed instruction of enabling awx gui over https

**Comment by akus062381** [comment]
Hi @rmitura,
this appears to be less of a bug report or feature request and more of a question. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.
