### ISSUE TITLE
POST to api/v2/job_templates/N/credentials/ incorrect behaviour

### ISSUE THREAD

**Issue by marcos-bonfanti-me** [ansible/awx#13286]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hi! When you make a POST to api/v2/job_templates/N/credentials/ for adding a credential to a job_template, AWX expects a different body from the one in the documentation

https://github.com/ansible/awx/blob/21.8.0/docs/credentials/multi_credential_assignment.md#important-changes

POST /api/v2/job_templates/N/credentials/ {'associate': true, 'id': X'}
POST /api/v2/job_templates/N/credentials/ {'disassociate': true, 'id': Y'}

Instead of adding the existing credential to the job template, it creates a new credential, and this is the body that expects

![image](https://user-images.githubusercontent.com/82385224/205796999-38362181-6c9f-496c-a1e0-9390531831a5.png)

### AWX version

21.8.0

### Select the relevant components

- [ ] UI
- [X] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

Post to api/v2/job_templates/N/credentials/
with body shown in documentation 

https://github.com/ansible/awx/blob/21.8.0/docs/credentials/multi_credential_assignment.md#important-changes

POST /api/v2/job_templates/N/credentials/ {'associate': true, 'id': X'}
POST /api/v2/job_templates/N/credentials/ {'disassociate': true, 'id': Y'}

### Expected results

Attach existing credential to job template

### Actual results

New credential created, and different body expected

**Comment by akus062381** [comment]
@marcos-bonfanti -

thank you for letting us know about the quotation errors in the documentation. I tried myself to add a credential to a job template, and as long as the type of credential did not already exist on the JT, I was able to do so using the following JSON as a POST request:
{"associate": true, "id": 12}

Will you give this a try? I think you'll find success.
We would welcome a PR opened by our community to improve this documentation!

Thank you!

**Comment by AlanCoding** [comment]
The view `JobTemplateCredentialsList` actually is of the type `SubListCreateAttachDetachAPIView`, so you should be able to create a credential from this view. As that is the case, I don't see anything wrong with the suggested fields in the API browser. Whether or not it is a good idea to create a credential at this view is another matter, it is possible to change it to a `SubListAttachDetachAPIView`, but I don't feel strongly motivated to do that.

**Comment by AlanCoding** [comment]
Closing as working-as-intended
