### ISSUE TITLE
404 error in UI navigating to instance in instance group's list

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#13290]
##### ISSUE TYPE
 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME
 - UI

##### SUMMARY
Navigating to an instance from the top-level "Instances" page works fine.

However, if you start from the "Instance Groups" top-level page and navigate to that same instance, it gives an error.

The cluster in this case has 1 hybrid node.

##### STEPS TO REPRODUCE

To spell it out:

 - top level nav -->
   - instance groups -->
     - instance group detail -->
       - instances -->
         - click on hybrid instance

##### EXPECTED RESULTS

I get instance editing page, works fine when navigating from the global instance list. The URL for that is:

https://localhost:8043/#/instances/1/details

![Screenshot from 2022-12-06 14-00-25](https://user-images.githubusercontent.com/1385596/205998757-7ed08278-3823-4a8e-82da-565fb6e28e30.png)

##### ACTUAL RESULTS

404 error

> GET api/v2/instances/1/health_check/ 404
> Not found.

![Screenshot from 2022-12-06 13-41-59](https://user-images.githubusercontent.com/1385596/205996075-8cf850b6-cff9-44d9-bbad-6e544e5831fe.png)

![Screenshot from 2022-12-06 13-41-40](https://user-images.githubusercontent.com/1385596/205996078-c8605048-363e-4a4e-8d84-dbc58c000c31.png)

A page refresh does not clear the error, the URL where I hit this is:

https://localhost:8043/#/instance_groups/2/instances/1/details

##### ADDITIONAL INFORMATION

Using development environment, just 1 hybrid node. Node in question is "awx_1"

```
MAIN_NODE_TYPE=hybrid EXECUTION_NODE_COUNT=0 COMPOSE_TAG=devel make docker-compose
```

**Comment by kialam** [comment]
This is likely fallout due to these being completed: https://github.com/ansible/awx/pull/13041 and https://github.com/ansible/awx/issues/12966. We will have to do a manual check before calling a GET request to /health_check for non-execution nodes as the endpoint no longer exists.
