### ISSUE TITLE
AWX with Netapp ontap 9 SAML authentication

### ISSUE THREAD

**Issue by eselvam** [ansible/awx#13299]
certificate authentication with SAML enabled on a netapp otap cluster is not working. We are able to use cert based authentication however it is redirecting to ADFS SAML.  Please let us know how we can make AWX work with SAML/ADFS/Single single sing on enabled netapp ontap 9.x cluster.  

Awx version: 21.5.0
Netapp: 9.x

**Comment by akus062381** [comment]
@eselvam are you getting any errors that you can screenshot here, to give us more context?

**Comment by eselvam** [comment]
we used below command and it stuck at redirecting of sso ADFS. Nothing specific error message shown. It just prints the sso encrypted info with redirect 302 code.  
curl -v -k https://filer.example.com/api/cluster?fields=version --cert filer.pem --k filer.key

How to use AWX if the application is enabled with sso.

**Comment by akus062381** [comment]
Hi @eselvam,

this appears to be less of a bug report or feature request and more of a question. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.

Thank you!
