### ISSUE TITLE
Custom email template for notification

### ISSUE THREAD

**Issue by kakawait** [ansible/awx#133]
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
May I miss something, but I didn't find a way to customize email template used by built)

##### EXPECTED RESULTS

Be able to pass raw or HTML email template with some variable substitution system.

**Comment by wenottingham** [comment]
dup of #79

**Comment by kakawait** [comment]
Erf I didn't find it issue using search... Sorry! I will track it
