### ISSUE TITLE
how to convert the python code written for ansible 1.9 to ansible 3

### ISSUE THREAD

**Issue by sreecharanm** [ansible/awx#13309]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

we have a code which was written in python2 and used ansible 1.9. 
Now we are upgrading to python3 and **ansible 3.2** here we are facing issue with the modules used for python3
most of the modules has been changed from ansible 1.9 to ansible 3. is there any tool converter like that for this or any plugins to convert the ansible modules and code from ansible 1.9 to ansible 3.0 in python perspective

for example: using 1.9
**********************
**from ansible import callbacks**

stats = callbacks.AggregateStats()
    playbook_cb = callbacks.PlaybookCallbacks(verbose=utils.VERBOSITY)
    runner_cb = callbacks.PlaybookRunnerCallbacks(stats, verbose=utils.VERBOSITY)

whereas in ansible 3.2 (callbacks are deprecated)
***********************
**from ansible.cli.playbook import PlaybookCLI**

where i found to use PlaybookCLI instead of callbacks.
how can i pass verbose and stats to the PlaybookCLI i didn't get any info on this. 

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

we have a code which was written in python2 and used ansible 1.9. 
Now we are upgrading to python3 and **ansible 3.2** here we are facing issue with the modules used for python3
most of the modules has been changed from ansible 1.9 to ansible 3. is there any tool converter like that for this or any plugins to convert the ansible modules and code from ansible 1.9 to ansible 3.0 in python perspective

for example: using 1.9
**********************
**from ansible import callbacks**

stats = callbacks.AggregateStats()
    playbook_cb = callbacks.PlaybookCallbacks(verbose=utils.VERBOSITY)
    runner_cb = callbacks.PlaybookRunnerCallbacks(stats, verbose=utils.VERBOSITY)

whereas in ansible 3.2 (callbacks are deprecated)
***********************
**from ansible.cli.playbook import PlaybookCLI**

where i found to use PlaybookCLI instead of callbacks.
how can i pass verbose and stats to the PlaybookCLI i didn't get any info on this. 

### Current results

we have a code which was written in python2 and used ansible 1.9. 
Now we are upgrading to python3 and **ansible 3.2** here we are facing issue with the modules used for python3
most of the modules has been changed from ansible 1.9 to ansible 3. is there any tool converter like that for this or any plugins to convert the ansible modules and code from ansible 1.9 to ansible 3.0 in python perspective

for example: using 1.9
**********************
**from ansible import callbacks**

stats = callbacks.AggregateStats()
    playbook_cb = callbacks.PlaybookCallbacks(verbose=utils.VERBOSITY)
    runner_cb = callbacks.PlaybookRunnerCallbacks(stats, verbose=utils.VERBOSITY)

whereas in ansible 3.2 (callbacks are deprecated)
***********************
**from ansible.cli.playbook import PlaybookCLI**

where i found to use PlaybookCLI instead of callbacks.
how can i pass verbose and stats to the PlaybookCLI i didn't get any info on this. 

### Sugested feature result

To run the playbook used 

PlaybookExecutor() 
where it is throwing the error saying "TypeError: __init__() got an unexpected keyword argument 'playbook'"

### Additional information

TypeError: __init__() got an unexpected keyword argument 'playbook'

**Comment by relrod** [comment]
Hello,

This appears to be a question about ansible, not awx, so the correct repo would be ansible/ansible. However, the best place to ask your question is probably on the `ansible-project` mailing list: https://groups.google.com/g/ansible-project

Or on Matrix.

See https://docs.ansible.com/ansible/latest/community/communication.html

Hope this helps you find people who are able to help!
