### ISSUE TITLE
bad spacing in sidebar

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1331]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

![bugfu](https://user-images.githubusercontent.com/5208768/36563125-1d62fd1c-17e7-11e8-94ab-56b1802cb367.png)

##### ENVIRONMENT
* AWX version: 1.0.3.41
* Web Browser: Firefox 58.0.1

**Comment by jaredevantabor** [comment]
This is fixed in devel.
