### ISSUE TITLE
AWX has problem to connect to Redis

### ISSUE THREAD

**Issue by filipprosovsky** [ansible/awx#13313]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

After upgrading the AWX-operator to 1.1.1 and AWX included is 21.10.0 with removed aio redis package, we are getting errors in connection.py. See below:

`future: <Task finished name='Task-3' coro=<Connection.disconnect() done, defined at /var/lib/awx/venv/awx/lib64/python3.9/site-packages/redis/asyncio/connection.py:828> exception=RuntimeError('Event loop is closed')>
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/redis/asyncio/connection.py", line 837, in disconnect
    self._writer.close()  # type: ignore[union-attr]
  File "/usr/lib64/python3.9/asyncio/streams.py", line 353, in close
    return self._transport.close()
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 698, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')`

### AWX version

21.10.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

Deploy 1.1.1 of AWX-operator, sync dynamic inventory.

### Expected results

Inventory sync

### Actual results

Job failed and error is present in log.

**Comment by pankaj-pal** [comment]
I can confirm, I have the same issue. Just brought up awx-operator and awx. 

```Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Connection.disconnect() done, defined at /var/lib/awx/venv/awx/lib64/python3.9/site-packages/redis/asyncio/connection.py:828> exception=RuntimeError('Event loop is closed')>
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/redis/asyncio/connection.py", line 837, in disconnect
    self._writer.close()  # type: ignore[union-attr]
  File "/usr/lib64/python3.9/asyncio/streams.py", line 353, in close
    return self._transport.close()
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 698, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2022-12-08 13:34:04,686 ERROR    [-] awx.main.utils.reload supervisorctl restart awx-rsyslogd errored with exit code `7`, stdout:
b'tower-processes:awx-rsyslogd: stopped\ntower-processes:awx-rsyslogd: ERROR (abnormal termination)'stderr:
b''
Task exception was never retrieved
```


Judging by the similar timing of the issue.. python just releases the latest patch ..may it broke something?

**Comment by filipprosovsky** [comment]
Looks like a redis-py issue, [similar redis-py issue](https://github.com/redis/redis-py/issues/2491)
AWX creates the pool same way `redis_conn = await redis.asyncio.create_redis_pool(settings.BROKER_URL)` [line of pool creation](https://github.com/ansible/awx/blob/devel/awx/main/analytics/broadcast_websocket.py#L84)

**Comment by anxstj** [comment]
I experience the same issue with my "docker development environment". AWX 21.10.0.

**Comment by hungpr0** [comment]
Same issue on K3D setup.
I needed to scale down to replicas=1 to workaround the issue. awx-web container keeps crashing because of this.

**Comment by jsalgado78** [comment]
Same issue. It's a new issue in AWX 21.10.0

**Comment by skattaa** [comment]
same here , but very weird seems to be .. I have tried operator 1.1.1 with AWX 21.10.0 and works fine with a new fresh database . when I have migrated the old postgres data to the new database, this problem started to show up !

**Comment by Cartman25** [comment]
The same issue with AWX 21.10.0 & AWX 21.10.1 with an existing Database.
UI is working for now, but this error message keeps looping in awx-task pod.

**Comment by shanemcd** [comment]
https://github.com/django/channels_redis/issues/332 @fosterseth found this

**Comment by filipprosovsky** [comment]
Found 2 commits which could cause this. As removing `channels` and replacing it for `daphne` could affect functioning of [CHANNEL LAYER CORE](https://github.com/ansible/awx/blob/21.10.1/awx/settings/defaults.py#L792)
There is core used instead of pubsub as proposed in issue @fosterseth found.
Commits: [This1](https://github.com/ansible/awx/commit/3b24afa7f2a8276ea8c13f2539dda96c27eb2745) and [This2](https://github.com/ansible/awx/commit/ef29589940bb071b802671f090158f0916f9c260)

Could this be fixed with replacing core to pubsub?

**Comment by relrod** [comment]
@shanemcd In light of that issue, should we downgrade channels-redis for now?

**Comment by pankaj-pal** [comment]
Is there a workaround for this issue in meanwhile?

**Comment by filipprosovsky** [comment]
@relrod I see that PR is merged, thanks a lot! When can we expect a new release to come out, do we have any info?

**Comment by relrod** [comment]
@filipprosovsky I've just cut a release with this fix.

**Comment by filipprosovsky** [comment]
@relrod deployed and working! Thanks a lot, can be closed

**Comment by HGS9761** [comment]
Hello,

Perhaps not the smartest question.
What do I need to do to have the issue fixed in my environment?

Regards Hans-Peter

**Comment by anxstj** [comment]
Hello @HGS9761,

you need to update to 21.10.2. (Or backport the above-mentioned PR to your environment.)

**Comment by HGS9761** [comment]
Thanks
Well that is beyond my expertise I am afraid.
But do I understand correctly that the error can be ignored?
