### ISSUE TITLE
Ansible AWX Status is Disabled

### ISSUE THREAD

**Issue by ekharrat** [ansible/awx#13312]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hello 
![disabled_inv](https://user-images.githubusercontent.com/120107931/206456324-2d5cd806-d179-4a7b-b897-964bfccefcc4.PNG)
i installed ansible awx with docker containers, whenever i create an inventory its status is showing disabled as shown in the attached screenshot , your assistance is appreciated

### AWX version

17.1.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.9.18

### Operating system

Ubuntu 20.04.5 LTS

### Web browser

Chrome

### Steps to reproduce

-

### Expected results

-

### Actual results

-

### Additional information

-

**Comment by kurokobo** [comment]
You can safely ignore it if you don't add any "Inventory Source" for your inventory.

This does not indicate that the whole inventory is invalid and can't be used, but rather that synchronization with the inventory source is disabled.

In recent versions, it has been changed to "Sync Status."
Related: https://github.com/ansible/awx/issues/12478, https://github.com/ansible/awx/pull/12531
![image](https://user-images.githubusercontent.com/2920259/206598400-e9fbfa27-ad08-4bbf-be2c-c2e8a697b375.png)

**Comment by ekharrat** [comment]
Thank you for your update, my aim is to link AWX inventory to /etc/ansible/hosts file , or create a manual inventory locally on the server and just run playbooks and manage them through AWX . can you please advise how to do it ? 

Best Regards 
Elie

**Comment by john-westcott-iv** [comment]
Hello, this appears to be less of a bug report or feature request and more of a question. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.
