### ISSUE TITLE
[web/task split] New `heartbeet` daemon should catch SIGTERM and send a "going offline" message

### ISSUE THREAD

**Issue by relrod** [ansible/awx#13322]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

The new [`run_heartbeet`](https://github.com/ansible/awx/blob/wsrelay/awx/main/management/commands/run_heartbeet.py) daemon will send a heartbeat message via pg_notify broadcast every *n* seconds.

When it is being shut down (i.e. gets a SIGTERM), we should have it send a similar message with `action=offline`.

This allows wsrelay to act on it a bit faster in the "normal" scale down case.

Refs #13319 

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

Use the `web-task-split` branch of awx-operator and `wsrelay` branch of awx. Scale down a web node, and `wsrelay` will usually "fail" a connection by trying to send something over the closed/closing web socket connection.

It handles this case fine and will just remove the producer and the host from it its internal state.

But we can speed up the process and handle the "normal" case a bit better if we have an actual message come across that says "this web node is going offline".

It's already prepared for this message (I think), but `run_heartbeet.py` needs to be modified to send it.

### Current results

Right now, no message is sent when `run_heartbeet.py` is terminated.

### Sugested feature result

See above :)

**Comment by thedoubl3j** [comment]
@jessicamack is taking this during hardening, this is not blocking the feature
