### ISSUE TITLE
[web/task split] Figure out how to ship subsystem metrics to web nodes in the post-`wsrelay` world

### ISSUE THREAD

**Issue by relrod** [ansible/awx#13334]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

This is a tracking issue for $title.

We need to modify how metrics are shipped to the web nodes in the post-`wsrelay` world.

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

Visit /api/v2/metrics on a web node

### Current results

Currently in the `wsrelay` branch, these metrics simply don't show up because the call that used to make them happen is commented out.

### Sugested feature result

At the end of this work, we should have metrics visible at /api/v2/metrics, and administrators should notice no difference to what they see in the pre-split world.

### Additional information

refs #13319

**Comment by jay-steurer** [comment]
@CFSNM is working on the test coverage for this task as part of a new feature.
