### ISSUE TITLE
Session Parity issue between API and UI

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/awx#1333]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY
Login session is not maintained from API to UI. 

Possible related issue is: when you log out on the API side, it doesn’t log out on the UI.

##### ENVIRONMENT
* AWX version: 3.2.3
* AWX install method: docker for mac
* Ansible version:  2.3.1
* Operating System: OS X
* Web Browser: Chrome
* After OAuth2 Merge

##### STEPS TO REPRODUCE

1. Log into the API
2. Navigate to the UI

Temporary fix: 
1. Open Developer's console
2. Click Applications tab
3. Clear all cookies

##### EXPECTED RESULTS

When you log in to the UI and navigate to an API endpoint, the user should remain logged in.  And visa versa.  Currently there is a bug going from the API to the UI.  

##### ACTUAL RESULTS

*Issue*: when a user logs in to the api, then navigates to the UI, the user is logged out and sees an incomplete dashboard.  At this point the user is unable to log in via the UI and needs to clear application cookies manually from the Developer's console to fix it.

**Comment by jaredevantabor** [comment]
Can this be moved to testing? @rooftopcellist

**Comment by rooftopcellist** [comment]
This has been fixed downstream.
