### ISSUE TITLE
Unable to edit/create a "Source Control" type credential OR the choice of the type of credential "Source Control" has disappeared in the creation of a credential

### ISSUE THREAD

**Issue by pxsc437** [ansible/awx#13347]
### Please confirm the following

- [x] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### AWX version

17.1.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.9.27

### Operating system

CentOS 7.9.2009

### Steps to reproduce

- Install AWX 17.1.0
- Connect to Web UI
- Create a 'Source Control' type credential and name it myCred
- Then edit myCred again to check
- Then create 7 empty credential type by naming them from ct1 to ct7
- Edit myCred again to check
- Create an empty 8th credential type by naming it ct8
- Edit myCred again and observe that the web browser displays a blank page --> Bug !
- Also try creating a new Credential and observe that the 'Source Control' type is gone --> Bug !

### Expected results

We do not expect to get a blank page or to see the choice 'Source Control' in the drop-down list of credential types.

### Actual results

1) When edit myCred, observe that the web browser displays a blank page.
2) When try creating a new Credential and observe that the 'Source Control' type is gone.

**Comment by fosterseth** [comment]
@keithjgrant @mabashian 

do we think this is still a bug in newer AWX deployments (they are on AWX v17)?

**Comment by mabashian** [comment]
This should have been addressed a long time ago.  I don't currently see this bug present in awx/devel and confirmed that we now fetch all of the credential types recursively (see https://github.com/ansible/awx/pull/11794).  Give it a try on a more recent version of AWX and if you run into a problem, open up a new issue.

**Comment by pxsc437** [comment]
I found this issue :
[#9610 : machine credential type disapeared in 17.0.1 version](https://github.com/ansible/awx/issues/9610)

The given solution solved my issue.
Change value of PAGE_SIZE from 25 to 50 in web container settings.

> [root@myhost ~]# docker ps
[root@myhost ~]# docker exec -it awx_web bash
bash-4.4# cd /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/settings/
bash-4.4# ls -l
bash-4.4# cp -p defaults.py defaults.py_BAK
bash-4.4# vi defaults.py

> /PAGE_SIZE

    298 MAX_PAGE_SIZE = 200
    299 REST_FRAMEWORK = {
    300     'DEFAULT_PAGINATION_CLASS': 'awx.api.pagination.Pagination',
    301     'PAGE_SIZE': 25,   --> Before
    301     'PAGE_SIZE': 50,   --> After

> bash-4.4# exit
[root@myhost ~]# docker restart awx_web
[root@myhost ~]# docker ps_

Note: I also checked setting this value on AWX21 but it is still at 25.
