### ISSUE TITLE
Missing Changelog for releases

### ISSUE THREAD

**Issue by dgolja** [ansible/awx#1335]
Hi,

Is there any change log for the current and future releases of AWX ?

Would be great that this repository would have a `CHANGELOG.md` describing all the new features, bug fixes, etc.

**Comment by DrPreobrazhensky** [comment]
Guys please write release notes at least for 1.0.7 to 2.0.0. I have no idea about changes and should I upgrade or not.

**Comment by matburt** [comment]
You can see a changelog now on the github releases page: https://github.com/ansible/awx/releases/tag/2.0.1

**Comment by chuckyz** [comment]
@matburt I apologize for responding to a closed issue, but that tag seems to only contain a changelog for the 2.0.1 release.  Did nothing change in the 2.0.0 release aside from a new tag, with nothing in it?

**Comment by matburt** [comment]
We *did* cover this in the AWX community summit at Ansiblefest a few weeks ago. For the 2.0.0 release of AWX we're resetting the way that we manage releases of AWX and comitting to a more stable release cadence where direct upgrades are supported between minor versions.

So <=2.0.0, sorry about that.... 2.0.0+ we'll be better.

**Comment by MarkusTeufelberger** [comment]
Putting the output of `git log` on the https://github.com/ansible/awx/releases page is not a changelog... :-(

**Comment by ryancurrah** [comment]
Agreed it’s unreadable for humans

**Comment by MarkusTeufelberger** [comment]
https://groups.google.com/forum/#!topic/awx-project/x3MOtOzrTm8

Still no improvement so far.

**Comment by weeheavy** [comment]
IMHO still applies for AWX 4.0.0. Apart from https://groups.google.com/forum/#!topic/awx-project/Ixk0VUBA5WA no human-readable changelog exists that would give indication if new features or fixes have been made. The Github release page https://github.com/ansible/awx/releases/tag/4.0.0 is hard to read. Not trying to flame or so, but a good example would be https://docs.stackstorm.com/changelog.html.

**Comment by Freeze** [comment]
Is there a good resource to reference to figure out if changes were made to the API between 4.0.0 and 7.0.0+?  Googling for an AWX changelog led me to this issue.  😒

**Comment by lunarthegrey** [comment]
Why is this closed still? Latest release is 9.1.0 and there's still no human-readable changelog. It's sad to say but, it almost seems as if Red Hat wants everyone to just use Tower and AWX is simply the playgrounds for it.

**Comment by ryanpetrello** [comment]
@lunarthegrey,

We publish changelogs on the official AWX mailing list.  They're generally not a commit-by-commit explanation of *everything* that changed (that's what the commit log is for), but a synopsis of new features, bugs fixes, etc... added since the last release.

Here are some of the more recent examples:

https://groups.google.com/forum/#!topic/awx-project/aYYtuAuHMzY
https://groups.google.com/forum/#!topic/awx-project/YZqcSmspqL0
https://groups.google.com/d/msg/awx-project/48G0df5eDjw/c0C4g4DsDwAJ

**Comment by lunarthegrey** [comment]
Thanks @ryanpetrello, excuse my bit of rage. Has been a tough month... :frowning:

Those mailing list changelogs are good enough for me.

**Comment by andrewsav-bt** [comment]
@ryanpetrello  So is there any place that have a list of these links for each release?

**Comment by ryanpetrello** [comment]
@andrewsav-datacom 

https://github.com/ansible/awx/blob/devel/CHANGELOG.md

**Comment by jamescassell** [comment]
Awesome! Thanks for updating the changelog with historical mailing list posts!
