### ISSUE TITLE
RHACM Ansible automations failing with AWX

### ISSUE THREAD

**Issue by asaf-refaeli** [ansible/awx#13381]
### Bug Summary

I am trying to run automations using AWX and Red Hat Advanced Cluster Management
I configured the _Credentilas_ to my awx server, and created a proper _Ansible template_.
I tried to create a cluster, I selected the template i have created in the '_Automation_' section in '_Create Cluster_', launched the creation and the pre-hook failed with the error:

`curator-job-**** DesiredCuration: install Failed - AnsibleJob test/prehook-xxxx exited with an error`.
so I went to the created cluster project and saw that there are pods named - 
`prehookjob-****-**** : 0/1 Error`

I did oc logs on those pods and these are the results:

`TASK [job_runner : ansible.controller.job_launch] ****************************************************************
[WARNING]: You are using the controller version oc this collection but connecting to AWX
fatal: [localhost]: FAILED! => {"changed": false, "errors": ["The field extra vars was specified but the job template does not allow for it to be overridden"], "msg": "Parameters specified which can not be passed into job template, see errors for details"}`

So I got the yaml of the AnsibleJob that has been created and I noticed that in the 'specs': there is another field that called `extra_vars` - as written in the error (that i did not put myself) that contains all the details of the created cluster for some reason, for example: clusterName, platform, compute(nodes resources) and all the parameters that i put in while creating the cluster. Is there a way to remove this field while creation? - I think this field makes all the problems.
By the way, I tried to manually create the ansible job without the `extra_vars` field and it worked.
Help will be much appreciated,
Thank you

### AWX version

21.8.0

### OpenShift version

4.10.26

### Red Hat Advanced Cluster Management version

2.5

### Steps to reproduce
You will need to try and run ansible automations using Red Hat Advanced Cluster Management, while installing a cluster.

### Expected results
I expected that the automation to be succesful and I will see jobs trying to run on the awx UI.

### Actual results
The automation failed with the error

**Comment by akus062381** [comment]
Hi @asaf-refaeli, thank you for your submission. This appears to be less of a bug report or feature request and more of a question. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.

**Comment by nastacio** [comment]
I tried the same scenario. The RHACM documentation has no mention of what the job template should look like.

In a way, it is a question, but for the RHACM team.

@asaf-refaeli, I found what seem to be RHACM-compatible templates here, but they did not work either, producing the same error about "The field extra vars was specified but the job template does not allow for it to be overridden"

https://github.com/stolostron/ansible-tower-samples

**Comment by nastacio** [comment]
I bumped into this [other issue - https://github.com/ansible/awx/issues/955](https://github.com/ansible/awx/issues/955), which gave me the idea of fixing the problem by setting the "Prompt on launch" in the job template inside Ansible, like this:

<img width="1369" alt="image" src="https://github.com/ansible/awx/assets/3278623/6e9e5c4b-4fbb-45a7-a586-209c9195a444">

After that, the job was executed successfully as a prehook in RHACM and I can see the job run in Ansible Tower:

<img width="604" alt="image" src="https://github.com/ansible/awx/assets/3278623/d2f79dae-f46a-416b-845b-9f7525517789">

<img width="1715" alt="image" src="https://github.com/ansible/awx/assets/3278623/5475bafb-2a93-4651-89d7-8290bc439f1e">
