### ISSUE TITLE
Server Error thrown when trying to edit external secret in Ansible Automation Platform

### ISSUE THREAD

**Issue by timothydilbert** [ansible/awx#13386]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Ansible Automation Hub throws "**A server error has occurred.**" message when you attempt to edit a secret that's stored in Thycotic Secret Server.

### AWX version

Ansible Automation Platform Controller 4.2.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Ansible version

ansible [core 2.13.3]

### Operating system

RHEL 8

### Web browser

Chrome

### Steps to reproduce

1. Within Ansible Automation Hub add an external secret from Thycotic Secret Server.
2. Within Ansible Automation Hub, attempt to edit the credential, making changes to the **Description** field.

### Expected results

You should be able to make changes like updating the Description (etc.).

### Actual results

The following error is thrown in the Ansible Automation Hub UI:
```
A server error has occurred
```

### Additional information

The only workaround is to delete the credential in Ansible Automation Hub and then re-added it. This is a pain because we have to re-map it to all of the job templates using this credential.

**Comment by akus062381** [comment]
Hi @timothydilbert, thank you for your submission. 

It appears that you are using an RPM build for RHEL. Please reach out to the Red Hat support team and submit a ticket.
Here is the link to do so:

https://access.redhat.com/support

Thank you for your submission and for supporting AWX!

**Comment by timothydilbert** [comment]
Noted with thanks.
