### ISSUE TITLE
rsyslog centos stream9 

### ISSUE THREAD

**Issue by vailenwallaces** [ansible/awx#13394]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

rsyslog package from  centos 9 rsyslog-8.2102.0-107.el9 get an error message: 

"rsyslogd could not update the internal posix capabilities settings based on the options passed to it, capng_updatev=-1"

If you build with rsyslog-8.2102.0-106.el9 it is working. 

### AWX version

21.10.2

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

docker development environment

### Modifications

no

### Steps to reproduce

make docker-compose-build

### Expected results

rsyslogd ist up and running the the container

### Actual results

awx_1 Container stoped with exit 0

**Comment by shanemcd** [comment]
Workaround for this has been merged.
