### ISSUE TITLE
Incorrect deprecation warning for awx.awx.schedule_rrule

### ISSUE THREAD

**Issue by jmighion** [ansible/awx#13417]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When using the schedule_rrule lookup plugin in the awx collection, I get the following deprecation warning:

```
[DEPRECATION WARNING]: The lookup plugin 'awx.awx.schedule_rrule' was expected to return a list, got '<class 'str'>'
instead. The lookup plugin 'awx.awx.schedule_rrule' needs to be changed to return a list. This will be an error in Ansible
2.18. This feature will be removed in version 2.18. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
```

This seems wrong because that plugin does intend to return a string and not a list. 

Ansible version:
```
$ ansible --version
ansible [core 2.14.1]
  config file = /Users/jmighion/.ansible.cfg
  configured module search path = ['/Users/jmighion/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jmighion/.pyenv/versions/3.10.0/envs/3.10.0_dev/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/jmighion/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/jmighion/.pyenv/versions/3.10.0_dev/bin/ansible
  python version = 3.10.0 (default, Dec  6 2021, 14:41:16) [Clang 12.0.0 (clang-1200.0.32.2)] (/Users/jmighion/.pyenv/versions/3.10.0/envs/3.10.0_dev/bin/python3.10)
  jinja version = 3.1.2
  libyaml = True
```

awx.awx version 21.10.0

Sample playbook:
```
- name: Test
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Debug
      ansible.builtin.debug:
        msg: "{{ query('awx.awx.schedule_rrule', 'hour', start_date='2022-01-01', timezone='GMT') }}"
```

### AWX version

21.10.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Ansible version

2.14.1

### Steps to reproduce

Run the sample playbook.

### Expected results

No deprecation warning.

### Actual results

Seemingly incorrect deprecation warning.

**Comment by AlanCoding** [comment]
Here's an example of another lookup plugin, which really has no right to be returning a list, but nonetheless returns a list with 1 element in it. The word "string" is even in the name of the plugin...

https://github.com/ansible-collections/community.general/blob/main/plugins/lookup/random_string.py#L131

So something weird is going on.

https://github.com/ansible/ansible/blob/6d0aeac1e166842f2833f4fb64c727cc7f818118/lib/ansible/template/__init__.py#L863

https://github.com/ansible/ansible/pull/77875

I don't really claim to understand this, but it appears the expectation is on the awx.awx collection to conform to the updated standard.

**Comment by thedoubl3j** [comment]
@AlanCoding that is correect, there has been a few updates to the sanity suite around and ansible itself around the types of returns as well as mismatching arg spec <-> docs which warned of this error. If someone has time before I do, if you run the `ansible-test sanity --docker` with ansible version 2.14 > you will see a few more you will see these errors, they can go in an open issue.

**Comment by AlanCoding** [comment]
Hmm, I put up https://github.com/ansible/awx/pull/13422 so that the check would run the sanity tests with devel, and discover the failures you mention. In the steps, it does clearly confirm Ansible core version `2.15.0.dev0` is installed. I don't doubt that it should have failures, but this passes. Is it something to do with using the `--docker` flag? If the tests use the Ansible install from inside of the container, then I don't get it.

**Comment by AlanCoding** [comment]
@thedoubl3j I tried to double-check this locally, so I ran with Ansible devel locally _without_ the `--docker` flag, and it still passed. This appears consistent with the result from that attempt to do the same with CI. It's not returning any failures in either case.

Nonetheless, I _am_ able to reproduce the depreciation warning in my local environment with the playbook in this issue. It just seems to me right now that the sanity tests don't catch this.

**Comment by AlanCoding** [comment]
I tried this patch, and it successfully addressed the warning, but...

```diff
diff --git a/awx_collection/plugins/lookup/schedule_rrule.py b/awx_collection/plugins/lookup/schedule_rrule.py
index 5f1d34c0ae..fb9ae9e304 100644
--- a/awx_collection/plugins/lookup/schedule_rrule.py
+++ b/awx_collection/plugins/lookup/schedule_rrule.py
@@ -82,7 +82,8 @@ RETURN = """
 _raw:
   description:
     - String in the rrule format
-  type: string
+  type: list
+  elements: string
 """
 import re
 
@@ -147,7 +148,7 @@ class LookupModule(LookupBase):
 
         frequency = terms[0].lower()
 
-        return self.get_rrule(frequency, kwargs)
+        return [self.get_rrule(frequency, kwargs)]
 
     def get_rrule(self, frequency, kwargs):
 
```

output before:

```
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are
modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of code and
can become unstable at any point.

PLAY [Test] **********************************************************************************************************

TASK [Debug] *********************************************************************************************************
[DEPRECATION WARNING]: The lookup plugin 'awx.awx.schedule_rrule' was expected to return a list, got '<class 'str'>' 
instead. The lookup plugin 'awx.awx.schedule_rrule' needs to be changed to return a list. This will be an error in 
Ansible 2.18. This feature will be removed in version 2.18. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
ok: [localhost] => {
    "msg": "DTSTART;TZID=GMT:20220101T000000 RRULE:FREQ=HOURLY;INTERVAL=1"
}

PLAY RECAP ***********************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```


output after:

```
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are
modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of code and
can become unstable at any point.

PLAY [Test] **********************************************************************************************************

TASK [Debug] *********************************************************************************************************
ok: [localhost] => {
    "msg": [
        "DTSTART;TZID=GMT:20220101T000000 RRULE:FREQ=HOURLY;INTERVAL=1"
    ]
}

PLAY RECAP ***********************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```

So this materially changes the behavior of playbooks. Presumably though, this is a problem for all content, everywhere, that previously had a scalar return value. I read the docs, this was previously supported, and now it's not. The change isn't coming from us, as the collection maintainers, but it will be hard backward-incomparable. The warning message doesn't actually give advice about how to change the playbook, and I'm skeptical that it's our domain to add such a thing.

FYI to @john-westcott-iv , I think you introduced the plugin. I really want someone else to tell us explicitly what to do, whatever user disruption comes from it was accepted by the decision making another level, so I would not rule out breaking-changes, because it's out of our hands.

**Comment by thedoubl3j** [comment]
Interesting @AlanCoding so then this is a different issue then what I was experiencing. Good work on digging into it. I will log another issue separate of this if I find what I was running into.

**Comment by MallocArray** [comment]
I'm seeing the same depreciation warning after upgrading to 2.14.6 from 2.13.x.  I'm doing everything as the documentation appears to be showing, so not sure if the end user really has anything to do or not

```
TASK [awx_job_template : AWX Job Templates] ************************************
[DEPRECATION WARNING]: The lookup plugin 'awx.awx.schedule_rrule' was expected 
to return a list, got '<class 'str'>' instead. The lookup plugin 
'awx.awx.schedule_rrule' needs to be changed to return a list. This will be an 
error in Ansible 2.18. This feature will be removed in version 2.18. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
```

**Comment by MallocArray** [comment]
This error is still present.  Since 2.17 is now out, we aren't far away from 2.18 when this is reported to be full removed and start breaking things

**Comment by bheisig** [comment]
As expected it breaks with recently released Ansible 2.18:

~~~
msg: >-
  The lookup plugin 'awx.awx.schedule_rrule' was expected to return a list, got
  '<class 'str'>' instead. The lookup plugin 'awx.awx.schedule_rrule' needs to
  be changed to return a list. 
~~~

Is there any workaround other than downgrading Ansible?

**Comment by jmighion** [comment]
Looks to be the same issue with rruleset as well

```
[DEPRECATION WARNING]: The lookup plugin 'awx.awx.schedule_rruleset' was expected to return a list, got '<class 'str'>' instead. The lookup plugin 'awx.awx.schedule_rruleset'
 needs to be changed to return a list. This will be an error in Ansible 2.18. This feature will be removed in version 2.18. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
```

**Comment by AlanCoding** [comment]
This got more aggressive to the point of failing the checks, the action was super clear so change was made in https://github.com/ansible/awx/pull/15625

This may require modifying playbooks with that collection version, using `lookup`, and treating the output as a string (not a list) is recommended. We don't envision this lookup plugin to ever by used as `query` which returns a list.

**Comment by jmighion** [comment]
@AlanCoding @thedoubl3j this still seems to be an issue. Can this be reopened until the fix is in?

**Comment by chrisahl** [comment]
On newer ansible versions, we are busted with this error.  Can someone give an example of how we are supposed to get around this regression while picking up a newer ansible version?  We are currently stuck at ansible==10.6.0

**Comment by exu-g** [comment]
Please reopen this issue. It's obviously not working with any version newer than Ansible 2.17
