### ISSUE TITLE
network connection issue using group names

### ISSUE THREAD

**Issue by TheFausap** [ansible/awx#1341]
Hello,

i'm using mongodb example (from ansible-examples git repo) but I have this error (quite at the end):

"msg": "Failed to connect to the host via ssh: OpenSSH_7.2p2 Ubuntu-4ubuntu2.4, OpenSSL 1.0.2g  1 Mar 2016\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/tmp/awx_39_DXJ8D3/cp/groups.replication_servers22root\" does not exist\r\ndebug2: resolving \"groups.replication_servers\" port 22\r\ndebug2: ssh_connect_direct: needpriv 0\r\ndebug1: Connecting to groups.replication_servers [10.74.202.10] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 10.74.202.10 port 22: Connection refused\r\nssh: connect to host groups.replication_servers port 22: Connection refused\r\n",

it tries to connect to groups.replication_servers ! The DNS I'm using is another funny thing, and it resolves this unexistent name with its IP address.

Why ansible see that group name as a DNS name ?

I'm at this step (from ansible-examples/mongodb/roles/mongod/tasks/main.yml)

- name: create data directory for mongodb
  file: path={{ mongodb_datadir_prefix }}/mongo-{{ inventory_hostname }} state=directory owner=mongod group=mongod
  delegate_to: '{{ item }}'
  with_items: groups.replication_servers

My version is

awx@u1604:~$  . /var/lib/awx/venv/ansible/bin/activate
(ansible) awx@u1604:~$ ansible --version
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/awx/.local/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

running under Ubuntu 16.0.4

thanks,
Fausto

**Comment by matburt** [comment]
If you need help with ansible then you should ask a question on their mailing list or irc channel. This tracker is for the AWX project.
