### ISSUE TITLE
Not able to login in the UI

### ISSUE THREAD

**Issue by Piyush1786** [ansible/awx#13432]
### Please confirm the following

- [x] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Not able to login in the UI with the default username and password

### AWX version

17.0.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.13

### Operating system

RHEL 8.7

### Web browser

Edge

### Steps to reproduce

Proceeded with the steps given in the install.md file and the default username and password didn't work

### Expected results

That i should get login into the AWX UI using default username and password

### Actual results

Invalid username and password

**Comment by djyasin** [comment]
Hello, this issue pertains to an older version of AWX. Try upgrading to the latest version and let us know if that resolves your issue.
