### ISSUE TITLE
[constructed-inventory] add --limit to inventory sources

### ISSUE THREAD

**Issue by TheRealHaoLiu** [ansible/awx#13436]
https://github.com/ansible/ansible/pull/79596 introduced --limit option to `ansible-inventory`

we want to expose this feature to all inventory including the new constructed inventory

**Comment by gamuniz** [comment]
How do we add version detection to ansible-inventory command for user provided execution environments?

**Comment by TheRealHaoLiu** [comment]
from Friday's testing we discover that the new option also need to be exposed through serializer as well as additional work is needed to add the new option to AWXkit

**Comment by gamuniz** [comment]
@TheRealHaoLiu https://github.com/ansible/awx/pull/13456
