### ISSUE TITLE
Not able to do bulk inventory upload to awx

### ISSUE THREAD

**Issue by dpatel-mbira** [ansible/awx#13443]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I'm getting the following when trying to do a bulk upload of hosts into an inventory:

 bash-5.1# awx-manage inventory_import --inventory-name ALL_HOSTS --source hosts_add
    1.529 INFO     Updating inventory 4: ALL_HOSTS
2023-01-12 16:11:46,830 INFO     [-] awx.analytics.job_lifecycle inventoryupdate-16 created
    1.576 WARNING  This command is not able to run on kubernetes-based deployment. This action should be done using the API.

Is there any way around this? I went on the pod and did awx-manage but it's not accepting this.

### AWX version

1.1.0 (21.9.0 )

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

Go into docker hosting the pods:
docker exec -it minikube /bin/bash

Go into the pod as awx and create the root user in /etc/passwd
docker exec -it -u awx k8s_awx-demo-task_awx-demo-597d866648-b2rsx_awx_58ff9c0f-239b-4018-958d-8b60897653af_0 bash
vi /etc/passwd <-- add root

exit the container and go back in as root
docker exec -it -u root k8s_awx-demo-task_awx-demo-597d866648-b2rsx_awx_58ff9c0f-239b-4018-958d-8b60897653af_0 bash

Run awx-manage commands
awx-manage version

### Expected results

something like this:

[root@awx awx]# awx-manage inventory_import --inventory-name Linux_UA_Hosts --source hosts_add
   13.320 INFO     Updating inventory 2: Linux_UA_Hosts
   13.965 INFO     Reading Ansible inventory source: /var/lib/awx/hosts_add
   22.051 INFO     Processing JSON output...
   22.052 INFO     Loaded 0 groups, 8 hosts
2018-11-26 17:03:32,529 DEBUG    awx.main.models.inventory Going to update inventory computed fields
2018-11-26 17:03:32,705 DEBUG    awx.main.models.inventory Finished updating inventory computed fields
   22.581 INFO     Inventory import completed for  (Linux_UA_Hosts - 7) in 10.2s

### Actual results

bash-5.1# awx-manage inventory_import --inventory-name ALL_HOSTS --source hosts_add
    1.529 INFO     Updating inventory 4: ALL_HOSTS
2023-01-12 16:11:46,830 INFO     [-] awx.analytics.job_lifecycle inventoryupdate-16 created
    1.576 WARNING  This command is not able to run on kubernetes-based deployment. This action should be done using the API.

**Comment by djyasin** [comment]
Hello @dpatel-mbira,
We are currently working on a way to allow for bulk inventory adds through the API. You can see more here: https://github.com/ansible/awx/pull/13369

In the meantime, there are other ways that you can accomplish this. An inventory source,  using awxkit import, or with a playbook using the awx awx collection. 

You may find this documentation helpful:
https://docs.ansible.com/automation-controller/latest/html/userguide/inventories.html#sourced-from-a-project

At this time we don't have any plans to adjust the awx-manage command on a Kubernetes deployment.

**Comment by GitGorgon** [comment]
Hopeless.
