### ISSUE TITLE
Credentials Missing Job Template Tab

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#13442]
There is a certain list of credential types which are allowable for use with a job template.
Those credentials should have, within them, a job template tab, where the user can 1) view associated job templates and 2) create a new job template

The following credentials should have a job template tab within them, but do not:

- Amazon Web Services
- Google Compute Engine
- Microsoft Azure Resource Manager
- OpenStack
- Red Hat Ansible Automation Platform
- Red Hat Satellite 6
- Red Hat Virtualization
- VMWare vCenter
- GPG Key
- OpenShift or Kubernetes API Bearer Token

(Network, Machine, and Vault, which are credential types that can be associated with job templates, all have the job template tab within them.)

The cred types outlined above should have the job template tab available within them.

To reproduce:
Create any of the credential types in the bullet point list above. Click into the job template and you will see there is no Job Template tab.

**Comment by mabashian** [comment]
@AlexSCorey it looks like this came in with https://github.com/ansible/awx/pull/13262.  I do see your note around limiting the Job Templates related tab to only those credentials with a `kind`.  It seems like there's some sort of mismatch here though.  For example, AWS credentials can definitely be added to a job template and we used to show the job templates tab on a credential like that:

<img width="1720" alt="Screen Shot 2023-01-18 at 11 29 40 AM" src="https://user-images.githubusercontent.com/9889020/213236903-4f07dee2-556d-4291-87c6-f5dc4e624e31.png">
