### ISSUE TITLE
RFE: Include dynamic entries in multi-choice survey drop-down menu

### ISSUE THREAD

**Issue by b0urn3** [ansible/awx#1346]
##### ISSUE TYPE
 - Feature Idea
 
##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Add possibility to use external resources (e.g. any database) for including entries under the drop down menu. 

##### ENVIRONMENT
* AWX version: N/A
* AWX install method: N/A
* Ansible version:  N/A
* Operating System: N/A
* Web Browser: N/A

##### STEPS TO REPRODUCE
In survey definition (multi-choice type, both single/multi select) under the drop down menu we can currently only define static entries.

Consider possibility to include/put dynamic entries under drop down that will fetch data from external location e.g. some database (external to the tower - not it's PostgreSQL).

##### EXPECTED RESULTS
Capability to add dynamic values to multi-choice drop-down menu.

**Comment by wenottingham** [comment]
see #20

**Comment by ooasis** [comment]
In our use case, we need to be able to select from a list of available builds for deployment.  

Any estimate when this feature might be available?

-thanks

**Comment by wenottingham** [comment]
A la Duke Nukem Forever... "when it's done". No estimates beyond that.
