### ISSUE TITLE
RFE: Prompt to choose which Vault credential to use on job template launch

### ISSUE THREAD

**Issue by Ompragash** [ansible/awx#1347]
##### ISSUE TYPE

  - Feature Idea
 
##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

Ability to choose Vault credential when launching a job template, similar to current functionality of machine credentials. 

##### ENVIRONMENT
* AWX version: N/A
* AWX install method: N/A
* Ansible version:  N/A
* Operating System: N/A
* Web Browser: N/A

##### EXPECTED RESULTS

Ability to choose Vault credential when launching a job template.

**Comment by AlanCoding** [comment]
This appears to be a mis-communication with the UI. If the JT is set to Prompt for Credential on Launch, then you can provide vault credentials on launch.

To do this, you need to select "Vault" in the credential type dropdown, and then you can choose from your vault options.

![screen shot 2018-02-26 at 8 30 53 am](https://user-images.githubusercontent.com/1385596/36673089-8dc799a6-1acf-11e8-8f66-2cdc8debe4c5.png)

This feature is functional in current `devel` by my testing.
