### ISSUE TITLE
awxkit: Use awx groups create as non-System-Administrator

### ISSUE THREAD

**Issue by CWollinger** [ansible/awx#13484]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

awxkit: Use `awx groups create` as non-System-Administrator

It is not possible to create groups in an inventory as admin (org. admin, inventory admin of org. or admin role). Only System Administrators are able to perform this cli option. This does not apply for the host creation. 

### AWX version

21.10.2

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Installation method

minikube

### Modifications

no

### Ansible version

awxkit 21.11.0

### Steps to reproduce

1. Create a new (normal) user
2. Assign org. admin, inventory admin or admin role for the Demo Inventory
3. Create write token for new user
4. Create write token for System Administrator
5. Try to create a group in the Demo Inventory with both tokens
6. Unable to create groups in the Demo Inventory as org. admin, inventory admin or admin role

(basic authentication behaves the same) 

### Expected results

As admin of an inventory, you should be able to create new groups in it. (like hosts option)

### Actual results

`group create `function is not available for non-System-Administrators
Error:

````
awx --conf.host https://example.com--conf.token TOKEN groups create --name tmp --inventory 1
usage: awx groups [-h] action ...

positional arguments:
  action
    list
    get
    modify
    delete

options:
  -h, --help  show this help message and exit

awx groups: argument action: invalid choice: 'create' (choose from 'list', 'get', 'modify', 'delete')

````

**Comment by AlanCoding** [comment]
Thanks @CWollinger, this is a valid bug in the API. I have put up a fix at https://github.com/ansible/awx/pull/13500, I'm fairly sure it solves the issue you faced, but I have not tested it with the CLI at this moment.

**Comment by AlanCoding** [comment]
Fix merged, should be good to close soon.
