### ISSUE TITLE
[constructed-inventory] add constructed inventory to awx module

### ISSUE THREAD

**Issue by TheRealHaoLiu** [ansible/awx#13495]
https://github.com/ansible/awx/issues/13447

introduced the constructed inventory view 

this view needed to be exposed via awx module

**Comment by AlanCoding** [comment]
I think users could still do everything through the normal inventory view, but this would require knowledge of some API behavior. Even so, I would rate this as very low priority, as other TODO items are core feature development.

**Comment by TheRealHaoLiu** [comment]
we can't add input inventory via the inventory module
