### ISSUE TITLE
Disable job isolation using tower-cli missing docs

### ISSUE THREAD

**Issue by e-minguez** [ansible/awx#1350]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME
 - Configuration

##### SUMMARY
This https://docs.ansible.com/ansible-tower/latest/html/administration/tipsandtricks.html#setting-up-a-jump-host-to-use-with-tower can be done using tower-cli

##### ENVIRONMENT
* AWX version: ansible-tower-server-3.2.2-1.el7.x86_64
* AWX install method: rpms
* Ansible version:  ansible 2.4.2.0
* Operating System: RHEL 7
* Web Browser: n/a

##### STEPS TO REPRODUCE
Instead using the gui to disable job islation, tower-cli can be used as:

tower-cli setting modify AWX_PROOT_ENABLED false

##### ADDITIONAL INFORMATION
I've tried to create the PR by myself, but I couldn't find the docs repo...

**Comment by matburt** [comment]
This is probably better placed on the `tower-cli` repo. Since tower-cli is not required the Tower product docs tend to focus on Tower-interface centric solutions.

**Comment by e-minguez** [comment]
I think there are some "tower-cli" commands in the same section, so I'd say a "note" on how to do it with tower-cli could be nice.
