### ISSUE TITLE
Is it possible ot use AWX17.10 with python3.9 ?

### ISSUE THREAD

**Issue by jaawasth** [ansible/awx#13518]
##### ISSUE TYPE

 - Question

##### COMPONENT NAME

 - Docs

##### SUMMARY
I have a hard depedency on AWX17, and its required to move to python3.9, is possible to do that or can it break ?
The current version is 17.10 on python3.6 and ubuntu 18
we are using awx as a custom docker image with the base image being ubunt18.04 and creating awx layers on top of it.
We are now required to move to python3.9, will it be safe enough to do that ? [no major impacts to awx internals if we move to py3.9 ?]
##### ENVIRONMENT
* AWX version: 17.10.0
* AWX install method: operator
* AWX deployment target: VM
* Operating System: ubuntu18.04

**Comment by shanemcd** [comment]
Hi - we don't have the resources to support older versions of AWX. AWX 17.1.0 came out almost 2 years ago. If you look at our past releases, AWX is a one-way train. It's possible that you may find someone willing to help on the mailing list [mailing list](https://groups.google.com/forum/#!forum/awx-project) or the `#ansible-awx` channel on irc.libera.chat - but we unfortunately we can't.
