### ISSUE TITLE
callback receiver flushing too often

### ISSUE THREAD

**Issue by fosterseth** [ansible/awx#13517]
##### SUMMARY

noticed all these messages in the task container (indefinitely)
```
awx awx-7d9b5ccb4b-tblkq awx-task 2023-02-02 20:49:06,109 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(0)
awx awx-7d9b5ccb4b-tblkq awx-task 2023-02-02 20:49:06,109 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(0)
awx awx-7d9b5ccb4b-tblkq awx-task 2023-02-02 20:49:06,110 DEBUG    [-] awx.main.commands.run_callback_receiver JobEvent.objects.bulk_create(0)
awx awx-7d9b5ccb4b-tblkq awx-task 2023-02-02 20:49:06,110 DEBUG    [-] awx.main.commands.run_callback_receiver JobEvent.objects.bulk_create(0)
```
from @AlanCoding 
"I removed self.buff = {} which was our prior method for clearing the buffer - because it was giving problems in some error cases the buffer didn't get cleared and that's a big problem.
this was replaced with self.buff[cls] = [], class-specific after a full bulk_create success. This allows us to remove individual events when there are more fine grain problems encountered."

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - API

**Comment by AlanCoding** [comment]
To clarify the negative consequences of this as I see it:
 - Obviously this is over-logging, but to the point that the task container logs are unusable, and current AWX users should be affected by this
 - We will also be running `bulk_create` calls very frequently, although it is passed an empty list. This may cause excess database activity, but not actually sure.

**Comment by jay-steurer** [comment]
PR's were merged yesterday. Closing it
