### ISSUE TITLE
New EE killed AWX

### ISSUE THREAD

**Issue by it-pappa** [ansible/awx#13534]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Just added EE 21.11.0 to test a playbook since i get errors in the latest one (still). 
(I added and did not change the awx EE). 

When running win_ping agains a inventory host, AWX gave bad gateway and killed the whole thing. AWX doesnt work anymore? 
After reloading the page i get: 404 page not found. 

### AWX version

latest

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.11 (devel)

### Operating system

Ubuntu 22.04

### Web browser

Chrome

### Steps to reproduce

Any install of AWX. 
Go to Execution environments and press Add. 
Add a new EE, press save and run a win_ping from inventory command with that EE. 

### Expected results

To run win_ping and not die. 

### Actual results

Bad gateway then no web gui. Gets 404 page not found.

**Comment by it-pappa** [comment]
Update: 
After a hard restart og the server and wait for a while. It is up and running again.
Looks like a timeout when downloading an EE?

**Comment by shanemcd** [comment]
Hi @it-pappa - we really can't ascertain much based on the details you shared here. Is there anything more helpful in the logs?

**Comment by it-pappa** [comment]
@shanemcd Hi, after poking around i dont feel this is an error from the EE or anything like that. I think it was a timeout or something else happening to the awx when starting to download the other EE. I think this one can be closed
