### ISSUE TITLE
[20+] Cannot extend base image anymore, as it seems network is unreachable since the migration to CentOS 9

### ISSUE THREAD

**Issue by mbutton77** [ansible/awx#13543]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hi,

I've encountered a weird behavior while migrating from 17 to 21.11.0. 
We're not directly using the AWX base image in the Operator, but we're first extending it with some packages (to suit my client needs).
In 17, we used to define our own YUM repo and installed those packages. Everything was smooth and we could generate our own image without any problem.

We decided to migrate to the latest version (21.11.0 at the time of writing). And then our build pipeline failed. At first, we thought it was because the new internal mirrors towards CentOS9 repo were not up, but that's not it : no external URL is reachable.

I tried to diagnose the problem, by logging into the image and and performing some network investigations but as the image does not have any network tool (ping, ip, host, dig, tracepath ...) it's very hard to tell what's wrong. I checked the _resolv.conf_, the _hosts_ file, the _selinux_ config, _access.conf_, etc and nothing obvious came out of it.

I checked all the versions and the problem seems to appear in version 20 (with the switch to CentOS9).
Again, I may miss something obvious but I carefully read the docs (AWX + CentOS), browsed the current issues and couldn't find the slightest clue.

For now, as I'm in an early stage, I just dropped the installation of additional packages, but as they were security related, I won't be able to go in production without them.

If you have something in mind, I would be glad to hear it.

Thanks !

### AWX version

21.11.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

yes

### Ansible version

Not relevant here

### Operating system

Not relevant here as well

### Steps to reproduce

`docker build . `

Using this Docker file : 

```
#ARG AWX_VERSION=17.1.0@sha256:d5d6003a9f32c3d00ee4be3275f62186937570e9e33776f848dbe9185623da97 # OK
#ARG AWX_VERSION=19.2.0@sha256:f7cdabee0da2ea195e3dab8a8b39f3f5f1f32f0d2ee3d0ac561ec7d640d7042d # OK
#ARG AWX_VERSION=19.5.1@sha256:e68ec0ad39f2b8d1a28f65fef9431c244537e7a6791c0b12ffb1ee07a76c421a # OK
#ARG AWX_VERSION=20.0.0@sha256:1af0d56bda7ae6e8ff69046d5833ea14669ea8c12ac1a3bef88c98722ff1afda # KO
#ARG AWX_VERSION=21.0.0@sha256:916bb21bb87586090dcfa86c2edf7d08cdde2d47e642c4a642fba6c9ee68dbfe # KO
#ARG AWX_VERSION=21.6.0@sha256:4229705340d64123bc7d9639f7dd8a10aa1222961771d28261eecd4d79c49dd8 # KO
#ARG AWX_VERSION=21.11.0@sha256:85c516b99efdc61df1d9fe37cd6f26c635fcd67ca8adb5a5c438c5598a55eda7 # KO

ARG AWX_VERSION=21.11.0@sha256:85c516b99efdc61df1d9fe37cd6f26c635fcd67ca8adb5a5c438c5598a55eda7

FROM remote-docker-quay-io.artifactory.internal.com/ansible/awx:$AWX_VERSION

USER root

RUN curl -kv https://artifactory.internal.com:443/artifactory
```

> The target URL has been obviously changed

### Expected results

The same result as we have when using an image prior to 20 :

`docker build .`

```
Sending build context to Docker daemon   2.56kB
Step 1/4 : ARG AWX_VERSION=19.5.1@sha256:e68ec0ad39f2b8d1a28f65fef9431c244537e7a6791c0b12ffb1ee07a76c421a
Step 2/4 : FROM remote-docker-quay-io.artifactory.internal.com/ansible/awx:$AWX_VERSION
 ---> 8294ea9a34d5
Step 3/4 : USER root
 ---> Using cache
 ---> a71f2d577ed3
Step 4/4 : RUN curl -kv https://artifactory.internal.com:443/artifactory
 ---> Running in 96fb0e9e0d5e
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying XXX.XXX.XXX.XXX...
* TCP_NODELAY set
* Connected to artifactory.internal.com (XXX.XXX.XXX.XXX) port 443 (#0)
```

### Actual results

`docker build .`

```
Sending build context to Docker daemon   2.56kB
Step 1/4 : ARG AWX_VERSION=21.11.0@sha256:85c516b99efdc61df1d9fe37cd6f26c635fcd67ca8adb5a5c438c5598a55eda7
Step 2/4 : FROM remote-docker-quay-io.artifactory.internal.com/ansible/awx:$AWX_VERSION
 ---> 1ff4d926150a
Step 3/4 : USER root
 ---> Running in 50d214f44870
Removing intermediate container 50d214f44870
 ---> 0bd51d5ff58a
Step 4/4 : RUN curl -v https://artifactory.internal.com:443/artifactory
 ---> Running in 133ff075961b
* getaddrinfo() thread failed to start
* Could not resolve host: artifactory.internal.com
* Closing connection 0
curl: (6) getaddrinfo() thread failed to start
The command '/bin/sh -c curl -v https://artifactory.internal.com:443/artifactory' returned a non-zero code: 6
```

### Additional information

The tests have been executed from our GitLab runners as well as on a local machine.
All hosts can reach the target URL.

**Comment by djyasin** [comment]
Hello, this appears to be less of a bug report or feature request and more of a question. Could you please ask this on our mailing list? There may be other community members who have experience with this who may be able to assist you.

See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.

**Comment by mbutton77** [comment]
Hi Lila,

Thanks for the pointer : I must admit that I did not think about the mailing list as I thought it was a internal developer thing.

I will then search through the mailing list history and may start a new thread if I find no matching situations.
And if that is alright, I will still keep this "bug"open to reference it in that potential new thread.

Thanks again !

**Comment by mbutton77** [comment]
To follow up, @kurokobo helped me, via the mailing list, to understand that the problem was due to the Docker/Podman versions I was using. (Docker 18.03 & Podman 2.0.5).
After upgrading to a more recent version of Podman (4+), the problem disappeared.
