### ISSUE TITLE
AWX Community Meeting Agenda - Mar 14 2023

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#13563]
# AWX Office Hours

## Proposed agenda based on topics
* Spud award [1 min]
    * Congrats to @stanislav-zaprudskiy for this months angry spud award for their work on the graceful termination of AWX instances
    *  https://github.com/ansible/awx-operator/pull/1193 and https://github.com/ansible/awx/pull/13445
* [mani3887](https://github.com/mani3887) Talk about scaling and redis cache [7 min]
* [nickjmv](https://github.com/nickjmv) SAML from extra settings discussion [7 min]
* Crunchy Data Presentation [44 min]
* Thanks to contributors and closeout [1 min]
    * @philipsd6 thanks for this nice contribution that allows complex extra var injection https://github.com/ansible/awx/pull/13267
    * @mbutton77 made their first contribution in https://github.com/ansible/awx-operator/pull/1248
    * @ravitejb made their first contribution in https://github.com/ansible/awx-operator/pull/1258
    * @flyinggreenfrog made their first contribution in https://github.com/ansible/awx-operator/pull/1257
    * @adpavlov made their first contribution in https://github.com/ansible/awx/pull/12242
    * @npithonDR made their first contribution in https://github.com/ansible/awx/pull/13541
    * @stanislav-zaprudskiy made their first contribution in https://github.com/ansible/awx/pull/13445
    * @tomsiewert made their first contribution in https://github.com/ansible/awx/pull/13574

## What

After a successful Contributor Summit in October, one of the bits of feedback we got was to host a regular time for the Automation Controller (AWX) Team to be available for your folks in the AWX Community, so we are happy to announce a new regular video meeting.

This kind of feedback loop is vital to the success of AWX and the AWX team wants to make it as easy as possible for you - our community - to get involved.

## Where & When
Our next meeting will be held on Tuesday, Mar 14th, 2023 at [1500 UTC](https://dateful.com/time-zone-converter?t=15:00&tz=UTC)

* [Google Meet](https://meet.google.com/vyk-dfow-cfi)
* Via Phone PIN: 842522378 [Guide](https://support.google.com/meet/answer/9518557)

This meeting is held once a month, on the second Tuesday of the month, at [1500 UTC](https://dateful.com/time-zone-converter?t=15:00&tz=UTC)

## How

Add one topic per comment in this GitHub issue

If you don't have a GitHub account, jump on [#awx:ansible.com](https://matrix.to/#/#awx:ansible.com) on Matrix and we can add the topic for you

## Talk with us

As well as the fortnightly video meeting you can join the Community (inc development team) on Matrix Chat.

* Matrix: [#awx:ansible.com](https://matrix.to/#/#awx:ansible.com) (recomended)
* libera.chat IRC: `#ansible-awx` (If you are already setup on IRC)

The Matrix & IRC channels are bridged, you'll just have a better experience on Matrix

## Links
[AWX YouTube Chanel](https://www.youtube.com/@ansible-awx)
[Previous Meeting](https://github.com/ansible/awx/issues/13431)
[Meeting recording](https://www.youtube.com/watch?v=DuYUE4D8FmI)
[Next Meeting](https://github.com/ansible/awx/issues/13687)

See you soon!

**Comment by mani3887** [comment]
Hi,

I had gone over the videos posted in the channel: Ansible AWX community which are super helpful, which gave me some clarity on how the flow goes within AWX. I had a below clarification questions:

1. We have a requirement to scale close to 1000 jobs in our AKS clusters. We have the capacity to handle the jobs in our clusters(with regard to CPUs and Memory in the underlying VMs). Can you please let me know what other things we need to consider to achieve this scalability? (With regard to Postgres DB configurations, redis configs, etc.). We tried scaling our system with few AWX replicas and we observed that we were able to scale until 150 jobs with 1 AWX deployment(3 replicas), but we were unable to go more than that. Please find the issue I created here: https://github.com/ansible/awx/issues/13657

2. Redis cache - In the videos, it has been mentioned that in-memory redis is primarily used for dumping the logs, dispatcher gets the logs from EE pods, sends it to redis cache, the callback handler gets this from the redis cache and dumps it in the DB. Is the redis cache used for any other functionality? Is this only for the ansible job output logs or it also does the same for the metadata of the job? In our application, we are currently re-directing the Ansible logs(executed on EE pod) to a mounted file share; would the AWX still gather the logs and forward it to dispatcher? we have a solution for  #transferring the logs, but ideally we would want the metadata for the logs as well.

Thanks and Regards,
Mani

**Comment by nickjmv** [comment]
What about topics that didn't get covered yesterday? Do we need to add them once again? If so, I'd like mine added.

A tutorial on how to enable SAML via the extra_settings instead of the GUI.

This would (probably) be a solution for this: https://github.com/ansible/awx/issues/12238

**Comment by TheRealHaoLiu** [comment]
Special guest from [Crunchy data](https://www.crunchydata.com/) to chat about their HA/DR solution for Postgres and how it can be used with AWX

**Comment by TheRealHaoLiu** [comment]
thanks to https://github.com/stanislav-zaprudskiy for his contribution https://github.com/ansible/awx-operator/pull/1193 and https://github.com/ansible/awx/pull/13445 to allow AWX to wait for job to complete before termination of a instance

**Comment by TheRealHaoLiu** [comment]
congratulations to [ravitejb](https://github.com/ravitejb) for the first contribution in AWX 
https://github.com/ansible/awx-operator/pull/1258

**Comment by TheRealHaoLiu** [comment]
congratulations @tomsiewert to for their first contribution to AWX https://github.com/ansible/awx/pull/13574

**Comment by TheRealHaoLiu** [comment]
congratulations to https://github.com/aurel333 first time contributor to awx-operator https://github.com/ansible/awx-operator/pull/1262

**Comment by john-westcott-iv** [comment]
Todays community meeting will be from 1400 UTC and continue to 1530 UTC (30 minute longer than usual) due to another daylight savings time scheduling mishap.

We apologies for any inconvenience, it will be recorded and posted to YouTube as normal incase you miss it.
