### ISSUE TITLE
Execution node constantly switching between 'Ready' and 'Unresponsive' state

### ISSUE THREAD

**Issue by BrillCom** [ansible/awx#13569]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I have successfully deployed an execution node, external to Kubernetes. The node successfully registers and shows as a visible and ready instance within the AWX console. However, I've noticed that the status within the console constantly switches between ready and unresponsive. When is shows unresponsive, the following message is displayed -- "Another cluster node has determined this instance to be unresponsive".

Upon looking into the awx_ee logs, I see the node is receiving multiple updates every minute or so from what I assume is from multiple awx_ee instances, i.e., a connection is made, routing is updated, and then the connection is disconnected (over and over again every minute or two).

Is this a known issue, a bug, or is there some way to prevent the constant switching between awx_ee instances?

### AWX version

21.11.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

Install AWX on Kubernetes with multiple replicas.
Build new VM with prerequisites, external to Kubernetes (not within the cluster).
Create new instance and download and install the bundle.
Verify instance is ready.

### Expected results

Instance should always remain in ready state (rather than randomly showing unresponsive).

### Actual results

Instance constantly bouncing between ready and unresponsive status.

**Comment by fosterseth** [comment]
the heath of the execution node depends on an active and stable connection via Receptor

if you kubectl exec into the awx pod (awx-ee container) you can run

`receptorctl --socket  /var/run/receptor/receptor.sock status`

you'll see information about what nodes are connected under "Connection"

maybe do a `watch` on that command and monitor it manually

do you see that execution node consistently present, or does it seem to go away at times?

**Comment by BrillCom** [comment]
The node seems to always be there (viewing from the status). Unfortunately, watch does not seem to be installed in the awx-ee container and I cannot seem to be able to install it. 

To dig further, I enabled debug log level on awx-ee and I randomly see the following:
     Error locating unit: {{varies}}
     unknown work unit {{varies}}

And also:
     Received unreachable message from {{awx-ee_node}}
     Could not read in control service: timeout: no recent network activity

I tried adjust the maxidleconnectiontimeout: 60s and restarted receptor service, but this did not help. 

UPDATE: The route seems to always stay the same and the network connection is stable.

**Comment by BrillCom** [comment]
SOLVED:
I ultimately burned everything down to start over again. I encountered a few issues along the way that ultimately led me to discovering my previous issue must have been a result of time being out of synch with cloud provider and local resources. Once I fixed that, reinstalled (again), the node appears to be staying in the 'Ready' state.
