### ISSUE TITLE
User accounts marked as Social(SAML logged) cannot set passwords

### ISSUE THREAD

**Issue by huhspunk** [ansible/awx#13575]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

- User accounts marked as Social(SAML logged) cannot set passwords
- I tried changing the password with API Call, but it doesn't work.
- This means there is no way to log in when the SAML authentication system fails.
- Therefore, please improve the function so that the user account logged in with SAML can change the password.

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

User accounts marked as Social(SAML logged) cannot set passwords in USER settings

### Current results

There is no UI to set password. (There is a general account).

### Sugested feature result

This means there is no way to log in when the SAML authentication system fails. Therefore, please improve the function so that the user account logged in with SAML can change the password.

**Comment by rooftopcellist** [comment]
This is working as expected IMO.  SAML becomes your source of truth for authentication of users created via logging in with the SAML integration.  

What you are suggesting would mean that it would be possible for the same user to have two passwords (one set in SAML IdP and the other set in the AWX db).  

As a work-around, you can exec into the awx-task pod and create a super user to log in with if you are the admin of the cluster).  Then you can log in with that user until your SAML is back online.
