### ISSUE TITLE
[Schedules] Project updates (with caching) does not run

### ISSUE THREAD

**Issue by Commifreak** [ansible/awx#13580]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Scheduled project updates does not run (with caching)

### AWX version

21.12.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

minikube

### Modifications

no

### Web browser

Firefox

### Steps to reproduce

I set up scheduling on one project. The project is set to caching for 24 hours. But I wish, to force update it at a schedule and cache it afterwards. So I set up a schedule.

But the schedule passes without any action. There is no job created when the time arrives. The next schedule changes correctly.

I edited the project and disabled caching. That works with scheduling.

### Expected results

Scheduled project updates (with caching) should be force-refreshed

### Actual results

Scheduled project updates (with caching) does not refresh, when the cache is still valid

**Comment by djyasin** [comment]
Hello @Commifreak  we would like to get a little bit more information from you so that we can better assist you.

Did you place the schedule on the job or the project itself?

**Comment by Commifreak** [comment]
On the project.

**Comment by fosterseth** [comment]
note: seems this is working as intended

@Commifreak  what is the reason for having both the scheduled project update and the update on launch (with cache timeout) set? seems choosing one or the other would yield the best results for you

**Comment by Commifreak** [comment]
Im not using both. I was testing some things. Actually I wanted to just used the scheduled project update which isnt working.

you write it is working. I will test it again and met you know

**Comment by Commifreak** [comment]
Tested again:
![grafik](https://user-images.githubusercontent.com/87267/222390705-efbdfa30-81bd-46c1-b767-4fb349912b30.png)

It is working. Maybe fixed within last update.
