### ISSUE TITLE
Credential form disabled save button border is green

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#1359]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Border should be the same color as the background when disabled

##### STEPS TO REPRODUCE

Go to add a credential but don't input any fields so that the save button is disabled due to missing fields.

<img width="1296" alt="screen shot 2018-02-26 at 3 07 29 pm" src="https://user-images.githubusercontent.com/9889020/36692952-aa2f338c-1b07-11e8-9b36-3eafdb6db7a9.png">

**Comment by ryanpetrello** [comment]
Closing due to age and UI rewrite.
