### ISSUE TITLE
AWS credential missing cloud icon on templates list

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#1360]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
We list out credentials on the templates list now and we denote the type of credential with an icon.  It seems like AWS credentials are missing their cloud icon:

<img width="1243" alt="screen shot 2018-02-26 at 3 17 19 pm" src="https://user-images.githubusercontent.com/9889020/36693090-29c7f2e6-1b08-11e8-8f39-d27fc2ffb424.png">

It should look like:

<img width="405" alt="screen shot 2018-02-26 at 3 15 43 pm" src="https://user-images.githubusercontent.com/9889020/36693099-2fa245d6-1b08-11e8-88a9-08c65ed58880.png">

**Comment by ryanpetrello** [comment]
We don't show credentials on the JT list anymore - closing.

**Comment by wenottingham** [comment]
we do, but it appears to be working now
