### ISSUE TITLE
Faild upgrade: Cannot assign "<Role: Role object>": "Organization.member_role" must be a "Role" instance.

### ISSUE THREAD

**Issue by iyurev** [ansible/awx#1363]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### ENVIRONMENT
* AWX version: 1.0.2.75
* AWX install method:  docker on linux
* Ansible version:  2.4.0
* Operating System: CentOS
* Web Browser: Google Chrome 

##### STEPS TO REPRODUCE

Can't upgrade to version  higher  1.0.3.0 from 1.0.2.75 .  
I pull new docker image,  start all containers , but seems  migration  step failed:

```Cannot assign "<Role: Role object>": "Organization.member_role" must be a "Role" instance.``` 
After that instance don't working (always show "Upgrade" banner instead of web UI ) . 

##### EXPECTED RESULTS

Successful upgrade to new version 

##### ACTUAL RESULTS

Faild upgrade

**Comment by matburt** [comment]
If you read the announcement for version 1.0.3 you'll notice that this is covered. Upgrades from 1.0.2 to versions higher than 1.0.3.0 are not supported.
