### ISSUE TITLE
Alt Galaxy Support

### ISSUE THREAD

**Issue by nervo** [ansible/awx#1365]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Please, consider using [Alt Galaxy](https://github.com/gantsign/alt-galaxy) as an ansible-galaxy alternative, as this one is damn' too slow

##### ENVIRONMENT
* AWX version: 1.0.4
* AWX install method: docker on linux

##### STEPS TO REPRODUCE

Use a project with dozens of roles defined in `roles/requirements.yml`

##### EXPECTED RESULTS

Launching a simple playbook should take few seconds.

##### ACTUAL RESULTS

Launching a simple playbook could take more than 20 minutes, just because of ansible-galaxy slowness

##### ADDITIONAL INFORMATION

Please.

**Comment by matburt** [comment]
This is one I don't think we're ever likely to get to, if this is something that you are interested in then you should submit a PR adding support for it.

**Comment by nervo** [comment]
Seems fair :)
What about adding a way to disable roles update in force mode ?

**Comment by wenottingham** [comment]
That may be a more useful parameter, I don't think we'd ever build in support for an optional different mechanism for role updates, though.

**Comment by matburt** [comment]
Yeah agreed, I'm going to close this one out.
