### ISSUE TITLE
Unable to update custom inventory script

### ISSUE THREAD

**Issue by AbbyRH** [ansible/awx#1366]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

When trying to run a custom inventory script i get the follow error: 
`awx-manage inventory_import: error: unrecognized arguments: -e @/tmp/awx_62_6tcS9H/tmphP32xr`

##### ENVIRONMENT
* AWX version: 1.0.4.14
* AWX install method: docker on linux
* Ansible version:  2.4.3.0 
* Operating System: Ubuntu 16.04
* Web Browser: Chrome 64

##### STEPS TO REPRODUCE

- create a custom inventory script
- create or use a credential that has a `extra_vars` injector
- create a inventory that uses the above script as its source with an `extra_vars` injector for its credential
- attempt to sync the inventory

##### EXPECTED RESULTS

inventory is updated based on the output of the inventory script

##### ACTUAL RESULTS

update fails with the following error: 

```
usage: awx-manage inventory_import [-h] [--version] [-v {0,1,2,3}]
                                   [--settings SETTINGS]
                                   [--pythonpath PYTHONPATH] [--traceback]
                                   [--no-color] [--inventory-name n]
                                   [--inventory-id i] [--overwrite]
                                   [--overwrite-vars] [--keep-vars] [--custom]
                                   [--source s] [--enabled-var v]
                                   [--enabled-value v] [--group-filter regex]
                                   [--host-filter regex]
                                   [--exclude-empty-groups]
                                   [--instance-id-var v]
awx-manage inventory_import: error: unrecognized arguments: -e @/tmp/awx_62_6tcS9H/tmphP32xr
```

**Comment by AlanCoding** [comment]
These steps are not sufficient for me to reproduce the error. Syncs happen correctly.

Did you attach a custom credential to your inventory source which provided extra vars? @ryanpetrello what do you think of that theory?

**Comment by ryanpetrello** [comment]
@AlanCoding related: https://github.com/ansible/product-docs/pull/333

**Comment by AbbyRH** [comment]
I'll try and get some better steps to reproduce later on. It was working until the latest version I believe, but its possible I screwed something up somewhere. Will try to re-create on a fresh install

**Comment by wenottingham** [comment]
@AbbyRH no, it's a known issue. Don't attach a custom credential with an `extra_vars` injector to an inventory source... it won't work. (And wouldn't do anything for the inventory update even if it did work.)

**Comment by AbbyRH** [comment]
Ahh, I'd managed to change the credential for my inventory source from from an `env` injector to `extra_vars`. I'd been copying the syntax to another credential and must have got mixed up. Thats why it was working before. 

Sorry for wasting everyone's time.

**Comment by ryanpetrello** [comment]
@AbbyRH to be fair, this _is_ a bug - thanks for reporting it.  I'm working on a fix at the moment.

**Comment by AbbyRH** [comment]
I've updated my initial issue comment to include using a `extra_vars` injector credential as part of the steps to reproduce so the issue makes sense without having to read through the commens
