### ISSUE TITLE
Activity Stream for application shows client_secret

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#1367]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Activity stream for Application model leaks secret

##### ENVIRONMENT
* AWX version: 1.0.4-66
* AWX install method: docker for mac
* Ansible version:  N/A
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Create an application, view `/api/v2/applications/1/activity_stream/`

##### EXPECTED RESULTS

No secrets.

##### ACTUAL RESULTS

```
            "changes": {
                "updated": "2018-02-27 14:15:50.398779+00:00",
                "redirect_uris": "",
                "description": "",
                "created": "2018-02-27 14:15:50.398752+00:00",
                "logo_data": "",
                "client_type": "public",
                "user": "admin",
                "client_id": "TLmqoGkOxTGq4E7rF8gGmmFMK6f76tI8AKynGz3S",
                "client_secret": "ufF43Ea72Bt1J7f5ONjHlCwhH39j1jKpUjHMg9Z0h65oNa5t6nwLDOFuERy6AkXkul7vWw8XfsteLJtSyhzang8MsX33iEJijfYeu4DQnU3R4IYnjjif68AQOVBPPkEF",
                "skip_authorization": false,
                "authorization_grant_type": "password",
                "id": "1",
                "name": "alans application 日本語"
            },
```

`client_secret` shown in the data.

**Comment by rooftopcellist** [comment]
@AlanCoding and I talked in person.  I will remove this from the activity stream.  After some digging, it looks like django-auth-toolkit does NOT hash/encrypt the client_secret.

**Comment by rooftopcellist** [comment]
This was fixed with https://github.com/ansible/awx/pull/1427
