### ISSUE TITLE
Constructed Inventory- Ace Editor- JSON => Yaml conversion not functioning on variable edit

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#13675]
Testing performed on branch feature_constructed-inventory

When a user edits the variables in the ace editor of a constructed inventory, the json => yaml conversion stops functioning properly.

To recreate:

Create a constructed inventory with valid source_vars in the ace editor. Enter the variables like this and save:
`{
  "plugin": "constructed",
  "groups": {
    "shutdown_in_product_dev": "state | default(\"running\") == \"shutdown\" and account_alias == \"product_dev\""
  }
}`

Edit the constructed inventory. In the source_vars variable editor input, make the following changes and save:
`{
  "plugin": "blah",
  "strict": True,
  "groups": {
    "shutdown_in_product_dev": "state | default(\"running\") == \"shutdown\" and account_alias == \"product_dev\""
  }
}`

After saving these changes, click the JSON/YAML buttons- you'll notice that the code stays in JSON format.

![image](https://user-images.githubusercontent.com/63685497/224367118-ca1c97fd-7629-475e-87f6-df995cc14b97.png)

![image](https://user-images.githubusercontent.com/63685497/224367165-70a08b8e-3806-4694-b07e-0c2fd907763c.png)

**Comment by marshmalien** [comment]
https://user-images.githubusercontent.com/15881645/225400796-3d4a7ade-8130-44b3-bf52-2b9e626922d9.mov


Seeing this issue on devel too. 
1. Find a resource with existing vars
2. Go to edit form
3. Don't edit/modify the vars value
4. Toggle YAML/JSON mode button
5. See bug
