### ISSUE TITLE
AWX Community Meeting Agenda - Apr 11 2023

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#13687]
# AWX Office Hours

## Proposed agenda based on topics
* Web Task Split @thedoubl3j   5 min
* Constructed Inventory @AlanCoding 10 min
* UI Next @TheRealHaoLiu 5 min
* Infra Config as Code @sean-m-sullivan 20min 
* https://github.com/ansible/awx/pull/13507 @tanganellilore @CMPluto @AlanCoding 15min
* Thanks to new contributors & closing 5min

## What

After a successful Contributor Summit in October, one of the bits of feedback we got was to host a regular time for the Automation Controller (AWX) Team to be available for your folks in the AWX Community, so we are happy to announce a new regular video meeting.

This kind of feedback loop is vital to the success of AWX and the AWX team wants to make it as easy as possible for you - our community - to get involved.

## Where & When
Our next meeting will be held on Tuesday, Apr 11th, 2023 at [1500 UTC](https://dateful.com/time-zone-converter?t=15:00&tz=UTC)

* [Google Meet](https://meet.google.com/vyk-dfow-cfi)
* Via Phone PIN: 842522378 [Guide](https://support.google.com/meet/answer/9518557)

This meeting is held once a month, on the second Tuesday of the month, at [1500 UTC](https://dateful.com/time-zone-converter?t=15:00&tz=UTC)

## How

Add one topic per comment in this GitHub issue

If you don't have a GitHub account, jump on [#awx:ansible.com](https://matrix.to/#/#awx:ansible.com) on Matrix and we can add the topic for you

## Talk with us

As well as the fortnightly video meeting you can join the Community (inc development team) on Matrix Chat.

* Matrix: [#awx:ansible.com](https://matrix.to/#/#awx:ansible.com) (recomended)
* libera.chat IRC: `#ansible-awx` (If you are already setup on IRC)

The Matrix & IRC channels are bridged, you'll just have a better experience on Matrix

## Links
[AWX YouTube Chanel](https://www.youtube.com/@ansible-awx)
[Previous Meeting](https://github.com/ansible/awx/issues/13563)
[Meeting recording](https://youtu.be/a75Kv8CN_Lg)
[Next Meeting](https://github.com/ansible/awx/issues/13836)

See you soon!

**Comment by sean-m-sullivan** [comment]
The [Infra Configuration as Code Team](https://galaxy.ansible.com/infra/) will do a presentation of how to use their collections.

**Comment by TheRealHaoLiu** [comment]
Introducing the new AWX UI https://github.com/ansible/awx/pull/13660

**Comment by CMPluto** [comment]
please include isssue : https://github.com/ansible/awx/pull/13507
**_[-] awx.conf.settings Database settings are not available, using defaults. error: connection already closed\n","stream":"stderr"_**

**Comment by l3acon** [comment]
Discuss #13725, an`exist` state to credential module and perhaps other modules.

**Comment by tanganellilore** [comment]
team, can we spent 2 minutes also on this?

Issues: #13756 / #13812
PR that fix it: #13766

Is related blank UI for users that not have a Browser language not implemented on AWX (ex Italian or German).
