### ISSUE TITLE
Allow for specifying a Kubernetes Service Account in automation-jobs 

### ISSUE THREAD

**Issue by satellite-no** [ansible/awx#13689]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

Allow the end user to specific a different service account in the `automation-job-` pods that are run in Kubernetes.  This could be a 1 size fits all settings thats in the settings > jobs menu or if possible for increased funcunality and security allow different Service Accounts to be defined per template. 

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Steps to reproduce

Create a new job and watch the pod get created with the name `automation-job-`

### Current results

The pod created as `automation-job-` has the "default" service account attached to it. 

### Sugested feature result

Allow the end user to specific a different service account in the `automation-job-` pods that are run in Kubernetes.

**Comment by satellite-no** [comment]
NVM, just stumbled on to this is possible via the instance groups.  Found this by reading deeper into https://github.com/ansible/awx/blob/ac6a82eee41feb041ff3e4d16459d4b1a774175f/awx/main/scheduler/kubernetes.py.  Forgive me and care one the great work!

**Comment by alanjose10** [comment]
Hi @satellite-no, I am trying to accomplish the same thing. Can you please explain how this is possible via instance groups? Apologies since i am new to kubernetes.

**Comment by K3N44N** [comment]
Thanks for the clues, just dropping the method here in case someone else needs it in the future.

Go to **Instance Groups**, under the **Administration** tab.

Then click **Add** > **Add container group**.

Check the **Customize pod specification** option.

Here you can override the service account in under the **spec property** in YAML/JSON.

Then when creating/editing a job template, add the created container group under the **Instance Groups** thing.

As a side note, you can modify other useful properties such as pod sizing and namespace here :)

Thanks again!

**Comment by ol-minhle** [comment]
Do we have any ways to store this configuration as code instead of going via UI? For example a property in Helm values or sthing like that. I've gone through the Helm doc but nothing mentioned
