### ISSUE TITLE
The web dashboard couldn't open 

### ISSUE THREAD

**Issue by yuanyuefeng** [ansible/awx#13691]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I installed awx v19.5.1 through docker method. It looks like installation is ok . And container s run as below:
CONTAINER ID  IMAGE                            COMMAND               CREATED       STATUS             PORTS                                                                                                                                                                             NAMES
8ca214c6587e  [docker.io/library/redis:latest](http://docker.io/library/redis:latest)   /usr/local/etc/re...  20 hours ago  Up 28 minutes ago                                                                                                                                                                                    tools_redis_1
d2449b19f0d8  [docker.io/library/postgres:12](http://docker.io/library/postgres:12)    postgres              20 hours ago  Up 28 minutes ago                                                                                                                                                                                    tools_postgres_1
4c1ec7e29e5c  [quay.io/awx/awx_devel:19.5.1](http://quay.io/awx/awx_devel:19.5.1)     launch_awx.sh         20 hours ago  Up 28 minutes ago  0.0.0.0:2222->2222/tcp, 0.0.0.0:6899->6899/tcp, 0.0.0.0:7899-7999->7899-7999/tcp, 0.0.0.0:8013->8013/tcp, 0.0.0.0:8043->8043/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:8888->8888/tcp  tools_awx_1
4177b85bcdff  [quay.io/ansible/receptor:v1.2.1](http://quay.io/ansible/receptor:v1.2.1)  receptor --config...  20 hours ago  Up 28 minutes ago  0.0.0.0:5555->5555/tcp                                                                                                                                                            tools_receptor_hop
a33176dc2026  [quay.io/awx/awx_devel:19.5.1](http://quay.io/awx/awx_devel:19.5.1)     receptor --config...  20 hours ago  Up 28 minutes ago                                                                                                                                                                                    tools_receptor_2
48b271638e6e  [quay.io/awx/awx_devel:19.5.1](http://quay.io/awx/awx_devel:19.5.1)     receptor --config...  20 hours ago  Up 28 minutes ago                                                                                                                                                                                    tools_receptor_1

And run command (successfully):
$ docker exec tools_awx_1 make clean-ui ui-devel

But the dashboard couldn't open (blank), i did check the log of tools_awx_1. Found below errors :
awx-receptor stdout | WARNING 2023/03/15 04:44:30 Could not read in control service: read unix /var/run/awx-receptor/receptor.sock->@: use of closed network connection
awx-receptor stdout | WARNING 2023/03/15 04:44:30 Could not close connection: close unix /var/run/awx-receptor/receptor.sock->@: use of closed network connection".

awx-uwsgi stdout | 10.127.96.82 GET / - HTTP/1.1 200   -- shows that return 200 ok 
The dashboard always show blank and not prompt login page.  

### AWX version

19.5.1

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.9.27

### Operating system

Oracle Linux 8 

### Web browser

Chrome

### Steps to reproduce

$ make  docker-compose-build
$ make docker-compose
$ docker exec tools_awx_1 make clean-ui ui-devel

### Expected results

Expect to access web and start to login

### Actual results

The actual docker-compose.yml  as below:
---
version: '2.1'
services:
        # Primary AWX Development Container
  awx_1:
    user: "0"
    image: "quay.io/awx/awx_devel:19.5.1"
    container_name: tools_awx_1
    hostname: awx_1
    command: launch_awx.sh
    environment:
      OS: "linux"
      SDB_HOST: 0.0.0.0
      SDB_PORT: 7899
      AWX_GROUP_QUEUES: tower
      MAIN_NODE_TYPE: "${MAIN_NODE_TYPE:-hybrid}"
      RECEPTORCTL_SOCKET: /var/run/awx-receptor/receptor.sock
      CONTROL_PLANE_NODE_COUNT: 1
      EXECUTION_NODE_COUNT: 2
      RUN_MIGRATIONS: 1
    depends_on:
      - postgres
      - redis_1
    networks:
      - awx_default
    working_dir: "/awx_devel"
    volumes:
      - "../../../:/awx_devel"
      - "../../docker-compose/supervisor.conf:/etc/supervisord.conf"
      - "../../docker-compose/_sources/database.py:/etc/tower/conf.d/database.py"
      - "../../docker-compose/_sources/websocket_secret.py:/etc/tower/conf.d/websocket_secret.py"
      - "../../docker-compose/_sources/local_settings.py:/etc/tower/conf.d/local_settings.py"
      - "../../docker-compose/_sources/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "../../docker-compose/_sources/receptor/receptor-awx-1.conf:/etc/receptor/receptor.conf"
      - "../../docker-compose/_sources/receptor/work_public_key.pem:/etc/receptor/work_public_key.pem"
      - "../../docker-compose/_sources/receptor/work_private_key.pem:/etc/receptor/work_private_key.pem"
      # - "../../docker-compose/_sources/certs:/etc/receptor/certs"  # TODO: optionally generate certs
      - "/sys/fs/cgroup:/sys/fs/cgroup"
      - "~/.kube/config:/var/lib/awx/.kube/config"
      - "redis_socket_1:/var/run/redis/:rw"
    privileged: true
    tty: true
    ports:
      - "7899-7999:7899-7999"  # sdb-listen
      - "6899:6899"
      - "8080:8080"  # unused but mapped for debugging
      - "8888:8888"  # jupyter notebook
      - "8013:8013"  # http
      - "8043:8043"  # https
      - "2222:2222"  # receptor foo node
  redis_1:
    image: redis:latest
    networks:
      - awx_default
    container_name: tools_redis_1
    volumes:
      - "../../redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "redis_socket_1:/var/run/redis/:rw"
    entrypoint: ["redis-server"]
    command: ["/usr/local/etc/redis/redis.conf"]
  # A useful container that simply passes through log messages to the console
  # helpful for testing awx/tower logging
  # logstash:
  #   build:
  #     context: ./docker-compose
  #     dockerfile: Dockerfile-logstash
  postgres:
    image: postgres:12
    container_name: tools_postgres_1
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: awx
      POSTGRES_DB: awx
      POSTGRES_PASSWORD: KkjRxHIqHonEdhybonFU
    networks:
      - awx_default
    volumes:
      - "awx_db:/var/lib/postgresql/data"
  receptor-hop:
    image: quay.io/ansible/receptor:v1.2.1
    user: root
    container_name: tools_receptor_hop
    hostname: receptor-hop
    command: 'receptor --config /etc/receptor/receptor.conf'
    depends_on:
      - awx_1
    networks:
      - awx_default
    ports:
      - "5555:5555"
    volumes:
      - "../../docker-compose/_sources/receptor/receptor-hop.conf:/etc/receptor/receptor.conf"
  receptor-1:
    image: "quay.io/awx/awx_devel:19.5.1"
    user: "0"
    container_name: tools_receptor_1
    hostname: receptor-1
    command: 'receptor --config /etc/receptor/receptor.conf'
    environment:
      RECEPTORCTL_SOCKET: /var/run/awx-receptor/receptor.sock
    depends_on:
      - receptor-hop
    networks:
      - awx_default
    volumes:
      - "../../docker-compose/_sources/receptor/receptor-worker-1.conf:/etc/receptor/receptor.conf"
      - "/sys/fs/cgroup:/sys/fs/cgroup"
      - "../../docker-compose/_sources/receptor/work_public_key.pem:/etc/receptor/work_public_key.pem"
    privileged: true
  receptor-2:
    image: "quay.io/awx/awx_devel:19.5.1"
    user: "0"
    container_name: tools_receptor_2
    hostname: receptor-2
    command: 'receptor --config /etc/receptor/receptor.conf'
    environment:
      RECEPTORCTL_SOCKET: /var/run/awx-receptor/receptor.sock
    depends_on:
      - receptor-hop
    networks:
      - awx_default
    volumes:
      - "../../docker-compose/_sources/receptor/receptor-worker-2.conf:/etc/receptor/receptor.conf"
      - "/sys/fs/cgroup:/sys/fs/cgroup"
      - "../../docker-compose/_sources/receptor/work_public_key.pem:/etc/receptor/work_public_key.pem"
    privileged: true

volumes:
  awx_db:
    name: tools_awx_db
  redis_socket_1:
    name: tools_redis_socket_1
networks:
  awx_default:

**Comment by akus062381** [comment]
Hi @ultramanyuan,
This issue pertains to an older version of AWX. Try upgrading to the latest version and let us know if that resolves your issue.
You may also opt to reach out to our mailing list. See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.
