### ISSUE TITLE
AWX not sending workflow events to Elastic

### ISSUE THREAD

**Issue by anasaizg** [ansible/awx#13697]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

We have one of our AWX deployments configured to send logs to Elastic. Some days ago we observed it wasn't sending workflow events. This has been happening since we installed it a couple months ago. If we try to filter for a field with "workflow" word in it, there is nothing to show:

![image](https://user-images.githubusercontent.com/57350196/225375010-851c88ea-daed-4785-8aee-f76df81b5517.png)

However, in another AWX deployment we have (with same parameters configured), we can see some workflow-related available fields, so there are such events registered:

![image](https://user-images.githubusercontent.com/57350196/225375205-0172182b-c752-42c5-a147-7a2f4cb2119f.png)

Moreover, I have detected that today there is not a single event arriving. If we filter in AWX, for example, the jobs from the last 4 hours, we have quite of them:

![image](https://user-images.githubusercontent.com/57350196/225375664-28fa0714-2bdc-4547-9cdd-f2044e3d3aa6.png)

But nothing is shown in Elastic:

![image](https://user-images.githubusercontent.com/57350196/225375801-e0112e82-44dd-418c-8d66-981471886825.png)

Pods have been up with no changes since 6 days ago:

![image](https://user-images.githubusercontent.com/57350196/225376368-7ca8ed56-5f64-46d7-8efa-4ef31b9c4b7a.png)

As I said, there is another environment configured the same and it appears to be sending the logs correctly. Is there anything or anywhere else we should check?

Thanks

### AWX version

21.13.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

Install AWX 21.13.0 and configure log sending with logstash method

### Expected results

Logs of all events are received by Elastic

### Actual results

At first, no workflow-related events were received. Today, no event at all is received.

**Comment by anasaizg** [comment]
Just a little update on this, I have been launching some tests and I have seen we receive an event when the workflow is modified, but we don't receive anything when it is launched.

I have also seen some messages about rsyslogd in awx-task logs, such as:

```
ERROR rsyslogd was unresponsive: FileNotFoundError: [Errno 2] No such file or directory
ERROR rsyslogd was unresponsive: OSError: [Errno 90] Message too long
ERROR rsyslogd was unresponsive: BlockingIOError: [Errno 11] Resource temporarily unavailable
```

They don't necessarily appear at the time the workflows are launched, but I think they are suspicious nonetheless.

**Comment by anasaizg** [comment]
Ok, nevermind, after some more testing the monitoring team realized it was Elastic who was discarding the events...

**Comment by gundalow** [comment]
Hi @anasaizg 
I know this is an old bug report, though I'm interested what the misconfiguration was?
