### ISSUE TITLE
Use persistent storage for redis db dump in /data/dump.rdp

### ISSUE THREAD

**Issue by A-Kumpf** [ansible/awx#13729]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

Creating persistent storage for the redis db dump in /data/dump.rdp.

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

Creating persistent storage for the redis db dump dump.rdp would be helpful, as there's the ldap configuration stored.
After deleting the corresp. container the ldap creds are lost and nedd to be set again.

### Current results

LDAP creds are lost after deleting the awx deployment

### Sugested feature result

Redis dump is in persistent storage

**Comment by djyasin** [comment]
Hello @A-Kumpf,
The LDAP configuration should be stored as secrets in the database and should not be lost if the AWX deployment is deleted as long as the Postgres PVC  is left intact. 

Could you please provide a bit more context around the behavior you are seeing? Any logs or error messages that you are encountering would be extremely helpful.

**Comment by A-Kumpf** [comment]
> Hello @A-Kumpf, The LDAP configuration should be stored as secrets in the database and should not be lost if the AWX deployment is deleted as long as the Postgres PVC is left intact.
> 
> Could you please provide a bit more context around the behavior you are seeing? Any logs or error messages that you are encountering would be extremely helpful.

Hoi djyasin
Is that a fact, secrets are stored in the postgresql db and even if the db is unmanaged and external?
If that's the case, I won't need the redis to be dumped in a PVC.
Regards
Andi

**Comment by djyasin** [comment]
Thank you for your reply. We are going to go ahead and close this issue. Should you encounter any additional trouble, please open a new issue. Thank you for your time!
