### ISSUE TITLE
Vault Dynamic AWS credentials

### ISSUE THREAD

**Issue by lee5i3** [ansible/awx#13739]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

We are using Dynamic AWS credentials in Vault for generating temporary access keys

However, when I'm mapping the aws credentials in AWX, its creating 2 separate users for access key and secret key

### AWX version

21.13.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Operating system

Ubuntu

### Web browser

Chrome

### Steps to reproduce

In Vault, we have a AWS backend secret called "aws", we have a role inside aws called "ansible" with specific IAM permissions

In AWX, we have 2 credentials

**HashiCorp Vault Secret Lookup**
Pointed to my Vault server, using AppRole authentication
I have tested and it creates a new IAM user as expected

**Amazon Web Service**
Access Key is mapped to
```
{
  "auth_path": "approle",
  "secret_key": "access_key",
  "secret_path": "creds/ansible",
  "secret_backend": "aws",
  "secret_version": ""
}
```
Secret Key is mapped to
```
{
  "auth_path": "approle",
  "secret_key": "secret_key",
  "secret_path": "creds/ansible",
  "secret_backend": "aws",
  "secret_version": ""
}
```

### Expected results

I would expect this to create a single user and read both access key and secret key from the same user

### Actual results

Created 2 separate IAM users and unable to access AWS, as it appears to be reading the access key from first user and secret key from second user

**Comment by djyasin** [comment]
Hello @lee5i3,
We are so very sorry, but what you are attempting to do is not currently possible. At this time you cannot use AWS cloud credentials in the automation controller when relying on IAM roles to access the AWS API.

Here is the supporting documentation: (https://docs.ansible.com/automation-controller/latest/html/userguide/credentials.html#amazon-web-services)

Please let us know if you are able to resolve this issue!

**Comment by lee5i3** [comment]
Is there another option to get this working?

Only option we see is to create a schedule job to generate AWS credentials and copy them to another secret which can then be mapped to a secret

Is it possible to create a custom credential for Vault? I know we can create credential types but as it would use Hashicorp Vault Secret Lookup, it still only allows for 1 secret value at a time, we would need to create a new Hashicorp Vault Secret credential that would allow for both values returned

What we are wanting to call is inside Vault "aws/creds/ansible" which returns both access_key and secret_key
