### ISSUE TITLE
AWX Collection - Inventory module doesnt allow to create constructed inventory

### ISSUE THREAD

**Issue by CFSNM** [ansible/awx#13781]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When using the inventory module from the AWX Collection, trying to create a constructed inventory using 2 input inventories is failing.

### AWX version

devel

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Ansible version

2.15

### Operating system

RHEL

### Steps to reproduce

Passing these parameters to the inventory module:
```
'module_args': {'name': 'MaximumCheek�', 'description': 'hello world', 'organization': 'Organization - LieComputerꬒ', 'kind': 'constructed', 'input_inventories': ['Inventory - DepressionCoupleᙘ', 'Inventory - SleepSurround�']
```

The list of input inventories are 2 inventories which have been created, the same for the organization

### Expected results

The constructed inventory should be created correctly.

### Actual results

Getting this error message:
The requested object could not be found at /api/v2/constructed_inventories/33/input_inventories/.

**Comment by relrod** [comment]
Found this same issue last night.

Refs #13779 for a really hacky solution, but I don't think that's the right way.

@AlanCoding ideas?

**Comment by relrod** [comment]
The break is https://github.com/ansible/awx/pull/13730

**Comment by AlanCoding** [comment]
I don't think it would disrupt much to point the url link back to `/api/v2/inventories/id/` and then add an additional link for `/api/v2/constructed_inventories/id/`, for informational purposes. But @mabashian was hitting a similar issue with the UI for some reason, and we should get a general consensus about what direction we want to go here.

**Comment by Jaapis** [comment]
Tested and it is working correctly as expected.
