### ISSUE TITLE
awx exported SSO user is not imported back as SSO user

### ISSUE THREAD

**Issue by ArtsiomMusin** [ansible/awx#13798]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When an SSO user is exported, it cannot be imported back and it seems it's imported as a local user by asking for a password

### AWX version

Ansible Automation Platform Controller 4.2.1

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Installation method

openshift

### Modifications

no

### Ansible version

n/a

### Operating system

n/a

### Web browser

Chrome

### Steps to reproduce

After exporting an SSO user, I got this json:
```
{
     "users": [
          {
               "username": "user@com",
               "first_name": "User",
               "last_name": "ABC",
               "email": "user@com",
               "is_superuser": true,
               "is_system_auditor": true,
               "related": {
                    "roles": [...]
               },
               "natural_key": {
                    "username": "user@com",
                    "type": "user"
               }
          }
     ]
}
```

after importing this user back to the same instance when the user doesn't exist, I got:
> /api/v2/users/ "user@com": Bad Request (400) received - {'password': ['This password is too short. It must contain at least 15 characters.', 'This password is too common.']}.

### Expected results

SSO user could be imported. Or maybe it's not supported?

### Actual results

SSO user is not imported back to the instance

**Comment by fosterseth** [comment]
currently this is not supported. Right now users will just need to log in via SSO to create the accounts in AWX

**Comment by ArtsiomMusin** [comment]
@fosterseth ok thanks for this information. I think we can close this issue
