### ISSUE TITLE
null value in column "is_bulk_job" of relation "main_workflowjob" violates not-null constraint DETAIL: Failing row contains

### ISSUE THREAD

**Issue by ewertonhm** [ansible/awx#13810]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

After upgrading from 21.11.0 to 21.13.0, on launching workflows we are getting the following error:

POST api/v2/workflow_job_templates/186/launch/ 400
null value in column "is_bulk_job" of relation "main_workflowjob" violates not-null constraint DETAIL: Failing row contains (15330, {"hostnames": "VSRVDEVCHECK01.havan.corp"}, 186, {}, f, f, null, {}, 55, null, , , null).

### AWX version

21.13.0

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Web browser

Chrome, Edge

### Steps to reproduce

Create an workflow with survey on 21.11.0 or early
upgrade to 21.13.0, try to run it

### Expected results

expected the workflow to run

### Actual results

workflow retun an error and don't start

**Comment by ewertonhm** [comment]
can't replicate the problem, seens some problem with our deployment.

**Comment by kdelee** [comment]
may have been some issue with updating code w/o running migrations
