### ISSUE TITLE
Demo Project Failed when AWX Hosted on a Raspberry PI 4

### ISSUE THREAD

**Issue by apcameron** [ansible/awx#13811]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

The installation is successful and The GUI works fine but Deployments fail.

### AWX version

Latest Development Image

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

ansible [core 2.14.4]

### Operating system

22.04.2 LTS (Jammy Jellyfish)

### Web browser

Firefox

### Steps to reproduce

Install on a AWX on a Raspberry PI 4 using the Docker instructions
Run the Demo Project

### Expected results

The Demo Project runs successfully

### Actual results

WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers 
WARN[0682] image platform (linux/amd64) does not match the expected platform (linux/arm64) 
{"msg":"exec container process `/usr/local/bin/entrypoint`: Exec format error","level":"error","time":"2023-04-06T14:56:13.036171Z"}

**Comment by AlanCoding** [comment]
Well this is about the furthest thing from supported imaginable, but I think it would be cool if you did it! It's not that podman can't install on Raspberry Pi, it calls it out right here:

https://podman.io/getting-started/installation

But if you're doing that, you're not in the CentOS type ecosystem, so you're going way off the rails. This wouldn't be a problem if docker-compose just ran containers, but it runs _containers inside of containers_. You can see how podman recommends you install podman on your Pi, which is the advice for a general debian system:

https://podman.io/getting-started/installation#debian

But inside of the awx_devel container, it installs this way:

https://github.com/ansible/awx/blob/f62bf6a4c37ef30ede0b2effd4223c43ad313caa/tools/ansible/roles/dockerfile/templates/Dockerfile.j2#L191

So by having the base OS being something different, you are well into uncharted territory. If you don't turn around at this point, your next step may be to adjust the Dockerfile to work for a debian system, and build your own custom awx_devel image.

**Comment by apcameron** [comment]
I reverted back to AWX version 17.1.0 and installed it in Docker on my Raspberry PI 4
