### ISSUE TITLE
Unable to edit files in AFS mount path using ansible code (win_lineinfile module) from windows VM

### ISSUE THREAD

**Issue by parthadas-1986** [ansible/awx#13830]
##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - API 
 - Collection
 - Other

##### SUMMARY
The Azure File Share is successfully mounted on the Windows VM (Windows Server 2019 Datacenter), and required permissions are added as per Microsoft document. But whenever we are trying to update any file with in the share path using ansible code(win_lineinfile), we are getting "File path does not exists" error. But in the same VM we are ale to edit file in other physical  disk.  Although we are able manually update file in AFS path, only via ansible it is not working. Please note, We are running the ansible code from Control node (i.e. A Linux vm in same vnet and same region)

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: operator, developer environment
* AWX deployment target: openshift, kubernetes, minikube
* Operating System:
* Web Browser:

**Comment by Zokormazo** [comment]
Hello @parthadas-1986 this sounds like an issue with `community.windows` module and not with awx itself. would you mind to open the issue [in their tracker](https://github.com/ansible-collections/community.windows)?

Thanks

**Comment by Zokormazo** [comment]
Oh, found you already made it: https://github.com/ansible-collections/community.windows/issues/507 . Closing this one then
