### ISSUE TITLE
AWX Community Meeting Agenda - May 9 2023

### ISSUE THREAD

**Issue by djyasin** [ansible/awx#13836]
# AWX Office Hours

## Proposed agenda based on topics
* Upcoming work items:
  * Hop Node @fosterseth @tanganellilore 
  * Resilience improvement @relrod 
  * Django migration status @john-westcott-iv 
* Proposed ideas:
  * Community integration tests @AlanCoding 
* Spud award @TheRealHaoLiu 
  * @tanganellilore - DB connectivity help and Hop Node UI #13507
* Contribution/environment announcement by @thedoubl3j 
* Open question time as permitted

## What

After a successful Contributor Summit in October, one of the bits of feedback we got was to host a regular time for the Automation Controller (AWX) Team to be available for your folks in the AWX Community, so we are happy to announce a new regular video meeting.

This kind of feedback loop is vital to the success of AWX and the AWX team wants to make it as easy as possible for you - our community - to get involved.

## Where & When
Our next meeting will be held on Tuesday, May 9th, 2023 at [1500 UTC](https://dateful.com/time-zone-converter?t=15:00&tz=UTC)

* [Google Meet](https://meet.google.com/vyk-dfow-cfi)
* Via Phone PIN: 842522378 [Guide](https://support.google.com/meet/answer/9518557)

This meeting is held once a month, on the second Tuesday of the month, at [1500 UTC](https://dateful.com/time-zone-converter?t=15:00&tz=UTC)

## How

Add one topic per comment in this GitHub issue

If you don't have a GitHub account, jump on [#awx:ansible.com](https://matrix.to/#/#awx:ansible.com) on Matrix and we can add the topic for you

## Talk with us

As well as the fortnightly video meeting you can join the Community (inc development team) on Matrix Chat.

* Matrix: [#awx:ansible.com](https://matrix.to/#/#awx:ansible.com) (recomended)
* libera.chat IRC: `#ansible-awx` (If you are already setup on IRC)

The Matrix & IRC channels are bridged, you'll just have a better experience on Matrix

## Links
[AWX YouTube Chanel](https://www.youtube.com/@ansible-awx)
[Previous Meeting](https://github.com/ansible/awx/issues/13687)
[Meeting recording](https://youtu.be/Nr57-VHTBaQ)
[Next Meeting](https://github.com/ansible/awx/issues/14016)

See you soon!

**Comment by TheRealHaoLiu** [comment]
let's talk about some of the efforts that the team and community is working on 
- hop node @fosterseth 
- resilience improvement

**Comment by AlanCoding** [comment]
I want to share a proposal to add integration testing of external services as a part of our github checks. I have a draft on my fork here:

https://github.com/AlanCoding/awx/pull/81

The use cases I have in mind are

1. SSO
2. Credential Plugins

Proposed design is to run `py.test` on the base Ubuntu VM running the checks, which will spin up an AWX container for the duration of the test session, and then bring up-and-down other containers for testing against. It's not hard to develop an initial list of what we could use, just look at our [docker-compose.yml](https://github.com/ansible/awx/blob/devel/tools/docker-compose/ansible/roles/sources/templates/docker-compose.yml.j2) file which already has many of these integrations in it and the public image to get them from, like `splunk/splunk:latest`, `dchidell/docker-tacacs`, `bitnami/openldap:2`, `quay.io/keycloak/keycloak:15.0.2`

The draft I has do TACACS Plus and we have a pretty good path forward to add RADIUS auth. But the bigger benefit I see is integrating with recently-active work from the community like CyberArc (ping @infamousjoeg) or Thycotic (ping @vician). I think this could go a long way to improving our speed of adoption of these contributions.

**Comment by infamousjoeg** [comment]
@AlanCoding,

How can I help test this against one of our credential plugins?

**Comment by AlanCoding** [comment]
Something like a minimal set of instructions for (I assume) `cyberark/conjur` such that it could be used with the credential plugin. I realize that it may have other container dependencies, or may need a config mounted, or we may need to make requests to it once it starts up. For now, I'm still thinking having we can have the test do those things.

**Comment by vician** [comment]
@AlanCoding I think better testing of credential plugins is a great idea. But I have no idea how to do that when Delina Secret Server (Thycotic) is based on Windows platform, I think.

**Comment by sean-m-sullivan** [comment]
Though it would be a good discussion of this issue about enforced state for the awx collection modules
#13927 
with the example here
#13960
