### ISSUE TITLE
add pip install pysphere to dockerfile.j2 template

### ISSUE THREAD

**Issue by akcrisp** [ansible/awx#1384]
##### ISSUE TYPE
  - Feature Idea

##### COMPONENT NAME
 - Installer

##### SUMMARY
Add pip install pysphere to docker.j2 template file 

Required for ansible modules - 
vsphere_guest
vsphere_copy

##### ENVIRONMENT
* AWX version: 1.1.173
* AWX install method: docker on linux
* Ansible version:  2.4.3.0-1
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

trying to use vmware module fails unless pypshere present 

##### EXPECTED RESULTS

able to deploy vmware guest

##### ACTUAL RESULTS

fails 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "pysphere module required"}

**Comment by matburt** [comment]
We include psphere and pyvmomi which support the newer ansible vmware modules. We will not be adding pysphere whose development is no longer continuing.

**Comment by akcrisp** [comment]
@matburt problem is that the vmware_guest ansible module does not support the cdrom, where as the vsphere_guest (which requires pypshere) does. I'll email the authors of the vmware_guest and see if there are plans to add support.
