### ISSUE TITLE
Browser content-language "de" bricks AWX webpage

### ISSUE THREAD

**Issue by Kardi5** [ansible/awx#13865]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When running a browser which content language (i.e. Settings=>Language) is German (de) the AWX webpage fails to load (empty white page with error in console):
![grafik](https://user-images.githubusercontent.com/15264610/232457375-2b585b9a-a2d3-4d14-ad17-092485afce1f.png)

The same page loads fine when using English (en) language.

### AWX version

22.0.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

n/a

### Operating system

n/a

### Web browser

Chrome

### Steps to reproduce

1. Set own browser language to German, i.e. set it to the top most language (eg. for Edge see below) 
![grafik](https://user-images.githubusercontent.com/15264610/232457652-45dd7913-1942-483a-a4ed-26a5034ee9e7.png)
2. Try to load AWX web page (any) => Error in console and white page
3. Set language to English again
2. Try to load AWX web page => Works

### Expected results

Show AWX dashboard/job page/etc

### Actual results

White page shown, error in console log

**Comment by Nyralei** [comment]
https://github.com/ansible/awx/issues/13756

**Comment by Kardi5** [comment]
Ah, didn't see. Thanks. Closing this
