### ISSUE TITLE
Blank Home Page if web browser is not set to English 

### ISSUE THREAD

**Issue by keytechnologies** [ansible/awx#13866]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

If web browser is not set to English the home page is blank. We need to add /?lang=en  in the uri.

I saw many reports about this issue closed without a solution other than manually add  /?lang=en  in the uri.

### AWX version

22.0.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

Dafault installation on Kubernetes without any changes.
Try to open the home page.

### Expected results

The home page

### Actual results

Blank page

**Comment by Lucas1794** [comment]
I can confirm with that problem. We have the same issue.

**Comment by ewertonhm** [comment]
I can confirm, the problem also appears in the 21.14.0 version, on 21.13.0 its working fine.

**Comment by ewertonhm** [comment]
After upgrade from awx-operator 1.3.0 to 1.4.0 (awx 21.13.0 to 21.14.0) we get the same issue, blank screen, changing the browser to english "fix" the issue

**Comment by weiserhei** [comment]
They tackled this already (#13756) and published the Update now. 
Installing the latest 22.1.0 release fixed it for us, thank you 🎉
