### ISSUE TITLE
[ui-next] Tech Preview capability not properly functioning

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#13877]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When an admin toggles the user interface capability on or off, and goes back to the Dashboard, the user has to click the refresh button to see the change.
![image](https://user-images.githubusercontent.com/63685497/232867945-4210fbb4-02f7-42e7-b46a-b5d9d985af12.png)

### AWX version

devel

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Steps to reproduce

To recreate:
Visit the settings screen and change the setting shown above. For example- disable the setting.
Visit the Dashboard. You would expect not to see the blue tech preview bar across the top, but you do. You have to click refresh for it to go away.

### Expected results

The setting change should take effect immediately without having to refresh.

### Actual results

The user has to click refresh for the setting to take effect.

**Comment by mabashian** [comment]
Yea this was by design and at this point we're unlikely to change that behavior
