### ISSUE TITLE
Docs on LDAP org/team mapping refer to email address which has no bearing on anything

### ISSUE THREAD

**Issue by psy-q** [ansible/awx#1387]
##### ISSUE TYPE
 - Documentation

##### SUMMARY

[The LDAP admin documentation](http://docs.ansible.com/ansible-tower/latest/html/administration/ldap_auth.html) states:

> Next, you will need to control which users are placed into which Tower organizations based on their username and email address (mapping out between your organization admins/users and LDAP groups).

But the email address is never used in any of the following examples. And I think it shouldn't have a bearing on anything anyhow since LDAP is just the directory service, users there don't necessarily have email addresses.

**Comment by tvo318** [comment]
@psy-q, the references to the email attribute is referenced in step 15. However, I will make it more clear in the docs to prevent confusion.

**Comment by psy-q** [comment]
Yes, it's true that email is used further up, but that map in step 15 only specifies which LDAP attributes are mapped to which field in AWX. 

Section 15.3, where the quote is from, is about something else: the section explains how you can map users to organizations based on their CN, so neither username nor e-mail address is used. That's why I thought the introduction sentence isn't correct. Unless there is some way to use usernames/e-mail in place of CNs in that config, but that isn't explained or shown in the example.

**Comment by chrismeyersfsu** [comment]
> Next, you will need to control which users are placed into which Tower organizations based on LDAP attributes (mapping out between your organization admins/users and LDAP groups).

@psy-q What do you think about the wording above?

**Comment by psy-q** [comment]
Absolutely fantastic, cheers :)

**Comment by tvo318** [comment]
Resolved with doc PR #[369](https://github.com/ansible/product-docs/pull/369).
