### ISSUE TITLE
LDAP example has wrong brackets in JSON (screenshot shows correct ones)

### ISSUE THREAD

**Issue by psy-q** [ansible/awx#1388]
##### ISSUE TYPE
 - Documentation

##### SUMMARY
[The LDAP admin docs ](http://docs.ansible.com/ansible-tower/latest/html/administration/ldap_auth.html) show an example for the LDAP User Attribute Map option:

```
[
"first_name": "givenName",
"last_name": "sn",
"email": "mail"
]
```

But it should be:
```
{
"first_name": "givenName",
"last_name": "sn",
"email": "mail"
}
```

Since a JSON hash is expected there.

**Comment by cchurch** [comment]
@psy-q This example has been fixed in our docs repo for 3.2.x and 3.3, will be live the next time we push docs.
