### ISSUE TITLE
Azure AD redirects to login

### ISSUE THREAD

**Issue by HelMirron** [ansible/awx#13893]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

**What i did:**

- Created an app in azure AD
- added in the process the redirect URL `https://awx.foo.site/sso/complete/azuread-oauth2/`
- retrived the AppID and the Secret and put them in the correct place.

now after the succsessfull login the page redirects me to the loginpage again instead loging me in. 

### AWX version

22.1.0

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

latest

### Operating system

Ubuntu 22.04

### Web browser

Firefox, Chrome

### Steps to reproduce

Fresh installation: 
add AD oauth via AzureAD

### Expected results

Succsessfull login with an AD User that is added to the allowed users

### Actual results

redirect to loginpage

**Comment by Klaas-** [comment]
check your logs if you have an error, sounds like the auth is not valid on the azure ad side. I think errors should show up here:
`kubectl logs pod/[intance name]-web-[...] -c [intance name]-web -f`

You may need to enable debug logs via logging settings

Make sure your client secret is valid (on the azure side) and set correctly inside awx db

```
kubectl exec --stdin --tty [intance name]-task-[...] -c [intance name]-task -- /bin/bash
awx-manage shell_plus
from awx.main.utils import decrypt_field
print(decrypt_field(Setting.objects.get(key='SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET'), 'value'))
```

**Comment by Klaas-** [comment]
@MirronSenpai so what was the problem? :)

**Comment by omnachiketa** [comment]
I am getting the same error, and I have checked the secret too. @Klaas- 
`10.34.71.229 - - [14/Jun/2023:08:31:37 +0000] "GET /sso/error/ HTTP/1.1" 301 0 "https://FQDN/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "10.38.46.227"
[pid: 144|app: 0|req: 360/24468] 10.34.71.229 () {64 vars in 1307 bytes} [Wed Jun 14 08:31:37 2023] GET /sso/error/ => generated 0 bytes in 29 msecs (HTTP/1.1 301) 10 headers in 463 bytes (1 switches on core 0)
10.34.75.218 - - [14/Jun/2023:08:31:38 +0000] "GET /sso/complete/azuread-oauth2/ HTTP/1.1" 499 0 "https://FQDN/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "10.38.46.227"
2023-06-14 08:31:38,527 ERROR    [294240cfde2448b68733c548274c91d1] social Missing needed parameter state.
2023-06-14 08:31:38,527 ERROR    [a789011ade854847be3a6ac4c484e900] social Missing needed parameter state.
[pid: 144|app: 0|req: 361/24469] 10.34.75.218 () {64 vars in 1343 bytes} [Wed Jun 14 08:31:38 2023] GET /sso/complete/azuread-oauth2/ => generated 0 bytes in 30 msecs (HTTP/1.1 302) 10 headers in 461 bytes (1 switches on core 0)
10.34.75.218 - - [14/Jun/2023:08:31:38 +0000] "GET /sso/complete/azuread-oauth2/ HTTP/1.1" 302 0 "https://FQDN/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "10.38.46.227"
[pid: 135|app: 0|req: 623/24470] 10.34.75.218 () {64 vars in 1343 bytes} [Wed Jun 14 08:31:38 2023] GET /sso/complete/azuread-oauth2/ => generated 0 bytes in 31 msecs (HTTP/1.1 302) 10 headers in 461 bytes (1 switches on core 0)
10.34.71.229 - - [14/Jun/2023:08:31:38 +0000] "GET / HTTP/1.1" 200 1044 "https://FQDN/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "10.38.46.227"
[pid: 144|app: 0|req: 362/24471] 10.34.71.229 () {62 vars in 1287 bytes} [Wed Jun 14 08:31:38 2023] GET / => generated 1044 bytes in 30 msecs (HTTP/1.1 200) 9 headers in 438 bytes (1 switches on core 0)
`
