### ISSUE TITLE
Cannot perform backup on AWX minikube

### ISSUE THREAD

**Issue by ggalindo-networkingdev** [ansible/awx#13899]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When it restores data of the PostgreSQL container from backup, the AWX-Operator service goes down.

So, the only way for running the AWX-Operator up again is to stop the Minikube service and start it again. But, it runs with the not restored data. 

Do you know of any solution to make the backup in Minikube service?

Is there any way to make the backup running the AWX service in Minikube?

### AWX version

20.0.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

minikube

### Modifications

no

### Steps to reproduce

Backup

> docker exec -it minikube bash

> docker exec -i c1399946a795 /usr/bin/pg_dump -U awx awx > postgres-backup.sql

Restore

> docker exec -i c1399946a795 pg_restore -U <database_owner> -d <database_name> <path_to_dump>

### Expected results

Runs AWX with restored data

### Actual results

AWX cannot be restored

**Comment by fosterseth** [comment]
have you tried using the backup and restore roles for operator? https://github.com/ansible/awx-operator#backup

that said, what you are doing with docker exec and pg_dump / pg_restore should be possible, but we haven't tested it. What errors are you seeing specifically?

**Comment by dmzoneill** [comment]
No response. Closing for now.  Please re-open if you feel this issue if you can provide the information requested.
