### ISSUE TITLE
Smart Inventory: Execution of Templates also starts on disabled ("OFF") hosts

### ISSUE THREAD

**Issue by stefan-wegener** [ansible/awx#1390]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API?
 - UI

##### SUMMARY
I create a Smart Inventory. Then I disable ("OFF") hosts in it. When now running a Template on my Smart Inventory, the Template will also be executed on all hosts that are disabled.

##### ENVIRONMENT
* AWX version: 1.0.4.14
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: Linux (Ubuntu)
* Web Browser: Firefox, Chrome

##### STEPS TO REPRODUCE

1. Create Inventory with some hosts in it.
2. Create Smart Inventory with hosts of previous Inventory
3. Disable ("OFF") some hosts in these Smart Inventory
4. Execute a Template that uses the Smart Inventory.

##### EXPECTED RESULTS

The Template will be executed on all hosts of the Smart Inventory except for those that are marked as "OFF".

##### ACTUAL RESULTS

The Template executes on all hosts of the Smart Inventory.

**Comment by ryanpetrello** [comment]
@stefan-wegener thanks for reporting this; there's a bug fix coming for it in the near-ish future - stay tuned!

**Comment by ryanpetrello** [comment]
@stefan-wegener this should be fixed now via https://github.com/ansible/awx/commit/23267bce387602514ce351b4f5b21748a81d1dc1
