### ISSUE TITLE
RFE: Make the schedule of cluster heartbeats configurable

### ISSUE THREAD

**Issue by b0urn3** [ansible/awx#1391]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### ENVIRONMENT
* AWX version: N/A
* AWX install method: N/A
* Ansible version:  N/A
* Operating System: N/A
* Web Browser: N/A

##### STEPS TO REPRODUCE

Currently the heartbeat schedule for cluster is hard-coded in here

https://github.com/ansible/awx/blob/devel/awx/settings/defaults.py#L489

Consider making it configurable.

##### EXPECTED RESULTS

Be able to configure the heartbeats schedule, e.g. every 30 seconds instead of currently hard-coded 60.

**Comment by wenottingham** [comment]
What is the context of why you would need this?

**Comment by b0urn3** [comment]
@wenottingham it's a request from customer they would like to have this possibility so they can control how quickly an issue with some node is discovered and therefore subsequently removed from potentially scheduling a job on such a node.

**Comment by wenottingham** [comment]
That seems like a reason to lower the default one... I still don't think it makes sense as a configurable knob.

**Comment by wenottingham** [comment]
Solved differently by https://github.com/ansible/awx/pull/1411 and followons
