### ISSUE TITLE
Frequency Detail displays incorrect data on Schedule page, but the schedule is correct

### ISSUE THREAD

**Issue by jjbaumgartner** [ansible/awx#13925]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Recurring schedules appear to have the wrong day listed in the "runs on" field of the schedule.  The schedule below is set to run on the second Saturday, but the runs on field shows first Saturday.  The edit page shows the correct value is selected, and the list of upcoming runs is choosing the correct dates.

Schedule detail page:
![image](https://user-images.githubusercontent.com/26311555/235196672-052ad3eb-6702-4704-81f6-e89aa8c74339.png)

Schedule edit page:
![image](https://user-images.githubusercontent.com/26311555/235196757-1559ddbd-dbb7-4cd1-ad89-c85c54989703.png)

### AWX version

22.1.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

minikube

### Modifications

no

### Operating system

Ubuntu 22.04

### Web browser

Chrome

### Steps to reproduce

1. Create a new schedule
2. Set the **Repeat frequency** to **Month**
3. Set **Run on** to **The <any option except First> <any day>**
4. Save the schedule

### Expected results

The schedule detail **Run on** field should show the value selected in the steps to reproduce.

### Actual results

The schedule detail **Run on** field will always show "The first <day selected>".

### Additional information

This appears to be a display issue only - functionally the schedule is working as expected.

**Comment by jjbaumgartner** [comment]
Adding correct Schedule Edit screenshot:
![image](https://user-images.githubusercontent.com/26311555/235198712-4e049652-2d4f-4d85-a03e-cd915aa522f2.png)

**Comment by mabashian** [comment]
Fixed by https://github.com/ansible/awx/pull/13941
