### ISSUE TITLE
Inventory Scripts - Python Script executes with errors

### ISSUE THREAD

**Issue by stefan-wegener** [ansible/awx#1392]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
I created a 

##### ENVIRONMENT
* AWX version: 1.0.4.14
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: Linux (Ubuntu)
* Web Browser: Firefox, Chrome

##### STEPS TO REPRODUCE

1. Create Inventory Script with custom script code:
`#!/usr/bin/env python

data_to_print = '{"marietta": ["host6.example.com"], "5points": ["host7.example.com"] "_meta": {"hostvars": {}}}'
print data_to_print`

2. Create new Inventory. Sources -> Add Source -> Type: Custom Script -> Custom Inventory Script: Select previous created Inventory Script. Save.

Inventory sync job fails. Log:
`2018-02-28 15:04:43,480 INFO     awx.main.commands.inventory_import Updating inventory 8: Mssql Inventory
2018-02-28 15:04:43,495 INFO     awx.main.commands.inventory_import Reading Ansible inventory source: /tmp/awx_inventory_6F6SLV/tmpWQAftk
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==1.0.4.14', 'console_scripts', 'awx-manage')()
  File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 993, in handle
    self.is_custom)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 242, in load_inventory_source
    is_custom=is_custom).load()
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 177, in load
    data = self.command_to_json(base_args + ['--list'])
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 160, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=4) with stdout:

stderr:
ERROR! Could not parse inventory source /tmp/awx_inventory_6F6SLV/tmpWQAftk with available plugins:
Plugin script failed: failed to parse executable inventory script results from /tmp/awx_inventory_6F6SLV/tmpWQAftk: Syntax Error while loading YAML.

The error appears to have been in '/tmp/awx_inventory_6F6SLV/tmpWQAftk': line 1, column 70, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

#!/usr/bin/env python
                                                                     ^ here

exception type: <class 'yaml.parser.ParserError'>
exception: while parsing a flow mapping
  in "<unicode string>", line 1, column 1
did not find expected ',' or '}'
  in "<unicode string>", line 1, column 70

Plugin yaml failed: Syntax Error while loading YAML.

The error appears to have been in '/tmp/awx_inventory_6F6SLV/tmpWQAftk': line 3, column 52, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

data_to_print = '{"marietta": ["host6.example.com"], "5points": ["host7.example.com"] "_meta": {"hostvars": {}}}'
                                                   ^ here
We could be wrong, but this one looks like it might be an issue with
unbalanced quotes.  If starting a value with a quote, make sure the
line ends with the same set of quotes.  For instance this arbitrary
example:

    foo: "bad" "wolf"

Could be written as:

    foo: '"bad" "wolf"'

exception type: <class 'yaml.parser.ParserError'>
exception: while parsing a block mapping
  in "<unicode string>", line 3, column 1
did not find expected key
  in "<unicode string>", line 3, column 52
Plugin ini failed: /tmp/awx_inventory_6F6SLV/tmpWQAftk:3: Expected key=value host variable assignment, got: {"marietta": ["host6.example.com"], "5points": ["host7.example.com"] "_meta": {"hostvars": {}}}

`

For me it seems that the script gets interpreted as YAML and there is no real execution of the script as a Python script.

##### EXPECTED RESULTS

Sync of the script that inserts the hosts: host6.example.com and host7.example.com.

##### ACTUAL RESULTS

Error seen above.

**Comment by wenottingham** [comment]
Your script has invalid JSON. You may want to check it with something like 'jq' first.

**Comment by stefan-wegener** [comment]
Oh, you are right. I was pretty sure that this "script" ran successfully some months ago and thereby never questioned it...

Thanks for your quick answer and sorry for opening this in error!
