### ISSUE TITLE
Proxy settings not used by AWX containers

### ISSUE THREAD

**Issue by jordan78** [ansible/awx#13944]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I am running awx 22.0.0 installed using awx-operator 2.0.0 on k3s cluster 1.25.3+k3s1 on Ubuntu 22.04. This cluster is behind a proxy and I added the proxy settings in AWX UI under settings-> jobs settings->"extra environment variables".  We configured splunk log aggregation and it was working with splunk on-prem. When splunk instance got moved to the cloud we noticed awx-rsyslog, awx-web, awx-task and rest of the containers didn't have http_proxy and https_proxy env set. I shelled to the awx-rsyslog in the awx-web pod and was not able to curl send test logs to splunk untill I added https_proxy env variable.  

### AWX version

22.0.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

After running a job the output doesn't make it to splunk. awx-rsyslog giving this error:

rsyslogd: omhttp: checkResult error http status code: 0 reply: NULL [v8.2102.0-106.el9 try https://www.rsyslog.com/e/2007 ]
rsyslogd: omhttp: error opening error file /var/log/tower/rsyslog.err: No such file or directory [v8.2102.0-106.el9]
rsyslogd: omhttp: suspending ourselves due to server failure 28: Failed to connect to xxxxxsplunkcloud.com port 443: Connection timed out [v8.2102.0-106.el9 try https://www.rsyslog.com/e/2007 ]

from the host running k3s/awx pods I am able to curl send data to splunk
from inside the container awx-ryslog or awx-web, etc. curl timeout sending data to splunk unless https_proxy is set in the container.  https_proxy and http_proxy are set in the UI under job settings.

### Expected results

automation jobs should be able to ship logs to splunk using the proxy setting in the AWX UI.

### Actual results

automation jobs are unable to honor the proxy settings set in the awx UI.

**Comment by fosterseth** [comment]
thanks for highlighting this, sounds like a bug

**Comment by jordan78** [comment]
I found out I could use this instea rsyslog_extra_env: and it worked fine for me.
