### ISSUE TITLE
InstanceInstallBundle as a bash script instead of ansible collection and role

### ISSUE THREAD

**Issue by erezo9** [ansible/awx#13946]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

as the run on kubernetes/openshift allows the use of execution nodes
in a disconnected environment its diffcult to install the ansible.receptor collection as well as all the prerequisites to run the playbook

I would suggest using a bash script that will do the same as the collection - as well as I am proposing to write the bash script it self
it would be helpful to know if I were to create the merge request or after writing the bash script (if it makes sense) where should it be published
for me, as an admin , running the ansible.receptor collection and doing the whole thing to make it work, would be easier to just run the bash script it self

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

Installing awx on a disconnected environment and trying to install a disconnected exeuction node with no port 22 open to it

### Current results

you need to install python + ansible + required ansible.receptor collection and then run the role

### Sugested feature result

use a bash script which will be alot easier to run on every platform

### Additional information

I would write the script myself, I would like to know where to put it on the repository, or what directory

also modifing the ansible receptor api
https://github.com/ansible/awx/blob/devel/awx/api/views/instance_install_bundle.py#L43

**Comment by djyasin** [comment]
@erezo9 
Thank you for reaching out to us! After reviewing this issue with the team, we have decided that this is not something that would be implemented upstream. We do not have checks in place to support this type of feature. Since we do not have supporting checks it would not be something that would be fruitful for the project. 

This is certainly something you could do locally in your own environment if you chose to. If you would like support for that endeavor, we would recommend reaching out to the community mailing list(https://github.com/ansible/awx/#get-involved) or Matrix Channel(https://docs.ansible.com/ansible/latest/community/communication.html#ansible-community-on-matrix).

Thank you for your time!

**Comment by erezo9** [comment]
@djyasin is it possible for me to do a pull request of this feature? after checks and everything? or should i just use it on my own
i have a bash script ready to test

**Comment by shanemcd** [comment]
@erezo9 We appreciate the offer, but isn't something we're currently able to support and maintain long term.

**Comment by erezo9** [comment]
@shanemcd 

I think there should be an option to support somehow an easy way to configure instances on an on-prem environment
the ssh port isnt really open to all the hosts i have, and since i use awx, i dont have an instance to run from (the controller isnt open on the ssh port)

also installin python and ansible on the execution itself just to un the playbook is useless (in my opinion)

**Comment by shanemcd** [comment]
Thank you for sharing your opinion. I'm not discounting it - but our position here stands. You are free to build and maintain the tooling on your own, but it's not something we're interested in maintaining ourselves.
