### ISSUE TITLE
Job Templates not showing correctly via organization page after AWX update to 1.04.14

### ISSUE THREAD

**Issue by pnkcigarette** [ansible/awx#1396]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
Since updating to release 1.0.4, I'm seeing UI issues around viewing job templates via organizations.  This includes not iterating job template counts when new job templates are added for a particular organization.

##### ENVIRONMENT
* AWX version: 1.0.4.14
* AWX install method: k8s
* Ansible version:  2.4.3.0
* Operating System: client is Windows 7
* Web Browser: Chrome 60.0.3112.90

##### STEPS TO REPRODUCE

1) Login to AWX.
2) Select ORGANIZATIONS from the left menu.
3) Select JOB TEMPLATES for any organization.

##### EXPECTED RESULTS

You would be shown job templates filtered by organization, as well as counts for each organization would increment.

##### ACTUAL RESULTS

The page does not show job templates and reports no results found.  The page shows multiple template fields.  See screen shot for detailed view.

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/36895410/36800193-83eef0a4-1c74-11e8-8609-d82f516ee5e4.png)

**Comment by mabashian** [comment]
Link https://github.com/ansible/awx/pull/1323 - could be related/similar fix

**Comment by jaredevantabor** [comment]
this is fixed in devel
