### ISSUE TITLE
Update collection docs

### ISSUE THREAD

**Issue by jay-steurer** [ansible/awx#13974]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

Add the `state:exists` to the collection docs. [here](https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_kvm_module.html#parameter-state)
PR that added the new state: https://github.com/ansible/awx/pull/13890

Version: 4.5

### Select the relevant components

- [ ] UI
- [ ] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

.

### Current results

.

### Sugested feature result

.

**Comment by samccann** [comment]
The docs link in the description is pointing to the community.general collection, not awx.awx.

When I look at the PR that added the new state, it seems to have already updated the docs. I looked at a couple of them on docs.ansible.com and the exists state is there:
https://docs.ansible.com/ansible/latest/collections/awx/awx/credential_type_module.html#parameter-state

So either I'm not following the ask here, or ...it's already been updated and y'all can close this issue.
