### ISSUE TITLE
Websocket Connection to 'wss://{{ awx-host }}/websocket' failed: WebSocket is closed before the connection is established.

### ISSUE THREAD

**Issue by ewertonhm** [ansible/awx#13978]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

After upgrading to awx 22.1.0, the jobs output won't show real-time data, you need to keep pressing f5 to reload the page,
in browser console you get the error:

Websocket Connection to 'wss://{{ awx-host }}/websocket' failed: WebSocket is closed before the connection is established.

### AWX version

22.1.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

Run a template playbook and watch the output

### Expected results

Output should show real-time logs

### Actual results

Output is blank, when the webpage is reload it shows the logs until that point (or all if the template already finished running)

**Comment by darviche** [comment]
Hello,
I experienced the same issue with Firefox 102.11.0esr (64 bits) and Microsoft Edge 112.0.1722.64 (64-bit).

**Comment by ewertonhm** [comment]
Solved with an redeploy

**Comment by aryklein** [comment]
I'm having the same issue with Chromium-based browsers.

**Comment by wildw1ng** [comment]
Same issue with Firefox and Chrome.

**Comment by smcavoy-workwork** [comment]
I "cleared" the issue by restarting the task container
This is on awx 22.2.0 installed w/ awx-operator-2.3.0
