### ISSUE TITLE
implement instance groups as bulk job node launch time "prompt"

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#13981]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

We left a comment for ourselves to implement this but then it seems we have not gotten around to it:

https://github.com/ansible/awx/blob/85e7189ee369c9b08e5301180a3c86fe31029bdb/awx/api/serializers.py#L4689-L4690

#13584 merged...but we did not implement this for bulk api

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

should be able to include instance group as "prompt" value if thats supported on underlying job template

### Current results

is not

### Sugested feature result

should be

**Comment by kdelee** [comment]
@jainnikhil30 @AlanCoding @gamuniz looks like we missed this

**Comment by jay-steurer** [comment]
PR has been merged, closing it.
