### ISSUE TITLE
No Icon For Pending/Running Jobs

### ISSUE THREAD

**Issue by grahamneville** [ansible/awx#1399]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
In recent versions of AWX there is no longer a flashing grey/green icon for pending/running jobs

##### ENVIRONMENT
* AWX version: 1.4.0.31
* AWX install method: docker on linux
* Ansible version:  2.4.0.3

##### STEPS TO REPRODUCE

1) Run a job and go back to the job_templates view, 

##### EXPECTED RESULTS

You'll see an icon flashing to indicate there is a pending/running job

##### ACTUAL RESULTS

You no longer see a flashing icon to indicate a job is running

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/19539695/36810402-7f3aec0e-1cc2-11e8-8b82-1c3500463d59.png)

**Comment by wenottingham** [comment]
Known issue, websockets are broken.

**Comment by jaredevantabor** [comment]
this has been fixed in devel.
