### ISSUE TITLE
Missing job output and log lines

### ISSUE THREAD

**Issue by mamercad** [ansible/awx#14003]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

I've run into this rather strange situation where I'm missing output from jobs. In an attempt to reproduce it, I created a relatively simple Ansible playbook which runs for a few hours and generates a few thousands of lines of output. For the most recent test, it ran for about 4 hours and 20 minutes and the playbook simply counted to 40,000.

The output in the UI and when downloaded looks like this (abbreviated):

![image](https://github.com/ansible/awx/assets/6192266/a3e0c85d-f2b4-4a16-a70c-d85e56c23fdb)

Notice the huge swath of missing lines.

The playbook that it's running is quite simple:

```ansible
---
- name: long_log_lines
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    how_many: 40000

  tasks:
    - name: Create a list
      ansible.builtin.command:
        cmd: seq {{ how_many }}
      register: the_list

    - name: Set a fact for the list
      ansible.builtin.set_fact:
        the_list: "{{ the_list.stdout_lines }}"

    - name: Ping list times
      ansible.builtin.ping:
      loop: "{{ the_list }}"
```

### AWX version

21.11.14

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.9

### Operating system

Linux

### Web browser

Chrome

### Steps to reproduce

This should be simple to reproduce, it's a very simple playbook.

### Expected results

That all of the output is there.

### Actual results

Missing many thousands of lines.

**Comment by dylex** [comment]
We're seeing the same thing on 22.2.0 on a new k8s multi-node cluster. (We did not see this issue on an older 21.7.0, single-node k8s. Not sure what the critical difference is.) I do see the output in the automation-job pod log, but various errors in the awx-ee log (at the time the job ends):
```
WARNING 2023/05/19 15:35:33 [hfO2BPfm] Error getting pod awx/automation-job-203-h96fh. Will retry 5 more times. Error: client rate limiter Wait returned an error: context canceled
WARNING 2023/05/19 15:35:34 [hfO2BPfm] Error getting pod awx/automation-job-203-h96fh. Will retry 4 more times. Error: client rate limiter Wait returned an error: context canceled
WARNING 2023/05/19 15:35:35 [hfO2BPfm] Error getting pod awx/automation-job-203-h96fh. Will retry 3 more times. Error: client rate limiter Wait returned an error: context canceled
WARNING 2023/05/19 15:35:36 [hfO2BPfm] Error getting pod awx/automation-job-203-h96fh. Will retry 2 more times. Error: client rate limiter Wait returned an error: context canceled
ERROR 2023/05/19 15:35:37 Exceeded retries for reading stdout /tmp/receptor/awx-task-6dd69c77d5-ssn6l/hfO2BPfm/stdout
WARNING 2023/05/19 15:35:37 Could not read in control service: read unix /var/run/receptor/receptor.sock->@: use of closed network connection
WARNING 2023/05/19 15:35:37 Could not close connection: close unix /var/run/receptor/receptor.sock->@: use of closed network connection
WARNING 2023/05/19 15:35:37 [hfO2BPfm] Error getting pod awx/automation-job-203-h96fh. Will retry 1 more times. Error: client rate limiter Wait returned an error: context canceled
ERROR 2023/05/19 15:35:38 [hfO2BPfm] Error getting pod awx/automation-job-203-h96fh. Error: client rate limiter Wait returned an error: context canceled
ERROR 2023/05/19 15:35:38 Error updating status file /tmp/receptor/awx-task-6dd69c77d5-ssn6l/hfO2BPfm/status: open /tmp/receptor/awx-task-6dd69c77d5-ssn6l/hfO2BPfm/status.lock: no such file or directory.
```

**Comment by shanemcd** [comment]
What distro of k8s are y'all using? Are you running jobs in the control plane's namespace or externally via a container group?

**Comment by dylex** [comment]
We're using k8s 1.26.1 via kubeadm (on-prem). awx is deployed via awx-operator 2.1.0 with helm without anything special, jobs in the "default" container group instance (not control plane), AWX EE.

**Comment by mamercad** [comment]
> What distro of k8s are y'all using? Are you running jobs in the control plane's namespace or externally via a container group?

I'm seeing this, at least, on `1.24.8`.

**Comment by mamercad** [comment]
> What distro of k8s are y'all using? Are you running jobs in the control plane's namespace or externally via a container group?

I can't remember if it was under `controlplane` or a separate Container Group; next week, I'll do the same experiment under both and report back.

**Comment by mamercad** [comment]
> > What distro of k8s are y'all using? Are you running jobs in the control plane's namespace or externally via a container group?
> 
> I can't remember if it was under `controlplane` or a separate Container Group; next week, I'll do the same experiment under both and report back.

For the output that I began this issue with, it happened under the `default` Container Group.

**Comment by mamercad** [comment]
> e's namespace or external

Hrm, when using `controlplane` I'm currently getting `This job is not ready to start because there is not enough available capacity.`; trying to figure out which knobs to turn.

**Comment by mamercad** [comment]
> What distro of k8s are y'all using? Are you running jobs in the control plane's namespace or externally via a container group?

Hrm, I'm getting kind of confused, this is basically a stock install and what I have:
![image](https://github.com/ansible/awx/assets/6192266/28544b74-1bf5-4e27-a391-79805df7baa2)

What/how would you like me to test?

**Comment by mabashian** [comment]
At first I thought this was exclusively a ui issue but since you indicated that the downloaded output was also missing the same lines I'm going to flip this over to api.  Downloaded output comes straight through the api.

**Comment by shanemcd** [comment]
@mamercad  Sorry for the confusion here. By default AWX will run pods in the same namespace the control plane is running. The "default" container group is using the k8s api to run jobs in the same namespace AWX is running. The instance group "controlplane" forces certain types of tasks (like project updates) to run within the AWX pod rather than as an external pod. We also support running jobs in remote Kubernetes clusters using the container group mechanism. Based on your comments and image here it looks like you're just running things in the local cluster, which is what I was curious about.

**Comment by mamercad** [comment]
> @mamercad Sorry for the confusion here. By default AWX will run pods in the same namespace the control plane is running. The "default" container group is using the k8s api to run jobs in the same namespace AWX is running. The instance group "controlplane" forces certain types of tasks (like project updates) to run within the AWX pod rather than as an external pod. We also support running jobs in remote Kubernetes clusters using the container group mechanism. Based on your comments and image here it looks like you're just running things in the local cluster, which is what I was curious about.

Ah, okay. Yes, I'm running everything in the same cluster, and, in the same namespace.

**Comment by mamercad** [comment]
Just a quick update, I'm testing this on 22.3.0, I'll report back (same setup, single cluster, same namespace).

**Comment by mamercad** [comment]
> Just a quick update, I'm testing this on 22.3.0, I'll report back (same setup, single cluster, same namespace).

Still running, noticing this behavior also:

![image](https://github.com/ansible/awx/assets/6192266/d4fefd93-35c6-4c6e-8ef4-0f13b311a070)

<details><summary>Console</summary>
<p>


```text
index.js:9 I18nProvider did not render. A call to i18n.activate still needs to happen or forceRenderOnLocaleChange must be set to false.
index.js:2066     GET https://awx.cloudmason.org/static/css/ 403
getOKResponse @ index.js:2066
loadAsDataURL @ index.js:2085
getImageDataURL @ index.js:2167
(anonymous) @ index.js:2142
getImageDetails @ index.js:2136
(anonymous) @ index.js:2865
(anonymous) @ index.js:3000
(anonymous) @ index.js:3000
getDeclarations @ index.js:3280
(anonymous) @ index.js:3307
(anonymous) @ index.js:4553
(anonymous) @ index.js:4550
modifySheet @ index.js:4431
buildOverrides @ index.js:4957
render @ index.js:4970
update @ index.js:6181
(anonymous) @ index.js:4903
Promise.then (async)
details @ index.js:4899
(anonymous) @ index.js:6103
createDynamicStyleOverrides @ index.js:6103
runDynamicStyle @ index.js:6217
createThemeAndWatchForUpdates @ index.js:6225
createOrUpdateDynamicThemeInternal @ index.js:6420
createOrUpdateDynamicTheme @ index.js:6375
onMessage @ index.js:6667
connectJobSocket.js:48 WebSocket connection to 'wss://awx.cloudmason.org/websocket/' failed: WebSocket is closed before the connection is established.
(anonymous) @ connectJobSocket.js:48
Fl @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vi @ react-dom.production.min.js:122
Dl @ react-dom.production.min.js:261
yl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vi @ react-dom.production.min.js:122
Yi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
fl @ react-dom.production.min.js:237
Io @ react-dom.production.min.js:170
(anonymous) @ JobOutput.js:194
Promise.then (async)
(anonymous) @ JobOutput.js:193
Fl @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vi @ react-dom.production.min.js:122
Dl @ react-dom.production.min.js:261
yl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vi @ react-dom.production.min.js:122
Yi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
fl @ react-dom.production.min.js:237
Io @ react-dom.production.min.js:170
(anonymous) @ useRequest.js:44
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
fr @ asyncToGenerator.js:3
o @ asyncToGenerator.js:25
Promise.then (async)
fr @ asyncToGenerator.js:13
o @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Job.js:113
Fl @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vi @ react-dom.production.min.js:122
Dl @ react-dom.production.min.js:261
yl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vi @ react-dom.production.min.js:122
Yi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
fl @ react-dom.production.min.js:237
Io @ react-dom.production.min.js:170
(anonymous) @ useRequest.js:34
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
fr @ asyncToGenerator.js:3
o @ asyncToGenerator.js:25
Promise.then (async)
fr @ asyncToGenerator.js:13
o @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Config.js:91
Fl @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vi @ react-dom.production.min.js:122
Dl @ react-dom.production.min.js:261
yl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vi @ react-dom.production.min.js:122
Yi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
fl @ react-dom.production.min.js:237
Io @ react-dom.production.min.js:170
(anonymous) @ useRequest.js:44
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
fr @ asyncToGenerator.js:3
o @ asyncToGenerator.js:25
Promise.then (async)
fr @ asyncToGenerator.js:13
o @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Session.js:97
Fl @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vi @ react-dom.production.min.js:122
Dl @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
M @ scheduler.production.min.js:16
_.port1.onmessage @ scheduler.production.min.js:12

```

</p>
</details>

**Comment by mamercad** [comment]
> > Just a quick update, I'm testing this on 22.3.0, I'll report back (same setup, single cluster, same namespace).
> 
> Still running, noticing this behavior also:
> 
> ![image](https://user-images.githubusercontent.com/6192266/241245352-d4fefd93-35c6-4c6e-8ef4-0f13b311a070.png)
> 
> Console

Different machine 🤷 

<img width="729" alt="image" src="https://github.com/ansible/awx/assets/6192266/9b09b487-632a-4c4e-a3c8-4feb31228915">

**Comment by mamercad** [comment]
> > > Just a quick update, I'm testing this on 22.3.0, I'll report back (same setup, single cluster, same namespace).
> > 
> > 
> > Still running, noticing this behavior also:
> > ![image](https://user-images.githubusercontent.com/6192266/241245352-d4fefd93-35c6-4c6e-8ef4-0f13b311a070.png)
> > Console
> 
> Different machine 🤷
> 
> <img alt="image" width="729" src="https://user-images.githubusercontent.com/6192266/241266547-9b09b487-632a-4c4e-a3c8-4feb31228915.png">

Well, it errored out (I had it set to count to 12,000):

<img width="741" alt="image" src="https://github.com/ansible/awx/assets/6192266/7efdfc42-62ef-4f10-9c5c-732beb04e05e">

**Comment by mamercad** [comment]
Here are some logs from the task container around the time the job (83) died:

<summary><details>

```text
2023-05-26 12:14:04,870 INFO     [059fb68fa81c41ebbb1baa06084131c8] awx.analytics.job_lifecycle job-83 waiting
2023-05-26 12:14:05,053 INFO     [059fb68fa81c41ebbb1baa06084131c8] awx.analytics.job_lifecycle job-83 pre run
2023-05-26 12:14:05,459 INFO     [059fb68fa81c41ebbb1baa06084131c8] awx.analytics.job_lifecycle job-83 preparing playbook
2023-05-26 12:14:05,539 INFO     [059fb68fa81c41ebbb1baa06084131c8] awx.analytics.job_lifecycle job-83 running playbook
2023-05-26 12:14:06,289 INFO     [059fb68fa81c41ebbb1baa06084131c8] awx.analytics.job_lifecycle job-83 work unit id received
2023-05-26 12:14:06,338 INFO     [059fb68fa81c41ebbb1baa06084131c8] awx.analytics.job_lifecycle job-83 work unit id assigned
2023-05-26 13:31:15,120 INFO     [-] awx.main.wsrelay Producer 10.42.2.138-jobs-summary has no subscribers, shutting down.
2023-05-26 13:31:16,821 INFO     [-] awx.main.wsrelay Producer 10.42.2.138-project_update_events-78 has no subscribers, shutting down.
2023-05-26 13:31:19,163 INFO     [-] awx.main.wsrelay Starting producer for 10.42.2.138-schedules-changed
2023-05-26 13:31:20,515 INFO     [-] awx.main.wsrelay Producer 10.42.2.138-job_events-79 has no subscribers, shutting down.
2023-05-26 13:31:20,516 INFO     [-] awx.main.wsrelay Producer 10.42.2.138-project_update_events-77 has no subscribers, shutting down.
2023-05-26 13:31:20,518 INFO     [-] awx.main.wsrelay Producer 10.42.2.138-job_events-81 has no subscribers, shutting down.
2023-05-26 13:31:39,166 INFO     [-] awx.main.wsrelay Producer 10.42.2.138-schedules-changed has no subscribers, shutting down.
2023-05-26 13:42:29,849 INFO     [-] awx.main.wsrelay Producer 10.42.2.138-job_events-83 has no subscribers, shutting down.
2023-05-26 13:45:23,996 INFO     [-] awx.main.wsrelay Starting producer for 10.42.2.138-schedules-changed
2023-05-26 13:45:28,093 INFO     [-] awx.main.wsrelay Starting producer for 10.42.2.138-job_events-83
2023-05-26 13:45:28,093 INFO     [-] awx.main.wsrelay Starting producer for 10.42.2.138-jobs-summary
2023-05-26 13:45:33,999 INFO     [-] awx.main.wsrelay Producer 10.42.2.138-schedules-changed has no subscribers, shutting down.
2023-05-26 13:45:36,573 INFO     [-] awx.main.wsrelay Starting producer for 10.42.2.138-schedules-changed
2023-05-26 13:45:46,575 INFO     [-] awx.main.wsrelay Producer 10.42.2.138-schedules-changed has no subscribers, shutting down.
2023-05-26 13:45:52,015 INFO     [-] awx.main.wsrelay Starting producer for 10.42.2.138-schedules-changed
2023-05-26 13:57:12,166 INFO     [-] awx.main.wsrelay Producer 10.42.2.138-schedules-changed has no subscribers, shutting down.
2023-05-26 14:43:38,791 INFO     [-] awx.main.wsrelay Producer 10.42.2.138-jobs-summary has no subscribers, shutting down.
2023-05-26 14:43:38,792 INFO     [-] awx.main.wsrelay Producer 10.42.2.138-job_events-83 has no subscribers, shutting down.
2023-05-26 14:43:42,364 INFO     [-] awx.main.wsrelay Starting producer for 10.42.2.138-job_events-83
2023-05-26 14:43:42,365 INFO     [-] awx.main.wsrelay Starting producer for 10.42.2.138-jobs-summary
2023-05-26 14:48:13,524 INFO     [-] awx.main.wsrelay Starting producer for 10.42.2.138-schedules-changed
2023-05-26 14:48:23,529 INFO     [-] awx.main.wsrelay Producer 10.42.2.138-schedules-changed has no subscribers, shutting down.
2023-05-26 14:48:26,442 INFO     [-] awx.main.wsrelay Starting producer for 10.42.2.138-schedules-changed
2023-05-26 14:48:36,446 INFO     [-] awx.main.wsrelay Producer 10.42.2.138-schedules-changed has no subscribers, shutting down.
2023-05-26 15:45:06,420 INFO     [-] awx.main.wsrelay Starting producer for 10.42.2.138-schedules-changed
2023-05-26 15:45:16,422 INFO     [-] awx.main.wsrelay Producer 10.42.2.138-schedules-changed has no subscribers, shutting down.
2023-05-26 15:55:38,464 ERROR    [8846ca95313f4ae9866926fde12dbf24] awx.main.dispatch Worker failed to run task awx.main.tasks.system.purge_old_stdout_files(*[], **{}
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/worker/task.py", line 103, in perform_work
    result = self.run_callable(body)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/worker/task.py", line 78, in run_callable
    return _call(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/system.py", line 332, in purge_old_stdout_files
    for f in os.listdir(settings.JOBOUTPUT_ROOT):
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/awx/job_status'
2023-05-26 16:15:03,624 INFO     [059fb68fa81c41ebbb1baa06084131c8] awx.main.commands.run_callback_receiver Starting EOF event processing for Job 83
2023-05-26 16:15:03,749 INFO     [059fb68fa81c41ebbb1baa06084131c8] awx.analytics.job_lifecycle job-83 post run
2023-05-26 16:15:03,885 INFO     [059fb68fa81c41ebbb1baa06084131c8] awx.analytics.job_lifecycle job-83 finalize run
2023-05-26 16:15:04,060 WARNING  [059fb68fa81c41ebbb1baa06084131c8] awx.main.dispatch job 83 (error) encountered an error (rc=None), please see task stdout for details.
Task was destroyed but it is pending!
task: <Task pending name='Task-715421' coro=<RedisConnection._read_data() done, defined at /var/lib/awx/venv/awx/lib64/python3.9/site-packages/aioredis/connection.py:180> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f7d5504f610>()]> cb=[RedisConnection.__init__.<locals>.<lambda>() at /var/lib/awx/venv/awx/lib64/python3.9/site-packages/aioredis/connection.py:168]>
Task was destroyed but it is pending!
task: <Task pending name='Task-715485' coro=<RedisConnection._read_data() done, defined at /var/lib/awx/venv/awx/lib64/python3.9/site-packages/aioredis/connection.py:180> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f7d5507ca90>()]> cb=[RedisConnection.__init__.<locals>.<lambda>() at /var/lib/awx/venv/awx/lib64/python3.9/site-packages/aioredis/connection.py:168]>
2023-05-26 18:58:57,964 INFO     [-] awx.main.wsrelay Starting producer for 10.42.2.138-schedules-changed
2023-05-26 18:59:07,968 INFO     [-] awx.main.wsrelay Producer 10.42.2.138-schedules-changed has no subscribers, shutting down.
```
</details>
</summary>

**Comment by mamercad** [comment]
> 

Different symptom than the original ticket, at least the logging seems intact:

```shell
❯ wc -l ~/Downloads/job_83.txt
   11919 /Users/mark/Downloads/job_83.txt
```

**Comment by mamercad** [comment]
> Just a quick update, I'm testing this on 22.3.0, I'll report back (same setup, single cluster, same namespace).

I'm going to hide the unrelated comments. Need to get more formal about replicating this.

**Comment by mamercad** [comment]
For the new "Job terminated due to error" that I'm seeing on 22.3.0, I opened #14057.

**Comment by tparker00** [comment]
I was able to reproduce this in my home environment as well.
k8s: 1.24.8
awx: 22.3.0

I just deployed it yesterday using operator 2.2.1

Only thing I changed with the deployment was to specify the `image_version` for awx, everything else is as the operator sets it up by default

When I download the job output a simple `wc -l` shows way less lines than the 16k I would have expected as well (around 7k) 
![Screenshot 2023-06-02 at 3 01 21 PM](https://github.com/ansible/awx/assets/2592584/94d5a4af-c4fd-4e77-b546-a34e047b2210)

**Comment by mamercad** [comment]
I'm testing this version, 21.11.14, with the resolution in #14057 to see if they do the trick for this version as well.

**Comment by mamercad** [comment]
> I'm testing this version, 21.11.14, with the resolution in #14057 to see if they do the trick for this version as well.

Seems good, going to close this (10k lines worked just fine):

```shell
❯ wc -l ~/Downloads/job_126.txt
   10019 /Users/mark/Downloads/job_126.txt
```
