### ISSUE TITLE
RFE: Project View list should have Organization column

### ISSUE THREAD

**Issue by dhartford** [ansible/awx#1400]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
When setting up projects, you map it to one (and possibly many) organizations.  However the list view does not show the Organization similar to the Inventory list view. 

Desire to have Organization column in the Project list view for faster review on that page.

**Comment by wenottingham** [comment]
https://tower-mockups.testing.ansible.com/mockups/projects/projects/

**Comment by mabashian** [comment]
We show the organization in the expanded view of a project row now:

<img width="1454" alt="Screen Shot 2021-07-01 at 3 35 50 PM" src="https://user-images.githubusercontent.com/9889020/124180379-181ba280-da82-11eb-950d-696222375812.png">
