### ISSUE TITLE
Allow Jobs to run against disabled hosts

### ISSUE THREAD

**Issue by disi** [ansible/awx#14014]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

At the moment it always returned an empty host_list by AWX, if you try to target disabled hosts from inventories.
I tried specifying limits/filters in the Ansible role, but it doesn't help, because AWX pre-filters all disabled hosts from inventories before the Ansible role is run.

It would be great to use the AWX database to source hosts that are in disabled state, for reports or usage of external APIs like Park my Cloud.

I suggest to add this to the template GUI, to ignore host check.

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

Run a template against an inventory with disabled hosts.

### Current results

WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'
[WARNING]: Could not match supplied host pattern, ignoring: A000022PTLE03
PLAY [all] *********************************************************************
skipping: no hosts matched

### Sugested feature result

Return the host, even though it is disabled, so the hosts attributes can be used in the Ansible role.

### Additional information

We use the Azure powerstate variable to determine if a host should be en- or disabled in the inventory.
I created a smart inventory to only contain disabled hosts and a role to use the Park My Cloud API to wake them.
The template would only use the hosts "name" attribute for this, but it can never find any hosts, due to it's disabled state.

**Comment by djyasin** [comment]
Hi @disi,
We would like to gather a bit more information from you. Could you please elaborate a bit regarding the disabled hosts you have described? Can you explain the use case a little more?  To clarify, disabling hosts in awx tells awx not to use those hosts when running jobs. Therefor, your running jobs will not have access to those hosts.

**Comment by mabashian** [comment]
@disi this is an interesting idea, thanks for suggesting it!  As Lila stated, running jobs against disabled hosts is sort of counterintuitive to the current solution from a user experience perspective.  We're unlikely to implement this particular solution at this time but we'll take this into consideration if we think about giving more granular control over the hosts that get automated against.

**Comment by disi** [comment]
Hello,
I use AWX to index all hosts on Azure in an inventory every 3 hours.
My idea was to then use the variable powerstate ==  'running' to determine
if a host should be enabled. If it is running, I can connect to it and
perform jobs.

We have an issue where users use Park my Cloud to park their servers
outside of our patch window.
I wanted to go over "disabled" hosts, grab their names in a job and use the
Park my Cloud API to unpark them, also toggle their power state for 2 hours
or so and then do the updates.
Since AWX does not return any disabled hosts and has no override to get
those in a job, I could not do this.

I have since changed the variable for enabled/disabled and have now all
hosts enabled again.
This means, I have to add to every other job a check if the host is
reachable or not rather than checking this during import.

It would also be useful to export data about hosts or run reports in the
future regardless if the host is 'running' or not.
If you could allow users to override this behaviour in a template, it would
be very useful.

Thanks,

Marcus

**Comment by Klaas-** [comment]
Hi,
our solution to this problem is to always have all hosts enabled that we want to operate on, and then we have groups for powered on/powered off/whatever powerstates that we use within job templates via limit. That seems to work fine for us :)
