### ISSUE TITLE
RFE: Job view list should have 'caller' user name column

### ISSUE THREAD

**Issue by dhartford** [ansible/awx#1401]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
The job list doesn't show who ran each job.  Desire to have the user that made the call (scheduled/automated calls could be a stock value, transitive calls could be 'called from <xyz> project' such as when updating SCM jobs).

**Comment by wenottingham** [comment]
https://tower-mockups.testing.ansible.com/mockups/jobs/jobs/

**Comment by mabashian** [comment]
We now show `Launched By` in the expanded row view of a job:

<img width="1407" alt="Screen Shot 2021-07-01 at 3 37 51 PM" src="https://user-images.githubusercontent.com/9889020/124180552-5a44e400-da82-11eb-8f6e-81f865c90f67.png">
