### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'awx' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by fs30000** [ansible/awx#14015]
##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - Other

##### SUMMARY

Error while installing AWX in docker.

##### ENVIRONMENT
* AWX version: 22.2.0
* AWX install method: developer environment
* AWX deployment target: docker
* Operating System: rocky linux 8.7
* Web Browser:

##### STEPS TO REPRODUCE

On a virgin Rocky Linux 8,7 instalation after installing docker and friends:

git clone -b 22.2.0 https://github.com/ansible/awx.git
cd awx
make docker-compose-build
COMPOSE_TAG=release_4.4  make docker-compose COMPOSE_UP_OPTS=-d

##### EXPECTED RESULTS

For containers to work

##### ACTUAL RESULTS

[log.txt](https://github.com/ansible/awx/files/11496735/log.txt)

**Comment by djyasin** [comment]
Hi  @fs30000,
If you are running `make docker-compose-build`
`COMPOSE_TAG=release_4.4 make docker-compose COMPOSE_UP_OPTS=-d`, could you try `devel` tag vs a specific release, and see if that resolves for you?

May we ask where you received the direction to tag release_4.4 specifically?

**Comment by fs30000** [comment]
> If you are running `make docker-compose-build`
> `COMPOSE_TAG=release_4.4 make docker-compose COMPOSE_UP_OPTS=-d`, could you try `devel` tag vs a specific release, and see if that resolves for you?

Ok, tried again on fresh Rocky Linux 8.8 install with the 22.3.0 release. It built the image and running ok now.


> May we ask where you received the direction to tag release_4.4 specifically?

My mistake, i thought COMPOSE_TAG was for something else. I'll read the docs more carefully next time :)

Case closed then.
