### ISSUE TITLE
AWX Community Meeting Agenda - Jun  2023

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#14016]
# AWX Office Hours

## Proposed agenda based on topics
* @fosterseth @tanganellilore will discuss https://github.com/ansible/receptor-collection/pull/35 and https://github.com/ansible/receptor-collection/pull/41
* @AlanCoding Code Health Initiative and call to action
* @TheRealHaoLiu Updated merge policy
* @thedoubl3j bullhorn announcement and meetup info
* @john-westcott-iv redo community day AWX presentation (time permitting)

## What

After a successful Contributor Summit in October, one of the bits of feedback we got was to host a regular time for the Automation Controller (AWX) Team to be available for your folks in the AWX Community, so we are happy to announce a new regular video meeting.

This kind of feedback loop is vital to the success of AWX and the AWX team wants to make it as easy as possible for you - our community - to get involved.

## Where & When
Our next meeting will be held on Tuesday, Jun th, 2023 at [1500 UTC](https://dateful.com/time-zone-converter?t=15:00&tz=UTC)

* [Google Meet](https://meet.google.com/vyk-dfow-cfi)
* Via Phone PIN: 842522378 [Guide](https://support.google.com/meet/answer/9518557)

This meeting is held once a month, on the second Tuesday of the month, at [1500 UTC](https://dateful.com/time-zone-converter?t=15:00&tz=UTC)

## How

Add one topic per comment in this GitHub issue

If you don't have a GitHub account, jump on [#awx:ansible.com](https://matrix.to/#/#awx:ansible.com) on Matrix and we can add the topic for you

## Talk with us

As well as the fortnightly video meeting you can join the Community (inc development team) on Matrix Chat.

* Matrix: [#awx:ansible.com](https://matrix.to/#/#awx:ansible.com) (recomended)
* libera.chat IRC: `#ansible-awx` (If you are already setup on IRC)

The Matrix & IRC channels are bridged, you'll just have a better experience on Matrix

## Links
[AWX YouTube Chanel](https://www.youtube.com/@ansible-awx)
[Previous Meeting](https://github.com/ansible/awx/issues/13836)
[Meeting recording](https://www.youtube.com/watch?v=OGetgVAwfFI)
[Next Meeting](https://github.com/ansible/awx/issues/14131)

See you soon!

**Comment by fosterseth** [comment]
I will discuss https://github.com/ansible/receptor-collection/pull/35
and
https://github.com/ansible/receptor-collection/pull/41

@tanganellilore you should also attend if you're available to talk about your work!

we'll mention the new ways in which receptor binaries are obtained for execution nodes
