### ISSUE TITLE
Windows WINRM Setup is not operational anymore

### ISSUE THREAD

**Issue by ashutoshc1234** [ansible/awx#14028]
##### ISSUE TYPE
 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME
Setting up a Windows Host[](https://docs.ansible.com/ansible/latest/os_guide/windows_setup.html#setting-up-a-windows-host)
WINRM setup script is not at all functional anymore. I had followed the guide in the past step by step and everything used to work. Now i see few additional steps and things doesn't really work anymore with following documents.

##### SUMMARY
Potential Bug after modifying the Powershell script for the WINRM setup on the windows host. 

##### ENVIRONMENT
Tried the Microsoft azure Windows 2016, 2010, 2019 and latest Windows too. Tried running step by step the process defined in the document and it is not working at all
Setting up a Windows Host[](https://docs.ansible.com/ansible/latest/os_guide/windows_setup.html#setting-up-a-windows-host)
##### STEPS TO REPRODUCE
You can follow the steps in any cloud windows host and things are breaking.
Setting up a Windows Host[](https://docs.ansible.com/ansible/latest/os_guide/windows_setup.html#setting-up-a-windows-host)

##### EXPECTED RESULTS
Things were supposed to bringup the HTTP listener and HTTP listener was also supposed to be working however it is not operational anymore.
##### ACTUAL RESULTS

HTTPS LISTENER DOES NOT COMESUP 

PS C:\Users\ashutmch> $username = "Administrator"
PS C:\Users\ashutmch>                                                                                                   PS C:\Users\ashutmch> (New-Object -TypeName System.Net.WebClient).DownloadFile($url, $file)
PS C:\Users\ashutmch> Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force
PS C:\Users\ashutmch>
PS C:\Users\ashutmch> &$file -Version 5.1 -Username $username -Password $password -Verbose
VERBOSE: 2023-05-20T21:03:20 - INFO - starting script
VERBOSE: 2023-05-20T21:03:20 - INFO - current and target PS version are the same, no action is required
VERBOSE: 2023-05-20T21:03:20 - INFO - clearing auto logon registry properties
PS C:\Users\ashutmch> winrm enumerate winrm/config/Listener
Listener
    Address = *
    Transport = HTTP
    Port = 5985
    Hostname
    Enabled = true
    URLPrefix = wsman
    CertificateThumbprint
    ListeningOn = 10.0.0.4, 127.0.0.1, ::1, fe80::6f37:9e2c:c8da:607f%6

PS C:\Users\ashutmch> winrm enumerate winrm/config/Listener
Listener
    Address = *
    Transport = HTTP
    Port = 5985
    Hostname
    Enabled = true
    URLPrefix = wsman
    CertificateThumbprint
    ListeningOn = 10.0.0.4, 127.0.0.1, ::1, fe80::6f37:9e2c:c8da:607f%6

PS C:\Users\ashutmch>
PS C:\Users\ashutmch>

**Comment by djyasin** [comment]
Hello @ashutoshc1234,
Your question seems to be about using Ansible, not about AWX. https://groups.google.com/g/ansible-project  and https://docs.ansible.com/ansible/latest/community/communication.html are the best places to visit for user questions about Ansible. Thanks!

**Comment by ashutoshc1234** [comment]
Well you guys need to fix the documentation what you have on the porat. I got my problem fixed however your document is not going to result in working code.
