### ISSUE TITLE
Add edit icon on job templates view

### ISSUE THREAD

**Issue by grahamneville** [ansible/awx#1403]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
For consistency there should be an edit icon on the job templates view

##### ENVIRONMENT
* AWX version: 1.0.4.31
* AWX install method: docker on linux
* Ansible version:  2.4.0.3

##### STEPS TO REPRODUCE

Add the edit icon on the job templates view
![image](https://user-images.githubusercontent.com/19539695/36811496-eba446da-1cc5-11e8-945b-cea060ffc6ef.png)

![image](https://user-images.githubusercontent.com/19539695/36811555-1e1770e2-1cc6-11e8-93a6-9e665eebd74f.png)

**Comment by wenottingham** [comment]
This is intentional currently - the title goes to details/edit. CC'ing UX

**Comment by mabashian** [comment]
Closing - the intent is for the user to click on the name of the resource to navigate to it's edit form
