### ISSUE TITLE
##[error]ERROR: Cannot parse 'tools/ansible/roles/dockerfile/templates/Dockerfile.j2:18:1' for if condition jinja2 in awx version21.14.0

### ISSUE THREAD

**Issue by pradeep-git23** [ansible/awx#14038]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### AWX version

21.14.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.14

### Operating system

ubuntu

### Web browser

Chrome

### Steps to reproduce

build the awx 

### Expected results

success

### Actual results

success 

### Additional information

na

**Comment by shanemcd** [comment]
I can't reproduce this. Please try on the most recent version of AWX. If you're still having a problem please open a new issue and fill out the template with the exact steps you took.
