### ISSUE TITLE
Could not find constructed inventories on tech preview

### ISSUE THREAD

**Issue by Jaapis** [ansible/awx#14037]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Adding a constructed inventory does not work from the tech preview web UI. It lands on "We could not find that page".

![image](https://github.com/ansible/awx/assets/9306551/8bce6aa2-f835-4df0-a984-0989fc2b482b)

### AWX version

4.4

### Select the relevant components

- [ ] UI
- [X] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.4

### Web browser

Firefox, Chrome

### Steps to reproduce

Accept the tech preview web UI when prompted.
Navigate to Inventories > Create inventory > Create constructed inventory

### Expected results

Constructed Inventory creation page would be displayed.

### Actual results

Error page is displayed, saying "We could not find that page".

### Additional information

Bug found during testathon

**Comment by mabashian** [comment]
Hey @Jaapis!  Thanks for filing this!  There's a lot of missing functionality in the tech preview compared to the existing ui.  Constructed inventories is one of those missing functions.  We should be showing a more informative message on that page but it will eventually be replaced by a functioning form.  We're tracking the remaining feature parity items internally at this time.
