### ISSUE TITLE
Personal Access Tokens are automatically removed once AWX's setting is configured such as DISABLE_LOCAL_AUTH: true and AUTH_BASIC_ENABLED: false with version 22.3.0.

### ISSUE THREAD

**Issue by laiminhtrung1997** [ansible/awx#14030]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Old version: 21.10.2.
PAT for user system can be get on UI or API.

New version: 22.3.0.
PAT for user system cannot be found on UI or API.

### AWX version

22.3.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Web browser

Firefox, Edge

### Steps to reproduce

Using ansible collection awx.awx for configure AWX.
Step 1: Create Personal Access Token (PAT) with ansible collection awx.awx.token.
Step 2: Setting AWX to SAML SSO configuration with ansible collection awx.awx.setting.

### Expected results

PAT for user system can be get on UI or API.

### Actual results

PAT for user system cannot be found on UI or API.

**Comment by djyasin** [comment]
Hi @laiminhtrung1997!
We would like to get a little bit more information from you.  Are you using user and password credentials with awx collection that belong to an external identity provider, such as SAML?

**Comment by laiminhtrung1997** [comment]
Dear @djyasin 
I have re-checked the flow and I found out that the PAT is removed after these setting is configured.
`DISABLE_LOCAL_AUTH: true`
`AUTH_BASIC_ENABLED: false`

> Hi @laiminhtrung1997! We would like to get a little bit more information from you. Are you using user and password credentials with awx collection that belong to an external identity provider, such as SAML?

I am not. I am using user and password basic auth of AWX with awx collection to create PAT.
