### ISSUE TITLE
Incorrect capacity for remote execution nodes

### ISSUE THREAD

**Issue by fosterseth** [ansible/awx#14051]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Incorrect reporting when task container resource limits are set (in k8s). We are scaling the CPU and Memory values by `SYSTEM_TASK_ABS_CPU`, even for execution nodes

https://github.com/fosterseth/awx/blob/5afdfb11351dca986d62c7ebbfc7438c55274449/awx/main/utils/common.py#L759

we need at least these two changes,

`def save_health_data`
and
`get_cpu_effective_capacity` (which is called by refresh_capacity_fields)

### AWX version

devel

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

add limits to your task container
```yaml
task_resource_requirements:
  requests:
    cpu: 250m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi
```

then add a remote execution node. The "cpu" and "memory" fields on the api/v2/instances endpoint are not correct.

### Expected results

execution node capacity should not be affected by SYSTEM_TASK_ABS_CPU

### Actual results

it is

**Comment by djyasin** [comment]
TODO: need a backport to 2.3 and 2.4

**Comment by djyasin** [comment]
PR: https://github.com/ansible/awx/pull/14315
