### ISSUE TITLE
Add an argument to control the API call frequency with --monitor or --wait

### ISSUE THREAD

**Issue by Flashh38** [ansible/awx#14064]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

I would like to propose the addition of a new argument in the AWX project to provide users with the ability to control the frequency of API calls when utilizing the --monitor or --wait options. Currently, these options trigger API calls every 0.25 seconds, which can lead to security alerts.

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Steps to reproduce

1. Launch a job using the AWX command-line interface.
2. Include the --monitor or --wait options in the command to enable monitoring or waiting for job completion.
3. Observe the API calls being made every 0.25 seconds.

### Current results

When using the AWX command-line interface with the --monitor or --wait options, the API calls are made every 0.25 seconds. This frequent API call behavior can trigger security alerts in certain environments.

### Sugested feature result

The proposed feature aims to introduce a customizable argument, such as --api-interval, that would allow users to define the desired interval between API calls when utilizing the --monitor or --wait options in AWX. By incorporating this feature, administrators would have the flexibility to adjust the frequency of API calls according to their specific environment requirements, thereby reducing the occurrence of security alerts and improving the overall user experience.

**Comment by AlanCoding** [comment]
@gamuniz @jay-steurer closing as resolved with https://github.com/ansible/awx/pull/14068
