### ISSUE TITLE
Inventory Vars from SCM

### ISSUE THREAD

**Issue by itdependsnetworks** [ansible/awx#1407]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY

SCM Access for inventory and specifically vars, not tied to project.

##### ENVIRONMENT
N/A

##### STEPS TO REPRODUCE

N/A

##### EXPECTED RESULTS

To allow the inventory from SCM to pull down not just inventory, but group and host vars via SCM. This allows normal CI/CD workflow for adding vars within all repo's that awx/tower is tied to. 

##### ACTUAL RESULTS

N/A

##### ADDITIONAL INFORMATION

This is an extension of the well documented feature: `Sourced from a Project`

**Comment by wenottingham** [comment]
Can you describe the layout of the repo you're expecting this with?

**Comment by itdependsnetworks** [comment]
Hopefully this is an ample enough description
```
inventory
group_vars/
   group1.yml
   group2.yml
   group3/
       vlans.yml
       interfaces.yml
host_vars/
   hostname1.yml
   hostname2.ym
   hostname3/
       vlans.yml
       interfaces.yml
```

**Comment by freehck** [comment]
+1, it would be useful to describe some specific host or group variables in the project repository.
I think that their priority must be higher than variables from awx inventory.

**Comment by onitake** [comment]
I think AWX already imports group_vars just fine. At least I can see default variables on the inventory and created groups that definitely come from group_vars.

I'm noticing something else though: Certain groups aren't detected at all, and consequently all the variables from these groups are missing. This could be a bug.

**Comment by itdependsnetworks** [comment]
@onitake can you verify that it does in relation to inventory? I have been unable to replicate. 

I see:
 - Working: Group/host vars in relation to project 
 - Working: Inventory from inventory from SCM
 - Not Working: group host vars in relation to project

**Comment by itdependsnetworks** [comment]
@onitake and @wenottingham anything else I can provide?

**Comment by onitake** [comment]
Can you be more specific what you mean with "group host vars in relation to project"?
With an example, perhaps?

**Comment by itdependsnetworks** [comment]
@onitake The only other way I can think to explain it is this:
Go to -> `INVENTORIES` -> `{{ your_inventory }}` -> `SOURCES` ->  `CREATE INVENTORY SOURCE`

Then set `SOURCE`, `INVENTORY FILE`, and `PROJECT`.

Then note that from: https://docs.ansible.com/ansible/2.5/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable none of the below will work.

```
inventory group_vars/all [3]
inventory group_vars/* [3]
inventory file or script host vars [2]
inventory host_vars/*
inventory host_vars/* [3]
```

**Comment by termlen0** [comment]
> I think AWX already imports group_vars just fine. At least I can see default variables on the inventory and created groups that definitely come from group_vars.
> 
> I'm noticing something else though: Certain groups aren't detected at all, and consequently all the variables from these groups are missing. This could be a bug.

I used the setting described in https://github.com/ansible/awx/issues/1966 to get the `group_vars` to populate from SCM.

**Comment by itdependsnetworks** [comment]
I see this working as expected now, and reflected in the tower documentation.
