### ISSUE TITLE
AWX deployment swarm documentation

### ISSUE THREAD

**Issue by bdoublet91** [ansible/awx#14084]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

Hi,
I use AWX 17.1.0 on docker Swarm (working well) and I want to upgrade to AWX 22.3.0. I understood all new architecture and I succeeded in deploy the new UI with 2 controller node with docker-compose deployment.
I also understood that new AWX version is using ansible-controller with podman container.

My last problem: Job can't executes on container awx controller node because of swarm doesnt allow containers (tasks) to do docker in docker or podman in docker.
For all podman command in awx controller node
```
cannot clone: Operation not permitted
Error: cannot re-exec process
```

Compare to docker-compose with --priviledged flag, swarm services doesnt support it, I tried this documentation:
https://www.redhat.com/sysadmin/podman-inside-container.

I saw in awx google groups that a lot of people have problem to deploy new AWX version with Orchestrator which is not Kubernetes and migrate to Kubernetes is not an option for a lot of company.

Solutions:
1. Use an external podman server and configure the AWX controller container to use it like DOCKER_HOST (I already did it for gitlab container)
On external podman server
```
podman system service --listen tcp://0.0.0.0:1234
```

On AWX controller container
```
export PODMAN_REMOTE_SOCKET=tcp://remote-server-ip:1234
```

2. Use ansible-controler in standalone mode without container
3. Other soluton but I didnt find anything else ...

Please help me on this one, I would be glad to share my swarm deployment when it will be ready.

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Steps to reproduce

cf feature summary

### Current results

cf feature summary

### Sugested feature result

cf feature summary

**Comment by fosterseth** [comment]
Unfortunately we don't have plans to support docker Swarm. The only officially supported deployment of AWX is through the awx-operator -- let us know if you have questions about that deployment.

**Comment by bdoublet91** [comment]
Yeah I know how this github works. I use AWX since 3 years.
The only thing I ask is a clue or something to help me to continue my work. I spent two weeks to deploy the last version of AWX in swarm, only podman in docker is a problem here.
Even if you dont know how swarm works, you know what is possible to do with AWX deployment.

So please just tell me about my two questions:
1. Is it possibl to use an external podman server and configure the AWX controller container to use it like DOCKER_HOST (I already did it for gitlab container).
2.Is it possible to use ansible-controler in standalone mode without container ?
3. If you see another solution to make podman works in container without priviledge mode ?

Thanks again for your time
