### ISSUE TITLE
awx.awx.goup module does fail if preserve_existing_hosts is true and the group does not exist yet

### ISSUE THREAD

**Issue by disi** [ansible/awx#14102]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

awx.awx.goup module does fail if preserve_existing_hosts is true and the group does not exist yet

### AWX version

22.2

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

awx-ee:21.11.0

### Operating system

Linux

### Web browser

Chrome, Edge

### Steps to reproduce

Create an ansible playbook to add a group with preserve_existing_hosts: true. Example:
- name: add host to group "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}"
  awx.awx.group:
    inventory: existing_inventory
    controller_host: mycontroller
    controller_oauthtoken: mytoken
    name: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}"
    description: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}"
    validate_certs: false
    state: present
    preserve_existing_hosts: true
    preserve_existing_children: true
    hosts: "{{ inventory_hostname }}"
  delegate_to: localhost

### Expected results

If the group "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}" does not yet exist, it is created and the host "{{ inventory_hostname }}" is added to the group.
If the group "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}" does exist, the existing hosts in the group are preserved and the host "{{ inventory_hostname }}" is added.

### Actual results

If the group "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}" does not yet exist, the module crashes.
If the group "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}" does exist, the existing hosts in the group are preserved and the host "{{ inventory_hostname }}" is added.

### Additional information

Crash log:
{
  "module_stdout": "",
  "module_stderr": "Traceback (most recent call last):\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1686308130.883564-102-216899407513794/AnsiballZ_group.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1686308130.883564-102-216899407513794/AnsiballZ_group.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1686308130.883564-102-216899407513794/AnsiballZ_group.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.awx.awx.plugins.modules.group', init_globals=dict(_module_fqn='ansible_collections.awx.awx.plugins.modules.group', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_awx.awx.group_payload_lzr14bia/ansible_awx.awx.group_payload.zip/ansible_collections/awx/awx/plugins/modules/group.py\", line 184, in <module>\n  File \"/tmp/ansible_awx.awx.group_payload_lzr14bia/ansible_awx.awx.group_payload.zip/ansible_collections/awx/awx/plugins/modules/group.py\", line 173, in main\nTypeError: 'NoneType' object is not subscriptable\n",
  "exception": "Traceback (most recent call last):\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1686308130.883564-102-216899407513794/AnsiballZ_group.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1686308130.883564-102-216899407513794/AnsiballZ_group.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1686308130.883564-102-216899407513794/AnsiballZ_group.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.awx.awx.plugins.modules.group', init_globals=dict(_module_fqn='ansible_collections.awx.awx.plugins.modules.group', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_awx.awx.group_payload_lzr14bia/ansible_awx.awx.group_payload.zip/ansible_collections/awx/awx/plugins/modules/group.py\", line 184, in <module>\n  File \"/tmp/ansible_awx.awx.group_payload_lzr14bia/ansible_awx.awx.group_payload.zip/ansible_collections/awx/awx/plugins/modules/group.py\", line 173, in main\nTypeError: 'NoneType' object is not subscriptable\n",
  "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
  "rc": 1,
  "_ansible_no_log": false,
  "changed": false,
  "_ansible_delegated_vars": {
    "ansible_host": "localhost",
    "ansible_port": null,
    "ansible_user": "itadmin",
    "ansible_connection": "local"
  }
}

**Comment by fosterseth** [comment]
thanks for opening this ticket!

duplicate of https://github.com/ansible/awx/issues/11954

this was fixed here https://github.com/ansible/awx/pull/13913

should land in the next AWX release
