### ISSUE TITLE
docker-compose-build  does not build. Wrong rsyslog version.

### ISSUE THREAD

**Issue by fs30000** [ansible/awx#14115]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

The docker build fails because rsyslog-8.2102.0-106.el9 is not on the centos stream 9 repo anymore.

Any reason why the build is done with that specific rsyslog version? Changing the rsyslog build version to 111, makes it build. 

### AWX version

22.3.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

docker development environment

### Modifications

no

### Operating system

Rocky9

### Steps to reproduce

git clone -b 22.3.0 https://github.com/ansible/awx.git 
cd awx/
make docker-compose-build

### Expected results

To build.

### Actual results

````
... snip...

#0 18.07   Verifying        : python3-six-1.15.0-9.el9.noarch                        6/8
#0 18.07   Verifying        : python3-systemd-234-18.el9.x86_64                      7/8
#0 18.07   Verifying        : systemd-libs-252-15.el9.x86_64                         8/8
#0 18.13
#0 18.13 Installed:
#0 18.13   dbus-libs-1:1.12.20-7.el9.x86_64
#0 18.13   dnf-plugins-core-4.3.0-8.el9.noarch
#0 18.13   python3-dateutil-1:2.8.1-6.el9.noarch
#0 18.13   python3-dbus-1.2.18-2.el9.x86_64
#0 18.13   python3-dnf-plugins-core-4.3.0-8.el9.noarch
#0 18.13   python3-six-1.15.0-9.el9.noarch
#0 18.13   python3-systemd-234-18.el9.x86_64
#0 18.13   systemd-libs-252-15.el9.x86_64
#0 18.13
#0 18.13 Complete!
#0 18.29 Failed to set locale, defaulting to C.UTF-8
#0 18.62 Failed to set locale, defaulting to C.UTF-8
#0 19.13 CentOS Stream 9 - BaseOS                         32 kB/s | 9.5 kB     00:00
#0 19.43 CentOS Stream 9 - AppStream                      42 kB/s |  10 kB     00:00
#0 20.40 CentOS Stream 9 - CRB                           6.5 MB/s | 5.4 MB     00:00
#0 23.83 Package openldap-2.6.2-3.el9.x86_64 is already installed.
#0 23.84 No match for argument: rsyslog-8.2102.0-106.el9
#0 23.85 Package vim-minimal-2:8.2.2637-20.el9.x86_64 is already installed.
#0 23.86 Error: Unable to find a match: rsyslog-8.2102.0-106.el9
------
Dockerfile.dev:82
--------------------
  81 |     # Install runtime requirements
  82 | >>> RUN dnf -y update && dnf install -y 'dnf-command(config-manager)' && \
  83 | >>>     dnf config-manager --set-enabled crb && \
  84 | >>>     dnf -y install acl \
  85 | >>>     git-core \
  86 | >>>     git-lfs \
  87 | >>>     glibc-langpack-en \
  88 | >>>     krb5-workstation \
  89 | >>>     nginx \
  90 | >>>     "openldap >= 2.6.2-3" \
  91 | >>>     postgresql \
  92 | >>>     python3-devel \
  93 | >>>     python3-libselinux \
  94 | >>>     python3-pip \
  95 | >>>     python3-psycopg2 \
  96 | >>>     python3-setuptools \
  97 | >>>     rsync \
  98 | >>>     rsyslog-8.2102.0-106.el9 \
  99 | >>>     subversion \
 100 | >>>     sudo \
 101 | >>>     vim-minimal \
 102 | >>>     which \
 103 | >>>     unzip \
 104 | >>>     xmlsec1-openssl && \
 105 | >>>     dnf -y clean all
 106 |
--------------------
ERROR: failed to solve: process "/bin/sh -c dnf -y update && dnf install -y 'dnf-command(config-manager)' &&     dnf config-manager --set-enabled crb &&     dnf -y install acl     git-core     git-lfs     glibc-langpack-en     krb5-workstation     nginx     \"openldap >= 2.6.2-3\"     postgresql     python3-devel     python3-libselinux     python3-pip     python3-psycopg2     python3-setuptools     rsync     rsyslog-8.2102.0-106.el9     subversion     sudo     vim-minimal     which     unzip     xmlsec1-openssl &&     dnf -y clean all" did not complete successfully: exit code: 1
make: *** [Makefile:572: docker-compose-build] Error 1
````

**Comment by john-westcott-iv** [comment]
Thanks for brining this up, we are actively working on it.

**Comment by arunsippygmail** [comment]
[root@cdff80be9201 /]# dnf info rsyslog
Last metadata expiration check: 0:04:50 ago on Sat Jun 17 18:25:00 2023.
Installed Packages
Name         : rsyslog
Version      : 8.2102.0
Release      : 115.el9
Architecture : x86_64
Size         : 2.5 M
Source       : rsyslog-8.2102.0-115.el9.src.rpm
Repository   : @System
From repo    : appstream
version of rsyslog is  rsyslog-8.2102.0-115.el9
Change this entry in the /home/awxuser/awx/tools/ansible/roles/dockerfile/templates/Dockerfile.j2
and then 'make docker-compose-build'

**Comment by fs30000** [comment]
> [root@cdff80be9201 /]# dnf info rsyslog Last metadata expiration check: 0:04:50 ago on Sat Jun 17 18:25:00 2023. Installed Packages Name : rsyslog Version : 8.2102.0 Release : 115.el9 Architecture : x86_64 Size : 2.5 M Source : rsyslog-8.2102.0-115.el9.src.rpm Repository : @System From repo : appstream version of rsyslog is rsyslog-8.2102.0-115.el9 Change this entry in the /home/awxuser/awx/tools/ansible/roles/dockerfile/templates/Dockerfile.j2 and then 'make docker-compose-build'

From what i see here in Issues, 106 is the last release that works, right?

**Comment by Korhm** [comment]
> > [root@cdff80be9201 /]# dnf info rsyslog Last metadata expiration check: 0:04:50 ago on Sat Jun 17 18:25:00 2023. Installed Packages Name : rsyslog Version : 8.2102.0 Release : 115.el9 Architecture : x86_64 Size : 2.5 M Source : rsyslog-8.2102.0-115.el9.src.rpm Repository : @System From repo : appstream version of rsyslog is rsyslog-8.2102.0-115.el9 Change this entry in the /home/awxuser/awx/tools/ansible/roles/dockerfile/templates/Dockerfile.j2 and then 'make docker-compose-build'
> 
> From what i see here in Issues, 106 is the last release that works, right?

106 seems to be the latest that can been started withtout root user.
Unfortenately, the pacakge is no more available for Centos9 steam since 2 days. See: https://github.com/ansible/awx/issues/13412#issuecomment-1597508333#14152 

I'm running devel version 21.11.0, but unable to upgrade to latest version because of this

**Comment by fs30000** [comment]
> > > [root@cdff80be9201 /]# dnf info rsyslog Last metadata expiration check: 0:04:50 ago on Sat Jun 17 18:25:00 2023. Installed Packages Name : rsyslog Version : 8.2102.0 Release : 115.el9 Architecture : x86_64 Size : 2.5 M Source : rsyslog-8.2102.0-115.el9.src.rpm Repository : @System From repo : appstream version of rsyslog is rsyslog-8.2102.0-115.el9 Change this entry in the /home/awxuser/awx/tools/ansible/roles/dockerfile/templates/Dockerfile.j2 and then 'make docker-compose-build'
> > 
> > 
> > From what i see here in Issues, 106 is the last release that works, right?
> 
> 106 seems to be the latest that can been started withtout root user. Unfortenately, the pacakge is no more available for Centos9 steam since 2 days. See: [#13412 (comment)](https://github.com/ansible/awx/issues/13412#issuecomment-1597508333)
> 
> I'm running devel version 21.11.0, but unable to upgrade to latest version because of this


Hum... then you just change the rsyslog line in  tools/ansible/roles/dockerfile/templates/Dockerfile.j2 to https://download.copr.fedorainfracloud.org/results/ansible/Rsyslog/epel-9-x86_64/06076718-rsyslog/rsyslog-8.2102.0-106.el9.x86_64.rpm

**Comment by x86txt** [comment]
> Hum... then you just change the rsyslog line in tools/ansible/roles/dockerfile/templates/Dockerfile.j2 to https://download.copr.fedorainfracloud.org/results/ansible/Rsyslog/epel-9-x86_64/06076718-rsyslog/rsyslog-8.2102.0-106.el9.x86_64.rpm

Thank you @fs30000 - this worked for me and the rest of the install completed successfully.

**Comment by Anvill1** [comment]
> > Hum... then you just change the rsyslog line in tools/ansible/roles/dockerfile/templates/Dockerfile.j2 to https://download.copr.fedorainfracloud.org/results/ansible/Rsyslog/epel-9-x86_64/06076718-rsyslog/rsyslog-8.2102.0-106.el9.x86_64.rpm
> 
> Thank you @fs30000 - this worked for me and the rest of the install completed successfully.

Can u write plz what exactly (which part of Dockerfile.j2) u change in tools/ansible/roles/dockerfile/templates/Dockerfile.j2?

**Comment by x86txt** [comment]
> > > Hum... then you just change the rsyslog line in tools/ansible/roles/dockerfile/templates/Dockerfile.j2 to https://download.copr.fedorainfracloud.org/results/ansible/Rsyslog/epel-9-x86_64/06076718-rsyslog/rsyslog-8.2102.0-106.el9.x86_64.rpm
> > 
> > 
> > Thank you @fs30000 - this worked for me and the rest of the install completed successfully.
> 
> Can u write plz what exactly (which part of Dockerfile.j2) u change in tools/ansible/roles/dockerfile/templates/Dockerfile.j2?

Hi @Anvill1 -

Change line 125 to this:

> https://download.copr.fedorainfracloud.org/results/ansible/Rsyslog/epel-9-x86_64/06076718-rsyslog/rsyslog-8.2102.0-106.el9.x86_64.rpm \

Here is a screenshot where I commented line 125 out and added the RPM as line 126:

![image](https://github.com/ansible/awx/assets/34278354/99594dd9-a527-41e4-bf4d-bfe2d0bfa75b)

**Comment by dfarkas77** [comment]
> > > > [root@cdff80be9201 /]# dnf info rsyslog Last metadata expiration check: 0:04:50 ago on Sat Jun 17 18:25:00 2023. Installed Packages Name : rsyslog Version : 8.2102.0 Release : 115.el9 Architecture : x86_64 Size : 2.5 M Source : rsyslog-8.2102.0-115.el9.src.rpm Repository : @System From repo : appstream version of rsyslog is rsyslog-8.2102.0-115.el9 Change this entry in the /home/awxuser/awx/tools/ansible/roles/dockerfile/templates/Dockerfile.j2 and then 'make docker-compose-build'
> > > 
> > > 
> > > From what i see here in Issues, 106 is the last release that works, right?
> > 
> > 
> > 106 seems to be the latest that can been started withtout root user. Unfortenately, the pacakge is no more available for Centos9 steam since 2 days. See: [#13412 (comment)](https://github.com/ansible/awx/issues/13412#issuecomment-1597508333)
> > I'm running devel version 21.11.0, but unable to upgrade to latest version because of this
> 
> Hum... then you just change the rsyslog line in tools/ansible/roles/dockerfile/templates/Dockerfile.j2 to https://download.copr.fedorainfracloud.org/results/ansible/Rsyslog/epel-9-x86_64/06076718-rsyslog/rsyslog-8.2102.0-106.el9.x86_64.rpm

Thanks a lot, very useful. Solved my problem.
