### ISSUE TITLE
[hop_node] adjust validation logic to use "==" rather than "in"

### ISSUE THREAD

**Issue by thedoubl3j** [ansible/awx#14121]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

@relrod raised an issue around how we are validating an instance is a control type in regards to the specific syntax. 

### AWX version

devel

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

n/a

### Operating system

n/a

### Steps to reproduce

Bug currently not reproducible due to how the tuple is defined.  

### Expected results

`if node_type in (Instance.Types.CONTROL):` to be written as `if node_type == Instance.Types.CONTROL:` 

### Actual results

`if node_type in (Instance.Types.CONTROL):`

### Additional information

will also need to look through the rest of the feature branch to make sure we aren't doing this other places.

**Comment by fosterseth** [comment]
fixed in https://github.com/ansible/awx/pull/14132
