### ISSUE TITLE
The AWX "awx-operator-instance" is invalid: spec.no_log: Invalid value: "boolean": spec.no_log in body must be of type string: "boolean"

### ISSUE THREAD

**Issue by SigntriggerLabs** [ansible/awx#14138]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

I'm trying to upgrade AWX from version 21.2.0 to next minor release - 21.3.0 (target to reach the n-1 version eventually in next few weeks)
But getting an error in awx-instance deployment:
"The AWX "awx-operator-instance" is invalid: spec.no_log: Invalid value: "boolean": spec.no_log in body must be of type string: "boolean"
"

Below is the content of awx-operator-instance.yaml

apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-operator-instance
spec:
  image: quay.io/ansible/awx
  image_version: 21.3.0
  hostname: <<value>>
  postgres_configuration_secret: <<secret_name>>
  admin_user: <<user>>
  service_type: ClusterIP
  ldap_cacert_secret: <<cert>>
  bundle_cacert_secret: <<cert>>
  ingress_type: ingress
  ingress_tls_secret: <<secret>>
  admin_password_secret: <<secret>>
  secret_key_secret: <<secret>>
  ee_pull_credentials_secret: <<secret>>
  extra_settings:
    - setting: MIDDLEWARE
      value: "['corsheaders.middleware.CorsMiddleware'] + MIDDLEWARE"
    - setting: CORS_ORIGIN_ALLOW_ALL
      value: "True"
  task_resource_requirements:
    requests:
      cpu: "0.5"
      memory: "536870912"
    limits:
      cpu: "1"
      memory: "1073741825"
  web_resource_requirements:
    requests:
      cpu: "0.5"
      memory: "1073741824"
    limits:
      cpu: "1"
      memory: "2147483648"
  ee_resource_requirements:
    limits:
      cpu: "1.5"
      memory: "2147483648"
    requests:
      cpu: "0.25"
      memory: "536870912"

The operator has been deployed using instructions from github page and it deploys okay. Problem is with AWX instance only

### AWX version

21.2.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

Once operator is deployed (0.24.0), just take the above content, put into a YAML file and try to deploy using kubectl. 

### Expected results

Deployment would happen just okay

### Actual results

Error being presented:
The AWX "awx-operator-instance" is invalid: spec.no_log: Invalid value: "boolean": spec.no_log in body must be of type string: "boolean"

**Comment by djyasin** [comment]
Hello @deep7861,
Could you give us the yaml of the object?  You can use `kubctl get awx  awx-operator-instance -o yaml` to gather that information.

**Comment by SigntriggerLabs** [comment]
@djyasin Thank you.
Attaching the file (existing deployment: 21.2.0). (Have removed the Azure pipeline annotations & hidden the value of hostname.)
[awx-operator-instance.txt](https://github.com/ansible/awx/files/11819914/awx-operator-instance.txt)

**Comment by SigntriggerLabs** [comment]
Hello, Is there a way to get updates on this one?

**Comment by SigntriggerLabs** [comment]
I happened to delete the AWX instance and redeploy and it worked fine. Was able to upgrade to next minor version as well. 
Issue is not reproducible anymore. Don't know where that setting of no_log: true came in to existing instance.
