### ISSUE TITLE
installation failing: unable to access fdisk

### ISSUE THREAD

**Issue by smrutikanta** [ansible/awx#1413]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
1st time installation on rhel 7 box. Unable to perform installation. While running the playbook getting the below error 

Error pulling ansible/awx_web - code: None message: failed to register layer: ApplyLayer exit status 1 stdout:  **stderr: open /usr/sbin/fdisk: permission denied**

##### ENVIRONMENT
* AWX install method: docker on linux
* Ansible version:  2.4.1.0
* Operating System: linux
* Web Browser: chrome

##### STEPS TO REPRODUCE

run the install.yml
cmd to run the playbook: **ansible-playbook -i inventory install.yml**

##### EXPECTED RESULTS

The installation should have gone fine without any issues
Expected output:

##### ACTUAL RESULTS
TASK [local_docker : Activate AWX Web Container] ********************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error pulling ansible/awx_web - code: None message: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: open /usr/sbin/fdisk: permission denied"}
        to retry, use: --limit @/root/awx/installer/install.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=9    changed=0    unreachable=0    failed=1

##### ADDITIONAL INFORMATION

I have tried to do a dockerpull to pull the image
docker pull ansible/awx_web
which gives the below error:
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: open /usr/sbin/fdisk: permission denied

**Comment by wenottingham** [comment]
Your `docker_container` module or docker installation is somehow broken; this is not an AWX issue.
