### ISSUE TITLE
Installation Path for Non K8s/Container Environment

### ISSUE THREAD

**Issue by darthVikes** [ansible/awx#14154]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

Installation Path for Non K8s/Container Environment. Would like to see a binary/rpm based installation

### Select the relevant components

- [X] UI
- [X] API
- [X] Docs
- [X] Collection
- [X] CLI
- [X] Other

### Steps to reproduce

NA

### Current results

NA

### Sugested feature result

rpm/repo to update code from via yum/dnf

**Comment by djyasin** [comment]
@darthVikes thank you for taking the time to create an issue. We currently do not offer rpm-based installation and do not have plans to support this in the future. If you need assistance with your environment, we would recommend reaching out on our mailing list. You can do that here: https://groups.google.com/g/awx-project 

We appreciate your time and have a great day!
