### ISSUE TITLE
Notification Templates | support querying on job_metadata 

### ISSUE THREAD

**Issue by gannaramu** [ansible/awx#14150]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

it would be nice to have the ability to query the job_metadata to either tag the user who created the ticket on mattermost. 

i currently see that feature is not supported
```
At the present time, you cannot query individual fields within {{ job_metadata }}. When using {{ job_metadata }} in a notification template, all data will be returned.
```

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

API sends a 400 when we try to query

### Current results

cannot query job_metadata

### Sugested feature result

support templating using job_metadata example {{ job_metadata.created_by }}

**Comment by djyasin** [comment]
Hello @gannaramu, we are happy to help! We do support this and currently have some documentation surrounding this. You can view that documentation here:
 https://docs.ansible.com/automation-controller/latest/html/userguide/notification_parameters_supported.html

Once on that page, scroll down to created_by. 

Please let us know if this resolves this issue for you.

**Comment by gannaramu** [comment]
the link on the customize notification page takes me to https://docs.ansible.com/automation-controller/latest/html/userguide/notifications.html#create-custom-notifications and there i see the warning and carried away by it. i think we should point that link to the page you sent it has more useful information or club them.
Thanks for the pointer 
```@{{ job.summary_fields.created_by.username }}``` solved it for me
![image](https://github.com/ansible/awx/assets/12237488/50d3e922-7633-421d-b60c-e632d9a56d05)

![image](https://github.com/ansible/awx/assets/12237488/cb1de796-8656-49e3-b389-90bd86d505f0)
