### ISSUE TITLE
OAuth2 Application client_secret is not encrypted in the database

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/awx#1416]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY
Application client_secret is not encrypted in the database.  

##### ENVIRONMENT
* AWX version: 1.0.4.31
* AWX install method: docker on linux
* Ansible version: 2.4.0.3

##### STEPS TO REPRODUCE

1. exec into the awx container
2. do a SELECT on main__oauth2application
3. see client_secret field in plain text

##### EXPECTED RESULTS

Expect that django-oauth-toolkit would encrypt this by default. 

##### ACTUAL RESULTS

The client_secret is shown in plain text.  

##### ADDITIONAL INFORMATION

To fix, the application model we will have to override the application model.

**Comment by ryanpetrello** [comment]
Looks like we'll have to solve this ourselves given the response in: https://github.com/evonove/django-oauth-toolkit/issues/276

**Comment by rooftopcellist** [comment]
On the first pass, I will censor the `client_secret` from the ActivityStream.  Do we want to handle client_secrets like token values (only show their value on creation)?  It looks like other developers have handled this either way.  GitHub for example shows their `client_secret` and `client_id` when the user is logged in, _not_ just on creation.

**Comment by ghjm** [comment]
@rooftopcellist If the fix is merged, should this be closed now?

**Comment by rooftopcellist** [comment]
@ghjm It is not, that was a preliminary PR to hide the client_secret in the serializer, it does not yet encrypt it in the db.  This needs to remain open.

**Comment by ryanpetrello** [comment]
Resolved downstream.
