### ISSUE TITLE
Double-clicking the "Launch" button creates two Jobs

### ISSUE THREAD

**Issue by flxbwr** [ansible/awx#14187]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

If the user accidentally double clicks the "Launch" button of a Job Template, two jobs may be started. This is not an expected behavior and is not a natural user experience.

This bug has already been solved by you two times and now is actual again.
It is well described:
https://github.com/ansible/awx/issues/11633

I looked through the changelog from 21.10.2 to the latest version (22.4.0) and didn't find fix.

### AWX version

21.10.2

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.15.0rc2

### Operating system

Windows 10

### Web browser

Firefox

### Steps to reproduce

1. Open the "Templates" page.
2. Click one of the following repeatedly at high speed.
        - Launch icon on the list of the Job Templates page
        - Launch button on the Details page of the Job Template.
        - Launch button on the Propmt if some "Prompt on launch" stuff is enabled for the Job Template

### Expected results

Only one Job will be created.

### Actual results

Two or more Jobs will be created at the same time.

**Comment by djyasin** [comment]
@mabashian do you know if this bug was addressed between 21.10.2 and the current version? If so, do you think this bug could be resolved via upgrading?

**Comment by flxbwr** [comment]
I updated to actual 22.5.0 and the problem is still present.

**Comment by mabashian** [comment]
This should be addressed with https://github.com/ansible/awx/pull/14407

**Comment by flxbwr** [comment]
> This should be addressed with #14407

@mabashian, Thanks for the answer!
