### ISSUE TITLE
Launch Job popup closes on credential change

### ISSUE THREAD

**Issue by rchaud** [ansible/awx#14185]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

It seems if we use the search parameter in Templates to search for a template example https://awx-demo.localhost/#/templates?template.name__icontains=yumrepos right when we change the credential during the pop up window the popup closes and url changes back to https://awx-demo.localhost/#/templates 

Seems to be a similar issue like https://github.com/ansible/awx/issues/9218 

My guess is that https://github.com/ansible/awx/blob/86f6b54eec6758f618e5cb6d922f7ff508d75462/awx/ui/src/components/LaunchPrompt/steps/CredentialsStep.js#L177C14-L177C47 is causing the url to be clear and the popup to close.

### AWX version

21.14.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Operating system

Kubernetes

### Web browser

Chrome

### Steps to reproduce

Go to Templates
Search for a Template
Launch the Template using the Rocket icon
Change the Credential Type in the Credentials tab

### Expected results

When we change the Credential Type, the popup should not close.

### Actual results

Popup closes as soon as we change the Credential Type.

**Comment by rchaud** [comment]
Actually, it seems there is a fix, the version I am using might not have that fix. I will test out upgrade to see how it goes.

**Comment by fosterseth** [comment]
@chinochao were you able to test if this is still an issue on later versions?

**Comment by rchaud** [comment]
Yes, newer versions have the fix. I tested it and I do not see the bug.
