### ISSUE TITLE
Invalid time format when trying to add schedule

### ISSUE THREAD

**Issue by mzac** [ansible/awx#14197]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

When trying to add a schedule to a task and choosing the time I get an error:

![image](https://github.com/ansible/awx/assets/10270879/14ecd2e2-2651-45cf-879c-fe2df3da403b)

### AWX version

22.4.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

Setup a schedule, choose daily then choose the any time and then you get the error

### Expected results

Should not get an error

### Actual results

Cannot create the schedule

**Comment by MSULS-sys** [comment]
I have encountered the same problem after installing a new server with k3s AWX 22.4.0 on AlmaLinux 8 when configuring scheduled jobs

**Comment by Radins** [comment]
I've found the same problem in a fresh install. I installed AWX on another cluster about a month ago and there works fine, so i think it may be something with the new version.

**Comment by mabashian** [comment]
@mzac thanks for raising this one!  I rolled back https://github.com/ansible/awx/pull/14086 locally and it seems like the issue went away.  I suspect an upstream change to one of our dependencies (Patternfly) may be causing this bug.

**Comment by trevorl-dtl** [comment]
Any temporary workaround for this issue? It's actually quite disappointing something this obvious wasn't caught earlier.

**Comment by LarsMde** [comment]
Do not change the time or create the scheduled job at the time you want it to run.

**Comment by mabashian** [comment]
#14206 contains the fix and has been merged.  Will go out in the next release.  If you need the fix sooner you can pull down the head of the devel branch.  Quickest workaround would be to interact directly with the api via the api web browser or cli.
