### ISSUE TITLE
Smart Inventory filter documentation

### ISSUE THREAD

**Issue by mkempster22** [ansible/awx#1419]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME
 - UI

##### SUMMARY
Documentation link inside the smart host inventory filter is broken

##### ENVIRONMENT
* AWX version: 1.0.4.14
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: RHEL7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Open up the Smart Inventory filter and click the 'Key' button, at the bottom of the key there is a link to syntax documentation that doesn't work:

http://docs.ansible.com/ansible-tower/1.0.4.14/html/userguide/search_sort.html

If the /1.0.4.14/ is changed to /latest/ it works

http://docs.ansible.com/ansible-tower/latest/html/userguide/search_sort.html

**Comment by ghjm** [comment]
We don't have docs for AWX versions, so I guess docs links always needs to go to latest when running in AWX.
