### ISSUE TITLE
Add support for sesu become method

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#1420]
because some people are already assuming we support it...

https://github.com/ansible/ansible/pull/27376/files#diff-f5b4ed56691a28c106adf759d95de084L128

**Comment by matburt** [comment]
This might be as simple as adding it to our constants list if it's supported in core

**Comment by wenottingham** [comment]
Marking as blocked until it's *actually* merged upstream: https://github.com/ansible/ansible/pull/27376/

**Comment by AlanCoding** [comment]
@wenottingham this issue will soon be made obsolete by https://github.com/ansible/awx/issues/2630.

Feel free to close.
