### ISSUE TITLE
There is no way to set credential for job templates using REST api

### ISSUE THREAD

**Issue by thakee-kochasoft** [ansible/awx#14203]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

Using the [AWX REST api](https://docs.ansible.com/ansible-tower/latest/html/towerapi/api_ref.html) There is no way to set an existing credential for a job template. And I would like to have this feature.

![Screenshot 2023-07-05 175544](https://github.com/ansible/awx/assets/113889842/809e5953-4564-459c-bbfa-b2044f9d3427)

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

In the api documentation https://docs.ansible.com/ansible-tower/latest/html/towerapi/api_ref.html there isn't any endpoints to set an existing credential to a template.

### Current results

N/A

### Sugested feature result

Add an endpoint or modify existing job_template point to support this feature

**Comment by relrod** [comment]
From your link:

![image](https://github.com/ansible/awx/assets/43930/494e3958-c812-4de3-875d-5130ae9879cc)

will this do what you are looking for?

**Comment by thakee-kochasoft** [comment]
@relrod This will create a new credential but I don't see any way to use an existing credential? can you find some way to do that?

**Comment by kurokobo** [comment]
See this section from @relrod;
![image](https://github.com/ansible/awx/assets/2920259/970534eb-f2cf-4e93-b6c6-d2148ab98c86)

**Comment by thakee-kochasoft** [comment]
@kurokobo Thanks a lot and it was my bad, didn't understand the docs properly.

**Comment by kodkurdu** [comment]
Hi,
Is there any way to change or remove avaiable job template credential by rest api?

**Comment by relrod** [comment]
@kodkurdu Please reach out on our [community forum](https://forum.ansible.com/) to ask support questions. :)
