### ISSUE TITLE
Not able to get the web access 

### ISSUE THREAD

**Issue by Fayaz305** [ansible/awx#14213]
[Installation & Deployment logs.txt](https://github.com/ansible/awx/files/11974756/Installation.Deployment.logs.txt)

Hi Everyone,

Please find installation steps and the output as well as logs of awx installation. Can you please help me with understand, where I did mistake or what steps need to be taken, any further ports need to be opened.

Thanks,
Shaik

**Comment by relrod** [comment]
Hello, this appears to be less of a bug report or feature request and more of a question. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.
