### ISSUE TITLE
the tech preview of the new Ansible AWX user interface does not display(Oops... Looks like the UI Next wasn't properly built

### ISSUE THREAD

**Issue by anouaressa** [ansible/awx#14214]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

when a click the link to see the tech preview of the new Ansible AWX user interface a screen with tech preview of the new Ansible AWX user interface dose not diplay

<img width="960" alt="Capture" src="https://github.com/ansible/awx/assets/89299571/76924f25-0544-49a9-9dbd-526f8cefe10f">
after clicking on the link  the next screen display:
<img width="638" alt="3" src="https://github.com/ansible/awx/assets/89299571/c822f8ac-10ce-464e-ba77-72803fc36c5e">

### AWX version

22.4.0

### Select the relevant components

- [ ] UI
- [x] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.10.8

### Operating system

Distributor ID: Ubuntu Description:    Ubuntu 22.04.2 LTS Release:        22.04 

### Steps to reproduce

new installation of awx 22.4.0 

### Expected results

navigate to tech preview ui 

### Actual results

tech preview ui dose not diplay 

### Additional information

when a click an the link the output of the console is :
tools_awx_1 | awx-uwsgi stderr | [pid: 394|app: 0|req: 15/108] 192.168.209.1 () {64 vars in 1153 bytes} [Fri Jul  7 16:16:50 2023] GET /ui_next/dashboard/ => generated 325 bytes in 115 msecs (HTTP/1.1 200) 9 headers in 437 bytes (1 switches on core 0)
tools_awx_1 | awx-uwsgi stderr |
tools_awx_1 | awx-uwsgi stderr | [pid: 394|app: 0|req: 16/109] 192.168.209.1 () {64 vars in 1153 bytes} [Fri Jul  7 16:16:51 2023] GET /ui_next/dashboard/ => generated 325 bytes in 69 msecs (HTTP/1.1 200) 9 headers in 437 bytes (1 switches on core 0)
tools_awx_1 | awx-uwsgi stderr |

**Comment by relrod** [comment]
You likely need to run `docker exec tools_awx_1 make ui-next`

We probably need to update the [dev env install doc](https://github.com/ansible/awx/blob/devel/tools/docker-compose/README.md#clean-and-build-the-ui)

**Comment by anouaressa** [comment]
wehn i try to run docker exec tools_awx_1 make ui-next 
i have the next result 
make: Nothing to be done for 'ui-next'.

**Comment by cigamit** [comment]
I get the same issue when attempting to build it.  

`make: Nothing to be done for 'ui-next'.`

**Comment by relrod** [comment]
Can you try with `clean/ui-next` before it?

`docker exec tools_awx_1 make clean/ui-next ui-next`

**Comment by cigamit** [comment]
While that does appear to build something now
```
<SNIP>
webpack 5.86.0 compiled with 2 warnings in 196607 ms
make[1]: Leaving directory '/awx_devel'
=== Copying awx/ui_next/src/build to awx/ui_next/build ===
=== Done building awx/ui_next/build ===
```


the Next UI itself throws an error when trying to access

![image](https://github.com/ansible/awx/assets/957322/f0dcab39-80d3-4877-bfee-7981bc391ce3)

**Comment by anouaressa** [comment]
when i try  docker exec tools_awx_1 make clean/ui-next ui-next or  docker exec tools_awx_1 make -B ui-next
=== Done building awx/ui_next/build ===
it's building but the same ui still exist

**Comment by cigamit** [comment]
You should be seeing a link on the dashboard to access the new UI
![image](https://github.com/ansible/awx/assets/957322/a539b759-c2a2-4ff2-81d0-a38a54a68576)
If not, there is a setting under Misc
![image](https://github.com/ansible/awx/assets/957322/3b661f94-ffcb-4a56-8240-699ef9f8449c)
You have to reload the browser after changing the setting also.

**Comment by cigamit** [comment]
@anouaressa 
There should be a link to the new UI on the dashboard, if its not there, check under the Misc settings to enable it (reload the browser after enabling the setting to get the link to the New UI to show up)

**Comment by anouaressa** [comment]
i have the link on the dashboard but wehn i click 
i have the next screen 
![image](https://github.com/ansible/awx/assets/89299571/51180001-cc0e-4a15-b9b6-782647bf852d)

**Comment by anouaressa** [comment]
I stop and start all containers  and i reload the browser it's work
