### ISSUE TITLE
Each AWX inventory has an underbar. How can I remove this?

### ISSUE THREAD

**Issue by sohwaje** [ansible/awx#14218]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary
I am automatically registering Azure's inventory.
Each AWX inventory has an underbar. How can I remove this?
<img width="552" alt="스크린샷 2023-07-10 오후 11 57 22" src="https://github.com/ansible/awx/assets/19942049/7a68d060-3024-4087-aca5-fc244a683074">

### AWX version

20

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

minikube

### Modifications

yes

### Operating system

Rocky Linux 8

### Web browser

Chrome

### Steps to reproduce

Each AWX inventory has an underbar. How can I remove this?

<img width="552" alt="스크린샷 2023-07-10 오후 11 57 22" src="https://github.com/ansible/awx/assets/19942049/b3cb9ba5-fd33-410b-95be-02502129b7f5">

### Expected results

I can remove underbar.

### Actual results

not anymore

**Comment by fosterseth** [comment]
Hello, this appears to be less of a bug report or feature request and more of a question. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.
