### ISSUE TITLE
Login Fails

### ISSUE THREAD

**Issue by MrMEEE** [ansible/awx#1423]
##### ISSUE TYPE
 - Bug Report
##### COMPONENT NAME
 - UI

##### SUMMARY
When trying to login to the webinterface it just hangs after pressing Sign In..

I get:

![screenshot_20180302_152825](https://user-images.githubusercontent.com/768031/36903574-723012ce-1e2e-11e8-8450-8f57598a3971.png)

##### ENVIRONMENT
* AWX version: 1.0.4.38
* AWX install method: RPM-based, I know this is not supported, but I hope you can point me in the right direction
* Operating System: CentOS
* Web Browser: Firefox/Chrome

**Comment by matburt** [comment]
The rpm install method isn't supported by us... you can seek help in the irc channel if you have development related questions.
