### ISSUE TITLE
[RFE] Verbosity: 5 in job_template module

### ISSUE THREAD

**Issue by mahoutukaisali** [ansible/awx#14234]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

Currently, job_template module has the `verbosity:` option which has only 0-4. However, AWX also has "5(WinRM Debug) mode so job_template module should be able to set 5 in `verbosity:`.

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

- Cannot create Job Template with verbosity: 5(WinRM Debug) in job_template module.

### Current results

- Cannot create Job Template with verbosity: 5(WinRM Debug) in job_template module.

### Sugested feature result

- Enable to set verbosity: 5(WinRM Debug) in job_template module.

**Comment by fosterseth** [comment]
should be resolved in the above PR
