### ISSUE TITLE
AWX kubernetes installation issue in setting.py

### ISSUE THREAD

**Issue by shen3lu4** [ansible/awx#1424]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
AWX Kubernetes installation successful with pods in running status. But there is an internal server error when trying to access AWX from a browser.

##### ENVIRONMENT
* AWX version: latest docker tag as of 3/1/2018
* AWX install method: kubernetes (installed using Oracle Container Services for use with Kubernetes) 
* Ansible version:  2.4.0.0
* Operating System: Oracle Enterprise Linux 7.4
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Follow the installation guide for kubernetes. Made changes to installer/inventory file to these two lines:
kubernetes_context=<context info>
 awx_kubernetes_namespace=<namespace info>
all other things remain the default.

##### EXPECTED RESULTS

AWX running with no errors.

##### ACTUAL RESULTS

The pods spun up successfully showing status Running in kubernetes cluster. But cannot access the AWX web site - getting an Internal Server Error on the web page. 
The logs in both awx_web and awx_celery containers show this error:
  File "/etc/tower/settings.py", line 16, in <module>
    CELERY_TASK_QUEUES += (Queue(CLUSTER_HOST_ID, Exchange(CLUSTER_HOST_ID), routing_key=CLUSTER_HOST_ID),)
NameError: name 'CELERY_TASK_QUEUES' is not defined

**Comment by a-nanasov** [comment]
Same here, @shen3lu4 try using images version 1.0.3
(set dockerhub_version=1.0.3 in your inventory file)

**Comment by shen3lu4** [comment]
using images v 1.0.3 works! thank you!

**Comment by cydvd** [comment]
Using `dockerhub_version=1.0.3`solved the problem also for me.
I'm using the release`1.0.4` of awx, deployed to an OpenShift cluster.

**Comment by Cryptophobia** [comment]
@cydvd  Thank you for the solution! Using 1.0.3 works for me as well!

**Comment by shanemcd** [comment]
Should be fixed after https://github.com/ansible/awx/pull/1446.
