### ISSUE TITLE
Unable to create schedule. "Create" button missing in UI

### ISSUE THREAD

**Issue by RobinR1** [ansible/awx#14256]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Using AWX 22.4.0 I bumped onto #14197 but as a fix (#14206) was merged 2 weeks ago, I figured it should be fixed in AWX 22.5.0 from last week. So I upgraded.
After the upgrade I wanted to retry creating a schedule which I failed to due to aforementioned bug, but I no longer find the "Create" button in the UI. I only see the "Delete" button.  And I find no option or possibility anymore in UI to create a new schedule.
I logged in with my personal account, which should have enough permissions. I also tried as admin user, where I see more schedules, but also no "Create" button.

### AWX version

22.5.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.15

### Operating system

SLES15SP4

### Web browser

Firefox

### Steps to reproduce

* Login to UI
* Ensure you have a template to run as a schedule
* Navigate to Schedules

### Expected results

Get a list of configured schedules and have an option to create a new schedule.

### Actual results

A list of configured schedules and only an option to Delete a schedule

**Comment by RobinR1** [comment]
As a workaround I was able to create a new schedule using the UI Tech Preview, which does display a "Create Schedule" button. I was unable to complete the configuration of the schedule as I did not find a way to set  limits on the scheduled playbook run using the Tech Preview. But I could save the schedule, then go back  to the classic UI where I could edit the new schedule and change it correctly.

**Comment by marshmalien** [comment]
@RobinR1 Thank you for reaching out! Are you trying to create a schedule from the top-level schedules list? Currently, we do not allow users to create schedules directly from the main schedules list view. We apologize for the inconvenience this may cause. However, we plan on exposing that option in the future UI Tech Preview.

Could you try creating a schedule from within a specific resource (template, project, etc)? 

You can find the more documentation about schedules here: https://docs.ansible.com/automation-controller/latest/html/userguide/scheduling.html#add-a-new-schedule

For the time being, I will go ahead and close this issue. If you're still encountering a bug after following the steps outlined in the documentation above, then please reach out to us and reopen this issue.
