### ISSUE TITLE
Allow domains with a single letter top level domain in the LDAP URL/Base URL Config

### ISSUE THREAD

**Issue by ghost** [ansible/awx#14270]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

Hi, we are stuck with a stupid domain with a single letter TLD due to horrible decisions. Due to that I cannot configure LDAP or the proper base URL of AWX :( 
Do you think it would be possible to allow single letter TLDs, despite them being non-conforming?
Love AWX, thanks for all of your work :)

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

Enter a URL with a single-letter TLD into the LDAP URL/Base URL fields, f.e. testserver.domain.i, and klick  "Save"

### Current results

AWX refuses to save the url with the error "Enter a valid URL"

### Sugested feature result

Allow domains with a single-letter TLD instead of disallowing them entirely

**Comment by kurokobo** [comment]
Refer to: https://github.com/ansible/awx/issues/12970#issuecomment-1261403643

**Comment by ghost** [comment]
> Refer to: [#12970 (comment)](https://github.com/ansible/awx/issues/12970#issuecomment-1261403643)

Thanks for the response! Yeah I'm aware that domains with one character are not valid :(  Sadly our domain won't change... So it'll stay the way it is?

**Comment by kurokobo** [comment]
I am not a member of AWX team so this is just an opinion, but it will probably remain the same as it is now.

I wouldn't recommend it, though, but as a (pretty dirty) workaround, you can create custom AWX image to remove this restriction by following `Dockerfile`.

```dockerfile
FROM quay.io/ansible/awx:22.5.0
USER root
RUN sed -i 's/2,63/1,63/g' /var/lib/awx/venv/awx/lib/python3.9/site-packages/awx/conf/fields.py
USER 1000
```

Build and push it to registry, then specify `image` and `image_version` in the AWX spec.

```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
...
spec:
  ...
  image: registry.example.com/ansible/awx
  image_version: 22.5.0-single-letter-tld
```

**Comment by ghost** [comment]
@kurokobo ohhh, thanks, that's cool! will try that probably :)
