### ISSUE TITLE
AWX fail when i send files from localhost to remote host

### ISSUE THREAD

**Issue by anouaressa** [ansible/awx#14309]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ansible/plugins/lookup/file.py", line 84, in run
    raise AnsibleOptionsError("file not found, use -vvvvv to see paths searched")
ansible.errors.AnsibleOptionsError: file not found, use -vvvvv to see paths searched
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ansible/plugins/action/template.py", line 152, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False, overrides=overrides)
  File "/usr/local/lib/python3.9/site-packages/ansible/template/__init__.py", line 1001, in do_template
    res = myenv.concat(rf)
  File "/usr/local/lib/python3.9/site-packages/ansible/template/native_

### AWX version

22.4.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.10.8

### Operating system

Distributor ID: Ubuntu Description:    Ubuntu 22.04.2 LTS Release:        22.04 Codename:       jammy awx@awx:~$

### Web browser

Chrome, Edge

### Steps to reproduce

try to copy file from the host machine to a target machine 

### Expected results

the copy of the file

### Actual results

The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ansible/plugins/lookup/file.py", line 84, in run
    raise AnsibleOptionsError("file not found, use -vvvvv to see paths searched")
ansible.errors.AnsibleOptionsError: file not found, use -vvvvv to see paths searched
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ansible/plugins/action/template.py", line 152, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False, overrides=overrides)
  File "/usr/local/lib/python3.9/site-packages/ansible/template/__init__.py", line 1001, in do_template
    res = myenv.concat(rf)
  File "/usr/local/lib/python3.9/site-packages/ansible/template/native_

### Additional information

even i try that  https://github.com/ansible/awx/issues/12518 it not work

**Comment by fosterseth** [comment]
keep in mind jobs are running in the awx ee container, does this file exist in that container?

**Comment by anouaressa** [comment]
no the file is not exist but how i can do that even the file not exist in container i see in https://github.com/ansible/awx/issues/12518 that we can share file from the host to the container but it not work for me ??

**Comment by fosterseth** [comment]
This appears to be less of a bug report or feature request and more of a question. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.
