### ISSUE TITLE
Job run resource links are all tooltiped as 'Edit the XYZ'

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1430]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

All resources linked off of a job run have tooltips of 'Edit the XYZ' (inventory, project, job template, etc.)

However, the user may not be able to edit them at all. 'View the XYZ' may be more appropriate.

##### ENVIRONMENT
* AWX version: 1.0.4.38

**Comment by jaredevantabor** [comment]
this is fixed now in devel
