### ISSUE TITLE
Implement documentation for how to implement custom inventory source

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#14303]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

Right now custom inventory scripts were deprecated and replaced with some undocumented black box mechanism. Please provide some documentation with steps and examples (and possibly screenshots from UI) that explain how we can convert our existing scripts to new model. There are only some very scarce information that can be found by googling over various open issues but no definitive documentation that actually exists.

### Select the relevant components

- [ ] UI
- [ ] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

N/A

### Current results

There is no documentation for this feature whatsoever

### Sugested feature result

Have a nice documentation for custom inventory scripts / plugins for dynamic inventories with screenshots and examples

### Additional information

best I found is https://docs.ansible.com/ansible-tower/3.8.6/html/administration/scm-inv-source.html#ag-inv-import but that doesn't really describe it at all, it just say that it's "possible" but doesn't explain how to achieve it

**Comment by benapetr** [comment]
I found this - https://github.com/ansible/awx/issues/8081 where @AlanCoding claims you can just create a .py script that would dynamically return inventory and put it as "inventory source", but when I did that it tried to parse that .py file using .ini inventory parser instead:

```
yaml declined parsing /runner/project/inventories/everything.py as it did not pass its verify_file() method
toml declined parsing /runner/project/inventories/everything.py as it did not pass its verify_file() method
[WARNING]:  * Failed to parse /runner/project/inventories/everything.py with
script plugin: problem running /runner/project/inventories/everything.py --list
([Errno 8] Exec format error: '/runner/project/inventories/everything.py')
  File "/usr/local/lib/python3.9/site-packages/ansible/inventory/manager.py", line 293, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/local/lib/python3.9/site-packages/ansible/plugins/inventory/script.py", line 150, in parse
    raise AnsibleParserError(to_native(e))
[WARNING]:  * Failed to parse /runner/project/inventories/everything.py with
ini plugin: /runner/project/inventories/everything.py:1: Expected key=value
host variable assignment, got: requests
  File "/usr/local/lib/python3.9/site-packages/ansible/inventory/manager.py", line 293, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/local/lib/python3.9/site-packages/ansible/plugins/inventory/ini.py", line 137, in parse
    raise AnsibleParserError(e)
[WARNING]: Unable to parse /runner/project/inventories/everything.py as an
inventory source
ERROR! No inventory was parsed, please check your configuration and options.
```

**Comment by fosterseth** [comment]
@benapetr looks like you're setting up the inventory source correctly, but your script itself is problematic, given the "exec format error line" 

So I would start with troubleshooting that, and making sure your script runs successfully outside of the AWX environment.

if you need further help, please go ahead and visit our mailing list https://groups.google.com/u/1/g/awx-project

**Comment by AlanCoding** [comment]
The core error you should pay attention to (given that you have a script) is:

> Failed to parse /runner/project/inventories/everything.py with
script plugin: problem running /runner/project/inventories/everything.py --list
([Errno 8] Exec format error: '/runner/project/inventories/everything.py')

Ansible core has no expectation that a script is python, it's just trying to execute it, and "Exec format error" is what it got when it did that.

**Comment by fosterseth** [comment]
this appears to be less of a bug report or feature request and more of a question. Closing for now

**Comment by lubouski** [comment]
Hi team, This is a shot guide on how to enable dynamic inventory plugin for AWX operator:
`awx version: "2.8.0"`
First you need a proper source code directories structure (which is synced with a help of projects in AWX):
```
$ tree
|-- ansible.cfg
|-- inventories
|   `-- test.yaml
`-- plugins
    `-- inventory
        `-- test.py
```
File `ansible.cfg` configures where `ansible-inventory` should look for `.py` inventory script.
```
$ cat ansible.cfg
[defaults]
inventory_plugins=./plugins/inventory
```
Inventory file `inventories/test.yaml` should be added to the `AWX` -> `Inventories` -> `Sources` -> Type: `Sourced from a Project` -> `Source details/Inventory file:` -> `inventories/test.yaml` -> `Save`
```
$ cat inventories/test.yaml
plugin: test
```
File `plugins/inventory/test.py` should have two parts, `def verify_file` and `def parse`, to fulfill script plugin requirement for options `--list` or `--host`:
```
#!/usr/bin/env python3
from ansible.plugins.inventory import BaseInventoryPlugin

class InventoryModule(BaseInventoryPlugin):
    NAME = 'test'

    def verify_file(self, path):
        valid = False
        if super(InventoryModule, self).verify_file(path):
            if path.endswith('yaml') or path.endswith('yml'):
                valid = True
        return valid

    def parse(self, inventory, loader, path, cache=True):
       super(InventoryModule, self).parse(inventory, loader, path, cache)
       '''Return dynamic inventory from source '''
       self._read_config_data(path)
       self.inventory.add_group("test_hosts")
       self.inventory.add_host(host="8.8.8.8", group="test_hosts")
```
To verify locally that this setup is working run following command:
```
$ ansible-inventory -i inventories/test.yaml --list
{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped",
            "test_hosts"
        ]
    },
    "test_hosts": {
        "hosts": [
            "8.8.8.8"
        ]
    }
}
```

**Comment by luflo66** [comment]
Good morning
Thank you for the documentation. I have a question about the test.yaml. I used to have the option of adding additional variables to the yaml file:
```
plugin: test
inventory_source: "dbname='pdb_p98_oiz' user='wikiadm' host='pcl_p998.global.szh.loc' port='5433'"
twrserver: tstm58281
```

When I define the additional variables, the error message appears:
Failed to parse /runner/project/inventories/test.yaml with yaml plugin: Plugin configuration YAML file, not YAML inventory

**Comment by lubouski** [comment]
Hey @luflo66, the purpose of dynamic inventory is to provide hosts values to the playbooks, dynamic inventory source them from python inventory plugin `plugins/inventory/test.py`: in this file you could add logic of adding `hosts`, `groups` and `variables`, additionally you could add variables to the AWX template directly. 
Please read about `set_variable` adds a variable to a group or host in inventory.: https://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html#inventory-object

**Comment by luflo66** [comment]
Hello Alex
Thank you very much for the quick reply.
The problem was actually not a problem. It was an error in the Python code. (Intentio Error)
Thanks again for taking the time.

_____________________________________________________________________________________________________________________________________________________________________

Freundliche Grüsse ⦾ Meilleures salutations ⦾ Cordiali saluti ⦾ Cun amiaivels salüds ⦾ Best regards ⦾ Saludos cordiales ⦾ наилучшими пожеланиями ⦾ 此致 ⦾ భవదీయులు

Beat Zürrer ⦾ Oberhofweg 6 ⦾ 8815 Horgenberg ⦾ +41 79 406 34 35
