### ISSUE TITLE
[constructed-inventory] Add option to modify the hostnames in a constructed inventory 

### ISSUE THREAD

**Issue by SimHeb** [ansible/awx#14310]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

Imagine a use case where we track a list of app servers in the inventory "app_servers":

app01.mycompany.domain
app02.mycompany.domain
app03.mycompany.domain

Now, we want to construct a secondary inventory from the inventory "app_servers" that contains the database servers for the corresponding app servers

db01.mycompany.domain
db02.mycompany.domain
db03.mycompany.domain

My proposal is to add a feature to the ansible.builtin.constructed plugin:

```
# inventory.config file in YAML format
plugin: ansible.builtin.constructed
strict: False
hosts: "{{ source_hosts | replace('app','db') }}
```

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs
- [X] Collection
- [X] CLI
- [ ] Other

### Steps to reproduce

1. Create a new Inventory in AWX and add multiple hosts to it
3. Create a constructed inventory in AWX and create a modifying statement in the source vars:
```
---
plugin: ansible.builtin.constructed
hosts: 
    name: "{{ inventory_hostname | replace ('kvh', 'bos')}}"
strict: true
use_vars_plugins: true
```

### Current results

The source hosts a simply taken over by the constructed inventory

### Sugested feature result

The source inventory_hostname variable should be updated with the modify statement

### Additional information

eventually this can be fulfilled already with another plugin.

**Comment by fosterseth** [comment]
@SimHeb thanks for the suggestion. This would an enhancement for **ansible core**, so go ahead and open an issue there instead https://github.com/ansible/ansible/issues

I'll close this one
