### ISSUE TITLE
Unable to Send a Mail with an attachemnt

### ISSUE THREAD

**Issue by ramachandra1234** [ansible/awx#14320]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Dears,

I have installed AWX version 17 on RHEL8

Here, awx_task container is responsible to send a email notification when playbook started/success/failure.

In one of our requirement is that the playbook is having a requirement to send an email with an attachment, playbook is executed successfully but not received an email with an attachment, where all the tasks are performed by awx_task container

But, not getting how awx_task container is sending a email notification when playbook started/failed or success

I’m attaching the docker-compose.yml file for reference, please review and help me to fulfill the above requirement (to send an email with an attachment)

[root@lenltrain1d01 awxcompose]# cat docker-compose.yml
version: '2'
services:
  web:
    image: ansible/awx:17.1.0
    container_name: awx_web
    depends_on:
      - redis
      - postgres
    ports:
      - "80:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "/var/lib/awx/awxcompose/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "/var/lib/awx/awxcompose/environment.sh:/etc/tower/conf.d/environment.sh"
      - "/var/lib/awx/awxcompose/credentials.py:/etc/tower/conf.d/credentials.py"
      - "/var/lib/awx/awxcompose/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/var/lib/awx/awxcompose/redis_socket:/var/run/redis/:rw"
      - "/var/lib/awx/projects:/var/lib/awx/projects:rw"
    environment:
      http_proxy:
      https_proxy:
      no_proxy:

  task:
    image: ansible/awx:17.1.0
    container_name: awx_task
    depends_on:
      - redis
      - web
      - postgres
    command: /usr/bin/launch_awx_task.sh
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "/var/lib/awx/awxcompose/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "/var/lib/awx/awxcompose/environment.sh:/etc/tower/conf.d/environment.sh"
      - "/var/lib/awx/awxcompose/credentials.py:/etc/tower/conf.d/credentials.py"
      - "/var/lib/awx/awxcompose/redis_socket:/var/run/redis/:rw"
      - "/var/lib/awx/projects:/var/lib/awx/projects:rw"
      - "/data:/data:rw"
    environment:
      POSTFIX_ENABLED: "1"
      AWX_SKIP_MIGRATIONS: "1"
      http_proxy:
      https_proxy:
      no_proxy:
      SUPERVISOR_WEB_CONFIG_PATH: '/etc/supervisord.conf'

  redis:
    image: redis
    container_name: awx_redis
    restart: unless-stopped
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - "/var/lib/awx/awxcompose/redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - "/var/lib/awx/awxcompose/redis_socket:/var/run/redis/:rw"

  postgres:
    image: postgres:12
    container_name: awx_postgres
    restart: unless-stopped
    volumes:
      - "/var/lib/awx/pgdocker/12/data/:/var/lib/postgresql/data:Z"
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      http_proxy:
      https_proxy:
      no_proxy:

volumes:
  supervisor-socket:
  rsyslog-socket:
  rsyslog-config:
[root@lenltrain1d01 awxcompose]#

Please assist me to send a mail with an attachment.

Thank you, Ramachandra

### AWX version

17

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

ansible [core 2.13.3]

### Operating system

RHEL8

### Steps to reproduce

If the mail agent information is provided in the installation doc would be much helpful

### Expected results

Playbook has to send an email with an attachment

### Actual results

Not received an email with an attachement

### Additional information

Installed to install postfix on awx_task container & tried to start postfix service, got the below error

bash-4.4# systemctl start postfix
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
bash-4.4#

**Comment by fosterseth** [comment]
Hello, this issue pertains to an older version of AWX. Try upgrading to the latest version and let us know if that resolves your issue.

**Comment by ramachandra1234** [comment]
Hi Seth Foster,

Thank you for your time and response.

Please provide me a doc/link to upgrade AWX version 17 to 19 or 20 or a link to install the latest AWX version.

I have tried to search the official document to install the latest AWX version but no luck.

It would be a great help if you provide the latest version installation doc or link or upgradation doc or link.

Thank you,
Ramachandra
