### ISSUE TITLE
Parallel jobs of the same project within a workflow interfere with each other

### ISSUE THREAD

**Issue by jimmydavies** [ansible/awx#1432]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
If you have a workflow that runs multiple jobs from the same project in parallel they will interfere with each others galaxy roles install. When each job kicks off it triggers a project scm full update which run ansible-galaxy install with a --force flag. 
https://github.com/ansible/awx/blob/5370c5e07d701bb4c97381a4969f818339f01db2/awx/playbooks/project_update.yml#L142
This --force flag will replace the roles in the project and if another job is already running through those roles certain files will go missing at the point the other jobs try to use them. I have mostly encountered this with template files (presumably because these are looked up as needed, where as other files are potentially looked up and evaluated when an the ansible-playbook command starts up).

##### ENVIRONMENT
* AWX version: 1.0.4.33
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: CentOS 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Create a project with two playbooks and a galaxy requirements.yml file in the roles directory
2. Add the project to AWX
3. Create two job templates from that project (one for each playbook)
4. Create a workflow that runs both job templates at the same time
5. Execute the workflow

##### EXPECTED RESULTS

The two job templates execute in parallel successfully

##### ACTUAL RESULTS

One of the two jobs fails due to the roles files being replaced after it started executing.

##### ADDITIONAL INFORMATION

The problem seems to be more pronounced as more jobs run in parallel in the workflow. Quite possibly there is a way of stopping the project from updating for each job template execution, I'm quite new to AWX and maybe there is something I'm missing

https://github.com/ansible/awx/blob/5370c5e07d701bb4c97381a4969f818339f01db2/awx/playbooks/project_update.yml#L142

**Comment by ryanpetrello** [comment]
@jimmydavies we've just released 1.0.7, which we believe resolves the underlying issue here. You can try it out here: https://github.com/ansible/awx/releases/tag/1.0.7

Let us know if you're still seeing this issue after installing the latest awx - thanks!
