### ISSUE TITLE
Job are showing successfull but not able to see live logs on awx

### ISSUE THREAD

**Issue by pradeep-git23** [ansible/awx#14321]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Triggered a job in AWX.
Job ended with status as success.
But no output is visible for logs on AWX

### AWX version

20.1.0.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.12

### Operating system

RHEL

### Steps to reproduce

trigger a job in awx.
wait for job to change the status from running to succesfull/failed
once job is updated their is no logs on awx output

### Expected results

see the job output on awx

### Actual results

output tab in awx is blank

**Comment by fosterseth** [comment]
Hello, this issue pertains to an older version of AWX. Try upgrading to the latest version and let us know if that resolves your issue.
