### ISSUE TITLE
Where we can find ansible.cfg in 22.5.0 AWX version ?

### ISSUE THREAD

**Issue by venkatasykam** [ansible/awx#14330]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Where we can find ansible.cfg in 22.5.0 AWX version ?

### AWX version

Default with awx 22.5.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

I would like to pass additional parameteters from ansible.cfg file

but I’m unable to find in awx wrb, tax etc

### Expected results

Shall I find ansible.cfg 

### Actual results

Ansible.cfg

**Comment by abcqwertz** [comment]
As far as I know you can just commit the ansible.cfg file in your playbook/roles repository and it will automatically be used by the execution environment.

**Comment by relrod** [comment]
As @abcqwertz points out, you can include it in your project, or embed it in a custom execution environment.

For community support, please [reach out on Matrix or the AWX mailing list](https://docs.ansible.com/ansible/latest/community/communication.html). We try to keep the issue tracker here for bugs and feature requests.
