### ISSUE TITLE
CredSSP Not 

### ISSUE THREAD

**Issue by tbHoosier** [ansible/awx#14337]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

I have setup CredSSP on my Windows 2019 servers and deployed playbooks to them using the Ansible CLI.  After installing AWX, and attempting to run the same playbooks I received an error message stating that credssp is not installed.  The documentation states that there is a machine type for Windows, but there is not.

### AWX version

22.6.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.15.2

### Operating system

Ubuntu Server

### Web browser

Firefox

### Steps to reproduce

Deployed AWX to Kubernetes cluster using the procedure:   https://computingforgeeks.com/how-to-install-ansible-awx-on-ubuntu-linux/?expand_article=1

Tested all components within the UI needed for playbook deployment.

### Expected results

After setting up the proper inventory, I expected AWX to utilize WINRM and CredSSP as outlined in several training classes and documents.

### Actual results

I received the following error:  

credssp: requests auth method is credssp, but requests-credssp is not installed.

### Additional information

The documents that I have read lead me to believe this capability is a part of the normal AWX Operator install.

**Comment by fosterseth** [comment]
this sounds similar to this issue here https://github.com/ansible/awx-ee/issues/183

You may need to build out your own EE in order to get this working

**Comment by fosterseth** [comment]
closing for now since it is a duplicate, please add more information on that other awx-ee issue
