### ISSUE TITLE
job events are not fully updated after job finished

### ISSUE THREAD

**Issue by zou-can** [ansible/awx#14339]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Our system will request `GET: /api/v2/jobs/{job_id}/job_events/` to get job events after job finished, but we found that events are not fully updated after job finished, so we can not ensure to obtain all events in final status.

Here's a case:

```
GET: /api/v2/jobs/32322/

{
  "id": 32322,
  "type": "job",
  "started": "2023-08-14T07:39:27.054016Z",
  "finished": "2023-08-14T07:39:33.418258Z"
}
```

```
GET: /api/v2/jobs/32322/job_events/?or__event=runner_on_ok

{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "id": 826923,
      "created": "2023-08-14T07:39:33.041231Z",
      "modified": "2023-08-14T07:39:34.212958Z",
      "event": "runner_on_ok"
    }
  ]
}
```

Job finished at 2023-08-14T07:39:33, but event modified at 2023-08-14T07:39:34.

### AWX version

21.13.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

1. Launch a job.
2. Get job events after job finished by `GET: /api/v2/jobs/{job_id}/job_events/`
3. Compare `modified` field in event and job finished time.

### Expected results

Modified times for all events are earlier than job finished time.

### Actual results

Modified times for a part of events are later than job finished time.

**Comment by fosterseth** [comment]
@AlanCoding I think we recently changed something around the timing of events processing and finished status. Am I remembering correctly?

what is the best way to determine that all job events have been processed for a finished job?

**Comment by AlanCoding** [comment]
^ this has not changed recently. It is a well-known thing that job events are still processing after status changes, since saving the events is often the bottleneck. We have a boolean `event_processing_finished` _only_ on the details page, which is `/api/v2/jobs/N/` which shows true/false about whether events are all saved.

**Comment by zou-can** [comment]
@AlanCoding Thanks for your reply, `event_processing_finished` is helpful for this case. However, it's not a well-known thing for users. I think it would be better to mention this point on ansible docs.

**Comment by fosterseth** [comment]
marking as solved for now
