### ISSUE TITLE
AWX Community Meeting Agenda - Sep  2023

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#14346]
# AWX Office Hours

## Proposed agenda based on topics
* @tvo318 The new AWX docs site, fully updated and ready for your contributions! https://github.com/ansible/awx/tree/devel/docs/docsite
* @relrod AWX collection test in GitHub Action!
* @TheRealHaoLiu Ansible Community Forum update. https://www.ansible.com/blog/welcome-to-the-new-ansible-community-forum
* @fosterseth Release of hop node feature.
* @fosterseth [Ability to allow inbound connection to AWX receptor mesh on Kubernetes](https://forum.ansible.com/t/ability-to-allow-inbound-connection-to-awx-receptor-mesh-on-kubernetes/215)
* @relrod [Ansible Community Day - Berlin](https://www.eventbrite.com/e/ansible-community-day-berlin-2023-tickets-696525324997)
* @TheRealHaoLiu [Ansible Community Summit in Durham](https://hackmd.io/@ansible-community/cs202310-planning)
* @elibogomolnyi  The EKS reconnect support https://github.com/ansible/awx/issues/14293 https://github.com/ansible/receptor/pull/818/files
* @elibogomolnyi The AWX project updates issue https://github.com/ansible/awx/issues/14432
* @sean-m-sullivan https://github.com/ansible/awx/pull/14428
* Spuds Award!

## What

After a successful Contributor Summit in October, one of the bits of feedback we got was to host a regular time for the Automation Controller (AWX) Team to be available for your folks in the AWX Community, so we are happy to announce a new regular video meeting.

This kind of feedback loop is vital to the success of AWX and the AWX team wants to make it as easy as possible for you - our community - to get involved.

## Where & When
Our next meeting will be held on Tuesday, Sep 12th, 2023 at [1500 UTC](https://dateful.com/time-zone-converter?t=15:00&tz=UTC)

* [Google Meet](https://meet.google.com/vyk-dfow-cfi)
* Via Phone PIN: 842522378 [Guide](https://support.google.com/meet/answer/9518557)

This meeting is held once a month, on the second Tuesday of the month, at [1500 UTC](https://dateful.com/time-zone-converter?t=15:00&tz=UTC)

## How

Add one topic per comment in this GitHub issue

If you don't have a GitHub account, jump on [#awx:ansible.com](https://matrix.to/#/#awx:ansible.com) on Matrix and we can add the topic for you

## Talk with us

As well as the fortnightly video meeting you can join the Community (inc development team) on Matrix Chat.

* Matrix: [#awx:ansible.com](https://matrix.to/#/#awx:ansible.com) (recomended)
* libera.chat IRC: `#ansible-awx` (If you are already setup on IRC)

The Matrix & IRC channels are bridged, you'll just have a better experience on Matrix

## Links
[AWX YouTube Chanel](https://www.youtube.com/@ansible-awx)
[Previous Meeting](https://github.com/ansible/awx/issues/14239)
[Meeting recording](https://youtu.be/1_auAzb8pMc)
[Next Meeting](https://github.com/ansible/awx/issues/14546)

See you soon!

**Comment by relrod** [comment]
Agenda item: [Ansible Community Day - Berlin](https://www.eventbrite.com/e/ansible-community-day-berlin-2023-tickets-696525324997)
Agenda item: Reminder about the [Bullhorn](https://docs.ansible.com/ansible/latest/community/communication.html#the-bullhorn)

**Comment by TheRealHaoLiu** [comment]
Ansible Community Forum update

**Comment by tvo318** [comment]
Agenda item: Announce the new AWX docs repo, fully updated and ready for your contributions!

**Comment by TheRealHaoLiu** [comment]
https://hackmd.io/@ansible-community/cs202310-planning

Ansible Community Summit in Durham, NC, USA as part of DjangoCon 2023

**Comment by TheRealHaoLiu** [comment]
Announcement of the new forum.ansible.com

**Comment by fosterseth** [comment]
Agenda items: 
- announce hop node
- ideas thread on https://forum.ansible.com/t/ability-to-allow-inbound-connection-to-awx-receptor-mesh-on-kubernetes/215/9

**Comment by elibramson** [comment]
More agenda items:

- The EKS reconnect support https://github.com/ansible/awx/issues/14293, https://github.com/ansible/receptor/pull/818/files
- The AWX project updates issue https://github.com/ansible/awx/issues/14432

**Comment by sean-m-sullivan** [comment]
Another agenda item discuss
https://github.com/ansible/awx/pull/14428

- Many to many associations are out of scope for this. 
- do we include it in OPTIONS for list views? leaning towards yes
- naming?

**Comment by john-westcott-iv** [comment]
@elibogomolnyi and @sean-m-sullivan adding these items to the agenda slides.
