### ISSUE TITLE
Slack notification is not working as expecting from awx

### ISSUE THREAD

**Issue by jmamatha** [ansible/awx#14356]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hi Team,

Tried sending success or fail notification from AWX to slack notification using slack or webhook options but getting error when we do Test after filling slack details in notifications tab. But we are unable to view error message in AWX.
When I am trying to send messages from awx to slack using webhook, getting below mentioned error. Please help to fix on this certification verification issue. 

Error Details:

TPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))
NOTIFICATION TEMPLATES
1

Thanks & Regards,
Mamatha J

### AWX version

AWX 22.4.0 

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

openshift

### Modifications

no

### Ansible version

ansible [core 2.15.3]

### Operating system

Linux 

### Web browser

Firefox, Chrome

### Steps to reproduce

1. Go to notification tab in AWX, under the notification template click on add.
2. In the create new notification template fill the below details. 
3. Name, organization and Type as: Webhook
4. After selecting Webhook in type it will ask for Webhook url and HTTP method. 
5. So I gave webhook URL info and HTTP method as Post and HTTP Hearders info then clicked on save. 
6. Then do click on test. Then it is giving as error but it is not showing error info to fix.

### Expected results

Slack notifications need to send from AWX for success and failure state's of ansible job. 

### Actual results

When we click on Test after filling notification with webhook or slack details getting error.

**Comment by jmamatha** [comment]
Please let me know if more info is required from my end.

**Comment by relrod** [comment]
> Name, organization and Type as: Webhook

For slack, you likely want to use the "Slack" notification type instead of webhook. Please try using that (you'll have to create a [slack app](https://api.slack.com/apps) with appropriate permissions).

**Comment by jmamatha** [comment]
Hi Relrod,

Thank You for the update. 

Actually I mentioned only Webhook in this ticket but I tried both Webhook method as well as selecting Slack as a Type, and filled Name and organization correctly.  Slack application created with appropriate permissions and I did testing by posting some text to slack channel using webhook from my command prompt and it worked. Only from AWX unable to send notifications.

1. When I clicked on Test button after filing slack or webhook notification type, getting error  but unable to view the error message. This is one issue.
2. One of my team member tried sending messages to slack channel using Webhook from AWX and they got error as mentioned below. So, we are thinking like error may be with certification verification. 

Error details:
PSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/chat.postMessage (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))
NOTIFICATION TEMPLATES
1

Please let me know if you need more info from my end. I hope I gave clarity on my current issue.

Thanks & Regards,
Mamatha Jalla.

**Comment by djyasin** [comment]
Hello, 
Based on what you have described, this seems like it is an environmental issue. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information on ways to connect with us.
