### ISSUE TITLE
symlinks don't work with group_vars (and possibly elsewhere as well) even if follow symlinks is checked

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#14360]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Right now we have some project that has group vars that contain files with same name as datacenters (each datacenter has different config) and servers are grouped by datacenter.

Since some datacenters are in same country and share some configuration, we only created symlinks to PDC, eg.

```
lrwxrwxrwx 1 ansible ansible   12 Feb  6  2020 C_IN-CC-AHMEDABAD_all -> C_IN-PDC_all
lrwxrwxrwx 1 ansible ansible   12 Feb  6  2020 C_IN-CC-BANGALORE_all -> C_IN-PDC_all
lrwxrwxrwx 1 ansible ansible   12 Feb  6  2020 C_IN-CC-GURGAON_all -> C_IN-PDC_all
lrwxrwxrwx 1 ansible ansible   12 Feb  6  2020 C_IN-CC-MUMBAI_all -> C_IN-PDC_all
lrwxrwxrwx 1 ansible ansible   12 Feb  6  2020 C_IN-PDC-DILLI_all -> C_IN-PDC_all
```

This works just fine with standalone ansible of all versions, but in AWX this doesn't work, it seems that symlink is treated as a file that contains literally the name of its target, that means in this case C_IN-PDC-DILLI_all would be a text file containing only string literal "C_IN-PDC_all" instead of yaml contents it actually has

AWX jobs then fail with:

```
TASK [Gathering Facts] *********************************************************
ERROR! failed to combine variables, expected dicts but got a 'dict' and a 'AnsibleUnicode': 
{}
"C_IN-PDC_all"
```

I tried checking follow symlinks and refresh the project, but it didn't help. This problem seems to affect only AWX as with regular ansible this works just fine.

### AWX version

22.5.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

minikube

### Modifications

no

### Operating system

OL9

### Steps to reproduce

Create a repository that contains symlinks it gets cloned without symlinks, where symlinks are replaced with regular files that have name of target file as content

### Expected results

symlinks work

### Actual results

symlinks don't work

**Comment by djyasin** [comment]
Hello,
We would like to gather a bit more information from you. Are you using a sourced project? Are the targets other files in the same directory? Where is "C_IN-PDC_all" in relation to the other files in the directory?

**Comment by benapetr** [comment]
this seems it was problem on my side - minikube was using some p9 driver which doesn't seem to support symlinks well, on real k8s this works fine now
