### ISSUE TITLE
Can't delete the notification both during cleanup and manually

### ISSUE THREAD

**Issue by elibramson** [ansible/awx#14366]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

There is a notification template we can't delete because of its huge number of records (we have about 2.5 notifications in our templates for some reason). We decided to delete all notifications  by gradually decreasing the number of days by one in this command:
`awx-manage cleanup_jobs --notifications --days ...`

And then, when all of them are deleted, delete the broken notification template.

We started doing it and believe we found this issue's root cause. When we reached 65 days, the process got stuck on:
`deleting "**notification-15409343**" (started 2023-06-17 06:27:11.461526+00:00, webhook type, 1 sent)`

Retry doesn't help; it gets stuck on this template repeatedly.

We found this notification in DB, and I tried to bypass this notification by deleting it manually (we made a backup before):
`DELETE from main_notification WHERE id=15409343`

But even this didn't help. The notification deletion still gets stuck on this notification, even if it doesn't exist in the main notification table.

After some time, we saw that this notification with an **ID 15409343** was somehow recovered to the table by itself (there seems to be some AWX automation that we don't know about that returns the deleted records).

So, it looks like this notification makes the whole process stuck. Is there any way to delete this notification from everywhere so we can let the AWX cleanup proceed?

The notification details are here:
<img width="459" alt="image (5)" src="https://github.com/ansible/awx/assets/79839819/4b4539d2-f42f-4a3e-bed4-8d5dd311c4c8">

### AWX version

22.5

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

Unknown

### Expected results

The notification is deleted and the cleanup keeps running.

### Actual results

The cleanup gets stuck on a particular notification, even if it doesn't exist in DB.

**Comment by elibogomolnyi** [comment]
Closing this issue since it was resolved by itself after restarting all AWX pods. It seems like some parallel queries caused it to happen.

**Comment by elibramson** [comment]
Closing this issue since it was resolved by itself after restarting all AWX pods. It seems like some parallel queries caused it to happen.
