### ISSUE TITLE
allow users to work with instance groups

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#14367]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

Right now instance groups are accessible only to system administrators, which doesn't make them very useful. It would be great if regular users were allowed to chose which instance group they want their jobs to execute with, or be able to assign inventories to instance groups, instead of requesting AWX administrators to do this for them.

It should be possible to grant permissions on instance group so that team or user can "use it"

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

Now instance groups can be used and assigned to inventories or projects only by system administators

### Current results

Now instance groups can be used and assigned to inventories or projects only by system administators

### Sugested feature result

Instance groups are useable by regular users as well

**Comment by mcen1** [comment]
Pardon me if I am misunderstanding you, but I believe I ran into something similar to what you are trying to do so I figured maybe I'd try to help. 

We recently upgraded our AWX to 22.4.0 and I now see options to assign Instance Group permissions for users and teams as a role where this option definitely did not exist before we did our upgrade (I validated between the old and new versions before they were all upgraded). The role options include "Admin", "Read", and "Use" for the instance group(s) selected. It's possible you are using an older version of AWX like I was, maybe.

**Comment by benapetr** [comment]
@mcen1 hello!

where do you see it? I upgraded to 23.2.0 and I don't see this anywhere in instance group administration. When I login as regular user, I don't have any option to change which instance group my project or templates are going to use, I am forced to use defaults or ask administrator to assign instance groups themselves (I am administrator but I want to make this option available to other people)

**Comment by mcen1** [comment]
I see the option when I go to the "Users" section in the GUI, go to my user, select the Roles tab, select Add, and there are options for "Instance Groups".

![image](https://github.com/ansible/awx/assets/49885111/6a3de321-9977-4807-8f57-0734499129ef)

**Comment by AlanCoding** [comment]
Closing as resolved

**Comment by kengsia** [comment]
@mcen1 < even the option is there , after I select the instance group and try to associate , it will be failed and pop up the error: do not have permissions .
