### ISSUE TITLE
API v2 users: Allow setting `ldap_dn`

### ISSUE THREAD

**Issue by mamercad** [ansible/awx#14379]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

Add `ldap_dn` to `/api/v2/users` as an optional field which, when set, populates `main_profile` accordingly. The reason behind this request is the ability to pre-populate (with random passwords initially, since for new users, they're required) AWX with LDAP users (by automation).

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

There is nothing to reproduce, the API does not have this functionality at this time.

### Current results

The API does not have this functionality at this time.

### Sugested feature result

Add `ldap_dn` as an optional parameter to POST, PUT, and PATCH of `/api/v2/users`.

**Comment by djyasin** [comment]
@mamercad Would you mind outlining this proposal in a bit more detail? 

Thank you for your time!

**Comment by mamercad** [comment]
> @mamercad Would you mind outlining this proposal in a bit more detail?
> 
> Thank you for your time!

I'm going to close this ... I don't think I remember the use-case anymore.
