### ISSUE TITLE
Make flows look better for many consecutive jobs

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#14378]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

Right now flows aren't looking very well if you put too many consecutive jobs there, it's basically 1 massive line, see screenshot (that is zoomed out to even be able to display all of them)

<img width="1669" alt="image" src="https://github.com/ansible/awx/assets/1560121/4d4fd603-7005-44e4-be71-c167dcd39aa7">

it would be far better if in case of such long flow it would organize boxes into multiple lines connected with arrow going from end of line to beginning of next one

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

make a workflow with 50 jobs that follow each other

### Current results

looks ugly

### Sugested feature result

looks nice

**Comment by djyasin** [comment]
@benapetr Thank you for your feedback! We will take this into consideration during our ongoing efforts to update the visualizer.
