### ISSUE TITLE
awx.awx collection license is ambiguous

### ISSUE THREAD

**Issue by gotmax23** [ansible/awx#14393]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

The the `awx.awx` colection's galaxy.yml file claims that the license is `GPL-3.0-only`. On the other hand, the README says

> All content in this folder is licensed under the same license as Ansible, which is the same as the license that applied before the split into an independent collection.

which suggests that the collection is licensed under `GPL-3.0-or-later`, as that's the license of Ansible. Additionally, some of the files have GPLv3+ license comments.

`awx.awx` is included in the ansible package, so it MUST be licensed under `GPL-3.0-or-later` or a compatible license as per the [Collection Requirements](https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_requirements.html#collection-licensing-requirements).

Can you please confirm that the license is `GPL-3.0-or-later`? If it's not, we will probably need to remove the collection from the ansible package.

### AWX version

23.0.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Ansible version

N/A

### Operating system

N/A

### Steps to reproduce

N/A

### Expected results

N/A

### Actual results

N/A

**Comment by gotmax23** [comment]
FYI @ansible/steering-committee.

**Comment by gundalow** [comment]
@gotmax23 Thanks for spotting and raising this, let me check with a few people then we can get a PR raised to clarify 

https://github.com/ansible/awx/blob/devel/awx_collection/galaxy.yml and https://github.com/ansible/awx/blob/devel/awx_collection/tools/roles/template_galaxy/templates/galaxy.yml.j2

**Comment by AlanCoding** [comment]
From reading what you wrote, it sounds like the problematic bit is here:

https://github.com/ansible/awx/blob/951bd1cc87199a003a7973e7fce9bede3c0a2078/awx_collection/tools/roles/template_galaxy/templates/galaxy.yml.j2#L20-L21

The statement about sharing the same license as Ansible-core is because the modules were copied over from when they lived in `ansible/ansible`, although the modules have changed very dramatically since that time.

The first appearance of the licence entry in galaxy.yml appears to be 2f0f692f4a2758a2d3dc8c2b6c21c5affd39906a by me, upon introduction of the collection. I'm fairly sure that was due to copying other collection metadata from around that time.

If we were to do this today, we would probably prefer the `license_file` key like `community.general`, although that actually confuses me further because I don't see how that covers the "-or-later" part https://github.com/ansible-collections/community.general/blob/main/galaxy.yml

**Comment by djyasin** [comment]
@gundalow Can you provide a specific action regarding this?

**Comment by gundalow** [comment]
Let's use `license_file` to point to COPYING (not sure if we need the full path or not)

**Comment by gotmax23** [comment]
> If we were to do this today, we would probably prefer the `license_file` key like `community.general`, although that actually confuses me further because I don't see how that covers the "-or-later" par

[`community.general`'s README](https://github.com/ansible-collections/community.general/tree/main#licensing) explicitly states `GPL-3.0-or-later`.

> Let's use `license_file` to point to COPYING (not sure if we need the full path or not)

That works, but the README should also more clearly state the license.

**Comment by AlanCoding** [comment]
Can you point to a file for GPLv3+ we would use that case? I'm not sure if I understand correctly if the "+" is part of the license file itself or specified outside of the license file. Also should we keep the headers like this?

https://github.com/ansible/awx/blob/224e9e0324b6663c2f777a05b731a5268a66be2f/awx_collection/plugins/modules/execution_environment.py#L4-L5

That links https://www.gnu.org/licenses/gpl-3.0.txt, which we could use in `awx_collection/COPYING`, but I'm not sure if this accomplishes the intent and IANAL

**Comment by gundalow** [comment]
> > If we were to do this today, we would probably prefer the `license_file` key like `community.general`, although that actually confuses me further because I don't see how that covers the "-or-later" par
> 
> [`community.general`'s README](https://github.com/ansible-collections/community.general/tree/main#licensing) explicitly states `GPL-3.0-or-later`.
> 
> > Let's use `license_file` to point to COPYING (not sure if we need the full path or not)
> 
> That works, but the README should also more clearly state the license.

@gotmax23 Though community.generaly's galaxy.yml points to https://github.com/ansible-collections/community.general/blob/6303096648c0a5052ff96a85ff1d34d528fb0ef2/galaxy.yml#L13 `COPYING` which is a the GPLv3 (not plus) license file)

**Comment by felixfontein** [comment]
Well, the license **file** is GPLv3, but the license itself says:

>   Each version is given a distinguishing version number.  If the
> Program specifies that a certain numbered version of the GNU General
> Public License "or any later version" applies to it, you have the
> option of following the terms and conditions either of that numbered
> version or of any later version published by the Free Software
> Foundation.  If the Program does not specify a version number of the
> GNU General Public License, you may choose any version ever published
> by the Free Software Foundation.

So if you just point to the license file, it is not clear whether you mean GPLv3 (SPDX: GPL-3.0-only) or GPLv3+ (SPDX: GPL-3.0-or-later). You need to clarify that somewhere else, for example in the README, in source code files, or somewhere else. The source files seem to already state GPLv3+, but galaxy.yml explicitly says "no newer version" at the moment.

It should either say "GPL-3.0-or-later", or link to the license file and state somewhere else that later versions of the GPLv3 are also OK.

**Comment by AlanCoding** [comment]
Then I would lean towards strictly doing

```diff
diff --git a/awx_collection/tools/roles/template_galaxy/templates/galaxy.yml.j2 b/awx_collection/tools/roles/template_galaxy/templates/galaxy.yml.j2
index b9bb8e0ccc..5290dc7217 100644
--- a/awx_collection/tools/roles/template_galaxy/templates/galaxy.yml.j2
+++ b/awx_collection/tools/roles/template_galaxy/templates/galaxy.yml.j2
@@ -18,7 +18,7 @@ documentation: https://github.com/ansible/awx/blob/devel/awx_collection/README.m
 homepage: https://www.ansible.com/
 issues: https://github.com/ansible/awx/issues?q=is%3Aissue+label%3Acomponent%3Aawx_collection
 license:
-  - GPL-3.0-only
+  - GPL-3.0-or-later
 name: {{ collection_package }}
 namespace: {{ collection_namespace }}
 readme: README.md
```

Because this conflicted with both the statement about Ansible-core correspondence, the headers, and the intent from the time of migrating the modules, and as the one who added that line I attest to the fact that I did not mean to do it.

**Comment by felixfontein** [comment]
Sounds good to me! I would also scan through all files in the collection to see whether there is one that does not explicitly allows later versions of GPL, just to be on the safe side. Usually (in all collections where I've been working) folks tend to copy the copyright headers from another file and update them instead of writing them from scratch, so probably all will say the same ("GNU General Public License v3.0+").

**Comment by AlanCoding** [comment]
Oh I didn't realize we already had a GPL v3 `awx_collection/COPYING` file. That's compatible but like @gundalow said we should declare it via `license_file:`, but doesn't remove the need for the `license:` key.

I don't see any inconsistencies (other than aesthetic) in the file headers.

**Comment by AlanCoding** [comment]
I take back what I just said, I don't know how this happened.

https://github.com/ansible/awx/blob/cf1e448577a6349dc008ce48944bee46a3a25480/awx_collection/plugins/module_utils/tower_legacy.py#L2

Many (python) files don't have headers, which I assume is A-ok, because we have a license declared for the collection generally.

**Comment by felixfontein** [comment]
You cannot use both `license_file` and `license` in galaxy.yml, either `ansible-galaxy collection build` doesn't like it or the Galaxy importer (don't remember which one).

Having BSD licensed files (or files with other licenses that are GPL compatible, like MIT, PSF, Apache, ...) in a GPLv3+ licensed collection is no problem. Many collections have that, also ansible-core itself.

Potential problems could be files that have no license header at all - there you might need approval from all contributors that contributed during the time the collection was GPL-3.0-only to make them GPL-3.0-or-later. But IANAL.

**Comment by AlanCoding** [comment]
I don't really want BSD licensed files hanging around. I can't find any imports of `TowerLegacyModule` by the actual collection, and I'm wondering if I can delete that file.

**Comment by felixfontein** [comment]
Please note that that file is part of the public API of the collection, so removing it can only be done in a new major release.

**Comment by AlanCoding** [comment]
Followup - https://github.com/ansible/awx/pull/14421

But I will close this as the current issue is resolved.
