### ISSUE TITLE
Inventory Variables Not Updating

### ISSUE THREAD

**Issue by scottlarnach** [ansible/awx#14391]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

We define a number of variables in our hosts files and in AWX they are displayed in the Variables section of the Details tab, under Resources > Inventories.  We were facing strange issues running jobs in AWX, which worked in the CLI, and discovered these variables aren't updating after a commit and project/inventory sync. 

Under the inventory details, if I manually click Edit, remove the Variables, Save and then re-sync, only then do the variables update with the latest revision.

### AWX version

22.3.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.12.0

### Operating system

Ubuntu 22.04.2

### Steps to reproduce

Create hosts file, define hosts and define vars for the hosts.

Sync project in AWX and view Variables under Resources > Inventories, select inventory > Details tab

Update/Add/Remove variables in hosts file and sync project again, view Variables again - they will not  be updated.

Click Edit and manually remove Variables, re-sync project and updated variables will now be used in AWX.

### Expected results

When variables in hosts file are updated, AWX should update these after a project/inventory sync.

### Actual results

When variables in hosts files are updated, AWX does not update these after a project/inventory sync, the Variables only update if the field is empty in AWX.

**Comment by djyasin** [comment]
@scottlarnach we would like to gather a bit more information from you. Could you please provide us with screenshots of the behavior you are experiencing and some more information about the steps you are taking to produce this behavior?

Thank you for your time!

**Comment by scottlarnach** [comment]
@djyasin thanks for getting back to me, I went to get the screenshots and now bizarrely can't replicate the issue.  Very strange, as I sat with my colleague watching it happen before!

I'll close for now and raise again if it reappears in the future.  Thanks
