### ISSUE TITLE
Job output not displayed during the job run

### ISSUE THREAD

**Issue by dchittibala** [ansible/awx#14415]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

When I ran any Job, the output of the job is not displayed while it's running or even it's completed. I have to go back to the dashboard/home then jump to the job output page to see the output.
It seems a duplicate of [#11765 ](https://github.com/ansible/awx/issues/11765), but its still is not fixed

### AWX version

22.5.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.15.3

### Operating system

OSX

### Steps to reproduce

Installation of AWX was done by following [awx-operator](https://github.com/ansible/awx-operator) documentation and without any modifications.
Created a Sample job, and run it.

### Expected results

expected to see output while the job is running.

### Actual results

Displays `waiting for job output..` instead of displaying the stdout/stderr of the Job
![Screenshot 2023-09-05 at 2 17 27 PM](https://github.com/ansible/awx/assets/22890744/9b9d939e-abd3-4631-9050-10143355fd79)

When I switch to home and back to Job output, I see the stdout, but notice from above image that the elapsed time was 55 sec, but the job failed with in the first 10 sec of start(shown in  below screenshot)
User can be on that screen for long time and see the job status in running but actually it has failed/succeeded, User needs to switch back from home to job output to see the output.
![Screenshot 2023-09-05 at 2 21 19 PM](https://github.com/ansible/awx/assets/22890744/be1f2748-0088-409d-8d25-4e8105817958)

**Comment by fosterseth** [comment]
live stdout is fed to the browser via websocket messages. if you open network tab in your browser, and navigate to the WS column (websockets), you should see open connections to server. Do you see healthy connections? which browser are you on?

On the main job list page, do you see job statuses change in real time? that also uses websockets.

**Comment by dchittibala** [comment]
Hello @fosterseth 
I have installed AWX on my K8 cluster and did a local port forward from the service `kubectl port-forward svc/awx-test-service 80:80`
Looking at the websockets in inspect, I see this `web socket is closed before the connection is established` while watching the job for stdout.
<img width="1726" alt="Screenshot 2023-09-08 at 11 09 58 AM" src="https://github.com/ansible/awx/assets/22890744/30fac01b-8d5e-41fe-8fb0-58365611daab">

<img width="1722" alt="Screenshot 2023-09-08 at 11 30 20 AM" src="https://github.com/ansible/awx/assets/22890744/62eab47a-4d67-474c-a095-ea791279d53b">


On the above screenshot status of job change changed to error but it never gave me the stdout output. But once I switch back to the dashboard and get back to that job I see the output like below
<img width="1166" alt="Screenshot 2023-09-08 at 11 14 14 AM" src="https://github.com/ansible/awx/assets/22890744/87cd3bf4-036c-4bc7-819e-d7d52bc3dbc0">

**Comment by dchittibala** [comment]
Adding extra headers on my nginx helped me to resolve this
`Upgrade $http_upgrade`
`Connection "Upgrade"`
