### ISSUE TITLE
Search filter reset after click on previous page

### ISSUE THREAD

**Issue by EchoRider999** [ansible/awx#14439]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

The search filter doesn't work when we come back on the page.

### AWX version

21.13

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.9

### Operating system

Amazon Linux

### Web browser

Chrome

### Steps to reproduce

In AWX, Ressources > Templates
Search something match some results.
A filter is add.
Click on one result
Click "previous page" in web browser
The filter is still here but the results is reset and show all

### Expected results

Keep results with filters when I click on previous page.

### Actual results

The filter is still here but the results is reset and show all

**Comment by thedoubl3j** [comment]
Hello, this issue pertains to an older version of AWX. Try upgrading to the latest version and let us know if that resolves your issue. This should have been fixed with this PR https://github.com/ansible/awx/pull/13869 and we are unable to reproduce on latest.

**Comment by EchoRider999** [comment]
Ok thanks for the good news, I will update when we can, thanks.
