### ISSUE TITLE
list of credential tags on templates view should wrap horizontally with an eventual 'see more'

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#1444]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### STEPS TO REPRODUCE
- create at least 20 credential types or, alternatively, 20 vault credentials with different vault_ids
- create one credential for each type
- create a job template
- assign all credentials to that job template
- inspect the job template on the lists view

##### EXPECTED RESULTS
- the list of credential tags should wrap horizontally with an eventual 'see more..'

##### ACTUAL RESULTS
- they stack vertically in a column

**Comment by ryanpetrello** [comment]
Fixed in 1.0.7.
