### ISSUE TITLE
Thycotic Secret Server credentials not working when using domain field.

### ISSUE THREAD

**Issue by Laskya** [ansible/awx#14446]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

When using Thycotic Secret Server credential type domain and password are switched

### AWX version

23.1.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Steps to reproduce

In Thycotic Secret Server credentials type when using domain field type your credentials and click button test and give proper secret id that you have access to.

### Expected results

This should return a secret.

### Actual results

It return SecretServerClientError.

**Comment by AlanCoding** [comment]
fix is merged
