### ISSUE TITLE
Impossible to update project with proxy authentification

### ISSUE THREAD

**Issue by Altometers** [ansible/awx#14468]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Impossible to update project with proxy authentification when we have requirement in playbook for download to ansible galaxy.

### AWX version

23.1.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Operating system

Debian 11

### Web browser

Firefox, Chrome

### Steps to reproduce

Update project behind proxy where require authentification.
and we have requirement :

collections:
  - name: community.general
  - name: ansible.posix

we need to download to ansible galaxy.

### Expected results

success to update project

### Actual results

ERROR! Failed to download collection

**Comment by Altometers** [comment]
sorry it's a misconfiguration.

**Comment by Jed-Giblin** [comment]
What was the correct env setup for this? My project updates also fail behind our corporate proxy and using 
```
https_proxy=http://<user>:<password>@proxy_addr GIT_CURL_VERBOSE=1 /usr/bin/git ls-remote https://www.github.com/something -h refs/heads/HEAD
```

The output of which shows git not sending the ProxyAuthenticate header
