### ISSUE TITLE
Tower Settings of type on/off idempotency not working

### ISSUE THREAD

**Issue by Dustin-Wi** [ansible/awx#14487]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

When trying to set the setting named AWX_MOUNT_ISOLATED_PATHS_ON_K8S to true, no matter what I put in the playbook it is always marked as "changed: true", even if the setting is already true..

Sample Task:
```
    - name: SET AWX EXPOSE HOST PATHS
      awx.awx.settings:
        name: "AWX_MOUNT_ISOLATED_PATHS_ON_K8S"
        value: true

```

When I change the playbook value and register the results of the task to review the results I get this:

| Value In Playbook | Resulting Debug|
| ------- | ------- |
| true    | ok: [awxlab] => {<br>    "this_setting": {<br>        "changed": true,<br>        "failed": false,<br>        "new_values": {<br>            "AWX_MOUNT_ISOLATED_PATHS_ON_K8S": "True"<br>        },<br>        "old_values": {<br>            "AWX_MOUNT_ISOLATED_PATHS_ON_K8S": true<br>        },<br>        "value": true<br>    }<br>}|
| True    | ok: [awxlab] => {<br>    "this_setting": {<br>        "changed": true,<br>        "failed": false,<br>        "new_values": {<br>            "AWX_MOUNT_ISOLATED_PATHS_ON_K8S": "True"<br>        },<br>        "old_values": {<br>            "AWX_MOUNT_ISOLATED_PATHS_ON_K8S": true<br>        },<br>        "value": true<br>    }<br>}|
| "true"  | ok: [awxlab] => {<br>    "this_setting": {<br>        "changed": true,<br>        "failed": false,<br>        "new_values": {<br>            "AWX_MOUNT_ISOLATED_PATHS_ON_K8S": "true"<br>        },<br>        "old_values": {<br>            "AWX_MOUNT_ISOLATED_PATHS_ON_K8S": true<br>        },<br>        "value": true<br>    }<br>}|
| "True"  | ok: [awxlab] => {<br>    "this_setting": {<br>        "changed": true,<br>        "failed": false,<br>        "new_values": {<br>            "AWX_MOUNT_ISOLATED_PATHS_ON_K8S": "True"<br>        },<br>        "old_values": {<br>            "AWX_MOUNT_ISOLATED_PATHS_ON_K8S": true<br>        },<br>        "value": true<br>    }<br>}
| yes     | ok: [awxlab] => {<br>    "this_setting": {<br>        "changed": true,<br>        "failed": false,<br>        "new_values": {<br>            "AWX_MOUNT_ISOLATED_PATHS_ON_K8S": "True"<br>        },<br>        "old_values": {<br>            "AWX_MOUNT_ISOLATED_PATHS_ON_K8S": true<br>        },<br>        "value": true<br>    }<br>}

The documentation says this:
```> AWX.AWX.SETTINGS    ([...]collections/ansible_collections/awx/awx/plugins/modules/settings.py)

        Modify Automation Platform Controller settings. See https://www.ansible.com/tower for an overview.

OPTIONS (= is mandatory):
- value
        Value to be modified for given setting.
        **If given a non-string type, will make best effort to cast it to type API expects.**
        For better control over types, use the `settings' param instead.
        default: null
        type: str
```

This leads me to believe that the logic used to sanitize the input might be doing a little extra or the conversion of 'settings' parameters to/from name/value parameters.

The documentation does show an example of how to use both the settings parameter and the name/value parameter.  So, this may be lower priority but I wanted to get this somewhere that could be search by others who may be running into this issue.

### AWX version

23.1.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.15.4

### Operating system

CentOS Stream release 9

### Web browser

Firefox

### Steps to reproduce

Use a playbook that modifies a boolean setting.
Use the awx.awx.setting module.
Use the name/value parameters instead of the settings paremeter.
Sample:
```
    - name: SET AWX EXPOSE HOST PATHS
      awx.awx.settings:
        name: "AWX_MOUNT_ISOLATED_PATHS_ON_K8S"
        value: true
      register: this_setting
    
    - name: Debug this setting
      debug: var=this_setting
```

### Expected results

When the setting is already true, idempotency keeps the playbook from trying to update the setting again.

### Actual results

Regardless if the setting is true or not, the playbook always updates the setting.

**Comment by kurokobo** [comment]
As documented, `settings` param is recommended for non-string types settings.

> For better control over types, use the `settings' param instead.

So try this out:

```yaml
    - name: SET AWX EXPOSE HOST PATHS
      awx.awx.settings:
        settings:
          AWX_MOUNT_ISOLATED_PATHS_ON_K8S: true
      register: this_setting
```

**Comment by Dustin-Wi** [comment]
This is what I ended up doing and it works.

I realize this may not be the most important issue for an open source project of this size, and  I wasn't sure if this was intended behavior.  So, I reported it.

Thank you,

Dustin

**Comment by kurokobo** [comment]
Oh, you already mentioned about `settings` param in the first post, my apologies.

I've made investigate a bit and found that this is an unintended behavior indeed, so I'll send PR to address this.

**Comment by Dustin-Wi** [comment]
Sorry to harass further, but how do I implement the update?  I tried installing the collection again using ansible-galaxy but it's telling me that I already have the latest version of the collection?  Do these updates and patches get pushed on sprint cycles or something?

**Comment by kurokobo** [comment]
@Dustin-Wi 
The fix will be shipped with the next version of AWX. You should just wait for the next release, or if you want to use before its release, you can install it from git repository.

CLI:

```bash
ansible-galaxy collection install git+https://github.com/ansible/awx.git,devel
```

or by `requirements.yml`:

```yaml
collections:
  - name: https://github.com/ansible/awx.git
    type: git
    version: devel
```

**Comment by Dustin-Wi** [comment]
@kurokobo Thank you!
