### ISSUE TITLE
How to match builder, runner and ee versions for awx k8s deployment

### ISSUE THREAD

**Issue by manneharikrishna** [ansible/awx#14498]
##### ISSUE TYPE

 - Breaking Change
 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - API
 - UI
 - Collection
 - Docs
 - CLI
 - Other

##### SUMMARY
Hi All,

   I am trying to build awx 21.14 application for aws eks.
What versions i need to pick for builder, runner and ee.
I tried a lot but keep failing while building images.
Your quick response is much appriciated.

Thanks,
Hari

##### ENVIRONMENT
* AWX version: 21.14
* AWX install method: operator, developer environment
* AWX deployment target: kubernetes, eks
* Operating System:
* Web Browser:

**Comment by fosterseth** [comment]
Hello, this appears to be less of a bug report or feature request and more of a question. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.
