### ISSUE TITLE
Fix spelling errors in AWX user guide

### ISSUE THREAD

**Issue by samccann** [ansible/awx#14490]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Fix the following spelling errors:
./credentials.rst:616: Authenication ==> Authentication
./glossary.rst:40: serveral ==> several
./inventories.rst:899: documenation ==> documentation
./inventories.rst:927: documenation ==> documentation
./notifications.rst:532: adddress ==> address
./project-sign.rst:36: Vist ==> Visit

### AWX version

current

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Web browser

Firefox

### Steps to reproduce

none

### Expected results

none

### Actual results

none

**Comment by Abhinav-CHD** [comment]
Hey can I work on this issue?

**Comment by VibhorGits** [comment]
Hey I would like to work on this issue.

**Comment by tvo318** [comment]
@Abhinav-CHD and @VibhorGits - thank you for your interest in helping improves these docs. Please clone the repo or simply open the file you want to work on and edit it using the GitHub web tools and open a PR.
1. Clone the AWX repo.
2. Navigate to the source files for the User Guide in GitHub at: https://github.com/ansible/awx/tree/devel/docs/docsite/rst/userguide (locally they should reside in ``/Users/you/awx/docs/docsite/rst/userguide``).
3. Edit the .rst files, as applicable. 
4. Commit the changes, open a PR.

**Comment by maskboyAvi** [comment]
Hey, I would like to work on this issue.

**Comment by tvo318** [comment]
Resolved via #14507.
