### ISSUE TITLE
launch on VirtualMashine  through the AWX-Container a playbook.yml

### ISSUE THREAD

**Issue by vikslol** [ansible/awx#14494]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Dear Sir or Madam

i have installed virtualmashine and ubuntu above, then i have installed another things, and myplaybook.yml is working through 
ansible-playbook... . Then i ve got ansible awx from git clone https://github.com/ansible/awx.git. i made settings with repository and etc, that i can do myplaybook.yml through awx, but ive got always the same error(below). Is it possible to fix it? and how?

Sorry, i dont have a big experience witht these things, but i ve not found the same error here, thats why i wrote to you, sorry if u got more work because of me

best regrets

The full traceback is:
  File "/tmp/ansible_docker_network_payload_7tvmq96i/ansible_docker_network_payload.zip/ansible_collections/community/docker/plugins/module_utils/common_api.py", line 117, in __init__
    super(AnsibleDockerClientBase, self).__init__(**self._connect_params)
  File "/tmp/ansible_docker_network_payload_7tvmq96i/ansible_docker_network_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/api/client.py", line 188, in __init__
    self._version = self._retrieve_server_version()
  File "/tmp/ansible_docker_network_payload_7tvmq96i/ansible_docker_network_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/api/client.py", line 212, in _retrieve_server_version
    raise DockerException(
fatal: [localhost]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "ch…

### AWX version

23.1.1

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.10.8

### Operating system

Ubuntu

### Web browser

Firefox

### Steps to reproduce

VirtualMaschine
Ubuntu
docker
docker-compose
openssh
ansible
awx

images from Dockerfiles
create myplaybook.yml
d /path/to/your/playbooks/
git init

git add .
git commit -m "Initial commit"

docker run -d --name=gitea -p 3100:3000 -p 2322:22 -v gitea:/data gitea/gitea:latest

### Expected results

1  network and 2 containers

---
- name: Deploy Docker containers and network with Ansible
  hosts: localhost
  gather_facts: no
  tasks:
     - name: Create Docker network
       docker_network:
        name: my-network
        driver: bridge
        ipam_config:
          - subnet: 172.18.0.0/16

     - name: Deploy MySQL container
       docker_container:
        name: my-sql-container
        image: mysql
        network_mode: my-network
        ports:
          - "3306:3306"
        networks:
          - name: my-network
            ipv4_address: "172.18.0.100"
        env:
          MYSQL_PASSWORD: "admin1"
        volumes:
          - "mysql_data2:/var/lib/mysql"
        state: started

     - name: Wait for MySQL container to start
       wait_for:
        host: localhost
        port: 3306
        timeout: 60

     - name: Deploy web container
       docker_container:
        name: web
        image: myweb
        network_mode: my-network
        ports:
         - "80:80"
         - "443:443"
        networks:
         - name: my-network
           ipv4_address: "172.18.0.99"
        volumes:
         - "wordpress_data3:/var/www/html"
        state: started

### Actual results

this error

The full traceback is:
  File "/tmp/ansible_docker_network_payload_7tvmq96i/ansible_docker_network_payload.zip/ansible_collections/community/docker/plugins/module_utils/common_api.py", line 117, in __init__
    super(AnsibleDockerClientBase, self).__init__(**self._connect_params)
  File "/tmp/ansible_docker_network_payload_7tvmq96i/ansible_docker_network_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/api/client.py", line 188, in __init__
    self._version = self._retrieve_server_version()
  File "/tmp/ansible_docker_network_payload_7tvmq96i/ansible_docker_network_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/api/client.py", line 212, in _retrieve_server_version
    raise DockerException(
fatal: [localhost]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "ch…

**Comment by fosterseth** [comment]
Hello, this appears to be less of a bug report or feature request and more of a question. Could you please ask this on our ansible community forum? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us
