### ISSUE TITLE
Cannot pass VM Properties to filter on when using VMware Inventory 

### ISSUE THREAD

**Issue by Wicaeed** [ansible/awx#145]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
When using source variables for the VMware Inventory type, it should be possible to decrease the number of discovered properties of each VM in order to decrease the inventory processing time. Currently for ~800 VMs the discovery time is around 25 minutes, and each discovered host has 150+ items associated with it.

##### STEPS TO REPRODUCE

- Add a new VMware Inventory item
- Create a new Inventory Source
- Add new Source Variables and include a properties YAML dictionary:
```
---
validate_certs: False
host_filters: "{{ config.template != 'templates' }}"
properties:
  prop01: name 
  prop02: instanceUuid
```
- Start a new inventory scan

##### EXPECTED RESULTS

Using the above as an example, I would expect a vmware_inventory.ini file to be generated that looks like the following:
```
[vmware]
cache_max_age = 0
username = <username>
password = <password>
server = <vcenter>
validate_certs = False
host_filters = {{ config.template != 'templates' }}

[properties]
prop01=name
prop02=instanceUuid
```

##### ACTUAL RESULTS

- While the scan is running, docker exec into the task container and view the generated ini file being used by the task. These can be found in the container /tmp/awx_<jobid>_<radomstring> folder
- Within the generated file, you will find something that looks like this:
```
[vmware]
cache_max_age = 0
username = <username>
password = <password>
server = <vcenter>
validate_certs = False
properties = {'prop01': 'name', 'prop02': 'instanceUuid'}
host_filters = {{ config.template != 'templates' }}
```

The properties argument is being incorrectly declared. There should be two separate blocks in the ini file, one called `[vmware]` and one called `[properties]`.

##### ADDITIONAL INFORMATION
[vmware_inventory reference](https://github.com/ansible/ansible/blob/devel/contrib/inventory/vmware_inventory.ini)

[AWX Code snippet responsible for ini file generation](https://github.com/ansible/awx/blob/devel/awx/main/tasks.py#L1699-L1717)

Using the reference vmware_inventory.ini and manually running the vmware_inventory.py script within the task container, it is possible to correctly get only the filtered properties

**Comment by matburt** [comment]
That's definitely not a UI thing. Will mark this as a backend enhancement.

**Comment by tima** [comment]
Would this be helped by #171?

**Comment by matburt** [comment]
Yep that's entirely possible

**Comment by ewithak** [comment]
I was having this issue with AWX (not being able to configure VMware inventory) and it turns out that the vmware_inventory.ini doesn't exist and isn't needed. In the Ansible Tower 3.1.5 docs, it mentions that the place to set these variables is in the "source variables" field at the bottom of the source setup panel. Settings ca be YAML or JSON.

eg:
```
---
validate_certs: False
lower_var_keys: True
alias_pattern: "{{ config.name | lower }}"

**Comment by Wicaeed** [comment]
If you check in the task container when a vmware inventory task is running there is actually a generated inventory file located in a folder named something like `/tmp/ad76f-<jobid#>/`

I believe the way it works is that a placeholder vmware_inventory.ini file is read in by the vmware_inventory.py at run time.

Most of the source variables **do work**, but it's only when you try to add a new one called `host_filters` do things get buggy, since host_filters is a new configuration section in the vmware_inventory.ini but is currently being passed in as a dictionary item instead of a new section of the config file.

**Comment by fortinj66** [comment]
@Wicaeed   I am running into the same issue

**Comment by jdranchman** [comment]
The properties feature was added in 2016 by jctanner - not sure if he has seen this issue or not.

**Comment by pelinore** [comment]
I have the same problem and I think I understand it a little better.

To fix it, one either has to change the vmware_inventory.py to look for the properties variable values within the [vmware] section instead of it's own [properties] section, or the tasks.py needs to be changed to add the optional [properties] section to the generated file.

I also understand now the Inventory Source's Instance Filters populates the host_filters value.  There's no need to try to set that as a SOURCE VARIABLE.  Does anyone have an example of that working, other than the AWS one?

BTW:   I was able to sort of get around this issue by overloading the skip_keys SOURCE VARIABLE.  Example below

`skip_keys = declaredalarmstate,disabledmethod,dynamicproperty,dynamictype,environmentbrowser,managedby,parent,childtype,resourceconfig,resourcepool,customvalue,permission,storage,configissue,parentvapp,recenttask,availablefield,datastore,summary,overallstatus,triggeredalarmstate,network,capability,guestheartbeatstatus,layout,effectiverole,rootsnapshot,configstatus,value,snapshot,layoutex,runtime`

It's ugly, but it reduced the job run time on a 600 VM vCenter instance from 2279 seconds to 209 seconds.  Not as elegant as the properties option runtime of 20 seconds when I only wanted 12 of the values,, but it's an improvement nonetheless.

**Comment by jdranchman** [comment]
I "think" I got around this by uploading a copy of vmware_inventory.py as a custom script with one change: 'ini_path': '/etc/ansible/vmware_inventory2.ini'

The generated /tmp/awx_inventory_*/tmp* file references my ini file as expected. I went from around an hour to do an inventory to around 2.5 minutes.  FYI - my ini looks like this:

```
[vmware]
server=vcenter.example.com
username=yoyo
password=so!there
validate_certs=False

skip_keys=declaredalarmstate,disabledmethod,dynamicproperty,dynamictype,environmentbrowser,managedby,childtype,resourceconfig,parent

# We don't allow duplicate vm names so this works
alias_pattern={{ config.name }}

lower_var_keys=True

max_object_level=1

# Hostname is the configured DNS/hostname
host_pattern={{ config.name }}

# Generate groups based on the guest ID.
groupby_patterns={{ guest.guestid }},{{ 'templates' if config.template else 'linuxGuests' }}

# Pull in all linux guests except for the template(s) and Ansible control & repository guests.
host_filters={{ ( guest.gueststate == 'running' ) and ( guest.guestfamily == 'linuxGuest' ) and ( config.name != 'Template CentOS 7' ) and ( config.name != 'ansible' ) and ( config.name != 'pulp' ) }}

[properties]
prop00=name
prop01=config.template
prop02=guest.guestid
prop03=guest.guestfamily
prop04=guest.gueststate
prop05=config.name
prop06=guest.hostname
prop07=runtime.powerstate
prop08=config.uuid
```
As an example, a single guest snippit is returned like this:
 
```
     "guestosme": {
        "name": "guestosme",
        "ansible_ssh_host": "guestosme",
        "ansible_uuid": "45a34370-444d-440c-af5c-6614d0563b3c",
        "runtime": {
          "powerstate": "poweredOn"
        },
        "config": {
          "name": "guestosme",
          "template": false,
          "uuid": "421a9391-7d53-ca65-095e-5ecd07f17a06"
        },
        "ansible_host": "guestosme",
        "guest": {
          "guestid": "centos64Guest",
          "guestfamily": "linuxGuest",
          "gueststate": "running",
          "hostname": "guestosme"
        }
      },
```
And all of my groups are made (and populated) from guest.guestid:

$ tower-cli group list 
=== =================== ========= 
id         name         inventory 
=== =================== ========= 
359 centos64Guest              13
360 centos6_64Guest            13
361 centos7_64Guest            13
362 fedoraGuest                13
358 linuxGuests                13
363 oracleLinux64Guest         13
364 other3xLinux64Guest        13
365 rhel7_64Guest              13
366 ubuntu64Guest              13
=== =================== =========

**Comment by jdranchman** [comment]
@matburt IMHO I'm not sold on this is an enhancement with low priority. Although I have presented a workaround, to use the embedded VMware VCenter source is broken for [properties]. At some point this will probably be replaced with a plugin but until then...

**Comment by matburt** [comment]
It's a low-priority enhancement because it implements some newer capabilities from the core modules and it's not high on our priority of things to deal with right at this moment. If it's higher priority for you then you can take it up and submit a PR.

**Comment by ghost** [comment]
is there any update on this ? 
I'm unable to limit hosts due to + uuid added to the host name. It's not very convenient 
Can vmware_inventory.py just detect the duplicate values and store them under group rather than appending the UUID to it ?

**Comment by matburt** [comment]
We pull the inventory source from ansible/ansible itself. We haven't made any changes here because it's just not a high priority now. If it is for you then submit a PR and we can review it.

**Comment by the-cat-is-maybe** [comment]
I just changed in the file
/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py

The Lines

        if config.has_section('properties'):
            self.guest_props = []
            for prop in config.items('properties'):
                self.guest_props.append(prop[1])

to

        if config.has_option('vmware','prop01'):
            self.guest_props = []
            for prop in config.items('vmware'):
                if prop[0].startswith("prop"):
                    self.guest_props.append(prop[1])


Now in the inventory source variables if I include an options called prop01 it will grab all the prop* key:values and only get the values.

If you use the standard docker install for ansible I can get in to modify the files using. 
docker exec -it awx_task bash

**Comment by shanemcd** [comment]
I believe this is a problem that should be raised with https://github.com/ansible-collections/community.vmware
