### ISSUE TITLE
uWSGI listen on 127.0.0.1 but nginx sent to localhost

### ISSUE THREAD

**Issue by aperigault** [ansible/awx#1452]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
I have a lot of errors like this on my awx_web container:
```
2018/03/06 16:23:13 [warn] 27#0: *3362 upstream server temporarily disabled while connecting to upstream, client: 172.0.0.2, server: _, request: "POST /api/v2/authtoken/ HTTP/1.1", upstream: "uwsgi://[::1]:8050", host: "ansible.test"
```

When I replace localhost in **upstream uwsgi** and **upstream daphne** by 127.0.0.1 all seems to be ok. Am I the only one ?

##### ENVIRONMENT
* AWX version: 1.0.4.0
* AWX install method: docker on linux
* Operating System: Debian

**Comment by matburt** [comment]
I don't think you're the only one... I've noticed this too... I think it has to do with the lack of `localhost` defined anywhere or resolvable within a container in some situations.

**Comment by matburt** [comment]
I'm going to cc @shanemcd to see what he thinks also.

**Comment by shanemcd** [comment]
Hmmm.... I don't think I've ever seen this. I noticed you are running `1.0.4.0`, and a lot of bugs have been squashed since then. Would you mind trying with a fresh system running the latest code from devel?

**Comment by matburt** [comment]
@aperigault I'm okay with you submitting a PR to this effect.
