### ISSUE TITLE
[DOCS] Add alt-text codeblock to Images for Userguide: instance_groups.rst

### ISSUE THREAD

**Issue by tvo318** [ansible/awx#14524]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

We need to add alt-text to images for accessibility purposes. See the syntax in the Expected Results below.

### AWX version

latest

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

1. Clone the AWX repo.
2. Navigate to the source files for the User Guide in GitHub at: https://github.com/ansible/awx/tree/devel/docs/docsite/rst/userguide (locally they should reside in ``/Users/you/awx/docs/docsite/rst/userguide``).
3. Open the instance_groups.rst file to edit it. Search all image directives and place the `:alt:` code block beneath it. See syntax in Expected Results below.
4. Commit the changes, open a PR.

### Expected results

The following codeblock added to each image with its specific descriptors filled in: 
```
.. image:: ../common/images/image-filename.png
   :alt: Phrase that describes image

```
or

```   
|Resource - alt text describing image|

.. |Resource - alt text describing image| image:: ../common/images/image-filename.png
   :alt: Phrase that describes image

```
### Actual results
Some images don't have the alt text info in them.

### Additional information
Example from Credentials section of the User Guide:

```
Add Team Permissions
^^^^^^^^^^^^^^^^^^^^^^

To add permissions to a Team:

1. Click the **Add** button, which opens the Add Permissions Wizard.

.. image:: ../common/images/teams-users-add-permissions-form.png 
   :alt: Add Permissions Form

```

**Comment by Celebi07** [comment]
@tvo318 Can you please assign it to me?

**Comment by tvo318** [comment]
@Celebi07 looks like @123MwanjeMike has already opened a PR for this. @123MwanjeMike - can you please comment on this issue in order to be assigned to it?

**Comment by 123MwanjeMike** [comment]
Hi @tvo318
Please assign this issue to me.
I see it's closed though.
