### ISSUE TITLE
AWX Community Meeting Agenda - Oct 2023

### ISSUE THREAD

**Issue by thedoubl3j** [ansible/awx#14546]
### **AWX Office Hours**
**Proposed agenda based on topics**
- @tvo318 [hacktoberfest](https://github.com/ansible/awx/issues?q=is%3Aissue+is%3Aopen+label%3AHacktoberfest) call to action
- @fosterseth https://github.com/ansible/awx/issues/14486
- @AlanCoding https://github.com/ansible/awx/pull/14469
- @thedoubl3j galaxy NG updates
- Reminder [Django Con & Ansible Contributors Summit](https://www.ansible.com/blog/ansible-contributor-summit-durham-2023) 
- Red Hat Summit & Ansible Fest [CFP now open](https://www.redhat.com/en/summit/submit-a-session)
- Mailing List [Deprecation](https://groups.google.com/g/awx-project/c/SLL5fz7xcmE)
- 

### What
After a successful Contributor Summit in October, one of the bits of feedback we got was to host a regular time for the Automation Controller (AWX) Team to be available for your folks in the AWX Community, so we are happy to announce a new regular video meeting.

This kind of feedback loop is vital to the success of AWX and the AWX team wants to make it as easy as possible for you - our community - to get involved.

### Where & When
Our next meeting will be held on Tuesday, Oct 10th, 2023 at [1500 UTC](https://dateful.com/time-zone-converter?t=15:00&tz=UTC)

[Google Meet](https://meet.google.com/vyk-dfow-cfi)
Via Phone PIN: 842522378 [Guide](https://support.google.com/meet/answer/9518557)
This meeting is held once a month, on the second Tuesday of the month, at [1500 UTC](https://dateful.com/time-zone-converter?t=15:00&tz=UTC)

### How
Add one topic per comment in this GitHub issue

If you don't have a GitHub account, jump on [#awx:ansible.com](https://matrix.to/#/#awx:ansible.com) on Matrix and we can add the topic for you

### Talk with us
As well as the fortnightly video meeting you can join the Community (inc development team) on Matrix Chat.

Matrix: [#awx:ansible.com](https://matrix.to/#/#awx:ansible.com) (recomended)
libera.chat IRC: #ansible-awx (If you are already setup on IRC)
The Matrix & IRC channels are bridged, you'll just have a better experience on Matrix

### Links
[AWX Youtube Channel](https://www.youtube.com/@ansible-awx)
[Previous Meeting](https://github.com/ansible/awx/issues/14346)
Meeting recording
Next Meeting

**Comment by TheRealHaoLiu** [comment]
@thedoubl3j where u put that meeting recording... I can't find it

**Comment by djyasin** [comment]
> @thedoubl3j where u put that meeting recording... I can't find it

I think this is what you're looking for: https://drive.google.com/file/d/1ce81yz9EywGvJFo3sb7AE_5MO28l9Ho9/view

**Comment by gundalow** [comment]
[Next meeting](https://github.com/ansible/awx/issues/14621)
