### ISSUE TITLE
UI not showing output + overlaping elements 

### ISSUE THREAD

**Issue by fritz0011** [ansible/awx#14552]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

setup:
kubernets 1.27
awx-operator: 2.5.0

  - extranal postgres (separated pod)
Same behaviour also on AWX 22.6.0
![image](https://github.com/ansible/awx/assets/86201211/65f85cd4-2f9e-4af3-86de-c074e2bf41ca)

now, if I click on reload output ....

![image](https://github.com/ansible/awx/assets/86201211/f4957a02-cf17-4e55-9400-f6824b64002c)

If I switch to tech preview job output shows properly...

![image](https://github.com/ansible/awx/assets/86201211/5a82f828-9fae-4bd5-8a92-465df49d5ce0)

### AWX version

22.5.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Operating system

linux/win

### Steps to reproduce

see attached images

### Expected results

see attached images 
mostly when switch to tech preview interface

### Actual results

see attached images

**Comment by fosterseth** [comment]
Are you saying that when you hit Reload output, the stdout still doesn't show? what if you do a browser page refresh?

**Comment by fritz0011** [comment]
> Are you saying that when you hit Reload output, the stdout still doesn't show? what if you do a browser page refresh?

the same , doesn't matter if reload or refresh, for both firefox and edge...
![image](https://github.com/ansible/awx/assets/86201211/4f129d60-d8cc-4194-950b-bc6f4967f7b8)

In fact the output is hidden to the area that is highlighted....

**Comment by fritz0011** [comment]
I found out a temporary solution:

![image](https://github.com/ansible/awx/assets/86201211/2e9518f2-6f00-429a-8254-55d36e722905)

I had to reduce the zoom  of the page to 50%..... 
The area that display the output is plain to small.... 
![image](https://github.com/ansible/awx/assets/86201211/52f67f06-a00a-4fba-9423-5d8a3825f1a4)

**Comment by fritz0011** [comment]
Found the main problem:
It turned out to be a problem with font size on windows: I just reset font size to 100% and everything looks normal :)
