### ISSUE TITLE
BUG: User can bypass instance group restriction of organizations

### ISSUE THREAD

**Issue by youtous** [ansible/awx#14559]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Related to https://github.com/ansible/awx/issues/14367 and https://github.com/ansible/awx/issues/4292.

When a user gains the USE right on an Instance Group, they can bypass the allowed list of instance groups in an organization.

Before the introduction of this RFE (Request for Enhancement), the organization's allowed instance group acted as a filter. This is no longer the case, leading to a kind of "security check bypass" if the instance group is used to restrict access to specific assets.

### AWX version

23.2.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Operating system

RHEL like

### Steps to reproduce

1. Create instance groups IG-A and IG-B.
2. Create organizations ORG-A and ORG-B.
3. Allow IG-A in the list of instance groups for ORG-A, and allow IG-B in ORG-B.
4. Create a user USER-1, grant them access to IG-A and IG-B, and assign admin rights for both ORG-A and ORG-B.
5. Create an inventory using USER-1 within ORG-B, and select IG-A as the instance group.

### Expected results

This should not be allowed, IG-B should be filtered from allowed list of ORG-A

### Actual results

It works.

**Comment by AlanCoding** [comment]
I filed https://github.com/ansible/awx/issues/14565 to articulate the ask that we restrict associating items in different organizations. To my knowledge, there was never any such same-organization restrictions with instance groups.

Also see https://github.com/ansible/awx/issues/14564 which was considered before - to add an organization to instance groups for permission management.

**Comment by youtous** [comment]
Hi @AlanCoding

> To my knowledge, there were never any same-organization restrictions with instance groups.

Agreed, although the former documentation stated:

> A group that contains instances for use in a clustered environment. An instance group provides the ability to group instances based on policy.
(https://docs.ansible.com/ansible-tower/3.8.6/html/installandreference/glossary.html#term-Instance-Group)
> Similarly, instance groups associated with Inventories are checked before those associated with Organizations. Thus, Instance Group assignments for the three resources form a hierarchy: Job Template > Inventory > Organization.
(https://docs.ansible.com/ansible-tower/3.8.6/html/administration/external_execution_envs.html#instance-groups)

To my understanding, in Tower 3.8.6, the so-called "policy" was inherited by the Org Admin role; however, with the recent change (https://github.com/ansible/awx/issues/4292), policy enforcement is becoming more detached from the inheritance mode of the admin org.

After reading https://github.com/ansible/awx/issues/14565, I understand that this is more likely an RFE (Request for Enhancement) than a BUG. Nonetheless, considering a hierarchical enforcement of resource policies can bring clarity for both the sys admin of the platform and org admins. When a sys admin defines the list of instance groups in the organization, they use system privileges and do not expect less privileged users to bypass the settings. (One could argue that the IG behavior is the same as the Execution Environment, but EEs are not considered as critical as IGs are).

Closing this issue in favor of your RFEs, thanks!
