### ISSUE TITLE
[Rest API] workflow_job_template_nodes endpoint does not support POST request

### ISSUE THREAD

**Issue by TomCapelle** [ansible/awx#14599]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

I want to create a new workflow job template node with the REST API. I've tried two endpoints:

POST on /api/v2/workflow_job_template_nodes with {"workflow_job_template": 4242, "unified_job_template": 1337} in body

POST on /api/v2/workflow_job_templates/4242/workflow_nodes with {"unified_job_template": 1337} in body

Headers were {"Authorization": "Bearer SECRET"} (Token with Write scope on the right application)

In both cases I got a 200 response with same result as GET request in body. No node was created.

### AWX version

23.1.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Operating system

Linux

### Steps to reproduce

Send POST request to /api/v2/workflow_job_template_nodes with {"workflow_job_template": 4242, "unified_job_template": 1337} in body

OR

POST on /api/v2/workflow_job_templates/4242/workflow_nodes with {"unified_job_template": 1337} in body

workflow_job_template 4242 and job_template 1337 are assumed to exist

### Expected results

Code 201 or 4XX (with error message)

### Actual results

Code 200 and results of a GET request in body

**Comment by fosterseth** [comment]
it might be worth exploring the how the UI sends the requests when adding a node via the UI visualizer
![image](https://github.com/ansible/awx/assets/8745776/87619a58-0676-4bfa-a4fe-135d139c6439)

I see POST with 201 response, not 200. 

can you provide the exact curl (or whatever api call) you are using?

**Comment by TomCapelle** [comment]
Hi, thanks for your answer !

It is indeed a good idea to see how the UI sends the requests to its API, but I do not get the same results as you:
![image](https://github.com/ansible/awx/assets/60487357/c316deb8-bc63-4b4f-bfd5-94c140a3eaf3)

The first red dot (the upper one) is when I start creation of a new node (it fetchs the available job templates), and the last red dot is when I click on the "save" button in the end. It is not written but these are GET or OPTIONS requests. I am not a web developper so I'm not at ease with the dev console of a web browser.

However, here are the requests I've tried to send in Python (all of them gave me the 200 response code with the same result as a GET):

```
import requests

requests.post("https://REDACTED/api/v2/workflow_job_template_nodes", headers= {"Authorization": "Bearer REDACTED"}, json= json.loads(
        '{ "all_parents_must_converge": true, "diff_mode": true, "extra_data": {}, "identifier": "string", "inventory": 0, "job_tags": "string", "job_type": "string", "limit": "string", "scm_branch": "string", "skip_tags": "string", "unified_job_template": 1337, "verbosity": "string", "workflow_job_template": 4242 }'
    ))
    
requests.post("https://REDACTED/api/v2/workflow_job_templates/4242/workflow_nodes", headers= {"Authorization": "Bearer REDACTED"}, json= json.loads('{"unified_job_template": 1337}'))
```

I tried different variants of these requests (with all possible parameters, with requested parameters only, with plain json string, with json dumps on a dict, with json loads on a json string,...), I got the same result each time.

**Comment by fosterseth** [comment]
nothing stands out as wrong upon first glance,

do you mind posting a new "get help" type thread on forum.ansible.com with these details? we may get more support over there

**Comment by TomCapelle** [comment]
Sure, here is the link to the topic: https://forum.ansible.com/t/awx-rest-api-workflow-job-template-nodes-endpoint-does-not-support-post-request/2092

Thanks for your help so far

**Comment by TomCapelle** [comment]
After some deeper investigation, we found out that our AWX instance receives GET requests on some endpoints even if we send POST requests, it seems to come from the ingress controller which redirects wrongly our requests, it is not an issue on AWX end.

Sorry for the inconvenience and thank you for the time you spent on my issue.
