### ISSUE TITLE
[DOCS] AWX site tab misses icon

### ISSUE THREAD

**Issue by Andersson007** [ansible/awx#14591]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

I don't know how this kind of icon is properly called but it's missed on [AWX docsite](https://ansible.readthedocs.io/projects/awx/en/latest/quickstart/index.html) tabs in Chrome and Firefox at least and it doesn't look mature:)

See the screenshot
![Screenshot from 2023-10-19 13-17-25](https://github.com/ansible/awx/assets/34477873/f65041fd-af90-4ff2-ac5e-f1d77a18b3f6)

### AWX version

latest

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Web browser

Firefox, Chrome

### Steps to reproduce

Open https://ansible.readthedocs.io/projects/awx/en/latest/quickstart/index.html

### Expected results

it has a picture

### Actual results

It doesn't have any picture

**Comment by Bhanuteja01** [comment]
@Andersson007 can you assign me this issue
I would like work on this issue

**Comment by gundalow** [comment]
Please copy from https://github.com/ansible/awx/blob/devel/awx/ui/public/static/media/favicon.ico into the docs directory, thanks.

**Comment by Bhanuteja01** [comment]
@gundalow small request can add hackoctoberfest tag for this issue

**Comment by Bhanuteja01** [comment]
@gundalow can you explain how to do it
i tried but i not able to figure it out .can you help me in this.

**Comment by gundalow** [comment]
Maybe add `html_favicon` into https://github.com/ansible/awx/blob/devel/docs/docsite/conf.py

https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_favicon

**Comment by webknjaz** [comment]
This is not an easy issue. The problem only appears on URL subpaths (so https://awx.rtfd.io works, for example).

Upgrading Sphinx will likely fix this, based on the comparison of https://readthedocs.org/projects/awx/builds/22558930/, https://readthedocs.org/projects/receptor/builds/22486603/ and https://readthedocs.org/projects/stage-ansible-core/builds/22549592/.

As a bonus, it'd be useful to split the `tox` command into two in the RTD config — `tox -e docs --notest -v` followed by `tox -e docs --skip-pkg-install -q`.

**Comment by gundalow** [comment]
@Bhanuteja01 I'll unassign you from this. I appreciate you taking the time to look at it.

@webknjaz Thank you for providing info on how to fix this.

**Comment by Bhanuteja01** [comment]
@gundalow already i created pr

**Comment by oraNod** [comment]
FYI that I've sent a [PR to upgrade sphinx](https://github.com/ansible/awx/pull/14669) and the other doc requirements, which does seem to fix the issue, judging from the [RTD PR preview build](https://ansible--14669.org.readthedocs.build/projects/awx/en/14669/quickstart/index.html).

On a side note we held off on the version upgrades until the [API reference docs](https://github.com/ansible/awx/pull/14607) were integrated so we could be certain the upgrade wouldn't break anything.

**Comment by tvo318** [comment]
This has now been fixed per PR https://github.com/ansible/awx/pull/14669
