### ISSUE TITLE
Grant view-only permissions for job runs to users and/or teams.

### ISSUE THREAD

**Issue by ricalenil** [ansible/awx#1461]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
Would like the feature to grant view-only to specific job template or view job-runs.

##### ENVIRONMENT
* AWX version: 1.0.4.50
* AWX install method: docker on linux
* Ansible version:  2.4.3
* Operating System: Ubuntu 16.04
* Web Browser: Firefox 58.0.2

##### STEPS TO REPRODUCE
When assigning permissions to user or teams, it should present view role. 

##### EXPECTED RESULTS

View role grant view-only permissions to user or teams.

##### ACTUAL RESULTS

Theres no view role to job or job templates. If there is a way to workarround this, please tell.

**Comment by wenottingham** [comment]
-> https://github.com/ansible/awx/issues/775

**Comment by ricalenil** [comment]
@wenottingham thanks
