### ISSUE TITLE
CleanUp Job Run fails with psycopg.errors.OutOfMemory: out of shared memory HINT:  You might need to increase max_locks_per_transaction.

### ISSUE THREAD

**Issue by esos-ansible** [ansible/awx#14612]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

deleting "2023-10-23 10:45:05.719038+00:00-1367-successful" (type dependency)
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/psycopg/cursor.py", line 723, in execute
    raise ex.with_traceback(None)
psycopg.errors.OutOfMemory: out of shared memory
HINT:  You might need to increase max_locks_per_transaction.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/__init__.py", line 200, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 458, in execute

root@PRD02:~# kubectl get all -n awx
NAME                                                   READY   STATUS    RESTARTS          AGE
pod/awx-postgres-13-0                                  1/1     Running   28 (4h39m ago)    45d
pod/awx-web-5bff8ff6dd-qrphs                           3/3     Running   84 (4h39m ago)    45d
pod/awx-operator-controller-manager-566b76fc7f-4wbmp   2/2     Running   60 (4h39m ago)    45d
pod/awx-task-598d8ddf5b-8dj5b                          4/4     Running   112 (4h39m ago)   45d

NAME                                                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
service/awx-operator-controller-manager-metrics-service   ClusterIP   10.43.128.237   <none>        8443/TCP       45d
service/awx-postgres-13                                   ClusterIP   None            <none>        5432/TCP       45d
service/awx-service                                       NodePort    10.43.171.154   <none>        80:30080/TCP   45d

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/awx-web                           1/1     1            1           45d
deployment.apps/awx-operator-controller-manager   1/1     1            1           45d
deployment.apps/awx-task                          1/1     1            1           45d

NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/awx-web-5bff8ff6dd                           1         1         1       45d
replicaset.apps/awx-operator-controller-manager-566b76fc7f   1         1         1       45d
replicaset.apps/awx-task-598d8ddf5b                          1         1         1       45d

NAME                               READY   AGE
statefulset.apps/awx-postgres-13   1/1     45d

Cant find the postgresql file to change the settings, please advise , has anyone seen this before?

### AWX version

23.1.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

CleanUp Job Schedule fails

  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/__init__.py", line 200, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/usr/lib64/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/management/commands/cleanup_jobs.py", line 413, in handle
    skipped_partition, deleted_partition = func()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/management/commands/cleanup_jobs.py", line 183, in cleanup_project_updates_partition
    return self.cleanup(ProjectUpdate)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/management/commands/cleanup_jobs.py", line 172, in cleanup
    skipped, deleted = delete_meta.delete()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/management/commands/cleanup_jobs.py", line 138, in delete
    self.drop_partitions()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/management/commands/cleanup_jobs.py", line 130, in drop_partitions
    cursor.execute(f"DROP TABLE {parts_to_drop_str}")
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/psycopg/cursor.py", line 723, in execute
    raise ex.with_traceback(None)
django.db.utils.OperationalError: out of shared memory
HINT:  You might need to increase max_locks_per_transaction.

Have tried awx-manage to delete from controller /bin/bash reports same issue

### Expected results

Job Schedule should run without fails

### Actual results

Job Fails with above error message

**Comment by fosterseth** [comment]
when doing job cleanup, how many "days" retention did you input?

also, how much days worth of jobs/events do you estimate is being cleaned up? Do you run jobs every hour of the day?

**Comment by fosterseth** [comment]
maybe a relevant discussion here https://github.com/ansible/awx/issues/13698

**Comment by esos-ansible** [comment]
> when doing job cleanup, how many "days" retention did you input?
> 
> also, how much days worth of jobs/events do you estimate is being cleaned up? Do you run jobs every hour of the day?

7 days. have tried everyday also. Yes we have jobs running every hour.

**Comment by esos-ansible** [comment]
> maybe a relevant discussion here #13698

Looked at that link

Im unsure how to connect to the postgresdb

Ive connected to the container with a bin/bash session and get this prompt


```
postgres@awx-postgres-13-0:~/data$ ls -al
total 12
drwxrwxrwx  3 root     root     4096 Sep 14 15:50 .
drwxr-xr-x  1 postgres postgres 4096 Sep  7 14:26 ..
drwx------ 19 postgres root     4096 Nov  2 07:02 pgdata
postgres@awx-postgres-13-0:~/data$ 
```

But dont know how to issues the commands on the page.

**Comment by esos-ansible** [comment]
if anyone knows the manual steps to delete the job history and i can run the job template on schedule every day, that would be super super helpful @fosterseth

**Comment by esos-ansible** [comment]
```
awx=# \l
                             List of databases
   Name    | Owner | Encoding |  Collate   |   Ctype    | Access privileges 
-----------+-------+----------+------------+------------+-------------------
 awx       | awx   | UTF8     | en_US.utf8 | en_US.utf8 | 
 postgres  | awx   | UTF8     | en_US.utf8 | en_US.utf8 | 
 template0 | awx   | UTF8     | en_US.utf8 | en_US.utf8 | =c/awx           +
           |       |          |            |            | awx=CTc/awx
 template1 | awx   | UTF8     | en_US.utf8 | en_US.utf8 | =c/awx           +
           |       |          |            |            | awx=CTc/awx
(4 rows)

awx=# SHOW max_connections;
 max_connections 
-----------------
 100
(1 row)

awx=# SHOW max_locks_per_transaction;
 max_locks_per_transaction 
---------------------------
 64
(1 row)
```

Ive logged in , how do i delete old job runs? Does anyone know

**Comment by esos-ansible** [comment]
Update. Managed to get the "Cleanup Job Details"  Job template to successfully run.

Steps to accomplish this.

Delete significant portion of old job runs in AWX GUI.

Login to the task container on an interactive bin/bash session

awx-manage cleanup_jobs --days 40
awx-manage cleanup_jobs --days 30
awx-manage cleanup_jobs --days 10

Trying to delete them all at once via awx-manage was causing the same error message "django.db.utils.OperationalError: out of shared memory HINT: You might need to increase max_locks_per_transaction."

Ive now set the clean up to run every mng at 08:00am keeping no more than 10 days of logs in the database.

**Comment by djyasin** [comment]
@esos-ansible we are so happy to hear that you were able to get the "Cleanup Job Details" Job template to successfully run! We will go ahead and close this issue since it has been resolved. Please let us know if you encounter any additional difficulties!

**Comment by grimlokason** [comment]
For those who are encountering the same issue,
Take a look at the memory usage of the pods, the crash could be due to a high memory usage when you select a big timeslot. ( it was for my )

**Comment by prabhumathiyalagan** [comment]
@djyasin I'm encountering similar issue, tried running cleanup job it runs for a while and failed again with same error. I have increase the pod resource to below value but no luck :(

It showing up "Hint: You might need to increase max_locks_per_transaction", where this has to be update? Updating this in AWX operator spec is not accepted. Advice on this, please

```yaml
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  ...
  postgres_resource_requirements:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
```

**Comment by prabhumathiyalagan** [comment]
> @djyasin I'm encountering similar issue, tried running cleanup job it runs for a while and failed again with same error. I have increase the pod resource to below value but no luck :(
> 
> It showing up "Hint: You might need to increase max_locks_per_transaction", where this has to be update? Updating this in AWX operator spec is not accepted. Advice on this, please
> 
> ```yaml
> apiVersion: awx.ansible.com/v1beta1
> kind: AWX
> metadata:
>   name: awx
>   namespace: awx
> spec:
>   ...
>   postgres_resource_requirements:
>     requests:
>       memory: "512Mi"
>       cpu: "250m"
>     limits:
>       memory: "1Gi"
>       cpu: "500m"
> ```

This works fins after updating max_connections = 1000, since we are in old version of awx setting in operator argument is not supported, had to update it in the config file.
