### ISSUE TITLE
Issue on awx.awx.export/import awx cli/collection

### ISSUE THREAD

**Issue by tanganellilore** [ansible/awx#14635]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hi team,
I founded tow bugs related awx cli and collection import / export.

The first issue is related export module, that not work if user is a system_auditor (or not have certain admin role in object like schedule.
I already found why this bug is present and proposed a PR: #14626 .

Second "bug" is related import module  (I don't know  and don't find if someone decide it) and is related how import will be processed.
Actually import perform a `POST`, if object not exists, or a `PUT`, if object exists. In case of we `PUT` an object that already exist api will replace it in all fields, including encrypted key, that in export are removed (correctly).

So, i don't know if it's better approach with `PATCH` instead a `PUT`, but I think that here the issue is in the export itself, that will  replace value of encrypted key `$encrypted$` with `''` .
The side effect of "restore" `$encrypted$ ` on the export is that we remove it for the POST, due to the fact that is a reseved keyword.
 
 I will propose a PR also to fix the second bugs

### AWX version

23.3.1

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [X] Collection
- [X] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

bug 1: execute an export of schedule with a system_auditor

bug 2: import a credential already present in AWX

### Expected results

bug 1: export will go fine

bug 2: credential will be updated with only fields present in export

### Actual results

bug 1: export will fail

bug 2: credential will be replaced with exported data. But due to the fact that encrypted key are not exported and replaced the value `$encrypted$` with `''` we replace current secrets with `''`

**Comment by fosterseth** [comment]
the fix here might be to just on export side, retain the `$encrypted$` value

**Comment by tanganellilore** [comment]
Hi @fosterseth ,
yes for bug 2 i have proposed a PR https://github.com/ansible/awx/pull/14636.
We need to remove `$encrypted$` on post when object not exists because otherwhise we receive error from AWX because `$encrypted$` is a "protected" value
