### ISSUE TITLE
Add custom Root CA during installation

### ISSUE THREAD

**Issue by jffz** [ansible/awx#1463]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - Installer

##### SUMMARY
Add the ability to add our custom Root CA during installation

##### ENVIRONMENT
* AWX version: any
* AWX install method: any
* Ansible version:  any
* Operating System: any
* Web Browser: any

##### STEPS TO REPRODUCE
We actually need to build the image locally with some rework of the playbooks installs in order to add this.

##### EXPECTED RESULTS
Add this feature within the default inventory file

**Comment by matburt** [comment]
This is a dupe and there are a few issues already tracking this:

https://github.com/ansible/awx/issues/531
https://github.com/ansible/awx/issues/416
https://github.com/ansible/awx/issues/411
