### ISSUE TITLE
Invalid key names: REFRESH_TOKEN_EXPIRE_SECONDS

### ISSUE THREAD

**Issue by MrMEEE** [ansible/awx#1464]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
There seems to be something missing in the newly implemented OAuth.. I'm having problems with websockets.. Daphne is not working correctly:

mar 06 22:20:04 akiva.outerrim.lan daphne[10618]: 2018-03-06 22:20:04,844 WARNING  The current value "{u'ACCESS_TOKEN_EXPIRE_SECONDS': 31536000000, u'REFRESH_TOKEN_EXPIRE_SECONDS': 31536000000, u'AUTHORIZATION_CODE
mar 06 22:20:04 akiva.outerrim.lan daphne[10618]: Traceback (most recent call last):
mar 06 22:20:04 akiva.outerrim.lan daphne[10618]: File "/opt/awx/embedded/lib/python2.7/site-packages/awx/conf/settings.py", line 371, in _get_local
mar 06 22:20:04 akiva.outerrim.lan daphne[10618]: return field.run_validation(value)
mar 06 22:20:04 akiva.outerrim.lan daphne[10618]: File "/opt/awx/embedded/lib/python2.7/site-packages/rest_framework/fields.py", line 523, in run_validation
mar 06 22:20:04 akiva.outerrim.lan daphne[10618]: value = self.to_internal_value(data)
mar 06 22:20:04 akiva.outerrim.lan daphne[10618]: File "/opt/awx/embedded/lib/python2.7/site-packages/awx/api/fields.py", line 88, in to_internal_value
mar 06 22:20:04 akiva.outerrim.lan daphne[10618]: self.fail('invalid_key_names', invalid_key_names=', '.join(list(invalid_flags)))
mar 06 22:20:04 akiva.outerrim.lan daphne[10618]: File "/opt/awx/embedded/lib/python2.7/site-packages/rest_framework/fields.py", line 585, in fail
mar 06 22:20:04 akiva.outerrim.lan daphne[10618]: raise ValidationError(message_string, code=key)
mar 06 22:20:04 akiva.outerrim.lan daphne[10618]: ValidationError: [u'Invalid key names: REFRESH_TOKEN_EXPIRE_SECONDS']

REFRESH_TOKEN_EXPIRE_SECONDS seems to be missing from:

/opt/awx/embedded/lib/python2.7/site-packages/awx/api/fields.py

 valid_key_names = {'ACCESS_TOKEN_EXPIRE_SECONDS', 'AUTHORIZATION_CODE_EXPIRE_SECONDS'}

If I add it to the list, I no longer get the error, but websockets are still not working..

I'm using my own RPM build, but just want to let you guys know that there is something wrong..

**Comment by rooftopcellist** [comment]
link: (https://github.com/ansible/awx/pull/1458

@MrMEEE Thanks for bringing this up.  I merged a fix this morning.  If you still see this after pulling down the new code, I'll re-open this.

**Comment by MrMEEE** [comment]
I can confirm that it's fixed :)

**Comment by MrMEEE** [comment]
And I fixed the other issue as well:

I think I fixed it.. added a line to the configuration (/etc/awx/settings.py):

ANSIBLE_VENV_PATH = '/opt/awx/embedded'

and created folder

mkdir /var/lib/awx/venv && chown awx:awx /var/lib/awx/venv

and

yum install bubblewrap

**Comment by rooftopcellist** [comment]
Great!  Thanks for following up on that @MrMEEE
