### ISSUE TITLE
[DOCS] Heading rendering off

### ISSUE THREAD

**Issue by tvo318** [ansible/awx#14653]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Not sure what happened here... maybe a stylesheet issue?

### AWX version

latest

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

Go to https://ansible.readthedocs.io/projects/awx/en/latest/userguide/workflow_templates.html#extra-variables

### Expected results

Look more like https://docs.ansible.com/automation-controller/latest/html/userguide/workflow_templates.html#extra-variables:
![image](https://github.com/ansible/awx/assets/7514801/8b25cc94-13e6-4b34-92cf-77c8adf72c13)

### Actual results

![image](https://github.com/ansible/awx/assets/7514801/2079edea-c747-4f84-b9e0-4be1947a3ee6)

**Comment by fosterseth** [comment]
@oraNod do you mind taking a look at this one, and then removing Triage label?
