### ISSUE TITLE
Microsoft Azure Resource Manager Source Sync failing to parse /runner/inventory/azure_rm.yml with auto plugin

### ISSUE THREAD

**Issue by fedormartynov** [ansible/awx#14650]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hello! I have an issue with "Microsoft Azure Resource Manager" Inventory sync.
We do posses a few subscriptions in Azure and I have separate Source Inventory with type "Microsoft Azure Resource Manager" for each of them. Few days ago (about 08-11-2023)  with no updates done to the system/awx/ansible) SOME of them stop working with error thrown.
Interestingly other inventory sources of the same type, same tenant and same credentials but different subscription working just as fine as before. They all setup the same way with the same variables and settings, just some are working others are not.
I have spinned another server with latest version of AWX but the issue has been repeated also in the new environment (AWX Operator 2.7.2, AWX 23.4.0). Installation done in k3s. All logs in Azure indicate that failed request are not even reaching frontend.

Can you please direct me how it can be fixed?

Sincerely,

### AWX version

21.2.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

N/A

### Modifications

no

### Operating system

Ubuntu 22.04/ Centos Stream8 

### Web browser

Firefox, Chrome

### Steps to reproduce

1. install AWX by AWX-Operator on k3s follow https://github.com/kurokobo/awx-on-k3s. Both CentOS 8 Stream (suggested) and Ubuntu 22.04(tested) are possible. 
2. Have App Registration with Client secret and Permissions READ.ALL deployed in Azure Tenant.  
3. Add Credentials into AWX with Credential Type "Microsoft Azure Resource Manager" providing tenant ID, subscription ID, clientID (App ID) and Client Secret.
4. Add Inventory with Source  by created Credential in step 3 and type "Microsoft Azure Resource Manager"
5. Run sync

On some sources got error parsing inventory azure_rm - on some got no error and hosts are collected/updated.

### Expected results

```
ansible-inventory [core 2.15.6]
  config file = None
  configured module search path = ['/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.9.18 (main, Sep  7 2023, 00:00:00) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
No config file found; using defaults
redirecting (type: inventory) ansible.builtin.azure_rm to azure.azcollection.azure_rm
Using inventory plugin 'ansible_collections.azure.azcollection.plugins.inventory.azure_rm' to process inventory source '/runner/inventory/azure_rm.yml'
Parsed /runner/inventory/azure_rm.yml inventory source with auto plugin
   11.439 INFO     Processing JSON output...
   11.441 INFO     Loaded 3 groups, 3 hosts
   11.502 INFO     Inventory import completed for Azure | XXXXXX | Europe | EU - West Europe | XXXXXXX-WE in 0.1s
```

### Actual results

```
-----------------
ansible-inventory [core 2.15.6]
  config file = None
  configured module search path = ['/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.9.18 (main, Sep  7 2023, 00:00:00) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
No config file found; using defaults
setting up inventory plugins
Loading collection ansible.builtin from 
redirecting (type: inventory) ansible.builtin.azure_rm to azure.azcollection.azure_rm
Loading collection azure.azcollection from /usr/share/ansible/collections/ansible_collections/azure/azcollection
Using inventory plugin 'ansible_collections.azure.azcollection.plugins.inventory.azure_rm' to process inventory source '/runner/inventory/azure_rm.yml'
[WARNING]:  * Failed to parse /runner/inventory/azure_rm.yml with auto plugin:
Expecting value: line 1 column 1 (char 0)
  File "/usr/local/lib/python3.9/site-packages/ansible/inventory/manager.py", line 293, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/local/lib/python3.9/site-packages/ansible/plugins/inventory/auto.py", line 59, in parse
    plugin.parse(inventory, loader, path, cache=cache)
  File "/usr/share/ansible/collections/ansible_collections/azure/azcollection/plugins/inventory/azure_rm.py", line 220, in parse
    self._get_hosts()
  File "/usr/share/ansible/collections/ansible_collections/azure/azcollection/plugins/inventory/azure_rm.py", line 283, in _get_hosts
    self._process_queue_batch()
  File "/usr/share/ansible/collections/ansible_collections/azure/azcollection/plugins/inventory/azure_rm.py", line 414, in _process_queue_batch
    batch_resp = self._send_batch(batch_requests)
  File "/usr/share/ansible/collections/ansible_collections/azure/azcollection/plugins/inventory/azure_rm.py", line 445, in _send_batch
    return json.loads(response.body())
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
[WARNING]: Unable to parse /runner/inventory/azure_rm.yml as an inventory
source
ERROR! No inventory was parsed, please check your configuration and options.

-----------------

```

**Comment by fosterseth** [comment]
are you able to verify that the ansible inventory is valid outside of AWX?

you may open a new thread on https://forum.ansible.com/tag/collections to see if someone can help

**Comment by hzargaryan** [comment]
For me the issue has started since awx-ee:23.4.0, @fedormartynov if you choose older execution environment it should run without errors.

**Comment by fedormartynov** [comment]
> For me the issue has started since awx-ee:23.4.0, @fedormartynov if you choose older execution environment it should run without errors.

Thank you so much! It start working for me with old 22.6.0 tag environment. Will keep it on this version for now, and test with next one when it will arrive.

Thanks once again.

**Comment by jsw1993** [comment]
Sorry. Why is this closed? This is still an issue?

**Comment by fedormartynov** [comment]
> Sorry. Why is this closed? This is still an issue?

It is for me still an issue, although after applying suggested workaround things started to work normally.
Looks like latest (default) environment affected after version awx-ee:23.4.0.
Then setting pre 23.4 version inventory works as expected.

Fedor.

**Comment by jsw1993** [comment]
Please can someone reopen this till the latest version works?
