### ISSUE TITLE
Dns settings not taken

### ISSUE THREAD

**Issue by jffz** [ansible/awx#1465]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
DNS settings set within the inventory file are not applied to the containers

##### ENVIRONMENT
* AWX version: 1.0.4.43
* AWX install method: docker on linux,
* Ansible version:  2.4.3.0
* Compose version: 1.19.0
* Operating System: CentOS 7.4
* Web Browser: any

##### STEPS TO REPRODUCE
Set desired DNS settings in `awx_alternate_dns_servers` and `use_docker_compose=true` parameters

##### EXPECTED RESULTS
DNS settings should be applied within the containers (or through the compose file)

##### ACTUAL RESULTS
DNS Settings are set within the compose file but not applied to the containers. Note that search domains seems working.

```bash
docker exec -ti awx_task_1 cat /etc/resolv.conf
search domain.com
nameserver 127.0.0.11
options ndots:0
```

**Comment by matburt** [comment]
Something doesn't quite look right with the way it's implemented in the compose file:

https://github.com/ansible/awx/blob/devel/installer/local_docker/templates/docker-compose.yml.j2#L21-L23

I don't use this mechanism so if it's something that bothers you I'd appreciate debug help. Does this work okay if you omit using docker_compose and install using standalone docker?

**Comment by wenottingham** [comment]
This got merged
