### ISSUE TITLE
Install fails when trying to build new image - git error --first-parent

### ISSUE THREAD

**Issue by akcrisp** [ansible/awx#1466]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY
Trying to install awx, creating new image fails with -

TASK [image_build : Build AWX distribution using container] ************************************************************************************************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Error creating container: 500 Server Error: Internal Server Error (\"{\"message\":\"Error parsing reference: \\\"awx_sdist_builder:\\\" is not a valid repository/tag\"}\")"}
        to retry, use: --limit @/root/git_repos/awx/installer/install.retry

It appears its not getting the awx version.

Looking at image_build/tasks/main.yml 

the first task has changed between version 1.0.1.173 and this latest 1.0.4-146-g095515b

1.0.1.173 had -

- name: Get Version from checkout if not provided
  shell: "git describe --long | sed 's/\\-g.*//' | sed 's/\\-/\\./'"
  delegate_to: localhost
  register: awx_version_command
  when: awx_version is not defined

1.0.4.146 has -

- name: Get Version from checkout if not provided
  shell: "git describe --long --first-parent | sed 's/\\-g.*//' | sed 's/\\-/\\./'"
  delegate_to: localhost
  register: awx_version_command
  when: awx_version is not defined

Running the newer version on the command line reports -

 git describe --long --first-parent | sed 's/\\-g.*//' | sed 's/\\-/\\./'
error: unknown option `first-parent'
usage: git describe [options] <committish>*
   or: git describe [options] --dirty

    --contains            find the tag that comes after the commit
    --debug               debug search strategy on stderr
    --all                 use any ref
    --tags                use any tag, even unannotated
    --long                always use long format
    --abbrev[=<n>]        use <n> digits to display SHA-1s
    --exact-match         only output exact matches
    --candidates <n>      consider <n> most recent tags (default: 10)
    --match <pattern>     only consider tags matching <pattern>
    --always              show abbreviated commit object as fallback
    --dirty[=<mark>]      append <mark> on dirty working tree (default: "-dirty")

version of git installed -

git-1.8.3.1-6.el7_2.1.x86_64

Looking at the change log for git from redhat.com and comparing it too, the version we have - I don't see anything that says --first-parent has been added - to describe git option. 

Infact this appears to be an option to the --log ie git --log --first-parent

NOTE:- removing the --first-parent from the task - and the build proceeds as expected.

##### ENVIRONMENT
* AWX version: 1.0.4
* AWX install method: docker on linux
* Ansible version:  2.4.3.0-1
* Operating System: RHEL 7.2
* Web Browser: Chrome

##### STEPS TO REPRODUCE

run regular install.

#

**Comment by matburt** [comment]
Yep, you'll need to have a version of git that supports that flag.

**Comment by akcrisp** [comment]
Matt so which version of git ? as per my comment I can't see any mention of this on the versions from rhel ?

**Comment by akcrisp** [comment]
Also the build failed to build - getting load more errors, which seems to be related to not being able to get to github and npm - which is very odd in deed - having set the proxy in /etc/sysconfig/docker and in the inventory file.
