### ISSUE TITLE
LDAP UI missing LDAP GROUP SEARCH

### ISSUE THREAD

**Issue by mzeier** [ansible/awx#1468]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Configuring LDAP auth in the UI but "LDAP GROUP SEARCH" is missing (it's present in Tower but not in AWX 1.0.4.53).

This generates the following error when trying to authenticate:
```
ImproperlyConfigured: AUTH_LDAP_GROUP_SEARCH must be an LDAPSearch instance.
```

##### ENVIRONMENT
* AWX version: 1.0.4.53
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: Ubuntu 16.04
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Navigate to https://awx.example.com/#/configuration/auth and select LDAP from the dropdown.

Note missing LDAP GROUP SEARCH text box.

##### EXPECTED RESULTS

Should have a text box to enter LDAP GROUP SEARCH.

##### ADDITIONAL INFORMATION

* [LDAP UI on AWX](https://www.dropbox.com/s/sv2l9icci9363iz/awx-ldap.png?dl=0)
* [LDAP UI on Tower](https://www.dropbox.com/s/u3emlnojlzgnpot/tower-ldap.png?dl=0)

**Comment by jakemcdermott** [comment]
@mzeier which version of tower is the screenshot from?

On tower 3.2 and latest awx I'm seeing the ldap group search field here:
<img width="1190" alt="screen shot 2018-03-07 at 11 35 46 pm" src="https://user-images.githubusercontent.com/9753817/37133311-88affdd0-2260-11e8-9570-8c11c13b9275.png">

**Comment by mzeier** [comment]
Tower 3.1.2. Never saw it there in AWX :/

**Comment by jakemcdermott** [comment]
No worries, we did move the field after all. With the new location of the field in mind are you able to check your instance and see if it is there?

**Comment by mzeier** [comment]
It's there. Now I need to figure out the syntax for what we had in Tower.

(which is something like)
```
ou=Users,o=3dc731ff,dc=jumpcloud,dc=com
SCOPE_SUBTREE
(objectClass=groupOfNames)
```

**Comment by matburt** [comment]
seems like this can close?

**Comment by jakemcdermott** [comment]
Excellent! Happy to hear you've located it. I'm going to go ahead and close this issue out as resolved. 

If you have any questions please drop us a line on the awx mailing list or join our irc channel on freenode.
