### ISSUE TITLE
EDA Server Built into AWX

### ISSUE THREAD

**Issue by rchaud** [ansible/awx#14686]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

I want to know why is EDA Server not built into AWX. At the end ADE Server uses AWX to run jobs, why wasn't EDA Server added into AWX since at the end it is just another Django application. 

EDA Server seems to be missing a lot of core feature like a more mature authentication system like AWX already has implemented, Credentials example HashiCorp Lookup is another weakness that is EDA Server was built into AWX would take advantage of.

in my opinion, EDA Server can be just another item in the Side Navigation Menu that users can easily access, instead of a complete different project.

As a business, it does makes sense to keep both separate to push two different products to users but I want to know what others in the community think.

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Steps to reproduce

N/A

### Current results

N/A

### Sugested feature result

N/A

**Comment by jessicamack** [comment]
Hello, this question is not a bug. For community discussion please use the forum https://forum.ansible.com/.
