### ISSUE TITLE
API Reference Guide has headers separate from content

### ISSUE THREAD

**Issue by tvo318** [ansible/awx#14694]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

The API Reference Guide appears to be rendering incorrectly with headings separated from their content.

### AWX version

latest

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Operating system

MacOS

### Steps to reproduce

1. Navigate to https://ansible.readthedocs.io/projects/awx/en/latest/rest_api/api_ref.html
2. View content with headings up top and expanded content below.

### Expected results

![image](https://github.com/ansible/awx/assets/7514801/0c6a8d1e-ec0c-4396-a39f-fde85557b80a)
It should expand and collapse like https://docs.ansible.com/automation-controller/latest/html/controllerapi/api_ref.html

### Actual results

![image](https://github.com/ansible/awx/assets/7514801/9893dd98-acae-4fe1-9d2d-57ba75e5114f)

**Comment by oraNod** [comment]
@tvo318 Thanks for reporting this. I've double checked and it appears to be an issue with the swagger.json file that the jenkins job generates. I'm looking into it but it's probably not something we'll need to fix with a pull request to this repo.

**Comment by oraNod** [comment]
@tvo318 This should be resolved now. The issue was with the branch used with the jenkins job. Please double check the published docs here: https://ansible.readthedocs.io/projects/awx/en/latest/rest_api/api_ref.html#

**Comment by tvo318** [comment]
@oraNod - Did you have a PR for this? The fix looks FANTASTIC! Can you leave a comment on the steps you took to fix this (for future reference)? thanks!

**Comment by oraNod** [comment]
@tvo318 No PR to this repo. I made the mistake of running that jenkins job from the wrong branch of the repo. It should not use the devel branch.
