### ISSUE TITLE
Update link to Execution environment getting started guide

### ISSUE THREAD

**Issue by samccann** [ansible/awx#14690]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

The execution environment getting started guide as move to https://ansible.readthedocs.io/en/latest/getting_started_ee/index.html

Update the url introduced in https://github.com/ansible/awx/pull/14263 to point to the new location.

### AWX version

latest

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

none

### Expected results

none

### Actual results

none

**Comment by tvo318** [comment]
The link for the EE chapter of the AWX docs have already been updated to include the new link: https://ansible.readthedocs.io/projects/awx/en/latest/userguide/execution_environments.html#building-an-execution-environment
