### ISSUE TITLE
command not work thouth playbook but work well temp run test

### ISSUE THREAD

**Issue by helloworld113** [ansible/awx#14697]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

command not work through playbook.but work well in inventory host command temp run test.

### AWX version

AWX 22.7.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.15.7rc1

### Steps to reproduce

use the example 
```
---
- name: Hello World!
  hosts: all
  tasks:
  - name: Hello World!
    shell: echo "Hi! Tower is working."
```
but there is nothings in stdout.
![image](https://github.com/ansible/awx/assets/17806666/1ea909c7-0142-4fef-b825-702581e2e39d)

and I change the shell to :  echo "Hi! Tower is working." > /tmp/test.log 
the file not create also. but when I try run command from inventory it work well. I need you help!

### Expected results

Is there any way we can troubleshoot this problem?Can't see useful information in the logs

### Actual results

command not work through playbook

**Comment by fosterseth** [comment]
Hello, this appears to be less of a bug report or feature request and more of a question. Could you please ask this on either the [Ansible AWX channel on Matrix](https://matrix.to/#/#awx:ansible.com) or the [Ansible Community Forum](https://forum.ansible.com/tags/c/help/6/all/awx)?
