### ISSUE TITLE
documentation for prod deployment

### ISSUE THREAD

**Issue by fritz0011** [ansible/awx#14695]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

Hello,

We're about to switch from a test Kubernetes cluster to   prod  Kubernetes.
prod cluster will run ONLY gitlab + keycloak + AWX

 - 3 master nodes (16gb/each)
 - 3 workers (32gb/each)
 - 3 exec nodes (4gb/each)
 - ~ 2000 managed nodes 
 
 Deployment should follow those 2 requirements 
 - HA for AWX (3 replicas would be the best approach)
 - HA for postgres (3 replicas would be enough ? )
 
 According to mentioned resources,  32gb/worker would be enough ? 
 Some additional postgres tuning or default install with default values are enough  ?
  - also in case of PG what  would be the recommended PVC size (50gb, 100gb ? )

### Select the relevant components

- [ ] UI
- [ ] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

N/A

### Current results

N/A

### Sugested feature result

N/A

**Comment by jessicamack** [comment]
Hello, this is a project not a product. We don't provide prod deployment advice. If you would like prod support Red Hat offers an enterprise production ready product called Ansible Automation Platform. You can find further information here https://www.redhat.com/en/technologies/management/ansible.
