### ISSUE TITLE
Install fails with missing docker-py issue on OCP 3.5

### ISSUE THREAD

**Issue by stewartshea** [ansible/awx#147]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Installing into a proper OCP cluster (ie. not a local install such as minishift, oc cluster up, or cdk) fails with:

```
Failed to import docker-py - No module named docker. Try `pip install docker-py'
```

##### ENVIRONMENT
* AWX version: devel branch
* Ansible version:  2.2.1
* Operating System: Mac OS 10.12.5 & RHEL 7.3
* Web Browser: NA. 

##### STEPS TO REPRODUCE

- git clone https://github.com/ansible/awx
- cd awx/installer
- edit the inventory file as per below
- ansible-playbook -i inventory install.yml -e openshift_password=$(oc whoami -t) -e docker_registry_password=$(oc whoami -t)

```
localhost ansible_connection=local

[all:vars]

# Build AWX with official logos
# Requires cloning awx-logos repo into the project root.
# Review the trademark guidelines at https://github.com/ansible/awx-logos/blob/master/TRADEMARKS.md
awx_official=false

# Openshift Install
# Will need to set -e openshift_password=developer -e docker_registry_password=$(oc whoami -t)
#
openshift_host=<console address>:8443
awx_openshift_project=awx
openshift_user=<username>
awx_node_port=30083

# Standalone Docker Install
# postgres_data_dir=/tmp/pgdocker
# host_port=80

# Required for Openshift, Optional for Standalone Docker install
# Define if you want the image pushed to a registry. The container definition
# will also use these images
docker_registry=172.30.198.70:5000
docker_registry_repository=awx
docker_registry_username=<username>

# Set pg_hostname if you have an external postgres server, otherwise
# a new ephemeral postgres service will be created
pg_hostname=postgresql
pg_username=awx
pg_password=awxpass
pg_database=awx
pg_port=5432

# AWX Tunables
awx_secret_key=aabbcc
```

##### EXPECTED RESULTS

Installer to complete

##### ACTUAL RESULTS

docker-py import error and playbook fails

```
TASK [image_build : Stat distribution file] ************************************
ok: [localhost -> localhost]

TASK [image_build : Clean distribution] ****************************************
changed: [localhost -> localhost]

TASK [image_build : Build sdist builder image] *********************************
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "failed": true
}

MSG:

Failed to import docker-py - No module named docker. Try `pip install docker-py`

	to retry, use: --limit @/root/awx/installer/install.retry

PLAY RECAP *********************************************************************
localhost                  : ok=14   changed=2    unreachable=0    failed=1
```

**Comment by matburt** [comment]
Have you tried installing docker-py then?

**Comment by stewartshea** [comment]
Yes on the macos - same result. Testing on the RHEL host now.

**Comment by matburt** [comment]
You might also try just installing `docker`:

`pip install docker` and see if that works.

**Comment by gdahlm** [comment]
Are you using python virtual environments, or a brew installed version of python?

The local connection will use the system python by default which may not have the package installed.

`-e "ansible_python_interpreter=python"`

Or you can add it to `~/.ansible.cfg` in the `[defaults]` section

```
[defaults]
ansible_python_interpreter = python
```
I would highly encourage the use of some form of virtual env when working with this project as `docker-py` will break the `docker` python module and it will remove your ability to install `docker-compose` to install this in the system directories.

ansible/ansible#22993
docker/docker-py#1652

One of these days the `import docker` name conflict will be resolved but it is painful right now.

**Comment by stewartshea** [comment]
Thanks @gdahlm  - that was a big help. Used a virtalenv and have made progress (currently building).
