### ISSUE TITLE
Inventory sync with vmware plugin gets in waiting state endless

### ISSUE THREAD

**Issue by renanguilhermef** [ansible/awx#14706]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

I have a workflow that runs time in time, but intermittently when runs inventory sync using VMWare plugin, gets with waiting state forever and it doesn't show any particular reason apparently

### AWX version

22.2.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Operating system

AKS

### Steps to reproduce

Sync inventory using VMWare vCenter plugin

Source Variables:

---
plugin: vmware_vm_inventory
validate_certs: False
resources:
  - datacenter:
    - xxxxxxxxxxxxxxxxxxxxxx
    resources:
      - folder:
        - 'xxxxxxxxxxxxxxx'
compose:
    ansible_host: >-
      guest.net
      | selectattr('ipAddress')
      | map(attribute='ipAddress')
      | flatten
      | select('match', 'xxxxxxxxxxxx')
      | list
      | first
hostnames:
- 'config.name'
properties:
- 'name'
- 'config.name'
- 'guest.ipAddress'
- 'guest.toolsStatus'
- 'guest.toolsRunningStatus'
- 'config.guestFullName'
- 'config.guestId'
- 'guest.guestFamily'
- 'guest.hostName'
- 'guest.net'
- 'runtime.powerState'
with_path: True
with_tags: True
with_nested_properties: True
filters:
- "config.guestFullName is match('XXXXXXXXXX*') and 'XXXXXXXXXX' in tags"
- "runtime.powerState == 'poweredOn'"

### Expected results

Inventory gets synchronized and complete my workflow

### Actual results

Synchronize with waiting state endless

### Additional information

Below is the log. It doesn't show any reason for the inventory update get in waiting status

2023-12-06 05:15:07,140 INFO     [0dc574ddc2dd4b46a57f2e57662b2a15] awx.analytics.job_lifecycle inventoryupdate-122734 created
2023-12-06 05:15:08,335 INFO     [0dc574ddc2dd4b46a57f2e57662b2a15] awx.analytics.job_lifecycle inventoryupdate-122734 acknowledged
2023-12-06 05:15:10,073 INFO     [0dc574ddc2dd4b46a57f2e57662b2a15] awx.analytics.job_lifecycle inventoryupdate-122734 waiting
2023-12-06 05:23:27,894 INFO     [b6c7232efadf481daafcbf07f5507685] awx.analytics.job_lifecycle job-122721 blocked by inventoryupdate-122734
...

**Comment by djyasin** [comment]
Hello @renanguilhermef the vmware inventory plugin comes from the vmware community collection. They will be better able to assist you. You can view their repo here: https://github.com/ansible-collections/community.vmware
