### ISSUE TITLE
ansible.windows.win_powershell script not running as expected

### ISSUE THREAD

**Issue by GaetanHermann** [ansible/awx#14730]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

The following powershell script doen't work as expected. It will inject some values in a simple database table.

### AWX version

21.14.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Web browser

Edge

### Steps to reproduce

ansible.windows.win_powershell:
    script: |
      $SqlCmdLines = @()
      $insert = "INSERT INTO MyTable(Field1,Field2) VALUES ('{0}','{1}');"
      $listObjects = $myJson | ConvertFrom-Json # $myJson = "[{'Attr1':'value1','Attr2':'value2'},{'Attr1':'value11','Attr2':'value12'}]"
      $listObjects | Foreach-Object {
        $test = $PSItem.Attr1
        if (-not([string]::IsNullOrEmpty($test))) {
          $newTest = "$($test) replaced"
        }
        [String]$SqlInsert = $insert -f $PSItem.Attr1, $newTest
        $SqlCmdLines += $SqlInsert
      }

### Expected results
$SqlCmdLines =>
INSERT INTO MyTable(Field1,Field2) VALUES ('value1','value1 replaced');
INSERT INTO MyTable(Field1,Field2) VALUES ('value11','value11 replaced');

### Actual results
SqlCmdLines =>
INSERT INTO MyTable(Field1,Field2) VALUES ('value1','value1 replaced');
INSERT INTO MyTable(Field1,Field2) VALUES ('value11','value1 replaced'); (this is wrong)

**Comment by GaetanHermann** [comment]
I have found, that if I make a trace of this, it works (Write-Host), but if I inject it directly to the database, it doesn't work. Now I have changed my script and I'm testing it with Start-Sleep -Seconds 2 before injecting to database.

It works now! You can close the ticket.

**Comment by djyasin** [comment]
@GaetanHermann thank you so much for letting us know that you were able to resolve this! We are glad to hear that you found a resolution.
