### ISSUE TITLE
nth-check is currently showing as using 2 different versions in use.

### ISSUE THREAD

**Issue by kumarkaji** [ansible/awx#14734]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

While researching a vulnerability issue with nth-check, i came across the below information from the git hub dependency graph. it looks like the version 1.0.2 needs to be updated in package-lock.json with the newer version which is already in use.

•	nth-check1.0.2
Detected automatically on Sep 06, 2023 (npm) · awx/ui/package-lock.json · BSD-2-Clause
•	[nth-check](https://github.com/fb55/nth-check)2.0.1
Detected automatically on Sep 06, 2023 (npm) · awx/ui/package-lock.json · BSD-2-Clause

### AWX version

23.3.1

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.15.2

### Operating system

ubuntu

### Web browser

Chrome

### Steps to reproduce

Navigate to Insights on the AWX project
Click on dependency graph
Search for nth-check in dependencies
The results should show 2 versions in use.

### Expected results

https://github.com/fb55/nth-check
2.0.1
Detected automatically on Sep 06, 2023 (npm) · [awx/ui/package-lock.json ](https://github.com/ansible/awx/blob/devel/awx/ui/package-lock.json)· BSD-2-Clause

### Actual results

https://github.com/fb55/nth-check
1.0.2
Detected automatically on Sep 06, 2023 (npm) · [awx/ui/package-lock.json ](https://github.com/ansible/awx/blob/devel/awx/ui/package-lock.json)· BSD-2-Clause
https://github.com/fb55/nth-check
2.0.1
Detected automatically on Sep 06, 2023 (npm) · [awx/ui/package-lock.json ](https://github.com/ansible/awx/blob/devel/awx/ui/package-lock.json)· BSD-2-Clause

**Comment by jessicamack** [comment]
Hello @kumarkaji, please email this issue to security@ansible.com.

**Comment by kumarkaji** [comment]
Thank you @jessicamack. Will do.
