### ISSUE TITLE
Ansible Project keeps waiting to git url

### ISSUE THREAD

**Issue by r4s1y** [ansible/awx#14732]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### AWX version

23.5.1

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Steps to reproduce

i installed ansible and awx through ansible automation platform, now i want to use a git repo to fork some yaml files from it but  the project inside the AAP cannot fork the git , it keeps waiting and then gives error.

### Expected results

expected result is forking the repo, and get to the files in the repo.

### Actual results

cannot access the git repo

**Comment by djyasin** [comment]
Hello @r4s1y, this type of question will be better answered in our Forum. Please ask this question there: https://forum.ansible.com/
