### ISSUE TITLE
django-ansible-base missing from requirements/requirements.in ?

### ISSUE THREAD

**Issue by kapouer** [ansible/awx#14748]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

I believe https://github.com/ansible/awx/pull/14705 is missing proper update of requirements.in / requirements.txt.

### AWX version

23.6.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

N/A

### Modifications

no

### Steps to reproduce

This is a source code issue

### Expected results

This is a source code issue

### Actual results

This is a source code issue

**Comment by shanemcd** [comment]
It's in requirements_git.txt - this library is currently under active development and we are iterating on it quickly. If and when we decide to publish to pypi we will update the appropriate files. Since "This is a source code issue" is not describing an actual issue I'm going to close this.
