### ISSUE TITLE
Allow Configuration of SSH Args for isolated instance groups

### ISSUE THREAD

**Issue by one-t** [ansible/awx#1474]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - Installer

##### SUMMARY
Occasionally, clients have asked about connecting to isolated nodes through bastion hosts. Can we expose the ssh args for isolated groups as group vars during installation?

##### ENVIRONMENT
* Tower Version - 3.2+

##### EXPECTED RESULTS
```
[instance_group_security]
towerB
towerC

[isolated_group_govcloud]
isolatedA
isolatedB

[isolated_group_govcloud:vars]
controller=security
ssh_args='-o ProxyCommand="ssh -W %h:%p -q user@gateway.example.com"'
```

##### ADDITIONAL INFORMATION
Other considerations would include making sure we can authenticate on the jump host.

**Comment by ghost** [comment]
We are waiting for this feature to be implemented as well for our environment, it works great for us in Ansible Core. I've seen a few people mention that they haved worked around this temporarily by adding an SSH config to the root user in the task container for the ProxyCommand, I'm in the process of testing this out.

**Comment by glitchcrab** [comment]
I'd like to add my voice to this; I can modify the root user's SSH config but that's not a container-friendly way of working. I have some servers in an extremely heavily firewalled environment and jumping through a bastion host is the only realistic option. It's a pretty common use-case with Ansible so it would be very useful.

**Comment by wenottingham** [comment]
This code is being removed, so this will not be done in this manner.
