### ISSUE TITLE
AWX Community Meeting Agenda - Feb 2024

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#14756]
# AWX Office Hours

## Proposed agenda based on topics
- @fosterseth Mesh Ingress DEMO!
- @TheRealHaoLiu "Failed to JSON parse a line from worker stream due to unexpected EOF(b'')" saga https://github.com/ansible/awx/issues/14693
- @rooftopcellist AWX Operator deployment overrides PR's
  * @TheRealHaoLiu  initial PR - https://github.com/ansible/awx-operator/pull/1695
  * @kurokobo alternate PR - https://github.com/ansible/awx-operator/pull/1697
- @AlanCoding custom RBAC role in AWX
  * https://github.com/ansible/django-ansible-base/pull/45
  * https://github.com/ansible/awx/pull/14735

## What

After a successful Contributor Summit in October, one of the bits of feedback we got was to host a regular time for the Automation Controller (AWX) Team to be available for your folks in the AWX Community, so we are happy to announce a new regular video meeting.

This kind of feedback loop is vital to the success of AWX and the AWX team wants to make it as easy as possible for you - our community - to get involved.

## Where & When
Our next meeting will be held on Tuesday, Feb th, 2024 at [1500 UTC](https://dateful.com/time-zone-converter?t=15:00&tz=UTC)

* [Google Meet](https://meet.google.com/vyk-dfow-cfi)
* Via Phone PIN: 842522378 [Guide](https://support.google.com/meet/answer/9518557)

This meeting is held once a month, on the second Tuesday of the month, at [1500 UTC](https://dateful.com/time-zone-converter?t=15:00&tz=UTC)

## How

Add one topic per comment in this GitHub issue

If you don't have a GitHub account, jump on [#awx:ansible.com](https://matrix.to/#/#awx:ansible.com) on Matrix and we can add the topic for you

## Talk with us

As well as the fortnightly video meeting you can join the Community (inc development team) on Matrix Chat.

* Matrix: [#awx:ansible.com](https://matrix.to/#/#awx:ansible.com) (recomended)
* libera.chat IRC: `#ansible-awx` (If you are already setup on IRC)

The Matrix & IRC channels are bridged, you'll just have a better experience on Matrix

## Links
[AWX YouTube Chanel](https://www.youtube.com/@ansible-awx)
[Previous Meeting](https://github.com/ansible/awx/issues/14712)
[Meeting recording](https://www.youtube.com/watch?v=_S4BIWCgDfg)
[Next Meeting](https://github.com/ansible/awx/issues/14969)

See you soon!

**Comment by tanganellilore** [comment]
Thinking to resume https://github.com/ansible/awx/issues/20 ?

https://ansibleforms.com/  is a good alternative, but we need to re-invent rbac and so on...

**Comment by TheRealHaoLiu** [comment]
@tanganellilore if ur able to make it to March meeting can you put it on March's agenda?
