### ISSUE TITLE
Invalid YAML or JSON not handled well in prompt for extra vars

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#1478]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
Invalid YAML or JSON not handled well in prompt for extra vars.

##### STEPS TO REPRODUCE

* Create a job template with prompt for extra vars.

##### EXPECTED RESULTS

* Not being allowed to proceed to the next step until valid yaml or json

##### ACTUAL RESULTS

* console error and pop-up error

##### ADDITIONAL INFORMATION

```
angular.js:14800 Parse error. Failed to parse variables. <div prompt-data="vm.promptData" class="ng-isolate-scope">
```

**Comment by mabashian** [comment]
I think this might need to be an app-wide improvement.  I think you can get a similar error on the job template form if you put in some bad json and hit save.

**Comment by ryanpetrello** [comment]
Fixed downstream.
