### ISSUE TITLE
Erratic quoting of survey prompt mult-choice values

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#1479]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
- UI

##### SUMMARY
Some values get wrapped in `'quotes'`. Some don't.

##### STEPS TO REPRODUCE

* Create a JT survey prompt w/ a multichoice field with values:
```
fun'
it's fun to run
1
2
3
```
* Launch the JT
* Select all the values for the multichoice

##### EXPECTED RESULTS

```
---
my_multi_choice:
  - fun'
  - it's fun to run
  - 1
  - 2
  - 3
```

##### ACTUAL RESULTS
```
---
my_multi_choice:
  - 'fun'''
  - it's fun to run
  - '1'
  - '2'
  - '3'
```

**Comment by unlikelyzero** [comment]
worth retesting in the new ui. Maybe be a duplicate at this point

**Comment by unlikelyzero** [comment]
no stub necessary

**Comment by shanemcd** [comment]
Just verified that this is fixed in the new UI. @unlikelyzero unless we plan to add an automated test here, I think we can close.
