### ISSUE TITLE
cannot download playbook from redhat insights 

### ISSUE THREAD

**Issue by bskou57** [ansible/awx#14791]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hi

When creating a project to download playbooks (plan) from my redhat insights account I got below error message :

PLAY [Update source tree if necessary] *****************************************
TASK [Ensure the project directory is present] *********************************
ok: [localhost]
TASK [Fetch Insights Playbook(s)] **********************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Expected /api/remediations/v1/remediations to return a status code of 200 but returned status code "404" instead with content "b'<!doctype html>\n\n\n <title>Example Domain</title>\n\n <meta charset="utf-8" />\n <meta http-equiv="Content-type" content="text/html; charset=utf-8" />\n <meta name="viewport" content="width=device-width, initial-scale=1" />\n <style type="text/css">\n body {\n background-color: #f0f0f2;\n margin: 0;\n padding: 0;\n font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;\n \n }\n div {\n width: 600px;\n margin: 5em auto;\n padding: 2em;\n background-color: #fdfdff;\n border-radius: 0.5em;\n box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);\n }\n a:link, a:visited {\n color: https://github.com/ansible/awx-operator/issues/38…
PLAY RECAP *********************************************************************
localhost : ok=1 changed=0 unreachable=0 failed=1 skipped=0 rescued=0 ignored=0

Thanks for your support

### AWX version

23.5.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.14.2

### Operating system

Redhat 8.8

### Steps to reproduce

create insights project with insights credential and try to sync
job failed when trying to fetch playbooks

### Expected results

fetch playbooks from insights successfully

### Actual results

PLAY [Update source tree if necessary] *****************************************
TASK [Ensure the project directory is present] *********************************
ok: [localhost]
TASK [Fetch Insights Playbook(s)] **********************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Expected /api/remediations/v1/remediations to return a status code of 200 but returned status code \"404\" instead with content \"b'<!doctype html>\\n<html>\\n<head>\\n    <title>Example Domain</title>\\n\\n    <meta charset=\"utf-8\" />\\n    <meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\" />\\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\\n    <style type=\"text/css\">\\n    body {\\n        background-color: #f0f0f2;\\n        margin: 0;\\n        padding: 0;\\n        font-family: -apple-system, system-ui, BlinkMacSystemFont, \"Segoe UI\", \"Open Sans\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\\n        \\n    }\\n    div {\\n        width: 600px;\\n        margin: 5em auto;\\n        padding: 2em;\\n        background-color: #fdfdff;\\n        border-radius: 0.5em;\\n        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);\\n    }\\n    a:link, a:visited {\\n        color: #38…
PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

### Additional information

PLAY [Update source tree if necessary] *****************************************
TASK [Ensure the project directory is present] *********************************
ok: [localhost]
TASK [Fetch Insights Playbook(s)] **********************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Expected /api/remediations/v1/remediations to return a status code of 200 but returned status code \"404\" instead with content \"b'<!doctype html>\\n<html>\\n<head>\\n    <title>Example Domain</title>\\n\\n    <meta charset=\"utf-8\" />\\n    <meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\" />\\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\\n    <style type=\"text/css\">\\n    body {\\n        background-color: #f0f0f2;\\n        margin: 0;\\n        padding: 0;\\n        font-family: -apple-system, system-ui, BlinkMacSystemFont, \"Segoe UI\", \"Open Sans\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\\n        \\n    }\\n    div {\\n        width: 600px;\\n        margin: 5em auto;\\n        padding: 2em;\\n        background-color: #fdfdff;\\n        border-radius: 0.5em;\\n        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);\\n    }\\n    a:link, a:visited {\\n        color: #38…
PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by kurokobo** [comment]
Duplicate of: https://github.com/ansible/awx/issues/4447
Workaround: https://github.com/ansible/awx-operator/issues/930#issuecomment-1903910659

**Comment by bskou57** [comment]
Hi Kurokobo

works fine

Thanks again for your support

You can close the ticket

**Comment by fosterseth** [comment]
closing since this is dup, and workaround works
