### ISSUE TITLE
LDAP Organization Mapping Trailing Whitespace

### ISSUE THREAD

**Issue by hiddenicon** [ansible/awx#148]
- Bug Report

* AWX 1.0.0.350
* Ansible version:  2.3.1

When configuring the LDAP Organization Map under the LDAP settings, any trailing whitespaces will be taken and used. Example screenshot below will create an organization of "Network Team " when a "Network Team" is already in place. Whitespace characters are used in this case. 

This string should be trimmed before committing to the settings/DB.

I have not tested with beginning whitespaces or on any other text fields on the form. 

![image](https://user-images.githubusercontent.com/10273594/30355390-29424d38-9801-11e7-9a61-b9931e7daed1.png)

**Comment by matburt** [comment]
We don't currently perform any validation on inputs in this field, because it's kind-of a complex input. We'll pass this down into django-ldap/python-ldap and let the library handle anything of that nature.

I'm thinking we don't really want to be in the business of sanitizing strings like that.
