### ISSUE TITLE
job stay stuck in running status due to defunct process on the host

### ISSUE THREAD

**Issue by birb57** [ansible/awx#14808]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hi

I am running a job that simply upgrade my Red Hat servers but on 2 hosts dnf is in defunct status so job stuck in running status

can you please advise ?

thanks for your support

### AWX version

0.23.5

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.12.5

### Operating system

Red Hat 

### Web browser

Chrome

### Steps to reproduce

run job that execute yum upgrade on a host where yum/dnf commands are in defunct status

no yum/dnf command works

Thanks

### Expected results

job continue processing

### Actual results

job stay in running status but is not processing other hosts in the list and seems stuck on 2 hosts where dnf command are locked

**Comment by fosterseth** [comment]
Hi! thanks for detailing the issue.

Sounds like an ansible core issue, not AWX. Do you also experience this issue when running ansible through the command line, not through AWX?

This discussion seems relevant (using `async`) https://github.com/ansible/ansible/issues/30411#issuecomment-1772072672

**Comment by birb57** [comment]
Hello

Yes I also have the issue via command line

I will raise it in ansible async


Thanks
