### ISSUE TITLE
skipping: no hosts matched

### ISSUE THREAD

**Issue by birb57** [ansible/awx#14804]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hi

When I run job template if host is not available I got "skipping: no hosts matched" but job status is successful

Is it a normal behavior ?

Can I have a work around to set the job as failed ?

Thanks for your support

### AWX version

0.23.5

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.20

### Operating system

Red Hat 

### Web browser

Chrome

### Steps to reproduce

run a job on hosts which is not part of the inventory you will get "skipping: no hosts matched" and job finish with status of "Successful"
Why do not we get failed status for related job ?
 

### Expected results

job failed

### Actual results

job successful

**Comment by akira6592** [comment]
@birb57 Hello.

It is the default behavior of Ansible.

According on the setting of [`HOST_PATTERN_MISMATCH`](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#host-pattern-mismatch). The default is `warning` not `error`.

If you set `error` for this setting, the `no hosts matched` causes error as follows.

<img width="1440" alt="image" src="https://github.com/ansible/awx/assets/16851744/88ca8c07-8505-464b-b6a2-353d9d4fc6c4">


`ansible.cfg` sample

```ini
[inventory]
host_pattern_mismatch=error

**Comment by bskou57** [comment]
Hello akira6592 

works fine and should be enough

Thanks for your support

**Comment by akira6592** [comment]
@birb57 (@bskou57 ?)

My pleasure.
If resolved, could you please close this issue?
