### ISSUE TITLE
Cant create webhook notification with custom message

### ISSUE THREAD

**Issue by ingvarrwvw** [ansible/awx#14817]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hi!
I can create webhook notification via UI with custom message, like this:

{"key": "value", "text": "{{ job_friendly_name }} \"{{ job.name }}\" id {{ job.id }} had status {{ job.status }} [details]({{ url }})"}

But , i cant create the same notification via awx.awx collection, reason:

The error was: 'job_friendly_name' is undefined

### AWX version

21.4.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.13.7

### Operating system

Ubuntu

### Steps to reproduce

Run playbook, like this:

- name: Add notification with custom messages
  notification_template:
    name: test
    controller_host: host
    controller_oauthtoken: token
    organization: some_organization
    notification_type: webhook
    notification_configuration:
      url: some_url
      headers:
        X-APIToken: token
      http_method: POST
    messages:
       started:
         body: "{\"some_key\": \"some_value\", \"text\": \"{{  job_friendly_name }}\"}"

### Expected results

Notification created with custom message

### Actual results

Error:
 The error was: 'job_friendly_name' is undefined

**Comment by kurokobo** [comment]
@ingvarrwvw 
Hi, the `{{ ... }}` in strings is determined as Jinja2 template, so if you embed curly brackets itself in strings, we should escape these characters.
We can use `!unsafe` tag or `{% raw %} ... {% endraw %}`. Refer to this page: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_advanced_syntax.html

```yaml
messages:
  started:
    body: !unsafe '{"some_key": "some_value", "text": "{{ job_friendly_name }}"}'
```

If you have any further questions, create new topic on [the forum](https://forum.ansible.com/) since this is not a bug report nor RFE and this type of questions should be asked there instead.

**Comment by ingvarrwvw** [comment]
> @ingvarrwvw Hi, the `{{ ... }}` in strings is determined as Jinja2 template, so if you embed curly brackets itself in strings, we should escape these characters. We can use `!unsafe` tag or `{% raw %} ... {% endraw %}`. Refer to this page: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_advanced_syntax.html
> 
> ```yaml
> messages:
>   started:
>     body: !unsafe '{"some_key": "some_value", "text": "{{ job_friendly_name }}"}'
> ```
> 
> If you have any further questions, create new topic on [the forum](https://forum.ansible.com/) since this is not a bug report nor RFE and this type of questions should be asked there instead.

Yes, thank you!

**Comment by ingvarrwvw** [comment]
not a bag
