### ISSUE TITLE
how can I add folder inside web UI in Templates section

### ISSUE THREAD

**Issue by birb57** [ansible/awx#14818]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hi

how can I add folder inside web UI in Templates section ?

I want to organize my playbooks/templates by theme (os, network, storage, ...)

Thanks for your support

### AWX version

23.5.1

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.12.5

### Operating system

Red Hat 

### Web browser

Chrome

### Steps to reproduce

I want to create folder in web UI for Templates section

### Expected results

I want to have different folder to organize/sort my tempales

### Actual results

long list without organisation

### Additional information

none

**Comment by fosterseth** [comment]
Hello, this appears to be less of a bug report or feature request and more of a question. Could you please ask this on either the [Ansible AWX channel on Matrix](https://matrix.to/#/#awx:ansible.com) or the [Ansible Community Forum](https://forum.ansible.com/tag/awx)?
