### ISSUE TITLE
VirtualEnvironment not a valid python environment

### ISSUE THREAD

**Issue by pkennedymwg** [ansible/awx#1482]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

I pulled from devel on March 6th and everything installed fine.  Using the virtual env throws an error:

RuntimeError: a valid Python virtualenv does not exist at /var/lib/awx/venv/mwg/

##### ENVIRONMENT
* AWX version: 1.0.4.43
* AWX install method: docker on linux,
* Ansible version:  2.4.3.0
* Operating System:
* Web Browser: Chrome latest 

##### STEPS TO REPRODUCE

Set up a custom venv using instructions from:

https://github.com/ansible/awx/pull/940/files#diff-015b935452ac22e8799e290bcfa7cb07

sudo virtualenv /var/lib/awx/venv/mwg
sudo yum install python-devel
sudo /var/lib/awx/venv/mwg/bin/pip install python-memcached psutil
sudo /var/lib/awx/venv/mwg/bin/pip install f5-sdk
sudo /var/lib/awx/venv/mwg/bin/pip install bigsuds

Created it fine, memcahced and psutil installed fine.

(installed fe-sdk and bigsuds after)

I patched the job template to use it, and it is reflected in the UI for the job.  When I run the job i get:

Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 925, in run env = self.build_env(instance, **kwargs) File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 1143, in build_env env = self.add_ansible_venv(job.ansible_virtualenv_path, env, add_awx_lib=kwargs.get('isolated', False)) File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 753, in add_ansible_venv 'a valid Python virtualenv does not exist at {}'.format(venv_path) RuntimeError: a valid Python virtualenv does not exist at /var/lib/awx/venv/mwg/

##### EXPECTED RESULTS

To connect to F5 without bigsuds error

##### ACTUAL RESULTS

Bad virtual env

**Comment by ryanpetrello** [comment]
@pkennedymwg have you replicated the `virtualenv` creation steps on _all_ containers - particularly the task container where jobs actually run?

What happens if you run this adhoc command?

`ls -ls /var/lib/awx/venv/`

See: https://github.com/ansible/awx/pull/940/files#diff-015b935452ac22e8799e290bcfa7cb07R43

**Comment by pkennedymwg** [comment]
ugh.  i did not run it on the task server.  I just did and am getting a new error, but beyond the scope of this report.  Thanks.

received exception: <urlopen error [Errno -2] Name or service not known

**Comment by ryanpetrello** [comment]
At first glance, looks to me like a connectivity issue from the task container.  I'm going to go ahead and close out this issue since it relates to custom virtualenvs.
