### ISSUE TITLE
Can I get ride of unreachable hosts in awx job output

### ISSUE THREAD

**Issue by birb57** [ansible/awx#14824]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hi

Can I get ride of "unreachable" hosts in awx job output ?

From time to time we have many cloud vm down for different reason (but still in our inventory)

thanks for oyur support

### AWX version

23.6.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.12.5

### Operating system

Red Hat 

### Web browser

Chrome

### Steps to reproduce

Run job template or adhoc command with many hosts down you will see "host unreachable" in job output

### Expected results

no more "host unreachable" output

### Actual results

"host unreachable" is loggued many times in the output

**Comment by fosterseth** [comment]
Hello, this appears to be less of a bug report or feature request and more of a question. This is more of a question for ansible-core folks. Could you please ask this on either the [Ansible user channel on Matrix](https://matrix.to/#/#user:ansible.com) or the [Ansible-core Community Forum](https://forum.ansible.com/tag/ansible-core)?
