### ISSUE TITLE
Workflow Editor, tab elements don't disapear

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#1483]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
In the workflow editor. Job prompt fields carry over into the project list.

##### STEPS TO REPRODUCE

* Create a JT with lots of prompt things checked (Limit, Job Tags, Skip Tags)
* Click to add a node to the workflow
* Select the JT with prompts
* Now select the Project Sync tab

##### EXPECTED RESULTS

* For the Job Prompt fields to disappear

##### ACTUAL RESULTS

* The memory remains

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/722880/37175592-f9bbc8f6-22e7-11e8-9690-c47d09144a93.png)

![image](https://user-images.githubusercontent.com/722880/37175633-159bea06-22e8-11e8-9ce8-7dbf72a9380f.png)

**Comment by awithrow9** [comment]
please retest :-)

**Comment by mabashian** [comment]
Closing, those fields no longer appear beneath the list
