### ISSUE TITLE
Allow users to add a label to tasks in a workflow, so that jobs derived from same template can have different name

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#14836]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

Right now when you create a workflow that contains many instances of same template just with different variables, you can't distinguish which one is which, here is example:

![image](https://github.com/ansible/awx/assets/1560121/7471c326-9845-4d54-bc84-a384aa417c0f)

Those jobs look like 2 same jobs running in paralel, but their variables are completely different. However it's impossible to distinguish between them right now.

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

Make a workflow that contains multiple instances of same template with different variables

### Current results

Jobs are called exactly the same

### Sugested feature result

Each job would have a dedicated name to make it possible to see which one is which

**Comment by fosterseth** [comment]
there is a node alias you can use to distinguish different nodes, even if based on the same template

![image](https://github.com/ansible/awx/assets/8745776/fdf2de0f-65c0-4287-b34a-0c4c8a167036)

is this what you had in mind, or something else?
