### ISSUE TITLE
Why cant you use the Auth Type GitHub Personal Access Token in projects?

### ISSUE THREAD

**Issue by gsg-git** [ansible/awx#14845]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

Im new in AWX and still learning, but i stumbled about this and am a little confused, because it seems obious to me.
I m testing with github as datasource and couldnt get it to run uptil now with this PAT. used it in SC Private Key Passphrase.
I couldnt find anywhere where i could use the SigHub PAT - so why is there even this kind of Credentials?

Thank you very much in advance for your time!

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Steps to reproduce

-

### Current results

-

### Sugested feature result

-

**Comment by kurokobo** [comment]
The credential type that named `GitHub Personal Access Token` is designed for using webhooks: https://ansible.readthedocs.io/projects/awx/en/latest/userguide/webhooks.html#github-webhook-setup

If you want to use PAT for project, simply enter your PAT in `Password` field instead:

> You can use a personal access token in place of a password when authenticating to GitHub in the command line or with the API.
> https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens

**Comment by gsg-git** [comment]
Sadly i cant get anything to sync.
git pull shows the  data is correct:
![grafik](https://github.com/ansible/awx/assets/92863111/f7388f92-32bd-4cd2-bd78-d1a360da9f10)

But when i enter the PAT in the Password and sync:
![grafik](https://github.com/ansible/awx/assets/92863111/f4de074f-6e8a-4d15-b6a8-90c58dd67b3a)
![grafik](https://github.com/ansible/awx/assets/92863111/ea28fa07-b7d1-40f0-ba9b-0717d52babd4)
It fails:
![grafik](https://github.com/ansible/awx/assets/92863111/42cb072d-7b9c-4d8a-b792-b6def8fa17ee)

How is the communication? git pull too or ssh? I even added the Pubilc key in gitgub to be shure.

**Comment by kurokobo** [comment]
Username seems to be missing: 
![image](https://github.com/ansible/awx/assets/2920259/a4d52cb1-5a1b-4649-aee5-55f5936b4527)

**Comment by gsg-git** [comment]
Thank you @kurokobo!
I tried to use the github username password  and the PAT in Private Key Passphrase, but not like this.
I got the error that the regular credentials wherend supported anymore so i thought i just had to use the PAT.
Additionalls there is a guide somewhere i fond in which they told just to enter the PAT in the Private Key Passphrase and nothing else.

**Comment by gsg-git** [comment]
I got now how the credentials do theyr job - thank you very much!

**Comment by xue-kai-wen** [comment]
@gsg-git  Could you tell me how did you solve the same issue that I'm facing ？ thanks

**Comment by davidkingaz** [comment]
Just make sure you have your email address filled out and use your token in place the "password" field.  That should do it.
