### ISSUE TITLE
workflow status doesn't change from pending to running in UI

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#1484]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
* workflow status doesn't change from pending to running. It jumps straight to "successful"

##### STEPS TO REPRODUCE

* Create a workflow with a node or two
* Launch the workflow

##### EXPECTED RESULTS

* While watching the job results page for the workflow. I expect the job status to move from pending -> running -> successful

##### ACTUAL RESULTS

* Job results goes from pending -> successful

**Comment by jaredevantabor** [comment]
this is fixed now in devel
