### ISSUE TITLE
Feature: Autoscaling, isolated, containerized job running

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1485]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

Followon of https://github.com/ansible/awx/issues/1207

Essentially, once we can register an isolated node (or something like it) on demand, there's no reason how AWX runs jobs can't change to a simple:

- create job
- spin up a per-job-run container
- run job
- kill container

This has many followon questions:
- does this obsolete instance groups?
- how does this work with custom venvs?
- what's the best mechanism for passing the runtime environment?

In general, this requires that we be able to talk to our container orchestrator to spin up the job running containers. So this may limit supported platforms.

##### ENVIRONMENT
* AWX version: any

**Comment by cben** [comment]
Ignorant bystander question: could https://github.com/ansible/ansible-runner fulfill this role?

**Comment by dkraklan** [comment]
Is this implemented now? I'm struggling to find the documentation on setting this up? Specifically setting it up when I already have AWX installed.
