### ISSUE TITLE
Unable to add new execution instance with awx 23.xxx

### ISSUE THREAD

**Issue by Bergdolt** [ansible/awx#14880]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hello All,
I seems that adding a new execution instance is no more working with 23.xxx versions.
When you add à new execution instance in awx + download installer bundle + run it on node, there is no incoming network traffic on node (port 27199). 
In awx-task log say that:  awx.main.tasks.receptor Instance <XXX> is not in the receptor mesh. 9 attempts left.
I try with IP and FQDN same results. There is now firewall issue on node (port 27199 is open, and is listening)
It seem that the problem comes from awx not node.

### AWX version

23.7.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

23.7.0

### Operating system

RHEL9

### Web browser

Edge

### Steps to reproduce

on awx: create new execution instance (either with IP or FQDN, listener port 271099)
download installer bundler, run it on execution node
on awx click on "run health check"

### Expected results

on awx status should become availbale
expect to seen icomming network trafic on execution node port 27199

### Actual results

on awx: execution node status remain "unavailable"
on execution node no incomming network trafic on port 27199

### Additional information

no firewall issue between awx and exection node
on execution node port 27199 is listening

same with version 22.6.0 is working

**Comment by fosterseth** [comment]
can you make sure 'peers_from_control_nodes' is set to true for the execution node?

if you shell into your task container with:
`kubectl exec -it deploy/awx-task -c awx-task -- bash`
and run

`cat /etc/receptor/receptor.conf`

does it show tcp-peer entry for your execution node?

**Comment by Bergdolt** [comment]
Hello fosterseth,
thanks for your reply.
option "peers_from_control_nodes" was not set (I left default configuration)
I set the option et retry health check and now it is working.
Many thanks for the help.

**Comment by Bergdolt** [comment]
Issue is closed thanks to fosterseth

**Comment by fosterseth** [comment]
@Bergdolt thanks for confirming the fix and closing the issue!
