### ISSUE TITLE
awx-ee Error opening log stream for pod Failed to load  proxyconnect tcp: proxy error from 127.0.0.1:6443

### ISSUE THREAD

**Issue by pablodorao** [ansible/awx#14890]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hi. I have this message error form awx-ee.  Is possible try using some setting set proxy  in deploy awx? Where information deploy EE proxy vars?.

Failed to load logs: Get "https://node_ip:10250/containerLogs/awx-founos/awx-founos-task-679cf5fd5d-6bh9g/awx-founos-ee?tailLines=502&timestamps=true": proxyconnect tcp: proxy error from 127.0.0.1:6443 while dialing proxy.prd.prod:8080, code 502: 502 Bad Gateway

ERROR 2024/02/16 16:21:11 Error opening log stream for pod awx-founos/automation-job-201043-mcmnm. Error: Get "[https://node_ip:10250/containerLogs/awx-founos/automation-job-201043-mcmnm/worker?follow=true&sinceTime=0001-01-01T00%!A(MISSING)00%!A(MISSING)00Z&timestamps=true":](https://node_ip:10250/containerLogs/awx-founos/automation-job-201043-mcmnm/worker?follow=true&sinceTime=0001-01-01T00%!A(MISSING)00%!A(MISSING)00Z&timestamps=true%22:) proxyconnect tcp: proxy error from 127.0.0.1:6443 while dialing proxy.prd.prod:8080, code 502: 502 Bad Gateway

Regards

### AWX version

23.6.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

Launch Job template - Same issue all launch job.

### Expected results

Pass all run job template

### Actual results
```
Failed to JSON parse a line from worker stream. Error: Expecting value: line 1 column 1 (char 0) Line with invalid JSON data: b''
```
Receptor detail:
```
Error opening log stream for pod awx-founos/automation-job-201011-x2zrm. Error: Get "https://node_ip:10250/containerLogs/awx-founos/automation-job-201011-x2zrm/worker?follow=true&sinceTime=0001-01-01T00%3A00%3A00Z&timestamps=true": proxyconnect tcp: proxy error from 127.0.0.1:6443 while dialing proxy.prd.prod:8080, code 502: 502 Bad Gateway
```

**Comment by fosterseth** [comment]
do you have the receptor reconnect feature enabled on your awx spec?

https://github.com/ansible/receptor/pull/683

this might help with periodic bad gateway errors, if the proxy is just having a temporary blip

**Comment by TheRealHaoLiu** [comment]
```
Same issue all launch job.
```
indicate that this is not a blip 
```
Error opening log stream for pod awx-founos/automation-job-201011-x2zrm. Error: Get "https://node_ip:10250/containerLogs/awx-founos/automation-job-201011-x2zrm/worker?follow=true&sinceTime=0001-01-01T00%3A00%3A00Z&timestamps=true": proxyconnect tcp: proxy error from 127.0.0.1:6443 while dialing proxy.prd.prod:8080, code 502: 502 Bad Gateway
```
the error message indicate that receptor is failing to connect to kube apiserver from within the cluster this is an environmental/configuration issue
