### ISSUE TITLE
how can upgrade AWX 17.1.0 version to AWX 23.8.1 on RHEL 8.8 

### ISSUE THREAD

**Issue by gajit671** [ansible/awx#14894]
##### ISSUE TYPE

 - Breaking Change  
 - New or Enhanced Feature
 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - API
 - UI
 - Collection
 - Docs
 - CLI
 - Other

##### SUMMARY
 how can upgrade AWX 17.1.0 version to AWX 23.8.1 on RHEL 8.8 

##### ENVIRONMENT
* AWX version: AWX 17.1.0
* AWX install method: operator, developer environment
* AWX deployment target: normal
* Operating System: RHEL 8.8
* Web Browser: http://10.250.22.228/?credential_passwords.ssh_password=Ind%21an%40321#/login

##### STEPS TO REPRODUCE

 how can upgrade AWX 17.1.0 version to AWX 23.8.1 on RHEL 8.8 please share step by step

##### EXPECTED RESULTS

 how can upgrade AWX 17.1.0 version to AWX 23.8.1 on RHEL 8.8

##### ACTUAL RESULTS

 how can upgrade AWX 17.1.0 version to AWX 23.8.1 on RHEL 8.8

##### ADDITIONAL INFORMATION

how can upgrade AWX 17.1.0 version to AWX 23.8.1 on RHEL 8.8

**Comment by fosterseth** [comment]
please see these docs for migrating from older installations (<18) to current AWX

https://github.com/ansible/awx-operator/blob/fc11db4ececf3fa7197b3906f6a9c50e2e1b6bb1/docs/migration/migration.md
