### ISSUE TITLE
awx-task pod evicted and in ContainerStatusUnknown STATUS

### ISSUE THREAD

**Issue by fahadshery** [ansible/awx#14908]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hi,

I am trying to deploy awx in the cloud. 
I am following the official documentation. 
But for some reason the `wax-task` pod is being evicted...
I can't seem to check any logs either.
This is what I see...
![image](https://github.com/ansible/awx/assets/7301267/f129144c-afe0-4cd6-88ac-27da8d651b56)

any ideas?

### AWX version

2.11.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.11.0

### Operating system

Oracle 9

### Steps to reproduce

Follow the official customisation.yaml and awx.yaml files and then deploy using kubectl

### Expected results

all pods should be up and running

### Actual results

screenshot attached

**Comment by fosterseth** [comment]
Hello, this appears to be less of a bug report or feature request and more of a question. Could you please ask this on either the [Ansible AWX channel on Matrix](https://matrix.to/#/#awx:ansible.com) or the [Ansible Community Forum](https://forum.ansible.com/tag/awx)?
