### ISSUE TITLE
Unformatted help text is popped out when peers for intances are changed

### ISSUE THREAD

**Issue by kurokobo** [ansible/awx#14924]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Following unformatted help text (includes `{0}` and `{1}`) is popped out on the top-right corner when I change peers for any intances.

> Peers update on {0}. Please be sure to run the install bundle for {1} again in order to see changes take effect.

![image](https://github.com/ansible/awx/assets/2920259/91cb7395-d965-42b0-a93a-0d3b99c80f86)

### AWX version

23.8.1

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

N/A

### Operating system

CentOS Stream 8

### Web browser

Chrome

### Steps to reproduce

Unformatted help text will be popped out on the steps 4 and 5.

1. Add `hop01.example.com` as new hop node
2. Add `exec01.example.com` as new execution node, with port `27199`
3. Open `hop01.example.com` and move on to the `Peers` tab
4. Associate `exec01.example.com` as a peer
5. Remove `exec01.example.com` from peers

### Expected results

The help text should be

> Peers update on hop01.example.com. Please be sure to run the install bundle for hop01.example.com again in order to see changes take effect.

### Actual results

Help text contains `{0}` and `{1}`.

> Peers update on {0}. Please be sure to run the install bundle for {1} again in order to see changes take effect.

**Comment by thedoubl3j** [comment]
@fosterseth @TheRealHaoLiu @jbradberry

**Comment by jbradberry** [comment]
Format string in question is coming from here: https://github.com/ansible/awx/blob/devel/awx/ui/src/screens/Instances/InstancePeers/InstancePeerList.js#L194.

**Comment by jbradberry** [comment]
There is another similar format string in there, raising the question whether that one is broken as well.

**Comment by jbradberry** [comment]
cc @dmzoneill

**Comment by kurokobo** [comment]
Maybe Lingui related issue I guess

**Comment by dmzoneill** [comment]
https://github.com/ansible/awx/pull/14990

**Comment by jbradberry** [comment]
#14990 has merged.
