### ISSUE TITLE
Is there a way to get the awx user info in the launch job vars?

### ISSUE THREAD

**Issue by ngsin** [ansible/awx#14936]
### Please confirm the following

- [ ] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [ ] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [ ] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

when launch the job, get the awx user info from built-in  vars

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

when launch the job, get the awx user info from built-in  vars

### Current results

no user info found in ansible_env

### Sugested feature result

when launch the job, get the awx user info from built-in  vars

**Comment by thedoubl3j** [comment]
hey @ngsin this would be a good question for the forum, it can be found [here](https://forum.ansible.com/c/help/6/none).
