### ISSUE TITLE
AWX Community Meeting Agenda - March 2024

### ISSUE THREAD

**Issue by TheRealHaoLiu** [ansible/awx#14969]
# AWX Office Hours

## Proposed agenda based on topics
@thedoubl3j postgres 15 [upgrade](https://forum.ansible.com/t/awx-postgres-15-support-container-readiness-checks-available/4262)
@AlanCoding progress update/plan on RBAC changes
@fosterseth https://github.com/ansible/awx-operator/pull/1674 -ness check and migration change
@TheRealHaoLiu Bind EE images version with DEFAULT_AWX_VERSION https://github.com/ansible/awx-operator/pull/1740
@TheRealHaoLiu VScode Debugging demo #14942
## What

After a successful Contributor Summit in October 2023, one of the bits of feedback we got was to host a regular time for the Automation Controller (AWX) Team to be available for your folks in the AWX Community, so we are happy to announce a new regular video meeting.

This kind of feedback loop is vital to the success of AWX and the AWX team wants to make it as easy as possible for you - our community - to get involved.

## Where & When
Our next meeting will be held on Tuesday, March12 th, 2024 at [1500 UTC](https://dateful.com/time-zone-converter?t=15:00&tz=UTC)

* [Google Meet](https://meet.google.com/vyk-dfow-cfi)
* Via Phone PIN: 842522378 [Guide](https://support.google.com/meet/answer/9518557)

This meeting is held once a month, on the second Tuesday of the month, at [1500 UTC](https://dateful.com/time-zone-converter?t=15:00&tz=UTC)

## How

Add one topic per comment in this GitHub issue

If you don't have a GitHub account, jump on [#awx:ansible.com](https://matrix.to/#/#awx:ansible.com) on Matrix and we can add the topic for you

## Talk with us

As well as the fortnightly video meeting you can join the Community (inc development team) on Matrix Chat.

* Matrix: [#awx:ansible.com](https://matrix.to/#/#awx:ansible.com) (recomended)
* libera.chat IRC: `#ansible-awx` (If you are already setup on IRC)

The Matrix & IRC channels are bridged, you'll just have a better experience on Matrix

## Links
[AWX YouTube Chanel](https://www.youtube.com/@ansible-awx)
[Previous Meeting](https://github.com/ansible/awx/issues/14756)
[Meeting recording](https://youtu.be/i1Kd6ts0RNk)
[Next Meeting](https://github.com/ansible/awx/issues/15062)

See you soon!

**Comment by TheRealHaoLiu** [comment]
https://github.com/ansible/awx/pull/14942 demo vscode native debug workflow for awx development environment

**Comment by thedoubl3j** [comment]
@puiterwijk would you be interested in presenting/talking about #14628 at the next AWX community meeting? (no expected time amount etc, just a cool feature highlight if you want)

**Comment by puiterwijk** [comment]
> @puiterwijk would you be interested in presenting/talking about #14628 at the next AWX community meeting? (no expected time amount etc, just a cool feature highlight if you want)

@thedoubl3j sure, happy to do so.

**Comment by puiterwijk** [comment]
@thedoubl3j so, since this got reverted (#14977), do you still want me to join to highlight it?

**Comment by thedoubl3j** [comment]
@puiterwijk I think April or May meeting would be good time since we had to revert this. But if you can't make those (second tuesday of each month) then I would say now is fine. 

Its not a matter of if this will get merge but a matter of implementation and when I think.

**Comment by AlanCoding** [comment]
Need a link for RBAC content:

https://github.com/ansible/django-ansible-base/pull/45 --> https://github.com/ansible/awx/pull/14905

https://github.com/AlanCoding/django-ansible-base/blob/django_permissions/docs/apps/rbac.md
