### ISSUE TITLE
pls has configuration to set baseURL

### ISSUE THREAD

**Issue by gripenk** [ansible/awx#150]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- configuration

##### SUMMARY

the email / notification generated includes an URL to the job report but the domain name / baseURL is not corrected. 

##### STEPS TO REPRODUCE

configure a valid email notification
add and enable such notification to the job templates
launch the job template.

##### ACTUAL RESULTS

email got:

Job #54 had status successful, view details at https://towerhost/#/jobs/54

{
    "status": "successful", 
    "credential": "ssh_key", 
    "name": "hello1", 
    "started": "2017-09-13T03:35:40.394794+00:00", 
    "extra_vars": "{}", 
    "traceback": "", 
    "friendly_name": "Job", 
    "created_by": "admin", 
    "project": "webcloud1", 
    "url": "https://towerhost/#/jobs/54", 
    "finished": "2017-09-13T03:35:57.580014+00:00", 
    "hosts": {
        "10.10.3.54": {
            "skipped": 0, 
            "ok": 2, 
            "changed": 0, 
            "dark": 0, 
            "failed": false, 
            "processed": 1, 
            "failures": 0
        }
    }, 
    "playbook": "trunk/hello_world.yml", 
    "limit": "", 
    "id": 54, 
    "inventory": "webcloud1"
}

##### ADDITIONAL INFORMATION

- Suggestion
Add configuration to allow admin to define the baseURL of the AWX

**Comment by fchiacchiaretta** [comment]
You can find it in Settings -> System -> Base URL of the tower host.

**Comment by gripenk** [comment]
no such "Setting" / "System" item for image  awx_task 1.0.0.312

**Comment by fchiacchiaretta** [comment]
Maybe the version you are running is still affected by the side navigation panel bug (fixed now), try to zoom out the page to show the Settings menu entry in the side panel.
![screenshot from 2017-09-13 11-42-24](https://user-images.githubusercontent.com/23556082/30370910-450d288a-9879-11e7-946e-d226225c7305.png)
