### ISSUE TITLE
RFE: coalesce activity stream entries into fewer entries

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1500]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY

The activity stream is currently very fine-grained. While this allows detailed look at changes, this does lead to verbosity.

Many edits in AWX are a series of related changes - adding a user + associating it with an org/team. Adding a job template + adding a survey + adding permissions + adding notifications. An inventory update creates a flurry of activity stream entries for associating hosts to groups.

This leads to a very verbose activity stream, and collapsing some of these into single larger events may be useful.

##### ENVIRONMENT
* AWX version: any

**Comment by AlanCoding** [comment]
> An inventory update creates a flurry of activity stream entries for associating hosts to groups.

The activity stream does not show any activity related to creating hosts from inventory updates, nor would I expect it to.

I will see about confirming this, but if host-group entries are being generated from inventory updates, then those should simply be removed as a separate issue IMO.

EDIT: I cannot confirm that host-group associations from inventory updates show up, and I tend to think they don't.

**Comment by cchurch** [comment]
Inventory updates *should* only show in activity stream when `ACTIVITY_STREAM_ENABLED_FOR_INVENTORY_SYNC` is true, default is false.

**Comment by wenottingham** [comment]
closing old issue
