### ISSUE TITLE
Invalid JT warning misaligned

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1501]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

Create a JT. 
Delete its project.

The warning market is misaligned.

![screenshot from 2018-03-09 14-55-44](https://user-images.githubusercontent.com/5208768/37227131-2dcbf126-23aa-11e8-81ee-14b7984b3544.png)

##### ENVIRONMENT
* AWX version: 1.0.4.64
* AWX install method: docker on linux
* Browser: Firefox 58.0.2

##### ADDITIONAL INFORMATION

May be fixed by #1499?

**Comment by jaredevantabor** [comment]
this is fixed now in devel
