### ISSUE TITLE
awx.awx.application does not return the application client_secret

### ISSUE THREAD

**Issue by alice-rc** [ansible/awx#15028]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

When using the collection module awx.awx.application it does not return the client_secret which is unobtainable after creation.

### AWX version

24.0.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

yes

### Ansible version

2.15.9

### Operating system

N/A

### Steps to reproduce

```
- name: applications | Create AWX application
  awx.awx.application:
    controller_config_file : "{{ gv_awx_controller_config_file }}"
    name: Test App
    organization: XXX
    authorization_grant_type: password
    client_type: confidential
    state: present
  register: _application_creation

- debug:
    var: _application_creation
```

### Expected results

```
_application_creation": {
    "changed": true,
    "failed": false,
    "id": 3,
    "name": "Test App"
    "client_id": "y8mys4bSpk49sEqMCez3E4ss995h1Zu8cwCGRlfA",
    "client_secret": "jCyr7oPR5PNZt7BsFEr96nnjcc6cyjNxS2nsuMPwK8hRgf7dgCO8tbSoPgysMFGFOPiAmPiIk5SEmLP7bWSgF3QKOs2tOEjUDK3dmSW98WHtp3hQtnQPYe4dqMNXAS2K"
}
```

### Actual results

```
_application_creation": {
    "changed": true,
    "failed": false,
    "id": 3,
    "name": "Test App"
}
```

### Additional information

installation, deployment topology, or container images not relevant to collection function
Collection Version
awx.awx  24.0.0

**Comment by fosterseth** [comment]
@alice-rc do you know what version of AWX this was last working for you? we are making a lot of changes around auth at the moment, so we may have broke the endpoint at some point

**Comment by jbradberry** [comment]
I've just checked the api endpoint results in my development environment, and it does have the expected behavior there.

**Comment by jbradberry** [comment]
I have confirmed, this module was not set up to properly output this information.  PR forthcoming.

**Comment by jbradberry** [comment]
#15045 has merged.
