### ISSUE TITLE
Launch icon shown for invalid job templates

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1503]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

![screenshot from 2018-03-09 15-05-32](https://user-images.githubusercontent.com/5208768/37227490-6f7d4b5a-23ab-11e8-975d-c5baf097d896.png)

The launch icon shouldn't be there. (It doesn't do anything if clicked.)

##### ENVIRONMENT
* AWX version: 1.0.4.64
* Web Browser: Firefox 58.0.2

**Comment by jaredevantabor** [comment]
this is fixed now in devel
