### ISSUE TITLE
Every single request with a token makes an activity stream entry

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#1505]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Making a request using a PAT as authentication leaves an activity stream entry in its wake.

##### ENVIRONMENT
* AWX version: 1.0.4-171
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version: N/A
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Use the branch for tower-cli oauth2 support (thanks @ryanpetrello !)

```
tower-cli login admin
tower-cli user list
tower-cli user list
tower-cli user list
tower-cli user list
```

##### EXPECTED RESULTS

1 activity stream entry.

If that. 0 sounds more reasonable

##### ACTUAL RESULTS

2 for logging in.

4 more entries, one for each `user list` command issued.

One of the entries from the list command

```json
{
    "id": 595,
    "type": "activity_stream",
    "url": "/api/v2/activity_stream/595/",
    "related": {
        "access_token": "*************",
        "actor": "/api/v2/users/1/"
    },
    "summary_fields": {
        "actor": {
            "username": "admin",
            "first_name": "",
            "last_name": "",
            "id": 1
        },
        "access_token": "*************"
    },
    "timestamp": "2018-03-09T20:03:02.068234Z",
    "operation": "update",
    "changes": {
        "last_used": [
            "2018-03-09 20:02:30.950601+00:00",
            "2018-03-09 20:03:02.001484+00:00"
        ]
    },
    "object1": "o_auth2_access_token",
    "object2": "",
    "object_association": ""
}
```

**Comment by matburt** [comment]
Sooo... probably shouldn't be *every* request.

**Comment by rooftopcellist** [comment]
After talking with Alan, the issue seems to be that the "last_used" field is being updated, and as a result, that update is being added to the ActivitySerializer for that token.  I will look into removing this.  It is likely in the `activity_stream_update` in `signals.py`.

**Comment by AlanCoding** [comment]
I would process this special-case here

https://github.com/ansible/awx/blob/953850a0d7875b7a6d18f79ded5059a3083d52c5/awx/main/utils/common.py#L337

**Comment by rooftopcellist** [comment]
resolved and verified downstream.  closing.
