### ISSUE TITLE
AWX Community Meeting Agenda - April 2024 

### ISSUE THREAD

**Issue by TheRealHaoLiu** [ansible/awx#15062]
# AWX Office Hours

## Proposed agenda based on topics
@TheRealHaoLiu fall out of the postgres 15 upgrade
- [Data lost after restarting postgres-15 pod after upgrading to awx-operator 2.13.0 ](https://github.com/ansible/awx-operator/issues/1768)
- [Postgres 15 pod: cannot create directory '/var/lib/pgsql/data/userdata': Permission](https://github.com/ansible/awx-operator/issues/1770)
- [postgres_data_path not respected by postgres-15 causing data lost](https://github.com/ansible/awx-operator/issues/1790) 
- [awx migration pod issue with custom ca ](https://github.com/ansible/awx-operator/issues/1782) 

@TheRealHaoLiu ARM64 AWX image release coming in future release https://github.com/ansible/awx/pull/15053

This afternoon's release will also contain fixes for the `postgres_data_path` parameter issue as well as the `/var/lib/pgsql/data/userdata` permissions issue, both of which are related to the sclorg postgresql image change.  Please refer to the following docs for more information on that:
* https://ansible.readthedocs.io/projects/awx-operator/en/latest/user-guide/database-configuration.html?h=databas#note-about-overriding-the-postgres-image

## What

After a successful Contributor Summit in October 2023, one of the bits of feedback we got was to host a regular time for the Automation Controller (AWX) Team to be available for your folks in the AWX Community, so we are happy to announce a new regular video meeting.

This kind of feedback loop is vital to the success of AWX and the AWX team wants to make it as easy as possible for you - our community - to get involved.

## Where & When
Our next meeting will be held on Tuesday, April 9th, 2024 at [1500 UTC](https://dateful.com/time-zone-converter?t=15:00&tz=UTC)

* [Google Meet](https://meet.google.com/vyk-dfow-cfi)
* Via Phone PIN: 842522378 [Guide](https://support.google.com/meet/answer/9518557)

This meeting is held once a month, on the second Tuesday of the month, at [1500 UTC](https://dateful.com/time-zone-converter?t=15:00&tz=UTC)

## How

Add one topic per comment in this GitHub issue

If you don't have a GitHub account, jump on [#awx:ansible.com](https://matrix.to/#/#awx:ansible.com) on Matrix and we can add the topic for you

## Talk with us

As well as the fortnightly video meeting you can join the Community (inc development team) on Matrix Chat.

* Matrix: [#awx:ansible.com](https://matrix.to/#/#awx:ansible.com) (recomended)
* libera.chat IRC: `#ansible-awx` (If you are already setup on IRC)

The Matrix & IRC channels are bridged, you'll just have a better experience on Matrix

## Links
[AWX YouTube Chanel](https://www.youtube.com/@ansible-awx)
[Previous Meeting](https://github.com/ansible/awx/issues/14969)
Meeting recording
Next Meeting

See you soon!

**Comment by thedoubl3j** [comment]
recording posted, https://www.youtube.com/watch?v=oBd0e2pzGxE. closing issue and spawning next months.
