### ISSUE TITLE
Be able to sort projects by last updated

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1506]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY

The 'Last updated' field of the project list isn't sortable. It should be.

![screenshot from 2018-03-09 15-13-52](https://user-images.githubusercontent.com/5208768/37227831-8b0ff1b4-23ac-11e8-9933-d1af4c9fb7c4.png)

##### ENVIRONMENT
* AWX version: 1.0.4.64

##### ADDITIONAL INFORMATION

Having it be sortable by revision is a really weird thing to do, especially with git.

**Comment by mabashian** [comment]
<img width="1438" alt="screen shot 2018-11-26 at 3 30 38 pm" src="https://user-images.githubusercontent.com/9889020/49040333-43360b00-f190-11e8-8d28-67262c02ec35.png">

I'm not sure what the expectation is now that the projects list has changed and no longer has columns

**Comment by mabashian** [comment]
New UI has the same columns as before - still relevant.

**Comment by mabashian** [comment]
Last updated is shown in the expanded row view so sorting by it would now be quite clunky.
