### ISSUE TITLE
'Completed job' list is sorted by ID, not completed date

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1507]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY

The 'completed jobs' list for a job template by default is sorted by ID. Sorting by 'completed date (newest first)' would be more useful with how people usually use it.

##### ENVIRONMENT
* AWX version: 1.0.4.64

**Comment by mabashian** [comment]
I thought this might have been addressed when we re-worked the jobs list but it seems that it was not.  We're still making a request that looks like:

`/api/v2/unified_jobs/?page_size=20&job__job_template={:id}&order_by=-id`

**Comment by mabashian** [comment]
New UI makes a request like: `/api/v2/unified_jobs/?job__job_template={id}&not__launch_type=sync&order_by=-finished&page=1&page_size=20` so I think we're good here - closing.
