### ISSUE TITLE
Duplicate help text for token expiration settings in edit mode

### ISSUE THREAD

**Issue by irozet12** [ansible/awx#15076]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Settings > Miscellaneous Authentication > Edit

Fields 'Access Token Expiration', 'Refresh Token Expiration', 'Authorization Code Expiration' have the same help message:

 'Dictionary for customizing OAuth 2 timeouts, available items are `ACCESS_TOKEN_EXPIRE_SECONDS`, the duration of access tokens in the number of seconds, `AUTHORIZATION_CODE_EXPIRE_SECONDS`, the duration of authorization codes in the number of seconds, and `REFRESH_TOKEN_EXPIRE_SECONDS`, the duration of refresh tokens, after expired access tokens, in the number of seconds.'

### AWX version

22.1.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Steps to reproduce

1. Go to Settings > Miscellaneous Authentication settings
2. Click Edit
3. Check help message of  'Access Token Expiration', 'Refresh Token Expiration', 'Authorization Code Expiration' fields

### Expected results

Each field has its own help message

### Actual results

All 2 fields have the same help message, namely 'Dictionary for customizing OAuth 2 timeouts, available items are `ACCESS_TOKEN_EXPIRE_SECONDS`, the duration of access tokens in the number of seconds, `AUTHORIZATION_CODE_EXPIRE_SECONDS`, the duration of authorization codes in the number of seconds, and `REFRESH_TOKEN_EXPIRE_SECONDS`, the duration of refresh tokens, after expired access tokens, in the number of seconds.'

**Comment by fosterseth** [comment]
good catch, thanks for raising this issue
