### ISSUE TITLE
ARM64 system - AWX image pull failing

### ISSUE THREAD

**Issue by alensfor** [ansible/awx#15079]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

I might need a clarification maybe, more than technical help as I am probably doing something wrong.
My deployment of AWX via AWX-Operator is failing on an ARM64 CPU system, despite pulling an AWX image that is supposed to be compatible with AMD64 (quay.io/ansible/awx:23.9.0)

The awx-web pod (kubernetes) fails to find a suitable image.
But since AWX 23.8.1 (https://github.com/ansible/awx/releases) or 23.9.0 (https://forum.ansible.com/t/announcing-awx-23-9-0-and-awx-operator-2-12-2/4178) ARM64 system should have an image... correct ?

```
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  21m                 default-scheduler  Successfully assigned awx/awx-web-55d5d78c97-hfdw4 to ip-xxx
  Normal   Pulled     21m                 kubelet            Container image "quay.io/ansible/awx-ee:latest" already present on machine
  Normal   Created    21m                 kubelet            Created container init
  Normal   Started    21m                 kubelet            Started container init
  Normal   Pulled     21m                 kubelet            Container image "quay.io/centos/centos:stream9" already present on machine
  Normal   Created    21m                 kubelet            Created container init-projects
  Normal   Started    21m                 kubelet            Started container init-projects
  Normal   Pulled     21m                 kubelet            Container image "docker.io/redis:7" already present on machine
  Normal   Created    21m                 kubelet            Created container redis
  Normal   Started    21m                 kubelet            Started container redis
  Normal   Pulling    20m (x2 over 21m)   kubelet            Pulling image "quay.io/ansible/awx:23.9.0"
  Warning  Failed     20m (x2 over 21m)   kubelet            Failed to pull image "quay.io/ansible/awx:23.9.0": rpc error: code = NotFound desc = failed to pull and unpack image "quay.io/ansible/awx:23.9.0": no match for platform in manifest: not found
  Warning  Failed     20m (x2 over 21m)   kubelet            Error: ErrImagePull
  Normal   BackOff    20m (x3 over 21m)   kubelet            Back-off pulling image "quay.io/ansible/awx:23.9.0"
  Warning  Failed     20m (x3 over 21m)   kubelet            Error: ImagePullBackOff
  Warning  Failed     20m (x2 over 21m)   kubelet            Error: ImagePullBackOff
  Normal   BackOff    61s (x85 over 21m)  kubelet            Back-off pulling image "quay.io/ansible/awx:23.9.0"
```
  
  This is the CPU on this server
```
  $ lscpu
Architecture:             aarch64
  CPU op-mode(s):         32-bit, 64-bit
  Byte Order:             Little Endian
CPU(s):                   2
  On-line CPU(s) list:    0,1
Vendor ID:                ARM
  Model name:             Neoverse-N1
    Model:                1
    Thread(s) per core:   1
    Core(s) per socket:   2
    Socket(s):            1
    Stepping:             r3p1
    BogoMIPS:             243.75
```

Am I missing an important detail here, or, I'm too impatient and this work needs to be completed first https://github.com/ansible/awx/issues/14643 ?
Thank you all.

### AWX version

23.9.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

NA

### Operating system

Amazon Linux 2023

### Steps to reproduce

Run AWX operator install similar to how it was successfully installing AWX on ADM64 systems.

### Expected results

A successful install of AWX components.

### Actual results

awx web pod cannot be completed.

**Comment by kurokobo** [comment]
@alensfor 
The `awx` images for ARM64 are NOT available on quay.io yet. Currently they are only available on ghcr.io with limited tags.
The fix to release images for ARM64 on quay.io is still in progress by @TheRealHaoLiu  on https://github.com/ansible/awx/pull/15053#issuecomment-2043062636 so if it's okay for you to just wait, simply wait this PR to be merged and new AWX to be released.

If you are interested in testing ARM images that still under development, refer to the PR and specify custom images via Operator :smiley:

**Comment by alensfor** [comment]
Many thanks for the quick reply.
So we do have an `awx-operator` image available for arm64 but not the `awx` image ...yet. Understood. 
I am definitely interested in testing the work from @TheRealHaoLiu , I will search how to customize your `awx-on-k3s` repo to test this image, thank you all for the work you are doing !
Feel free to close my question/bug post.

**Comment by TheRealHaoLiu** [comment]
i provided the awx resource for using the arm image build from my fork in #15053
