### ISSUE TITLE
Are `ghcr.io/ansible/awx_devel` Docker images supported?

### ISSUE THREAD

**Issue by AlexPykavy** [ansible/awx#15082]
Hi,

Sorry for not following the issue template. I'm trying to install AWX locally to play with it. The best solution I found is to follow the https://github.com/ansible/awx/blob/devel/tools/docker-compose/README.md which instructs to:
- build the `awx_devel` Docker image via `make docker-compose-build`
- run the AWX via `make docker-compose`

I noticed that there are existing https://github.com/ansible/awx/pkgs/container/awx_devel images which are frequently updated. The questions I have are:
- Are these images supported? May we use them and skip the `make docker-compose-build`?
- If so, may I update the docs? If not, may we start publishing and supporting them?

**Comment by fosterseth** [comment]
> Are these images supported? May we use them and skip the make docker-compose-build?

yep they are supported, and we rely on the prebuilt images heavily for local development. running `make docker-compose-build` should only be needed if those prebuilt images don't work on your system for some reason, or have altered requirements/requirements.yml

> If so, may I update the docs? If not, may we start publishing and supporting them?

I think we can highlight that building the image may be optional, and emphasize that prebuilt images are on ghcr registry

a PR making that change would be welcomed
