### ISSUE TITLE
Build of 24.2.0 image failed

### ISSUE THREAD

**Issue by Nachichuri** [ansible/awx#15088]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Build and push of the 24.2.0 release image failed 2 hours ago:
https://github.com/ansible/awx/actions/runs/8619697870/job/23626024956#step:8:147

And operator version 2.15.0 is already depending on that image tag:
https://github.com/ansible/awx-operator/releases/tag/2.15.0

Do we have an ETA on when the build job will be retriggered? Thanks

### AWX version

24.2.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

Deploy AWX using the AWX operator

### Expected results

Image can be pulled

### Actual results

Image can't be pulled since tag doesn't exist

**Comment by kurokobo** [comment]
Failed logs on Galaxy side: https://galaxy.ansible.com/ui/repo/published/awx/awx/import-log/

**Comment by tanganellilore** [comment]
Pipeline weeror: https://github.com/ansible/awx/actions/runs/8619697870/job/23626024956

**Comment by rooftopcellist** [comment]
Looks like it failed while pushing the awx.awx collection to [galaxy.ansible.com](http://galaxy.ansible.com/).  We should add a rescue/retry task for that as [galaxy.ansible.com](http://galaxy.ansible.com/) can sometimes be flaky.
The images didn't get pushed because the workflow failed earlier (when pushing the collection)

Weird, in the logs on galaxy.ansible.com you linked I see this error:
```
[ErrorDetail(string='Collection awx.awx-24.2.0 already exists with a different artifact', code='invalid')]
```

However, the promote workflow was only run once as far as I can tell.  It looks like this sort of thing has happened before and we just need to try re-uploading:
* https://github.com/ansible/galaxy/issues/2823

**Comment by florianbeer** [comment]
Can any one of you trigger a rebuild?

I am still waiting for my ImagePullBackoff pods to recover.
ansible/awx-operator already references this tag since 19 hours ago, so all deployments with the latest version are consistently failing for that long for everyone.

**Comment by TheRealHaoLiu** [comment]
Got snagged on a CI failure when try to fix the publish failure 

Need to force merge that galaxy publishing fix and retrigger the publishing workflow

**Comment by TheRealHaoLiu** [comment]
https://github.com/ansible/awx/pull/15086

**Comment by TheRealHaoLiu** [comment]
Note to self. Do not publish operator until AWX image has published successfully.

**Comment by Nachichuri** [comment]
Image 24.2.0 already available in registry https://quay.io/repository/ansible/awx?tab=tags

Working as expected. Thanks!

**Comment by florianbeer** [comment]
Can confirm, all my pods where able to pull the new image.
Thanks!

But now the link to the new UI (ui_next) results in a 404
