### ISSUE TITLE
Workflow editor is not responsive

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1508]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY

The workflow editor is not very responsive to all display sizes. It should be!

Sample mockup:

![image](https://user-images.githubusercontent.com/13351591/28885808-266cd05c-7785-11e7-9947-c46c1cc0580e.png)

##### ENVIRONMENT
* AWX version: 1.0.4.64

**Comment by shanemcd** [comment]
This _seems_ to be better in the new UI?
