### ISSUE TITLE
AWX Community Meeting Agenda - May 2024

### ISSUE THREAD

**Issue by thedoubl3j** [ansible/awx#15099]
# AWX Office Hours

## What

After a successful Contributor Summit in October 2023, one of the bits of feedback we got was to host a regular time for the Automation Controller (AWX) Team to be available for your folks in the AWX Community, so we are happy to announce a new regular video meeting.

This kind of feedback loop is vital to the success of AWX and the AWX team wants to make it as easy as possible for you - our community - to get involved.

## Where & When
Our next meeting will be held on Tuesday, April 9th, 2024 at [1500 UTC](https://dateful.com/time-zone-converter?t=15:00&tz=UTC)

* [Google Meet](https://meet.google.com/vyk-dfow-cfi)
* Via Phone PIN: 842522378 [Guide](https://support.google.com/meet/answer/9518557)

This meeting is held once a month, on the second Tuesday of the month, at [1500 UTC](https://dateful.com/time-zone-converter?t=15:00&tz=UTC)

## How

Add one topic per comment in this GitHub issue

If you don't have a GitHub account, jump on [#awx:ansible.com](https://matrix.to/#/#awx:ansible.com) on Matrix and we can add the topic for you

## Talk with us

As well as the fortnightly video meeting you can join the Community (inc development team) on Matrix Chat.

* Matrix: [#awx:ansible.com](https://matrix.to/#/#awx:ansible.com) (recomended)
* libera.chat IRC: `#ansible-awx` (If you are already setup on IRC)

The Matrix & IRC channels are bridged, you'll just have a better experience on Matrix

## Links
[AWX YouTube Chanel](https://www.youtube.com/@ansible-awx)
[Previous Meeting](https://github.com/ansible/awx/issues/14969)
[Meeting recording](https://youtu.be/w2wdjxE2UhE)
[Next Meeting](https://github.com/ansible/awx/issues/15236)

See you soon!

**Comment by abhijeet-AT** [comment]
please give us some updates on this https://github.com/ansible/awx/issues/20

**Comment by TheRealHaoLiu** [comment]
I will be at Red Hat Summit and Ansible Fest giving a talk about the AWX Community. If I am able to I want to be able to give the presentation at the community meeting too

**Comment by TheRealHaoLiu** [comment]
ok lets talk about issue #20 I also open a forum post for us to iterate on the design https://forum.ansible.com/t/programable-survey-feature-in-awx/5806/2
