### ISSUE TITLE
'Jobs' view should have an activity stream link

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1509]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY

When viewing the activity stream, you can click 'Jobs' on the filter to show job related entries.

Hence, the jobs panel should have an activity stream link that goes there (a la other pages).

##### ENVIRONMENT
* AWX version: 1.0.4.64

**Comment by mabashian** [comment]
This was fixed somewhere along the line - likely when the jobs list was reworked.

![jobs_activity_stream](https://user-images.githubusercontent.com/9889020/49040600-04ed1b80-f191-11e8-8cb8-304ba527bb9d.gif)
