### ISSUE TITLE
200MB repository

### ISSUE THREAD

**Issue by calston** [ansible/awx#151]
Abandoning the template, makes no sense in this instance. 

Checking out the repository is 200MB for a total of 20MB worth of actual content. I guess there was massive churn on a binary object somewhere or something and that ref should probably be dropped from the repo to save people time. Might not seem important but bandwidth isn't great everywhere on earth.

**Comment by matburt** [comment]
okay

**Comment by calston** [comment]
You're okay with a broken repo?@matburt

**Comment by matburt** [comment]
There's no churn on any binary objects. Any old images have been removed, old branches have been purged, and the repository has been GCed. I'm sorry if that doesn't work for you, but it works fine here.

**Comment by cchurch** [comment]
@calston You can use the `--depth` or `--shallow-since` options to `git clone` to avoid retrieving the full history.
