### ISSUE TITLE
Pass full AWX user as extra var

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1515]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY

We pass `*_user_name` and `*_user_id` to jobs launched by a user. It could be useful to pass other
user fields (email, etc.) or perhaps the whole user structure.

##### ENVIRONMENT
* AWX version: any

##### ADDITIONAL INFORMATION

This should come with the understanding that fields beyond username/id are mutable by the user in many cases.

**Comment by matburt** [comment]
implemented in #1542
