### ISSUE TITLE
Expanding job's output window option not available anymore

### ISSUE THREAD

**Issue by vibhorkumaragarwal** [ansible/awx#15157]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

We used to have an option to expand job's output window via button like below:
![image](https://github.com/ansible/awx/assets/93639256/8794f969-e96f-43c5-86a2-f37744defd62)

It seems to be no longer available in AWX now.
Feasible to get it back?

### AWX version

23.9.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Steps to reproduce

Install AWX, expand option not available in job output.

### Expected results

Nice to have that option :)

### Actual results

Not available

**Comment by TheRealHaoLiu** [comment]
ur right this is not available in the current awx UI, we are migrating to the next iteration of the UI this might be a feature request for https://github.com/ansible/ansible-ui

closing this issue as Not a bug
