### ISSUE TITLE
AWX 24.3.1  - quay.io/ansible/awx:24.3.1: not found

### ISSUE THREAD

**Issue by moreirodamian** [ansible/awx#15158]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Error after updating to version 24.3.1.

The image: quay.io/ansible/awx:24.3.1 is not available.

### AWX version

24.3.1.

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

Install AWX 24.3.1.

### Expected results

Running correctly

### Actual results

Failed to pull image "quay.io/ansible/awx:24.3.1": rpc error: code = NotFound desc = failed to pull and unpack image "quay.io/ansible/awx:24.3.1": failed to resolve reference "quay.io/ansible/awx:24.3.1": quay.io/ansible/awx:24.3.1: not found

**Comment by fosterseth** [comment]
thanks, we had some github workflow issues that we are working out, images should be available soon

**Comment by rooftopcellist** [comment]
The images for 24.3.1 are availble on quay.io now, thanks for bringing this issue to our attention!

The collection needs to be uploaded still, that may not happen until tomorrow, so I'll leave this issue open to track that.
* https://galaxy.ansible.com/ui/repo/published/awx/awx/

cc @thedoubl3j

**Comment by thedoubl3j** [comment]
collection is up and available, closing out the issue now.
