### ISSUE TITLE
Use select/prefetch_related for inherited models if it ever exists

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1516]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY

Someday, django-polymorphic might implement https://github.com/django-polymorphic/django-polymorphic/issues/198.

If that glorious future comes to pass, we should use it.

##### ENVIRONMENT
* AWX version: any

**Comment by AlanCoding** [comment]
Rolling bounty for issue:

https://www.bountysource.com/issues/30802552-select_related-and-prefetch_related-for-inherited-models

**Comment by TheRealHaoLiu** [comment]
from the future... still not there yet we can keep waiting...

**Comment by TheRealHaoLiu** [comment]
lost hope... closing
