### ISSUE TITLE
concurrent jobs limit

### ISSUE THREAD

**Issue by zholbrook** [ansible/awx#15167]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

I would like to be able to allow concurrent jobs on a workflow or job template but also set the max number of concurrent jobs. Then after X number of jobs start queuing them. 

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

Any workflow as the concurrent jobs option

### Current results

In EKS after about 150 workflow jobs with 10 job tasks under i start to have job failures

### Sugested feature result

All to queue any number of workflow jobs but only X number will run at any give time.

**Comment by marek1712** [comment]
If your jobs run under common Instance Group, you could assign max number of forks and concurrent jobs. See the [LINK](https://docs.ansible.com/automation-controller/latest/html/userguide/instance_groups.html).
Does it help in your case?

**Comment by zholbrook** [comment]
Its not exactly what i want but i think it will be good enough to use the instance group limits. thanks!
