### ISSUE TITLE
Figure out how to translate credential help text

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1517]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY

The `help_text` of a credential type field is defined inside of the JSON definition of the fields in the database, getting translations for this is different from ordinary fields and will take extra work to solve.

This is only a problem for managed_by_tower credential types. Users will write help text for their custom types in whatever language they prefer.

Right now the `help_text` is static. This issue is to make it translated like how other text is translated.

##### ENVIRONMENT
* AWX version: any

**Comment by ryanpetrello** [comment]
Resolved downstream.
