### ISSUE TITLE
Playbooks are not discovered in subdirectories within git project

### ISSUE THREAD

**Issue by YaronL16** [ansible/awx#15187]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Suppose I have this repo:
```
+ Git Repository
    playbook1.yml
    + ansible_directory
        playbook2.yaml
        + playbooks_directory
            playbook3.yml
```

When creating a template, only playbook 1 and 2 will be available to choose. files more than one directories deep within the repo are not discovered, which is a shame for those using large repos.

### AWX version

24.2

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

normal install using operator
add a git based project with playbooks inside subdirectories

### Expected results

I'd expect too be able to choose all playbooks in the repo

### Actual results

I can only choose playbooks which are 0 or 1 subdirectories deep

**Comment by kurokobo** [comment]
Hi, is your `playbook3.yml` valid playbook? AWX does not list all existing YAML files but list YAML files that can be determined as playbooks. Also there is no limitation about the depth of the sub directories.

**Comment by TheRealHaoLiu** [comment]
https://github.com/ansible/awx/blob/devel/awx/main/utils/ansible.py/#L42-L66
this is how we determine if a yaml file "could be a playbook"

**Comment by TheRealHaoLiu** [comment]
and here's the regex used to https://github.com/ansible/awx/blob/devel/awx/main/utils/ansible.py#L20 to scan the lines to determine if it "could be a playbook"

**Comment by YaronL16** [comment]
> Hi, is your `playbook3.yml` valid playbook? AWX does not list all existing YAML files but list YAML files that can be determined as playbooks. Also there is no limitation about the depth of the sub directories.

@kurokobo all 3 playbooks are exactly the same. It couldn't be a problem with the file itself

**Comment by YaronL16** [comment]
> and here's the regex used to https://github.com/ansible/awx/blob/devel/awx/main/utils/ansible.py#L20 to scan the lines to determine if it "could be a playbook"

That shouldn't make much difference because the playbooks are identical yet only the first two are detected

**Comment by kurokobo** [comment]
Hmm okay, so please check:

- Project is synced and its revision is up-to-date, if your project on the SCM.
- Check if the result contains correct playbooks by querying `https://<YOUR AWX>/api/v2/projects/<PROJECT ID>/playbooks/`
- Try super-reloading your browser on the `Create New Job Template` page

**Comment by YaronL16** [comment]
Okay after diving into the code I realize my problem

Apparently the project function skips any directory named `roles` which is exactly where my playbooks were placed, and ignores any files under it

Thats why my playbooks did not show up, after renaming `roles` to `playbooks` it works perfectly
