### ISSUE TITLE
adding up multiple variables to host via api ends up with {"variables":["Not a valid string."]}

### ISSUE THREAD

**Issue by suppqt** [ansible/awx#15209]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Might be related to https://github.com/ansible/awx/pull/14585 fixxed in https://github.com/ansible/awx/releases/tag/23.4.0

Adding multiple variables to host ends up with given error message.

`$body = @{
      "variables" = @(
        "last_seen: $lastseen",
        "os_version: $os"
       )
    }`

`iwr -Uri $uri -UseBasicParsing -Headers $header -Body ($body|ConvertTo-Json) -Method PATCH -ContentType "application/json`

### AWX version

23.8.1

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

create powershell json body like given
push to host api 

### Expected results

multiple variables getting added

### Actual results

{"variables":["Not a valid string."]} error message

### Additional information

**Workaround works when pushing to api endpoint /api/v2/hosts/id/variables_data directly**

**Comment by thedoubl3j** [comment]
yes, the variable field is a string field. you will need to "stringify" your yaml or json.
