### ISSUE TITLE
TLS handshake timeout - TASK [local_docker : Activate AWX Task Container]

### ISSUE THREAD

**Issue by GProst** [ansible/awx#1521]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
From time to time installation fails with the error (sometimes it installs successfully):
```
Error pulling ansible/awx_task - code: None message: Get https://registry-1.docker.io/v2/ansible/awx_task/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Aansible%2Fawx_task%3Apull&service=registry.docker.io: net/http: TLS handshake timeout
```

##### ENVIRONMENT
* AWX version: cloned from `devel` branch
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: RHEL

##### STEPS TO REPRODUCE
Running `ansible-playbook -i inventory install.yml` command.

##### ADDITIONAL INFORMATION
I use `packer` to create AWS AMI image from RHEL

**Comment by GProst** [comment]
Noticed, that error can be different, this time it is:
```
Error starting container <container_id>: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
```

**Comment by GProst** [comment]
Not sure if it is true in 100% cases, but if I clone AWX repo from `7984bd2824ddb5e77e13cddca13b94b54f591976` commit it seams to always install it successfully.

**Comment by GProst** [comment]
And also:
```
Error inspecting image ansible/awx_task:latest - UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
```

**Comment by wenottingham** [comment]
This sounds like an issue with your local docker setup; this is working for us. Please reopen if you have more details.

**Comment by GProst** [comment]
Sorry, it wasn't Fedora, it was RHEL...😅
Still get this error occasionally, not every time.
I install latest stable docker from scratch using base AWS AMI of RHEL.
Is it possible that this issue is because of absence of Google DNS servers in `/etc/resolv.conf`?

**Comment by GProst** [comment]
Ok, probably we found the cause.
`packer` used t2.micro type of EC2 instance to build AMI and I guess it couldn't handle pulling AWX image fast enough.
