### ISSUE TITLE
Tech Preview UI displaying "password" survey type value in extra vars "Review" page

### ISSUE THREAD

**Issue by skywalkw3r** [ansible/awx#15240]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

When using survey feature on Tech Preview UI the "password" survey type question is presenting the variable value within the "Review" page when launching a template. Interestingly enough if i set a "Default answer" for the "password" type in the survey i see the proper "$encrypted$" value when presented on the "Review" page.

### AWX version

24.3.1

### Select the relevant components

- [ ] UI
- [X] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

openshift

### Modifications

no

### Web browser

Firefox

### Steps to reproduce

1. Navigate to Tech Preview UI
2. Launch existing template with survey feature enabled
3. Enter survey values and select next
4. On "Review" page under "extra vars" you can see the password type var in clear text

### Expected results

Expecting to see the extra var section showing "$encrypted$" for the password value.

### Actual results

The extra var section showing unencrypted value for the password value.

### Additional information

Test Template Survey - Password Question
![Test-Bug-0](https://github.com/ansible/awx/assets/37527320/70d57820-faef-4fdf-9e01-569061ed9038)

Test Template Survey - Survey prompting for password
![Test-Bug-1](https://github.com/ansible/awx/assets/37527320/9aa94473-55bf-4a7e-b36a-be9406f20818)

Test Template Survey - Survey displaying extravars password in plain text
![Test-Bug-2](https://github.com/ansible/awx/assets/37527320/52e3b719-65e2-46a3-b8a1-0718e9b91f7c)

Test Template Survey - Survey displaying extravars password encrypted (when using "default answer" option)
![Test-Bug-3](https://github.com/ansible/awx/assets/37527320/246cabd6-8a35-4166-a3be-6cee0ac6ee56)

**Comment by marshmalien** [comment]
Closing. Addressed bug fix in https://github.com/ansible/ansible-ui/pull/2487
