### ISSUE TITLE
RFE: Increase the pixel size to set up a custom logo in tower

### ISSUE THREAD

**Issue by Ompragash** [ansible/awx#1524]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

  - UI

##### SUMMARY

Whenever custom logo is used, it is shrink-ed in Ansible Tower log-in window than the original size.

##### ENVIRONMENT
* AWX version: 1.0.0

##### STEPS TO REPRODUCE

Increase the pixel size for this variable `LoginModal-logoImage{max-width:` to 550px in this path 
/var/lib/awx/public/static/css/app.css.

**Comment by aoyawale** [comment]
tried to test this change but, it looks like increasing the size to 550px is too big and makes the page unable to scroll up & down. There might be something else that might need to be changed also.

**Comment by aoyawale** [comment]
if the pic is bigger than 379 x 432 after changing `LoginModal-logoImage{max-width:` to 550 it breaks scrolling on the page.

**Comment by vqw** [comment]
@jlozadad there is some solution that we implemented:
`max-width: calc(100% - 40px)`
40px is based on left/right margin being 20px

**Comment by mabashian** [comment]
There's no longer a max width on the custom logo, only a max height of 285px
