### ISSUE TITLE
RFE: - Finer RBAC Rules, Prevent Org admins from creating users in tower

### ISSUE THREAD

**Issue by akcrisp** [ansible/awx#1526]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
We want to prevent Org admins being able to create local users within tower. All our controls are based around ldap groups. We want to prevent teams with their own orgs being able to create local users in awx, as this breaks our standard. We therefore need finer grained RBAC rules. 

##### ENVIRONMENT
* AWX version: 1.0.1.173
* AWX install method:  docker on linux
* Ansible version:  2.4.3
* Operating System: RHEL 7.x
* Web Browser: Chrome

**Comment by wenottingham** [comment]
Pulling some things out of https://github.com/ansible/awx/issues/166 here:

Additional restrictions on the user model that would land here:

- prohibit manual team mapping adjustments at the org admin level
- and/or have a mapping just for an org

The idea is that:
- each organization has an LDAP configuration
- the org admin can then make team mappings for that organization from that config

**Comment by wenottingham** [comment]
Related comment: https://github.com/ansible/awx/issues/166#issuecomment-358012997

**Comment by akcrisp** [comment]
Ok but I don’t see that preventing an org admin from still creating local accounts in awx ? 

As for each org having their own ldap mapping - again it would be useful if we can lock this down so that orgs admins can’t change it. We want the ability to be able to configure ldap for awx instances on behalf of app teams (each with their own orgs) and then prevent them from being able to change it. Which at the moment they can’t do because they don’t have admin wide rights.

**Comment by akcrisp** [comment]
Hmmm #166 this send to relate to rfe I raised for tower where I pointed out it the ldap integration is far to reactive ie groups don’t appear until someone logs in.

**Comment by wwitzel3** [comment]
#1608 introduced a system configuration that allows you to disable awx management of users and teams.

**Comment by akcrisp** [comment]
Why is this closed ?

**Comment by akcrisp** [comment]
Just seen The follow up. Ok

**Comment by akcrisp** [comment]
Is there any more detail on how this works ? I can’t see anything in the thread which explains how you actually configure this.

Andy

**Comment by wwitzel3** [comment]
There is a toggle under the AWX System Settings or you can set `MANAGE_ORGANIZATION_AUTH=False` in your settings.

**Comment by wwitzel3** [comment]
Probably helps if I reference the correct PR

**Comment by akcrisp** [comment]
Which is ?

**Comment by akcrisp** [comment]
Can we also confirm which build this feature is in.

Thanks

Andy

**Comment by wwitzel3** [comment]
I updated https://github.com/ansible/awx/issues/1526#issuecomment-374760820 with the correct PR.

**Comment by akcrisp** [comment]
Thanks

**Comment by akcrisp** [comment]
Why has this been reopened ? As per earlier update there is a option to prevent orgs creating users and teams in 1.0.5 release 

Andy

**Comment by marshmalien** [comment]
This was reopened because the UI needed to add related work to this issue. We included a warning message to inform org admins that they can not manage users and teams.
