### ISSUE TITLE
ERROR: Failed to JSON parse a line from worker stream. Error: Expecting value: line 1 column 1 (char 0) Line with invalid JSON data: b''

### ISSUE THREAD

**Issue by chinna44** [ansible/awx#15273]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

We have issues while running multiple workflows on few jobs with ERROR: Previous Task Failed: {"job_type": "inventory_update", "job_name": "sandbox-eu-west-1-dev-39-ce-arion - AWS-sandbox-Windows", "job_id": "542781"}

![image](https://github.com/ansible/awx/assets/61354272/9a4032d2-7d46-4114-b66f-8e93c5ba35ed)

When I check the status of **"job_id": "542781"** Failed to JSON parse a line from worker stream. Error: Expecting value: line 1 column 1 (char 0) Line with invalid JSON data: b''  and **standard output** is Receptor detail: Error creating pod: pod failed to start

![image](https://github.com/ansible/awx/assets/61354272/3762306b-a4e6-4402-9d2e-9fe6f82962ba)

Logs from the **pegasus-awx-control-plane-ee** ERROR 2024/06/14 09:12:23 Exceeded retries for reading stdout /tmp/receptor/awx-task-5f9498c777-v9pvw/AUxBunxh/stdout

We are running the awx version 23.9.0 which is deployed on EKS 1.28 version

This only occurs when AWX handles more workflows.

ee_extra_env: |-
    - name: RECEPTOR_KUBE_SUPPORT_RECONNECT
      value: enabled

Could you please assist how can we avoid this failure 

### AWX version

23.9.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

Run many workflows simultaneously 

### Expected results

Every job has to assign/create the pod successfully

### Actual results

AWX is unable to create the pod for the jobs

**Comment by kzinas-adv** [comment]
It could be issue with lack of memory for worker pod/container in node on which it is running, as it it is mine case
```ERROR: Failed to JSON parse a line from worker stream. Error: Expecting value: line 1 column 1 (char 0) Line with invalid JSON data: b''```
Means OOM kill
```Failed: The running ansible process received a shutdown signal.```
And this one means kubernetes evicted worker pod due to lack of memory on node.

How many machines do you have in in your inventory? In our case it is ~400, lasts 5-6 hours and a lot of log output.

```
[Mon Jun 10 16:20:18 2024] ansible-playboo invoked oom-killer: gfp_mask=0xcc0(GFP_KERNEL), order=0, oom_score_adj=988
[Mon Jun 10 16:20:18 2024] CPU: 3 PID: 696480 Comm: ansible-playboo Not tainted 6.1.0-21-amd64 #1  Debian 6.1.90-1
[Mon Jun 10 16:20:18 2024] Hardware name: DigitalOcean Droplet/Droplet, BIOS 20171212 12/12/2017
[Mon Jun 10 16:20:18 2024] Call Trace:
[Mon Jun 10 16:20:18 2024]  <TASK>
[Mon Jun 10 16:20:18 2024]  dump_stack_lvl+0x44/0x5c
[Mon Jun 10 16:20:18 2024]  dump_header+0x4a/0x211
[Mon Jun 10 16:20:18 2024]  oom_kill_process.cold+0xb/0x10
[Mon Jun 10 16:20:18 2024]  out_of_memory+0x1fd/0x4c0
[Mon Jun 10 16:20:18 2024]  mem_cgroup_out_of_memory+0x134/0x150
[Mon Jun 10 16:20:18 2024]  try_charge_memcg+0x696/0x780
[Mon Jun 10 16:20:18 2024]  charge_memcg+0x39/0xf0
[Mon Jun 10 16:20:18 2024]  __mem_cgroup_charge+0x28/0x80
[Mon Jun 10 16:20:18 2024]  wp_page_copy+0xfc/0x720
[Mon Jun 10 16:20:18 2024]  __handle_mm_fault+0x97b/0xfa0
[Mon Jun 10 16:20:18 2024]  handle_mm_fault+0xdb/0x2d0
[Mon Jun 10 16:20:18 2024]  do_user_addr_fault+0x191/0x580
[Mon Jun 10 16:20:18 2024]  exc_page_fault+0x70/0x170
[Mon Jun 10 16:20:18 2024]  asm_exc_page_fault+0x22/0x30
[Mon Jun 10 16:20:18 2024] RIP: 0033:0x7fbe68b60466
[Mon Jun 10 16:20:18 2024] Code: Unable to access opcode bytes at 0x7fbe68b6043c.
[Mon Jun 10 16:20:18 2024] RSP: 002b:00007ffeaec51080 EFLAGS: 00010206
[Mon Jun 10 16:20:18 2024] RAX: 0000000000000006 RBX: 00007fbe686dd030 RCX: 0000000000000004
[Mon Jun 10 16:20:18 2024] RDX: 00007fbe4f094f80 RSI: 00007ffeaec51120 RDI: 00005571cd8e6a30
[Mon Jun 10 16:20:18 2024] RBP: 00007ffeaec51120 R08: 00007fbe4a21eb30 R09: 00007fbe4bf32c90
[Mon Jun 10 16:20:18 2024] R10: 0000000000000002 R11: 00005571cd8e6a40 R12: 00005571cd8e6780
[Mon Jun 10 16:20:18 2024] R13: 00005571cd8e6a30 R14: 00005571cd8e6a30 R15: 00007fbe4bf32ca0
[Mon Jun 10 16:20:18 2024]  </TASK>
[Mon Jun 10 16:20:18 2024] memory: usage 6957056kB, limit 6957056kB, failcnt 7563598
[Mon Jun 10 16:20:18 2024] swap: usage 0kB, limit 9007199254740988kB, failcnt 0
[Mon Jun 10 16:20:18 2024] Memory cgroup stats for /kubepods:
[Mon Jun 10 16:20:18 2024] anon 6943481856
                           file 8343552
                           kernel 172183552
                           kernel_stack 7192576
                           pagetables 24993792
                           sec_pagetables 0
                           percpu 470328
```

```
Message:          The node was low on resource: memory. Threshold quantity: 100Mi, available: 26544Ki. Container awx-prod-rsyslog was using 178036Ki, request is 128Mi, has larger consumption of memory. Container awx-prod-task was using 2201964Ki, request is 128Mi, has larger consumption of memory. 
```

**Comment by Geogboe** [comment]
@kzinas-adv I'm in a similar situation (long running jobs) but I'm not seeing logs like yours anywhere on my system. Can you point me to where you found those logs or what commands you ran?

**Comment by adv-bet** [comment]
> @kzinas-adv I'm in a similar situation (long running jobs) but I'm not seeing logs like yours anywhere on my system. Can you point me to where you found those logs or what commands you ran?

https://ansible.readthedocs.io/projects/awx/en/latest/administration/troubleshooting.html
I guess this is enough this will leave your container after job done for kubectl  logs/describe investigation.

There more hard way enable this through custom.py through awx kubernetes config. 
https://github.com/ansible/awx/blob/devel/awx/settings/defaults.py
```
# Delete completed work units in receptor
RECEPTOR_RELEASE_WORK = True
RECPETOR_KEEP_WORK_ON_ERROR = False

# K8S only. Use receptor_log_level on AWX spec to set this properly
RECEPTOR_LOG_LEVEL = 'info'
```

Additional logs I got from VM on which worker container was running.
Basically  this  error `: Failed to JSON parse a line"` just means that your work or awx task has crashed for some reason, it can be various issues.

**Comment by kzinas-adv** [comment]
> @kzinas-adv I'm in a similar situation (long running jobs) but I'm not seeing logs like yours anywhere on my system. Can you point me to where you found those logs or what commands you ran?

https://ansible.readthedocs.io/projects/awx/en/latest/administration/troubleshooting.html
I guess this is enough this will leave your container after job done for kubectl  logs/describe investigation.

There more hard way enable this through custom.py through awx kubernetes config. 
https://github.com/ansible/awx/blob/devel/awx/settings/defaults.py
```
# Delete completed work units in receptor
RECEPTOR_RELEASE_WORK = True
RECPETOR_KEEP_WORK_ON_ERROR = False

# K8S only. Use receptor_log_level on AWX spec to set this properly
RECEPTOR_LOG_LEVEL = 'info'
```

Additional logs I got from VM on which worker container was running.
Basically  this  error `: Failed to JSON parse a line"` just means that your work or awx task has crashed for some reason, it can be various issues.
