### ISSUE TITLE
Access View is Blank

### ISSUE THREAD

**Issue by mxs-weixiong** [ansible/awx#15293]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Unable to see the access 

![image](https://github.com/ansible/awx/assets/134896313/53feaab8-0a13-418d-bac5-35b836291ed1)

### AWX version

24.5.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

Unable to view the configured Access when viewing another organization.

### Expected results

Able to see the configured access

### Actual results

Unable to see the configured access

**Comment by djyasin** [comment]
Hello,
@mxs-weixiong we would like to gather a bit more information. Can you let us know what type of role the user is in that is trying to view this information? 

Thank you for your time!

**Comment by mxs-weixiong** [comment]
No longer an issue after update to the latest version.
