### ISSUE TITLE
Pagination problem in Hosts tab in Inventories

### ISSUE THREAD

**Issue by Labutin** [ansible/awx#1537]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Pagination problem in HOSTS tab in Inventories

##### ENVIRONMENT
* AWX version: 1.0.4.70
* AWX install method: docker on linux

##### STEPS TO REPRODUCE

1. Create 2 inventories
1. Add just one host to first inventory
1. Add hosts to second inventory enough to see pagination
1. Click to the second page
1. Return to first inventory
1. Click to "HOSTS" button
1. You will see an error message

##### EXPECTED RESULTS

Show the hosts list

##### ACTUAL RESULTS

Error message "Invalid search term entered. GET returned: 404 Invalid page."

##### ADDITIONAL INFORMATION

UI remember page number from another inventory and trying to show the second page in inventory, where only one page.

```
2018-03-12 23:30:15,894 WARNING  awx.api.generics status 404 received by user admin attempting to access /api/v2/inventories/2/hosts/ from 10.30.110.98
2018-03-12 23:30:15,895 WARNING  django.request Not Found: /api/v2/inventories/2/hosts/
2018-03-12 23:30:15,895 WARNING  django.request Not Found: /api/v2/inventories/2/hosts/
[pid: 36|app: 0|req: 136/1135] 10.30.110.98 () {42 vars in 2384 bytes} [Mon Mar 12 23:30:15 2018] GET /api/v2/inventories/2/hosts/?page_size=20&order_by=name&page=2 => generated 26 bytes in 24 msecs (HTTP/1.1 404) 8 headers in 235 bytes (1 switches on core 0)
[pid: 33|app: 0|req: 284/1136] 10.30.110.98 () {42 vars in 2305 bytes} [Mon Mar 12 23:30:15 2018] GET /api/v2/inventories/2/ => generated 2163 bytes in 34 msecs (HTTP/1.1 200) 8 headers in 244 bytes (1 switches on core 0)
```

**Comment by jaredevantabor** [comment]
this is fixed now in devel
