### ISSUE TITLE
Bug with workflow approve permission 

### ISSUE THREAD

**Issue by lucasvivian** [ansible/awx#15372]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hi, I'm trying to set WorkFlow Approve Permission to a user. When I set the permission to the user, all other permissons are reset. Workflow becomes with no permissions to anybody and a message appears on the UI ("No Roles Found")

### AWX version

24.5.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.16.0

### Operating system

Ubuntu

### Web browser

Firefox

### Steps to reproduce

Create a Workflow and give Approve permisson to a user.

### Expected results

A user with Approve permission are listed with other users permissions.

### Actual results

UI Message: "No Roles Found" 

### Additional information

No additional informations

**Comment by djyasin** [comment]
Hello @lucasvivian,
Based on what you are describing this sounds like a good issue to raise on the  [Ansible Community Forum](https://forum.ansible.com/tag/awx). We would recommend raising this issue there to see if anyone else has encountered it.

**Comment by djyasin** [comment]
We are going to go ahead and close this issue. We look forward to speaking with you on the Forum!
