### ISSUE TITLE
Launch the same or different job template based on one SCM project simultaneously

### ISSUE THREAD

**Issue by cesarfn4** [ansible/awx#1538]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
When the 'Delete on Update' and 'Update on Launch' options are activated in an SCM project, it should be possible to execute several different or the same playbook within one project.

The background is, that in our case each project is executed on 3 to 4 inventories. However, when I have only one inventory and start several different playbooks on it at the same time, the issue also occurs.

 Here, a function should be built which creates a working copy of the content, e.g. after an SCM update, on which it can work. Further, an SCM update should be able to wait for another update until the loaded version was copied (or relocated) into the working directory.

**Comment by wenottingham** [comment]
This is covered under https://github.com/ansible/awx/issues/282.
