### ISSUE TITLE
RFE: Dynamically specify a tag version in the SCM project when executing the job template

### ISSUE THREAD

**Issue by Ompragash** [ansible/awx#1539]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

We require a new feature which enables us to select a certain tag of the specified branch or a random tag (if no branch was specified) from all branches in the job template. This field must contain the "Prompt on Launch" option.

##### ENVIRONMENT
* AWX version: 1.0.0

**Comment by wenottingham** [comment]
This is covered by https://github.com/ansible/awx/issues/282, there is actually no distinction between branch or tag.
