### ISSUE TITLE
Console Output lines are in wrong order when there is more than 1000 lines

### ISSUE THREAD

**Issue by doronshai** [ansible/awx#1540]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When I run playbook with long log output, the lines order is getting wrong and it is not usable which is SEVERE issue as I do not able to know what was done and what is the exact result.

##### ENVIRONMENT
* AWX version: 1.0.1.81
* AWX install method: docker on linux
* Ansible version:  Ansible 2.4.0.0 
* Operating System: Ubuntu 16.04.1 LTS
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Running a playbook which will have log of more than 1000 lines (can be done with lot of  steps or on bug group of servers)

##### EXPECTED RESULTS

I should be able to see all the lines in the correct order

##### ACTUAL RESULTS

The order of the lines is corrupted and it is not usable

##### ADDITIONAL INFORMATION

https://ibb.co/nDYNNx
https://ibb.co/cB5Bhx
https://ibb.co/cExfQH
https://ibb.co/jTbeKc

**Comment by ryanpetrello** [comment]
@doronshai we've completely rewritten this UI from the ground up in newer versions of awx to address issues like this.  Mind giving it another try, and reopening if you still see issues?

**Comment by pearj** [comment]
@ryanpetrello will this fix make its way into ansible tower anytime soon? I just bumped into this the other day.

**Comment by ryanpetrello** [comment]
@pearj yep, this change will be present in a future release of Ansible Tower.
