### ISSUE TITLE
Set an env variable in the execution environment 

### ISSUE THREAD

**Issue by skandarchahbouni** [ansible/awx#15430]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

I think a very important feature is currently missing in AWX: the ability to set variables in the execution environment of a job directly from AWX. At the moment, I believe the only ways to set environment variables in the execution environment are by rebuilding the image or by accessing the container and setting them manually, such as by running export commands...

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

- Create a simple job in AWX that prints an environment variable. For example:
```yaml
---
- name: Debugging env variables ... 
  hosts: localhost
  tasks:
    - name: Display a debug message
      debug:
        msg: "The value of TESTis {{ lookup('env', 'TEST') }}"
```

- Try to set the environment variable from AWX in the Variables tab: 
```yaml
TEST: some_value
```

or 

```yaml
env:
    TEST: some_value
```

or another way ...

### Current results

Run the job; it will always return an empty variable because it is not set...

### Sugested feature result

- Add a field in AWX that allows us to set environment variables directly in the execution environment.

### Additional information

I think this feature is quite important. There are many sensitive variables that shouldn't be set or displayed in the AWX UI. Additionally, these variables need to be changed periodically. For example, a certain application token must be set as an environment variable and updated periodically because it will likely expire and isn't permanent.

**Comment by kurokobo** [comment]
There are some ways:

- Use custom Credential Types: I think this is the best approach for your requirements that pass sensitive variables
- Use `Extra Environment Variables` in `Settings` > `Job settings`
- Define customized Container Group with customized Pod specification with environment variables

**Comment by skandarchahbouni** [comment]
- **Use Custom Credential Types**: I think this is the best approach for passing sensitive variables.
  - **If I create custom credentials, how would I be able to access them from the playbook?**
  
- **Use Extra Environment Variables in Settings > Job Settings**
  - **Is there a way to set an extra variable only for one job, not for all the jobs?**

**Comment by skandarchahbouni** [comment]
> There are some ways:
> 
> * Use custom Credential Types: I think this is the best approach for your requirements that pass sensitive variables
  -  **If I create custom credentials, how would I be able to access them from the playbook?**
> * Use `Extra Environment Variables` in `Settings` > `Job settings`
  - **Is there a way to set an extra variable only for one job, not for all the jobs?**

**Comment by kurokobo** [comment]
> If I create custom credentials, how would I be able to access them from the playbook?

See the docs: https://ansible.readthedocs.io/projects/awx/en/latest/userguide/credential_types.html

> Is there a way to set an extra variable only for one job, not for all the jobs?

No, this is global configuration.

**Comment by skandarchahbouni** [comment]
Thank you, gonna close the issue.
