### ISSUE TITLE
WebUI User variable not available in Job runs.

### ISSUE THREAD

**Issue by bsclark** [ansible/awx#1547]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
WebUI User variable not available in Job runs.

##### ENVIRONMENT
* AWX version: 1.0.2.327 
* AWX install method: docker on linux
* Ansible version:  2.4.2.0

##### ADDITIONAL INFORMATION
Email to Forum resulted in the following exchange, prompting me to open an issue. Transcript:

Matthew Jones <majones@redhat.com>

At one time we put the username in as an extra var but it looks like that's somehow being omitted from anything ad-hoc jobs right now. Can you open an issue for us to add that and the email address back to job runs?  I'll point out that, even when populated, it will not be populated when jobs are launched via schedules etc.

------
Howdy everyone,

Wondering if you could direct me to what I am looking for.

When you launch a template and the job starts, one of the details of the job, is "Launched By" and the username of the user. If you click on the user, it shows you a username, first and last name and email address.

In my survey that builds EC2 instances, we have a filed for person launching the template to enter their email address. That info is used to add a tag to the EC2 instance called "Requestor".

I was wondering if there was a way to access the WebUI variable for "Launched By" users email address and auto fill my survey filed that asks for the info.

Thanks!

**Comment by wenottingham** [comment]
We do not have any capability for auto-filling survey entries. I would just do this in the playbook.

**Comment by fosterseth** [comment]
The awx user is injected as an extra var into the running playbook, and that would be the preferred way to go about this
