### ISSUE TITLE
docker-compose initial install issue

### ISSUE THREAD

**Issue by jalphonso** [ansible/awx#1548]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY
During initial install when using Docker Compose, the awx_web container starts too early and the UI doesn't load properly.

##### ENVIRONMENT
* AWX version: master
* AWX install method: docker for linux
* Ansible version:  2.4
* Operating System: Ubuntu/CentOS
* Web Browser: Chrome

##### STEPS TO REPRODUCE

docker-compose up

##### EXPECTED RESULTS

AWX Migration page should load properly and then once DB migrations are complete, the Login page should appear
##### ACTUAL RESULTS

Internal Server error or white page with no icons and a OK, Cancel options

##### ADDITIONAL INFORMATION

Adding a health check for the DB and service condition checks for the awx_web task resolves the issue. Example here: https://github.com/jalphonso/awx/commit/60ae93b79b3e69e696d7f9bda015030d36386081

**Comment by luisico** [comment]
I'm seeing exactly the same behavior when trying to install with docker-compose.

Although @jalphonso solution works, conditions on `depends_on` have been removed in version 3 and this solution might need revisiting later on. I found this nice explanation about treating startup "disorders" in containers (see https://docs.docker.com/compose/startup-order/) and started looking at the examples mentioned in there when I realized that `awx_task` already supports this "wait for" behavior using ansible in `launch_awx_task.sh`. I just copied that code to `launch_awx.sh` and rebuild the images and it is working. I haven't had time to evaluate if all the "wait for" are needed, but I thought I would start by sharing my finding with the experts. The commit is at luisico@5330f3206be9cb1d329750f22b8f415ecc6422f7

Please, let me know if you want a pull request or some extra digging.

Best,
Luis

**Comment by wenottingham** [comment]
Sorry about the delay - sure, a PR would be fine.

**Comment by luisico** [comment]
Hi @wenottingham, quick reminder the PR was sent. Please, let me know if you need anything. Thanks, Luis

**Comment by shanemcd** [comment]
Closing since the old `docker-compose` installer is gone now.
