### ISSUE TITLE
Error when installing AWX using playbook

### ISSUE THREAD

**Issue by Manimala94** [ansible/awx#15486]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

I'm trying to work Final year project using Ansible AWX. But getting error when installing AWX using playbook

### AWX version

Ansible(core 2.17.30)

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

Ansible(core 2.17.30)

### Operating system

Ubuntu 22.04

### Web browser

Chrome, Edge

### Steps to reproduce

I'm getting below error when running the play book 'ansible-playbook -i inventory install.yml
Already python3 is installed on AWS ubuntu 22.04. 

I used the steps to install from this website https://medium.com/@sahildrive007/easily-install-ansible-awx-on-ubuntu-a-step-by-step-guide-b391c783d54c

### Expected results

I thought it will run  but didn't. Not sure how to set the interpreter. If you know please explain in detail. I'm new to work ubuntu.

### Actual results

Getting below error when running playbook.

[DEPRECATION WARNING]: community.docker.docker_compose has been deprecated. This module uses docker-compose v1, which is End of life since july 2022. Please migrate to community.docker.docker_compose_v2. this feature will be removed from community.docker in version 4.0.0. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY [Build and deploy AWX] ************************************************************

TASK [Gathering Facts] *****************************************************************
fatal: [localhost]: fAILED! => {'ansible_facts":{}, "changed": false, "failed_modules": {"ansible.legacy.setup": {"failed": true, "module_stderr": "/bin/sh: 1: /usr/bin/env python3: not found\n", "module_stdout": "", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127}}, "msg": "the following module failed to execute: ansible.legacy.setup\n"}

PLAY RECAP **************************************************************************

**Comment by fosterseth** [comment]
that guide is using awx 17, which is no longer supported.

You should be using awx-operator install method instead. If you want to run in docker for development purposes, please follow the instructions here https://github.com/ansible/awx/blob/devel/CONTRIBUTING.md
