### ISSUE TITLE
Relaunch task is not working

### ISSUE THREAD

**Issue by jffz** [ansible/awx#1550]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

Restarting a task by clicking the 'rocket' ask to chose beteen 'fail' and 'all'. 
Doesn't matter which one we pick, it end saying <choice> is not a correct choice.
##### ENVIRONMENT
* AWX version: 1.0.4.70
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: CentOS 7.4
* Web Browser: Chrome / Firefox

##### STEPS TO REPRODUCE

Restart a task using the 'rocket' button and pick any choice
##### EXPECTED RESULTS
It should restart the task, the one failed or all

##### ACTUAL RESULTS
Fail saying "<choice> is not a correct choice."

##### ADDITIONAL INFORMATION
Side question, does 'faiul' should restart from the failed task or only the failed ones ?

**Comment by jaredevantabor** [comment]
this is fixed now in devel
