### ISSUE TITLE
Unable to create inventory source based on custom script

### ISSUE THREAD

**Issue by Yiadh** [ansible/awx#1551]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
I am unable to create inventory source based on custom script.
For previous versions (<=1.0.4.0), it is working fine. Now I am facing the following error while using the version 1.0.4.83

![image](https://user-images.githubusercontent.com/30578850/37396035-079db102-2778-11e8-90d8-5baac97b9297.png)

##### ENVIRONMENT
* AWX version: 1.0.4.83
* AWX install method: openshift
* Ansible version:  2.4.3.0
* Operating System: ubuntu 16.04
* Web Browser: chrome

##### STEPS TO REPRODUCE

Create inventory script [working fine]
Create inventory [working fine]
Create inventory source based on custom script: select the newly created inventory, click on sources, add sources, choose custom script as source and select the created one, set a name and click on Save. [Then the problem appears]

##### EXPECTED RESULTS

inventory source based on custom script created successfully

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/30578850/37396035-079db102-2778-11e8-90d8-5baac97b9297.png)

**Comment by AlanCoding** [comment]
Likely duplicate of #1545
