### ISSUE TITLE
docker-compose-build fails with: Unable to find a match: openssl-3.0.7

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/awx#15540]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

```make docker-compose-build``` fails when trying to install ```openssl-3.0.7```.

### AWX version

24.6.1

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.17.4

### Operating system

CentOS stream 9

### Steps to reproduce

with:
- awx_version=24.6.0 or 24.6.1
- awx_devel_container_version=release_4.5 or release_4.6
- awx_receptor_version=devel or latest

1. git clone -b $awx_version https://github.com/ansible/awx.git git-awx && cd git-awx
2. git switch -c $awx_devel_container_version
3. export RECEPTOR_IMAGE=quay.io/ansible/receptor:${awx_receptor_version}
4. make docker-compose-build

### Expected results

No error

### Actual results

```
    ansible-playbook -e ansible_python_interpreter=python3.11 tools/ansible/dockerfile.yml \
            -e dockerfile_name=Dockerfile.dev \
            -e build_dev=True \
            -e receptor_image=quay.io/ansible/receptor:devel
...
    13.47 CentOS Stream 9 - BaseOS                         27 kB/s |  16 kB     00:00
    13.60 CentOS Stream 9 - AppStream                     205 kB/s |  17 kB     00:00
    14.10 CentOS Stream 9 - CRB                            19 MB/s | 6.5 MB     00:00
    16.53 No match for argument: openssl-3.0.7
    16.57 Error: Unable to find a match: openssl-3.0.7
    ------
    Dockerfile.dev:22
    --------------------
      21 |     # Install build dependencies
      22 | >>> RUN dnf -y update && dnf install -y 'dnf-command(config-manager)' && \
      23 | >>>     dnf config-manager --set-enabled crb && \
      24 | >>>     dnf -y install \
      25 | >>>     iputils \
      26 | >>>     gcc \
      27 | >>>     gcc-c++ \
      28 | >>>     git-core \
      29 | >>>     gettext \
      30 | >>>     glibc-langpack-en \
      31 | >>>     libffi-devel \
      32 | >>>     libtool-ltdl-devel \
      33 | >>>     make \
      34 | >>>     nodejs \
      35 | >>>     nss \
      36 | >>>     openldap-devel \
      37 | >>>     # pin to older openssl, see jira AAP-23449
      38 | >>>     openssl-3.0.7 \
      39 | >>>     patch \
      40 | >>>     postgresql \
      41 | >>>     postgresql-devel \
      42 | >>>     python3.11 \
      43 | >>>     "python3.11-devel" \
      44 | >>>     "python3.11-pip" \
      45 | >>>     "python3.11-setuptools" \
      46 | >>>     "python3.11-packaging" \
      47 | >>>     "python3.11-psycopg2" \
      48 | >>>     swig \
      49 | >>>     unzip \
      50 | >>>     xmlsec1-devel \
      51 | >>>     xmlsec1-openssl-devel
      52 |
    --------------------
    ERROR: failed to solve: process "/bin/sh -c dnf -y update && dnf install -y 'dnf-command(config-manager)' &&     dnf config-manager --set-enabled crb &&     dnf -y install     iputils     gcc     gcc-c++     git-core     gettext     glibc-langpack-en     libffi-devel     libtool-ltdl-devel     make     nodejs     nss     openldap-devel     openssl-3.0.7     patch     postgresql     postgresql-devel     python3.11     \"python3.11-devel\"     \"python3.11-pip\"     \"python3.11-setuptools\"     \"python3.11-packaging\"     \"python3.11-psycopg2\"     swig     unzip     xmlsec1-devel     xmlsec1-openssl-devel" did not complete successfully: exit code: 1
    make: *** [Makefile:619: docker-compose-build] Error 1
```

**Comment by cigamit** [comment]
I believe this was resolved already in 
https://github.com/ansible/awx/commit/82b8f7d4c039184b135733cf01a29f172c0b0b51

**Comment by jean-christophe-manciot** [comment]
Thx @cigamit 
I'll wait for ```24.6.2``` then.

**Comment by jean-christophe-manciot** [comment]
@cigamit 
This seems to be a hasty closing since there has not been any testing yet AFAIK.
