### ISSUE TITLE
Multiselect checkboxes won't uncheck in permissions modal

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#1555]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### STEPS TO REPRODUCE
* Navigate to Users tab
* Select a user
* Click `Add Permissions` button
* Under any resource tab, select checkboxes to add resources
* Deselect checkboxes

##### EXPECTED RESULTS
* Checkbox is deselected

##### ACTUAL RESULTS
* Checkbox stays selected

##### SUMMARY
![2018-03-14 09_24_33](https://user-images.githubusercontent.com/15881645/37406468-9d132da8-276d-11e8-87a8-fd8fd709d7ea.gif)

##### ADDITIONAL INFORMATION
When we rollback the following changes, the deselect works. 
Link: https://github.com/ansible/tower/pull/353

**Comment by ryanpetrello** [comment]
Fixed via https://github.com/ansible/awx/commit/bf142fa4349b2518c185e45ff5c617a475347042
