### ISSUE TITLE
Import git repo for AWX error

### ISSUE THREAD

**Issue by NobeliY** [ansible/awx#15560]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

ssh: connect to host github.com port 22: Connection timed out

### AWX version

22.3.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Operating system

Ubuntu 22.04.2 LTS

### Web browser

Firefox

### Steps to reproduce

1. ssh-keygen -t rsa
2. Import a public key to Github SSH and GPG keys
3. Create a Credential by private key
4. Create project from git@github.com:... with source branch

### Expected results

Successfully import project

### Actual results

ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

**Comment by oceanthunder** [comment]
a) Try using HTTPS:  
```bash
git clone https://github.com/ansible/awx.git
```

b) If you prefer using SSH, make sure your `.gitconfig` has the following settings to avoid issues with HTTPS:  
```ini
[url "git@github.com:"]
    insteadOf = https://github.com/
```
If you see the reverse (i.e., `url` is `http://github.com` and `insteadOf` is `git@github.com`), change it to the above.

c) Ensure your SSH key is correctly copied and pasted into the **SSH and GPG keys** section of your GitHub account. Double-check that the public key matches what you generated with `ssh-keygen`.

**Comment by NobeliY** [comment]
The problem was that there was no access to the ssh git. The problem has now been solved.
