### ISSUE TITLE
devel: make clean-ui fails

### ISSUE THREAD

**Issue by jceddy** [ansible/awx#15619]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

When I run the following command to generate UI files, it fails:

```
docker compose -f tools/docker-compose/_sources/docker-compose.yml run --rm awx_1 make clean-ui ui-devel
```

### AWX version

devel

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

core 2.16.3

### Operating system

AlmaLinux 8

### Steps to reproduce

Following the guide at this location: https://community.hetzner.com/tutorials/awx-without-kubernetes#step-1---setting-up-the-server

Pull version "devel"

Get to the "Generating UI Files" step and run the following command:

`docker compose -f tools/docker-compose/_sources/docker-compose.yml run --rm awx_1 make clean-ui ui-devel`

### Expected results

The docker compose command succeeds.

### Actual results

The docker compose command fails with the following output:

```
[+] Creating 2/0
 ✔ Container tools_redis_1     Running                                                                                                                    0.0s 
 ✔ Container tools_postgres_1  Running    

WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers
make: *** No rule to make target 'clean-ui'.  Stop.
```

**Comment by jceddy** [comment]
It seems that clean-ui isn't in the Makefile (anymore?).
Can I just skip that?

**Comment by jceddy** [comment]
Seems like that guide doesn't work with this version.

**Comment by 777ilya777** [comment]
And who know where is new guide ?

**Comment by kiby75** [comment]
This command worked for me:

`docker-compose -f tools/docker-compose/_sources/docker-compose.yml run --rm awx_1 make clean/ui  -B ui
`

I took it from here:

`cat cat awx/ui/README.md`


## Build

```bash
make ui
```

## Rebuild

```bash
make -B ui
```

## Clean

```bash
make clean/ui
```
