### ISSUE TITLE
Return data formatted as YAML

### ISSUE THREAD

**Issue by markfaine** [ansible/awx#15618]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

When retrieving data like the following:
```python
vars = client.hosts.get(name=hostname).results[0].get_related('variable_data')
```
The resulting data is return as a json structure:

```json
{
    "node_availability": "active",
    "node_labels": {
        "ansible": "true"
    },
    "node_role": "worker",
    "remote_host_enabled": "true",
    "remote_host_id": 2504,
    "remote_tower_enabled": "true",
    "remote_tower_id": 2504,
}
```
However, when attempting to convert it to yaml using ruamel.yaml and the 'rt' or 'safe' dumper, this results in an error:
```python
   vars = client.hosts.get(name=hostname).results[0].get_related('variable_data')
   yaml.dump(vars, sys.stdout)

```
```
raise RepresenterError(f'cannot represent an object: {data!s}')
ruamel.yaml.representer.RepresenterError: cannot represent an object: {
```
The 'unsafe' dumper will dump the objects but that data is not useful as yaml output.

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [x] CLI
- [ ] Other

### Steps to reproduce

```python
   vars = client.hosts.get(name=hostname).results[0].get_related('variable_data')
   yaml.dump(vars, sys.stdout)

```

### Current results

```
ruamel.yaml.representer.RepresenterError: cannot represent an object: {
```

### Sugested feature result

It would be nice if there was a way to indicate that yaml output was desired or a utility function that could convert the objects back to regular python data structures.

**Comment by markfaine** [comment]
FYI, I still think it's a good idea but I was able to work around it by converting the entire output to a string and feeding the string to yaml.dump.

**Comment by PabloHiro** [comment]
Since there are workarounds, and supporting additional format outputs is not something we want to prioritize, I will be closing this issue.
