### ISSUE TITLE
min_value in DecimalField should be Decimal type.

### ISSUE THREAD

**Issue by xibriz** [ansible/awx#15664]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

I see the following in the logs:

```
min_value in DecimalField should be Decimal type.
min_value in DecimalField should be Decimal type.
min_value in DecimalField should be Decimal type.
min_value in DecimalField should be Decimal type.
min_value in DecimalField should be Decimal type.
min_value in DecimalField should be Decimal type.
min_value in DecimalField should be Decimal type.
min_value in DecimalField should be Decimal type.
min_value in DecimalField should be Decimal type.
```

These log messages come in bursts of 9 lines. This is exaclty the number of functioning instances/receptors I have.

I have tried adjusting all values on the instances with no luck.

### AWX version

24.6.1

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.15.9

### Operating system

Ubuntu

### Steps to reproduce

Add a instance.

### Expected results

No log messages.

### Actual results

Many log enteries.

**Comment by ActionCactus** [comment]
Seeing the same thing in my instance.  Are you encountering any degraded capability from AWX, @xibriz , or is this just a noisy log?

**Comment by xibriz** [comment]
@ActionCactus We don't use the instances much but I have not encountered any problems yet, apart from the troubles I have adding new instances mentioned in #15665

**Comment by thedoubl3j** [comment]
@kdelee perhaps in your land? #15413
