### ISSUE TITLE
Custom 404 page for AWX docs

### ISSUE THREAD

**Issue by gundalow** [ansible/awx#15667]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

As we've removed various docs from the devel branch as part of https://github.com/ansible/awx/pull/15641 people are [getting 404s](https://forum.ansible.com/t/awx-documentation-no-longer-exists-besides-contribution-guide-and-api-reference/11161/).

We should create a custom 404 page that links to the `https://ansible.readthedocs.io/projects/awx/en/24.6.1/` docs, see the [RTD docs for details](https://docs.readthedocs.io/en/stable/reference/404-not-found.html)

Once this is live, update the [forum post](https://forum.ansible.com/t/awx-documentation-no-longer-exists-besides-contribution-guide-and-api-reference/11161/).

### AWX version

24.6.1

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Steps to reproduce

n/a

### Expected results

n/a

### Actual results

n/a

**Comment by millemme** [comment]
Added a pull request here: https://github.com/ansible/awx/pull/15680
Please suggest any changes so that I can make them.

**Comment by oraNod** [comment]
Docs 404 page added with https://github.com/ansible/awx/commit/699c0c769d5d994b9606554e9f364184c6a0e135

**Comment by oraNod** [comment]
Followed up by https://github.com/ansible/awx/pull/15669

**Comment by tvo318** [comment]
@gundalow put a comment on the [forum post](https://forum.ansible.com/t/awx-documentation-no-longer-exists-besides-contribution-guide-and-api-reference/11161/12) saying we are done!
