### ISSUE TITLE
AWX throws templating error when using a template to set a variable value under set_fact method

### ISSUE THREAD

**Issue by AMHAnsible9** [ansible/awx#1566]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

When using the set_fact method and the variable to set involves using a template, AWX intermittently throws the following templating error:

`"msg": "Unexpected templating type error occurred on ({{ ((dir_output.stdout_lines[0])[-1] | regex_search(regexp,'\\\\g<fs>') | list)[0] | int }}): 'NoneType' object is not iterable"`

##### ENVIRONMENT
* AWX version: 1.0.4.78
* AWX install method: docker on linux,
* Ansible version:  2.4.3.0
* Operating System: Red Hat 4.8.5-16
* Web Browser: Google Chrome Version 65.0.3325.162 (Official Build) (64-bit)

##### STEPS TO REPRODUCE

To reproduce, use the set_fact method and try to set the variable value based upon the result of a regular expression using a template:

For example:

`    - name: Check flash directory free space
      asa_command:
        commands:
          - command: "dir {{ new_image.filesystem }}"
      register: dir_output
    - name: Record number of bytes free within Flash
      set_fact:
        flash_free_space: "{{ ((dir_output.stdout_lines[0])[-1] | regex_search(regexp,'\\g<fs>') | list)[0] | int }}"
      vars:
        regexp: '(?P<fs>[0-9]*) bytes free'`

The code snippet above looks to record the number of bytes free within the flash directory of a Cisco ASA device by looking at the end of the output and locating the value next to "bytes free".

##### EXPECTED RESULTS

The following result is expected:

`"ansible_facts": {
        "flash_free_space": "154906624"
    }`

##### ACTUAL RESULTS

The following result is observed, albeit intermittently:

`"msg": "Unexpected templating type error occurred on ({{ ((dir_output.stdout_lines[0])[-1] | regex_search(regexp,'\\\\g<fs>') | list)[0] | int }}): 'NoneType' object is not iterable"`

**Comment by wenottingham** [comment]
This appears to be an issue with Ansible, not Tower. Please file at https://github.com/ansible/ansible, or reopen if it's something specific to Tower.
