### ISSUE TITLE
upgrade etcd

### ISSUE THREAD

**Issue by kfox1111** [ansible/awx#1578]
https://github.com/ansible/awx/blob/devel/installer/kubernetes/templates/etcd.yml.j2
Points to:
elcolio/etcd

This is a very old version of etcd. Can it be templated so you can specify your own value? Should it default to:
https://quay.io/repository/coreos/etcd?tag=latest&tab=tags

Does it work with etcd3?

Also it looks like its not maintaining state. Is it just used for locking? Is it safe to delete the etcd pod?

**Comment by matburt** [comment]
I'd be fine trying out the upgrade to the latest coreos etcd2... I'm not sure if etcd3 works.

We use etcd2 to drive rabbitmq autoclustering so it's pretty important. If you remove the etcd2 pod entirely then the rabbitmq services will not be able to cluster together and things will break in fantastic ways.

**Comment by kfox1111** [comment]
Is rabbit the only user of etcd?
If thats the case, how about:
https://www.rabbitmq.com/cluster-formation.html#peer-discovery-k8s?

It would completely eliminate a source of redundant state.

**Comment by matburt** [comment]
Yes! This is interesting... we'll have a look. Whatever we do would need to work for both Openshift and Kubernetes

**Comment by matburt** [comment]
We'll need to upgrade our rabbitmq image since this relies on 3.7 rabbitmq clustering.

**Comment by krepflap** [comment]
Is this fixed? Right now etcd isn't being deployed anymore in the code:

https://github.com/ansible/awx/search?utf8=%E2%9C%93&q=etcd&type=

Considering @matburt 's remark:
>If you remove the etcd2 pod entirely then the rabbitmq services will not be able to cluster together and things will break in fantastic ways.

Is this oversight? Transitional phase?

**Comment by krepflap** [comment]
I'm guessing this is fixed in 935dc8bca7d5a03e2b2aeb3a199be0181b62ccbb.

**Comment by ryanpetrello** [comment]
@krepflap correct - we looked into https://github.com/ansible/awx/issues/1578#issuecomment-373770886 and awx now uses https://github.com/rabbitmq/rabbitmq-peer-discovery-k8s rather than etcd for peer discovery.
