### ISSUE TITLE
add more flexibility to kubernetes service definitions

### ISSUE THREAD

**Issue by kfox1111** [ansible/awx#1579]
The awx service is hardcoded to to be of type NodePort. In my case I would like to export it through ingress. Can service.type be made a variable so nodeport can be disabled when not desired?

Ingress is also not configurable. I have multiple ingress controllers at one of my sites and need to specify annotations to bind it to a particular one. 

The deployment also needs support for specifying a nodeSelector so it can be deployed on the right pool of nodes when you have a heterogeneous cluster.

**Comment by kfox1111** [comment]
Oh. a toleration section would be useful too. That would let you land it on controller nodes.

**Comment by matburt** [comment]
This sounds like a good idea, and I'm fine with a PR that extends the service definitions to support these things.

**Comment by shanemcd** [comment]
Ingress customization and tolerations are both supported by https://github.com/ansible/awx-operator
