### ISSUE TITLE
SCM update in Demo Project failed with "permission denied" error

### ISSUE THREAD

**Issue by shen3lu4** [ansible/awx#1582]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

Installed AWX in kubernetes successfully. Tried to run SCM Update with the out-of-box Demo Project and received a Permission denied error.

##### ENVIRONMENT
* AWX version: dockerhub version 1.0.3
* AWX install method: kubernetes 
* Ansible version: 2.4.0.0
* Operating System: Oracle Enterprise Linux 7.4
* Web Browser: Chrome

##### STEPS TO REPRODUCE

A fresh installation. No configuration changes.
Go to Projects -> Choose Demo Project -> Leave all 3 check boxes under "SCM UPDATE OPTIONS" unchecked -> Run "Start an SCM update"

##### EXPECTED RESULTS

SCM update successfully clones https://github.com/ansible/ansible-tower-samples.

##### ACTUAL RESULTS

    
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: Unable to set correct type for configuration entry:
DEFAULT_LOCAL_TMP

PLAY [all] *********************************************************************

TASK [delete project directory before update] **********************************
skipping: [localhost]

TASK [check repo using git] ****************************************************
skipping: [localhost]

TASK [update project using git] ************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 13] Permission denied: '~'
fatal: [localhost]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1

**Comment by techwavedev** [comment]
It also doesn't work on docker deployment

**Comment by wwitzel3** [comment]
Please try again with latest devel. Some bug fixes were merged that should resolve this.

**Comment by shen3lu4** [comment]
Used the latest devel and also the latest dockerhub images (instead of 1.0.3), this issue has been resolved.

**Comment by wenottingham** [comment]
Thanks for the update!

**Comment by MansM** [comment]
Currently encountering this again
using 1.0.5.20

```
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: Unable to set correct type for configuration entry:
DEFAULT_LOCAL_TMP


PLAY [all] *********************************************************************


TASK [delete project directory before update] **********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 13] Permission denied: '~'
fatal: [localhost]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```
unfortunately I cant add some v's to the scm job
