### ISSUE TITLE
UI badly represents API active jobs error message

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#1584]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Resources deleted while jobs are running throw an error

the UI shows this badly

##### ENVIRONMENT
* AWX version: 1.0.4-258-g2640ef8b1c
* AWX install method: docker for mac
* Ansible version:  N/A
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Create an inventory source that runs a script that sleeps for 5 minutes

Sync it

While that is running try to delete it

##### EXPECTED RESULTS

Details from the API response

```json
{"active_jobs":[{"type":"inventory_update","id":"133"}],"error":"Resource is being used by running jobs."}
```

##### ACTUAL RESULTS

![screen shot 2018-03-15 at 3 50 25 pm](https://user-images.githubusercontent.com/1385596/37487776-f701bfd6-2868-11e8-9245-58ea21d36272.png)

**Comment by chrismeyersfsu** [comment]
As a result of this change https://github.com/ansible/awx/pull/1536

UI folks, the return payload for resources that have running jobs has changed. We will return 409, but the payload `conflict` key has changed to `error` to be more in line with our normal error returns.

**Comment by wenottingham** [comment]
-> https://github.com/ansible/awx/issues/1295

**Comment by AlanCoding** [comment]
That might not be the exact same bug, because this is the inventory source list page, and that one was the inventory source edit page.
