### ISSUE TITLE
Demo Project cannot be deleted. Official Docker images - 1.0.4.97

### ISSUE THREAD

**Issue by lukasmrtvy** [ansible/awx#1585]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

Demo project can not be deleted from Projects on fresh deploy of AWX  1.0.4.97 from Docker hub official images.

Logs from awx_web container:
https://pastebin.com/9QDS84Sf

##### ENVIRONMENT
* AWX version: 1.0.4.97
* AWX install method: docker linux
* Operating System: Docker

##### STEPS TO REPRODUCE

1. run awx stack on version 1.0.4.97
2. try to delete demo project from projects
3. Error shows up ( Call to /api/v2/projects/4/ failed. DELETE returned status: 500 A server error has occurred. ) 
4. more logs in awx_web

**Comment by tobgen** [comment]
Same issue in AWX 1.0.4.96

**Comment by wwitzel3** [comment]
Looks like one of the model classes didn't receive the new mixin `RelatedJobsMixin`

**Comment by wwitzel3** [comment]
I was wrong, mixins were properly applied, the view logic looks for the `get_active_jobs` method on the Project itself, so we need to collect that information from the project_updates related to it. PR up with fix.

**Comment by Glutexo** [comment]
Just to clarify for further readers, this applies to any project, not just the Demo one.
