### ISSUE TITLE
Support Kubernetes along with Openshift

### ISSUE THREAD

**Issue by chadswen** [ansible/awx#159]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - Installer

##### SUMMARY
Create an installer that will deploy to a (non-OpenShift) Kubernetes cluster. Since the Dockerfile and OpenShift templates already exist this could be a relatively easy win.

**Comment by matburt** [comment]
This is an excellent idea... a lot of the current openshift role can be a guide for this.

**Comment by elnappo** [comment]
This could be done as a Kubernetes [Helm](https://github.com/kubernetes/helm) package.

**Comment by chadswen** [comment]
@elnappo It could, but not every cluster runs Helm Tiller, nor should every cluster. There are still some [authorization growing pains](https://github.com/kubernetes/helm/issues/1918) that prevent Helm from being operationalized in some environments.

Besides, the OpenShift templates already exist and could be reused. While using the Helm chart/release lifecycle to manage would be convenient, Ansible templating on top of Helm templating might be a bit overkill.

I think a Helm chart would make sense eventually, but that would be secondary to a Kubernetes native solution.

**Comment by victorock** [comment]
What about creating this based on ansible-container?

**Comment by matburt** [comment]
From what I understand AC still lacks support for ConfigMap and maybe Secrets, both of which would be crucial.

**Comment by tima** [comment]
That is my understanding @matburt based on what @chouseknecht said in #189. Pull request accepted.

**Comment by arthur-c** [comment]
I built an helm package for myself (a single deployment with awx_task and awx_web from the docker hub in a pod), and I am using stable charts for postgresql, memcached and rabbitmq. 

It is still in alpha/beta but if someone is interested let me know.

**Comment by jrosengren** [comment]
@arthur-c, I'd be interested in taking a look at what you've come up with.

**Comment by tima** [comment]
@arthur-c: If this is a module (assuming that’s what you mean by package) I’d suggest you mention your work over in the Ansible project for more visibility and feedback.

**Comment by arthur-c** [comment]
@jrosengren here it is: https://github.com/arthur-c/ansible-awx-helm-chart
It is still a draft, I would like to use internal Helm requirements to install postgresql, rabbitmq and memcached and enhance the package.
The interesting part is the configmap template in awx-web-task/template. I added the latest changes from the awx devel branch but it might break soon as the project is moving fast.

@tima it's pure helm. I like ansible but I prefer to use helm to deploy on Kubernetes as it is widely adopted by the community. Ansible has already a module to manage helm packages, it's trivial to make a playbook to manage this installation.

**Comment by matburt** [comment]
I think this is excellent... it's probably a bit incompatible with my `scalable_clusters` branch. I feel like I'd probably take this idea and change it up a little bit. Nice work :)

**Comment by arthur-c** [comment]
Ideally the chart should be splitted in two. I first tried to make 1 chart for the web part and 1 for the task part but I had some trouble to figure out how the two parts talk to each other.

**Comment by andrewhowdencom** [comment]
> @elnappo It could, but not every cluster runs Helm Tiller, nor should every cluster. There are still some authorization growing pains that prevent Helm from being operationalized in some environments.

Incidentally, the current advise is to run an instance of helm per namespace, or in a `${namespace}-system` namespace. This allows limiting of access.

**Comment by matburt** [comment]
I've posted pr #938 that will add initial support for this.

I went ahead and did this in the same vein as the openshift installer. I could definitely see the value in having a Chart for this but want initial support to follow our current model.

**Comment by arthur-c** [comment]
I bumped this thread as I upgraded the previoud chart I made last year - if anyone interested : https://github.com/arthur-c/ansible-awx-helm-chart

It's not perfect but it's already a lot cleaner and up to date.
