### ISSUE TITLE
Help Text not rendering correctly

### ISSUE THREAD

**Issue by tvo318** [ansible/awx#1592]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Help text in Key doesn't render correctly: 
![image](https://user-images.githubusercontent.com/7514801/37536505-57a5580a-2910-11e8-85ec-694e7b8ecd1a.png)

##### ENVIRONMENT
* AWX version: Tower 3.3.0.435
* AWX install method: spun dev instance from engineering gce job template
* Ansible version: Ansible 2.4.2.0
* Operating System: Mac OS
* Web Browser: Chrome

##### STEPS TO REPRODUCE
1. Go to Users page
2. Click on a user
3. Click on Permissions tab
4. Click on Add to add permissions for that user
5. Click on a resource that has EXECUTE as an option for a Role
6. Check a box next to the resource you want to assign a role to.
7. Click Key 
The description for **Execute** looks like it didn't parse just the description but other code as well. 

##### EXPECTED RESULTS

The description for **Execute** should only have a Standard-english description

##### ACTUAL RESULTS
See screen capture above.

##### ADDITIONAL INFORMATION
Also, not sure if it is working as designed, but if you click on a resource and put a checkbox next to a resource name, then that tab automatically goes down in the Roles area as well. Should it? In the example below, I had selected the 3 resources shown (JT, Inventories, and Organizations) and they persisted and remained on the Role section of the UI:

![image](https://user-images.githubusercontent.com/7514801/37537896-9cd983d4-2914-11e8-98fa-42e2917f2b41.png)

(It is confusing, because there are already resources above, but if it is like a breadcrumb "last visited" then I can make a note of that in the docs so users don't get confused like I did)

**Comment by jaredevantabor** [comment]
This appears to have been fixed.
