### ISSUE TITLE
"&" symbol in password

### ISSUE THREAD

**Issue by soloman747** [ansible/awx#1595]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Passwords that have the "&" symbol fail.

##### ENVIRONMENT
* AWX version: 1.0.4
* AWX install method: docker on linux
* Ansible version:  2.4.3
* Operating System: Centos
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create an administrator password with ampersand "&" symbol and try to log into the UI

##### EXPECTED RESULTS

The password should work and allow me to log in as an administrator.

##### ACTUAL RESULTS

The login fails

**Comment by wenottingham** [comment]
-> https://github.com/ansible/awx/issues/1553
