### ISSUE TITLE
Update rabbitmq and use k8s plugin for clustering

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1600]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - Installer

##### SUMMARY

We currently pull RMQ 3.6.14 into the K8S/OpenShift install, and use etcd2 for handling autoclustering.

RabbitMQ 3.7 supports a K8S autodiscovery mechanism: http://www.rabbitmq.com/cluster-formation.html#peer-discovery-k8s. This sounds better than maintaining our own etcd container.

Work is approximately:

1) revving the rabbitmq image versions all around
b) update our rabbitmq config to accept some templated values
iii) find a way to apply those templates at deployment, or at least take them as env vars so they get picked up on pod launch
4) revise the inventory file if the defaults don’t work
V) k8s vs openshift differences?

##### ENVIRONMENT
* AWX version: current

##### ADDITIONAL INFORMATION
See also https://github.com/ansible/awx/issues/1578#issuecomment-373770886

**Comment by krepflap** [comment]
I think this can also be closed since 935dc8bca7d5a03e2b2aeb3a199be0181b62ccbb.
