### ISSUE TITLE
API filter doesn't work for roles endpoint with fields 'name' and 'description'

### ISSUE THREAD

**Issue by kma617** [ansible/awx#1604]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
API filter doesn't work for roles endpoint with fields name and description

##### ENVIRONMENT
* AWX version: 1.0.4.80
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: ubuntu 16.04
* Web Browser: Firefox 59.0

##### STEPS TO REPRODUCE
Send GET request to
https://your-awx.com/api/v2/roles/?name=Use

##### EXPECTED RESULTS

Answer with list of roles which have name='Use'

##### ACTUAL RESULTS

HTTP 400 Bad Request
{
    "detail": "Role has no field named 'name'"
}

**Comment by AlanCoding** [comment]
try `/api/v2/roles/?role_field=use_role`

extremely detailed hackery for filtering roles is demonstrated with tower-cli
