### ISSUE TITLE
SSH Error - data could not be sent to remote host

### ISSUE THREAD

**Issue by riponbanik** [ansible/awx#1605]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Cannot connect to an ec2 instance using the private key while running the playbook using job template.

##### ENVIRONMENT
* AWX version: 1.0.4
* AWX install method: docker on linux
* Ansible version: 2.4.3.0
* Operating System: Red Hat Enterprise Linux Server release 7.4 (Maipo)
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Setup inventory with host, private key and user
2. Setup job with existing repo
3. Run playbook against the inventory

##### EXPECTED RESULTS

Should be able to connect to the host using ssh private key

##### ACTUAL RESULTS
Connection fails with following results -

ssh -vvv -o ControlMaster=auto -o ControlPersist=30m -o StrictHostKeyChecking=no -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 -o ControlPath=/tmp/awx_20_4deC_Z/cp/%h%p%r 10.50.x.x '/bin/sh -c '"'"'no_proxy=localhost,127.0.0.1,169.254.169.254,10.0.0.0/8,.example.com,s3-ap-southeast-2.amazonaws.com https_proxy=http://awsproxy.example.com:80 http_proxy=http://awsproxy.example.com:80 /usr/bin/python && sleep 0'"'"''

##### ADDITIONAL INFORMATION
We use proxy in our environment. Also ping, telnet and ssh connection to the target host from docker container awx_task_1, shows ok.

**Comment by matburt** [comment]
Connections seem to work okay for me, but I don't have access to a proxy to test so if you can gather some more information that would certainly be helpful. There are some suggestions here: https://github.com/ansible/awx/issues/1532 that might help you.

**Comment by riponbanik** [comment]
@matburt Thanks for looking at it. Proxy was specified in docker-compose to launch and is being used by Docker Daemon to use Internet. Please see the excerpt below.

web:
    image: ansible/awx_web:latest
    depends_on:
      - rabbitmq
      - memcached
      - postgres
    ports:
      - "80:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    dns_search: "example.com"
    dns: "10.70.x.x,10.70.x.x"
    environment:
      http_proxy: http://example.com:80
      https_proxy: http://example.com:80
      no_proxy: localhost,127.0.0.1,169.254.169.254,10.0.0.0/8,.example.com,s3-ap-southeast-2.amazonaws.com

**Comment by wenottingham** [comment]
Apologies for the delay - is this still occuring for you?

**Comment by riponbanik** [comment]
@wenottingham yes it is

**Comment by wenottingham** [comment]
Are you still on 1.0.4?

**Comment by riponbanik** [comment]
@wenottingham yes. Shall I try to upgrade it?

**Comment by wenottingham** [comment]
It may help; I don't have a specific PR to reference, but we are not doing fixes for 1.0.4, so a reproduction scenario on the latest release would help.

**Comment by riponbanik** [comment]
Upgrade failed with the following error message -

[2018-06-25 06:31:54,835: ERROR/MainProcess] Task awx.main.scheduler.tasks.run_task_manager[0a64b1c8-847e-4abf-bdd2-2ec4ce4987f3] raised unexpected: InternalError('current transaction is aborted, commands ignored until end of transaction block\n',)

I have used the following commands -

Stop AWX : docker-compose stop
Upgrade AWX : docker-compose pull && docker-compose up --force-recreate

**Comment by riponbanik** [comment]
I have removed the environment proxy config in the playbook and it resolved the origin issue to connect to machine
