### ISSUE TITLE
The Application resources could not show [description] and [organization] information correctly

### ISSUE THREAD

**Issue by zhangtiny123** [ansible/awx#1614]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

I've deployed the latest code by building image myself, and create a new application, and filled in all informations, then I go to the other page, and  click the resource link to view the details, but there is no **DESCRIPTION** and **ORGANIZATION** information. 

##### ENVIRONMENT
* AWX version: 1.0.4.106
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System:
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Deploy the awx version 1.0.4.106
2. Login to the awx web UI 
3. Go to the application page and create an application with all information, include **DESCRIPTION** and **ORGANIZATION**
4. Then view the application's detail information

##### EXPECTED RESULTS

**DESCRIPTION** and **ORGANIZATION** should be showing on the page.

##### ACTUAL RESULTS

There's no **DESCRIPTION** and **ORGANIZATION** showing on the page.

##### ADDITIONAL INFORMATION

From the application API, I see the **DESCRIPTION** information is right there, but nothing about the **ORGANIZATION**

**Comment by ryanpetrello** [comment]
Hey @zhangtiny123,

Thanks for reporting this - I'm able to see the same behavior.

**Comment by jaredevantabor** [comment]
this is fixed now in devel
