### ISSUE TITLE
"relation "conf_setting" does not exist at character 158" & "relation "django_migrations" does not exist at character 124" errors in postgres container 

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/awx#1618]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - awx_web

##### SUMMARY
Browsing to the localhost URL yields the "This site can’t be reached" error.
I see ```Starting server at tcp:port=8051:interface=127.0.0.1, channel layer awx.asgi:channel_layer.``` in dockercompose_web_1 logs, yet the container redirects 0.0.0.0:80->8052/tcp.  This may explain the issue. Or maybe I'm missing something.

##### ENVIRONMENT
* AWX version: tag 1.0.4
* AWX install method: docker/docker-compose on linux
* Ansible version: v2.4.3.0-1
* Operating System: Ubuntu 17.10
* Web Browser: chrome 65.0.3325.162
* docker-ce ```18.02.0~ce-0~ubuntu``` (from official docker PPA)
* docker==3.1.3
* docker-compose==1.20.0
* requests==2.18.1
* Django==1.11.10

##### STEPS TO REPRODUCE

```
# echo ---------------------------
# echo Starting all AWX containers
# echo ---------------------------
# cd <docker-compose.yml folder>
# docker-compose start
Starting memcached ... done
Starting postgres  ... done
Starting rabbitmq  ... done
Starting web       ... done
Starting task      ... done

# docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                NAMES
d54f70bc9382        ansible/awx_task:latest   "/tini -- /bin/sh -c…"   15 minutes ago      Up 15 minutes       8052/tcp                             dockercompose_task_1
4474f311762e        ansible/awx_web:latest    "/tini -- /bin/sh -c…"   15 minutes ago      Up 15 minutes       0.0.0.0:80->8052/tcp                 dockercompose_web_1
58ec082ced51        rabbitmq:3                "docker-entrypoint.s…"   15 minutes ago      Up 15 minutes       4369/tcp, 5671-5672/tcp, 25672/tcp   dockercompose_rabbitmq_1
a67dadbea52a        postgres:9.6              "docker-entrypoint.s…"   15 minutes ago      Up 15 minutes       5432/tcp                             dockercompose_postgres_1
5ce8b8f76985        memcached:alpine          "docker-entrypoint.s…"   15 minutes ago      Up 15 minutes       11211/tcp                            dockercompose_memcached_1
```
[dockercompose_task_1.logs](https://github.com/ansible/awx/files/1830120/dockercompose_task_1.logs.txt)
[dockercompose_web_1.logs](https://github.com/ansible/awx/files/1830122/dockercompose_web_1.logs.txt)

Access http://localhost with chrome

##### EXPECTED RESULTS
Login screen

##### ACTUAL RESULTS
This site can’t be reached

**Comment by jean-christophe-manciot** [comment]
upgrading to stable ```18.03.0~ce-0~ubuntu``` leads to some similar logs for the **[web container](https://github.com/ansible/awx/files/1838292/dockercompose_web_1.logs.txt)**:
```
# docker logs -f dockercompose_web_1
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
...
django.db.utils.OperationalError: could not connect to server: Connection refused
	Is the server running on host "postgres" (172.23.0.4) and accepting
	TCP/IP connections on port 5432?
```
Checking that the postgres container lives at the expected IP address and port:
```
# docker ps 
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                NAMES
3aec2f95c206        ansible/awx_task:latest   "/tini -- /bin/sh -c…"   25 minutes ago      Up 25 minutes       8052/tcp                             dockercompose_task_1
169df4ff8898        ansible/awx_web:latest    "/tini -- /bin/sh -c…"   25 minutes ago      Up 25 minutes       0.0.0.0:80->8052/tcp                 dockercompose_web_1
237f8d0e4551        postgres:9.6              "docker-entrypoint.s…"   25 minutes ago      Up 25 minutes       5432/tcp                             dockercompose_postgres_1
a8395ce35ad7        rabbitmq:3                "docker-entrypoint.s…"   25 minutes ago      Up 25 minutes       4369/tcp, 5671-5672/tcp, 25672/tcp   dockercompose_rabbitmq_1
a4e6e3b46011        memcached:alpine          "docker-entrypoint.s…"   25 minutes ago      Up 25 minutes       11211/tcp                            dockercompose_memcached_1

# docker inspect dockercompose_postgres_1 | grep "\"IPAddress\": "
"IPAddress": "172.23.0.4"
docker inspect dockercompose_postgres_1 | grep -C 1 "\"Ports\": "
"Ports": {
                "5432/tcp": null
```

and the logs for **[postgres container](https://github.com/ansible/awx/files/1838298/dockercompose_postgres_1.logs.txt)** show:
```
# docker logs -f dockercompose_postgres_1
...
LOG:  received fast shutdown request
LOG:  aborting any active transactions
waiting for server to shut down....LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

LOG:  database system was shut down at 2018-03-22 15:43:15 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  incomplete startup packet
ERROR:  relation "conf_setting" does not exist at character 158
...
ERROR:  relation "django_migrations" does not exist at character 124
...
...
```
It seems that awx **web container cannot connect to postgres container because of the errors** **```relation "conf_setting" does not exist at character 158``` & ```relation "django_migrations" does not exist at character 124```**.

Other logs:
- [task container](https://github.com/ansible/awx/files/1838305/dockercompose_task_1.logs.txt)
- [rabbitmq container](https://github.com/ansible/awx/files/1838308/dockercompose_rabbitmq_1.logs.txt)

**Comment by mvanrompuy** [comment]
Seeing the same issue on v1.5.0.

**Comment by jean-christophe-manciot** [comment]
@mvanrompuy 
Yes, same issue with latest awx with a fresh install using the following parts:
* AWX version: tag 1.0.5
* AWX install method: docker/docker-compose on linux
* Ansible version: v2.5.0 (from official ansible PPA)
* Operating System: Ubuntu 17.10
* docker-ce ```18.03.0~ce-0~ubuntu``` (from official docker PPA)
* docker==3.1.4
* docker-compose==1.20.1
* requests==2.18.1

**Comment by jean-christophe-manciot** [comment]
If awx is installed from sources as non root user with ```$ ansible-playbook -i inventory install.yml```, postgres container fails with:
```
# docker logs -f dockercompose_postgres_1
mkdir: cannot create directory ‘/var/lib/postgresql/data’: Permission denied
```

**Comment by wenottingham** [comment]
Apologies, but there have been many changes since then, and this reads as a generic installation error due to bad settings.

Please try 2.0+, and file a new issue if this persists.

**Comment by alsgow** [comment]
facing same issue with latest versions any fix

**Comment by chandrukvr** [comment]
Getting the same ERROR with new ansible version as well..

ERROR:  relation "django_migrations" does not exist at character 124
STATEMENT:  SELECT "django_migrations"."id", "django_migrations"."app", "django_migrations"."name", "django_migrations"."applied" FROM "django_migrations" WHERE ("django_migrations"."app" = 'main' AND NOT ("django_migrations"."name"::text LIKE '%squashed%')) ORDER BY "django_migrations"."id" DESC LIMIT 1

anyone there to help ?

**Comment by clayrisser** [comment]
I'm facing the same issue.

**Comment by piaverous** [comment]
Facing the same issue in latest version, after deploying with `awx-operator` (not sure if I should open an issuer here or there)

Steps to reproduce : 
- Create a GCP Kubernetes Managed Cluster
- Get operator 0.13.0 release : `curl -O https://raw.githubusercontent.com/ansible/awx-operator/0.13.0/deploy/awx-operator.yaml`
- Apply : `kubectl apply -f awx-operator.yaml`
- Create the most basic manifest (example in `awx-operator` README) in file `awx-demo.yaml` : 
```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: nodeport
  ingress_type: none
  hostname: awx-demo.example.com
```
- Deploy it using `kubectl apply -f awx-demo.yaml`

I then get tons of logs like so : 
```
2021-09-07 20:54:52.866 UTC [1355] ERROR:  relation "conf_setting" does not exist at character 158
...
2021-09-07 20:54:54.211 UTC [1358] ERROR:  relation "main_instance" does not exist at character 24
```


--- 
Additional information : 
- awx operator image : `quay.io/ansible/awx-operator:0.13.0`
- awx docker image : `quay.io/ansible/awx:19.1.0`
- Postgres image : `postgres:12`

Got any clues ?

**Comment by sharad7828** [comment]
I had the same issue, tried many things but did not help. After ~1hours it started working fine even with same error in postgres log.
