### ISSUE TITLE
Credential password structure different for launch/relaunch endpoints

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#1621]
##### ISSUE TYPE
 - Bug Report (I think)

##### COMPONENT NAME
 - API

##### SUMMARY
When launching a job template with credentials that require passwords at run time, the api accepts the following format in the POST:

```
{
    credential_passwords: {
        ssh_password: "foo",
        become_password: "bar"
    }
}
```

When hitting the relaunch endpoint for the same job, the api throws a 400 if the passwords are formatted like they are above.  I think the api is expecting them to come in like:

```
{
    ssh_password: "foo",
    become_password: "bar"
}
```

I _think_ that this is a bug.  I'm pretty sure that the format directly above is the legacy format (pre-vault credential changes).  There could be a good reason why the api expects this format for relaunch but I figured I'd better make an issue just in case this was missed.  If this gets closed without any API changes then the UI will need a bit of work to make sure that the format matches up.

##### STEPS TO REPRODUCE

Outlined in summary but the basic gist is:

1) Create a credential that requires password on launch
2) Create a JT that uses the credential in step 1
3) Launch a job with that JT
4) Try to relaunch the job and pass credential passwords in the specified format

**Comment by wenottingham** [comment]
cc @AlanCoding

**Comment by AlanCoding** [comment]
both new / old request data structure supported now
