### ISSUE TITLE
URI module is logging the password task argument to job_events in plaintext

### ISSUE THREAD

**Issue by mattcrossm** [ansible/awx#1633]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Passwords used within the "password" option of the URI module are being logged in plain text to the "task_args" field of the job_event

##### ENVIRONMENT
* AWX version: 1.0.4.109
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: Ubuntu 16
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Run a playbook with a URI task that includes the password option

- name: "Running vmBase playbook"
  local_action:
    module: uri
    url: "{{ awx_api_url }}/job_templates/7/launch/"
    method: POST
    validate_certs: no
    body: {"inventory": "{{ AWX_INVENTORY }}", "limit": "{{ inventory_hostname }}", "credential": 45}
    body_format: json
    user: "{{ srvfiamawx_user }}"
    password: "{{ srvfiamawx_password }}"
    status_code: 200, 201
  register: awx_playbook

##### EXPECTED RESULTS

The password option would be censored

From job_events:
"task_args": "body={u'credential': 45, u'limit': u'hostname', u'inventory': 16}, _ansible_version=2.4.3.0, password=******

##### ACTUAL RESULTS

The password is displayed in plaintext

From job_events:
"task_args": "body={u'credential': 45, u'limit': u'hostname', u'inventory': 16}, _ansible_version=2.4.3.0, password=plaintext

**Comment by ryanpetrello** [comment]
@mattcrossm have you tried adding `no_log: true` to your task?  awx records what Ansible passes it via the callback plugin, so if sensitive data is sent in plaintext, awx would have to guess at what needs censoring.

**Comment by mattcrossm** [comment]
I have used no_log for cases where sensitive data is passed within the body, but I was told in a similar request (https://github.com/ansible/awx/issues/697) that the password should be censored as long as it was passed to the "password" task argument instead of the body argument.

**Comment by ryanpetrello** [comment]
Hey @mattcrossm - a fix for this is coming in the near future.  In the meantime, try using `no_log` on your task.

**Comment by ryanpetrello** [comment]
Hey @mattcrossm,

This should be resolved now via https://github.com/ansible/awx/commit/5fd5c95a1d0e8ed98fa51244234db3ab83bcd185
