### ISSUE TITLE
Playbooks aren’t showing up in the “Job Template” drop-down

### ISSUE THREAD

**Issue by santizo** [ansible/awx#1636]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI
##### SUMMARY
When running through the basic helloworld example template the "PLAYBOOK: Choose a playbook" dropdown doesn't not populate any playbooks. I can add the project but cant see any playbooks inside of it. I am using the helloworld project from https://github.com/ansible/tower-example . I double-checked permissions and /var/lib/awx/projects/* is owned by awx:awx so it should be visible, no issues adding the project itself. I also tried creating a template from a project that is git sourced (https://github.com/ansible/ansible-tower-samples.git) and got the same results.

##### ENVIRONMENT
* AWX version: 1.0.4.114
* AWX install method: docker-compose
* Ansible version:   2.4.3.0
* Operating System: RHEL 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Follow the guide to creating a helloworld project/template:
http://docs.ansible.com/ansible-tower/2.3.0/html/quickstart/create_job.html

##### EXPECTED RESULTS

It would display and allow me to choose a playbook from the selected project.

##### ACTUAL RESULTS

No playbooks are listed, can't save template because it is required.

**Comment by ryanpetrello** [comment]
@santizo has an update been run for the project?

![screen shot 2018-03-21 at 1 02 29 pm](https://user-images.githubusercontent.com/214912/37724892-20f032b6-2d08-11e8-924d-6208b61d6f4b.png)

**Comment by santizo** [comment]
I ran one manually for the git helloworld project. The manual project with the same helloworld.yml does the same thing though.

I found issue: https://github.com/ansible/awx/issues/1603 which looks similar to mine, the regex pointed out should match my playbook on line 3.
```
cat helloworld.yml
---
- name: Hello World!
  hosts: all

  tasks:

  - name: Hello World!
    shell: echo "Hi! Tower is working."
```

**Comment by santizo** [comment]
I apologize, it was an selinux issue. Both manual  and git based projects are working now.

**Comment by danleonard80** [comment]
Hi Santizo, could you please elaborate on how you resolved the selinux issue that was preventing the list of playbooks from populating?

**Comment by realtebo** [comment]
@santizo Hi ! I have same problem.... what  is the solution you found?

**Comment by 15ramky** [comment]
i ran into the similar issue
for me adding "hosts" is missed in the playbook, it's working fine after added the hosts

---
- name: to get the jdm config
  **hosts**: testing

**Comment by peternerd** [comment]
@santizo Could you please share how you solved this issue?

**Comment by zhangbin1137** [comment]
@santizo Could you pls share your solution,thanks.

**Comment by ramzcode** [comment]
@15ramky  I did the same mistake on my first test playbook on AWX.. Thank you so much for the input.

**Comment by andyitsus** [comment]
> i ran into the similar issue for me adding "hosts" is missed in the playbook, it's working fine after added the hosts
> 
> * name: to get the jdm config
>   **hosts**: testing

This is the solution.  The suggested workaround from Red Hat is somewhat vague:

https://access.redhat.com/solutions/7059433

I think what they specifically mean is that the playbook yaml has to be in the "correct" syntax before it comes displayable.
And that means having the hosts variable defined as suggested by @15ramky .  Then it becomes visible.

Also discussed in this StackOverflow link:

https://stackoverflow.com/questions/66215777/ansible-awx-unable-to-choose-a-playbook-when-tried-creating-awx-job-template
