### ISSUE TITLE
RFE: Support provisioning callbacks via isolated nodes when the node can't reach tower proper

### ISSUE THREAD

**Issue by benjdudas** [ansible/awx#1638]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY

For isolated nodes have a default option that could be used by hosts in the isolated networks to make callbacks. 

One option would be to configure the isolated node as a SSL proxy for those hosts to reach the control nodes. 

##### ENVIRONMENT
* AWX version: any

**Comment by shanemcd** [comment]
RIP isolated nodes. We may tackle this problem under the future Receptor architecture.
