### ISSUE TITLE
Inventory Update Events are all created after finish time

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#1639]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Inventory updates should be something that the client can continuously monitor, but it appears that events are getting stuck in some buffer until the update is fully finished.

##### ENVIRONMENT
* AWX version: 1.0.4-318
* AWX install method: docker for mac
* Ansible version:  N/A
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Run and inventory update that takes a considerable time to run.

##### EXPECTED RESULTS

That events are saved and show up in the API in real time.

##### ACTUAL RESULTS

Inspect any inventory update events, and you can find that fields like `created` on the _event_ take place after the `finished` time on the inventory update. By my testing so far, this is true for all inventory update events.

**Comment by cchurch** [comment]
With events emitted via callback plugin, we capture the time of that event in the event data (https://github.com/ansible/awx/blob/devel/awx/lib/awx_display_callback/events.py#L132), whereas with stdout from anything else, the created timestamp would be set when the event is inserted into the database. This would likely show up on system jobs too, and even in normal jobs for stdout emitted outside of the callback (e.g. ssh-agent output, ansible prompts).

Setting a created timestamp in the event (if not present) as soon as it's read from stdout (https://github.com/ansible/awx/blob/devel/awx/main/tasks.py#L848) may work.

**Comment by AlanCoding** [comment]
But what might be causing them to not get saved until the job is finished in the first place? This means that updates in the UI mid-run are impossible, since the API itself doesn't show the data until after finish. Is there any blocking logic within the callback that might be causing them to get held up?

**Comment by AlanCoding** [comment]
Confirmed on a real deployment

inventory update fields:

```
    "started": "2018-03-26T16:46:44.882200Z",
    "finished": "2018-03-26T16:51:51.880992Z",
```

first event

```json
        {
            "id": 9,
            "type": "inventory_update_event",
            "url": "",
            "related": {
                "inventory_update": "/api/v2/inventory_updates/35/"
            },
            "summary_fields": {},
            "created": "2018-03-26T16:51:51.951004Z",
            "modified": "2018-03-26T16:51:51.951023Z",
            "event": "verbose",
            "counter": 9,
            "event_display": "verbose",
            "event_data": {},
            "failed": false,
            "changed": false,
            "uuid": "",
            "stdout": "2018-03-26 16:51:51,501 INFO     awx.main.commands.inventory_import Inventory import completed for sdf in 301.1s",
            "start_line": 8,
            "end_line": 9,
            "verbosity": 0,
            "inventory_update": 35
        },
```

This script sleeps for 5 minutes.

**Comment by ryanpetrello** [comment]
Resolved downstream.
