### ISSUE TITLE
SCM group_vars not added to non-SCM additional hosts

### ISSUE THREAD

**Issue by cjworden** [ansible/awx#1647]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY

Additional hosts added to an inventory sourced from SCM don't get group_vars applied to them after being associated with said group.

##### ENVIRONMENT
* AWX version: 1.0.4.109
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: Debian 9
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1.  Create a new project from SCM using this repo: [https://github.com/cjworden/ansible-test-playbook](https://github.com/cjworden/ansible-test-playbook)
2. Create an inventory sourced from that project
3. Add an extra host which is not currently in the inventory to the inventory manually
4. Add the SCM sourced groups to your manually added host ("+ ASSOCIATE GROUP" button)
5. Create a job template using inventory created in step 2, project created in step 3, and playbooks/play.yml. 
6. Run the job

##### EXPECTED RESULTS

The job completes successfully against all hosts

##### ACTUAL RESULTS

The job runs successfully against all hosts defined in SCM, but fails on the manually added host due to unknown variable:

```
PLAY [Print variable] **********************************************************14:12:06
TASK [Print variable] **********************************************************14:12:06
fatal: [127.0.0.1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'test_var' is undefined\n\nThe error appears to have been in '/var/lib/awx/projects/_13__cody/playbooks/play.yml': line 5, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: Print variable\n      ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'test_var' is undefined"}
ok: [localhost] => {
    "msg": "this is a variable"
}
PLAY RECAP *********************************************************************14:12:06
127.0.0.1                  : ok=0    changed=0    unreachable=0    failed=1   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

##### ADDITIONAL INFORMATION

I'm not sure if this is the same underlying issue as #1192, if it is and should be fixed, what version should I update to to test it out? (I'm currently installing AWX using docker-compose pulling the 'latest' tag)

**Comment by AlanCoding** [comment]
Checked Ansible version 2.4.3.0, and the `--export` is not present. The bug you hit has been fixed, but you may need development version of Ansible. It might be in some release candidates, I have not checked.
