### ISSUE TITLE
Job Output is out of order when serial is set to 1.  

### ISSUE THREAD

**Issue by marcosgeorgopoulos** [ansible/awx#1650]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI
 

##### SUMMARY
As soon as the standard output for a job goes over 100 lines the output in the job UI gets out of order.

##### ENVIRONMENT
* AWX version: 1.0.4.93 
* AWX install method: , docker on linux
* Ansible version:  2.4.3.0 
* Operating System: RHEL
* Web Browser: Safari

##### STEPS TO REPRODUCE

Run a job with output longer than 100 lines, maybe less when serial is set to 1 in playbook. 

##### EXPECTED RESULTS

I expected the output to be in order.

##### ACTUAL RESULTS

The lines are out of order. 
<img width="980" alt="output_new" src="https://user-images.githubusercontent.com/5653675/37746424-49675ee2-2dce-11e8-89f9-4a22002b3ad0.png">

**Comment by marcosgeorgopoulos** [comment]
ok I have done some more testing and this issue seems to occur when serial is set to 1 in the playbook.
i.e  serial: 1 

I haven't had a chance to look through the code but perhaps its getting confused with the repeating TASK titles?

**Comment by wenottingham** [comment]
This is essentially #200 and #1540.
