### ISSUE TITLE
Allow job templates to have no credential at all

### ISSUE THREAD

**Issue by ghjm** [ansible/awx#1656]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Currently, the credential field is required in the UI.  However, there are scenarios where it makes sense to have a job template with no credentials at all.

For example, Tower running in AWS may be installed on an EC2 instance with an IAM role assigned that grants it privileges to manage other parts of the AWS infrastructure, without requiring any tokens or keys.

You can get around this by assigning 'Demo Credential' (or some other meaningless credential) to the JT, but it seems inelegant to require this.

**Comment by ryanpetrello** [comment]
@ghjm this _should be_ supported by the new multicred support in awx: https://github.com/ansible/awx/pull/595

If it's not working, it may be a bug in the UI.

**Comment by awithrow9** [comment]
This should be fixed.  Closing.
