### ISSUE TITLE
Feature: more granular permission types

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#166]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

Right now, a large number of permissions are lumped into "org admin". These should be separate permissions that an org admin (optionally) inherits, but can also be separately delegated.

Among the requests:
- [x] project creation
- [x] inventory creation
- [x] workflow creation
- [x] notification creation/assigning
- [ ] per-org LDAP team mapping creation (create team mappings for an org - this is delegating superuser -> org admin)
- [x] alternatively, prohibit an org admin from associating/disassociating users from teams

**Comment by cchurch** [comment]
- [x] credential creation (asked about at last night's AWX meetup - ability to create credentials for shared use within an org without being org admin)

**Comment by wenottingham** [comment]
Filed https://github.com/ansible/awx/issues/429 as something that should likely be tackled with this, but is functionally different.

**Comment by wwitzel3** [comment]
@wenottingham can you expand on: per-org LDAP team mapping creation (create team mappings for an org - this is delegating superuser -> org admin)

I don't full understand what is being asked for there. And is the alternatively line item an alternative to this?

**Comment by wenottingham** [comment]
The idea is such:
- each organization has an LDAP configuration
- the org admin can then make team mappings for that organization from that config

Question is how possible that is in the current framework.

**Comment by chrismeyersfsu** [comment]
Chicken and the egg. New user tries to login. We don't know what org that user belongs to, so we don't know which ldap servers to hit. Also, duplicate users, trust/conflict in the ldap org/team mapping.

Hmm, with a single ldap server config and a per-org LDAP mapping this is more feasible. But even with a single list of ldap servers, will there then be a per-server per-org LDAP team/org mapping?

**Comment by wenottingham** [comment]
@chrismeyersfsu @wwitzel3 think these last bits (LDAP mappings/user management) are better handled separately, tacked on to https://github.com/ansible/awx/issues/1526.

**Comment by wwitzel3** [comment]
We now have #1616 and #1126 and #429 broken out to their own bodies of work. Do you want to keep this open or can we close it out? @wenottingham

**Comment by wenottingham** [comment]
Yes, I think we can close this out.
