### ISSUE TITLE
UI doesn't refresh JOB TEMPLATE pages when the number is greater than 20 and the default 20 items per page is used.

### ISSUE THREAD

**Issue by cesan3** [ansible/awx#1660]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Have more than 20 JOB TEMPLATES configured, and use the default 20 items to view per page. If you hit the second page or next, it doesn't refresh, nor show the next page.

##### ENVIRONMENT
* AWX version: 1.0.4.125
* AWX install method: kubernetes
* Ansible version:  2.4.3.0
* Operating System: Linux
* Web Browser: Chrome / Firefox

##### STEPS TO REPRODUCE

Have more than 20 JOB TEMPLATES configured, and use the default 20 items to view per page.

##### EXPECTED RESULTS
We can navigate between pages to show all JOB_TEMPLATES.

##### ACTUAL RESULTS
 If you hit the second page or next, it doesn't refresh, nor show the next page. If you change the items to 50, they show up.

##### ADDITIONAL INFORMATION
Even if the webconsole shows the query, to retrieve the job templates per page, the table doesn't refresh.

The webconsole shows, when I hit the next page:

$onSuccess templates
app.90e45cc5c4a3ace158b7.js:29:192492
$onCreate templates
app.90e45cc5c4a3ace158b7.js:29:192154
$onBefore templates
app.90e45cc5c4a3ace158b7.js:29:192239
$onError templates
app.90e45cc5c4a3ace158b7.js:29:192323

Empty string passed to getElementById().
vendor.747e0213ca95621eb37b.js:29:32327

However, the query retrieves the elements of the page:

page1:

params:
order_by	name
page	2
page_size	20
type	workflow_job_template,job_template

response:

{"count":28,"next":null,"previous":"/api/v2/unified_job_templates/?order_by=name&page=1&page_size=20&type=workflow_job_template%2Cjob_template","results":[{"id":430,"type":"job_template","url":"/api/v2/job_templates/430/","related":{"created_by":"/api/v2/users/1/","modified_by":"/api/v2/users/1/","labels":"/api/v2/job_templates/430/labels/","inventory":"/api/v2/inventories/3/","project":"/api/v2/projects/14/","credential":"/api/v2/credentials/3/","extra_credentials":"/api/v2/job_templates/430/extra_credentials/","credentials":"/api/v2/job_templates/430/credentials/","notification_templates_error":"/api/v2/job_templates/430/notification_templates_error/","notification_templates_success":"/api/v2/job_templates/430/notification_templates_success/","jobs":"/api/v2/job_templates/430/jobs/","object_roles":"/api/v2/job_templates/430/object_roles/","notification_templates_any":"/api/v2/job_templates/430/notification_templates_any/","access_list":"/api/v2/job_templates/430/access_list/","launch":"/api/v2/job_templates/430/launch/","instance_groups":"/api/v2/job_templates/430/instance_groups/","schedules":"/api/v2/job_templates/430/schedules/","copy":"/api/v2/job_templates/430/copy/","activity_stream":"/api/v2/job_templates/430/activity_stream/","survey_spec":"/api/v2/job_templates/430/survey_spec/"},
......

**Comment by jaredevantabor** [comment]
I am seeing this too

**Comment by ryanpetrello** [comment]
@cesan3 mind giving this another look?  Should be resolved via https://github.com/ansible/awx/commit/3f15966d9dbdd20289e2c97b138142b2f1cfe7d1

**Comment by cesan3** [comment]
thanks @ryanpetrello , works now ( deployed version 1.0.6.1 on kubernetes).
