### ISSUE TITLE
Unable to use machine credential in custom inventory source

### ISSUE THREAD

**Issue by mkempster22** [ansible/awx#1661]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
A custom inventory source is unable to use a machine credential as it is filtered out of the available options. If the custom inventory is made to go off to a selection of servers, e.g. Solaris zones, then scan for hosts the machine credential would be needed

##### ENVIRONMENT
* AWX version: 1.0.4.114
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: RHEL7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create custom inventory script for source, when editing that source the machine credential will not show up in the credentials list

**Comment by wenottingham** [comment]
How are you expecting that to work... are you writing a script that calls SSH under the hood?

**Comment by matburt** [comment]
No response in 5 days, closing.

**Comment by mkempster22** [comment]
Hello, Apologies for the late replay, I've been on holiday.

Essentially yes, we're trying to get a list of our Solaris hosts dynamically by going to the physical hosts and using a script, this requires using ssh keys. The other way that we're using currently means running that script from the server that has the containers on it then putting it in a database then using the inventory script to get it from there but that isn't very clean.
The inventory script can run very well dynamically in one part except for we cant select the machine credential for it to use

Thanks

**Comment by ryanpetrello** [comment]
To @wenottingham's point:

> are you writing a script that calls SSH under the hood?

If the answer to this is "yes":

awx's inventory updates don't _currently_ support SSH authentication, but you might be able to implement something similar by using custom Credential Types:

https://docs.ansible.com/ansible-tower/latest/html/userguide/credential_types.html#create-a-new-credential-type

1.  Create a custom credential type that defines a field for the SSH private key data, and has two injectors e.g., (I have not tested this)

```json
{
  "inputs": {
    "fields": [
      {
        "type": "string",
        "id": "ssh_private_key",
        "label": "SSH Private Key",
        "secret": true,
      },
    ],
    "required": ["ssh_private_key"],
  },
  "injectors": {
    "file": {
      "template": "{{ ssh_private_key }}"
    },
    "env": {
      "MY_SSH_PRIVATE_KEY": "{{tower.filename}}"
    }
  }
}
```

2.  Add code to your custom inventory script that would call `ssh-add` to add the SSH key (defined in `environ['MY_SSH_PRIVATE_KEY']` to your running agent.

3.  Create a credential with the type `$YOUR_CUSTOM_CREDENTIAL_TYPE` and paste in your private key for the `ssh_private_key` field.  Assign this credential to the Inventory Source.

**Comment by mkempster22** [comment]
@ryanpetrello Thank you! I will try this method out and see how it goes

Is there a specific reason the normal machine credentials are filtered out of the ones you can use in custom inventories?

**Comment by ryanpetrello** [comment]
@mkempster22 mostly because there isn't any defined behavior for what a Machine/SSH credential _means/would do_ when used with an inventory script (hence @wenottingham's question https://github.com/ansible/awx/issues/1661#issuecomment-375826340).  Given that it's a _custom_ inventory script that's just some binary somewhere, we don't really have any way of knowing what the user's expectation is.
