### ISSUE TITLE
Using job tags in AWX

### ISSUE THREAD

**Issue by d-malko** [ansible/awx#1674]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME

 - UI

##### SUMMARY
Please help! I don`t know where to ask!
How to import tags from ansible roles into a tower? I add tags in the ansible roles. 
Checkin in pure Ansible:
`ansible-playbook -i stage rsyslog.yml --list-tags`
And I get list of all of my tags. 
`play # 1 (rsyslog): rsyslog TAGS: []  
 TASK TAGS: [rsyslog_config, rsyslog_install, update_firewall`
but there is not a single tag in the drop-down list of my AWX template. 

##### ENVIRONMENT
* AWX version: 1.0.4.14
* AWX install method: docker on linux
* Ansible version:  2.4.3.0 
* Operating System: debian 9
* Web Browser: Firefox, Chrome

**Comment by d-malko** [comment]
Sorry, my mistake! For some reason thought that the field is the same as playbook field in AWX templates.

**Comment by rsmoorthy** [comment]
@d-malko I have the exact same problem, however I don't understand why you closed the bug.

Do you mean that the "tags" in ansible is not the same as "JOB TAGS" in AWX?

As per this https://docs.ansible.com/ansible-tower/latest/html/userguide/job_templates.html (relevant section reproduced below), You should be able to specify the ansible playbook tags here -- but it is not allowing. I don't understand why you closed the issue. Just wanted to understand, before I create another issue.

> Job Tags:
> 
> Provide a comma-separated list of playbook tags to specify what parts of the playbooks should be executed.
> For more information and examples refer to Tags in the Ansible documentation.
> Prompt on Launch – If selected, even if a default value is supplied, you will be prompted upon launch to choose a job tag.

**Comment by jbidinger** [comment]
What happened with this? Did you guys figure it out?

**Comment by sandeepdharembra** [comment]
I have the same issue. Here is the playbook -

`---
- hosts: all
  remote_user: xxxx

  tasks:
    - name: pinging the hosts
      ping:
      tags: pinging
    - name: checking free memory
      command: free -m
      tags: [ 'mem', 'sys' ]
    - name: checking tmp disk space
      command: du -sh /home/nextag
      tags: [ 'disk', 'sys' ]`

and here is the command line output -

ansible-playbook test4.yml --list-tags

playbook: test4.yml

  play #1 (all): all	TAGS: []
      TASK TAGS: [disk, mem, pinging, sys]

The AWX job template does not show the tags

**Comment by sandeepdharembra** [comment]
Similar issues #2222 and #1182 

@d-malko, @rsmoorthy  Actually #1182 is a feature request for seeing a list of tags on UI and selecting one of those. The workaround option I was able to find was at https://github.com/ansible/awx/issues/2222#issuecomment-418396509 where you have to type the name of the tag manually and press enter
