### ISSUE TITLE
Initial Docker install fails

### ISSUE THREAD

**Issue by Anthonyjmartin** [ansible/awx#168]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
When performing docker install of AWX the ansible-playbook fails on the following:

TASK [image_build : Build AWX distribution] *************************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error creating container: 500 Server Error: Internal Server Error (\"invalid reference format\")"}

For fail message with -vvvv verbosity: https://pastebin.com/RcjnS5LC

I have done this on both OS X and Linux as root and nonroot.
##### ENVIRONMENT
* AWX version: 1.0.0
* Ansible version:  2.4.0
* Operating System: Antergos Linux
* Web Browser: Chrome

* AWX version: 1.0.0
* Ansible version:  2.3.2
* Operating System: OS X Sierra 10.12.6
* Web Browser: Chrome

##### STEPS TO REPRODUCE

With default config run ansible-playbook -i inventory install.yml

**Comment by matburt** [comment]
What version of docker are you using?

**Comment by Anthonyjmartin** [comment]
On the linux box Docker version 17.07.0-ce, build 87847530f7
on OSX Docker version 17.06.2-ce, build cec0b72

**Comment by matburt** [comment]
Can you show me the rest of the playbook run? It looks like your playbook run didn't pick up the tag from the scm checkout perhaps.

**Comment by Anthonyjmartin** [comment]
Here is the full output:
https://pastebin.com/JJ7mDtLU

**Comment by matburt** [comment]
Here's your problem:

```

    "cmd": "git describe --long | sed 's/\\-g.*//' | sed 's/\\-/\\./'",
    "delta": "0:00:00.038252",
    "end": "2017-09-14 18:00:02.018088",
    "invocation": {
        "module_args": {
            "_raw_params": "git describe --long | sed 's/\\-g.*//' | sed 's/\\-/\\./'",
            "_uses_shell": true,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "warn": true
        }
    },
    "rc": 0,
    "start": "2017-09-14 18:00:01.979836",
    "stderr": "fatal: Not a git repository (or any of the parent directories): .git",
    "stderr_lines": [
        "fatal: Not a git repository (or any of the parent directories): .git"
    ],
    "stdout": "",
    "stdout_lines": []
}
```

We take the version of the git tree and tag the image with it during the image build, since that doesn't exist for you it's not able to apply the right tag.

**Comment by matburt** [comment]
you want to make sure you are executing the installer from the install directory also, as per the INSTALL.md instructions.

**Comment by kavitaag** [comment]
I am facing the same issue. 

The only change I did was to comment "dockerhub_base" in inventory file. 

TASK [image_build : Build AWX distribution using container]
The full traceback is:
  File "/tmp/ansible_E8thoL/ansible_module_docker_container.py", line 1940, in container_create
    new_container = self.client.create_container(image, **create_parameters)
  File "/usr/lib/python2.6/site-packages/docker/api/container.py", line 135, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/lib/python2.6/site-packages/docker/api/container.py", line 146, in create_container_from_config
    return self._result(res, True)
  File "/usr/lib/python2.6/site-packages/docker/client.py", line 178, in _result
    self._raise_for_status(response)
  File "/usr/lib/python2.6/site-packages/docker/client.py", line 174, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)

fatal: [localhost -> localhost]: FAILED! => {
...}

"msg": "Error creating container: 500 Server Error: Internal Server Error (\"{\"message\":\"invalid reference format\"}\")"
