### ISSUE TITLE
Upgrading from 1.0.4 to 1.0.5 erases the whole admin configuration

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/awx#1680]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - memcached_1
- rabbitmq_1
- postgres_1

##### SUMMARY
Upgrading from 1.0.4 to 1.0.5 fails due to multiple errors..

##### ENVIRONMENT
* AWX version: tag 1.0.5
* AWX 1.0.4 install method: docker/docker-compose on linux
* Ansible version: v2.5.0 (from official ansible PPA)
* Operating System: Ubuntu 17.10
* docker-ce ```18.03.0~ce-0~ubuntu``` (from official docker PPA)
* docker==3.1.4
* docker-compose==1.20.1
* requests==2.18.1

##### STEPS TO REPRODUCE

```
git checkout 1.0.5
git checkout -b actionmystique_build
cd /var/lib/awx/docker-compose
sudo docker-compose pull && sudo docker-compose up --force-recreate

##### EXPECTED RESULTS
Correct upgrade to 1.0.5

##### ACTUAL RESULTS
```
```
Pulling memcached (memcached:alpine)...
alpine: Pulling from library/memcached
Digest: sha256:50512620d0101d6ba045caf623028b8ad99894382bf4e573c9879df194ecf054
Status: Image is up to date for memcached:alpine
Pulling postgres (postgres:9.6)...
9.6: Pulling from library/postgres
Digest: sha256:eda798e53a1a2684308c3d6408400c39e1431892e77d7d790d65d64a14467a43
Status: Image is up to date for postgres:9.6
Pulling rabbitmq (rabbitmq:3)...
3: Pulling from library/rabbitmq
Digest: sha256:90d77d4a710bb84378f4e929e67caf2d6d9e6f5485011cb1664537241bcdc0dd
Status: Image is up to date for rabbitmq:3
Pulling web (ansible/awx_web:latest)...
latest: Pulling from ansible/awx_web
5e35d10a3eba: Already exists
1bdeea372afe: Already exists
743d55e71777: Already exists
7e321be1c024: Pull complete
91aa004d5c03: Pull complete
ab3ef9b5f397: Pull complete
dbfc4d265748: Pull complete
3d9b3c4b7101: Pull complete
33ee86348fdb: Pull complete
2bfa512bf705: Pull complete
a7db869375d9: Pull complete
e0ba656cae52: Pull complete
cde16e2a5053: Pull complete
0ef96d3484f9: Pull complete
fb6fd7ced036: Pull complete
4b877738be1d: Pull complete
457787ab0b7a: Pull complete
56a3d31cad6d: Pull complete
e476a4346d41: Pull complete
57092fec3dec: Pull complete
c0fb45361a6d: Pull complete
a64016e325d2: Pull complete
04dc0c87ae8e: Pull complete
b24f0e626078: Pull complete
66d592bbdab6: Pull complete
10aee7db5a4e: Pull complete
ece210411bec: Pull complete
Digest: sha256:a289c62c6a02664ffe537e9e28bf35ae453ba27eff2c18cfa6433c6951bea713
Status: Downloaded newer image for ansible/awx_web:latest
Pulling task (ansible/awx_task:latest)...
latest: Pulling from ansible/awx_task
5e35d10a3eba: Already exists
1bdeea372afe: Already exists
743d55e71777: Already exists
7e321be1c024: Already exists
91aa004d5c03: Already exists
ab3ef9b5f397: Already exists
dbfc4d265748: Already exists
3d9b3c4b7101: Already exists
33ee86348fdb: Already exists
2bfa512bf705: Already exists
a7db869375d9: Already exists
e0ba656cae52: Already exists
cde16e2a5053: Already exists
0ef96d3484f9: Already exists
fb6fd7ced036: Already exists
4b877738be1d: Already exists
457787ab0b7a: Already exists
56a3d31cad6d: Already exists
e476a4346d41: Already exists
57092fec3dec: Already exists
c0fb45361a6d: Already exists
a64016e325d2: Already exists
04dc0c87ae8e: Already exists
b24f0e626078: Already exists
66d592bbdab6: Already exists
10aee7db5a4e: Already exists
ece210411bec: Already exists
043a3fd8c027: Pull complete
Digest: sha256:428552616ab5efb0e504d21bee67bb192e6f051bb9e7cce0cec23f74b3e8416b
Status: Downloaded newer image for ansible/awx_task:latest
Recreating dockercompose_rabbitmq_1  ... done
Recreating dockercompose_postgres_1  ... done
Recreating dockercompose_memcached_1 ... done
Recreating dockercompose_web_1       ... done
Recreating dockercompose_task_1      ... done
Attaching to dockercompose_memcached_1, dockercompose_rabbitmq_1, dockercompose_postgres_1, dockercompose_web_1, dockercompose_task_1
memcached_1  | /bin/sh: can't open '/usr/local/bin/docker-entrypoint.sh'
rabbitmq_1   | error: exec: "/usr/local/bin/docker-entrypoint.sh": stat /usr/local/bin/docker-entrypoint.sh: permission denied
postgres_1   | error: exec: "/usr/local/bin/docker-entrypoint.sh": stat /usr/local/bin/docker-entrypoint.sh: permission denied
task_1       | Using /etc/ansible/ansible.cfg as config file
dockercompose_rabbitmq_1 exited with code 1
dockercompose_postgres_1 exited with code 1
dockercompose_memcached_1 exited with code 2
...
```

**Comment by matburt** [comment]
Something looks to be a bit out of sorts on the memcached, rabbitmq, and postgres containers... @ewjoachim do you think you could take a look at this?

**Comment by shanemcd** [comment]
Can you try re-running the installer?

I'm not able to recreate on Fedora 27.

**Comment by ewjoachim** [comment]
(Sorry for the delay) Sure, I'll have a look asap :)

**Comment by jean-christophe-manciot** [comment]
@shanemcd  @ewjoachim 
I have rerun the 1.0.4 build && 1.0.5 upgrade by modifying 2 things:
- with a non-root user instead of root
- without modifying the ```postgres_data_dir``` in ```installer/inventory```

I have also modified the admin configuration in 1.0.4.

Now, the issue has mutated into a string of other non-blocking errors: 
- ```web_1        | django.db.utils.OperationalError: could not connect to server: Connection refused```: connection is tried too early
- ```postgres_1   | ERROR:  relation "conf_setting" does not exist at character 158```: cf issue [1618](https://github.com/ansible/awx/issues/1618)
- ```postgres_1   | ERROR:  relation "django_migrations" does not exist at character 124```: cf issue [1618](https://github.com/ansible/awx/issues/1618)
- ```web_1        | 2018-03-29 06:53:20,486 ERROR    Error trying to receive messages: [Errno 111] Connection refused```: probably not the right time again
- **the whole admin configuration made in 1.0.4 has been erased**: that's more damaging

Also, the default ```/tmp/pgdocker``` continues to be owned by an unknown user: cf issue [1695](https://github.com/ansible/awx/issues/1695).

The whole upgrade log is [here](https://github.com/ansible/awx/files/1858992/awx-upgrade-1.0.5.txt)
.

**Comment by ewjoachim** [comment]
> with a non-root user instead of root

Ah, I was just going to suggest this :)

Regarding `/tmp/pgdocker` belonging to 999, it's "normal" (as in, it's standard docker stuff, when using bind-mount volumes permissions are hell to set up)

Regarding "connection is tried too early", yes, the whole docker state could (IMHO) be largly improved by splitting to more atomic containers (uwsgi, daphne, nginx, celery, ...), getting rid of software that is "un-docker-ish" (supervisor, tiny, ...) setting up appropriate healthchecks, and using [wait-for-it](https://docs.docker.com/compose/startup-order/) or other similar software.

Regarding 'relation "conf_setting" does not exist', I'd bet this is a migration issue (does it happen both when running from a clean DB or from an existing DB ?)

Regading 'relation "django_migrations" does not exist', it could well be linked to the other error, but this one is a basic django table, so it's surprising that it's not found.

Seeing all these errors together, my **guess** would be: Are you sure you're hitting the right DB ?

**Comment by jean-christophe-manciot** [comment]
@ewjoachim 
> Regarding 'relation "conf_setting" does not exist', I'd bet this is a migration issue (does it happen both when running from a clean DB or from an existing DB ?)

when running from a clean DB

> Seeing all these errors together, my guess would be: Are you sure you're hitting the right DB ?
yes: I use the default one; 

During the 1.0.4 build & 1.0.5 upgrade processes, I made no other modifications to ```installer/inventory``` than:
- ```docker_compose_dir=/var/lib/awx/docker-compose```
- ```use_docker_compose=true```

**Comment by ewjoachim** [comment]
I'll need to try this locally and tell you :/

**Comment by ewjoachim** [comment]
Hm, still didn't have the time to tackle this... Sorry.

**Comment by matburt** [comment]
No follow up in several months.
