### ISSUE TITLE
Credential password prompts not always updated properly

### ISSUE THREAD

**Issue by aperigault** [ansible/awx#1681]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Only one credential is prompted if two fields are mark as "prompt at lauch" except if it is configured as default in job template.
This bug was already present in 1.0.4 version.
See STEPS TO REPRODUCE screen.

##### ENVIRONMENT
* AWX version: 1.0.5
* AWX install method: docker on linux
* Ansible version: 2.5.0
* Operating System: Debian 9.4
* Web Browser: Firefox/Chrome

##### STEPS TO REPRODUCE
![peek 2018-03-27 15-23](https://user-images.githubusercontent.com/5754674/37970255-4ad80f84-31d3-11e8-8452-cc6b2fef1255.gif)

**Comment by mabashian** [comment]
Steps to reproduce:

1) Create a Machine credential where Password prompt on launch is checked
2) Create a Machine credential where Password prompt on launch and Privilege Escalation Password prompt are both checked
3) Create a Job Template and select the credential from step 1 as the default Machine cred.  Also select PROMPT ON LAUNCH for credentials
4) Launch the job template
5) The password fields should be displayed properly:

<img width="763" alt="screen shot 2018-03-27 at 2 57 36 pm" src="https://user-images.githubusercontent.com/9889020/37988564-3799e180-31cf-11e8-968b-4a1e93e4a422.png">

6) Select the second credential:

<img width="778" alt="screen shot 2018-03-27 at 2 58 08 pm" src="https://user-images.githubusercontent.com/9889020/37988597-4ed72ea2-31cf-11e8-991d-9c882400f531.png">

Password fields are not updated properly, there should be a password field and a privilege escalation password field.

**Comment by aperigault** [comment]
Anybody can look at this ?
It's a major bug !

**Comment by ryanpetrello** [comment]
@aperigault mind giving this another shot?  It should be resolved via https://github.com/ansible/awx/commit/a6dd7dbf070c7c57f5cb38dd6d6df2a239475c2e

**Comment by aperigault** [comment]
Problem solved in 1.6.1.
Thanks
