### ISSUE TITLE
Host Variable Data endpoint deprecated without alternative

### ISSUE THREAD

**Issue by BenJuan26** [ansible/awx#1682]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME
 - API

##### SUMMARY
The Host Variable Data endpoint at `/api/v1/hosts/<host_number>/variable_data/` is listed as deprecated, but there is no listed alternative. Once it is deprecated, how can host variables be set/updated from the API?

##### ENVIRONMENT
* AWX version: 3.2.0
* AWX install method: docker on linux
* Ansible version:  2.4.3
* Operating System: Ubuntu 16.04
* Web Browser: Google Chrome on macOS

**Comment by AlanCoding** [comment]
> Once it is deprecated, how can host variables be set/updated from the API?

PATCH `/api/v2/hosts/N/`

```json
{"variables": "foo: bar"}
```

**Comment by natman** [comment]
It is impossible to host filter variables from this endpoint:
filter `variables.os_type.icontains:rhel` retuns anything while
           ` "variables": "os_type: rhel_8x64"` because variable type is a string and not a dict
`variables.icontains:rhel` returns some hosts, but this is not what I was expecting.
