### ISSUE TITLE
Results Page not properly displaying output on 1.0.5.0/11

### ISSUE THREAD

**Issue by sentania** [ansible/awx#1687]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
The Results page for a job provides no standard output and fields in the results Column appear to be unresolved variable names

##### ENVIRONMENT
* AWX version: 1.0.5.11 (and 1.0.5.0)
* AWX install method:  docker on linux
* Ansible version:  2.5.0
* Operating System: CentOS 7.4
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Perform a standard install of awx, create an SCM project or job template, and execute that project.

##### EXPECTED RESULTS

The job runs, and provides about the execution in the Results column, and standard output in the standard output column

##### ACTUAL RESULTS

The standard output column is blank, and the results column appear to have unresolved variable names.

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/2688043/37977769-13001030-31aa-11e8-8d32-c19675f80e7e.png)

**Comment by jakemcdermott** [comment]
<img width="1414" alt="screen shot 2018-03-27 at 12 21 53 pm" src="https://user-images.githubusercontent.com/9753817/37980596-766cf91c-31b9-11e8-8db2-27a66e351928.png">

**Comment by sentania** [comment]
This appears to apply to inventory updates as well, but standard job templates appear to be unaffected:
![image](https://user-images.githubusercontent.com/2688043/37981573-a7ba1776-31b3-11e8-881a-04f53eb96bd7.png)

![image](https://user-images.githubusercontent.com/2688043/37981664-e77d3104-31b3-11e8-9aa3-ee67ad9c354b.png)

**Comment by OsirisS13** [comment]
Can confirm I'm seeing this in SCM update as well, seems to be the same problem as https://github.com/ansible/awx/issues/1692
