### ISSUE TITLE
Vault Issue on AWX 1.0.4.130  version

### ISSUE THREAD

**Issue by Chennait06** [ansible/awx#1694]
ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY
I have created template and pointed one of my playbook which is vault encrypted ,  

Created new credential with following details:

Credential type : Vault
Vault Password  : password given at the time of creating vault file
Vault Identifier  : Vault file name

Mapped this user to template.

But playbook fails

##### ENVIRONMENT
* AWX version: 1.0.4.130
* AWX install method: docker on Linux
* Ansible version:  2.5.0
* Operating System: Centos 
* Web Browser: IE

##### STEPS TO REPRODUCE

I have created template and pointed one of my playbook which is vault encrypted ,  

Created new credential with following details:

Credential type : Vault
Vault Password  : password given at the time of creating vault file
Vault Identifier  : Vault file name

Mapped this user to template.

##### EXPECTED RESULTS

Playbook should run successfully 

##### ACTUAL RESULTS

Found a vault_id (default) in the vault text, but we do not have a associated secret (--vault-id)
Trying to use vault secret=(<ansible.parsing.vault.PromptVaultSecret object at 0x1c630d0>) id=db2_vault to decrypt None
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x1c630d0> for vault_id=db2_vault
Tried to use the vault secret (db2_vault) to decrypt (None) but it failed. Error: HMAC verification failed: Signature did not match digest.

**Comment by AlanCoding** [comment]
The vault identifier doesn't have anything to do with the filename for the vault content. We need more information about the credential you created, and about how you included your vault secrets in source control. For the credential, either a UI screenshot or the payload sent to the API would give us something to work off of.

**Comment by ryanpetrello** [comment]
Please re-open if you've got some more details to share.
