### ISSUE TITLE
/tmp/pgdocker/pgdata is owned by an unknown user "999"

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/awx#1695]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- postgres_1

##### SUMMARY
Running the installer from scratch as a **non-root user** creates by default a ```/tmp/pgdocker/pgdata``` folder which is owned by an unknown ```999``` user and the permissions are limited to that user.

##### ENVIRONMENT
* AWX version: tag 1.0.5
* AWX 1.0.4 install method: docker/docker-compose on linux
* Ansible version: v2.5.0 (from official ansible PPA)
* Operating System: Ubuntu 17.10
* docker-ce ```18.03.0~ce-0~ubuntu``` (from official docker PPA)
* docker==3.1.4
* docker-compose==1.20.1
* requests==2.18.1
* ```use_docker_compose=true``` in installer/inventory

##### STEPS TO REPRODUCE

```
$ docker ps --all
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                NAMES
$
$ git checkout 1.0.5
$ git checkout -b actionmystique_build
$ cd installer
$ ansible-playbook -i inventory install.yml
```

##### EXPECTED RESULTS
Correct installation of 1.0.5

##### ACTUAL RESULTS
```
# ll /tmp/pgdocker/pgdata/
total 128
drwx------ 19  999 root    4096 Mar 28 12:18 ./
drwxr-xr-x  3 root root    4096 Mar 28 12:18 ../
drwx------  6  999 docker  4096 Mar 28 12:18 base/
drwx------  2  999 docker  4096 Mar 28 12:23 global/
drwx------  2  999 docker  4096 Mar 28 12:18 pg_clog/
drwx------  2  999 docker  4096 Mar 28 12:18 pg_commit_ts/
drwx------  2  999 docker  4096 Mar 28 12:18 pg_dynshmem/
-rw-------  1  999 docker  4490 Mar 28 12:18 pg_hba.conf
-rw-------  1  999 docker  1636 Mar 28 12:18 pg_ident.conf
drwx------  4  999 docker  4096 Mar 28 12:18 pg_logical/
drwx------  4  999 docker  4096 Mar 28 12:18 pg_multixact/
drwx------  2  999 docker  4096 Mar 28 12:18 pg_notify/
drwx------  2  999 docker  4096 Mar 28 12:18 pg_replslot/
drwx------  2  999 docker  4096 Mar 28 12:18 pg_serial/
drwx------  2  999 docker  4096 Mar 28 12:18 pg_snapshots/
drwx------  2  999 docker  4096 Mar 28 12:18 pg_stat/
drwx------  2  999 docker  4096 Mar 28 12:34 pg_stat_tmp/
drwx------  2  999 docker  4096 Mar 28 12:18 pg_subtrans/
drwx------  2  999 docker  4096 Mar 28 12:18 pg_tblspc/
drwx------  2  999 docker  4096 Mar 28 12:18 pg_twophase/
-rw-------  1  999 docker     4 Mar 28 12:18 PG_VERSION
drwx------  3  999 docker  4096 Mar 28 12:26 pg_xlog/
-rw-------  1  999 docker    88 Mar 28 12:18 postgresql.auto.conf
-rw-------  1  999 docker 22266 Mar 28 12:18 postgresql.conf
-rw-------  1  999 docker    37 Mar 28 12:18 postmaster.opts
-rw-------  1  999 docker    92 Mar 28 12:18 postmaster.pid
# cat  /etc/passwd | grep 999
#
```

**Comment by jean-christophe-manciot** [comment]
I have noticed that this alien 999 UID happens to be my UID minus 1.

**Comment by matburt** [comment]
Sooo... what's the problem? This is likely just happening through user mappings within the actual docker postgres container, see: https://github.com/docker-library/postgres/blob/7f18547f3779e8593e2bb35f21eba5baadc47290/9.6/Dockerfile#L15

If this doesn't work for you then you'll need to set up an external postgres server.

**Comment by jean-christophe-manciot** [comment]
@matburt 
I've discovered afterwards that the issue happens during the build process run as a non-root user when modifying ```postgres_data_dir``` in ```installer/inventory```: **if the new target folder is not world-writable, then the postgres container fails completely**. This "detail" is not mentioned anywhere in the [official install doc](https://github.com/ansible/awx/blob/devel/INSTALL.md#docker-or-docker-compose).

**Comment by jean-christophe-manciot** [comment]
Also, I have one comment about the postgres docker container you're using:
it's based on a very old image ```debian:jessie```. Many people consider -for good reasons - debian stable -currently stretch - as prehistoric  How would consider a version which is 2 years older?

**Comment by matburt** [comment]
We're just using the default docker library container for dockerhub... you can take that up with them if you need it a newer version or.... install and configure your own postgres service.

**Comment by andrewsav-bt** [comment]
I just came across this issue today, almost 2 years later. It indeed does not work when run as non-root user, as described in the OP, and it is indeed still not mentioned in the documentation.
