### ISSUE TITLE
sidebar looks wrong on firefox

### ISSUE THREAD

**Issue by changsijay** [ansible/awx#1696]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
the side bar width is wrong as below
![screen shot 2018-03-28 at 6 13 07 pm](https://user-images.githubusercontent.com/245306/38025760-b908bf68-32b3-11e8-85b2-3577e324e219.png)

##### ENVIRONMENT
* AWX version: 1.0.5
* AWX install method: docker
* Ansible version:  2.5.0
* Operating System: CentOS 7
* Web Browser: firefox 60.0b7 (64-bit)

##### EXPECTED RESULTS

There should not have horizontal scroll bar

**Comment by jaredevantabor** [comment]
linking to #590

**Comment by ryanpetrello** [comment]
@changsijay this issue should be resolve now.  Mind giving it another try?
