### ISSUE TITLE
AWX slack notification fails 

### ISSUE THREAD

**Issue by mkrish004c** [ansible/awx#1698]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY
The slack client fix for larger workspace (probably more than 10K members) has to be incorporated in awx backend code. It fails to deliver the slack notification with in the defined time out,  throws error on the GUI "
Call to test notifications failed." and the notification left undelivered inconsistently.

Fix on the slackclient
https://github.com/slackapi/python-slackclient/blob/master/slackclient/client.py#L42

to be made, 
https://github.com/ansible/awx/blob/1.0.5/awx/main/notifications/slack_backend.py#L35

##### ENVIRONMENT
* AWX version: 1.0 (corrected)
* AWX install method: RH Community ansible script on RHEL 7.3 machine
* Ansible version:  2.4.0.0
* Operating System: Windows 10
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Bot & channel on a Workspace with 10K member or more
Test notification from Tower

##### EXPECTED RESULTS

Test notification must be delivered successfully 

##### ACTUAL RESULTS

`Call to test notifications failed.`

**Comment by jaredevantabor** [comment]
`AWX version: 3.2.1` is not a version of AWX. If you are using Tower  I would recommend you reach out to your support representative.

**Comment by mkrish004c** [comment]
yes, i checked with the RH and slack support team, we suspect that the slack notification backend has to modified to adopt this limitation, slack has the know caveat that `rtm.connect` is a lighter version and only this works normal on the larger workspace (more than 10K members). 

[slack client note](https://github.com/slackapi/python-slackclient/blob/master/slackclient/client.py#L42)

Note - Tower works normal with the smaller slack workspace.

**Comment by mkrish004c** [comment]
Corrected AWX version to 1.0
