### ISSUE TITLE
Job results pane shows no results and only unfilled angular keys, Console shows angular error

### ISSUE THREAD

**Issue by wcom939** [ansible/awx#1700]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

On a fresh install, when running a command, there is no output on successful or unsuccessful commands,

##### ENVIRONMENT
* AWX version: 1.0.5
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: Centos 7 x64
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. install a fresh CENTOS 7 minimal, 
2. disable selinux, firewall and run yum update and yum install net-tools
yum install epel-release
yum install git gettext ansible docker nodejs npm gcc-c++ bzip2 python-docker-py
systemctl start docker
systemctl enable docker
git clone https://github.com/ansible/awx.git
cd awx
git checkout 1.0.5
cd installer/
ansible-playbook -i inventory install.yml

wait for install to finish.

3. open browser towards IP
4. go into inventory, attempt to run a command against localhost, select ping

##### EXPECTED RESULTS

The angular data in the job detail pane should be filled.

##### ACTUAL RESULTS
job details show unfilled angular keys under results, and no sysout, F12 Console shows an error:

vendor.a01e7d1898d8d762113c.js:71 Error: [$injector:unpr] Unknown provider: DeleteJobProvider <- DeleteJob <- JobStdoutController
http://errors.angularjs.org/1.6.9/$injector/unpr?p0=DeleteJobProvider%20%3C-%20DeleteJob%20%3C-%20JobStdoutController
    at vendor.a01e7d1898d8d762113c.js:71
    at vendor.a01e7d1898d8d762113c.js:71
    at Object.getService [as get] (vendor.a01e7d1898d8d762113c.js:71)
    at vendor.a01e7d1898d8d762113c.js:71
    at getService (vendor.a01e7d1898d8d762113c.js:71)
    at injectionArgs (vendor.a01e7d1898d8d762113c.js:71)
    at Object.instantiate (vendor.a01e7d1898d8d762113c.js:71)
    at vendor.a01e7d1898d8d762113c.js:71
    at Object.<anonymous> (vendor.a01e7d1898d8d762113c.js:616)
    at vendor.a01e7d1898d8d762113c.js:71 "<div class="col-lg-12 ng-scope" ui-view="">"

![image](https://user-images.githubusercontent.com/16446451/38043014-db5fe4e0-3283-11e8-8667-433c141b05b7.png)

**Comment by jaredevantabor** [comment]
This should be fixed with #1691
