### ISSUE TITLE
Warning: Failure using method (v2_playbook_on_notify) in callback plugin

### ISSUE THREAD

**Issue by anlutro** [ansible/awx#1705]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- UI (not sure)

##### SUMMARY
Running a playbook and following the output live, one of the tasks generated this warning:

```
TASK [fail2ban : manage fail2ban/jail.local] ***********************************13:26:00
 [WARNING]: Failure using method (v2_playbook_on_notify) in callback plugin
(<awx_display_callback.module.AWXDefaultCallbackModule object at 0x214de50>):
'Handler' object has no attribute '_host'
```

This is the task, I don't know what's special about it to cause this warning - everything other task ran fine.

```
- name: manage fail2ban/jail.local
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: reload fail2ban
```

##### ENVIRONMENT
* AWX version: AWX 1.0.5.13
* AWX install method: docker on linux
* Ansible version:  2.5.0
* Operating System: Debian Stretch
* Web Browser: Chromium

**Comment by ryanpetrello** [comment]
@anlutro thanks for reporting this!

It looks like the `v2_on_playbook_notify` function was actually **never called** prior to Ansible 2.5 (this was fixed in https://github.com/ansible/ansible/pull/32633).  It also looks like our current implementation of `v2_on_playbook_notify` is _wrong_, because it was copied from the upstream callback plugin reference implementation years ago (which was _also_ wrong: https://github.com/ansible/ansible/pull/35664)

## 2.5.0
```python
> /awx_devel/awx/lib/awx_display_callback/module.py(284)v2_playbook_on_notify()
-> event_data = dict(
(Pdb) import ansible
(Pdb) ansible.__version__
'2.5.0'
(Pdb) l
279  	            super(BaseCallbackModule, self).v2_playbook_on_no_hosts_remaining()
280
281  	    def v2_playbook_on_notify(self, result, handler):
282  	        # NOTE: Not used by Ansible 2.x.
283  	        import pdb; pdb.set_trace()
284  ->	        event_data = dict(
285  	            host=result._host.get_name(),
286  	            task=result._task,
287  	            handler=handler,
288  	        )
289  	        with self.capture_event_data('playbook_on_notify', **event_data):
(Pdb) result._host
*** AttributeError: 'Handler' object has no attribute '_host'
```

**Comment by kladiv** [comment]
+1

**Comment by sysblade** [comment]
Same issue, this makes impossible to call any handlers apparently ?

**Comment by ryanpetrello** [comment]
This should be resolved now via https://github.com/ansible/awx/commit/f8c40cc26f353fda76577afdeee64cdb99b21f96
