### ISSUE TITLE
Ansible version selection

### ISSUE THREAD

**Issue by shen3lu4** [ansible/awx#1706]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME

 - Installer

##### SUMMARY

Currently the Ansible version in the AWX is 2.4.3.0. Is there a way to choose a different version like 2.5 during installation? I am not able to find any documentation about setting the Ansible version. 

##### ENVIRONMENT
* AWX version: 1.0.4.109
* AWX install method: Kubernetes
* Ansible version:  2.4.3.0
* Operating System: Oracle Linux 7.4
* Web Browser: Chrome

**Comment by ryanpetrello** [comment]
Hey @shen3lu4 - check out this new feature recently added to awx:  https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md
