### ISSUE TITLE
yaml error in file docker-compose.yml when setting awx_alternate_dns_servers in inventory

### ISSUE THREAD

**Issue by christopheduchenoy** [ansible/awx#1710]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
"Configuration error - yaml.parser.ParserError" when variable "awx_alternate_dns_servers" is set

##### ENVIRONMENT
* AWX version: 1.0.5
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: SLES 12 SP 3
* Web Browser: any

##### STEPS TO REPRODUCE
Modifications made in inventory file : 
use_docker_compose=true
awx_official=true
awx_alternate_dns_servers="8.8.8.8"

##### EXPECTED RESULTS
In docker-compose.yml file, line for dns should be : (replace _ by a space character)
_____dns: "8.8.8.8"

##### ACTUAL RESULTS
The line is in column 1.
dns: "8.8.8.8" 

##### ADDITIONAL INFORMATION
Issue reproduced with Ubuntu 16.04.4

**Comment by ryanpetrello** [comment]
@christopheduchenoy can you share the generated `docker-compose.yml` file?  It might help us debug.

**Comment by christopheduchenoy** [comment]
# file docker-compose.yml (anonymized) : 
http://bit.ly/2Hfj0bx

**Comment by ryanpetrello** [comment]
@christopheduchenoy Sorry, any chance you could paste it in a preformatted block in the comment?  I think Github is eating up spaces in your paste (which matter):

```
    ```yaml
    pre-formatted pasted text
    goes here
    ```
```

**Comment by christopheduchenoy** [comment]
I have uploaded the file in paste.org and modified the previous comment ;)

**Comment by ryanpetrello** [comment]
Okay I see what you're saying now - it looks like that `dns` key isn't being properly indented when we generate it.

**Comment by ryanpetrello** [comment]
Hey @christopheduchenoy, a change has been merged which should address this.  Thanks for reporting this.

**Comment by challenger90** [comment]
It's very good ! thx
