### ISSUE TITLE
RFE: Add 'doas' in the drop down list of privilege escalation methods in Credential. 

### ISSUE THREAD

**Issue by IshwarKanse** [ansible/awx#1712]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### ENVIRONMENT

* Ansible Tower / AWX latest release

##### SUMMARY
Currently 'doas' is missing in the drop down list of privilege escalation methods in credential. Since the method is already supported in core. It can be also added in AWX.

##### ACTUAL RESULTS
![screenshot from 2018-03-31 08-40-34](https://user-images.githubusercontent.com/10349173/38159088-6198a802-34bf-11e8-8269-7ce85b2d480f.png)

**Comment by matburt** [comment]
Should just need to add it here: https://github.com/ansible/awx/blob/devel/awx/main/constants.py#L16-L18

**Comment by matburt** [comment]
Potential unit tests here: https://github.com/ansible/awx/blob/devel/awx/main/tests/functional/test_credential.py

**Comment by ryanpetrello** [comment]
This will be resolved soon via a downstream change.
