### ISSUE TITLE
AWX 1.0.5 Not able to save LDAP config

### ISSUE THREAD

**Issue by tjyang** [ansible/awx#1713]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Not able to save LDAP configuration

##### ENVIRONMENT
* [About ScreenShot](https://user-images.githubusercontent.com/378638/38162388-f9b2527e-34a5-11e8-9e71-7fb6540e21dc.png)

* AWX version: 1.0.5
* AWX install method: rpm install from https://github.com/MrMEEE/awx-build/blob/master/installguide
* Ansible version:  2.4.3
* Operating System: CentOS 7.4
* Web Browser: Chrome latest.

##### STEPS TO REPRODUCE

* From a fresh install of AWX pre-built RPMs from following.
  * https://github.com/MrMEEE/awx-build/blob/master/installguide
* login as admin/password
* Setting -> select LDAP from pull-down menu.
* Enter all the needed LDAP server info.
* Click and Save button and Save action was OK.

##### EXPECTED RESULTS

AWX keep the setting after logout from admin and login again.

##### ACTUAL RESULTS

AWX didn't keep the previous LDAP config setting.

##### ADDITIONAL INFORMATION

* Same procedure works on AWX 1.0.2 using above install and LDAP config procedure.

**Comment by jakemcdermott** [comment]
👋 
Hello tjyang. Thanks for reaching out. The steps to reproduce you provided use an installation method that we do not support, so I'm closing this issue.

Please feel free to stop by the official awx mailing list or our irc channel on freenode if you have any questions.

**Comment by tjyang** [comment]
Just for the record.
https://github.com/ansible/awx/issues/1040 could be the fix, I haven't tried yet.
