### ISSUE TITLE
401 Authentication credentials were not provided.

### ISSUE THREAD

**Issue by raghavs1108** [ansible/awx#1714]
Issue:  - Documentation
Component Name: API

Summary: 

ENVIRONMENT: 
AWX Version: 1.0.5.19
AWX Install Method: Docker on linux
Ansible version: 2.5.0
OS: Centos 7
Request Source: POSTMAN

STEPS TO REPRODUCE:
1. Fire a request from Postman to the awx server, requesting a job template: http://server-ip/api/v2/job_templates/8/launch/

EXPECTED RESULTS: template details
ACTUAL RESULTS
403 Forbidden: 
{
    "detail": "Authentication credentials were not provided."
}

ISSUE DESCRIPTION:
Please provide the headers/parameters that need to be passed with the API, to make an authorised request. 
Please also elaborate on how to obtain the needed credentials that should be passed. (such as auth token, etc)

**Comment by matburt** [comment]
Please refrain from using the AWX issue tracker to seek help in how to do something. Instead use our mailing list or IRC channel.
