### ISSUE TITLE
[RFE] Please enable language switcher at login page

### ISSUE THREAD

**Issue by sshedmake** [ansible/awx#1715]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

Language switcher is currently missing from login page. Adding it could offer better UX, while using localized interface of AWX in preferred LANG (say:  ja, fr, es, nl).

##### ENVIRONMENT
* AWX version: 1.0.5
* AWX install method: docker on linux
* Ansible version:  ansible-2.4.3.0-1
* Operating System: Fedora 27
* Web Browser: google-chrome

##### STEPS TO REPRODUCE

Visit AWX login page

##### EXPECTED RESULTS

Language switcher is enabled (to start using localized interface in preferred LANG)

##### ACTUAL RESULTS
Language switcher missing (need some way to use localized interface in preferred LANG)

##### ADDITIONAL INFORMATION

Example from oVirt (open source project) - http://jensd.be/wp-content/uploads/ovirt-login.png

**Comment by wenottingham** [comment]
This is done by the browser locale.
