### ISSUE TITLE
RFE: Allow Teams to be assigned to Organization roles.

### ISSUE THREAD

**Issue by wwitzel3** [ansible/awx#1717]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY
Allow the assignment of some Organization roles to Teams.

##### ADDITIONAL INFORMATION
Currently you cannot assign a Team any Organization level roles, this is due to nature of how role assignments are implemented and how parent/children hieachies are caclutated. With the addition of the new focused admin roles for Organization resources it might be nice to revisit the idea of allowing a Team to belong to Organization level roles.

**Comment by wenottingham** [comment]
this landed
