### ISSUE TITLE
Ubuntu `do-release-upgrade -d` to new LTS wiped database to defaults

### ISSUE THREAD

**Issue by shaneholloman** [ansible/awx#1719]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Updating from Ubuntu 16.04 to 18.04 reset the entire AWX environment to fresh default settings
Wiped all inventories/groups/organizations etc
Reset users to the initial install

##### ENVIRONMENT
* AWX version: 1.04
* AWX install method: docker on linux, 
* Ansible version:  2.5
* Operating System: Ubuntu 18.04
* Web Browser: All

##### STEPS TO REPRODUCE

`do-release-upgrade -d`

##### EXPECTED RESULTS
Database not wiped to defaults

##### ACTUAL RESULTS
Database was reset to defaults

**Comment by wenottingham** [comment]
Did you set up persistent storage for your database container?

**Comment by shaneholloman** [comment]
@wenottingham No I did not. I perhaps foolishly assumed the installer made my storage persistent by default since this is the type of data most would not want to lose

Cheers for the heads up. I will be more careful for my next installation and check for that option
