### ISSUE TITLE
Review Project and Inventory Sync in Workflow template versus Project & Inventory source "Update on Launch"

### ISSUE THREAD

**Issue by khelkun** [ansible/awx#1728]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
I use the "Update Revision on Launch" on my Project configuration so a Job Template, using a playbook of this Project, updates the Project revision before the job is launched.
However I use Job Templates in Workflow Templates. So if I use 3 Job Templates (that use distinct playbooks of the same Project) in the same Workflow Template then the Project revision gets updated 3 times: one time before the execution of each jobs. I'm not sure this suggestion is relevant but here is what I would expect:
- keep the auto update of the Project revision when the Job template is launched independently, through the "Update Revision on Launch" of the Project configuration
- keep the auto update of the Project revision when the Job template is launched inside a Workflow Template, by letting the user able to add a "Project Sync" node in the Worflow Template **but avoid a repetition of the project revision update for each job in the workflow**.

The bold part is the actual feature I would like to have.

##### ENVIRONMENT
* AWX version: 1.0.4.124
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: Ubuntu 17.10
* Web Browser: Google Chrome 65.0.3325.181

##### ADDITIONAL INFORMATION
I guess the same observation could be made for the "Update on Launch" of a Source inside an Inventory against the "INVENTORY SYNC" node of a Workflow Template but I've never used Inventory sources so far.

**Comment by wenottingham** [comment]
This is what cache_timeout is for. Please see the documentation.

**Comment by khelkun** [comment]
@wenottingham indeed thanks, I didn't consider Project cache timeout could do the trick.
However, for the Project "Update revision on launch" to occur only at the start of the workflow (using PROJECT SYNC node), I guess that the cache timeout of the project has to be superior to the maximum execution time of the whole workflow minus the the maximum execution time of the last job.
Still considering the fact that I want to use the Job template in Workflow and outside of a Workflow, so I do want to keep Project "Update revision on launch" enabled.

**Comment by wenottingham** [comment]
Correct... that being said, this isn't a bug/software issue. This is best targeted at the mailing list/IRC channel.

**Comment by khelkun** [comment]
ok I'll check in IRC or the mailing list before posting a feature request
