### ISSUE TITLE
Job log should be clearer about censored output via no_log

### ISSUE THREAD

**Issue by alexander-bauer** [ansible/awx#1729]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
Currently, when an Ansible task specifies `no_log`, the summary output in AWX is not as explicit about this as it should be. Particularly with tasks with multiple items, we see output like
```
TASK [foreman_proxy : Slurp cert content for installation on the proxy] ********
14:16:04
ok: [foreman-sp.<domain>] => (item=None)
ok: [foreman-sp.<domain>] => (item=None)
ok: [foreman-sp.<domain>] => (item=None)
```
When clicked, it explains as follows:
```
{
    "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"
}
```

It would be clearer if the summary log added `<CENSORED>` or a similar marker for identifying at a glance why there is no information in the log.

##### ENVIRONMENT
* AWX version: 1.0.2.75
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: Mac
* Web Browser: Firefox

**Comment by wenottingham** [comment]
This is just duplicating the message that comes from Ansible; we would not change this in AWX.
