### ISSUE TITLE
Feature:  REPLACE supervisor

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#173]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY

Right now, we pull supervisor at build time from the repo for the OS that we're building on/for.
supervisor is pure python and we can pull it into our requirements system.
This will involve building init scripts and other ancillary things.

Getting this done will include getting the following items checked:

- [ ] Find a replacement for supervisor
- [ ] Update sosreport to gather information based on the replacement
- [ ] Update installation scripts to install the replacement and not install supervisor

**Comment by wenottingham** [comment]
Alternatively... we're not using supervisor in container installs. We could move away from it entirely for non-container in favor of systemd units.

**Comment by ryanpetrello** [comment]
We _are_ using supervisor in container installs:

https://github.com/ansible/awx/blob/devel/installer/roles/image_build/files/supervisor.conf
https://github.com/ansible/awx/blob/devel/installer/roles/image_build/files/supervisor_task.conf

![image](https://user-images.githubusercontent.com/214912/43654321-da1c3ddc-9718-11e8-8de3-4fe2da1854a9.png)


![image](https://user-images.githubusercontent.com/214912/43654285-ba0a4e9e-9718-11e8-9c7a-edf8681533a4.png)

**Comment by wwitzel3** [comment]
https://circus.readthedocs.io/en/latest/

**Comment by wenottingham** [comment]
... also apparently supervisor 4.0 may be a thing in the future.

**Comment by ryanpetrello** [comment]
I'm currently testing, but there's a lot of evidence that suggests that `supervisor==4.0.0.dev` _just works_ in py3 for our purposes.  At least, I've got one building and passing tests:

```shell
# service supervisord status | grep python
Redirecting to /bin/systemctl status supervisord.service
           ├─15017 /usr/bin/python3 /usr/bin/supervisord -c /etc/supervisord.conf
           ├─15020 python /usr/bin/failure-event-handler
           ├─15021 python /usr/bin/awx-manage run_dispatcher
           ├─15022 python /usr/bin/awx-manage run_callback_receiver
           ├─15023 python /usr/bin/awx-manage runworker --only-channels websocket.*
           ├─15025 /var/lib/awx/venv/awx/bin/python /var/lib/awx/venv/awx/bin/daphne -b 127.0.0.1 -p 8051 awx.asgi:channel_layer

# supervisorctl
exit-event-listener                     RUNNING   pid 23713, uptime 0:04:54
tower-processes:awx-callback-receiver   RUNNING   pid 23715, uptime 0:04:54
tower-processes:awx-channels-worker     RUNNING   pid 24505, uptime 0:03:47
tower-processes:awx-daphne              RUNNING   pid 23718, uptime 0:04:54
tower-processes:awx-dispatcher          RUNNING   pid 23714, uptime 0:04:54
tower-processes:awx-uwsgi               RUNNING   pid 23717, uptime 0:04:54

# curl -ks "https://localhost:443/api/v2/ping/"  | python -m json.tool | grep capacity
            "capacity": 54,
            "capacity": 54,
```

**Comment by ryanpetrello** [comment]
Looks like there's a lot of people who are also having good luck with supervisor in py3 here:

https://github.com/Supervisor/supervisor/issues/1060

I can't say I understand why they haven't just released a `4.0.0dev` to PyPI at this point, though.

**Comment by ryanpetrello** [comment]
Okay, on a first pass, integration results look promising w/ supervisor on py3.  This issue title + description is somewhat inaccurate now - our plan _going forward_ is to just run supervisor under python3 on distributions that don't provide a python2 and test/verify stability in those environments.

**Comment by mnaberez** [comment]
So it is not missed here, this is what I replied on https://github.com/Supervisor/supervisor/issues/1060#issuecomment-457401493:

> Please do not ship production software using an unstable version of Supervisor (git sha or otherwise). If it was suitable to be used with production software, it would be released as a stable version. I think we are close but we are not there yet. There are a number of alternative programs that do what Supervisor does. If you cannot use a stable version of Supervisor, I would recommend choosing an alternative rather than risk a production environment on an unstable version.

**Comment by ryanpetrello** [comment]
It looks like there's a good chance a supervisor `4.0.0` (or `4.0.0rc`) will land in the next few weeks with official Python3 support:

https://github.com/Supervisor/supervisor/issues/1060#issuecomment-475972528

So our intention at this point is to *not* replace our usage of supervisor.

**Comment by mnaberez** [comment]
[Supervisor 4.0.0](https://pypi.org/project/supervisor/) (PyPI package; supports Python 3.4+ and 2.7)
