### ISSUE TITLE
Editable Slack Notification Template

### ISSUE THREAD

**Issue by parinapatel** [ansible/awx#1730]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

Currently Slack notification just contain Ansible Template name ,job id and information regarding job result. I would like an ability to manipulate slack message or notification .
We just have single template which can run thing according to variables and I would really like to get information regarding those variables in my slack message.

**Comment by wenottingham** [comment]
see #79
