### ISSUE TITLE
Cant update any SCM

### ISSUE THREAD

**Issue by MansM** [ansible/awx#1733]
Might be duplicate of: https://github.com/ansible/awx/issues/1582 but that one mentioned it should already be fixed (and is in different step)
```
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: Unable to set correct type for configuration entry:
DEFAULT_LOCAL_TMP


PLAY [all] *********************************************************************


TASK [delete project directory before update] **********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 13] Permission denied: '~'
fatal: [localhost]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   

```
unfortunately I cant add some v's to the scm job

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
UI ( I guess...)

##### SUMMARY
Cant update any git repo

##### ENVIRONMENT
* AWX version: 1.0.5.20 (2018-04-05)
* AWX install method: openshift
* Ansible version:  
* Operating System: rhel 7.4
* Web Browser: chrome

##### STEPS TO REPRODUCE

add credentials and git repo (inventory)
##### EXPECTED RESULTS

getting the project to load

##### ACTUAL RESULTS

no git import

**Comment by wenottingham** [comment]
Do you have any AVC messages from SELinux?

**Comment by wenottingham** [comment]
Closing, please reopen if this persists in 1.0.6+ and you are able to provide the needed information.
