### ISSUE TITLE
Error 500 When Trying to Re-Launch Failed Job

### ISSUE THREAD

**Issue by tc-jhall** [ansible/awx#1734]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

When trying to relaunch a failed job an error pops up but another user can re-launch the job even though we have the same permissions. 
##### ENVIRONMENT
* AWX version: 1.0.4.124
* AWX install method: docker on linux
* Ansible version:  2.4.3.0 
* Operating System: Ubuntu 16.04
* Web Browser: Chrome 65.0.3325.181 (Official Build) (64-bit) (MAC)

##### STEPS TO REPRODUCE

1. Launch a job.
2. Job fails, then click on the Rocket to relaunch with same variables. 
3. Error opens with: 

![Error](https://i.imgur.com/TjHnYJP.png)

4. When the original user who created the AWX instance clicks the same button it re-launches but with parallel jobs like so:

![Dual Jobs](https://i.imgur.com/Apnyu3Q.png)

##### EXPECTED RESULTS

1. Just re-launches job with the same variables as expected. 

##### ACTUAL RESULTS

1. Error box opens with: 

![Error](https://i.imgur.com/TjHnYJP.png)

##### ADDITIONAL INFORMATION
None.

**Comment by AlanCoding** [comment]
Could you get us the logs from when the server error happened, which should contain a traceback?

**Comment by tc-jhall** [comment]
Yes, I will get some logs in the next day or so when I can re-create the failure.

**Comment by wenottingham** [comment]
Please reopen if this persists and you are able to get the needed logs.
