### ISSUE TITLE
AWX LDAP Configuration Issues

### ISSUE THREAD

**Issue by bedcruncher** [ansible/awx#1736]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI
 - Installer

##### SUMMARY
I've created a brand new dockerized AWX configuration and I cannot get it to perform LDAP authentication in any shape or form. I used the steps at the following [URL](http://guyheckman.me/installing-awx-on-centos7.html). 

##### ENVIRONMENT
* AWX version: Most Recent Github Version
* AWX install method: docker on linux
* Ansible version:  2.4.1.0
* Operating System: Centos 7.3.1611
* Web Browser: Firefox

##### STEPS TO REPRODUCE
Attempt to setup LDAP with our onsite AD and using the following Information that has been sanitized
`
LDAP SERVER
ldap://adservername.domain.local:389

LDAP USER CN
CN=Ansible,OU=Service_Accounts,DC=domain,DC=local

Password
password

LDAP REQUIRE GROUP
CN=Domain Admins,CN=Users,DC=domain,DC=local

LDAP USER SEARCH
[
 "OU=SystemAdmin,,DC=domain,DC=local",
 "SCOPE_SUBTREE",
 "(sAMAccountName=%(user)s)"
]

LDAP GROUP SEARCH
[
 "CN=Users,DC=domain,DC=local",
 "SCOPE_SUBTREE",
 "(objectClass=group)"
]

LDAP User Attribute Map
{
 "first_name": "givenName",
 "last_name": "sn",
 "email": "mail"
}

LDAP USER FLAGS BY GROUP
{
 "is_superuser": "CN=Domain Admins,CN=Users,DC=domain,DC=local"
}

LDAP TEAM MAP
{
 "GROUPNAME": {
  "users": true,
  "admins": "CN=Domain Admins,CN=Users,DC=domain,DC=local",
  "remove_admins": false,
  "remove_users": false
 }
}
`

##### EXPECTED RESULTS

To save the attributes and allow authentication via AD creds

##### ACTUAL RESULTS

If you click save and then click out, it will then pretend like it saves, but then when you try to click out it will state you have UNSAVED CHANGES, do you want to save? 

Even if you click save there it still pretends to save, but then lets you click out of the screen. When you come back to the LDAP screen, all values have been wiped out and no data has been saved.

**Comment by tjyang** [comment]
Hi @bedcruncher 

* Please look at https://github.com/ansible/awx/issues/1040 
```
 I would want to point out that this issue would not have been created if AWX presented me 
with an error or in some way the documentation would have pointed out that you cant
use "LDAP REQUIRE GROUP" with "LDAP_USER_SEARCH" &| "LDAP_GROUP_SEARCH".
```
* I haven't try above tip from Riccardo1976 myself yet.

**Comment by bedcruncher** [comment]
I saw that @tjyang but I have not ever messed with Postgres and am not 100% sure of the proper command to insert it like @riccardo1976. I've reached out to him in the original thread to see if he can paste the commands that he used. Do you perhaps know that information, or can you point me in the right direction?

**Comment by bedcruncher** [comment]
Here are the settings from the DB that get stored if you follow @riccardo1976, so if for some reason you have to manually input them, this is what will be stored in your DB.

>  AUTH_LDAP_1_START_TLS         | true
 AUTH_LDAP_SERVER_URI          | "ldap://fqdn:389"
 AUTH_LDAP_BIND_DN             | "CN=Ansible,OU=Service_Accounts,DC=SOMENAME,DC=FINAL PART OF DOMAIN"
 AUTH_LDAP_BIND_PASSWORD       | "REMOVED"
 AUTH_LDAP_START_TLS           | false
 AUTH_LDAP_USER_SEARCH         | ["PATH TO USER OU SEARCH PATH", "SCOPE_SUBTREE", "(sAMAccountName=%(user)s)"]
 AUTH_LDAP_USER_DN_TEMPLATE    |
 AUTH_LDAP_USER_ATTR_MAP       | {"first_name": "givenName", "last_name": "sn", "email": "mail"}
 AUTH_LDAP_GROUP_SEARCH        | ["PATH TO GROUP OU SEARCH PATH", "SCOPE_SUBTREE", "(objectClass=group)"]
 AUTH_LDAP_GROUP_TYPE          | "GroupOfNamesType"
 AUTH_LDAP_REQUIRE_GROUP       |
 AUTH_LDAP_DENY_GROUP          |
 AUTH_LDAP_USER_FLAGS_BY_GROUP | {"is_superuser": "SUPER USER OU PATH"}
 AUTH_LDAP_ORGANIZATION_MAP    | {"ORG NAME HERE": {"admins": "SUPER USER PATH", "remove_users": false, "remove_admins": false, "users": true}}
 AUTH_LDAP_TEAM_MAP            | {}

**Comment by tjyang** [comment]
Hi @bedcruncher 

I finally got a chance to test out AWX LDAP binding with my office MS AD server.

Using same LDAP setting(ie, Leave "LDAP REQUIRE GROUP" blank when LDAP USER/GROUP SEARCH are configured).


ansible01: AWX 1.0.2 using [rpm install approach(not supported by AWX team)](https://github.com/MrMEEE/awx-build/blob/master/installguide)
ansible03: AWX 1.0.5 using supported docker install approach
ansisble04: AWX 1.0.5 using rpm install approach

* only ansbile01 works with my MS AD server, I am able to have mult-users login in an AD group.
* ansbile03/04 are not working, the ldap setting got lost next time I login as admin user. 
* I need to find out steps to connect to backend postgresql DB to configure those settings on my ansible03/04.

**Comment by wenottingham** [comment]
You should not be connecting to PG to change configuration ever. 

This honestly sounds like a configuration issue that is best discussed on list or in IRC; please redirect there so that it can be worked through.

**Comment by bedcruncher** [comment]
@wenottingham I didn't manually change any settings via the database. I simply posted that information to show how it is stored in the database and give someone a way to see that it truly is being stored correctly and not simply being "stored" and promptly forgotten as I had previously seen.
