### ISSUE TITLE
Expected /var/lib/awx/venv/ansible to be used and it's not

### ISSUE THREAD

**Issue by dmsimard** [ansible/awx#1737]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- UI
- Installer

##### SUMMARY
There are references in the documentation that AWX should be using ansible as installed in ``/var/lib/awx/venv/ansible`` but it's actually using ``/usr/bin/ansible-playbook`` with the ``/usr/bin/python2`` interpreter.

##### ENVIRONMENT
* AWX version: awx==1.0.5.22
* AWX install method: ``docker-compose up`` from [geerlingguy](https://github.com/geerlingguy/awx-container)
* Ansible version: ansible==2.5.0

##### STEPS TO REPRODUCE

When the AWX instance is up with the demo template, edit the template to use the scm from here instead: https://github.com/dmsimard/ansible-tower-samples

It's a simple playbook edit that prints the value of the ``ansible_playbook_python`` variable.
This will return ``/usr/bin/python2``.

Additionally, you can also look at the shebang of the ``/usr/bin/ansible-playbook`` file, you'll see:
```
#!/usr/bin/python2
# (c) 2012, Michael DeHaan <michael.dehaan@gmail.com>
```

##### EXPECTED RESULTS

The documentation appears to reference ``/var/lib/awx/venv/ansible`` as where ansible runs from, i.e:
- https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md
- http://docs.ansible.com/ansible-tower/latest/html/administration/tipsandtricks.html#using-virtualenv-with-at

But in fact, that doesn't appear to be the case as shown in the reproducer.
This feels like either a bug or perhaps the documentation is outdated.

I know AWX provides the ability to create a virtualenv and you can select it manually when doing templates but that's a bit bothersome.

I would like to have the ability to install something for the python interpreter ansible/awx uses by default without having to install it system-wide -- because right now ansible/awx uses the system python interpreter and libraries.

##### ACTUAL RESULTS

I'm getting ``/usr/bin/python2`` as the interpreter so installing things in ``/var/lib/awx/venv/ansible`` are not effective since ansible will seek things in ``/usr/lib/python2.7/site-packages`` instead.

**Comment by ryanpetrello** [comment]
> AWX install method: docker-compose up from geerlingguy

@dmsimard are you seeing the same behavior using one of awx's officially supported installation methods?

https://github.com/ansible/awx/blob/devel/INSTALL.md

**Comment by dmsimard** [comment]
@ryanpetrello I'll try and report back AFAIK the ``awx_task`` container (that I reproduced this on) comes straight from Ansible: https://github.com/geerlingguy/awx-container/blob/3800cd13a24bbc9e55bd149e44d9065efa3ee779/docker-compose.yml#L46

**Comment by dmsimard** [comment]
@ryanpetrello same thing with the official docker installation:

```
git clone https://github.com/ansible/awx
cd awx/installer
ansible-playbook -i inventory install.yml
```

See screenshot:

![alt text](https://i.imgur.com/dQIUqIr.png)

Here's some sort of reproducer on the ``awx_task`` container itself:

```
[root@awx awx]# which ansible
/usr/bin/ansible
[root@awx awx]# head -n5 /usr/bin/ansible
#!/usr/bin/python2

# (c) 2012, Michael DeHaan <michael.dehaan@gmail.com>
#
# This file is part of Ansible
[root@awx awx]# which python2
/usr/bin/python2
[root@awx awx]# ansible localhost -m debug -a "var=ansible_playbook_python"
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

localhost | SUCCESS => {
    "ansible_playbook_python": "/usr/bin/python2"
}
[root@awx awx]# . venv/ansible/bin/activate
(ansible) [root@awx awx]# which python2
/var/lib/awx/venv/ansible/bin/python2
(ansible) [root@awx awx]# ansible localhost -m debug -a "var=ansible_playbook_python"
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

localhost | SUCCESS => {
    "ansible_playbook_python": "/usr/bin/python2"
}
(ansible) [root@awx awx]# pip install ansible
Requirement already satisfied: ansible in /usr/lib/python2.7/site-packages
Requirement already satisfied: jinja2 in /usr/lib/python2.7/site-packages (from ansible)
Requirement already satisfied: PyYAML in ./venv/ansible/lib/python2.7/site-packages (from ansible)
Requirement already satisfied: paramiko in ./venv/ansible/lib/python2.7/site-packages (from ansible)
Requirement already satisfied: cryptography in ./venv/ansible/lib/python2.7/site-packages (from ansible)
Requirement already satisfied: setuptools in ./venv/ansible/lib/python2.7/site-packages (from ansible)
Requirement already satisfied: MarkupSafe in /usr/lib64/python2.7/site-packages (from jinja2->ansible)
Requirement already satisfied: pyasn1>=0.1.7 in ./venv/ansible/lib/python2.7/site-packages (from paramiko->ansible)
Requirement already satisfied: bcrypt>=3.1.3 in ./venv/ansible/lib/python2.7/site-packages (from paramiko->ansible)
Requirement already satisfied: pynacl>=1.0.1 in ./venv/ansible/lib/python2.7/site-packages (from paramiko->ansible)
Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in ./venv/ansible/lib/python2.7/site-packages (from cryptography->ansible)
Requirement already satisfied: enum34; python_version < "3" in ./venv/ansible/lib/python2.7/site-packages (from cryptography->ansible)
Requirement already satisfied: asn1crypto>=0.21.0 in ./venv/ansible/lib/python2.7/site-packages (from cryptography->ansible)
Requirement already satisfied: idna>=2.1 in ./venv/ansible/lib/python2.7/site-packages (from cryptography->ansible)
Requirement already satisfied: six>=1.4.1 in ./venv/ansible/lib/python2.7/site-packages (from cryptography->ansible)
Requirement already satisfied: ipaddress; python_version < "3" in ./venv/ansible/lib/python2.7/site-packages (from cryptography->ansible)
Requirement already satisfied: pycparser in ./venv/ansible/lib/python2.7/site-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography->ansible)
```

**Comment by wenottingham** [comment]
I'm a little confused here as to what's requested.

ansible is installed as a system RPM, ergo the `#!/usr/bin/python2` comes from Ansible itself. Activating the venv isn't going to rewrite the Ansible binary.

We use the venv via setting PYTHONPATH, hence it will use newer things from the venv even with that python.... we support adding new python libs to the venv, not changing the python interpreter itself.

**Comment by ryanpetrello** [comment]
> There are references in the documentation that AWX should be using ansible as installed in /var/lib/awx/venv/ansible but it's actually using /usr/bin/ansible-playbook with the /usr/bin/python2 interpreter.

@dmsimard Can you point us where you see this?  If there are docs that suggest this, we should probably correct them.  The docs I've found (https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md) suggest that the _virtualenv_ at `/var/lib/awx/venv/ansible` will be activated (which is true), not that the `python2` _binary_ in that venv will necessarily be used.

I _can_ confirm the behavior you're seeing on a recent awx install, but as @wenottingham said, what you're seeing isn't necessarily indicative of an issue/problem; it's just how it works.

![screen shot 2018-04-09 at 10 40 48 am](https://user-images.githubusercontent.com/214912/38504377-85121834-3be2-11e8-88e2-bd8c95bab97b.png)

...and for what it's worth, the binaries seem to be identical anyways:

```shell 
sh-4.2$ md5sum /usr/bin/python2                                                                                                                                                                                                    
19fcc8d683aeb90faa0abcf53dd2a91b  /usr/bin/python2                                                                                                                                                                                 
sh-4.2$ md5sum /var/lib/awx/venv/awx/bin/python                                                                                                                                                                                    
19fcc8d683aeb90faa0abcf53dd2a91b  /var/lib/awx/venv/awx/bin/python
sh-4.2$ md5sum /var/lib/awx/venv/awx/bin/python2                                                                                                                                                                                   
19fcc8d683aeb90faa0abcf53dd2a91b  /var/lib/awx/venv/awx/bin/python2
```

> I'm getting /usr/bin/python2 as the interpreter so installing things in /var/lib/awx/venv/ansible are not effective since ansible will seek things in /usr/lib/python2.7/site-packages instead.

I don't think this is _actually_ true; awx has code that explicitly adds the awx-specific virtualenv to Python's `sys.path`:

https://github.com/ansible/awx/blob/538bf40f96c6440d842d57a8a582e84567788282/awx/main/tasks.py#L718

Here's an adhoc command I just ran with `-m shell -a python -c "import sys; print(sys.path)"`.  Note the second item in the list:

![screen shot 2018-04-09 at 10 47 12 am](https://user-images.githubusercontent.com/214912/38504795-a345b396-3be3-11e8-9995-c5c6474d9d5a.png)

**Comment by ryanpetrello** [comment]
@dmsimard if you're seeing evidence that the venv at `/var/lib/awx/venv/awx/` is _not_ activated or is _not_ in use for job runs, let me know and I'll re-open this.

**Comment by dmsimard** [comment]
@wenottingham @ryanpetrello I took a fresh look at this and I still can't figure it out.

Despite installing ARA (and it's dependencies) inside /var/lib/awx/venv/ansible, ARA isn't able to import any of it's dependencies:

![rrg5q78](https://user-images.githubusercontent.com/1291204/49156004-53fa9400-f2ea-11e8-8d4c-78bdf81f49cf.png)

The dependencies I need are all installed and they've been installed with umask 0022 as per the documentation:

```
# /var/lib/awx/venv/ansible/bin/pip freeze |grep -i xstatic
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
XStatic==1.0.2
XStatic-Bootstrap-SCSS==3.3.7.1
XStatic-DataTables==1.10.15.1
XStatic-jQuery==3.3.1.1
XStatic-Patternfly==3.21.0.1
XStatic-Patternfly-Bootstrap-Treeview==2.1.3.2
```

Out of curiosity, I tried installing XStatic in /var/lib/awx/venv/awx and it doesn't resolve the problem.
I tried installing XStatic globally -- not in a virtualenv -- and ARA was able to import it but fails on the import of another dependency.

In theory, making ARA work with AWX should be as simple as this:
```
# Install ARA from pypi
$ /var/lib/awx/venv/ansible/bin/pip install ara

# Print the path where the callback is located
$ /var/lib/awx/venv/ansible/bin/python -m ara.setup.callback_plugins
/var/lib/awx/venv/ansible/lib/python2.7/site-packages/ara/plugins/callbacks
```

And then set it up in settings:
![screenshot from 2018-11-27 18-40-21](https://user-images.githubusercontent.com/1291204/49156361-37129080-f2eb-11e8-8a2c-6bf6f564dfd2.png)

But it doesn't work.

Any ideas ? :)

**Comment by dmsimard** [comment]
Spent some more time on this but I haven't been able to get to the bottom of it ...

What I found out is that it doesn't work if the virtual environment is inheriting from the system's site packages.
If I create a new virtual environment without ``--system-site-packages`` (requires installing ``psutils`` and ``python-memcached`` manually), install ARA and Ansible in it, it works.

I don't know why.
My current suspicions are that it's either a problem related to the way we customize ``PYTHONPATH`` and ``sys.path`` or it's somehow a conflict coming from the fact that the default venv, ``/var/lib/awx/venv/ansible``, carries Ansible from the distribution installed RPM package outside the virtualenv.

This is the PYTHONPATH and the sys.path when it doesn't work:
```
PYTHONPATH = ['/var/lib/awx/venv/ansible/lib/python2.7/site-packages', '']
sys.path = [
    '/var/lib/awx/venv/awx/lib/python2.7/site-packages/awx/lib',
    '/usr/bin',
    '/var/lib/awx/venv/ansible/lib/python2.7/site-packages',
    '/var/lib/awx/projects/_4__ansible_tower_cicd',
    '/usr/lib64/python27.zip',
    '/usr/lib64/python2.7',
    '/usr/lib64/python2.7/plat-linux2',
    '/usr/lib64/python2.7/lib-tk',
    '/usr/lib64/python2.7/lib-old',
    '/usr/lib64/python2.7/lib-dynload',
    '/usr/lib64/python2.7/site-packages',
    '/usr/lib64/python2.7/site-packages/gtk-2.0',
    '/usr/lib/python2.7/site-packages'
]
```

This is the PYTHONPATH and sys.path when it works:
```
PYTHONPATH = ['/var/lib/awx/venv/test/lib/python2.7/site-packages', '']
sys.path = [
    '/var/lib/awx/venv/awx/lib/python2.7/site-packages/awx/lib',
    '/var/lib/awx/venv/test/bin',
    '/var/lib/awx/venv/test/lib/python2.7/site-packages',
    '/var/lib/awx/projects/_4__ansible_tower_cicd',
    '/var/lib/awx/venv/test/lib64/python27.zip',
    '/var/lib/awx/venv/test/lib64/python2.7',
    '/var/lib/awx/venv/test/lib64/python2.7/plat-linux2',
    '/var/lib/awx/venv/test/lib64/python2.7/lib-tk',
    '/var/lib/awx/venv/test/lib64/python2.7/lib-old',
    '/var/lib/awx/venv/test/lib64/python2.7/lib-dynload',
    '/usr/lib64/python2.7',
    '/usr/lib/python2.7'
]
```
