### ISSUE TITLE
Delete Instance Group without selecting an Instance Group - Infinite gear icon

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#1739]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- UI

##### SUMMARY
On the Instance Group list, clicking the trash can without selecting any Instance Groups results in the gear icon showing without ever disappearing.

Note: After this happens, you can "recover" by simply refreshing the page.

**Comment by jaredevantabor** [comment]
this is fixed now in devel
