### ISSUE TITLE
Selecting an inventory file from a project only lists yml files

### ISSUE THREAD

**Issue by kustodian** [ansible/awx#174]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When selecting an inventory file for a `Source from Project` inventory, the file selector only displays `*.yml` files and no other files. Check out the picture:
![image](https://user-images.githubusercontent.com/1949229/30482852-fa78146c-9a24-11e7-806f-fa841d36d4e1.png)
You can type the full path of the filename in the textbox above the file list and press enter, but that is not a good user experience. I can understand that you don't want to display all the files in a project, but at least allow filtering them by typing the file names, or displaying more extensions by default (e.g. `*.ini`).

##### ENVIRONMENT
* AWX version: 1.0.0.333

**Comment by matburt** [comment]
I'm trying to remember if this was a thing we consciously decided on, but it does seem a little wrong. I'm going to cc @AlanCoding who implemented this feature on the Tower side and we'll see what we can do.

There is a limitation to how many files we can process to try to determine what an inventory file/dir/script is.

**Comment by AlanCoding** [comment]
`*.ini` files should show up. We cap the list at 50 entries, so overly-broad criteria are only a problem in that they may crowd out other valid files.

You can also type in the relative path if you need an immediate practical resolution.

**Comment by matburt** [comment]
I was talking to @rmfitzpatrick about this one last week and he had some great suggestions.

I definitely think we need to deprioritize the .yml files, I don't think I've met anyone who uses yml files for inventory. In fact, a lot of folks will *literally* use a file called `inventory`. So we could almost just list all of the files and directories that are *not* yml files... maybe up to one subdirectory deep while keeping our 50 item limit?

I also think the text entry box needs to have some sort of placeholder/help text to call it out as a place you could enter a project-relative path if you didn't see your inventory file listed. I think I mentioned this one to @jaredevantabor @gconsidine and @jlmitch5 also. Would love their feedback along with @trahman73

**Comment by AlanCoding** [comment]
> I also think the text entry box needs to have some sort of placeholder/help text to call it out as a place you could enter a project-relative path if you didn't see your inventory file listed.

@matburt do you just mean putting it in the help text? Because such a suggestion is already in there.

![screen shot 2017-09-18 at 9 02 56 am](https://user-images.githubusercontent.com/1385596/30543216-3987ebfa-9c50-11e7-8fcc-557693925cf7.png)

**Comment by AlanCoding** [comment]
@kustodian Could you share with us a repository that reproduces the scenario you observed? I have `*.ini` files in a repo here:

https://github.com/AlanCoding/Ansible-inventory-file-examples

Those show up in the suggestions for me. Some cases that will cause them to _not_ show up include:

 - putting them inside a dot directory, like `.git`
 - putting them inside a directory named `group_vars` or `host_vars`

**Comment by matburt** [comment]
I mean putting some help text in the text entry line... it's not immediately obvious what that's for and folks don't always read the tooltip

**Comment by trahman73** [comment]
@matburt @AlanCoding I agree with having some placeholder on the field itself and only showing the most commonly used file types capped at 50.  We can also turn this field into a lookup similar to how we pick credentials so the user can search/filter through all available files.

**Comment by AlanCoding** [comment]
After reviewing our existing code and examples, I'm going to put this in `needs_info`. For reference:

 - Our code intends to include all `.ini` files in the list, see https://github.com/ansible/awx/blob/devel/awx/main/utils/ansible.py#L65-L67
 - My examples show that this is working, see folder https://github.com/AlanCoding/Ansible-inventory-file-examples/tree/master/test_batch

![screen shot 2017-09-18 at 12 03 32 pm](https://user-images.githubusercontent.com/1385596/30551798-c04e8f2c-9c69-11e7-961f-0193ff7eb227.png)

We can look further into this if given a repo with .ini files that are not getting picked up when loaded as a project in AWX.

**Comment by AlanCoding** [comment]
Proposal from aggregating the related discussions:

(API)
 - Do not include YAML files in the file suggestions list (few people use them as inventory)
 - Always include any file with the filename of "hosts" or "inventory"

(UI)
 - New placeholder to suggest that typing into the field is possible
 - Implement a search-while-typing feature for the entry box

**Comment by kustodian** [comment]
We have some very long paths to inventory files (don't ask why for now) which looks like this:
```
gameserver_playbooks/teamcity_playbooks/inventories/environment1_test/environment1_test.ini
gameserver_playbooks/teamcity_playbooks/inventories/environment2_test/test.ini
gameserver_playbooks/teamcity_playbooks/inventories/environment3/test-hosts.ini
gameserver_playbooks/teamcity_playbooks/inventories/environment4/test-hosts.ini
gameserver_playbooks/teamcity_playbooks/inventories/environment5/environment1_hosts.ini
gameserver_playbooks/teamcity_playbooks/inventories/environment6/environment6_hosts.ini
gameserver_playbooks/teamcity_playbooks/inventories/environment7/environment7.ini
```
I changed the name of files a little bit but this is how they look like and they are not displayed in the list of files. But also if I type `.ini` I would expect the box to display only ini files, but it doesn't display these files. I also tried typing e.g. `environment` or `inventories` expect it to display only files in those directories, but nothing I type filters out those files. Of course as I mentioned before writing a full path and pressing ENTER helps, but it's not the most convenient way of selecting an inventory files.

If you need a full list of files in our project, I can send you directly, because I don't want to share a whole project here (for now).

**Comment by matburt** [comment]
@kustodian this might not work in the near term for you. We're only going to index the first 50 files we find.

The input box on that drop down will take anything, though... it doesn't have to match a search pattern. Since you already know the name of inventory you'd just type it in directly there and it will pick it up and work.

**Comment by kustodian** [comment]
@matburt I know it works like that, just saying that it isn't the best UX in the world :P

If you removed displaying `.yml` by default and only display `.ini`, `inventory`, `hosts`,... it would at least suggest better files.

**Comment by AlanCoding** [comment]
Thank you for the feedback, the inclusion criteria for that list is strictly based on user utility, and I agree your use case is the most representative of what most users will have.

**Comment by AlanCoding** [comment]
Changes made, if you pick up current `devel`, it should be giving a better list according to the changes agreed on here.

Some UI work is still remaining, so issue will remain open.

**Comment by AlanCoding** [comment]
@trahman73 leaving issue open for items you mentioned:

> having some placeholder on the field itself and only showing the most commonly used file types capped at 50. We can also turn this field into a lookup similar to how we pick credentials so the user can search/filter through all available files.

**Comment by matburt** [comment]
@AlanCoding can you create another issue to track the placeholder text?

**Comment by AlanCoding** [comment]
We talked, and we weren't on the same page about what he was talking about. I thought someone was saying the dropdown wasn't searchable (it is), and showing >50 isn't something we have any intention of doing, so I think we can leave the issue to rest with the already-mentioned API adjustments.

**Comment by Testicule** [comment]
"inventory_linux"
no good eh.
great.
