### ISSUE TITLE
UI freezes bottom lines on job task reader

### ISSUE THREAD

**Issue by asc-me** [ansible/awx#1740]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### ENVIRONMENT
* AWX version: AWX 1.0.5.20
* AWX install method: docker compose on linux
* Ansible version:  2.5.0
* Operating System: centos 7 3.10
* Web Browser: chrome

##### STEPS TO REPRODUCE

in a longer running play, if you sit and watch the template run, lock your computer, then turn it back on while its still running the tasks. the bottom few lines will have frozen from when the screen locked.

![image](https://user-images.githubusercontent.com/2293255/38512886-5d4846da-3be1-11e8-8839-59a57fe035ba.png)

##### EXPECTED RESULTS

i would expect the lines to keep running at its current activity line.

##### ACTUAL RESULTS

see the above image, the bottom few lines freeze in place and start blocking the task reader

**Comment by jakemcdermott** [comment]
Hello Twistedsixty4,

Thanks for filing this bug report. This issue has been resolved downstream and so you'll be seeing the fixes for this issue once the code changes are merged back into AWX.
