### ISSUE TITLE
Custom Inventory Script Credentials

### ISSUE THREAD

**Issue by jamestutton** [ansible/awx#1744]
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
Ability to pass Custom Credentials to custom inventory script.  

Some of the cloud inventories allow passing credentials but there isn't a suitable option when using a custom script.  In my case pulling data from an asset management system.  As the script is displayed in RAW form in the AWX UI and the environment variables are also not encrypted and view-able there is currently no way to securely pass the api credentials to the script. 

I had hopped the I could tweak my script to pass the ansible_user and ansible_host enviroment variables and use those but machine credentials are obviously filtered within the inventory script section.  So as such the only option would be to cheat and maybe use AWX or one of the Redhat cloud options but that is far from ideal.  As such can i raise the idea of either a custom script credential option or even better a fully custom credential with free text key value pairs that are stored encrypted and converted to environment variables for use anywhere.

**Comment by ryanpetrello** [comment]
Hi @jamestutton,

awx has support for custom credential types, which allow you to define your own custom fields (e.g., username, password, API key) and also define how those field values are injected into the `ansible-playbook` runtime environment (e.g., setting specific extra vars, setting environment variables, writing out templated data to a file).  Take a look at this Ansible Tower documentation that describes how the feature works:

https://docs.ansible.com/ansible-tower/latest/html/userguide/credential_types.html

If you need some inspiration, a number of the cloud credentials in awx itself are actually implemented using this feature under the hood:

https://github.com/ansible/awx/blob/devel/awx/main/models/credential/__init__.py#L1084
https://github.com/ansible/awx/blob/devel/awx/main/models/credential/__init__.py#L1112
https://github.com/ansible/awx/blob/devel/awx/main/models/credential/__init__.py#L1164

**Comment by andrewsav-bt** [comment]
@ryanpetrello The issue raised is about "to pass Custom Credentials to custom inventory script" Could you please point out which part of you answer addresses this?

When you create and Inventory Script there is no UI field provided to pass (or as you put it "inject") your Custom Credentials into that Inventory Script. If you could possibly specify how to do this, it would help a lot.

**Comment by ryanpetrello** [comment]
What version of AWX are you running?  You specify the credential when you set up an inventory *source*:

![image](https://user-images.githubusercontent.com/214912/64382855-a4361d80-d003-11e9-876c-abaa1d6ec495.png)

**Comment by andrewsav-bt** [comment]
@ryanpetrello  Right. Thank you for that, it clears this up.
