### ISSUE TITLE
Venv Docker

### ISSUE THREAD

**Issue by dragon2611** [ansible/awx#1746]
##### ISSUE TYPE
 - Bug Report
 - Documentation

##### COMPONENT NAME
- UI
 - Installer

##### SUMMARY
Virtual Environments don't appear to be exposed outside of the docker containers 
Could just be user error but wouldn't this lead to loss of the venv on an update to the container?

##### ENVIRONMENT
* AWX version: AWX 1.0.5.22
* AWX install method: docker on linux
* Ansible version:  2.50
* Operating System: Centos 7

##### STEPS TO REPRODUCE

Attempt to setup virtual environment appears to involve editing the FS inside the docker containers for awx-web and awx-test

##### EXPECTED RESULTS

Expect the directory to be exposed to the host to preserve virtual-env across updates.

##### ACTUAL RESULTS

Directory is not exposed as far as I can tell

**Comment by ryanpetrello** [comment]
Hey @dragon2611,

Take a look at https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md#preparing-a-new-custom-virtualenv, specifically the part that starts with:

> For container-based deployments, this likely means building these steps into your own custom image building workflow, e.g.,

It's possible that we could expose some sort of volume mapping to the host for this in the future, but for now, the supported way to do this w/ the installer is to build your own image that bakes in your custom dependencies/virtualenvs:

https://github.com/ansible/awx/blob/devel/INSTALL.md#official-vs-building-images

**Comment by dragon2611** [comment]
@ryanpetrello Aren't all supported deployments container based?

The only reason I even started down the path of venv is because I needed netaddr for a jina2 IP filter.

**Comment by ryanpetrello** [comment]
@dragon2611 awx shares it source code with Ansible Tower, which is currently _not_ container based - you'll find that much of the awx docs are ambiguous in this regard to describe all possible types of deployment for features.

**Comment by ryanpetrello** [comment]
@dragon2611 if you're just adding a single dependency, _another_ option is that you can build your own dependencies into the base ansible virtualenv by adding to:

https://github.com/ansible/awx/blob/devel/requirements/requirements_ansible.txt

...and following the instructions to build your own image:

https://github.com/ansible/awx/blob/devel/INSTALL.md#official-vs-building-images
