### ISSUE TITLE
SAML Authentication not working. Wrong location in AssertionConsumerService Binding

### ISSUE THREAD

**Issue by Baefisch** [ansible/awx#1749]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - SAML Authentication

##### SUMMARY
Not able to authenticate. Got localhost in SAML configuration.
configured addresse in Webui:
https://ansible-tower-xy.com/sso/metadata/saml/

get the following back:
<md:SPSSODescriptor AuthnRequestsSigned="false" WantAssertionsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
<md:KeyDescriptor xmlns:ds="http://www.w3.org/2000/09/xmldsig#" use="signing">
<ds:KeyInfo>
<ds:X509Data>
<ds:X509Certificate>
xyxyxyxyxyxyxyxyxyxyxyxyxyx
</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</md:KeyDescriptor>
<md:NameIDFormat>...</md:NameIDFormat>
<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://localhost:8080/sso/complete/saml/"index="1"/>
</md:SPSSODescriptor>

##### ENVIRONMENT
* AWX version: 1.0.5.0 
* AWX  docker on linux
* Ansible version:  2.5.0
* Operating System: Centos 7.4
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

Configure SAML authentification and try to login.

##### EXPECTED RESULTS

Successfully logged in.

##### ACTUAL RESULTS

Error Page.

An error occurred
An error occurred. Contact your administrator for more information.
Error details
Activity ID: 00000000-0000-0000-590d-0080000000a8
Relying party: Ansible Tower
Error time: Wed, 11 Apr 2018 12:13:01 GMT
Cookie: enabled
User agent string: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by wenottingham** [comment]
Hi, if you're having an issue with configuration of Ansible Tower, please contact your Red Hat support rep.

**Comment by Baefisch** [comment]
I am using AWX. Only the dns name is Ansible-tower. Sorry for that.

**Comment by wenottingham** [comment]
What is your SAML configuration?

**Comment by Baefisch** [comment]
![2018-04-17 11_24_57-ansible awx _ edit configuration](https://user-images.githubusercontent.com/38285078/38861113-070e8ebc-4232-11e8-9ced-dcd4ff4dfd9a.png)

**Comment by Baefisch** [comment]
![2018-04-17 11_24_57-ansible awx _ edit configuration](https://user-images.githubusercontent.com/38285078/38861260-6985e6d0-4232-11e8-8100-dd80738edd5c.png)

**Comment by jakemcdermott** [comment]
Hello @Baefisch 

Thanks for creating this issue. This looks like a configuration or infrastructure issue - your best bet would be to reach out to our mailing list or stop by our irc channel (`#ansible-awx` on freenode) for support on making sure you've configured your AWX properly.

**Comment by mtward** [comment]
Hello @Baefisch.  Were you able to resolve this?  I seem to be having the same issue.

**Comment by Baefisch** [comment]
I did Not try anymoore. I am using ldaps now. Keep me in loop, If you are succesfull
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 07.02.19, 20:53, mtward <notifications@github.com> schrieb:
Hello @Baefisch.  Were you able to resolve this?  I seem to be having the same issue.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ansible/awx","title":"ansible/awx","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ansible/awx"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mtward in #1749: Hello @Baefisch.  Were you able to resolve this?  I seem to be having the same issue."}],"action":{"name":"View Issue","url":"https://github.com/ansible/awx/issues/1749#issuecomment-461572637"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ansible/awx/issues/1749#issuecomment-461572637",
"url": "https://github.com/ansible/awx/issues/1749#issuecomment-461572637",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
