### ISSUE TITLE
awx current ansible version.

### ISSUE THREAD

**Issue by kiranos** [ansible/awx#175]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - Installer

##### SUMMARY
AWX seems to rely upon epel to provide ansible version which is currently 2.3.1 
There is an important bugfix in 2.3.2 which was released 2017-08-04 but epel has not gotten this release yet. So I've fixed it with "backporting the module from 2.3.2 to a local library/"

It would be nice if AWX could get the current release of ansible sooner.

**Comment by matburt** [comment]
My thought here is that we could include the ansible repo in the installer instead of relying on epel.

**Comment by matburt** [comment]
alrighty!  check out #183 if you get a chance.
