### ISSUE TITLE
AWX on Openshift installation failed with rabbitmq container error: "su-exec: setgroups: Operation not permitted"

### ISSUE THREAD

**Issue by Volkimd** [ansible/awx#1750]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

I try to install AWX in Openshift from this repo and have a problem with rabbitmq Container.
It crashes and put the message
`su-exec: setgroups: Operation not permitted`

##### ENVIRONMENT
* AWX version: latest
* AWX install method: openshift
* Ansible version:  2.4.2.0
* Operating System: Red Hat Enterprise Linux Server release 7.4
* Web Browser:  Google Chrome

##### STEPS TO REPRODUCE

ansible-playbook -i inventory install.yml -e openshift_token="bla"  -e docker_registry_password=$(oc whoami -t) -e pg_volume_capacity=5

after creating conainers, rabbitmq container is crashing with 
`su-exec: setgroups: Operation not permitted`

##### EXPECTED RESULTS

Should come up

##### ACTUAL RESULTS

Crash:
`su-exec: setgroups: Operation not permitted`

**Comment by shanemcd** [comment]
What version of OpenShift are you using?

**Comment by Volkimd** [comment]
Hi thx for reply. It is v3.7.0

**Comment by midekra** [comment]
Any suggestions? I have the same issue.

**Comment by midekra** [comment]
I got it working with the following workaround:

oc adm policy add-scc-to-user anyuid system:serviceaccount:awx-namespace:default

**Comment by ryanpetrello** [comment]
This should be resolved in newer versions of awx - let us know you're still encountering issues and we'll reopen this.
