### ISSUE TITLE
Extra Environment Variables from global settings not passed to playbook run

### ISSUE THREAD

**Issue by ahotzler** [ansible/awx#1752]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Variables, defined in AWX-Webinterface->Settings->Jobs->"Extra Environment Variables" are not passed to a playbook run

##### ENVIRONMENT
* AWX version: 1.0.5.22
* AWX install method: docker
* Ansible version:  ansible 2.5.0
* Operating System: CentOS Linux release 7.4.1708 (Core)
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1.) Add something like:
```
{
 "HOME": "/var/lib/awx",

 "default_var_file": "../../_15__vars_gitlabfritzbox/default-vars/awxdeb-vars.yml"
}
```
into: AWX-Webinterface->Settings->Jobs->"Extra Environment Variables"
and click "save"

2.) Exec a playbook im Tower:
```
  tasks:

  - debug:
      msg: "{{default_var_file}}"
```
3.) Result:

`{
    "msg": "The task includes an option with an undefined variable. The error was: 'default_var_file' is undefined\n\nThe error appears to have been in '/var/lib/awx/projects/_14__playbooks_gitlabfritzbox/debug_vars/main.yml': line 7, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - debug:\n    ^ here\n"
}`

4.) add the same variables to a job template and it works.

The description for
AWX-Webinterface->Settings->Jobs->"Extra Environment Variables"
is:
"Additional environment variables set for playbook runs, inventory updates, project updates, and notification sending."

So in my understanding, variables defined there should be passed to every playbook run.

##### EXPECTED RESULTS

`TASK [debug] *******************************************************************16:10:30
ok: [testbuechse1.fritz.box] => {
    "msg": "../../_15__vars_gitlabfritzbox/default-vars/awxdeb-vars.yml"
}`

##### ACTUAL RESULTS

`{
    "msg": "The task includes an option with an undefined variable. The error was: 'default_var_file' is undefined\n\nThe error appears to have been in '/var/lib/awx/projects/_14__playbooks_gitlabfritzbox/debug_vars/main.yml': line 7, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - debug:\n    ^ here\n"
}`

##### ADDITIONAL INFORMATION

-

**Comment by LukeShortCloud** [comment]
The environment variables are added to the shell environment, not the Ansible facts/variables. Try using a Jinja environment lookup instead.

```
  - debug:
      msg: "{{ lookup('env', 'default_var_file') }}"
```

http://docs.ansible.com/ansible/2.5/plugins/lookup/env.html#examples

**Comment by AlanCoding** [comment]
Let us know if the solution from @ekultails does not solve your issue.

**Comment by ahotzler** [comment]
Thank you, that makes sense. I misunderstood the configuration setting.
