### ISSUE TITLE
Unable to clone mercurial repositories hosted on servers using SNI

### ISSUE THREAD

**Issue by s19n** [ansible/awx#1753]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - AWX "web" docker image

##### SUMMARY
Mercurial projects cannot be cloned when the remote server is hosting multiple SSL certificates via SNI. All certificates are LetsEncrypt signed and currently valid.

##### ENVIRONMENT
* AWX version: 1.0.5
* AWX install method: docker on linux
* Ansible version:  2.5.0
* Operating System: Ubuntu 16.04
* Web Browser: any

##### STEPS TO REPRODUCE

* Host an Ansible Project or a role in a mercurial repository on a server providing multiple SSL certificates via SNI
* Define a Project or also a dependency on a role in a roles/requirements.yml file
* Try an inventory update from the interface, or run `hg clone` for the same repository inside the web container

##### EXPECTED RESULTS

The mercurial repository is correctly cloned.

##### ACTUAL RESULTS

The clone operation cannot complete because of a certificate error:
```
[root@5caa6406da47 /]# hg clone https://user:password@a.example.com/rolename
abort: a.example.com certificate error: certificate is for b.example.com
(configure hostfingerprint <fingerprint> or use --insecure to connect insecurely)
```

##### ADDITIONAL INFORMATION

The problem can be solved by installing mercurial 3.3.0+ inside the container, i.e. via `pip`:
https://www.mercurial-scm.org/wiki/WhatsNew/Archive#Mercurial_3.0_.282014-05-01.29
> * https: support tls sni (server name indication) for https urls (issue3090)

Presumably in https://github.com/ansible/awx/blob/1595947ae2b87756ecac0124bf1ba7823ee20285/installer/roles/image_build/files/Dockerfile.sdist ?

**Comment by wenottingham** [comment]
While true, the container image is built from EL-7 and pulls its packages from there. I don't know that we'd specifically pick this up unless EL-7 does.

**Comment by AlanCoding** [comment]
mercurial support is being removed now https://github.com/ansible/awx/pull/8727
