### ISSUE TITLE
Allowing password phrase to ssh keys for isolated node

### ISSUE THREAD

**Issue by cesarfn4** [ansible/awx#1759]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
We have a customer that needs to manage the RSA key that we distribute to all "isolated" nodes  (isolated_key_generation=false), but the isolated nodes only accepts SSH keys without passphrase.

##### EXPECTED RESULTS
Allowing password phrase to ssh keys for isolated node

**Comment by shanemcd** [comment]
RIP isolated nodes.
