### ISSUE TITLE
Test, document, and refine new patterns established in awx/ui/lib/ and awx/ui/features/

### ISSUE THREAD

**Issue by jaredevantabor** [ansible/awx#176]
### Summary

**Testing**

1. Test runner configuration (for fast unit tests)
2. At minimum, a well-tested example of a model, a directive, and a controller. This will help serve as a reference for additional test coverage over time.

**Linting**

Fully-linted source based on agreed upon eslint configuration.

**Documentation**

At minimum, documentation of `BaseModel` and the interface for each component.

**Nice to have**

* Test coverage reporting
* Generated documentation
* Hosted coverage and documentation

**Comment by wenottingham** [comment]
@gconsidine @jakemcdermott is this covered by the existing test suite?

**Comment by mabashian** [comment]
I'm inclined to close this issue.  It's unlikely that we'll be spending any significant time expanding on the patterns described here.
