### ISSUE TITLE
On object updates, include summary_fields in ActivityStream log. (such as object id/pk)

### ISSUE THREAD

**Issue by mirskiy** [ansible/awx#1761]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY

This came out of discussion on #1757 
On update, the object id is not included in any of the fields logged by the ActivityStreamMiddleware, and there is no single field that could be logged to solve the issue for all object types - each type has a separate field in ActivityStream.
On create and delete, the object id is logged in ActivityStream.changes, as `get_allowed_fields` in `model_to_dict` (which populates changes) includes the id for all object types. On associate/dissociate, objtect1_pk and object2_pk are included in changes. So only update is missing the id.

#1757 Fixes this problem for Setting by logging ActivityStream.setting, but a more general solution is needed.
A few ideas:
- Include the object id in the changes field as in the case of create, delete, and associate/dissociate. ActivityStream.changes comes from `model_instance_diff`, which could easily be modified for this, but it could break any tools that depend on ActivityStream.changes to be only values that changed in the case of an update.
- Make the change in the middleware - log an object1_pk field and object2_pk  determined from the appropriate ManyToManyFIeld in ActivityStream. This wouldn't work for Setting, as ActivityStream doesn't maintain a relation to the Setting object that was updated.
- Switch to GenericForeignKeys or add object1_id/object2_id back to ActivityStream (they were removed in 61059fa1a4bd93f881eccf16d5f703bd8625ce74)

For all of the solutions above (except GenericForeignKey), I would recommend still logging the ActivityStream.setting field in the middleware OR finding a solution that logs Setting.key as part of the ActivityStream log, as this would make compliance easier. Currently, `model_to_dict` (which is used for ActivityStream.changes on create/delete) does not include Setting.key because it is a read-only field in the serializer. (See `get_allowed_fields`).

##### ENVIRONMENT
* AWX version: 1.0.5.22
* AWX install method: docker on linux
* Ansible version:  2.5.0
* Operating System: Ubuntu
* Web Browser: Chrome

##### STEPS TO REPRODUCE

- Setup external logging to include activity_stream
- Change a JobTemplate or Setting
- Notice the activity stream logs doesn't include the id of the object changed (see actual results)

##### EXPECTED RESULTS

- The object id should be present for all ActivityStream logs.
- The Setting key should be present for all settings creation/changes/deletion

##### ACTUAL RESULTS

For JobTemplate update:
```
{"cluster_host_id": "awx", 
"relationship": "", 
"level": "INFO", 
"type": "splunk", 
"@timestamp": "2018-04-11T22:49:16.160Z", 
"host": "awxweb", 
"actor": "admin", 
"object1": "job_template", 
"object2": "",
"logger_name": "awx.analytics.activity_stream", 
"message": "Activity Stream update entry for job_template", 
"changes": "{\"description\": [\"\", \"TEST\"]}", 
"operation": "update"}
```

For Setting update
```
{"cluster_host_id": "awx",
"relationship": "",
"level": "INFO",
"type": "splunk",
"@timestamp": "2018-04-11T19:15:22.352Z",
"host": "awxweb",
"actor": "admin",
"object1": "setting",
"object2": "",
"logger_name": "awx.analytics.activity_stream",
"message": "Activity Stream update entry for setting",
"changes": "{\"value\": [30, 31]}",
"operation": "update"}
```

##### ADDITIONAL INFORMATION

This might be considered a bug, as it breaks auditing compliance.

**Comment by AlanCoding** [comment]
Let me just throw it out there that I think we should get rid of the activity stream middleware.

https://github.com/ansible/awx/blob/20e5d8200e359b6f57dd620fc728ee15d6d9aa86/awx/main/middleware.py#L68

This is a major complicating factor for this issue. There is way too much unnecessary complexity.

**Comment by nixocio** [comment]
This one was manually verified.

![image](https://user-images.githubusercontent.com/9053044/78283225-7e1a2280-74eb-11ea-9714-0f05975658be.png)




```json
{
    "@timestamp": "2020-04-02T18:06:02.213Z",
    "message": "Activity Stream update entry for setting",
    "host": "awx",
    "level": "INFO",
    "logger_name": "awx.analytics.activity_stream",
    "stack_info": null,
    "changes": {
        "value": true,
        "id": 72
    },
    "relationship": "",
    "actor": "admin",
    "operation": "create",
    "object1": "setting",
    "object2": "",
    "summary_fields": {
        "actor": {
            "id": 1,
            "username": "admin",
            "first_name": "",
            "last_name": ""
        },
        "setting": [
            {
                "category": "logging",
                "name": "LOG_AGGREGATOR_ENABLED"
            }
        ]
    },
    "cluster_host_id": "awx",
    "tower_uuid": "00000000-0000-0000-0000-000000000000"
}{
    "@timestamp": "2020-04-02T18:06:34.294Z",
    "message": "Activity Stream update entry for setting",
    "host": "awx",
    "level": "INFO",
    "logger_name": "awx.analytics.activity_stream",
    "stack_info": null,
    "changes": {
        "value": [
            "udp",
            "tcp"
        ]
    },
    "relationship": "",
    "actor": "admin",
    "operation": "update",
    "object1": "setting",
    "object2": "",
    "summary_fields": {
        "actor": {
            "id": 1,
            "username": "admin",
            "first_name": "",
            "last_name": ""
        },
        "setting": [
            {
                "category": "logging",
                "name": "LOG_AGGREGATOR_PROTOCOL"
            }
        ]
    },
    "cluster_host_id": "awx",
    "tower_uuid": "00000000-0000-0000-0000-000000000000"
}


```
