### ISSUE TITLE
Unable to add variable file to template

### ISSUE THREAD

**Issue by vab2048** [ansible/awx#1762]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea

Not sure which one this comes under.

##### COMPONENT NAME
 - UI

##### SUMMARY
When running from the command line I can include a variable file using the -e flag:

`ansible-playbook -e "@vars_file.yml" -e "ENV=prod" some_playbook.yml`

I can easily replicate the key value pair in the template by simply adding it to the "extra vars" box but how do I set up the template so it runs with the -e "@vars_file.yml" as well?

##### ENVIRONMENT
* AWX version: 1.0.5
* AWX install method: docker on linux
* Ansible version:  2.5.0
* Operating System: Ubuntu 16.04
* Web Browser:

**Comment by wenottingham** [comment]
You can't/don't.

Can do an extra_var or survey that's used to populate a vars_file entry in the playbook.
