### ISSUE TITLE
Request addition of Python netaddr to default virtualenv

### ISSUE THREAD

**Issue by howels** [ansible/awx#1763]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - Installer

##### SUMMARY

The Python netaddr package is widely used and mentioned as [closely related to Ansible](http://docs.ansible.com/ansible/latest/user_guide/playbooks_filters_ipaddr.html) but is not available in the default venv.  This rules out deploying other major projects including the popular [Kubernetes Kubespray installer](https://github.com/kubernetes-incubator/kubespray/blob/master/README.md).  Could netaddr please be added to the standard AWX task/web docker image virtualenv so that users do not have to maintain a custom Docker build for this one package?

##### ENVIRONMENT
* AWX version: 1.0.5
* AWX install method: minikube (Kubernetes)
* Ansible version:  latest
* Operating System: Ubuntu/minikube
* Web Browser: Chrome

##### STEPS TO REPRODUCE

The feature would be a pip install netaddr into the default venv and would allow for a wider range of playbook compatibility with the default AWX builds.

**Comment by bladecoates** [comment]
Getting the same issue with 1.0.5.32. Using custom Docker build, to add a few extra items like ssh-keys and others, but no new pip requirements. The ipv4 filter fails. 

{"changed": false, "msg": "AnsibleFilterError: The ipv4 filter requires python-netaddr be installed on the ansible controller"}

**Comment by bladecoates** [comment]
Looks to have been removed from one requirement file in 556e6c4a117597fc36fdab53b32a4e29ed494a34

**Comment by howels** [comment]
This appears to have indeed been caused by 556e6c4 which removed netaddr along with many other packages relating to Azure, OpenStack etc.  
Whilst this may have saved space, the inability to build Kubernetes is a concern.  

Please can this be reverted? Happy to do a commit but want to understand the reasoning that caused this change in the first place.
