### ISSUE TITLE
win_copy Connection aborted.', error("(104, 'ECONNRESET') on AWX

### ISSUE THREAD

**Issue by LeDOC666** [ansible/awx#1766]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- WinRM

##### SUMMARY

Can you add module pywinrm 0.3.0 to docker image to correct bug deposed on issue:
#https://github.com/ansible/ansible/issues/38474

**Comment by LeDOC666** [comment]
Finally, I make newer tests:

On my VM:
ansible-2.4.2
pywinrm==0.3.0

Everything work, I can make copy of exe files (4Mo) and more to Windows 2008 R2 servers

On my awx container:
- ansible/awx_task:latest
- ansible/awx_web:latest (from 7 days)

I can copy some files, but when I have to copy that 4Mo file:
`<virwiphipsql.pam.lan> WINRM PUT "/var/lib/awx/projects/projet_windows/files/npp756.exe" to "C:\Temp\ansible-tmp-1523969601.34-141635792052231\source" (offset=4250000 size=250000)
 [WARNING]: FATAL ERROR DURING FILE TRANSFER: ('Connection aborted.',
error("(104, 'ECONNRESET')",))`

I tryed in updating pip, and pywinrm to 0.3.0 in container like other issue, but same problem.
I can copy other files (exe of 200Ko) for exemple

Do you have an idea ?

**Comment by wenottingham** [comment]
We already include this. See requirements.txt.

**Comment by LeDOC666** [comment]
Hi, maybe I checked on bad place, but I see no trace of pywinrm under requirement.txt file.
I rebuild docker image of awx_web, and pip seems not install this module too !?

`[root@awxweb sample]# pip freeze | more
You are using pip version 8.1.2, however version 10.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ansible==2.5.0
awx==1.0.5.24
Babel==0.9.6
backports.ssl-match-hostname==3.4.0.2
cffi==1.6.0
chardet==2.2.1
cryptography==1.7.2
enum34==1.0.4
httplib2==0.9.2
idna==2.4
iniparse==0.4
ipaddress==1.0.16
Jinja2==2.8
jmespath==0.9.0
kitchen==1.1.1
MarkupSafe==0.11
meld3==1.0.2
mercurial==2.6.2
paramiko==2.1.1
ply==3.4
psutil==2.2.1
psycopg2==2.7.4
pyasn1==0.1.9
pycparser==2.14
pycrypto==2.6.1
pycurl==7.19.0
pygobject==3.22.0
pygpgme==0.3
pyliblzma==0.5.3
python-keyczar==0.71rc0
pyxattr==0.5.1
PyYAML==3.10
six==1.9.0
supervisor==3.3.4
urlgrabber==3.10
virtualenv==15.2.0
yum-metadata-parser==1.1.4`
