### ISSUE TITLE
Adhoc task output not displayed after returning to job detail

### ISSUE THREAD

**Issue by madeinoz67** [ansible/awx#1770]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

When executing an adhoc command the output is displayed as per normal, however if I leave the job detail page and then return back to the job detail the output is not displayed.

Returning to a template job works as expected.

##### ENVIRONMENT
* AWX version: 1.0.5.23
* AWX install method: docker on linux
* Ansible version:  2.5.0
* Operating System: Centos 7.4
* Web Browser: safari, chrome

##### STEPS TO REPRODUCE

1) from inventory hosts I select an adhoc command (win_ping) and execute it.
2) task detail is displayed along with output of adhoc command
3) return to the list of jobs i.e.  click on job list
4) drill down down into the job detail - no job output is displayed 

##### EXPECTED RESULTS

job output to be displayed 

##### ACTUAL RESULTS

job output screen blank

##### ADDITIONAL INFORMATION

jsconsole output
```
[Error] undefined is not an object (evaluating 'self.socket.readyState')
http://nms-ans01/static/js/app.763b47aa28c5e5fd8aac.js:47 – "Possibly unhandled rejection: {\"line\":47,\"column\":687595,\"sourceURL\":\"http://nms-ans01/static/js/app.763b47aa28c5e5fd8aac.js\"}"
	(anonymous function) (vendor.3e674a3ba3212cd5dd22.js:71:93571)
	processChecks (vendor.3e674a3ba3212cd5dd22.js:71:134823)
	$digest (vendor.3e674a3ba3212cd5dd22.js:71:146080)
	(anonymous function) (vendor.3e674a3ba3212cd5dd22.js:71:148589)
	completeOutstandingRequest (vendor.3e674a3ba3212cd5dd22.js:71:37088)
	(anonymous function) (vendor.3e674a3ba3212cd5dd22.js:71:40247)
[Error] TypeError: undefined is not an object (evaluating 'self.socket.readyState')
	onopen (app.763b47aa28c5e5fd8aac.js:47:685096)
	(anonymous function) (app.763b47aa28c5e5fd8aac.js:24:984200)
	dispatchEvent
	onopen (app.763b47aa28c5e5fd8aac.js:24:985673)
```

![2018-04-17_12-27-53](https://user-images.githubusercontent.com/4160293/38848760-59620988-423b-11e8-9053-b8046cc11a83.png)
![2018-04-17_12-28-44](https://user-images.githubusercontent.com/4160293/38848763-5dc4475c-423b-11e8-9cb9-ea58d6601e03.png)
![2018-04-17_12-29-00](https://user-images.githubusercontent.com/4160293/38848767-61dee5e0-423b-11e8-9d1f-79476a438bd9.png)

**Comment by madeinoz67** [comment]
this appears to be working in v1.0.6.5 so will close

**Comment by buggsdummy** [comment]
I am still seeing this as an issue for AWX 24.6.0

If you run in realtime and look for stdout output is found for this job, but if you go back to the job history, you will see it show up. 

My command was just running uptime

<img width="3782" height="1972" alt="Image" src="https://github.com/user-attachments/assets/c5fbf58e-0bb8-4219-970a-f80e2d35b360" />
