### ISSUE TITLE
Add ability to set inventory source in workflow templates.

### ISSUE THREAD

**Issue by soloman747** [ansible/awx#1772]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
We have a workflow with 20+ jobs. We are able to set the inventory source at the job level, but it becomes a bit taxing to have to modify each of the job templates whenever we want to switch inventory sources. It is also not feasible to copy job templates to have separate inventories per workflow, as it wouldn't be very long before we have more job templates than we can manage. It would be nice to be able to set the inventory source at the workflow template alone, and have the workflow level inventory take precedence over the job template level inventory.

##### ENVIRONMENT
* AWX version: 1.0.4.124
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: Ubuntu
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create a workflow template with various job templates. In each job template, you have the ability to set the inventory source. In the workflow template, you can overwrite job template level variables, but you cannot overwrite the job template level inventory source.

**Comment by wenottingham** [comment]
You should be able to do this for workflow nodes if 'prompt for inventory' is set.

**Comment by soloman747** [comment]
I can confirm that's not the case. In the user guide it specifically states:

"As the workflow runs, jobs are spawned from the node’s linked template. Nodes linking to a job template which has prompt-driven fields (job_type, job_tags, skip_tags, limit) can contain those fields, and will not be prompted on launch. Job templates with promptable credential and/or inventory, WITHOUT defaults, will not be available for inclusion in a workflow."

**Comment by wenottingham** [comment]
This is a workflow-creation-time feature, not a launch-time feature.

**Comment by soloman747** [comment]
Okay can I specify that the feature request is for the inventory selection to be executable at launch time?

**Comment by wenottingham** [comment]
That's https://github.com/ansible/awx/issues/1731. Marking as a duplicate.
