### ISSUE TITLE
Feature: Normal user should be able to create Projects/Inventory from awx web.

### ISSUE THREAD

**Issue by chestercheng** [ansible/awx#1773]
ISSUE TYPE

- Feature

 Idea

- COMPONENT

 NAME

- UI

SUMMARY

A normal user should be able to create projects or inventory. Since project or inventory may be imported from their own SCM, users should be able to create project or inventory and then create template to run. Or it will always need system administrator to create.

The view of admin
![default](https://user-images.githubusercontent.com/36478905/38909935-731c3a06-42f9-11e8-8726-188dfe3c2eb5.JPG)

The view of normal user => No 「+ADD」Button for creating a new project
![default](https://user-images.githubusercontent.com/36478905/38909890-351e171a-42f9-11e8-9032-f3ee703da7d7.JPG)

ENVIRONMENT

- AWX version: any

**Comment by wenottingham** [comment]
This will not be done.

In current AWX, these are specific permissions that you can delegate, outside of org admin.

**Comment by IAMShashankk** [comment]
@wenottingham How can I allow Normal user to create/copy the new/exiting inventories.

**Comment by wenottingham** [comment]
Assign them the 'Inventory admin' permission for their organization.

**Comment by IAMShashankk** [comment]
I tried that but after admin permission they are only allowed to edit the
inventory.
Still they are not able to copy/create new inventory.

I assigned admin roles for the users by adding them in team.

**Comment by ms-harmonic** [comment]
Hi @wenottingham ,

Assigning 'Inventory admin' permission allows a normal user to create/edit/delete the inventories in their organization.
But is there a way we can assign this permission to the LDAP user by default i.e. by setting some configuration in the LDAP server settings like "LDAP Organization Map" or "LDAP Team Map". Otherwise, it is not feasible to assign the "Inventory Admin" to all the LDAP users manually.

Thanks,
Mukesh R Sahay

**Comment by wenottingham** [comment]
Inventory Admin can be assigned to a team, which can come from an LDAP map.

**Comment by ms-harmonic** [comment]
> Inventory Admin can be assigned to a team, which can come from an LDAP map.

@wenottingham 
Could you please let know how can we do that? Which parameter should be added to make this happen?

e.g. 
LDAP Team Map:

{
 "Team1": {
  "organization": "org1",
  "users": true
 }
}

**Comment by wenottingham** [comment]
You map the team as above, and apply the role to the team once it exists.
