### ISSUE TITLE
Docker image for ansible/awx_web:1.0.4 seems to contain a version of 1.0.5

### ISSUE THREAD

**Issue by dantheta** [ansible/awx#1779]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY

After installing and starting an AWX install using the 1.0.4 docker images, I tried to log in through the API using /api/v2/authtoken/.  The API issued a 404 response.  I looked inside the docker image at api/urls/urls.py, and found references to LoggedLoginView and LoggedLogoutView instead of AuthTokenView; these changes are found in the 1.0.5 tagged version, not in 1.0.4.  I'm wondering if the docker images were built from the wrong source.

The images I'm using are:

```
ansible/awx_task    1.0.4               6d2002c20b84        3 weeks ago         1.03GB
ansible/awx_task    1.0.4.130           6d2002c20b84        3 weeks ago         1.03GB
ansible/awx_web     1.0.4               efce4d0feb8c        3 weeks ago         1.01GB
ansible/awx_web     1.0.4.130           efce4d0feb8c        3 weeks ago         1.01GB


```

##### ENVIRONMENT
* AWX version: 1.0.4
* AWX install method: docker on linux
* Ansible version:  2.4.1
* Operating System: Centos7

##### STEPS TO REPRODUCE

Ran installer/install.yml, having set ```dockerhub_version=1.0.4``` in inventory.

```
curl  -X POST -H 'Content-type: application/json' 'http://localhost:8010/api/v2/authtoken/' -d '{"username":"admin","password":"password"}'
```

##### EXPECTED RESULTS

Output:
```
{"token":"b61b77dc58ca53aecc846977e13784c08c2c64af","expires":"2018-04-18T17:10:43.352981Z"}
```

##### ACTUAL RESULTS

Output:
```{"detail":"The requested resource could not be found."}```

**Comment by matburt** [comment]
anything after 1.0.4.0 will contain some changes moving towards 1.0.5... if you aren't interested in those then you'll need to set it to explicitly be 1.0.4.0
