### ISSUE TITLE
Ingress not working for AWX Kubernetes installation

### ISSUE THREAD

**Issue by shen3lu4** [ansible/awx#1781]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

I am setting up ingress so that AWX can have SSL termination. The path of awx URL can only be <hostname>/. Anything other than / would not work.

##### ENVIRONMENT
* AWX version: 1.0.4.109
* AWX install method: kubernetes
* Ansible version:  2.4.3
* Operating System: Oracle Enterprise Linux 7.4
* Web Browser: Chrome, IE, Firefox

##### STEPS TO REPRODUCE

Tweaked awx-ingress spec to be as follows:
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: awx-ingress
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  tls:
  \- hosts:
    \- \<hostname\>
    secretName:  \<secret name\>
  rules:
  \- host: \<hostname\>
    http:
      paths:
      \- path: /awx
        backend:
          serviceName: awx-web-svc
          servicePort: 80

##### EXPECTED RESULTS

Expect to get to AWX login page when go to https://\<hostname\>/awx

##### ACTUAL RESULTS

The web page doesn't load properly. See screenshot.

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/36993641/38958218-3a00dff0-4322-11e8-89f0-4c445d709f68.png)

if I simply set the path to: "path: /", it is working fine at https://\<hostname\>/

**Comment by shanemcd** [comment]
This is currently not supported. Our Nginx config does not handle SSL at all. You will need to do your own SSL termination using something like HAProxy or whatever else you would like to put in front of AWX.
