### ISSUE TITLE
Nginx Redirection and python error

### ISSUE THREAD

**Issue by JulienFR56** [ansible/awx#1787]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Nginx/Python

##### SUMMARY

I had this error log (container awx_web output) when i tried to record the logstasch connector through the GUI AWX interface.

'2018/04/19 15:20:17 [error] 27#0: *799 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.7, server: _, request: "OPTIONS /api/v2/settings/all/ HTTP/1.1", upstream: "uwsgi://[::1]:8050", host: "203.34.222.69", referrer: "https://203.34.222.69/"
'
After that, i apply this fix https://github.com/ansible/awx/issues/1452 and the precedent error disapear...but to have a new one .

'2018-04-20 09:00:27,641 ERROR    awx.main.utils.handlers Error sending message from TCPHandler:
 Traceback (most recent call last):
   File "/usr/lib/python2.7/site-packages/awx/main/utils/handlers.py", line 272, in _send
     sok.connect((self._get_host(hostname_only=True), self.port or 0))
   File "/usr/lib64/python2.7/socket.py", line 224, in meth
     return getattr(self._sock,name)(*args)
 error: [Errno 111] Connection refused
'
 
I modified this file /usr/lib/python2.7/site-packages/awx/main/utils/handlers.py", line 272 to replace hostname_only=True by hostname_only=True but it dosen't fix the problem.

Is the version 1.0.5 fix the logstasch output log ?

Thank you

##### ENVIRONMENT
* AWX version: 1.0.5.24
* AWX install method: docker on linux
* Ansible version:  2.5
* Operating System: RedHat 7.4
* Web Browser:

Edit : Update to the last version.

**Comment by JulienFR56** [comment]
I updated the AWX to the 1.0.5.24 version. The behavior is better but i have this error again,

2018-04-20 14:32:12,864 WARNING  awx.api.generics status 500 received by user admin attempting to access /api/v2/settings/logging/test/ from 203.5.128.225
[pid: 26|app: 0|req: 17/126] 203.5.128.225 () {46 vars in 2373 bytes} [Fri Apr 20 14:32:12 2018] POST /api/v2/settings/logging/test/ => generated 26 bytes in 103 msecs (HTTP/1.1 500) 8 headers in 236 bytes (1 switches on core 0)

**Comment by JulienFR56** [comment]
Hello,

Someone has an answer on this subject ?

Thank you

**Comment by wenottingham** [comment]
Apologies, but there have been many changes since then. Please try 2.0 or later, and open a new issue if this persists.
