### ISSUE TITLE
project_data_dir and ca_trust_dir don't work together

### ISSUE THREAD

**Issue by jok26r** [ansible/awx#1788]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

If you specify project_data_dir and ca_trust_dir in the inventory file, then the only project_data_dir will be defined in the volumes part of the awx_tasks and awx_web containers.

##### ENVIRONMENT
* AWX version: 1.0.5
* AWX install method: docker on linux
* Ansible version:  2.5.1
* Operating System: Ubuntu 16.04 LTS

##### STEPS TO REPRODUCE
1. Specify project_data_dir and ca_trust_dir in the inventory file
2. Run an installation sudo ansible-playbook -i inventory install.yml --check -vvv

##### EXPECTED RESULTS
You should see the following output in the volumes parts of the awx_task and awx_web containers:
```
"volumes": [
                "project_data_dir:/var/lib/awx/projects:rw",
                "ca_trust_dir:/etc/pki/ca-trust/source/anchors:ro"
]
```

##### ACTUAL RESULTS
```
"volumes": [
                "project_data_dir:/var/lib/awx/projects:rw"
]
```

**Comment by akcrisp** [comment]
this seems to be a bug that was introduced after 1.0.5.11 and has just caught me on a 1.0.5.32 build

**Comment by akcrisp** [comment]
as a quick fix  changing local_docker/tasks/standalone.yml - for awx_task and awx_web

Change -
  volumes: >
      {{
        [project_data_dir + ':/var/lib/awx/projects:rw'] if project_data_dir is defined else []
        + [ca_trust_dir + ':/etc/pki/ca-trust/source/anchors:ro'] if ca_trust_dir is defined else []
      }}

to -

    volumes:
     - "{{ project_data_dir + ':/var/lib/awx/projects:rw' if project_data_dir is defined else [] }}"
     - "{{ ca_trust_dir + ':/etc/pki/ca-trust:ro' if ca_trust_dir is defined else [] }}"

and it works again.

**Comment by shanemcd** [comment]
This installer has been removed from the project.
