### ISSUE TITLE
Returned JSON is empty when standard output is large

### ISSUE THREAD

**Issue by AStrangwood** [ansible/awx#1789]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

When a job returns a large standard output(around 4800 lines) the UI does not shown any output at all and just displays {}, 

##### ENVIRONMENT
* AWX version: 1.05
* AWX install method: docker on linux
* Ansible version:  2.5.1
* Operating System: Ubuntu 16
* Web Browser: Firefox/Chrome

##### STEPS TO REPRODUCE

Run a job that has at least 4800 lines returned in standard ouput

##### EXPECTED RESULTS

![expected](https://user-images.githubusercontent.com/5055026/39128329-6aa5ac4a-46ff-11e8-9af9-99abf50fbfc8.PNG)
Standard output returned around 1800 lines in this one

##### ACTUAL RESULTS

![empty](https://user-images.githubusercontent.com/5055026/39128177-0333b304-46ff-11e8-8977-a6a2dd8b5543.PNG)
This was around 4800 lines in standard output.

##### ADDITIONAL INFORMATION

This is a fresh install of ansible, awx and ubuntu

**Comment by ryanpetrello** [comment]
@AStrangwood if you visit:

`https://your.tower.example.org/api/v2/job_events/78/`

...do you see any stdout data?

**Comment by AStrangwood** [comment]
![78](https://user-images.githubusercontent.com/5055026/39134675-0ca88ef4-470f-11e8-83db-2078b2afbabc.PNG)

This is what i get from the link. Missing everything from the task that ran and has the large standard output returned.

**Comment by ryanpetrello** [comment]
Any chance you see any errors in your web browser's developer/Javascript console?

**Comment by jaredevantabor** [comment]
The UI shows `event_data.res` in the JSON tab of the host event modal, and `event_data.res.stdout` for the Standard Out tab. In the API screenshot, it looks like `event_data.res` is an empty object, so the UI in this case is correctly showing the output.

**Comment by AStrangwood** [comment]
I dont see any error in the browsers dev console. Just the empty task when i click on it. Are there any logs that i can check to see whats going on when the task finishes? The exact same task has no issue when it doesn't have so many lines in the standard out.

This is a Poweshel task if that is any help.

**Comment by ryanpetrello** [comment]
@AStrangwood as @jaredevantabor alluded to, the data we're recording here comes directly from the Ansible callback plugin interface - it's just what Ansible passes us, and I don't _think_ we're doing anything to filter out this data structure.

Are you encountering this issue in other versions of Ansible (pre 2.5.1)?

**Comment by ryanpetrello** [comment]
Hey @AStrangwood I've found the culprit:

https://github.com/ansible/awx/blob/devel/awx/lib/awx_display_callback/events.py#L148

awx has a configurable setting that truncates large `res` values:

https://github.com/ansible/awx/blob/devel/awx/settings/defaults.py#L172

If you raise this value, you should see the issue go away.

**Comment by AStrangwood** [comment]
@ryanpetrello thanks for that, how can adjust this value?

**Comment by ryanpetrello** [comment]
@AStrangwood you can add the following to the bottom of `/etc/tower/settings.py` on the `awx-celery` container:

`MAX_EVENT_RES_DATA = <large int>`

**Comment by ryanpetrello** [comment]
@AStrangwood one thing to keep in mind is that memcached itself (where this data is stored during processing) has an upper bound here - you may find that raising this value actually overflows memcached and causes evictions if your data is sufficiently large.

**Comment by vhpj** [comment]
Hello @ryanpetrello, do you know the units of the parameter MAX_EVENT_RES_DATA?

**Comment by ryanpetrello** [comment]
Hey @vhpj, it should be bytes.

**Comment by evelandi** [comment]
Exactly the same is happening to me using ansible-runner python module. when the output is too large it return an empty res. is it possible to change the MAX_EVENT_RES_DATA within the ansible config file?

**Comment by evelandi** [comment]
Hello Folks, I found a way of modifying this when using ansible_runner as a Python interface module. first of all, I want to tell you that this variable is used by ansible_runner when managing the events, exactly on this file /<python site-packages path/ansible_runner/display_callback/events.py. in this file, you can see there is an expression where it gets the MAX_EVENT_RES (Same variable as MAX_EVENT_RES_DATA in AWX) from environment variables and if it doesn't exist it assigns a default value of 700000 which in some cases when the output of the device is too big the res data will be empty. having said that the solution is to set the MAX_EVENT_RES as the environment variable as follows: os.environ['MAX_EVENT_RES'] = "value bigger than 700000" before calling the ansible_runner.run(), I used 90000000 and it worked perfectly.

**Comment by person50002** [comment]
can this value of be configured in the AWX web interface? I tried adding it to "Extra Environment Variables" under "Jobs settings" but it didn't help.
