### ISSUE TITLE
Simple install - Error while fetching server API version

### ISSUE THREAD

**Issue by naisanza** [ansible/awx#179]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

When installing AWX from the documentation, it stops at an error: Error while fetching server API version

Following the install guide found here: https://github.com/ansible/awx/blob/devel/INSTALL.md

Installed the requirements:
```
sudo apt-get update
sudo apt-get install -y software-properties-common
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update
apt install -y ansible docker make git python-setuptools python-pip python3-pip
pip install --upgrade pip
pip install --upgrade docker
pip3 install --upgrade pip
pip3 install --upgrade docker
git clone https://github.com/ansible/awx.git
```

Ran the ansible playbook
```
TASK [image_build : Build sdist builder image] **************************************************************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))"}
	to retry, use: --limit @/root/awx/installer/install.retry

PLAY RECAP **************************************************************************************************************************************
localhost                  : ok=8    changed=2    unreachable=0    failed=1   
```

##### STEPS TO REPRODUCE

1. Install requirements
2. cd awx/installer
3. ansible-playbook inventory install.yml

**Comment by naisanza** [comment]
Missed inventory tag `ansible-playbook -i inventory install.yml`

**Comment by naisanza** [comment]
Looks like the issue is related to docker service not starting, but docker can't run inside lxc

**Comment by Sagarvt2002** [comment]
How is this fixed. I am getting the same issue

**Comment by philipp-winterle** [comment]
> How is this fixed. I am getting the same issue

Install Docker - Debian e.g.:
https://docs.docker.com/engine/install/debian/
