### ISSUE TITLE
Ansible getting stucked after executing a "raw" command

### ISSUE THREAD

**Issue by alissonpdc** [ansible/awx#1790]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- Engine

##### SUMMARY
Ansible gets stuck just after execute a command using the "raw" module on a Cisco video conference device (tested on EX60 and EX90).

##### ENVIRONMENT
Ansible 2.4.2.0
RHEL 7

##### STEPS TO REPRODUCE

YAML:
- name: Ansible job
  hosts: 10.54.39.68
  gather_facts: no

  tasks:
  - name: Executing command
    raw: xStatus Diagnostics Call

##### EXPECTED RESULTS

Expected to get the call statistics from de device (it's possible to get such statistics normally acessing the device from SSH)
[...]
*s Diagnostics Call 4 Channels IncomingAudioChannel 148 Netstat 1 Bytes: 18185089512
*s Diagnostics Call 4 Channels IncomingAudioChannel 148 Netstat 1 ChannelRate: 65000
*s Diagnostics Call 4 Channels IncomingAudioChannel 148 Netstat 1 Drop: 0
*s Diagnostics Call 4 Channels IncomingAudioChannel 148 Netstat 1 Jitter: 3
*s Diagnostics Call 4 Channels IncomingAudioChannel 148 Netstat 1 LastIntervalLost: 0
*s Diagnostics Call 4 Channels IncomingAudioChannel 148 Netstat 1 LastIntervalReceived: 350
*s Diagnostics Call 4 Channels IncomingAudioChannel 148 Netstat 1 Loss: 425
*s Diagnostics Call 4 Channels IncomingAudioChannel 148 Netstat 1 MaxJitter: 4
[...]

##### ACTUAL RESULTS

Right after the command "xStatus Diagnostics Call" is executed, Ansible gets stuck and doesn't "see" de device's response:

TASK [Executing command] **************************************************************************************************
task path: /var/lib/awx/projects/PROJ-Monitoracao_VC_TP/teste.yaml:7
<10.54.39.68> ESTABLISH CONNECTION FOR USER: admin on PORT 22 TO 10.54.39.68
<10.54.39.68> EXEC xStatus Diagnostics Call

Stay this way forever.

##### ADDITIONAL INFORMATION

I don't know if this could be the cause, but when accessing the video conference device, it doesn't display a common CLI. It doesn't look like it is expecting any input.. maybe this is making Ansible gets lost.

"Password: 
Welcome to V-BR-SP-CT-5Âº-BLC-DADOS
Cisco Codec Release TC7.3.3.c84180a
SW Release Date: 2015-06-12
*r Login successful

OK

"

You can type a command after the "OK".
There is no "hostname>" or "hostname#", as if it wasn't expecting any command.
![ansible](https://user-images.githubusercontent.com/38671015/39153682-34874a60-4722-11e8-9ed6-973f5068e850.png)

**Comment by cchurch** [comment]
This looks like an issue with Ansible itself and not with AWX.

Please ask these kinds of questions on the [ansible-project](https://groups.google.com/forum/#!forum/ansible-project) mailing list or IRC. See [Reporting Bugs And Requesting Features](http://docs.ansible.com/ansible/latest/community/reporting_bugs_and_features.html) for more info.
