### ISSUE TITLE
100% CPU load after rebooting machine with running AWX docker-compose installation

### ISSUE THREAD

**Issue by Grokzen** [ansible/awx#1792]
##### ISSUE TYPE

 - [X] Bug Report
 - Feature Idea
 - Documentation

##### COMPONENT NAME

 - Docker & Compose

##### SUMMARY

If i have AWX running on my machine and i reboot my laptop, when the docker containers automatically start after reboot, it will start to churn away on 100% CPU on my laptop.

##### ENVIRONMENT
* AWX version: 1.0.5
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: Linux
* Web Browser: Chrome

##### STEPS TO REPRODUCE

 - Start the AWX with docker-compose method
 - Reboot your macihne
 - Look in `htop` for 100% CPU usage

##### EXPECTED RESULTS

One of 2 things

1. Docker compose components should NOT automatically start on machine boot. I do want to start it myself each time i boot my machine.
2. Locate and fix the CPU problem inside the problem container and solve it for reboots.

##### ACTUAL RESULTS

100% CPU usage on my machine after reboot and i have to manually stop and start all AWX containers to resolve the issue.

**Comment by shanemcd** [comment]
What process(es) are pegging your CPU?

**Comment by rancheradminau** [comment]
I just had this issue last night. I think it is the rabbitmq container. Once I started stopping them in order, CPU starting to go down after that one. I might try to pull a prior mq container and see if it works.

**Comment by rancheradminau** [comment]
Update, this only appears to happen when my Macbook is on battery power. :(

**Comment by Grokzen** [comment]
@shanemcd `python /usr/bin/awx-manage migrate --noinput --fake-initial` runs when i boot my laptop. I let it run to see if there was some loop or just a very long process, and it took about 8-12 minutes before it calmed down and the load on my machine went away.

I would still argue that by default the local_docker solution should not boot up automatically, but that should be a option in the settings that you can enable and it renders out the correct config to the compose file.

**Comment by wenottingham** [comment]
This is to be expected if you're using /tmp for database storage and your /tmp is cleared on boot - it will restart and recreate the database by running the migrations.
