### ISSUE TITLE
AWX 3.2.3 /api/v2/authtoken/ removed prematurely?

### ISSUE THREAD

**Issue by AgentCormac** [ansible/awx#1793]
##### ISSUE TYPE

 - Bug Report
 - Documentation

##### COMPONENT NAME

 - API

##### SUMMARY
/api/v2/authtoken/ no longer seems to be available in AWX 3.2.3. The release notes suggest that this endpoint is deprecated and that it will be removed on AWX 3.3. However, OAuth endpoint is available but there is no documentation and there seems to be no way to generate application keys in AWX.

##### ENVIRONMENT
* AWX version: 3.2.3
* AWX install method: ansible role: geerlingguy.ansible

##### ADDITIONAL INFORMATION

GET /api/v2/
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
X-API-Node: awx
X-API-Time: 0.059s

{
    "ping": "/api/v2/ping/",
    "instances": "/api/v2/instances/",
    "instance_groups": "/api/v2/instance_groups/",
    "config": "/api/v2/config/",
    "settings": "/api/v2/settings/",
    "me": "/api/v2/me/",
    "dashboard": "/api/v2/dashboard/",
    "organizations": "/api/v2/organizations/",
    "users": "/api/v2/users/",
    "projects": "/api/v2/projects/",
    "project_updates": "/api/v2/project_updates/",
    "teams": "/api/v2/teams/",
    "credentials": "/api/v2/credentials/",
    "credential_types": "/api/v2/credential_types/",
    "applications": "/api/v2/applications/",
    "tokens": "/api/v2/tokens/",
    "inventory": "/api/v2/inventories/",
    "inventory_scripts": "/api/v2/inventory_scripts/",
    "inventory_sources": "/api/v2/inventory_sources/",
    "inventory_updates": "/api/v2/inventory_updates/",
    "groups": "/api/v2/groups/",
    "hosts": "/api/v2/hosts/",
    "job_templates": "/api/v2/job_templates/",
    "jobs": "/api/v2/jobs/",
    "job_events": "/api/v2/job_events/",
    "ad_hoc_commands": "/api/v2/ad_hoc_commands/",
    "system_job_templates": "/api/v2/system_job_templates/",
    "system_jobs": "/api/v2/system_jobs/",
    "schedules": "/api/v2/schedules/",
    "roles": "/api/v2/roles/",
    "notification_templates": "/api/v2/notification_templates/",
    "notifications": "/api/v2/notifications/",
    "labels": "/api/v2/labels/",
    "unified_job_templates": "/api/v2/unified_job_templates/",
    "unified_jobs": "/api/v2/unified_jobs/",
    "activity_stream": "/api/v2/activity_stream/",
    "workflow_job_templates": "/api/v2/workflow_job_templates/",
    "workflow_jobs": "/api/v2/workflow_jobs/",
    "workflow_job_template_nodes": "/api/v2/workflow_job_template_nodes/",
    "workflow_job_nodes": "/api/v2/workflow_job_nodes/"
}

**Comment by rooftopcellist** [comment]
@AgentCormac AuthToken was removed in favor of OAuth2 early in AWX 1.0.4.  AWX is an upstream community project, so the feature lands when the PR is merged effectively.  Here is the [ML Post](https://groups.google.com/forum/#!topic/awx-project/kjlXPyc2YwE) about it.  

There are acceptance docs [here](https://github.com/ansible/awx/blob/devel/docs/auth/oauth.md).
