### ISSUE TITLE
Dark theme / dark mode

### ISSUE THREAD

**Issue by avindra** [ansible/awx#1794]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY

Would be great to have a dark theme, so we can spend extra hours inside AWX without burning our eyes out.

**Comment by shanemcd** [comment]
In the meantime, [this Chrome extension](https://chrome.google.com/webstore/detail/dark-mode-night-reader/hmafjphdklmdjfcnljjeonfpgafanjjc?hl=en) works pretty ok.

**Comment by G3ph4z** [comment]
Any news?

**Comment by AlexSCorey** [comment]
@G3ph4z we don't have anything in the works right now to add a dark mode in the current ui.  However, the new ui (which we are currently building out in conjunction with Patternfly) does have a dark-er mode and they have an Epic created to track progress in that area.  

This is the current ui with the "dark mode":
![Screen Shot 2020-04-21 at 2 59 20 PM](https://user-images.githubusercontent.com/39280967/79904441-a4dcc200-83e2-11ea-9738-826faa5a5c43.png)

Here are some resources that might help and provide some insight: 

https://github.com/patternfly/patternfly/issues/1977 
https://blog.patternfly.org/ux-research/patternfly-4-navigation-light-theme-or-dark-theme/

**Comment by G3ph4z** [comment]
@AlexSCorey Thanks for the update, I'll check it. :)

**Comment by BloodyIron** [comment]
As someone who really is sensitive to light that really needs a lot more dark to reduce eye strain. The main content of that page is all white. I would like to add my vote for a full dark mode/theme, it';s the direction so many applications have already gone and are going. Windows 10, MacOS and countless applications have full Dark Mode/Themes already. If we're spending hours upon hours upon hours in this environment, something that drastically reduces eye strain really is something worth doing.

**Comment by CaptainStealthy** [comment]
One more vote for this feature, as I work in 'dark mode' applications all day long.

But as a temporary workaround, the [Dark Reader](https://darkreader.org/) extension works pretty well, and supports Chrome, Firefox, Edge, and Safari.

**Comment by ansiblejunky** [comment]
I created a simple Ansible Role to change Ansible Tower into "dark mode". You can see screenshots and code on my Github repo [here](https://github.com/ansiblejunky/ansible_tower_dark_mode). I basically push a new CSS with overriding colors, styles, etc to produce the dark mode theme. Spent some time to try to get all of the screens and bips-and-bops worked out with the right colors. I am sure I missed something but it's generally quite usable and enjoyable. You can easily switch between `light mode` and `dark mode` easily. 

Feel free to create a branch and PR for mods to make it work with AWX - haven't tried it yet against AWX.

Cheers and enjoy!

![Screenshot](https://github.com/ansiblejunky/ansible_tower_dark_mode/raw/main/images/tower-darkmode.jpg)

**Comment by SasBer** [comment]
+1
I would love to have a official suppored dark mode

**Comment by USB-Coffee** [comment]
Official dark mode would be amazing

**Comment by TheRealHaoLiu** [comment]
we are working on the next iteration of UI for AWX which includes dark mode 🚀 

it's included in awx 22.0.0 as tech preview please check it out
