### ISSUE TITLE
Install Fails because deprecated NPM package contextify is Required by UI

### ISSUE THREAD

**Issue by llbbl** [ansible/awx#1795]
Can not build locally using the ansible-playbook command. 

ubuntu 16.04
node -v v9.11.1
node-gyp -v v3.6.2
npm 5.6.0
Python 2.7.12
pip 10.0.1

AWX on 1.0.5 tag

```
npm --unsafe-perm --prefix awx/ui install awx/ui
```

The npm install command from the Makefile is returning an error that is preventing install from continuing. 

```
contextify.target.mk:95: recipe for target 'Release/obj.target/contextify/src/contextify.o' failed
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
make: Leaving directory '/var/www/awx/node_modules/contextify/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/logan/.nvm/versions/node/v9.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "/home/logan/.nvm/versions/node/v9.11.1/bin/node" "/home/logan/.nvm/versions/node/v9.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/awx/node_modules/contextify
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/var/www/awx/package.json'
npm WARN awx No description
npm WARN awx No repository field.
npm WARN awx No README data
npm WARN awx No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/logan/.npm/_logs/2018-04-24T16_59_51_128Z-debug.log
```

Contextify is no longer maintained. 

[https://github.com/brianmcd/contextify/issues/205](https://github.com/brianmcd/contextify/issues/205)

Tried globally installing "node-gyp rebuild" packages. Didn't fix. 

Can't figure out why it is required exactly. 

```
ansible-playbook -i inventory install.yml
- calls:
make sdist
- calls:
npm --unsafe-perm --prefix awx/ui install awx/ui
```
#

**Comment by llbbl** [comment]
Looks like it is working with older versions of nodejs. 

Try using nodejs in the following range:

v6.0  to v8.11.1

Don't have time to try them all. Got it working with nodejs 6.0 then switched to LTS with ```nvm install —lts``` and seemed to be okay, but didn't delete all the artifacts that 6.0 left over.  Looks like 7.10.1 is the newest release currently in that version.

**Comment by ryanpetrello** [comment]
Hey @llbbl,

Building the UI requires 6.x LTS of Node and NPM:

https://github.com/ansible/awx/blob/bfea00f6dc6af0fb01057ce38e9d0337e6c589aa/awx/ui/README.md

@jaredevantabor should we call this out in https://github.com/ansible/awx/blob/bfea00f6dc6af0fb01057ce38e9d0337e6c589aa/INSTALL.md ?

**Comment by llbbl** [comment]
Adding this to Install.md was very helpful. Thanks.
