### ISSUE TITLE
Credentials do not show up under workflow for a Job template for credential type of network

### ISSUE THREAD

**Issue by micruzz82** [ansible/awx#1796]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Workflow template on selecting a Job template with credential type of network in it shows in the workflow editor info under job as None Selected

##### ENVIRONMENT
* AWX 1.0.5.24
* AWX install method: docker on linux
* Ansible 2.5.0
* Operating System: centos 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create a Project with SCM as Git
Create a Job template with a project, playbook and use a credential with a credential type of network.
Create a Workflow template
Click Start
Under jobs, click info button for the job template created above and credential says none selected

##### EXPECTED RESULTS

Object for credential should show under the workflow job with credential of type network

##### ACTUAL RESULTS

CREDENTIAL
NONE SELECTED

**Comment by kialam** [comment]
Closing as this is expected behavior. Workflow lists and detail views should not show credentials, however Job templates and playbooks should display the credentials associated with it.
