### ISSUE TITLE
Cannot delete the admin user or any user that has associated resources.

### ISSUE THREAD

**Issue by sysblade** [ansible/awx#1803]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API ( I suppose as it's related to data storage)
 - UI

##### SUMMARY
Cannot delete an user that has created something (for example even the default admin user on a blank install)

##### ENVIRONMENT
* AWX version: AWX 1.0.5.31
* AWX install method: Docker on Linux
* Ansible version:  2.5.1
* Operating System: Docker on Centos Atomic
* Web Browser: Chrome

##### STEPS TO REPRODUCE

- Delete the admin user on a blank install
or
- Delete a custom user after having created for example a template with it

##### EXPECTED RESULTS

The user would get deleted

##### ACTUAL RESULTS

The UI returns an error 500 and `awx_web` shows 
```sql
IntegrityError: update or delete on table "auth_user" violates foreign key constraint "main_unifie
djobtemplate_created_by_id_1f5fadfa_fk_auth_user_id" on table "main_unifiedjobtemplate"
DETAIL:  Key (id)=(2) is still referenced from table "main_unifiedjobtemplate".
```

**Comment by ryanpetrello** [comment]
@kedare we've just released 1.0.7, which we believe resolves the underlying issue here. You can try it out here: https://github.com/ansible/awx/releases/tag/1.0.7

Let us know if you're still seeing this issue after installing the latest awx - thanks!
