### ISSUE TITLE
Re-run jobs on failed host not working

### ISSUE THREAD

**Issue by seansabour** [ansible/awx#1805]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
When a template job fails and you double click the icon and choose Relaunched on `Failed` it triggers a new job but doesn't limit to the failed host, it just re-runs job on all hosts.
 
##### ENVIRONMENT
* AWX version: 1.0.5
* AWX install method: docker on linux
* Ansible version:  2.5.0
* Operating System: Linux
* Web Browser: Firefox 59.0.2 (64-bit)

##### STEPS TO REPRODUCE

1. Create a template and execute a template with a task that will fail on a given host.
2. Double click Launch Icon and choose `Failed`
3. Notice it runs on all hosts again.

##### EXPECTED RESULTS

To run only on the failed hosts.

##### ACTUAL RESULTS

Runs on all hosts.

##### ADDITIONAL INFORMATION

I do pass my hosts via extra variables, not sure if that's causing the issue, but i would i assume the limit would take a subset of those hosts.

**Comment by AlanCoding** [comment]
> I do pass my hosts via extra variables, not sure if that's causing the issue

What do you mean by this?

This feature should work fine with your providing a custom limit for the original job template run. The limit for the 2nd run it gets from the playbook_on_stats at the end of the job, so you should see the relaunched job run against those failed hosts referenced in the playbook summary.

**Comment by seansabour** [comment]
Sorry let me clarify, I run the template against 10 groups and out of the 100 servers let's say that 10 hosts fail. If I try to currently relaunch the job only on failed hosts using the "launch" icon it re-runs the job on all hosts not just the failed hosts.

**Comment by mkempster22** [comment]
I have this issue, I noticed that if i go back out to the jobs screen and then back into the job that i want to rerun it will limit correctly. 

I have this issue on versions 1.0.5.29 & 1.0.2.79

**Comment by seansabour** [comment]
I tried your suggestion and still hitting this issue.

**Comment by AlanCoding** [comment]
Would you be able to show what request data is sent in the POST to the /job_templates/N/launch/ endpoint using your browser's debugging tools?

**Comment by wenottingham** [comment]
Closing, please open if you have the information requested above.

**Comment by jeffpascal** [comment]
Hello !

I'm having the same issue with awx 17.1.0

Payload for relaunch

{passwords_needed_to_start: [], retry_counts: {all: 168, failed: 113}}
passwords_needed_to_start: []
retry_counts: {all: 168, failed: 113}
all: 168
failed: 113

**Comment by jhkcia** [comment]
I also have the same problem with version 17.1.0
