### ISSUE TITLE
[RFE] Support for Group mapping through SAML attributes

### ISSUE THREAD

**Issue by jparrill** [ansible/awx#1806]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - Installer

##### SUMMARY
When you perform the integration between SAML and Ansible Tower/AWX the users that are federated on the SAML side will be created on Tower/AWX, but there is not any way to sync groups. The point of this issue is create a way to Map those groups that exists on SAML server agains the Orgs/Teams on Tower/AWX.

##### ENVIRONMENT
* AWX version: latest
* AWX install method: all
* Ansible version:  a compatible one
* Operating System: Linux
* Web Browser: N/A

##### STEPS TO REPRODUCE

To perform the integration with SAML you must put the correct JSON definition on Authentication field regarding to Tower/AWX Configuration.

The point is that now you could Map users to a Team/Org using regex like this:

```json
SOCIAL_AUTH_TEAM_MAP = {
  "My Team": {
    "organization": "Test Org",
    "users": ["/^[^@]+?@test\.example\.com$/"],
    "remove": True,
  },
  "Other Team": {
    "organization": "Test Org 2",
    "users": ["/^[^@]+?@test\.example\.com$/"],
    "remove": False,
  },
}
```

But the point is to create a way to use a SAML attribute comming from the IDP to be mapped against the Orgs/Tems on Tower/AWX, something like this:

```json
{
 "Default": {
  "users": true
 },
 "Systems Engineering": {
  "users": true,
  "admins": [
   "groups.tower-admin"
  ],
  "remove_admins": false,
  "remove_users": false
 }
}
```

The content of groups array is:
```
groups = ['tower-admin', 'group1', 'group2']
```

##### EXPECTED RESULTS

Create a Team/Org that maps with the groups which comes from SAML attributes

**Comment by jparrill** [comment]
Reviewing I see this other issue: https://github.com/ansible/awx/pull/1576, it is that I look for.

**Comment by wenottingham** [comment]
Closing as a dup of #1576
