### ISSUE TITLE
Scrolling issue on the job progress page on vertical screens

### ISSUE THREAD

**Issue by sysblade** [ansible/awx#1807]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When uing a vertical screen, the job log appear not on the right but down after the job property, the auto follow of the logs make it impossible to scroll up, it is automatically scrolled down every few miliseconds.

##### ENVIRONMENT
* AWX version: AWX 1.0.5.31
* AWX install method: Docker on Linux
* Ansible version:  2.5.1
* Operating System: Docker on Centos Atomic
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Use a vertical screen or resize the window to enable the responsive design, start any job producing more than a few 10's lines of logs, try to scroll up.

##### EXPECTED RESULTS

To be able to scroll up.

##### ACTUAL RESULTS

The view is stuck at the bottom of the window, because of the log autofollow.

**Comment by jakemcdermott** [comment]
resolved by https://github.com/ansible/awx/pull/2457

**Comment by jakemcdermott** [comment]
This should be resolved in the latest awx release.
