### ISSUE TITLE
foreman.py dynamic inventory script for Red Hat Satellite 6 not loading Host Collections as groups

### ISSUE THREAD

**Issue by jamesfreeman959** [ansible/awx#1808]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
foreman.py dynamic inventory script for Red Hat Satellite 6 not loading Host Collections as groups

##### ENVIRONMENT
* AWX version: 1.0.5.24
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: AWX running on CentOS 7, browser accessing UI from Windows 7u
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Create a new Inventory in AWX UI
2. Add a new Source, type Red Hat Satellite 6
3. Associate Red Hat Satellite 6 credentials (including hostname) with new Inventory Source
4. Add new Source Variable, contents:

```
---
want_hostcollections: True
```

5. Save the new Inventory Source
6. Sync new Inventory Source

##### EXPECTED RESULTS

Inventory defined above is populated from Satellite 6 server, with Host Collections included as groups for the Hosts.

##### ACTUAL RESULTS

Inventory is populated, but Host Collections are not retrieved from the Satellite 6 server - dynamic inventory script behaves like want_hostcollections=False (which is the default)

**Comment by smossber** [comment]
Also see this issue.
When adding some debugging to the foreman.py script and basically printing the temporary foreman.ini, I see that all source variables are passed under to the [foreman] section, when want_hostcollections should go under [ansible]. 

 17.178 ERROR  [ERROR]: Print Content of tmp FOREMAN_INI configuration: [foreman] ssl_verify 17.178 ERROR = False host_filters = lifecycle_environment="test"  url = https://satellite.example.com user = svc-awx 17.178 ERROR password = password  [ansible] group_patterns = [] 17.178 ERROR want_facts = True group_prefix = foreman_  [cache] path = /tmp max_age = 0 17.178 ERROR group_pattern: [] group_prefix: foreman_ want_hostcollections: True

Get this output by adding:
        if env_value is not None:
            with open(os.path.expandvars(env_value), 'r') as fin:
                print("Print Content of tmp FOREMAN_INI configuration: %s" % fin.read(), file=sys.stderr)
            self.config_paths.append(os.path.expanduser(os.path.expandvars(env_value)))

at https://github.com/ansible/awx/blob/617d6a8cf498545e72a60a8d46f56992f06303a0/awx/plugins/inventory/foreman.py#L74

This would also mean that nothing in the [ansible] section of the ini file can be overridden.

**Comment by wenottingham** [comment]
This could be adjusted in tasks.py where these variables are passed.

**Comment by smossber** [comment]
Thanks for pointing out the file! 
I see now that only satellite6_group_patterns and satellite6_group_prefix  is looked for, and that it's added to the [ansible] section when picked up. 
So my previous comment is a bit off! 

Guess it's just a matter of adding another key in https://github.com/ansible/awx/blob/0bbc08e5878d41304c4cb6576f1b8d0608658c0c/awx/main/tasks.py#L1853-L1859

I could give that a go

**Comment by smossber** [comment]
Btw, any reason why the keys are named with the satellite6_* prefix? 
Not very intuitive as the foreman.ini doesn't use it? 
Doesn't look like the inventories looks for prefixes either.

**Comment by dverbeek84** [comment]
@wenottingham I think you can close this one. works fine on the last release 13.0.0

**Comment by wenottingham** [comment]
Thanks, will do.
