### ISSUE TITLE
Unable to provide any extra vars in job template

### ISSUE THREAD

**Issue by grahamneville** [ansible/awx#1816]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Unable to provide any extra vars in job template

##### ENVIRONMENT
* AWX version: 1.0.6.0
* AWX install method: docker on linux
* Ansible version:  2.5.2

##### STEPS TO REPRODUCE

Create a new job template

##### EXPECTED RESULTS

Able to provide extra vars

##### ACTUAL RESULTS

unable to enter any extra vars

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/19539695/39382883-a62b738a-4a56-11e8-87f1-2907f9d89260.png)

**Comment by ryanpetrello** [comment]
Do you see any Javascript errors in your browser console?  I'm having trouble reproducing this one on a fresh install.

**Comment by grahamneville** [comment]
So it seems this is working again, not sure whats changed

**Comment by ryanpetrello** [comment]
Let us know if you continue to see issues.
