### ISSUE TITLE
Bundle `pexpect` package

### ISSUE THREAD

**Issue by sumkincpp** [ansible/awx#1818]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - AWX installation, docker images

##### SUMMARY
Add `pexpect` support to AWX docker images, so expect module will work

##### ADDITIONAL INFORMATION

1. [Dockerfile.j2](https://github.com/ansible/awx/blob/devel/installer/roles/image_build/templates/Dockerfile.j2) with linked requirements
2. [/requirements](https://github.com/ansible/awx/tree/devel/requirements) - python requirements

**Comment by wenottingham** [comment]
This can be done by sending a PR that adjusts requirements_ansible.in

**Comment by wenottingham** [comment]
see #1895 - thanks!
