### ISSUE TITLE
[1.0.6] Displayed projects base path does not match project_data_dir in installer/inventory and cannot be changed later in Settings

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/awx#1822]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - web

##### SUMMARY
Projects base path displayed in "Projects/+ADD" page does not match <some/other/projects/path> set during awx build.
It is impossible to modify the default projects base path to anything else than```/var/lib/awx/projects```. 

##### ENVIRONMENT
* AWX version: tag 1.0.6
* AWX 1.0.5 install method: docker/docker-compose on linux
* Ansible version: v2.5.2 (from PyPi)
* Operating System: Ubuntu 17.10
* docker-ce ```18.04.0~ce~3-0~ubuntu``` (from official docker PPA)
* docker==3.3.0
* docker-compose==1.21.1
* requests==2.18.1

##### STEPS TO REPRODUCE

```
$ git checkout 1.0.6
$ git checkout -b actionmystique_build
$ sed -i 's|#project_data_dir=/var/lib/awx/projects|project_data_dir=<some/other/projects/path>|g' installer/inventory
$ cd installer
$ ansible-playbook -i inventory install.yml
```

##### EXPECTED RESULTS
Projects base path displayed in "Projects/+ADD" page should match <some/other/projects/path>.
It should be possible to modify that path in the GUI.

##### ACTUAL RESULTS
Projects base path displayed in "Projects/+ADD" page is always the default path ```/var/lib/awx/projects```:
![displayed projects base path](https://user-images.githubusercontent.com/13176858/39422915-d951c99c-4c6f-11e8-92f1-9e340d701628.png)

The System Settings has no option to change that path, or am I missing something?
![system settings](https://user-images.githubusercontent.com/13176858/39423069-8421fa18-4c70-11e8-97d3-bf9892f4984e.png)

**Comment by wenottingham** [comment]
That's not how this works - the project data dir you pass at container instantiation is mounted as a volume at /var/lib/awx/projects inside the container.
