### ISSUE TITLE
Inventory prompt on lauch broken

### ISSUE THREAD

**Issue by aperigault** [ansible/awx#1824]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
As you can see on my screenshot, when I select an inventory I can't click on ``next``.

##### ENVIRONMENT
* AWX version: 1.0.6.1
* AWX install method: docker on linux
* Ansible version: 2.5.2
* Operating System: Ubuntu
* Web Browser: Tested on Firefox and Chromium (latest versions)

##### STEPS TO REPRODUCE

Lauch a job template with ``prompt on lauch`` ticked on inventory field.

![screenshot from 2018-04-30 15-31-52](https://user-images.githubusercontent.com/5754674/39430295-bae4b3ca-4c8d-11e8-833e-0b2533f92a4a.png)

**Comment by cesan3** [comment]
I see this issue as well. Bypassed by scheduling/triggering jobs via the api or using tower-cli

**Comment by adam-j-turner** [comment]
I see this with 1.0.6.0 as well

**Comment by aperigault** [comment]
Someone can help me to fix it ?
I use this feature in many job templates and I think i'm not the only one.

**Comment by jakemcdermott** [comment]
👋 Hello. Thanks for filing this issue. 

This is fixed downstream - it'll be resolved once we merge the associated code changes into awx.

**Comment by aperigault** [comment]
Oh good! Thanks.
Can I test the patch ?

**Comment by cesan3** [comment]
This bug is annoying and causes the UI to be useless to launch a job. Can you give us the patch?, ETA on when the merge will happen?

**Comment by trogeat** [comment]
same same, can i try the patch ?
