### ISSUE TITLE
latest postgres build missing /usr/bin/python symbolic link

### ISSUE THREAD

**Issue by akcrisp** [ansible/awx#1829]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY
I believe you guys use upstream image - however we note the python seems to have been updated to python3 and a synbolic link is missing from /usr/bin/python3 to /usr/bin/python.

Last week it had python 2.7 installed and it was present.

We found that running a backup against it via ansible playbook (gathering facts) now fails without it.

Not sure if you want to pass this onto the guys doing the postgres container build.

##### ENVIRONMENT
* AWX version: 1.0.5.32
* AWX install method: docker on linux
* Ansible version:  2.5.2-1
* Operating System: RHEL 7.4
* Web Browser: Chrome

##### STEPS TO REPRODUCE

run a playbook against postgres host. 

##### EXPECTED RESULTS

gather facts = ok

##### ACTUAL RESULTS

fatal: /usr/bin/python not found

##### ADDITIONAL INFORMATION

work around - create link - commit the docker container - all now works.

**Comment by wenottingham** [comment]
What's the specific PG container image/hash you're looking at?

**Comment by akcrisp** [comment]
Will check tomorrow

**Comment by akcrisp** [comment]
Bill just built very latest awx from scratch with brand new Postgres container and there’s still no /usr/bin/python link.

There is links for python3 to python3.5

Is this because they have removed python 2.7 ??

Andy

**Comment by wenottingham** [comment]
Yes, this is due to the upstream postgres container changing; we are not looking to override this at this time.
