### ISSUE TITLE
ps

### ISSUE THREAD

**Issue by tmckinne** [ansible/awx#1830]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by wenottingham** [comment]
Closing (empty report)
