### ISSUE TITLE
RFE: Assign a Tower team to multiple Tower organization

### ISSUE THREAD

**Issue by cesarfn4** [ansible/awx#1833]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Be able to assign a Tower team to multiple Tower organization

##### ENVIRONMENT
* AWX version: any

**Comment by wenottingham** [comment]
This is best done with mappings in your authentication provider configuration - by matching on attributes, you can put the 'same' logical team in multiple organizations.
