### ISSUE TITLE
tower-cli installation in awx

### ISSUE THREAD

**Issue by RohitUppal** [ansible/awx#1835]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
tower-cli not able to connect to host

##### ENVIRONMENT
RHEL 7.4

##### STEPS TO REPRODUCE

1. Install AWX Community edition in docker
2. Copy towe cli tar ansible-tower-cli-3.2.1.tar inside awx_web container
    docker cp /ansible-tower-cli-3.2.1.tar awx_web:/
3. Attach to awx_web container and extract ansible cli tar.
4. Run setup script to install tower-cli
    ./setup build
    ./setup install
5. Tun tower-cli to update user and password
   tower-cli config username admin
   tower-cli config password <password>
   tower-cli config host <hostip of the host on which docker containers are running>
6. Run tower-cli command to get list of templates
    
tower-cli job_template list
Error: There was a network error of some kind trying to connect to Tower.

The most common  reason for this is a settings issue; is your "host" value in `tower-cli config` correct?
Right now it is: "<ip>".

Scenario here is I have created a manual project in awx at location /var/lib/awx/projects/<projectname>
Project is visible in awx GUI
Playbook already uploaded in Manual project
Create template using the manual project .

I already have a json file for survey, which I want to upload to the created job template using tower-cli

I have already copied survey json in awx_web container
tower-cli job_template modify --name="<job template name>" --survey-spec=@/<Survey>.json --survey-enabled=true 

My question here is

1. On which container i should install tower-cli
2. What should be the host ip to update in tower-cli config host <IP?>

**Comment by ryanpetrello** [comment]
@RohitUppal questions about how to use AWX are more suited for the mailing list (https://groups.google.com/d/forum/awx-project) or our IRC room (#ansible-awx on Freenode).

> On which container i should install tower-cli

If you're trying to run `tower-cli` from within a playbook, you'll need to install it in the `awx-celery` container (which is where `ansible-playbook` processes actually run).

> What should be the host ip to update in tower-cli config host <IP?>

The IP should be the IP address of whatever AWX you're attempting to talk to.  If you're attempting to run a playbook that interacts with the AWX where the playbook is running, AWX exposes the IP in an environment variable, `AWX_HOST`.

You'll also need to manage credentials for the AWX you're interacting with (the username and password) - you might try creating an Ansible Tower credential and attaching it to your Job Template:

![screen shot 2018-05-02 at 10 28 40 am](https://user-images.githubusercontent.com/214912/39529002-9c81288e-4df3-11e8-82cc-ba6b4914863c.png)

By using one of these credentials, the username and password you provide will be injected into two environment variables you can use, `TOWER_USERNAME` and `TOWER_PASSWORD`.  The `tower-cli` tool uses these environment variables by default, so there shouldn't be a need to call `tower-cli config`:

https://docs.ansible.com/ansible-tower/latest/html/towerapi/tower_cli.html#set-configuration-with-tower-cli-config
