### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by nolfb** [ansible/awx#1839]
How do you tell what the version of AWX you are running?  Is there plans to update the current version?
thanks

##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by wenottingham** [comment]
There's an 'about' link at the bottom.  In any case, this is not a bug report/RFE.
