### ISSUE TITLE
Pagination is not working at Jobs page.

### ISSUE THREAD

**Issue by zhangtiny123** [ansible/awx#1841]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

No matter what page number you choose, the jobs displayed on the page is the newest ones. 
I checked the data returned by api and api parameters, seems it's OK .
So the problem should be at UI level.

##### ENVIRONMENT
* AWX version: 1.0.5
* AWX install method: docker on linux
* Ansible version:  1.0.5
* Operating System: Linux
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

1. Go to Jobs page
2. You should have jobs more than one page could display.
3. Then choose second page or others.
4. You should see the results displayed is still the previous ones.

##### EXPECTED RESULTS

We should see the previous jobs, data should be updated.

##### ACTUAL RESULTS

Never update.

**Comment by jaredevantabor** [comment]
This is fixed in devel now.
