### ISSUE TITLE
Smart inventories don't update on launch

### ISSUE THREAD

**Issue by abelboldu** [ansible/awx#1842]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
The 'Update on launch' behaviour for inventories does not work when using a Smart inventory.

##### ENVIRONMENT
*  AWX 1.0.5.32
* AWX install method: docker on linux
* Ansible version:  2.5.1
* Operating System: Ubuntu 16.04
* Web Browser: Webkit 

##### STEPS TO REPRODUCE

- Mark the 'Update on launch' option on a inventory source.
- Create a Smart inventory based on the previous one.
- Run a job associated to the smart inventory.
- Do some changes on the smart inventory (like deleting/adding a node).
- Run same job again.

##### EXPECTED RESULTS

When the job runs, the parent inventory gets updated, and then the smart directory too.

##### ACTUAL RESULTS

When the job runs, the inventory is not updated. 
I.E.: Job fails if some host is now missing.

##### ADDITIONAL INFORMATION

Using digitalocean.py script to create the dynamic inventory.

**Comment by wenottingham** [comment]
This is expected, that does not propagate to the different inventories that a smart inventory pulls from.

**Comment by abelboldu** [comment]
I don't see the point on Smart Inventories when using them on a dynamic fashion then.

In our use case, we use the to select a subset of the global inventory (like selecting droplets by tag name) but then it's useless if it's not refreshed at every job run, just for the record...
