### ISSUE TITLE
Docker image with tag 1.0.5 includes an old ansible version

### ISSUE THREAD

**Issue by Reamer** [ansible/awx#1843]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Docker Image

##### SUMMARY
The newest docker image with name awx_task and tag 1.0.5 includes ansible in version 2.5.1. It is possibly to update ansible in awx_task image with tag 1.0.5? Ansible 2.5.x has serveral bugfixes. For example: https://github.com/ansible/ansible/issues/39004

**Comment by sujiar37** [comment]
@Reamer  Use custom virtual env which can be associated in organization and job templates. Check out this for more details 

https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md

**Comment by wenottingham** [comment]
The image for a particular version uses what is current as of the time it was built; we are not updating it for new ansible versions as they come out.
