### ISSUE TITLE
Add password strength policy enforcement

### ISSUE THREAD

**Issue by ghost** [ansible/awx#1846]
##### ISSUE TYPE
 - Feature Idea
 
##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Allow admins to set and enforce a password strength policy that applies to all users when updating passwords

##### ENVIRONMENT
* AWX version: 1.0.6

##### STEPS TO REPRODUCE

Currently, password strength requirements can be enforced only on externally-authenticated accounts.  This enhancement would allow the enforcement of strength requirements on local users' passwords.

**Comment by wenottingham** [comment]
This is best done in the external account provider, as noted.

**Comment by drevatt** [comment]
This is a very important security measure to implement. An additional possibility is whether you can exclusively implement, say LDAP / AD authentication, which enforces password complexity and expiration requirements, and disallow other authentication mechanisms. We could perhaps live with enforcing it via AD if we could technically disallow other forms of authentication within Ansible/AWX.

**Comment by wenottingham** [comment]
There is a knob that disables the ability of non-superusers to add users - this effectively allows you to do this.

**Comment by drevatt** [comment]
Thank you for the quick response. Now when you say a "non-superuser", how would you define that term? For instance, if I have an account that is in the sudoers list that elevates them to effectively a superuser, I assume they would still be allowed to add users. Or do you literally mean the local host root account? And lastly, what exactly is that "knob" to tweak?

**Comment by wenottingham** [comment]
non-superuser: anyone who is not a 'system administrator' in AWX.
knob: the 'MANAGE_ORGANIZATION_AUTH' setting in AWX (label: "Organization Admins Can Manage Users and Teams")

**Comment by daczka92** [comment]
> non-superuser: anyone who is not a 'system administrator' in AWX.
> knob: the 'MANAGE_ORGANIZATION_AUTH' setting in AWX (label: "Organization Admins Can Manage Users and Teams")

does it really work? still normal users can create users. I think this is to allow superusers to create users for any organisation.

btw anything changed with this? how to change policy about creating users or to require more complex passwords?

**Comment by matburt** [comment]
Not yet which is why this issue is still open.

**Comment by wenottingham** [comment]
https://github.com/ansible/awx/pull/9999
