### ISSUE TITLE
AWX server not accepting token for auth

### ISSUE THREAD

**Issue by pkaramol** [ansible/awx#1854]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY
Keep getting back no credentials provided error when posting with `Authorization` token in the `POST` headers

##### ENVIRONMENT
* AWX version: 1.0.4.130
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.5.0
* Operating System: `Ubuntu 16.04.04 LTS`
* Web Browser: `Firefox`

##### STEPS TO REPRODUCE

1. Log in to `UI`
2. Perform via the UI the following `POST `to `/api/v2/tokens/`

```
{
    "description": "",
    "application": null,
    "scope": ""
}
```

3. From the response, use the `token` field in the subsequent sample `POSTS`:

__A__:
```
http://<my-tower-url>/api/v2/job_templates/10/launch/

Headers:
Content-Type:application/json
Authorization:token

{
    "inventory": "inventoryname",
    "verbosity": 0,
    "extra_vars": {
        "var1": "somevar1",
        "var2": "somevar2",
        "var3": "somevar3",
        "var4": "somevar4",
        "var5": "somevar5"
    }
}
```

__B__:

```
http://<my-tower-url>/api/v2/job_templates/10/launch/

Headers:
Content-Type:application/json
Authorization:Token token

{
    "inventory": "inventoryname",
    "verbosity": 0,
    "extra_vars": {
        "var1": "somevar1",
        "var2": "somevar2",
        "var3": "somevar3",
        "var4": "somevar4",
        "var5": "somevar5"
    }
}
```

__C__:

(without usage of the `token` and the `Authorization` header)

```
http://<my-tower-url>/api/v2/job_templates/10/launch/

Headers:
Content-Type:application/json

{
    "username": "myusername",
    "password": "mypass",
    "inventory": "inventoryname",
    "verbosity": 0,
    "extra_vars": {
        "var1": "somevar1",
        "var2": "somevar2",
        "var3": "somevar3",
        "var4": "somevar4",
        "var5": "somevar5"
    }
}
```

##### EXPECTED RESULTS

Job execution (or at least some complaining about the parameters)

##### ACTUAL RESULTS

> {"detail":"Authentication credentials were not provided."}

**Comment by ryanpetrello** [comment]
@pkaramol awx currently gives two options for authentication: reusable OAuth2 tokens or HTTP basic auth (username and password provided on _every_ request).

This link has some examples on how to generate and use an OAuth2 Personal Access Token:

https://github.com/ansible/awx/blob/devel/docs/auth/oauth.md#using-oauth-2-token-system-for-personal-access-tokens-pat

If you want to use basic HTTP auth, you'll have to specify it in an `Authorization` header, not the request body in JSON format:

`curl -u user:pass -X POST https://my-tower-host.example.org/api/v2/job_templates/10/launch/`
