### ISSUE TITLE
Missing playbooks in Job Template

### ISSUE THREAD

**Issue by abatista75** [ansible/awx#1859]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When I edit a "Job Template", the field "Playbook" does not show all the playbooks, but only some of them.
The "Project" is updated: The Git revision is the latest one, and all the playbook files are fetched locally.

##### ENVIRONMENT
* AWX version: 2.5.2
* AWX install method: docker on linux
* Ansible version:  1.0.6.5
* Operating System: Debian 9
* Web Browser: Chrome 66

##### STEPS TO REPRODUCE
- Create or edit a job template

##### EXPECTED RESULTS
I would expect to see all the playbooks (*.yml files).

##### ACTUAL RESULTS
Only some files are displayed in the "Playbook" dropbox field.

##### ADDITIONAL INFORMATION
If I edit one of the displayed playbooks and include one of the missing playbooks (`  - include: playbooks/dump.yml`), it works:

**Comment by wenottingham** [comment]
There is a parser that ensures the .yml file looks like a playbook.

What do the playbooks that don't show up look like?

**Comment by abatista75** [comment]
That's right... The "hidden" playbooks aim at being included in another YAML file. So the header `- hosts: all` are deliberately missed.

A short explanation in the UI would be nice.
