### ISSUE TITLE
Please add workflow type of 'after all successful'

### ISSUE THREAD

**Issue by gamuniz** [ansible/awx#1862]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI
 

##### SUMMARY

It would be nice to have another type of workflow status to add to always/ success/ failed which ran only if all other job templates were successful.

##### ENVIRONMENT
* AWX version: latest
* AWX install method: n/a
* Ansible version:  2.5.2
* Operating System: RHEL7
* Web Browser: Chrome

**Comment by wenottingham** [comment]
covered here: https://github.com/ansible/awx/issues/284
