### ISSUE TITLE
awx ui support chinese

### ISSUE THREAD

**Issue by Colstuwjx** [ansible/awx#1864]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

It'd better to support show Chinese language ui for awx, I'm happy to contribute this, but can NOT find awx ng sourcecode :(

Thanks.

**Comment by wenottingham** [comment]
Code is all at https://github.com/ansible/awx/ - see `awx/ui/po` and `awx/locale/<locale>/LC_MESSAGES/django.po`.

**Comment by shanemcd** [comment]
We had had Chinese translations for a while, closing.
