### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by runtman** [ansible/awx#1865]
Is it possible that the notifier rather than only having (Success, failure) we could get (changes) added?

I don't really care if my job succeeds, but I do care if it succeeded and tasks "changed" parts of the system.

Thanks.

**Comment by wenottingham** [comment]
It's based off the job status, so... no. We can work to have it include more of the job summary that would let you deduce it.

See #79.

**Comment by runtman** [comment]
Perfect, thanks!
