### ISSUE TITLE
ERROR while executing Demo Template after AWX installation on RHEL 7.4

### ISSUE THREAD

**Issue by Rohit-Uppal** [ansible/awx#1867]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
ERROR when Demo Job Template is executed

##### ENVIRONMENT
* AWX version: Latest
* AWX install method: Docker
* Ansible version:  2.5.2
* Operating System: RHEL 7.4
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Install AWX on RHEL 7.4 using Docker.
2. Run Demo Job Template which is a helloworld.yml

Screen shot attached
![awx_bug](https://user-images.githubusercontent.com/38099282/39860705-dff9684c-545b-11e8-834b-ac7ae5793884.PNG)

##### EXPECTED RESULTS

[ERROR] should not come

**Comment by ryanpetrello** [comment]
@Rohit-Uppal this is a bug in Ansible 2.5.1 and 2.5.2 itself:

https://github.com/ansible/ansible/issues/39007
