### ISSUE TITLE
Jobs in progress cannot be cancelled and never complete

### ISSUE THREAD

**Issue by ewortzman** [ansible/awx#1870]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
Jobs in progress cannot be cancelled and never complete

##### ENVIRONMENT
* AWX version: 1.0.6.5
* AWX install method: docker on linux
* Ansible version:  2.5.2
* Operating System: CentOS 7
* Web Browser: Chrome on Windows 7

##### STEPS TO REPRODUCE

1. create a project, add credentials, and create a job template
2. attempt to spin up a job from the template

##### EXPECTED RESULTS

the job should begin, execute fully, and terminate.  The job should also be able to be cancelled.

##### ACTUAL RESULTS

occasionally, the job will simply never start.  Other times, the job will start but never complete.  Attempting to cancel the job, either from the individual job page or from the jobs list page, simply does nothing.

**Comment by stefan-wegener** [comment]
I am using the same version. I have no issues while starting jobs, but cancelling currently running jobs is also not possible for me.

**Comment by kavink** [comment]
Were you able to figure out a workaround or something ? Seeing the same issue.

**Comment by jspitzen** [comment]
Same here, I am also not able to cancel it through the `tower-cli`

**Comment by ryanpetrello** [comment]
@ewortzman @kavink @jspitzen we've just released 1.0.7, which we believe resolves the underlying issue here. You can try it out here: https://github.com/ansible/awx/releases/tag/1.0.7

Let us know if you're still seeing this issue after installing the latest awx - thanks!
