### ISSUE TITLE
Strange error without failure with sudo

### ISSUE THREAD

**Issue by abatista75** [ansible/awx#1871]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When running a playbook, AWS displays the following at the beginning (with debug enabled):

```
Enter passphrase for /tmp/awx_797_fEcOyW/credential_2: |  
-- | --
  | 2 | Identity added: /tmp/awx_797_fEcOyW/credential_2 (/tmp/awx_797_fEcOyW/credential_2) |  
  | 3 | ansible-playbook 2.5.2 |  
  | 4 | config file = /etc/ansible/ansible.cfg |  
  | 5 | configured module search path = [u'/usr/lib/python2.7/site-packages/awx/plugins/library'] |  
  | 6 | ansible python module location = /usr/lib/python2.7/site-packages/ansible |  
  | 7 | executable location = /usr/bin/ansible-playbook |  
  | 8 | python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] |  
  | 9 | Using /etc/ansible/ansible.cfg as config file |  
  | 10 | SUDO password: |  
  | 11 | [ERROR]: |  
  | 12 |   |  
  | 13 | Parsed /tmp/awx_797_fEcOyW/tmpbTYxC1 inventory source with script plugin |  
  | 14 | statically imported: /var/lib/awx/projects/_6__playbooks_inventories/playbooks/my_playbook.yml
```

The line 11 shows an error in red, but it is not blocking, as AWX executes the rest of the playbook without any issue.

##### ENVIRONMENT
* AWX version: 2.5.2
* AWX install method: docker on linux
* Ansible version:  1.0.6.5
* Operating System: Debian 9.4
* Web Browser: Chrome 66

##### STEPS TO REPRODUCE

When running any playbook.

"Enable Privilege Escalation" is not set in the job template.

##### EXPECTED RESULTS

No error should be displayed

##### ACTUAL RESULTS

```
SUDO password:
[ERROR]:
```

**Comment by wenottingham** [comment]
Ansible bug, will be fixed in 2.5.3.

https://github.com/ansible/ansible/issues/39007
