### ISSUE TITLE
adding new machine credential is missing username/password/ssh key info

### ISSUE THREAD

**Issue by glenpekarcsik** [ansible/awx#1872]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When trying to create a machine credential in the UI, the username, password, and ssh keys boxes are not shown.

##### ENVIRONMENT
* AWX version: 1.0.5.32
* AWX install method: openshift
* Ansible version:  2.5.1
* Operating System:
* Web Browser: Chrome

##### STEPS TO REPRODUCE
- create a new credential
- select machine as the credential type
- click save
- there is no next screen that enables you to enter the username, password, ssh keys, etc...

##### EXPECTED RESULTS
the ability to enter in a new machine credential along with the username, password, ssh key.

##### ACTUAL RESULTS
there is no way to enter in a username/password/ssh key for a machine credential.

**Comment by stefan-wegener** [comment]
Using AWX 1.0.6.5 with Ansible 2.5.2 I can not reproduce this error. Maybe you can upgrade your instance to a newer version and try it again? 
Hint/Warning: When upgrading from 1.0.5 to 1.0.6 you need to backup your data!

**Comment by glenpekarcsik** [comment]
I've tried 1.0.6 last week and ran into an issue with LDAP.  I was unable to login to AWX using LDAP.  I was receiving the following error:

[pid: 34|app: 0|req: 60/160] 10.1.17.1 () {50 vars in 2301 bytes} [Tue May  8 15:49:01 2018] GET /api/login/ => generated 5676 bytes in 61 msecs (HTTP/1.1 200) 8 headers in 360 bytes (1 switches on core 0)
2018-05-08 15:49:01,384 WARNING  awx.conf.settings The current value "{u'member_attr': u'member', u'name_attr': u'cn'}" for setting "AUTH_LDAP_GROUP_TYPE_PARAMS" is invalid.
Traceback (most recent call last):

If this error is fixed in the latest build of 1.0.6 I will try 1.0.6.

**Comment by wenottingham** [comment]
Closing this as fixed in 1.0.6 - we are not seeing this here in the current version.
