### ISSUE TITLE
Add a section on contributing translations to CONTRIBUTING.md

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1879]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME
- none of the above

##### SUMMARY

The contributing docs should explain how to contribute translations.

##### ENVIRONMENT
* AWX version: current

##### STEPS TO REPRODUCE

1. see https://github.com/ansible/awx/issues/1864
2. note we don't document this

**Comment by aoyawale** [comment]
interested in this for esp. Some of the wording in awx/ui/po and https://github.com/ansible/awx/blob/devel/awx/locale/es will need to be changed or discussed further.

**Comment by yousong** [comment]
[Release note of ansible tower](https://docs.ansible.com/ansible-tower/latest/html/release-notes/supported_locales.html) indicates that it has support for a large number of locales and many of them is not included in the awx code base here (`awx/locales/`, `awx/ui/po/`).

I am wondering what's the license status of those translation files and is it legal/viable/possible to import those into awx project here.  Sorry if this seems to be a dumb question

**Comment by ryanpetrello** [comment]
@yousong,

> Ansible Tower supports the following locales for UTC-friendly date and time information.

I think this document is referring to support for locale-specific date/time formatting, not _actual_ full language translation.

The languages you see with translation files at https://github.com/ansible/awx/tree/devel/awx/locale are what AWX/Tower support in terms of language translation.
