### ISSUE TITLE
Feature: Open Service Broker API

### ISSUE THREAD

**Issue by victorock** [ansible/awx#188]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Extend API to Support Open Service Broker API and Ansible Playbooks Bundle.

Ref: 
https://github.com/openshift/ansible-service-broker/blob/master/README.md

**Comment by matburt** [comment]
This seems like something the openshift team should do

**Comment by j00bar** [comment]
I think it need to be clarified to a _large_ extent what "support" means in the report's mind.

**Comment by wenottingham** [comment]
Yeah - this isn't something we would do outside of conjunction with the OpenShift team. It's not clear this makes sense to be in AWX itself.

**Comment by j00bar** [comment]
I mean, I'm all for it and we should totally work together on how to better support each other's efforts - just... what does "extend" and "support" look like? @victorock, thoughts? @matburt, probably should be `needs_info`.

**Comment by matburt** [comment]
Going to close this one for the time being, we'll file follow up enhancements when we've decided more on the interaction points between the two projects.
