### ISSUE TITLE
Add secure flag to session cookie to require that it be sent only over secure connection

### ISSUE THREAD

**Issue by ghost** [ansible/awx#1881]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
The session token cookie can currently be sent by a browser over an unencrypted connection, potentially exposing the token to a third party.

##### ENVIRONMENT
* AWX version: 1.0.6

##### STEPS TO REPRODUCE

Setting a flag on the cookie to require that it be sent by the browser only over a secure connection can mitigate that risk of a third party obtaining the token.

**Comment by jaredevantabor** [comment]
this will get fixed elsewhere
