### ISSUE TITLE
[RFE] Automatically redirect to External Auth Provider Option

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/awx#1886]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

Implement the ability to automatically redirect users to a specified external authentication provider when accessing the Tower login page rather than selecting a specific provider.

##### ADDITIONAL INFORMATION

This would be for auth providers such as SAML which require a third party authentication method outside of AWX/Tower

**Comment by wenottingham** [comment]
This would only work iff:
a) there is a single external authentication source
b) there are no local users at all

I'm not sure how complex those queries are to do.

**Comment by lah-aaron** [comment]
@wenottingham 
a) No, it is not uncommon to allow automatic redirection to a SSO page. Furthermore, the automatic redirection could be bypassed.
b) No, there should be a link to bypass external authentication. ie. http://example.com?loginType=local

**Comment by gforster** [comment]
This is actually a very important need for me. What can I do to help?

**Comment by walkafwalka** [comment]
@gforster, you could create a pull request.

**Comment by matburt** [comment]
This also covers the scenario where SAML/SSO authentication was already completed at some prior time and the user has a valid login. Rather than requiring the user to click the saml login button we should be able to just redirect to the dashboard via the 2-legged mechanism that would normally take them to the SSO login screen.

**Comment by ryanpetrello** [comment]
@one-t let me know if you're ready to close this.
