### ISSUE TITLE
Add support for certificate authentication for PostgreSQL client connection

### ISSUE THREAD

**Issue by ghost** [ansible/awx#1887]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Add support for client certificate-based authentication to the PostgreSQL service

##### ENVIRONMENT
* Tower 3.2.5

##### STEPS TO REPRODUCE

This would add flexibility to the configuration of the connection, and would allow the storage of a plaintext password on the client side to be avoided.

**Comment by wenottingham** [comment]
-> #709
