### ISSUE TITLE
Two 'cancel' buttons in a dialog window

### ISSUE THREAD

**Issue by vrutkovs** [ansible/awx#1891]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### EXPECTED RESULTS

A window with 'Yes, cancel' and 'No, dismiss' buttons

##### ACTUAL RESULTS
https://imgur.com/weJBLZM

**Comment by wenottingham** [comment]
Fixed already in commit cf0efe969ef52507205d85a60f480650a8116dc2.
