### ISSUE TITLE
Feature Idea: CyberArk Vault credential type

### ISSUE THREAD

**Issue by mpetrive-rh** [ansible/awx#1893]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
In AWX, CyberArk Vault credentials can be injected into the inventory by specifying inventory variables in the UI and using  `cyberarkpassword` lookup plugin in the form:

```
ansible_pass: "{{ lookup('cyberarkpassword', { 'app_id': 'some_id', 'output': 'Password', 'query': '...' }"
```

In AWX, there are a number of "built-in" credential types, to allow for authentication  against hosts.  We would like have a built-in CyberArk Vault credential type for use as a machine credential.  This custom credential could utilize the cyberarkpassword lookup plugin or have a deeper level of integration with the CyberArk credential provider.

**Comment by wenottingham** [comment]
Would need more information as to what that 'deeper level of integration' would be.

I don't think wrapping the lookup plugin makes a lot of sense, as that makes the credential dynamic in a way that credentials aren't. I suspect we'd need an entirely different sort of thing to store this.

**Comment by wenottingham** [comment]
-> https://github.com/ansible/awx/issues/2238
