### ISSUE TITLE
Feature: Select All/Batch Operations

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#19]
AWX Feature Spec - Select All/Batch Operations
==============================================

User Persona
------------
AWX admin/org admin

Use cases
---------
In prior releases, complex filtering and sorting was added throughout AWX,
allowing users to easily see the 5/10/100 items they want to operate on. We
should allow them to easily select some or all of these filtered items at
once, and operate on them.

Example:
* As a user editing my inventory, I want to select all subgroups, or hosts in a group, with a single click, and then delete them/run a command on them/etc.
* As a admin/org admin/user assigning permissions to multiple job templates, or adding permissions for multiple teams, I should be able to select all items that match my filter with a single click to then add permissions.
* As an admin managing job templates, I should be able to select with a single click all items matching my filter, and delete them/launch them/etc.
* As an admin cleaning old job history, I should be able to select with a single click all items matching my filter, and delete them.

This should have proper support for pagination, including:
* selecting all items on the page
* selecting all items that match the filter regardless of pagination

API Considerations
------------------

Likely need support for batched operations, including returning status on
items that have changed.

UI/UX Considerations
--------------------

Likely needs support for refreshing a list properly after batched operations
change multiple items.

Docs
----

QA Suggestions
--------------

Notes
-----

Examples:
- Gmail multiple select and operate
- GitHub issues multiple select and operate

Updates/Changelog
-----------------
2017-09-06: initial/updated version

**Comment by daemenseth** [comment]
Is there some progression on this issue?

**Comment by wenottingham** [comment]
Not currently; when it is there will likely be more updates in-ticket.

**Comment by spsingh1982** [comment]
Any update on this?

**Comment by donnelll** [comment]
Umm...going to ask this again since this is HUGE for us since we offer it as SAAS internally to our customers; "Any Update on this ?"

**Comment by ryanpetrello** [comment]
@donnelll if there's progress made on this, you'll see it here.  Like any other feature or enhancement in open source software, it's a matter of time/priority, and finding somebody to put in the work.

**Comment by bac-w** [comment]
Seems to me the issue has been in place since Sep 2017. When might we reasonably expect the fix?

**Comment by daemenseth** [comment]
Is there any progress on this issues, or have someone a commandline solution for me

**Comment by mili988** [comment]
is there a solution for this? is it possible to delete old jobs from commandline (docker container)?

**Comment by wenottingham** [comment]
The new AWX UI allows for this.
