### ISSUE TITLE
RFE: Feature to copy job templates between clusters

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#1902]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
It would be beneficial for some customers to be able to copy job templates between clusters, such as a test and prod, as opposed to creating a new template once the test job template is ready for promotion.

Similar to #283 but between 2 separate clusters.

**Comment by wenottingham** [comment]
This is what `tower-cli send` and `tower-cli recieve` is for.

**Comment by AlanCoding** [comment]
`tower-cli receive --job_template name_of_your_job_template > save_file.json`

then the send command with that file
