### ISSUE TITLE
RFE: Support openssl public / private keys for api token access

### ISSUE THREAD

**Issue by akcrisp** [ansible/awx#1906]
##### ISSUE TYPE

  - Feature Idea
 

##### COMPONENT NAME
 - API
 

##### SUMMARY
We raised an RFE against redhat (when we was using ansible tower) to have the ability for passwordless access to the api. In awx 1.0.5 this was supposedly delivered with oauth2. However we now discover having looked at it, that you now need a password to get the initial token required for the rest of the api commands to work without a password. This is fundementally not much different to the previous authorisation model and still hinders automation as we now have to deal with a password and storing it in some location that is secure. 

We assumed that having read our requirement and indeed spelt that out on the github ticket (https://github.com/ansible/awx/issues/21) addressing this - that it was understood what we meant. I assumed that the move to oauth2 was to allow openssl public / private keys to be used to enable this. However this hasn't been done. So can someone look into this. 

##### ENVIRONMENT
* AWX version: 1.0.6.8
* AWX install method: docker on linux
* Ansible version:  2.5.3
* Operating System: rhel 7.4
* Web Browser: chrome

**Comment by wenottingham** [comment]
OAuth2 is the standard way to perform this for web applications, and at least  *some* authentication step is required. Certificate-based authentication is not planned.

**Comment by akcrisp** [comment]
I am not saying no authentication - i am merely asking for a non password based method. Sorry but I find it hard to believe you can't see why this is important. You appreciate that automation becomes trickier when your dealing with passwords  - and causes unnecessary grief in the highly audited world I certainly live in.

I'll follow this up with our account team.

**Comment by rooftopcellist** [comment]
OAuth2 _is_ a non password based method for accessing AWX.  Once you have acquired an Access Token, that token can be used from that point forward without a need for using a password (Authenticate *once* to issue the token).  However, you need _some_ form of authentication to acquire this Access Token (via the various grant types specified in the docs).

**Comment by akcrisp** [comment]
Please explain to me how this is any different to the old api method ? You still need to manage passwords whether it’s to get the auth token or get access to api via old method and this point seems to have been missed by those developing the solution. 

I assumed that (having explained the point both on git hub, direct with Redhat when we was using tower and in conference calls with senior management of the ansible business unit ) that you guys would have been looking to use OpenSSL keys to provide that keyless entry to the auth token.

Andy

**Comment by rooftopcellist** [comment]
The difference is that with OAuth2 you only need a username and password to set up your service that interfaces with the API (to issue the token).  This eliminates the need to manage username/password for each request to the API, as you would have had to with the previous api method (through basic authentication).  This allows users to avoid sending their credentials in plaintext with every single API request.

**Comment by ryanpetrello** [comment]
Andy,

As @wenottingham mentioned (https://github.com/ansible/awx/issues/1906#issuecomment-391729988), certificate-based authentication is not currently planned.

> This is fundementally not much different to the previous authorisation model and still hinders automation as we now have to deal with a password and storing it in some location that is secure.

You _don't need_ to store a password:

1.  When you deploy awx, roll an initial, randomized admin password into your deployment process via `tower-manage changepassword some_user`.
2.  Use the newly generated password and the API to generate an OAuth2 token (once).
3.  Store that token and use it for all subsequent API requests.

Unlike the auth tokens in prior versions of awx and Tower, OAuth2 tokens are long-lived, and can be scoped (e.g., to limit read/write permissions).  They're also notably easier for client libraries to deal with (because OAuth2 is a well-known standard, whereas our prior custom auth token implementation was _not_).
