### ISSUE TITLE
Template - "Inventory - Prompt on launch" disables "Next"-button when trying launch template

### ISSUE THREAD

**Issue by stefan-wegener** [ansible/awx#1908]
##### ISSUE TYPE
 - Bug Report
##### COMPONENT NAME
 - UI

##### SUMMARY
When creating a Template with the "Inventory - Prompt on launch"-checkbox, it is not possible to launch the job, because the "Next"-button is always disabled. 

##### ENVIRONMENT
* AWX version: AWX 1.0.6.9
* AWX install method: docker on linux
* Ansible version:  2.5.3
* Operating System: Ubuntu
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Create new Template and check the "Inventory - Prompt on launch"-checkbox. Then try to launch the template.

##### EXPECTED RESULTS

After selecting an Inventory, by clicking on the "Next"-button, get to the launch template page.

##### ACTUAL RESULTS

No matter which Inventories I am selecting, the "Next"-button is always disabled.

##### ADDITIONAL INFORMATION
<img width="957" alt="awx-bug" src="https://user-images.githubusercontent.com/5695658/40482883-79e6fc8a-5f56-11e8-9f6b-4ec64bed6b74.png">
Please note: The some spaces in the shown image are white/empty, as I did not want to show some names.

**Comment by AlanCoding** [comment]
On 1.0.6-301 here, and it appears that the fix put in https://github.com/ansible/awx/pull/1357 has taken effect and this is working correctly.
