### ISSUE TITLE
Can't change  password

### ISSUE THREAD

**Issue by FabianCernota** [ansible/awx#1909]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
HTTP basic auth when trying to change my users password
##### ENVIRONMENT
* AWX version: AWX 1.0.6.9
* AWX install method: docker on linux
* Ansible version:  2.5.2
* Operating System: Debian 9.3
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Login as user -> Try to change Username

##### EXPECTED RESULTS

Only typing the password and save

##### ACTUAL RESULTS
Getting a basic auth dialog when click on save button

**Comment by AlanCoding** [comment]
Have you tried refreshing the page and logging in? Doing that, is the new password in effect, or is the old password still in effect?

**Comment by FabianCernota** [comment]
The new password is in effect, but this strange popup confuse employees at our company

**Comment by rooftopcellist** [comment]
@FabianCernota It sounds like there is a residual cookie hanging around in the browser from an earlier AWX install.  Try deleting your application cookies in the the inspector in the browser (Inspector --> Application Tab --> Cookies (Delete all)).  

Let me know if this fixes it for you.  Also, what version of AWX are you using?

**Comment by rooftopcellist** [comment]
I'm going to go ahead and close this for now.  If you are still having this issue, drop a not in the comments here and I'll reopen.  -- Thanks

**Comment by FabianCernota** [comment]
I never used AWX before our own installation :)
