### ISSUE TITLE
awx/installer/roles/image_build/tasks/main.yml': line 64, column 3

### ISSUE THREAD

**Issue by sicute** [ansible/awx#1913]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

I try build  with command : 
#/awx/installer$ ansible-playbook -i inventory install.yml
ERROR! no action detected in task

The error appears to have been in '/home/ubuntu/awx/installer/roles/image_build/tasks/main.yml': line 64, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Build AWX distribution using container
  ^ here

ubuntu@ip-172-31-13-185:~/awx/installer$ 

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.0.0.2
* Operating System: Ubuntu 
* Web Browser: -

##### STEPS TO REPRODUCE

ubuntu@ip-172-31-13-185:~/awx/installer$ ansible-playbook -i inventory install.yml 
ERROR! no action detected in task

The error appears to have been in '/home/ubuntu/awx/installer/roles/check_vars/tasks/main.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- include_tasks: check_openshift.yml
  ^ here

ubuntu@ip-172-31-13-185:~/awx/installer$ vi ~ubuntu/awx/installer/roles/check_vars/tasks/main.yml 
ubuntu@ip-172-31-13-185:~/awx/installer$ vi ~ubuntu/awx/installer/roles/check_vars/tasks/main.yml 
ubuntu@ip-172-31-13-185:~/awx/installer$ ansible-playbook -i inventory install.yml 
ERROR! no action detected in task

The error appears to have been in '/home/ubuntu/awx/installer/roles/check_vars/tasks/main.yml': line 6, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- include_tasks: check_docker.yml
  ^ here

ubuntu@ip-172-31-13-185:~/awx/installer$ vi ~ubuntu/awx/installer/roles/check_vars/tasks/main.yml 
ubuntu@ip-172-31-13-185:~/awx/installer$ ansible-playbook -i inventory install.yml 
ERROR! no action detected in task

The error appears to have been in '/home/ubuntu/awx/installer/roles/image_build/tasks/main.yml': line 64, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Build AWX distribution using container
  ^ here

ubuntu@ip-172-31-13-185:~/awx/installer$ vi ~ubuntu/awx/installer/roles/check_vars/tasks/main.yml
ubuntu@ip-172-31-13-185:~/awx/installer$ vi ~ubuntu/awx/installer/roles/image_build/tasks/main.yml 
ubuntu@ip-172-31-13-185:~/awx/installer$ ansible-playbook -i inventory install.yml 
ERROR! no action detected in task

The error appears to have been in '/home/ubuntu/awx/installer/roles/image_build/tasks/main.yml': line 64, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Build AWX distribution using container
  ^ here

git status
On branch devel
Your branch is up-to-date with 'origin/devel'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   installer/inventory
	modified:   installer/roles/check_vars/tasks/main.yml

no changes added to commit (use "git add" and/or "git commit -a")
ubuntu@ip-172-31-13-185:~/awx$ cat installer/roles/image_build/tasks/main.yml
  when: use_container_for_build|default(true)|bool

- name: Build AWX distribution using container
  docker_container:
    env:
      http_proxy: "{{ http_proxy | default('') }}"
      https_proxy: "{{ https_proxy | default('') }}"
      no_proxy: "{{ no_proxy | default('') }}"
    image: "awx_sdist_builder:{{ awx_version }}"
    name: awx_sdist_builder
    state: started
    detach: false
    volumes:
      - ../:/awx:Z
  delegate_to: localhost
  when: use_container_for_build|default(true)|bool

- name: Build AWX distribution locally
  shell: make sdist

**Comment by LukeShortCloud** [comment]
The current version of AWX requires at least Ansible 2.4 to be used for the deployment Playbooks and you mentioned that your system is using Ansible 2.0 (which is also end-of-life).

https://github.com/ansible/awx/blob/bd744bced77d1f2cf92dbc27c4c7657ba039105c/INSTALL.md#prerequisites

You can install a newer version of Ansible by following this guide:

http://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html

**Comment by sicute** [comment]
thank @ekultails after add ppa.launchpad.net as my source ansible is working, last time i using source debian .
I close it now
