### ISSUE TITLE
Unable to choose a playbook - Template

### ISSUE THREAD

**Issue by doves99** [ansible/awx#1917]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

When creating the template, unable to choose a playbook.  The drop down menu shows the "Choose a playbook" option rather the actual playbook within the folders.
##### ENVIRONMENT
* AWX version: 1.0.5.31
* AWX install method: docker on linux
* Ansible version:  2.5.1
* Operating System: SE Linux
* Web Browser:Chrome

##### STEPS TO REPRODUCE

Create template and enter the necessary information, when selecting the PlayBook, the drop down menu should give the available playbooks within the folder.
##### EXPECTED RESULTS

The user should be able to select a playbook from the dropdown menu under "PLAYBOOK" 
##### ACTUAL RESULTS

The option is greyed out and cannot see the available playbook.
##### ADDITIONAL INFORMATION
The playbook and folder structure exists, this can be seen via cli.

![playbook_issue](https://user-images.githubusercontent.com/38662914/40618415-6db012d8-625f-11e8-9624-fda9e76c061b.png)

**Comment by wenottingham** [comment]
Did you place the playbook in both the task and web containers?

**Comment by doves99** [comment]
Yes, the directories and playbook are available under web and task containers.

[root@awxweb test_project]# ls
test.yml

[root@awx test_project]# ls
test.yml

**Comment by wenottingham** [comment]
What does the playbook look like?

**Comment by doves99** [comment]
The file contains the following two liner.  3 dashes and the comment line

>>cat test.yml
---
# Test script - does not produce anything

**Comment by wenottingham** [comment]
As there can be '.yml' files that are not playbooks, we filter the dropdown to only show files that pass a playbook syntax check.

The regex used is `valid_playbook_re = re.compile(r'^\s*?-?\s*?(?:hosts|include|import_playbook):\s*?.*?$')`

Let us know if using a proper playbook instead of a placeholder doesn't work for you.

**Comment by doves99** [comment]
Thanks Wenottingham,

Have updated the yaml file to the following and have the same issue as well.  Also check the web and task folder as well the file is updated.

[root@awx test_project]# cat test.yml
---
- hosts: windows
  tasks:
  - name: run a command under cmd
    win_ping:
# Test script - does not produce anything

**Comment by ryanpetrello** [comment]
I'm having trouble reproducing this on a fresh install of awx with a manual project:

```
[root@awx ~]# cat /projects/ryan/try_it_out.yml
---
- hosts: windows
  tasks:
  - name: run a command under cmd
    win_ping:
```

![screen shot 2018-06-01 at 7 44 27 am](https://user-images.githubusercontent.com/214912/40839241-a2fc3256-656f-11e8-8250-332f52296ea7.png)

**Comment by doves99** [comment]
would changing the the docker directory have any impact of choosing the playbook from ?.

# Docker Compose Install
# use_docker_compose=false
# The docker_compose.yml file will be created in this directory
# The name of the directory (here "awx") will be the prefix of the docker containers
docker_compose_dir=/opt/lib/awx


This is the only change i have performed on the inventory file, due to web being hung.

**Comment by doves99** [comment]
ok seems like the issue was due to the docker_compose_dir was pointing to /opt/lib/awx instead of /var/lib/awx.  How do i safely point/change the docker_compose_dir to a different directory?.

**Comment by jakemcdermott** [comment]
Hi doves99 - that variable (and others) can be configured in the `inventory` file used by the installer. 

If you have questions, please reach out to our community mailing list or join us on IRC. Thanks!

**Comment by donnangeric** [comment]
Hello,

I got the same issue with AWX 17.0.1.
Impossible to choice playbook while Git project, but playbook are display when manual project.
Please would you help me???

![image](https://user-images.githubusercontent.com/5146262/107997468-19709500-6fe3-11eb-8816-5eaa8a219147.png)
