### ISSUE TITLE
Role of each component in AWX system

### ISSUE THREAD

**Issue by nhproject** [ansible/awx#1918]
##### ISSUE TYPE
 Documentation

##### COMPONENT NAME
 Installer

##### SUMMARY
I would like to know more about the role of each component in the AWX architecture - Memcached, RabbitMQ, Postgres, AWX_web and AWX_task; What is each component responsible for?

##### ENVIRONMENT
* AWX version: latest
* AWX install method: Docker on Linux
* Ansible version:  2.4.1.0
* Operating System: Ubuntu 16.04
* Web Browser: Chrome

**Comment by ryanpetrello** [comment]
Hey @nhproject,

This issue list is for reporting bugs or feature enhancement requests to awx.  If you'd like to chat about the inner workings of awx, pop into our IRC room (#awx-devel) on Freenode.
