### ISSUE TITLE
Postgres container missing python module psycopg2

### ISSUE THREAD

**Issue by akcrisp** [ansible/awx#1919]
##### ISSUE TYPE

 - Bug Report
 

##### COMPONENT NAME

 - Installer

##### SUMMARY
Writing playbook to restore db. I've successfully backed up the database using pg_dump.

Now when trying to add create db permissions in postgres to the awx user - I am getting a dependency failure - 

ASK [Temporarily grant createdb role] ********************************************************************************************************************************************************************************
fatal: [postgres]: FAILED! => {"changed": false, "msg": "the python psycopg2 module is required"}
        to retry, use: --limit @/root/awx_backup/restore.retry

postgres container doesn't have pip installed. I don't appear to be able to install pip via apt-get install python3-pip and I don't appear to be able to install python3-psycopg2 via same method either.

Has anyone tested doing a backup  / restore of the db ? Is there a better way ?

Given the postgres container is missing the symlink to /usr/bin/python as well (see #1829 ). Are you guys planning on working with the postgres container builders to resolve this ? 

Or do i need to revert to bash commands to get this working. 

##### ENVIRONMENT
* AWX version: 1.0.6.8
* AWX install method: docker on linux
* Ansible version:  2.5.3
* Operating System: RHEL 7.4
* Web Browser: Chrome

##### STEPS TO REPRODUCE
 Playbook contains 

- hosts: 'postgres'
  connection: docker
  gather_facts: false
  tasks:
    - name: Temporarily grant createdb role
      postgresql_user:
        name: awx
        role_attr_flags: CREATEDB
      become_user: postgres

##### EXPECTED RESULTS
awx user has create db permissions added

##### ACTUAL RESULTS

fatal: [postgres]: FAILED! => {"changed": false, "msg": "the python psycopg2 module is required"}
        to retry, use: --limit @/root/awx_backup/restore.retry

**Comment by akcrisp** [comment]
just as fyi I've now managed to implement this using shell rather than the  ansible postgres modules for dump and restore which rely on the psycopg2 module

**Comment by wenottingham** [comment]
This is the upstream, postgres-maintained, dockerhub postgres container. We do not change it.

**Comment by akcrisp** [comment]
I know you don’t but I would have thought you would have a vested interest in ensuring all python dependencies are met so the community can use the standard ansible modules to do backup / restores ???

Maybe it’s time to make your own Postgres container if upstream aren’t interested in customising it.

Andy
