### ISSUE TITLE
install fails during Build AWX distribution using container

### ISSUE THREAD

**Issue by aoyawale** [ansible/awx#192]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

Installation fails on `TASK [image_build : Build AWX distribution using container]`

##### STEPS TO REPRODUCE
install minishift and the required rpms
configure the inventory file like mentioned in the docs for minishift
run the install playbook
##### EXPECTED RESULTS
successfully build.

##### ACTUAL RESULTS
`
TASK [image_build : Build AWX distribution using container] *******************************************************************************************************************************************************
task path: /data/git/awx/installer/image_build/tasks/main.yml:64
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/docker/docker_container.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: jlozadad
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/jlozadad/.ansible/tmp/ansible-tmp-1505747283.43-34877793143326 `" && echo ansible-tmp-1505747283.43-34877793143326="` echo /home/jlozadad/.ansible/tmp/ansible-tmp-1505747283.43-34877793143326 `" ) && sleep 0'
<localhost> PUT /tmp/tmpUPxvZ8 TO /home/jlozadad/.ansible/tmp/ansible-tmp-1505747283.43-34877793143326/docker_container.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/jlozadad/.ansible/tmp/ansible-tmp-1505747283.43-34877793143326/ /home/jlozadad/.ansible/tmp/ansible-tmp-1505747283.43-34877793143326/docker_container.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/env python /home/jlozadad/.ansible/tmp/ansible-tmp-1505747283.43-34877793143326/docker_container.py; rm -rf "/home/jlozadad/.ansible/tmp/ansible-tmp-1505747283.43-34877793143326/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "api_version": null, 
            "blkio_weight": null, 
            "cacert_path": null, 
            "capabilities": null, 
            "cert_path": null, 
            "cleanup": false, 
            "command": null, 
            "cpu_period": null, 
            "cpu_quota": null, 
            "cpu_shares": null, 
            "cpuset_cpus": null, 
            "cpuset_mems": null, 
            "debug": false, 
            "detach": false, 
            "devices": null, 
            "dns_opts": null, 
            "dns_search_domains": null, 
            "dns_servers": null, 
            "docker_host": null, 
            "entrypoint": null, 
            "env": {
                "http_proxy": "", 
                "https_proxy": "", 
                "no_proxy": ""
            }, 
            "env_file": null, 
            "etc_hosts": null, 
            "exposed_ports": null, 
            "filter_logger": false, 
            "force_kill": false, 
            "groups": null, 
            "hostname": null, 
            "ignore_image": false, 
            "image": "awx_sdist_builder:1.0.0.395", 
            "interactive": false, 
            "ipc_mode": null, 
            "keep_volumes": true, 
            "kernel_memory": null, 
            "key_path": null, 
            "kill_signal": null, 
            "labels": null, 
            "links": null, 
            "log_driver": null, 
            "log_options": null, 
            "mac_address": null, 
            "memory": "0", 
            "memory_reservation": null, 
            "memory_swap": null, 
            "memory_swappiness": null, 
            "name": "awx_sdist_builder", 
            "network_mode": null, 
            "networks": null, 
            "oom_killer": null, 
            "oom_score_adj": null, 
            "paused": false, 
            "pid_mode": null, 
            "privileged": false, 
            "published_ports": null, 
            "pull": false, 
            "purge_networks": false, 
            "read_only": false, 
            "recreate": false, 
            "restart": false, 
            "restart_policy": null, 
            "restart_retries": null, 
            "security_opts": null, 
            "shm_size": null, 
            "ssl_version": null, 
            "state": "started", 
            "stop_signal": null, 
            "stop_timeout": null, 
            "timeout": null, 
            "tls": null, 
            "tls_hostname": null, 
            "tls_verify": null, 
            "trust_image_content": false, 
            "tty": false, 
            "ulimits": null, 
            "user": null, 
            "uts": null, 
            "volume_driver": null, 
            "volumes": [
                "../:/awx:Z"
            ], 
            "volumes_from": null
        }
    }, 
    "msg": "make: *** No rule to make target `sdist'.  Stop.\nmake: *** No rule to make target `sdist'.  Stop.\nmake: *** No rule to make target `sdist'.  Stop.\nmake: *** No rule to make target `sdist'.  Stop.\nmake: *** No rule to make target `sdist'.  Stop.\nmake: *** No rule to make target `sdist'.  Stop.\nmake: *** No rule to make target `sdist'.  Stop.\nmake: *** No rule to make target `sdist'.  Stop.\n", 
    "status": 2
}
`

**Comment by shanemcd** [comment]
Please have a look at https://github.com/ansible/awx/blob/devel/installer/inventory#L5-L14 and let us know if this resolves your issue.

**Comment by jgorinsky** [comment]
If anybody comes across this issue and is confused by the above link, I think it was meant to point at this block: https://github.com/ansible/awx/blob/f5ccb51ef2d61367e50b4de4ac6e398c7af10714/installer/inventory#L5-L14
