### ISSUE TITLE
User management page corrupted

### ISSUE THREAD

**Issue by sirkubax** [ansible/awx#1920]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

While editing an user profile, content of userID=1 (admin) is loaded and override the 'expected user data'  example - userID=3  ->  http://awx.example.com/#/users/3 
It loads the page with correct data (throwing a password error and an error in browser-console; then after 1 second it fill admin data)
![image](https://user-images.githubusercontent.com/3442120/40659289-213c3a36-634e-11e8-89f7-c2c70972dbed.png) "The value does not match the password you entered previously, Please confirm that passoword" 
It overrides the displayed text with a content of userID=1 http://awx.example.com/#/users/1

It may be a case, that the 'Add User' interface is broken
![image](https://user-images.githubusercontent.com/3442120/40659857-ba1e6d72-634f-11e8-805b-ea787d95f663.png)

It fills up the form content while I believe the filelds shall stay empty (now fields are filled with UserID=1 data - in my case it is admin user)

EDIT:
I believe the form for presenting user is broken
![image](https://user-images.githubusercontent.com/3442120/40660528-8940cd56-6351-11e8-9447-8e721e8cdf15.png)

##### ENVIRONMENT
* AWX version:  awx-manage --version
1.0.6.11
* AWX install method:  docker-compose
* Ansible version:  2.5.1
* Operating System: Ubuntu 16.04 LTS
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Add user, and save. try to edit data of user other that ID=1

##### EXPECTED RESULTS

Display correct user data

**Comment by ryanpetrello** [comment]
> throwing a password error and an error in browser-console

Would you mind sharing the error you're seeing in your browser console?

**Comment by sirkubax** [comment]
Logs seems unrelated

![image](https://user-images.githubusercontent.com/3442120/40683440-e4a8989e-638e-11e8-9ee2-217d4d142a52.png)

**Comment by sirkubax** [comment]
https://pastebin.com/hXw4FSwb

**Comment by sirkubax** [comment]
![image](https://user-images.githubusercontent.com/3442120/40683531-2b688262-638f-11e8-8e1e-b9fbe72aa465.png)


Check out that other user data shall be presented, but 'admin' data is dissplayed

**Comment by sirkubax** [comment]
It may not be related to user/1
I've just reloaded http://example.com/#/users/2 with Ctrl+R 
Now User/2 works well, but User/1 data is never displayed :/

**Comment by sirkubax** [comment]
could it be a cache?  The data seems to be there, just not displaying :/

![image](https://user-images.githubusercontent.com/3442120/40683926-38dc2a24-6390-11e8-8149-d3ce52fd8bfd.png)

**Comment by wenottingham** [comment]
Are you using lastpass or a similar form-autofill browser add-on?

**Comment by matburt** [comment]
No follow up in several months
