### ISSUE TITLE
 Set SHA hash / branch for project at template level

### ISSUE THREAD

**Issue by rex-kwon-do** [ansible/awx#1923]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

Looking for a option to set SCM branch at job template level with `prompt on launch` to avoid having to configure multiple projects when running different branches of the same playbook.  

##### ENVIRONMENT
* AWX version: devel

##### ADDITIONAL INFORMATION

As a workaround this is currently being done by performing the checkout as part of the playbook.

**Comment by wenottingham** [comment]
This is https://github.com/ansible/awx/issues/282
