### ISSUE TITLE
How is awx_rabbitmq container built?

### ISSUE THREAD

**Issue by cben** [ansible/awx#1926]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME
 - Installer

##### SUMMARY
Installer once used standard `rabbitmq:3` image but since https://github.com/ansible/awx/commit/6a85fc38dd861633bc795e14155271f73b816b40#diff-d975205ae64de1b20726919b50ffcc75R44 defaults to `ansible/awx_rabbitmq` image.

https://hub.docker.com/r/ansible/awx_rabbitmq/ has zero information how it gets built, from which source @ what version, how it differs from upstream rabbitmq...  No README, no Dockerfile...
Please document somewhere, including whether it's safe to replace with upstream rabbitmq or one you build yourself, to help users exercise their freedoms :)

##### ENVIRONMENT
* AWX version: 1.0.4+
* AWX install method: openshift

cc @matburt

**Comment by cben** [comment]
Actually, I think the current situation falls short of [the RabbitMQ MPL-1.1 license](https://www.rabbitmq.com/mpl.html), a "weak copyleft" license, especially if there were any modifications — but even if not, should include on Docker Hub license & pointer to source :
[IANAL]

> ### 3. Distribution Obligations.
> #### 3.1. Application of License.
> ... and You must include a copy of this License with every copy of the Source Code You distribute ...
> #### 3.2. Availability of Source Code.
>   Any Modification which You create or to which You contribute must be
>   made available in Source Code form under the terms of this License
>   either on the same media as an Executable version or via an accepted
>   Electronic Distribution Mechanism to anyone to whom you made an
>   Executable version available; ...  
> #### 3.3. Description of Modifications. ...
>  You must cause all Covered Code to which You contribute to contain a
>    file documenting the changes You made to create that Covered Code and
 >   the date of any change.
> #### 3.6. Distribution of Executable Versions.
>  You may distribute Covered Code in Executable form only if the requirements of Section 3.1-3.5 have been met ...

**Comment by matburt** [comment]
I've made these changes to the dockerhub repository and I've opened up the awx rabbitmq repository here:

https://github.com/ansible/awx-rabbitmq
