### ISSUE TITLE
RFE: Add an awx-manage command for generating an OAuth2 token

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#1927]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
The first time you create an OAuth2 token for a user, you must use basic HTTP Auth with the API using a password.  To make automation easier, it might be nice to have an `awx-manage` command that could be run as the `awx` user over ssh.

`awx-manage create_oauth2_token --user=some_user`

Such a command would create a write-scoped token for an existing user and return the token value.

related: https://github.com/ansible/awx/issues/1906

**Comment by YunfanZhang42** [comment]
This requested feature is implemented in #1942, so I am closing it.
