### ISSUE TITLE
installed awx with docker

### ISSUE THREAD

**Issue by sitaramlinux9** [ansible/awx#1929]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY
Installed AWX on rhel 7.5, configured 570 hosts and tried to test using ping module and the tower freezes for a while

##### ENVIRONMENT
* AWX version: AWX 1.0.6.8 
* AWX install method: docker on linux
* Ansible version: Ansible 2.5.3
* Operating System: rhel 7.5
* Web Browser: chrome

##### STEPS TO REPRODUCE
I have installed awx ansible on rhel 7.5, configures 570 hosts and tried to use ping module on awx tower, it freezes for a while. i wanted to see the cpu usagae of the server. i have found that the container is using 1 cpu "25%" usage. what changes should be made so that the tower uses 2 cpu's?
The server is configured with 2 cpu, 4 cores.

**Comment by wenottingham** [comment]
CPU/memory requests are done by the installer, see installer/roles/kubernetes/defaults/main.yml, etc.
