### ISSUE TITLE
Unable to add SSHtectia generated private key in Credential to authenticate remote machines

### ISSUE THREAD

**Issue by Shilpaklala** [ansible/awx#1930]
##### ISSUE TYPE

 - Bug Report
I was unable to execute playbooks on remote machine using ansible Tower, but I am able to execute playbooks  from the ansible server(cmd line). Here I have a ansible user on both ansible server and client and they are authenticate using SSH-passwordless auth. Keys are generated using SSHtectia.  Also I was getting "Invalidkey forma" while I was trying to add the ansible private key in the credentails of ansible user in tower.

our key starts with
----- BEGIN SSH2 ENCRYPTED PRIVATE KEY------
asasfasdasdddddddddddd
sdfffffffffffffffffffffffffffffff
---- END SSH2 ENCRYPTED PRIVATE KEY ----
##### COMPONENT NAME

 - API
 - UI
 - Installer

##### ENVIRONMENT
* tower version: 3.0.4 
* AWX install method: Redhat 6.9
* Ansible version:  2.5.2
* Operating System: Redhat
* Web Browser: chrome

**Comment by ghjm** [comment]
This issue tracker is for development issues for the AWX open source project. If you are having trouble while using Ansible Tower, you should open a support case at access.redhat.com.

**Comment by cchurch** [comment]
Check that the number of dashes in the header/footer of your key are consistent; they definitely aren't in the example you provided.

I don't see "invalid key format" anywhere in the code; I would expect the error message to be either "Invalid certificate or key" or "Invalid private key: unsupported type". 

The current private key validation doesn't include support for the SSH2 format (https://github.com/ansible/awx/blob/devel/awx/main/validators.py#L38). Try converting your key to RSA format and see if that works.
