### ISSUE TITLE
Ordering Warnings in Tests

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/awx#1931]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY
There are "no default ordering warnings" on our functional tests that were introduced when we upgraded to Django 1.11.11.  

##### Possible Solutions
Option A: add an `ordered_by` in all of the get_queryset() and filtered_querysets() functions that are acting up in views.py.  
Option B: Make this change by adding ordering to the Meta class on the model.  
maybe we can find a sneaky metaclassed way to default to something like `order_by = ['id']`
Option C: Inherit from a common model that is `order_by = ['id']`.  It looks like this is already done for all models that use BaseModel, and is only an issue for custom models.  

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Run our functional tests.  

##### EXPECTED RESULTS

No warning messages

##### ACTUAL RESULTS

Warning messages that our serializers are not ordered.  

##### ADDITIONAL INFORMATION
It looks like this is already done for all models that use BaseModel, and is only an issue for custom models.  

Traceback:

```
============================= warnings summary ===============================
awx/main/tests/functional/api/test_oauth.py::test_oauth_token_create
  /venv/awx/lib/python2.7/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'awx.main.models.oauth.OAuth2AccessToken'> QuerySet.
    paginator = self.django_paginator_class(queryset, page_size)

-- Docs: http://doc.pytest.org/en/latest/warnings.html
```

**Comment by ryanpetrello** [comment]
@rooftopcellist is this still an issue?  Seems like we squashed this at some point when upgrading to a newer Django.

**Comment by ryanpetrello** [comment]
(feel free to reopen if I'm wrong)
