### ISSUE TITLE
RFE: Expose Job Template Timeout in UI

### ISSUE THREAD

**Issue by LukeShortCloud** [ansible/awx#1932]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
Allow a job template to timeout. Add a default value (maybe something large such as 24 hours / 1440 minutes) and/or provide an additional option for a timeout. After the timeout, the Ansible playbook command should be stopped and the job forcefully cancelled. This could help to address issues like this: https://github.com/ansible/awx/issues/888 and https://github.com/ansible/awx/issues/1034.

##### ENVIRONMENT
* AWX version: 1.0.6
* AWX install method: DockerHub
* Ansible version:  2.5.3
* Operating System: RHEL 7.5

##### STEPS TO REPRODUCE
Create a new Job Template. There is no option for a timeout.

##### EXPECTED RESULTS
When creating or editing a Job Template there should be a new "Timeout" setting in the "Option" section. Tower can continue to check on this Job once it is ran. If it has not completed (or started, for that matter) by the timeout that was set then the job should be stopped.

##### ACTUAL RESULTS
There is no timeout.

**Comment by wenottingham** [comment]
This already exists, see the 'timeout' field of the job template (and the default timeout in job settings).

It is not currently exposed in the UI at the job template level, but you can set it in the API.

**Comment by fedelemantuano** [comment]
Hi,

I can see `timeout` parameter in API, but it's not documented (https://docs.ansible.com/ansible-tower/2.3.1/html/towerapi/job_template.html)

Maybe the default it's `0`. What's does it mean? Infinite?

The value is in seconds?

**Comment by mabashian** [comment]
@fedelemantuano The timeout parameter is the amount of time (in seconds) to run before the task is canceled.  The default is 0 which afaik means there is no timeout.

**Comment by dsesami** [comment]
Verification plan:
- [x] Ensure that the timeout field renders appropriately and in a similar fashion to the rest of the job template options.
- [x] Ensure that the field accepts and passes appropriate values, and that form validation behaves correctly.

**Comment by jlmitch5** [comment]
From api options:

```
"timeout": {
                "type": "integer",
                "required": false,
                "label": "Timeout",
                "help_text": "The amount of time (in seconds) to run before the task is canceled.",
                "min_value": -2147483648,
                "max_value": 2147483647,
                "filterable": true,
                "default": 0
            },
```

**Comment by jlmitch5** [comment]
This is how options is passed back for these two fields:

```
"OAUTH2_PROVIDER": {
                "type": "nested object",
                "required": false,
                "label": "OAuth 2 Timeout Settings",
                "help_text": "Dictionary for customizing OAuth 2 timeouts, available items are `ACCESS_TOKEN_EXPIRE_SECONDS`, the duration of access tokens in the number of seconds, and `AUTHORIZATION_CODE_EXPIRE_SECONDS`, the duration of authorization grants in the number of seconds.",
                "category": "Authentication",
                "category_slug": "authentication",
                "default": {
                    "ACCESS_TOKEN_EXPIRE_SECONDS": 31536000000,
                    "AUTHORIZATION_CODE_EXPIRE_SECONDS": 600
                },
                "child": {
                    "type": "integer",
                    "required": true,
                    "read_only": false,
                    "min_value": 1
                }
            },
```

**Comment by jlmitch5** [comment]
moving to needs_test though I think @dsesami has already verified and this can probably be closed

**Comment by dsesami** [comment]
confirmed verified as mentioned here: https://github.com/ansible/awx/issues/1932#issuecomment-453208456
