### ISSUE TITLE
RFE: Allow Job Templates to Update Inventories and/or Projects on Launch

### ISSUE THREAD

**Issue by LukeShortCloud** [ansible/awx#1934]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Allow both an inventory and/or project sync on launch to be an option **in the job template**.

Our use case is that our inventory is dynamically sourced from Red Hat Satellite. During the deployment of a new server, a provisioning callback is done to configure the new server. However, the new server is not yet added to the inventory. Currently the inventory settings have it set to "update on launch" which is not ideal as the large inventory takes a long time to process for every Job Template that is ran. The inventory only needs to be updated during a few select Jobs.

##### ENVIRONMENT
* AWX version: 1.0.6
* AWX install method: DockerHub
* Ansible version:  2.5.3
* Operating System: RHEL 7.5

##### STEPS TO REPRODUCE
Create a new Job Template. There is no option in there to update an inventory and/or project whenever this Job is ran.

##### EXPECTED RESULTS
There should be an option in the Job Template to update the inventory and/or project. This way it will update the relevant source of truth only for the Job Templates that have those options checked/enabled.

##### ACTUAL RESULTS
Inventories and projects can only have their settings changed to *always* update on launch or *never* update on launch. There is no way to do this on a per-Job Template basis.

##### ADDITIONAL INFORMATION
Related RBAC settings are also something to keep in mind.

**Comment by wenottingham** [comment]
Note that this can be accomplished today with a workflow, although this is an extra step.

**Comment by mkempster22** [comment]
Could you not do this by having a task in the playbook that calls the API to update it? we have something similar in a playbook of ours
