### ISSUE TITLE
passing ec2.ini files to inventory script

### ISSUE THREAD

**Issue by apremalal** [ansible/awx#1935]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME
 - UI

##### SUMMARY

AWS ec2 external inventory scripts use `ec2.ini` files as documented here http://docs.ansible.com/ansible/latest/user_guide/intro_dynamic_inventory.html#example-aws-ec2-external-inventory-script

However I couldn't find any documentation on how to configure this file via aws UI. I was able to add the inventory script `ec2.py` via UI. I have multiple inventory scripts which make use of different ec2.ini files,

##### ENVIRONMENT
* AWX version: 1.0.6.9 
* AWX install method: docker-compose
* Ansible version:  2.5.3
* Operating System: Ubuntu 16.04 
* Web Browser: Chrome

**Comment by cchurch** [comment]
AWX includes its own copy of the EC2 inventory script, so there should be no need to add it as a custom inventory script.

Refer to http://docs.ansible.com/ansible-tower/latest/html/userguide/inventories.html#amazon-web-services-ec2 for details on configuring an inventory with an EC2 source. AWX generates a custom ec2.ini when running the built-in script, and the source variables field can be used to include additional options in the generated ec2.ini.

Custom inventory scripts can only be configured via environment variables (http://docs.ansible.com/ansible-tower/latest/html/userguide/inventories.html#custom-script).
