### ISSUE TITLE
Feature: Workflow parallel dependencies

### ISSUE THREAD

**Issue by seansabour** [ansible/awx#1937]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
In a workflow you should be able to define 2 templates to run in parallel and have a 3rd template rely on the previous 2 templates `on success` completion before executing 3rd playbook.

##### ENVIRONMENT
* AWX version: all
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  all
* Operating System: all
* Web Browser: All

##### STEPS TO REPRODUCE

Open Workflow and create two nodes that run in parallel, create a third node that should connect to the two previous nodes. You will see you can only choose a single node.

##### EXPECTED RESULTS
Open workflow and create two nodes that run in parallel, create a third node that can connect to the two previous plays.

##### ACTUAL RESULTS

Unable to do so today.

##### ADDITIONAL INFORMATION

![workflow](https://user-images.githubusercontent.com/9244813/40767196-b0079134-6466-11e8-8c70-c20f9e9ff7dd.PNG)

**Comment by wenottingham** [comment]
this is covered in #284
