### ISSUE TITLE
requirements.yml file is ignored in <project_dir>/root/requirements.yml

### ISSUE THREAD

**Issue by pkubica** [ansible/awx#1939]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

requirements.yml file is ignored in project

##### ENVIRONMENT
* AWX version: 3.2.5-1
* AWX install method: via RPM
* Ansible version:  2.5.3-1.el7
* Operating System: Red Hat Enterprise Linux Server 7.5
* Web Browser: firefox 52.7.3

##### STEPS TO REPRODUCE

I used an example: https://github.com/ansible/tower-example (cloned into /var/lib/awx/projects/)
I changed only playbook file (helloworld.yml) to use role defined in requirements.yml file:

```yaml
---
- name: Hello World!
  hosts: all
 
  tasks:
    - name: Hello World!
      shell: echo "Hi! Tower is working."

  roles:
    - yatesr.timezone
```

I created in Ansible Tower project with type manual. From that project I created template and ran it as a job and I get this error:

ERROR! the role 'yatesr.timezone' was not found in /var/lib/awx/projects/tower-example/roles:/var/lib/awx/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/var/lib/awx/projects/tower-example
The error appears to have been in '/var/lib/awx/projects/tower-example/helloworld.yml': line 11, column 7, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
  roles:
    - yatesr.timezone
      ^ here

but yatesr.timezone is mentioned in <project_dir>/roles/requirements.yml

##### EXPECTED RESULTS
dependencies should be installed

##### ACTUAL RESULTS
ignored requirement file

**Comment by wenottingham** [comment]
The ansible-galaxy command to automatically download roles is not run on manual projects, by design. If you're using a manual project, clone the roles manually.
