### ISSUE TITLE
ANSIBLE all - ping -vvv ISSUES

### ISSUE THREAD

**Issue by Tamharpreet** [ansible/awx#194]
Hi Everyone,

I am new to ANSIBLE!
I just installed it on my AWS instance. 
I am able to ssh into remote guests and ssh keys are in the authorized_keys folder.
I am trying to Ansible ping all my remote guests. I am facing these issues since last week. But it gives me error as follows:

>

 ubuntu@ip-172-31-30-138:~$ ansible all -m ping -vvv
> Using /etc/ansible/ansible.cfg as config file
> META: ran handlers
> Using module file /usr/lib/python2.7/dist-packages/ansible/modules/system/ping.py
> Using module file /usr/lib/python2.7/dist-packages/ansible/modules/system/ping.py
> <166.151.49.164> ESTABLISH SSH CONNECTION FOR USER: debian
> Using module file /usr/lib/python2.7/dist-packages/ansible/modules/system/ping.py
> Using module file /usr/lib/python2.7/dist-packages/ansible/modules/system/ping.py
> <166.151.222.19> ESTABLISH SSH CONNECTION FOR USER: debian
> <166.151.222.19> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22095 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=debian -o ConnectTimeout=10 -o ControlPath=/home/ubuntu/.ansible/cp/d808d5e425 166.151.222.19 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
> <172.17.0.2> ESTABLISH SSH CONNECTION FOR USER: ubuntu
> <166.151.49.166> ESTABLISH SSH CONNECTION FOR USER: debian
> <172.17.0.2> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22095 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/ubuntu/.ansible/cp/e67eba8851 172.17.0.2 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
> <166.151.49.164> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22095 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=debian -o ConnectTimeout=10 -o ControlPath=/home/ubuntu/.ansible/cp/641657136c 166.151.49.164 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
> <166.151.49.166> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22095 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=debian -o ConnectTimeout=10 -o ControlPath=/home/ubuntu/.ansible/cp/97be8de99a 166.151.49.166 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
> Using module file /usr/lib/python2.7/dist-packages/ansible/modules/system/ping.py
> <localhost> ESTABLISH LOCAL CONNECTION FOR USER: ubuntu
> <localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
> <localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1505754595.46-35723922020174 `" && echo ansible-tmp-1505754595.46-35723922020174="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1505754595.46-35723922020174 `" ) && sleep 0'
> <localhost> PUT /tmp/tmpx_G_ZX TO /home/ubuntu/.ansible/tmp/ansible-tmp-1505754595.46-35723922020174/ping.py
> <localhost> EXEC /bin/sh -c 'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1505754595.46-35723922020174/ /home/ubuntu/.ansible/tmp/ansible-tmp-1505754595.46-35723922020174/ping.py && sleep 0'
> <localhost> EXEC /bin/sh -c '/usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1505754595.46-35723922020174/ping.py; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1505754595.46-35723922020174/" > /dev/null 2>&1 && sleep 0'
> localhost | SUCCESS => {
>     "changed": false,
>     "invocation": {
>         "module_args": {
>             "data": null
>         }
>     },
>     "ping": "pong"
> }
> <166.151.49.164> (255, '', 'Debian GNU/Linux 7\n\nBeagleBoard.org Debian Image 2015-03-01\n\nSupport/FAQ: http://elinux.org/Beagleboard:BeagleBoneBlack_Debian\n\ndefault username:password is [debian:temppwd]\n\nPermission denied (publickey,password).\r\n')
> 166.151.49.164 | UNREACHABLE! => {
>     "changed": false,
>     "msg": "Failed to connect to the host via ssh: Debian GNU/Linux 7\n\nBeagleBoard.org Debian Image 2015-03-01\n\nSupport/FAQ: http://elinux.org/Beagleboard:BeagleBoneBlack_Debian\n\ndefault username:password is [debian:temppwd]\n\nPermission denied (publickey,password).\r\n",
>     "unreachable": true
> }
> 

The host file looks like this:

```

> > [ubuntu01]
> 172.17.0.2 ansible_user=ubuntu
> 
> [copesalt]
> 166.151.49.164 ansible_user=debian
> 166.151.49.166 ansible_user=debian
> 166.151.222.19 ansible_user=debian

```

Your help will be much appreciated
Thank You so Much

**Comment by ryanpetrello** [comment]
@Tamharpreet is looks like your question might be specific to Ansible itself, not the awx project.  Try posing your question on the Ansible mailing list:

http://groups.google.com/group/ansible-project

...or `#ansible` on irc.freenode.net
