### ISSUE TITLE
Old ovirt-engine-sdk-python in Tower setup

### ISSUE THREAD

**Issue by pkubica** [ansible/awx#1940]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

Old ovirt-engine-sdk-python causes that ovirt modules in Ansible 2.5 don't work
##### ENVIRONMENT
* AWX version: 3.2.5-1
* AWX install method: RPM
* Ansible version:  2.5.3-1
* Operating System: Red Hat Enterprise Linux Server 7.5
* Web Browser: Firefox 52.7.3

##### STEPS TO REPRODUCE
After installation:
$ cd  /var/lib/awx/venv/ansible/bin/
$ ./pip list | grep ^ovirt
ovirt-engine-sdk-python (4.1.6)

run project with oVirt modules
TASK [oVirt.cluster-upgrade : Login to oVirt] **********************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "ovirtsdk4 version 4.2.4 or higher is required for this module"}

##### EXPECTED RESULTS
There should be ovirtsk4 version >= 4.2.4

**Comment by wenottingham** [comment]
This isn't an AWX issue.
