### ISSUE TITLE
Form Template requires specified Machine Credential when there is already specified RHV Credential

### ISSUE THREAD

**Issue by pkubica** [ansible/awx#1941]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

When using only localhost (as current practice for oVirt modules/roles to coordinate oVirtSDK with Ansible) in template form for defining job - the form requires Machine credentials, which is not necessary when there is 'ansible_connection: local' in inventory in host (localhost) variables.
There is already specified RHV Credentials, which should be sufficient.

##### ENVIRONMENT
* AWX version: 3.2.5-1
* AWX install method: RPM
* Ansible version:  2.5.3-1
* Operating System: Red Hat Enterprise Linux Server 7.5
* Web Browser: 52.7.3

##### STEPS TO REPRODUCE
- Create project with oVirt modules
- Have localhost inventory (specified variable ansible_connection: local)
- Create template for project with oVirt modules with localhost inventory and also with RHV Credentials
result: Form also wants Machine credentials which isn't necessary.

##### EXPECTED RESULTS
RHV Credentials should be sufficient.

##### ACTUAL RESULTS
Dummy credentials must be created and used.

**Comment by ryanpetrello** [comment]
@pkubica this is fixed in recent versions of awx, and will be fixed in an upcoming version of Tower:

https://github.com/ansible/awx/issues/1656
https://github.com/ansible/awx/pull/595
