### ISSUE TITLE
Cannot install modules from within Docker task container. It appears that something in corrupt.

### ISSUE THREAD

**Issue by marcosgeorgopoulos** [ansible/awx#1943]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Unable to update pip or install python libraries from within awx_task container. for example

'pip install napalm'

Adding the command to the docker compose file gives the same error.

##### ENVIRONMENT
* AWX version: 1.0.6
* AWX install method: docker container built from source using 'use_container_for_build=true' option 
* Ansible version:  2.5.3
* Operating System: RHEL 7.4
* Web Browser:  N/A

##### STEPS TO REPRODUCE

update docker compose file to contain

'RUN pip install napalm'

or from within container 

pip install napalm.    

(Note I get the same Error 22 for multiple python modules including pip ) 

I do not get this issue when installing from the host at all.

##### EXPECTED RESULTS

modules should install successfully.

##### ACTUAL RESULTS

Installing collected packages: setuptools, cffi, future, jtextfsm, netaddr, pyeapi, scp, pyserial, textfsm, netmiko, lxml, pyIOSXR, ncclient, junos-eznc, urllib3, idna, chardet, certifi, requests, pynxos, napalm
  Found existing installation: setuptools 0.9.8
    Uninstalling setuptools-0.9.8:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 326, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/lib64/python2.7/shutil.py", line 299, in move
    rmtree(src)
  File "/usr/lib64/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib64/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 22] Invalid argument: '/usr/lib/python2.7/site-packages/_markerlib'
You are using pip version 8.1.2, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

##### ADDITIONAL INFORMATION

The path ''/usr/lib/python2.7/site-packages/_markerlib'' exists. 

I am running as root.

**Comment by ryanpetrello** [comment]
@marcosgeorgopoulos are you attempting to install `napalm` for use within a playbook you'll run in awx?  If so, you'll want to use `pip` in the specific Python virtualenv that awx uses for playbook runs, _not_ the system pip.

Try:

`/var/lib/awx/venv/ansible/bin/pip install ...`

Also, you may find this documentation helpful:
https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md

**Comment by marcosgeorgopoulos** [comment]
Thanks Ryan,  strangely enough though I’ve always just ran pip install straight from the awx_task container and it’s worked. I’ve tested this a few times. I will try you method and see if it works, however I still don’t understand why the pip is failing with the error

**Comment by marcosgeorgopoulos** [comment]
ok I can successfully add modules to the virtualenv as suggest above. thank you for that link. 

The one piece of the puzzle I am missing is how do I configure my action plugins etc?  for my newly installed modules? i.e where do I configure ansible to be able to point to napalm-ansible's action plugin folder?

The ansible within the awx_task container points to usr/lib/python for its ansible module location.

**Comment by wenottingham** [comment]
This can be done via an ansible.cfg in the project path; there are other ways to pass custom action plugins. Closing for the initial issue.
