### ISSUE TITLE
AWX 5 Containers into a 1 single Container. 

### ISSUE THREAD

**Issue by ghost** [ansible/awx#1945]
##### ISSUE TYPE

 - Feature Idea
 - Documentation
 AWX 5 Containers into a 1 single Container. 

##### COMPONENT NAME

 - Installer

##### SUMMARY

We have a high secured infra structure. they don't let us to install docker or kubernetes or openshift. We need to install AWX in a bare-metal or bare-bone server. How to do that with with the installer ?

**Comment by wenottingham** [comment]
this is #419
