### ISSUE TITLE
No new tasks are executed in AWX...

### ISSUE THREAD

**Issue by asir214** [ansible/awx#1950]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
When you try to run a job, the application remains on hold and does not start or finish executing it.
Any ideas? Can anybody help me?

Thank you

##### ENVIRONMENT
* AWX version: 3.2.3
* AWX install method: openshift
* Ansible version:  2.5.3
* Operating System: Ubuntu 16.04.4 LTS
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

I executed several tasks at once and suddenly stopped doing new tasks.

##### ADDITIONAL INFORMATION

![awx-1](https://user-images.githubusercontent.com/39795205/40904345-c300516e-67da-11e8-9e01-4a96959396b1.png)

![awx-2](https://user-images.githubusercontent.com/39795205/40904354-c9212226-67da-11e8-9efb-749af7cd77db.png)

**Comment by wenottingham** [comment]
What is your actual AWX version in the screenshot? 3.2.3 is not an AWX version, but you've got an AWX screenshot.
