### ISSUE TITLE
UI survey options

### ISSUE THREAD

**Issue by hemskgren** [ansible/awx#1951]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

1, add job_template name to survey prompt 
2, add survey optional job description.
3, add  an optional "line brake" in survey, prefered with an text option.
##### ENVIRONMENT
* AWX version: 1.0.6

##### EXPECTED RESULTS

1, survey -> PROMPT : my awx job
2, survey -> PROMPT and text explaine purpose "my awx job do this ..."
3, add an optional "line brake" in survey between question, prefered with an text option.
4, survey questions more input verification options. example verify that input include "@" for mail adress. ipv4 adress include "." or prefered three "."
##### ACTUAL RESULTS

1, survey -> PROMPT
2, survey -> use first question to describe playbook purpose.
3,  N/A
4,   N/A only minimum and max length.

**Comment by wenottingham** [comment]
Closing as a dup of #1108
