### ISSUE TITLE
RFE: Option for customization of nginx config during setup/upgrade

### ISSUE THREAD

**Issue by benjdudas** [ansible/awx#1952]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - Installer

##### SUMMARY

Currently any custom include statement in nginx.conf will be overwritten during upgrade. This option would provide a variable for the include path in the inventory file. 

roles/nginx/templates/nginx.conf:
```
{% if extra_nginx_include is defined %}
    include {{ extra_nginx_include }};
    {% endif %}
```
Inventory:
```
#cat inventory |grep extra
extra_nginx_include='./conf.d/*'
```
##### ENVIRONMENT
* AWX version: 1.0

**Comment by wenottingham** [comment]
solved by https://github.com/ansible/awx/pull/1956
