### ISSUE TITLE
More descriptive error if user tries to create Job Template before adding an inventory.

### ISSUE THREAD

**Issue by wturnage** [ansible/awx#1958]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

When handing out Organizations to users they always get a little click happy and reply back with they cannot create a job template. I know this is something minor. 

##### ENVIRONMENT
* AWX version: 1.0.1.314
* AWX install method: docker on linux
* Ansible version:  2.4.1.0
* Operating System: RHEL 7.5 
* Web Browser: Firefox

##### STEPS TO REPRODUCE

1 ) Create a user that is an admin of an organization with nothing in its inventory
2) Create a Job Template. Templates > plus button > Job Template
3) Error will pop up when the form loads reading "You do not have permission to add a job template"

##### EXPECTED RESULTS

Would be nice if the error was more descriptive as the user has permissions to create a job template, but first needs to create an inventory.

##### ACTUAL RESULTS

Adding an item to the Organization's inventory then repeating step 2 will allow the user to proceed to the form.

**Comment by ryanpetrello** [comment]
@wturnage we've just released 1.0.7, which we believe resolves the underlying issue here. You can try it out here: https://github.com/ansible/awx/releases/tag/1.0.7

Let us know if you're still seeing this issue after installing the latest awx - thanks!

**Comment by sujiar37** [comment]
@ryanpetrello  This issue is still reproducing in the latest version of AWX 2.1.0 . Would be better if the error message is more descriptive, so that it helps to understand that atleast an single inventory should be exist already in order to setup a job template .

**Comment by Michael-B-G** [comment]
I just encountered a variation of this issue in Ansible 2.6.19 / Tower 3.5.2 , though with no projects rather than no inventories.  When one project was created, even with no inventories created, the problem went away.
