### ISSUE TITLE
job output options

### ISSUE THREAD

**Issue by hemskgren** [ansible/awx#1959]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - UI

##### ENVIRONMENT
* AWX version: 1.0.6
* AWX install method: docker on linux,
* Ansible version:  2.5.4
* Operating System: 
* Web Browser:

##### EXPECTED RESULTS

[example tower 2.x output. ](https://github.com/hemskgren/dump/blob/master/tower2.x.png)
include Event, Result and Json.
##### ACTUAL RESULTS

[example awx 1.0.6 output. ](https://github.com/hemskgren/dump/blob/master/awx.png)
include Json.
##### ADDITIONAL INFORMATION

For network engineer it is way more trust in the good looking tower result (with command, proposed, existing and end_state)  than awx json only.

**Comment by gamuniz** [comment]
You can see result, event and json in the newer UI. Closing this as done
