### ISSUE TITLE
Ansible command works however ansible-playbook doesn't 

### ISSUE THREAD

**Issue by boris-42** [ansible/awx#1961]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY

Job Templates creates on vanila installation do not work. Problems with ssh connectivity. 
However, ad hoc operations on hosts work without any issues. 

##### ENVIRONMENT
* AWX version: 1.0.6.14
* AWX install method: docker on linux
* Ansible version:  2.5.4
* Operating System: Centos
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

Create 1 inventory, with 1 host, 1 machine credentials (with ssh key). 
1. Run ad hoc command (which triggers ansible) -> everything works 
2. Create job template and run it -> problems with ssh connections 

In case if ControlMaster=no is set in ansible.conf everything works! 

##### EXPECTED RESULTS

System works without any issues 

##### ADDITIONAL INFORMATION

Logs of ad hoc VS job template execution
https://gist.github.com/boris-42/87cdccd6dac08d2f10c810fd9340040b

**Comment by jakegatsby** [comment]
Experiencing the same issue, AWX using local docker-compose.  I'm also seeing the same key_load_public error messages as boris-42.  After setting ControlMaster=no in ansible.cfg, playbooks/templates work as expected in AWX.

AWX version: 1.0.6.14
AWX install method: docker (compose) on linux
Ansible version: 2.5.4
Operating System: Ubuntu 16.04
Web Browser: Google Chrome

**Comment by jakemcdermott** [comment]
This should be resolved in the latest version of awx - closing
