### ISSUE TITLE
Add metrics endpoint for use by Prometheus (or similar) monitoring tools

### ISSUE THREAD

**Issue by jainnikhil30** [ansible/awx#1963]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

Add Prometheus as a monitoring tool in awx for monitoring application internals.  Prometheus is also set as monitoring within Openshift.
It can be used to gain insights about:
- any run time statistics like queue length, number of jobs executed, execution lengths of the jobs, etc.
- any instance statistics like number of projects, number of user, number of job_templates
- memory consumption of database, django itself, etc.
- etc. etc..
All the nice feature a whitebox monitoring would like
These features should be accessible over a defined REST-Endpoint without any additional server which can be queried by prometheus. Please see examples under https://github.com/prometheus/prometheus/wiki/Default-port-allocations

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by wenottingham** [comment]
This should track more things:
- job runs (successful, failed, etc.)
- hosts (and their associated job history)
- job runs x hosts
- tasks x hosts 
- job execution time
- task execution time
- module usage
- count of users, teams, by org
- count of projects/JTs/WFJTs/creds/etc
- count of inventory source and projects by type
- possibly others


NO task names, role names, vars, etc.

**Comment by matburt** [comment]
Some other things:

* Hosts in inventory (relative to license)
* num toplevel resources
* cpu and memory usage of instances
* jobs and queue length per-instance and overall

We'll want to make sure we support `text-plain` on the endpoint and can generate stats that look like this: https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-example

An easy prometheus container can be stood up with:

`docker run -d --name=prometheus -p 9090:9090 prom/prometheus`

a toplevel endpoint like `/v2/metrics` can be used which should be exposed to system admin and system auditor rules.

We already have some time-series details at `/api/v2/dashboard` which we should carry over.

More info to follow.

**Comment by matburt** [comment]
Add overall healthy status (are any instances *down*)

**Comment by matburt** [comment]
Materialize data into a table containing singletons where possible.

Write a module that defines collection for all details, so things are collected and can be re-materialized at a time.

**Comment by matburt** [comment]
Two types of data:

* moment, roll up, overall resource summarization/counts
* deep analytics of jobs/events

This card should cover the first one.

**Comment by matburt** [comment]
document granularity of updates

**Comment by wenottingham** [comment]
Ideally, this data should have a configurable setting that sends this data over a configured logging integration every N seconds|minutes. It can default to 'off'. Depending on complexity/use, not all metrics may be sent this way.

**Comment by wenottingham** [comment]
Data summary
* version
* system ansible version
* Active Users (active sessions)
  * websocket listeners?
* Running Jobs
* cluster identifier (for tools pulling this from multiple clusters)
* By instance:
  * CPU (raw core count and loadavg)
  * Mem (raw mem count and current usage)
  * Dispatcher queue
  * Capacity calculation
  * consumed_capacity
  * percent_capacity_remaining
  * cpu_capacity
  * mem_capacity
* cluster topology? (IGs/isolated nodes, if not obvious from ^^^)
* Jobs_Total
* Jobs x hosts run
* tasks x hosts run
* job queue length (overall)
* license count
* Count of:
  * orgs
  * teams
  * users
  * inventories
  * creds
  * projects
  * JTs
  * WFJTs
  * hosts
  * schedules
  * inventory scripts?
  * venvs
  * completed jobs (by jt/wfjt/system job)
    * successful
    * Failed
    * cancelled(?)

**Comment by hypery2k** [comment]
any chance that this gots implemented? If not I can try doing a PR for this

**Comment by wwitzel3** [comment]
@hypery2k this is not currently implemented in master. You are welcome to take a crack at pulling together a PR for this. I'll be happy to review it and guide you along the way. If you don't start working on a PR please take the time to look at https://github.com/ansible/awx/pull/3284 as that has some recent work around analytics and metrics, you may be able to use some of the same code paths to expose information to a `/v2/metrtics` endpoint.

Also see @matburt post above about how to get started with coding this up.

**Comment by one-t** [comment]
Just wanted to mention, OPTIONS on the `/api/v2/metrics` endpoint indicates json is available, but it is not.

**Comment by rooftopcellist** [comment]
@one-t I have addressed that in this PR: https://github.com/ansible/awx/pull/3672/files  Thanks for pointing it out.

**Comment by kdelee** [comment]
@one-t going to close this as I think you are done. Please re-open if need be
