### ISSUE TITLE
[RFE] Add OIDC generic integration to AWX

### ISSUE THREAD

**Issue by jparrill** [ansible/awx#1967]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
As social auth2 for Google or Github have an integration method on WebUI, we need another for OIDC connect to provide a generic solution for auth/authz into AWX.

**Comment by etamminga** [comment]
Indeed, this would be very welcome

**Comment by hbjydev** [comment]
Bumping, this would be really useful.

**Comment by whitej6** [comment]
social-auth-core 4.3.0 now provides a generic OIDC backend and no longer requires a subclass to be implemented. My PR is tested against my development instance of KeyCloak as a generic provider.

**Comment by whitej6** [comment]
Implemented via #12552 and is in release https://github.com/ansible/awx/releases/tag/21.5.0
