### ISSUE TITLE
Copy Module Copies Locally To AWX Container, Not Ansible host

### ISSUE THREAD

**Issue by knockturnlabs** [ansible/awx#1968]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### ENVIRONMENT
* AWX version: 1.0.6.5
* AWX install method: docker on linux
* Ansible version:  2.5.2
* Operating System: CentOS 7
* Web Browser: FireFox

##### STEPS TO REPRODUCE

---
- name: ASA Backup
  hosts: "{{ host_name }}"
  gather_facts: no
  vars:
    remote_backup_host:
    remote_backup_dir:
    cli:
      host: "{{ inventory_hostname }}"
      username:
      password:
      authorize:
      auth_pass:

  tasks:
    - name: Retrieve Running-Config
      asa_command:
        commands:
          - more system:running-config
        provider: "{{ cli }}"
      register: show_run

    - name: Copy Running-Config To Server
      copy:
        content: '{{ show_run.stdout[0] }}'
        dest: /{{ remote_backup_dir }}/{{ inventory_hostname }}-{{ lookup('pipe','date +%d-%m-%Y') }}.txt

Run this via CLI (Works Perfect)
Run this via Tower (Copies contents LOCALLY to AWX Container instead of Ansible Host)

##### EXPECTED RESULTS

File is copied to Ansible host directory, as designated in DEST:

##### ACTUAL RESULTS

No directory found error appears.
OR
If I provide it with a valid directory inside of the AWX container, is then successfully gets copied to the AWX container volume.

How do I get this to stop trying to use the AWX container volume?

**Comment by aoyawale** [comment]
what is `/{{ remote_backup_dir }}/` ?
when you mean `ansible_host` you mean the target/destination?
also would probably work better if you use the `tempfile` module. https://docs.ansible.com/ansible/latest/modules/tempfile_module.html

**Comment by matburt** [comment]
No follow up in several months

**Comment by mhrznamn068** [comment]
Having same issue

**Comment by Workasis** [comment]
Same issue
