### ISSUE TITLE
Workflow Job Template extra variables don't resolve jinja variables correctly

### ISSUE THREAD

**Issue by mrj1m0thy** [ansible/awx#1970]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
If a variable in the "Extra Variables" section of a workflow template references another variable through jinja, it is not resolved by the ansible script.

##### ENVIRONMENT
* AWX version: 1.0.6.15
* AWX install method: docker on linux
* Ansible version:  2.5.4
* Operating System: Centos 7.5
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Create a new workflow template
2. Add a job template that has a ansible script that references a variable Ex: - debug: msg: "{{ message }}"
3. Add two variables to extra vars, one that uses the name from step 2 and its value is a reference to another variable, the second variable uses the name that is referenced by the first and has any value. Ex. message: "{{ reference }}" and reference: "value"
4. Execute workflow

##### EXPECTED RESULTS

Extra variables should dereference the jinja variable it is assigned, in the example above, the message on the output should be "value" 

##### ACTUAL RESULTS

The variable is taken literally and is not dereferenced. In the example above, the output is "{{ reference }}"

**Comment by ghjm** [comment]
When `ALLOW_JINJA_IN_EXTRA_VARS` is set to `template` or `always`, Jinja values are interpreted when set in extravars directly on a job template, but _not_ when set on _workflow_ job template.  It seems reasonable that this should work.  (Is there a counter-argument to this?)

**Comment by mrj1m0thy** [comment]
Is this a go? Would like to see this feature. I have multiple uses for it that I'd like to take advantage of.

**Comment by jjohnson1024** [comment]
I have some workflows that depended on this behavior previously. Those broke when upgrading to 1.0.6.17, bringing me here to look for the issue.

**Comment by sumkincpp** [comment]
:+1: doesn't currently work with workflows on latest build **1.0.6.49**

**Comment by FrederikSuijs** [comment]
I'm running into a similar issue, I think.
However this only affects my workflow when using multiple job templates. My first job template seems to be working fine, resolving the jinja variables.
It is only when entering the second job template, the problem appears.

**Comment by AlanCoding** [comment]
Thanks for giving feedback on this. As @ghjm detailed, the way to obtain this behavior now is to set `ALLOW_JINJA_IN_EXTRA_VARS=always`.

Also, we just merged a feature into current devel that allows use of workflows inside of other workflows. That is a complicating factor for any further configuration options, because there may be multiple _layers_ of workflow variables, and it would be monumentally difficult to tease these apart. Also keep in mind that schedules can provide variables.

Closing for now, if you have a more specific feature proposal we can address it as a new issue.

**Comment by FrederikSuijs** [comment]
Hi @AlanCoding , can you refer to the commit number where you are adding this extra functionality? So I can follow when it is released in stable.

**Comment by AlanCoding** [comment]
The commit where the functionality to _disallow_ jinja2 templating in these conditions was:

7074dcd677be72718dd5e0c490635c5cd9862f64

Again, you can re-allow it by changing that above setting. This setting is available in the UI, you just need to be superuser to change it. This issue's expectation is:

> Extra variables should dereference the jinja variable it is assigned, in the example above, the message on the output should be "value"

Does say much more than "unapply that prior change", and we definitely cannot do that.

One option that I have discussed in the past was a flag on the specific job template or workflow which would allow using variables in it to be templated. If that was done, it could only be set by a superuser. There are no plans for that right now, you are free to raise a new issue that requests some version of this.

**Comment by hari-hud** [comment]
To enable this setting you can use tower-cli:

`tower-cli setting modify ALLOW_JINJA_IN_EXTRA_VARS always`
