### ISSUE TITLE
ERROR! no action detected in task - during AWX install (docker)

### ISSUE THREAD

**Issue by itcrowdsource** [ansible/awx#1974]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY
I just tried to upgrade AWX but received an error message during install:

```
ERROR! no action detected in task

The error appears to have been in '/xxx/awx/installer/roles/check_vars/tasks/main.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- include_tasks: check_openshift.yml
  ^ here
```

##### ENVIRONMENT
* AWX version: latest
* AWX install method: docker on linux
* Ansible version:  latest
* Operating System: Ubuntu 16.04
* Web Browser: Not applicable

##### STEPS TO REPRODUCE

```
git pull
ansible-playbook -i inventory install.yml
```

##### EXPECTED RESULTS
Successful install

##### ACTUAL RESULTS
```
ERROR! no action detected in task
```

**Comment by ryanpetrello** [comment]
What version of Ansible are you using?

```
$ ansible --version
```

**Comment by acsrujan** [comment]
I got the same issue on release tag 1.0.6, Mac OSX.
ansible v 2.1.2.0 , Python v 2.7.10

**Comment by itcrowdsource** [comment]
@ryanpetrello sorry I overlooked your response, here's the output of ansible --version:
```
ansible 2.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

But in the meantime I have another issue: #2041 

So I'm unable the reproduce the problem.

**Comment by paszczus** [comment]
I have same problem. I have tried on ansible 2.4 and now 2.6.1.

**Comment by teo-chenglim** [comment]
Just upgrade my ansible version to 2.7 work prefect for me..

**Comment by wenottingham** [comment]
Closing, then - please reopen if there is a new issue.
