### ISSUE TITLE
Since an error occurred in the "Demo Project", you can not call the program with git.

### ISSUE THREAD

**Issue by doicom** [ansible/awx#1975]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI
 

##### SUMMARY

After installing the latest AWX, I updated the [Demo Project]of the project.
An error occurred in **TASK [Update project using git]**.
fatal: [localhost]: FAILED!

##### ENVIRONMENT
* AWX version: 1.0.6.15
* AWX install method: docker on linux
* Ansible version:  2.5.4
* Operating System:debian8.8
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Log in to AWX
Select [PROJECTS] from the menu.
Click the cloud mark [Get latest SCM revision] next to [Demo Project].

##### EXPECTED RESULTS

Successful.
You can call the program with git.

##### ACTUAL RESULTS

```
Using /etc/ansible/ansible.cfg as config file
 
 PLAY [all] *********************************************************************
 
 TASK [delete project directory before update] **********************************
 
 skipping: [localhost]

TASK [check repo using git] ****************************************************

skipping: [localhost]

TASK [update project using git] ************************************************

fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin https://github.com/ansible/ansible-tower-samples /var/lib/awx/projects/_4__demo_project", "msg": "Cloning into '/var/lib/awx/projects/_4__demo_project'...\nfatal: unable to access 'https://github.com/ansible/ansible-tower-samples/': Could not resolve host: github.com; Unknown error", "rc": 128, "stderr": "Cloning into '/var/lib/awx/projects/_4__demo_project'...\nfatal: unable to access 'https://github.com/ansible/ansible-tower-samples/': Could not resolve host: github.com; Unknown error\n", "stderr_lines": ["Cloning into '/var/lib/awx/projects/_4__demo_project'...", "fatal: unable to access 'https://github.com/ansible/ansible-tower-samples/': Could not resolve host: github.com; Unknown error"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```

##### ADDITIONAL INFORMATION

I use it under the proxy.

**Comment by wenottingham** [comment]
> I use it under the proxy.

This appears to be an error with your proxy configuration. What is it, and how is it set?

**Comment by doicom** [comment]
wenottingham 

Thank you for your answer.
This error occurred because the proxy settings in the inventory file were not reflected correctly.

Really sorry.
Inventory file was incorrect.
That is my lack of confirmation.
