### ISSUE TITLE
AWX Ldap Authentication Configuration steps

### ISSUE THREAD

**Issue by hnagireddygari** [ansible/awx#1976]
##### ISSUE TYPE
  - Documentation

##### COMPONENT NAME
 - UI
##### SUMMARY
I am new to AWX and Please provide AWX Ldap Authentication Configuration steps. I have ldap URL, admin_Username and Password of my ldap server. 

##### ENVIRONMENT
* AWX version: AWX 1.0.6.15
* AWX install method: docker on centos
* Ansible version:  2.5.4
* Operating System: Centos7
* Web Browser: Google Chrome (on Windows 10)

##### STEPS TO REPRODUCE

settings -> authentication -> sub category -> ldap -> --> ldap URL --> CN=<which_user_tower_or_ldapadminuser>,OU=?,DC=pro.example,DC=com --> password--> ldap user search --> ldap group search -> save

##### EXPECTED RESULTS
* Settings saved 
* Unable to login to AWX using ldapadminuser

##### ACTUAL RESULTS

* Setting saved and not able to login using ldapadminuser

##### ADDITIONAL INFORMATION

Can someone please send me step by step process that how to integrate LDAP in AWX UI. That would be a great and helpful to me to Configure LDAP. 

i am giving parameters as below:

LDAP Server URI:
ldap://pro.example.com:389(URL didnt mentioned due to compliance)

LDAP Bind DN:
CN=admin.gex,OU=Micro Users,DC=example,DC=com

LDAP User DN Template:
blank

LDAP Group Type:
MemberDNGroupType

LDAP Require Group:
CN=admin.gex,OU=Micro Users,DC=example,DC=com

LDAP Deny Group:
blank

Thanks 
Prasad

**Comment by aoyawale** [comment]
you can still use the same steps as tower https://docs.ansible.com/ansible-tower/latest/html/administration/ldap_auth.html

**Comment by wenottingham** [comment]
Closing; this tracker is for specific bugs, not user support. User support is best handled on the mailing list or IRC channel.
