### ISSUE TITLE
Error when create Notification from Ansible tower to HipChat

### ISSUE THREAD

**Issue by mbrother2** [ansible/awx#1981]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Error when create Notification from Ansible tower to HipChat

##### ENVIRONMENT
* AWX version: 3.2.0
* AWX install method: direct on linux
* Ansible version:  2.5.2
* Operating System: CentOS 7.5
* Web Browser: Chrome

##### STEPS TO REPRODUCE

- Config notification from Ansible Tower to HipChat
- Run test notification

##### EXPECTED RESULTS

Notification on HipChat when task finish

##### ACTUAL RESULTS

Test notification fail and error log in /var/log/tower/tower.log
"message": "Value u'Gray' for field 'color' is not in the enumeration: ['yellow', 'green', 'red', 'purple', 'gray', 'random']",

**Comment by mbrother2** [comment]
I must edit core file "/var/lib/awx/public/static/app.js" to change Gray value (two positions) to gray. Then I run test notification, it works!

**Comment by ryanpetrello** [comment]
@mbrother2 this is the issue tracker for the open source AWX project; it sounds like you're using Red Hat Ansible Tower.  This is a known issue that will be resolved in the next major version of Tower:

https://github.com/ansible/awx/pull/301
