### ISSUE TITLE
RFE: Allow to select the "intance_group" in a Job Template from a playbook

### ISSUE THREAD

**Issue by cesarfn4** [ansible/awx#1988]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Currently, the "instance_group" has to be selected manually in the job template forcing to create one for each of the instance groups. It would be useful in the case that someone just wants to use a single job template and a single inventory and needs to set an specify "instance_group"  for each of the host groups.

**Comment by wenottingham** [comment]
This is not planned.

1. This would require parsing the playbook before the job is assigned to run. It may not even be checked out of SCM at that point.
2. An 'instance group for each host group' implies you're expecting a playbook to run on multiple instance groups if it spans hosts. That's not how Ansible and AWX works; a job template only runs one invocation of ansible-playbook.
