### ISSUE TITLE
Jinja2 is very old in awx_task container

### ISSUE THREAD

**Issue by willthames** [ansible/awx#1989]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY

Jinja2 is very old in the awx_task container. Playbooks written with the expectation of a modern Jinja fail as a result.

##### ENVIRONMENT
* AWX version: 1.0.6.16
* AWX install method: docker
* Ansible version:  2.5.4
* Operating System: OS X
* Web Browser: firefox

##### STEPS TO REPRODUCE

```
$ docker run ansible/awx_task pip freeze | grep Jinja2
```

##### EXPECTED RESULTS

Jinja2==2.10

##### ACTUAL RESULTS

Jinja2==2.8

**Comment by poiriermike** [comment]
Experiencing the same issue on my end as well.

**Comment by poiriermike** [comment]
Looking into this, it appears that Jinja 2.8 is being pulled in via a `deb` packages from the `pgdg96` repository:

```
python-jinja2.noarch                                                                                                                         2.8-7.rhel7                                                                                                              @pgdg96  
```

**Comment by wenottingham** [comment]
This is pulled in at the system level for an ansible dependency.  I do not think we would specifically put a new one in the awx/ansible venvs.
