### ISSUE TITLE
AWX port change issue

### ISSUE THREAD

**Issue by Najeongho** [ansible/awx#1990]
Hi there.

I have AWX port change issue.
I would like to change the deploy port from 22 to 2222.

Take a look at this problem.

##### ISSUE TYPE
 - Function issue

##### COMPONENT NAME
 - UI : Menu -> Projects

##### SUMMARY
-> port 22: Connection refused

##### ENVIRONMENT
* AWX version: latest
* AWX install method: Kubernetes
* Ansible version:  2.5.4
* Operating System: CentOS Linux 7.5
* Web Browser: Chrome 67.0

##### STEPS TO REPRODUCE
1. When the awx_task Container (POD) is started with Kubernetes, the following command will be auto executed.
-> Command: ["/bin/sh", "-c", "echo 'root::0:0:root:/root:/bin/bash' >> /etc/passwd;su -c 'sed -i -e \"s/\\#remote_port/remote_port/g\" -e \"s/= 22/= 2222/g\" /etc/ansible/ansible.cfg'"]
2. Sign in to AWX.
3. Create gitlab credential.
-> Menu -> Credentials -> Create a new credential -> Insert Name,Org,Credential type(Source Control) -> Input SCM Private key -> Save
4. Create gitlab project
-> Menu -> Projects -> Create a new project -> Insert Name,Org,SCM type(Git) -> SCM URL(My gitlab ssh url(2222 Port), Ex. git@(My gitlab domain):(My gitlab project).git) -> SCM Credential(Select gitlab credential name) -> Save
5. Get latest SCM revision

##### EXPECTED RESULTS
Connected 2222 port, I thought I would bring the git source successfully.

##### ACTUAL RESULTS
The following error occurred:
{
    "_ansible_parsed": true,
    "stderr_lines": [
        "Cloning into '/var/lib/awx/projects/_5__project'...",
        "ssh: connect to host (My gitlab domain) port 22: Connection refused",
        "fatal: Could not read from remote repository.",
        "",
        "Please make sure you have the correct access rights",
        "and the repository exists."
    ],
    "cmd": "/usr/bin/git clone --origin origin '' /var/lib/awx/projects/_5__project",
    "_ansible_no_log": false,
    "stdout": "",
    "changed": false,
    "invocation": {
        "module_args": {
            "executable": null,
            "force": false,
            "refspec": null,
            "reference": null,
            "dest": "/var/lib/awx/projects/_5__project",
            "umask": null,
            "clone": true,
            "verify_commit": false,
            "update": true,
            "accept_hostkey": true,
            "ssh_opts": null,
            "repo": "git@(My gitlab domain):(My gitlab project).git",
            "depth": null,
            "version": "HEAD",
            "bare": false,
            "recursive": true,
            "remote": "origin",
            "key_file": null,
            "archive": null,
            "track_submodules": false
        }
    },
    "stderr": "Cloning into '/var/lib/awx/projects/_5__project'...\nssh: connect to host (My gitlab domain) port 22: Connection refused\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n",
    "rc": 128,
    "msg": "Cloning into '/var/lib/awx/projects/_5__project'...\nssh: connect to host (My gitlab domain) port 22: Connection refused\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.",
    "stdout_lines": []
}

##### ADDITIONAL INFORMATION
None.

**Comment by Najeongho** [comment]
Can anyone help me about this issue?

**Comment by jakemcdermott** [comment]
Hello Najeongho,

Thanks for creating this issue. Since this is a question about configuration and not a bug, you should reach out to our community mailing list or join our IRC channel. (see the 'where can I find support for awx' here: https://www.ansible.com/products/awx-project/faq).
