### ISSUE TITLE
WEBUI - Re Run jobs on Failed hosts fails in French language

### ISSUE THREAD

**Issue by adavid44** [ansible/awx#1993]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

On French UI, when trying to re run template on failed hosts, it fails with pop up "hosts: "échec" is not a valid choice" : 

##### ENVIRONMENT
* AWX version: 1.0.6.16
* AWX install method: docker on linux
* Ansible version:  2.5.4
* Operating System: Ubuntu 16.04
* Web Browser: Firefox

##### STEPS TO REPRODUCE

![image](https://user-images.githubusercontent.com/40363860/41546494-1097666c-731e-11e8-9c06-1a32a518e964.png)

![image](https://user-images.githubusercontent.com/40363860/41546482-09af3708-731e-11e8-9b84-a081078294d1.png)

##### EXPECTED RESULTS

It re run on failed hosts

##### ACTUAL RESULTS

 it fails with pop up "hosts: "échec" is not a valid choice"

##### ADDITIONAL INFORMATION

I found that if I change on the container awx_web ( docker exec -ti awx_web /bin/bash ) in `/var/lib/awx/public/static/languages/fr.json` the "Failed":"Échec" by "Failed":"Failed" it works again but the UI is not in french anymore : 

![image](https://user-images.githubusercontent.com/40363860/41546742-ba414872-731e-11e8-8e63-c7e1b7a06b68.png)

**Comment by ryanpetrello** [comment]
This _should_ just be a case of over-aggressive i18n usage in the UI code.

**Comment by ryanpetrello** [comment]
@MuLoT44 we've just released 1.0.7, which we believe resolves the underlying issue here. You can try it out here: https://github.com/ansible/awx/releases/tag/1.0.7

Let us know if you're still seeing this issue after installing the latest awx - thanks!
