### ISSUE TITLE
AWX: Jobs View not working while running on https

### ISSUE THREAD

**Issue by sudheer6122** [ansible/awx#1995]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Unable to fetch job details on AWX. Getting 
ERROR! Invalid search term entered. GET returned: -1

##### ENVIRONMENT
* AWX version: 1.0.6.16
* AWX install method: docker on linux, docker for mac
* Ansible version: 2.3.1.0
* Operating System: Linux, Mac
* Web Browser: Chrome, Firefox

##### STEPS TO REPRODUCE
Launch any SCM job from UI and click on jobs. API call gets failed and error is shown on UI.

##### EXPECTED RESULTS
Jobs view should work

##### ACTUAL RESULTS
![screen shot 2018-06-18 at 11 38 29 am](https://user-images.githubusercontent.com/16406506/41555759-888a5f34-72ed-11e8-9265-8ff77f229d5b.png)

##### ADDITIONAL INFORMATION
Running nginx on https on port 443. Please find the nginx conf file.
[nginx.txt](https://github.com/ansible/awx/files/2112589/nginx.txt)

**Comment by wenottingham** [comment]
You modified the nginx configuration (I suspect for a non-docker install?); I suspect you did something wrong.

This is best figured out the mailing list/irc channel; this is not a bug report.

**Comment by sudheer6122** [comment]
@wenottingham I'm able to replicate the same issue in 1.0.6.16 on http (No nginx.conf changes). Can you please let me if I can raise new issue ?
