### ISSUE TITLE
Group variables are not overwritten after syncing a inventory of type "Sourced from a Project"

### ISSUE THREAD

**Issue by cesarfn4** [ansible/awx#1997]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Group variables are not overwritten after syncing a inventory of type "Sourced from a Project".

##### ENVIRONMENT
* AWX version: N/A
* Ansible version: N/A

##### STEPS TO REPRODUCE
1. Create a git repository with the following structure:
- hosts.yml:
```
all:
  host:
    host01
    host02
```
- group_vars/all.yml
```
all:
  ansible_user: root
```

2. In Tower, create a git project pointing to the repository where we have our inventory files.
3. In Tower, create a new inventory of type "Sourced from a Project" with the options "Overwrite" and "Update on project change" enabled.
4. After the first sync, check the "Details" tab in the inventory to check the "Variables" field. The content should be exactly this:
```
all:
  ansible_user: root
```
5. Back to the git repository, modify the "group_vars/all.yml" file removing the "all:" and fixing the indent.
```
ansible_user: root
```
6. In Tower, sync the project and the inventory again.
8. Go to the Inventory and check the "Details" tab, in the "Variables" field we can now see the "ansible_user" variable has been duplicated.
```
all:
  ansible_user:root
ansible_user:root

```
##### EXPECTED RESULTS
Tower should overwrite the variables:
```
ansible_user: root
```

##### ACTUAL RESULTS
Tower should not duplicate the variable "ansible_user: root":
```
all:
  ansible_user: root
ansible_user: root
```

**Comment by wenottingham** [comment]
This is intentional; group_vars/all are set at the inventory level, and inventory-level vars are not completely replaced, as you could have multiple dynamic sources in a single inventory, causing a conflict.
