### ISSUE TITLE
RFE: have a setting to change service loglevel

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#1998]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY

LOG_AGGREGATOR_LEVEL sets the log level used by external logging integrations.

There is no knob that changes the default logging level used by the service itself to syslog/stdout. Ideally, LOG_AGGREGATOR_LEVEL would set both.

##### ENVIRONMENT
* AWX version: any

**Comment by shawndwells** [comment]
Is there an expected release for this? Currently required for a potential customer to use Ansible.

**Comment by Spredzy** [comment]
this is verified and working as expected
