### ISSUE TITLE
AWX Jobs view failing on UI

### ISSUE THREAD

**Issue by sudheer6122** [ansible/awx#2003]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Unable to fetch job details on AWX. Getting 
ERROR! Invalid search term entered. GET returned: -1

##### ENVIRONMENT
* AWX version: 1.0.6.16
* AWX install method: docker on linux, docker for mac
* Ansible version: 2.3.1.0, 2.4.0.0
* Operating System: Linux, Mac
* Web Browser: Chrome, Firefox

##### STEPS TO REPRODUCE
Launch any SCM job from UI and click on jobs. API call gets failed and error is shown on UI.

##### EXPECTED RESULTS
Jobs view should work

##### ACTUAL RESULTS

![screen shot 2018-06-20 at 3 27 51 pm](https://user-images.githubusercontent.com/16406506/41687902-8a0acef4-749e-11e8-91e0-0f2e5bd8b634.png)

##### ADDITONAL INFORMATION
Please find the screen recording. 
[jobs_issue.zip](https://github.com/ansible/awx/files/2121336/jobs_issue.zip)

**Comment by krepflap** [comment]
I can confirm this, happens at least since 1.0.6.8 and is still present in 1.0.6.17. Happens only with project syncs.

In the API I can find the job output at `/project_updates/:id/stdout` so it's definitely being stored in the database, just that it's not accessible anymore from the UI.

**Comment by jaredevantabor** [comment]
Are there any console errors you can find on the web console?

**Comment by sudheer6122** [comment]
@jaredevantabor Please find the screenshot. xhr calls are failing for playbook_on_stats event.
![screen shot 2018-06-21 at 10 17 55 am](https://user-images.githubusercontent.com/16406506/41734701-945ac9ec-753c-11e8-817f-bcba404be4f4.png)

**Comment by sudheer6122** [comment]
@jaredevantabor Any update on the issue ?

**Comment by jakemcdermott** [comment]
With a fresh, non-upgraded install of the latest devel container image I'm not seeing this bug:

![project_sync](https://user-images.githubusercontent.com/9753817/41864501-3e5b6530-7878-11e8-9d7b-dc8a844fd71a.gif)

At any rate, that specific api query has been removed downstream - This will be resolved when those code changes reach devel.

**Comment by sudheer6122** [comment]
@jakemcdermott I tried awx_web:latest container image. I'm still seeing the issue. Can you please suggest some fix?

**Comment by dillonwelch** [comment]
I am also seeing the issue and just installed today.

**Comment by jValdron** [comment]
Disable your AdBlocker on AWX. Had this issue for a while too, but it's always been because of uBlock. If you check on that failed request, you'll see that it errors out with ERR_BLOCKED_BY_CLIENT.

**Comment by dillonwelch** [comment]
That solved the issue for me, thanks.
