### ISSUE TITLE
[External logger] host field in job event payload conflicts with Splunk internal field

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#2004]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
When sending job event logs, the field `host` needs to be modified by a custom rule in Splunk if it is to be used. Ordinarily, Splunk uses this field to report what address _it_ received the log from.

##### ENVIRONMENT
* AWX version: any
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Set up external logging with splunk, include job events

##### EXPECTED RESULTS

No manual rules needed

##### ACTUAL RESULTS

Manual rule needed to rename the host field

##### ADDITIONAL INFORMATION

Options include:

 - rename the key "host" to something else
 - rename it just for Splunk
 - take all of our data and nest it under some other sub-field
 - ???

**Comment by zyphermonkey** [comment]
I'm also having this issue.  
I suggest updating `host:` to `host_id:`, but anything other than the `host` will work.

**Comment by zyphermonkey** [comment]
I added this to my indexers behind our HEC VIP and while not an ideal solution it does keep the host field from being used.

**props.conf**  
```
[source::http:ansible-tower]
SEDCMD-ansible-tower-hostname = s/"host":/"host_id":/
```

**Comment by AlanCoding** [comment]
Closing due to age, existing workaround.
