### ISSUE TITLE
[External logger] Activity stream logs are sent with `changes` as a string

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#2005]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
External logs for the activity stream show the `changes` field as a parsed JSON string, instead of as a sub-dict

##### ENVIRONMENT
* AWX version: any
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Set up external logger & send activity stream, view the raw text of the body being sent

##### EXPECTED RESULTS

Everything is JSON

##### ACTUAL RESULTS

JSON nested inside of JSON. Meaning that the log aggregator must parse the top-level data, and then replace the string in the `changes` field with a dict which came from parsing this value.

**Comment by ryanpetrello** [comment]
fixed via https://github.com/ansible/awx/pull/2618
