### ISSUE TITLE
[External logger] Splunk periodic log rejection (needs retry implemented)

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#2008]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Some external loggers will intermittently reject some attempts to send log messages. We need a retry logic in order to fully solve this. It might be a simple if the fix is specific to Splunk, otherwise, we may need to utilize our messaging system to process logs.

##### ENVIRONMENT
* AWX version: any
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Setup external logger with Splunk, send job events, run for >100 job events.

Inspect count of job events in Splunk versus Tower over a congruent filter.

##### EXPECTED RESULTS

Counts are the same

##### ACTUAL RESULTS

Splunk is missing some events.

We know this to be related to a the error:

```
Traceback (most recent call last):
  File "/lib/python2.7/site-packages/awx/main/utils/handlers.py", line 63, in _wrapped
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/requests_futures/sessions.py", line 73, in wrap
    resp = sup(*args_, **kwargs_)
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
```

Since this is only intermittent, it is beyond the scope of external logger to resolve this actual issue (and is believed to be dependent on the Splunk server behavior). However, to fix this practically we need retry logic when sending the log.

**Comment by shanemcd** [comment]
I believe this problem was solved when we moved to rsyslog.
