### ISSUE TITLE
Can not chose vault credential type when loading inventory file at source

### ISSUE THREAD

**Issue by tshohe** [ansible/awx#2016]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

In order to use the inventory managed by SCM even with AWX, I am planning to load it into AWX by the following procedure.

1. Inventory > Source
2. Source: Source Project
3. Inventory file: Inventory file that I want to load

It will work if there is no file encrypted with ansible-vault.
But, I got below error message
"ERROR! Attempting to decrypt but no vault secrets found"

https://github.com/ansible/awx/blob/72f2994cc5f00848dd3e68074c32cef88707f48b/awx/ui/client/src/inventories-hosts/inventories/related/sources/edit/sources-edit.controller.js#L292

When source is scm, it seems that only cloud type can be chosen. So I can not chose vault credential type.
But, I am not familiar with Angular.js so please point out if it is wrong.

If I manage inventory in Ansible AWX, it'll be well.
However, I also want to execute with ansible-playbook commands.

It will be helpful if you let me know if there is workaround

##### ENVIRONMENT
* AWX version: 10.0.6.12
* AWX install method: docker on linux
* Ansible version:  2.5.3
* Operating System: CentOS 6.9
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Inventory > Source
2. Source: Source Project
3. Push glass icon

Since I am using the Japanese version, name may be different

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/4979936/41834191-4b9d0224-788e-11e8-984c-bc93edb50f09.png)

**Comment by wenottingham** [comment]
Hi. We've had this filed before. You can find more information here: #223
