### ISSUE TITLE
Added Golang SDK support

### ISSUE THREAD

**Issue by Colstuwjx** [ansible/awx#2017]
Hi team,

I'm happy to share a golang SDK for awx v2 api: https://github.com/Colstuwjx/awx-go, and wishes more users or feedbacks.

If someone agrees, I will be happy to take a PR to update our README and link it.
Thanks.

**Comment by ryanpetrello** [comment]
Hey @Colstuwjx,

Thanks for contributing this!  I'm going to close this, as we generally use Github issues to track bugs in awx, but you might consider announcing this over on our mailing list and IRC chatroom:

https://groups.google.com/forum/#!forum/awx-project
`#ansible-awx` on freenode IRC

**Comment by Colstuwjx** [comment]
Thanks!
