### ISSUE TITLE
SELinux set to "enforcing" will not allow login.

### ISSUE THREAD

**Issue by mbrost** [ansible/awx#202]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME

 - UI
 - Installer

##### SUMMARY

Having set SELinux to permissive during the installation everything worked as expected (docker method). Now when I set SELinux to enforcing, AWX shows this:
![sever_error](https://user-images.githubusercontent.com/25187669/30564991-7bdbdaf4-9c62-11e7-9ca4-639781e22908.png)

I am new to SELinux, I know it gets a rep of being a pain, however I'm doing my best to have SELinux set back to "enforcing", as it is our policy. The Ansible Tower documentation states that only "targeted" SELinux policy is supported and can be set to enforcing: [http://docs.ansible.com/ansible-tower/latest/html/installandreference/install_notes_reqs.html#notes-for-red-hat-enterprise-linux-and-centos-setups](url)

Using `ls -Z /usr/share/nginx/html` within the "awx_web" docker container, which returned this:

`-rw-r--r--. root root system_u:object_r:svirt_sandbox_file_t:s0:c606,c797 404.html`
`-rw-r--r--. root root system_u:object_r:svirt_sandbox_file_t:s0:c606,c797 50x.html`
`-rw-r--r--. root root system_u:object_r:svirt_sandbox_file_t:s0:c606,c797 index.html`
`-rw-r--r--. root root system_u:object_r:svirt_sandbox_file_t:s0:c606,c797 nginx-logo.png`
`-rw-r--r--. root root system_u:object_r:svirt_sandbox_file_t:s0:c606,c797 poweredby.png`

Does this need to be modified, what are my next steps, or what could be included to the install.yml playbook to allow for SELinux modificiation? Perhaps a variable?

##### ENVIRONMENT

* AWX version: 1.0.0.284
* Ansible version:  2.3.1.0
* Operating System: CentOS Linux 7.3.1611
* Web Browser: Google Chrome Version 60.0.3112.113

##### STEPS TO REPRODUCE

On host:
`# setenforce 1`

On browser
`http://ipaddress`

##### EXPECTED RESULTS

Expected to see AWX login.

##### ACTUAL RESULTS

AWX loads, but only shows a title "Sever Error" with the description, "A server error has occurred." When SELinux not set to enforcing but set to permissive, AWX loads and login is fine.

##### ADDITIONAL INFORMATION

None

**Comment by matburt** [comment]
This totally does need to be expanded in the containers and I haven't managed to get around to that just yet!

**Comment by ragingpastry** [comment]
It appears that a default installation of AWX in local docker containers will fail if SELinux is enabled due to this issue. Has this gotten any more notice?

**Comment by matburt** [comment]
I haven't been able to circle back to this yet so feel free to pick it up and work on it if you want.

I'd also like to see the container errors that pop up during this put in this issue.

**Comment by lah-aaron** [comment]
I do not have time to replicate the environment but this article will help you diagnose.
https://osric.com/chris/accidental-developer/2017/11/selinux-audit2why-audit2allow-policy-files/

**Comment by wenottingham** [comment]
In the intervening time we have rebased the entire OS underneath, and we do run dev env containers with SELinux enforcing on the host, not to mention OCP installs. Assuming this is fixed, please open a new issue if it reoccurs.
