### ISSUE TITLE
[Feature Request] Add revision number inside the Docker image

### ISSUE THREAD

**Issue by ghost** [ansible/awx#2022]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - Installer

##### SUMMARY

It is hard to find out at which time the Docker image, that are registered on Docker Hub, has been build.
So it is hard to trace it back, when a bug occurs. 

To solve this problem, it would be nice to have a file inside the container image like 'xxx.release',
which shows the revision number from the time it was build.

**Comment by jakemcdermott** [comment]
Hi nyasu1111, you can get the container image version from within a running container using an `awx-manage` command:

```
[root@awx-server ~]# docker exec awx_web awx-manage version
1.0.6.28
```
