### ISSUE TITLE
[Feature Request] Remove old projects' files

### ISSUE THREAD

**Issue by nikita-shchipachev** [ansible/awx#2023]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
- Installer

##### SUMMARY
Unnecessary projects' directories should be removed.

##### ENVIRONMENT
* AWX version: 1.0.2.74
* AWX install method: docker on linux
* Ansible version: 2.4.2.0
* Operating System: Ubuntu 16.04
* Web Browser:

##### STEPS TO REPRODUCE
- Create a project
- Do SCM update
- Delete the project

##### EXPECTED RESULTS
There are no files related to removed project in root directory (`/var/lib/awx/projects`)

##### ACTUAL RESULTS
The files still there

##### ADDITIONAL INFORMATION
The main problem is extremely fast exhaustion of disk free space when AWX is intensively used and project's repositories are heavy.
The situation is getting worse when you will try cleanup old files by yourself. It's hard to determine which files in use right now and which free for removing even using AWX API.
Probably we need some indexing of directories to relate it with AWX internal objects and some kind of garbage collector (a management job?) which will purge orphans files.

**Comment by wenottingham** [comment]
-> #426
