### ISSUE TITLE
Win_Updates: failed_update_count is not always returned

### ISSUE THREAD

**Issue by TylerKerrACG** [ansible/awx#2025]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME

 - API

##### SUMMARY

The win_updates module is not properly documented. The "failed_update_count" return value is not always returned.

##### ENVIRONMENT
* AWX version: 1.0.6.16
* AWX install method: docker on linux
* Ansible version:  2.5.4
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Run a task that installs updates on a target that has no updates required.

##### EXPECTED RESULTS

The "failed_updates_count" field is returned with a value of 0

##### ACTUAL RESULTS

The "failed_updates_count" field is undefined

##### ADDITIONAL INFORMATION

The "installed_update_count" field is properly defined as 0, even when no updates were found. The documentation specifies that the field should always be returned. [https://docs.ansible.com/ansible/latest/modules/win_updates_module.html#win-updates-module](url)

**Comment by wenottingham** [comment]
This repository is for AWX, I believe you are looking for https://github.com/ansible/ansible/

**Comment by TylerKerrACG** [comment]
Sorry about that, followed the wrong link.
