### ISSUE TITLE
Vault credentials should be selectable when launching job template

### ISSUE THREAD

**Issue by bensiebert** [ansible/awx#2027]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
Support selecting vault credentials when launching job templates

##### ENVIRONMENT
* AWX version: 3.2.4

##### ADDITIONAL INFORMATION
Since the introduction of different credential types, there is a 1-to-1 relation between job template and vault credential. In the past vault credential was tied to machine credentials which were selectable using the prompt-on-launch feature.

![image](https://user-images.githubusercontent.com/5683792/42033226-74d307ce-7adc-11e8-86e9-04983cb463df.png)

The reason for this feature is that we have environments with different levels of security which have distinct vault passwords. For environments with less strict security settings we want the vault credentials to be pre-filled while for stricter environments we want the password to be prompted.

**Comment by AlanCoding** [comment]
Vault should appear in that credential type dropdown in the current version

![screen shot 2018-06-28 at 10 18 51 am](https://user-images.githubusercontent.com/1385596/42040022-b9e96cd8-7abc-11e8-8558-12ace918b0d2.png)

> AWX version: 3.2.4

This isn't an AWX version, if it's a Tower issue, then this probably isn't the right forum. Several features have been between that version of Tower and the current AWX, and this issue queue can only address changes to the design of the current AWX.
