### ISSUE TITLE
RFE: Audit login/logoff to Ansible Tower

### ISSUE THREAD

**Issue by shawndwells** [ansible/awx#2031]
##### ISSUE TYPE
 - Feature Idea
 - Documentation

##### COMPONENT NAME
 - UI

##### SUMMARY
Regulatory frameworks such as PCI-DSS, HIPAA, and US Government, require applications to audit user login/logoff events. Currently logon/logoff events to Tower are not audited by default. 

@jaredhocutt stepped through the code and noticed logons are using logger.info:

https://github.com/ansible/awx/blob/72f2994cc5f00848dd3e68074c32cef88707f48b/awx/api/generics.py#L73
`````
        if current_user and getattr(current_user, 'pk', None) and current_user != original_user:
            logger.info("User {} logged in.".format(current_user.username))
`````

and for logouts:

https://github.com/ansible/awx/blob/72f2994cc5f00848dd3e68074c32cef88707f48b/awx/api/generics.py#L97
`````
        if (not current_user or not getattr(current_user, 'pk', True)) \
                and current_user != original_user:
            logger.info("User {} logged out.".format(original_user.username))
`````

Technically this is fine, but documentation seems to be missing on how to switch Tower from WARNING log level to INFO.

##### EXPECTED RESULTS
- Update documentation on how to switch Tower to INFO vs default WARNING log level; or,
- Update login/logoff events to use logger.warning

(using INFO seems ideal)

Attempted to find docs on switching to INFO, but this does not appear to be a user configurable option. If it is user configurable and someone can point out where, I'll submit a PR to update the security docs.

**Comment by shawndwells** [comment]
related: https://github.com/ansible/awx/issues/683 Set global logging to INFO partial working

**Comment by wenottingham** [comment]
I think https://github.com/ansible/awx/issues/1998 is more relevant to switching the loglevel.

**Comment by shawndwells** [comment]
@wenottingham https://github.com/ansible/awx/issues/1998 seeks to update ``LOG_AGGREGATOR_LEVEL`` to effect local and remote logging. That'd be a great approach.

An alternative is to update the existing logon/logoff events to WARNING vs INFO.

Both accomplish the same thing. What's preferred? Update the existing code or wait to update all AWX logging?

**Comment by wenottingham** [comment]
#1998 is the better answer, as it solves more issues rather than just changing the priority of a few messages.

**Comment by matburt** [comment]
Closing, we'll track changes on #1998
