### ISSUE TITLE
"Prompt on launch" variables ignored

### ISSUE THREAD

**Issue by gnosek** [ansible/awx#2033]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When a job template specifies prompt on launch fields (e.g. limit or tags), the form to enter the values appears but the submitted API request contains defaults. This is potentially catastrophic if you run a playbook on your whole fleet instead of checking it on one machine.

##### ENVIRONMENT
* AWX version: AWX 1.0.6.23
* AWX install method: docker on linux
* Ansible version:  2.5.5
* Operating System: Linux on AWX, macOS on client
* Web Browser: Chrome 67

##### STEPS TO REPRODUCE

1. Create a job template.
2. Check one of the "Prompt on launch" checkboxes
3. Run the template
4. In the form that appears, change the prompted-for value from its default
5. Submit the form to launch the job

##### EXPECTED RESULTS

Job launches with overrides entered in the form applied

##### ACTUAL RESULTS

Job launches with job defaults which cannot be overridden

##### ADDITIONAL INFORMATION

Job summary just before launch:

![image](https://user-images.githubusercontent.com/3634/42097808-5de864ea-7bb9-11e8-89be-28847ad91cf2.png)

Actual request sent to start the job. Note `limit` is empty despite being specified by the user.

![image](https://user-images.githubusercontent.com/3634/42097837-6a88b8ee-7bb9-11e8-9be3-eee4d7421fec.png)

Known working version (Docker `ansible/awx_web` image ID): 26c177132af0
Known broken version (Docker `ansible/awx_web` image ID): 8be3712d96dc

**Comment by sumkincpp** [comment]
Latest **ansible/awx_web:1.0.6.23** a818f6952a06 is not affected.

Checked limit and custom extra variable to work properly.

**Comment by sumkincpp** [comment]
Met this bug: **ansible/awx_web:1.0.6.23** image id=037af4a6dc21 is affected

**Comment by sumkincpp** [comment]
:+1: for prioritizing this, not working on latest 1.0.6.39 


This one may be related issue #2148

**Comment by ryanpetrello** [comment]
@gnosek @sumkincpp we've just released 1.0.7, which we believe resolves the underlying issue here. You can try out here: https://github.com/ansible/awx/releases/tag/1.0.7

Let us know if you're still seeing this issue after installing the latest awx - thanks!
