### ISSUE TITLE
ansible logging - can we have details of what data forms part of awx, activity_stream, job_events, system_tracking

### ISSUE THREAD

**Issue by akcrisp** [ansible/awx#2038]
##### ISSUE TYPE
<
 - Documentation

##### COMPONENT NAME

 - UI
 

##### ENVIRONMENT
* AWX version: 1.0.6.8
* AWX install method: docker on linux, 
* Ansible version: 2.5.4
* Operating System: RHEL 7.4
* Web Browser: Chrome

##### STEPS TO REPRODUCE
I've looked in the ansible tower docs but I can't find anywhere where it actually details what data forms part of the following -

awx, activity_stream, job_events, system_tracking

Some of it is obvious but others are not. We need to decide what needs to be logged for security related data.

Can someone clarify ?

Andy

**Comment by AlanCoding** [comment]
Maybe this will help?

https://github.com/ansible/awx/blob/devel/docs/logging_integration.md

some things might have changed since that was written, but it covers the basics of the general metadata vs. the logger-specific fields.

**Comment by akcrisp** [comment]
Hmmm so what’s not covered by that is the awx logger - is this what was called job_status?

As we now have -

awx, activity_stream, job_events, system_tracking 

The doc references - 

job_status, activity_stream, job_events, system_tracking

**Comment by AlanCoding** [comment]
yeah, that was a latter addition and the doc just needs to be updated.

the awx logger includes logs that would normally be written to a file. It contains the standard metadata that all logs have, but other than that it only has the message from the log statement.

**Comment by akcrisp** [comment]
When you say logged to a file - would that be messages that include security data that might go in /var/log/messages or secure ?

Ultimately I need to know if I want to capture all security related events is it sufficient just to log activity_stream ?
