### ISSUE TITLE
Schedule page broken

### ISSUE THREAD

**Issue by subuk** [ansible/awx#204]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Schedule edit page has javascript errors.

##### ENVIRONMENT

* AWX version: 1.0.0.484, 1.0.0.352
* Ansible version:  2.3.1.0
* Operating System:
      client: macOS Sierra
      server: Amazon Linux 2017.3
* Web Browser: Google chrome 60.0.3112.113

##### STEPS TO REPRODUCE

Just open any schedule page, for example http://127.0.0.1/#/management_jobs/management_jobs/1/schedules/edit/1?schedule_search=page_size:20;order_by:name

##### EXPECTED RESULTS

I can edit or create new schedule

##### ACTUAL RESULTS

http://joxi.ru/xAeGlXYhpK3dXm
http://joxi.ru/KAxeRMYcMDdaNr

**Comment by iyurev** [comment]
Hi, I already wrote about this https://github.com/ansible/awx/issues/164

**Comment by subuk** [comment]
Okay, haven't seen it, lets close this issue as duplicated.

**Comment by ykisialevich** [comment]
I had similar issue in version 1.0.5 (Schedule page was broken), but in my case this fix helped me:
1. set SELINUX=disabled in /etc/selinux/config
2. setenforce 0
3. reboot
