### ISSUE TITLE
rabbitmq missing

### ISSUE THREAD

**Issue by SLusenti** [ansible/awx#2042]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

when running <pre> ansible-playbook -i inventory install.yml </pre>

it gives this error:
```

TASK [local_docker : Activate rabbitmq container] *************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))"}

```

##### ENVIRONMENT
* AWX version: latest
* AWX install method:  docker on linux
* Ansible version:  2.5.5
* Operating System: centos 7
* Web Browser: firefox (latest)

##### STEPS TO REPRODUCE

```
git clone [...]/ansible/awx.git
cd awx
git clone [...]/ansible/awx-logos.git
cd installer
#modify inventory to run locally with docker
vi inventory
````

##### EXPECTED RESULTS

no rabbitmq errors

##### ACTUAL RESULTS

```

TASK [local_docker : Activate rabbitmq container] *************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))"}

```

**Comment by SLusenti** [comment]
in the local_docker role there's no ansible/rabbitmq:{{ rabbitmq_version }} file, this could be the issue...

**Comment by SLusenti** [comment]
I saw that it was a problem with docker 1.13.x installed with rpm and docker-py.
I solved by migrating to docker-ce to the latest version.

**Comment by wenottingham** [comment]
Thanks for the update, closing.
