### ISSUE TITLE
Group vars no longer editable after saving duplicate key

### ISSUE THREAD

**Issue by abedwardsw** [ansible/awx#2043]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
After accidentally modifying the group variables of an inventory, the UI fails to show the "bad/duplicate" values so that it can be fixed.

##### ENVIRONMENT
* AWX version: 1.0.6.23
* AWX install method: docker on linux
* Ansible version:  2.5.5
* Web Browser: Chrome

##### STEPS TO REPRODUCE
1. login to AWX
2. navigate to "INVENTORIES" and edit a inventory
3. under the "Variables" section enter the following content:
```
#...
#50 other keys I don't want to lose
#...
my_duplicate: herehere
my_duplicate: therethere
```
4. click save
5. error will be displayed after save: "ERROR! Attempts to parse variables as JSON and YAML failed.  Last attempt returned: duplicated mapping key at line x, column y: ...."
6. there is no way to bring back your old inventory variables so you can fix them.

##### EXPECTED RESULTS
1. UI/backend should prevent you from saving "bad data"
or
2. UI/backend should present the "bad" data so it can be fixed

##### ACTUAL RESULTS
bad data cannot be edited, so you have to find another way to go find your old variables and fix the issue

##### ADDITIONAL INFORMATION
Workaround to get your "old" values is to use the HTTP API to go get them, then you can manually fix and re-update the variables.

**Comment by AlanCoding** [comment]
I can confirm that I am able to reproduce this.

![screen shot 2018-11-19 at 1 23 16 pm](https://user-images.githubusercontent.com/1385596/48726841-8a575580-ebfe-11e8-90c7-c22bbb024bc6.png)

This is the UI after saving, but if you reload, you get the message again.

The API actually accepts the data here, and therein lies the problem, it seems.

variables from API:

```json
   "variables": "#...\n#50 other keys I don't want to lose\n#...\nmy_duplicate: herehere\nmy_duplicate: therethere",
```

**Comment by AlanCoding** [comment]
My 2 cents:

This should be solved by having the API throw errors when given duplicate keys. Some approaches to modifying the YAML loading logic to accomplish this:

https://gist.github.com/pypt/94d747fe5180851196eb

If someone wanted to dig into that, this seems very actionable to me.

**Comment by unlikelyzero** [comment]
let's retest this

**Comment by unlikelyzero** [comment]
no stub necessary
