### ISSUE TITLE
API: Provide a way to obtain most recent job results

### ISSUE THREAD

**Issue by willthames** [ansible/awx#2045]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
/v2/jobs returns the first page (or all pages) of jobs from oldest to newest. A mechanism to reverse that order so that I could get the most recent page of jobs

##### ENVIRONMENT
* AWX version: 1.0.6
* AWX install method: kubernetes
* Ansible version:  2.6.0
* Operating System: Linux
* Web Browser:

##### STEPS TO REPRODUCE

/v2/api/jobs

##### EXPECTED RESULTS

A mechanism to sort by age descending

##### ACTUAL RESULTS

Results always returned oldest first, so have to paginate or request all results

**Comment by wenottingham** [comment]
`/api/v2/jobs/?order_by=-finished`

**Comment by wenottingham** [comment]
Clicking the `?` next to 'Jobs List` in the API browser will give info on all the fields and sorting comparators.
