### ISSUE TITLE
How would one add privileges to awx Pod ?

### ISSUE THREAD

**Issue by mhobotpplnet** [ansible/awx#2049]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

Am trying to run awx in Kubernetes and instead of creating say ec2 instance etc, I would like to run few things right on the awx pod to get info like for example kubectl. However the privileges on pod are disabled so I can not install it, 'root' is not even present. 

I tried sudoing with the awx user thats there by default , that did not work either. 
Let me know what my options are. 

##### STEPS TO REPRODUCE

bash into container 

```
bash-4.2$ sudo mv kubectl /usr/local/bin/
sudo: unknown user: root
sudo: unable to initialize policy plugin
```

**Comment by wenottingham** [comment]
Hi - this appears to be a user issue, not a bug report. You will find more success using the mailing list or the IRC channel, see here: https://github.com/ansible/awx/#get-involved
