### ISSUE TITLE
Where to place j2 templates?

### ISSUE THREAD

**Issue by reecewebb** [ansible/awx#2050]
##### ISSUE TYPE
 - Bug Report
 - Documentation

##### COMPONENT NAME
 - UI

##### SUMMARY
I'm using SCM to import project playbooks. My test playbook copies a jinja2 template to a host using the template module. The playbook runs, I see facts are gathered successfully, but I'm getting an error about "source not found".

I have the *.j2 file in the same top-level directory as the *.yml. I can't find info on how to layout directories when using SCM, and my "template" searches are only bringing up AWX Templates info.

Am I just doing something wrong, or is this a bug?

Thanks!
Reece

##### ENVIRONMENT
* AWX version: 1.0.6.23
* AWX install method: docker on linux
* Ansible version:  2.5.5
* Operating System: macOS
* Web Browser: Chrome/Firefox

##### STEPS TO REPRODUCE
Run job using template.

##### EXPECTED RESULTS

Job runs successfully, /etc/acct/holidays is updated.

##### ACTUAL RESULTS

Identity added: /tmp/awx_26_umrodj/credential_2 (/tmp/awx_26_umrodj/credential_2) |  
-- | --
  | 2 |   |  
  | 3 | PLAY [all] ********************************************************************* | 10:42:58
  | 4 |   |  
  | 5 | TASK [Gathering Facts] ********************************************************* | 10:42:58
  | 6 | ok: [parn-tsm2] |  
  | 7 |   |  
  | 8 | TASK [Update /etc/acct/holidays] *********************************************** | 10:43:01
  | 9 | fatal: [parn-tsm2]: FAILED! => {"changed": false, "checksum": "d7db4d7e7e59777c7ef2434593c996714b2edbe7", "msg": "Source /root/.ansible/tmp/ansible-tmp-1530898981.41-227928534999664/source not found"} |  
  | 10 | ...ignoring |  
  | 11 |   |  
  | 12 | PLAY RECAP ********************************************************************* | 10:43:03
  | 13 | parn-tsm2                  : ok=2    changed=0    unreachable=0    failed=0

**Comment by wenottingham** [comment]
Hi - this appears to be a user issue, not a bug report. You will find more success using the mailing list or the IRC channel, see here: https://github.com/ansible/awx/#get-involved

**Comment by reecewebb** [comment]
If you're confident it's not a bug I'm assuming you know the answer. Would have been nice to share that instead of punting.
