### ISSUE TITLE
Feature Request for awx survey - popup child variables depended on previous variables to improve UX

### ISSUE THREAD

**Issue by rajmechi** [ansible/awx#2053]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY
 Toggle feature for awx survey  ( or new Toggle option ). for Example my playbook call an api for doing several operations so my top level variables decide the rest of variables . top level variable might be a role tag. This feature will reduce multiple jobs and also improve UX  

##### EXPECTED RESULTS
If i choose variable TEST ( first variable in the form ) then  form needs to ask TEST1 TEST2 TEST3 variables and if i choose variable XXX then form needs to ask XXX1 TEST2 (depends on how user design )

**Comment by rajmechi** [comment]
in my view most appropriate primary variable should be role rag.

**Comment by wenottingham** [comment]
This is #20 - closing as a duplicate.
