### ISSUE TITLE
Introduce a restrictive Content Security Policy

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#2056]
Add a restrictive Content-Security-Policy (https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) to awx to drastically reduce the surface area for a wide variety of in-browser security issues.

This is **really easy** to do on the backend:

```python
response['Content-Security-Policy'] = "default-src 'self'; report-uri /csp-violation/"
```

It's _hard_ on the front-end, because we'd need to identify any place we (or third-party libraries) inject inline JS and CSS.

Current roadblocks **may** include:

* Our version of Angular _itself_ (need to read up on https://code.angularjs.org/1.6.10/docs/api/ng/directive/ngCsp) 
* https://github.com/josdejong/mathjs/issues/401 (used by the network UI - it sounds like we're only using one or two small functions from this dependency, so maybe we can just lose it entirely?)
* Anything related to the pendo service?

**Comment by benthomasson** [comment]
mathjs v4.0.0 removes eval: https://github.com/josdejong/mathjs/issues/682#issuecomment-367286156

**Comment by mabashian** [comment]
OK so I took a look at `ng-csp` and I think I understand what it does.  By adding that directive to the dom (body) it lets angular know that it should not make use of `eval()` or inline styles/resources _internally_.  The UI will need to import `angular-csp.css` to get things like ng-cloak/ng-show/ng-hide to work since they'll no longer be able to depend on inline styles.  

UI will need to make sure it uses directives like `ng-click` rather than `onclick` as these won't be allowed by the CSP.

[Here's a short presentation on csp + angular 1.x](https://www.youtube.com/watch?time_continue=703&v=FIt9CITQFtY)

**Comment by ryanpetrello** [comment]
If we addressed this (and I think we should), we're unlikely to do so in the "old" AWX UI, but instead would start enforcing it in the replacement UI (ui-next).

**Comment by kdelee** [comment]
@ryanpetrello @jakemcdermott  do you have any particular suggestions for testing this, either from an API or UI perspective? This has been in a while and has not caused any problems for our API regression testing, so I'm happy with the way it is.

**Comment by wenottingham** [comment]
I would think if both API regression testing and UI functional testing works... it works.

**Comment by ryanpetrello** [comment]
We could *try* to come up with some testing that did something you weren't allowed to do (like ran JavaScript on the fly).

**Comment by ryanpetrello** [comment]
But what @wenottingham said is mostly correct - we're looking for outliers where we (or some awx user) notices front-end failures that result in CSP warnings in the browser.  I don't think we've seen any of those since we released this change.

**Comment by unlikelyzero** [comment]
Note: we will need to worry about packaging and non-production builds outside the scope of this ticket

**Comment by kylerossd** [comment]
Is there a way to modify, add exceptions or disable CSP?  I am making a API POST to tower from ServiceNow and it is blocking.

2021-09-02 20:59:49,724 ERROR    awx {'csp-report': {'blocked-uri': 'https://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css', 'document-uri': 'https://tower.**********.io/api/o/authorize/?scope=write&response_type=code&state=-1094397606&redirect_uri=https://dev******.service-now.com/oauth_redirect.do&client_id=MUxioXptXj7f95gCTkjhT8myIrMk3hFpk5w8AH5X', 'original-policy': "default-src 'self'; connect-src 'self' https://*.pendo.io ws: wss:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://*.pendo.io; img-src 'self' https://*.pendo.io data:; report-uri https://tower.*******.io/csp-violation/", 'referrer': '', 'violated-directive': 'style-src'}}
