### ISSUE TITLE
RFE: Provide CSV Format for Job Output

### ISSUE THREAD

**Issue by LukeShortCloud** [ansible/awx#2057]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Job stdout at `api/v2/jobs/$JOB_ID/stdout/` can be exported to text, ansi, html, and json. Job events at `/api/v2/jobs/$JOB_ID/job_events/` are even more limited by only being able to report back as JSON. My client is looking to utilize Ansible Tower as a full replacement for HPSA and is seeking the ability to have CSV reports. This makes it easier for their team to open it up using Microsoft Office's Excel or LibreOffice Calc and have a quick overview. It is a middle-ground between having a programmer-oriented structure such as JSON and an unparsable structure of pure stdout text. On a somewhat related note, it would be ideal to also be able to download different formats (besides the default text format) directly from the Job page in the dashboard `/jobs/$JOB_ID`.

Due to the restriction of not being able to override the stdout_callback [1][2] in AWX/Tower, the ability to modify the stdout is limited from a Tower perspective.

##### ENVIRONMENT
* AWX version: 1.0.6.23
* Ansible version:  2.6.1

##### STEPS TO REPRODUCE
1. Launch a job.
2. When it is done running, the standard output can only be downloaded as a text file from the `/jobs/$JOB_ID` page you are on.
3. Through the API, it cannot be downloaded as an CSV. `/api/v2/jobs/$JOB_ID/stdout/`

##### EXPECTED RESULTS
`/api/v2/jobs/$JOB_ID/stdout/` should provide an option to `GET` CSV output.

##### ACTUAL RESULTS
`/api/v2/jobs/$JOB_ID/stdout/` only provides options to `GET` api, html, txt, ansi, json, txt_download,  and ansi_download.

##### ADDITIONAL INFORMATION
1. https://github.com/ansible/awx/issues/335#issuecomment-336662791
2. https://github.com/ansible/awx/blob/a4b1cb6e2066de7569f161c8d94b428d6dddba4d/awx/main/tasks.py

**Comment by wenottingham** [comment]
There is no 'CSV' format for the job output from Ansible, and we would not invent a specific one to use; we would not be doing this.

If they are only interested in certain subsets of job data, there are a variety of options;
- use the API for job events; filter only the information they need from that json (converting as necessary)
- use the log streaming for job events; filter only the information they need from that json
- write a custom callback plugin that sends only the information they need
- ensure `no_target_syslog` is False and use syslog from the managed machines
