### ISSUE TITLE
Connection to Windows host doesn't work via AWX

### ISSUE THREAD

**Issue by giordyb** [ansible/awx#206]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Connection to Windows server doesn't work using AWX but works fine with ansible from the same command host

##### ENVIRONMENT
* AWX version: 1.0.0.487
* Ansible version:  2.4.0.0
* Operating System: Centos 7.3
* Web Browser: Chrome

Centos 7 server command server joined to a domain
Windows 2016 Hyper-v host joined to the same domain

I can run the win_ping module manually from the command line of the command server, so I know that the server configuration and the windows host are configured correctly.
I am using a domain user that is a member of the administrators group on the windows server.

##### STEPS TO REPRODUCE

after creating the inventory and a set of credentials for the domain I added the windows host.
I also added the following variables to the inventory:

ansible_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore

##### EXPECTED RESULTS

win_ping and win_command should work on the windows host without issues

##### ACTUAL RESULTS

When I run a win_ping via the host's "run commands" I get a failure and the "stdout capture is missing" is displayed in the standard out window

when I run a template that calls a simple playbook with "win_ping" it seems to connect but fails right after kinit

##### ADDITIONAL INFORMATION

```
1
Using /etc/ansible/ansible.cfg as config file
2
SSH password: 
3
Loading callback plugin awx_display of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
4
5
PLAYBOOK: ping.yml *************************************************************
6
1 plays in ping.yml
7
8
PLAY [all] *********************************************************************11:51:47
9
10
TASK [Gathering Facts] *********************************************************11:51:47
11
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/setup.ps1
12
<myserver.domain.local> ESTABLISH WINRM CONNECTION FOR USER: user.admin@DOMAIN.LOCAL on PORT 5986 TO myserver.domain.local
13
creating Kerberos CC at /tmp/tmpKg4dzF
14
calling kinit for principal user.admin@DOMAIN.LOCAL

The full traceback is:
16
Traceback (most recent call last):
17
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 125, in run
18
    res = self._execute()
19
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 522, in _execute
20
    result = self._handler.run(task_vars=variables)
21
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 45, in run
22
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars, wrap_async=wrap_async))
23
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 738, in _execute_module
24
    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)
25
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 887, in _low_level_execute_command
26
    rc, stdout, stderr = self._connection.exec…
```
traceback

`{
    "msg": "Unexpected failure during module execution.",
    "failed": true,
    "exception": "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py\", line 125, in run\n    res = self._execute()\n  File \"/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py\", line 522, in _execute\n    result = self._handler.run(task_vars=variables)\n  File \"/usr/lib/python2.7/site-packages/ansible/plugins/action/normal.py\", line 45, in run\n    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars, wrap_async=wrap_async))\n  File \"/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py\", line 738, in _execute_module\n    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)\n  File \"/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py\", line 887, in _low_level_execute_command\n    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)\n  File \"/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py\", line 328, in exec_command\n    super(Connection, self).exec_command(cmd, in_data=in_data, sudoable=sudoable)\n  File \"/usr/lib/python2.7/site-packages/ansible/plugins/connection/__init__.py\", line 53, in wrapped\n    self._connect()\n  File \"/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py\", line 301, in _connect\n    self.protocol = self._winrm_connect()\n  File \"/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py\", line 207, in _winrm_connect\n    self._kerb_auth(self._winrm_user, self._winrm_pass)\n  File \"/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py\", line 182, in _kerb_auth\n    p = subprocess.Popen(kinit_cmdline, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=krbenv)\n  File \"/usr/lib64/python2.7/subprocess.py\", line 711, in __init__\n    errread, errwrite)\n  File \"/usr/lib64/python2.7/subprocess.py\", line 1327, in _execute_child\n    raise child_exception\nOSError: [Errno 2] No such file or directory\n",
    "stdout": ""
}`

**Comment by giordyb** [comment]
quick update, the same job running as local administrator of the windows server runs fine

**Comment by giordyb** [comment]
it looks like the awx_tasks docker image is missing the kerberos packages, thus it's failing when trying to do the kinit command.

I was able to get it to work by logging into the container and running "yum install krb5-workstation krb5-libs krb5-devel"

**Comment by matburt** [comment]
Is krb5-devel strictly necessary?

**Comment by giordyb** [comment]
Probably not, I just added the packages mentioned in the Ansible Tower docs (http://docs.ansible.com/ansible-tower/latest/html/administration/kerberos_auth.html)

**Comment by matburt** [comment]
So you also needed to `pip install kerberos` ?

**Comment by giordyb** [comment]
well, I did try to run `pip install kerberos` as per the docs but since the container image is missing some dependencies so it failed.  At that point I gave up and tried to run the win_ping anyways...lo and behold it started working!

**Comment by matburt** [comment]
I only ask because I think we already have that bit covered:

https://github.com/ansible/awx/blob/devel/requirements/requirements_ansible.in#L24

**Comment by matburt** [comment]
Done in #207
