### ISSUE TITLE
standard_init_linux.go:178: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by flynn1973** [ansible/awx#2063]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
after install the following comes up in the logs ->

root@lpgaixmgmtlx01:/root/awx>docker logs -f awx_task
standard_init_linux.go:178: exec user process caused "exec format error"
standard_init_linux.go:178: exec user process caused "exec format error"
standard_init_linux.go:178: exec user process caused "exec format error"
standard_init_linux.go:178: exec user process caused "exec format error"
standard_init_linux.go:178: exec user process caused "exec format error"
standard_init_linux.go:178: exec user process caused "exec format error"
standard_init_linux.go:178: exec user process caused "exec format error"
standard_init_linux.go:178: exec user process caused "exec format error"
standard_init_linux.go:178: exec user process caused "exec format error"
standard_init_linux.go:178: exec user process caused "exec format error"
standard_init_linux.go:178: exec user process caused "exec format error"
standard_init_linux.go:178: exec user process caused "exec format error"
standard_init_linux.go:178: exec user process caused "exec format error"

root@lpgaixmgmtlx01:/root/awx/installer>docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                          PORTS               NAMES
a0ea9fc5fa31        ansible/awx_task:latest      "/tini -- /bin/sh ..."   7 minutes ago       Restarting (1) 9 seconds ago                        awx_task
11ddabcd6bae        ansible/awx_web:latest       "/tini -- /bin/sh ..."   7 minutes ago       Restarting (1) 19 seconds ago                       awx_web
431172f30629        memcached:alpine             "docker-entrypoint..."   9 minutes ago       Up 9 minutes                    11211/tcp           memcached
925d7faf36f6        ansible/awx_rabbitmq:3.7.4   "docker-entrypoint..."   9 minutes ago       Restarting (1) 2 minutes ago                        rabbitmq
5ce474307c8d        postgres:9.6                 "docker-entrypoint..."   9 minutes ago       Up 9 minutes                    5432/tcp            postgres

since i use linux on power, could it be there is some "architecture dependent" part messing up?

##### ENVIRONMENT
* AWX version:  latest checkout from git, not sure where to look for version numbers.
* AWX install method:  docker on linux
* Ansible version:  2.6.1
* Operating System: RedHat 7.4 - ppc64le
* Web Browser: Firefox

##### STEPS TO REPRODUCE
i just used standard install procedure.

##### EXPECTED RESULTS
working installation

##### ACTUAL RESULTS
not working installation

##### ADDITIONAL INFORMATION

none

**Comment by flynn1973** [comment]
little update, dont know if this of some importance...

when i kill the rabbitmq container, the ports on the two awx container at least showing up.

```
root@lpgaixmgmtlx01:/root/awx/installer>docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                         PORTS                                                 NAMES
aa74c1ac2686        ansible/awx_task:latest      "/tini -- /bin/sh -c…"   11 minutes ago      Restarting (1) 5 minutes ago   8052/tcp                                              awx_task
31978b87a0fd        ansible/awx_web:latest       "/tini -- /bin/sh -c…"   11 minutes ago      Restarting (1) 5 minutes ago   0.0.0.0:8888->8052/tcp                                awx_web
26beb1e716bc        memcached:alpine             "docker-entrypoint.s…"   12 minutes ago      Up 12 minutes                  11211/tcp                                             memcached
18c90ee03b88        ansible/awx_rabbitmq:3.7.4   "docker-entrypoint.s…"   12 minutes ago      Up Less than a second          4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 25672/tcp   rabbitmq
6accd38a7d0e        postgres:9.6                 "docker-entrypoint.s…"   12 minutes ago      Up 12 minutes                  5432/tcp                                              postgres
root@lpgaixmgmtlx01:/root/awx/installer>docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                         PORTS                    NAMES
aa74c1ac2686        ansible/awx_task:latest      "/tini -- /bin/sh -c…"   11 minutes ago      Restarting (1) 5 minutes ago   8052/tcp                 awx_task
31978b87a0fd        ansible/awx_web:latest       "/tini -- /bin/sh -c…"   11 minutes ago      Restarting (1) 5 minutes ago   0.0.0.0:8888->8052/tcp   awx_web
26beb1e716bc        memcached:alpine             "docker-entrypoint.s…"   12 minutes ago      Up 12 minutes                  11211/tcp                memcached
18c90ee03b88        ansible/awx_rabbitmq:3.7.4   "docker-entrypoint.s…"   12 minutes ago      Restarting (1) 3 seconds ago                            rabbitmq
6accd38a7d0e        postgres:9.6                 "docker-entrypoint.s…"   12 minutes ago      Up 12 minutes                  5432/tcp                 postgres
```

the restart loops are still there anyway...

**Comment by wenottingham** [comment]
If you're using the prebuilt images on ppc64le... that's not going to work. (Are you sure you pulled the proper architecture images for the dependencies?). If you built the images yourself... something was broken in your build. 

In any case, this doesn't appear to be an AWX issue itself.

**Comment by flynn1973** [comment]
yes i've used the prebuild images, was not aware they are not portable.
