### ISSUE TITLE
local Docker issue in postgres (auth_user_username_key)

### ISSUE THREAD

**Issue by Unterstrichmoepunterstrich** [ansible/awx#2065]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
 - UI
 - Installer

##### ENVIRONMENT
* AWX version: last checkout few days ago: commit 07ddfe2c9c15fbec28ce40bb8c91051842a4a0f1 (HEAD -> devel, origin/devel, origin/HEAD) 
* AWX install method: docker on linux
* Ansible version:  2.5.1
* Operating System: Ubuntu 18.04
* Web Browser: Chromium

##### STEPS TO REPRODUCE

I installed few months ago AWX. Then my goal was to make an upgrade. So I made git pull and just my former inventory file with the settings.
In the new playbook I noticed, that awx_secret_key is now secret_key. I changed just the var name in my inventory.

##### EXPECTED RESULTS

I expected a migration which change the secret_key in the database.

##### ACTUAL RESULTS

all containers are running. When I want to visit the AWX site in my browser, then I see "Upgrade AWX" button and nothing happens.

docker-compose -f /opt/awx_latest/docker-compose.yml logs|grep ERROR

postgres_1   | ERROR:  duplicate key value violates unique constraint "auth_user_username_key"
web_1        | 2018-07-12 13:34:37,111 ERROR    Error trying to receive messages: [Errno 104] Connection reset by peer 

##### ADDITIONAL INFORMATION

docker-compose -f /opt/awx_latest/docker-compose.yml exec task /bin/bash

[root@awx awx]# awx-manage showmigrations
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
 [X] 0007_alter_validators_add_error_messages
 [X] 0008_alter_user_username_max_length
conf
 [X] 0001_initial
 [X] 0002_v310_copy_tower_settings
 [X] 0003_v310_JSONField_changes
 [X] 0004_v320_reencrypt
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
djcelery
 [X] 0001_initial
main
 [X] 0001_initial
 [X] 0002_squashed_v300_release (18 squashed migrations)
 [X] 0003_squashed_v300_v303_updates (9 squashed migrations)
 [X] 0004_squashed_v310_release (6 squashed migrations)
 [X] 0005_squashed_v310_v313_updates (3 squashed migrations)
 [X] 0006_v320_release
 [X] 0007_v320_data_migrations
 [X] 0008_v320_drop_v1_credential_fields
 [X] 0009_v322_add_setting_field_for_activity_stream
 [X] 0010_v322_add_ovirt4_tower_inventory
 [X] 0011_v322_encrypt_survey_passwords
 [X] 0012_v322_update_cred_types
 [X] 0013_v330_multi_credential
 [X] 0014_v330_saved_launchtime_configs
 [X] 0015_v330_blank_start_args
 [X] 0016_v330_non_blank_workflow
 [X] 0017_v330_move_deprecated_stdout
 [X] 0018_v330_add_additional_stdout_events
 [X] 0019_v330_custom_virtualenv
 [X] 0020_v330_instancegroup_policies
 [X] 0021_v330_declare_new_rbac_roles
 [X] 0022_v330_create_new_rbac_roles
 [X] 0023_v330_inventory_multicred
 [X] 0024_v330_create_user_session_membership
 [ ] 0025_v330_add_oauth_activity_stream_registrar
 [ ] 0026_v330_delete_authtoken
 [ ] 0027_v330_emitted_events
 [ ] 0028_v330_add_tower_verify
 [ ] 0030_v330_modify_application
 [ ] 0031_v330_encrypt_oauth2_secret
 [ ] 0032_v330_polymorphic_delete
 [ ] 0033_v330_oauth_help_text
 [ ] 0034_v330_delete_user_role
 [ ] 0035_v330_more_oauth2_help_text
 [ ] 0036_v330_credtype_remove_become_methods
 [ ] 0037_v330_remove_legacy_fact_cleanup
network_ui
 [X] 0001_initial
oauth2_provider
 [X] 0001_initial
 [X] 0002_08_updates
 [X] 0003_auto_20160316_1503
 [X] 0004_auto_20160525_1623
 [X] 0005_auto_20170514_1141
sessions
 [X] 0001_initial
sites
 [X] 0001_initial
 [X] 0002_alter_domain_unique
social_django
 [X] 0001_initial (2 squashed migrations)
 [X] 0002_add_related_name (2 squashed migrations)
 [X] 0003_alter_email_max_length (2 squashed migrations)
 [X] 0004_auto_20160423_0400 (2 squashed migrations)
 [X] 0005_auto_20160727_2333 (1 squashed migrations)
 [X] 0006_partial
 [X] 0007_code_timestamp
 [X] 0008_partial_timestamp
sso
 [X] 0001_initial
 [X] 0002_expand_provider_options
taggit
 [X] 0001_initial
 [X] 0002_auto_20150616_2121

**Comment by chrismeyersfsu** [comment]
@Unterstrichmoepunterstrich https://github.com/ansible/awx/blob/devel/DATA_MIGRATION.md Upgrading via Django migrations isn't expected to work. Especially when going to devel vs. a point release.
