### ISSUE TITLE
Prevent Tower from pulling from Galaxy

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#2073]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

We would like to prevent Tower from being able to dynamically pull roles from galaxy.ansible.com. Instead we are going to have an internal review process and hand pick versions of roles which we will allow within our enterprise. As such, we want to have a toggle switch in AWX which would prevent it from auto-polling a role.

##### ENVIRONMENT
* AWX version: 1.0.6
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.6.1
* Operating System: RHEL
* Web Browser: All

##### STEPS TO REPRODUCE

In settings => job there would be a new toggle switch for "Enable Galaxy". If "off" then when a JT kicks off a project update the logic in project_update.yml for pulling down new roles would be bypassed.

**Comment by wenottingham** [comment]
This can (functionally) be achieved by not storing roles in roles/.

If the concern is "an authorized SCM user could add a roles/requirements.yml" file, that seems an issue best solved by the use of pull requests, reviews, and protected branches for AWX to pull from.

**Comment by matburt** [comment]
Fixed in #2078
