### ISSUE TITLE
project_update.yml reports skipping even though it runs ansible-galaxy

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#2077]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY

When running a job template which launches a project update and the project update is pulling roles down from a requirements.yml file the output in the Tower job reports:
  | 49 | TASK [Write Repository Version] ************************************************ | 16:32:13
  | 50 | changed: [localhost] |  
  | 51 |   |  
  | 52 | PLAY [all] ********************************************************************* | 16:32:13
  | 53 |   |  
  | 54 | TASK [detect requirements.yml] ************************************************* | 16:32:13
  | 55 | skipping: [localhost] |  
  | 56 |   |  
  | 57 | TASK [fetch galaxy roles from requirements.yml] ******************************** | 16:32:13
  | 58 | skipping: [localhost] |  
  | 59 |   |  
  | 60 | TASK [fetch galaxy roles from requirements.yml (forced update)] **************** | 16:32:14
  | 61 | skipping: [localhost] |  
  | 62 |   |  
  | 63 | PLAY RECAP *********************************************************************

Note the skipping:[localhost].

However, if you check /var/lib/awx/project/_<id>__<project name>/roles/ the roles files will be there.

##### ENVIRONMENT
* AWX version: 1.0.6.3
* AWX install method: docker for mac
* Ansible version:  2.6.1
* Operating System: OS X
* Web Browser: Any

##### STEPS TO REPRODUCE

The JSON mentioned below will build a project called “GIT Project” and a job template called “GIT Test”. The project will be tied to Default organization tied back to a public GHE repo of mine. The JT will be tied to the GIT Project and Demo Inventory running a playbook called get_ip.yml which just spits out ansible_default_ipv4.address in a debug statement.

Here is the import command (just make sure you don’t already have a “GIT Project” or “GIT Test” JT):
tower-cli send —tower-host XXXX git_stuff.json 
If you run into any issues be sure you have a github version of tower-cli. 

Once its imported check out /var/lib/awx/projects/_<ID>__git_project/roles and note that thee is only a requirements.yml file. Now kick off the GIT Test job, this will kick off a full SCM update of GIT Project. It should then create /var/lib/awx/projects/_<ID>__git_projects/roles/yatesr.timezone
Now look at project update job in Tower, scroll down to the bottom. You should see the skipping label.

##### EXPECTED RESULTS

If the steps are truly skipping I would expect that the yatesr.timezone directory would not exist. However, I expect the labels to not say skipping, instead they should correctly report changed or OK.

##### ACTUAL RESULTS
The logs indicate that the role steps are skipping.

##### ADDITIONAL INFORMATION

Github location: https://github.com/john-westcott-iv/ansible-testing
JSON file https://github.com/john-westcott-iv/ansible-testing/blob/master/files/git_stuff.json

**Comment by rooftopcellist** [comment]
it turns out these tasks are "skipped" when the project_update is executed as a "Check" Job Type.  The roles are indeed pulled from SCM to the node executing the job directly before executing a JT in a separate "Run" project_update job.  

More information:

 > The “Check” project_update checks the git revision hash and updates the scm in the db if necessary (and doesn’t necessarily run before every JT run, whereas the “Run” project_update checks out the scm just before the job run and is necessary because of clustered tower (each tower node needs a copy of the scm locally to run the job)
