### ISSUE TITLE
More ssh keys needed for AWX session 

### ISSUE THREAD

**Issue by olokolo250** [ansible/awx#2079]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY

More ssh  keys available for the user (modification of machine credentials; new type or possibility to add more machine credentials to the job  template). 
Currently you can only add  one key for the particular user, would be really great if you could have more of them as in some environments you have more that one bastion host with different keys allowed.  
There should also be  a possibility to protect keys with the passphrase. 

##### ENVIRONMENT
* AWX version: X.Y.Z

##### EXPECTED RESULTS

ssh-agent running for the particular awx session having more than one key which will allow one user to be able  to ssh to different servers using different ssh keys.

**Comment by wenottingham** [comment]
this is https://github.com/ansible/awx/issues/286

**Comment by olokolo250** [comment]
Don't understand your reply wenottingham, those two links in #286 provide the basics about the AWX credentials, dont see any possibility to add more ssh keys for one user. If its possible the docs are just not explanatory enough.
