### ISSUE TITLE
Add timeout to email notification configuration

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#2080]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Django's base class seems to allow for a `timeout` parameter for the email notification class, but AWX doesn't allow making use of it

##### ENVIRONMENT
* AWX version: any
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Send a notification with incorrect configuration, see how long it takes to get a connection refused error

##### EXPECTED RESULTS

Some way to configure timeout

##### ACTUAL RESULTS

It could be system-dependent, but through experimentation I can see a difference between an attempt to send the email notification to when it errors of 12:34:37 to 12:38:21, or around 4 minutes total.

Hypothetically. being a rational actor, and not wanting to swamp my system in the case my flaky email server sometimes dies, I would like the timeout to be shorter.

##### ADDITIONAL INFORMATION

Our class:

https://github.com/ansible/awx/blob/devel/awx/main/notifications/email_backend.py

The base class of that:

https://github.com/django/django/blob/stable/1.11.x/django/core/mail/backends/smtp.py

This allows a `timeout` parameter that users can't make use of... yet.

**Comment by beeankha** [comment]
Timeout feature has been added to the email notification templates.  The default is 30 seconds, range is from 1 to 120 seconds.  

![EmailNotificationForm](https://user-images.githubusercontent.com/28930622/54289265-38588800-457f-11e9-8984-e83e57aa0967.png)

![ToolTip](https://user-images.githubusercontent.com/28930622/54289269-3abae200-457f-11e9-8d75-a4b7009ece59.png)
