### ISSUE TITLE
[kubernetes] split containers in single pods

### ISSUE THREAD

**Issue by TheKangaroo** [ansible/awx#2081]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - Installer

##### SUMMARY
Split awx container into separate pods on kubernetes deployment.

##### ENVIRONMENT
* AWX install method: kubernetes

##### STEPS TO REPRODUCE

We deploy AWX on our in-house kubernetes cluster which we share with other teams separated by namespaces.
Since AWX is one of the biggest apps (6cpu/8GB ram requested) we easily repress other pods on that node when we start AWX deployments.
This could have less effect if we would split the container in separate pods. Besides is this AFAIK the preferred way to deploy applications to kubernetes.
Another benefit of splitting containers into single pods is the ability to scale them independently. 
Are there any reasons why we deploy all containers into one single pod?

Any ideas on this?

**Comment by matburt** [comment]
This architecture matches the standalone *Tower* deployment architecture where some services are local to the node. This helps simplify deployments overall and makes sure each Tower web/worker has the capability to execute jobs if they are online.

It's possible will adjust this architecture later, but it's not something we're looking at right now.
