### ISSUE TITLE
Add checkboxes for bulk actions

### ISSUE THREAD

**Issue by RoUS** [ansible/awx#2084]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
1. In the UI, having to individually cancel and then delete multiple [pending] jobs from a runaway/misconfigured template/playbook is a major pain.  Hence, RFE: A checkbox beside each job, and an action pulldown including 'cancel selected items' and 'delete selected items.'

2. In the tower-cli tool, again, it appears that jobs must be individually canceled, and then deleted.  A way to specify multiple job IDs on the command line would be very welcome.

##### ENVIRONMENT
* AWX version: 2.4.1.0
* AWX install method: unknown
* Ansible version:  
* Operating System: RHEL
* Web Browser: Firefox 61.0.1

**Comment by wenottingham** [comment]
-> #19
