### ISSUE TITLE
Allow RabbitMQ TLS Authentication instead of cleartext

### ISSUE THREAD

**Issue by chrisandersonbtg** [ansible/awx#2086]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - Installer

##### SUMMARY
Is it possible to change the RabbitMQ configuration to support TLS and not send connection information via clear text?

##### ENVIRONMENT
* AWX version: All
* AWX install method: N/A
* Ansible version:  2.4.2
* Operating System: RedHat 7.4
* Web Browser:  Chrome

##### STEPS TO REPRODUCE

AWX uses plain text connection string to connect to RabbitMQ

##### EXPECTED RESULTS

AWX would have the ability to use TLS and a user provided certificate to encrypt traffic to RabbitMQ.
See link for details:  https://www.rabbitmq.com/ssl.html

##### ACTUAL RESULTS

AWX uses plain text connection string to connect to RabbitMQ

##### ADDITIONAL INFORMATION

I opened a similar ticket with RedHat and they recommended opening a ticket in AWX.  See below:

Thanks for the follow-up, Chris.  I appreciate the question.

The original issue was created in a private internal GitHub repo used by the Tower development team, and it remains active there.  As such, it is not currently visible externally.

We have a couple of options from here:  We can leave this case open, and I will keep you informed as the situation develops, or you can create and interact directly with an appropriate issue in the open Tower-upstream AWX repo here:

https://github.com/ansible/awx/issues

**Comment by kladiv** [comment]
+1

**Comment by stoleas** [comment]
@bradynathan

**Comment by SLusenti** [comment]
+1

**Comment by kfattig** [comment]
This configuration results in a medium severity from Nessus:

[87733 AMQP Cleartext Authentication](https://www.tenable.com/plugins/nessus/87733)

**Comment by ryanpetrello** [comment]
Closing this issue, as we're removing AWX's usage of RabbitMQ entirely (see: https://github.com/ansible/awx/issues/5443)
