### ISSUE TITLE
RFE: Support FQDN in addition to URL for RHV credentials

### ISSUE THREAD

**Issue by machacekondra** [ansible/awx#2089]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

For RHV credentials it would be nice to either insert FQDN or URL of oVirt API.

##### STEPS TO REPRODUCE

Create RHV credentials, try to insert FQDN instead of URL of the API.

##### EXPECTED RESULTS

Possible.

##### ACTUAL RESULTS

Not possible.

##### ADDITIONAL INFORMATION

It would be nice to check if user has passed URL, just by searching for '/' in input string, if it contains '/' then pass it else append to it `https://{{host}}/ovirt-engine/api`

**Comment by gamuniz** [comment]
In the current AWX version I can put anything I want into the host field. Closing as already implemented.
