### ISSUE TITLE
ECONNRESET on Chromedriver Installation RHEL 7.3

### ISSUE THREAD

**Issue by welsh** [ansible/awx#209]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI
 - Installer

##### SUMMARY
When performing the installation it fails on `image_build : Build AWX distribution using container` specifically the `npm --unsafe-perm --prefix awx/ui install awx/ui` task while installing `chromedriver@2.32.3`.

##### ENVIRONMENT
* AWX version: devel (710aaaa2c84ce20da5b1e906024c80ab1c8c040d)
* Ansible version:  2.3.0.0
* Operating System: Red Hat Enterprise Linux Server release 7.3 (Maipo)

##### STEPS TO REPRODUCE
Attempting to perform a clean installation using the `geerlingguy.awx` galaxy role to RHEL 7.3.

##### EXPECTED RESULTS
UI to install properly

##### ACTUAL RESULTS
Fails with error:

```
> chromedriver@2.32.3 install /awx/awx/ui/node_modules/chromedriver
> node install.js

Downloading https://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip
Saving to /tmp/chromedriver/chromedriver_linux64.zip
ChromeDriver installation failed Error with http(s) request: Error: read ECONNRESET
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {\\\"os\\\":\\\"darwin\\\",\\\"arch\\\":\\\"any\\\"} (current: {\\\"os\\\":\\\"linux\\\",\\\"arch\\\":\\\"x64\\\"})
npm WARN karma-webpack@1.8.1 requires a peer of webpack@^1.1.0 || ^2 || ^2.1.0-beta || ^2.2.0-rc but none was installed.
npm WARN awx@1.0.0 No license field.
npm ERR! Linux 3.10.0-514.16.1.el7.x86_64
npm ERR! argv \\\"/usr/bin/node\\\" \\\"/usr/bin/npm\\\" \\\"--unsafe-perm\\\" \\\"--prefix\\\" \\\"awx/ui\\\" \\\"install\\\" \\\"awx/ui\\\"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.32.3 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chromedriver@2.32.3 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.
```

##### ADDITIONAL INFORMATION

Attempted to perform a wget of the zip and received the following:
```
$ wget "https://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip" -d
DEBUG output created by Wget 1.14 on linux-gnu.

URI encoding = ‘UTF-8’
Converted file name 'chromedriver_linux64.zip' (UTF-8) -> 'chromedriver_linux64.zip' (UTF-8)
Converted file name 'chromedriver_linux64.zip' (UTF-8) -> 'chromedriver_linux64.zip' (UTF-8)
--2017-09-19 00:26:01--  https://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip
Resolving chromedriver.storage.googleapis.com (chromedriver.storage.googleapis.com)... 216.58.193.80, 2607:f8b0:4006:80f::2010
Caching chromedriver.storage.googleapis.com => 216.58.193.80 2607:f8b0:4006:80f::2010
Connecting to chromedriver.storage.googleapis.com (chromedriver.storage.googleapis.com)|216.58.193.80|:443... connected.
Created socket 3.
Releasing 0x0000000001483f60 (new refcount 1).
Initiating SSL handshake.
SSL handshake failed.
Closed fd 3
Unable to establish SSL connection.
```

This is the current SSL version:
```
$ yum info openssl
Loaded plugins: package_upload, product-id, search-disabled-repos, subscription-manager
Installed Packages
Name        : openssl
Arch        : x86_64
Epoch       : 1
Version     : 1.0.2k
Release     : 8.el7
Size        : 814 k
Repo        : installed
From repo   : rhel-7-server-rpms
Summary     : Utilities from the general purpose cryptography library with TLS implementation
URL         : http://www.openssl.org/
License     : OpenSSL
Description : The OpenSSL toolkit provides support for secure communications between
            : machines. OpenSSL includes a certificate management tool and shared
            : libraries which provide various cryptographic algorithms and
            : protocols.
```

If I download locally the `chromedriver_linux64.zip` and then set `export CHROMEDRIVER_FILEPATH=/tmp/chromedriver_linux64.zip` I can complete the `npm --unsafe-perm --prefix awx/ui install awx/ui` task however this doesn't resolve the issue as its building the UI in the container.

Where can I specify to the container an alternative download URL for the Chrome Driver?

**Comment by matburt** [comment]
That galaxy role is unsupported by this team, our docker packaging uses a build container to handle this. can you try going that route first? Not sure why your system would have an issue with the googleapis.com ssl handshake.

**Comment by welsh** [comment]
@matburt understood that the galaxy role isn't supported by this team but it does call the `awx/installer/install.yml` playbook which is the piece that is failing. Is that the docker packaging you are referring to?

I too am not sure why its not working to connect to the googleapis.com, as I can make a successful telnet connection but when attempting to grab the file I'm always met with the same Connection Reset Error. (Trying with curl or wget result in same error)

Is there a way for me to Shim into your docker packaging to download the chromedriver from an alternative URL? As it appears my server can successfully access `https://npm.taobao.org/mirrors/chromedriver`  so being able to have it set this environment variable:

```
CHROMEDRIVER_CDNURL=https://npm.taobao.org/mirrors/chromedriver 
```

Before the `npm --unsafe-perm --prefix awx/ui install awx/ui` task would get me further ahead.

**Comment by matburt** [comment]
you could certainly add that on to your local image build. I'm just not sure it's needed for a wider audience

**Comment by welsh** [comment]
Agree'd that its probably not required for a wider audience.

What worked for me was adjusting the `env` option for the `Build AWX distribution using container` task in [`installer/image_build/tasks/main.yml`](https://github.com/ansible/awx/blob/6b7126ab6b423c63aed1bb20fb762d5dd7f856ff/installer/image_build/tasks/main.yml#L66) to be:
```
- name: Build AWX distribution using container
  docker_container:
    env:
      http_proxy: "{{ http_proxy | default('') }}"
      https_proxy: "{{ https_proxy | default('') }}"
      no_proxy: "{{ no_proxy | default('') }}"
      CHROMEDRIVER_CDNURL: "https://npm.taobao.org/mirrors/chromedriver"
    image: "awx_sdist_builder:{{ awx_version }}"
    name: awx_sdist_builder
    state: started
    detach: false
    volumes:
      - ../:/awx:Z
  delegate_to: localhost
  when: use_container_for_build|bool
```
I'll close this issue and hopefully if anyone else runs into this, it will help them resolve it.
