### ISSUE TITLE
Issues with Project SCM_Update on Multiple Instances

### ISSUE THREAD

**Issue by mneumarkidg** [ansible/awx#2093]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
When running an update (scm_update from GIT Repo) on a project. Only the POD/Instance that picks up the job is able to process the request and the remaining PODS/instance wont update, unless i disable all other instances and rerun the job. This is the only way I can get all my PODS/instances to update from scm_update.

##### ENVIRONMENT
* AWX version: 1.0.6.5
* AWX install method: Kubernetes
* Ansible version:  2.5.2
* Operating System: Kubernetes Cluster running CentOS 7
* Web Browser: Chrome and Firefox produce same issue

##### STEPS TO REPRODUCE

1. Upload new file into git repo.
2. Login to AWX on Kubernetes
3. Click Sync button next to project
4. Check each POD/Instance for updated file(s)

##### EXPECTED RESULTS

All instances should update local directories or atleast have the capability to specify all/or one.

##### ACTUAL RESULTS

When running an scm_update. Only the instance that picks up the job will update the local repo. Which isn't always the same instance that did the scm_update. Which means the files are not there or updated correctly.

##### ADDITIONAL INFORMATION

![screen shot 2018-07-25 at 12 26 30 pm](https://user-images.githubusercontent.com/25063770/43227362-656e6a84-9013-11e8-9b70-8cc31774323c.png)

Running Job's load balance as expected. However, logically all pods/instances should update on scm_update.

**Comment by mneumarkidg** [comment]
NOTE: Also, it noticed a small bug on the slider on the instances screen. If you notice the first two instances show CPU/RAM on the slider. The third does not!

**Comment by wenottingham** [comment]
This is intentional. See discussion in #289.

**Comment by mneumarkidg** [comment]
@wenottingham  This doesn't work. As the SCM_Update is picked up on a different pod or instance than the job itself. There is no way to guarantee that the scm_update happens on the same instance or pod.

**Comment by wenottingham** [comment]
A checkout is run before job runs regardless. Again, see the discussion in the linked issue.

**Comment by mneumarkidg** [comment]
@wenottingham We have over 100+ templates. This really isn't an answer other than a workaround. I would have to add requirements.txt to over 100+ templates and go through QA with each and every one. I do not see how this answer is a solution by modifying all existing code. Just to try and force a server to run on the same pod/instance. This should be on the server side. Not the code! How else am i going to ensure that every pod/instance is always the exact same?

**Comment by wenottingham** [comment]
The code already ensures that the revision desired will be there before any job runs, so I'm really not sure what you're getting at here.

**Comment by wenottingham** [comment]
In more detail - there are two types of project updates.

A 'check' job is run when the sync icon is clicked, or as part of 'update on launch' in a job setting. It runs on any node, and updates the AWX database with the revision of source control to use.

Then there is the 'run' type of project update. This happens directly before any job is run, on the same node where the job is run. This ensures the proper revision is present for the playbook to run regardless of the state of the node beforehand. (If it's the same node where the 'check' job ran, it will not do much.)
