### ISSUE TITLE
Foreman Ini file not being read

### ISSUE THREAD

**Issue by brad-soileau** [ansible/awx#2094]
##### ISSUE TYPE

 - Bug Report
##### COMPONENT NAME

 Module/plugin 

##### SUMMARY

When trying to use /etc/ansible/foreman.ini as documented, it doesn't seem to be read.  Adding a couple simple statements in the INI file as documented do not work.
##### ENVIRONMENT
* AWX version: 1.0.6.5
* AWX install method: docker on linux
* Ansible version:  2.5.2
* Operating System: CentOS 7.5/Docker
* Web Browser: Any

##### STEPS TO REPRODUCE

Create /etc/ansible/foreman.ini.

Add some simple options. Here is an example of the foreman.ini I'm using:
[foreman]
want_hostcollection = True
group_prefix = "newprefix"

Then import the inventory from Foreman, (I'm using Satallite6 but should work the same) using typical sync.

##### EXPECTED RESULTS

I expect Host Collections to show up in the inventory.  I also expect the imported groups to be named "newprefix_groupname" instead of "foreman_groupname".

##### ACTUAL RESULTS

Host Collections are not showing up in AWX at all.  Any Host Group I get from Foreman and named "foreman_groupname"

**Comment by jakemcdermott** [comment]
Hello, @bsoiled1

Thanks for creating this issue. Make sure `foreman.ini` is mounted as a volume so that it is reachable from within the container. Please re-open if you continue to see this issue after doing so. Thanks!
