### ISSUE TITLE
AWX UI changes not saving

### ISSUE THREAD

**Issue by sidhurana** [ansible/awx#2097]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### ENVIRONMENT
* AWX version:1.0.6.35
* AWX install method: docker
* Ansible version: ansible 2.4.2.0
* Operating System: Centos 7.5
* Web Browser: Chrome/Mozilla

##### SUMMARY
Followed : https://github.com/ansible/awx/blob/devel/INSTALL.md 

So, pulled all latest docker images/ ran it. Save and commit it to local nexus repository.

On another Server:
I pulled those images and start docker containers.
Startup went fine.
awx UI was up and running but all saved changes at UI level were missing. Like templates, Org creation etc. 

Postgres: I am using another mount point (instead of default /tmp) and copied that as well. But result still same. 

I can see my playbook is present and other files but somehow all AWX UI data is missing. 

##### STEPS TO REPRODUCE
Pull docker images -> commit -> save it to dockerhub or nexus -> Pull images and run to check if UI persist or not.

**Comment by sidhurana** [comment]
Any update or suggestions ?

**Comment by matburt** [comment]
Try the latest version of AWX and let us know, a lot of work has happened over the last few months.
