### ISSUE TITLE
Slack notification ignores name and icon of bot

### ISSUE THREAD

**Issue by onitake** [ansible/awx#2098]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

Currently, the Slack integration will send notifications to Slack as the user "bot" with a generic avatar icon.
Slack allows configuring the appearance of bot users and it would be very nice if AWX took advantage of this.

##### ENVIRONMENT
* AWX version: 1.0 (also with 1.0.6)
* AWX install method: custom playbook based on official docker containers
* Ansible version:  2.6.1
* Operating System: CentOS Linux 7
* Web Browser: Firefox / Chrome

##### STEPS TO REPRODUCE

This would work exactly as the Slack integration does right now.

##### EXPECTED RESULTS

This is what the notification should look like, with a custom icon and bot name configured in Slack:
![awx-bot-expected](https://user-images.githubusercontent.com/371687/43268093-03e6e4de-90f0-11e8-9ae7-7b0fd38c6752.png)

##### ACTUAL RESULTS

This is what AWX posts:
![awx-bot-actual](https://user-images.githubusercontent.com/371687/43268138-1f4acc9a-90f0-11e8-91a7-a7b243ed08a4.png)

##### ADDITIONAL INFORMATION

None.

**Comment by walkafwalka** [comment]
AWX does not have control over the custom icon for the bot user. It is likely you have the Slack bot user misconfigured which is a very easy thing to do considering the documentation on Slack and Tower are very confusing about this.

Slack has made some changes with how they handle bot users. In the past, a workspace could have a bot user created similarly to custom integrations. However, this has been deprecated and removed whereas custom integrations have been deprecated, but not yet removed.

In its place, Slack highly recommended using Slack Apps for any external integrations with Slack including incoming webhooks and bot users.

The Slack backend for AWX is built to be compatible with Slack Apps, but it is technically partially compatible with the old method. The documentation found at [notifications.html#slack](https://docs.ansible.com/ansible-tower/latest/html/userguide/notifications.html#slack) arguably could be better, but essentially the steps to integrate AWX with Slack are the following:

1. Create a workspace app
2. Create a bot user on the workspace app
3. Install the workspace app to your workspace
4. Invite the bot user to the channels you want to notify
5. Copy the _Bot User OAuth Access Token_ to the _Token_ field in AWX

The custom icon for the bot user is actually the same image as the custom image for the custom app. When you update the custom app's icon, it is updated in previous posts too.

**Comment by onitake** [comment]
So, you're saying I should write a custom Slack app and install it into our workspace?
That sounds a bit like overkill to me... Wouldn't it make a lot more sense if there was an official (or semi-official) Tower app?

**Comment by ryanpetrello** [comment]
@onitake you might actually be encountering this bug: https://github.com/ansible/awx/issues/2187

**Comment by onitake** [comment]
Looks like the other bug is a duplicate of this one.

Anyway, I followed @walkafwalka 's advice and created a workspace app. This works, but seems like overkill for a few simple notifications....

**Comment by ryanpetrello** [comment]
@onitake I'm currently reading Slack docs and debugging this issue, and I think I've got something that _should_ fix this for folks.  If you're feeling adventurous and want to help me test, you could give this small diff a whirl:

```diff
diff --git a/awx/main/notifications/slack_backend.py b/awx/main/notifications/slack_backend.py
index b68f91ef7c..603fe2f1c4 100644
--- a/awx/main/notifications/slack_backend.py
+++ b/awx/main/notifications/slack_backend.py
@@ -69,6 +69,7 @@ class SlackBackend(AWXBaseEmailBackend):
                         r = r[1:]
                     ret = connection.api_call("chat.postMessage",
                                               channel=r,
+                                              as_user=True,
                                               attachments=[{
                                                   "color": self.color,
                                                   "text": m.subject
```

**Comment by ryanpetrello** [comment]
Duplicate of https://github.com/ansible/awx/issues/2187

**Comment by ryanpetrello** [comment]
It's also worth saying that given the changes to Slack that @walkafwalka described above, and Slack's plans to deprecate some of this, this _may not_ work for much longer without actually making a workspace app :/

**Comment by runtman** [comment]
> @onitake I'm currently reading Slack docs and debugging this issue, and I think I've got something that _should_ fix this for folks. If you're feeling adventurous and want to help me test, you could give this small diff a whirl:
> 
> ```diff
> diff --git a/awx/main/notifications/slack_backend.py b/awx/main/notifications/slack_backend.py
> index b68f91ef7c..603fe2f1c4 100644
> --- a/awx/main/notifications/slack_backend.py
> +++ b/awx/main/notifications/slack_backend.py
> @@ -69,6 +69,7 @@ class SlackBackend(AWXBaseEmailBackend):
>                          r = r[1:]
>                      ret = connection.api_call("chat.postMessage",
>                                                channel=r,
> +                                              as_user=True,
>                                                attachments=[{
>                                                    "color": self.color,
>                                                    "text": m.subject
> ```

This doesn't appear to have made a difference with my notifier.

**Comment by runtman** [comment]
Correction I edited the code on the incorrect worker, this is the fix.
