### ISSUE TITLE
Cannot create a new project 

### ISSUE THREAD

**Issue by Buddwa** [ansible/awx#2099]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

There is only project base path and I cannot clicked the save button when I create a project on the web. I have disabled SELinux and the directory /var/lib/awx/projects have directories and files which can be accessed by any Linux users. You can refer to my snapshots below.

##### ENVIRONMENT
* AWX version: 1.0.6.16
* AWX install method: docker on linux
* Ansible version:   2.5.3
* Operating System: CentOS 7.5
* Web Browser: Firefox

##### EXPECTED RESULTS

I can click the save button and then create a new project.
##### ACTUAL RESULTS

The save button is gray， so the project cannot be created normally.
##### ADDITIONAL INFORMATION

![selection_004](https://user-images.githubusercontent.com/14852447/43300009-768c06c8-918f-11e8-9142-6c2bd81fb414.png)
![selection_005](https://user-images.githubusercontent.com/14852447/43300017-7f67036a-918f-11e8-95f4-239a35d4139f.png)

**Comment by jakemcdermott** [comment]
Hello @Buddwa 

You'll need to make sure the project directory is mounted to the container as a volume for it to be accessible. Please reach out to our mailing list or drop by our irc channel (`#ansible-awx` on freenode) if you're still having trouble.
