### ISSUE TITLE
Support RHEL base image

### ISSUE THREAD

**Issue by dnguyen9** [ansible/awx#2104]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - Installer

##### SUMMARY
I would like to build AWX and run them using the RHEL7 base image instead of Centos. A lot of the standard redhat product allows selection of base images during the buildout of the docker images such as https://github.com/openshift/jenkins.

##### ENVIRONMENT
* AWX version: latest
* AWX install method: openshift

**Comment by aoyawale** [comment]
you can probably do something similar at the moment https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/getting_started_with_containers/using_red_hat_base_container_images_standard_and_minimal and look at the dockerfile at https://github.com/ansible/awx/tree/devel/tools/docker-compose and docker-isolated/

**Comment by matburt** [comment]
We have no plans to do this, you'll need to manage your own images if you want this.
