### ISSUE TITLE
Compile with 3.7 

### ISSUE THREAD

**Issue by h4ck3rm1k3** [ansible/awx#2118]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Compilation problems with python 3.7

##### ENVIRONMENT
* AWX version: devel
* AWX install method: unsupported
* Operating System: debian unstable

##### STEPS TO REPRODUCE

```python3.7
Python 3.7.0 (default, Jun 27 2018, 14:40:03)
[GCC 8.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> SENSITIVE_URI_PATTERN = re.compile(ur'(\w+:(\/?\/?)[^\s]+)', re.MULTILINE)  # NOQA
  File "<stdin>", line 1
    SENSITIVE_URI_PATTERN = re.compile(ur'(\w+:(\/?\/?)[^\s]+)', re.MULTILINE)  # NOQA
                                                              ^
SyntaxError: invalid syntax
```

##### EXPECTED RESULTS

No error

##### ACTUAL RESULTS

syntax error

##### ADDITIONAL INFORMATION

Python 3 does not support ur'regex' need to use the six lib for that to do u(r'regex') 
patch pending

**Comment by ryanpetrello** [comment]
@h4ck3rm1k3 awx currently doesn't support Python3, and there's a _lot_ of work to do before we get there.

**Comment by h4ck3rm1k3** [comment]
There is usage of six in the project so this just another brick in the wall.

**Comment by ryanpetrello** [comment]
FYI, we've just released a new version of awx (https://github.com/ansible/awx/releases/tag/3.0.0) which runs under python3.6.  This version of awx also supports python2 _and_ python3 virtualenvs when running Ansible playbooks.
