### ISSUE TITLE
Error: Invalid Tower authentication credentials (HTTP 401). 

### ISSUE THREAD

**Issue by stenyjames** [ansible/awx#2120]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer 

##### SUMMARY

Tower-CLI Intermittent connectivity issues with Tower-HA.

##### ENVIRONMENT
* Ansible version: 2.4.2
* Ansible Tower HA version: 3.2.4
* Operating System: RED HAT 7

##### STEPS TO REPRODUCE
Trying to trigger the Tower HA job templates resulting in intermittent connectivity issue
tower-cli organization list 

##### EXPECTED RESULTS
List of organizations available in tower

##### ACTUAL RESULTS
Error: Invalid Tower authentication credentials (HTTP 401).

**Comment by ryanpetrello** [comment]
@stenyjames,

This is an issue tracker for awx, the open source project which Tower is based on.  If you need assistance with Ansible Tower, please reach out to Red Hat.
