### ISSUE TITLE
Azure_rm_resource 

### ISSUE THREAD

**Issue by yayefa** [ansible/awx#2127]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### ENVIRONMENT
* AWX version: 3.2.3
* AWX install method: Linux
* Ansible version: 2.6.1
* Operating System: CentOS 7

##### STEPS TO REPRODUCE

```
---
- hosts: localhost
  vars: 
    resource_group: "rg"
    resourceName: "resourcename"
    location: "location"
    dns_prefix: "dns_prefix"
    number_of_agents: "number_of_agents"
    agent_group_name: "agent_group_name"
    vm_size: "vm_size"
    kubernetes_version: "kubernetes_version"
    admin_username: "admin_username"
    admin_ssh_public_keys: "ssh_key"
    tag: "tag"
  tasks:

    - name: Create AKS
      local_action:
        module: azure_rm_resource
        api_version: "2018-03-31"
        url: "https://management.azure.com/subscriptions/{{subscription_id}}\
              /resourceGroups/{{resource_group}}/providers/Microsoft.ContainerService\
              /managedClusters/{{resourceName}}?api-version=2018-03-31"
        body: 
          {
            "location": "{{ location }}",
            "properties":
            {
              "dnsPrefix": "{{ dns_prefix }}",
              "tags": "tags_aks : {{ tag }}",
              "type":"Microsoft.ContainerService/ManagedClusters",
              "agentPoolProfiles":[
                 {
                   "count": "{{ number_of_agents}}",
                   "name": "{{ agent_group_name }}",
                   "vmSize": "{{ vm_size }}"
                   }
                ],
                "kubernetesVersion": "{{ kubernetes_version }}",
                "servicePrincipalProfile": {
                  "clientId": "{{ client_id }}",
                  "keyVaultSecretRef":null,
                  "secret": "{{ client_secret }}"
                },
                "linuxProfile":{
                  "adminUsername": "{{ admin_username }}",
                  "ssh": {
                     "publicKeys": [
                       { 
                         "keyData": "{{ admin_ssh_public_keys }}"
                       }
                      ]
                   }

                 }
             } 
          }
      register: output
```
##### EXPECTED RESULTS
AKS service created

##### ACTUAL RESULTS

`
    "_ansible_parsed": false,
    "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_4PGyGf/ansible_module_azure_rm_resource.py\", line 288, in <module>\n    main()\n  File \"/tmp/ansible_4PGyGf/ansible_module_azure_rm_resource.py\", line 284, in main\n    AzureRMResource()\n  File \"/tmp/ansible_4PGyGf/ansible_module_azure_rm_resource.py\", line 200, in __init__\n    super(AzureRMResource, self).__init__(self.module_arg_spec, supports_tags=False)\n  File \"/tmp/ansible_4PGyGf/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 284, in __init__\n  File \"/tmp/ansible_4PGyGf/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 650, in _get_credentials\n  File \"/tmp/ansible_4PGyGf/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 563, in _get_azure_cli_credentials\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/azure/common/credentials.py\", line 45, in get_azure_cli_credentials\n    profile = get_cli_profile()\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/azure/common/credentials.py\", line 28, in get_cli_profile\n    ACCOUNT.load(os.path.join(azure_folder, 'azureProfile.json'))\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/azure/cli/core/_session.py\", line 42, in load\n    self.save()\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/azure/cli/core/_session.py\", line 46, in save\n    with codecs_open(self.filename, 'w', encoding=self._encoding) as f:\n  File \"/var/lib/awx/venv/ansible/lib64/python2.7/codecs.py\", line 881, in open\n    file = __builtin__.open(filename, mode, buffering)\nIOError: [Errno 2] No such file or directory: '/var/lib/awx/.azure/azureProfile.json'\n",
    "_ansible_no_log": false,
    "_ansible_delegated_vars": {
        "ansible_delegated_host": "localhost",
        "ansible_host": "localhost"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_4PGyGf/ansible_module_azure_rm_resource.py\", line 288, in <module>\n    main()\n  File \"/tmp/ansible_4PGyGf/ansible_module_azure_rm_resource.py\", line 284, in main\n    AzureRMResource()\n  File \"/tmp/ansible_4PGyGf/ansible_module_azure_rm_resource.py\", line 200, in __init__\n    super(AzureRMResource, self).__init__(self.module_arg_spec, supports_tags=False)\n  File \"/tmp/ansible_4PGyGf/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 284, in __init__\n  File \"/tmp/ansible_4PGyGf/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 650, in _get_credentials\n  File \"/tmp/ansible_4PGyGf/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 563, in _get_azure_cli_credentials\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/azure/common/credentials.py\", line 45, in get_azure_cli_credentials\n    profile = get_cli_profile()\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/azure/common/credentials.py\", line 28, in get_cli_profile\n    ACCOUNT.load(os.path.join(azure_folder, 'azureProfile.json'))\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/azure/cli/core/_session.py\", line 42, in load\n    self.save()\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/azure/cli/core/_session.py\", line 46, in save\n    with codecs_open(self.filename, 'w', encoding=self._encoding) as f:\n  File \"/var/lib/awx/venv/ansible/lib64/python2.7/codecs.py\", line 881, in open\n    file = __builtin__.open(filename, mode, buffering)\nIOError: [Errno 2] No such file or directory: '/var/lib/awx/.azure/azureProfile.json'\n",
    "changed": false,
    "module_stdout": "",
    "rc": 1,
    "msg": "MODULE FAILURE"
}`

**Comment by wenottingham** [comment]
This reads as if you did not properly attach a credential to the job.

**Comment by yayefa** [comment]
I use Survey for credentials

**Comment by wenottingham** [comment]
You can't pass a credential with a survey, and survey variables are passed as extra vars, *not* environment variables.

**Comment by yayefa** [comment]
Sorry I didn't get the point.
Which credentials must be attach to the job?

**Comment by wenottingham** [comment]
Azure credentials.

**Comment by yayefa** [comment]
OH sorry, see my mistakes, . I added the wrong crendentials type in my job configuration.
Thank you.
