### ISSUE TITLE
Multi-line verbose events

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#2129]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Ansible events can be multi-line, but any verbose events (which are not Ansible events) can be only 1 line each

It would be more performant to save multiple lines to a single event, when `write` is called to the standard out buffer in that way.

##### ENVIRONMENT
* AWX version: all
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Run an inventory update that fails

##### EXPECTED RESULTS

Single events that correspond to a write of the full traceback

##### ACTUAL RESULTS

Still things like blank line events

```json
        {
            "id": 81,
            "type": "inventory_update_event",
            "url": "",
            "related": {
                "inventory_update": "/api/v2/inventory_updates/21/"
            },
            "summary_fields": {},
            "created": "2018-07-09T19:14:39.013314Z",
            "modified": "2018-07-09T19:14:39.013331Z",
            "event": "verbose",
            "counter": 38,
            "event_display": "verbose",
            "event_data": {},
            "failed": false,
            "changed": false,
            "uuid": "",
            "stdout": "",
            "start_line": 37,
            "end_line": 38,
            "verbosity": 0,
            "inventory_update": 21
        },
```

Even lines that are clearly correlated, and written to the standard out buffer in that way, are broken up by lines.

##### ADDITIONAL INFORMATION

related to https://github.com/ansible/awx/issues/200

**Comment by AlanCoding** [comment]
Been testing this and it works fine so far:

https://github.com/ansible/awx/compare/devel...AlanCoding:multi_line_verbose?expand=1

**Comment by AlanCoding** [comment]
The new `__init__` kwarg will go in ansible-runner config, and AWX will slurp it from setting `EVENT_STDOUT_MAX_BYTES_DISPLAY`, to match with what we display.

https://github.com/ansible/ansible-runner/blob/ce3c90f97fc7c7e7bdc6a53494503b9a907875c0/ansible_runner/runner_config.py

Next time I look at this, I need to first see about porting those tests over to runner. The "merge" of this might just delay until runner is integrated in.

**Comment by ryanpetrello** [comment]
Given that this is a performance improvement/enhancement, I'd _prefer_ that we change this as an enhancement in runner only instead of putting the change into awx and then having to port it to runner as well.

**Comment by AlanCoding** [comment]
In the 3.5 switch, the vast majority of

https://github.com/ansible/awx/blob/devel/awx/main/tests/unit/utils/test_event_filter.py

will be removed. We will _probably_ continue to keep the `OutputVerboseFilter` class and tests for it, which become kind of like integration tests. In my diff above, I am trying to reduce the role of the class to strictly managing the remainder text instead of duplicating the task of splitting it on all line breaks.

tests will need to pack up and move to

https://github.com/ansible/ansible-runner/blob/master/test/unit/test_utils.py

I assume

**Comment by AlanCoding** [comment]
🚚 https://github.com/ansible/ansible-runner/issues/242
