### ISSUE TITLE
Inventory sync jobs happen in an odd order

### ISSUE THREAD

**Issue by willthames** [ansible/awx#2138]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
When a job is run through the API (and likely through the web interface too), it seems that the inventory sync happens first and then the SCM sync (or the two happen in parallel). That means that any inventory changes that happen as part of the SCM update don't get reflected in the job execution

##### ENVIRONMENT
* AWX version: 1.0.6.41
* AWX install method: kubernetes
* Ansible version:  2.6.0
* Operating System: Linux
* Web Browser:

##### STEPS TO REPRODUCE

Create a job with an inventory that has an SCM based inventory source. Run job. Update SCM to new value, re-run job

##### EXPECTED RESULTS

New value is reflected in job execution, because job execution triggers SCM sync first and then inventory sync

##### ACTUAL RESULTS

Old value is reflected in job execution

##### ADDITIONAL INFORMATION

It's difficult to see exact timings, but 

SCM sync job:  Started 8/6/2018 11:35:22 AM Finished 8/6/2018 11:35:33 AM
Inventory sync job: Started 8/6/2018 11:35:22 AM Finished 8/6/2018 11:35:31 AM

From the SCM sync job:

| 12 | TASK [update project using git] ************************************************ | 11:35:24
| 13 | changed: [localhost] |  
| 14 |   |  
| 15 | TASK [Set the git repository version] ****************************************** | 11:35:32
| 16 | ok: [localhost]

From the tail of the inventory sync job:

  | 439 | 2018-08-06 01:35:31,310 DEBUG    awx.main.models.inventory Going to update inventory computed fields |  
  | 440 | 2018-08-06 01:35:31,424 DEBUG    awx.main.models.inventory Finished updating inventory computed fields |  
  | 441 | 5.050 INFO     Inventory import completed for XYZ in 3.7s |

**Comment by willthames** [comment]
This might be expected behaviour. I had inventory source set to "Update on Launch" rather than "Update on Project Change".

**Comment by jakemcdermott** [comment]
Hello @willthames 

Thanks for creating this issue. This is indeed expected behavior, given the "Update.." settings you've described.

Also: If you need to guarantee that an inventory sync occurs prior to a job run, Another way to do this is to create a workflow with an inventory sync step preceding the job template you are using.
