### ISSUE TITLE
RFE: "TCP Keepalive" option on the Splunk external logging aggregator

### ISSUE THREAD

**Issue by hiyokotaisa** [ansible/awx#2139]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY

I would like to add TCP Keepalive message option on logging setting to avoid closing idle connection by firewall. If firewall terminate the connection between logging aggregator, These events will be dropped and not recorded on external logging.

**Comment by gamuniz** [comment]
no longer applicable since moving from python based logging to rsyslog.
