### ISSUE TITLE
A deleted user should still be displayed on the Job Details view for traceability/auditability

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2143]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
If a user runs a job, his/her username is attached to that jobrun. If that user is deleted, the username is no longer displayed with the job. This information may be important for traceability/auditability of job history.

##### ENVIRONMENT
* AWX version: any
* AWX install method: any
* Ansible version:  N/A
* Operating System: N/A
* Web Browser: N/A

##### STEPS TO REPRODUCE

1. Log in as 'deleteduser'
2. Run a job 'jobA'
3. View the Job detail for 'jobA'.
4. Log in as another user with Admin permission.
5. Delete the user which ran the job 'deleteduser'
6. Log in as another user
7. View the Job detail for 'jobA'.

##### EXPECTED RESULTS

I would expect to see the username of anyone who ran a job I had view permission for.

##### ACTUAL RESULTS

I saw everything but the username.

##### ADDITIONAL INFORMATION

Before User was deleted
<img width="776" alt="screen shot 2018-08-06 at 4 29 34 pm" src="https://user-images.githubusercontent.com/12446869/43739647-c7a29446-9996-11e8-8d78-98cc4c124fb7.png">
After User was deleted
<img width="776" alt="screen shot 2018-08-06 at 4 30 22 pm" src="https://user-images.githubusercontent.com/12446869/43739655-cdd7eae6-9996-11e8-89d8-e1763a98cf2d.png">

**Comment by ryanpetrello** [comment]
@unlikelyzero the activity stream _should_ display this information, and that's the place we generally send people for auditing purposes:
