### ISSUE TITLE
Increase size of 'limit' field in job template

### ISSUE THREAD

**Issue by ghost** [ansible/awx#2144]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Increase the maximum size of the 'limit' field in the job template from the current maximum of 1024 bytes to 2048 bytes.

##### ENVIRONMENT
* Tower 3.2.5

##### STEPS TO REPRODUCE

This change will allow more complex limit logic in job templates, especially with large inventories.

**Comment by krentiken** [comment]
+1

we have about 4,000 servers RHEL in our company and the limit of 1024 bytes is not enough

**Comment by wenottingham** [comment]
Fixed, see #3162
