### ISSUE TITLE
Getting an error Failed to import docker-py

### ISSUE THREAD

**Issue by arnabsen1234** [ansible/awx#2145]
TASK [local_docker : Activate postgres container] *******************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import docker-py - No module named requests.exceptions. Try `pip install docker-py`"}

**Comment by jakemcdermott** [comment]
hey arnabsen,

One typically sees this error when the `docker` or `docker-py` python dependency isn't installed to the environment running the installer.

If you haven't installed the required python docker dependencies mentioned in the [install docs](https://github.com/ansible/awx/blob/devel/INSTALL.md), please do that.

If you've installed the dependencies to a virtualenv and are still seeing this error, make sure you source the virtual env first (`. venv/bin/activate) before running the installer.
