### ISSUE TITLE
Workflow Job Template extra_data variables

### ISSUE THREAD

**Issue by sumkincpp** [ansible/awx#2147]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

Currently :
 -  `extra_vars` are allowed for Nodes within workflows(job_template). Only vars defined in survey can be used here in extra_vars.
 -  `extra_data` variables are allowed for whole job_template/workflow only.

This is a suggestion of adding a support for `extra_data` within workflow on per-workflow node(job_template) basis. This will allow more precise control of workflow job_templates.

**Comment by wenottingham** [comment]
This isn't correct; you can prompt for extra_vars when creating a workflow node.

**Comment by sumkincpp** [comment]
@wenottingham What isn't correct? Yes, you can prompt for extra_vars, but you can't use extra_data for template node within workflow. 

Won't it be useful to add extra_data for nodes in workflow?

**Comment by wenottingham** [comment]
extra_data is filled by the prompted extra_vars.
