### ISSUE TITLE
API bug: integer extra_vars are ignored

### ISSUE THREAD

**Issue by sumkincpp** [ansible/awx#2148]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Passing extra_vars with integer values(i.e. via tower-cli --version 3.3.0) results on value not being passed
```
tower-cli workflow_job launch -W "Test Workflow" -e count_input='10' --monitor -v
```

```
POST http://.../api/v2/workflow_job_templates/1807/launch/
Data: {'extra_vars': u'{"count_input": 10}'}
```
`count_input` becomes empty in workflow :

```
$ curl http://<>:80/api/v2/workflow_jobs/9706/  | jq
{
...
  "elapsed": 32.084,
  "job_args": "",
  "job_cwd": "",
  "job_env": {},
  "job_explanation": "",
  "result_traceback": "",
  "workflow_job_template": 1807,
  "extra_vars": "{\"count_input\": \"\"}",
 "allow_simultaneous": false
}
```

##### ENVIRONMENT
* AWX version: 1.0.6.39

**Comment by sumkincpp** [comment]
Seems to be related to tower-cli, since the type of field is `text`. 
This issue is relevant  to [ansible/tower-cli/issues/254](https://github.com/ansible/tower-cli/issues/254)

Value passed in CLI passed as int and not as text from tower-cli.

**Comment by sumkincpp** [comment]
Is it fine that AWX ignores var that expected to be text, but passed as integer?
So, if count_input is expected to be text, the value is ignored in this query :
```
{'extra_vars': u'{"count_input": 10}'}
```
But treated fine in this query :
```
{'extra_vars': u'{"count_input": "10"}'}
```

**Comment by AlanCoding** [comment]
I filed an issue for this in the tower-cli issue queue. At least I'm fairly certain this isn't a server bug, yes, it will sometimes use the string type for extra_vars, which is dumped JSON and kind of confusing, but the conversion of the count_input to empty string must be CLI related.
