### ISSUE TITLE
Batch inventory sync broken in 1.0.6.*

### ISSUE THREAD

**Issue by sumkincpp** [ansible/awx#2149]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
In `inventory variables` of `Inventory` only data from one source is present after batch inventory sync.

##### ENVIRONMENT
* AWX version: 1.0.6.17, 1.0.6.39, 1.0.6.41
* working AWX version: ??

Inventory Sources configured with following options:
  [x] Overwrite 
  [ ] Overwrite Variables 
  [ ] Update on Launch 

##### STEPS TO REPRODUCE

Create mutlisource inventory and sync it, i.e. manually or via tower-cli
```
tower-cli inventory batch_update -n "INVENTORY-WITH-MANY-SOURCES"
```
This results in data from the single source present. Subsequent sync solves issue.

##### EXPECTED RESULTS

Data from all inventories is present in "inventory variables"

##### ACTUAL RESULTS

Only data from single source is present.

**Comment by jakemcdermott** [comment]
@sumkincpp I believe this is fixed in the latest AWX version - closing.
