### ISSUE TITLE
RFE: Add Confirmation on Job Launch

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#2151]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Ask for the user to be sure to run a job from the jobs' list or allow to block/deny the launch for some templates from the jobs' list.

With some critical templates, it would be useful to check if the operator is sure to run those templates in order to avoid he pressed the run button for mistake.
This is especially critical when a previously run job is re-run using the button in the jobs' list, when no imput from the operator is needed.
We can ask for the user to be sure (a standard form) or we can block to run jobs from the jobs' list for some templates (and maybe for some users)

**Comment by wenottingham** [comment]
I don't think blocking job runs from the job list is practical - for anything the user could relaunch that way, they could launch with those parameters normally.  Confirming is potentially possible.

**Comment by mabashian** [comment]
A couple of thoughts here:

1) I'm not sure if this is necessary for launching templates that have prompts so I'd argue if prompting is involved we probably don't need to change anything.
2) When prompts are involved with a launch we have a summary/preview page that looks like:
<img width="804" alt="screen shot 2019-01-15 at 10 40 17 am" src="https://user-images.githubusercontent.com/9889020/51191265-047c2180-18b2-11e9-971f-a0b15b0dea79.png">
We could just _always_ show that preview page on launch/relaunch.  If there are no other prompts then it would be the only step but would provide a buffer against inadvertent clicks.

An alternative would be for the api to add some kind of flag to template resources that would let users mark them as "critical" and only show the launch confirmation when launching those templates.

**Comment by sugitk** [comment]
Can anyone look into this issue now?

A customer urgently wants this feature.  Unexpected running a job for a production system may cause a critical disaster. 

When removing a job template, we can see `Are you sure` dialog.  I suppose this feature is also needed on running / re-running a job.

**Comment by sugitk** [comment]
Another customer submitted an issue regarding this feature.

`PROMPT ON LAUNCH` in a JT/WFJT is effective though, it cannot be prompted when we relaunch a job in `JOBS` history screen.

**Comment by nixocio** [comment]
There are different ways to solve this, possibly changes on the API.

**Comment by ammygill** [comment]
+1 for this RFE

**Comment by shanemcd** [comment]
This is one of the reasons we added "Workflow Approval Nodes".
