### ISSUE TITLE
SCM Failure prints git synchronization passwords in plain text

### ISSUE THREAD

**Issue by gauravshankarsymcor** [ansible/awx#2153]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

SCM Failure  prints git synchronization passwords in plain text

##### ENVIRONMENT
* AWX version: 1.0.6.14
* AWX install method: docker
* Ansible version:  2.5.4

* Operating System: RHEL
* Web Browser:  chrome

##### STEPS TO REPRODUCE

Create an SCM update at the project level

ensure that scm fails by putting a wrong username ,, password which is encrypted gets printed in plain text

![image](https://user-images.githubusercontent.com/42220463/43861236-39bc52e0-9b24-11e8-87a9-a0a1e0ad34bb.png)
![image](https://user-images.githubusercontent.com/42220463/43861342-86106bb8-9b24-11e8-8fee-4b3abe7a312d.png)

##### EXPECTED RESULTS

password should be *******

##### ACTUAL RESULTS

Password is Password123 [Plain text]

**Comment by gauravshankarsymcor** [comment]
Gitlab is our SCM

**Comment by AStrangwood** [comment]
I have seen the same issue when using mercurial.

**Comment by ryanpetrello** [comment]
@gauravshankarsymcor @AStrangwood we've just released 1.0.7, which we believe resolves this issue.  You can try out here: https://github.com/ansible/awx/releases/tag/1.0.7

Let us know if you're still seeing issues after installing the latest awx - thanks!
