### ISSUE TITLE
Checkout-less project updates

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#2154]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
"check" type project updates check out the full source tree to the file system.

This is not necessary, and it will be done on the pre-JT sync anyway. It would be lazier behavior, and more performant, to avoid this in the updates themselves.

It would also be semantically more easy to understand that a "check" type update just checks.

##### ENVIRONMENT
* AWX version: all
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Create a project, check the projects folder. Alternatively, delete the project folder and do a new update, or update the project and do a new update.

##### EXPECTED RESULTS

source tree checkout is lazy, so the source tree should not be there after just creating the project, or be unaffected by the update.

The server should wait until actually running a job before checking out the source tree.

##### ACTUAL RESULTS

Every project update clones the full source tree

##### ADDITIONAL INFORMATION

the git module clearly has utilities to accomplish this:

https://github.com/ansible/ansible/blob/0a701ff74601748efa93fbc366e6368e53c39cd0/lib/ansible/modules/source_control/git.py#L494-L534

examples using git CLI:

```
$ git ls-remote https://github.com/ansible/ansible.git -h HEAD
8662e87b1af9b189d9c10d80655581807ad520dc	HEAD
$ git ls-remote https://github.com/ansible/ansible.git -h refs/heads/stable-2.3
b20520f500ad6878750bd2e2e8be46f756e4eaa5	refs/heads/stable-2.3
```

it appears that we can _just_ use these utilities without actually checking out if we use check_mode

https://github.com/ansible/ansible/blob/0a701ff74601748efa93fbc366e6368e53c39cd0/lib/ansible/modules/source_control/git.py#L1067-L1074

So this is entirely possible...

but a major challenge will be how we deal with populating the playbook list.

**Comment by chrismeyersfsu** [comment]
@AlanCoding I'm seeing people on the mailing list complaining about playbooks not appearing in the drop-down selector when they expect it to. One person mentioned they had to delete and resync their project. I'm wondering if different version of ansible/git are behaving differently given our parameters. If we recreate, we should make the check type project update behave like the run type project update to ensure our playbook list is up-to-date.

**Comment by AlanCoding** [comment]
yeah, closing b/c of no real plan to make this work with playbook list.
