### ISSUE TITLE
No job output in awx. 

### ISSUE THREAD

**Issue by pluto2112** [ansible/awx#2155]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Hello, i have installed AWX 1.0.6.41 but i have no output of the playbooks when i start a job and what went wrong. I already found a bug report but it was for an old version and already closed.

##### ENVIRONMENT
* AWX version: 1.0.6.41 
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  ansible 2.6.2
* Operating System: Ubuntu 16.04.5 LTS
* Web Browser: Firefox/Chrom

##### STEPS TO REPRODUCE

Let a script run

##### EXPECTED RESULTS

See the ansible output of the playbook

##### ACTUAL RESULTS

No output and no button where i could click to see the output

**Comment by sumkincpp** [comment]
Are you using vars_prompt in your playbook?
This might be a reason why you are not seeing any output.

**Comment by jakemcdermott** [comment]
This should be cleared up as of today - please re-open if you're still seeing this after updating. Thank you!
