### ISSUE TITLE
Slack integration is not working

### ISSUE THREAD

**Issue by computerlyrik** [ansible/awx#2161]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY

We try to evaluate the AWX and are not able to send slack notifications.
The documentation seems to be outdated.
Some examples how auth tokens look might be useful

##### ENVIRONMENT
* AWX version: 
awx-manage --version
3.2.4

* AWX install method: AWS europe central AMI

* Ansible version:  X.Y.Z
ansible --version
ansible 2.5.2

* Operating System:
* Web Browser: firefox

##### STEPS TO REPRODUCE

- Set up EC2 instance with latest AMI in Frankfurt Main
- Add a notification type "Slack"
- Click "Test notification" button

##### EXPECTED RESULTS

A notification should appear in my slack channel

##### ACTUAL RESULTS

from tower.log
```

2018-08-10 13:00:00,680 ERROR    awx.main.notifications.slack_backend Exception sending messages: 'NoneType' object has no attribute 'send_message'
2018-08-10 13:00:00,681 ERROR    awx.main.tasks Send Notification Failed 'NoneType' object has no attribute 'send_message'

```

##### ADDITIONAL INFORMATION

- We created a new app in slack (there is no way to add a bot only right now)
- We added a bot user
- We installed the app in our private channel
- We set up the channel name and the token starting with xoxb- (oAuth bot token) within Ansible tower

**Comment by wenottingham** [comment]
3.2.4 is an Ansible Tower version. If you are having issues with Ansible Tower, please contact your Red Hat support rep.
