### ISSUE TITLE
UI can erroneously show Failed to access license information error

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#2162]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
After login, the UI makes a call out to the config endpoint and then does _a number of things_ directly after that.  If any one of those things fails, the UI is currently throwing a generic error message about failing to access license information.  You can see that code [here](https://github.com/ansible/awx/blob/devel/awx/ui/client/src/login/loginModal/loginModal.controller.js#L97).  If we want to have just one generic catch we should probably change that message since right now it indicates an issue with the license which may not in fact be the case.  Otherwise, we should maybe look at handling errors for each of those steps individually so that a more relevant error message is shown to the user.

**Comment by matburt** [comment]
This specifically seems to happen when the API returns a 500 because the projects directory is not readable by AWX.

**Comment by nixocio** [comment]
Closing this one - since this is not longer accurate on the new UI.
