### ISSUE TITLE
RFE (?) remove spinny from the UI

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#2163]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
Ideally this service shouldn't exist, but in the short term lets replace the implementation of the `Wait` service with something that specifically disables save buttons, form fields, etc. (or whatever problem it's trying to solve) in a more targeted fashion instead of complete and total interruptive disablement of the UI for potentially more than one user at a time.

This would have significant, positive impacts on testability _and_ UX, particularly for situations where more than one user is using AWX at the same time.

**Comment by jakemcdermott** [comment]
ideas:

- For requests triggered via job status updates, etc. - if we can specifically identify and isolate them all (something we need to do anyway, because we're removing them in the future) we should consider removing the `working...` spinner entirely, 

- For form submissions, modal acknowledgements, list actions, etc. we maybe just disable the buttons and fields until the transaction completes.

- For everything else (transitions between pages, etc.) we can maybe show the spinny but don't disable anything.

**Comment by jakemcdermott** [comment]
Potential implementation details, which are just ideas that _might_ work, which we can adopt, modify, or throw out when the time comes:

Add two argument flags to the `wait` function:
   1. `showSpinny`: true/false -> default to true
   2. `disableEverything`: true/false -> default to false

- set the `disableEverything` flag to true for form saves, etc.
- set both flags to false for anything related to sockets or refreshing list data.

**Comment by Testicule** [comment]
kill it, the spinny needs to DIE.
