### ISSUE TITLE
How to call a bootstrap script from jobs template.

### ISSUE THREAD

**Issue by lion24** [ansible/awx#2167]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME
 - UI

##### SUMMARY
Call a bootstrap bash script.

##### ENVIRONMENT
* AWX version: 1.0.6.28 
* AWX install method: docker on linux
* Ansible version:  2.6.1 
* Operating System: Ubuntu linux
* Web Browser: Mozilla

##### STEPS TO REPRODUCE
Hi all,

We are using a setup.sh script that is sourced automatically using direnv. This setup.sh bootstrap some environment variables and also setup ansible (In order to avoid discrepancy among different ansible version, we decided in the team to configure ansible as a gitsubmodule in our project).

The setup.sh is also responsible of generating the ssh-config file based on the inventory. 

The problem is from ansible AWX I don't see whether or not it is possible to create a job template or workflow template that will do the bootstrap before running the configured playbook in the job template. Because right know it is failing complaining it cannot find the "ssh-config" file because setup.sh was not executed.

Can you give me some support on that? 

Thank you very much!

**Comment by wenottingham** [comment]
AWX is designed to run ansible-playbook; it is not designed to inject commands before that, and likely will not be designed to do so.

You'd have to do this in another way. AWX includes support for custom virtual environments, which likely could be used for your ansible versioning issues. If you're doing SSH config per inventory, that seems better done with inventory variables. Etc.
