### ISSUE TITLE
Slack Notifier - Adding colour to the alert removes the alert image and name which is set in slack

### ISSUE THREAD

**Issue by runtman** [ansible/awx#2168]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
This is more of a FYI (Something I just noticed).

I just added the colour #FF0000 to my slack notifier and I noticed within Slack, the name of the alert and the avatar of the alert vanished.

See the below image:

![bug](https://user-images.githubusercontent.com/6459792/44038951-de70e7a8-9f0f-11e8-881c-7b13dcf7ea63.png)

##### ENVIRONMENT
* AWX version:  AWX 1.0.5.24
* AWX install method:docker on linuxer
* Ansible version:  Ansible 2.5.0 
* Operating System: Ubuntu 16
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Add a colour to the notification (Slack)

##### EXPECTED RESULTS

The image and name changes on the bot account.

##### ACTUAL RESULTS

The name and image should remain the same.

##### ADDITIONAL INFORMATION

None.

**Comment by wenottingham** [comment]
Almost certainly fixed by https://github.com/ansible/awx/pull/2126

**Comment by runtman** [comment]
Interesting, I upgraded AWX today by removing the containers, pulling the latest devel branch and using the installer. Did my upgrade fail?

**Comment by wenottingham** [comment]
The latest even before today's devel merge was 1.0.6.something.

**Comment by runtman** [comment]
I guess something failed, thanks.

**Comment by runtman** [comment]
Just installed 1.0.7 and it still just shows "bot" it removes the name and also the icon you assign to the bot.

**Comment by runtman** [comment]
![screenshot from 2018-08-16 16-31-03](https://user-images.githubusercontent.com/6459792/44218533-cbf4e200-a171-11e8-9a36-104f45ab5749.png)

**Comment by runtman** [comment]
_______________ 
<  AWX 1.0.7.2  >
 --------------- 
        \   ^__^
         \  (oo)\_______
            (__)      A )\/\
                ||----w |
                ||     ||

Ansible 2.6.2
