### ISSUE TITLE
Installing Tower: The 'awx==3.2.6' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by DrStrangepork** [ansible/awx#2171]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

I am following the instructions https://docs.ansible.com/ansible-tower/latest/html/quickinstall/install_script.html
Eventually, I end up with this error:
```
TASK [awx_install : Migrate the Tower database schema (may take awhile when upgrading).] *
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["awx-manage", "migrate", "--noinput", "--fake-initial"], "delta": "0:00:00.139771", "end": "2018-08-13 22:33:05.880807", "msg": "non-zero return code", "rc": 1, "start": "2018-08-13 22:33:05.741036", "stderr": "Traceback (most recent call last):\n  File \"/bin/awx-manage\", line 5, in <module>\n    from pkg_resources import load_entry_point\n  File \"/usr/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 3098, in <module>\n    @_call_aside\n  File \"/usr/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 3082, in _call_aside\n    f(*args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 3111, in _initialize_master_working_set\n    working_set = WorkingSet._build_master()\n  File \"/usr/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 573, in _build_master\n    ws.require(__requires__)\n  File \"/usr/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 891, in require\n    needed = self.resolve(parse_requirements(requirements))\n  File \"/usr/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 777, in resolve\n    raise DistributionNotFound(req, requirers)\npkg_resources.DistributionNotFound: The 'awx==3.2.6' distribution was not found and is required by the application", "stderr_lines": ["Traceback (most recent call last):", "  File \"/bin/awx-manage\", line 5, in <module>", "    from pkg_resources import load_entry_point", "  File \"/usr/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 3098, in <module>", "    @_call_aside", "  File \"/usr/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 3082, in _call_aside", "    f(*args, **kwargs)", "  File \"/usr/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 3111, in _initialize_master_working_set", "    working_set = WorkingSet._build_master()", "  File \"/usr/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 573, in _build_master", "    ws.require(__requires__)", "  File \"/usr/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 891, in require", "    needed = self.resolve(parse_requirements(requirements))", "  File \"/usr/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 777, in resolve", "    raise DistributionNotFound(req, requirers)", "pkg_resources.DistributionNotFound: The 'awx==3.2.6' distribution was not found and is required by the application"], "stdout": "", "stdout_lines": []}
```

##### ENVIRONMENT
* AWX version: 3.2.6
* AWX install method: Via install of Ansible Tower
* Ansible version:  2.6.2
* Operating System: RHEL 7.5 (Maipo)
* Web Browser:

##### STEPS TO REPRODUCE

Running ./setup.sh causes the error. Also
```
# awx-manage --version
Traceback (most recent call last):
  File "/bin/awx-manage", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3098, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3082, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3111, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'awx==3.2.6' distribution was not found and is required by the application
```

##### EXPECTED RESULTS

I expect the installer to work

##### ACTUAL RESULTS

Errors above

##### ADDITIONAL INFORMATION

I also ran `pip install --upgrade setuptools pip wheel` outside of the Ansible Tower install process in order to work around previous errors installing ansible-tower-venv-ansible and ansible-tower-venv-tower

Checking the contents of /usr/lib/python2.7/site-packages/sos/plugins/tower.py, none of the following files exist either:

- /var/lib/awx/venv/awx/bin/pip 
- /var/lib/awx/venv/ansible/bin/pip 
- /etc/tower/awx.key
- /etc/tower/awx.cert

My guess is there is a pip module `awx` that is supposed to be installed, but it is either not there or not installed correctly?

**Comment by dfederlein** [comment]
This is a failed Tower install. Ansible BU/SAs are working with a Red Hat customer on this. This is not appropriate for the AWX repository.

For the record: The Tower installer is not maintained here, and the guess about the missing pip module is incorrect and this action likely created an issue with the python env:

_

> I also ran pip install --upgrade setuptools pip wheel outside of the Ansible Tower install process in order to work around previous errors installing ansible-tower-venv-ansible and ansible-tower-venv-tower

_

AWX team please close this. My team will work with the customer.

**Comment by DrStrangepork** [comment]
Actually @dfederlein, I have confirmed that the problem stemmed from the inclusion of pip 10.0.1 in the site-packages of awx, and running `pip install` outside of the Ansible Tower install process FIXED the problem.

You should think twice before throwing clients under the bus in a public forum.

**Comment by y2kkarthik** [comment]
@DrStrangepork  I seem to have a similar issue. May I know the resolution please?

**Comment by ryanpetrello** [comment]
This issue queue is intended for tracking issues in the open source project, AWX.  If you need support assistance with Red Hat Ansible Tower, please contact Red Hat.
