### ISSUE TITLE
SSH proxy doesn't work in awx

### ISSUE THREAD

**Issue by Colstuwjx** [ansible/awx#2172]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
I have been using the awx as our job system, and setup an inventory with a list of instances, they are all ssh via a jump host, and inventory ssh config likes below:

```
ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q admin@jumper-01"'
```
and awx throws error:

![image](https://user-images.githubusercontent.com/3972545/44078895-3d3f17d0-9fda-11e8-8506-d4dcbe6664bf.png)

##### ENVIRONMENT
* AWX version: 1.0.6.9
* AWX install method: docker on linux
* Ansible version:  2.5.3
* Operating System: CentOS 7
* Web Browser:

##### STEPS TO REPRODUCE

Add an inventory with some instances, and configure instance variable likes below:

```
ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q admin@jumper-01"'
```

##### EXPECTED RESULTS

Job result would be succeed.

##### ACTUAL RESULTS

Job result was failed, could NOT ssh into instances.

**Comment by Colstuwjx** [comment]
Ping @wenottingham , any suggestions?

**Comment by wenottingham** [comment]
There is not enough information in that failure to really debug.

**Comment by orgito** [comment]
Looks like Host key checking is failing. Can  you try this?

`ansible_ssh_common_args: '-o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p -q admin@jumper-01"'`

**Comment by Colstuwjx** [comment]
I have been successfully setup the proxy configuration according to the [document](https://docs.ansible.com/ansible-tower/latest/html/administration/tipsandtricks.html#setting-up-a-jump-host-to-use-with-tower).

Thanks!

**Comment by coudenysj** [comment]
If I'm ready the document [correctly](https://docs.ansible.com/ansible-tower/latest/html/administration/tipsandtricks.html#setting-up-a-jump-host-to-use-with-tower), I can only use 1 static jump host?

I'm trying to use kubespray directly into AWX, so through the ansible_ssh_common_args I can configure the jump host, but not the credentials for the jump host.

So for every jump host, I should add the key in the ssh config files of the workers?

**Comment by zx1986** [comment]
not work for me in 2022 :-(
can't find any setting about job isolation,
using awx-cli to check, only got `"AWX_ISOLATION_BASE_PATH": "/tmp"` and `"AWX_ISOLATION_SHOW_PATHS": []`

- AWX 19.1.0
- K8S
- awx operator
