### ISSUE TITLE
Cannot login in web UI

### ISSUE THREAD

**Issue by nduyhai** [ansible/awx#2178]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### ENVIRONMENT
* AWX version: 1.0.7
* AWX install method:  docker on linux
* Ansible version:  2.6.2
* Operating System: CentOS Linux release 7.2.1511
* Web Browser: Google Chrome Version 68.0.3440.106

##### STEPS TO REPRODUCE

- On remote server, clone awx repository from github, checkout version 1.0.7, install follow[ install guide](https://github.com/ansible/awx/blob/devel/INSTALL.md). Wait util install completed
- On local server, access web awx through [remote server ip]:80, login with username and password

##### EXPECTED RESULTS

- Login successful
##### ACTUAL RESULTS

- UI show message login failed
- Cookie have value: userLoggedIn=true and current_user ....

##### ADDITIONAL INFORMATION

![screenshot from 2018-08-16 13-35-44](https://user-images.githubusercontent.com/15892244/44193113-02276700-a15c-11e8-8d34-cbc66a354d1d.png)

**Comment by ryanpetrello** [comment]
@nduyhai can you share the `Response` tab of the red `/api/` request on the right side of your screenshot?

**Comment by nduyhai** [comment]
@ryanpetrello  There are response of `/api/`
![simulate](https://user-images.githubusercontent.com/15892244/44221028-75f06080-a1aa-11e8-9d99-26b173f56ce7.png)

Note:
- After login failed, i cannot access any `awx` endpoint. For access again, i must manually remove cookies
- Other case, when first time access (and no login) , i can access /api/ normally

**Comment by ryanpetrello** [comment]
@nduyhai what is the response code?  `HTTP 401`?  `HTTP 403`?  can you share the `Response` tab in your screenshot?

**Comment by nduyhai** [comment]
@ryanpetrello `Response` is empty, therefore not have response code (tab `Headers` contain  request and response)

* Response tab
![response](https://user-images.githubusercontent.com/15892244/44244234-21c29c00-a1fd-11e8-8d39-3991fa67284c.png)

* Review tab
![review](https://user-images.githubusercontent.com/15892244/44244240-2b4c0400-a1fd-11e8-80e2-5bf8810ba7da.png)

* Timing tab
![timing](https://user-images.githubusercontent.com/15892244/44244249-30a94e80-a1fd-11e8-8441-533c32f7e099.png)

**Comment by nduyhai** [comment]
Log of container awx_web when login failed:
```
yyy.yyy.yyy.yyy - - [17/Aug/2018:02:28:09 +0000] "GET /api/v2/ HTTP/1.1" 200 1545 "http://xxx.xxx.xxx.xxx/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-"
yyy.yyy.yyy.yyy - - [17/Aug/2018:02:28:09 +0000] "GET /static/partials/login/loginModal/thirdPartySignOn/thirdPartySignOn.partial.html HTTP/1.1" 200 539 "http://xxx.xxx.xxx.xxx/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-"
yyy.yyy.yyy.yyy - - [17/Aug/2018:02:28:09 +0000] "GET /static/assets/logo-login.svg HTTP/1.1" 200 38676 "http://xxx.xxx.xxx.xxx/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-"
[pid: 139|app: 0|req: 77/199] yyy.yyy.yyy.yyy () {44 vars in 762 bytes} [Fri Aug 17 02:28:09 2018] GET /api/v2/auth/ => generated 2 bytes in 44 msecs (HTTP/1.1 200) 8 headers in 221 bytes (1 switches on core 0)
yyy.yyy.yyy.yyy - - [17/Aug/2018:02:28:09 +0000] "GET /api/v2/auth/ HTTP/1.1" 200 2 "http://xxx.xxx.xxx.xxx/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-"
2018-08-17 02:28:21,677 INFO     awx.api.generics User admin logged in.
[pid: 139|app: 0|req: 78/200] yyy.yyy.yyy.yyy () {52 vars in 992 bytes} [Fri Aug 17 02:28:21 2018] POST /api/login/ => generated 0 bytes in 131 msecs (HTTP/1.1 302) 13 headers in 1844 bytes (1 switches on core 0)
yyy.yyy.yyy.yyy - - [17/Aug/2018:02:28:21 +0000] "POST /api/login/ HTTP/1.1" 302 0 "http://xxx.xxx.xxx.xxx/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-"
RESULT 2
OKREADY
RESULT 2
OKREADY
RESULT 2
OKREADY
RESULT 2
OKREADY
RESULT 2
OKREADY

```

**Comment by pschulten** [comment]
I also get a 403. But it says: 
```html
<h1>Forbidden <span>(403)</span></h1>
<p>CSRF verification failed. Request aborted.</p>
```
maybe you have the same issue?

**Comment by generalconsensus** [comment]
using incognito i can get in

**Comment by nduyhai** [comment]
In my case, UI cannot receive response because firewall filter it
