### ISSUE TITLE
RFE: Looking to control user access to the Ansible Tower during a particular time period

### ISSUE THREAD

**Issue by cesarfn4** [ansible/awx#2179]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
For example, if operator can execute certain automation task during the greenzone, they would prefer to provide that particular user access to Ansible Tower only during the Greenzone time period and restrict the access to ansible tower for other time period.

**Comment by wenottingham** [comment]
This is #1229, more or less. I assume they are only interested in restricting the ability to run jobs... restricting the ability to view prior jobs by timeframe doesn't make much sense to me at first glance.
