### ISSUE TITLE
my AWx is dead

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx#2180]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
When I try to access the dashboard on the AWX web ui I get "Failed to get dashboard job templates list: 500 a server error has occured".
When I try to get the list of templates, i get "Invalid search term entered. 500 a server error has occured", same on "My View"

##### ENVIRONMENT
* AWX version: 1.0.7
* AWX install method: docker on linux
* Ansible version:  2.6.2
* Operating System: openSUSE Leap 42.3
* Web Browser: firefox 59.0.1 on windows, firefox 61.0.2 on linux

##### STEPS TO REPRODUCE

Log in to the web ui, try to use it

##### EXPECTED RESULTS

I expected it "to work like it used to"

##### ACTUAL RESULTS

See above. web ui does not work. using AWX with tower-cli from the commandline is also broken.

##### ADDITIONAL INFORMATION

I have been running this set of AWX containers for several months with no problems, today i decided to update them, and that broke it.

Here's how i did the update:

- shut down all containers
- make backup of database folder
- delete containers and images
- git pull
- check inventory file for necessary changes
- run installer playbook as usual

After that i was able to login to my AWX just like before, but as soon as I try to actually do anything it breaks.

logfiles suggest that the database scheme has changed since my last pull, but no migration was done after my update.

From the postgres container:
ERROR:  column main_organization.job_template_admin_role_id does not exist at character 588

Any hints how to fix this quickly? Is there a migration script i can run without losing my data?

**Comment by mkempster22** [comment]
I also get this on a fresh installation of 1.0.7.2 on the dashboard plus all pages in the 'resources' category

**Comment by nschhina** [comment]
https://groups.google.com/forum/#!searchin/awx-project/1.0.7%7Csort:date/awx-project/z_sg_En-XIM/TcE5ECGgCQAJ . According to this, direct migration to 1.0.7 wouldn't work. You basically need to start afresh database and then import all the data You'd need.

**Comment by lemmy04** [comment]
I guess next time I consider upgrading my AWX i'll be thinking "better not."
