### ISSUE TITLE
Azure ansible_module_azure_rm_virtualmachine.py

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/awx#2181]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY
AWX does not handle Azure modules the same as ansible "core"

##### ENVIRONMENT
* AWX version: 1.0.6.41
* AWX install method: docker on linux
* Ansible version:  2.6.2

##### STEPS TO REPRODUCE

`azure_rm_virtualmachine:
    subscription_id: '{{ az_customer_subscription_id }}'
    ad_user: '{{ ad_user_login_var }}'
    password: '{{ ad_password_var }}'
    resource_group: '{{customer_prefix}}-can{{can_var}}'
    name: "{{customer_prefix}}-can{{can_var}}-vm"
    vm_size: "{{can_size_selection}}"
    os_type: Windows
    managed_disk_type: Premium_LRS
    public_ip_allocation_method: Dynamic
    admin_username: "{{admin_username}}"
    admin_password: "{{can_admin_password}}"
    virtual_network_resource_group: "{{customer_prefix}}-aio"
    virtual_network_name: "{{customer_prefix}}-vnet"
    subnet_name: "{{customer_prefix}}-aio-subnet"
    image:
      offer: WindowsServer
      publisher: MicrosoftWindowsServer
      sku: 2012-R2-Datacenter
      version: latest
    data_disks:
    - lun: 0
      disk_size_gb: 1023
      managed_disk_type: Premium_LRS
    - lun: 1
      disk_size_gb: 1023
      managed_disk_type: Premium_LRS
    - lun: 2
      disk_size_gb: 1023
      managed_disk_type: Premium_LRS`

##### EXPECTED RESULTS

In ansible core with same ansible version a VM is created

##### ACTUAL RESULTS

`
task path: /var/lib/awx/projects/_12__ansible141918/Playbooks/roles/azure-dce-can/tasks/main.yml:12 |  
-- | --
  | 103 | Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/azure/azure_rm_virtualmachine.py |  
  | 104 | <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root |  
  | 105 | <127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 && sleep 0' |  
  | 106 | The full traceback is: |  
  | 107 | File "/tmp/ansible_7Vosly/ansible_module_azure_rm_virtualmachine.py", line 1635, in create_default_nic |  
  | 108 | subnet = self.network_client.subnets.get(virtual_network_resource_group, virtual_network_name, self.subnet_name) |  
  | 109 | File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/azure/mgmt/network/v2017_11_01/operations/subnets_operations.py", line 175, in get |  
  | 110 | raise exp |  
  | 111 |   |  
  | 112 | fatal: [localhost]: FAILED! => { |  
  | 113 | "changed": false, |  
  | 114 | "invocation": { |  
  | 115 | "module_args": { |  
  | 116 | "ad_user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", |  
  | 117 | "adfs_authority_url": null, |  
  | 118 | "admin_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", |  
  | 119 | "admin_username": "testadmin", |  
  | 120 | "allocated": true, |  
  | 121 | "api_profile": "latest", |  
  | 122 | "append_tags": tru… |  
  | ... |   |  
  | 188 |   |  
  | 189 | PLAY RECAP ********************************************************************* | 14:42:10
  | 190 | localhost                  : ok=4    changed=1    unreachable=0    failed=1

`

##### ADDITIONAL INFORMATION

Seems like AWX has issues with the azure modules.

**Comment by wenottingham** [comment]
We would need the full output, not a truncated version.

**Comment by nicolaibaralmueller** [comment]
User error. Closing incident.
