### ISSUE TITLE
Inventoy var ca_trust_dir ignored when var project_data_dir is set

### ISSUE THREAD

**Issue by micahel71** [ansible/awx#2183]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
When you uncomment both variables `project_data_dir` and `ca_trust_dir` in the inventory file only `project_data_dir` will get mounted and `ca_trust_dir` is _ignored_.

##### ENVIRONMENT
* AWX version: 1.0.7.2
* AWX install method: docker on linux
* Ansible version:  2.6.2
* Operating System: RHEL Linux
* Web Browser: n/a

##### STEPS TO REPRODUCE
In the `installer/inventory` file uncomment both variables at the end.
Start the installer which will startup `awx_web` and `awx_task`.

> docker inspect <awx_web>
> docker inspect <awx_task>

In both container you will see that `ca_trust_dir` is not mounted.

##### EXPECTED RESULTS
Both mount points (`project_data_dir` and `ca_trust_dir`) should be available in the container.

##### ACTUAL RESULTS
Only `project_data_dir` is mounted.

**Comment by jimmyface** [comment]
I have this issue on my setup as well. 

- AWX version: 1.0.7
- AWX install method: Docker on Linux
- Ansible Version: 2.6.3
- OS: CentOS 7.5.1804 (Core)

I can't have both project_data_dir and ca_trust_dir defined. ca_trust_dir gets completely ignored if that is the case.

**Comment by ghjm** [comment]
Can you test and let us know if this is still a problem in current versions of AWX?

**Comment by jimmyface** [comment]
I just checked with version 3.0.0 and it appears to be working fine now.
