### ISSUE TITLE
Feature Idea: Add a Limit Option in Template Survey

### ISSUE THREAD

**Issue by jmarci** [ansible/awx#2184]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
Add an overriding limit option to the template survey to be able to select and define (single or multiple) hosts or host groups from the inventory source. 

Think a selectable limit option would be nice UI option. This would eliminate having to know and manually define these host(s) or host group(s) in the limit option free form field.

![image](https://user-images.githubusercontent.com/20398085/44298775-0a87bb00-a29e-11e8-8ed5-8f1dfda6fe8b.png)

**Comment by wenottingham** [comment]
This is #1179, closing as a duplicate.
