### ISSUE TITLE
Slack Notifier Not Retaining Avatar / Name

### ISSUE THREAD

**Issue by runtman** [ansible/awx#2187]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Since upgrading to 1.0.7, the Slack notifier ignores the Avatar and name that is set within the Slack configuration

##### ENVIRONMENT
* AWX version:Ansible 2.6.2
* AWX install method: docker on linux
* Ansible version: AWX 1.0.7.2
* Operating System: Ubuntu

##### STEPS TO REPRODUCE

Add a avatar and name to the bot in Slack and send a Slack notifier to it from AWX

##### EXPECTED RESULTS

To keep name and avatar

##### ACTUAL RESULTS

![screenshot from 2018-08-20 07-45-02](https://user-images.githubusercontent.com/6459792/44324240-f504c380-a44c-11e8-8d9c-0ee70534c306.png)

##### ADDITIONAL INFORMATION

It previous looked like this:

![screenshot from 2018-08-20 07-45-50](https://user-images.githubusercontent.com/6459792/44324272-12399200-a44d-11e8-87b9-296d055d1471.png)

**Comment by ryanpetrello** [comment]
@runtman we've got a fix coming for this in the near future; it's due to a bug in our usage of the Slack Web API.  In the meantime, if you remove the color you've defined on the Notification Template, the message will use the RTM API (it doesn't exhibit the same bug).

**Comment by runtman** [comment]
Strangely I tested with and without colour, I'll give it another go!

**Comment by runtman** [comment]
![feelsbadman](https://user-images.githubusercontent.com/6459792/44485542-d408c200-a648-11e8-9809-3eac10ad0c2c.png)

I deleted it, re added it and it;s still the same I'm afraid.

**Comment by ryanpetrello** [comment]
@runtman we've merged some changes into the latest version of awx (1.0.8) that we believe resolve this issue. If you're still encountering problems after upgrading, please let us know and we'll reopen this issue.

**Comment by tumluliu** [comment]
just upgraded from awx 1.0.4.14 to 2.0.1. This issue is happening in our slack bot notifications. Previously in 1.0.4, it worked fine with avatar and Name. Now all gone
