### ISSUE TITLE
Long job output missing tasks names

### ISSUE THREAD

**Issue by Herve-ross** [ansible/awx#2188]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Missing tasks name in job output

##### ENVIRONMENT
* AWX version: 1.0.6.46
* AWX install method: openshift
* Ansible version:  2.6.1
* Operating System: 7.5
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Run a playbook with multiple tasks on many nodes (log = 1769 lines)

##### EXPECTED RESULTS

PLAY [Update RHEL Servers 5 by 5] **********************************************************
TASK [Stop McAfee nails service] *************************************************************
changed: [myserver-btbs002.mydomain.com]
changed: [myserver-btbc001.mydomain.com]
changed: [myserver-btbs001.mydomain.com]
changed: [myserver-btbc002.mydomain.com]
TASK [UpdateAll : Upgrade All Packages] ****************************************
changed: [myserver-btbs002.mydomain.com]
changed: [myserver-btbc001.mydomain.com]
changed: [myserver-btbc002.mydomain.com]
changed: [myserver-btbs001.mydomain.com]
TASK [Start McAfee nails service] ************************************************************
changed: [myserver-btbs002.mydomain.com]
changed: [myserver-btbs001.mydomain.com]
changed: [myserver-btbc001.mydomain.com]
changed: [myserver-btbc002.mydomain.com]
PLAY [Update RHEL Servers 5 by 5] **********************************************************
TASK [Stop McAfee nails service] *************************************************************
changed: [myserver-btbs004.mydomain.com]
changed: [myserver-crus001.mydomain.com]
changed: [myserver-btbs003.mydomain.com]
changed: [myserver-docs001.mydomain.com]
TASK [UpdateAll : Upgrade All Packages] ****************************************
changed: [myserver-docs001.mydomain.com]
changed: [myserver-crus001.mydomain.com]
changed: [myserver-btbs004.mydomain.com]
changed: [myserver-btbs003.mydomain.com]
PLAY [Update RHEL Servers 5 by 5] **********************************************************
TASK [Stop McAfee nails service] *************************************************************
changed: [myserver-edwb001.mydomain.com]
changed: [myserver-ebxb001.mydomain.com]
changed: [myserver-edwb003.mydomain.com]
changed: [myserver-edwb002.mydomain.com]
TASK [UpdateAll : Upgrade All Packages] ****************************************
changed: [myserver-edwb001.mydomain.com]
changed: [myserver-edwb003.mydomain.com]
changed: [myserver-ebxb001.mydomain.com]
changed: [myserver-edwb002.mydomain.com]
TASK [Start McAfee nails service] ************************************************************
changed: [myserver-ebxb001.mydomain.com]
changed: [myserver-edwb001.mydomain.com]
changed: [myserver-edwb003.mydomain.com]
changed: [myserver-edwb002.mydomain.com]
PLAY [Reboot Servers 1 by 1 after update] **********************************************************
TASK [Gathering Facts] *********************************************************
ok: [myserver-apms001.mydomain.com]
TASK [RebootIfRequire : Install yum-utils] *************************************
ok: [myserver-apms001.mydomain.com]
TASK [RebootIfRequire : Check if reboot require] *******************************
ok: [myserver-apms001.mydomain.com]
TASK [RebootIfRequire : Reboot Host if Require] ********************************
skipping: [myserver-apms001.mydomain.com]
TASK [RebootIfRequire : waiting for host after reboot] *************************
skipping: [myserver-apms001.mydomain.com]
TASK [RebootIfRequire : Wait 10s before next action] ***************************
skipping: [myserver-apms001.mydomain.com]
TASK [RebootIfRequire : Check if reboot require] *******************************
skipping: [myserver-apms001.mydomain.com]
TASK [RebootIfRequire : Reboot Host if Require] ********************************
skipping: [myserver-apms001.mydomain.com]
TASK [RebootIfRequire : waiting for host after reboot] *************************
skipping: [myserver-apms001.mydomain.com]
TASK [RebootIfRequire : Wait 10s before next action] ***************************
skipping: [myserver-apms001.mydomain.com]
PLAY [Reboot Servers 1 by 1 after update] **********************************************************
TASK [Gathering Facts] *********************************************************
ok: [myserver-arcs001.mydomain.com]
TASK [RebootIfRequire : Install yum-utils] *************************************
ok: [myserver-arcs001.mydomain.com]
TASK [RebootIfRequire : Check if reboot require] *******************************
ok: [myserver-arcs001.mydomain.com]
TASK [RebootIfRequire : Reboot Host if Require] ********************************
skipping: [myserver-arcs001.mydomain.com]
TASK [RebootIfRequire : waiting for host after reboot] *************************
skipping: [myserver-arcs001.mydomain.com]
TASK [RebootIfRequire : Wait 10s before next action] ***************************
skipping: [myserver-arcs001.mydomain.com]
TASK [RebootIfRequire : Check if reboot require] *******************************
skipping: [myserver-arcs001.mydomain.com]
TASK [RebootIfRequire : Reboot Host if Require] ********************************
skipping: [myserver-arcs001.mydomain.com]
TASK [RebootIfRequire : waiting for host after reboot] *************************
skipping: [myserver-arcs001.mydomain.com]

##### ACTUAL RESULTS

PLAY [Update RHEL Servers 5 by 5] **********************************************
TASK [Stop McAfee nails service] ***********************************************
changed: [myserver-wmqm003.mydomain.com]
changed: [myserver-wmqm004.mydomain.com]
changed: [myserver-zeps001.mydomain.com]
changed: [myserver-zepc002.mydomain.com]
changed: [myserver-zepc001.mydomain.com]
TASK [UpdateAll : Upgrade All Packages with some exclusions] *******************
ok: [myserver-wmqm003.mydomain.com]
ok: [myserver-wmqm004.mydomain.com]
changed: [myserver-zepc001.mydomain.com]
changed: [myserver-zepc002.mydomain.com]
changed: [myserver-zeps001.mydomain.com]
TASK [Start McAfee nails service] **********************************************
changed: [myserver-zepc002.mydomain.com]
changed: [myserver-zepc001.mydomain.com]
changed: [myserver-zeps001.mydomain.com]
changed: [myserver-wmqm003.mydomain.com]
ok: [myserver-wmqm004.mydomain.com]
PLAY [Update RHEL Servers 5 by 5] **********************************************
changed: [myserver-zeps002.mydomain.com]
changed: [myserver-btbc001.mydomain.com]
changed: [myserver-apms001.mydomain.com]
changed: [myserver-btbc002.mydomain.com]
changed: [myserver-btbs001.mydomain.com]
changed: [myserver-btbc001.mydomain.com]
changed: [myserver-btbc002.mydomain.com]
changed: [myserver-zeps002.mydomain.com]
changed: [myserver-apms001.mydomain.com]
changed: [myserver-btbs001.mydomain.com]
changed: [myserver-zeps002.mydomain.com]
changed: [myserver-btbs001.mydomain.com]
changed: [myserver-btbc002.mydomain.com]
changed: [myserver-btbc001.mydomain.com]
changed: [myserver-apms001.mydomain.com]
PLAY [Update RHEL Servers 5 by 5] **********************************************
changed: [myserver-btbs003.mydomain.com]
changed: [myserver-etsc002.mydomain.com]
changed: [myserver-btbs004.mydomain.com]
changed: [myserver-etsc001.mydomain.com]
changed: [myserver-btbs002.mydomain.com]
changed: [myserver-btbs004.mydomain.com]
changed: [myserver-etsc002.mydomain.com]
changed: [myserver-btbs003.mydomain.com]
changed: [myserver-btbs002.mydomain.com]
changed: [myserver-etsc001.mydomain.com]
changed: [myserver-btbs004.mydomain.com]
changed: [myserver-etsc002.mydomain.com]
changed: [myserver-btbs002.mydomain.com]
changed: [myserver-etsc001.mydomain.com]
changed: [myserver-btbs003.mydomain.com]
PLAY [Reboot Servers 1 by 1 after update] **************************************
TASK [Gathering Facts] *********************************************************
ok: [myserver-wmqm003.mydomain.com]
TASK [RebootIfRequire : Install yum-utils] *************************************
ok: [myserver-wmqm003.mydomain.com]
TASK [RebootIfRequire : Check if reboot require] *******************************
ok: [myserver-wmqm003.mydomain.com]
TASK [RebootIfRequire : Reboot Host if Require] ********************************
skipping: [myserver-wmqm003.mydomain.com]
TASK [RebootIfRequire : waiting for host after reboot] *************************
skipping: [myserver-wmqm003.mydomain.com]
TASK [RebootIfRequire : Wait 10s before next action] ***************************
skipping: [myserver-wmqm003.mydomain.com]
TASK [RebootIfRequire : Check if reboot require] *******************************
skipping: [myserver-wmqm003.mydomain.com]
TASK [RebootIfRequire : Reboot Host if Require] ********************************
skipping: [myserver-wmqm003.mydomain.com]
TASK [RebootIfRequire : waiting for host after reboot] *************************
skipping: [myserver-wmqm003.mydomain.com]
TASK [RebootIfRequire : Wait 10s before next action] ***************************
skipping: [myserver-wmqm003.mydomain.com]
PLAY [Reboot Servers 1 by 1 after update] **************************************
TASK [Gathering Facts] *********************************************************
ok: [myserver-wmqm004.mydomain.com]
ok: [myserver-wmqm004.mydomain.com]
ok: [myserver-wmqm004.mydomain.com]
skipping: [myserver-wmqm004.mydomain.com]
skipping: [myserver-wmqm004.mydomain.com]
skipping: [myserver-wmqm004.mydomain.com]
skipping: [myserver-wmqm004.mydomain.com]
skipping: [myserver-wmqm004.mydomain.com]
skipping: [myserver-wmqm004.mydomain.com]
skipping: [myserver-wmqm004.mydomain.com]
PLAY [Reboot Servers 1 by 1 after update] **************************************
TASK [Gathering Facts] *********************************************************
ok: [myserver-zepc001.mydomain.com]
ok: [myserver-zepc001.mydomain.com]
ok: [myserver-zepc001.mydomain.com]
changed: [myserver-zepc001.mydomain.com]
ok: [myserver-zepc001.mydomain.com]
Pausing for 10 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)\r
ok: [myserver-zepc001.mydomain.com]
skipping: [myserver-zepc001.mydomain.com]
skipping: [myserver-zepc001.mydomain.com]
skipping: [myserver-zepc001.mydomain.com]
skipping: [myserver-zepc001.mydomain.com]
PLAY [Reboot Servers 1 by 1 after update] **************************************
TASK [Gathering Facts] *********************************************************
ok: [myserver-zepc002.mydomain.com]
ok: [myserver-zepc002.mydomain.com]
ok: [myserver-zepc002.mydomain.com]
changed: [myserver-zepc002.mydomain.com]
ok: [myserver-zepc002.mydomain.com]
Pausing for 10 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)\r
ok: [myserver-zepc002.mydomain.com]
skipping: [myserver-zepc002.mydomain.com]
skipping: [myserver-zepc002.mydomain.com]
skipping: [myserver-zepc002.mydomain.com]
skipping: [myserver-zepc002.mydomain.com]

##### ADDITIONAL INFORMATION

Hi, 
posting this issue because I don't see any open about it.

Expected result is the output I get using Ansible core.
The playbook I am using have 2 plays inside.
- First play have a parameter "serial= 5" which is respected in Ansible core output but AWX started well and suddenly show servers 10 by 10 in the tasks.
- Second play have a parameter "serial = 1" which is respected in Ansible core output but AWX started well and suddenly doesn't show lines for tasks name anymore.

Exporting the CSV give me the same output as web UI.

I just moved from 1.0.5.x to 1.0.6.x (fresh install) and 1.0.5.x had also some issue with line orders for jobs output.

Hope would'l find a fix, as of now, I don't find a workaround to extract the correct output.

**Comment by aperigault** [comment]
Hi,
This bug seems to be related to serial not to output size.
First serial pool work as expected but when the second pool start tasks names is missing.

**Comment by Gianlu** [comment]
Also I have a similar issue when serial=1. The first target works fine but the next ones are very confused

**Comment by nixocio** [comment]
Reopen this one if not addressed on the new UI.
