### ISSUE TITLE
Hashicorp Terraform Provider for AWX

### ISSUE THREAD

**Issue by mauromedda** [ansible/awx#2190]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
I'm proud to announce the WIP on a terraform provider for AWX. It's based on the Go SDK https://github.com/Colstuwjx/awx-go that we are extending to satisfy the provider and the AWX/Tower capabilities.
The current provider version permits CRUD operations on the basic inventory resource.

##### ADDITIONAL INFORMATION

https://github.com/mauromedda/terraform-provider-awx
https://github.com/Colstuwjx/awx-go

**Comment by ryanpetrello** [comment]
@mauromedda this is awesome 😄.  We generally use Github issues to track feature requests and bugs for awx itself.  You might want to announce this on the awx mailing list to reach a broader audience:

https://groups.google.com/d/forum/awx-project
