### ISSUE TITLE
Allow OAuth2 token creation for LDAP 

### ISSUE THREAD

**Issue by jmnguye** [ansible/awx#2191]
##### ISSUE TYPE
AWX 1.0.7.2 
While retrieving a token using an ldap account, i'm getting access denied : 
(access_denied) OAuth2 Tokens cannot be created by users associated with an external authentication provider (ldap)

##### COMPONENT NAME
Access is denied on both 
 - API
 - UI

##### SUMMARY
Not sure why we cannot retrieve an OAuth2 Tokens, there might be some unknown security reason, maybe i get a bug or something, but i would like to get an OAuth2 Tokens using an ldap account
(with ldap auth setup on AWX)

##### ADDITIONAL INFORMATION
Again, not sure if it's a "bug" or more a feature request, but as i get a clear error message, it seems to me that it should be more a feature request.

**Comment by ryanpetrello** [comment]
@jmnguye this is a default behavior we've enabled for security reasons:

1.  Log into awx with a user from SAML/LDAP/etc
2. They create an OAuth2 token for their use.
3.  They use their token to do things
4.  They get fired and are no longer in SAML/LDAP/OAuth/etc
5.  They cannot log into awx (we perform the e.g., LDAP search at login time to determine login validity).
6.  ... but they can still use their OAuth2 token to do things

https://github.com/ansible/awx/commit/df0e28ec651ca8378d5610e399b964e0a44a4bc1

You can disable this behavior by visiting `/api/v2/settings/ldap/` and setting `ALLOW_OAUTH2_FOR_EXTERNAL_USERS` to `True` (the default is `False`).

**Comment by jmnguye** [comment]
Thx a lot @ryanpetrello 
The setting is available on `/api/v2/settings/all/` on AWX 1.0.7.2

**Comment by ryanpetrello** [comment]
Typo on my part!

You can also find it at `/api/v2/settings/authentication/`.
