### ISSUE TITLE
No logging when debugging AD authentication issues

### ISSUE THREAD

**Issue by 0xceb1d** [ansible/awx#2194]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

- No logging when debugging AD authentication issues on Ubuntu 18.04.1 - AWX 1.0.7.2

##### ENVIRONMENT
* AWX version: 1.0.7.2
* AWX install method: docker on linux
* Ansible version:  2.6.2 
* Operating System: Ubuntu 18.04
* Web Browser: Safari, Firefox

##### STEPS TO REPRODUCE

`/etc/tower/conf.d/ldap.py` created
`LOGGING['handlers']['tower_warnings']['level'] =  'DEBUG'` added to ldap.py

LDAP Config:
```
Server URL
ldaps://<LDAP Server>:636

Bind DN
CN=ansible,CN=users,DC=<LDAP domain>,DC=com

LDAP User Search
[
 "OU=Users,DC=<LDAP domain>,DC=com",
 "SCOPE_SUBTREE",
 "(cn=%(user)s)"
]

LDSP Group Search
[
 "dc=<LDAP domain>,dc=com",
 "SCOPE_SUBTREE",
 "(objectClass=group)"
]

LDAP User Attribute MAP
{
 "first_name": "givenName",
 "last_name": "sn",
 "email": "mail"
}

LDSP Group Type Params
{
 "member_attr": "member",
 "name_attr": "cn"
}

LDSP User Flags by Group
{
 "is_superuser": [
  "cn=AWX Admin,ou=groups,dc=<LDAP domain>,dc=com"
 ]
}

LDAP Org MAP
{
 "MAIN": {
  "users": [
   "cn=AWX Users,ou=groups,dc=<LDAP domain>,dc=com"
  ],
  "admins": "cn=AWX Admin,ou=groups,dc=<LDAP domain>,dc=com",
  "remove_admins": false,
  "remove_users": false
 }
}
```
##### EXPECTED RESULTS

Failures logged into `/var/log/tower`

##### ACTUAL RESULTS

No logging exists on failed login with AD accounts

**Comment by Testicule** [comment]
If you use "docker logs --follow" to dump the awx_web logs to a file, and then "tail -f" the file, you may see a few django errors relating to ldap, so try this, and good luck.

You'll need it, i'm sorry to say:
docker logs --follow awx_web_container_id > /tmp/awx/logs/awx_web.log 2>&1 &
tail -n 100 -f /tmp/awx/logs/awx_web.log
