### ISSUE TITLE
Issues when /var/lib/awx/projects is on an NFS share

### ISSUE THREAD

**Issue by kerk1v** [ansible/awx#2195]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Docker Containers
- web
- task

##### SUMMARY
AWX is unable to check out the SCM repository of a project if the /var/lib/awx/projects volume is located on an NFS drive

##### ENVIRONMENT
* AWX version: 1.0.7.2 (:latest tag Docker Images) 
* AWX install method: Docker Compose (Swarm)
* Ansible version:  2.6.2
* Operating System: Docker Swarm on CentOS 7.2
* Web Browser: n/a 

##### STEPS TO REPRODUCE

- Have a docker swarm cluster where a directory for persistent volumes is mounted as nfs, i.e.: 
``nfs:/data/hdd                   /data/hdd               nfs     rw,sync         0 0``
- Install AWX with the Docker Compose method on a docker swarm. 
- Make sure /var/lib/awx/projects is mapped to a dir in the NFS mount specified above
- Create a project with any SCM as source for the playbooks. 
- Update / Checkout the project

##### EXPECTED RESULTS

- Project is checked out and playbooks are available

##### ACTUAL RESULTS

SCM Checkout job ends almost immediately and shows the following error message in the job detail: 

``Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 912, in run self.pre_run_hook(instance, **kwargs) File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 1746, in pre_run_hook self.acquire_lock(instance) File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 1726, in acquire_lock fcntl.flock(self.lock_fd, fcntl.LOCK_EX | fcntl.LOCK_NB) IOError: [Errno 9] Bad file descriptor``

##### ADDITIONAL INFORMATION

Seems to be an issue with Python's fopen() implementation and NFS locking.

**Comment by nschhina** [comment]
I've had this bug as well, in the end I just didn't use NFS and store files on the ec2 instance. But does need to be fixed

**Comment by nschhina** [comment]
Any update on this issue? This is still broken

**Comment by matburt** [comment]
This has to do with our locking to prevent simultaneous access to the project while the system is running project updates. In the near future AWX will transition to using ansible-runner which has this as a feature: https://github.com/ansible/ansible-runner/issues/112

This would allow us to bypass creating lock files under projects since we wouldn't need to share that execution directory
