### ISSUE TITLE
Job detail and job output not updated

### ISSUE THREAD

**Issue by andersharrisson-ess** [ansible/awx#2198]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### ENVIRONMENT
* AWX version: 1.0.7.2
* AWX install method: docker on linux
* Ansible version:  2.6.2
* Operating System: Linux
* Web Browser: Firefox 61.0.1

##### STEPS TO REPRODUCE

Run a job template and wait to be redirected to the job output page.

##### EXPECTED RESULTS

The job output console should automatically be filled with log output and the job status in the job detail pane should be updated upon completion of the job.

##### ACTUAL RESULTS

Initially the output and details work as intended, but after a certain time (a day or two?) job output console remains empty and the job detail still indicates "Running" state until the page is manually refreshed. Clicking the "Go to first page" on the job output also refreshes the console output.
Restarting the container solves the issue temporarily.

##### ADDITIONAL INFORMATION

We've had similar experiences with older versions of AWX, but now recently upgraded to 1.0.7 with hopes that it would fix the issue.
Similarly with others, we run AWX behind a reverse proxy (Traefik), but I find it hard to believe that the proxy would cause the issues since it works after AWX container restart.
This issue is more or less the same as #1861, but in accordance with https://github.com/ansible/awx/issues/1861#issuecomment-415033350 I am reposting to let you know that the issue remains in 1.0.7.2.

**Comment by jakemcdermott** [comment]
Hey 	andersharrisson-ess, Thanks for filing this issue. I believe this has been fixed downstream - the fix should be making it to AWX in the next version.

**Comment by boris-42** [comment]
@jakemcdermott any ideas when the new release is expected?
