### ISSUE TITLE
Allow team name to be shown in the permission tab under credentials

### ISSUE THREAD

**Issue by jainnikhil30** [ansible/awx#2199]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

Allow team name to be shown under the permission tab on credentials. Currently when you give a permission to team on a credential, individual users of team are shown under the permission tab (hovering over the team roles does show the team name). But, If there are large number of teams and user, it becomes hard to figure out which teams have been given permission. Explicitly putting team names in the permission tab will be useful.

**Comment by wenottingham** [comment]
This is a variation of #587
