### ISSUE TITLE
API: no matching hosts found inconsistency

### ISSUE THREAD

**Issue by fredleger** [ansible/awx#220]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
"No matching hosts found" reported by callbacks when run is ok from UI.

##### ENVIRONMENT
* AWX version: 1.0.0.312
* Ansible version:  2.3.1.0
* Operating System: docker
* Web Browser: chrome
-->

##### STEPS TO REPRODUCE
- setup openstack based inventory
- setup a job using sample hello-world.yml
- enable callbacks in the job
- run from the ui
- then try to run from callback call

##### EXPECTED RESULTS
Results should be the same on both sides

##### ACTUAL RESULTS
From UI:
```
Identity added: /tmp/awx_94_3i8OFp/credential_5 (/tmp/awx_94_3i8OFp/credential_5)

PLAY [Hello World Sample] ******************************************************16:37:27

TASK [Gathering Facts] *********************************************************16:37:27
ok: [0211208b-d41e-4f51-a7ad-a7c349999a8e]
ok: [3c82d6a9-7aec-4ba6-826a-9b8930db2e15]
TASK [Hello Message] ***********************************************************16:37:32
ok: [3c82d6a9-7aec-4ba6-826a-9b8930db2e15] => {
    "msg": "Hello World!"
}
ok: [0211208b-d41e-4f51-a7ad-a7c349999a8e] => {
    "msg": "Hello World!"
}

PLAY RECAP *********************************************************************16:37:32

0211208b-d41e-4f51-a7ad-a7c349999a8e : ok=2    changed=0    unreachable=0    failed=0   
3c82d6a9-7aec-4ba6-826a-9b8930db2e15 : ok=2    changed=0    unreachable=0    failed=0   
```

From callback:
```
curl --data 'host_config_key=xxxxxxxxxxxxxx' http://localhost:80/api/v2/job_templates/12/callback/
{"msg":"No matching host could be found!"}
```

##### ADDITIONAL INFORMATION

- inventory is configured to update on launch and actually we can see it did and stop there.

**Comment by wenottingham** [comment]
What's your host that the request is coming from? Does reverse DNS match to get the inventory hostname entry?

**Comment by fredleger** [comment]
currently from my laptop where awx is running a gueerlinguy/awx stack. I don't get the point here does the callbacks are supposed to be called from the host that need provisionning ?

The idea here was to trigger the job from my laptop to provision 2 openstack servers in the cloud

**Comment by wenottingham** [comment]
Yes, provisioning callbacks are called from the host that requires configuration, and are limited to that host. See http://docs.ansible.com/ansible-tower/latest/html/userguide/job_templates.html#provisioning-callbacks for an example.

If you just want to launch jobs locally via the API, see `/api/v2/job_templates/N/launch`.

**Comment by fredleger** [comment]
ok thanks, good to know
