### ISSUE TITLE
Dynamic survey by url

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/awx#2200]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Survey Multiple choice does not support dynamic lists from url as described here:
https://github.com/ansible/awx/pull/1408

##### STEPS TO REPRODUCE

Create IIS site with Webdav virtual directory. Point default document to a valid json.
Create a multiple choice survey and enter: "url: http://address/choices"

##### EXPECTED RESULTS

Multiple Choice Survey listing of the json content.

##### ACTUAL RESULTS

Choice only shows the string: "url: http://address/choices"

**Comment by wenottingham** [comment]
Right, that code was never merged, so it's expected that it doesn't work. If you're running a build with that patch applied, you're on your own, or should perhaps contact the initial author.

**Comment by nicolaibaralmueller** [comment]
@wenottingham So Tower does have no dynamic survey options what so ever? Hmm

I hope this feature will arrive soon. Hardcoding lists, for example AD groups and user, is not viable for enterprises.
