### ISSUE TITLE
Use semver for AWX version numbers

### ISSUE THREAD

**Issue by Gui13** [ansible/awx#2203]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - Installer

##### SUMMARY

At multiple points in the life of AWX, you published minor versions that broke the AWX installation of people using your install script.

I'd suggest (as is suggested in the [comments of issues](https://github.com/ansible/awx/issues?q=is%3Aissue+migration+is%3Aclosed) related to the migration) that you at least use semver versioning (https://semver.org/). 

For instance, the 1.0.7 version cannot be migrated from the 1.0.6 previous version, contrary to what the minor bump in the version seems to suggest.
I personally encountered the issue multiple times when switching from 1.6.0.X to 1.6.0.X+1, which is really surprising.  
I understand the policy that you [underlined](https://github.com/ansible/awx/issues/2173#issuecomment-412952459) in a [few](https://github.com/ansible/awx/issues/1817#issuecomment-385449265) of the [issues](https://github.com/ansible/awx/issues/1363) (that migration is best effort and the official recommended way is to completely reinstall the stack and import a json), but I think there is a middleground where you could save yourself and the enthousiasts here trying your software a bit of time: switch to using semantic versioning.

Using semver would at least solve a host of problems:

- people using "1" or "1.X" tag in the docker image version would be confident that rebooting the cluster won't botch their AWX install
- We could plan the updates more easily, with a clear difference between major versions and patch versions.
- You would actually see a lot less bugs related to migrations here in Github.

 Just.. try to not break people stuff when pushing minor versions that are actually major versions.
Also, as a more personal opinion: you are not flattering your potential EE clients that might want the Tower version but actually try the OSS version. We have already lost a lot of man-days rebuilding our AWS stack from broken migrations, and this doesn't shine, neither from us Devops folks nor our hierarchy.

As a closing message, let me tell you that I appreciate the effort of opensourcing this product, and the immense work that RH is putting in it.

**Comment by ryanpetrello** [comment]
@Gui13 I just wanted to chime in and say that we _are_ aware of how painful this has been for open source AWX users, and that we're actively working on ways to make this better in the future.  Thanks for your feedback and suggestions!

**Comment by matburt** [comment]
As per our announcements at Ansiblefest Austin we'll be doing this going forward: https://groups.google.com/forum/#!topic/awx-project/FKEZwrO-96k

**Comment by clcollins** [comment]
@matburt: Pardon my confusion, but that appears to be a link to an announcement for an Ansiblefest group?

EDIT: Nevermind - I see the point in the agenda to discuss this issue.
