### ISSUE TITLE
notification option: job output as attachment or inline with message body

### ISSUE THREAD

**Issue by Rthur** [ansible/awx#2207]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Notifications should have option to include job output as attachment (plain/html) or inline with body. I maintain a very clean template UI for users who only need to run workflow templates. I don't grant these users access to the underlying templates. As such these are hidden from the Templates and Jobs tab. These users can't view the output of failed jobs. If I could include job output of a failed playbook in the notification, I can maintain a clean Template UI.

**Comment by wenottingham** [comment]
This is part of  #79 ... however, this is not at all practical for a large number of notification destinations. Closing as a duplicate.
