### ISSUE TITLE
Can demote last admin to a normal user

### ISSUE THREAD

**Issue by NiveditaKumari14** [ansible/awx#2208]
ISSUE TYPE
Feature/ Bug 

COMPONENT NAME
UI

SUMMARY
I changed the role of only admin user (default admin) to normal user and now i cant change the role back to System admin neither i can create project or can do anything.
Is there any thing that can be done in this case.

See Screen Shots:
This will work:

**Comment by AlanCoding** [comment]
you need to make a new superuser through the management command `awx-manage createsuperuser`

However, the API is supposed to prevent you from demoting the last remaining superuser, if you have steps for how you achieved this state, we will look into it.

**Comment by wenottingham** [comment]
```[notting@nostromo: ~]$ tower-cli user list
== ======== ================= ========== ========= ============ ================= 
id username       email       first_name last_name is_superuser is_system_auditor 
== ======== ================= ========== ========= ============ ================= 
 2 joe      joe@joe.joe       Joe        joe              false             false
 1 admin    admin@example.com                              true             false
== ======== ================= ========== ========= ============ ================= 
[notting@nostromo: ~]$ tower-cli user modify 1 --is-superuser false
Resource changed.
== ======== ================= ========== ========= ============ ================= 
id username       email       first_name last_name is_superuser is_system_auditor 
== ======== ================= ========== ========= ============ ================= 
 1 admin    admin@example.com                             false             false
== ======== ================= ========== ========= ============ ================= 
```

You can demote the last superuser to a normal user. Unsure if this is really a bug (as opposed to just a missing guardrail we may or may not want.)

**Comment by ryanpetrello** [comment]
What @wenottingham said; this is just how it works.
