### ISSUE TITLE
Environment Variables injection

### ISSUE THREAD

**Issue by fredleger** [ansible/awx#221]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
sometimes we need to have access to the shell environments variables to run the job.
one good exemple of that is when using os_server_* tasks which could rely on OS_* vars.

This could prevent users to switch from local ansible scripts to AWX/Tower 

##### ENVIRONMENT
* AWX version: next one ?
* Ansible version:  any
* Operating System: any
* Web Browser: any

**Comment by wenottingham** [comment]
This is settable globally in AWX settings.

Having this on a per org/JT level would be an enhancement.

**Comment by fredleger** [comment]
in the case of openstack variables, having them available globally is not an option, it can be different by customers / projects.

And also very sensitive information.

**Comment by wenottingham** [comment]
Note that per-*task* can be done via the environment task (http://docs.ansible.com/ansible/latest/playbooks_environment.html) which can be fed by extra vars, vaulted vars, etc.

**Comment by wenottingham** [comment]
This is doable via custom credentials - these can be used to inject custom environment variables.

**Comment by arthur-c** [comment]
Hi, too bad this issue is closed, "Having this on a per org/JT level would be an enhancement" is an expected functionality.

Is there a simple way to do it with custom credentials ? It's not trivial to set it up.

**Comment by rluisr** [comment]
now AWX support OpenStack credential and works fine with openstack module.
no need create custom credentials.
