### ISSUE TITLE
Restrict virtual environment access per org 

### ISSUE THREAD

**Issue by HarishaAmeen** [ansible/awx#2212]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
AWX now populates all the available venvs to all the users, we would like to restrict it based onorganization's assigned venv. 

##### ENVIRONMENT
* AWX version: 1.0.4
* AWX install method: openshift
* Ansible version:  2.6.3
* Operating System: CentOS
* Web Browser: google chrome

##### STEPS TO REPRODUCE

1. Create a new venv as described in the page https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md
2. Assign newly created venv to any of the existing org and logout as admin user.
3. Login as a member of the org to which venv was assigned.
4. Create a new job template (for example) and select the dropdown to choose virtual environment. User will be able to see all the venvs not just the ones assigned to the org.

Ideally I would expect only assigned venv to pop up in the dropdown.

##### EXPECTED RESULTS

Ideally I would expect only assigned venv to pop up in the dropdown.

##### ACTUAL RESULTS

All the venvs are listed in the dropdown.

##### ADDITIONAL INFORMATION
NA

**Comment by wenottingham** [comment]
venvs do not currently have RBAC at all (and in fact, are not really objects in that sense).

**Comment by HarishaAmeen** [comment]
Hi @wenottingham Thanks for your quick reply. Do you know what does happen when you assign a particular vnev to an organization? My intention is to prevent users from using the venvs created for other users, with no RBAC any user can install any python modules in any venv. How do we stop this from happening?

Even if you suggest any workaround for the situation I'm facing at the moment, will be helpful.!

Thanks.

**Comment by wenottingham** [comment]
> Do you know what does happen when you assign a particular vnev to an organization?

venv assignment is about use of the venv, not management of the venv. When you assign a venv to an organization, it means it will be used for all jobs in that organization (that do not explicitly pick a different venv). 

>  with no RBAC any user can install any python modules in any venv. How do we stop this from happening?

That's not the case. Any venv modifications have to be done by the sysadmin *on the AWX server*... there's no way to add/remove/modify a venv from AWX itself. So you should not have this problem.

**Comment by HarishaAmeen** [comment]
@wenottingham Thanks for your response. Just would like to mention that it is possible to install/uninstall pip modules inside a venv using a playbook (Ansible pip module can be used). An example task can be:

    - name: install bottle
      pip:
        name: bottle
        virtualenv: /var/lib/awx/venv/test

Is there a way I can restrict users from not executing such tasks?

Regards,
Harish

**Comment by wenottingham** [comment]
On the AWX server? Sure, if job isolation is on, they can't do this...

**Comment by shanemcd** [comment]
Virtual environment support has been removed in favor of Execution Environments.
