### ISSUE TITLE
Can't launch a job template with prompted variables via API

### ISSUE THREAD

**Issue by techBeck03** [ansible/awx#2215]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
API

##### SUMMARY
I have a job template that prompts for inventory, credentials, and extra_vars.  If i launch this template within the web UI everything works as expected.  If however i send the same post via the API (using POSTMAN) with the exact same payload, the job doesn't launch.

##### ENVIRONMENT
* AWX 1.0.7.2
* AWX install method: docker on linux
* Ansible version:  2.6.2
* Operating System: Cent7
* Web Browser: Chrome

##### STEPS TO REPRODUCE
POSTMAN call (Authorization header properly defined)
(POST) http://172.16.1.75/api/v2/job_templates/16/launch

request_payload =
{
    "inventory_id": 2, 
    "extra_vars": {
        "deployment": {
            "id": "brandon api test", 
            "user": {
                "name": "Brandon"
            }
        }
    }, 
    "credentials": [
        9
    ]
} 

##### EXPECTED RESULTS

I expect to get a response with a pending status and a job id.

##### ACTUAL RESULTS

I get the following response with looks like it isn't accepting my prompted variables but nothing shows ignored

{
    "can_start_without_user_input": false,
    "passwords_needed_to_start": [],
    "ask_variables_on_launch": true,
    "ask_tags_on_launch": false,
    "ask_diff_mode_on_launch": false,
    "ask_skip_tags_on_launch": false,
    "ask_job_type_on_launch": false,
    "ask_limit_on_launch": false,
    "ask_verbosity_on_launch": false,
    "ask_inventory_on_launch": true,
    "ask_credential_on_launch": true,
    "survey_enabled": false,
    "variables_needed_to_start": [],
    "credential_needed_to_start": false,
    "inventory_needed_to_start": true,
    "job_template_data": {
        "id": 16,
        "description": "",
        "name": "Deploy Multiple VMs"
    },
    "defaults": {
        "job_tags": "",
        "extra_vars": "",
        "verbosity": 0,
        "job_type": "run",
        "diff_mode": false,
        "skip_tags": "",
        "limit": "",
        "inventory": {
            "id": null,
            "name": null
        }
    }
}

**Comment by techBeck03** [comment]
Sorry was missing a trailing / on my url :-)

**Comment by leemeador** [comment]
I would call it a bug when I enter the URL without a trailing slash and the api call fails. Shouldn't it work with or without a slash?

**Comment by syunwei** [comment]
Hi techBeck03,
Thanks for sharing the problem and solution.
Adding a trailing slash '/' fixed my problem :-)
Thank you!!

**Comment by ryanm63** [comment]
I faced same issue, but it caused to http in place of https in url
