### ISSUE TITLE
RFE: Allow adding and linking of Workflows within a Workflow.

### ISSUE THREAD

**Issue by IshwarKanse** [ansible/awx#2216]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Feature to add and link other Workflows from the Workflow Visualizer, similar to adding job templates, project and inventory sync.

**Comment by ghost** [comment]
+1 Useful feature

**Comment by sumkincpp** [comment]
Will solve great problem about workflow recovery, i.e. if one of the steps failed in workflow that was referenced in our main workflow(no matter what step), we will still be able to use single node(template/workflow) as a recovery.

**Comment by AlanCoding** [comment]
Sorry we missed this card earlier, but it's a duplicate with https://github.com/ansible/awx/issues/2252 and is under active development now. I am closing this issue because we have a bunch of links already pointing to the other card.
