### ISSUE TITLE
image_build docker install fails

### ISSUE THREAD

**Issue by p-kg** [ansible/awx#2217]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Commented the dockerhub_base in inventory

"ansible-playbook -i inventory  install.yml"
...
TASK [image_build : Build AWX distribution using container] ***********************************************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error creating container: 500 Server Error: Internal Server Error (\"{\"message\":\"invalid reference format\"}\")"}

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: docker on linux
* Ansible version:  ansible 2.4.1.0
* Operating System: Linux [Red Hat Enterprise Linux Server release 6.8 (Santiago)]
* Web Browser: chrome

##### STEPS TO REPRODUCE

Comment dockerhub_base in inventory to run roles=>image_build

##### EXPECTED RESULTS
Have all the docker containers running and eventually add new packages.

**Comment by bisimrem** [comment]
Not sure if this will be helpful, but yesterday i've ran into the same issue - invalid reference format - (on Centos 7), because the roles were trying to call `git describe` with `--first-parent` in order to tag the images with the version based on AWX repo tag, which is not a known parameter to the git version that comes with the default yum (1.8.3.1)
Try getting a newer version of GIT or adjust the calls (remove this parameter).

**Comment by p-kg** [comment]
I get the following error message -
TASK [image_build : Build AWX distribution using container] *****************************************************************************************

fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "npm --unsafe-perm --prefix awx/ui install awx/ui\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/timezone-js.git /root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-6937de14ce0c193961538bb5b3b12b7ef62a358f-d653e9e1: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-6937de14ce0c193961538bb5b3b12b7ef62a358f-d653e9e1'...\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/timezone-js.git /root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-6937de14ce0c193961538bb5b3b12b7ef62a358f-d653e9e1: fatal: unable to connect to github.com:\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/timezone-js.git /root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-6937de14ce0c193961538bb5b3b12b7ef62a358f-d653e9e1: github.com[0: 192.30.255.112]: errno=Connection refused\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-tz-extensions.git /root/.npm/_git-remotes/git-github-com-ansible-angular-tz-extensions-git-9cabb05d58079092bfb29ccae721b35b46f28af6-a87177b8: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ansible-angular-tz-extensions-git-9cabb05d58079092bfb29ccae721b35b46f28af6-a87177b8'...\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-tz-extensions.git /root/.npm/_git-remotes/git-github-com-ansible-angular-tz-extensions-git-9cabb05d58079092bfb29ccae721b35b46f28af6-a87177b8: fatal: unable to connect to github.com:\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-tz-extensions.git /root/.npm/_git-remotes/git-github-com-ansible-angular-tz-extensions-git-9cabb05d58079092bfb29ccae721b35b46f28af6-a87177b8: github.com[0: 192.30.255.113]: errno=Connection refused\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-tz-extensions.git /root/.npm/_git-remotes/git-github-com-ansible-angular-tz-extensions-git-9cabb05d58079092bfb29ccae721b35b46f28af6-a87177b8: github.com[1: 192.30.255.112]: errno=Connection refused\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/jkbrzt/rrule.git /root/.npm/_git-remotes/git-github-com-jkbrzt-rrule-git-4ff63b2f8524fd6d5ba6e80db770953b5cd08a0c-f2d4f677: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-jkbrzt-rrule-git-4ff63b2f8524fd6d5ba6e80db770953b5cd08a0c-f2d4f677'...\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/jkbrzt/rrule.git /root/.npm/_git-remotes/git-github-com-jkbrzt-rrule-git-4ff63b2f8524fd6d5ba6e80db770953b5cd08a0c-f2d4f677: fatal: unable to connect to github.com:\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/jkbrzt/rrule.git /root/.npm/_git-remotes/git-github-com-jkbrzt-rrule-git-4ff63b2f8524fd6d5ba6e80db770953b5cd08a0c-f2d4f677: github.com[0: 192.30.255.113]: errno=Connection refused\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/jkbrzt/rrule.git /root/.npm/_git-remotes/git-github-com-jkbrzt-rrule-git-4ff63b2f8524fd6d5ba6e80db770953b5cd08a0c-f2d4f677: github.com[1: 192.30.255.112]: errno=Connection refused\nnpm ERR! tar.unpack unzip error /tmp/npm-27-78c6fe99/registry.npmjs.org/babel-istanbul/-/babel-istanbul-0.12.2.tgz\nnpm ERR! tar.unpack unzip error /tmp/npm-27-78c6fe99/registry.npmjs.org/es6-set/-/es6-set-0.1.5.tgz\nnpm ERR! tar.unpack untar error /tmp/npm-27-78c6fe99/registry.npmjs.org/es6-set/-/es6-set-0.1.5.tgz\nnpm ERR! tar.unpack unzip error /tmp/npm-27-78c6fe99/registry.npmjs.org/debug/-/debug-3.1.0.tgz\nnpm ERR! tar.unpack untar error /tmp/npm-27-78c6fe99/registry.npmjs.org/debug/-/debug-3.1.0.tgz\nnpm ERR! tar.unpack unzip error /tmp/npm-27-78c6fe99/registry.npmjs.org/has-value/-/has-value-1.0.0.tgz\nnpm ERR! tar.unpack unzip error /tmp/npm-27-78c6fe99/registry.npmjs.org/depd/-/depd-1.1.2.tgz\nnpm ERR! tar.unpack unzip error /tmp/npm-27-78c6fe99/registry.npmjs.org/postcss-selector-parser/-/postcss-selector-parser-2.2.3.tgz\nnpm ERR! tar.unpack untar error /tmp/npm-27-78c6fe99/registry.npmjs.org/postcss-selector-parser/-/postcss-selector-parser-2.2.3.tgz\nnpm ERR! tar.unpack unzip error /tmp/npm-27-78c6fe99/registry.npmjs.org/ms/-/ms-2.0.0.tgz\nnpm ERR! tar.unpack unzip error /tmp/npm-27-78c6fe99/registry.npmjs.org/querystringify/-/querystringify-2.0.0.tgz\nnpm ERR! fetch failed https://registry.npmjs.org/karma-html2js-preprocessor/-/karma-html2js-preprocessor-1.1.0.tgz\nnpm WARN retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND www-proxy.us.oracle.com www-proxy.us.oracle.com:80\nnpm ERR! Linux 4.9.93-linuxkit-aufs\nnpm ERR! argv \"/usr/bin/node\" \"/usr/bin/npm\" \"--unsafe-perm\" \"--prefix\" \"awx/ui\" \"install\" \"awx/ui\"\nnpm ERR! node v6.14.4\nnpm ERR! npm  v3.10.10\nnpm ERR! code 128\n\nnpm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/timezone-js.git /root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-6937de14ce0c193961538bb5b3b12b7ef62a358f-d653e9e1\nnpm ERR! Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-6937de14ce0c193961538bb5b3b12b7ef62a358f-d653e9e1'...\nnpm ERR! fatal: unable to connect to github.com:\nnpm ERR! github.com[0: 192.30.255.112]: errno=Connection refused\nnpm ERR! \nnpm ERR! \nnpm ERR! \nnpm ERR! If you need help, you may report this error at:\nnpm ERR!     <https://github.com/npm/npm/issues>\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /awx/npm-debug.log\nmake: *** [awx/ui/.deps_built] Error 1\nnpm --unsafe-perm --prefix awx/ui install awx/ui\nnpm WARN addRemoteGit Error: Command failed: git config --get remote.origin.url\nnpm WARN addRemoteGit \nnpm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:199:12)\nnpm WARN addRemoteGit     at emitTwo (events.js:106:13)\nnpm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)\nnpm WARN addRemoteGit     at maybeClose (internal/child_process.js:920:16)\nnpm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:351:11)\nnpm WARN addRemoteGit     at emitOne (events.js:96:13)\nnpm WARN addRemoteGit     at Socket.emit (events.js:188:7)\nnpm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:509:12)\nnpm WARN addRemoteGit  git://github.com/ansible/timezone-js.git#6937de14ce0c193961538bb5b3b12b7ef62a358f resetting remote /root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-6937de14ce0c193961538bb5b3b12b7ef62a358f-d653e9e1 because of error: { Error: Command failed: git config --get remote.origin.url\nnpm WARN addRemoteGit \nnpm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:199:12)\nnpm WARN addRemoteGit     at emitTwo (events.js:106:13)\nnpm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)\nnpm WARN addRemoteGit     at maybeClose (internal/child_process.js:920:16)\nnpm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:351:11)\nnpm WARN addRemoteGit     at emitOne (events.js:96:13)\nnpm WARN addRemoteGit     at Socket.emit (events.js:188:7)\nnpm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:509:12)\nnpm WARN addRemoteGit   killed: false,\nnpm WARN addRemoteGit   code: 1,\nnpm WARN addRemoteGit   signal: null,\nnpm WARN addRemoteGit   cmd: 'git config --get remote.origin.url' }\nnpm ERR! git fetch -a origin (https://git@github.com/ansible/angular-drag-and-drop-lists.git) fatal: unable to access 'https://git@github.com/ansible/angular-drag-and-drop-lists.git/': Proxy CONNECT aborted\nnpm WARN addRemoteGit Error: Command failed: git config --get remote.origin.url\nnpm WARN addRemoteGit \nnpm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:199:12)\nnpm WARN addRemoteGit     at emitTwo (events.js:106:13)\nnpm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)\nnpm WARN addRemoteGit     at maybeClose (internal/child_process.js:920:16)\nnpm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:351:11)\nnpm WARN addRemoteGit     at emitOne (events.js:96:13)\nnpm WARN addRemoteGit     at Socket.emit (events.js:188:7)\nnpm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:509:12)\nnpm WARN addRemoteGit  git://github.com/ansible/angular-tz-extensions.git#9cabb05d58079092bfb29ccae721b35b46f28af6 resetting remote /root/.npm/_git-remotes/git-github-com-ansible-angular-tz-extensions-git-9cabb05d58079092bfb29ccae721b35b46f28af6-a87177b8 because of error: { Error: Command failed: git config --get remote.origin.url\nnpm WARN addRemoteGit \nnpm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:199:12)\nnpm WARN addRemoteGit     at emitTwo (events.js:106:13)\nnpm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)\nnpm WARN addRemoteGit     at maybeClose (internal/child_process.js:920:16)\nnpm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:351:11)\nnpm WARN addRemoteGit     at emitOne (events.js:96:13)\nnpm WARN addRemoteGit     at Socket.emit (events.js:188:7)\nnpm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:509:12)\nnpm WARN addRemoteGit   killed: false,\nnpm WARN addRemoteGit   code: 1,\nnpm WARN addRemoteGit   signal: null,\nnpm WARN addRemoteGit   cmd: 'git config --get remote.origin.url' }\nnpm WARN addRemoteGit Error: Command failed: git config --get remote.origin.url\nnpm WARN addRemoteGit \nnpm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:199:12)\nnpm WARN addRemoteGit     at emitTwo (events.js:106:13)\nnpm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)\nnpm WARN addRemoteGit     at maybeClose (internal/child_process.js:920:16)\nnpm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:351:11)\nnpm WARN addRemoteGit     at emitOne (events.js:96:13)\nnpm WARN addRemoteGit     at Socket.emit (events.js:188:7)\nnpm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:509:12)\nnpm WARN addRemoteGit  git://github.com/jkbrzt/rrule.git#4ff63b2f8524fd6d5ba6e80db770953b5cd08a0c resetting remote /root/.npm/_git-remotes/git-github-com-jkbrzt-rrule-git-4ff63b2f8524fd6d5ba6e80db770953b5cd08a0c-f2d4f677 because of error: { Error: Command failed: git config --get remote.origin.url\nnpm WARN addRemoteGit \nnpm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:199:12)\nnpm WARN addRemoteGit     at emitTwo (events.js:106:13)\nnpm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)\nnpm WARN addRemoteGit     at maybeClose (internal/child_process.js:920:16)\nnpm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:351:11)\nnpm WARN addRemoteGit     at emitOne (events.js:96:13)\nnpm WARN addRemoteGit     at Socket.emit (events.js:188:7)\nnpm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:509:12)\nnpm WARN addRemoteGit   killed: false,\nnpm WARN addRemoteGit   code: 1,\nnpm WARN addRemoteGit   signal: null,\nnpm WARN addRemoteGit   cmd: 'git config --get remote.origin.url' }\nnpm ERR! git fetch -a origin (https://git@github.com/ansible/angular-breadcrumb.git) fatal: unable to access 'https://git@github.com/ansible/angular-breadcrumb.git/': Proxy CONNECT aborted\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/timezone-js.git /root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-6937de14ce0c193961538bb5b3b12b7ef62a358f-d653e9e1: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-6937de14ce0c193961538bb5b3b12b7ef62a358f-d653e9e1'...\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/timezone-js.git /root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-6937de14ce0c193961538bb5b3b12b7ef62a358f-d653e9e1: fatal: unable to connect to github.com:\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/timezone-js.git /root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-6937de14ce0c193961538bb5b3b12b7ef62a358f-d653e9e1: github.com[0: 192.30.255.113]: errno=Connection refused\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-tz-extensions.git /root/.npm/_git-remotes/git-github-com-ansible-angular-tz-extensions-git-9cabb05d58079092bfb29ccae721b35b46f28af6-a87177b8: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ansible-angular-tz-extensions-git-9cabb05d58079092bfb29ccae721b35b46f28af6-a87177b8'...\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-tz-extensions.git /root/.npm/_git-remotes/git-github-com-ansible-angular-tz-extensions-git-9cabb05d58079092bfb29ccae721b35b46f28af6-a87177b8: fatal: unable to connect to github.com:\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-tz-extensions.git /root/.npm/_git-remotes/git-github-com-ansible-angular-tz-extensions-git-9cabb05d58079092bfb29ccae721b35b46f28af6-a87177b8: github.com[0: 192.30.255.113]: errno=Connection refused\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-tz-extensions.git /root/.npm/_git-remotes/git-github-com-ansible-angular-tz-extensions-git-9cabb05d58079092bfb29ccae721b35b46f28af6-a87177b8: github.com[1: 192.30.255.112]: errno=Connection refused\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/jkbrzt/rrule.git /root/.npm/_git-remotes/git-github-com-jkbrzt-rrule-git-4ff63b2f8524fd6d5ba6e80db770953b5cd08a0c-f2d4f677: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-jkbrzt-rrule-git-4ff63b2f8524fd6d5ba6e80db770953b5cd08a0c-f2d4f677'...\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/jkbrzt/rrule.git /root/.npm/_git-remotes/git-github-com-jkbrzt-rrule-git-4ff63b2f8524fd6d5ba6e80db770953b5cd08a0c-f2d4f677: fatal: unable to connect to github.com:\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/jkbrzt/rrule.git /root/.npm/_git-remotes/git-github-com-jkbrzt-rrule-git-4ff63b2f8524fd6d5ba6e80db770953b5cd08a0c-f2d4f677: github.com[0: 192.30.255.113]: errno=Connection refused\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/jkbrzt/rrule.git /root/.npm/_git-remotes/git-github-com-jkbrzt-rrule-git-4ff63b2f8524fd6d5ba6e80db770953b5cd08a0c-f2d4f677: github.com[1: 192.30.255.112]: errno=Connection refused\nnpm ERR! tar.unpack unzip error /tmp/npm-28-0e0bace4/registry.npmjs.org/mute-stream/-/mute-stream-0.0.7.tgz\nnpm ERR! tar.unpack unzip error /tmp/npm-28-0e0bace4/registry.npmjs.org/d3/-/d3-3.3.13.tgz\nnpm ERR! Linux 4.9.93-linuxkit-aufs\nnpm ERR! argv \"/usr/bin/node\" \"/usr/bin/npm\" \"--unsafe-perm\" \"--prefix\" \"awx/ui\" \"install\" \"awx/ui\"\nnpm ERR! node v6.14.4\nnpm ERR! npm  v3.10.10\nnpm ERR! code 128\n\nnpm ERR! Command failed: git fetch -a origin\nnpm ERR! fatal: unable to access 'https://git@github.com/ansible/angular-drag-and-drop-lists.git/': Proxy CONNECT aborted\nnpm ERR! \nnpm ERR! \nnpm ERR! If you need help, you may report this error at:\nnpm ERR!     <https://github.com/npm/npm/issues>\nnpm ERR! tar.unpack untar error /tmp/npm-28-0e0bace4/registry.npmjs.org/d3/-/d3-3.3.13.tgz\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /awx/npm-debug.log\nmake: *** [awx/ui/.deps_built] Error 1\n", "status": 2}

**Comment by p-kg** [comment]
$npm -v
5.6.0
$node -v
v8.11.4

**Comment by shanemcd** [comment]
Hi. This is our bug tracking system. For help troubleshooting your installation, head over to #ansible-awx on FreeNode or send a message to our mailing list.
