### ISSUE TITLE
docker compose successful but awx throws error 

### ISSUE THREAD

**Issue by ghost** [ansible/awx#2219]
##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY
docker compose successful but awx throws error. 
ERROR!
Failed updating job undefined with variables. POST returned: 500 A server error has occurred.

##### ENVIRONMENT
* AWX version: 1.0.7.2
* AWX install method: docker for mac
* Ansible version: Ansible 2.6.2 
* Operating System: MacOS 
* Web Browser: Safari 

##### STEPS TO REPRODUCE

I just use docker-compose with the installer provided awx's installer. Also the error occurs : ansible-playbook -i inventory install.yml  ( attached my compose file for reference. ) 

##### EXPECTED RESULTS

Demo Project should be successfully execute and run successfully. 

##### ACTUAL RESULTS

THERE IS NO SCM UPDATE INFORMATION AVAILABLE FOR THIS PROJECT. AN UPDATE HAS NOT YET BEEN COMPLETED. IF YOU HAVE NOT ALREADY DONE SO, START AN UPDATE FOR THIS PROJECT.

ERROR!
Failed updating job undefined with variables. POST returned: 500 A server error has occurred.

**Comment by shanemcd** [comment]
This sounds like a misconfigured project. For help with troubleshooting, stick to the mailing list or IRC. This is our bug tracking system.

**Comment by kylix3511** [comment]
Attached is yaml file. 
[awx.yaml.zip](https://github.com/ansible/awx/files/2340852/awx.yaml.zip)

**Comment by ghost** [comment]
No Shane. It is not misconfigured project. It was working fine 3 days back. Same awx.yaml file.

**Comment by ghost** [comment]
[awx.yaml 2.zip](https://github.com/ansible/awx/files/2340872/awx.yaml.2.zip)
