### ISSUE TITLE
Cannot use JOB TAGS

### ISSUE THREAD

**Issue by ysolan** [ansible/awx#2222]
##### ISSUE TYPE
 - Bugs

##### COMPONENT NAME
 - UI

##### SUMMARY
Can't use JOB TAGS in a template.
I always have the message : "No result Found"

##### ENVIRONMENT
AWX version: 1.0.6.8
AWX install method: docker on linux
Ansible version: 2.5.2
Operating System: Redhat 7
Web Browser: Chrome

##### STEPS TO REPRODUCE

In a job template, select a playbook that contain tags.
Then try to use JOB TAGS

##### EXPECTED RESULTS

list of tags present in the playbook

**Comment by wenottingham** [comment]
This looks like #1182

**Comment by ysolan** [comment]
I have found the way to use JOB TAGS in a template.
just type the name of tags and press ENTER
