### ISSUE TITLE
Powershell on linux: Unable to retrieve the specified information about the process or thread.  It may have exited or may be privileged

### ISSUE THREAD

**Issue by endejoli** [ansible/awx#2223]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
##### SUMMARY

while exeucitng powershell script on linux through ansible,  got the below error 

 "FailFast: Unable to retrieve the specified information about the process or thread.  It may have exited or may be privileged.", 
        "", 
        "   at System.Environment.FailFast(System.String, System.Exception)", 
        "   at System.Environment.FailFast(System.String, System.Exception)", 
        "   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String, System.String[], Int32)", 
        "   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])"
    ], 

Now this may sound like an ansible issue, but executing ansible directly on that host, everything works fine. This issue occurs only when job executed through tower 

##### ENVIRONMENT
* AWX version: Tower 3.2.1
* AWX install method: on vm
* Ansible version:  ansible 2.4.1.0
* Operating System: 16.04.3 
* Web Browser: chrome

##### STEPS TO REPRODUCE

1) execute below task  
 - name: wershell script
      command: /usr/bin/pwsh  test.ps1
      args:
        chdir: "commandpipeline"

##### EXPECTED RESULTS
  Powershell should be executed successfully 

##### ACTUAL RESULTS

    "msg": "non-zero return code", 
    "rc": -6, 
    "start": "2018-09-04 09:32:09.378408", 
    "stderr": "FailFast: Unable to retrieve the specified information about the process or thread.  It may have exited or may be privileged.\n\n   at System.Environment.FailFast(System.String, System.Exception)\n   at System.Environment.FailFast(System.String, System.Exception)\n   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String, System.String[], Int32)\n   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])", 
    "stderr_lines": [
        "FailFast: Unable to retrieve the specified information about the process or thread.  It may have exited or may be privileged.", 
        "", 
        "   at System.Environment.FailFast(System.String, System.Exception)", 
        "   at System.Environment.FailFast(System.String, System.Exception)", 
        "   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String, System.String[], Int32)", 
        "   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])"
    ], 
##### ADDITIONAL INFORMATION

TASK [ powershell script] *****
task path: /var/lib/awx/projects/_59__sshgittesttest7999actintautomategit_development/ansible/test/test_clone_repository.yml:55
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/commands/command.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: awx
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1536053529.27-33824948249879 `" && echo ansible-tmp-1536053529.27-33824948249879="` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1536053529.27-33824948249879 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpCSK0jO TO /var/lib/awx/.ansible/tmp/ansible-tmp-1536053529.27-33824948249879/command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-tmp-1536053529.27-33824948249879/ /var/lib/awx/.ansible/tmp/ansible-tmp-1536053529.27-33824948249879/command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /var/lib/awx/.ansible/tmp/ansible-tmp-1536053529.27-33824948249879/command.py; rm -rf "/var/lib/awx/.ansible/tmp/ansible-tmp-1536053529.27-33824948249879/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": true, 
    "cmd": [
        "/usr/bin/pwsh", 
        "test.ps1"
    ], 
    "delta": "0:00:00.561549", 
    "end": "2018-09-04 09:32:09.939957", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "_raw_params": "/usr/bin/pwsh test.ps1", 
            "_uses_shell": false, 
            "chdir": "commandpipeline", 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "warn": true
        }
    }, 
    "msg": "non-zero return code", 
    "rc": -6, 
    "start": "2018-09-04 09:32:09.378408", 
    "stderr": "FailFast: Unable to retrieve the specified information about the process or thread.  It may have exited or may be privileged.\n\n   at System.Environment.FailFast(System.String, System.Exception)\n   at System.Environment.FailFast(System.String, System.Exception)\n   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String, System.String[], Int32)\n   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])", 
    "stderr_lines": [
        "FailFast: Unable to retrieve the specified information about the process or thread.  It may have exited or may be privileged.", 
        "", 
        "   at System.Environment.FailFast(System.String, System.Exception)", 
        "   at System.Environment.FailFast(System.String, System.Exception)", 
        "   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String, System.String[], Int32)", 
        "   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])"
    ], 
    "stdout": "", 
    "stdout_lines": []
}

**Comment by wenottingham** [comment]
Is this running powershell on the local awx server?

**Comment by endejoli** [comment]
yes, we have powershell core installed on the awx server.  if I execute ansible-playbook directly on the server everything works fine. If the job is invoked through UI/API job fails with above error

**Comment by wenottingham** [comment]
This is almost certainly a conflict with the job isolation environment playbooks run under. I assume it works if you disable job isolation?

**Comment by wenottingham** [comment]
I would note that 3.2.1 is not an AWX version. If you are having issues with Ansible Tower, please contact your Red Hat support rep.

**Comment by endejoli** [comment]
Is there a way to get around this problem without disabling job isolation?

**Comment by wenottingham** [comment]
I believe this is likely fixed in c1a0e2cd1660d77c984c51f337a75e31e3e6fb10... if you can reproduce this on a current AWX version, please re-open.
