### ISSUE TITLE
Allow Tower to handle manual projects similarly to SCM style.

### ISSUE THREAD

**Issue by gamuniz** [ansible/awx#2224]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API
 - UI
 

##### SUMMARY

It would be beneficial for those who do not have access to or desire to use a source control management tool to be able to sync projects across clusters. 
A utility to rsync and keep all clustered on the same revision.

**Comment by wenottingham** [comment]
This is not planned. We strongly recommend using source control as part of best Ansible practices.

If someone needs to do this behind the scenes, they can create their own process with rsync.

**Comment by ghost** [comment]
+1 good feature to implement
