### ISSUE TITLE
could not handle archive. Command \"unzip\" not found

### ISSUE THREAD

**Issue by mouliveera** [ansible/awx#2228]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY
could not handle archive. Command \"unzip\" not found

##### ENVIRONMENT
* AWX version: 16.04
* AWX install method: ansible, trying to unzip on ubuntu box
* Ansible version:  2.5.8
* Operating System: Ubuntu 16.04
* Web Browser:

**Comment by wenottingham** [comment]
This does not appear to be a bug in AWX. None of the AWX installation playbooks reference unzip or consul, certainly not installing consul directly from Hashicorp..

You may have better luck with the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project
