### ISSUE TITLE
email notification from awx docker images 

### ISSUE THREAD

**Issue by TwoTwenty** [ansible/awx#2230]
I am using the most recent version of awx docker images 1.0.7, the email notifier generates a url

https://awx.url.com/#/jobs/426
when in fact the location is 
https://awx.url.com/#/jobz/playbook/426

**Comment by matburt** [comment]
You need to configure the TOWER_URL_BASE in your settings.

**Comment by matburt** [comment]
This doesn't seem right... we don't use `jobz` and we *do* want to link to the job itself

**Comment by TwoTwenty** [comment]
This appears solved in the lates version of AWX. 2.0.1 potentially before. 

Thank you Marliana. & Matburt
