### ISSUE TITLE
"Invalid search term entered. GET returned: 400 無効な credential_type ID: NaN" when click CREDENTIAL at Templates (LANG Japanese only)

### ISSUE THREAD

**Issue by kakkotetsu** [ansible/awx#2231]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
`Invalid search term entered. GET returned: 400 無効な credential_type ID: NaN` when click `CREDENTIAL` at `Templates`.  
This problem occurs only when blowser language setting is `Japanese`.  (When browser language is `English`, not encounter this problem.)

##### ENVIRONMENT
* AWX version: `1.0.7.2`
* AWX install method: `docker on linux`
* Ansible version:  `2.6.2`
* Operating System:  `Ubuntu 18.04.1 LTS (Bionic Beaver)`
* Web Browser: `FireFox 62.0` , `Chrome 69.0.3497.81 (Official Build) (64 bit)` too

##### STEPS TO REPRODUCE

- docker-compose up
- Create belows on WebUI
    - Organization x1
    - Users x2
    - Teams x1
    - Credential x2
        - type Machine x1
        - type Network x1
    - Inventories x1 (static)
        - HOSTS x4
        - GROUPS x 3
- Create Job Template, and  click on CREDENTIAL search button, problem occur !

##### EXPECTED RESULTS

CREDENTIALS appear, same as blowser language setting is English.

##### ACTUAL RESULTS

pop up `Invalid search term entered. GET returned: 400 無効な credential_type ID: NaN` message

##### ADDITIONAL INFORMATION

- Browser language setting is `English`

![ok_en](https://user-images.githubusercontent.com/8026416/45281414-ae1d6180-b512-11e8-85e4-72690c9a800e.png)

- Browser language setting is `Japanese`

![invalid_ja](https://user-images.githubusercontent.com/8026416/45281427-b83f6000-b512-11e8-9246-1a06425d6aaa.png)

**Comment by NRDiaz92** [comment]
Hi, i'm having the same issue with the browser in spanish language

![image](https://user-images.githubusercontent.com/28863706/46677530-31d17900-cbb9-11e8-968b-894f1dbbdb6e.png)

**Comment by mgvazquez** [comment]
Same here in spanish.
Awx Version: 3.3.0

**Comment by wenottingham** [comment]
fixed by #2646
