### ISSUE TITLE
Slack notifications are failing

### ISSUE THREAD

**Issue by larrybg** [ansible/awx#2232]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY
Slack notifications are failing

##### ENVIRONMENT
* AWX  version 1.0.7.2
* AWX install method: docker on linux
* Ansible version:  2.6.s
* Operating System: Centos
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Install AWX with docker. Setup Slack notifications and test it. Error message " Job Notification: Notification failed" will appear.

##### EXPECTED RESULTS

The slack message should be sent successfully.

##### ACTUAL RESULTS
Nothing sent, error message appears.

##### ADDITIONAL INFORMATION
AWX is installed with the database on the separate box. SSL was configured with nginx.

**Comment by computerlyrik** [comment]
may have the same source of error as https://github.com/ansible/awx/issues/2161

**Comment by computerlyrik** [comment]
@larrybg  Managed to make it work:

- Create Slack app "AWX"
- Add permission chat:write:bot 
- use oauth token in AWX Notifications settings
- install slack app to your slack workspace

**Comment by larrybg** [comment]
@computerlyrik, we already have Slack boat and our existing Tower instance can send notifications to our channel. But AWX cannot send test notifications with the same Notifications settings. I'm using the same channel name and token. It's clearly AWX problem

**Comment by larrybg** [comment]
@computerlyrik Found the problem - just added the `#` at the beginning the channel name... 
It's clearly stating that `The pound symbol (#) is not required`, but you MUST put it with the channel name

**Comment by computerlyrik** [comment]
@larrybg Nope. Not on my side. Without ```#``` works good for me.
Just a note: I set up the AWX today, and i used a ```git checkout 1.0.7``` before running the install playbook. Just to make sure i am on the latest release version and not getting some in-between-version-bugs from master :)

**Comment by larrybg** [comment]
@computerlyrik That is the only change I did... hmm.. weird but it's working now

**Comment by sdarwin** [comment]
got the same results as the last messages in this thread:
- Without pound symbol, it did not work.   a few tests.
- Only change - add pound symbol.  Ok, it's fixed.
- Then, overall it is fixed. "weird but it's working now".

**Comment by jaybuidl** [comment]
Also:
- manually invite the Bot to the channels in Slack
