### ISSUE TITLE
Provide option for org admins to limit maximum verbosity allowed for any job launch

### ISSUE THREAD

**Issue by ghost** [ansible/awx#2236]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Add an option in the configuration to limit the maximum verbosity allowed for a job template within the organization.  This will limit the volume of data placed in the database for each run, and therefore, limit the overall size and associated performance and operational impacts.

**Comment by wenottingham** [comment]
Someone with the ability to edit a job template would have the ability to choose a different playbook that can produce more output, launch it N more times, etc. Having this just for verbosity feels like the wrong place to make this restriction.
