### ISSUE TITLE
Retrieve variables content from the API.

### ISSUE THREAD

**Issue by lion24** [ansible/awx#2243]
##### ISSUE TYPE
 - Documentation request

##### COMPONENT NAME
 - API

##### SUMMARY

I would like to know from the API, if it is possible to retrieve inventory variables. For example, from one of our inventory, we have a variable defined which is a list of integers. The ultimate goal would be to retrieve that list from the API and expose it in a survey for the user to select existing values.. 

If it's not possible that's not an issue, I could do it another way...

##### ADDITIONAL INFORMATION
 Nil

**Comment by wenottingham** [comment]
Yes, it's possible, see /api/v2/inventories/N/variables.

In any case, this isn't a bug report/feature request... this sort of thing is best handled on the awx-project mailing list.
