### ISSUE TITLE
Windows remote host fails via public ip but not fqdn

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/awx#2244]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
hosts

##### SUMMARY
Connecting to remote windows host via IP result in an winrm error. 

##### ENVIRONMENT
* AWX version: ?
* AWX install method: docker on linux
* Ansible version:  2.6.2

##### STEPS TO REPRODUCE

Build several tower inventories with Azure Resource Manager. Added the ansible winrm variables for connection. Same for all. 
winrm_host variable shows public IP for all hosts which succeed. I have one host which fails when using public IP.

##### EXPECTED RESULTS

Connection success.

##### ACTUAL RESULTS

Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/setup.ps1 
<publicip> ESTABLISH WINRM CONNECTION FOR USER: testuser on PORT 5986 TO publicip
checking if winrm_host publicip is an IPv6 address 
<publicip> WINRM CONNECT: transport=ssl endpoint=https://publicip:5986/wsman 
<publicip> WINRM CONNECTION ERROR: ("bad handshake: SysCallError(104, 'ECONNRESET')",)

##### ADDITIONAL INFORMATION

When running manually with fqdn insteaf of public ip the connection succeeds. The other hosts have no problem with public IPs. I also ran the ansible winrm powershell script with -forcenewsslcert

**Comment by nicolaibaralmueller** [comment]
I've also testet the connection with powershell like this: 

> $test = New-PsSessionOption –SkipCACheck -SkipCNCheck
Enter-PSSession -ComputerName $ip -Credential $user -UseSSL -SessionOption $test

> $test = New-PsSessionOption –SkipCACheck -SkipCNCheck
Enter-PSSession -ComputerName $fqdn -Credential $user -UseSSL -SessionOption $test

Both types are working fine with powershell.

**Comment by nicolaibaralmueller** [comment]
Also tried building a inventory without tower and running a fact playbook against the host:

> Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/windows/setup.ps1
<publicip> ESTABLISH WINRM CONNECTION FOR USER: testuser on PORT 5986 TO publicip
checking if winrm_host publicip is an IPv6 address
fatal: [publicip]: UNREACHABLE! => {
    "changed": false, 
    "msg": "ssl: HTTPSConnectionPool(host='publicip', port=5986): Read timed out. (read timeout=30)", 
    "unreachable": true
}

Via fqdn:

> Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/windows/setup.ps1
<fqdn> ESTABLISH WINRM CONNECTION FOR USER:testuser on PORT 5986 TO fqdn
checking if winrm_host fqdn is an IPv6 address
EXEC (via pipeline wrapper)
ok: [fqdn]

**Comment by nicolaibaralmueller** [comment]
2 out of our 6 hosts have this issue with ansible... not powershell

**Comment by nicolaibaralmueller** [comment]
Anyone?

**Comment by wenottingham** [comment]
If you have issues with Tower, please contact your Red Hat support rep.

I would note that if it behaves the same outside of AWX, it's likely an issue with Ansible regardless, and should be tracked at https://github.com/ansible/ansible/issues/.
