### ISSUE TITLE
Need ldap logs

### ISSUE THREAD

**Issue by MarcusCaepio** [ansible/awx#2246]
I try to setup ldap login, but it does not work with my AD user and I don't know why. Where can I find the ldap logs to see what's wrong?

**Comment by Testicule** [comment]
You can't Markus. You can't.
There are none.
Well, there are, but they're not necessarily going to be very useful.
If you use "docker logs --follow" to dump the awx_web logs to a file, and then "tail -f" the file, you may see a few django errors relating to ldap, so try this, and good luck. 

You'll need it, i'm sorry to say:
docker logs --follow awx_web_container_id > /tmp/awx/logs/awx_web.log 2>&1 &
tail -n 100 -f /tmp/awx/logs/awx_web.log
