### ISSUE TITLE
AWX Very Poor Performance! 

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/awx#2249]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
AWX performance very poor

##### ENVIRONMENT
* AWX version: 1.0.7
* AWX install method: docker on linux
* Ansible version: 2.6.3
* Web Browser: Chrome, Firefox

##### STEPS TO REPRODUCE

We have roughly 30 templates, 60 inventories, 30 credentials. 

##### EXPECTED RESULTS

Normal web interface performance

##### ACTUAL RESULTS

The container needs be restartet every day in order to have somewhat ok performance. 
When job history exceeds about 50 the web interface performance is very poor, meaning that we are unable to enter job specific results. Just nothing happens. This was tried on several browsers. Reboot fixes this.
Also, the job output console hangs or shows output from other jobs until the job page is reloaded.

**Comment by jakemcdermott** [comment]
Hey nicolaibaralmueller,

Thanks for filing this issue.

Performance for this view has been significantly improved downstream. These changes will hopefully be landing in awx shortly. Thanks for your patience!
