### ISSUE TITLE
How to run AWX with SSL ?

### ISSUE THREAD

**Issue by MarcusCaepio** [ansible/awx#2250]
As soon as you define LDAP auth, the access should be over https.
How do I run AWX with with SSL in this huge black cloud construct of docker containers?

Thanks in advance

**Comment by MarcusCaepio** [comment]
For everyone, who also needs this:
https://www.youtube.com/watch?v=Ulrr9knCc_w

**Comment by egroeper** [comment]
Since awx 5.0.0 SSL is supported, if you build the containers by yourself. See #3983.

**Comment by Aech1977** [comment]
That video is kinda old and makes some assumptions (like your docker container is not read only).
