### ISSUE TITLE
Create Users w/ AWX REST API

### ISSUE THREAD

**Issue by phermann1988** [ansible/awx#2251]
i successfully uploaded with the REST API servers to AWX via POST Request.
[http://127.123.45.67:15080/api/v2/hosts/

credendtials as basic auth

body raw as JSON (application/json)

{ "name" : "hostname.fqdn.net",

"inventory" : 2 } ....]

now, i want to add users vi the API.

Required fileds are (https://docs.ansible.com/ansible-tower/latest/html/towerapi/users.html -> the tower/awx documentation isn't that good or well updated i know..)

{

"username" : "USERNAME0815",

"first_name" : "tom",

"last_name" : "tester",

"email" : "tom@tester.com",

"is_superuser": false,

"is_system_auditor": false,

"password": ""

}

i tried it w/ a lot of other combinations but all i get as a response is the same thing when i perform a GET operations to:

http://127.123.45.67:15080/api/v2/hosts..

No users are created and i get no error code or sth back from the API :-(

i checked the logs of the web container, it's really strange that I don't get an error :-(

working POST -> hosts

2018-09-14 13:21:38,424 INFO awx.api.authentication User admin performed a POST to /api/v2/hosts/ through the API

[pid: 138|app: 0|req: 241/1821] 172.17.0.1 () {50 vars in 888 bytes} [Fri Sep 14 13:21:38 2018] POST /api/v2/hosts/ => generated 1833 bytes in 252 msecs (HTTP/1.1 201) 9 headers in 264 bytes (1 switches on core 0)

172.17.0.1 - admin [14/Sep/2018:13:21:38 +0000] "POST /api/v2/hosts/ HTTP/1.1" 201 1833 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36" "-"

RESULT 2

OKREADY

not working POST -> users

172.17.0.1 - admin [14/Sep/2018:13:19:33 +0000] "POST /api/v2/users HTTP/1.1" 301 0 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36" "-"

[pid: 135|app: 0|req: 604/1819] 172.17.0.1 () {50 vars in 888 bytes} [Fri Sep 14 13:19:33 2018] POST /api/v2/users => generated 0 bytes in 34 msecs (HTTP/1.1 301) 6 headers in 198 bytes (1 switches on core 0)

2018-09-14 13:19:34,094 INFO awx.api.authentication User admin performed a GET to /api/v2/users/ through the API

[pid: 135|app: 0|req: 605/1820] 172.17.0.1 () {44 vars in 741 bytes} [Fri Sep 14 13:19:33 2018] GET /api/v2/users/ => generated 1765 bytes in 173 msecs (HTTP/1.1 200) 8 headers in 230 bytes (1 switches on core 0)

172.17.0.1 - admin [14/Sep/2018:13:19:34 +0000] "GET /api/v2/users/ HTTP/1.1" 200 1765 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36" "-"

RESULT 2

OKREADY

**Comment by wenottingham** [comment]
You need a trailing '/ ' on your POST.

**Comment by phermann1988** [comment]
brilliant, thank you!!!

**Comment by shyimo** [comment]
@walkafwalka from what i understand, trailing slack at the end in REST Api should be ignore.. very strange that we need to had this to POST requests :)

**Comment by walkafwalka** [comment]
@shyimo I have no idea why I was referenced.
