### ISSUE TITLE
Feature: Workflow Convergence Node

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#2254]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
* Have a convergence step that tracks the completion of multiple workflow jobs before continuing

**Comment by ghost** [comment]
+1

**Comment by csmartins** [comment]
+1

**Comment by kdelee** [comment]
I'm going to be back up for @jladdjr on testing for this feature

**Comment by chrismeyersfsu** [comment]
People of the internet who want this feature. Can you help me out and give me a concrete example as to your use case/need for this feature?

**Comment by jladdjr** [comment]
@kdelee - with the feature merged / tests merged seems like we can close this out, what do you think?
