### ISSUE TITLE
Feature: Workflow level Inventory

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#2256]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
* Set an inventory for a workflow that will then be used by every Job Template in that workflow.

##### ADDITIONAL INFORMATION
Needed to complete workflow callbacks https://github.com/ansible/awx/issues/1845

**Comment by mabashian** [comment]
@chrismeyersfsu As far as UI changes here - would this simply require the UI to add an optional inventory field to the workflow form?

**Comment by sumkincpp** [comment]
Would be great to have named InventoryType variable specified on workflow run (i.e. variables like InventoryHosts for HOSTS inventory and InventoryServices for SERVICES inventory) which can be used in template nodes. 
For example, for certain template node by default it will use inventory A(or disabled to run without inventory) or implicitly passed inventory value of variable InventoryHosts.

**Comment by kdelee** [comment]
@AlanCoding I hear that you will be working on this. I've signed up to be the primary test owner for this feature. Let me know when you start thinking about working on it!

**Comment by AlanCoding** [comment]
done
