### ISSUE TITLE
Wrong message displayed momentarily when deleting an organization

### ISSUE THREAD

**Issue by one-t** [ansible/awx#2257]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Intermittently, if you attempt to delete an org without objects after attempting to delete one with objects, the wrong message will be displayed momentarily before the correct one loads.

##### STEPS TO REPRODUCE

* Attempt to delete an organization without objects; observe warning message
* Attempt to delete an organization with objects; observe warning message

##### EXPECTED RESULTS

Appropriate error messages for each deletion

##### ACTUAL RESULTS

Previous message displayed momentarily before the correct one is rendered

![image](https://user-images.githubusercontent.com/28987580/45575382-28f2bf00-b828-11e8-96c6-db44c8d195a8.png)

##### ADDITIONAL INFORMATION

Split off of ansible/tower#689

**Comment by unlikelyzero** [comment]
Let's see if this has been fixed

**Comment by one-t** [comment]
Closed- old UI.

**Comment by unlikelyzero** [comment]
@one-t we have the same patterns to follow and have used these issues to help discover feature parity. I believe this is related to the feature work being worked on this sprint, but cannot be sure without checking

**Comment by tiagodread** [comment]
Closing this as a duple of https://github.com/ansible/awx/issues/5546 current work related to this.
