### ISSUE TITLE
postgres will not activate

### ISSUE THREAD

**Issue by JR1994** [ansible/awx#2258]
I am trying to install AWX via docker in an Ubuntu 18.04 lxc container. When I run the install script I get this error. Trying to understand what I am missing.

Thanks!

-----
TASK [local_docker : Set DockerHub Image Paths] ********************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [local_docker : Activate postgres container] ******************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error starting container f7f0d1111594aec590f206fa96137557b41f8a7cde83dbe9d6f42835eaaeb19c: 400 Client Error: Bad Request (\"{\"message\":\"OCI runtime create failed: container_linux.go:348: starting container process caused \\\"process_linux.go:402: container init caused \\\\\\\"rootfs_linux.go:58: mounting \\\\\\\\\\\\\\\"proc\\\\\\\\\\\\\\\" to rootfs \\\\\\\\\\\\\\\"/var/lib/docker/overlay2/1f49d15fe7c73fde6a29975f82091454e8c5a55c67bee239c567237f8e147a81/merged\\\\\\\\\\\\\\\" at \\\\\\\\\\\\\\\"/proc\\\\\\\\\\\\\\\" caused \\\\\\\\\\\\\\\"permission denied\\\\\\\\\\\\\\\"\\\\\\\"\\\": unknown\"}\")"}
	to retry, use: --limit @/tmp/awx/installer/install.retry

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1   

root@ubuntu-awx:/tmp/awx/installer# 
----

**Comment by shanemcd** [comment]
Hi! Thanks for trying AWX. Given the amount of traffic in this repo, we have to be pretty strict about only tracking bugs here.

This issue seems related to your environment, perhaps due to running a privileged Docker inside of LXC. I have never tried this so I won't be much help.

For troubleshooting and exploration, come hang out in #ansible-awx on [freenode](https://webchat.freenode.net), or send an email out to the [AWX mailing list](https://groups.google.com/forum/#!forum/awx-project).
