### ISSUE TITLE
All user visible to organisation admin not working

### ISSUE THREAD

**Issue by NiveditaKumari14** [ansible/awx#2259]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
I created organisation red and blue and created admin, normal user and system auditor in both the organisation.
I planned to check the option "All user visible to organisation admin" in the Settings option under System.
I turned OFF this, I loggedIn with organisation blue admin and what i understand it should not allow the admin to control the users and teams of other organisation, but this is not happening.

Please let me know, if i am right here or i missing something.

##### ENVIRONMENT
* AWX version: 1.0.7.2
* AWX install method:  docker on linux
* Ansible version: 2.6.2
* Web Browser:

##### STEPS TO REPRODUCE

Create 2 organisation and create admin and normal users in both of them
Goto settings under system tab turn off the option "All users visible to organisation admin".

##### EXPECTED RESULTS
Admin of one team should be able access users and team of other organisation

##### ACTUAL RESULTS

Admin is able to access all users and team.

**Comment by NiveditaKumari14** [comment]
let suppose i created  a normal user and made it a organisation admin, then when i logged in with that credential then it will only show the details of that organisation only, in-spite of regarding weather i set All user visible to organisation admin OFF or ON

**Comment by AlanCoding** [comment]
I cannot reproduce this, but perhaps there is some confusion about functionality.

I created a new organization, and a new user as admin of that organization. As the system admin, I can see 35 users in my particular system, and as this new user I can see 17 users.

There is a provision in our permissions logic to allow all users to see any users who are system administrators. In my case, I had 17 users made system administrators and the rest, who are not system admins, were hidden from the org admin when the setting was turned off. Perhaps your system has a similar issue where many of your users are system admins.

If you could find any information that contradicts these expectations then we will keep this open, but right now I don't see any bugs.

Also keep in mind that the ability to view a user does not imply any permissions to manage that user.

**Comment by matburt** [comment]
No follow up in a week, let us know if you see this again.

**Comment by zabandija123** [comment]
> No follow up in a week, let us know if you see this again.

I ran into the same issue with Tower  3.5.2-1, I'm unsure if it would be reported here.
In my case, any organization member, whether it is an admin or not, can see all the system administrators and system auditors when listing organization's users, having the setting OFF. 
Please let me know if you need further information or log detail.

**Comment by AlanCoding** [comment]
> In my case, any organization member, whether it is an admin or not, can see all the system administrators and system auditors when listing organization's users, having the setting OFF.

What setting are you talking about? I know of this setting:

https://github.com/ansible/awx/blob/fd027f87a908fe6f624424dffc89f2e61896d27a/awx/main/conf.py#L38

That is not related to what you are doing. We allow ordinary users to see system admins and auditors

https://github.com/ansible/awx/blob/fd027f87a908fe6f624424dffc89f2e61896d27a/awx/main/access.py#L583-L592

and it is expected that you cannot turn that off.
