### ISSUE TITLE
Different Server for AWX and ansible?

### ISSUE THREAD

**Issue by dreamylch** [ansible/awx#2263]
I would like to install AWX on a different server with the one that Ansible is installed and playbooks are run due to security issue. Is it possible? I have done some googling and can't find what I need. Thanks in advance.

**Comment by shanemcd** [comment]
Hi! Thanks for trying AWX. Given the amount of traffic in this repo, we have to be pretty strict about only tracking issues here.

For troubleshooting and exploration, come hang out in #ansible-awx on freenode, or send an email out to the [AWX mailing list](https://groups.google.com/forum/#!forum/awx-project)
