### ISSUE TITLE
Feature Request: Show Custom Virtual Environment used in job details

### ISSUE THREAD

**Issue by grahamn-gr** [ansible/awx#2264]
##### ISSUE TYPE
- Feature

##### COMPONENT NAME
 - UI

##### SUMMARY
When running a job and if using a custom virtual environment display it in the job details

**Comment by wenottingham** [comment]
This isn't directly recorded in the job record currently, so it's not a trivial UI addition.

**Comment by ryanpetrello** [comment]
@mabashian is this done/merged/ready to be closed?

**Comment by ryanpetrello** [comment]
@grahamn-gr we've implemented this as of awx 4.0.0:

![image](https://user-images.githubusercontent.com/214912/55569004-c9c6a000-56ce-11e9-92c8-687ae284e1d8.png)
