### ISSUE TITLE
Ability to get inventory scripts from Source control

### ISSUE THREAD

**Issue by cg-cnu** [ansible/awx#2268]
##### ISSUE TYPE
 - Feature Idea

Have a mechanism to get inventory scripts from source control instead of adding it in the UI.

##### SUMMARY

Currently inventory scripts are added in the UI input box, disconnected from the source control.
When ever the script changes we have to manually copy the code and update the inventory script. 
It would be very helpful if we have the ability to connect the inventory scripts to a version control like git and pull the changes before running it.

Thanks! :slightly_smiling_face:

**Comment by AlanCoding** [comment]
You can do this by adding an inventory source and selecting the option to source from a project. Then either select or paste in the relative path of the script inside of your project.

**Comment by cg-cnu** [comment]
Hey @AlanCoding 
I didn't exactly got what you meant by 
> Then either select or paste in the relative path of the script inside of your project.

Can you explain a bit more or point me to the respective topic in the documentation. Thanks!

**Comment by AlanCoding** [comment]
current docs: https://docs.ansible.com/ansible-tower/latest/html/administration/scm-inv-source.html

**Comment by cg-cnu** [comment]
Thanks for the link. After much debugging I realized that awx only recognizes the files which are executable, from [awx source](https://github.com/ansible/awx/blob/d8c4f118c23fde9f59f38334974381264d22f120/awx/main/utils/ansible.py#L69). I just added the file in the git and hoping it to show up in awx interface. :man_facepalming: 
Just in case someone face a similar issue, make sure your scripts are executable for awx to recognize. 

Thanks for your time @AlanCoding :slightly_smiling_face:

**Comment by L1ghtman2k** [comment]
I am not sure what I am doing wrong...
I have "inventory" file located in the root of the project located in github.
After updating the project, and updating it on awx, I am getting this error:

```
    1.896 INFO     Updating inventory 3: Lockdown
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==3.0.1.0', 'console_scripts', 'awx-manage')()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 140, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1049, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 947, in handle
    source = self.get_source_absolute_path(self.source)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 311, in get_source_absolute_path
    raise IOError('Source does not exist: %s' % source)
OSError: Source does not exist: /var/lib/awx/projects/_10__cse365_git/inventory
```

This is the inventory file:

```
#!/usr/bin/env python
import os
import sys
import argparse

try:
    import json
except ImportError:
    import simplejson as json


class Inventory(object):

    def __init__(self):
        self.inventory = {}
        self.read_cli_args()

        # Called with `--list`.
        if self.args.list:
            self.inventory = self.enventory_generator()
        # Called with `--host [hostname]`.
        elif self.args.host:
            # Not implemented, since we return _meta info `--list`.
            self.inventory = self.empty_inventory()
        # If no groups or vars are present, return empty inventory.
        else:
            self.inventory = self.empty_inventory()

        print(json.dumps(self.inventory))

    def enventory_generator(self):
    // DATA, THIS WORKS, and I HAVE ALREADY TESTED IT
    # Empty inventory for testing.
    def empty_inventory(self):
        return {'_meta': {'hostvars': {}}}

    # Read the command line args passed to the script.
    def read_cli_args(self):
        parser = argparse.ArgumentParser()
        parser.add_argument('--list', action='store_true')
        parser.add_argument('--host', action='store')
        self.args = parser.parse_args()

Inventory()
```

I knoe @cg-cnu mentioned it should be executable. Would that mean I have to go into awx docker and set chmod +x ?

**Comment by AlanCoding** [comment]
> Would that mean I have to go into awx docker and set chmod +x ?

No, if you're using git, `chmod +x` should change the file in a way that you can commit that change to source control. Then a project update should pick up the executable bit.

It's best to test your file locally by running `./inventory` from the root of your project directory.

**Comment by L1ghtman2k** [comment]
Thanks! it worked!
