### ISSUE TITLE
How to use awx_user_email to email the initiator of a job?

### ISSUE THREAD

**Issue by AndreasDavour** [ansible/awx#2269]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

I would like to be able to email the initiator of a job that it finished, not just the hard coded recipients in a notification template.

**Comment by wenottingham** [comment]
This is covered in https://github.com/ansible/awx/issues/79.

In the meantime, you could write a playbook task that uses `awx_user_email`.
