### ISSUE TITLE
Project update get an import error (ImportError: cannot import name cleanup)

### ISSUE THREAD

**Issue by iTraceur** [ansible/awx#2276]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Project update

##### SUMMARY
I was executing project update job, and the output got an import error (ImportError: cannot import name cleanup).

##### ENVIRONMENT
* AWX version: 1.0.8
* AWX install method: native on linux
* Ansible version:  2.6.4
* Operating System: Linux

##### STEPS TO REPRODUCE

Can't find a way

##### EXPECTED RESULTS

Job should success

##### ACTUAL RESULTS

Still got error

##### ADDITIONAL INFORMATION

Output:
```
ansible-playbook 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/awx/venv/awx/lib/python2.7/site-packages/ansible
  executable location = /home/awx/venv/awx/bin/ansible-playbook
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /etc/ansible/ansible.cfg as config file
Parsed localhost, inventory source with host_list plugin
ERROR! Unexpected Exception, this is probably a bug: cannot import name cleanup
the full traceback was:

Traceback (most recent call last):
  File "/home/awx/venv/awx/bin/ansible-playbook", line 118, in <module>
    exit_code = cli.run()
  File "/home/awx/venv/awx/lib/python2.7/site-packages/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/home/awx/venv/awx/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 89, in run
    self._tqm.load_callbacks()
  File "/home/awx/venv/awx/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 182, in load_callbacks
    self._stdout_callback = callback_loader.get(self._stdout_callback)
  File "/home/awx/venv/awx/lib/python2.7/site-packages/ansible/plugins/loader.py", line 378, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/home/awx/venv/awx/lib/python2.7/site-packages/ansible/plugins/loader.py", line 357, in _load_module_source
    module = imp.load_source(full_name, path, module_file)
  File "/home/awx/venv/awx/lib/python2.7/site-packages/awx-1.0.8-py2.7.egg/awx/plugins/callback/awx_display.py", line 30, in <module>
    from awx_display_callback import AWXDefaultCallbackModule as CallbackModule  # noqa
  File "/home/awx/venv/awx/lib/python2.7/site-packages/awx-1.0.8-py2.7.egg/awx/lib/awx_display_callback/__init__.py", line 21, in <module>
    from . import cleanup  # noqa (registers control persistent cleanup)
ImportError: cannot import name cleanup
```

Job api detail:
`{
    "id": 1,
    "type": "project_update",
    "url": "/api/v2/project_updates/1/",
    "related": {
        "created_by": "/api/v2/users/1/",
        "unified_job_template": "/api/v2/projects/4/",
        "stdout": "/api/v2/project_updates/1/stdout/",
        "project": "/api/v2/projects/4/",
        "cancel": "/api/v2/project_updates/1/cancel/",
        "notifications": "/api/v2/project_updates/1/notifications/",
        "scm_inventory_updates": "/api/v2/project_updates/1/scm_inventory_updates/",
        "events": "/api/v2/project_updates/1/events/"
    },
    "summary_fields": {
        "instance_group": {
            "id": 2,
            "name": "tower"
        },
        "unified_job_template": {
            "id": 4,
            "name": "Demo Project",
            "description": "",
            "unified_job_type": "project_update"
        },
        "project": {
            "id": 4,
            "name": "Demo Project",
            "description": "",
            "status": "failed",
            "scm_type": "git"
        },
        "created_by": {
            "id": 1,
            "username": "admin",
            "first_name": "",
            "last_name": ""
        },
        "user_capabilities": {
            "start": true,
            "delete": true
        }
    },
    "created": "2018-09-19T14:20:30.897988Z",
    "modified": "2018-09-19T14:45:41.116566Z",
    "name": "Demo Project",
    "description": "",
    "local_path": "_4__demo_project",
    "scm_type": "git",
    "scm_url": "https://github.com/ansible/ansible-tower-samples",
    "scm_branch": "",
    "scm_clean": false,
    "scm_delete_on_update": false,
    "credential": null,
    "timeout": 0,
    "unified_job_template": 4,
    "launch_type": "manual",
    "status": "failed",
    "failed": true,
    "started": "2018-09-19T14:45:41.269848Z",
    "finished": "2018-09-19T14:45:42.916423Z",
    "elapsed": 1.647,
    "job_args": "[\"ansible-playbook\", \"-i\", \"localhost,\", \"-vvv\", \"-e\", \"@/tmp/awx_1_JcSSI0/tmpX3LIfg\", \"project_update.yml\"]",
    "job_cwd": "/home/awx/venv/awx/lib/python2.7/site-packages/awx-1.0.8-py2.7.egg/awx/playbooks",
    "job_env": {
        "TMP": "/tmp",
        "ANSIBLE_BECOME_ASK_PASS": "False",
        "ANSIBLE_PARAMIKO_RECORD_HOST_KEYS": "False",
        "AWX_PRIVATE_DATA_DIR": "/tmp/awx_1_JcSSI0",
        "LC_CTYPE": "en_US.UTF-8",
        "_MP_FORK_LOGFILE_": "",
        "ANSIBLE_ASK_PASS": "False",
        "CELERY_LOG_REDIRECT": "1",
        "SUPERVISOR_GROUP_NAME": "awx",
        "PATH": "/home/awx/venv/awx/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin",
        "HOME": "/var/lib/awx",
        "DISPLAY": "",
        "ANSIBLE_CALLBACK_PLUGINS": "/home/awx/venv/awx/lib/python2.7/site-packages/awx-1.0.8-py2.7.egg/awx/plugins/callback",
        "LANG": "en_US.UTF-8",
        "VIRTUAL_ENV": "/home/awx/venv/awx",
        "SUPERVISOR_SERVER_URL": "unix:///var/run/supervisor/supervisor.sock",
        "TZ": "UTC",
        "ANSIBLE_RETRY_FILES_ENABLED": "False",
        "LANGUAGE": "en_US.UTF-8",
        "_MP_FORK_LOGFORMAT_": "[%(asctime)s: %(levelname)s/%(processName)s] %(message)s",
        "AWX_SETTINGS_FILE": "/etc/awx/settings.py",
        "SUPERVISOR_ENABLED": "1",
        "CELERY_LOG_FILE": "",
        "DJANGO_PROJECT_DIR": "/home/awx/venv/awx/lib/python2.7/site-packages/awx-1.0.8-py2.7.egg",
        "CACHE": "redis://192.168.8.64:6379/4",
        "ANSIBLE_HOST_KEY_CHECKING": "False",
        "DJANGO_LIVE_TEST_SERVER_ADDRESS": "localhost:9013-9199",
        "ANSIBLE_STDOUT_CALLBACK": "awx_display",
        "PYTHONPATH": "/home/awx/venv/awx/lib/python2.7/site-packages:/home/awx/venv/awx/lib/python2.7/site-packages/awx-1.0.8-py2.7.egg/awx/lib:",
        "CELERY_LOADER": "djcelery.loaders.DjangoLoader",
        "_MP_FORK_LOGLEVEL_": "10",
        "LC_ALL": "en_US.UTF-8",
        "ANSIBLE_FORCE_COLOR": "True",
        "CELERY_LOG_REDIRECT_LEVEL": "WARNING",
        "SUPERVISOR_PROCESS_NAME": "celery",
        "CELERY_LOG_LEVEL": "10",
        "PROJECT_UPDATE_ID": "1",
        "DJANGO_SETTINGS_MODULE": "awx.settings.production",
        "ANSIBLE_VENV_PATH": "/home/awx/venv/awx"
    },
    "job_explanation": "",
    "execution_node": "bogon",
    "result_traceback": "",
    "event_processing_finished": true,
    "project": 4,
    "job_type": "check",
    "host_status_counts": {},
    "playbook_counts": {
        "play_count": 0,
        "task_count": 0
    }
}
`

**Comment by ghjm** [comment]
Hey @iTraceur - is there any chance you could send me a snapshot or clone or Vagrant box or something like that of the system experiencing this error?

**Comment by ryanpetrello** [comment]
@iTraceur another thing you might try that would give us additional debugging data is visiting:

`/api/v2/settings/jobs/`

...and setting:

![image](https://user-images.githubusercontent.com/214912/45836692-8630b980-bcdb-11e8-93c6-1a728bb7f02e.png)

...and relaunching the failing job again.

**Comment by ryanpetrello** [comment]
@iTraceur we have been able to reproduce this in environments where `enum==0.4.6` was installed in the global Python site-packages due to _this_ bug/issue:

https://github.com/pyca/cryptography/issues/4010

Forcibly uninstalling the stray `enum` fixed the issue for us.  I suspect that your:

> AWX install method: native on linux

...has contributed to this in some way.

**Comment by matburt** [comment]
also, to be clear on this:

`AWX install method: native on linux`

is unsupported by us.

**Comment by iTraceur** [comment]
@ghjm @ryanpetrello I found my mistake and fixed this issue. because I tried to change the CACHE settings from "django.core.cache.backends.memcached.MemcachedCache" backend to "django_redis.cache.RedisCache" backend, and when I changed back it turned to working well.

**Comment by ryanpetrello** [comment]
@iTraceur yea, the usage of memcached is intentional - don't do that 😄
