### ISSUE TITLE
Using external Postgresql results in some migrations fail

### ISSUE THREAD

**Issue by ghost** [ansible/awx#2278]
##### ISSUE TYPE
 - Bug Report
##### COMPONENT NAME

 - Installer
##### SUMMARY

When using external PostgreSQL awx_web container seems to have some issues while applying migrations on first run. 
##### ENVIRONMENT
* AWX version: (Can't determine) VERSION file is empty. make VERSION fails with error: unknown option `first-parent'. Actual clone of repo.
* AWX install method: docker-compose on linux
* Ansible version: 2.6.4
* Operating System: CentOS 7.5
##### STEPS TO REPRODUCE
Set up an external PostgreSQL 10 database. Set up inventory. Run `ansible-playbook -i inventory install.yml`

##### EXPECTED RESULTS
Working awx deployment. 

##### ACTUAL RESULTS
AWX web interface seems to remain "silent". Error in migrations in `awx_web_1` container.

##### ADDITIONAL INFORMATION
`docker logs awx_web_1`

> WSGI app 0 (mountpoint='') ready in 13 seconds on interpreter 0x14e28d0 pid: 136 (default app)
> 2018-09-19 09:35:06,643 WARNING  awx.conf.settings Database settings are not available, using defaults, error:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 80, in <module>
>     application = get_wsgi_application()
>   File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 77, in get_wsgi_application
>     return AWXWSGIHandler()
>   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 151, in __init__
>     self.load_middleware()
>   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 56, in load_middleware
>     mw_class = import_string(middleware_path)
>   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_string
>     module = import_module(module_path)
>   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/usr/lib/python2.7/site-packages/awx/sso/middleware.py", line 18, in <module>
>     from social_django import utils
>   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/utils.py", line 13, in <module>
>     BACKENDS = settings.AUTHENTICATION_BACKENDS
>   File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 531, in __getattr_without_cache__
>     return getattr(self._wrapped, name)
>   File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 444, in __getattr__
>     value = self._get_local(name)
>   File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 361, in _get_local
>     self._preload_cache()
>   File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 323, in _preload_cache
>     for setting in Setting.objects.filter(key__in=settings_to_cache.keys(), user__isnull=True).order_by('pk'):
>   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
>     self._fetch_all()
>   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
>     self._result_cache = list(self._iterable_class(self))
>   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
>     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
>   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
>     raise original_exception
> ProgrammingError: relation "conf_setting" does not exist
> LINE 1: ...f_setting"."value", "conf_setting"."user_id" FROM "conf_sett...
> 

`inventory`

```
localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python"
 
[all:vars]
 
# Remove these lines if you want to run a local image build
# Otherwise the setup playbook will install the official Ansible images. Versions may
# be selected based on: latest, 1, 1.0, 1.0.0, 1.0.0.123
# by default the base will be used to search for ansible/awx_web and ansible/awx_task
dockerhub_base=ansible
dockerhub_version=latest

# Openshift Install
# Will need to set -e openshift_password=developer -e docker_registry_password=$(oc whoami -t)
# openshift_host=127.0.0.1:8443
# openshift_project=awx
# openshift_user=developer
# openshift_skip_tls_verify=False
# openshift_pg_emptydir=True

# Kubernetes Install
# kubernetes_context=test-cluster
# kubernetes_namespace=awx
# tiller_namespace=kube-system

# Kubernetes and Openshift Install Resource Requests
# This is the request value for a pod's "task" container, which is the container
# used to run jobs. The other containers have a fixed resource request. The total amount
# of requested resources for a pod is the sum of all resources requested by all containers
# in the pod
# A cpu_request of 1500 is 1.5 cores for the task container
# A mem_request of 2 is for 2 gigabytes of memory for the task container
# task_cpu_request=1500
# task_mem_request=2

# Common Docker parameters
postgres_data_dir=/tmp/pgdocker
host_port=80

# Docker Compose Install
use_docker_compose=true
# The docker_compose.yml file will be created in this directory
# The name of the directory (here "awx") will be the prefix of the docker containers
docker_compose_dir=/var/lib/awx

# Required for Openshift when building the image on your own
# Optional for Openshift if using Dockerhub or another prebuilt registry
# Required for Standalone Docker Install if building the image on your own
# Optional for Standalone Docker Install if using Dockerhub or another prebuilt registry
# Required for Docker Compose Install if building the image on your own
# Optional for Docker Compose Install if using Dockerhub or another prebuilt registry
# Define if you want the image pushed to a registry. The container definition will also use these images
# docker_registry=172.30.1.1:5000
# docker_registry_repository=awx
# docker_registry_username=developer

# Docker_image will not attempt to push to remote if the image already exists locally
# Set this to true to delete images from docker on the build host so that they are pushed to the remote repository
# docker_remove_local_images=False

# Set pg_hostname if you have an external postgres server, otherwise
# a new postgres service will be created
pg_hostname=192.168.10.103
pg_username=<SOMEUSER>
pg_password=<SOMEPASSWORD>
pg_database=<SOMEDB>
pg_port=5432

# Use a local distribution build container image for building the AWX package
# This is helpful if you don't want to bother installing the build-time dependencies as
# it is taken care of already.
# NOTE: IMPORTANT: If you are running a mininshift install, using this container might not work
#                  if you are using certain drivers like KVM where the source tree can't be mapped
#                  into the build container.
#                  Thus this setting must be set to False which will trigger a local build. To view the
#                  typical dependencies that you might need to install see:
#                  installer/image_build/files/Dockerfile.sdist
#use_container_for_build=true

# This will create or update a default admin (superuser) account in AWX, if not provided
# then these default values are used
default_admin_user=unb0rn
# default_admin_password=password

# AWX Secret key
# It's *very* important that this stay the same between upgrades or you will lose the ability to decrypt
# your credentials
secret_key=<%SOMESECRET>

# Build AWX with official logos
# Requires cloning awx-logos repo into the project root.
# Review the trademark guidelines at https://github.com/ansible/awx-logos/blob/master/TRADEMARKS.md
awx_official=true

# Proxy
#http_proxy=http://proxy:3128
#https_proxy=http://proxy:3128
#no_proxy=mycorp.org

# Container networking configuration
# Set the awx_task and awx_web containers' search domain(s)
#awx_container_search_domains=example.com,ansible.com
# Alternate DNS servers
#awx_alternate_dns_servers="10.1.2.3,10.2.3.4"

# AWX project data folder. If you need access to the location where AWX stores the projects
# it manages from the docker host, you can set this to turn it into a volume for the container.
project_data_dir=/var/lib/awx/projects
 
# CA Trust directory. If you need to provide custom CA certificates, supplying
# this variable causes this directory on the host to be bind mounted over
# /etc/pki/ca-trust in the awx_task and awx_web containers.
# NOTE: only obeyed in local_docker install
#ca_trust_dir=/etc/pki/ca-trust
```

**Comment by matburt** [comment]
This is normal, if you look at the other container it is running the install and applying migrations. The web container will proceed once it is done.
