### ISSUE TITLE
high cpu load (3.5) with linux on docker with fresh install

### ISSUE THREAD

**Issue by phospi** [ansible/awx#2280]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
unknown component, docker environment

##### SUMMARY
I installed awx with docker as described in the installation manual. 

##### ENVIRONMENT
* AWX version: 1.0.7.2
* AWX install method:  docker on linux
* Ansible version: 2.6.2
* Operating System: RHEL 7.5
* Web Browser: irrelevant

##### STEPS TO REPRODUCE

I installed awx with docker as described in the installation manual. Nothing more. This is a fresh install of awx linux on docker with version 1.0.7.

wget https://github.com/ansible/awx/archive/1.0.7.zip
unzip 1.0.7.zip
edit inventory file as attached
ansible-playbook -i inventory install.yml
after that login screen of awx is available and cpu usage rises

##### EXPECTED RESULTS

I expect the docker containers to run without generating a linux cpu load of 3+.

##### ACTUAL RESULTS

There are three python processes that are spawned every second and every process generates a cpu load about 95%.

##### ADDITIONAL INFORMATION

[20180919_awx_inventory.txt](https://github.com/ansible/awx/files/2397096/20180919_awx_inventory.txt)

Process Commands:
python /usr/bin/awx-manage runworker --only-channels websocket.*
python /usr/bin/awx-manage run_callback_receiver
python /usr/bin/awx-manage celery beat -l debug --pidfile= -s /var/lib/awx/beat.db
 

docker stats
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
146f810299da        awx_task            1.29%               641.3MiB / 7.631GiB   8.21%               106MB / 133MB       0B / 8.63MB         18
6dd58d2c2b95        awx_web             0.06%               667.8MiB / 7.631GiB   8.55%               5.33MB / 16.1MB     0B / 0B             13
3379099a009d        memcached           0.02%               7.168MiB / 7.631GiB   0.09%               28.2MB / 19.2MB     0B / 0B             10
0d7782c8f420        rabbitmq            1.49%               80.85MiB / 7.631GiB   1.03%               30.4MB / 30.3MB     90.1kB / 55.4MB     94
203f2bd6e549        postgres            0.00%               5.898MiB / 7.631GiB   0.08%               76.7MB / 61.5MB     8.19kB / 1.2GB      8

 

top - 14:02:01 up 20:13,  1 user,  load average: 3.42, 3.50, 3.55
Tasks: 224 total,   4 running, 220 sleeping,   0 stopped,   0 zombie
%Cpu(s): 74.3 us,  4.3 sy,  0.0 ni, 21.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  8001364 total,  1880040 free,  1088352 used,  5032972 buff/cache
KiB Swap:  2097148 total,  2097148 free,        0 used.  6465360 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
18145 awx       20   0  392512  74760   8280 R  94.1  0.9   0:01.80 python
18152 awx       20   0  380528  62788   8276 R  94.1  0.8   0:01.43 python
18153 awx       20   0  380520  62784   8276 R  94.1  0.8   0:01.43 python
 1049 awx       20   0  424588  99384   8688 S   5.9  1.2  14:38.19 daphne
    1 root      20   0   54388   6584   3964 S   0.0  0.1   0:12.36 systemd
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd
    3 root      20   0       0      0      0 S   0.0  0.0   0:14.17 ksoftirqd/0
    5 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:0H
    7 root      rt   0       0      0      0 S   0.0  0.0   0:02.25 migration/0
    8 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcu_bh
    9 root      20   0       0      0      0 S   0.0  0.0   1:31.70 rcu_sched
   10 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 lru-add-drain
   11 root      rt   0       0      0      0 S   0.0  0.0   0:00.23 watchdog/0
   12 root      rt   0       0      0      0 S   0.0  0.0   0:00.19 watchdog/1
   13 root      rt   0       0      0      0 S   0.0  0.0   0:02.00 migration/1
   14 root      20   0       0      0      0 S   0.0  0.0   0:14.05 ksoftirqd/1
   16 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/1:0H
   17 root      rt   0       0      0      0 S   0.0  0.0   0:00.19 watchdog/2
   18 root      rt   0       0      0      0 S   0.0  0.0   0:01.99 migration/2
   19 root      20   0       0      0      0 S   0.0  0.0   0:14.10 ksoftirqd/2
   21 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/2:0H
   22 root      rt   0       0      0      0 S   0.0  0.0   0:00.19 watchdog/3
   23 root      rt   0       0      0      0 S   0.0  0.0   0:02.00 migration/3
   24 root      20   0       0      0      0 S   0.0  0.0   0:14.16 ksoftirqd/3
   26 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/3:0H
   28 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kdevtmpfs
   29 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 netns
   30 root      20   0       0      0      0 S   0.0  0.0   0:00.04 khungtaskd
   31 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 writeback
   32 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kintegrityd
   33 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 bioset
   34 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 bioset
   35 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 bioset
   36 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kblockd
   37 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 md
   38 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 edac-poller
   47 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kswapd0
   48 root      25   5       0      0      0 S   0.0  0.0   0:00.00 ksmd
   49 root      39  19       0      0      0 S   0.0  0.0   0:01.46 khugepaged
   50 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 crypto
   58 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kthrotld
   59 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kmpath_rdacd
   60 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kaluad
   62 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kpsmoused
   64 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 ipv6_addrconf
   77 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 deferwq
  110 root      20   0       0      0      0 S   0.0  0.0   0:00.01 kauditd
  302 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_0
  303 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_0
  304 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 vmw_pvscsi_wq_0
  306 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 ata_sff
  308 root      20   0       0      0      0 S   0.0  0.0   0:00.01 scsi_eh_1
  309 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_1
  311 root      20   0       0      0      0 S   0.0  0.0   0:00.01 scsi_eh_2
  312 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_2
  322 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_3
  323 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_3
  324 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_4
  326 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_4
  328 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_5
  329 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_5
  330 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_6
  331 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_6
  332 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_7
  333 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_7
  334 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_8
  335 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_8
  336 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_9
  337 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_9
  338 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_10
  339 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_10
  340 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_11
  341 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_11
  342 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_12
  343 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_12
  344 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_13
  345 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_13
  346 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_14
  347 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_14
  348 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_15
  349 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_15
  350 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_16
  351 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_16
  352 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_17
  353 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_17
  354 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_18
  355 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_18
  356 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_19
  357 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_19
  358 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_20
  359 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_20
  360 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_21
  361 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_21
  362 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_22
  363 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_22
  364 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_23
  365 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_23
  366 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_24
  367 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_24
  368 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_25
  369 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_25
  370 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_26
  371 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_26
  372 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_27
  373 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_27
  374 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_28
  375 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_28
  376 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_29
  377 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_29
  378 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_30
  379 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_30
  380 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_31
  381 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_31
  382 root      20   0       0      0      0 S   0.0  0.0   0:00.00 scsi_eh_32
  383 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 scsi_tmf_32
  413 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 ttm_swap
  414 root     -51   0       0      0      0 S   0.0  0.0   0:00.00 irq/16-vmwgfx
  446 root       0 -20       0      0      0 S   0.0  0.0   0:00.09 kworker/0:1H
  487 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kdmflush
  488 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 bioset
  498 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kdmflush
  500 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 bioset
  509 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kdmflush
  510 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 bioset
  524 root      20   0       0      0      0 S   0.0  0.0   0:00.02 jbd2/dm-0-8
  525 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 ext4-rsv-conver
  555 root      20   0       0      0      0 S   0.0  0.0   0:00.02 jbd2/dm-2-8
  556 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 ext4-rsv-conver
  607 root      20   0   39476   8592   8196 S   0.0  0.1   0:01.68 systemd-journal
  625 root      20   0  201056   5672   2616 S   0.0  0.1   0:00.02 lvmetad
  696 root       0 -20       0      0      0 S   0.0  0.0   0:00.01 kworker/1:1H
  734 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 bioset
  735 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 xfsalloc
  736 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 xfs_mru_cache
  737 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 xfs-buf/sda1
  738 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 xfs-data/sda1
  739 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 xfs-conv/sda1
  740 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 xfs-cil/sda1
  741 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 xfs-reclaim/sda
  742 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 xfs-log/sda1
  743 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 xfs-eofblocks/s
  744 root      20   0       0      0      0 S   0.0  0.0   0:00.01 xfsaild/sda1
  746 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kdmflush
  749 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kdmflush
  750 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 bioset
  754 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kdmflush
  755 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 bioset
  757 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kdmflush
  758 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 bioset
  789 root      20   0       0      0      0 S   0.0  0.0   0:00.57 jbd2/dm-6-8
  790 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 ext4-rsv-conver
  793 root      20   0       0      0      0 S   0.0  0.0   0:00.00 jbd2/dm-5-8
  794 root      20   0       0      0      0 S   0.0  0.0   0:01.15 jbd2/dm-4-8
  795 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 ext4-rsv-conver
  796 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 ext4-rsv-conver
  798 root      20   0       0      0      0 S   0.0  0.0   0:02.07 jbd2/dm-3-8
  800 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 ext4-rsv-conver
  835 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 rpciod
  836 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 xprtiod
  857 polkitd   20   0  538436  12080   4640 S   0.0  0.2   0:00.19 polkitd
  858 root      20   0   21672   1296    972 S   0.0  0.0   0:02.75 irqbalance
  859 dbus      20   0   66472   2608   1888 S   0.0  0.0   0:01.28 dbus-daemon
  860 rpc       20   0   69220   1056    520 S   0.0  0.0   0:00.06 rpcbind
  862 root      20   0   99656   6064   4460 S   0.0  0.1   0:00.00 VGAuthService
  863 root      20   0   26376   1780   1452 S   0.0  0.0   0:00.63 systemd-logind
  866 root      20   0  224960   6100   4772 S   0.0  0.1   0:30.32 vmtoolsd
  881 ntp       20   0   25720   1980   1396 S   0.0  0.0   0:00.14 ntpd
  888 root      20   0  195080   1240    768 S   0.0  0.0   0:00.00 gssproxy
  907 nrpe      20   0   44876   1536    848 S   0.0  0.0   0:01.23 nrpe
  910 root      20   0  126280   1692   1056 S   0.0  0.0   0:00.51 crond
  932 root      20   0  110088    880    748 S   0.0  0.0   0:00.00 agetty
 1043 root      20   0  221716  12276   1180 S   0.0  0.2   5:26.64 supervisord
 1044 root      20   0  125492   4676   2064 S   0.0  0.1   0:13.71 python
 1046 awx       20   0  167104   7244   4448 S   0.0  0.1   0:01.84 uwsgi
 1059 awx       20   0  438484 108576   8424 S   0.0  1.4   0:02.79 uwsgi
 1060 awx       20   0  438680 108788   8416 S   0.0  1.4   0:02.96 uwsgi
 1061 awx       20   0  437744 107924   8384 S   0.0  1.3   0:02.66 uwsgi
 1062 awx       20   0  438128 108048   8384 S   0.0  1.4   0:02.67 uwsgi
 1063 awx       20   0  437728 108000   8404 S   0.0  1.3   0:02.63 uwsgi
 1068 root       0 -20       0      0      0 S   0.0  0.0   0:00.01 kworker/3:1H
 1265 memcach+  20   0  350232   7996   1224 S   0.0  0.1   0:16.82 memcached
 1270 root      20   0  218504   7828   6904 S   0.0  0.1   0:02.28 rsyslogd
 1275 root      20   0  112808   4276   3248 S   0.0  0.1   0:00.02 sshd
 1276 rabbitmq  20   0 3896228  73928   3996 S   0.0  0.9   3:05.76 beam.smp
 1291 root      20   0  115696    676    516 S   0.0  0.0   0:00.00 rhsmcertd
 1302 root      20   0  107964    576    428 S   0.0  0.0   0:00.00 rhnsd
 1309 postgres  20   0 1064796  44364  43140 S   0.0  0.6   0:12.92 postmaster
 1348 root      20   0  107912   1244    144 S   0.0  0.0   0:00.00 nginx
 1350 nginx     20   0  108560   3860   2224 S   0.0  0.0   0:00.01 nginx
 1352 nginx     20   0  108564   3336   1700 S   0.0  0.0   0:00.01 nginx
 1353 nginx     20   0  108568   3860   2220 S   0.0  0.0   0:00.02 nginx
 1354 nginx     20   0  108564   3340   1624 S   0.0  0.0   0:00.01 nginx
 1540 postgres  20   0  215328   1732    536 S   0.0  0.0   0:00.00 postmaster
 1575 postgres  20   0 1064916  10872   9604 S   0.0  0.1   0:00.67 postmaster
 1576 postgres  20   0 1064796   8036   6812 S   0.0  0.1   0:00.40 postmaster
 1577 postgres  20   0 1064796  18296  17052 S   0.0  0.2   0:04.91 postmaster
 1578 postgres  20   0 1065340   2992   1456 S   0.0  0.0   0:00.67 postmaster
 1579 postgres  20   0  217716   2088    660 S   0.0  0.0   0:05.63 postmaster
 1616 rabbitmq  20   0   11624    340    216 S   0.0  0.0   0:00.34 epmd
 1877 rabbitmq  20   0    4352    536    444 S   0.0  0.0   0:01.17 erl_child_setup
 2073 root       0 -20       0      0      0 S   0.0  0.0   0:00.01 kworker/2:1H
 2250 postgres  20   0 1066004   6412   4296 S   0.0  0.1   0:00.00 postmaster
 2814 rabbitmq  20   0   11588    448    344 S   0.0  0.0   0:00.04 inet_gethost
 2815 rabbitmq  20   0   13712    704    560 S   0.0  0.0   0:00.08 inet_gethost
 3801 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kworker/1:1
 3821 root      20   0       0      0      0 S   0.0  0.0   0:00.01 kworker/0:3
 3868 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kworker/3:1
 3905 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kworker/2:0
 3962 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kworker/u128:0
 7280 root      20   0       0      0      0 S   0.0  0.0   0:00.08 kworker/3:2
 7609 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 bioset
11736 root      20   0       0      0      0 S   0.0  0.0   0:00.27 kworker/0:0
14925 root      20   0       0      0      0 S   0.0  0.0   0:00.05 kworker/1:0
18212 root      20   0  161972   2172   1516 R   0.0  0.0   0:00.02 top
21066 root      20   0   46848   4496   2868 S   0.0  0.1   0:00.06 systemd-udevd
24013 root      20   0  573816  19148   6096 S   0.0  0.2   0:04.50 tuned
26124 root      20   0       0      0      0 S   0.0  0.0   0:06.20 kworker/0:1
32650 root      20   0       0      0      0 S   0.0  0.0   0:00.20 kworker/2:2
35070 root      16  -4   55508    896    492 S   0.0  0.0   0:00.08 auditd
41252 root      20   0       0      0      0 S   0.0  0.0   0:00.45 kworker/u128:1
48148 root      20   0  761812  66992  25168 S   0.0  0.8   1:08.53 dockerd
48161 root      20   0  741816  31416  12552 S   0.0  0.4   0:58.97 docker-containe
59026 root      20   0  154616   5608   4288 S   0.0  0.1   0:00.26 sshd
59082 root      20   0  115516   2144   1680 S   0.0  0.0   0:00.05 bash

**Comment by gamuniz** [comment]
closing due to age of issue, version, and lack of followup
