### ISSUE TITLE
Clicking on a run job link in the 'jobs' WebUI page does nothing using Firefox browser

### ISSUE THREAD

**Issue by pemcg** [ansible/awx#2283]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
In Firefox, if I click on the blue link for a run job on the 'jobs' page to examine the details of a job, nothing happens. I am not taken to the job details, and the 'working...' spinner turns indefinitely. It works fine in Chrome.

##### ENVIRONMENT
* Tower 3.3.0
* AWX install method: VMs (3-node cluster + external PostgreSQL node)
* Ansible version:  2.6.4
* Operating System: RHEL 7.5
* Web Browser: Firefox 52.9.0 (64-bit) Mac

##### STEPS TO REPRODUCE
Login using Firefox for Mac. Navigate to the 'Jobs' side-bar and click the name of a job that's run (the blue link)

##### EXPECTED RESULTS
The job details should be displayed

##### ACTUAL RESULTS
Nothing happens, the 'working...' spinner turns indefinitely

**Comment by ryanpetrello** [comment]
Hey @pemcg,

This issue tracker is used to track issues for the open source awx project. If you are having issues with Ansible Tower, please contact your Red Hat support rep.

**Comment by ryanpetrello** [comment]
If case anybody encounters this, it was encountered on FF 52.9.0, which is EOL as of August 2018.  I was able to reproduce this in awx using FF 52.9.0, and confirmed that it went away when I used a newer Firefox (62.0).
