### ISSUE TITLE
RFE: Add Export and Import feature in the UI

### ISSUE THREAD

**Issue by e-tienne** [ansible/awx#2284]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 
 - UI

##### SUMMARY

- It would be nice to have an Export and Import feature in the UI
- The current command line equivalent is receive and send with tower-cli
##### ADDITIONAL INFORMATION

tower-cli send and receive commands to export and import resources:

https://github.com/ansible/tower-cli/tree/v3.3.0/tower_cli/cli/transfer

**Comment by ghost** [comment]
+1

**Comment by chazemery** [comment]
any update on this feature?
I see it has been a couple of years since last comment

**Comment by chazemery** [comment]
would be fantastic for a this or a similar feature to be able to connect with Source Control (GIT, BitBucket, whatever)
in order to treat Tower objects as source controlled code

**Comment by azrdev** [comment]
is this issue the same as #5109 ?

**Comment by ffirg** [comment]
We are not looking to implement this feature. There are collections already around which can treat the tower/controller config as code.
