### ISSUE TITLE
Search Feature doesn't seem to work for Firefox 62 on AWX 1.0.7.4

### ISSUE THREAD

**Issue by mneumarkidg** [ansible/awx#2286]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Unable to use the search boxes. When I type my search terms in the box and hit "enter" or click the icon for search. Nothing happens

##### ENVIRONMENT
* AWX version: 1.0.7.4
* AWX install method: Kubernetes
* Ansible version:  2.6.4
* Operating System: Kubernetes / Docker
* Web Browser: Firefox 62.0

##### STEPS TO REPRODUCE

When I type my search terms in the box and hit "enter" or click the icon for search. Nothing happens

##### EXPECTED RESULTS

Page searches and filters out results as expected.

##### ACTUAL RESULTS

Nothing happens when trying to search. Icon and hit doesn't trigger filter to search.

##### ADDITIONAL INFORMATION

None.

**Comment by wenottingham** [comment]
Is there an error in the browser console?
