### ISSUE TITLE
Ansible Playbooks missing in AWX

### ISSUE THREAD

**Issue by naisanza** [ansible/awx#229]
##### ISSUE TYPE

 - Documentation Report?

##### COMPONENT NAME

 - AWX New Projects

##### SUMMARY

Ansible playbooks in /var/lib/awx/projects, are not showing up in AWX when creating a new project

![screenshot from 2017-09-20 17-08-24](https://user-images.githubusercontent.com/1614425/30673227-67fc1632-9e26-11e7-9389-aba64dc721d0.png)

```
root@awx-world0:/var/lib/awx/projects# ls
ansible_awx.yml  gui_lxc.yml                python-minimal.yml     ubuntu-readyup-lxc.yml
ansible.yml      openvpn_lxc.yml            splunk-enterprise.yml  ubuntu-readyup.yml
docker.yml       ping.yml                   splunk-light.yml       unattended-upgrades.yml
freeradius.yml   proxmox_newlxc-simple.yml  tmux.yml
```
After reading the comment in https://github.com/ansible/awx/blob/devel/awx/main/models/projects.py#L59, I moved the playbooks into a folder, and re-ran awx via install.yml:
```
root@awx-world0:/var/lib/awx/projects# ls
antsable
```
But it still doesn't show up in AWX when creating a new project. http://docs.ansible.com/ansible-tower/2.4.1/html/quickstart/create_project.html

Am I doing something wrong?

##### ENVIRONMENT

* AWX version: ece93c45c9c932cfbfba2b44e217e99a6bb6a752
* Ansible version:  2.4.0.0
* Operating System: Proxmox Ubuntu 16.04 server
* Web Browser: Chrome

**Comment by matburt** [comment]
If you are trying to manage projects manually (which we don't recomment, btw). You'll need to make sure you load the projects onto both containers and in the same location.
