### ISSUE TITLE
RFE: Easier to Digest Search Filters

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#2296]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
- UI

##### SUMMARY
As an Operator I want to have easier to use filter criteria so that I can more easily create my own without having to study the API pages

##### ADDITIONAL INFORMATION
Filter dropdowns would be a potential solution here.

**Comment by wenottingham** [comment]
Assumption is this would be a la the github search dropdowns.

**Comment by unlikelyzero** [comment]
Going to assume that this has been solved by the new Advanced Search
