### ISSUE TITLE
Changing Credential Type, when not used anywhere else

### ISSUE THREAD

**Issue by naisanza** [ansible/awx#230]
##### ISSUE TYPE

 - Feature request

##### COMPONENT NAME

 - Edit Credentials

##### SUMMARY

Editing a credential type, when it's not used anywhere else, gives an error

![screenshot from 2017-09-20 22-46-01](https://user-images.githubusercontent.com/1614425/30680744-2d288556-9e56-11e7-9bb9-659b46ac225d.png)

Error:
```
You cannot change the credential type of the credential, as it may break the functionality of the resources using it.
```

##### ENVIRONMENT

* AWX version: ece93c45c9c932cfbfba2b44e217e99a6bb6a752
* Ansible version:  2.4.0.0
* Operating System: Proxmox Ubuntu 16.04 server
* Web Browser: Chrome

**Comment by ryanpetrello** [comment]
@naisanza I've got a fix coming for this soon

**Comment by ryanpetrello** [comment]
@naisanza I merged in support for this a few weeks ago:

https://github.com/ansible/awx/commit/c8f4320b5820c43770fb4ab2671965aad54344c4

Let me know how it works for you!

**Comment by naisanza** [comment]
@ryanpetrello Will do if I run into an issues!
