### ISSUE TITLE
Changing postgres_data_dir to a persistent directory does not prevent configuration being wiped.

### ISSUE THREAD

**Issue by shanedobson-ibboost** [ansible/awx#2307]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI
 - Installer

##### SUMMARY
Changing postgres_data_dir to a persistent directory does not prevent configuration being wiped.

##### ENVIRONMENT
* AWX version: 1.0.7.2
* AWX install method:  docker on linux
* Ansible version:  2.6.4
* Operating System: Ubuntu 18.04.1 LTS
* Web Browser: All

##### STEPS TO REPRODUCE

1. Install AWX and configure users, organisations, jobs
2. Edit inventory file to change  postgres_data_dir to /var/lib/postgres
3. Restart host server for maintenance

##### EXPECTED RESULTS

Access the UI and find all pre-existing configuration intact

##### ACTUAL RESULTS

Access the UI and only default user (admin/password) exists and no other configuration persists.

**Comment by shanedobson-ibboost** [comment]
I didn't realise I had to rebuild the containers.

**Comment by Aech1977** [comment]
which would normally be no problem except the export import of the Postgres container DB.  I have yet to be able to restore the psql data dump.
