### ISSUE TITLE
Update and default admin 

### ISSUE THREAD

**Issue by jamm1985** [ansible/awx#231]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

In case of rename `admin` to `someuser` and do performing update process the `admin` user will be created with default login and password next to existing renamed admin account.

##### ENVIRONMENT

* AWX version: 1.0.0.505
* Ansible version:  2.3.2.0
* Operating System: Ubuntu 16.04.3 LTS
* Web Browser: 60.0.3112.113

##### STEPS TO REPRODUCE

Just rename `admin` and do update

##### EXPECTED RESULTS

The  `admin` with default `password` will be created

##### ACTUAL RESULTS

Security issue

**Comment by matburt** [comment]
done in #249

**Comment by jamm1985** [comment]
@matburt thank you!
