### ISSUE TITLE
expand Azure creds to handle all varieties of Azure credential

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#2315]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

From https://docs.ansible.com/ansible/2.6/scenario_guides/guide_azure.html#providing-credentials-to-azure-modules:

...

Using Environment Variables

To pass service principal credentials via the environment, define the following variables:

    AZURE_CLIENT_ID
    AZURE_SECRET
    AZURE_SUBSCRIPTION_ID
    AZURE_TENANT

To pass Active Directory username/password via the environment, define the following variables:

    AZURE_AD_USER
    AZURE_PASSWORD

To pass Active Directory username/password in ADFS via the environment, define the following variables:

    AZURE_AD_USER
    AZURE_PASSWORD
    AZURE_CLIENT_ID
    AZURE_TENANT
    AZURE_ADFS_AUTHORITY_URL

“AZURE_ADFS_AUTHORITY_URL” is optional. It’s necessary only when you have own ADFS authority like https://xxx.com/adfs.
...

We do not support all of these in the current Azure credential.

**Comment by gamuniz** [comment]
Closing as custom credential system allows for this type of modification.
