### ISSUE TITLE
WorkflowChart-svg needs a width: 100%

### ISSUE THREAD

**Issue by henry-zektser-vineti** [ansible/awx#2316]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
In Workflow Visualizer, the svg element is horizontally truncated.
<img width="1444" alt="image" src="https://user-images.githubusercontent.com/40836835/45978592-bd280780-c01a-11e8-8bfc-829cd8ae1eff.png">

##### ENVIRONMENT
* AWX version: tip of master branch
* AWX install method: openshift
* Ansible version:  tip of master branch
* Operating System: CentOS 7
* Web Browser: Confirmed in Firefox and Safari

##### STEPS TO REPRODUCE
Just open workflow visualizer

##### EXPECTED RESULTS
Diagram is full width

##### ACTUAL RESULTS
Diagram is truncated

##### ADDITIONAL INFORMATION
Adding a width: 100% to the CSS class WorkflowChart-svg appears to resolve this.

**Comment by mabashian** [comment]
Fixed with https://github.com/ansible/awx/pull/2348
