### ISSUE TITLE
AWX Installer: There is no way to prevent preloaded/demo configuration from being created

### ISSUE THREAD

**Issue by dmsimard** [ansible/awx#2317]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
The "regular" Tower installer supports setting ``create_preload_data=False`` to prevent the creation of demonstration configuration.
There is currently no equivalent for the current installer of AWX in OpenShift/k8s: https://github.com/ansible/awx/blob/ae207b5f330b087d29917a5b661d04fa3b0dfc9a/installer/roles/kubernetes/tasks/main.yml#L188-L193

##### EXPECTED RESULTS

There should be a parameter to disable the creation of preloaded/demo configuration.

##### ACTUAL RESULTS

The preloaded/demo configuration is always created.

**Comment by vin-c** [comment]
Hi there,

The PR mentionned seems to disable the creation when deploying on k8s, but this does not work for a docker installation (tested with 11.0.0)

Regards

**Comment by vin-c** [comment]
Hi there,

The PR mentionned seems to disable the creation when deploying on k8s, but this does not work for a docker installation (tested with 11.0.0)

Regards

**Comment by balonik** [comment]
this is still the case for local_docker install in 15.0.1.
the create_preload_data has no effect and demo organization/project/inventory is still created
