### ISSUE TITLE
AWX Should Support Inline Vaulted Variables During Inventory Sync

### ISSUE THREAD

**Issue by jritorto** [ansible/awx#2319]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
AWX should work seamlessly with existing inline-vaulted variable inventories in the recommended Ansible Alternative Directory Layout.

##### ADDITIONAL INFORMATION
- When running the inventory sync, despite having entered the vault password in a credential, vault variables for some reason don't work -- i.e. we get "ERROR!  Attempting to decrypt but no vault secrets found."

**Comment by wenottingham** [comment]
We in general do not want to decrypt vault content on inventory import, as then it is stored in plaintext in the API.

**Comment by wenottingham** [comment]
Does this work if variables are not vaulted at the file level?

**Comment by matburt** [comment]
Down the road we'll manage vault usage as the inventory import level. Since there's no follow up within the last week I'll close this issue.
