### ISSUE TITLE
Inventory Source, does not show yaml inventory files in root and subdirectories

### ISSUE THREAD

**Issue by naisanza** [ansible/awx#232]
##### ISSUE TYPE

 - Feature request

##### COMPONENT NAME

 - Inventory Source

##### SUMMARY

When selecting an inventory file, yaml files and files within subdirectories are not shown. For example, there should be inventory files at `all.yml` and `hosts/all.yml`

![screenshot from 2017-09-21 04-23-04](https://user-images.githubusercontent.com/1614425/30693475-9d942bc8-9e84-11e7-8ab8-67b7948966e8.png)

##### ENVIRONMENT

* AWX version: ece93c45c9c932cfbfba2b44e217e99a6bb6a752
* Ansible version:  2.4.0.0
* Operating System: Proxmox Ubuntu 16.04 server
* Web Browser: Chrome

**Comment by AlanCoding** [comment]
Related recent issue #174

We were providing yaml files as suggestions, but the problem is that this has a crowding-out effect, which is made particularly acute by users storing their playbooks in the same repository. You can still manually paste in the relative path of your yaml inventory file (and it will still work), but the inventory file suggestions are a tradeoff to make it easiest to use for the largest number of users.

**Comment by matburt** [comment]
I guess I'm wondering how prevelant this is for folks... my impression has always been that .yml inventories were less used than other types.

**Comment by AlanCoding** [comment]
When we check for the playbook file listing, we do some introspection of the file (looking for "hosts" or "include" words).

For inventory files, we could selectively add the file if it did _not_ fit the criteria we use for playbooks. That could help limit the noise.

**Comment by naisanza** [comment]
@AlanCoding it's funny, because mine only shows non-yaml files, and https://github.com/ansible/awx/issues/174 only shows yaml files

@matburt which is probably why yaml was depreciated once, before being brought back into the code? I had read on some Ansible documentation (maybe?), that to import an inventory it needed to be in yaml, so I reluctantly figured out yaml. But once I had, it wasn't too bad. Yaml is also used as the format for a lot of other cloud-related pre-configurations. So for me, having to use yaml took down two birds with one stone.

Yaml is certainly better than JSON, in terms of writing in, imho

@AlanCoding or simply, turn the text box into a search/filter box, which is what I originally thought it was. It'll give the UX of either scrolling to find their inventory file, or begin typing it into the text box, and it'll return a filtered list?

**Comment by matburt** [comment]
We don't currently do live searching, so I think we'll stick with where we are now as it covers the common inventory file use case while allowing folks to input things that aren't shown.
