### ISSUE TITLE
ERROR when trying to select credential in job template

### ISSUE THREAD

**Issue by g3l0l4** [ansible/awx#2321]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
I`m trying to create a new job template with a credential but when I try to select the credential I get this error --> 
![imagen](https://user-images.githubusercontent.com/17069911/46066200-66364580-c174-11e8-9d0f-7cead9d5bdb2.png)

##### ENVIRONMENT
* AWX version: 1.0.7.2
* AWX install method: docker on linux
* Ansible version:  2.6.2
* Operating System: Ubuntu 18.04.1 LTS
* Web Browser: Mozilla Firefox

##### STEPS TO REPRODUCE

Create new job template and click the search icon to search my credential.

##### EXPECTED RESULTS
List of credentials ir displayed.

##### ACTUAL RESULTS

Get this error: **Invalid search term entered. GET returned: 400 ID de credential_type no válida: NaN**

**Comment by wenottingham** [comment]
Does it work if you're not running in Spanish? (Just to narrow down the bug.)

**Comment by wenottingham** [comment]
In further looking, I'm going to assume this is the same thing as https://github.com/ansible/awx/issues/2231, and close it as a duplicate.

**Comment by g3l0l4** [comment]
Changing firefox language to english solved the problem but... if I want it in spanish i can´t select credential for job template... do you know how to fix that or I have to whait until the solution arrives?

**Comment by wenottingham** [comment]
It will require a software fix, there's not a workaround at the moment.
