### ISSUE TITLE
Versioning changed after 1.0.8??

### ISSUE THREAD

**Issue by MrMEEE** [ansible/awx#2322]
Hi

Has versioning or the way you are tagging version changed after 1.0.8??

mj@falcon:~/Download$ git clone https://github.com/ansible/awx.git
Cloning into 'awx'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 179555 (delta 0), reused 1 (delta 0), pack-reused 179548
Receiving objects: 100% (179555/179555), 201.52 MiB | 6.75 MiB/s, done.
mj@falcon:~/Download/awx$ git describe --long 
1.0.8-14-g8a66213db
mj@falcon:~/Download/awx$ git describe --long --first-parent
1.0.7-9-g8a66213db

When building the lastest source, the resulting tar.gz is named awx-1.0.7.9.tar.gz

-bash-4.2$ git describe --long 
1.0.8-14-g8a66213db
-bash-4.2$ ls -la dist/
total 10652
drwxr-xr-x.  2 root root       32 Sep 26 11:35 .
drwxr-xr-x. 14 awx  awx      4096 Sep 26 11:35 ..
-rw-r--r--.  1 root root 10900105 Sep 26 11:35 awx-1.0.7.9.tar.gz

In the makefile this is used:

VERSION=$(shell git describe --long --first-parent)
VERSION3=$(shell git describe --long --first-parent | sed 's/\-g.*//')
VERSION3DOT=$(shell git describe --long --first-parent | sed 's/\-g.*//' | sed 's/\-/\./')
RELEASE_VERSION=$(shell git describe --long --first-parent | sed 's@\([0-9.]\{1,\}\).*@\1@')

Which results in the 1.0.7.9 version tag..

**Comment by shanemcd** [comment]
Sounds like maybe an issue with your git repo. Try to fetch upstream again. We have a lot of tooling that is built around this versioning system and it’s showing up as 1.0.8 everywhere else. If you’re still having issues hit us up on IRC or the mailing list.

**Comment by MrMEEE** [comment]
mj@falcon:~/Download$ git clone https://github.com/ansible/awx.git
Cloning into 'awx'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 179555 (delta 0), reused 1 (delta 0), pack-reused 179548
Receiving objects: 100% (179555/179555), 201.52 MiB | 4.99 MiB/s, done.
Resolving deltas: 100% (139134/139134), done.
mj@falcon:~/Download$ cd awx/
mj@falcon:~/Download/awx$ git describe --long
1.0.8-14-g8a66213db                                                                                                                                                                                                   
mj@falcon:~/Download/awx$ git describe --long --first-parent                                                                                                                                                          
1.0.7-9-g8a66213db                                                                                                                                                                                                    
mj@falcon:~/Download/awx$

**Comment by MrMEEE** [comment]
Oh, didn't see the last part of the message, will try to post in the mailing list...

**Comment by shanemcd** [comment]
I'm actually going to reopen this. Here's what happening

When we cut `1.0.8`, things were fine. The images reported the right version and life was good.

Then when we merged a PR that was based off of devel @ 1.0.7, `--first-parent` now reports what @MrMEEE is seeing. 😞 

We're going to take this opportunity to revisit how versioning works in AWX. I will post updates here and close this out when we have a solution. Thanks for your patience.
