### ISSUE TITLE
Add WF level inventory to AWX UI

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#2325]
##### ISSUE TYPE
 - Task

##### COMPONENT NAME
 - UI

##### SUMMARY
link #2256 

This work can be split into two different steps:

### Step 1 - Adding support for the new field

**When creating/editing a workflow:**
-  A new lookup field (inventory) will be added to the form.  This field is always present and is optional.  A user can type into the input or click the magnifying glass icon to be presented with a modal lookup of inventory options.  If an invalid inventory is typed into the field the user should be presented with the exact same error message used in the job templates form.  Note that completely removing text from the input should not yield an error since the field is not required:
<img width="375" alt="screen shot 2018-09-26 at 10 30 11 am" src="https://user-images.githubusercontent.com/9889020/46086933-39376200-c177-11e8-9bd2-aca5466cad54.png"> 

-  In addition to the lookup field being added, a checkbox above the lookup field will be added which allows the user to toggle whether or not the inventory should be prompted at run-time.  All together the new field(s) will look like:
<img width="377" alt="screen shot 2018-09-26 at 10 33 08 am" src="https://user-images.githubusercontent.com/9889020/46087107-9b906280-c177-11e8-8425-3cae7a70bc02.png">

-  Popover help text will be added to the new field.  This gets displayed when the user clicks on this icon (contents tbd).  We'll want to explain to the user that this field _only_ overrides the inventory for JT workflow nodes where the JT has ask_inventory_on_launch set to true:
<img width="377" alt="screen shot 2018-09-26 at 10 33 08 am" src="https://user-images.githubusercontent.com/9889020/46087235-e14d2b00-c177-11e8-8e7d-f5840b9982b6.png">

-  The WORKFLOW VISUALIZER button will be removed from the form in favor of an icon link to be added on the templates list

**When adding/editing workflow nodes:**
-  If the template selected in the node is a WFJT:
    -  If the WFJT associated with the node has ask_inventory_on_launch set to true then the PROMPT button should be shown.  Clicking that PROMPT button should show an INVENTORY tab that lets the user optionally select an inventory before saving the node.

**When viewing a WF in the templates list:**
-  If a default inventory has been specified on the WF, display the inventory like we do for JT's
-  A new icon will be added to WF's in the templates list that will take the user straight to the visualizer without having to first view the edit form:
<img width="1381" alt="screen shot 2018-09-26 at 11 37 40 am" src="https://user-images.githubusercontent.com/9889020/46091367-b3b8af80-c180-11e8-848a-cdb01bbd22aa.png">

**When viewing WF job in jobs list:**
-  If a WF level inventory was specified at run-time, add an INVENTORY label along with the inventory name:
<img width="535" alt="screen shot 2018-09-26 at 11 38 57 am" src="https://user-images.githubusercontent.com/9889020/46091557-190ca080-c181-11e8-897d-0683be9a7f34.png">

**When viewing WF results:**
-  If a WF level inventory was specified at run-time, add an INVENTORY label along with the inventory name to the details (left-hand) panel of the WF results page:
<img width="629" alt="screen shot 2018-09-26 at 11 42 02 am" src="https://user-images.githubusercontent.com/9889020/46091646-435e5e00-c181-11e8-834a-db6120b808b5.png">

**When launching a WF:**
-  [Link to entire launch WF flow including possible prompts](https://tower-mockups.testing.ansible.com/mockups/templates/templates-prompt-wf-inventory/)
-  If ask_inventory_on_launch is set to true, launching the workflow should prompt the user for an _optional_ inventory.  The user should be able to provide an inventory, remove the specified inventory and/or move past this step without any changes.

**When scheduling a WF:**
-  If ask_inventory_on_launch is set to true, a PROMPT button should be shown next to the SAVE/CANCEL buttons on the schedule form.  Clicking the PROMPT button should show an optional INVENTORY step where the user can provide/remove an inventory or move past this step without any changes (see above screenshot).
<img width="1420" alt="screen shot 2018-09-26 at 1 37 45 pm" src="https://user-images.githubusercontent.com/9889020/46098041-6d1f8100-c191-11e8-8d13-ffb4b753e050.png">

### Step 2 - Enhance the user's experience

**When creating/editing a workflow:**
-  When a user first creates a workflow, on successful save they will be navigated from the form straight into the visualizer
-  In the lookup modal for WF level inventory the UI will add a static message explaining the impact of selecting a default inventory. 

**When adding/editing workflow nodes:**
-  If the template selected in the node is a WFJT:
    -  If a workflow level inventory has been set:
        -  If the WFJT associated with the node prompts for inventory on launch
            -  Show a message in add/edit node form stating that the outer workflow level inventory will override this inventory at run time

-  If the template selected in the node is a JT:
    -  The Inventory field on a workflow node will now _always_ be optional when prompted.  Previously this field has _always_ been required.  The UI will now need to indicate to the user that if an inventory is not provided, the node will not execute successfully unless a global WF inventory is specified .  This will require the UI to relax restrictions within the prompt modal on the inventory step.

    -  If a workflow level inventory has been set:
       -  If the JT associated with the node prompts for inventory on launch
          -  Show a message in add/edit node form stating that the workflow level inventory will override this inventory at run time
       -  If the JT associated with the node does not prompt for inventory on launch
          -  Show a message in add/edit node form stating that the workflow level inventory will not override the default inventory for this JT at run time
    -  If workflow level ask_inventory_on_launch has been set to true (checkbox):
       -  If the JT associated with the node prompts for inventory on launch
          -  Show a message in add/edit node form stating that if a workflow level inventory is specified at runtime it will override this inventory
       -  If the JT associated with the node does not prompt for inventory on launch
          -  Show a message in add/edit node form stating that the workflow level inventory will not override the default inventory 
-  Since we're decoupling the workflow form and the workflow visualizer, when the user saves the workflow visualizer, we'll now navigate the user back to the templates list rather than the WF edit form.

**When adding/editing workflow nodes:**
-  In the launch prompt modal for a WF the UI will add a static message explaining the impact of selecting an inventory.

**Comment by jakemcdermott** [comment]
done

**Comment by kw-c** [comment]
Is this now in image download and will it allow prompted selection of Inventory when running a workflow template ?

**Comment by sumkincpp** [comment]
Also a good question - can we restrict inventory prompt for certain inventory list?
That would be really useful since you will not be able to pickup incorrect one.
