### ISSUE TITLE
Trigger Synchronizations Remotely with Token, like Jenkins

### ISSUE THREAD

**Issue by naisanza** [ansible/awx#233]
##### ISSUE TYPE

 - Feature request

##### COMPONENT NAME

 - Scheduler

##### SUMMARY

Allow synchronizations to git servers to be started by a token when git hooks are used

This way AWX will always have the most up-to-date information, rather than retrieving the information on a scheduled interval. If the interval is too long, AWX isn't updated in time. And if the interval is very short, it would be making a lot of unnecessary connections when nothing has changed

##### ENVIRONMENT

* AWX version: ece93c45c9c932cfbfba2b44e217e99a6bb6a752
* Ansible version:  2.4.0.0
* Operating System: Proxmox Ubuntu 16.04 server
* Web Browser: Chrome

**Comment by matburt** [comment]
This will likely be covered by this work effort: https://github.com/ansible/awx/issues/21
