### ISSUE TITLE
Show instance name of instance that executed job on list and details for jobs

### ISSUE THREAD

**Issue by mneumarkidg** [ansible/awx#2330]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
When listing the Job List of Completed Jobs and Clicking on the Job Details for a Job. Should quickly identify the instance that executed the job. 

This will help for quickly identifying where issues within instance might be.

Example: If you have 5 PODs running on Kubernetes with AWX. You should be able to look at the job list and job details to identify the instance that executed the job for tracking and auditing purposes!

**Comment by marshmalien** [comment]
### UI
~~#### Jobs List~~
~~GET: [/api/v2/unified_jobs/]~~
~~Retrieve instance name from the "execution_node" field~~

~~* Add RowItem component with label and value~~
    ~~* Currently, an instance detail view does not exist, therefore we aren't providing a link~~
No plans to add an execution node field to the job list view until we implement configurable lists.

#### Jobs Details
GET: [/api/v2/jobs/:id]
Retrieve instance name from the "execution_node" field
* Add JobResults-resultRow with label and value to output details

**Comment by dsesami** [comment]
Verification checklist:
- [ ] Ensure that the instance name correctly renders and links given the constraints of possible instance names on ~the Jobs List page, as well as~ the Jobs Details page.
- [ ] Ensure appropriate behavior if the instance name information is blank for some reason (probably just a blank field)

**Comment by trahman73** [comment]
Updated Job Details panel to include EXECUTION NODE and rename INSTANCES to INSTANCE GROUP.

![image](https://user-images.githubusercontent.com/13351591/51206387-ee805800-18d5-11e9-928e-5ce93f39b0b9.png)

**Comment by dsesami** [comment]
Verified that EXECUTION NODE and INSTANCE GROUP fields show correctly on the Jobs Details page for successful and failed jobs.
