### ISSUE TITLE
AWX Inventory import does not work with foreman 1.19 

### ISSUE THREAD

**Issue by couchgott** [ansible/awx#2334]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - dynamic Inventory, inventory source

##### SUMMARY
Since i updated foreman to v1.19 i get an error if i try to import the foreman inventory into my awx instance.

AWX Log shows: 
`/usr/lib/python2.7/site-packages/awx/__init__.py:101: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif settings.SECRET_KEY == 'permission-denied':
2018-09-28 08:41:15,471 INFO     awx.main.commands.inventory_import Updating inventory 2: SPK
2018-09-28 08:41:15,484 DEBUG    awx.main.commands.inventory_import Using system install of ansible-inventory CLI: /usr/bin/ansible-inventory
2018-09-28 08:41:15,485 INFO     awx.main.commands.inventory_import Reading Ansible inventory source: /usr/lib/python2.7/site-packages/awx/plugins/inventory/foreman.py
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==1.0.5.19', 'console_scripts', 'awx-manage')()
  File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 993, in handle
    self.is_custom)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 242, in load_inventory_source
    is_custom=is_custom).load()
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 177, in load
    data = self.command_to_json(base_args + ['--list'])
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 160, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
ValueError("More than one set of facts returned for '%s'" % host) ValueError:
More than one set of facts returned for `

on the foreman Side i get a "Completed 200 OK in 88ms (Views: 8.5ms | ActiveRecord: 16.6ms)" in the logs (besides a JSON containing the inventory data) which looks like it should. no "401"/etc which would explain that permission denied AWX is mentioning. 

##### ENVIRONMENT
* AWX version: 1.0.5.19
* AWX install method: docker on linux
* Ansible version:  2.5.0
* Operating System: RHEL 7.5 
* Web Browser: Chrome/FF 
* Foreman 1.19.0

##### STEPS TO REPRODUCE
Setup Foreman as Inventory Source (va Sattelite 6) 

##### EXPECTED RESULTS

Inventory Imported.

##### ACTUAL RESULTS

Inventory Import Job quits with error.

**Comment by wenottingham** [comment]
What happens if you run the script by hand?

Regardless, this would need fixed in https://github.com/ansible/ansible first.

**Comment by couchgott** [comment]
Hey, 
not sure how to run the script manually 
Guessing just go into the container and running the mentioned py script? /usr/lib/python2.7/site-packages/awx/plugins/inventory/foreman.py
Creating the usual foreman.ini inventory by hand and place it somewhere in the container ... 
am i right? :o)

**Comment by couchgott** [comment]
Hey. 

running the script manually from inside the awx container or via a non-docker ansible gives the same result. 

`ValueError: More than one set of facts returned for '{u'comment': u'', u'build_status': 0, u'environment_id': 1, u'managed': True, u'model_id': 1, u'ip': None, u'provision_method': u'build', u'updated_at': u'2018-10-05 07:41:30 UTC', u'realm_name': None, u'configuration_status': 0, u'compute_resource_id': 1, u'puppet_status': 0, u'sp_mac': None, u'operatingsystem_name': u'Windows Server 2016', u'id': 239, u'disk': None, u'domain_id': 1, u'build_status_label': u'Installed', u'ptable_id': None, u'subnet_id': None, u'sp_name': None, u'environment_name': u'windows_prod', u'architecture_name': u'x64', u'domain_name': u'spectrumk.ads', u'capabilities': [u'build', u'image', u'snapshots'], u'subnet6_id': None, u'image_id': None, u'global_status': 0, u'architecture_id': 3, u'build': False, u'hostgroup_title': u'Server/XXXXXXXX', u'subnet_name': None, u'sp_ip': None, u'model_name': u'XXXXXXXX', u'puppet_proxy_id': 1, u'global_status_label': u'OK', u'owner_id': 4, u'operatingsystem_id': 7, u'sp_subnet_id': None, u'puppet_ca_proxy_name': u'XXXXXXXX', u'owner_name': u'XXXXXXXX', u'configuration_status_label': u'No changes', u'name': u'XXXXXXXX', u'compute_profile_name': u'XXXXXXXX', u'certname': u'XXXXXXXX', u'image_name': None, u'image_file': u'', u'mac': None, u'ip6': u'', u'puppet_ca_proxy_id': 1, u'puppet_ca_proxy': {u'url': u'https://XXXXXXXX', u'name': u'lXXXXXXXX', u'id': 1}, u'last_report': u'2018-10-05 07:40:15 UTC', u'puppet_proxy': {u'url': u'XXXXXXXX', u'name': u'lyo-pconf.spectrumk.ads', u'id': 1}, u'medium_name': None, u'last_compile': None, u'uuid': None, u'pxe_loader': u'None', u'ptable_name': None, u'medium_id': None, u'compute_resource_name': u'XXXXXXXX', u'created_at': u'2018-09-28 09:36:57 UTC', u'expired_on': None, u'enabled': True, u'hostgroup_id': 52, u'subnet6_name': None, u'hostgroup_name': u'XXXXXXXX', u'use_image': None, u'compute_profile_id': 1, u'owner_type': u'User', u'realm_id': None, u'installed_at': None, u'puppet_proxy_name': u'lXXXXXXXX'}'`

so i will head over to the ansible issue tracker. 

Thanks and Cheers!

D.

**Comment by couchgott** [comment]
Hey guys, 
sooo.. after trying the new way of importing foreman inventories using the (new) Ansible Inventory Plugin Structure it's working:
https://github.com/ansible/ansible/issues/46523#issuecomment-428565417

sadly this is not the way AWX is doing imports atm. 
Are there any plans to change that? 
Or do i need to build sth. as a work-a-round? :)

**Comment by wenottingham** [comment]
Inventory plugin work is tracked here: https://github.com/ansible/awx/issues/171

**Comment by Nitradamus** [comment]
I'm running into the same error, have you got this working yet within AWX @couchgott ?

**Comment by couchgott** [comment]
hey @nitram2k,
no not working jet. 
my plan is to write a little cron job checking in an inventory via vanilla ansible 2.6 into git and then import that project as inventory source into AWX until awx is using the plugin as well. 
another way might be to use the custom inventory function in awx .. but not sure how that works yet. 
i planned to look deeper into it next week or the week after if i find some time. 
will let you guys know how the solution (at least for me) looks in the end :)

**Comment by Nitradamus** [comment]
@couchgott 

> hey @nitram2k,
> no not working jet.
> my plan is to write a little cron job checking in an inventory via vanilla ansible 2.6 into git and then import that project as inventory source into AWX until awx is using the plugin as well.
> another way might be to use the custom inventory function in awx .. but not sure how that works yet.
> i planned to look deeper into it next week or the week after if i find some time.
> will let you guys know how the solution (at least for me) looks in the end :)

Cool, i'll be trying out the other options as well, love to hear what you did to make this work :)

**Comment by couchgott** [comment]
hiho @nitram2k,
so i got something working as a work-a-round. Honestly i did not care so much about the "want_facts" feature as i am not using it here. 
Anyway. Here is what i did: 

Create a little script running via cron locally on a host (in my case it's running on the host where the awx containers are living but it does not matter ..) using the Vanilla Ansible 2.6
I setup the foreman inventory plugin in a way i can see the inventory/groups stuff from foreman appeating as a json.

`
/sbin/pidof -s -o '%PPID' -x $( basename $0 ) > /dev/null 2>&1 && echo "Another Inventory Update script is already running at $(date)" >&2 && exit

exec 1> >(logger -s -t $(basename $0) 2>&1)
exec 2> >(logger -s -t $(basename $0))

/bin/ansible-inventory -i /etc/ansible/my.foreman.yml --list | /etc/ansible/ansible-dynamic-inventory-converter.py
/bin/svn commit -m "TEST: Ansible Inventory Update" /path to hosts/hosts

exit 0`

i found the following little pretty helper to generate a static inventory file from the dynamic foreman inventory -> https://gist.github.com/DavidWittman/189816c1c2b3a25bd1b18f5f9f681262

so i am ending up with a plain inventory file. 
The Script also generates a host_vars structure but i am not using this for my approach.. ;) 

the resulting hosts inventory file i am uploading to my code repository (svn in our case but git will perfectly do)

At AWX i added a new inventory source "Sourced from a Project" 

and done. 

hope this helps you until AWX is using the plugin as vanilla ansible does.

**Comment by couchgott** [comment]
Hi folks,

i just tested with Foreman 1.19.1 and awx 2.1.0 and i was able to successfully import the foreman inventory. 

Maybe you want to give it a try ;) 

Cheers!

D.

**Comment by linuxcube** [comment]
couchgott, can you provide more update in details as to how to get this working...I am using foreman 1.20 and need something like this to import my dynamic inventory. Thank you.

**Comment by couchgott** [comment]
@linuxphone just create an account at your foreman instance and add the creds and url of your foreman instance as "RH Sattelite 6" inventory source into your awx. works this way also with foreman 1.20
Hope this helps.
