### ISSUE TITLE
LDAP setup is not working with AWX

### ISSUE THREAD

**Issue by forprem** [ansible/awx#2337]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
LDAP setup is not working, main issue is LDAP Bind DN password value is not saved. After setting up the field I tried ldap id but did not work.
django_auth_ldap Caught LDAPError while authenticating ,<LDAP_ID> OPERATIONS_ERROR({'info': 'SSL connection already established.', 'desc': 'Operations error'},)

##### ENVIRONMENT
* AWX version: 1.0.8.0
* AWX install method: docker on linux
* Ansible version:  2.6.4
* Operating System: Tried in RHEL and Centos 7.5
* Web Browser:

##### STEPS TO REPRODUCE

Log into AWX, Settings, Authentication, LDAP 

##### EXPECTED RESULTS

Connection to Active Directory

##### ACTUAL RESULTS

UI Says "Invalid username and/or password. Please try again."

##### ADDITIONAL INFORMATION

<img width="730" alt="capture1" src="https://user-images.githubusercontent.com/12073404/46212548-4170d800-c304-11e8-8edd-a13c013331d8.PNG">
<img width="241" alt="capture2" src="https://user-images.githubusercontent.com/12073404/46212560-46ce2280-c304-11e8-88eb-91d36f25e07e.PNG">
<img width="302" alt="capture3" src="https://user-images.githubusercontent.com/12073404/46212566-49c91300-c304-11e8-822d-95ca5d79d240.PNG">

**Comment by jakemcdermott** [comment]
Hi forprem,

Thanks for filing this issue. This looks like a configuration or infrastructure issue - if you're looking for support on such things, your best options would be to reach out to our community mailing list or stop by our irc channel (`#ansible-awx` on freenode).
