### ISSUE TITLE
Installation Fail's Due To - ERROR! 'name' is not a valid attribute for a Block

### ISSUE THREAD

**Issue by APenketh** [ansible/awx#234]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Upon trying to perform a fresh installation of AWX tower the installer fails with the error message:
ERROR! 'name' is not a valid attribute for a Block

##### STEPS TO REPRODUCE

Upon downloading a fresh copy of the AWX repository, edited the appropriate fields in the inventory file and then run the install like indicated within the installation instructions:
ansible-playbook -i inventory install.yml

##### EXPECTED RESULTS

Expected result if for the installer to finish the installation of the tower.

##### ACTUAL RESULTS

The following error is displayed:
ERROR! 'name' is not a valid attribute for a Block

The error appears to have been in '/opt/awx/installer/openshift/tasks/main.yml': line 24, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Get docker registry password from oc if needed
  ^ here

##### ADDITIONAL INFORMATION

Based upon the output, looks like the issue is with the following block:

- name: Get docker registry password from oc if needed
  block:
    - name: Set docker registry password
      shell: oc whoami -t
      register: docker_registry_password_shell
    - name: Set docker registry password
      set_fact:
        docker_registry_password: "{{ docker_registry_password_shell.stdout }}"
  when: docker_registry_password is not defined

**Comment by APenketh** [comment]
As per the documentation: http://docs.ansible.com/ansible/latest/playbooks_blocks.html

"New in version 2.3: The name: keyword for blocks: was added in Ansible 2.3."

Looks like I might be able to fix this by upgrading to Ansible 2.3. 
It does not say anywhere in the installation documents that there is a minimum requirement of Ansible 2.3 though - https://github.com/ansible/awx/blob/devel/INSTALL.md

I'll update the Ansible version re-try and then if it works I shall add something to the installation documentation to reflect that.

**Comment by APenketh** [comment]
Using Ansible version 2.3.X solved this issue.

**Comment by shahidkarimi** [comment]
What is a solutoin for ansible 2.2 ??

**Comment by APenketh** [comment]
The requirement for AWX is now ansible version 2.8 as per doc's.
https://github.com/ansible/awx/blob/devel/INSTALL.md#prerequisites
You should not be using 2.2 anymore with AWX
