### ISSUE TITLE
RFE: export schedule information in tabular format

### ISSUE THREAD

**Issue by e-tienne** [ansible/awx#2353]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY
generate schedule report in tabular format for the following:
* Report containing templates, and workflows with schedule, and inventory hosts
*  Report containing jobs, and workflow jobs with schedules as well  as hosts where jobs were executed on
##### ADDITIONAL INFORMATION

Ability to generate a report of what job template being affected when acting on a schedule.
Also, if the schedule is for a workflow template, what job templates being affected by acting the schedule.

If it is even possible, include inventories and hosts affected by the schedule also.
Here is an example of output I would like to see:

schedulename, month, date, time, recurse, workflow template name, job template name(s), inventory(ies), host(s)

**Comment by wenottingham** [comment]
This is generally not something we would do without building a more generic reporting engine, which is not a near-term item.

This could be done via scripting of API queries.
