### ISSUE TITLE
Deleting multiple hosts 

### ISSUE THREAD

**Issue by naisanza** [ansible/awx#236]
##### ISSUE TYPE

 - Feature Request 

##### COMPONENT NAME

 - UI

##### SUMMARY

Multiselecting, selecting all hosts

If an erroneous inventory file is imported, the current UI requires you to individually delete each host one by one

##### ENVIRONMENT

* AWX version: ece93c45c9c932cfbfba2b44e217e99a6bb6a752
* Ansible version:  2.4.0.0
* Operating System: Proxmox Ubuntu 16.04 server
* Web Browser: Chrome

**Comment by matburt** [comment]
This work will be covered here: https://github.com/ansible/awx/issues/19

**Comment by naisanza** [comment]
@matburt in the meantime.. is there a command-line tool to get rid of these hosts?

**Comment by naisanza** [comment]
Edit: Yes it does remove all the hosts, horay

@matburt if I delete the inventory file from where the host came from, will it remove the hosts?

**Comment by matburt** [comment]
You can delete the inventory and recreate it.

**Comment by one1zero1one** [comment]
Just a kind reminder, delete/recreate the inventory causes the id_inventory field from main_jobtemplate to become NULL, blocking templates that were using said inventory to be edited in or ran.
