### ISSUE TITLE
Kubernetes deployment unintentionally self-upgraded and now it's stuck

### ISSUE THREAD

**Issue by bisimrem** [ansible/awx#2361]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer (probably?)

##### SUMMARY
After deploying to Kubernetes (after some struggles) about a month ago,using external Postgres, AWX was working fine. Doing no changes on it whatsoever since then, we did check up on it yesterday and discovered that it's stuck in a wierd permanent upgrade state. Restarting the cluster didn't help, scaling up and down deployment/pods/replica sets either. We're trying to find a workaround or a solution to get it back to a working state in the cleanest possible way without losing data and secrets already inside (if they're not lost already).
[What became of our AWX](https://imgur.com/a/FBGzeJb)

##### ENVIRONMENT
* AWX version: 1.0.7
* AWX install method: kubernetes
* Ansible version:  2.6.3
* Operating System: Centos 7
* Web Browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)

##### STEPS TO REPRODUCE

Invent time machine, go back one month, deploy AWX 1.0.7 to a kubernetes cluster, wait till today.

##### EXPECTED RESULTS

Nothing, we expected to work with the installed version until we decided to upgrade to a newer one.

##### ACTUAL RESULTS

It stopped working on it's own.

##### ADDITIONAL INFORMATION

Upon closer examination, we've discovered that the docker images used in a RELEASE are tagged 'latest' instead of by their release version. Looks like kubernetes somehow discovered there are new versions of those images and proceeded to upgrade to them (version 1.0.8)
(on master)
```
kubectl describe pod awx -n awx | grep "Image:"
    Image:          ansible/awx_web:latest
    Image:         ansible/awx_task:latest
    Image:          ansible/awx_rabbitmq:3.7.4
    Image:          memcached:latest
```
(on one of the workers with awx currently residing)
```
docker image list
REPOSITORY                      TAG                 IMAGE ID            CREATED             SIZE
ansible/awx_task                latest              7b5e01db4cb5        8 days ago          1.07GB
ansible/awx_web                 latest              bd4a204ab89a        8 days ago          1.04GB
memcached                       latest              9bf7d35db978        2 weeks ago         62.2MB
ubuntu                          16.04               52b10959e8aa        5 weeks ago         115MB
gcr.io/kubernetes-helm/tiller   v2.10.0             0cccc6576d01        6 weeks ago         69MB
ansible/awx_task                <none>              67398bc01f40        7 weeks ago         1.03GB
k8s.gcr.io/kube-proxy-amd64     v1.11.2             46a3cd725628        8 weeks ago         97.8MB
busybox                         latest              e1ddd7948a1c        2 months ago        1.16MB
node                            8.11.2              baf6417c4cac        3 months ago        673MB
ansible/awx_rabbitmq            3.7.4               e08fe791079e        6 months ago        85.6MB
quay.io/coreos/flannel          v0.10.0-amd64       f0fad859c909        8 months ago        44.6MB
gitlab/gitlab-runner-helper     x86_64-5cf5e19a     ec1417f49750        9 months ago        43.9MB
gitlab/gitlab-runner            alpine-v10.3.0      0282be6186b1        9 months ago        105MB
k8s.gcr.io/pause                3.1                 da86e6ba6ca1        9 months ago        742kB
```

**Comment by jakemcdermott** [comment]
Hello, 

Thanks for creating this issue. Upgrades between 1.* versions are not supported. Please see our [documentation on data migrations and upgrades](https://github.com/ansible/awx/blob/devel/DATA_MIGRATION.md) for more information. Thanks!
