### ISSUE TITLE
AWX not updating to show any new files in git repo

### ISSUE THREAD

**Issue by mramirezacr** [ansible/awx#2365]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

I set up a Git repo under my work email with one .yml file as a playbook.  Set up a new project named 'Test Repo' in AWX.  That file named createfile.yml shows up when I try to create a new job template using that project.  However, any new files added to the Git repo are not showing up in AWX.  

##### ENVIRONMENT
* AWX version: 1.0.8.0
* AWX install method: docker on linux
* Ansible version:  2.6.4
* Operating System: Centos 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Go to Project > Test Repo > Get latest SCM revision.  The latest revision number then shows up for 'Test Repo' but any new files added to the repo do not appear.

##### EXPECTED RESULTS

Any new files added to repo display in drop down box for Playbook in job template.

##### ACTUAL RESULTS

Only original file named createfile.yml is shown.

**Comment by mramirezacr** [comment]
Have tried rebooting server.
Have tried deleting 'Test Repo' project and creating a whole new project using the same URL for the Git repo.  The new project was created after new files were added to the repo, but still only the first, original createfile.yml appears.

**Comment by matburt** [comment]
I'm having trouble reproducing this. Are these files playbooks? We *will* only show files that appear to be playbooks (not just any yaml file). Do these files show up in the project directory in the container itself?

**Comment by mramirezacr** [comment]
Hi Mat, I am 100% new to Ansible and AWX, so it's entirely possible my file isn't the correct syntax.  I tried copying a playbook template I found online.  The git link is https://github.com/mramirez-t/awx.  The createfile.yml playbook shows up no problem.  My #1 purpose to use AWX is to run yum updates on our Linux servers, so it's the exclude1.yml playbook that I really want to get working.  I copied it from an online source to try to run yum while excluding certain packages.  

Is it my syntax that's wrong?

**Comment by matburt** [comment]
`exclude1.yml` is not a valid playbook... it's just a single task. It's missing the `hosts` line and some other things.

I'd *strongly* recommend you go through the Ansible introduction before going much further https://docs.ansible.com/ansible/latest/user_guide/intro_getting_started.html

and then move on to the other chapters in the documentation. You really need to have a good handle on Ansible before you can extend that to AWX.
