### ISSUE TITLE
Additonal Monitoring Info on Dashboard, Job List, and My View without need for Filtering

### ISSUE THREAD

**Issue by mneumarkidg** [ansible/awx#2366]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
Would love to see real-time status for the last 24 hours of new, pending, and running jobs in the Dashboard, Jobs List, or My View page. This will allow to monitor (quick glance) from a single panel without having to filter (requiring users to know filter syntax and perm queries to gather counts) jobs list or API.

**Comment by matburt** [comment]
We have a plan to revamp the dashboard in the near future.
