### ISSUE TITLE
Provide workflow ID, schedule ID, username, etc. automatically in extra_vars

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#237]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY

Current behavior:

Jobs all have the following automatically added to the variables passed in as `--extra-vars`.

 - tower_job_id
 - tower_job_launch_type
 - tower_job_template_id
 - tower_job_template_name
 - tower_user_name

When you launch a job template manually, the `tower_user_id` variable is also provided.

However, if a playbook needed to make a decision based on whether it was used in a workflow, or launched by a schedule, there is not any flag obviously available right now.

Proposal:

 - if a job is ran as a part of a workflow, add `tower_workflow_job_template_id` to its extra vars
 - if a job is spawned by a schedule, add `tower_schedule_id` to its extra vars

Another proposal:

 - if a user directly launches a workflow, we should include `tower_user_id` in jobs that are spawned by the workflow as well, which is not currently done

**Comment by AlanCoding** [comment]
Note that the variables are also passed in the `awx_*` format. Some more details are in the linked closed issue.

Also editing title to reflect more of the variables.

**Comment by MWassim211** [comment]
is it possible to have the Tower_Workflow_Status ?

**Comment by AlanCoding** [comment]
^ wouldn't that always be "running" at the time the job started?
