### ISSUE TITLE
JT project-related error message needs updating

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#2370]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Delete the project that a JT uses and then try to edit the JT

error message returned is

> {'project': ["Job types 'run' and 'check' must have assigned a project."]}

But if you check OPTIONS

```json
            "job_type": {
                "type": "choice",
                "required": false,
                "label": "Job type",
                "filterable": true,
                "default": "run",
                "choices": [
                    [
                        "run",
                        "Run"
                    ],
                    [
                        "check",
                        "Check"
                    ]
                ]
            },
```

There are only 2 types.

The error message is old and needs to be updated to reflect the current options.

##### ENVIRONMENT
* AWX version: 1.0.8
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

details in summary

**Comment by paradegoat** [comment]
I'm interested in working on this. Could you explain what the expected error message would be?

**Comment by AlanCoding** [comment]
Yes, since there are no longer any "scan" type job templates (which did _not_ need a project), _all_ job templates must have a project assigned. @chrismeyersfsu could you check me on that?
