### ISSUE TITLE
Accept same variable formats in all cases

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#2371]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
AWX has many fields that contain variables, and is editable by the user. There's no fundamental difference in the type for any of these, but yet, they behave differently.

##### ENVIRONMENT
* AWX version: 1.0.8
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  N/A
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Here's a unit test to haphazardly create a table of what works and doesn't work:

```python
@pytest.mark.django_db
def test_vars_consistency(patch, inventory, job_template, project, wfjt_node, admin_user):
    d = {'foo': 'bar'}
    job_template.project = project
    job_template.ask_variables_on_launch = True
    job_template.ask_inventory_on_launch = True
    job_template.inventory = inventory
    job_template.playbook = 'helloworld.yml'
    job_template.save()
    for kind, vars in (('dict', d), ('json_str', json.dumps(d)), ('yaml_str', 'foo: bar')):
        print ''
        print ' testing kind: ' + str(kind)
        for res, fd in ((inventory, 'variables'), (job_template, 'extra_vars'), (wfjt_node, 'extra_data')):
            print ' field: ' + str(fd)
            try:
                patch(
                    url=res.get_absolute_url(),
                    data={fd: vars},
                    user=admin_user,
                    expect=200
                )
                print ' worked '
            except Exception as e:
                print ' did not work ' + str(e)
    assert False
```

##### EXPECTED RESULTS

All fields accept all forms of passing the variables in.

##### ACTUAL RESULTS

table from those results

| field \ accepts           | plain dict | JSON string | YAML string |
|---------------------------|------------|-------------|-------------|
| inventory (variables)     | ❌          | ✅           | ✅           |
| job template (extra_vars) | ❌          | ✅           | ✅           |
| WFJT nodes (extra_data)   | ✅          | ✅           | ✅           |

##### ADDITIONAL INFORMATION

Also, job template `extra_vars` will preserve comments, while none of the others will.

**Comment by ryanpetrello** [comment]
Should be resolved by the solution to https://github.com/ansible/awx/pull/4600
