### ISSUE TITLE
EFS mount with AWX

### ISSUE THREAD

**Issue by nschhina** [ansible/awx#2374]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
EFS mount with AWX ec2 instance fails and results in bad file descriptor error in logs

##### ENVIRONMENT
* AWX version: 1.8.0
* AWX install method: docker on linux
* Ansible version:  2.4.0
* Operating System: Amazon Linux
* Web Browser: All

##### STEPS TO REPRODUCE

Try to mount EFS volume on the EC2 instance's directory(directory to store git resources). Mount is successful, can verify mount is working as expected. However can't update/pull Projects and error logs show Python: bad file descriptor

##### EXPECTED RESULTS

Project should update sucessfully

##### ACTUAL RESULTS

Bad File Descriptor error with Python

**Comment by wenottingham** [comment]
I assume this is #2195, marking as duplicate.
