### ISSUE TITLE
RFE: Being able to select both `Update on Launch` and `Update on Project Change` for source from SCM inventory sources

### ISSUE THREAD

**Issue by cesarfn4** [ansible/awx#2382]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Currently, there is not possible to enable `Update on Launch` and `Update on Project Change` for a SCM-based inventory even disabling `Update Revision on Launch` for the SCM project.

**Comment by wenottingham** [comment]
Correct, this is intentional; you use the SCM update-on-launch in combination with update-on-project-change to do an inventory update on launch.

**Comment by wenottingham** [comment]
Further discussion: the use case is an executable script in source control, where it is desired to run it on launch even if the repo doesn't change.

**Comment by aneagoe** [comment]
We've hit the same, having this functionality would be great!

**Comment by AlanCoding** [comment]
We removed the `Update on Project Change` toggle in https://github.com/ansible/awx/pull/12366

The backing for doing that is that it is replaced with ordinary update-on-launch, done in https://github.com/ansible/awx/pull/12073 by @fosterseth, and what you get from that basically equates to what you were hoping for here. Accordingly, closing.
