### ISSUE TITLE
Partition (/var) keeps growing

### ISSUE THREAD

**Issue by coom** [ansible/awx#2385]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Core

##### SUMMARY

Docker container keeps growing in term of disk usage. /var is growing by 1Go every month.

```bash
/dev/sda3       6.4G  5.7G  359M  95% /var
overlay         6.4G  5.7G  359M  95% /var/lib/docker/overlay2/1816d8cfacb32f87b19e764c359c78a4abc5084e2fd94e09cb63b6151cbb5265/merged
shm              64M     0   64M   0% /var/lib/docker/containers/788c527944137241b7789581349a23a52e3124109465d1c6c60ee16538a203fb/mounts/shm
overlay         6.4G  5.7G  359M  95% /var/lib/docker/overlay2/6be50c2b7aa68782e6c86d24384dc9c2917038295669870c0ef4932227d1b5d5/merged
shm              64M     0   64M   0% /var/lib/docker/containers/a8c7bf6da6c9c3b7eb91a1d0637a804f2c2862bacc5c16de9c51f6d662107d47/mounts/shm
overlay         6.4G  5.7G  359M  95% /var/lib/docker/overlay2/8a730dccb267a048f85a5a4e022e3c6ae0d4b00c857bebaaca1d5d6df335f17f/merged
shm              64M  4.0K   64M   1% /var/lib/docker/containers/8f762e027d2ddd68b3a7644651ae2a0d7459981d93c9439fde80a0258953f4a5/mounts/shm
overlay         6.4G  5.7G  359M  95% /var/lib/docker/overlay2/77d1d1c61975156a5da52781e0ee169d2f0d7d46b501bde49ce4ebc460f5ac0c/merged
shm              64M     0   64M   0% /var/lib/docker/containers/5a8bae00820ed837adede4668e0d39c53bcaddef1fb40fe5d6f2040a17f6b6de/mounts/shm
overlay         6.4G  5.7G  359M  95% /var/lib/docker/overlay2/706f67a7498458ecbd860e4aeb1b130144f1db7335feb61ed89c5d881fb85b16/merged
shm              64M  368K   64M   1% /var/lib/docker/containers/d4130ed7c90a2e4d23e5d4ae1ef89cf274b9198393b8cb601400a2bebfbea5ad/mounts/shm
```

##### ENVIRONMENT
* AWX version: AWX 1.0.6.23
* AWX install method: docker on linux
* Ansible version:  2.6.0
* Operating System: Debian 9.4 x64
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE
Install a new instance of AWX, provision some hosts and playbooks, and wait..

##### EXPECTED RESULTS
/var should not grows as fast as this.

##### ACTUAL RESULTS

/var growing by 1Go every month.

##### ADDITIONAL INFORMATION
Reproduced on 2 distincts environnements.

**Comment by coom** [comment]
@wwitzel3 May I ask you how your pull request will affect this issue ? I see that this issue has been referenced 10 days ago ? Is that a mistake ?

**Comment by matburt** [comment]
This issue is a little vague, what in /var is growing that is surprising?

**Comment by matburt** [comment]
ping?

**Comment by jakemcdermott** [comment]
@coom 

It looks like you're probably building or pulling new container images on a regular basis. If the rate at which your disk utilization is increasing is unacceptable to you, you'll need to remove old docker images after pulling or adding new ones. This is behavior of docker itself and not something particular to awx.

If you have any questions please have a look at the docker documentation for admins, reach out to our community mailing list, or stop by our irc channel on freenode `#ansible-awx`

**Comment by coom** [comment]
Finally found what cause the issue.

There is an AWX logs that keeps growing : 

```bash
root@ansible:/: du -hs /var/lib/docker/containers/d4130ed7c90a2e4d23e5d4ae1ef89cf274b9198393b8cb601400a2bebfbea5ad/d4130ed7c90a2e4d23e5d4ae1ef89cf274b9198393b8cb601400a2bebfbea5ad-json.log
7.4G    /var/lib/docker/containers/d4130ed7c90a2e4d23e5d4ae1ef89cf274b9198393b8cb601400a2bebfbea5ad/d4130ed7c90a2e4d23e5d4ae1ef89cf274b9198393b8cb601400a2bebfbea5ad-json.log
```

It contains some stuffs about AWX :

```bash
root@ansible:/var/lib/docker/containers/d4130ed7c90a2e4d23e5d4ae1ef89cf274b9198393b8cb601400a2bebfbea5ad: tail -2 d4130ed7c90a2e4d23e5d4ae1ef89cf274b9198393b8cb601400a2bebfbea5ad-json.log
{"log":"2019-03-16 07:19:27,118 DEBUG    awx.main.scheduler Starting Scheduler\n","stream":"stderr","time":"2019-03-16T07:19:27.119259491Z"}
{"log":"[2019-03-16 07:19:27,152: INFO/MainProcess] Task awx.main.scheduler.tasks.run_task_manager[a9cba724-6fbd-4a1a-85b5-d68b49d35fb5] succeeded in 0.0648250419763s: None\n","stream":"stderr","time":"2019-03-16T07:19:27.153233112Z"}
root@ansible:/var/lib/docker/containers/d4130ed7c90a2e4d23e5d4ae1ef89cf274b9198393b8cb601400a2bebfbea5ad:
```

Why this log is not flushed/rotated correctly ?

**Comment by ryanpetrello** [comment]
> Why this log is not flushed/rotated correctly ?

Because awx doesn't make any decisions about this for you, especially under native Docker.

If you're using native Docker container, look into https://docs.docker.com/config/containers/logging/configure/ to set up log rotation.

Specifically, check out `max-size` in the `log-opts` at https://docs.docker.com/config/containers/logging/json-file/
