### ISSUE TITLE
Schedule limit value not reported in activity stream on creation

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#2387]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
A schedule that provides a limit does not report the value of the limit in the activity stream in the entry for creation of the schedule. Subsequent edits of the limit field do report it.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Create a schedule that provides `limit` for a JT  of "foobar"

now change it to "barfoo"

Now view activity stream

##### EXPECTED RESULTS

1. Entry for schedule creation containing "foobar"
2. Entry for schedule modification "foobar" -> "barfoo"

##### ACTUAL RESULTS

number 2 is ✅ , in UI:

```json
{
 "extra_data": [
  "{}",
  ""
 ],
 "limit": [
  "foobar",
  "barfoo"
 ]
}
```

number 1 is ❌ , the entry for creation exists, but does not report "foobar"

```json
{
 "description": "every day for 1 time",
 "enabled": true,
 "extra_data": "{}",
 "id": 4,
 "inventory": null,
 "name": "asdffdsfe",
 "rrule": "DTSTART;TZID=America/New_York:20181010T000000 RRULE:FREQ=DAILY;INTERVAL=1;COUNT=1",
 "unified_job_template": "JobTemplate - DetailArt爩-397"
}
```

##### ADDITIONAL INFORMATION

Reported modification of `extra_data` there could be argued to be another minor bug.

**Comment by rebeccahhh** [comment]
Tested by creating a schedule with a limit and the limit is reported in the creation entry of the Activity Stream, this has already been resolved.
ex:
```
{
 "description": "a test to see if limit is in this entry",
 "diff_mode": null,
 "enabled": true,
 "extra_data": "{}",
 "id": 9,
 "inventory": null,
 "job_tags": null,
 "job_type": null,
 "limit": null,
 "name": "rrrrr",
 "rrule": "DTSTART;TZID=America/New_York:20200327T000000 RRULE:FREQ=MINUTELY;INTERVAL=1;COUNT=1",
 "scm_branch": null,
 "skip_tags": null,
 "unified_job_template": "uselessjobtemplate",
 "verbosity": null
}
```
