### ISSUE TITLE
Support an IPv6 only installation

### ISSUE THREAD

**Issue by rhjhunt** [ansible/awx#2388]
##### ISSUE TYPE
 - The ability to install Tower in an IPv6 only infrastructure.

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY

Our organization is running out of IPv4 network addresses and has made the commitment to be IPv6 only.  We depend on Ansible and need the ability for Tower to run in an IPv6 only environment.

**Comment by wenottingham** [comment]
Development notes: 
- as far as known, all components support this at a technical level
- this is a test/fix whack-a-mole scenario
- also includes finding an appropriate IPv6-only cloud environment that can be used as a testbed

**Comment by ryanpetrello** [comment]
cc @wenottingham what's the official state of this?

**Comment by wenottingham** [comment]
I would like to call it tech preview. At the moment verification is running in a specific config? (cc @Spredzy )

**Comment by gamuniz** [comment]
ipv6 has been in for a while closing
