### ISSUE TITLE
Local project not visible in Tower

### ISSUE THREAD

**Issue by mtxd** [ansible/awx#239]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

After creating a local project in `/var/lib/awx/projects/custom_project` I am unable to initialize it via web. Getting 
```
WARNING: There are no available playbook directories in /var/lib/awx/projects. Either that directory is empty, or all of the contents are already assigned to other projects. Create a new directory there and make sure the playbook files can be read by the "awx" system user, or have AWX directly retrieve your playbooks from source control using the SCM Type option above.
```

Content of `/var/lib/awx/projects/custom_project` 
```
ls -la /var/lib/awx/projects/custom_project
total 20
drwxr-xr-x 2 root root 4096 Sep 21 14:03 .
drwxr-xr-x 5 root root 4096 Sep 21 14:15 ..
-rw-r--r-- 1 root root  107 Sep 21 13:26 deploy_iotop.yml
-rw-r--r-- 1 root root  215 Sep 21 13:26 deploy_nginx.yml
-rw-r--r-- 1 root root   55 Sep 21 14:03 README.md
```
awx_manage is running in a docker container as root (default setup from the manual)

A project with 'git' SCM type from https://github.com/ansible/ansible-tower-samples synced successfully.

##### ENVIRONMENT
AWX version: 1.0.0.487

**Comment by matburt** [comment]
See https://github.com/ansible/awx/issues/229

**Comment by mtxd** [comment]
What do you mean by "both containers in the same location" ? Playbooks are resided in the awx-task container.

**Comment by matburt** [comment]
yep, but manual projects need to be available in the web container also to show up in the list results.

OR, manage them in a source control system and the project fetch operation will index them for you.

Manual projects are a bit of a leftover concept from our current non-container based install and we've been phasing out direct support of them for a while.

**Comment by mtxd** [comment]
I see, thanks for explanation. Where should I put them on awx_web container?

**Comment by matburt** [comment]
In the same place

**Comment by suganthanraj** [comment]
change ownership to that file and folder to awx
