### ISSUE TITLE
Job Details not displaying in Firefox 52 ESR

### ISSUE THREAD

**Issue by roostercactus** [ansible/awx#2401]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Recently installed AWX v2.0.0.0 and noticed that the Job Details page for any given job will not display in Firefox 52 ESR.  It (Firefox 52 ESR) worked fine in AWX v1.0.6.  So looks like it's related to the older ESR release of Firefox in the latest AWX.  

All other pages display fine in ESR 52, just not the Job Details page for a job.  I can see the list of jobs...but if I click on a job to view the Details it just sits forever with the spinning "Working" icon popped up in the corner.  I cannot click anything else on the page while the "Working" icon is spinning (to navigate somewhere else).  To get the browser page back I have to reload the main URL of AWX.

I tried with Firefox 60 ESR and that is working okay in latest v2.0.0.0.  I can view the Job Details normally.  But our environment is still on ESR 52 for the time being.
##### ENVIRONMENT
* AWX version: 2.0.0
* AWX install method: docker on linux
* Ansible version:  2.6.5
* Operating System: Linux OEL 7.5 64-bit (RHEL 7 clone)
* Web Browser:  Firefox 52.8.0 ESR 64-bit

##### STEPS TO REPRODUCE

Using Firefox 52 ESR open AWX v2.0.0.0 and try to view the Details of a job.  It tries to open the page but all you get is the "Working" icon spinning and it locks up the page.

##### EXPECTED RESULTS

Using Firefox 52 ESR open AWX v2.0.0.0 and being able to view the Details of a job.  I should be able to view the Job Details for any given job using Firefox 52 ESR.

##### ACTUAL RESULTS

Using Firefox 52 ESR if you try to view the Details of a job it just sits and spins.

##### ADDITIONAL INFORMATION

All other pages in AWX v2.0.0.0 seem to work fine, it's just the Job Details page for any given job that won't open in Firefox ESR 52.

**Comment by wenottingham** [comment]
Is there an error in the browser console?

**Comment by roostercactus** [comment]
Here's what pops up in the console.  I enabled JS errors and warnings.

```
Empty string passed to getElementById().  vendor.5f6ddd740b2188f99155.js:29:32327
Strict-Transport-Security: The connection to the site is untrustworthy, so the specified header was ignored.[Learn More]  413
Strict-Transport-Security: The connection to the site is untrustworthy, so the specified header was ignored.[Learn More]  job_events
```
I'm using a self-signed SSL cert so I thnk the two security errors are probably related to that.

**Comment by roostercactus** [comment]
Closing issue (as per matburt on IRC there will not be a fix).  Will try to get our environment updated to ESR 60.
