### ISSUE TITLE
install.yml inconsistently fails at activating postgres

### ISSUE THREAD

**Issue by AdrianDutu** [ansible/awx#2405]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
I am trying to update to 2.0.1 from 2.0.0. I have deleted awx_web and awx_task containers and images. All the other containers are still there.
When running install.yml sometimes fails with the error below. The behavior is very inconsistent, i can run the playbook once and it fails, and 1 second later works.

`UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: mm_send_fd: sendmsg(2): Broken pipe\r\nmux_client_request_session: send fds failed\r\n", "unreachable": true}`

##### ENVIRONMENT
* AWX version: 2.0.0
* AWX install method: docker on linux
* Ansible version:  2.6.4
* Operating System: CentOS 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Already have a postgres container. This is an update scenario.
2. Run install.yml

##### EXPECTED RESULTS

Playbook finishing

##### ACTUAL RESULTS

Inconsistently fails with error:

`UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: mm_send_fd: sendmsg(2): Broken pipe\r\nmux_client_request_session: send fds failed\r\n", "unreachable": true}`

##### ADDITIONAL INFORMATION
This has not happened while installing fresh.

**Comment by matburt** [comment]
This looks like an ssh problem on your end rather than a problem with the installer.

**Comment by AdrianDutu** [comment]
How is it an SSH problem if a fresh install always works?

**Comment by matburt** [comment]
You tell me, this is an SSH client/server problem:

```Failed to connect to the host via ssh: mm_send_fd: sendmsg(2): Broken pipe\r\nmux_client_request_session: send fds failed```
