### ISSUE TITLE
Using Survey to install yum packages, does not work

### ISSUE THREAD

**Issue by aamarques** [ansible/awx#2409]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

Created a survey to pass variables (pkg name and state) into a playbook that will install packages using yum but doesn't work - it doesn't install.

But if I write another playbook with the values (pkg name and state) hardcoded that package installs.

 
##### ENVIRONMENT
* AWX version: 1.0.7.2
* AWX install method:  docker on linux
* Ansible version:  2.6.2
* Operating System: CentOS Linux release 7.4.1708 (Core)
* Web Browser: Version 69.0.3497.100 (Official Build) (64-bit)

##### STEPS TO REPRODUCE

- Create a Job Template
- Add a survey for two variables: 
  -- p_module (text)  - for the package name 
  -- p_state (multi-choice) - for the state (latest, installed, ...)

- Create a playbook, like this:

-------------- Playbook ---------------
- hosts: hostA
  tasks:
  - name: install "{{ p_module }}"
    yum:
        name: "{{ p_module }}"
        state: "{{ p_state }}"

- Run

Note: I have used notation name=var with the same results.

##### EXPECTED RESULTS

Package installed

##### ACTUAL RESULTS
Using previous playbook with Survey to  install "htop" package and looking at the /var/log/message of destination machine (hostA):

------------ LOG hostA --------------------
Oct 11 12:11:04 localhost systemd: Starting Session 321 of user root.
Oct 11 12:11:05 localhost ansible-setup: Invoked with filter=* gather_subset=['all'] fact_path=/etc/ansible/facts.d gather_timeout=10
Oct 11 12:11:06 localhost ansible-yum: Invoked with allow_downgrade=False name=['htop'] bugfix=False list=None disable_gpg_check=False conf_file=None install_repoquery=True validate_certs=True state=installed disablerepo=None update_cache=False disable_plugin=[] enablerepo=None exclude=None security=False update_only=False enable_plugin=[] installroot=/ skip_broken=False
Oct 11 12:12:13 localhost systemd-logind: Removed session 321.

##### ADDITIONAL INFORMATION
Using the following playbook to install  the same package, works fine.

--------------- Playbook ---------------
- hosts: hotaA
  tasks:
  - name: Install htop
    yum: 
        name: htop 
        state: latest

------------ LOG hostA --------------------
Oct  11 12:42:38 localhost systemd-logind: New session 224 of user root
Oct  11 12:42:50 localhost ansible-yum: Invoked with allow_downgrade=False name=['htop'] bugfix=False list=None disable_gpg_check=False conf_file=None install_repoquery=True validate_certs=True state=latest disablerepo=None update_cache=False disable_plugin=[] enablerepo=None exclude=None security=False update_only=False enable_plugin=[] installroot=/ skip_broken=False
Oct  11 12:42:50 localhost ansible-yum: Invoked with allow_downgrade=False name=['htop'] bugfix=False list=None disable_gpg_check=False conf_file=None install_repoquery=True validate_certs=True state=latest disablerepo=None update_cache=False disable_plugin=[] enablerepo=None exclude=None security=False update_only=False enable_plugin=[] installroot=/ skip_broken=False
Oct  11 12:43:08 localhost yum[31123]: Installed: htop-2.2.0-1.el7.x86_64
Oct  11 12:44:16 localhost systemd-logind: Removed session 224.

The difference is that the second one calls YUM to install
Oct  11 12:43:08 localhost yum[31123]: Installed: htop-2.2.0-1.el7.x86_64

**Comment by aamarques** [comment]
Hi ? Any ideas ?

**Comment by aamarques** [comment]
up

**Comment by ryanpetrello** [comment]
@aamarques,

Are you still encountering this on the latest version of awx (4.0.0)?

**Comment by gamuniz** [comment]
Closing as unresponsive and age of issue.
