### ISSUE TITLE
Postgres service makes persistent volume claim during OpenShift install

### ISSUE THREAD

**Issue by switchboardOp** [ansible/awx#241]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Documentation and inventory file state that "a new ephemeral postgres service will be created", but after running the install playbook the postgres service tries to mount a persistent volume claim.

##### ENVIRONMENT
AWX Version: 1.0.0
Ansible Version: 2.3
Operating System: RHEL 7.3
OpenShift Origin Version: 1.5

##### STEPS TO REPRODUCE
- Configure inventory file for an OpenShift deploy as described in INSTALL.md leaving `pg_hostname` commented out.
- run the install playbook

##### EXPECTED RESULTS
Postgres pod deployed as ephemeral with storage mapped to emptydir

##### ACTUAL RESULTS
Postgres pod deployed with 1Gi persistent volume claim "postgresql"

**Comment by matburt** [comment]
Documentation updated: https://github.com/ansible/awx/commit/55259b4445c1a45d620aa692ece154f0fcde0087
