### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [ansible/awx#2412]
Hello! @ansible   

I wanted to design a logo compatible with ansible for this repository. thus this warehouse can provide a more recognizable view. 

![1](https://user-images.githubusercontent.com/36298335/46824521-bc70ce80-cd99-11e8-9bc2-fd82bc9faae5.jpg)

Readme file view;

![2](https://user-images.githubusercontent.com/36298335/46824539-cd214480-cd99-11e8-9599-994fb3b13d70.png)

Please give feedback if you want to use it. Thanks. Best regards.

**Comment by robynbergeron** [comment]
Hi, @reallinfo  :)

Thanks for taking the time to create this logo and submit a PR for it -- I think it is awesome that you are sharing your skills with our project, and all the other open source projects you have been contributing too. 

However, we already have a logo and accompanying guidelines for this project -- which you can see [here](https://github.com/ansible/awx-logos). Which I guess was not very obvious / easy to find or know about. 

That said -- I do think the idea of showing the logo at the top of the README.md page is an excellent idea, as you displayed in your PR for your logo suggestion. (And also, hey, people would know it has a logo!) So I'm going to close this -- but I did just open an issue (#2413) with a suggestion to display the logo from the logo repository in the readme file. (Which anyone could create a PR for if folks in the community agree it's a good idea, and also suggested that at least documenting the existence of a logo and where it is located is a good idea.)

Thanks for taking the time to lend a hand -- sorry it wasn't more clear that we already had one, but now we know it wasn't obvious 😄 and can fix that!

**Comment by reallinfo** [comment]
You're welcome. you can write me if you need anything else. I hope you can find the logo you wish. Have a nice day!
