### ISSUE TITLE
Unable to Activate AWX Web Container

### ISSUE THREAD

**Issue by ryan012880** [ansible/awx#2417]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Installer failed to activate web container

##### ENVIRONMENT
* AWX version: 2.0.1
* AWX install method: docker on linux
* Ansible version:  2.7.0-1.el7.ans
* Operating System: RHEL7
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Clone the awx git repo and build the awx container images

##### EXPECTED RESULTS
Installer should be able to activate the web container.
TASK [local_docker : Activate AWX Web Container] **********************************************************************************
changed: [localhost]

##### ACTUAL RESULTS

TASK [local_docker : Activate AWX Web Container] **********************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (docker_container) module: register Supported parameters include: api_version, auto_remove, blkio_weight, cacert_path, cap_drop, capabilities, cert_path, cleanup, command, cpu_period, cpu_quota, cpu_shares, cpuset_cpus, cpuset_mems, debug, detach, devices, dns_opts, dns_search_domains, dns_servers, docker_host, domainname, entrypoint, env, env_file, etc_hosts, exposed_ports, force_kill, groups, hostname, ignore_image, image, init, interactive, ipc_mode, keep_volumes, kernel_memory, key_path, kill_signal, labels, links, log_driver, log_options, mac_address, memory, memory_reservation, memory_swap, memory_swappiness, name, network_mode, networks, oom_killer, oom_score_adj, output_logs, paused, pid_mode, privileged, published_ports, pull, purge_networks, read_only, recreate, restart, restart_policy, restart_retries, security_opts, shm_size, ssl_version, state, stop_signal, stop_timeout, sysctls, timeout, tls, tls_hostname, tls_verify, tmpfs, trust_image_content, tty, ulimits, user, userns_mode, uts, volume_driver, volumes, volumes_from, working_dir"}

**Comment by ryan012880** [comment]
Manage to fixed it with:

```# git diff installer/roles/local_docker/tasks/standalone.yml
diff --git a/installer/roles/local_docker/tasks/standalone.yml b/installer/roles/local_docker/tasks/standalone.yml
index 41560b9..9eee52b 100644
--- a/installer/roles/local_docker/tasks/standalone.yml
+++ b/installer/roles/local_docker/tasks/standalone.yml
@@ -111,7 +111,7 @@
       MEMCACHED_PORT: "11211"
       AWX_ADMIN_USER: "{{ default_admin_user|default('admin') }}"
       AWX_ADMIN_PASSWORD: "{{ default_admin_password|default('password') }}"
-    register: awx_web_container
+  register: awx_web_container
 
 - name: Update CA trust in awx_web container
   command: docker exec awx_web '/usr/bin/update-ca-trust'```

**Comment by wenottingham** [comment]
see #2420
