### ISSUE TITLE
Can't Access AWX with SSL Configured

### ISSUE THREAD

**Issue by jariley** [ansible/awx#242]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

I have been able to successfully install and access AWX via http. I wanted to implement SSL for the application and so I created my private key and certificate, then configured the nginx.conf file, and forwarded port 443 from the host to the container. I have the cert files and the nginx.conf mounted into the awx_web image and running nginx -t in the container verifies that it is running successfully. However, I receive a connection closed error whenever I attempt to access the application via https (from an external machine or from the host using https://localhost). Can anyone please assist with determining the issue?

##### STEPS TO REPRODUCE
Create a private key and certificate, then configure the nginx.conf file to listen on 443 and use that cert. Then, run the awx_web container with the cert, key, and nginx.conf mounted and port 443 forwarding from the host to the container. Go to https://yourserver.yourdomain.com and see error message.

##### EXPECTED RESULTS
I expected the page to load via https.

##### ACTUAL RESULTS

I received a connection closed error when I attempted to visit my awx instance via https.

**Comment by matburt** [comment]
Greetings!  See this message on the mailing list: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/awx-project/p5oWivyuGPA/V8vQvWaiAQAJ

**Comment by jariley** [comment]
@matburt The linked correspondance is referencing the host machine receiving the ssl traffic over 443 and then terminating ssl before forwarding the traffic over 8052 for the container to serve up the http site. I am simply trying to open up 443 and have the container itself serve up the SSL site.

**Comment by matburt** [comment]
Then you'll need to maintain your own nginx configuration for the container. In the future when this is implemented I'll probably do it from another container like haproxy so we can map the certificates in in an easy way.
