### ISSUE TITLE
Allow Scale Down of Tower instances from Openshift 

### ISSUE THREAD

**Issue by MikeNald** [ansible/awx#2422]
##### ISSUE TYPE
 - Feature Idea
Allow Scale Down of Tower instances from Openshift 

##### COMPONENT NAME
 - Installer

##### SUMMARY
Currently Tower 3.3 on Openshift can be scaled editing StateFulSet and setting replica: X inside the yaml or using oc oc scale --replicas=x sts ansible-tower
This change trigger the deployment of a new POD and since the container ansible-tower-web will execute /usr/bin/launch_awx_task.sh as start-up command Tower will be scaled automatically adding a new instance .
ScaleDown is not working since the shell script is not managing the deprovisioning. 
Calling "awx-manage deprovision_instance —-hostname=xxxx" will delete the instance inside the instance_group.

**Comment by ryanpetrello** [comment]
@MikeNald this issue tracker is for the open source AWX project; if you need help with Ansible Tower, please contact a Red Hat support representative.

**Comment by Klaas-** [comment]
Just in case anyone else comes across this; this is working as of awx 3.0.1. It just takes a couple of minutes for the instance to disappear from UI.
