### ISSUE TITLE
Deploying windows app

### ISSUE THREAD

**Issue by levissfuture** [ansible/awx#2423]
##### ISSUE TYPE
Bad argument passed to host

##### SUMMARY
Bad argument passed to host when i use this format of arguments:
win_package:
        path: \\test\test\Skype8.exe
        product_id: Skype_is1
        arguments:
         -/VERYSILENT
         -/SUPPRESSMSGBOXES
         -/LOG
         -/NORESTART

at the host machine it seems like : 
"C:\Windows\TEMP\is-SEMMV.tmp\Skype8.tmp" /SL5="$60186,61885148,404480,\\test\test\Skype8.exe" **-**/VERYSILENT **-**/SUPPRESSMSGBOXES **-**/LOG **-**/NORESTART

when i use : arguments: ['/VERYSILENT','/SUPPRESSMSGBOXES','/LOG','/NORESTART']
all working fine

##### ENVIRONMENT
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

 host: Windows 7

##### STEPS TO REPRODUCE

---
- name: Installing software to PC
  hosts: windows
  gather_facts: false

  tasks:
    - name: Install Skype 8
      win_package:
        path: \\test\test\Skype8.exe
        product_id: Skype_is1
        arguments:
         -/VERYSILENT
         -/SUPPRESSMSGBOXES
         -/LOG
         -/NORESTART
      register: Skype8_Install
      become: yes
      become_method: runas
      become_user: SYSTEM
...

**Comment by wenottingham** [comment]
This appears to be an Ansible issue, not an AWX issue.

Ansible issues should be filed at https://github.com/ansible/ansible/.
