### ISSUE TITLE
Deprecate ask_* fields shown in the job serialization

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#2427]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Inside of the job serialization, mark these files for eventual removal:

```json
            "ask_diff_mode_on_launch": false,
            "ask_variables_on_launch": false,
            "ask_limit_on_launch": false,
            "ask_tags_on_launch": false,
            "ask_skip_tags_on_launch": false,
            "ask_job_type_on_launch": false,
            "ask_verbosity_on_launch": false,
            "ask_inventory_on_launch": false,
            "ask_credential_on_launch": false,
```

(9 fields)

The implementation of these looks like:

https://github.com/ansible/awx/blob/5910b8c5627d46ad52a41801c6998322973c650e/awx/main/models/jobs.py#L548-L552

I believe there is a good case to say that these don't provide any real value. They just add confusion.

##### ADDITIONAL INFORMATION

job serialization in list:

https://gist.github.com/AlanCoding/f0ac97a46c6388285d26e47894f97279

It takes 88 lines for the job's serialization, so 9 lines, about 10% isn't nothing.

@ryanpetrello since these have been around for a while, I think there's a good case to mark them as deprecated, but still wait until API v3 to actually remove them. Interested in your thoughts on that.

**Comment by itdependsnetworks** [comment]
If you remove them, are you also removing the functionality they provide? If so can you explain how.

**Comment by AlanCoding** [comment]
What functionality is being used? If there is any valid use case I would really like to know. The obvious interpretation of the field would be that if you relaunch the job, then `ask_diff_mode_on_launch` being true would set an expectation that the user provides `diff_mode` on relaunch, and that the server uses that value. This might have been true for `variables` a long time ago in the past, but it is not the case now.

Alternatively, you might interpret it to mean that the JT prompted for the value at the time that the job was launched. This may be true most of the time, but is not reliable, and we have other means of getting this information now.

**Comment by itdependsnetworks** [comment]
Q: What functionality is being used?
A. I am using `ask_variables_on_launch`

**Comment by AlanCoding** [comment]
That would remain usable on the job template as always, the issue here is that in the API design, those fields are duplicated on the job for no reason, and I would like to schedule those for eventual removal.
