### ISSUE TITLE
WF Template resets ask_variables_on_launch

### ISSUE THREAD

**Issue by itdependsnetworks** [ansible/awx#2428]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

You can currently only set `ask_variables_on_launch` via an API. However, once you submit via the UI, it removes that.

##### ENVIRONMENT
* AWX version: AWX 1.0.6.16  >
* AWX install method: docker
* Ansible version:  2.5.5
* Operating System: Ubuntu
* Web Browser: Chrome/Firefox/Safari

##### STEPS TO REPRODUCE

* Create a workflow
* path it via API with `ask_variables_on_launch` and set to true
* View workflow setting for `ask_variables_on_launch` and see it is true
* Go back to workflow and click submit
* View workflow setting for `ask_variables_on_launch` and see it is false

##### EXPECTED RESULTS

UI to have no impact on anything else

##### ACTUAL RESULTS

UI resests `ask_variables_on_launch`

**Comment by matburt** [comment]
You're running a fairly old version of AWX and I'm unable to reproduce on the latest version. Reopen if found against 2.X+

**Comment by itdependsnetworks** [comment]
@matburt how do I reopen? 

It was found using same steps in <  AWX 2.0.1  >, though I guess I said `submit`, where I should have said `save`. Should be reproducible on your side with little effort, if not, please let me know what you are seeing. 


It's a bit blury on the gif, but I think you can still make out that it went from true to false. 
https://gph.is/2AuTI5a

**Comment by wenottingham** [comment]
From the GIF, you are patching in the API while the UI edit page is open. The UI will not track API updates that happen after you open the edit page; this is not something we have a mechanism to fix at this point.

**Comment by itdependsnetworks** [comment]
@wenottingham I don’t think that is the issue, that was just the demonstration, can you leave this open until it is confirmed?

**Comment by itdependsnetworks** [comment]
Confirmed, if you rewatch the GIF, there is no patching being done, I simply show that it is true (via the UI), and then returns to false (via the UI). Can you @matburt or @wenottingham can you please reopen the issue?

**Comment by mabashian** [comment]
UI will now use a PATCH instead of a PUT when updating a workflow job template.  Corresponding commit is [here](https://github.com/ansible/awx/pull/2745/commits/1d7d2820fd70946fa978706880daee20b288ddb4)
