### ISSUE TITLE
Cannot activate the AWX Web container

### ISSUE THREAD

**Issue by Raghuveer123** [ansible/awx#2433]
TASK [local_docker : Activate AWX Web Container] ******************************************************************************************************************************************************************************************************************************
task path: /home/awx/installer/roles/local_docker/tasks/standalone.yml:79
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating container: unhashable type: 'list'"}
        to retry, use: --limit @/home/awx/installer/install.retry
Please help out me with this issue,

I cloned this awx project and ran ansible-playbook -i inventory install.yaml and got above error.

**Comment by ghost** [comment]
It looks like the error is in the *installer/roles/local_docker/tasks/standalone.yml* file if you don't specify a project directory the expression concatenating the volumes: for awx_web and awx_task containers.

Specifying *both* *project_data_dir* *and ca_trust_dir* allows you to continue, but still fails on my CentOS.

**Comment by thulle** [comment]
Got this on Ubuntu 18.04 too, but differing from gyorgynadabans experience is that specifying both project_data_dir and ca_trust_dir got everything up and running.

**Comment by gstorme** [comment]
Same here on Debian 9, local docker install.  
Uncommented the project_data_dir & ca_trust_dir in the inventory file, and the playbook continues.

**Comment by ghost** [comment]
@gstorme That solved it for me too.

**Comment by RoKondo** [comment]
it solved for me on a CentOS 7 (just had to solve a small conflict with nginx)

**Comment by ramuskay** [comment]
Ok for me too !

**Comment by jacobgarder** [comment]
Thats solved it for me too (RHEL 7.5).

**Comment by dannyhimself** [comment]
Also solves for Ubuntu 16.04

**Comment by wenottingham** [comment]
Related to #2156  ?

**Comment by wenottingham** [comment]
Assumption: dup of #2418 , closing.
