### ISSUE TITLE
Deleting the last Project on a paginated Page causes a 404 Error

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2444]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Deleting the last Project on a paginated Page causes a 404 Error

##### ENVIRONMENT
* AWX version: 2.0.1
* Operating System: macOS
* Web Browser: Firefox and Chrome

##### STEPS TO REPRODUCE

1. Create 101 Projects
2. Set the Pagination view to 100
3. Navigate to the second page of results
4. Delete the 101st Project

##### EXPECTED RESULTS

1st Page of 100 results returned

##### ACTUAL RESULTS

404 Modal

##### ADDITIONAL INFORMATION

![pagination](https://user-images.githubusercontent.com/12446869/46980587-0233dc80-d0a3-11e8-8ca2-57dd3745d31f.gif)

**Comment by jlmitch5** [comment]
I attempted to reproduce this and was able to delete the first item of the second pagination page with no problem.  moving to needs_test for rechecking

**Comment by dsesami** [comment]
This still occurs in `devel` @jlmitch5 

I used towerkit to produce 101 projects, then set the view to view 100 per page, then tried to delete the second page project. Let me know if you need help reproducing.

This is with latest awx:
![screenshot from 2018-12-06 12-58-24](https://user-images.githubusercontent.com/19942822/49602711-226f7180-f957-11e8-89e7-dace097b78f0.png)

**Comment by dsesami** [comment]
this is broken for credentials as well w/ the 21st credential which causes pagination. It was also broken for groups in the past, though that was fixed. It seems like this is a bit of copy/pasted code, which needs to be identified and fixed for all relevant resources in AWX.

**Comment by unlikelyzero** [comment]
retest

**Comment by unlikelyzero** [comment]
stub needed

**Comment by akus062381** [comment]
issue has been fixed and stubs added.
