### ISSUE TITLE
[WIP] User receives error modal if attempting to navigate to a Project list before logging in

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2447]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
User receives error modal "Failed to get config. GET returned status: status: undefined" if attempting to navigate to a Project list before logging in

##### ENVIRONMENT
* AWX version: 2.0.1
* Operating System: MacOS
* Web Browser: Firefox 62.0.3

##### STEPS TO REPRODUCE

1. Log in to Projects view and wait for session to end
2. Log in by URL like: /#/projects?project_search=page_size:100;order_by:name;scm_type__icontains_DEFAULT:git

##### EXPECTED RESULTS

Navigate to the login screen without error

##### ACTUAL RESULTS

Navigates to the login screen with an Error Modal "Failed to get config. GET returned status: status: undefined"

##### ADDITIONAL INFORMATION
<img width="1298" alt="screen shot 2018-10-15 at 6 27 44 pm" src="https://user-images.githubusercontent.com/12446869/46981936-55f4f480-d0a8-11e8-89d7-3e8bfecd3a2b.png">

**Comment by jlmitch5** [comment]
I was not able to reproduce this on timeout as the reproduction scenario mentions--it just redirects to /#/login as soon as you click enter with /#/projects... in the url.  Moving back over to test to see if the issue can be reliably reproduced.

**Comment by unlikelyzero** [comment]
I saw this one again. I'm going to keep it open and assigned to me while I try to find repeatable steps

**Comment by unlikelyzero** [comment]
I saw this once more but have been unable to reproduce. Closing as cannot reproduce for now
