### ISSUE TITLE
OperationalError: could not translate host name "postgres" to address: Name or service not known

### ISSUE THREAD

**Issue by b3rgman** [ansible/awx#2453]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

  - UI
 

##### SUMMARY

When connecting to awx server, I receive a message that states a server error has occured.
##### ENVIRONMENT
* AWX version: 1.0.8
* AWX install method: docker on linux
* Ansible version:  
* Operating System: CentOS 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Access link to server to login
##### EXPECTED RESULTS

Login page to be presented in UI
##### ACTUAL RESULTS

Receive an error that states Server error has occured
##### ADDITIONAL INFORMATION

Seeing this at the end of logs for awx_web

    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: could not translate host name "postgres" to address: Name or service not known
[pid: 131|app: 0|req: 30/62] 10.252.65.162 () {42 vars in 1404 bytes} [Tue Oct 16 14:46:35 2018] GET / => generated 3762 bytes in 59 msecs (HTTP/1.1 500) 4 headers in 148 bytes (1 switches on core 0)
xxx.xxx.xxx.xxx - - [16/Oct/2018:14:46:35 +0000] "GET / HTTP/1.1" 500 3762 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" "-"
RESULT 2
OKREADY
2018-10-16 14:47:03,714 ERROR    Error trying to receive messages: [Errno -2] Name or service not known
2018-10-16 14:47:33,835 ERROR    Error trying to receive messages: [Errno -2] Name or service not known
RESULT 2
OKREADY
2018-10-16 14:48:03,969 ERROR    Error trying to receive messages: [Errno -2] Name or service not known
2018-10-16 14:48:34,073 ERROR    Error trying to receive messages: [Errno -2] Name or service not known
RESULT 2
OKREADY
2018-10-16 14:49:04,175 ERROR    Error trying to receive messages: [Errno -2] Name or service not known

**Comment by wenottingham** [comment]
This reads as you have misinstalled and have not properly configured the database connection.

This is not an AWX issue; you may have better luck on the awx-project email list or ansible-awx IRC channel/.
