### ISSUE TITLE
Management Jobs and SCM Updates have a 'Slice job undefined/undefined' tag in the Jobs list

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2463]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Management Jobs and SCM Updates have a 'Slice job undefined/undefined' tag in the Jobs list

##### ENVIRONMENT
* AWX version: 2.0.1

##### STEPS TO REPRODUCE

1. Run a SCM Update for a Project which contains a Sliced Job Template
2. Navigate to the Jobs view list

or Run a Management Jobtype

##### EXPECTED RESULTS

No tag

##### ACTUAL RESULTS

tag with 'Slice job undefined/undefined'

##### ADDITIONAL INFORMATION

![image 2018-10-16 at 9 11 00 pm](https://user-images.githubusercontent.com/12446869/47056036-814f1080-d188-11e8-9618-15fd802a7242.png)

**Comment by kialam** [comment]
👀 @AlanCoding Do you see in that screenshot a `Slice job 0/15`? That doesn't look right.

**Comment by AlanCoding** [comment]
At some time, I did push code that gave the undefined/undefined bug. After some finagling I got it to go away, but that's even before your changes. I would definitely say this needs re-testing.

**Comment by kialam** [comment]
@unlikelyzero I am unable to recreate this issue. I'm going to move this back to needs_test.

**Comment by unlikelyzero** [comment]
@kialam the 0/15 is what appears when this happens: https://github.com/ansible/awx/issues/2464 It's possible that any SJT which fails to run will appear as 0/slice.

I'll redeploy with the latest feature branch. Assigning this to myself to retest.
