### ISSUE TITLE
If a SJT is converted from a JT and the JT version is relaunched, it fails semi-gracefully

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2464]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
If a SJT is converted from a JT and the JT version is relaunched, it fails with negative index errors

##### ENVIRONMENT
* AWX version:2.0.1

##### STEPS TO REPRODUCE

1. Create a JT with a slice of 1
2. Run job
3. Convert JT to SJT by increasing slice count.
4. Run the original JT from the Jobs List view

##### EXPECTED RESULTS

Unable to launch job

##### ACTUAL RESULTS

Job fails gracefully (although the description could be improved)

##### ADDITIONAL INFORMATION

```Traceback (most recent call last): File "/lib/python2.7/site-packages/awx/main/tasks.py", line 939, in run File "/lib/python2.7/site-packages/awx/main/tasks.py", line 1254, in build_args File "/lib/python2.7/site-packages/awx/main/tasks.py", line 810, in build_inventory File "/lib/python2.7/site-packages/awx/main/models/inventory.py", line 247, in get_script_data File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 269, in __getitem__ "Negative indexing is not supported." AssertionError: Negative indexing is not supported. ```
![screen shot 2018-10-16 at 9 34 10 pm](https://user-images.githubusercontent.com/12446869/47056619-3f739980-d18b-11e8-9d84-b109f372e73b.png)

**Comment by AlanCoding** [comment]
I'm inclined to return a 400 error in this case @matburt does that sound sufficient to you?

The expected behavior is too non-obvious to me.

**Comment by AlanCoding** [comment]
Good find, this should be addressed in the PR now. I didn't go out of my way to make it return a 400 error, but an unrelated fix results in it relaunching in a non-split state. That seems good-enough to me.

IMO, sharding shouldn't really be considered with regards to prompting/permissions. There's no _permissions_ problem with someone relaunching a job from the old pre-shard state, and we need to be _really_ particular about respecting the shard parameters on relaunch for other jobs. So I say I'm happy with this.

**Comment by AlanCoding** [comment]
Link fix https://github.com/ansible/awx/pull/2792

**Comment by unlikelyzero** [comment]
Verified the following cases:

- Launch a JT which was converted from a SJT on the SJT Job Result view. Receive appropriate error
- Launch a JT which was converted from a SJT on the Jobs List view. Receive appropriate error
- Launch a joblet which was part of a SJT which was converted to a SJT on the Jobs List view to success
- Launch a SJT which was converted from a JT which was converted from a SJT but with a different slice count. Receive appropriate error
- Launch a SJT which was converted from a JT which was converted from a SJT but uses the same exact slice count. Success
