### ISSUE TITLE
Insufficient Page Authorization

### ISSUE THREAD

**Issue by vikash5507** [ansible/awx#2466]
Hi,

I am actively using AWX for non-prod deployment in my team. But few concerns were raised by our security team. Kindly look into these.

An admin user can view pages and UI items that are restricted to other roles such as "System Administrator" and "System Auditor".

- After login, JSON parameters in the body of the server response can be modified to gain access to restricted screens and functionalities, as shown in the HTTP Request and Response below:

**HTTP Request:**
GET /api/v2/me/ HTTP/1.1
Host: some_hostName
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101
Firefox/61.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://hostName/
Authorization: Token 78ae6f5bae181e0280cfcb4a92fb854880e950c7
X-Auth-Token: Token 78ae6f5bae181e0280cfcb4a92fb854880e950c7
Cookie: sessionExpired=false; lastPath=%2Fusers%2F72; current_user=%7B%7D; token=%
2278ae6f5bae181e0280cfcb4a92fb854880e950c7%22; token_expires=2018-09-19T10%3A50%
3A46.838012Z; userLoggedIn=true
DNT: 1
Connection: close

**Original HTTP Response:**
HTTP/1.1 200 OK
Server: nginx/1.12.2
Date: Wed, 19 Sep 2018 10:20:53 GMT
Content-Type: application/json
Content-Length: 840
Connection: close
X-API-Time: 0.023s
X-API-Total-Time: 0.031s
Allow: GET, HEAD, OPTIONS
Content-Language: en
Vary: Accept, Accept-Language, Cookie
Auth-Token-Timeout: 1800
X-API-Node: awx
Strict-Transport-Security: max-age=15768000
{"count":1,"next":null,"previous":null,"results":[{"id":91,"type":"user","url":"/api/
v2/users/91/","related":{"admin_of_organizations":"/api/v2/users/91/
admin_of_organizations/","organizations":"/api/v2/users/91/organizations/","roles":"/
api/v2/users/91/roles/","access_list":"/api/v2/users/91/access_list/","teams":"/api/
v2/users/91/teams/","credentials":"/api/v2/users/91/
credentials/","activity_stream":"/api/v2/users/91/activity_stream/","projects":"/api/
v2/users/91/projects/"},"summary_fields":{"user_capabilities":
{"edit":true,"delete":false}},"created":"2018-09-19T08:49:10.856569Z","username":"adi
tjain","first_name":"Aditya","last_name":"Jain","email":"aditjain@something.com","is_super
user":false,"is_system_auditor":false,"ldap_dn":"cn=jain\\, aditya,ou=users,ou=ap
region,dc=company_name,dc=com","external_account":"ldap","auth":[]}]}

**Modified HTTP Response:**
  HTTP/1.1 200 OK
  Server: nginx/1.12.2
  Date: Wed, 19 Sep 2018 10:20:53 GMT
  Content-Type: application/json
  Content-Length: 840
  Connection: close
  X-API-Time: 0.023s
  X-API-Total-Time: 0.031s
  Allow: GET, HEAD, OPTIONS
  Content-Language: en
  Vary: Accept, Accept-Language, Cookie
  Auth-Token-Timeout: 1800
  X-API-Node: awx
  Strict-Transport-Security: max-age=15768000
  {"count":1,"next":null,"previous":null,"results":[{"id":91,"type":"user","url":"/api/
  v2/users/91/","related":{"admin_of_organizations":"/api/v2/users/91/
  admin_of_organizations/","organizations":"/api/v2/users/91/organizations/","roles":"/
  api/v2/users/91/roles/","access_list":"/api/v2/users/91/access_list/","teams":"/api/
  v2/users/91/teams/","credentials":"/api/v2/users/91/
  credentials/","activity_stream":"/api/v2/users/91/activity_stream/","projects":"/api/
  v2/users/91/projects/"},"summary_fields":{"user_capabilities":
  {"edit":true,"delete":false}},"created":"2018-09-19T08:49:10.856569Z","username":"adi
  tjain","first_name":"Aditya","last_name":"Jain","email":"aditjain@something.com","is_super
  user":true,"is_system_auditor":true,"ldap_dn":"cn=jain\\, aditya,ou=users,ou=ap
  region,dc=company_name,dc=com","external_account":"ldap","auth":[]}]}

- The notifications functionality is successfully accessed and notification templates were modified

- Similarly, the 'is_superuser' parameter can be forcibly set to 'true' to view UI items and screens restricted to system administrators. However, the functionality cannot be performed as server side validation has been implemented.
 
These concerns are very important for our team. If you need more information, Please let me know.

**Comment by wenottingham** [comment]
Just to be clear: you're MITM-ing the server response to the UI?

**Comment by wenottingham** [comment]
This is not an issue.

The UI acts based on the return from the API; if it authenticates to the API and recieves a response that claims the user is a superuser, it will act accordingly and show 'edit' screens for items the user has permission to view. 

However, these screens, even in this mode, will not show information the user cannot already retrieve from the API, and will not actually commit changes (as that goes through the API).

If you are able to make *and save* changes, feel free to reopen this.

**Comment by ryanpetrello** [comment]
@vikash5507

In the future, if you encounter what you perceive to be a security-related bug, **please** follow our guidelines for responsible disclosure of security issues:

![kapture 2018-10-17 at 9 45 46](https://user-images.githubusercontent.com/214912/47090768-84cab200-d1f1-11e8-922c-bc9c213ded72.gif)
