### ISSUE TITLE
Cross Site Websocket Hijacking

### ISSUE THREAD

**Issue by vikash5507** [ansible/awx#2467]
Hi,

This is our third security concern. You can find previous ones here:
https://github.com/ansible/awx/issues/2466
https://github.com/ansible/awx/issues/2468

The application utilizes websockets for bidirectional communication and does not verify the Origin of the HTTP Upgrade request being originated thus resulting in a successful connection from an external domain.

**HTTP Request:**
GET http://some_hostName/websocket/ HTTP/1.1
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
like Gecko) Chrome/68.0.3440.106 Safari/537.36
Upgrade: websocket
Origin: http://attacker.com/pwn
Sec-WebSocket-Version: 13
Accept-Language: en-US,en;q=0.9
Cookie: -- omitted for brevity -- Sec-WebSocket-Key: IJZdry7VZUM8mi8zfarfog== Content-Length: 0
Host: some_hostName

**HTTP Response:**
HTTP/1.1 101 Switching Protocols
Server: nginx/1.12.2
Date: Wed, 19 Sep 2018 11:45:50 GMT
Connection: upgrade
Upgrade: WebSocket
Sec-WebSocket-Accept: Hdpc5WsCNIVoiC3y4xkAoZBV+Gs=

**Comment by ryanpetrello** [comment]
@vikash5507

In the future, if you encounter what you perceive to be a security-related bug, **please** follow our guidelines for responsible disclosure of security issues:

![kapture 2018-10-17 at 9 45 46](https://user-images.githubusercontent.com/214912/47090768-84cab200-d1f1-11e8-922c-bc9c213ded72.gif)

We believe this is not a valid security issue - please take a look at my comment on the related issue you filed here:  
https://github.com/ansible/awx/issues/2468#issuecomment-430648248
