### ISSUE TITLE
WebSocket Requires No Authentication 

### ISSUE THREAD

**Issue by vikash5507** [ansible/awx#2468]
Hi,

This is our second security concern. You can find previous ones here:
https://github.com/ansible/awx/issues/2466
https://github.com/ansible/awx/issues/2467

Please look into these.

The websocket does not require authentication to initiate a connection. WebSockets do not handle authentication, instead normal application authentication mechanisms apply, such as cookies, HTTP Authentication or TLS authentication

**Original HTTP Request:**
GET http://some_hostName/websocket/ HTTP/1.1
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
like Gecko) Chrome/68.0.3440.106 Safari/537.36
Upgrade: websocket
Origin: some_hostName.com
Sec-WebSocket-Version: 13
Accept-Language: en-US,en;q=0.9
Cookie: token=%2281d1dae9f4c31c226f00f216e7c0f4e9a7041441%22;
token_expires=2018-09-19T12%3A13%3A31.774171Z; userLoggedIn=true;
sessionExpired=false; current_user=%7B%22id%22%3A94%2C%22type%22%3A%22user%22%2C%
22url%22%3A%22%2Fapi%2Fv2%2Fusers%2F94%2F%22%2C%22related%22%3A%7B%
22admin_of_organizations%22%3A%22%2Fapi%2Fv2%2Fusers%2F94%2Fadmin_of_organizations%2F
%22%2C%22organizations%22%3A%22%2Fapi%2Fv2%2Fusers%2F94%2Forganizations%2F%22%2C%
22roles%22%3A%22%2Fapi%2Fv2%2Fusers%2F94%2Froles%2F%22%2C%22access_list%22%3A%22%
2Fapi%2Fv2%2Fusers%2F94%2Faccess_list%2F%22%2C%22teams%22%3A%22%2Fapi%2Fv2%2Fusers%
2F94%2Fteams%2F%22%2C%22credentials%22%3A%22%2Fapi%2Fv2%2Fusers%2F94%2Fcredentials%2F
%22%2C%22activity_stream%22%3A%22%2Fapi%2Fv2%2Fusers%2F94%2Factivity_stream%2F%22%2C%
22projects%22%3A%22%2Fapi%2Fv2%2Fusers%2F94%2Fprojects%2F%22%7D%2C%22summary_fields%
22%3A%7B%22user_capabilities%22%3A%7B%22edit%22%3Atrue%2C%22delete%22%3Afalse%7D%7D%
2C%22created%22%3A%222018-09-19T11%3A43%3A31.598762Z%22%2C%22username%22%3A%
22aditjain%22%2C%22first_name%22%3A%22Aditya%20(c)%22%2C%22last_name%22%3A%22Singh%
22%2C%22email%22%3A%22aditjain%40visa.com%22%2C%22is_superuser%22%3Afalse%2C%
22is_system_auditor%22%3Afalse%2C%22ldap_dn%22%3A%22cn%3Djain%5C%5C%2C%20aditya%20
(c)%2Cou%3Dusers%2Cou%3Dap%20region%2Cdc%3Dvisa%2Cdc%3Dcom%22%2C%22external_account%
22%3A%22ldap%22%2C%22auth%22%3A%5B%5D%7D
Sec-WebSocket-Key: IJZdry7VZUM8mi8zfarfog==
Content-Length: 0
Host: some_hostName

**HTTP Response:**
HTTP/1.1 101 Switching Protocols
Server: nginx/1.12.2
Date: Wed, 19 Sep 2018 11:45:50 GMT
Connection: upgrade
Upgrade: WebSocket
Sec-WebSocket-Accept: Hdpc5WsCNIVoiC3y4xkAoZBV+Gs=

**HTTP Request without cookies:**
GET http://some_hostName/websocket/ HTTP/1.1
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
like Gecko) Chrome/68.0.3440.106 Safari/537.36
Upgrade: websocket
Origin: http://attacker.com/pwn
Sec-WebSocket-Version: 13
Accept-Language: en-US,en;q=0.9
Sec-WebSocket-Key: IJZdry7VZUM8mi8zfarfog==
Content-Length: 0
Host: some_hostName

**HTTP Response:**
HTTP/1.1 101 Switching Protocols
Server: nginx/1.12.2
Date: Wed, 19 Sep 2018 11:53:48 GMT
Connection: upgrade
Upgrade: WebSocket
Sec-WebSocket-Accept: Hdpc5WsCNIVoiC3y4xkAoZBV+Gs=

**Remediation Recommendations**
Enforce authentication controls for all websocket connections.

**Comment by ryanpetrello** [comment]
@vikash5507

In the future, if you encounter what you perceive to be a security-related bug, **please** follow our guidelines for responsible disclosure of security issues:

![kapture 2018-10-17 at 9 45 46](https://user-images.githubusercontent.com/214912/47090768-84cab200-d1f1-11e8-922c-bc9c213ded72.gif)

It _is_ true that an _unauthenticated_ `Upgrade` request is allowed (even from a third party host that doesn't match the `Origin` header):

```
GET http://some_hostName/websocket/ HTTP/1.1
Connection: Upgrade
...
```

```
HTTP/1.1 101 Switching Protocols
...
```

However, this isn't the whole story.  _Just because_ you get back an `HTTP 101`, it doesn't mean awx will start sending you messages.

The way our websocket system works is that it's bidirectional, and based on topic subscriptions:

1.  When a user logs in, our login system sets a special cookie which contains a CSRF token.  This cookie is only set on valid logins, and is not readable by third party websites.

![image](https://user-images.githubusercontent.com/214912/47091962-f0ae1a00-d1f3-11e8-9a5e-cae120ddef22.png)

2. The user establishes a websocket session via an initial `Connection: Upgrade` request.  If they are logged in, they receive a message that contains `accept: true`.  Unauthenticated users will see `accept: false`.

![image](https://user-images.githubusercontent.com/214912/47091997-04598080-d1f4-11e8-8582-64398791071b.png)

3. The user sends a message containing desired topics (e.g., job status changes, streaming playbook event data used to render the Job Details view), and that message **must** contain the cross-origin token from their cookie.  This token **must** be provided on **every** topic subscription request.

![image](https://user-images.githubusercontent.com/214912/47092012-0ae7f800-d1f4-11e8-87ad-fbee80f681ba.png)

3.  If the subscription message _does not contain_ a CSRF token, or that token is *incorrect* for the current session, awx will send back `{"error": "access denied to channel"}`, and will not honor the requested topic subscription.  These incidents are also recorded in awx's log:

![image](https://user-images.githubusercontent.com/214912/47092850-e7be4800-d1f5-11e8-8dc5-b47246fd0e55.png)

![image](https://user-images.githubusercontent.com/214912/47092869-f1e04680-d1f5-11e8-9c92-23f830ad01b8.png)

4.  If the subscription message **does** contain a valid CSRF token, subscription will succeed, and messages intended for that user will be sent to them as they are published.

All of is all implemented here:

https://github.com/ansible/awx/commit/af84b25726326842d3e6a4b9f9de5e670945d070

If you find that any of this is *not* working as described here, **please** follow our guidelines (https://www.ansible.com/security) for disclosure of security issues and contact us directly via `security@ansible.com`
