### ISSUE TITLE
Normal installation of awx

### ISSUE THREAD

**Issue by Neurozone** [ansible/awx#2469]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - Installer

##### SUMMARY
How can we have a normal installation of awx ?
I.E without this shitty docker thing.
Maybe rpm or just tarball ?

##### ADDITIONAL INFORMATION
Don't have any docker or kurbernetes at disposition

**Comment by wilmardo** [comment]
See #882 there are no plans to support this for AWX. 

PS. Docker is awesome 🐳

**Comment by Neurozone** [comment]
> 
> 
> See #882 there are no plans to support this for AWX.
> 
> PS. Docker is awesome whale

Ho ok.
So sad for this project.
It will never be good with only docker image.
Thanks for you answer.
