### ISSUE TITLE
Celery in error loop

### ISSUE THREAD

**Issue by skunkr** [ansible/awx#2470]
##### ISSUE TYPE
 - Celery Erros

##### COMPONENT NAME

 - Installer

##### SUMMARY
Hi,
After a PgSQL docker non-clean restart , celery conatiner remains in a loop error:

```
jango.db.utils.ProgrammingError: relation "main_instance" does not exist
--
  | LINE 1: SELECT (1) AS "a" FROM "main_instance" WHERE "main_instance"...
```

UI is continuously showing: "AWX is currently upgrading"

I do not have a backup/export of the PgSQL, which by the way it runs as a docker in Openshift too... 

Is there a way that I can follow to pass over this error so I will not lose the ansible configured content ?
Thank you very much !

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by matburt** [comment]
`AWX version: X.Y.Z`

Please provide this information.

**Comment by skunkr** [comment]
Thank you very much for reply !
I am using the "latest" tag of the docker image: "ansible/awx_web:latest", and I am not sure how could I find the running version since it is in a continuous  "upgrading" loop, version not being printed at the moment in the UI.
I have tried to search through inside the docker container for a VERSION file,  but just cant find it.
Any recommendation for fixing this loop issue ?
Thank you very much !

**Comment by skunkr** [comment]
Hi,
Any thoughts on this issue ?
Thank you,  have a nice day !

**Comment by ryanpetrello** [comment]
@skunkr we've made some notable changes to how we run playbooks in the background in newer awx versions (including no longer using the celery library).  Please give the latest awx (3.0.0) a shot and reopen if you're still having issues.

**Comment by skunkr** [comment]
Thank you very much Ryan !
