### ISSUE TITLE
AWX / Tower Container does not generate UUID file

### ISSUE THREAD

**Issue by dnguyen9** [ansible/awx#2473]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
UUID is not created for AWX Container deployment when sending the logs. According to the redhat KB (3228651), UUID is generated by python  and stored on  '/etc/tower/conf.d/ha.py' as a SYSTEM_UUID variable.

##### ENVIRONMENT
* AWX version: 2.0.1
* AWX install method: openshift,
* Ansible version:  2.6.5
* Operating System: RHEL7
* Web Browser: Chrome

##### EXPECTED RESULTS

Deploy AWX as you normally would and configure Logging to 'splunk'. 

{"cluster_host_id": "awx-3-pcjjl", "level": "DEBUG", "tower_uuid": "**XXXX_YYYY_ZZZZ**", "@timestamp": "2018-10-17T13:35:32.302Z", "host": "awx-3-pcjjl", "logger_name": "awx", "message": "AWX Connection Test", "type": "splunk"} |  

##### ACTUAL RESULTS

{"cluster_host_id": "awx-3-pcjjl", "level": "DEBUG", "tower_uuid": "", "@timestamp": "2018-10-17T13:35:32.302Z", "host": "awx-3-pcjjl", "logger_name": "awx", "message": "AWX Connection Test", "type": "splunk"} |  

##### ADDITIONAL INFORMATION

information. -->

**Comment by matburt** [comment]
This is a bit of a legacy field left over from our old HA system. It looks like you're running in k8s or openshift you should use the cluster_host_id to aid in cluster identification.
