### ISSUE TITLE
Sliced job badge for workflow jobs

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#2479]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
The API is now providing a field for workflow jobs `is_slicked_job`, which is true/false.

This would make it fairly easy for the UI to implement a badge indicating where a workflow job is a slice-container entity.

For example, here I have a workflow job template, where a job template is aded to it. When ran, the jobs it produces is non-obvious to the user.

![screen shot 2018-10-18 at 7 29 05 am](https://user-images.githubusercontent.com/1385596/47151447-cc137a00-d2a7-11e8-9c85-46f54f2e8f7a.png)

One of the workflow jobs is from the workflow job template (can't tell which), and the other is from the sliced job template. The job-lets can be told by the fraction badge.

As an enhancement, I'm proposing that we should have a badge for the workflow job. Maybe it could just say "Sliced job", but wording is up for discussion.

##### ADDITIONAL INFORMATION

I see this as out of scope of the original planning, but it's relevant enough that I wanted an issue for it.

**Comment by kialam** [comment]
I think this is a great idea. Bringing in @trahman73 and @wenottingham to start a discussion on what the badge name should be. I like "Slice Job" and "Slice Job Parent."

**Comment by trahman73** [comment]
I like "Slice Job" for the parent container and "Slice Job 0/0" for the individual slice jobs.

**Comment by wenottingham** [comment]
I'd do 'Job Slice' for the child job; it's a slice of the larger job.

**Comment by AlanCoding** [comment]
![Screen Shot 2019-04-01 at 9 42 43 AM](https://user-images.githubusercontent.com/1385596/55332038-87992680-5462-11e9-8d3c-bf4a50e17daf.png)

4/1/2019, confirmed this was not implemented, so this is still a valid work item.

**Comment by kialam** [comment]
@AlanCoding are you simply meaning that the badge copy should read "Job Slice x/y" instead of what it reads currently?

**Comment by AlanCoding** [comment]
The badges that read "Slice Job 1/2" and "Slice Job 2/2" look great. This issue pertains to the job which has the badge "Workflow Job". This is a workflow job that came from a slice JT, and there's no way (at a glance) to tell it apart from a workflow job that came from a WFJT.

**Comment by nixocio** [comment]
This is possibly relevant to the workflow job details as well.

**Comment by akus062381** [comment]
resolved
