### ISSUE TITLE
No limits set on containers in Kubernetes install

### ISSUE THREAD

**Issue by jaevans** [ansible/awx#2488]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - Installer

##### ENVIRONMENT
* AWX version: 2.0.1
* AWX install method: Kubernetes
* Ansible version:  2.7.0
* Operating System: Mac OS High Sierra
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Use the install.yml playbook to install to a Kubernetes cluster with low default CPU and memory limits.

##### EXPECTED RESULTS

Deployment succeeds and starts the Pods.

##### ACTUAL RESULTS

We set our LimitRange to basically nil to enforce having limits set on our applications. Without setting limits, the aux-0 Pod fails to start. The database migration also fails due to the migration process being OOM killed.

##### ADDITIONAL INFORMATION

Best practices suggest applying both requests and limits to containers.

**Comment by joseorpa** [comment]
It is already done, if you set the variables(management_mem_limit and/or management_cpu_limit) in the inventory the deployment will have limits as shown in the jinja template code:
{% if management_mem_limit is defined or management_cpu_limit is defined %}
        limits:
{% endif %}
{% if management_mem_limit is defined %}
          memory: "{{ management_mem_limit }}Gi"
{% endif %}
{% if management_cpu_limit is defined %}
          cpu: "{{ management_cpu_limit }}m"
{% endif %}
