### ISSUE TITLE
Unknown error while connecting to vCenter or ESXi API / Name or service not known

### ISSUE THREAD

**Issue by JasonLGuthrie** [ansible/awx#2490]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API / UI

##### SUMMARY
When running the following playbook in Ansible, all is fine.  When running from an AWX Job Template, we get an error about having trouble logging into the vCenter or API:

cat vm_create.yml
---
- hosts: localhost
  connection: local
  tasks:
    - name: "VM Creation"
      vmware_guest:
        hostname: vcenter.ourcorp.com
        username: ansible@vsphere.ourcorp.com
        password: PASS1234!
        validate_certs: False
        template: "Template-RHEL-7.4"
        name: awx-deployed
        cluster: the-lab
        folder: "Discovered virtual machine"
        datacenter: "Lab"

##### ENVIRONMENT
* AWX version: 1.0.6.23
* AWX install method: Ansible on RHEL, AWX on Docker 18.06.1-ce Build e68fc7a
* Ansible version:  2.6.5
* Operating System: RHEL 7.4
* Web Browser: Chrome or any other...

##### STEPS TO REPRODUCE
Create a job template with the same detail as the provided yaml file and run from schedule in AWX.

##### EXPECTED RESULTS
Within Ansible, the script produces the VM.  Within AWX, the system is running the same script with admin level access, and should create the same VM.

##### ACTUAL RESULTS

Regardless of which account we use, or even if we leave the same credentials used in the Ansible playbook (shown above), the various levels of logging all point to the playbook not executing due to not being able to connect to the vCenter or the API.

##### ADDITIONAL INFORMATION

ansible-playbook 2.6.0 |  
  | 2 | config file = /etc/ansible/ansible.cfg |  
  | 3 | configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', 
 '/usr/share/ansible/plugins/modules'] |  
  | 4 | ansible python module location = /usr/lib/python2.7/site-packages/ansible |  
  | 5 | executable location = /usr/bin/ansible-playbook |  
  | 6 | python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] |  
  | 7 | Using /etc/ansible/ansible.cfg as config file |  
  | 8 | [WARNING]: provided hosts list is empty, only localhost is available. Note |  
  | 9 | that the implicit localhost does not match 'all' |  
  | 10 |   |  
  | 11 |   |  
  | 12 | PLAYBOOK: vm_create.yml **************************************************** |  
  | 13 | 1 plays in vm_create.yml |  
  | 14 |   |  
  | 15 | PLAY [localhost] *************************************************************** | 22:29:12
  | 16 | META: ran handlers |  
  | 17 |   |  
  | 18 | TASK [VM Creation] ************************************************************* | 22:29:12
  | 19 | task path: /var/lib/awx/projects/VMProjects/vm_create.yml:6 |  
  | 20 | fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unknown error while connecting to vCenter or ESXi API at vcenter.ourcorp.com:443 : [Errno -2] Name or service not known"} |  
  | 21 |   |  
  | 22 | PLAY RECAP ********************************************************************* | 22:29:13
  | 23 | localhost                  : ok=0    changed=0    unreachable=0    failed=1 |  
  | 24

**Comment by ybizeul** [comment]
Does it works if you put the IP instead? Looks like a name resolution issue

**Comment by ryanpetrello** [comment]
Closing due to age (and no response).
