### ISSUE TITLE
Versioning for Workflow Template

### ISSUE THREAD

**Issue by powertim** [ansible/awx#2491]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI
 - Core

##### SUMMARY
Workflow template is a wonderful feature but it's not possible to track changes in time and offering the possibility to revert to a previous version.
Could it be possible to change the way it is stored (currently in DB if I'm right) ?
I suggest to use YAML files (as most related Ansible files) to permit versioning in Git or any other SCM.
Workflow Templates should be imported from projects the same way we do for Job Templates.

##### ADDITIONAL INFORMATION
This feature would very efficient to permit safer collaboration within and between teams while building complex workflows inside Tower or AWX.

**Comment by AlanCoding** [comment]
Some attempt to do this was made with the tower-cli workflow "schema" feature, you can see YAML files here.

https://tower-cli.readthedocs.io/en/latest/cli_ref/usage/WORKFLOWS.html

This feature was also integrated with the tower modules, so inside of a playbook you can do a `tower_workflow` task and provide the YAML structure directly inside of your playbook YAML.

I would like to keep the focus on client-oriented solutions to this, via self-creation if needed, and if that gets really crazy popular then those actions could be streamlined with a deeper system integration to be faster. Having worked on this, I would identify two problems / shortcomings of what you can do with a client tool:

 - nodes have no identifier https://github.com/ansible/awx/issues/2032, so idempotence is contingent on the specific tree structure, and only with tremendous effort on the client's part
 - uniqueness rules (see `/api/v2/settings/named-url/`) still make life very hard, see how projects have a different uniqueness rule than job templates

**Comment by wenottingham** [comment]
Job templates are *not* imported from projects, so I'm not sure what you mean there.
In any case, this is #578, so marking as a duplicate.

**Comment by powertim** [comment]
> Job templates are not imported from projects, so I'm not sure what you mean there.

Yes, my bad. Job template content, the playbook you play refers to the project.
I was thinking of a way in the UI to permit automatic save of the workflow template content to a project that refers to a Git repo for example.

Btw, I'm glad to see that you already opened a feature request for that.
