### ISSUE TITLE
Smart Inventory, unable to search by related fields

### ISSUE THREAD

**Issue by naisanza** [ansible/awx#250]
##### ISSUE TYPE

 - Feature Request

##### COMPONENT NAME

 - UI

##### SUMMARY

Searching for things like `groups:dev` doesn't work

And the documentation doesn't explain how to search by the `RELATED FIELDS`

![screenshot from 2017-09-21 20-32-32](https://user-images.githubusercontent.com/1614425/30728335-0b109830-9f0c-11e7-838a-a75e8c147557.png)

![screenshot from 2017-09-21 20-46-27](https://user-images.githubusercontent.com/1614425/30728613-0c42451c-9f0e-11e7-9d88-765988651ab9.png)

##### ENVIRONMENT

* AWX version: ece93c45c9c932cfbfba2b44e217e99a6bb6a752
* Ansible version:  2.4.0.0
* Operating System: Proxmox Ubuntu 16.04 server
* Web Browser: Chrome

**Comment by chrismeyersfsu** [comment]
@naisanza Can you capture the network XHR request that is issued when you run that search? If your in chrome, right click -> inspect -> click on the Network tab -> click the XHR filter -> issue the search request and watch for it in the list.

![smart_search_bug](https://user-images.githubusercontent.com/722880/30747144-53435994-9f7a-11e7-9491-7c061248b7e9.gif)

**Comment by naisanza** [comment]
@chrismeyersfsu 

```
http://awx/api/v2/hosts/?order_by=name&page_size=5&inventory__organization=1&host_filter=groups__icontains=vpn
```

**Comment by jlmitch5** [comment]
@naisanza this is being fixed in Tower, and that code will be merged back into AWX shortly.  We will keep this issue open until those changes have landed in AWX and ping you to make sure you aren't seeing it anymore.

**Comment by mabashian** [comment]
Talked with @wwitzel3 about what the UI should be sending here.  If the user types in something like `groups:vpn` then the UI should be sending a request that looks like: `/api/v2/hosts/?order_by=name&page_size=5&inventory__organization=1&host_filter=groups=vpn`.  Note that this will do an ID search on the related groups.  If the user wanted to search for a group by name they would need to use the following syntax: `groups.name:vpn`.  I'm working on fixing this downstream.  @naisanza you might be able to get around this bug by using one of the following `groups.name:vpn` if the group's name is exactly `vpn` or `groups.name.icontains:vpn` for a contains match.  I haven't tested those options but that might get you around the bug for now.

**Comment by naisanza** [comment]
@mabashian `groups.name.icontains:vpn` and `groups.name:vpn` both work

Is the `i` in `icontains` for case-insensitive?

**Comment by Pectojin** [comment]
For anyone curious. The `i` does indeed seem to be for case-insensitive.
