### ISSUE TITLE
Date picker widget is busted when creating a schedule for a Job Template

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#2503]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
![image](https://user-images.githubusercontent.com/214912/47296254-b1ab0a80-d5df-11e8-8c2a-bfc9c56122a1.png)

##### ENVIRONMENT
* AWX version: latest
* AWX install method: docker on linux

**Comment by unlikelyzero** [comment]
@ryanpetrello do we know which change caused this regression?

**Comment by wenottingham** [comment]
per @kialam - https://github.com/ansible/awx/pull/2141/files#diff-93ced64530afe01c1e00aba523647af4

**Comment by kialam** [comment]
Note _anywhere_ the scheduler template is used is broken, not just Job Template (e.g. Projects, etc.).

**Comment by kialam** [comment]
@unlikelyzero @dsesami this is ready for testing.
