### ISSUE TITLE
Provisioning callback No matching host could be found

### ISSUE THREAD

**Issue by jwinderWCB** [ansible/awx#2507]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
I am attempting to setup a provisioning callback. The message being returned is "No matching host could be found!"

I have verified the host was added to the dynamic inventory and has a fact foreman.ip: [correct ip address]

The hostname can not be resolved using a reverse DNS lookup. What other methods does AWX use to lookup a host by the requesting IP?

##### ENVIRONMENT
* AWX version: 2.0.1
* AWX install method: docker on linux
* Ansible version:  2.7.0
* Operating System: RHEL 7.5
* Web Browser: Chrome

##### STEPS TO REPRODUCE
1) I setup an inventory and verified it would update.
    I also set Overwrite, and Update on Launch.
2) Verified remote host is available in the inventory. Also, found host's IP address in the following facts:
  - foreman.ip
  - foreman_facts.discovery_bootip
  - foreman_facts.ipaddress_ens32
  - foreman_facts.discovery_ip_cidr
  - foreman_facts.nmprimary_ip4_address
  - foreman_facts.ipaddress
3) Created project and verified it would update from git.
   I also set Clean, and Update Revision on Launch
4) Created template and verified I could execute it on remote host via the AWX UI.
   I also set Allow Provisioning Callbacks

5) On remote host execute 'curl -k -s -vv --data "host_config_key=4d27ec88782b2010cee8ae19f5977199" https://[server running AWX]/api/v2/job_templates/15/callback/

##### EXPECTED RESULTS
I expected the job template to be kicked off and run my provisioning playbook against the calling host.

##### ACTUAL RESULTS
After updating the dynamic inventory I receive the error "No matching host could be found!"

**Comment by matburt** [comment]
It'd be helpful to check the web server / docker console logs to see where AWX thinks the request is coming from... is it the actual host or does the source address differ?

**Comment by dmaple-gci** [comment]
I have the same issue.  However, I know the issue is due to my load balancer replacing the source IP.  Is there a way to use the X-Forwarded-For header or pass another variable in the callback with the hostname or IP?

**Comment by jwinderWCB** [comment]
My issue is a lack of reverse DNS lookups, so AWX is not able to locate the host in the inventory. There are variables in the inventory with the IP address, but these are not variables searched for a match.

I believe I have three options:
1) Get Satellite 6 managing DNS, https://access.redhat.com/articles/1527913 It is going to take our Windows admins some time to create all of the reverse lookup zones.
2) Modify the curl call to include a new header with the host's hostname. Then add that header as one searched in AWX. https://docs.ansible.com/ansible-tower/3.2.6/html/administration/proxy-support.html
3) Modify the foreman.py inventory script to populate an ansible_host variable.

**Comment by jwinderWCB** [comment]
> I have the same issue. However, I know the issue is due to my load balancer replacing the source IP. Is there a way to use the X-Forwarded-For header or pass another variable in the callback with the hostname or IP?

@dmaple-gci See the documentation here: https://docs.ansible.com/ansible-tower/3.2.6/html/administration/proxy-support.html

**Comment by dmaple-gci** [comment]
Thanks @jwinderWCB  I had part of that, but not all of it.  Tested and working now, with proper PTR record.

I would still like to see another option besides PTR records to match a host to inventory.  There are situations where we don't have access to update the reverse zone for a subnet.

**Comment by jwinderWCB** [comment]
I agree with the requirement of reverse DNS lookups. It would be nice if in the inventory you could specify a list of variables/facts to match against.

I ran into an issue with a legacy Satellite 5.x/Spacewalk system that none of the hosts were even in DNS. I ended up having the modify the spacewalk.py inventory script to set the ansible_host to the host's IP in order to be able to run anything against them.

**Comment by matburt** [comment]
Looks like we're good here.
