### ISSUE TITLE
Chain workflow

### ISSUE THREAD

**Issue by door7302** [ansible/awx#2511]
##### ISSUE TYPE
It will be interesting to be able to chain different Workflow. Variables set in a survey might be shared between several workflow. 

[WF 1 + survey with vars ] ----> [WF 2 (knows vars of WF 1) ] ----> [WF 3 (knows vars of WF 1) ] 

##### COMPONENT NAME

 - API
 - UI
 - Installer

**Comment by wenottingham** [comment]
-> #2252
