### ISSUE TITLE
Ansible Tower - Servicenow integration Failed

### ISSUE THREAD

**Issue by hd2212** [ansible/awx#2515]
##### ISSUE TYPE
 - Error dynamic inventory parsing.

##### COMPONENT NAME

 - API

##### SUMMARY

I'm basically following the steps mentioned in ansible servicenow integration official repo to integrate servicenow and get hosts from CMDB. I have all the dependencies installed ( python-configparser) and my ansible version is 2.7.0 and my tower version is 3.3.0 . I have the now.ini file in my /etc/ansible directory and also my now.py script. I have pasted the contents of now.py in my custom script contents in tower. Created an inventory and used the custom script in sources. I have all the credentials set up and also enabled .ini, script plugins in ansible.cfg file . When i'm trying to sync the inventory I'm facing the below error.  Could anyone please help me out with resolving this problem?
Please find the error below
[WARNING]:  * Failed to parse /tmp/awx_69_rRSdgQ/tmpZkM0LD with script plugin:
Inventory script (/tmp/awx_69_rRSdgQ/tmpZkM0LD) had an execution error:
Traceback (most recent call last):   File "/tmp/awx_69_rRSdgQ/tmpZkM0LD", line
321, in <module>     main(sys.argv)   File "/tmp/awx_69_rRSdgQ/tmpZkM0LD", line
316, in main     inventory.generate()   File "/tmp/awx_69_rRSdgQ/tmpZkM0LD",
line 205, in generate     content = self._invoke('GET', path, None)   File
"/tmp/awx_69_rRSdgQ/tmpZkM0LD", line 155, in _invoke     'http': self.proxy,
'https': self.proxy})   File "/var/lib/awx/venv/ansible/lib/python2.7/site-
packages/requests/sessions.py", line 535, in get     return self.request('GET',
url, **kwargs)   File "/var/lib/awx/venv/ansible/lib/python2.7/site-
packages/requests/sessions.py", line 522, in request     resp = self.send(prep,
**send_kwargs)   File "/var/lib/awx/venv/ansible/lib/python2.7/site-
packages/requests/sessions.py", line 642, in send     r = adapter.send(request,
**kwargs)   File "/var/lib/awx/venv/ansible/lib/python2.7/site-
packages/requests/adapters.py", line 503, in send     raise ConnectionError(e,
request=request) requests.exceptions.ConnectionError:
HTTPSConnectionPool(host='none', port=443): Max retries exceeded with url: //ap
i/now/table/cmdb_ci_server?sysparm_exclude_reference_link=true&sysparm_display_
value=true&sysparm_fields=sys_class_name,fqdn,ip_address,name,host_name (Caused
by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConne
ction object at 0x7f9fc37e23d0>: Failed to establish a new connection: [Errno
-2] Name or service not known',))
 [WARNING]: Unable to parse /tmp/awx_69_rRSdgQ/tmpZkM0LD as an inventory source
ERROR! No inventory was parsed, please check your configuration and options.

##### ADDITIONAL INFORMATION

Link to the now.py file.
https://github.com/ServiceNowITOM/ansible-sn-inventory/blob/master/now.py

**Comment by wenottingham** [comment]
```
HTTPSConnectionPool(host='none', port=443): Max retries exceeded with url: //ap
i/now/table/cmdb_ci_server?sysparm_exclude_reference...
```

You appear to not be passing the host correctly.

**Comment by hd2212** [comment]
you mean the servicenow instance name like your_instance.service-now.com?

**Comment by wenottingham** [comment]
Yes - however you're supposed to pass it to that script, it doesn't look like it made it through.

**Comment by hd2212** [comment]
I'm using the now.ini file where I placed it in our tower cluster servers in the /etc/ansible/ directory so that it will help the script to pull the instance, username and password from the file. So you think the problem is with the credentials?

**Comment by wenottingham** [comment]
If you're not passing the `NOW_INI` env variable, it does not look like it will look in /etc/ansible... only in the current working directory.

**Comment by hd2212** [comment]
Got it! Thanks much!

**Comment by wenottingham** [comment]
Sure. Closing this, feel free to reopen if you run across an AWX bug in the process of using it.

**Comment by hd2212** [comment]
Hey I have the script running on my unix server and i'm able to fetch the hostnames from the cmdb server when i run the commands ansible -i now.py all -m ping and ./now.py --list, but i'm still facing the same error in the tower even after specifying the "NOW_INI":"/etc/ansible/now.ini" in extra environment variables. What can be possibly going wrong?

**Comment by wenottingham** [comment]
Is job isolation enabled?

**Comment by hd2212** [comment]
Yes

**Comment by hd2212** [comment]
Also my tower is an elb which contains two tower servers as one cluster.
So is there a chance that might be causing the problem? . But it shouldn't as i'm using the elb to hit the cluster.

**Comment by wenottingham** [comment]
If you're using Tower, please contact your RH support rep.

**Comment by hd2212** [comment]
Hey I got it working on Tower as well, but do you have any idea how the filtering of hosts is done on tower?. Because I just need a set of hosts and not the whole pool of hosts.
