### ISSUE TITLE
Force Limit on launch job

### ISSUE THREAD

**Issue by Colstuwjx** [ansible/awx#2518]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
For current version, if we need to launch a job with limit option, we can set the limit on ui or pass limit param to API, but we don't limit that `You must fillout the limit option, otherwise this job template could NOT be launched`.

For security reason, I think it's indeed needed.
Thanks.

##### ADDITIONAL INFORMATION

AWX 1.0.7.2

**Comment by wenottingham** [comment]
Security reasons? Given that no verification of limit is done, I don't think there is a security issue here.

**Comment by Colstuwjx** [comment]
If limit is not set yet, all of inventory hosts would be run, it's pretty dangerous! I think we should have this force limit. Or it must be controlled by user side?

**Comment by wenottingham** [comment]
If you are letting the user specify a limit, specifying no limit is a reasonable answer to that.

If you want them to only have access to certain hosts, put them in an specific inventory and only delegate access to that.

**Comment by dapiced** [comment]
We have the same concern here! we would like to put a dummy limit by defaut for each tower job template created...

The goal was to avoid someone who did a "adhoc job" for one machine only and forgot to put a limit and spread the modification all around theirs inventories...

we already have rbac for tower....


any idea ?   i can for sure make rest api to fill up all limit field who's empty.... but its not the best idea...

suggestion ?

**Comment by mboeker** [comment]
This is marked as completed, what was the solution?
I found a workaround for anyone else in the future, pretty simple but not super elegant: just populate the default limit field with something like NO_HOSTS which will never find a match, so the user has to put something. If they decide to put "*" then that's on them, but it can't run on all by accident.
