### ISSUE TITLE
Use regex to create more flexible smart inventories

### ISSUE THREAD

**Issue by mjhermanson** [ansible/awx#2525]
##### ISSUE TYPE
 - Need the ability to create a smart inventory based on regular expression

##### COMPONENT NAME
 - UI

##### SUMMARY
A common practice is to use a standardized hostname for nodes in an inventory. A regular expression can be used against some attribute (like inventory_hostname) to have dynamically created groups. A use case would be for bootstrapping of a node. 

Consider the following workflow:
- An admin could provision a node 'devweb01'
- The node is added to Ansible Tower's inventory through the dynamic inventory
- The node is automatically added to the group development_webservers because it matches the regular expression associated with that group
- Ansible configures the node with appropriate roles and variable due to its presence in the development_webservers group

**Comment by wenottingham** [comment]
This can be done now for smart inventories.

Example:
`name.regex:^foo`
will pull all hosts that start with `foo`.

**Comment by wenottingham** [comment]
As for searching inventory_hostname, that would be #371.

**Comment by UristMcMiner** [comment]
@wenottingham is it possible to use advanced regex constructs like capturing groups? I tried this, and no matter how i try to escape characters it just fails
