### ISSUE TITLE
Workflow Job UI in extra variable frame (width)

### ISSUE THREAD

**Issue by ryan012880** [ansible/awx#2526]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Workflow live job stream does not display properly due to extra variable frame width scale. 

##### ENVIRONMENT
* AWX version: <= 2.0.1
* AWX install method: docker on linux
* Ansible version:  <= 2.7.0
* Operating System: RHEL7
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Create a workflow and put a extra variable with long string value

##### EXPECTED RESULTS
![screen shot 2018-10-25 at 9 03 12 pm](https://user-images.githubusercontent.com/10410660/47502746-2362ad00-d89b-11e8-93b0-56d13cc898eb.png)

As seen in the attached capture the width of the frame does not scale, this should be the correct behaviour.

##### ACTUAL RESULTS
![screen shot 2018-10-25 at 9 02 36 pm](https://user-images.githubusercontent.com/10410660/47502849-52791e80-d89b-11e8-8e16-96ef918edbe2.png)

This will occur during runtime and after (when you view the completed job details)

**Comment by unlikelyzero** [comment]
@mabashian anyway we can knock this out in devel?

**Comment by ryan012880** [comment]
the issue still there in 2.1.1, tnx
