### ISSUE TITLE
No more access to the HMI after login

### ISSUE THREAD

**Issue by Gamoth** [ansible/awx#2528]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### ENVIRONMENT
* AWX version: 2.0.0
* AWX install method: docker on linux with docker-compose 
* Ansible version:  2.4.2.0
* Operating System: RHEL 7.5
* Web Browser: Firefox 60ESR
* Docker : 18.06-1-ce
* Docker-compose : 1.20.1

##### STEPS TO REPRODUCE

* Install AWX with local docker
* Use it for a few days
* Try to connect with any account (local or ldap)

##### EXPECTED RESULTS

Access the AWX dashboard

##### ACTUAL RESULTS

Blocked after entering login password, I stay on the same page.
![2018-10-25_163439](https://user-images.githubusercontent.com/2760060/47508175-e3d49a80-d873-11e8-88e9-a41f2499c49d.png)
[docker-compose.log](https://github.com/ansible/awx/files/2515380/docker-compose.log)

**Comment by matburt** [comment]
There's no really enough information to go on here, it looks like something is wrong with rabbitmq and other services. I see you are running version 2.0, I'd recommend upgrading and seeing how that goes.
