### ISSUE TITLE
Activity Smart Status represents 10 individual slices instead of overall WF result which masks failure if more than 11 slices are run

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2531]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Activity Smart Status represents 10 individual slices instead of overall WF result which masks failure if more than 11 slices are run

##### ENVIRONMENT
* AWX version: 3.4.0

##### STEPS TO REPRODUCE

1. Create a SJT with 10 slices.
2. Launch the SJT and watch the Activity Smart Status on the Jobs list view.

##### EXPECTED RESULTS

The activity Smart Status would only show the overall status of the SJT and not the individual slices.

##### ACTUAL RESULTS

Individual slices are represented as job history.

##### ADDITIONAL INFORMATION

![sjt-activity](https://user-images.githubusercontent.com/12446869/47520362-fba12400-d85d-11e8-9600-2d9f57add46b.gif)

**Comment by AlanCoding** [comment]
We were showing workflow jobs in the recent_jobs list, but then went back on that decision:

https://github.com/ansible/awx/pull/2174/commits/5342c635581a24a83e2e694694125a214f31690c

**Comment by unlikelyzero** [comment]
@kialam @AlanCoding I think we landed this as a RFE. Did we need any further action on this in 3.4?

**Comment by kialam** [comment]
@unlikelyzero Not that I see. @AlanCoding is right; I requested that we only show slice jobs in the recent jobs list. This does become problematic if you have large slices as you lose the ability to gauge the health of a job template "at a glance." We should think about ways we can improve this for 3.4.x.
