### ISSUE TITLE
POST to /api/v2/users directly does not associate user with target organization

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#2532]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI (?)

##### SUMMARY
In the actual UI, the "organizations" field is mandatory, and when you create a user, the user is then associated with the organization requested. However, when making a direct POST, we can't get the organization to associate with the user -- the user is successfully created, but then is not linked to any organizations.

##### ENVIRONMENT
____________________________ 
<  AWX 2.0.1-165-g695c7ade8  >
Ansible 2.7.0 
* Operating System: Fedora
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Use this POST, which was copied from a successful call from the UI to make a user: 
```{email: "null@ansible.ccom"
first_name: "A"
is_superuser: false
is_system_auditor: false
last_name: "a"
organization: 1
password: "a"
password_confirm: "a"
user_type: {type: "normal", label: "Normal User"}
username: "aaaaa"}
```
##### EXPECTED RESULTS

The user is associated with the "Default" org.
##### ACTUAL RESULTS
The user is not associated with any orgs.

**Comment by dsesami** [comment]
cc @AlanCoding

**Comment by AlanCoding** [comment]
I had to walk through the steps locally, but I found that the UI is actually making the POST to the endpoint:

`/api/v2/organizations/510/users/`

When a POST is made to such a sublist, the API automatically fills in the parent field.

I think the confusion here was that this fact was very non-obvious looking at the network traffic, suggesting the action was to `/api/v2/users/` and not the org-users-sublist. If you use the sublist via the API you should quickly confirm that the organization is associated.
