### ISSUE TITLE
CSRF Token Issue

### ISSUE THREAD

**Issue by dtardoin** [ansible/awx#2537]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
- UI

##### SUMMARY
For some users (it seems like only Chrome on OSX) that they're required to clear their cache every time 
they log in to the UI, otherwise they get complaints of CSRF tokens not being valid on post requests.

##### ENVIRONMENT
* AWX version: 2.0.0
* AWX install method: Docker
* Ansible version:  2.3.2
* Server Operating System: Ubuntu 16.04 
* Client Operating System: OSX High Sierra
* Web Browser: Chrome

##### STEPS TO REPRODUCE

- Log into AWX
- Navigate to any form with an associated POST action, EG a job template
- Click the button to perform an API Post (click run)

##### EXPECTED RESULTS

- Action is performed (job is started) 

##### ACTUAL RESULTS

- Modal Window pops up stating that your CSRF token is missing or invalid 
- User logs out, clears the browser cache/cookies
- User logs back in, everything works as expected

##### ADDITIONAL INFORMATION

This started happening with the upgrade to 2.0.0, it didn't happen in the previous version we ran (1.0.3).
The database is from a former Tower installation, that was re-used for AWX.  
"Wiping the database and starting from scratch" isn't an option.  

<img width="601" alt="screen shot 2018-10-26 at 10 20 34 am" src="https://user-images.githubusercontent.com/3720321/47574533-cb18c300-d90d-11e8-99d9-059a34a8919a.png">
<img width="554" alt="screen shot 2018-10-26 at 10 20 43 am" src="https://user-images.githubusercontent.com/3720321/47574534-cb18c300-d90d-11e8-8714-8e89b0b51d3c.png">

**Comment by wenottingham** [comment]
What specific version of chrome?

**Comment by Smalltown15** [comment]
The issue is happening for me and another user on Chrome Version 70.0.3538.77. We are both running OSX Version 10.14.

I tested this out in Safari and could not reproduce the issue.

**Comment by jakemcdermott** [comment]
I'm unable to reproduce this using chrome 70 on Mac OS 10.13.16 - @Smalltown15 , are you using the same database as @dtardoin ?

**Comment by dtardoin** [comment]
@jakemcdermott yeah. @Smalltown15 is using my installation. 

For more context: this happens for me (in Chrome on Linux) whenever I rebuild awx, but if I clear my cache the issue goes away. 

I couldn't find a management command to purge tokens, not to mention find the table where they're stored to manually delete them. Is there something I'm missing?

**Comment by jakemcdermott** [comment]
Tower is a downstream project of AWX. We aren't setup to support DB migrations from downstream project installations for AWX installations. In some cases it might work, but there are absolutely no guarantees in terms of data integrity.

To use AWX, it is highly encouraged that you do so by starting with an AWX database. If you continue to see this issue after doing this, please re-open this issue. 

Reach out to our community mailing list or stop by our irc channel (`#ansible-awx` on freenode) if you have additional questions. Thanks!

**Comment by dtardoin** [comment]
After taking the time to rebuild our AWX instance *from scratch* this is still happening.
