### ISSUE TITLE
when using AWS as a inventory source , only EC2 instances with public IP addresses are imported

### ISSUE THREAD

**Issue by garethbroadhurst** [ansible/awx#2545]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
when using AWS as a inventory source , only EC2 instances with public IP addresses are imported

##### ENVIRONMENT
* AWX version: 2.0.1
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.7.1
* Operating System: Centos7
* Web Browser: Chrome

**Comment by jakemcdermott** [comment]
Hello @garethbroadhurst 

Thanks for creating this issue. What you've described is expected default behavior for the dynamic aws inventory - only instances with public ips are imported.

If you need to modify this behavior, you can do so by setting `ec2_opts.setdefault('vpc_destination_variable', 'ip_address')` in source vars.
