### ISSUE TITLE
Problem about adding hosts in AWX

### ISSUE THREAD

**Issue by jeannot49** [ansible/awx#2546]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: docker on linux
* Ansible version:  2.7.1
* Operating System: CentOS 7
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

Go to AWX > inventories > hosts > "+" (add host) >
Enter the host which has to be added

Add these variables : 
            ansible_connection: winrm
            ansible_winrm_transport: credssp
            ansible_winrm_server_cert_validation: ignore
            ansible_user: user@DOMAIN
            ansible_password: password

Then click "Save"

##### EXPECTED RESULTS

One host added to the list of hosts

##### ACTUAL RESULTS

Call to /api/v2/hosts/. GET returned: undefined Internal server error.

**Comment by wenottingham** [comment]
What is the actual server error?

**Comment by jeannot49** [comment]
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

I tried to search into the API by enterring <ip_server>/api but I don't have enough experience in the API's.

**Comment by matburt** [comment]
This will either be in the web container console or in log files in /var/log in the container itself.

**Comment by jeannot49** [comment]
I didn't find any interesting log, neither in the awx_task nor in the awx_web container.

**Comment by jeannot49** [comment]
The file you have corrected appears in my system with the good lines.
The issue stills unresolved anymore...
I have the 2.7.10 version of python. i'll try to re-create a virtual machine with the 3.6.

**Comment by jeannot49** [comment]
It works with a virtual environment of python, more precisely the 3.7.1. 
Thanks for your time.
