### ISSUE TITLE
AWX Disable HTTP Auth Login Form?

### ISSUE THREAD

**Issue by srflaxu40** [ansible/awx#2549]
##### ISSUE TYPE
 - Feature Idea

Can we, or is there, disable login forms to force alternate logins, like GitHub, so that we can have a public internet facing awx?

##### COMPONENT NAME

 - UI

##### SUMMARY

Allow removal or disabling of AWX login form.  Example just GitHub auth button and no username / password field - to disable brute force.

**Comment by wenottingham** [comment]
... why not just remove local users?

**Comment by jakemcdermott** [comment]
@srflaxu40 

Nope - there is currently no way to disable the login page, and there aren't any plans to provide a way to remove it at this time. You _can_ certainly use github and other external authentication providers if you enable and configure them from the settings page.

If you intend to use github authentication _and_ are concerned with brute forcing, @wenottingham 's suggestion of clearing any local users from the system after configuring the external auth would definitely be the way to go.

**Comment by srflaxu40** [comment]
is the "admin" user considered local?
