### ISSUE TITLE
A SJT with Prompts is not routed to SJT-Workflow view on launch

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2551]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
A SJT with Prompts is not routed to SJT-Workflow view on launch.

##### ENVIRONMENT
* AWX version: 3.4.0

##### STEPS TO REPRODUCE

1. Create a SJT with any prompted value (i.e. Job Type)
2. Launch JT from any screen (i.e. Templates View
3. Accept or modify default prompts
4. Note that the session does not route to the Workflow view

##### EXPECTED RESULTS

Session Routed to the workflow view

##### ACTUAL RESULTS

Session stays on current view

**Comment by unlikelyzero** [comment]
Related to https://github.com/matburt/awx/pull/7

**Comment by kialam** [comment]
This should be fixed upstream already.

**Comment by dsesami** [comment]
Confirmed that this correctly routes to the workflow view in both chrome and firefox.
