### ISSUE TITLE
Real-time Job data isn't available on the Organization/JobTemplates view

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2552]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Real-time Job events data isn't available on the Organization/JobTemplates view

##### ENVIRONMENT
* AWX version: 3.4.0

##### STEPS TO REPRODUCE

1. Create a JT which is associated with a Organization
2. Navigate to the Organization Job Template view
3. Launch the JT from step 1 but stay on view from step 2.
Note that the real-time status of the job isn't available

##### EXPECTED RESULTS

Job status is updated in real-time. Pending, running, completed with smart view activity bubbles.

##### ACTUAL RESULTS

No job status change

##### ADDITIONAL INFORMATION

![org-job-status](https://user-images.githubusercontent.com/12446869/47741915-e3f8df80-dc51-11e8-86d1-643646c44488.gif)

**Comment by dsesami** [comment]
Followed reproduction steps above on a few job templates and verified that this is resolved in the devel branch. (Chrome/Firefox)
