### ISSUE TITLE
Instance Groups Jobs view doesn't contain Workflow jobs

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2553]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Instance Groups Jobs view doesn't display Workflow Jobs

##### ENVIRONMENT
* AWX version: 3.4.0

##### STEPS TO REPRODUCE

1. Launch a WFJT against a particular instance group
2. Navigate to the Instance Groups / Jobs view
3. Note that Job Templates and SCM Updates are displayed but WFJTs are not

##### EXPECTED RESULTS

Workflow jobs to be displayed. In the slice job world, this is odd.

##### ACTUAL RESULTS

No workflow jobs displayed but slices are displayed.

##### ADDITIONAL INFORMATION

<img width="1372" alt="screen shot 2018-10-30 at 3 01 50 pm" src="https://user-images.githubusercontent.com/12446869/47743153-c24d2780-dc54-11e8-9f2b-8db4d1c8e5d8.png">

**Comment by matburt** [comment]
Workflows are not associated with Instance Groups, I believe this to be a non-issue. I don't see us ever actually doing that. The IG view is more interested in what individual jobs are running there.
