### ISSUE TITLE
If a SJT is converted to a regular job type, it cannot be relaunched from the Workflow Job view without error

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2554]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
If a SLT is converted to a regular job type, it cannot be relaunched from the Workflow Job view without error

##### ENVIRONMENT
* AWX version: 3.4.0

##### STEPS TO REPRODUCE

1. Create a SJT with multiple slices
2. Run Job
3. Convert SJT to single JT
4. Attempt to re-launch SJT from Workflow view

##### EXPECTED RESULTS

1. Run JT or error message

##### ACTUAL RESULTS

Inert button

##### ADDITIONAL INFORMATION

XHR POST failed loading /api/v2/workflow_jobs/312/relaunch/

**Comment by AlanCoding** [comment]
I have received word that this is an API issue instead

**Comment by unlikelyzero** [comment]
Verify:

- Error modal appears and properly describes the issue from Jobs List, Dashboard, and anywhere else the Relaunch job is used
