### ISSUE TITLE
Expand settings entry forms to construct json/python rather than requiring it

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#2562]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

There are a number of places in our settings configuration where the user is required to enter properly formatted JSON, python data structures (lists, dictionaries), or combinations thereof.

Ideally, we would have a cleaner settings paradigm that allows for easier user entry and constructs properly-formatted data structures to pack to the backend.

**Comment by unlikelyzero** [comment]
Covered in the new ui
