### ISSUE TITLE
Regarding Oauth for login to fetch access token

### ISSUE THREAD

**Issue by congmingdexiong** [ansible/awx#2564]
Hi,
We need to use unirest(node js) to touch ansible by Oauth2 auth( it looks this ansible version doesn't support basic auth to get token), but kept me a error '{ error: 'unsupported_grant_type' }' which troubles me for 2 days, here is the code:
var Request = unirest.post('https://xxxxxxx/api/o/token/');
   Request.headers({
           'Accept': 'application/json',
           'Content-Type': 'application/x-www-form-urlencoded'
        }).oauth({
                callback: 'https://localhost:4001/atauth/callback',
                consumer_key: 'client_key',
                consumer_secret: 'client_secret',
                response_type:'code',
                authorization_grant_type: "authorization_code",
                state: 'random_state_string',
                scope:'write'
        }).end(function (response) {

                console.log(response);
                console.log('----------------------');
                var access_token = response.body;
                console.log(access_token);
        });

We have already configured the settings in application tab in Ansible tower:
![image](https://user-images.githubusercontent.com/30189426/47830220-f3993500-ddc5-11e8-932d-0b600d7a0191.png)

Ansible tower version: Tower 3.3.0, Ansible 2.6.2,

And I am deeply appreciate any help. Thank you

**Comment by jakemcdermott** [comment]
Hello!

This issue tracker is for awx. Tower is a downstream project that is separate from AWX. For help with Tower, please contact your support representative.

**Comment by saxonww** [comment]
FWIW we are seeing this exact behavior with AWX (July 18 build of ansible/awx_web), following the guide at https://github.com/ansible/awx/blob/devel/docs/auth/oauth.md.
