### ISSUE TITLE
Allow to add descreption or Custom Job name while triggering Job template

### ISSUE THREAD

**Issue by parinapatel** [ansible/awx#2568]
##### ISSUE TYPE
 - enhancement

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
Custom Job name when triggering jobs from Job Template, or Provide option to add description for that Job run. Currently we have single template which does different deployment provided variable.
Thus having same name for template makes finding for particular run really hard.

**Comment by wenottingham** [comment]
this is #739, closing as duplicate.
