### ISSUE TITLE
Workflow Visualizer has inconsistent pagination for 'Jobs', 'Project Sync', and 'Inventory Sync' tabs 

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2582]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Workflow Visualizer has inconsistent pagination for 'Jobs', 'Project Sync', and 'Inventory Sync' tabs. 20 for Jobs, 5 for Project Sync, and 5 for Inventory Sync

##### ENVIRONMENT
* AWX version: 3.4

##### STEPS TO REPRODUCE
1. Create or ensure that 21 WFJT are created.
2. Create or ensure that 6 Projects are created.
3. Create or ensure that 6 Inventories are created.
4. Navigate to the Workflow Visualizer
Note that the Jobs tab has an 20 jobs displayed while Projects and Inventories have 5

##### EXPECTED RESULTS

1. 20 is too large. 5 is rather small.

##### ACTUAL RESULTS

All tabs to display the same number of resources. More Projects and Inventories to be available.

##### ADDITIONAL INFORMATION

<img width="1286" alt="screen shot 2018-11-02 at 1 52 29 pm" src="https://user-images.githubusercontent.com/12446869/47931921-8f9a6d80-dea6-11e8-92cb-7d183138d95b.png">

**Comment by unlikelyzero** [comment]
@marshmalien @mabashian @trahman73 thoughts?

**Comment by marshmalien** [comment]
Spoke to @trahman73 and we decided to set all of them to 10.
