### ISSUE TITLE
WFJT with 3+ successive nodes causes "responsitivity" issues in the Workflow Job Result window in Firefox

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2584]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
WFJT with 3+ successive nodes causes "responsitivity" issues in the Workflow Job Result window in Firefox. Resizing the nav bar, resizing the browser window, and 'Expand Output' cause visual glitches and inconsistent behavior.

##### ENVIRONMENT
* AWX version: 3.4.0
* Operating System: macOS
* Web Browser: Firefox 63

##### STEPS TO REPRODUCE

1. Create a WFJT with 3+ chained Jobs and run to completion
2. Open up the Workflow Job Result page
3. Resize the window or Expand and Collapse the Side Nav

##### EXPECTED RESULTS

1. Workflow Job Results view to resize accordingly

##### ACTUAL RESULTS

1. The window size is not recalculated and in some cases the workflow objects disappear from view

##### ADDITIONAL INFORMATION

![resize](https://user-images.githubusercontent.com/12446869/47941616-3aba1f80-dec5-11e8-9f7b-805d323a5d38.gif)

**Comment by dsesami** [comment]
Verified in chrome and firefox that a chained workflow resizes correctly with the sidenav now, in devel.
