### ISSUE TITLE
AWX doesn't show jobs output in ad-hoc commands

### ISSUE THREAD

**Issue by lucaslan** [ansible/awx#259]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
When you launch a job it doesn't show the output.

##### ENVIRONMENT
* AWX version: 1.0.0.532
* Ansible version:  2.4.0.0
* Operating System: RHEL7
* Web Browser: chrome / firefox/ IE

##### STEPS TO REPRODUCE
Simple run a Job:
Add a host, run ping command on host created. 

##### EXPECTED RESULTS

See output from the job.

##### ACTUAL RESULTS

Nothing happens on output.
It stuck on "Waiting for results..." and the status is "Waiting"
If I browse to JOBS, I can see the outputs as well

##### ADDITIONAL INFORMATION

I'm running AWX on docker locally, see docker output bellow:
```
[root@docker01 ansible-awx]# docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                                NAMES
1ad77e547f1a        awx_task:1.0.0.532   "/tini -- /bin/sh ..."   20 minutes ago      Up 20 minutes       8052/tcp                             awx_task
cc8a0efe9a92        awx_web:1.0.0.532    "/tini -- /bin/sh ..."   20 minutes ago      Up 20 minutes       0.0.0.0:80->8052/tcp                 awx_web
413ebefcbb5e        memcached:alpine     "docker-entrypoint..."   20 minutes ago      Up 20 minutes       11211/tcp                            memcached
878022ae8e55        rabbitmq:3           "docker-entrypoint..."   20 minutes ago      Up 20 minutes       4369/tcp, 5671-5672/tcp, 25672/tcp   rabbitmq
3170d5795036        postgres:9.6         "docker-entrypoint..."   20 minutes ago      Up 20 minutes       5432/tcp                             postgres

```

**Comment by lucaslan** [comment]
After I deleted my old docker images:
awx_web
awx_task
awx_sdist_builder

The issue changed a litle bit, now the status is working as I expect, but now the "standard out" is:      
**stdout capture is missing**

I don't know why deleting old images from last release that I had "1.0.0.367" can affect the new relase, its important to say that:

- This new release "1.0.0.532" I'm using a fresh new directory to the postgree database so I made a "fresh install"
- I cloned the brench again, not made pull or fetch

**Comment by naisanza** [comment]
I get the same thing

![peek 2017-09-22 17-35](https://user-images.githubusercontent.com/1614425/30768492-dae4fdd4-9fbc-11e7-89ba-c8054dc945ab.gif)

**Comment by matburt** [comment]
If these are all ad-hoc commands then you are running into a current architectural gap:

https://github.com/ansible/awx/issues/146#issuecomment-329653342
