### ISSUE TITLE
Ansible AWX 2.1.0 Custom Image Build Failed

### ISSUE THREAD

**Issue by ryan012880** [ansible/awx#2590]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
AWX version 2.1.0 image build fails on task: Build AWX distribution using container

##### ENVIRONMENT
* AWX version: 2.1.0
* AWX install method: docker on linux
* Ansible version:  ansible-2.7.0-1.el7.ans.noarch
* Operating System: RHEL7
* Web Browser: N/A

##### STEPS TO REPRODUCE
1. Clone the latest AWX repository
2. Install using custom image build

##### EXPECTED RESULTS
Should proceed without error.

##### ACTUAL RESULTS
TASK [image_build : Build AWX distribution using container] ***********************************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "npm --unsafe-perm --prefix awx/ui install --no-save awx/ui\n> chromedriver@2.40.0 install /awx/awx/ui/node_modules/chromedriver\n> node install.js\nDownloading https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip\nSaving to /tmp/chromedriver/chromedriver_linux64.zip\nReceived 781K...\nReceived 1566K...\nReceived 2350K...\nReceived 3134K...\nReceived 3769K total.\nExtracting zip contents\nCopying to target path /awx/awx/ui/node_modules/chromedriver/lib/chromedriver\nFixing file permissions\nDone. ChromeDriver binary available at /awx/awx/ui/node_modules/chromedriver/lib/chromedriver/chromedriver\n> puppeteer@1.8.0 install /awx/awx/ui/node_modules/puppeteer\n> node install.js\nERROR: Failed to download Chromium r588429! Set \"PUPPETEER_SKIP_CHROMIUM_DOWNLOAD\" env variable to skip download.\n{ Error: ENOSPC: no space left on device, write errno: -28, code: 'ENOSPC', syscall: 'write' }\nnpm WARN awx@1.0.0 No license field.\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {\"os\":\"darwin\",\"arch\":\"any\"} (current: {\"os\":\"linux\",\"arch\":\"x64\"})\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! puppeteer@1.8.0 install: `node install.js`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the puppeteer@1.8.0 install script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /root/.npm/_logs/2018-11-05T13_04_20_357Z-debug.log\nmake: *** [awx/ui/.deps_built] Error 1\n", "status": 2}
        to retry, use: --limit @/root/awx/installer/install.retry

##### ADDITIONAL INFORMATION

1. Docker awx_sdist_builder container logs
```
# docker logs -f f41088bc2d87
npm --unsafe-perm --prefix awx/ui install --no-save awx/ui
> chromedriver@2.40.0 install /awx/awx/ui/node_modules/chromedriver
> node install.js
Downloading https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
Saving to /tmp/chromedriver/chromedriver_linux64.zip
Received 781K...
Received 1566K...
Received 2350K...
Received 3134K...
Received 3769K total.
Extracting zip contents
Copying to target path /awx/awx/ui/node_modules/chromedriver/lib/chromedriver
Fixing file permissions
Done. ChromeDriver binary available at /awx/awx/ui/node_modules/chromedriver/lib/chromedriver/chromedriver
> puppeteer@1.8.0 install /awx/awx/ui/node_modules/puppeteer
> node install.js
ERROR: Failed to download Chromium r588429! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: ENOSPC: no space left on device, write errno: -28, code: 'ENOSPC', syscall: 'write' }
npm WARN awx@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.8.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-05T13_04_20_357Z-debug.log
make: *** [awx/ui/.deps_built] Error 1
```
2. NPM version in docker host
```
# npm version
{ npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.1',
  icu: '50.1.2',
  modules: '48',
  napi: '3',
  node: '6.14.3',
  openssl: '1.0.2k-fips',
  uv: '1.22.0',
  v8: '5.1.281.111',
  zlib: '1.2.7' }
```

**Comment by jakemcdermott** [comment]
Hello - thanks for creating this issue.

Looks like your node and npm versions are out of date, you'll need to update your node installation to node 8.9.0 LTS prior to running the installer and/or building the source distribution.

**Comment by ryan012880** [comment]
@jakemcdermott , I still encounter the same error with the below versions:

```
# npm version
{ npm: '6.4.1',
  ares: '1.10.1-DEV',
  cldr: '32.0',
  http_parser: '2.8.0',
  icu: '60.1',
  modules: '57',
  napi: '3',
  nghttp2: '1.32.0',
  node: '8.12.0',
  openssl: '1.0.2p',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.19.2',
  v8: '6.2.414.66',
  zlib: '1.2.11' }
```

**Comment by ryan012880** [comment]
Thanks, updated the NPM and my bad I didn't notice the line on the log ```Error: ENOSPC: no space left on device, write errno: -28, code``` so the error was due to disks space on / it reach 100% while building the image.
