### ISSUE TITLE
AWX Docker Hub tags do not match GitHub tags

### ISSUE THREAD

**Issue by LukeShortCloud** [ansible/awx#2592]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
The GitHub tagged release are *not* the same releases on Docker Hub. For example, right now on DockerHub `2.1.0` is actually constantly tracking master when the GitHub tag `2.1.0` was published on [November 1](https://github.com/ansible/awx/commit/a28f8c43cb12afb0ed35fca0c4581633b95d0b50). This leads to inconsistency of versions between the two platforms. This will likely lead to pain points for troubleshooting and reporting issues.

##### ENVIRONMENT
* AWX version: 2.Y.Z

##### STEPS TO REPRODUCE
View the container releases on Docker Hub [here](https://hub.docker.com/r/ansible/awx_task/tags/) and compare the release dates and code to the GitHub releases/tags [here](https://github.com/ansible/awx/releases).

##### EXPECTED RESULTS
The latest commits to master should push *only* to be the latest container on Docker Hub. Use the actual GitHub tags for the versioned containers (ex. 2.1.0 should actually be 2.1.0 and not 2.1.Z since Z releases aren't really being tracked right now).

Alternatively, the latest release on Docker Hub could also be tagged as 2.Y (2.1 right now).

##### ACTUAL RESULTS
All of the 2.Y.Z releases seem to be incorrectly aligned. For example, The `2.1.0` containers on DockerHub were last published on November 3rd, not from the code from November 1st.

**Comment by shanemcd** [comment]
Hi, sorry! This was a bug in our automation. The correct* 2.1.0 is being rebuilt and pushed now.
