### ISSUE TITLE
RFE: Option to select custom venv for ad-hoc jobs

### ISSUE THREAD

**Issue by benjdudas** [ansible/awx#2594]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

Add option to select ANSIBLE ENVIRONMENT for ad-hoc commands in Tower/AWX

**Comment by gamuniz** [comment]
closing as execution environments have replaced custom venv and are selectable on ad hoc jobs.
