### ISSUE TITLE
JT admin associating label gets infinite "WORKING" gear

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#2598]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
User with admin role to job template gets the UI stuck if they try to add a new label.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Create a fresh user

 - make user admin to the JT
   - this implies not giving them any permission to the JT's project or inventory, or the organization thereof
 - add a label to the JT in the UI
 - click the save button

##### EXPECTED RESULTS

Not an infinite working gear

##### ACTUAL RESULTS

Infinite working gear

![screen shot 2018-11-05 at 3 23 17 pm](https://user-images.githubusercontent.com/1385596/48024728-629cc380-e10f-11e8-81f2-eba64366d8e6.png)

##### ADDITIONAL INFORMATION

API gives 403 for the POST to `/api/v2/job_template/N/labels/`. This might be an API bug, but it's apparently an unhandled case for the UI, which makes me say _this_ is a UI bug.

I'll look, but the label permissions are probably related to organization of the labels...

**Comment by jakemcdermott** [comment]
resolved by https://github.com/ansible/awx/pull/2604

**Comment by AlanCoding** [comment]
Remains an issue after I retested it

![label_working_gear](https://user-images.githubusercontent.com/1385596/61468921-575f9000-a94c-11e9-86eb-982063f31e7d.gif)

**Comment by AlanCoding** [comment]
I might put up an API-oriented fix, or at least a proposal.

**Comment by ryanpetrello** [comment]
@AlanCoding what's the state of this issue?  Is it still broken, or did your PR fix it?

**Comment by AlanCoding** [comment]
The PR does fix it, but an API fix was not anticipated for this issue.

The PR further undermines the role of the `organization` field for labels, but I don't if that can be avoided.

If anyone wants to have this solved a different way, I can work with them on that. For instance, when the UI shows the dropdown we could filter that based on labels in orgs the user is a member of. Myself, I don't think that would be much better, but I want to get some more input on what people's preferences are for the fix.

**Comment by appuk** [comment]
The Job template admin can add labels and is not getting stuck in the infinite working gear

##### Steps performed
1. Create a workflow job template
2. Create a normal user and assign it as the Job Template Admin
3. Login as the user and add labels in the Job Template
4. Save the changes

##### Outcome:
The labels are added successsfully,

<img width="1655" alt="Screen Shot 2019-09-05 at 11 18 12 AM" src="https://user-images.githubusercontent.com/11617351/64355659-96ff3b80-cfcf-11e9-8a99-46fe0b3b0434.png">

Also, the `/api/v2/job_templates/N/labels/` doesn't throw the 403 Error

<img width="1212" alt="Screen Shot 2019-09-05 at 11 24 36 AM" src="https://user-images.githubusercontent.com/11617351/64355855-e7769900-cfcf-11e9-9501-7e95b5b5ae9e.png">
