### ISSUE TITLE
UI does not show error giving someone permission to private credential

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#2600]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
If API gives this:

> You cannot grant private credential access to another user

The UI does not give any notice to the user about what happened

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Create a new credential

Do not give an organization in the UI menu to do this

Then try to give another user access

##### EXPECTED RESULTS

The window closes and gives a popup with error message

##### ACTUAL RESULTS

the window just closes, and I have to inspect the network traffic console to see what happened

![ui_cred_perm](https://user-images.githubusercontent.com/1385596/48025407-50238980-e111-11e8-8728-015141b4a69c.gif)

**Comment by jlmitch5** [comment]
this issue was based on testing a pr that was updated--it is not present in devel
