### ISSUE TITLE
sorting add permissions user list by first name changes the total count

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#2602]
sorting the permissions page by first name, it changes the total count

This is because the original list checks for only users where is_superuser is false, but that filter is lost once the list is sorted.

![48024891-d9d25780-e10f-11e8-962e-7e7bd65cbc26](https://user-images.githubusercontent.com/1342624/48029179-98e04000-e11b-11e8-9fb2-443cb5a581b5.gif)

**Comment by nixocio** [comment]
Reopen if we see this behavior on the new UI.
