### ISSUE TITLE
Clicking on a Job Template no longer scrolls the user to the Edit Job Template view

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2603]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Clicking on a Job Template no longer scrolls the user to the Edit Job Template view

##### ENVIRONMENT
* AWX version: 3.4.0

##### STEPS TO REPRODUCE
1. Create enough JTs to take up an entire screenspace (i.e. 8+)
2. Scroll down the page
3. Click on the last JT to edit the JT.

##### EXPECTED RESULTS

Note: Working spinner. Screenspace scroll. Edit JT View.

##### ACTUAL RESULTS

Note: Working spinner. Edit JT View opened out of screenspace

**Comment by dsesami** [comment]
Verified that scrolling when clicking a job template now works on chrome/firefox latest on both fedora and windows machines in the devel branch.
