### ISSUE TITLE
Adding Team Permissions to WF doesn't do anything

### ISSUE THREAD

**Issue by tvo318** [ansible/awx#2609]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
When adding team permissions to a WF, nothing happens.

##### ENVIRONMENT
AWX 2.1.0  
Ansible 2.7.1 
* Operating System: Mac OS Serra 10.13.6
* Web Browser: Chrome Version 70.0.3538.77 (Official Build) (64-bit)

##### STEPS TO REPRODUCE

1. Add or Edit Workflow Template (and save)
2. Go to Permissions tab and use the wizard to add a team
3. Team selected, assign it a permission
4. Save the selections, wizard closes

##### EXPECTED RESULTS
Members of the previously selected team show up on the list of users and their permissions.

##### ACTUAL RESULTS

Nothing shows up on the list of users and their permissions, just the pre-populated entry for admin.

##### ADDITIONAL INFORMATION

When doing the same for users instead of Teams, the results are as expected, with chosen users having their selected permissions.

**Comment by jakemcdermott** [comment]
Took a look at this with @tvo318 - the team being used just needed some users. closing.
