### ISSUE TITLE
Schedule doesn't work

### ISSUE THREAD

**Issue by lucaslan** [ansible/awx#261]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
Schedule doesn't work

##### ENVIRONMENT

* AWX version: 1.0.0.532
* Ansible version:  2.4.0.0
* Operating System: RHEL7
* Web Browser: Firefox, Chrome, IE

##### STEPS TO REPRODUCE

Create a job template, then click in the calendar icon, click in +add, now the schedule frame is  #broken:
![image](https://user-images.githubusercontent.com/24614153/30764412-337eca70-9fc1-11e7-9a35-b989dd82b679.png)

##### EXPECTED RESULTS

Create a schedule.

**Comment by naisanza** [comment]
Related: https://github.com/ansible/awx/issues/245 and https://github.com/ansible/awx/issues/164

There's a PR you can test here: https://github.com/ansible/awx/pull/244 (see comment: https://github.com/ansible/awx/issues/245#issuecomment-331509052)

**Comment by matburt** [comment]
This is a dupe of those issues mentioned above
