### ISSUE TITLE
Custom Logo is not applied to the UI, only at Login screen

### ISSUE THREAD

**Issue by davivcgarcia** [ansible/awx#2611]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Adding a custom logo through settings changes only the logo from the Login page. The rest of the UI is still using the AWX logo (/static/assets/logo-header.svg).

##### ENVIRONMENT
* AWX version: 2.1.0
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: CentOS 7.5
* Web Browser: Chrome Version 70.0.3538.77

##### STEPS TO REPRODUCE

1. Install AWX with `awx_official=false`
2. Go to 'Settings > User Interface > Custom Logo' and add a custom logo
3. Logout and Login again

##### EXPECTED RESULTS

Both Login and Logged UIs should be using the custom logo (same behavior as Ansible Tower).

##### ACTUAL RESULTS

Only the Login UI is using the custom logo.

**Comment by wenottingham** [comment]
This is intentional. See #1316.
