### ISSUE TITLE
Missing Parent WF label and value 

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#2617]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
* Missing `Parent Workflow` label and value in project and inventory job details

##### STEPS TO REPRODUCE
* Create a Workflow Template with a project update and inventory update
* Run Workflow
* View Project Update and Inventory job details

##### EXPECTED RESULTS
<img width="401" alt="screen shot 2018-11-06 at 12 42 44 pm" src="https://user-images.githubusercontent.com/15881645/48082828-891b3700-e1c1-11e8-8792-c0627c91567f.png">

##### ACTUAL RESULTS
<img width="448" alt="screen shot 2018-11-06 at 12 42 21 pm" src="https://user-images.githubusercontent.com/15881645/48082838-90dadb80-e1c1-11e8-9afb-1ea6bd08398f.png">

**Comment by marshmalien** [comment]
Spoke with @wenottingham and @trahman73 and we decided to rename the label from "Parent Workflow" to "Source Workflow"

**Comment by elyezer** [comment]
I verified this on both Chrome and Firefox by checking the details of a Workflow within a workflow and a Job within a workflow, in both cases the source workflow were properly presented, see below:

Workflow details:

![screenshot from 2018-12-12 11-23-35](https://user-images.githubusercontent.com/48132/49872495-669fbd80-fe00-11e8-985c-dd15d487242d.png)

Job details

![screenshot from 2018-12-12 11-23-13](https://user-images.githubusercontent.com/48132/49872496-67385400-fe00-11e8-8c23-cd9ce0c390ed.png)
