### ISSUE TITLE
Implement ability to export workflows and job templates / for sync with remote AWX installations

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#2628]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
We have a setup of 8 different AWX nodes in 8 different data centres, very far away from each other with bad connectivity between. Each AWX is running jobs for local infrastructure only, but environments are identical in each country. We need to be able to run same jobs and same workflows in all 8 AWX installations, but right now we have to define them manually, clicking them in AWX interface on all 8 nodes simultaneously, which is extremely annoying.

Make it possible to export definitions for jobs from 1 AWX instance so that it can be imported on others.

**Comment by ryanpetrello** [comment]
@benapetr,

Take a peek at `tower-cli`, specifically this feature:  https://groups.google.com/forum/#!topic/awx-project/1f77RNcihZc

Given that AWX has a RESTful API, we're not likely to solve this problem in awx itself.
