### ISSUE TITLE
Workflow Template, no Jobs?

### ISSUE THREAD

**Issue by naisanza** [ansible/awx#263]
##### ISSUE TYPE

 - Feature Request

##### COMPONENT NAME

 - UI

##### SUMMARY

When creating a new Workflow Template, when trying to add a Job into the workflow, it doesn't seem to list any of the jobs that were created.

![peek 2017-09-22 16-19](https://user-images.githubusercontent.com/1614425/30767522-fa6b8f52-9fb1-11e7-9a25-d45dddd3d0ba.gif)

![screenshot from 2017-09-22 16-23-23](https://user-images.githubusercontent.com/1614425/30767581-855e8aba-9fb2-11e7-91c9-930e5b26b974.png)

##### ENVIRONMENT

* AWX version: ece93c45c9c932cfbfba2b44e217e99a6bb6a752
* Ansible version:  2.4.0.0
* Operating System: Proxmox Ubuntu 16.04 server
* Web Browser: Chrome

**Comment by matburt** [comment]
I suspect this is happening because we are filtering out some templates that require run-time selection of various components (credentials for example). Are your job templates configured to prompt for these?  What is the basic configuration of your job templates?

**Comment by matburt** [comment]
I'm also seeing a console error (shown below) where I create a job template without an inventory whose inventory is prompt-on-launch:

![image](https://user-images.githubusercontent.com/89544/30769362-ac0156e8-9fe4-11e7-8178-12980aaf5b6d.png)

**Comment by naisanza** [comment]
@matburt ~~you were right. It is filtering out Job Templates that require a prompt~~. I made them that way as a workaround with the issue that you can't modify Job Templates after they've been saved.

I suppose a better note would have helped, like if it mentioned they needed to be Job Templates without prompts?

But then again, maybe I want to specify an Inventory or credentials to use, and I don't want a separate Job Template for every different configuration?

**Also, I figured out why the Templates weren't being able to be edited.**

**Comment by naisanza** [comment]
@matburt By finding out the issue with the Template Jobs becoming uneditable in https://github.com/ansible/awx/issues/245#issuecomment-331619612, Job Templates now work correctly, and you can specify the settings for the ones that were selected to be prompted for.

![screenshot from 2017-09-23 01-23-19](https://user-images.githubusercontent.com/1614425/30771519-5f1983cc-9ffe-11e7-8848-1ee3a4b2d482.png)

**Comment by matburt** [comment]
Sounds good, I'm going to keep this open for the weekend to discuss prompt requirements for workflow jobs.

**Comment by matburt** [comment]
Going to close this one out, we'll have a fix for the job template in soon from the downstream release hardening.

**Comment by chrismeyersfsu** [comment]
> But then again, maybe I want to specify an Inventory or credentials to use, and I don't want a separate Job Template for every different configuration?

That would be a great enhancement to awx! Unfortunately, it does not yet exist.

**Comment by naisanza** [comment]
@chrismeyersfsu it actually looks like you can already do that. 

However, the functionality to "browse" for the correct credentials or inventory to use is broken. It just closes the Workflow Template window and brings you back to the Templates window. But I'm sure if you manually entered it in, it'll probably work. I haven't tested that yet

![peek 2017-09-25 14-36](https://user-images.githubusercontent.com/1614425/30832166-f598fc36-a1fe-11e7-8e6e-7d5eccfc04a5.gif)

**Comment by mabashian** [comment]
@naisanza I've gone ahead and opened up a new issue for the inv/cred lookups [here](https://github.com/ansible/awx/issues/297)
