### ISSUE TITLE
Django migration added to 2.0.1 docker image

### ISSUE THREAD

**Issue by cpatry-poly** [ansible/awx#2636]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Docker image
 - Installer

##### SUMMARY
12 days ago, the docker image awx_task, with the tag 2.0.1, was updated on docker hub.
Now, this image contains this commit: https://github.com/ansible/awx/commit/3b7336c570d476e97f0edbdd3739680321f31306

##### ENVIRONMENT
* AWX version: 2.0.1
* AWX install method: docker on linux
* Ansible version:  2.7.1
* Operating System: Debian
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Use official docker image

##### EXPECTED RESULTS

Docker image 2.0.1 should not change after release. Important changes should come with a new tag.

##### ACTUAL RESULTS

12 days ago, a new 2.0.1 image was released. It contains new django migration(s), so its incompatible with the old 2.0.1. It also upgrade ansible to 2.7.1 from 2.7.0.

##### ADDITIONAL INFORMATION
We are affected by this change because the new awx_task image 2.0.1 is still affected by this issue: https://github.com/ansible/ansible/issues/47207 .

I don't know why, because this fix should be included in ansible 2.7.1.
With the old 2.0.1 image, we manually upgraded ansible to 2.7.1, and it fixed the issue.
Now that the new image 2.0.1 is shipped with ansible 2.7.1, I still have this issue in my playbooks, and I don't know how to fix it (and I can't go back to the old 2.0.1 image).

For future changes, would it be possible not to modify an existing docker hub tag?

Thank you so much for your hard work on AWX. We particularly appreciate your latest efforts to facilitate upgrade to new AWX version.

**Comment by cpatry-poly** [comment]
Hi !
We found an error on our side which explains why we had still the issue 47207 in the new docker image 2.0.1 :-) .

This issue still remains, because it's about the recreation of a docker image without using a new tag.

**Comment by jakemcdermott** [comment]
Hello Tiduster, thanks for creating this issue.

This was probably a result of a bug in our automation (related https://github.com/ansible/awx/issues/2592), which we fixed. The correct image was pushed to docker hub a few days ago and you can expect it to remain unchanged. Apologies for any inconvenience!

**Comment by cpatry-poly** [comment]
Thanks !

My gosh, no need to apology :-) .
