### ISSUE TITLE
User's with readonly view of inv source get unnecessary error modal about not seeing project

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#2641]
If a user has read-only view of an inventory source, they should not see this error message about not being able to access the project-as the inv file dropdown is greyed out and they don't need to access the project.

![screen shot 2018-11-08 at 1 07 45 pm](https://user-images.githubusercontent.com/1342624/48218190-51de8e80-e357-11e8-87eb-f4f3ccb67b53.png)

- Create inventory source with inventory file sourced from a project.
- Log in to user that has read permission only of the inventory the source is part of.
- Click to view the source as this user.

Expected results: get greyed out form.

Actual results:

![screen shot 2018-11-08 at 1 07 45 pm](https://user-images.githubusercontent.com/1342624/48218275-84888700-e357-11e8-8c34-99ad6948b3ae.png)

We should hide this error modal if the user can not edit the source.

---

Related, if the source has an inv sync schedule associated, you can run into this by clicking to view the schedule detail from the schedules list.  You get taken to:

![screen shot 2018-11-08 at 1 07 45 pm](https://user-images.githubusercontent.com/1342624/48218370-b6015280-e357-11e8-9c3b-7aea4c81b1b9.png)

Which this error message doesn't make sense on.  It only really makes sense when you are on the edit form for the source itself and when the user has admin permission of the inventory, not the schedule.

**Comment by nixocio** [comment]
The new UI handles read only access in a different way from the previous one.
