### ISSUE TITLE
[WIP] Intermittent Permission Denied for WFJT creation or edit

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#2644]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

While doing other things in the background, I suddenly was not allowed to edit or add WFJTs.
I was given a YOU DO HAVE PERMISSION error when I clicked the "+" sign and selected "Workflow Job Template" on the Templates page.

I could then open the Workflow Visualizer for an existing WFJT, but not allowed to apply changes to it.

When I then refreshed, it seemed like my license had been removed out from under me by whatever other things I was doing in the background from another shell (not shown in screenshot).

##### ENVIRONMENT
* AWX version: workflow-convergence feature branch
* AWX install method: docker on linux
* Ansible version:  2.7
* Operating System: fedora 28
* Web Browser: Chrome

##### STEPS TO REPRODUCE
? Not sure. Maybe be successfully logged in and on Templates page but then take out license/EULA out from under yourself in a different window/view/shell.
 

##### EXPECTED RESULTS

If I'm admin, I can do anything

##### ACTUAL RESULTS

![permissiondenied_workflow](https://user-images.githubusercontent.com/29239279/48222983-f961be00-e363-11e8-8e50-68c0e3a964f4.png)

##### ADDITIONAL INFORMATION

@unlikelyzero ping...could use some more investigation to find out root cause

**Comment by unlikelyzero** [comment]
@dsesami let's try to repro while we verify 3.4 workflow features. If we can't find it, we can just mark it as closed

**Comment by dsesami** [comment]
spoke with @unlikelyzero on this, closing based on above -- isn't reproduced.
