### ISSUE TITLE
RFE: Add Workflow Template item in Organizations View

### ISSUE THREAD

**Issue by Ompragash** [ansible/awx#2648]
##### ISSUE TYPE

 - Feature Idea
 
##### COMPONENT NAME

 - UI

##### SUMMARY

When we click on Organizations, we can see multiple organizations. Each Organization shows 6 items - Users, Teams, Inventory, Project, Admin & Job Templates.

Expecting Workflow Template as a item in the organization.

**Comment by wenottingham** [comment]
Workflows are not necessarily unique to an org.

**Comment by ghost** [comment]
Correct, and same applies to other things like Users & Admin but they are still shown in Organization Views. Same applies to Workflow.

**Comment by wenottingham** [comment]
Adding API, this would need surfaced on the related fields.

**Comment by unlikelyzero** [comment]
This is now solved in the new ui
