### ISSUE TITLE
JT launch prompt modal button responsive issue

### ISSUE THREAD

**Issue by naisanza** [ansible/awx#265]
##### ISSUE TYPE

 - Feature Request

##### COMPONENT NAME

 - UI

##### SUMMARY

The Launch button is cut off

![screenshot_20170923-014312](https://user-images.githubusercontent.com/1614425/30771729-f576e554-a002-11e7-829a-31a3442fd915.png)

##### ENVIRONMENT

* AWX version: ece93c45c9c932cfbfba2b44e217e99a6bb6a752
* Ansible version:  2.4.0.0
* Operating System: Proxmox Ubuntu 16.04 server
* Web Browser: Chrome

**Comment by jlmitch5** [comment]
Thanks for filing, @naisanza!

Just a note this would probably be a good first bug if you or anyone in the community would like to take a look and open a PR.  Feel free to ping here or in the #ansible-awx IRC channel with implementation questions if needed.

**Comment by naisanza** [comment]
@jlmitch5 before I go aimlessly hunting around, do you guys have your implementation documented anywhere?
