### ISSUE TITLE
RFE: add satellite6_want_facts to enable/disable syncing of host facts 

### ISSUE THREAD

**Issue by hiyokotaisa** [ansible/awx#2659]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY

One step would be to disable sync:ing of host facts which we don't use.
Unfortunately it looks like it's hardcoded to be enabled:
https://github.com/ansible/awx/blob/devel/awx/main/tasks.py#L1929

So it would be nice to have asatellite6_want_facts parameter that could be set, similar to satellite6_want_hostcollections.

**Comment by gamuniz** [comment]
closing this as we moved from inv scripts to plugins and source vars allow you to pass this in.
