### ISSUE TITLE
awx just deleted everything

### ISSUE THREAD

**Issue by ghost** [ansible/awx#266]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
After a reboot of the host and restarting the docker containers, all my settings and work for a week were gone.

##### ENVIRONMENT
* AWX version: 1.0.0.395
* Ansible version:  2.3.2.0
* Operating System: linux
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Work for a week, restart the host, and just run all containers in docker, because it does not restart automatically.

##### EXPECTED RESULTS

Just restart the awx gui.

##### ACTUAL RESULTS

Deleted everything.

##### ADDITIONAL INFORMATION

No additional information.

**Comment by kiranos** [comment]
Default option in Inventory is:

```
# Standalone Docker Install
postgres_data_dir=/tmp/pgdocker
host_port=80
```

so its expected to delete the database if you havent changed that value to a location which will not be wiped when the host node reboots.

**Comment by wwitzel3** [comment]
Sorry to hear about you losing your configuration, that really stinks. The default runtime for awx is as a development environment and will therefore it will place data in ephmerial storage, like /tmp. As mentioned by @kiranos you will want to update your path to a location that will persisted after system restarts.

**Comment by allen00se** [comment]
@kiranos Is that an install file, or is that something that can be changed anytime?
