### ISSUE TITLE
Some operations in converging workflows causes the pending link to persist

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#2661]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
On the `workflow-convergence` branch, if you click any other node when a node hasn't been fully set up (assigned a template, the RUN option set), the pending node will disappear so you can work elsewhere. However, clicking another node's + button to create a node doesn't get rid of the pending gray node, resulting in messy error propagation. 

##### ENVIRONMENT
* AWX version: 2.1.0
* Ansible version:  2.7.0
* Operating System: Fedora 28
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create a workflow and go to the visualizer, create any sort of pending node so that it has a gray link, then instead of saving, click another node's + button.

##### EXPECTED RESULTS

The pending node vanishes and the dialogue for the clicked node appears.
##### ACTUAL RESULTS

The pending node persists.

**Comment by dsesami** [comment]
The initial case has been fixed, but there is a new way to do it still:
1) Create a pending node (the pending node in this screenshot). 
2) Click the convergence button and make a link (the gray link in this screenshot).
![screenshot from 2018-11-13 09-09-09](https://user-images.githubusercontent.com/19942822/48418708-f3812980-e723-11e8-8682-7d56b03577e7.png)

This renders the pending node uneditable.

**Comment by mabashian** [comment]
Should be addressed by https://github.com/ansible/awx/commit/68830fffc5b80c73983df1ac318c1c9d8c42a470.  Clicking on the link button should remove the pending node

**Comment by dsesami** [comment]
confirmed fixed in the `workflow-convergence` branch. will reopen if i ever find another case, though :smile:

**Comment by dsesami** [comment]
Reopening this for the `workflow-convergence` branch currently, click a node for convergence, don't set its RUN value, and click the convergence of another node instead and it persists and starts another link:
![screenshot from 2018-11-15 09-42-15](https://user-images.githubusercontent.com/19942822/48559955-c2872d00-e8ba-11e8-8f38-39eb81478db8.png)

**Comment by mabashian** [comment]
https://github.com/ansible/awx/commit/8477d96b7069a5e2cc03966e67e9c09c0c25a93c should address https://github.com/ansible/awx/issues/2661#issuecomment-439063083

**Comment by dsesami** [comment]
Confirmed fixed in the `workflow-convergence` branch.
