### ISSUE TITLE
Unable to modify a WFJT choice after initial JT selection in workflow visualizer

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2664]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Unable to modify a WFJT choice after initial JT selection in workflow visualizer

##### ENVIRONMENT
* AWX version: 3.4.0

##### STEPS TO REPRODUCE
1. Open up WF Visualizer.
2. Add a WFJT from 'Start'
3. Add a second WFJT from 'Start'
4. Click on the WFJT from step 2 or 3.
Note: cannot change project type

##### EXPECTED RESULTS
1. Able to change Project type after initial selection

##### ACTUAL RESULTS
1. Missing Project Type selection options

##### ADDITIONAL INFORMATION

<img width="1452" alt="screen shot 2018-11-12 at 2 54 33 pm" src="https://user-images.githubusercontent.com/12446869/48371868-e8c68600-e68a-11e8-8a9c-c645d2d7bca3.png">

**Comment by mabashian** [comment]
I haven't been able to reproduce this one.  A lot has changed in the last four days and this bug may have been fixed.  @unlikelyzero @dsesami are you all able to reproduce this with the most recent code changes?

**Comment by dsesami** [comment]
Haven' seen this reproduced at all. I'll defer to @unlikelyzero on final call.
