### ISSUE TITLE
Empty groups are imported as group and host when from custom script

### ISSUE THREAD

**Issue by tstuber** [ansible/awx#2668]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
We use a custom script to import the inventory. The problem is that empty ansible groups are imported as `group` AND as `host`.

##### ENVIRONMENT
* AWX version: 2.0.1
* AWX install method: docker on linux
* Ansible version:  2.7.1
* Operating System: Redhat
* Web Browser: Crome

##### STEPS TO REPRODUCE

- Set `CUSTOM_EXCLUDE_EMPTY_GROUPS = False` in `/etc/tower/settings.py` 
- Create a inventory file (ini)
```
[group-empty]
# None yet

[group-full]
host-1
```
- Create a inventory (from custom script)
- Source Script:
```
#!/bin/bash
ANSIBLE_INVENTORY_EXPORT=false ANSIBLE_CONFIG=/etc/ansible/ansible.cfg ANSIBLE_INVENTORY_ENABLED=ini,yaml,host_list,script,auto ansible-inventory -i /var/lib/awx/projects/io-ansible/prod --list --vault-password-file=/var/lib/awx/projects/io-ansible/vault_password.txt'
```
- Run the inventory import job

##### EXPECTED RESULTS

`group-empty` is imported as an empty group.

##### ACTUAL RESULTS

`group-empty` is listed as group as well as an host (as host that belongs to the group). That causes issues during ansible playbook runs.

##### ADDITIONAL INFORMATION

Looks similar to this issue:
https://github.com/ansible/awx/issues/1966

But setting only the flag does not work. If we add a sed command to add an empty host array, the import works as expected:

```
#!/bin/bash
ANSIBLE_INVENTORY_EXPORT=false ANSIBLE_CONFIG=/etc/ansible/ansible.cfg ANSIBLE_INVENTORY_ENABLED=ini,yaml,host_list,script,auto ansible-inventory -i /var/lib/awx/projects/io-ansible/prod --list --vault-password-file=/var/lib/awx/projects/io-ansible/vault_password.txt | sed -E 's/\{\}/\{\"hosts\": \[\]\}/g'
```

**Comment by AlanCoding** [comment]
Actually, https://github.com/ansible/ansible/pull/45621 has some background that seems almost certainly relevant to this report.

...will need to dig into what's happening, it could be a massive combination bug with `ansible-inventory` and AWX, maybe even config options.

But let me ask the obvious question, why would you use the `#!/bin/bash` script at all? If you have the .ini file in source control, just set the source path to the ini inventory relative path. You are effectively running `ansible-inventory` inside of `ansible-inventory` via this method.

**Comment by tstuber** [comment]
@AlanCoding Thanks for the fast feedback. The reason we use a custom script is that our deployment environment does not have direct SCM access. So the ansible code is loaded via another approach and thus is not recognized as an SCM project.
