### ISSUE TITLE
Add relaunch with prompting from jobs page.

### ISSUE THREAD

**Issue by gamuniz** [ansible/awx#2684]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API
 - UI
 
##### SUMMARY

Allow for relaunching jobs with reprompting of fields so users don't have to excessively click to relaunch a job with fresh variables.

**Comment by wenottingham** [comment]
This is not planned in this form; relaunch is a relaunch of that configuration of the job.

**Comment by 514amir** [comment]
The endgame issue is that upon debugging a job and realizing you need to make a single change to what might be a complex set of inputs to the prompts, there is no actual way to bring up the launch window as used was for this particular job and edit a specific item. 

Its either relaunch the exact same job or start from scratch.

**Comment by 514amir** [comment]
Also the factor of the amount of clicks, and scrolling, it takes to get the new launch from scratch (if you choose to go that route)

**Comment by gforster** [comment]
this would be a massive benefit to the end user and for debugging as mentioned

**Comment by mabashian** [comment]
I believe this is a dupe of https://github.com/ansible/awx/issues/2421
