### ISSUE TITLE
RFE: SAML Attribute Mapping to Specific Teams and Organizations

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/awx#2688]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

Allow mapping of SAML attributes to map to team and organization names that do not match attribute_value.

##### ADDITIONAL INFORMATION

For example,

When mapping users with SAML attribute "ansibleOrganizations" and mapping attribute_value "developer-unix-org" to the organization "Unix Developers"
```json
{
    "saml_attr": "ansibleOrganizations",
    "saml_admin_attr": "ansibleOrganizationAdmins",
    "remove": true,
    "remove_admins": true,
    "org_map": [
    {
        "organization": "developer-unix-org",
        "org_alias": "Unix Developers"
    }
  ]
}
```

When mapping users with SAML attribute "ansibleGroups" and mapping attribute_value "unix-adms" to the team "Unix Administrators":
```json
{
    "saml_attr": "ansibleGroups",
    "remove": true,
    "team_org_map": [
    {
        "team": "unix-adms",
        "organization": "Default",
        "team_alias": "Unix Administrators"
    }
  ]
}
```

**Comment by wenottingham** [comment]
While keeping this open, we recommend to have the team names match, or doing this translation on the SAML provider.

**Comment by gforster** [comment]
This would be incredibly helpful for when the SAML IDP uses LDAP. e.g - Our team names end up looking like this: cn=SOMEGROUP,ou=groups,dc=our,dc=org,dc=com

**Comment by paylocity-sflanders** [comment]
This really needs to be supported.  tower should have a way to map external saml attributes to team names.   otherwise if a AD group name is changed you may have an enormous amount of changes to make if your are storing the configuration of tower in source

**Comment by patrykk** [comment]
Hi, do you have any plans to implement this functionality soon? We keep group names in the LDAP and we couldn't translate them directly to the team names.

**Comment by chuegel** [comment]
I also look forward to see this implemented.

**Comment by one-t** [comment]
Tested - this is now working as expected

**Comment by going2thecloud** [comment]
I am trying to configure Org using SAML attribute and wondering if following feature is supported as posted in the top of this feature request. I am using Ansible Tower 3.8. I am getting error while saving this setting entered in "SAML Organization Attribute Mapping". My requirement is to add users of group belongs to okta-grp1 (mapped with ansibleOrganizations attribute) as Org Users and add users of group belongs to okta-grp2 (mapped with ansibleOrganizationAdmins attribute) as Org admins. If not supported then is there any alternative to achieve similar behavior?
Update: After looking into /sso/pipeline.py it seems like it does not support org alias in SAML Organization Attribute Mapping. Any plan to support this feature similar to what you have in SAML Team Attribute Mapping? SSO group names are not very user friendly and would definitely like to create org name using org_alias.  
```
{
    "saml_attr": "ansibleOrganizations",
    "saml_admin_attr": "ansibleOrganizationAdmins",
    "remove": true,
    "remove_admins": true,
    "org_map": [
    {
        "organization": "okta-grp1",
        "org_alias": "Some Org"
    },
    {
        "organization": "okta-grp2",
        "org_alias": "Some Org"
    }
  ]
}
```
