### ISSUE TITLE
RFE: Specify the cache max_age for Satellite 6 Inventory

### ISSUE THREAD

**Issue by hiyokotaisa** [ansible/awx#2693]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

foreman.ini can specify the cache max_age in the following section:
https://github.com/ansible/ansible/blob/devel/contrib/inventory/foreman.ini#L157

But as far as I can see cache max_age is set to 0 on AWX (so effectively disabled and hard coded): https://github.com/ansible/awx/blob/devel/awx/main/tasks.py#L1955

This means that scan_new_hosts doesn't make any difference since cache isn't used. 

So It would be great if we can specify the cache max_age from SOURCE VARIABLES.

**Comment by wenottingham** [comment]
This is intentional, inventory refreshes are intended to be a full refresh regardless of source. If we were to introduce caching, it would not be at the level of an individual source.
