### ISSUE TITLE
Missing WINRM in AWX docker 2.1.0

### ISSUE THREAD

**Issue by marcingarstka** [ansible/awx#2694]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

Unable to connect to Windows machine from AWX.
I am using http and basic authentication using local account on windows machine (no kerberos/AD authentication)

##### ENVIRONMENT
* AWX version: 2.1.0
* AWX install method: docker on linux
* Ansible version:  2.7.1
* Operating System: CentOs
* Web Browser: Chrome

##### STEPS TO REPRODUCE

I am able to connect to Windows machine from AWX host machine (CentOS)
# ansible -m win_ping -i inventory server01
server01 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}

However I am not able to ping from inside of awx_task container
# ansible -m win_ping -i inventory.yml server01
server01 | FAILED! => {
    "msg": "winrm or requests is not installed: No module named winrm"
}

It looks that winrm is not working in awx docker.

##### EXPECTED RESULTS

I expect to connect from AWX to Windows machines:

server01 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}

**Comment by jakemcdermott** [comment]
Hi marcingarstka,

Thanks for making this issue.

At this time, we do not provide dependencies for the entire set of shipped-with-Ansible modules in the environment.

The normal way to do this is to create a custom image that contains the updated libraries, system dependencies, etc.

If you have any questions, please reach out to our community mailing list or stop by our irc channel on freenode `#ansible-awx`.
