### ISSUE TITLE
Playbook runs fine locally, but in Tower it says file doesnt exist

### ISSUE THREAD

**Issue by lsantiag86** [ansible/awx#2698]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I have a playbook that works fine locally but when I put it in tower, it tells me a file doesn't exist, but it does. I added the path to "expose to isolated jobs" and I even tried turning off "enable job isolation" in tower but it still fails with same error. I assume its a permission thing, but I tried adding a few different things to my playbook including doing it all as root and still got the same result. That the file doesn't exist.  In tower I run my job template against localhost and I delegate to the node that has the tool installed that I need ran.

I reached out in ansible slack channel and the guy who helped me told me it was a bug so that is why I'm opening this.

I also thought maybe its tied to the mail module I'm trying to use.

##### ENVIRONMENT
Ansible Tower 3.2.1
Ansible version: ansible 2.4.0.0

##### STEPS TO REPRODUCE

run my playbook in ansible tower

##### EXPECTED RESULTS

I get an email with my results and csv files attached that I create in my ansible playbook

##### ACTUAL RESULTS

Locally - it works
Tower - it says file doesn't exist.

##### ADDITIONAL INFORMATION

EXAMPLE OF MY PLAYBOOK (edited and shortened)

- name: run cipa on the node that has it installed and get details on prod
  delegate_to: '{{ delegate_host }}'
  environment:
    http_proxy: '{{ http_proxy_host }}'
    https_proxy: '{{ https_proxy_host }}'
  shell: cipa --no-border -H host, host, host, host, host -d ipa.domain.com -W '{{ dm_pw_prod }}' > /tmp/output_prod.csv
  register: cipa_output_prod_detailed
  tags: run_cipa_prod_detailed

- name: run cipa on the node that has it installed and get short details on prod
  delegate_to: '{{ delegate_host }}'
  environment:
    http_proxy: '{{ http_proxy_host }}'
    https_proxy: '{{ https_proxy_host }}'
  shell: cipa -n -H host, host, host, host, host -d ipa.domain.com -W '{{ dm_pw_prod }}'
  failed_when: false
  no_log: true
  register: cipa_output_prod_short
  tags: run_cipa_prod_short

- name: email if fail is detected
  delegate_to: '{{ delegate_host }}'
  environment:
    http_proxy: '{{ http_proxy_host }}'
    https_proxy: '{{ https_proxy_host }}'
  mail:
    host: smtp.blah.com
    port: 587
    to: Lauren Santiago <lsantiag@blah.com>
    from: noreply@blah.com
    subject: IPA Consistency Report Detected Fails
    body: |
      PROD: "{{ cipa_output_prod_short.stdout }}"
      Please see attached csv file for more details
    attach:
      - /tmp/output_prod.csv
    secure: never
  when: "'CRITICAL' in cipa_output_prod_short.stdout"
  tags: email_fail

Error from tower looks like:

{
    "_ansible_parsed": true,
    "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_eDhaVG/ansible_module_mail.py\", line 355, in main\n    fp = open(file, 'rb')\nIOError: [Errno 2] No such file or directory: \"['output_prod.csv',\"\n",
    "_ansible_no_log": false,
    "_ansible_delegated_vars": {
        "ansible_delegated_host": "blah@blah.com",
        "ansible_host": "blah@blah.com"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "body": "Dev: \"CRITICAL - 15/17 checks passed\"\nQA: \"WARNING - 16/17 checks passed\"\nSTAGE: \"CRITICAL - 15/17 checks passed\"\nPROD: \"CRITICAL - 13/17 checks passed\"\nPlease see attached csv files for more details\n",
            "username": null,
            "from": "noreply@blah.com",
            "sender": "noreply@blah.com",
            "to": "Lauren Santiago <lsantiag@blah.com>",
            "cc": null,
            "charset": "us-ascii",
            "subject": "IPA Consistency Report Detected Fails",
            "bcc": null,
            "port": 587,
            "headers": null,
            "host": "smtp.blah.com",
            "timeout": 20,
            "subtype": "plain",
            "password": null,
            "attach": "['output_dev.csv', 'output_qa.csv', 'output_stage.csv', 'output_prod.csv']",
            "secure": "never"
        }
    },
    "rc": 1,
    "msg": "Failed to send mail: can't attach file ['output_dev.csv',: [Errno 2] No such file or directory: \"['output_dev.csv',\""
}

**Comment by chrismeyersfsu** [comment]
@lsantiag86 This feels like a `cwd` issue. Can you provide more of the original playbook? There are inconsistencies in the summarized version. i.e. `- /tmp/output_prod.csv` is hard coded in the example playbook but the error is saying the file is `output_dev.csv`. Further, the error is a relative path `output_dev.csv` instead of an absolute path `/tmp/output_dev.csv`. I checked to make sure the mail module doesn't do some fancy cd into the dir before calling open and it doesn't https://github.com/ansible/ansible/blob/v2.4.0.0-1/lib/ansible/modules/notification/mail.py#L355

I would try putting a debug message and printing the `cwd` or make sure you pass the absolute path.

```
- name: Find out cwd
  shell: pwd
  register: cwd
- debug: 
  debug: var=cwd.stdout
```

**Comment by lsantiag86** [comment]
@chrismeyersfsu here is my entire playbook

#DEV

- name: run cipa on the node that has it installed and get details on dev
  delegate_to: '{{ delegate_host }}'
  environment:
    http_proxy: '{{ http_proxy_host }}'
    https_proxy: '{{ https_proxy_host }}'
  shell: cipa --no-border -H idm01, idm02, idm03, idm04, idm-admin -d ipa.dev.redhat.com -W '{{ dm_pw_dev }}' > /tmp/output_dev.csv
  register: cipa_output_dev_detailed
  tags: run_cipa_dev_detailed

- name: run cipa on the node that has it installed and get short details on dev
  delegate_to: '{{ delegate_host }}'
  environment:
    http_proxy: '{{ http_proxy_host }}'
    https_proxy: '{{ https_proxy_host }}'
  shell: cipa -n -H idm01, idm02, idm03, idm04, idm-admin -d ipa.dev.redhat.com -W '{{ dm_pw_dev }}'
  failed_when: false
  no_log: true
  register: cipa_output_dev_short
  tags: run_cipa_dev_short

#QA

- name: run cipa on the node that has it installed and get details on qa
  delegate_to: '{{ delegate_host }}'
  environment:
    http_proxy: '{{ http_proxy_host }}'
    https_proxy: '{{ https_proxy_host }}'
  shell: cipa --no-border -H idm01, idm02, idm03, idm04, idm-admin -d ipa.qa.redhat.com -W '{{ dm_pw_qa }}' > /tmp/output_qa.csv
  register: cipa_output_qa_detailed
  tags: run_cipa_qa_detailed

- name: run cipa on the node that has it installed and get short details on qa
  delegate_to: '{{ delegate_host }}'
  environment:
    http_proxy: '{{ http_proxy_host }}'
    https_proxy: '{{ https_proxy_host }}'
  shell: cipa -n -H idm01, idm02, idm03, idm04, idm-admin -d ipa.qa.redhat.com -W '{{ dm_pw_qa }}'
  failed_when: false
  no_log: true
  register: cipa_output_qa_short
  tags: run_cipa_qa_short


#STAGE

- name: run cipa on the node that has it installed and get details on stage
  delegate_to: '{{ delegate_host }}'
  environment:
    http_proxy: '{{ http_proxy_host }}'
    https_proxy: '{{ https_proxy_host }}'
  shell: cipa --no-border -H idm01, idm02, idm03, idm04, idm-admin -d ipa.stage.redhat.com -W '{{ dm_pw_stage }}' > /tmp/output_stage.csv
  register: cipa_output_stage_detailed
  tags: run_cipa_stage_detailed

- name: run cipa on the node that has it installed and get short details on stage
  delegate_to: '{{ delegate_host }}'
  environment:
    http_proxy: '{{ http_proxy_host }}'
    https_proxy: '{{ https_proxy_host }}'
  shell: cipa -n -H idm01, idm02, idm03, idm04, idm-admin -d ipa.stage.redhat.com -W '{{ dm_pw_stage }}'
  failed_when: false
  no_log: true
  register: cipa_output_stage_short
  tags: run_cipa_stage_short

#PROD

- name: run cipa on the node that has it installed and get details on prod
  delegate_to: '{{ delegate_host }}'
  environment:
    http_proxy: '{{ http_proxy_host }}'
    https_proxy: '{{ https_proxy_host }}'
  shell: cipa --no-border -H idm01, idm02, idm03, idm04, idm-admin -d ipa.redhat.com -W '{{ dm_pw_prod }}' > /tmp/output_prod.csv
  register: cipa_output_prod_detailed
  tags: run_cipa_prod_detailed

- name: run cipa on the node that has it installed and get short details on prod
  delegate_to: '{{ delegate_host }}'
  environment:
    http_proxy: '{{ http_proxy_host }}'
    https_proxy: '{{ https_proxy_host }}'
  shell: cipa -n -H idm01, idm02, idm03, idm04, idm-admin -d ipa.redhat.com -W '{{ dm_pw_prod }}'
  failed_when: false
  no_log: true
  register: cipa_output_prod_short
  tags: run_cipa_prod_short

#EMAILS

- name: email if fail is detected
  delegate_to: '{{ delegate_host }}'
  environment:
    http_proxy: '{{ http_proxy_host }}'
    https_proxy: '{{ https_proxy_host }}'
  mail:
    host: smtp.redhat.com
    port: 587
    to: IAM SPAM <iamspam@redhat.com>
    from: noreply@redhat.com
    subject: IPA Consistency Report Detected Fails
    body: |
      Dev: "{{ cipa_output_dev_short.stdout }}"
      QA: "{{ cipa_output_qa_short.stdout }}"
      STAGE: "{{ cipa_output_stage_short.stdout }}"
      PROD: "{{ cipa_output_prod_short.stdout }}"
      Please see attached csv files for more details
    attach:
      - /tmp/output_dev.csv
      - /tmp/output_qa.csv
      - /tmp/output_stage.csv
      - /tmp/output_prod.csv
    secure: never
  when: "'CRITICAL' in cipa_output_dev_short.stdout or 'CRITICAL' in cipa_output_qa_short.stdout or 'CRITICAL' in cipa_output_stage_short.stdout or 'CRITICAL' in cipa_output_prod_short.stdout"
  tags: email_fail

- name: email if fail is NOT detected
  delegate_to: '{{ delegate_host }}'
  environment:
    http_proxy: '{{ http_proxy_host }}'
    https_proxy: '{{ https_proxy_host }}'
  mail:
    host: smtp.redhat.com
    port: 587
    to: IAM SPAM <iamspam@redhat.com>
    from: noreply@redhat.com
    subject: IPA Consistency Report All Passed
    body: |
      Dev: "{{ cipa_output_dev_short.stdout }}"
      QA: "{{ cipa_output_qa_short.stdout }}"
      STAGE: "{{ cipa_output_stage_short.stdout }}"
      PROD: "{{ cipa_output_prod_short.stdout }}"
      Please see attached csv files for more details
    attach:
      - /tmp/output_dev.csv
      - /tmp/output_qa.csv
      - /tmp/output_stage.csv
      - /tmp/output_prod.csv
    secure: never
  when: "'CRITICAL' not in cipa_output_dev_short.stdout and 'CRITICAL' not in cipa_output_qa_short.stdout and 'CRITICAL' not in cipa_output_stage_short.stdout and 'CRITICAL' not in cipa_output_prod_short.stdout"
  tags: email_pass

#remove created files

- name: remove the csv files
  delegate_to: '{{ delegate_host }}'
  environment:
    http_proxy: '{{ http_proxy_host }}'
    https_proxy: '{{ https_proxy_host }}'
  shell: rm -f output_*
  tags: remove_csv


It works fine when ran locally, I only get those errors when trying to run in tower that the files dont exist

**Comment by jakemcdermott** [comment]
@lsantiag86 
This is the repo for the AWX project, which is different from Tower. Please contact your support representative.

**Comment by chrismeyersfsu** [comment]
After chatting with @lsantiag86 we found out it was an Ansible `mail` module issue where the `attach:` field expects a whitespace separated string of files to attach. In never versions of Ansible (2.7) a proper yaml array is expected.

**Comment by rajeshpeta** [comment]
@chrismeyersfsu can you please explain in detail. i am also facing this issue
