### ISSUE TITLE
Upper tabs in workflow visualizer for jobs, projects, inventories not working

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#2699]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
** This is in the `workflow-convergence` branch **
f
Simply put, in the workflow visualizer when clicking a node in any way, there are three buttons at the top for jobs, project sync, and inventory sync. these buttons aren't working. So you remain stuck on the JOBS page.
![screenshot from 2018-11-15 14-28-12](https://user-images.githubusercontent.com/19942822/48576747-553bc200-e8e3-11e8-8bff-9820fe32700d.png)

##### ENVIRONMENT
* AWX version: `workflow-convergence` branch
* AWX install method: docker on linux 
* Ansible version: 2.7.0
* Operating System: Fedora 28
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Go to the workflow visualizer and try to click the `PROJECT SYNC` etc. buttons in the right side bar.

##### EXPECTED RESULTS

The buttons work.

##### ACTUAL RESULTS

The buttons don't work.

cc @mabashian

**Comment by mabashian** [comment]
Should be addressed by https://github.com/ansible/awx/commit/8477d96b7069a5e2cc03966e67e9c09c0c25a93c

**Comment by dsesami** [comment]
Confirmed repaired by `8477d96`.
