### ISSUE TITLE
Settings icon/option from left menu panel is not visible in small browser windows as well as in 100% zoom.

### ISSUE THREAD

**Issue by spathare21** [ansible/awx#27]
### Summary

Settings icon from left menu panel is not visible on 100 % zoom, as well as on small windows size. it get visible if we zoom out to 90%. 

### Branch:
Devel

### Environment
* AWX version: 1.0.0.269
* Ansible version:  2.3.1.0 
* Operating System: Fedora 25
* Web Browser: Chrome 60 , Firefox 55 64 bit.

### Steps To Reproduce:
* Clone this project and do setup/installation.
* Open the AWX Ansible instance on Chrome and firfox browser.
* Observe the left menu panel option.
* If the browser is 100% zoom you will not able to see settings icon/option on Firefox and on chrome, you will see settings option is cut.
* Double click on browser top to minimize the browser window size.
* Again observe the menu icons.
* Now zoom out the page to 90% or below. 
* Scroll the menu panel and observe menu items.

### Expected Results:
- Settings menu option from left menu panel should be visible all the time.

### Actual Results:
- Settings menu not visible on firefox on 100% zoom.
- Settings menu getting half cut on chrome browser.
- Settings option/menu gets visible if we zoom-out browser to 90% or below.
- After zoomout to 90% if we minize the window size again that option get invisible.

### Additional Information:
- Attached screen captured for more info.

![90 -zoom](https://user-images.githubusercontent.com/23230884/30156254-b0aed356-93ae-11e7-96a2-8bb6606fb727.png)

![100 _fullscreen](https://user-images.githubusercontent.com/23230884/30156280-c0f0a35c-93ae-11e7-9090-e493cc18d478.png)
![screenshot from 2017-09-07 14-37-38](https://user-images.githubusercontent.com/23230884/30156313-dc25cc88-93ae-11e7-86f4-f2136e7fe122.png)
![screenshot from 2017-09-07 14-38-16](https://user-images.githubusercontent.com/23230884/30156321-e27deb2e-93ae-11e7-9e85-e04b967053f6.png)

![chrome_1005_fullscreen](https://user-images.githubusercontent.com/23230884/30156298-cf653c86-93ae-11e7-83ba-65691d97e4b1.png)

![screenshot from 2017-09-07 14-38-38](https://user-images.githubusercontent.com/23230884/30156342-ecd8a244-93ae-11e7-9e8d-2c7103319b89.png)

**Comment by jlmitch5** [comment]
thanks @spathare21 for the report!

The plan was to follow up with a second PR follow-up to fix some things with this new navigation structure, and I'll make sure we take a look at this for that.

I'm not entirely sure how to "triage" this in terms of labeling the issue and such, so I just wanted to let you know this is noted, thanks!

**Comment by jlmitch5** [comment]
Was able to reproduce (just resizing the height of the browser to be shorter than the menu items shows the issue).

The fix here probably revolves around setting a height or max-height on the side nav element (the scrolling container), so that it doesn't go past the bottom of the screen.
