### ISSUE TITLE
clear expired sessions periodically

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/awx#2701]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY
Currently, once a user's session is expired it hangs around in the db indefinitely, or until the admin runs `awx-manage clearsessions` manually.  

This should default to clearing expired sessions once a week.  Additionally, expired OAuth2 access tokens should also be cleared out.  

##### ADDITIONAL INFORMATION

This schedule could be added here: https://github.com/ansible/awx/blob/devel/awx/settings/defaults.py#L464

And the related tasks would have to be written in `tasks.py`.  

For cleaning up revoked oauth2 tokens, call this: https://github.com/jazzband/django-oauth-toolkit/blob/5b51da74019046ef4c8c81c9975db029a2113d52/oauth2_provider/models.py

**Comment by wenottingham** [comment]
Note that ^ doesn't *default* to doing that; it essentially hardcodes it. (That may still be OK).

**Comment by rooftopcellist** [comment]
True.. @wenottingham I think this may be better as a System Job/Management Job, like `Cleanup Activity Stream`.  That way users are aware of it, and can disable it if they want.

**Comment by wenottingham** [comment]
If we're in the system job mood, we probably want system jobs for `expire_sessions` and `revoke_oauth2_tokens`...

**Comment by rooftopcellist** [comment]
implemented in #3856
