### ISSUE TITLE
Worker nodes not registering and not executing any jobs

### ISSUE THREAD

**Issue by srgvg** [ansible/awx#2705]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - Celery task workers

##### ENVIRONMENT
* AWX version: 2.1.0
* AWX install method: openshift
* Ansible version:  2.7
* Operating System: Centos (ansible docker images)

##### STEPS TO REPRODUCE

I'm having similar issues with AWX 1.7, but it really persist on a new deploy with 2.1.0
It's starting to become apparent during the import of objects (from the 1.7 deploy), especially after `tower-cli send` the first project: it stalls as the project update job never starts.

##### EXPECTED RESULTS

Jobs just execute.

##### ACTUAL RESULTS

Jobs don't start, and stay in there
```
STATUS New or Pending
STARTED Not Started
FINISHED Not Finished
```

##### ADDITIONAL INFORMATION
Originally posted on the mailing list: https://groups.google.com/d/msg/awx-project/e33bdusVu3A/muTHGxAQAQAJ 
I was asked to file a bug, as this seemed to be a bug in a recent change in AWX>

I'm seeing issues  with worker nodes not registering and not executing any jobs. This is AWX running on Openshift, in some variations (version 1.7 which is preprod/testing, and 2.1 which is a migrated instance from the former I'm testing, I also tried variations of running these with a single pod, and scaled to 3 pods), all showing the same issue.

The issue is, when worker nodes do not seem to register in the (default tower) instance group. Sometimes that can get fixed by redeploying a single pod (after scaling to 0), and only in a second step scaling back to three (race condition in rabbitmq?), sometimes it just never happens (2.1 setup, starting with one pod, scaled to three later, ..)

When hitting the plus button to add instances to a group, I can see the list of pod names that were spawned (including older scaled down pods, which seemingly are not cleaned up). When added, they come as a member of the group, but are mentioned as 'UNAVAILABLE'. witching them off and on again in that interface, makes them mentioned available..

Looking at the (docker) logs, the only error that looks important is this stacktrace, repeating continuously on the worker/task container:
```
2018-11-16 13:32:11,077 INFO spawned: 'dispatcher' with pid 1428
2018-11-16 13:32:12,079 INFO success: dispatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==2.1.0', 'console_scripts', 'awx-manage')()
  File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 108, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/run_dispatcher.py", line 122, in handle
    AutoscalePool(min_workers=4)
  File "/usr/lib/python2.7/site-packages/awx/main/dispatch/worker/base.py", line 45, in __init__
    self.pool.init_workers(self.worker.work_loop)
  File "/usr/lib/python2.7/site-packages/awx/main/dispatch/pool.py", line 209, in init_workers
    self.up()
  File "/usr/lib/python2.7/site-packages/awx/main/dispatch/pool.py", line 378, in up
    idx = random.choice(range(len(self.workers)))
  File "/usr/lib64/python2.7/random.py", line 274, in choice
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
IndexError: list index out of range
2018-11-16 13:32:13,175 INFO exited: dispatcher (exit status 1; not expected)
```
A brief look at the code, I think this means the worker pool is full, it wants assign a job to a random worker, but there are none workers...?

I checked memory, there's 8GB memory per pod and 4cpu with my last test, whih I believe should be enough.

I just also this on the awx_celery worker container:
```
sh-4.2$ ps auxwf
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
awx        4847  0.0  0.0  11816  1708 ?        Ss   14:10   0:00 /bin/sh
awx        4854  0.0  0.0  51704  1684 ?        R+   14:10   0:00  \_ ps auxwf
awx           1  0.0  0.0   4352   348 ?        Ss   13:49   0:00 /tini -- /bin/sh -c /usr/bin/launch_awx_task.sh
awx           7  0.0  0.0  11684  1500 ?        S    13:49   0:00 bash /usr/bin/launch_awx_task.sh
awx         186  0.1  0.0 114940 13920 ?        S    13:50   0:01  \_ /usr/bin/python2 /usr/bin/supervisord -c /supervisor_task.conf
awx         189  0.0  0.0 103524 10896 ?        S    13:50   0:00      \_ python /usr/bin/config-watcher
awx         190  0.1  0.3 333232 104492 ?       S    13:50   0:02      \_ python /usr/bin/awx-manage runworker --only-channels websocket.*
awx         191  0.1  0.3 328492 104224 ?       S    13:50   0:02      \_ python /usr/bin/awx-manage run_callback_receiver
awx         223  0.0  0.2 326024 93688 ?        S    13:50   0:00          \_ python /usr/bin/awx-manage run_callback_receiver
awx         225  0.0  0.2 326308 93740 ?        S    13:50   0:00          \_ python /usr/bin/awx-manage run_callback_receiver
awx         226  0.0  0.2 326332 93756 ?        S    13:50   0:00          \_ python /usr/bin/awx-manage run_callback_receiver
awx         227  0.0  0.2 326356 93880 ?        S    13:50   0:00          \_ python /usr/bin/awx-manage run_callback_receiver
```
I believe that confirms there are no worker nodes spawned?

**Comment by ryanpetrello** [comment]
@srgvg,

In the celery container, can you run:

`awx-manage shell_plus`

..and at the prompt, type `settings.SYSTEM_TASK_ABS_MEM` ?

**Comment by ryanpetrello** [comment]
@srgvg we currently have code in the latest awx that looks at total system memory and uses that as a guide to determine how many worker processes (what size the pool should be).  In your case, your traceback suggests that the `max_workers` value is being set to _zero_.  I've tried to replicate this by _forcibly_ setting the `max_workers` value to zero in my environment, and I get the same traceback:

![image](https://user-images.githubusercontent.com/214912/48627964-fb3f0900-e983-11e8-8930-869520136a3f.png)


In the `awx_celery` container, can you run:

`awx-manage shell_plus`

..and at the prompt, type:

```python
settings.SYSTEM_TASK_ABS_MEM
import psutil
psutil.virtual_memory().total
```

It might help shed some light on the issue.

**Comment by srgvg** [comment]
Same for both setups: 
```
sh-4.2$ awx-manage shell_plus
# Shell Plus Model Imports
from awx....
...import...
...
Python 2.7.5 (default, Jul 13 2018, 13:06:57) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> settings.SYSTEM_TASK_ABS_MEM
0
>>> import psutil
>>> psutil.virtual_memory().total
33550254080
>>> 
```

I didn't keep the awx installer's `inventory` (I deploy based on a yaml file we keep versioned now), so I don't know how, but ` SYSTEM_TASK_ABS_MEM` somehow got set to 0, which seems to be the now obvious culprit of all my problems. `/slap self`

I should note that this setting applies to both setups (1.0.7.2 preprod, which mostly works, until it doesn't and then restarting the pods fixes it, and 2.1.0 where it never worked).

I'm redeploying with SYSTEM_TASK_ABS_MEM set to 20, and will test this. I'll get back with further information if relevant.

**Comment by ryanpetrello** [comment]
@srgvg sounds good - if adjusting `SYSTEM_TASK_ABS_MEM` doesn't help, let us know.  In the meantime, I've merged a change that will help prevent mistakes like this: https://github.com/ansible/awx/pull/2707

**Comment by srgvg** [comment]
So far, everything seems to work as expected... Thanks for the pointers.

**Comment by batemanst** [comment]
@ryanpetrello This is somewhat tangential but is there a way to make AWX aware of Docker/cgroup memory limits? I've run into this issue a lot where the `awx-celery` container oversubscribes to memory and gets restarted by Docker.

` psutil.virtual_memory().total` reports node memory, say 16 GB, and if I'm running on k8s this will not be accurate relative to the 10-12 GB I might have given the `awx-celery` container. From there, `SYSTEM_TASK_ABS_MEM` will not be calculated correctly from a capacity perspective.

Any workarounds for that other than changing the way AWX calculates free mem? Should we set `SYSTEM_TASK_ABS_MEM` manually?

**Comment by ryanpetrello** [comment]
@batemanst 

Yep, that's exactly what we intended for scenarios like this.  You can adjust `SYSTEM_TASK_ABS_MEM` in your configmap:

https://github.com/ansible/awx/blob/devel/installer/roles/kubernetes/templates/configmap.yml.j2#L19
