### ISSUE TITLE
Add a confirmation modal when closing the workflow visualizer without saving. 

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#2708]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
I would hate to close the workflow visualizer accidentally after making several changes. A simple modal that asks "Are you sure you want to close the visualizer and abandon your changes?" is appropriate here.

**Comment by wenottingham** [comment]
This is a variation on #1267

**Comment by dsesami** [comment]
closed as this is fully duplicated
