### ISSUE TITLE
What happen when I run multiple jobs at same time on the same host?

### ISSUE THREAD

**Issue by fedelemantuano** [ansible/awx#2711]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Job Template

##### SUMMARY
I can't understand what happen when I run multiple jobs at same time on the same host.
I'd like to understand what happen if I can the same job template or different job template on the same server.
From logs I can see that AWX makes a queue for task. I know that I can remove concurrent jobs from GUI of job template, but not for different template.

Is it possibile to force a queue at playbook level?

I have scheduled jobs that have separate stop and start jboss tasks, so there is the possibility of some issue.

##### ENVIRONMENT
* AWX version: 1.0.7.2
* AWX install method: docker on linux
* Ansible version: 2.6.2
* Operating System: Red Hat
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Run the the same job template in parallel on the same host.
Run different jobs templates in parallel on the same host.

##### EXPECTED RESULTS
Queue a job level. Do one job at a time.

##### ACTUAL RESULTS
Maybe a queue for task

##### ADDITIONAL INFORMATION
None

**Comment by jakemcdermott** [comment]
hey fedelemantuano

Thanks for making this issue. You can ensure that multiple runs of the same job template run consecutively (and not in parallel) by making sure the `Enable Concurrent Jobs` box is unchecked when configuring the job template.

<img width="665" alt="screen shot 2018-11-21 at 9 26 32 am" src="https://user-images.githubusercontent.com/9753817/48847720-34a2ba80-ed70-11e8-97b2-7019c1f4212c.png">

There's no direct way to do this for multiple job templates running against the same inventory at the same time - generally speaking, this is inadvisable. For more complex organization of job template runs in your environment, you may want to see if moving your job templates into a workflow will help.

If you have any additional questions, please reach out to our community mailing list or stop by the `#ansible-awx` freenode channel on IRC.

**Comment by jakemcdermott** [comment]
> by making sure the Enable Concurrent Jobs box is checked when configuring the job template.

s/checked/unchecked
