### ISSUE TITLE
"TOTAL JOBS" field on WFJ view does not reflect number of jobs in WF, instead it is the number of nodes

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#2712]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

When I look at the detail of a WFJ, there is text that indicates the "TOTAL JOBS" a WF had in it. It is not accurate, it displays the number of nodes in the WF, not the number of jobs actually run.

##### ENVIRONMENT
* AWX version: `workflow-convergence` feature branch
* AWX install method: docker on linux
* Operating System: fedora
* Web Browser: chrome

##### STEPS TO REPRODUCE

Make a WF where some nodes will not be executed (a failure path that is not taken for example)
Run the WF
Look at the workflow job view for the completed WF.

##### EXPECTED RESULTS

TOTAL JOBS reflects number of jobs ran or different wording to say TOTAL WORKFLOW JOB NODES or something.

##### ACTUAL RESULTS

text says TOTAL JOBS but is actually TOTAL WORKFLOW JOB NODES

##### ADDITIONAL INFORMATION

View from UI (number says 500, you can see if you zoom in)
![total_job_count_is_actually_node_count](https://user-images.githubusercontent.com/29239279/48640346-70223b00-e9a4-11e8-8e4d-4cddfa7f7c7e.png)

View from API filtering on workflow job nodes with no job associated:
![nodes_that_had_no_jobs](https://user-images.githubusercontent.com/29239279/48640375-803a1a80-e9a4-11e8-9a06-e0a5f5557bba.png)

Looks like this is existing behavior, I just confirmed it happens in 3.3.1 as well.
Low priority.

**Comment by unlikelyzero** [comment]
@trahman73 can this one get moved into 3.4.0? "Total Nodes"

**Comment by trahman73** [comment]
@unlikelyzero If we can move it into 3.4, we'll just have to let @tvo318 know for any possible docs screen changes.

**Comment by dsesami** [comment]
Verified that this says "total nodes" now in devel.
