### ISSUE TITLE
Missing dependencies in INSTALL.md

### ISSUE THREAD

**Issue by Glandos** [ansible/awx#272]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME

 - Installer

##### SUMMARY

`rsync` is needed by the installer playbook

##### ENVIRONMENT
* AWX version:  git clone from 2017-09-25
* Ansible version:  2.3.2
* Operating System: Debian unstable

##### STEPS TO REPRODUCE

Run the playbook, after a fresh and basic Debian unstable installation.

##### EXPECTED RESULTS

The playbook should run until the end.

##### ACTUAL RESULTS

```

TASK [image_build : Copy logos for inclusion in sdist] ********************************************************************************************************************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to find required executable rsync in paths: /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin"}
```

**Comment by matburt** [comment]
I think we'll cover this here: https://github.com/ansible/awx/pull/267
