### ISSUE TITLE
Edit Workflow Visualizer button is missing from Edit Workflow Job Template View

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2720]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Edit Workflow Visualizer button is missing from Edit Workflow Job Template View

##### ENVIRONMENT
* AWX version: 3.4.0

##### STEPS TO REPRODUCE
1. Create a new WFJT

##### EXPECTED RESULTS

`Workflow Visualizer` button

##### ACTUAL RESULTS

No Button. Re-used Network UI icon is available on Templates List.

##### ADDITIONAL INFORMATION
Old
<img width="877" alt="screen shot 2018-11-16 at 5 11 52 pm" src="https://user-images.githubusercontent.com/12446869/48650128-f9e10100-e9c2-11e8-9506-c6e35bc98ccb.png">
new
![screen shot 2018-11-16 at 4 25 43 pm](https://user-images.githubusercontent.com/12446869/48650177-2c8af980-e9c3-11e8-946c-0895675de57c.png)

**Comment by unlikelyzero** [comment]
@trahman73 this is the awx ticket to track adding the button back

**Comment by jakemcdermott** [comment]
@unlikelyzero this is expected behavior - see https://github.com/ansible/awx/issues/2325

**Comment by unlikelyzero** [comment]
I think we're going to change it back

**Comment by unlikelyzero** [comment]
Both werk
