### ISSUE TITLE
Launching a WFJT from the Jobs list doesn't launch the Workflow Job Details

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2722]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Launching a WFJT from the Jobs list doesn't launch the Workflow Job Details

##### ENVIRONMENT
* AWX version: 3.4.0-workflow_inventory

##### STEPS TO REPRODUCE

1. Launch a WFJT
2. Navigate to the Jobs List
3. Relaunch same WFJT

##### EXPECTED RESULTS
1. Expect to be navigated to the Workflow Job Details

##### ACTUAL RESULTS
1. Remain on Jobs List

**Comment by jakemcdermott** [comment]
@unlikelyzero this is expected behavior for all job types on the job list. We do it this way to make it easier to launch multiple jobs from this view.
