### ISSUE TITLE
tower run failed but command run success

### ISSUE THREAD

**Issue by tendey** [ansible/awx#2728]
Hi.
my playbook:
- hosts: all
  user: root
  become: true
  tasks:
    - name: file-copy
      copy: 
        src: /root/tmp3
        dest: /root/tmp4
        owner: root
tower sys is ubuntu 16.04
remote sys is centos 7
I run at command window:
![image](https://user-images.githubusercontent.com/8463924/48657575-d32bd480-ea6d-11e8-897a-2157d421fab6.png)
when I run at tower
![image](https://user-images.githubusercontent.com/8463924/48657615-7e3c8e00-ea6e-11e8-94eb-a41cbda05804.png)
I had search more,but still not know why,who could tell me how I can do.

**Comment by tendey** [comment]
I used the playbook,it still failed
---
- hosts: all
  user: root
  become: true
  tasks:
    - name: file-copy
      copy: 
         src: /root/tmp2
         dest: /root/tmp3
         owner: root
         group: root
         mode: 0644

**Comment by ryanpetrello** [comment]
@tendey by default, AWX uses `bubblewrap` to prevent playbooks from accessing certain portions of the file system (for security purposes).  To confirm that this is what you're encountering, try disabling the `Enable Job Isolation` setting under `Setting -> Jobs`.

It's also possible to whitelist certain paths instead of turning this feature off entirely.  Have a look at this document and see if it helps:

https://docs.ansible.com/ansible-tower/3.3.0/html/administration/proot_func_variables.html

**Comment by tendey** [comment]
Tower file :
![image](https://user-images.githubusercontent.com/8463924/48813180-b72b7a00-ed70-11e8-91ef-35dac64a0429.png)
I want copy to this:
![image](https://user-images.githubusercontent.com/8463924/48813197-d1fdee80-ed70-11e8-9332-71772bba11e1.png)
my playbook:
![image](https://user-images.githubusercontent.com/8463924/48813286-273a0000-ed71-11e8-895a-4c47147331ae.png)
I run at command line and it is success:
![image](https://user-images.githubusercontent.com/8463924/48813333-60727000-ed71-11e8-81c3-b36285ec5800.png)
my job setting:
![image](https://user-images.githubusercontent.com/8463924/48813447-edb5c480-ed71-11e8-82a7-d71c67d12ecd.png)
my CREDENTIAL
![image](https://user-images.githubusercontent.com/8463924/48813470-0d4ced00-ed72-11e8-9715-9581f65de4a8.png)
when I run the job,result is:
![image](https://user-images.githubusercontent.com/8463924/48813506-31103300-ed72-11e8-9f24-94b7a1d342f6.png)
Of course，I had set the Enable Job Isolation to disabled
So,what can I do for you.TKS.

**Comment by tendey** [comment]
I got the exception detail：
    "exception": "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/ansible/plugins/action/copy.py\", line 457, in run\n    source = self._find_needle('files', source)\n  File \"/usr/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py\", line 1051, in _find_needle\n    return self._loader.path_dwim_relative_stack(path_stack, dirname, needle)\n  File \"/usr/lib/python2.7/dist-packages/ansible/parsing/dataloader.py\", line 322, in path_dwim_relative_stack\n    raise AnsibleFileNotFound(file_name=source, paths=[to_text(p) for p in search])\nAnsibleFileNotFound: Could not find or access '/root/tmp2' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option\n",

**Comment by tendey** [comment]
![image](https://user-images.githubusercontent.com/8463924/48831620-25dcf780-edb2-11e8-9fb7-63d36f2f3484.png)

**Comment by tendey** [comment]
![image](https://user-images.githubusercontent.com/8463924/48831695-545ad280-edb2-11e8-8092-2b991de6c771.png)

**Comment by jakemcdermott** [comment]
@tendey 

Have you tried running the job with `Enable Job Isolation` disabled, as @ryanpetrello suggested above? Can you please let us know if you see a different result after doing that? This would provide us some valuable information for diagnosing the underlying cause of what you are experiencing.

**Comment by tendey** [comment]
@jakemcdermott I had set the Enable Job Isolation disabled and then to run the copy.yml,the result was those pictures.What do you want to know,I can show you.This issue tormented me one week,I am going crazy.

**Comment by jakemcdermott** [comment]
Thank you for running with job isolation disabled, that is valuable information for finding a root cause. You should turn job isolation back on if you haven't already done so.

Can you elaborate a bit more on how you installed this? Which [AWX install method](https://github.com/ansible/awx/blob/devel/INSTALL.md) leaves you with `/var/lib/awx/projects...` running on ubuntu? 😕

**Comment by jakemcdermott** [comment]
@tendey 
Is this a Tower install? You should be reaching out to your support rep.

**Comment by jakemcdermott** [comment]
@tendey 
This looks like a Tower install? If that is the case, please reach out to your support representative. This is the repo for the AWX project, which is different from Tower.

**Comment by tendey** [comment]
OK,Thank you very much

**Comment by tendey** [comment]
I found why。because the root directory is shortlink，so the tower not searched it.But I still have a doubt,why it ran success at command line。
