### ISSUE TITLE
Trigger AWX workflows from external events

### ISSUE THREAD

**Issue by knipknap** [ansible/awx#2731]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY

Is it possible to trigger workflows from an event source, like a syslog message or a message on an AMQP bus? I am looking for a solution that is configurable in the AWX user interface and that does not require an already-running workflow.

In other words, I want to allow users to create a listener that waits for an external trigger, without polling, that creates a new workflow.

An example is syslog messages: A user should be able to specify a string, and whenever that string occurs in a syslog message, a specific workflow is executed.

**Comment by wenottingham** [comment]
Use the REST API and the workflow launch bits.

https://github.com/ansible/tower-nagios-integration is an example with nagios.
