### ISSUE TITLE
Getting "ERROR! no action detected in task" while executing ansible playbook in AWX

### ISSUE THREAD

**Issue by amit-prayag** [ansible/awx#2735]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

While executing the job template (Ansible Playbooks), from AWX GUI, get the following error:

===================================================================
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
2
3
The error appears to have been in '/var/lib/awx/projects/_6__e2e/playbooks/power/power_on.yml': line 9, column 5, but may
4
be elsewhere in the file depending on the exact syntax problem.
5
6
The offending line appears to be:
7
8
9
  - name: Turn system power on
10
    ^ here
===================================================================
##### ENVIRONMENT
* AWX version: 1.0.8.0
* AWX install method: docker on Linux, 
* Ansible version:  2.6.4
* Operating System: Cent OS 7.0
* Web Browser: Mozilla/IE/Chrome
* Python: 2.7.5

##### STEPS TO REPRODUCE

Create an Inventory,  Project, and then Job Template to include the Ansible Playbook. While running the job template e.g. to get the the NIC details or System Inventory from the HPE DL560 Gen10 and HPE SDFlex Server, getting the above mentioned error.

##### EXPECTED RESULTS

The playbook should run without error, as below.

(redfish) apandey@redfish2:~/projects/github/ansible> ansible-playbook -i hosts playbooks/get_system_inventory.yml

PLAY [System Inventory] *****************************************************************************************************************************************

TASK [Define output file] ***************************************************************************************************************************************
included: /home/apandey/projects/github/ansible/playbooks/create_output_file.yml for hawks2-4s01, dl5601

TASK [Define timestamp] *****************************************************************************************************************************************
ok: [hawks2-4s01]

TASK [Define file to place results] *****************************************************************************************************************************
ok: [hawks2-4s01]
ok: [dl5601]

TASK [Create dropoff directory for host] ************************************************************************************************************************
ok: [dl5601]
ok: [hawks2-4s01]

TASK [Getting system inventory] *********************************************************************************************************************************
ok: [hawks2-4s01 -> 127.0.0.1]
ok: [dl5601 -> 127.0.0.1]

TASK [Copy results to output file] ******************************************************************************************************************************
changed: [dl5601]
changed: [hawks2-4s01]

PLAY RECAP ******************************************************************************************************************************************************
dl5601                     : ok=5    changed=1    unreachable=0    failed=0
hawks2-4s01                : ok=6    changed=1    unreachable=0    failed=0

##### ACTUAL RESULTS
====================================================================
SSH password: 
2
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
3
4
The error appears to have been in '/var/lib/awx/projects/_37__demo_proj72232_pm/playbooks/get_system_inventory.yml': line 14, column 5, but may
5
be elsewhere in the file depending on the exact syntax problem.
6
7
The offending line appears to be:
8
9
10
  - name: Getting system inventory
11
    ^ here

=================================================================

##### ADDITIONAL INFORMATION

I have also observed the same playbook which is failing while executing with AWX, fails with CLI execution as well. For Ex. as shown below.
[root@awx _37__demo_proj72232_pm]# ansible-playbook -i hosts playbooks/get_system_inventory.yml
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/var/lib/awx/projects/_37__demo_proj72232_pm/playbooks/get_system_inventory.yml': line 14, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - name: Getting system inventory
    ^ here

===================================================================
Note: When I execute the same playbook from a different setup using CLI it woks fine, with following configuration:
===================================================================
************************
- Ansible Version 2.7.1, 
- Python 3.6.5  
- OS: SuSe Leap 15
************************
Following shows an execution of the playbook (get_system_inventory.yml) which collects the system inventory using Redfish API's:

(redfish) apandey@redfish2:~/projects/github/ansible> ansible-playbook -i hosts playbooks/get_system_inventory.yml

PLAY [System Inventory] *****************************************************************************************************************************************

TASK [Define output file] ***************************************************************************************************************************************
included: /home/apandey/projects/github/ansible/playbooks/create_output_file.yml for hawks2-4s01, dl5601

TASK [Define timestamp] *****************************************************************************************************************************************
ok: [hawks2-4s01]

TASK [Define file to place results] *****************************************************************************************************************************
ok: [hawks2-4s01]
ok: [dl5601]

TASK [Create dropoff directory for host] ************************************************************************************************************************
ok: [dl5601]
ok: [hawks2-4s01]

TASK [Getting system inventory] *********************************************************************************************************************************
ok: [hawks2-4s01 -> 127.0.0.1]
ok: [dl5601 -> 127.0.0.1]

TASK [Copy results to output file] ******************************************************************************************************************************
changed: [dl5601]
changed: [hawks2-4s01]

PLAY RECAP ******************************************************************************************************************************************************
dl5601                     : ok=5    changed=1    unreachable=0    failed=0
hawks2-4s01                : ok=6    changed=1    unreachable=0    failed=0

**Comment by ryanpetrello** [comment]
@amit-prayag,

The error message you're seeing here suggests you've got an error in your playbook's syntax, or that you're using syntax that's not supported in the installed version of Ansible.  This issue tracker is for tracking issues in AWX itself.

> I have also observed the same playbook which is failing while executing with AWX, fails with CLI execution as well.

...suggests that the issue is _likely_ in your playbook itself, not AWX.

It you need help debugging Ansible playbooks, please take a look at Ansible's mailing list or their IRC room on freenode (#ansible).

**Comment by amit-prayag** [comment]
I have updated the ansible version to 2.7.5 and Python version to Python 3.6.5, but get the following python error (AttributeError: module 'enum' has no attribute 'IntFlag'
) in AWX, while syncing the created project in AWX with GitHub Repository using URL, as listed below. 
**************************************************************************************************************
1
Traceback (most recent call last):
2
  File "/usr/bin/ansible-playbook", line 36, in <module>
3
    import shutil
4
  File "/usr/lib64/python3.6/shutil.py", line 10, in <module>
5
    import fnmatch
6
  File "/usr/lib64/python3.6/fnmatch.py", line 14, in <module>
7
    import re
8
  File "/usr/lib64/python3.6/re.py", line 142, in <module>
9
    class RegexFlag(enum.IntFlag):
10
AttributeError: module 'enum' has no attribute 'IntFlag'
**************************************************************************************************************

[root@awx _37__demo_proj72232_pm]# ansible --version
ansible 2.7.1
  config file = /var/lib/awx/projects/_37__demo_proj72232_pm/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
***************************************************************************************************************

**Comment by amit-prayag** [comment]
Does AWX version: 1.0.8.0 support the following environment?
 (1) Ansible 2.7.1, and 
 (2) Python 3.6.5

Is the error "
AttributeError: module 'enum' has no attribute 'IntFlag'" specific to Pythin 3.6.5? 

Any fix available?
Thank you.

**Comment by wenottingham** [comment]
AWX certainly doesn't support being run with python 3.6 at this point.

We have not tested an install where the ansible install is using python 3.

**Comment by amit-prayag** [comment]
Is there a way to assign a custom virtual environment in AWX 2.x?
I have created custome venv "/var/lib/awx/venv3" and want to include in AWX Organizations.
Thanks.

**Comment by amit-prayag** [comment]
I am executing the following, which doesn't seem to be working.

curl https://10.3.24.109/api/v2/organizations/N/ -i --insecure -u user:password -L
Content-Type: application/json
{
    'custom_virtualenv': '/var/lib/awx/venv/my-custom-venv'
}

**Comment by amit-prayag** [comment]
When I am setting the custom variable as "custom_virtualenv": "/var/lib/awx/venv3", using PATCH /api/v2/job_templates/42/, get the below error after PATCH:

{
    "custom_virtualenv": [
        "/var/lib/awx/venv3 is not a valid virtualenv in /var/lib/awx/venv"
    ]
}

AWX version updated to 2.1.0 now.
Is there a fix for the same?

**Comment by amit-prayag** [comment]
Following is the output of "GET /api/v2/config/".

***************************************************************************************************************
HTTP 200 OK
Allow: GET, POST, DELETE, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
X-API-Node: awx
X-API-Time: 0.384s



{
    "custom_virtualenvs": [
        "/var/lib/awx/venv/ansible/"
    ],
    "eula": "",
    "license_info": {
        "license_type": "open",
        "compliant": true,
        "valid_key": true,
        "license_key": "OPEN",
        "features": {
            "rebranding": true,
            "surveys": true,
            "multiple_organizations": true,
            "activity_streams": true,
            "ldap": true,
            "workflows": true,
            "ha": true,
            "system_tracking": true,
            "enterprise_auth": true
        }
    },
    "analytics_status": "off",
    "version": "2.1.0",
    "project_base_dir": "/var/lib/awx/projects",
    "time_zone": "UTC",
    "ansible_version": "2.7.1",
    "project_local_paths": []
}

***************************************************************************************************************

**Comment by amit-prayag** [comment]
I have created the custom virtual env within /var/lib/awx/venv now, and able to set it in AWX. Now, when I execute the playbook in AWX get the below error:
*************************************************************************************************************
ERROR! No inventory was parsed, please check your configuration and options.
*************************************************************************************************************

**Comment by ryanpetrello** [comment]
@amit-prayag,

As @wenottingham suggested, awx just doesn't support python3 at the moment - we're working on adding support in the near future.

**Comment by ryanpetrello** [comment]
FYI,

We've just released a new version of awx (https://github.com/ansible/awx/releases/tag/3.0.0) which includes support for custom virtualenvs that use python36+.
