### ISSUE TITLE
Root node link in WF visualizer can be edited to run on success or failure (undefined behavior) instead of only being set to "always".

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#2739]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
`workflow-convergence` feature branch.
Root node links can and should only be set to run "always", as they are the first step in the workflow. However, inserting a pending node before a root node, then canceling the pending node, makes the link selectable and editable, allowing you to run it on success or failure as though it was not a root node:
![screenshot from 2018-11-19 10-17-57](https://user-images.githubusercontent.com/19942822/48716405-486de580-ebe5-11e8-80da-bb83978784c9.png)

##### ENVIRONMENT
* AWX version: `workflow-convergence` branch.
* AWX install method: docker on linux
 * Ansible version:  2.7.0
* Operating System: Fedora 28
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Create a workflow.
Insert a node (pending) before a root node with the + button.
Cancel the operation.
The node link is now editable, like in the image above.

**Comment by mabashian** [comment]
Should be fixed by https://github.com/ansible/awx/commit/e1580318dd9bcac3331ff6aac9a291832be911f5

**Comment by dsesami** [comment]
fixed by latest commits in `workflow-convergence`
