### ISSUE TITLE
Feature idea: right click -> open in new tab

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#274]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY

Many links in AWX are only clickable in the context of opening in the current tab; ideally, you would be able to right-click and open in new tabs.

Some examples (not exhaustive):

- individual job link in the job list
 - breadcrumbs

##### ADDITIONAL INFORMATION

Notes from UI team:

- We leverage the ng-click directive pretty extensively throughout the application
- ng-click is set up to call an arbitrary javascript function, which may just be a `$state.go` call (which would be fairly easy to turn into a href call). If there's any sort of stateful behavior that happens inside those blocks, that won't work, though.
- As a stopgap we could look into displaying a custom right-click menu that gives the user the option to "Open link in a new tab" -- we could execute the ng-click function on click of "Open link in a new tab", then listen for the `$stateChangeStart` event. That should give us enough info to prevent the state change on the tab in focus and open a new tab at the correct state. It'd be a little weird but it could be explored if there's interest.

**Comment by senorsmile** [comment]
+1

**Comment by mabashian** [comment]
Going to prioritize the jobs list and the templates list first.  Right-click -> open in a new tab when clicking on the name/id in the list should work but currently doesn't.  We're not expecting the action items in the list to be right-clickable at this time.  Really just looking at text links.

As far as breadcrumbs go, the user should be able to right click and open in a new tab at this point in time.  AFAIK this should be working everywhere.

**Comment by mabashian** [comment]
Known lists where right clicking the name to open in a new tab does not work:

Jobs (#/jobs)
Schedules (#/jobs/schedules)
Inventories (#/inventories)
Hosts (#/hosts)
Organization name (#/organizations)
User/Team/Job Template/WFJT/Project/Inventory/Credential/Org in permissions modals throughout app
Inventory Groups (#/inventories/inventory/:id/groups)
Inventory Hosts (#/inventories/inventory/:id/hosts)
Inventory Sources (#/inventories/inventory/:id/inventory_sources)
Inventory Completed Jobs (#/inventories/inventory/:id/completed_jobs) ID/Name both don't work
Template Completed Jobs (#/templates/job_template/:id/completed_jobs) ID/Name both don't work
Template Schedule (#/templates/job_template/:id/schedules) likely that all schedules don't work
