### ISSUE TITLE
Superuser unable to remove optional org from workflow job template in UI

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#2744]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### ENVIRONMENT
* AWX version: head of devel

##### STEPS TO REPRODUCE
1. Log in as superuser
2. Create a workflow and provide an org
3. Attempt to remove the org by clearing it out of the input

##### EXPECTED RESULTS
Since org is not a required field for superusers they should be able to successfully remove the org at any time.

##### ACTUAL RESULTS
<img width="1269" alt="screen shot 2018-11-19 at 11 56 50 am" src="https://user-images.githubusercontent.com/9889020/48722529-39416480-ebf2-11e8-9acc-f17567268520.png">

An error is shown under the field and the SAVE button is disabled until you select an org

Note that the org can be removed via the api

**Comment by nixocio** [comment]
This issue was addressed on the new UI.
