### ISSUE TITLE
Workflow node activity stream does not link to workflow

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#2760]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
No links for workflow node edits

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

edit workflow nodes

view activity stream

##### EXPECTED RESULTS

lots 'o links

for creation

modification

adding or removing links

##### ACTUAL RESULTS

no links

![screen shot 2018-11-20 at 10 39 22 am](https://user-images.githubusercontent.com/1385596/48784442-b29f8c80-ecb0-11e8-9b50-af778696c717.png)

##### ADDITIONAL INFORMATION

Tested in workflow convergence branch

**Comment by ryanpetrello** [comment]
Resolved via https://github.com/ansible/awx/pull/3447
