### ISSUE TITLE
Nested workflow jobs with failure connections are very slow

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#2766]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Workflow job failure connections take a long time to run.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Create a workflow with a long chain of failure nodes.

For purposes of illustrations, make these nodes call the workflow itself, so that it fails right away

![screen shot 2018-11-20 at 2 46 17 pm](https://user-images.githubusercontent.com/1385596/48798755-54d06c00-ecd3-11e8-8739-261ceff72260.png)

Run this

##### EXPECTED RESULTS

The entire workflow should finish in under 5 seconds.

##### ACTUAL RESULTS

Takes about 2 minutes in example

##### ADDITIONAL INFORMATION

I think this is addressed by hooks added in https://github.com/ansible/awx/pull/2729

**Comment by shanemcd** [comment]
I think this can be closed if I traced this correctly.... https://github.com/ansible/awx/pull/5768 got merged.

**Comment by AlanCoding** [comment]
I hate to re-open, but the steps are very clear and really quick to reproduce.

> Create a workflow with a long chain of failure nodes.
> For purposes of illustrations, make these nodes call the workflow itself, so that it fails right away

I made one with 3 nodes in it (again, the nodes are _itself_).

Started  4/5/2023, 8:26:37 AM
Finished  4/5/2023, 8:27:24 AM

That's a time of about 50 seconds. It should really be about 1 second.

**Comment by AlanCoding** [comment]
Patched merged
