### ISSUE TITLE
UI Karma Tests failing

### ISSUE THREAD

**Issue by kialam** [ansible/awx#2770]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Running tests on `devel` results in 76 failures.
<img width="978" alt="screen shot 2018-11-20 at 6 06 26 pm" src="https://user-images.githubusercontent.com/2293210/48808537-31b3b580-ecef-11e8-9a87-ab097c0787ae.png">

##### ENVIRONMENT
* AWX version: 2.1.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

1. Run `npm run test`.
2. Observe failures.
##### EXPECTED RESULTS

No failures.
##### ACTUAL RESULTS
76 failures.

**Comment by jakemcdermott** [comment]
Having trouble reproducing this one on devel. Starting with a fresh checkout, I ran:

```
make ui-devel
npm --prefix=awx/ui run test
```

and saw these results:

```
20 11 2018 21:10:18.212:WARN [karma]: No captured browser, open http://localhost:9876/
20 11 2018 21:10:18.228:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
20 11 2018 21:10:18.229:INFO [launcher]: Launching browsers Chrome, Firefox with unlimited concurrency
20 11 2018 21:10:18.316:INFO [launcher]: Starting browser Chrome
20 11 2018 21:10:18.334:INFO [launcher]: Starting browser Firefox
20 11 2018 21:10:20.116:INFO [Chrome 71.0.3542 (Mac OS X 10.14.0)]: Connected on socket s4dAHVrv62aisnYtAAAA with id 25469368
20 11 2018 21:10:20.254:INFO [Firefox 60.0.0 (Mac OS X 10.14.0)]: Connected on socket xSBw5rEfVgxwkG7dAAAB with id 44513797
Chrome 71.0.3542 (Mac OS X 10.14.0): Executed 0 of 65 SUCCESS (0 secs / 0 secs)
20 11 2018 21:10:22.678:WARN [web-server]: 404: /static/lib/angular-tz-extensions/tz/data/northamerica
20 11 2018 21:10:22.749:WARN [web-server]: 404: /api/
Chrome 71.0.3542 (Mac OS X 10.14.0): Executed 9 of 65 (skipped 19) SUCCESS (0 secs / 0.307 secs)
Chrome 71.0.3542 (Mac OS X 10.14.0): Executed 14 of 65 (skipped 20) SUCCESS (0 secs / 0.466 secs)
Chrome 71.0.3542 (Mac OS X 10.14.0): Executed 20 of 65 (skipped 21) SUCCESS (0 secs / 0.642 secs)
Firefox 60.0.0 (Mac OS X 10.14.0): Executed 0 of 65 (skipped 1) SUCCESS (0 secs / 0 secs)
Chrome 71.0.3542 (Mac OS X 10.14.0): Executed 40 of 65 (skipped 25) SUCCESS (1.241 secs / 1.004 secs)
Firefox 60.0.0 (Mac OS X 10.14.0): Executed 40 of 65 (skipped 25) SUCCESS (1.978 secs / 1.608 secs)
TOTAL: 80 SUCCESS
```

A quick scan of [recent unit test runs in zuul](https://github.com/ansible/awx/pull/2772#issuecomment-440500772) show consistently passing results as well.

I'm not entirely certain, but the tracebacks you've provided make me wonder if your local environment is out of sync with devel somehow? Have you tried a doing a full refresh?

**Comment by ryanpetrello** [comment]
Is this still an issue @kialam ?

**Comment by kialam** [comment]
@ryanpetrello seems to be isolated to my local environment so closing this ticket.
