### ISSUE TITLE
installation on Kubernetes created with Rancher fails at database migration

### ISSUE THREAD

**Issue by mihai-satmarean** [ansible/awx#2774]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY

running the installer against a kubernetes cluster built with Rancher 2.0 does not finish, 
stuck at database migration

I am very new with Kubernetes, still maybe something that does not work.
Thank you!

##### ENVIRONMENT
* AWX version: branch devel sha: 79f483a66d1bd5cee938eef5c19074667dc268a8
* AWX install method: kubernetes on Rancher 2
* Ansible version:  2.6.2
* Operating System: mac OSX
* Web Browser: none

##### STEPS TO REPRODUCE
fill in the kuberentes variables in the inventory

```
# Kubernetes Install
kubernetes_context=myfirst
kubernetes_namespace=awx
tiller_namespace=kube-system
```
and run 
`ansible-playbook -i inventory install.yml`

##### EXPECTED RESULTS

awx gets installed

##### ACTUAL RESULTS

the task migrate databases ended in error

##### ADDITIONAL INFORMATION
`
TASK [kubernetes : Migrate database] *********************************************************************************************************************************************************************************************************
task path: /awx/installer/roles/kubernetes/tasks/main.yml:162
Wednesday 21 November 2018  09:08:40 +0100 (0:00:00.674)       0:16:26.181 ****
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "kubectl -n awx exec ansible-tower-management -- bash -c \"awx-manage migrate --noinput\"", "delta": "0:03:03.630970", "end": "2018-11-21 09:11:44.303477", "msg": "non-zero return code", "rc": 1, "start": "2018-11-21 09:08:40.672507", "stderr": "Traceback (most recent call last):\n  File \"/usr/bin/awx-manage\", line 9, in <module>\n    load_entry_point('awx==2.1.0', 'console_scripts', 'awx-manage')()\n  File \"/usr/lib/python2.7/site-packages/awx/__init__.py\", line 108, in manage\n    execute_from_command_line(sys.argv)\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py\", line 364, in execute_from_command_line\n    utility.execute()\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py\", line 356, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py\", line 283, in run_from_argv\n    self.execute(*args, **cmd_options)\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py\", line 327, in execute\n    self.check()\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py\", line 359, in check\n    include_deployment_checks=include_deployment_checks,\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/commands/migrate.py\", line 62, in _run_checks\n    issues.extend(super(Command, self)._run_checks(**kwargs))\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py\", line 346, in _run_checks\n    return checks.run_checks(**kwargs)\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/checks/registry.py\", line 81, in run_checks\n    new_errors = check(app_configs=app_configs)\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/checks/urls.py\", line 16, in check_url_config\n    return check_resolver(resolver)\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/checks/urls.py\", line 26, in check_resolver\n    return check_method()\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/urls/resolvers.py\", line 256, in check\n    for pattern in self.url_patterns:\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/urls/resolvers.py\", line 407, in url_patterns\n    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/urls/resolvers.py\", line 400, in urlconf_module\n    return import_module(self.urlconf_name)\n  File \"/usr/lib64/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\n  File \"/usr/lib/python2.7/site-packages/awx/urls.py\", line 17, in <module>\n    url(r'^sso/', include('social_django.urls', namespace='social')),\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/conf/urls/__init__.py\", line 50, in include\n    urlconf_module = import_module(urlconf_module)\n  File \"/usr/lib64/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/urls.py\", line 6, in <module>\n    from . import views\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/views.py\", line 10, in <module>\n    from .utils import psa\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/utils.py\", line 13, in <module>\n    BACKENDS = settings.AUTHENTICATION_BACKENDS\n  File \"/usr/lib/python2.7/site-packages/awx/conf/settings.py\", line 552, in __getattr_without_cache__\n    return getattr(self._wrapped, name)\n  File \"/usr/lib/python2.7/site-packages/awx/conf/settings.py\", line 456, in __getattr__\n    value = self._get_local(name)\n  File \"/usr/lib64/python2.7/contextlib.py\", line 35, in __exit__\n    self.gen.throw(type, value, traceback)\n  File \"/usr/lib/python2.7/site-packages/awx/conf/settings.py\", line 94, in _ctit_db_wrapper\n    if 'migrate' in sys.argv and get_tower_migration_version() < '310':\n  File \"/usr/lib/python2.7/site-packages/awx/main/utils/db.py\", line 14, in get_tower_migration_version\n    loader = MigrationLoader(connection, ignore_no_migrations=True)\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/loader.py\", line 52, in __init__\n    self.build_graph()\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/loader.py\", line 209, in build_graph\n    self.applied_migrations = recorder.applied_migrations()\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/recorder.py\", line 65, in applied_migrations\n    self.ensure_schema()\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/recorder.py\", line 52, in ensure_schema\n    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py\", line 254, in cursor\n    return self._cursor()\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py\", line 229, in _cursor\n    self.ensure_connection()\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py\", line 213, in ensure_connection\n    self.connect()\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/utils.py\", line 94, in __exit__\n    six.reraise(dj_exc_type, dj_exc_value, traceback)\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py\", line 213, in ensure_connection\n    self.connect()\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py\", line 189, in connect\n    self.connection = self.get_new_connection(conn_params)\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/postgresql/base.py\", line 176, in get_new_connection\n    connection = Database.connect(**conn_params)\n  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/psycopg2/__init__.py\", line 130, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\ndjango.db.utils.OperationalError: could not translate host name \"awx-postgresql\" to address: Name or service not known", "stderr_lines": ["Traceback (most recent call last):", "  File \"/usr/bin/awx-manage\", line 9, in <module>", "    load_entry_point('awx==2.1.0', 'console_scripts', 'awx-manage')()", "  File \"/usr/lib/python2.7/site-packages/awx/__init__.py\", line 108, in manage", "    execute_from_command_line(sys.argv)", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py\", line 364, in execute_from_command_line", "    utility.execute()", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py\", line 356, in execute", "    self.fetch_command(subcommand).run_from_argv(self.argv)", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py\", line 283, in run_from_argv", "    self.execute(*args, **cmd_options)", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py\", line 327, in execute", "    self.check()", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py\", line 359, in check", "    include_deployment_checks=include_deployment_checks,", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/commands/migrate.py\", line 62, in _run_checks", "    issues.extend(super(Command, self)._run_checks(**kwargs))", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py\", line 346, in _run_checks", "    return checks.run_checks(**kwargs)", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/checks/registry.py\", line 81, in run_checks", "    new_errors = check(app_configs=app_configs)", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/checks/urls.py\", line 16, in check_url_config", "    return check_resolver(resolver)", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/checks/urls.py\", line 26, in check_resolver", "    return check_method()", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/urls/resolvers.py\", line 256, in check", "    for pattern in self.url_patterns:", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/functional.py\", line 35, in __get__", "    res = instance.__dict__[self.name] = self.func(instance)", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/urls/resolvers.py\", line 407, in url_patterns", "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/functional.py\", line 35, in __get__", "    res = instance.__dict__[self.name] = self.func(instance)", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/urls/resolvers.py\", line 400, in urlconf_module", "    return import_module(self.urlconf_name)", "  File \"/usr/lib64/python2.7/importlib/__init__.py\", line 37, in import_module", "    __import__(name)", "  File \"/usr/lib/python2.7/site-packages/awx/urls.py\", line 17, in <module>", "    url(r'^sso/', include('social_django.urls', namespace='social')),", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/conf/urls/__init__.py\", line 50, in include", "    urlconf_module = import_module(urlconf_module)", "  File \"/usr/lib64/python2.7/importlib/__init__.py\", line 37, in import_module", "    __import__(name)", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/urls.py\", line 6, in <module>", "    from . import views", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/views.py\", line 10, in <module>", "    from .utils import psa", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/utils.py\", line 13, in <module>", "    BACKENDS = settings.AUTHENTICATION_BACKENDS", "  File \"/usr/lib/python2.7/site-packages/awx/conf/settings.py\", line 552, in __getattr_without_cache__", "    return getattr(self._wrapped, name)", "  File \"/usr/lib/python2.7/site-packages/awx/conf/settings.py\", line 456, in __getattr__", "    value = self._get_local(name)", "  File \"/usr/lib64/python2.7/contextlib.py\", line 35, in __exit__", "    self.gen.throw(type, value, traceback)", "  File \"/usr/lib/python2.7/site-packages/awx/conf/settings.py\", line 94, in _ctit_db_wrapper", "    if 'migrate' in sys.argv and get_tower_migration_version() < '310':", "  File \"/usr/lib/python2.7/site-packages/awx/main/utils/db.py\", line 14, in get_tower_migration_version", "    loader = MigrationLoader(connection, ignore_no_migrations=True)", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/loader.py\", line 52, in __init__", "    self.build_graph()", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/loader.py\", line 209, in build_graph", "    self.applied_migrations = recorder.applied_migrations()", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/recorder.py\", line 65, in applied_migrations", "    self.ensure_schema()", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/recorder.py\", line 52, in ensure_schema", "    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py\", line 254, in cursor", "    return self._cursor()", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py\", line 229, in _cursor", "    self.ensure_connection()", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py\", line 213, in ensure_connection", "    self.connect()", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/utils.py\", line 94, in __exit__", "    six.reraise(dj_exc_type, dj_exc_value, traceback)", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py\", line 213, in ensure_connection", "    self.connect()", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py\", line 189, in connect", "    self.connection = self.get_new_connection(conn_params)", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/postgresql/base.py\", line 176, in get_new_connection", "    connection = Database.connect(**conn_params)", "  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/psycopg2/__init__.py\", line 130, in connect", "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)", "django.db.utils.OperationalError: could not translate host name \"awx-postgresql\" to address: Name or service not known"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/Volumes/diskE/Us`

**Comment by jakemcdermott** [comment]
Hello mihai 

Thanks for creating this issue. This appears to be a configuration / infrastructure issue with your particular setup. The best place to get help with that would be our community mailing list or our irc channel on freenode (`#ansible-awx`).

**Comment by FleischKarussel** [comment]
I am experiencing the same issue with Rancher 2.1.0 and latest repo checkout.
