### ISSUE TITLE
RFE: Allow to permanently set the view of items per page in the Templates page

### ISSUE THREAD

**Issue by cesarfn4** [ansible/awx#2775]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Currently, You can set the Templates page to show 20, 50, 100 items per page, but if you set 50 or 100, and you click on other tab and then go back to the Templates page, you can see that its set to 20 items per page again.

It would be great if you could have the possibility to permanently set the view of items per page in the Templates page.

**Comment by jakemcdermott** [comment]
Hi cesarfn4 - thanks for creating this issue. This type of functionality is on the roadmap and something we'll be tracking in this issue: https://github.com/ansible/awx/issues/278

Closing this out as a duplicate.
