### ISSUE TITLE
Clicking a non-job node in visualizer fails to load right-side bar (workflow node, inventory, project)

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2777]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Clicking a non-job node in visualizer fails to load right-side bar (workflow node, inventory, project)

##### ENVIRONMENT
* AWX version: 3.4.0-workflow-convergence

##### STEPS TO REPRODUCE
1. Open Workflow Visualizer
2. Click on the Inventory or project tabs
Note: Nothing loads

**Comment by unlikelyzero** [comment]
Note: Found during Bug Bash by @dsesami

**Comment by jakemcdermott** [comment]
@unlikelyzero 

Does the `needs_test` label here imply that a fix has already been made on the convergence branch for this and that verification is needed?

**Comment by unlikelyzero** [comment]
Yes

**Comment by unlikelyzero** [comment]
Re-Reverified:
- Node selection from right hand pane for project, inventory, jobs
- Reselect existing workflow
