### ISSUE TITLE
LDAP Login issues 

### ISSUE THREAD

**Issue by bedcruncher** [ansible/awx#2778]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
I was able to successfully get this installed and setup successfully, but when I try to configure the LDAP setup for my domain I keep getting a username/password is incorrect. When I checked the docker logs for the container I see the following initially:

` 2018-11-20 19:18:01,057 DEBUG    django_auth_ldap search_s('ou=LEVEL3,ou=LEVEL2,dc=LEVEL1,dc=local', 2, '(sAMAccountName=%(user)s)') returned 1 objects: cn=myADName,ou=LEVEL4,ou=LEVEL3,ou=LEVEL2,dc=LEVEL1,dc=local
 2018-11-20 19:18:01,090 DEBUG    django_auth_ldap Created Django user myADUsername
 2018-11-20 19:18:01,090 DEBUG    django_auth_ldap Populating Django user myADUsername
 2018-11-20 19:18:01,094 WARNING  django_auth_ldap Caught LDAPError while authenticating myADUsername: NO_SUCH_OBJECT({'info': "0000208D: NameErr: DSID-0310020A, problem 2001 (NO_OBJECT), data 0, best match of:\n\t'DC=LEVEL1,DC=local'\n", 'matched': 'DC=LEVEL1,DC=local', 'desc': 'No such object'},)`

then afterwords on successive attempts I don't see anything in the logs about this, but on the login page I only get an error message "Invalid Username or Password"

##### ENVIRONMENT
* AWX version: 2.0.1 or 2.1.0 (I tried both)
* AWX install method: ansible using the git provided playbook
* Ansible version:  2.5.2
* Python version: 2.7.5
* Operating System: Centos 7
* Web Browser: Firefox/IE/Chrome

##### STEPS TO REPRODUCE
I added the following to the LDAP page to reflect my domain

LDAP Server URI
`Ldap://myserver.domain.local`

BIND DN
`CN=Ansible,OU=Service_Accounts,DC=domain,DC=local`

PASSWORD
`REMOVED`

USER SEARCH
`[
 "ou=LEVEL2,ou=LEVEL1,dc=domain,dc=local",
 "SCOPE_SUBTREE",
 "(sAMAccountName=%(user)s)"
]`

GROUP SEARCH
`[
 "dc=domain,dc=local",
 "SCOPE_SUBTREE",
 "(objectClass=group)"
]`

USER ATTRIBUTE MAP
`{
 "first_name": "givenName",
 "last_name": "sn",
 "email": "mail"
}`

USER FLAGS
`{
 "is_superuser": [
  "cn=Domain Admins,ou=Users,dc=domain,dc=local"
 ]
}`

##### EXPECTED RESULTS

A successful AD login

##### ACTUAL RESULTS

Error message stating "Invalid username and/or password"

**Comment by jakemcdermott** [comment]
Hello - thanks for creating this issue.

This looks like an issue with your configuration, infrastructure, or both. This sort of thing is best discussed on our community mailing list or in our IRC channel on freenode `#ansible-awx`.

**Comment by bedcruncher** [comment]
I am sure it isn't an infrastructure issue as it is able to successfully
connect to AD and get my user info out. So at least for the configuration
part that is correct. I am pretty positive it's a different issue.

**Comment by bedcruncher** [comment]
@jakemcdermott Can this be reopened? I'm sure that it isn't an issue with my infrastructure or configuration. I was also able to successfully authenticate against AD in a previous release as to the exact one, I don't remember off the top of my head.
