### ISSUE TITLE
On Workflow Visualizer, Project Sync and Inventory Sync do not have proper pagination controls

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2779]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
On Workflow Visualizer, Project Sync and Inventory Sync do not have proper pagination controls. JTs allow for 10 options per page. Project and Inventory Sync only allow 5 options per page.

##### ENVIRONMENT
* AWX version: 3.4.0-workflow-visualizer

##### STEPS TO REPRODUCE
1. Create at least 11 resources for JTs, Inventories, or Projects
2. Navigate to the Workflow Visualizer
3. Attempt to use pagination on JTs, Projects, and Inventories.
Note: 5 options per page on Projects and Inventories and 10 options per page for Jobs

**Comment by mabashian** [comment]
Fixed by https://github.com/ansible/awx/pull/2790/commits/c9de189fad7df9b79f57be8fcb67d2c903d5cbb8
