### ISSUE TITLE
Instance capacity is zero/unavailable and jobs pending

### ISSUE THREAD

**Issue by AbhiJram** [ansible/awx#2784]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Instance capacity is zero/unavailable and jobs pending, we are trying to do a fresh installation of 1.0.8 on openshift using standard installation. Installation goes through fine, UI also is available, however tower instance group doesn't have the main instance as available.

##### ENVIRONMENT
* AWX version: 1.0.8
* AWX install method: openshift
* Ansible version:  2.4.3
* Operating System: NA
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Follow the official installer to deploy AWX 1.0.8 in openshift, we are able to get the UI running but unable to execute any jobs/adhoc commands as tower instance is not available.

We also tried to provision the instance and register the instance, from celery awx-manage, but this did not help as well...
##### EXPECTED RESULTS

Instance group should display the available capacity for main instance.

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/25050570/48896372-7bc2a580-ee6d-11e8-99e0-559d74419354.png)

When I checked for database migration status, find this error, not sure if its related.

sh-4.2$ awx-manage check_migrations                                                                                                                                                                     
File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql                                                                                   
    raise original_exception                                                                                                                                                                            
OperationalError: no such table: conf_setting

**Comment by HarishaAmeen** [comment]
I also see the same issue with 1.0.8 in openshift. Any help would be appreciated.

**Comment by ryanpetrello** [comment]
@AbhiJram would you mind giving this another shot on the latest version of awx (3.0.0)?  Thanks.

**Comment by AbhiJram** [comment]
Hi Ryan,

We did manage to get the capacity reflected in settings.py once we changed the units of memory from Gi to Mi, so the instance is added now, not sure if this was documented somewhere, we took a while to fix the same.

And we will test the 3.0.0 soon, looks good👍

Thanks,
Abhishek

**Comment by AlanCoding** [comment]
Any updates here? latest version does a lot to surface the reasons that capacity is zero.

**Comment by KALX9** [comment]
We are having an issue, wherein no job are running.  
Below is the status....

bash-4.4# awx-manage list_instances
[tower capacity=0 policy=100%]
        awx capacity=0 version=17.0.1
![Capture](https://user-images.githubusercontent.com/73586362/176894940-c8728223-fe4f-4426-8fbc-5a858ac1419d.JPG)

**Comment by AlanCoding** [comment]
You should be able to click on the instance and get error text now. That's the hope.

**Comment by gamuniz** [comment]
closing as installation method no longer supported
