### ISSUE TITLE
Prompt on launch option for Instance Group in a job template

### ISSUE THREAD

**Issue by rbergami** [ansible/awx#2785]
**ISSUE TYPE**
- Request for Enhancement

**COMPONENT NAME**
- UI
- API

**SUMMARY**

It's not possible in the latest awx version to have the _Prompt on Launch_ checkbox for the Instance Groups selection in the Template definition screen.

This today forces the user to have the same template replicated as many times the number of Instance Groups available in the scenario since it's not possible to spacify it via survey at launch. When you have isolated nodes working on different VLANs this is very annoying.

![screenshot from 2018-11-22 11-35-10](https://user-images.githubusercontent.com/17081949/48906875-2b941500-ee66-11e8-965f-a26280bbc41d.png)

![154289775867143533](https://user-images.githubusercontent.com/17081949/48909298-2c7c7500-ee6d-11e8-9abd-226b3338d049.gif)

**Comment by wenottingham** [comment]
> This today forces the user to have the same template replicated as many times the number of Instance Groups available

What are you trying to do here that couldn't be done by setting the instance group on the inventory?

**Comment by christianmarangoni** [comment]
In machine provisioning scenario, start from scratch, the global inventory ( Satellite as Example ) have all hosts but the machine is possible\needed to deploy in a target environment ( devel as example ) where only dedicate instance group are able to communicate ( network segregation for security reason ).

This is the scenario where we request to manage dynamically the Selection of Instance group.

**Comment by wenottingham** [comment]
Why not build a smart inventory filtered based on target facts that is then tied to the instance group?

**Comment by christianmarangoni** [comment]
Our provisioning, application deployment & configuration interact with Customer Change Management and parse\start from a file ( yaml ).
In this automation scenario, we want to achieve a flexible way that not required more variable ( inventory ) external from customer provisioning.

The Above scenario is a scenario where a customer wants automation and integration with the other tools flow.
Build a smart inventory and fix a specific instance group is an additional step ( workaround at the moment ) that is not required at provisioning start.

**Comment by wenottingham** [comment]
My concerns are:
- one of the use cases of Instance Groups is for the administrator to segment capacity. Prompting for instance groups on launch can subvert that. (It would need to, at a minimum, be restricted to instance groups attached to the organization)
- The suggested flow requires the user to know what Instance Group to select based on some knowledge they have on the host. Finding a way to make that happen automatically seems better than relying on the user to select the right group

**Comment by christianmarangoni** [comment]
About First concern:

Agree for the start of think instance as "load Worker".
Instance, an isolated moreover, are the best scenario for manage network segmentation, not all time is possible to create a specific inventory for instance or a smart inventory from a filter.
Selection to point only to the network segment or remote branch is the best Have 

Knowledge is not synonymous of automation, automation methodology that starts from an internal flow and evolves the process as smart as possible.
If we put other constraints "knowledge of inventory" we don't do it in a smart way.

thanks

**Comment by wenottingham** [comment]
combining into #5711
