### ISSUE TITLE
How to Shutdown and Start up Ansible AWX opensource version (Correct Approach)

### ISSUE THREAD

**Issue by alagirir** [ansible/awx#2786]
##### ISSUE TYPE
 
 - Documentation

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY
I am not sure what is the right process to shutdown and start the Ansible tower AWX open source version

##### ENVIRONMENT
* AWX version: 2.1.0
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: Centos
* Web Browser: Firefox

information. -->

Could you please let me know how to Shutdown and Start up Ansible AWX opensource version (Correct Approach). As it is docker containers, I am not sure what is the right way. Please clarify.

**Comment by wenottingham** [comment]
This is not a bug report; this is best handled via the normal contact mechanisms listed in the readme.
    Join the #ansible-awx channel on irc.freenode.net
    Join the mailing list (https://groups.google.com/forum/#!forum/awx-project)
