### ISSUE TITLE
Azure missing pip dependency

### ISSUE THREAD

**Issue by Papina** [ansible/awx#2787]
##### ISSUE TYPE
 - when running an azure_rm_* template, an error is generated:

##### COMPONENT NAME
 - Templates
 - Azure_rm

##### SUMMARY
error is generated when running any azure_rm_* template

`FAILED! => {"changed": false, "msg": "Do you have packaging installed? Try `pip install packaging`- No module named packaging.version"}
`

##### ENVIRONMENT
* AWX version: 2.1.0
* AWX install method: docker on linux
* Ansible version:  2.7.1
* Operating System: /etc/redhat-release : Red Hat Enterprise Linux Server release 7.6 (Maipo)
* Web Browser: Chrome/Firefox

##### STEPS TO REPRODUCE

1. Create an azure inventory, and make the source with the relevant credentials. sync the inventory to gather the hosts
2. create a template with the following code

```
---
- name: Azure Lists
  hosts: all
  tasks:
  
    - name: Get facts for all zones
      azure_rm_dnszone_facts:
        resource_group: Wordpress-RG
```

run the template against the Azure inventory

##### EXPECTED RESULTS

should show results of the script

##### ACTUAL RESULTS

```
Identity added: /tmp/awx_308_6vytFz/credential_3 (/tmp/awx_308_6vytFz/credential_3)
Using /etc/ansible/ansible.cfg as config file
PLAY [Azure Lists] *************************************************************

TASK [Gathering Facts] *********************************************************
ok: [debian-wp]

TASK [Get facts for all zones] *************************************************
fatal: [debian-wp]: FAILED! => {"changed": false, "msg": "Do you have packaging installed? Try `pip install packaging`- No module named packaging.version"}

PLAY RECAP *********************************************************************
debian-wp                  : ok=1    changed=0    unreachable=0    failed=1  
``` 

##### ADDITIONAL INFORMATION
Docker version 18.09.0, build 4d60db4

```
# docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                                 NAMES
29f14d38fe3e        ansible/awx_task:2.1.0       "/tini -- /bin/sh -c…"   2 weeks ago         Up 5 days           8052/tcp                                              awx_task
d8d4b23cd6f8        ansible/awx_web:2.1.0        "/tini -- /bin/sh -c…"   2 weeks ago         Up 5 days           0.0.0.0:80->8052/tcp                                  awx_web
e7598eaae1f7        memcached:alpine             "docker-entrypoint.s…"   2 weeks ago         Up 5 days           11211/tcp                                             memcached
db82dbbeca60        ansible/awx_rabbitmq:3.7.4   "docker-entrypoint.s…"   2 weeks ago         Up 5 days           4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 25672/tcp   rabbitmq
c564fd174834        postgres:9.6                 "docker-entrypoint.s…"   2 weeks ago         Up 5 days           5432/tcp                                              postgres
```

**Comment by wenottingham** [comment]
You didn't specify to run that playbook on the AWX host - it's running on the managed host, which would likely need Azure libs installed there.

Does it work if you do 'connection: local' on the task?

**Comment by Papina** [comment]
ah, this worked for most of the most of the fact gathering modules i was testing except azure_rm_virtualmachine_facts

but this gives a different issue and i will log as a separate job. thanks Bill!

**Comment by wenottingham** [comment]
OK, closing.
