### ISSUE TITLE
Feature idea: customizable list display / something better than lists

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#279]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY

Common request for AWX is "why doesn't the JT list (or jobs list) display `X`?".  Generally, each user asks for a different `X` (user, launch time, inventory used, credential, etc.).

Similarly, we allow filtering by many many fields... without necessarily showing the filtered field.

Suggestion is a two-pronged approach:
- Move the list display to something more table-like, that displays more information out of the box
- Allow the users to have preferences on what is displayed in that table

##### ADDITIONAL INFORMATION

Depends on https://github.com/ansible/awx/issues/278

**Comment by AlanCoding** [comment]
Related #641 #640 #639

**Comment by jlmitch5** [comment]
@wenottingham we do this now
