### ISSUE TITLE
Links to edit management job schedule don't work

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#2797]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### ENVIRONMENT
* AWX version: head of devel

##### STEPS TO REPRODUCE
1. As an admin user, navigate to the management jobs page
2. Click the schedule icon for one of the management jobs listed
3. Attempt to click on the name/pencil icon of the schedule listed

##### EXPECTED RESULTS
Clicking name/pencil icon navigate the user to a form with all the appropriate schedule fields filled out

##### ACTUAL RESULTS
Clicking name/pencil icon do nothing

##### ADDITIONAL INFORMATION
<img width="1283" alt="screen shot 2018-11-26 at 3 39 58 pm" src="https://user-images.githubusercontent.com/9889020/49041010-0b2fc780-f192-11e8-9846-6e8f0217a3b3.png">

Note that if the user attempts to enter this flow via the Schedules tab it is equally broken.

**Comment by dsesami** [comment]
Verified in devel.
