### ISSUE TITLE
Nature of license

### ISSUE THREAD

**Issue by sspreitzer** [ansible/awx#28]
Hello

I try to identify the nature of license and if it is one of the FLOSS license models commonly known as well as admissable by the Fedora Project?

References:
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#SoftwareLicenses
* http://www.gnu.org/philosophy/license-list.html#GPLCompatibleLicenses
* https://opensource.org/licenses/

Would you consider a popular license for this project?

Thank you very much
Sascha

**Comment by wwitzel3** [comment]
We are using Apache License 2.0
https://github.com/ansible/awx/blob/devel/LICENSE.md

**Comment by sspreitzer** [comment]
Thank you!

There is also https://github.com/ansible/awx/blob/devel/COPYING, could that be removed then?

**Comment by wenottingham** [comment]
Sure, done.

**Comment by sspreitzer** [comment]
:+1:
