### ISSUE TITLE
Feature: update to AngularJS 1.6.x

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#280]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
We're currently on AngularJS 1.4.14.

We should move to the current release, 1.6.6 (or later, as they come out.)

This probably involves fixing a large variety of minor (or major) things.

##### ADDITIONAL INFORMATION

There's a limitation in rendering SVG elements beyond a certain depth in Angular 1.4 that isn't an issue in 1.6. v1.5+ also introduces proper support for components (as opposed to directives we refer to as components), potentially making a transition to Angular 2 a bit easier if we decide to go that route at some point in the distant future.

**Comment by wenottingham** [comment]
This happened.

**Comment by wenottingham** [comment]
actually - doublechecking - @marshmalien can we close this?

**Comment by marshmalien** [comment]
@wenottingham Yes, we can close this. We upgraded to Angular 1.6.

**Comment by achrafbouchiba** [comment]
i want to add a new item in the sidebar template , i want to know where is the file .html for this template
