### ISSUE TITLE
In workflow Visualizer, Auditors cannot see Jobs on the Node selection view

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2803]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
In workflow Visualizer, Auditors cannot see Jobs in the Node selection view

##### ENVIRONMENT
* AWX version: 3.4.0-devel

##### STEPS TO REPRODUCE
1. Create a system auditor attached to an org
2. Ensure that the org has a workflow with at least 1 JT or WFJT.
3. As the system auditor, open the workflow visualizer and attempt to view the Jobs List in the Node selection screen
Note: Inventory and Project Nodes are available. Jobs are not listed

##### ADDITIONAL INFORMATION

![screen shot 2018-11-26 at 7 50 23 pm](https://user-images.githubusercontent.com/12446869/49051220-ec8ef800-f1b4-11e8-8b18-161c34a5cc20.png)

**Comment by AlanCoding** [comment]
I think this is because the UI filters that list to only show templates that the user has execute access to. In the case of a user who is purely system auditor, there are no such templates.

The wording of "please add items to this list" is unfortunate in such cases.

**Comment by mabashian** [comment]
I think we'll be able to close this one out once the workflow convergence branch is merged.  In that branch we added a read-only view when clicking on a node that does not include the lists but only static data from the node endpoint.

**Comment by unlikelyzero** [comment]
@mabashian @AlanCoding I can verify that it is fixed in workflow-convergence
