### ISSUE TITLE
Producing artifacts upstream of inventory updates hangs the task manager

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#2806]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
If a workflow contains job nodes that have inventory nodes downstream of it (always connection makes it easy to reproduce), then the task manager will hang and all jobs will stop running.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

 - Create a workflow
 - add a node that does `set_stats`
 - add an inventory update to always nodes of that node

##### EXPECTED RESULTS

runs

##### ACTUAL RESULTS

stops running half-way through

##### ADDITIONAL INFORMATION

Re-filing from reports in conversation in older issue

https://github.com/ansible/awx/issues/2642#issuecomment-441990894

**Comment by oekotaco** [comment]
Have tested here in my Environment (as reported in the initial Bug-Report) and works like a charm.

**Comment by kdelee** [comment]
Works for me!

**Comment by mhurron** [comment]
I deleted the workflow that was causing the error and created a new one. The old job was created on awx < 2.0, the new one on awx 2.1.0.

I first created the workflow without the inventory sync at the end - this worked.
I added the inventory sync to the workflow - this worked.

It would appear that workflows created on awx 2.0 do not have whatever was causing the issue before.
