### ISSUE TITLE
In Workflow Viz, when adding a new node with the + action, the previously selected node is automatically attached as the new link

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2808]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
In Workflow Viz, when adding a new node with the + action, the previously selected node is automatically attached as the new link

##### ENVIRONMENT
* AWX version: 3.4.0-workflow-convergence

##### STEPS TO REPRODUCE
1. Create a WF with multiple nodes
2. Edit WF in WF Viz
3. Select any node, 
4. Now, select the + action to create a new link
Note: the previously selected node is automatically selected for the new link. Presumably with all associated prompts

##### EXPECTED RESULTS
On 4, no selected link

##### ACTUAL RESULTS
Previously selected link

##### ADDITIONAL INFORMATION
![preselect](https://user-images.githubusercontent.com/12446869/49094675-c7da6500-f234-11e8-9475-b5c9f6bfd546.gif)

**Comment by mabashian** [comment]
This should be addressed by https://github.com/ansible/awx/commit/76b9721ddb78f9079facff9b57904d776971da07

**Comment by dsesami** [comment]
Clicking the + sign while a node is highlighted was tested and verified.
Other scenarios verified:
- Clicking the convergence link while another node is selected
- Canceling a convergence link after the above test, without selecting a RUN condition.
- Clicking to delete another node while a node is selected.
