### ISSUE TITLE
configure celery queues from DB instead of command line args

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#281]
##### ISSUE TYPE
 - Enhancement

##### COMPONENT NAME
 - API

##### SUMMARY

We currently control what queues celery listens to in [1] and [2]. This is rather rigid. It is set at image build or image runtime and can only be changed by rebuilding the image or relaunching the container.

Going forward, we want to be able to manage instance groups via the API. Allowing for this feature depends on being able to dynamically control what queues celery workers listen to.

This card is to track work that involves communicating with live celery worker(s) to dynamically change the queues the workers service.

1. https://github.com/ansible/awx/blob/devel/tools/docker-compose/supervisor.conf
2. https://github.com/ansible/awx/blob/devel/installer/image_build/files/supervisor_task.conf

**Comment by matburt** [comment]
See #74 also

**Comment by matburt** [comment]
Implemented in #303
