### ISSUE TITLE
No credential is available when creating an inventory sourced from a project

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/awx#2812]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - GUI

##### SUMMARY
No credential is available when creating an inventory sourced from a project, although some machine & source control credentials have already been created
Or maybe I'm missing something...

##### ENVIRONMENT
* AWX version: 2.1.0
* AWX install method: docker on linux
* Ansible version:  2.7.2
* Operating System: Debian buster
* postgresql: 9.6.10-0+deb9u1
* Web Browser: chrome 70.0.3538.110 (Official Build) (64-bit)

##### STEPS TO REPRODUCE

- create some machine & source control credentials
- create a git project
- create an inventory
- create an inventory sourced from that project
- try to add a credential

##### EXPECTED RESULTS

Ability to add a credential

##### ACTUAL RESULTS

![no credential](https://user-images.githubusercontent.com/13176858/49098385-0a209800-f26f-11e8-9bd5-b4b5840088c0.png)

Error message when saving the inventory source without credential:
![inventory source without credential](https://user-images.githubusercontent.com/13176858/49098690-c712f480-f26f-11e8-9e37-abb0706d1f23.png)

##### ADDITIONAL INFORMATION

The project update is fine.

**Comment by AlanCoding** [comment]
SCM source inventory sources will only take cloud-type credentials. The list is probably empty because you have no cloud credentials.

**Comment by jean-christophe-manciot** [comment]
@AlanCoding 
There is a discrepancy here:
- the project is correctly cloned from a user-defined (non cloud-type) git repository with a **Source Control** type credential
- the inventory is defined as being sourced from the aforementioned project

Yet, you're saying that inventory sources do not take "Source Control" type credentials.
I'm assuming that by cloud-type you mean AWS, GCP, Azure, .... and not Source Control.
Either it's a missing feature, or there is an issue somewhere.

The **bottom line** is: as an admin, I should not need extra/different credentials to access an inventory that is part of an already cloned git project.

**Comment by AlanCoding** [comment]
> The bottom line is: as an admin, I should not need extra/different credentials to access an inventory that is part of an already cloned git project.

True. You should only need use role to the project, and you should be able to create and sync the inventory source without adding credentials.

> I'm assuming that by cloud-type you mean AWS, GCP, Azure, .... and not Source Control.

Correct, the inventory may be syncing content from AWS, GCP, etc.

**Comment by jean-christophe-manciot** [comment]
In order to figure out what is happening, I deleted the project & the inventory, including all groups & hosts.
- I recreated the project from scratch with the same settings:
   + SCM type: git
   + SCM URL:non public cloud git repository on the local host
   + SCM credential: source control
   + SCM Update option: Clean & Update revision on launch
- after its creation, the project is correctly cloned (except for the roles which will be dealt with in another bug report):
```
...
PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0   
```
- I recreated the inventory sourced from the same source:
   + Source: Sourced from a project
   + Credential: None
   + Project: aforementioned project
   + Inventory file: hosts (chosen from the drop-down list)
   + Verbosity: Debug
   + Update Options: Overwrite, Overwrite variables & Update on project change
- the first sync after creation triggers an **exception (3)** which is detailed only in the "ERROR DETAILS" on the left-hand side & the stdout is completely empty on the right-hand side (despite ```VERBOSITY
2 (DEBUG)```:
```
Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 930, in run self.pre_run_hook(instance, **kwargs) File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 2177, in pre_run_hook project_update_task().run(local_project_sync.id) File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 621, in _wrapped return f(self, *args, **kwargs) File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 1074, in run raise AwxTaskError.TaskError(instance, rc) Exception: project_update 3 (failed) encountered an error (rc=2), please see task stdout for details.
```
- I manually synced the project & the inventory source which lead to... a correct load of all groups & hosts detailed in the hosts file:
```
...
2018-12-04 16:15:37,831 DEBUG    awx.main.models.inventory Going to update inventory computed fields
2018-12-04 16:15:37,955 DEBUG    awx.main.models.inventory Finished updating inventory computed fields
    3.229 INFO     Inventory import completed for git-project-playbooks.inventory.source in 1.1s
```
- I checked in the inventory "GROUPS" & "HOSTS" tabs that the objects were correctly created
- if I perform another manual sync, I get another **exception (7)** with again no stdout:
```
Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 930, in run self.pre_run_hook(instance, **kwargs) File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 2177, in pre_run_hook project_update_task().run(local_project_sync.id) File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 621, in _wrapped return f(self, *args, **kwargs) File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 1074, in run raise AwxTaskError.TaskError(instance, rc) Exception: project_update 7 (failed) encountered an error (rc=2), please see task stdout for details.
```
- Another manual sync leads to another **exception (9)** with no stdout:
```
Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 930, in run self.pre_run_hook(instance, **kwargs) File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 2177, in pre_run_hook project_update_task().run(local_project_sync.id) File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 621, in _wrapped return f(self, *args, **kwargs) File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 1074, in run raise AwxTaskError.TaskError(instance, rc) Exception: project_update 9 (failed) encountered an error (rc=2), please see task stdout for details.
```

The same ```manual sync``` leads to different results without any different settings between them.

**Comment by AlanCoding** [comment]
This is very interesting behavior to me. It sounds like the project job_type=check runs are successful, but job_type=run are not successful.

From the error messages, both project updates 3 and 7 were pre-run syncs (job_type=run) and failed for a yet-unknown reason. Could you have a peek at relative URLs `/api/v2/project_updates/3/stdout/` and `/api/v2/project_updates/7/stdout/`, and share whatever interesting information is there? There's a good chance that will expose something that we could fix.

**Comment by jean-christophe-manciot** [comment]
```http://172.22.0.1/api/v2/project_updates/3/stdout/```:
--------------------------------------------------------------------
```
TASK [check repo using git] ****************************************************
ok: [localhost]

PLAY [all] *********************************************************************

TASK [detect requirements.yml] *************************************************
ok: [localhost]

TASK [fetch galaxy roles from requirements.yml] ********************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["ansible-galaxy", "install", "-r", "requirements.yml", "-p", "/var/lib/awx/projects/_6__git_project_playbooks/roles/"], "delta": "0:00:29.622386", "end": "2018-12-04 16:15:22.499505", "msg": "non-zero return code", "rc": 250, "start": "2018-12-04 16:14:52.877119", "stderr": "\\u001b[0;31mERROR! Unexpected Exception, this is probably a bug: [Errno 21] Is a directory: u'/var/lib/awx/projects/_6__git_project_playbooks/roles/git-Project-Roles/git-Project-Roles/group_vars/ios_xev/16.5.1b'\\u001b[0m", "stderr_lines": ["\\u001b[0;31mERROR! Unexpected Exception, this is probably a bug: [Errno 21] Is a directory: u'/var/lib/awx/projects/_6__git_project_playbooks/roles/git-Project-Roles/git-Project-Roles/group_vars/ios_xev/16.5.1b'\\u001b[0m"], "stdout": "- extracting git-Project-Roles to /var/lib/awx/projects/_6__git_project_playbooks/roles/git-Project-Roles\\nto see the full traceback, use -vvv", "stdout_lines": ["- extracting git-Project-Roles to /var/lib/awx/projects/_6__git_project_playbooks/roles/git-Project-Roles", "to see the full traceback, use -vvv"]}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1   
```
It appears that the current issue is linked to the roles sync issue I mentioned earlier: in the root of the ```git_project_playbooks```, there is a roles folder containing the following ```requirements.yml``` file:
```
- src: <URL of a git repository on the localhost containing roles>
  scm: git
```
There is nothing special about the folder that seems to trigger the error. Except that it stops to sync the contents of the folder at a file ending with ```.yml~```. Is this a "killer" extension? ;-)

```http://172.22.0.1/api/v2/project_updates/7/stdout/```:
--------------------------------------------------------------------
```
TASK [detect requirements.yml] *************************************************
ok: [localhost]

TASK [fetch galaxy roles from requirements.yml] ********************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["ansible-galaxy", "install", "-r", "requirements.yml", "-p", "/var/lib/awx/projects/_6__git_project_playbooks/roles/"], "delta": "0:00:31.166983", "end": "2018-12-04 16:16:50.465489", "msg": "non-zero return code", "rc": 1, "start": "2018-12-04 16:16:19.298506", "stderr": "\\u001b[1;35m [WARNING]: - git-Project-Roles was NOT installed successfully: the specified\\u001b[0m\\n\\u001b[1;35mrole git-Project-Roles appears to already exist. Use --force to replace it.\\u001b[0m\\n\\u001b[1;35m\\u001b[0m\\n\\u001b[0;31mERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.\\u001b[0m", "stderr_lines": ["\\u001b[1;35m [WARNING]: - git-Project-Roles was NOT installed successfully: the specified\\u001b[0m", "\\u001b[1;35mrole git-Project-Roles appears to already exist. Use --force to replace it.\\u001b[0m", "\\u001b[1;35m\\u001b[0m", "\\u001b[0;31mERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.\\u001b[0m"], "stdout": "- extracting git-Project-Roles to /var/lib/awx/projects/_6__git_project_playbooks/roles/git-Project-Roles", "stdout_lines": ["- extracting git-Project-Roles to /var/lib/awx/projects/_6__git_project_playbooks/roles/git-Project-Roles"]}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1   
```

```Renaming the "killer" .yml~ extension```:
-----------------------------------------------------
Now, if I rename the extension from ```.yml~``` to ```.yml```, add/commit & resync, I get the following error stating that I should ```Use --force to replace``` the git roles clone, but there is no such option in the inventory source settings page and I could not find an ansible [ENVIRONMENT VARIABLE](https://docs.ansible.com/ansible/2.5/reference_appendices/config.html) to perform such a --force:
```
TASK [detect requirements.yml] *************************************************
ok: [localhost]

TASK [fetch galaxy roles from requirements.yml] ********************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["ansible-galaxy", "install", "-r", "requirements.yml", "-p", "/var/lib/awx/projects/_6__git_project_playbooks/roles/"], "delta": "0:00:29.903517", "end": "2018-12-04 18:20:57.572084", "msg": "non-zero return code", "rc": 1, "start": "2018-12-04 18:20:27.668567", "stderr": "\\u001b[1;35m [WARNING]: - git-Project-Roles was NOT installed successfully: the specified\\u001b[0m\\n\\u001b[1;35mrole git-Project-Roles appears to already exist. Use --force to replace it.\\u001b[0m\\n\\u001b[1;35m\\u001b[0m\\n\\u001b[0;31mERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.\\u001b[0m", "stderr_lines": ["\\u001b[1;35m [WARNING]: - git-Project-Roles was NOT installed successfully: the specified\\u001b[0m", "\\u001b[1;35mrole git-Project-Roles appears to already exist. Use --force to replace it.\\u001b[0m", "\\u001b[1;35m\\u001b[0m", "\\u001b[0;31mERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.\\u001b[0m"], "stdout": "- extracting git-Project-Roles to /var/lib/awx/projects/_6__git_project_playbooks/roles/git-Project-Roles", "stdout_lines": ["- extracting git-Project-Roles to /var/lib/awx/projects/_6__git_project_playbooks/roles/git-Project-Roles"]}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1   
```

If I resync the **project** with a ```Delete on update``` option, the sync works fine, although the roles folder is not updated:
```
TASK [detect requirements.yml] *************************************************
skipping: [localhost]

TASK [fetch galaxy roles from requirements.yml] ********************************
skipping: [localhost]

TASK [fetch galaxy roles from requirements.yml (forced update)] ****************
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0   
```

If I resync the **inventory source** now, I get the same error:
```
TASK [detect requirements.yml] *************************************************
ok: [localhost]

TASK [fetch galaxy roles from requirements.yml] ********************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["ansible-galaxy", "install", "-r", "requirements.yml", "-p", "/var/lib/awx/projects/_6__git_project_playbooks/roles/"], "delta": "0:00:30.350432", "end": "2018-12-04 18:40:03.159205", "msg": "non-zero return code", "rc": 1, "start": "2018-12-04 18:39:32.808773", "stderr": "\\u001b[1;35m [WARNING]: - git-Project-Roles was NOT installed successfully: the specified\\u001b[0m\\n\\u001b[1;35mrole git-Project-Roles appears to already exist. Use --force to replace it.\\u001b[0m\\n\\u001b[1;35m\\u001b[0m\\n\\u001b[0;31mERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.\\u001b[0m", "stderr_lines": ["\\u001b[1;35m [WARNING]: - git-Project-Roles was NOT installed successfully: the specified\\u001b[0m", "\\u001b[1;35mrole git-Project-Roles appears to already exist. Use --force to replace it.\\u001b[0m", "\\u001b[1;35m\\u001b[0m", "\\u001b[0;31mERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.\\u001b[0m"], "stdout": "- extracting git-Project-Roles to /var/lib/awx/projects/_6__git_project_playbooks/roles/git-Project-Roles", "stdout_lines": ["- extracting git-Project-Roles to /var/lib/awx/projects/_6__git_project_playbooks/roles/git-Project-Roles"]}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1   
```

**Comment by AlanCoding** [comment]
The playbook that the project updates are running is here:

https://github.com/ansible/awx/blob/74123647fedb204ec86aa4b9d68d566f35d51ea4/awx/playbooks/project_update.yml#L142-L154

And, indeed, there are some cases where `--force` is used.

As to why it used the non-forcing task...

> scm_full_checkout: true (if for a job template run), false (if retrieving revision)

This case (the job_type=run) that we're looking at is the former. So we can assume that variable is true. That probably means that we don't end the play on the "break if already checked out" task, meaning that `scm_result` is True.

I can see why `scm_result` may be true here, but not in the manually launched project updates. (causing a less-than-graceful failure)

Still, that doesn't say anything about the root problem, which is:

> role git-Project-Roles appears to already exist. Use --force to replace it.

I chatted with @chrismeyersfsu, and he suggested that maybe your source control already has a roles directory with this in it?

**Comment by jean-christophe-manciot** [comment]
@AlanCoding 
There are multiple issues here:
1) the **inventory source** git clone stops at ````interfaces.yml~``` for an unknown reason (what I called a "killer" extension)
2) the next **inventory source** sync run is confused and requests a ```--force``` to start over, but I don't know how to trigger that --force from AWX GUI/settings
3) syncing the **project** again with the ```Delete on update option``` should allow AWX to reclone the whole git repo with the playbooks & fetch the roles from the second git repo, but in reality it does not clone the latter.

> I chatted with @chrismeyersfsu, and he suggested that maybe your source control already has a roles directory with this in it?

Here is an excerpt regarding the contents of both git repos:
---git-Project-Playbooks/
├── ansible.cfg
├── hosts
├── \<playbooks\>
├── roles
│   └── requirements.yml
```
- src: <URL pointing to the roles git repository repo "git-Project-Roles">
  scm: git
```
---git-Project-Roles
├── files
│   ├── ...
├── group_vars
│   ├── ...
│   ├── ios_xev
│   │   ├── 16.5.1b
│   │   │   ├── ...
│   │   │   ├── interfaces.yml
│   │   │   ├── interfaces.yml~
│   │   │   ├── lldp.yml
│   │   │   ├── ...
│   │   └── 16.6.1
│   │       ├── ...
├── roles
│   ├── ...

Now, if I look at the contents of the **cloned repos** in the ```awx/projects``` folder, I can see that git-Project-Playbooks is correctly & fully cloned, except for the roles folder which is flawed:
├── _6__git_project_playbooks
│   ├── ansible.cfg
│   ├── hosts
│   ├── roles
│   │   ├── git-Project-Roles
│   │   │   └── git-Project-Roles
│   │   │       ├── files
│   │   │       │   ├── ...
│   │   │       └── group_vars
│   │   │           ├── ...
│   │   │           ├── ios_xev
│   │   │           └── ios_xev
│   │   │               └── 16.5.1b
│   │   │                   ├── ...
│   │   │                   └── interfaces.yml
│   │   └── requirements.yml
│   └── \<playbooks\>
└── _6__git_project_playbooks.lock
