### ISSUE TITLE
RFE: logging aggregator through HTTP/HTTPS proxy

### ISSUE THREAD

**Issue by sugitk** [ansible/awx#2818]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

We cannot set HTTP/HTTPS proxy to configure logging aggregator.

##### ADDITIONAL INFORMATION

I set proxy settings to below configuration files, but it doesn't go well.

- /etc/profile.d/proxy.sh
- /var/lib/awx/.bashrc
- /etc/supervisord.d/tower.ini (we use Ansible Tower 3.3.1)

Also I push the "Test" button, UI shows an error.

**Comment by shanemcd** [comment]
I think this issue pre-dates us moving to rsyslog. I believe you could do this via custom rsyslog configuration. Per https://www.rsyslog.com/doc/master/rainerscript/global.html:

> A common example is to set the http_proxy variable, e.g. for use with KSI signing or ElasticSearch. This can be done as follows:

```
global(environment="http_proxy=http://myproxy.example.net")
```
