### ISSUE TITLE
Lines coming from start node are longer than others

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#2833]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
![screen shot 2018-11-29 at 9 44 25 am](https://user-images.githubusercontent.com/9889020/49230998-fd12be80-f3be-11e8-9260-4977e1ec052c.png)

##### EXPECTED RESULTS
All lines should be the same length

##### ACTUAL RESULTS
Lines coming from the artificial start node are longer

**Comment by nixocio** [comment]
Reopen if we see this behavior on the new UI.
