### ISSUE TITLE
Auto-logout behavior now generates two logout messages

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#2837]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Auto-logout behavior now generates two logout messages

##### ENVIRONMENT
* AWX version: 3.4.0-devel

##### STEPS TO REPRODUCE
1. Navigate to a page which receives events (like the dashboard)
2. Wait until session is logged out

##### EXPECTED RESULTS
1 error message

##### ADDITIONAL INFORMATION

<img width="634" alt="screen shot 2018-11-29 at 1 34 33 pm" src="https://user-images.githubusercontent.com/12446869/49244577-1d05aa80-f3de-11e8-90a5-a2c9a1398abd.png">

**Comment by mabashian** [comment]
Fixed by #3091 - closing
