### ISSUE TITLE
wrong message on JT PATCH failure

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#2838]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

1. Have a JT
2. Do something so the PATCH will fail (delete a valid slice count entirely, as an example)
3. Error message:
```
Failed to update job template. PUT returned status: 400
```

But we sent a PATCH, not a PUT.

##### ENVIRONMENT
* AWX version: 2.1ish
##### ADDITIONAL INFORMATION

This is very nitpicky.

**Comment by girishramnani** [comment]
@wenottingham I can work on this

**Comment by girishramnani** [comment]
Opened a PR https://github.com/ansible/awx/pull/3053 to resolve this issue

**Comment by girishramnani** [comment]
PR has been merged, this issue can be closed
