### ISSUE TITLE
LDAP Group Type documentation link broken

### ISSUE THREAD

**Issue by alexander-bauer** [ansible/awx#285]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
In the helptext for the LDAP Group Type documentation (Configuration -> Authentication -> Sub Category = LDAP), the following text is shown.

> #### LDAP Group Type
> The group type may need to be changed based on the type of the LDAP server. Values are listed at: http://pythonhosted.org/django-auth-ldap/groups.html#types-of-groups

However, this link is broken. The new path for the best-matching documentation I could find is

> http://django-auth-ldap.readthedocs.io/en/latest/groups.html

##### ENVIRONMENT
* AWX version: 1.0.0.521 (self-built)
* Ansible version:  2.3.1.0
* Operating System: CentOS 7
* Web Browser: Firefox

##### STEPS TO REPRODUCE

At the Web UI, navigate to Configuration -> Authentication -> Sub Category = LDAP, then hover over the `?` to the right of `LDAP GROUP TYPE`. Try to visit the given link, and find that it gives a 404 error.

##### EXPECTED RESULTS

The link should yield actual documentation of the Django LDAP group types.

##### ACTUAL RESULTS

Broken link.

**Comment by Zokormazo** [comment]
https://django-auth-ldap.readthedocs.io/en/stable/groups.html#types-of-groups
