### ISSUE TITLE
LDAP Group Type drop down does not show up

### ISSUE THREAD

**Issue by bigjerv55** [ansible/awx#2855]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
The LDAP Group Type drop down does not show options to choose from.  I have tried multiple other ticket fixes with no luck so starting my own thread.  

##### ENVIRONMENT
* AWX version: 2.1.0
* AWX install method: docker on linux
* Ansible version:  2.7.2
* Operating System: Linux Cent OS 7
* Web Browser: Chrome, Firefox, 

##### STEPS TO REPRODUCE

- login as admin
- go to settings -> authentication -> LDAP
- select the drop down for LDAP GROUP TYPE

##### EXPECTED RESULTS

To see a list of options to choose from for LDAP GROUP TYPE (screen shot taken from Tower)
![image](https://user-images.githubusercontent.com/40799461/49380813-22ae0980-f6d8-11e8-99ca-94973f0a5d19.png)

##### ACTUAL RESULTS

No options listed (screen shot taken from my AWX)
![image](https://user-images.githubusercontent.com/40799461/49380843-3e191480-f6d8-11e8-822a-ba9c6ea4b6b1.png)

##### ADDITIONAL INFORMATION

I have attempted to implement "fixes" from several other tickets with no success.  I'll reference #2586 as I have attempted the steps listed there.

**Comment by jakemcdermott** [comment]
@bigjerv55 we fixed a bug like this recently. Are you certain you're on the latest AWX? Can you verify the version you're running?

![ldapgroup](https://user-images.githubusercontent.com/9753817/49385724-15027f00-f6ec-11e8-8e23-252e5799ddfa.gif)

**Comment by jakemcdermott** [comment]
@bigjerv55 going by the information in your bug report, it looks like you're running `2.1.0`. You'll need to update to `2.1.1` to get the fix for this bug.
