### ISSUE TITLE
Add UI elements for job launch, project sync, etc to edit screens

### ISSUE THREAD

**Issue by earchibald-lv** [ansible/awx#2858]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY
Currently, when clicking on a job template, or project, or anything really, one is taken to the edit screen, which is all well and good - but what I would really like is not to have to filter/navigate the job templates, or projects, or <*> to perform actions: launch job, update SCM, etc.

Ideally, for the actively focused template/project/<> there would be a set of UI elements matching the actions available from the listing, up at the top where the user doesn't have to scroll or filter - they *intend* to be interacting with that particular template or whatever -- editing is only *one* of the actions a user might want to do.

**Comment by wenottingham** [comment]
Mostly covered here: https://github.com/ansible/awx/issues/1991

The biggest issue is that performing operations on edited-but-unsaved content is likely to be confusing.
