### ISSUE TITLE
Docs: tooltip is incorrect for Slack notification templates

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#2859]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
When you set up slack notifications in Tower from the notification templates, you give it a list of channels to notify, like:
```
#test-channel
#other-test-channel
```
The tooltip next to the list of channels explicitly says you don't need the starting hash sign (#) in the list. However, slack notifications fail otherwise; the hash sign is mandatory.

##### ENVIRONMENT
* AWX version: Latest
* Operating System: Fedora
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Create a notification template of a slack type and try to test a notification with and without the hash sign prepended.

##### EXPECTED RESULTS
Both work.

##### ACTUAL RESULTS
Only the one with a hash sign works.

**Comment by wenottingham** [comment]
Fixed in #2861
