### ISSUE TITLE
move to Django 2.x LTS

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#2863]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY

There will be a Django 2.2 LTS in approximately April 2019. At some point after that date, we should move to using it.

##### ADDITIONAL INFORMATION

This work will be done in at least 3 pieces:

- [x] Upgrade Django REST Framework
- [x] ~~Remove django-jsonfield and jsonbfield in favor of Django's built-in JSONField~~
- [x] Upgrade Django
  - [x] #2075 Increase the size of the `User` first and last name fields

**Comment by wenottingham** [comment]
2.2 LTS is here: https://docs.djangoproject.com/en/2.2/releases/2.2/

**Comment by Spredzy** [comment]
Closing it as it is done
