### ISSUE TITLE
Forks option on Job Template has a text tip that makes user think the default forks is 0

### ISSUE THREAD

**Issue by ansiblejunky** [ansible/awx#2866]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
Navigate to a Job Template.
Click on the `?` icon next to `Forks` option. The text reads that the default value is 0 when nothing is set on this option. This leads users to believe the default is 0 when in fact it should state that if nothing is set, then it will use the default value of 5 or whatever is set on the `ansible.cfg` that is grabbed by the JT.

##### ENVIRONMENT
* AWX version: latest
* AWX install method: vagrant
* Ansible version:  2.7.1
* Operating System: Mac
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Normal install, go to JT and see tip text.

##### EXPECTED RESULTS

Tip text should advise correctly for the user.

##### ACTUAL RESULTS

Tip text shows that default value will be 0, which makes no sense.

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/14311849/49408091-c535af00-f70f-11e8-9069-116dfa81333c.png)

**Comment by mabashian** [comment]
Should say something like: `An empty value, or a value less than 1 will use the Ansible default which is usually 5.  The default number of forks can be overwritten with a change to ansible.cfg.` instead of `Value defaults to 0.`  I think the rest can stay the same.

**Comment by ryanpetrello** [comment]
Addressed via https://github.com/ansible/awx/pull/3965
