### ISSUE TITLE
command not found when running the job template in AWX or ansible tower

### ISSUE THREAD

**Issue by ChengalReddy** [ansible/awx#2868]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY
When I trigger the sqlplus to update the database in AWX, it throughs the error as below

sqlplus: command not found", 

changed: [127.0.0.1] => {
    "changed": true, 
    "cmd": "sh Integration_TEST.sh get_server CHG111111 India Test_Sys Test", 
    "delta": "0:00:00.602746", 
    "end": "2018-12-04 12:24:55.878897", 
    "invocation": {
        "module_args": {
            "_raw_params": "sh Integration_TEST.sh get_server CHG11111 India Test_Sys Test", 
            "_uses_shell": true, 
            "argv": null, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "warn": true
        }
    }, 
    "rc": 0, 
    "start": "2018-12-04 12:24:55.276151", 
    "stderr": "Integration_TEST.sh: line 55: sqlplus: command not found", 
    "stderr_lines": [

##### ENVIRONMENT
AWX version: 2.1.0
AWX install method: docker
Ansible version: 2.7.1
Operating System: Redhat
Web Browser: chrome

##### STEPS TO REPRODUCE
Execute the playbook again from AWX
Re-Run the sqlplus command. Error as below

sqlplus: command not found",

**Comment by ChengalReddy** [comment]
Can I know If some one can assist on how to set the environment variables or path to the docker containers in AWX? Probably this might be the cause

**Comment by wenottingham** [comment]
This sounds more like a user configuration issue than a bug, please bring this up on IRC (#ansible-awx on freenode) or on the mailing list (https://groups.google.com/forum/#!forum/awx-project)

**Comment by ChengalReddy** [comment]
@wenottingham But I made all settings as per requirement but not working. Would like to know what is the solution for this
