### ISSUE TITLE
Instance Group members show 'Unavalable'

### ISSUE THREAD

**Issue by mhurron** [ansible/awx#2871]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
API/UI

##### SUMMARY
When adding multiple awx_task/rabbitmq containers to a cluster/instance group, all new nodes appear offline, however still pick up jobs.

##### ENVIRONMENT
* AWX version: 2.1.1 (first seen in 2.1.0)
* AWX install method: docker on linux
* Ansible version:  Included in docker container
* Operating System: RHEL7
* Web Browser: Safari

##### STEPS TO REPRODUCE

Install AWX, including the following steps: (note I don't installl awx_web on every node)

- name: start rabbit app
  command: docker exec awx_rabbitmq rabbitmqctl start_app 

- name: enable rabbitmq Management
  command: docker exec awx_rabbitmq rabbitmq-plugins enable rabbitmq_management

- name: Create awx vhost
  command: docker exec awx_rabbitmq rabbitmqctl add_vhost awx

- name: Setup RabbitMQ awxmq user
  command: docker exec awx_rabbitmq rabbitmqctl add_user awxmq awxpassword

- name: Setup RabbitMQ awx user permissions to awx
  command: docker exec awx_rabbitmq rabbitmqctl set_permissions -p awx awxmq ".*" ".*" ".*"

- name: stop rabbit app on not master nodes
  command: docker exec awx_rabbitmq rabbitmqctl stop_app
  when: awx_web == False

- name: Join RabbitMQ cluster
  command: docker exec awx_rabbitmq rabbitmqctl join_cluster rabbit@{{ awx_master }}
  when: awx_web == False

- name: start rabbit app on not master nodes
  command: docker exec awx_rabbitmq rabbitmqctl start_app
  when: awx_web == False

##### EXPECTED RESULTS

Show active nodes

##### ACTUAL RESULTS

All new nodes are inactive, original AWX instance shows available.

![awx_instance_group](https://user-images.githubusercontent.com/3199503/49467925-8ff19580-f7d1-11e8-8eb5-3e1b72e8223f.png)

**Comment by mhurron** [comment]
This actually causes a bigger issue than just cosmetic issues. In this state, the web UI/API in the web container will crash hard, background tasks will continue to function. nginx will return 499 errors and no amount of restarting the services under supervisord will bring it back.

The core issue appears to be caused by the fact there is no way to update two settings in /etc/tower/settings.py in the awx_task container - CLUSTER_HOST_ID and SYSTEM_UUID. 

These are hard-coded settings and appear to cause confusion between AWX and RabbitMQ. When awx_task registers itself it registers with its hostname and the SYSTEM_UUID setting it keeps creating entries with the same UUID. If the RabbitMQ is running a different hostname than the hostname for awx_task, AWX can not see that the the nodes are healthy but can still submit to the cluster if it can communicate with it. However, given a little bit of time, sometimes just one job, the UI/API will crash being unable to communicate with the queues on the RabbitMQ cluster.

**Comment by idgdmg** [comment]
@mhurron - is there any update / solution to this? We are running the AWX in Kubernetes and I see after 4-5 weeks the AWX instances are "dis-apperaring / re-appearing" in the AWX dashboard.

**Comment by gamuniz** [comment]
Closing this for age of issue and due to the fact that we no longer use rabbitmq
