### ISSUE TITLE
custom_virtualenvs and alternate versions of python

### ISSUE THREAD

**Issue by roostercactus** [ansible/awx#2878]
##### ISSUE TYPE
 - Able to use an alternate version of python to setup a custom virtualenv.  

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

We are using the HPE Oneview ansible modules (https://github.com/HewlettPackard/oneview-ansible) which require python 2.7.9 or higher.  The default python version in the AWX container (centos 7) is python 2.7.5.  

So to use the Oneview modules I installed Python 2.7.13 from Software Collections (https://wiki.centos.org/AdditionalResources/Repositories/SCL) inside the awx_task and awx_web containers.  This installs to /opt/rh/python27.  To enable this python you have to run:  

source /opt/rh/python27/enable

Now I can setup my virtualenv for the HPE Oneview modules.  

I've done this in both containers (task/web) and it accepts the virtualenv and displays it as a choice for my templates in AWX.  Once I try to run a job though I get symbol errors and it errors out.  As far as I can tell it's because AWX is not able to "enable" the newer version of python before running the job from the virtualenv.

##### ADDITIONAL INFORMATION

Here's the steps I have done and the things I've done to try and make it work.  

These steps are done in both the awx_task and awx_web containers.

First install python 2.7.13:  

yum install scl-utils which
yum install centos-release-scl
yum clean all
yum install scl-utils-build python27.x86_64
vi /etc/yum.repos.d/CentOS-SCLo-scl.repo (disable repo)
vi /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo (disable repo)
yum clean all

Now enable the new python version so that 2.7.13 is added to your PATH before the older OS python:

source /opt/rh/python27/enable

which python (/opt/rh/python27/root/usr/bin/python)
python -V (Python 2.7.13)

Now create the virtualenv:  

cd /var/lib/awx/venv
mkdir oneview_ansible265
which virtualenv (/opt/rh/python27/root/usr/bin/virtualenv)
virtualenv /var/lib/awx/venv/oneview_ansible265
cd oneview_ansible265
source bin/activate
which python (/var/lib/awx/venv/oneview_ansible265/bin/python)
python -V (Python 2.7.13)

Now install ansible and friends and also the HPE Oneview modules

which pip (/var/lib/awx/venv/oneview_ansible265/bin/pip)
pip install --upgrade pip
pip install --upgrade setuptools
pip install ansible==2.6.5
pip install hpOneView==4.7.0
pip install pyvmomi==6.7.1
pip install orionsdk==0.0.6

Okay now everything is installed. Repeat on the web container.  

Now in AWX I can select this custom_virtualenvs from the template page.  

When I run a job though, I get these symbol errors:  

Identity added: /tmp/awx_586_VnMs4j/credential_3 (/tmp/awx_586_VnMs4j/credential_3)
Traceback (most recent call last):
  File "/var/lib/awx/venv/oneview_ansible265/bin/ansible-playbook", line 67, in <module>
    import ansible.constants as C
  File "/var/lib/awx/venv/oneview_ansible265/lib/python2.7/site-packages/ansible/constants.py", line 11, in <module>
    from jinja2 import Template
  File "/var/lib/awx/venv/oneview_ansible265/lib/python2.7/site-packages/jinja2/__init__.py", line 41, in <module>
    from jinja2.bccache import BytecodeCache, FileSystemBytecodeCache, \\
  File "/var/lib/awx/venv/oneview_ansible265/lib/python2.7/site-packages/jinja2/bccache.py", line 23, in <module>
    import tempfile
  File "/var/lib/awx/venv/oneview_ansible265/lib64/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/var/lib/awx/venv/oneview_ansible265/lib64/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /var/lib/awx/venv/oneview_ansible265/lib64/python2.7/lib-dynload/_io.so: undefined symbol: _PyErr_ReplaceException

If I login to the docker container I can do this:  

docker exec -it awx_task bash

Then...

cd venv/oneview_ansible265
source bin/activate
cd ../../projects/_10__my_project
ansible-playbook playbooks/site.yml
which python (/var/lib/awx/venv/oneview_ansible265/bin/python)
python -V (Python 2.7.5)

It's still trying to use the OS python v2.7.5...not the new Software Collections python installed in /opt.  

I get the same symbol errors.  

If I enable the new python version from Software Collections first though, it works properly (from inside the container anyway...not from AWX).  Logout and back in.

exit
docker exec -it awx_task bash
source /opt/rh/python27/enable 
cd venv/oneview_ansible265/
source bin/activate
cd ../../projects/_10__my_project
which python (/var/lib/awx/venv/oneview_ansible265/bin/python)
python -V (Python 2.7.13)

Now it's using the new python and playbooks will run.  But this doesn't seem to be happening when AWX uses the virtualenv.  

Is there some way to get AWX to 'enable' the new python in /opt before it tries to use the virtualenv?  

I've tried to add the extra-var

ansible_python_interpreter: /var/lib/awx/venv/oneview_ansible265/bin/python2

to the template but it doesn't seem to help.  

I also wasn't sure how AWX was enabling the virtualenvs either.  Normally from the bash shell you run

source bin/activate

So I added this line to the top of that script

source /opt/rh/python27/enable

in hopes that AWX is also running 'source bin/activate'.  But this doesn't seem to help either.  There's also activate.csh and activate.fish but neither of those shells are installed in the container so I don't think they are used.  I also added this line to the activate_this.py script in case AWX was calling it:  

os.system('source /opt/rh/python27/enable')

but again, it doesn't seem to help.  

Any ideas on how we can use newer versions of python with virtualenvs in AWX?  

Thanks.

**Comment by wenottingham** [comment]
> We are using the HPE Oneview ansible modules (https://github.com/HewlettPackard/oneview-ansible) which require python 2.7.9 or higher. 

This is the problem. I'd suggest running them on the included python until such point it is proven they do not work, given that the SSL changes in 2.7.9 have been backported to the python used in the virtual environment.

**Comment by roostercactus** [comment]
Hi, yes they (oneview modules) do seem to work with python 2.7.5.  At least in the capacity it's not giving me symbol errors anymore.  I'll have to run my playbooks to verify all the functions I need are working properly.  Hopefully they all just work.  I'll report back later.

**Comment by ryanpetrello** [comment]
@roostercactus we've recently (in awx 3.0.0) merged in support for more flexibility in regards to the Python version in custom virtualenvs: https://github.com/ansible/awx/commit/65641c7edd909527bfa0ec88908f10888aa1ed3f.  Mind giving this another shot?

**Comment by roostercactus** [comment]
Hi, great.  I'm still running 2.x for now since that's what we have in production.  I'll test out 3.x probably later after a few more releases.  Honestly since the HP modules work fine with python 2.7.5 I haven't really needed this functionality.  I'm glad it's been improved in 3.x though and will try it out in the future since you never know when things might actually break and I really need a newer version of python.  For now I'll close this issue so it won't be hanging out.  It may be a few weeks (months?) before I get a chance to test with 3.x.  Thanks for the help!
