### ISSUE TITLE
Feature/Bug: fix job output for `strategy` and `serial`

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#288]
##### ISSUE TYPE
 - Bug Idea/Feature Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

We have event-driven display of ansible / ansible-playbook output. This event-driven output is not correct for a few cases.

- [ ] use of `strategy: free`
- [ ] use of `serial: N`

##### ADDITIONAL INFORMATION

With regards to the display:

- we lose the task headers for the task invocations for later hosts in the stdout display (and view)
- the events-as-they-come view during job processing is all out of whack

For a particular task on hosts X, Y, and Z, the returned events share the same parent_uuid. This is likely causing some of the issue.

**Comment by cchurch** [comment]
[awx/lib/awx_display_callback/module.py](https://github.com/ansible/awx/blob/devel/awx/lib/awx_display_callback/module.py#L224) handles some part of this for free strategy in that `playbook_on_task_start` events will come in once per host with the same "uuid" instead of once per task.

Good luck to anyone who attempts to tackle this one! :+1:

**Comment by ryanpetrello** [comment]
Some notes from planning/discussion on this topic.  The fundamental issue here is that events under free strategy are received in a different order than awx code relies on, and that _some_ events which we previously relied on to happen *once* can be received as duplicates:

```
Today 3.2 and before

- Playbook_on_start
    - Playbook_on_play_start
        - Playbook_on_task_start
            - Runner_A
            - Runner_B
            - Runner_C
        - Playbook_on_task_start
            - Runner_A
            - Runner_B
            - Runner_C
...
- Playbook_on_stats
```

Free strategy does not wait for a task to "finish" on all hosts, so the events you see are more like:

```
- Playbook_on_start
    - Playbook_on_play_start_A {id: ---, name: Install stuff}
        - Playbook_on_task_start_A {id: aaaaa, name: Install Nginx, parent….}
            - runner_X {parent: aaaaa, parent_name: Install Nginx}
        - Playbook_on_task_start_A {id: aaaaa, line: 47}
            - runner_Y {parent: aaaaa, line: 48}
        - Playbook_on_task_start_B {id: bbbbb, line: 49}
            - runner_X {parent: bbbbb, line: 50}
        - Playbook_on_task_start_A {id: aaaaa, line: 51}
            - runner_on_Z {parent: aaaaa, line: 52}
```

As @cchurch noted, free strategy allows the same event to be received twice with the same uuid.  The first step to experimenting with support here is likely to break this unique constraint on `JobEvents`:

https://github.com/ansible/awx/blob/f03b40aa50f5e62f98823c62f66d79812a31af72/awx/main/models/jobs.py#L961

**Comment by chrismeyersfsu** [comment]
No API work needed to support this. https://github.com/ansible/awx/blob/devel/docs/job_events.md

**Comment by wenottingham** [comment]
This should be done now.

**Comment by lingfish** [comment]
Hi, confused here.  I see this commit done over a year ago, but it doesn't seem to be in 2.1.0?
