### ISSUE TITLE
User token list pagination shows wrong items count number

### ISSUE THREAD

**Issue by elyezer** [ansible/awx#2882]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
`/#/users/:id/tokens` view pagination's items count show wrong information when playing with the per page option.

##### ENVIRONMENT
* AWX version: head of devel

##### STEPS TO REPRODUCE

1. Log in as a superuser
2. Create an application
3. Create an arbitrary user
4. Navigate to the tokens tab for that user
5. Create 21+ personal access tokens for that user
6. Then select 20 as per page
7. Navigate to the second page
8. Then select 50 as per page

PS.: You can accomplish the same reproduction by creating 6 tokens, then navigating to the page 2 and changing the per page option. Since 5 is not on the per page value options creating 21 is a better way to reproduce it.

##### EXPECTED RESULTS

It should have displayed 1-21 of 21 instead

##### ACTUAL RESULTS

The items count will display 51-21 of 21. (see the screen shot on the additional information)

##### ADDITIONAL INFORMATION

Checking the URL on the browser URL bar there is `page:2` and I think that is what is causing the items count to display incorrectly.

![screenshot from 2018-12-06 14-46-25](https://user-images.githubusercontent.com/48132/49598490-e7c10580-f965-11e8-8e1f-2ed82119dcb6.png)

**Comment by unlikelyzero** [comment]
@wenottingham can we sneak this into 3.4?

**Comment by wenottingham** [comment]
already in upstream, so it's there...

**Comment by elyezer** [comment]
What is in upstream handles https://github.com/ansible/awx/issues/2844. This issue is when the pagination is already added but the `items` count does not provide the right value when the user is on a page other than 1 and changes the `per page` option.

I retried the steps and the items count still showing wrong values like `ITEMS  21 - 6 OF 6`, that is telling that it is showing items from 21 to 6 out of 6 which is not correct.

**Comment by nixocio** [comment]
Reopen if we see this behavior on the new UI.
