### ISSUE TITLE
 make ui-devel failed  with error

### ISSUE THREAD

**Issue by saurabhchandrapatel** [ansible/awx#2883]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System: Ubuntu Bash on window 10
* Web Browser:
Eage
##### STEPS TO REPRODUCE

run commond -

 make ui-devel

##### EXPECTED RESULTS

successful build and file should be generated in ui/static 

##### ACTUAL RESULTS

npm --unsafe-perm --prefix awx/ui install --no-save awx/ui
WARN engine puppeteer@1.11.0: wanted: {"node":">=6.4.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine https-proxy-agent@2.2.1: wanted: {"node":">= 4.5.0"} (current: {"node":"4.2.6","npm":"3.5.2"})

> puppeteer@1.11.0 install /mnt/c/srv/python/awx_poc/awx/awx/ui/node_modules/puppeteer
> node install.js

/mnt/c/srv/python/awx_poc/awx/awx/ui/node_modules/puppeteer/install.js:78
  return Promise.all([...cleanupOldVersions, generateProtocolTypesIfNecessary(true /* updated */)]);
                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN optional Skipping failed optional dependency /nunjucks/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN optional Skipping failed optional dependency /watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN optional Skipping failed optional dependency /webpack-dev-server/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none was installed.
npm WARN awx@1.0.0 No license field.
npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "--unsafe-perm" "--prefix" "awx/ui" "install" "--no-save" "awx/ui"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! puppeteer@1.11.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.11.0 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the puppeteer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs puppeteer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls puppeteer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/c/srv/python/awx_poc/awx/npm-debug.log
Makefile:470: recipe for target 'awx/ui/.deps_built' failed

##### ADDITIONAL INFORMATION
 
problem with  puppeteer

and I remove puppeteer then its run successful.

**Comment by jakemcdermott** [comment]
> ACTUAL RESULTS
> npm --unsafe-perm --prefix awx/ui install --no-save awx/ui
> WARN engine puppeteer@1.11.0: wanted: {"node":">=6.4.0"} (current: > 
> {"node":"4.2.6","npm":"3.5.2"}) <---

as [our documentation](https://github.com/ansible/awx/blob/devel/CONTRIBUTING.md#setting-up-your-development-environment) indicates, you'll need to use node 8. Please do that.
