### ISSUE TITLE
"Error connecting: Error while fetching server API version: - RabbitMQ

### ISSUE THREAD

**Issue by saurabhchandrapatel** [ansible/awx#2885]
##### ISSUE TYPE
 - Bug Report
When running this command

ansible-playbook -i inventory install.yml

then Issues with rabbitmq 

##### COMPONENT NAME

 - Installer

##### SUMMARY 

TASK [local_docker : Activate rabbitmq container] **********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or d
irectory'))"}
        to retry, use: --limit @/mnt/c/srv/python/awx_poc/awx_v2/awx/installer/install.retry

##### ENVIRONMENT
* AWX version: 2.1.0
* AWX install method:docker on Linux
* Ansible version:  
* Operating System: ubuntu 16.4 on window 10 with bash
* Web Browser: NA

##### STEPS TO REPRODUCE

run this command on ubuntu bash window 10

ansible-playbook -i inventory install.yml

##### ACTUAL RESULTS

above

**Comment by wenottingham** [comment]
This is an issue with either the distro docker python bindings, or docker under WSL; it does not appear to be an installer issue.
