### ISSUE TITLE
Workflow doesn't save properly if JT has credential prompt enabled.

### ISSUE THREAD

**Issue by ryan012880** [ansible/awx#2887]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI
 
##### ENVIRONMENT
* AWX version: 2.1.1
* AWX install method: docker on linux
* Ansible version:  2.7.1
* Operating System: RHEL7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. create a JT configured with credential prompt enabled
2. create a workflow and attach the JT (supply credential prompt then confirm and select)
3. click save

it will just get stuck on working spinning

##### EXPECTED RESULTS

workflow should be save properly for JT with credential prompt

##### ACTUAL RESULTS

<img width="1411" alt="screen shot 2018-12-07 at 6 56 59 pm" src="https://user-images.githubusercontent.com/10410660/49647603-073b5980-fa5e-11e8-82c9-e75bf4ff2ae8.png">

##### ADDITIONAL INFORMATION

<img width="548" alt="screen shot 2018-12-07 at 8 36 48 pm" src="https://user-images.githubusercontent.com/10410660/49648210-e6740380-fa5f-11e8-8a48-ff02317e1cde.png">

**Comment by mabashian** [comment]
This should be addressed by #2889, closing
