### ISSUE TITLE
Inventory updates do not show credential in list view

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#2891]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Inventory updates in the UI only show the credential if you click on the detail view, this is unlike what jobs do.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Create an inventory source with a credential.

Sync it.

View JOBS page in UI.

##### EXPECTED RESULTS

Shows credential like how jobs do.

![screen shot 2018-12-07 at 3 26 10 pm](https://user-images.githubusercontent.com/1385596/49671002-74d29000-fa34-11e8-956d-985b863bfda1.png)

##### ACTUAL RESULTS

Does not show the credential:

![screen shot 2018-12-07 at 3 23 32 pm](https://user-images.githubusercontent.com/1385596/49670962-4e145980-fa34-11e8-94ea-3365df4c3ba0.png)

Same inventory update in detail view:

![screen shot 2018-12-07 at 3 23 39 pm](https://user-images.githubusercontent.com/1385596/49670972-55d3fe00-fa34-11e8-8684-58ff6b05f1b2.png)

**Comment by kdelee** [comment]
![Screenshot from 2019-06-06 16-50-04](https://user-images.githubusercontent.com/29239279/59065681-474b8f80-887b-11e9-98d7-e4e1a76eccc2.png)
Works for me.

1st item is a project update...which also does not show the credential (maybe will file bug for that)
2nd item is an inventory source update, which shows its credential used...and is clickable
3rd item is a job run which shows its credential used.

Detail view:
![Screenshot from 2019-06-06 16-54-03](https://user-images.githubusercontent.com/29239279/59065888-c50f9b00-887b-11e9-8d52-e54c9ff36388.png)
Also confirmed credential is clickable and links to expected credential

@dsesami I'm going to close but pinging you in case you want to take a second look.

**Comment by AlanCoding** [comment]
Related issue https://github.com/ansible/awx/issues/4361
