### ISSUE TITLE
AWX Survey Issue with MultipleChoice(Single Select)

### ISSUE THREAD

**Issue by nanisyako** [ansible/awx#2894]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

I am not able to add 2 options to the survey when I chose the answer type multiple options single select. 

##### ENVIRONMENT
* AWX version: 2.0.1
* AWX install method: docker on linux
* Ansible version:  2.7.0
* Operating System: RHEL 7.3
* Web Browser: safari/chrome/firefox

##### STEPS TO REPRODUCE

Add one question to survey with mutliple Choice(Single Select) type . And ask how many PE you want and the options can be 1 or 2.
##### EXPECTED RESULTS

Once I hit enter in the multiple choice options box, I am expecting to go to next line to add my second option.

##### ACTUAL RESULTS

it stuck in the first line
##### ADDITIONAL INFORMATION

![2e175102-1be4-4a0b-bd8b-27049d1794a2](https://user-images.githubusercontent.com/38341020/49709291-99c82e00-fc01-11e8-9372-ff632759655d.png)

**Comment by AlanCoding** [comment]
I tried with 2.1.1 and Chrome.

I could not reproduce the described behavior, either for the case of creating a new question, or editing the existing one. In each case I was able to add 2, 3 on new lines in the multiple choice options.

Let us know if you still have the problem after upgrading to latest, or have any more information.

**Comment by Sreenadh8** [comment]
@AlanCoding I tried with 3.0, 4.0 and latest version 5.0, this multiple choice still exist, can you please re-open this issue... I am keep pressing 'Enter' but awx does not take other inputs....

**Comment by AlanCoding** [comment]
I will leave this closed in favor of https://github.com/ansible/awx/issues/4192
