### ISSUE TITLE
Variables - tower_user* / awx_user* not inherited in workflow over workflow

### ISSUE THREAD

**Issue by ryan012880** [ansible/awx#2896]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
The variables tower_user* / awx_user* does not appear as part of ```hostvars[inventory_hostname]``` when the JT is launch from workflow over workflow.

1. workflow --> workflow --> jt (not ok)
2. workflow --> jt (ok)

##### ENVIRONMENT
* AWX version: 2.1.1
* AWX install method: docker on linux
* Ansible version:  2.7.1
* Operating System: RHEL7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Create a playbook to debug ```hostvars[inventory_hostname]```
2. Configure a JT with the above playbook
3. Create a workflow which contains the above JT
4. Create another workflow which contains the above workflow
5. Launch and examine the JT output logs.

##### EXPECTED RESULTS

You should see the tower_user* and awx_user* variables

##### ACTUAL RESULTS

```hostvars[inventory_hostname]``` does not contain the tower_user* and awx_user* variables

**Comment by AlanCoding** [comment]
What would be the expected contents of these variables? The user who launched the workflow?

Also, a related fact to note is that JTs launched via schedules do not provide these variables either, and for those there is no singular user to reference.

**Comment by ryan012880** [comment]
@AlanCoding Yes, the user who launched the workflow should be the content of those variables but it didn't have any or I didn't see those variables present as per my testing.

**Comment by AlanCoding** [comment]
The root issue is that we do not propagate the workflow job's `created_by` field to jobs that they spawn. I don't know if simply propagating the field would be the preferred approach, or if some more granular information tracking of "indirectly launched by" would be better, but this does seem like a reasonable request to me.

**Comment by ryan012880** [comment]
@AlanCoding I was able to test the same scenario and it looks good, able to see now the tower_user_* / awx_user_* inherited. thanks
