### ISSUE TITLE
Templet UI survey expand/collapse section

### ISSUE THREAD

**Issue by hemskgren** [ansible/awx#290]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

We have template UI survey that are have a lot of questions but only use about 5 really common.
It wold be really good to have an option to ether have per question/prompt to start collapsed (not optimal for "required") to hide description and answer box or an section with multiple questions to start collapsed. 

The users need all options and descriptions per options. 

##### EXPECTED RESULTS

This wold help to have large UI survey but still minimize the default size and have more power than multiple templates.

**Comment by wenottingham** [comment]
Hi, I've added this to our larger feature request about updating the surveys in general. Please see https://github.com/ansible/awx/issues/20.

Thanks for the submission!
