### ISSUE TITLE
Pass tower_user_* / awx_user_* to the dynamic inventory update

### ISSUE THREAD

**Issue by jainnikhil30** [ansible/awx#2900]
##### ISSUE TYPE
Pass tower_user_* / awx_user_* to the dynamic inventory update, like we do for normal job template, so that those can be used in a custom script if needed.

##### COMPONENT NAME

 - API

##### SUMMARY

Pass tower_user_* / awx_user_* to the dynamic inventory update, like we do for normal job template, so that those can be used in the custom script if needed. 

##### ADDITIONAL INFORMATION

we currently pass those as job args for a normal job run and thus those can be used in playbook. Similarly it will be useful to pass those to inventory update as well and can be used in custom inventory scripts.

**Comment by wenottingham** [comment]
@AlanCoding can confirm, but this may be tricky, as I don't know that the update-on-launch inventory update is actually launched in the context of that user.

**Comment by AlanCoding** [comment]
Inventory updates don't accept extra_vars. But if we put that aside, what @wenottingham mentioned is also an issue, which is related to https://github.com/ansible/awx/issues/2896

**Comment by ryanpetrello** [comment]
What @AlanCoding said, inventory updates don't accept `extra_vars`.
