### ISSUE TITLE
Enabling Fact Caching overwrite the custom module path and breaks ability to use custom modules

### ISSUE THREAD

**Issue by pierre8778** [ansible/awx#2901]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- API 
- UI

##### SUMMARY
When facts caching is enabled on a template, module search path is overwritten at runtime.
Jobs from this template won't run with the module search path set from parameter "library" in /etc/ansible/ansible.cfg, but with "/usr/lib/python2.7/site-packages/awx/plugins/library"

##### ENVIRONMENT
* AWX version: 1.0.8.0
* AWX install method: docker on linux
* Ansible version:  2.6.4
* Operating System: RHEL 7
* Web Browser: Firefox Quantum 63.0.3

##### STEPS TO REPRODUCE
- Set 'library' parameter to '/usr/share/my_modules' in /etc/ansible/ansible.cfg
- Create a custom module and put it in /usr/share/my_modules
- Create a template with parameters below : 
  - run playbook using the custom module
  - set verbosity to 'more verbose' (only to display the value assigned to the module search path) 
  - enable facts caching 

##### EXPECTED RESULTS
- configured module search path = [u'/usr/share/my_modules']
- job using custom module run fine

##### ACTUAL RESULTS
- configured module search path = [u'/usr/lib/python2.7/site-packages/awx/plugins/library']
- job failed with message : ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path. [...]

**Comment by ryanpetrello** [comment]
Hey @pierre8778,

If you want to set a custom library parameter, you can do so using the `ANSIBLE_LIBRARY` environment variable.  See this issue and the related discussion for details:

https://github.com/ansible/awx/issues/815#issuecomment-357753056
