### ISSUE TITLE
Schedule linking back to template

### ISSUE THREAD

**Issue by tabletick** [ansible/awx#2902]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY

Tower: v3.3.0

When listing the schedules of future job runs, the schedules are listed by their assigned, uniq name (menu: Schedules). Hovering the mouse pointer over the name will reveal the configured template that will run.
When entering the schedule, the template is not visible any more. Neither any option to open the connected template.

I'd suggest adding a possibility to open the connected template that the schedule is related to.

Since the schedules are available from inside the template configuration, the opposite should also be possible to allow the opposite entry point as well.

During daily usage this seems to be very useful and allows to easily attribute a schedule to a template.

##### ADDITIONAL INFORMATION

--

**Comment by wenottingham** [comment]
This repo is for AWX issues, for Tower issues please contact your RH support rep. This was fixed in AWX in  https://github.com/ansible/awx/pull/2638
