### ISSUE TITLE
awx is not coming up on browser

### ISSUE THREAD

**Issue by Raghuveer123** [ansible/awx#2906]
8fe29dc3c25c        ansible/awx_task:2.1.0       "/tini -- /bin/sh -c…"   31 minutes ago      Up 31 minutes       8052/tcp                                              awx_task
0f72c042c2f0        ansible/awx_web:2.1.0        "/tini -- /bin/sh -c…"   31 minutes ago      Up 16 minutes       0.0.0.0:80->8052/tcp                                  awx_web
02e80e21b92f        memcached:alpine             "docker-entrypoint.s…"   32 minutes ago      Up 32 minutes       11211/tcp                                             memcached
b7a17a418568        ansible/awx_rabbitmq:3.7.4   "docker-entrypoint.s…"   32 minutes ago      Up 32 minutes       4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 25672/tcp   rabbitmq
441e3461d167        postgres:9.6                 "docker-entrypoint.s…"   32 minutes ago      Up 32 minutes       5432/tcp                                              postgres
 Even though containers are up,I am unable to see on browser

**Comment by jaykumar-jnpr** [comment]
Please provide container logs (awx_web)

also, this would help 

curl -vv <url to AWX>
