### ISSUE TITLE
Have backlinks on inventory script page

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#2908]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

When viewing/editing an inventory script, there should be a tab that links to the sources where that inventory script is used.

**Comment by shanemcd** [comment]
No longer relevant, inventory scripts have migrating to inventory plugins which are built into EEs and not managed via the AWX UI.
