### ISSUE TITLE
How to uninstall awx?

### ISSUE THREAD

**Issue by magick93** [ansible/awx#2909]
##### ISSUE TYPE
 - Feature Idea 

##### COMPONENT NAME
 - Installer / uninstaller

##### SUMMARY

Its very easy to install. However I mistakenly installed AWX on my local, rather than in Kubernetes. Now I would like to be able to easily uninstall.

##### ADDITIONAL INFORMATION

There are several running awx docker containers, eg, rabbit, awx_tasks, awx_web etc - how best/easiest to remove this?

**Comment by ryanpetrello** [comment]
@magick93,

This issue tracker is for reporting bugs and issues in awx - questions like this one are best suited for our mailing list (https://groups.google.com/forum/#!forum/awx-project)

Are you running a _local_ (e.g., minishift) Kubernetes cluster, or have you just accidentally created some Docker containers in a local Docker you're running?  

If it's the former, consult https://kubernetes.io/docs/ for the best way to tear down.  Something like this might work, depending on what else you might have running locally:

https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#tear-down

If you just need to clean up some stray Docker containers, you should be able to just stop and delete the containers:

`~ docker stop awx_tasks`
`~ docker rm awx_tasks`
etc...

**Comment by magick93** [comment]
HI @ryanpetrello 

This isnt a question, but a feature request. 

I just think it would be nice to tell people how they can uninstall - or at the vary least, tell people what needs to be uninstalled.
