### ISSUE TITLE
Pre-fill playbook if only one is available for a selected project

### ISSUE THREAD

**Issue by cg-cnu** [ansible/awx#2912]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

In NEW JOB TEMPLATE prefill INVENTORY & PLAYBOOK if only one option is available in the list.

##### ADDITIONAL INFORMATION
 AWX Version: 1.0.8.0 

While creating NEW JOB TEMPLATE, in case the user has access to only one project, the PROJECT is prefilled with the project name. It would be helpful if we can replicate the same for INVENTORY & PLAYBOOK in the same UI. 

Why ? In case of users having limited access, in some cases only to one inventory and one playbook, Its a minor convenience to just prefill it without selecting from the dropdown. 

Let me know if you got any questions! :slightly_smiling_face:

**Comment by mabashian** [comment]
I don't foresee a scenario where we pre-fill the inventory because inventory isn't a required field.  It could be prompted.  Playbook could be pre-filled though if there's only one available.
