### ISSUE TITLE
dynamic inventory fail to match host pattern

### ISSUE THREAD

**Issue by tobiasjohanssonsdnit** [ansible/awx#2914]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Having problems with dynamic inventory (custom scripts) and the matching of groups inside playbooks, doesn't work as expected for groups

##### ENVIRONMENT
* AWX version: 2.1.0
* AWX install method: docker on linux
* Ansible version:  2.7.2
* Operating System: Centos 7
* Web Browser: Chrome Version 71.0.3578.80

##### STEPS TO REPRODUCE
A dynamic inventory (custom script in AWX) that rebuilds the inventory for each run of related job_templates.
ansible-inventory -i dynamic_inventory.py --ask-vault-pass --graph site_1:
```
@site_1:
  |--@pe-cluster-1:
  |  |--host15
  |  |--host16
  |--@pe_cluster_2:
  |  |--host1
  |  |--host2
  |--@pe_cluster_3:
  |  |--host9
  |  |--host10
```

Having a playbook with a play like
```
- hosts: site_1
  connection: local
  gather_facts: no

  tasks:
    - name: debug groups available
      debug:
        msg: "{{ group_names }}"
```

##### EXPECTED RESULTS

```
TASK [debug groups available] ************************************************** | 11:17:41
-- | --
  | 65 | ok: [host1] => { |  
  | 66 | "msg": [ |  
  | 67 | "pe_cluster_2", |  
  | 68 | "site_1" |  
  | 69 | ] |  
  | 70 | }

```
The name of the hosts/groups have been changed for integrity reasons.

##### ACTUAL RESULTS

AWX prints that is skipping the task as it doesn't match any hosts in the inventory.
```
skipping: no hosts matched
[WARNING]: Could not match supplied host pattern, ignoring: site_1
```

##### ADDITIONAL INFORMATION
This works in AWX with
* AWX version: 1.0.6.15
* AWX install method: docker on linux
* Ansible version:  2.5.5
* Operating System: Centos 7
* Web Browser: Chrome Version 71.0.3578.80

Standalone with ansible 2.7.2 this works as expected as well:
```
ansible-inventory -i dynamic_inventory.py --ask-vault-pass --graph site_1
ansible-playbook -i dynamic_inventory.py debug_inventory.yml --ask-vault-pass
 
```

If having the hosts pattern as group "pe_cluster_3" there is a match in the playbook in AWX (2.1.0), this is a group with hosts and not any other groups (if that matters)

In the UI if browsing through the inventory everything is correct and the search for "site_1" gives me all expected hosts and nested groups.

**Comment by AlanCoding** [comment]
If you're using 2.1.0, this is likely to be the previously-reported bug of grandparent groups being excluded, and should be fixed. Let us know if you still see issues after upgrading. Thanks.

https://github.com/ansible/awx/issues/2574
