### ISSUE TITLE
Unusable Workflow Template UI on Mobile

### ISSUE THREAD

**Issue by naisanza** [ansible/awx#292]
##### ISSUE TYPE

 - Feature Request

##### COMPONENT NAME

 - UI

##### SUMMARY

The UI for the Workflow Template on mobile devices doesn't have a practical layout. The graph doesn't get centered into view, and you end up searching around for it. It's less worse in landscape mode.

![screenshot_20170925-114053](https://user-images.githubusercontent.com/1614425/30831449-5b9e63f2-a1fc-11e7-8c72-554e25274e7e.png)

##### ENVIRONMENT

* AWX version: ece93c45c9c932cfbfba2b44e217e99a6bb6a752
* Ansible version:  2.4.0.0
* Operating System: Proxmox Ubuntu 16.04 server
* Web Browser: Chrome

**Comment by wenottingham** [comment]
-> #1508
