### ISSUE TITLE
Is possible to use mysql for awx ? 

### ISSUE THREAD

**Issue by saurabhchandrapatel** [ansible/awx#2920]
##### ISSUE TYPE
 - Bug Report
working fine for PostgreSQL  but for mysql DB: - 

 main.JobTemplate.project: (models.E006) The field 'project' clashes with the field 'project' from model 'main.unifiedjobtemplate'.

##### COMPONENT NAME

 - Installer

##### SUMMARY

working fine for PostgreSQL but for mysql DB getting an error 
##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### ACTUAL RESULTS

 main.JobTemplate.project: (models.E006) The field 'project' clashes with the field 'project' from model 'main.unifiedjobtemplate'.

**Comment by ryanpetrello** [comment]
@saurabhaec,

AWX is built and tested to work with postgres, and uses a number of features that are _specific_ to postgres.  MySQL support is not planned.
