### ISSUE TITLE
Openshift deploy fails with read-only filesystem error.

### ISSUE THREAD

**Issue by sharkcus** [ansible/awx#2925]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Using provided openshift role/playbook + vanilla setup, "awx-web" and "awx-celery" containers fail to start with the following error:
`mkdir /var/lib/docker/devicemapper/mnt/<ID>/rootfs/etc/tower/conf.d: read-only file system`
In my opinion, this directly relates to this issue: https://access.redhat.com/solutions/3397331

##### ENVIRONMENT
* AWX version: 2.1.2
* AWX install method: openshift
* Ansible version:  2.7.4
* Operating System: rhel 7
* Web Browser: chrome

##### STEPS TO REPRODUCE
1. git clone https://github.com/ansible/awx
2. (modify inventory with project name and auth)
3. `ansible-playbook -i inventory install.yml -e openshift_token=##### -e docker_registry_password=#####`

##### EXPECTED RESULTS
Successful AWX deploy

##### ACTUAL RESULTS
Containers "awx-web" and "awx-celery" go into a boot loop and throw the following error (errors are the same except container name):

```Error: failed to start container "awx-web": Error response from daemon: {"message":"invalid header field value \"oci runtime error: container_linux.go:247: starting container process caused \\\"process_linux.go:364: container init caused \\\\\\\"rootfs_linux.go:54: mounting \\\\\\\\\\\\\\\"/var/lib/origin/openshift.local.volumes/pods/<pod-id>/volumes/kubernetes.io~secret/awx-confd\\\\\\\\\\\\\\\" to rootfs \\\\\\\\\\\\\\\"/var/lib/docker/devicemapper/mnt/<id>/rootfs\\\\\\\\\\\\\\\" at \\\\\\\\\\\\\\\"/var/lib/docker/devicemapper/mnt/<id>/rootfs/etc/tower/conf.d\\\\\\\\\\\\\\\" caused \\\\\\\\\\\\\\\"mkdir /var/lib/docker/devicemapper/mnt/6<id>/rootfs/etc/tower/conf.d: read-only file system\\\\\\\\\\\\\\\"\\\\\\\"\\\"\\n\""}```

##### ADDITIONAL INFORMATION
Worth noting, we do not see this issue with awx 1.0.x deploys.

I believe this directly relates to this issue from redhat/openshift:
https://access.redhat.com/solutions/3397331
Unfortunately, their resolution is `Applications should be configured to write to other locations.`

**Comment by sharkcus** [comment]
Alright. How about a compromise. None of you need to get me a Christmas present this year if you can help me out with this issue.

**Comment by gamuniz** [comment]
Closing this as deployment has changed to awx-operator
