### ISSUE TITLE
Vulnerable jQuery

### ISSUE THREAD

**Issue by nikkyjha** [ansible/awx#2926]
We are actively using AWX and we have one new security concern: -

 

We have already reported few in past:
      https://github.com/ansible/awx/issues/2466
      https://github.com/ansible/awx/issues/2467
      https://github.com/ansible/awx/issues/2468

 

**Summary**

The application is running a vulnerable version of jQuery v2.2.4, which was released on May 20, 2016. The noted version of the product is vulnerable to Cross Site Scripting attacks.

 **Details**

The application is using vulnerable version of jQuery at the following URL:

**Affected Endpoint 
https://<some_hostname>/static/js/vendor.9d966eb1d3c348bc617.js

 

jQuery JavaScript Library v2.2.4

* http://jquery.com/

*

* Includes Sizzle.js

* http://sizzlejs.com/

*

* Copyright jQuery Foundation and other contributors
* Released under the MIT license

* http://jquery.org/license

*

* Date: 2016-05-20T17:23Z

 

**Remediation Recommendations**

Upgrade the affected service to the latest secure version. At the time of this writing, the latest secure version of jQuery is v3.3.1, released 20th January, 2018. In addition, a patch management system / plan is required to reduce this constant threat as new versions are released.

**Comment by jayasuryapitchuka** [comment]
Hi awx team,

Currently we are blocked on this issue. Can we know your remedy for this vulnerability?

**Comment by jakemcdermott** [comment]
Hey there - thanks for creating this issue. We will be updating jquery and a few other dependencies in the coming weeks.

**Comment by mabashian** [comment]
https://github.com/ansible/awx/pull/2983 brings jquery up to 3.3.1
