### ISSUE TITLE
Relationship between hosts and credentials

### ISSUE THREAD

**Issue by magick93** [ansible/awx#2927]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

Currently AWX does not have anyway of associating credentials with a inventory host, only with an inventory (in a job template). 

It is very common for each host to require unique credentials. But awx assumes that all hosts use the same credentials.

## User story

> As a awx user, I would like to be able to associate a credential with a host, as each of my servers that I want to manage with ansible uses a unique username and password.

**Comment by magick93** [comment]
Related to https://github.com/ansible/awx/issues/286

**Comment by wenottingham** [comment]
Yes, closing this to track in #286.
