### ISSUE TITLE
[RFE] Limitations for the execution date and time setting range for the scheduled job

### ISSUE THREAD

**Issue by saito-hideki** [ansible/awx#2928]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Customer wants to make limitation that certain jobs to only run at certain times of the day so they don't affect other operations like a large scale job execution.
Currently, when users create a schedule, there is no features to limit the execution date and time range for job templates.

If it is possible, It would be nice if we make limitations the setting range for following sections in the CREATE SCHEDULE page(TEMPLATES > My_JOB_TEMPLATE > SCHEDULES   CREATE SCHEDULE):
- START DATE
- START TIME (HH24:MM:SS)
- LOCAL TIME ZONE
- REPEAT FREQUENCY

##### ADDITIONAL INFORMATION
None

**Comment by radioactive73** [comment]
It would be even better if there was a schedule option in the template survey so the end user could pick from the available schedule options defined in the survey.

Ex:
START DATE - Selectable from survey prompt on launch
START TIME (HH24:MM:SS) - Configurable in the survey configuration (set to 01:00:00) but hidden from survey prompt on launch
LOCAL TIME ZONE - also configurable but hidden on survey launch
REPEAT FREQUENCY - selectable from survey prompt on launch

Essentially choose which date options are prompted for on job launch, and those that aren't prompted for on launch would be configured in the edit survey options.

**Comment by gamuniz** [comment]
Closing this as done via exclusions
