### ISSUE TITLE
URL absolute instead of relative

### ISSUE THREAD

**Issue by yoanncrenn** [ansible/awx#2931]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

Some links are absolute instead of relative.

##### ENVIRONMENT
* AWX version: 2.1.1
* AWX install method: docker on linux
* Ansible version: 2.7.2
* Operating System: CentOS 7
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Connect to AWX. At home page, links in dashboard-list for jobs, dashboard-count and activity-stream are absolute.

##### EXPECTED RESULTS

Relative links (#/...)

##### ACTUAL RESULTS

Absolute links (/#/...)

##### ADDITIONAL INFORMATION

See : 
* activitystream.controller.js line 57
* jobs-list.directive.js lines 35 and 37
* dashboard-counts.directive.js lines 37, 42, 48, 53, 59 and 64

**Comment by jakemcdermott** [comment]
Does this impact the behavior of the app or its links in any way?
