### ISSUE TITLE
404 when accessing SJT details from a workflow while SJT is running

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#2935]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
1. Create a workflow "foo"
2. Add a SJT "bar" to the workflow
3. Launch the workflow
4. Wait for "bar" to start
5. Click on the 'details' link for bar *while it is still running*

You get:

"Invalid search term entered. GET returned: 404 Not found."

It works properly once the SJT "bar" finishes.

##### ENVIRONMENT
* AWX version: current
##### ADDITIONAL INFORMATION

The bad query (while running) is for GET to `/api/v2/jobs/115/`.

The good query (after finished) is for GET to `/api/v2/workflow_jobs/115/`.

**Comment by unlikelyzero** [comment]
https://github.com/ansible/awx/pull/2938#issuecomment-448022145
