### ISSUE TITLE
Allow workflow node details to open in new tab

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#2936]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

When viewing a workflow output, each node has a "DETAILS" link.

I should be able to control-click/right-click/middle-click to open these details in a new tab.

##### ENVIRONMENT
* AWX version: current

##### ADDITIONAL INFORMATION

Filing as 'bughancement'.

**Comment by tvo318** [comment]
Which release is this going into?

**Comment by unlikelyzero** [comment]
@tvo318 likely 3.4.0. Testing now. I have an instance up if you wanna take a 👁 .

@wenottingham @mabashian seeing some unanticipated behavior here:

The new page is opened up in a tab, but the mouse is hooked onto the 'DETAILS' link and isn't released until the user mouse event is fired... which opens up the details link in the current tab... which is counter-productive to this change. Even hitting the [Esc] Key doesn't release the mouse "hook"

**Comment by unlikelyzero** [comment]
Also, details links aren't rendering if firefox

**Comment by unlikelyzero** [comment]
https://github.com/ansible/awx/pull/2938#issuecomment-448022145
