### ISSUE TITLE
Application dropdown error should be improved

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#2939]
##### ISSUE TYPE
Feature idea

##### COMPONENT NAME
 - UI

##### SUMMARY
Failing to fill a required field in the UI for creating applications should show a more useful error than just kicking back the API error. Here's a screenshot of the current behavior if you try to use the Authorization code option then don't fill in a field.

![screenshot from 2018-12-12 09-42-43](https://user-images.githubusercontent.com/19942822/50095942-8e1dce00-01e4-11e9-96c1-ed01a3c14963.png)

**Comment by jlmitch5** [comment]
There also seems to be an issue with the params passed to the alert() dialog when saving:

<img width="1370" alt="screen shot 2019-03-06 at 12 37 29 pm" src="https://user-images.githubusercontent.com/1342624/53901933-1a82a480-400e-11e9-8301-6798f5af99ff.png">

**Comment by keithjgrant** [comment]
These are two separate issues. I split the "Unexpected Error: undefined" into a new issue #3374

**Comment by keithjgrant** [comment]
Improving the error message will probably need to be done in the API, since the UI simply displays the error message it receives in the response.

Alternately, we could make the Redirect URIs field required if the Authorization Grant type is set to either Authorization Code or Implicit.

**Comment by unlikelyzero** [comment]
This UX Pattern was solved in the new UI. Let's ensure we have an explicit test for this

**Comment by kdelee** [comment]
Until any changes to the API have been made, I'm removing the `component:api` label -- because right now there is no clear change/fix to verify from the api side

**Comment by unlikelyzero** [comment]
@akus062381 can you check to see how we're handling this error case in the tests?

**Comment by akus062381** [comment]
@unlikelyzero - I have taken care of this- see PR https://github.com/ansible/tower-qa/pull/6092

Closing this issue
