### ISSUE TITLE
kerberos: Unable to authenticate <Response [302]>, ssl: Bad HTTP response returned from server. Code 403

### ISSUE THREAD

**Issue by LeDOC666** [ansible/awx#2944]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Ansible

##### SUMMARY

After done a fresh install, I quick configured all awx objects, and configure krb5.conf in 2 awx containers. But, I'm unable to connect to Windows client.
Another ansible runtime can connect with same method on that Windows client.

##### ENVIRONMENT
* AWX version: 2.1.2
* AWX install method: docker-compose
* Ansible version:  2.7.4
* Operating System: Docker on CentOS 7.4
* Web Browser: Firefox

##### STEPS TO REPRODUCE

**AWX Credential Type injector:**
`
extra_vars:
  ansible_connection: winrm
  ansible_password: '{{ password }}'
  ansible_port: '5986'
  ansible_user: '{{ username }}'
  ansible_winrm_server_cert_validation: ignore
`

**Inventory:**
One host with FQHN resolved by DNS

**Job**
Any

**krb5.conf**
`[logging]
 default = FILE:/var/log/krb5libs.log
 kdc = FILE:/var/log/krb5kdc.log
 admin_server = FILE:/var/log/kadmind.log

[libdefaults]
 dns_lookup_realm = false
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true
 rdns = false
 default_realm = PAM.LAN
 default_ccache_name = DIR:/tmp/krb5_%{uid}

[realms]
PAM.LAN = {
   kdc = vsrvxxxxx.pam.lan
   admin_server = vsrvcronos.pam.lan
}
[domain_realm]
.pam.lan = PAM.LAN`

##### EXPECTED RESULTS

Connecting, and authenticate to Windows Client

##### ACTUAL RESULTS

`

PLAYBOOK: install_notepadpp.yml ************************************************
1 plays in install_notepadpp.yml
PLAY [Install Notepad++] *******************************************************
TASK [Gathering Facts] *********************************************************
task path: /var/lib/awx/projects/projet_windows/install_notepadpp.yml:2
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/setup.ps1
<virwiphipsql.pam.lan> ESTABLISH WINRM CONNECTION FOR USER: Binder.Admin@PAM.LAN on PORT 5986 TO virwiphipsql.pam.lan
checking if winrm_host virwiphipsql.pam.lan is an IPv6 address
creating Kerberos CC at /tmp/tmpNxItIW
calling kinit with pexpect for principal Binder.Admin@PAM.LAN
kinit succeeded for principal Binder.Admin@PAM.LAN
<virwiphipsql.pam.lan> WINRM CONNECT: transport=kerberos endpoint=https://virwiphipsql.pam.lan:5986/wsman
<virwiphipsql.pam.lan> WINRM CONNECTION ERROR: Unable to authenticate <Response [302]>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 400, in _winrm_connect
    self.shell_id = protocol.open_shell(codepage=65001)  # UTF-8
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/winrm/protocol.py", line 157, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/winrm/protocol.py", line 234, in send_message
    resp = self.transport.send_message(message)
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/winrm/transport.py", line 256, in send_message
    response = self._send_message_request(prepared_request, message)
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/winrm/transport.py", line 261, in _send_message_…
<virwiphipsql.pam.lan> WINRM CONNECT: transport=ssl endpoint=https://virwiphipsql.pam.lan:5986/wsman
<virwiphipsql.pam.lan> WINRM CONNECTION ERROR: Bad HTTP response returned from server. Code 403
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 400, in _winrm_connect
    self.shell_id = protocol.open_shell(codepage=65001)  # UTF-8
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/winrm/protocol.py", line 157, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/winrm/protocol.py", line 242, in send_message
    raise ex
WinRMTransportError: Bad HTTP response returned from server. Code 403
fatal: [virwiphipsql.pam.lan]: UNREACHABLE! => {
    "changed": false, 
    "msg": "kerberos: Unable to authenticate <Response [302]>, ssl: Bad HTTP response returned from server. Code 403", 
    "unreachable": true
}
PLAY RECAP *********************************************************************
virwiphipsql.pam.lan       : ok=0    changed=0    unreachable=1    failed=0   

`

##### ADDITIONAL INFORMATION

I tryed to install krb-devel
install pywinrm
winrm[kerberos]
more, and more packages, but same error...

the kinit is ok:
`[root@awx awx]# klist
Ticket cache: DIR::/tmp/krb5_0/tkt
Default principal: Binder.Admin@PAM.LAN

Valid starting       Expires              Service principal
12/17/2018 17:11:21  12/18/2018 03:11:21  krbtgt/PAM.LAN@PAM.LAN
        renew until 12/24/2018 17:11:18`

**Comment by wenottingham** [comment]
Why are you using a custom credential injectors rather than just host vars?

**Comment by LeDOC666** [comment]
I tryed with host var too, and same problem.
I prefer use custom credential for specify this credential for my Windows Inventory

**Comment by LeDOC666** [comment]
Hello, do you have any news for this problem ? Im completly blocked to deploy awx.

**Comment by nevotheless** [comment]
Hey @LeDOC666,

Your issue was the only one on the search for help with our issue, so I'll post our answer here and hopefully, it can help you:

I assume you're behind a proxy server and have `http_proxy`, `https_proxy` and `no_proxy` vars on the awx_task container set.

The Errors you're getting are probably not from the Windows Server you're trying to connect to. The requests are probably sent to the proxy server that is responding with certain Error Codes.

Regardless of that, if you still need to further debug the issue, you can change up the Error reporting of the transport.py file `/var/lib/awx/venv/ansible/lib/python2.7/site-packages/winrm/transport.py` a bit so will get the response body instead of the simple error code.

I changed

`raise WinRMTransportError('http', ex.response.status_code, response_text)` 
(Thanks for helping response_text....)

to 

`raise WinRMTransportError('http', ex.response.content, response_text)`

That way I got the body of the response during the job run on awx and saw that our proxy was handling the request.

Hopefully, this can help you a bit. Keep it up and you'll get the issue resolved (if you still have it).

**Comment by LeDOC666** [comment]
Hello,
Thanks for your info,
I've seen this $*#ing proxy is running.
I will configure it without it later. I will clise this issue by waiting.
Thanks
