### ISSUE TITLE
UI only fetches first 25 success/failure notification templates

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#2945]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
* Note that this bug only applies to the toggles on the notification list.  The UI will appropriately fetch all the notification templates.

Lets use the Org notification list as an example.  In order to construct that view, the UI needs to make 3 requests:

1) A request to `/api/v2/organizations/:id/notification_templates` this is the list of notification templates (paginated, capped at 20 by default)
2) A request to `/api/v2/organizations/:id/notification_templates_success/` this is the list of notification
templates that are turned on for successful scenarios (paginated, capped at 25 by default)
3) A request to `/api/v2/organizations/:id/notification_templates_failure/` this is the list of notification
templates that are turned on for failure scenarios (paginated, capped at 25 by default)

Create 26 notification templates for this organization and turn them all on for success scenarios.  Since the UI only fetches one page (25 rows) worth of entries from the `notification_templates_success` endpoint, the 26th row will not show an enabled toggle as it should.

##### EXPECTED RESULTS
UI always accurately shows when a notification is turned on/off regardless of number of templates

##### ACTUAL RESULTS
Once you get to > 25 notification templates turned on for success/failure the UI starts showing everything after those first 25 as _off_.

**Comment by unlikelyzero** [comment]
Adding some retesting for the new ui

**Comment by unlikelyzero** [comment]
will not need to add coverage for pagination for this list
