### ISSUE TITLE
credential typo credenital

### ISSUE THREAD

**Issue by medberry** [ansible/awx#2946]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Noticed that in the gui, sometimes credential (in tooltips) is misspelled.

##### ENVIRONMENT
* AWX version: 3.3.1 and later (maybe earlier)

##### STEPS TO REPRODUCE

git clone $AWX; cd awx; grep -rIn -e credenital . ; echo Yep, there's a bug

##### EXPECTED RESULTS

No typos returned

##### ACTUAL RESULTS

original error plus translations in .po files:

[medberry@thestral awx]$ grep -rIni -e credenital .
./awx/ui/client/src/credential-types/list/main.js:10:angular.module('credenitalTypesList', [])
./awx/ui/client/src/credential-types/credential-types.list.js:58:                awToolTip: i18n._('Edit credenital type'),
./awx/ui/po/ansible-tower-ui.pot:1528:msgid "Edit credenital type"
./awx/ui/po/fr.po:1721:msgid "Edit credenital type"
./awx/ui/po/es.po:1723:msgid "Edit credenital type"
./awx/ui/po/ja.po:1662:msgid "Edit credenital type"
./awx/ui/po/nl.po:1713:msgid "Edit credenital type"

##### ADDITIONAL INFORMATION

Badee badee badee that's all folks.

**Comment by wenottingham** [comment]
Fixed in #2947
