### ISSUE TITLE
Frameable Responses

### ISSUE THREAD

**Issue by nikkyjha** [ansible/awx#2950]
We have been actively using AWX and blocked on the below security finding.

**Summary** The application does not set a suitable X-Frame-Options header in the responses to prevent framing.

**Impact** It is possible for a malicious user to frame content of the application on a malicious website. This may be used in a clickjacking attack, where the attacker's page overlays a hidden, framed version of the application. A user could then be persuaded to perform actions on the application, like clicks, keystrokes, or dragging content An attacker could potentially use this to cause the user to unknowingly perform an action in the framed application.

**Details** The X-Frame-Options header is not sent in responses from the server.

**HTTP Request**:

GET /api/v2/jobs/10695/job_events/? page_size=200&order_by=start_line&not__event__in=playbook_on_start,playbook_on_play_s tart,playbook_on_task_start,playbook_on_stats HTTP/1.1
Host: sl73vdpciapd002 Accept: application/json, text/plain, */*
X-Auth-Token: Token 34abe61cf8c2bf1b4d9a53432fe683e8dd6d9074
Authorization: Token 34abe61cf8c2bf1b4d9a53432fe683e8dd6d9074
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Referer: http://<some hostname>
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cookie: ---- trimmed ----

**HTTP Response**:
HTTP/1.1 200 OK
Server: nginx/1.12.2
Date: Tue, 21 Aug 2018
12:30:14 GMT
Content-Type: text/html;
charset=utf-8
Content-Length: 19443
Connection: close
X-API-Time: 0.055s
X-API-Total-Time: 0.149s
Allow: GET, PUT, PATCH,
DELETE, HEAD, OPTIONS
Content-Language: en
Vary: Accept,
Accept-Language, Cookie
X-API-Node: awx
Strict-Transport-Security:
max-age=15768000

**Remediation Recomendations**
The application should send responses that include the X-Frame-Options header set to DENY or SAMEORIGIN to prevent the page being framed by a malicious site

**Comment by ryanpetrello** [comment]
Something like:

`add_header X-Frame-Options "DENY";`

...here:

https://github.com/ansible/awx/blob/devel/installer/roles/image_build/templates/nginx.conf#L46

...would likely resolve this.

**Comment by Spredzy** [comment]
Closed-by: https://github.com/ansible/awx/pull/3038
