### ISSUE TITLE
Webhook Json validation does not work with arrays

### ISSUE THREAD

**Issue by joe-speedboat** [ansible/awx#2951]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### ENVIRONMENT
* AWX version: 2.1.2
* AWX install method: docker
* Ansible version:  2.7.5
* Operating System: CentOS 7.6.1810
* Web Browser: Firefox 64.0

##### STEPS TO REPRODUCE
* Log into AWX Web
* Notifications > New
* Type Webhook
* Fill the json box with
```
{ "UserName": "", "Password": "", "Originator": "", "Recipients": [ "" ], "MessageText": "", "DeferredDeliveryTime": "", "FlashingSMS": "", "URLBufferedMessageNotification": "", "URLDeliveryNotification": "", "URLNonDeliveryNotification": "", "AffiliateID": "", "ForceGSM7bit": false }
```

##### EXPECTED RESULTS
Save button should be available after filling all the mandatory fields.

##### ACTUAL RESULTS
Save button is grayed out

##### ADDITIONAL INFORMATION
As soon as you remove the "[ ]" save is possible, but array sould be allowed, it is a valid json object.

**Comment by jakemcdermott** [comment]
Hey there. Thanks for creating this issue. I've reproduced this one with the steps you've provided.

Note for when this gets worked on:

I looked into this for a moment. We'd need to do some testing (and also a bit of digging into whether or not we had a reason for preventing this in the first place) but I think we might be able to resolve this one by relaxing the [input validation for nested keys](https://github.com/ansible/awx/blob/devel/awx/ui/client/src/notifications/add/add.controller.js#L98) to allow arrays (or perhaps specifically only arrays of all strings), ex: `if (_.isObject(headers[k]) && !_.isArray(headers[k))`

**Comment by joe-speedboat** [comment]
Hi @jakemcdermott 
Thanks for looking at this, would be great to have arrays available in webhooks soon.
but no stress...

cu
chris

**Comment by cgs-admin** [comment]
AWX 4.0

I hit the same issue when trying to setup a webhook/notification for discord.

Discord requires an array but I can't save the json.

**Comment by unlikelyzero** [comment]
@akus062381 can you please retest this manually, this does not require a stub

**Comment by akus062381** [comment]
I verified that this has been fixed
Also verified testability
