### ISSUE TITLE
AWX ignore inventory variables when hosts in group

### ISSUE THREAD

**Issue by skylinetux** [ansible/awx#2953]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
AWX ignore inventory variables when hosts in group.

`$ cat test_vault/main.yml 
- name: Check template
  hosts: all
  tasks:
    - name: Copy
      copy:
        content: '{{ vault_data }}'
        dest: "/tmp/vault.data"
`
[https://i.imgur.com/L7XIaHX.png](url)
[https://i.imgur.com/PpUaBQL.png](url)
[https://i.imgur.com/PpUaBQL.png](url)
[https://i.imgur.com/wDzJyyx.png](url)
[https://i.imgur.com/xZpkvfR.png](url)
[https://i.imgur.com/xZpkvfR.png](url)
[https://i.imgur.com/LJYkTu7.png](url)

##### ENVIRONMENT
* AWX version: 2.1.0
* AWX install method: docker on linux
* Ansible version:  2.7.2
* Operating System:  Ubuntu 18.04.1 LTS
* Web Browser: Google Chrome Version 71.0.3578.80 (Official Build) (64-bit)

**Comment by wenottingham** [comment]
Should be fixed in 2.1.1.
