### ISSUE TITLE
AWX - Unable to configure only HTTPS/SSL

### ISSUE THREAD

**Issue by linuxcube** [ansible/awx#2954]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY
New installation, trying to get https/SSL connection working...I am not sure why AWX only permits http connection in particular when it involves username/password credentials.

##### ENVIRONMENT
* AWX version: 2.1.1.0
* AWX install method: docker on linux
* Ansible version:  2.7.4
* Operating System: Red Hat Enterprise Linux 7.6
* Web Browser: Chrome 71, Firefox 60.4, Internet Explorer 11

##### STEPS TO REPRODUCE

Went inside the ansible/awx_web container to try to modified the nginx.conf to reflect port 443 instead of 8052, this resulted in the webserver to stop working.

##### EXPECTED RESULTS

switching from 8052 to 443 should allow the nginx web-server to run in port 443 instead of 80 redirect to 8052, this is not intended outcomes. I am expecting that port 80 will be redirected to 443, considering we want only 443 traffic to be use for AWX in its entirety. 

##### ACTUAL RESULTS

The results reflected nginx to stop working.

##### ADDITIONAL INFORMATION

This is a clean install of AWX running the latest 2.1.1.0 as of the time of this writting. Please advise on the best approach to get the connectivity to ONLY allow https traffic.

**Comment by matburt** [comment]
This is not how that works... if you aren't sure how to configure nginx to use https on the right port and modify your docker configuration accordingly then you should use a load balancer in front of AWX (like HAProxy).

**Comment by linuxcube** [comment]
Why is this topic getting close without any sort of recommendation on configuring nginx with SSL?
