### ISSUE TITLE
confusing "inventory script"

### ISSUE THREAD

**Issue by medberry** [ansible/awx#2955]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI
 
##### SUMMARY
The "inventory scripts" selection does NOT allow you to specify a project and an inventory script. Yes, you can do this directly under inventory but not with the "inventory script" selection (which is what a novice is more likely to choose). It does allow you to "pasted" in an inventory script but that's full of fail. I should be able to enter a record for the inventory script from a project in the inventory script pick itself. This is horrible UX that can be made better (with no new real functionality, just better/proper exposure.)

##### ENVIRONMENT
* AWX version: devel

##### STEPS TO REPRODUCE

Just try and create an inventory script with the inventory script config pick and try and refer to a project owned script.
##### EXPECTED RESULTS

Expect to see an option to choose a project and a script.
##### ACTUAL RESULTS
Only allowed to cut/paste one.

**Comment by wenottingham** [comment]
This is different things for different use cases... I agree that it's confusing, but we wouldn't use the project picker here.
