### ISSUE TITLE
allow passing job_type to job template callback api

### ISSUE THREAD

**Issue by hlarsen** [ansible/awx#2957]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Currently it appears if a Job Template has a job type of check, it cannot be overridden when using the callback API. Because of this to actually have the template run from a callback job type must be set to run. I'd like to be able to keep the Job Template set to check in AWX but override it with run when calling the API.

##### ADDITIONAL INFORMATION
I've attempted to add job_type: run to the POST json and extra_vars, doesn't look like it did the trick. Setting the Job Template job type to run in AWX results in the job running as one would expect.

**Comment by shanemcd** [comment]
This is now a prompt-able field. You should be able to pass it in to the payload now. See `-d` in the curl example under https://docs.ansible.com/automation-controller/latest/html/userguide/job_templates.html#provisioning-callbacks.
