### ISSUE TITLE
error with requirements.yml ssh on gitlab

### ISSUE THREAD

**Issue by cavamagie** [ansible/awx#2958]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
hi i usi a scm with scm privare key 
to download project no problem

when i use a requirement.yml 
like this

- src: git@anacard.com/AnsibleGalaxy/Common.git
  scm: git
  version: master

 i receive this error 
i see in the manual that the configuration for github is correct
example

# from GitLab or other git-based scm
- src: git@gitlab.company.com:mygroup/ansible-base.git
  scm: git
  version: "0.1"  # quoted, so YAML doesn't parse this as a floating-point value

##### ENVIRONMENT
 AWX 2.1.2.0  
 AWX install method: openshift, 
 Web Browser: Chrome

##### STEPS TO REPRODUCE

- src: git@anacard.com/AnsibleGalaxy/Common.git
  scm: git
  version: master

{
    "_ansible_parsed": true,
    "stderr_lines": [
        "\u001b[1;35m [WARNING]: - Common was NOT installed successfully: - command /usr/bin/git\u001b[0m",
        "\u001b[1;35mclone git@gitlab.anacard.com/AnsibleGalaxy/Common.git Common failed in directory\u001b[0m",
        "\u001b[1;35m/var/lib/awx/.ansible/tmp/ansible-local-72j3SkVV/tmpaaF76g (rc=128)\u001b[0m",
        "\u001b[1;35m\u001b[0m",
        "\u001b[0;31mERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.\u001b[0m"
    ],
    "cmd": [
        "AnsibleGalaxy",
        "install",
        "-r",
        "requirements.yml",
        "-p",
        "/var/lib/awx/projects/_25__proj_l6_common_ansible_galaxy100208/roles/"
    ],
    "end": "2018-12-14 09:15:53.772215",
    "_ansible_no_log": false,
    "stdout": "",
    "changed": false,
    "start": "2018-12-14 09:15:51.309139",
    "delta": "0:00:02.463076",
    "stderr": "\u001b[1;35m [WARNING]: - Common was NOT installed successfully: - command /usr/bin/git\u001b[0m\n\u001b[1;35mclone git@gitlab.anacard.com/AnsibleGalaxy/Common.git Common failed in directory\u001b[0m\n\u001b[1;35m/var/lib/awx/.ansible/tmp/ansible-local-72j3SkVV/tmpaaF76g (rc=128)\u001b[0m\n\u001b[1;35m\u001b[0m\n\u001b[0;31mERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.\u001b[0m",
    "rc": 1,
    "invocation": {
        "module_args": {
            "warn": true,
            "executable": null,
            "chdir": "/var/lib/awx/projects/_25__proj_l6_common_ansible_galaxy100208/roles",
            "_raw_params": "AnsibleGalaxy install -r requirements.yml -p /var/lib/awx/projects/_25__proj_l6_common_ansible_galaxy100208/roles/",
            "removes": null,
            "argv": null,
            "creates": null,
            "_uses_shell": false,
            "stdin": null
        }
    },
    "stdout_lines": [],
    "msg": "non-zero return code"
}

##### ACTUAL RESULTS

{
    "_ansible_parsed": true,
    "stderr_lines": [
        "\u001b[1;35m [WARNING]: - Common was NOT installed successfully: - command /usr/bin/git\u001b[0m",
        "\u001b[1;35mclone git@gitlab.anacard.com/AnsibleGalaxy/Common.git Common failed in directory\u001b[0m",
        "\u001b[1;35m/var/lib/awx/.ansible/tmp/ansible-local-72j3SkVV/tmpaaF76g (rc=128)\u001b[0m",
        "\u001b[1;35m\u001b[0m",
        "\u001b[0;31mERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.\u001b[0m"
    ],
    "cmd": [
        "AnsibleGalaxy",
        "install",
        "-r",
        "requirements.yml",
        "-p",
        "/var/lib/awx/projects/_25__proj_l6_common_ansible_galaxy100208/roles/"
    ],
    "end": "2018-12-14 09:15:53.772215",
    "_ansible_no_log": false,
    "stdout": "",
    "changed": false,
    "start": "2018-12-14 09:15:51.309139",
    "delta": "0:00:02.463076",
    "stderr": "\u001b[1;35m [WARNING]: - Common was NOT installed successfully: - command /usr/bin/git\u001b[0m\n\u001b[1;35mclone git@gitlab.anacard.com/AnsibleGalaxy/Common.git Common failed in directory\u001b[0m\n\u001b[1;35m/var/lib/awx/.ansible/tmp/ansible-local-72j3SkVV/tmpaaF76g (rc=128)\u001b[0m\n\u001b[1;35m\u001b[0m\n\u001b[0;31mERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.\u001b[0m",
    "rc": 1,
    "invocation": {
        "module_args": {
            "warn": true,
            "executable": null,
            "chdir": "/var/lib/awx/projects/_25__proj_l6_common_ansible_galaxy100208/roles",
            "_raw_params": "AnsibleGalaxy install -r requirements.yml -p /var/lib/awx/projects/_25__proj_l6_common_ansible_galaxy100208/roles/",
            "removes": null,
            "argv": null,
            "creates": null,
            "_uses_shell": false,
            "stdin": null
        }
    },
    "stdout_lines": [],
    "msg": "non-zero return code"
}

**Comment by cavamagie** [comment]
solved changing url with :

**Comment by mbmokgosi** [comment]
Having the exact same issue, how did you solve it?

**Comment by aqua-terra** [comment]
> Having the exact same issue, how did you solve it?

I think he put in a port number. I had the same issue but was able to get it working when I switched from using https to ssh on the source url.
