### ISSUE TITLE
How to remove old logs

### ISSUE THREAD

**Issue by rcextreme** [ansible/awx#2963]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME
 - UI

##### SUMMARY
How do I delete old log files.  I did the docker installation method.  After a new months running my file system is full.  I can see the pgdocker dir and /var/lib/docker are the biggest offenders.  I had scheduled the "Clean Up Job Schedule" and "Clean up activity schedule" it doesn't seem like this cleared logs.  

##### ENVIRONMENT
* AWX version: 1.0.6.37
* AWX install method: docker on linux
* Ansible version:  2.6.1
* Operating System: Ubuntu 18.04
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Run AWX tower jobs till file systems get full

**Comment by wenottingham** [comment]
Hi -

This is not a bug with AWX. Please see the mailing list (https://groups.google.com/forum/#!forum/awx-project) or the IRC channel (#ansible-awx on irc.freenode.net).
