### ISSUE TITLE
DEPRECATION: Google+ OAuth APIs

### ISSUE THREAD

**Issue by inhumantsar** [ansible/awx#2964]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
Google will be shutting down the G+ OAuth APIs, which AWX uses for Google authentication, on March 7 2019. Information on its replacement can be found here: https://developers.google.com/identity/

##### ENVIRONMENT
* AWX version: current
* AWX install method: docker on linux
* Ansible version:  2.7.x
* Operating System: EL7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

N/A

##### EXPECTED RESULTS

N/A

##### ACTUAL RESULTS

N/A

**Comment by wenottingham** [comment]
https://github.com/python-social-auth/social-core/issues/300

**Comment by omab** [comment]
@inhumantsar, @wenottingham, linked issue https://github.com/python-social-auth/social-core/issues/300 is clsoed now that the related PR https://github.com/python-social-auth/social-core/pull/301 was merged.

**Comment by wenottingham** [comment]
@omab am I reading it right that this is in the 3.0.0 that was just released?

ETA: never mind, yes I see it.

**Comment by omab** [comment]
@wenottingham, yes, that's correct

**Comment by ryanpetrello** [comment]
We've just released a new version of awx (https://github.com/ansible/awx/releases/tag/3.0.0) which should resolve this issue with an update to the latest version of the `social-core` library.
