### ISSUE TITLE
Credential/Inventory lookups broken in workflow job template node form

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#297]
Initially reported: https://github.com/ansible/awx/issues/263#issuecomment-332021526

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### STEPS TO REPRODUCE

1) Create a job template with a default credential, prompt for credential, default inventory and prompt for inventory.
2) Create a workflow
3) Go to workflow editor and add a new node
4) Select the JT created in step 1
5) Click the magnifying glass lookup for inventory or credential

##### EXPECTED RESULTS

User should be able to select a different inv/credential using the lookup.

##### ACTUAL RESULTS

Workflow editor closes.  I think this is because of some bad state transition.  The following is in the console:

<img width="1440" alt="screen shot 2017-09-26 at 9 01 39 am" src="https://user-images.githubusercontent.com/9889020/30861644-6663f53e-a299-11e7-8124-6e8009bdcc50.png">

**Comment by jaredevantabor** [comment]
This was fixed downstream. Will get fixed w/ next merge from 3.2.0 branch. Closing now.
