### ISSUE TITLE
When activating postgres container, encounter "no such directory"

### ISSUE THREAD

**Issue by Stargator** [ansible/awx#2970]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Unable to go through Activate postgres container task.

Executed `ansible-playbook -i inventory install.yml`

```bash
TASK [local_docker : Activate postgres container] ******************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))"}
	to retry, use: --limit @/home/ec2-user/awx/installer/install.retry
```

##### ENVIRONMENT
* AWX version: 4641056829e136fd97cd93a1f1ad44eed5024ac2
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.4.6.0-1.amzn2.0.1
* Operating System: Amazon Linux 2
* Web Browser: N/A

##### STEPS TO REPRODUCE

Clone AWX and AWX-logo repositories into the same directory.

Run the following:
```bash
sudo amazon-linux-extras install epel
sudo amazon-linux-extras install ansible2
sudo amazon-linux-extras install docker
sudo amazon-linux-extras install nginx

sudo wget -O /etc/yum.repos.d/awx-rpm.repo https://copr.fedorainfracloud.org/coprs/mrmeee/awx/repo/epel-7/mrmeee-awx-epel-7.repo

sudo yum install -y epel-release docker ansible postgresql-server rabbitmq-server wget memcached nginx
```

cd into the directory that contains awx and awx-logo.

Update awx/installer/roles/local_docker/tasks/standalone so the path for Postgresql is changed from `/var/lib/postgresql/data` to `/var/lib/pgsql/data`

Run the installer: `ansible-playbook -i inventory install.yml`

##### EXPECTED RESULTS

I expected the Activate postgres container task to be completed successfully without issue.

##### ACTUAL RESULTS

```bash
TASK [local_docker : Activate postgres container] ******************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))"}
	to retry, use: --limit @/home/ec2-user/awx/installer/install.retry
```

##### ADDITIONAL INFORMATION

N/A

**Comment by matburt** [comment]
Sorry, we don't support the rpm installer... you'll need to contact the maintainer of that project.

**Comment by Stargator** [comment]
@matburt Thanks, I got the same error when running the installation from the aws repo. I tried several different ways to get it installed. I'll just shelve this for another time.

**Comment by ntman4real** [comment]
Had the same issue as well.  Using AMZ Linux 2.  Got it to work with the follwing, as "ec2-user".

sudo yum install -y ansible docker
sudo usermod -a -G docker ec2-user #must logout of session for this to work
sudo service docker start
curl -O https://bootstrap.pypa.io/get-pip.py
python get-pip.py --user
pip install docker --user
git clone https://github.com/ansible/awx.git
#logout of session to make enable the docker permissions for ec2-user
cd ./awx/installer
ansible-playbook -i inventory install.yml
