### ISSUE TITLE
AWX is failing to do SCM pull after openshift upgrade to 3.9 from 3.7 

### ISSUE THREAD

**Issue by codeby-sreddy** [ansible/awx#2971]
##### ISSUE TYPE
- Bug Report
 
##### COMPONENT NAME

- Installer
 
 
##### SUMMARY
Awx is failing to to SCM update after the openshift upgrade to 3.9. ( one of the issue )
 
we have awx installed on openshift version 3.6 with awx images that were pushed to our own registry ( to avoid accidental upgrades ). these images were working fine with version openshift 3.7 and when we upgrade the openshift to version 3.9 ( were docker upgraded to 1.13 ) awx is failing with new error that we dint see in version 3.6 and 3.9
 
awx_web image is failing with error permission denied for /etc/passwd and also user in container is changed.
after upgrade:
sh-4.2$ id
uid=1000 gid=0(root) groups=0(root)
 
before upgrade:
sh-4.2$ id
uid=1000(awx) gid=0(root) groups=0(root)
 
##### ENVIRONMENT
* AWX version: AWX 1.0.6.17
* AWX install method: openshift
* Ansible version:  2.5.5
* Operating System: Rhel 7
* Web Browser: chrome
 
##### STEPS TO REPRODUCE
 
upgrade openshift from 3.7 to 3.9. and start the awx and try doing scm pull.
 
##### EXPECTED RESULTS
 
A smooth scm pull
 
##### ACTUAL RESULTS
 
scm pull is failing
 
##### ADDITIONAL INFORMATION
 
after our multiple testings. these images are working fine on docker 1.12 and 1.10 but failing on docker 1.13.

**Comment by matburt** [comment]
hmm, we'll need to look and see why permission is now failing on that file. The image should provide that file as a way for us to assign a username to the userid. Have you changed the way openshift behaves here? Normally it will generate a random uid for the user at container launch time.

**Comment by ryanpetrello** [comment]
Closing due to age and no response.  Please retry on a newer version of AWX.
