### ISSUE TITLE
Bug: SCHEDULE_MAX_JOBS is ignored for scheduled Workflow Job Templates

### ISSUE THREAD

**Issue by b0urn3** [ansible/awx#2975]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY

The setting `SCHEDULE_MAX_JOBS` is ignored for WFTJs but works correctly for JTs.

##### ENVIRONMENT
* AWX version: devel branch
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  N/A
* Operating System: N/A
* Web Browser: N/A

##### STEPS TO REPRODUCE

The Job Template model implements usage of the `SCHEDULE_MAX_JOBS`

https://github.com/ansible/awx/blob/d57fc998d5b5c6744595bc768aba6ec8861bb5b5/awx/main/models/jobs.py#L454-L459

however the same isn't true for Workflows

https://github.com/ansible/awx/blob/d57fc998d5b5c6744595bc768aba6ec8861bb5b5/awx/main/models/workflow.py#L408-L410

##### EXPECTED RESULTS

`SCHEDULE_MAX_JOBS` working for Workflow Job Templates same as it's working for Job Templates.

##### ACTUAL RESULTS

`SCHEDULE_MAX_JOBS` is ignored for Workflow Job Templates.

**Comment by ryanpetrello** [comment]
Addressed by https://github.com/ansible/awx/pull/3005
