### ISSUE TITLE
Allow Org Admins to remove users in their own Org.

### ISSUE THREAD

**Issue by gamuniz** [ansible/awx#2979]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI
 

##### SUMMARY

The ability to remove a user that was created by the Org admin by the same user should be possible if the user only belongs to the Org to which the admin has permissions.

##### ENVIRONMENT
* AWX version: latest
* AWX install method: installer
* Ansible version:  2.7.5
* Operating System: RHEL7
* Web Browser: Chrome

##### STEPS TO REPRODUCE
1. Use Org administrator to create a user
2. Attempt to delete same user

##### EXPECTED RESULTS
Able to delete the user just created. 

##### ACTUAL RESULTS
Unable to delete newly created user.

**Comment by AlanCoding** [comment]
It looks like this is how it worked in 2.4.5, but then in 3.3.0, it changed such that only superuser could delete.

https://github.com/ansible/tower/commit/eae73496650a92fac033349bcd85635893928830#diff-c14c9d695bfbeb70889f2b42b18ed42dL259

Given that our logic for editing a user is now more conservative, I would not have a problem with allowing org admins to delete a user (criteria is that they are org admin of all orgs user is member of).

**Comment by kdelee** [comment]
@rebeccahhh tried out https://github.com/ansible/awx/pull/4839 by creating an org admin, logging in as them, then creating another user in the org I am admin of, then I was able to delete them in UI.

Works for me, merge it!

**Comment by rebeccahhh** [comment]
Merged

**Comment by kdelee** [comment]
Works for me!
