### ISSUE TITLE
UX Enhancement: Add Ability to Collapse Jobs List

### ISSUE THREAD

**Issue by kialam** [ansible/awx#2984]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

Add ability to expand/collapse the Jobs List. Below are the following changes proposed:

1. Default view for the Jobs List view is collapsed with Job Status, Job Name, Job Type Label, and Relaunch Icon.
<img width="1420" alt="screen shot 2019-01-09 at 12 45 49 pm" src="https://user-images.githubusercontent.com/2293210/50917815-8aa8eb80-140c-11e9-95d8-9a32c0e37bf2.png">

2. Add an expand/collapse bar to the top of the Jobs List View
<img width="1413" alt="expand_collapse_toolbar" src="https://user-images.githubusercontent.com/2293210/50917499-a364d180-140b-11e9-9cb0-fbe025ce31f8.png">

- Clicking the expand button will expand all items in the list.
- Clicking the collapse button will collapse all items in the list.

3. Spread out Job detail items into flexible grid columns of 3, collapsing down to 2, and 1
![tower-jobs-table-expand](https://user-images.githubusercontent.com/2293210/50921371-e0ce5c80-1415-11e9-984e-0e2646f33c67.png)

**Comment by trahman73** [comment]
Updated image for Step 3 above...

![tower-jobs-table-expand](https://user-images.githubusercontent.com/13351591/50925805-67d50200-1421-11e9-973e-5a21562ee646.png)

**Comment by dsesami** [comment]
@kialam @trahman73 I asked a few people what they thought the expand and collapse buttons did (without knowing ahead of time) and it wasn't the most intuitive thing for them -- do you think perhaps we can make it a single toggle button? and even explicitly have "expand all/collapse all" text? 

It also feels like it might be better to have it on the left side, since per-row toggles tend to rest on the left side in my experience.

**Comment by shanemcd** [comment]
Was thinking about this while looking at @dsesami's screen earlier and I wasn't immediately clear on what that icon is supposed to do. What do y'all think about some variation on this concept?

<img width="199" alt="screen shot 2019-01-10 at 10 11 36 am" src="https://user-images.githubusercontent.com/773186/50977370-25aecd80-14c0-11e9-831c-12d24bf39541.png">

**Comment by elyezer** [comment]
Verification list:

- [x] Check if the same information is being presented.
- [x] Check some different resolutions for any inconsistency.
- [x] Check if the expand/collapse works on Chrome and Firefox on both Windows and Linux
- [x] Check if the default state is compact
- [x] Check if pagination is working as expected: the state persists when navigating (if it is expanded then navigating to another page will present it expanded)
- [x] Check if the state is reset to compact when navigating to another page and then back to the listing

**Comment by trahman73** [comment]
Here is an updated screen based on the feedback from above. I think we should still provide tooltips to this example to further explain the options.

![tower-jobs-table-expand](https://user-images.githubusercontent.com/13351591/50993359-7ab20a00-14e7-11e9-9a5d-f1f339adf7c0.png)

**Comment by dsesami** [comment]
Verified most of the scenarios described in @elyezer 's scenarios above and checked them off. This needs to be tested on Windows still, if @unlikelyzero or elyezer can provide that environment.

**Comment by dsesami** [comment]
Verified the last windows compatibility tests, closing the issue.
