### ISSUE TITLE
UX Enhancement: Add Ability to Collapse Templates List

### ISSUE THREAD

**Issue by kialam** [ansible/awx#2985]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

Add ability to expand/collapse the Templates List. Below are the following changes proposed:

1. Default view for the Templates List view is collapsed with Template Name, Template Type Label, Activity Stream, and Relaunch and Copy Icons.
<img width="1386" alt="screen shot 2019-01-09 at 2 04 46 pm" src="https://user-images.githubusercontent.com/2293210/50922175-da40e480-1417-11e9-87ab-57396b15aa89.png">

2. Add an expand/collapse bar to the top of the Templates List View
<img width="1378" alt="expand_collapse_toolbar_templates" src="https://user-images.githubusercontent.com/2293210/50922241-02c8de80-1418-11e9-8b02-01aa5f5e28c6.png">

- Clicking the expand button will expand all items in the list.
- Clicking the collapse button will collapse all items in the list.

3. Spread out Template detail items into flexible grid columns of 3, collapsing down to 2, and 1 (mockups to come)

**Comment by elyezer** [comment]
Verification list:

- [x] Check if the same information is being presented.
- [x] Check some different resolutions for any inconsistency.
- [ ] Check if the expand/collapse works on Chrome and Firefox on both Windows and Linux
- [x] Check if the default state is compact
- [x] Check if pagination is working as expected: the state persists when navigating (if it is expanded then navigating to another page will present it expanded)
- [x] Check if the state is reset to compact when navigating to another page and then back to the listing

**Comment by dsesami** [comment]
Verified most of the scenarios presented by @elyezer minus same comments as mirrored in https://github.com/ansible/awx/issues/2984#issuecomment-458004189

both this and the projects list https://github.com/ansible/awx/issues/2986 have the same issue in that if it is in expanded mode, and the copy button is used to copy and create a new template or project, the page is reset to compact mode. i have created an issue here: https://github.com/ansible/awx/issues/3081

**Comment by dsesami** [comment]
Verified the last windows compatibility tests, closing the issue.
