### ISSUE TITLE
UX Enhancement: Add Ability to Collapse Projects List

### ISSUE THREAD

**Issue by kialam** [ansible/awx#2986]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

Add ability to expand/collapse the Projects List. Below are the following changes proposed:

1. Default view for the Projects List view is collapsed with Project Sync Status, Project Name,Project Type Label, Sync, Copy, and Delete Icons.
<img width="1382" alt="screen shot 2019-01-09 at 2 10 51 pm" src="https://user-images.githubusercontent.com/2293210/50922774-4c65f900-1419-11e9-886d-0558fef76073.png">

2. Add an expand/collapse bar to the top of the Projects List View
<img width="1407" alt="projects_toolbar" src="https://user-images.githubusercontent.com/2293210/50922806-5c7dd880-1419-11e9-99f1-6815154a3fa9.png">

- Clicking the expand button will expand all items in the list.
- Clicking the collapse button will collapse all items in the list.

3. Spread out Project detail items into flexible grid columns of 3, collapsing down to 2, and 1 (mockups to come)

**Comment by elyezer** [comment]
Verification list:

- [x] Check if the same information is being presented.
- [x] Check some different resolutions for any inconsistency.
- [ ] Check if the expand/collapse works on Chrome and Firefox on both Windows and Linux
- [x] Check if the default state is compact
- [x] Check if pagination is working as expected: the state persists when navigating (if it is expanded then navigating to another page will present it expanded)
- [x] Check if the state is reset to compact when navigating to another page and then back to the listing

**Comment by dsesami** [comment]
See comments on https://github.com/ansible/awx/issues/2985#issuecomment-458004609

**Comment by dsesami** [comment]
Verified the last windows compatibility tests, closing the issue.
