### ISSUE TITLE
UX: better space usage on wide screens

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#2987]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY

Our current UX for the new-style detailed lists has a *lot* of whitespace on wide screens.

![screenshot from 2019-01-09 14-53-00](https://user-images.githubusercontent.com/5208768/50924752-7cfc6180-141e-11e9-93c7-9e046142fef5.png)

![screenshot from 2019-01-09 14-53-19](https://user-images.githubusercontent.com/5208768/50924760-7ff75200-141e-11e9-8d18-fb99d1b4db55.png)

Ideally, there are ways we can utilize the space better in this scenario.

**Comment by trahman73** [comment]
We will try a 3 column approach that would scale down when the browser is resized.

![tower-jobs-table-expand](https://user-images.githubusercontent.com/13351591/50925573-c188fc80-1420-11e9-8fce-65a273a71227.png)

**Comment by dsesami** [comment]
Verified that this appears correctly on chrome and firefox and responds well to varying widths.
