### ISSUE TITLE
UX Enhancement: Collapse My View lists

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#2988]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
Mockup: https://tower-mockups.testing.ansible.com/mockups/misc/portal/

As part of the "collapse/expand" list work, we want to condense the content within My View to display a brief view of the Job Template and Job list. 

**Current My View:**
<img width="1413" alt="screen shot 2019-01-09 at 3 04 16 pm" src="https://user-images.githubusercontent.com/15881645/50925717-2a707480-1421-11e9-87ff-c350025a436d.png">

**Proposed My View:** 
<img width="1341" alt="screen shot 2019-01-10 at 10 22 50 am" src="https://user-images.githubusercontent.com/15881645/50978121-c05bdc00-14c1-11e9-9a68-838be3dc4a3a.png">

1. Job Templates
    - Row Content: Name, Badge, Activity Status, Launch button

2. Jobs
  a. My Jobs
    - Row Content:  Status, Name, Badge, Launch button

    b. All Jobs
    - Row Content:  Status, Name, Badge, Launch button

**Comment by elyezer** [comment]
Verification list:

- [x] Check if the same information is being presented.
- [x] Check some different resolutions for any inconsistency.
- [x] Check if the expand/collapse works on Chrome and Firefox on both Windows and Linux
- [x] Check if the default state is compact
- [x] Check if pagination is working as expected: the state persists when navigating (if it is expanded then navigating to another page will present it expanded)
- [x] Check if the state is reset to compact when navigating to another page and then back to the listing

**Comment by dsesami** [comment]
Mirrored testing and comments as to https://github.com/ansible/awx/issues/2984#issuecomment-458004189. Browserstack verification still needs to occur and My View also triggers odd sidebar behavior https://github.com/ansible/awx/issues/3082

**Comment by dsesami** [comment]
Finished verification scenario on windows and the sidebar is fine now, marking as closed.
