### ISSUE TITLE
RFE: Inventory/Hosts distributed locks

### ISSUE THREAD

**Issue by sumkincpp** [ansible/awx#2989]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Currently it's possible to run simultaneously different jobs on single device which may cause problems.

This feature will forbid execution of 1 or more job on a single host/inventory.
* When inventory is specified whole inventory should locked for execution for execution of other jobs
* When hosts are specified separate hosts from inventory should be locked for execution of other jobs

Would also be great to see execution locks in UI.

**Comment by sumkincpp** [comment]
Similar to #2541

**Comment by wenottingham** [comment]
Closing in favor of #2541.
