### ISSUE TITLE
Bug: Jobs fail due to long hard-coded ssh control path

### ISSUE THREAD

**Issue by scottlinux** [ansible/awx#299]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

https://github.com/ansible/awx/blob/devel/awx/main/tasks.py

##### SUMMARY

Due to the hard-coded ssh control_path in awx here:

https://github.com/ansible/awx/blob/devel/awx/main/tasks.py#L1042

awx jobs fail against hosts with long yet valid hostnames.

##### ENVIRONMENT
* AWX version: 3.0.3
* Ansible version:  2.3.1.0
* Operating System: RHEL 7.x

##### STEPS TO REPRODUCE

Launch a job against host with a long hostname of 41 characters or more, ansible fails (see below).

##### EXPECTED RESULTS

Being able to configure the control path or for the hard-code to be valid.

##### ACTUAL RESULTS

The output seen in tower is:

`fatal: [xxx-xxxxx-xxx-xxxxx-xxxxxx.xxxx-xx-xxx.xxx.xxx.xxxxxx.xxx]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ControlPath too long\r\n", "unreachable": true}`

and/or:

`\r\nControlPath "/tmp/ansible_tower_XUag7Q/cp/ansible-ssh-xxxxxx-xxxxxxx.xxxx-xx-xxx.xxx.xxxx.xxxxxx.xxx-22-root.NoZSK9Hu8W0odZZk" too long for Unix domain socket\r\n')`

##### ADDITIONAL INFORMATION

In the current hard-coded control path, one could potentially have a control path that is 130 characters in length which is invalid.

To illustrate, the current hard-code:

`env['ANSIBLE_SSH_CONTROL_PATH'] = os.path.join(cp_dir, '%%h%%p%%r')`

becomes the following:

`/tmp/ansible_tower_XUag7Q/cp/ansible-ssh-xxxxxxxx-xx.xxxx-xx-xxx.xxx.xxxx.xxxxxx.xxx-22-root.NoZSK9Hu8W0odZZk`

Disabling proot / bubblewrap is not an option as the installation is in use by a large team with concurrent jobs and the security of isolated jobs is a desired feature to use. 

Possibly solutions:

* Remove `%%h%%p` from hard-coded value to gain short and valid control path
* Remove hard-coded control path and make this a user configurable option

Footnotes:

* Max length of a unix domain socket is 108 characters[1]

* Max hostname length is 63 characters[2]

[1] http://man7.org/linux/man-pages/man7/unix.7.html
[2] https://tools.ietf.org/html/rfc1034#section-3.1

**Comment by wenottingham** [comment]
Minimum distinguishing information per connection is hostname/port/user; changing this is problematic.

**Comment by wenottingham** [comment]
Note that you''re posting old data above - the path in awx does not have the `ansible-ssh-` component, and it starts with `/tmp/awx-` instead of `/tmp/ansible-tower`, so it's already ~20 characters shorter in awx.

**Comment by scottlinux** [comment]
Awesome, thank you. This is the commercial offering of Ansible Tower, to clarify. I will check the latest version available to me to see if it has these changes.

**Comment by matburt** [comment]
keep us posted

**Comment by scottlinux** [comment]
Hi, I tried with latest commercial version of Ansible Tower: 3.1.5

It appears upstream changes have not gotten pushed out to that product yet.

`"/tmp/ansible_tower_tGrkKC/cp/xxx-xxxxxx-xxx-xxxxx-xxxxxxx.xxxx-xx-xxx.xxx.xxxx.xxxxxx.com22root.ZuLyxwgThntwOmvB" too long for Unix domain socket\r\nControlPath /tmp/ansible_tower_tGrkKC/cp/xxx-xxxxxx-xxx-xxxxx-xxxxxxx.xxxx-xx-xxx.xxx.xxxx.xxxxxx.com22root.ZuLyxwgThntwOmvB too long, disabling multiplexing\r\n')`

**Comment by wenottingham** [comment]
As noted, that removes the `ansible-tower-` part of the path, and there will be an change to  use `/tmp/awx` instead of `/tmp/ansible_tower` in a later release.  There's not much that can be done beyond that.
