### ISSUE TITLE
RFE: Schedule job after other job

### ISSUE THREAD

**Issue by sumkincpp** [ansible/awx#2990]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Similar to #1756, but in a simpler way.

Feature that will allow to schedule a job after completion of other scheduled job.
Many jobs can be scheduled after a certain job is completed. Scheduling can be done starting at some time.

Will help gluing many scheduled "environment dependent" workflows/jobs together .

Benefits are
 - No need for making of one big workflow in Workflow Editor with every prompt
 - Workflows are still "building blocks" but with scheduling capability to arrange them
 - User/Operator decides what to schedule without changing existing workflow or making a new ones

**Comment by wenottingham** [comment]
I strongly believe that if you have dependent jobs, workflows is the best way to accomplish that.

Otherwise, use the API to kick them off on finish.

**Comment by sumkincpp** [comment]
From Operator perspective this may be destructive and will result in many single purpose workflows have been used only once.
