### ISSUE TITLE
Error in installing

### ISSUE THREAD

**Issue by akhilbatra898** [ansible/awx#300]
##### ISSUE TYPE
 - Error Installation

##### COMPONENT NAME
 - Installer

##### SUMMARY
Encounter following error while installing on localhost

````
ERROR! no action detected in task

The error appears to have been in '/home/akhil/awx/installer/image_build/tasks/main.yml': line 64, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Build A`
```

**Comment by matburt** [comment]
You didn't really enough details but from the looks of it, you are using a version of ansible that is too old.

**Comment by krizzie13** [comment]
hey,

Just downloaded the awx, and wanted to use the docker setup to have a quick look in to it but get the same error:
:~/git/awx/installer$ ansible-playbook -i inventory install.yml
ERROR! no action detected in task

The error appears to have been in '/home/user/git/awx/installer/image_build/tasks/main.yml': line 64, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Build AWX distribution using container
  ^ here

@:~/git/awx/installer$ ansible --version
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
