### ISSUE TITLE
AWX won't start with external PostgreSQL

### ISSUE THREAD

**Issue by AdrianDutu** [ansible/awx#3000]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY
I have installed AWX with an external PostgreSQL DB (9.6). 
I have commented postgres_data_dir in inventory and filled pg_hostname, pg_username, pg_password,
pg_database, pg_port.
I have created the awx db and user on PostgreSQL. I've setup the pg_hba.conf file so it can accept connections. Psql connection from awx_task container to the DB works.

The web page says "AWXis currently upgrading. This page will refresh when complete." And the refresh arrows keep spinning but it never finishes.
![awx](https://user-images.githubusercontent.com/4824201/51118730-60429e00-1811-11e9-97f9-f55d966f328c.PNG)

In the awx_task logs i see:
[awx_task.log](https://github.com/ansible/awx/files/2755530/awx_task.log)

Same error on the awx_web logs.

##### ENVIRONMENT
* AWX version: 2.1.2
* AWX install method: docker compose
* Ansible version:  2.6
* Operating System: CentOS 7

##### STEPS TO REPRODUCE

1. Install an external PostgreSQL instance.
2. Configure the db to accept connections from awx.
3. Create awx user and db.
4. In the inventory file, fill the pg_hostname, pg_username, pg_password, pg_database, pg_port variables with your postgresql instance details.
5. Run install.yml

##### EXPECTED RESULTS

Working AWX instance.

##### ACTUAL RESULTS

Webpage stuck at "AWX is currently upgrading" and DB errors in the logs:
ProgrammingError: relation "conf_setting" does not exist
LINE 1: ...f_setting"."value", "conf_setting"."user_id" FROM "conf_sett...

**Comment by matburt** [comment]
The error you received is normal to see early during a first start before migrations run. How long did you wait? I'd like to see the logs from the running container (not just the logfile).

**Comment by AdrianDutu** [comment]
Hi Matthew,

It's been 6h already. 

[awx_task-json.log](https://github.com/ansible/awx/files/2756233/awx_task-json.log)

I've uploaded as much as the 10mb limit will allow.

**Comment by matburt** [comment]
I probably need to see more of the top of the log. I'd reset everything and capture it from the task container startup until after the migration check.

**Comment by AdrianDutu** [comment]
I figured it out. I am using instance groups. For some reason, one of the hosts in the group did not start. Once I started it the migration completed and I can log in. Thanks for the support, Matt.

**Comment by alsgow** [comment]
Hi @AdrianDutu, I am trying to deploying AWX from ECS but facing same issue. Please find the attached image for error log
<img width="1246" alt="Screen Shot 2019-08-14 at 10 15 48 PM" src="https://user-images.githubusercontent.com/24711327/63068501-55540700-bee1-11e9-8446-a5f6833a67c5.png">
Please let me know if there is any specific solution.
