### ISSUE TITLE
Removal of /api/v1

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#3001]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY

`/api/v2` has been available for quite a while, and `/api/v1` has been deprecated for quite a while as well.

`/api/v1` should eventually be removed (as it's complicating some credential work).

**Comment by unlikelyzero** [comment]
I am assigned as the UI Test Owner for this feature.

**Comment by elyezer** [comment]
I am assigned as the API Test Owner for this feature.

**Comment by kdelee** [comment]
I am picking this issue up and starting by updating dependent tooling.

**Comment by kdelee** [comment]
Works for me, filed https://github.com/ansible/awx/issues/4031 as follow up that https://github.com/ansible/awx/pull/3413 did not address
