### ISSUE TITLE
Proxy Support for Pulling Postgres,Rabbit and Memcached images

### ISSUE THREAD

**Issue by FossilBlade** [ansible/awx#3004]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
When running the installer with local docker behind a corporate proxy, the task is failing to download the docker images from the hub for postgres, rabbitmq and memcached. 

The reason for this is because there is no http_proxy, https_proxy and no_proxy variable defined under the env in the file 'installer/roles/local_docker/tasks/standalone.yml' for the tasks for Activating postgres, rabbitmq and memchached.
  

##### ENVIRONMENT
* AWX version: 2.1.2
* AWX install method: docker on linux, 
* Ansible version:  2.7
* Operating System: CentOs 7

##### STEPS TO REPRODUCE

1. git clone https://github.com/ansible/awx.git
2. cd awx/installer
3. edit inventory file to set proxy variables
4. ansible-playbook -i inventory install.yml

##### EXPECTED RESULTS

All the docker images are downloaded and installation is a success.

##### ACTUAL RESULTS

Cannot download images as no cummunication with docker hub. 

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/32032862/51146229-2201b900-18bb-11e9-8e40-b54d21addbdd.png)

WORKAROUND:
Manually adding following proxy variables to the file 'installer/roles/local_docker/tasks/standalone.yml'
 
http_proxy: "{{ http_proxy | default('') }}"
 https_proxy: "{{ https_proxy | default('') }}"
 no_proxy: "{{ no_proxy | default('') }}"

**Comment by matburt** [comment]
Sounds like your workaround would make a good pull request.

**Comment by ryanpetrello** [comment]
Closed via https://github.com/ansible/awx/pull/3921
