### ISSUE TITLE
RFE: AWX maintenance mode

### ISSUE THREAD

**Issue by sumkincpp** [ansible/awx#3009]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Allow enabling/disabling AWX instance by administrator moving in into "Maintenance mode".
As a result running and scheduling jobs by users should not be permitted.

**Comment by wenottingham** [comment]
Instances can already be disabled, see the 'enabled' flag.

**Comment by sumkincpp** [comment]
@wenottingham AWX instance which have been disabled and maintenance modes are different things. 
With current disabled mode you can still schedule scenarios and even run them(Though, if you run task it is moved to pending state).  Also non-admin users can edit and perform tasks in disabled mode.
I believe that in maintenance mode all tasks by non-admin users should be forbidden.
