### ISSUE TITLE
Support for the Amazon (Karoo) Operating System

### ISSUE THREAD

**Issue by Stargator** [ansible/awx#3011]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - Installer

##### SUMMARY
I tried to install on Amazon (Karoo) OS and I got a response that it was not supported. I'd like to request that support would be implemented or at least evaluated for possible support.

##### ADDITIONAL INFORMATION

Amazon (Karoo) is very similar, if not a forked, to CentOS. It utilizes yum for the package management. Other then that, I have no other information about it.

May be the same as Amazon Linux 2

**Comment by ryanpetrello** [comment]
Hey @Stargator,

Thanks for the request - it's pretty unlikely that we'll support this as a supported platform for AWX in the near future due to the potential for additional maintenance burden.

**Comment by Stargator** [comment]
Again, I'm not familiar with Amazon Linux 2, but it seems to be a fork of CentOS or a very close cousin. I can't imagine it would add much of a burden. But okay.
