### ISSUE TITLE
Request additional description in API guide

### ISSUE THREAD

**Issue by ssamdwii** [ansible/awx#3015]
##### ISSUE TYPE
 - Feature Idea
(I'm sorry but I wanted to request the additional description in API guide but I don't choose a type for the guide.
So I register it as Feature Idea. 
Please let me know if you have to make a different type.)

##### COMPONENT NAME

 - API

##### SUMMARY

- There is no description of the parameter (paramater : dark)
Is it only an unreachable state?
Or can it include other state?

##### ADDITIONAL INFORMATION

- URL : https://docs.ansible.com/ansible-tower/latest/html/towerapi/api_ref.html#/Jobs/Jobs_jobs_job_host_summaries_list
- API : /api/v2/jobs/{id}/job_host_summaries/
- parameter : dark

**Comment by ryanpetrello** [comment]
Hey @ssamdwii,

I'm closing this, as it's not an issue with AWX itself, but Red Hat Ansible Tower's documentation.
