### ISSUE TITLE
Change body text  in e-mail sent by AWX

### ISSUE THREAD

**Issue by Ivheror** [ansible/awx#3016]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### ADDITIONAL INFORMATION

It would be nice to change the body message of notification zone in awx, by default it sends a JSON which if u had some password on it, someone is free to watch

**Comment by qjcg** [comment]
This looks like a dupe of #79.

**Comment by wenottingham** [comment]
Yes, closing.
