### ISSUE TITLE
Installer combined 2 instances into 1

### ISSUE THREAD

**Issue by AdrianDutu** [ansible/awx#3019]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
I am not sure if this issue is with the installer or something with something else, but looks like it.
 I have an environment with 2 awx hosts. 
The DB is external, it resides on the first node.
I want to have 2 hosts in the same instance group. In the inventory I added the 2 hosts under the tower group like so:
[tower]
host1
host2

Installation finished, migration done, I can access the UI on both nodes. When I look at the instances, I don't see the 2 instances I just installed, I see just one instance in the instance group, with the combined hardware resources of both nodes. Like so:

![instances](https://user-images.githubusercontent.com/4824201/51333534-3d68f180-1a7e-11e9-8247-74ab4dade7aa.PNG)

As you can see, there is just one instance with 8 CPUs. I actually have 2 machines with 2 CPUs each, so not even sure why there's 8 there instead of 4.

I added a GIT project. I checked inside the containers where were the files pulled. They were pulled only on one node. I stopped that node, opened the interface from the other one, triggered a project update. The job was queued and didn't start until I brought back online the node I stopped before.

##### ENVIRONMENT
* AWX version: 2.1.2
* AWX install method: docker compose with external postgres 9.6
* Ansible version:  2.6
* Operating System: CentOS 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Setup the external PostgreSQL, create the DB and awx user, modify pg_hba.conf file to accept connections
2. Modify the DB vars in the inventory file to match with the db instance previously installed
3. Add the 2 hosts under the [tower] group in the inventory
4. Run install.yml

##### EXPECTED RESULTS

1. See 2 instances in the instance group
2. Jobs get picked up by available instances

##### ACTUAL RESULTS

1. See 1 instance in the instance group with the combined hardware resources of the nodes 
2. Jobs are queued with 1 node up

**Comment by AdrianDutu** [comment]
Update: the CLUSTER_HOST_ID in /etc/tower/settings.py, inside the containers awx_web and awx_task, was set to 'awx' and i guess that's why it was seeing only one instance. 
I manually changed them and now i see 2 instances in the UI. Although the CPU count is still incorrect, it shows 8 (maybe it's 2x4 because it sees 2 CPUs for each container? that would be very silly though).
Anyway, the issue described still persists. If i start a project update, it works and pulls the playbooks on one node. If i stop this node, the jobs get queued. If i look at the instances in the UI now, the node that's still up shows some used capacity so somehow it looks like it tries to run something. But the jobs still show as queued. If i now bring up the node i stopped, it instantly shows as failed with the message "Task was marked as running in Tower but was not present in the job queue, so it has been marked as failed."

**Comment by matburt** [comment]
There isn't a `tower` group in the installer inventory and the docker compose installation method does not support installing an AWX cluster, that's only supported if you are installing on Kubernetes or Openshift. Are you sure you aren't using the Tower installer?

**Comment by AdrianDutu** [comment]
I am using the awx installer and I was following the tower instance group documentation since I didn't find any for awx. I managed to get awx_web and awx_task working in a cluster by fiddling with docker, so now I can see 2 instances in the UI. I found out later that this is not supported with docker. Theoretically, if I fiddle with the rabbitmq containers also and manage to get them join the same cluster, will the cluster work properly, or are there other things that I haven't consider that will break it? Just so I know if it's worth the time or if I need to consider k8s or openshift.

**Comment by matburt** [comment]
I'd probably suggest going the k8s/openshift route or it'll just fail to work at some point in the future if you want to upgrade.

When we make changes and consider upgrade paths we'll assume things are in-spec. You are certainly free to go it on your own but you should expect us to close issues or ask that you try our recommended install configuration.

**Comment by sujiar37** [comment]
@AdrianDutu, If you are planning to stick with specific version w/o upgrades / with rebuilds, there is a way we can enable cluster in AWX on Docker Install which I'd mentioned in the [AWX google groups thread](https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!msg/awx-project/E6mlcdfED2s/vprvoFH_AwAJ ), this is tested and working under the latest version 3.0.1. Also, I'm grateful and thankful to all the contributors in this whole AWX community.
