### ISSUE TITLE
Entering the proper value of a settings option does not clear the red color from the label

### ISSUE THREAD

**Issue by elyezer** [ansible/awx#3023]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Inputting an invalid value for any settings option will proper highlight the label in red and display a validation erro message. If a valid value is entered after the validation error only the validation error message will be cleared but the label will continue in red.
 
##### ENVIRONMENT
* AWX version: devel
* AWX install method: docker
* Ansible version:  X.Y.Z
* Operating System: Fedora 29 (Linux)
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Navigate to Settings > System (or any other settings page)
2. Input an invalid value for an option (for example an option that expects an integer and you input a string)
3. The validation error message will be displayed and the option's label will be colored to red.
4. Input a valid value for the option
5. Only the validation error message will be cleared, but the option's label will continue in red

##### EXPECTED RESULTS

The option's label color was back to its default color (without the validation error)

##### ACTUAL RESULTS

The option's label continue colored in red giving the impression that its option value still invalid.

**Comment by ryanpetrello** [comment]
@elyezer to your knowledge, is this still an issue in `devel`?

**Comment by elyezer** [comment]
@ryanpetrello I was stuck on another task and didn't had the time to check this until now. This still an issue in the latest devel, furthermore it is not providing the validation error message anymore. Following the steps to reproduce when trying to save a string as the value for the `Authorization Code Expiration` setting a 400 is being returned:

![Screenshot from 2019-06-24 12-08-41](https://user-images.githubusercontent.com/48132/60034519-d842a900-9678-11e9-9d8a-88db79870306.png)


The returned response body is:

```
{"OAUTH2_PROVIDER":{"AUTHORIZATION_CODE_EXPIRE_SECONDS":["A valid integer is required."]}}
```

So it seems UI is not handling that anymore. Since I can't proceed I can't confirm if the validation message is being cleared or not.

**Comment by nixocio** [comment]
Reopen if we see this behavior on the new UI.
