### ISSUE TITLE
After deleting a custom virtualenv, UI shows "Use Default Environment"

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#3029]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Deleted custom virtualenvs lead to jobs that error, with no good way to debug in the UI

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE
Create a virtualenv

create a JT that uses this virtualenv

delete the virtualenv

navigate to the JT

##### EXPECTED RESULTS

Some invalid notice

##### ACTUAL RESULTS

![screen shot 2019-01-18 at 3 23 16 pm](https://user-images.githubusercontent.com/1385596/51411310-67c9b600-1b35-11e9-9529-37a13fb62bd6.png)

The UI says the JT will use the default, but this is wrong. If you launch it, it will use the deleted one and will error.

**Comment by ryanpetrello** [comment]
It might be nice for the UI to detect this state by comparing the custom virtualenv defined on the JT, and if it's not in the list returned by the config endpoint, show an error and disallow save.
