### ISSUE TITLE
Failed to parse JSON string. Parser returned: Unexpected token ' in JSON at position 4 | Variations

### ISSUE THREAD

**Issue by TLMcNulty** [ansible/awx#3031]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
When adding an LDAP Group Type Parameter with other fields already defined you receive a JSON formatting error that seems to be well known with Angular. 

##### ENVIRONMENT
* AWX version: 2.1.2.0
* AWX install method: docker on linux
* Ansible version:  2.7.4
* Operating System: macOS 10.14.2
* Web Browser: Chrome Version 71.0.3578.98 (Official Build) (64-bit)

##### STEPS TO REPRODUCE

Fill out LDAP settings on LDAP authentication page. Fill in all boxes below minus LDAP User Search and LDAP Group Type Parameter. Click save. 

##### EXPECTED RESULTS

Save fails or succeeds.

##### ACTUAL RESULTS

You receive an error message.
![screen shot 2019-01-18 at 4 59 43 pm](https://user-images.githubusercontent.com/8993166/51415075-8bdfc400-1b42-11e9-87e6-c66768c13f66.png)

##### ADDITIONAL INFORMATION

None

**Comment by TLMcNulty** [comment]
Additionally if anyone is willing to help me set up LDAP I'd appreciate it. My schema is a bit complex.

**Comment by matburt** [comment]
That error typically means you are using single quotes instead of double quotes (required by json).

**Comment by TLMcNulty** [comment]
Any chance you guys can do anything about the single quotes in the official documentation?

https://docs.ansible.com/ansible-tower/latest/html/administration/ldap_auth.html
