### ISSUE TITLE
Error to Activate AWX Web Container

### ISSUE THREAD

**Issue by rfcoutinho** [ansible/awx#3033]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Attempted to try AWX running local and got error using default settings

##### ENVIRONMENT
* AWX version: 2.1.1
* AWX install method: docker for mac
* Ansible version:  ansible 2.8.0.dev0
* Operating System: MacOS 10.14.2
* Web Browser: Firefox Quantum

##### STEPS TO REPRODUCE

git clone https://github.com/ansible/awx.git
ansible-playbook -i inventory install.yml

##### EXPECTED RESULTS

All tasks completed and AWX running

##### ACTUAL RESULTS

TASK [local_docker : Activate AWX Web Container] ****************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Non-string value found for env option. Ambiguous env options must be wrapped in quotes to avoid YAML parsing. Key: DATABASE_PORT"}

**Comment by matburt** [comment]
What do you have defined for pg_port in your inventory file?

**Comment by rfcoutinho** [comment]
Hi @matburt 
I'm using all default inventory settings, which in this case is 
pg_port=5432

**Comment by rfcoutinho** [comment]
I was able to finally run it locally, had to edit the DATABASE_PORT settings on both tasks in
awx/installer/roles/local_docker/tasks/standalone.yml

#DATABASE_PORT: "{{ pg_port }}"
DATABASE_PORT: "5432"

Executed the playbook again and ran successfully

**Comment by matburt** [comment]
That would seem to suggest that pg_port was not defined in your inventory. I can't seem to reproduce this and we haven't heard it anywhere else so I'll close.

**Comment by ivanvolozhenin** [comment]
In inventory file in [all:vars] section 
pg_port: 5432 
I've change to **pg_port="5432"** , and this is resolve issue.
