### ISSUE TITLE
How do I update the current installation?

### ISSUE THREAD

**Issue by fortinj66** [ansible/awx#304]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME
 - Installer

##### SUMMARY
I've been able to successfully install and use AWX without too many issues.  However, I see bug fixes that need to be applied (especially UI fixes.)  How do I go about rebuilding AWX without blowing away the current environment.

I did try a git pull and install but had issues with the inventory file and awx_secret_key.  I was unable to use the system after the rebuild and had to start completely from scratch

##### ENVIRONMENT

Openshift 3.5

**Comment by matburt** [comment]
Remove the containers and re-install them. I just merged a change that adds official image support so no need to rebuild them: https://github.com/ansible/awx/blob/devel/INSTALL.md#official-vs-building-images
