### ISSUE TITLE
NPM & relaxed dependencies leading to regressions

### ISSUE THREAD

**Issue by mmallet-digipok** [ansible/awx#3043]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI
 - Installer

##### SUMMARY
Context: In the company I work for, I forked AWX and the latter is deployed in-house with custom deployment scripts (basically one additional playbook with vaults to hold our AWX servers credentials and certificates and an additional nginx front-end docker image with SSL configuration).

Upon a new AWX release (tag), the upstream is merged and new custom docker images are built.

In a reliable build factory, the assets produced at a given SHA1 must always be the same whenever they are rebuilt. Unfortunately, with the relaxed dependency management with npm, the AWX UI cannot be guaranteed to be the same.

For instance, in December, I built AWX 2.1.0 docker images. Using the same Git branch/sha1, when I rebuilt those images today, the npm components embedded in the UI aren't the same. If you try to rebuilt the AWX 2.1.0 today, you won't be able to create an inventory through the UI: after clicking on "+" button in the inventory page, the dropdown menu where the user is asked to pick-up either "Inventory" or "Smart Inventory" does not appear.

One could say "Why don't you deploy the latest version (2.1.2)?". The same problem stands as there is no guarantees that the npm dependencies remain the same between the time the official AWX images are built and the time when someone else build them. Moreover latest builds often introduce other regressions making an AWX update in production unsafe.

##### ENVIRONMENT
* AWX version: 2.1.0, 2.1.1 and 2.1.2 (but basically any version are impacted)
* AWX install method: docker on linux (standalone.yml)
* Ansible version:  2.7.x (untouched)
* Operating System: CentOS 7
* Web Browser: Firefox 64.0.2 x64 and Chrome 71.0 x64

##### STEPS TO REPRODUCE

Rebuild AWX 2.1.0 docker images and notice that some features in the UI are broken whereas they were working with official images built at the time of the AWX 2.1.0 release.

##### EXPECTED RESULTS

The npm UI dependencies used are the same.

##### ACTUAL RESULTS

The npm UI dependencies are not always the same.

**Comment by shanemcd** [comment]
Hi @mmallet-digipok. You are using an upstream project, which by nature moves quickly and is not guaranteed the same level of stability as a downstream product. I understand what you are saying and do not disagree on a fundamental level, but we are never going to lock ourselves down like this on our devel branch, which is what this repository is. We try our best to not break things between version bumps, but again, you are using an open source project that we provide for free.

**Comment by jakemcdermott** [comment]
@mmallet-digipok 
We don't recommend AWX for production.
