### ISSUE TITLE
Add Message Queue Option for Log Aggregator

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/awx#305]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
A client requested a log aggregator method using message queues such as rabbitmq to forward logs to an ELK DR setup. This is to transfer logs over another rabbit server which then forwards the logs to 2 ELK servers simultaneously in two separate DCs

##### ENVIRONMENT

* AWX version: 3.2

**Comment by gamuniz** [comment]
@jamesmarshall24 I feel like using rsyslog here meets the criteria, closing
