### ISSUE TITLE
AWX doesn't like parentheses in json payload when creating smart inventory

### ISSUE THREAD

**Issue by kefiras** [ansible/awx#3063]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 

##### SUMMARY
AWX sending internal server error when trying to create a smart inventory via API. 

Using curl to update the API:
`
curl -u user:password -ksXPOST https://host/api/v2/inventories/ -d @test -H "Content-Type: application/json"
`
with below payload:
`
{
"name": "Nonprod15",
"description": "Nonprod15",
"organization": 92,
"kind": "smart",
"host_filter": "groups__name=nonprod15-(nonprod15-a-1)master",
"variables": "",
"insights_credential": null
}
`

Getting the error:
`
{"host_filter":["Invalid query groups__name=nonprod15-(nonprod15-a-1)master"]}
`
##### ENVIRONMENT
* AWX version: 1.0.4.0
* AWX install method: docker on linux
* Ansible version:  2.4.0
* Operating System: OSX
* Web Browser: curl

##### STEPS TO REPRODUCE

Try to update the API as per description above

##### EXPECTED RESULTS

Expected to create smart inventory as per definition

##### ACTUAL RESULTS

Server error with error mentioned in the description

##### ADDITIONAL INFORMATION

I can create smart inventory with any other groups that doesn't contain parentheses.

**Comment by ryanpetrello** [comment]
I'm able to reproduce this:

![image](https://user-images.githubusercontent.com/214912/56829815-bffa0d80-6832-11e9-9213-46203caf189f.png)

![image](https://user-images.githubusercontent.com/214912/56829832-c6888500-6832-11e9-813c-ff3afe5d3fad.png)

**Comment by ryanpetrello** [comment]
@kefiras,

Does quoting the value like _this_ work for you?

`groups__name="nonprod15-(nonprod15-a-1)master"`

**Comment by gamuniz** [comment]
The use of smart inventories is deprecated in favor of using the work done in this PR:
https://github.com/ansible/awx/pull/13303

Constructed inventories
