### ISSUE TITLE
Reuse SCM Credentials as Environment Variable

### ISSUE THREAD

**Issue by hypery2k** [ansible/awx#3064]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME
 - API
##### SUMMARY
I'm trying to use in AWX defined credentials in a git command within my playbooks. I thought there's a way to use an environment var for that.

##### ENVIRONMENT
* AWX version: 2.1.2
* AWX install method: openshift
* Ansible version: 2.7.6
* Operating System: RHEL 7
* Web Browser: Latest Chrome

##### STEPS TO REPRODUCE
-

##### EXPECTED RESULTS

-

##### ACTUAL RESULTS

-

##### ADDITIONAL INFORMATION

-

**Comment by jakemcdermott** [comment]
Hello - thanks for making this issue. When you get a moment, would you please add some explicit steps to reproduce as well as expected results?

**Comment by hypery2k** [comment]
yes of course,

we have a playbook which inside executes via shell command a "git clone". So we would like to pass the existing AWX SCM credentials to this git clone command

**Comment by wenottingham** [comment]
See project_update.yml for how they are passed. Username/password are only passed for certain SCMs (not git). SSH keys are added to the key ring, so *may* work.

**Comment by hypery2k** [comment]
thanks for the hint, but can you point to the appropriate code sample?
Our current workaround is to create a custom credential type for this

**Comment by ryanpetrello** [comment]
This isn't a bug - if you need further assistance, please check out our Google Groups mailing list or the public IRC room on freenode (`#awx-devel`)
