### ISSUE TITLE
Debug Module running local instead of using SSH

### ISSUE THREAD

**Issue by glenpekarcsik** [ansible/awx#3069]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- Jobs

##### SUMMARY
I have a playbook that uses the CyberArk AIM Tool to fetch a password from the CyberArk Vault.  It runs fine when I run it locally.  When I run the playbook in AWX, AWX doesn't process the module correctly.  From CyberArk's documentation, they say to use the following module below in Ansible to use the AIM client to connect to CyberArk to retrieve information.  

 - name: getting creds from cyberark for "{{ cyberark_username }} on {{ ansible_hostname }}"
    debug:
      msg: "{{ item }}"
    with_cyberarkpassword:
      appid: "{{ cyberark_appid }}"
      query: "safe={{ cyberark_safe }};folder={{ cyberark_folder }};object={{ cyberark_username }}"
      output: "Password,PassProps.UserName,PassProps.Address,PasswordChangeInProcess"
    register: cyberark
    no_log: no

When AWX goes to process this module, I get the following error:

TASK [getting creds from cyberark for "{{ cyberark_username }} on {{ ansible_hostname }}"] ***
task path: /var/lib/awx/projects/_23__waf/playbooks/asm_f5_gather_facts.yml:66
fatal: [sdc01waftlta01x]: FAILED! => {
    "msg": "ERROR - AIM not installed or clipasswordsdk not in standard location. ERROR=(2) => No such file or directory "
}

AWX isn't using SSH to connect to the remote client that has the CyberArk AIM Client installed on it so the module can work properly.  

##### ENVIRONMENT
* AWX version: 1.0.8
* AWX install method: openshift,
* Ansible version:  2.6.4
* Operating System:  mac os
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Launch playbook in AWX and AWX processes the debug module as a local connection.

##### EXPECTED RESULTS

AWX should process the debug module as an SSH connection to the remote server.

##### ACTUAL RESULTS

AWX processed the debug module as a local connection and the module could not find the AIM client.

**Comment by wenottingham** [comment]
The Ansible debug module only ever runs on the control node. You'll have to debug your playbook in a different way.

**Comment by wenottingham** [comment]
Also note here: https://docs.ansible.com/ansible/latest/plugins/lookup.html?highlight=lookup#lookup-plugins

```
Like all templating, these plugins are evaluated on the Ansible control machine, not on the target/remote.
```
