### ISSUE TITLE
Support multiple LDAP configurations natively

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#307]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

We currently only support one LDAP 'configuration' in AWX configuration.

Django has the concept of multiple configurations here:
    http://django-auth-ldap.readthedocs.io/en/latest/multiconfig.html

The request is for AWX to support this framework natively (likely by allowing multiple LDAP 'configurations' that are then assembled into the above settings framework).

##### ADDITIONAL INFORMATION

This would need release noted such that "multiple configurations that contain the same users/groups may lead to undefined behavior".

An enhancement to this would automatically put each configuration into its own organization.

**Comment by chrismeyersfsu** [comment]
django-auth-ldap example on how to support multiple LDAP backends

 :(

```
class LDAPBackend1(LDAPBackend):
    settings_prefix = "AUTH_LDAP_1_"

class LDAPBackend2(LDAPBackend):
    settings_prefix = "AUTH_LDAP_2_"
```

**Comment by chrismeyersfsu** [comment]
The current plan is to extend the configure tower in tower settings to allow for a fixed number of LDAP backends.

**Comment by wenottingham** [comment]
@chrismeyersfsu @jakemcdermott can this be closed?

**Comment by wenottingham** [comment]
![screenshot from 2018-02-26 14-11-33](https://user-images.githubusercontent.com/5208768/36690000-03aeaf04-1aff-11e8-8f4b-34fdf6512191.png)

N/M, this landed.
