### ISSUE TITLE
Allowed job templates are grayed out on the Workflow Visualizer

### ISSUE THREAD

**Issue by saito-hideki** [ansible/awx#3073]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Allowed job templates are grayed out on the Workflow Visualizer when I tried to edit workflow.

##### ENVIRONMENT
* AWX version: 3.0.0 / Ansible Tower v3.4.0 and v3.4.1
* AWX install method: docker on linux
* Ansible version:  2.7.6
* Operating System: Red Hat Enterprise Linux Server release 7.5 (Maipo)
* Web Browser: Google Chrome 71.0.3578.98

##### STEPS TO REPRODUCE
You can follow the following steps to reproduce this problem:

1. Create `testuser`
1. Assign permissions to `testuser` as follows (USERS >  testuser >  PERMISSIONS)
  TYPE: Organization / ROLE: Workflow Admin
  TYPE: Job Template / ROLE: Execute
1. Login to Tower's dashboard as `testuser`
1. Create a workflow job template, then edit workflow using by Workflow Visualizer

You will see a grayed out job template even if you have `Execute` permission for this. Also you can choose this even if it is grayed out.

##### EXPECTED RESULTS
Allowed job templates are not grayed out, and users are able to choose it on Workflow Visualizer.

##### ACTUAL RESULTS
Allowed job templates are grayed out, but users are able to choose it on Workflow Visualizer.

##### ADDITIONAL INFORMATION
![wfjt](https://user-images.githubusercontent.com/7360578/51736722-2b1a3380-20ce-11e9-9196-6dca38bf3dd5.gif)

**Comment by mabashian** [comment]
Enabled/Disabled on the template row is controlled by `summary_fields.user_capabilities.edit` so as it's currently written I would expect the row to be disabled if the user adding/editing the wfjt does not have permissions to edit the job template.  @AlanCoding is that the appropriate behavior based on what the api is expecting?  We filter the templates list like so:

`/api/v2/unified_job_templates/?page_size=10&order_by=name&role_level=execute_role&type=workflow_job_template,job_template`

and then we use `summary_fields.user_capabilities.edit` as a boolean for enabling/disabling the row.

**Comment by AlanCoding** [comment]
I don't see how admin permission would be relevant here. I would expect that either:

 - templates list is filtered based on user execute role, and no items are greyed out
 - template list is not filtered, and items are greyed out that user does not have execute role for

Even if you're going to answer a survey, or provide prompts, you only need execute role to the JT or WFJT.

**Comment by fvzwieten** [comment]
I have experienced the exact same thing. v3.4.1

**Comment by razhaq** [comment]
I ma facing the issue while creating workflow. I am getting "You do not have permission to add a workflow job template." I have assign the required permission.

**Comment by AlanCoding** [comment]
> and then we use summary_fields.user_capabilities.edit as a boolean for enabling/disabling the row.

I think this might need to be switched to execute??

https://github.com/ansible/awx/blob/9fc1378fd17c6774d075e4e4888206185ad29cde/awx/ui/client/src/templates/workflows/edit-workflow/workflow-edit.controller.js#L286

Or, `can_edit` could always be set to true, because it's filtered anyway...

**Comment by unlikelyzero** [comment]
adding to retest in the new ui. This testcase does not exist

**Comment by unlikelyzero** [comment]
coverage in viz tests

**Comment by akus062381** [comment]
Manually checked, all good.
