### ISSUE TITLE
sidebar becomes incredibly long in mobile view after expanding a collapsed list.

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#3082]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
After expanding a collapsed list, if you make the screen narrow enough to make the sidebar go into a mobile view, it becomes incredibly long in length.

##### ENVIRONMENT
* AWX version: devel
* AWX install method: docker on linux
* Operating System: Fedora 29
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Expand a collapsed list, like a jobs list or templates.
2. Make your browser window narrow enough to trigger the mobile view (i.e. a toggle button to view the sidebar). 
3. Expand the sidebar if it is collapsed.

##### EXPECTED RESULTS
A normal length sidebar menu.

##### ACTUAL RESULTS

A very long sidebar menu (note the scrollbar)
![screenshot from 2019-01-28 15-01-33](https://user-images.githubusercontent.com/19942822/51817343-a3226c80-230d-11e9-921c-84f62a6f4573.png)

**Comment by kialam** [comment]
@dsesami I believe this bug exists on `devel` as well.

**Comment by dsesami** [comment]
sidebar verified to behave normally in mobile mode; no longer has strange spacing issues.
