### ISSUE TITLE
latyest pycurl 7.43 prevents from connecting to any RHV/ovirt job

### ISSUE THREAD

**Issue by natman** [ansible/awx#3083]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- embedded pycurl 7.43 and nss
- ovirt4.py

##### SUMMARY
- /opt/awx/embedded/lib64/python2.7/site-packages/pycurl-7.43.0.1 is not compiled with nss support and prevents ovirt ansible module from connecting to the ovirt/RHV engine API. 
- It also breaks ovirt4.py which is called by  the synchronization of the inventories with RHV credentials.

##### ENVIRONMENT
* AWX version: 2.1.2
* AWX install method: RPM with repo from wget -O /etc/yum.repos.d/ansible-awx.repo https://copr.fedorainfracloud.org/coprs/mrmeee/ansible-awx/repo/epel-7/mrmeee-ansible-awx-epel-7.repo
https://github.com/MrMEEE/awx-build/blob/master/installguide.md
* Ansible version:  2.7.4
* Operating System: centos 7.6
* Web Browser: firefox esr 60.4

##### STEPS TO REPRODUCE

When trying to add dynamic inventory from RHV, the job fails with this error:
...
ERROR! No inventory was parsed, please check your configuration and options.

It is like ovirt4.py couldn't generate the json exepcted file supposed to be read by ansible-inventory.

##### EXPECTED RESULTS

- inventory synchronization from RHV/ovirt is ok
- ovirt related playbooks successfully connects to the RHV API 

##### ACTUAL RESULTS

When trying to add dynamic inventory from RHV, the job fails with this error:
...
ERROR! No inventory was parsed, please check your configuration and options.

##### ADDITIONAL INFORMATION

I successfully tested the command manually with awx-manage:

sudo -u awx /opt/awx/bin/awx-manage inventory_import --inventory-name Infra --source ovirt_source

cat ovirt_source
#!/bin/bash
/var/lib/awx/venv/ovirt/bin/ansible-inventory -i ovirt4.py --list
so credentials and url are ok.
/opt/awx/embedded/lib64/python2.7/site-packages/ovirtsdk4 which is broken due to 7.43 pycurl embedded version.

Two ways for fixing it:

    1. pycurl 7.19 in a venv resolves the issue
    2. also in the venv, compiling 7.43 with nss support:
    export PYCURL_SSL_LIBRARY=nss; pip install pycurl --compile --no-cache-dir

Then, I rsynced the 7.43 pycurl  from venv to /opt/embedded to check if the issue was the same... and this time ovirtsdk4 worked!

So obviously, /opt/awx/embedded/lib64/python2.7/site-packages/pycurl-7.43.0.1 sould be compiled with the nss support,

**Comment by wenottingham** [comment]
```
So obviously, /opt/awx/embedded/lib64/python2.7/site-packages/pycurl-7.43.0.1 sould be compiled with the nss support
```

This is not the official distribution of AWX. You're best off reporting build-specific issues of that to the people who maintain that distribution.
