### ISSUE TITLE
RFE: Toggle to control displaying 'OK' task/host results in a task

### ISSUE THREAD

**Issue by cesarfn4** [ansible/awx#3084]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
It would be great, if it would be possible to control displaying 'ok' task/host results in a task (`display_ok_hosts`).

https://docs.ansible.com/ansible/latest/plugins/callback/counter_enabled.html

**Comment by shanemcd** [comment]
It looks like you can configure that via an ansible.cfg. The easiest way to do that is either baking it into the EE or dropping it into a Project.
