### ISSUE TITLE
Support Azure AD SAML multiple certificates

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#309]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY

Azure AD SAML uses multiple certificates at once when signing responses (https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-signing-key-rollover#other). This doesn't work with our SAML implementation.

**Comment by chrismeyersfsu** [comment]
Our Azure integration uses oauth2, not SAML. We will get support for M$ rotating certs for free when we upgrade to use the new python social auth

https://github.com/omab/python-social-auth/blob/master/MIGRATING_TO_SOCIAL.md
https://github.com/python-social-auth/social-core/blob/master/social_core/backends/azuread_tenant.py#L73

**Comment by chrismeyersfsu** [comment]
Test, you can manually invoke a key rollover by using scripts in https://github.com/AzureAD/azure-activedirectory-powershell-tokenkey
