### ISSUE TITLE
AWX and Python 2.5 Clients

### ISSUE THREAD

**Issue by bcochofel** [ansible/awx#3096]
Hi all,

I have some servers that have Python 2.5 and I cannot upgrade them.
Usually I can manage the configuration of these servers using ansible 2.3 but trying to run the same playbooks on AWX I cannot run them succefully.

How can I force AWX to use ansible 2.3? Or is there any other way to make this to work?

Thanks,
Bruno

**Comment by ryanpetrello** [comment]
@bcochofel awx will - by default - use the latest stable version of ansible available at install time.  If you want to use an older version, check out this documentation on creating a custom virtualenv.  You'll want to make a custom virtualenv, install ansible 2.3 into it, and assign it at the Job Template/Project/Organization level as appropriate:

https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md#managing-custom-python-dependencies
https://docs.ansible.com/ansible-tower/latest/html/upgrade-migration-guide/virtualenv.html#preparing-a-new-custom-virtualenv

**Comment by bcochofel** [comment]
> @bcochofel awx will - by default - use the latest stable version of ansible available at install time. If you want to use an older version, check out this documentation on creating a custom virtualenv. You'll want to make a custom virtualenv, install ansible 2.3 into it, and assign it at the Job Template/Project/Organization level as appropriate:
> 
> https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md#managing-custom-python-dependencies
> https://docs.ansible.com/ansible-tower/latest/html/upgrade-migration-guide/virtualenv.html#preparing-a-new-custom-virtualenv

Thanks ryanpetrello, I was trying to follow the instructions but couldn't find the way to defined the venv.
I've installed AWX using docker-compose and I can't find the path: /var/lib/awx/venv/

Thanks,
Bruno
