### ISSUE TITLE
Show all job's fields when the job is complete

### ISSUE THREAD

**Issue by elyezer** [ansible/awx#3105]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Not all fields are showing when the job completes while watching its progress. If the page is reloaded then all fields are shown.

##### ENVIRONMENT
* AWX version: devel
* AWX install method: docker on linux
* Ansible version:  2.7.5
* Operating System: Fedora 29
* Web Browser: Chrome 71.0.3578.98

##### STEPS TO REPRODUCE

1. Go to a completed job and relaunch it
2. Watch until the job is completed. (Don't change tab, since this may trigger a full reload)
3. Check all fields present on the details column.
4. Reload the page (F5)
5. Check all fields present on the details column. More will be displayed.

##### EXPECTED RESULTS

The same set of fields are displayed when the job is completed while watching the job and when refreshing the page.

##### ACTUAL RESULTS

The instance group and revision fields are missing when the job is completed while watching but they are shown when the page is reloaded.

##### ADDITIONAL INFORMATION
The screen shot below shows the fields when the job is completed while watching its progress:

![screenshot from 2019-01-30 10-32-57](https://user-images.githubusercontent.com/48132/51981703-0b429100-247b-11e9-8443-92637b1d4bf8.png)

But when reloading the page more fields are shown:

![screenshot from 2019-01-30 10-33-10](https://user-images.githubusercontent.com/48132/51981726-15fd2600-247b-11e9-85fe-4a8fa24a678d.png)

**Comment by jakemcdermott** [comment]
We don't want to poll the details endpoint with http requests, nor do we (generally) want to trigger http requests with websocket events. For this information to show up without a refresh, it should be delivered asynchronously over websockets. 

That said, we've added code to our status service to make the ui fetch again from the details endpoint at the "end" of a job - which is when the UI is able to tell that events are done processing on the server, which is most of the time. The relevant data in the http response is then extracted and processed as if it were a websocket event.

We can continue using this approach if there isn't a feasible way to deliver them over websockets.

**Comment by jakemcdermott** [comment]
My recommendation would be for us to take the UI-only approach if we want to see this functionality in the near future / 3.5 timeframe.

**Comment by jakemcdermott** [comment]
@elyezer and I talked about this offline - we're going to make this issue about delivering a targeted fix for this UI side and continue the API discussion in other github issues.

**Comment by ryanpetrello** [comment]
Addressed via https://github.com/ansible/awx/pull/3678

**Comment by unlikelyzero** [comment]
https://github.com/ansible/tower/issues/3304#issuecomment-483296189
