### ISSUE TITLE
stdout from job in browsable api is all messed up

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#3108]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API ?

##### SUMMARY

https://my.tower.com/api/v2/jobs/29/stdout/ displays garbage instead of the proper output.

![screenshot from 2019-01-30 11-48-21](https://user-images.githubusercontent.com/29239279/51997734-4cd83980-2485-11e9-9af0-adebad483c47.png)

##### ENVIRONMENT
* AWX version: devel
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Run a job with maxiumum vebosity
Attempt to look at stdout on browsable api

##### EXPECTED RESULTS

See the output
##### ACTUAL RESULTS

See some garbage

##### ADDITIONAL INFORMATION

The UI displays something readable that looks like this:
![screenshot from 2019-01-30 11-52-44](https://user-images.githubusercontent.com/29239279/51997864-958ff280-2485-11e9-92eb-b6f82a9d2a8b.png)

**Comment by ryanpetrello** [comment]
@kdelee you mind verifying this in `devel` and closing?

**Comment by mabashian** [comment]
fwiw the stdout looks good in the api browser for me at the head of devel

**Comment by kdelee** [comment]
LGTM!
![screenshot from 2019-02-12 16-48-36](https://user-images.githubusercontent.com/29239279/52670270-1c14ed00-2ee6-11e9-9c97-612ce0ba3faa.png)
