### ISSUE TITLE
all configuration changes lost after host restart

### ISSUE THREAD

**Issue by nordinrm** [ansible/awx#311]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY

after default installation (docker installation) everything is working fine but after the docker host restart
all changes are lost / whole awx system is set to default settings

##### ENVIRONMENT

* AWX version: 1.0.0.561
* Ansible version:  2.4.0.0
* Operating System: ubuntu server 16.04
* Web Browser: Chromium  Version 61.0.3163.79

##### STEPS TO REPRODUCE

After default install login to web gui, create a new team or new user or new organisation, restart docker host - after restart and logging in all changes are lost / system is at default state

##### EXPECTED RESULTS

we should be see the new team we added to configuration

##### ACTUAL RESULTS

there are no new teams / default config

**Comment by matburt** [comment]
Your /tmp directory is probably cleared at reboot, you can change where the installer chooses to set up the postgres data directory: https://github.com/ansible/awx/blob/devel/installer/inventory#L30
