### ISSUE TITLE
Openshift installer produces AWX container which runs as root

### ISSUE THREAD

**Issue by davidkirwan** [ansible/awx#3115]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

Once installed on Openshift, the installer produces the AWX container which runs as root and cannot run without adding `oc adm policy add-scc-to-user privileged -n ansible-tower -z awx`

##### ENVIRONMENT
* AWX version: latest on devel branch
* AWX install method: openshift
* Ansible version:  2.7.5
* Operating System: Openshift 3.11
* Web Browser: Firefox 64

##### STEPS TO REPRODUCE

Install AWX on openshift cluster where the user does not have cluster admin privileges

##### EXPECTED RESULTS

Run installer to completion, and have the pods come up without manual intervention

##### ACTUAL RESULTS

Installer runs to completion, but the pod refuses to come up as they run as root which is forbidden by default on openshift. It requires `oc adm policy add-scc-to-user privileged -n ansible-tower -z awx` permission to be added.

##### ADDITIONAL INFORMATION

```
create Pod awx-0 in StatefulSet awx failed error: pods "awx-0" is forbidden: unable to validate against any security context constraint: [spec.containers[1].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]
```

**Comment by matburt** [comment]
This is not running as root, that would require:
```
oadm policy add-scc-to-user anyuid -z default
```

Which we don't do.

This is from a running openshift:

```
sh-4.2$ whoami
awx
sh-4.2$ id
uid=1000(awx) gid=0(root) groups=0(root)
sh-4.2$ cat /etc/passwd
awx:x:1000:0:,,,:/var/lib/awx:/bin/bash
sh-4.2$ sudo
sudo: unknown user: root
```
