### ISSUE TITLE
Failed to log in: The username column in user_auth table is too short

### ISSUE THREAD

**Issue by towolf** [ansible/awx#312]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - DB Schema
 - UI

##### SUMMARY

We are using `givenname.surname@company.com` as a username in AWX LDAP config, and some of our people have relatively long names that make their email address go beyond 30 characters.

We could only let the people log in after doing this ALTER TABLE:

`ALTER TABLE auth_user ALTER COLUMN username TYPE character varying(100);`

My colleague who is managing the Enterprise Tower says that there must be yet another place in the codebase, where a length limit is in effect.

##### ENVIRONMENT

* awx-1.0.0.519
* Tower 3.1.4

##### STEPS TO REPRODUCE

Sign in to tower with a username longer than 30 characters. Here, we use LDAP sign-in with email.

**Comment by MarcoDotNet** [comment]
![screenshot from 2017-09-27 14-03-15 - 2677434](https://user-images.githubusercontent.com/10263250/30912408-a9e920f6-a38c-11e7-8822-5135805d4f3d.png)

**Comment by towolf** [comment]
So, that seems to come from this line:
`'username': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '30'})`

**Comment by wenottingham** [comment]
I think this may need to wait on django-1.11 for this. See https://docs.djangoproject.com/en/1.8/ref/contrib/auth/ (this field is 150 in Django 1.11).

**Comment by wenottingham** [comment]
See https://github.com/ansible/awx/issues/84 for django upgrade.

**Comment by towolf** [comment]
@wenottingham 

Thanks for the explanation and the path to how this will get fixed automatically (?). 

But nevertheless, should this issue not be kept open until the fix is actually in? This avoids dupes like we had on here already before.

**Comment by wenottingham** [comment]
We can... but there's nothing to do here until django upgrade comes in. Flagging appropriately.

**Comment by matburt** [comment]
I'm going to close this because the django upgrade hash appened. If this is still an issue let us know.
