### ISSUE TITLE
Add the descriptions of prompts being presented to users

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#3120]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
Customer request: When prompt on launch is selected, please add a description of the functionality of that prompt for users to easily know what they are inputting.

**Comment by wenottingham** [comment]
What prompted item are they unclear on the functionality of? (In a way where normal operation of AWX is more clear)

**Comment by msilmser** [comment]
This was specifically related to wanting a description of the limit field.

**Comment by wenottingham** [comment]
So migrating the tooltips from the JT display may be useful here.

**Comment by unlikelyzero** [comment]
@msilmser @keithjgrant  i'm not 100% sure what cases I should test for here. Can you confirm that this would suffice:

- JT Prompt Tooltips observe the correct Z-depth when Jobs launch on Templates Page and WFViz
- JT Prompt Tooltips are "correctly" rendered on FFox/ Chrome
- JT Prompt Tooltips are present on JTs and WFJTs Modal Prompts
- JT Prompt Tooltips appear when after navigating between tabs on the Modal
- JT Prompt Tooltips collapse after hoverover and quickly use the 'Next' button

**Comment by keithjgrant** [comment]
Those sound good to me

**Comment by unlikelyzero** [comment]
Tested the scenarios above and also:

- JT Prompts collapse before and after interacting with a Promptable dropdown element
