### ISSUE TITLE
enhance custom venv support to look in an alternate location

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#3126]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

Right now, custom venvs live in `/var/lib/awx/venv` alongside the system `awx` and `ansible` venvs.

When building a deployment that has multiple custom venvs, you need to:
- build them all into the container image
- volume mount each one individually in `/var/lib/awx/venv` (presumably, haven not tested)

It may be useful to have a specific, configurable, location to search for custom venvs. In this case, a deployment could have a specific volume/mount that contains all of their venvs.

Complication: the path-specific-ness of venvs may imply that the user's choice here affects how they build the venv. 

##### ADDITIONAL INFORMATION

UI mentioned merely because if this is a setting, it would need exposed in settings.

**Comment by ryanpetrello** [comment]
It would be ideal to expose this as a configurable setting e.g.,

```
settings.CUSTOM_VENV_PATHS = []
```

...and update our code to _also_ discover venvs in _those_ locations.  Things to consider:

1.  We'd want to be able to _set_ this programmatically via the API at `/api/v2/settings/all/`
2. The UI should show this setting and let you edit a configurable list (similar to how the `AWX_PROOT_SHOW_PATHS` proot whitelist works)

![image](https://user-images.githubusercontent.com/214912/53111404-fd78ac80-350a-11e9-9517-f4c49f72e44a.png)

3. Is there any special logic necessary for conflicts (what if two venvs in different locations have the same `name`?  Do our models store the _absolute_ path)?

**Comment by ryanpetrello** [comment]
@vismay-golwala have a look at https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md for details on how this feature works _today_

**Comment by vismay-golwala** [comment]
@ryanpetrello should we still keep ```BASE_VENV_PATH``` setting? If we are accumulating all the custom virtual environments from different directories, I was wondering if a base path is still necessary.

**Comment by ghost** [comment]
@ryanpetrello while adding paths using API, which of the following case would be appropriate to handle incorrect path:

1. Create a path with given name and then add it to settings.
2. Alert the user that the path doesn't exist and hence cannot be added.
3. Add anyways, but skip it while trying to fetch virtual environments from that directory. 

Also, should I be modifying the ```get_custom_venv_choices``` [function](https://github.com/ansible/awx/blob/devel/awx/main/utils/common.py#L941-L953) for this feature? I believe there are some tests associated with that function and was wondering if they should be updated as well?

**Comment by ryanpetrello** [comment]
I'd say validation here is probably two-fold.

The first pass of validation is _probably_ on the setting itself via some form of validator i.e., when user tries to *set* a value with a path that doesn't exist.

The second pass is probably when we actually call `get_custom_venv_choices`; we might want to have an `if not os.path.exists(custom_dir): logger.error(...)` so that users will see in the logs that they specified an invalid path.

**Comment by ghost** [comment]
Do we validate uniqueness of path while adding it through API?

**Comment by ryanpetrello** [comment]
@vismay-golwala yea, we _should_ probably check for duplicates in the user-provided list _at the time_ the setting is applied (e.g., `HTTP PATCH /api/v2/settings/system {'CUSTOM_VENV_PATHS': ['/opt/', '/opt/'])

**Comment by ghost** [comment]
@ryanpetrello what path do we take here in case of example above:

1. Ask user to enter valid directories only and throw an error.
2. Discard duplicate values and insert rest without any error

**Comment by ryanpetrello** [comment]
I'd say if they specify a value with duplicates, either is appropriate.  It might be easiest for the user to just silently filter out the duplicates.

**Comment by ghost** [comment]
Closing the issue in favor of https://github.com/ansible/awx/pull/3320

**Comment by kdelee** [comment]
:+1:
