### ISSUE TITLE
Python F5 SDK modules not found

### ISSUE THREAD

**Issue by HelixEvo** [ansible/awx#3128]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

I am getting the Python module F5SDK not found when trying to use code thats calling these modules.

- I have installed them and they are in /usr/lib/python3.6/site-packages/
- I have chmod them for global read access
- I have checked Python 3.6 is default

##### ENVIRONMENT
* AWX version: 3.0.0.0
* AWX install method: docker on CentOS 7
* Ansible version:  2.8.0 dev0 (Did not work on 2.7 either)
* Operating System: CentOS 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Run the job that contains the code

##### EXPECTED RESULTS

- New pool to be created
- Add nodes to the pool

##### ACTUAL RESULTS

TASK [Create a pool] ***********************************************************
fatal: [192.168.100.101]: FAILED! => {"changed": false, "msg": "The python f5-sdk module is required"}

**Comment by wenottingham** [comment]
Are you using a custom virtual environment? Ansible is still run with default system python.

**Comment by HelixEvo** [comment]
Hi.. Not custom.. I was using Python 2.7 and had the same issue, running 3.6 because I tried an upgrade to see if that helped... Same problem though.

**Comment by HelixEvo** [comment]
Hi.. Any thoughts on this one please?

**Comment by wenottingham** [comment]
You installed the library at the system level for python 3. You need to install it in the virtual environment used by Ansible, either the default one at /var/lib/awx/venv/ansible, or a custom one you use for that job/project.

**Comment by HelixEvo** [comment]
I have adjusted the inventory file to read:

localhost ansible_connection=local ansible_python_interpreter="/usr/lib/python3.6"

Still the same issue.. Do I need to restart any services for this now, or are you suggesting to use pip to install the SDK's into a different location. Using docker and AWX so not sure where else to put the SDK files.

Thanks..

**Comment by wenottingham** [comment]
> you suggesting to use pip to install the SDK's into a different location

^ This. You're really better off taking this to the awx-project mailing list or the #ansible-awx IRC channel, see https://github.com/ansible/awx/#get-involved.
