### ISSUE TITLE
Jobs history is not showing (web page freezes) - AWX 3.0.0

### ISSUE THREAD

**Issue by radanliska** [ansible/awx#3130]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
Web browser tab freezes after clicking on the history of some jobs at jobs menu.

##### ENVIRONMENT
* AWX version: 3.0.0
* AWX install method: openshift (Kubernetes)
* Ansible version:  2.7.6
* Operating System: Ubuntu Server 16.04.05 LTS
* Web Browser: Google Chrome 51.0.2704.63 m

##### STEPS TO REPRODUCE

When I click on Jobs and then select some job, there is a waiting icon with text: "working..." at the right bottom and after that all screen freezes (content of the web browser tab, not the whole browser). When I check the job history through API, everything is OK and I'm able to see jobs history without any problem. I think the problem is with UI not with the backend.

##### EXPECTED RESULTS

I expect to see jobs history as the same as in the previous versions.

**Comment by radanliska** [comment]
The same bug is in Firefox 45.7.0.

**Comment by jakemcdermott** [comment]
Hello,

Thanks for making this issue.

You'll need to update your Chrome or Firefox installation. The minimum Firefox version we fully support is 60.3 ESR. For Chrome, your version should be above 64.

If you have questions, please reach out to our community mailing list or join our irc channel on freenode (`#ansible-awx`)

**Comment by rbenabbas** [comment]
Hello, 
I had the same issue when I test with latest version of chrome, the problem fixed.
