### ISSUE TITLE
AWX kubernetes install ignores ca_trust_dir and project_data_dir

### ISSUE THREAD

**Issue by AdrianDutu** [ansible/awx#3134]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
I specified in the installer the ca_trust_dir and project_data_dir variables. 
project_data_dir=/opt/awx/projects
ca_trust_dir=/etc/pki/ca-trust/source/anchors

Below you can see the mounts from awx_web from one of the awx pods in k8s:

> docker inspect -f '{{ .Mounts }}' d30ab2c45da2
[{bind  /var/lib/kubelet/pods/81c9b5a3-2632-11e9-bb20-001dd8b736ad/etc-hosts /etc/hosts   true rprivate} {bind  /var/lib/kubelet/pods/81c9b5a3-2632-11e9-bb20-001dd8b736ad/containers/awx-web/ed8553e5 /dev/termination-log   true rprivate} {volume f0d4fe41a90cec79627ca30580e4f4687a317ac83e32f132ab14b2b5230987b6 /var/lib/docker/volumes/f0d4fe41a90cec79627ca30580e4f4687a317ac83e32f132ab14b2b5230987b6/_data /var/lib/nginx local  true } {bind  /var/lib/kubelet/pods/81c9b5a3-2632-11e9-bb20-001dd8b736ad/volumes/kubernetes.io~configmap/awx-application-config /etc/tower  ro false rprivate} {bind  /var/lib/kubelet/pods/81c9b5a3-2632-11e9-bb20-001dd8b736ad/volumes/kubernetes.io~secret/awx-confd /etc/tower/conf.d  ro false rprivate} {bind  /var/lib/kubelet/pods/81c9b5a3-2632-11e9-bb20-001dd8b736ad/volumes/kubernetes.io~secret/awx-token-q4zzk /var/run/secrets/kubernetes.io/serviceaccount  ro false rprivate}]

No mounts found for the directories I set. Nothing in kubernetes either. I need the ca_trus_dir for setting up ldap authentication. This was working in a docker installation.

##### ENVIRONMENT
* AWX version: 3.0, 2.1.2
* AWX install method: kubernetes
* Ansible version:   2.4.2.0
* Operating System: CentOS 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Install AWX on k8s. Specify the ca_trust_dir and project_data_dir in inventory.

##### EXPECTED RESULTS

Directories specified in the before mentioned variables be mounted inside the containers.

##### ACTUAL RESULTS

Directories are not mounted.

**Comment by Darkhan90** [comment]
Is anyone looking over the issues? I cannot use the tool if I can't set this up.
I tried to modify the installer/roles/kubernetes/templates/deployment.yml.j2 and add:

under volumes: 
- name: "ca-trust"
   hostPath: "/etc/pki/ca-trust/source/anchors"

Then under the awx-celery and awx-web containers, unde volumeMounts:
 - name: "ca-trust"
    mountPath: "/etc/pki/ca-trust"

The playbook fails at the Apply deployment step.

**Comment by AdrianDutu** [comment]
I managed to do this by manually editing the deployment yaml file and adding the mounts myself, but this is a major issue.

**Comment by anasypany** [comment]
@AdrianDutu Could you share what you modified in deployment.yml.j2 to get the trusted ca certs working? Currently experiencing the same requirement for ldap auth.

**Comment by AdrianDutu** [comment]
@anasypany my certificates are kept in /etc/pki/ca-trust/source/anchors on the host machines.
So in the deployment yaml i added a volume with this path:

```yaml
volumes:
        - name: "ca-trust"
          hostPath:
            path: "/etc/pki/ca-trust/source/anchors"
            type: "Directory"
```

Then I added a mount point to this volume in the awx_web container specs and mount it in the same path inside the container:

```yaml
volumeMounts:
            - name: "ca-trust"
              mountPath: "/etc/pki/ca-trust/source/anchors"
              readOnly: true
```

**Comment by tchellomello** [comment]
Hitting the same issue.

**Comment by tchellomello** [comment]
Hello guys, I've submitted the PR https://github.com/ansible/awx/pull/4116 that takes care of this problem. Thanks!
