### ISSUE TITLE
Smart Inventory Hosts tab doesn't redirect to related hosts list

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#3135]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
![broken inv host](https://user-images.githubusercontent.com/15881645/52134182-fbf54c00-2610-11e9-90e0-27bb9b1e737d.gif)

##### STEPS TO REPRODUCE
1) Create Smart Inventory
2) Add a Host
3) Click HOSTS tab

##### EXPECTED RESULTS
Page redirects to related host list

##### ACTUAL RESULTS
Page does not redirect.

**Comment by dsesami** [comment]
Verified that this redirects on both chrome and firefox correctly.
