### ISSUE TITLE
Interactive workflow

### ISSUE THREAD

**Issue by xwatav** [ansible/awx#3137]
##### Feature request

We would like to request interactive workflows.

 Our company's workflow would be to run a playbook in check mode with the --diff long-switch to show operators what would change in the configuration. Once the job finished, we would like to prompt the operator an inputfield (eg. survey) where they can opt whether to continue or not. The operator reviews changes, and if selects continue, the same jobtemplate is run in run mode, to commit changes.

The interactivity beats scheduling, as it needs human interaction. Our idea is to have two types of workflows: interactive(non-schedulable) and non-interactive(schedulable). These properties would be mutually exclusive.

##### COMPONENT NAME

 - awx/main/models ?
 - API
 - UI

##### SUMMARY
We would like to have interactive workflows for operators. The intention is the have breaks, more human control in automation.

##### ADDITIONAL INFORMATION

The graph below shows a possible scenario: the operator gives the answer to the chooser playbook which fails/succeeds and the appropriate playbooks runs: commiting or interrupting.

<pre>
                                                         __________________________
                                                        |                          |
                                                        | Job template on success  |
                                   prompt here         /|__________________________| 
 _______      ___________________  |  ____________    / 
|       |    |                   | | |            |  /
| Start |----| some job template |-+-| chooser.yml|-+
|_______|    |___________________|   |____________|  \
                                                      \  __________________________
                                                       \|                          |
                                                        | Job template on interrupt|
                                                        |__________________________|
</pre>              
This is just an idea, any implementation is welcome.

**Comment by wenottingham** [comment]
-> #1206
