### ISSUE TITLE
working locally but in AWX playbook is error

### ISSUE THREAD

**Issue by svrraja** [ansible/awx#3142]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 
 - UI
 

##### ENVIRONMENT
* AWX version:2.4.4.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.5.5
* Operating System:
* Web Browser:

##### ADDITIONAL INFORMATION

fatal: [abc.com]: FAILED! => {"changed": false, "command": "20 permit ip host 10.1.1.1 any log", "failed": true, "msg": "20 permit ip host 10.1.1.1 any log\\r\\n                    ^\\r\\n% Invalid input detected at '^' marker.\\r\\n\\r\\nabc(config)#", "rc": 1}

**Comment by ryanpetrello** [comment]
Can you share the playbook you're running?  We'll need some more context to help you troubleshoot.
