### ISSUE TITLE
Create Export Ability from AWX for Usage Statistics

### ISSUE THREAD

**Issue by hosurmadhan** [ansible/awx#3146]
##### ISSUE TYPE
Create Export Ability from AWX for Usage Statistics

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

 Ability to export from AWX for Usage Statistics. Is there any option to export data from AWX to any other source? Example: Export list of job's executed by a user to Excel or CSV.

##### ADDITIONAL INFORMATION

We see there is an option to view the usage, we need to if there is an option to export it.

**Comment by wenottingham** [comment]
This is not currently planned. You can perform queries against the REST API to return data in JSON format, which can then be massaged into the data format of your choice.

**Comment by hosurmadhan** [comment]
@wenottingham : Thanks for your feed back.
