### ISSUE TITLE
Graphical calendar widget for survey

### ISSUE THREAD

**Issue by mrmibrown** [ansible/awx#3149]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

A request for a graphical calendar widget for survey data fields.

**Comment by wenottingham** [comment]
... there's really not a datetime *type* for a variable, so there would likely need to be some definition around what this produces.

Assumption would be you get an extended, UTC, iso8601 datetime and that's it.

**Comment by wenottingham** [comment]
-> https://github.com/ansible/awx/issues/553
