### ISSUE TITLE
Document method to have awx_web bind only to localhost

### ISSUE THREAD

**Issue by alexander-bauer** [ansible/awx#315]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME
 - Installer

##### SUMMARY
I run AWX behind an NGINX reverse proxy, and have AWX itself bind to port 8052 on the host. Simply supplying `host_port: 8052` in the installer inventory causes Docker to bind to `0.0.0.0:8052`.

Instead, if I supply `host_port: 127.0.0.1:8052` in the inventory file, Docker binds only to localhost. This should be documented in the installation instructions.

##### ENVIRONMENT
* AWX version: 2.3.1

**Comment by kiranos** [comment]
hi just curios, do you use nginx for ssl termination? if so I agree there should be a install path with support for nginx or haproxy reverse proxy to support ssl termination. Perhaps x-forwarded-for support if awx uses the clients ip somewhere.

**Comment by alexander-bauer** [comment]
Hi @kiranos that's right; I use NGINX for SSL termination. I was successful in configuring (so far as I can tell) it by setting the client IP in `X-Forwarded-For` (as most commonly used in NGINX), then modifying the AWX System configuration field `Remote Host Headers` to contain `HTTP_X_FORWARDED_FOR`.

**Comment by ghost** [comment]
can we see your nginx configuration, I have mine setup but its lacking since auto refresh of the screen seems broken ? This is mine (not sure if this is the right place to paste it) 

```
server {
   listen 80;
   server_name    DN.FQ.TLD;
   return 301 https://$server_name$request_uri;
}


server {

    listen 443;
    server_name DN.FQ.TLD;

    ssl_certificate           /etc/ssl/certs/SSL_.pem;
    ssl_certificate_key       /etc/ssl/private/SSL_.key;

    ssl on;
    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_protocols TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;

    access_log            /var/log/nginx/awx.access.log;

    location / {

      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;

      # Fix the “It appears that your reverse proxy set up is broken" error.
      proxy_pass          http://127.0.0.1:8052;
      proxy_read_timeout  90;

      proxy_redirect      http://127.0.0.1:8052 https://DN.FQ.TLD;
    }
  }
```

**Comment by alexander-bauer** [comment]
@twotwenty I think this is solved by these options, which helps websockets behave.

```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
```

**Comment by markandrewj** [comment]
@alexander-bauer is correct, you need to use upgrade for websocket proxying.

[http://nginx.org/en/docs/http/websocket.html](http://nginx.org/en/docs/http/websocket.html)

I did it like this, which is pretty basic, but does work.

```
map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
}

server {
    listen 443;
    server_name www.awx.host.com awx.host.com;

        ssl on;
        ssl_certificate /etc/nginx/ssl/default-cert.pem;
        ssl_certificate_key /etc/nginx/ssl/default-key.pem;

    location / {
        proxy_pass http://127.0.0.1:7575;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```

**Comment by bedcruncher** [comment]
@alexander-bauer Thank you for posting this in your original problem. I was looking at how to lock the port down for the initial creation of the AWX instance. Thankfully using the '127.0.0.1:8052' for host_port has blocked it from external access.

**Comment by shanemcd** [comment]
This is no longer relevant after the move to https://github.com/ansible/awx-operator
