### ISSUE TITLE
Notifications tab missing on all templates/projects unless global system-admin

### ISSUE THREAD

**Issue by sharkcus** [ansible/awx#3150]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Regardless of how I set permissions for a user (org/project/template/etc...) the notifications tab for projects/templates is missing unless that person is a system-administrator

##### ENVIRONMENT
* AWX version: 3.0.0
* AWX install method: Openshift
* Ansible version:  Unsure. No longer says on awx "about" page.
* Operating System: rhel7
* Web Browser: chrome

##### STEPS TO REPRODUCE

Create project, template, org, inventory, and notification (and attach notification to org)
Assign user "admin" permissions to org, project, template, and inventory.
Edit template to enable notification

##### EXPECTED RESULTS

Navigate to template, click "notifications" tab and set accordingly.

##### ACTUAL RESULTS

The notification tab is missing, unless user is a global system-administrator

##### ADDITIONAL INFORMATION
I tried every combination of access I could on a test user account, I gave the user admin roles on everything I could (except actual system wide system-administrator account) and could not get that tab to pop up. I know there is an open issue for v1.0.8 but I'm not sure how much attention that will get because it's older.
![admin_user](https://user-images.githubusercontent.com/677450/52234284-4b48b000-288f-11e9-9e6d-3e6e7e041371.png)
![system-admin_user](https://user-images.githubusercontent.com/677450/52234285-4b48b000-288f-11e9-8857-e8be4ffe9f73.png)

**Comment by sharkcus** [comment]
Ticket from 2 major versions ago for reference:
https://github.com/ansible/awx/issues/2949

**Comment by wenottingham** [comment]
Yes, this should just be tracked in #2949.
