### ISSUE TITLE
RFE: Add grouping to the Job Template view

### ISSUE THREAD

**Issue by e-tienne** [ansible/awx#3151]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY
Grouping job templates together would be beneficial in providing an easier navigation of a set of job templates.
##### ADDITIONAL INFORMATION

This would be very useful for being able to group job templates by type so that if there were a function or set of functions (workflows) that needed to be executed they would be organized and located easier within the template view. It would be nice to be able to "group" templates together and be able to bring up the group under the search  page of the templates.

(Customer request)

**Comment by wenottingham** [comment]
-> #2058
