### ISSUE TITLE
Allow to start a template directly from the "edit" section.

### ISSUE THREAD

**Issue by Saurabh-Thakre** [ansible/awx#3153]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

  - UI
 
##### SUMMARY

Customer request : To start a job template faster it would be very helpful to start it directly in the "edit" section. Currently when pressing the "save" button you have to search for the template and then have to press "launch" there.

**Comment by wenottingham** [comment]
-> #1991
