### ISSUE TITLE
Host filters removing quotes on API calls

### ISSUE THREAD

**Issue by hluaces** [ansible/awx#3160]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

The creation process for hosts filters on a smart inventory incorrectly handles filters that query numeric variables (or any value that requires you to quote the filter, for that matter).

According to the [official documentation](https://docs.ansible.com/ansible-tower/latest/html/userguide/inventories.html#host-filter-search):

> If a search term in host_filter is of string type, to make the value a number (e.g. 2.66), or a JSON keyword (e.g. null, true or false) valid, add double quotations around the value to prevent Tower from mistakenly parsing it as a non-string:

The problem resides on the API call made by the UI, as it improperly encodes the request removing any quotes from the filter (detailed below) which ends up returning unwanted, or empty, values.

For example, if I were to create a host filter to query the release version such as `ansible_facts.ansible_lsb__major_release:"7"` the results on my inventory would be null because the generated XHR request would send a GET request against **\[1\]** when instead it should be pointed to **\[2\]** (please note the quotes and take into consideration that in this example the string is not url-encoded).

**[1]**: `/api/v2/hosts/?order_by=name&page_size=5&inventory__organization=2&host_filter=ansible_facts__ansible_lsb__major_release=7`

**[2]**: `/api/v2/hosts/?order_by=name&page_size=5&inventory__organization=2&host_filter=ansible_facts__ansible_lsb__major_release="7"`

##### ENVIRONMENT
* AWX version: 3.0.0.0
* AWX install method: docker
* Ansible version:  2.7.6
* Operating System: CentOS Linux release 7.2.1511
* Web Browser: 
  * Firefox v65.0
  * Google Chrome v71.0.3578.98
  * Opera 58.0.3135.53

##### STEPS TO REPRODUCE

Please note that in order to reproduce the issue you need a populated inventory with servers that have gathered facts. If possible, the `ansible_facts.ansible_lsb__major_release` fact would be needed to reproduce the issue.

- Access to `AWX → Inventory → Click the "plus" ("+") sign → Add new Smart Inventory`.
- Click on the lens next to the `Smart filter` section.
- Open your browser's network tab on its developer tools and set it to filter XHR calls.
- Add a new smart filter that queries a numeric value, such as `ansible_facts.ansible_lsb__major_release:"7"`.

##### EXPECTED RESULTS

I expect the query to return all servers that match the given criteria and the XHR call to be pointed to `/api/v2/hosts/?order_by=name&page_size=5&inventory__organization=2&host_filter=ansible_facts__ansible_lsb__major_release="7"` (note the quotes around the number 7).

##### ACTUAL RESULTS

The filter returns no matched servers. The XHR query is pointed to `/api/v2/hosts/?order_by=name&page_size=5&inventory__organization=2&host_filter=ansible_facts__ansible_lsb__major_release=7` (note the absence of quotes.

##### ADDITIONAL INFORMATION

Querying the API directly with the properly-formed URL returns the expected results.

This can be done via a GET request (f.ex.: with a browser) to the beforementioned URL.

**Comment by mabashian** [comment]
Should be fixed by #3608
