### ISSUE TITLE
Options layout not aligned properly

### ISSUE THREAD

**Issue by tvo318** [ansible/awx#3164]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Options in certain credential add screens have strange formatting.

##### ENVIRONMENT
* Tower version: 3.5.0, devel
* install method:  gce job template
* Ansible version:  2.7.6 
* Operating System: Mac OS Mohave 10.14.2 (18C54)
* Web Browser: Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

##### STEPS TO REPRODUCE
1. Create Credential (Add)
2. Set Credential Type to **Ansible Tower**
3. Look at Options field below (**Verify SSL** is bolded and misaligned)
4. Change the Credential Type to **Network** 
5. Look at Options field below (**Authorize** is bolded and misaligned)

##### EXPECTED RESULTS

The options field for Credential Type = Ansible Tower should line up with the checkbox and not be bolded.
The options for Credential Type = Network should line up with the checkbox and not be bolded.

##### ACTUAL RESULTS

Options field for both are bolded and misaligned

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/7514801/52300222-92dd4380-2944-11e9-88f7-6966d85a22b4.png)
>

![image](https://user-images.githubusercontent.com/7514801/52300260-aa1c3100-2944-11e9-9964-64ac46382e08.png)

**Comment by mabashian** [comment]
Fixed by #3217
