### ISSUE TITLE
Container's root filesystem size doesn't change after changing dockerd dm.basesize

### ISSUE THREAD

**Issue by mvineza** [ansible/awx#3169]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
We are running AWX via docker on a separate virtual machine. We tried resizing the host's `dm.basesize` (from 10GB to 50GB) in `/etc/docker/daemon.json` so that AWX's containers would not run out of space quickly under /.

After docker restart, the changes took effect on containers ran via `docker run <image>`. Their root filesystem size was increased to 50GB.

But when I recreate awx_task container via the ansible playbook that comes up with the installer, the container's root filesystem is still at 10GB. We did some modifications on the installer because we are just targeting awx_task for now and leaving the other containers running and untouched. Some of the modifications are putting ansible tags on the necessary tasks needed which are in `local_docker/tasks/main.yml`. Please also note that the installer version we are using is 1.0.2.335.

##### ENVIRONMENT
* AWX version: 1.0.2.335
* AWX install method: docker on linux
* Ansible version:  2.6.3
* Operating System: CentOS Linux release 7.3.1611 (Core)
* Web Browser: Google Chrome (any versions)

##### STEPS TO REPRODUCE

1. change dm.basesize in /etc/docker/daemon.json
```
{
    "insecure-registries" : ["host1:4567", "host2:8083"],
    "storage-driver": "devicemapper",
    "storage-opts": [
    "dm.thinpooldev=/dev/mapper/base-thinpool",
    "dm.use_deferred_removal=true",
    "dm.use_deferred_deletion=true",
    "dm.basesize=50GB"
    ]
}
```

2. restart docker daemon
`systemctl restart docker`

3. run installer
`ansible-playbook -i inventory install.yml --tags awx_task -e "pg_hostname=postgres awx_task_docker_actual_image=host2:8083/awx_task:1.0.0.561"`

4. check the container's filesystem size
`docker exec -it awx_task df -h /`

##### EXPECTED RESULTS

Container's root filesystem will be increased to 50 GB

##### ACTUAL RESULTS

Container's root filesystem is still at 10 GB

**Comment by ryanpetrello** [comment]
@shanemcd you have any ideas about this?

**Comment by gamuniz** [comment]
Closing this as we no longer support this type of deployment.
