### ISSUE TITLE
Passing environment variables from survey to dynamic inventories

### ISSUE THREAD

**Issue by akcrisp** [ansible/awx#3184]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
I want to be able to extract a list of hosts from a remedy ticket and use that list of hosts to generate a dynamic inventory. I can set the ticket number in the inventory sources enviroment variables but there appears to be no way to actually enter the cr number on a survey (they go in as extra vars) and have that passed through as an environment variable that could then be picked up by the python script.

Is this currently doable - if not can i request an ehancement to add it ?

I've tried doing as an enviroment variable
REMTICKET: "{{ CRNUMBER }}" but it iterally just uses {{ CRNUMBER }} 

CRNUMBER being set in survey and course they are extra vars.

I can't see that even trying to use a plugin would make any difference because I still need to get the ticket from the Survey into it.

**Comment by wenottingham** [comment]
This is not a thing that makes sense in AWX's inventory model - an inventory is a (more or less) stable thing that does not change based on job run parameters.

You'd be better off having an inventory script/plugin make groups populated from all ticket IDs and use vars/surveys to populate host patterns in the playbook.

**Comment by akcrisp** [comment]
Bill I thought of that but - that’s crazy slow - to retrieve literally thousands of remedy tickets and their contents would be massively slow and put unnecessary load on remedy server. You guys need to think about this.
