### ISSUE TITLE
Vertical Scroll bar is more likely to be displayed now that we have additional data on the Job Result Details view

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#3195]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Now that we've added another codemirror field to the Job Results details page, users are more likely to see a vertical scroll bar as a means to view all of the information about a job result.

Note: this mainly affects windows users and all firefox ESR users as those browsers display the scrollbars at all times -- not just when the scroll event is being triggered.

##### ENVIRONMENT
* AWX version: 3.0.3
* Operating System: MacOS, Windows
* Web Browser: Firefox, and sort Chrome

##### STEPS TO REPRODUCE

1. Open up the job result details page when artifacts are attached to a job in a browser with a vertical resolution < 1000.

##### EXPECTED RESULTS

No scroll bar necessary to view all information

##### ACTUAL RESULTS

Vertical scroll in the center of the screen

##### ADDITIONAL INFORMATION

<img width="1422" alt="image 2019-02-08 at 4 14 20 pm" src="https://user-images.githubusercontent.com/12446869/52506491-c0342680-2bbc-11e9-9c0e-d8bf31dee990.png">

**Comment by mabashian** [comment]
> users are more likely to see a horizontal scroll bar

Do you mean vertical scroll bar here?

The only thing that comes to mind to address this would be to allow the output panel (on the right) to grow either a) as tall as the page or b) as tall as the details panel (on the right) - whichever one is taller.  That would avoid the scrollbar on the details panel but it would mean that the whole page would scroll.  I'm not really sure which of those options is better.

**Comment by unlikelyzero** [comment]
> Do you mean vertical scroll bar here?

Yes, sorry.
