### ISSUE TITLE
VERISON 3.0.1 for awx_web docker image not found

### ISSUE THREAD

**Issue by Bourne-ID** [ansible/awx#3199]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY
docker image ansible/awx_web:3.0.1 not found

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method:docker on linux
* Ansible version:  2.7.7
* Operating System: Ubuntu 16.04
* Web Browser: N/A

##### STEPS TO REPRODUCE

Follow the installation instructions for docker-compose (ansible-playbook -i inventory install.yml)

##### EXPECTED RESULTS

To install successfully

##### ACTUAL RESULTS

Error during playbook run:

TASK [local_docker : Start the containers] **************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "errors": [], "module_stderr": "", "module_stdout": "", "msg": "Error starting project 404 Client Error: Not Found (\"manifest for ansible/awx_web:3.0.1 not found\")"}

##### ADDITIONAL INFORMATION

Seems the docker image Ansible Web 3.0.1 doesn't exist following the release of 3.0.1 - reference: 
https://hub.docker.com/r/ansible/awx_web/tags

**Comment by fredgate** [comment]
Same error today that did not happen last week :-(

**Comment by fredgate** [comment]
File `installer/roles/local_docker/defaults/main.yml` defines version of `awx_web` image as
```yaml
dockerhub_version: "{{ lookup('file', playbook_dir + '/../VERSION') }}"
```
And recent commit 63e3e733e015faff3f9683eab097b8a67f10e555 changed the file `VERSION` from `3.0.0` to `3.0.1`. But in the docker hub, there is no image tagged as `3.0.1`. So install playbook now fails :-(

**Comment by benapetr** [comment]
definitely broken

**Comment by jakemcdermott** [comment]
Hello,

Thanks for creating this issue. We published the new image this morning, so I think this should now be resolved.
