### ISSUE TITLE
Job Schedules unexpected redirect on edit cancel

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#320]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- UI

##### SUMMARY
Clicking the `X` when editing a Schedule from the Jobs->Schedules tab takes me to a list view of all the schedules for that job associated with the schedule; instead I expect to be taking back to the list of all scheduled jobs.

##### ENVIRONMENT
* AWX version: 1.0.0

##### STEPS TO REPRODUCE

* Create a few schedules for a job
* Go to Jobs and click the schedules tab
* Click on Edit for one of the schedules you created
* Click the `X` for that edit

##### EXPECTED RESULTS

* To be taken back to the Jobs -> Schedules list

##### ACTUAL RESULTS

* Taken to the list of schedules for that particular job

**Comment by jaredevantabor** [comment]
fixed in devel now
