### ISSUE TITLE
changed": false, "cmd": "apt-get update", "msg": "[Errno 2] No such file or directory", "rc": 2}

### ISSUE THREAD

**Issue by nandeeshb09** [ansible/awx#3204]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY
try to run in localhost using awx in ubuntu machine alaways get this message no such file or directory.

changed": false, "cmd": "apt-get update", "msg": "[Errno 2] No such file or directory", "rc": 2}

##### ENVIRONMENT
* AWX version: 3.0.0.0 
* AWX install method: docker on linux(ubuntu)
* Ansible version: 2.7.6
* Operating System: ubuntu 18.04
* Web Browser: chrome

##### STEPS TO REPRODUCE

Tried to install lamp stack using awx through ansible playbook,from last 3 days im getting this same error.

please help me on this ,im stuck at this.

##### EXPECTED RESULTS

It should install packages from apt module ,but its not happening.

##### ACTUAL RESULTS

fatal: [localhost]: FAILED! => {"changed": false, "cmd": "apt-get update", "msg": "[Errno 2] No such file or directory", "rc": 2}

##### ADDITIONAL INFORMATION
Identity added: /tmp/awx_170_v16asb5k/credential_3 (/tmp/awx_170_v16asb5k/credential_3)
PLAY [localhost] ***************************************************************
TASK [Gathering Facts] *********************************************************
ok: [localhost]
TASK [install lamp stack] ******************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "apt-get update", "msg": "[Errno 2] No such file or directory", "rc": 2}
PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1

**Comment by wenottingham** [comment]
This isn't an issue with the AWX installer (there's no LAMP stack involved there), this seems to be a general playbook error. You're better off checking the awx-project mailing list.

**Comment by nandeeshb09** [comment]
Thanks Wen,
I know its not issue with installation.But its not working from awx ui.
 Its working in local, but not working from AWX ui.? if i try to run any playbook,its giving the same error in ubuntu machine.

**Comment by Fiasee** [comment]
where you able to resolve?

**Comment by rajeshpeta** [comment]
i am also facing the same issue can you help me plase

**Comment by rajeshpeta** [comment]
> awx-project mailing list

Hello @nandeeshb09 Were you able to fix this

**Comment by rajeshpeta** [comment]
> where you able to resolve?

Any resolution you found for this

**Comment by ovitente** [comment]
I am receiving the same error on mac os Catalina BUT under virtual env.
ansible 2.9.11
```
TASK [common : Initial System Upgrade] ******************************************************************************************************************************************************************************
task path: /Users/det/x7/projects/x7/Atlas/x7deployer/roles/common/tasks/main-list.yaml:2
Using module file /Users/det/x7/projects/x7/Atlas/x7deployer/env/lib/python3.8/site-packages/ansible/modules/packaging/os/apt.py
Pipelining is enabled.
<10.10.0.3> ESTABLISH LOCAL CONNECTION FOR USER: det
<10.10.0.3> EXEC /bin/sh -c 'sudo -H -S -n  -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-vwzuiwoejfazdwknjodbtqqmossxrgbe ; /usr/bin/python'"'"' && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_apt_payload_iGAQky/ansible_apt_payload.zip/ansible/module_utils/basic.py", line 2588, in run_command
    cmd = subprocess.Popen(args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
[WARNING]: Updating cache and auto-installing missing dependency: python-apt
fatal: [b3]: FAILED! => {
    "changed": false,
    "cmd": "apt-get update",
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false,
            "autoclean": false,
            "autoremove": false,
            "cache_valid_time": 0,
            "deb": null,
            "default_release": null,
            "dpkg_options": "force-confdef,force-confold",
            "force": false,
            "force_apt_get": false,
            "install_recommends": false,
            "only_upgrade": false,
            "package": null,
            "policy_rc_d": null,
            "purge": false,
            "state": "present",
            "update_cache": true,
            "upgrade": "full"
        }
    },
    "msg": "[Errno 2] No such file or directory",
    "rc": 2
}

PLAY RECAP **********************************************************************************************************************************************************************************************************
b3                         : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```

Playbook that fails

```
  - name: Initial System Upgrade
    tags: [main-list, sysupgrade]
    apt:
      update_cache: yes
      install_recommends: no
      upgrade: full
```
And the same with other blocks that are using the `apt` module.

**Comment by ovitente** [comment]
In my case SOLUTION found. I opened my eyes wide and saw that I have an uncommented option  `connection: local` in my playbook.

Ansible was trying to search `apt-get` command on the mac os.

**Comment by PratikKhandelwal17** [comment]
I'm testing my ansible playbook on local, and it is giving me the error mentioned in the issue.
Ansible tasks:
1. Create a new ec2 instance and ssh into it
2. Run apt-get on the instance

I've used the following command to run the ansible playbook: 
`ansible-playbook --connection=local sparkmaster.yml`

For the solution mentioned above, If I remove the --connection=local, then I get a new error:
`"msg": "Failed to connect to the host via ssh: ssh: connect to host (ip) port (port): Operation timed out"`

Any idea on how to solve this?

**Comment by ffirg** [comment]
Please raise such issues using the google mailing list for support. This is not a support forum. Thank you.

**Comment by yatish1992** [comment]
[WARNING]: Updating cache and auto-installing missing dependency: python-apt
fatal: [172.31.92.240]: FAILED! => {"changed": false, "cmd": "apt-get update", "msg": "[Errno 2] No such file or directory", "rc": 2}

i am also facing the same problem can you please give me any solution

**Comment by ovitente** [comment]
@yatish1992 
@PratikKhandelwal17 
and others,

Please don't reanimate years-old issues, use Ansible support telegram channel to solve your support-requests
https://t.me/pro_ansible

**Comment by shanemcd** [comment]
Note that the link above is not affiliated with Red Hat or Ansible.
