### ISSUE TITLE
Job Event processing results in unexpected query when specific smart inventory query used

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#3205]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Unexpected smart inventory query appears when smart inventory query with 3 or more `and` used for ansible facts. For a system with a large smart inventory this results in slow job event processing.

##### ENVIRONMENT
* Tower 3.4.1

##### STEPS TO REPRODUCE

For slowness of job event processing:
* Create an inventory with at least 3,000 hosts
* Create 60 smart inventories that matches a fraction of those hosts, say 300.
* use a host_filter with at least 3 and's ie. `ansible_facts__ansible_distribution=CentOS and ansible_facts__ansible_distribution=CentOS and ansible_facts__ansible_distribution=CentOS`
* Run a playbook against any of the smart inventories.

##### EXPECTED RESULTS

* Shortly after ansible job finishes, stdout shows in the UI

##### ACTUAL RESULTS

* job events take a _long_ time to be processed (> 500 ms per event). This is observable in the UI/API

##### ADDITIONAL INFORMATION

https://gist.github.com/chrismeyersfsu/f0a5e6109cc134a533c7e9d0b2ba5cb4 <-- can be used to log all queries issued in tower along with a stack trace.

`SELECT "main_host"."id", "main_host"."created", "main_host"."modified", "main_host"."description", "main_host"."created_by_id", "main_host"."modified_by_id", "main_host"."name", "main_host"."inventory_id", "main_host"."enabled", "main_host"."instance_id", "main_host"."variables", "main_host"."last_job_id", "main_host"."last_job_host_summary_id", "main_host"."has_active_failures", "main_host"."has_inventory_sources", "main_host"."ansible_facts", "main_host"."ansible_facts_modified", "main_host"."insights_system_id" FROM "main_host" WHERE ("main_host"."ansible_facts" @> '{"ansible_local": {"ansible_distribution": "CentOS"}' AND "main_host"."ansible_facts" @> '{"ansible_local": {"ansible_distribution": "CentOS"}}') ORDER BY "main_host"."name" ASC` <-- This is the offending query. We should NOT generate a query of this type if things are working correctly.

**Comment by kdelee** [comment]
Going to close this as @one-t confirms it works for him
