### ISSUE TITLE
Pop out host_vars 

### ISSUE THREAD

**Issue by ahuffman** [ansible/awx#3209]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

It's extremely difficult to view host_vars in an inventory if you have more than 4-5 set.  It would be nice if there was a button to pop-out the host_vars from an inventory similar to how you can pop-out extra_vars on a job log pane.

**Comment by vismay-golwala** [comment]
@ahuffman is this the pop-out you are referring to? 

![Pop-out SS](https://user-images.githubusercontent.com/15652962/52593641-709d6700-2e17-11e9-8430-fa1c232ff6d3.png)

**Comment by wenottingham** [comment]
This is akin to #1268... presumably a similar implementation could work.

**Comment by mabashian** [comment]
@ahuffman When you say host_vars I want to make sure I understand exactly what you mean.  Are you referring to the extra vars on the host form?

<img width="1539" alt="Screen Shot 2019-03-13 at 4 39 44 PM" src="https://user-images.githubusercontent.com/9889020/54312987-a9636400-45ae-11e9-9e32-70e57f801eb3.png">

@wenottingham I think this same feature would be _really_ useful for host facts which can be lengthy and difficult to scroll through.  It might not be too much of a stretch for us to add expand/collapse to _most_ of our extra variables.  Is that something that we should consider here?

**Comment by wenottingham** [comment]
Yeah, I wonder how many of our codemirror implementations this could apply to.

I could argue for the host case, it almost makes sense to expand *down* and collapse the list that's under the host display... but that's not really something we do.

**Comment by ahuffman** [comment]
@mabashian yes, that's what I'm referring to.  It would definitely be useful on the facts tab as well, pretty much the same situation.

**Comment by unlikelyzero** [comment]
@ahuffman can you give me an example of the size/type of input you'd like to see? I'm testing this now

**Comment by ahuffman** [comment]
@unlikelyzero in some cases I have 10,000+ lines in that view, same for the fact view.  I need to be able to pop that window to full screen or similar to see the data more intuitively.  Right now I literally ctrl+a and ctrl+c the data and paste to a text editor so I can actually see it. 

Imagine having something similar to a full `ansible_facts` dump in there and how hard that would be to view in the current window.  Anything will work as long as I can see more than 10 lines of text at a time.  

Collapsible buttons on dicts in that field would be sweet if you could pull that off as well, but if it's too much work, no big deal.  Thanks!

**Comment by unlikelyzero** [comment]
@ahuffman I just tested it with 10k lines. One more question. Do you usually use json or yaml

**Comment by ahuffman** [comment]
yaml usually

**Comment by unlikelyzero** [comment]
Verified:

- 10k lines
- Add new line in expanded view.  Appears on collapsed view and can be saved.
- Copypasta 10k lines in expanded view
- Delete new line in expanded view. Appears on collapsed view and can be saved.
- YAML/JSON toggle works on expanded view 
- error validation sorta works on json mode https://github.com/ansible/awx/issues/3638
- error validation works on yaml mode https://github.com/ansible/awx/issues/3639

**Comment by unlikelyzero** [comment]
@dsesami once https://github.com/ansible/awx/issues/3639 is closed, we can close this ticket
