### ISSUE TITLE
Dashboard 'Job Status' dropdown wonkiness

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#3210]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Dashboard 'Job Status' dropdowns persist once selected. This is visually jarring, but they continue to function as intended. In addition, once a Dashboard dropdown has been interacted with and the user resizes the browser, the dropdown selects will realign to the menu sidebar. At this point, they will overlap and it becomes impossible to make a selection without refresh.

##### ENVIRONMENT
* AWX version: 3.0.2
* Operating System: macOS
* Web Browser: Firefox ESR, chrome:latest

##### STEPS TO REPRODUCE
1. Navigate to the Dashboard
2. Select a dropdown option from the Job Status timeseries display
Note: dropdown list persists
3. Select a second dropdown option from the Job Status timeseries display
Note: both dropdown lists persist
4. Resize the browser
Note: both dropdown lists have realigned to the top left

##### EXPECTED RESULTS

1. Dropdown lists to collapse after a selection is made

##### ACTUAL RESULTS

1. Dropdown lists persist after a selection is made
2. Dropdown lists realign after a browser resize

##### ADDITIONAL INFORMATION

![dashboard](https://user-images.githubusercontent.com/12446869/52600160-b9115080-2e28-11e9-8854-31377ffac8f3.gif)

**Comment by mabashian** [comment]
Fixed by ansible/awx#3363
