### ISSUE TITLE
Cloud region list should be sorted

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#322]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

![screenshot from 2017-09-28 14-41-25](https://user-images.githubusercontent.com/5208768/30984403-3986e62a-a45b-11e7-9d34-01d26eb9753e.png)

*How* to sort it might be worth discussion (US first? Alphabetically?), but the current unsorted is odd.

##### ENVIRONMENT
* AWX version: currentish

##### STEPS TO REPRODUCE

Go to Inventory Source, select AWS, select region dropdown.

**Comment by matburt** [comment]
Implemented in #1544
