### ISSUE TITLE
Field "limit" for job template or ad_hoc command cannot be empty

### ISSUE THREAD

**Issue by krentiken** [ansible/awx#3223]
##### ISSUE TYPE
Field "limit" for job template or ad_hoc command cannot be empty

##### COMPONENT NAME
 - UI

##### SUMMARY
If the "limit" field is empty, then job template or ad_hoc command execute on all inventory servers.
It is necessary to make so that if the field is empty, then job template or ad_hoc command is NOT execute. We execute job template (ad_hoc command) on a large number of servers,  so if the "limit" field is empty (forgot to fill), this can lead to the launch of the task on all servers.

##### ADDITIONAL INFORMATION
<img src="https://cdn1.radikalno.ru/uploads/2019/2/13/7aa2275401e5077650c14cbba6d841cc-full.jpg">

**Comment by jakemcdermott** [comment]
Hello. Thanks for creating this issue.

Changing job templates in this way would make `limit` behave in a fundamentally different way from how it does in ansible core, which is not something we want to do.

The scenario you described is in alignment with regular ansible behavior: When running `ansible-playbook`, for example, _not_ specifying a limit would result in ansible considering all hosts in the provided inventory as potential targets to run tasks against.

If you'd like your job template to _not_ run against any hosts if the user forgets to provide a value for the `limit` prompt, you can try setting the default value of `limit` to `!all`.

Please join our irc channel on freenode (#ansible-awx) or reach out to our community mailing list if you additional questions. Thanks!
