### ISSUE TITLE
The "run commands" button in "ad_hoc" commands must be ACTIVE if no hosts or group is selected.

### ISSUE THREAD

**Issue by krentiken** [ansible/awx#3224]
##### ISSUE TYPE

The "run commands" button in "ad_hoc" commands must be ACTIVE if no hosts or group is selected.

##### COMPONENT NAME

 - UI

##### SUMMARY

Often we need to "copy-paste" the hosts list from cmdb to the "limit" field to run commands. It would be very good that the "run commands" button was active, even if no hosts (groups) was selected from the list.

##### ADDITIONAL INFORMATION
<img src="https://cdn1.radikalno.ru/uploads/2019/2/13/b7a2f1b2f6b74f437639b44cce6f7dae-full.jpg">

**Comment by krentiken** [comment]
I think it's not a good idea to make an "active" button "run commands". It would be nice if we could upload a list of hosts file in the format of .txt , .csv or another... and executing commands

**Comment by wenottingham** [comment]
That will not be added; the point is to work on the inventory defined in Tower.

**Comment by mabashian** [comment]
I'm fine with enabling the button regardless of whether or not any hosts/groups have been selected.  Those checkboxes are really just a convenience to automatically fill the `limit` field.  Clicking the button without selecting anything first would just require the user to manually input a limit if one is desired.  I think this would mean that the button is always enabled.  If that's the case, should we consider hiding that button when the inventory contains no hosts?

**Comment by AlexSCorey** [comment]
@krent84 the run commands buttons is now active in ui_next even if no hosts have been selected. is fixed in ui_next

**Comment by nixocio** [comment]
Reopen if we see this behavior on the new UI.
