### ISSUE TITLE
job_status logger doesn't exist; remove it from the docs

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#3226]
https://github.com/ansible/product-docs/blame/91b1e17f4b4bd4bacfabaa22791803699b9dfc52/administration/source/logging.rst <-- Introduced the notion of `job_status` but that logger doesn't actually exist (and never did exist in code). We should remove `job_status` from the tower docs and from the awx/docs https://github.com/ansible/awx/blob/devel/docs/logging_integration.md

**Comment by tvo318** [comment]
Oops, I mistakenly closed this when it's not even mine to close.

**Comment by ryanpetrello** [comment]
Closing this, as it's just a minor to-do and now it's to-_done_.
