### ISSUE TITLE
VMware vcenter_inventory: max_object_level gt 1

### ISSUE THREAD

**Issue by Gankarloo** [ansible/awx#3231]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI
 

##### SUMMARY
VMware vcenter inventory fails if **max_object_level** is greater than 1

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: docker on linux
* Ansible version:  2.7.7
* Operating System: Oracle Linux 7
* Web Browser:

##### STEPS TO REPRODUCE

Create a new inventory source of type "VMware vCenter"
In SOURCE VARIABLES add only
`max_object_level: 2`

##### EXPECTED RESULTS

Successful run of inventory sync

##### ACTUAL RESULTS

Sync fails with
_[WARNING]: Unable to parse /var/lib/awx/venv/awx/lib64/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py as an inventory source_

##### ADDITIONAL INFORMATION

Full output from jobs view

>     2.141 INFO     Updating inventory 2: vcenter
>     2.154 DEBUG    Using base command: /usr/bin/ansible-inventory -i /var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py
>     2.154 INFO     Reading Ansible inventory source: /var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py
>     2.157 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
>     2.157 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
>     2.157 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python2.7/site-packages:
>   Traceback (most recent call last):
>   File "/var/lib/awx/venv/awx/bin/awx-manage", line 11, in <module>
>     load_entry_point('awx==3.0.1', 'console_scripts', 'awx-manage')()
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 140, in manage
>     execute_from_command_line(sys.argv)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line utility.execute()
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv self.execute(*args, **cmd_options)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 330, in execute
>     output = self.handle(*args, **options)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1049, in handle
>     raise exc
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 949, in handle
>     data = AnsibleInventoryLoader(source=source, is_custom=self.is_custom, venv_path=venv_path).load()
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 195, in load
>     return self.command_to_json(base_args + ['--list'])
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 178, in command_to_json
>     self.method, proc.returncode, stdout, stderr))
> RuntimeError: ansible-inventory failed (rc=1) with stdout:
> stderr:
>  [WARNING]:  * Failed to parse /var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py with script plugin:
> Inventory script (/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py) had an execution error:
> Traceback (most recent call last):   File
> "/var/lib/awx/venv/awx/lib64/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 779, in <module>
> print(VMWareInventory().show())   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py", line 145, in
> __init__     self.do_api_calls_update_cache()   File
> "/var/lib/awx/venv/awx/lib64/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 184, in
> do_api_calls_update_cache     self.inventory =
> self.instances_to_inventory(self.get_instances())   File
> "/var/lib/awx/venv/awx/lib64/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 507, in
> instances_to_inventory     keylist = map(lambda x: x.strip(),
> tv['value'].split(',')) AttributeError: 'dict' object has no attribute 'split'
>  [WARNING]: Unable to parse /var/lib/awx/venv/awx/lib64/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py as an inventory source
> ERROR! No inventory was parsed, please check your configuration and options.

I have successfully run this manually from within the awx_tasks docker container by first copying the generated config file during a sync from /tmp/awx_xxx_xxxxxx to /tmp/vmware.ini

and using it with this commandline.
`VMWARE_INI_PATH=/tmp/vmware.ini /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py --list`

Reason for upping the max_object_level is that I use the option groupby_custom_field but that information is not obtained with a max_object_level of 1. 

I have also tried getting the latest version of vmware_inventory.py from ansible project and replacing the one in awx_tasks continer. but same result.

**Comment by wenottingham** [comment]
- for the vmware inventory script, this would need fixed in upstream Ansible first, and then brought into AWX
- *in general*, we are undertaking a move to inventory plugins. See https://github.com/ansible/awx/issues/171

**Comment by Gankarloo** [comment]
But there is nothing wrong with the script.
It's only when used via awx the problem shows. 

As a workaround I uploaded it as a inventory script and it works as expected.

**Comment by wenottingham** [comment]
Sorry, I missed that - just saw the bit about using latest upstream under AWX not working.

**Comment by AlanCoding** [comment]
> I have successfully run this manually from within the awx_tasks docker container by first copying the generated config file during a sync from /tmp/awx_xxx_xxxxxx to /tmp/vmware.ini

> and using it with this commandline.
`VMWARE_INI_PATH=/tmp/vmware.ini /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py --list`

This will run the import with your config file, yes, but it means that you will lose your authentication-related environment variables, which include:

https://github.com/ansible/awx/blob/5682fb15034960521f3e57a6c8e74b176c74a67d/awx/main/models/credential/injectors.py#L55-L59

You can check that the update used these in via `/api/v2/jobs/N/` under the `job_env`. Updates require this related credential, so it probably used these.

I'm unclear on exactly what content it is going to be providing you if you run it on the CLI without authentication information. If you replicated the inventory update environment, I would expect that it will give the same error, which, yes, would probably be a bug with the script.

**Comment by gamuniz** [comment]
Closing this as we reworked inventories to use plugins instead of scripts.
