### ISSUE TITLE
Document how to monitor both stdout and status through AWX API

### ISSUE THREAD

**Issue by EdCampion** [ansible/awx#3237]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME

 - API

##### SUMMARY

I am trying to monitor a job through the awx api. To accomplish this I (every 500ms)
get the job status from jobs/{jobId}/
call jobs/{jobId}/stdout?format=json
Once both calls complete, I inspect job.failed, if true I output the message from stdout in red, else green.
Problem: A situation occurs where job.failed is false and job.status is 'running', but the stdout contains an error. This error is output in green as a status update.

As the job is 'running' it is polled again. And this time job.failed will be true.
Is there any way to synchronize stdout and job status?

##### ENVIRONMENT
* AWX version: 2.1.2
* AWX install method: unknown
* Ansible version:  unknown
* Operating System: Windows 10
* Web Browser: Chrome

AWX environment is not owned by me, so am unsure of these details.

##### STEPS TO REPRODUCE

As in summary
##### EXPECTED RESULTS

Can fetch stdout and status at the same time.

**Comment by ryanpetrello** [comment]
Ed,

Your approach _will work_, but polling the API over HTTP is always going to be a suboptimal way to approach this.  The AWX web interface _itself_ actually uses websockets to receive _push_ messages about new stdout and status changes for a job.  If you want better results, I'd recommend checking out this document:

https://github.com/ansible/awx/blob/devel/docs/websockets.md

...and using a library like:  https://pypi.org/project/websocket-client/  (assuming you're using Python)

For your needs, you'll want to use `https://your-awx.example.org/websocket` to "subscribe" to the groups you care about:

https://github.com/ansible/awx/blob/devel/docs/websockets.md#protocol

Specifically, you probably want something like this:

```js
'groups': {
        'jobs': ['status_changed', 'summary'],    // <---- sends you notifications when any 
                                                  // job's status _changes_, or when the
                                                  // job has a summary (i.e., it finished 
                                                  // running and has playbook stats)
        'job_events': [12345]  // <--- where 12345 is some Job ID
}
```

**Comment by atsai1220** [comment]
Could I get some more clarification on this please?

I am able to receive a HTTP 101 response from my websocket by pointing my Python app to `wss://my-awx.com/websocket` but I am not receiving either `accept: true` or `accept: false` when I try to subscribe to a job.

My workflow is as follows. First I receive a token from `/api/v2/tokens/` then I use this `headers = { 'Authorization': 'Bearer' + auth_token }` and use it as part of my header when I create my connection. At least this is what I gather from this documentation (https://github.com/ansible/awx/blob/devel/docs/websockets.md#protocol)
> You must provide a valid Auth Token in the request URL.

This is from my Python app
```
--- request header ---
GET /websocket HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: my-awx.com
Origin: http://awx.marina.viasat.io
Sec-WebSocket-Key: abcdefghijklmnopqwstuvwxyz
Sec-WebSocket-Version: 13
Authorization: Bearer abcdefghijklmnopqwstuvwxyz 

-----------------------
--- response header ---
HTTP/1.1 101 Switching Protocols
Server: openresty/1.15.8.1
Date: Thu, 19 Dec 2019 17:24:28 GMT
Connection: upgrade
Upgrade: WebSocket
Sec-WebSocket-Accept: abcdefghijklmnopqwstuvwxyz
Strict-Transport-Security: max-age=15724800; includeSubDomains
-----------------------
```

**Comment by atsai1220** [comment]
Could I get some more clarification on this please?

I am able to receive a HTTP 101 response from my websocket by pointing my Python app to `wss://my-awx.com/websocket` but I am not receiving either `accept: true` or `accept: false` when I try to subscribe to a job.

My workflow is as follows. First I receive a token from `/api/v2/tokens/` then I use this `headers = { 'Authorization': 'Bearer' + auth_token }` and use it as part of my header when I create my connection. At least this is what I gather from this documentation (https://github.com/ansible/awx/blob/devel/docs/websockets.md#protocol)
> You must provide a valid Auth Token in the request URL.

This is from my Python app
```
--- request header ---
GET /websocket HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: my-awx.com
Origin: http://my-awx.com
Sec-WebSocket-Key: abcdefghijklmnopqwstuvwxyz
Sec-WebSocket-Version: 13
Authorization: Bearer abcdefghijklmnopqwstuvwxyz 

-----------------------
--- response header ---
HTTP/1.1 101 Switching Protocols
Server: openresty/1.15.8.1
Date: Thu, 19 Dec 2019 17:24:28 GMT
Connection: upgrade
Upgrade: WebSocket
Sec-WebSocket-Accept: abcdefghijklmnopqwstuvwxyz
Strict-Transport-Security: max-age=15724800; includeSubDomains
-----------------------
```

**Comment by ryanpetrello** [comment]
@atsai1220,

We recently added a new official CLI to AWX, and it includes some underlying libraries (namely, `awxkit`) which could probably be used to accomplish what you're looking for:

https://github.com/ansible/awx/tree/devel/awxkit/awxkit/cli/docs

Here's some pseudocode which is probably close to what you want:

```python
from awxkit.api.client import Connection
from awxkit import WSClient

hostname = 'awx.example.org'
user = 'example'
pw = 'secret'

connection = Connection(f'https://{hostname}:443')
connection.get('/api/')
connection.login(user, pw, next='/')
client = WSClient(
    hostname=hostname,
    session_id=connection.session_id,
    csrftoken=connection.session.cookies.get('csrftoken'),
)
client.connect()
client.status_changes()

while True:
    for r in iter(client):
        print(r)
```

**Comment by atsai1220** [comment]
@ryanpetrello Thank you for reaching back!

I was able to connect to my instance but I am receiving 403 as a result when I try to login. My `connection.session_id` is None.

```python
from awxkit.api.client import Connection
from awxkit import WSClient

connection = Connection(f'https://{hostname}:443')  
connection.get('/api/')  
connection.login(username, password, next='/')  
client = WSClient(  
     hostname=hostname,  
     session_id=connection.session_id,  
     csrftoken=connection.session.cookies.get('csrftoken'),  
 )  
 client.connect()  
 client.job_details(832)  
 print(connection.session.cookies.items()) 
 for r in iter(client):  
          print('hi' + r) 
```

These are my debug messages. It seems I am receiving a 403 but I can successfully login from my browser with the same credentials. I am also able to receive a token from `/api/v2/tokens/` by posting with basic auth.

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): awx.marina.viasat.io:443
DEBUG:urllib3.connectionpool:https://awx.marina.viasat.io:443 "GET /api/ HTTP/1.1" 200 None
DEBUG:awxkit.api.client:"GET https://awx.marina.viasat.io:443/api/" elapsed: 0:00:01.428109
DEBUG:urllib3.connectionpool:https://awx.marina.viasat.io:443 "POST /api/login/ HTTP/1.1" 403 None <---------
DEBUG:awxkit.api.client:"POST https://awx.marina.viasat.io:443/api/login/" elapsed: 0:00:00.319181
DEBUG:awxkit.ws:successfully sent {"groups": {"jobs": ["status_changed", "summary"], "job_events": [832]}, "xrftoken": "123123123123123123123123123"}
```

This is from `pprint(vars(connection))`
```
{ 'server': 'https://awx.marina.viasat.io:443',
  'session': <requests.sessions.Session object at 0x1035028d0>,
  'session_id': None,
  'uses_session_cookie': True,
  'verify': False}
```

Thank you in advance and happy holidays!

**Comment by atsai1220** [comment]
@ryanpetrello Thank you for reaching back!

I was able to connect to my instance but I am receiving 403 as a result when I try to login. My `connection.session_id` is None.

```python
from awxkit.api.client import Connection
from awxkit import WSClient

connection = Connection(f'https://{hostname}:443')  
connection.get('/api/')  
connection.login(username, password, next='/')  
client = WSClient(  
     hostname=hostname,  
     session_id=connection.session_id,  
     csrftoken=connection.session.cookies.get('csrftoken'),  
 )  
 client.connect()  
 client.job_details(832)  
 print(connection.session.cookies.items()) 
 for r in iter(client):  
          print('hi' + r) 
```

These are my debug messages. It seems I am receiving a 403 but I can successfully login from my browser with the same credentials. I am also able to receive a token from `/api/v2/tokens/` by posting with basic auth.

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): awx.xxx:443
DEBUG:urllib3.connectionpool:https://awx.xxx443 "GET /api/ HTTP/1.1" 200 None
DEBUG:awxkit.api.client:"GET https://awx.xxx:443/api/" elapsed: 0:00:01.428109
DEBUG:urllib3.connectionpool:https://awx.xxx:443 "POST /api/login/ HTTP/1.1" 403 None <---------
DEBUG:awxkit.api.client:"POST https://awx.xxx:443/api/login/" elapsed: 0:00:00.319181
DEBUG:awxkit.ws:successfully sent {"groups": {"jobs": ["status_changed", "summary"], "job_events": [832]}, "xrftoken": "123123123123123123123123123"}
```

This is from `pprint(vars(connection))`
```
{ 'server': 'https://awx.xxx:443',
  'session': <requests.sessions.Session object at 0x1035028d0>,
  'session_id': None,
  'uses_session_cookie': True,
  'verify': False}
```

Thank you in advance and happy holidays!

**Comment by ryanpetrello** [comment]
Hey @atsai1220,

It'll probably just require a little tinkering.  What's the return value of `connection.login(username, password, next='/') ` ?

**Comment by AmoVanB** [comment]
Just a note for those that would be encountering the same issue.

The `/api/login` POST call returns a 403 because the CSRF check fails. The reason for that is that the server checks the `Origin` header sent by the client, and `https://{hostname}:443` is not a trusted origin. 

Simply using 
```
connection = Connection(f'https://{hostname}')  
```

does the trick.
