### ISSUE TITLE
Add information ( like firstname and lastname ) on users team list

### ISSUE THREAD

**Issue by grimlokason** [ansible/awx#3238]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
Being able to know who is behind the "username" while reading the list of user in a team like when we add an user in a team.

##### ADDITIONAL INFORMATION

The UI to change : ![user groups list](https://docs.ansible.com/ansible-tower/3.2.2/html/userguide/_images/teams-users-list.png)
exemple of url to acces that menu on a server :  https://awx_fqdn/#/teams/1/users/add-user?team_search

It could be interesting to be able to get firstname and lastname like here : ![user groups list](https://docs.ansible.com/ansible-tower/3.2.2/html/userguide/_images/teams-add-users-for-example-team-selected.png)

Best regards.

**Comment by wenottingham** [comment]
Would a tooltip be appropriate here?

**Comment by grimlokason** [comment]
Hello,

It could be a quick work around to know who is who, but we won't be able to sort by first name/last name.
