### ISSUE TITLE
The play book install.yml gives error

### ISSUE THREAD

**Issue by Sunithapnair** [ansible/awx#324]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

The play book install.yml gives an error during run.

##### STEPS TO REPRODUCE#######################

#/etc/ansible/awx-devel/installer# ansible-playbook -vvv -i inventory install.yml
Using /etc/ansible/ansible.cfg as config file
ERROR! 'name' is not a valid attribute for a Block

The error appears to have been in '/etc/ansible/awx-devel/installer/openshift/tasks/main.yml': line 24, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Get docker registry password from oc if needed
  ^ here

**Comment by LukeShortCloud** [comment]
According to the [Blocks documentation](http://docs.ansible.com/ansible/latest/playbooks_blocks.html), the "name" attribute was added as a new feature in Ansible 2.3. What Ansible version are you using? Could you try re-testing with 2.3 and/or 2.4?

**Comment by matburt** [comment]
closing, use latest ansible.
