### ISSUE TITLE
Root user inside containers

### ISSUE THREAD

**Issue by AdrianDutu** [ansible/awx#3251]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - Installer

##### SUMMARY
Currently, there is no root user inside the containers, or sudo rights given to the awx user. 
This could be added as an optional step via an installer variable but I would prefer having it by default.

##### ADDITIONAL INFORMATION

I'm actually surprised this is not available. I have a lot of files that ansible use from /etc. I cannot add or modify the files without root privileges. One classic example would be a vault file residing in /etc/ansible.

**Comment by wenottingham** [comment]
We recommend for cases like this where you want to do management of the system running AWX itself, that you connect via ssh (or similar) mechanisms as some non-awx user and then sudo; using sudo directly from a `connection: local` playbook has inherent security issues.

**Comment by AdrianDutu** [comment]
@wenottingham That makes no sense. I don't think you understood what i mean. I'm not talking about managing anything from AWX. I'm talking about loging in to awx-celery or awx-web with a user capable of doing sudo or root (docker exec -u root -it awx_celery /bin/bash). The only user in passwd is awx and it has no sudo privileges.

**Comment by kdelee** [comment]
@Darkhan90 try this if you want to modify things in root space
```
docker exec --user=0 -it <name_of_container> bash
```

**Comment by kdelee** [comment]
For some more background, AFAIK this has been a rub since there were changes to help us get running on zuul

Now if you want to do things like, say, install anything in `/venv/awx` you need to shell in like this: `docker exec --user=0 -it <name_of_container> bash`. I left a comment on the issue. You are effectively root but there is no root user I guess? :waves hands:

```
$ docker exec --user=0 -it tools_awx_1 bash
bash-4.2# whoami
whoami: cannot find name for user ID 0
# no user named "root" but I can still do this now and will be able to write to root space -->
bash-4.2# source /venv/my_custom_venv/bin/activate 
bash-4.2# pip install <my_favorite_package>
```

**Comment by ryanpetrello** [comment]
What @kdelee said - if you want root for arbitrary commands, use `docker exec -u0`

If you want your playbooks to use something not available to the `awx` user, then make them available to the `awx` user.

**Comment by jpic** [comment]
Do we really still need venv in containers? As long as we're running non
root, isn't it fine to happily pollute the systèm level package space
during build time given that the images are supposed to be immutable ?

Confirming entering the container with --user root and having the container
locked into non root is the best practice (see docker security manual)

**Comment by kdelee** [comment]
> Do we really still need venv in containers? As long as we're running non root, isn't it fine to happily pollute the systèm level package space during build time given that the images are supposed to be immutable ?

Well that is a whole other can of worms. If you are really passionate about it I'd make a separate RFE. 

Seeing as the `awx` venv and the ansible execution environment are often different I think you'd have quite a few speedbumps to overcome if you wanted to ditch venvs. :man_shrugging:

**Comment by jpic** [comment]
Thanks for your enlightening reply, isolation between two distinct Python
products encapsulated by a single image does make sense, unless at some
point you plan to import the Python API of one into the other, in that case
both the products will have to do the effort of following upstream updates
of common dependencies (which is a good practice to have anyway).
Passionate enough to naively ask what refutation would come up against the
practice I like yes, but I'm sure I'll find a more valuable subject to be
passionate about and try to contribute to awx and learn from your
experience. Have a great day !
