### ISSUE TITLE
likely bootstrap upgrade issue: JT with allow provisioning callback/host config key set causes console error on load

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#3255]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
JT with allow provisioning callback/host config key set causes console error on load.  This is probably due to bootstrap upgrade based on the nature of the console error message

##### ENVIRONMENT
* AWX version: devel

##### STEPS TO REPRODUCE

Save JT when provision callback checkbox under options and a host config key is set (using the auto generating button works)

##### EXPECTED RESULTS

not have a console error

##### ACTUAL RESULTS

![screen shot 2019-02-18 at 4 58 28 pm](https://user-images.githubusercontent.com/1342624/52978615-0ef17580-33a0-11e9-8c64-cef98f5b6703.png)

**Comment by unlikelyzero** [comment]
@jlmitch5 is this ready for a `needs_test` label?

**Comment by ryanpetrello** [comment]
Addressed by https://github.com/ansible/awx/pull/3376
