### ISSUE TITLE
Workflow display for running job is not using most of screen space

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#3258]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: docker
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Just open any running workflow - you will see that workflow visualisation is going to be extremely small vertically, only fixed pixels in height. Most of screen space is not utilized, and workflows that have many paralel jobs can't be easily displayed, unless you zoom out like crazy.

<img width="1474" alt="image" src="https://user-images.githubusercontent.com/1560121/53018108-c7c3bd00-3451-11e9-8057-a0b50ea98823.png">

**Comment by benapetr** [comment]
Here is what I think should expand in the view, right now it's really hard to see whole diagram:
![image](https://user-images.githubusercontent.com/1560121/53168489-033dc300-35db-11e9-9c21-9ec37c9c59a8.png)

**Comment by Dagon-** [comment]
Seeing the same thing across multiple browsers (vivaldi, firefox, chrome) and systems after update to 3.0.1 from 2.x.
