### ISSUE TITLE
Compact list breaks My View page on small resolution (1200x800)

### ISSUE THREAD

**Issue by elyezer** [ansible/awx#3263]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

The compact list does not render properly the _My View_ page on a 1200x800 resolution. See the additional information section for the screenshot.

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: docker on linux
* Ansible version:  2.6
* Operating System: Linux
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Create a Job Template with a long name
2. Run the created job template
3. Check the _My View_ page

##### EXPECTED RESULTS

Either the row height or the columns on the compact view should adjust better to properly show the UI elements.

##### ACTUAL RESULTS

Some elements are not shown entirely (see the screenshot)

##### ADDITIONAL INFORMATION

![relaunch-a-job-from-the-all-jobs-list_failed_feb-19-2019-173037-gmt 0000](https://user-images.githubusercontent.com/48132/53036320-491d4e80-3456-11e9-81f7-16bb95776e0b.png)

**Comment by unlikelyzero** [comment]
Elements are now properly rendered
