### ISSUE TITLE
Feature: update to Angular UI Router v. 1.0 

### ISSUE THREAD

**Issue by jaredevantabor** [ansible/awx#327]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
UI

##### SUMMARY

We're currently on angular-ui-router v.1.0.0-beta.3,

We should move to the current major release, 1.0

This probably involves fixing a large variety of minor (or major) things, perhaps even ripping out the state-generator that has plagued us for some time. 

##### ADDITIONAL INFORMATION

Angular UI Router v. 1.0 will provide more flexibility, given that we also want to upgrade to Angular JS v. 1.6, and that we are moving towards a component architecture that many people in the community have embraced. With Angular UI Router 1.0, you can route directly to a component, whereas in the past you always needed to leverage a controller + template paradigm. 

https://ui-router.github.io/guide/ng1/migrate-to-1_0

**Comment by wenottingham** [comment]
@jaredevantabor this can be closed, right?

**Comment by jaredevantabor** [comment]
Absolutely
