### ISSUE TITLE
shell module not finding paths inside awx containers

### ISSUE THREAD

**Issue by AdrianDutu** [ansible/awx#3273]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI
 - Installer

##### SUMMARY
I have a few playbooks that are using the shell module and the chdir argument. The paths I give to this argument are not recognised. These paths are inside the awx_celery container.

One simple play example:

`- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Import inventory
      shell: "awx-manage inventory_import --source=hosts --inventory-id=4 --overwrite"
      args:
        chdir: /var/lib/awx/shared`

Running this from AWX, i get:

> TASK [Import inventory] ********************************************************
task path: /var/lib/awx/projects/_14__awx/plays/awx-inventory-sync.yml:12
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: awx
<127.0.0.1> EXEC /bin/sh -c 'echo ~awx && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1550681868.78-72577694193075 `" && echo ansible-tmp-1550681868.78-72577694193075="` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1550681868.78-72577694193075 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
<127.0.0.1> PUT /var/lib/awx/.ansible/tmp/ansible-local-3ojpC7B/tmprk8i_o TO /var/lib/awx/.ansible/tmp/ansible-tmp-1550681868.78-72577694193075/AnsiballZ_command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-tmp-1550681868.78-72577694193075/ /var/lib/awx/.ansible/tmp/ansible-tmp-1550681868.78-72577694193075/AnsiballZ_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /var/lib/awx/.ansible/tmp/ansible-tmp-1550681868.78-72577694193075/AnsiballZ_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /var/lib/awx/.ansible/tmp/ansible-tmp-1550681868.78-72577694193075/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1550681868.78-72577694193075/AnsiballZ_command.py", line 113, in <module>
    _ansiballz_main()
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1550681868.78-72577694193075/AnsiballZ_command.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1550681868.78-72577694193075/AnsiballZ_command.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_command_payload_zfuJ1D/__main__.py", line 286, in <module>
  File "/tmp/ansible_command_payload_zfuJ1D/__main__.py", line 226, in main
OSError: [Errno 2] No such file or directory: '/var/lib/awx/shared'
fatal: [127.0.0.1]: FAILED! => {
    "changed": false, 
  …

The path is correct, the file exists and can be accessed and read.

> bash-4.2# cd /var/lib/awx/shared
bash-4.2# ls -ld
drwxr-xr-x 3 0 root 51 Feb 20 18:07 .
bash-4.2# ls -l
drwxr-xr-x 2 0 root  24576 Feb 19 17:05 group_vars
-rw-r--r-- 1 0 root 117418 Feb 20 17:42 hosts

If I run docker exec -it awx_celery /bin/bash then ansible-playbook and run the above play like this, it works.
Also if I use an absolute path and then don't use the chdir argument, I don't get the "No such file or directory" from AWX anymore. Example play:

`- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Import inventory
      shell: "awx-manage inventory_import --source=/var/lib/awx/shared/hosts --inventory-id=4 --overwrite"`

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: kubernetes
* Ansible version:  2.7.7
* Operating System: CentOS 7

##### STEPS TO REPRODUCE

1. Have a file on the awx_celery filesystem
2. Have a playbook using the shell module and chdir argument and try to do anything with the file. (example playbook above)

##### EXPECTED RESULTS

Playbook runs.

##### ACTUAL RESULTS

"No such file or dirrectory" exception is thrown.

**Comment by wenottingham** [comment]
See the 'job isolation' checkbox in settings. (Note: you likely shouldn't change this if you have multiple organizations writing and running playbooks through AWX).

Workaround: use a directory that's *not* /var/lib/awx/shared as your shared directory. (Somewhere in /opt?)
