### ISSUE TITLE
Custom rabbitmq password doesn't apply to the rabbitmq container

### ISSUE THREAD

**Issue by mrj1m0thy** [ansible/awx#3274]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
When using a custom password for rabbitmq during the installation process, the password is not actually changed in the rabbitmq container but the custom password is stored in the AWX installation causing a 500 error when trying to do any sort of major changes in AWX.

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: docker on linux
* Ansible version:  2.7.6
* Operating System: Windows 10
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Launch a new AWX environment with "rabbitmq_password" in the inventory set to something other than the default password
2. Attempt to add a AWS ec2 source to an inventory

##### EXPECTED RESULTS

Source is correctly added to the inventory

##### ACTUAL RESULTS

500 Error is received in the UI and in the logs I get:
`
2019-02-20 18:01:09,697 ERROR    django.request Internal Server Error: /api/v2/inventory_sources/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/kombu/utils/functional.py", line 36, in __call__
    return self.__value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'
`
Which is essentially useless information for me.

##### ADDITIONAL INFORMATION

In order to solve my issue I had to get into the rabbitmq container and manually change the password for the guest user to the one I set in the inventory by doing: `rabbitmqctl change_password guest`

**Comment by konkolorado** [comment]
It almost looks like the different installation procedures are using different variables to set the rabbitmq default password.  The compose deployment seems to not set the password at all.

The installer [installer/roles/local_docker/tasks/standalone.yml](https://github.com/ansible/awx/blob/0dbf21a15c3f26879ae31a8d15c8535828c081a1/installer/roles/local_docker/tasks/standalone.yml#L109)  references rabbitmq_default_password and the [installer/inventory](https://github.com/ansible/awx/blob/0dbf21a15c3f26879ae31a8d15c8535828c081a1/installer/inventory#L91) references rabbitmq_password.

**Comment by radioactive73** [comment]
> It almost looks like the different installation procedures are using different variables to set the rabbitmq default password. The compose deployment seems to not set the password at all.
> 
> The installer [installer/roles/local_docker/tasks/standalone.yml](https://github.com/ansible/awx/blob/0dbf21a15c3f26879ae31a8d15c8535828c081a1/installer/roles/local_docker/tasks/standalone.yml#L109) references rabbitmq_default_password and the [installer/inventory](https://github.com/ansible/awx/blob/0dbf21a15c3f26879ae31a8d15c8535828c081a1/installer/inventory#L91) references rabbitmq_password.

Updating the referenced rabbitmq_default_password variable to rabbitmq_password in [installer/roles/local_docker/tasks/standalone.yml](https://github.com/ansible/awx/blob/0dbf21a15c3f26879ae31a8d15c8535828c081a1/installer/roles/local_docker/tasks/standalone.yml#L109) did the trick for me. The deployment through ansible now properly sets the password without having to manually update it. I had to change both RABBITMQ_DEFAULT_PASS and RABBITMQ_PASSWORD to point to rabbitmq_password

I'm not sure if this is the best approach but for a local docker install it worked.
