### ISSUE TITLE
[3.0.1] Could not connect to websocket: 403

### ISSUE THREAD

**Issue by Commifreak** [ansible/awx#3276]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

After Upgrade to 3.0.1, I get no live Job output anymore. Errors showing up in the browsers developer console: My Firefox can no longer connect to the AWX websocket at /websocket/:

Request:
```
GET /websocket/ HTTP/1.1
Host: ansible-qlb.jki.intern
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Sec-WebSocket-Version: 13
Origin: http://ansible-qlb.jki.intern
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: +7XQILrR9pg8HprqS/ndwA==
Connection: keep-alive, Upgrade
Cookie: csrftoken=o4iLdPgedzHxf64oejvJt2sV9CoTL0Yyxxi7GFRgfdSSZXcjyUfSgpfgIugNyaDS; current_user=%7B%22id%22%3A1%2C%22type%22%3A%22user%22%2C%22url%22%3A%22%2Fapi%2Fv2%2Fusers%2F1%2F%22%2C%22related%22%3A%7B%22teams%22%3A%22%2Fapi%2Fv2%2Fusers%2F1%2Fteams%2F%22%2C%22organizations%22%3A%22%2Fapi%2Fv2%2Fusers%2F1%2Forganizations%2F%22%2C%22admin_of_organizations%22%3A%22%2Fapi%2Fv2%2Fusers%2F1%2Fadmin_of_organizations%2F%22%2C%22projects%22%3A%22%2Fapi%2Fv2%2Fusers%2F1%2Fprojects%2F%22%2C%22credentials%22%3A%22%2Fapi%2Fv2%2Fusers%2F1%2Fcredentials%2F%22%2C%22roles%22%3A%22%2Fapi%2Fv2%2Fusers%2F1%2Froles%2F%22%2C%22activity_stream%22%3A%22%2Fapi%2Fv2%2Fusers%2F1%2Factivity_stream%2F%22%2C%22access_list%22%3A%22%2Fapi%2Fv2%2Fusers%2F1%2Faccess_list%2F%22%2C%22tokens%22%3A%22%2Fapi%2Fv2%2Fusers%2F1%2Ftokens%2F%22%2C%22authorized_tokens%22%3A%22%2Fapi%2Fv2%2Fusers%2F1%2Fauthorized_tokens%2F%22%2C%22personal_tokens%22%3A%22%2Fapi%2Fv2%2Fusers%2F1%2Fpersonal_tokens%2F%22%7D%2C%22summary_fields%22%3A%7B%22user_capabilities%22%3A%7B%22edit%22%3Atrue%2C%22delete%22%3Afalse%7D%7D%2C%22created%22%3A%222018-12-14T07%3A23%3A43.054211Z%22%2C%22username%22%3A%22admin%22%2C%22first_name%22%3A%22Robin%22%2C%22last_name%22%3A%22Kluth%22%2C%22email%22%3A%22robin.kluth%40julius-kuehn.de%22%2C%22is_superuser%22%3Atrue%2C%22is_system_auditor%22%3Afalse%2C%22ldap_dn%22%3A%22%22%2C%22external_account%22%3Anull%2C%22auth%22%3A%5B%5D%7D; sessionid=knwhgqlt5dbxwlwtqg14etqjt6u0d54u; userLoggedIn=true; sessionExpired=false; lastPath=%2Fjobs%2Fplaybook%2F184
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
```

Response:
```
HTTP 403
```

![unbenannt](https://user-images.githubusercontent.com/87267/53146721-98be6000-35a5-11e9-8ee3-6c32810fe7d4.JPG)

I have absolutely no idea, since AWX is set up via Docker, so it should setup all by itself.

Was working in 2.1.2

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: docker (local)
* Ansible version:  2.7.7
* Operating System: Ubuntu 18.04 LTS
* Web Browser: Firefox 65.0.1

##### STEPS TO REPRODUCE

Visit start-page of AWX, open F12 -> Developer Console -> See errors about no connection to /websocket/

##### EXPECTED RESULTS

Working websocket connection

**Comment by ryanpetrello** [comment]
@Commifreak are you encountering this issue in any other browsers?  Are you able to click on the HTTP 403 errors and view the response body (does it provide any additional context?)

**Comment by Commifreak** [comment]
Hi, thanks for your answer.

Interesting - I just tested Google Chrome, that is working:

![chrome](https://user-images.githubusercontent.com/87267/53320199-3a5eed80-38d5-11e9-8a72-2d1576ff4894.jpg)


But Firefox is still unwilling.

I can click on the 403 but the response is empty.

**Comment by Commifreak** [comment]
Got the problem: Using FoxyProxy since years - also with AWX. It seems that a FireFox Upgrade broke FoxyProxy's ability to proxy ws:// - disabling FoxyProxy recovers AWXs full functionality.
