### ISSUE TITLE
Create contraints for launching new jobs connected to system resources (don't launch more jobs if system is out of RAM)

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#3277]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY
It would be cool if AWX could be configured to prevent launching of tasks for example if 90% of RAM is actively being used by instance where AWX runs. Right now it's not connected to OS resources in any way, which requires very inefficient setup (in peaks AWX uses about 15GB RAM, but most of time about 5GB, yet we had to add 16GB to VM where it run just to avoid swap-death of peaks).

In simple words: check instance resources before launching a job - if there is too much RAM / CPU used, keep job pending until resources are available.

**Comment by wenottingham** [comment]
This is what the capacity sliders are for, in terms of forks. Since there's no way to determine exactly how much resources the next job will run, it doesn't make sense to wait for an arbitrary low water mark that may not be relevant.

**Comment by benapetr** [comment]
> This is what the capacity sliders are for, in terms of forks. Since there's no way to determine exactly how much resources the next job will run, it doesn't make sense to wait for an arbitrary low water mark that may not be relevant.

I don't agree - if you know that you are already above some threshold (say 95% of RAM usage - should be possible to define by user) then it does make sense to prevent launching more jobs until RAM usage is lower. If you keep on spawning more jobs, you kill the server. Which is exactly what is happening now.

**Comment by shanemcd** [comment]
Closing due to lack of interest in this issue.
