### ISSUE TITLE
Unable to parse inventory file

### ISSUE THREAD

**Issue by nutts** [ansible/awx#3286]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY
Failed in my first case, failing to parse the inventory file. 

##### ENVIRONMENT
* AWX version: 2.1.2
* AWX install method: non-docker, find a google link https://www.howtoforge.com/tutorial/centos-ansible-awx-installation/
* Ansible version:  2.7.4
* Operating System: Cent OS 7
* Web Browser: firefox

##### STEPS TO REPRODUCE

1. Create an inventory
2. Manually add host, the name is acs003.adobesandbox.com
3. Create a template, playbook is gather_facts/main.yml
3. Run this template

##### EXPECTED RESULTS

Run the first case successfully.

##### ACTUAL RESULTS

 It will throw error: Failed to parse Failed to parse /tmp/awx_93_tl3Yma/tmp7HONdX with yaml plugin
Syntax Error while loading YAML.   did not find expected key  The error appears
to have been in '/tmp/awx_93_tl3Yma/tmp7HONdX': line 3, column 115, but may be
elsewhere in the file depending on the exact syntax problem.  The offending
line appears to be:  # -*- coding: utf-8 -*- print '{"all": {"hosts":
["acs003.adobesandbox.com"], "vars": {"ansible_ssh_user": "admin",
"ansible_sudo": true}}, "_meta": {"hostvars": {"acs003.adobesandbox.com":
{"ansible_host": "35.166.241.214"}}}}'

**Comment by ryanpetrello** [comment]
@nutts,


https://www.howtoforge.com/tutorial/centos-ansible-awx-installation/ isn't a method of installing awx that the project maintainers generally provide support/help with.  If you're encountering this issue on the latest awx using one the supported installation methods (https://github.com/ansible/awx/blob/devel/INSTALL.md), please let me know and I'll reopen this.
