### ISSUE TITLE
Can not stat file: Custom Credential template

### ISSUE THREAD

**Issue by p1rateg0ld** [ansible/awx#3299]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY
Trying to use a template from a custom credential creates the file, but the host cannot find it when its called. 

To help debug I've created the following volume between the awx container and host: /tmp:/tmp 

Doing so verified that the files are indeed being created, however they tend to disappear right before they're needed.  

I also moved the call for the credential to the top of the playbook, but that did not help. For context, I need this the custom config files to be inserted into a docker container.

Using environment variables instead of a template file works, but due to the amount of variables, would be far from ideal.

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: docker on linux (compose)
* Ansible version:  Whichever came with 3.0.1
* Operating System: Amazon Linux 2
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Create a custom credential with a file template and environment variable. Read the environment variable for the filepath and attempt an operation on the file. The file may not ever exist on the host.

##### EXPECTED RESULTS

A template file named with a random string of characters given an environment variable name contains injected credentials from the tower vault.

##### ACTUAL RESULTS

`FAILED! => {"changed": true, "cmd": ["mv", "/tmp/awx_742_3end_ueu/tmphrdq9cfp", "/var/lib/ansible_python_container/GOOGLE_APPLICATION_CREDENTIALS"], "delta": "0:00:00.003292", "end": "2019-02-22 23:10:41.957345", "msg": "non-zero return code", "rc": 1, "start": "2019-02-22 23:10:41.954053", "stderr": "mv: cannot stat ‘/tmp/awx_742_3end_ueu/tmphrdq9cfp’: No such file or directory", "stderr_lines": ["mv: cannot stat ‘/tmp/awx_742_3end_ueu/tmphrdq9cfp’: No such file or directory"], "stdout": "", "stdout_lines": []}`
##### ADDITIONAL INFORMATION

Example Injector Configuration:
`env:
  GOOGLE_APPLICATION_CREDENTIALS: '{{ tower.filename.gsuite }}'
extra_vars:
  google_application_credentials: '{{ tower.filename.gsuite }}'
file:
  template.gsuite: |
    {
      "AUTH_PROVIDER_X509_CERT_URL": "{{ auth_provider_x509_cert_url }}"
      "AUTH_URI": "{{ auth_uri }}"
      "CLIENT_EMAIL": "{{ client_email }}"
      "CLIENT_ID": "{{ client_id }}"
      "CLIENT_X509_CERT_URL": "{{ client_x509_cert_url }}"
      "PRIVATE_KEY": "{{ private_key }}"
      "PRIVATE_KEY_ID": "{{ private_key_id }}"
      "PROJECT_ID": "{{ project_id }}"
      "TOKEN_URI": "{{ token_uri }}"
      "TYPE": "{{ type }}"
    }
`

**Comment by awithrow9** [comment]
Do you still see this with the latest AWX?

**Comment by ryanpetrello** [comment]
Closing due to age.  If you're still encountering issues on the latest AWX, please file a new ticket with details.
