### ISSUE TITLE
Issue with Self-Signed Certificates

### ISSUE THREAD

**Issue by knechtionscoding** [ansible/awx#33]
### Summary

Despite setting NPM to use the HTTP registry, git config http.sslVerify false, and trying to set NPM ca to null it doesn't seem to be respecting the use of a corporate self-signed certificate. 

### Steps To Reproduce:
Use Enterprise self-signed certificate and add it to the CentOS server using:

cp foo.crt /etc/pki/ca-source/source/anchors
update-ca-trust extract

then try to run the install playbook (local docker version)
### Expected Results:

Completion of Ansible Playbook

### Actual Results:

NPM err! git clone on the Build AWX Distribution Task of image_build

### Additional Information:

Full error: 
`
fatal: [localhost -> localhost]: FAILED! => {"changed": true, "cmd": "make sdist", "delta": "0:15:42.611880", "end": "2017-09-07 10:10:28.688145", "failed": true, "rc": 2, "start": "2017-09-07 09:54:46.076265", "stderr": "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/jkbrzt/rrule.git /root/.npm/_git-remotes/git-github-com-jkbrzt-rrule-git-4ff63b2f8524fd6d5ba6e80db770953b5cd08a0c-f2d4f677: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-jkbrzt-rrule-git-4ff63b2f8524fd6d5ba6e80db770953b5cd08a0c-f2d4f677'...\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/jkbrzt/rrule.git /root/.npm/_git-remotes/git-github-com-jkbrzt-rrule-git-4ff63b2f8524fd6d5ba6e80db770953b5cd08a0c-f2d4f677: \nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/jkbrzt/rrule.git /root/.npm/_git-remotes/git-github-com-jkbrzt-rrule-git-4ff63b2f8524fd6d5ba6e80db770953b5cd08a0c-f2d4f677: fatal: read error: Connection timed out\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-drag-and-drop-lists.git /root/.npm/_git-remotes/git-github-com-ansible-angular-drag-and-drop-lists-git-4d32654ab7159689a7767b9be8fc85f9812ca5a8-33d66294: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ansible-angular-drag-and-drop-lists-git-4d32654ab7159689a7767b9be8fc85f9812ca5a8-33d66294'...\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-drag-and-drop-lists.git /root/.npm/_git-remotes/git-github-com-ansible-angular-drag-and-drop-lists-git-4d32654ab7159689a7767b9be8fc85f9812ca5a8-33d66294: \nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-drag-and-drop-lists.git /root/.npm/_git-remotes/git-github-com-ansible-angular-drag-and-drop-lists-git-4d32654ab7159689a7767b9be8fc85f9812ca5a8-33d66294: fatal: read error: Connection timed out\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/timezone-js.git /root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-6937de14ce0c193961538bb5b3b12b7ef62a358f-d653e9e1: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-6937de14ce0c193961538bb5b3b12b7ef62a358f-d653e9e1'...\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/timezone-js.git /root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-6937de14ce0c193961538bb5b3b12b7ef62a358f-d653e9e1: \nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/timezone-js.git /root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-6937de14ce0c193961538bb5b3b12b7ef62a358f-d653e9e1: fatal: read error: Connection timed out\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-codemirror.git /root/.npm/_git-remotes/git-github-com-ansible-angular-codemirror-git-75c3a2d0ccdf2e4c836fab7d7617d5db6c585c1b-799d0573: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ansible-angular-codemirror-git-75c3a2d0ccdf2e4c836fab7d7617d5db6c585c1b-799d0573'...\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-codemirror.git /root/.npm/_git-remotes/git-github-com-ansible-angular-codemirror-git-75c3a2d0ccdf2e4c836fab7d7617d5db6c585c1b-799d0573: \nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-codemirror.git /root/.npm/_git-remotes/git-github-com-ansible-angular-codemirror-git-75c3a2d0ccdf2e4c836fab7d7617d5db6c585c1b-799d0573: fatal: read error: Connection timed out\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-tz-extensions.git /root/.npm/_git-remotes/git-github-com-ansible-angular-tz-extensions-git-33caaa9ccf5dfe29a95962c17c3c9e6b9775be35-a87177b8: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ansible-angular-tz-extensions-git-33caaa9ccf5dfe29a95962c17c3c9e6b9775be35-a87177b8'...\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-tz-extensions.git /root/.npm/_git-remotes/git-github-com-ansible-angular-tz-extensions-git-33caaa9ccf5dfe29a95962c17c3c9e6b9775be35-a87177b8: \nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-tz-extensions.git /root/.npm/_git-remotes/git-github-com-ansible-angular-tz-extensions-git-33caaa9ccf5dfe29a95962c17c3c9e6b9775be35-a87177b8: fatal: read error: Connection timed out\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-scheduler.git /root/.npm/_git-remotes/git-github-com-ansible-angular-scheduler-git-9f2893a54c758b05bd6afce897488c01a6e8959d-9914d692: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ansible-angular-scheduler-git-9f2893a54c758b05bd6afce897488c01a6e8959d-9914d692'...\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-scheduler.git /root/.npm/_git-remotes/git-github-com-ansible-angular-scheduler-git-9f2893a54c758b05bd6afce897488c01a6e8959d-9914d692: \nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-scheduler.git /root/.npm/_git-remotes/git-github-com-ansible-angular-scheduler-git-9f2893a54c758b05bd6afce897488c01a6e8959d-9914d692: fatal: read error: Connection timed out\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-breadcrumb.git /root/.npm/_git-remotes/git-github-com-ansible-angular-breadcrumb-git-6c2b1ad45ad5fbe7adf39af1ef3b294ca8e207a9-c4dd1768: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ansible-angular-breadcrumb-git-6c2b1ad45ad5fbe7adf39af1ef3b294ca8e207a9-c4dd1768'...\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-breadcrumb.git /root/.npm/_git-remotes/git-github-com-ansible-angular-breadcrumb-git-6c2b1ad45ad5fbe7adf39af1ef3b294ca8e207a9-c4dd1768: \nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-breadcrumb.git /root/.npm/_git-remotes/git-github-com-ansible-angular-breadcrumb-git-6c2b1ad45ad5fbe7adf39af1ef3b294ca8e207a9-c4dd1768: fatal: read error: Connection timed out\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/nvd3.git /root/.npm/_git-remotes/git-github-com-ansible-nvd3-git-a28bcd494a1df0677be7cf2ebc0578f44eb21102-422814a5: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ansible-nvd3-git-a28bcd494a1df0677be7cf2ebc0578f44eb21102-422814a5'...\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/nvd3.git /root/.npm/_git-remotes/git-github-com-ansible-nvd3-git-a28bcd494a1df0677be7cf2ebc0578f44eb21102-422814a5: \nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/nvd3.git /root/.npm/_git-remotes/git-github-com-ansible-nvd3-git-a28bcd494a1df0677be7cf2ebc0578f44eb21102-422814a5: fatal: read error: Connection timed out\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/lorenzofox3/lrInfiniteScroll.git /root/.npm/_git-remotes/git-github-com-lorenzofox3-lrInfiniteScroll-git-59d348bc5c18f164438d2a30f1fd79b333c3b649-a44206e6: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-lorenzofox3-lrInfiniteScroll-git-59d348bc5c18f164438d2a30f1fd79b333c3b649-a44206e6'...\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/lorenzofox3/lrInfiniteScroll.git /root/.npm/_git-remotes/git-github-com-lorenzofox3-lrInfiniteScroll-git-59d348bc5c18f164438d2a30f1fd79b333c3b649-a44206e6: \nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/lorenzofox3/lrInfiniteScroll.git /root/.npm/_git-remotes/git-github-com-lorenzofox3-lrInfiniteScroll-git-59d348bc5c18f164438d2a30f1fd79b333c3b649-a44206e6: fatal: read error: Connection timed out\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/ngToast.git /root/.npm/_git-remotes/git-github-com-ansible-ngToast-git-fea95bb34d27687e414619b4f72c11735d909f93-93cae3e8: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ansible-ngToast-git-fea95bb34d27687e414619b4f72c11735d909f93-93cae3e8'...\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/ngToast.git /root/.npm/_git-remotes/git-github-com-ansible-ngToast-git-fea95bb34d27687e414619b4f72c11735d909f93-93cae3e8: \nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/ngToast.git /root/.npm/_git-remotes/git-github-com-ansible-ngToast-git-fea95bb34d27687e414619b4f72c11735d909f93-93cae3e8: fatal: read error: Connection timed out\nnpm ERR! Linux 3.10.0-327.el7.x86_64\nnpm ERR! argv \"/usr/local/bin/node\" \"/usr/local/bin/npm\" \"--unsafe-perm\" \"--prefix\" \"awx/ui\" \"install\" \"awx/ui\"\nnpm ERR! node v6.11.3\nnpm ERR! npm  v3.10.10\nnpm ERR! code 128\n\nnpm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/jkbrzt/rrule.git /root/.npm/_git-remotes/git-github-com-jkbrzt-rrule-git-4ff63b2f8524fd6d5ba6e80db770953b5cd08a0c-f2d4f677\nnpm ERR! fatal: read error: Connection timed out\nnpm ERR! \nnpm ERR! \nnpm ERR! If you need help, you may report this error at:\nnpm ERR!     <https://github.com/npm/npm/issues>\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /root/awx/npm-debug.log\nmake: *** [awx/ui/.deps_built] Error 1", "stderr_lines": ["npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/jkbrzt/rrule.git /root/.npm/_git-remotes/git-github-com-jkbrzt-rrule-git-4ff63b2f8524fd6d5ba6e80db770953b5cd08a0c-f2d4f677: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-jkbrzt-rrule-git-4ff63b2f8524fd6d5ba6e80db770953b5cd08a0c-f2d4f677'...", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/jkbrzt/rrule.git /root/.npm/_git-remotes/git-github-com-jkbrzt-rrule-git-4ff63b2f8524fd6d5ba6e80db770953b5cd08a0c-f2d4f677: ", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/jkbrzt/rrule.git /root/.npm/_git-remotes/git-github-com-jkbrzt-rrule-git-4ff63b2f8524fd6d5ba6e80db770953b5cd08a0c-f2d4f677: fatal: read error: Connection timed out", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-drag-and-drop-lists.git /root/.npm/_git-remotes/git-github-com-ansible-angular-drag-and-drop-lists-git-4d32654ab7159689a7767b9be8fc85f9812ca5a8-33d66294: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ansible-angular-drag-and-drop-lists-git-4d32654ab7159689a7767b9be8fc85f9812ca5a8-33d66294'...", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-drag-and-drop-lists.git /root/.npm/_git-remotes/git-github-com-ansible-angular-drag-and-drop-lists-git-4d32654ab7159689a7767b9be8fc85f9812ca5a8-33d66294: ", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-drag-and-drop-lists.git /root/.npm/_git-remotes/git-github-com-ansible-angular-drag-and-drop-lists-git-4d32654ab7159689a7767b9be8fc85f9812ca5a8-33d66294: fatal: read error: Connection timed out", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/timezone-js.git /root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-6937de14ce0c193961538bb5b3b12b7ef62a358f-d653e9e1: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-6937de14ce0c193961538bb5b3b12b7ef62a358f-d653e9e1'...", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/timezone-js.git /root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-6937de14ce0c193961538bb5b3b12b7ef62a358f-d653e9e1: ", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/timezone-js.git /root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-6937de14ce0c193961538bb5b3b12b7ef62a358f-d653e9e1: fatal: read error: Connection timed out", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-codemirror.git /root/.npm/_git-remotes/git-github-com-ansible-angular-codemirror-git-75c3a2d0ccdf2e4c836fab7d7617d5db6c585c1b-799d0573: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ansible-angular-codemirror-git-75c3a2d0ccdf2e4c836fab7d7617d5db6c585c1b-799d0573'...", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-codemirror.git /root/.npm/_git-remotes/git-github-com-ansible-angular-codemirror-git-75c3a2d0ccdf2e4c836fab7d7617d5db6c585c1b-799d0573: ", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-codemirror.git /root/.npm/_git-remotes/git-github-com-ansible-angular-codemirror-git-75c3a2d0ccdf2e4c836fab7d7617d5db6c585c1b-799d0573: fatal: read error: Connection timed out", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-tz-extensions.git /root/.npm/_git-remotes/git-github-com-ansible-angular-tz-extensions-git-33caaa9ccf5dfe29a95962c17c3c9e6b9775be35-a87177b8: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ansible-angular-tz-extensions-git-33caaa9ccf5dfe29a95962c17c3c9e6b9775be35-a87177b8'...", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-tz-extensions.git /root/.npm/_git-remotes/git-github-com-ansible-angular-tz-extensions-git-33caaa9ccf5dfe29a95962c17c3c9e6b9775be35-a87177b8: ", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-tz-extensions.git /root/.npm/_git-remotes/git-github-com-ansible-angular-tz-extensions-git-33caaa9ccf5dfe29a95962c17c3c9e6b9775be35-a87177b8: fatal: read error: Connection timed out", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-scheduler.git /root/.npm/_git-remotes/git-github-com-ansible-angular-scheduler-git-9f2893a54c758b05bd6afce897488c01a6e8959d-9914d692: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ansible-angular-scheduler-git-9f2893a54c758b05bd6afce897488c01a6e8959d-9914d692'...", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-scheduler.git /root/.npm/_git-remotes/git-github-com-ansible-angular-scheduler-git-9f2893a54c758b05bd6afce897488c01a6e8959d-9914d692: ", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-scheduler.git /root/.npm/_git-remotes/git-github-com-ansible-angular-scheduler-git-9f2893a54c758b05bd6afce897488c01a6e8959d-9914d692: fatal: read error: Connection timed out", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-breadcrumb.git /root/.npm/_git-remotes/git-github-com-ansible-angular-breadcrumb-git-6c2b1ad45ad5fbe7adf39af1ef3b294ca8e207a9-c4dd1768: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ansible-angular-breadcrumb-git-6c2b1ad45ad5fbe7adf39af1ef3b294ca8e207a9-c4dd1768'...", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-breadcrumb.git /root/.npm/_git-remotes/git-github-com-ansible-angular-breadcrumb-git-6c2b1ad45ad5fbe7adf39af1ef3b294ca8e207a9-c4dd1768: ", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-breadcrumb.git /root/.npm/_git-remotes/git-github-com-ansible-angular-breadcrumb-git-6c2b1ad45ad5fbe7adf39af1ef3b294ca8e207a9-c4dd1768: fatal: read error: Connection timed out", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/nvd3.git /root/.npm/_git-remotes/git-github-com-ansible-nvd3-git-a28bcd494a1df0677be7cf2ebc0578f44eb21102-422814a5: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ansible-nvd3-git-a28bcd494a1df0677be7cf2ebc0578f44eb21102-422814a5'...", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/nvd3.git /root/.npm/_git-remotes/git-github-com-ansible-nvd3-git-a28bcd494a1df0677be7cf2ebc0578f44eb21102-422814a5: ", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/nvd3.git /root/.npm/_git-remotes/git-github-com-ansible-nvd3-git-a28bcd494a1df0677be7cf2ebc0578f44eb21102-422814a5: fatal: read error: Connection timed out", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/lorenzofox3/lrInfiniteScroll.git /root/.npm/_git-remotes/git-github-com-lorenzofox3-lrInfiniteScroll-git-59d348bc5c18f164438d2a30f1fd79b333c3b649-a44206e6: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-lorenzofox3-lrInfiniteScroll-git-59d348bc5c18f164438d2a30f1fd79b333c3b649-a44206e6'...", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/lorenzofox3/lrInfiniteScroll.git /root/.npm/_git-remotes/git-github-com-lorenzofox3-lrInfiniteScroll-git-59d348bc5c18f164438d2a30f1fd79b333c3b649-a44206e6: ", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/lorenzofox3/lrInfiniteScroll.git /root/.npm/_git-remotes/git-github-com-lorenzofox3-lrInfiniteScroll-git-59d348bc5c18f164438d2a30f1fd79b333c3b649-a44206e6: fatal: read error: Connection timed out", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/ngToast.git /root/.npm/_git-remotes/git-github-com-ansible-ngToast-git-fea95bb34d27687e414619b4f72c11735d909f93-93cae3e8: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ansible-ngToast-git-fea95bb34d27687e414619b4f72c11735d909f93-93cae3e8'...", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/ngToast.git /root/.npm/_git-remotes/git-github-com-ansible-ngToast-git-fea95bb34d27687e414619b4f72c11735d909f93-93cae3e8: ", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/ngToast.git /root/.npm/_git-remotes/git-github-com-ansible-ngToast-git-fea95bb34d27687e414619b4f72c11735d909f93-93cae3e8: fatal: read error: Connection timed out", "npm ERR! Linux 3.10.0-327.el7.x86_64", "npm ERR! argv \"/usr/local/bin/node\" \"/usr/local/bin/npm\" \"--unsafe-perm\" \"--prefix\" \"awx/ui\" \"install\" \"awx/ui\"", "npm ERR! node v6.11.3", "npm ERR! npm  v3.10.10", "npm ERR! code 128", "", "npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/jkbrzt/rrule.git /root/.npm/_git-remotes/git-github-com-jkbrzt-rrule-git-4ff63b2f8524fd6d5ba6e80db770953b5cd08a0c-f2d4f677", "npm ERR! fatal: read error: Connection timed out", "npm ERR! ", "npm ERR! ", "npm ERR! If you need help, you may report this error at:", "npm ERR!     <https://github.com/npm/npm/issues>", "", "npm ERR! Please include the following file with any support request:", "npm ERR!     /root/awx/npm-debug.log", "make: *** [awx/ui/.deps_built] Error 1"], "stdout": "npm --unsafe-perm --prefix awx/ui install awx/ui", "stdout_lines": ["npm --unsafe-perm --prefix awx/ui install awx/ui"]}`

**Comment by jlmitch5** [comment]
@KnechtionsCoding can you ping github from inside your server?

I'm not the most familiar with certs so I can do some digging into what exactly your setup is to see if I can try to reproduce, but first, just making sure you have a connection to github seems like the most simple problem based on the `"Connection timed out"` errors.

**Comment by jlmitch5** [comment]
@gconsidine I think the git+https solution in package.json may have an effect on this as well.  I'm gonna assign you to issue so that we can ping on this one once that's done.

**Comment by knechtionscoding** [comment]
@jlmitch5 I've got a connection to github on that server. This was the last error that I couldn't solve. Turning off the NPM http check and the git check solved the first two.

**Comment by jlmitch5** [comment]
@KnechtionsCoding if you want to try to apply the change in PR #68 linked above manually (or just wait til it goes in), I wonder if it will fix things for you?  involves changing the protocol part of the github urls for those node packages.

Note that you should be able to try the npm install to the same affect by doing `cd awx/ui; npm install`, that might be helpful as we try to get to the bottom of this.

**Comment by knechtionscoding** [comment]
Sure. I'll try those out now.

**Comment by gconsidine** [comment]
Fixed in #49

**Comment by knechtionscoding** [comment]
@jlmitch5 I made the changes manually and ran it again. I'm getting a different issue now unrelated to certificates. So this issue should be considered resolved.
