### ISSUE TITLE
Stack trace thrown if improper format used during prompted Extra Var field entry 

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#3302]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Stack Trace thrown if improper format used during prompted Extra Var field entry 

##### ENVIRONMENT
* AWX version: 3.0.1
* Operating System: MacOS
* Web Browser: Firefox

##### STEPS TO REPRODUCE
1. Create a JT with prompted Extra Var field
2. Launch JT and entry an incorrect extra_var format: "fff"
3. Click next on the Prompt modal
Note: Error thrown over the modal and stacktrace generated
Note: Error modal correct and corrective modification to the field allows for the JT to launch successfully

##### EXPECTED RESULTS
No stack trace thrown

##### ACTUAL RESULTS
Stack Trace

##### ADDITIONAL INFORMATION
![screen shot 2019-02-22 at 6 37 39 pm](https://user-images.githubusercontent.com/12446869/53277341-63af2c00-36d1-11e9-9aa7-6585405b0e4b.png)

**Comment by mabashian** [comment]
I think this has been fixed - probably by @keithjgrant.  This is what I see when I try to reproduce:

<img width="800" alt="Screen Shot 2019-06-12 at 4 22 34 PM" src="https://user-images.githubusercontent.com/9889020/59383672-6a1fed00-8d2e-11e9-90a0-7986f03c3704.png">

Which seems reasonable to me.  The user cannot move forward with the launch until they correct the error.

I also don't see any stacktrace in the console.
