### ISSUE TITLE
Security concerns about unverified Docker build dependencies

### ISSUE THREAD

**Issue by leoluk** [ansible/awx#3307]
##### ISSUE TYPE
 - Feature Request / Discussion

##### COMPONENT NAME
 - Installer

##### SUMMARY

While looking at the installer sources, I found a few places where third party code or binaries were pulled in without pinning or verifying them.

Unverified binary fetched from GitHub:

https://github.com/ansible/awx/blob/b383144b69d9a0e375d4928514d844bf4fe012a8/installer/roles/image_build/templates/Dockerfile.j2#L12

Third party RPM installed via plain HTTP, without validating signature:

https://github.com/ansible/awx/blob/b383144b69d9a0e375d4928514d844bf4fe012a8/installer/roles/image_build/templates/Dockerfile.j2#L32

Unverified Nodesource installer:

https://github.com/ansible/awx/blob/b383144b69d9a0e375d4928514d844bf4fe012a8/installer/roles/image_build/files/Dockerfile.sdist#L12

Also, the Python dependencies are not hashed and are therefore unreproducible/susceptible to PyPI compromise.

If there's interest in hardening the installer against that kind of threat model/removing dependencies on 3rd parties, I'm happy to contribute. Some thoughts:

- Either vendor the `tini` binary or validate its checksum in the Ansible playbook.
- Add the PostgreSQL repository and import the key, or use a SCL instead (unless that has major differences).
- Use SCL Node.js instead of Nodesource.
- Pin the packages using hashin: https://pypi.org/project/hashin/

**Comment by shanemcd** [comment]
As of right now, there are 2 places where we pull in things from hardcoded URL:

https://github.com/ansible/awx/blob/1e690fcd7f2854dda493722f0084a4f22758823b/tools/ansible/roles/dockerfile/templates/Dockerfile.j2#L49-L55

This ^ is pulling in a build dependency (not included in the final image) - and only on a specific architecture. I don't really care enough, but if someone wants to do it then feel free to send a PR.

https://github.com/ansible/awx/blob/1e690fcd7f2854dda493722f0084a4f22758823b/tools/ansible/roles/dockerfile/templates/Dockerfile.j2#L160

This ^ is inside a conditional that only gets run when building the development environment. Again, if someone wants to send a PR feel free.
