### ISSUE TITLE
Provide the ability to add several schedules to a job using different Inventory and Credentials.

### ISSUE THREAD

**Issue by cesan3** [ansible/awx#331]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
We would like to have the ability to add schedules where we can setup the INVENTORY and the CREDENTIALS we want that scheduled JOB to run against.

Right now, the only way of doing what I need with a generic JOB is to copy it and set the values for that specific JOB and then I can add a schedule.

##### ENVIRONMENT

* AWX version: 1.0.0.550
* AWX install method:  docker on linux
* Ansible version:  2,4.0
* Operating System: FC26
* Web Browser: Firefox/Chrome

##### STEPS TO REPRODUCE

I want to run the same JOB over several different clients, and I want to add different schedules for each one.
I'd like the ability to chose an INVENTORY and CREDENTIALS for that specific scheduled JOB.  Also, if the job has surveys, I'd also like to be able to chose those values.  Right now that's feasible via the environment, but it'll be nice to pick it from the survey elements directly, if possible.

I could be running the same JOB against 500 clients on different schedules and each client has a different CREDENTIAL to connect. 

The silly way of doing it is probably via the REST API, by duplicating the JOBS with the wanted variables, including INVENTORY and CREDENTIAL, and then adding the specific schedule to it, but I think that duplication should be avoided in this case.

**Comment by matburt** [comment]
I totally agree that we need to move some options out to the schedule for this. Good feature idea.

**Comment by wenottingham** [comment]
This is #169
