### ISSUE TITLE
For JT X, Admin on JT + Notification Admin on Org couldn't able to assgin Notification for that JT

### ISSUE THREAD

**Issue by Ompragash** [ansible/awx#3311]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - UI
 
##### SUMMARY
For Job Template X, Admin on JT + Notification Admin on Org couldn't able to assgin Notification for that JT. According to this #2949 , notification tab is missing in JT for Org Admin but he can able to assign notify templates via API. But Admin on JT + Notification Admin on Org couldn't able to assign it via API and throws `You don't have permission to do that (HTTP 403).` error.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

- Create a Normal User 'Y'
- Give him Notification Admin on Org Level and Admin role for a JT 'X'
- Now, login as user 'Y' 
- In UI, he can't assign notify templates for JT 'X' as the notification tab will be missing on UI and it's a known issue #2949 
- Try to assign notification for JT 'X' via API

##### EXPECTED RESULTS
Notification assigned to JT 'X'

##### ACTUAL RESULTS
Failed with `You don't have permission to do that (HTTP 403).` error.

**Comment by mabashian** [comment]
Following the steps outlined, User 'Y' will now see the notifications tab (based on latest devel).  I think that the problem you're outlining is that User 'Y' sees disabled on/off toggles in the notifications tab and is unable to toggle those values.  This is consistent with the api's behavior (throws 403).  The question is, is this the expected behavior?  @AlanCoding might need you or someone else with a more intimate knowledge of rbac to chime in.  The question is, should a notif admin with an admin role on a JT be able to _edit_ the notifications for that JT or should the just be able to see them?

**Comment by AlanCoding** [comment]
Right now it requires organization admin to attach the notification template to a job template.

https://github.com/ansible/awx/blob/d1005f91e73b8eff3ad1f5ebe327ab6315e8a22c/awx/main/access.py#L1463-L1465

Why admin, and why not notification_template_admin? A bug? @wwitzel3 @matburt

**Comment by jamesmarshall24** [comment]
@AlanCoding @mabashian I'm also seeing the same behavior with org admin and job templates. The toggle shows as disabled with the following:
- Notification template owned by Default org
- Project owned by Default org
- Inventory owned by Default org
- Credentials owned by Default org
- Job Template using the above owned objects
- "testuser" is set to org admin of Default

When you login as "testuser", go to "Organizations" and click on the Job Templates (to demonstrate that the templates are registered as associated to the org). Then in the job template, go to the notifications tab. The notification toggles will be grayed out.

**Comment by AlanCoding** [comment]
Resolved by https://github.com/ansible/awx/pull/3629

**Comment by kdelee** [comment]
@AlanCoding I did the following:

1) Add user to default org
2) Make user admin
3) Log in as user
4) Create a project with default org
5) Create a notification with default org
5) Create job template with project + save
6) attempt to enable notification :fire: (does not work)

**Comment by AlanCoding** [comment]
> 2. Make user admin

admin of the default org, right?

**Comment by ryanpetrello** [comment]
Resolved by https://github.com/ansible/awx/pull/3629
