### ISSUE TITLE
Bulk add user to groups/teams/jobs - job failure monitoring.

### ISSUE THREAD

**Issue by egidijus** [ansible/awx#3314]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
- UI
- CLI
##### SUMMARY
I am trying to add a user to many groups, because I would like to use this user to get "job status" via api.
There is a project I am working on, to try and use a simple python script to interrogate AWX api.

I tried using the UI, but I got very tired of clicking on all the templates.
I tried to find a way to do it in the DB, but I got lost in the "ancestors_id" ..

Could someone please help me, either manage user permissions, or have an API way of looking at failed jobs.

**Comment by egidijus** [comment]
Wow, just found this:
```
/api/v1/jobs/?failed=True
```

**Comment by jakemcdermott** [comment]
As you've pointed out, you should be able to filter by job status in the api`(?failed=True`), and also the ui searchable lists (`status:failed`).

Closing this issue as resolved - please reach out to our mailing list or stop by our irc channel if you have other questions.
