### ISSUE TITLE
On an Org Max Hosts form, an empty value as entered is not treated as unlimited

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#3317]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
A user can submit a min value of 0 on the Organization Max Hosts form and that is treated as an empty string on save. However, if the user attempts to enter an empty string, an error modal is thrown.

##### ENVIRONMENT
* AWX version: 3.0.1

##### STEPS TO REPRODUCE
1. On the Organization 'Max Hosts' field, enter a value and submit the form
2. Delete that value and attempt to submit the form

##### EXPECTED RESULTS

Empty string to be treated as unlimited -- in the same way as it's represented when a "0" is saved.

##### ACTUAL RESULTS

Error modal

##### ADDITIONAL INFORMATION
![screen shot 2019-02-26 at 2 38 30 pm](https://user-images.githubusercontent.com/12446869/53441191-3ebe0000-39d4-11e9-8804-52db626a1de6.png)

**Comment by mabashian** [comment]
https://github.com/ansible/awx/pull/3174/commits/3e80cd644918c1f3900ae045c6f9d2907eb00658 should address this @unlikelyzero

**Comment by unlikelyzero** [comment]
Verified that the user can set the Org Max Hosts field to empty and it is saved as such.
Verified that a user can set the Org Max Hosts field to "0" and it is saved as such
