### ISSUE TITLE
Auto logout is inconsistently routing the session to the login page after session expiry

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#3321]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

The Auto Logout functionality is not occuring consistently. I’m regularly thrown back to the login page if I’ve left a session idle <for some time> and I attempt to interact with an element of the page.

- I've seen this on the Org Edit, Job Results Detail, and Settings License pages.
- The page was in focus
- single user signed in
- no popup to notify the user that the session is expiring

##### ENVIRONMENT
* AWX version: 3.0.0

Firefox and chrome

##### STEPS TO REPRODUCE

None available.

##### EXPECTED RESULTS

Session timeout modal to appear and the session automatically logged out. 

##### ACTUAL RESULTS

Session re-routed to the login screen after interacting with an element.

##### ADDITIONAL INFORMATION

![wfviz](https://user-images.githubusercontent.com/12446869/55257590-bb900400-5236-11e9-853a-aa3de1d05cb1.gif)

[Archive 19-03-29 15-27-33.har.zip](https://github.com/ansible/awx/files/3024156/Archive.19-03-29.15-27-33.har.zip)

**Comment by wenottingham** [comment]
Plz test on https://github.com/ansible/awx/pull/3510

**Comment by unlikelyzero** [comment]
@wenottingham unfortunately, I still don't have accurate reproduction steps.

Is someone able to take a look at the har file to determine if #3510 will fix it?

**Comment by wenottingham** [comment]
Moving to test/tackle in the context of the new UI

**Comment by unlikelyzero** [comment]
tests are green but it remains to be seen if we should add an automated test for this. I'll verify this one manually once it lands on a packaged build of 4.0

**Comment by unlikelyzero** [comment]
will need to retest once session expiration lands

**Comment by unlikelyzero** [comment]
retest as a part of https://github.com/ansible/awx/pull/8168

**Comment by unlikelyzero** [comment]
Implicitly tested as a part of https://github.com/ansible/awx/pull/8168
