### ISSUE TITLE
Github Organisation OAUTH2 Callback URL Not Highlightable

### ISSUE THREAD

**Issue by davidkirwan** [ansible/awx#3323]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
The Github Organisation OAUTH2 Callback URL is not selectable or copyable in the UI. Hovering the mouse over this field shows up a :no_entry_sign: sign.

##### ENVIRONMENT
* AWX version: 3.4.0
* AWX install method: openshift
* Ansible version:  2.7.5
* Operating System: RHEL 7
* Web Browser: Firefox 65.0

##### STEPS TO REPRODUCE

Visit the Settings/Authentication/Github

##### EXPECTED RESULTS

I expect to be able to easily copy this OAUTH2 callback url, so I can configure the projects in Github.

##### ACTUAL RESULTS

I cannot select the Github Organisation OAUTH2 Callback URL, I had to stretch the browser out far enough to see the full URL, and manually type it into Github.

##### ADDITIONAL INFORMATION

![screenshot from 2019-02-27 12-12-39](https://user-images.githubusercontent.com/1700165/53489410-062c2e00-3a89-11e9-9b86-935d005c2424.png)

**Comment by mabashian** [comment]
This is just how Firefox works unfortunately.  https://bugzilla.mozilla.org/show_bug.cgi?id=195361 - the text is copyable in Chrome if you have access to that browser.

**Comment by davidkirwan** [comment]
@mabashian great thanks I'll use Chrome.

**Comment by ssbarnea** [comment]
This is really a PITA, we are better-off if you just replace the input with a simple text, so we can copy it. This also adds to the frustration of getting `Authentication failed: The redirect_uri MUST match the registered callback URL for this application.` even if you copied the URL perfectly.

This is clearly AWX bug, cannot blame Firefox for it.
