### ISSUE TITLE
Hosts listing for Smart inventory

### ISSUE THREAD

**Issue by grimlokason** [ansible/awx#3324]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Using the Hosts button on smart inventory pages is not showing them like normal inventory while  using the magnifier on "Smart Host Filter" show them.

##### ENVIRONMENT
* AWX version: 3.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.6
* Operating System: Windows 7.
* Web Browser: firefox 65.0.1 64bits / Chrome Version 72.0.3626.109 (Build officiel) (64 bits)/ Chrome Version 72.0.3626.119 (Build officiel) (64 bits)

##### STEPS TO REPRODUCE

On INVENTORIES, choose a working Smart Inventory, : 
![2019-02-27 14_15_34-ansible awx _ ocb_redhat](https://user-images.githubusercontent.com/5112238/53492950-6b3c4f80-3a9a-11e9-8dc1-3c28abbe87a6.jpg)

Use the magnifier on "Smart Host Filter" and we should be able to see a list of hosts : 
![2019-02-27 14_16_54-ansible awx _ ocb_redhat](https://user-images.githubusercontent.com/5112238/53493070-c5d5ab80-3a9a-11e9-8c3b-e3117bbe22cd.jpg)

Click on the "Hosts" button here, and nothing happen  other than an "Working" on the bottom right : 
![2019-02-27 14_15_34-ansible awx _ ocb_redhat](https://user-images.githubusercontent.com/5112238/53492950-6b3c4f80-3a9a-11e9-8dc1-3c28abbe87a6.jpg)

##### EXPECTED RESULTS

Being able to see the hosts list like on a normal inventory

##### ACTUAL RESULTS

Nothing except the "working" gear on the bottom right

##### ADDITIONAL INFORMATION

Using the api to navigate to the hosts list is ok ( the smart inventory id was the 3 ) : 
https://awx_server/api/v2/inventories/3/hosts/

From the inspectorcode of firefox, the code of "hosts" button  on smart inventory is : 
```html
<div id="hosts_tab" class="Form-tab" ng-click="$state.go('inventories.editSmartInventory.hosts');" ng-class="{'is-selected' : $state.includes('inventories.editSmartInventory.hosts') || $state.includes('inventories.edit.hosts')}" translate="">Hosts</div>
```

While the one on normal inventory is : 
```html
<div id="hosts_tab" class="Form-tab is-selected" ng-click="$state.go('inventories.edit.hosts')" ng-class="{'is-selected' : $state.includes('inventories.edit.hosts')}" translate="">Hosts</div>
```

**Comment by grimlokason** [comment]
Some logs from docker logs awx_web : 
Click on hosts button on smart inventory with id 3 : 
```
[pid: 687|app: 0|req: 97/4978] 172.18.0.6 () {52 vars in 2423 bytes} [Wed Feb 27 14:15:55 2019] GET /api/v2/inventories/3/ => generated 2349 bytes in 132 msecs (HTTP/1.1 200) 8 headers in 252 bytes (1 switches on core 0)
172.18.0.6 - - [27/Feb/2019:14:15:55 +0000] "GET /api/v2/inventories/3/ HTTP/1.1" 200 2349 "https://awx_server/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0" "ip_source"

```

Same action on normal inventory with id 2 : 
```[pid: 687|app: 0|req: 94/4970] 172.18.0.6 () {52 vars in 2427 bytes} [Wed Feb 27 14:10:37 2019] GET /api/v2/inventories/2/ => generated 2316 bytes in 129 msecs (HTTP/1.1 200) 8 headers in 252 bytes (1 switches on core 0)
172.18.0.6 - - [27/Feb/2019:14:10:37 +0000] "GET /api/v2/inventories/2/ HTTP/1.1" 200 2316 "https://awx_server/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0" "ip_source"
[pid: 134|app: 0|req: 788/4971] 172.18.0.6 () {56 vars in 2509 bytes} [Wed Feb 27 14:10:37 2019] OPTIONS /api/v2/hosts/ => generated 11102 bytes in 148 msecs (HTTP/1.1 200) 8 headers in 239 bytes (1 switches on core 0)
172.18.0.6 - - [27/Feb/2019:14:10:37 +0000] "OPTIONS /api/v2/hosts/ HTTP/1.1" 200 11102 "https://awx_server/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0" "ip_source"
[pid: 132|app: 0|req: 921/4972] 172.18.0.6 () {52 vars in 2492 bytes} [Wed Feb 27 14:10:37 2019] GET /api/v2/inventories/2/hosts/?page_size=20&order_by=name => generated 42411 bytes in 583 msecs (HTTP/1.1 200) 8 headers in 239 bytes (1 switches on core 0)
172.18.0.6 - - [27/Feb/2019:14:10:37 +0000] "GET /api/v2/inventories/2/hosts/?page_size=20&order_by=name HTTP/1.1" 200 42411 "https://awx_server/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0" "ip_source"
[pid: 130|app: 0|req: 780/4973] 172.18.0.6 () {52 vars in 2492 bytes} [Wed Feb 27 14:10:37 2019] GET /api/v2/inventories/2/hosts/?page_size=20&order_by=name => generated 42411 bytes in 556 msecs (HTTP/1.1 200) 8 headers in 239 bytes (1 switches on core 0)
172.18.0.6 - - [27/Feb/2019:14:10:37 +0000] "GET /api/v2/inventories/2/hosts/?page_size=20&order_by=name HTTP/1.1" 200 42411 "https://awx_server/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0" "ip_source"
[pid: 687|app: 0|req: 95/4974] 172.18.0.6 () {56 vars in 2537 bytes} [Wed Feb 27 14:10:37 2019] OPTIONS /api/v2/inventories/2/hosts/ => generated 11234 bytes in 94 msecs (HTTP/1.1 200) 8 headers in 239 bytes (1 switches on core 0)
172.18.0.6 - - [27/Feb/2019:14:10:38 +0000] "OPTIONS /api/v2/inventories/2/hosts/ HTTP/1.1" 200 11234 "https://awx_server/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0" "ip_source"
```

**Comment by cedlerouge** [comment]
Hi,
I have the same probleme, the list of the hosts in the smart inventory doesn't appear. But when i go to the API, hosts appear : 
```

GET /api/v2/inventories/10/

HTTP 200 OK
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
X-API-Node: awx
X-API-Time: 0.136s

{
    "id": 10,
    "type": "inventory",
    "url": "/api/v2/inventories/10/",
    "related": {
        "named_url": "/api/v2/inventories/hosts_cerr++Default/",
        "created_by": "/api/v2/users/1/",
        "modified_by": "/api/v2/users/1/",
        "hosts": "/api/v2/inventories/10/hosts/",
        "groups": "/api/v2/inventories/10/groups/",
        "root_groups": "/api/v2/inventories/10/root_groups/",
        "variable_data": "/api/v2/inventories/10/variable_data/",
        "script": "/api/v2/inventories/10/script/",
        "tree": "/api/v2/inventories/10/tree/",
        "inventory_sources": "/api/v2/inventories/10/inventory_sources/",
        "update_inventory_sources": "/api/v2/inventories/10/update_inventory_sources/",
        "activity_stream": "/api/v2/inventories/10/activity_stream/",
        "job_templates": "/api/v2/inventories/10/job_templates/",
        "ad_hoc_commands": "/api/v2/inventories/10/ad_hoc_commands/",
        "access_list": "/api/v2/inventories/10/access_list/",
        "object_roles": "/api/v2/inventories/10/object_roles/",
        "instance_groups": "/api/v2/inventories/10/instance_groups/",
        "copy": "/api/v2/inventories/10/copy/",
        "organization": "/api/v2/organizations/1/"
    },
    ...
    "created": "2019-02-27T13:35:30.081849Z",
    "modified": "2019-03-04T11:22:31.078609Z",
    "name": "hosts_cerr",
    "description": "",
    "organization": 1,
    "kind": "smart",
    "host_filter": "groups__name=xxx",
    "variables": "",
    "has_active_failures": false,
    "total_hosts": 5,
    "hosts_with_active_failures": 0,
    "total_groups": 0,
    "groups_with_active_failures": 0,
    "has_inventory_sources": false,
    "total_inventory_sources": 0,
    "inventory_sources_with_failures": 0,
    "insights_credential": null,
    "pending_deletion": false
}



GET /api/v2/inventories/10/hosts/

HTTP 200 OK
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
X-API-Node: awx
X-API-Time: 0.072s

{
    "count": 5,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 1193,
            "type": "host",
            "url": "/api/v2/hosts/1193/",
            "related": {
                "variable_data": "/api/v2/hosts/1193/variable_data/",
....
```

**Comment by mabashian** [comment]
I've set up a smart inventory locally using the latest code on devel but haven't been able to reproduce this issue so I may need some help from those of you who can.  When this happens, can you take a look at the Firefox (you mentioned this browser so I assume it's what you use) developer tools and let me know if there are any errors int he console?  Also, if you could capture the network requests being _sent_ by the browser via the network tab that could be helpful as well.  The `working...` spinner is typically shown while the UI is interacting with the API.  A few things could be going wrong - there could be a JS error thrown somewhere before the network requests finish.  There could also be an issue with queuing up those requests.

**Comment by cedlerouge** [comment]
I tried with the branch 3.0.1 and the smart inventory display properly the list of hosts. I think this was a bug on 3.0.0 version.

**Comment by cedlerouge** [comment]
For information, when hosts wasn't displayed in smart inventory (awx 3.0.0), developer tools show only one http GET : 
![2019-03-05 13_07_42-awx_smart_inventory_bad](https://user-images.githubusercontent.com/4787982/53805158-aa124f80-3f49-11e9-8259-05fc7fa03322.png)

whereas with version 3.0.1 developer tools shows 4 requests 

![2019-03-05 13_07_42-awx_smart_inventory_good](https://user-images.githubusercontent.com/4787982/53805163-aed70380-3f49-11e9-8a6b-8da4d1af1954.png)
