### ISSUE TITLE
tox API test flake 

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#3325]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
##### SUMMARY
zuul API checks occasionally fail, but work on `recheck`.
https://ansible.softwarefactory-project.io/logs/94/3294/29dbcc15fa8553f86e7e144e3b9358e1c92ee4c6/check/tox-awx-api/104ab12/ara-report/

```Starting tools_rabbitmq_1  ... [32mdone[0m
[1B[2A[2K
Starting tools_postgres_1  ... [32mdone[0m
[2BError response from daemon: driver failed programming external connectivity on endpoint tools_awx_run_2 (e376f233645ebed9390535ecb8d2a68bb76635fb554d464faa9eeb321f80c997): Bind for 0.0.0.0:8888 failed: port is already allocated
Exception TypeError: "'NoneType' object is not callable" in <function _removeHandlerRef at 0x7fcdb7df7ed8> ignored
make: *** [docker-compose-runtest] Error 1
ERROR: InvocationError for command '/usr/bin/make docker-compose-runtest' (exited with code 2)
```
##### ENVIRONMENT
* AWX version: latest

##### STEPS TO REPRODUCE

Unknown exactly -- the PR zuul check that was run is here: 
https://github.com/ansible/awx/pull/3294

##### EXPECTED RESULTS

checks pass the first time.

##### ACTUAL RESULTS

checks pass the second time with no changes.

cc @chrismeyersfsu @rooftopcellist

**Comment by chrismeyersfsu** [comment]
Seems like there is a left-over tower container that is holding the wanted port. Ping @Spredzy @shanemcd @matburt 


`docker-compose run --rm` <-- relies on cleanup _after_ so if a run messes up, things can be left behind.
