### ISSUE TITLE
image build error trying to build awx 1.0.6.8

### ISSUE THREAD

**Issue by akcrisp** [ansible/awx#3328]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY
I am trying to redeploy my awx 1.0.6.8 awx instance - we are seeing though the following in the awx_sdist_builder container -

npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/angular-tz-extensions.git /root/.npm/_git-remotes/git-github-com-ansible-angular-tz-extensions-git-a87177b8: fatal: Unable to look up github.com (port 9418) (Name or service not known)
npm WARN addRemoteGit Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:199:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:920:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:351:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:509:12)
npm WARN addRemoteGit  ansible/timezone-js#0.4.14 resetting remote /root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-0-4-14-d653e9e1 because of error: { Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:199:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:920:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:351:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:509:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git config --get remote.origin.url' }
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/timezone-js.git /root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-0-4-14-d653e9e1: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-0-4-14-d653e9e1'...
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/ansible/timezone-js.git /root/.npm/_git-remotes/git-github-com-ansible-timezone-js-git-0-4-14-d653e9e1: fatal: Unable to look up github.com (port 9418) (Name or service not known)

Now this looks like a proxy issue maybe (we've not modified the the distribution since we last deployed it) can someone tell me where i find in the code where its doing the git://github.com and why its being done this way rather than https ?  Any reason why we can't change it to https in case git:// being blocked - is there any other known work arounds ?

##### ENVIRONMENT
* AWX version: 1.0.6.8
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.5.3.-1
* Operating System: rhel 7.6
* Web Browser: chrome

##### STEPS TO REPRODUCE
root@uklvapapp016p[PRD][installer] # ansible-playbook -i inventory install.yml

PLAY [Build and deploy AWX] **************************************************************************************************************************************************************************************************************

TASK [check_vars : include_tasks] ********************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [check_vars : include_tasks] ********************************************************************************************************************************************************************************************************
included: /root/awx/awx/installer/roles/check_vars/tasks/check_docker.yml for localhost

TASK [check_vars : postgres_data_dir should be defined] **********************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [check_vars : host_port should be defined] ******************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [image_build : Get Version from checkout if not provided] ***************************************************************************************************************************************************************************
changed: [localhost -> localhost]

TASK [image_build : Set global version if not provided] **********************************************************************************************************************************************************************************
ok: [localhost]

TASK [image_build : Verify awx-logos directory exists for official install] **************************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Copy logos for inclusion in sdist] ***********************************************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Set sdist file name] *************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [image_build : AWX Distribution] ****************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "awx-1.0.6.8.tar.gz"
}

TASK [image_build : Stat distribution file] **********************************************************************************************************************************************************************************************
ok: [localhost -> localhost]

TASK [image_build : Clean distribution] **************************************************************************************************************************************************************************************************
changed: [localhost -> localhost]

TASK [image_build : Build sdist builder image] *******************************************************************************************************************************************************************************************
changed: [localhost -> localhost]

TASK [image_build : Build AWX distribution using container] ******************************************************************************************************************************************************************************

(hangs on last step)

##### EXPECTED RESULTS

containers build and start 

##### ACTUAL RESULTS

its hanging building the container

**Comment by konkolorado** [comment]
This is probably a firewall issue.  You can configure git to use https instead of the native git by adding the following line to Dockerfile.sdist    
`RUN git config --global url."https://".insteadOf git://`

**Comment by matburt** [comment]
`fatal: Unable to look up github.com (port 9418) (Name or service not known)`

Your problem is that your system can't resolve github.com from DNS.

Also, you are using a fairly old version of AWX.
