### ISSUE TITLE
Inconsistency in API usage / result

### ISSUE THREAD

**Issue by EricVS** [ansible/awx#333]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
I use a template to populate AWX through the API (started before in Tower). Previously I had the option to specify a vault_password on a credential, now looking at AWX GUI they've been separated.
When I try to create a credential kind: ssh and provide vault_password the API complains that username is not a valid field for Vault. When I remove the vault_password field the SSH user gets created.
Now, when I want to add a credential kind: vault it doesn't accept it, I found out it needs to be kind: ssh and only provide the vault_password field/value pair. 

When querying the API the result are shown like that.

In short: the kind: vault doesn't get recognized and needs to be added for consistency.
##### ENVIRONMENT
* AWX version: 1.0.0.561
* AWX install method: docker on linux
* Ansible version:  2.4.0.0
* Operating System: CentOS 7.3
* Web Browser: Chrome

##### STEPS TO REPRODUCE
I use a custom Python script with requests to process the below:

tower_credentials:
    - name: "alpine-core git-credential"
      kind: "scm"
      description: "alpine-core git-credential"
      organization: "alpine-core"
      ssh_key_data: "~/.ssh/ansible"
      endpoint: "credentials/"

    - name: "alpine-core machine-credential"
      kind: "ssh"
      description: "alpine-core machine-credential"
      organization: "alpine-core"
      username: "ansible"
      ssh_key_data: "~/.ssh/ansible"
      vault_password: "XXXXXXXXXXXXXXX"
      endpoint: "credentials/"

##### EXPECTED RESULTS

Should create alpine-core git-credential and machine credential with above values

##### ACTUAL RESULTS

[*] creating tower_credentials; invalid response from HTTP: https://mdc-co-awx01.msgreen.dom/api/v1/credentials/ code: 400, BAD REQUEST: {"detail":["'username' is not a valid field for Vault"]}
invalid response from HTTP: https://mdc-co-awx01.msgreen.dom/api/v1/credentials/ code: 400, BAD REQUEST: {"detail":["'username' is not a valid field for Vault"]}

##### ADDITIONAL INFORMATION

What does work is this:

tower_credentials:
    - name: "alpine-core git-credential"
      kind: "scm"
      description: "alpine-core git-credential"
      organization: "alpine-core"
      ssh_key_data: "~/.ssh/ansible"
      endpoint: "credentials/"

    - name: "alpine-core machine-credential"
      kind: "ssh"
      description: "alpine-core machine-credential"
      organization: "alpine-core"
      username: "ansible"
      ssh_key_data: "~/.ssh/ansible"
      endpoint: "credentials/"

    - name: "alpine-core vault-credential"
      kind: "ssh" ================>>>>>>> should be kind vault
      description: "alpine-core vault-credential"
      organization: "alpine-core"
      vault_password: "XXXXXXXXXXXXXXXXXXXX"
      endpoint: "credentials/"

**Comment by matburt** [comment]
Tower is behind AWX by quite a bit... AWX tracks the development branch. The version of Tower that is about to release will work like this too where vault credentials have been separated out into their own credential.
