### ISSUE TITLE
Broken search documentation link

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#3337]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI
-Documentation

##### SUMMARY
The link in Inventories --> Host --> documentation seems to be a broken link.  

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: docker for mac
* Ansible version:  2.7.5
* Operating System: Mac OS 10.14.3 (Mojave)
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

1) Click on inventories
2) Click on Key next to the search bar (a box appears below the search)
3) click on the documentation link at the bottom of the box.

##### EXPECTED RESULTS

The link should take you to a documentation page to provide information about searches.  Probably here: https://docs.ansible.com/ansible-tower/latest/html/userguide/search_sort.html

##### ACTUAL RESULTS

The user gets a 404 Not Found error.

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/39280967/53577595-ee65b000-3b43-11e9-9bc4-d3b33c8bbcf5.png)

![image](https://user-images.githubusercontent.com/39280967/53577647-02111680-3b44-11e9-8354-5035084e8d8a.png)

**Comment by mabashian** [comment]
https://github.com/ansible/awx/blob/devel/awx/ui/client/src/shared/smart-search/smart-search.controller.js#L115 is where we'd want to start.  AWX should always be using `latest`.
