### ISSUE TITLE
Display failed job information, errors, etc. as output.

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#3339]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API (probably)
 - UI (yes)

##### SUMMARY
Currently, we display this type of information on the job details panel:

![job_error_details](https://user-images.githubusercontent.com/9753817/53586211-aea7c400-3b55-11e9-9fb0-ac8ea6529cdd.png)

This can be hard to read. It would be better if we represented these errors and tracebacks as if they were job output instead.

##### ADDITIONAL INFORMATION
A job can fail, stop running, or unexpectedly not start for a variety of reasons. In the API, we send this information using several different fields depending on context:

- `job.license_error` (bool):
to indicate a license error of some kind
- `job.org_host_limit_error` (string):
to indicate an error due to hitting the host limit for an organization (see [#3174](https://github.com/ansible/awx/pull/3174/files#diff-a000eec9bcdc95dd30b2269e9e3d4c76R239))
- `job.result_traceback` (string):
for issues that caused a traceback prior to a job run.
- `job.job_explanation` ([sometimes a string](https://github.com/ansible/awx/blob/devel/awx/main/models/unified_jobs.py#L1228), sometimes a [part-string, part-stringified-json-hybrid](https://github.com/ansible/awx/blob/devel/awx/main/tests/unit/models/test_inventory.py#L35) that needs to be [split and parsed.](https://github.com/ansible/awx/blob/devel/awx/ui/client/features/output/details.component.js#L396-#L401)):
for other occurrences, like failed inventory syncs.

The work here would probably entail:
- API side, see if it's feasible to represent this information in the job details in a more consolidated or consistent way. This isn't strictly necessary - All of the information is technically there, but it could be helpful for the ui changes that would follow.
- Remove code that shows this information from [the job details panel component](https://github.com/ansible/awx/blob/devel/awx/ui/client/features/output/details.component.js)
- Add a function to the [top-level job output controller](https://github.com/ansible/awx/blob/devel/awx/ui/client/features/output/index.controller.js) that knows how to take information from these fields when it exists (e.g: `resource.model.get('result_traceback')` and generate a 'fake' job event, complete with ansi stdout fields, counters, etc, which can be pushed into the `render` service and displayed as if it were job output. 
 - Use this function on initialization for finished jobs and also with our `sync` function that we invoke when jobs finish running.

**Comment by unlikelyzero** [comment]
@jakemcdermott was this done as a part of the latest job result output work?
