### ISSUE TITLE
Unable to add both SSH and Vault credentials through API

### ISSUE THREAD

**Issue by EricVS** [ansible/awx#334]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
With the split of SSH credential and Vault credential we need to be able to add multiple credentials through API. This is not supported at the moment.

##### ENVIRONMENT
* AWX version: 1.0.0.561
* AWX install method: docker on linux
* Ansible version:  2.4.0.0
* Operating System: CentOS 7.3
* Web Browser: Chrome

##### STEPS TO REPRODUCE

I use a custom Python script with requests to process the below:

  tower_job_templates:
      - name: "alpine-core - deploy"
        job_type: run
        inventory: "alpine-core"
        project: "master-alpine-core"
        machine_credential: "alpine-core machine-credential"
        playbook: playbooks/alpine_core/deploy.yml
        extra_vars: "env: '{{ ansible_local.local_facts.env }}'"
        survey_enabled: yes
        allow_simultaneous: yes
        endpoint: "job_templates/"

##### EXPECTED RESULTS

Template created with both Machine and Vault credential added.

##### ACTUAL RESULTS

[*] creating tower_job_templates; invalid response from HTTP: https://mdc-co-awx01.msgreen.dom/api/v1/job_templates/ code: 400, BAD REQUEST: {"credential":["Must either set a default value or ask to promp
t on launch."]}
invalid response from HTTP: https://mdc-co-awx01.msgreen.dom/api/v1/job_templates/ code: 400, BAD REQUEST: {"credential":["Must either set a default value or ask to prompt on launch."]}

**Comment by AlanCoding** [comment]
This should be filed in the Ansible repo, not AWX. You might find it helpful to use the Github issue moves referenced in their docs:

http://docs.ansible.com/ansible/latest/dev_guide/repomerge.html#move-issues-and-prs-to-new-repo

Example of a previous issue on the tower modules:

https://github.com/ansible/ansible/issues/24547
