### ISSUE TITLE
Create Playbook

### ISSUE THREAD

**Issue by seahurt** [ansible/awx#3344]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY

Can I create a playbook through the web page other than pulling from git or reading from local?

##### ADDITIONAL INFORMATION
I am new to ansible and ansible tower. I cannot find the page to create playbook on the web. Is that already possible ? Or this function is just not necessary?

**Comment by wenottingham** [comment]
No. As a feature, this would encourage behaviors we want to discourage - any usage at scale is based on usage of source control.

(Also, this is a better question for the mailing list.)
