### ISSUE TITLE
Job start notification

### ISSUE THREAD

**Issue by cdvv7788** [ansible/awx#3347]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
I would like to know (be notified) when a new job is started. This feature is important because normally there are more than 1 user, and knowing what is happening with relevant projects is a topic of interest.

**Comment by wenottingham** [comment]
lineitem in https://github.com/ansible/awx/issues/79, closing.
