### ISSUE TITLE
Cannot filter by organization roles by 'name'

### ISSUE THREAD

**Issue by yzhivkov** [ansible/awx#3350]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Trying to filter nested model such as Role under Organization would return 

##### ENVIRONMENT
* AWX version: 2.1.2
* AWX install method: docker for mac
* Ansible version:  2.6.3
* Operating System: Mac OS
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Try performing the following API call:
```
http://localhost/api/v2/organizations/1/object_roles/?name=Execute
```
##### EXPECTED RESULTS

A list that only contains the role by the name Execute is to be returned

##### ACTUAL RESULTS

The following error (error code 400):
```
{
    "detail": "Role has no field named 'name'"
}
```

**Comment by AlanCoding** [comment]
See the OPTIONS

https://github.com/ansible/awx/blob/devel/awx/main/models/rbac.py#L142

These are the database fields - which are the fields that you can filter by. If a field is not a database field, or is not filterable for any other reason the OPTIONS will give you `"filterable": false` for that field info.

What you want is `?role_field=execute_role`

Other people already have built clients using this contract, so we can't change it easily.
