### ISSUE TITLE
Need help to run playbook on version 2.7

### ISSUE THREAD

**Issue by leninbabuk** [ansible/awx#3351]
Hi ,
I am able run adhoc commands on ansible without any errors, however,  when running playbooks getting the following errors on version 2.7

![image](https://user-images.githubusercontent.com/38011563/53689493-61a63680-3d7d-11e9-9327-a1f7dce01dcb.png)
![image](https://user-images.githubusercontent.com/38011563/53689495-6d91f880-3d7d-11e9-9c7e-20e6b3cf3365.png)
TASK [creating a file] ***************************************************************************************************************
fatal: [ubuntu1]: FAILED! => {"changed": false, "msg": "There was an issue creating /home/ansible/testfile.txt as requested: [Errno 13] Permission denied: '/home/ansible/testfile.txt'", "path": "/home/ansible/testfile.txt", "state": "absent"}
fatal: [ubuntu2]: FAILED! => {"changed": false, "msg": "There was an issue creating /home/ansible as requested: [Errno 13] Permission denied: '/home/ansible'", "path": "/home/ansible/testfile.txt", "state": "absent"}
 [WARNING]: Could not create retry file '/etc/ansible/test.retry'.         [Errno 13] Permission denied: u'/etc/ansible/test.retry'

PLAY RECAP ***************************************************************************************************************************
ubuntu1                    : ok=0    changed=0    unreachable=0    failed=1
ubuntu2                    : ok=0    changed=0    unreachable=0    failed=1

The following is the hosts file

packt@dnsmasq:/etc/ansible$ cat hosts
[all]
ubuntu1 ansible_sudo_user=packt ansible_sudo_pass=password
ubuntu2

**Comment by wenottingham** [comment]
This repo is for AWX, a REST api and web console for Ansible. You're just running Ansible itself. 

The issue tracker for ansible is at https://github.com/ansible/ansible/, however this looks like a user issue that is better served on the mailing list (https://groups.google.com/forum/#!forum/ansible-project).
