### ISSUE TITLE
Upload YAML extra-vars file when launching job

### ISSUE THREAD

**Issue by jfcgaspar** [ansible/awx#3353]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
When launching a job template, AWX allows extra variables to be prompted at launch time, so that users can set specific extra variables at launch time. This is currently done by writing out in YAML or JSON format the variables in a text box.
Instead of this method, would like to be able to upload a YAML file containing those extra variables in YAML format instead of having to copy+paste its contents into the currently available textbox at launch time.
Alternatively, instead of uploading, could also fetch the YAML file from some collaborative repository.

##### ADDITIONAL INFORMATION

To contextualize, I want to convert an Ansible playbook that uses var_prompt to ask the user for a local input YAML file containing extra variables that is then read via an include_vars task. In this case the file is in the local directory.

The idea is to make this possible in a AWX job template :

  vars_prompt:
    - name: input_file
      prompt: Input YML File
      private: no

  tasks:
    - name: "READ INPUT VARS"
      include_vars:
        file: "{{ input_file }}"

Note: the input YAML file is dynamically created, with different contents and different name.

**Comment by wenottingham** [comment]
For prompting, we use surveys ... that is unlikely to change.

Further survey types are tracked in https://github.com/ansible/awx/issues/553.

What are you doing that you expect users to have a full YAML file of variables rather than something with more guardrails?

**Comment by jfcgaspar** [comment]
This is for device validation, where the list of dynamic validation commands to run is passed via input YAML file.
Commands are dynamically generated into a YAML file which is then passed to the playbook as an input.

**Comment by wenottingham** [comment]
That sounds better as a file upload survey type than direct file injection into extra_vars. That is covered in #553.
