### ISSUE TITLE
UX Enhancement: Add Sort Dropdown to List Toolbar

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#3355]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### UX Behavior
- Sort dropdown on the new lists toolbar.
- Default dropdown option is set when list is initialized.
- Users can set a new sort option by selecting from the dropdown options.
- On Pagination - Persist sort option 
- On Navigation away from list - Reset sort option

##### QE Verification for Sorting Lists:

- Check if sorting persists when using pagination
- Check if sorting will be back to the default value when navigating to another page and navigating back
- Check if the expected sorting options are provided and if they sort properly
- Check if the default sorting option is presented on the options list
- Checking if sorting dropdown is present on the expected lists

##### MOCKUP
<img width="288" alt="screen shot 2019-03-04 at 11 47 13 am" src="https://user-images.githubusercontent.com/15881645/53748411-4cabcf00-3e73-11e9-8616-c703c034b5cc.png">

##### LISTS
| Location                                     | Sort By                                                            | PR |
|----------------------------------------------|--------------------------------------------------------------------|---------|
| Jobs<br>My View / My Jobs & All Jobs<br>Inventory / Completed Jobs<br>Host / Completed Jobs<br>Instance Group / Jobs<br>Instance / Jobs<br>Template / Completed Jobs<br>Workflow Template / Completed Jobs   | Default: Finish Time<br>Start Time<br> Name (Ascending)<br> Name (Descending)|https://github.com/ansible/awx/pull/3367|
| Templates<br>My View / Templates<br>Organization / Templates<br>Project / Templates| Default: Name (Ascending)<br> Name (Descending)                    |https://github.com/ansible/awx/pull/3576|
| Projects                                     | Default: Name (Ascending)<br> Name (Descending)                    |https://github.com/ansible/awx/pull/3356|
| Applications                                 | Default: Name (Ascending)<br> Name (Descending)                    |https://github.com/ansible/awx/pull/3401|
| Applications / Tokens(Users)                 | Default: User (Ascending)<br> User (Descending)                    |https://github.com/ansible/awx/pull/3453|
| Users / Tokens                               | Default: Application (Ascending)<br> Application (Descending)      |https://github.com/ansible/awx/pull/3458|
| Instance Groups                              | Default: Name (Ascending)<br> Name (Descending)                    |https://github.com/ansible/awx/pull/3408|
| Instance Groups / Instances                  | Default: Name (Ascending)<br> Name (Descending)                    |https://github.com/ansible/awx/pull/3440|
| Instance Groups / Instances / Instance Modal | Default: Name (Ascending)<br> Name (Descending)                    |https://github.com/ansible/awx/pull/3502|

**Comment by unlikelyzero** [comment]
Because (at)Elyezer is out on this one, @dsesami and myself will be tackling this one.

**Comment by unlikelyzero** [comment]
assigning to @elyezer to close out as it is his 3.5 Feature

**Comment by elyezer** [comment]
I've checked all lists that the sorting feature was added and they are working as expected.

Thank you
