### ISSUE TITLE
Launch from jt/wfjt form doesn't show extra vars codemirror

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#3358]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
<img width="1459" alt="screen shot 2019-03-04 at 4 49 08 pm" src="https://user-images.githubusercontent.com/9889020/53765278-8db8d900-3e9d-11e9-978b-68d13edf635e.png">

##### STEPS TO REPRODUCE
Create a JT that prompts for extra vars on launch
While remaining on the JT form click the blue Launch button

##### EXPECTED RESULTS
Extra vars codemirror to be shown on OTHER PROMPTS tab

##### ACTUAL RESULTS
No codemirror (see screenshot above)

##### ADDITIONAL INFORMATION
I suspect this might have to do element id's.  It's possible that the extra var textarea shares the same id as the form's extra var textarea

**Comment by unlikelyzero** [comment]
@mabashian any idea when this was introduced?

**Comment by AlexSCorey** [comment]
Issue cannot be reproduced.
