### ISSUE TITLE
Allow for job template admin to cancel scheduled jobs/workflows.

### ISSUE THREAD

**Issue by gamuniz** [ansible/awx#336]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

Currently the permissions structure does not allow for job template admins to cancel a scheduled job. This can cause issues if a job or workflow gets stuck.

##### ENVIRONMENT
AWX version: 3.1.4
Ansible version: 2.4
Operating System: RHEL 7
Web Browser: Chrome

##### STEPS TO REPRODUCE
1. schedule a job or workflow as any user
2. attempt to cancel the job with a non-system admin user

##### EXPECTED RESULTS

Expectation is that admin on job template/workflow should allow for these scheduled jobs to be canceled.

##### ACTUAL RESULTS

Receive a 403 access denied on the UI/API when trying to cancel a scheduled job.

**Comment by AlanCoding** [comment]
Actually, I think we allow this for jobs. However, we do not allow it for workflow jobs. Compare:

jobs:

```python
    def can_cancel(self, obj):
        if not obj.can_cancel:
            return False
        # Delete access allows org admins to stop running jobs
        if self.user == obj.created_by or self.can_delete(obj):
            return True
        return obj.job_template is not None and self.user in obj.job_template.admin_role
```

workflow jobs:

```python
    def can_cancel(self, obj):
        if not obj.can_cancel:
            return False
        return self.can_delete(obj) or self.user == obj.created_by
```

**Comment by AlanCoding** [comment]
Fix is in `devel`
