### ISSUE TITLE
Dashboard UI - In Recently Used Template frame - Name overlapping with Activity

### ISSUE THREAD

**Issue by ryan012880** [ansible/awx#3361]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Dashboard UI - overlapping template name on activity status view

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: docker on linux
* Ansible version:  2.7.8
* Operating System: RHEL
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Create a template with long name
2. Run the template so it shows in the Dashboard RECENTLY USED TEMPLATES frame

##### EXPECTED RESULTS
In AWX 2.1.2 this didn't occur, it would display properly.

##### ACTUAL RESULTS

See: demo_patching.demoservers

<img width="606" alt="screen shot 2019-03-05 at 1 37 11 pm" src="https://user-images.githubusercontent.com/10410660/53783396-5c4b1680-3f4c-11e9-8e18-2aa6b4f82de4.png">

**Comment by AlexSCorey** [comment]
This issue was addressed by PR https://github.com/ansible/awx/pull/3417
