### ISSUE TITLE
Permission for Inventory Scripts

### ISSUE THREAD

**Issue by shen3lu4** [ansible/awx#3364]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
Try to assign a user or a team to create/update Inventory Scripts. AWX doesn't seem to provide that option.

##### ENVIRONMENT
* AWX version: 2.1.1
* AWX install method: Kubernetes
* Ansible version:  2.7.2
* Operating System: Centos 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Login as admin. Click on a Team and go to Permission tab. Click on the + sign to add permissions but there is no option for Inventory Scripts. 

##### EXPECTED RESULTS

There should be an option to grant a Team or a user Inventory Script Admin role.

##### ACTUAL RESULTS

Only users as system admin or org Admin can create/update Inventory scripts. There is no Admin role at Team level nor Inventory Scripts Admin role.

**Comment by konkolorado** [comment]
This is still an issue on AWX version 3.0.1

**Comment by wenottingham** [comment]
Yes, this is not a thing that exists currently.

**Comment by mabashian** [comment]
Inventory scripts are gone
