### ISSUE TITLE
Editing workflow node link throws 400 error

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#3366]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI
(not sure which is to blame)

##### SUMMARY
When changing a link from one type to another (ex. change always to on success) the api throws a 400 error on save.  It's unclear to me whether this is an issue with the UI code or with the API code.

![workflow_link_error](https://user-images.githubusercontent.com/9889020/53828400-8cde8080-3f4b-11e9-8bbb-03d0b5e38b5c.gif)

##### ENVIRONMENT
* AWX version: latest devel

##### STEPS TO REPRODUCE
Create a workflow
Add some nodes in serial
Save
Open Visualizer again
Change one of the link types
Attempt to save

##### EXPECTED RESULTS
Successful save

##### ACTUAL RESULTS
400 error from API

```
POST https://127.0.0.1:3000/api/v2/workflow_job_template_nodes/3/success_nodes/ 400
Possibly unhandled rejection: {"data":{"Error":"Relationship not allowed."},"status":400,"config":{...bunch of stuff in here}
```

**Comment by ryanpetrello** [comment]
@mabashian is this still an issue, or has it been resolved?

**Comment by unlikelyzero** [comment]
We need to know if this is still a problem with the new workflow visualizer

**Comment by kdelee** [comment]
Until any changes to the API have been made, I'm removing the component:api label -- because right now there is no clear change/fix to verify from the api side

**Comment by unlikelyzero** [comment]
@akus062381 please retest this and note if we're missing any testability.

**Comment by akus062381** [comment]
opening an issue, testability needs to be added.
https://github.com/ansible/awx/issues/9667

**Comment by akus062381** [comment]
I have verified that this issue has been resolved.
