### ISSUE TITLE
Paginate directive doesn't update URL state params

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#3368]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
The URL params don't accurately reflect the page filter or page location. 

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: docker for mac
* Ansible version:  2.7.5

##### STEPS TO REPRODUCE
1. Navigate to a list with 2 or more pages
2. Filter the list using the page_size dropdown
3. Navigate to different page via the paginate controls 
4. Watch URL 

##### EXPECTED RESULTS
URL params update on page filter and page change

##### ACTUAL RESULTS
URL params don't reflect current list state

##### ADDITIONAL INFORMATION
Note: This occurs in the new and old lists

![inv paginate params](https://user-images.githubusercontent.com/15881645/53836339-c324fb80-3f5d-11e9-80d5-a2cb611833eb.gif)

**Comment by ryanpetrello** [comment]
@marshmalien @unlikelyzero is this still an issue, or has it been resolved?
