### ISSUE TITLE
Creating new application displays error even though save is successful

### ISSUE THREAD

**Issue by keithjgrant** [ansible/awx#3374]
There seems to be an issue with the params passed to the alert() dialog when saving. This occurs when the API returns a 201. The save seems to be successful

<img width="1370" alt="screen shot 2019-03-06 at 12 37 29 pm" src="https://user-images.githubusercontent.com/1342624/53901933-1a82a480-400e-11e9-8301-6798f5af99ff.png">

_Originally posted by @jlmitch5 in https://github.com/ansible/awx/issues/2939#issuecomment-470206553_

**Comment by unlikelyzero** [comment]
Verified:

- New Application Type can be created with 'Resource owner password-based' 'Redirect URIS' as the local machine's URI, 'Client Type' Public

**Comment by rooftopcellist** [comment]
Duplicate issue: https://github.com/ansible/awx/issues/3399
