### ISSUE TITLE
A user with WFJT 'execute' permissions triggers an unsaved changes modal after selecting a node in the WFViz and then attempting to close the WFViz

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#3378]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
A user with WFJT 'execute' permissions triggers an unsaved changes modal after selecting a node in the WFViz and then attempting to close the WFViz

##### ENVIRONMENT
* AWX version: 3.0.1

##### STEPS TO REPRODUCE
1. Give a user WFJT 'Execute' Permission
2. Login as that user and open the WFViz for that WFJT from step 1
3. Click on any node as if to edit it
4. Attempt to close the WFViz
Note: Unsaved Changes modal is triggered

##### EXPECTED RESULTS

A user with no edit permissions should see no edit dialogues

##### ACTUAL RESULTS

A user with execute only permissions sees an edit-related modal

##### ADDITIONAL INFORMATION

After talking with @mabashian , we believe that this should not be prioritized to be fixed in any reasonable timeframe as the work necessary to solve this edgecase will add unnecessary complexity.

**Comment by mabashian** [comment]
An important distinction here:  The node form _must be open_ when you click to close the visualizer in order for the save changes modal to be shown.  If you close the node form first, the modal will not be shown.

**Comment by dsesami** [comment]
This works correctly now -- the modal does not appear either way when either selecting a node or making any attempts to manipulate the WF (as the user doesn't have permission)
