### ISSUE TITLE
Azure PostgresSQL - error on startup - no such role

### ISSUE THREAD

**Issue by Aylard** [ansible/awx#3380]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
I have Azure PostgreSQL service which requires login as user@host, but roles in PostgresSQL are just "user" without "@host", which cause "no such role error" 

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: docker on linux
* Ansible version:  2.7.8
* Operating System: RHEL7
* Web Browser: n/a

##### STEPS TO REPRODUCE
Create Azure Database for PostgreSQL , change variables in inventory, run install yml  and see the logs of awx_task

##### EXPECTED RESULTS
not having an error 

##### ACTUAL RESULTS

```
Using /etc/ansible/ansible.cfg as config file
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ProgrammingError: role "user@host" does not exist
127.0.0.1 | FAILED! => {
    "changed": false,
    "msg": "Database query failed: role \"user@host\" does not exist\n"
}
Operations to perform:
  Apply all migrations: auth, conf, contenttypes, main, oauth2_provider, sessions, sites, social_django, sso, taggit
...
```

**Comment by Dagon-** [comment]
Sounds like you haven't correctly created the role in postgres.

We're using azure postgres with awx (and a number of other applications). Logging in as role@host works as expected.

**Comment by Aylard** [comment]
@Dagon- thanks for reply.
AWX is starting and working normally, but nevertheless this line in startup log exist and I wonder why :)
