### ISSUE TITLE
Allow setting venv for inventory updates on inventory source

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#3387]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

Allow venv to be set on inventory source and use default of the ansible venv we ship.

##### ADDITIONAL INFORMATION
This is my idea to resolve a usability issue that has come to my attention. If users are using the Organization level VENV, we may put them at risk of breaking their inventory updates.

* If they use ansible 2.3 in this venv, which we still allow in custom venvs, their inventory updates will be completely broken because we call `ansible-inventory` which does not exist in this version

* They may be used to letting their jobs run in a special venv that they love but does not provide necessary dependencies that the inventory sources they rely on need. Their inventory updates may start blowing up/breaking and they be confused as to why it used to work, and it may not be obvious to them that NOW their inventory updates are happening in the venv set at the org level and they are missing dependencies

Ideally this would be same workflow as is present on Job Templates.
![screenshot from 2019-03-07 14-18-06](https://user-images.githubusercontent.com/29239279/53982829-e37ec280-40e3-11e9-99dc-23dcffc487df.png)

**Comment by wenottingham** [comment]
I don't think setting a venv on the inventory source is really needed beyond a "use system venv instead" checkbox?

**Comment by AlanCoding** [comment]
> I don't think setting a venv on the inventory source is really needed beyond a "use system venv instead" checkbox?

A venv setting is what matches the current pattern. There is a very strong precedent set for this.

https://github.com/ansible/awx/blob/928de6127bf360f14f20ec344783f616b4439646/awx/main/models/jobs.py#L583-L593

Job templates get custom venv from itself, then other stuff, then organization, in that precedence order. This is also true for projects, and it is very clearly documented. If inventory sources had a checkbox instead, that would be super surprising for anyone familiar with how JTs and projects operate.

**Comment by wenottingham** [comment]
While I understand that conceptually, this feels like exposing way way too much of the warts of the system, given that custom venv + built-in sources is almost certainly a bad idea.

**Comment by AlanCoding** [comment]
I get better where you're coming from now.

> given that custom venv + built-in sources is almost certainly a bad idea.

Yikes, to be honest this was completely the intent. That is how we are using it now for our own testing purposes. Beyond that, I don't expect that every Ansible release will have every inventory plugin bug free. I am far too familiar with the process of getting tracebacks from the inventory plugins and then going bug hunting. I fully expect that switching the venv will be needed and used for issue remediation.

Counter-proposal:

What if we added `custom_virtualenv` field to inventory sources:

 - as an exception, inventory updates will never use `inventory.organization.custom_virutalenv`
   - I take back what I said earlier, this might actually be congruent with project updates
 - if `source_project` has a virtualenv, and inventory source doesn't have one, source_project's will be used
 - if inventory source has a virtualenv, that will always be used
 - naturally, if neither inventory source or source project has a virtualenv, then default venv is used

This feels more explicit and natural to me.

It would also avoid mucking with any existing official-source-type inventory sources.

**Comment by wenottingham** [comment]
Yeah, I can see that. My concern is that built-in source + inheritied custom venv is an accident waiting to happen.

**Comment by wwitzel3** [comment]
I agree with what @AlanCoding is proposing above.

**Comment by kdelee** [comment]
I'm for this most recent proposal!

Sounds like we still need the drop down on the UI
