### ISSUE TITLE
[RFE] Need Two Separate Options In SETTINGS > SYSTEM for Org Admins To Manage Users And Teams 

### ISSUE THREAD

**Issue by Ompragash** [ansible/awx#3390]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

Currently if we traverse to SETTINGS > SYSTEM we have a option `ORGANIZATION ADMINS CAN MANAGE USERS AND TEAMS` through which an Org Admin can manage both Users and Teams if turned On. But it'll be nice if we have two separate options `ORGANIZATION ADMINS CAN MANAGE USERS` and `ORGANIZATION ADMINS CAN MANAGE TEAMS` so that it'll easy to delegate permission to org Admin for user/team management.

**Comment by wenottingham** [comment]
Why is this needed? What is the use case for only managing one or the other?

**Comment by rsevilla87** [comment]
@wenottingham  This RFE is intented to allow an organization admin to manage teams (create/delete teams and associate/disassociate users from teams) but not to give him permissions to create local users in Tower/AWX.

**Comment by wenottingham** [comment]
What account source are you using that you require pulling all users for it but can't map teams/orgs?

**Comment by rsevilla87** [comment]
We're using LDAP, using internal groups instead of LDAP groups

**Comment by shanemcd** [comment]
Closing due to lack of interest in this.
