### ISSUE TITLE
Authentication credentials were not provided. To establish a login session, visit /api/login/

### ISSUE THREAD

**Issue by akamalov** [ansible/awx#3393]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 
##### SUMMARY
Azure Authentication integrated environment. Trying to authenticate to obtain token. Error: detail:

```Authentication credentials were not provided. To establish a login session, visit /api/login/```

I am referencing document - https://docs.ansible.com/ansible-tower/latest/html/administration/oauth2_token_auth.html#ag-use-oauth-pat

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: docker on linux
* Ansible version:  2.7.8
* Operating System: CentOS7.4
* Web Browser: Chrome 70.0.x
* cURL: 7.63.0

##### STEPS TO REPRODUCE

* Deploy AWX in Azure
* Integrate with Azure AD
* Change System Settings to ```Allow External Users To Create Oath2 Tokens```
* Login to AWX using Azure AD credentials to confirm that it works
* Log out and re-login with ```admin``` credentials
* Create organization
* Add newly-autocreated (Azure AD) user to organization

Try to login using Azure AD credentials using cURL:
```
curl -ku <AzureAD UserName>:'<Azure AD Password>' -H "Content-Type: application/json" -X POST -d '{"description":"Tower CLI", "application":null, "scope":"write"}' http://192.168.2.37/api/v2/users/1/personal_tokens/ | jq .

{"detail":"Authentication credentials were not provided. To establish a login session, visit /api/login/."}% 
```
##### EXPECTED RESULTS

I expect a token to be returned

##### ACTUAL RESULTS
```
{"detail":"Authentication credentials were not provided. To establish a login session, visit /api/login/."}% 
```

**Comment by ryanpetrello** [comment]
@akamalov,

Several of AWX's supported enterprise authentication methods (like Azure/Google/Github) don't support direct authentication to AWX via HTTP basic auth (it just isn't how it works) - rather, they're intended to be used via a third party OAuth2.0/OpenID login that directs you to log into your Azure account (generally, in browser, or via some 3rd party SDK) and passes metadata _back_ to AWX via a callback so a valid session can be established.

If you enable Azure and visit the AWX login screen, you'll notice that a windows icon shows up which initiates the single sign on mechanism:

![image](https://user-images.githubusercontent.com/214912/54045796-87c63f00-41a0-11e9-935d-700ed2705814.png)

Clicking this will send you to Azure's login screen:

https://login.microsoftonline.com/common/oauth2/authorize?client_id=some_client&redirect_uri=https://awx.example.org/sso/complete/azuread-oauth2/&state=some_hash&response_type=code&scope=openid+profile+user_impersonation

![image](https://user-images.githubusercontent.com/214912/54045829-99a7e200-41a0-11e9-8b6a-ce062a58639c.png)

...where you provide your Microsoft login and are sent *back* to AWX.

If you wanted to do this, you **could** make a series of requests to the `/sso/` API endpoint in AWX and Azure (the same series of requests your web browser would make in the screenshots above), and work out the details of interacting with Azure's authentication endpoint.  But that's an exercise left to the reader.

If you *don't* want to automate all of this, a more reasonable approach might be to log into AWX in-browser and generate an initial OAuth2 token yourself (and use that for subsequent AWX API requests).

**Comment by akamalov** [comment]
Thanks so much @ryanpetrello!!

**Comment by adurenshi** [comment]
Authorization: Bearer:$token

**Comment by ryanpetrello** [comment]
@adurenshi you want a space after `Bearer`, not a colon:

`Authorization: Bearer $token`

**Comment by adurenshi** [comment]
@ryanpetrello I've tried it. Colon: is OK.
