### ISSUE TITLE
Cannot delete group if its name is too long

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#3395]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
If my group has too many non-space characters, I cannot delete the group in the UI

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: docker for mac
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

name group 1234567890

copy + paste 10 times

copy + paste result from prior step 4 times, 400 characters

![Screen Shot 2019-03-08 at 2 37 01 PM](https://user-images.githubusercontent.com/1385596/54051417-c9aab180-41af-11e9-8ae6-020c2b03da76.png)

##### EXPECTED RESULTS

🗑 

##### ACTUAL RESULTS

🚫 🗑

**Comment by jakemcdermott** [comment]
What's the actual use case here?

**Comment by jakemcdermott** [comment]
👍 I can see how this can be a problem. This is not about repeat api-backed copies, which would also explode the character length of a resource name.

**Comment by AlanCoding** [comment]
I hit it because I was importing inventory and using the inventory plugin constructed groups. Granted, I got it wrong, so it merged the names of many entries into 1 entry. Nonetheless, it shows how someone can _unintentionally_ hit this, because that's exactly what I did.

**Comment by jakemcdermott** [comment]
yep 👍 makes sense. we should fix it.
