### ISSUE TITLE
Receiving 401 Unauthorized when Trying to List Inventory via REST call

### ISSUE THREAD

**Issue by akamalov** [ansible/awx#3396]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 
##### SUMMARY

Trying to list inventory using cURL + token but getting 401 error

```curl: (22) The requested URL returned error: 401 Unauthorized```

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: docker on linux
* Ansible version:  2.7.8
* Operating System: CentOS7.4
* Web Browser: Chrome 70.0.x
* cURL: 7.63.0

##### STEPS TO REPRODUCE

* Deploy AWX in Azure
* Integrate with Azure AD
* Change System Settings to ```Allow External Users To Create Oath2 Tokens```
* Login to AWX using Azure AD credentials to confirm that it works
* Log out and re-login with ```admin``` credentials
* Create organization
* Add newly-autocreated (Azure AD) user to organization
* Assign permissions: "project-admin" to user (me)
* Login as myself
* Generate token
* In terminal, export token (i.e., ```export token=XXXXXX```)

Try to obtain inventories using cURL:
```
curl -H "Authorization:Token $token" -f -k -H "content-Type: application/json" -X GET http://192.168.2.37/api/v2/inventories/  | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 401 Unauthorized

```
##### EXPECTED RESULTS

* User is part of organization
* User has ```project admin``` privileges
* User using AWX-generated token
* I expected an inventory list to be returned, but received 401 instead.

##### ACTUAL RESULTS
```
 curl: (22) The requested URL returned error: 401 Unauthorized
```

**Comment by ryanpetrello** [comment]
@akamalov,

Try:

`Authorization: Bearer $token`

**Comment by akamalov** [comment]
@ryanpetrello, you're awesome, and it's official. Don't deny it... Thank You!!

**Comment by adurenshi** [comment]
Authorization: Bearer:<your token>

**Comment by adurenshi** [comment]
Authorization: Bearer:<your token>

**Comment by adurenshi** [comment]
Authorization: Bearer:$token
