### ISSUE TITLE
Restrict user from login within GUI

### ISSUE THREAD

**Issue by jota2016** [ansible/awx#3398]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
 - GUI

##### SUMMARY
Unable to restrict login from UI

##### ENVIRONMENT
* AWX version: 3.0.1
* Ansible version:  2.7.8
* Operating System: CentOS 7.6

##### STEPS TO REPRODUCE
I have created a new regular user with execution permissions over a template. From a Jenkins server, I can launch the playbook of the template succesfully, but I need to restrict that user from logging into AWK GUI.

##### EXPECTED RESULTS
User can exec template but cannot login within GUI.

**Comment by wenottingham** [comment]
This is what the OAuth token support is for.

**Comment by jota2016** [comment]
Thanks **wenottingham**.
I will investigate in that way.
