### ISSUE TITLE
Undefined status on token & app creation

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/awx#3399]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY
When creating a resource in the UI that has a pop-up modal after creation, the resource is created, but the modal does not display correctly.  This is an issue for Application and Token creation because the pop up modal shows information that the user will not be able to get later (ie: token value and client_secret).  

![image](https://user-images.githubusercontent.com/11698892/54126822-d103d200-43de-11e9-9207-6ac0e57f225c.png)

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE
Note: This only happens the first time you create a resource in the UI, or if you do a hard refresh of your browser cache.  My guess is that this is linked to the userLoggedIn cookie.  

1. Use Developer tools to Hard Refresh the browser cache
2. Create an Application or Token in the UI

##### EXPECTED RESULTS

See the correct pop-up modal which displays the token value or client secret.

##### ACTUAL RESULTS

See the incorrect pop-up modal.

**Comment by unlikelyzero** [comment]
@rooftopcellist I'm assuming that this is awx/devel? 
Does this occur with all application types?
Which browser/OS?

**Comment by mabashian** [comment]
@rooftopcellist I'd be curious to see if there are any errors in the developer tools console when this happens.  Did you happen to check the console out when this happens?

**Comment by rooftopcellist** [comment]
@mabashian I am seeing this in the console:

![image](https://user-images.githubusercontent.com/11698892/54130519-e7159080-43e6-11e9-95d6-8998ae541040.png)


@unlikelyzero Chrome Version 72.0.3626.109 (Official Build) (64-bit)
It does happen with all application types.

**Comment by rooftopcellist** [comment]
It looks like this has been fixed by https://github.com/ansible/awx/pull/3376.  Closing.
