### ISSUE TITLE
(docker-compose) how to add another instance to instance-group?

### ISSUE THREAD

**Issue by heikocane** [ansible/awx#3400]
Hello,

I have two virtual machines (awx01 and awx02). I have setup awx on awx01 successfully with docker-compose and now I want to add awx02 (also with docker-compose) as an instance so my jobs can also be scheduled on awx02. Is there a way to add the awx02 to my setup? I

Thanks for helping me!

Heiko

**Comment by impca** [comment]
Docker Compose does not span across multiple hosts, you'd have edit your compose configuration on awx01 and make the required ports are accessible from awx02 and then copy the compose configuration over to awx02 and edit the configuration again to start only the task container and connect to awx01. Then it *might* work. 

Also, you may be better off asking this question here: https://www.reddit.com/r/ansible/ or here https://stackoverflow.com/questions/tagged/ansible-awx

**Comment by sujiar37** [comment]
I have published the code for building AWX V4.0.0 with Instance Group
functionality . You may please find it here :
https://github.com/sujiar37/AWX-HA-InstanceGroup

Regards,
Sujith

**Comment by ryanpetrello** [comment]
As @impca suggested, this issue tracker is for reporting bugs.  If you have questions about operating AWX, check out our mailing list or IRC room on Freenode (`#ansible-awx`)
