### ISSUE TITLE
Allow key management and jump host configuration

### ISSUE THREAD

**Issue by jainnikhil30** [ansible/awx#3405]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
Allow ssh key management and jump host configuration. Currently its all via file system and have to be managed manually. It will be great if its something that can be done via UI.

**Comment by wenottingham** [comment]
In general, we want to fix this by expanding how isolated nodes work, not introduce another jump host construct.

**Comment by wenottingham** [comment]
Use case here is a job that does orchestration across multiple networks - perform a configuration update to some internal service, then connecting to multiple nodes in different networks accessible via isolated nodes.

This can be put into a workflow, but it's very very clunky. Ideally would be able to do just do tasks on hosts and connect however is needed then.

**Comment by wenottingham** [comment]
This is also tied to https://github.com/ansible/awx/issues/286

**Comment by shanemcd** [comment]
No longer relevant after automation mesh landed.
