### ISSUE TITLE
unable to install AWX on kubernetes

### ISSUE THREAD

**Issue by kprerana** [ansible/awx#3406]
##### ISSUE TYPE
 - I am unable to install AWX on kubernetes using https://github.com/ansible/awx

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY

PLAY [Build and deploy AWX] **********************************************************************************************************

TASK [check_vars : include_tasks] ****************************************************************************************************
skipping: [localhost]

TASK [check_vars : include_tasks] ****************************************************************************************************
included: /home/kube30/awx/installer/roles/check_vars/tasks/check_docker.yml for localhost

TASK [check_vars : postgres_data_dir should be defined] ******************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [check_vars : host_port should be defined] **************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [image_build : Set global version if not provided] ******************************************************************************
skipping: [localhost]

TASK [image_build : Verify awx-logos directory exists for official install] **********************************************************
skipping: [localhost]

TASK [image_build : Copy logos for inclusion in sdist] *******************************************************************************
skipping: [localhost]

TASK [image_build : Set sdist file name] *********************************************************************************************
skipping: [localhost]

TASK [image_build : AWX Distribution] ************************************************************************************************
skipping: [localhost]

TASK [image_build : Stat distribution file] ******************************************************************************************
skipping: [localhost]

TASK [image_build : Clean distribution] **********************************************************************************************
skipping: [localhost]

TASK [image_build : Build sdist builder image] ***************************************************************************************
skipping: [localhost]

TASK [image_build : Build AWX distribution using container] **************************************************************************
skipping: [localhost]

TASK [image_build : Build AWX distribution locally] **********************************************************************************
skipping: [localhost]

TASK [image_build : Set docker build base path] **************************************************************************************
skipping: [localhost]

TASK [image_build : Set awx_web image name] ******************************************************************************************
skipping: [localhost]

TASK [image_build : Set awx_task image name] *****************************************************************************************
skipping: [localhost]

TASK [image_build : Ensure directory exists] *****************************************************************************************
skipping: [localhost]

TASK [image_build : Stage sdist] *****************************************************************************************************
skipping: [localhost]

TASK [image_build : Template web Dockerfile] *****************************************************************************************
skipping: [localhost]

TASK [image_build : Template task Dockerfile] ****************************************************************************************
skipping: [localhost]

TASK [image_build : Stage launch_awx] ************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage launch_awx_task] *******************************************************************************************
skipping: [localhost]

TASK [image_build : Stage nginx.conf] ************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage supervisor.conf] *******************************************************************************************
skipping: [localhost]

TASK [image_build : Stage supervisor_task.conf] **************************************************************************************
skipping: [localhost]

TASK [image_build : Stage settings.py] ***********************************************************************************************
skipping: [localhost]

TASK [image_build : Stage requirements] **********************************************************************************************
skipping: [localhost]

TASK [image_build : Stage config watcher] ********************************************************************************************
skipping: [localhost]

TASK [image_build : Stage Makefile] **************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage ansible repo] **********************************************************************************************
skipping: [localhost]

TASK [image_build : Stage ansible repo key] ******************************************************************************************
skipping: [localhost]

TASK [image_build : Build base web image] ********************************************************************************************
skipping: [localhost]

TASK [image_build : Build base task image] *******************************************************************************************
skipping: [localhost]

TASK [image_build : Tag task and web images as latest] *******************************************************************************
skipping: [localhost]

TASK [image_build : Clean docker base directory] *************************************************************************************
skipping: [localhost]

TASK [image_push : Authenticate with Docker registry if registry password given] *****************************************************
skipping: [localhost]

TASK [image_push : Remove web image] *************************************************************************************************
skipping: [localhost]

TASK [image_push : Remove task image] ************************************************************************************************
skipping: [localhost]

TASK [image_push : Tag and push web image to registry] *******************************************************************************
skipping: [localhost]

TASK [image_push : Tag and push task image to registry] ******************************************************************************
skipping: [localhost]

TASK [image_push : Set full image path for Registry] *********************************************************************************
skipping: [localhost]

TASK [kubernetes : fail] *************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : include_tasks] ****************************************************************************************************
skipping: [localhost] => (item=openshift_auth.yml)
skipping: [localhost] => (item=openshift.yml)

TASK [kubernetes : include_tasks] ****************************************************************************************************
included: /home/kube30/awx/installer/roles/kubernetes/tasks/kubernetes_auth.yml for localhost
included: /home/kube30/awx/installer/roles/kubernetes/tasks/kubernetes.yml for localhost

TASK [kubernetes : Set the Kubernetes Context] ***************************************************************************************
changed: [localhost]

TASK [kubernetes : Get Namespace Detail] *********************************************************************************************
changed: [localhost]

TASK [kubernetes : Create AWX Kubernetes Project] ************************************************************************************
skipping: [localhost]

TASK [kubernetes : Set postgresql service name] **************************************************************************************
ok: [localhost]

TASK [kubernetes : Use kubectl or oc] ************************************************************************************************
ok: [localhost]

TASK [kubernetes : set_fact] *********************************************************************************************************
ok: [localhost]

TASK [kubernetes : Record deployment size] *******************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "kubectl get sts awx -n awx -o=jsonpath='{.status.replicas}'", "delta": "0:00:00.100814", "end": "2019-03-12 12:21:13.486161", "msg": "non-zero return code", "rc": 1, "start": "2019-03-12 12:21:13.385347", "stderr": "Error from server (NotFound): statefulsets.apps \"awx\" not found", "stderr_lines": ["Error from server (NotFound): statefulsets.apps \"awx\" not found"], "stdout": "", "stdout_lines": []}
...ignoring

TASK [kubernetes : Set expected post-deployment Replicas value] **********************************************************************
skipping: [localhost]

TASK [kubernetes : Delete existing Deployment] ***************************************************************************************
skipping: [localhost]

TASK [kubernetes : Get Postgres Service Detail] **************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "kubectl describe svc awx-postgresql -n awx", "delta": "0:00:00.119227", "end": "2019-03-12 12:21:13.941072", "msg": "non-zero return code", "rc": 1, "start": "2019-03-12 12:21:13.821845", "stderr": "Error from server (NotFound): services \"awx-postgresql\" not found", "stderr_lines": ["Error from server (NotFound): services \"awx-postgresql\" not found"], "stdout": "", "stdout_lines": []}
...ignoring

TASK [kubernetes : Template PostgreSQL Deployment (OpenShift)] ***********************************************************************
skipping: [localhost]

TASK [kubernetes : Deploy and Activate Postgres (OpenShift)] *************************************************************************
skipping: [localhost]

TASK [kubernetes : Deploy and Activate Postgres (Kubernetes)] ************************************************************************
fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": true}
        to retry, use: --limit @/home/kube30/awx/installer/install.retry

PLAY RECAP ***************************************************************************************************************************
localhost                  : ok=12   changed=4    unreachable=0    failed=1

**Comment by ghost** [comment]
+1

**Comment by miroslavKovacPantheon** [comment]
+1

**Comment by mchipana94** [comment]
Same problem

**Comment by matburt** [comment]
The no_log there is hiding the details of the error, it's likely that you don't have `helm` installed which is required by that step, see:

https://github.com/ansible/awx/blob/devel/INSTALL.md#prerequisites-2

**Comment by ghost** [comment]
Hi @matburt , 

Even after installing the helm, we still have issue : 

```
$ k get pods -n kube-system  | grep -i tiller 
tiller-deploy-5b7c66d59c-jhh8s   1/1     Running   1          26h
$ helm ls 
NAME          	REVISION	UPDATED                 	STATUS  	CHART           	APP VERSION	NAMESPACE
awx-postgresql	3       	Fri Mar 15 11:18:46 2019	DEPLOYED	postgresql-2.0.0	10.5.0     	awx      
$

```



```

$
<localhost> EXEC /bin/sh -c 'echo ~kylix3511 && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/kylix3511/.ansible/tmp/ansible-tmp-1552674646.478857-274332286522078 `" && echo ansible-tmp-1552674646.478857-274332286522078="` echo /Users/kylix3511/.ansible/tmp/ansible-tmp-1552674646.478857-274332286522078 `" ) && sleep 0'
Using module file /Users/kylix3511/venv280/lib/python3.7/site-packages/ansible/modules/commands/command.py
<localhost> PUT /Users/kylix3511/.ansible/tmp/ansible-local-38097wc9wqptq/tmpv_aaxs8d TO /Users/kylix3511/.ansible/tmp/ansible-tmp-1552674646.478857-274332286522078/AnsiballZ_command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/kylix3511/.ansible/tmp/ansible-tmp-1552674646.478857-274332286522078/ /Users/kylix3511/.ansible/tmp/ansible-tmp-1552674646.478857-274332286522078/AnsiballZ_command.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/env python /Users/kylix3511/.ansible/tmp/ansible-tmp-1552674646.478857-274332286522078/AnsiballZ_command.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/kylix3511/.ansible/tmp/ansible-tmp-1552674646.478857-274332286522078/ > /dev/null 2>&1 && sleep 0'
FAILED - RETRYING: Wait for management pod to start (1 retries left).Result was: {
    "attempts": 60,
    "changed": true,
    "cmd": "kubectl -n awx  get pod ansible-tower-management -o jsonpath=\"{.status.phase}\"\n",
    "delta": "0:00:00.101452",
    "end": "2019-03-15 11:30:46.873692",
    "invocation": {
        "module_args": {
            "_raw_params": "kubectl -n awx  get pod ansible-tower-management -o jsonpath=\"{.status.phase}\"\n",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "rc": 0,
    "retries": 61,
    "start": "2019-03-15 11:30:46.772240",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "Pending",
    "stdout_lines": [
        "Pending"
    ]
}
<localhost> EXEC /bin/sh -c 'echo ~kylix3511 && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/kylix3511/.ansible/tmp/ansible-tmp-1552674656.904634-167541889381131 `" && echo ansible-tmp-1552674656.904634-167541889381131="` echo /Users/kylix3511/.ansible/tmp/ansible-tmp-1552674656.904634-167541889381131 `" ) && sleep 0'
Using module file /Users/kylix3511/venv280/lib/python3.7/site-packages/ansible/modules/commands/command.py
<localhost> PUT /Users/kylix3511/.ansible/tmp/ansible-local-38097wc9wqptq/tmpcm89o2t8 TO /Users/kylix3511/.ansible/tmp/ansible-tmp-1552674656.904634-167541889381131/AnsiballZ_command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/kylix3511/.ansible/tmp/ansible-tmp-1552674656.904634-167541889381131/ /Users/kylix3511/.ansible/tmp/ansible-tmp-1552674656.904634-167541889381131/AnsiballZ_command.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/env python /Users/kylix3511/.ansible/tmp/ansible-tmp-1552674656.904634-167541889381131/AnsiballZ_command.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/kylix3511/.ansible/tmp/ansible-tmp-1552674656.904634-167541889381131/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "attempts": 60,
    "changed": true,
    "cmd": "kubectl -n awx  get pod ansible-tower-management -o jsonpath=\"{.status.phase}\"\n",
    "delta": "0:00:00.094710",
    "end": "2019-03-15 11:30:57.222284",
    "invocation": {
        "module_args": {
            "_raw_params": "kubectl -n awx  get pod ansible-tower-management -o jsonpath=\"{.status.phase}\"\n",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "rc": 0,
    "start": "2019-03-15 11:30:57.127574",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "Pending",
    "stdout_lines": [
        "Pending"
    ]
}

PLAY RECAP *************************************************************************************************************************************************
localhost                  : ok=20   changed=8    unreachable=0    failed=1    skipped=48   rescued=0    ignored=2   

$

```
