### ISSUE TITLE
Feature idea: gpg verification of project checkouts

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#341]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

Ansible 2.0 supports the verify_commit option on checkout:

```
if yes, when cloning or checking out a version verify the signature of a GPG signed commit.
This requires git version>=2.1.0 to be installed.
The commit MUST be signed and the public key MUST be trusted in the GPG trustdb.
```

This would require:
- [ ] parameter on the project
- [ ] figuring out how to use multiple keys
- [ ] a gpg trustdb exposed to the checkout

Doing the last of these in a way that's not gross may be complicated.

**Comment by sdirbach** [comment]
Is there any progress on this?

**Comment by ericzolf** [comment]
The feature should allow to verify only the last commit _or_ all commits leading to the current commit.

**Comment by shanemcd** [comment]
This was implemented in https://github.com/ansible/awx/pull/12813.
