### ISSUE TITLE
Schedule job with `None (run once)` but saved as `Day`

### ISSUE THREAD

**Issue by sugitk** [ansible/awx#3414]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

I saved the schedule as `None (run once)` but when edit this schedule it is saved as `Day`.

##### ENVIRONMENT
* AWX version: Tower 3.4.2
* Operating System: RHEL 7.6
* Web Browser: Chrome 72.0.3626.121

##### STEPS TO REPRODUCE

1) Add a new schedule for a job template
2) Configure time and Save as `None (run once)`
3) Edit this schedule, we can see `Day` at `REPEAT FREQUENCY`

##### EXPECTED RESULTS

`None (run once)` instead of `Day`

##### ADDITIONAL INFORMATION

When created:
<img width="1132" alt="スクリーンショット 2019-03-14 11 47 47" src="https://user-images.githubusercontent.com/2234991/54328052-cac85c80-464f-11e9-8077-84c76717fece.png">

When edit it:
<img width="1131" alt="スクリーンショット 2019-03-14 11 48 05" src="https://user-images.githubusercontent.com/2234991/54328062-d156d400-464f-11e9-947d-c420da50d0fc.png">

**Comment by wenottingham** [comment]
This is expected behavior with how the rrule parsing library works. Yes, it's a bit weird, but it's not worth us reimplementing the entire stack for this.

**Comment by sugitk** [comment]
Thank you for your review and comment. I understood it.
