### ISSUE TITLE
translation of `SCHEDULE DESCRIPTION` is not good in Japanese

### ISSUE THREAD

**Issue by sugitk** [ansible/awx#3415]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

`説明のスケジュール` is not good translation in Japanese

##### ENVIRONMENT
* AWX version: Tower 3.4.2
* Web Browser: Chrome 73.0.3683.75

##### STEPS TO REPRODUCE

click Job Template -> Schedule tab -> new Schedule

##### EXPECTED RESULTS

スケジュールの詳細

##### ACTUAL RESULTS

説明のスケジュール

##### ADDITIONAL INFORMATION

<img width="1149" alt="スクリーンショット 2019-03-14 15 50 55" src="https://user-images.githubusercontent.com/2234991/54337539-8a2e0a80-4672-11e9-991a-c37a21ded8ff.png">

**Comment by ryanpetrello** [comment]
cc @docschick @sshedmake

**Comment by wenottingham** [comment]
Please send a new PR if the translation needs corrected.

**Comment by sugitk** [comment]
Thank you, I've created a PR
