### ISSUE TITLE
Add python-ldap module to awx images

### ISSUE THREAD

**Issue by losil** [ansible/awx#3419]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - AWX Task

##### SUMMARY
I am using ldap lookups in my playbooks. Like this: https://github.com/quinot/ansible-plugin-lookup_ldap
This method is failing because the python-ldap module is missing. 

Can you build the awx docker images with this python-ldap module?

**Comment by ryanpetrello** [comment]
This can be accomplished using a custom virtualenv:

https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md

**Comment by AlekseiSaff** [comment]
We are using inventory in LDAP and custom script for inventory. Also missing this module in the AWX docker image. It looks like it's not possible to use virtualenv for Invenroty population script.

**Comment by colans** [comment]
Looks like this is now [Execution Environments](https://ansible.readthedocs.io/projects/awx/en/latest/userguide/execution_environments.html).

Related to https://github.com/ansible/awx/issues/515
