### ISSUE TITLE
Feature: use file upload widgets where appropriate

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#342]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY

We have a variety of items that are 'uploaded' into AWX via cut-and-paste.

- [ ] SSH keys
- [ ] GCE keys
- [ ] SAML certificates
- [ ] Custom inventory scripts

Ideally, these would be file upload widgets.

**Comment by wenottingham** [comment]
Note that for inventory scripts, they should still be viewable.

**Comment by wenottingham** [comment]
cc @jakemcdermott if he has notes from GCE work in case someone wants to pick this up

**Comment by IshwarKanse** [comment]
Can we add extra vars file with yaml / json syntax that can be uploaded to the item list ?

**Comment by ghost** [comment]
+1

**Comment by gamuniz** [comment]
closing as done in new UI
