### ISSUE TITLE
Include Host_filter OR Logic in Smart Inventory UI

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/awx#3427]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

[Smart inventory](https://docs.ansible.com/ansible-tower/latest/html/userguide/inventories.html#smart-inventories) host_filter is currently set AND. Add ability to allow OR set for host_filter.

**Comment by mrmibrown** [comment]
Here's a work-around for this issue:
https://access.redhat.com/solutions/4268032

**Comment by shanemcd** [comment]
We are moving away from smart inventories and recently introduced a new feature called Constructed Inventory. That merged in https://github.com/ansible/awx/pull/13448 and got released with AWX 22. Constructed Inventories allow for querying host vars. I'm going to go ahead and close this and can also follow up with a link to a blog post that @AlanCoding is currently working on.

Docs to new constructed inventory source:

https://github.com/ansible/awx/blob/devel/docs/inventory/constructed_inventory.md
