### ISSUE TITLE
New option -> relaunch job with different verbosity

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#3428]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY
Make it possible to relaunch job with higher verbosity for debugging purposes. If job fails on few hosts and you need to see more verbose output this would be great thing.

**Comment by kdelee** [comment]
@beeankha reach out to @appuk when you get started on this

**Comment by unlikelyzero** [comment]
https://github.com/ansible/tower-qa/issues/4396 is the testplan

**Comment by shanemcd** [comment]
Closing in favor of the more general issue at https://github.com/ansible/awx/issues/2421
