### ISSUE TITLE
Allow the use of the same job template name across multiple orgs(multi-tenancy)

### ISSUE THREAD

**Issue by gamuniz** [ansible/awx#3432]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API
 - UI
 

##### SUMMARY

Please allow the use of the same job template name across multiple organizations. This should allow for better use of multi tenant environments.

##### ADDITIONAL INFORMATION
Currently the name field is unique across the entire Tower/AWX installation.

**Comment by ryanpetrello** [comment]
@wenottingham if we haven't done this, it should probably be easy to prioritize and accomplish?

**Comment by wenottingham** [comment]
it filters down to UJT, so ... maybe?

**Comment by wenottingham** [comment]
also, the fact that org is merely inherited from a project likely complicates this.

**Comment by AlanCoding** [comment]
Closing to be done as part of 3903
