### ISSUE TITLE
Text field in Groups, etc should be resizable

### ISSUE THREAD

**Issue by RogerSik** [ansible/awx#3436]
Text field in Groups, etc should be resizable

Current situation: 
![2019-03-18 13_52_59-Ansible AWX _ AWS](https://user-images.githubusercontent.com/165814/54531455-9fae7780-4985-11e9-8e5a-38bb6dfdecf5.png)

Desired situation: 
![2019-03-18 13_53_40-Die besten WordPress-Blogs 2017 · Elbnetz-Blog](https://user-images.githubusercontent.com/165814/54531494-bb198280-4985-11e9-98f2-811215614427.png)

**Comment by mabashian** [comment]
<img width="1385" alt="Screen Shot 2022-04-04 at 2 53 28 PM" src="https://user-images.githubusercontent.com/9889020/161612349-c30de4c4-3f27-43b0-9008-0533e8abb292.png">

We've added this button to display the textarea in a larger window
