### ISSUE TITLE
Extra variables field should be resizeable

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#3437]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY
Right now you can't resize the text area:
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/1560121/54533795-4cd7be80-498b-11e9-910e-7aa95487de6c.png">

**Comment by wenottingham** [comment]
Which specific area are you looking at? (see https://github.com/ansible/awx/issues/1268)

**Comment by benapetr** [comment]
Job template definition

**Comment by benapetr** [comment]
If you edit any job template

**Comment by keithjgrant** [comment]
I just finished a lot of prep work for this under #3209: the `<at-code-mirror>` directive supports the popout view with a much larger text area. The next steps will be to figure out how to incorporate the "prompt on launch" checkbox with this directive and change forms with extra variables fields to use the directive.
