### ISSUE TITLE
Add total host count to inventory hosts display

### ISSUE THREAD

**Issue by ghost** [ansible/awx#344]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
Re-introduce a total host count to the inventory hosts display page in the Tower UI, similar to the summary count that was available in previous versions.

##### ENVIRONMENT
* AWX version: 1.1.0

##### STEPS TO REPRODUCE

The host count provides  a useful summary in the UI display of the total number of hosts in an inventory, without the need to look for details elsewhere.

**Comment by jdranchman** [comment]
My work around is to use the API https://tower/api/v1/inventories/ - inventory id -/ and look for total_hosts

**Comment by mjhermanson** [comment]
I also have a request for this feature.  This is useful information for at least the following use cases:
- when scheduling ad-hoc jobs
- when creating 'Smart Inventories'
- auditing the inventory
- managing licenses
- writing playbooks
- validating jobs
- troubleshooting inventory sync

Running a job without knowing the number of hosts ahead of time is dangerous and the user should have this information displayed.

**Comment by nixocio** [comment]
We can add info as part of the details page for inventories.
