### ISSUE TITLE
Notification templates return BadRequest if no timeout provided

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#3444]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY

Attempting to create notification template through API gets BadRequest if no timeout provided

##### ENVIRONMENT
* AWX version: devel
* AWX install method: docker on linux

##### STEPS TO REPRODUCE

Attempt to create notification without timeout but with all other fields

##### EXPECTED RESULTS
Default timeout is provided

##### ACTUAL RESULTS
No default provided, not able to create notification

`["Missing required fields for Notification Configuration: ['timeout']`

**Comment by kdelee** [comment]
@ryanpetrello sounds like we are hemming and hawing about maybe accepting this change.

Last question is, does this require some kind of migration? How will this effect current notifications (e.g. you had one, then you update, what happens?)

**Comment by ryanpetrello** [comment]
@kdelee @beeankha I think this is a legitimate concern that _probably_ will cause issues at upgrade time, and I think the best way to resolve this is to copy the approach taken by *other* notification backends for *optional* parameters.

Here's a good example:

```python
~/dev/awx ack hex_color
awx/main/notifications/slack_backend.py
22:    def __init__(self, token, hex_color="", fail_silently=False, **kwargs):
26:        if hex_color.startswith("#") and (len(hex_color) == 4 or len(hex_color) == 7):
27:            self.color = hex_color

awx/ui/client/src/notifications/notificationTemplates.form.js
534:            hex_color: {
```

Notice that the Slack backend **does not** specify `hex_color` in its `init_parameters`, and as a result, they're not *strictly required*.  I think we should take the same approach with the Email notification backend.  This might *also* allow us to add in some of that validation we wanted - you could probably come up with a way (maybe in `EmailBackend.__init__`?) to validate the type (`int`) and min/max bounds of provided timeout values:

```python
class CustomEmailBackend(EmailBackend):

    def __init__(self, *args, **kwargs):
        # perform validation on kwargs.get('timeout')
        return super(CustomEmailBackend, self).__init__(*args, **kwargs)
```

@beeankha would you work on this, and add some tests for it?

**Comment by kdelee** [comment]
@Spredzy verified this with @beeankha , going to close
