### ISSUE TITLE
RFE: Select an inventory when provisioning callback is invoked

### ISSUE THREAD

**Issue by sugitk** [ansible/awx#3445]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY

The customer of Tower has multiple inventories that run the same playbook. They would like to boot a system from any inventory, and have it call back to Tower, and update it's corresponding inventory and provision based on userdata.

**Comment by wenottingham** [comment]
If the system knows what inventory it's in, why could it not just call the appropriate callback template?

**Comment by ryanpetrello** [comment]
Closing due to lack of response.
