### ISSUE TITLE
When host and group share name, group steals hostvars from azure_rm inventory update with script

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#3448]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY

If a host and a group share a name and an inventory update is made with a script, the host ends up with no hostvars and the group gets the hostvars that were meant to be associated with  the group.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

create a host and a group on azure that share a name

##### EXPECTED RESULTS

Host gets hostvars, group does not

##### ACTUAL RESULTS
Group gets host vars, host does not

##### ADDITIONAL INFORMATION
This is fixed by #3266 

FWIW I think this is a "WONTFIX" issue, but I do want to document it
@AlanCoding knows about this allready

**Comment by AlanCoding** [comment]
The error text from this case is

>  [WARNING]: Found both group and host with same name: xxxxxxx

**Comment by AlanCoding** [comment]
Link https://github.com/ansible/ansible/pull/54060 as a way to restore the requested bug.

**Comment by ryanpetrello** [comment]
@AlanCoding @kdelee how much do we care about tracking this?  Sounds like "just the way it works"?

**Comment by AlanCoding** [comment]
Ansible core fixed this by adding randomization to host names. We removed that randomization in order to get parity with legacy behavior. Users who hit this will have functionality of their inventory impacted.

**Comment by awithrow9** [comment]
@AlanCoding is there anything left to do with this one?

**Comment by AlanCoding** [comment]
It makes sense to close this as a known issue with the remediation to be to implement #4306. Assuming that is done, the afflicted users could address it by removing the `plain_host_names` option.

**Comment by ryanpetrello** [comment]
@AlanCoding @awithrow9 closing in favor of tracking #4306
