### ISSUE TITLE
Feature: enhance select modals to only list appropriate choices

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#345]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY

An example:

-  Click 'add users to team'.
- Select all users
- Hit submit.
- Users are added to team
- Click 'add users to team' again
- All users still available for selection

This is global paradigm across the app - we don't filter "already applied" items out of available choices. (Other examples: inventory host/group association.)

##### ADDITIONAL INFORMATION

Filed as UI feature. May need API query help.

**Comment by mabashian** [comment]
Note that as part of planning we'll want to run through the app and identify the lists/lookups.  Adding a host to a group comes to mind

**Comment by unlikelyzero** [comment]
QE Questions or Concerns:

- Two cases: lookups and existing org and users
- Projects, Credentials, Instance Groups,
- Add users to org. Not from the Permissions page
- We need to discover and test all the list/lookups.
- Multi-select case

**Comment by unlikelyzero** [comment]
@jlmitch5 please let me know when you're about 24 hours away from a PR

**Comment by unlikelyzero** [comment]
dun n dusted

**Comment by unlikelyzero** [comment]
@tvo318 @jlmitch5 no doc changes are necessary, correct?
