### ISSUE TITLE
UI: Opened survey gets closed when other job is running

### ISSUE THREAD

**Issue by sumkincpp** [ansible/awx#3462]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Opened survey gets closed when page gets an update in background about running jobs.

##### ENVIRONMENT
* AWX version: 1.6.49
* AWX install method: docker

##### STEPS TO REPRODUCE

1. Open Survey in 1 Tab
2. Run job in 2 Tab
3. See that after background update of first Tab, survey on this tab gets closed

##### EXPECTED RESULTS

Survey on 1 tab not closes when job

**Comment by sumkincpp** [comment]
Just to note - on installation where lots of jobs are running in background(and they are obviously block each other from parallel execution) prompting and filling Surveys is completely impossible.

**Comment by ryanpetrello** [comment]
@mabashian any thoughts on this one?

**Comment by Xaroth** [comment]
This same issue also affects the job listing; when expanding the job listing to show more information, each completed job run (or new job being started) refreshes the listing, thus causing it to show it's default collapsed overview.

**Comment by sumkincpp** [comment]
~~Issue is present in latest AWX 9.4.0/10.0.0.~~

~~AWX Users/Engineers can't simultaneously use AWX without mutual interference and interference from already running workflows.~~

**Comment by sumkincpp** [comment]
I was not right initially, when tracing the issue. It is local to one browser session.

As of 11.2.0 survey window is getting closed in one session, other browser/users sessions are not affected, they still have opened Survey window.

Issue can be closed.
