### ISSUE TITLE
UI: collapsed left-hand menu helper text will not disappear sometimes  

### ISSUE THREAD

**Issue by IPvSean** [ansible/awx#3463]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
when the hamburger menu is collapsed it is fairly easy to get the helper text to stay (see attached screenshot)

##### ENVIRONMENT
* AWX version: N/A
* Tower 3.4.1
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker N/A
* Tower install method: RHEL 7.4
* Ansible version:  Ansible 2.7.8 
* Operating System: MacOS
* Web Browser: Chrome Version 72.0.3626.121 (Official Build) (64-bit)

##### STEPS TO REPRODUCE

Here is picture->
![picture of broken buttons](https://github.com/IPvSean/pictures_for_github/blob/master/broken_buttons.png?raw=true)

to reproduce just collapse the menu and move your mouse quickly back and forth, here is an animation->
![animation](https://github.com/IPvSean/pictures_for_github/blob/master/broken_buttons.gif?raw=true)

##### EXPECTED RESULTS

For the helper text to dissapear  
##### ACTUAL RESULTS

see screen shot above

##### ADDITIONAL INFORMATION

N/A see above

**Comment by unlikelyzero** [comment]
I know that this is a dupe but may be so old that it doesn't exist in awx/tower issues
