### ISSUE TITLE
Unable to create  ALB with AWX

### ISSUE THREAD

**Issue by submah** [ansible/awx#3475]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY
Hello, I have written a playbook to create ALB on AWS. The playbook is working if i am executing it on directly on a Linux tty, but same playbook with AWX giving error as bellow. 

AWX is not taking both the subnets simultaneously, it s taking subnet id one by one. Please suggest me in order to resolve the issue.
. 
TASK [Creating ALB] ************************************************************
task path: /var/lib/awx/projects/_225__sccoe_awx_dev/ELB_ALB/ELB_ALB-Playbook.yml:97
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ClientError: An error occurred (ValidationError) when calling the CreateLoadBalancer operation: At least two subnets in two different Availability Zones must be specified
failed: [10.218.110.183] (item=subnet-8e471ea3) => {"boto3_version": "1.5.20", "botocore_version": "1.8.34", "changed": false, "error": {"code": "ValidationError", "message": "At least two subnets in two different Availability Zones must be specified", "type": "Sender"}, "item": "subnet-8e471ea3", "msg": "An error occurred (ValidationError) when calling the CreateLoadBalancer operation: At least two subnets in two different Availability Zones must be specified", "response_metadata": {"http_headers": {"connection": "close", "content-length": "337", "content-type": "text/xml", "date": "Fri, 22 Mar 2019 06:23:55 GMT", "x-amzn-requestid": "121490cf-4c6b-11e9-b02c-3f673408bdd8"}, "http_status_code": 400, "request_id": "121490cf-4c6…
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ClientError: An error occurred (ValidationError) when calling the CreateLoadBalancer operation: At least two subnets in two different Availability Zones must be specified
failed: [10.218.110.183] (item=subnet-a99049f1) => {"boto3_version": "1.5.20", "botocore_version": "1.8.34", "changed": false, "error": {"code": "ValidationError", "message": "At least two subnets in two different Availability Zones must be specified", "type": "Sender"}, "item": "subnet-a99049f1", "msg": "An error occurred (ValidationError) when calling the CreateLoadBalancer operation: At least two subnets in two different Availability Zones must be specified", "response_metadata": {"http_headers": {"connection": "close", "content-length": "337", "content-type": "text/xml", "date": "Fri, 22 Mar 2019 06:24:00 GMT", "x-amzn-requestid": "14d7f6e3-4c6b-11e9-b188-978194d0c8e9"}, "http_status_code": 400, "request_id": "14d7f6e3-4c6…

##### ENVIRONMENT
Tower CLI 3.2.1
API v2
AWX 2.0.1
Ansible 2.7.1

**Comment by wenottingham** [comment]
This error is coming from the module itself; at a glance, it may be because of different boto versions between your commandline run and in AWX.

This is probably best discussed on the ansible-project mailing list.
