### ISSUE TITLE
project_update waits until job is finished

### ISSUE THREAD

**Issue by gstorme** [ansible/awx#3478]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY

We use a Git repository where we commit playbooks in, this Git repo is defined as a project in AWX.
Jobs are launched, using this project.
The "scm update options" are all disabled in the project settings.

Our flow compares the Git revision with the one of the AWX project, and triggers a project_update when it's different.

We noticed that when a job is running, the scm update remains in a pending state until the job is finished, and only starts after the job has finished.

##### ENVIRONMENT
* AWX version: 2.1.2.0
* AWX install method: docker on linux
* Ansible version:  2.7.4
* Operating System: Debian

##### STEPS TO REPRODUCE

Commit a playbook to Git
Run a project update
Run a playbook job
Commit another playbook to Git
Run a project update

##### EXPECTED RESULTS

The 2nd project update is executed during the 1st playbook job execution

##### ACTUAL RESULTS

The 2nd project update remains pending, until the 1st playbook job is finished

##### ADDITIONAL INFORMATION

When running ansible-playbook outside of AWX, and changing the contents of a  role/playbook/... during this run, the playbook run is not affected by these changes.
Why does an SCM project update in AWX wait until a job is finished, I would think the project update wouldn't impact any running jobs?

**Comment by wenottingham** [comment]
Because it's operating out of a single directory, and updating out from under a running job would be bad.

Will link to #282 ... until that is solved, there's nothing to do here.
