### ISSUE TITLE
WorkFlow: Child job is still being triggered even parent job is failed. 

### ISSUE THREAD

**Issue by jainshagun** [ansible/awx#3480]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

In case of multiple parent job, if one is failing still child job is getting triggerd.
##### ENVIRONMENT
* AWX version: 3.0.1.0
* AWX install method: docker on linux
* Ansible version:  2.7.7
* Operating System: linux
* Web Browser: Crome

##### STEPS TO REPRODUCE

create a workflow with 2 parallel jobs and point both jobs to a single child job. make one job fail.
##### EXPECTED RESULTS

child job should not get triggered.
##### ACTUAL RESULTS

child job is getting triggered.
##### ADDITIONAL INFORMATION

![workflow_link](https://user-images.githubusercontent.com/40594574/54820619-c0354500-4c97-11e9-80d3-32dec7c8e0d4.PNG)

**Comment by wenottingham** [comment]
-> #3054
