### ISSUE TITLE
Not able to create the schedule with REST API

### ISSUE THREAD

**Issue by atotala** [ansible/awx#3486]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API

##### ENVIRONMENT
* AWX version: 3.0.0-92-gc79fe458c-4
* AWX install method: docker container
* Ansible version:  2.7.8
* Operating System: centOS
* Web Browser: Aany /POSTMAN

##### STEPS TO REPRODUCE
I am sending below body to create a schedule in AWX but I am not able to create
{
  "description": "Kubernetes Monitor",
  "enabled": "True",
  "verbosity": "2",
  "job_type": "run",
  "unified_job_template": "8",
  "inventory": "Kubernetes Monitor Inventory",
  "rrule": "DTSTART:20500331T055000Z RRULE:FREQ=MINUTELY;INTERVAL=10;COUNT=5",
  "name": "Kubernetes Monitor CAS Alert Nodes Job Template"
}

Response:
I am getting below response instead.
{
    "count": 0,
    "next": null,
    "previous": null,
    "results": []
}

am I making mistake somewhere ??

**Comment by wenottingham** [comment]
Most likely, yes.

This tracker is for filing bugs/RFEs for AWX. This seems like more of a user issue; this is better discussed on the `awx-project` mailing list, or on the `ansible-awx` IRC channel. See https://github.com/ansible/awx/#get-involved for details.
