### ISSUE TITLE
virtual env not verified on launch against current list of virtual environments

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#3495]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Followon of: https://github.com/ansible/awx/pull/3320

We do not verify the custom venv used on launch is actually a currently configured custom venv.

##### ENVIRONMENT
* AWX version: next (when 3320 is merged)

##### STEPS TO REPRODUCE

1. set a custom venv path
2. put some venvs in it
3. assign those venvs to things
4. remove the custom venv path
5. launch something from step 3

##### EXPECTED RESULTS

Fails, due to the venv on the resource not being a current custom venv.

##### ACTUAL RESULTS

Works, becuase it happens to still be a path that contains a venv

**Comment by ryanpetrello** [comment]
https://github.com/ansible/awx/blob/devel/awx/main/models/unified_jobs.py#L1226 would be a good place in code accomplish this check at launch time.

**Comment by wenottingham** [comment]
Does that cover inventory updates too? (insert other-custom-venv-using places here as well)

**Comment by ryanpetrello** [comment]
@wenottingham it should, the `UnifiedJob` code should be shared across all the implementations.

**Comment by AlanCoding** [comment]
Yes, and at the unified job model level, there is an expectation that a property, `ansible_virtualenv_path`, will give the path. Even as we do https://github.com/ansible/awx/issues/3387, the implementation for this should not change.

**Comment by ryanpetrello** [comment]
Fixed in https://github.com/ansible/awx/pull/3549#event-2285550239
