### ISSUE TITLE
tasks/main.yml pg_hostname setting wrong

### ISSUE THREAD

**Issue by shen3lu4** [ansible/awx#3496]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

The installation on Kubernetes failed due to a wrong parameter in roles/kubernetes/tasks/main.yml file.

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: kubernetes
* Ansible version:  2.4.0
* Operating System: Oracle Linux 7.4
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Checkout awx code tag 3.0.1. Make appropriate changes to inventory file as documented by providing the kubernetes context and namespace info. Run "ansible-playbook -i inventory install.yml" to install. 

##### EXPECTED RESULTS

Expect AWX to be installed successfully.

##### ACTUAL RESULTS

Playbook failed at step: [kubernetes : Migrate database]. Error:
could not translate host name \"awx-postgresql-postgresql\" to address: Name or service not known

##### ADDITIONAL INFORMATION

It turns out in roles/kubernetes/tasks/main.yml task "Set postgresql hostname to helm package service (Kubernetes)":

    pg_hostname: "{{ postgresql_service_name }}-postgresql"

is wrong. It should be:

    pg_hostname: "{{ kubernetes_deployment_name }}-postgresql"

After correcting this, the installation was successful.

**Comment by ryanpetrello** [comment]
cc @shanemcd

**Comment by freaker2k7** [comment]
Happened to me as well on Ubuntu 16.04

**Comment by awithrow9** [comment]
@shen3lu4 can you try this on the latest AWX?
