### ISSUE TITLE
Inventory variable name/value for determining whether a host is active from ENV

### ISSUE THREAD

**Issue by hudecof** [ansible/awx#350]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Inventory variable name/value for determining whether a host is active from ENV, with fallback to **./awx/settings/defaults.py** with fallback to defautls.

##### ENVIRONMENT
* AWX version: 1.0.0.592 / latest
* AWX install method: docker on linux
* Ansible version:  2.4.0
* Operating System: CentOS 7

##### STEPS TO REPRODUCE
set ENV variable for source based inventory in my case, but should be more genral like in your code
- SCM_ENABLED_VAR
- SCM_ENABLED_VALUE

```
./awx/main/tasks.py:        if getattr(settings, '%s_ENABLED_VAR' % src.upper(), False):
./awx/main/tasks.py:                        getattr(settings, '%s_ENABLED_VAR' % src.upper())])
./awx/main/tasks.py:        if getattr(settings, '%s_ENABLED_VALUE' % src.upper(), False):
./awx/main/tasks.py:                        getattr(settings, '%s_ENABLED_VALUE' % src.upper())])
```

##### EXPECTED RESULTS
the hosts enabled state is changed for hosts, where the **ENABLED_VAR** and **ENABLED_VALUE** matches for given source type.

##### ACTUAL RESULTS
Whens et ENV variabel for SMC based inventory, nothing happens. The **installer/image_build/files/settings.py** needs to be changed and the docker image full rebuild is needed.

##### ADDITIONAL INFORMATION

Generaly, consider to read more variables from ENV, where UI allows to set it.

**Comment by AlanCoding** [comment]
Not the same, but related to #221

**Comment by wenottingham** [comment]
Wonder if this is worth solving generically in the context of https://github.com/ansible/awx/issues/171

**Comment by wenottingham** [comment]
This was solved in moderately recent AWX, where this is now set on the source.

**Comment by dagstuan** [comment]
@wenottingham is there any documentation available as to _how_ this was solved?

**Comment by hudecof** [comment]
Wow, hell freezes. Solved in 3 1/2 year.
This was really show stopper for me and reason why I stopped to use AWX.
Sorry for such a negative attitude, but RH seems not to be very customer oriented.

**Comment by wenottingham** [comment]
> @wenottingham is there any documentation available as to _how_ this was solved?

PR is here: https://github.com/ansible/awx/pull/7763/, merged in mid-late 2020.

enabled_var and enabled_value are now options directly on the inventory source instance, so they can be configured separately for each ec2 inventory source (as an example).

**Comment by dagstuan** [comment]
Ah perfect. Thank you! :)
