### ISSUE TITLE
Changed - Notification

### ISSUE THREAD

**Issue by lmfreitas** [ansible/awx#3504]
##### ISSUE TYPE
 - Notification and Graph "Changed"

##### SUMMARY
Is there a way to register Changed in graph and in Notifications?

**Comment by wenottingham** [comment]
In graph? There is no graph.

Notification enhancements are mostly tracked here: https://github.com/ansible/awx/issues/79. Closing as a dup.

**Comment by lmfreitas** [comment]
![image](https://user-images.githubusercontent.com/24903244/55164265-443d7000-5163-11e9-8f16-b60e59f9f649.png)
