### ISSUE TITLE
RFE Enable azure_rm inventory plugin for ansible 2.8+

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#3506]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY

Usage of azure plugin was not enabled with https://github.com/ansible/awx/pull/3266 because of this blocking issue in core: https://github.com/ansible/ansible/issues/54065

##### ADDITIONAL INFORMATION

This is getting merged ASAP so at this point we only need to wait for that to land and then make a follow up PR to enable for 2.8+
@AlanCoding

**Comment by AlanCoding** [comment]
merged in core

Need

 - azure_rm enabled
 - set in config `plain_host_names: True`

I'll do it, but if someone else wants to instead, I'll walk them through it.

**Comment by kdelee** [comment]
Person who implements this should confirm they can customize hostname and close https://github.com/ansible/ansible/issues/54065

**Comment by AlanCoding** [comment]
Sorry, I missed switching this issue to test when I merged that.

**Comment by kdelee** [comment]
tested this out and it works for me!
