### ISSUE TITLE
RFE enable sat6/foreman inventory plugin for ansible 2.9+

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#3509]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY

Usage of sat6/foreman inventory plugin was not enabled with https://github.com/ansible/awx/pull/3266

We should work on this and enable it in the future

##### ADDITIONAL INFORMATION

We need to do more research about what differences there may be between script and plugin and get any fixes into ansible core before we can do this.

**Comment by jladdjr** [comment]
Posted a PR for the foreman plugin that should give the plugin's output the same basic contents / structure as the script. With this change, I'm able to get identical output from the script and plugin.

https://github.com/ansible/ansible/pull/67070

**Comment by kdelee** [comment]
We are now using the plugin and our regression tests are running and passing -- calling this verified.
