### ISSUE TITLE
Cloudforms inventory script not updated to python3?

### ISSUE THREAD

**Issue by MrMEEE** [ansible/awx#3511]
Hi guys.. 

Seems like some of the plugin scripts (cloudforms.py for one), are not python3 compatible.. (fails with ConfigParser not being able to import, due to rename to configparser).. 

Are these meant to be run in a python2 venv?

Regards

**Comment by AlanCoding** [comment]
Can confirm, in principle, this is trivially true looking at the code.

Upstream fix is needed:

https://github.com/ansible/ansible/blob/devel/contrib/inventory/cloudforms.py#L25

@kdelee @wenottingham

**Comment by kdelee** [comment]
Ok going to file upstream bug for the script. Updated title to be a bit more clear about what component needs fixed.

**Comment by kdelee** [comment]
upstream bug: https://github.com/ansible/ansible/issues/54464

**Comment by 6sossomons** [comment]
Will also need to work on the urllib3 piece...

    7.638 ERROR    ansible-inventory failed (rc=1) with stdout:
stderr:
 [WARNING]:  * Failed to parse /opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/cloudforms.py with script plugin: Inventory
script (/opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/cloudforms.py) had an execution error:
/opt/rh/rh-python36/root/lib/python3.6/site-
packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified
HTTPS request is being made. Adding certificate verification is strongly
advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-
warnings   InsecureRequestWarning) Traceback (most recent call last):   File
"/opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/cloudforms.py", line 485, in <module>
CloudFormsInventory()   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/cloudforms.py", line 56, in __init__
self.update_cache()   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/cloudforms.py", line 295, in update_cache
for host in self._get_hosts():   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/cloudforms.py", line 277, in _get_hosts     ret
= self._get_json("%s/api/vms?offset=%s&limit=%s&expand=resources,tags,hosts,&at
tributes=ipaddresses" % (self.cloudforms_url, offset, limit))   File
"/opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/cloudforms.py", line 245, in _get_json
ret.raise_for_status()   File "/opt/rh/rh-python36/root/lib/python3.6/site-
packages/requests/models.py", line 940, in raise_for_status     raise
HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 401
Client Error: Unauthorized for url: https://10.10.80.33/api/vms?offset=0&limit=
100&expand=resources,tags,hosts,&attributes=ipaddresses
 [WARNING]: Unable to parse /opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/cloudforms.py as an inventory source
ERROR! No inventory was parsed, please check your configuration and options.
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    sys.exit(manage())
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 140, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1111, in handle
    raise exc
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1003, in handle
    data = AnsibleInventoryLoader(source=source, is_custom=self.is_custom, venv_path=venv_path).load()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 195, in load
    return self.command_to_json(base_args + ['--list'])
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 178, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
 [WARNING]:  * Failed to parse /opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/cloudforms.py with script plugin: Inventory
script (/opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/cloudforms.py) had an execution error:
/opt/rh/rh-python36/root/lib/python3.6/site-
packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified
HTTPS request is being made. Adding certificate verification is strongly
advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-
warnings   InsecureRequestWarning) Traceback (most recent call last):   File
"/opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/cloudforms.py", line 485, in <module>
CloudFormsInventory()   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/cloudforms.py", line 56, in __init__
self.update_cache()   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/cloudforms.py", line 295, in update_cache
for host in self._get_hosts():   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/cloudforms.py", line 277, in _get_hosts     ret
= self._get_json("%s/api/vms?offset=%s&limit=%s&expand=resources,tags,hosts,&at
tributes=ipaddresses" % (self.cloudforms_url, offset, limit))   File
"/opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/cloudforms.py", line 245, in _get_json
ret.raise_for_status()   File "/opt/rh/rh-python36/root/lib/python3.6/site-
packages/requests/models.py", line 940, in raise_for_status     raise
HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 401
Client Error: Unauthorized for url: https://10.10.80.33/api/vms?offset=0&limit=
100&expand=resources,tags,hosts,&attributes=ipaddresses
 [WARNING]: Unable to parse /opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/cloudforms.py as an inventory source
ERROR! No inventory was parsed, please check your configuration and options.

**Comment by kdelee** [comment]
Closing this as it works for me
