### ISSUE TITLE
Provide means of flipping Ansible config TRANSFORM_INVALID_GROUP_CHARS

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#3513]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
In version 2.10, Ansible will implement a breaking change to group naming. Group names will be automatically renamed by default.

AWX may need some sort of strategy to deal with this.

##### ADDITIONAL INFORMATION

https://github.com/ansible/ansible/blob/d66f3de3dca5d23950c5889858f211da14bc4eb0/lib/ansible/config/base.yml#L1481-L1494

(env: ANSIBLE_TRANSFORM_INVALID_GROUP_CHARS)

Things that will break:

 - uses in `--limit`
 - references like `groups["foo"]` in playbook namespace
 - vars plugins, like in `group_vars/` folder
 - accessing groups via named URL or API
 - things I didn't think of?

At least smart inventories are not a concern, because they don't enable groups.

You can not use the configure-tower-in-tower setting to do this.

You _can_ use `ansible.cfg` in your source control, but this would need to be adjacent to inventory (in the case of SCM inventory, an increasingly common complaint) and your playbook. Is this sufficient? This could argue in favor of the "do nothing" option. Ping @wenottingham

**Comment by wenottingham** [comment]
We may just need to set it by default.

**Comment by AlanCoding** [comment]
> We may just need to set it by default.

You have a good point.

I made a PR to do this (it was lost in the feature changes for compatibility mode) for the built-in sources. For built-in sources you cannot apply your own `ansible.cfg`.

This issue is still not resolved, in that users do not have any sort of visible toggle. I'm more concerned with playbook runs than for inventory imports.

**Comment by xarses** [comment]
Since this is the first search result for `TRANSFORM_INVALID_GROUP_CHARS`, I'm going to link this here https://github.com/ansible/ansible-documentation/issues/89.

**Comment by AlanCoding** [comment]
Merged the PR that deletes this setting.

### Workaround

I have manually confirmed that I can PATCH `/api/v2/settings/jobs/` with

```json
{
    "AWX_TASK_ENV": {
        "ANSIBLE_DEVEL_WARNING": "False",
        "ANSIBLE_TRANSFORM_INVALID_GROUP_CHARS": "never"
    },
}
```

After doing this, I can run an inventory update and it will have that in its environment. This will apply to jobs as well, but you should only want it to apply to both of neither.... or else get pointless inconsistencies.

I will make a note about this for product-docs, and ping @tvo318 . I do want to call it out and outline the work-around in release notes.

**Comment by AlanCoding** [comment]
Closing as removed, and workaround is outlined above. It will get into release notes and go out in next AWX release.
