### ISSUE TITLE
Support multiple vault credentials

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#352]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

Ansible in 2.4 supports multiple vault credentials, each with its own ID. AWX needs to support this as well.

This breaks the 1-1 vault credential/job template mapping, and therefore requires some work.

Likely has knock-on effects for #223

**Comment by ryanpetrello** [comment]
There are two parts to solving this.  Invoking ansible with multiple vault credentials works like this:

http://docs.ansible.com/ansible/latest/vault.html#multiple-vault-passwords
`If multiple vault passwords are provided, by default Ansible will attempt to decrypt vault content by trying each vault secret in the order they were provided on the command line.`

`$ ansible-playbook --vault-id some-first-password@prompt --vault-id some-second-password@prompt helloworld.yml`

We need a way to correlate vault passwords with a vault ID (the `some-first-password`) part.  There are two options for this:

1.  Require awx users who want to use this feature to specify a vault ID on each Vault credential.  This would require an additional (optional) column on the CredentialType definition.  The downside is that for pre-existing Vault credentials that don't have a vault ID, we'll need to continue to have logic that uses the old `--ask-vault-pass` flag.
2.  It's possible that we could randomly generate a UUID for these vault IDs so the users doesn't have to care.

The second part is actually assigning multiple vault credentials to a `JobTemplate`/`Job` via some new relation.

To avoid major API changes, one possible option here is to actually include vault credentials in the `JobTemplate.extra_credentials` relation, and to make the `JobTemplate.vault_credential` a virtual property that works similarly to how the legacy v1 `JobTemplate.cloud_credential` and `JobTemplate.network_credential` properties work (similar to https://github.com/ansible/awx/blob/devel/docs/custom_credential_types.md#api-backwards-compatability)

This would mean that you could do, for example:

```
POST /api/v2/job_templates/N/extra_credentials/
{
    'associate': true,
    'id': <vault-pk-id>
}
```

...and for backwards compatibility purposes, you can continue to do:
```
PATCH /api/v2/job_templates/
{
    'vault_password': <vault-pk-id>,
}
```

**Comment by ryanpetrello** [comment]
Open Question:  what about vault password promptability?  We probably need smarts to prompt for *multiple* vault passwords if you choose multiple that require a prompt.  The current model for passing launch time vault password only currently supports *one* vault password - we would need to modify this.

```
POST /api/v2/job_templates/N/launch/
{
    "passwords_needed_to_start": [
        "vault_password"
    ]
}
```

How do we support this in a model with *multiple* credentials that need a prompted password?  **Can** we support this in a way that's backwards compatible?

**Comment by AlanCoding** [comment]
Link:

https://github.com/ansible/awx/blob/5635f5fb4960af3cbf05bfcddb96b69c3b65c481/awx/main/tasks.py#L1182-L1192

This code builds our password prompting dict. I think the biggest question is if we prompt for the new string with the id, like `Vault password (alan):`, where "alan" is the id in this case.

some examples, I did using ansible-inventory: https://github.com/AlanCoding/Ansible-inventory-file-examples/tree/master/vault

**Comment by ryanpetrello** [comment]
What if the awx launch API presented "necessary Vault passwords" like this?

```
POST /api/v2/job_templates/N/launch/
{
    "passwords_needed_to_start": [
        "vault_password[vault-id1]",
        "vault_password[vault-id2]"
    ]
}

or

{
    "passwords_needed_to_start": [
        "vault_password.id1",
        "vault_password.id2"
    ]
}
```

This of course makes the assumption that you won't choose two vault creds w/ the same ID.  Though I'm not sure why you would do that - it doesn't make sense for two credentials with the same ID to have two different passwords.

**Comment by jaredevantabor** [comment]
connecting this card related to networking credentials on the JT form: https://github.com/ansible/awx/issues/747

**Comment by jakemcdermott** [comment]
connecting this card related to credential prompting on the launch view: https://github.com/ansible/awx/issues/737

**Comment by ryanpetrello** [comment]
Next steps for this issue are to support https://github.com/ansible/awx/issues/352#issuecomment-337995178 and modify the API validation to actually allow multi-vault assignment on JTs (@AlanCoding's PR https://github.com/ansible/awx/pull/740 does some of this already)

**Comment by AlanCoding** [comment]
yes, noting lines here:

https://github.com/AlanCoding/awx-1/blob/fa9606a75efabcee6f516c17d22473a8eedc4e2c/awx/api/views.py#L610-L637

https://github.com/AlanCoding/awx-1/blob/fa9606a75efabcee6f516c17d22473a8eedc4e2c/awx/api/views.py#L3063-L3068

The condition for the latter would just need to change to be the condition of the former, and then I think there's 1 duplicate condition.

**Comment by ryanpetrello** [comment]
I added a playbook that makes testing this a bit easier:

https://github.com/jlaska/ansible-playbooks/commit/33b81c8c2355ee40cda03694a441ba9cec95e21f

**Comment by AlanCoding** [comment]
Nice example to have!

I cloned the jlaska repo and replicated the steps mentioned, but giving the 2 vault credentials static passwords (not asking on launch), and the playbook runs, producing the decrypted strings "First!" and "Second!". So everything is working well by my testing.
