### ISSUE TITLE
awx_task container doesn't work 

### ISSUE THREAD

**Issue by Win32Sector** [ansible/awx#3526]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
After ansible-playbook ended his job, task container doesn't works properly.

On version 2.1.2 works fine.

```
docker logs 1d82160c09f3 -f
Using /etc/ansible/ansible.cfg as config file
127.0.0.1 | FAILED! => {
    "changed": false, 
    "msg": "argument port is of type <type 'str'> and we were unable to convert to int: invalid literal for int() with base 10: ''"
}
Using /etc/ansible/ansible.cfg as config file
```

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: docker on linux
* Ansible version:  2.7.9
* Operating System: CentOS 7.6

##### STEPS TO REPRODUCE

1. Run ansible-playbook -i inventory install.yml

##### EXPECTED RESULTS

I expect running awx installation

##### ACTUAL RESULTS

awx_task container doesn't work properly.

**Comment by Win32Sector** [comment]
When 3.0.0 version installing with ansible-playbook, I see  
```
[WARNING]: Non-string value found for env option. Ambiguous env options should be wrapped in quotes to avoid YAML parsing. This will become an error in Ansible 2.8. Key: DATABASE_PORT; value will be treated
as: 5432
```
May be in 3.0.1 version ansible can't parse this variable?

**Comment by shanemcd** [comment]
Are you running the installer from master? If you are, then the issue you're hitting will be addressed by https://github.com/ansible/awx/pull/3525. In the meantime you should check out the git tag that corresponds to the docker tag.

**Comment by shanemcd** [comment]
The PR mentioned above has been merged. If you're using code from master you'll have to build your own image until we cut a new release (sometime later today).
