### ISSUE TITLE
On Job Results Detail, Error Detail Text isn't displayed when a JT Errors out until refresh

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#3531]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Error Detail Text isn't displayed when a JT Errors out until refresh

##### ENVIRONMENT
* AWX version: 3.0.1

##### STEPS TO REPRODUCE
1. Create a JT which will error out (bad machine credentials)
1. Run JT and expect Error state
Note: No error details until refresh

##### EXPECTED RESULTS
Error Detail text after error result

##### ACTUAL RESULTS
Error Detail text only available after refresh

##### ADDITIONAL INFORMATION
![error details not displayed](https://user-images.githubusercontent.com/12446869/55114795-4e0a9900-50b9-11e9-8817-ca7546cee7b3.gif)

**Comment by unlikelyzero** [comment]
@wenottingham noted that there might be an existing issue for this

**Comment by nixocio** [comment]
Reopen if we see this behavior on the new UI.
