### ISSUE TITLE
SAML Authentication

### ISSUE THREAD

**Issue by chanaka-jostle** [ansible/awx#3533]
Hello,

I'm not sure if I can post this here but I assume it also impacts AWX.  I configured Tower to authenticate with OKTA via SAML . When I go to Tower's login page and click "Sign in with SAML" it functions correctly and takes me to Okta to sign in, then allows me into Tower after authenticating. However, If I initiate the process from OKTA by clicking the Tower app I setup, it doesn't work. I see "ERROR    social u''. in the tower.log . Does anyone know what would cause this?

Thanks

**Comment by ecchong** [comment]
I have the exact same problem, but can't figure out why.  Both OneLogin and Okta have the same result.

**Comment by ryanpetrello** [comment]
👋 

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
