### ISSUE TITLE
AWX does not work when setting a subpath

### ISSUE THREAD

**Issue by darviche** [ansible/awx#3538]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### ENVIRONMENT
* AWX version: 2.1.0
* AWX install method: docker on linux
* Ansible version:  2.7.2
* Operating System: Redhat
* Web Browser: Google Chrome 73.0.3683.86 (Official Build) (64-bit)

##### STEPS TO REPRODUCE

Replace "/" location in the default nginx configuration file by :

location /app/ {
            # Add trailing / if missing
            rewrite ^(.*)/app/(.*[^/])$ $1/$2/ permanent;
            uwsgi_read_timeout 120s;
            uwsgi_pass uwsgi;
            include /etc/nginx/uwsgi_params;            proxy_set_header X-Forwarded-Port 443;
 }

##### EXPECTED RESULTS

The web UI should be working when run from the subpath /app

##### ACTUAL RESULTS

The web UI does not load and get this line in the awx_web logs : 

**WARNING  django.request Not Found: /app/api**

**Comment by wenottingham** [comment]
There are some known issues here; the recommendation is mostly "do not do this".

**Comment by shanemcd** [comment]
We've changed our tune here because it's a very common pattern in Kubernetes. Closing this in favor of https://github.com/ansible/awx/issues/13821 since it has linked a bunch of related issues together.
