### ISSUE TITLE
Unable to export job list

### ISSUE THREAD

**Issue by arshantz** [ansible/awx#3541]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY

When saving the list of executed jobs as PDF, the output only saves the first three jobs (even though there's 100 listed in the GUI.  I also tried installing tower-cli to do it that way, but I get compilation errors (separate issue).

##### ENVIRONMENT
* AWX version: 3.3.1
* AWX install method: rpm
* Ansible version:  2.7.1
* Operating System: RHEL7
* Web Browser: Chrome & Safari

##### EXPECTED RESULTS

Go to jobs
Search for desired job
Go to print, save as PDF. 

##### ACTUAL RESULTS

It saves the PDF with only 3 jobs.

**Comment by wenottingham** [comment]
If you are trying to build a report, we recommend using the REST API.

**Comment by arshantz** [comment]
@wenottingham - using tower-cli?  I can't seem to get it to install on RHEL7.6.  It throws an error about not being able to find a module called ssl_match_hostname, even though backports.ssl_match_hostname is installed:

    ImportError: No module named ssl_match_hostname

I'm happy to use the cli if I can get it to work.

**Comment by shanemcd** [comment]
Closing this issue as we're not seeing a lot of demand for this.
