### ISSUE TITLE
RPM Installation... Again

### ISSUE THREAD

**Issue by MrMEEE** [ansible/awx#3542]
Hi guys..

It's been over a year now, since I started doing the RPM installation of AWX.. I think it has become pretty stable and there seems to be quite a few people using it..

I'm not saying that the RPM installation is better or worse than the docker one, but each have their advantages..

I would love for us to collaborate on providing both to the community, any chance that we can work together on this??

Regards

Martin

**Comment by matburt** [comment]
Unfortunately it's just not something we can take on from a maintenance perspective right now.

**Comment by MrMEEE** [comment]
Hi @matburt 

I'm not asking you guys to take on the maintenance perspective at all, I will do that (would be nice with some help from time to time, though).. 

I'm just asking if you guys could share some information on your thought and upcoming changes (so that I can get it fixed in advance)

Also just to add a link to my installation guide (or add it to the wiki).. just informing that there is an RPM alternative, but it's not supported in the same way...

Any of this doable??

/Martin
