### ISSUE TITLE
Custom virtual environments can become links in API browser

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#3544]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
The custom virtual environment path is mistaken for a hyperlink in API browser.

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Create a custom virtual env directory

Apply this to a job template, and include a trailing slash, `/`

Launch a job from this JT

go to job detail view, inspect `job_env`

##### EXPECTED RESULTS

probably best behavior would be to give the virtualenv path without the trailing slash, for general clarity and consistency when consuming the API

##### ACTUAL RESULTS

The trailing slash makes it a link

##### ADDITIONAL INFORMATION

Attempted fix was made at https://github.com/ansible/awx/pull/3026, but went stale. That link has screenshots.

**Comment by gamuniz** [comment]
closing as no longer relevant.
