### ISSUE TITLE
Openstack credential type does not provide OS_CLIENT_CONFIG_FILE to scm based inventory

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#3547]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY

It is expected that the Openstack credential will provide to the environment `OS_CLIENT_CONFIG_FILE` pointing to a temporary file that has been written in the job's temporary directory.

Note, this somewhat related to https://github.com/ansible/awx/issues/941

##### ENVIRONMENT
* AWX version: devel

##### STEPS TO REPRODUCE

Create openstack credential
Create scm based inventory source for an inventory, could point to anything
Run inventory update
Look at `job_env`, obvserve no OS_CLIENT_CONFIG_FILE

##### EXPECTED RESULTS

Openstack credential provides to job_env OS_CLIENT_CONFIG_FILE pointing to config file generated and laid down in temporary job directory

##### ACTUAL RESULTS
Not there

##### ADDITIONAL INFORMATION
This enables many different usages of the openstack credentials as OS_CLIENT_CONFIG is a standard way of providing credentials and other configuration options, including scm sourced plugin config files for inventory plugins.

**Comment by AlanCoding** [comment]
implemented
