### ISSUE TITLE
UI survey answer types

### ISSUE THREAD

**Issue by hemskgren** [ansible/awx#355]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

New answer type with "two layers/linked" choise 
##### EXPECTED RESULTS

One answer type with first "single select" then new options with linked/registered, ether single or multiple select.
example:
single select->
A    
 | 
---multiple select - >
A.1  A.2   A.3 
                                            
To only have an maximum of 4 to 6 in first single select will make it much easier to delegate in complex environments.  
We can solve it with more templates but to delegate example 50+ templates for the same job using the same playbook!  We feel the survey limit some of the possibility today.

**Comment by wenottingham** [comment]
This sounds like a duplicate of https://github.com/ansible/awx/issues/20
