### ISSUE TITLE
User is immediately logged out if the page redirects to a 404. 

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#3557]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Possibly related to https://github.com/ansible/tower/issues/2760
When a user is automatically logged out, they can log back in and land on the page they previously viewed. However, if the page they previously viewed is for a resource that no longer exists (for example, a job template that is now deleted), the page 404s (which is fine) and the user is logged back out (which is not fine).

##### ENVIRONMENT
* AWX version: AWX 4.0.0-25-g4e01b1157
* AWX install method: docker on linux
* Ansible version:  2.7.9
* Operating System: Fedora 29
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE
1. Wait for a session to expire so the user is logged out, while viewing a resource like a job template.
2. Via API or another session, delete the resource that the initial session was on.
3. Log back into the initial session.

##### EXPECTED RESULTS
The page redirects to the missing resource, a 404 is displayed, and confirmation of the 404 dialog modal redirects to the dashboard.
##### ACTUAL RESULTS
The page redirects to the missing resource, a 404 is displayed, and confirmation of the 404 dialog modal logs the user back out. The only way to "recover" is to manually visit the dashboard via URL bar.

**Comment by wenottingham** [comment]
Can you test on top of https://github.com/ansible/awx/pull/3510 ?

**Comment by dsesami** [comment]
Tested with #3510, it behaves. @jbradberry ping me when that is merged so i can re-verify and close this as appropriate.

**Comment by jbradberry** [comment]
@dsesami this has just merged.

**Comment by dsesami** [comment]
Verified that this behaves as intended now, the user is no longer redirected around.

**Comment by lemmy04** [comment]
this seems to be back: I log in, get a 404, and get logged right out.

**Comment by lemmy04** [comment]
> 
> 
> this seems to be back: I log in, get a 404, and get logged right out.

restarted my AWX stack, that fixed it.
