### ISSUE TITLE
Callbacks Not Working

### ISSUE THREAD

**Issue by bradlyaolson** [ansible/awx#356]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Hello. I am having a problem performing callbacks from a job template in the UI. I currently have 2 hosts in inventory, but when I browse to the callback job in the API, it displays:

"matching_hosts": []

##### STEPS TO REPRODUCE

Run curl command from client requesting callback:

curl -d "host_config_key=KEY" http://awxweb:80/api/v2/job_templates/12/callback/

##### EXPECTED RESULTS

Expected job template to run

##### ACTUAL RESULTS

Receive error message on client:

{"msg":"No matching host could be found!"}

**Comment by cchurch** [comment]
@bradlyaolson: Check that the hostnames given in your inventory (or `ansible_host` variable if set for those hosts) resolve to those clients from the `awx_web` container. If you've modified the `REMOTE_HOST_HEADERS` setting that may also affect AWX's ability to determine which host made the request.

The code we use to determine the host from the request can be found here: [awx/api/views.py#L3036](https://github.com/ansible/awx/blob/devel/awx/api/views.py#L3036).

**Comment by matburt** [comment]
Find out more about how provisioning callbacks work here: http://docs.ansible.com/ansible-tower/3.2.0/html/userguide/job_templates.html#provisioning-callbacks

**Comment by bradlyaolson** [comment]
Thanks for the information. I really appreciate it.

The thing is, it was working last week. I didn't change anything (honest!) and have been playing with the ansible_host variable trying to get it working again.

If I manually run the job, it works fine and is able to hit the hosts. Am I correct in assuming that the job template is working correctly, and the callback is off?

I will keep messing with it to make sure it is not a config issue on my end. But the fact that it stopped working does have me a little worried.

Thanks!

EDIT: Also, should the matching_hosts section of the callback show the empty array when I browse to its the API section?

**Comment by bradlyaolson** [comment]
This has to be an issue with my Openstack and name resolution. I tried with a callback in a different environment and it worked fine. Plesae disregard!
