### ISSUE TITLE
Ansible AWX marks some variables as unsafe by default while generating the extra vars file.

### ISSUE THREAD

**Issue by urbinaalex17** [ansible/awx#3566]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

I've got an ansible playbook which makes use of the variable jboss_bind_iface to gather information based on the ansible facts E.g.: ansible_eth0.ipv4.address. I investigated deeper and it turns out that it has to do with unsafe variables, I'm gonna explain this in the additional information section.

##### ENVIRONMENT
* AWX version: 3.0.1.0
* AWX install method: docker on Linux
* Ansible version:  2.7.9
* Operating System: CentOS Linux release 7.6.1810 (Core)

##### STEPS TO REPRODUCE

Task: 

- name: "Set fact jboss_eap_bind_address"
  set_fact: jboss_eap_bind_address="{{ '{{ ' + 'ansible_' + jboss_bind_iface + '.ipv4.address' ' }}' }}"

- name: "Debug fact"
  debug:
    msg: "Variable jboss_eap_bind_address is {{ jboss_eap_bind_address }} based on interface {{ jboss_bind_iface }}"

- name: "Copy instance specific standalone-full-ha.xml"
  template:
    src: "standalone-full-ha.xml.j2"
    dest: "/tmp/standalone-full-ha.xml"

Jinja2 template (standalone-full-ha.xml.j2):

<inet-address value="${jboss.bind.address.management:{{ jboss_eap_bind_address }}}"/>

##### EXPECTED RESULTS

Using ansible-playbook command works.

PLAY [rd-iap1] **************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************
ok: [172.16.4.16]

TASK [install-jboss-eap : Create helper fact] *******************************************************************************************
ok: [172.16.4.16]

TASK [install-jboss-eap : Set fact jboss_eap_bind_address] ******************************************************************************
ok: [172.16.4.16]

TASK [install-jboss-eap : Debug fact] ***************************************************************************************************
ok: [172.16.4.16] => {
    "msg": "Variable jboss_eap_bind_address is 172.16.4.16 based on interface eth0"
}

TASK [install-jboss-eap : Copy instance specific standalone-full-ha.xml] ****************************************************************
changed: [172.16.4.16]

PLAY RECAP ******************************************************************************************************************************
172.16.4.16                : ok=5    changed=1    unreachable=0    failed=0

The generated standalone-full-ha.xml file looks like this:
<inet-address value="${jboss.bind.address.management:172.16.4.16}"/>

##### ACTUAL RESULTS

Using Ansible AWX does not work

PLAY [172.16.4.16] *****************************************************************

TASK [Gathering Facts] *********************************************************
ok: [172.16.4.16]

TASK [install-jboss-eap : Create helper fact] **********************************
ok: [172.16.4.16]

TASK [install-jboss-eap : Set fact jboss_eap_bind_address] *********************
ok: [172.16.4.16]

TASK [install-jboss-eap : Debug fact] ******************************************
ok: [172.16.4.16] => {
    "msg": "Variable jboss_eap_bind_address is {{ ansible_eth0.ipv4.address }} based on interface eth0"
}

TASK [install-jboss-eap : Copy instance specific standalone-full-ha.xml] *******
changed: [172.16.4.16]

PLAY RECAP *********************************************************************
172.16.4.16 : ok=5    changed=1    unreachable=0    failed=0   

The generated standalone-full-ha.xml file looks like this:
<inet-address value="${jboss.bind.address.management:{{ ansible_eth0.ipv4.address }}}"/>

##### ADDITIONAL INFORMATION

While generating the Ansible Extra Vars file it marks some variables as "unsafe" 

!unsafe 'awx_job_id': 310
!unsafe 'awx_job_launch_type': !unsafe 'relaunch'
!unsafe 'tower_job_id': 310
!unsafe 'tower_job_launch_type': !unsafe 'relaunch'
!unsafe 'awx_user_id': 1
!unsafe 'awx_user_name': !unsafe 'admin'
!unsafe 'awx_user_first_name': !unsafe 'Alexander'
!unsafe 'awx_user_last_name': !unsafe 'Urbina'
!unsafe 'tower_user_id': 1
!unsafe 'tower_user_name': !unsafe 'admin'
!unsafe 'tower_user_first_name': !unsafe 'Alexander'
!unsafe 'tower_user_last_name': !unsafe 'Urbina'
!unsafe 'awx_project_revision': !unsafe 'dd28f74d986b22dcaea8ea2eabecd2f985d4aefc'
!unsafe 'tower_project_revision': !unsafe 'dd28f74d986b22dcaea8ea2eabecd2f985d4aefc'
!unsafe 'awx_job_template_id': 8
!unsafe 'awx_job_template_name': !unsafe 'JBoss_Configure_in_Provisioning'
!unsafe 'tower_job_template_id': 8
!unsafe 'tower_job_template_name': !unsafe 'JBoss_Configure_in_Provisioning'
!unsafe 'console_enabled': !unsafe 'true'
!unsafe 'jboss_bind_iface': !unsafe 'eth0'

If I remove the !unsafe in the value of the variable jboss_bind_iface like this: !unsafe 'jboss_bind_iface': 'eth0' and execute the playbook again works.

Is there a way to explicitly mark a variable as safe while using AWX?

**Comment by AlanCoding** [comment]
You can change the setting `ALLOW_JINJA_IN_EXTRA_VARS` to allow unsafe variables generally.

Or, you can leave that setting as the default, and set this variable in the job template extra_vars instead of getting from the prompts or wherever it comes from now.

**Comment by urbinaalex17** [comment]
Hi Alan,
I did it that way, in the job template extra_vars (screenshot below)

![image](https://user-images.githubusercontent.com/42731074/55356513-1cfae180-5488-11e9-92e6-7c2f51826e5b.png)

I gathered the files (inventory, extra_vars files) while executing the template in AWX.

**Comment by AlanCoding** [comment]
Let me re-state what you're telling us here, in your job template extra_vars you have:

```yaml
jboss_bind_iface: eth0
```

But it generates an extra_vars file with

```yaml
!unsafe 'jboss_bind_iface': !unsafe 'eth0'
```

And you have `ALLOW_JINJA_IN_EXTRA_VARS` set to the default of "template".

Is that accurate?

**Comment by urbinaalex17** [comment]
That's accurate... I'm sure the variable is set to the default. Where should I change that value?

**Comment by vrubiolo** [comment]
@urbinaalex17 : check https://github.com/ansible/awx-operator#exporting-environment-variables-to-containers for how to inject vars into the associated containers

**Comment by shanemcd** [comment]
We havent seen any reports of this recently and are unsure how to reproduce. If you are still seeing this and have a repo or some other easy to follow reproducer please share and open a new issue.
