### ISSUE TITLE
Workflow Node Modification Broken

### ISSUE THREAD

**Issue by ryan012880** [ansible/awx#3567]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Unable to modify workflow with nodes that has configured with inventory, credentials, job tags and survey prompts.

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.9
* Operating System: RHEL7
* Web Browser: Chrome/Firefox

##### STEPS TO REPRODUCE

1. Create a workflow
2. add a Job template that has an inventory, credential, job tag and survey prompt configured
3. Save the workflow
4. Modify the workflow by changing the JT that you have added previously

##### EXPECTED RESULTS

You should be able to modify without error

##### ACTUAL RESULTS

During the modification process an error pops up

Fig.1 without job tags prompt you can still click CONFIRM button

<img width="974" alt="Screen Shot 2019-03-31 at 12 31 37 AM" src="https://user-images.githubusercontent.com/10410660/55279680-284df000-5356-11e9-8ae7-44e4e4bf6087.png">

Fig.2 with inventory, credential, job tag and survey prompt configured in the JT, there is no way to proceed

<img width="1043" alt="Screen Shot 2019-03-31 at 1 28 12 AM" src="https://user-images.githubusercontent.com/10410660/55279741-cfcb2280-5356-11e9-853d-1defc3abbe3c.png">

**Comment by mabashian** [comment]
Should be resolved by #3669

**Comment by ryan012880** [comment]
@mabashian thanks, just tested and it works!!
