### ISSUE TITLE
uwsgi memory leak

### ISSUE THREAD

**Issue by grahamneville** [ansible/awx#3578]
##### ISSUE TYPE
- Bug Report

 
##### COMPONENT NAME
- API
- UI

 
##### SUMMARY
When running AWX on K8s or a standalone docker host there is a constant memory increase seen on the awx-web container and after a certain amount of jobs run, or even page clicks, the uwsgi processes start to be killed due to the container hitting the resource limits set. These tie up with HTTP 500 and 502 errors.

 
##### ENVIRONMENT
* AWX version: 2.1.2, 3.0.1 and 4.0.0
* AWX install method: k8s,docker
* Ansible version:  NA

 
##### STEPS TO REPRODUCE
Monitor awx-web container usage,
use top within container, press 'e' a couple of times to get memory in MB and keep an eye on the uwsgi processes then browse or run jobs. You'll see that the uwsgi processes just continue to consume more and more memory, eventually there will be logs showing that the uwsgi processes are being killed (probably due to OOM). This then returns 500/502 errors back to the user.

It seems when the awx web container first starts the pids allocated to the uwsgi processes are in the low hundreds, if the container has been up for a few weeks the pids are in the tens of thousands.

If no-one is logged on via the GUI then memory doesn't increase, but it doesn't reduce either.

Example log when running in K8s and with AWX 4.0.0

[pid: 130|app: 0|req: 1000/2342] <ip> () {48 vars in 2359 bytes} [Mon Mar 25 10:28:43 2019] GET /api/v2/job_templates/59/launch/ => generated 1020 bytes in 94 msecs (HTTP/1.1 200) 10 headers in 394 bytes (1 switches on core 0)
...The work of process 130 is done. Seeya!
worker 1 killed successfully (pid: 130)
Respawned uWSGI worker 1 (new pid: 170)
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x10e2290 pid: 170 (default app)

The logs are different on AWX 2.1.2, it shows a signal 9 killing the process.

##### EXPECTED RESULTS
Memory is cleaned up and doesn't continue to rise after each page click or job is run.

 
##### ACTUAL RESULTS
Memory keeps increasing after every page click or every job run.

 
##### ADDITIONAL INFORMATION

Noticed a 151MB memory increase on the awx-web container within 30 mins. This was with just 1 user logged in and 22 new jobs - job ID at the start was 682 and was 704 after (including SCM and inventory updates).

At 14:15 (start) the memory consumed by awx-web was 997MB

At 14:45 (end) the memory consumed by awx-web was 1.148GB

I've noticed on a fresh start of awx-web the uwsgi processes are using around 130MB each. My container has been up for a few days and has logged 704 runs and I see the top uwsgi process using 230MB (the others range from 177MB to 208MB)

This was seen on AWX 2.1.2, 3.0.1, and 4.0.0 on host K8s and standalone docker hosts. I've not tried earlier versions.

The memory even increases just when browsing around not running any jobs.

For the standalone docker host we have 32GB of RAM. 

For the K8s hosts we've set resource limits matching those in your inventory files.

For K8s we are using HAProxy as an ingress service for SSL termination, for standalone docker we also front it with HAProxy for SSL termination.

**Comment by grahamneville** [comment]
Overnight I ran a python script to continually hit AWX and setup valgrind to monitor for memory leaks.

At the start it looked like the valgrind wrapped uwsgi pid was 149

```
top - 21:07:53 up 11 days,  7:17,  0 users,  load average: 2.10, 2.85, 3.41
Threads:  13 total,   1 running,  12 sleeping,   0 stopped,   0 zombie
%Cpu(s):  6.6 us,  1.2 sy,  0.0 ni, 92.1 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 65922024 total,  2342292 free, 32073856 used, 31505876 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 32800484 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
    1 root      20   0    4.3m   0.6m   0.6m S  0.0  0.0   0:00.03 tini
    8 root      20   0   11.4m   2.7m   2.5m S  0.0  0.0   0:00.00 bash
  137 root      20   0  112.3m  16.6m   6.9m S  0.0  0.0   0:00.14 supervisord
  140 root      20   0  101.1m  13.8m   6.9m S  0.0  0.0   0:00.06 python
  141 root      20   0  271.8m  88.5m  14.4m S  0.0  0.1   0:01.69 daphne
  142 root      20   0   55.4m   7.1m   6.0m S  0.0  0.0   0:00.01 nginx
  143 root      20   0  167.8m  82.8m   9.5m S  0.0  0.1   0:02.51 memcheck-am+
  144 nginx     20   0   55.9m   4.7m   3.2m S  0.0  0.0   0:00.00 nginx
  149 root      20   0  620.8m 383.6m  21.7m S  0.0  0.6   1:13.77 memcheck-am+
  150 root      20   0   14.9m   3.5m   3.1m S  0.0  0.0   0:00.03 bash
  173 root      20   0   14.9m   3.4m   3.1m S  0.0  0.0   0:00.02 bash
  190 root      20   0   58.2m   4.2m   3.7m R  0.0  0.0   0:00.54 top
  192 root      20   0    7.6m   0.7m   0.6m S  0.0  0.0   0:00.00 tail
```
 
This ended up dying and coming 208

```
top - 05:51:19 up 11 days, 16:01,  0 users,  load average: 1.38, 1.32, 1.69
Tasks:  15 total,   1 running,  14 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.8 us,  0.9 sy,  0.0 ni, 94.8 id,  0.5 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 65922024 total,   567840 free, 32152480 used, 33201704 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 32426504 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 root      20   0    4.3m   0.6m   0.6m S   0.0  0.0   0:00.65 tini
    8 root      20   0   11.4m   2.7m   2.5m S   0.0  0.0   0:00.00  `- bash
  137 root      20   0  112.3m  16.6m   6.9m S   0.0  0.0   0:10.92      `- su+
  140 root      20   0  101.1m  13.8m   6.9m S   0.0  0.0   0:00.25          `+
  141 root      20   0  272.0m  88.8m  14.4m S   0.0  0.1   0:14.58          `+
  142 root      20   0   55.4m   7.1m   6.0m S   0.0  0.0   0:00.01          `+
  144 nginx     20   0   56.0m   4.7m   3.2m S   0.0  0.0   0:01.16           +
  143 root      20   0  167.8m  83.4m   9.5m S   0.0  0.1   0:06.59          `+
  208 root      20   0  673.4m 433.0m  21.7m S   0.0  0.7  15:12.00           +
  150 root      20   0   14.9m   3.5m   3.1m S   0.0  0.0   0:00.03 bash
  192 root      20   0    7.6m   0.6m   0.5m S   0.0  0.0   0:00.63  `- tail
  173 root      20   0   14.9m   3.4m   3.1m S   0.0  0.0   0:00.02 bash
  190 root      20   0   58.2m   4.2m   3.7m R   0.0  0.0   0:06.37  `- top
  213 root      20   0   14.9m   3.4m   3.1m S   0.0  0.0   0:00.10 bash
  237 root      20   0   14.9m   3.5m   3.1m S   0.0  0.0   0:00.01 bash
```

I saw a couple of processes die:

```
[root@amdr7 gneville]# grep -r "respawn" /var/lib/docker/containers/315172af2d739c82ac146ea3e43c574221f11d15e1af5df489aec54f30481c3b/315172af2d739c82ac146ea3e43c574221f11d15e1af5df489aec54f30481c3b-json.log
{"log":"DAMN ! worker 1 (pid: 198) died, killed by signal 9 :( trying respawn ...\n","stream":"stderr","time":"2019-04-02T04:11:11.425215511Z"}
{"log":"DAMN ! worker 1 (pid: 203) died, killed by signal 9 :( trying respawn ...\n","stream":"stderr","time":"2019-04-02T05:25:01.555175161Z"}
```

Here's the logs from valgrind:

https://raw.githubusercontent.com/grahamneville/valgrind-awx/master/log

**Comment by grahamn-gr** [comment]
So I first spotted this issue when running AWX in K8s for the first time, migrating away from standalone docker. 
We set resource limits for the containers and gave awx-web 2GB.

I see that by default uwsgi workers get reloaded after they serve 1000 requests, however within K8s we was hitting the containers memory limits before the workers hit the 1000 requests. The OOM killer was killing the uwsgi processes causing HTTP 5xx errors. 
On our standalone docker host as we have no resource limits the workers are able restart once they hit 1000 requests and the host gets its memory back. We've not seen the HTTP 5xx errors on the standalone docker host.

This morning we could get each uwsgi process up to 700MB on the standalone docker host before it would restart, this was done just by navigating on the left hand menu (e.g dashboard, my views, templates and back again). 

What I've now done for our K8s instance is apply a custom supervisor.conf file with the `--reload-on-as` parameter set to 600, so a worker restarts after it hits a virtual memory allocation of 600M, the processes then restart before the reserved memory maxes out the 2GB resource limit set for the container on K8s.

Full line:

```
    [program:uwsgi]
    command = /var/lib/awx/venv/awx/bin/uwsgi --socket 127.0.0.1:8050 --module=awx.wsgi:application --vacuum --processes=5 --reload-on-as=600 --harakiri=120 --no-orphans --master --max-requests=1000 --master-fifo=/var/lib/awx/awxfifo --lazy-apps -b 32768
```

I've tested this and seems to work fine. I'll raise a PR suggesting this so processes aren't killed by the memory manager.

**Comment by chrismeyersfsu** [comment]
@grahamn-gr why the concern over virt mem rather than resident mem?
@grahamneville valgrind is going to have a large memory usage overhead. 230MB per-uwsgi process isn't abnormal. Are you able to get it to go much higher?

**Comment by grahamneville** [comment]
Without Valgrind on our standard alone docker host we was able to get each of the uwsgi process (of which there are 5) up to 700MB of Res memory before they then restarted (I believe this is due to the max requests being set to 100 before reloading).

I don't understand why every click of the page the memory just continues to climb, that doesn't seem right.

With the K8s setup, we need to set memory restrictions, your defaults give the web container 1GB of memory https://github.com/ansible/awx/blob/devel/installer/roles/kubernetes/defaults/main.yml#L21
With this, the process have to be torn down by the memory manager as the container goes OOM, due to the processes not hitting the 100 requests before restarting. This causes the HTTP 500 errors.

The testing I performed showed that the `--reload-as` parameter would restart the processes when the virt memory hit the configured number in the parameter. This would mean each uwsgi process would reach about 300MB-ish of Res memory. So 5x300MB gave a figure of 1.5GB for these processes and I then allowed an extra 500MB for everything else that may be running in the background. 

I did test with setting the parameter much lower but I soon hit OOM issues, I think the lowest I could go was 400MB but then the uwsgi processes would restart after around 20 clicks or so, which I felt was too often.

**Comment by chrismeyersfsu** [comment]
@grahamneville I tried to reproduce a run-away memory leak and wasn't able to. It grew very slow.

* set `--max-requests=1000000`
* 2 browser tabs open; 1 on jobs page; 1 on a specific job
* Schedule job template to run every minute & curl the job template launch endpoint in a loop x 2 processes
* ` top -c -p $(pgrep -d',' -f uwsgi)` <-- =~ 150 max resident memory
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
24589 awx       20   0  462.0m 125.9m   3.0m S   5.6  6.9   0:32.14 /var/lib/awx/venv/awx/bin/uwsgi+
24575 awx       20   0  163.1m   2.4m   2.1m S   0.0  0.1   0:00.24 /var/lib/awx/venv/awx/bin/uwsgi+
24585 awx       20   0  451.8m 116.0m   2.9m S   0.0  6.3   0:09.60 /var/lib/awx/venv/awx/bin/uwsgi+
24586 awx       20   0  460.1m 122.3m   3.0m S   0.0  6.7   0:46.13 /var/lib/awx/venv/awx/bin/uwsgi+
24587 awx       20   0  490.5m 154.3m   2.9m S   0.0  8.4   1:30.30 /var/lib/awx/venv/awx/bin/uwsgi+
24588 awx       20   0  457.8m 119.7m   2.9m S   0.0  6.5   0:16.38 /var/lib/awx/venv/awx/bin/uwsgi+
```

* After 56,000 web requests
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
24587 awx       20   0  548.4m 206.7m   2.3m R  25.2 11.2  24:06.85 /var/lib/awx/venv/awx/bin/uwsgi+
24589 awx       20   0  517.3m 174.8m   2.3m S  16.6  9.5  12:54.62 /var/lib/awx/venv/awx/bin/uwsgi+
24585 awx       20   0  500.9m 158.3m   2.3m S   7.3  8.6   7:32.09 /var/lib/awx/venv/awx/bin/uwsgi+
24586 awx       20   0  500.3m 157.2m   2.3m S   7.3  8.6   7:10.25 /var/lib/awx/venv/awx/bin/uwsgi+
24588 awx       20   0  492.7m 149.4m   2.3m S   5.6  8.1   4:46.74 /var/lib/awx/venv/awx/bin/uwsgi+
24575 awx       20   0  163.1m   0.6m   0.3m S   0.0  0.0   0:00.64 /var/lib/awx/venv/awx/bin/uwsgi+
```
* After 75,000 web requests
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
24587 awx       20   0  564.2m 223.7m   2.3m S  28.3 12.2  33:18.12 /var/lib/awx/venv/awx/bin/uwsgi+
24589 awx       20   0  528.4m 186.2m   2.3m R  17.0 10.1  17:48.25 /var/lib/awx/venv/awx/bin/uwsgi+
24585 awx       20   0  505.1m 163.3m   2.3m S   7.7  8.9  10:27.19 /var/lib/awx/venv/awx/bin/uwsgi+
24586 awx       20   0  505.7m 158.4m   2.3m S   2.3  8.6   9:19.14 /var/lib/awx/venv/awx/bin/uwsgi+
24588 awx       20   0  495.6m 153.5m   2.3m S   1.3  8.4   6:16.67 /var/lib/awx/venv/awx/bin/uwsgi+
24575 awx       20   0  163.1m   0.6m   0.3m S   0.0  0.0   0:00.74 /var/lib/awx/venv/awx/bin/uwsgi+
```
