### ISSUE TITLE
Can't login with standard AWX installation on Docker

### ISSUE THREAD

**Issue by teewhey** [ansible/awx#358]
Not sure whether this has been reported before. I will still report it nonetheless. Thank you for your help.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
I can't login using default credentials after a standard installation of AWX.

##### STEPS TO REPRODUCE

1. Install AWX on docker on Debian Jessie as documented.
2. Login using default credentials (admin password)

##### EXPECTED RESULTS

It shouldn't log me out

##### ACTUAL RESULTS

It logs me out immediately after I log in using default credentials. I did not change any values in inventory file prior to build.

##### ADDITIONAL INFORMATION

This is the requests as shown under Developer Tools

<img width="522" alt="2017-10-04_1116" src="https://user-images.githubusercontent.com/4113595/31158627-91e207ca-a8f5-11e7-94fd-8f296cfc36ee.png">

**Comment by shanemcd** [comment]
I just pulled / started everything from scratch and am not able to recreate this. 

A couple of questions:

- Does this happen if you try in an incognito session?
- If you visit http://localhost/api/v1/config/ and log in via the basic auth prompt, does it work?

**Comment by teewhey** [comment]
<img width="524" alt="image" src="https://user-images.githubusercontent.com/4113595/31209105-5f92b17c-a9bb-11e7-8252-632b2a62a051.png">

Hi Shane,

Yes it does happened in Incognito.
If I manually visited those 401 links and log in via auth prompt, it works.

**Comment by matburt** [comment]
Given that some of the requests seem to work fine, are you behind a proxy or load balancer?

**Comment by teewhey** [comment]
I'm not behind proxy or a load balancer. It is a direct to an instance in AWS

**Comment by matburt** [comment]
Not sure what's up here then, we'll leave this open until we can get some more detail as I can't reproduce it.

**Comment by teewhey** [comment]
I just tried with Ubuntu 16 and it works fine.
The faulty one was built on Debian 8

**Comment by matburt** [comment]
Glad it's working for you now!

**Comment by andekaputra** [comment]
anyone has figured out what caused the issue? Apparently it happens also with Debian 9.
