### ISSUE TITLE
SSO broken Azure AD -  "ERROR    social Your credentials aren't allowed"

### ISSUE THREAD

**Issue by sujiar37** [ansible/awx#3582]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
SSO return error as "**ERROR    social Your credentials aren't allowed**" 

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.9
* Operating System: Linux
* Web Browser: Chrome / Firefox

##### STEPS TO REPRODUCE
Try single sign on after configuring Azure AD authentication

##### EXPECTED RESULTS

User should be able to login without any error

##### ACTUAL RESULTS
Getting error as "**ERROR    social Your credentials aren't allowed**" and it returns to login page again even though the authentication was successful. Following are the related logs,

```
2019-04-02 08:44:08,667 ERROR    social Your credentials aren't allowed.
....
2019-04-02 08:44:11,984 INFO     awx.api.generics status 401 received by user AnonymousUser attempting to access /api/v2/settings/all/ from X.X.X.X
....
2019-04-02 08:44:12,008 INFO     awx.api.generics status 401 received by user AnonymousUser attempting to access /api/v2/config/ from X.X.X.X
 ```

##### ADDITIONAL INFORMATION
#1800

**Comment by sujiar37** [comment]
@ryanpetrello / @rooftopcellist  Could you please look into this and see if it is reproducible. thanks.

**Comment by sujiar37** [comment]
My bad, the secret key [ Azure AD Oauth2 ] which I had updated was wrong. I corrected that and now SSO is working.

**Comment by emoshaya** [comment]
@sujiar37 I'm having the same issue as you for azure ad oauth2.. I'm using the Object ID for the secret key. What did you do to fix it?
