### ISSUE TITLE
How to use inventory script

### ISSUE THREAD

**Issue by NiveditaKumari14** [ansible/awx#3584]
##### ISSUE TYPE
I am new to the AWX. Please tell me that how to use inventory script in details.

##### SUMMARY
There is no proper documentation is available to create or use inventory script in ansible documentation.

**Comment by wenottingham** [comment]
This would need to be done in the ansible documentation first - https://github.com/ansible/ansible/

I would start here: https://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html
