### ISSUE TITLE
Error while installing AWX with Kubernetes

### ISSUE THREAD

**Issue by anksvault** [ansible/awx#3585]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: Kubernetes on Linux
* Ansible version:  2.7.9
* Operating System: RHEL 7.6

##### STEPS TO REPRODUCE

Install pre-requisites, update inventory parameters and run ansible-playbook -i inventory install.yml 

##### EXPECTED RESULTS

The installation should be successful.

##### ACTUAL RESULTS

Getting the following message for the Failed task: Error from server (NotFound): services \"awx-postgresql\" not found

##### ADDITIONAL INFORMATION
NOTE: Like mentioned in the closed issue (https://github.com/ansible/awx/issues/3406), helm is already installed and initiated.

PLAY [Build and deploy AWX] *****************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************
ok: [localhost]

TASK [check_vars : include_tasks] ***********************************************************************************************************************************************************
skipping: [localhost]

TASK [check_vars : include_tasks] ***********************************************************************************************************************************************************
included: /root/AWX_K8s/awx/installer/roles/check_vars/tasks/check_docker.yml for localhost

TASK [check_vars : postgres_data_dir should be defined] *************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [check_vars : host_port should be defined] *********************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [image_build : Set global version if not provided] *************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Verify awx-logos directory exists for official install] *****************************************************************************************************************
skipping: [localhost]

TASK [image_build : Copy logos for inclusion in sdist] **************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Set sdist file name] ****************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : AWX Distribution] *******************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stat distribution file] *************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Clean distribution] *****************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Build sdist builder image] **********************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Build AWX distribution using container] *********************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Build AWX distribution locally] *****************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Set docker build base path] *********************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Set awx_web image name] *************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Set awx_task image name] ************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Ensure directory exists] ************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage sdist] ************************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Template web Dockerfile] ************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Template task Dockerfile] ***********************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage launch_awx] *******************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage launch_awx_task] **************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage nginx.conf] *******************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage supervisor.conf] **************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage supervisor_task.conf] *********************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage settings.py] ******************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage requirements] *****************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage config watcher] ***************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage Makefile] *********************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage ansible repo] *****************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Stage ansible repo key] *************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Build base web image] ***************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Build base task image] **************************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Tag task and web images as latest] **************************************************************************************************************************************
skipping: [localhost]

TASK [image_build : Clean docker base directory] ********************************************************************************************************************************************
skipping: [localhost]

TASK [image_push : Authenticate with Docker registry if registry password given] ************************************************************************************************************
skipping: [localhost]

TASK [image_push : Remove web image] ********************************************************************************************************************************************************
skipping: [localhost]

TASK [image_push : Remove task image] *******************************************************************************************************************************************************
skipping: [localhost]

TASK [image_push : Tag and push web image to registry] **************************************************************************************************************************************
skipping: [localhost]

TASK [image_push : Tag and push task image to registry] *************************************************************************************************************************************
skipping: [localhost]

TASK [image_push : Set full image path for Registry] ****************************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : fail] ********************************************************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : include_tasks] ***********************************************************************************************************************************************************
skipping: [localhost] => (item=openshift_auth.yml)
skipping: [localhost] => (item=openshift.yml)

TASK [kubernetes : include_tasks] ***********************************************************************************************************************************************************
included: /root/AWX_K8s/awx/installer/roles/kubernetes/tasks/kubernetes_auth.yml for localhost
included: /root/AWX_K8s/awx/installer/roles/kubernetes/tasks/kubernetes.yml for localhost

TASK [kubernetes : Set the Kubernetes Context] **********************************************************************************************************************************************
changed: [localhost]

TASK [kubernetes : Get Namespace Detail] ****************************************************************************************************************************************************
changed: [localhost]

TASK [kubernetes : Create AWX Kubernetes Project] *******************************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Set postgresql service name] *********************************************************************************************************************************************
ok: [localhost]

TASK [kubernetes : Use kubectl or oc] *******************************************************************************************************************************************************
ok: [localhost]

TASK [kubernetes : set_fact] ****************************************************************************************************************************************************************
ok: [localhost]

TASK [kubernetes : Record deployment size] **************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "kubectl get sts awx -n awx -o=jsonpath='{.status.replicas}'", "delta": "0:00:00.106883", "end": "2019-04-02 08:02:55.878452", "msg": "non-zero return code", "rc": 1, "start": "2019-04-02 08:02:55.771569", "stderr": "Error from server (NotFound): statefulsets.apps \"awx\" not found", "stderr_lines": ["Error from server (NotFound): statefulsets.apps \"awx\" not found"], "stdout": "", "stdout_lines": []}
...ignoring

TASK [kubernetes : Set expected post-deployment Replicas value] *****************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Delete existing Deployment] **********************************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Get Postgres Service Detail] *********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "kubectl describe svc awx-postgresql -n awx", "delta": "0:00:00.116245", "end": "2019-04-02 08:02:56.327103", "msg": "non-zero return code", "rc": 1, "start": "2019-04-02 08:02:56.210858", "stderr": "Error from server (NotFound): services \"awx-postgresql\" not found", "stderr_lines": ["Error from server (NotFound): services \"awx-postgresql\" not found"], "stdout": "", "stdout_lines": []}
...ignoring

TASK [kubernetes : Template PostgreSQL Deployment (OpenShift)] ******************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Deploy and Activate Postgres (OpenShift)] ********************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Deploy and Activate Postgres (Kubernetes)] *******************************************************************************************************************************
fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": true}
        to retry, use: --limit @/root/AWX_K8s/awx/installer/install.retry

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=13   changed=4    unreachable=0    failed=1

**Comment by anksvault** [comment]
Ok, i disabled the no_log and could see the following:
 
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "helm repo update --tiller-namespace=kube-system\n helm upgrade awx-postgresql --install --namespace awx --set postgresqlUsername=awx --set postgresqlPassword=awxpass767 --set postgresqlDatabase=awx --set persistence.size=5Gi --version=\"2.0.0\" --tiller-namespace=kube-system       stable/postgresql", "delta": "0:00:02.331259", "end": "2019-04-02 08:18:53.417201", "msg": "non-zero return code", "rc": 1, "start": "2019-04-02 08:18:51.085942", "stderr": "Error: could not find a ready tiller pod", "stderr_lines": ["Error: could not find a ready tiller pod"], "stdout": "Hang tight while we grab the latest from your chart repositories...\n...Skip local chart repository\n...Successfully got an update from the \"stable\" chart repository\nUpdate Complete. ⎈ Happy Helming!⎈ ", "stdout_lines": ["Hang tight while we grab the latest from your chart repositories...", "...Skip local chart repository", "...Successfully got an update from the \"stable\" chart repository", "Update Complete. ⎈ Happy Helming!⎈ "]}

**Comment by matburt** [comment]
> Error: could not find a ready tiller pod

You *have* to follow our install instructions which tells you that you need to have Tiller installed.
