### ISSUE TITLE
Insights project update doesn't include user-agent headers

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#3590]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Tower API issues proxy request to Insights. In each request it includes a User-Agent header that lets us know information about the requester (i.e. tower version, license type). That header is *not* included in the request to download the remediation playbooks.

##### ENVIRONMENT
* AWX version: Tower

##### STEPS TO REPRODUCE

* Run an insights project update in Tower

##### EXPECTED RESULTS

* To find the insights request in the Insights Kibana instance

##### ACTUAL RESULTS

* User-Agent headers not found in the Kibana instance

##### ADDITIONAL INFORMATION

* Ask @chrismeyersfsu to find the log in the kibana instance. Alternatively, if your feeling fancy, you can use a proxy server to observe the user-agent headers.

**Comment by kdelee** [comment]
Closing this as @Spredzy confirms it works for him
