### ISSUE TITLE
Pickup insights id from ansible facts

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#3591]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Insights lays down the machine/system id in ansible facts directory. This way, playbooks that run `gather_facts` w/ fact caching turned on will automatically recognize the machine as an insights host.

The insights install role lays down the fact file https://github.com/RedHatInsights/insights-client-role/blob/master/tasks/main.yml#L105

##### ENVIRONMENT
* AWX version: tower

##### STEPS TO REPRODUCE

* Emulate an insights host by creating /etc/ansible/facts.d/insights.fact and filling it with `{ "system_id": "<some_system_id_gotten_from_access_redhat_com>"}`
* Run a playbook in tower that gathers facts and turn on fact cache

##### EXPECTED RESULTS

* For the host to be recognized as an insights host and pickup the system_id (verify by going to the host in the API and look for `insights_system_id`

##### ACTUAL RESULTS

* The `insights_system_id` field for the host is null

**Comment by kdelee** [comment]
Closing this as @one-t confirmed it works for him
