### ISSUE TITLE
Unable to generate token for SAML Authentication enabled instance

### ISSUE THREAD

**Issue by anjan-tummalapalli** [ansible/awx#3599]
As you already know, for SAML based authentication mechanism we don't provide username and password to login

Here is the command provided in documentation to generate token
https://docs.ansible.com/ansible-tower/latest/html/administration/oauth2_token_auth.html#application-using-password-grant-type

curl -X POST -d "grant_type=password&username=<username>&password=<password>&scope=read" -u "<client_id>:<client_secret>" http://<tower>/api/o/token/ -i

Here is the response if I put empty in password field

{"error_description": "Request is missing password parameter.", "error": "invalid_request"}

Please help me in, what to provide in the place of password placeholder for SAML enabled instance.

**Comment by ryanpetrello** [comment]
Hey @anjan-tummalapalli,

Third party authentication and basic auth don't work together when creating OAuth2 tokens in this way.  Here's an explanation of _why_ that's the case for a different authentication provider (Windows Azure).  Have a look:

https://github.com/ansible/awx/issues/3393#issuecomment-471016949

To solve this, you'll have to automate the process of logging in (using something like curl, or another tool/software library for creating HTTPS requests) and establishing a session, and using _that_ session key (`Cookie`) header in a subsequent request to:

```
curl -X POST "https://awx.example.org/api/v2/users/N/personal_tokens/" -H "Cookie:..."
```
