### ISSUE TITLE
Can't clone Mercurial repository with SSL certificates

### ISSUE THREAD

**Issue by pmontanari** [ansible/awx#360]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME

 - UI
 - Installer

##### SUMMARY

My mercurial repository requires a SSL certificate to authenticate. How can I configure it in AWX ?

**Comment by aoyawale** [comment]
do you mean a ssh key to be able to access it through https or ssh? if so then you need to create a a SCM credential.

**Comment by pmontanari** [comment]
No, I mean a pem CA to authenticate against the Rhodecode server.

**Comment by aoyawale** [comment]
that is more OS than AWX specific. You need to get inside the container, replace the self signed certs with signed certs and update the CA files.

**Comment by matburt** [comment]
We use the ansible hg module which doesn't really give us an option on how to treat the SSL certificate. There may be another way but I'm not immediately sure.

**Comment by AlanCoding** [comment]
Mercurial support is being removed https://github.com/ansible/awx/pull/8727

And the Ansible hg module was moved into `community.general` collection, in the default images we will not be including the mercurial software. Users will be able to create their own custom execution environment to do things with it.
