### ISSUE TITLE
Endpoint Needed For Failed Hosts in a Workflow Job

### ISSUE THREAD

**Issue by mrmibrown** [ansible/awx#3605]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY

There is a need for an endpoint for failed hosts in a workflow job.  At the moment, only failed/successful job templates are tracked.

**Comment by wenottingham** [comment]
Hosts don't have a concept of workflow jobs run on them (only jobs). Workflow jobs don't have a unified concept of 'hosts' applied to them (as it could be 20 different inventories across a workflow).

**Comment by wenottingham** [comment]
What's the use case for this?

**Comment by wenottingham** [comment]
Closing per https://github.com/ansible/awx/issues/3605#issuecomment-479957284 - this doesn't generally make sense with how workflows can pull from multiple inventories and have multiple failure paths.
