### ISSUE TITLE
On the Dashboard, Inventory Sync failures can return null and will not render

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#3607]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
On the Dashboard, Inventory Sync failures can return null and will not render. Note: the API returns null on the request.

##### ENVIRONMENT
* AWX version: 4.0.0

##### STEPS TO REPRODUCE
1. Create a new organization and a new user associated with that user
2. Log in as that user and land on dashboard
Note: the dashboard represents 0s for all single stat measurements.

API request on /dashboard/ returns
`inventories: {url: “/api/v2/inventories/“, total: 0, total_with_inventory_source: 0, job_failed: 0,…}
*inventory_failed: null*
job_failed: 0
total: 0
total_with_inventory_source: 0
url: “/api/v2/inventories/” (edited) `

##### EXPECTED RESULTS
A number is returned and represented

##### ACTUAL RESULTS
No number is displayed (but it doesn't 'splode!)

##### ADDITIONAL INFORMATION

<img width="338" alt="Screen Shot 2019-04-03 at 3 59 45 PM" src="https://user-images.githubusercontent.com/12446869/55510297-f9709c00-562b-11e9-824c-7e657664041e.png">

<img width="1634" alt="Screen Shot 2019-04-03 at 3 58 04 PM" src="https://user-images.githubusercontent.com/12446869/55510326-0c836c00-562c-11e9-9428-12694701856f.png">

**Comment by ryanpetrello** [comment]
Fixed by: https://github.com/ansible/tower/issues/3456

**Comment by dsesami** [comment]
Created a user and org and verified that at varying levels of permissions, the inventory sync failure count displays correctly.
