### ISSUE TITLE
Install.yml - Activate Postgres Container

### ISSUE THREAD

**Issue by mkempster22** [ansible/awx#361]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Install Playbook failing on the [local_docker : Activate postgres container] with error
Error connecting: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))

##### ENVIRONMENT
* AWX version: Sorry couldn't find where to see this, Git cloned 2pm GMT 4th October 17
* AWX install method: Docker with install.yml
* Ansible version:  2.3.2.0
* Operating System: RedHat 6.9
* Web Browser: N/A?

##### STEPS TO REPRODUCE

Followed install instructions, Installed all prerequisites listed

##### EXPECTED RESULTS

Task to succeed as usual

##### ACTUAL RESULTS

```
TASK [local_docker : Activate postgres container] ************************************************************************************************
task path: /root/awx/installer/local_docker/tasks/main.yml:105
Using module file /usr/lib/python2.6/site-packages/ansible/modules/cloud/docker/docker_container.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1507125034.51-170571385689994 `" && echo ansible-tmp-1507125034.51-170571385689994="` echo /root/.ansible/tmp/ansible-tmp-1507125034.51-170571385689994 `" ) && sleep 0'
<localhost> PUT /tmp/tmpajB2mK TO /root/.ansible/tmp/ansible-tmp-1507125034.51-170571385689994/docker_container.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1507125034.51-170571385689994/ /root/.ansible/tmp/ansible-tmp-1507125034.51-170571385689994/docker_container.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/env python /root/.ansible/tmp/ansible-tmp-1507125034.51-170571385689994/docker_container.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1507125034.51-170571385689994/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "api_version": null,
            "blkio_weight": null,
            "cacert_path": null,
            "capabilities": null,
            "cert_path": null,
            "cleanup": false,
            "command": null,
            "cpu_period": null,
            "cpu_quota": null,
            "cpu_shares": null,
            "cpuset_cpus": null,
            "cpuset_mems": null,
            "debug": false,
            "detach": true,
            "devices": null,
            "dns_opts": null,
            "dns_search_domains": null,
            "dns_servers": null,
            "docker_host": null,
            "entrypoint": null,
            "env": {
                "POSTGRES_DB": "awx",
                "POSTGRES_PASSWORD": "awxpass",
                "POSTGRES_USER": "awx"
            },
            "env_file": null,
            "etc_hosts": null,
            "exposed_ports": null,
            "filter_logger": false,
            "force_kill": false,
            "groups": null,
            "hostname": null,
            "ignore_image": false,
            "image": "postgres:9.6",
            "interactive": false,
            "ipc_mode": null,
            "keep_volumes": true,
            "kernel_memory": null,
            "key_path": null,
            "kill_signal": null,
            "labels": null,
            "links": null,
            "log_driver": null,
            "log_options": null,
            "mac_address": null,
            "memory": "0",
            "memory_reservation": null,
            "memory_swap": null,
            "memory_swappiness": null,
            "name": "postgres",
            "network_mode": null,
            "networks": null,
            "oom_killer": null,
            "oom_score_adj": null,
            "paused": false,
            "pid_mode": null,
            "privileged": false,
            "published_ports": null,
            "pull": false,
            "purge_networks": false,
            "read_only": false,
            "recreate": false,
            "restart": false,
            "restart_policy": "unless-stopped",
            "restart_retries": null,
            "security_opts": null,
            "shm_size": null,
            "ssl_version": null,
            "state": "started",
            "stop_signal": null,
            "stop_timeout": null,
            "timeout": null,
            "tls": null,
            "tls_hostname": null,
            "tls_verify": null,
            "trust_image_content": false,
            "tty": false,
            "ulimits": null,
            "user": null,
            "uts": null,
            "volume_driver": null,
            "volumes": [
                "/tmp/pgdocker:/var/lib/postgresql/data:Z"
            ],
            "volumes_from": null
        }
    },
    "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))"
}
        to retry, use: --limit @/root/awx/installer/install.retry
```

##### ADDITIONAL INFORMATION

By the looks of things its something to do with PostgreSQL install, this isn't listed as a prerequisite but after getting this issue I tried installing different versions of this not getting any different results

I've not really used Docker before so please excuse my lack of knowledge around it

**Comment by aoyawale** [comment]
did you start docker?

**Comment by mkempster22** [comment]
Okay that set me along the right lines, the docker package i was using wasn't working correctly so i removed it and installed docker-io

Now i'm getting an issue i had solver earlier with the failed to install docker-py try 'pip install docker-py'

Pretty sure i've seen tickets raised with this already so i'll have a search. Thanks for the help!

**Comment by mkempster22** [comment]
Fixed that issue by adding this to my command '-e "ansible_python_interpreter=python"'

Now I am getting 

"msg": "Error pulling postgres - code: None message: Get https://index.docker.io/v1/repositories/library/postgres/images: x509: certificate signed by unknown authority"

**Comment by mkempster22** [comment]
Just for anyone finding this in the future i fixes my last issue with this: http://www.robwin.eu/running-docker-behind-a-http-proxy/

And now it all works

**Comment by peterducai** [comment]
Still got this issue on Ubuntu 16.04.3 and Fedora 27..
```
git clone awx
cd awx/installer
ansible-playbook -i inventory install.yml 
```

and fails also with -e "ansible_python_interpreter=python"

using ansible 2.4.2 (installed through PIP), Docker version 1.13.1, build 092cba3 (on Ubuntu), docker running (and docker pull postgres downloads image without problems)

```
TASK [local_docker : Activate postgres container] *************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', error(13, 'Permission denied'))"}
	to retry, use: --limit @/home/daemonna/awx/installer/install.retry
```
sudo is with NOPASSWD, no permission denied for anything else.

BTW same error even if switching to latest docker **17.09.0-ce**

**Comment by mkempster22** [comment]
@peterducai Permission denied is a different issue to what I had, Mine was no such file or directory. I'd suggest making a new issue if you cant resolve it with google

**Comment by nkal19** [comment]
TASK [local_docker : Activate postgres container] ******************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import docker-py - No module named requests.exceptions. Try `pip install docker-py`"}
	to retry, use: --limit @/Users/nxxxx/Documents/archive/work/awx/installer/install.retry

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1   

ansible --version
ansible 2.4.2.0

docker --version
Docker version 17.12.0-ce, build c97c6d6

**Comment by nkal19** [comment]
pip list | grep docker
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
docker-py (1.10.6)
docker-pycreds (0.2.1)
dockerpty (0.4.1)

still fails

**Comment by nkal19** [comment]
Sorry to add details in this closed issue page but may help someone

python path needed  to be changed as

#/opt/ansible/awx/installer/inventory

#localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python"
localhost ansible_connection=local ansible_python_interpreter="/usr/local/bin/python2.7"

and docker engine restarted.

build success

TASK [local_docker : Start the containers] *************************************
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=12   changed=5    unreachable=0    failed=0

docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                NAMES
bd003eedba01        ansible/awx_task:latest   "/tini -- /bin/sh -c…"   3 minutes ago       Up 2 minutes        8052/tcp                             awx_task
b8da26b0ebea        ansible/awx_web:latest    "/tini -- /bin/sh -c…"   3 minutes ago       Up 2 minutes        0.0.0.0:80->8052/tcp                 awx_web
91e0cab69b41        memcached:alpine          "docker-entrypoint.s…"   4 minutes ago       Up 3 minutes        11211/tcp                            memcached
17021e1542aa        rabbitmq:3                "docker-entrypoint.s…"   4 minutes ago       Up 3 minutes        4369/tcp, 5671-5672/tcp, 25672/tcp   rabbitmq
2baef2f46cd6        postgres:9.6              "docker-entrypoint.s…"   4 minutes ago       Up 3 minutes        5432/tcp                             postgres
