### ISSUE TITLE
unable to pull ansible roles from open repo 

### ISSUE THREAD

**Issue by arani007** [ansible/awx#3610]
##### ISSUE TYPE
 - Pulling ansible roles like https://github.com/geerlingguy/ansible-role-kubernetes
   into a project and use in jobs is not possible.
   
   any idea how can i do that? 

##### COMPONENT NAME

 - API
 - UI
 - Installer

**Comment by ryanpetrello** [comment]
@arani007,

This issue tracker is for tracking bugs and enhancements to awx.  If you have questions on how to use awx, check out our IRC room (`#ansible-awx` on freenode) or our mailing list (https://groups.google.com/forum/#!forum/awx-project).
