### ISSUE TITLE
Make docker-compose.yml more configurable

### ISSUE THREAD

**Issue by clushie** [ansible/awx#3611]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
- Installer

##### SUMMARY
At the moment it is not easily possible to add additional configurations to the [`docker-compose.yml`](https://github.com/ansible/awx/blob/1f1cb2bdacfdb59a839eab00bfddabe9ed7e51e9/installer/roles/local_docker/templates/docker-compose.yml.j2).
This is sometimes needed, for example when you need to configure a network with a different mtu, such as when you're having mtu fragmentation. For docker, you can configure this in `/etc/docker/daemon.json` - but for docker-compose you need to configure in [each file](https://mlohr.com/docker-mtu/).

I'm fairly new to this project, so I think a possible solution would be to add the feature of specifying additional yaml/jinja in a newly added configuration item such as `docker_compose_merge_file` in [`inventory`](https://github.com/ansible/awx/blob/1f1cb2bdacfdb59a839eab00bfddabe9ed7e51e9/installer/inventory) that are added to the default file.

If someone could guide me on what kind of code contribution you would like to have in this context, that would be very welcome.

**Comment by clushie** [comment]
Update: Yes you are required to apply this to the docker-compose.yml, but you don't have to place it into the same file. So adding something like `docker_compose_extend` (see [documentation](https://docs.docker.com/compose/extends/)) and then placing the content into a separate file is probably also a solution.

**Comment by tumbl3w33d** [comment]
I also just ran into this problem (not for the first time, but last time it was about [adding additional volumes](https://github.com/ansible/awx/pull/3253)) and for those who need a workaround, this is how you extend the existing compose file with network options:
```
networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: {{ facter_mtu_br_int | default(ansible_default_ipv4.mtu) }}
```
There are [more](https://docs.docker.com/engine/reference/commandline/network_create/),  but the mtu is a quite frequent case, I guess.

Apart from that, I'd also love to see a nicer approach to adjusting the compose setup.

**Comment by shanemcd** [comment]
Our docker-compose file is now a jinja template that can be easily extended. Please open a PR if you would like to see new functionality.
