### ISSUE TITLE
Project update optimization

### ISSUE THREAD

**Issue by SpikeShen** [ansible/awx#3612]
##### ISSUE TYPE
When a project update triggered, all instances should update the playbooks. 

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
The current situation is when a job started, the related instance will update the project which used my the job first and then start to finish the job events.

In my env, the project update will take 7-10 seconds which means every job will spend so much time on preparing.

This feature can shorten the run time of routine job.

My AWX version is 1.0.8.0.

**Comment by wenottingham** [comment]
Instances may not be online at the time of a project update, so you can't just do this. In any case, it's already in the issue tracker. -> #289
