### ISSUE TITLE
An organization's admin cannot enable notifications on a job template via the UI.

### ISSUE THREAD

**Issue by dieterdm** [ansible/awx#3613]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
An organization's admin cannot enable notifications on a job template from the GUI. However, he can using tower-cli.

##### ENVIRONMENT
* AWX version: 4.0.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.9
* Operating System: Fedora 29
* Web Browser: Chrome
==> Also reproduced with Ansible Tower 3.4.2-1 on RHEL 7.5 and ansible 2.7.9

##### STEPS TO REPRODUCE

As admin user:
1/ Create a new organization.
2/ Create a user for this organization.
3/ By default, the user is member of the organization. Assign the organisation admin role to this member as well.

Log in as the newly created user:
4/ Create Slack notifications (+ test Slack notifications).
5/ Create a new project.
6/ Create an empty inventory.
7/ Create a job template with this project and inventory.
8/ Try enabling your Slack notifications on your template. This is not possible.
9/ Do this using tower-cli with the same credentials. This is possible.
`tower-cli job_template associate_notification_template --job-template <> --notification-template <> --status success -u my_user -p <>`

##### EXPECTED RESULTS
An organization's admin should be able to manage Slack notifications from the GUI.

##### ACTUAL RESULTS
The organization's admin can see the notifications tab on a job template and can see the enabled status of the different notifications. However, he cannot enable or disable any notifications. (He can using tower-cli). The admin user can do this from the GUI.

**Comment by AlanCoding** [comment]
Fix is up at https://github.com/ansible/awx/pull/3589 ping @mabashian

**Comment by AlanCoding** [comment]
this has been merged
