### ISSUE TITLE
Install Ansible on Ubuntu 18.04 With AWX is failing at TASK [local_docker : Start the containers]

### ISSUE THREAD

**Issue by karungn1** [ansible/awx#3621]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
When Running 
 ansible-playbook -i inventory install.yml 

Gives below error:

TASK [local_docker : Start the containers] *****************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))"}
        to retry, use: --limit @/home/karun/awx/installer/install.retry

PLAY RECAP *************************************************************************************************************
localhost                  : ok=8    changed=0    unreachable=0    failed=1

##### ENVIRONMENT
* AWX version: latest
* AWX install method: docker on linux (https://dzone.com/articles/install-ansible-on-ubuntu-1804-with-awx)
* Ansible version:  2.7.9
* Operating System: Ubuntu 1804
* Web Browser: Firefox(latest)

##### STEPS TO REPRODUCE

https://dzone.com/articles/install-ansible-on-ubuntu-1804-with-awx

##### EXPECTED RESULTS

AWX installed

##### ACTUAL RESULTS

Installation failing

##### ADDITIONAL INFORMATION

Installing on windows 10 Subsystem for Linux

**Comment by sujiar37** [comment]
Please make sure the docker daemon already in started state and active.

**Comment by karungn1** [comment]
@sujiar37 Thanks for the response. I am completely new to Linux, can you please give me command to start the docker daemon and active.

**Comment by Cizin** [comment]
@karungn1 
systemctl enable docker
systemctl start docker

But it's more docker related than AWX...

**Comment by wenottingham** [comment]
This repo is for reporting bugs, not "getting started" support. 

This is best discussed on the mailling list or IRC channel, see https://github.com/ansible/awx/#get-involved.

**Comment by LKS1302** [comment]
@karungn1 ,

Hi,

Am getting the same error while performing the same action.
May i know how did you resolve it.

TASK [local_docker : Set DockerHub Image Paths] *************************************************************************************************************
ok: [localhost]

TASK [local_docker : Create /var/lib/awx directory] *********************************************************************************************************
ok: [localhost]

TASK [local_docker : Create Docker Compose Configuration] ***************************************************************************************************
ok: [localhost] => (item=environment.sh)
ok: [localhost] => (item=credentials.py)
ok: [localhost] => (item=docker-compose.yml)

TASK [local_docker : Render SECRET_KEY file] ****************************************************************************************************************
ok: [localhost]

TASK [local_docker : Start the containers] ******************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: Timeout value connect was Timeout(connect=10, read=10, total=None), but it must be an int or float."}
PLAY RECAP **************************************************************************************************************************************************
localhost                  : ok=8    changed=0    unreachable=0    failed=1

Thanks in advance,

**Comment by datagpu** [comment]
found to have multiple version of docker* which was blocking/conflicting 

yum remove docker-compose docker python-docker-py-1.10.6-11.el7.noarch python-docker-pycreds-0.3.0-11.el7.noarch
pip install docker docker-compose
yum install docker
systemctl start docker
## to check if ports are not being blocked by another application (80,443)
netstat -ntap | grep -i list 
##install
sudo ansible-playbook -i inventory install.yml

TASK [local_docker : Set redis config to other group readable to satisfy redis-server] *********************************************************************************
changed: [localhost]

TASK [local_docker : Render SECRET_KEY file] ***************************************************************************************************************************
ok: [localhost]

TASK [local_docker : Start the containers] *****************************************************************************************************************************
changed: [localhost]

TASK [local_docker : Update CA trust in awx_web container] *************************************************************************************************************
changed: [localhost]

TASK [local_docker : Update CA trust in awx_task container] ************************************************************************************************************
changed: [localhost]

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=16   changed=5    unreachable=0    failed=0    skipped=86   rescued=0    ignored=0

#check docker status
docker ps 
#check awx 
curl -I localhost:80
 installer]$ curl -I localhost:80
HTTP/1.1 302 Found

if all well, open on browser and let awx to upgrade and start.
Cheers!
