### ISSUE TITLE
Add the ability to generate dynamic options for survey multi-select fields.

### ISSUE THREAD

**Issue by cesan3** [ansible/awx#363]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
We'd like to use survey select boxes, to provide the user a dynamic list of values (products, releases, etc...).  Values from a secondary multi-choice selection box, could depend on the value selected on the first one, or be a total dynamic generated list from an api call to a provider service, for example. 

##### STEPS TO REPRODUCE

We want to run a generic job, that has a survey element (multiple options select box) where we ask for the Product Version to deploy.  From that selection, we want to update a second select with a list of releases, queried from an external api.

We'd like to have a configuration mechanism where we specify the source of the select box options.  It could be a source script that takes arguments, and that generates the output, or some other bootstrap, jinja2 or jquery update mechanism.

**Comment by wenottingham** [comment]
Already filed as #20
