### ISSUE TITLE
awx_task & awx_web containers doesn't start after reboot

### ISSUE THREAD

**Issue by rezelh** [ansible/awx#3630]
##### SUMMARY
awx_task & awx_web containers doesn't start after reboot. After flawless installation and import my datas with awx_cli. All works as a expected but break after reboot. I already have changed /tmp dirs.   

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.2
* Operating System:
* Web Browser:

##### ACTUAL RESULTS

Containers never start

**Comment by ryanpetrello** [comment]
Hey @rezelh, we're going to need more than this to go on if you want some help troubleshooting - the full template we provide for bug reports at https://github.com/ansible/awx/issues/new?template=bug_report.md exists for a reason, after all.  You might have better luck having a conversation in #ansible-dev on freenode IRC or on our mailing list (https://groups.google.com/forum/#!forum/awx-project).
