### ISSUE TITLE
Duplicate Entry Syntax validation does not apply on codemirror when using JSON

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#3638]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Duplicate Entry Syntax validation does not apply on codemirror when using JSON

##### ENVIRONMENT
* AWX version: 4.0.0
* Operating System: macos
* Web Browser: firefox, chrome

##### STEPS TO REPRODUCE

1. Open up a codemirror form (i.e. host variable) and toggle to JSON
2. Make a duplicate entry (i.e. ```{ "host": "local", "host": "notlocal"}``` )
3. Switch to YAML
Note: duplicate entry deleted, no console errors

##### EXPECTED RESULTS

1. Validation error/warning.
2. Duplicate value to persist

##### ACTUAL RESULTS

Duplicate value removed

##### ADDITIONAL INFORMATION
![duplicate](https://user-images.githubusercontent.com/12446869/55656709-fdd0bc80-57c5-11e9-92b8-6fe2b6c76765.gif)

**Comment by unlikelyzero** [comment]
@keithjgrant notes that this issue is likely a problem with our json parsing library

**Comment by keithjgrant** [comment]
> @keithjgrant notes that this issue is likely a problem with our json parsing library

Not our library: this is the behavior of the native JSON parsing API in the browser. It’s unlikely we'll be able to do anything here to change this.

**Comment by unlikelyzero** [comment]
Note: not a regression and does not affect functionality (as far as I can tell)

**Comment by ryanpetrello** [comment]
Closing this, as this is just a nuance of how the JSON parsing API works.
