### ISSUE TITLE
Cannot sync project from scm with different port

### ISSUE THREAD

**Issue by py-t** [ansible/awx#3641]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

UI

##### SUMMARY
When I try to clone from my online git repository with a nonstandard ssh port and pubkey authentication, I am getting various errors.

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: Compose
* Ansible version: 2.7.1
* Operating System: Ubuntu
* Web Browser: Irrelvant

##### STEPS TO REPRODUCE
Try to clone repo from git server on a nonstandard port with private key credentials
I tried following scm strings:

> git@myserver:2222/path/to/my/repo.git"
> 
> git://myserver:2222/path/to/my/repo.git"

##### EXPECTED RESULTS
It should work.

##### ACTUAL RESULTS
I am either getting:

    Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"

(while the private key is right -> I think, it just disregards the port)

Or

    Failed to download remote objects and refs:  fatal: Unable to look up git@myserver (port 2222) 

(while the server name is well known and also replacing it by IP address does not help

**Comment by wenottingham** [comment]
What is the final URL passed to the git module?

**Comment by prg318** [comment]
I'm also running into this issue and can provide additional details if necessary

**Comment by tomaszov** [comment]
+1, I have the same issue. Did anyone find any solution?

**Comment by tomaszov** [comment]
Finally after some experimenting, for me the following syntax worked:

ssh://git@mygitserver:mycustomport/myrepo.git

**Comment by pauloreloy** [comment]
> Finally after some experimenting, for me the following syntax worked:
> 
> ssh://git@mygitserver:mycustomport/myrepo.git

This syntax worked for me too...
Thank you so much!

**Comment by shanemcd** [comment]
Looks like you all figured this out, nice work!
