### ISSUE TITLE
Find credential type given a credential

### ISSUE THREAD

**Issue by Spredzy** [ansible/awx#3644]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY

Given a credential `/api/v2/credentials/N`, with v1 we used to be able to find the accurate type by querying `credential.kind` which could be `aws`.

Now with v2, `credential.get_related('credential_type').kind` returns `cloud` and credential.get_related('credential_type').name` return `Amazon Web Services`. But there is no more way to retrieve `aws`.

As I understand it, we could checkt the namespace `aws` to see if the credentials are in there. But from the credentials we can't see the namspace. Which means, in order to find the proper kind, we need to loop over each namespace and check if our credential are in there. Which is iniefficient.

##### ENVIRONMENT

* AWX version: devel

##### STEPS TO REPRODUCE

  * Create a `kind=aws` cred.

##### EXPECTED RESULTS

  * Given the cred find a way to retrieve the `aws` string

##### ACTUAL RESULTS

  * Retrieve `Amazon Web Services`

##### ADDITIONAL INFORMATION

  * N/a

**Comment by AlanCoding** [comment]
You want to list all AWS credentials - `/api/v2/credentials/?credential_type__namespace=aws`

**Comment by ryanpetrello** [comment]
Yes, I think what @Spredzy is asking for is just a summary field on credential that tells you so you don't have to list everything and build the mapping (which I think is fair).  I'll tinker on this as it will be helpful to people migrating to `/api/v2/` in the near future.

**Comment by ryanpetrello** [comment]
@Spredzy this work?

https://github.com/ansible/awx/pull/3647
