### ISSUE TITLE
Configurable project_root for Each Project

### ISSUE THREAD

**Issue by mrmibrown** [ansible/awx#3648]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

The PROJECT_ROOT should be configurable for each project.  This includes SCM TYPE Git as well.

**Comment by wenottingham** [comment]
Why would PROJECT_ROOT need configured for SCM?

**Comment by wenottingham** [comment]
For manual projects, there could conceptually be a use case for "I want to attach a volume for automation", which might require some other mount point, although that doesn't seem like best practice. For SCM projects... this isn't likely to ever be configurable.

**Comment by shanemcd** [comment]
Closing due to lack of interest.
