### ISSUE TITLE
Discrepancy in POST response for jobs vs project & inventory updates

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#365]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
When you launch a job, the API returns the full serialization of the new job, _as if_ you performed a GET to the job detail view.

When you update a project, it returns a minimal response like `{"project_update": 42}`.

Arguably, the project update endpoint (and others) should follow suit and return the full serialization of the newly-created object.

##### STEPS TO REPRODUCE

POST to `/api/v2/job_templates/N/launch/`

POST to `/api/v2/projects/N/update/`

##### EXPECTED RESULTS

consistency

##### ACTUAL RESULTS

somewhat similar

**Comment by matburt** [comment]
This should actually be a pretty easy task as it's just sending that object through the serializer and then returning that. Here's how we do that with the job template launch: https://github.com/ansible/awx/blob/devel/awx/api/views.py#L2822
