### ISSUE TITLE
Limit inventories that a template can use

### ISSUE THREAD

**Issue by jammcder** [ansible/awx#3650]
##### ISSUE TYPE
 - Ability to be able to limit a subset of inventories that a template can run against.

##### COMPONENT NAME

 - UI

##### SUMMARY

Compensating security controls.
We have templates where we allow a user with a lesser level of privilege to launch things as a higher privileged user, even root, as long as we can ensure they can only do what we allow against the servers we allow.  The inventory is part of those controls and as it stands today to enforce this security we have to create a templates to the same thing for every inventory authorized.  It would be easier on us, if we could create one template that could run against a “set” of inventories.

**Comment by wenottingham** [comment]
This is usually done with RBAC and promptable inventories. In any case, #2419 is the specific RFE.
