### ISSUE TITLE
Create a smart inventory from another teams inventory

### ISSUE THREAD

**Issue by jammcder** [ansible/awx#3651]
##### ISSUE TYPE
 - Create a smart inventory from another teams inventory

##### COMPONENT NAME

 - UI

##### SUMMARY

Currently we can not create a smart inventory from another teams inventory even though we have the ability to view it.  It would be nice if we could do this.

**Comment by wenottingham** [comment]
Do you mean organization?

**Comment by jammcder** [comment]
Yes sorry for the confusion.  Here is the breakdown of the conversation that should make it more clear.

Our department is divided into two organizations, Engineering and UNIX, under the UNIX org is a team breakdown for the various groups we have. 
Our Engineering org owns the "master" inventories and the UNIX ORG has the ability to view and execute against the inventories. 
We want to maintain control of the "master inventory" within the Engineering ORG so as to prevent anyone else from modifying it. 

Our Automation team has a need to create smart inventories for various projects we are working on but at this time we cannot create the smart inventory from the "Master" despite having the ability to execute against it.

**Comment by wenottingham** [comment]
OK. Shortest workaround would be to precreate the smart inventory and delegate access to that, and let the team set their own host filter.

**Comment by TheRealHaoLiu** [comment]
Smart inventories has been deprecated in favor of constructed inventory

Please check out https://github.com/ansible/awx/pull/13303
