### ISSUE TITLE
WARNING about json not serializable when using vaulted include_vars

### ISSUE THREAD

**Issue by larsmaes** [ansible/awx#3654]
I have a playbook the includes a vaulted var and when running this task it show this warning:

[WARNING]: Failure using method (v2_runner_on_ok) in callback plugin
(<awx_display_callback.module.AWXDefaultCallbackModule object at
0x7f6cc3b97210>): u'dCMYn3s2rjew5j4Yf2FredPs3zPshbDg' is not JSON serializable

**Comment by ryanpetrello** [comment]
@larsmaes please edit or re-open this ticket using the template provided for AWX bug reports (the more details the better):

https://github.com/ansible/awx/issues/new?template=bug_report.md
