### ISSUE TITLE
When you add team to permission tab, team members are added instead of team itself

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#3665]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When you add a team via permission tab after you grant some permissions instead of the team its members are added to permission list. This is very inpractical.

##### ENVIRONMENT
* AWX version: 4.0.0
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE
Click permissions for a template, add a team there, instead of team its members are added to GUI

##### EXPECTED RESULTS
Add a team as item to permission tab.

##### ACTUAL RESULTS
Members of team are added. So subsequent edits of permissions need to be on individual user basis instead of for whole team. Also adding or removing members to a team later will probably not update this list.

**Comment by AlanCoding** [comment]
> Also adding or removing members to a team later will probably not update this list.

The list will be updated, assuming you refresh the page.

**Comment by wenottingham** [comment]
This is expected behavior; it shows the list, and shows them as having access via their team (under team roles).

**Comment by benapetr** [comment]
And how do you remove whole team from access list if you can only see its members and never the team? How do you change the team privileges? This as much not intuitive as it possibly could be.

**Comment by wenottingham** [comment]
Clicking on the 'X' on a team role will tell you it's removing the role from the team. You can grant permissions to/from a team in batch on the team view.
