### ISSUE TITLE
SCM Update failed

### ISSUE THREAD

**Issue by hudecof** [ansible/awx#367]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
running the template job will failed with the SCM Update failed for testing project with ID 257.

![screen shot 2017-10-05 at 10 37 13](https://user-images.githubusercontent.com/4510160/31218005-3de127c2-a9b9-11e7-97b9-e38ada2ba9a8.png)
![screen shot 2017-10-05 at 10 37 30](https://user-images.githubusercontent.com/4510160/31218006-3e033182-a9b9-11e7-8855-cf902cf6482b.png)

The job is triggering the **SCM Update** job with id **256**. 

The job **257**  in error message I even do not see in job list. I guess, this is inventory sync. The inventory is SMC based /git/.

I I run the inventry sync manualy, it work as expected, see the job **253**

##### ENVIRONMENT
* AWX version: 1.0.0.592
* AWX install method: docker
* Ansible version:  2.4.0
* Operating System: CentOS 7

##### STEPS TO REPRODUCE

run any job, all my jib share the same inventory.

##### EXPECTED RESULTS

job result should be **OK**

##### ACTUAL RESULTS

job will failed, see screenshots.

##### ADDITIONAL INFORMATION

I'm not using the docker registry images, I have build one by the **install.yml** with custom `installer/image_build/files/settings.py`

```
diff --git a/installer/image_build/files/settings.py b/installer/image_build/files/settings.py
index e46051b..ee3c4e7 100644
--- a/installer/image_build/files/settings.py
+++ b/installer/image_build/files/settings.py
@@ -112,3 +112,7 @@ CACHES = {
         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
     },
 }
+
+# added by Peter Hudec
+CUSTOM_ENABLED_VAR = 'host.enabled'
+SCM_ENABLED_VAR = 'host.enabled'
```

**Comment by hudecof** [comment]
the same on version **1.0.0.588** from images on docker hub

**Comment by AlanCoding** [comment]
> The job 257 in error message I even do not see in job list. I guess, this is inventory sync. The inventory is SMC based /git/.

The job 257 is almost certainly a project sync, which runs before every job as a matter of assuring that the source tree on the filesystem has the correct SCM revision. These are hidden from the UI, but you can still find them using the API browser. For instance `http://towerhost.com/api/v2/project_updates/257/`

Is the project "testing project" set to update on launch? Was the inventory source inside of your inventory set to "update on project change"? Do you have any logs from the task manager? It would also help to have details from that project update 257.

**Comment by hudecof** [comment]
running the inventory sync work normal. I tried to rollback back to version **1.0.0.561** but withou luck.
Right now I'm rebuild back the latest version, I will let you know.
I will try also start with empty database for test.

**Comment by hudecof** [comment]
thanks poinintg me to API
```
ERROR! Unable to load data from the requirements file: requirements.yml
```

I fixed typo in `roles/requirements.yml`

**Comment by s17t** [comment]
@AlanCoding, is this by design and well documented ? A failure in checking out one of the requirements will fail the inventory update job without clear explanation.

**Comment by AlanCoding** [comment]
The UI should link to the dependent project sync, in which case you should be able to follow the links and messages to the error. I think we might already have a UI issue for that.
