### ISSUE TITLE
Since 4.0.0 every result seems to increment "successful" jobs counter, even if it's failed

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#3681]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When I start a 3 jobs and they all fail, counters for "successfull" jobs will increment by 3 as well as counter for failed jobs

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE
Launch any job that is going to fail, successful jobs will be incremented

##### EXPECTED RESULTS
Increment failed jobs only

##### ACTUAL RESULTS
Both counters incremented

**Comment by AlanCoding** [comment]
I cannot reproduce this. Did you set the projects for those job templates to update on launch?

**Comment by benapetr** [comment]
yes, but there is 60 sec cache timeout and I don't see any extra scm jobs, for example today it shows 26 failed and 26 succeeded jobs:

<img width="354" alt="image" src="https://user-images.githubusercontent.com/1560121/55976962-ed20ba80-5c8d-11e9-8fd4-4e6d057856ce.png">

Here you can see minimized screenshot of all jobs I can see in jobs page (I made 2 screenshots because I don't know how to make these "tall" screenshots of long pages also jobs were launched from workflows a lot that's why numbers don't seem to be in order):

<img width="445" alt="image" src="https://user-images.githubusercontent.com/1560121/55977153-5bfe1380-5c8e-11e9-8d7a-7561cf12f8eb.png">

![image](https://user-images.githubusercontent.com/1560121/55977224-8c45b200-5c8e-11e9-9970-4434df14245a.png)

These 2 screenshots list all jobs ran this day

**Comment by benapetr** [comment]
Also I count about 30 jobs on that page, despite UI showing 26 success and 26 failed

**Comment by benapetr** [comment]
lots of these jobs are "cancelled" not sure if cancelled now count as successful?

**Comment by shanemcd** [comment]
Sorry we didn't get around to helping you here. It seems like this wasn't a widespread issue based on the lack of activity here. I'm assuming you either fixed this yourself or you gave up. To get help with the current version of AWX open a new issue or for troubleshooting / anything that isnt a bug you can use the mailing list or join our public chatroom: https://github.com/ansible/awx#get-involved
