### ISSUE TITLE
Creating awx containers with 3.0.1 or 4.0.0 prevents initial login with default admin/password

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/awx#3684]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
- **Creating** AWX containers with docker compose enabled at tag ```3.0.1``` or ```4.0.0``` prevents the initial AWX login (which appears fine) with default admin_user (admin) and admin_password (password); this means that all access is forbidden from the GUI.
- No such issue when **creating** awx containers with tags earlier than ```3.0.1``` with the same environment & config.
- No such issue when **upgrading** awx containers to ```4.0.0``` from ```3.0.0```

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.10
* Operating System: Ubuntu disco
* docker-ce: ```5:18.09.5~3-0~ubuntu-bionic```
* Web Browser: chrome

##### STEPS TO REPRODUCE
Inside a python virtualenv:
```
. /path/to/awx/venv/bin/activate
pip2 install -I -U pip
pip2 install -I -U ansible
pip2 install -I -U docker
pip2 install -I -U docker-compose
git checkout 4.0.0
echo "use_docker_compose=true" >> installer/inventory
echo "docker_compose_dir=/path/to/awx/docker-compose" >> installer/inventory
cd installer
ansible-playbook -i inventory install.yml
deactivate
```
##### EXPECTED RESULTS

We should be able to perform the first  login as admin/password.

##### ACTUAL RESULTS

Login forbidden.

##### ADDITIONAL INFORMATION
- postgresql 9.6 is external
- I have also tried with the latest commit to date: ```4.0.0-274-g8383568e3```

**Comment by majerus1223** [comment]
Seeing the same thing

Could not login at all with 'admin' using https://github.com/geerlingguy/awx-container/blob/master/docker-compose.yml

Troubleshooting..

docker exec -it <container> /bin/bash execute the following commands.

```
bash-4.2# awx-manage changepassword admin
CommandError: user 'admin' does not exist
bash-4.2# awx-manage createsuperuser
Username (leave blank to use 'root'): admin
Email address: majerus@domain.com
Password:
Password (again):
Superuser created successfully.
```

Now i can login

**Comment by naren-ambati** [comment]
@majerus1223 that was helpful, but do you think we can pass the admin credentials using "docker run" command.

**Comment by majerus1223** [comment]
If you can I do not know how..

**Comment by ajs-88** [comment]
> Seeing the same thing
> 
> Could not login at all with 'admin' using https://github.com/geerlingguy/awx-container/blob/master/docker-compose.yml
> 
> Troubleshooting..
> 
> docker exec -it /bin/bash execute the following commands.
> 
> ```
> bash-4.2# awx-manage changepassword admin
> CommandError: user 'admin' does not exist
> bash-4.2# awx-manage createsuperuser
> Username (leave blank to use 'root'): admin
> Email address: majerus@domain.com
> Password:
> Password (again):
> Superuser created successfully.
> ```
> 
> Now i can login

This really helps. Thanks,
