### ISSUE TITLE
Clear Failed Host Status

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/awx#3687]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Add a decay setting to host status or all admins to overwrite hosts marked as failed in inventory overview.

Currently the only way to clear the status is to either run a job where the host succeeds or delete the failed job.

**Comment by wenottingham** [comment]
This feature is (very nearly) deprecated and more likely to be removed than enhanced.
