### ISSUE TITLE
InsecureRequestWarning when update inventory

### ISSUE THREAD

**Issue by NazNAzim** [ansible/awx#3691]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
 When I update inventories by my own script, all hosts are added but I have an error appearing : [ERROR]: /var/lib/awx/venv/ansible/lib/python2.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings   InsecureRequestWarning) 

##### ENVIRONMENT
* AWX version: 3.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.6
* Operating System: Debian
* Web Browser: chrome

##### STEPS TO REPRODUCE

* Launch an update inventory script asking an https website

##### EXPECTED RESULTS

* Adding all hosts without error 

##### ACTUAL RESULTS

* Adding all hosts but having an error

**Comment by wenottingham** [comment]
Is it a self-signed cert? If so, this is expected.

**Comment by ryanpetrello** [comment]
@NazNAzim,

Also, are you running a custom inventory script that uses the Python requests library?  Are you using a custom virtualenv, or the default one provided by AWX?  Depending on your setup, you may need to follow the instructions at the link above to ensure that you've enabled certification verification:

https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl

**Comment by NazNAzim** [comment]
@wenottingham No it is not. It is signed by my company's CA.

@ryanpetrello It is a python script using the requests library. I use the default venv provided by AWX. I did the modifications adviced by this doc and re-installed awx and restarted the dockers but I still have the error.

**Comment by ryanpetrello** [comment]
@NazNAzim can you share the inventory script with us (or at least the portion that's using the requests library)?

**Comment by dc-jbd** [comment]
I get these same errors (warnings?) using the devel version of vmware-inventory.py at https://github.com/ansible/ansible/blob/devel/contrib/inventory/vmware_inventory.py
and ansible 2.7.10
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
The inventory run completes though...
