### ISSUE TITLE
Job output is displayed with significant delay

### ISSUE THREAD

**Issue by iturovsky** [ansible/awx#3699]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When I start Job against significant number of hosts (4K), job output is displayed after delay (~ 2 hours).

##### ENVIRONMENT
* AWX version: 2.1.2.0
* AWX install method: docker on linux, SQL database is on separate host. 
* Ansible version:  2.7.4
* Operating System: Debian 9.5
* Web Browser:
Chrome

##### STEPS TO REPRODUCE

Run playbooks against 4k Windows hosts via WinRM
##### EXPECTED RESULTS

Job output like tasks and hosts status
##### ACTUAL RESULTS

```
SSH password: 
Vault password: 
PLAY [all] *********************************************************************
```
No further job output

##### ADDITIONAL INFORMATION

I see that ansible-playbook  and kinit  (I use Kerberos authentication) processes are active on hosts so apparently playbook is running. 
I've also checked API for the job (/api/v2/jobs/1500/job_events/?order_by=counter&page=1&page_size=50), but it also has no new output.

**Comment by ryanpetrello** [comment]
We've made notable bug fixes related to stdout consumption in more recent versions of AWX.  Are you encountering this on the latest version (awx 4.0.0)?

**Comment by mabashian** [comment]
Please re-open if this is still an issue on a more recent version of AWX
