### ISSUE TITLE
credential types inputs/injectors of built-in types cannot be cut-and-pasted

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#370]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

You can't cut and paste credential type configuration.

##### STEPS TO REPRODUCE

Go to `#/credential_types/N`.
Look at input configuration, try and select it to paste elsewhere.

##### EXPECTED RESULTS

Able to select, copy, etc.

##### ACTUAL RESULTS

Can't (at least for built-in types)

##### ADDITIONAL INFORMATION

Yay codemirror.

**Comment by jlmitch5** [comment]
@wenottingham based on the implementation of the lib's disabled state, events are disabled when things are read-only.  A fix will most likely require exploring new codemirror implementations when we look at componentizing this input (in lieu of using our old, form-generator based way of building it)

**Comment by ryanpetrello** [comment]
Closing due to age and UI rewrite.
