### ISSUE TITLE
RFE: Allow adding Job Template to Workflow Job Template Visualizer without prompt setting

### ISSUE THREAD

**Issue by hiyokotaisa** [ansible/awx#3700]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

In the Workflow Job Template Visualizer, we need to set prompt setting in advance when "Prompt on Launch" is enabled on Inventory for Job Template.

But those prompt setting will be ignored when specified Inventory setting on Workflow Job Template.

I'm also reffering the issue: #1731 but I cannot see the similar request on there.
It would be great if we do not have to set prompt when "prompt on launch" setting is enabled.

**Comment by wenottingham** [comment]
Apologies, this isn't clear to me. Are you saying you want to have a promptable configured inventory on a JT that is *not* overridden by the workflow-level inventory?

That's not currently in the plans, if so.

**Comment by hiyokotaisa** [comment]
@wenottingham I'm sorry I didn’t make it clear enough.
When I set "Prompt On Launch" for the Inventory on the Job Template setting as below:

![jobtemplate-1](https://user-images.githubusercontent.com/4246532/56173901-b69ac500-602a-11e9-9d61-15d06311ef7b.png)

I cannot add the Job Template to the Workflow because the "SELECT" button will be grayed out.
![workflow-1](https://user-images.githubusercontent.com/4246532/56173921-d8944780-602a-11e9-94a9-c2fe31f00795.jpg)

I have to set the Inventory in Prompt setting of Workflow Job Template Visualizer as below:
![workflow-2](https://user-images.githubusercontent.com/4246532/56173931-dfbb5580-602a-11e9-9be4-bf730a800eea.jpg)

I would like to avoid the Prompt setting on Workflow Job Template Visualizer since those inventory setting will not be used when I set Inventory on Workflow Job Template directly.

**Comment by unlikelyzero** [comment]
let's retest this ux

**Comment by unlikelyzero** [comment]
retest with stub

**Comment by akus062381** [comment]
Manually verified, stubs added. see https://github.com/ansible/tower-qa/pull/6281
