### ISSUE TITLE
Organization based logging aggregation.

### ISSUE THREAD

**Issue by gamuniz** [ansible/awx#3713]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

In some cases it would be optimal to send specific organizations logging data to a specific splunk instance. This would be especially useful if logstash is unavailable as a logging method.

**Comment by wenottingham** [comment]
Organization is not something that is tracked at the level of where logging is set, so this would require significant architectural changes that are not planned in the short or medium term future.
