### ISSUE TITLE
Workflow template execution with sequential jobs

### ISSUE THREAD

**Issue by NiveditaKumari14** [ansible/awx#3716]
##### ISSUE TYPE
What is the correct behavior of execution when multiple jobs are assigned to the workflow template sequentially. In my observation time taken by workflow template to execute with 2 jobs is greater than the time taken by workflow template with 5 jobs 

##### STEPS TO REPRODUCE
1. Create a workflow template
2. Add 2 and 5 jobs in the workflow template
3. Analyze the time taken for execution

##### EXPECTED RESULTS

When workflow template contain 2 jobs it should take less time for execution as compared to workflow template with 5 jobs.

##### ACTUAL RESULTS

Time should be less when number of jobs in the workflow template is less.

**Comment by ryanpetrello** [comment]
This isn't a bug report.  If you have questions about how AWX works, please try out our mailing list or IRC room on free node (`#ansible-awx`)
