### ISSUE TITLE
AWX API - stdout capture is missing

### ISSUE THREAD

**Issue by castlemilk** [ansible/awx#372]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
After completing the installer process the stdout API for a given job doens't work giving the "stdout capture is missing" message.

##### ENVIRONMENT
* AWX version: 1.0.0.588
* AWX install method: docker for mac
* Ansible version:  2.4.0
* Operating System: MAC OS Sierra - 10.12.6
* Web Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

##### STEPS TO REPRODUCE
1. run $ ansible-playbook -i inventory install.yml
2. run demo job template
3. hit the api: http://localhost/api/v2/jobs/1/stdout/

##### EXPECTED RESULTS

I would expect to see the stdout output from the playbook. 

##### ACTUAL RESULTS

```
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: text/plain ;utf-8
Vary: Accept
X-API-Node: awx
X-API-Time: 0.046s




stdout capture is missing
```

##### ADDITIONAL INFORMATION
Hitting the api with the following formatting:
http://localhost/api/v2/jobs/1/stdout/?format=txt_download
Produces the following logs in the aws_web container:

`
$ docker logs -f awx_web
`

```
...
2017-10-05 22:31:58,451 DEBUG    awx.api.authentication User admin performed a GET to /api/v2/jobs/1/stdout/ through the API
2017-10-05 22:31:58,466 ERROR    django.request Internal Server Error: /api/v2/jobs/1/stdout/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 246, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 210, in get
    return self.retrieve(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/views.py", line 4377, in retrieve
    write_fd = open(unified_job.result_stdout_file, 'w')
**IOError: [Errno 2] No such file or directory: u'/var/lib/awx/job_status/1-ffed3434-a98f-11e7-8747-0242ac110006.out'**
[pid: 27|app: 0|req: 12/55] 172.17.0.1 () {46 vars in 2572 bytes} [Thu Oct  5 22:31:58 2017] GET /api/v2/jobs/1/stdout/?format=txt_download => generated 23 bytes in 103 msecs (HTTP/1.1 404) 3 headers in 119 bytes (1 switches on core 0)
172.17.0.1 - admin [05/Oct/2017:22:31:58 +0000] "GET /api/v2/jobs/1/stdout/?format=txt_download HTTP/1.1" 404 34 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" "-"
...
```
There is no /var/lib/awx/job_status directory being created inside the aws_web container.

**Comment by castlemilk** [comment]
Additionally I see the expected job_status logs in the awx_task container under /var/lib/awx/job_status. Is there a way to bridge these containers so that the stdout api can be used seamlessly? I guess it's happening because having the two containers separate makes the awx_web container a "non-executing node". From the documentation the fix for this is to run:
http://localhost/api/v2/jobs/1/stdout/?format=txt_download
But this doesn't seem to route to the "executing node" but instead hits the awx_web container. From the awx GUI when you click the button to download the stdout from a job it will route to:
http://localhost:8052/api/v2/jobs/1/stdout/?format=txt_download

port 8052 is not exposed by the current install.yml so how is this intending to work in the ansible tower architecture. Is there supposed to be a api server which is an "executing node" which can serve this request?

**Comment by matburt** [comment]
We'll be covering this within  the next few weeks, you can see a basic explanation here: https://groups.google.com/d/msg/awx-project/POJvaHEZL7U/8EDyVBJ8CAAJ

The job detail page itself shows a rendering of the events in stdout form... you can also hit the job_events api endpoint to get the list.

**Comment by llbbl** [comment]
Still having this issue with awx 1.0.5.1 using Docker. Will this be fixed in future releases ?
