### ISSUE TITLE
Replacing credential type detail items should allow to show and hide secret entries

### ISSUE THREAD

**Issue by jpell958** [ansible/awx#3725]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
When editing credential type details, one should be able to "hide" and "show" a secret value.  These options are available when creating the initial credential.  However, only the "replace" or "revert" option is available when editing the credential.  The request is to allow for all four options.

**Comment by ryanpetrello** [comment]
If you're still encountering problems, please reopen this issue using the template provided at https://github.com/ansible/awx/issues/new?template=bug_report.md (please include all of the details requested).

**Comment by ryanpetrello** [comment]
@jpell958,

Which version of AWX are you using, and how is it deployed?  We've recently (in awx 4.0.0) made some notable changes to this UI.

**Comment by jpell958** [comment]
@ryanpetrello,

Thanks for the response.  We just tested the latest version of AWX and saw the functionality we are looking for now exists.  Kudos to all that made this possible.
