### ISSUE TITLE
Filter by a label when it is clicked on

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#373]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
If user clicks on the text of a label, the list should be filtered to objects that have that label.

##### ENVIRONMENT
* AWX version: 1.0.0
* AWX install method: docker for mac
* Ansible version:  N/A
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Add a label to a job template, but leave some job templates without this label. Return to the TEMPLATES list. Click on the label in the LABELS column.

##### EXPECTED RESULTS

Say the label is "foobar"

Expect that clicking the label will filter on the label, as if I had typed "labels:foobar" into the search box.

That means that it should take me to the UI URL: `/#/templates?template_search=page_size:20;order_by:name;type:workflow_job_template,job_template;labels__search_DEFAULT:foobar`

##### ACTUAL RESULTS

Labels are not clickable.

**Comment by mabashian** [comment]
Closing in favor of the more generic https://github.com/ansible/awx/issues/3127
