### ISSUE TITLE
user is not allowed to execute '/bin/sh -c in dzdo privilege escalation

### ISSUE THREAD

**Issue by hiteshshaha** [ansible/awx#3731]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY
I am using privilege escalation (become_method=dzdo) in my playbook to run oracle commands to login to database. I have set dzdo permission to run particular command inside database server but when when i executed playbook ansible is not able to execute dzdo commands even though it has privilege to execute these commands.

##### ENVIRONMENT
* AWX version: NA
* AWX install method: NA
* Ansible version:  2.7.5
* Operating System: Linux
* Web Browser: NA

##### STEPS TO REPRODUCE

Below is playbook which i am using.

---
- name: Test Production Network Connection
  hosts: all
  gather_facts: false
  
  tasks:
  - name: Print Hello message
    debug:
      msg: "Entering Into Prod Network" 
  
  - name: list pmon output
    shell: ps -ef | grep pmon
    register: pmon
    #become: yes
    #become_user: oraacppp
  - name: Privilege escalation
    shell: echo exit | sqlplus / as sysdba
    become: yes
    become_user: oraacppp
    environment:
     ORACLE_HOME: "/ora/product/dbms/11.2.0.4/dblib1"
     ORACLE_BASE: "/ora"
     ORACLE_SID: TEST
     TNS_ADMIN: "/oracle/product/dbms/11.2.0.4/dblib1/network/admin"
     PATH: "/ora/product/dbms/11.2.0.4/dblib1/bin:/ora/product/dbms/11.2.0.4/dblib1/OPatch:$PATH:/bin:/usr/bin::/usr/ccs/bin"
    register: sqlplus

it is giving error in 2nd task name: Privilege escalation

##### EXPECTED RESULTS

playbook should not throw any error it just login to database and logout.

##### ACTUAL RESULTS

i am getting below error (For Task 2 only)

{
    "_ansible_parsed": false,
    "_ansible_no_log": false,
    "module_stderr": "Shared connection to dbserver.ana.com closed.\r\n",
    "changed": false,
    "module_stdout": "Sorry, user ABC is not allowed to execute '/bin/sh -c echo BECOME-SUCCESS-ngakodugvcjuytjsrqpgfahxrajdvaag; PATH='/ora/product/dbms/11.2.0.4/dblib1/bin:/ora/product/dbms/11.2.0.4/dblib1/OPatch:$PATH:/bin:/usr/bin::/usr/ccs/bin' ORACLE_SID=TEST TNS_ADMIN=/ora/product/dbms/11.2.0.4/dblib1/network/admin ORACLE_BASE=/ora ORACLE_HOME=/ora/product/dbms/11.2.0.4/dblib1 /usr/bin/python /tmp/ansible-tmp-155557rtt3951.28-210342729760200rtrt/command.py' as oraacppp on dbserver.ana.com.\r\n",
    "failed": true,
    "rc": 1,
    "msg": "MODULE FAILURE"
}

##### ADDITIONAL INFORMATION

I am suspecting issue with issue with dzdo commands with option -c /bin/sh which ansible couldnt do.

I am login to database server with user "ABC" and then using privilege escalation to execute commands with user "oraacppp"

dzdo access has been given to below command on db server

/ora/product/dbms/11.2.0.4/dblib1/bin/sqlplus .* run as oraacppp

**Comment by sayantandas** [comment]
try setting `executable=/bin/bash` in a custom ansible.cfg and add it to the base of the repository. I faced the same issue and fixed it using this method

**Comment by ryanpetrello** [comment]
This issue list is for tracking bugs in Ansible AWX, not Ansible itself.
