### ISSUE TITLE
installing custom python module problem

### ISSUE THREAD

**Issue by GrishaDev** [ansible/awx#3732]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I am trying to install extra python module for awx, in my case pymongo.
I thought going to docker awx_task and activating virtualenv of either ansible or awx in
/var/lib/awx/venv/  and then performing pip install will do the trick, but it didn't.(it worked but when running playbooks in awx it said missing module pymongo, i tried restart docker etc)
so i found this link:
https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md
and followed it.

##### ENVIRONMENT
* AWX version: 3.0.0
* AWX install method: docker compose
* Ansible version:  2.7.6
* Operating System: redhat 7.6
* Web Browser: chrome 65

##### STEPS TO REPRODUCE

I created directory on my awx_task docker, and made it into virtualenv as told by guide.
i tried both python 2.7 and 3 methods, and i tried in /var/lib/awx/venv/ and just /opt/my-venv like told in the guide.

then i did http request via the UI of awx api in /api/v2/settings/system
`HTTP PATCH /api/v2/settings/system {'CUSTOM_VENV_PATHS': ["/opt/my-envs/"]}`

obviously i got auth.

##### EXPECTED RESULTS

i got error JSON parse error Expecting property name enclosed in double quotes: line 1 column 2( char 1)\n Possible cause: trailling coma.

so i tried without the ' '  and instead " " as:
`HTTP PATCH /api/v2/settings/system {"CUSTOM_VENV_PATHS": ["/opt/my-envs/"]}`

and it didn't give error.

##### ACTUAL RESULTS

nothing happened
/api/v2/config/ doesn't show my custom vritualenv.

##### ADDITIONAL INFORMATION

https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md

**Comment by ryanpetrello** [comment]
@GrishaDev,

`CUSTOM_VENV_PATHS` is a new feature in AWX 4.0.0

If you don't want to upgrade, just create your custom venv in `/var/lib/awx/venv/` (no settings update necessary).

**Comment by GrishaDev** [comment]
> @GrishaDev,
> 
> `CUSTOM_VENV_PATHS` is a new feature in AWX 4.0.0
> 
> If you don't want to upgrade, just create your custom venv in `/var/lib/awx/venv/` (no settings update necessary).

I did that but it still doesnt work, i created custom venv in /var/lib/awx/venv/ ,
switched to the new venv by using source activate  and performed pip install pymongo, it worked succesfuly but when running the playbook in awx, it still says it doesnt find pymongo.

**Comment by ryanpetrello** [comment]
@GrishaDev,

I'm not able to reproduce this with a custom virtualenv in `devel` of awx (I didn't actually install mongo, but you can see that the `mongodb_user` module is working):

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/214912/56364231-11175b00-61bc-11e9-9b81-e17e5f89c597.png">

```shell
bash-4.2$ cat /projects/mongo/example.yml
- hosts: all
  gather_facts: false
  tasks:
    - name: add admin user to mongo
      mongodb_user:
        login_port: 27017
        database: admin
        name: admin
        password: password
        roles: userAdminAnyDatabase
        state: present
bash-4.2$ /venv/ryan/bin/pip freeze
ansible==2.7.10
asn1crypto==0.24.0
bcrypt==3.1.6
cffi==1.12.2
cryptography==2.6.1
Jinja2==2.10.1
MarkupSafe==1.1.1
paramiko==2.4.2
psutil==5.6.1
pyasn1==0.4.5
pycparser==2.19
pymongo==3.7.2
PyNaCl==1.3.0
PyYAML==5.1
six==1.12.0
```

**Comment by GrishaDev** [comment]
@ryanpetrello Weird, maybe i am doing something small wrong, if you have some time could you verify i am doing everything correct?

Steps:
* go to awx task docker
* go to /var/lib/awx/venv/
* created new venv here, lets say using python 2.7
* activate the venv with source activate
* pip install pymongo
* restart docker( just in case) 
* run the playbook in awx

thanks

**Comment by ryanpetrello** [comment]
@GrishaDev,

Can you share the output of this command?

`/var/lib/awx/venv/bin/pip freeze`

Also, you shouldn't need to restart Docker for this to take effect.

**Comment by GrishaDev** [comment]
> @GrishaDev,
> 
> Can you share the output of this command?
> 
> `/var/lib/awx/venv/bin/pip freeze`
> 
> Also, you shouldn't need to restart Docker for this to take effect.

@ryanpetrello Hey sorry for delayed reply,  /var/lib/awx/venv contains  ansible or awx directories, and each of them are seperate venv that contain bin directory.
I assumed awx is the venv used by awx, so i did  `/var/lib/awx/venv/awx/bin/pip freeze` :

`ansible==2.7.6
Babel==0.9.6
backports.ssl-match-hostname==3.5.0.1
cffi==1.6.0
chardet==2.2.1
cryptography==1.7.2
enum34==1.0.4
idna==2.4
iniparse==0.4
ipadress==1.0.16
Jinja2==2.8
kitchen==1.1.1
MarkupSafe==0.11
meld3==1.0.2
mercurial==2.6.2
paramiko==2.1.1
ply==3.4
psutil==2.2.1
psycopg2==2.7.5
pyasn1==0.1.9
pycparser==2.14
pycurl==7.19.0
pygobject==3.22.0
pygpgme==0.3
pyliblzma==0.5.3
pyxattr==0.5.1
PyYAML==3.10
six==1.9.0
supervisor==3.3.5
urlgrabber==3.10
virtualenv==16.3.0
yum-metadata-parser==1.1.4`


For some reason pymongo is missing here, i don't know if its intended, but pymongo appears if i activate the awx venv and run pip list.

**Comment by ryanpetrello** [comment]
Yep, I typo'd something.

What you want is:

`/var/lib/awx/venv/your-custom-venv/bin/pip freeze`

I _suspect_ that you won't see `pymongo` in there, and if that's the case, it sounds like you probably installed `pymongo` in your *global* system site-packages and want to do _this_ instead:

`/var/lib/awx/venv/your-custom-venv/bin/pip install pymongo`

**Comment by GrishaDev** [comment]
> Yep, I typo'd something.
> 
> What you want is:
> 
> `/var/lib/awx/venv/your-custom-venv/bin/pip freeze`
> 
> I _suspect_ that you won't see `pymongo` in there, and if that's the case, it sounds like you probably installed `pymongo` in your _global_ system site-packages and want to do _this_ instead:
> 
> `/var/lib/awx/venv/your-custom-venv/bin/pip install pymongo`

@ryanpetrello I only have 2 venvs in /var/lib/awx/venv,   which are ansible and awx.
Both have pymongo when i did pipfreeze( i installed on both)
By the environment value in playbook, i can see my awx is using the ansible venv.

In any case, it still doesn't work, when running the playbook it throws error:
the python pymongo module is required.

I have a feeling it's something small and dumb ;/

Oh and yes and i ran exactly the ansible code of pymongo you posted here, for test.

could it be problem in my specific version of awx?

**Comment by ryanpetrello** [comment]
@GrishaDev if you only have two virtualenvs in `/var/lib/awx/venv`, it sounds like you haven't followed the instructions at https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md

When playbooks run in AWX, the `/var/lib/awx/venv/ansible` virtualenv is activated (unless you've configured a *custom* virtualenv following the instructions in my link above).

**Comment by GrishaDev** [comment]
> @GrishaDev if you only have two virtualenvs in `/var/lib/awx/venv`, it sounds like you haven't followed the instructions at https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md
> 
> When playbooks run in AWX, the `/var/lib/awx/venv/ansible` virtualenv is activated (unless you've configured a _custom_ virtualenv following the instructions in my link above).

@ryanpetrello but you said earlier on this post that because of my awx version, i don't need to follow this file as its made for awx 4.0.0(and i tried it anyway but it didnt work as why i opened this issue)
I tried manually creating custom venv but it didn't work, unless i need to specify awx to use it somehow without the API?

When i am trying the last option of api:

` PATCH https://awx-host.example.org/api/v2/organizations/N/
PATCH https://awx-host.example.org/api/v2/projects/N/
PATCH https://awx-host.example.org/api/v2/job_templates/N/

Content-Type: application/json
{
    'custom_virtualenv': '/opt/my-envs/custom-venv'
} `

it says  /var/lib/awx/venv/custom is not valid virtualenv.

however i made it into virtualenv with virtualenv command.

**Comment by ryanpetrello** [comment]
@GrishaDev,

What does this print?

```shell
~ /opt/my-envs/custom-venv/bin/pip freeze | grep pymongo
```

I've just run through the instructions in https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md again, installing pymongo into my custom virtualenv, and it works fine for me, so I suspect you're missing a step somewhere.

**Comment by GrishaDev** [comment]
> @GrishaDev,
> 
> What does this print?
> 
> ```shell
> ~ /opt/my-envs/custom-venv/bin/pip freeze | grep pymongo
> ```
> 
> 
@ryanpetrello  I've just run through the instructions in https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md again, installing pymongo into my custom virtualenv, and it works fine for me, so I suspect you're missing a step somewhere.

I am sorry its taking long but this is a bit complicated ;D
/opt/ directory is empty and ~ /opt which is /root/opt doesn't exist.
Do i have to create custom venv in /opt directory?
I have a feeling the problem is because we have different versions.

**Comment by ryanpetrello** [comment]
@GrishaDev 

The steps are:

1.  Create a virtualenv in the web *and* task container in a location of your choosing using `virtualenv` or `python3 -m venv`.
2.  Install dependencies into that virtualenv: `/path/to/your-venv/bin/pip install pymongo`
3.  Update AWX settings so it knows where to find your virtualenv:

```
HTTP PATCH /api/v2/settings/system {'CUSTOM_VENV_PATHS': ["/path/to/"]}
```

4.  Assign the virtualenv to a Job Template and run it.

**Comment by GrishaDev** [comment]
> @GrishaDev
> 
> The steps are:
> 
> 1. Create a virtualenv in the web _and_ task container in a location of your choosing using `virtualenv` or `python3 -m venv`.
> 2. Install dependencies into that virtualenv: `/path/to/your-venv/bin/pip install pymongo`
> 3. Update AWX settings so it knows where to find your virtualenv:
> 
> ```
> HTTP PATCH /api/v2/settings/system {'CUSTOM_VENV_PATHS': ["/path/to/"]}
> ```
> 
> 1. Assign the virtualenv to a Job Template and run it.

@ryanpetrello 

But you said...

CUSTOM_VENV_PATHS is a new feature in AWX 4.0.0

If you don't want to upgrade, just create your custom venv in /var/lib/awx/venv/ (no settings update necessary).


Again i have awx 3.0.0.

Please read the post again to save time, its running in circles.
Thanks

**Comment by ryanpetrello** [comment]
@GrishaDev,

If you're on awx 3.0.0, just put your custom virtualenv in `/var/lib/awx/venv/` and skip the `CUSTOM_VENV_PATHS` step.

Make sure you've run e.g.,

`/var/lib/awx/venv/my-custom-venv-name/bin/pip install pymongo`

**Comment by GrishaDev** [comment]
> @GrishaDev,
> 
> If you're on awx 3.0.0, just put your custom virtualenv in `/var/lib/awx/venv/` and skip the `CUSTOM_VENV_PATHS` step.
> 
> Make sure you've run e.g.,
> 
> `/var/lib/awx/venv/my-custom-venv-name/bin/pip install pymongo`

@ryanpetrello  again we are running in circles, you are telling me what you told before, and i told you it didn't work, please re read the posts here.

**Comment by ryanpetrello** [comment]
@GrishaDev I've tried it in my environment using the instructions in the documentation and it works 🤷‍♂

**Comment by GrishaDev** [comment]
> @GrishaDev I've tried it in my environment using the instructions in the documentation and it works 🤷‍♂

@ryanpetrello 
Well idk, thanks, sorry it took long.
I guees i will just update to awx 4.0.0.
