### ISSUE TITLE
Support PostgreSQL 10

### ISSUE THREAD

**Issue by LukeShortCloud** [ansible/awx#374]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - Installer

##### SUMMARY
PostgreSQL 10.0 was just released. It features great improvements such as more efficient streaming replication, faster performance, and better user security by using SHA256 instead of MD5 for users' password hashes. Since this is the development environment for Ansible Tower, it would be great to see this version supported and tested out for a future release of Tower (3.3 or 3.4).

##### ENVIRONMENT
* AWX version: 1.0.0-588
* AWX install method: all

##### STEPS TO REPRODUCE
Install AWX. It will deploy a PostgreSQL 9.6 container.

##### EXPECTED RESULTS
Installing AWX should deploy and use PostgreSQL 10.0.

##### ACTUAL RESULTS
PostgreSQL 9.6 is installed and used.

##### ADDITIONAL INFORMATION
Release highlights: https://www.postgresql.org/about/news/1786/
Major upgrades notes for PostgreSQL 9 to 10: https://www.postgresql.org/docs/10/static/release-10.html#idm46046834255504
Full release notes: https://www.postgresql.org/docs/10/static/release-10.html

**Comment by dansou901** [comment]
what about directly using postgres 12 which is also just released and the current lts?

**Comment by dansou901** [comment]
maybe also the title of this issue needs to be updated then...

**Comment by geerlingguy** [comment]
I know Tower itself now requires Postgres 10 (see https://docs.ansible.com/ansible-tower/latest/html/installandreference/requirements_refguide.html), so it would seem AWX probably does too?

**Comment by ryanpetrello** [comment]
@geerlingguy thanks for the heads up - recent versions of AWX now use Postgres 10 (so this can be closed).
