### ISSUE TITLE
Ansible Module unarchive is unable to work

### ISSUE THREAD

**Issue by bhushanm90** [ansible/awx#3742]
I am unable to extract tar.gz file using unarchive module in Ansible
OS: Centos7
Ansible Version: 2.7
++++++++++++++ Error  +++++++++++
TASK [Extract the JDK file] ************************************************************************************************************
fatal: [3.17.73.46]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/opt/jdk-9.0.4_linux-x64_bin.tar.gz\". Make sure the required command to extract the file is installed. Command \"unzip\" not found. Command \"/bin/gtar\" could not handle archive."}
        to retry, use: --limit @/home/ansible/ansible/playbooks/jdk_install_tar_tmp.retry

+++++++++++++++++++++

**Comment by ryanpetrello** [comment]
Hey @18414,

This issue tracker is for the Ansible AWX project, not Ansible itself.
