### ISSUE TITLE
ansible awx cannot start the containers

### ISSUE THREAD

**Issue by FEspinha** [ansible/awx#3744]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After git clone the repository and run the install.yml playbook the installation encounters an error on the task [local_docker : Start the containers]

Please see actual results below 

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: docker on linux
* Ansible version:  2.7.10
* Operating System: Centos 7.5

##### STEPS TO REPRODUCE

ansible-playbook -i inventory install.yml -vvv

##### EXPECTED RESULTS

AWX installation successful.

##### ACTUAL RESULTS
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_docker_service_payload_GzPXZp/__main__.py", line 743, in cmd_up
    timeout=self.timeout)
  File "/usr/lib/python2.7/site-packages/compose/project.py", line 527, in up
    svc.ensure_image_exists(do_build=do_build, silent=silent)
  File "/usr/lib/python2.7/site-packages/compose/service.py", line 354, in ensure_image_exists
    self.pull(silent=silent)
  File "/usr/lib/python2.7/site-packages/compose/service.py", line 1222, in pull
    return progress_stream.get_digest_from_pull(event_stream)
  File "/usr/lib/python2.7/site-packages/compose/progress_stream.py", line 102, in get_digest_from_pull
    for event in events:
  File "/usr/lib/python2.7/site-packages/compose/service.py", line 1187, in _do_pull
    output = self.client.pull(repo, **pull_kwargs)

fatal: [localhost]: FAILED! => {
    "changed": false,
    "errors": [],
    "invocation": {
        "module_args": {
            "api_version": "auto",
            "build": false,
            "cacert_path": null,
            "cert_path": null,
            "debug": false,
            "definition": null,
            "dependencies": true,
            "docker_host": "unix://var/run/docker.sock",
            "files": null,
            "hostname_check": false,
            "key_path": null,
            "nocache": false,
            "project_name": null,
            "project_src": "/tmp/awxcompose",
            "pull": false,
            "recreate": "smart",
            "remove_images": null,
            "remove_orphans": false,
            "remove_volumes": false,
            "restarted": true,
            "scale": null,
            "services": null,
            "ssl_version": null,
            "state": "present",
            "stopped": false,
            "timeout": 10,
            "tls": false,
            "tls_hostname": "localhost",
            "tls_verify": false
        }
    },
    "module_stderr": "",
    "module_stdout": "",
    "msg": "Error starting project pull() got an unexpected keyword argument 'platform'"

Is there any issue similar to this one or am I doing anything wrong here?

Thanks!

Filipe

**Comment by ryanpetrello** [comment]
Can you share the output of:

```
docker-compose --version
```

**Comment by ryanpetrello** [comment]
Can you share:

```
docker-compose --version
```

This sounds like an incompatibility (either something changed in a newer version, or you're using an older version).

**Comment by FEspinha** [comment]
Hi Ryan,

Yes of course:
[root@smoke-awx ~]# docker-compose version
docker-compose version 1.24.0, build 0aa5906
docker-py version: 2.4.2
CPython version: 2.7.5
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017

**Comment by FEspinha** [comment]
I'll try to run a new installation and then I'll get back to you again, since celery service was not installed :-S

Thanks!

**Comment by FEspinha** [comment]
Hi, same thing after runned a new installation but different error:

The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_docker_service_payload_R_hbxQ/ansible_docker_service_payload.zip/ansible/module_utils/docker_common.py", line 228, in __init__
    super(AnsibleDockerClient, self).__init__(**self._connect_params)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 190, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 215, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_version": "auto",
            "build": false,
            "cacert_path": null,
            "cert_path": null,
            "debug": false,
            "definition": null,
            "dependencies": true,
            "docker_host": "unix://var/run/docker.sock",
            "files": null,
            "hostname_check": false,
            "key_path": null,
            "nocache": false,
            "project_name": null,
            "project_src": "/var/lib/awx",
            "pull": false,
            "recreate": "smart",
            "remove_images": null,
            "remove_orphans": false,
            "remove_volumes": false,
            "restarted": true,
            "scale": null,
            "services": null,
            "ssl_version": null,
            "state": "present",
            "stopped": false,
            "timeout": 10,
            "tls": false,
            "tls_hostname": "localhost",
            "tls_verify": false
        }
    },
    "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))"
}
        to retry, use: --limit @/root/awx/installer/install.retry

PLAY RECAP **************************************************************************************************************************************************************************************
localhost                  : ok=8    changed=2    unreachable=0    failed=1

**Comment by ryanpetrello** [comment]
Looks like you also may want to upgrade your Python `docker` library.
