### ISSUE TITLE
Variable precedence in ansible.cfg is not preserved

### ISSUE THREAD

**Issue by basos9** [ansible/awx#3745]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Variable precedence configuration seems to not apply on ansible awx.

This is a useful behavior to implement inventory specializations for group variables of default group variables as defined in playbook.

##### ENVIRONMENT
* AWX version: 3.0.0
* AWX install method: docker compose on linux
* Ansible version:  2.7.6
* Operating System: debian 9
* Web Browser: firefox

##### STEPS TO REPRODUCE
Create the following
```
inv-dev/
  group_vars/
    group1.yml
  hosts
sys
  group_vars
    group1.yml
  playbook.yml
ansible.cfg
```
inv-dev/hosts
```
[group1]
test1
```

inv-dev/group_vars/group1.yml
```
---
  new_var: "inventory dev"
  inv_var: "inv dev"
```

sys/group_vars/group1.yml
```
---
  new_var: "playbook"
  pb_var: "pb"
```

sys/playbook.yml
```
---
- name: test vars
  hosts: group1
  gather_facts: false
  connection: local
  tasks:
  - name: show vars
    debug:
      msg: "NEW: {{ new_var }}, PB: {{ pb_var }}, INV: {{ inv_var }}"
```

ansible.cfg
```
[defaults]
;; CHANGE variables precedence,
; Change precedence groups_plugins_inventory > group_plugins_play
; https://docs.ansible.com/ansible/latest/reference_appendices/config.html#variable-precedence
; Default
; precedence = all_inventory, groups_inventory, all_plugins_inventory, all_plugins_play, groups_plugins_inventory, groups_plugins_play
precedence = all_inventory, groups_inventory, all_plugins_play, all_plugins_inventory, groups_plugins_play, groups_plugins_inventory 
```

##### EXPECTED RESULTS
This is the output of ansiple core command:

ansible-playbook -i inv-dev/ sys/playbook.yml
```

PLAY [test vars] ********************************************************************

TASK [show vars] ********************************************************************
ok: [test1] => {
    "msg": "NEW: inventory dev, PB: pb, INV: inv dev"
}

PLAY RECAP **************************************************************************
test1    : ok=1    changed=0    unreachable=0    failed=0   
```

##### ACTUAL RESULTS
```
PLAYBOOK: playbook.yml *********************************************************
1 plays in sys/playbook.yml

PLAY [test vars] ***************************************************************

TASK [show vars] ***************************************************************
ok: [test1] => {
    "msg": "NEW: playbook, PB: pb, INV: inv dev"
}

PLAY RECAP *********************************************************************
test1    : ok=1    changed=0    unreachable=0    failed=0   
```

The culprit is the line
```
"msg": "NEW: playbook, 
```

as it seems new_var kept the value of playbook group vars, despite that variable precedence was changed to favor inventory groups variables.

**Comment by AlanCoding** [comment]
> precedence = all_inventory, groups_inventory, all_plugins_play, all_plugins_inventory

It is a known limitation of this two-step process (saving, then loading, inventory) that inventory plugin vars are converted to direct inventory vars.

I would like to know if this ordering would obtain your desired result, and whether there is any other incompatibility with your use case.

> precedence = all_inventory, groups_inventory, all_plugins_inventory, all_plugins_play

**Comment by basos9** [comment]
Hi, I tried it and it failed
```
task path: /var/lib/awx/projects/_30__test_awx_bugs/sys/playbook.yml:7

fatal: []: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'pb_var' is undefined\n\nThe error appears to have been in '/var/lib/awx/projects/_30__test_awx_bugs/sys/playbook.yml': line 7, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n  - name: show vars\n    ^ here\n"}
```
Now it totally ignores playbook variables.


ansible.cfg
```
[defaults]
precedence = all_inventory, groups_inventory, all_plugins_inventory, all_plugins_play
```

**Comment by AlanCoding** [comment]
It looks like I miscommunicated, I was trying to zone in on the first part of the setting, and the full setting should be:

> precedence = all_inventory, groups_inventory, all_plugins_inventory, all_plugins_play groups_plugins_play, groups_plugins_inventory

You are very probably missing the playbook-adjacent group plugin vars, which is exactly what 'pb_var' is. Sorry, I didn't mean to suggest removing that entry from the list, only rearranging the first 4 items.

**Comment by basos9** [comment]
Ok, I tried also the new suggestion (which is almost the default despite the last groups_plugins_*) and it didn't work.

```
task path: /var/lib/awx/projects/_30__test_awx_bugs/sys/playbook.yml:7
ok: [test1.stage] => {
    "msg": "NEW: playbook, PB: pb, INV: inv dev"
}
```

ansible.cfg
```
precedence = all_inventory, groups_inventory, all_plugins_inventory, all_plugins_play, groups_plugins_play, groups_plugins_inventory
```

**Comment by AlanCoding** [comment]
It should have saved `new_var: "inventory dev"` to the group in the inventory. Could you check `group1` in the inventory, and see if this shows `new_var` in its variables in the UI or API? This would further disambiguate the bug.

My thinking is that this variable should have changed status from `groups_plugins_inventory` to `groups_inventory`, but you report that it is still losing to `new_var: "playbook"` which has status of `all_plugins_play`.

**Comment by basos9** [comment]
the group inventory variables are ok:
![image](https://user-images.githubusercontent.com/1616441/56587252-e11bed80-65e9-11e9-884d-d90186520917.png)

How could I tell the "Status" of a variable ?

I even tried to increase groups_inventory priority over all_plugins_play
```
precedence =  all_inventory, all_plugins_play, all_plugins_inventory, groups_inventory, groups_plugins_play, groups_plugins_inventory 
```

it didn't also work.

**Comment by AlanCoding** [comment]
yep, I don't know why that wouldn't work.

I'm pretty sure you specified it correctly

https://github.com/ansible/ansible/blob/devel/lib/ansible/config/base.yml

```yaml
VARIABLE_PRECEDENCE:
  name: Group variable precedence
  default: ['all_inventory', 'groups_inventory', 'all_plugins_inventory', 'all_plugins_play', 'groups_plugins_inventory', 'groups_plugins_play']
  description: Allows to change the group variable precedence merge order.
  env: [{name: ANSIBLE_PRECEDENCE}]
  ini:
  - {key: precedence, section: defaults}
  type: list
  version_added: "2.4"
```

the key and section matches.

**Comment by basos9** [comment]
The config's syntax is ok since I test it always with ansible core, and it works with the desired behavior.

**Comment by basos9** [comment]
What seemed to work is this
```
precedence =  all_inventory, all_plugins_play, all_plugins_inventory, groups_plugins_play, groups_inventory, groups_plugins_inventory 
```

So the logic is to put the 
all play < all inventory < groups_play <  group_inventory

What is the difference between all_inventory and all_plugins_inventory and likewise groups_inventory, groups_plugins_inventory?

```
TASK [show vars] ***************************************************************
task path: /var/lib/awx/projects/_30__test_awx_bugs/sys/playbook.yml:7
ok: [test1.stage] => {
    "msg": "NEW: inventory dev, PB: pb, INV: inv dev"
}
```

**Comment by AlanCoding** [comment]
> What is the difference between all_inventory and all_plugins_inventory and likewise groups_inventory, groups_plugins_inventory?

My assumptions up until this point:

 - all_plugins_inventory: a file `group_vars/all.yml` adjacent to the inventory file
 - groups_plugins_inventory: a file `group_vars/group_name.yml` adjacent to the inventory file, you have this
 - groups_inventory: vars defined for the group in the inventory file itself

I see how these could be interpreted differently, so take it with a grain of salt

**Comment by ryanpetrello** [comment]
Not really a bug, this is just how it works.

**Comment by Fafadji** [comment]
Hi

I spent some time looking for the answer
Here is the behaviour I found from my tests

```
[defaults]
; last win precedence
; reference : 
;;  https://docs.ansible.com/ansible/latest/reference_appendices/config.html#variable-precedence
;;  https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
;;;;; default ;;;;;
; all_inventory               = hosts[all:vars]                  = inventory file or script group vars/all
; groups_inventory            = hosts[group:vars]                = inventory file or script group vars/*
; all_plugins_inventory       = inventories/ENV/group_vars/all   = inventory group_vars/all
; all_plugins_play            = group_vars/all                   = playbook group_vars/all
; groups_plugins_inventory    = inventories/ENV/group_vars/*     = inventory group_vars/* 
; groups_plugins_play         = group_vars/*                     = playbook group_vars/* 

;;;;; custom ;;;;;
; all_inventory               = hosts[all:vars]                  = inventory file or script group vars/all
; groups_inventory            = hosts[group:vars]                = inventory file or script group vars/*
; all_plugins_play            = group_vars/all                   = playbook group_vars/all
; groups_plugins_play         = group_vars/*                     = playbook group_vars/* 
; all_plugins_inventory       = inventories/ENV/group_vars/all   = inventory group_vars/all
; groups_plugins_inventory    = inventories/ENV/group_vars/*     = inventory group_vars/* 

; precedence = all_inventory, groups_inventory, all_plugins_inventory, all_plugins_play, groups_plugins_inventory, groups_plugins_play
precedence = all_inventory, groups_inventory, all_plugins_play, groups_plugins_play, all_plugins_inventory, groups_plugins_inventory
```
