### ISSUE TITLE
Copying a credential does not copy all fields

### ISSUE THREAD

**Issue by elyezer** [ansible/awx#3750]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

When copying any credential not all fields are copied, for example the owner. See the additional information for an screenshot.

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker on linux
* Ansible version:  2.7
* Operating System: Fedora 29
* Web Browser: Chrome and Firefox

##### STEPS TO REPRODUCE

Copy any credential of any type and see the owners column. The copied one won't have an owner.

##### EXPECTED RESULTS

The copied credential has the same owner or set the owner to the user that copied it.

##### ACTUAL RESULTS

No owners are set to the copied credential.

##### ADDITIONAL INFORMATION

![Screenshot from 2019-04-22 16-15-58](https://user-images.githubusercontent.com/48132/56526147-f1649780-6519-11e9-8c72-af009d1bad79.png)

**Comment by AlanCoding** [comment]
Does the same thing happen if the owner does not have implicit access via org admin or system admin?

**Comment by ryanpetrello** [comment]
Addressed by https://github.com/ansible/awx/pull/3801

**Comment by elyezer** [comment]
I was able to verify this by doing the following:

1. Create 3 credentials of different types.
2. Copied each of the credentials
3. Checked if the owner was copied as well.

I've also tried with different users and checked that the owner was set to the user copying the credential.
