### ISSUE TITLE
[RFE] Add prompt on launch option when multiple instance groups are set directly on the JT

### ISSUE THREAD

**Issue by pravindmali** [ansible/awx#3752]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

An administrator can assign instance groups to organizations. Once instance groups are assigned, In that organization, single job template with 'prompt on launch' option will be prompted upon launch to choose a 'Instance group' to be selected.

**Comment by wenottingham** [comment]
What is the use case here? Why/how would the user know what to choose?

**Comment by pravindmali** [comment]
Currently to run a job in different instance groups, it's required to create one job per instance group or need to edit the JT everytime to change instance group. 
 
So here scenario is , Once the instance groups(say A,B,C,D) is assigned to organization then users in that organization can choose any of the instance group from A,B,C,D  If we add "prompt on launch" option in Job template. And there is no need to create different JT for each instance group or edit it.

**Comment by wenottingham** [comment]
-> #2785
