### ISSUE TITLE
External Logger needs `organization` information at activity_stream

### ISSUE THREAD

**Issue by sugitk** [ansible/awx#3759]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

We know the organization structure though,  the event of activity_stream needs `organization`.  For example, job template doesn't belong to organization directly, however the customer needs the information about that.

https://docs.ansible.com/ansible-tower/latest/html/userguide/organizations.html#organizations

**Comment by wenottingham** [comment]
This is not a thing that exists. The activity stream logs the creation and changes of objects in Tower; it is not going to record organization for objects that do not have it.
