### ISSUE TITLE
Load plugins from the root of the project

### ISSUE THREAD

**Issue by orgito** [ansible/awx#376]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
In my projects I have several playbooks organized by folder. For example:
```
├── playbooks
│   ├── network
│   │   └── facts.yml
│   ├── spectrum
│   │   ├── common
│   │   │   ├── _fix_start_ss.yml
│   │   │   └── _restrict.yml
│   │   ├── files
│   │   │   └── fixedStartSS.pl
│   │   ├── patch
│   │   │   ├── _apply_patch.yml
│   │   │   ├── main.yml
│   │   ├── recover
│   │   │   ├── filter_plugins -> ../../../plugins/filter_plugins/
│   │   │   ├── main.yml
│   │   │   └── _recover.yml
│   └── wlc
│       └── sysinfo.yml
└── plugins
    └── filter_plugins
        └── lsprimary.py
```

If I want to reuse the lsprimary filter plugin I need to copy it to every playbook or create a symlink. AWX should load the plugins from the plugins folder in the root of the project, like its done for roles.

##### ENVIRONMENT
* AWX version: 1.0.0.561
* AWX install method: docker on linux
* Ansible version:  2.4.0.0
* Operating System: Centos 7.4

**Comment by matburt** [comment]
This is actually controlled by ansible itself. I'll note that you can provide an `ansible.cfg` with your project which could control loading of plugins that way.
