### ISSUE TITLE
SCM Update gets stucked in AWX Ansible 4.0 (in task update project using git)

### ISSUE THREAD

**Issue by jperttul** [ansible/awx#3760]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
New Ansible AWX environment has been built from scratch. Postgres DB 9.6 runs in separate node. AWX installation is done by cloning the main repo and then running ansible-playbook -i inventory install.yml. After installation a git credential is created and then Project with the created credential. Running the SCM update gets stucked on the [update project using git].

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.10
* Operating System: CentOS Linux release 7.6.1810 (Core) 
* Web Browser: Firefox, Chrome

##### STEPS TO REPRODUCE
1. Make a new installation of 4.0  from scratch with separate postgres.
2. Create a credential with username + encrypted scm private key
3. Create a Project with the created credential and type Git with URL ssh://git@gitlabxxxx.xxxx.xxx.xx.xx/xx.git

##### EXPECTED RESULTS

When running the scm update the repository gets updated.

##### ACTUAL RESULTS

Playbook runs get stcuked all the time (different crredental variaions used, docker containers rebuild, reboots done etc.) to the [update project using git]

##### ADDITIONAL INFORMATION

Works nicely in AWX 3.0.1 but not anymore in 4.0.0.

**Comment by extjperttula** [comment]
Has the identity recognision somehow changed in playbook run as in the beginning there's:
Identity added: tmp/awx_1_6x19brtz/artifacts/1/ssh_key_data (/tmp/awx_1_6x19brtz/artifacts/1/ssh_key_data? Or is this just a change in the wording.

This used to be Identity added:xxxxxx/credential_4 or something like that.

**Comment by extjperttula** [comment]
After running the git clone for two hours it eventually fails with 

fatal: [localhost,]: FAILED! => {"changed": false, "cmd": ["/usr/bin/git", "fetch", "origin"], "msg": "Failed to download remote objects and refs:  packet_write_wait: Connection to xx.xx.xx.xx port 22: Broken pipe\r\nfatal: The remote end hung up unexpectedly\nfatal: protocol error: bad pack header\n"}

**Comment by ryanpetrello** [comment]
@extjperttula sounds to me like git itself is hanging attempting to clone via ssh?  If that's the case, not a lot we can do about that.

**Comment by jperttul** [comment]
I would totally agree but we have AWX Ansible 3.0.1 running simultaneously
to exactly the same repository. Or can that be actually the issue
that this 3.0.1 is holding the gitlab?

Kind regards
Jarkko

pe 26.4.2019 klo 20.37 Ryan Petrello <notifications@github.com> kirjoitti:

**Comment by extjperttula** [comment]
This can be closed. In my case the issue was with the mtu values of eth0 vs. mtu values in awxcompose_default bridge network. Eth0 needed to be lower than the bridge mtu. Deleting the network once, building it again with docker-compose, changing eth0 mtu and things started to work. (well, in addition one or two reboots here and there).

**Comment by sergh-one** [comment]
Same issue, but in my conditions it stuck when some playbook is running on the same project. It hangs on status: pending, when i trying to run other playbook it is also status: pending.
It is normal behavior, when all plays and SCM update running one by one, not simultaneously ?

**Comment by ryanpetrello** [comment]
@sergh-one there are a number of situations where a job will hang out in `pending`.  The most obvious ones to check are:

1.  Are you out of capacity (`/api/v2/ping/`)?
2.  If you want to run a job template multiple times in parallel, have you enabled concurrent jobs on the Job Template in question?

![image](https://user-images.githubusercontent.com/214912/60833646-b07d3600-a18c-11e9-829f-5f97fce028de.png)
