### ISSUE TITLE
Vault KV config should validate URL

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#3763]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

The vault KV backend should validate the vault URL passed.

##### ENVIRONMENT
* AWX version: current

##### STEPS TO REPRODUCE

enter "host:1234" for a vault server

##### EXPECTED RESULTS

1) accepts it, uses it as http://host:1234/
- or -
2) throws an error on save

##### ACTUAL RESULTS

throws error on use

**Comment by ryanpetrello** [comment]
What's the error?  What happens when you push the test button?

**Comment by wenottingham** [comment]
![hashi](https://user-images.githubusercontent.com/5208768/56693930-95357b00-66b3-11e9-92fe-d871fb9e622b.png)

**Comment by ryanpetrello** [comment]
Resolved.
