### ISSUE TITLE
Launching a JT with a Credential that prompts throws status undefined error

### ISSUE THREAD

**Issue by konkolorado** [ansible/awx#3764]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When using a Job Template that either (a) prompts for a credential at run time or (b) uses a credential that prompts for user input at run time, the job fails to launch and displays the error "Failed to get credential types. GET status: undefined".

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: kubernetes , docker for mac
* Ansible version:  2.7.10 
* Operating System:
* Web Browser: Chrome

##### STEPS TO REPRODUCE

On a fresh install with `create_preload_data=True`,  open the Demo Job Template and select  Prompt On Launch on the Credential only. Save the JT and click Launch. This happens on any JT.

##### EXPECTED RESULTS

I expect to see the "working" popup on the bottom right and for the page to auto navigate to the Job Details page showing the process of the launched job.

##### ACTUAL RESULTS

No "working" pop up appears, no redirection happens.  An Error! pop up appears instead with the text "Failed to get credential types. GET status: undefined".  The job fails to launch and the launch button in the template becomes unresponsive (until a page refresh).

![image](https://user-images.githubusercontent.com/5422638/56753269-da0eef80-674f-11e9-9b8d-d908b93bafe1.png)
  
##### ADDITIONAL INFORMATION

- Selecting Prompt on Launch in the JT screen is the most obvious way of triggering this error, but the error also occurs if the selected credential in the JT has any fields Prompting on launch
- The logs on the awx_web container show status code 200 for all the requests the Launch button triggers
  - OPTIONS /api/v2/job_templates/5/launch/ HTTP/1.1 200
  - GET /api/v2/job_templates/5/launch/ HTTP/1.1 200
  - GET /api/v2/credential_types/?page_size=200 HTTP/1.1 200
  - OPTIONS /api/v2/credentials/ HTTP/1.1 200
  - GET /api/v2/credentials/?order_by=name&page_size=5&credential_type=1 HTTP/1.1 200
- The Chrome DevTools console isn't showing any blocked requests or failures (just a few violations)
- The issue can be worked around by also selecting Prompt on Launch on the Inventory field in the JT

**Comment by jakemcdermott** [comment]
resolved by https://github.com/ansible/awx/commit/14045c10179460ec9823c0a3762f2b2227ccb02f
