### ISSUE TITLE
Expand usage of action buttons in view/edit screen

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#3768]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

We now have `launch` button on the view/edit screen for Job Templates and Workflow Templates.

Ergo, we should have 'Sync' buttons on Inventory sources and Projects in the same way.

**Comment by AlexSCorey** [comment]
This is completed by https://github.com/ansible/awx/pull/6975 and https://github.com/ansible/awx/pull/9003
![Screen Shot 2021-04-28 at 4 55 01 PM](https://user-images.githubusercontent.com/39280967/116471324-89509680-a842-11eb-8616-47e8c414d40c.png)
![Screen Shot 2021-04-28 at 4 55 16 PM](https://user-images.githubusercontent.com/39280967/116471335-8b1a5a00-a842-11eb-8f38-921f032e7f44.png)
