### ISSUE TITLE
Not able to login via default username and password

### ISSUE THREAD

**Issue by atul9911** [ansible/awx#377]
I have setup awx using normal django migration but is throwing 401 in  ```/api/v2/me/```  when i am trying to login.
It is also successfully generated a token as you can see in the logs but still it showing ```received by user AnonymousUser attempting to access``` 
Please find  logs for you reference:-

```[pid: 10971|app: 0|req: 1/1] 127.0.0.1 () {46 vars in 816 bytes} [Mon Oct  9 16:09:27 2017] GET / => generated 11094 bytes in 188 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
2017-10-09 16:09:45,395 INFO     awx.api.generics Calling intialize 
[pid: 10971|app: 0|req: 2/2] 127.0.0.1 () {46 vars in 776 bytes} [Mon Oct  9 16:09:45 2017] GET /api/ => generated 154 bytes in 651 msecs (HTTP/1.1 200) 8 headers in 249 bytes (1 switches on core 0)
2017-10-09 16:09:46,169 INFO     awx.api.generics Calling intialize 
[pid: 10971|app: 0|req: 3/3] 127.0.0.1 () {48 vars in 798 bytes} [Mon Oct  9 16:09:46 2017] GET /api/ => generated 154 bytes in 111 msecs (HTTP/1.1 200) 8 headers in 249 bytes (2 switches on core 0)
2017-10-09 16:09:46,760 INFO     awx.api.generics Calling intialize 
2017-10-09 16:09:47,111 INFO     awx.api.generics Calling intialize 
[pid: 10968|app: 0|req: 1/4] 127.0.0.1 () {48 vars in 804 bytes} [Mon Oct  9 16:09:46 2017] GET /api/v2/ => generated 1512 bytes in 643 msecs (HTTP/1.1 200) 8 headers in 249 bytes (2 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 10971|app: 0|req: 4/5] 127.0.0.1 () {46 vars in 792 bytes} [Mon Oct  9 16:09:47 2017] GET /api/v2/auth/ => generated 2 bytes in 442 msecs (HTTP/1.1 200) 8 headers in 250 bytes (1 switches on core 0)
2017-10-09 16:09:48,196 INFO     awx.api.generics Calling intialize 
[pid: 10970|app: 0|req: 1/6] 127.0.0.1 () {46 vars in 792 bytes} [Mon Oct  9 16:09:47 2017] GET /api/v2/auth/ => generated 2 bytes in 541 msecs (HTTP/1.1 200) 8 headers in 250 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
2017-10-09 16:09:56,042 INFO     awx.api.generics Calling intialize 
2017-10-09 16:09:56,463 INFO     awx.api.views d14214f6b18dc042a5b95cdf368d0cc5a88a440c
2017-10-09 16:09:56,465 INFO     awx.api.views User admin logged in
[pid: 10971|app: 0|req: 5/7] 127.0.0.1 () {56 vars in 1001 bytes} [Mon Oct  9 16:09:56 2017] POST /api/v2/authtoken/ => generated 89 bytes in 482 msecs (HTTP/1.1 200) 13 headers in 446 bytes (1 switches on core 0)
2017-10-09 16:09:56,928 INFO     awx.api.generics Calling intialize 
2017-10-09 16:09:57,217 INFO     awx.api.generics status 401 received by user AnonymousUser attempting to access /api/v2/me/ from 127.0.0.1
[pid: 10971|app: 0|req: 6/8] 127.0.0.1 () {52 vars in 1069 bytes} [Mon Oct  9 16:09:56 2017] GET /api/v2/me/ => generated 58 bytes in 400 msecs (HTTP/1.1 401) 10 headers in 311 bytes (1 switches on core 0)
2017-10-09 16:09:57,618 INFO     awx.api.generics Calling intialize 
[pid: 10968|app: 0|req: 2/9] 127.0.0.1 () {52 vars in 1056 bytes} [Mon Oct  9 16:09:57 2017] DELETE /api/v2/authtoken/ => generated 0 bytes in 130 msecs (HTTP/1.1 204) 8 headers in 247 bytes (1 switches on core 0)
```

I have created one super user for me while migration but still i am not able to login

**Comment by matburt** [comment]
What do you mean by this statement `setup awx using normal django migration` ?

The installer will create a user after running the initial migration in the awx_task container, did it not do that? were there any errors?

**Comment by atul9911** [comment]
I basically cloned awx repository in my local and setup that as a normal django project instead of running its setup playbook and complete the setup using docket and open shift.Second step i have run django migration using normal python migration command which created necessary tables in my postgres database and after that i have created a super user account using django create super user command. Apart from that my auth api is creating an access token but still my  ```/api/v2/me/ ``` throwing me 401 which i have already shared in logs.
Kindly let me know if i am doing anything wrong because in installer itself you are doing the same steps which i have done manually. And if you ask me why i want to do it manually because i want it to use using mysql instead of postgres which i couldn't do until i'll setup it using normally using postgres.

**Comment by matburt** [comment]
I'm very sorry, but we only support the installation mechanism outlined in the documentation. If you want to deploy AWX (and especially if you want to swap the database out) then you are on  your own.

**Comment by atul9911** [comment]
That's ok if you could not help me in installing and migration but what i am expecting is why my ```/v2/api/me``` is throwing 401 despite my auth API has generated the access token.How this API is validating a user?which table it is looking for?

**Comment by dwimsey** [comment]
This issue happens with the supported installation method as well.  Happens when deployed to openshift with the latest master on OpenShift 3.6.

Fresh install, only changes to inventory file are the openshift cluster information.

Note access the URL directly prompts for basic auth, entering the admin/password on the default install works and allows access, but login through the standard UI still fails due to a 401

**Comment by JAntF9905** [comment]
@dwimsey I am running into the same issue on when deploying to Origin 3.6, can you explain the the alternate login method you used?

**Comment by hydroxy** [comment]
For me the issue was only 3 out of the 4 required docker containers were running due to an incorrect install of docker-compose. I reinstalled docker-compose correctly, repeated the install from scratch and I was able to log in no bother.
