### ISSUE TITLE
'float' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by flynn1973** [ansible/awx#3772]
this error appeared out of no reason, no update ,no fiddling around, no nothing. seems it only bails out at fact gathering.

Identity added: /tmp/awx_1139_iC6hIp/credential_3 (/tmp/awx_1139_iC6hIp/credential_3)
1
Identity added: /tmp/awx_1139_iC6hIp/credential_3 (/tmp/awx_1139_iC6hIp/credential_3)
1
Identity added: /tmp/awx_1139_iC6hIp/credential_3 (/tmp/awx_1139_iC6hIp/credential_3)
2
3
PLAY [prepare ansible controller] **********************************************
14:49:32
4
5
TASK [Gathering Facts] *********************************************************
14:49:33
6
fatal: [AIXBIDBT01]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to remote host \"AIXBIDBT01\". Make sure this host can be reached over ssh", "unreachable": true}
7
ERROR! Unexpected Exception, this is probably a bug: 'float' object has no attribute 'iteritems'
8
to see the full traceback, use -vvv

**Comment by ryanpetrello** [comment]
@flynn1973,

Please reopen this issue with all of the details requested at https://github.com/ansible/awx/issues/new?template=bug_report.md so that we can attempt to reproduce and help troubleshoot.
