### ISSUE TITLE
sos plugin tower.py improvements

### ISSUE THREAD

**Issue by pmoravec** [ansible/awx#3775]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Few improvements of https://github.com/ansible/awx/blob/devel/tools/sosreport/tower.py from a contributor of `sosreport` tool.

##### ENVIRONMENT
upstream code review

##### STEPS TO REPRODUCE
n.a., not much wrong in particular, rather code improvements suggestions.

##### EXPECTED RESULTS
- https://github.com/ansible/awx/blob/devel/tools/sosreport/tower.py#L8:
   - `ansible --version` is already collected by `ansible` plugin (https://github.com/sosreport/sos/blob/master/sos/plugins/ansible.py#L29) - this call is redundant (until you call `sosreport -o tower` or `sosreport -n ansible`)
- https://github.com/ansible/awx/blob/devel/tools/sosreport/tower.py#L26:
   - `/etc/ansible` is already collected by `ansible` plugin (https://github.com/sosreport/sos/blob/master/sos/plugins/ansible.py#L25) - this collection is redundant and in very rare cases, it can be dangerous (see https://github.com/sosreport/sos/issues/1596)
- https://github.com/ansible/awx/blob/devel/tools/sosreport/tower.py#L32-L34:
  - these three log patterns are already collected by `logs` plugin - again, redundant and potentially dangerous duplicate collection
- https://github.com/ansible/awx/blob/devel/tools/sosreport/tower.py#L50:
  - is this still applicable? Are there systems with sosreport version *older* than 3.0 (that was released 5years ago)?
- https://github.com/ansible/awx/blob/devel/tools/sosreport/tower.py#L53 and https://github.com/ansible/awx/blob/devel/tools/sosreport/tower.py#L71 : 
  - we stick to name plugins starting with capital letter ;-)
- https://github.com/ansible/awx/blob/devel/tools/sosreport/tower.py#L59-L60:
  - this can be shortened to `self.add_copy_spec(SOSREPORT_TOWER_DIRS)` as the method supports also lists as its argument. But you might want to stick on the current code in case more than 25MB data are expected to be collected altogether; *one* call of `add_copy_spec` collects files from newest to oldest and stops collecting after reaching 25MB limit (by default; it is configurable via `--log-size=..` or `--all-logs` options). So if e.g. each of three logdirs would have 10MB, one copyspec would skip some oldest file(s), while copyspec called for each logdir individually will collect everything.
- https://github.com/ansible/awx/blob/devel/tools/sosreport/tower.py#L62-L63:
  - like above, worth calling single `self.add_forbidden_path(SOSREPORT_FORBIDDEN_PATHS)` ; no catches here
- https://github.com/ansible/awx/blob/devel/tools/sosreport/tower.py#L65-L66:
  - like above, worth calling single `self.add_cmd_output(SOSREPORT_TOWER_COMMANDS)` ; no catches here

##### ADDITIONAL INFORMATION

**Comment by ryanpetrello** [comment]
@pmoravec 

pull requests welcome 😉

**Comment by Spredzy** [comment]
@ryanpetrello can this be closed as the PR has been merged ?
