### ISSUE TITLE
Update email notification TLS/SSL options to be check boxes instead of radio buttons

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#3777]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The TLS/SSL options are enable/disble buttons in the email notification option. At a glance, it looks like this needs to be one or the other because of the radio button view. Since these can be disabled, these should be updated to appear as check boxes.

**Comment by zicklam** [comment]
Hi @msilmser 
but with checkboxes you will be able to select both. 
Another solution would be to add an "None" radio selection to visualize the correct behavior.

**Comment by jainnikhil30** [comment]
fixed with https://github.com/ansible/awx/pull/6389 ?

**Comment by unlikelyzero** [comment]
we need to make sure this user experience is improved in the new ui
