### ISSUE TITLE
Job stuck in running state, "cancel" not effective

### ISSUE THREAD

**Issue by techraf** [ansible/awx#378]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Job permanently in "Running" state. Other jobs from the same template get queued.

Cancel button not effective. In the meantime I rebooted AWX machine, the job is still in the running state, the started time is the original one (i.e. it does not start again on reboot).

Jobs created from other templates work (start, finish) properly.

##### ENVIRONMENT
* AWX version: 1.0.0.588
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.4.0.0
* Operating System: CentOS 7
* Web Browser: Chrome 61 / macOS

##### STEPS TO REPRODUCE
Not sure yet... This is more of a question how this can be resolved in its current state.

##### ADDITIONAL INFORMATION
Playbook stopped running on gathering facts:

```
SSH password: 

PLAY [all] *********************************************************************19:02:44

TASK [Gathering Facts] *********************************************************19:02:44
```

**Comment by matburt** [comment]
You said you rebooted the awx machine. I reckon you could just restart the awx task container rather than rebooting the whole machine. Can we see some logs from the task container itself?

**Comment by matburt** [comment]
Since you haven't provided any more information I'm going to close this issue. Let us know if you were able to get more information about it.

**Comment by nvidiajunkie** [comment]
having same issue w/ Tower 3.3.1, Ansible v 2.7.1.  Under the "Jobs" section, stuck at "Running" for a status, and "Finished" = "Not finished".  I try to cancel in the UI and no joy.  any help would be great! thanks!

**Comment by kitsushadow** [comment]
Also having the same issue day after day. Tower 3.8.3

**Comment by kitsushadow** [comment]
This really should be reopened.
