### ISSUE TITLE
Suboptimal use of column widths on the Activity Stream

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#3786]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The Activity Stream table displays events by timestamp and user. At the moment, it has issues with displaying events with items which exceed 12 characters.

##### ENVIRONMENT
* AWX version: 4.0.0
* Operating System: macOS
* Web Browser: Firefox 60ESR

##### STEPS TO REPRODUCE

1. Generate an activity on the activity Stream page with a resource/item/user with a string longer than 12 characters. 
1. Note the format on the Event Column.

##### EXPECTED RESULTS

Better use of spacing within the row.

##### ACTUAL RESULTS

Strange wrapping.

##### ADDITIONAL INFORMATION
<img width="1321" alt="Screen Shot 2019-04-30 at 10 47 27 AM" src="https://user-images.githubusercontent.com/12446869/56975200-49b12000-6b3e-11e9-8b2c-5ed90a147d00.png">

**Comment by anshulbehl** [comment]
Will need adding extra property to tableCell.description-column class, setting the display property to table fixes this issue, not sure where it can cause regressions.

**Comment by jlmitch5** [comment]
I belive this is fixed in the new ui activity stream pr:
![Screen Shot 2021-01-14 at 12 45 02 PM](https://user-images.githubusercontent.com/1342624/104628557-5ead4a00-5666-11eb-8d89-8fc10cf0b921.png)

**Comment by unlikelyzero** [comment]
covered in activity-stream.spec.js
