### ISSUE TITLE
Expand and Collapse buttons are inert on Job Result Detail Page

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#3794]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Expand and Collapse buttons are inert on Job Result Detail Page

##### ENVIRONMENT
* AWX version: 4.0.0

##### STEPS TO REPRODUCE
1. Run a job to completion
2. On the Job Result Detail page, use the collapse expand buttons

##### EXPECTED RESULTS

Expand or collapse

##### ACTUAL RESULTS

inert action

**Comment by ryanpetrello** [comment]
Resolved via https://github.com/ansible/awx/commit/04d22a930d662e4269b5b8337645232bb4de4d3e and https://github.com/ansible/awx/commit/46795cc71ef63135ec097f72e8c82448bedcca8d
