### ISSUE TITLE
Add username environment variable when running job templates

### ISSUE THREAD

**Issue by Rylon** [ansible/awx#3795]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
When executing a job template, it would be useful to have the username of the user who triggered the job template, added to the other environment variables set when a playbook is run.

The reason for this, is that we use Ansible to launch and configure VMs on different environments, and it's useful to be able to set some metadata based on which user triggered it.

I see some environment variables already get defined, such as `JOB_ID`, would it be possible to add some others, like the `JOB_STARTED_BY` username?

This is similar to the request https://github.com/ansible/awx/issues/1547 but for slightly different reasons.

**Comment by ryanpetrello** [comment]
Hey @Rylon,

We _do_ already expose this data as an extra var (`awx_user_name`).  Is there a reason that wouldn't work?

https://github.com/ansible/awx/blob/devel/awx/main/models/unified_jobs.py#L1407-L1413

**Comment by wenottingham** [comment]
Closing this since there is a feature that provides this (as extra var, not env var); you can set env vars from this if needed.

**Comment by Rylon** [comment]
Ahh, no that should work, let me verify and get back to you :) Thanks!

**Comment by Rylon** [comment]
Hi @ryanpetrello confirmed that's all working as expected, thanks again! 👍

**Comment by ssaammoo** [comment]
Hi @wenottingham 
Is it always provided as extra var through the whole workflow ?
I assume I should be simply to use the var awx_user_name in any playbook within the workflow as it is extra var, but sometime I get undefined error variable. 

Should I open a new bug for this ?

**Comment by wenottingham** [comment]
Yes, a new bug please.
