### ISSUE TITLE
Job Event children not being populated

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#3798]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
There is supposed to be an accounting of job event children at `/api/v2/job_events/N/children/`, but this list is always coming up 0, even for an event `N` that clearly has its `uuid` field referenced by `parent_uuid` field on other events.

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Run the playbook:

https://github.com/ansible/test-playbooks/blob/master/debug.yml

and set `ansible_connection: local`

Do this on an inventory with 500 hosts (roughly).

##### EXPECTED RESULTS

The event:

> Task Started (debug)

is a parent of many other events. Proof:

My playbook_on_task_started event is at `/api/v2/job_events/17606/`, and it has `"uuid": "0242ac12-0005-e7f4-73ba-0000000001ee",`

Thus, I expect:

 - `/api/v2/job_events/17606/children/`
 - `/api/v2/job_events/?parent_uuid=0242ac12-0005-e7f4-73ba-0000000001ee`

To both have the same listings of job events.

##### ACTUAL RESULTS

`/api/v2/job_events/?parent_uuid=0242ac12-0005-e7f4-73ba-0000000001ee` has 975 events

but

`/api/v2/job_events/17606/children/` has 0

##### ADDITIONAL INFORMATION

The children sublist should also be linked from the job event, but it is not.

Ping @jakemcdermott and @ryanpetrello

**Comment by kdelee** [comment]
This is working for me! Thanks
