### ISSUE TITLE
Specifying Inventory File Path when sourcing from project need placeholder text on file selection box

### ISSUE THREAD

**Issue by gdykeman** [ansible/awx#380]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME
 - UI

##### SUMMARY
Difficult to figure out that there is an option to specify the path to the inventory file when sourcing from project.  Currently, you click the `inventory file` dropdown, then type into the blank text box that appears.  Did not realize this and couldn't utilize yml format inventories until speaking with a Tower engineer.

**Comment by shanemcd** [comment]
This is addressed via tooltip in new UI.
