### ISSUE TITLE
failed : synchronize module in awx 

### ISSUE THREAD

**Issue by Mohamed095** [ansible/awx#3806]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker compose
* Ansible version:  2.7
* Operating System:  centos 7
* Web Browser: firefox

##### STEPS TO REPRODUCE
Hello,

when i run my playbook with awx, the synchronize task take a lot of time without any result, i think that awx has problem with this module, how can i overcame this problem ? please.

**Comment by matburt** [comment]
If you are having trouble with an Ansible module you should check with the Ansible project.

**Comment by Mohamed095** [comment]
I think the problem is related to awx project because when i try to replace the "synchronize" module by "copy" module it's worked, in addition to that when i launched the playbook ( with "synchronize" module ) without awx then it's worked successfully, thanks.

**Comment by rchaud** [comment]
@Mohamed095  Did you get this to work? I tried the synchronize module from a role in AWX and I never got it to work. I was getting a SSH connection issues while it worked perfectly locally. I switched to copy module, which is not ideal but that worked.
