### ISSUE TITLE
AWX swarm services

### ISSUE THREAD

**Issue by lucaslan** [ansible/awx#381]
#### ISSUE TYPE

 - Feature Idea ?

##### COMPONENT NAME

 - None of all
##### SUMMARY

Deploy Ansible AWX on a swarm cluster doesn't work

##### ENVIRONMENT

* AWX version: All
* AWX install method: Docker
* Ansible version:  2.4.0
* Operating System: RHEL 7
* Web Browser: IE/Firefox/Chrome

##### STEPS TO REPRODUCE

Install a swarm cluster with a minimum of 3 nodes, install AWX using awx scripts sending containers to a registry.

you can deploy the images using this docker-compose file:

`version: '3'
services:
  postgres:
    image: "postgres:9.6"
    networks:
      - safadao
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
    volumes:
      - "/tmp/nfs/pgdata:/var/lib/postgresql/data:Z"

  rabbitmq:
    image: "rabbitmq:3"
    networks:
      - safadao
    environment:
      RABBITMQ_DEFAULT_VHOST: awx

  memcached:
    image: "memcached:alpine"
    networks:
      - safadao

  awx_web:
    image: "ansible/awx_web:latest"
    networks:
      - safadao
    ports:
      - "88:8052"
    hostname: awxweb
    user: root
    environment:
      SECRET_KEY: aabbcc
      DATABASE_USER: awx
      DATABASE_PASSWORD: awxpass
      DATABASE_NAME: awx
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: awx
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211

  awx_task:
    image: "ansible/awx_task:latest"
    networks:
      - safadao
    hostname: awx
    user: root
    environment:
      SECRET_KEY: aabbcc
      DATABASE_USER: awx
      DATABASE_PASSWORD: awxpass
      DATABASE_NAME: awx
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: awx
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
networks:
  safadao:
    driver: overlay
`

note that I'm using a network insted a container linking.

##### EXPECTED RESULTS

Use ansible AWX with swarm services. (for HA purpose)

##### ACTUAL RESULTS

I tried a few times and a get some errors like 500 internal error

**Comment by matburt** [comment]
Yep swarm is not currently a supported installation target.

**Comment by kiranos** [comment]
Hi

I have a stack compose file working for swarm, its located here:

https://github.com/kiranos/playground/tree/master/awx/swarm

Try it and see if it works for you. its 1 replica per service for the time beeing, awx is working on supporting multiple instances per service. But this is using network aswell instead of links.

**Comment by kiranos** [comment]
@matburt I think we can close this? above works for me, I would love for your recent work with multiple instances of awx to coexist to have swarm support but it feels like another issue than this?

**Comment by matburt** [comment]
Sounds good!
