### ISSUE TITLE
Many popovers do not appear including the Recent Notification list

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#3811]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Recent Notification list does not appear. No network errors. No console log

##### ENVIRONMENT
* AWX version: 4.0.0

##### STEPS TO REPRODUCE
1. Trigger a notification which passes or fails
2. Click on the bulb next to the notification.
Note: no list of notification history

##### EXPECTED RESULTS
1. Notification history

##### ACTUAL RESULTS
1. No notification history

##### ADDITIONAL INFORMATION
<img width="1383" alt="Screen Shot 2019-05-02 at 2 22 18 PM" src="https://user-images.githubusercontent.com/12446869/57099321-2b882300-6cea-11e9-9dff-605d2daf0890.png">

**Comment by rooftopcellist** [comment]
I can reproduce.  I am thinking that this line may be needed: https://github.com/ansible/awx/commit/9c20e1b4946f05cbb63a616f297dc7da62071385#diff-575afb44c6f45c35abbf843ceaa5c189L28  @mabashian could you give me some more context about this change?

It looks like this is the function that sets the notification status popup in question: https://github.com/ansible/awx/blob/devel/awx/ui/client/src/notifications/notification-templates-list/list.controller.js#L65

**Comment by marshmalien** [comment]
Bootstrap tooltips and popovers use a built-in sanitizer that does not accept the HTML elements we are providing it by default (e.g., `<table>`, `<td>`).

Options to fix this issue:
1) Add HTML elements to the sanitizer whiteList
```
  $(element).popover.Constructor.Default.whiteList.table = [];
```
2) Build popover content using default [whiteList](https://getbootstrap.com/docs/4.3/getting-started/javascript/#sanitizer)
 3) Use a bootstrap popover alternative (custom popover component)

https://getbootstrap.com/docs/4.3/getting-started/javascript/#sanitizer
https://github.com/twbs/bootstrap/releases/tag/v4.3.1

**Comment by unlikelyzero** [comment]
@marshmalien does this affect that bulb indicator across the entire app?

**Comment by marshmalien** [comment]
@unlikelyzero This impacts the popover/tooltip on the bulb indicator IF it contains HTML elements that are not included in the bootstrap sanitizer whitelist. The project and job list status indicators work as expected because they display text within a `<div>`. Any bootstrap tooltip/popover that displays a `<table>` could have been affected when we [updated bootstrap](https://github.com/ansible/awx/pull/2983).

**Comment by dsesami** [comment]
Both successful and failed notifs, as well as the absence of recent notifications appear correctly in popovers now.
