### ISSUE TITLE
Inventory Hosts Groups view has a busted table layout

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#3813]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Inventory Hosts Groups view has a busted table layout.

##### ENVIRONMENT
* AWX version: X.Y.Z

##### STEPS TO REPRODUCE
1. Navigate to the Inventory Page -> Select a host -> click on Groups
2. If not a part of group, add a group.
Note: that the table format is busted but the items / links / actions are still functional

##### EXPECTED RESULTS
1. proper layout

##### ACTUAL RESULTS
1. Improper layout

##### ADDITIONAL INFORMATION
No network traffic errors. No console log errors.
<img width="1372" alt="Screen Shot 2019-05-02 at 3 03 38 PM" src="https://user-images.githubusercontent.com/12446869/57100604-63dd3080-6ced-11e9-8609-7f40a8df9d5b.png">

**Comment by AlexSCorey** [comment]
Fixed downstream
