### ISSUE TITLE
Clicking through the Failed Hosts on the Dashboard generates a strange query

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#3814]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Note: Not a regression. Has been like this for quite some time.

Clicking through the Failed Hosts on the Dashboard generates a strange query.

- Pagesize is 25, not 20.
- UI Renders Pagination toggle for 20 instead of 25.
- Filter `has_active_failures:true` cannot be removed
- Filter should be `has_active_failures__icontains`

##### ENVIRONMENT
AWX 2.0.0

##### STEPS TO REPRODUCE
1. Generate 26+ Failed Hosts
1. On Dashboard, select the Failed Hosts badge.

Note: 

- Pagesize is 25, not 20.
- UI Renders Pagination toggle for 20 instead of 25.
- Filter `has_active_failures:true` cannot be removed
- Filter should be `has_active_failures__icontains`

##### EXPECTED RESULTS
- Correct filter used.
- Correct pagesize used

##### ACTUAL RESULTS
- Strange behavior with pagination
- Unable to remove filter

##### ADDITIONAL INFORMATION
![failedhostsbadge](https://user-images.githubusercontent.com/12446869/57101403-24afdf00-6cef-11e9-9e25-4de2703fd8d9.gif)

**Comment by gamuniz** [comment]
Given the age of the issue and the fact that we have rewritten the UI twice since this was filed, closing
