### ISSUE TITLE
Extend Docker - Python Module - Then errors on Module PIP install in Playbook task

### ISSUE THREAD

**Issue by kenmaglio** [ansible/awx#3816]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
We have extended the base task image, to allow us to include 
1. Custom Env's and Additional 'standard' pip modules.

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: kubernetes
* Ansible version:  2.7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Extend the docker image using the [documentation]
(https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md)

We have something similar in our Dockerfile
We simply install those into the existing ansible venv

```
COPY requirements.txt /tmp/requirements.txt
RUN source /var/lib/awx/venv/ansible/bin/activate && \
     pip install -r /tmp/requirements.txt
```

Build AWX using that image into K8s

Test playbook that has a Task using pip module to install a module not in AWX image, or our requirements.txt file.

it's really as simple as

```yaml
- hosts: localhost
  tasks:
    - name: Pip Install
      pip:
        name:
          - pywinrm
          - pymongo
```

##### EXPECTED RESULTS

it installs correctly

##### ACTUAL RESULTS

OSError: [Errno 30] Read-only file system: '/var/lib/awx/venv/ansible/lib64/python2.7/site-packages/pymongo

##### ADDITIONAL INFORMATION

We found:
site-packages is read only for anyone but root:

```
sh-4.2# ls -al /var/lib/awx/venv/ansible/lib64/python2.7/site-packages 
total 2064
drwxr-xr-x.  1 root root   4096 Apr 22 17:45 .
```

"msg": "stdout: Requirement already satisfied: pywinrm in /var/lib/awx/venv/ansible/lib/python2.7/site-packages\nCollecting pymongo\n  Downloading https://files.pythonhosted.org/packages/6e/ea/353a9f8ced71b9e258438aa4d6aa048c1eaf5b774d3ef2273d686fde0947/pymongo-3.8.0-cp27-cp27mu-manylinux1_x86_64.whl (410kB)\nRequirement already satisfied: xmltodict in /var/lib/awx/venv/ansible/lib/python2.7/site-packages (from pywinrm)\nRequirement already satisfied: requests>=2.9.1 in /var/lib/awx/venv/ansible/lib/python2.7/site-packages (from pywinrm)\nRequirement already satisfied: requests-ntlm>=0.3.0 in /var/lib/awx/venv/ansible/lib/python2.7/site-packages (from pywinrm)\nRequirement already satisfied: six in /var/lib/awx/venv/ansible/lib/python2.7/site-packages (from pywinrm)\nRequirement already satisfied: idna<2.8,>=2.5 in /var/lib/awx/venv/ansible/lib/python2.7/site-packages (from requests>=2.9.1->pywinrm)\nRequirement already satisfied: chardet<3.1.0,>=3.0.2 in /var/lib/awx/venv/ansible/lib/python2.7/site-packages (from requests>=2.9.1->pywinrm)\nRequirement already satisfied: urllib3<1.25,>=1.21.1 in /var/lib/awx/venv/ansible/lib/python2.7/site-packages (from requests>=2.9.1->pywinrm)\nRequirement already satisfied: certifi>=2017.4.17 in /var/lib/awx/venv/ansible/lib/python2.7/site-packages (from requests>=2.9.1->pywinrm)\nRequirement already satisfied: ntlm-auth>=1.0.2 in /var/lib/awx/venv/ansible/lib/python2.7/site-packages (from requests-ntlm>=0.3.0->pywinrm)\nRequirement already satisfied: cryptography>=1.3 in /var/lib/awx/venv/ansible/lib/python2.7/site-packages (from requests-ntlm>=0.3.0->pywinrm)\nRequirement already satisfied: cffi>=1.7; platform_python_implementation != \"PyPy\" in /var/lib/awx/venv/ansible/lib/python2.7/site-packages (from cryptography>=1.3->requests-ntlm>=0.3.0->pywinrm)\nRequirement already satisfied: enum34; python_version < \"3\" in /var/lib/awx/venv/ansible/lib/python2.7/site-packages (from cryptography>=1.3->requests-ntlm>=0.3.0->pywinrm)\nRequirement already satisfied: asn1crypto>=0.21.0 in /var/lib/awx/venv/ansible/lib/python2.7/site-packages (from cryptography>=1.3->requests-ntlm>=0.3.0->pywinrm)\nRequirement already satisfied: ipaddress; python_version < \"3\" in /var/lib/awx/venv/ansible/lib/python2.7/site-packages (from cryptography>=1.3->requests-ntlm>=0.3.0->pywinrm)\nRequirement already satisfied: pycparser in /var/lib/awx/venv/ansible/lib/python2.7/site-packages (from cffi>=1.7; platform_python_implementation != \"PyPy\"->cryptography>=1.3->requests-ntlm>=0.3.0->pywinrm)\nInstalling collected packages: pymongo\n\n:stderr: Exception:\nTraceback (most recent call last):\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pip/basecommand.py\", line 215, in main\n    status = self.run(options, args)\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pip/commands/install.py\", line 342, in run\n    prefix=options.prefix_path,\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pip/req/req_set.py\", line 784, in install\n    **kwargs\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pip/req/req_install.py\", line 851, in install\n    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pip/req/req_install.py\", line 1064, in move_wheel_files\n    isolated=self.isolated,\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pip/wheel.py\", line 345, in move_wheel_files\n    clobber(source, lib_dir, True)\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pip/wheel.py\", line 316, in clobber\n    ensure_dir(destdir)\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pip/utils/__init__.py\", line 83, in ensure_dir\n    os.makedirs(path)\n  File \"/var/lib/awx/venv/ansible/lib64/python2.7/os.py\", line 157, in makedirs\n    mkdir(name, mode)\nOSError: [Errno 30] Read-only file system: '/var/lib/awx/venv/ansible/lib64/python2.7/site-packages/pymongo'\n"

**Comment by ryanpetrello** [comment]
@kenmaglio,

Check out these steps for setting up custom virtualenvs in k8s environments:

https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md#kubernetes-custom-virtualenvs

Alternatively, check out this new feature in 4.0.0 that allows you to pull custom virtualenvs from _other_ (configurable) file system locations:

https://github.com/ansible/awx/issues/3126
https://github.com/ansible/awx/commit/ec390b049dd9ff38885f23c53f5d475ea2c4ac82#diff-015b935452ac22e8799e290bcfa7cb07

**Comment by kenmaglio** [comment]
@ryanpetrello So you're saying the way we did it - won't work when we deploy with K8s, and we need to refactor now ( we with this new version we moved it all into K8s) to use the K8s method in that doc?

**Comment by ryanpetrello** [comment]
You're installing awx with k8s already, right (your issue suggestion suggests so)?

> AWX install method: kubernetes

You could _maybe_ make your way work, but the way suggested in our documentation is the recommended approach.

**Comment by kenmaglio** [comment]
@ryanpetrello I guess the thing we've noticed from using the OOTB AWX image on the prior version - we had no issues installing pip's from playbook tasks. 

Our new method, while we looked at the k8s method, we chose to extend the docker image for speed and dependencies. 
* the installs take about 5min to install, so we'd have to wait that long for a pod to "rebuild"
* dependencies

Using the docker extension, we only need the docker repo to be accessible ( our Artifactory ) for a pod to come back up. 

Using K8s init containers, you'd need:
* Docker registry
* internet
* pypy availabilty

We took our approach as it was documented there on that document, and just applied it to the image K8s was going to use.

However, we didn't expect to run into the ```site-packages``` directory to be only accessible by root. Ansible is apparently coming back into the container when it's running tasks not as root, therefore it cannot install new modules. 

This appears to be a change in the container, in the newer 4.0.0 version.. that the directory is locked down.

```
/var/lib/awx/venv/ansible/lib64/python2.7/site-packages
```

**Comment by kenmaglio** [comment]
@ryanpetrello My worry here and why I submitted this  is this new feature... 

https://github.com/ansible/awx/releases/tag/4.0.0
---------------
commit ec390b049dd9ff38885f23c53f5d475ea2c4ac82
Author: Vismay Golwala <vgolwala@redhat.com>
Date:   Tue Feb 26 22:09:28 2019 -0500

    Feature: custom virtual environment directories

    Currently, users are allowed to define virtual environments in
    `settings.BASE_VENV_PATH` only, because that's the only place
    Tower looks for virtual environments. This feature allows users
    to custom define the directory paths, using API or UI, to look
    for virtual environments. Tower aggregates virtual environments
    from all these paths, except environments with special name `awx`.

    Signed-off-by: Vismay Golwala <vgolwala@redhat.com>
------



Appears to have changed the way the task container works and permissions into venv's

**Comment by ryanpetrello** [comment]
@kenmaglio the ownership of awx's directory for virtualenvs _definitely_ changed recently.

The way suggested in our documentation is the recommended approach (as of 4.0.0).

**Comment by kenmaglio** [comment]
@ryanpetrello -- So those changes have now BROKEN the ability to install pip modules as a task in a playbook.

So we were utilizing AWX  1.0.6.35  and the Task Pip worked.
Now with 4.0.0   Task Pip  no longer works.

**Comment by ryanpetrello** [comment]
@kenmaglio,

You upgraded from 1.0.6.35 to 4.0.0, which is a difference of three major versions.

Software changes.

We have a documented approach to accomplishing what you want, and I've helped explain it to you.

1.  Create a custom location to place your custom virtualenvs.
2.  Create a custom virtualenv there, and make sure it's writable as the appropriate user.
3.  Update `settings.CUSTOM_VENV_PATHS`
4.  Run your playbook which does a `pip install` in the appropriate virtualenv.

**Comment by kenmaglio** [comment]
@ryanpetrello 

Really trying not to be difficult and appreciate your help on this... but 

1. So we have a custom location  ansible2.7  by name
2. Since root appears to now own everything and is the user you log into now in 4.0.1
   Appears it used to be ( in 1.0.6.x at least)   uid 1000  which was assigned root - but now we appear to come in as  uid 0  we can see this on the prompt as well when we ssh.
3. We can select for a template the new ansible2.7 environment.
4. We run our playbook - still get the error... but now...

OSError: [Errno 30] Read-only file system: '/var/lib/awx/venv/ansible2.7/lib64/python2.7/site-packages/pymongo

**Comment by shanemcd** [comment]
@kenmaglio have you tried building your own image? the process for that is pretty easy. when you're running the installer, uncomment the `dockerhub_base` variable in the inventory file and follow the errors until you have an image built, and push that up to somewhere you can pull it from. Then specify the image with `-e kubernetes_task_image=your_awx_task -e kubernetes_web_image=your_awx_web`. We're going to make the process of using custom virtualenvs in Kubernetes feel more native in future releases, but right now unless you can figure out how to deal with the filesystem permissions in your containers, you'll probably be stuck building your own images.

**Comment by kenmaglio** [comment]
@shanemcd  We have not built our own image from scratch and that's not really something we want to entertain. We don't want to fall away from the provided image and changes / enhancements to that image.  However, we simply wanted to add a few extra pip installs as they take a while.

What I'm suggesting we try is to use the OOTB 4.0.0 awx_task image and see what happens.
However, this is as simple as our Dockerfile is .. 

We've tried both the 'ansible' and 'ansible2.7' environments when running templates - no change.

```
ARG AWX_VERSION
ARG AWX_CONTAINER_SOURCE

FROM ${AWX_CONTAINER_SOURCE}:${AWX_VERSION}

MAINTAINER Reliability Engineering <ReliabilityEngineering@wwt.com>

USER root

## GCC Required for the LDAP Modules
RUN yum install -y python2-devel gcc

## Add PIP required Modules in base venv
COPY requirements.txt /tmp/requirements.txt
RUN source /var/lib/awx/venv/ansible/bin/activate && \
     pip install -r /tmp/requirements.txt

## Add additional venv here

### Ansible 2.3 Environment
RUN mkdir -p /var/lib/awx/venv/ansible2.3
RUN virtualenv --python=python2 --system-site-packages /var/lib/awx/venv/ansible2.3
RUN cp -a /var/lib/awx/venv/ansible/lib64/python2.7/site-packages/* /var/lib/awx/venv/ansible2.3/lib64/python2.7/site-packages/
RUN . /var/lib/awx/venv/ansible2.3/bin/activate && \
    pip install python-memcached psutil && \
    pip install ansible==2.3.3.0 && \
    pip install -r /tmp/requirements.txt

### Ansible 2.7 Environment
RUN mkdir -p /var/lib/awx/venv/ansible2.7
RUN virtualenv --python=python2 --system-site-packages /var/lib/awx/venv/ansible2.7
RUN cp -a /var/lib/awx/venv/ansible/lib64/python2.7/site-packages/* /var/lib/awx/venv/ansible2.7/lib64/python2.7/site-packages/
RUN . /var/lib/awx/venv/ansible2.7/bin/activate && \
    pip install python-memcached psutil && \
    pip install ansible==2.7.10 && \
    pip install -r /tmp/requirements.txt
```

**Comment by shanemcd** [comment]
@kenmaglio What you have here looks pretty great to me. I think I might have missed some context. I inferred earlier that you were having permission errors when writing into the containers file system while it was running inside of Kubernetes. Are you seeing permission errors when trying to build the Dockerfile you've provided above?

**Comment by kenmaglio** [comment]
@shanemcd  So no not having any issues there. 

And here's what's even weirder, OS packages are installing just fine.. it's apparently only pip modules. 

Something about that directory... once it's running in K8s is locked down. We are not mounting any persistent storage to that ( no symlinks ) .  

From all our K8s configs, nothing is touching that directory. 
We're kind of stumped to be honest... and not really sure how to diagnose.

Also if we take our image, run it in docker, and activate the ansible or ansible2.7 env and pip install - it works just fine.  It's something once it's running in K8s that's the issue.  ¯\_(ツ)_/¯

**Comment by shanemcd** [comment]
I think I am starting to understand the problem now. Do you need to switch back to `USER 1000` at the end of your Dockerfile? Also compare the file permissions of the files you created with the files that were already in the container, then `chown -R` and `chmod -R`. Maybe re-run this: https://github.com/ansible/awx/blob/devel/installer/roles/image_build/templates/Dockerfile.j2#L30

**Comment by kenmaglio** [comment]
@shanemcd  Thanks for your suggestions we'll try that out!

**Comment by coreywan** [comment]
Just for anyone else that may run into the `Read-only` error. It seems to be more of the feature of bubblewrap that is causing that error message. I just want to put this out here incase anyone runs into the same error and this shows up on their google search. 😄

**Comment by ryanpetrello** [comment]
@coreywan that's a good point - @kenmaglio does the pip install work as you expect if you (temporarily) turn off bwrap?

```
PATCH /api/v2/settings/jobs/
{"AWX_PROOT_ENABLED": false}
```

**Comment by kenmaglio** [comment]
@ryanpetrello @coreywan So Corey (works with us) did test this and came up with:

From Corey:

---

With bubblewrap still enabled, I reproduced the same error message with the read-only filesystem error.

I then turned off bubblewrap turned off we got the error message I suggested we would get earlier, access denied because the OOTB container is running as 1000 while the venv’s were built using root with a 0022 umask:

---

I believe if we returned the container to run as User 1000 ( or changed permissions ) - we would probably have success with bubblewrap off.

However, we didn't want to continue with that off - as that's the communities direction on the containers. 

Not sure the direction, if more and more is going to get locked down on the Container w/ bubblewrap - but OS-level package installs still work into the container.

**Comment by konkolorado** [comment]
I'm wondering if it would be easier (or even work) if you installed the pip requirements into the awx user's space (User 1000) with the --user flag (or extra_args: --user).  This assumes the user you are during the install is the same user running jobs on AWX which I think is in fact User 1000.

I've typically built the images and installed pip modules before by injecting the installation into the Dockerfile.sdist before the switch to user 1000 and that's worked fine in docker and K8s.  I've installed pip modules into user space before and Ansible has picked them up so I'm doing a bit of generalizing / hopeful thinking.

**Comment by kenmaglio** [comment]
We have decided to move forward with pushing any required PIP modules into our docker image build process. However, this breaks the development flow of python Ansible modules and use of them pretty badly vs. how things used to operate before.
