### ISSUE TITLE
Distinguish requests from API/UI for analytics

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/awx#3823]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
We need to be able to determine if a request to the API is coming from the UI for analytics data.  

The UI may be able to add a flag/header with each request which can be checked by the API as a way of definitively knowing the request came from the UI and not an integration like tkit, etc.  

Once this is added, we should add the following queries to analytics collection:
* Number of Jobs launched by UI/API 
* Maybe add a field to the Job named `launch_method`
   + if so, add `launch_method` to the `main_unified_job` table copy.

**Comment by mabashian** [comment]
If we do go down the route of adding a custom header to every request [this would be the place to do it](https://github.com/ansible/awx/blob/devel/awx/ui/client/src/rest/interceptors.service.js#L18).  Pretty straightforward, this interceptor hooks in on _every_ request afaik.

**Comment by wenottingham** [comment]
OK.

**Comment by unlikelyzero** [comment]
Note for future selves: test haproxy+ssl deployment

**Comment by wenottingham** [comment]
Folding into a different issue.
