### ISSUE TITLE
Clicking on another project (different page) does not retain pagination context

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#3829]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Navigating away from one project to another can lose the current page, under certain circumstances

##### STEPS TO REPRODUCE

In my setup, I have 16 pages of projects

 - navigate to page 5, and click on one of the projects on this page
 - without X-ing the current project's edit window, I click on page 6 (the edit window remains open)
 - I click on a project in page 6 to bring up the edit window of that project
 - check the list under the edit window

##### EXPECTED RESULTS

Stays on page 6, the 2nd project I clicked on is highlighted with the blue marker next to it.

##### ACTUAL RESULTS

List is at page 1

**Comment by awithrow9** [comment]
Think this is fixes, please test

**Comment by AlanCoding** [comment]
Tested with 3 pages of inventories, and it is not a problem there.

Will take me a minute to spin up >50 projects.

**Comment by AlanCoding** [comment]
I have made enough to re-test.

The issue still exists. Clicking on a page 3 project (while having an active selection open) redirects the list to page 1. It may also be redirecting (without prior active selection) when active status changes are coming in over websocket, but not 100% sure about that.

**Comment by jlmitch5** [comment]
The issue here is that the search query params do not get added to the url when the link is clicked.  this is also true of the templates (and would be true of all new-style lists defined in features).

it is not true of the inventories list.  Trying to figure out what to change to propagate that query param.

**Comment by dsesami** [comment]
Page context is now properly maintained when navigating between these lists. I also verified this works on templates and other resources.
