### ISSUE TITLE
JT copy only copies 'first' credential

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#383]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

Have a JT that contains a machine, AWS, GCE, and Azure credential.

Click the 'copy' icon.

Only the machine credential makes it into the copy.

##### ENVIRONMENT
* AWX version: 1.0.0-somethingorother

##### ADDITIONAL INFORMATION

Proper fix is via https://github.com/ansible/awx/issues/283. Leaving open in case someone wants to write a targeted fix first...

**Comment by mabashian** [comment]
If we want to fix this before #283 then we'll need to insert some logic [here](https://github.com/ansible/awx/blob/devel/awx/ui/client/src/templates/copy-template/template-copy.service.js#L40).  Extra credentials are added to a JT via a separate POST to `/api/v2/job_templates/:id/extra_credentials/`.  After the base JT has been copied we'll need to grab any `extra_credentials` from the `summary_fields` and POST those to the new JT.  The only slightly tricky part would be handling up to 2 promises (extra creds and survey) both of which would have to be processed after the initial POST.

**Comment by AlanCoding** [comment]
Agreed, this will be swept up by #283

**Comment by jian-feng** [comment]
Alan just mentioned that part is done, in #283. Could you please review this issue again?
Our customer is waiting for this fix and they will go production in March.

Best regards,
Feng

**Comment by matburt** [comment]
If they are a Tower customer then this will be available in the next Tower release which is not ready yet @jian-feng

**Comment by jakemcdermott** [comment]
resolved by https://github.com/ansible/awx/pull/903 and https://github.com/ansible/awx/pull/1201.

As matburt pointed out, this will be in the next Tower release
