### ISSUE TITLE
Smart Inventory Host Filter pop-up when no hosts in inventory

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#3830]
##### SUMMARY
The UI has a feature that shows `YOU MUST HAVE ACCESS TO AT LEAST ONE HOST IN ORDER TO CREATE A SMART INVENTORY HOST FILTER` in the host-filter builder pop-up when an the selected Organization has no hosts in it. The query below is how the UI determines this. This is good.
http://127.0.0.1:8013/api/v2/hosts/?order_by=name&page_size=5&inventory__organization=105

The problem is the error message (and check) isn't done until you clear all your host filter filters.

##### STEPS TO REPRODUCE

* Create an org with no hosts
* Build a Smart Inventory host filter for the org you created

##### EXPECTED RESULTS

* For the "no hosts" helper message to show right when I click the smart filter builder.

##### ACTUAL RESULTS

* The helper message doesn't show up until I clear all my search terms.

##### ADDITIONAL INFORMATION

![smart_inventory_no_hosts](https://user-images.githubusercontent.com/722880/42238277-449402f2-7ece-11e8-90de-bfc7524da190.gif)

**Comment by mabashian** [comment]
The UI should _always_ show the search bar in this modal regardless of the number of matching hosts.  This includes the initial state where a filter has not been applied.

**Comment by dsesami** [comment]
when viewing the search filter modal with an organization that has no hosts, I see the default message for adding host filters, not the "no hosts" helper message that was expected.

With a random filter:
![Screenshot from 2019-07-29 11-48-43](https://user-images.githubusercontent.com/19942822/62062369-e1361580-b1f6-11e9-8f71-87d28014e422.png)

With no filter, but no accessible hosts for the org (expected no hosts message):
![Screenshot from 2019-07-29 11-48-54](https://user-images.githubusercontent.com/19942822/62062398-f0b55e80-b1f6-11e9-9a38-59a1ddb2e4e7.png)

Let me know if you see this as well, and we can figure out what's going on if you get different results.

**Comment by nixocio** [comment]
Reopen if we see this behavior on the new UI.
