### ISSUE TITLE
The UI will PATCH to all instead of DELETE when reverting settings category to defaults

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#3831]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
The UI does not follow the intended API contract when reverting settings

##### ENVIRONMENT
* AWX version: all
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

go to the UI page `/#/configuration/system`

navigate to the logging sub-category

click "REVERT ALL TO DEFAULT"

##### EXPECTED RESULTS

DELETE to `/api/v2/settings/logging/`

##### ACTUAL RESULTS

PATCH to `/api/v2/settings/all/` with all of this data

https://gist.github.com/AlanCoding/034f9ec18fa7eb5037f221fa015937cc

This creates an enormous swarm of activity stream entries.

It also reverts all non-logging settings, which isn't what the user expects based on the dialog.

**Comment by unlikelyzero** [comment]
@AlanCoding has it been this way since the dawn of time?

**Comment by AlanCoding** [comment]
> has it been this way since the dawn of time?

Since the introduction of configure-tower-in-tower, yes

**Comment by AlanCoding** [comment]
Actually, I might be wrong on one point. Break this into 2 items:

1. UI uses PATCH instead of DELETE
2. reverting a category reverts all settings

I know that 1 has been that way since the introduction of the feature. I am not so sure about 2. In fact, 2 probably needs to be re-tested, and it is a fairly severe bug.

**Comment by AlanCoding** [comment]
Ok, re-tested 2nd point, and it doesn't work exactly as originally stated.

The UI gets the defaults of all settings, and then when reverting a category, it does do a PATCH with all the values, but it does this with the user-provided values from the GET. It then replaces with the defaults only for the current category.

So that may be working as designed. In other words, it's not changing values from categories other than the current window.

**Comment by AlanCoding** [comment]
The point 1 is still inherently problematic.

![url_reset](https://user-images.githubusercontent.com/1385596/57620550-1798b880-7557-11e9-9edf-4fe84a5899a7.gif)

In this example, I visit from `http://localhost:8013` and reset to defaults. Then I visit from `https://localhost:8043` and reset to defaults. Resetting to defaults should never change values. It's not a factory default if it does. However, the value does change depending on the URL from which the server is being accessed, which may change in real customer environments due to reasons much less superficial than in my example.

**Comment by mabashian** [comment]
I _think_ I understand why we don't `DELETE` but rather `PATCH` all the visible fields.  Not all of these forms correspond 1:1 with an endpoint:

- Authentication
  - AZURE AD - /api/v2/settings/azuread-oauth2/
  - GITHUB
    - Default - /api/v2/settings/github/
    - Org - /api/v2/settings/github-org/
    - Team - /api/v2/settings/github-team/
  - GOOGLE OAUTH2 - /api/v2/settings/google-oauth2/
  - LDAP - /api/v2/settings/ldap/
  - RADIUS - /api/v2/settings/radius/
  - SAML - /api/v2/settings/saml/
  - TACACS+ - /api/v2/settings/tacacsplus/
- Jobs (no extra tabs) - /api/v2/settings/jobs/
- System
  - MISC. SYSTEM - /api/v2/settings/system/ (partial) /api/v2/settings/authentication/ (partial)
  - ACTIVITY STREAM  - /api/v2/settings/system/ (partial)
  - LOGGING - /api/v2/settings/logging/
- User Interface (no extra tabs) - /api/v2/settings/ui/

The problematic forms are MISC. SYSTEM and ACTIVITY STREAM where we pull fields from multiple different endpoints/fields from the system endpoint show up across both of the forms.  We _could_ `DELETE` for most of the forms but doing so for the aforementioned two would cause fields that are potentially on other forms to be reverted.  I assume that these fields were grouped for a reason in the UI but if the forms matched up 1:1 with the api's endpoints then this would be trivial.  Alternatively we could use `DELETE` for the forms that do match up and `PATCH` for the forms that don't.  @AlanCoding @wenottingham thoughts?

**Comment by unlikelyzero** [comment]
@mabashian @marshmalien @AlanCoding we're about halfway through redoing all these forms. Can we sync on this next week?

**Comment by akus062381** [comment]
An additional error has been discovered in SAML settings- When editing SAML settings, I entered random information for two of the required fields and clicked save, and I got the error message reminding me to fill in the third required field. I entered random letters and numbers and clicked save, and saw this:
![image](https://user-images.githubusercontent.com/63685497/119551176-56c58b00-bd67-11eb-8987-ce495b479c5c.png)

**Comment by akus062381** [comment]
@mabashian can I just check in on this with you? Just making sure that it's ok for it to be left alone before the release?

**Comment by mabashian** [comment]
Note:

Looks like these authentication settings weren't being displayed in any forms in the UI:

```
    AUTHENTICATION_BACKENDS
    SOCIAL_AUTH_ORGANIZATION_MAP
    SOCIAL_AUTH_TEAM_MAP
    SOCIAL_AUTH_USER_FIELDS
```
