### ISSUE TITLE
On Org Detail Page, 'User' count includes direct and indirect memberships

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#3832]
#Steps To Reproduce
Precondition: Organization with 2 member, 2 system admins and one of those system admins is given the member role.
1. As a system admin, view the /organizations/N/users page. Note that 4 Users are shown in the 'Organization Users' view
2. On the organization view, on the 'Org List Subpane' and note that the 'User Count' is 3.

<img width="1167" alt="screen shot 2018-04-13 at 11 01 46 am" src="https://user-images.githubusercontent.com/12446869/38742866-a0712db4-3f0b-11e8-9296-ad710ad8c19a.png">

This count is consistent with the Organization Detail API.

#Expected Results
The expected behavior is that all users of an organization would be included in that count OR not shown as part of the org users list UNLESS they are a member of an org

#Actual Results
System admins are displayed on the 'Organization Users' view **in addition** to all other org members. They are indirect members but can also be direct members to an org. 
The 'User Count' for the Org List Subpane only displays direct memberships. This is inconsistent.

#Additional Information
This is also inconsistent with the System Admin View. All sysadmins are implicitly Org Admins but not listed. https://cl.ly/072s1O2V0Z0c

**Comment by ghost** [comment]
Link: https://github.com/ansible/awx/pull/3714

**Comment by dsesami** [comment]
Spoke with @wenottingham about the intended behavior here -- current behavior is that only users explicitly marked as `members` are included in the user count. as such, this works as intended and can be closed.
