### ISSUE TITLE
Start Template/Workflow for new created hosts 

### ISSUE THREAD

**Issue by RogerSik** [ansible/awx#3835]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Current situation: when creating a new host and than starting the all-system workflow it takes up to 20-30 minutes to get it rollout on all machine. An option to run the workflow *once* for only new created hosts would be nice. Current workaround is to copy the workflow and limit it to the new hosts.

**Comment by wenottingham** [comment]
Is #1845 what you're looking for?

**Comment by wenottingham** [comment]
closing as dup of #1845
