### ISSUE TITLE
Skip SSL Verification for Webhooks with SelfSigned Certificates on Endpoint

### ISSUE THREAD

**Issue by zicklam** [ansible/awx#3838]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
 - Notification with type "Webhook" against https services with self-signed certificates will fail with error message:
  ```awx.main.tasks Send Notification Failed ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)```

 - This PR will add an addiditonal checkbox to disable the verify process of ssl certificates within the send request.
 
 - Feature copied from other already existing notification types.

##### ENVIRONMENT
 - AWX Version: [4.0.0](https://github.com/ansible/awx/tree/4.0.0)

**Comment by lukepafford** [comment]
*Notice* - I'm running Ansible Tower version 3.3.2 and assume the differences between AWX are minimal.

I too have a webhook notification and I was receiving the same error. However the webhook server has a certificate from a custom certificate authority. I do **not** want to disable SSL verification. Instead, we should be able to configure a root CA path in the /etc/tower/settings.py file.

The ability to add custom trusted certificates is very important for offline deployments, or environments with their own CA.

###  Workaround
I created an incredibly hacky workaround in the meantime. I noticed that since it is a Python app, it is likely using the `requests` library on the backend. In `requests` You can configure a trusted root certificate with the `REQUESTS_CA_BUNDLE` environment variable.

I tested this by setting the Supervisord environment value at `/etc/supervisord.conf`:
```
[supervisord]
environment=REQUESTS_CA_BUNDLE=/path/to/your/bundle-file.crt
...
```

Sure enough, after restarting the `supervisord` service my webhook notification no longer complained that it couldn't trust the certificate.

**Comment by ryanpetrello** [comment]
>  I'm running Ansible Tower version 3.3.2 and assume the differences between AWX are minimal.

Not a reasonable assumption to make 😉  Ansible Tower 3.3.2 is a product built off of AWX _at some point in time_ and was released over six months ago.  AWX is an upstream open source project, and differs _considerably_.

That said, thanks for chiming in on a workaround for those who don't yet have access to https://github.com/ansible/awx/pull/3839  `REQUESTS_CA_BUNDLE` is indeed a clever workaround (and yes, the webhooks notifications *do* use the `requests` library under the hood).

**Comment by elyezer** [comment]
Here are the steps done to verify this:

1) Create a self-signed certificate by running:

```console
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -out mycert.crt -keyout mycert.key
```

2) Created the following Python 2 HTTPS server script and started the HTTPS server:

```python
import BaseHTTPServer
import ssl
from io import BytesIO

class RequestHandler(BaseHTTPServer.BaseHTTPRequestHandler):
    def do_POST(self):
        content_length = int(self.headers['Content-Length'])
        body = self.rfile.read(content_length)
        print body
        self.send_response(200)
        self.end_headers()
        response = BytesIO()
        response.write('This is POST request. ')
        response.write('Received: ')
        response.write(body)
        self.wfile.write(response.getvalue())

httpd = BaseHTTPServer.HTTPServer(('localhost', 9999), RequestHandler)

httpd.socket = ssl.wrap_socket (httpd.socket,
        keyfile="mycert.key",
        certfile='mycert.crt', server_side=True)

httpd.serve_forever()
```

3) Created a Webhook notification without checking the `Disable SSL verification` option
4) Ran a Job template configured to send the notification created on 3 and checked that the Notification failed to be sent as expected. The UI showed a red `!` icon and also had this on the logs:

```
awx_1        | 2019-09-05 13:57:04,829 ERROR    awx.main.tasks Send Notification Failed HTTPSConnectionPool(host='localhost', port=9999): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fce7e6797f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

5) Edited the notification created on 3 and now `Disable SSL verification` is checked.
6) Ran the same job template ran on 4 and checked if the server received the webhook notification. The server received notification for both start and succeed events, see below the output produced by the server:

```
{"id": 33, "name": "Demo Job Template", "url": "https://towerhost/#/jobs/playbook/33", "created_by": "admin", "started": "2019-09-05T13:59:24.906575+00:00", "finished": null, "status": "running", "traceback": "", "inventory": "Demo Inventory", "project": "Demo Project", "playbook": "hello_world.yml", "credential": "Demo Credential", "limit": "", "extra_vars": "{}", "hosts": {}, "friendly_name": "Job"}
127.0.0.1 - - [05/Sep/2019 13:59:25] "POST / HTTP/1.1" 200 -
{"id": 33, "name": "Demo Job Template", "url": "https://towerhost/#/jobs/playbook/33", "created_by": "admin", "started": "2019-09-05T13:59:24.906575+00:00", "finished": "2019-09-05T13:59:32.775812+00:00", "status": "successful", "traceback": "", "inventory": "Demo Inventory", "project": "Demo Project", "playbook": "hello_world.yml", "credential": "Demo Credential", "limit": "", "extra_vars": "{}", "hosts": {"localhost": {"failed": false, "changed": 0, "dark": 0, "failures": 0, "ok": 2, "processed": 1, "skipped": 0, "rescued": 0, "ignored": 0}}, "friendly_name": "Job"}
127.0.0.1 - - [05/Sep/2019 13:59:33] "POST / HTTP/1.1" 200 -
```

With all the above we can consider this issue as verified.
