### ISSUE TITLE
Unable to reorder Instance Groups for Org

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#3840]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Related to https://github.com/ansible/awx/issues/3679

When trying to reorder instance groups in a JT, Inventory, or Organization to select a "default", saving the reordered group appears to always reorder according to IG id. 

##### ENVIRONMENT
* AWX version: 3.4

##### STEPS TO REPRODUCE
1. Create at least 2 instance groups in AWX
2. Navigate to Organizations 
3. Remove the default (`tower`) from the list of IGs.
4. Save
5. Add the secondary IGs, and add `tower` _last_ so it appears as:
```
x test
x new-test
x tower
```
6. Save

##### EXPECTED RESULTS
Order is maintained after the save

##### ACTUAL RESULTS
`tower` reverts to the first spot

##### ADDITIONAL INFORMATION
Appears to be coinciding with the IG id from the database:
```
awx=> select id, name from main_instancegroup;
-[ RECORD 1 ]---
id   | 1
name | tower
-[ RECORD 2 ]---
id   | 2
name | test
-[ RECORD 3 ]---
id   | 3
name | new-test
-[ RECORD 4 ]---
id   | 4
name | supertest
```

**Comment by ryanpetrello** [comment]
Closing this in lieu of https://github.com/ansible/awx/issues/3679

**Comment by ryanpetrello** [comment]
@AlanCoding so this may actually be more difficult than we initially thought:

```python
Traceback (most recent call last):
  File "/awx_devel/awx/main/tests/functional/task_management/test_rampart_groups.py", line 153, in test_failover_group_run
    objects1.job_template.instance_groups.add(ig1)
  File "/venv/awx/lib64/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 929, in add
    (opts.app_label, opts.object_name)
AttributeError: Cannot use add() on a ManyToManyField which specifies an intermediary model. Use main.UnifiedJobTemplateInstanceGroupMembership's Manager instead.
```

Looks like this is a limitation of M2M `through=...` in Django < 2:

https://docs.djangoproject.com/en/1.11/topics/db/models/#intermediary-manytomany
![image](https://user-images.githubusercontent.com/214912/57252035-3e1b9880-7019-11e9-8cc7-65753202992f.png)

We make _extensive_ use of `.add()` and `.remove()` in our associate/disassociate API implementation, so this could end up being a real pain to deal with.  We may have to get more creative about how we approach this.

https://github.com/django/django/blob/1.11.20/django/db/models/fields/related_descriptors.py#L924

**Comment by kdelee** [comment]
This works for me, going to close
