### ISSUE TITLE
Strange string in activity stream for various resources

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#3841]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Strings look odd in their current format in activity streams when assigning a role to a resource, whether it is a project, inventory, credential, or job template.

The first string in the row here shows what I mean:
> associated admin admin_role to machine-credential
In generic terms:
> associated [user] [role name] to [resource]
1. Is admin_role (the role name) supposed to be written out like the way it is in the screenshot?
2. The phrasing is odd. This should be rephrased to something like:
> associated [resource] [role name] with [user]
Written out, it would look like
> associated machine-credential admin_role to admin
![Screenshot from 2019-05-06 15-50-34](https://user-images.githubusercontent.com/19942822/57252376-f1848d00-7019-11e9-96ab-a70755683706.png)

##### ENVIRONMENT
* AWX version: latest
* AWX install method: docker on linux
* Operating System: Fedora 30
* Web Browser: Chrome

##### STEPS TO REPRODUCE
1. Create a resource, like a credential.
2. Assign role to it.
3. Visit the activity stream for the resource.

**Comment by AlexSCorey** [comment]
After further investigation I have found that when the initial credential is created is automatically creates a permission that gives the creator the admin role.  When this happens the api creates an object that looks like this```

description: "associated  <a href="/#/credentials/27/">&nbsp;1&nbsp;</a> admin_role to  <a href="/#/users/1/">&nbsp;admin&nbsp;</a> "
id: 131
object1: "credential"
object2: "user"
object_association: "role"
operation: "associate"
type: "activity_stream"
url: "/api/v2/activity_stream/131/"
user: "<a href="/#/users/1">admin</a>

``` where object1 is `credential and object2 is `user.  Then when other users are given permission manually the api sends the same information but object 1 is `user` and object 2 is `credential`.  Effectively making the string in the `event` column read strangely.

**Comment by dsesami** [comment]
Phrasing has been corrected and the links are formatted as expected.
