### ISSUE TITLE
Workflow shows as successful when a job template fails but has a successful task after always or failure branch 

### ISSUE THREAD

**Issue by geauxvirtual** [ansible/awx#3843]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
A workflow will show as successful when a job template or workflow template fails but runs a successful job template or workflow on a failure or always branch.

##### ENVIRONMENT
* AWX version: 3.0.0
* AWX install method: kubernetes
* Ansible version:  2.7.6

##### STEPS TO REPRODUCE

Create a workflow with a job template that fails. Add a successful job template that will execute when the previous job template either fails, or add the successful job template to always execute.

##### EXPECTED RESULTS

Workflow should show as failed regardless of execution results of any tasks on a failure or always branch after a failed job template or workflow template.

##### ACTUAL RESULTS

Workflow reports as successful even though job template failed.

**Comment by wenottingham** [comment]
This is intentional. Workflow failure is defined as "a failure that is not caught/handled by a subsequent node".

If you need to propagate a failure, a final "failed when" step is likely useful.
