### ISSUE TITLE
Basic search not working when defining smart inventory host filter

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#3845]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
See gif:

![host_filter](https://user-images.githubusercontent.com/9889020/57314808-5bf00880-70c0-11e9-8c5a-555382164d01.gif)

We're making this request: `/api/v2/hosts/?order_by=name&page_size=5&inventory__organization=1&host_filter=local` from the UI when we should be making this request: `/api/v2/hosts/?order_by=name&page_size=5&inventory__organization=1&host_filter=search=local`

Note that searching by a key like `name:local` is still working as expected.

##### STEPS TO REPRODUCE
1. Go to smart inventory form
2. Open host filter modal
3. Type in `local`
4. Hit enter

##### EXPECTED RESULTS
List is filtered down to hosts that match `local`

##### ACTUAL RESULTS
400 error thrown by api due to bad query syntax

**Comment by mabashian** [comment]
Looks like this got introduced when we fixed https://github.com/ansible/awx/issues/950

**Comment by unlikelyzero** [comment]
Verified by Mike locally:
- foo - search=foo
- foo bar - search=foo and search=bar
- foo or bar - search=foo or search=bar
- name:foo or bar - name__icontains=foo or search=bar
- name:foo bar - name__icontains=foo and search=bar
- foo or name:bar - search=foo or name__icontains=bar
- foo name:bar - search=foo and name__icontains=bar
- name:foo or name:bar - name__icontains=foo or name__icontains=bar
- name:foo name:bar - name__icontains=foo and name__icontains=bar
- name:foo name:bar or baz - name__icontains=foo and name__icontains=bar or search=baz
- baz or name:foo name:bar or baz - search=baz or name__icontains=foo and name__icontains=bar

Verified on a production install:
- Various versions of the above
- or logic with additional fields (id, created)
- and logic with additional fields (id, created)
- Running JT actual smart inventory

**Comment by mabashian** [comment]
Fix coming shortly - closing for now
