### ISSUE TITLE
RFE: Link credentials in job details view

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#385]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY

When viewing/editing a job template, you'll get a list of all the credentials that job uses.

Clicking on the non-'x' portion of that label should take you to that credential details.

##### ENVIRONMENT
* AWX version: 1.0.0-recent

**Comment by akus062381** [comment]
implemented
