### ISSUE TITLE
smart inventory filter ansible_facts.ansible_distribution_major_version gives no result

### ISSUE THREAD

**Issue by HaraldPaterek** [ansible/awx#3862]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I am trying to build a smart inventory with the following filter:

ansible_facts.ansible_distribution_major_version:"6"

This doesn't return any hosts. Looking up a RHEL6 hosts I see the fact:

ansible_distribution_major_version: '6'

Repeating the query with single quotes or no quotes gives the same result.

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.9
* Operating System: RHEL 7.6
* Web Browser: Firefox on OSX

##### STEPS TO REPRODUCE

Select Inventories in the UI, Click on Hosts. In the filter field enter the filter specified above. 

##### EXPECTED RESULTS

A list of hosts running RHEL 6

##### ACTUAL RESULTS

No results were returned.

**Comment by HaraldPaterek** [comment]
The issue seems to be it doesn't like integers. When searching ansible_facts.ansible_distribution_release:Santiago it delivers valid results. 

Searching for ansible_facts.ansible_distribution_version:6.10 gives no results, neither when quoting the 6.10.

But this returns results: ansible_facts.ansible_processor_vcpus:4

**Comment by shanemcd** [comment]
Likely https://github.com/ansible/awx/issues/3845

We can keep this open until the code lands upstream.

**Comment by ryanpetrello** [comment]
Should be resolved in the next version of AWX via https://github.com/ansible/awx/commit/f524c94bad1a710d152c8539dc1471aa767017bd cc @mabashian
