### ISSUE TITLE
No permission to add a survey to job templates

### ISSUE THREAD

**Issue by alancivita** [ansible/awx#388]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

I'm using LDAP for user authentication. (but i can reproduce the error with local users as well)
I have a user, who is an Admin, but it can't add surveys to job templates. 
This is the error i get:
ERROR!
You do not have permission to perform this action.

Apparently only the default Admin user can do that

##### ENVIRONMENT

* AWX version: 1.0.0.561
* AWX install method:  docker on linux (from docker hub)
* Ansible version:  
* Operating System: MacOS Sierra
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Login as a users, with admin roles, different from the local admin user.
Create a new job template, add a survey.

##### EXPECTED RESULTS

To Be able to add the survey
##### ACTUAL RESULTS
Unable to add survey

**Comment by AlanCoding** [comment]
Could be related to #157, do you see anything in the logs?

**Comment by alancivita** [comment]
from awx_web container i can see only this warning:
`2017-10-10 12:03:56,120 WARNING  awx.api.generics status 403 received by user aci56 attempting to access /api/v2/job_templates/8/survey_spec/ from 10.110.222.9
[pid: 30|app: 0|req: 540/3346] 10.110.222.9 () {54 vars in 2436 bytes} [Tue Oct 10 12:03:56 2017] POST /api/v2/job_templates/8/survey_spec/ => generated 63 bytes in 99 msecs (HTTP/1.1 403) 7 headers in 224 bytes (1 switches on core 0)
10.110.222.9 - - [10/Oct/2017:12:03:56 +0000] "POST /api/v2/job_templates/8/survey_spec/ HTTP/1.1" 403 74 "http://10.45.67.89/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" "-"
2017-10-10 12:04:25,973 WARNING  awx.api.generics status 403 received by user aci56 attempting to access /api/v2/job_templates/8/survey_spec/ from 10.110.222.9
[pid: 30|app: 0|req: 541/3347] 10.110.222.9 () {54 vars in 2436 bytes} [Tue Oct 10 12:04:25 2017] POST /api/v2/job_templates/8/survey_spec/ => generated 63 bytes in 77 msecs (HTTP/1.1 403) 7 headers in 224 bytes (1 switches on core 0)
10.110.222.9 - - [10/Oct/2017:12:04:25 +0000] "POST /api/v2/job_templates/8/survey_spec/ HTTP/1.1" 403 74 "http://10.45.67.89/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" "-"`

awx_task is set to debug and it's a bit hard to find something useful, any idea how change the log level for awx_task?

thanks for the help.

**Comment by AlanCoding** [comment]
Thanks, those logs are consistent with my first reading of the issue. When you say "local admin user", do you mean the user has the "admin" role to the job template? You can navigate to the job template in the UI and see the PERMISSIONS tab. Any user with admin permission (directly or indirectly) should be able to change the survey spec. Given that's the case, this certainly sounds like a bug.

**Comment by alancivita** [comment]
with local admin i mean the builtin admin user.
As you can see from the attached screenshot, the user aci06 has the admin role on the specific template, but it's still unable to save a survey.
<img width="1539" alt="screenshot at oct 10 14-20-17" src="https://user-images.githubusercontent.com/23634711/31386196-39dfcfa0-adc6-11e7-8bc2-353302a57716.png">

<img width="1214" alt="screenshot at oct 10 14-22-51" src="https://user-images.githubusercontent.com/23634711/31386286-8b10404e-adc6-11e7-93c7-55ee731e3015.png">

**Comment by AlanCoding** [comment]
Thanks. Just to confirm expectations - users `aci06` and `admin` in the above screenshot should both have permission to modify the survey_spec.

**Comment by alancivita** [comment]
Great, let me know if you need any further info or logs.

**Comment by AlanCoding** [comment]
@alancivita thanks for your help with this. I was able to replicate and the fix PR is up.

**Comment by alancivita** [comment]
pleasure!
