### ISSUE TITLE
Drop-down sort on Projects looks mis-aligned

### ISSUE THREAD

**Issue by tvo318** [ansible/awx#3884]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

![image](https://user-images.githubusercontent.com/7514801/57636216-f4c1d080-7565-11e9-9a3f-cea28c575943.png)

##### ENVIRONMENT
* Tower version: 3.5.0
* AWX install method: playbook run from tower.ansible.eng.rdu2.redhat.com
* Ansible version:  2.8.0b1.post0
* Operating System: Mac Mojave 10.14.4
* Web Browser: Chrome Version 74.0.3729.131 (Official Build) (64-bit)

##### STEPS TO REPRODUCE
1. View Projects list
2. Click on the Sort drop-down menu

##### EXPECTED RESULTS

Expected the drop-down menu options to be enclosed inside the menu, not spew outside of it.

##### ACTUAL RESULTS

Saw the drop-down menu options not enclosed inside the confines of the drop-down menu.

**Comment by dsesami** [comment]
Tried this with a variety of window sizes -- the dropdown works correctly and looks good. :+1:
