### ISSUE TITLE
Missing Instance Group label

### ISSUE THREAD

**Issue by tvo318** [ansible/awx#3886]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Missing Instance Group Name in the Jobs tab.

##### ENVIRONMENT
* Tower version: 3.5.0
* AWX install method: playbook run from tower.ansible.eng.rdu2.redhat.com
* Ansible version:  2.8.0b1.post0
* Operating System: Mac Mojave 10.14.4
* Web Browser: Chrome Version 74.0.3729.131 (Official Build) (64-bit)

##### STEPS TO REPRODUCE
1. Go to Instance Groups
2. Click on an Instance Group to view its details.
3. Click on the Jobs tab.

##### EXPECTED RESULTS

Expected to see the Instance Group Name and not the tab label:
Screen from previous version of Tower, showing _Instance Group 1_ as the IG name when viewing Jobs:

![image](https://user-images.githubusercontent.com/7514801/57640575-1cb63180-7570-11e9-8912-c2b6072534a4.png)

##### ACTUAL RESULTS
The IG name is lost and only showing the Jobs label. All other tabs (**Details** and **Instances** both have the correct IG name displayed)

![image](https://user-images.githubusercontent.com/7514801/57640668-5b4bec00-7570-11e9-9d6c-3feeb3ad6ec0.png)

##### ADDITIONAL INFORMATION

Instances and Detail tabs display the IG name as expected:

![image](https://user-images.githubusercontent.com/7514801/57640923-e0370580-7570-11e9-872b-adef9e3216e5.png)

**Comment by dsesami** [comment]
This appears to still say "Jobs" in the name area where we would expect the instance group name to appear. Moving back to needs_devel
cc @marshmalien let me know if there's anything I can do to help here.

screenshot:
![Screenshot from 2019-06-21 10-30-45](https://user-images.githubusercontent.com/19942822/59929913-c90cf280-940f-11e9-957c-49491630fb36.png)

**Comment by dsesami** [comment]
Reread correct behavior -- this is correct, actually and shows the instance group name.
