### ISSUE TITLE
Build sdist builder image task fails

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/awx#3888]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Build sdist builder image task fails in repo tag 4.0.0. Error is caused by Dockerfile.sdist.

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.10
* Operating System: Ubuntu 18 bionic

##### STEPS TO REPRODUCE

git clone clone https://github.com/ansible/awx.git
git checkout tags/4.0.0
comment/remove dockerhub_base in inventory
uncomment/add use_container_for_build=true

##### EXPECTED RESULTS

Image build and container start

##### ACTUAL RESULTS

/awx/installer/roles/image_build/files/Dockerfile.sdist

> RUN ls -s /usr/bin/python36 /usr/bin/python3

fails with:

> failed to create symbolic link

Adding force to the following line resolves the image build process:

> RUN ls -s -f /usr/bin/python36 /usr/bin/python3

However, the "Build AWX distribution using container" task is stuck and won't finish. 

> docker logs awx_sdist_builder

results in

> PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1 npm --unsafe-perm --prefix awx/ui ci --no-save awx/ui

##### UPDATE

Using devel branch does not have  RUN ls -s /usr/bin/python36 /usr/bin/python3 in the Dockerfile.sdist and sdist image builder does not fail.

npm 6.9.0
nodejs v10.15.3

I have also deleted docker and reinstalled from scratch. Same issue.

**Comment by xsecops** [comment]
Can confirm; experienced the same issue. What fixed this for was on Ubuntu: upgrade Ansible to the latest 2.8

`sudo apt-add-repository ppa:ansible/ansible
apt update
apt upgrade`

**Comment by nicolaibaralmueller** [comment]
> Can confirm; experienced the same issue. What fixed this for was on Ubuntu: upgrade Ansible to the latest 2.8
> 
> `sudo apt-add-repository ppa:ansible/ansible apt update apt upgrade`

@xsecops I have ansible 2.8 on centos7.3 and the error is still there.

**Comment by nicolaibaralmueller** [comment]
Using the latest devel branch does not produce this error. 

Someone needs to update the official 4.0.0 release!

**Comment by ryanpetrello** [comment]
This is resolved in newer versions of AWX.  Please try upgrading to 5.0.0 or 6.0.0 w/ Ansible 2.8.
