### ISSUE TITLE
<playbook-dir>/roles/requirements.yml is undetected during playbooks project creation

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/awx#3898]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
```<playbook-dir>/roles/requirements.yml``` is undetected during playbooks project creation. 

##### ENVIRONMENT
* AWX version: 3.0.0 --> 4.0.0-547-g6bc185665
* AWX install method: docker on linux
* Ansible version:  2.7.10
* Operating System: Debian buster
* Web Browser: chrome Version 74.0.3729.157 (Official Build) (64-bit)

##### STEPS TO REPRODUCE
- Settings/Jobs/Enable Role Download: ON
![Roles download enabled](https://user-images.githubusercontent.com/13176858/57763788-70588480-7702-11e9-96e7-818cf049374a.png)
- create playbooks project:
  + playbooks SCM type: git
  + playbooks SCM URL: valid private URL (not hosted on ansible galaxy)
  + playbooks SCM Update Options:
    * Clean
    * Delete on Update
    * Update Revision on Launch
  + playbooks git repository contains ```roles/requirements.yml```
  ```
  - src: <roles SCM private URL>
    scm: git
  ```

##### EXPECTED RESULTS

1) playbooks git repository cloned
2) roles downloaded from ```<roles SCM private URL>```

##### ACTUAL RESULTS

1) playbooks git repository cloned, including the file ```roles/requirements.yml```
2) roles NOT downloaded

##### ADDITIONAL INFORMATION:
1) private git repositories are located on the host running the AWX containers
2) Playbooks project creation job log
```
PLAY [all] *********************************************************************
TASK [delete project directory before update] **********************************
ok: [localhost]
TASK [check repo using git] ****************************************************
skipping: [localhost]
TASK [update project using git] ************************************************
changed: [localhost]
TASK [Set the git repository version] ******************************************
ok: [localhost]
TASK [update project using hg] *************************************************
skipping: [localhost]
TASK [Set the hg repository version] *******************************************
skipping: [localhost]
TASK [parse hg version string properly] ****************************************
skipping: [localhost]
TASK [update project using svn] ************************************************
skipping: [localhost]
TASK [Set the svn repository version] ******************************************
skipping: [localhost]
TASK [parse subversion version string properly] ********************************
skipping: [localhost]
TASK [Ensure the project directory is present] *********************************
skipping: [localhost]
TASK [Fetch Insights Playbook(s)] **********************************************
skipping: [localhost]
TASK [Save Insights Version] ***************************************************
skipping: [localhost]
TASK [Repository Version] ******************************************************
ok: [localhost] => {
    "msg": "Repository Version 5a89c492c2be5f3911a39f7a36ac10bc46f89017"
}
TASK [Write Repository Version] ************************************************
changed: [localhost]
PLAY [all] *********************************************************************
TASK [detect requirements.yml] *************************************************
skipping: [localhost]
TASK [fetch galaxy roles from requirements.yml] ********************************
skipping: [localhost]
TASK [fetch galaxy roles from requirements.yml (forced update)] ****************
skipping: [localhost]
PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=2    unreachable=0    failed=0   
```
3) Checking ```<roles SCM private URL>``` by manually cloning the roles on the localhost:
```
/tmp/test# git clone <roles SCM private URL> .
remote: Enumerating objects: 2889, done.
remote: Counting objects: 100% (2889/2889), done.
remote: Compressing objects: 100% (2483/2483), done.
remote: Total 2889 (delta 1905), reused 0 (delta 0)2.15 MiB/s   
Receiving objects: 100% (2889/2889), 237.81 MiB | 20.66 MiB/s, done.
Resolving deltas: 100% (1905/1905), done.
Checking out files: 100% (937/937), done.
```
4) Suggestion:
Since the block where ```detect requirements.yml``` is defined in ```project_update.yml``` is executed only when ```roles_enabled``` is true, there are at least 2 possible causes for this issue:
- roles_enabled is not properly set  as true depending on the value ON defined in the settings
- roles_enabled is modified somewhere in the code after is has been assigned

**Comment by jean-christophe-manciot** [comment]
A closer look shows that:
- ```git-awx/awx/playbooks/project_update.yml``` is very different from ```/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/playbooks/project_update.yml```
    Why?
- in particular, the block conditional check in the latter is ```scm_full_checkout|bool and roles_enabled|bool``` instead of ```roles_enabled|bool```
- this brings 2 more possible causes to this issue: ```scm_full_checkout``` is not correctly set or is modified after it has been set

**Comment by jean-christophe-manciot** [comment]
In ```/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/playbooks/project_update.yml```:
```
# scm_full_checkout: true (if for a job template run), false (if retrieving revision)
```
When the playbooks project is created or synced, is it considered a ```job template run```?

**Comment by wenottingham** [comment]
> git-awx/awx/playbooks/project_update.yml is very different from /var/lib/awx/venv/awx/lib/python3.6/site packages/awx/playbooks/project_update.yml Why?

Were you comparing current git head to AWX 3.x or 2.x? If so, yes, it's going to be changed....

There are two types of project update runs:
- the 'update' run (to update the revision of the project). This passes `scm_full_checkout: false`
- the 'sync' run, before running a template on the project. This ensures the project is fully checked out so the playbook can run. This runs with `scm_full_checkout: true`.

**Comment by jean-christophe-manciot** [comment]
@wenottingham
> Were you comparing current git head to AWX 3.x or 2.x?

I was comparing:
- git-awx/awx/playbooks/project_update.yml from git awx sources tag ```4.0.0-547-g6bc185665``` (way beyond 4.0.0)
- /var/lib/awx/venv/awx/lib/python3.6/site packages/awx/playbooks/project_update.yml from within the container ```docker-compose_task_1``` built from the previous tag.
We can expect that both are identical, can't we?

> There are two types of project update runs:
> the 'update' run (to update the revision of the project). This passes scm_full_checkout: false
> the 'sync' run, before running a template on the project. This ensures the project is fully checked out so the playbook can run. This runs with scm_full_checkout: true.

The issue happens when:
- the project is created
- or the project is synced after its creation, outside any template run with the ```Get latest SCM revision``` button:
![sync](https://user-images.githubusercontent.com/13176858/57844911-34d8bb80-77d1-11e9-9ea8-39175f5c00bc.png)

It appears that following your explanation, **we have found the root causes of the issue**:
1) when the project is created, it does not appear to be worthwhile what you call a 'sync': ```scm_full_checkout``` is false
2) when the project is 'updated' with the ```Get latest SCM revision``` button, it is not 'synced' although it should be: ```scm_full_checkout``` is false

**As a proposal**:
- the boolean ```scm_full_checkout``` name is misleading: there seems to be some confusion between [git checkout](https://git-scm.com/docs/git-checkout) and [git fetch](https://git-scm.com/docs/git-fetch) (this [post](https://stackoverflow.com/a/30733500/9299396) shows a nice graph); the boolean variable should be **renamed everywhere in the code** to reflect the fact that the **remote changes need to be fetched**, or not, such as ```scm_fetch```
- the name is focused on git, so it may not be appropriate for other SCMs
- the roles fetch must be done in the following cases with ```scm_fetch``` set to true
  + when the project is created
  + when the project is manually synced with the ```Get latest SCM revision``` GUI button (what you call 'update')
  + when the project is run as part of a template run when ```Update revision on launch``` is requested in the project settings

**Comment by wenottingham** [comment]
> I was comparing:
> 
>     * git-awx/awx/playbooks/project_update.yml from git awx sources tag `4.0.0-547-g6bc185665` (way beyond 4.0.0)
> 
>     * /var/lib/awx/venv/awx/lib/python3.6/site packages/awx/playbooks/project_update.yml from within the container `docker-compose_task_1` built from the previous tag.
>       We can expect that both are identical, can't we?

The change was made in March... all I can say is that your build must be stale if it's showing the two-part conditional.

**Comment by jean-christophe-manciot** [comment]
> The change was made in March... all I can say is that your build must be stale if it's showing the two-part conditional.

You're right on this: the upgrade process from 3.0.0 as detailed [here](https://github.com/ansible/awx/blob/devel/INSTALL.md#maintenance-using-docker-compose) somehow did not work as expected. A closer look shows that:
- the containers have been renamed between the 2 releases (the docker-compose folder name has been replaced with 'awx')
- the newly created ```docker-compose/environment.sh``` matching ```/etc/tower/conf.d/environment.sh``` has a glitch with the ```DATABASE_PASSWORD=``` where the quotes are missing to protect some special characters in the password from being interpreted 
-  the images (```ansible/awx_*```) version which are pulled do not match the unstable tag, but the stable tag 4.0.0. There used to be some images matching the unstable tags on [dockerhub](https://hub.docker.com/r/ansible/awx_task/tags). This means that there are still differences between ```project_update.yml``` from git unstable checkout and the one inside the 4.0.0 ```awx_task``` container. 

I confirm that the roles are now downloaded with ```4.0.0```, even though another issue has surfaced regarding the folders tree below ```<playbook-dir>/roles/```.

How is it possible to correctly build from an unstable tag (such as```4.0.0-582-gf174902bb``` ) in order to get containers matching that tag?
