### ISSUE TITLE
Cannot search through facts with a `.` without quoting

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#390]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

Our service scan returns systemd services of the form `foo.service`. These are hard to search for.

##### ENVIRONMENT
* AWX version: 1.0.0-something

##### STEPS TO REPRODUCE

Attempt to enter a search parameter in the UI.

##### EXPECTED RESULTS

`ansible_facts.services.foobar.service.state:stopped` finds matching hosts.

##### ACTUAL RESULTS

`ansible_facts.services.foobar.service.state:stopped` fails to find matching hosts.

You have to use `ansible_facts.services.foobar%2Eservice.state:stopped`.

**Comment by mabashian** [comment]
Since the UI uses the `.` as a delimiter in the portion of the search term before the `:` I don't really see a great way around this other than escaping/quoting.
