### ISSUE TITLE
Run templates with more than 1 credential

### ISSUE THREAD

**Issue by cdvv7788** [ansible/awx#3902]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
I want to run a playbook to perform some changes on my entire infrastructure. I already have my inventory configured for that.
I want, however, to be able to use different keys for some parts of the infrastructure.
When I select credentials, there is a list with a radio button. I can select a different credential of different types, but not of the same.
What limitations would this add? Is this feasible?

**Comment by wenottingham** [comment]
-> #286
