### ISSUE TITLE
AWX web interface does not support HTTPS

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx#3907]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX web interface does not support HTTPS

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker on linux
* Ansible version:  not relevant
* Operating System: openSUSE Leap 15.0
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Install AWX using local_docker, make sure to put the path to a certificate file in your inventory file in ssl_certificate=, if necessary put the path to your trust anchors folder in ca_trust_dir

##### EXPECTED RESULTS
I expect the AWX web UI to be listening for HTTPS

##### ACTUAL RESULTS
The AWX web UI still only listens for HTTP

**Comment by gstorme** [comment]
https://github.com/ansible/awx/pull/3604

**Comment by lemmy04** [comment]
can we please have that merged in?

**Comment by ryanpetrello** [comment]
see: https://github.com/ansible/awx/pull/3604

**Comment by lemmy04** [comment]
this is getting somewhat ridiculous - AWX 5.0.0 is out by now, still no https.

**Comment by ryanpetrello** [comment]
For the sake of anybody viewing this issue in the future, https support *is* possible as shown by the numerous people at https://github.com/ansible/awx/pull/3604 reporting success.

@lemmy04 if you're having trouble getting this to work, there are a number of people that appear open to helping you diagnose the issue over at https://github.com/ansible/awx/pull/3604. As always, the mailing list and IRC room are also avenues to explore for getting help troubleshooting AWX.
