### ISSUE TITLE
large numbers of schedules cause a delay at dispatcher startup time

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#3912]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
1.  Install AWX with many schedules (100+) with this rrule:
```
In [1]: Schedule.objects.filter(unified_job_template_id=5).count()
Out[1]: 20
In [2]: Schedule.objects.filter(unified_job_template_id=5).first().rrule
Out[2]: 'DTSTART;TZID=America/New_York:20190517T000000 RRULE:FREQ=HOURLY;INTERVAL=2;COUNT=5'
```
2.  Start the dispatcher manually with `awx-manage run_dispatcher`.
3.  Observe that the jobs do not run until several minutes later.

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker

**Comment by ryanpetrello** [comment]
This is happening because at dispatcher startup time, we run this code (which blocks) _before_ we start consuming messages:

https://github.com/ansible/awx/blob/devel/awx/main/tasks.py#L109

**Comment by ryanpetrello** [comment]
As I see it, there are two ways to solve this problem:

1.  Calculate schedules somewhere else, or in a non-blocking way.  I don't _think_ (I could be wrong) we can **actually** do this, because the way that AWX schedules work is that if AWX goes _offline_ and comes back up, we **don't** run the schedules that were _missed_ in the meantime.  That means that we _have to_ calculate the "next run date" when the dispatcher process starts (so it doesn't run things for past dates).

2.  Make rrule date parsing faster by automatically moving `DTSTART` values forward.  One thing I've noticed about this bug is that it's *most* noticeable when you have an `rrule` without a `DTSTART` or recurrence rule that ends and does things like "run every X minutes/hours".  This results in *lots* of Python objects being created in memory.  For example, if you create a schedule in 2016 and have it run every 5 minutes, that's a _lot_ of dates to calculate every time need to do date math.

One thing we _could_ do is _change_ this code:

https://github.com/ansible/awx/blob/devel/awx/main/models/schedules.py#L207

So if a rule has `HOURLY` or `MINUTELY`, we could maybe parse the `DTSTART` value and *iff* it's in the past, _change_ it to `now() - 1_minute` (or `1_hour`).

**Comment by ryanpetrello** [comment]
I think _this_ code is actually the culprit regarding much of the slowness.

https://github.com/ansible/awx/blame/devel/awx/main/models/unified_jobs.py#L254

By commenting out this field computation on a JT with 1000 schedules, I'm seeing `Schedule.update_computed_fields()` go from ~4 minutes to ~10 seconds.

**Comment by AlanCoding** [comment]
Implementation details of the merged solution (for testing):

 - no schema changes were made
 - a change _was_ made that `next_run` of a schedule will not be updated if it is disabled
 - the database operations were reduced by efficiency tweaking that should not affect functionality

I believe you should still be able to get the preview endpoint for a disabled schedule, I don't feel like we're losing anything. Also, no observables on job templates should change at all.

**Comment by kdelee** [comment]
Now I've tested a large number of disabled schedules (minutely) that have a old start date + a large number of enabled schedules that have an old start date (hourly). I create them and then turn off tower for a half an hour or so. Then I timed starting up tower again. Both cases took very reasonable amounts of time.  Going to close this
