### ISSUE TITLE
Incorrect URL being used for Red Had Insights project synchronisation

### ISSUE THREAD

**Issue by bigtob** [ansible/awx#3916]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Incorrect URL endpoint being used for project synchronisation, using an Insights credential.

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.0
* Operating System: RHEL 7.4
* Web Browser: Chrome 74

##### STEPS TO REPRODUCE

1) Create an Insights credential
2) Create an Insights project
3) Synchronise project

##### EXPECTED RESULTS

Successful synchronisation of project.

##### ACTUAL RESULTS

Synchronisation job fails because of an incorrect endpoint: https://example.org/r/insights/v3/maintenance?ansible=true

`Using /etc/ansible/ansible.cfg as config file
/tmp/awx_297_6mslrjox/inventory/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/tmp/awx_297_6mslrjox/inventory/hosts did not meet script requirements, check plugin documentation if this is unexpected
PLAY [all] *********************************************************************
TASK [delete project directory before update] **********************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [check repo using git] ****************************************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [update project using git] ************************************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [Set the git repository version] ******************************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [update project using hg] *************************************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [Set the hg repository version] *******************************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [parse hg version string properly] ****************************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [update project using svn] ************************************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [Set the svn repository version] ******************************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [parse subversion version string properly] ********************************
skipping: [localhost,] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [Ensure the project directory is present] *********************************
ok: [localhost,] => {"changed": false, "gid": 0, "group": "root", "mode": "0755", "owner": "root", "path": "/var/lib/awx/projects/_28__insights_project", "size": 6, "state": "directory", "uid": 0}
TASK [Fetch Insights Playbook(s)] **********************************************
fatal: [localhost,]: FAILED! => {"changed": false, "msg": "Expected https://example.org/r/insights/v3/maintenance?ansible=true to return a status code of 200 but returned status code \"404\" instead with content \"<!doctype html>\n<html>\n<head>\n    <title>Example Domain</title>\n\n    <meta charset=\"utf-8\" />\n    <meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n    <style type=\"text/css\">\n    body {\n        background-color: #f0f0f2;\n        margin: 0;\n        padding: 0;\n        font-family: \"Open Sans\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n        \n    }\n    div {\n        width: 600px;\n        margin: 5em auto;\n        padding: 50px;\n        background-color: #fff;\n        border-radius: 1em;\n    }\n    a:link, a:visited {\n        color: #38488f;\n        text-decoration: none;\n    }\n    @media (max-width: 700px) {\n        body {\n            background-co…
PLAY RECAP *********************************************************************
localhost,                 : ok=1    changed=0    unreachable=0    failed=1`

##### ADDITIONAL INFORMATION

Procedure followed: []https://www.ansible.com/blog/easy-integration-using-ansible-tower-and-red-hat-insights

**Comment by ryanpetrello** [comment]
@bigtob,

The instructions you referenced are for integrating with Red Hat Ansible Tower.  If you need assistance integrating with a Red Hat service like Red Hat Insights, please reach out to your Red Hat support representative.

**Comment by bigtob** [comment]
@ryanpetrello 

Hi Ryan, I don't follow. The URL used for the Insights integration is presumably sourced from within the AWX code and has been set as "https://example.org/r/insights/v3/maintenance?ansible=true". If this integration isn't 'supported' from within AWX then why is an Insights credential type offered? 

I am happy to talk to my Red HAT SR for the correct steer, but as the issue doesn't originate from them I'm not sure what they would do to help...

**Comment by vishal01de** [comment]
Even I'm facing same problem,  is there anyways to fix it or file where i can change the url

**Comment by Bahu2016** [comment]
It worked for me.
```
$ docker exec -it awx_task /bin/bash
# vi venv/awx/lib/python3.6/site-packages/awx/settings/defaults.py
change: 
INSIGHTS_URL_BASE = "https://<.com>"
# exit
# docker restart awx_task

$ docker exec -it awx_web /bin/bash
# vi venv/awx/lib/python3.6/site-packages/awx/settings/defaults.py
change: 
INSIGHTS_URL_BASE = "https://<.com>"
# docker restart awx_web
```
