### ISSUE TITLE
Provide way to configure local timezone in AWX Task container

### ISSUE THREAD

**Issue by alexander-bauer** [ansible/awx#392]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI
 - Installer

##### SUMMARY
The AWX Task container has a different local time than my Foreman instance, to which it reports facts. Whenever facts are reported to Foreman, Foreman marks their timestamp as "four hours ago." This leaves those hosts appearing out-of-sync.

##### ENVIRONMENT
* AWX version: 1.0.0.524
* AWX install method: docker on linux
* Ansible version:  2.3.1.0
* Operating System: CentOS Linux 7

##### EXPECTED RESULTS

AWX Task container should either match host timezone, or be configurable.

**Comment by matburt** [comment]
You said it marks it as "four hours ago" but we have no baseline to compare the actual vs expected datetime.

Can you please tell us what the actual time delta is? Are time stored with a timezone or utc or do they include an offset? What is your local time relative to one of the items displayed? Can you provide a screen shot or api/response output? what is the time relative to the server hosting the docker container?

**Comment by alexander-bauer** [comment]
@matburt I just simultaneously ran `date` on the container, container host, and on the receiving Foreman instance. Both the container host and Foreman report the correct time in EDT (10:07, currently). The container itself reports the correct time in UTC (14:07).

I attached to the container and set the timezone, and that resolved the time offset issue in Foreman. I think the correct solution is for Foreman to accept timezone information. If it does so already, then the breakdown may be in the Ansible callback, but that's an upstream issue.

There may still be some potential timezone-selection as an AWX feature, but I'm not super convinced.

**Comment by alexander-bauer** [comment]
I've changed my Foreman master's timezone to be UTC, which has resolved the problem. There's some merit to this as standard practice across all infrastructure, but that's entirely another debate. I'm going to close this, because *my* issue is resolved, but it could be reopened if timezone-selection is a feature desired by anyone else.
