### ISSUE TITLE
Fatal Build Failed

### ISSUE THREAD

**Issue by zernoff21** [ansible/awx#3923]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Hello everyone! I was facing some issues during build.

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: n/a
* Ansible version:  2.8.0
* Operating System: n/a
* Web Browser: n/a

##### STEPS TO REPRODUCE

I commended out `dockerhub_base` in `inventory` file and started build.

##### EXPECTED RESULTS

Successful build.

##### ACTUAL RESULTS

I was constantly getting error:

`fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Error building awx_sdist_builder - code: 1, message: The command '/bin/sh -c ln -s /usr/bin/python36 /usr/bin/python3' returned a non-zero code: 1, logs: [u'Step 1/10 : FROM centos:7', u'\\n', u' ---> 9f38484d220f\\n', u'Step 2/10 : RUN yum install -y epel-release', u'\\n', u' ---> Using cache\\n', u' ---> a61370070ca5\\n', u'Step 3/10 : RUN yum install -y bzip2     gcc-c++     gettext     git     make     python36-setuptools', u'\\n', u' ---> Using cache\\n', u' ---> fc9917daac0f\\n', u'Step 4/10 : RUN curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -', u'\\n', u' ---> Using cache\\n', u' ---> ff2b0fde63ea\\n', u'Step 5/10 : RUN yum install -y nodejs', u'\\n', u' ---> Using cache\\n', u' ---> 54f5f026371d\\n', u'Step 6/10 : RUN npm set progress=false', u'\\n', u' ---> Using cache\\n', u' ---> cf1272e699ab\\n', u'Step 7/10 : RUN ln -s /usr/bin/python36 /usr/bin/python3', u'\\n', u' ---> Running in 38bc01d9b9dc\\n', u\"\\x1b[91mln: failed to create symbolic link '/usr/bin/python3': File exists\\n\\x1b[0m\", u'Removing intermediate container 38bc01d9b9dc\\n']"}`
##### ADDITIONAL INFORMATION

I removed ` RUN ln -s /usr/bin/python36 /usr/bin/python3'` from all files where it was present and build succeed.

**Comment by konkolorado** [comment]
This was fixed by #3640. If you want the fix you'll need to pull from that commit onward or wait until a new release gets cut.
