### ISSUE TITLE
Azure login icon not displayed

### ISSUE THREAD

**Issue by okelet** [ansible/awx#3924]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The Azure AD login icon is not displayed in login page, only a grey circle.

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: kubernetes (microk8s)
* Ansible version:  2.7.10
* Operating System: Ubuntu 18.04
* Web Browser: Firefox/Chrome

##### STEPS TO REPRODUCE

Configured Azure AD Login; the login works fine, but the icon in the login page is a grey circle, instead of an icon.

##### EXPECTED RESULTS

Show the Azure AD login icon.

##### ACTUAL RESULTS

Only a grey circle is displayed.

Screenshot here https://imgur.com/a/FAE3t6S

**Comment by sdktr** [comment]
We have the same issue, has been present since at least 2.1.0, I wasn't aware that there should be an icon but that makes sense:-)

**Comment by mabashian** [comment]
@sdktr are you also accessing the application through Chrome/FF on Ubuntu?

I'm not able to reproduce this with the latest AWX code through Chrome/FF on macOS High Sierra:

<img width="1680" alt="Screen Shot 2019-06-11 at 9 29 10 AM" src="https://user-images.githubusercontent.com/9889020/59276090-a1f23c00-8c2b-11e9-8e1b-65eac27b47ee.png">
<img width="1680" alt="Screen Shot 2019-06-11 at 9 28 12 AM" src="https://user-images.githubusercontent.com/9889020/59276091-a1f23c00-8c2b-11e9-84d8-6598843a2e06.png">

**Comment by okelet** [comment]
@mabashian I am using AWX 4.0 (and was using also 2.0) with the same issue. Installed with Kubernetes. Tried with Firefox and Chrome in Kubuntu 18.04, with the same result, only a grey circle. But my login screen is different, I don't have that angry peanut, but the AWX logo with wings (see screenshot here https://imgur.com/a/CZGuKMy)

**Comment by Klaas-** [comment]
I am having the same issue with a kubernetes install of AWX 6.0.0 and current firefox (68.0).

inspecting the element seems to show the same as in the working screenshots of @mabashian 
`<i class="fa ThirdPartySignOn-icon ThirdPartySignOn-icon--fontCustom icon-microsoft" ng-class="item.icon">`

**Comment by AdamMorris23** [comment]
I have the same issue in Windows 10 with Chrome and Microsoft Edge.  I see the same grey circle and the same element on inspection...  

Like Okelet I am using the official logos.  If I turn on github oauth2 as well I get the github logo, so it does appear to just be an issue with Microsoft Azure AD.

**Comment by mabashian** [comment]
@okelet @sdktr @AdamMorris23 @Klaas- I've got #4776 in the works to address this issue

**Comment by dsesami** [comment]
Opened up a session in a few different browser types (chrome, ff, edge) on windows. Looks like it functions correctly now.
