### ISSUE TITLE
"Bad file descriptor" when trying to lock file on NFS mount

### ISSUE THREAD

**Issue by patrikbeno** [ansible/awx#3926]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

File descriptor obtained using `os.open()` cannot be used in `fcntl.flock()` call when the file is on NFS mount.

https://github.com/ansible/awx/blob/4.0.0/awx/main/tasks.py#L1853

`fcntl.flock(os.open())` does not work on NFS mount.
`fcntl.flock(open())` does work, or at least does not fail.

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: kubernetes
* Ansible version:  ansible-2.8.0-1.el7.ans.noarch

##### STEPS TO REPRODUCE

Mount NFS folder on `/var/lib/awx/projects`

All jobs that try to create a project lock in this folder will fail with:

`awx/main/tasks.py", line 1865, in acquire_lock fcntl.flock(self.lock_fd, fcntl.LOCK_EX | fcntl.LOCK_NB) OSError: [Errno 9] Bad file descriptor`

Isolated testing:

```bash
$ bash -c "flock -xn lockfile ls -l lockfile"
=>OK

$ python3 -c 'import fcntl; import os; fcntl.flock(open("lockfile", "a"), fcntl.LOCK_EX | fcntl.LOCK_NB)'
=>OK

$ python3 -c 'import fcntl; import os; fcntl.flock(os.open("lockfile", os.O_RDONLY | os.O_CREAT), fcntl.LOCK_EX | fcntl.LOCK_NB)'
=> OSError: [Errno 9] Bad file descriptor
```

Disclaimer: Python is not my domain of expertise, I'm just a newbie hacking.

##### EXPECTED RESULTS

locking should work on NFS

##### ACTUAL RESULTS

Job fails because a file lock cannot be created on NFS folder

##### ADDITIONAL INFORMATION

That's all I got

**Comment by patrikbeno** [comment]
Related: #2195

**Comment by ryanpetrello** [comment]
Should be resolved by https://github.com/ansible/awx/pull/3928
