### ISSUE TITLE
gratuitous bold on notification template screen

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#3929]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When creating a notification template, the Use SSL/TLS options are randomly bold:

![Screenshot from 2019-05-20 14-32-16](https://user-images.githubusercontent.com/5208768/58043816-36c1b800-7b0c-11e9-9310-f54a62c00ea6.png)

Presumably a minor issue with the less/css.

##### ENVIRONMENT
* AWX version: current

**Comment by dsesami** [comment]
This appears to still be an issue, it is still bold. changing labels to needs_devel
cc @AlexSCorey

**Comment by dsesami** [comment]
this appears to be fixed now. thanks!
