### ISSUE TITLE
Survey multi-select option varies if options are selected then removed

### ISSUE THREAD

**Issue by ghost** [ansible/awx#393]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When a multi-select survey option is used in a job launch to set an option that is not required and has no default, the variable is undefined if no option is selected.  But, if an option is selected, then unselected, the variable is defined as empty (`[]`).

##### ENVIRONMENT
* AWX version: 1.0.0
* Ansible version:  2.3.2

##### STEPS TO REPRODUCE

* Create a job template and add a survey
* Add a Multiple Choice (Multiple Select) option
* Add selections,
* Leave default empty
* Uncheck 'Required'
* Run Template

##### EXPECTED RESULTS

The variable should be in the same state is no selections accepted at launch, whether there were some temporarily selected in the process of the completion of the survey.

##### ACTUAL RESULTS

The variable is undefined if no selections are made, and is defined as empty if any selection is made then removed prior to launch.

**Comment by jaredevantabor** [comment]
This is now fixed in devel.
