### ISSUE TITLE
Inventory Issue

### ISSUE THREAD

**Issue by AutomateIT1979** [ansible/awx#3938]
##### ISSUE TYPE
 - Bug Report
ERROR! No inventory was parsed, please check your configuration and options.
##### SUMMARY

I tried to create a dynamic inventory from OpenStack, unfortunately without success and I got the below error message :

**ERROR! No inventory was parsed, please check your configuration and options.**

##### ENVIRONMENT
* AWX version: <  AWX 4.0.0.0  >
* AWX install method:  docker on Linux,
* Ansible version:  2.7.9
* Operating System: CentOS Linux release 7.6.1810 (Core)
* Web Browser: FireFox - Chrome

##### STEPS TO REPRODUCE

deployed AWX and created OpenStack credential, then tried to generate the inventory

##### EXPECTED RESULTS

I'm expecting to collect all hosts from OpenStack

##### ACTUAL RESULTS

the collection fail with error message

##### ADDITIONAL INFORMATION

I'm attaching the output 
[inventory_update_45.txt](https://github.com/ansible/awx/files/3202552/inventory_update_45.txt)

**Comment by wenottingham** [comment]
`keystoneauth1.exceptions.http.Unauthorized: The username or password is wrong.
(HTTP 401)`

Check your config.

**Comment by AutomateIT1979** [comment]
@wenottingham 
Thank you for your reply. I installed OpenStack client and I created admin-openrc.sh file and I'm able to connect to OpenStack. would you please help me where shall I change/check the login and password in Ansible AWX

Thanking you in advance

**Comment by AlanCoding** [comment]
To triage the issue, we would like you to confirm whether it works with your parameters with `ansible-inventory` or `ansible-playbook` locally via the CLI.

**Comment by AutomateIT1979** [comment]
@AlanCoding 
Unfortunately, all the machines are on the cloud. the PING from Ansible machine to other hosts is working fine. but when I try to create the dynamic inventory I obtained the error message mentioned above, and to be honest I'm not sure where is the issue and how I can solve it
