### ISSUE TITLE
No job output

### ISSUE THREAD

**Issue by soniachan** [ansible/awx#3940]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
There is no job output in https://awx/api/v2/jobs/<job_id>/stdout/
Empty job events in https://awx/api/v2/jobs/<job_id>/job_events/
##### ENVIRONMENT
* AWX version: 1.0
* AWX install method: docker on linux
* Ansible version:  2.6.3
* Operating System:
* Web Browser: Google Chrome 74.0.3729.169 (Official Build) (64-bit)

##### STEPS TO REPRODUCE
- run any job

##### EXPECTED RESULTS

Be able to see job output

##### ACTUAL RESULTS

Empty job output

##### ADDITIONAL INFORMATION
- EC2 Instance type was upgraded in AWS, then when the instance restarts, there is no job output.
- cannot locate job_status in /var/lib/awx in awx_task container

```
$ ansible --version
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

I have tried to find job outputs in the dockers below but failed to find any..
```
$ sudo docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS
      NAMES
170805b09527        ansible/awx_task:1.0         "/tini -- /bin/sh -c "   8 months ago        Up 17 hours         8052/tcp
      awx_task
441bd23583fe        ansible/awx_web:1.0          "/tini -- /bin/sh -c "   8 months ago        Up 17 hours         0.0.0.0:80->8052/tcp
      awx_web
24235241ab64        memcached:alpine             "docker-entrypoint.sh"   8 months ago        Up 17 hours         11211/tcp
      memcached
075a0d7292ae        ansible/awx_rabbitmq:3.7.4   "docker-entrypoint.sh"   8 months ago        Up 17 hours         4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 25672/tcp   rabbitmq
35c6806d0cbc        postgres:9.6                 "docker-entrypoint.sh"   8 months ago        Up 19 hours         5432/tcp
      postgres
```

**Comment by soniachan** [comment]
issue is solved by running the following in awx_task docker

```
$ /usr/bin/awx-manage run_callback_receiver
```
then restart supervisor
```
$ supervisorctl -c /supervisor_task.conf restart all
```

**Comment by soniachan** [comment]
Issue started to happen again after some hours..
suspecting this relates to too many jobs are triggered at the same time

**Comment by ryanpetrello** [comment]
We've fixed a number of bugs related to stdout streaming since version 1.0 of AWX.  Please let us know if you're seeing the same problems on a modern version of AWX (the version you're running is nearly two years old).

**Comment by Throckmortra** [comment]
Seeing this issue on 9.1.1

**Comment by ryanpetrello** [comment]
@Throckmortra can you share the output of this command in the task container?

`$ supervisorctl -c /supervisor_task.conf status`

**Comment by Throckmortra** [comment]
```
awx-config-watcher                  RUNNING   pid 24862, uptime 3:55:00
tower-processes:callback-receiver   RUNNING   pid 24864, uptime 3:55:00
tower-processes:channels-worker     RUNNING   pid 24865, uptime 3:55:00
tower-processes:dispatcher          RUNNING   pid 24863, uptime 3:55:00
```

I actually managed to fix this by indenting line 
```
BROKER_URL = 'amqp://{}:{}@{}:{}/{}'.format(
```
in settings.py

**Comment by ryanpetrello** [comment]
Sounds like there was a syntax error in your settings, then.  That would definitely explain why events weren't being processed.

**Comment by Throckmortra** [comment]
my apologies then

**Comment by zmbutter** [comment]
We are having this problem today. Please let me know exactly what information you'd like to see.
