### ISSUE TITLE
DATABASE_PASSWORD value in <docker-compose-path>/environment.sh must be quoted

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/awx#3943]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The ```DATABASE_PASSWORD```value is currently not quoted in ```/etc/tower/conf.d/environment.sh``` mapped to ```<docker-compose-path>/environment.sh```.
An error occurs when the ```DATABASE_PASSWORD``` contains a character that can be interpreted by the shell inside the ```awx_web``` container, such as '('.

##### ENVIRONMENT
* AWX version: 4.0.0 (4.0.0-593-g75fe801ef)
* AWX install method: docker on linux
* Ansible version:  2.8.0
* Operating System: Ubuntu eoan/Debian buster

##### STEPS TO REPRODUCE
- set ```pg_password="password+("``` (for instance) in ```installer/inventory```
- build & start 4.0.0 (or any unstable tag beyond that)

##### EXPECTED RESULTS
No error

##### ACTUAL RESULTS

```
# docker logs -f awx_task
/etc/tower/conf.d/environment.sh: line 5: syntax error near unexpected token `('
/etc/tower/conf.d/environment.sh: line 5: `DATABASE_PASSWORD=password+('
```

##### WORKAROUND:
- stop the awx containers
- enclose DATABASE_PASSWORD value in quotes ```DATABASE_PASSWORD='password+('``` in ```<docker-compose-path>/environment.sh```.
- start the awx containers

This allows awx_task to start.

**Comment by ryanpetrello** [comment]
@Spredzy @shanemcd you have any thoughts on this?

**Comment by shanemcd** [comment]
ah, yep. ansible has a `| quote` filter we should use
