### ISSUE TITLE
Copy module, file not found

### ISSUE THREAD

**Issue by ayaseen** [ansible/awx#3946]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY
Copy module in playbook not works

##### ENVIRONMENT
* AWX version: 4
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2<
* Operating System: el7

##### STEPS TO REPRODUCE

Add a task in the playbook to copy a file from ansible awx controller into the remote machine.
Disable job isolation (if required)

##### EXPECTED RESULTS

File not found

"msg": "Could not find or access '/var/lib/awx/projects/_6__tenant/roles/rh/files/openstack.conf' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option",
    "exception": "Traceback (most recent call last):\n  File \"/var/lib/awx/venv/python3-ansible2.6.16-2152019/lib/python3.6/site-packages/ansible/plugins/action/copy.py\", line 442, in run\n    source = self._find_needle('files', source)\n  File \"/var/lib/awx/venv/python3-ansible2.6.16-2152019/lib/python3.6/site-packages/ansible/plugins/action/__init__.py\", line 1060, in _find_needle\n    return self._loader.path_dwim_relative_stack(path_stack, dirname, needle)\n  File \"/var/lib/awx/venv/python3-ansible2.6.16-2152019/lib/python3.6/site-packages/ansible/parsing/dataloader.py\", line 322, in path_dwim_relative_stack\n    raise AnsibleFileNotFound(file_name=source, paths=[to_text(p) for p in search])\nansible.errors.AnsibleFileNotFound: Could not find or access '/var/lib/awx/projects/_6__tenant/roles/rh/files/openstack.conf' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option\n",
    "_ansible_no_log": false,

##### ACTUAL RESULTS

The file must be copied into remote machine

**Comment by ghjm** [comment]
This looks like a bug in the playbook, not in AWX.
