### ISSUE TITLE
AWX 4.0.0.0 stopped showing job outputs

### ISSUE THREAD

**Issue by larrybg** [ansible/awx#3951]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX 4.0.0.0 running in the Docker containers. The database is installed on a separate server. New installation is about 1 month old. Stopped showing job outputs

##### ENVIRONMENT
* AWX version: 4.0.0.0
* AWX install method: docker on linux CentOS 7
* Ansible version:  2.7.9
* Operating System: CentOS
* Web Browser: Chrome, Safari

##### STEPS TO REPRODUCE

Execute the template, check job's output

##### EXPECTED RESULTS

Running job produces an output that should be shown in the UI output window

##### ACTUAL RESULTS

Nothing has shown

##### ADDITIONAL INFORMATION

<img width="1215" alt="Screen Shot 2019-05-24 at 12 42 12 PM" src="https://user-images.githubusercontent.com/20246246/58344167-f96a6c80-7e22-11e9-9c82-766a1f8c8abc.png">

<img width="626" alt="Screen Shot 2019-05-24 at 12 56 14 PM" src="https://user-images.githubusercontent.com/20246246/58344367-7b5a9580-7e23-11e9-93f6-4d608e1b5954.png">

**Comment by larrybg** [comment]
UPDATE: looks like it's a performance issue. I have left my browser opened on the job's page and suddenly the output starts loading in the log window...

**Comment by MathijsVanWilligen** [comment]
@larrybg, do you have fixed this issue?
My job output will be showing after 2 day's, i'm also running on AWX 4.0.0

**Comment by larrybg** [comment]
No, we didn’t. Our outputs showed up later. Turned out its a server
performance issue.

**Comment by ryanpetrello** [comment]
> looks like it's a performance issue

@larrybg,

Sounds like you've worked this out, and narrowed it down to a performance issue?  AWX can be fairly write-heavy with the database depending on your usage, sounds like there's some tuning needed here.

**Comment by larrybg** [comment]
I have to re-open this issue. We've lost job outputs again. No changes were made to the environment. Disk space is not an issue either.
