### ISSUE TITLE
AWX Ansible - Python requirement for endpoint nodes

### ISSUE THREAD

**Issue by kylecribbs** [ansible/awx#3954]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
running a command job with cat /etc/passwd requires python on the target node

##### ENVIRONMENT
* AWX version: 4.0
* AWX install method: docker on linux

##### STEPS TO REPRODUCE
In web interface select your host and click "Run Command" here you will choose command, and the args will be cat /etc/passwd. Choose your credentials. After clicking launch i get the following error:
```
SSH password: 
SUDO password[defaults to SSH password]: 
192.168.168.21 | FAILED! => {
    "changed": false, 
    "module_stderr": "Connection to 192.168.168.21 closed.\r\n", 
    "module_stdout": "/bin/sh: /usr/bin/python: No such file or directory\r\n", 
    "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", 
    "rc": 127
}

```

##### EXPECTED RESULTS
I expected the output of the passwd file. Instead the target node needs python on it?

##### ACTUAL RESULTS
Python error.

##### ADDITIONAL INFORMATION
I am assuming i am doing something wrong and the target node does not need python installed.. That would be strange instead of SSHing into the box and running the command needed

**Comment by kylecribbs** [comment]
I did find this [page](https://docs.ansible.com/ansible/latest/reference_appendices/faq.html) where it stated the python interpreter is required. I am a bit confused, why not have ansible spawn a subprocess to ssh into the box and run a bash command?

**Comment by ryanpetrello** [comment]
This is a dependency of Ansible itself.  From the link you referenced:

> While you can write Ansible modules in any language, most Ansible modules are written in Python, including the ones central to letting Ansible work.

> By default, Ansible assumes it can find a /usr/bin/python on your remote system that is either Python2, version 2.6 or higher or Python3, 3.5 or higher.

**Comment by kylecribbs** [comment]
@ryanpetrello I guess my real question is, how do I run a command or ping in AWX without a python dependency?

**Comment by ryanpetrello** [comment]
@kylecribbs if you want to use the `command` and `ping` modules _directly_, you don't.

https://docs.ansible.com/ansible/latest/modules/raw_module.html might be more what you're looking for.

If you want to use the `raw` module in AWX, you'll need to whitelist it (it's not enabled by default):

<img width="592" alt="image" src="https://user-images.githubusercontent.com/214912/58492364-c08e0880-813e-11e9-8adf-e48e93af07f7.png">

**Comment by kylecribbs** [comment]
@ryanpetrello thanks, just curious why Raw is not whitelisted by default?
