### ISSUE TITLE
Remove OAuth 2 Implicit grant type

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/awx#3957]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
now that browsers have universally adopted CORS, using the `implicit` grant type for obtaining OAuth 2 tokens is not recommended.  We should remove this grant type as an option for Applications.  
https://oauth.net/2/grant-types/implicit/

The RFC has always advocated for using the Authorization code grant type over the implicit grant type anyways since the implicit grant type is less secure (it returns the token value in the redirect URL)

Things to do:
* remove grant type from application model
* remove from awx docs
* update function tests
* update e2e tests (awx/ui/test/e2e/objects/applications.js)

**Comment by Spredzy** [comment]
`ansible/tower-qa` PR that goes with this: https://github.com/ansible/tower-qa/pull/3467
