### ISSUE TITLE
Can't authenticate to Azure with AWX to create Resource Group

### ISSUE THREAD

**Issue by jedelblu** [ansible/awx#3960]
##### SUMMARY
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "No handlers could be found for logger \"msrestazure.azure_active_directory\"\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1559074172.33-168348615981483/AnsiballZ_azure_rm_resourcegroup.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1559074172.33-168348615981483/AnsiballZ_azure_rm_resourcegroup.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1559074172.33-168348615981483/AnsiballZ_azure_rm_resourcegroup.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_PnKfxJ/__main__.py\", line 256, in <module>\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_PnKfxJ/__main__.py\", line 252, in main\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_PnKfxJ/__main__.py\", line 136, in __init__…

##### ENVIRONMENT
* AWX version: AWX 4.0.0.0 
* AWX install method:  docker on linux
* Ansible version:  Ansible 2.7.9
* Operating System: Red hat 7.6
* Web Browser: Chrome

##### STEPS TO REPRODUCE
1. just running a template.

**Comment by jedelblu** [comment]
Thanks.

**Comment by ryanpetrello** [comment]
@jedelblu,

This looks like a bug in the ansible module itself that you're using.

Please post the _entire_ traceback (everything truncated after `in init…`)

**Comment by jedelblu** [comment]
First off Thanks.
Here is the json error
{
    "_ansible_parsed": false,
    "_ansible_no_log": false,
    "module_stderr": "No handlers could be found for logger \"msrestazure.azure_active_directory\"\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1559074172.33-168348615981483/AnsiballZ_azure_rm_resourcegroup.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1559074172.33-168348615981483/AnsiballZ_azure_rm_resourcegroup.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1559074172.33-168348615981483/AnsiballZ_azure_rm_resourcegroup.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_PnKfxJ/__main__.py\", line 256, in <module>\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_PnKfxJ/__main__.py\", line 252, in main\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_PnKfxJ/__main__.py\", line 136, in __init__\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_PnKfxJ/ansible_azure_rm_resourcegroup_payload.zip/ansible/module_utils/azure_rm_common.py\", line 308, in __init__\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_PnKfxJ/__main__.py\", line 150, in exec_module\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/azure/mgmt/resource/resources/v2017_05_10/operations/resource_groups_operations.py\", line 261, in get\n    'resourceGroupName': self._serialize.url(\"resource_group_name\", resource_group_name, 'str', max_length=90, min_length=1, pattern=r'^[-\\w\\._\\(\\)]+$'),\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/msrest/serialization.py\", line 488, in url\n    data = self.validate(data, name, required=True, **kwargs)\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/msrest/serialization.py\", line 568, in validate\n    raise ValidationError(key, name, value)\nmsrest.exceptions.ValidationError: Parameter 'resource_group_name' must conform to the following pattern: '^[-\\\\w\\\\._\\\\(\\\\)]+$'.\n",
    "changed": false,
    "module_stdout": "",
    "rc": 1,
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
}

**Comment by jedelblu** [comment]
Does that help?

**Comment by ryanpetrello** [comment]
```
msrest.exceptions.ValidationError: Parameter 'resource_group_name' must conform to the following pattern: '^[-\\w\\.\\(\\)]+$'.\n
```

Are you specifying `resource_group` or `resource_group_name` in your playbook, or creating a named group using `azure_rm_resourcegroup`?  Based on this error, it sounds like you're using an invalid character.

I'm closing this, because it doesn't seem like an issue w/ AWX to me.

**Comment by jedelblu** [comment]
Lets me show you my playbook. Please don' close the ticket. 
---
- name: Create Azure RG
  hosts: localhost
  connection: local

  tasks:
    - name: Build RG
      azure_rm_resourcegroup:
        name: Resource Group
        cloud_environment: AzureCloud
        location: westus
        tags:
          testing: testing
          delete: never

**Comment by ryanpetrello** [comment]
@jedelblu 

As I said, this isn't an AWX issue.  According to what the `azure_rm_resourcegroup ` group considers "valid", your resource group name has an invalid character (a space).  Remove the space from `Resource Group`:

```python
>>> x = re.compile('^[-\\w\\.\\(\\)]+$')
>>> x.match('testing123')
<_sre.SRE_Match object at 0x7f5707fed3d8>
>>> x.match('testing 123') is None
```

**Comment by jedelblu** [comment]
Thanks, Ryan you were correct the space in the Name fixed the issue. you rock!
