### ISSUE TITLE
Database trim / cleanup

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#3962]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Right now it seems that old data are kept forever in database - that leads to database with tens to hundreds of GB of data from job executions.

There should be some way to clean it up, for example delete data older than N days, etc.

**Comment by ryanpetrello** [comment]
Hey Petr,

This is probably what you want:

https://docs.ansible.com/ansible-tower/latest/html/administration/management_jobs.html#removing-old-job-history
