### ISSUE TITLE
Upgrade pip and setuptools in requirements

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#3968]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
This needs to be done, and the sooner the better

https://github.com/ansible/awx/blob/34c3aaee3d96ed5286924ccf4c91e42a5bc055ad/requirements/requirements.in#L51-L52

https://github.com/ansible/awx/blob/34c3aaee3d96ed5286924ccf4c91e42a5bc055ad/requirements/requirements_ansible.in#L53-L54

**Comment by AlanCoding** [comment]
Adding @shanemcd to notification list for this issue.

status update: In https://github.com/ansible/awx/pull/4106, an intermediate upgrade to `pip==18.1` was attempted, but that was also reverted.

**Comment by wenottingham** [comment]
this looks like it landed

**Comment by elyezer** [comment]
This has been around for quite some time and no issues on installing or upgrading related to the pip and setuptools upgrade has been raised.

I've done a recent install (last Friday) and no issues where found.

With that said we can consider this as being verified.
