### ISSUE TITLE
Awx code base integration with oracle db

### ISSUE THREAD

**Issue by rageshpillai** [ansible/awx#3969]
What all files we need to change for using oracle as backend for the existing awx code base.
We have a requirement to use oracle as backend for the awx application

**Comment by ryanpetrello** [comment]
This issue tracker is for tracking enhancements and bugs in AWX itself (and we don't intend to support Oracle DB as a backend for AWX at this time, as noted in the last ticket you filed about this: https://github.com/ansible/awx/issues/3949).

AWX itself makes use of the Django ORM, which *does* support Oracle DB 12.1 and higher, so you _could_ hypothetically hack something together:

https://docs.djangoproject.com/en/2.2/ref/databases/#oracle-notes

That said, there are a [notable](https://github.com/ansible/django-jsonbfield) [number](https://github.com/ansible/awx/blob/devel/awx/main/utils/pglock.py) [of](https://github.com/ansible/awx/blob/devel/awx/main/db/profiled_pg/base.py#L110) [features](https://github.com/ansible/awx/blob/13ff5ffdf2ce17c0bf2f6a97f7fafc2f3123e407/awx/main/models/unified_jobs.py#L1027) in AWX that are implemented using _specific_ database functionality of Postgres, so you'd have to completely reimplement those using similar functionality (if available) in Oracle DB.  It is _extremely_ unlikely that we would be willing to merge these type of changes back into AWX, so you'd be carrying your own patches long-term to support this.

If you have additional questions about AWX itself, please try out the AWX mailing list (https://www.ansible.com/products/awx-project) or our IRC room on freenode (`#ansible-awx`)
