### ISSUE TITLE
Update awx_task on hub.docker.com

### ISSUE THREAD

**Issue by tadeas22** [ansible/awx#3971]
##### COMPONENT NAME
 - Installer

##### SUMMARY
Please can you update version of ansible to 2.8 (current is 2.7.9) in this two docker images?
https://hub.docker.com/r/ansible/awx_task
https://hub.docker.com/r/ansible/awx_web

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method:  docker on linux
* Ansible version:  2.7.9

##### EXPECTED RESULTS

Ansible 2.8

##### ACTUAL RESULTS

Ansible 2.7.9

**Comment by ryanpetrello** [comment]
We'll do this in the next major release of Ansible AWX.
