### ISSUE TITLE
update puppeteer dev / unit test dependency

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#3972]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
This drives our unit tests so its good to keep this _reasonably_ up to date. As of right now, updating this to a more recent version (`1.8.0` -> `1.16.0`) results in errors when running the tests in CI.

It's likely this may come down to just needing a few more libs in our CI container, or perhaps updating a complementary dependency to a newer version in order to make the tests work. At any rate, we'll need to spend some time digging for the root cause to update this dependency.

##### STEPS TO REPRODUCE
- clone the awx repo
- build the test container:
```
make docker-compose-build
make docker-compose-test
```
- (from within the test container) update puppeteer and run the tests:
```
cd /awx_devel
make clean-ui
npm --prefix=awx/ui uninstall --save-dev puppeteer
npm --prefix=awx/ui install --save-dev puppeteer@1.16.0
make ui-devel
make ui-test-ci
```

##### EXPECTED RESULTS
The tests run and pass.

##### ACTUAL RESULTS
```
29 05 2019 19:20:18.182:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
29 05 2019 19:20:18.184:INFO [launcher]: Launching browser chromeHeadless with unlimited concurrency
29 05 2019 19:20:18.288:INFO [launcher]: Starting browser Chrome
29 05 2019 19:20:18.909:INFO [HeadlessChrome 76.0.3786 (Linux 0.0.0)]: Connected on socket _0M3DlK5AyPgWczfAAAA with id 54283728
29 05 2019 19:20:28.911:WARN [HeadlessChrome 76.0.3786 (Linux 0.0.0)]: Disconnected (1 times), because no message in 10000 ms.
```

**Comment by wenottingham** [comment]
@jakemcdermott is this still a thing that may happen soon?

**Comment by ryanpetrello** [comment]
Spoke w/ @jakemcdermott, not a priority in the near term.

**Comment by jakemcdermott** [comment]
Closing - the related code is no longer around
