### ISSUE TITLE
Credential Plugins don't work with adhoc `ansible -u`

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#3973]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Run an adhoc command that specifies a credential with a username pulled from e.g., HashiCorp Vault.  It **does** work for a Job Template:

<img width="268" alt="image" src="https://user-images.githubusercontent.com/214912/58642049-78035600-82ca-11e9-9d3d-85e3df293870.png">

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/214912/58642308-15f72080-82cb-11e9-9ec6-c8b8a1669f6b.png">

...but it doesn't work for adhoc:

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/214912/58642260-f9f37f00-82ca-11e9-973b-e8803a82e7f5.png">

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: any
* Ansible version:  any

**Comment by ryanpetrello** [comment]
Should be resolved when this merges:

https://github.com/ansible/awx/pull/3413/files#diff-9d4ea1dd908b35fb92eaede4bd10bb46R2232

**Comment by Spredzy** [comment]
Verified
