### ISSUE TITLE
Highlight selected focus items

### ISSUE THREAD

**Issue by kaovilai** [ansible/awx#3975]
##### ISSUE TYPE
 - Ansible Tower UI should
    - highlight the selected items when using tab key

##### SUMMARY

Currently it is unclear especially for dropdown menus that it is being selected when user is using tab to navigate the forms.
For example, in the `Resources > Templates > New Job Template`
 - When name text input field is selected
    - you can see blinking cursor which is a good visual feedback
 - When Job Type is selected
    - There are no visible highlights around the field

##### PC Info
 - Browser: Google Chrome 74.0.3729.169 (Official Build) (64-bit)
 - OS: macOS Mojave Version 10.14.5

**Comment by mabashian** [comment]
The UI was completely rewritten in 2020 and I believe this was addressed.  Please re-open if you still have concerns about a recent version of AWX.
