### ISSUE TITLE
Awkward column width in Select Application Wizard

### ISSUE THREAD

**Issue by tvo318** [ansible/awx#3977]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Left column for name of application looks too narrow/squished:

![image](https://user-images.githubusercontent.com/7514801/58681703-cba58c00-832a-11e9-87d5-e6ef94e560cd.png)

##### ENVIRONMENT
* Tower version: 3.5.0 ([ec2-54-209-180-137.compute-1.amazonaws.com](https://ec2-54-209-180-137.compute-1.amazonaws.com))
* Tower install method: yolo without any test runs
* Ansible version: 2.8.0.dev0
* Operating System: Mac Mojave 10.14.4
* Web Browser: Chrome Version 74.0.3729.169 (Official Build) (64-bit)

##### STEPS TO REPRODUCE

1. Go to **Users** from the left navigation pane.
2. Select YOUR user to access its details page.
3. Click the **Tokens** tab.
4. Click **[+]** to add a token for your user.
5. Click the magnifying glass in the **Application** field to open a window that allows you to select an application .

This is the Select Application Wizard that has the narrow width **Name** column.

##### EXPECTED RESULTS

I expected the Select Application Wizard would have a wide enough **Name** column to read an entire word at least.

##### ACTUAL RESULTS

See screen capture above.

##### ADDITIONAL INFORMATION

See screen capture above.

**Comment by dsesami** [comment]
Created applications with both short and long names. Modal now renders correctly and responds well to window resizes.
