### ISSUE TITLE
How to get access to awx google group

### ISSUE THREAD

**Issue by rageshpillai** [ansible/awx#3978]
I am not able to access the ur google group
https://groups.google.com/forum/#!forum/awx-project

Getting the below warning
"This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the owner of the group and ask them to give you access"

Whom should i contact to get access to this group?

**Comment by ryanpetrello** [comment]
@matburt @wenottingham,

I'm seeing the same in an incognito window.  Do you think this is some sort of issue w/ Google atm, or do we have something misconfigured permission-wise?

<img width="593" alt="image" src="https://user-images.githubusercontent.com/214912/58706373-de967b80-837f-11e9-8cb6-d27f55c450d7.png">

When I view as a logged in group member:

<img width="693" alt="image" src="https://user-images.githubusercontent.com/214912/58706431-0ab1fc80-8380-11e9-9630-fb409922e486.png">

**Comment by ryanpetrello** [comment]
@rageshpillai we've changed the group permissions around a bit and I'm able to view the group as an anonymous user - mind giving it a try now?
