### ISSUE TITLE
Version-specific documentation links broken 

### ISSUE THREAD

**Issue by razorinc** [ansible/awx#399]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
 - UI
##### SUMMARY
When clicking the button Key from Search you'll get a series of informations, the link that send to Ansible Tower is not aligned with the AWX version.

##### ENVIRONMENT

* Docker on Linux
* All browsers

##### STEPS TO REPRODUCE

Within search box, pressing the button Key you will be presented with options and with a link that redirect you to Ansible Tower documentation.

##### EXPECTED RESULTS

http://docs.ansible.com/ansible-tower/latest/html/userguide/search_sort.html 

##### ACTUAL RESULTS

http://docs.ansible.com/ansible-tower/1.0.1.0/html/userguide/search_sort.html

##### ADDITIONAL INFORMATION

Even tho is correct that AWX is at release 1.0.1.0 the documentation is not correctly aligned.

**Comment by wenottingham** [comment]
Tweaked title... this likely surfaces in more places.

**Comment by agaffney** [comment]
I noticed this, as well.

**Comment by shanemcd** [comment]
Assuming this has been resolved in the new UI. Please reopen if I'm wrong.
