### ISSUE TITLE
Allow users with Update role on Inventory to add/remove hosts

### ISSUE THREAD

**Issue by falcon78921** [ansible/awx#3990]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

- UI

Ansible Tower currently does not have the ability to allow a Normal User to add/remove hosts from an Inventory (unless you're a Tower admin or admin of an Inventory). Per a customer's request, they would like to be able to give a normal user the **Update** role and then have the normal user add/remove hosts from the Inventory (without giving them full admin rights or full rights on the Inventory).

**Comment by wenottingham** [comment]
What purpose does the ability to add hosts without admin access serve?

**Comment by rwagnergit** [comment]
Bill - exactly that.  It lets a user who is not an admin add hosts, which is something we would like users to be able to do.  If they have admin access, they can do more than just add hosts (e.g., delete the inventory, grant privs on the inventory to others).

I can provide the whole feature request I sent to Red Hat if you'd like.

**Comment by wenottingham** [comment]
I think that would have to be a new role; we can't logically piggyback on `use` here.

**Comment by wenottingham** [comment]
Functionally, all of our objects generally don't have 'partial' edit access in this way - if you have the ability to change a resource ,you can delete it.

**Comment by rwagnergit** [comment]
Thanks Bill.  Just to clarify, I'm not asking for "Use" to be extended, but rather "Update" to be extended, which seems more logical.  The "Update" role currently allows a user to update the hosts in an inventory from an inventory list in SCM.  I'm just asking that this role be extended to allow users to update the hosts in an inventory *from within Tower*.  In other words, allow a user to add/remove hosts to/from an inventory from within Tower (and using Tower's REST API), rather than forcing them to update a file in SCM, commit it, and refresh it in Tower.

**Comment by wenottingham** [comment]
It's still not something we can do without changing the semantics of security of the inventory works overall - it changes the option from "can only pull inventory from a third-party source" (which in most cases they can't affect directly) to "can add anything".

**Comment by rwagnergit** [comment]
Understood.  To provide an illustration of why I'm seeking this Feature, here's more context from the original ER I opened w/ Red Hat:

To illustrate our need for this use case, we are a hosting provider, and we use Tower to provision hosts before delivery to our customers.  When a contract is signed, a set of hosts will be provisioned for the customer, and each application team is responsible for provisioning their portion of the software stack on the hosts (e.g., databases on some hosts, web on others, compute on others, etc).  As each team prepares to provision their subset of hosts, they need the ability to add their hosts to the inventory used by the JTs they run.  Once they are done provisioning, there is no longer any need to maintain these hosts in the inventory, so they are removed.  In other words, we don't maintain a "site-wide" inventory that's relatively static; our inventories are much smaller and very fluid.  Ideally, our teams would be able to add/remove their hosts to/from inventories without being inventory admins.

You are certainly correct - we can mitigate (and are mitigating) this by granting Admin on inventory to these users, but this increases risk and would be better supported if Update allowed users to add/remove hosts from inventories.  Not a showstopper, but this is a Feature idea, after all.

**Comment by lijok** [comment]
> Understood. To provide an illustration of why I'm seeking this Feature, here's more context from the original ER I opened w/ Red Hat:
> 
> To illustrate our need for this use case, we are a hosting provider, and we use Tower to provision hosts before delivery to our customers. When a contract is signed, a set of hosts will be provisioned for the customer, and each application team is responsible for provisioning their portion of the software stack on the hosts (e.g., databases on some hosts, web on others, compute on others, etc). As each team prepares to provision their subset of hosts, they need the ability to add their hosts to the inventory used by the JTs they run. Once they are done provisioning, there is no longer any need to maintain these hosts in the inventory, so they are removed. In other words, we don't maintain a "site-wide" inventory that's relatively static; our inventories are much smaller and very fluid. Ideally, our teams would be able to add/remove their hosts to/from inventories without being inventory admins.
> 
> You are certainly correct - we can mitigate (and are mitigating) this by granting Admin on inventory to these users, but this increases risk and would be better supported if Update allowed users to add/remove hosts from inventories. Not a showstopper, but this is a Feature idea, after all.

similar usecase here
provisioning devices that we add with an inventory script, once provisioned we send them off and remove them from inventory, sometimes some hosts need to be re-added/removed manually by non-admin operators

**Comment by falcon78921** [comment]
Moved to https://github.com/ansible/awx/issues/7637
