### ISSUE TITLE
RBAC - New role for creating smart inventories

### ISSUE THREAD

**Issue by OndraLipo** [ansible/awx#3995]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
We need an option to give permission to team or user to be able to create a smart inventory from already existing inventory.

Nowadays we can assign only Inventory Admin role to the whole Organization, which gives permission to add/edit/delete all inventories in that Organization and we need users/teams to be able to add smart inventory, but not edit/delete current ones.

##### Info
AWX version: 4.0.0

**Comment by wenottingham** [comment]
I'm not sure this is practical for just smart inventories; if we were to add a role that could only create and manage new inventories, it would likely handle both types.

**Comment by OndraLipo** [comment]
@wenottingham I agree that both types makes more sense ;-). I also discovered the same issue with projects.

**Comment by OndraLipo** [comment]
Same issue with workflow templates, why only Organization admins can create and copy the workflow template?

**Comment by liborburda** [comment]
Bump.
I have similar problem, I need to give user "create job template" permission, without permission to see other job templates in organization.

The only way is to give him "Organization admin" rights. Same problem with workflow templates, projects... 

Or is there any other way how to do that?

**Comment by Sergiodcm00** [comment]
I think its interesting to have a role for only admin smart inventory. 
You can avoid users modify "master inventory" (for example when inventory comes from git) but you want users can create smart inventory from the "master inventory".

**Comment by OndraLipo** [comment]
Is there any update on this issue? SMART inventories are a must these days, so it is bit of a shame, that it's not possible for regular users in AWX/Tower. A recommendation for developers: take a look on other automation tools and theirs RBAC.

**Comment by TheRealHaoLiu** [comment]
Smart inventories has been deprecated in favor of constructed inventory

Please check out https://github.com/ansible/awx/pull/13303
