### ISSUE TITLE
Support RHEL 8 podman in installer

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#3998]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The build/install playbooks do not run on RHEL 8 out of the box in a way that works with podman.

**Comment by ephracis** [comment]
Would very much want this. I have a use case where we need to run AWX on a single host and having to deploy Kubernetes or OpenShift is really overkill. We want to move this from RHEL 7 to RHEL 8 but the lack of Docker means there is really now way to deploy AWX.

How would one even proceed to deploy this with Podman? As far as I can tell there is no way to make containers talk to each other unless one uses host networking or a pod, but then there will be a port conflict between `awx_web` and `awx_tasks`.

**Comment by ablecable** [comment]
I'm working for a municipality in the Netherlands and we also want to use AWX with RHEL 8 and podman.

**Comment by LukeShortCloud** [comment]
It would be a lot easier to implement if we got the [podman_container module](https://github.com/ansible/ansible/issues/46362#issuecomment-540734152) upstreamed. :-)

**Comment by cfelder** [comment]
It is obviously better to fix this in awx directly but there has already been some progress in a different project. I created a pull request ikke-t/awx_pod#1 for this project to support awx 9.1.1.

**Comment by alexhaydock** [comment]
I would have loved to see this but I suppose this request is redundant now that the AWX Operator is the preferred way to install AWX as of v18+

**Comment by ephracis** [comment]
That’s too bad. A lot of us are not running OpenShift.

**Comment by wenottingham** [comment]
Correct, this is now redundant.

**Comment by JuddTracy-DAS** [comment]
So does this mean that Kubernetes is going to be the only official way to install AWX going forward?

**Comment by wenottingham** [comment]
There is kubernetes, and there is the development environment based on docker-compose (not for production). More info here: https://groups.google.com/g/awx-project/c/47MjWSUQaOc/m/En0NrUiqAAAJ
