### ISSUE TITLE
Add help text popovers to SSL and TLS options in the notification section

### ISSUE THREAD

**Issue by ghost** [ansible/awx#3999]
##### ISSUE TYPE

- UI text
- Documentation

##### SUMMARY

In the notification section of AWX, there are two options:

- Use SSL
- Use TLS

I could find nowhere in the UI or documentation where this is accurately described. After reading the source code, I realized this is actually just passed to the Django library, where there is (some) documentation:

- https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-EMAIL_USE_SSL
- https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-EMAIL_USE_TLS

It seems like "Use SSL" is for using what many people call SMTPS on port 465 and appears to be a still-supported but deprecated standard.

On the other hand, it seems like "Use TLS" refers to using STARTTLS on the SMTP submission port 587.

Supporting these options is perfectly fine but some better explanation of what they mean, both in the UI and in the relevant documentation, would be very helpful and prevent confusion.

**Comment by john-westcott-iv** [comment]
Thanks for opening this issue. The help text now references the docs so I will close this issue:
![image](https://user-images.githubusercontent.com/32551173/229899097-67655a82-d10f-4b6b-a7e1-63dd8af496ed.png)
