### ISSUE TITLE
ERROR! Unexpected Exception, this is probably a bug: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by orgito** [ansible/awx#400]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
After upgrading from 1.0.561 I started getting this error running any of my job templates:

`ERROR! Unexpected Exception, this is probably a bug: 'ascii' codec can't decode byte 0xc3 in position 1551: ordinal not in range(128)`

I tried to upgrade from every new tag since 1.0.0.588 with the same results

##### ENVIRONMENT
* AWX version: 1.0.1.8
* AWX install method: docker on linux (official builds)
* Ansible version:  2.4.0.0
* Operating System: Centos 7.4
* Web Browser: Chrome 60

##### STEPS TO REPRODUCE

1. Upgrade AWX
2. Run a job template

##### EXPECTED RESULTS

The job template should run as before the upgrade

##### ACTUAL RESULTS

The playbook fails with the error message:

`ERROR! Unexpected Exception, this is probably a bug: 'ascii' codec can't decode byte 0xc3 in position 1382: ordinal not in range(128)
`

The position varies from one template to another

##### ADDITIONAL INFORMATION

debug output:
`
Identity added: /tmp/awx_427_Qd0YLs/credential_2 (/tmp/awx_427_Qd0YLs/credential_2)
2
ansible-playbook 2.4.0.0
3
  config file = /etc/ansible/ansible.cfg
4
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
5
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
6
  executable location = /usr/bin/ansible-playbook
7
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
8
Using /etc/ansible/ansible.cfg as config file
9
ERROR! Unexpected Exception, this is probably a bug: 'ascii' codec can't decode byte 0xc3 in position 1382: ordinal not in range(128)
10
the full traceback was:
12
Traceback (most recent call last):
13
  File "/usr/bin/ansible-playbook", line 106, in <module>
14
    exit_code = cli.run()
15
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 104, in run
16
    loader, inventory, variable_manager = self._play_prereqs(self.options)
17
  File "/usr/lib/python2.7/site-packages/ansible/cli/__init__.py", line 784, in _play_prereqs
18
    inventory = InventoryManager(loader=loader, sources=options.inventory)
19
  File "/usr/lib/python2.7/site-packages/ansible/inventory/manager.py", line 144, in __init__
20
    self.parse_sources()
21
  File "/usr/lib/python2.7/site-packages/ansible/inventory/manager.py", line 205, in parse_sources
22
    parse = self.parse_source(source, cache=cache)
23
  File "/usr/lib/python2.7/site-packages/ansible/inventory/manager.py", line 280, in parse_source
24
    display.warning('\n* Failed to parse %s with %s plugin: %s' % (to_native(fail['src']), fail['plugin'], to_native(fail['exc'])))
25
  File "/usr/lib/python2.7/site-packages/ansible/utils/display.py", line 220, in warning
26
    self.display(new_msg, color=C.COLOR_WARN, stderr=True)
27
  File "/usr/lib/python2.7/site-packages/ansible/utils/display.py", line 114, in display
28
    msg = stringc(msg, color)
29
  File "/usr/lib/python2.7/site-packages/ansible/utils/color.py", line 93, in stringc
30
    return u"\n".join([u"\033[%sm%s\033" % (color_code, t) for t in text.split(u'\n')])
31
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1382: ordinal not in range(128)
`

**Comment by AlanCoding** [comment]
Do you have any unicode characters in your job template name, extra_vars, or any other fields?

**Comment by orgito** [comment]
No. To make sure I created a new template with the playbook below:

 ```yaml
---
- hosts: all
  gather_facts: no

  tasks:
  - debug: var=inventory_hostname
```

Ran it against an inventory containing only localhost with empty credentials, no extra vars. Got that error:

`ERROR! Unexpected Exception, this is probably a bug: 'ascii' codec can't decode byte 0xc3 in position 1551: ordinal not in range(128)`

It appears the byte is always 0xc3.

**Comment by orgito** [comment]
Maybe I'm not upgrading the right way. Here the steps I execute:

1. git pull
2. stop all containers
3. remove all containers and images
4. run ansible-playbook -i inventory install.yml
5. start all containers

Since I don't delete the pgdocker folder my data is preserved.

I never see the "AWX is Upgrading" message on the UI though. I just assume that the upgrade is really fast or that no data migration was necessary.

**Comment by jangsutsr** [comment]
Could not replicate via devel environment. Probably an installer issue.

**Comment by matburt** [comment]
I'm having trouble replicating this too, it actually looks like it could be a problem in ansible itself ... were you using ansible 2.3 before and are now on 2.4?

**Comment by orgito** [comment]
On the host machine where I run the installer I use ansible 2.3.2. But the ansible on awx_task container is 2.4.0 for both 1.0.0-561 and 1.0.1.8.

I installed aswx 1.0.0-561 using the official docker images. Add inventories, template jobs, etc.

Every time I tried to upgrade to another version I get this error when trying to run any template job. Luckly I keep a snapshot of the working state so I can revert back.

**Comment by matburt** [comment]
I reckon we should wait and see what ansible 2.4.1 looks like for you

**Comment by orgito** [comment]
Update: I generated the images for 1.0.1.33 using the nightly builds rpms for ansible (2.4.1.0-0.3.rc1) and got the same error.

**Comment by orgito** [comment]
Looks like the problem is not restricted to updating awx. I just installed a new server with the latest official docker image (1.0.1.35) and received the same error even when i run the out of the box demo template.

**Comment by matburt** [comment]
I really think this is coming from ansible itself... if downgrading to 2.3.X makes the problem go away then we should try to develop a playbook that triggers the issue from ansible so we can take this upstream.

**Comment by orgito** [comment]
I finally figured out the problem.

 I have `*_proxy` variables set on the inventory file for the installer. The awxrest.py inventory script issues a request to the local docker container using the url **http://awxweb:8052**. Since the requests module uses the proxy environment variables it tries to use my proxy to reach the local web server. The resulting error message from the proxy contains the invalid characters.

As a workaround a just added `awxweb` to the `no_proxy` variable. But I would suggest adding `proxies={'https': None, 'http': None}` to any request to the local web server on awxrest.py or any other script. Or force awxweb (and any other local urls that might be used) to be part of the no_proxy environment variable when *_proxy is set.
