### ISSUE TITLE
Loosen uniqueness on job templates

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#4008]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

```class JobTemplate(UnifiedJobTemplate, JobOptions, SurveyJobTemplateMixin, ResourceMixin, CustomVirtualEnvMixin, RelatedJobsMixin):
    '''
    A job template is a reusable job definition for applying a project (with
    playbook) to an inventory source with a given credential.
    '''
    FIELDS_TO_PRESERVE_AT_COPY = [
        'labels', 'instance_groups', 'credentials', 'survey_spec'
    ]
    FIELDS_TO_DISCARD_AT_COPY = ['vault_credential', 'credential']
    SOFT_UNIQUE_TOGETHER = [('polymorphic_ctype', 'name')]
```
Ideally, it would be unique across an org (or a project?)

**Comment by AlanCoding** [comment]
Let's do this with the work item from https://github.com/ansible/awx/issues/282, where the organization field will be added to the JT.

**Comment by wenottingham** [comment]
Caveat: if relaxing this changes the `named_url` field, we may need a loud release note.

**Comment by wenottingham** [comment]
Flipping back to needs_devel as #4338 was closed.

**Comment by ryanpetrello** [comment]
@AlanCoding is there actually any tangible work here besides "merge https://github.com/ansible/awx/issues/3903" ?

**Comment by AlanCoding** [comment]
No other work AFAIK. Recap of status:

 - in JT.organization work, uniqueness is loosened from `(name,)` to `(organization, name)`
 - in that PR, named URL grows an additional JT-specific shim to support old URLs
 - even so, we would have to yell about it loudly in release notes

**Comment by kdelee** [comment]
@tvo318 this is related to https://github.com/ansible/awx/issues/3903

I have some notes there about how this is impacted

> This has the consequence that the “named url” for the job template is now officially /api/v2/job_templates/MyJobTemplate++MyOrganization/ . However, for backwards compatibility the deprecated /api/v2/job_templates/MyJobTemplate will still work for Tower 3.7.
