### ISSUE TITLE
Insights Job counts do not reflect accurate Job counts

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/awx#4014]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The insights `job_counts.json' are not being updated properly due to a default order_by("id") on the UnifiedJob model, which django's ORM interprets as "group_by id".  We instead want to group by "status" here.    

```
In [7]: dict(UnifiedJob.objects.values_list('status').annotate(Count('status')).order_by('id'))
Out[7]: {'failed': 1, 'successful': 1}

In [6]: connection.queries
Out[6]: 
[{'sql': 'SELECT "main_unifiedjob"."status", COUNT("main_unifiedjob"."status") AS "status__count" FROM "main_unifiedjob" GROUP BY "main_unifiedjob"."id" ORDER BY "main_unifiedjob"."id" ASC',
  'time': '0.005'}]

```

##### STEPS TO REPRODUCE

1. Run multiple jobs
2. run awx-manage gather_analytics
3. tar xfvz the analytics tar.gz
4. `job_counts.json | python -m json.tool` should reflect the correct number of jobs in "status" and "launch_type".

##### EXPECTED RESULTS

Should show the correct number of jobs in "status" and "launch_type"

```
{
    "launch_type": {
        "manual": 44,
        "workflow": 15
    },
    "status": {
        "failed": 10,
        "successful": 49
    },
    "total_jobs": 59
}
```

##### ACTUAL RESULTS

Caps at 1: 

```
{'launch_type': {'manual': 1},
 'status': {'running': 1, 'successful': 1},
 'total_jobs': 33}
```

**Comment by one-t** [comment]
Verified on devel-

steps to test:
1. Enable analytics
2. gather analytics
3. check counts
4. launch jobs
5. gather analyics
6. compare counts

This is working as expected
