### ISSUE TITLE
Credentials associated with an organization cannot be shared, through RBAC, with other organizations

### ISSUE THREAD

**Issue by mpetrive-rh** [ansible/awx#4020]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
A Tower credential that is associated with an organization cannot be shared, via RBAC roles, with other users or teams in other organizations.  This occurs even if the user attempting the assignment is `system administrator`.  This seems like a gap in functionality or is perhaps there is security concern here.  Sharing of inventory and projects across organizations seems to work as expected.

##### ENVIRONMENT
* AWX version: Tower 3.5
* AWX install method: Tower VM install
* Ansible version:  2.7
* Operating System: RHEL7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Assuming the following organization and team structure:

* org1
  * teamA
* org2
  * teamB

As a system administrator user, create a `credX` machine credential and associate it with `org1`.  Open the permissions dialog.  Only `teamA` and users in `org1` are listed

##### EXPECTED RESULTS

Ability to assign roles to users/team in other organizations ie `org2->teamB`

##### ACTUAL RESULTS

Can only assign roles to users/teams in credential associated organization ie `org1`

**Comment by jmartensson** [comment]
Any update on this? We use RBAC heavily and this is a must to get it to work in a smooth way.

**Comment by ryanpetrello** [comment]
cc @wenottingham @AlanCoding could you take a peek at this?

**Comment by wenottingham** [comment]
this is a dup of #5738

**Comment by etsurbkfs** [comment]
@wenottingham @ryanpetrello Why did you close this (older) issue in favor of a feature idea that was opened in 2020?  This is not the duplicate, #5738 is a duplicate of this issue.
