### ISSUE TITLE
Secret Management System Credential Types Missing

### ISSUE THREAD

**Issue by jtstuedle** [ansible/awx#4034]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Secret Management System Credential Types Missing

##### ENVIRONMENT
* AWX version: 4.0.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.9
* Operating System: Ubuntu 18.04
* Web Browser: Version 74.0.3729.169 (Official Build) (64-bit)

##### STEPS TO REPRODUCE
- git clone https://github.com/ansible/awx
- _set awx/installer/inventory variables_
- ansible-playbook -i inventory install.yml
- Login to web console, click credentials, add a new credential, try to select one of the credential types found here: https://docs.ansible.com/ansible-tower/latest/html/administration/credential_plugins.html#configure-and-link-secret-lookups

##### EXPECTED RESULTS
Expected to have the ability to create/setup the Secret Management System credential for lookups

##### ACTUAL RESULTS
I've only got the default 14 credential types; it doesn't appear that the Secret Management System credentials were included with the clone.

**Comment by jakemcdermott** [comment]
@jtstuedle 

That feature isn't available on the 4.0.0 images. You'll need to update to a later version than whats on the 4.0.0 container images.
