### ISSUE TITLE
Delete button in credentials list isn't working correctly.

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#4037]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Simply put, the trash icon button isn't working when trying to delete a credential from the credentials list.
![delete_cred_bjork](https://user-images.githubusercontent.com/19942822/59275569-905c6480-8c2a-11e9-8c0d-68d85fca37d3.gif)

##### ENVIRONMENT
* AWX version: latest

##### STEPS TO REPRODUCE
1) Create a credential
2) Attempt to delete it

##### EXPECTED RESULTS
The deletion works.

##### ACTUAL RESULTS
It does not work.

**Comment by jakemcdermott** [comment]
resolved by https://github.com/ansible/awx/pull/4038
