### ISSUE TITLE
Enable customizing/disabling CA certificate when communicating with openstack

### ISSUE THREAD

**Issue by jangsutsr** [ansible/awx#404]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Our upstream dependency `os-client-config` [support it](https://docs.openstack.org/os-client-config/latest/user/configuration.html). `tasks.py` should be modified to officially support it, too.

**Comment by wenottingham** [comment]
Closing, this should be handled in #416 (and the underlying inventory mechanism has changed signficantly here anyway)
