### ISSUE TITLE
 nginx on awx_web creates PID in wrong location - awx intermittenttly refusing connections

### ISSUE THREAD

**Issue by tomoliveri** [ansible/awx#4048]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
/usr/lib/systemd/system/nginx.service
ExecStartPre=/usr/bin/rm -f /run/nginx.pid

/etc/nginx/nginx.conf
pid        /tmp/nginx.pid;

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker on linux
* Ansible version:  2.7
* Operating System: Ubuntu 4.15.0-50-generic
* Web Browser: N/A

##### STEPS TO REPRODUCE
docker-compose up
make multiple ssh / port forwarding connections to awx_web, causing nginx to reload 
or reload nginx on awx_web manually 

##### EXPECTED RESULTS
nginx service reloads successfully  

##### ACTUAL RESULTS
nginx looks for /run/nginx.pid, which does not exist as nginx.conf creates /tmp/nginx.pid
port 8052 remains open but non-responsive 

##### ADDITIONAL INFORMATION
It appears that as the service and nginx.conf point to differing PID files, nginx is unable to clear its PID on restart.

**Comment by shanemcd** [comment]
Hi. Sorry for the delay here. It kind of looks like you were trying to start nginx via systemctl? I think we've always ran it under supervisor, so you would want to use `supervisorctl restart nginx` to restart it. If you are still seeing this please open a new issue with more detailed steps on how to reproduce.
