### ISSUE TITLE
Missing documentation uninstall awx

### ISSUE THREAD

**Issue by JoaoCastroFerreira** [ansible/awx#4049]
##### ISSUE TYPE
 - I would like to uninstall awx

##### SUMMARY
I install with ansible playbook but I don´t find a way to uninstall

**Comment by ryanpetrello** [comment]
There are multiple supported installation methods - how did you install it?  Please provide **all** of the details in the bug report issue template at https://github.com/ansible/awx/issues/new?template=bug_report.md

**Comment by matburt** [comment]
This isn't the place to seek usage help. The irc channel or mailing list would be more suitable.
