### ISSUE TITLE
Add the ability to lookup last time an Inventory was utilized

### ISSUE THREAD

**Issue by falcon78921** [ansible/awx#4061]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Per a customer's request, they would like to be able to review the last time an Inventory was utilized.

Inventories show a modified date/time:
~~~
"modified": "2019-05-28T20:00:24.252273Z"
~~~

In the same way an Inventory is modified, they would like to see a "last-utilized" timestamp.

**Comment by AlanCoding** [comment]
You can get this from the API via a query like `/api/v2/jobs/?inventory=2&order_by=-created`. I'd like to have a better idea of what specific shortcoming of that is of interest here.

**Comment by falcon78921** [comment]
Moved to  https://github.com/ansible/awx/issues/7638
