### ISSUE TITLE
UI popup on successful token deletion that does not make sense

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#4063]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Deleting a token in UI gives unwanted and confusing pop up

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Click on the icon in the UI with your user name

go to tokens

delete one

##### EXPECTED RESULTS

token is deleted

##### ACTUAL RESULTS

this message:

![Screen Shot 2019-06-12 at 3 48 43 PM](https://user-images.githubusercontent.com/1385596/59381591-c6ccd900-8d29-11e9-998c-c0457e032649.png)

request yields a 204 response code. Token is deleted in backend.

**Comment by unlikelyzero** [comment]
We've reimplemented this popup in the new ui. Let's verify that it makes sense

**Comment by unlikelyzero** [comment]
@akus062381 please add a test here if we don't have one already

**Comment by akus062381** [comment]
this issue is fixed, working on finalizing a test. see https://github.com/ansible/tower-qa/pull/6114
