### ISSUE TITLE
INSTALL.md prerequisites clarification needed for remote deployment and with official images

### ISSUE THREAD

**Issue by jirib** [ansible/awx#4065]
##### INSTALL.md could clarify prerequisites for remote deployment and official images
- prerequisites clarification when using official images
- prerequisites clarification for remote deployment

##### SUMMARY
- prerequisites clarification when using official images

When one is going to use official images does she still needs `GNU make`, `nodejs` and `npm`? I don't think so, or am I wrong?

 - prerequisites clarification for remote deployment

When one is going to deploy to a remote - ie. non-local - docker, does she still needs locally installed `docker`, `docker-compose`/docker python module...? Isn't it done via SSH on remote host?

**Comment by john-westcott-iv** [comment]
Our apologies for not responding sooner. We no longer install AWX the same way and the INSTALL.md file is drastically different that it used to be so this should no longer apply. That being said, if you are installing with the operator everything is included in the containers. If you are using a local docker install you will need to install docker/docker-compose locally on the server which will be running AWX. If you need additional help, please open another issue.
