### ISSUE TITLE
Easier keyboard navigation for Job Launch

### ISSUE THREAD

**Issue by alexander-bauer** [ansible/awx#407]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
A common pattern for me is to define an "Apply Site" job template, which normally applies the entire `site.yml`, but also prompts for an optional `limit`. I have to click on the field I want, rather than the first one being selected automatically. When I finish typing that limit string, I press enter to submit the form, but nothing happens, and I must tab over several times, or click the button.

##### ENVIRONMENT
* AWX version: 1.0.0.524
* AWX install method: docker on linux
* Ansible version:  2.3.1.0

##### STEPS TO REPRODUCE

Write a run job template. Leave all prompt-for-launch fields unchecked, except for the `limit`. Attempt to launch the job template. Begin typing before clicking on any field, and find that your cursor is not in any of them. Press enter to launch the job, and find that it does not submit the launch button.

##### EXPECTED RESULTS

The first form-field should be automatically selected when bringing up the prompt. The job should be submitted when pressing enter on non-multiline fields.

##### ACTUAL RESULTS

No field is automatically selected. The form is not submitted when enter is pressed.

**Comment by wenottingham** [comment]
To be fair, keynav is somewhat wonky across many areas of AWX. I'd suspect this is mostly just a bunch of gruntwork across all the various forms.

**Comment by wenottingham** [comment]
It's mostly a question of whether to piecemeal solve this, or pick it up for free(ish) with https://github.com/ansible/awx/issues/143

**Comment by unlikelyzero** [comment]
Here is the behavior which now occurs in the UI:
Job Template Edit View
- If a JT is configured w/ `Job Type` Prompt on Launch, the autofocus does not select the dropdown and mouse needs to be used.
- If a JT is configured w/ `Job Type` and `Inventory` Prompt on Launch, the autofocus does not select the modal and mouse needs to be used.
- If a JT is configured w/ `Survey` with a textfield Prompt on Launch and no other prompted values, the autofocus does not select the modal's first text field.
- If a JT is configured w/ `Survey` with a textfield Prompt on Launch and other prompted values the autofocus selects the modal's first text field on that appropriate Survey tab. 
- If a JT is configured w/ `SKIP TAGS` Prompt on Launch, the autofocus *does* select the first form field, however it always needs to be double clicked to be interacted with if empty.
- If a JT is configured w/ `SKIP TAGS` Prompt on Launch but with a default already set, the autofocus does not select the first form field.
- If a JT is configured w/ `JOB TAGS` Prompt on Launch, the autofocus *does* select the first form field, however that form field always needs to be double clicked to be interacted with.
- If a JT is configured with `Verbosity` Prompt on Launch, the autofocus does not select the first form field.
- If a JT is configured with `Inventory` Prompt on Launch, the `Inventory` radio buttons cannot be interacted with.
- If a JT is configured with `Extra Variables` Prompt on Launch, the autofocus selects the extra_var field for text entry

WFJT Template Edit View
- If a JT is configured with `Extra Variables` Prompt on Launch, the autofocus selects the extra_var field for text entry
- If a JT is configured with `Inventory` Prompt on Launch, the Inventory radio buttons cannot be interacted with.

Management Jobs
- If a Cleanup Activity Stream Job is Launched, the `Set Hours` field is auto focused and text entry is immediate.
- If a Cleanup Job Details Job is Launched, the `Set Hours` field is auto focused and text entry is immediate.

WFViz
- While setting prompts on JTs in WFJT, If a JT is configured with `Extra Variables` Prompt on Launch, the autofocus selects the extra_var field for text entry

In many cases, using tab loses focus on the modal and begins to interact and highlight buttons behind the modal

**Comment by unlikelyzero** [comment]
Closing as this meets the AC. Leaving the comment above to document the new keyboard interaction
