### ISSUE TITLE
Incorrect CSS applied to Labels in Job Template Expanded View

### ISSUE THREAD

**Issue by sugitk** [ansible/awx#4076]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Incorrect CSS applied to Labels in Job Template Expanded View

##### ENVIRONMENT
* AWX version: Tower 3.5.0
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Multiple `LABELS` defined to the Job Template.

##### EXPECTED RESULTS

![After (1)](https://user-images.githubusercontent.com/2234991/59478254-a02ab180-8e93-11e9-9419-ebb4e74723cd.PNG)

![ManyLabelsAfter (1)](https://user-images.githubusercontent.com/2234991/59478289-c2243400-8e93-11e9-9968-c8de5ee22fa1.PNG)

##### ACTUAL RESULTS

![Before (1)](https://user-images.githubusercontent.com/2234991/59478269-ae78cd80-8e93-11e9-9119-5e2a225a709d.PNG)

![ManyLabelsBefore (1)](https://user-images.githubusercontent.com/2234991/59478257-a587fc00-8e93-11e9-964d-7cdef9db6637.PNG)

##### ADDITIONAL INFORMATION

The customer send us the feature request to change labels from vertical formatting to horizontal for ease of view.
In the `.at-RowItem--labels` css class, display should be 'inline-flex' instead of 'inline block'

**Comment by MrBones757** [comment]
@j-shade and i will submit a PR to resolve this issue.

**Comment by dsesami** [comment]
Confirmed in latest AWX that rows display normally, responsiveness appears to be functional, and that the correct CSS is now present.
