### ISSUE TITLE
Build AWX with custom logo

### ISSUE THREAD

**Issue by BramFr** [ansible/awx#4078]
##### ISSUE TYPE
 - Bug Report / Local issue 

##### SUMMARY
Try to build a new awx image with custom logo. But i`ll get potato image :)

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker
* Ansible version:  2.8.1
* Operating System: debian / docker
* Web Browser: chrome latest

##### STEPS TO REPRODUCE

Dir structure
./awx_build/
├── awx (git clone https://github.com/ansible/awx.git)
├── awx-logos (git clone https://github.com/ansible/awx-logos.git)

I`ll change the awx-logos with our logo. 
In the inventory file uncomment line ```awx_official=true```
and comment this line for local build ```#dockerhub_base=ansible```

In the MANIFEST.in change this line:
```
recursive-exclude awx/ui/client *
```
to
```
recursive-include awx/ui/client *
```

##### EXPECTED RESULTS

New logo image when going to http://localhost

##### ACTUAL RESULTS

I`ll get a angry potato image

##### ADDITIONAL INFORMATION

When i login into awx_web and find my logo this is the result:
```
find / -name logo-login.svg
/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/ui/client/assets/logo-login.svg <--- new logo
/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/ui/static/assets/logo-login.svg <--- Angry potato
/var/lib/awx/public/static/assets/logo-login.svg <--- Angry potato
```

**Comment by shanemcd** [comment]
You can provide a custom logo via the UI / API. We include the potato image when building the images yourself for trademark reasons.
