### ISSUE TITLE
Smart Inventory Edit Form is not displaying correctly

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#4082]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Smart Inventory Edit Form is not displaying correctly

##### ENVIRONMENT
* AWX version: 4.0+

##### STEPS TO REPRODUCE

1. Create a Smart Inventory
2. Navigate to that Smart Inventory

##### EXPECTED RESULTS

Smart Inventory Form to appear

##### ACTUAL RESULTS

Corrupted view with limited functionality

##### ADDITIONAL INFORMATION
<img width="1049" alt="Screen Shot 2019-06-14 at 6 51 56 PM" src="https://user-images.githubusercontent.com/12446869/59542763-8e69fe00-8ed5-11e9-8747-214aa44ad67e.png">

Console log ```TypeError: Cannot read property 'summary_fields' of undefined
    at app.83182357a673b003f2c9.js:29
    at new SmartInventoryEdit (app.83182357a673b003f2c9.js:29)
    at Object.instantiate (vendor.553a1b1494b8385f98bf.js:575)
    at vendor.553a1b1494b8385f98bf.js:575
    at Object.<anonymous> (vendor.553a1b1494b8385f98bf.js:608)
    at vendor.553a1b1494b8385f98bf.js:575
    at invokeLinkFn (vendor.553a1b1494b8385f98bf.js:575)
    at nodeLinkFn (vendor.553a1b1494b8385f98bf.js:575)
    at compositeLinkFn (vendor.553a1b1494b8385f98bf.js:575)
    at vendor.553a1b1494b8385f98bf.js:575 "<div ui-view="form" class="ng-scope">"```

**Comment by mabashian** [comment]
Came in with https://github.com/ansible/awx/pull/4044

**Comment by dsesami** [comment]
No more angular anger :+1: each tab displays correctly as well and we don't get any more console errors. I tried this with a few simple smart inventory selection filters.
