### ISSUE TITLE
Ansible version should be 2.8.x in latest (4.0.0) container

### ISSUE THREAD

**Issue by ronnicek** [ansible/awx#4084]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Ansible version in docker version is still 2.7.9

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker on linux
* Ansible version: 2.7.9
* Operating System: 
* Web Browser:

##### STEPS TO REPRODUCE

```
# docker pull ansible/awx_web
Using default tag: latest
latest: Pulling from ansible/awx_web
Digest: sha256:00f9cbe3e1d4d1ed30666bb07669bc30ec44006ecf0ecd0f7f22ad7f5ca643e6
Status: Image is up to date for ansible/awx_web:latest
# # docker exec -it awx_task ansible --version
ansible 2.7.9
```

##### EXPECTED RESULTS

Ansible version should be updated in image (and all packages in image) and not only when version is released. This is also for security (IMHO).

##### ACTUAL RESULTS

Ansible version is old :)

##### ADDITIONAL INFORMATION
N/A

**Comment by shanemcd** [comment]
Ansible 2.8 came out after 4.0.0. We don't rebuild released images, so you'll need to upgrade to 5.0.0 to get the latest version of Ansible. If that is not something you can swing at the moment, you could always check out the 4.0.0 tag and build the images yourself.
