### ISSUE TITLE
WFJT Create form greyed out for Admin User

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/awx#4091]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When logged in as an admin, I cannot create a WFJT in the UI (though I can in the API).  The create form in the UI is greyed out.  

![image](https://user-images.githubusercontent.com/11698892/59633645-fa897380-911a-11e9-9f15-188152a124f9.png)

`git bisect` tracked this back to this PR: https://github.com/ansible/awx/pull/4041

It looks like a permissions issue.  Also, after I create a WFJT in the API, when I go to view it in the UI I can edit the fields.  

##### STEPS TO REPRODUCE

Navigate to the WFJT page, press the [+] sign to create a new WFJT, and observe all the fields greyed out.

##### EXPECTED RESULTS

To be able to edit the fields and submit to create a WFJT.

**Comment by ryanpetrello** [comment]
@rooftopcellist @mabashian does this affect anything other than `devel`?

**Comment by rooftopcellist** [comment]
It looks like the commit that caused it is not in release_3.5.1, I haven't spun up an instance to test it yet though.

**Comment by dsesami** [comment]
Tested WFJT creation as both admins and non-admins. behavior appears to be normal now.

**Comment by giovannifl** [comment]
Just upgraded from AWX 5.0.0 to AWX 6.0.0 and now Workflow templates fields are editable.
