### ISSUE TITLE
Failed to save settings. Returned status: 504 on change logo

### ISSUE THREAD

**Issue by irfanpule** [ansible/awx#4094]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
`Failed to save settings. Returned status: 504` When I change logo in settings > user interface

##### ENVIRONMENT
* AWX version: 2.1.2
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.7.4
* Operating System: CentosOS 7
* Web Browser: firefox

##### ADDITIONAL INFORMATION

![Screen Shot 2019-06-18 at 13 34 41](https://user-images.githubusercontent.com/11069520/59658676-8c05ed80-91ce-11e9-94f3-afc5d252171c.png)

**Comment by shanemcd** [comment]
Interesting. I have not seen this before. I see that you are on AWX 2.1.2. Please try upgrading to a more recent release and open another issue if you are still seeing the problem.

**Comment by zdriic** [comment]
Hi,
I have the same issue with 6.1.0... Impossible to save settings or demo project/template etc... with a DB container.

**Comment by mihoos** [comment]
Hi, 

I have the same issue with AWX 9.3.0.
