### ISSUE TITLE
AWX Tower UI is giving different error as compared to AWX core while running any win_ping or any module from Run Command action.

### ISSUE THREAD

**Issue by LKS1302** [ansible/awx#4095]
COMPONENT NAME - UI

ENVIRONMENT : 
* AWX version: 2.8.1
* AWX install method: docker on linux : Ubuntu
* Ansible version:  2.8.1

Hi,

TOWER RESULT : ERROR  while running basic win_ping module using Run Command on 1 host.
{
    "msg": "pypsrp or dependencies are not installed: cannot import name NtlmContext",
    "_ansible_no_log": false
}
But when we run the same module directly on the core it gives the result. 
Instead of going to localhost core ansible image (2.8.1 Version) every execution gets executed on Docker Ansible image (2.7.9 Version) We have upgraded the due to which it's not visible in the screenshot.
It's a basic installation by directly running the command : ansible-playbook -i inventory install.yml
Can someone please suggest, how could we resolve it.

**Comment by lovisharma1** [comment]
![image](https://user-images.githubusercontent.com/36501381/59665704-ffffc000-91e5-11e9-9d41-2ff26c847803.png)

**Comment by LKS1302** [comment]
![image](https://user-images.githubusercontent.com/36501381/59665925-6a186500-91e6-11e9-8525-37094738a762.png)

**Comment by wenottingham** [comment]
To work out of the box, use the winrm connection plugin.

If you want to use the PSRP plugin, you'll need to work on modifying the image and/or using a custom venv. See here: https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md
