### ISSUE TITLE
SAML Regression

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#4099]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Multiple "Invalid Field" responses for various SAML configuration parameters.

##### ENVIRONMENT
* AWX version: devel

##### STEPS TO REPRODUCE

* PATCH to /api/v2/settings/saml
```
{

    "SOCIAL_AUTH_SAML_ORGANIZATION_ATTR": {
        "saml_attr": "Orgs",
        "saml_admin_attr": "Admins"
    },
    "SOCIAL_AUTH_SAML_TEAM_ATTR": {
        "team_org_map": [
            {
                "organization": "Red Hat",
                "team": "Marketing"
            },
            {
                "organization": "Red Hat",
                "team": "Human Resources"
            },
            {
                "organization": "Red Hat",
                "team": "Engineering"
            },
            {
                "organization": "Ansible",
                "team": "Engineering"
            },
            {
                "organization": "Ansible",
                "team": "Quality Engineering"
            },
            {
                "organization": "Ansible",
                "team": "Sales"
            }
        ]
    }
}
```

##### EXPECTED RESULTS

* 200 

##### ACTUAL RESULTS

400 BAD Request
```
{
    "SOCIAL_AUTH_SAML_ORGANIZATION_ATTR": {
        "saml_admin_attr": [
            "Invalid field."
        ],
        "saml_attr": [
            "Invalid field."
        ]
    },
    "SOCIAL_AUTH_SAML_TEAM_ATTR": {
        "team_org_map": [
            "Invalid field."
        ]
    }
}
```

##### ADDITIONAL INFORMATION

Possibly due to Django + package upgrades.

**Comment by one-t** [comment]
~Just tried this out with the suggested payload, same error for me. Is this payload correct though? That appears to be an explicit map in the attr setting. (Paging @chrismeyersfsu because @jbradberry is on vacation)~

Disregard, tried on devel. Rerunning on jbradberry:fix-4099

**Comment by one-t** [comment]
Confirmed, `jbradberry:fix-4099` corrects the issue. This payload was accepted.
