### ISSUE TITLE
Ability to configure entire system for DataDog Ansible integration

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#41]
DataDog has an integration that saves and visualizes metrics from playbook runs:

https://docs.datadoghq.com/integrations/ansible/

This works via a callback plugin, details here:

https://github.com/DataDog/ansible-datadog-callback

See Installation section

> Copy datadog_callback.py to your playbook callback directory (by default callback_plugins/ in your playbook's root directory). Create the directory if it doesn't exist.
> Create a datadog_callback.yml file alongside datadog_callback.py, and set its contents with your API key, as following:

We should have a way to enable this for all playbook runs inside of AWX, instead of a one-off configuration for every playbook directory.

**Comment by rromanchuk** [comment]
Related for docker users https://github.com/ansible/awx/issues/34  this callback requires pip libraries, it's a bit confusing to figure out how to get them enabled
