### ISSUE TITLE
Error when composing : manifest for ansible/awx_web:5.0.0 not found

### ISSUE THREAD

**Issue by oroomans** [ansible/awx#4100]
- Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Installer seems broken since the push https://github.com/ansible/awx/commit/5d49fe2170f34767cb21f7b6ca84269566dad247

##### ENVIRONMENT
* AWX version: 5.0.0
* AWX install method:  docker on linux,
* Ansible version:  5.0..0
* Operating System: Ubuntu 18.04 LTS
* Web Browser:

##### STEPS TO REPRODUCE

ansible-playbok -i inventory install.yml

##### EXPECTED RESULTS
Installation succeed
##### ACTUAL RESULTS
Error, image 5.0.0 not found

**Comment by oroomans** [comment]
Setting back VERSION file to 4.0.0 does solves the issue as workaround

**Comment by shanemcd** [comment]
5.0.0 is not released yet. If you want to track devel you'll need to build your own images. Otherwise it's always a good idea to track a specific tag.
