### ISSUE TITLE
Jobs return "Successful" even when host pattern broken and failing to match or run against any hosts

### ISSUE THREAD

**Issue by HariSekhon** [ansible/awx#4109]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Host pattern failed to match, AWX job ran against no hosts but returned Successful

##### ENVIRONMENT
* AWX version: 4.0.0.0
* AWX install method:  docker on linux
* Ansible version:  2.7.9
* Operating System: Linux
* Web Browser: Chrome

##### STEPS TO REPRODUCE

I had an AWX job that used to work, someone changed inventory tags which meant the host pattern which was using those tags now failed to match anything.

##### EXPECTED RESULTS

I would have expected a job error upon the host pattern failing and finding no hosts to match, so that we would know to debug the job.

##### ACTUAL RESULTS

Job was still marked as Successful, even though it did nothing:

##### ADDITIONAL INFORMATION

```
[WARNING]: Could not match supplied host pattern, ignoring: <custom>

[WARNING]: Could not match supplied host pattern, ignoring: role_<custom>

PLAY [<custom>:&role_<custom>] *********************************************
skipping: no hosts matched
```

**Comment by HariSekhon** [comment]
Turns out my colleague has been working around this "feature" by writing his playbooks with all hosts and then putting the limit in the AWX Limit box of the job template, which seems highly risky as if someone ran the playbook from the command line instead all hell would break loose across servers.

**Comment by wenottingham** [comment]
This is ansible behavior - see https://github.com/ansible/ansible/issues/14693
