### ISSUE TITLE
Set execution rights to custom inventory scripts synced from Git

### ISSUE THREAD

**Issue by falcon78921** [ansible/awx#4111]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

When syncing custom inventory scripts from Git, the script may not have the execution bit set (i.e. `chmod +x`).  

Users may run into this issue because of execution permissions:
~~~
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
[WARNING]:  * Failed to parse
/var/lib/awx/projects/_6__github/scripts/custom_inv1.py with script plugin:
problem running /var/lib/awx/projects/_6__github/scripts/custom_inv1.py --list
([Errno 13] Permission denied)
~~~

Per a customer's request, they thought it would be nice if a  `chmod +x` command were executed on custom inventory scripts being pulled down from Git.

**Comment by ryanpetrello** [comment]
@falcon78921,

I'm a little uneasy about assuming intent and automatically applying a `+x` from arbitrary source code AWX might pull.  I think is better handled by script authors being explicit in source control.
