### ISSUE TITLE
Unable to create 'Grafana' Notification Type

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#4113]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Unable to create 'Grafana' Notification type. I can edit an existing notification to _become_ a Grafana type but cannot make further edits.

##### ENVIRONMENT
* AWX version: 5.0.0
* AWX install method: N/A
* Ansible version:  N/A
* Operating System: macOS 10.14.5
* Web Browser: Firefox  	60.7.0esr

##### STEPS TO REPRODUCE

1. Navigate to the Notification Templates Page
2. Use the Add Notification form to create a Grafana Type notification.
3. When Save is pressed, a console error is generated.

##### EXPECTED RESULTS

Grafana Notification created

##### ACTUAL RESULTS

Console error and no notification created.

##### ADDITIONAL INFORMATION

```TypeError
​
columnNumber: 761892
​
fileName: "https://ec2-3-84-25-214.compute-1.amazonaws.com/static/js/app.67701a56bccfdc1649f0.js"
​
lineNumber: 29
​
message: "$scope[i] is undefined"
​
stack: "processValue@https://ec2-3-84-25-214.compute-1.amazonaws.com/static/js/app.67701a56bccfdc1649f0.js:29:761892\nexports.default</$scope.formSave/params.notification_configuration<@https://ec2-3-84-25-214.compute-1.amazonaws.com/static/js/app.67701a56bccfdc1649f0.js:29:762755\nexports.default</$scope.formSave@https://ec2-3-84-25-214.compute-1.amazonaws.com/static/js/app.67701a56bccfdc1649f0.js:29:762618\nfn@https://ec2-3-84-25-214.compute-1.amazonaws.com/static/js/vendor.553a1b1494b8385f98bf.js line 575 > Function:4:141\ncallback@https://ec2-3-84-25-214.compute-1.amazonaws.com/static/js/vendor.553a1b1494b8385f98bf.js:575:265537\n$eval@https://ec2-3-84-25-214.compute-1.amazonaws.com/static/js/vendor.553a1b1494b8385f98bf.js:575:149044\n$apply@https://ec2-3-84-25-214.compute-1.amazonaws.com/static/js/vendor.553a1b1494b8385f98bf.js:575:149382\ncompile/</<@https://ec2-3-84-25-214.compute-1.amazonaws.com/static/js/vendor.553a1b1494b8385f98bf.js:575:265638\ndispatch@https://ec2-3-84-25-214.compute-1.amazonaws.com/static/js/vendor.553a1b1494b8385f98bf.js:29:53629\nadd/elemData.handle@https://ec2-3-84-25-214.compute-1.amazonaws.com/static/js/vendor.553a1b1494b8385f98bf.js:29:50461\n"```

**Comment by ryanpetrello** [comment]
Moving this to `state:medium`, it's a JS error traceback being thrown.

cc @mabashian

**Comment by dsesami** [comment]
Confirmed that I can create a grafana notification directly now, and also that I can edit another notification and change it to a grafana type.
