### ISSUE TITLE
gce dynamic inventory hosts are always disabled

### ISSUE THREAD

**Issue by fvzwieten** [ansible/awx#4115]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Hosts synced from GCE are all "off" (disabled)

##### ENVIRONMENT
* Tower version 3.5.0
* Tower bundle on RHEL 8.
* Ansible version:  2.8.0
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

- Created GCP credential. I created a key for the "Compute Engine default service account", downloaded the JSON and uploded that into the GCP credential. 
- Created inventory with GCP source using GCP credential
- Create simple playbook that creates instance in GCP which works, proving the GCP credential is valid
- Performed inventory sync -> hosts sync including all groups and data, however, hosts are all "off" (disabled), rendering the inventory useless.

##### EXPECTED RESULTS

Enabled hosts

##### ACTUAL RESULTS

Disabled hosts

##### ADDITIONAL INFORMATION

When I create instances directly in GCP using the GCP web ui, it gets also synced, but also "disabled".

The sync job does procedure errors, but I do not think these are related, but I include them anyway:

    1.220 INFO     Updating inventory 2: MyInv
    1.535 INFO     Reading Ansible inventory source: /tmp/awx_118_bktil_eq/gcp_compute.yml
    1.537 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    1.537 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
    1.537 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
   32.867 ERROR    ansible-inventory 2.8.0
   32.867 ERROR      config file = /etc/ansible/ansible.cfg
   32.867 ERROR      configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
   32.867 ERROR      ansible python module location = /usr/lib/python3.6/site-packages/ansible
   32.867 ERROR      executable location = /usr/bin/ansible-inventory
   32.867 ERROR      python version = 3.6.8 (default, Jan 11 2019, 02:17:16) [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)]
   32.867 ERROR    Using /etc/ansible/ansible.cfg as config file
   32.867 ERROR    [DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to 
   32.867 ERROR    allow bad characters in group names by default, this will change, but still be 
   32.867 ERROR    user configurable on deprecation. This feature will be removed in version 2.10.
   32.867 ERROR     Deprecation warnings can be disabled by setting deprecation_warnings=False in 
   32.867 ERROR    ansible.cfg.
   32.867 ERROR     [WARNING]: Invalid characters were found in group names but not replaced, use
   32.867 ERROR    -vvvv to see details
   32.867 ERROR    
   32.867 ERROR    Parsed /tmp/awx_118_bktil_eq/gcp_compute.yml inventory source with auto plugin
   32.868 INFO     Processing JSON output...
   32.868 INFO     Loaded 7 groups, 1 hosts
   33.025 INFO     Inventory import completed for gcp in 31.8s

**Comment by ryanpetrello** [comment]
Hey @fvzwieten,

This should be resolved in the most recent version of AWX.  It came about due a (subtle) recent change to Google's API:

https://github.com/ansible/awx/pull/4052
