### ISSUE TITLE
Target multiple inventories for a job template

### ISSUE THREAD

**Issue by astraios** [ansible/awx#412]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
In a job template, I think it would be great to be able to select multiple inventories. Also a feature like being able to target every hosts in every inventories for a job would be fantastic.

**Comment by wenottingham** [comment]
This can be faked by setting up a smart inventory that pulls from multiple inventories and automating across that.

**Comment by matburt** [comment]
Our typical recommendation is, that if you have a need to target multiple inventories then just create another inventory with hosts from the other inventories also.

**Comment by lhoss** [comment]
> ...just create another inventory with hosts from the other inventories also.

really sub-optimal solution (to have to duplicate) if you have a larger number of inventories (like 1 per data-center) and many (>50) inv. groups

>...a smart inventory that pulls from multiple inventories and automating across that.

sounds like a smarter solution!  Will have to dig into that. Ref page: http://docs.ansible.com/ansible-tower/latest/html/userguide/inventories.html#smart-inventories

Still, I can imagine various advantages of having an explicit multi-inventory deploy support:
* Possibility of providing a configurable multiple choice list of inventories, that the user can adapt on demand before submitting the deployment job
* Possibility to provide a run the job sequentially (vs in-parallel) over each selected inventory and stop deployment on the whole list (or not) on playbook failure
