### ISSUE TITLE
ovirt dynamic inventory script in Tower does not work with ovirt 4.3

### ISSUE THREAD

**Issue by pharriso** [ansible/awx#4121]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

ovirt.py dynamic inventory shipped with Tower 3.5.0.1 fails on inventory sync with RHV/Ovirt 4.3.

The problem related to inventory sync with ovirt 4.3 was fixed in this issue - https://github.com/ansible/ansible/pull/54338/

But this fix is not in the inventory script shipped with Tower.

##### ENVIRONMENT

* Tower Install - 3.5.0.1

* AWX install method: linux
* Ansible version:  2.8.0
* Operating System: RHEL 7.6
* Web Browser: Firefox 66.0.5

* RHV 4.3.3.7-0.1

##### STEPS TO REPRODUCE

Execute inventory sync with source "Red Hat Virtualization" using Tower 3.5.0.1 connected to RHV 4.3 environment.

##### EXPECTED RESULTS

Inventory sync completes without error.

##### ACTUAL RESULTS

Sync fails with:

 [WARNING]:  * Failed to parse /var/lib/awx/venv/awx/lib64/python3.6/site- packages/awx/plugins/inventory/ovirt4.py with script plugin: Inventory script (/var/lib/awx/venv/awx/lib64/python3.6/site- packages/awx/plugins/inventory/ovirt4.py) had an execution error: Traceback (most recent call last):   File "/var/lib/awx/venv/awx/lib64/python3.6/site- packages/awx/plugins/inventory/ovirt4.py", line 262, in <module>     main() File "/var/lib/awx/venv/awx/lib64/python3.6/site- packages/awx/plugins/inventory/ovirt4.py", line 254, in main vm_name=args.host,   File "/var/lib/awx/venv/awx/lib64/python3.6/site- packages/awx/plugins/inventory/ovirt4.py", line 213, in get_data     vms[name] = get_dict_of_struct(connection, vm)   File "/var/lib/awx/venv/awx/lib64/python3.6/site- packages/awx/plugins/inventory/ovirt4.py", line 182, in get_dict_of_struct (stat.name, stat.values[0].datum) for stat in stats   File "/var/lib/awx/venv/awx/lib64/python3.6/site- packages/awx/plugins/inventory/ovirt4.py", line 182, in <genexpr> (stat.name, stat.values[0].datum) for stat in stats IndexError: list index out of range

##### ADDITIONAL INFORMATION

Manually adding the fix from https://github.com/ansible/ansible/pull/54338/ allows inventory sync to RHV 4.3 to work.

**Comment by ryanpetrello** [comment]
Resolved by https://github.com/ansible/awx/pull/4083

**Comment by kdelee** [comment]
Works for me! :stamp:

Synced against internal RHV...imported both disabled and enabled hosts.
![Screenshot from 2019-06-26 16-10-37](https://user-images.githubusercontent.com/29239279/60211434-ffda7280-982c-11e9-916e-e063b865528a.png)
