### ISSUE TITLE
support v2_runner_on_start event that is to be added in Ansible 2.8

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#4129]
https://github.com/ansible/ansible/pull/47684/files Ansible 2.8 is adding a `v2_runner_on_start` event type. Pre Ansible 2.8 a single event is emitted, `playbook_on_task_start`, when a play begins. Then, an event of the form `runner_on_*` is emitted for _each_ host when it finishes the task. Now, for each `runner_on_*` finish event, there will be a corresponding `v2_runner_on_start` event.

This is especially helpful to identify tasks that are long-running for various reasons i.e. waiting for input, establishing an ssh connection, etc.

At a minimum we need to add the new event to our event list https://github.com/ansible/awx/blob/devel/awx/main/models/events.py#L102

Ideally, we would relate the finish task event to the start task event via our uuid similar to how we relate events via parent_uuid. Note that this might need to be added at the Ansible Runner level but the field may need to be brought to the forefront in awx so that we can database index it.

**Comment by ryanpetrello** [comment]
@matburt @jakemcdermott @wenottingham is this list of events even used anymore?

https://github.com/ansible/awx/blob/devel/awx/main/models/events.py#L102

I can update it, but the `runner_on_start` event seem to work (and get recorded) just fine in `devel`:

I'm not really sure there's *actually* much we need to do here in terms of event display:

```sql
awx-dev=> SELECT event, task, parent_uuid FROM main_jobevent WHERE event='runner_on_start';
      event      |      task       |             parent_uuid
-----------------+-----------------+--------------------------------------
 runner_on_start | Gathering Facts | 0242ac12-0005-0113-8abb-00000000000c
 runner_on_start | Hello Message   | 0242ac12-0005-0113-8abb-000000000008
 runner_on_start | Gathering Facts | 0242ac12-0005-28af-e3b2-00000000000c
 runner_on_start | Hello Message   | 0242ac12-0005-28af-e3b2-000000000008
(4 rows)

awx-dev=> SELECT event, uuid, task FROM main_jobevent WHERE uuid IN ('0242ac12-0005-28af-e3b2-000000000008', '0242ac12-0005-0113-8abb-00000000000c');
         event          |                 uuid                 |      task
------------------------+--------------------------------------+-----------------
 playbook_on_task_start | 0242ac12-0005-0113-8abb-00000000000c | Gathering Facts
 playbook_on_task_start | 0242ac12-0005-28af-e3b2-000000000008 | Hello Message
(2 rows)
```

![image](https://user-images.githubusercontent.com/214912/64785246-ef878900-d539-11e9-9dc2-e4fb3a7f9d73.png)

**Comment by kdelee** [comment]
Works for me!
