### ISSUE TITLE
Feature: Insights One-Click Remediation

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#413]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Right now remediating hosts using Insights information and playbook is a cumbersome process. Things that have to happen to be able to get to the finish line of running an Insights generated playbook (Maintenance Plan):

1. Hosts have to have Insights installed
2. AWX has to know a host is an Insights host
3. Maintenance Plan
4. AWX must have Insights Creds
5. Run maintenance plan

##### Currently
1. Up to the user to do this
2. Done via a special playbook in AWX + assign Insights Cred to Inventory that hosts live in
3. User has to create a Maintenance Plan in Insights then come back into AWX and re-sync an Insights Project in order for the Maintenance Plan to be ran in AWX.
4. User creates and Insights Cred in AWX.
5. Confusing path to find the remediate button; per-host or Inventory

http://docs.ansible.com/ansible-tower/latest/html/userguide/insights.html

The goal is to make the running of a maintenance plan simpler in AWX.

##### Future
1. Create an Insights installer playbook/roles and add a special project in AWX that points at the github scm.
a. Install Insights
b. Register Insights
c. Run Insights "scan" (this will generate a facts.d)
d. Consume facts.d (via Ansible gather facts)
2. New Insights client will lay down the insights system id in facts.d so that "normal" fact gathering can identify a host as an Insights host. AWX needs to support this new feature. Once it does, users will not need to run a special playbook.
3. Create Insights Maintenance Plans through the AWX UI. This can only be done if the AWX knows about Insights Rules + Reports.
a. AWX needs to gather reports during a gather facts when fact caching is activated for Insights hosts and store them in the DB (per-host).
b. AWX needs to periodically gather rules from Insights API and store it in the AWX DB.
c. Maintenance Plans created via AWX needs to be stored in the AWX DB.
4. This will always need to be done.
5. With 3a. and 3b. completed, the UI can show aggregate information.

**Comment by wenottingham** [comment]
closing in favor of more generic https://github.com/ansible/awx/issues/5158
