### ISSUE TITLE
Inventory Host Name vs Hostname

### ISSUE THREAD

**Issue by strawgate** [ansible/awx#4131]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Currently AWX uses the hostname of the host entered as the name of the host in the inventory file. This means that you cannot inventory/manage multiple hosts which share the same IP address or hostname. A particular use-case would be devices exposed behind a NAT where many devices share the same IP address from the perspective of the AWX server but each is accessible from a different port on the gateway for the NAT.

**Comment by matburt** [comment]
This is more about the way Ansible itself handles hosts, and there are ways to work around this. For example using `ansible_ssh_host=...` or `ansible_host=...` where the identifier becomes an alias for the actual system you are connecting to.

**Comment by wdrury-uk** [comment]
@matburt thanks for the response, but this is my challenge also.  In cmdline ansible-playbook, this is how I use my hosts, but now migrating into awx/tower seem to only be able to provide hostname/ip.

As per original feature request, is it not possible to provide _alias_ field in awx/tower for hosts to mirror the offering when using standalone inventory/hosts files?

**Comment by matburt** [comment]
The reason it works the way it does is because Tower/AWX doesn't do anything extra to the hosts that are in inventory. So whatever you are doing in standalone ansible would work the same way in Tower.

You can import inventory files from a project directly into a Tower inventory and it'll just pick up whatever vars are associated with it.

I'm not sure I understand what you are doing different on standalone ansible versus Tower?

**Comment by wdrury-uk** [comment]
For example extract of _inventory_ file of hosts looks like:
```
[application]
twrapp1 ansible_host=192.168.1.100
twrapp2 ansible_host=192.168.1.101
twrapp3 ansible_host=192.168.1.102

[database]
twrdb1 ansible_host=192.168.1.104
```

But in tower/awx when adding a host, you can only provide Host Name and Description.  But if I treat Description like Alias in inventory file the play will fail.

I was expecting Name/Alias, Host therefore being the equivalent of Alias and ansible_host value in the inventory example above.

Does that make sense, am I missing something obvious?

Sorry still quite new to tower.

**Comment by wenottingham** [comment]
There's a variables section for a host, that's where `ansible_host=x.y.z` goes. In your inventory example above, what you're doing is declaring a host named `twrapp1` with variables of `ansible_host=192.168.1.100` (and any other key=value pairs you have after it).
