### ISSUE TITLE
RFE: Add jobs description in workflow visualizer

### ISSUE THREAD

**Issue by sebw** [ansible/awx#4135]
My customer would appreciate to see the job description of job templates in the workflow visualizer.

Another idea would be to add the possibility to add notes.

Job description or notes would help a lot understanding what the workflow is all about.

Automagic, an automation app on Android implemented the note feature a while ago.

This is a screenshot of Automagic workflow visualizer. The yellow block is a note:

![automagic](https://user-images.githubusercontent.com/2285094/59907169-f2228880-93f9-11e9-909d-708f0079d001.jpg)

**Comment by unlikelyzero** [comment]
Please follow the work in https://github.com/ansible/awx/issues/2032
