### ISSUE TITLE
ovirt4 integration is broken in recent AWX versions with Ansible 2.8

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#4138]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Two problems:

- Up until _very_ recently (like, moments ago), the `ovirt4.py` inventory script in Ansible (which we vendor in AWX) didn't work when run under python3 (meaning these inventory updates would fail in certain distributions that ship py3 by default, like RHEL8)

- Due to a bug in the `ovirt4.py` inventory script, Inventory Syncs would fail if any VMs managed by the Ovirt/RHV manager were powered off.

- In Ansible 2.8, the `ovirt` modules now require `>= ovirtsdk4 version 4.3.0` (see  https://github.com/ansible/awx/issues/4030, https://github.com/ansible/ansible/commit/bfc6a2a8d6342c7f36038c2216dc8f3e50a6244a)

We should:

- Pull in the latest `ovirt4.py` script from Ansible 2.9dev (PR: https://github.com/ansible/awx/pull/4083)
- Update the version of `ovirt-engine-sdk-python` in our `requirements.txt`

**Comment by rmkraus** [comment]
Also, inventory syncs would fail if any VMs managed by the Ovirt/RHV manager were powered off. Slightly different issue, but same resolution.

**Comment by kdelee** [comment]
Works for me! :stamp:

Synced against internal RHV...imported both disabled and enabled hosts.
![Screenshot from 2019-06-26 16-10-37](https://user-images.githubusercontent.com/29239279/60211434-ffda7280-982c-11e9-916e-e063b865528a.png)
