### ISSUE TITLE
5.0.0 tag points to a commit not in the devel branch

### ISSUE THREAD

**Issue by geauxvirtual** [ansible/awx#4142]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
5.0.0 tag points to a commit not in the devel branch

##### EXPECTED RESULTS

5.0.0 tag points to a commit in the devel branch

##### ACTUAL RESULTS

5.0.0 tag points to a test commit not in the devel branch.

https://github.com/ansible/awx/commit/34ba862c5ae690bafff822bdd82366ad87b7e78e

**Comment by shanemcd** [comment]
Whoops!

**Comment by shanemcd** [comment]
I'll fix this now.

**Comment by shanemcd** [comment]
Fixed, sorry about that.
