### ISSUE TITLE
JSON Format for metrics API

### ISSUE THREAD

**Issue by kfattig** [ansible/awx#4144]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The '/metrics/' API [does not support JSON format](https://github.com/ansible/awx/pull/3672/files).

Metrics are returned as raw text, with comments and inconsistent formatting. This is different than most of the other API endpoints, that return easily consumable JSON.  We would prefer to interact with this API in a similar manner to the others, for example using [tower-cli](https://github.com/ansible/tower-cli) .  If JSON was supported, this would be relatively easy functionality to add.

I've attempted to do this myself in a client (extending tower-cli), and I'm able to handle most of the metrics pretty easily.  When comments make clear what they are, and they have meaningful values.  For example this metric:
```bash
# HELP awx_organizations_total Number of organizations
# TYPE awx_organizations_total gauge
awx_organizations_total 28.0
```
Translates to:
```json
  "awx_organizations_total": "28.0",
```

But not all items are this straightforward.  I'm unsure how to handle this one for instance:
```bash
# HELP awx_instance_info Info about each node in a Tower system
# TYPE awx_instance_info gauge
awx_instance_info{enabled="True",instance_uuid="f3c13b50-74c2-4f47-b847-f17a09c0d3c9",last_isolated_check="None",managed_by_policy="True",version="3.5.0"} 1.0
```
Applying the same logic to this metric produces odd results.  It seems like all the usable information in this case is in the key, and the value is meaningless?:
```json
"awx_instance_info{enabled=\"True\",instance_uuid=\"4a0cab64-64fc-4a6f-88d7-2dae480ed71f\",last_isolated_check=\"None\",managed_by_policy=\"True\",version=\"3.5.0\"}": "1.0",
```

This representation seems more logical:
```json
"awx_instance_info": {
  "enabled": "True",
  "instance_uuid": "4a0cab64-64fc-4a6f-88d7-2dae480ed71f",
  "last_isolated_check": "None",
  "managed_by_policy": "True",
  "version": "3.5.0"
}

```

This difference in format seems to be discussed [here](https://github.com/ansible/awx/issues/3781).

I'm happy to assist with this if I can - I had planned on submitting a PR to tower_ci to handle this data, but this structure seems like something that should be defined by the API.

**Comment by ryanpetrello** [comment]
@kfattig,

The `/api/v2/metrics/` API is intended to be consumed by https://prometheus.io

**Comment by ryanpetrello** [comment]
@kfattig I've got a PR open for this, which may interest you: https://github.com/ansible/awx/pull/4465

**Comment by kfattig** [comment]
Thanks @ryanpetrello!  I built & tested https://github.com/ansible/awx/pull/4465 , it covers our needs.

I'll have a PR sometime next week for tower-cli to get/list these values.

**Comment by ryanpetrello** [comment]
@kfattig before opening a PR over there, you may care to know that we're actively working on an official tool in awx that is a _replacement_ for `tower-cli`, and it's currently *in* the awx source tree (though it's not ready for prime time in the official release _just_ yet - in the coming weeks, we intend to make an announcement on the mailing list): https://github.com/ansible/awx/tree/devel/awxkit

One of the benefits to this tool is that - unlike `tower-cli` - it discovers much of AWX's new endpoints and functionality via HTTP OPTIONS requests.

The good news is that it already supports this feature, and you can test it out today:

```shell
~ pip install "git+ssh://git@github.com/ansible/awx.git#egg=awxkit[formatting,websockets]&subdirectory=awxkit"
~ awx -h
~ awx metrics | head
{
     "awx_system_info": {
          "labels": {
               "ansible_version": "2.9.0.dev0",
               "external_logger_enabled": "False",
               "external_logger_type": "None",
               "insights_analytics": "False",
               "install_uuid": "4fb19bfb-3c3d-4b41-b6b7-4cf8ef6b2c73",
               "license_expiry": "0",
               "license_type": "open",
```

**Comment by kfattig** [comment]
@ryanpetrello I was wondering what that command was in the PR.  Thank you, I'll take a look.

**Comment by ryanpetrello** [comment]
Also, if you run into trouble installing with `awxkit[formatting]`, you may need a few extras for `--jq` to work (like `libtool`):

https://github.com/ansible/awx/blob/devel/awxkit/awxkit/cli/docs/source/output.rst#custom-formatting-with-jq
