### ISSUE TITLE
AWX_ANSIBLE_CALLBACK_PLUGINS settings does not work in ansible_runner

### ISSUE THREAD

**Issue by Turgon37** [ansible/awx#4149]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The AWX settings "AWX_ANSIBLE_CALLBACK_PLUGINS" is not propagated to the ansible-playbook process during job executions

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.9
* Operating System: CentOS
* Web Browser: Firefox 67

##### STEPS TO REPRODUCE
Add a custom path into the variable AWX_ANSIBLE_CALLBACK_PLUGINS using the webui SETTINGS-> JOBS-> ANSIBLE CALLBACK PLUGINS 

Then dump the content of the variable ANSIBLE_CALLBACK_PLUGINS from a playbook

```
- debug: msg="{{ lookup('env', 'ANSIBLE_CALLBACK_PLUGINS') }}"
```

##### EXPECTED RESULTS
The custom path in the list produced by "debug" task

##### ACTUAL RESULTS
This "static" path 

```
ok: [localhost] => {
    "msg": "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/ansible_runner/callbacks"
}
```

##### ADDITIONAL INFORMATION

I'm using AWX with a custom virtual environment with the ara project https://github.com/ansible-community/ara/tree/0.16.5. To ara to work, we need to extends the callback_plugins directories list with a path to the ara project library folder (according to https://github.com/ansible-community/ara/blob/0.16.5/doc/source/configuration.rst#using-ansiblecfg).
By default, I notice that AWX (https://github.com/ansible/awx/blob/9f42d9426cf0165921dca0d77bbb8fe9d283f41f/awx/main/tasks.py#L1387) adds the "callback_plugins" directory from the root of the current project and append the value of the setting AWX_ANSIBLE_CALLBACK_PLUGINS if available to the list.
I suppose AWX produces the environment vars called "ANSIBLE_CALLBACK_PLUGINS" and pass it to the ansible_runner library. But this last one does not take care of it because it look for  "AWX_LIB_DIRECTORY" https://github.com/ansible/ansible-runner/blob/master/ansible_runner/runner_config.py#L172

```
    "AWX_ANSIBLE_CALLBACK_PLUGINS": [
        "/data/virtualenvs/python3-v1.0.0/lib/python3.6/site-packages/ara/plugins/callbacks"
    ],
```

See this issue on stackoverflow related to the same problem https://stackoverflow.com/questions/55331878/how-to-add-a-callback-plugin-to-awx-docker

**Comment by dmsimard** [comment]
@turgon37 this is already tracked in ansible-runner: https://github.com/ansible/ansible-runner/issues/219

**Comment by Turgon37** [comment]
@dmsimard I'm very sorry, I've deeply checked on awx repository but I've forgotten to check on ansible_runner because I was thinking that this issue is only AWX related.

Do I close this issue ? or keep it until the another one is fixed ?

**Comment by ryanpetrello** [comment]
Let's track it over there.

**Comment by vvxxvvxx** [comment]
@Turgon37  did you fix this issue already? I met the same issue that the playbook can't use my custom callback when running the playbook on AWX. even after I add the variables "ANSIBLE_CALLBACK_PLUGINS": "./plugins/callback" in Settings>Jobs. or change "ANSIBLE_CALLBACK_PLUGINS" to "AWX_ANSIBLE_CALLBACK_PLUGINS"... the result is the same, no callback is called when running the playbook on AWX. 
But if i run the playbook just using command line "ansible-playbook -i inventory playbook.yml...", it works all right, the callback also works...

Don't know which part or env variables have such issue which makes the custom plugin from awx can't be called.
