### ISSUE TITLE
Ansible AWX Job Failed

### ISSUE THREAD

**Issue by myo-myint-zaw** [ansible/awx#4151]
##### ISSUE TYPE
 - Feature 

##### SUMMARY
Can anyone please advise this issue?

{
    "msg": "Traceback (most recent call last):\n  File \"/bin/ansible-connection\", line 335, in <module>\n    main()\n  File \"/bin/ansible-connection\", line 315, in main\n    messages.extend(Connection(socket_path).pop_messages())\n  File \"/opt/awx/embedded/lib/python2.7/site-packages/ansible/module_utils/connection.py\", line 167, in __rpc__\n    response = self._exec_jsonrpc(name, *args, **kwargs)\n  File \"/opt/awx/embedded/lib/python2.7/site-packages/ansible/module_utils/connection.py\", line 146, in _exec_jsonrpc\n    response = json.loads(out)\n  File \"/usr/lib64/python2.7/json/__init__.py\", line 338, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib64/python2.7/json/decoder.py\", line 366, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib64/python2.7/json/decoder.py\", line 384, in raw_decode\n    raise ValueError(\"No JSON object could be decoded\")\nValueError: No JSON object could be decoded\n",
    "_ansible_no_log": false
}

**Comment by ryanpetrello** [comment]
@user-david please re-file this and provide _all_ of the information requested at:

https://github.com/ansible/awx/issues/new?template=bug_report.md

(including AWX + Ansible version you're using, what you did to reproduce it, the error you see in its entirety, etc...)
