### ISSUE TITLE
RBAC - Disable Job Cancelation on template

### ISSUE THREAD

**Issue by JulienGrp** [ansible/awx#4153]
##### ISSUE TYPE
 - Feature Idea
We use AWX to create resources on a VmWare infrastructure. When we're creating a resource, if the Job is cancelled while it's running, the model "breaks" without human intervention.

##### SUMMARY
Is it possible to unauthorised an "Execute" profile to cancel a job ? It could be only done by an "Admin" profile on this Job.

I would appreciate any help you can provide.

**Comment by shanemcd** [comment]
Sorry for the delay here. To me, it sounds like it might end up being more dangerous to not allow someone to cancel a job they launched. Given the lack of interest in this issue I'm going to close this.
