### ISSUE TITLE
Netbox Inventory Plugin for AWX/Tower

### ISSUE THREAD

**Issue by loganbest** [ansible/awx#4154]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

As of Ansible 2.8, Netbox has had a native inventory plugin. Including that as an available inventory source in AWX/Tower would be a welcome addition in the automation world as Netbox's popularity increases.

**Comment by loganbest** [comment]
@fragmentedpacket

**Comment by petrdanecek** [comment]
what is the workaround for now? I mean I tested the ansible netbox plugin and it works like a charm. Do I need to use some kind of custom script in the AWX until it is implemented into AWX?

**Comment by ryanpetrello** [comment]
@petrdanecek,

AWX supports custom inventory scripts.  This is one way to accomplish this for now: https://docs.ansible.com/ansible-tower/latest/html/administration/custom_inventory_script.html

**Comment by ryanpetrello** [comment]
@AlanCoding,

Is there any way to do this with the new plugin architecture?  i.e., have some custom source that - instead of a script - is literally just "use plugin X from Ansible"?

**Comment by wenottingham** [comment]
The short-term way to use an inventory plugin is to place the configuration file for the plugin in source control in an AWX project, and point the inventory source at that.

**Comment by loganbest** [comment]
The main blocker to bringing it natively is that the inventory plugin structure is different than with Ansible. The same plugin can be used but just needs to be modified slightly to adhere to the different format. Boggles my mind why all native ansible inventory plugins aren't automatically usable in AWX really.

**Comment by AlanCoding** [comment]
Replacing this issue with https://github.com/ansible/awx/issues/4306

Basically, allow users to enter the plugin configuration without having to go through source control. Let me know if I have misunderstood anything.

**Comment by emil-palm** [comment]
@wenottingham 
> The short-term way to use an inventory plugin is to place the configuration file for the plugin in source control in an AWX project, and point the inventory source at that.

Can you provide some more insight into this solution, i tried to put my yaml config file in my repo and point the inventory to that file but that just failed with 

```ansible-inventory 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /var/lib/awx/projects/_8__test/ansible/hosts/hosts as it did not pass it's verify_file() method
script declined parsing /var/lib/awx/projects/_8__test/ansible/hosts/hosts as it did not pass it's verify_file() method
auto declined parsing /var/lib/awx/projects/_8__test/ansible/hosts/hosts as it did not pass it's verify_file() method
toml declined parsing /var/lib/awx/projects/_8__test/ansible/hosts/hosts as it did not pass it's verify_file() method
 [WARNING]:  * Failed to parse
/var/lib/awx/projects/_8__test/ansible/hosts/hosts with yaml plugin: Plugin
configuration YAML file, not YAML inventory
  File "/usr/lib/python2.7/site-packages/ansible/inventory/manager.py", line 267, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/inventory/yaml.py", line 112, in parse
    raise AnsibleParserError('Plugin configuration YAML file, not YAML inventory')
 [WARNING]:  * Failed to parse
/var/lib/awx/projects/_8__test/ansible/hosts/hosts with ini plugin: Invalid
host pattern 'plugin:' supplied, ending in ':' is not allowed, this character
is reserved to provide a port.
  File "/usr/lib/python2.7/site-packages/ansible/inventory/manager.py", line 267, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/inventory/ini.py", line 138, in parse
    raise AnsibleParserError(e)
 [WARNING]: Unable to parse /var/lib/awx/projects/_8__test/ansible/hosts/hosts
as an inventory source
ERROR! No inventory was parsed, please check your configuration and options.```

**Comment by AlanCoding** [comment]
> auto declined parsing /var/lib/awx/projects/_8__test/ansible/hosts/hosts as it did not pass it's verify_file() method

The `verify_file` method mentioned:

https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/auto.py#L34-L37

Sounds like this error is telling me that you gave it a file that did not end in .yml/.yaml, as the [netbox inventory plugin](https://docs.ansible.com/ansible/latest/plugins/inventory/netbox.html) documents

> netbox_inventory.yml file in YAML format

**Comment by daswars** [comment]
awx only finds the file if it is called hosts.

I tried it with the following hostfile names:
hosts - awx finds the file
hosts.yaml - awx does not find the file
hosts.yml - awx does not find the file
netbox_inventory.yml - awx doesn't find the file
inventories/hosts - awx finds the file
inventories/hosts.yaml - awx doesn't find the file
inventories/hosts.yml - awx does not find the file
inventories/netbox_inventory.yml - awx does not find the file

Sourced from a Project

`    2.315 INFO     Updating inventory 3: netbox
    2.750 INFO     Reading Ansible inventory source: /var/lib/awx/projects/_8__ansible_playbook_deploy_v2/hosts
    2.752 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    2.752 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    2.752 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python2.7/site-packages:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==6.1.0.0', 'console_scripts', 'awx-manage')()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 142, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1148, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1038, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 214, in load
    return self.command_to_json(base_args + ['--list'])
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 197, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
ansible-inventory 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /var/lib/awx/projects/_8__ansible_playbook_deploy_v2/hosts as it did not pass it's verify_file() method
script declined parsing /var/lib/awx/projects/_8__ansible_playbook_deploy_v2/hosts as it did not pass it's verify_file() method
auto declined parsing /var/lib/awx/projects/_8__ansible_playbook_deploy_v2/hosts as it did not pass it's verify_file() method
toml declined parsing /var/lib/awx/projects/_8__ansible_playbook_deploy_v2/hosts as it did not pass it's verify_file() method
 [WARNING]:  * Failed to parse
/var/lib/awx/projects/_8__ansible_playbook_deploy_v2/hosts with yaml plugin:
Plugin configuration YAML file, not YAML inventory
  File "/usr/lib/python2.7/site-packages/ansible/inventory/manager.py", line 268, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/inventory/yaml.py", line 112, in parse
    raise AnsibleParserError('Plugin configuration YAML file, not YAML inventory')
 [WARNING]:  * Failed to parse
/var/lib/awx/projects/_8__ansible_playbook_deploy_v2/hosts with ini plugin:
Invalid host pattern '---' supplied, '---' is normally a sign this is a YAML
file.
  File "/usr/lib/python2.7/site-packages/ansible/inventory/manager.py", line 268, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/inventory/ini.py", line 138, in parse
    raise AnsibleParserError(e)
 [WARNING]: Unable to parse
/var/lib/awx/projects/_8__ansible_playbook_deploy_v2/hosts as an inventory
source
ERROR! No inventory was parsed, please check your configuration and options.`

**Comment by sakbhav** [comment]
I wrote a small inventory script to use netbox as inventory:

https://github.com/sakbhav/netbox-awx

**Comment by jdrew82** [comment]
> I wrote a small inventory script to use netbox as inventory:
> 
> https://github.com/sakbhav/netbox-awx

I don't see this script working as it appears you never actually populate the devices list. I see you also have a hosts_list variable that I'm assuming is a duplicate variable? I updated script to use that and it appears to be working now outside of the tenants portion crashing it. Works when commented out though. I do see that facts for the hosts don't appear to be populated though. Good start for the script but needs some tweaking.

**Comment by sakbhav** [comment]
Thanks for reporting @jdrew82 !  It was my bad.  I weeded out some of my organisation specific code to filter out hosts based on specific tags.  I think this could be useful for everyone, so I have added it back.
I have fixed the code and added some additional checks for null values.  Please let me know if its working for you now or not.

**Comment by jdrew82** [comment]
Much better now! I'm able to have everything uncommented and it appears to populate more info than before. I've started tweaking it a bit to pull more information from Netbox for Ansible but it's a good start. Very much appreciated!

**Comment by sakbhav** [comment]
Glad to know it worked for you.  Please feel free to raise a Pull Request if you find something worth adding to this script for general usecase.

**Comment by zedr** [comment]
I've written a new example script from scratch, if anyone needs it: https://gist.github.com/zedr/6979ab2fc49fe13e752a9896d6195c4d

**Comment by AndrewSav** [comment]
@zedr what's the plan with regards to this when custom scripts are removed in the next version of awx?

**Comment by AlanCoding** [comment]
The forward-looking way to use the netbox inventory would be to use https://galaxy.ansible.com/netbox/netbox

You can create a project with your inventory file and put a file `collections/requirements.yml` that lists `netbox.netbox` in a way that `ansible-galaxy` CLI can understand. That should work now.

With execution environments, #8030, we could talk about an additional feature to allow direct input of the inventory config, where the collection is sourced from the container image.

**Comment by zedr** [comment]
I've refashioned the Inventory Script into a proper Ansible Inventory Plugin: https://github.com/zedr/simple_netbox_inventory_plugin

**Comment by joubbi** [comment]
I found this bug report when trying to get Tower use NetBox as an inventory.
I took @zedr (Thank you!) code example from above and made a few improvements to it. It can be found here: https://github.com/joubbi/towerbox
Just in case someone else comes here for the same purpose.

**Comment by TheeMadWhiteHatter** [comment]
I am having issues getting Netbox to populate the inventory of AWX. I have tried adding collections/requirements.yml listing netbox.netbox and netbox_inventory.yml file and creating a project with the inventory file like @AlanCoding suggested but only getting the same errors as mrevilme was. 

  ansible-inventory [core 2.11.6.post0] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
host_list declined parsing /bin/[ as it did not pass its verify_file() method
auto declined parsing /bin/[ as it did not pass its verify_file() method
Parsed /bin/[ inventory source with ini plugin
host_list declined parsing /bin/addr2line as it did not pass its verify_file() method
auto declined parsing /bin/addr2line as it did not pass its verify_file() method
toml declined parsing /bin/addr2line as it did not pass its verify_file() method
[WARNING]:  * Failed to parse /bin/addr2line with script plugin: Inventory
script (/bin/addr2line) had an execution error: /bin/addr2line: unrecognized
option '--list' Usage: /bin/addr2line [option(s)] [addr(s)]  Convert addresses
into line number/file name pairs.  If no addresses are specified on the command

From cli I can run ansible-inventory -i inventory.yml and pull all the devices in fine, with the same config in that inventory file as is in what AWX is using. @joubbi I attempted to run the script you provided but ended up with similar errors
![image](https://user-images.githubusercontent.com/73369617/141384228-f9fc7755-bef3-429a-a8db-931395f066ca.png)

Am I missing something?

**Comment by zedr** [comment]
@ogowen45 what is `addr2line`? It's being called as the inventory script, but it cannot handle the argument `--list`.

**Comment by ogowen45** [comment]
@zedr First, thank you for your response. I found that when I was calling the inventory source I had a space in the file now it is as follows 
![image](https://user-images.githubusercontent.com/73369617/141494874-43c3b86b-bc6e-435c-89f4-27f176bf7f78.png)
 The netbox_inventory.yml just contains (but with token and api_endpoint set)
 ---
plugin: netbox.netbox.nb_inventory
api_endpoint: 
token: 
group_by:
 - device_roles
 - sites
validate_certs: false

Then my collections/requirements.yml only contains
---
collections:
 - netbox.netbox


After making the change in the inventory source to be just /netbox_inventory.yml the error I receive now is:
![image](https://user-images.githubusercontent.com/73369617/141496254-0fb7d5a4-4273-4be7-9212-8ddacbfdd7df.png)
Says that it is not able to parse as inventory

Thank you again for your help, fairly new to Ansible in general. Kinda got plunged into

**Comment by TheeMadWhiteHatter** [comment]
It had to do with there being a space in the file location in the inventory source, as well as there was no ansible.cfg file in the repo. 

After, I made an ansible.cfg file for repository that is as follows 
![image](https://user-images.githubusercontent.com/73369617/141514365-2926f8a3-16bc-49e5-921a-c0f2125b9a03.png)
 Now getting error
![image](https://user-images.githubusercontent.com/73369617/141535350-95055617-9e92-44c8-a1d2-94d7954f7592.png)

![image](https://user-images.githubusercontent.com/73369617/141534825-049fa1b4-c990-4c6f-b307-446e2a26a577.png)

**Comment by AlanCoding** [comment]
I think you basically need to create an execution environment with the collection and its dependencies (like jsonschema). This is the problem they were intended to solve.
