### ISSUE TITLE
SCM inventory not deleted when SCM changes

### ISSUE THREAD

**Issue by cdeniro** [ansible/awx#4155]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Hosts which are deleted from SCM inventory are not deleted from AWX

##### ENVIRONMENT
* AWX version: AWX 3.0.1.0
* AWX install method:  docker on linux
* Ansible version:  2.7.7
* Operating System: ubuntu 
* Web Browser: firefox

##### STEPS TO REPRODUCE

I have created SCM inventory using Git
Inventory is added and synced correctly. 
New hosts added to SCM are added to AWX
Hosts (Nor groups) deleted in SCM are not removed from AWX

##### EXPECTED RESULTS

Inventory would be in sync with SCM

##### ACTUAL RESULTS

Hosts (Nor groups) deleted in SCM are not removed from AWX

##### ADDITIONAL INFORMATION

{
    "count": 30,
    "next": "/api/v2/inventory_updates/?page=2",
    "previous": null,
    "results": [
        {
            "id": 374,
            "type": "inventory_update",
            "url": "/api/v2/inventory_updates/374/",
            "related": {
                "unified_job_template": "/api/v2/inventory_sources/7/",
                "stdout": "/api/v2/inventory_updates/374/stdout/",
                "inventory_source": "/api/v2/inventory_sources/7/",
                "cancel": "/api/v2/inventory_updates/374/cancel/",
                "notifications": "/api/v2/inventory_updates/374/notifications/",
                "events": "/api/v2/inventory_updates/374/events/",
                "source_project_update": "/api/v2/project_updates/375/",
                "inventory": "/api/v2/inventories/2/",
                "credentials": "/api/v2/inventory_updates/374/credentials/"
            },
            "summary_fields": {
                "inventory": {
                    "id": 2,
                    "name": "Juniper Ansible Inventory",
                    "description": "",
                    "has_active_failures": true,
                    "total_hosts": 574,
                    "hosts_with_active_failures": 2,
                    "total_groups": 549,
                    "groups_with_active_failures": 5,
                    "has_inventory_sources": true,
                    "total_inventory_sources": 1,
                    "inventory_sources_with_failures": 0,
                    "organization_id": 1,
                    "kind": ""
                },
                "unified_job_template": {
                    "id": 7,
                    "name": "Ansible Git",
                    "description": "",
                    "unified_job_type": "inventory_update"
                },
                "inventory_source": {
                    "source": "scm",
                    "last_updated": "2019-06-24T16:48:12.257104Z",
                    "status": "successful"
                },
                "instance_group": {
                    "name": "tower",
                    "id": 1
                },
                "user_capabilities": {
                    "delete": true,
                    "start": true
                }
            },
            "created": "2019-06-22T16:00:19.886462Z",
            "modified": "2019-06-22T16:00:22.804035Z",
            "name": "Juniper Ansible Inventory - Ansible Git",
            "description": "",
            "unified_job_template": 7,
            "launch_type": "dependency",
            "status": "successful",
            "failed": false,
            "started": "2019-06-22T16:00:22.942035Z",
            "finished": "2019-06-22T16:00:42.318023Z",
            "elapsed": 19.376,
            "job_explanation": "",
            "execution_node": "awx",
            "source": "scm",
            "source_path": "Inventory",
            "source_script": null,
            "source_vars": "",
            "credential": null,
            "source_regions": "",
            "instance_filters": "",
            "group_by": "",
            "overwrite": false,
            "overwrite_vars": false,
            "timeout": 0,
            "verbosity": 1,
            "inventory": 2,
            "inventory_source": 7,
            "license_error": false,
            "source_project_update": 375,
            "custom_virtualenv": "/var/lib/awx/venv/ansible"
        },

**Comment by AlanCoding** [comment]
> "overwrite": false,

If you change this field to `true`, does it behave the way you want?

**Comment by cdeniro** [comment]
@AlanCoding where do I make this change?

**Comment by okelet** [comment]
@cdeniro 

![image](https://user-images.githubusercontent.com/108803/60091883-e5799980-9745-11e9-8af4-0965bf4c06a8.png)

**Comment by cdeniro** [comment]
@okelet This resolved the issue. The configuration is confusing IMO. Update on launch from a SCM source infers that the hosts will "refresh" each time a job is launched but this only adds hosts and does not actually sync the hosts.
