### ISSUE TITLE
Inventory icons are shifted in weird way in 5.0.0

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#4158]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 5.0.0
* AWX install method: docker on linux
* Ansible version:  X.Y.Z
* Operating System: Debian
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Just open inventory list

##### EXPECTED RESULTS
<img width="633" alt="image" src="https://user-images.githubusercontent.com/1560121/60086891-35536300-973c-11e9-9d78-c6fecc571db1.png">

##### ACTUAL RESULTS
<img width="669" alt="image" src="https://user-images.githubusercontent.com/1560121/60086831-1ce34880-973c-11e9-9ce3-190bea7fe859.png">

**Comment by ryanpetrello** [comment]
@benapetr can you share your version of Firefox?

**Comment by benapetr** [comment]
67.0.4 (64-bit) on MacOS 10.14.4

**Comment by geauxvirtual** [comment]
Seen on 67.0.4 on Windows as well.

**Comment by geauxvirtual** [comment]
I've got a Linux jump host with an older version of Firefox, 60.7.1esr (64bit) where the issue **is not** seen.

**Comment by benapetr** [comment]
Still happening in 6.1

**Comment by AlexSCorey** [comment]
This issue is no longer valid n the new UI.
