### ISSUE TITLE
slow job output AWX 4+

### ISSUE THREAD

**Issue by MathijsVanWilligen** [ansible/awx#4159]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After upgrade from 2.0.1 to 4.0.0 we had very slow job output, after serveal days we must wait for about 1-2 days to retreive the output.
Also after an upgrade from 4.0.0 to 5.0.0 there was no improvement on this.
After some resource (we used azure psql Paas service) we find out that a local PSQL sever (wich can handle more load) solved this.
At version 2.0.1 we have no issues with this.

##### ENVIRONMENT
* AWX version: 5.0.0
* AWX install method: kubernetes
* Ansible version:  2.8.1
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

we noticed that awx4+ requires significantly more PSQL write IO than AWX2. This has propably something to do with the changed logging infrastructure reference HERE. Is this uptake in write IO by design / could this be optimised with bulk updates/are there best practices voor PSQL sizing?

##### EXPECTED RESULTS

AWX should work with powerless PSQL servers

##### ACTUAL RESULTS

After switching to an more powerfull PSQL server the job output worked well again.
But without this workaround the job output is very slow.

##### ADDITIONAL INFORMATION

link to other issue for some resource https://github.com/ansible/awx/issues/3761

**Comment by ryanpetrello** [comment]
For optimal performance, we generally recommend a database server with the following specs:

- 20 GB of dedicated hard disk space for nodes containing a database (150 GB+ recommended)
- The storage volume should be rated for a high baseline IOPS (1000 or more.)

Depending on _how much_ output your playbooks have, write I/O *can* be high and storage with lower IOPS _will_ see the type of slow down in job output you've described.

This document is specific to Red Hat Ansible Tower, but the requirements it outlines are also generally applicable to AWX as well:

https://docs.ansible.com/ansible-tower/latest/html/installandreference/requirements_refguide.html

> This has propably something to do with the changed logging infrastructure reference HERE.

Can elaborate on what "HERE" is?

**Comment by MathijsVanWilligen** [comment]
At first, sorry for the late replay.
Thank you very much for your answer, we will test this out with a higher baseline IOPS, our playbooks has a lot of output.

"Can elaborate on what "HERE" is?", we thought that the logging infrastructure has been changed from awx2 >> awx4.
