### ISSUE TITLE
The Scale up deployment task is failing.

### ISSUE THREAD

**Issue by ashokdevop** [ansible/awx#4160]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by ashokdevop** [comment]
Hi Team,

The The Scale up deployment task is failing. getting below error please help me on this.

TASK [kubernetes : Scale up deployment] ******************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "kubectl -n 2304378531 scale sts awx --replicas=1\n kubectl -n 2304378531 scale sts awx --replicas=1", "delta": "0:00:03.752777", "end": "2019-06-25 16:32:43.161765", "msg": "non-zero return code", "rc": 1, "start": "2019-06-25 16:32:39.408988", "stderr": "Error from server (NotFound): statefulsets.apps \"awx\" not found\nError from server (NotFound): statefulsets.apps \"awx\" not found", "stderr_lines": ["Error from server (NotFound): statefulsets.apps \"awx\" not found", "Error from server (NotFound): statefulsets.apps \"awx\" not found"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/Users/ashok.g/Downloads/awx-devel/installer/install.retry

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=21   changed=9    unreachable=0    failed=1

**Comment by ryanpetrello** [comment]
@capslk,

This issue tracker is for tracking bugs and enhancements to awx itself.  If you need help troubleshooting an awx install, you might have better luck in our IRC room or the mailing list:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
