### ISSUE TITLE
Quoted "event_display" breaks "stdout" view

### ISSUE THREAD

**Issue by bkmeneguello** [ansible/awx#4162]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Quoted "event_display" breaks "stdout" view

##### ENVIRONMENT
* AWX version: 5.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.1
* Operating System: CentOS
* Web Browser: Firefox 67.0.4

##### STEPS TO REPRODUCE

* Create a playbook with tasks having quotes, ex: `Some "task"`
* Run this playbook
* Check Job "stdout" view now have some `Event ID: 4468" aw-tip-placement="top">` rows

##### EXPECTED RESULTS

The layout should not be affected by message content. The HTML entities should be converted.

##### ACTUAL RESULTS

The layout breaks and events aren't usable (cannot be clicked)

##### ADDITIONAL INFORMATION

The [JobRenderService#createToolTip method in render.service.js](https://github.com/ansible/awx/blob/devel/awx/ui/client/features/output/render.service.js#L435) must convert HTML entities when building the response.

**Comment by ryanpetrello** [comment]
@bkmeneguello,

Can you share a playbook that exhibits this behavior?

**Comment by jakemcdermott** [comment]
confirmed - reproduced with https://github.com/jakemcdermott/ansible-playbooks/blob/master/ping.yml

![Screenshot from 2019-06-25 21-10-43](https://user-images.githubusercontent.com/9753817/60143781-dfa7a680-978d-11e9-93cc-30bcbfc80dcb.png)

introduced in april sometime.

**Comment by ryanpetrello** [comment]
Hey @bkmeneguello,

Thanks for reporting this.  It should be fixed by this change (which will be in the next version of AWX):
https://github.com/ansible/awx/pull/4313

**Comment by dsesami** [comment]
Verified on a playbooks with quoted tasks and non-quoted tasks (including ping.yml) that stdout appears normal and does not break.
