### ISSUE TITLE
add_host module not working with any win_* module in AWX using in memory inventory

### ISSUE THREAD

**Issue by AechLyons** [ansible/awx#4172]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I have a playbook that creates a windows VM and then add's the results to an in memory inventory to allow me to execute other commands (in this case I want to join it to the domain and configure IIS settings). I got this working on the Linux templates for CentOS and Ubuntu but for windows I cant get any of the win modules to work. I created a small playbook outside of AWX to confirm I could get win_ping to work and I get the response back ('pong').

##### ENVIRONMENT
* AWX version: 4.0.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.9
* Operating System: CentOS
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE
Job Template in AWX

"- name: Connect to vSphere host
hosts: localhost
gather_facts: true
connection: local

tasks:

name: Survey Answers
include_vars: Vars.yml

name: Create VM from Template
vmware_guest:
hostname: X.X.X.X
username: "{{ vcenter_user }}"
password: "{{ vcenter_pass }}"
validate_certs: no
datacenter: ***********
name: "{{ name }}"
folder: "{{ Folder }}"
template: Windows Server 2019 (Updates 2018-12-19)
disk:
- size_gb: "{{ disk }}"
type: thin
datastore: "{{ datastore }}"
networks:
- name: "{{ network }}"
hardware:
memory_mb: "{{ mem }}"
num_cpus: "{{ cpus }}"
state: poweredon
wait_for_ip_address: yes
register: new_vm

add_host: hostname="{{ name }}"
ansible_host="{{ new_vm.instance.hw_eth0.ipaddresses[0] }}"
groups=newguest
ansible_user=ansible
ansible_password=**********
ansible_port=5986
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore

name: Configure windows
hosts: newguest
gather_facts: no

tasks:

name: Need Name Variable
include_vars: Vars.yml

name: ping
win_ping:"

##### EXPECTED RESULTS

When  Iru na small playbook specially for the win_ping module from commandline 

"ansible-playbook win_ping.yml
[DEPRECATION WARNING]: DEFAULT_SUDO_USER option, In favor of Ansible Become, which is a generic framework. See become_user. , use become
instead. This feature will be removed in version 2.8. Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
10.0.2.186 | SUCCESS => {
"changed": false,
"ping": "pong""

##### ACTUAL RESULTS

"{

"msg": "Unexpected failure during module execution.",

"exception": "Traceback (most recent call last):\n File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 144, in run\n res = self._execute()\n File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 648, in _execute\n result = self._handler.run(task_vars=variables)\n File "/usr/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 46, in run\n result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))\n File "/usr/lib/python2.7/site-packages/ansible/plugins/action/init.py", line 917, in _execute_module\n res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)\n File "/usr/lib/python2.7/site-packages/ansible/plugins/action/init.py", line 1042, in _low_level_execute_command\n cmd = self._connection.become.build_become_command(cmd, self._connection._shell)\n File "/usr/lib/python2.7/site-packages/ansible/plugins/become/sudo.py", line 104, in build_become_command\n return ' '.join([becomecmd, flags, prompt, user, self._build_success_command(cmd, shell)])\n File "/usr/lib/python2.7/site-packages/ansible/plugins/become/init.py", line 52, in _build_success_command\n cmd = shlex_quote('%s %s %s %s' % (shell.ECHO, self.success, shell.COMMAND_SEP, cmd))\nAttributeError: 'ShellModule' object has no attribute 'ECHO'\n",

"_ansible_no_log": false,

"stdout": ""

}"

##### ADDITIONAL INFORMATION

This playbook works to deploy other Linux OS's and I'm able to run commands with the in-memory inventory successfully.  It just appears that the win modules dont work.  I have tried both win_ping and win_domain_membership and both fail in the exact same way.  win_ping works outside of AWX so I'm thinking there is an issue with win modules and in memory inventories.  I am no programmer and I'm still learning AWX/Ansible.

**Comment by ryanpetrello** [comment]
@AechLyons,

This issue tracker is used for tracking bugs and feature enhancements to AWX.  Give our mailing list or IRC room a try - there's lots of folks who follow along there and are willing to help troubleshoot:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
