### ISSUE TITLE
Inventory source credentials not saved

### ISSUE THREAD

**Issue by ggiinnoo** [ansible/awx#4173]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 5.0.0
* AWX install method: docker
* Ansible version:  2.8.1
* Operating System: CentOS Linux release 7.6.1810 (Core)
* Web Browser: Google Chrome 75.0.3770.100

##### STEPS TO REPRODUCE

Install awx using the installation guide using docker.
Add openstack credentials.

Add inventory source openstack. When saving the Credential field, it goes empty.

##### EXPECTED RESULTS

The field is being saved and i can start the sync.

##### ACTUAL RESULTS

Field 'Credential' is empty and sync fails

##### ADDITIONAL INFORMATION

Credential openstack:
![Credentials](https://user-images.githubusercontent.com/3601832/60253887-31a31600-98cd-11e9-8d10-ee68c2fe5013.png)

Source (after hitting save):
![Source](https://user-images.githubusercontent.com/3601832/60254132-a37b5f80-98cd-11e9-84f5-a76c32d622be.png)

![partial_log](https://user-images.githubusercontent.com/3601832/60254397-33b9a480-98ce-11e9-9e38-28fc91da0428.png)

**Comment by ryanpetrello** [comment]
I suspect this is a duplicate of https://github.com/ansible/awx/issues/4059 which has been fixed in `devel` (via https://github.com/ansible/awx/pull/4074)

**Comment by ggiinnoo** [comment]
Looks like it yeah.
The error in the last picture was my own fault :) i forgot to enter a domain name in the openstack credentials page.

If people are using the openstack V3 api. It is necessary to fill this in. You can enter "Default" in the field and all will be fine.
