### ISSUE TITLE
Support an RPM-based deployment of AWX

### ISSUE THREAD

**Issue by akesterton** [ansible/awx#419]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - Installer

##### SUMMARY

I am working with users who do not use containers or OpenShift and want to work with AWX. Can we support an RPM-based packaging and deployment method as well as the current deployment method. This will allow more people to use AWX.

**Comment by stokkie90** [comment]
@akesterton, A already found this project: https://github.com/subuk/awx-rpm. 

In my experience this was not a fully working solution. Also it dit not really perform well.  I created an ansible playbook to deploy it outside docker. It's working but still having some minor issues. This solution is performing well (supervisord)

**Comment by matburt** [comment]
We have no plans to do this currently.

**Comment by MrMEEE** [comment]
@stokkie90 I have created a RPM repository, that I think works pretty well, if anyone is interested

https://github.com/MrMEEE/awx-build/blob/master/installguide

**Comment by MrMEEE** [comment]
Hi Guys..

It's been another year.. The RPMs I'm currently making are becoming more and more stable and I was wondering if you could be interested in doing a joined effort, to let an RPM based installation be a officially support install method?

**Comment by MrMEEE** [comment]
@matburt

**Comment by RunicBean** [comment]
@matburt 
Can you please provide one RPM based solution under official version?

**Comment by MrMEEE** [comment]
https://github.com/ansible/awx/issues/3542

**Comment by sspreitzer** [comment]
@matburt Can you please provide a reasoning for the public and opensource community, why the AWX project is not releasing RPMs. Despite, Red Hat as an OpenSource company does provide RPMs of AWX in form of Ansible Tower to its customers?
Why do you or Red Hat not provide the Ansible Tower RPM installer mechanism as OpenSource? Red Hats tenor is OpenSource, yet for this part exists silence. Thank you

**Comment by wenottingham** [comment]
You can find the AWX FAQ from the time of the initial release here: https://www.ansible.com/products/awx-project/faq
Supporting an RPM-based installation of AWX is not part of those goals, especially as we move to more container-native deployment and container-first playbook execution (see https://groups.google.com/d/msgid/awx-project/b71a5c96-13f0-4d69-aade-83aaa124b094n%40googlegroups.com).

As for Red Hat, Red Hat does many things and provides assorted deliverables and services for the customers of its products and platforms that Red Hat-sponsored projects may choose not to do for users of upstream projects.
