### ISSUE TITLE
FEATURE: Job returns

### ISSUE THREAD

**Issue by resmo** [ansible/awx#4191]
##### ISSUE TYPE
feature request

##### SUMMARY
Integrate job custom results (key, values as json) back to the job launcher.

Think of a job creates a VM. There is not integrated way to return the IP of the new created VM back to the job launcher. This would be especially useful when pragmatically launching jobs by the API, e.g. by openshift ansible service broker.

**Comment by wenottingham** [comment]
This is what `set_stats` is for. Does this not work for you?

**Comment by resmo** [comment]
Whow, this seems to be the best kept secret! Exactly what I am looking for. Thanks!
