### ISSUE TITLE
SSH Connection Timeout after 10 seconds instead of value defined in ansible.cfg

### ISSUE THREAD

**Issue by Moumoutaru** [ansible/awx#4193]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX frequently times out trying to connect to hosts. This seems to change in relation to how many hosts we are trying to operate on at any given time. Looked into increasing SSH connection time as that should resolve it but the path to doing so isn't clear.

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker on linux
* Operating System: CentOS 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Seeing as this issue appears to be related to the default connection timeout, steps to reproduce don't seem necessary.

##### EXPECTED RESULTS

I'd expect AWX to pick up on the config values defined in ansible.cfg or provide a clearer way to override some default settings AWX is assuming.

##### ACTUAL RESULTS

Normal Output:
```
TASK [Gathering Facts] *********************************************************
Monday 01 July 2019  12:44:00 +0000 (0:00:00.209)       0:00:02.145 *********** 
fatal: [host1.thing.tld]: UNREACHABLE! => {"changed": false, "msg": "Connection timed out.", "unreachable": true}
fatal: [host2.thing.tld]: UNREACHABLE! => {"changed": false, "msg": "Connection timed out.", "unreachable": true}
```
WINRM Debug Output:
```
[task 8381] 12:59:19.553673 D mitogen: Context(0, None).call_service_async(u'ansible_mitogen.services.ContextService', u'get', {'stack': [{u'method': u'ssh', u'kwargs': {u'username': u'username@domain.tld, u'check_host_keys': u'ignore', u'compression': True, u'ssh_debug_level': None, u'hostname': u'host1.thing.tld', u'identities_only': False, u'identity_file': None, u'connect_timeout': 10, u'python_path': [u'/usr/bin/python'], u'ssh_path': u'ssh', u'password': [secret], u'port': 22, u'ssh_args': [u'-o', u'ForwardAgent=yes']}}, {u'enable_lru': True, u'method': u'sudo', u'kwargs': {u'username': u'root', u'sudo_path': None, u'python_path': [u'/usr/bin/python'], u'password': None, u'sudo_args': [u'-H', u'-S', u'-n'], u'connect_timeout': 10}}]})
```

**Comment by Moumoutaru** [comment]
Seen other people mention this as well:

https://groups.google.com/forum/#!topic/awx-project/hvFM6OOLFB4

**Comment by Moumoutaru** [comment]
For those still trying to solve this, editing /etc/tower/setting.py and adding the following to the bottom works:

```
AWX_TASK_ENV['ANSIBLE_TIMEOUT'] = '120'
```

This should be documented better.

**Comment by ghjm** [comment]
Looks like we have a solution.  Closing issue.
