### ISSUE TITLE
Nginx redirect doesn't respect host to container port mapping

### ISSUE THREAD

**Issue by carbonin** [ansible/awx#420]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

The the nginx redirect which adds a trailing `/` to URLs without one issues a 301 with a new location which specifies the port which nginx is bound to *inside* the container, not the one my browser can reach.

##### ENVIRONMENT

* AWX version: devel @ bcd2a8f
* AWX install method: docker on linux
* Operating System: Fedora 25
* Web Browser: `curl`

##### STEPS TO REPRODUCE

```bash
$ cd installer
$ ansible-playbook -i inventory install.yml

... wait for UI to become accessible

$ curl -v localhost/api/v1
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 80 (#0)
> GET /api/v1 HTTP/1.1
> Host: localhost
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.10.2
< Date: Thu, 12 Oct 2017 21:01:59 GMT
< Content-Type: text/html
< Content-Length: 185
< Location: http://localhost:8052/api/v1/
< Connection: keep-alive
< Strict-Transport-Security: max-age=15768000
< 
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.2</center>
</body>
</html>
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

##### EXPECTED RESULTS

I would expect `Location: http://localhost:8052/api/v1/` to read `Location: http://localhost/api/v1/`

**Comment by arnoSCC** [comment]
Confirmed this bug and the fix with a local build of the images. 
`Before:

[arno@forgedoc test]$ curl -v http://172.112.11.202/api/v1/organizations
* About to connect() to 172.112.11.202 port 80 (#0)
*   Trying 172.112.11.202...
* Connected to 172.112.11.202 (172.112.11.202) port 80 (#0)
> GET /api/v1/organizations HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 172.112.11.202
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.10.2
< Date: Fri, 13 Oct 2017 12:01:18 GMT
< Content-Type: text/html
< Content-Length: 185
< Location: http://172.112.11.202:8052/api/v1/organizations/
< Connection: keep-alive
< Strict-Transport-Security: max-age=15768000
<
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.2</center>
</body>
</html>
* Connection #0 to host 172.112.11.202 left intact

After:

[arno@forgedoc test]$ curl -v http://172.112.11.202/api/v1/organizations
* About to connect() to 172.112.11.202 port 80 (#0)
*   Trying 172.112.11.202...
* Connected to 172.112.11.202 (172.112.11.202) port 80 (#0)
> GET /api/v1/organizations HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 172.112.11.202
> Accept: */*
>
< HTTP/1.1 301 MOVED PERMANENTLY
< Server: nginx/1.10.2
< Date: Fri, 13 Oct 2017 13:21:57 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept-Language, Cookie
< Location: http://172.112.11.202/api/v1/organizations/
< Content-Language: en
< Strict-Transport-Security: max-age=15768000
<
* Connection #0 to host 172.112.11.202 left intact
`

**Comment by n-Arno** [comment]
Confirmed this bug and fix using locally built images:

```
Before:

[arno@forgedoc test]$ curl -v http://172.112.11.202/api/v1/organizations
* About to connect() to 172.112.11.202 port 80 (#0)
*   Trying 172.112.11.202...
* Connected to 172.112.11.202 (172.112.11.202) port 80 (#0)
> GET /api/v1/organizations HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 172.112.11.202
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.10.2
< Date: Fri, 13 Oct 2017 12:01:18 GMT
< Content-Type: text/html
< Content-Length: 185
< Location: http://172.112.11.202:8052/api/v1/organizations/
< Connection: keep-alive
< Strict-Transport-Security: max-age=15768000
<
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.2</center>
</body>
</html>
* Connection #0 to host 172.112.11.202 left intact

After:

[arno@forgedoc test]$ curl -v http://172.112.11.202/api/v1/organizations
* About to connect() to 172.112.11.202 port 80 (#0)
*   Trying 172.112.11.202...
* Connected to 172.112.11.202 (172.112.11.202) port 80 (#0)
> GET /api/v1/organizations HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 172.112.11.202
> Accept: */*
>
< HTTP/1.1 301 MOVED PERMANENTLY
< Server: nginx/1.10.2
< Date: Fri, 13 Oct 2017 13:21:57 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept-Language, Cookie
< Location: http://172.112.11.202/api/v1/organizations/
< Content-Language: en
< Strict-Transport-Security: max-age=15768000
<
* Connection #0 to host 172.112.11.202 left intact
```

**Comment by matburt** [comment]
This is definitely a major problem that is on my radar, just haven't had a chance to get around to it yet if someone wants to take a stab at it.
