### ISSUE TITLE
Tooltip for Chips

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#4202]
When the text of a chip is extra long we want to have a tooltip that shows the entirety of the text on hover.  
![Screen Shot 2019-06-24 at 3 25 02 PM](https://user-images.githubusercontent.com/39280967/60046183-b6efb600-9694-11e9-8206-c8438292c97c.png)

**Comment by AlexSCorey** [comment]
I think that Pattern Fly has a prop that solves this problem.  It might be that we just want to use that prop (`isOverflowChip`) for this in places where we use `Chip`. https://patternfly-react.surge.sh/patternfly-4/components/chipgroup/

**Comment by mabashian** [comment]
Yea I see that prop listed but in the longchip example I don't see that prop being used and it does show a tooltip.  It would make sense for pf to handle this on their end I think.  I suspect we may get this for free when we next upgrade pf.

**Comment by AlexSCorey** [comment]
This issue was resolved.
