### ISSUE TITLE
Search implementation mega issue

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4203]
Search is one of the biggest pain points in the UI of classic AWX both from a developers pov and from a users pov.  The approach that we took there was to try to expose as much of power of django's query language to the user as possible.  This approach might be nice for a very small number of our users bug I suspect that it's too complicated for most.  I'd like to identify a list of minimum requirements wrt search and discuss how this feature should be exposed to the user.  

[Link to mockups](https://tower-mockups.testing.ansible.com/patternfly/orgs/orgs/)

1) Should we support `or` in addition to `and`?  Currently only `and` is supported
2) Should we allow users to search multiple terms at the same time like we currently do?  Probably not if the UX requires the user to select a field to search on
3) How should things like greater than, less than be handled?
4) Should we support `not`.  Currently we don't
5) Do we continue to use the `?search=` query param and if so, how does a user interact with that?  I would assume that they just type in a string and hit search?  If we use the field dropdown next to the search bar then I'm not sure how this will work.
6) How are spaces in search strings handled?
7) What special characters are supported?
8) Do we expose the ability to filter on related fields?  For example, on the old projects list, a user could do something like `organization.name:Default`.  Will that still be supported?
9) Can users edit a search term after the search has been performed?  This is a request we've heard before.
10) Do we support operators like `icontains`?  Currently a user can leverage this operator but it's certainly not intuitive unless they know the django query language.
11) If we expose search values in the URL what should happen when the user changes those params in the url?

I think it would be really nice if we could tell the user what type of input each field is looking for.  It can be confusing when a related field is expecting an integer (id) but the user types in a string.

We may need to take the inventory host filter into account as well.  That presents some unique problems since the syntax is slightly different (single param `host_filter` supports `or` keyword operator and parenthesis).  Searching facts is a whole can of worms and I predict it's going to be difficult to help the user out without some api help.  I'd actually be open to exploring host filtering as a completely separate feature.

There are probably any number of other issues/concerns that we'll want to discuss here.

**Comment by mabashian** [comment]
Some potentially relevant awx issues:

https://github.com/ansible/awx/issues/2817
https://github.com/ansible/awx/issues/2247
https://github.com/ansible/awx/issues/1520
https://github.com/ansible/awx/issues/1419
https://github.com/ansible/awx/issues/1351
https://github.com/ansible/awx/issues/589
https://github.com/ansible/awx/issues/402 (this is the "improve smart search" issue)
https://github.com/ansible/awx/issues/371

**Comment by mabashian** [comment]
@wenottingham this is likely relevant to your interests.  Search is easily one of the biggest question marks with this new project and I think it's going to require a lot of discussion to lock down what the requirements are.  If you have strong feelings about what the minimum requirements would be I'd be curious to hear about that.

**Comment by chrismeyersfsu** [comment]
I'm bias, but I would like an "advanced mode" where you can see the API generated query. This way, users can type the UI version of the query and see what comes out after it goes through the meat grinder. Also, an options for users to input the API version of the query themselves in the UI.

**Comment by mabashian** [comment]
Search is going to be tracked in a different location - closing.
