### ISSUE TITLE
Add support for social auth on login

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4204]
AWX currently supports social auth options such as Google and Github (there may be others).  You can see the documentation for that [here](https://docs.ansible.com/ansible-tower/latest/html/administration/social_auth.html).  Note that when these social auth options are enabled/configured a logo appears on the login modal.  Clicking that logo should redirect the user to the platform in question where the user will authenticate.  Upon authentication, a callback url will be hit and the user will be logged in.

@trahman73 afaik the patternfly react login component doesn't have support for these social auth buttons.  If you have ideas on where they should go/how they should function i'd be interested in hearing about that.

**Comment by trahman73** [comment]
@mabashian The React login component doesn't currently support social auth logins, but the PF4 core module does.

https://pf-next.com/components/login/examples-full/?component=Login

We can request the PF4 React Login dev to include support for social auths or we can build our own following the design from the above link. The latter might be more difficult as the login is a single page component.

**Comment by nixocio** [comment]
Social auth is listed here now - https://www.patternfly.org/v4/components/login-page/react/#props

**Comment by unlikelyzero** [comment]
covered in 5783
