### ISSUE TITLE
Track session timeout and prompt user to continue session when it's about to expire

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4205]
I'd be happy to discuss other UX designs to solve this problem but I do think we want to give the user the ability to extend their session when it's about to expire.  This would require the UI to do a couple of things:

1) We'll need to probably keep a timer running that gets updated with each api response to track how much time is left on a particular session.
2) When that timer gets down to some threshold (was 60 seconds in old awx) we prompt the user to extend their session.  
3) If the user does click to extend their session... ??? I'm actually not too sure how this currently works but I would assume a request needs to be made to the api which would inherently extend the session.
4) If the user does not extend their session, the UI should hit the logout endpoint(? maybe) and redirect the user to the login screen
5) In the past, we've shown a message to the user saying that their session expired.  If/when we have a generic message field on the pf login component we could put it there or we could just go to the login screen with no message

**Comment by jlmitch5** [comment]
As part of https://github.com/ansible/awx-pf/pull/156 401 authentication is checked based on an api response returning a 401 (instead of checking the cookie).  This works, but it does cause the UI to show the route before loading the login page for a split second.  There are a couple ways we can handle this:

- moving back to checking the cookie
- block rendering of the UI until the first api response is returned

The thing we need to be careful of is we do want the message that the user has been logged out to be population by the root dialog provider (which is why I had to move away from the check of api.isAuthenticated called from index.jsx)

We will also need to make sure other routes are not able to be accessed when the user is logged out.  There is currently an issue where trying to access `/#/foo` redirects the user to dashboard instead of login.

**Comment by mabashian** [comment]
Adding onto this issue something currently in awx-pf.  The `logged out` text on the login screen seems to be shown inconsistently.  I believe the expected behavior is that it should be shown after logout.  Currently it's being shown on load/refresh but not after logging out:

![logout](https://user-images.githubusercontent.com/9889020/56153186-8f3ced00-5f83-11e9-8b28-f2f0922753e5.gif)

@jlmitch5 is planning on addressing this as part of his work on this issue.

**Comment by keithjgrant** [comment]
Some miscellaneous thoughts while discussing #7210 (copied from slack):

>  I think we need the app to go through the login/auth validation logic before <Route>s  get mounted at or near the top level of the component hierarchy. That would only execute when the page is first opened/refreshed, since all routing afterwards happens through react-router
> Somewhere in that same logic, we could add a setTimeout or whatever to periodically confirm with the API that the session is still active
> By performing that check first, we would avoid what happens now: rendering most of a page before hitting a 401 error and flickering a bunch of rapidly changing UI on the screen

**Comment by jakemcdermott** [comment]
re: Login page behavior (showing a message for for idle logouts, etc: https://github.com/ansible/awx/issues/4205#issuecomment-483348031)

I've made a separate issue for this because I'd like to handle it separately and in a follow-up PR: https://github.com/ansible/awx/issues/8272

**Comment by jakemcdermott** [comment]
see: https://github.com/ansible/awx/pull/8250

**Comment by unlikelyzero** [comment]
@jakemcdermott we'd like to consider coverage for this in the closedsource tests

**Comment by unlikelyzero** [comment]
To close:
- Visual Test to cover this modal
- Network intercept to trigger this with a cy.clock
- Settings which modify this behavior are tested
- Tested manually
- Stubs added to closedsourcetests

Note: there is also a global config setting which would allow us to reduce the timeout from the default 5 minutes down to 61 seconds to make this test faster (please reapply old timeout when done :) )

**Comment by akus062381** [comment]
Make sure to test this on multiple pages, specifically, test on the following:
Dashboard default
Dashboard when there is a recurring job generating Websocket requests over and over. the session * should * keep restarting
Job Result Output page after a job is launched and completed- does timeout happen here?
Workflow Visualizer- it's a separate screen- does the session modal appear over this?
1 modal
1 wizard
Settings- general screen or editing job idle timeout- does it come up?

**Comment by akus062381** [comment]
Action items still needed to complete:

- Visual Test to cover this modal

- Network intercept to trigger this with a cy.clock

**Comment by akus062381** [comment]
visual test added
