### ISSUE TITLE
ux enhancements of lookups

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#4206]
mockups for instance groups (basic case implemented): https://tower-mockups.testing.ansible.com/patternfly/orgs/orgs-edit-instances/

![screen shot 2018-12-03 at 11 51 53 am](https://user-images.githubusercontent.com/1342624/49388398-dcfe3a80-f6f1-11e8-878a-69c5af8cdecd.png)

there are some particular tricky things about lookups that will need to be supported (if not in this particular case, elsewhere):

- if you type into the text field next to the search icon, it should periodically check with the api to see if the user has entered a valid item to add.  TBD for multi select (should enter create "tags"?)
- autopopulation.  if user's only have access to one of a certain resource and the resource is required (and not promptable), it should prefil to that.  for example, if org is a required field and 'Org 1' is the only org a user has, the field should prefill to 'Org 1'.

**Comment by mabashian** [comment]
Note: We decided to only show 5 results per page

**Comment by jlmitch5** [comment]
@kialam since this field is more or less complete for instance groups.  I am repurposing this card to just capture the enhancements (autopopulation and type to create tags) part of the feature.

**Comment by mabashian** [comment]
I think the search tags are going to be included with the search work that's going on right now.  I've peeled the autopopulation portion out into https://github.com/ansible/awx/issues/4254.
