### ISSUE TITLE
Gate CI on unit test coverage based on threshold

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#4207]
- ~change --watchAll to --watch in npm test script~ (edit: "test": "jest --coverage" & "test-watch": "jest --watch" are currently available.)
- update CI to check coverage

**Comment by jakemcdermott** [comment]
for the CI portion, we'd like the job to fail if the coverage drops beneath a certain threshold. For determining where that threshold would be, I think we can probably decide on a reasonable number when we do https://github.com/ansible/awx-pf/issues/25. We can get the coverage as high as possible for https://github.com/ansible/awx-pf/issues/25 and then set the threshold to something slightly lower; from there we will adjust it up or down as is reasonable while we continue to work on other things.

**Comment by mabashian** [comment]
Repurposed to track test coverage gating

**Comment by unlikelyzero** [comment]
@jakemcdermott @mabashian any changes this will come back? It would be great to see

**Comment by AlexSCorey** [comment]
This issue has been open for quite a while. The new UI has >80% coverage on unit tests right now.  I am going to close this, but we can reopen if necessary.
