### ISSUE TITLE
Expand/collapse all rows v. single row

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4208]
There are some lists (Jobs and Job Templates in particular) where it may not make a lot of sense for the user to expand/collapse all of the rows at the same time.  It may make more sense to allow the user to expand/collapse a single row.  I'm thinking that this could be a feature _in addition to_ the list level expand/collapse.  Ping @trahman73 for thoughts.  Ping @jakemcdermott because you mentioned something along these lines in our meeting.

link #47 because it's loosely related

**Comment by trahman73** [comment]
Spoke to @jakemcdermott about possible solutions and landed with the following:

Compact view with additional expand/collapse arrow for workflows.
https://tower-mockups.testing.ansible.com/mockups/jobs/jobs/
https://tower-mockups.testing.ansible.com/mockups/jobs/jobs-expand/

Expanded view of the above.
https://tower-mockups.testing.ansible.com/mockups/jobs/jobs-table-expand/
https://tower-mockups.testing.ansible.com/mockups/jobs/jobs-table-expand-workflows/

**Comment by mabashian** [comment]
@trahman73 I'm having some trouble following exactly what's proposed here.  Is the proposal for the user to click on a row and then click on the expand/collapse button to control it on the individual row level?

**Comment by trahman73** [comment]
@mabashian The expand/compact toggles in the list header is still an all or nothing for the entire list. Only workflows will have an individual row level carat to show/hide it's nested jobs.

**Comment by mabashian** [comment]
We'll be in a holding pattern here until we get to the templates list

**Comment by mabashian** [comment]
Since we're still trying to figure out what our long term plan is for data list I'm inclined to mark this as blocked.  If we do decide to roll our own simple table component then this should be part of the plan.

**Comment by AlexSCorey** [comment]
Table lists are implemented across 95% of the project and is currently being worked on in the remaining lists.  I think we can add an expand all feature for these lists and we should.  It is a pain for the user if they want to see something within the expanded row data for all list items and have to expand them individually.  The UI implementation would be simply a carrot on the same row as the column headers

**Comment by trahman73** [comment]
@AlexSCorey Agree, PF suggest adding that as I have it in mockups here:
https://tower-mockups.testing.ansible.com/patternfly/jobs/jobs/
