### ISSUE TITLE
websockets client / wrapper

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#4209]
This is for adding a basic ws module to the client:

- global subscriptions / global states
- view-specific / per-job subscriptions

**Comment by jakemcdermott** [comment]
some notes:

when we launch a job in AWX, the following things happen sequentially:

1. client makes an http request to `/api/v2/item/n/launch`
2. api responds with a job id
3. client uses job id to subscribe to a channel with the shared socket service, which delivers the job-specific ws events over that channel.

Ideally we want to eliminate the possibility for race conditions and missed job events between steps 2 and 3.

**Comment by jakemcdermott** [comment]
more notes:

* The implementation should be framework-agnostic and testable in isolation. For example, it should be straightforward to write a functional test or debugging script that imports this module by itself to test important behavior (connect / disconnect, subscribing, unsubscribing, etc.) with a real or mocked backend.

* The [api design](https://github.com/ansible/awx/blob/devel/docs/websockets.md#protocol) encourages clients to be idempotent with subscription state, which is favorable for a variety of reasons. We should:

  - keep the client-side representation of the subscription state as close to the API version as possible, ideally identical. In current AWX, we maintain a separate data structure and convert it to the one the API expects whenever subscriptions are changed. This is fragile and difficult to debug.

  - expose asynchronous parts of the connect, disconnect, and (re)subscribe cycle as promises or something chainable. For example, someone developing a new page or feature should, if necessary, be able to ensure that a newly requested subscription state is ready before something else happens.

**Comment by jakemcdermott** [comment]
Potentially useful for any presentational components that are driven by job statuses (status icons, etc.): https://reactjs.org/docs/hooks-custom.html

**Comment by wenottingham** [comment]
tangentially: https://github.com/ansible/awx/issues/1611

**Comment by wenottingham** [comment]
Also tangentially: as part of this we should revisit moving to a daphne/channels version from this century

**Comment by jakemcdermott** [comment]
Mike and I are breaking this work up into smaller issues:

https://github.com/ansible/awx/issues/5883
https://github.com/ansible/awx/issues/5885
https://github.com/ansible/awx/issues/5886

**Comment by ryanpetrello** [comment]
@mabashian @jakemcdermott @rebeccahhh re the job list performance issue, I think we can make a *lot* of progress by just being smarter about the requests we make.

Here's an `m5.4xl` w/ 1M jobs and 1B+ job events:

<img width="646" alt="image" src="https://user-images.githubusercontent.com/214912/74479594-6a542780-4e7d-11ea-8c75-f18e6d3ebd24.png">

Note if we drill down *only* to job IDs we care about (perhaps what _just_ got sent over the websocket w/ a status change), things really get snappy:

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/214912/74479569-61fbec80-4e7d-11ea-85ce-8ce4c173c15b.png">
