### ISSUE TITLE
Add proper error handling to Org Form(s)

### ISSUE THREAD

**Issue by kialam** [ansible/awx#4210]
- [ ] Add error handling for our API requests.
- [x] Redirect user to the Details view of the newly created org if Save is successful.
- [x] UX feedback from [here](https://github.com/ansible/awx-pf/pull/53#issuecomment-447382451):
 >Can we adjust the vertical space between the body of the form and the footer buttons to match the vertical line spacing within the body of the form itself? I would also adjust the vertical spacing under the footer buttons to match.
Example: https://tower-mockups.testing.ansible.com/patternfly/orgs/orgs-add/

**Comment by keithjgrant** [comment]
Sticking `Needs UX` on this for the error handling. It “works” now, but just says "error" in plain text at the bottom.

**Comment by keithjgrant** [comment]
I was gonna tackle the spacing issues here, but I realized it probably makes sense to wait until PF gets updated in #174

**Comment by mabashian** [comment]
Actually - I'm going to close this in favor of https://github.com/ansible/awx/issues/4240
