### ISSUE TITLE
Component: Active Filters List

### ISSUE THREAD

**Issue by kialam** [ansible/awx#4211]
Create an Active Filters list based on mockup below:
![active_filters_list](https://user-images.githubusercontent.com/2293210/51042453-59eec080-158a-11e9-8e72-7d187821f3fe.png)

1. Number of results that match the current set of filter criteria
2. Clear All Filters button removes all current filters; Active Filters List disappears and the results count reverts to original count.
3. Clicking on X next to a specific active filter removes it from the active filter list. This updates the results count.

**Comment by mabashian** [comment]
Blocked until https://github.com/ansible/awx-pf/pull/87 is merged

**Comment by mabashian** [comment]
This _could_ be built without knowledge of the search implementation details (input would be an array of... strings?) or something like that but moving to icebox for now.

**Comment by keithjgrant** [comment]
The SelectedList component certainly looks like this, minus a few text labels. It _might_ be the right tool for this given a couple new props

**Comment by mabashian** [comment]
Closing this issue as it was addressed by v1 search
