### ISSUE TITLE
Display dates in readable form

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4213]
The date strings that the api passes back to us look like:

<img width="1374" alt="screen shot 2019-02-05 at 3 10 07 pm" src="https://user-images.githubusercontent.com/9889020/52301376-4ac81c00-2958-11e9-8a19-aaeb07eea216.png">

We probably want to use something like http://momentjs.com/ to format those strings into something nice and readable.

To complete this task we'll need to (likely) settle on a lib and implement it for the date strings currently being shown in the app.  At this point in time that only includes the org details view.

**Comment by keithjgrant** [comment]
I’ve heard good things about date-fns, which is lighter weight and operates on the native Date type. Smaller bundle size (only imports what you use) + better performance by the benchmarks I've seen.

https://date-fns.org/

**Comment by jakemcdermott** [comment]
I'm also curious to see how much of what we need can be done using the native `Date` type. It's very likely we have some gnarly formatting / TZ problems that we would want to use a library for but we should verify that is true with a little exploration first. 

- How many places show dates / times on the organizations view? 
- Of those places, what are the formatting differences + timezone considerations, etc.?

**Comment by kialam** [comment]
The Scheduler part of the app also formats a set of 'timzoned' dates as [`rrule`](https://github.com/jakubroztocil/rrule) to be sent back to the API. 

I am in favor of using moment.js for its ease of use and extensive documentation.

**Comment by mabashian** [comment]
As far as I'm concerned https://github.com/ansible/awx/pull/4913 addresses this specific issue.  We'll still need to discuss dates at length when we go to build the scheduler.
