### ISSUE TITLE
Click to open Tooltips

### ISSUE THREAD

**Issue by keithjgrant** [ansible/awx#4214]
Currently, PatternFly tooltips can only be opened with keyboard focus or mouse hover. We would like them to open with mouse click as well. An issue has been filed with PatternFly for this at https://github.com/patternfly/patternfly-react/issues/1564

Follow up with this once they determine their course of action. If they decide to implement it, we can confirm functionality after upgrading. If they don't we will need to use Popovers instead, and re-style them to look like Tooltips.

**Comment by marshmalien** [comment]
Issue resolved in PF-React: https://github.com/patternfly/patternfly-react/issues/1564

They added a `trigger` prop to display tooltip on mouseenter, focus, and/or click.
