### ISSUE TITLE
Focus on username input after logging out

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4217]
Ping @trahman73 for confirmation but we do this in the existing app and it's quite nice IMO.  Right now when you log out we navigate you back to the login screen but don't focus on the input.

<img width="1328" alt="Screen Shot 2019-04-17 at 4 32 39 PM" src="https://user-images.githubusercontent.com/9889020/56318981-73297f00-612e-11e9-82ab-35f6ab249d5d.png">

**Comment by trahman73** [comment]
I don’t think we meant to be different here. We should support this flow in the new app.

**Comment by marshmalien** [comment]
Currently, the PatternFly Login component doesn't support the ability to autofocus input fields (without manipulating the DOM directly). Once we're able to obtain a [ref](https://reactjs.org/docs/forwarding-refs.html) to the instance and focus the nested input field through the virtual DOM, this issue will be ready for development. 

I've create an issue for the PatternFly React project here: https://github.com/patternfly/patternfly-react/issues/1954

**Comment by marshmalien** [comment]
Resolved with PF upgrade https://github.com/patternfly/patternfly-react/pull/2659
