### ISSUE TITLE
Templates List - Hookup Sort Functionality

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#4220]
## Templates List

Mockup: https://tower-mockups.testing.ansible.com/patternfly/templates/templates/

* Hookup sort dropdown options 
  * Name (Ascending/Descending) 
  * Modified (Ascending/Descending) 
  * Last Job Run (Ascending/Descending) 
  * Inventory (Ascending/Descending) 
  * Project (Ascending/Descending) 

* Mark strings for translation

<img width="1409" alt="Screen Shot 2019-05-22 at 3 26 25 PM" src="https://user-images.githubusercontent.com/15881645/58202667-22b1be00-7ca6-11e9-8c8a-db4cb05f0de2.png">

**Comment by mabashian** [comment]
Note that sort is already hooked up but only with Name, Modified, and Created right now.  We'll need to add the other options.

**Comment by dsesami** [comment]
Sort appears to work for all variations. It should be noted that since we can sort by project and inventory, there needs to be some way of identifying these columns. That should possibly be part of future work. Closing this issue for now as its scope is in fact complete.
