### ISSUE TITLE
Templates List - Sparkline

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#4225]
## Templates List

Mockup: https://tower-mockups.testing.ansible.com/patternfly/templates/templates/

<img width="1327" alt="Screen Shot 2019-05-23 at 2 18 15 PM" src="https://user-images.githubusercontent.com/15881645/58276561-c7df9b80-7d65-11e9-9618-a2231337b8e1.png">

This view should duplicate existing AWX behavior and display the status of the last 10 job runs. 

#### Tasks
* This will require a sparkline (smart status) component 
* Add a sparkline to each job template row item (this will require websockets)
* Display a green status if `job.status === 'successful`
* Display a red status if `job.status === 'failed' || job.status === 'error' || job.status === 'canceled'`
* On job status click, redirect to job details (dependent on job detail view #219)
* Display tooltip on job status hover with job id, status, and finished time
* Mark tooltip strings for translation

_Current AWX sparkline tooltip_
<img width="485" alt="Screen Shot 2019-05-23 at 2 33 26 PM" src="https://user-images.githubusercontent.com/15881645/58278233-910b8480-7d69-11e9-9afc-5bae5018bcef.png">

#### Not in Scope
* A sparkline for workflow job template items

**Comment by mabashian** [comment]
Note: once this merges please remove the blocked label from https://github.com/ansible/awx/issues/4247
