### ISSUE TITLE
Jobs List - Hookup Sort Functionality

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4227]
## Jobs List

Mockup: https://tower-mockups.testing.ansible.com/patternfly/jobs/jobs/

Depends on https://github.com/ansible/awx-pf/issues/225

* Hookup sort dropdown options 
  * Name (Ascending/Descending key: name) 
  * Finish Time (Ascending/Descending key: finished) 
  * Start Time (Ascending/Descending key: started) 
  * Launched By (Ascending/Descending key: created_by__id) 
  * Project (Ascending/Descending key: unified_job_template__project__id) 

* Mark strings for translation

Note that default is Finish Time (descending)

<img width="1476" alt="Screen Shot 2019-05-23 at 4 31 05 PM" src="https://user-images.githubusercontent.com/9889020/58284638-0894e000-7d79-11e9-97eb-e66be477b58a.png">

**Comment by mabashian** [comment]
Blocked until #4226 lands

**Comment by dsesami** [comment]
All sort parameters appear to move normally and redirect to the first page upon new sorting. :+1:

**Comment by unlikelyzero** [comment]
@dsesami needs test stubs PR
