### ISSUE TITLE
Multi-select or add new component (Labels, Tags, etc/Select2)

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4230]
This is the Select2 dropdown component that allows the user to select multiple values from an existing list or add new values.

Mockup: https://tower-mockups.testing.ansible.com/patternfly/templates/templates-add/

This is how the component operates in the existing UI:

![labels](https://user-images.githubusercontent.com/9889020/58483530-7b61da80-812e-11e9-8311-77b6b6c2a552.gif)

- User should be able to select N values from an existing list
- User should be able to add N new values
- User should be able to deselect values
- Component should be able to take in a list of selected values to display initially (think Edit Form)

We don't _have_ to mirror the exact same UX as the old UI.  If we have other ideas for presenting these options to the user we should explore them.  Maybe the solution is still _Select2_ - I'm not sure.  I would expect some research/scoping to need to be done alongside this issue.

**Comment by sumkincpp** [comment]
Something similar for hosts lookup would be great!

**Comment by jakemcdermott** [comment]
closing this as done - we've made some  issues and added them to the backlog for any remaining work surrounding labels and multiselect, but basic label selection is implemented and functional.
