### ISSUE TITLE
Job Template Add Form - Credential Lookup

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4231]
## Job Template Add Form - Credential Lookup

Mockup: https://tower-mockups.testing.ansible.com/patternfly/templates/templates-edit-creds/

_Current AWX behavior for reference_
<img width="1416" alt="Screen Shot 2019-05-28 at 10 50 26 AM" src="https://user-images.githubusercontent.com/9889020/58488132-d4ce0780-8136-11e9-9f12-689e214076e7.png">

<img width="732" alt="Screen Shot 2019-05-28 at 10 51 56 AM" src="https://user-images.githubusercontent.com/9889020/58488137-d8618e80-8136-11e9-8bf4-68616a4000c2.png">

<img width="720" alt="Screen Shot 2019-05-28 at 10 53 54 AM" src="https://user-images.githubusercontent.com/9889020/58488179-e8796e00-8136-11e9-8f4e-6f454f0451bd.png">

#### Tasks
* Add form field
  * Field looks/behaves exactly like the Instance Groups form field
  * User should be able to remove a selected credential from the form field
  * This field is _not_ required
* Clicking magnifying glass will open credential selection modal
  * Modal should initially display list of Machine Credentials
  * Modal should have a dropdown that allows the user to toggle between all the different `types` of credentials (including custom credential types)
  * Toggling to a new credential type should update the list contents
  * Displaying selected credentials should mirror displaying selected Instance Groups (should be removable)
  * A user should be able to select just one credential of each type.  There's one exception to this rule which is `Vault` credentials where a user can select up to N vault credentials as long as they have different `Vault IDs`.  You can only select one vault credential per `Vault ID`.  (We need to confirm this behavior).
* Mark strings for translation
* Responsive

#### Not in Scope for MVP
* Prompt on launch

**Comment by unlikelyzero** [comment]
Assigning myself to QE

**Comment by mabashian** [comment]
Blocked until https://github.com/ansible/awx/issues/4229 lands

**Comment by mabashian** [comment]
https://github.com/ansible/awx/pull/4257 has been merged so I don't think this is blocked any longer.

**Comment by jakemcdermott** [comment]
unassigning this and moving this out of in progress for now to reflect reality.

**Comment by AlexSCorey** [comment]
Removing myself.  Got other things in progress.
