### ISSUE TITLE
Job Template Add Form - Playbook Field

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4233]
## Job Template Add Form - Playbook Field

Mockup: https://tower-mockups.testing.ansible.com/patternfly/templates/templates-add/

<img width="466" alt="Screen Shot 2019-05-28 at 11 51 32 AM" src="https://user-images.githubusercontent.com/9889020/58492498-02b74a00-813f-11e9-8b68-72960bb851b7.png">

#### Tasks
* Add playbook dropdown
  * If there is a default/existing value it should be displayed as selected
* When the project field changes (and is valid) we'll need to go out and fetch the list of possible playbooks
  * This is true for the initial load of the edit form (if we want to track this behavior somewhere else that's fine)
* Mark strings for translation
* Responsive

#### Not in Scope for MVP

**Comment by mabashian** [comment]
Blocked until https://github.com/ansible/awx/issues/4229 lands

**Comment by mabashian** [comment]
Additionally this blocks https://github.com/ansible/awx/issues/4234

**Comment by mabashian** [comment]
Since #4229 is done I don't think this is blocked any longer.

**Comment by marshmalien** [comment]
We will want to revert the playbook select to the default option of "Please select . . ." whenever the project changes. 

https://github.com/ansible/awx/pull/4505#discussion_r314890747
