### ISSUE TITLE
Job Template Details - Launch Button

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4235]
Mockup: https://tower-mockups.testing.ansible.com/patternfly/templates/templates-detail/

Launch button should:
* Be shown to users with the appropriate permissions
* Launch the JT and redirect to job details after successful launch
  * See the launch behavior outlined for the templates list for more info/expected pattern.

**Comment by unlikelyzero** [comment]
Adding myself as QE

**Comment by mabashian** [comment]
link https://github.com/ansible/awx/pull/4251

**Comment by mabashian** [comment]
@AlexSCorey @unlikelyzero It looks like this is done/merged over a month ago.  I'm going to close.  Feel free to re-open if needed.
