### ISSUE TITLE
Job Results - Output Toolbar and backing API controls

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#4236]
## Job Results - Output Toolbar

Mockup: https://tower-mockups.testing.ansible.com/patternfly/jobs/jobs-output/

Depends on https://github.com/ansible/awx-pf/issues/219

These are the core pagination controls and api interaction for the static (non-realtime) event data. It's best to do these prior to hooking up the scrollbar, since they'll use the same underlying api calls.

<img width="1428" alt="Screen Shot 2019-06-15 at 8 53 51 AM" src="https://user-images.githubusercontent.com/9753817/59551683-353cb180-8f4b-11e9-923a-fc2c89196967.png">

**Comment by mabashian** [comment]
I've marked https://github.com/ansible/awx/issues/4224 as blocked until this gets done.  When this is merged we can unblock that issue.
