### ISSUE TITLE
Error: <filter> attribute width: Unexpected end of attribute. Expected length, ""

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4237]
This gets thrown to the console on page load/refresh.  Login is not necessary.  This seems to be part of the initial compilation of the app in the browser.

`Error: <filter> attribute width: Unexpected end of attribute. Expected length, ""`

<img width="1680" alt="Screen Shot 2019-06-03 at 10 32 00 AM" src="https://user-images.githubusercontent.com/9889020/58809968-f3c31280-85ea-11e9-8045-4b3045cb2e2e.png">

**Comment by marshmalien** [comment]
It _looks_ like a PF4 bug: https://github.com/patternfly/patternfly-react/issues/2100. 
We'll need to upgrade to pull in their fix: https://github.com/patternfly/patternfly-react/pull/2070.
