### ISSUE TITLE
Bug: deleting last element on a page does not pop you back to the previous page

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#4239]
update 2/13: @keithjgrant has a fix incoming (a simple fix is already merged for credential lists), but it's going to take some refactoring to get a general solution. we'll hold off on closing this bug until the generalized solution is there.

Steps to reproduce:

Take a list (say organizations), and go to the last page with only one element on it.  If you have two orgs, you can do this by going to: `/#/organizations?organization.page=2&organization.page_size=1`

Delete that item.

Expected results:  be taken to org list page 1
Actual resutls: 404 and kicked back to dashboard

**Comment by marshmalien** [comment]
Reopening Issue - Seeing this behavior in devel
![pagination del](https://user-images.githubusercontent.com/15881645/71194753-8317d680-225a-11ea-92e9-a13bd4d51182.gif)

**Comment by appuk** [comment]
@keithjgrant I see the PR is merged, is this issue ready for needs_test ?

**Comment by dsesami** [comment]
@keithjgrant I found that this still occurs if we have more than one "page reset"

1. Create like 17 projects and use the 5 per page view for easy toggling
2. Go to the second page, delete all the items so it goes back to the first page
3. There should only be two pages available now. Go to the second page and delete all the items.

It will still 404 with the above scenario ^

**Comment by keithjgrant** [comment]
@dsesami I wasn't able to replicate the 404... 17 items should result in 4 pages though, not three, so maybe I followed something incorrectly?

**Comment by dsesami** [comment]
@keithjgrant after further investigation, this looks like it works now. I couldn't replicate the previous scenario yet. If it comes back, I'll re-open the bug. For now, we're good. Thanks!
