### ISSUE TITLE
content loading enhancements

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#4241]
Right now we just show "loading". As a next step we probably want to show something a little nicer, like a spinner or skeleton lines.

sync up with taufique for scoping

**Comment by unlikelyzero** [comment]
@jakemcdermott does this still need to be done?

**Comment by jakemcdermott** [comment]
@unlikelyzero  Yep, but holding off until support for skeleton lines lands.

**Comment by mabashian** [comment]
Gonna close this as I think #4212 covers this same thing
