### ISSUE TITLE
boot user to login page when auth cookie is expired or no longer authenticated

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#4243]
There's not a lot of great options here as far as I can tell. One approach we've discussed at some length is using one of the request / intercept hooks from `axios`. I don't like that this ties us to a particular http interface object. Plus, it doesn't cover session expiration.

I don't think there are any native event handlers we can tap into for cookie changes that are supported on all browsers.

...so I'm wondering if we should just _poll the cookie_ and give users the 👢 when it changes to a value other than `true` or if its expired?

I know it sounds gross but its also direct and easily replaced later. If you absolutely hate this idea: So do I, so please talk me out of it.

**Comment by jakemcdermott** [comment]
might also be able to slip a `redirect` into the `NetworkErrorDetails` component since we're passing most network error objects and their status codes to that, be they in a modal or part of a content error.

:man_shrugging:

**Comment by dsesami** [comment]
I think this is is manifesting as a cycle where the user is stuck on the dashboard and it says "Unable to retrieve configuration" now. The possible only way to escape it is either manually logging out before responding to the modal, or just visiting /api and going through the api login.

**Comment by mabashian** [comment]
AFAIK this is working as intended.  There may be specific scenarios where this is not working and I'm inclined to track that in separate issues when we find them.
