### ISSUE TITLE
Prevent double click on templates list launch button

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4249]
#243 will add launch buttons to the job template rows in the templates list.  Something that we've run into in the past is that some users will double click on the launch icon which can inadvertently launch the job twice.  We'll want to prevent this behavior from happening.  I envision disabling the button after it's been clicked until either a) the job has been launched or b) an error has been thrown.

**Comment by AlexSCorey** [comment]
@mabashian should we also check for this in the JTDetails launch button?  If so, seems like this check should occur inside the `LaunchButton` component.  Is that what you were thinking?

**Comment by mabashian** [comment]
Just double checked and its still possible to do this

**Comment by tiagodread** [comment]
PR merged, worked as expected.
