### ISSUE TITLE
Template save failure when "Inventory Prompt on Lanuch" was enabled

### ISSUE THREAD

**Issue by FlickinChri443** [ansible/awx#425]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
I ´ve tried to save a Template where "Inventory - promt on launch" was enabled. 
All other fields were filled out. 

After saving the template, there is a confuse situation. 
I am not able to add surveys, (gui says the template wasnt saved). see attached file "not_saved_message"
Klick the "save" Button again theres an error (see attached file "error_message".

After leaving the job template creation, the created template appears but could not be edit. There is no error message or similar, there is just nothing happens. 

This  behavior is repeatable. It doesnt matter which project or playbook was selected. 

##### STEPS TO REPRODUCE

Same as summary!

##### EXPECTED RESULTS

I am expecting, the template will be saved and could be edit. 

##### ACTUAL RESULTS

The template appears (template overview) but could not be edit. 

##### ADDITIONAL INFORMATION

![not_saved_message](https://user-images.githubusercontent.com/32768728/31545096-3d2f659e-b01e-11e7-95d5-aecae03b5b87.jpg)
![error_message](https://user-images.githubusercontent.com/32768728/31545097-3d8aab84-b01e-11e7-82d7-8a87d91555d6.jpg)
![job_details](https://user-images.githubusercontent.com/32768728/31545098-3de6e85e-b01e-11e7-821a-cef12e00a9a8.jpg)

**Comment by wenottingham** [comment]
closing as dup of #415

**Comment by FlickinChri443** [comment]
Ok, thanks!
