### ISSUE TITLE
Custom Login logo not displaying properly

### ISSUE THREAD

**Issue by ryan012880** [ansible/awx#4253]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Uploading custom login logo does not display properly after upgrading from 5.0.0 to 6.0.0 

##### ENVIRONMENT
* AWX version: 6.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.1
* Operating System: RHEL7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Go to settings
2. Go to User Interface
3. Upload a custom image (PNG, JPEG .. any format mentioned as supported) to replace the login logo

##### EXPECTED RESULTS

Image should display properly

##### ACTUAL RESULTS

Settings User Interface
<img width="407" alt="Screen Shot 2019-07-02 at 8 40 38 PM" src="https://user-images.githubusercontent.com/10410660/60514178-826ea080-9d0b-11e9-8643-346cd948024c.png">
Login
<img width="563" alt="Screen Shot 2019-07-02 at 8 53 04 PM" src="https://user-images.githubusercontent.com/10410660/60514196-8e5a6280-9d0b-11e9-927d-fa3505e7649c.png">

**Comment by mabashian** [comment]
@ryan012880 out of curiousity - what's the error being thrown in the browser when it tries to fetch that resource?  Is it a 404?  A screenshot of the console may be helpful.  Moving forward, is it possible to revert the custom logo and re-upload?

**Comment by ryanpetrello** [comment]
I'm having trouble reproducing this one:

![image](https://user-images.githubusercontent.com/214912/60523331-87563480-9cb8-11e9-8f26-bba823ca455b.png)

![image](https://user-images.githubusercontent.com/214912/60523336-8b825200-9cb8-11e9-8017-584de3c5308d.png)

**Comment by ryanpetrello** [comment]
Okay, I see what's up.  This is a bug introduced by https://github.com/ansible/awx/pull/4167

@ryan012880 I'm assuming you see an error like this one in your browser console?

![image](https://user-images.githubusercontent.com/214912/60524177-16b01780-9cba-11e9-83de-98abd50e2ff6.png)

**Comment by ryanpetrello** [comment]
Thanks for reporting this @ryan012880, it'll be fixed via https://github.com/ansible/awx/pull/4256

**Comment by ryan012880** [comment]
Thanks guys for fixing, just tested the latest commit and it works!!
