### ISSUE TITLE
Auto populate lookup fields in add forms when user only has access to one resource

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4254]
##### SUMMARY
On certain add forms in the UI lookup fields like Inventory/Project/Organization (that are required) are automatically populated when the user only has access to one of these resources.  Since the field is required and the user only has access to one we can safely assume that that's the resource they'll select.

In order to achieve this, we'll need to identify all of the fields that should behave this way/do behave this way in `awx/ui`.  This will only impact add forms.  Edit forms should not behave this way.  If we detect that the user has access to more than one of these resources the field should be blank.

**Comment by mabashian** [comment]
Link https://github.com/ansible/awx/issues/4206 for original issue.  This is a subset of those proposed changes.

**Comment by mabashian** [comment]
Adding machine credential in the adhoc command wizard to this issue

**Comment by mabashian** [comment]
OK here's my best effort on all of the places where this should happen:

1) User Form
   - Organization Lookup
2) Application Form
   -  Organization Lookup
3) Inventory Form
   - Organization Lookup
4) Smart Inventory Form
   - Organization Lookup
5) Project Form 
   - Organization Lookup
   - Red Hat Insights -> Credential Lookup
6) Team Form 
   - Organization Lookup
7) Job Template Form 
   - Project Lookup (this was already in place but I normalized the implementation)
8) Inventory Source Form 
   - Sourced from project -> Project Lookup (this was already in place but I normalized the implementation)
   - Google Compute Engine -> Credential Lookup
   - Microsoft Azure Resource Manager -> Credential Lookup
   - VMware vCenter -> Credential Lookup
   - Red Hat Satellite 6 -> Credential Lookup
   - OpenStack -> Credential Lookup
   - Red Hat Virtualization-> Credential Lookup
   - Ansible Tower -> Credential Lookup

------ These are not included in #8104 and will have to be added in other PR(s) ------

9) Notification Template Form 
   - Organization Lookup
10) Container Group Form 
    - Credential Lookup
11) Adhoc Command Form 
    - Machine Credential Lookup

**Comment by tiagodread** [comment]
Tests and PR already merged 👍🏽
