### ISSUE TITLE
Please add file system cleanup when deleting Projects through the UI.

### ISSUE THREAD

**Issue by gamuniz** [ansible/awx#426]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

When a project is deleted from the UI the directories are left orphan on all nodes in the cluster. This leads to another manual step of deleting projects from the file system. It also balloons the size of the /var partition
##### ENVIRONMENT
AWX version: 1.0.1
Ansible version: 2.4
Operating System: RHEL 7
Web Browser: Chrome

##### STEPS TO REPRODUCE

1. create project in UI
2. delete project in UI
3. navigate to file system on clusters 

##### EXPECTED RESULTS
Expected that the files are cleaned when deleted from the UI

##### ACTUAL RESULTS
Ideally deleting the files from the UI would remove them from all nodes in the cluster/instance group

**Comment by wenottingham** [comment]
For someone that picks this up, note that this would probably need to be a task that fans out to all cluster nodes.

**Comment by matburt** [comment]
`tower_broadcast_all` is the queue we usually use for fanout

**Comment by AlanCoding** [comment]
The hard part of using the fanout queue is whether we report the logs within the standard out of the job. I could see us doing some kind of generalized solution that could apply to all unified jobs, since this has similarities to #289, although that may still be overly-ambitious.

**Comment by AlanCoding** [comment]
Looking at this again, the complexity is nowhere near what #289 would be. We don't need to track anything in the database for this action. We could just send out the task in the broadcast queue, have it delete the files, and that's it.
