### ISSUE TITLE
Add logging options to docker compose with inventory settings.

### ISSUE THREAD

**Issue by rubenrodr-versia** [ansible/awx#4262]
Docker logs size grows until fs is full.
Enabling docker log rotation options on inventory during install to setup docker compose file
Example:
```
docker_logging_options_max_file=10
docker_logging_options_max_size=100m
```
would avoid recreating containers after setup to enable logging options.

**Comment by john-westcott-iv** [comment]
Thanks for the suggestion. WIth the new recommended way to install AWX via the operator this would only now apply to development environments. Because of this we are going to close this issue.
