### ISSUE TITLE
AWX 6.0.0 install

### ISSUE THREAD

**Issue by cbutler65** [ansible/awx#4266]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Problems encountered during install and testing

##### ENVIRONMENT
* AWX version: 6.0.0
* AWX install method:  docker on linux, 
* Ansible version:  X.Y.Z
* Operating System: RHEL 7
* Web Browser:Chrome Version 64.0.3282.186

##### STEPS TO REPRODUCE

Install 6.0.0

##### EXPECTED RESULTS

similar to 4.0.0

##### ACTUAL RESULTS

Password not set for guest in awx_rabbitmq.
work around:
/bin/docker exec awx_rabbitmq rabbitmqctl change_password guest {{ awx.mqpassword }}

When running a playbook the output window does not update. In my view this is the problem that makes it unusable.

tower-cli cannot migrate templates because credential data is not supported.

##### ADDITIONAL INFORMATION

Thank you for providing a very useful tool.

**Comment by ryanpetrello** [comment]
Hey @cbutler65,

We use this issue tracker for tracking enhancements and bugs to AWX.  If you need assistance troubleshooting an install or update, check out our mailing list or IRC room on free node:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
