### ISSUE TITLE
Ability to add AWX Inventory name as a variable in playbook

### ISSUE THREAD

**Issue by falcon78921** [ansible/awx#4269]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Per a customer's request, they would like to query the name of the Inventory utilized as a variable and use that variable in a playbook.

~~~
---
- name: Test connectivity
  hosts: all

  tasks:
    - name: Run hostname command
      command: hostname
    - name: Run Inventory Name
      command: echo {{ inventory_name }}
~~~

**Comment by sumkincpp** [comment]
We are using our own `inventory_name` variable for the same purposes which is setuped dynamically on inventory update. 
Following AWX naming conventions, it might be great to have `awx_inventory_name`, specified by AWX.

I am seeing merged PR, any reason why the issue was reopened?

**Comment by wenottingham** [comment]
For testing.

**Comment by kdelee** [comment]
Talked to @ryanpetrello and I think this needs some docs about how it is expected to be used before I can test it. Going to put in `needs_docs`

**Comment by ryanpetrello** [comment]
@tvo318 you ready to call this closed?

**Comment by kdelee** [comment]
Tested this out and it works for me, also it is in the docs now!
