### ISSUE TITLE
Make docker config persistent after each reboot

### ISSUE THREAD

**Issue by titocad** [ansible/awx#427]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME
 - Installer

##### SUMMARY
Need a way to make AWX docker configurations persistent after server reboot

##### ENVIRONMENT
* AWX version: 1.0.1.14
* AWX install method: docker on linux
* Ansible version:  2.4.0.0
* Operating System: Ubuntu 14.04 LTS

##### STEPS TO REPRODUCE
After rebooting the server AWX configurations are reset to the initial installation setup.

**Comment by titocad** [comment]
Additional info:
After rebooting AWX server I get this message on http://localhost: "AWX is Upgrading"

I already tried changing docker storage-driver from overlay2 to devicemapper and the issue remains.
Every time I reboot the server, all configurations are lost and the server returns to a fresh install state.

**Comment by matburt** [comment]
This is probably because the default directory is pointed at `/tmp`. You are free to, and encouraged, to change this to some place more permanent:

https://github.com/ansible/awx/blob/devel/installer/inventory#L30

**Comment by titocad** [comment]
Thanks! That was the issue.
