### ISSUE TITLE
Azure dynamic inventory does not honour hostvar_expressions setting

### ISSUE THREAD

**Issue by chris-p-martin** [ansible/awx#4273]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY
Azure Dynamic inventory import does not honour configuration of hostvar_expressions setting in azure_rm.py

##### ENVIRONMENT
* AWX version: AWX 6.0.0.0
* AWX install method: docker on linux
* Ansible version:  Ansible 2.8.1 
* Operating System: Ubuntu
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Change the ansible_host settings under hostvar_expressions to something other than defaults. Run dynamic inventory import. 

##### EXPECTED RESULTS

Inventory should import using the settings I specified 

##### ACTUAL RESULTS

Import runs but the settings are not honored and the import is done using the original ansible_host settings

##### ADDITIONAL INFORMATION

My config

> my_host_var:
> \# A statically-valued expression has to be both single and double-quoted, or use escaped quotes, since the outer
> \# layer of quotes will be consumed by YAML. Without the second set of quotes, it interprets 'staticvalue' as a
>   \# variable instead of a string literal.
>   some_statically_valued_var: "'staticvalue'"
>   \# overrides the default ansible_host value with a custom Jinja2 expression, in this case, the first DNS hostname, or
>   \# if none are found, the first public IP address.
>   ansible_host: (private_address) | first
> 

Original config:

> my_host_var:
>   \# A statically-valued expression has to be both single and double-quoted, or use escaped quotes, since the outer
>   \# layer of quotes will be consumed by YAML. Without the second set of quotes, it interprets 'staticvalue' as a
>   \# variable instead of a string literal.
>   some_statically_valued_var: "'staticvalue'"
>   \# overrides the default ansible_host value with a custom Jinja2 expression, in this case, the first DNS hostname, or
>   \# if none are found, the first public IP address.
>   ansible_host: (public_dns_hostnames + public_ip) | first
>

**Comment by AlanCoding** [comment]
This seems to be a mis-understanding of what the current inventory source form does. We do not have any place for the user to directly modify the inventory file used by the supported inventory plugins.

I'm replacing this with https://github.com/ansible/awx/issues/4306, because I think that would let you do what you are trying to do.

**Comment by gomker** [comment]
@AlanCoding  For the Amazon EC2 inventory I do show that it obeys these vars
![image](https://user-images.githubusercontent.com/3577339/62491663-2a0b4280-b792-11e9-8782-f0f4d45091bf.png)
Am I misunderstanding something in that this is specific to the Azure inventory itself?

**Comment by AlanCoding** [comment]
Those you mention are documented in https://github.com/ansible/ansible/blob/devel/contrib/inventory/ec2.ini

**Comment by gomker** [comment]
So Azure fails since they are not defined in https://github.com/ansible/ansible/blob/devel/contrib/inventory/azure_rm.ini

And the inventory script is not configured for those options.
I was trying to understand the differences in the configuration.

Thanks
