### ISSUE TITLE
Postgres data permissions are wrong on kubernetes

### ISSUE THREAD

**Issue by alancivita** [ansible/awx#4275]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
the postgres pod fails to start as it complains about a wrong permission of the data directory. Permissions are set to 0770 instead of 0700.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: Kubernetes on Linux
* Ansible version:  X.Y.Z
* Operating System: Ubuntu Xenial
* Web Browser:

##### ADDITIONAL INFORMATION

The only way to fix it is to connect to the kubernetes node that mounts the data directory and change the permissions to 700 immediately , right after the container has started.
There should be a better way to fix it.
Any tips 

Thanks

**Comment by ryanpetrello** [comment]
Hey @alancivita,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
