### ISSUE TITLE
Add sync all sources button to inventory list

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#4284]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Right now when you need to update inventory you need to open it and then go to sources list and then click the refresh button. That is tedious.

There should be a button right in the inventory list that allow you to click it in order to trigger refresh of all sources this inventory has.

**Comment by shanemcd** [comment]
There is now a Sync All button under Inventory -> Sources. I'm not sure we want to expose that on the main inventory list since that is a very performance intensive action.

**Comment by benapetr** [comment]
This doesn't solve the problem at all, most inventories already have only one source, so sync all button solves nothing. The problem is that it's non-trivial to sync multiple inventories because you have to do many clicks to get inside of inventory settings, sources, click sync all. Doing this for multiple inventories is tedious, although it can be worked around by making a separate flow to do this.
