### ISSUE TITLE
AWX cannot run without privileged rights in k8s

### ISSUE THREAD

**Issue by TheKangaroo** [ansible/awx#4286]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Cannot run AWX 6.0.0 in a multitenant k8s cluster because of security implications.

##### ENVIRONMENT
* AWX version: 6.0.0
* AWX install method: kubernetes yaml files
* Ansible version:  n.a. (we render the upstream jinja yaml templates to deploy them directly to k8s)
* Operating System: client: mac, k8s cluster is running on container linux
* Web Browser:Chrome 75.0.3770.100 (Mac)

##### STEPS TO REPRODUCE

We replaced a AWX 5.0.0 instance with the new AWX 6.0.0 instance.
Everything seems to run fine, but as soon as we want to run jobs inside AWX, we get errors with bwrap like
```
bwrap: Can't mount proc on /newroot/proc: Operation not permitted
```
I dug a bit into the problem and it seems like you now need to run
a) awx-web with allowPrivilegeEscalation: true and
b) awx-celery with privileged: true

This is somewhat problematic for our use case since we run a ton of different applications in an (internally) shared cluster and do not allow privileged, privilege escalation or any capabilities at all. Is there any way to run it without these elevated rights?

##### EXPECTED RESULTS

Expected AWX to run without any additional privileges like in the prior version.

##### ACTUAL RESULTS

AWX won't run in our environment as is. 

##### ADDITIONAL INFORMATION

Ask if anything is uncelar :)

**Comment by matburt** [comment]
AWX uses [bubblewrap](https://github.com/projectatomic/bubblewrap) to isolate processes (as you alluded to). This requires the capability to create chroots which implies elevated privileges. You *can* disable bwrap usage in AWX via settings and then disable these elevated permissions however you should be aware that disables process isolation between running playbooks which means other playbook run on the same system could make changes to *other* projects or the running AWX system itself... including the python interpreter and environment.

**Comment by TheKangaroo** [comment]
Ahh thank you @matburt :) Disabling bwrap worked for me.

**Comment by Vacant0mens** [comment]
@matburt how do you go about disabling bubblewrap for the kubernetes setup?
I'd like to run this in a local cluster as non-privileged, but I can't seem to get the install working properly.

**Comment by TheKangaroo** [comment]
@Vacant0mens I'm not 100% sure since I configured it for a colleague and it's been a while, but IIRC you have to run the app and disable bubblewrap from the settings page on AWX GUI
