### ISSUE TITLE
i would like to know how to open awx in vscode for me to edit some stuff thank you 

### ISSUE THREAD

**Issue by ahmedmaz24** [ansible/awx#4297]
##### ISSUE TYPE

- question 

##### COMPONENT NAME

 - API
 - UI
 

##### SUMMARY

i would like to know how to open it in vscode
##### ENVIRONMENT

* Ansible version:  latest
* Operating System: centos 7
* Web Browser: firefox

**Comment by ryanpetrello** [comment]
Hey @ahmedmaz24,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting or contributing to an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
