### ISSUE TITLE
Option to Enforce End Dates on Scheduled Jobs

### ISSUE THREAD

**Issue by mdinwoodie** [ansible/awx#4298]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add an option or setting for admins to require that users specify an end date on any scheduled job they setup.

**Comment by wenottingham** [comment]
I think this is the wrong level to apply these sorts of controls, as the next step would be a setting that sets the maximum end date, or the minimum time for recurrence, or....

**Comment by ghjm** [comment]
We don't currently have any plan to implement this.
