### ISSUE TITLE
System Auditor cannot access settings menu

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#4302]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
System Auditor cannot access settings menu either through navbar or direct navigation.

Still need to determine if this is just one manifestation of a larger permissions issue.

#### ENVIRONMENT
* AWX version: tower 3.5.0 awx 6.0.0

##### STEPS TO REPRODUCE

Attempt to access settings menu as Auditor persona.

##### EXPECTED RESULTS

Settings options available to view

##### ACTUAL RESULTS

Unable to access settings configuration

**Comment by mabashian** [comment]
Changing https://github.com/ansible/awx/blob/devel/awx/ui/client/src/configuration/settings.service.js#L49 to `var putActions = data.actions.PUT ? appendOauth2ProviderKeys(data.actions.PUT) : {};` alleviates this issue.  System auditors don't have PUT actions from the options response so the existing code will silently error out while attempting to navigate to the settings view.

**Comment by unlikelyzero** [comment]
Verified that System Auditor can now navigate to All Dashboard Nav Options including Settings
Verified that System Auditor's view of settings page includes header: "System auditors have read-only permissions in this section."
