### ISSUE TITLE
Scheduled Jobs do not show vars

### ISSUE THREAD

**Issue by alxndr13** [ansible/awx#4303]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When filling out the survey for scheduled jobs, you can save the vars but afterwards they will not be visible. The Job gets scheduled and runs fine nevertheless. 

##### ENVIRONMENT
* AWX version: 5.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.1
* Operating System: Linux / Windows
* Web Browser: Chrome / Firefox

##### STEPS TO REPRODUCE

- Create scheduled job from template with survey
- press prompt, fill out survey
- click next and save the results
- "Extra Vars" field is empty

##### EXPECTED RESULTS

See extra vars filled out. 

##### ACTUAL RESULTS

See the saved extra vars

**Comment by mabashian** [comment]
This is actually the intended behavior as it's currently designed.  When you schedule a job template with a survey, the answers to the survey questions are not combined with the promptable extra variables area while looking at the schedule form.  When the job runs, the variables are aggregated.  This pattern is similar to how default survey answers do not show up as extra variables in the job template form but they will get aggregated when you launch the job.  If you want to see the survey answers for a saved schedule you'll have to open up the prompt modal again:

<img width="1532" alt="Screen Shot 2019-07-12 at 2 19 55 PM" src="https://user-images.githubusercontent.com/9889020/61150115-a6bb4180-a4b0-11e9-84e6-6dc68bc315ae.png">

**Comment by alxndr13** [comment]
Thanks, that does make sense!
