### ISSUE TITLE
Form for direct user input of inventory plugin configuration

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#4306]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Right now, there is no way to use an inventory plugin-style YAML configuration aside from checking it into source control. We have had several inquiries related to this, so this is proposed as a solution to resolve all of those use cases.

Things we can say this feature would necessary need to have:

 - form elements
   - Place to select a credential or multiple credentials
   - Place to enter YAML content of the inventory plugin (no JSON)
   - (unclear) filename may or may not need to be independently specified, the only known stubborn exception that could require this is [VMWare](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/vmware_vm_inventory.py#L278)
   - any other shared elements with whatever type of resource it is (like NAME)
 - The YAML content will be required to have `plugin: foo` as a top-level entry
 - The form will enforce that supported types use a credential of its corresponding type
   - possible additional feature - allow custom types to claim an inventory plugin namespace
 - Inventory updates already use plugins, this will do very little different, just using the config that the user gives
 - A "convert to plugin" button on existing inventory sources that work with plugins
   - this will start the user out with a configuration that gives compatibility with existing behavior, which they can then modify at will

Questions still remain. Will this be another type, similar to inventory scripts? Or will it be another option for `source` of an inventory source? Will there be any way for the user to alter ansible.cfg options, like the group name conversion?

Ping @wenottingham @ghjm

**Comment by AlanCoding** [comment]
@kdelee we should close https://github.com/ansible/awx/issues/3448 if we get this added.

**Comment by wenottingham** [comment]
-> #5150
