### ISSUE TITLE
install awx failed in TASK [local_docker : Start the containers] about  import the required Python library

### ISSUE THREAD

**Issue by PePoDev** [ansible/awx#4309]
I got this error But I already install "docker" via pip install docker.

> Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on ubuntu-s-1vcpu-1gb-sgp1-01's Python /usr/bin/python. Please read module documentation and install in the appropriate location, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: cannot import zname constants"}

I try to search about it but dont found any solution can solve it.

**Comment by jakemcdermott** [comment]
@PePoDev You'll need docker / docker-compose on the machine to which you are installing awx as well. Did you install it there?

**Comment by PePoDev** [comment]
@jakemcdermott  Yes, I can run hello-world image and use command `docker --version` or `docker ps` in machine

**Comment by ryanpetrello** [comment]
Hey @PePoDev,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by thuban-arrakis** [comment]
This link might help, i've also struggled few times during installation.
https://neutrollized.blogspot.com/2018/12/cannot-have-both-docker-py-and-docker.html

**Comment by renepardon** [comment]
> This link might help, i've also struggled few times during installation.
> https://neutrollized.blogspot.com/2018/12/cannot-have-both-docker-py-and-docker.html

sadly this didn't do the trick so far :/


```
Docker version 19.03.8, build afacb8b
docker-compose version 1.25.5, build 8a1c60f6
Python 3.7.7
ansible 2.9.9
```

**Comment by Vadims06** [comment]
Hi @renepardon 
did you solve the issue? Pls share

**Comment by izha-alltech** [comment]
>  did you solve the issue? Pls share

Google for **exact error** (the **last phrase** in copy-pasted message, i.e. 

> cannot import zname constants

Or Google for **YOUR** error (if it is **NOT** "cannot import zname constants")
