### ISSUE TITLE
install awx failed in TASK [compose.yml - name: Start the containers] - Openshift

### ISSUE THREAD

**Issue by jsdevalx** [ansible/awx#4310]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
ansible-playbook -i inventory install.yml -e openshift_password=XXX -e docker_registry_password=$(oc whoami -t) -vvvv

ansible-playbook 2.6.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/XXX/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, May 20 2019, 12:21:26) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Set default localhost to localhost
Parsed /home/XXX/awx/installer/inventory inventory source with ini plugin
statically imported: /home/XXX/awx/installer/roles/local_docker/tasks/set_image.yml
statically imported: /home/XXX/awx/installer/roles/local_docker/tasks/compose.yml
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/XXX/awx/installer/roles/local_docker/tasks/compose.yml': line 25, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Start the containers
  ^ here

##### ENVIRONMENT
* AWX version: 6.0.0
* AWX install method: openshift
* Ansible version: 2.6.5
* Operating System: RHEL 7.5
* Web Browser:

##### STEPS TO REPRODUCE

Install on Openshift:
ansible-playbook -i inventory install.yml -e openshift_password=XXX -e docker_registry_password=$(oc whoami -t) -vvvv

**Comment by ryanpetrello** [comment]
Hey @jsdevalx,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

I suspect you're actually running into this issue:

https://github.com/ansible/awx/pull/4260
