### ISSUE TITLE
Host_Vars imported incorrectly formatted

### ISSUE THREAD

**Issue by EnzoAkira** [ansible/awx#4322]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After importing the Hosts and Groups, I always have to correct the Host_vars because they appear incorrectly formatted.
Attached is an image with an example.

##### ENVIRONMENT
* AWX version: 5.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.1
* Operating System: CentOS 7
* Web Browser: Mozilla

##### EXPECTED RESULTS

host_vars as in source project

###### Note: 
**On the left side is the final result after importing to AWX through a repository as source; on the right is the original version of the variables that are in the Git repository.**

![Import host vars](https://user-images.githubusercontent.com/39481527/61140535-8648b280-a4c3-11e9-86ab-bb1e55b0fec7.png)

**Comment by ryanpetrello** [comment]
@EnzoAkira I'm looking at this screenshot and making sure I understand.  Is the complaint here that the key ordering wasn't persisted (i.e., name and desired_state are swapped now)?

**Comment by EnzoAkira** [comment]
Hi @ryanpetrello 
Thank you for quick response.
The keys ordering are a bit important but for the record that works fine (for now).
I am complaining why this happens. I also need the comments because go services maybe grow shortly and other applications are being finalized.

**Comment by ghjm** [comment]
Unfortunately we are not able to preserve order or comments, because this data is ingested by the ansible-inventory command which is not able to preserve these items.

**Comment by EnzoAkira** [comment]
> Unfortunately we are not able to preserve order or comments, because this data is ingested by the ansible-inventory command which is not able to preserve these items.

Thank you @ghjm
