### ISSUE TITLE
SSH connection to network devices (ios) breaks

### ISSUE THREAD

**Issue by smnmtzgr** [ansible/awx#4325]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When using AWX 6.0.0 connections to network devices (cisco_ios) are broken if more than one task is present for the device.

##### ENVIRONMENT
* AWX version: 6.0.0
* AWX install method: Kubernetes
* Ansible version: 2.8.1
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create a playbook with multiple tasks of ios modules e.g. 

- name: <all> get facts
  ios_facts:
    gather_subset: all

- name: <all> execute commands to get model
  ios_command:
    commands:
      - show version
  register: version_output

##### EXPECTED RESULTS

That this works without problems

##### ACTUAL RESULTS

After the first successful task the job fails at the second task with:

using connection plugin network_cli (was local)
starting connection from persistent connection plugin
found existing local domain socket, using it!
Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
updating play_context for connection
 
The full traceback is:
Traceback (most recent call last):
  File "/usr/bin/ansible-connection", line 302, in main
    conn.update_play_context(pc_data)
  File "/usr/lib/python2.7/site-packages/ansible/module_utils/connection.py", line 186, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
ConnectionError: unsupported operand type(s) for ^: 'str' and 'str'

TASK [helper-network_facts : <all> execute commands to get model] **************
task path: /var/lib/awx/projects/_8__ans_netops_fil_awx_int/roles/helper-network_facts/tasks/main.yml:34
fatal: [device1]: FAILED! => {
    "msg": "unsupported operand type(s) for ^: 'str' and 'str'"
}

PLAY RECAP *********************************************************************
device1                   : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Playbook run took 0 days, 0 hours, 0 minutes, 6 seconds

##### ADDITIONAL INFORMATION

I found another issue which was opened regarded to this problem: https://github.com/ansible/ansible/issues/48093
I already tried to reproduce the error with pure Ansible 2.8.1 on CLI. But here everything works perfectly fine. AWX 6.0.0 is also using Ansible 2.8.1

**Comment by ryanpetrello** [comment]
This is a bug in Ansible itself, not AWX:

```python
File "/usr/lib/python2.7/site-packages/ansible/module_utils/connection.py", line 186, in rpc
```

The link you referenced at https://github.com/ansible/ansible/issues/48093 indeed looks like the same thing to me.
