### ISSUE TITLE
Inventory source from a project -> set inventory variable_data

### ISSUE THREAD

**Issue by jmcshane** [ansible/awx#4327]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

When sourcing an inventory from an AWX project, I want to be able to set the global inventory variable_data field with a set of properties. We are using `variable_data` api from the inventories and want to be able to set fields in source control with the rest of our inventory rather than managing those values manually.

When I sync right now, it reads every top level field as a group name, rather than seeing the `vars:` key as a global vars object

**Comment by wenottingham** [comment]
Can you given an example of the sort of inventory you're looking to import? I would expect this to be in `group_vars/all` (or equivalent)

**Comment by awithrow9** [comment]
Closing.  If you have an example you can reopen and comment.
