### ISSUE TITLE
Markdown not rendered on Insight issue summaries

### ISSUE THREAD

**Issue by jaredevantabor** [ansible/awx#433]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

### Steps to Reproduce
* Set up your scan jobs so that your stock host has insights data. Use a valid set of Insights credentials.
* Inspect the issues presented in the UI.

The problem is that the API returns backticks that would normally indicate markup text under `/api/v2/hosts/N/insights`:
```
....
"summary": "A critical security flaw in the `glibc` library was found. It allows an attacker to crash an application built against that library or, potentially, execute arbitrary code with privileges of the user running the application.",
....
```

...But the UI doesn't render the markup. So we have backticks surrounding technical terms in the UI for no real reason. For instance:
<img width="1326" alt="screen shot 2017-06-29 at 6 39 58 pm" src="https://user-images.githubusercontent.com/5964417/27713593-69f01d34-5cfa-11e7-98cd-2d260a8ab312.png">
<img width="1329" alt="screen shot 2017-06-29 at 6 40 07 pm" src="https://user-images.githubusercontent.com/5964417/27713594-69f762a6-5cfa-11e7-976d-3f4c0ab539cb.png">

##### ENVIRONMENT
* AWX version: 1.0.1.14

**Comment by shanemcd** [comment]
Issue mentions "scan jobs" which don't exist anymore. Assuming this is no longer relevant.
