### ISSUE TITLE
fancy traceback screen (which leaks information it shouldn't)

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#4335]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
1. Cause https://github.com/ansible/awx/issues/4334

You no longer get a generic server error page.
You get:
![Screenshot from 2019-07-16 17-11-52](https://user-images.githubusercontent.com/5208768/61330149-02593800-a7ed-11e9-8256-7c3605a7ca2f.png)

Things on this page:
- all cookies
- all settings (including BROKER_URL, etc.)

##### ENVIRONMENT
* AWX version: current devel
* AWX install method: docker-compose

##### ADDITIONAL INFORMATION

I assume this is a result of the django 2.2 upgrade.

**Comment by wenottingham** [comment]
until proven otherwise, this appears to be a stray debug setting in the dev environment.

**Comment by ryanpetrello** [comment]
Yep, this is what the dev environment displays when an uncaught exception occurs in a request and `settings.DEBUG` is `True` (the default in the dev env).
