### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by pwe123345** [ansible/awx#4336]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When running specific modules on remote hosts, the task fails because "Failed to import the required Python library (<Name of library>) on <Remote Hosts>'s Python /usr/bin/python."

##### ENVIRONMENT
* AWX version: 6.0.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.1
* Operating System: CentOS 7
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Run the following task:

```
    - name: Create the PostgreSQL User
      postgresql_user:
        name: user
        password: password
        encrypted: True
      become_user: postgres
```

##### EXPECTED RESULTS

User gets created.

##### ACTUAL RESULTS

```
{
    "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_postgresql_user_payload_Caykqb/__main__.py\", line 239, in <module>\n    import psycopg2\nImportError: No module named psycopg2\n",
    "_ansible_no_log": false,
    "invocation": {
        "module_args": {
            "ssl_mode": "prefer",
            "ca_cert": null,
            "login_user": "postgres",
            "login_host": "",
            "expires": null,
            "db": "",
            "conn_limit": null,
            "login_unix_socket": "",
            "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_password": "",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 5432,
            "fail_on_user": true,
            "priv": null,
            "name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "no_password_changes": false,
            "session_role": null,
            "state": "present",
            "encrypted": true,
            "role_attr_flags": ""
        }
    },
    "changed": false,
    "msg": "Failed to import the required Python library (psycopg2) on <Remote Server>'s Python /usr/bin/python. Please read module documentation and install in the appropriate location"
}
```

##### ADDITIONAL INFORMATION

Same happens with modules for mysql_db and expect.

**Comment by ryanpetrello** [comment]
@pwe123345,

Many ansible modules require _additional_ Python libraries beyond what we package by default in awx. (here's what we include by default: https://github.com/ansible/awx/blob/devel/requirements/requirements_ansible.txt).  See this document for instructions on customizing the environment in which your playbooks run: https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md

**Comment by pwe123345** [comment]
I have no idea how to include additional packages in the standard environment. I dont see any value to use custom venvs.
Do you have different instructions since I cant find any, just lots of people with similar problems.
