### ISSUE TITLE
 Inventory source checkbox group items too wide

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#434]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

The individual checkbox items are clickable too far to the right:
![issue](https://user-images.githubusercontent.com/10867373/28335014-f38027ae-6bca-11e7-9ea7-a5d45ae853de.gif)

##### ENVIRONMENT
* AWX version: 1.0.x

##### STEPS TO REPRODUCE

Edit any inventory source and see the width of the checkbox items

##### EXPECTED RESULTS

Only the checkbox and text are selectable.

##### ACTUAL RESULTS

Most of browser width is selectable.

**Comment by jaredevantabor** [comment]
This is now fixed in devel.
