### ISSUE TITLE
External Postgres configured with Patroni

### ISSUE THREAD

**Issue by svrraja** [ansible/awx#4340]
ISSUE TYPE:
External Postgres configured with Patroni

SUMMARY:
We have our AWX running in K8s and postgres is configured externally on a Patroni HA.
Had enabled "pg_hostname=postgresql" and its connectivity to primary server
How can we give primary and secondary DB server in the connection string.

**Comment by ryanpetrello** [comment]
Hey @svrraja,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
