### ISSUE TITLE
Enable/Disable Nodes per Instance Group, not Globally

### ISSUE THREAD

**Issue by mdinwoodie** [ansible/awx#4350]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Currently, disabling a node from any instance group disables it globally. This RFE is to allow enabling/disabling of nodes on a per-instance group basis, rather than globally.

**Comment by wenottingham** [comment]
Is there a reason to not just remove it from the instance group in this scenario?

This would also likely behave oddly with auto-IG policies.

**Comment by kfattig** [comment]
Removing it from the instance group could be an acceptable workaround, but that's not currently possible in the GUI. As I understand it the only way is to use awx-manage, which requires SSH access as root/awx .

**Comment by wenottingham** [comment]
No, you can definitely do this via the API (PATCH the `policy_instance_list` of the instance group in the API).

You can also do it via the UI via the `x` next to the instance here:

![Screenshot from 2019-07-19 11-00-46](https://user-images.githubusercontent.com/5208768/61545039-91946480-aa14-11e9-9935-bae1af28eb30.png)

**Comment by kfattig** [comment]
Thank you - I wasn't aware that was possible in the 'select instance' window.  This is a usable workaround for us.

Just to be clear if anyone else stumbles on this in the future:

The process described in the documentation for [associating hosts](https://docs.ansible.com/ansible-tower/latest/html/userguide/instance_groups.html#associate-instances-to-an-instance-group) also works for disassociating them.

**Comment by ryanpetrello** [comment]
We might revisit improving the UX here so it's clearer: https://github.com/ansible/awx/issues/4355
