### ISSUE TITLE
Add timestamp & collection type to analytics TAR

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/awx#4354]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Add a new `query_info.json` file to the tar that includes the timestamp of collection as well as any other relevant collection metadata.  

Pass a flag with the awx-manage command if manually run and include that in the `query_info.json`.  It may be useful to know if this is a scheduled collection or not.

**Comment by elyezer** [comment]
I was able to verify this by doing the following:

1) Ran couple jobs
2) Gathered analytics 2 times
3) Check if the information provided was as expected.
