### ISSUE TITLE
AWX doesn't send correct infromation to logstash

### ISSUE THREAD

**Issue by pasta88** [ansible/awx#4357]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Wrong information sending to logstash.

##### ENVIRONMENT
* AWX version: 6.1.0
* AWX install method: rpm from https://copr-be.cloud.fedoraproject.org/results/mrmeee/ansible-awx/epel-7-x86_64/
* Ansible version:  2.8.2
* Operating System: rhel 7.6
* Web Browser:
ELK: 7.2

##### STEPS TO REPRODUCE
1. Connect awx to logstash.
2. Perform any role which changes a file (task type is the template) and after runs a handler.
I run the below playbook:

- name: Configure the /etc/chrony.conf
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0600'
  notify:
    - chrony restart

##### EXPECTED RESULTS
In awx and logstash should be information about change of file ( changed: true)

##### ACTUAL RESULTS
In awx information about change is CORRECT (changed: true)
In logstash information about change is WRONG (changed: false).

##### ADDITIONAL INFORMATION
I connected the awx to the logstash.

For instance, I deploy the /etc/chrony.conf file . In the jobs in the awx I see that there are two changes: replacing config file and performing chrony restart:
![image](https://user-images.githubusercontent.com/53143930/61591289-453c5680-abc5-11e9-9d43-e02b219e874e.png)

Unfortunately, awx send wrong informations to logstash, because in the row which indicates on changing the file configuration is set changed: false.

![image](https://user-images.githubusercontent.com/53143930/61591309-b714a000-abc5-11e9-9604-3973693df2d7.png)

I set default configuration of logstash and awx.
In version 5.x of awx is the same behaviour.

Below is the logstash configuration:
input {
    http {
        host => '0.0.0.0'
        port => 20000
        tags => 'awx'
    }
}

filter {
    json {
        source => "message"
    }
}

output {
    elasticsearch {
        hosts => [ 'localhost:9200' ]
    }
}

**Comment by pasta88** [comment]
And I think it will be a good idea sending a diff to logstash too.

**Comment by beeankha** [comment]
Tower emits logs for each each individual event coming back from `ansible`.  These are wrapped in a `JobEvent`, which are by default marked as `changed=False` until we observe the actual `changed: [...]` output.  

As an example, below is a list of specific job events values from a successful Job Template run:

```
In [40]: list(lots_changed.job_events.values_list('event', 'changed', 'play', 'parent_uuid'))
Out[40]:
[('verbose', False, '', ''),
 ('verbose', False, '', ''),
 ('verbose', False, '', ''),
 ('verbose', False, '', ''),
 ('verbose', False, '', ''),
 ('verbose', False, '', ''),
 ('verbose', False, '', ''),
 ('verbose', False, '', ''),
 ('verbose', False, '', ''),
 ('verbose', False, '', 'bf7af0a9-d534-4fbe-9704-426e5954e204'),
 ('playbook_on_start', True, '', ''),
 ('playbook_on_play_start',
  False,
  'AWX Issue Tester',
  'bf7af0a9-d534-4fbe-9704-426e5954e204'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-00000000000c'),
 ('playbook_on_task_start',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-000000000006'),
 ('runner_on_start',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-00000000000c'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-00000000000c'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-00000000000c'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-00000000000c'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-00000000000c'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-00000000000c'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-00000000000c'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-00000000000c'),
 ('playbook_on_task_start',
  True,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-000000000006'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-000000000008'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-000000000008'),
 ('runner_on_ok',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-00000000000c'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-000000000008'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-00000000000c'),
 ('runner_on_start',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-000000000008'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-000000000008'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-000000000008'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-000000000008'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-000000000008'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-000000000008'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-000000000008'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-000000000008'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-000000000008'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-000000000008'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-000000000008'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-000000000008'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-000000000008'),
 ('runner_on_ok',
  True,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-000000000008'),
 ('verbose',
  False,
  'AWX Issue Tester',
  '0242ac12-0005-5224-8291-000000000008'),
 ('playbook_on_stats', True, '', 'bf7af0a9-d534-4fbe-9704-426e5954e204')]
```

It appears that what's going on under the hood is that the default state of a job event's `changed` state is false until it isn't, so even if there is no info to update in there, the `changed` status gets reported as `false`.  Because of this, any given play will wind up with some number of `changed=false` events, and some that are `changed=true`.  Semantically, the play should probably be overall considered `changed=true` if _any_ are listed as such.

Something to try in order to get more accurate information for Logstash is to switch back to preferring `runner_on_*` instead of any `changed=true`.
