### ISSUE TITLE
Template description should be visible in template list

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#4359]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Right now it's visible only when you open template definition, it would be far more useful if it was visible at least in expanded view, so that it's clear what templates are used for.

**Comment by AlanCoding** [comment]
I assume this would only be of interest in the "expanded" view of templates. Expanded view does not include description right now.

**Comment by appuk** [comment]
Template Description is now visible in the expanded view:

<img width="1680" alt="Screen Shot 2019-08-05 at 12 37 46 PM" src="https://user-images.githubusercontent.com/11617351/62480475-f1616e00-b77d-11e9-8c6f-6e3085fc6e96.png">

**Comment by elyezer** [comment]
@tvo318 leaving this open for now. Can you close it when docs are in place? Thank you very much

**Comment by jakemcdermott** [comment]
I think I moved this over to `needs_test` by mistake. Sorry.

**Comment by jakemcdermott** [comment]
whoops, maybe not. @AlanCoding and are I still taking a look..

**Comment by jakemcdermott** [comment]
state is exactly as @elyezer described. Issue is resolved by devel and tested by qe, but looks like there may be a docs component to this that needs to be addressed before closing?

cc @tvo318 @AlanCoding

**Comment by tvo318** [comment]
All the screen captures are done in the end to accommodate views like this. See doc issue https://github.com/ansible/product-docs/issues/757.

**Comment by jakemcdermott** [comment]
:+1: sgtm @tvo318, thanks!
