### ISSUE TITLE
 I have a question about awx clusters.

### ISSUE THREAD

**Issue by dhkim07** [ansible/awx#4365]
##### ISSUE TYPE
 - Feature Idea

 - ENVIRONMENT
AWX version: 6.0.0

##### SUMMARY

We configured the awx cluster using a bare metal based docker-swarm.
Our management server is very large, about 10,000.
To quickly process large volumes of work, you need to use three awx nodes simultaneously.
The cluster has been configured, but only one node will use the resources when the playbook is running.
Is there a way to have 3 awx cluster nodes use all resources when running a playbook on 10000 hosts?

**Comment by ryanpetrello** [comment]
Hey @dhkim07,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install or have a question about AWX in general, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
