### ISSUE TITLE
Add "pending_jobs" metric

### ISSUE THREAD

**Issue by grahamn-gr** [ansible/awx#4366]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Add "pending_jobs" metric so you can spot if AWX is not processing jobs

There are metrics to show running jobs but nothing for pending jobs.
We sometimes see issues with our AWX instances which are usually spotted by a high number of pending jobs in the queue.
It would be good to add pending jobs as a metric so issues can be spotted earlier than reported.

**Comment by rooftopcellist** [comment]
This is resolved by #4375.  Thanks for the idea @grahamn-gr!
