### ISSUE TITLE
AnsibleAWX Docker-compose file updated,working with ansible task & web 6.0.0

### ISSUE THREAD

**Issue by jcwang84** [ansible/awx#4371]
Hi all 
docker-compose file i found on github that doesnt work with any version above 3
I have updated docker compose file. see my repo below if you needed . 
https://github.com/jcwang84/AnsibleAWXDocker

**Comment by ryanpetrello** [comment]
@jcwang84,

If you've fixed an issue with AWX, please file a detailed issue and open a pull request.

Thanks!
