### ISSUE TITLE
Isolated node cleanup bug can cause isolated capacity to fail to update

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#4376]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
1.  Install a cluster with one or more isolated nodes.
2.  Configure the periodic isolated cleanup so it happens more frequently:

```python
AWX_ISOLATED_PERIODIC_CHECK = 30
```

3.  Run _this_ script on the isolated node (as the `awx` user):

```python
import os
import time

path = '/tmp/awx_123456789_abc'
os.mkdir(path)
yesterday = time.time() - 86400
os.utime(path, (yesterday, yesterday))
```

4.  The periodic capacity check for isolated nodes will fail with this traceback:

![image](https://user-images.githubusercontent.com/214912/61903105-b9db0200-aef1-11e9-9408-5c2ab06e5027.png)

**Comment by Spredzy** [comment]
This is fixed.
