### ISSUE TITLE
[DOUBT] How can i add more than one credentials to a job template?

### ISSUE THREAD

**Issue by AndreMTrindade** [ansible/awx#4381]
Good morning. 

I have a rocky doubt can someone help me?
I want created a job workflow to deploy configurations to multiple remote hosts but i just can add one credential per job template. Is it possible add multiple credentials per job template for my multiple remote hosts? 

Thanks for help. 
Grazie

**Comment by ryanpetrello** [comment]
Hey @AndreMTrindade,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
