### ISSUE TITLE
API job_templates/id/launch no longer accepting 'credential' param

### ISSUE THREAD

**Issue by ijmason** [ansible/awx#4382]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Hi, we have been using a very old version of AWX (pre-2.0) until this week we were finally able to upgrade to 6.1.0.

The only problem we have seen so far is with our in-house application which launches jobs through the API.

Previously, that application would make a POST to api/v2/job_templates/id/launch, and include parameters for the inventory and credentials ID ('inventory' and 'credential', respectively).

I noticed with the new release of AWX, that jobs launched this way did not have the credential associated.  After a bit of digging in the API UI, found out that the field seems to have been renamed to 'credentials', and now accepts a list rather than a single value as we were providing before.

I have updated our application to use this method instead, and it works now, but I am wondering if this is an intentional change, since it would seem to be a breaking change on the existing API v2.  I found some mention of deprecating some old v1 style credential handling in the changelogs, so perhaps we had been using the old v1 credential unknowingly, *but*, I tried to use the new 'credentials' parameter with an older AWX (still api v2), and it refused to accept it, so I'm not sure what to think.

I haven't been able to find any clear documentation explaining this change nor any bug reports, so I'm opening this; my apologies if this is already a well known (and non-bug) issue.

##### ENVIRONMENT
* AWX version: 6.1.0
* AWX install method: kubernetes
* Ansible version:  2.8.2
* Operating System: Fedora 28
* Web Browser: N/A

##### STEPS TO REPRODUCE

POST to the api/v2/job_templates/id/launch and provide a 'credential' parameter with the numeric ID of the credential to supply to the job template.

##### EXPECTED RESULTS

The job template is launched with the specified credential attached.

##### ACTUAL RESULTS

The job template is launched without any credential attached.

##### ADDITIONAL INFORMATION

The latest version of tower-cli (3.3.6) also seems to be affected in the same way, i.e. jobs launched while specifying a credential do not actually get that credential when run in AWX.

**Comment by ryanpetrello** [comment]
Hey @ijmason,

This _is_ an intentional removal of a feature that dates from API v1 (which as you noted, we recently removed in `6.0.0`).  For convenience, we added support to keep this working in `/api/v2/` when we deprecated `/api/v1/` years ago, but we did remove the polyfill from `/api/v2/` when we removed `/api/v1/`.

All of this has been part of a multi-year transition period to move to a new model where jobs support _multiple_ credentials:

https://github.com/ansible/awx/pull/595

**Comment by ijmason** [comment]
Thanks @ryanpetrello, that clears things up.  Based on that though I would expect our older AWX install to accept the new credentials list in v2; if that should be the case then I will have to figure out why that didn't seem to work in my tests.

**Comment by ryanpetrello** [comment]
> we have been using a very old version of AWX (pre-2.0)

You might have something slightly wrong, or it's also possible that version you're using doesn't _have_ the new `credentials` support on launch.

This is where it was added (merged Nov 27, 2017, _likely_ available in Dec 2017 as part of awx 1.0.2): https://github.com/ansible/awx/pull/595

![image](https://user-images.githubusercontent.com/214912/61968167-4c88a900-afa5-11e9-83e8-8e48c66fcfc6.png)

**Comment by ijmason** [comment]
@ryanpetrello thanks, I'll have to go back and see what happened.  I think I was passing both fields at one point so that may be what it didn't like.

Thanks again for the quick response.
