### ISSUE TITLE
Git force push breaks project sync

### ISSUE THREAD

**Issue by nanoscopic** [ansible/awx#4384]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The following breaks the ability to sync a project against git:

1. Setup a project against a git repo
2. Sync the project
3. Git commit --amend the last commit and force push it to the repo ( not a great practice; but commonly done )
4. Try to sync the project ( specifically in my case tried to sync an inventory file in the project )
5. Cannot sync ( gives an error saying it cannot find commit after [hash of commit that was replaced by the commit --amend] )

##### ENVIRONMENT
* AWX version: 6.1.0.0
* AWX install method: docker for mac
* Ansible version:  2.8.2
* Operating System: OSX Mojave
* Web Browser: N/A

**Comment by wenottingham** [comment]
Is 'clean' or 'delete on update' set?

**Comment by nanoscopic** [comment]
Delete on update is not set. ( assuming you mean the option to fully delete and checkout again )
Agreeably that would likely let it work; because it won't try to do an incremental pull.

I have now though retried to produce the same error I encountered yesterday. On second attempt I do not get the error; I get green on both syncs. My file though is not updated. I double checked the bitbucket I force pushed to and it shows the old data, despite having amended. I don't think there is an issue here with AWX.

I will attempt to pin down where the error is, update this ticket with the results, and close it if the problem is outside of AWX.

**Comment by nanoscopic** [comment]
Looking further there is no issue with AWX. The initial error I encountered appears to have been triggered somehow by not first syncing the project then syncing the source, then poking at the local copy of the file that AWX checked out.

I believe my issue that caused the error would have been fixed by using the 'clean' option to discard local changes.
