### ISSUE TITLE
Build AWX with AWX and AWX-custom logo

### ISSUE THREAD

**Issue by svrraja** [ansible/awx#4389]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Build awx image along with AWX-logo but still only angry potato logos are there and not the  AWX logo.

Build AWX image with AWX-logo and installed (k8s), even the login and dashboard are having angry potato logos only.
Uploaded the custom logo under settings - User interface - Custom LOGO which changed the logo in login screen but after making this change also the dashboard still contains the angry potato in the top left corner.

Need AWX logo or custom in the dash board.
 
##### ENVIRONMENT
* AWX version: 6.1.0
* AWX install method: Kubernetes
* Ansible version:  2.8.0rc1
* Operating System: docker
* Web Browser: chrome

##### STEPS TO REPRODUCE

Build your own images by disabling dockerhub_base.
# dockerhub_base=ansible
kubernetes_context and kubernetes_namespace must be provided and docker_registry_ must be enabled alone with use_container_for_build=true and awx_official=true

##### EXPECTED RESULTS

The login and dashboard must having AWX logos.

##### ACTUAL RESULTS
The login and dashboard are having angry potato logos.

##### ADDITIONAL INFORMATION
TASK [image_build : Verify awx-logos directory exists for official install] ****************************************************************************************************************************************************************

ok: [localhost] => {
    "changed": false, 
    "failed_when_result": false, 
    "invocation": {
        "module_args": {
            "checksum_algorithm": "sha1", 
            "follow": false, 
            "get_attributes": true, 
            "get_checksum": true, 
            "get_md5": null, 
            "get_mime": true, 
            "path": "../../awx-logos"
        }
    }, 

TASK [image_build : Copy logos for inclusion in sdist] *************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "dest": "../awx/ui/client/", 
    "invocation": {
        "dest": "../awx/ui/client/", 
        "module_args": {
            "dest": "../awx/ui/client/", 
            "src": "../../awx-logos/awx/ui/client/assets"
        }, 
        "src": "../../awx-logos/awx/ui/client/assets"
    }, 
    "src": "/Users/abc/AWX/awx/installer/../../awx-logos/awx/ui/client/assets"

**Comment by alekslebedev** [comment]
I have the same problem. When you build your own image, awx ignore official=true setting in inventory file.

**Comment by svrraja** [comment]
I had Manually changed the files to make it work

**Comment by loitho** [comment]
Hi there,
This issue is still happening to me, the problem is described here too : 
https://github.com/ansible/awx/issues/4078

When i login into awx_web and find my logo this is the result:
```
find / -name logo-login.svg
/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/ui/client/assets/logo-login.svg <--- new logo
/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/ui/static/assets/logo-login.svg <--- Angry potato
/var/lib/awx/public/static/assets/logo-login.svg <--- Angry potato
```
I just don't want to see the potato logo in the header, I just want to swap it and display the one of the company
(The login logo is already modified)

So I did one of the suggested modification in another issue : 

E.g. when used with *docker-compose.yml* (assuming custom-logo.svg is in the same folder):
```
web:
      image: awx_web:9.0.1
  ...
  volumes:
      - "/yourfolder/logo-header.svg:/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/ui/static/assets/logo-header.svg:ro"
    ...
```
