### ISSUE TITLE
AWX 5.0 How can I get the error message

### ISSUE THREAD

**Issue by mattluk168** [ansible/awx#4390]
##### ISSUE TYPE
 - How can I get the error message in awx

##### SUMMARY
I see some specialist can found the error message in the server/awx web. How can they get the error messages? 

Eg. https://github.com/ansible/awx/issues/886

> I get an error:
> "Could not read from remote repository, Please make sure you have the correct access rights and the repository exist"

**Comment by ryanpetrello** [comment]
Hey @mattluk168,

Generally the types of errors you're talking about are surfaced in the server logs for your installation (which can be in a variety of locations depending on your installation method, such as `docker logs` of `/var/log/tower/`).

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
