### ISSUE TITLE
Job notification data omits new host summary fields (rescued, ignored)

### ISSUE THREAD

**Issue by jladdjr** [ansible/awx#4394]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: devel
* Ansible

##### SUMMARY
The Job model's `notification_data` method omits the new ansible host summary fields added [here](https://github.com/ansible/ansible/pull/48418).
https://github.com/ansible/awx/blob/c7bb0f10e10476e10df8a7e7b26732eb60958ca1/awx/main/models/jobs.py#L655-L661

##### STEPS TO REPRODUCE

1. Create a job template
1. Create an email notification template
1. Configure the JT to trigger the e-mail notification on job success
1. Run the job
1. Once the job completes, look at the body of the e-mail notification that was sent

These steps can be accomplished with `akit` using the following commands:
```python
jt = v2.job_templates.create(); host = jt.ds.inventory.add_host()
nt = v2.notification_templates.create(notification_type='email')
jt.add_notification_template(nt, 'notification_templates_success')
job = jt.launch().wait_until_completed()
```

##### EXPECTED RESULTS

The e-mail notification will include a JSON dictionary with a number of fields describing the job run. The `hosts` section will list results for each host involved in the playbook run. Each host's results should include the `rescued` and `ignored` fields.

##### ACTUAL RESULTS

`rescued` and `ignored` fields are missing:

![Screenshot 2019-08-19 12 35 57](https://user-images.githubusercontent.com/4440360/63293909-ef1f0980-c27d-11e9-9924-e0c1ad24822b.png)

##### ADDITIONAL INFORMATION

The new host summary fields (rescued, ignored) were [added in Ansible 2.8](https://github.com/ansible/ansible/issues/31245) and adopted by awx [here](https://github.com/ansible/awx/issues/466) (and included in Tower 3.5)

**Comment by ryanpetrello** [comment]
@jladdjr can you add some instructions here on how to reproduce/observe this bug?

**Comment by jladdjr** [comment]
@rebeccahhh (@ryanpetrello) - provided some additional context. Let me know if you need any other info!

**Comment by elyezer** [comment]
I verified this by doing the following:

1) Started a HTTP server and made it listen to connections
2) Created a Webhook notification and configured it to post to the HTTP server started on 1
3) Created a Job template and associated with the notification created on 2
4) Launched the job template and wait until it completed
5) Check if the POST request was made to the HTTP server and that the `rescued` and `ignored` fields were present (see the JSON data received below)

```json
{
    "created_by": "admin",
    "credential": "Demo Credential",
    "extra_vars": "{}",
    "finished": "2019-09-05T13:19:11.784510+00:00",
    "friendly_name": "Job",
    "hosts": {
        "localhost": {
            "changed": 0,
            "dark": 0,
            "failed": false,
            "failures": 0,
            "ignored": 0,
            "ok": 2,
            "processed": 1,
            "rescued": 0,
            "skipped": 0
        }
    },
    "id": 15,
    "inventory": "Demo Inventory",
    "limit": "",
    "name": "Demo Job Template",
    "playbook": "hello_world.yml",
    "project": "Demo Project",
    "started": "2019-09-05T13:19:04.441732+00:00",
    "status": "successful",
    "traceback": "",
    "url": "https://towerhost/#/jobs/playbook/15"
}
```

With all the above we consider this done
