### ISSUE TITLE
is_system_auditor flag isnt working properly

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#4397]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
`is_system_auditor` flag on ldap isnt working properly. When the ldap user logs in for the first time in AWX it doesnt assign the user as system auditor, it only creates it as a normal user. But if you re-login with the same ldap user, it assigns it as `system_auditor`.

##### STEPS TO REPRODUCE

1.) Have a `is_system_auditor` flag set on ldap configuration
2.) Login with the user which is not there on AWX and with a matching query for `is_system_auditor`

##### EXPECTED RESULTS

User should get created as `system_auditor`

##### ACTUAL RESULTS

User doesnt gets created as `system_auditor`. You have to re-login and then user gets assigned as system auditor. 

##### ADDITIONAL INFORMATION

Note: This looks like a regression related to a recent change in `django-auth-ldap`: https://github.com/django-auth-ldap/django-auth-ldap/commit/b777321fb486620f261e2ebbe28e508ca5a826eb

**Comment by Spredzy** [comment]
This is fixed.
