### ISSUE TITLE
CyberArk web service provider prerequisite 

### ISSUE THREAD

**Issue by tvo318** [ansible/awx#4400]
##### ISSUE TYPE
 - Enhancement

##### SUMMARY
To address a concern from user(s) on the mailing list - we want to explicitly mention the Central Credential Provider service in the name of the lookup plugin and in its documentation to make it more clear that you need the central provider service component installed to your aim server in order to store secrets in it (and therefore use our secret lookup plugin with it)

- Docs will call this out by referring to it as "**5.1.1. CyberArk AIM Central Credential Provider Lookup**"  in the docs. 

- will also also update the code so that the the credential type is called "CyberArk AIM Central Credential Provider Lookup" instead of "CyberArk AIM Secret Lookup". This would require a new screenshot, but would help cover the bases by making sure we mention both "AIM" and "Central Credential Provider" when referring to the integration.

**Comment by ryanpetrello** [comment]
As part of verifying this, we should confirm that you can install an older version of AWX, configure an AIM credential, and that post-upgrade, everything continues to work (with the name of the credential type changed).

**Comment by kdelee** [comment]
@one-t putting you since you were subject matter expert for this, but @Spredzy says he can help if you need to delegate

**Comment by one-t** [comment]
I haven't been able to find a clean upgrade path. I'll need to come back to this later after my patience has recovered

**Comment by one-t** [comment]
Tested on openshift

Steps:
1. Install in openshift 
2. Set up a credential and job template using internal infrastructure
3. upgrade
4. Verify that the name is changed
5. Successfully run the job template with the lookup

This is working as expected
