### ISSUE TITLE
Allow selection and copying output from the Standard Out section in the HostEvent modal

### ISSUE THREAD

**Issue by orgito** [ansible/awx#441]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
I'd like to be able to select and copy output from the task detail (host event) modal. 

##### ENVIRONMENT
* AWX version: 1.0.0.561
* AWX install method:docker on linux (official images)
* Ansible version:  2.4.0.0
* Operating System: Centos 7.4
* Web Browser: Chrome 60.0.3112.78 

##### STEPS TO REPRODUCE

1. Click on any task that produces output in the job results window. 
2. Try to select the text from the standard out or error section

##### EXPECTED RESULTS
Being able to select and copy the text.

##### ACTUAL RESULTS
Not possible to select and copy the text.

##### ADDITIONAL INFORMATION
Please also allow copying other sections like the extra variables.

**Comment by matburt** [comment]
Oh, that is super annoying.

Attempting to select the text will cause the box to be repositioned and it doesn't allow text selection.
