### ISSUE TITLE
PLAYBOOK DIRECTORY of project show [object Object]

### ISSUE THREAD

**Issue by morganw** [ansible/awx#4414]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
in project, when SCM_TYPE select Manual, and the PLAYBOOK DIRECTORY sometimes show [object Object]
i look the code awx/awx/ui/client/src/projects/factories/get-project-path.factory.js
 scope.project_local_paths = arraySort(opts);
                    if (scope.local_path) {
                        for (i = 0; scope.project_local_paths.length; i++) {
                            if (scope.project_local_paths[i].value === scope.local_path) {
                                scope.local_path = scope.project_local_paths[i];
                                break;
                            }
                        }
                    }

in code: scope.local_path = scope.project_local_paths[i]; why not 
 scope.local_path = scope.project_local_paths[i].value;???

I notice this js will run 3 times, so scope.local_path will become very complex.

##### ENVIRONMENT
* AWX version: 5.0.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by morganw** [comment]
now i  modify: it become ok
if (scope.local_path) {
    // List only includes paths not assigned to projects, so add the
    // path assigned to the current project.
    if (scope.local_path instanceof Object){
        opts.push({
            label: scope.local_path.value,
            value: scope.local_path.value
        });
        scope.local_path = scope.local_path.value
    } 
    else{
        opts.push({
            label: scope.local_path,
            value: scope.local_path
        });
    }
}

**Comment by awithrow9** [comment]
@morganw can you try this on the latest version (6.1.0) and let us know what you find?

**Comment by morganw** [comment]
OK， let me test. thanks.

**Comment by morganw** [comment]
if my error. version: 5.0.0 is also ok. let me close this issuse

**Comment by morganw** [comment]
I am sorry, it is my error. version 5.0.0 is also ok. I will close this issuse.
