### ISSUE TITLE
AWX 1.0.6.15/41 :  win_ping module FAILED ntlm code 403

### ISSUE THREAD

**Issue by zdriic** [ansible/awx#4416]
##### ISSUE TYPE
 - Bug Report
 - Documentation

##### COMPONENT NAME
 - UI

##### SUMMARY

My goal is to use AWX to do some actions on Windows servers (in a company).
From the command line I can ping my test server with the win_ping module from my Ubuntu VM (18.04) with the Ansible package (v2.8.3).

In the "inventories" directory, I have this :

>> Local Ubuntu 18.04 + ansible 2.83
/inventories
---inventory.inv (file)
---/group_vars (directory)
------windows.yml (file)

>> File inventory.inv : 
[windows]
Mywindows_Host (<= this is an example!)

>> File windows.yml :
ansible_user: user
ansible_password: password
ansible_port: 5985
ansible_winrm_transport: ntlm
ansible_connection: winrm
ansible_winrm_message_encryption: always
ansible_winrm_server_cert_validation: ignore

When I ping this windows host from my local Ubuntu with Ansible 2.8.3 using the command line there is no problem.

$> ansible windows -m win_ping -i inventories/

Mywindows_Host | SUCCESS => {
    "changed": false,
    "ping": "pong"
}

But the same conf in AWX, I have an error... 

> Configuration in AWX : 
- Credential : type MACHINE + user and password like in windows.yml file
- Inventory : create an inventory with the host name and in "Variables" section I put this : 
ansible_port: 5985
ansible_winrm_transport: ntlm
ansible_connection: winrm
ansible_winrm_message_encryption: always
ansible_winrm_server_cert_validation: ignore
(see attach file)

>But when I run win_ping command from AWX I have this error :
{
    "msg": "ntlm: Bad HTTP response returned from server. Code 403",
    "unreachable": true,
    "changed": false
}

![image](https://user-images.githubusercontent.com/51320434/62368076-cbdd2600-b52b-11e9-83dd-9ecf1a4275e9.png)

##### ENVIRONMENT
* AWX version: 1.0.6.15
* AWX install method: docker on linux
* Ansible version:  2.8.3
* Operating System: Ubuntu 16.04
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Just use the command win_ping which is available in AWX , section "Inventory"

##### EXPECTED RESULTS
ping SUCCESS !!

##### ACTUAL RESULTS

ntlm: Bad HTTP response returned from server. Code 403

**Comment by wenottingham** [comment]
Hi - this looks like an issue with your inventory or configuration, not with AWX itself. You may have better luck on the awx-project mailing list, or the ansible-awx IRC channel; this repo is for AWX bugs only.
