### ISSUE TITLE
Add 'limit' field in job search

### ISSUE THREAD

**Issue by mrmibrown** [ansible/awx#4421]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add the limit field in searches to find jobs run where a host name was in limit.  Also allow a none option so you could search for job runs with no limit set (IE that ran against the entire inventory.)

**Comment by wenottingham** [comment]
Enter `job.limit:<whatever>` in the search/filter job to search by limit. 

limit is not interpreted to a set of hosts by Tower (only by Ansible at job run time), so if you want to determine on which hosts actions happened, you'll need a different query.

**Comment by wenottingham** [comment]
To find what jobs have run on a hosts, see the `completed jobs` view for that host.
