### ISSUE TITLE
Add RBAC rules to side-nav

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4426]
##### SUMMARY
The side-nav in `ui_next` does not have any RBAC rules baked in yet.  This issue will be used to track that work.  https://github.com/ansible/awx/blob/devel/awx/ui/client/lib/components/layout/layout.partial.html can be used as a reference.  In general, we want to do the following:

1. Hide Settings, Management Jobs, and Credential Types from _all users except system administrators and system auditors_.  Note that these two flags come from `/api/v2/me` (is_superuser, is_system_auditor).
2. Hide Instance Groups and Integrations (Applications) from _all users except system administrators, system auditors, and org administrators_.  Determining whether a user is an org admin is done with a request to `/api/v2/users/:user_id/admin_of_organizations/` and checking that the count is greater than one.
3. Hide Notifications from _all users except system administrators, system auditors, org administrators, and notification administrators_.    Determining whether a user is an org admin is done with a request to `api/v2/organizations/?role_level=notification_admin_role` and checking that the count is greater than one.

If none of the `Administration` or `Settings` options are shown to a user then those headers should be hidden as well.

**Comment by AlexSCorey** [comment]
backing out for now

**Comment by jakemcdermott** [comment]
I would like to discuss with the api team the possibility of adding an endpoint (or more information to an existing API) to help solve this, as I believe it would reduce a lot of complexity and http calls.

**Comment by unlikelyzero** [comment]
@nixocio as I understand it, we will need to add some api changes to the /me and /config API endpoints. Is that correct @jakemcdermott ?

**Comment by nixocio** [comment]
It would be a nice to have, but not a blocker. I was waiting for the wizard PR work to be completed to move forward with this one.

**Comment by nixocio** [comment]
There is now also the execution environment admin that needs to be taken in consideration for the side-nav.

**Comment by tiagodread** [comment]
This is now fixed
