### ISSUE TITLE
Feature: support Github enterprise OAuth

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#443]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

We support github.com OAuth for connecting to Tower.

We should support GitHub Enterprise as well (it's supported by the underlying library).

**Comment by gomker** [comment]
I haven't looked at the code yet but would this not be easy enough to have a field configurable to your Enterprise github Domain and override it trying to go to public github.com ?

**Comment by ryanpetrello** [comment]
@wenottingham is this a near-term priority that we should track more closely as an enhancement in the next major release?

**Comment by unlikelyzero** [comment]
This is in test as we add ui coverage. @yagomarques and @shebangbash are leading the api testing

**Comment by one-t** [comment]
This has already been merged as of february
