### ISSUE TITLE
Add Advanced section to job template form (add and edit)

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4431]
##### SUMMARY
Now that the job template form skeleton is in place and the unique fields are starting to filter in we can move forward with adding the `Advanced` section to the Job Template form.  Here's a [link](https://tower-mockups.testing.ansible.com/patternfly/templates/templates-add/) to the mockup of the add form.  Note that in the mockup, the `Advanced` section is closed by default.  If the user clicks on that `Advanced` button then the additional form section is shown (see [mockup](https://tower-mockups.testing.ansible.com/patternfly/templates/templates-add-expand/)).

Note the types of fields that appear in the `Advanced` section.  There shouldn't be any fields in this section that we don't already have patterns/examples for.  The job/skip tags fields should behave like the labels field up above.  At this point in time, there's an open PR for adding the labels field to this form.

Having this section collapsed does present some interesting problems to solve.  If there's an error with one of the fields in this section and the section is collapsed I would expect the section to open back up in order to show the erroneous field.

@trahman73, what's the expected behavior of this section when the user is editing an existing job template?  Will this section always be initially closed?

**Comment by trahman73** [comment]
@mabashian Actually, I'll remove the Advanced button from the Edit mockups so we would just show the all applicable fields in the view.

**Comment by jakemcdermott** [comment]
blocks https://github.com/ansible/awx/issues/4613, please remove blocked label from https://github.com/ansible/awx/issues/4613 when this is resolved.
