### ISSUE TITLE
Reverting logging option and saving disables entire page

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#4432]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
In `SETTINGS > SYSTEM > LOGGING`, choosing a `LOGGING AGGREGATOR TYPE` and then saving, followed by using the `REVERT` button and saving again, leaves the page in a constant `working...` state, with the entire page being unresponsive until page refresh. 

##### ENVIRONMENT
* AWX version: latest
* Operating System: Fedora 30
* Web Browser: Chrome

##### STEPS TO REPRODUCE
1. Go to `SETTINGS > SYSTEM > LOGGING`
2. Choose a logging aggregator type, like `logstash`. Save your option.
3. Hit the `REVERT` button on the logging aggregator option. Save again.

##### EXPECTED RESULTS
The page saves normally.

##### ACTUAL RESULTS
The page freezes in a `working...` state.

##### ADDITIONAL INFORMATION
In a successful save on this page, a call is made to `api/v2/settings/all`. In this bug, however, no REST call is seen in the network logs.

![Screenshot from 2019-08-06 09-54-01](https://user-images.githubusercontent.com/19942822/62545806-642b2180-b830-11e9-8b51-99699e1245b4.png)

**Comment by appuk** [comment]
On clicking the revert link, the page saves normally and does not  freeze in a working state. Hence, closing the issue.
![ezgif-3-9ba9da3af148](https://user-images.githubusercontent.com/11617351/65162074-b1410c80-da06-11e9-9de5-bed6a7571329.gif)
