### ISSUE TITLE
Fresh AWX install - login fails Code: 401

### ISSUE THREAD

**Issue by thoben** [ansible/awx#4438]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

After finishing the initial awx deployment (Docker) on a fresh Centos installation. The initial login is not functioning properly (http://awx.thoben.local/#/login).

Instead of login successfully the following message appears:

"Returned Error Code: Failed to access user information. GET returned status: 401"

##### Workaround
- Try to login through the Rest-API Interface successfully using the URL **http://awx.thoben.local/api/login/**
- After login into the REST-API interface successfully, the standard login interface (http://awx.thoben.local/#/login) starts working too (no 401 error appearing anymore)
- Workarround has to run once only & not for each session individually

##### ENVIRONMENT
* AWX version: AWX 6.1.0.0
* AWX install method: docker
* Ansible version:  ansible 2.8.1
* Operating System: CentOS Linux release 7.6.1810 (Core)
* Web Browser: Firefox 68.0.1 (64-Bit)

##### STEPS TO REPRODUCE

- clean fresh installation of Centos 7 (vm on vmware esxi)
- installing all centos updates via yum update
- installing dependencies für asx via yum & pip
- installing AWX (Docker) successfully

##### EXPECTED RESULTS

- Working login interface
- login successfully with standard admin credentials

##### ACTUAL RESULTS

"Returned Error Code: Failed to access user information. GET returned status: 401"

##### ADDITIONAL INFORMATION

<img width="372" alt="2019-08-06 22_37_37-Ansible AWX" src="https://user-images.githubusercontent.com/2189799/62575895-03393300-b89c-11e9-8878-5b4307277fcb.png">

[awx_webserver.log](https://github.com/ansible/awx/files/3474090/awx_webserver.log)

<img width="582" alt="2019-08-06 22_56_18-REST API · AWX REST API" src="https://user-images.githubusercontent.com/2189799/62576573-6ecfd000-b89d-11e9-8521-05761e5c4c46.png">

**Comment by mabashian** [comment]
@thoben we're tracking something very similar (if no identical) in #4904.  I'm glad you found a workaround.  If you do run in to this again would you mind taking a look at the browsers console and let us know if there are any errors in there?  Additionally I'd be curious to know what the response to `/api/v2/me` looks like.

**Comment by thoben** [comment]
> @thoben we're tracking something very similar (if no identical) in #4904.  I'm glad you found a workaround.  If you do run in to this again would you mind taking a look at the browsers console and let us know if there are any errors in there?  Additionally I'd be curious to know what the response to `/api/v2/me` looks like.

My Apolgizes! I did forget about checking for any responses in this project. Even after one year.... - Are you still interested in getting the requested console output - if I'm able to reproduce the issue?

Again, my apologies..

Regards,

David

**Comment by nixocio** [comment]
Reopen if we see this behavior on the new UI.
