### ISSUE TITLE
Variables of tower_workflow_job for email

### ISSUE THREAD

**Issue by bfantoni** [ansible/awx#4439]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

I want to send an email from AWX with some variables from the workflow_job I have just executed.

In the documentation of Ansible Tower, they said : (16.7 Launch a Job Template)
"Along with any extra variables set in the job template and survey, Tower automatically adds the following variables to the job environment"
After that, there is a list of variable like "tower_workflow_job_id" for example. (I have succeeded to use tower_workflow_id because it is automatically added by Tower)

I want to retrieve workflow_job information about started and finished.
It seems they are not available automatically like tower_workflow_id. Is there a way to access thoses variables ? or to add it from Tower configuration ?

##### ENVIRONMENT
* AWX version: 6.0.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.1
* Operating System: Ubuntu 16.04.6 LTS
* Web Browser: Chrome - Version 75.0.3770.142 (Build officiel) (64 bits)

##### STEPS TO REPRODUCE

I execute a workflow job and at the end the last job is to send an email (Jinja2 Template) from AWX with some variables :
- tower_workflow_job_id or tower_workflow_job_name (working)
But I want to add the information that is present in the started and finished variables I see in the browser api : awx/api/v2/workflow_jobs/[JOB ID]/

    "started": "2019-08-06T12:18:30.191202Z",
    "finished": "2019-08-06T12:18:59.440905Z",

I write the line in the jinja2 file like that but it is not working. 
Time : {{ tower_workflow_job_started }}

##### EXPECTED RESULTS

I expect to see the value of these variables. I also want to see it in a more readable format like the time in UTC+2 like that :

Start time   ==> 14:18:30 2019-08-06
Finish time ==> 14:18:59 2019-08-06

##### ACTUAL RESULTS

"msg": "The task includes an option with an undefined variable. The error was: 'tower_workflow_job_started' is undefined

**Comment by wenottingham** [comment]
This will be fixed with #79.

**Comment by wenottingham** [comment]
To be clear, this should be done via a templated notification once #79 lands; we wouldn't do this via more variables.

**Comment by bfantoni** [comment]
Hi,

Thank you for this reply.
How can I follow and know when #79 will be ready?

These are my first steps with that kind of things 😊
