### ISSUE TITLE
Feature: allow autocomplete on the AWX login page

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#444]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

The login form sets the "autocomplete=off" tag on the AWX login modal - this disables browser auto-fill.

Doesn't seem like there's a good reason to force this, so we shouldn't.

**Comment by mabashian** [comment]
Closing since #2117 was merged
