### ISSUE TITLE
Fix popovers on job template form to allow hovering

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#4443]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When specifying an scm refspec when using branch override, there are example refspecs in the tooltip that a user might want to copy/paste. Currently, the tooltip deactivates when trying to do this.
@jlmitch5 assigning you for now since you worked on the refspec field, feel free to unassign or reassign as you like.

##### ENVIRONMENT
* AWX version: latest (dependent on branch override feature)

**Comment by appuk** [comment]
everything looks good! when using branch override, the user is now able to select the text in the `scm refspec` tooltip that he can further copy/paste and the tooltip does not deactivate while doing that.
<img width="1462" alt="Screen Shot 2019-09-05 at 11 34 35 AM" src="https://user-images.githubusercontent.com/11617351/64357590-f4e15280-cfd2-11e9-961e-431720e961f0.png">
