### ISSUE TITLE
Deleting Application Token and Person Token is not properly working

### ISSUE THREAD

**Issue by elyezer** [ansible/awx#4446]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Trying to delete an Application Token is not properly working. The UI shows an error but reloading the page we see that the token is gone. 

##### ENVIRONMENT
* AWX version: 6.1.0
* AWX install method: docker on linux
* Ansible version:  Not related
* Operating System: Linux
* Web Browser: Chrome 75

##### STEPS TO REPRODUCE

Create an application token or a personal token and try to delete it

##### EXPECTED RESULTS

The token is removed and the list of tokens is reloaded to not show the deleted token anymore.

##### ACTUAL RESULTS
The token is removed but the UI shows an error message (see screenshot on additional information section) and the list is not updated. Doing a browser refresh updates it and remove the deleted token.

##### ADDITIONAL INFORMATION

![Screenshot from 2019-08-07 17-50-30](https://user-images.githubusercontent.com/48132/62660399-f10ed180-b93b-11e9-9ec7-66975a37b728.png)

See the list behind the error message the token still there and won't be gone until a browser refresh is done.

**Comment by elyezer** [comment]
Reopening so I can test it.

**Comment by dsesami** [comment]
Created personal tokens and application tokens for the user and attempted to delete them in succession. The page refreshes appropriately with new information upon deletion and no errors come up. :+1:
