### ISSUE TITLE
Remove Hipchat (discontinued 2/15/19)

### ISSUE THREAD

**Issue by jladdjr** [ansible/awx#4448]
The Hipchat service is no longer active and should be removed:
https://www.atlassian.com/partnerships/slack/faq#faq-3ccc5a61-711b-4ef2-9ca2-3a34b2ec143b

##### ISSUE TYPE
 - Feature Idea (Bug?)

![image](https://user-images.githubusercontent.com/4440360/62663228-8d7ca800-b92b-11e9-8eeb-accce0ec7eee.png)

**Comment by ryanpetrello** [comment]
> Existing Hipchat Data Center & Hipchat Server customers will have support through the end of their license period. 

Earliest we can do this is Jun 2020:

https://confluence.atlassian.com/support/atlassian-support-end-of-life-policy-201851003.html

<img width="222" alt="image" src="https://user-images.githubusercontent.com/214912/62705948-7b971580-b9bc-11e9-93eb-11c084fe7457.png">

**Comment by ryanpetrello** [comment]
@beeankha removed this awhile ago:

https://github.com/ansible/awx/pull/7075
