### ISSUE TITLE
Feature: better parameterized cleanup jobs

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#445]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

We have generic clean-up options for old jobs. People ask for multiple enhancements to this:
- only SCM updates
- only inventory updates
- per-job cleanup (on the 'COMPLETED JOBS' page for a particular job)
- per-org cleanup

##### ADDITIONAL INFORMATION

Options include doing a batch delete (dependent on https://github.com/ansible/awx/issues/19) or a new management job (dependent on writing it)

**Comment by AlanCoding** [comment]
What makes this different than clicking the delete button on the job? The multi-select batch operation?

**Comment by wenottingham** [comment]
Yes, and that the general request we've had from users is to purge all history for the job, not just one at a time.

**Comment by jcomito** [comment]
+1 for wanting to be able to remove per-job or per-org.

Anyone know of a way to do this currently?

**Comment by TheRealHaoLiu** [comment]
This is currently not possible after after we moved to partitioned tables for job events. A separate partition is created for each hour. There is no performant method of querying these tables for a specific job, and reworking that system would be quite an undertaking.
