### ISSUE TITLE
Update python 3 for awx_web/task (ansible) on hub.docker.com

### ISSUE THREAD

**Issue by frsauvage** [ansible/awx#4454]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - Installer

##### SUMMARY
Please can you please update version of python 3.6 in ansible to 2.8.2 in this two docker images?
https://hub.docker.com/r/ansible/awx_task
https://hub.docker.com/r/ansible/awx_web

May be I can do it by myself, that it is a naïve request, I apologize, I am much more a python developer than a  "_deployer_" I can't figure out how to do that from docker images.
I guess I could override python ("yum install python 3.6,  change ansible interpreter ... blablabla, debug what is missing.... :-)
I guess it could be a good idea to simply update it in docker images, as python 2 will be shortly deprecated... 

##### ENVIRONMENT
* AWX version: 6.1.0.0 latest
* AWX install method: docker on linux,from hub/docker 
* Ansible version:  2.8.2

##### STEPS TO REPRODUCE
ansible --version

##### EXPECTED RESULTS
--> python 3.6

##### ACTUAL RESULTS
--> python 2.7.5

**Comment by wenottingham** [comment]
What's the use case for this? 

The underlying image is built on CentOS 7, utilizing Ansible packages built against the system python.

**Comment by frsauvage** [comment]
Hi @wenottingham , thank you for your answer.
You are right, it is based on OS.
Is it possible to add python 3 before ansible/awx on centos image ? 

Use case ? Python 2 is deprecated, I would like to deliver my modules and plugins on python 3.

**Comment by ryanpetrello** [comment]
@frsauvage,

Our plan is to use py2 as the _default_ Python for the ansible virtualenv at least until it's officially retired (not until next year: https://github.com/python/devguide/pull/344).

In the meantime, it's possible to build a custom virtualenv using the Python version of your choosing (including python3.x).  Here are instructions for doing so:

https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md

**Comment by frsauvage** [comment]
@ryanpetrello , thank a lot for your answer.
As there is a date, it is enough for me.
I will try to use the custom awx venv, I miss this method, thank you.

**Comment by stoune** [comment]
Sorry Guys, 2020 is here and Python 2.7 is officially retired.

**Comment by wenottingham** [comment]
The base OS was changed to CentOS8, and python 3, a few releases ago.
