### ISSUE TITLE
awx-manage (de)provision_instance issue

### ISSUE THREAD

**Issue by zdriic** [ansible/awx#4458]
##### ISSUE TYPE
Issue with awx-manage provision_instance command (or deprovision_instance)

##### SUMMARY
I would like manage my cluster with the below command but this one never ends... 

bash-4.2# awx-manage deprovision_instance --hostname=myHost
Instance Removed
/bin/sh: rabbitmqctl: command not found
Node deprovisioning may have failed when attempting to remove the RabbitMQ instance myHost from the cluster
(changed: True)
2019-08-12 10:59:28,113 DEBUG    awx.main.dispatch publish awx.main.tasks.apply_cluster_membership_policies(a982e718-b977-4055-a989-d3e31c4122da, queue=awx_private_queue)

sudo -s => Same result.
It's seems to be an issue with RabbitMQ ?

##### ENVIRONMENT
* AWX version: 6.1.0
* AWX install method: docker on linux
* Ansible version:  2.8.3
* Operating System: Ubuntu 16.04
* Web Browser: Firefox

##### STEPS TO REPRODUCE

awx-manage deprovision_instance --hostname=myHost
or awx-manage provision_instance --hostname=myHost

##### EXPECTED RESULTS

The command must finish correctly to give me the prompt

**Comment by wenottingham** [comment]
When running containerized, you do not use `awx-manage` to deprovision. Use the cluster manager such as kubernetes or OpenShift to scale the image.

**Comment by zdriic** [comment]
Ok but this method worked fine with previous versions of AWX.

**Comment by wenottingham** [comment]
I'm not sure how. rabbitmq has always been in a different container, and I don't think we've ever installed rabbitmqctl in the task/tools container except possibly in the dev environment (fixed in #3740)

**Comment by zdriic** [comment]
Thanks for your answer. Could you tell me why I have RABBITMQ / DATABASE environment variables for example in awx_task/web containers on my version 1.0.6.41 and I can't find them on my version 6.1.0 after installing AWX 6.1.0 ? It's seems strange for me...
