### ISSUE TITLE
Much larger docker image size with 6.1

### ISSUE THREAD

**Issue by strawgate** [ansible/awx#4463]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Due to this PR: https://github.com/ansible/awx/pull/3852 the docker image size has grown by over 700 megabytes. It appears as though --squash was added to the development image make target but not to the production image base target and thus things like yum update, install, and clean are now all in separate layers in the production images:

<missing>           3 weeks ago         |0 /bin/sh -c rm -rf /root/.cache               0B
<missing>           3 weeks ago         |0 /bin/sh -c yum -y clean all                  1.77MB
<missing>           3 weeks ago         |0 /bin/sh -c yum -y remove cyrus-sasl-devel…   33.5MB
<missing>           3 weeks ago         |0 /bin/sh -c cd /tmp && VENV_BASE="/var/lib…   486MB
<missing>           3 weeks ago         /bin/sh -c #(nop) ADD multi:0f1c43523039b333…   9.97kB
<missing>           3 weeks ago         |0 /bin/sh -c mkdir /tmp/requirements           0B
<missing>           3 weeks ago         /bin/sh -c #(nop) ADD file:30b7ffceb853b2711…   22.4kB
<missing>           3 weeks ago         |0 /bin/sh -c pip install supervisor            3.3MB
<missing>           3 weeks ago         |0 /bin/sh -c python3 -m ensurepip && pip3 i…   11.4MB
<missing>           3 weeks ago         |0 /bin/sh -c chmod +x /tini                    19.9kB
<missing>           3 weeks ago         /bin/sh -c #(nop) ADD 4fa3d24e60ad01b3ac8419…   19.9kB
<missing>           3 weeks ago         |0 /bin/sh -c yum -y install acl   ansible  …   706MB

##### ENVIRONMENT
* AWX version: 6.1.0
* AWX install method: docker
* Ansible version:  2.8.1
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Compare awx_task and awx_web from 5.0.0 to 6.1.0

##### EXPECTED RESULTS

Image size is similar

##### ACTUAL RESULTS

Image size is very different

**Comment by ryanpetrello** [comment]
@shanemcd any thoughts on this?

**Comment by strawgate** [comment]
Care should be taken on using --squash here because if --squash is used at the end of image generation for both images they will then not share any layers at all which will cause double the storage consumption when both images are used.

**Comment by shanemcd** [comment]
This happened after I refactored the image out into more layers to make it more readable and cache-friendly. I don't care all that much, but I reckon we would need to either condense back into a mono-layer image (yuck) or use squash.

**Comment by strawgate** [comment]
Simply adding yum clean all and rm -rf /root/.cache to each yum install command should go a long way towards fixing this without having to undo all of the layer changes

**Comment by strawgate** [comment]
The image size continues to grow.
In 9.1.0 the compressed image size is now 650 MB versus 280 MB in 4.0.0.
In 9.1.0 the uncompressed image size is now 1.84GB versus 919 MB in 4.0.0

**Comment by matburt** [comment]
I'm fine with it if you want to submit a PR for this @strawgate
