### ISSUE TITLE
Feature: show artifacts set by jobs

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#447]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY

We allow people to save 'artifacts' for a job via the `set_stats` module that is used for later steps in a workflow.

We should display these in job details.

**Comment by wenottingham** [comment]
Mockups here: https://tower-mockups.testing.ansible.com/mockups/jobs/jobs-details/

**Comment by unlikelyzero** [comment]
QE Questions and Concerns:

- Will this only be available on the jobs details page?
- How would this be represented if a job is currently being run? How would this work of the job result output is lagging behind the completion of the job?
- Is there a funcional limit to how large the stat can be?
- Test responsivity with the scroll bar.
- Does Bill have any concerns with different character formats (unicode, etc)
- All functionality must be tested with Firefox 

AC:

- Needs to be accurate
- Is this displayed regardless of set_stats available?
- Needs helper text
- Needs to expand and collapse
- Needs to allow the switch between json/yaml format
- Needs to support a payload of X size?
- WFJT/SJT support?
- Do we need a download action?
- Permissions. Are set stats limited by permissions any differently than the job result screen? 
- Can they be deleted?
- Tower Upgrades will show existing jobs with artifacts as if they were run on a fresh 3.5 install.
- How many characters will a single line represent (wordwrap) (I'm guessing that many users would represent MD5 checksums here).

**Comment by wenottingham** [comment]
First stab at answers?
>  Will this only be available on the jobs details page?

Yes

>  How would this be represented if a job is currently being run? How would this work of the job result output is lagging behind the completion of the job?

I suspect the initial implementation only needs to show it when materialized on the job in the API.

> Is there a funcional limit to how large the stat can be?

No (it's similar to extra vars).

>  Does Bill have any concerns with different character formats (unicode, etc)

Follows the same format as extra_vars, presumably has the same limitations.

**Comment by kialam** [comment]
@wenottingham @chrismeyersfsu @unlikelyzero 
As it works currently, artifacts are processed _after_ the job state is transitioned to final and event processing is finished.

If a user is watching a job run in "real-time" in the job details view, they will **_not_** see Artifacts details until after a page refresh.

It would be better user experience if we can emerge the field similarly to how we are emerging the `custom_virtualenv` field on the job details page #2264. The `custom_virtualenv` value is available immediately to the UI after a job is marked as successful/done.

Currently, the `artifacts` value is _not_ available to the UI after a job is marked as successful.
<img width="398" alt="screen shot 2019-02-06 at 1 00 10 pm" src="https://user-images.githubusercontent.com/2293210/52422185-d1910c00-2ab2-11e9-9d85-770e8a0deab7.png">

The values are _only_ available after a job has successfully ran and after a refresh of the job details page.

**Comment by mabashian** [comment]
Primary work has been completed here - closing
