### ISSUE TITLE
Automation Insights Org Data Collection

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/awx#4473]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

In the collection tarball, modify the unified_job table copy to include org name & id for jobs. This can be used by Automation Insights to produce visual representations of how many jobs are being run per org organized by type & status.

**Comment by elyezer** [comment]
Here are the steps done to verify:

1) Run couple jobs
2) Gathered the analytics
3) Checked that the organization information was available on the report
4) Checked that only one entry per job run was present and it has the right Job Template and Organization information.
