### ISSUE TITLE
Automation Insights Version Tracker

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/awx#4475]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add a new `.json` file to keep track of the version of each file in the collection tarball.  

`manifest.json`
```
{
config.json: 1.0
counts.json: 1.0
query_info.json: 1.0
cred_type_counts.json: 1.0
inventory_counts.json:1.0
job_counts.json: 1.0
jobs.json: 2.0
org_counts.json: 3.0
projects_by_scm_type.json:1.0 }
```

**Comment by elyezer** [comment]
I was able to verify this by doing the following:

1) Ran the gather analytics command
2) Checked if the `manifest.json` file was present on the report
3) Check if there was one entry for every other file on the report and that each of them had a version associated with it.
