### ISSUE TITLE
adjust output page up control so that it always moves up by one visible page

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#4476]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The page up control doesn't always go up by exactly one visible page. This issue is for investigating the cause and trying some possible solutions. 

related: https://github.com/ansible/awx/pull/4383#discussion_r312235586

**Comment by mabashian** [comment]
@jakemcdermott is this still valid?  I can't tell if this was opened against the new UI or the old UI.  If it's not valid, go ahead and close.
