### ISSUE TITLE
Add custom name for login provider

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#449]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

For all our authentication providers, we have hardcoded icons and tooltip names, i.e., a Google icon and 'Sign in with Google'.

We should allow setting a 'name'  for a configuration. This name would be used in the tooltip. For example, setting the 'name' of the configuration to 'frobozz.com google domain'  would change the login tooltip to 'Login with frobozz.com google domain'.

##### ENVIRONMENT
* AWX version: 1.0.x

##### ADDITIONAL INFORMATION

This would just be a field on the login configurartion.

A custom icon could be an additional enhancement on top of this.

**Comment by shanemcd** [comment]
Going to assume there is not much demand for this given the lack of feedback or interaction on this issue.

**Comment by john-westcott-iv** [comment]
Some of the source, like SAML will say things in the tool top like "login with SAML". There is also another feature request to change the login icons to be "prettier" https://github.com/ansible/awx/pull/12705
