### ISSUE TITLE
API/SDK configure CUSTOM_LOGO doesn't take affect

### ISSUE THREAD

**Issue by LangJV** [ansible/awx#4492]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When utilizing the UI, one can head to Settings/UI and upload an image file. This "replaces" the Image file on the login screen. One can also view this image in a "data:url" format at api/v2/settings/ui CUSTOM_LOGO: "data:image/png;base64,Base64EncodedStringhere="

Attempting the same via the API or tower-cli (example below) produces no "error" and updates the CUSTOM_LOGO attribute properly when viewed in the API, but doesn't actually "take effect" in that the logo is not actually changed at login.

##### ENVIRONMENT
* AWX version: 6.1.0
* AWX install method: openshift
* Ansible version:  Whatever comes built-in with 6.1.0's ansible virtualenv
* Operating System: Openshift 3.11 running on RHEL 7.6
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Reproduce using the tower-cli:

```
with open("/path/to/a/png/file.png, 'rb') as logofile:
          logo_64_encode = base64.b64encode(logofile.read()).decode()
          created_data_url = 'data:image/png;base64,{}'.format(logo_64_encode)

# Placeholder: Setup AWX auth - however you do it since there's 10,000 ways

# Set a bunch of other settings as examples - these all WORK FINE
# Assuming you have some valid data in login_message and custom_venv_paths variables
settings_resource.modify('CUSTOM_LOGIN_INFO', login_message)
settings_resource.modify('CUSTOM_VENV_PATHS', json.dumps(custom_venv_paths))

# Setup AWX Custom Logo using above data:url - this shows a successful return and updates CUSTOM_LOGO - but never displays
settings_resource.modify('CUSTOM_LOGO', created_data_url)

```

##### EXPECTED RESULTS
if the tower-cli call succeeded (no errors) an i can see the encoded data:url in CUSTOM_LOGO - i would expect a Custom Image to be displayed at the login prompt.

##### ACTUAL RESULTS

No image is displayed. Uploading the same image via the UI's "browse" option causes it to display immediately, same apparent data:url object written to CUSTOM_LOGO

##### ADDITIONAL INFORMATION

N/A

**Comment by jakemcdermott** [comment]
@LangJV we recently added [awxkit](https://github.com/ansible/awx/tree/devel/awxkit), an sdk / cli for awx. 

With it, I've double-checked for you that one can add and update the awx logo programmatically with it.

```shell
git clone git@github.com:ansible/awx.git
pip install awx/awxkit
```

```python3
from awxkit import api, config
from awxkit.utils import PseudoNamespace as ns

# set config
config.credentials = ns({'default': {'username': 'admin', 'password': 'password'}})
config.base_url = 'http://127.0.0.1:8013'

# load logofile
logofile = open("foo.gif", "rb")
logo_64_encode = base64.b64encode(logofile.read()).decode()
created_data_url = 'data:image/gif;base64,{}'.format(logo_64_encode)

# update logo in api
root = api.Api()
root.load_session().get()
v2 = root.available_versions.v2.get()
settings_all = v2.settings.get().get_endpoint('all')
settings_all.CUSTOM_LOGO = created_data_url  # implicitly makes a patch request
```

The updated logo shows up as expected for me after doing the above steps.

I'm going to close this issue as resolved for awx. That said, I do see that the steps you provided _appear_ to be using some components of [tower-cli](https://github.com/ansible/tower-cli/). If using tower-cli components programmatically is a requirement for you and you are still seeing this issue, please create an issue in the tower-cli repo.
