### ISSUE TITLE
ansible_host ignored with delegate_to

### ISSUE THREAD

**Issue by ggiinnoo** [ansible/awx#4500]
##### ISSUE TYPE
- Bug Report

##### SUMMARY
When not using a ip or hostname in ```Host Name``` of an host, the delegate_to function doesn't use the ```ansible_host``` or ```ansible_ssh_host``` (deprecated) variables given at the host details page

##### ENVIRONMENT
* AWX version: 6.1.0
* AWX install method: docker on linux
* Ansible version:  2.8.2
* Operating System: CentOS 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Create inventory
2. Add host with as name a uuid
   73281a45-f6ed-405c-a965-d90b89db9735 (example)
3. Add the following to the details page:
```
---
ansible_host: 24.77.44.55
ansible_ssh_host: 24.77.44.55
```
(not real ip's)
4. run playbook with delegate_to in it

##### EXPECTED RESULTS

You would expect it to succeed.
I tried it with a ping run command. wich gives the following results:
![ping works](https://user-images.githubusercontent.com/3601832/63150458-1fa93e00-c007-11e9-9227-0b481ed62b00.png)

##### ACTUAL RESULTS

But when using ```delegate_to``` it fails. The ```ansible_host``` are set.
```
"msg": "Failed to connect to the host via ssh: ssh: connect to host 2bff1a port 22: Connection timed out",
```

**Comment by wenottingham** [comment]
This looks like an issue with your usage of Ansible unrelated to AWX.

This repo is for AWX issues only, please file this at https://github.com/ansible/ansible/issues , or contact the ansible-project mailing list.
