### ISSUE TITLE
AWX is not getting the private IPs of instances, if no Public IP is assigned - Google Cloud Compute Engine

### ISSUE THREAD

**Issue by lord-kyron** [ansible/awx#4501]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
In certain cases, when no public IP is used on the VM (either the GCE project is using Google Cloud NAT or there is a VPN tunnel to the project and there is no need of public IPs) AWX is not getting the private IP of the instances as "ansible_ssh_host" and is unable to connect even if there is actual connection between the AWX node and the instance.

##### ENVIRONMENT
* AWX version: 6.x.x
* AWX install method: docker
* Ansible version:  2.8.1
* Operating System: Ubuntu 18.04.2 LTS
* Web Browser: Google Chorme / Firefox

##### STEPS TO REPRODUCE
Create an inventory with google compute project as a source. Create a VM without public IP address and then sync the inventory. After the sync check the host definition in the inventory for the created VM - there is no "ansible_ssh_host" variable get from Google in the host variables, so AWX/Ansible will not be able to connect as usually when there is no such variable, ansible is trying to resolve the hostname which will not be possible. And so connection is not possible.

##### EXPECTED RESULTS
When there is no Public IP address assigned to the instance, AWX to take the Private IP to be used as "ansible_ssh_host" as variable.

##### ACTUAL RESULTS
When there is no public IP address, there is no connectivity to the GCE instance.

##### ADDITIONAL INFORMATION
After some testing and debugging I found, that the problem is on line https://github.com/ansible/awx/blob/e08e70efb48779b31f300737b085b3f3053f3520/awx/main/models/inventory.py#L2367
Now it is hardcoded to default only to the public IP address.
I suggest changing the line to:
`'ansible_ssh_host': 'networkInterfaces[0].accessConfigs[0].natIP | default(networkInterfaces[0].networkIP)'`
This way it will take the public IP if there is such assigned to the instance. If there's no public IP it will default to the private one, which is ALWAYS present.

**Comment by kdelee** [comment]
:thinking: This mostly makes sense to me. But I do wonder if we can get with the program re: `ansible_host` in favor of `ansible_ssh_host` seeing as the second is deprecated

**Comment by AlanCoding** [comment]
I looked at what the deprecated script did:

https://github.com/ansible/ansible/blob/devel/contrib/inventory/gce.py#L365

The default `ip_type` is blank string, so I believe your proposal is consistent with the expected historical behavior.

**Comment by AlanCoding** [comment]
I dug a little more, and I'm having trouble with the new expectation here. I stopped an instance, and doing so, find that it has a private IP but no public IP. In this case, the script gives `"ansible_ssh_host": null`. I'm going to find it hard time justifying this change if I cannot reproduce the behavior via the script.

**Comment by lord-kyron** [comment]
I can see that my proposal was already included in the lates release, so I will close the issue.

**Comment by ryanpetrello** [comment]
@lord-kyron if you don't mind, I'm going to leave this open so we can do some final verification on our end.

**Comment by kdelee** [comment]
Created an instance with no public ip with our GCE account, it was imported without problems and the private IP was set as the a`ansible_ssh_host`

```
gce_private_ip: XX.XXX.XX.XX
gce_public_ip: null
ansible_ssh_host: XX.XXX.XX.XX (same as above)
```

Works for me! Thanks again @AlanCoding
