### ISSUE TITLE
Label multi-select field doesn't handle unique labels

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#4504]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
<img width="337" alt="Screen Shot 2019-08-16 at 10 42 09 AM" src="https://user-images.githubusercontent.com/15881645/63177728-897d1400-c016-11e9-86a7-62c72c302581.png">

##### STEPS TO REPRODUCE
1. Navigate to awx-pf Job Template form
2. In the label multi-select field, type in the name of a label that already exists
3. Create the label

##### EXPECTED RESULTS
Label input doesn't let you create a new label. 

##### ACTUAL RESULTS
Label input lets you add multiple identical labels.

**Comment by jakemcdermott** [comment]
blocked by https://github.com/ansible/awx/issues/4613 

note: resolving 4613 might clear this issue up on it's own since 4613 is likely a component replacement. If that ends up being the case please close this.
