### ISSUE TITLE
Worflow template named_url: API access through template name 

### ISSUE THREAD

**Issue by jdorel** [ansible/awx#4508]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

`workflow_job_templates` could be accessed through the API using their name, rather than just their id.

This should be similar to how `job_templates` can be accessed using their name.

There should also be a `named_url` field in the `workflow_job_templates` objects, just as there is right now for `job_templates` objects.

**Comment by wenottingham** [comment]
This already exists.

For example, a workflow named 'Deploy to development' can be accessed at https://towerhost/api/v2/workflow_job_templates/Deploy%20to%20development++/.
