### ISSUE TITLE
mso_schema_site_anp_epg_staticport - Dont have choice for path type of the static port as VPC

### ISSUE THREAD

**Issue by Sethueha** [ansible/awx#4510]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY
mso_schema_site_anp_epg_staticport - Dont have choice for path type of the static port as VPC

##### ENVIRONMENT
* Ansible version:  2.8.2
* Operating System: RHEL 7

##### STEPS TO REPRODUCE

The current module dont have option to configure the EPG static port type as VPC. It has only one option as port, but cisco ACI has three options port, VPC and Direct Port channel.

##### EXPECTED RESULTS

The static port type should have choice as VPC

##### ACTUAL RESULTS

The static port type has only port as option.

**Comment by wenottingham** [comment]
This is an issue with the ansible module, not AWX. Please file this at https://github.com/ansible/ansible/issues/.
