### ISSUE TITLE
Gather analytics fails to upload analytics when run as awx

### ISSUE THREAD

**Issue by benthomasson** [ansible/awx#4513]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

No data is being uploaded to the analytics service.

##### ENVIRONMENT
* AWX version: 3.5.
* AWX install method: 
* Ansible version:  2.8.0
* Operating System: RHEL8
* Web Browser:  N/A

##### STEPS TO REPRODUCE

ssh to awx machine
sudo su - awx
awx-manage gather_analytics --ship

`/tmp/844d6710-0867-4b6e-8495-7ce9f559627a_2019-08-19-181335+0000.tar.gz
shipping analytics file: /tmp/844d6710-0867-4b6e-8495-7ce9f559627a_2019-08-19-181335+0000.tar.gz
No GPG-verified eggs can be found
['insights-client', '--payload', '/tmp/844d6710-0867-4b6e-8495-7ce9f559627a_2019-08-19-181335+0000.tar.gz', '--content-type', 'application/vnd.redhat.tower.analytics+tgz'] failure:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/analytics/core.py", line 132, in ship
    output = smart_str(subprocess.check_output(cmd, timeout=60 * 5))
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['insights-client', '--payload', '/tmp/844d6710-0867-4b6e-8495-7ce9f559627a_2019-08-19-181335+0000.tar.gz', '--content-type', 'application/vnd.redhat.tower.analytics+tgz']' returned non-zero exit status 1.
`

##### EXPECTED RESULTS

[root@ip-10-0-5-39 ~]# awx-manage gather_analytics --ship
/tmp/844d6710-0867-4b6e-8495-7ce9f559627a_2019-08-19-182009+0000.tar.gz
shipping analytics file: /tmp/844d6710-0867-4b6e-8495-7ce9f559627a_2019-08-19-182009+0000.tar.gz
Uploading Insights data.
Successfully uploaded report for ip-10-0-5-39.ec2.internal.

##### ACTUAL RESULTS

`/tmp/844d6710-0867-4b6e-8495-7ce9f559627a_2019-08-19-181335+0000.tar.gz
shipping analytics file: /tmp/844d6710-0867-4b6e-8495-7ce9f559627a_2019-08-19-181335+0000.tar.gz
No GPG-verified eggs can be found
['insights-client', '--payload', '/tmp/844d6710-0867-4b6e-8495-7ce9f559627a_2019-08-19-181335+0000.tar.gz', '--content-type', 'application/vnd.redhat.tower.analytics+tgz'] failure:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/analytics/core.py", line 132, in ship
    output = smart_str(subprocess.check_output(cmd, timeout=60 * 5))
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['insights-client', '--payload', '/tmp/844d6710-0867-4b6e-8495-7ce9f559627a_2019-08-19-181335+0000.tar.gz', '--content-type', 'application/vnd.redhat.tower.analytics+tgz']' returned non-zero exit status 1.
`

**Comment by benthomasson** [comment]
3.5 work around add this to the root crontab:

`0 0 * * * awx-manage gather_analytics --ship`

**Comment by benthomasson** [comment]
Here is a playbook that will enable gather analytics and will work correctly on RHEL8

`---
- name: Configures tower to gather metrics
  hosts: all 
  gather_facts: false
  become: yes 
  become_method: sudo
  tasks:
      - name: Disable celerybeat task for gather_analytics
        lineinfile:
          path: /etc/tower/conf.d/insights.py
          state: present
          line: "CELERYBEAT_SCHEDULE.pop('gather_analytics')"
      - name: Creates a cron file under /etc/cron.d
        cron:
          name: gather_analytics
          minute: 0
          hour: 0
          user: root
          job: "awx-manage gather_analytics --ship"



...`

**Comment by matburt** [comment]
Instead of using a crontab we can put down a systemd unit and enable it on a systemd timer. That'll be a little more idiomatic on our systems.

**Comment by benthomasson** [comment]
I prefer a solution to upload directly to the file upload service  https://cloud.redhat.com/api/ingress/v1/upload.   This would require storing the cloud.redhat.com credentials.  Luckily AWX is very good at storing credentials.   We could use the insights credential type for this.

**Comment by matburt** [comment]
I think the only problem with this is trusting the upload api service not to change and thus requiring us to ship a code change to fix it if it does.

**Comment by rooftopcellist** [comment]
This is fixed now.
