### ISSUE TITLE
Ansible Tower installation is getting failed(offline through package)

### ISSUE THREAD

**Issue by vivuu1989** [ansible/awx#4518]
Hi Experts,

I am trying to install Ansible tower 3.2.0 version in my Redhat machine 7.2  and getting following error. I already installed ansible version 2.8 . But tower installation is getting failed.

```
failed: [localhost] (item=[u'python-psycopg2', u'python-setuptools', u'libselinux-python', u'setools-libs', u'yum-utils', u'sudo', u'acl']) => {"ansible_loop_var": "item", "changed": false, "item": ["python-psycopg2", "python-setuptools", "libselinux-python", "setools-libs", "yum-utils", "sudo", "acl"], "msg": "The Python 2 bindings for rpm are needed for this module. If you require Python 3 support use the `dnf` Ansible module instead.. The Python 2 yum module is needed for this module. If you require Python 3 support use the `dnf` Ansible module instead."}


PLAY RECAP **************************************************************************************************************************************************
localhost                  : ok=28   changed=3    unreachable=0    failed=1    skipped=113  rescued=0    ignored=2


[error] Oops!  An error occured while running setup.
[warn] /var/log/tower does not exist.
Setup log saved to setup.log.
```
Also tried to explicity put the pyuthon2.7 entry in /etc/ansible/hosts file. but still it fails.

please advise me here. ( In my server no internet connectivity and doing through offline package)

**Comment by ryanpetrello** [comment]
Hey @vivuu1989,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

It sounds like you're using Red Hat Ansible Tower, which is a software product supported by Red Hat - please reach out to them for support for that product.

**Comment by vivuu1989** [comment]
Tried.. but no luck.. is there any workaround for this... For tower offline
installation. Getting error related to python  only

**Comment by ryanpetrello** [comment]
@vivuu1989 

It sounds like you're using Red Hat Ansible Tower, which is a software product supported by Red Hat (not the upstream AWX community, which is what this issue tracker represents) - please reach out directly to Red Hat for support for that product.
