### ISSUE TITLE
Awx on kubernetes : Server Error

### ISSUE THREAD

**Issue by alancivita** [ansible/awx#4519]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After a successful installation, awx worked fine for 2 weeks and the suddently it stopped working: The error displayed at the login page is : (see attached screenshot)
Restaring/recreating the pods didn't help.

##### ENVIRONMENT
* AWX version: 6.0.0 
* AWX install method: kubernetes
* Ansible version:  X.Y.Z
* Operating System: Centos
* Web Browser: Chrome

##### ADDITIONAL INFORMATION

![Screenshot at Aug 20 10-01-44](https://user-images.githubusercontent.com/23634711/63329173-b7719980-c331-11e9-82c0-4c2a15963843.png)
[container.log](https://github.com/ansible/awx/files/3519362/container.log)
[rabbit.log](https://github.com/ansible/awx/files/3519368/rabbit.log)
[celery.log](https://github.com/ansible/awx/files/3519370/celery.log)

**Comment by AlanCoding** [comment]
Doing a very quick pass, I would speculate that you added the instana middleware. This is [loading](https://github.com/instana/python-sensor/blob/3c81c090cc4dd933c61c733fdb9aec39c873b93a/instana/instrumentation/django/middleware.py#L90) Django middleware, only problem is that it's doing it for the 2nd time. Our AWX middleware is not written to be compatible with that. If you want wild speculation about why it started happening, maybe you upgraded the instana python package and picked up something like [this](https://github.com/instana/python-sensor/pull/181) which could easily result in double-loading of the middleware.

**Comment by alancivita** [comment]
Hi Alan, thanks for getting back
well as far as i know i haven't upgraded any package in this deployment and i have no idea what instana is :) 
I'm using kubernetes and i've used the ansible/awx*:6.0.0 docker containers.

**Comment by alancivita** [comment]
Never mind, it looks like someone played with instana as you said :)
thanks for the help.
