### ISSUE TITLE
Inventory script runs 4 times

### ISSUE THREAD

**Issue by milodanlso** [ansible/awx#4520]
##### ISSUE TYPE
 - Bug Report
 
##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

I have a custom inventory script written in Python. 
Everytime time I run it from the GUI it is run 4 times instead of once only. 
When I run the script using Python it runs once only.
I wrote a script that highlight the behaviour.

##### ENVIRONMENT
* AWX version: 6.0.0.0
* AWX docker on linux
* Ansible version:  2.8.1
* Operating System: CentOS Linux release 7.6.1810
* Web Browser: Chrome

##### STEPS TO REPRODUCE
1/ Create an inventory script in Python with the following lines :
**#!/usr/bin/env python
import time
def fonction():
    f.write("Il passe par la\n")
    return
def main():
    '''Main program'''
    print 'rhel5_64Guest:'
    print '  hosts: [server1, server2, server3]'
    print 'vcenter:'
    print '  children: [rhel5_64Guest]'
    f.write("Debut ecriture\n")
    fonction()
if __name__ == "__main__":
    f = open("output.txt", "a")
    main()
    f.close()
    time.sleep(30)**

2/ Run this inventory

3/ You see in output.txt file the following lines
**sh-4.2$ pwd
/tmp/awx_472_iro8nt09
sh-4.2$ tail -f output.txt
Debut ecriture
Il passe par la
Debut ecriture
Il passe par la
Debut ecriture
Il passe par la
Debut ecriture
Il passe par la**

**Comment by wenottingham** [comment]
See https://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html#tuning-the-external-inventory-script, notably this part:

```To satisfy the requirements of using _meta, to prevent ansible from calling your inventory with --host you must at least populate _meta with an empty hostvars dictionary.```

**Comment by milodanlso** [comment]
Thanks for that quick response that solved my problem. Sorry for the inconvenience but i start with awx and ansible :-)
