### ISSUE TITLE
Inert link to Workflow Editor Link on WJFT Form on certain Tabs

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#4523]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Unable to use link to Workflow Editor Link on WJFT Form on certain Tabs. If on the WFJT 'Details' tab, the link for Missing Job Templates found in the Workflow Editor correctly opens up the Workflow Visualizer. If on Permissions, Notifications, Completed Jobs, or Schedules, the link is inert.

##### ENVIRONMENT
* AWX version: 6.0.0 (may have never worked)
* Web Browser: Chrome and Firefox

##### STEPS TO REPRODUCE

1. Create a WFJT with Template A
2. Delete Template A such that the WFJT now contains a missing Job Template
3. Navigate to WFJT Editor form
4. Note the warning "Missing Job Templates found in the Workflow Editor"
5. When clicking the link on the details tab, the workflow viz is correctly opened.
Note: if on any other tab, the Workflow Editor form will not launch.

##### EXPECTED RESULTS
All WFJT tabs to launch the Workflow Visualizer when the error is shown.

##### ACTUAL RESULTS
Only the Details tab will launch the Workflow Visualizer when error is shown.

##### ADDITIONAL INFORMATION
<img width="1495" alt="Screen Shot 2019-08-20 at 10 39 50 AM" src="https://user-images.githubusercontent.com/12446869/63357618-b2afe400-c337-11e9-93c8-8c0847b20a6d.png">

**Comment by dsesami** [comment]
Attempted to click the WF editor link in all workflow job template tabs -- the link works correctly on all tabs.
