### ISSUE TITLE
Hide prompt button on survey form when only prompt is extra vars

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4528]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
On the schedule form, the prompt button should not be shown when the only prompt is extra vars.  Extra var prompting is done through the form itself.  This is a break from the usual prompting behavior.

Form:
<img width="1485" alt="Screen Shot 2019-08-20 at 11 26 49 AM" src="https://user-images.githubusercontent.com/9889020/63361044-7089a100-c33d-11e9-8d2e-dfd05f2b5ace.png">

Clicking prompt button:
<img width="1524" alt="Screen Shot 2019-08-20 at 11 26 56 AM" src="https://user-images.githubusercontent.com/9889020/63361053-741d2800-c33d-11e9-8496-6193f8308dbb.png">

##### ENVIRONMENT
awx: 6.1.0

##### STEPS TO REPRODUCE
1) Create a JT that only prompts for extra vars
2) Create a schedule for JT in step 1
3) Click on Prompt button in schedule form

##### EXPECTED RESULTS
No prompt button

##### ACTUAL RESULTS
Prompt button, empty modal

**Comment by dsesami** [comment]
Prompt button does appear when other prompts exist, but does not appear when it is only extra vars that is prompted. Marking as fixed and closing.
