### ISSUE TITLE
Add changed state for playbooks in the UI and Notifcations

### ISSUE THREAD

**Issue by ismc** [ansible/awx#453]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

There is no way to get a changed state in the AWX UI to detect configuration drift.  You either get a failed with an associated red dot or passed with an associated green dot.  Same with notifications.  This is particularly useful for detecting configuration drift on network equipment now that AWX added `diff`.  An operator could see that there is an out-of-compliance devices with either a yellow dot and/or notification, then go see what the actual difference is on that device.

##### STEPS TO REPRODUCE

N/A

##### EXPECTED RESULTS

N/A

##### ACTUAL RESULTS

N/A

##### ADDITIONAL INFORMATION

N/A

**Comment by wenottingham** [comment]
I think this is conflating the status of a host (which can have a changed status) with current playbook status (which is success/failure only). Even if we did return this for playbook, all it would say is that *some* host had a changed event, and you'd have to go back to the API for stats on the hosts to find the info at a host level. It would seem simplest to do this level of introspection in all success cases.

**Comment by ismc** [comment]
True, it would say that _some_host changed, then the operator looks in the playbook output to see which host(s) changed and what the diff was.  That seems like a useful workflow and easier than seeing that a host has changed then trying to figure out why/how it changed.  Do we have a better/recommended way built-in to AWX/Tower for detecting configuration and alerting the operator?  After all, that is one of the features that we attribute to AWX/Tower.  I am not wed to any particular solution, I just think that Tower needs the capability to provide notification on configuration/desired state drift.

**Comment by wenottingham** [comment]
The idea of the notifications is (eventually) to get to a point where you don't necessarily have to go to AWX/Tower to get the information out you need.

When I look at this, this is just setting another knob that then forces you to go back to AWX to make sense of this... while that may be expected for the 'failed' case, it shouldn't be for most cases.

Rather than separate notification types, I think this may be better solved by templated notifications (see https://github.com/ansible/awx/issues/79) and having that include the stats dump for different hosts?

**Comment by matburt** [comment]
Either way this isn't something that I think we are interested in on a basic level. If you want to implement it and submit a PR we can evaluate it then.

**Comment by ismc** [comment]
Part of my request was for improving notifications, so I completely agree with that being operationally more efficient.  I would definitly like to see #79 implemented.  Not quite sure that I agree on the changed status.  It seems like basic concept completeness, but getting half of what I want is much better than I usually get out of life, so we'll call this a success :)
