### ISSUE TITLE
Unable to remove customized messages from notification template

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#4531]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Unable to remove customized messages from notification template

##### STEPS TO REPRODUCE
1. Create a Slack notification with customized notification messages.
2. Edit Slack notification from step 1 and remove customized notification messages via toggle and save
Note: 500 error

##### EXPECTED RESULTS
1. Default messages used and customize message toggle disabled

##### ACTUAL RESULTS
HTTP 500 from API

##### ADDITIONAL INFORMATION

<img width="1497" alt="Screen Shot 2019-08-20 at 12 43 30 PM" src="https://user-images.githubusercontent.com/12446869/63366604-222dcf80-c348-11e9-80b7-a53a717a4b9f.png">

**Comment by jladdjr** [comment]
@unlikelyzero - how did you remove the custom notification message? Did you just toggle off "CUSTOMIZE MESSAGES..." in the ui?

**Comment by unlikelyzero** [comment]
@jladdjr yea, sorry, updating repro steps

**Comment by jladdjr** [comment]
I believe https://github.com/jladdjr/awx/commit/b40566f513d604a2a2588b6ba843e26a7314a95e should fix this. I'm now able to follow your steps and can confirm custom notifications are erased (set to null, which will prompt awx to use the defaults). Can you take this for a spin again?

**Comment by unlikelyzero** [comment]
Verified on latest
