### ISSUE TITLE
Unable to a new line to Start, Success, and Failure Message for Customized Email Notification Types

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#4538]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Unable to a new line to Start, Success, and Failure Message for Customized Email Notification Types. 

Notes:

- New lines can be added to Start, Success and Failure Message **Body** however.
- Message, itself, can be modified as long as a new line is not added

##### STEPS TO REPRODUCE

1. Create a working email notification
2. Modify the notification's customizable messages by adding a new line to Start Message.
3. Assign Notification to JT and launch JT.
Note: Start Message not received.

##### EXPECTED RESULTS
1. Modified Start Message to be received.

##### ACTUAL RESULTS
No start message received. If Job failed/succeeded, then the customized notification success/failure message is received.

##### ADDITIONAL INFORMATION

This works
![Screen Shot 2019-08-20 at 6 20 15 PM](https://user-images.githubusercontent.com/12446869/63388655-2cb38d80-c377-11e9-8aef-85ebe62db98e.png)

This doesn't
![Screen Shot 2019-08-20 at 6 20 45 PM](https://user-images.githubusercontent.com/12446869/63388687-3f2dc700-c377-11e9-8a8b-9f1cce981d3a.png)

**Comment by jladdjr** [comment]
Was able to repro this. Logs show:

```
awx_1        | 2019-08-21 06:58:18,269 ERROR    awx.main.tasks Send Notification Failed Header values can't contain newlines (got "Job #4 'JobTemplate - DirectionPayment?' running: https://towerhost/#/jobs/playbook/4\n\ntest" for header 'Subject')
```

Will need to add some extra validation for this.

**Comment by keithjgrant** [comment]
Should we prohibit newlines in the UI? Or do some notification types support them?

**Comment by jladdjr** [comment]
Checked up on each of the notification types and I'm not seeing any that would support multilines.

**Comment by unlikelyzero** [comment]
@keithjgrant @jladdjr @ryanpetrello let's get rid of the ability to enter newlines in that form or provide some sort of error. At the moment, I enter new lines and the NT is not fired

**Comment by unlikelyzero** [comment]
Verified that error text appears in line on email and pagerduty.
It's still possible to save with an invalid form and create an invalid NT resource

**Comment by jladdjr** [comment]
Updated validation to ensure messages field does not contain newlines (newlines in body field are okay).

![repro](https://user-images.githubusercontent.com/4440360/63646034-e6846400-c6bf-11e9-9bb8-48621b0d88c0.gif)

**Comment by dsesami** [comment]
Verified that newline validation in the UI occurs correctly and that I can't introduce newlines now.
