### ISSUE TITLE
ec2.py dynamic inventory is out of date

### ISSUE THREAD

**Issue by LavaToaster** [ansible/awx#454]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
ec2.py is out of date with that of the ansible-contrib version.

##### ENVIRONMENT
n/a

##### STEPS TO REPRODUCE

Look at [current awx ec2.py](https://github.com/ansible/awx/blob/devel/awx/plugins/inventory/ec2.py) and look at [current contrib ec2.py](https://github.com/ansible/ansible/blob/devel/contrib/inventory/ec2.py)

##### ADDITIONAL INFORMATION

I want to be able to use the IAM Sts:AssumeRole feature so that I don't have to provide AWX with credentials to the AWS accounts it needs to, when instead it can pivot using the credentials given to the machine via its instance profile.

**Comment by wenottingham** [comment]
We may pull the 2.4 version at some point.

However, see https://github.com/ansible/awx/issues/171 - these will all be replaced in the short-to-medium-term future.

**Comment by matburt** [comment]
This is a task that we periodically perform during the release process
