### ISSUE TITLE
Google Cloud Compute Engine credential type is stripping the json file

### ISSUE THREAD

**Issue by lord-kyron** [ansible/awx#4542]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When a google compute engine credential is created with the json credential file, AWX is stripping some valuable lines. I need those, as I am using gcp_compute_disk module which also requires the service account file to be give as absolute path to the json and instead of giving the file path twice manually, I am using {{ lookup('env','GCP_SERVICE_ACCOUNT_FILE') }} to refer the absolute path to the json, but I am getting error that the lines about email and token_uri are missing.
In order to resolve that I was forced to create a custom credential type for uploading the json and use it without stripping.

##### ENVIRONMENT
* AWX version: 6.x.x
* AWX install method: docker
* Ansible version:  2.8.2
* Operating System: Ubuntu 18.04
* Web Browser: Firefox, Chrome

##### STEPS TO REPRODUCE

Upload a google json credential to awx and try to use the service_account_file: "{{ lookup('env','GCP_SERVICE_ACCOUNT_FILE') }}" when using the gcp_compute_disk module for example. Your AWX template must be pointed to the gce credential also.

##### EXPECTED RESULTS

get the full json and take all needed lines

##### ACTUAL RESULTS

gets the json, but it seems the AWX module for gce credenials strips some lines and the file is usable by the gcp_compute_* ansible modules.

##### ADDITIONAL INFORMATION
New credential type I've used to get around this is:

Input configuration:
`fields:
  - id: gcp_credential_file
    type: string
    label: GCP Credential File (JSON)
    secret: true
    multiline: true`

Injector configuration:
`env:
  GCP_SERVICE_ACCOUNT_FILE: '{{ tower.filename }}'
file:
  template: '{{ gcp_credential_file }}'`

**Comment by ryanpetrello** [comment]
@AlanCoding is this related to https://github.com/ansible/awx/pull/4072 ?

I'd expect that change to address this, and it looks to me like it went into AWX 6.1.0.

**Comment by ryanpetrello** [comment]
@lord-kyron can you share the contents of the *actual* config file laid down, vs. what you'd expect?  Also, what version of AWX are you using?  Is it the latest?

**Comment by AlanCoding** [comment]
^ these are important questions. To recap the important change from #4072, we added another env var `GCP_SERVICE_ACCOUNT_FILE` which references the credential file (also referenced by a deprecated env var name). this would fit with what you reported if the module failed to recognize any credential file.

**Comment by lord-kyron** [comment]
@ryanpetrello @AlanCoding 
I first faced this in 6.0.0 and there was the first time I developed the workaround, but yesterday I installed 6.1.0 fresh and forgot about my workaround and since I was using the same playbooks, I faced the same issue.
Here is what I am calling in my playbook:
`   - name: create a disk
     gcp_compute_disk:
         name: "disk-{{ dc_prefix }}-test-vm-{{ item }}"
         size_gb: 50
         source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts'
         type: 'pd-ssd'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "serviceaccount"
         service_account_file: "{{ lookup('env','GCP_SERVICE_ACCOUNT_FILE') }}"
         state: present
     loop: "{{ lookup('sequence','count='+vm_num|string).split(',') }}"`

Here is the error output with the AWX default gce credenital type:
`{
    "exception": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1566381907.01-242728289292873/AnsiballZ_gcp_compute_disk.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1566381907.01-242728289292873/AnsiballZ_gcp_compute_disk.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1566381907.01-242728289292873/AnsiballZ_gcp_compute_disk.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_gcp_compute_disk_payload_z3tLPR/__main__.py\", line 705, in <module>\n  File \"/tmp/ansible_gcp_compute_disk_payload_z3tLPR/__main__.py\", line 456, in main\n  File \"/tmp/ansible_gcp_compute_disk_payload_z3tLPR/__main__.py\", line 544, in fetch_resource\n  File \"/tmp/ansible_gcp_compute_disk_payload_z3tLPR/ansible_gcp_compute_disk_payload.zip/ansible/module_utils/gcp_utils.py\", line 84, in get\n  File \"/tmp/ansible_gcp_compute_disk_payload_z3tLPR/ansible_gcp_compute_disk_payload.zip/ansible/module_utils/gcp_utils.py\", line 131, in session\n  File \"/tmp/ansible_gcp_compute_disk_payload_z3tLPR/ansible_gcp_compute_disk_payload.zip/ansible/module_utils/gcp_utils.py\", line 158, in _credentials\n  File \"/usr/lib/python2.7/site-packages/google/oauth2/service_account.py\", line 209, in from_service_account_file\n    filename, require=['client_email', 'token_uri'])\n  File \"/usr/lib/python2.7/site-packages/google/auth/_service_account_info.py\", line 72, in from_filename\n    data = json.load(json_file)\n  File \"/usr/lib64/python2.7/json/__init__.py\", line 290, in load\n    **kw)\n  File \"/usr/lib64/python2.7/json/__init__.py\", line 338, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib64/python2.7/json/decoder.py\", line 366, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib64/python2.7/json/decoder.py\", line 384, in raw_decode\n    raise ValueError(\"No JSON object could be decoded\")\nValueError: No JSON object could be decoded\n",
    "ansible_loop_var": "item",
    "_ansible_item_label": "1",
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1566381907.01-242728289292873/AnsiballZ_gcp_compute_disk.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1566381907.01-242728289292873/AnsiballZ_gcp_compute_disk.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1566381907.01-242728289292873/AnsiballZ_gcp_compute_disk.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_gcp_compute_disk_payload_z3tLPR/__main__.py\", line 705, in <module>\n  File \"/tmp/ansible_gcp_compute_disk_payload_z3tLPR/__main__.py\", line 456, in main\n  File \"/tmp/ansible_gcp_compute_disk_payload_z3tLPR/__main__.py\", line 544, in fetch_resource\n  File \"/tmp/ansible_gcp_compute_disk_payload_z3tLPR/ansible_gcp_compute_disk_payload.zip/ansible/module_utils/gcp_utils.py\", line 84, in get\n  File \"/tmp/ansible_gcp_compute_disk_payload_z3tLPR/ansible_gcp_compute_disk_payload.zip/ansible/module_utils/gcp_utils.py\", line 131, in session\n  File \"/tmp/ansible_gcp_compute_disk_payload_z3tLPR/ansible_gcp_compute_disk_payload.zip/ansible/module_utils/gcp_utils.py\", line 158, in _credentials\n  File \"/usr/lib/python2.7/site-packages/google/oauth2/service_account.py\", line 209, in from_service_account_file\n    filename, require=['client_email', 'token_uri'])\n  File \"/usr/lib/python2.7/site-packages/google/auth/_service_account_info.py\", line 72, in from_filename\n    data = json.load(json_file)\n  File \"/usr/lib64/python2.7/json/__init__.py\", line 290, in load\n    **kw)\n  File \"/usr/lib64/python2.7/json/__init__.py\", line 338, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib64/python2.7/json/decoder.py\", line 366, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib64/python2.7/json/decoder.py\", line 384, in raw_decode\n    raise ValueError(\"No JSON object could be decoded\")\nValueError: No JSON object could be decoded\n",
    "rc": 1,
    "module_stdout": "",
    "item": "1",
    "changed": false,
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "_ansible_no_log": false
}`

Among this output I found that the problem is once the json is uploaded, it seems the credential type plugin strips client_email and token_uri from the json. Here is the line from the error referencing that:
`File \"/usr/lib/python2.7/site-packages/google/oauth2/service_account.py\", line 209, in from_service_account_file\n    filename, require=['client_email', 'token_uri'])\n`

And that is why I was forced to create a new credential type to avoid this.

**Comment by AlanCoding** [comment]
I'm a little worried that the interpretation of the behavior might be wrong. Let me present two exhibits:

1. https://github.com/AlanCoding/utility-playbooks/blob/master/gce_lookup.yaml
2. https://github.com/ansible/test-playbooks/blob/master/cloud_modules/gce.yml

Item 1 is my attempt at reproducing this exact issue. Item 2 is a more generic example about using the gce modules.

> it seems the credential type plugin strips client_email and token_uri from the json

I really don't think this is correct. The treatment of these parameters is not all all different from the others.

On the other hand, I completely believe that these are not present via their _environment variable_ aliases. These have moved, and I will admit to not fully knowing what the right names to use for them are. I could see the client library getting `GCP_AUTH_KIND` from env vars, and then expecting to get email from another env var and failing. But this is simply speculation.

In both cases 1 and 2, I get it to run locally. Now there might be more complications if I switched the state from absent to present. I'm not sure.

But this is also talking about a fairly non-standard way to apply the credential, and I'd rather focus on energy on getting case 2 right, and working to document what that looks like.
