### ISSUE TITLE
Send Ad-hoc events to log Aggregator

### ISSUE THREAD

**Issue by saali2016** [ansible/awx#4545]
##### ISSUE TYPE
Currently we have no way to ship ad-hoc command to the log aggregator 
/api/v2/ad_hoc_commands/

When a user executes an ad-hoc command, a single activity_stream event is sent representing the creation of the command  but no other information is. None of the 'ad_hoc command events' available in the Tower API are sent.

**Comment by ryanpetrello** [comment]
I'm able to reproduce this.

**Comment by kdelee** [comment]
I have confirmed that when setting up external logging (I used loggly), and sending `job_events`, that ad_hoc commands end up showing up in external logger.

![Screenshot from 2019-09-19 13-35-53](https://user-images.githubusercontent.com/29239279/65267242-9fcd3280-dae2-11e9-9fe2-f61ba4ef3345.png)
