### ISSUE TITLE
Error handling for invalid form entry for NT custom messages isn't prescriptive or defensive

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#4546]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Error handling for invalid form entry for Customized messages in NT isn't prescriptive or defensive. Example https://github.com/ansible/awx/issues/4539

##### STEPS TO REPRODUCE
Repro in https://github.com/ansible/awx/issues/4539

##### EXPECTED RESULTS
Defensive form entry to prevent bad input. OR
Prescriptive feedback on how to correct bad form entry

##### ACTUAL RESULTS

Nondescript error message

##### ADDITIONAL INFORMATION

https://github.com/ansible/awx/issues/4539

**Comment by jladdjr** [comment]
@unlikelyzero - When I run through the steps to reproduce I see `Failed to add new notifier. Field 'extra_vars' unavailable.`:

![image](https://user-images.githubusercontent.com/4440360/63543283-4e2b8b00-c4d7-11e9-9dd6-259444be688e.png)

Does that look okay?

**Comment by unlikelyzero** [comment]
yes that's perfect
