### ISSUE TITLE
How to enable CORS on awx-tower? Documentation needed.

### ISSUE THREAD

**Issue by themalaikulfi** [ansible/awx#4547]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I would like to use the AWX API to run jobs from a custom front-end, however I am unable to get past the authentication surrounding it. If I provide credentials in the header, I get no response and if I don't provide any headers I get : 
{"detail":"Authentication credentials were not provided. To establish a login session, visit /api/login/."}

Our AWX version was recently upgraded in order to have CORS enabled, however I am unable to find any documentation for how to set up CORS other than this feature request:
https://github.com/ansible/awx/issues/1519

I have tried installing django-cors-headers and added in setup.py :
INSTALLED_APPS = ['corsheaders' ]
MIDDLEWARE = [
'corsheaders.middleware.CorsMiddleware',
'django.middleware.common.CommonMiddleware'
]

CORS_ORIGIN_ALLOW_ALL = True

That caused all kinds of errors.

I request any documentation regarding how to enable CORS so I can access the API through my front-end. 

##### ENVIRONMENT
* AWX version: 6.1.0
* AWX install method: docker on linux
* Ansible version:  2.8.2
* Operating System: CentOS Linux release 7.6.1810 (Core)
* Web Browser: firefox

**Comment by ryanpetrello** [comment]
@themalaikulfi what errors are you seeing?

**Comment by ryanpetrello** [comment]
Since you asked this question over on https://github.com/ansible/awx/issues/1519#issuecomment-523607418, let's track it there.

Also, this issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, you might get a quicker response on our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by ajmerhasan** [comment]
i am using branch 17.0.1 from https://github.com/ansible/awx.git and using install using docker

i followed as per suggested in docs/cors.md

i made changes accordingly :
awx/installer/roles/local_docker/tasks/compose.yml
task : Create Docker Compose Configuration
...
- file: cors.py
  mode: "0664"
...

awx/installer/roles/local_docker/templates/docker-compose.yml.j2
web:
  ...
  volumes:
    ...
    - "{{ docker_compose_dir }}/cors.py:/etc/tower/conf.d/cors.py"

task:
  ...
  volumes:
    ...
    - "{{ docker_compose_dir }}/cors.py:/etc/tower/conf.d/cors.py"

#new file
awx/installer/roles/local_docker/templates/cors.py.j2
![image](https://user-images.githubusercontent.com/2297652/164394296-7596ab31-ef38-4e31-ae01-00b176b68d41.png)

cd awx/installer/
ansible-playbook -i inventory install.yml

it helped me fixed the problem. hope it help others as well.
