### ISSUE TITLE
RFE: Add toggle for "Disable Local User Log-in" setting

### ISSUE THREAD

**Issue by hiyokotaisa** [ansible/awx#4553]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

When the external authentication (LDAP/SAML/OAuth etc.) is enabled, there is a use-case to turn off the authentication for local users for security reason.

It would be great if there is a toggle switch to turn on/off authentication for local users. When the local auth is disabled, it is not able to log in via local users but Tower can use built-in admin user in backup/restore process.

**Comment by agilleyrh** [comment]
This feature would alleviate security concerns in highly regulated environments.

**Comment by wenottingham** [comment]
The simplest way to do this is (right now, without code changes) to remove the local users.

**Comment by kdelee** [comment]
@one-t hoping you can take lead on testing this one

**Comment by one-t** [comment]
Just a UI note, we can't take away the username and password entry with LDAP and RADIUS.

**Comment by tiagodread** [comment]
@one-t this issue can be closed?
