### ISSUE TITLE
Management Jobs shown in two columns instead of three

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4554]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
<img width="1558" alt="Screen Shot 2019-08-22 at 10 26 36 AM" src="https://user-images.githubusercontent.com/9889020/63523057-727f6b80-c4c7-11e9-9852-469a677053f9.png">

##### ENVIRONMENT
* AWX version: 6.1.0

##### STEPS TO REPRODUCE
1. Go to Management Jobs
2. Observe

##### EXPECTED RESULTS
3 columns

##### ACTUAL RESULTS
2 columns

**Comment by appuk** [comment]
Management Jobs are shown in 3 columns, hence closing the issue
![Screen Shot 2019-09-17 at 4 13 23 PM](https://user-images.githubusercontent.com/11617351/65076061-2c9eb180-d966-11e9-80d7-538580c4da8a.png)
