### ISSUE TITLE
Small widths cause the sparkline to be overlapped by the launch button on dashboard

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#4568]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Using narrower and narrower widths cause the launch button on the dashboard to start to overlap the sparkline, which looks odd and prevents you from clicking the sparkline. Simply put, this happens:
![Screenshot from 2019-08-22 14-32-46](https://user-images.githubusercontent.com/19942822/63540478-242f9400-c4ea-11e9-9116-5a1491010fe3.png)

##### ENVIRONMENT
* AWX version: latest on chrome
##### STEPS TO REPRODUCE
Launch some jobs to get a sparkline. narrow the screen to half-width on something like a laptop or some smaller width.
##### EXPECTED RESULTS
The launch button avoids the sparkline.
##### ACTUAL RESULTS
The launch button overlaps the sparkline.

**Comment by appuk** [comment]
Another issue on the dashboard page, where the summary of Inventories and Inventory Sync Failures is not getting wrapped properly on small widths
![Screen Shot 2019-10-24 at 1 27 22 PM](https://user-images.githubusercontent.com/11617351/67694679-2397fb80-f97a-11e9-8a16-563a74d7078e.png)

**Comment by AlexSCorey** [comment]
This issue is no longer valid n the new UI. Closing.
