### ISSUE TITLE
Satellite 6 Inventory does not include hosts that are not "managed"

### ISSUE THREAD

**Issue by alexander-bauer** [ansible/awx#457]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

Satellite 6 inventory does not list hosts that are not managed by Foreman, leaving the inventory incomplete. I think this is different from a behavior I used to see in AWX 1.0.0 and Ansible 2.3. This is a necessary behavior, as I am migrating old hosts to be Foreman-managed using Ansible.

##### ENVIRONMENT
* AWX version: 1.0.1.31
* AWX install method: docker on linux
* Ansible version:  2.4.0

##### STEPS TO REPRODUCE

1. Configure a Satellite 6 inventory
1. Add a host to Satellite 6 that is not "managed"
1. Sync the inventory
1. The new host is not listed in Hosts.

##### EXPECTED RESULTS

The new host should be listed in Hosts.

##### ACTUAL RESULTS

The new host is not listed in Hosts, or used as part of the inventory.

##### ADDITIONAL INFORMATION

Running an old copy of the Foreman remote inventory script on another machine, I am able to see the un-managed hosts alongside hostvars and `groups['all']`. This makes the AWX behavior even stranger. 

The unmanaged hosts cannot even be iterated over with `groups['all']`.

**Comment by matburt** [comment]
Can you verify that this behavior is different than what would happen if you ran the ansible core satellite inventory script (which is basically what we are pulling in)?

**Comment by alexander-bauer** [comment]
@matburt  Using the inventory script from upstream on [stable-2.4](https://github.com/ansible/ansible/blob/stable-2.4/contrib/inventory/foreman.py), I get the whole inventory, including host that aren't managed by Foreman. My `ansible.cfg` and `foreman.ini` are as follows:

```
# ansible.cfg
[defaults]
inventory = ./foreman.py
bin_ansible_callbacks = True
callback_whitelist = foreman
ask_pass = True

[privilege_escalation]
become = True
become_ask_pass = True
```

```
# foreman.ini
[foreman]
url=https://foreman.<domain>
user=<ansible_foreman_user>
password=<password>
ssl_verify=true
```

**Comment by matburt** [comment]
Can you try pulling that inventory script into AWX to see if it fixes your issue?

**Comment by matburt** [comment]
Let us know if pulling the new ansible inventory script was able to work for you, in the meantime I'm going to close this out.
