### ISSUE TITLE
CLI: awx credential create difficulties

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#4570]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Two issues, could be convinced these are not bugs but would like to have discussion about it.

1) Not clear what to pass for `credential_type`. Now that I've been working with the CLI more I knew I needed to probably provide a credential type id, but reptile brain still wanted to put `--credential_type ssh`. Would like to have it described as `CREDENTIAL_TYPE_ID`
![image](https://user-images.githubusercontent.com/29239279/63542163-b6856700-c4ed-11e9-93d9-b6eccc1f5268.png)

This is along the lines of other items that need a project id, but the help says PROJECT, etc. Would prefer that `PROJECT_ID` is specified, etc etc.

2) Credentials require a user XOR organization XOR team, and again, these should be USER_ID, ORGANIZATION_ID, TEAM_ID. Because it is one of these three, the help text is not showing you that you must have one of the three.

The API does tell you though when you try. (also affected by https://github.com/ansible/awx/issues/4565
##### STEPS TO REPRODUCE

```
awx credentials create --help
usage: awx credentials create [-h] --name TEXT [--description TEXT]
                              [--organization ORGANIZATION] --credential_type
                              CREDENTIAL_TYPE [--inputs INPUTS] [--user USER]
                              [--team TEAM]

required arguments:
  --credential_type CREDENTIAL_TYPE
                        [REQUIRED] Specify the type of credential you want to
                        create. Refer to the Ansible Tower documentation for
                        details on each type.

optional arguments:
  -h, --help            show this help message and exit
  --description TEXT    Optional description of this credential.
  --organization ORGANIZATION
                        Inherit permissions from organization roles. If
                        provided on creation, do not give either user or team.
  --inputs INPUTS       Enter inputs using either JSON or YAML syntax. Use the
                        radio button to toggle between the two. Refer to the
                        Ansible Tower documentation for example syntax.
  --user USER           Write-only field used to add user to owner role. If
                        provided, do not give either team or organization.
                        Only valid for creation.
  --team TEAM           Write-only field used to add team to owner role. If
                        provided, do not give either user or organization.
                        Only valid for creation.

required arguments:
  --name TEXT           [REQUIRED] Name of this credential.

awx credentials create: the following arguments are required: --name, --credential_type
```

#### EXPECTED RESULTS:
1) Tell me I need ID's for related objects
2) Tell me I need one of `CHOICES: [user, team, organization]`

**Comment by ryanpetrello** [comment]
@kdelee I think my PR for name support (https://github.com/ansible/awx/pull/4640) makes this a lot easier now: 

```
~ awx credentials create --credential_type 'Machine' --name 'My SSH Key' --user 'ryan' --inputs "{'ssh_key_data': '@~/.ssh/id_rsa', 'ssh_key_unlock': 'example-pass'}"
{
     "id": 7,
     "type": "credential",
     "url": "/api/v2/credentials/7/",
     "summary_fields": {
          "created_by": {
```

![image](https://user-images.githubusercontent.com/214912/64208358-a87c0280-ce6c-11e9-9c4d-6e90968ac873.png)

**Comment by kdelee** [comment]
Works for me. Maybe someday we can make it possible to nest file references in files :smiling_imp: 

Example:
`awx credentials create --credential_type 'Machine' --name 'My SSH Key' --user 'ryan' --inputs "@my_nested_args.json"`
where my_nested_args.json looked like `{'ssh_key_data': '@~/.ssh/id_rsa', 'ssh_key_unlock': 'example-pass'}`
