### ISSUE TITLE
Cannot execute tasks as sudo 

### ISSUE THREAD

**Issue by AndreMTrindade** [ansible/awx#4579]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I have using AWX for a while and when i executed tasks as root all worked perfetly but recently i have been forced to changed to use a user with sudo privileges and it is not possible use sudo on awx. 

##### ENVIRONMENT
* AWX version: AWX 6.1.0.0
* AWX install method:  docker on linux
* Ansible version: 2.8.2 
* Operating System: Cent OS
* Web Browser: Mozilla Firefox

##### STEPS TO REPRODUCE

1 - Create a playbook with shell attribute with become: true and command with privilege requirements. 
2 - Create a job with option "ENABLE PRIVILEGE ESCALATION" enabled and with playbook associated. 
3 - Create a credentials with:
          * Credential Type: Machine 
          *  Username: Some_Think
          * Password: ******
          * Privilege Escalation Method: sudo 
          * Privilege Escalation Username: Some_Think
          * Privilege Escalation Password: ******
4 - Run the playbook ans check the output. 

##### EXPECTED RESULTS
Task executed 

##### ACTUAL RESULTS
Permission denied

**Comment by ryanpetrello** [comment]
Hey @AndreMTrindade,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

It looks as if you've already asked about this elsewhere: https://groups.google.com/forum/#!topic/awx-project/xCmjY_92nEo

...so I'm going to close this issue.

**Comment by AndreMTrindade** [comment]
Good afternoon. For reference the issue is that i was trying to escalate for my user. I removed my username from "Privilege Escalation Username" and it´s working. Thanks.
