### ISSUE TITLE
CLI: awx job_templates create --help does not indicate all required args

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#4583]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

`awx job_template create --help` is missing several required args

##### EXPECTED RESULTS

```
                                                                                                                     
required arguments:                                        
  --name TEXT           Name of this job template.
  --inventory INVENTORY ID <more text>
  --project PROJECT ID <more text>
  --playbook TEXT <more text>
```

##### ACTUAL RESULTS

```
required arguments:
  --name TEXT           Name of this job template.
```

**Comment by ryanpetrello** [comment]
_Technically_ `--inventory` is **not** required, because you _could_ specify `--ask_inventory_on_launch`.  Our `OPTIONS` don't really capture these requirements of "*one* of these must be specified", so it's going to be difficult to make the CLI do the same.

```shell
$ awx job_templates create --name 'Foo' --project 6
{"inventory": ["Must either set a default value or ask to prompt on launch."]}
```

**Comment by kdelee** [comment]
works for me!
