### ISSUE TITLE
Smart Inventory caps at 101 hosts

### ISSUE THREAD

**Issue by djseiss** [ansible/awx#4588]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Using mulitple OpenStack inventories (single source^1 for each), the creation of a smart inventory to filter an inventory with all hosts (from OpenStack inventories) via AWX web ui only allows 101 hosts per smart inventory.

Is this an intended cap? Cannot find any documentation on this.

^1= What I mean by this is a single "Inventory" is made under Inventories. This "Inventory" has only one source under "Sources" and is a OpenStack source.

##### ENVIRONMENT
* AWX version: 6.1.0
* AWX install method: docker on linux
* Ansible version:  2.8.4
* Operating System: centos7
* Web Browser: Chrome

##### STEPS TO REPRODUCE
1. Create two inventories with a single OpenStack source that when combined have over 101+ hosts.
2. Create a smart inventory that would collect all hosts (over 101+) using the smart host filter.

##### EXPECTED RESULTS
Smart inventory collects all hosts.

##### ACTUAL RESULTS
Smart inventory collects only 101 hosts.

**Comment by wenottingham** [comment]
Just to be clear: you only see 101 hosts in the preview, or you only get 101 hosts out of the saved smart inventory?

**Comment by djseiss** [comment]
I only get 101 hosts out of a saved smart inventory. I have tried multiple smart hosts filters and they seem to all cap out at 101.

The preview (I assume you mean when adding a smart host filter?) shows 123 hosts, which is the total hosts I have. But when saving the inventory I only get 101.

**Comment by djseiss** [comment]
Update: I moved my multiple OpenStack inventories (broken down by different endpoints and singled sourced for each endpoint) into a single OpenStack inventory with multiple sources. I created a new Smart Inventory and got all hosts. Going to update original bug report to include this detail. Can anyone else with over 101+ hosts reproduce this?

**Comment by ryanpetrello** [comment]
Can you share some details on the filter you're using?  I haven't been able to reproduce this, and can't think of anything that would explain >101 being the limit.

**Comment by djseiss** [comment]
Hi Ryan. I was using a pretty basic filter. The smart host filter was "name.icontains:PROJ". Which all Hosts I was pulling from OpenStack has "PROJ" in the Host name.

I am not sure if you saw my update. I was actually able to get past the 101 limit I was hitting by making changes that should have been done from the beginning.

I know Ansible Tower has a license count. We used Tower before and had a limit of 100 but it went to 101 due to localhost. A coworker and I thought that could be connected?

https://docs.ansible.com/ansible-tower/latest/html/installandreference/updates_support.html#node-counting-in-licenses

**Comment by ryanpetrello** [comment]
@FighterD1 it sounds to me like it _could_ be?  Are you running AWX or Red Hat Ansible Tower?  If you're encountering issues with Tower that end up being related to licensing code, you'll need to reach out to Red Hat.

If you're hitting a cap in AWX, it _shouldn't_ have anything to do with licensing code, since AWX doesn't enforce any sort of limits like the ones described at https://docs.ansible.com/ansible-tower/latest/html/installandreference/updates_support.html#node-counting-in-licenses

**Comment by ryanpetrello** [comment]
For what it's worth, I'm *not* able to reproduce this behavior with AWX.  I've set up a 6.1.0 install with 251 total hosts in the system, and made a Smart Inventory that filters on the word "Host":

![image](https://user-images.githubusercontent.com/214912/64266032-ed05ad80-cf01-11e9-893d-e8689700a42e.png)

...and I see all 251 hosts:

![image](https://user-images.githubusercontent.com/214912/64266057-f5f67f00-cf01-11e9-8e40-50f61e6a88cb.png)

**Comment by djseiss** [comment]
Oh no we have moved away from Ansible Tower and now solely using AWX. Could just be complete coincidence. This AWX is a fresh setup on a whole new machine and has no relationship with our old Tower installation.

**Comment by ryanpetrello** [comment]
Just out of curiosity, I edited the AWX licensing code path in my local checkout to return fake data that only provides 50 hosts (similar to what a Red Hat Ansible Tower installation might do):

![image](https://user-images.githubusercontent.com/214912/64266265-4ff74480-cf02-11e9-916c-26111404e52a.png)

...and I'm still seeing all 250+ hosts, so I think what you suggested might just be a coincidence.

In any event, I'm not able to reproduce this - let me know if you can find any steps to reproduce.

**Comment by djseiss** [comment]
I think it has something to do with the OpenStack setup.

I had 5 individual inventories. Not smart inventories. Just inventories. Each inventory had a single source that used OpenStack as its Type/Source.

Smart inventories could not get over 101 hosts.

Once I switched that to 1 inventory with 5 sources that used OpenStack. I no longer had the 101 host issue.

**Comment by TheRealHaoLiu** [comment]
Smart inventories has been deprecated in favor of constructed inventory

Please check out https://github.com/ansible/awx/pull/13303
