### ISSUE TITLE
AWX_Secret

### ISSUE THREAD

**Issue by doves99** [ansible/awx#4598]
##### ISSUE TYPE
 - Encrypting the secret_key off the inventory file on the install files.

##### SUMMARY
 Is there any way to pass an encrypted value to the secret_key="awxsecret".  If so how do to make it happen.  Would like to encrypt the secret_key so that no one has access nor not available on clear text. 
--------------------------------------------
# AWX Secret key
# It's *very* important that this stay the same between upgrades or you will lose the ability to decrypt
# your credentials
secret_key=awxsecret

**Comment by wenottingham** [comment]
-> https://github.com/ansible/awx/issues/4620
