### ISSUE TITLE
Retrieving the password using "Cyberark AIM" CREDENTIAL TYPE

### ISSUE THREAD

**Issue by LKS1302** [ansible/awx#4601]
##### ISSUE TYPE
 - General Issue

##### COMPONENT NAME
API
UI

##### SUMMARY
Hi All,

We are trying to retrieve the password from Cyberark AIM Secret Lookup Credential Type by passing the AIM URL, Application ID and Object Query. While running the test its giving us 400 Response Code from Ansible Tower.
Whereas, when we try to access the same API using POSTMAN with POST Method we are getting the successful response.
Need some suggestion, do we have dependencies for Ansible Tower to Cyberark integration. 
or any issue with Cred Module as we don't see POST Method for querying.
ANSIBLE CRED PLUGIN MODULE : https://github.com/ansible/awx/blob/c626f51dae09fb7770bc313f7d7f28e86ef2b9a3/awx/main/credential_plugins/aim.py

ENVIRONMENT
* Ansible version:  
ansible 2.8.1
python version = 2.7.5 
AWX Version = Ansible 2.8.2

**Comment by ryanpetrello** [comment]
Hey @LKS1302,

This issue tracker is for tracking feature enhancements and bugs to AWX itself (the open source project).

If you need help troubleshooting an Ansible Tower install, please reach out to Red Hat for support.
