### ISSUE TITLE
support typeahead for playbook select

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#4615]
##### ISSUE TYPE
 - Enhancement

##### SUMMARY
Projects can have a _lot_ of playbooks to choose from. They're also likely to incorporate file naming conventions for playbooks, making them conducive to typeahead / search.

![Screenshot from 2019-08-28 09-02-43](https://user-images.githubusercontent.com/9753817/63858149-02636080-c973-11e9-927b-89b7592fcaac.png)

This issue is for incorporating typeahead for playbook select. There are now pf-react [components that support this behavior out of the box](https://www.patternfly.org/v4/documentation/react/components/select/), so this is also a good opportunity for us to look into swapping out our `AnsibleSelect` component with something from the pf-react lib.

**Comment by AlexSCorey** [comment]
Removing myself to work on things of higher priority

**Comment by mabashian** [comment]
Probably want to use this specifically: http://patternfly-react.surge.sh/documentation/react/components/select#typeahead

**Comment by mabashian** [comment]
dupe #8473
