### ISSUE TITLE
template inventory should be single-select and required

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#4617]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
- There's 1 inventory per job template, so we should change the wording, component naming, help text, etc. from `Inventories` to `Inventory`
- Inventory is a required field so we'll want to update the input to reflect this

**Comment by keithjgrant** [comment]
Probably best to wait for https://github.com/ansible/awx/pull/4992 to merge before starting work on this
