### ISSUE TITLE
Create organization-level execute role

### ISSUE THREAD

**Issue by ghost** [ansible/awx#462]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Add an organization-level role that would allow a user to execute all templates in the organization

##### ENVIRONMENT
* AWX version: 1.0.0

##### STEPS TO REPRODUCE
This would allow assignment of general execute permissions to users without requiring assignment to teams or assignment of permissions at the template level.

**Comment by AlanCoding** [comment]
Seems like this would be a part of #166?
