### ISSUE TITLE
AWX_Secret

### ISSUE THREAD

**Issue by doves99** [ansible/awx#4620]
##### ISSUE TYPE
 - AWX_Secret

##### SUMMARY
Encrypting the secret_key off the inventory file on the install files.

##### ENVIRONMENT
* AWX version: 6.1.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.2
* Operating System: Linux
* Web Browser: Chrome

##### STEPS TO REPRODUCE

AWX_Secret is visible in clear text at /home_directory/awx/SECRET_KEY.

##### EXPECTED RESULTS

Is there way to encrypt or mask the actual secret_key in a different format/variable?.  Is there a method of procedure available?.  Is there any work around available to either to mask or encrypt the Secret_Key off both AWX Install File and most importantly at the file location?. 

##### ACTUAL RESULTS

Secret_Key is in clear text format

**Comment by wenottingham** [comment]
The key needs to be readable by the service at start. It is only readable by the service user in any case.
