### ISSUE TITLE
Workflow pause notification count should update on timeout. 

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#4621]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
This is an enhancement to the current implementation for workflow pause/approve. Currently, if an approval node times out, the upper counter does not update. If a workflow node timed out and completed, the end user goes to click the counter, but does not get any useful information.

There are two approaches to this:
1) Update the notification to indicate that the workflow timed out, and persist it in the notifications list. This provides more information, but may cause a lot of noise in a complicated list.
2) Simply update the counter so that the user does not see any "ghost" workflow pause/approval notifications. 

link https://github.com/ansible/awx/issues/1206

cc @mabashian @beeankha

**Comment by beeankha** [comment]
Closing this issue, due to https://github.com/ansible/awx/pull/4625 being merged.
