### ISSUE TITLE
Allow Project Admins to Configure the Project's Ansible Environment

### ISSUE THREAD

**Issue by falcon78921** [ansible/awx#4622]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Per a customer's request, Project Admins should be able to configure which Python virtual environment is used within a Project. Currently, only System/Organization Administrators have this ability.

**Comment by wenottingham** [comment]
Custom environments currently don't have RBAC, which prevents this.

**Comment by falcon78921** [comment]
Moved to https://github.com/ansible/awx/issues/7646
