### ISSUE TITLE
Project details does not show that it ran as part of a workflow

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#4623]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Project updates do not identify the workflow that spawned them

##### ENVIRONMENT
* AWX version: 6.1.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Launch a workflow with a project update and a JT

##### EXPECTED RESULTS

I expect to see a "W" like in job templates

![Screen Shot 2019-08-29 at 12 49 25 PM](https://user-images.githubusercontent.com/1385596/63960055-97418900-ca5b-11e9-97d2-9279c066ec96.png)

This element contains a link to the workflow job

##### ACTUAL RESULTS

no W on project update from that same workflow

![Screen Shot 2019-08-29 at 12 49 35 PM](https://user-images.githubusercontent.com/1385596/63960079-a4f70e80-ca5b-11e9-9db7-f7496f8b5ef5.png)

##### ADDITIONAL INFORMATION

Also no W for either of these in the JOBS listing. I can make that into a separate issue if needed, also not 100% sure if this was expected or not.

**Comment by unlikelyzero** [comment]
Still not covered in the new ui. Marking as enhancement

**Comment by wenottingham** [comment]
@jbradberry @marshmalien will what we do for https://github.com/ansible/awx/issues/5057 also solve this?

**Comment by marshmalien** [comment]
@wenottingham This looks like it was addressed by https://github.com/ansible/awx/pull/9035. Instead showing a (w) icon, we show "Source Workflow Job" with a link to the workflow job.

<img width="493" alt="Screen Shot 2021-02-01 at 11 11 58 AM" src="https://user-images.githubusercontent.com/15881645/106485257-66e6f100-647e-11eb-86a5-e4e149558290.png">

**Comment by marshmalien** [comment]
Related: https://github.com/ansible/awx/issues/8915

**Comment by unlikelyzero** [comment]
@akus062381 this functionality should exist, please make sure we have a stub for this case

**Comment by akus062381** [comment]
Coverage added.
