### ISSUE TITLE
UX: hitting enter when modifying fields like user password should hit Save

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#4629]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Right now when I hit enter in password field while modifying user account nothing happens, I have to use mouse to click the Save button, I suppose this behaviour is everywhere but didn't test it. Enter should imply confirmation like in most other software. It makes work faster than using mouse to find Save button.

**Comment by wenottingham** [comment]
I don't think we want to trap enter for this only for specific fields. cc @trahman73

**Comment by trahman73** [comment]
We don't focus on save on enter across the app because we have certain fields that interact with the enter key differently, for example, creation of tags/labels on enter.

**Comment by wenottingham** [comment]
Closing. We do want keynav to work where tab can take you to the save key; that is being tackled in https://github.com/ansible/awx/tree/devel/awx/ui_next
