### ISSUE TITLE
Only use inventory contents down-selected to relevant hosts in Ad Hoc Commands

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#463]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
It can take a very long time to run an ad hoc command against a _single_ host if that host exists inside of a larger inventory.

##### ENVIRONMENT
* AWX version: all

##### STEPS TO REPRODUCE

Create an inventory with a large number of groups & hosts, then run a simple ad hoc command against a single host.

##### EXPECTED RESULTS

The output of `awxrest.py` (soon to be from internal method on Host model) should return only the hosts that the command is being ran against.

##### ACTUAL RESULTS

Passing the script contents of the entire inventory to Ansible can take a long time, bottlenecking the command run.

##### ADDITIONAL INFORMATION

After merging https://github.com/ansible/awx/pull/459 the implementation of this will be much more simple.

`ansible-inventory` takes an option `--list-hosts`, which is analogous to --limit in playbook commands. Proof:

```
$ ansible-inventory --list-hosts hello_world -i static/just_hello_world --list
{
    "_meta": {
        "hostvars": {
            "hello_world": {}
        }
    }, 
    "all": {
        "children": [
            "ungrouped"
        ]
    }, 
    "ungrouped": {
        "hosts": [
            "hello_world"
        ]
    }
}
```

(EDIT: this example was superficial and the functionality doesn't actually exist)

To keep the interface standard, that means we should allow use of a queryparam `list_hosts`, which will accept a list of hosts, in the same format that --limit does.

This should then be used anytime we're running an ad hoc command, because it will not affect the functionality of the command. We can not use this speedup for playbooks, because it will affect variables that can be accessed in the playbook.

**Comment by wenottingham** [comment]
Techically, ad-hoc commands on the commandline are passed a full inventory, and therefore *could* access hostvars from other machines (via inventory or fact cache).

Whether that's worth the performance penalty to support is another question.

**Comment by AlanCoding** [comment]
We could have a flag on the ad hoc command, or a setting variable to toggle it?

**Comment by wenottingham** [comment]
I'm loath to add settings we don't need to - we can just say that's not supported.

What is the state of fact cache usage in ad-hoc commands anyway?

**Comment by matburt** [comment]
I disagree with this proposal on a fundamental level. This is why we support adding hosts to different inventories. If it's slow then it needs to be fixed by us or Ansible itself.

**Comment by AlanCoding** [comment]
Related issue in core: https://github.com/ansible/ansible/issues/31929

Given that issue, you might say that a precedent does _not_ already exist for the argument structure for down-selecting an inventory script to a `limit` (in the general sense).

**Comment by matburt** [comment]
Given that you closed the original issue as-stated (even though it was re-opened to track something else). I think we can close this one?

**Comment by AlanCoding** [comment]
The related Ansible issue was more about what we would call a queryparam to do down-selecting, turned out it doesn't actually exist, but it might sometime.

Here's what I wanted to get, POST payload to ad hoc commands endpoint, with configured inventory, cred, etc.

```json
{
  "job_type":"run",
  "limit":"all",
  "credential":2,
  "module_name":"command",
  "module_args":"echo 'hi {{hostvars}}'",
  "forks":0,"verbosity":0,
  "extra_vars":"---",
  "privilege_escalation":""
}
```

This shows vars for all hosts in the inventory, which is the reason you're saying we would never want to change the existing behavior. I just wanted to document a concrete example. Closing.
