### ISSUE TITLE
Add GitHub Oauth authentication support to SCM credential

### ISSUE THREAD

**Issue by mrmibrown** [ansible/awx#4633]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add feature which integrates GitHub OAuth user objects in Tower with a corresponding SCM credential on login for seamless project integration into Tower.

**Comment by wenottingham** [comment]
Is this asking for the user's credentials to GitHub to be forwarded to project checkouts?

**Comment by wenottingham** [comment]
In short: projects are an RBACed object that is delegated; we would never use a user's login credential to pull them. We also would not want to auto-create all projects that a user has access to. So I don't think there's actually a use case for this as stated.
