### ISSUE TITLE
Parallel job runs on the same inventory

### ISSUE THREAD

**Issue by tamirshaul** [ansible/awx#4634]
##### ISSUE TYPE
 - Feature Idea
Add  ```ENABLE CONCURRENT JOBS``` checkbox to inventory like in job templates.

##### SUMMARY
When using ansible to provide a service through a bastion host, 
AWX isn't aware of the servers behind the bastion host.
This causes serial run of jobs instead of parallel.

**Comment by wenottingham** [comment]
What is the issue you're running into? Parallel jobs on inventory is already allowed.

**Comment by tamirshaul** [comment]
Thanks for the response, I double checked the situation and found out there was another problem (non AWX related) that caused non parallel job runs.
