### ISSUE TITLE
Change ANSIBLE_GATHER_TIMEOUT doesnt work

### ISSUE THREAD

**Issue by v1dlak** [ansible/awx#4635]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I changed `ANSIBLE_GATHER_TIMEOUT` in `EXTRA ENVIROMENT VARIABLES` via `/etc/tower/settings.py`, but `gather_timeout` is still in default value `10`.

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.9
* Operating System: Debian 9.8
* Web Browser: Firefox 68.0.1 (64-bit)

##### STEPS TO REPRODUCE

* I added line to end of file `/etc/tower/settings.py`.
```
[root@awxweb awx]# tail -n 1 /etc/tower/settings.py 
AWX_TASK_ENV['ANSIBLE_GATHER_TIMEOUT'] = 60
```
* I checked this change in webUI.
![Screenshot(37)](https://user-images.githubusercontent.com/15999901/64098873-3f12cb80-cd68-11e9-8497-4e4691f0b20b.png)

* But when I show debug info some job for `TASK [Gather facts]` (in webUI), I still see default value.
![Screenshot(38)](https://user-images.githubusercontent.com/15999901/64099053-a6308000-cd68-11e9-8a49-69470610918b.png)

##### EXPECTED RESULTS

Change value `gather_timeout`.

##### ACTUAL RESULTS

`gather_timeout` ignore change.

**Comment by ryanpetrello** [comment]
@AlanCoding I suspect this is related to the move to runner, too?

**Comment by AlanCoding** [comment]
```
[root@awxweb awx]# tail -n 1 /etc/tower/settings.py 
AWX_TASK_ENV['ANSIBLE_GATHER_TIMEOUT'] = 60
```

Try doing it as

```
ANSIBLE_GATHER_TIMEOUT = "60"
```

Instead. By setting `AWX_TASK_ENV`, you're injecting it via a different method. You can see in our defaults file that before a job run we loop over `ANSIBLE_*` settings and apply them to the environment. I also think we didn't allow these via that variable at some point, and you're running an older version. So this syntax has a credible chance of fixing the issue for you.

**Comment by v1dlak** [comment]
The option `AWX_TASK_ENV['ANSIBLE_GATHER_TIMEOUT']` was found in [#4193](https://github.com/ansible/awx/issues/4193#issuecomment-507287519)

But I tried option `ANSIBLE_GATHER_TIMEOUT`.

```
a6awx.ng(a6awx.ng):~ # tail -n 2 /var/lib/dockercompose/settings.py 
#AWX_TASK_ENV['ANSIBLE_GATHER_TIMEOUT'] = 60
ANSIBLE_GATHER_TIMEOUT = 60
```

Changes in webUI.
![Screenshot(39)](https://user-images.githubusercontent.com/15999901/64469817-0e9caa00-d139-11e9-8350-cff6b187ec11.png)

But result is same
![Screenshot(40)](https://user-images.githubusercontent.com/15999901/64469834-54f20900-d139-11e9-9b08-e283b8a3f5a8.png)

**Comment by ryanpetrello** [comment]
I'm able to reproduce this failure by setting `AWX_TASK_ENV` and running an adhoc with `-m setup`:

![image](https://user-images.githubusercontent.com/214912/66219211-be155f80-e698-11e9-9f59-e73108f6593c.png)

![image](https://user-images.githubusercontent.com/214912/66219189-b48bf780-e698-11e9-91df-42783406997d.png)

**Comment by ryanpetrello** [comment]
This looks like it _might_ actually be a bug in Ansible itself, because I'm able to get down the point in time where we actually fork `ansible-playbook`, and it looks like we're passing the environment variable correctly:

![image](https://user-images.githubusercontent.com/214912/66219379-0e8cbd00-e699-11e9-8358-4547dd11dbb5.png)

**Comment by ryanpetrello** [comment]
Actually @v1dlak are you sure your timeout of 60s isn't _actually_ being respected by Ansible?  AWX is certainly passing it in as an env var (as the Ansible documentation suggests).

This screenshot you've referenced is just the `module_args` that were passed in (and you didn't specify any _as module args_, so the value of 10 in this context makes sense)

![](https://user-images.githubusercontent.com/15999901/64099053-a6308000-cd68-11e9-8a49-69470610918b.png)

It seems to me that AWX is behaving as it should here.
