### ISSUE TITLE
Job template create not associate the Vault credential to job (tower-cli)

### ISSUE THREAD

**Issue by zzsoka** [ansible/awx#4636]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Does not associate a credential while creating a job_template with tower-cli.

##### ENVIRONMENT
* AWX version: 6.1.0
* AWX install method: docker on linux,
* Ansible version:  2.8.4
* Operating System: RHEL 7.6 
* Web Browser: Firefox

##### STEPS TO REPRODUCE
```bash
tower-cli credential create -n "VAULT cred" --organization "My Org." --credential-type 3 --inputs '{ "vault_password":"password" }'
tower-cli job_template create -n "Job template 1"  -i "My inv" --project "My project" --playbook playbook.yml --vault-credential "VAULT cred"           
```

##### EXPECTED RESULTS

Expected result is a job teplate with associated Vault credential.

##### ACTUAL RESULTS

Job is created but the credential is not associated. Later association of this Vault type of credential is not allowed at all.

**Comment by jakemcdermott** [comment]
Hello - this repo is for tracking issues and work related to AWX.

For tower-cli issues, please create an issue in the [tower-cli repo](https://github.com/ansible/tower-cli).

Please also note that there's a new, supported CLI being worked on: https://github.com/ansible/awx/tree/devel/awxkit
