### ISSUE TITLE
Add awx_task pods automatically in awx on kubernetes

### ISSUE THREAD

**Issue by niso120b** [ansible/awx#4637]
when i use awx on kubernetes and running more then 1 jobs then the other jobs get into pending how can i enable it to run multiple jobs in parallel and to add dynamicly awx_task pods

**Comment by ryanpetrello** [comment]
Hey @niso120b,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
