### ISSUE TITLE
win_get_url fails in awx but not ansible

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/awx#4639]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.4
* Operating System: Centos 7.3

##### STEPS TO REPRODUCE

FYI: This has worked in the past.

> - name: Download letsencrypt 
  win_get_url:
    url: https://github.com/PKISharp/win-acme/releases/download/v1.9.11.2/win-acme.v1.9.11.2.zip
    dest: C:\tmp\win-acme.zip
    timeout: 60
    validate_certs: no

I've targeted multiple windows machines but same result.
The error only happens in awx. When running in only ansible no error happens.

##### EXPECTED RESULTS

File download

##### ACTUAL RESULTS

> {
    "msg": "Unexpected failure during module execution.",
    "exception": "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py\", line 145, in run\n    res = self._execute()\n  File \"/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py\", line 664, in _execute\n    result = self._handler.run(task_vars=variables)\n  File \"/usr/lib/python2.7/site-packages/ansible/plugins/action/normal.py\", line 46, in run\n    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))\n  File \"/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py\", line 917, in _execute_module\n    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)\n  File \"/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py\", line 1044, in _low_level_execute_command\n    cmd = self._connection.become.build_become_command(cmd, self._connection._shell)\n  File \"/usr/lib/python2.7/site-packages/ansible/plugins/become/sudo.py\", line 104, in build_become_command\n    return ' '.join([becomecmd, flags, prompt, user, self._build_success_command(cmd, shell)])\n  File \"/usr/lib/python2.7/site-packages/ansible/plugins/become/__init__.py\", line 52, in _build_success_command\n    cmd = shlex_quote('%s %s %s %s' % (shell.ECHO, self.success, shell.COMMAND_SEP, cmd))\nAttributeError: 'ShellModule' object has no attribute 'ECHO'\n",
    "_ansible_no_log": false,
    "stdout": ""
}

**Comment by kfattig** [comment]
I recently encountered this error with another module - in my case it was because:
```yaml
become: true
```
was set. But the defaults were used for:
```yaml
become_method: sudo
become_user: root
```

And obviously those are not valid on Windows.  This is confusing because some modules [set them for you](https://github.com/ansible/ansible/pull/60006), while others don't.

Since sudo.py is in your stack trace, I assume you're in a similar situation. Maybe you've got 'become' set in an inventory or credential and you don't realize it?

**Comment by nicolaibaralmueller** [comment]
> I recently encountered this error with another module - in my case it was because:
> 
> ```yaml
> become: true
> ```
> 
> was set. But the defaults were used for:
> 
> ```yaml
> become_method: sudo
> become_user: root
> ```
> 
> And obviously those are not valid on Windows. This is confusing because some modules [set them for you](https://github.com/ansible/ansible/pull/60006), while others don't.
> 
> Since sudo.py is in your stack trace, I assume you're in a similar situation. Maybe you've got 'become' set in an inventory or credential and you don't realize it?

Hi @kfattig,

Thanks for the reply which actually helped find the problem.

For some unknown reason "Enable privilege escalation" was enabled for this template. 

All is good again.
