### ISSUE TITLE
Generate Custom Reports From Job Template Runs

### ISSUE THREAD

**Issue by falcon78921** [ansible/awx#4654]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Per a customer's request, they would like to generate custom reports based on job template runs via the Tower UI. For example, when patching remote systems, they would like to generate a pie chart where it shows systems that were successful (`ok` in `PLAY RECAP`), systems that failed (`failed` in `PLAY RECAP`), and systems that were missed (`unreachable` in `PLAY RECAP`).

**Comment by wenottingham** [comment]
This can be easily done by querying the API and then processing that JSON in whatever tool you want.

**Comment by dasbiswajit** [comment]
@wenottingham Can we have a referance page please and can this be prioritise please!! It is very important for EDF Engagement.

**Comment by wenottingham** [comment]
General API docs are here: https://docs.ansible.com/ansible-tower/latest/html/towerapi/index.html. You can also see references on every page of the browsable API at https://your.awx.host/api/v2/.

Specifically for what you're looking for, for job number 1138, you'll want /api/v2/jobs/1138/job_host_summaries/ - this gives you JSON-formatted data on the host summary for each host.

**Comment by falcon78921** [comment]
Moved to https://github.com/ansible/awx/issues/7647
