### ISSUE TITLE
Unwanted project source tree updates before job run

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#4660]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Projects are not supposed to update to newer versions when a job is ran, unless the project is set to update on launch.

This appears to be happening when `scm_branch` of the project is blank, and new commits have been added to the repo.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

create a new project with test-playbooks, then merge a PR to that repo, and re-run a job that uses the debug playbook from it.

##### EXPECTED RESULTS

old version ran

##### ACTUAL RESULTS

new version ran

##### ADDITIONAL INFORMATION

fallout from project branch override

**Comment by kdelee** [comment]
Works for me, thanks!
