### ISSUE TITLE
6.1.0.0 -> 7.0.0 Breaks SAML login due to 'saml_auditor_attr'

### ISSUE THREAD

**Issue by ingvaldlorentzen** [ansible/awx#4664]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Login with SAML fails after upgrade to `7.0.0` due to missing `saml_auditor_attr` in settings. 

##### ENVIRONMENT
* AWX version: 7.0.0
* AWX install method: openshift manual deployment
* Ansible version:  2.8.4
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE
This should be identical when using docker-compose, as our manual AWX OpenShift instance is more or less identical to the docker-compose version. 
Have a AWX instance running in OpenShift manually deployed. Upgrade to new version by pushing new images to ImageStream, let migrations run and deployment finish. 

Attempt to login with existing SAML login that utilizes the `SOCIAL_AUTH_SAML_ORGANIZATION_ATTR` setting. 

##### EXPECTED RESULTS
AWX is updated to 7.0.0 and login still works as normal. 

##### ACTUAL RESULTS
Login failed with error `saml_auditor_attr` 

##### ADDITIONAL INFORMATION
Seems related to this: https://github.com/ansible/awx/pull/3623

##### WORKAROUND
Add the `saml_auditor_attr` with a value manually to the Database in table `conf_settings` in row `SOCIAL_AUTH_SAML_ORGANIZATION_ATTR`

**Comment by wenottingham** [comment]
see https://github.com/ansible/awx/pull/4796

**Comment by one-t** [comment]
Confirmed that users can log in when these are not set
