### ISSUE TITLE
Failing to install a role doesn't fail the update job

### ISSUE THREAD

**Issue by jpaulovic** [ansible/awx#4666]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When running a project update for a playbook which depends on roles defined in requirements.yml, the task job finishes successfully even if the roles are not successfully installed

##### ENVIRONMENT
* AWX version: Tower 3.5.1
* AWX install method: openshift
* Ansible version:  2.8.2
* Operating System: Fedora 30
* Web Browser: Firefox 68

##### STEPS TO REPRODUCE

1. Add a project containing a playbook and a requirements.yml file
1.1 The role in the requirements.yml file is incorrect - e.g. missing meta/main.yml
2. Run a project update

##### EXPECTED RESULTS

The project update job fails

##### ACTUAL RESULTS

The project update job succeeds due to an --ignore-errors flag in the ansible-galaxy command (I assume). Upon inspecting the TASK [fetch galaxy roles from requirements.yml] 
[tower_fail.log](https://github.com/ansible/awx/files/3578651/tower_fail.log)
output, one can see:
"stderr_lines": [
        "\u001b[1;35m [WARNING]: - comet was NOT installed successfully: this role does not appear\u001b[0m",
        "\u001b[1;35mto have a meta/main.yml file.\u001b[0m",
        "\u001b[1;35m\u001b[0m"

##### ADDITIONAL INFORMATION

- added the whole task log to attachment

**Comment by AlanCoding** [comment]
The `project_update.yml` playbook does not use the `--ignore-errors` flag.

https://github.com/ansible/awx/blob/43d816b6e4c7ea01c31e42e713101cf51011b534/awx/playbooks/project_update.yml#L129

Have modifications been made to the project update playbook on your server? Could you cat the file and compare the syntax of that task?

**Comment by jpaulovic** [comment]
You're onto something, Alan. I'll check with folks if they made any modifications, but I'm more inclined into thinking this is what's actually present in the official Ansible Tower 3.5.1 version...
```
     - name: fetch galaxy roles from requirements.yml
        command: ansible-galaxy install -r "{{ item.path|quote }}" -p "{{ (item.path.split('/')[-2] == 'roles') | ternary(item.path.split('/')[0:-2]|join('/'),item.path|quote|dirname) }}/roles" --force --ignore-errors
```
Thanks for pointing me to the right place to check the code.
