### ISSUE TITLE
Sporadic timeout errors with LDAP auth

### ISSUE THREAD

**Issue by jleach8** [ansible/awx#467]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
When authenticating via LDAP (Active Directory), seeing sporadic login failures. I see errors in the awx_web container logs

##### ENVIRONMENT

* AWX version: 1.0.0.588
* AWX install method: docker on linux
* Ansible version:  2.3.2.0
* Operating System: RHEL 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Login via web UI. Logins sporadically fail. Can't reproduce the issue for local accounts (admin, etc.)

##### EXPECTED RESULTS

LDAP Logins should consistently work

##### ACTUAL RESULTS

Sporadic login failure/timeout

##### ADDITIONAL INFORMATION

```
2017/10/18 14:56:51 [warn] 597#0: *314 upstream server temporarily disabled while reading response header from upstream, client: 10.0.1.33, server: _, request: "POST /api/v2/authtoken/ HTTP/1.1", upstream: "uwsgi://127.0.0.1:8050", host: "host1.xxx.com", referrer: "http://host1.xxx.com/"
2017/10/18 14:56:51 [error] 597#0: *314 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.0.1.33, server: _, request: "POST /api/v2/authtoken/ HTTP/1.1", upstream: "uwsgi://127.0.0.1:8050", host: "host1.xxx.com", referrer: "http://host1.xxx.com/"
10.0.1.33 - - [18/Oct/2017:14:56:51 +0000] "POST /api/v2/authtoken/ HTTP/1.1" 504 585 "http://host1.xxx.com/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" "-"
Wed Oct 18 14:56:52 2017 - *** HARAKIRI ON WORKER 1 (pid: 720, try: 1) ***
Wed Oct 18 14:56:52 2017 - HARAKIRI !!! worker 1 status !!!
Wed Oct 18 14:56:52 2017 - HARAKIRI [core 0] 10.95.126.12 - POST /api/v2/authtoken/ since 1508338491
Wed Oct 18 14:56:52 2017 - HARAKIRI !!! end of worker 1 status !!!
DAMN ! worker 1 (pid: 720) died, killed by signal 9 :( trying respawn ...
Respawned uWSGI worker 1 (new pid: 743)
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x1e3c560 pid: 743 (default app)
```

**Comment by matburt** [comment]
I'm not sure we can do much if your ldap server is hanging/timing out while we are trying to communicate with it which is what it seems like is happening here?

We'd need more details to see if this is an issue from the AWX side as this is a pretty well tested and heavily used feature.

**Comment by jleach8** [comment]
It’s not hanging actually. At times this works with no issues. At other times we observe this issue. I can login fine, then logout and immediately try to log back in and we see this error. This also doesn’t occur with the same LDAP setup/configuration in Tower.

**Comment by jleach8** [comment]
I tracked this down to a bug in the docker daemon while running on an OpenStack VM. This was causing sporadic packet drops. Adding --mtu=1400 to the docker daemon options fixed it.

**Comment by akcrisp** [comment]
we are seeing random logouts even when not idle awx version 1.0.1.173,  is it likely to be the same mtu docker setting ?
