### ISSUE TITLE
Migration from awx 6.1 to 7.0?

### ISSUE THREAD

**Issue by infosecwatchman** [ansible/awx#4670]
Is there a wiki or something on properly migrating to a new version in a production environment?

**Comment by ryanpetrello** [comment]
Hey @GregorioSecurity,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

The general approach to upgrading/migrating to new versions depends on how you've deployed AWX, but generally speaking what you want is to keep your database around, and blow away all your old awx containers.
