### ISSUE TITLE
Login background broken in Firefox

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4672]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
<img width="1678" alt="Screen Shot 2019-09-06 at 9 49 44 AM" src="https://user-images.githubusercontent.com/9889020/64433089-cd9a8c00-d08b-11e9-9236-889089690fbe.png">

Nothing of note in the console

**Comment by keithjgrant** [comment]
Fixed with the recent Patternfly upgrade (https://github.com/patternfly/patternfly-react/issues/2693) and confirmed working now in awx-pf in devel
