### ISSUE TITLE
Terminal colors not rendered in UI in spite of forcing use of colors

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#4673]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Colors in Ansible task outputs are not rendered in the UI.

Commands that invoke Ansible commands (such as our project update playbook does) force use of colors.

##### ENVIRONMENT
* AWX version: 7.0.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

run a job template with this playbook:

https://github.com/AlanCoding/utility-playbooks/blob/master/color_outputs.yml

Click on the task that runs the ansible config command. Click on the stdout tab.

##### EXPECTED RESULTS

Either there are no colors, or the text is colored.

##### ACTUAL RESULTS

Markers indicating terminal colors, but no rendered.

![Screen Shot 2019-09-06 at 10 32 39 AM](https://user-images.githubusercontent.com/1385596/64436632-c0cd6680-d092-11e9-9782-f4275d21e31c.png)

##### ADDITIONAL INFORMATION

Ordinarily, commands detect if it is in an interactive terminal and do not use colors when invoked in this context. But commands such as these show colors because:

https://github.com/ansible/awx/blob/ffbce2611a9897909e1fe756cecf367dd91b2579/awx/settings/defaults.py#L583-L585

Ansible core has cleaned up some of their output from `ansible-galaxy` commands in https://github.com/ansible/ansible/pull/61902 Thank you @jborean93 for doing that and @abadger for helping us to triage these issues.

This unwanted color syntax is user-facing (because they need this output to debug anything related to role installing), and the presence of these markings are entirely due to AWX. It must be solved here, cannot be solved in the Ansible core side.

**Comment by AlanCoding** [comment]
Technically the use case of calling a playbook inside a playbook still gives ugly colors, but if someone wants to resolve that they can use the `environment:` syntax we now have in our project update playbook. The important case of Galaxy commands showing nicely to users is taken care of.

**Comment by dsesami** [comment]
colors render correctly as far as I can see, looks good.
