### ISSUE TITLE
Raise error if a group and host is created with the same name

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#4680]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Create an inventory, inside that inventory create a host with name "foo". Then create a group with name "foo".

This breaks playbooks.

We should prevent the creation of the group with name "foo" because a host by that name exists, and return a 400 error message with details in this case.

Related https://github.com/ansible/awx/issues/3384

**Comment by kdelee** [comment]
verified, tried it a few ways:

- made group first, tried to add host to inventory or in the group itself, both denied saying a group already has the name
- made the host first, tried to add the group and got an error saying a host already existed.

closing as verified, thanks!
