### ISSUE TITLE
Get MVP working: tower job running with ansible runner + perf stats plugin enabled (1-2d)

### ISSUE THREAD

**Issue by jladdjr** [ansible/awx#4681]
tracking progress here..

**Comment by jladdjr** [comment]
Running into hairy issue where awx + runner + perf stats = pexpect hanging:

* Ran `strace -f -p 599`
* .. where 599 was the pid reported by `awx-manage run_dispatcher --status`
* .. and `-f` will `Trace child processes as they are created by currently traced processes as a result of the fork(2), vfork(2) and clone(2) system calls.`
* .. so (iiuc) when the dispatcher process forks a new process (thread?) using pexpect, then strace should follow the execution of the forked process / thread.

This is what I see happen shortly after pexpect forks a process:
![image](https://user-images.githubusercontent.com/4440360/64469424-6cec6d00-d0e6-11e9-91f3-d33935e17aaa.png)

`[pid  1212] close(314124)               = -1 EBADF (Bad file descriptor)`

* what is the job trying to access?
* .. and why would running w/ `cgexec` cause the file to be missing?

cc @ryanpetrello, @one-t, @appuk

**Comment by jladdjr** [comment]
Worked through this issue this a.m. w/ @ryanpetrello. The issue here was that I was
* setting an env. variable (used by perf stats) in awx and the env. var was a float (instead of a string)
* pexpect was attempting to fork, but 
* .. python's forking function was throwing an OS error when it saw the float (basically, expects a string)
* pexpect basically assumes that the fork was successful 🤕 (see [this issue](https://github.com/pexpect/pexpect/issues/512))
* .. and ends up polling the (non-existent) thread indefinitely (that's the `EBADF (Bad file descriptor)` shown at the end of the strace in the issue description)

Ensuring the env var as a string to avoid the python OS exception + pexpect hanging issue. Unblocked!

**Comment by ryanpetrello** [comment]
We ready to close this issue, or are you using it to track something else @jladdjr ?

**Comment by jladdjr** [comment]
@ryanpetrello - Using it to track the actual development of an MVP of awx + runner. Will kick the blocker issue out of the description so that it's cited as an issue and not made out to be the focus of the card.

**Comment by jladdjr** [comment]
Got this knocked out - closing
