### ISSUE TITLE
Look Up Modal has Pluralization Errors

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#4685]
##### ISSUE TYPE
The AWX-PF look up modal has pluralization errors when it doesn't find the thing the user is looking for.  This was noticed in the JT ---> edit but might occur in other places as well.  
![Screen Shot 2019-09-09 at 12 06 55 PM](https://user-images.githubusercontent.com/39280967/64547728-35a2d980-d2fb-11e9-8d57-0ab0d8bab633.png)

##### SUMMARY
Just misspellings.  
![Screen Shot 2019-09-09 at 12 05 54 PM](https://user-images.githubusercontent.com/39280967/64547679-160bb100-d2fb-11e9-99f3-c78cdb390332.png)

![Screen Shot 2019-09-09 at 12 04 43 PM](https://user-images.githubusercontent.com/39280967/64547650-ff655a00-d2fa-11e9-9700-2d93d042ea9e.png)

##### ENVIRONMENT
* AWX version: 6.1.0
* AWX install method: docker for mac
* Ansible version:  2.9.0
* Operating System: Mac os
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Go to Job Template edit/add and click to add an Inventory, Project or Instance Group.  Type the name of an item that does not exist.  
##### EXPECTED RESULTS

The empty list state would not have  pluralization errors . 

##### ACTUAL RESULTS

It has pluralization errors .

##### ADDITIONAL INFORMATION

See pictures above.

**Comment by marshmalien** [comment]
https://github.com/ansible/awx/blob/devel/awx/ui_next/src/components/PaginatedDataList/PaginatedDataList.jsx#L87
We could pass an `itemNamePlural` value from the parent component to the PaginatedDataList. If `itemNamePlural` evaluates to false, it will get transformed by the pluralize method inside of the string util.
