### ISSUE TITLE
win_psexec module return error

### ISSUE THREAD

**Issue by ronchy1** [ansible/awx#470]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY

When using Tower to run the playbook with containing the win_pexec module, it would return error, which is working fine in Ansible core

##### STEPS TO REPRODUCE

The config in the yml is:
- name: Application Release Execution
  win_psexec:
    chdir: '{{release_folder}}/'
    command: cmd.exe /c "{{release_folder}}/appRelease.bat >> {{release_folder}}/release.log"
    executable: '{{psexec_path}}'
    hostnames: localhost
    username: '{{appserver_username}}'
    password: '{{appserver_password}}'

##### ACTUAL RESULTS

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/var/lib/awx/projects/_1232__<project_name>/roles/appserver/tasks/release.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Application Release Execution
  ^ here

The error appears to have been in '/var/lib/awx/projects/_1232__<project_name>/roles/appserver/tasks/release.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Application Release Execution
  ^ here

**Comment by matburt** [comment]
First of all, we *really* need you to provide the version of both Ansible and AWX. We don't just ask for these in the template for no reason.

Secondly, you didn't format the playbook yml well enough for us to be able to get an idea of whether or not it's related to module invocation.

We don't control module parsing and execution, that's handled by ansible itself and it looks like you have a syntax problem in release.yml I think you'll probably need to take this over to the Ansible team.
