### ISSUE TITLE
Support for s390x

### ISSUE THREAD

**Issue by james-crowley** [ansible/awx#4700]
##### SUMMARY

I wanted to start a discussion about supporting `s390x`. I ported a version of AWX a while back to `s390x`, and it went pretty smooth. There were just a couple small tweaks that needed to be made to get the Docker images to build. 

Here are a couple of tweaks that were needed (These are off the top of my head, more might be needed):

-	Template out the base image pulls, CentOS to ClefOS
-	Point the download for Tini to an updated version, I think v0.16.1 was the first build for `s390x`
-	Some lib C packages might need to be changed
-	IUS Repos will need to be changed/modified to alternative repo lists

Would you guys be open to support `s390x`? 

I know a lot of the Dockerfiles are using templating to be dynamic. One possible solution would add a couple more dynamic parameters to allow for the changes that `s390x` needs. Thus, not changing the Dockerfiles for `x86` but still allowing `s390x` images to be built.

**Comment by matburt** [comment]
I'll be honest, none of us here have access to s390 systems, so we'd probably be apt to breaking it on a pretty regular basis. We would have no way to validate feature or bugfix branches against those systems.

**Comment by james-crowley** [comment]
@matburt Well it’s your lucky day! We have a couple ways we can get you access to `s390x` systems (also ` ppc64le` too, but we can talk more about that later).  We have a couple ways to accomplish this, but it depends on how you want it set up.

One of the ways is to utilize Oregon State University's pipeline resources. Here is a link to check out, https://osuosl.org/services/ibm-z/. You can hear more about a dev's experiences from the Dumb-init team, https://github.com/Yelp/dumb-init/issues/188#issuecomment-517453008.

If that does not fit your current build workflow/pipeline, we could set up some servers running on `s390x`, that you would have full access to, thus allow you to pull them into your build process. This method is a little more flexible but requires a little more setup.

What does your current pipeline/testing look like? Maybe I can help direct you to the best resource if I know a little more about your process.

**Comment by james-crowley** [comment]
@matburt Were you interested in getting `s390x` access? No rush, just wanted to get your thoughts on my last comment.

**Comment by matburt** [comment]
It looks like we have something underway here between RH and IBM, I think we should funnel this through that process.

**Comment by james-crowley** [comment]
@matburt Do you mind emailing me about this internal process? I just want to make sure were on the same page. 

My email is `James.Crowley@ibm.com`.

**Comment by bendermIBM** [comment]
Hey @matburt, @james-crowley and I would love to get involved in this process and help contribute code/doc where we can!
