### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by artemkamolodets** [ansible/awx#471]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Problem with ansible-playbook -i inventory install.yml.
Python2.x: 

ERROR! Unexpected Exception, this is probably a bug: 'CallbackModule' object has no attribute 'set_options'

Python3.x:

ERROR! Unexpected Exception, this is probably a bug: name 'reload' is not defined

**Comment by wenottingham** [comment]
What AWX and ansible version? Please use the form - we do need that info.

**Comment by matburt** [comment]
It really looks like your ansible installation may be busted/too old? Would be super helpful to know that version also.
