### ISSUE TITLE
Download collections for inventory imports

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#4720]
##### ISSUE TYPE
 - Feature Idea
 - Future Bug fix

##### SUMMARY
We use inventory plugins for all the native inventory source types. These are vendored with Ansible core. These will move. The locations listed here may not be their final locations, but they will move somewhere:

 - aws_ec2: https://github.com/ansible-collections/ansible_collection_aws/blob/master/plugins/inventory/aws_ec2.py
 - gcp_compute: https://github.com/ansible-collections/ansible_collection_google/blob/master/plugins/inventory/gcp_compute.py
 - tower: https://github.com/ansible/awx/pull/4701

Once the migration to collection lands, the one we are using via our current logic will be deprecated. Then eventually removed.

Unclear what the solution would look like:

1. we could start vendoring inventory plugins like we did with scripts 🤢 
2. we run `ansible-galaxy collection install <>.<>.tower` before the update

Depending on settings of the server, the namespace may need to be different things. With the implementation in https://github.com/ansible/awx/pull/4589, we would not properly have the information needed to do option 2.

**Comment by wenottingham** [comment]
I think it has to be 1) ; too many issues with 2).

**Comment by kdelee** [comment]
will https://github.com/ansible/awx/pull/6283 resolve this?

**Comment by wenottingham** [comment]
yes

**Comment by kdelee** [comment]
We are now using plugins sourced from collections that are packaged via this mechanism. Calling this verified and closing
