### ISSUE TITLE
[CLI] when tower is upgrading/returning /migrations_notran/ , CLI throws error with bad info

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#4721]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

If tower is actively upgrading (or busted as it sometimes gets in development environment), running `awx -h` will return a hard to interpret error that does not really help you.

##### STEPS TO REPRODUCE

When tower is in the state that you get the "upgrading screen" instead of normal response, e.g. when normal request ends up redirecting you to `/migrations_notran/` and you see:

`172.18.0.1 GET /migrations_notran/ - HTTP/1.1 200` in the logs, running the following gets weird error:

```
awx -h
'Base' object has no attribute 'available_versions'
```
##### EXPECTED RESULTS

Help text, perhaps some message saying server is not responding normally

##### ACTUAL RESULTS

Error message

##### Additional information
I think this is an underlying awxkit problem, I've seen this before using just plain awxkit

**Comment by ryanpetrello** [comment]
@kdelee PR here: https://github.com/ansible/awx/pull/4732

**Comment by kdelee** [comment]
works for me, thanks!
