### ISSUE TITLE
extra vars are not shown on workflow job template schedules with prompted extra vars

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#4726]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
extra vars are not shown on workflow job template schedules with prompted extra vars

**Comment by jakemcdermott** [comment]
https://github.com/ansible/awx/pull/4727

**Comment by elyezer** [comment]
Step to verify:

1) Created a workflow job template with the prompt on launch checked for the extra vars
2) Created a new schedule for the previous workflow job template and the extra vars text area was presented.
3) Created another workflow job template without checking the prompt on launch for extra vars
4) Created a new schedule for the previous workflow job template and the extra vars text area was not present.

With that we can consider this verified.
