### ISSUE TITLE
AWX 4.0.0.0 stopped showing job outputs(2)

### ISSUE THREAD

**Issue by larrybg** [ansible/awx#4738]
ISSUE TYPE
Bug Report

SUMMARY
This is not a duplicate of issue #3951 - this is the same ongoing issue. Server performance turnes out is not the problem.

AWX 4.0.0.0 running in the Docker containers. The database is installed on a separate server. New installation is about 1 month old. Stopped showing job outputs

ENVIRONMENT
AWX version: 4.0.0.0
AWX install method: docker on linux CentOS 7
Ansible version: 2.7.9
Operating System: CentOS
Web Browser: Chrome, Safari
STEPS TO REPRODUCE
Execute the template, check job's output

EXPECTED RESULTS
Running job produces an output that should be shown in the UI output window

ACTUAL RESULTS
Nothing has shown

**Comment by awithrow9** [comment]
Thanks for reporting this.  Can you please try this with the latest AWX and open an issue if you see it there?

**Comment by larrybg** [comment]
@awithrow9 , why did you close this issue?
