### ISSUE TITLE
Weird tool tip behavior when in modals

### ISSUE THREAD

**Issue by appuk** [ansible/awx#4747]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When in an overlay modal, the tool tip appears no matter the position of the mouse pointer(see screenshot)

##### ENVIRONMENT
* AWX version: 3.6

##### STEPS TO REPRODUCE
Reproducible in all modals, for eg:
1. Templates > Specific Template > Permissions > Add
2. Organizations> Specific Organization > Users > Add

##### EXPECTED RESULTS
The tool tip should not appear when on the screen

##### ACTUAL RESULTS
The tool tip appears at all places in the screen(overlay)

![Tooltip-behavior](https://user-images.githubusercontent.com/11617351/64888012-e846a500-d637-11e9-8d0b-613b25d0324f.gif)

**Comment by wenottingham** [comment]
punting low-priority UI nits to ui-next

**Comment by mabashian** [comment]
This will probably just get closed at some point - this issue shouldn't follow us to the new UI since we're using completely different technologies.

**Comment by appuk** [comment]
I agree with that! I verified this issue in the new UI, and can not reproduce, hence closing the issue
