### ISSUE TITLE
Update ui_next search based on TODOs from first pass

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#4748]
DONE 
 - currently handleSearch in Search.jsx always appends the __icontains post-fix to make the filtering ux expected work right. Once we start adding number-based params we will won't to change this behavior. (done in https://github.com/ansible/awx/pull/4742)

TODO
 - utilize new defaultSearchKey prop instead of relying on sort key
 - make access have username as the default key?
- make access have username as the default key
- Jobs list
   - Name (which is also the name of the job template) — search is ?name=jt
   - Job ID — search is ?id=13
   - Label name — search is ?labels__name=foo
   - Job type (dropdown on right with the different types) ?type = job
   - Created by (username)  — search is ?created_by__username=admin
   - Status — search (dropdown on right with different statuses) is ?status=successful
   - support custom order_by being typed in the url bar
   - fix up which keys are displayed in the various lists (note this will also require non-string widgetry to the right of the search key dropdown, for integers, dates, etc.)
 - Move to new pf toolbar

**Comment by dsesami** [comment]
Testing on this was completed during the passthrough of https://github.com/ansible/awx/pull/5287 -- future work is already defined in other issues, so closing this one out.
