### ISSUE TITLE
Incorrect links in the users list while adding them in an Organization

### ISSUE THREAD

**Issue by appuk** [ansible/awx#4749]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The links in the Users list while adding users in an organization redirect to the Main users page instead of redirecting to the Specific User page

##### ENVIRONMENT
* AWX version: 3.6

##### STEPS TO REPRODUCE
1. Go to any organization
2. Go to users tab
3. Click on add a user
4. Click on any user link
##### EXPECTED RESULTS
It should redirect to the specific user: .../users/id

##### ACTUAL RESULTS
It is redirecting to the main users page: .../users
![wrong-link-to-the-User](https://user-images.githubusercontent.com/11617351/64889389-3f9a4480-d63b-11e9-83ac-12899ac212ec.gif)

**Comment by jakemcdermott** [comment]
https://github.com/ansible/awx/pull/4928

**Comment by jakemcdermott** [comment]
fix verified for users and teams:

![team_org_rbac_user_links](https://user-images.githubusercontent.com/9753817/66326273-adfabb80-e8f6-11e9-8b06-8bc343e7de6f.gif)

**Comment by appuk** [comment]
The links are working as expected, Hence, closing the bug
