### ISSUE TITLE
Add template button missing when no templates found on initial load

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4754]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
<img width="1680" alt="Screen Shot 2019-09-16 at 3 03 40 PM" src="https://user-images.githubusercontent.com/9889020/64985630-520ebb00-d893-11e9-88e2-ededf34419f8.png">

Add button should be shown even if there are no rows

##### STEPS TO REPRODUCE
Either don't have any JT's saved _or_ create an org, add a new org admin to that org and log in with that org admin.  Going to the templates list will yield the above screenshot.

##### EXPECTED RESULTS
Add button shown

##### ACTUAL RESULTS
Add button hidden

**Comment by marshmalien** [comment]
I'm not seeing this on devel - This bug was possibly resolved by https://github.com/ansible/awx/pull/5006
