### ISSUE TITLE
awxrest.py fails when http_proxy is set in installer inventory

### ISSUE THREAD

**Issue by orgito** [ansible/awx#476]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - Installer

##### SUMMARY
When `http_proxy` variable is set in the installer inventory `awxrest.py` will try to use the proxy when making requests to the AWX API (http://awxweb:8052). That will cause an error since the proxy will not be able to access that internal URL.

##### ENVIRONMENT
* AWX version: 1.0.1.77
* AWX install method: docker on linux (official images)
* Ansible version:  2.4.0.0
* Operating System: Centos 7.4
* Web Browser: Chrome 60

##### STEPS TO REPRODUCE

1. Set `http_proxy` variable in installer inventory
2. After installing AWX run any template

##### EXPECTED RESULTS
The template should run without a problem

##### ACTUAL RESULTS
The template will call ansible-playbook that will use the `awxrest.py` inventory script. The script will make a request to AWX API honoring http_proxy environment variable and fail.

##### ADDITIONAL INFORMATION
Including `awxweb` in the no_proxy variable solves the issue. This information should be included in the documentation and inventory comments. Another option is to have the container always include `awxweb` to the `no_proxy` environment variable. Or change the script to bypass proxy for local URLs.

**Comment by matburt** [comment]
Probably related to this: https://github.com/ansible/awx/pull/298

This is fixed with #459 which is already merged
