### ISSUE TITLE
Apply role display changes to ui_next

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4765]
##### ISSUE TYPE
 - Task

##### SUMMARY
Apply https://github.com/ansible/awx/pull/4529 to ui_next

This issue exists so we don't forget to make this change.

**Comment by unlikelyzero** [comment]
@dsesami can you check to make sure this is working?

**Comment by dsesami** [comment]
there's a bit of weirdness happening with the UI org/user relationship. I'd like to verify this after https://github.com/ansible/awx/issues/7756 is fixed.

**Comment by dsesami** [comment]
This is semi-redundant with https://github.com/ansible/awx/issues/4532 -- do we want to close this one and leave the other open @mabashian ?

**Comment by jakemcdermott** [comment]
closing as duplicate of https://github.com/ansible/awx/issues/4532
