### ISSUE TITLE
Freeform field in playbook dropdown doesn't filter at all.

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#4768]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The freeform field in the playbooks dropdown (in the job template form) should do some basic filtering. It is no longer doing that basic filtering (like typing the beginning of a phrase, and all the playbooks with that phrase appearing). 

Labeling this as medium because the main point of the field is to allow the user to type playbooks that might not exist in the list, but the filtering weakens user experience when tracking down listed playbooks.

##### ENVIRONMENT
* AWX version: latest
* Operating System: Fedora 30
* Web Browser: Chrome

##### STEPS TO REPRODUCE
- Make a project with a lot of playbooks, like https://github.com/ansible/test-playbooks.
- Start making a job template with this project.
- Open the playbooks dropdown and try to use the freeform text field.

##### EXPECTED RESULTS
Typing the beginning of a playbook will show all playbooks that have that same string at the beginning.
##### ACTUAL RESULTS
No results return, the list is empty.

##### ADDITIONAL INFORMATION
for example, several playbook names start with `with`. None are listed here.
![Screenshot from 2019-09-17 13-40-40](https://user-images.githubusercontent.com/19942822/65065634-ca878180-d950-11e9-8080-70942665968b.png)

**Comment by dsesami** [comment]
The decision on this was to not make this change in the angular UI, but it is a future item in the patternfly project. closing because of this.

**Comment by unlikelyzero** [comment]
@dsesami we've been adding the UI next flag to these
