### ISSUE TITLE
When approval node is deleted, viewing the completed job shows APPROVED and DELETED superimposed

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#4778]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY 

Viewing a workfow job after an approval node that was in it has been deleted causes states to be superimposed.

##### STEPS TO REPRODUCE

Create a WF with approval node, run it and approve or deny it.
Then delete the approval node and/or workflow
Then look at details of the WF job you ran.

##### EXPECTED RESULTS

Legible UI

##### ACTUAL RESULTS

![Screenshot from 2019-09-18 14-54-40](https://user-images.githubusercontent.com/29239279/65178163-2708a080-da26-11e9-9cb7-2196799fe0f0.png)

**Comment by elyezer** [comment]
Did the following to verify:

1) Created a workflow job template with 3 nodes: jt, approval, jt.
2) Ran the workflow two times, the first one approved the approval node and on the second one the approval node was denied
3) Edited the workflow job template created on step 1 and deleted the approval node
4) Came back to the previous job runs and saw the following. The test for deleted and approved/denied are not overlapping anymore.

![Screenshot from 2019-10-08 14-13-57](https://user-images.githubusercontent.com/48132/66421606-27b5a680-e9d6-11e9-892a-d2cf781403c7.png)

![Screenshot from 2019-10-08 14-14-08](https://user-images.githubusercontent.com/48132/66421605-27b5a680-e9d6-11e9-83d0-98fafcf43c95.png)

With all that we can consider this issue verified.
