### ISSUE TITLE
workflow_job_template_nodes POST authentication issuees

### ISSUE THREAD

**Issue by garnser** [ansible/awx#4781]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When trying to POST to workflow_job_template_nodes using basic auth and/or token-auth AWX replies with 401 failure.

`awx_web      | 2019-09-19 08:40:32,754 WARNING  awx.api.generics status 401 received by user AnonymousUser attempting to access /api/v2/workflow_job_template_nodes/ from XXX.XXX.XXX.XXX
awx_web      | 2019-09-19 08:40:32,780 WARNING  django.request Bad Request: /api/v2/workflow_job_template_nodes/
awx_web      | 2019-09-19 08:40:32,780 WARNING  django.request Bad Request: /api/v2/workflow_job_template_nodes/
awx_web      | [pid: 153|app: 0|req: 57/208] XXX.XXX.XXX.XXX () {38 vars in 568 bytes} [Thu Sep 19 08:40:32 2019] POST /api/v2/workflow_job_template_nodes/ => generated 140 bytes in 74 msecs (HTTP/1.1 400) 8 headers in 246 bytes (1 switches on core 0)
awx_web      | XXX.XXX.XXX.XXX - - [19/Sep/2019:08:40:32 +0000] "POST /api/v2/workflow_job_template_nodes/ HTTP/1.1" 400 140 "-" "curl/7.54.0" "-"`

##### ENVIRONMENT
* AWX version: 7.0.0
* AWX install method: docker on linux
* Ansible version:  2.6
* Operating System: CentOS
* Web Browser: Curl 7.54

##### STEPS TO REPRODUCE

0. nodes.json
`{
    {
      "type": "workflow_job_template_node",
        "workflow_job_template": {
          "id": 1238,
          "name": "DNS WF",
          "description": ""
        },
        "unified_job_template": {
          "id": 820,
          "name": "template-name",
          "unified_job_type": "job"
        }
      "extra_data": {},
      "inventory": null,
      "scm_branch": null,
      "job_type": null,
      "job_tags": "",
      "skip_tags": null,
      "limit": "",
      "diff_mode": null,
      "verbosity": null,
      "workflow_job_template": 1238,
      "unified_job_template": 820,
      "success_nodes": [],
      "failure_nodes": [],
      "always_nodes": []
    }
}
`
1. `curl -vvv -f -H 'Authorization: Token XXXX' -u username:password -H 'Content-Type: application/json' -XPOST http://awxhost/api/v2/workflow_job_template_nodes/ -d @nodes.json`

##### EXPECTED RESULTS

Creation of nodes for related workflow

##### ACTUAL RESULTS

Authorization failure.

Client:
```
* The requested URL returned error: 400 Bad Request
* stopped the pause stream!
100   706    0     0  100   706      0   7887 --:--:-- --:--:-- --:--:--  7932
* Closing connection 0
curl: (22) The requested URL returned error: 400 Bad Request
```

Server:
``awx_web      | 2019-09-19 08:40:32,754 WARNING  awx.api.generics status 401 received by user AnonymousUser attempting to access /api/v2/workflow_job_template_nodes/ from XXX.XXX.XXX.XXX
awx_web      | 2019-09-19 08:40:32,780 WARNING  django.request Bad Request: /api/v2/workflow_job_template_nodes/
awx_web      | 2019-09-19 08:40:32,780 WARNING  django.request Bad Request: /api/v2/workflow_job_template_nodes/
awx_web      | [pid: 153|app: 0|req: 57/208] XXX.XXX.XXX.XXX () {38 vars in 568 bytes} [Thu Sep 19 08:40:32 2019] POST /api/v2/workflow_job_template_nodes/ => generated 140 bytes in 74 msecs (HTTP/1.1 400) 8 headers in 246 bytes (1 switches on core 0)
awx_web      | XXX.XXX.XXX.XXX - - [19/Sep/2019:08:40:32 +0000] "POST /api/v2/workflow_job_template_nodes/ HTTP/1.1" 400 140 "-" "curl/7.54.0" "-"``

**Comment by ryanpetrello** [comment]
@awithrow9 I suspect this _could_ be related to the recent approval pause node feature work, and would like somebody to take a closer look just to be sure.

**Comment by ryanpetrello** [comment]
cc @appuk @beeankha once you wrap up https://github.com/ansible/awx/pull/4657

**Comment by beeankha** [comment]
Hi @garnser , thank you for filing this issue.  

I've dug into this a bit and think this is a `400` (bad request) error vs a `401` auth error.  While trying to recreate the problem, I encountered some JSON syntax issues in the `node.json` example you provided.  Can you please re-try with your `node.json` file formatted like the example below? 
```
{
    "type": "workflow_job_template_node",
    "extra_data": {},
    "inventory": null,
    "scm_branch": null,
    "job_type": null,
    "job_tags": "",
    "skip_tags": null,
    "limit": "",
    "diff_mode": null,
    "verbosity": null,
    "workflow_job_template": 1238,
    "unified_job_template": 820,
    "success_nodes": [],
    "failure_nodes": [],
    "always_nodes": []
}
```

POST-ing JSON info formatted in this way worked for me without throwing any errors.  Please let me know if this fixes the issue for you!

**Comment by ryanpetrello** [comment]
@garnser what @beeankha said - an HTTP 400 suggests that the data you've sent isn't valid JSON.  If you correct this and are still seeing issues, let us know.
