### ISSUE TITLE
instance group display wordwraps when it shouldn't

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#4788]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

When zoomed in / restricted in width, the Instance Group display starts breaking text before it needs to.

Example:
![squash](https://user-images.githubusercontent.com/5208768/65274258-e7f35180-daf0-11e9-90b1-6293a58f74ff.png)

##### ENVIRONMENT
* AWX version: current

##### STEPS TO REPRODUCE

Create a OCP/K8S instance group.

Zoom in.

**Comment by AlexSCorey** [comment]
This has been addressed in this PR.

**Comment by elyezer** [comment]
I did the following to verify this one:

1) Added a second instance group
2) Resized/zoomed the UI to see how it behaved. See below the screenshots:

![Screenshot from 2019-10-08 14-00-13](https://user-images.githubusercontent.com/48132/66420588-21262f80-e9d4-11e9-88f5-d32b618221de.png)

![Screenshot from 2019-10-08 14-00-25](https://user-images.githubusercontent.com/48132/66420589-21262f80-e9d4-11e9-8e50-d31ba8ce2a6e.png)

![Screenshot from 2019-10-08 14-00-39](https://user-images.githubusercontent.com/48132/66420590-21262f80-e9d4-11e9-8d06-a6954f16cee9.png)

![Screenshot from 2019-10-08 14-00-47](https://user-images.githubusercontent.com/48132/66420591-21262f80-e9d4-11e9-8c1e-e63421e9db67.png)

![Screenshot from 2019-10-08 14-01-04](https://user-images.githubusercontent.com/48132/66420592-21262f80-e9d4-11e9-966d-3038b8aeaa08.png)

The text is not being wrapped anymore and the page have a better responsiveness. With that said we can consider this verified.
