### ISSUE TITLE
Error trying to create Machine credential with prompted password field and HashiCorp Vault KV backed private key

### ISSUE THREAD

**Issue by omgjlk** [ansible/awx#4791]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I'm trying to set up a Machine credential. For SSH Private Key I'm sourcing it from an already configured HashiCorp Vault KV credential. I want the user to provide the passphrase at template launch so I check the box. When I do this I get an error stating that `cannot be set unless "SSH Private Key" is set`.

I suspect this is just a by-product of a credential plugin. Sourcing the private data by way of a plugin makes the schema for Machine (ssh) credentials fail to validate.

##### ENVIRONMENT
* AWX version: 6.1.0
* AWX install method: docker on linux
* Ansible version:  2.8.2
* Operating System: Mac OSX
* Web Browser: Safari

##### STEPS TO REPRODUCE

- Create a HashiCorp Vault KV credential
- Open dialog to create another credential; a Machine credential
- Click the search button for the SSH PRIVATE KEY dialog
- Select previously created HashiCorp Vault KV credential and click next
- Fill in data for secret path and key name and save
- Check Prompt on launch for PRIVATE KEY PASSPHRASE
- Click Save

##### EXPECTED RESULTS

I expected to be able to source the private data from Vault and the passphrase from the user, ensuring no part of the combo is stored within AWX at rest.

##### ACTUAL RESULTS

An error dialog appears below PRIVATE KEY PASSPHRASE and I cannot continue.

![Screen Shot 2019-09-19 at 7 06 05 PM](https://user-images.githubusercontent.com/523287/65294183-b9866e00-db12-11e9-902f-8a3175dc92f7.png)

##### ADDITIONAL INFORMATION

![vault-ssh-prompt](https://user-images.githubusercontent.com/523287/65294681-cc4d7280-db13-11e9-900c-bf769e649a30.gif)

cc github/gtower#19

**Comment by omgjlk** [comment]
I just tested again, this time typing in a passphrase to the passphrase box and the same error comes up. It appears that I will not be able to put any data in this box while sourcing the private key from a HashiCorp Machine credential.

**Comment by wenottingham** [comment]
Yeah, the validator checks that there's an SSH key if you try and set a passphrase, and since it's a lookup, there's not a ssh key stored in the API yet.

**Comment by wenottingham** [comment]
Feel free to give https://github.com/ansible/awx/pull/4798 a try.

**Comment by ryanpetrello** [comment]
@omgjlk mind giving this a shot?

https://github.com/ansible/awx/pull/4807

**Comment by omgjlk** [comment]
Yeah, as noted in that PR it appears to work in my environment.

**Comment by one-t** [comment]
Confirmed that it's now possible to use a passphrase when pulling a private key using a credential lookup

**Comment by L1ghtman2k** [comment]
Seems like I am unable to set the Kerberos credentials:

![Screenshot_3](https://user-images.githubusercontent.com/35672535/68894855-24f55200-06f6-11ea-9bb6-823e2019e7dd.png)

**Comment by wenottingham** [comment]
There are no 'kerberos' machine credentials, beyond WinRM implicit kinit using 'username' and 'password' from a machine credential.
