### ISSUE TITLE
improvements proposals for job details view in Ansible Tower web interface

### ISSUE THREAD

**Issue by AlexanderStohr** [ansible/awx#4799]
improvement proposals for Ansible Tower job details view:

1. change the text in the search box from "[...] still running" to "[...] running"
2. change the text top right of "extra variables" box from "EXPAND" to the same maximize icon as on the right frame. (this unifies the controls of the web UI)
3. add a "raw data download" button for the logged texts

**Comment by mabashian** [comment]
Hey @AlexanderStohr thanks for your feedback here - the interface for job details has changed pretty substantially in recent years.  If you have feedback on the current version please feel free to open up a new issue.
