### ISSUE TITLE
Enable awx connectivity with cloud secrete engines/authentication credentials for AWS/Azure/GCP through 'HashiCorp Vault'...

### ISSUE THREAD

**Issue by Sreenadh8** [ansible/awx#4800]
##### ISSUE TYPE
environment background 
ansible version: 2.8.4
awx version : 7.0 with external postgres rds 
secrete management tool : Hashicorp Vault 

We have HashiCorp Vault that provides SSH Signed key for Linux machines which is integrated and works fine in AWX too... however, in the same way, we would like to see Cloud Authentication credentials also to be generated from cloud secrete engines and fetched dynamically , which helps us to avoiding the AWS/Azure key rotation manual task... it's really become painful to maintain the EC2 IAM since we have more than 75+ accounts across multiple accounts...

More information how Vault generates short lived credentials for cloud providers : https://www.vaultproject.io/docs/auth/aws.html

##### SUMMARY

Below attached sample snippet works for SSH Signed-key, in the same, we should have an option to talk to cloud secrete engines to generate a dynamic credentials...

![image](https://user-images.githubusercontent.com/41424639/65382455-633c4980-dd23-11e9-8c63-1abfc599fe26.png)

Regards,
Sreenadh

**Comment by shanemcd** [comment]
We think this should now be possible using secret lookups: https://docs.ansible.com/automation-controller/latest/html/userguide/credential_plugins.html#configure-and-link-secret-lookups
