### ISSUE TITLE
Host variables not passing to play

### ISSUE THREAD

**Issue by Ugly-Wan** [ansible/awx#4801]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I am using the AWX to deploy docker containers, and since we upgraded to 6.1.0

##### ENVIRONMENT
* AWX version: 6.1.0
* AWX install method: docker
* Ansible version:  2.8.2
* Operating System: RedHat 7
* Web Browser: Firefox 69

##### STEPS TO REPRODUCE

host in inventory with DOCKER_HOST: 'tcp://xxx:yyy' set

Run a play using docker_container.

Output of play:

"msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))"

##### EXPECTED RESULTS

Play not to fail, as it worked before the upgrade

##### ACTUAL RESULTS

"msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))"

##### ADDITIONAL INFORMATION

When setting docker_host: 'tcp://xxx:yyy' in the play it works

**Comment by ryanpetrello** [comment]
@Ugly-Wan this sounds more like an issue w/ an Ansible module or one of its dependencies.  Could you give this a try in a different version of Ansible?

Do you have any more error context you could share?

**Comment by ryanpetrello** [comment]
@Ugly-Wan if you've got some more details after trying a different version of Ansible, let us know and we can reopen this.
