### ISSUE TITLE
LDAP Test when configuring Authentication

### ISSUE THREAD

**Issue by andrewm659** [ansible/awx#4802]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Can we get a button to test LDAP search filters or auth when configuring it within AWX/Tower?  Most of the other applications I have used in the past have it.  (Graylog, Atlassian Suite)

**Comment by tjyang** [comment]
@andrewm659 
This is a duplicated request of https://github.com/ansible/awx/issues/2209

**Comment by ryanpetrello** [comment]
Let's track this request over at #2209.
