### ISSUE TITLE
Add a YAML and JSON module to Ansible. 

### ISSUE THREAD

**Issue by tra7nce** [ansible/awx#4810]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add a YAML and JSON module to Ansible. This is critical to securing OpenShift. 

https://github.com/kwoodson/ansible-role-yedit can be used for the module.

**Comment by ryanpetrello** [comment]
Hey @tra7nce,

This issue tracker is for the Ansible AWX project, not Ansible itself.
