### ISSUE TITLE
Schedules created by API are set up with an initial start date of ~40 days in the future

### ISSUE THREAD

**Issue by viavokal** [ansible/awx#4812]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Schedules created by API are set up with an initial start date of ~40 days in the future, in an inconsistent manner.

##### ENVIRONMENT
* AWX version: 2.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.2
* Operating System: Ubuntu 16.04
* Web Browser: Chrome Version 76.0.3809.132 (Official Build) (64-bit)

##### STEPS TO REPRODUCE

    curl -o /dev/null -Ssf -d "{\"name\":\"$SCHEDULE_NAME\",\"rrule\":\"DTSTART;TZID=$SCHEDULE_TIMEZONE_ID:${SCHEDULE_START_DATE}T${SCHEDULE_HOUR} RRULE:FREQ=$SCHEDULE_FREQUENCY_CAPITALS;INTERVAL=$SCHEDULE_INTERVAL;BYDAY=$SCHEDULE_DAY\",\"description\":\"every week on $SCHEDULE_DAY\"}" $AWX_INTERNAL_API_URL/job_templates/$JOB_ID/schedules/ -H 'Content-Type: application/json' -H "Authorization: Bearer $TOKEN"

With SCHEDULE_START_DATE set to `date +%Y%m%d`

##### EXPECTED RESULTS

Schedule to the first near occurrence of $SCHEDULE_DAY 

##### ACTUAL RESULTS
Occasionally scheduled to begin at $SCHEDULE_DAY in about forty days time (this is a non-consistent behavior, sometimes it works just as expected)

##### ADDITIONAL INFORMATION
NA

**Comment by wenottingham** [comment]
Please try with a current version of AWX (7.0.0 is latest). 2.0.0 is very old, and many fixes have happened since then.

**Comment by ryanpetrello** [comment]
@viavokal if you're still encountering this in more recent versions of AWX, let us know and we'll reopen this.  Thanks!
