### ISSUE TITLE
Job stops for no reason and won't continue 

### ISSUE THREAD

**Issue by wilkis3** [ansible/awx#4813]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The job exection stops execution for no reason. The job status shows "Running" and you have to cancel the job manually.

##### ENVIRONMENT
* AWX version: 7.0.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.4
* Operating System: Ubuntu 18.04.3 LTS
* Web Browser: Firefox

##### STEPS TO REPRODUCE

I or AWX itself starts a playbook to keep all the 81 host up to date. 
The job stops every time on the same task and won't continue. I executed the playbook on different host successfully. And I did try to use various ssh options like ControlPersist, ControlMaster etc.

##### EXPECTED RESULTS

Continue execution.
There're a lot of tasks more.

##### ACTUAL RESULTS
```
<COOKIEHOST-01.example.com> (0, '\r\n{"changed": false, "cache_updated": true, "cache_update_time": 1569315114, "invocation": {"module_args": {"state": "present", "force": false, "dpkg_options": "force-confdef,force-confold", "only_upgrade": false, "cache_valid_time": 0, "package": ["curl"], "force_apt_get": false, "policy_rc_d": null, "purge": false, "autoclean": false, "default_release": null, "deb": null, "install_recommends": null, "update_cache": true, "autoremove": false, "upgrade": null, "allow_unauthenticated": false, "name": ["curl"]}}, "warnings": ["Could not find aptitude. Using apt-get instead"]}\r\n', 'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: auto-mux:Trying exis…
<COOKIEHOST-01.example.com> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<COOKIEHOST-01.example.com> SSH: ansible.cfg set ssh_args: (-C)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<COOKIEHOST-01.example.com> SSH: ANSIBLE_HOST_KEY_CHECKING/host_key_checking disabled: (-o)(StrictHostKeyChecking=no)
<COOKIEHOST-01.example.com> SSH: ansible_password/ansible_ssh_password not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<COOKIEHOST-01.example.com> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User="ubuntu")
<COOKIEHOST-01.example.com> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<COOKIEHOST-01.example.com> SSH: PlayContext set ssh_common_args: (-o)(ServerAliveInterval=600)(-o)(ControlPersist=30m)(-o)(ControlMaster=auto)
<COOKIEHOST-01.example.com> SSH: PlayContext set ssh_extra_args: ()
<COOKIEHOST-01.example.com> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/tmp/awx_28914_hl6fewhs/cp/f42ccbe7e0)
<COOKIEHOST-01.example.com> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ServerAliveInterval=600 -o ControlPersist=30m -o ControlMaster=auto -o ControlPath=/tmp/awx_28914_hl6fewhs/cp/f42ccbe7e0 COOKIEHOST-01.example.com '/bin/sh -c '"'"'rm -f -r /home/ubuntu/.ansible/tmp/ansible-tmp-1569315110.6-9454965381355/ > /dev/null 2>&1 && sleep 0'"'"''
<COOKIEHOST-01.example.com> (0, '', 'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive:done pid = 10002\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
ok: [COOKIEHOST-01.example.com] => {
    "cache_update_time": 1569315114,
    "cache_updated": true,
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false,
            "autoclean": false,
            "autoremove": false,
            "cache_valid_time": 0,
            "deb": null,
            "default_release": null,
            "dpkg_options": "force-confdef,force-confold",
            "force": false,
            "force_apt_get": false,
            "install_recommends": null,
            "name": [
                "curl",
    …
```
The job status shows still "Running" and suspension. Also few minutes later and I have cancel the job manually.
##### ADDITIONAL INFORMATION

I also did try:
https://github.com/ansible/ansible/issues/26359#issuecomment-316004134

**Comment by RogerSik** [comment]
Difficult to say it it happens with the upgrade to AWX 7.0.0.0. But the issues appeared shortly after upgrade to 7.0.0.0.

**Comment by ryanpetrello** [comment]
@wilkis3 @RogerSik have you tried another version of Ansible itself (we *do* regularly update the default Ansible version in new AWX releases)?  The symptoms described here don't sound related to AWX _to me_, but rather Ansible (at least, the verbose output above looks like the hanging is happening in the SSH connection).

**Comment by ryanpetrello** [comment]
Also, if you're seeing playbooks that run, complete some number of tasks, and then just **hang** halfway through - assuming you still see an `ansible-playbook` process running on the underlying host* - this strongly suggests to me that what you're encountering is a problem with Ansible itself, not AWX.

**Comment by RogerSik** [comment]
@ryanpetrello when using the AWX Docker Image, where we can change the Ansible Version?

**Comment by RogerSik** [comment]
Found the issue. Thanks to /var/syslog in the machines (which was many times another machine) it was visible that gather_timeout was running in 10 second timeout.

Setting 
`gather_timeout: 30`

solved it.

**Comment by RogerSik** [comment]
Revert it back. It was random completed succesfully. After starting it again multiple times it appears again.

**Comment by RogerSik** [comment]
The issue was now (after testing it multiple times) in the apt: module when using update_cache: true. 
After removing them (they were also unnecessaryin our playbooks) it works now after testing it multiple times.  I think its a problem with the current AWX / Ansible version. 

I can also recreate the hanging job always when I use update_cache: true 

Where would it best to report this?

**Comment by ryanpetrello** [comment]
@RogerSik what you're describing sounds like an issue with Ansible to me (not AWX).  I can't speak for @wilkis3, so I'll keep this issue open for now in case they're encountering something different.

**Comment by RogerSik** [comment]
Someone else also reported this problem in Ansible https://github.com/ansible/ansible/issues/62807 so we will continue there

**Comment by wilkis3** [comment]
@ryanpetrello thanks for help.
@RogerSik and I are working in the same company on the same AWX instance.
It looks like an ansible bug.

**Comment by ryanpetrello** [comment]
> https://github.com/ansible/awx/issues/4813#issuecomment-535873402

If you'd like to try to identify this as a regression in newer Ansibles (by testing an older version), check out this document for instructions on running custom versions of Ansible in AWX:

https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md
