### ISSUE TITLE
AWX containers fail to start using docker-entrypoint.sh due to permission denied

### ISSUE THREAD

**Issue by jcruzA1** [ansible/awx#482]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Installer fails at task "AWX Activate AWX Web Container" due to issues with preceding tasks "Activate postgres/rabbitmq/memcached container" failing to start the postgres, rabbitmq and memcached containers.

##### ENVIRONMENT
* Ansible version:  2.3.2.0
* Docker-io version:  1.7.1
* Operating System: CentOS 6.9 

##### STEPS TO REPRODUCE

* Run installer

`# cd /opt/awx/installer`
`# ansible-playbook -i inventory install.yml`

##### EXPECTED RESULTS

A working installation with Docker running 5 containers - postgres, rabbitmq, memcached, ansible/awx_web, ansible/awx_task.

##### ACTUAL RESULTS

Output of failed task from installer:
`TASK [local_docker : Activate AWX Web Container] **********************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error starting container f202c4eedf86e3b311a514ea12cc1024b49707451f6fbd5925b32ff5589fb27c: 500 Server Error: Internal Server Error (\"Cannot start container f202c4eedf86e3b311a514ea12cc1024b49707451f6fbd5925b32ff5589fb27c: Cannot link to a non running container: /postgres AS /awx_web/postgres\")"}
        to retry, use: --limit @/opt/awx/installer/install.retry`

Output of docker ps -a:
`CONTAINER ID        IMAGE                    COMMAND                CREATED             STATUS                     PORTS               NAMES`
`f202c4eedf86        ansible/awx_web:latest   "/tini -- /bin/sh -c   17 hours ago                                                       awx_web`
`7e3ae267a83b        memcached:alpine         "docker-entrypoint.s   17 hours ago        Exited (2) 3 minutes ago                       memcached`
`b4e8de5aa596        rabbitmq:3               "docker-entrypoint.s   17 hours ago        Exited (1) 3 minutes ago                       rabbitmq`
`f3d1bb50fc71        postgres:9.6             "docker-entrypoint.s   17 hours ago        Exited (1) 3 minutes ago                       postgres`

Output of docker logs for postgres/rabbitmq/memcached containers:
`error: exec: "/usr/local/bin/docker-entrypoint.sh": stat /usr/local/bin/docker-entrypoint.sh: permission denied`

##### ADDITIONAL INFORMATION

Attempt to start the docker containers manually fail with the same error:
`# docker start postgres`
`error: exec: "/usr/local/bin/docker-entrypoint.sh": stat /usr/local/bin/docker-entrypoint.sh: permission denied`

Attempt to run from a docker image works:
`# docker run -it postgres:9.6 /bin/bash`
`root@2c2371d14ff5:/# hostname`
`2c2371d14ff5`

Attempt to run from a docker image and execute 'docker-entrypoint.sh' fails:
`# docker run -it postgres:9.6 "docker-entrypoint.sh"`

Other:
* SELinux is disabled
* Running installer as root

**Comment by putz612** [comment]
I am running into this as well and was able to get more log data to help from the awx_web container.

`10/23/2017 3:49:18 PM2017-10-23 20:49:18,514 INFO spawned: 'nginx' with pid 43
10/23/2017 3:49:18 PM2017-10-23 20:49:18,514 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
10/23/2017 3:49:18 PMnginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
10/23/2017 3:49:18 PM2017/10/23 20:49:18 [emerg] 43#0: mkdir() "/var/lib/nginx/tmp/client_body" failed (13: Permission denied)
10/23/2017 3:49:18 PM2017-10-23 20:49:18,531 INFO exited: nginx (exit status 1; not expected)`

**Comment by putz612** [comment]
My original log file was from awx_web:1.0.1.81, I just tired ansible/awx_web:1.0.1.93 and I am seeing the same issue.

**Comment by matburt** [comment]
We had some churn around this a while ago... are you still seeing this?

**Comment by krispayne** [comment]
I'm having problems with postgres:9.6 sitting on docker-entrypoint.sh but the logs do not say anything about permission denied. This is on a system that was stable a few days ago. i.e. I have not ran the installer.yml in quite some time, but I am on the latest release version.

```
initdb: directory "/var/lib/postgresql/data/pgdata" exists but is not empty
If you want to create a new database system, either remove or empty
the directory "/var/lib/postgresql/data/pgdata" or run initdb
with an argument other than "/var/lib/postgresql/data/pgdata".
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
initdb: directory "/var/lib/postgresql/data/pgdata" exists but is not empty
If you want to create a new database system, either remove or empty
the directory "/var/lib/postgresql/data/pgdata" or run initdb
with an argument other than "/var/lib/postgresql/data/pgdata".
The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".
Data page checksums are disabled.
initdb: directory "/var/lib/postgresql/data/pgdata" exists but is not empty
If you want to create a new database system, either remove or empty
the directory "/var/lib/postgresql/data/pgdata" or run initdb
with an argument other than "/var/lib/postgresql/data/pgdata".
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".
Data page checksums are disabled.
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".
Data page checksums are disabled.
initdb: directory "/var/lib/postgresql/data/pgdata" exists but is not empty
If you want to create a new database system, either remove or empty
the directory "/var/lib/postgresql/data/pgdata" or run initdb
with an argument other than "/var/lib/postgresql/data/pgdata".
```

```
55194e2957bd        postgres:9.6              "docker-entrypoint.sh"   2 weeks ago         Restarting (1) 2 minutes ago   5432/tcp                             postgres
```

**Comment by MarkJB** [comment]
Was this resolved?

I'm seeing the `initdb: directory "/var/lib/postgresql/data/pgdata" exists but is not empty` issue with a clean install and the latest installer.
