### ISSUE TITLE
AWX install fails due to libselinux-python error

### ISSUE THREAD

**Issue by shemlik** [ansible/awx#4821]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I'm trying to install Ansible AWX on my local environment (RHEL 7 Maipo). But during the install run, it fails with the "libselinux-python" error.

##### ENVIRONMENT
* AWX version: 7.0.0
* AWX install method: docker on linux,
* Ansible version:  2.8.5
* Operating System: RHEL 7.5 (Maipo). Kernel 3.10.0-957.27.2.el7.x86_64
* Web Browser: Chrome Version 76.0.3809.132

##### STEPS TO REPRODUCE

1) Install Python 36 packages (System already had Python 2.7 but was having difficulties with Python Pip and wheel). Hence the need to install Python 36.

rh-python36-python-libs-3.6.3-7.el7.x86_64
rh-python36-runtime-2.0-1.el7.x86_64
rh-python36-python-setuptools-36.5.0-1.el7.noarch
rh-python36-python-pip-9.0.1-2.el7.noarch
rh-python36-python-devel-3.6.3-7.el7.x86_64
rh-python36-python-3.6.3-7.el7.x86_64
rh-python36-python-virtualenv-15.1.0-2.el7.noarch

2) Create a virtualenv "awxenv.
3) Using pip install the below packages

-->pip -V
pip 19.2.3 from /usr/mware/pythonApps/awxenv/lib/python3.6/site-packages/pip (python 3.6)

-->pip list
Package          Version
---------------- ---------
ansible          2.8.5
asn1crypto       0.24.0
bcrypt           3.1.7
cached-property  1.5.1
certifi          2019.9.11
cffi             1.12.3
chardet          3.0.4
cryptography     2.7
docker           3.7.3
docker-compose   1.24.1
docker-pycreds   0.4.0
dockerpty        0.4.1
docopt           0.6.2
idna             2.7
Jinja2           2.10.1
jsonschema       2.6.0
MarkupSafe       1.1.1
paramiko         2.6.0
pip              19.2.3
pycparser        2.19
PyNaCl           1.3.0
PyYAML           3.13
requests         2.20.1
setuptools       28.8.0
six              1.12.0
texttable        0.9.1
urllib3          1.24.3
websocket-client 0.56.0
wheel            0.29.0

4) Cloned AWX Git repo.
5) Went inside the installer directory. Updated "inventory" to use python3
localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python3"

6) Ran the below command
ansible-playbook -i inventory install.yml

7) Returned the error

TASK [local_docker : Create Docker Compose Configuration] *****************************************************************************************************************************
failed: [localhost] (item=environment.sh) => {"ansible_loop_var": "item", "changed": false, "checksum": "e369ef7b0186eef5f38dc16027878a3a6a0d9f0c", "item": "environment.sh", "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}
failed: [localhost] (item=credentials.py) => {"ansible_loop_var": "item", "changed": false, "checksum": "9d8c48ec0e65f6cc2aa8d1e2720f826b0f65551a", "item": "credentials.py", "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}
failed: [localhost] (item=docker-compose.yml) => {"ansible_loop_var": "item", "changed": false, "checksum": "35538f46d9cb24e817a8754db4c4f2431c126ec3", "item": "docker-compose.yml", "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}

PLAY RECAP ****************************************************************************************************************************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=1    skipped=78   rescued=0    ignored=0

8) Verified that the selinux packages are already installed.

-->rpm -qa |grep selinux
libselinux-2.5-14.1.el7.x86_64
selinux-policy-3.13.1-229.el7_6.6.noarch
container-selinux-2.77-1.el7_6.noarch
libselinux-python-2.5-14.1.el7.x86_64
libselinux-utils-2.5-14.1.el7.x86_64
selinux-policy-targeted-3.13.1-229.el7_6.6.noarch

##### EXPECTED RESULTS

I expected the playbook to complete the setup of docker image, bring up the container and run awx instance.

##### ACTUAL RESULTS

Playbok failed to complete the run and threw the below error.

TASK [local_docker : Create /tmp/awxcompose directory] ********************************************************************************************************************************
ok: [localhost]

TASK [local_docker : Create Docker Compose Configuration] *****************************************************************************************************************************
failed: [localhost] (item=environment.sh) => {"ansible_loop_var": "item", "changed": false, "checksum": "e369ef7b0186eef5f38dc16027878a3a6a0d9f0c", "item": "environment.sh", "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}
failed: [localhost] (item=credentials.py) => {"ansible_loop_var": "item", "changed": false, "checksum": "9d8c48ec0e65f6cc2aa8d1e2720f826b0f65551a", "item": "credentials.py", "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}
failed: [localhost] (item=docker-compose.yml) => {"ansible_loop_var": "item", "changed": false, "checksum": "35538f46d9cb24e817a8754db4c4f2431c126ec3", "item": "docker-compose.yml", "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}

PLAY RECAP ****************************************************************************************************************************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=1    skipped=78   rescued=0    ignored=0

##### ADDITIONAL INFORMATION

1) I tried restoring the "inventory" file to default to use the OS default Python (Python 2.7). Did not work.
2) Tried updating system python to Python3 by adding python3 to "/usr/local/sbin/python". Did not work.
3) Tried changing /usr/bin/python to point to python3 but that broke my OS (yum failed and other issues.)

2 things that I noticed
i) installing  "libselinux-python-2.5-14.1.el7.x86_64" package creates a "selinux" folder under "/usr/lib64/python2.7/site-packages" but not under "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/ " (which is the python3 installation location). This is despite the fact that python3 is the default python as explained above (Addition Information section).

ii) Python virtualenv does not have "selinux" module installed. If I install it, it causes virtualenv to crash. Ansible commands fail until I remove "selinux" python module. Error I get is

-->ansible
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'site' has no attribute 'getsitepackages'
ERROR! Unexpected Exception, this is probably a bug: Command '['/usr/bin/python3', '-c', 'import json, site; print(json.dumps(site.getsitepackages()))']' returned non-zero exit status 1.
the full traceback was:

Traceback (most recent call last):
  File "/usr/mware/pythonApps/awxenv/bin/ansible", line 90, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/usr/mware/pythonApps/awxenv/lib/python3.6/site-packages/ansible/cli/__init__.py", line 25, in <module>
    from ansible.parsing.dataloader import DataLoader
  File "/usr/mware/pythonApps/awxenv/lib/python3.6/site-packages/ansible/parsing/dataloader.py", line 17, in <module>
    from ansible.module_utils.basic import is_executable
  File "/usr/mware/pythonApps/awxenv/lib/python3.6/site-packages/ansible/module_utils/basic.py", line 74, in <module>
    import selinux
  File "/usr/mware/pythonApps/awxenv/lib/python3.6/site-packages/selinux/__init__.py", line 91, in <module>
    check_system_sitepackages()
  File "/usr/mware/pythonApps/awxenv/lib/python3.6/site-packages/selinux/__init__.py", line 81, in check_system_sitepackages
    system_sitepackages = get_system_sitepackages()
  File "/usr/mware/pythonApps/awxenv/lib/python3.6/site-packages/selinux/__init__.py", line 71, in get_system_sitepackages
    "import json, site; print(json.dumps(site.getsitepackages()))"
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-c', 'import json, site; print(json.dumps(site.getsitepackages()))']' returned non-zero exit status 1.

Selinux Python module is

selinux          0.1.6

Any help would be really appreciated.

Thanks,
Shemlik

**Comment by wenottingham** [comment]
You installed the python2 selinux bindings, and told it to use python3 instead. That will throw that error.

The other errors you post look like a misconfigured local environment as well. This does not look like an AWX issue, and is best discussed on the mailing list or IRC channel.

**Comment by shemlik** [comment]
I already mentioned that I tried to use both Python2 and Python3 and their specific results. I was not able to run the installer in both cases.

While I can understand that this might be an environmental issue, unless it is found what that issue is, it doesn't feel right to ignore the issue and close it. Do you have any suggestions on what could be the environment issue. I have already put in all the details to replicate the issue.

**Comment by wenottingham** [comment]
See above - this repo is specifically for tracking bugs, and discussing configuration is best done on the mailing list or IRC channel.

**Comment by vindevoy** [comment]
Hi, even if this is closed, I would like to add some comments.  I have the same problem and it's really a python config issue.

On RHEL7, python3.6 causes some huge problems:
- yum stops working
- docker daemon does not start

Using python2.7, docker and yum work correctly.  

I have verified this with using alternatives, switching between both.  When you run the playbook with python3.6 and the requirements listed above installed, the playbook does not have the problem with the libselinux-python missing.  Unfortunately, for me it crashes afterwards again on downloading the rabbitmq.  My server should use a local Nexus instead, so I'm stuck there for now.

But the problem above, is indeed not AWX, but python3 on RHEL7

**Comment by vindevoy** [comment]
Oh, as I am using the original install.yml playbook, it would be nice to add an option to specify the Nexus where to download, or just to use the Dockerhub repos.

**Comment by omidabc** [comment]
I simply run this and it solved my problem

> yum install libselinux-python3
