### ISSUE TITLE
Multiple vault credentials no longer allowed on a template? 

### ISSUE THREAD

**Issue by Freeze** [ansible/awx#4826]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
As of 7.0.0 we are no longer able to assign multiple vault credentials to a template.  This is a breaking change that will not allow us to upgrade AWX.  

##### ENVIRONMENT
* AWX version: 7.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.4
* Operating System: RHEL 7.6
* Web Browser: Safari, Chrome, FireFox.  Depends on my mood. 

##### STEPS TO REPRODUCE

```
curl -X POST \
  https://myawx/api/v2/job_templates/24/credentials/ \
  -d '{
    "associate": "true",
    "id": 6
}
```

against a template that already has a vault credential.  

##### EXPECTED RESULTS

204.   An additional vault credential added.  

##### ACTUAL RESULTS

400:
```
 {
    "error": "Cannot assign multiple Vault credentials."
}
```
##### ADDITIONAL INFORMATION

This worked in previous versions.  It seems like there have been a large amount of changes to the credential process and no changelog to speak of.

**Comment by ryanpetrello** [comment]
@Freeze,

You *can* assign multiple Vault credentials to a Job Template, but they must specify **different** Vault identifiers (AWX has behaved this since we introduced support for multiple vault credentials a few years ago):

![Kapture 2019-09-27 at 0 05 32](https://user-images.githubusercontent.com/214912/65741660-e3afd100-e0ba-11e9-9e31-4d5d2c14b5bf.gif)

```shell
~ awx credentials list --credential_type Vault -f human --filter id,inputs
id inputs
== ====================================================
2  {"vault_password": "$encrypted$"}
3  {"vault_password": "$encrypted$"}
4  {"vault_id": "foo", "vault_password": "$encrypted$"}

~ curl -ik "https://awx.example.org/api/v2/job_templates/7/credentials/" -X POST -d '{"associate": true, "id": 2}' -H "Content-Type:application/json"
HTTP/1.1 204 No Content

~ curl -ik "https://awx.example.org/api/v2/job_templates/7/credentials/" -X POST -d '{"associate": true, "id": 3}' -H "Content-Type:application/json"
HTTP/1.1 400 Bad Request
...
{"error":"Cannot assign multiple Vault credentials."}

~ curl -ik "https://awx.example.org/api/v2/job_templates/7/credentials/" -X POST -d '{"associate": true, "id": 4}' -H "Content-Type:application/json"
HTTP/1.1 204 No Content

~ awx job_templates get 7 -f jq --filter '.summary_fields.credentials' | python -m json.tool
[
    {
        "id": 1,
        "name": "Demo Credential",
        "description": "",
        "kind": "ssh",
        "cloud": false
    },
    {
        "id": 2,
        "name": "No Vault ID Specified Here Either",
        "description": "",
        "kind": "vault",
        "cloud": false
    },
    {
        "id": 4,
        "name": "This Has a Unique Vault ID",
        "description": "",
        "kind": "vault",
        "cloud": false
    }
]
```

https://github.com/ansible/awx/issues/352
https://github.com/ansible/awx/issues/352#issuecomment-337995178
https://docs.ansible.com/ansible/latest/user_guide/vault.html#vault-ids-and-multiple-vault-passwords
