### ISSUE TITLE
templates change dialog states "Credential" instead of plural

### ISSUE THREAD

**Issue by AlexanderStohr** [ansible/awx#4831]
the interface should state "Credentials" as it is possible to select a multitude of credentials.

Checking for a few types:
* Machine -> single selection
* Network -> single selection
* Vault -> multiple selections

As its possible to have at least one of each type (and for Vault even multiple), there is definitely the option to have a multitude of credentials. - My current test setup shows right now 5 items listed in this single box. Thus a plural in the headline is indicated.

**Comment by ryanpetrello** [comment]
Thanks for reporting this, @AlexanderStohr, it'll be available in the next release of AWX.
