### ISSUE TITLE
[Question] How to extract inventory list from AWX?

### ISSUE THREAD

**Issue by 4815162342lost** [ansible/awx#4832]
How to extract inventory list from AWX?

Hello, we are using AWX version 4.0.0.0 on Kubernetes.  We want to refuse from AWX and use common Ansible from command line (ansible-playbook). Or maybe migrate to AWX with docker-compose later.

How can we extract inventory list from AWX with all custom vars? 

I entered to docker container and what i should enter to console? I have found awx-manage utility, but can not found proper function and args...

Please, help.

Thanks!

**Comment by blindrood** [comment]
https://adam.younglogic.com/2018/08/ansible-tower-inventory-cli/

**Comment by ryanpetrello** [comment]
Hey @4815162342lost,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
