### ISSUE TITLE
localhost awx

### ISSUE THREAD

**Issue by pra2012** [ansible/awx#4841]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
TASK [image_build : Verify awx-logos directory exists for official install] **********************************************************************************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed_when_result": true, "stat": {"exists": false}}
        to retry, use: --limit @/awx-6.1.0/installer/install.retry

##### ENVIRONMENT
* AWX version:awx-6.1.0
* Ansible version: ansible 2.4.2.0
* Operating System:Red Hat 7.7 

##### STEPS TO REPRODUCE
[root@brsmcomcawx02 installer]# ansible-playbook -i inventory install.yml

PLAY [Build and deploy AWX] **********************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************
ok: [localhost]

TASK [check_vars : include_tasks] ****************************************************************************************************************************************************************
skipping: [localhost]

TASK [check_vars : include_tasks] ****************************************************************************************************************************************************************
included: /awx-6.1.0/installer/roles/check_vars/tasks/check_docker.yml for localhost

TASK [check_vars : postgres_data_dir should be defined] ******************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [check_vars : host_port should be defined] **************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [image_build : Set global version if not provided] ******************************************************************************************************************************************
ok: [localhost]

TASK [image_build : Verify awx-logos directory exists for official install] **********************************************************************************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed_when_result": true, "stat": {"exists": false}}
        to retry, use: --limit @/awx-6.1.0/installer/install.retry

PLAY RECAP ***************************************************************************************************************************************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=1

**Comment by ryanpetrello** [comment]
@pra2012,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
