### ISSUE TITLE
AWX & Bastion Host - Persistent SSH Keys

### ISSUE THREAD

**Issue by RyanW19** [ansible/awx#4842]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - awx_task Container

##### SUMMARY
To connect to some hosts across our environment we require the use of a Bastion host, after installing the SSH public key of awx_task container to the pre-configured bastion hosts all works as expected and we're able to get to the required environments.

After a reboot of the machine (or simply stop/start of awx_task container) the SSH key pair on the awx_task container is not persistent meaning a new keypair needs to be generated and copied over to the bastion hosts.
##### ENVIRONMENT
* AWX version: 7.0.0
* AWX install method: docker on linux
* Ansible version: 2.8.4
* Operating System: CentOS 7
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

1) Generate SSH RSA Keypair on awx_task container
2) Copy the public key to required bastion hosts
3) Test connection to the bastion hosts using the keypaid
4) Stop awx_task docker container
5) Start awx_task docker container
6) Repeat Step 3
##### EXPECTED RESULTS

I expected that the SSH key generated in the /root/.ssh directory of awx_task container to remain consistent over reboots.

##### ACTUAL RESULTS

SSH Key that was generated was not persistent and had to be re-generated

**Comment by Joffrey54** [comment]
It's not a bug, it's a normal docker behaviour.
You must edit the docker-compose file and mount a directory to /root/.ssh to persist and manage keys

**Comment by RyanW19** [comment]
@nORKy54 Mind letting me know where the docker-compose file so I can do as suggested. Had a look in ~/awx/tools/docker-compose.yml and couldn't find anything relating to awx_task container.
