### ISSUE TITLE
Notifications placeholder on WFJT tab looks strange at smaller widths

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#4846]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
If you make a workflow, go to the notifications tab, and view AWX and shrink your screen width, this happens:
![Screenshot from 2019-09-30 10-43-59](https://user-images.githubusercontent.com/19942822/65889494-5517aa00-e36f-11e9-903c-646447dc29a4.png)

##### ENVIRONMENT
* AWX version: latest
* Operating System: Fedora 30
* Web Browser: Chrome

##### STEPS TO REPRODUCE
1. Make a workflow of any kind.
2. View the notifications tab when there are no notifications present.
3. Shrink the screen width.

##### EXPECTED RESULTS
The text wraps normally. 

##### ACTUAL RESULTS
See screenshot in summary.

**Comment by dsesami** [comment]
![Screenshot from 2019-10-17 10-59-33](https://user-images.githubusercontent.com/19942822/67021160-36cedf80-f0cd-11e9-8f04-199098dd4dfd.png)
 Looks much better! thanks.

**Comment by mabashian** [comment]
Re-opening due to #3871.  We'll need to come up with a different way to solve this problem.

**Comment by keithjgrant** [comment]
The flexbox solution here should work, but we'll need to get rid of the `margin-bottom: -34px;` on `.List-actions` and adjust other padding/margins around it to get the spacing right.

The bug occurs because of the way two elements overlap with the negative margin—switching to flexbox affected the stacking behavior.

**Comment by wenottingham** [comment]
punting low-priority UI nits to ui-next

**Comment by unlikelyzero** [comment]
covered in empty.spec.js
