### ISSUE TITLE
Inert link for Container group on Job Results page

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#4848]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
On Job Results Page, unable to open a Container group reflink for completed Job

##### ENVIRONMENT
* AWX version: 7.0.0-container-group

##### STEPS TO REPRODUCE
1. Launch a Job with a Container Group
2. On Job Result detail page for that launched job, click the container group link
Note: Inert

##### EXPECTED RESULTS
1. Nav to container group

##### ACTUAL RESULTS
Nothing

**Comment by one-t** [comment]
Confirmed that there is now a link on the job results page and that it leads to the container group.
