### ISSUE TITLE
RFE: Add an inventory import option for tower-cli

### ISSUE THREAD

**Issue by vi-patel** [ansible/awx#485]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Can the tower-cli have an option to upload inventories?

Instead of creating the inventory object and adding groups and hosts.

Similiar to the functionality that the admin can use tower-manage (tower-manage inventory_import option).

##### ENVIRONMENT
* AWX version: AWX 1.0.0.588
* AWX install method:  docker on linux
* Ansible version: Ansible 2.4.0.0

**Comment by wenottingham** [comment]
tower-cli/awx-cli would need an API endpoint for uploading an inventory file/definition to use.

No such endpoint exists (as may be clear from the request). Question would be what do do around things like group_vars directories on the tower-cli side (or whether to just limit it to single-file usage).

**Comment by AlanCoding** [comment]
Related https://github.com/ansible/tower-cli/issues/197

**Comment by AlanCoding** [comment]
tower-cli is deprecated

anyone is free to file a new request for AWX CLI, if there is still interest
