### ISSUE TITLE
"Error pulling image postgres:9.6 - 500 Server Error:  - AWX Install

### ISSUE THREAD

**Issue by doves99** [ansible/awx#4858]
##### ISSUE TYPE
 - Cannot install AWX

##### SUMMARY

When i tried to install the awx, i am getting the following error

TASK [local_docker : Activate postgres container] ************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error pulling image postgres:9.6 - 500 Server Error: Internal Server Error (\"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)\")"}

-------------
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_docker_container_payload_XogXGY/ansible_docker_container_payload.zip/ansible/module_utils/docker/common.py", line 680, in pull_image
    for line in self.pull(name, tag=tag, stream=True, decode=True):
  File "/usr/lib/python2.7/site-packages/docker/api/image.py", line 393, in pull
    self._raise_for_status(response)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 224, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_version": "auto",
            "auto_remove": false,
            "blkio_weight": null,
            "ca_cert": null,
            "cap_drop": null,
            "capabilities": null,
            "cleanup": false,
            "client_cert": null,
            "client_key": null,
            "command": null,
            "comparisons": null,
            "cpu_period": null,
            "cpu_quota": null,
            "cpu_shares": null,
            "cpuset_cpus": null,
            "cpuset_mems": null,
            "debug": false,
            "detach": true,
            "device_read_bps": null,
            "device_read_iops": null,
            "device_write_bps": null,
            "device_write_iops": null,
            "devices": null,
            "dns_opts": null,
            "dns_search_domains": null,
            "dns_servers": null,
            "docker_host": "unix://var/run/docker.sock",
            "domainname": null,
            "entrypoint": null,
            "env": {
                "PGDATA": "/var/lib/postgresql/data/pgdata",
                "POSTGRES_DB": "awx",
                "POSTGRES_PASSWORD": "awxpass",
                "POSTGRES_USER": "awx"
            },
            "env_file": null,
            "etc_hosts": null,
            "exposed_ports": null,
            "force_kill": false,
            "groups": null,
            "healthcheck": null,
            "hostname": null,
            "ignore_image": false,
            "image": "postgres:9.6",
            "init": false,
            "interactive": false,
            "ipc_mode": null,
            "keep_volumes": true,
            "kernel_memory": null,
            "kill_signal": null,
            "labels": null,
            "links": null,
            "log_driver": null,
            "log_options": null,
            "mac_address": null,
            "memory": "0",
            "memory_reservation": null,
            "memory_swap": null,
            "memory_swappiness": null,
            "name": "postgres",
            "network_mode": null,
            "networks": null,
            "networks_cli_compatible": null,
            "oom_killer": null,
            "oom_score_adj": null,
            "output_logs": false,
            "paused": false,
            "pid_mode": null,
            "pids_limit": null,
            "privileged": false,
            "published_ports": null,
            "pull": false,
            "purge_networks": false,
            "read_only": false,
            "recreate": false,
            "restart": false,
            "restart_policy": "unless-stopped",
            "restart_retries": null,
            "runtime": null,
            "security_opts": null,
            "shm_size": null,
            "ssl_version": null,
            "state": "started",
            "stop_signal": null,
            "stop_timeout": null,
            "sysctls": null,
            "timeout": 60,
            "tls": false,
            "tls_hostname": "localhost",
            "tmpfs": null,
            "trust_image_content": false,
            "tty": false,
            "ulimits": null,
            "user": null,
            "userns_mode": null,
            "uts": null,
            "validate_certs": false,
            "volume_driver": null,
            "volumes": [
                "/opt/pgdocker:/var/lib/postgresql/data:Z"
            ],
            "volumes_from": null,
            "working_dir": null
        }
    },
    "msg": "Error pulling image postgres:9.6 - 500 Server Error: Internal Server Error (\"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)\")"

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: docker on linux,
* Ansible version:  2.8.4
* Operating System: Linux
* Web Browser:

##### EXPECTED RESULTS
Installed as per the outline https://github.com/ansible/awx/blob/devel/INSTALL.md
When running "ansible-playbook -i inventory install.yml" should install the AWX and containers should be coming up.

##### ACTUAL RESULTS

When it came to Activate postgres container the following error came up
TASK [local_docker : Activate postgres container] ************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error pulling image postgres:9.6 - 500 Server Error: Internal Server Error (\"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)\")"}
##### ADDITIONAL INFORMATION
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:28:55 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:27:34 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

docker-compose version 1.18.0, build 8dd22a9

**Comment by ryanpetrello** [comment]
@doves99 

`Error pulling image postgres:9.6 - 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection`

This looks to me like a temporary issue pulling from `docker.io`, not a bug in AWX itself.
