### ISSUE TITLE
Modify OpenShift deployment to put web and task into sep pods to allow for component scaling

### ISSUE THREAD

**Issue by derekmwright** [ansible/awx#486]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
- AWX Task
- AWX Web

##### SUMMARY
Current OpenShift deployment doesn't allow for individual components to scale

##### STEPS TO REPRODUCE

Separate Web and Task containers into their own Pods

##### EXPECTED RESULTS

Would allow for web or tasks pod to be scaled independently.

##### ADDITIONAL INFORMATION

Not being a django expert im not sure of the gains of how its currently running. But since they are in separate containers it seems they each have to load the entire django app to run anyways. Also not sure if this is the proper way to scale workers/task engines or if there is another preferable option.

**Comment by matburt** [comment]
This is something I'm looking at on our `scalable_clusters` branch.
