### ISSUE TITLE
using ansible kubernetes module on ansible tower

### ISSUE THREAD

**Issue by msterckx** [ansible/awx#4861]
Hi,
Does anyone know if it's possible to use the ansible kubernetes module (k8s) on AWX?  I'm getting this error: _no module named kubernetes_.

regards,
Michel

**Comment by ryanpetrello** [comment]
Hey @msterckx,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
