### ISSUE TITLE
How does the concurrency achieved in awx without parallel-ssh

### ISSUE THREAD

**Issue by gsakkar** [ansible/awx#4862]
##### ISSUE TYPE
 Most of the Ansible default transport layer is openssh. is there any scope for using https://github.com/ParallelSSH/parallel-ssh

##### SUMMARY

 Most of the Ansible default transport layer is openssh. is there any scope for using https://github.com/ParallelSSH/parallel-ssh it has better performance compare to openssh

if you dont have plan to use parallelssh what is the defect ssh transport is used to achive parallelism

**Comment by ryanpetrello** [comment]
@gsakkar,

This repository is unique to the Ansible AWX project.  If you've got questions about Ansible in general, check out the Ansible mailing list or IRC room:

https://groups.google.com/d/forum/ansible-project
`#ansible` on freenode
