### ISSUE TITLE
Folder Structure/More Organised Projects and Job Templates

### ISSUE THREAD

**Issue by RyanW19** [ansible/awx#4873]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
It would be great to have the ability to organise job templates, projects, inventories etc into folders, sub folders etc. This is more useful for the larger deployments/those with large numbers of projects for example. Not sure what other information to add as this is quite self-explanatory.

**Comment by wenottingham** [comment]
-> #2350
