### ISSUE TITLE
Credential type injector should be able to conditionally include environment variables

### ISSUE THREAD

**Issue by jangsutsr** [ansible/awx#488]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Currently if a credential type set up an environment variable injector, like `"ENV_NAME": "{{some_input_value}}"`, but the input value is not provided in credential `inputs`, the environment variable will still be set up as an empty string: `ENV_NAME=''`.

In reality, however, it is usually preferred the environment variable is *not set in the first place* if the value is not given, rather than providing an empty environment variable.

It would be better if we figure out a way of doing that.

##### ENVIRONMENT
* AWX version: N/A
* AWX install method: docker for mac
* Ansible version: N/A
* Operating System: N/A
* Web Browser: N/A

##### ADDITIONAL INFORMATION

Ping @ryanpetrello for opinion.

**Comment by wenottingham** [comment]
Is this for credential types with optional inputs? (As opposed to ones where there's an injector with no corresponding input at all).

**Comment by jangsutsr** [comment]
@wenottingham Yes. Like if injector is like `"ENV_VAR": "{{optional_var}}"` and `optional_var` is optional.

**Comment by ryanpetrello** [comment]
The trick to implementing this is that the Jinja template could be *anything*; it's not always so cut and dry as a simple variable substitution like this.  For example, how do we determine what to do for an injector like this?

`"ENV_VAR": "{{optional_var.upper() if optional_var else other_required_var}}"`

In practice, it's probably nearly impossible to determine if a value was composed of *solely* a certain named optional variable.

In general, maybe if the value evaluates to an empty string, we *don't* set the environment variable at all?

**Comment by jangsutsr** [comment]
@ryanpetrello That's true, I see why we don't have that in the first place.
> In general, maybe if the value evaluates to an empty string, we don't set the environment variable at all?

I thought of that, the issue might be cases where env variables are intentionally set to empty string. If we are safe to ignore those cases, we can do that.

**Comment by wenottingham** [comment]
... if it comes down to "trying to determine whether the user intentionally set an env var to empty", that's a strong argument for doing nothing for this case and telling the users to handle empty env vars themselves.

**Comment by cchurch** [comment]
Why not add a special `omit` variable [like Ansible does](https://github.com/ansible/ansible/blob/7fe6a8dab7740369f816fd54c60b6619700d065c/lib/ansible/vars/manager.py#L123), which is essentially a token that would indicate that an environment variable should not be set?

```
"ENV_VAR": "{{optional_var.upper() if optional_var else omit}}"
```

**Comment by ryanpetrello** [comment]
If you build an environment variable that renders to an empty string, is there any reason we wouldn't just omit the environment variable, generally speaking?  This seems like a fairly reasonable behavior to me.  Why would you want to set an environment variable with an empty string?

**Comment by wenottingham** [comment]
Also, whatever we do for env vars we should probably do for extra_vars (unless there's a compelling reason not to that I'm missing)

**Comment by shanemcd** [comment]
Closing due to lack of discussion and interest.
