### ISSUE TITLE
OpenShift user password is not always available (let the user "oc login" before installation)  

### ISSUE THREAD

**Issue by rassie** [ansible/awx#489]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
The installer currently requires `openshift_password` to be set, but depending on the environment, using a password might be not be desirable or possible.

##### STEPS TO REPRODUCE
Have one of the following on OpenShift:

1. OpenShift installation with third-party OAuth (like G-Suite)
2. A technical user in OpenShift used for installations without a password but with auth tokens.
3. Any other situation where you might want to use login tokens instead of passwords.

and then try installing AWX on OpenShift.

##### EXPECTED RESULTS
Installation should succeed at the very least when the user has logged in via `oc login` before installation.

##### ACTUAL RESULTS
Installer demands a username and a password.

**Comment by shanemcd** [comment]
No longer relevant after the transition to awx-operator.
