### ISSUE TITLE
Workflow approvals API: Add "approved_by" field.

### ISSUE THREAD

**Issue by austlane** [ansible/awx#4891]
In the AWX API, there should be a field that includes the user that approved/denied the workflow execution.

```
<awx_hostname>/api/v2/workflow_approvals/<approval_job_id>
```
Currently in this endpoint, there is an array called **summary_fields**, which contains the following objects:
- workflow_job_template
- workflow_job
- workflow_approval_template
- unified_job_template
- *created_by*
- user_capabilities
- source_workflow_job

I'd love to see a new field added called **approved_by**, which includes the `id`/`username` of the user that approved the workflow_job. Similar to the `created_by` field.

Thanks for your consideration :) and thanks for making AWX!

**Comment by ryanpetrello** [comment]
cc @beeankha

**Comment by ryanpetrello** [comment]
This is going to involve, at a minimum:

1.  Adding a new related field to the `WorkflowApproval` object to track the user that approved or rejected it (including a migration to add the new column):

https://github.com/ansible/awx/blob/devel/awx/main/models/workflow.py#L672

Here's a similar field: https://github.com/ansible/awx/blob/devel/awx/main/models/base.py#L277

2.  When an approval node is actually approved or rejected, we should set this attribute to the current user.

3.  As noted in the issue description, a request to `/api/v2/workflow_approvals/<approval_job_id>` should show information about the approving/rejecting user (if any) in the summary fields.  A link under the `related` key might be nice, too.

Another consideration: if a user is _deleted_ at a later point in time, we'll likely lose this context.  I think that's fine so long as we verify that the approving/rejecting user it recorded in the activity stream (which is traditionally where we point users for auditing purposes).

**Comment by AlanCoding** [comment]
I thought we planned to abuse the `created_by` field or something like that for exactly this purpose. After all, consider all other unified jobs:

![Screen Shot 2019-10-10 at 2 51 37 PM](https://user-images.githubusercontent.com/1385596/66597719-8bbea300-eb6d-11e9-8020-5ed00e8aa8ef.png)

The UI puts up a big "Launched By" field. The model has no such field. It is getting this from the `created_by` user. Clearly a little abuse of notation has never bothered us before.

For workflow approvals, they are created by the system, that's true. But there's also a `modified_by` field which exists for all the unified job models but is not even exposed through the UI. This should be solvable on the API side with very minimal changes and no migration.

**Comment by ryanpetrello** [comment]
@AlanCoding I...didn't know that's how `Launched By` worked :D.

I'm fine if we want to go down a similar path here cc @ghjm

**Comment by ghjm** [comment]
Yeah, that makes sense to me.  But in the summary fields in `api/v2/workflow_approvals`, we would still call it `modified_by`, right?  Since that's what the field "really" is in API-land?

**Comment by ryanpetrello** [comment]
I dunno, I'm kind of going back and forth the more I think about this.  Launching something is basically the _same action_ as creating it, so I see the argument for overloading that attribute in that context.

Approving or denying something has nothing to with creating it.  And I don't think we can lean on `modified_by` because it's *possible* something could edit the record at some point, and then we lose context (the approver/denier).  I feel like it doesn't cost us that much to just add a new explicit field - what reason is there to take a shortcut other than "we took a shortcut before"?

Seems like an explicit field on the API would make it much easier for non-AWX devs  to understand, too.

**Comment by AlanCoding** [comment]
Let me add, `modified_by` should automatically be detected and shown in summary fields. This is a separate subject from surfacing it as a top-level field. The UI has to use the data from summary_fields.

So, wherever the status swaps to approved, try saving the user to the modified_by field, and see what happens. The most important thing right now is that the approver shows in the UI... however it gets there.

**Comment by ryanpetrello** [comment]
@AlanCoding yea, I just feel like overloading `modified_by` in this way is pretty opaque to anybody _other_ than us, and I'm arguing it doesn't really save us _that much_ versus adding a new explicit foreign key for this specific use case.

**Comment by matburt** [comment]
Lets add a specific field for the person who approved it or denied it. We're not going to abuse the created_by field and `modified` is subject to wiping out the change.

**Comment by elyezer** [comment]
I can confirm that the new field is now present, for example check the following response:

```json
{
    "id": 59,
    "type": "workflow_approval",
    "url": "/api/v2/workflow_approvals/59/",
    "related": {
        "created_by": "/api/v2/users/1/",
        "unified_job_template": "/api/v2/workflow_approval_templates/64/",
        "source_workflow_job": "/api/v2/workflow_jobs/58/",
        "workflow_approval_template": "/api/v2/workflow_approval_templates/64/",
        "approve": "/api/v2/workflow_approvals/59/approve/",
        "deny": "/api/v2/workflow_approvals/59/deny/",
        "approved_or_denied_by": "/api/v2/users/1/"
    },
    ...
}
```

Mind the `"approved_or_denied_by": "/api/v2/users/1/"` related field.
