### ISSUE TITLE
Make AWX collection pass all the default sanity tests

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#4892]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The Ansible sanity tests for `validate-modules` do not pass with the current version of the collection.

This commit should cover most of the errors:

https://github.com/ansible/ansible/commit/341eb8754e87676ccc1a44dec951b38c104e352d

We'll want to cherry-pick that.

But we also can't fully run the sanity tests because of https://github.com/ansible/ansible/issues/61884, so we'll need to temporarily hack through that or wait for a fix.

**Comment by AlanCoding** [comment]
throwing out a branch here:

https://github.com/ansible/awx/compare/devel...AlanCoding:collection_sanity?expand=1

doesn't run yet, there are several problems here.

**Comment by squidboylan** [comment]
I tested this locally by running `make test_collection_sanity` with latest tower release_3.6.0 and it passes.
