### ISSUE TITLE
CyberArk AIM Secret Lookup returns password as username

### ISSUE THREAD

**Issue by bamason14** [ansible/awx#4901]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I have setup a Credential for CyberArk AIM Secret Lookup. When I attach this credential to a playbook, it uses the password as the username.

##### ENVIRONMENT
* AWX version: 7.0.0 also tested on 6.1.0 w/ Ansible 2.8.4
* AWX install method: awx-rpm
* Ansible version:  2.8.5
* Operating System: RHEL 7.7
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

Created CyberArk AIM Credential as CyberArk AIM Secret Lookup.
Added URL and AppID and tested successfully.
Then Created credential for user awxdns and clicked search for username and selected CyberArk AIM. Added the metadata search and tested successfully.

Attached credentials to a simple Windows playbook and it fails to connect. Error is showing the password as the WinRM username.

Playbook:
---
- hosts: all

  vars_files:
    - group_vars/windows.yml
    

  tasks:
  - name: Get product id and product key
    win_product_facts:
    register: win_facts
    
  - debug:
      msg: "{{ win_facts }}"

_________________________
group_vars/windows.yml:
---

ansible_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_winrm_transport: kerberos
ansible_winrn_transport: ssl

Error:

fatal: [sever.domainname]: UNREACHABLE! => {"changed": false, "msg": "Kerberos auth failure for principal xxxxxxpasswordxxxxx with subprocess: kinit: Client 'xxxxxpasswordxxx@domainname' not found in Kerberos database while getting initial credentials", "unreachable": true}

##### EXPECTED RESULTS

expected username to be awxdns and to use the password from CyberArk AIM Secret Lookup

##### ACTUAL RESULTS

used the password from CyberArk AIM Secret Lookup as the username.

**Comment by ryanpetrello** [comment]
Can you share the output of `/api/v2/credential_input_sources/` ?

**Comment by bamason14** [comment]
HTTP 200 OK
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
X-API-Node: mmdawxl01.dev.mig.corp
X-API-Time: 0.013s

{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 1,
            "type": "credential_input_source",
            "url": "/api/v2/credential_input_sources/1/",
            "related": {
                "created_by": "/api/v2/users/1/",
                "modified_by": "/api/v2/users/1/",
                "source_credential": "/api/v2/credentials/23/",
                "target_credential": "/api/v2/credentials/22/"
            },
            "summary_fields": {
                "source_credential": {
                    "id": 23,
                    "name": "CyberArk AIM",
                    "description": "",
                    "kind": "aim",
                    "cloud": false,
                    "credential_type_id": 17
                },
                "target_credential": {
                    "id": 22,
                    "name": "awxdns",
                    "description": "",
                    "kind": "ssh",
                    "cloud": false,
                    "credential_type_id": 1
                },
                "created_by": {
                    "id": 1,
                    "username": "admin",
                    "first_name": "",
                    "last_name": ""
                },
                "modified_by": {
                    "id": 1,
                    "username": "admin",
                    "first_name": "",
                    "last_name": ""
                },
                "user_capabilities": {
                    "delete": true
                }
            },
            "created": "2019-10-03T16:14:04.810683Z",
            "modified": "2019-10-03T16:14:04.810696Z",
            "description": "",
            "input_field_name": "username",
            "metadata": {
                "object_query": "Safe=P-HOST-WIN-ADM;Object=awxdns",
                "object_query_format": "Exact"
            },
            "target_credential": 22,
            "source_credential": 23
        }
    ]
}

**Comment by ryanpetrello** [comment]
So you're pulling a value from Cyberark using the query `Safe=P-HOST-WIN-ADM;Object=awxdns`.  Given the behavior you've described, this suggests to me that the query AWX is sending to Cyberark is returning a password value (which is likely a misconfiguration with your query, or the way you've saved the secret in CyberArk).

**Comment by jakemcdermott** [comment]
If I'm following this correctly you'd want to map the credential input to the ssh _password_ (not the username). 

You'd want to specify the `awxdns` username manually by saving it directly to the credential. If you also need the username to be dynamic you'd need to store that as a completely separate "secret" and map it to the username input.

**Comment by ryanpetrello** [comment]
I think @jakemcdermott has guessed at your intent here - you *probably* want to update that credential input source in your screenshot so that `input_field_name` is `password` (not `username`).

**Comment by bamason14** [comment]
When I call the CyberArk api directly this is the output:

{"Content":"xxxpasswordxxx","PolicyID":"P-COL-WIN-SRV","Name":"awxdns","SequenceID":"14","UserName":"awxdns","CPMStatus":"success","Folder":"Root","Safe":"P-HOST-WIN-ADM","Address":"domainname","LastSuccessVerification":"1570103186","LogonDomain":"DOMAIN","DeviceType":"Operating System","LastTask":"VerifyTask","RetriesCount":"-1","LastSuccessChange":"1570016787","CreationMethod":"PVWA","PasswordChangeInProcess":"False"}

From what I am understanding from you is that you are expecting it to return the username right after "Content:" and for AWX not to use the UserName attribute?

**Comment by ryanpetrello** [comment]
The AIM plugin pulls its value from the `Content` key in the HTTP response from AIM:

https://github.com/ansible/awx/blob/devel/awx/main/credential_plugins/aim.py#L100

**Comment by bamason14** [comment]
Got it. I was able to make the change you suggested above and it works. The documentation on this was not very in-depth to describe this. I will close this issue.

**Comment by jd2020x** [comment]
Does anyone know how to get this plugin to return username and password within a playbook? 
I am a newbie and I was not sure how to set the credential type and get the playbook to return the data from cyberark.
Really appreciate any help out there.
Thanks
Jd2020
