### ISSUE TITLE
adhoc commands run by container group don't cleanup job pod in k8s/openshift cluster

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#4908]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

This is a known issue of #4189 that will be resolved in follow up PR.

Currently with the feature if you run an `ad_hoc_command` that gets deployed to a ContainerGroup, the job will run in a pod on the cluster but the pod is never cleaned up after the job runs or is canceled.

##### STEPS TO REPRODUCE

1) create a working Container Group
2) Create an organization
3) Assign Container Group to organization as only instance group
4) Create inventory + one host (localhost is fine)
5) launch ad hoc command against host
6) see that job is spawned and runs
7) watch to see pod is never cleaned up

##### EXPECTED RESULTS

Job runs + is cleaned up

##### ACTUAL RESULTS

no clean up of pod

##### ADDITIONAL INFORMATION

This also happens for canceled ad hoc commands

**Comment by ryanpetrello** [comment]
Yep, I can reproduce this.

**Comment by kdelee** [comment]
downstream fix for this is working for me, will close when fix lands in awx/devel

**Comment by kdelee** [comment]
https://github.com/ansible/awx/pull/5047 brought in fixes, closing.
