### ISSUE TITLE
docker-compose installation

### ISSUE THREAD

**Issue by artemkamolodets** [ansible/awx#491]
##### ISSUE TYPE

 - Feature Idea
 

##### COMPONENT NAME

 - Installer

##### SUMMARY

Hello. 
At now, there is a several containers after installation (with docker method). Is it possible, to group them with docker-compose?

**Comment by matburt** [comment]
Go for it.

**Comment by muayyad-alsadi** [comment]
this was closed by mistake.

here is a sample [docker-compose.yml](https://github.com/geerlingguy/awx-container/blob/master/docker-compose.yml)

please include it and change images to official awx images on docker hub.

**Comment by ewjoachim** [comment]
I'm starting to work on a PR for this.

**Comment by ewjoachim** [comment]
@artemkamolodets @muayyad-alsadi While waiting for an official approval, feel free to give a go to the pull request referenced above (#856) and tell me if you see something wrong :)

**Comment by muayyad-alsadi** [comment]
no, it's does not look like what I wanted.
I want a section with a simple `curl` and simple `docker-compose up`

I'll continue on your PR.

**Comment by muayyad-alsadi** [comment]
@ewjoachim  please merge my PR, then add a similar yaml for openshift

```oc create -f awx.yml```

**Comment by ewjoachim** [comment]
But... Your suggestion completely bypasses all the idea that the installation parameters are defined in the inventory .ini file, which is the way of the 2 other existing installation method, why create more special cases when we can achieve a reasonable solution with the general case ?

**Comment by muayyad-alsadi** [comment]
Because I want to reduce entry barrier and learning curve for people who are curious and want to test it in an all-in-one non production setup without cloning such large project.

A kind note that this is a quick n dirty all in one setup with a pointer to the production setup.

**Comment by ewjoachim** [comment]
I really think this belongs to another ticket. This ticket is for a new installation method, not a trial. I'm not saying it's not a good idea, but it's a different idea.

And while I see the appeal of having a quick start solution, I'd be more confident to make it secure by default. How about a "curl && ansible-playbook" that would essentially do the same as your "curl && docker-compose", but in a saner way ?

This being said, I **really** think it should be done in another ticket / PR.
