### ISSUE TITLE
Need to be able to define controller for container groups

### ISSUE THREAD

**Issue by one-t** [ansible/awx#4912]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Related: https://github.com/ansible/awx/issues/4907

Users should be able to choose a controller node/nodes for their container groups- this would cut down on the number of firewall exceptions they'd need to create to allow for containerized execution of jobs.

**Comment by wenottingham** [comment]
Given the way we are splitting control & execution, not sure this makes sense initially. TBD.

**Comment by one-t** [comment]
Agreed, it doesn't make a lot of sense with the architectural direction we're taking now.
