### ISSUE TITLE
Container Group Form Tooltip is out of alignment

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#4940]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Container Group Form Tooltip is out of alignment

##### ENVIRONMENT
* AWX version: 7.0.0

##### STEPS TO REPRODUCE

1. Click tooltip on container group form 'Name'

##### EXPECTED RESULTS

Tooltip aligned to the tooltip icon

##### ACTUAL RESULTS

slightly out of alignment
![Screen Shot 2019-10-08 at 2 45 03 PM](https://user-images.githubusercontent.com/12446869/66424226-3bafd700-e9db-11e9-98bc-38b0673d1d8a.png)

**Comment by fpjrh** [comment]
@unlikelyzero, it would appear to me that the misalignment might be a couple of pixels at most. Can you clarify the exact amount that you expect to see this tooltip realigned?

Thank you!

**Comment by unlikelyzero** [comment]
![Screen Shot 2019-10-09 at 10 07 59 AM](https://user-images.githubusercontent.com/12446869/66488880-b1b84a80-ea7c-11e9-9e92-9776140dd532.png)

@fpjrh this is what it should look like. We wouldn't call out pixels in this class of defect because of how the alignment is calculated

**Comment by fpjrh** [comment]
@unlikelyzero, thank you!

**Comment by AlexSCorey** [comment]
Backing out for now.

**Comment by wenottingham** [comment]
pushing to pf-rewrite
