### ISSUE TITLE
Update template add button to account for workflow options

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4942]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Currently the template add button is hidden/shown based on the options response on `/api/v2/job_templates` _only_.  The button should be shown when the user can create a job template _or_ a workflow job template.  The options in the dropdown should also hidden/shown based on what the user has permission to do.  See this block https://github.com/ansible/awx/blob/devel/awx/ui/client/features/templates/templatesList.controller.js#L54-L56 in the existing application for reference

**Comment by mabashian** [comment]
As part of this work we should add tests to confirm this behavior (see projects/orgs list tests after https://github.com/ansible/awx/pull/4929 merges)

**Comment by mabashian** [comment]
Looks like this got addressed by https://github.com/ansible/awx/commit/25105d813d6ff313875c17f1cbda1998f83bdb3a.  Moving this over to needs_test.

**Comment by appuk** [comment]
The Tests are almost ready to merge, and are green, hence closing the issue.
