### ISSUE TITLE
System Auditor is unable to view Container Groups

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#4943]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
System Auditor is unable to view Container Groups

##### ENVIRONMENT
* AWX version: 7.0.0

##### STEPS TO REPRODUCE
1. Create Container Group
2. Log in as System Auditor
3. Attempt to view a container group

##### EXPECTED RESULTS
Able to view container group like an instance group

##### ACTUAL RESULTS
Unable to view container group

##### ADDITIONAL INFORMATION
![Screen Shot 2019-10-08 at 5 32 17 PM](https://user-images.githubusercontent.com/12446869/66435218-5c375b80-e9f2-11e9-8abb-0be7ba30ad30.png)

**Comment by AlexSCorey** [comment]
After investigating this a little bit it looks like a SystemAuditor does not have `OPTIONS.actions.PUT.pod_spec_override.default` coming back from the api,  which makes sense because this user can't update anything.

**Comment by rebeccahhh** [comment]
SystemAuditors only have GET access (as mentioned in previous comment) and we want to keep that access level from the API side.

**Comment by dsesami** [comment]
System auditors can view the container groups and instance groups normally now. Also, they only have read-only access.
