### ISSUE TITLE
Responsivity issues on WFJT Job Results Details View

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#4945]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Responsivity issues on WFJT Job Results Details View

##### ENVIRONMENT
* AWX version: 7.0.0

##### STEPS TO REPRODUCE
1. View the WFJT Job Results Page at a narrow width

##### EXPECTED RESULTS
1. Job Results window to expand horizontally

##### ACTUAL RESULTS
1. Squishy

##### ADDITIONAL INFORMATION
![Screen Shot 2019-10-08 at 6 08 27 PM](https://user-images.githubusercontent.com/12446869/66437408-a66f0b80-e9f7-11e9-8731-463ec0736ebc.png)

**Comment by dsesami** [comment]
responsiveness on details page is significantly improved -- tried a few different size workflows to ensure that everything ran correctly and looks normal.
