### ISSUE TITLE
Adjust spacing between detail list columns

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#4947]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Currently the detail list grid spacing is set to 20px. Per @trahman73, we should increase the detail list label + value column gap to 40px, and keep the spacing between the detail label and detail value at 20px. See image below for clarification. 

This style change should affect every Detail view: 
* Job Details
* Job Template Details
* Organization Details
* Project Details
* etc. 

<img width="1492" alt="Screen Shot 2019-10-09 at 12 38 03 AM" src="https://user-images.githubusercontent.com/15881645/66452472-958dbc80-ea2e-11e9-8fab-718df4fbfe3d.png">

##### Expected Results
* Spacing between detail list columns (label-value pair) should be 40px
* Spacing between detail label and detail value should be 20px

##### Actual Results
* 20px grid spacing between detail list columns (label-value pair), detail labels, and detail values

**Comment by unlikelyzero** [comment]
@marshmalien is this still an issue?

**Comment by marshmalien** [comment]
> Spacing between detail list columns (label-value pair) should be 40px

@unlikelyzero We haven't addressed this yet.

**Comment by unlikelyzero** [comment]
@marshmalien i think this is no longer an issue and we have several pages covered in the visual tests
