### ISSUE TITLE
Hide max hosts field on org form

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4950]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Hide max hosts field on Organization Add and Edit Form when installation type is AWX.  Field only applies to licensed installations (i.e. Tower).

<img width="1467" alt="Screen Shot 2019-10-09 at 9 59 09 AM" src="https://user-images.githubusercontent.com/9889020/66488178-854ffe80-ea7b-11e9-8fe5-062f0bdf292e.png">

**Comment by mabashian** [comment]
Should also be hidden on the Org Details view:

<img width="1415" alt="Screen Shot 2019-10-09 at 10 26 52 AM" src="https://user-images.githubusercontent.com/9889020/66490551-550a5f00-ea7f-11e9-867d-c4330ee5637c.png">

**Comment by unlikelyzero** [comment]
Note: this will need to be covered in a closed source test

**Comment by unlikelyzero** [comment]
covered in 5673
