### ISSUE TITLE
Org team list links should point to team details

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4951]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Currently points to `/#/api/v2/teams/:id`

<img width="655" alt="Screen Shot 2019-10-09 at 10 06 57 AM" src="https://user-images.githubusercontent.com/9889020/66488861-abc26980-ea7c-11e9-9447-4f4a43eec10d.png">

**Comment by dsesami** [comment]
Link works normally. Orgs with no teams also work normally.
