### ISSUE TITLE
Org access user links should point to user details

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4952]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Currently pointing to `/#/api/v2/users/:id`

<img width="702" alt="Screen Shot 2019-10-09 at 10 12 21 AM" src="https://user-images.githubusercontent.com/9889020/66489264-4f137e80-ea7d-11e9-9672-5d9160805e7b.png">

**Comment by mabashian** [comment]
Looks like this got fixed a while back.  Moving over to needs_test.

**Comment by dsesami** [comment]
Tried this with a few users and orgs. works great. :+1:
