### ISSUE TITLE
Link to instance group from org details when present

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4953]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
<img width="1481" alt="Screen Shot 2019-10-09 at 10 17 06 AM" src="https://user-images.githubusercontent.com/9889020/66489703-07d9bd80-ea7e-11e9-8e2d-c210560f30b3.png">

We don't currently do this in the existing application but with this new Details pattern I'm wondering if we should link out to all linkable resources like Instance Groups.

**Comment by mabashian** [comment]
Ping @trahman73 @wenottingham - thoughts on this pattern?  If we display related resources (instance groups, credentials, projects, etc) in the Details view for a particular item should we always provide a link to that resource?  It seems like it could be an easy win.

**Comment by trahman73** [comment]
@mabashian Agreed, we should link to resources whenever possible. For text, we would just use a standard text link and for tags, we can just make them clickable without changing their appearance.

**Comment by mabashian** [comment]
I'm not sure if we have an issue tracking similar work for things like credentials on the JT details view but if so this work can be combined as I'm sure it's very similar.

**Comment by tiagodread** [comment]
Fixed!
