### ISSUE TITLE
when passing a blank extra-var: "Error: failed to parse some of the extra variables.

### ISSUE THREAD

**Issue by erics302** [ansible/awx#4955]
In ansible-playbook, I can pass a blank variable via cli. I am attempting the same when launching a job_template with tower-cli but get an error.

awxkit==7.0.0
```
~$ awx-cli job launch -J my_template_name --extra-vars="foo=''"
Error: failed to parse some of the extra variables.
variables:
foo=''
```

**Comment by ryanpetrello** [comment]
@erics302 the `tower-cli` tool is no longer actively maintained (and isn't part of AWX).  You may want to take a look at the official AWX CLI instead:

https://github.com/ansible/awx/tree/devel/awxkit/awxkit/cli
