### ISSUE TITLE
JT Access tab

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4958]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Hook up JT Access related tab.  This tab shows who has roles on the JT and gives a user with proper permissions the ability to add/remove roles.

**Comment by mabashian** [comment]
The access tab has been hooked up in recent days.  Moving this over to needs_test.

**Comment by dsesami** [comment]
Some issues:

- Adding a team to JT access does not work. Teams cannot be added in any form through the wizard.
- Deleting a user's permissions in the access tab when they only have 1 permission does not appear to work. There is no `x` button or otherwise to revoke access.

**Comment by mabashian** [comment]
@dsesami 

> Adding a team to JT access does not work. Teams cannot be added in any form through the wizard.

Just tried this out on latest devel and you can assign team-level permissions via the wizard.  Not sure if that was added after your comment or what (too long ago to remember).  There is a caveat though - the list won't show any changes unless there are users _in_ the team.  The access list ultimately shows users with roles.

> Deleting a user's permissions in the access tab when they only have 1 permission does not appear to work. There is no x button or otherwise to revoke access.

Also tested this out and it seems like it's working to me.

So maybe this is ready to be re-tested?

**Comment by mabashian** [comment]
Yea I'm pretty certain this is working as expected.  Moving back to needs_test.

**Comment by unlikelyzero** [comment]
@akus062381 will be taking this ticket for testing.
1. Find every other example of Access Tab tests and list and compare them. If any other Resources are missing acces tab tests, list them.
2. Find other examples to "borrow from" Access tab testsuites like Org or Project Access.
3. If no test stubs for JT Access exist, add them based on the access tab tests from Org or Project
4. Execute the stubs manually by hand
5. If bugs are found, create new issues for those bugs

**Comment by unlikelyzero** [comment]
@akus062381 this happened at some point without QE https://github.com/ansible/awx/issues/7595 . While looking for Access list stubs note that you'll run into examples of Teams and Users tabs. They should all be merged into Access

**Comment by akus062381** [comment]
1. There is no record of this being tested and there are no stubs.
2. We are missing access tab links for notifications and projects as well.
3. Some of the best examples so far: tabs.spec for Organizations. The context is Access Tab - List Operations. ALSO- Workflows test suite- see the tabs.spec file.

**Comment by akus062381** [comment]
PR: https://github.com/ansible/tower-qa/pull/6041

**Comment by akus062381** [comment]
All set
