### ISSUE TITLE
JT Schedules List

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4959]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
There's a lot of overlap between this list and https://github.com/ansible/awx/issues/5857.  If we decide to include the Type column (which will always be Playbook Run in this case) then the two lists become even more similar.

The list is populated by interacting with `/api/v2/job_templates/:id/schedules`. 

The list should have 5 (maybe 4) columns:

1) Name (shows the name of the schedule and should link to `/#/job_templates/:job_template_id/schedules/:schedule_id/details`).
2) Type (Mockups show this column but it will always be Playbook Run so I think we can argue that it should be omitted).
3) Next Run (Shows the timestamp of the next run)
4) On/Off Toggle (Allows the user to toggle the schedule on and off - rbac protected)
5) Edit Button (See column 1.  This should link to `/#/job_templates/:job_template_id/schedules/:schedule_id/edit` - also rbac protected).

Deletion is also supported given that rbac allows it.

An add button should be present for users that have the ability to add.

Sortable keys:

1) Name (name)
3) Next Run (next_run)

Searchable keys:

Should probably match the sortable keys for now - use your discretion.

Here's a link to the mockups: https://tower-mockups.testing.ansible.com/patternfly/templates/templates-schedules/

**Comment by mabashian** [comment]
This issue and https://github.com/ansible/awx/issues/5857 should probably be worked on by the same individual.

**Comment by jlmitch5** [comment]
The list has also been added to the WFJT, JT and Project tabs.

**Comment by dsesami** [comment]
List pagination, toggles, and information all appears to work.

I do have one request: could something be done about the responsiveness here of the date/time of next runs:
![Screenshot from 2020-03-16 15-21-15](https://user-images.githubusercontent.com/19942822/76792729-0b464300-679a-11ea-8764-ae52a4db02d4.png)

**Comment by dsesami** [comment]
moving back to needs_devel after speaking with @jlmitch5 . the above comment is the last remaining issue I have with the feature, so once that's wrapped up I'll close it out.

**Comment by dsesami** [comment]
wrapping on names is also broken (long names go off the screen), but I think this is an issue with lists in general. @appuk is filing a related bug

**Comment by dsesami** [comment]
Closing this out; the wrapping issue has been addressed with https://github.com/ansible/awx/pull/6348
