### ISSUE TITLE
Add Enable Webhook & corresponding fields to JT form

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4962]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Existing JT form:

<img width="1481" alt="Screen Shot 2019-10-09 at 11 00 38 AM" src="https://user-images.githubusercontent.com/9889020/66493453-19be5f00-ea84-11e9-84b1-2597c29dffef.png">

**Comment by dsesami** [comment]
webhooks are now added to the form and are present in details as of the merging and approval of #6808 . nice work on this.
