### ISSUE TITLE
awx-cli - when passing a blank extra-var: "Error: failed to parse some of the extra variables.

### ISSUE THREAD

**Issue by erics302** [ansible/awx#4963]
In ansible-playbook, I can pass a blank variable via cli. I am attempting the same when launching a job_template with awx-cli but get an error.
I mistakenly pasted output from tower-cli in issue #4955, but the behavior exists identically in awx-cli as well. 

awxkit==7.0.0

~$ awx-cli job launch -J my_template_name --extra-vars="foo=''"
Error: failed to parse some of the extra variables.
variables:
foo=''

**Comment by ryanpetrello** [comment]
`awx-cli` is just an alias for `tower-cli` (you're still using the deprecated tool):

https://github.com/ansible/tower-cli/blob/master/setup.py#L165

Please follow the instructions at https://github.com/ansible/awx/issues/4955
