### ISSUE TITLE
JT save button enabled even when required fields empty

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4964]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
<img width="1449" alt="Screen Shot 2019-10-09 at 11 07 37 AM" src="https://user-images.githubusercontent.com/9889020/66494039-06f85a00-ea85-11e9-88be-d8cba6934e28.png">

**Comment by keithjgrant** [comment]
Are we sure we want to disable the submit button? With the current behavior, clicking it gives feedback to the user about which fields are invalid/missing. If it's disabled, it may not be immediately obvious why it's disabled.

**Comment by keithjgrant** [comment]
After some discussion, we've decided to keep the existing functionality as is. Closing this issue.

@trahman73:
> Lets go with the PF flow above:+1::skin-tone-2: Enabled at all times with validation shown on click of Save
