### ISSUE TITLE
Support prompt on launch options in JT form

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4967]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Example:

<img width="470" alt="Screen Shot 2019-10-09 at 11 12 55 AM" src="https://user-images.githubusercontent.com/9889020/66494522-cb11c480-ea85-11e9-9f86-5fc845f3836c.png">

See mockups for more examples: https://tower-mockups.testing.ansible.com/patternfly/templates/templates-add/

Currently supported promptable fields:
ask_scm_branch_on_launch
ask_diff_mode_on_launch
ask_variables_on_launch
ask_limit_on_launch
ask_tags_on_launch
ask_skip_tags_on_launch
ask_job_type_on_launch
ask_verbosity_on_launch
ask_inventory_on_launch
ask_credential_on_launch

**Comment by mabashian** [comment]
This issue should probably be worked on in conjunction with #5819

**Comment by appuk** [comment]
not able to test this until this issue https://github.com/ansible/awx/issues/6608 is resolved

**Comment by appuk** [comment]
Verified the prompt on launch checkbox on the JT Form and verified the new validation for inventory.
Everything works as expected, hence closing the issue
