### ISSUE TITLE
Add copy icon and functionality next to commonly copied fields

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4972]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
This would require some thought but for places where users copy text out of fields we could help them out by providing a shortcut (copy icon) next to the field which would copy the value to their clipboard.

https://www.patternfly.org/v4/documentation/react/components/clipboardcopy/

**Comment by nixocio** [comment]
We've already added the Copy button in a few different places in the new UI. If we miss something, let's focus on a specific problem - less broad. So I will close this issue.
