### ISSUE TITLE
adjust UI_LIVE_UPDATES_ENABLED to still allow job panel updates

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#4983]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

In an extremely busy environment, sometimes a user will set UI_LIVE_UPDATES_ENABLED to False to avoid extra REST requests and load. However, in general, we still want live updates to the job status and output panel, even if this is set to false.

**Comment by wenottingham** [comment]
This can be addressed in the new UI framework.

**Comment by wenottingham** [comment]
I think with the changes already made this is baked enough. Closing.

**Comment by wenottingham** [comment]
Reopening for testing.

**Comment by unlikelyzero** [comment]
@mabashian please adjust labels

**Comment by wenottingham** [comment]
Actually, closing this - we changed this behavior in the prior release.
