### ISSUE TITLE
Idea: Add delete button to all deletable details views

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4984]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
We already have this on the job details but I actually think it's a great idea on the details view for other resources.  Now that we don't show the list under the form/details a user would need to navigate back to the list to delete a resource that they've inspected.  Upon successful delete we should navigate the user back to the list view for that particular resource type.  Mockups will be adjusted.

**Comment by AlexSCorey** [comment]
Removing myself to reflect reality

**Comment by marshmalien** [comment]
List of current Detail views: 
- [x] Credential
- [x] Host
- [x] Inventory
- [x] InventoryGroup
- [x] Job
- [x] JobTemplate
- [x] Organization
- [x] Project
- [x] Team
- [x] User

**Comment by unlikelyzero** [comment]
@dsesami to review this afternoon

**Comment by dsesami** [comment]
Reviewed all delete buttons listed. all work as desired. :tada:
