### ISSUE TITLE
Add upper limits to memory and cpu for pods for Kubernetes deployments

### ISSUE THREAD

**Issue by shafi-khan** [ansible/awx#4993]
##### ISSUE TYPE
 - Presently, when following the documentation (https://github.com/ansible/awx/blob/devel/INSTALL.md#Kubernetes) to set up AWX in Kubernetes, there is a possibility of misconfiguration with respect to memory and cpu limits for the awx pods

##### SUMMARY

- According to the documentation linked above (https://github.com/ansible/awx/blob/devel/INSTALL.md#Kubernetes), to set up AWX in Kubernetes, one can quickly clone the repo and run the ansible installer playbook. 
- However,  looking at  https://github.com/ansible/awx/blob/devel/installer/roles/kubernetes/defaults/main.yml, it appears that while there are default memory and cpu requests set for the individual pods, there aren't any limits set by default.
This could lead to a potential problem where a user using a Kubernetes namespace with a  LimitRange object(https://kubernetes.io/docs/concepts/policy/limit-range/)  could see a 'Specified memory/cpu request greater than limit' error, because the LimitRange limit gets used for deployments with  no explicit limit configuration. In this case, even if the limitrange default limit values happen to be lower than the awx configured default requests ( such as web_mem_request, web_cpu_request, etc)  even if the actual max limit is higher. An example of a LimitRange spec is referenced below:

----
#### LimitRange
apiVersion: v1
kind: LimitRange
metadata:
  namespace: some-namespace
  name: default-limits-per-container
spec:
  limits:
  - max:
      cpu: "1.5"
      memory: "6Gi"

    min:
      cpu: "50m"
      memory: "20Mi"

    default:
      cpu: "250m"
      memory: "512Mi"

    defaultRequest:
      cpu: "50m"
      memory: "256Mi"

    type: Container
---

In the example above, if the values for awx containers (specified in https://github.com/ansible/awx/blob/devel/installer/roles/kubernetes/defaults/main.yml )happen to be the following.

web_mem_request: 1
web_cpu_request: 500

task_mem_request: 2
task_cpu_request: 1500

rabbitmq_mem_request: 2
rabbitmq_cpu_request: 500

memcached_mem_request: 1
memcached_cpu_request: 500

Because there are no upper limits set,  the LimitRange object will set the default upperlimits which happen to be lower than the explicit request values and can.
While the user can mitigate this quickly by adding the variables such as web_mem_limit and web_cpu_limit , it would be helpful if these were included in the default/main.yml configuration.

**Comment by gamuniz** [comment]
This method of installation is now handled via awx-operator. It also allows for configuration of both requests and limits. Closing this issue
