### ISSUE TITLE
Problem adding my personal git repository as a SCM in AWX

### ISSUE THREAD

**Issue by ervis-s** [ansible/awx#4996]
Hello Guys,
I have created a public Git repository: https://github.com/ervis-s/Ansible-Repository just as a source code management for my AWX.
The problem that I encounter is that when I create a project (in AWX) and afterwards I upload this project to a template I cannot see the playbook inside my repository.
However it works fine for other repositories like for example: https://github.com/ansible/ansible-tower-samples

Can anyone help me?
Thank you

**Comment by ryanpetrello** [comment]
Hey @ervis-s,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
