### ISSUE TITLE
maintenance page / announcement

### ISSUE THREAD

**Issue by swiedernix** [ansible/awx#4997]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
I'd like to add annoucements (eg. planned downtimes for maintenance, updates, current limitations, .... ) to the awx login page to inform our users.

**Comment by jakemcdermott** [comment]
There's a `CUSTOM LOGIN INFO` field in settings->ui that should let you do this:

![Screenshot from 2019-10-10 10-10-50](https://user-images.githubusercontent.com/9753817/66576873-6ec2a980-eb46-11e9-972f-4d1a6999731a.png)
