### ISSUE TITLE
ad-hoc commands not using custom ansible.cfg

### ISSUE THREAD

**Issue by elarrarte-d** [ansible/awx#4999]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX ignores custom ansible.cfg in ad-hoc commands

##### ENVIRONMENT
* AWX version: 7.0.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.4
* Operating System: Ubuntu 18.04
* Web Browser: -

##### STEPS TO REPRODUCE

Select a host or group from the inventory, [run commands]

##### EXPECTED RESULTS

ansible.cfg with custom parameters located at the root of the github project is used to execute ad-hoc commands; works well with job templates (ansible-playbook)

##### ACTUAL RESULTS

jobs run without using custom ansible.cfg:
deprecation_warnings=False

##### ADDITIONAL INFORMATION

> Identity added: /tmp/awx_1165_po60pibf/artifacts/1165/ssh_key_data (/tmp/awx_1165_po60pibf/artifacts/1165/ssh_key_data)
> [DEPRECATION WARNING]: Distribution Ubuntu 18.04 on host nagios-security-03 
> should use /usr/bin/python3, but is using /usr/bin/python for backward 
> compatibility with prior Ansible releases. A future Ansible release will 
> default to using the discovered platform python for this host. See https://docs
> .ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for 
> more information. This feature will be removed in version 2.12. Deprecation 
> warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
> nagios-security-03 | SUCCESS => {
>     "ansible_facts": {
>         "discovered_interpreter_python": "/usr/bin/python"
>     }, 
>     "changed": false, 
>     "ping": "pong"
> }

**Comment by AlanCoding** [comment]
> ansible.cfg with custom parameters located at the root of the github project is used to execute ad-hoc commands

ad hoc commands have no project associated with them. Commands are executed against the inventory. What project are you thinking of? For an SCM inventory or something?

**Comment by elarrarte-d** [comment]
OK, from the documentation:
https://docs.ansible.com/ansible-tower/latest/html/administration/tipsandtricks.html

> While Ansible does not require a configuration file, OS packages often include a default one in /etc/ansible/ansible.cfg for possible customization. In order to use a custom ansible.cfg file, place it at the root of your project. Ansible Tower runs ansible-playbook from the root of the project directory, where it will then find the custom ansible.cfg file. An ansible.cfg anywhere else in the project will be ignored.

I 've misread that it 's only applied to ansible-playbook command (job templates).

So, then, is there any way of using a custom ansible.cfg for ad-hoc commands?

Thanks!

**Comment by AlanCoding** [comment]
It's hard to apply a config specific to the inventory, or specific to that one ad hoc command (as in, I have no way to do this).

To set something globally, you can use the environment variables to set things. In the UI:

![Screen Shot 2019-10-16 at 1 21 16 PM](https://user-images.githubusercontent.com/1385596/66942842-f06b7900-f017-11e9-9d87-9fbcad22815f.png)

![Screen Shot 2019-10-16 at 1 21 34 PM](https://user-images.githubusercontent.com/1385596/66942846-f4979680-f017-11e9-8233-4d3279ad08c2.png)

for `deprecation_warnings`, go find it in

https://github.com/ansible/ansible/blob/4c2b137728d2b1cb085d5a9749d773a2093eaa62/lib/ansible/config/base.yml#L1226

The env var is `ANSIBLE_DEPRECATION_WARNINGS`. So you can put that in the data there. The syntax that needs to be added in the brackets, IIRC, looks like `"ANSIBLE_DEPRECATION_WARNINGS": "False"`.

**Comment by ryanpetrello** [comment]
@AlanCoding @elarrarte-despegar this is venturing into the realm of "how to use AWX" conversation (and this tracker is what we use to track bugs and enhancements), so I'm going to go ahead and close this.  Feel free to continue conversation here or on our mailing list.

**Comment by elarrarte-d** [comment]
Thanks!
