### ISSUE TITLE
Allow custom Ansible project structures

### ISSUE THREAD

**Issue by Timoses** [ansible/awx#5000]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Since Ansible offers a lot of flexibility in the way that projects can be set up, it would be great if the `project_update.yml` would be exposed for user customization.

EDIT: As [stated](https://github.com/ansible/awx/issues/5000#issuecomment-541098848) `project_update.yml` is not the only place affected by this feature request.

Some examples why this may be required:
* We use an `Ansible` playbook which installs Ansible in various flavours (CLI, Dev workplace, AWX, ...). The `ansible.cfg` for each setup differs. Thus for a project to be set up it is required to run the `Ansible` play or at least use the Ansible `template` module to place the ansible.cfg in the right place (in case of AWX in the project root path).
* `requirements.yml` may not be set up as required by AWX currently. In our case we have a requirements.yml in each `plays/<play>/requirements.yml`. ansible-galaxy should be executed to place the required roles into `plays/<play>/roles/`.
* Custom plugin usage (mainly driven through ansible.cfg configuration)
* ...

As it is currently, AWX forces users to (some examples):
* place roles into `roles/requirements.yml`
* no bootstrapping options to e.g. pull content, modules, ... (Addition of collections probably does help at this point)

There are so many ways to use Ansible. Forcing users to one way only disrupts usability.

Currently, we will probably move towards overriding the `project_update.yml` in `/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/playbooks/project_update.yml` of the `awx_task` container.
EDIT: Unfortunately `awx/main/tasks.py` contains further logic which makes above approach unfeasible.

Any other way to achieve this? Any documentation on this I have missed?

**Comment by Timoses** [comment]
I just found out that projects are copied (checked out with git) to `/tmp` directory and only the role requirements from `roles/requirements.yml` are used in `awx/main/tasks.py` (rendering all the `plays/<play>/requirements.yml` files as ignored).

This makes AWX quite unusable with custom Ansible project structures. Any way to circumvent this and simply "copy" the project path to the job temporary directory?

**Comment by wenottingham** [comment]
If we start going down the road of managing execution environments, this wouldn't be done by hooking into project_update.yml; it would be done at a higher level.

**Comment by Timoses** [comment]
Thanks @wenottingham . I adjusted the issue title to better reflect the issue at hand.

**Comment by ffirg** [comment]
This is not something we're looking to do now that execution environments are a thing and allow certain customisation that addresses some of the request.
