### ISSUE TITLE
Allow tower_credential to accept a custom credential type

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#5003]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
In the modules in the AWX collection, you can create a custom credential type, but you cannot create a credential of a specified custom credential type. This is a major pain point.

Prior fix attempts:

 - (cherry pick this) https://github.com/ansible/ansible/pull/56692
 - https://github.com/ansible/ansible/pull/54503

Prior issues:

 - https://github.com/ansible/ansible/issues/54493

**Comment by squidboylan** [comment]
I tested this locally by following the instructions at https://github.com/ansible/tower/blob/release_3.6.0/awx_collection/README.md to run the awx_collection tests in the docker container. Everything passed
