### ISSUE TITLE
Different result from ansible command line and AWX template

### ISSUE THREAD

**Issue by ervis-s** [ansible/awx#5005]
Hello everyone,

I am getting a different result when I execute a play in AWX from ansible command line.

Actually I am trying to clone a repository with git module in local. I attach the playbook image.
![Capture](https://user-images.githubusercontent.com/41151072/66660871-44f0ac00-ec46-11e9-90a8-2c72563506f2.JPG)

In AWX when I launch the template it seems all fine, but doesn't clone anything, instead when I use ansible-playbook play.yml does the work.

Can anyone help find the problem, if you want I can provide further information. 

Thank you

**Comment by wenottingham** [comment]
This repo is for bugs in AWX; this sounds like a configuration issue that is best discussed on the mailing list or the IRC channel.

I suspect it's to do with how each playbook run uses its own /tmp directory.
