### ISSUE TITLE
Add Prompt on Launch for Network Credential passwords and private key passphrase

### ISSUE THREAD

**Issue by IshwarKanse** [ansible/awx#5007]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Network Credential currently doesn't have Prompt on Launch option for Password, Authorize Password and Private Key Passphrase. 

![Screenshot from 2019-10-14 08-41-13](https://user-images.githubusercontent.com/10349173/66727856-59f45780-ee5f-11e9-8b5d-34b55a694cfb.png)

**Comment by wenottingham** [comment]
network creds are not the preferred mechanism in the current modules, so this is unlikely to change.
