### ISSUE TITLE
Workflow Job Template - send inventory and limit in API call

### ISSUE THREAD

**Issue by jleach8** [ansible/awx#501]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Currently there is no way (that I can find) to add inventory and limit to an API call (or via the UI) when launching a workflow job template. Regular job templates include this functionality. 

##### ENVIRONMENT

* AWX version: 1.0.1.50
* AWX install method: docker
* Ansible version:  2.4.0
* Operating System: Linux
* Web Browser: Chrome

**Comment by wenottingham** [comment]
this is #169
