### ISSUE TITLE
RFE: Make easier to find which job template a schedule is related to

### ISSUE THREAD

**Issue by elyezer** [ansible/awx#5012]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Can't easily find from which workflow job template or job template a schedule is when multiple schedules exist with the same name. See the screenshot below:

![Screenshot from 2019-10-14 16-10-44](https://user-images.githubusercontent.com/48132/66780001-b9715800-ee9d-11e9-8102-b03a843c8954.png)

The `Every other minute` schedule exist for both workflow job template 1 and workflow job template 2 but it is hard to tell from which one each schedule is.

##### ENVIRONMENT
* AWX version: 7.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.1
* Operating System: Fedora 30
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Create one job template and add an schedule named `My Schedule`
2. Create another job template and add an schedule named `My Schedule`
3. Navigate to the Schedules page 

##### EXPECTED RESULTS

To have a way to differentiate an schedule to each other based on the job template or workflow job template it is related to.

##### ACTUAL RESULTS

Can't figure out which is the related workflow job template or job template a schedule is related to.

**Comment by elyezer** [comment]
After a second thought this is more like an enhancement rather than a bug

**Comment by wenottingham** [comment]
This should be looked at for the new UI.

**Comment by mabashian** [comment]
Yea, to achieve this we'd need to add the name of the parent resource (JT/WFJT/PROJ/INV SRC) and probably a link to that resource in the list row.  Real estate will be the issue.  Here's what schedules currently look like in the new UI:

<img width="1446" alt="Screen Shot 2020-03-25 at 2 44 31 PM" src="https://user-images.githubusercontent.com/9889020/77573545-340bbe00-6ea7-11ea-9dca-7bf758acafd6.png">

Perhaps we could replace the "type" column with a link to the parent resource if available and move the "type" to a badge next to the schedule name?

**Comment by mabashian** [comment]
This won't help with the list view but we could also add the UJT name and a link to it in the schedule details.
