### ISSUE TITLE
Limit in template doest work with dynamic inventory

### ISSUE THREAD

**Issue by dominiquearpin** [ansible/awx#5021]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When I use a dynamic inventory, the template limit doesnt work correctly.

If I use a static inventory, everything is working fine

##### ENVIRONMENT
* AWX version: 7.0.0.599-1.el7 
* AWX install method: rpm from mrmeee
* Ansible version:  
* Operating System: CentOS
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Use a dynamic inventory in a template and use a limit (select a group)

##### EXPECTED RESULTS

Be able to retrieve facts with a dynamic inventory.

##### ACTUAL RESULTS

ansible-playbook 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible
  executable location = /opt/rh/rh-python36/root/bin/ansible-playbook
  python version = 3.6.3 (default, May 31 2019, 13:05:43) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
SSH password: 
setting up inventory plugins
host_list declined parsing /tmp/awx_4014_4mxv86b3/tmpztve1_ga as it did not pass it's verify_file() method
Parsed /tmp/awx_4014_4mxv86b3/tmpztve1_ga inventory source with script plugin
Loading callback plugin awx_display of type stdout, v2.0 from /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/callbacks/awx_display.py

PLAYBOOK: main.yml *************************************************************
Positional arguments: main.yml
verbosity: 5
ask_pass: True
remote_user: my_user
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/tmp/awx_4014_4mxv86b3/tmpztve1_ga',)
subset: cmk
extra_vars: ('@/tmp/awx_4014_4mxv86b3/env/extravars',)
forks: 22
1 plays in main.yml

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
task path: /tmp/awx_4014_4mxv86b3/project/main.yml:2
fatal: [server01.example.com]: FAILED! => {
    "msg": "the connection plugin '' was not found"
}
fatal: [server02.example.com]: FAILED! => {
    "msg": "the connection plugin '' was not found"
}

PLAY RECAP *********************************************************************
server01.example.com : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
server02.example.com : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by shanemcd** [comment]
Sounds like a bug with the RPM you're using, which isn't something we support. If you can reproduce in one of our supported environments please let us know.
