### ISSUE TITLE
awx-cli is missing the notification_template messages argument

### ISSUE THREAD

**Issue by idelsink** [ansible/awx#5027]
##### ISSUE TYPE
Add the ability to configure the custom messages using the awx-cli tool. (This should then be reflected in the ansible tower_notification module.

Example of the to be configured fields:
```json
"messages": {
    "started": {
        "message": "Custom started message: #{{ job.id }}",
        "body": null
    },
    "success": {
        "message": "Custom success message: #{{ job.id }}",
        "body": null
    },
    "error": {
        "message": "Custom error message: #{{ job.id }}",
        "body": null
    }
}
```

**Comment by ryanpetrello** [comment]
@idelsink how are you using it (it works for me):

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/214912/67009036-c0c07d80-f0b8-11e9-91a3-e1ef4ac2534f.png">

```shell
$ awx notification_templates create --name "Testing 123" --organization Default --notification_type slack --messages '{"success": {"message": "It worked!"}}' --notification_configuration '{"token": "abc123", "channels": ["#testing123"]}'
```



Please try with the latest available version of awx.

**Comment by idelsink** [comment]
Ah I see the issue. I've been using the `awx-cli` interface but this was not the interface I thought it was. This was an alias for the `tower-cli` command from the `ansible-tower-cli` package.

**Comment by idelsink** [comment]
However, should another issue be opened for the `messages` option in the `tower_notification` module?

**Comment by ryanpetrello** [comment]
@idelsink yep, go for it.  You should know that we're currently in the process of moving the Tower modules into an official collection instead, so we're a bit behind on feature enhancements like this one.

**Comment by idelsink** [comment]
Should I make it in the ansible or the awx repo?

**Comment by ryanpetrello** [comment]
@idelsink this repo - thanks.  The new AWX collection lives here: https://github.com/ansible/awx/tree/devel/awx_collection

**Comment by idelsink** [comment]
I've created an issue, see issue https://github.com/ansible/awx/issues/5032
