### ISSUE TITLE
Notification Templates UI doesn't always show custom messages

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#5029]
```shell
$ awx notification_templates get 4 -f human --filter name,messages
name        messages
=========== ====================================================
Testing 123 {"success": {"message": "It worked!", "body": null}}
```

<img width="877" alt="image" src="https://user-images.githubusercontent.com/214912/67009254-3fb5b600-f0b9-11e9-914c-184ed81c5e0e.png">

**Comment by ryanpetrello** [comment]
<img width="524" alt="image" src="https://user-images.githubusercontent.com/214912/67009424-9a4f1200-f0b9-11e9-84b6-1daed745f3d0.png">

**Comment by elyezer** [comment]
Steps to verify:

1) Created a new notification and edited the start message
2) Navigated away and back to the notification page and edited the same notification, the `customize message...` section was already expanded. Removed the custom message and edited back to the default value.
3) Navigated away and back to the notification page and edited the same notification, now the `customize message...` section was not expanded.
4) Did the above 3 steps for each of success message and error message. The `customize message...` section was expanded and not expanded as expected.
5) Finally had one, then two and three of the messages (start, success and error) customized and every time the `customize message...` was expanded as expected.

With that we can consider this verified.
