### ISSUE TITLE
Activity stream entry for workflow schedule does not link

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#5030]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
An activity stream entry for updating a schedule does not link to the schedule in the UI. The schedule does exist.

##### ENVIRONMENT
* AWX version: 7.0.0
* AWX install method: docker for mac
* Ansible version:  N/A
* Operating System: Mac
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create a schedule to run a workflow

disable this schedule

see the activity stream recent entry on disabling the schedule

##### EXPECTED RESULTS

Link to the schedule

Or, if not that, a link to the workflow (but really it should be a link to the schedule)

##### ACTUAL RESULTS

no link to the schedule

![Screen Shot 2019-10-17 at 9 39 33 AM](https://user-images.githubusercontent.com/1385596/67014165-5a405d00-f0c2-11e9-8c71-5cfdd8c2218f.png)

##### ADDITIONAL INFORMATION

API data

```json
{
    "id": 9282,
    "type": "activity_stream",
    "url": "/api/v2/activity_stream/9282/",
    "related": {
        "actor": "/api/v2/users/1/",
        "schedule": [
            "/api/v2/schedules/7/"
        ],
        "unified_job_template": "/api/v2/workflow_job_templates/384/"
    },
    "summary_fields": {
        "schedule": [
            {
                "id": 7,
                "name": "EEFDFFDSDFSDFSDSFADFS",
                "description": ""
            }
        ],
        "workflow_job_template": [
            {
                "id": 384,
                "name": "alan schedule WFJT",
                "description": ""
            }
        ],
        "actor": {
            "id": 1,
            "username": "admin",
            "first_name": "",
            "last_name": ""
        }
    },
    "timestamp": "2019-10-17T13:38:59.310450Z",
    "operation": "update",
    "changes": {
        "enabled": [
            true,
            false
        ]
    },
    "object1": "schedule",
    "object2": "",
    "object_association": "",
    "action_node": "awx",
    "object_type": ""
}
```

The schedule URL in the UI

http://localhost:8013/#/templates/workflow_job_template/384/schedules/7?template_search=page_size:20;order_by:name;type:workflow_job_template,job_template&schedule_search=page_size:20;order_by:name

All of the information needed to construct this URL is available from the API response, so this is a UI-only issue. Looks like additional code would be needed.

**Comment by tiagodread** [comment]
Verified this issue and we can safely close this after https://github.com/ansible/awx/pull/9083 merges
