### ISSUE TITLE
RFE: Add IP address to generics logger

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#5031]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Customer would like to be able to view the IP address along with the username of the user logging into Tower.

**Comment by rmauc** [comment]
Thanks for filing this RFE

We need to be able to track users and their source IP for event monitoring. 

We tried to ingest the Nginx access.log but it only logs the IP not the username (RH tell us that it is possible to update the Nginx config to include the headers, but this will also add the password to the log so not usable)

We require the updated generics logger as soon as possible

Many thanks

**Comment by elyezer** [comment]
Steps to verify:

1) Logged in
2) Checked the `/var/log/tower/tower.log`
3) Verified that the entry `2019-10-21 19:55:49,681 INFO     awx.api.generics User admin logged in from NN.NNN.NNN.NN` was present in the log and provided the IP address. (IP address redacted on the pasted log line)

With that we can consider this closed.
