### ISSUE TITLE
RFE: Add a mechanism for listing only normal job runs

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#5033]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Currently, when you attempt to filter job types at the jobs menu in the UI by type, you can use the following searches:

`type:project_update`
`type:inventory_update`
`type:workflow_job`
`type:system_job`
`type:job`

There is currently no search to limit _only_ single job template runs as the `type:job` search displays all workflow, system, and single template runs.

**Comment by AlanCoding** [comment]
Can confirm behavior. The UI issues request

`/api/v2/unified_jobs/?page_size=20&order_by=-finished&not__launch_type=sync&type__icontains=job`

There's definitely a problem with the `__icontains`, but don't know what problems this poses for the broader UI search paradigm.

**Comment by wenottingham** [comment]
This will not be addressed until the search updates that are coming with ui-next.

**Comment by jlmitch5** [comment]
The new jobs' type search will be select-based.  I just confirmed select "job" only shows single-template playbook runs.

![Screen Shot 2020-01-10 at 11 29 43 AM](https://user-images.githubusercontent.com/1342624/72169179-9c64fc00-339c-11ea-8b8c-b0350b8ef818.png)

Note the values here will be updated to the prettified/i18n'd label, there's an outstanding issue in pf that makes us have to keep the value and label the same for these checkbox options.

**Comment by dsesami** [comment]
@jlmitch5 and I conferred on this:

![Screenshot from 2020-04-03 10-51-55](https://user-images.githubusercontent.com/19942822/78375257-8bdab100-759a-11ea-8e41-1edd26258a07.png)

Currently:
- [x] Dropdown name is correct
- [ ] Search filter tag will be changed to match the dropdown name in @jlmitch5 's upcoming search PR (paste here)
- [ ] Column name will be changed in a PR here: https://github.com/ansible/awx/pull/6564

**Comment by unlikelyzero** [comment]
need to verify

**Comment by unlikelyzero** [comment]
This filter exists on _some_ lists, we care about Jobs/ List and Dashboard's Recent Jobs list

**Comment by akus062381** [comment]
see if this was implemented
add stubs if not
manually test
look for testability

**Comment by akus062381** [comment]
- [ ] Verified that this has been implemented in the new UI
- [ ] Stubs have been added- refer to https://github.com/ansible/tower-qa/pull/6123
- [ ] Manual tests performed
- [ ] Testability needs improvement- see https://github.com/ansible/awx/issues/9681
