### ISSUE TITLE
ssl_certificate not used in official container

### ISSUE THREAD

**Issue by craph** [ansible/awx#5036]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The `ssl_certificate` value is defined and uncommented in `inventory`, and it gets used correctly in the docker-compose.yml output file, but the awxweb container's `/etc/nginx/nginx.conf` file has no SSL declaration, resulting in HTTP access only.

##### ENVIRONMENT
* AWX version: 7.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.5
* Operating System: CentOS 7.7.1908
* Web Browser: Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)

##### STEPS TO REPRODUCE

Edit the inventory, removing the comment on ssl_certificate (line 63), and adding the path to the file containing my private key and certificate chain concatenated together. https://github.com/ansible/awx/blob/857683e54845262d197a14ac00227b4dbfbd10c1/installer/inventory#L63

Run ansible-playbook -i inventory install.yml, the installation process succeeds.
I get a functional AWX instance available at port 80. Trying to access the site over HTTPS results in an immediate failure.

##### EXPECTED RESULTS

I expect the awxweb container to get my SSL certificate configuration and serve the site over HTTPS. 

This should be the default behaviour because it's possible to configure it by using templating to override the `nginx.conf` in the official container by adding it in the docker-compose.yml file in the volume part.

**It should be done like that :**

https://github.com/ansible/awx/blob/857683e54845262d197a14ac00227b4dbfbd10c1/installer/roles/local_docker/templates/docker-compose.yml.j2#L22

```yaml
services:

  web:
    image: ansible/awx_web:7.0.0
   ...
    volumes:
      -...
     {% if ssl_certificate is defined %}
      - "{{ docker_compose_dir }}/nginx.conf:/etc/nginx/nginx.conf:ro"
    {% endif %} 
    environment:
      ...
```
and add in `local_docker\tasks\compose.yml` 
https://github.com/ansible/awx/blob/857683e54845262d197a14ac00227b4dbfbd10c1/installer/roles/local_docker/tasks/compose.yml#L7

```yaml
- name: Create Docker Compose Configuration
  template:
    src: "{{ item }}.j2"
    dest: "{{ docker_compose_dir }}/{{ item }}"
    mode: 0600
  with_items:
    - environment.sh
    - credentials.py
    - docker-compose.yml
    - nginx.conf
  register: awx_compose_config
```

##### ACTUAL RESULTS

The awxweb container's `/etc/nginx/nginx.conf` has no SSL declaration. Here is the `nginx.conf` file inside the awxweb container:

```bash
bash-4.2# cat /etc/nginx/nginx.conf
#user awx;

worker_processes  1;

pid        /tmp/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    server_tokens off;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /dev/stdout main;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    sendfile        on;
    #tcp_nopush     on;
    #gzip  on;

    upstream uwsgi {
        server 127.0.0.1:8050;
        }

    upstream daphne {
        server 127.0.0.1:8051;
    }


    server {
                listen 8052 default_server;

        # If you have a domain name, this is where to add it
        server_name _;
        keepalive_timeout 65;

        # HSTS (ngx_http_headers_module is required) (15768000 seconds = 6 months)
        add_header Strict-Transport-Security max-age=15768000;
        add_header Content-Security-Policy "default-src 'self'; connect-src 'self' ws: wss:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' cdn.pendo.io; img-src 'self' data:; report-uri /csp-violation/";
        add_header X-Content-Security-Policy "default-src 'self'; connect-src 'self' ws: wss:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' cdn.pendo.io; img-src 'self' data:; report-uri /csp-violation/";

        # Protect against click-jacking https://www.owasp.org/index.php/Testing_for_Clickjacking_(OTG-CLIENT-009)
        add_header X-Frame-Options "DENY";

        location /nginx_status {
          stub_status on;
          access_log off;
          allow 127.0.0.1;
          deny all;
        }

        location /static/ {
            alias /var/lib/awx/public/static/;
        }

        location /favicon.ico { alias /var/lib/awx/public/static/favicon.ico; }

        location /websocket {
            # Pass request to the upstream alias
            proxy_pass http://daphne;
            # Require http version 1.1 to allow for upgrade requests
            proxy_http_version 1.1;
            # We want proxy_buffering off for proxying to websockets.
            proxy_buffering off;
            # http://en.wikipedia.org/wiki/X-Forwarded-For
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # enable this if you use HTTPS:
            proxy_set_header X-Forwarded-Proto https;
            # pass the Host: header from the client for the sake of redirects
            proxy_set_header Host $http_host;
            # We've set the Host header, so we don't need Nginx to muddle
            # about with redirects
            proxy_redirect off;
            # Depending on the request value, set the Upgrade and
            # connection headers
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }

        location / {
            # Add trailing / if missing
            rewrite ^(.*)$http_host(.*[^/])$ $1$http_host$2/ permanent;
            uwsgi_read_timeout 120s;
            uwsgi_pass uwsgi;
            include /etc/nginx/uwsgi_params;            proxy_set_header X-Forwarded-Port 443;
        }
    }
}

```

**Comment by shanemcd** [comment]
It seems like you have already done most of the hard work. Can you open a PR?

**Comment by craph** [comment]
> It seems like you have already done most of the hard work. Can you open a PR?

Hi @shanemcd, PR open

**Comment by craph** [comment]
Hi @shanemcd ,

How can I solve "awx-detect-schema-change : FAILURE in 9m 28s (non-voting)" about my PR ? is it a blocking point ?

Thank you. 

Best regards,

**Comment by craph** [comment]
Hi @shanemcd,

Please could you give me a feedback about the ansible/gate ? I don't know what I have to do about my PR.

Thank you very much.

Best regards,

**Comment by shanemcd** [comment]
Hello. That is done once it’s approved by a member of our organization. I have been catching up on some other things since returning from vacation. I will take a look, but it may be tomorrow before I can. Cursory review of the code seems fine, but I’d like to test it out first. Thank you much for the PR.

**Comment by craph** [comment]
Hello @shanemcd ,

Thank you very much for your reply. It was with pleasure for the PR 😃 

Have a good day.

**Comment by craph** [comment]
Hi @shanemcd,

When my code will be available in the official awx container image ? 

Where can I found the release plan ?

Thank you very much. 

Best regards.
