### ISSUE TITLE
awx cli schedule command is missing the human friendly job_template option

### ISSUE THREAD

**Issue by idelsink** [ansible/awx#5038]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The awx cli `schedule` is missing the `--job_template` argument. This should take the friendly *name* of the Job template/workflow and not the identifier like `--unified_job_template` does.

Example:
```shell
# For Job Template
awx schedules create --name 'My awesome schedule' --job_template 'My awesome job template' --rrule 'DTSTART:20191010T143904Z RRULE:FREQ=WEEKLY;INTERVAL=1;COUNT=1'

# For Workflow Template
awx schedules create --name 'My awesome schedule' --job_template 'My awesome workflow template' --rrule 'DTSTART:20191010T143904Z RRULE:FREQ=WEEKLY;INTERVAL=1;COUNT=1'
```

**Comment by ryanpetrello** [comment]
@idelsink,

The CLI programmatically generates these flags from the actual fields you'd send to the HTTP API, and in this case, Schedules *do* have a relationship called `unified_job_template`.  Job Templates and WorkflowJobTemplates are _both_ examples of UnifiedJobTemplates (for that matter, so are Projects and InventorySources), which **is** a named top-level resource in our API - just one that the browser-based UI goes to great lengths to conceal - see `/api/v2/unified_job_templates/`.

For this sake of simplifying ongoing development overhead, our CLI is _mostly_ auto-generated, and this is just one example of that.  I don't think we intend to add special code to facilitate what you're asking for here.
