### ISSUE TITLE
Outlier role association/disassociation activity stream entries when changed project's organization

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#5039]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
If you change the organization of the project, is shows changes in some roles, but not other roles.

##### ENVIRONMENT
* AWX version: 7.0.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  N/A
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Modify the organization of a project.

Check the activity stream.

##### EXPECTED RESULTS

1 entry that the organization of the project was changed. That permissions also change is implied.

##### ACTUAL RESULTS

2 additional unexpected entries

![Screen Shot 2019-10-18 at 11 21 04 AM](https://user-images.githubusercontent.com/1385596/67107013-a27e7e80-f199-11e9-8983-56ce9f00d5ef.png)

##### ADDITIONAL INFORMATION

Some content of one of those unwanted entries

```json
{
 "action": "disassociate",
 "object1": "project",
 "object1_pk": 25,
 "object2": "organization",
 "object2_pk": 163,
 "relationship": "awx.main.models.rbac.Role_parents"
}
```

**Comment by rebeccahhh** [comment]
@AlanCoding just to clarify, do we want more logs so that disassociations are noted or no logs except for the org change because the others are implied?

**Comment by AlanCoding** [comment]
The latter, fewer activity stream entries. Only user-defined role parentage should be shown in the activity stream. Implicit relationships between roles like this should not be shown.

**Comment by wenottingham** [comment]
"If you change the organization of the project"

When we move organization to JTs, we weren't going to let you do this any more. So will this matter?

**Comment by AlanCoding** [comment]
^ good point

**Comment by rebeccahhh** [comment]
closing out since it won't be relevant
