### ISSUE TITLE
Fix tag filtering in azure inventory source

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#5044]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Looks filtering hosts by tags is not working with azure inventory

##### ENVIRONMENT
* AWX version: 7.0.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Here's an example from this comment:

https://github.com/ansible/awx/issues/3430#issuecomment-543753718

The data structure of tags has been observed to be a dict, so the logic we are using will not work with the template that is applied.

##### EXPECTED RESULTS

the [expectations](https://github.com/ansible/ansible/blob/devel/contrib/inventory/azure_rm.ini) are

> Control which tags are included. Set tags to a comma separated list of keys or key:value pairs

those probably have to be handled separately.

##### ACTUAL RESULTS

filters all hosts out

##### ADDITIONAL INFORMATION

Filing new issue from details in prior comment in issue

**Comment by kdelee** [comment]
@fosterseth I tried this out with your example of:
```
exclude_host_filters:
- "'Creator' not in tags.keys()"
- tags['Creator'] not in ['jmarshall']
```
in the extravars for an azure inventory source pointed at our azure account.

It is not working for me, as I still am getting hosts that have no tags in sync:
```
tags: null
```

**Comment by fosterseth** [comment]
@kdelee 

in extra vars you'll put `tags: Creator:jmarshall, peanutbutter:jelly`

what you tried is an intermediate representation that is automatically generated and sent into azure_rm.py script to filter the inventory.

sorry for the confusion

**Comment by AlanCoding** [comment]
yeah, I believe that syntax ^ was tested with the script version, and that's what defines the expectation for now.

**Comment by wenottingham** [comment]
@fosterseth to be clear - is this fixed or not?

**Comment by fosterseth** [comment]
@wenottingham yes this is fixed

I just double checked that my tests pass and that the filtering of hosts is correct.

I'll get someone on QE to recheck

**Comment by kdelee** [comment]
> @kdelee
> 
> in extra vars you'll put `tags: Creator:jmarshall, peanutbutter:jelly`
> 
> what you tried is an intermediate representation that is automatically generated and sent into azure_rm.py script to filter the inventory.
> 
> sorry for the confusion

Finally got back to this, thanks for the clarification. LGTM, did inventory sync and then applied the tag filter and selected overwrite options, saw that hosts not matching filter were removed, leaving only those that matched it. Good work.
