### ISSUE TITLE
Execution Node is not displayed in UI in some scenarios

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#5048]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Execution Node is not reflect on UI in some scenarios. Container Groups are shown on a JT, however localhost node execution is not. Execution_node information is available in the API Response on the Job output

##### ENVIRONMENT
* AWX version: 7.0.0

##### STEPS TO REPRODUCE
1. Launch a JT using a localhost execution node.
2. View JT Results Output after JT completes.
Note: execution node information is not shown

##### EXPECTED RESULTS
Execution node information shown on JT Results for all JTs.

##### ACTUAL RESULTS
Execution node information shown for Container Groups
Execution node information not shown for localhost execution

##### ADDITIONAL INFORMATION
Container Group Execution Node
<img width="812" alt="Screen Shot 2019-10-21 at 11 12 44 AM" src="https://user-images.githubusercontent.com/12446869/67218146-e1a80c00-f3f3-11e9-8aab-da7940fbebbf.png">
API Response for localhost execution
![Screenshot from 2019-10-21 10-37-12](https://user-images.githubusercontent.com/12446869/67218200-f389af00-f3f3-11e9-8ca7-de986c1f49f3.png)
UI JT Results view for localhost execution
![Screenshot from 2019-10-21 10-36-41](https://user-images.githubusercontent.com/12446869/67218201-f389af00-f3f3-11e9-996e-a07fc32000c1.png)

**Comment by mabashian** [comment]
So I'm seeing these errors in the console for the job launched by a scheduled workflow:

<img width="1680" alt="Screen Shot 2019-10-21 at 1 19 36 PM" src="https://user-images.githubusercontent.com/9889020/67227600-8c74f600-f405-11e9-9b8a-51c51a5534ca.png">

**Comment by marshmalien** [comment]
To Reproduce: 
* Create a Job Template
* Create a Workflow Template that launches the Job Template you just created
* Create a schedule that launches the Workflow Template you just created
* View details of job

Other Note: 
Not only is the execution node detail missing, but many more job details failed to get created (instance group, environment, credential, extra variables, etc.)

**Comment by unlikelyzero** [comment]
@marshmalien did this ever work?

Verified in tower 3.5.0 that a user could see execution nodes on JTs launched by WFJTs launched by Schedules

**Comment by dsesami** [comment]
Tried a few permutations -- Job template alone, job template with workflow, and scheduled workflow, as well as a webhook trigger. No undefined values occur and everything looks correct.
