### ISSUE TITLE
Unable to register the first host / group / source

### ISSUE THREAD

**Issue by nakacya** [ansible/awx#5049]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

In the newly created inventory
Unable to register the first host / group / source

##### ENVIRONMENT
* AWX version: 7.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.5
* Operating System: CentOS 7.7.1908

##### STEPS TO REPRODUCE

In the newly created inventory
Unable to register the first host / group / source

##### EXPECTED RESULTS

Cannot press [New Host Button]

##### ACTUAL RESULTS

![not register host](https://user-images.githubusercontent.com/1404766/67220214-561a9380-f464-11e9-8b8d-4b65d9533100.png)

##### ADDITIONAL INFORMATION
Cannot be registered even with the tower-cli command, but can be registered by sending JSON from API WebUI

**Comment by ryanpetrello** [comment]
@nakacya are you running 7.0.0 or `devel` (given my knowledge of what's causing this bug, I suspect you're running the latest - or a very recent - version of `devel`, not strictly 7.0.0)?

**Comment by ryanpetrello** [comment]
@nakacya this should be fixed via: https://github.com/ansible/tower/pull/3871
