### ISSUE TITLE
Unable to sync with Git after updating to 7

### ISSUE THREAD

**Issue by brennus390** [ansible/awx#5052]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Unable to sync with Git after updating to 7

##### ENVIRONMENT
* AWX version: 7.0.0
* AWX install method: docker on Linux
* Ansible version:  2.8.5
* Operating System: RHEL 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Use the web UI to configure Git Source Control credentials
Use web UI to configure git repository under Projects

##### EXPECTED RESULTS

Successful download of Git repository

##### ACTUAL RESULTS

Error message and failed download

"Cloning into '/var/lib/awx/projects/_8__playbook'...",
        "fatal: unable to access 'https://$encrypted$:$encrypted$@server.localdomain/ansible-playbook/playbook.git/': Invalid file descriptor"##### ADDITIONAL INFORMATION

**Comment by ryanpetrello** [comment]
@brennus390 can you share the entire error message?

**Comment by brennus390** [comment]
I will try to provide the whole message, but I have to first clean out any specific data. I do want to note, that this fails when using https to clone, but works with ssh-keys. I also tried manually cloning from the awx_task container but still got the failure.

**Comment by brennus390** [comment]
{
    "stderr_lines": [
        "Cloning into '/var/lib/awx/projects/_8__playbook'...",
        "fatal: unable to access 'https://$encrypted$:$encrypted$@server.localdomain/ansible-playbook/playbook.git/': Invalid file descriptor"
    ],
    "cmd": "/usr/bin/git clone --origin origin 'https://$encrypted$:$encrypted$@server.localdomain/ansible-playbook/playbook.git' /var/lib/awx/projects/_8__playbook",
    "_ansible_no_log": false,
    "stdout": "",
    "changed": false,
    "invocation": {
        "module_args": {
            "force": true,
            "track_submodules": false,
            "reference": null,
            "dest": "/var/lib/awx/projects/_8__playbook",
            "accept_hostkey": false,
            "clone": true,
            "update": true,
            "ssh_opts": null,
            "repo": "https://$encrypted$:$encrypted$@server.localdomain/ansible-playbook/playbook.git",
            "bare": false,
            "archive": null,
            "recursive": true,
            "executable": null,
            "remote": "origin",
            "refspec": null,
            "separate_git_dir": null,
            "verify_commit": false,
            "umask": null,
            "depth": null,
            "version": "HEAD",
            "key_file": null
        }
    },
    "stderr": "Cloning into '/var/lib/awx/projects/_8__playbook'...\nfatal: unable to access 'https://$encrypted$:$encrypted$@server.localdomain/ansible-playbook/playbook.git/': Invalid file descriptor\n",
    "rc": 128,
    "_ansible_delegated_vars": {
        "ansible_host": "localhost"
    },
    "stdout_lines": [],
    "msg": "Cloning into '/var/lib/awx/projects/_8__playbook'...\nfatal: unable to access 'https://$encrypted$:$encrypted$@server.localdomain/ansible-playbook/playbook.git/': Invalid file descriptor"
}

**Comment by ryanpetrello** [comment]
@brennus390  for some reason git thinks your clone URL is a file reference.  Try removing the trailing slash in your project URL?

**Comment by wenottingham** [comment]
Please try the solution in the above comment, and re-open if the error persists.
