### ISSUE TITLE
Text Alignment is Off for "MINUTES" Text On Scheduling Page

### ISSUE THREAD

**Issue by beeankha** [ansible/awx#5055]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* `awx: 7.0.0`
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create a schedule for a Job Template, set `REPEATE FREQUENCY` to `Minute`.

Text alignment is off for the word `MINUTE` under the `FREQUENCY DETAIL` section, no matter how wide the browser window is:

<img width="369" alt="Screen Shot 2019-10-21 at 2 41 32 PM" src="https://user-images.githubusercontent.com/28930622/67234696-943b9700-f413-11e9-800d-545a610529c3.png">

**Comment by wenottingham** [comment]
punting to ui-next

**Comment by mabashian** [comment]
This should be moved to needs_test when #5864 gets merged
