### ISSUE TITLE
Fix "Launched By" for JTs in scheduled workflows

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#5057]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Background issue for https://github.com/ansible/awx/issues/5048.

The UI includes a "Launched By" tag to denote how something was launched.
It is propagated by some combination of:
- created_by (for the launching user)
- related schedule (for scheduled jobs)

This means you get the following:
- JT launched manually: user who launched job
- JT launched from schedule: schedule that launched job
- JT launched from a workflow manually: user who launched workflow
- Workflow launched manually: user who launched workflow
- Workflow launched from schedule: schedule that launched workflow
- **JT launched from a workflow launched by a schedule: nothing!**

For now, we're just not going to show the field in that final case, but we should propagate something via the API to give useful data here.

**Comment by wenottingham** [comment]
Moving to tackle with the new UI.

**Comment by amolgautam25** [comment]
Hi UI team, 

I have assigned this issue to myself. 

The resolution here seems to be that we need to add another API field ( or key ), in the response, such that the UI will know that the job was launched from a template ,and that template was inside of a schedule. 

I was wondering if we all can agree on what should we name the new KEY, in the response that will be sent. Let me know.

**Comment by jbradberry** [comment]
@amolgautam25 in my opinion, this calculated value should just be called `launched_by`.  I'm thinking it would probably make sense to do it as a `@property` on the `UnifiedJob` model, and then expose that value in the API serializer.

**Comment by fosterseth** [comment]
Given elsewhere this either points to a schedule or a user, `launched_by` should point to the schedule that launched the workflow, that launched the job.

**Comment by jbradberry** [comment]
There are also jobs launched by webhook, which should probably be a distinct case.  Also host callbacks, which I admit I don't know much about.

**Comment by jbradberry** [comment]
I think that these `LAUNCH_TYPE_CHOICES` are probably important for this use case, and should probably be part of what is conveyed to the UI.

https://github.com/ansible/awx/blob/09a0448c3e29d8be5c662cc78e58f05cff77026f/awx/main/models/unified_jobs.py#L537-L547

**Comment by kdelee** [comment]
@shebangbash @yagomarques  I think this will be a good issue for y'all, get in touch with @amolgautam25 about the feature and then I can help you find where to add coverage for this if necessary
