### ISSUE TITLE
AWX 8.0.0 Kubernetes deployment error

### ISSUE THREAD

**Issue by alancivita** [ansible/awx#5061]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Awx deployment failing at task TASK [kubernetes : Apply Deployment]

##### ENVIRONMENT
* AWX version: 8.0.0
* AWX install method: kubernetes
* Ansible version:  2.8.4
* Operating System: MacOS Catalina/ Ubuntu 16.04
* Web Browser:

##### STEPS TO REPRODUCE

run the isntaller with ansible-playbook -i inventory install.yml
##### ACTUAL RESULTS

deployment failing - full log attached to this issue.
version 6.0.0 and 7.0.0 were running fine on the same platform.

from httplib import HTTPConnection\n    import sys\n    import os\n    import base64\n    authsecret = base64.b64encode(os.getenv('RABBITMQ_USER') + ':' + os.getenv('RABBITMQ_PASSWORD'))\n    conn=HTTPConnection('localhost:15672')\n    conn.request('GET', '/api/healthchecks/node', headers={'Authorization': 'Basic %s' % authsecret})\n    r1 = conn.getresponse()\n    if r1.status != 200:\n      sys.stderr.write('Received http error %i\\n' % (r1.status))\n      sys.exit(1)\n    body = r1.read()\n    if body != '{\"status\":\"ok\"}':\n      sys.stderr.write('Received body: %s' % body)\n      sys.exit(2)\n    sys.exit(0)\n---\napiVersion: v1\nkind: Service\nmetadata:\n  name: awx-web-svc\n  namespace: awx\n  labels:\n    name: awx-web-svc\nspec:\n  type: \"NodePort\"\n  ports:\n    - name: http\n      port: 80\n      targetPort: 8052\n  selector:\n    name: awx-web-deploy\n---\napiVersion: v1\nkind: Service\nmetadata:\n  name: awx-rmq-mgmt\n  namespace: awx\n  labels:\n    name: awx-rmq-mgmt\nspec:\n  type: ClusterIP\n  ports:\n    - name: rmqmgmt\n      port: 15672\n      targetPort: 15672\n  selector:\n    name: awx-web-deploy\n---\napiVersion: extensions/v1beta1\nkind: Ingress\nmetadata:\n  name: awx-web-svc\n  namespace: awx\nspec:\n  backend:\n    serviceName: awx-web-svc\n    servicePort: 80\n", "msg": "non-zero return code", "rc": 1, "start": "2019-10-22 08:36:40.042215", "stderr": "error: error parsing STDIN: error converting YAML to JSON: yaml: line 25: could not find expected ':'", "stderr_lines": ["error: error parsing STDIN: error converting YAML to JSON: yaml: line 25: could not find expected ':'"], "stdout": "serviceaccount/awx unchanged\nservice/rabbitmq created\nconfigmap/rabbitmq-config created\nrole.rbac.authorization.k8s.io/endpoint-reader unchanged\nrolebinding.rbac.authorization.k8s.io/endpoint-reader unchanged\nstatefulset.apps/awx created", "stdout_lines": ["serviceaccount/awx unchanged", "service/rabbitmq created", "configmap/rabbitmq-config created", "role.rbac.authorization.k8s.io/endpoint-reader unchanged", "rolebinding.rbac.authorization.k8s.io/endpoint-reader unchanged", "statefulset.apps/awx created"]}

##### ADDITIONAL INFORMATION

[awx8_error.log](https://github.com/ansible/awx/files/3755130/awx8_error.log)

**Comment by ryanpetrello** [comment]
@wanderboessenkool this looks might it could be related to your recent PR.

Any ideas?

https://github.com/ansible/awx/pull/5009

cc @shanemcd

**Comment by HunterNyan** [comment]
This looks very similar to the output I was getting in my logs as well which lead me to my pull request

**Comment by alancivita** [comment]
#5063 looks like fixed that issue!

**Comment by ryanpetrello** [comment]
This should only affect awx 8.0.0, so I'm going to close this once #5063 merges momentarily.

Thanks for the fix @HunterNyan!
