### ISSUE TITLE
ansible/awx_rabbitmq:3.7.15 image doesn't exist

### ISSUE THREAD

**Issue by grahamn-gr** [ansible/awx#5077]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
ansible/awx_rabbitmq:3.7.15 container image doesn't exist

This is referenced in this recent PR: https://github.com/ansible/awx/pull/5074/files#diff-88fadd046eb3187e4500687368abc149R33

Are we able to use the official 3.7.15 image (rabbitmq:3.7.15)?

##### ENVIRONMENT
* AWX version: 8.0.0
* AWX install method: openshift
* Ansible version:  2.8.6
* Operating System: NA
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Kubernetes installer references ansible/awx_rabbitmq:3.7.15 container image but this can't pulled down from dockerhub as it's not present

##### EXPECTED RESULTS

The image exists and can be pulled down

##### ACTUAL RESULTS

Image fails to be pulled down

##### ADDITIONAL INFORMATION

https://hub.docker.com/r/ansible/awx_rabbitmq

**Comment by ghost** [comment]
Confirm this!

I'm trying to deploy AWX 8.0 on OKD 3.11, and the deployment of the StatefulSet awx cannot be completed due the missing awx_rabbitmq image.

EDIT: Added a screenshot
![immagine](https://user-images.githubusercontent.com/13005894/67573277-40dd8780-f738-11e9-98e9-2ddf3ba4536d.png)

**Comment by ryanpetrello** [comment]
@shanemcd you have any idea what's up here?

**Comment by shanemcd** [comment]
Oops. We updated this downstream but forgot to push to dockerhub. Should be fixed. Can you give it a try?

**Comment by ghost** [comment]
@shanemcd Yes, now it's working properly.
Thank you!

![immagine](https://user-images.githubusercontent.com/13005894/67603689-dfd6a380-f779-11e9-825e-a854cf9434f3.png)

**Comment by shanemcd** [comment]
yay 😄
