### ISSUE TITLE
if a container group is full, fall back to other instance/container group

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#5083]
##### ISSUE TYPE
 - Feature Idea
Currently, in certain scenarios jobs can end up getting funneled to Container Groups because they always **seem** to have capacity from the Tower side. Due to this naive concept of capacity, jobs may get less-than-optimally sent to the ContainerGroup where they may end up waiting on resources, while meanwhile resources are free'd up in other instance groups or container groups, leading to the job sitting in pending for longer than it needs to (or in worst case for a very saturated k8s cluster, failing due to time out waiting for resources, while there was other place it could have run).

To resolve this, we should do some kind of introspection to find out if the container group is "full" or if the job is schedulable. If so, we can redirect it to another instance group or wait until some other resource is available instead of dispatching it to the container group where it may very well time out and fail before running.

##### SUMMARY

This RFE replaces the bug report https://github.com/ansible/awx/issues/4990

**Comment by nixocio** [comment]
I have been seeing this, but in fact the jobs do not sit in pending or waiting, instead they failed with the message 

```shell
Job terminated due to timeout 
```

We can reproduce by creating a container group and assigned to a job template, and allowing simultaneous then launch a hundred jobs in succession (this depend on your cluster capacity).

If you watch your container namespace you will see something like that

```shell
[kmo@automata tower-qa]$ kubectl get pods -n nf4lm5cmhn
NAME          READY   STATUS              RESTARTS   AGE
awx-job-216   0/1     ContainerCreating   0          29s
awx-job-217   1/1     Running             0          29s
awx-job-218   1/1     Running             0          28s
awx-job-219   0/1     ContainerCreating   0          27s
awx-job-220   0/1     ContainerCreating   0          27s
awx-job-221   0/1     ContainerCreating   0          26s
awx-job-222   0/1     ContainerCreating   0          25s
awx-job-223   0/1     ContainerCreating   0          25s
awx-job-224   0/1     ContainerCreating   0          24s
awx-job-225   0/1     ContainerCreating   0          24s
awx-job-226   0/1     ContainerCreating   0          23s
awx-job-227   0/1     ContainerCreating   0          22s
awx-job-228   0/1     ContainerCreating   0          21s
awx-job-229   0/1     ContainerCreating   0          21s
awx-job-230   0/1     ContainerCreating   0          20s
awx-job-231   0/1     ContainerCreating   0          19s
awx-job-232   0/1     ContainerCreating   0          19s
awx-job-233   0/1     ContainerCreating   0          18s
awx-job-234   0/1     ContainerCreating   0          18s
awx-job-235   0/1     ContainerCreating   0          17s
awx-job-236   0/1     ContainerCreating   0          16s
awx-job-237   0/1     ContainerCreating   0          16s
awx-job-238   0/1     ContainerCreating   0          15s
awx-job-239   0/1     ContainerCreating   0          14s
awx-job-240   0/1     ContainerCreating   0          14s
awx-job-241   0/1     ContainerCreating   0          13s
awx-job-242   0/1     ContainerCreating   0          13s
awx-job-243   0/1     ContainerCreating   0          12s
awx-job-244   0/1     Pending             0          12s
awx-job-245   0/1     Pending             0          11s
awx-job-246   0/1     Pending             0          10s
awx-job-247   0/1     Pending             0          10s
awx-job-248   0/1     Pending             0          9s
awx-job-249   0/1     Pending             0          9s
awx-job-250   0/1     Pending             0          8s
awx-job-251   0/1     Pending             0          8s
awx-job-252   0/1     Pending             0          7s
awx-job-253   0/1     Pending             0          6s
awx-job-254   0/1     Pending             0          6s
awx-job-255   0/1     Pending             0          5s
awx-job-256   0/1     Pending             0          5s
awx-job-257   0/1     Pending             0          4s
awx-job-258   0/1     Pending             0          4s
awx-job-259   0/1     Pending             0          3s
awx-job-260   0/1     Pending             0          2s
awx-job-261   0/1     Pending             0          2s
awx-job-262   0/1     Pending             0          1s
awx-job-263   0/1     Pending             0          1s
awx-job-264   0/1     Pending             0          0s
```

Some of the jobs will succeed, but the last ones will time out.

**Comment by wenottingham** [comment]
Are we timing out if they are in pending on the cluster waiting for capacity too long?

**Comment by kdelee** [comment]
The job gets sent to kubernetes and then fail w/ timeout on AWX because it times out waiting for the pod to be ready to dispatch the job to it.

**Comment by wenottingham** [comment]
On the one hand, I understand this.

On the other, given https://github.com/ansible/awx/issues/6134, we should probably *not* do this fallback to another IG.

**Comment by wenottingham** [comment]
Closing this given #6134
