### ISSUE TITLE
Allow the project's SCM Branch to be overridden from a workflow template

### ISSUE THREAD

**Issue by idelsink** [ansible/awx#5088]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Workflow templates can specify the inventory, however I also would like it to override the project's branch (`SCM Branch`). 

With this option I can have a generic flow of multiple job templates and specify the branch for all of the job templates. This adds the ability to only make 3 workflows for testing, staging and production and then reuse the same job templates instead of making multiple job templates with the only difference being the `SCM Branch`.

The following issue was talking about this feature, however this has been closed and I don't see this feature in AWX? (https://github.com/ansible/awx/issues/282)

**Comment by wenottingham** [comment]
It's there in 8.0.0.
