### ISSUE TITLE
[AWXKIT] Unable to provide extra_vars when launching workflow_job_template

### ISSUE THREAD

**Issue by devops-42** [ansible/awx#5093]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Using the AWXKIT CLI tool `awx` it is not possible to provide extra parameters like `scm_branch` or `extra_vars` when launching a workflow_job_template. 

##### ENVIRONMENT
* AWX version: 8.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.10 (Client)
* Operating system: macOS Mojave

##### STEPS TO REPRODUCE

Installed AWX 8.0.0 and created a workflow `sample_workflow`, which
* has survey enabled: "Ask for `foobar`"
* prompt for SCM branch when launching workflow

Installed AWXKIT:

```pip install "https://github.com/ansible/awx/archive/8.0.0.tar.gz#egg=awxkit&subdirectory=awxkit"```

Tried to launch workflow:

```awx workflow_job_templates launch sample_workflow```

Result:

```{"variables_needed_to_start": ["'foobar' value missing"]}```

Tried to extend request by using same parameter as for `tower-cli`:

```awx workflow_job_templates launch sample_workflow -e '{"foobar": 12345}'```

After enabling debug output `awx` threw a warning, that `-e` is an `unrecognized argument`.

Tried various arguments like
* `--extra_vars`
* `--extra-vars`
* `-extra_vars`
* ...

Same result.

##### EXPECTED RESULTS

CLI tool should ask for missing configuration items like `extra_vars`, `scm_branch`, or at least provide documentation on how to launch this special kind of workflow_job_templates.

##### ACTUAL RESULTS

See "Steps to reproduce"

**Comment by ryanpetrello** [comment]
@devops-42 thanks for reporting this.

Would you mind giving this PR a try?

https://github.com/ansible/awx/pull/5156/

**Comment by kdelee** [comment]
Tested this out and it works for me, thanks!
