### ISSUE TITLE
UNTIL module be modified to remove the "FAILED - RETRYING:" wording

### ISSUE THREAD

**Issue by jpell958** [ansible/awx#5100]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
We would like to see the "retrying" messages for the UNTIL module be modified to remove the "FAILED - RETRYING:" wording and replaced with "Condition not met - RETRYING:" (or something to that nature).

Using the word "failed" can be confusing as the task has not actually failed yet until it exhausts all the retries.  The message should reflect the fact that the UNTIL condition has yet been met.  Only when the reties are exhausted should a "failed"message be issued.

**Comment by wenottingham** [comment]
This is not something AWX has any control over, this would need to be changed in Ansible itself. You'd need to file this at https://github.com/ansible/ansible/
