### ISSUE TITLE
awx_task log gives argument conversion issue after awx install with docker

### ISSUE THREAD

**Issue by krleitch** [ansible/awx#5107]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

After running the playbook command the docker containers are not properly installed.
Looking at the the awx_task container log gives the following

```
127.0.0.1 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": false, 
    "msg": "argument port is of type <type 'str'> and we were unable to convert to int: <type 'str'> cannot be converted to an int"
}
```
The discovered python interpreter is python 2.7.16
The commands are being ran in a python virtualenv with docker-compose installed

##### ENVIRONMENT
* AWX version: 8.0.0
* AWX install method: docker for mac
* Ansible version:  2.8.5
* Operating System: MacOS Mojave 10.14.6
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Run the playbook
```
ansible-playbook -i inventory install.yml
```

Then look at the log
```
docker logs -f awx_task
```

##### EXPECTED RESULTS

A successful installation.

##### ACTUAL RESULTS

It throws the above error.

##### ADDITIONAL INFORMATION

I see this issue has been observed before but says it was fixed. Not sure why I'm seeing it on latest.
https://github.com/ansible/awx/issues/3526

**Comment by KMFSousa** [comment]
I've seen this issue too. Haven't been able to find a solution yet

**Comment by krleitch** [comment]
Fixed!
Issue was the
```
ansible-playbook -i inventory install.yml
```
command was being ran with sudo. It must have been running into a permissions error somewhere. Granting user privileges to ~/.ansible worked. Curious if anyone has any info on why this was happening though.
