### ISSUE TITLE
k8s "create django super user if it does not exist" fails if DB migrations are not completed.

### ISSUE THREAD

**Issue by alancivita** [ansible/awx#5108]
##### ISSUE TYPE
 - Deployment failure

##### SUMMARY

Deployment fails due to task "create django super user if it does not exist" failing because DB migration are not completed yet.

##### ENVIRONMENT
* AWX version: 8.0.0
* AWX install method: kubernetes
* Ansible version:  2.8.4
* Operating System: MacOS/Ubuntu
* Web Browser:

##### STEPS TO REPRODUCE

awx deployment on some kubernetes environments fails due to DB migrations not completed. Specifically the"create django super user if it does not exist" task fails if migrations are not completed.
As a temporary fix i had to run the deployment with the --step config option and wait a couple of minutes for the Migrate database task to complete (it can be seen looking at the awx-celery container logs). 

##### EXPECTED RESULTS

Deployment to complete without issues

**Comment by ryanpetrello** [comment]
Hey @alancivita,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by alancivita** [comment]
Hi Ryan, indeed i think is a bug.

**Comment by wenottingham** [comment]
The migrations are run and completed two tasks before setting the superuser, so something is off in your environment - that is why we suggest the mailing list.

**Comment by alancivita** [comment]
thanks for the reply.
I will share the logs on the mailing list then - with the timings, where it can be seen that the migrations are still going on.
Cheers

**Comment by aqua-terra** [comment]
I had the same error during the deployment, Can you share the resolution to this, @alancivita  ?

**Comment by alancivita** [comment]
Hi, the only way i've found to fix it is this:
run the playbook with the --step flag and move forward by pressing Y..
wait for the Migrate database task to complete (it can be seen looking at the awx-celery container logs)..or just wait a couple of minutes (5 for example) before pressing Y after me Migrate Database task..
 after that you can move forward and you should be able to complete the installation.

**Comment by aqua-terra** [comment]
Thanks, @alancivita. It works!
