### ISSUE TITLE
Project source in WFJT launch using custom scm_branch not working

### ISSUE THREAD

**Issue by devops-42** [ansible/awx#5112]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When launching a workflow with `ask_scm_branch_on_launch` checked the AWX GUI asks for the SCM branch to use. In the job nodes the given branch name seems to be ignored.

##### ENVIRONMENT
* AWX version: 8.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.10
* Operating System: macOS
* Web Browser: Chrome

##### STEPS TO REPRODUCE

**Prepare a workflow job**

* Create a project for a given git repository
* Define a workflow job template named `scm_test`
* Check the box "Prompt on launch" above the "SCM branch" input field
* Click "Save" to open Workflow Visualizer
* Add a Node "Project Sync"
* Choose your project and click "Select"
* Leave the Visualizer by clicking "Save"
* Save the workflow job template

**Launch the workflow job**

* Click on launch and enter the branch of your choice
* When starting workflow job you'll see the correct value for `scm_branch` listed in job overview
* When clicking in job node "Project sync", `scm_branch` is set to `master`

##### EXPECTED RESULTS

Project sync checks out the given branch from user's input.

##### ACTUAL RESULTS

Instead, master branch is checked out by default

**Comment by wenottingham** [comment]
This isn't how you want to do this. A Project Update node is checking the SCM repo for a new revision; it's not intended to honor a prompt on launch in this way. The promptable branching is for a playbook run to use that revision..
