### ISSUE TITLE
More Collection metadata to track lost due to network issues

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/awx#5113]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

For one of our SLIs (service level indicators) we should measure how much data has been lost due to networking errors or processing errors.

We'll need some data from tower to measure this:
* Counts of event, unified_job, and job_template tables

They would need to be added to the bundle along with the span of time that they cover.  This should go back much further than the current bundle so that the count overlaps bundles.  

##### Additional Notes

* Exclude job updates from job counts
* Set the count to go back 7 days for starters

**Comment by wenottingham** [comment]
This issue feels obsolete; it should be handled on the AA side, with a new issue opened if we're missing something.
