### ISSUE TITLE
Replace `with_items` with `loop` keyword in all playbooks

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#512]
We are using `with_items` for internal use in several playbooks:

https://github.com/ansible/awx/search?q=with_items

These are being removed in a future version of Ansible.

```
[DEPRECATION WARNING]: with_ type loops are being phased out, use the 'loop' keyword instead. This feature will be removed in version 2.9. Deprecation warnings can be disabled
 by setting deprecation_warnings=False in ansible.cfg.
```

Those uses should be replaced with the new pattern, except for the test in the "old" folder. That test should just be removed completely.

**Comment by wenottingham** [comment]
We can't do this until we're sure every playbook will be run with 2.5 or later.

**Comment by AlanCoding** [comment]
Good point. We can switch out `awx/lib/tests` a little earlier than that, but we do need a timeline.

**Comment by shanemcd** [comment]
Did we ever do this?

**Comment by wenottingham** [comment]
No, but I also think the syntax got undeprecated. We can do this more targeted-ly later if needed.
