### ISSUE TITLE
support for azure government keyvault integration 

### ISSUE THREAD

**Issue by russelljftw** [ansible/awx#5138]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The azure keyvault credentials plugin found here:
awx/awx/main/credential_plugins/azure_kv.py 

Is hard coded to use the azure commercial cloud vault URL: 
```
def auth_callback(server, resource, scope):
        credentials = ServicePrincipalCredentials(
            url = url,
            client_id = kwargs['client'],
            secret = kwargs['secret'],
            tenant = kwargs['tenant'],
            resource = "https://vault.azure.net",
        )
```
It would be great to either have a second plugin for azure government or a field in the plugin to select AzureCloud or AzureUSGovernment similar to the credential type "Microsoft Azure Resource Manager"

**Comment by kdelee** [comment]
@russelljftw have you had a chance to try this out?

**Comment by kdelee** [comment]
@jakemcdermott do you have any suggestions for how to test this out?

**Comment by jakemcdermott** [comment]
@kdelee yes

- [x] Verify no regressions have occurred with any of our tests that use the default (standard azure cloud) choice.
- [x] Verify all options show up correctly in the UI and API on a clean install and after running an upgrade on a system that already has one of these credentials created.
- [x] Create an azure keyvault credential using one of the new cloud options, link it to a machine credential, link the credential to a job template, and run the job template. It'll fail, but you can still verify that the url is building correctly and that the outbound request is formatted properly.
- [x] Verify test button is (still) behaving correctly on an instance of this credential type using an expected success and expected failure scenario.

We can wait to hear back from @russelljftw on whether he's had a chance to try it out on the altcloud.

**Comment by one-t** [comment]
This appears to be working as expected, waiting on confirmation from someone with access to one of these altclouds

**Comment by russelljftw** [comment]
We stood up a awx dev server recently and I'll try to test out the functionality in the next few days.  We've confirmed the option for the altcloud is in the portal, but haven't created a cred yet.

**Comment by jneedle** [comment]
@russelljftw Did you ever get a chance to confirm this?

**Comment by kdelee** [comment]
Going to close as there have been no reported problems and changes seem sane
