### ISSUE TITLE
Inventory sourced from a project fails when there is a vault in group_vars

### ISSUE THREAD

**Issue by flarno11** [ansible/awx#514]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

When adding an inventory via 'Sourced from a Project' it fails with 'ERROR! Attempting to decrypt but no vault secrets found'. I have a vault password defined, but this seems to get ignored. If I define ANSIBLE_VAULT_PASSWORD_FILE manually it works, but it adds all group_vars to the imported hosts, even the encrypted ones visible in clear text.

##### ENVIRONMENT
* AWX version: 1.0.1.100 (from 2017-10-26)
* AWX install method: docker for mac
* Ansible version:  2.4.0
* Operating System: MacOS
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Example inventory:
[test]
host_test

with an encrypted Ansible Vault in this location:
group_vars/
&nbsp;&nbsp;test/
&nbsp;&nbsp;&nbsp;&nbsp;vault

Then add a new inventory with 'Sourced from a Project' and run the import.

##### EXPECTED RESULTS

Hosts imported, without all the group_vars

##### ACTUAL RESULTS

"ERROR! Attempting to decrypt but no vault secrets found"
or
imported host, with all encrypted variables defined in the host visible in clear text

**Comment by wenottingham** [comment]
this is https://github.com/ansible/awx/issues/223, closing as duplicate

**Comment by redcricket** [comment]
I was able to get the inventory to sync from git.  I had set the ANSIBLE_VAULT_PASSWORD_FILE: /runner/project/vault_pass in the details of the inventory source screen.  Then I had to exec on to container in the awx pod and find the directory where my project lives and echo "thepassword" > vault_pass.
