### ISSUE TITLE
Any tower install done without specifying a macOS catalina-compatible cert at runtime will block macOS + Chrome users from accessing the web UI after July 1st, 2019

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#5144]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
MacOS Catalina users might be impacted by increased requirements for ca certs. If the user does not provide a cert at installtime, our tower-packaging playbook will generate a CA Cert which does not meet the requirements here https://support.apple.com/en-us/HT210176.

This means that all fresh installs of ansible tower after July 1st will generate a CA Cert which blocks macOS Catalina Users from accessing the Web app with Chrome.

##### ENVIRONMENT
* AWX version: Any version of tower without a ssl cert passed at install-time
* Operating System: macOS Catalina (only)
* Web Browser: Chrome any (only chrome)

##### STEPS TO REPRODUCE

Deploy tower without providing a SSL cert.
From a macOS Catalina + Chrome browser, attempt to access tower's UI

##### EXPECTED RESULTS

Standard Self Signed Cert errors and the ability to proceed.

##### ACTUAL RESULTS

Standard Self Signed Cert errors and no ability to proceed.

##### ADDITIONAL INFORMATION

Based on the research and troubleshooting done within this ticket: https://github.com/ansible/awx/issues/5122

**Comment by unlikelyzero** [comment]
@elyezer @wenottingham @dsesami @mabashian this is not technically a release blocker but will need to be researched asap in case tower-packaging changes apply.

It's a continuation of this ticket https://github.com/ansible/awx/issues/5122

**Comment by ghjm** [comment]
The difficulty here is that we don't necessarily know, at install time, what hostname users will be using to access Tower.  We could kinda-sorta guess that it's probably the ansible_hostname, but users with a load balancer or complex DNS, or just who decided to use IP addresses in their Tower inventory file, won't have a hostname we can parse out to put into this certificate.

Currently, we're using `localhost` - maybe someone with a Catalina install can check if it accepts a cert with `localhost` in a SAN as well as a CN.

If not, then the only thing I can think of would be to ask for a hostname from the end-user at install time, maybe through an inventory variable.

**Comment by jakemcdermott** [comment]
moving this issue to a different repo
