### ISSUE TITLE
Does ansible/ansible-runner need oc installed when using localhost container group host?

### ISSUE THREAD

**Issue by ffirg** [ansible/awx#5147]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX - running Demo Job Template against a localhost based container group fails, when run_isolated.yml calls synchronize (line 21) to run an rsync. It's expecting the oc client to be there but is missing from the ansible/ansible-runner image?

##### ENVIRONMENT
* AWX version: 8.0.0.0.0
* AWX install method: CRC version: 1.0.0+575079b OpenShift version: 4.2.0 (embedded in binary)
* Ansible version:  2.8.6
* Operating System: Runing MacOS Mojave 10.14.6
* Web Browser: Chrome 77.0.3865.90 (Official Build) (64-bit)

##### STEPS TO REPRODUCE

Setup Openshift Bearer Token Credential in AWX
Setup CRC container group instance in AWX
Modify Demo Job Template to use the container group in AWX
Run the JT in AWX

##### EXPECTED RESULTS

Demo job should invoke ansible-runner inside the container and succeed.

##### ACTUAL RESULTS

ansible-playbook 2.8.6
config file = /etc/ansible/ansible.cfg
configured module search path = [u'/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/plugins/isolated']
ansible python module location = /usr/lib/python2.7/site-packages/ansible
executable location = /usr/bin/ansible-playbook
 python version = 2.7.5 (default, Aug 7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: run_isolated.yml *****************************************************
1 plays in run_isolated.yml
PLAY [Prepare data, dispatch job in isolated environment.] ********************* 
META: ran handlers TASK [synchronize job environment with isolated host] **************************
task path: /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/playbooks/run_isolated.yml:14
skipping: [awx-job-38] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [synchronize job environment with remote job container] ******************* 
task path: /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/playbooks/run_isolated.yml:21
fatal: [awx-job-38 -> localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --copy-links --archive --rsh=$RSH --out-format=<<CHANGED>>%i %n%L /tmp/awx_38_q21m3pzt awx-job-38:/tmp", "msg": "rsync: Failed to exec oc: No such file or directory (2)\nrsync error: error in IPC code (code 14) at pipe.c(85) [sender=3.1.2]\nrsync: safe_write failed to write 4 bytes to socket [sender]: Broken pipe (32)\nrsync error: error in IPC code (code 14) at io.c(320) [sender=3.1.2]\n", "rc": 14}
PLAY RECAP ********************************************************************* 
awx-job-38 : ok=0 changed=0 unreachable=0 failed=1 skipped=1 rescued=0 ignored=0

##### ADDITIONAL INFORMATION

Should the image include the oc binary by default?

**Comment by ffirg** [comment]
Also just tested against an external OCP 4.2.0 cluster running in AWS. Same error. 

Actually, is it that the oc binary needs to be on the AWX pods? I guess it's running an oc rsync from there over to the remote cluster via the synchronize module?

**Comment by shanemcd** [comment]
I believe you found a bug. It seems like we forgot to install these clients in our upstream AWX images. I'll work on a fix today.

**Comment by ffirg** [comment]
Nice, thanks Shane! Happy to test again when it's ready.

**Comment by shanemcd** [comment]
Fixed in https://github.com/ansible/awx/pull/5164. We will cut another release within the next day or so.

**Comment by ffirg** [comment]
I noticed you’ve used oc client from v3.9.0. Will that work with v4 as well? I believe they are different clients.

**Comment by ryanpetrello** [comment]
This should be resolved in awx 9.0.0.
