### ISSUE TITLE
Move all execution to execution nodes managed via receptor network

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#5151]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Enable users to have a distributed network of execution nodes, where the only requirement is that the nodes have ansible-runner, ansible, and [receptor](https://github.com/project-receptor/receptor) installed. This node can then self register or be registered to the receptor network of which AWX control plane nodes will be receptor controllers (or able to dispatch work via a receptor controller).

This should be extended to be the only way jobs are executed - when a task is assigned to a node to be done, it should be done through that mechanism; there shouldn't be a separate way of running jobs.

This may mean replacing way work is dispatched to container groups as well, but that may be punted (not critical to ship this feature for all other nodes).

Acceptance criteria:
-----------------------------

- [ ] In the case that the execution node can reach Tower via the receptor network, it should be able to self register.
- [ ] If because of network topology only Tower can reach out to the execution node via the receptor network, then Tower should be able to find/register the execution node.
- [ ] only requirement of execution nodes are ansible-runner, ansible, and receptor and ability to receive network traffic from at least one receptor controller
- [ ] no downtime required when adding execution nodes
- [ ] connections w/ receptor are all TCP
- [ ] Right now our isolated node delivery time failure is 30 seconds, we will have similar resilience
- [ ] If job gets received and started but we lose node during execution, will have to do same thing we do today as far as marking it as failed because job no longer found running
- [ ] Each receptor can it manage multiple jobs at once, we should be able to dispatch more than one job at a time to an execution node
- [ ] Currently there is nothing built into receptor/runner that would prevent us from OOMing the system, but we need to implement something (capacity check of some kind) because currently we do this w/ isolated heartbeat + dispatcher

Questions to be answered:
---------------------------------------
- [ ] Multiple receptors can cohabitate on same system, can an execution node get registered several times under each of these receptors?

Additional notes:
------------------------
Receptor does not fork, hands off work to plugin that may fork
Plugin COULD be written in way that never gave control back to runner, which would force serial execution.
Runner plugin is written in such a way that should allow multiple calls to runner plugin, e.g. parallel job.

**Comment by wenottingham** [comment]
As part of this, execution nodes should be able to register and deregister dynamically as needed.

**Comment by ffirg** [comment]
this issue is outdated and the requirement already delivered so closing
