### ISSUE TITLE
Selecting "Regions: All" in Azure Resource Manager Source Causes 0 VM Imports

### ISSUE THREAD

**Issue by challett** [ansible/awx#516]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### ENVIRONMENT
* AWX version: 1.0.0.588
* AWX install method: docker on linux
* Ansible version:  2.4.0.0 
* Operating System: Centos
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Setup Valid Azure Resource Manager Credenials
2. Add new Azure Resource Manager source using credentials created earlier
3. Select "All" from Regions dropdown menu
4. Refresh inventory list

##### EXPECTED RESULTS

Instances from all regions will be imported to the inventory.

##### ACTUAL RESULTS

Zero Instances are imported to the inventory.

##### ADDITIONAL INFORMATION

Leaving the field blank causes all resources to be imported as expected.
AWX is actually passing the location "All" to azure_rm.py which doesn't match any locations in azure and causes all resources to be filtered out.

**Comment by ryanpetrello** [comment]
Hey @challett - are you running the latest version of awx?  This is a known bug that was recently fixed:

https://groups.google.com/forum/#!searchin/awx-project/azure%7Csort:date/awx-project/EBzE7923T5Q/MbqqRN0rAgAJ

https://github.com/ansible/awx/commit/328b70ceb8e1ce6c8da5e9f5d2fc4e01caf91bc0

Can you add your environment's information on this ticket?

```##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:
```

**Comment by challett** [comment]
Hey sorry I didn't realize that it was commented out in the comment. It should appear now.  

I've installed awx using the latest image about a week ago or so.  If it has been fixed since then then that's great!

**Comment by ryanpetrello** [comment]
Not your fault, I've done this too.

https://github.com/ansible/awx/pull/520 😄
