### ISSUE TITLE
Data flow in awx

### ISSUE THREAD

**Issue by sinu** [ansible/awx#5162]
Hello Team,

I am using awx with container, can someone help me to understand the requestflow/dataflow in this case, want to understand how the containers are linked and how the data flowing between these containers

**Comment by wenottingham** [comment]
This issue is for reporting issues in AWX, this sort of question belongs on the mailing list or IRC channel.

**Comment by sinu** [comment]
@wenottingham no one is responding in group as well as in irc please help i am unable to find any document regarding this
