### ISSUE TITLE
Add parameter to tower_job_template to take extra_vars directly

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#5167]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Right now this module has parameter `extra_vars_path`, and users would obviously prefer direct input of variables.

A proposed fix was put up at https://github.com/ansible/ansible/pull/57225, and needs to be moved over here. There's still a lot of content in that we don't need, and maybe it should be done from scratch.

**Comment by AlanCoding** [comment]
It also needs to have a type defined, and the prior attempt made a dict (which is probably reasonable).

**Comment by squidboylan** [comment]
Just merged https://github.com/ansible/test-playbooks/pull/99 which tests this
