### ISSUE TITLE
Awx-Postgresql deployment using Helm Chart

### ISSUE THREAD

**Issue by pbhandaru** [ansible/awx#5169]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY

Hi, 

I am not sure if this is the right forum . I am trying to deploy awx-postgresql pod using helm chart stable/postgresql by setting up a local repo since the K8 cluster we are using does not have access to the open source docker hub to pull the bitnami Images.

Have changed the docker image and repository location in the Charts/values.yaml downloaded from stable/postgresql and ran the helm install to see if the changes are working and I see the error below .  Please let me know if any one is aware of the error below.

Error: render error in "postgresql/templates/statefulset.yaml": template: postgresql/templates/statefulset.yaml:50:4: executing "postgresql/templates/statefulset.yaml" at <include "postgresql.imagePullSecrets" .>: error calling include: template: postgresql/templates/_helpers.tpl:276:48: executing "postgresql.imagePullSecrets" at <.Values.metrics.image.pullSecrets>: nil pointer evaluating interface {}.image

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: Kubernetes
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE
helm install --dry-run --debug ./postgresql

**Comment by ryanpetrello** [comment]
Hey @pbhandaru,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
