### ISSUE TITLE
New in ansible awx problem with playbook

### ISSUE THREAD

**Issue by ghost** [ansible/awx#517]
Hello everyone, 
I'm new in ansible awx, sorry if my problem was on forum but I'm not able to find it.
So I have some experiance in using ansible via CLI. Now I'm testing AWX.
I have prepared playbeook which work thru CLI, but when I'm trying to use it in AWX i got error:

![image](https://user-images.githubusercontent.com/33155415/32106389-c5c6b3f4-bb2b-11e7-909d-5d705836632a.png)

Playbook below:
---
- name: adduser
  hosts: all
 
  tasks:
 
  - name: newuser
    shell: useradd -s /bin/bash -m -d /home/xx xx && usermod -g adm xx &&  mkdir -p /home/xx/.ssh/ && echo "ssh-rsa xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx== xx" > /home/xx/.ssh/authorized_keys && echo 'xx    ALL=NOPASSWD{{':'}} ALL' >> /etc/sudoers && passwd -l xx 

I'm not able to run my script, and I'm don't know why.
My AWX VERSION : AWX 1.0.1.31
My Ansible version: Ansible 2.4.0.0 
Os: Linux version 3.10.0-693.2.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Tue Sep 12 22:26:13 UTC 2017

**Comment by wenottingham** [comment]
Your playbook is marked as a python file, I suspect it's not being executed properly. 

This is not an AWX issue - https://groups.google.com/forum/#!forum/ansible-project may be more appropriate.

**Comment by ghost** [comment]
Not sure that you have right I guess that your idea is regarding that, what is on screen ssl.py but it's not my playbook, Just have a look:
![image](https://user-images.githubusercontent.com/33155415/32107762-de48baa4-bb2f-11e7-98c9-020db52a19b3.png)
