### ISSUE TITLE
Want to install AWX high availability  on centos 7.

### ISSUE THREAD

**Issue by vaishnavi1993** [ansible/awx#5187]
##### ISSUE TYPE
 Want to install AWX high availability  on centos 7.

##### SUMMARY
I have installed AWX with localhost on centos 7, which was done successfully.But I also want to install AWX with high availability.
So I have placed 3 clustered servers in inventory file and then ran the install.yml. It has installed AWX in all three servers, but when I check for API ping for example https:// <serverip/api/v2/ping>
it is showing the high availability as false.

kindly suggest on how to approach this HA functionality.

**Comment by wenottingham** [comment]
This is a bug tracker for AWX. Your question seems more appropriate for the mailing lists or the IRC channel; please ask it there.
