### ISSUE TITLE
New menu dedicated for manual job/worfklow

### ISSUE THREAD

**Issue by Dodofox** [ansible/awx#5189]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
There are some workflow/job that we want to be launch manually only  (for exemple new vm deployment). 
Today we have to go on the modele job/workflow menu and launch it. 
It could be more ergonomic to create a new menu for these kind of job with spécific ACL. This menu could permit only to launch workflow/job define as a manually.

**Comment by wenottingham** [comment]
This is what the portal/my view is for. See #1240.
