### ISSUE TITLE
Footer is blocking items from being visible/actionable in the ui

### ISSUE THREAD

**Issue by spathare21** [ansible/awx#52]
### Summary

Pagniate controls to move on next page and number of items view per page drop down  are not visible in Activity Stream.

### Branch 
Devel

### Environment
* AWX version: 1.0.0.269
* Ansible version:  2.3.1.0 
* Operating System: Fedora 25
* Web Browser: Chrome 60 , Firefox 55 64 bit.

### Steps To Reproduce:
- Setup new instance using docker.
- Open the AWX-Ansible instance on chrome/firefox
- Click on dashboard.
- Click on View Activity Stream from top right corner.
- Scroll down and observe the paginated controls and view per page dropdown.
- Zoom-out to below 80 %.
- Observe controls are shows.
- Then double clik on top of browser to minimize the browser size.
- Again observer those controls are not visible 

### Expected Results:

- Paginated controls and view per page drop down should be visible clearly.

### Actual Results:

Controls are getting hide.

### Additional Information:
Attached screen captured for more info.

![paginate_invisible](https://user-images.githubusercontent.com/23230884/30194948-e248db68-9445-11e7-8568-ae933b64df0b.png)

![paginate_visible](https://user-images.githubusercontent.com/23230884/30194949-e74f209a-9445-11e7-9782-74625fca0a01.png)

![paginate_visible](https://user-images.githubusercontent.com/23230884/30195003-48add1ec-9446-11e7-81c7-cf69e69ee120.png)

**Comment by jlmitch5** [comment]
@jaredevantabor I believe you had worked on this a few weeks back, assigning you to take a look.

Thanks for filing the issue, @spathare21!

**Comment by pchauncey** [comment]
This issue also causes buttons to be obscured on some pages (Settings -> LDAP for example):

![screenshot from 2017-09-08 13-12-41](https://user-images.githubusercontent.com/908819/30226308-2d43b61a-949b-11e7-865b-82e68cf9fff1.png)

**Comment by jlmitch5** [comment]
@pchauncey yep--should be a fix at the footer styling level and it's fixed everywhere.  I'm going to update the issue title so that's clear.

**Comment by Zokormazo** [comment]
The footer has an absolute positioning and 40px height. Giving the main container a bottom-padding of 40px should fix this.
