### ISSUE TITLE
Remove Switch style override when display bug fixed upstream

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5211]
##### ISSUE TYPE
 - Task

##### SUMMARY
Remove `--pf-c-switch__toggle-icon--Offset: 0.125rem;` from Switch component(s) when PF fixes bug upstream.

**Comment by unlikelyzero** [comment]
@mabashian still an issue?

**Comment by mabashian** [comment]
Grep'd the codebase for that variable and I didn't find it.  I don't think this is still an issue and will close.
