### ISSUE TITLE
Buildling awkit cli HTML doc does not work anymore.

### ISSUE THREAD

**Issue by Spredzy** [ansible/awx#5217]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY

When trying to build the `awxkit-cli` HTML documentation (via `make clean html`) the process fails with the following issue:

```
Exception occurred:
  File "/home/ec2-user/awxkit/lib64/python3.6/site-packages/sphinxcontrib/autoprogram.py", line 105, in format_option
    value = '{{{0}}}'.format(','.join(arg.choices))
TypeError: sequence item 0: expected str instance, int found
```

This is the arg value it fails on

```
_StoreAction(option_strings=['--verbosity'], dest='verbosity', nargs=None, const=None, default=None, type=<class 'int'>, choices=[0, 1, 2, 3, 4, 5], help='', metavar=None)
```

`git bisect` indicates that https://github.com/ansible/tower/commit/c882cda58678e9509cdb398ea8ed46a4d33b8efd is the commit responsible for the breakage

##### ENVIRONMENT

  - N/A

##### STEPS TO REPRODUCE

  - Clone the repo, go into `awxkit/awxkit/cli/docs` and run `make clean html`

##### EXPECTED RESULTS

  - Process to exit successfully

##### ACTUAL RESULTS

  - Process fails to run

```
Exception occurred:
  File "/home/ec2-user/awxkit/lib64/python3.6/site-packages/sphinxcontrib/autoprogram.py", line 105, in format_option
    value = '{{{0}}}'.format(','.join(arg.choices))
TypeError: sequence item 0: expected str instance, int found
```

##### ADDITIONAL INFORMATION

  -N/A

**Comment by ryanpetrello** [comment]
@Spredzy @kdelee this is ready for another look, I think it's been fixed in `devel`.

**Comment by Spredzy** [comment]
Working.
