### ISSUE TITLE
VERISON 9.0.1 for awx_web docker image not found

### ISSUE THREAD

**Issue by rcarbajal01** [ansible/awx#5232]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Error starting project manifest for docker.io/ansible/awx_web:9.0.1 not found

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: docker on linux
* Ansible version:  2.7.5
* Operating System: RHEL 7
* Web Browser:

##### STEPS TO REPRODUCE

sudo ansible-playbook -i inventory install.yml

##### EXPECTED RESULTS

Start container successfully 

##### ACTUAL RESULTS

TASK [local_docker : Start the containers] ***********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "errors": [], "module_stderr": "", "module_stdout": "Trying to pull repository registry.access.redhat.com/memcached ... \nPulling repository registry.access.redhat.com/memcached\nTrying to pull repository docker.io/library/memcached ... \nalpine: Pulling from docker.io/library/memcached\nDigest: sha256:37c28f53d30d7b8d273eb86465f92932cac6662477075c85d4bc8d0ceb349f96\nStatus: Downloaded newer image for docker.io/memcached:alpine\nTrying to pull repository registry.access.redhat.com/postgres ... \nPulling repository registry.access.redhat.com/postgres\nTrying to pull repository docker.io/library/postgres ... \n10: Pulling from docker.io/library/postgres\nDigest: sha256:3263c8dad1b5aa6be80144786b18515910165ed771863d686c8b8fda30fea1ad\nStatus: Downloaded newer image for docker.io/postgres:10\nTrying to pull repository registry.access.redhat.com/ansible/awx_rabbitmq ... \nPulling repository registry.access.redhat.com/ansible/awx_rabbitmq\nTrying to pull repository docker.io/ansible/awx_rabbitmq ... \n3.7.4: Pulling from docker.io/ansible/awx_rabbitmq\nDigest: sha256:3ff448f979149a0684c61b0f00eb0fe7bc480b123323aa80fb3bb8934027f895\nStatus: Downloaded newer image for docker.io/ansible/awx_rabbitmq:3.7.4\nTrying to pull repository registry.access.redhat.com/ansible/awx_web ... \nPulling repository registry.access.redhat.com/ansible/awx_web\nTrying to pull repository docker.io/ansible/awx_web ... \nTrying to pull repository registry.fedoraproject.org/ansible/awx_web ... \nPulling repository registry.fedoraproject.org/ansible/awx_web\nTrying to pull repository quay.io/ansible/awx_web ... \nPulling repository quay.io/ansible/awx_web\nTrying to pull repository registry.centos.org/ansible/awx_web ... \nPulling repository registry.centos.org/ansible/awx_web\nTrying to pull repository docker.io/ansible/awx_web ... \n", "msg": "Error starting project manifest for docker.io/ansible/awx_web:9.0.1 not found"}
        to retry, use: --limit @/local/mnt/usr2/deployments/awx/installer/install.retry

PLAY RECAP *******************************************************************************************************************************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=1

**Comment by shanemcd** [comment]
I think you were too quick and tried to run the installer before the image push finished. Try again now.

**Comment by 1junechung** [comment]
I also have this error. for mine it is awx_web:9.1.1. and if you go into docker hub, the image name is ansible/awx_web:latest , not 9.1.1. I'm assuming the name difference is the reason the playbook cannot pull the image from docker.
