### ISSUE TITLE
Refactor VariablesField to handle variables stored as JSON

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5235]
##### ISSUE TYPE
 - Bug

##### SUMMARY

If you use the `VariablesField` in a form and create a resource with variables formatted as JSON, the edit form field will be toggled to `YAML` by default.

https://github.com/ansible/awx/blob/devel/awx/ui_next/src/components/CodeMirrorInput/VariablesField.jsx#L19 defaults to `yaml` even if the stored value is JSON.  `VariablesInput` is configured a bit differently but uses utility functions to determine whether value(s) are JSON/YAML https://github.com/ansible/awx/blob/devel/awx/ui_next/src/components/CodeMirrorInput/VariablesInput.jsx#L32.  One idea for achieving this would be to wrap the component with `withFormik` in order to have access to the value on props.  https://jaredpalmer.com/formik/docs/api/withformik

https://github.com/ansible/awx/pull/5180#issuecomment-548875368

**Comment by keithjgrant** [comment]
The latest version of Formik introduces a number of new hooks that can accomplish this without `withFormik` wrapper. I'm working now on this upgrade so I can fix this issue with a hook.
