### ISSUE TITLE
Add sparkline of recent jobs to expanded host row

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5236]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The awx-pf interface for hosts exposes recent jobs in a sparkline (like templates) but the one piece of information that we're missing is the job `type`.  The `type` is important because it allows us to navigate directly to the correct output page for the job in question without having to make an extra request.

I tried this chunk:

```
        d.setdefault('recent_jobs', [{
            'id': j.job.id,
            'name': j.job.job_template.name if j.job.job_template is not None else "",
            'status': j.job.status,
            'finished': j.job.finished,
            'type': j.job.get_real_instance_class()._meta.verbose_name.replace(' ', '_')
        } for j in obj.job_host_summaries.select_related('job__job_template').order_by('-created')[:5]])
```

in `def get_summary_fields(self, obj):` in the `HostSerializer` but wasn't sure if that was performant or correct.

**Comment by mabashian** [comment]
If this isn't possible - there are some ways we can get around it.  We can set up a generic job endpoint that acts as a router and redirects to the correct output page after a GET request to the job (to get the type).

**Comment by mabashian** [comment]
Note that these links:

<img width="1485" alt="Screen Shot 2019-11-04 at 4 37 22 PM" src="https://user-images.githubusercontent.com/9889020/68160292-7432ca00-ff21-11e9-9c09-ba9a89d6be16.png">

will be broken until we come up with a solution

**Comment by unlikelyzero** [comment]
Extra network call
<img width="1911" alt="Screen Shot 2020-07-16 at 12 02 32 PM" src="https://user-images.githubusercontent.com/12446869/87694435-364a9e80-c75c-11ea-9108-116ae4b5c0db.png">

**Comment by jakemcdermott** [comment]
https://github.com/ansible/awx/pull/7631#discussion_r455982679 :eye: :eye:

**Comment by kdelee** [comment]
Unit tests added for this attribute in the api are sufficient for future regression testing, going to call this verified from the API perspective and remove the `component:api` label
tests: https://github.com/ansible/awx/pull/7611/files#diff-c967e9f6369e046cb79c1676024a5187a3f25f37f6d154320594b6ba3479b0cdR38

**Comment by unlikelyzero** [comment]
Note: We can cover this feature by simply adding a feature test here https://github.com/ansible/awx/issues/5236#issuecomment-549558786

**Comment by unlikelyzero** [comment]
I'll keep this one and explain the reasoning in the tower-qa PR

**Comment by jakemcdermott** [comment]
I believe this is implemented and tested, & the qe pr can be tracked elsewhere. Please re-open if I missed something.

**Comment by unlikelyzero** [comment]
@jakemcdermott iirc we didn't explicitly have a test for this and I was going to give an explanation in the tower-qa pr

**Comment by akus062381** [comment]
@unlikelyzero if you see this- I am looking for the associated tower-qa PR that you refer to above, and I'm not seeing it- are you able to provide me with some insight?

**Comment by akus062381** [comment]
per @mabashian we should put this back into needs_devel.

**Comment by mabashian** [comment]
Now that this list has expandable rows we should add this back in to the expanded view of a host.

**Comment by unlikelyzero** [comment]
@mabashian @akus062381 IIRC you need to ensure that you're not making an extra Network XHR request for the summary_fields.recent_jobs data in order to represent information on the Hosts lists.

To verify this, I would generate a dataset with 25? different hosts with full job result histories (5 each?). Expand each row. Verify that a minimum number of requests are made to represent the dataset. 

@akus062381 I would see what other expanded rows are missing recent runs (Job Templates, Workflow, Project Syncs, etc)

**Comment by tiagodread** [comment]
Done
