### ISSUE TITLE
Getting parse inventory error when running Job Template using VMWare inventory builtin script.

### ISSUE THREAD

**Issue by ricalenil** [ansible/awx#524]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### ENVIRONMENT
* AWX version: 1.0.1.93
* AWX install method: docker on linux
* Ansible version:  2.4.0.0
* Operating System: UBUNTU 16.04
* Web Browser: Firefox 45.8

##### STEPS TO REPRODUCE

I configured the VMWare source in a new Inventory. It is discovering the VM Guests and creating the groups as configured in the UI.

Then I create a new Job Template using the Hello World playbook of the ansible examples to make sure that all is working.

When I run the job template, it ends successfully, but I get at the output (STDOUT) the following error, impeding it to execute the playbook.

 [WARNING]:  * Failed to parse /tmp/awx_58_88J1ON/inventory with script plugin:
local variable 'err' referenced before assignment
  File "/usr/lib/python2.7/site-packages/ansible/plugins/inventory/script.py", line 99, in parse
    raise AnsibleError("failed to parse executable inventory script results from {0}: {1}\n{2}".format(path, to_native(e), err))

##### EXPECTED RESULTS

This should run without any error.

##### ACTUAL RESULTS

This is the STD OUT...

Identity added: /tmp/awx_58_88J1ON/credential_4 (/tmp/awx_58_88J1ON/credential_4)
ansible-playbook 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Using /etc/ansible/ansible.cfg as config file
 **[WARNING]:  * Failed to parse /tmp/awx_58_88J1ON/inventory with script plugin:
local variable 'err' referenced before assignment
  File "/usr/lib/python2.7/site-packages/ansible/plugins/inventory/script.py", line 99, in parse
    raise AnsibleError("failed to parse executable inventory script results from {0}: {1}\n{2}".format(path, to_native(e), err))**
 [WARNING]:  * Failed to parse /tmp/awx_58_88J1ON/inventory with ini plugin:
/tmp/awx_58_88J1ON/inventory:3: Expected key=value host variable assignment,
got: {all: {hosts: [HOST-1A, HOST-1B, HOST-1C, HOST-1D, HOST-1E]}, _meta:
{hostvars: {HOST-1D: {resourcepool: {_moId: resgroup-827, name: Resources},
alarmactionsenabled: true, configissue: [], tag: [], datastore: [],
triggeredalarmstate: [], layout: {disk: [], swapfile: [HUS150-VOL211]
  File "/usr/lib/python2.7/site-packages/ansible/plugins/inventory/ini.py", line 129, in parse
    self._parse(path, data)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/inventory/ini.py", line 208, in _parse
    hosts, port, variables = self._parse_host_definition(line)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/inventory/ini.py", line 303, in _parse_host_definition
    self._raise_error("Expected key=value host variable assignment, got: %s" % (t))
  File "/usr/lib/python2.7/site-packages/ansible/plugins/inventory/ini.py", line 134, in _raise_error
    raise AnsibleError("%s:%d: " % (self._filename, self.lineno) + message)
 [WARNING]: Unable to parse /tmp/awx_58_88J1ON/inventory as an inventory source
 [WARNING]: No inventory was parsed, only implicit localhost is available
 [WARNING]: Could not match supplied host pattern, ignoring: all
 [WARNING]: provided hosts list is empty, only localhost is available
PLAYBOOK: hello_world.yml ******************************************************
1 plays in hello_world.yml
PLAY [Hello World Sample] ******************************************************
21:00:13
skipping: no hosts matched
PLAY RECAP *********************************************************************
21:00:13

**Comment by ricalenil** [comment]
I found that the issue is when AWX imports the VMWare host variables. Can't tell what value is breaking the script, but maybe someone could help.

**Comment by ricalenil** [comment]
Ok, I solve my issue with the following.

There is a Variable Key that was getting a value that cannot be parsed. The key is **config.vmxconfigchecksum**.

The value that was getting from VCenter was this.. "H%]~7\f0$" and this... "O'Jw\u00188\u0006\b... and for some reason, this was breaking the line. Maybe the \f and \b...

My workarround is to skip that key in the source variables... This is the source variables that I'm using for reference, and maybe this could help someone.

---
validate_certs: False
lower_var_keys: True
alias_pattern: "{{ config.name | lower }}"
host_pattern: "{{ guest.ipaddress }}"
skip_keys: "alarmactionsenabled,layout,resourcepool,capability,config.annotation,config.vmxconfigchecksum,declaredalarmstate,disabledmethod,dynamicproperty,dynamictype,environmentbrowser,managedby,parent,childtype,resourceconfig"

Regardless, this needs further analysis to fix the main script.

**Comment by AlanCoding** [comment]
It's not clear to me that it has anything to do with the \f or \b patterns.

https://github.com/AlanCoding/Ansible-inventory-file-examples/blob/master/scripts/escape/backslash.py

I tried to experiment sending these patterns (using 2.4.0.0) to `ansible-inventory`, and they don't cause problems. If I force it to fail by going through the ini parser (`export ANSIBLE_INVENTORY_ENABLED=ini`), then I get an error that reads differently from yours:

> [WARNING]:  * Failed to parse /Users/alancoding/Documents/repos/ansible-inventory-file-examples/scripts/escape/backslash.py with ini plugin: /Users/alancoding/Documents/repos
/ansible-inventory-file-examples/scripts/escape/backslash.py:3: Expected key=value host variable assignment, got: json

But what really catches my eye here is:

> [WARNING]: * Failed to parse /tmp/awx_58_88J1ON/inventory with script plugin:
local variable 'err' referenced before assignment

NOTE: I have a pretty good idea of what's going on here. The ini plugin throws errors, but it only used the ini plugin because the script plugin failed. These errors from the ini parser are red herrings.

https://github.com/ansible/ansible/blob/stable-2.4/lib/ansible/plugins/inventory/script.py#L98-L99

Reading that code, we should be able to hit that if `stderr` is an empty string (reasonable), but the inventory plugin loader still throws an error. Since Ansible isn't actually printing the error, we don't actually know what error that is, so we can't really hope to address it.

To further debug this, I would ask you to modify the source code of Ansible within your installation, and change:

```python
                except Exception as e:
                    raise AnsibleError("failed to parse executable inventory script results from {0}: {1}\n{2}".format(path, to_native(e), err))
```

to

```python
                except Exception as e:
                    raise AnsibleError("failed to parse executable inventory script results from {0}: {1}\n{2}".format(path, to_native(e), e))
```

**Comment by AlanCoding** [comment]
This is already fixed in `devel` (of Ansible core)

https://github.com/ansible/ansible/commit/cf938e99926a384303c1e291e47770d8f9c74b85

However, it's still not in the `stable-2.4` branch.

For your situation, you can get the full error by upgrading to the development version of Ansible. We won't know what the real issue is until then.

Ansible core also needs to cherry pick this back to 2.4-stable.

**Comment by ricalenil** [comment]
Thanks Alan, I'll try this later and let you know how it goes.

**Comment by AlanCoding** [comment]
@ricalenil the error handling fix made it into the 2.4 branch, I hope it'll be out in 2.4.2

**Comment by 01000101** [comment]
I have a very similar (or likely the same) issue but using the Cloudforms dynamic inventory. I patched the file above to show the full exception variable and here's what I got. 

```
Identity added: /tmp/awx_230_qf0i46/credential_4 (/tmp/awx_230_qf0i46/credential_4)
Using /etc/ansible/ansible.cfg as config file
 [WARNING]:  * Failed to parse /tmp/awx_230_qf0i46/inventory with script
plugin: failed to parse executable inventory script results from
/tmp/awx_230_qf0i46/inventory: Syntax Error while loading YAML.   The error
appears to have been in '/tmp/awx_230_qf0i46/inventory': line 1, column 6435,
but may be elsewhere in the file depending on the exact syntax problem.  The
offending line appears to be:   #! /usr/bin/env python
^ here  exception type: <class 'yaml.scanner.ScannerError'> exception: while
parsing a quoted scalar   in "<unicode string>", line 1, column 6398 found
unknown escape character   in "<unicode string>", line 1, column 6435 Syntax
Error while loading YAML.   The error appears to have been in
'/tmp/awx_230_qf0i46/inventory': line 1, column 6435, but may be elsewhere in
the file depending on the exact syntax problem.  The offending line appears to
be:   #! /usr/bin/env python
^ here  exception type: <class 'yaml.scanner.ScannerError'> exception: while
parsing a quoted scalar   in "<unicode string>", line 1, column 6398 found
unknown escape character   in "<unicode string>", line 1, column 6435
```

For some reason, all new jobs fail with this when using the dynamic inventory source that's been working fine for weeks. I would guess that someone spun up an instance with a name including some odd characters or maybe ManageIQ/Cloudforms itself did this.

**Comment by 01000101** [comment]
I ended up trying to find out if there were non-unicode values being returned by the API (Cloudforms) and found none, so this must be something weird in how AWX is handling the inventory data.  

```
curl -X GET -k --basic -u "admin:*******" "https://xxx.xxx.xxx.xxx/api/vms?offset=0&limit=200&expand=resources" > inventory.json
```

```
nonascii() { LANG=C grep --color=always '[^ -~]\+'; }
cat inventory.json | nonascii
grep -P '[^\x00-\x7f]' inventory.json
```

None of the above returned any values.

**Comment by AlanCoding** [comment]
It would be helpful to get the script output from AWX, which can be found at `/api/v2/inventories/N/script/?hostvars=1`, where N is the inventory with import VMWare contents.

If I have that, then I'll create a mock script that produces the same output and run it through `ansible-inventory`, this will then tell us if the error can be replicated outside of AWX. Then, we can look into what script dumping or loading rules might have been causing the problem.

**Comment by 01000101** [comment]
@AlanCoding I've attached the (partially redacted) inventory list you requested. This is for the Cloudforms one that I'm working with, not the OPs VMware one. Same problem. 
[awx-miq-inventory.json.zip](https://github.com/ansible/awx/files/1503392/awx-miq-inventory.json.zip)

**Comment by 01000101** [comment]
Hey, any updates on this? Thanks!

**Comment by ryanpetrello** [comment]
@ricalenil @01000101 have you given a recent version of awx a try?  Specifically, I'm pretty confident this change should resolve the issues many of you are encountering: https://github.com/ansible/awx/pull/551

**Comment by ryanpetrello** [comment]
This issue is likely another symptom (duplicate) of the problems described in https://github.com/ansible/awx/issues/546 (which have been resolved).

**Comment by matburt** [comment]
closing since no feedback and we think it's fixed
