### ISSUE TITLE
No such file or directory: '/tmp/pip-install-9in3wr7t/awxkit/awxkit/setup.py'

### ISSUE THREAD

**Issue by Mohamed70** [ansible/awx#5240]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I try to install the package such as indicate, using this command:
pip install "https://github.com/ansible/awx/archive/3.0.0.tar.gz#egg=awxkit&subdirectory=awxkit"
But I get this error:
Collecting awxkit
  Downloading https://github.com/ansible/awx/archive/3.0.0.tar.gz
     - 12.9MB 7.3MB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9in3wr7t/awxkit/awxkit/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9in3wr7t/awxkit/awxkit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-9in3wr7t/awxkit/awxkit/pip-egg-info
         cwd: /tmp/pip-install-9in3wr7t/awxkit/awxkit
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-9in3wr7t/awxkit/awxkit/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I looked at the git package, and setup.py is in awx/awxkit/setup.py and not in awx/awxkit/awxkit/setup.py

Can you fix this error, or maybe I'm wrong, so if you can tell me what's the problem.
Thanks

##### ENVIRONMENT
* AWX version: 3.0.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.7.6
* Operating System:
* Web Browser:

**Comment by ryanpetrello** [comment]
The official AWX CLI was introduced in version 7.0.0 of AWX (not prior versions, like 3.0.0 in your URL above).
