### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by ramesh-gundelli** [ansible/awx#5244]
##### ISSUE TYPE
 - This site can’t be reached

##### SUMMARY
Unabl;e to login to ansible tower as i am getting this site cant be reached error messag everytime. Please look into this or suggest me anything. Thanks

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: docker on linux, 
* Ansible version:  X.Y.Z
* Operating System: Red Hat 7
* Web Browser:

##### STEPS TO REPRODUCE

Please suggest me to do the next steps as I am frequently getting this isisue 2 times.

This site can’t be reached *****ip adress*** took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_TIMED_OUT
Check your Internet connection
Check any cables and reboot any routers, modems, or other network devices you may be using.
Allow Chrome to access the network in your firewall or antivirus settings.
If it is already listed as a program allowed to access the network, try removing it from the list and adding it again.
If you use a proxy server…
Check your proxy settings or contact your network administrator to make sure the proxy server is working. If you don't believe you should be using a proxy server: Go to the Chrome menu > Settings > Show advanced settings… > Change proxy settings… > LAN Settings and deselect "Use a proxy server for your LAN".

When I try to login to ansible tower I pasted the URL in chrome, and try to connect it. But the above error is givingme. And also I cloned the code from github but I dint find the tower file in the awx

**Comment by shanemcd** [comment]
Hi, a couple of things:

- If you're using Tower, contact support.
- This sounds like an issue with your environment rather than the app itself. We use GitHub issues for tracking bugs. For help troubleshooting, please go to the [Google Group](https://groups.google.com/forum/#!forum/awx-project) or join [ansible-awx](http://webchat.freenode.net/?channels=ansible-awx) on freenode.
