### ISSUE TITLE
Error starting project failed to register layer: Error processing tar file(exit status 1)

### ISSUE THREAD

**Issue by rcarbajal01** [ansible/awx#5247]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
"Error starting project failed to register layer: Error processing tar file(exit status 1): write /usr/lib64/python2.7/nntplib.py: no space left on device"

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: docker compose
* Ansible version:  2.7.5
* Operating System: RHEL 7
* Web Browser:

##### STEPS TO REPRODUCE

sudo ansible-playbook -i inventory install.yml 

##### EXPECTED RESULTS

Successful build

##### ACTUAL RESULTS

TASK [local_docker : Start the containers] ***********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "errors": [], "module_stderr": "", "module_stdout": "Trying to pull repository registry.access.redhat.com/ansible/awx_web ... \nPulling repository registry.access.redhat.com/ansible/awx_web\nTrying to pull repository docker.io/ansible/awx_web ... \n9.0.1: Pulling from docker.io/ansible/awx_web\nTrying to pull repository registry.fedoraproject.org/ansible/awx_web ... \nPulling repository registry.fedoraproject.org/ansible/awx_web\nTrying to pull repository quay.io/ansible/awx_web ... \nPulling repository quay.io/ansible/awx_web\nTrying to pull repository registry.centos.org/ansible/awx_web ... \nPulling repository registry.centos.org/ansible/awx_web\nTrying to pull repository docker.io/ansible/awx_web ... \n9.0.1: Pulling from docker.io/ansible/awx_web\n", "msg": "Error starting project failed to register layer: Error processing tar file(exit status 1): write /usr/lib64/python2.7/nntplib.py: no space left on device"}
        to retry, use: --limit @/local/mnt/usr2/deployments/awx/installer/install.retry

**Comment by ryanpetrello** [comment]
> write /usr/lib64/python2.7/nntplib.py: no space left on device

You're out of disk space.
This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
