### ISSUE TITLE
Inventory Host List

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5262]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Mockups: https://tower-mockups.testing.ansible.com/patternfly/inventories/inventories-hosts/

Columns:
**Name**: Should link to `#/inventories/:id/hosts/:id/details`
**Sparkline**: Use `summary_fields.recent_jobs`.  Note that the links will be broken until https://github.com/ansible/awx/issues/5236 is addressed.
**Related Groups**: Chips that expose `summary_fields.groups`.  In the existing app we have a show more/less which require an extra REST call on the action.
**Actions**: Includes both the edit button (only visible if user_capabilities.edit) as well as on/off toggle (only enabled if user_capabilities.edit).  Again, see `#/hosts` for reference.

Notes:
1) A lot of `#/hosts` can be reused here.  I'd recommend using that as a reference (note that some things will be different).
2) Ignore the `RUN COMMANDS` button for now - we'll tackle that when we hook up adhoc commands.

**Comment by marshmalien** [comment]
We aren't going to show a related groups tab in this view. To view the related groups a user can navigate to the host detail view and click on the groups sub tab. 

Mockup: https://tower-mockups.testing.ansible.com/patternfly/hosts/hosts-groups/

<img width="673" alt="Screen Shot 2019-11-20 at 2 46 16 PM" src="https://user-images.githubusercontent.com/15881645/69272377-8d37ae00-0ba4-11ea-914c-e33c6506597c.png">
