### ISSUE TITLE
Settings page resets when websocket events occur

### ISSUE THREAD

**Issue by shanemcd** [ansible/awx#5265]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When on a tab on the settings page and a websocket event occurs, user is thrown back to the first tab, losing any unsaved changes.

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: any
* Ansible version:  N/A
* Operating System: macOS 10.14.6
* Web Browser: Safari

##### STEPS TO REPRODUCE

- Go to Settings -> Authentication -> GitHub tab.
- Go to another tab and launch a job
- Go back to the Settings page

##### EXPECTED RESULTS

I should be looking at the tab I was on, with my unsaved changes.

##### ACTUAL RESULTS

Unsaved changes are lost, tossed back to the first tab.

**Comment by jakemcdermott** [comment]
fixed by #5582

**Comment by jakemcdermott** [comment]
#5582

**Comment by dsesami** [comment]
Refreshes do not occur on websocket events on chrome :+1: . Asking around to get this verified on safari.

**Comment by unlikelyzero** [comment]
i'll take it

**Comment by unlikelyzero** [comment]
I was able to make edits on the settings page in an open tab, switch to a new tab and launch a job, and save the edits in on the settings page
