### ISSUE TITLE
Inventory Host Details

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5266]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Mockup: https://tower-mockups.testing.ansible.com/patternfly/inventories/inventories-hosts-detail/
See `/#/hosts/:id/details` for reference.

Note that the existing host details component is missing the **Activity** section which is the Sparkline component displaying jobs from `summary_fields.recent_jobs`.  When added to this details view please add it to the other.

Edit button should be hidden for users without `summary_fields.user_capabilities.edit`
Delete button should be hidden for users without `summary_fields.user_capabilities.delete`
On/Off toggle does not exist in `/#/hosts/:id/details` currently.  When built for this view please add it to that other view.

**Comment by AlexSCorey** [comment]
This issue was addressed by https://github.com/ansible/awx/pull/5180
