### ISSUE TITLE
Inventory Groups List

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5267]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Mockups: https://tower-mockups.testing.ansible.com/patternfly/inventories/inventories-hosts/

Columns:
**Status**: This requires some discussion.
**Name**: Should link to `#/inventories/:id/groups/:id/details`
**Actions**: Includes the edit button (only visible if user_capabilities.edit)

Notes:
1) ALL GROUPS/ROOT GROUPS toggle should be included as part of this work.  ALL GROUPS: `/api/v2/inventories/:id/groups/`.  ROOT GROUPS: `/api/v2/inventories/:id/root_groups`
2) Deleting groups is a bit different from deleting other resources.  Deleting a group with other groups in it gives the user a few options:

<img width="1512" alt="Screen Shot 2019-11-06 at 10 21 12 AM" src="https://user-images.githubusercontent.com/9889020/68311200-377ce500-007f-11ea-9ea0-32643c4919c2.png">

We'll probably want to roll a new component specifically for deleting inventory groups.

3) Ignore the `RUN COMMANDS` button for now - we'll tackle that when we hook up adhoc commands.

**Comment by marshmalien** [comment]
Proposed Inventory Groups UX-Flow
![Groups WireFlow@1 5x](https://user-images.githubusercontent.com/15881645/69569430-a3ba7c80-0f8b-11ea-969a-1a5a1eebf219.png)

**Comment by appuk** [comment]
Adding test stubs to cover the Group Deletion Scenarios here: https://github.com/ansible/awx/issues/5267
