### ISSUE TITLE
Inventory Group Add Form

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5268]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Mockup: https://tower-mockups.testing.ansible.com/patternfly/inventories/inventories-groups-add/

Fields:
**Name**: Required, text
**Description**: text
**Variables**: codemirror (See host form for example)

**Comment by appuk** [comment]
Inventory Group Creation works correctly as expected, hence closing.
