### ISSUE TITLE
Inventory Group Edit Form

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5269]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Mockups: https://tower-mockups.testing.ansible.com/patternfly/inventories/inventories-groups-edit/
See: https://github.com/ansible/awx/issues/5268

**Comment by appuk** [comment]
Inventory Group Edit works as expected, verified the edit functionality on all the fields, hence closing the issue.
