### ISSUE TITLE
One out of many hosts being unreachable shows as the whole job failing

### ISSUE THREAD

**Issue by mkempster22** [ansible/awx#527]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
Running a playbook across a number of hosts and having any of them fail for ssh reasons counts the whole job as a failure.

##### ENVIRONMENT
* AWX version:  1.0.1.10 
* AWX install method: docker on linux
* Ansible version: 2.4.0
* Operating System: RHEL 6.9
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Although the mentioned behavior being how its designed and useful in many situations, Having the whole job show up as a failure because one or more hosts out of hundreds failed due to SSH shows up as a failure in the overview, This seems a bit misleading to anyone wanting an overview of whats failed as some ssh failures can be expected. It would be nice to have an option in the creation of a job template to ignore allow ssh failures to be ignored.
Similar to the ansible configuration option that allows you to define a percentage of ssh failures before the playbook stops, having it be an amount of hosts allowed to be unreachable before the job shows up red.

Use case example: On a playbook for adding a user to all Linux boxes in an estate having it fail on a couple of test boxes that aren't in AD properly therefore cannot be reached via SSH would be expected and although they should show up at the end in red having the whole job show up as a failure isn't accurate

Any thoughts?

**Comment by wenottingham** [comment]
This is how Ansible works... we're investigating things like relaunching on failed hosts (see #219), but we're not going to create new concepts in Tower.

Is it not respecting `max_fail_percentage` for you?

**Comment by mkempster22** [comment]
Thanks for the reply. Sorry I may have not worded that the best way, When I say it fails it doesn't fail in the way that it will stop the run of the job, having max_fail_percentage would be useful for that. I mean that once its done it says the job is a failure in the job's results page and in the graph on the dashboard etc. will also be a red dot in the list of jobs, although all tasks were actually done.
This is misleading to someone checking over jobs that have been scheduled then it looking like the whole thing stopped and didn't run or perform properly when actually it did complete and perform the tasks on the hosts just maybe one host had an ssh failure.

I have looked into clearing task errors, but from what I can tell this will also clear legitimate failures as well meaning the job will fail even if all hosts had actual serious failures

**Comment by wenottingham** [comment]
Sorry about coming back to this so late - this really is expected behavior; anywhere we list a single status for a playbook run, it's going to be based off the `ansible-playbook` exit code, which is going to be "failure" when a host fails absent other configuration.
