### ISSUE TITLE
Inventory Group Details

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5271]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Mockup: https://tower-mockups.testing.ansible.com/patternfly/inventories/inventories-groups-detail/

Fields:
**Name**
**Description**
**Variables**
**Created**
**Last Modified**

Notes:
1) Edit button should be hidden for users without `user_capabilities.edit`
2) Delete button should be hidden for users without `user_capabilities.delete`
3) Extra note about deleting a group:  See https://github.com/ansible/awx/issues/5267.  Groups have custom logic on delete that allows the user to promote or cascade delete child groups and hosts.  We'll want to follow the same pattern here/use the same delete modal component.

**Comment by appuk** [comment]
Verified all the fields on Inventory Details page and created stubs for automating the tests.
