### ISSUE TITLE
Credential List

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5273]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Mockups: https://tower-mockups.testing.ansible.com/patternfly/creds/creds/

Columns:
**Name**: Link to `/#/credentials/:id/details`
**Kind**: This column is a little bit tricky.  Kind name actually comes from `/api/v2/credential_types`.  All we have on the credential is a `credential_type` id.  In order to populate this list we currently make a targeted request to the credential_types endpoint to get all those credential types and then map the name to the Kind column.  It's probably best to go over to the old app and look at how this works before attempting to add this column.
**Owners**: Again, the best thing to do to understand how owners works will be to look at the old app.  The directive that handles this particular area can be found [here](https://github.com/ansible/awx/blob/devel/awx/ui/client/src/credentials/ownerList.directive.js).  At a high level, credentials can be owned by users, orgs, and/or teams.  This data comes from the `summary_fields.owners` field.
**Actions**: Edit

Notes:

1) Edit icon should be hidden for users without `user_capabilities.edit`
2) Delete: Deleting a credential has the possibility to impact some resources that rely on that particular credential.  See the following screenshot:
<img width="1536" alt="Screen Shot 2019-11-06 at 11 23 27 AM" src="https://user-images.githubusercontent.com/9889020/68316772-0228c500-0088-11ea-9724-fc94d0760d47.png">

**Comment by dsesami** [comment]
@marshmalien this is marked as closed in the project but surprisingly GH doesn't close the issue as well. would you like it closed?

**Comment by marshmalien** [comment]
Yes, I'll close it 👍
