### ISSUE TITLE
Credential Add Form

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5274]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Mockups: to come

Fields for all credential types:
**Name**: Required, text
**Description**: text
**Organization**: single select lookup
**Credential Type**: Required, single select lookup (this triggers the subform)

Notes:
1) For this iteration of the form we're only going to support two credential types
- Machine
  - Subform Fields:
<img width="1484" alt="Screen Shot 2019-11-06 at 11 42 22 AM" src="https://user-images.githubusercontent.com/9889020/68318293-89773800-008a-11ea-9d00-56d694bbc32c.png">

- Source Control
  - Subform Fields:
<img width="1485" alt="Screen Shot 2019-11-06 at 11 42 54 AM" src="https://user-images.githubusercontent.com/9889020/68318324-98f68100-008a-11ea-96fc-ae2ff1cb70c3.png">
2) About these subform fields - the intention is not to support credential plugins at this time so we don't need to build lookups into all of these fields in this first iteration.  Users will need to provide all fields manually.

**Comment by appuk** [comment]
Verified the form and field validation, and everything is working as expected, hence closing the issue
