### ISSUE TITLE
Credential Details

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5276]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Mockups: to come

All credentials will have the potential for name/description/org/type fields.  After that the fields vary based on the type of credential.  It'll be best to reference the form fields when trying to figure out what should be shown in the details view.

Notes:
1) Edit button should be hidden for users without summary_fields.user_capabilities.edit
2) Delete button should be hidden for users without summary_fields.user_capabilities.delete
3) Delete action can potentially impact resources that reference this credential (like JTs).  The delete confirmation modal is a bit different from our generic delete.  See #5273 for more info.

**Comment by dsesami** [comment]
note: @marshmalien has created https://github.com/ansible/awx/issues/5546 to establish a pattern for deleting resources with dependencies.

**Comment by dsesami** [comment]
Items tested:
- [x] Created a credential and ensured all fields display normally.
- [x] All encrypted fields stay encrypted.
- [x] Deleting a user that created a credential simply omits the "modified by" section of the credential information.
- [x] Edit and Delete buttons are only visible to users with write/delete access.
- [x] Responsiveness of the details page when changing window size.
- [ ] ~Credentials with linked job templates warn the user of linkage~ (separate issue: https://github.com/ansible/awx/issues/5546)

**Comment by dsesami** [comment]
closing out as #5546 is separate.
