### ISSUE TITLE
selecting multiple vault credentials with the same description fails

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#5277]
##### ISSUE TYPE
 - Bug Report

##### STEPS TO REPRODUCE
Create two vault creds with the same description.  Try to assign both to a job template in UI and save

##### EXPECTED RESULTS

It works!

##### ACTUAL RESULTS

It doesn't work, api has failure

---

@AlexSCorey has more info

**Comment by AlanCoding** [comment]
do you mean the same vault id? the vault id is mutually exclusive.

**Comment by jakemcdermott** [comment]
cc @AlexSCorey Any thoughts on Alan's questions above?

**Comment by wenottingham** [comment]
Closing per bug scrub comments.
