### ISSUE TITLE
self-buildign awx images should not require running as root

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx#5280]
##### ISSUE TYPE
Privilege issue

##### SUMMARY
I'm installing AWX with self built images, and the clean distribution step fails unless the playbook is run as root, if you run it on a computer that has already been used for this.

##### ENVIRONMENT
* AWX version: any, pretty much
* AWX install method: docker on linux with self built images
* Ansible version:  2.8
* Operating System: openSUSE Leap 15.1

##### STEPS TO REPRODUCE

check out the awx and awx-logos repositories
edit the inventory file so that the logos get included and images are built locally
run the installation, but cancel it at some stage after the start of building images
run it again, observe it failing to clean up the mess from the first pass
run it again but as root with sudo, observe it cleaning up properly

##### EXPECTED RESULTS

the installation should be able to clean up leftovers from a previous pass without root permissions

##### ACTUAL RESULTS

the installer can only clean up if run as root

**Comment by shanemcd** [comment]
I don't think this is relevant anymore since we build the sdist inside of the image (in a build stage).
