### ISSUE TITLE
awx_web:9.0.1 docker image - forgotten nginx config

### ISSUE THREAD

**Issue by roman-vynar** [ansible/awx#5281]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Upgraded AWX from 7.0.0 to 9.0.1.

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: docker

##### ACTUAL RESULTS

```
root@macaque.corp:~# docker run --rm -ti ansible/awx_web:9.0.1 bash
bash-4.4$ cat /etc/nginx/nginx.conf
# For more information on configuration, see:
#   * Official English Documentation: http://nginx.org/en/docs/
#   * Official Russian Documentation: http://nginx.org/ru/docs/

user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;

    server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  _;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }

# Settings for a TLS enabled server.
#
#    server {
#        listen       443 ssl http2 default_server;
#        listen       [::]:443 ssl http2 default_server;
#        server_name  _;
#        root         /usr/share/nginx/html;
#
#        ssl_certificate "/etc/pki/nginx/server.crt";
#        ssl_certificate_key "/etc/pki/nginx/private/server.key";
#        ssl_session_cache shared:SSL:1m;
#        ssl_session_timeout  10m;
#        ssl_ciphers PROFILE=SYSTEM;
#        ssl_prefer_server_ciphers on;
#
#        # Load configuration files for the default server block.
#        include /etc/nginx/default.d/*.conf;
#
#        location / {
#        }
#
#        error_page 404 /404.html;
#            location = /40x.html {
#        }
#
#        error_page 500 502 503 504 /50x.html;
#            location = /50x.html {
#        }
#    }

}
```
There are no other nginx vhost config mentioning port 8050-8052 in the image.

So it was forgotten to put the correct nginx.conf into the image.

##### ADDITIONAL INFORMATION

What I did is - just copied the content of nginx.conf from https://raw.githubusercontent.com/ansible/awx/987cfed6493d73dfcfca2dc6cc7b6d84b2247204/installer/roles/image_build/templates/nginx.conf.j2 and removed jinja conditions and it worked.

**Comment by ingvaldlorentzen** [comment]
I'm experiencing the same issue with AWX `9.0.1` in OpenShift `3.11.16`

Was not an issue with AWX `8.0.0` and `7.0.0` in the exact same environment. 

##### ENVIRONMENT
* AWX version: 9.0.0
* AWX install method: OpenShift manual deployment

**Comment by shanemcd** [comment]
Please ensure that you're using the version of the installer that corresponds to the image you are trying to run. Both local docker and OpenShift now render this out on the host and bind-mount it inside of the web container.

**Comment by roman-vynar** [comment]
Installer?
I was just stopping and starting a new container using the newer image as I was always doing since version 1.0.0 and I had no problems with that.

**Comment by shanemcd** [comment]
You seem to be having problems now. Try reading the docs: https://github.com/ansible/awx/blob/devel/INSTALL.md#docker-compose

**Comment by roman-vynar** [comment]
I am not building my own image, I am using your pre-built images 
```
ansible/awx_task                 9.0.1                      7e755bfd9495        2 days ago          1.96GB
ansible/awx_web                  9.0.1                      52af39e9910f        2 days ago          1.93GB
```
Why do I need to build an image as you pointed me to?

Again, there was no problem with upgrades between 1.0.0 > 2.0.0 > 3.0.0 > 4.0.0 > 5.0.0 > 6.0.0 > 7.0.0 and now you are saying to read the docs which haven't been changed since that?

DB migrations are run ok by the way automatically.

Please re-open this issue and provide the docs on how to upgrade awx image if the procedure is different than it was before.

**Comment by shanemcd** [comment]
The process is not different and I did not link you to docs that say you need to build your own image. Those docs would be [here](https://github.com/ansible/awx/blob/devel/INSTALL.md#official-vs-building-images). If you got lucky up until now that's cool, but have always needed to re-run the install.yml playbook to upgrade between versions.

**Comment by zx1986** [comment]
I am using the "official" image for our helm chart, what v9.0.0 (and v9.0.1) did were so unfriendly for Kubernetes.
Why I need to run install.yml or re-build if there was a working "official" image?
