### ISSUE TITLE
implement management.csp.policy into Ansible Tower's implementation of RabbitMQ

### ISSUE THREAD

**Issue by agilleyrh** [ansible/awx#5289]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
port 15672 (RabbitMQ management port) can be viewed as vulnerable due to missing http header security.  This could be addressed by adding " management.csp.policy = frame-ancestors 'none' "

**Comment by ryanpetrello** [comment]
Sounds like a good opportunity for a pull request :)

**Comment by wenottingham** [comment]
I would note that we do not recommend turning this on in general except for specific debugging, and it may go away in the future.

**Comment by ryanpetrello** [comment]
Closing this issue, as we're removing AWX's usage of RabbitMQ entirely (see: https://github.com/ansible/awx/issues/5443)
