### ISSUE TITLE
Add Underlying Python Version to About Section

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/awx#5290]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Add the python version used to run the underlying AWX/Tower environment

**Comment by wenottingham** [comment]
What's the use case here - it should be fairly constant? (either the system 3.x from EL8, or the scl 3.x from EL7).

**Comment by wenottingham** [comment]
Closing this - there is not a real usage case for this.
