### ISSUE TITLE
Set User-Agent on Analytics Upload POST

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/awx#5294]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

The User-Agent header is set on each request to inform the server about what type of client it is communicating with.  In this case, we are not yet setting User-Agent for analytics upload requests yet.  

We should do, and it should look something like the following:

```
User-Agent: AnsibleTower/3.6.0}
```

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by kdelee** [comment]
LGTM. I fiddled around with sending the analytics manually but could not really introspect into the request, neither do I have access to ingress service so could not really see that either. Do you have any suggestions for testing? 

Is this going to get backported to any prior releases?

**Comment by rooftopcellist** [comment]
@kdelee I don't have access to the ingress service either, but we could check to make sure it is in the request header.  Though the only real way I can think of to do that is to run the `ship()` method in something like `shell_plus` and set a `pdb.set_trace()` in that section of code, then introspect the request object after it has been created to look at the headers.

**Comment by rooftopcellist** [comment]
@benthomasson Would you be able to look at the header from the automation analytics side?

**Comment by kdelee** [comment]
Got access to logs from ingress service, can confirm that User Agent is getting set from devel instances
![Screenshot from 2020-01-21 13-30-12](https://user-images.githubusercontent.com/29239279/72835131-24c68500-3c58-11ea-951c-15fc270d0c01.png)
