### ISSUE TITLE
Lacking line wrap in Events detailed view

### ISSUE THREAD

**Issue by tvo318** [ansible/awx#5299]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Action description in Event details window does not wrap correctly.

##### ENVIRONMENT
* Tower version: 3.6.0 
* AWX install method: yolo #6631: Instance URL - https://ec2-34-238-249-200.compute-1.amazonaws.com  
* Ansible version:  2.10.0.dev0
* Operating System: Mac Mojave 10.14.6
* Web Browser: Version 78.0.3904.87 (Official Build) (64-bit)

##### STEPS TO REPRODUCE
1. Go to Activity Stream
2. Expand an event with long name

##### EXPECTED RESULTS
Expected to see word wrap be readable

##### ACTUAL RESULTS

Name doesn't wrap right, making the text difficult to read.
![image](https://user-images.githubusercontent.com/7514801/68625709-0c3b3100-0497-11ea-9018-55021f912c08.png)

##### ADDITIONAL INFORMATION
See above

**Comment by wenottingham** [comment]
We'll look at this after/during the awx-pf rewrite.

**Comment by jlmitch5** [comment]
Note, I'm not entirely sure if this is fixed, but the strream detail view description line is full width in a much wider modal.  It does still wrap when necessary, but I think that is inevitable.

![Screen Shot 2021-01-14 at 12 41 34 PM](https://user-images.githubusercontent.com/1342624/104628274-08400b80-5666-11eb-93ee-8c89cd6d41a0.png)
