### ISSUE TITLE
Clicking on inventory name in activity stream navigates to home

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#530]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
If I click on an inventory name in the activity stream it takes me to the homepage, not the inventory page.

##### ENVIRONMENT
* AWX version: 1.1.0
* AWX install method: docker for mac
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Navigate to the INVENTORIES tab. Click on the graph icon to get the activity stream for inventories. On the entry an inventory creation, click on the name of the inventory.

##### EXPECTED RESULTS
Redirected to inventory page.

##### ACTUAL RESULTS
Redirected to dashboard.

##### ADDITIONAL INFORMATION
N/A

**Comment by jaredevantabor** [comment]
this is fixed in devel now
