### ISSUE TITLE
Unable to authenticate via AD in multi domain env 

### ISSUE THREAD

**Issue by markatdxb** [ansible/awx#5300]
##### ISSUE TYPE
 - Feature Idea
Hello, 
apparently there is no possibility to authenticate to AWX via LDAP in multi domain environment when the same account exists in more than 1 domain. 
example we have :
domain1/awx_admin
domain2/awx_admin

unfortunately for some specific reasons we need to have some users having multiple accounts in more than 1 domain
Any plans to improve this in future release ?
cheers
Marek

**Comment by wenottingham** [comment]
This would require significant changes to how we do LDAP authentication with the libraries that we use, it is unlikely to happen.

**Comment by markatdxb** [comment]
Thanks for info
