### ISSUE TITLE
Clicking on links in UI during active session doesn't redirect to migration page

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#5302]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
If AWX goes into a migrating state, the UI doesn't take me there.

##### ENVIRONMENT
* AWX version: 9.0.1
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Login and go to the jobs page, keep tab open

do `awx-manage migrate N-1` in terminal

click on job in jobs page

##### EXPECTED RESULTS

Redirected to the migration polling page.

##### ACTUAL RESULTS

![Screen Shot 2019-11-11 at 11 09 35 PM](https://user-images.githubusercontent.com/1385596/68641485-fe0e0480-04d8-11ea-8480-0a0d0c1abd86.png)
![Screen Shot 2019-11-11 at 11 10 21 PM](https://user-images.githubusercontent.com/1385596/68641486-fe0e0480-04d8-11ea-9bab-556b6ef79d6f.png)

##### ADDITIONAL INFORMATION

Navigating back to the base URL does redirect

**Comment by wenottingham** [comment]
We don't intend to address this at this time.
