### ISSUE TITLE
RFE: Flagging users as superusers and auditors in SAML integration

### ISSUE THREAD

**Issue by IshwarKanse** [ansible/awx#5303]
##### ISSUE TYPE
Feature request for flagging users as superusers and auditors in SAML integration, similar to LDAP implementation.

**Comment by wenottingham** [comment]
This would probably be an addition to the attribute mapping.

**Comment by mattschwen** [comment]
This is something I am unable to get working and need to do as well.

**Comment by CoolZeroNL** [comment]
Any progress on this issue?

**Comment by justinokay** [comment]
I just opened a case with RedHat and they directed me to this RFE. As of today here is their latest response. The solutions link requires a RH customer account.

> We currently have an existing RFE to allow setting superuser and other similar roles via SAML mapping here: https://github.com/ansible/awx/issues/5303
Unfortunately, we do not have a timeline for when this feature will be implemented. We encourage you to comment on that issue and engage with our engineering team to provide any additional use-case or information you or they may find pertinent to this feature request. Often times the more activity an issue receives, the more likely it is to be implemented. You can review our full RFE process here: https://access.redhat.com/solutions/3446781

**Comment by blaira89** [comment]
My TAM customer would like to add to this request that this get serviced in a release soon. Thanks.

**Comment by balonik** [comment]
I would like to have this, it is really required to have a meaningful SAML integration.

**Comment by hockeygoonnorm** [comment]
RedHat Support referred me to this RFE after opening a case asking how to map SAML users/groups to Tower superusers and auditors. This really is a critical component for any organization that requires single sign-on for all apps.

**Comment by DE110283** [comment]
Voting for this! This is needed urgently!

**Comment by john-westcott-iv** [comment]
Development Task List
- [x] Modify SSO pipeline for setting user flags
- [x] Add new SAML setting for flag name, flag value and role names
- [x] Modify code to favor settings
- [x] Modify awx.sso.pipeline logger to respect DEBUG setting in logging aggregator
- [x] Add Org Admins by SAML attribute
- [x] Create unit tests
- [x] Add `KEYCLOAK=True make docker-compose` option to spin up a plumbed IdP w/ AWX for dev
- [x] Modify Tower SAML documentation
- [ ] Create integration tests

**Comment by ledgley** [comment]
RedHat support referred me to this RFE after raising a case today. RedHat case 03095152.

Our specific requirement is flagging Org Admins by SAML attribute (AD group under 'roles' attribute), so Org can manage their own admins via AD.

**Comment by john-westcott-iv** [comment]
**Acceptance Criteria:**

- [x] SAML users should be able to log into AWX with the is_superuser and is_system_auditor flags set based on SAML attributes and/or roles.
- [x] AWX developers should have documentation on how to setup a SAML provider with their AWX instance (for future development and testing)

**Comment by akus062381** [comment]
@shanemcd do you know if we can close this...?

**Comment by akus062381** [comment]
https://github.com/ansible/awx/pull/11798

**Comment by akus062381** [comment]
confirmed with @john-westcott-iv, we are good to close this one
