### ISSUE TITLE
AWX installer fails when using CRC 1.1.0 (SCC privileges failure)

### ISSUE THREAD

**Issue by ffirg** [ansible/awx#5306]
##### ISSUE TYPE

Can't install AWX 9.0.1 using a non-kubeadmin account despite having cluster-admin rights.

##### SUMMARY

I've raised this has a potential bug against CRC as well : 
https://github.com/code-ready/crc/issues/804

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: CRC 1.1.0 (local Mac install)
* Ansible version:  2.9.0
* Operating System: Mac OS X 10.14.6 BuildVersion:18G1012
* Web Browser: Chrome Version 78.0.3904.97

##### STEPS TO REPRODUCE

Used this to grant cluster-admin rights to the developer account and test:

$ oc login -u kubeadmin -p e4FEb-9dxdF-9N2wH-Dj7B8 https://api.crc.testing:6443
Login successful.

You have access to 52 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "awx".
MacBook-Pro:installer pgriffit$ oc adm policy add-role-to-user cluster-admin developer
clusterrole.rbac.authorization.k8s.io/cluster-admin added: "developer"
MacBook-Pro:installer pgriffit$ oc logout
Logged "kube:admin" out on "https://api.crc.testing:6443"
MacBook-Pro:installer pgriffit$ oc login -u developer -p developer https://api.crc.testing:6443
Login successful.

You have access to the following projects and can switch between them with 'oc project ':

awx
default
Using project "awx".
MacBook-Pro:installer pgriffit$ oc adm policy add-scc-to-user privileged system:serviceaccount:awx:awx
Error from server (Forbidden): securitycontextconstraints.security.openshift.io "privileged" is forbidden: User "developer" cannot get resource "securitycontextconstraints" in API group "security.openshift.io" at the cluster scope
MacBook-Pro:installer pgriffit$ oc get scc
Error from server (Forbidden): securitycontextconstraints.security.openshift.io is forbidden: User "developer" cannot list resource "securitycontextconstraints" in API group "security.openshift.io" at the cluster scope

$ ansible-playbook -i inventory install.yml -e openshift_password=developer  -e docker_registry_password=$(oc whoami -t)

TASK [kubernetes : Set postgresql service name] **********************************************************************************
task path: /Users/pgriffit/awx/installer/roles/kubernetes/tasks/openshift.yml:27
ok: [localhost] => {"ansible_facts": {"postgresql_service_name": "postgresql"}, "changed": false}

TASK [kubernetes : Add privileged SCC to service account] ************************************************************************
task path: /Users/pgriffit/awx/installer/roles/kubernetes/tasks/openshift.yml:32
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "oc --config=/tmp/awx-config/.kube/config adm policy add-scc-to-user privileged system:serviceaccount:awx:awx\n", "delta": "0:00:00.077235", "end": "2019-11-12 10:55:44.210280", "msg": "non-zero return code", "rc": 1, "start": "2019-11-12 10:55:44.133045", "stderr": "Error from server (Forbidden): securitycontextconstraints.security.openshift.io \"privileged\" is forbidden: User \"developer\" cannot get resource \"securitycontextconstraints\" in API group \"security.openshift.io\" at the cluster scope", "stderr_lines": ["Error from server (Forbidden): securitycontextconstraints.security.openshift.io \"privileged\" is forbidden: User \"developer\" cannot get resource \"securitycontextconstraints\" in API group \"security.openshift.io\" at the cluster scope"], "stdout": "", "stdout_lines": []}

PLAY RECAP ***********************************************************************************************************************
localhost                  : ok=14   changed=2    unreachable=0    failed=1    skipped=49   rescued=0    ignored=0

##### EXPECTED RESULTS

A CRC account with cluster-admin rights should be able to install. 

##### ACTUAL RESULTS

See above.

##### ADDITIONAL INFORMATION

Failure comes from /Users/pgriffit/awx/installer/roles/kubernetes/tasks/openshift.yml:32

Here's what I've got in my installer/inventory file:

$ grep -vE '^$|^#' inventory
localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python"
[all:vars]
dockerhub_base=ansible
openshift_host=192.168.64.3:6443
openshift_project=awx
openshift_user=developer
openshift_skip_tls_verify=True
openshift_pg_emptydir=True
awx_task_hostname=awx
awx_web_hostname=awxweb
postgres_data_dir="~/.awx/pgdocker"
host_port=80
host_port_ssl=443
docker_compose_dir="~/.awx/awxcompose"
pg_username=awx
pg_password=awxpass
pg_database=awx
pg_port=5432
pg_admin_password=postgrespass
rabbitmq_password=awxpass
rabbitmq_erlang_cookie=cookiemonster
admin_user=admin
admin_password=password
create_preload_data=True
secret_key=awxsecret

**Comment by praveenkumar** [comment]
As a workaround from crc side make sure use `--as system:admin` for all the commands when using the `developer` user.

**Comment by shanemcd** [comment]
This is not an AWX bug.

```
User "developer" cannot get resource "securitycontextconstraints" in API group "security.openshift.io" at the cluster scope"
```

**Comment by ffirg** [comment]
Agreed not an AWX bug but stops it installing potentially, hence why it was raised on here for others information. I referenced the CRC/OCP bug issue as well so people know what the problem is.
