### ISSUE TITLE
Password issue with SVN

### ISSUE THREAD

**Issue by ghost** [ansible/awx#533]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY

It is not possible to check out a SCM URL using subversion because the password is not correctly placed into the command string that runs.

##### ENVIRONMENT
- AWX version:  1.0.1.120
- AWX install method: docker on linux
 - Ansible version:  2.4.1.0
- Operating System: Centos 7.4
- Web Browser: 52.4.0 (64-bit)

##### STEPS TO REPRODUCE

- Create a new credentials(Source Control)
- Double check username/password

- Create a new project using the created credentials
- Start an SCM update

At this point it will fail.

##### EXPECTED RESULTS

Correctly checking out the repository

##### ACTUAL RESULTS

TASK [update project using svn with auth] ************************************** fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/svn --non-interactive --trust-server-cert --no-auth-cache --username testUser --password '********' checkout -r HEAD https://test.test.com/test/ /var/lib/awx/projects/_6__linuxtest", "failed": true, "msg": "svn: E170001: Unable to connect to a repository at URL 'https://test.test.com/test/'\nsvn: E170001: OPTIONS of 'https://test.test.com/test/': authorization failed: Could not authenticate to server: rejected Basic challenge (https://test.test.com)", "rc": 1, "stderr": "svn: E170001: Unable to connect to a repository at URL 'https://test.test.com/test/'\nsvn: E170001: OPTIONS of 'https://test.test.com/test/': authorization failed: Could not authenticate to server: rejected Basic challenge (https://test.test.com/test/)\n", "stderr_lines": ["svn: E170001: Unable to connect to a repository at URL 'https://test.test.com/test/'", "svn: E170001: OPTIONS of 'https://test.test.com/test/': authorization failed: Could not authenticate to server: rejected Basic challenge (https://test.test.com/test/)"], "stdout": "", "stdout_lines": []}

##### ADDITIONAL INFORMATION

When you run the command in the shell of the docker container and replace the password manually it successfully checks out the folder. 

```
svn --non-interactive --trust-server-cert --no-auth-cache --username testUser --password 'manuallyTypedPassword' checkout -r HEAD https://test.test.com/test/
```

All the auth caches have been cleared. I think that it may not correctly be escaping the password or something similar?

**Comment by wenottingham** [comment]
What sort of non-alphanumeric characters are in the password, if you're willing to say?

**Comment by yader-sasha** [comment]
I don't understand what you mean.

31 Окт 2017 г. 17:22 пользователь "Bill Nottingham" <
notifications@github.com> написал:

**Comment by matburt** [comment]
Are you using something other than `[a-zA-Z0-9]` as your password?

**Comment by yader-sasha** [comment]
Why I need to answer this question? All I did was reset my password. And I
don't know what is the problem with that. I did it several times, and
receive only notifications.

31 Окт 2017 г. 18:45 пользователь "Matthew Jones" <notifications@github.com>
написал:

**Comment by ghost** [comment]
Yes. For example a password could be:
testpassword!!@#!@$%$!@#$%

passwords can contain any ASCII char 32-126
http://www.asciitable.com/

I have tested a password containing only letters and numbers: test123
This password successfully checks out the repository through AWX.

The password that fails is for example: test123#

**Comment by matburt** [comment]
My next question would be what is the behavior using the ansible svn module by itself: http://docs.ansible.com/ansible/latest/subversion_module.html

**Comment by ghost** [comment]
---
- hosts: localhost
  tasks:
  - subversion:
      repo: https://test.test.com/test/
      dest: /root/testing/svncheckout
      username: testUser
      password: testPassword#
      

``
ansible-playbook -i "localhost," -c local svntest.yml
``

This works when I pass the password  as shown above

> testPassword#



[root@awx testing]# ansible-playbook -i "localhost," -c local svntest.yml

PLAY [localhost] ***************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************
ok: [localhost]

TASK [subversion] **************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP *********************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0

**Comment by matburt** [comment]
and to be clear, the password containing `#` does not work on AWX?

**Comment by ghost** [comment]
That is correct the password containing `#` does NOT work on AWX.

Working Passwords for AWX SCM update:
* test
* test123

NOT working passwords for for AWX SCM update:
* test!
* test123!
* test123#

Working passwords for ansible svn module run via playbook outside of AWX as shown above:
* test123
* test123!
* test123#

All these attempts have been on the same SCM URL. They have also been run as the same user on the same machine(inside awx_task docker). Is there anything else that I could test for locally?

**Comment by matburt** [comment]
It might have to do with our use of `|quote` here.  Can you try removing that and seeing if it works for you?

**Comment by ghost** [comment]
password: "{{scm_password|quote}}"

From the svn section in project_update.yml?

**Comment by matburt** [comment]
ping did you ever try this?

**Comment by wwitzel3** [comment]
@mlobbia were you ever able to try that `password: "{{scm_password|quote}}"` line without `|quote` ?

**Comment by wenottingham** [comment]
Closing, please reopen if you can provide the information needed.
