### ISSUE TITLE
AWX installation error on 9.0.1 and 9.0.0 versions on centos 7

### ISSUE THREAD

**Issue by tamilbabuece** [ansible/awx#5331]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

error i am getting while installing awx on centos:
failed: [localhost] (item=environment.sh) => {
    "changed": false,
    "item": "environment.sh",
    "msg": "AnsibleError: Unexpected templating type error occurred on (DATABASE_USER={{ pg_username|quote }}\nDATABASE_NAME={{ pg_database|quote }}\nDATABASE_HOST={{ pg_hostname|default('postgres')|quote }}\nDATABASE_PORT={{ pg_port|default('5432')|quote }}\nDATABASE_PASSWORD={{ pg_password|default('awxpass')|quote }}\n{% if pg_admin_password is defined %}\nDATABASE_ADMIN_PASSWORD={{ pg_admin_password|quote }}\n{% endif %}\nMEMCACHED_HOST={{ memcached_hostname|default('memcached') }}\nMEMCACHED_PORT={{ memcached_port|default('11211')|quote }}\nRABBITMQ_HOST={{ rabbitmq_hostname|default('rabbitmq')|quote }}\nRABBITMQ_PORT={{ rabbitmq_port|default('5672')|quote }}\nAWX_ADMIN_USER={{ admin_user|quote }}\nAWX_ADMIN_PASSWORD={{ admin_password|quote }}\n): 'int' object is not iterable"
}
l

While trying to install latest version (9.0.1) (9.0.0) of AWX on centos 7 getting this error ,wherein the same thing working when i use 8.0.0 version

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: docker
* Ansible version:  2.4.2
* Operating System: centos 7
* Web Browser: chrome

**Comment by zbenta** [comment]
I also had that issue, I updated to ansible 2.9.0 and solved it.

**Comment by tamilbabuece** [comment]
Thanks for the reply @wenottingham.

Would it be possible to share the commands which used to install AWX

**Comment by RodrigoAravena** [comment]
which version of python do you have? can you have a manual of step for step of installation? regards.

**Comment by zbenta** [comment]
I solved the issue by updating to python 3.6.

Cumprimentos / Best Regards,
Zacarias Benta

**Comment by chyap1981** [comment]
TASK [local_docker : Create Docker Compose Configuration] *********************************************************************************************************************************************************
task path: /home/cheehow/awx/installer/roles/local_docker/tasks/compose.yml:13
failed: [localhost] (item=environment.sh) => {"changed": false, "item": "environment.sh", "msg": "AnsibleError: Unexpected templating type error occurred on (DATABASE_USER={{ pg_username|quote }}\nDATABASE_NAME={{ pg_database|quote }}\nDATABASE_HOST={{ pg_hostname|default('postgres')|quote }}\nDATABASE_PORT={{ pg_port|default('5432')|quote }}\nDATABASE_PASSWORD={{ pg_password|default('awxpass')|quote }}\n{% if pg_admin_password is defined %}\nDATABASE_ADMIN_PASSWORD={{ pg_admin_password|quote }}\n{% endif %}\nMEMCACHED_HOST={{ memcached_hostname|default('memcached') }}\nMEMCACHED_PORT={{ memcached_port|default('11211')|quote }}\nAWX_ADMIN_USER={{ admin_user|quote }}\nAWX_ADMIN_PASSWORD={{ admin_password|quote }}\n): 'int' object is not iterable"}

Getting the same error even though on Ansible 2.9.0 and Python 3.6.8:

ansible 2.9.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/cheehow/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

Please help.

**Comment by Gopinath-G** [comment]
@wenottingham @tamilbabuece  @awxbot Could you please publish the fix or procedure to isolate this issue 
I am also facing same error when i try to install AWX on RHEL7

TASK [local_docker : Create Docker Compose Configuration] *******************************************************************
failed: [localhost] (item=environment.sh) => {"changed": false, "item": "environment.sh", "msg": "AnsibleError: Unexpected templating type error occurred on (DATABASE_USER={{ pg_username|quote }}\nDATABASE_NAME={{ pg_database|quote }}\nDATABASE_HOST={{ pg_hostname|default('postgres')|quote }}\nDATABASE_PORT={{ pg_port|default('5432')|quote }}\nDATABASE_PASSWORD={{ pg_password|default('awxpass')|quote }}\n{% if pg_admin_password is defined %}\nDATABASE_ADMIN_PASSWORD={{ pg_admin_password|quote }}\n{% endif %}\nAWX_ADMIN_USER={{ admin_user|quote }}\nAWX_ADMIN_PASSWORD={{ admin_password|quote }}\n): 'int' object is not iterable"}

Versions
----------
ansible: 2.4.2.0
RHEL: 7.8
python: 2.7 and 3.6 (getting same error when run with both versions)

**Comment by amitchauhan1502** [comment]
I am also getting same error 
TASK [local_docker : Create Docker Compose Configuration] ****************************************************************************
failed: [localhost] (item=environment.sh) => {"changed": false, "item": "environment.sh", "msg": "AnsibleError: Unexpected templating type error occurred on (DATABASE_USER={{ pg_username|quote }}\nDATABASE_NAME={{ pg_database|quote }}\nDATABASE_HOST={{ pg_hostname|default('postgres')|quote }}\nDATABASE_PORT={{ pg_port|default('5432')|quote }}\nDATABASE_PASSWORD={{ pg_password|default('awxpass')|quote }}\n{% if pg_admin_password is defined %}\nDATABASE_ADMIN_PASSWORD={{ pg_admin_password|quote }}\n{% endif %}\nAWX_ADMIN_USER={{ admin_user|quote }}\nAWX_ADMIN_PASSWORD={{ admin_password|quote }}\n): 'int' object is not iterable"}
changed: [localhost] => (item=credentials.py)

ansible: 2.4.2.0
RHEL: 7.7
python: 2.7 and 3.6 (getting same error when run with both versions)

**Comment by chyap1981** [comment]
Try upgrade the Ansible version, i would recommend 2.7 which is more stable.
