### ISSUE TITLE
Publish breaking changes

### ISSUE THREAD

**Issue by jagibson** [ansible/awx#5334]
##### ISSUE TYPE
Reporting system for breaking changes.

##### SUMMARY
Example: Previously updating AWX was a simple as updating the Ansible version in your Dockerfile.  With versions 9 and 9.0.1 this method of upgrade no longer works.  #5281 initially reported this but was closed and discussion was abruptly locked with no reason given.

It would be nice if breaking changes were published in some sort of digestible format.  Thank you.

**Comment by shanemcd** [comment]
Thanks for the feedback. We'll work on doing a better job of this.
