### ISSUE TITLE
Unable to access AWX web interface.

### ISSUE THREAD

**Issue by zbenta** [ansible/awx#5335]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Unable to access the web interface of AWX, i get "This connection was reset".

##### ENVIRONMENT
* AWX version: latest
* AWX install method: docker on linux
* Ansible version:  2.9.1
* Operating System: centos7
* Web Browser: firefox/lynx

##### STEPS TO REPRODUCE

Installed nodejs, updated ansible and installed gnu make.
I cloned the repo. altered the host_port to 8080 , ran the ansible script to install.
Forwarded port 8080 throuhg ssh and tried accessing the web interface.

##### EXPECTED RESULTS

I expected having access to the web interface of awx as I already have tried the previous "recipe" in another host and it worked like a charm.

##### ACTUAL RESULTS

I got a "The connection was reset" when i used firefox.

##### ADDITIONAL INFORMATION

I also tried using lynx on the docker host machine and got a "Alert!:Unexpected read error; connection aborted" and a Alert!:Unable to access document" error messages.

**Comment by ryanpetrello** [comment]
Hey @zbenta,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by zbenta** [comment]
Thanks, sorry for the inconvinience.
