### ISSUE TITLE
RFE: Allow sourced inventories to pull remote sourced inventory project on launch

### ISSUE THREAD

**Issue by zaskan** [ansible/awx#5341]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
We have a case in that the customer is using inventories sourced from projects. He is trying to update the inventory from the remote repo on the template launch. We shared with him the KCS below to clarify how to do that.

https://access.redhat.com/solutions/3805061

He followed the steps successfully, but he wants to suggest the idea of add an option that allow to pull the latest remote version of the inventory project from the remote git server on each use of the inventory.

**Comment by fosterseth** [comment]
solved in https://github.com/ansible/awx/pull/12073

if update on launch is enabled for project updates, then any inventory source update based on that project update will first run a project sync before the inventory source sync.
