### ISSUE TITLE
Add Ability to Set Default View Type for Jobs, Job Templates, and Projects

### ISSUE THREAD

**Issue by falcon78921** [ansible/awx#5342]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Per a customer's request, they would like the ability to set the View type for Jobs, Job Templates, and Projects (i.e. Compact or Expanded).

This functionality is also filed here: https://github.com/ansible/awx/issues/5133. However, this RFE builds on https://github.com/ansible/awx/issues/5133 to include Job Templates and Projects.

**Comment by wenottingham** [comment]
closed as a duplicate, will extend #5133
