### ISSUE TITLE
Tags for hosts in playbook 

### ISSUE THREAD

**Issue by ghost** [ansible/awx#5345]
##### ISSUE TYPE
 - Tags for Inventory AWS in playbook.

##### ENVIRONMENT
* AWX version: 6.0.0
* AWX install method: AWS
* Ansible version:  2.8

##### STEPS TO REPRODUCE
I have an inventory on AWX with all tags of my ec2 hosts, I would like use a tags for my inventory inside my playbooks. I could use a lot of inventorys with each tag but I don't like it. I want one inventory and use hosts tags on my playbook.

##### EXPECTED RESULTS
Tasks are run on hosts with specific tags, example
`hosts:
         - tag_Name_server`

##### ADDITIONAL INFORMATION
I run this playbook out of AWX and works fine with ec2.py and ec2.ini in my inventory folder.

**Comment by wenottingham** [comment]
This sounds like an issue with the playbook - grouping by tags is fully supported in the AWS inventory source. It's probably best discussed on the mailing list/IRC channel, as I do not believe this is a bug in awx.
