### ISSUE TITLE
unable to get local issuer certificate error (Custom Root and intermediate CA)

### ISSUE THREAD

**Issue by cpare** [ansible/awx#5346]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When attempting to authenticate against Active Directory (AD) we are getting the error
`WARNING  django_auth_ldap Caught LDAPError while authenticating cpare: SERVER_DOWN({'desc': "Can't contact LDAP server", 'info': 'error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed (unable to get local issuer certificate)'},)`

##### ENVIRONMENT
* AWX version: 9.0.1.0
* AWX install method: docker on linux
* Ansible version:  2.8.5
* Operating System:  RHEL
* Web Browser: Chrome / IE 

##### STEPS TO REPRODUCE
When installing added the setting in the inventory file to include files for our root and intermediate CA
```
# CA Trust directory. If you need to provide custom CA certificates, supplying
# this variable causes this directory on the host to be bind mounted over
# /etc/pki/ca-trust in the awx_task and awx_web containers.
#ca_trust_dir=/etc/pki/ca-trust/source/anchors
ca_trust_dir=/etc/ssl/certs
```

This appears to have worked as navigating to /etc/pki/ca-trust/source/anchors in the container shows the root and intermediate certificates correctly.  
"update-ca-trust extract" seems to have no effect

##### EXPECTED RESULTS

User should login without issue.

##### ACTUAL RESULTS

Login Fails, awx_web log gets error message
`WARNING  django_auth_ldap Caught LDAPError while authenticating cpare: SERVER_DOWN({'desc': "Can't contact LDAP server", 'info': 'error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed (unable to get local issuer certificate)'},)`

##### ADDITIONAL INFORMATION
None

**Comment by cpare** [comment]
re-ran installer - working as expected.

**Comment by deanmax** [comment]
We had the same issue when upgrading AWX from 10.0.0 to 15.0.1. The new version of AWX installer requires python3, so we took the effort to upgrade both python and ansible(2.8.4 to 2.10.3). Removed all running instances and ran the installer again, boom it worked.
