### ISSUE TITLE
AWX performance very poor

### ISSUE THREAD

**Issue by peshalav** [ansible/awx#5348]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

AWX performance very poor

##### ENVIRONMENT
* AWX version: 6.1.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.2
* Operating System: CentOS Linux release 7.6.1810 (Core)
* Web Browser:

##### EXPECTED RESULTS

run the jobs smoothly.

##### ACTUAL RESULTS

When job history exceeds about 50 the web interface performance is very poor, meaning that we are unable to enter job specific results.jobs are not running. Just nothing happens. This was tried on several browsers.

**Comment by ryanpetrello** [comment]
Hey @peshalav,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
