### ISSUE TITLE
Tuesday is not Tueday in selection

### ISSUE THREAD

**Issue by sugitk** [ansible/awx#5349]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

At schedule creation screen, Tuesday is `Tueday` in selection.

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: docker for mac

##### STEPS TO REPRODUCE

Select a job template -> go to `SCHEDULES` tab -> press `+` button -> select `REPEAT FREQUENCY` to `Month` -> select `ON THE` Tuesday

##### EXPECTED RESULTS

Tuesday

##### ACTUAL RESULTS

<img width="1133" alt="スクリーンショット 2019-11-19 18 25 20" src="https://user-images.githubusercontent.com/2234991/69145497-143b4680-0b11-11ea-8bee-0ac74ccf9f1c.png">

**Comment by ryanpetrello** [comment]
Maybe this is a bug in momentjs?

cc @mabashian

**Comment by dsesami** [comment]
says tuesday in devel properly now. This is resolved.
