### ISSUE TITLE
Error starting project a bytes-like object is required, not 'str'"

### ISSUE THREAD

**Issue by twobombs** [ansible/awx#5351]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Starting AWX in a Docker container fails

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: Docker in Docker
* Ansible version:  2.9.1
* Operating System: Ubuntu 18.04
* Web Browser: -

##### STEPS TO REPRODUCE

Build, Ship & Run AWX via Dockerfile ( eg: https://hub.docker.com/r/twobombs/ansibleawx )

##### EXPECTED RESULTS

AWX login UI

##### ACTUAL RESULTS

fatal: [localhost]: FAILED! => {"changed": false, "errors": [], "module_stderr": "Creating awx_postgres ... \nCreating awx_memcached ... \nCreating awx_rabbitmq  ... \n\u001b[2A\u001b[2K\nCreating awx_memcached ... \n\u001b[2B\u001b[1A\u001b[2K\nCreating awx_rabbitmq  ... \n\u001b[1B\u001b[3A\u001b[2K\nCreating awx_postgres  ... \n\u001b[3BCreating awx_web       ... \n", "module_stdout": "3.7.4: Pulling from ansible/awx_rabbitmq\nDigest: sha256:3ff448f979149a0684c61b0f00eb0fe7bc480b123323aa80fb3bb8934027f895\nStatus: Downloaded newer image for ansible/awx_rabbitmq:3.7.4\nalpine: Pulling from library/memcached\nDigest: sha256:3cfb2eee0b618722a62f4cc907fa0ede848efa87d773bb9384044f490926e7ce\nStatus: Downloaded newer image for memcached:alpine\n10: Pulling from library/postgres\nDigest: sha256:9ab0b88aae58f006e8da0e4f32678881fcb2eaae5154bb1a369733983d21b370\nStatus: Downloaded newer image for postgres:10\n9.0.1: Pulling from ansible/awx_web\nDigest: sha256:c14ae37e0e8836573443a2f4d7c75afb26658065ca36ac9688dc1b8251da6477\nStatus: Downloaded newer image for ansible/awx_web:9.0.1\n9.0.1: Pulling from ansible/awx_task\nDigest: sha256:d2d4ba190526fbbb2ecea3c024aec50626b18d9b1ade4620d5a7c24388e79371\nStatus: Downloaded newer image for ansible/awx_task:9.0.1\n", "msg": "**Error starting project a bytes-like object is required, not 'str'"**}

##### ADDITIONAL INFORMATION

![Screenshot 2019-11-19 at 14 15 11](https://user-images.githubusercontent.com/12692227/69149767-7b3c0980-0ad7-11ea-964b-c8ab55851558.png)

At first I got no error information, but after forcing to a python3 only install for AWX I finally got an error.

**Comment by wenottingham** [comment]
That error is from your docker-compose build, you probably want to post this upstream to them (e.g., https://github.com/docker/compose/issues/6998)
