### ISSUE TITLE
Jobs Error After Upgrade to AWX 9.0.1

### ISSUE THREAD

**Issue by phillipstr** [ansible/awx#5355]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
SCM updates from GitHub result in error -
Traceback (most recent call last): File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/tasks.py", line 1235, in run raise RuntimeError('not starting %s task' % self.instance.status) 

Template Jobs status error - 
Traceback (most recent call last): File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/tasks.py", line 1227, in run self.pre_run_hook(self.instance, private_data_dir) File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/tasks.py", line 1797, in pre_run_hook sync_task.run(local_project_sync.id) File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/tasks.py", line 683, in _wrapped return f(self, *args, **kwargs) File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/tasks.py", line 1392, in run raise AwxTaskError.TaskError(self.instance, rc) Exception: project_update 2321 (failed) encountered an error (rc=2)

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: Docker (v19.03.4) on Linux
* Ansible version:  2.9
* Operating System: RHEL7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Occurs on any SCM update or template job run. 

##### EXPECTED RESULTS

SCM update or job template run, or at least get to a point of failing.

##### ACTUAL RESULTS

Jobs end in error status. 

##### ADDITIONAL INFORMATION

Environment was previously running AWX 6.1.0 and Ansible 2.8.5, upgraded on 11/13/2019. Stopped/removed all containers prior to upgrade. Postgres_data_dir and docker_compose_dir were given the same path as previous install. Using official Ansible Docker images.

**Comment by pottom** [comment]
I had same issue.

After some investigation I found this error.

fatal: [localhost, -> localhost]: FAILED! => {"changed": true, "cmd": ["ansible-galaxy", "install", "-r", "requirements.yml", "-p", "/tmp/awx_297_g1trc62j/requirements_roles", "-v"], "delta": "0:00:01.752895", "end": "2019-11-20 08:29:36.046102", "msg": "non-zero return code", "rc": 1, "start": "2019-11-20 08:29:34.293207", "stderr": " [WARNING]: - mod_zabbix was NOT installed successfully: this role does not\nappear to have a meta/main.yml file.\nERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.", "stderr_lines": [" [WARNING]: - mod_zabbix was NOT installed successfully: this role does not", "appear to have a meta/main.yml file.", "ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list."], "stdout": "Using /etc/ansible/ansible.cfg as config file\n- extracting mod_linux to /tmp/awx_297_g1trc62j/requirements_roles/mod_linux\n- mod_linux (master) was installed successfully", "stdout_lines": ["Using /etc/ansible/ansible.cfg as conf…

After I created the correct directory structure all of my dependency roles the problem has gone.

**Comment by AlanCoding** [comment]
Other than seeing that https://github.com/ansible/ansible/blob/3a7b77a94ce534c502828ebd2959f6fdf9d183f5/lib/ansible/galaxy/role.py#L280 is being hit, I don't think there's much I can say without testing the specific `roles/requirements.yml` file.

**Comment by phillipstr** [comment]
As far as I can tell all roles have a meta/main.yml file. I'll do some more digging. Thanks to the both of you.

**Comment by kakawait** [comment]
@phillipstr do you find anything? I have same issue. Not enable to determine what's the source of the problem.

**Comment by phillipstr** [comment]
Unfortunately no, ended up just reinstalling. Fresh install at 9.0.1 has been working just fine.

**Comment by kakawait** [comment]
Finally I found my issue. Is something related SSL certificate from project on `requirements.yml`. That strange because plain old `git clone https://...` works inside `awx_task` container but when awx is using the same command on https://github.com/ansible/awx/blob/devel/awx/playbooks/project_update.yml#L139 it fails. Maybe related to `venv` or other `env` stuff because our custom SSL certificates are installed using `update-ca-trust`.

But what people should keep in mind is https://github.com/ansible/awx/issues/2083. I didn't know about API that give you much more logs than UI that help me to determine what's happen. @matburt gives some tips on that issue to help people debugging such step.

@phillipstr so you should checkout `/api/v2/project_updates/{id}` next time and specially `/api/v2/project_updates/{id}/stdout`
