### ISSUE TITLE
Unable to Install AWX

### ISSUE THREAD

**Issue by bmc1412** [ansible/awx#5356]
##### ISSUE TYPE
Installation problem
##### SUMMARY
 I am new to Ansible and want to install AWX, I installed Ansible, Docker-compose using pip and tried to install AWX but ansible-playbook -i inventory install.yml -vv faling with 

TASK [local_docker : Start the containers] ********************************************************************************************************************************************************************
task path: /ILMT/awx/installer/roles/local_docker/tasks/compose.yml:26
fatal: [localhost]: FAILED! => {"changed": false, "errors": [], "module_stderr": "Creating awx_postgres ... \r\nCreating awx_rabbitmq ... \r\nCreating awx_memcached ... \r\n\r\u001b[2BCreating awx_web       ... \r\nNo handlers could be found for logger \"compose.service\"\n\r\u001b[1B", "module_stdout": "", "msg": "Error starting project unknown cause"}

PLAY RECAP ****************************************************************************************************************************************************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=1    skipped=92   rescued=0    ignored=0   

Could you please help me with this please?

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: , docker on linux
* Ansible version:  ansible 2.9.1
* Operating System: RHEL 7 x86_64
* Web Browser: NA

##### STEPS TO REPRODUCE

sestatus
systemctl stop firewalld
systemctl disable firewalld
yum install -y epel-release
yum install -y yum-utils device-mapper-persistent-data lvm2 ansible git python-devel python-pip vim-enhanced
yum -y install git gcc gcc-c++ lvm2 bzip2 gettext nodejs yum-utils device-mapper-persistent-data ansible python-pip vim
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install docker-ce -y
systemctl start docker
systemctl enable docker
git clone https://github.com/ansible/awx.git
cd awx/
git clone https://github.com/ansible/awx-logos.git
cd installer/
vi inventory
  postgres_data_dir=/var/lib/pgdocker
  awx_official=true
  awx_alternate_dns_servers="4.2.2.1,4.2.2.2"
  project_data_dir=/var/lib/awx/projects

cat inventory |grep -v "#"
localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python"
[all:vars]
dockerhub_base=ansible
awx_secret_key=awxsecret
postgres_data_dir=/var/lib/pgdocker
host_port=80
docker_compose_dir=/var/lib/awx
pg_username=awx
pg_password=awxpass
pg_database=awx
pg_port=5432
awx_official=true
project_data_dir=/var/lib/awx/projects

ansible-playbook -i inventory install.yml -vv

##### EXPECTED RESULTS

AWX deployed sucecssfully

##### ACTUAL RESULTS

AWX playbook failing with:
TASK [local_docker : Start the containers] ********************************************************************************************************************************************************************
task path: /ILMT/awx/installer/roles/local_docker/tasks/compose.yml:26
fatal: [localhost]: FAILED! => {"changed": false, "errors": [], "module_stderr": "Creating awx_postgres ... \r\nCreating awx_rabbitmq ... \r\nCreating awx_memcached ... \r\n\r\u001b[2BCreating awx_web       ... \r\nNo handlers could be found for logger \"compose.service\"\n\r\u001b[1B", "module_stdout": "", "msg": "Error starting project unknown cause"}

PLAY RECAP ****************************************************************************************************************************************************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=1    skipped=92   rescued=0    ignored=0

**Comment by ryanpetrello** [comment]
Hey @bmc1412,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
