### ISSUE TITLE
Opening cleanup fact details launch modal throws JS error

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#536]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Cleanup Facts modal seems generally broken.  When it first gets opened, there's an error in the console.  If you fill out the form it throws more errors.

##### STEPS TO REPRODUCE

Navigate to Management Jobs and launch Cleanup Fact Details.  Notice error in console.  Attempt to fill out form and hit launch.  More errors in console.

##### ADDITIONAL INFORMATION

<img width="1440" alt="screen shot 2017-10-31 at 11 12 31 am" src="https://user-images.githubusercontent.com/9889020/32231758-df802240-be2c-11e7-8bb3-7fe75073502e.png">

<img width="1440" alt="screen shot 2017-10-31 at 11 16 02 am" src="https://user-images.githubusercontent.com/9889020/32231774-ea4187b4-be2c-11e7-9fe2-6005136f5650.png">

**Comment by mabashian** [comment]
I'm also seeing the initial JS error when launching the other management jobs

**Comment by jaredevantabor** [comment]
This is now fixed in devel.
