### ISSUE TITLE
AWX installation issue

### ISSUE THREAD

**Issue by bmc1412** [ansible/awx#5360]
ISSUE TYPE
Installation problem

SUMMARY
I am new to Ansible and want to install AWX, I installed Ansible, Docker-compose using pip and tried to install AWX but ansible-playbook -i inventory install.yml -vv faling with

task path: /ILMT/AWX/awx/installer/roles/local_docker/tasks/compose.yml:26
fatal: [localhost]: FAILED! => {"changed": false, "errors": [], "module_stderr": "Creating awx_rabbitmq ... \r\nCreating awx_postgres ... \r\nCreating awx_memcached ... \r\n\r\u001b[3BCreating awx_web       ... \r\nNo handlers could be found for logger \"compose.service\"\n\r\u001b[1B", "module_stdout": "alpine: Pulling from library/memcached\nDigest: sha256:3cfb2eee0b618722a62f4cc907fa0ede848efa87d773bb9384044f490926e7ce\nStatus: Downloaded newer image for memcached:alpine\n10: Pulling from library/postgres\nDigest: sha256:9ab0b88aae58f006e8da0e4f32678881fcb2eaae5154bb1a369733983d21b370\nStatus: Downloaded newer image for postgres:10\n3.7.4: Pulling from ansible/awx_rabbitmq\nDigest: sha256:3ff448f979149a0684c61b0f00eb0fe7bc480b123323aa80fb3bb8934027f895\nStatus: Downloaded newer image for ansible/awx_rabbitmq:3.7.4\n9.0.1: Pulling from ansible/awx_web\nDigest: sha256:c14ae37e0e8836573443a2f4d7c75afb26658065ca36ac9688dc1b8251da6477\nStatus: Downloaded newer image for ansible/awx_web:9.0.1\n9.0.1: Pulling from ansible/awx_task\nDigest: sha256:d2d4ba190526fbbb2ecea3c024aec50626b18d9b1ade4620d5a7c24388e79371\nStatus: Downloaded newer image for ansible/awx_task:9.0.1\n", "msg": "Error starting project unknown cause"}

PLAY RECAP ****************************************************************************************************************************************************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=1    skipped=92   rescued=0    ignored=0   

Could you please help me with this please?

ENVIRONMENT
AWX version: 9.0.1
AWX install method: , docker on linux
Ansible version: ansible 2.9.1
Operating System: RHEL 7 x86_64
Web Browser: NA
STEPS TO REPRODUCE
sestatus
systemctl stop firewalld
systemctl disable firewalld
yum install -y epel-release
yum install -y yum-utils device-mapper-persistent-data lvm2 ansible git python-devel python-pip vim-enhanced
yum -y install git gcc gcc-c++ lvm2 bzip2 gettext nodejs yum-utils device-mapper-persistent-data ansible python-pip vim
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install docker-ce -y
systemctl start docker
systemctl enable docker
git clone https://github.com/ansible/awx.git
cd awx/
git clone https://github.com/ansible/awx-logos.git
cd installer/
vi inventory
postgres_data_dir=/var/lib/pgdocker
awx_official=true
awx_alternate_dns_servers="4.2.2.1,4.2.2.2"
project_data_dir=/var/lib/awx/projects

cat inventory |grep -v "#"
localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python"
[all:vars]
dockerhub_base=ansible
awx_secret_key=awxsecret
postgres_data_dir=/var/lib/pgdocker
host_port=80
docker_compose_dir=/var/lib/awx
pg_username=awx
pg_password=awxpass
pg_database=awx
pg_port=5432
awx_official=true
project_data_dir=/var/lib/awx/projects

ansible-playbook -i inventory install.yml -vv

EXPECTED RESULTS
AWX deployed sucecssfully

ACTUAL RESULTS
task path: /ILMT/AWX/awx/installer/roles/local_docker/tasks/compose.yml:26
fatal: [localhost]: FAILED! => {"changed": false, "errors": [], "module_stderr": "Creating awx_rabbitmq ... \r\nCreating awx_postgres ... \r\nCreating awx_memcached ... \r\n\r\u001b[3BCreating awx_web       ... \r\nNo handlers could be found for logger \"compose.service\"\n\r\u001b[1B", "module_stdout": "alpine: Pulling from library/memcached\nDigest: sha256:3cfb2eee0b618722a62f4cc907fa0ede848efa87d773bb9384044f490926e7ce\nStatus: Downloaded newer image for memcached:alpine\n10: Pulling from library/postgres\nDigest: sha256:9ab0b88aae58f006e8da0e4f32678881fcb2eaae5154bb1a369733983d21b370\nStatus: Downloaded newer image for postgres:10\n3.7.4: Pulling from ansible/awx_rabbitmq\nDigest: sha256:3ff448f979149a0684c61b0f00eb0fe7bc480b123323aa80fb3bb8934027f895\nStatus: Downloaded newer image for ansible/awx_rabbitmq:3.7.4\n9.0.1: Pulling from ansible/awx_web\nDigest: sha256:c14ae37e0e8836573443a2f4d7c75afb26658065ca36ac9688dc1b8251da6477\nStatus: Downloaded newer image for ansible/awx_web:9.0.1\n9.0.1: Pulling from ansible/awx_task\nDigest: sha256:d2d4ba190526fbbb2ecea3c024aec50626b18d9b1ade4620d5a7c24388e79371\nStatus: Downloaded newer image for ansible/awx_task:9.0.1\n", "msg": "Error starting project unknown cause"}

PLAY RECAP ****************************************************************************************************************************************************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=1    skipped=92   rescued=0    ignored=0   

ADDITIONAL INFORMATION

**Comment by nicolaibaralmueller** [comment]
If you are new to AWX I suggest going simple and just install base stuff.

This inventory works for me:

```
localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python"

[all:vars]

# Remove these lines if you want to run a local image build
# Otherwise the setup playbook will install the official Ansible images. Versions may
# be selected based on: latest, 1, 1.0, 1.0.0, 1.0.0.123
# by default the base will be used to search for ansible/awx_web and ansible/awx_task
# dockerhub_base=ansible

# Openshift Install
# Will need to set -e openshift_password=developer -e docker_registry_password=$(oc whoami -t)
#           or set -e openshift_token=TOKEN
# openshift_host=127.0.0.1:8443
# openshift_project=awx
# openshift_user=developer
# openshift_skip_tls_verify=False
# openshift_pg_emptydir=True

# Kubernetes Install
# kubernetes_context=test-cluster
# kubernetes_namespace=awx
# tiller_namespace=kube-system
# Optional Kubernetes Variables
# pg_persistence_storageClass=StorageClassName
# pg_cpu_limit=1000
# pg_mem_limit=2

# Kubernetes Ingress Annotations
# You can use the variables below to pass annotations to Kubernetes Ingress
# The example below shows an annotation to be used with Traefik but other Ingress controllers are also supported.
#kubernetes_ingress_hostname=awx.example.org
#kubernetes_ingress_annotations={'kubernetes.io/ingress.class': 'traefik', 'traefik.ingress.kubernetes.io/redirect-entry-point': 'https'}

# Kubernetes and Openshift Install Resource Requests
# These are the request and limit values for a pod's container for task/web/rabbitmq/memcached/management.
# The total amount of requested resources for a pod is the sum of all
# resources requested by all containers in the pod
# A cpu_request of 1500 is 1.5 cores for the container to start out with.
# A cpu_limit defines the maximum cores that that container can reserve.
# A mem_request of 2 is for 2 gigabytes of memory for the container
# A mem_limit defines the maximum memory that that container can reserve.
# Default values for these entries can be found in ./roles/kubernetes/defaults/main.yml
# task_cpu_request=1500
# task_mem_request=2
# task_cpu_limit=2000
# task_mem_limit=4
# web_cpu_limit=1000
# web_mem_limit=2
# rabbitmq_cpu_limit=1000
# rabbitmq_mem_limit=3
# memcached_cpu_limit=1000
# memcached_mem_limit=2
# management_cpu_limit=2000
# management_mem_limit=2

# Common Docker parameters
awx_task_hostname=awx
awx_web_hostname=awxweb
postgres_data_dir=/opt/pgdocker
host_port=80
#host_port_ssl=443
#ssl_certificate=/opt/awxcompose/nginx/awxweb.pem
docker_compose_dir=/opt/awxcompose

# Required for Openshift when building the image on your own
# Optional for Openshift if using Dockerhub or another prebuilt registry
# Required for Docker Compose Install if building the image on your own
# Optional for Docker Compose Install if using Dockerhub or another prebuilt registry
# Define if you want the image pushed to a registry. The container definition will also use these images
# docker_registry=172.30.1.1:5000
# docker_registry_repository=awx
# docker_registry_username=developer


# Docker_image will not attempt to push to remote if the image already exists locally
# Set this to true to delete images from docker on the build host so that they are pushed to the remote repository
# docker_remove_local_images=False

# Set pg_hostname if you have an external postgres server, otherwise
# a new postgres service will be created
# pg_hostname=postgresql
pg_username=awx
# pg_password should be random 10 character alphanumeric string, when postgresql is running on kubernetes
# NB: it's a limitation of the "official" postgres helm chart
pg_password=awxpass
pg_admin_password=postgrespass
pg_database=awx
pg_port=5432
#pg_sslmode=require

# RabbitMQ Configuration
rabbitmq_password=awxpass
rabbitmq_erlang_cookie=cookiemonster

# Use a local distribution build container image for building the AWX package
# This is helpful if you don't want to bother installing the build-time dependencies as
# it is taken care of already.
# NOTE: IMPORTANT: If you are running a mininshift install, using this container might not work
#                  if you are using certain drivers like KVM where the source tree can't be mapped
#                  into the build container.
#                  Thus this setting must be set to False which will trigger a local build. To view the
#                  typical dependencies that you might need to install see:
#                  installer/image_build/files/Dockerfile.sdist
use_container_for_build=true

# This will create or update a default admin (superuser) account in AWX, if not provided
# then these default values are used
admin_user=admin
admin_password=admpass#1

# Whether or not to create preload data for demonstration purposes
create_preload_data=True

# AWX Secret key
# It's *very* important that this stay the same between upgrades or you will lose the ability to decrypt
# your credentials
secret_key=awxsecret

# Build AWX with official logos
# Requires cloning awx-logos repo as a sibling of this project.
# Review the trademark guidelines at https://github.com/ansible/awx-logos/blob/master/TRADEMARKS.md
awx_official=false

# Proxy
#http_proxy=http://proxy:3128
#https_proxy=http://proxy:3128
#no_proxy=mycorp.org

# Container networking configuration
# Set the awx_task and awx_web containers' search domain(s)
#awx_container_search_domains=example.com,ansible.com
# Alternate DNS servers
#awx_alternate_dns_servers="10.1.2.3,10.2.3.4"

# AWX project data folder. If you need access to the location where AWX stores the projects
# it manages from the docker host, you can set this to turn it into a volume for the container.
#project_data_dir=/var/lib/awx/projects

# AWX custom virtual environment folder. Only usable for local isntall.
#custom_venv_dir=/opt/my-envs/

# CA Trust directory. If you need to provide custom CA certificates, supplying
# this variable causes this directory on the host to be bind mounted over
# /etc/pki/ca-trust in the awx_task and awx_web containers.
#ca_trust_dir=/etc/pki/ca-trust/source/anchors

# Include /etc/nginx/awx_extra.conf
# Note the use of glob pattern for nginx
# which makes include "optional" - i.e. not fail
# if file is absent
#extra_nginx_include="/etc/nginx/awx_extra[.]conf"
```

**Comment by bmc1412** [comment]
but I want to execute playbooks using AWX
can it is possible using gui?

**Comment by nicolaibaralmueller** [comment]
> but I want to execute playbooks using AWX
> can it is possible using gui?

I don't understand the question. That is the purpose of AWX.

**Comment by bmc1412** [comment]
okay, 
will take a try

**Comment by bmc1412** [comment]
I am still getting similar error eith inventory file suggested by you
TASK [local_docker : Start the containers] ********************************************************************************************************************************************************************
task path: /ILMT/awx/installer/roles/local_docker/tasks/compose.yml:26
fatal: [localhost]: FAILED! => {"changed": false, "errors": [], "module_stderr": "Creating awx_postgres ... \r\nCreating awx_memcached ... \r\nCreating awx_rabbitmq  ... \r\n\r\u001b[2BCreating awx_web       ... \r\nNo handlers could be found for logger \"compose.service\"\n\r\u001b[1B", "module_stdout": "alpine: Pulling from library/memcached\nDigest: sha256:3cfb2eee0b618722a62f4cc907fa0ede848efa87d773bb9384044f490926e7ce\nStatus: Downloaded newer image for memcached:alpine\n10: Pulling from library/postgres\nDigest: sha256:9ab0b88aae58f006e8da0e4f32678881fcb2eaae5154bb1a369733983d21b370\nStatus: Downloaded newer image for postgres:10\n3.7.4: Pulling from ansible/awx_rabbitmq\nDigest: sha256:3ff448f979149a0684c61b0f00eb0fe7bc480b123323aa80fb3bb8934027f895\nStatus: Downloaded newer image for ansible/awx_rabbitmq:3.7.4\n", "msg": "Error starting project unknown cause"}

PLAY RECAP ****************************************************************************************************************************************************************************************************
localhost                  : ok=40   changed=24   unreachable=0    failed=1    skipped=63   rescued=0    ignored=0   


what I did :
$ docker stop -t 0 $(docker ps -qa)
$ docker rm -f $(docker ps -qa)
$ docker rmi -f $(docker images -qa)
systemctl restart docker

Replace inventory file with new one and take a try
[AWX_Fail.txt](https://github.com/ansible/awx/files/3869945/AWX_Fail.txt)

**Comment by nicolaibaralmueller** [comment]
Then I think the problem is the docker python module.
```
This is incompatible with docker-py. If you have previously installed docker-py, please uninstall it.
We use this module instead of docker-py because it is what the docker-compose Python module requires.
```

Create a file filename.sh and copy/paste this:

```
#!/bin/bash

echo "for centos7"

echo "updating centos7"
sudo yum update -y

echo "installing epel-release"
sudo yum install -y epel-release

echo "installing docker prerequisites"
sudo yum install -y yum-utils device-mapper-persistent-data lvm2

echo "installing docker"
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum -y install docker-ce
systemctl enable docker && systemctl start docker

echo "install docker-compose"
LATEST_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r '.tag_name')
curl -L "https://github.com/docker/compose/releases/download/$LATEST_VERSION/docker-compose-$(uname -s)-$(uname -m)" > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

echo "installing AWX dependencies"
yum install -y python2-pip
pip install ansible
pip install docker-compose

echo "adding current user to docker group"
sudo usermod -aG docker $(whoami)

echo "installing python-pip"
sudo yum install -y python-pip

echo "upgrading pip"
sudo pip install -U pip

echo "upgrading cffi"
sudo pip install -U cffi

echo "upgrading python"
sudo yum upgrade -y python*

echo "installing gcc-c++ make"
sudo yum install -y gcc-c++ make

echo "installing npm 10"
sudo curl -sL https://rpm.nodesource.com/setup_10.x | sudo -E bash -

echo "installing nodejs"
sudo yum install -y nodejs
```

```
chmod +x filename.sh
.\filename.sh
```

Should work for Centos.

**Comment by bmc1412** [comment]
Tried above thing, but still not working, I am using Redhat 7.7 x86_64

**Comment by shanemcd** [comment]
Hello, this issue tracker is for bugs. It seems like you need help troubleshooting a problem with your environment. For that, please try [IRC](http://webchat.freenode.net/?channels=ansible-awx) or the [AWX mailing list](https://groups.google.com/forum/#!forum/awx-project).
