### ISSUE TITLE
AWX install on Fargate AWS

### ISSUE THREAD

**Issue by ghost** [ansible/awx#5364]
Hello, 

I'm trying install AWX on Fargate and I have a task definition with 4 containers(rabbitmq, memcached, awx_task, awx_web).
I have an issue with SECRET KEY because AWX can't read environment variable and the implementation on docker use a volume for SECRET KEY. 
I can mount a volume on task definition(fargate), but I can't put data before task deployment.
How to add SECRET KEY on AWX for installation on Fargate? 

Thanks!

**Comment by ryanpetrello** [comment]
Hey @ivanmpk,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
