### ISSUE TITLE
[ RFE ] Additional Job Filters

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#5365]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Customer request to allow for additional search filters in the Jobs menu such as `limit` and `launched_by`.

**Comment by wenottingham** [comment]
We are not likely to expand on search until landing the pending UI rewrite.

**Comment by jlmitch5** [comment]
Based on UX feedback we gathered at ansiblefest, we will be adding these keys to the jobs search (which includes launched by and limit) to ui_next.

![Screen Shot 2020-01-10 at 11 25 34 AM](https://user-images.githubusercontent.com/1342624/72168852-f6b18d00-339b-11ea-8aa3-eef6d2b17e18.png)
