### ISSUE TITLE
Link to Instance Group docs incorrect

### ISSUE THREAD

**Issue by tvo318** [ansible/awx#5367]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The Create and Edit Instance Group forms have a pop-up that links incorrectly to the Clustering chapter.

##### ENVIRONMENT

- Tower version: 3.6.0
- AWX install method: yolo #6631: Instance URL - https://ec2-34-238-249-200.compute-1.amazonaws.com
- Ansible version: 2.10.0.dev0
- Operating System: Mac Mojave 10.14.6
- Web Browser: Version 78.0.3904.87 (Official Build) (64-bit)

##### STEPS TO REPRODUCE
To the Create form:
Instance Groups>Create Instance Group (Details tab)

To the edit form:
Instance Groups> Choose one off the list> Details tab

##### EXPECTED RESULTS
![image](https://user-images.githubusercontent.com/7514801/69273898-8144ef80-0b96-11ea-898e-0c96d538a52d.png)

The way it is linking, the link needs to link to the Instance Groups documentation instead: https://docs.ansible.com/ansible-tower/latest/html/userguide/instance_groups.html

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/7514801/69273185-2bbc1300-0b95-11ea-9533-3cab4f80748c.png)

##### ADDITIONAL INFORMATION

I would think that container groups need to link to the [Container Groups](https://docs.ansible.com/ansible-tower/latest/html/administration/external_execution_envs.html#ag-container-groups) section of the docs and the Instance Groups need to link to: https://docs.ansible.com/ansible-tower/latest/html/userguide/instance_groups.html

**Comment by unlikelyzero** [comment]
@ryanpetrello why is this a medium? Why is this being added to 3.7.0 before we've hit the other pf milestones?

**Comment by ryanpetrello** [comment]
@unlikelyzero because it's an obvious (and confusing) documentation bug in a product we ship today (and the fix is easy).

**Comment by dsesami** [comment]
instance group/container group links are verified to work normally in `devel`.
