### ISSUE TITLE
Increase psql pv size in kubernetes?

### ISSUE THREAD

**Issue by richardmosquera** [ansible/awx#5368]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME

 - Installer

##### SUMMARY
Is there any way to set the size of the postgres partition > 5gb? The installer creates a 5gb PV but it's not possible to increase after the install. 

##### ENVIRONMENT
* AWX version: 6.1.0.0 
* AWX install method: kubernetes
* Ansible version:  2.8.2
* Operating System: CentOS 7

**Comment by ryanpetrello** [comment]
Hey @richardmosquera,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you have general questions/need help managing or troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

If you do figure out how to accomplish this with the installer, we appreciate pull requests (a note in https://github.com/ansible/awx/blob/devel/INSTALL.md might appropriate).
