### ISSUE TITLE
LDAP Server Must Be FQDN

### ISSUE THREAD

**Issue by codyjohn** [ansible/awx#537]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### ENVIRONMENT
* AWX version: 1.0.1
* AWX install method: docker on linux
* Ansible version:  2.4.1
* Operating System: CentOS 7.4
* Web Browser: Chrome on Mac

##### STEPS TO REPRODUCE

1. On a new install of AWX, log in and navigate to Settings -> AUTHENTICATION.
2. In the Sub Category drop-down, select LDAP.
3. In the LDAP Server URI field, attempt to add a non-FQDN server name such as: 

ldaps://ldap:636

4. Click Save.
5. Navigate to Instance Groups and back to Settings.
6. The LDAP Server URI was not saved.

##### EXPECTED RESULTS

The non-FQDN hostname should be honored and saved.

##### ACTUAL RESULTS

The following log is seen when attempting to save the non-FQDN hostname:

```10.255.255.10 - - [31/Oct/2017:16:11:58 +0000] "PATCH /api/v2/settings/all/ HTTP/1.1" 400 57 "http://awxhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38" "-"```

**Comment by matburt** [comment]
Can you examine the api response from the service when this save was made?

**Comment by narankhetani** [comment]
Please see below:

Request payload:
```
{"AUTH_LDAP_SERVER_URI":"ldaps://ldap:636","AUTH_LDAP_BIND_DN":"","AUTH_LDAP_BIND_PASSWORD":"","AUTH_LDAP_USER_SEARCH":[],"AUTH_LDAP_GROUP_SEARCH":[],"AUTH_LDAP_USER_DN_TEMPLATE":null,"AUTH_LDAP_USER_ATTR_MAP":{},"AUTH_LDAP_GROUP_TYPE":"MemberDNGroupType","AUTH_LDAP_REQUIRE_GROUP":null,"AUTH_LDAP_DENY_GROUP":null,"AUTH_LDAP_START_TLS":true,"AUTH_LDAP_USER_FLAGS_BY_GROUP":{},"AUTH_LDAP_ORGANIZATION_MAP":{},"AUTH_LDAP_TEAM_MAP":{}}
```
response:
```
{"AUTH_LDAP_SERVER_URI":["Enter a valid URL"]}```

**Comment by cchurch** [comment]
Need to add `kwargs.setdefault('allow_plain_hostname', True)` to  https://github.com/ansible/awx/blob/devel/awx/sso/fields.py#L111 -- will submit a PR soon.

**Comment by matburt** [comment]
Applied and merged, please test it out and let us know.
