### ISSUE TITLE
Vanilla k8s install doesn't work with helm 3.x.x 

### ISSUE THREAD

**Issue by shanemcd** [ansible/awx#5371]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
From @one-t 

> The vanilla k8s installation does not work with the newly released version of helm due to some client syntax changes. It no longer accepts the --tiller-namespace flag.

##### ENVIRONMENT
* AWX version: N/A
* AWX install method: Kubernetes
* Ansible version:  N/A
* Operating System: N/A
* Web Browser: N/A

##### STEPS TO REPRODUCE

Attempt an install of AWX on a vanilla Kubernetes cluster, using the included Helm database option.

##### EXPECTED RESULTS

It should work.

##### ACTUAL RESULTS

It does not work.

**Comment by jcomito** [comment]
Tiller was removed in Helm 3 so it looks like any --tiller flags are breaking now. Fails at the Deploy and Activate Postgres task:


TASK [kubernetes : Deploy and Activate Postgres (Kubernetes)] *******************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "helm repo update --tiller-namespace=kube-system\necho 'postgresqlUsername: awx\npostgresqlPassword: awxpass\npostgresqlDatabase: awx\npersistence:\n  size: 5Gi\n' | helm upgrade awx-postgresql --install  --namespace awx  --version=\"6.2.1\"  --tiller-namespace=kube-system  --values -  stable/postgresql\n", "delta": "0:00:00.075302", "end": "2020-01-09 14:28:55.586166", "msg": "non-zero return code", "rc": 1, "start": "2020-01-09 14:28:55.510864", "stderr": "Error: unknown flag: --tiller-namespace\nError: unknown flag: --tiller-namespace", "stderr_lines": ["Error: unknown flag: --tiller-namespace", "Error: unknown flag: --tiller-namespace"], "stdout": "", "stdout_lines": []}

**Comment by thaurcam** [comment]
the problem is with this task in installer/roles/kubernetes/tasks/main.yml:
```
- name: Deploy and Activate Postgres (Kubernetes)
      shell: |
        helm repo update --tiller-namespace={{ tiller_namespace | default('kube-system') }}
        echo {{ pg_values | quote }} | helm upgrade {{ postgresql_service_name }} --install \
          --namespace {{ kubernetes_namespace }} \
          --version="6.2.1" \
          --tiller-namespace={{ tiller_namespace | default('kube-system') }} \
          --values - \
          stable/postgresql
      register: kubernetes_pg_activate
      no_log: true
  when:
    - pg_hostname is not defined or pg_hostname == ''
    - postgres_svc_details is defined and postgres_svc_details.rc != 0
    - kubernetes_context is defined
```

there are two issues with helm 3 which I found:
- tiller was removed
- due to a bug (https://github.com/helm/helm/issues/7002) the helm upgrade command does not read from stdin.

as a workaround you can change the task in your playbook like this:
```  
- name: Deploy and Activate Postgres (Kubernetes)
      shell: |
        helm repo update
        echo {{ pg_values | quote }} | helm install {{ postgresql_service_name }} \
          --namespace {{ kubernetes_namespace }} \
          --version="6.2.1" \
          --values - \
          stable/postgresql
      register: kubernetes_pg_activate
      no_log: false
  when:
    - pg_hostname is not defined or pg_hostname == ''
    - postgres_svc_details is defined and postgres_svc_details.rc != 0
    - kubernetes_context is defined
```

**Comment by shanemcd** [comment]
Patches are much appreciated. I am not too worried about maintaining support for helm 2 going forward, so if some kind soul would like to open a PR I'd be happy to test it out.

**Comment by bhundven** [comment]
@jcomito @shanemcd test that :)
