### ISSUE TITLE
Dockerized AWX issue with LDAP authentication

### ISSUE THREAD

**Issue by calimerosolo** [ansible/awx#5375]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

I am able to query the AD server from the command line and I can pull all the users:
`ldapsearch -x -H ldap://192.168.1.125:389 -D "CN=Acme Brick,OU=Users-DEV,DC=DEV,DC=ACME,DC=LOCAL" -b "DC=DEV,DC=ACME,DC=LOCAL" -w <PASSWORD>
`
But from the Web GUI Login page it fails (same issue when using FreeIPA IdM)

##### ENVIRONMENT
* AWX version: 7.0.0.0
* AWX install method: docker
* Ansible version:  2.8.4
* Operating System: Linux Centos 7
* Web Browser: Firefox/Chrome/IE

##### STEPS TO REPRODUCE
I use either AD or FreeIPA IdM with the following settings for LDAP (example for AD):

LDAP SERVER URI: ldap://192.168.1.125:389
LDAP BIND DN: CN=Acme Brick,OU=Users-DEV,DC=DEV,DC=ACME,DC=LOCAL
LDAP BIND PASSWORD: ************
LDAP USER DN TEMPLATE: sAMAccountName=%(user)s,ou=Users-DEV,DC=DEV,DC=ACME,DC=LOCAL
LDAP GROUP TYPE: MemberDNGroupType
LDAP REQUIRE GROUP: <EMPTY>
LDAP DENY GROUP: <EMPTY>

LDAP USER SEARCH:
[
"OU=Users-DEV,DC=DEV,DC=ACME,DC=local",
"SCOPE_SUBTREE",
"(sAMAccountName=%(user)s)"
]

LDAP GROUP SEARCH:
[
"dc=DEV,dc=ACME,dc=local",
"SCOPE_SUBTREE",
"(objectClass=user)"
]

LDAP USER ATTRIBUTE MAP:
{
"first_name": "givenName",
"last_name": "sn",
"email": "mail"
}

LDAP GROUP TYPE PARAMETERS:
{
 "name_attr": "cn",
 "member_attr": "member"
}

##### EXPECTED RESULTS
![login](https://user-images.githubusercontent.com/12199747/69373561-fcdc9480-0c9b-11ea-868e-ac56e2aa87d6.PNG)

Successfully authenticate against Active Directory

##### ACTUAL RESULTS
Invalid username and/or password. Please try again.

**Comment by ryanpetrello** [comment]
Hey @calimerosolo,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install or AWX feature, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
