### ISSUE TITLE
Actually support check mode in AWX collection

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#5383]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Check mode allows a user to see what changes would be made.

The AWX collection "supports" check mode by testing the connection.

https://github.com/ansible/awx/blob/8cb7b388dc122859756645f39f16a609c97d23e5/awx_collection/plugins/module_utils/ansible_tower.py#L80-L87

@john-westcott-iv started on doing this right in https://github.com/ansible/awx/pull/5337

Since we are removing tower-cli, it's categorically unavoidable that we are going to be re-implementing the client-side differ (this is a good thing, the old one was not very good). When that gets done, it makes complete sense to just build the check mode into the design.

**Comment by beeankha** [comment]
This work is being done in the current AWX Collections conversion PR: https://github.com/ansible/awx/pull/5747

**Comment by beeankha** [comment]
PR https://github.com/ansible/awx/pull/5747 has been merged.  New logic in the `module_util` file (`tower_api.py`) contains logic to support true check mode, closing this issue!
