### ISSUE TITLE
AWX starts and runs but returns 502

### ISSUE THREAD

**Issue by inhumantsar** [ansible/awx#5384]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Containerized AWX install running under Docker Swarm was running fine until yesterday. Users started getting 502s, none of the containers were returning errors. rebuilt the stack, reusing existing DB files. issue remains. 

after a subsequent rebuild, postgres started to throw database errors matching reports in #1618 (see logs below).

##### ENVIRONMENT
* AWX version: Docker image tag "latest" pulled on Nov 22 2019 @ 1622 UTC
* AWX install method: docker on linux
* Operating System: CentOS 7
* Web Browser: Chrome latest stable

##### STEPS TO REPRODUCE

Restart containers, remove and rebuild individual containers, remove and rebuild entire stack.

##### EXPECTED RESULTS

AWX starts without error, UI is accessible and functional

##### ACTUAL RESULTS

AWX starts without error, UI returns 502

##### ADDITIONAL INFORMATION

[awx_task.txt](https://github.com/ansible/awx/files/3880692/awx_task.txt)
[awx_web.txt](https://github.com/ansible/awx/files/3880693/awx_web.txt)
[pgsql.txt](https://github.com/ansible/awx/files/3880694/pgsql.txt)
[rabbit.txt](https://github.com/ansible/awx/files/3880695/rabbit.txt)

**Comment by ryanpetrello** [comment]
@inhumantsar,

> Docker image tag "latest" pulled on Nov 22 2019 @ 1622 UTC

This isn't _generally_ something we test extensively or provide help with unless an explicit bug can be identified.  You might have better luck with the latest official release of AWX.

Also, this issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
