### ISSUE TITLE
Help text in Host Name field appears to be missing examples

### ISSUE THREAD

**Issue by tvo318** [ansible/awx#5386]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Host name field in inventory create host form has help text that begins with "Examples include: " but does actually provide any examples.

![image](https://user-images.githubusercontent.com/7514801/69465377-44b3f800-0d3e-11ea-9072-f6a5523c6f98.png)

##### ENVIRONMENT
- Tower version: 3.6.0
- AWX install method: yolo #6631: Instance URL - https://ec2-34-238-249-200.compute-1.amazonaws.com
- Ansible version: 2.10.0.dev0
- Operating System: Mac Mojave 10.14.6
- Web Browser: Version 78.0.3904.87 (Official Build) (64-bit)

##### STEPS TO REPRODUCE
1. Go to Inventories
2. Create a new inventory and Save
3. Go to Hosts and create a new host
4. Open the tooltip in the first field "Host Name" and examine text 

##### EXPECTED RESULTS

The last sentence should have valid examples.

##### ACTUAL RESULTS
 
The last sentence begins with "Examples include:" but nothing is provided.

##### ADDITIONAL INFORMATION

None

**Comment by AlanCoding** [comment]
what it was supposed to have:

https://github.com/ansible/awx/blob/dbcc3c5733336d28a70065dd22f21adb9166d8b8/awx/ui/client/src/inventories-hosts/inventories/related/groups/related/nested-hosts/group-nested-hosts.form.js#L48-L54

**Comment by jakemcdermott** [comment]
ready for test once this actually merges: https://github.com/ansible/awx/pull/6261

**Comment by dsesami** [comment]
Examples are now included within the tooltip.
