### ISSUE TITLE
import mysql.connector ImportError: No module named mysql.connector

### ISSUE THREAD

**Issue by kazim1838** [ansible/awx#5387]
Hi 
I am facing issue while syncing Ansible AWX inventory-script 

import
mysql.connector ImportError: No module named mysql.connector

**Comment by wenottingham** [comment]
That looks like you're using a custom inventory script that uses mysql, but you haven't installed the necessary dependencies in your container. In any case, this isn't a bug in AWX, which is what this repo is for. This is better suited for the upstream mailing list and/or IRC channel where user questions are discussed.
