### ISSUE TITLE
Three panels shown on certain inventory views

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#539]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
The design for the inventory view is to only ever show two panels at a time.  I suspect that after the angular/ui-router upgrades something has gone sideways with the directive that we wrote to enforce this.

##### STEPS TO REPRODUCE

1. Create an inventory
2. Create a host
3. Edit the newly created host

All three panels are shown when only the top two should be:

<img width="1378" alt="screen shot 2017-10-31 at 3 27 27 pm" src="https://user-images.githubusercontent.com/9889020/32244791-114e70ba-be50-11e7-809f-3db76e0d9d6e.png"><img width="1373" alt="screen shot 2017-10-31 at 3 27 36 pm" src="https://user-images.githubusercontent.com/9889020/32244790-113cdad0-be50-11e7-931d-d00876e89d68.png">

Ping @trahman73 just so you're aware

**Comment by jaredevantabor** [comment]
This should be fixed in devel.
