### ISSUE TITLE
Push awx web and task to docker hub

### ISSUE THREAD

**Issue by kakawait** [ansible/awx#54]
What do you think about pushing (not manually) both images awx_task and awx_web on docker hub. In order to allow anybody deploy awx on docker stack without performing pre-install phase

**Comment by MartinTerp** [comment]
They stated in another issue: 

> This is something we are considering for the future

And i think alot of people will build the images themself, rather than pulling images from non-ansible repo, since there is alot of sensitive info on awx ( or can be )

But yes, hopefully there will be official docker hub images from RedHat

**Comment by wwitzel3** [comment]
Hi @kakawait as mentioned by @MartinTerp we are considering this in the future. Cheers!

link #35
