### ISSUE TITLE
Custom email notification for workflow approval/deny doesn't work

### ISSUE THREAD

**Issue by jainnikhil30** [ansible/awx#5401]
##### ISSUE TYPE
Custom email notification for workflow approval/deny doesnt work

##### SUMMARY
Custom email notification for workflow approval/deny doesnt work. It sends a blank email with no subject and body.

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: docker on linux
* Ansible version: 2.8.5
* Operating System: RHEL 7.6
* Web Browser: Google Chrome 78

##### STEPS TO REPRODUCE

1.) Create an Email Notification
2.) Enable the custom notification
3.) Create a workflow with approval node in it. 
4.) Enable all the 4 options for notification on workflow (APPROVAL, START, SUCCESS, FAILURE)
5.) Run the workflow.

##### EXPECTED RESULTS
While workflow waits for approval to be approved/denied. It should send a notification email with details.

##### ACTUAL RESULTS
It send an blank email with blank subject and body

**Comment by jainnikhil30** [comment]
Also, after the actual notification is approved/denied. There is no email which is being sent. But if I setup a slack notification. I see following notifications:

```
The approval node "approval-1" needs review. This node can be viewed at: https://localhost/#/workflows/43837
The approval node "approval-1" was denied. https://localhost/#/workflows/43837
```

**Comment by appuk** [comment]
I verified this on a devel instance and it sends a custom email notification with appropriate subject and body, hence closing the issue
