### ISSUE TITLE
Stuck in: AWX is Upgrading Page

### ISSUE THREAD

**Issue by ryan012880** [ansible/awx#5402]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After container image rebuild to latest commit of 9.0.1, AWX is stuck in the upgrading page once AWX stack starts. Note that AWX has existing data that is already running in version 9.0.1 before Merged: #5390

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: docker on linux
* Ansible version:  2.8.5
* Operating System: RHEL7 (docker host)
* Web Browser: Chrome

##### STEPS TO REPRODUCE

NOTE: AWX must have existing data from the old AWX version

1. Upgrade to AWX version 9.0.1 before Merged: #5390 
2. Rebuild the container image from the latest commit after Merged: #5390
3. After AWX start use the browser to navigate to AWX URL

##### EXPECTED RESULTS

1. Should show the AWX login page

##### ACTUAL RESULTS

1. Stuck in AWX upgrading/migration page infinitely.

**Comment by ryanpetrello** [comment]
Hey @ryan012880,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by ryan012880** [comment]
@ryanpetrello noted, thanks
