### ISSUE TITLE
Remove credential field when inventory is sourcing from a project

### ISSUE THREAD

**Issue by mdinwoodie** [ansible/awx#5404]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
When creating an inventory that sources from a project, the credential attached to the project is used to connect and the credential field in the inventory source details is unnecessary. Removing this field entirely would clear up any confusion on if the field is required or not.

**Comment by AlanCoding** [comment]
It's a completely valid use case to apply credentials to inventory sources from SCM. What if your inventory file is `awx_ec2.yml`? Then you either need to attach a credential of the built-in AWS type, or go make your own type with whatever injectors you need for your particular task. This is completely separate from the SCM credentials (for projects), which will not be applied to inventory updates at all. The inventory update gets the source tree, it does not get the project's credentials. It would be a security issue if it did.
