### ISSUE TITLE
Change Wording for Templated Notification

### ISSUE THREAD

**Issue by beeankha** [ansible/awx#5405]
##### SUMMARY

Currently, the label for the templated notification for "approval nodes needing approval" is `WORKFLOW RUNNING MESSAGE`:

<img width="517" alt="Screen Shot 2019-11-26 at 10 40 29 AM" src="https://user-images.githubusercontent.com/28930622/69664011-7a662300-1055-11ea-9bb2-c191182decf4.png">

If this could instead be changed to something like `WORKFLOW PENDING APPROVAL MESSAGE`, it would be more clear that this is for when approval nodes need review/approval, vs. for when the overall workflow is running in general.

Please note, this will have to be changed for both Message and Body options.

**Comment by dsesami** [comment]
The labels have been updated in tower/devel and appear normally.

**Comment by dsesami** [comment]
Reopening for docs. cc @tvo318

**Comment by dsesami** [comment]
Closing out this issue since tvo has finished up docs. 👍
