### ISSUE TITLE
Admin rights to install in openshift

### ISSUE THREAD

**Issue by zaskan** [ansible/awx#5410]
##### ISSUE TYPE
Suggestion

##### SUMMARY
One of our customers suggest to avoid high privileges escalation in order to install Tower over Openshift. He desisted to install Tower for this reason.

**Comment by ryanpetrello** [comment]
Hey @zaskan,

This issue tracker is for tracking feature enhancements and bugs to the open source AWX project itself (not Red Hat Ansible Tower).

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
