### ISSUE TITLE
Replacement of RabbitMQ to eliminate complexity

### ISSUE THREAD

**Issue by velzend** [ansible/awx#5414]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

**Replace RabbitMQ with Receptor**

To eliminate the complexity of RabbitMQ, Receptor was introduced and pushed forward as the replacement during [The Future of Ansible Tower talk, at Ansible Fest 2019 in Atlanta](https://www.ansible.com/hubfs//AnsibleFest%20ATL%20Slide%20Decks/Ansible%20Futures%20-%20Ansiblefest%20Atlanta%202019.pdf).

[Receptor Git project](https://github.com/project-receptor/receptor)

How should we move this feature forward?

Related Git issues/ feature ideas: 
 - [Move all execution to execution nodes managed via receptor network](https://github.com/ansible/awx/issues/5151)

**Comment by ryanpetrello** [comment]
Hey @velzend,

This is on our radar and something we intend to track as part of https://github.com/ansible/awx/issues/5151

**Comment by ryanpetrello** [comment]
also see: https://github.com/ansible/awx/issues/5443
