### ISSUE TITLE
SCM update stuck on TASK [detect requirements.yml]

### ISSUE THREAD

**Issue by alex-peyrard** [ansible/awx#5415]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
On a newly installed awx with docker compose, when launching a job with a git SCM, the SCM Update job hangs on the TASK [detect requirements.yml] step indefinitely

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.1
* Operating System: Centos7
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Install awx on centos7 with docker-compose
Create git credential
Create machine credential
Create inventory
Create project using this git credential
Create job template
Run job template

##### EXPECTED RESULTS

SCM Update step checks out the git repository and succeeds

##### ACTUAL RESULTS

SCM Update job stays stuck on TASK [detect requirements.yml] step

**Comment by ryanpetrello** [comment]
@alex-peyrard,

Have you done any debugging on the underlying host to see if the `ansible-playbook` process seems to be stuck/hung?  Any screenshots you could share?

This seems fairly innocuous:

https://github.com/ansible/awx/blob/devel/awx/playbooks/project_update.yml#L133

**Comment by alex-peyrard** [comment]
Here's some screenshots,

This job has been running for about an hour.
![stuck_job](https://user-images.githubusercontent.com/58302318/69966163-b85bbf00-150d-11ea-85a3-40f5368025e7.png)

The project:
![project](https://user-images.githubusercontent.com/58302318/69966203-d32e3380-150d-11ea-9fda-2fc8fb8a015b.png)

The job template:
![job_template](https://user-images.githubusercontent.com/58302318/69966273-f2c55c00-150d-11ea-9999-b9e995d3d247.png)

The playbook is a pretty simple one i've been using for testing, but I don't think It matters here.
Here's the git files. I have tried both with and without a requirements.yml
![git_files](https://user-images.githubusercontent.com/58302318/69966423-446de680-150e-11ea-9701-60499cfe0027.png)


I am not sure how to debug this or where to find helpful logs.
However, I see the hosts memory is almost full, I will try increasing the memory.

**Comment by alex-peyrard** [comment]
After increasing my hosts memory, the tasks now finishes successfully.

Thank you

**Comment by marvingoetz** [comment]
@alex-peyrard Got the same problem, with how much memory did it solve the problem?

**Comment by alex-peyrard** [comment]
@marvingoetz I found this in the install guide, so I set it to 4GB
https://github.com/ansible/awx/blob/devel/INSTALL.md#system-requirements

**Comment by r-okui** [comment]
In my case, this happens only once time after updating AWX. 
When "detect collections/requirements.(yml/yaml)" task gets stuck, cancel and relaunch the job will success.
(docker on linux, AWX 15.0.1, Ansible 2.9.15, CentOS 7, 2GB mem)

**Comment by danielo515** [comment]
Cancelling and relauncing seems to work on AWX 17.0.1, but it does not fix it definitely (at least not so far)
