### ISSUE TITLE
Playbooks stored in directories that start with `.` do not show up in the interface

### ISSUE THREAD

**Issue by pschmitt** [ansible/awx#5419]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Playbooks stored in hidden directories do not show up in the interface.

##### ENVIRONMENT
* AWX version: 9.0.1.0
* AWX install method: docker on linux
* Ansible version:  2.8.5
* Operating System: Linux
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Place a playbook in a directory that starts with `.`. It won't show up in the Playbook select widget.
Example structure:

```
test-root.yml
.hidden/test-hidden.yml
nothidden/test-nothidden.yml
```

##### EXPECTED RESULTS

Be able to select all 3 of the playbooks from the example above.

##### ACTUAL RESULTS

Only `test-root.yml` and `nothidden/test-nothidden.yml` are showing up in the interface.

**Comment by ryanpetrello** [comment]
This looks like intentional behavior:

https://github.com/ansible/awx/blob/devel/awx/main/utils/ansible.py#L34

@AlanCoding @matburt you have any opinions about relaxing this?

**Comment by AlanCoding** [comment]
including hidden _directories_ could result in a lot more in the listing. I don't think we have a limit on the playbook file listing anymore, so this is a viable change to make. But we don't have a good solution for picking out playbooks from a large list.

**Comment by matburt** [comment]
This is the whole point of hidden directories.

**Comment by pschmitt** [comment]
Yes and no.

I just want to be able to manually set the path to a playbook.

**Comment by AlanCoding** [comment]
If you check the box to allow branch override on the project it should let you do this, although maybe only by using the API browser.

**Comment by matburt** [comment]
Yep the api allows manual specification of the path to the playbook... I'm not sure the UI allows this though.
