### ISSUE TITLE
The job Console  not refreshed automatically when launching template , need to refresh the browser in order to see it

### ISSUE THREAD

**Issue by famantanantsoaandry** [ansible/awx#5421]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

The job Console  not refreshed automatically when launching template , need to refresh the browser in order to see it

##### ENVIRONMENT
* AWX version: 6.0.0 , 9.0.0
* AWX install method: docker/openshift 
* Ansible version:  2.8.5
* Operating System: Any OS
* Web Browser: Any browser

##### STEPS TO REPRODUCE

Just Launch any template , or a job, normally the job web console should be up to date in real when the playbook is execution through the steps

I tried two versions of AWX ( 6.0.0) on our production and 9.0.0 ( the latest one  ) , but the issues is staying the same 

##### EXPECTED RESULTS

The web interface should be up date , when the playbook run , We should not refresh the browser

##### ACTUAL RESULTS

![AWX interface not up to date](https://user-images.githubusercontent.com/48446952/69965098-ce6c7e00-1513-11ea-88a5-b14a32a577dc.PNG)

**Comment by ryanpetrello** [comment]
Hey @famantanantsoaandry,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
