### ISSUE TITLE
LDAP authencation setting not save to database

### ISSUE THREAD

**Issue by hotsnow** [ansible/awx#543]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Authencation setting not save to database

##### ENVIRONMENT
* AWX version: 1.0.1.120
* AWX install method: docker on linux
* Ansible version:  2.4.1.0 
* Operating System: Linux
* Web Browser: Chrome

##### STEPS TO REPRODUCE

The LDAP authentication setting ok in the web page, but after logout and login again, I found out the setting not there. go the database and found out the setting not updated to the database. So, just update the database manually, and then it works.
sometimes you can see the setting was lost when you change the other tab and then go back.
looks like the setting stored in user session but database update failed.

**Comment by matburt** [comment]
I wonder if you are running into the same issue here: https://github.com/ansible/awx/issues/537

Can you examine the response payload from the api?

**Comment by matburt** [comment]
Let us know if you are able to provide us some more information, otherwise I'm going to close this.
