### ISSUE TITLE
What is the file vendor.*.js in my AWX web container?

### ISSUE THREAD

**Issue by sammybenjamin** [ansible/awx#5432]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME

  - UI

##### ENVIRONMENT
* AWX version: 2.7.9
* AWX install method: docker on linux
* Ansible version:  2.7.9
* Operating System: Redhat Linux v7.7
* Web Browser: Chrome Version 78.0.3904.10

**Comment by sammybenjamin** [comment]
Additional details not captured while opening the case.

##### SUMMARY

What is the file vendor.8778ab7be905d20927b3.js in my AWX web container and how to upgrade its bootstrap to 4.4.1 ?

##### STEPS TO REPRODUCE
 N/A 

##### EXPECTED RESULTS
 N/A

##### ACTUAL RESULTS
 N/A 

##### ADDITIONAL INFORMATION

File in docker container awx_web : 
    /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/ui/static/js/vendor.8778ab7be905d20927b3.js

**Comment by ryanpetrello** [comment]
Hey @sammybenjamin,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by sammybenjamin** [comment]
My organization security team has flagged a security exposure to use older versions of  jquery-1.12.4.min.js  (update to 3.4.10), and bootstrap 4.1.3 (update to 4.4.1) due to known vulnerabilities.

This should be handled in the development stream to add a fix to the deployed AWX installation.

**Comment by ryanpetrello** [comment]
Modern versions of AWX use jQuery 3.4.1:

https://github.com/ansible/awx/pull/3891

What version of AWX are you running?

**Comment by sammybenjamin** [comment]
AWX version is 2.7.9

**Comment by ryanpetrello** [comment]
@sammybenjamin that's an Ansible version, not an AWX version:

https://github.com/ansible/awx/releases

From one of your AWX hosts, you can run:

`awx-manage --version`

**Comment by sammybenjamin** [comment]
# awx-manage --version
4.0.0.0

**Comment by ryanpetrello** [comment]
@sammybenjamin you'll want to upgrade to a newer version of AWX if you want a newer version of jQuery.

I recommend the latest (9.0.1).

**Comment by sammybenjamin** [comment]
Thank you @ryanpetrello for your prompt advice.

**Comment by mabashian** [comment]
Just for reference - the `vendor.*.js` file is generated when the web application is compiled.  It's a generated file - not meant to be edited.  We use webpack to bundle our vendor files as well as our source code.  That file is generated based on the dependencies specified in [here](https://github.com/ansible/awx/blob/eea97c89286bca0c029f8f187f610fb2d1aac48d/awx/ui/package.json#L97).  You can see the webpack config files [here](https://github.com/ansible/awx/tree/eea97c89286bca0c029f8f187f610fb2d1aac48d/awx/ui/build)

Some time ago [we bumped Bootstrap up to 4.3.1](https://github.com/ansible/awx/pull/3703).  Upgrading to the latest (9.0.1) will give you that.  You might be able to bump that up to 4.4.x yourself after upgrading AWX but I have no idea what that might break.
