### ISSUE TITLE
Playbook selection dropdown doesn't detect master playbooks that use import_playbook statements and not have a - hosts attribute defined.

### ISSUE THREAD

**Issue by cesan3** [ansible/awx#544]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
master playbook that imports others doesn't show up in the playbook selection drop-down list.
##### ENVIRONMENT
* AWX version: 1.0.1.35
* AWX install method: docker
* Ansible version:  2.4.0
* Operating System: Fedora
* Web Browser: Firefox

##### STEPS TO REPRODUCE
Commit a master playbook that import other to your project, without adding a -hosts attribute
- import_playbook: play1.yml
- import_playbook: play2.yml  
- import_playbook: play2.yml

##### EXPECTED RESULTS

The master playbook should appear in the drop-down list

##### ACTUAL RESULTS

The master playbook doesn't show up. Only if I do this, it appears:

```
- hosts: all
  gather_facts: no

- import_playbook: play1.yml
- import_playbook: play2.yml  
- import_playbook: play2.yml
```

**Comment by sjenning** [comment]
playbook filtering is done here
https://github.com/ansible/awx/blob/devel/awx/main/utils/ansible.py#L42-L57
