### ISSUE TITLE
Cannot tell apart inventory updates from same inventory

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#545]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
When I update an inventory and look at the jobs list, I can't tell _which_ inventory _source_ I updated

##### ENVIRONMENT
* AWX version: 1.0.1
* AWX install method: docker for mac

##### STEPS TO REPRODUCE
Create 1 inventories, and 2 inventory sources inside of it.

Launch both inventory sources.

Go to JOBS in UI.

##### EXPECTED RESULTS

I can tell apart updates from the 2 different sources.

##### ACTUAL RESULTS

Cannot.

The API generates the name for the inventory updates.

###### my example

In the API for both updates, you find:

```json
 "name": "Custom Script Example",
 ```

the user experience for the inventory sources view:
(you can easily tell the two apart here)

![screen shot 2017-11-01 at 10 05 40 am](https://user-images.githubusercontent.com/1385596/32278601-8c7e4a84-beec-11e7-93a5-bdda08146a44.png)

for the jobs list:
(you can not tell the two apart at all)

![screen shot 2017-11-01 at 10 05 53 am](https://user-images.githubusercontent.com/1385596/32278629-9fb03d2e-beec-11e7-81c8-64f07cafbd06.png)

##### ADDITIONAL INFORMATION

Ping @trahman73 

The API can solve this by changing its algorithm for how it names the inventory update.

Note that when the UI navigates to the inventory update details view, it erroneously gives the NAME as the name of the inventory source.

One suggestion might be to have the inventory update name be `(<inventory name> + <inventory source name>)`.

**Comment by trahman73** [comment]
@AlanCoding Your suggestion of appending the inventory source name to the inventory seems like the easiest/best approach.

**Comment by AlanCoding** [comment]
Link #808 and closing
