### ISSUE TITLE
unable to use azure-cli 

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/awx#5453]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Using azure-cli in AWX fails.

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.2

##### STEPS TO REPRODUCE

```
docker exec -it awx_task bash
yum install -y python3-devel gcc
pip3 install ansible --upgrade
pip3 install azure-cli
az --version
```
Azure-cli installs fine and az --version shows correct output. 

Using AWX via web interface however fails. This has worked until AWX 7.0.0

##### ACTUAL RESULTS

```
- name: Login
  command: az login --service-principal -u '{{ client_id }}' -p '{{ secret }}' --tenant '{{ tenant }}'
  delegate_to: localhost
```

results in...

```
/usr/bin/python3.6: No module named azure.cli.__main__; 'azure.cli' is a package and cannot be directly executed
```

**Comment by strahinjanis** [comment]
The same here, did you try maybe with 9.1.0?

**Comment by nicolaibaralmueller** [comment]
> The same here, did you try maybe with 9.1.0?

@strahinjanis Yes and as a consequence we are shifting to azure-cli containers for any scripting. It is not good to install stuff on containers post image creation.

**Comment by strahinjanis** [comment]
Thanks for the reply @nicolaibaralmueller , I was thinking about the same, to add one microsoft/azure-cli container, beside awx_* ones, then whenever "az ...." comes into the play (because az modules can't obviously cover everything) go with remote shell execution there.
Still, the "original" idea, although a bit quick & dirty sounds as a very convinient one.

**Comment by nicolaibaralmueller** [comment]
@strahinjanis This is a way to use docker with azure cli. However passing complex azure cli commands containing special characters might become an issue. 

[https://medium.com/@iced_burn/azure-cli-docker-containers-7059750be1f2](url)

[https://stackoverflow.com/questions/59284285/azure-cli-docker-container-unable-to-take-command](url)

**Comment by Sreenadh8** [comment]
+1 , same issue here, even awx 9.1.1 , does someone has any workaround or resolution.?

**Comment by ryanpetrello** [comment]
In order for this to work, you'll either need to install `azure-cli` *into* the Ansible virtualenv, _or_ (this is probably preferable) create a custom virtualenv as described at:

https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md

```shell
bash-4.4$ source /venv/ansible/bin/activate
(ansible) bash-4.4$ pip3 install azure-cli
(ansible) bash-4.4$ az --version
azure-cli                          2.6.0

command-modules-nspkg              2.0.3
core                               2.6.0
nspkg                              3.0.2 *
telemetry                          1.0.4

Python location '/venv/ansible/bin/python3'
Extensions directory '/var/lib/awx/.azure/cliextensions'

Python (Linux) 3.6.8 (default, Nov 21 2019, 19:31:34)
[GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]

Legal docs and information: aka.ms/AzureCliLegal
```

<img width="495" alt="image" src="https://user-images.githubusercontent.com/214912/83414879-32510000-a3ec-11ea-8d2f-138729988f50.png">

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/214912/83414856-2a915b80-a3ec-11ea-94b6-af02892c28cd.png">

**Comment by Sreenadh8** [comment]
Hi @ryanpetrello ,

thank you so much for quick update, i just did install azure-cli on 'Ansible' virtenv , unfortunately i am still facing the same error, i am using awx 9.3.0... below is the cli installation on Ansible virtenv, any other thought please...

--------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/41424639/83435122-4f6fe800-a459-11ea-9cc9-961784e2d339.png)

-------------------------------------------------------------------------------------------------------------
error:

![image](https://user-images.githubusercontent.com/41424639/83435068-349d7380-a459-11ea-9fb2-c48cd7c5942f.png)




Regards,
Sreenadh

**Comment by ryanpetrello** [comment]
Hey @Sreenadh8,

Have you tried on a newer version of AWX?  I'm not encountering this on 11.2.0.

**Comment by Sreenadh8** [comment]
Hi @ryanpetrello ,

I wish i could try it on newer version, but 9.3.0 runs on RabbitMq and our AWX active-active HA cluster working well and its serving a production work for us now, hence we couldn't upgrade to latest as rabbitmq replaced it with redis...

Further i installed "pip3 install azure.cli" separately in Ansible virtenv itself, now above mentioned is gone... 
but it's not able to log-in and run azure cli commands as expected manner, wait for manual az login/setup despite that i am providing Azure valid creds from awx GUI....

on another note, does latest version awx11.2.0 supports active-active HA cluster by any chance ?, we are using AWX very effectively more than 3000 hosts and its working well.. we love it, thanks for your help..

![image](https://user-images.githubusercontent.com/41424639/83440531-b776fc00-a462-11ea-8447-bbc2275801d4.png)

Regards,
Sreenadh

**Comment by wenottingham** [comment]
> I wish i could try it on newer version, but 9.3.0 runs on RabbitMq and our AWX active-active HA cluster working well and its serving a production work for us now, hence we couldn't upgrade to latest

That's fine, but that's not within the goals of the AWX project as it currently stands.  See the ![FAQ](https://www.ansible.com/products/awx-project/faq ) for details.

If you are interested in a longer-term supported product, that provides maintenance and potential fixes, we suggest contacting your Red Hat rep.

**Comment by Sreenadh8** [comment]
Hi @ryanpetrello @wenottingham ,

thanks for your response and update, just to update that, on 9.3.0, created a new brand venv and installed azure-cli in it... but still same error even in 'venv', any workaround until we upgrade latest version.

![image](https://user-images.githubusercontent.com/41424639/83509460-18491780-a4e9-11ea-9839-f1bf08752967.png)

**Comment by mili988** [comment]
+1 same issue here, after update from 12.x to latest (17.1.0).

We use awx workflows where some of the templates have "az" shell commands. The funny thing is that there are 3 templates that fire az commands via shell (two of them work after the update) and one does not. awx is a docker container..
Before updating everything worked without problems...

![image](https://user-images.githubusercontent.com/66796344/112044451-20db0f00-8b4a-11eb-90c9-88247c7932b1.png)
![image](https://user-images.githubusercontent.com/66796344/112044215-d35ea200-8b49-11eb-8a01-b44e29049bf4.png)
