### ISSUE TITLE
UNREACHABLE! failed to connect to the host via ssh

### ISSUE THREAD

**Issue by JRobinson333** [ansible/awx#5454]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
A node on the host network cannot be pinged from Ansible AWX despite firewalls from both the host node and target node being disabled completely. 

From my investigations so far, there is no route set up inside of the container and awxcompose_default network could be related to the issue. Are overlay networks required?

Adding a route as per solution #2 in below webpage does not solve the issue:
https://stackoverflow.com/questions/36882945/change-default-route-in-docker-container

Please help, particularly if there is something more obvious that I have missed in the configuration.

I tried the IRC channel but no responses there.

##### ENVIRONMENT
* AWX version: 2.8.2
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: CentOS 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Clean install of Ansible AWX, Gogs, 3rd Node on Host network.

##### EXPECTED RESULTS

Successful installations of both Ansible AWX and Gogs (that part is ok).
Successful connection between AWX and Gogs to retrieve git project (that part is ok).
Successful ssh connection established to 3rd node on host network (that part is problematic).

##### ACTUAL RESULTS

Below message issued during running of playbook:
"UNREACHABLE! failed to connect to the host via ssh"

**Comment by s10g** [comment]
SELinux~

**Comment by JRobinson333** [comment]
I've closed this issue down as I got a resolution but if anyone else stumbles across this one double check your SELinux and do a simple reboot.

We had it pinned down to a an issue in the route tables but running a freshly source alpine image didn't give the same issue despite the ip routes being the same...
