### ISSUE TITLE
Unable to see Job details after some time of using AWX

### ISSUE THREAD

**Issue by dragan-vucanovic-devtech** [ansible/awx#5455]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 1.0.6.16
* AWX install method: docker on linuxr
* Ansible version:  2.5.4
* Operating System: Windows 10
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

After some time, it's not possible to see Job details from Web Gui, when clicking on JOBS-job name, for a brief period of time  i see "Cog" and "Working" then nothing happens.
Workaround is to kill all running containers and create it again, it works for couple of weeks but again issue reappear

##### EXPECTED RESULTS

To see Job details when clicking on Job

##### ACTUAL RESULTS

Unable to see Job details

**Comment by ryanpetrello** [comment]
Hey @dragan-vucanovic-devtech,

AWX 1.0.6 is nearly 18 months old now - we've since fixed a number of issues, including ones similar to what you've described.

Give things a try on a newer version of AWX and let us know if you're still encountering problems.
