### ISSUE TITLE
Ability to Set ansible.cfg on an Organizational Level

### ISSUE THREAD

**Issue by falcon78921** [ansible/awx#5458]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Per a customer's request, they would like to be able to set `ansible.cfg` for use on an Organizational level.

**Comment by wenottingham** [comment]
We are unlikely to do this as specified; depending on how ansible.cfg exists in a project this could have all sorts of odd interactions.

It is best tackled as part of https://github.com/ansible/awx/issues/5157
