### ISSUE TITLE
Make AWX collection adhere to newly introduced sanity test rule

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#5465]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
See https://github.com/ansible/ansible/pull/65437

A new rule was added, and our modules do not pass. We need to fix this or otherwise we will be out of compliance.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

`make test_collection_sanity`

##### EXPECTED RESULTS

it always passes, I am not surprised by unexpected failures

##### ACTUAL RESULTS

```
Running sanity test 'use-argspec-type-path' with Python 3.6
Running sanity test 'use-compat-six' with Python 3.6
Running sanity test 'validate-modules' with Python 3.6
ERROR: Found 2 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/tower_project.py:0:0: doc-required-mismatch: Argument 'name' in argument_spec is not required, but is documented as being required
ERROR: plugins/modules/tower_role.py:0:0: doc-required-mismatch: Argument 'role' in argument_spec is not required, but is documented as being required
See documentation for help: https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/validate-modules.html
Running sanity test 'yamllint' with Python 3.6
ERROR: The 1 sanity test(s) listed below (out of 41) failed. See error output above for details.
validate-modules
```

**Comment by thedoubl3j** [comment]
working on this, should have a patch soon @AlanCoding I also caught a few more that I will add into it

**Comment by AlanCoding** [comment]
quick heads up to @squidboylan that this is landing now. It shouldn't affect any observable behavior and I'll probably close this issue myself later.

**Comment by squidboylan** [comment]
@AlanCoding can we close this now?

**Comment by AlanCoding** [comment]
given confirmation that sanity tests pass, absolutely
