### ISSUE TITLE
[AWX collection] Computed changed status based on API return values

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#5474]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
This replaces the two issues where the value of a field transforms from what the client provides, to what is returned in subsequent API requests.

 - https://github.com/ansible/awx/issues/5321 credential type `inputs`
 - https://github.com/ansible/ansible/issues/64734 JT `survey_spec`

As a general principle, given values cannot be assumed to be saved in the form they are given. However, POST, PATCH, etc. return a serialization of an object.

Something should only be considered changed when the prior model value differs from the value returned from the API on the PATCH or PUT request (POST always changes or fails).

##### ENVIRONMENT
* AWX version: 9.0.1

##### STEPS TO REPRODUCE

See related issues, specifically nested JSON data often has entries like "default" or "type" added by the API

##### EXPECTED RESULTS

Running a module twice should always yield ok on the second try

##### ACTUAL RESULTS

task says it is changed every time it is subsequently ran.

##### ADDITIONAL INFORMATION

This will be dependent on some amount of refactoring, related to the tower-cli removal.

**Comment by AlanCoding** [comment]
Proposed method on top of the tower-cli removal PR: https://gist.github.com/AlanCoding/91af7a151be7f3ccb9c5d9c0fae7b5e4

**Comment by ryanpetrello** [comment]
@AlanCoding did this get into @beeankha's PR, or is there still work to do?

**Comment by AlanCoding** [comment]
Not done, it's a little riskier, but free to be attempted now with the refactor out of the way

**Comment by AlanCoding** [comment]
This was implemented with a warning statement for the cases that cannot be determined. @squidboylan already merged 1 related fix for it.

**Comment by squidboylan** [comment]
As is we cannot test the warning statement, but we have testing around the changed values that I am happy with.
