### ISSUE TITLE
Deleting Oauth token with itself throws 500 error

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#5478]
1. create an Oauth token for a user
2. delete the Oauth token using itself as the Bearer
`curl -k -H 'Authorization: Bearer r8jwGD25D9rIDQ6F1lqcRwrejR9gR7' -X DELETE https://localhost/api/v2/tokens/21/`
3. Observe HTTP 500

**Comment by ryanpetrello** [comment]
fixed by: https://github.com/ansible/awx/pull/5477

**Comment by kdelee** [comment]
Tried this out and works like a charm.
```
awx_1        | 2020-01-03 14:42:02,490 INFO     awx.api.authentication User elijah performed a DELETE to /api/v2/tokens/1/ through the API using OAuth 2 token 1.
awx_1        | 172.18.0.1 DELETE /api/v2/tokens/1/ - HTTP/1.1 204
```
