### ISSUE TITLE
JT vault credential select incorrectly allows multiple vault creds with the same vault-id

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5480]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Users can select any number of vault credentials to associate with a JT as long as each of those vault credentials has a different vault id.  If a credential with a certain vault id has already been selected and a user selects another credential with that same vault id the application will automatically unselect the original credential in favor of the second without conveying why that happens.  Here's an example:

![vault](https://user-images.githubusercontent.com/9889020/70560179-22034b00-1b56-11ea-8897-7672b9c51d9d.gif)

In UI next we aren't restricting any vault cred selections based on ID so the form will error at submission if two vault creds with the same id are selected.  We should re-think this UX and potentially come up with a different pattern that indicates that selecting two vault creds with the same id is not allowed.

**Comment by jlmitch5** [comment]
After talking with @trahman73, we've decided to keep the same ux in terms of checking a new box will uncheck others with that vault ID.  We'll add the note "Note: You cannot select multiple vault credentials with the same vault ID.  Doing so will automatically deselect the other with the same vault ID." at the top of the modal in the info version of this https://www.patternfly.org/v4/documentation/react/components/alert#inline-types

**Comment by dsesami** [comment]
Vault credentials with the same ID cannot be multi-selected. All other types, including vault credentials with a different ID, are able to be selected successfully. :+1:
