### ISSUE TITLE
Add a configurable option to copy the project source

### ISSUE THREAD

**Issue by mrmibrown** [ansible/awx#5483]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add the option to copy the project source for a job run.  Currently this is not configurable and large projects take longer while making local private copies.

**Comment by wenottingham** [comment]
Branch/revision is overridable, and changes have already landed to ensure that jobs are not blocked on pending project updates. Neither of those work if jobs do not run from a private checkout. (to say nothing of dealing with execution nodes that come and go.)
