### ISSUE TITLE
Missing Cancel Job button in job details page.

### ISSUE THREAD

**Issue by ilijamt** [ansible/awx#5485]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After switching your browser language to non English language (Dutch), the **Cancel Button** is missing from the screen. See attachment.

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: doocker
* Operating System: Windows 10
* Web Browser: Chrome 78.0.3904.108

##### STEPS TO REPRODUCE

Switch your browser language to Dutch.

##### EXPECTED RESULTS

See **Cancel Job** on the screen.

##### ACTUAL RESULTS

Missing **Cancel Job** on the screen.

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/1139427/70608545-98f51e00-1c00-11ea-8ac5-33805c818a43.png)

**Comment by dsesami** [comment]
I can confirm that both the pause and delete buttons are missing in both Dutch and Japanese (they're the same button location, it just changes depending on whether or not the job has finished running). The button appears normally in English.
![Screenshot from 2019-12-13 13-52-56](https://user-images.githubusercontent.com/19942822/70824278-ef548f00-1daf-11ea-9539-fb0f6e9c6b4c.png)
![Screenshot from 2019-12-13 13-52-43](https://user-images.githubusercontent.com/19942822/70824279-ef548f00-1daf-11ea-8136-ad1d14e9a78b.png)
![Screenshot from 2019-12-13 13-52-29](https://user-images.githubusercontent.com/19942822/70824280-ef548f00-1daf-11ea-8271-0b7b49437c24.png)

**Comment by dsesami** [comment]
update: 

the `ng-show` logic for the element is looking for english strings.
```
<button class="List-actionButton List-actionButton--delete ng-hide" data-placement="top" ng-click="vm.cancelJob()" ng-show="vm.status.value === 'Pending' ||
                     vm.status.value === 'Waiting' ||
                     vm.status.value === 'Running'" aw-tool-tip="取り消し" data-original-title="" title="">
            <i class="fa fa-minus-circle"></i>
        </button>
```
the value that's currently being returned is `Geslaagd` in the dutch translation, for example. This should be changed to an API value.

**Comment by dsesami** [comment]
this has been resolved and does not exist in devel -- closing.
