### ISSUE TITLE
[RFE] Allow visibility of instance groups to Org Auditor/Normal Users

### ISSUE THREAD

**Issue by benjdudas** [ansible/awx#5488]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Allow the visibility of assigned instance groups on an Inventory/Job Template to Org Auditors and users with `Use` permission on the resource. The config will be greyed out but still visible by the user from both the UI and `./api/v2/inventories/<id#>/instance_groups/`similar to how it is for System Auditors currently.

**Comment by wenottingham** [comment]
We'll look at this as part of the UI rewrite/refresh.

**Comment by wenottingham** [comment]
This is #4953
