### ISSUE TITLE
Adding support for Power Linux (ppc64le) platform

### ISSUE THREAD

**Issue by seth-priya** [ansible/awx#5492]
##### ISSUE TYPE
 - Add support to build awx on ppc64le

##### SUMMARY
I am creating this issue to discuss and seek the community's inputs, thoughts and feedback for the changes required to extend awx on IBM Linux on Power (ppc64le) platform and the approach to be adopted.

I have some preliminary set of changes at https://github.com/seth-priya/awx/commit/11103aedc63e346f6801c831680f75c7a6941077

Since centos:8 is not yet available for ppc64le, I have created separate architecture specific Dockerfiles, I also plan to update these to UBI 8 in due course.

**Comment by wenottingham** [comment]
See https://github.com/ansible/awx/issues/5279#issuecomment-551087497, we do not have plans for this.

**Comment by seth-priya** [comment]
@wenottingham thanks for you response, just wanted to understand if there are specific reasons you don't want to support this yet on Power and if there is any way we (@gerrith3, our team) can help address those from our side?  thank you

**Comment by wenottingham** [comment]
In this upstream project, we deliver containers for docker-compose or K8S/openshift installations on x86 only and do not have plans to expand the set of things we provide support for in the upstream repo/delivery. 

There is a community of people that maintain things such as RPM delivery of AWX (https://github.com/ansible/awx/issues/3542, etc). If that or a similar community wants to maintain a Power build we are not against it and will take code patches - we just don't have plans to build or support such a build in this repo.
