### ISSUE TITLE
InventoryGroup Details doesn't update

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#5502]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Variables doesn't update
##### ENVIRONMENT
* AWX version: 9.0
* AWX install method: docker for mac
* Ansible version:  2.10
* Operating System: Mojave
* Web Browser:Chrome

##### STEPS TO REPRODUCE

Go to Inventories ---> Click on Inventory--> Groups ---> Click on Group ---> Edit ---> Change something about the variables ---> Save

##### EXPECTED RESULTS

New Variables show up in details view
##### ACTUAL RESULTS

Old Variables show up

**Comment by AlexSCorey** [comment]
It seems like `currentValue` and `value` in `VariablesDetail.jsx` can get out of whack when updating InventoryGroup.

**Comment by unlikelyzero** [comment]
We will be writing out the manual steps we performed and open up a PR to our cypress tests which links to a stub

**Comment by appuk** [comment]
Verified the above bug on Inventory and Inventory group Edit page and it's working as expected.

Steps:
Go to Inventory/ Inventory Group Details page ---> Edit ---> Change something about the variables ---> Save ---> The updated variable is shows up in the Detail view.

Hence closing the issue.

**Comment by unlikelyzero** [comment]
Added testcase stubs here https://github.com/ansible/tower-qa/pull/4635
