### ISSUE TITLE
What happend to the Network Visualization???

### ISSUE THREAD

**Issue by MrMEEE** [ansible/awx#5506]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Hi guys..

What happend to the network visualization??

https://github.com/ansible/awx/pull/1352

**Comment by wenottingham** [comment]
We decided not to pursue it as a priority, so it was dropped.

**Comment by MrMEEE** [comment]
@wenottingham Isn't the Network Visualization included in Ansible Tower??

**Comment by wenottingham** [comment]
Nope.
