### ISSUE TITLE
Add text to nodes in workflow view to indicate success and failure

### ISSUE THREAD

**Issue by ghost** [ansible/awx#552]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY
The workflow view in AWX uses color to indicate success and failure of nodes.  The red/green color indication can be difficult to distinguish for some users.

##### ENVIRONMENT
* AWX version: 1.0.x

##### STEPS TO REPRODUCE

An added text status indication in the workflow view will allow a display of status that is independent of color.

**Comment by wenottingham** [comment]
cc @trahman73 for ideas

**Comment by trahman73** [comment]
@wenottingham @mabashian On the RUN view for workflows, we indicate success/fail with our regular status circle with tooltip and border color, which is sufficient.

The EDIT view we just use line color, which can be difficult to see, until the node is clicked for more info. We can add a text status to the nodes as a possible solution.
![image](https://user-images.githubusercontent.com/13351591/32333506-84035fd4-bfbe-11e7-9355-0236b3d258ad.png)

**Comment by mabashian** [comment]
<img width="993" alt="screen shot 2018-11-26 at 3 00 07 pm" src="https://user-images.githubusercontent.com/9889020/49038853-25ff3d80-f18c-11e8-81c3-b5fdf11201b9.png">

We've added tooltips on links to indicate whether they are always/success/failure but i think the original issue is talking specifically about the status circles that appear on the nodes as the corresponding job runs.  We should add an exclamation point to the circle like we do on the jobs list:

<img width="72" alt="screen shot 2018-11-26 at 3 02 04 pm" src="https://user-images.githubusercontent.com/9889020/49038900-4c24dd80-f18c-11e8-9d2f-3fe667af7440.png">

**Comment by wenottingham** [comment]
This is fixed in the new UI in AWX 17 or later.
