### ISSUE TITLE
Jobs get stuck in execution state when awx_task container is down

### ISSUE THREAD

**Issue by soniya20** [ansible/awx#5521]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Jobs get stuck in execution state when awx_task container is down

##### ENVIRONMENT
AWX version: 9.0.1
AWX install method: doocker
Operating System: rhel7.4
Web Browser: Chrome 78.0.3904.108

##### STEPS TO REPRODUCE
1. Login to AWX dashboard using admin credential.
2. Click on ""Templates' panel  and select 'Job Template' to create a new job template.
3. Fill all the required parameters in the job template creation form.
4. Now click on save button.
5. Stop the awx_task container by running the following command.
      $ docker stop <awx_task_container_id>
6. Now execute job template by clicking on the execution button of the job template.

##### EXPECTED RESULTS

Timeout or exception message should pop up after a  few seconds.

##### ACTUAL RESULTS
No exception or timeout message pop up  for job execution when awx_task is down.

**Comment by ryanpetrello** [comment]
@soniya20 this is just how task execution in AWX works - there's a background queue used to schedule and run playbooks in the background on the task container.  If you shut off the task container, and there are no other containers to run playbooks, the job will wait in the "pending" state until there is available capacity to run the job.

**Comment by soniya20** [comment]
Hi @ryanpetrello 
I understand that a background queue is maintained to schedule and run playbooks on task container and if the task container goes down, the queue would be reset and job would be lost. But, my concern is the indefinite wait in web container for the jobs present in the queue when the task container is down. 
In my understanding, there must be some timeout associated with the waiting job in web container so as to fail jobs in awx_web even when the task container is still down.

**Comment by ryanpetrello** [comment]
Hey @soniya20,

The way it's currently implemented, the job timeout is how long the job will be allowed to run, and the implementation is *in* the task management code that runs in the task container.  If there are no task containers, the job will just stay in pending until there are.
