### ISSUE TITLE
No warning or notification displayed while changing the only admin user privilege  from admin to normal.

### ISSUE THREAD

**Issue by soniya20** [ansible/awx#5522]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
No warning or notification displayed while changing the only admin user privilege  from admin to normal.

##### ENVIRONMENT
AWX version: 9.0.1
AWX install method: doocker
Operating System: rhel7.4
Web Browser: Chrome 78.0.3904.108

##### STEPS TO REPRODUCE
1. Login to AWX  dashboard with admin user.
2. Now click on users panel and  make sure there is only one user with admin privileges.
3. Now edit the admin user details and  change admin user privileges to normal user. 
4.  Click on save button. 

##### EXPECTED RESULTS

Warning or notification should be displayed while trying to change the privileges to last remaining admin user in AWX.

##### ACTUAL RESULTS

No warning or notification gets displayed while trying to change the only admin user privileges to normal user.

**Comment by soniya20** [comment]
Hi @ryanpetrello, 
 I have been working on a fix for this bug and have added a pop-up on modification of permissions of a user from Administrator to any other type. I have added the below conditional check in /awx_devel/awx/ui/client/src/users/edit/users-edit.controller.js
        if (user_obj.is_superuser === true && $scope.is_superuser === false ) 
        
Also, while investigating the bug I found that the default admin user can be deleted and can have its permissions changed from "administrator" to some other type. This could lead to account hijacking considering the fact that any user with administrator role can delete or modify the default admin user.
I wonder if this an expected behavior for the default admin user? If not, would it not be better to disable delete option and user_type options for the default admin user?

**Comment by soniya20** [comment]
1.

**Comment by unlikelyzero** [comment]
@soniya20 we have just release awx 16.0.0. Please give this another go!

**Comment by wenottingham** [comment]
This isn't something we'd plan to do in AWX.
