### ISSUE TITLE
can't manage docker from AWX

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx#5526]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I have a very simple playbook that does nothing besides run one command inside a docker container. Playbook is here: https://polr.eregion.de/1/8adc
It works fine from a commandline, but it does **not** work when executed from within AWX.
The second task fails with this output:

TASK [flush dns cache on {{ item }}] *******************************************
fatal: [akari.eregion.home]: FAILED! => {"msg": "docker command not found in PATH"}

##### ENVIRONMENT
* AWX version:7.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.6
* Operating System: openSUSE Leap 15.1
* Web Browser: firefox 71, reproduces independent from browser used.

##### STEPS TO REPRODUCE

For my particular case:
run unbound in a docker container, using secns/unbound from dockerhub, and call the container unbound1 so the playbook works as expected
run the playbook

##### EXPECTED RESULTS

I expect the playbook to work in AWX and on a commandline

##### ACTUAL RESULTS

the playbook works on the commandline, but not in AWX.

**Comment by shanemcd** [comment]
AWX itself is running inside of Docker. This is not a bug, but an aspect of how the system works. If you want to run `docker` inside of your AWX containers, you would need to make the necessary changes to allow for running docker-in-docker. This issue tracker is not the place for this discussion, but you can try asking for help in IRC or the mailing list. Links for both can be found here: https://www.ansible.com/products/awx-project

**Comment by lemmy04** [comment]
so basically you are telling me that AWX by design can not manage anything that is located inside a docker container, unless there is "some other way" to get into the containers, for example by ssh?

**Comment by shanemcd** [comment]
I didn't say it was by design, I said it was an aspect of how the system works. This is not specific to AWX. If you were running anything else inside of a container you would run into this same problem. I would not recommend trying to SSH into a container. Perhaps SSHing to the host where Docker is running would make more sense.

**Comment by lemmy04** [comment]
ok then lets not say "by design", but basically what you're saying is that because awx_task is a docker container, ansible_connection can't be docker, right?

anyway I'm doing the job as a simple shell: task on the host that runs the containers now.
