### ISSUE TITLE
New AWX CLI returns type error when modifying list or dict settings

### ISSUE THREAD

**Issue by xelgand** [ansible/awx#5528]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When trying to modify a list or dictionary valued setting from the **awx** command line tool, the API return a type error.

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: Kubernetes
* Ansible version:  2.7.11
* Operating System: Ubuntu 18.04
* Web Browser: Firefox 71

##### STEPS TO REPRODUCE

1. Install the AWX CLI tool:
```
pip install "https://github.com/ansible/awx/archive/9.0.1.tar.gz#egg=awxkit&subdirectory=awxkit"
```
2. Try to modify the AUTH_LDAP_GROUP_SEARCH (type list) setting
```
awx settings modify AUTH_LDAP_USER_SEARCH '["DC=example,DC=com","SCOPE_SUBTREE","(uid=%(user)s)"]'
```
3. Receive the following error
```
{"AUTH_LDAP_USER_SEARCH": ["Expected a list of items but got type \"str\"."]}
```

##### EXPECTED RESULTS

Expected to modify the setting like the old tower-cli or awx-cli tools were able to.

##### ACTUAL RESULTS

Received a type error
```
{"AUTH_LDAP_USER_SEARCH": ["Expected a list of items but got type \"str\"."]}
```

##### ADDITIONAL INFORMATION

You can achieve the same modification with the awx-cli:
```
awx-cli setting modify AUTH_LDAP_USER_SEARCH '["DC=example,DC=com","SCOPE_SUBTREE","(uid=%(user)s)"]'
Resource changed.
===================== ===========================================================
         id                                      value
===================== ===========================================================
AUTH_LDAP_USER_SEARCH [u'DC=example,DC=com', u'SCOPE_SUBTREE', u'(uid=%(user)s)']
===================== ===========================================================

```

**Comment by ryanpetrello** [comment]
Theres's an open PR that I suspect might fix this (#5544)

**Comment by dojones1** [comment]
Any progress on this? - I see the problem myself as I've written a role for deploying AWX but am now blocked on the LDAP configuration.

**Comment by ryanpetrello** [comment]
@dojones1 I've merged https://github.com/ansible/awx/pull/5544, which will address this in the next release of AWX.

**Comment by fpjrh** [comment]
@nixocio can you provide an update on progress?

**Comment by nixocio** [comment]
Tests added.

**Comment by nixocio** [comment]
@fpjrh, completed. Missed your comment.
