### ISSUE TITLE
FAILED - RETRYING: Wait for management pod to start (60 retries left)

### ISSUE THREAD

**Issue by laurent95380** [ansible/awx#5534]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Can't successfully run the ansible-playbook to install AWX. 
Management pod won't start and Deployment postgresql #4 failed after playbook run.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift
* Ansible version:  2.9.2
* Operating System: RHEL 7.6
* Web Browser:

##### STEPS TO REPRODUCE

 ansible-playbook -i inventory install.yml -vvv

##### EXPECTED RESULTS

Successful install of AWX

##### ACTUAL RESULTS

TASK [kubernetes : Wait for management pod to start] *******************************************************************************************************
task path: /appdata/awx/installer/roles/kubernetes/tasks/main.yml:262
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1576672183.88-168366970120803 `" && echo ansible-tmp-1576672183.88-168366970120803="` echo /root/.ansible/tmp/ansible-tmp-1576672183.88-168366970120803 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
<localhost> PUT /root/.ansible/tmp/ansible-local-6982Z4XhKr/tmpnxOArZ TO /root/.ansible/tmp/ansible-tmp-1576672183.88-168366970120803/AnsiballZ_command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1576672183.88-168366970120803/ /root/.ansible/tmp/ansible-tmp-1576672183.88-168366970120803/AnsiballZ_command.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/env python /root/.ansible/tmp/ansible-tmp-1576672183.88-168366970120803/AnsiballZ_command.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1576672183.88-168366970120803/ > /dev/null 2>&1 && sleep 0'
FAILED - RETRYING: Wait for management pod to start (60 retries left).Result was: {
    "attempts": 1,
    "changed": true,
    "cmd": "oc --config=/tmp/awx-config/.kube/config -n awx  get pod ansible-tower-management -o jsonpath=\"{.status.phase}\"\n",
    "delta": "0:00:00.151661",
    "end": "2019-12-18 13:29:44.171174",
    "invocation": {
        "module_args": {
            "_raw_params": "oc --config=/tmp/awx-config/.kube/config -n awx  get pod ansible-tower-management -o jsonpath=\"{.status.phase}\"\n",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "rc": 0,
    "retries": 61,
    "start": "2019-12-18 13:29:44.019513",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "Pending",
    "stdout_lines": [
        "Pending"
    ]
}

and on postgresql pod console

--> Scaling postgresql-1 down to zero
--> Scaling postgresql-4 to 1 before performing acceptance check
error: update acceptor rejected postgresql-4: pods for rc 'awx/postgresql-4' took longer than 600 seconds to become available

In Openshift/OKD events:

1:30:09 PM | ansible-tower-management | Pod | Normal | Killing | Killing container with id docker://ansible-tower-management:Need to kill Pod
-- | -- | -- | -- | -- | --
1:30:03 PM | awx | Stateful Set | Warning | Failed Create | create  Pod awx-0 in StatefulSet awx failed error: pods "awx-0" is forbidden:  unable to validate against any security context constraint:  [spec.containers[1].securityContext.privileged: Invalid value: true:  Privileged containers are not allowed]         14 times in the last 9 minutes

**Comment by ryanpetrello** [comment]
> [spec.containers[1].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]

The AWX task container must run as privileged due to our usage of bubblewrap (see: https://github.com/ansible/awx/issues/3115)

You probably need something like:

`oc adm policy add-scc-to-user privileged -n awx -z awx`

**Comment by laurent95380** [comment]
Just tried this solution and didn't work:

[root@srv1384 ~]# oc login
Authentication required for https://127.0.0.1:8443 (openshift)
Username: admin
Password:
Login successful.

You have one project on this server: "awx"

Using project "awx".
[root@srv1384 ~]# oc adm policy add-scc-to-user anyuid -z default
Error from server (Forbidden): securitycontextconstraints.security.openshift.io "anyuid" is forbidden: User "admin" cannot get securitycontextconstraints.security.openshift.io at the cluster scope: no RBAC policy matched


same with your command:

[root@srv1384 ~]# oc adm policy add-scc-to-user privileged -n awx -z awx
Error from server (Forbidden): securitycontextconstraints.security.openshift.io "privileged" is forbidden: User "admin" cannot get securitycontextconstraints.security.openshift.io at the cluster scope: no RBAC policy matched
