### ISSUE TITLE
Failed to access license information. GET returned status:

### ISSUE THREAD

**Issue by Ashjoker24** [ansible/awx#5545]
##### ISSUE TYPE
 - Support

##### SUMMARY
Hi I try to loin in AWX dashboard and the console show error like Failed to access license information. GET returned status: after that It logged out me from dashboard and I am getting loin page again. 
##### ENVIRONMENT
* AWX version: Tower CLI 3.3.0
* AWX install method: RPM
* Ansible version:  ansible 2.8.5
* Operating System: Centos
* Web Browser: Chrome
![image](https://user-images.githubusercontent.com/43417210/71145926-3ed00a80-2249-11ea-9624-0bd00f284b38.png)

**Comment by ryanpetrello** [comment]
@Ashjoker24,

This repo is for tracking issues with the open source AWX project.  If you've having trouble with an installation of Red Hat Ansible Tower, please reach out to Red Hat support.
