### ISSUE TITLE
Smart Host Filter Accepts Value then Crashes on Edit

### ISSUE THREAD

**Issue by hs-hub-world** [ansible/awx#5554]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When creating Smart Host Filter, in the Dynamic Hosts I am able to use this filter
inventory.name:"Server Inventory"
![image](https://user-images.githubusercontent.com/20629911/71223233-26331500-2288-11ea-87f5-b441c5684122.png)

![image](https://user-images.githubusercontent.com/20629911/71223305-5e3a5800-2288-11ea-80c6-73d61fad0acf.png)

![image](https://user-images.githubusercontent.com/20629911/71223344-832ecb00-2288-11ea-949a-f9d1a278ffb2.png)

awx version: 2.9.2
![image](https://user-images.githubusercontent.com/20629911/71223474-f59fab00-2288-11ea-8e6d-cdb4067a9f0d.png)

##### ENVIRONMENT
* AWX install method: openshift
* Ansible version:  2.9.1
* Operating System: Centos 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE
See images above

##### EXPECTED RESULTS
Be able to edit the Search Filter

Thank you,
HS

**Comment by unlikelyzero** [comment]
no longer an issue
