### ISSUE TITLE
Issue with tower_job_template not setting vault_credential

### ISSUE THREAD

**Issue by JonTheNiceGuy** [ansible/awx#5557]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
This is a continuation of https://github.com/ansible/ansible/issues/62429, which I am opening here to, hopefully, get a resolution on.

With the `tower_job_template` module, if you set `vault_credential`, it returns "OK", but the value of `vault_credential` is not set. Returning the registered result, shows under "`invocation` -> `module_args` -> `vault_credential`" is set to an empty string.

##### ENVIRONMENT
* AWX version: AWX 9.1.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.5
* Operating System: Ubuntu
* Web Browser: N/A

##### STEPS TO REPRODUCE
This is a complex chain - I'm very sorry, but I'm more than happy to go into as much detail as is required!

I configure my AWX following an install using [this combination of Terraform, Bash and Ansible](https://gitlab.com/JonTheNiceGuy/pink-epsilon-xray-ten). While there's a lot in there, [Terraform provisions an Ubuntu AWS host, using user_data](https://gitlab.com/JonTheNiceGuy/pink-epsilon-xray-ten/blob/master/Terraform/Mgmt1/EC2_AWX.tf#L41-82) which in turn builds credentials for a selection of pieces - and ends up running [this Ansible playbook to configure AWX](https://gist.github.com/JonTheNiceGuy/deac8432fea5d39184ced1f9f745679a#file-configure_awx-yml). When it gets to the part where [it defines the Job Template](https://gist.github.com/JonTheNiceGuy/deac8432fea5d39184ced1f9f745679a#file-configure_awx-yml-L282-L316), it specifies (via [this blob of JSON](https://gist.github.com/JonTheNiceGuy/deac8432fea5d39184ced1f9f745679a#file-run-json-L156-L163)) the credentials to use, including the vault.

If I use `debug: var=_result` on the tower_job_template instruction, I get:

```
TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "_result": {
        "changed": true,
        "msg": "All items completed",
        "results": [
            {
                "ansible_loop_var": "item",
                "attempts": 1,
                "changed": true,
                "failed": false,
                "id": 11,
                "invocation": {
                    "module_args": {
                        "ask_credential": false,
                        "ask_diff_mode": false,
                        "ask_extra_vars": false,
                        "ask_inventory": false,
                        "ask_job_type": false,
                        "ask_limit": false,
                        "ask_skip_tags": false,
                        "ask_tags": false,
                        "ask_verbosity": false,
                        "become_enabled": false,
                        "concurrent_jobs_enabled": false,
                        "credential": "Default Machine",
                        "description": "",
                        "diff_mode_enabled": false,
                        "extra_vars_path": null,
                        "fact_caching_enabled": false,
                        "force_handlers_enabled": false,
                        "forks": null,
                        "host_config_key": "",
                        "inventory": "NebulaEC2",
                        "job_tags": "",
                        "job_type": "run",
                        "limit": "",
                        "name": "Nebula EC2",
                        "playbook": "site.yml",
                        "project": "Ansible Managed Nebula",
                        "skip_tags": "",
                        "start_at_task": "",
                        "survey_enabled": false,
                        "survey_spec": null,
                        "timeout": 0,
                        "vault_credential": "",
                        "verbosity": 0
                    }
                },
                "item": {
                    "key": "Nebula EC2",
                    "value": {
                        "credential": "Default Machine",
                        "inventory": "NebulaEC2",
                        "playbook": "site.yml",
                        "project": "Ansible Managed Nebula",
                        "vault_credential": "Vault"
                    }
                },
                "job_template": "Nebula EC2",
                "state": "present"
            }
        ]
    }
}
```

As a temporary work-around, I've added [this stanza](https://gist.github.com/JonTheNiceGuy/deac8432fea5d39184ced1f9f745679a#file-configure_awx-yml-L318-L336) (represented not exactly faithfully below, due to "reasons"!) directly after the tower_job_template instruction:

```yaml
  - name: Add Vault Credentials to the Job Template
    raw: |
      awx-cli config host {{ awx_host }} && \
      awx-cli login admin --password "{{ admin_password }}" && \
      awx-cli job_template associate_credential --job-template "{{ item.key }}" --credential "{{ item.value.vault_credential }}"
    when: item.value.vault_credential is defined
    loop: "{{ job_templates | dict2items }}"
```

##### EXPECTED RESULTS
tower_job_template should handle the vault_credential value.

##### ACTUAL RESULTS
It does not.

**Comment by AlanCoding** [comment]
for an immediate fix, I think we would just expand on what was done in:

https://github.com/ansible/tower-cli/commit/761bad184b688b7192512c32a8275bfd391d0c05

**Comment by squidboylan** [comment]
We now have a regression test for this which passes on devel.
