### ISSUE TITLE
awx survey dictionary

### ISSUE THREAD

**Issue by JoaoMJoia** [ansible/awx#5561]
Hello there,

AWX v3.0.0

https://docs.ansible.com/ansible/latest/modules/infini_export_module.html#infini-export-module

ex:
infini_export:
    name: /data02
    filesystem: foo
    client_list:
      - client: 192.168.0.2
        access: RW
        no_root_squash: True
      - client: 192.168.0.100
        access: RO
        no_root_squash: False

I'm trying to implement a playbook for the infini_export on the AWX with a survey but I'm having trouble with the list of dictionary as variable for the client_list section.
How it is possible to create a list of dictionary on a survey ?

Regards,
Joao Joia

**Comment by wenottingham** [comment]
You'll likely have to take a textarea and then process it into the required data structure.
