### ISSUE TITLE
How to use machine credential ( pem key of ec2 instance) in playbook?

### ISSUE THREAD

**Issue by vinuaven** [ansible/awx#5569]
##### ISSUE TYPE
 - we are using ec2_win_password module for retrieving administrator password of windows instance. For this job template we are trying to use pem key which is saved as machine credential in playbook. 
How can we achieve this? 

##### SUMMARY

we are using ec2_win_password module for retrieving administrator password of windows instance. For this job template we are trying to use pem key which is saved as machine credential in playbook. 
How can we achieve this?

**Comment by wenottingham** [comment]
You cannot. Private keys for SSH (machine credentials) are only added to ssh-agent; they are not exposed directly to playbooks.
