### ISSUE TITLE
LDAP group lookup with custom uid field

### ISSUE THREAD

**Issue by jainnikhil30** [ansible/awx#557]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

When looking up if a user is part of a group in LDAP Tower is using the primary UID of the user and compares it with the members listed in the group. But its possible that in the group we don't have the UID of the user, and are using other custom field. We need to be able to specify in the Tower configuration which entry of the user to use in looking up group membership.

##### ENVIRONMENT
* AWX version: 1.0.x

##### ADDITIONAL INFORMATION

Currently since group search by default is using uid, the group search fails.

**Comment by cchurch** [comment]
The different ways of determining group membership are handled by the various group types supported in Django-Auth-LDAP: https://django-auth-ldap.readthedocs.io/en/1.2.x/groups.html#types-of-groups

Have you tried changing the value of `AUTH_LDAP_GROUP_TYPE` to find a built-in one that supports your particular LDAP server?

If you find you need a custom group type, you can define a subclass of `django_auth_ldap.config.LDAPGroupType` in `/etc/awx/conf.d/ldap.py` (create it if it doesn't exist) and then specify something like `AUTH_LDAP_GROUP_TYPE = YourGroupType()` in that same file to support a custom group type.

**Comment by jainnikhil30** [comment]
@cchurch

The group type is posixgroup, the problem is with the uid field which ldap is using for the group search.  Here is an example:
~~~
uid:		"testuser.example"
customuid:	"testuser"
group is:	"testlinux"
"testuser" exists as memberUid in "testlinux" but tower is looking for "testuser.example" in memberUID.


USER LOOKUP:

[test@localhost ~]$ ldapsearch -x -H ldap://ldaptest:389 -b o=test.com customuid=testuser
# extended LDIF
#
# LDAPv3
# base <o=test.com> with scope subtree
# filter: customuid=testuser
# requesting: ALL
#

# testuser.example, People, test.com
dn: uid=testuser.example,ou=People,o=test.com
uid: testuser.example
...more stuff...
customuid: testuser
...more stuff...
~~~
Now while doing a group search tower is using the uid field which is "testuser.example" but we dont want that, we need it to use the cutomuid field which is set to "testuser"

Here are the debug logs from Tower side
~~~
2017-08-23 07:23:18,961 DEBUG    django_auth_ldap search_s('o=test.com', 2, '(customid=%(user)s)') returned 1 objects: uid=testuser.example,ou=people,o=test.com
2017-08-23 07:23:18,965 DEBUG    django_auth_ldap Populating Django user testuser
~~~
So here it uses that customid for doing the user search and finds the user "testuser" with uid "testuser.example"
And then it uses that uid "testuser.example" as the memberUid for searching the group membership, which fails. Because on the ldap side memberUid is set as "testuser", which is our customuid.
~~~
2017-08-23 07:23:18,967 DEBUG    django_auth_ldap search_s('cn=UserGroups,ou=Global,o=test.com', 2, '(&(objectClass=posixGroup)(|(gidNumber=xxxxx)(memberUid=testuser.example)))') 

~~~
So we need a way to specify in the Tower configuration which field of the user to use in looking up group membership.

**Comment by chrismeyersfsu** [comment]
@jainnikhil30 can you point to any standard LDAP schema that is being used?

https://access.redhat.com/documentation/en-US/Red_Hat_Directory_Server/8.1/html-single/Schema_Reference/index.html

The description seems like a modified Posix schema is being used. Also, this could just be a typo, you mention that on the ldap side `memberID is set as "testuser"`. `memberID` is different then the attribute that is being searched on, `memberUid`.

**Comment by jainnikhil30** [comment]
@chrismeyersfsu 

Ahh right that was typo for memberID and memberUid, my bad on that. Edited it.
