### ISSUE TITLE
Infinibox authentication failed. Check your credentials

### ISSUE THREAD

**Issue by JoaoMJoia** [ansible/awx#5572]
ENVIRONMENT
 AWX version: 3.0.0
 Ansible version:  2.9.2

Error message:
"msg": "Infinibox authentication failed. Check your credentials"

Hello there,
I'm trying to implement a playbook on the AWX (container awx_task, awx_web ) to create and export an NFS.
On the AWX I passed the infinibox credentials on the survey has variables without success, then I  passed the credentials as environment variables on the playbook and didn't work too. After that I tried to run the playbook directly on the container of awx_task with the same examples and I have always the same error: "msg": "Infinibox authentication failed. Check your credentials".

Can someone help me out with this ?

Regards,
Joao Joia

**Comment by ryanpetrello** [comment]
Hey @JoaoMJoia,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
