### ISSUE TITLE
postgres_data_dir should not be mandatory in docker install

### ISSUE THREAD

**Issue by nfj25** [ansible/awx#5575]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
postgres_data_dir is mandatory for docker install even if using external database, throwing an error if not defined.

##### ENVIRONMENT
* AWX version: 9.1.0
* AWX install method: docker on linux
* Ansible version:  1.8.4
* Operating System: CentOS7
* Web Browser:

##### STEPS TO REPRODUCE

Comment postgres_data_dir variable in inventory (because you are using an external database and this variable should not be necessary).

##### EXPECTED RESULTS

It should ignore any steps regarding local postgres instalation/upgrade if this variable is not set.

##### ACTUAL RESULTS

An error will occour in the main.yml of the local_docker role because the variable postgres_data_dir is undefined.

##### ADDITIONAL INFORMATION

Maybe the variable should be defined with the default in the "defaults" of the local_docker role, as it is a good practice for ansible roles anyway.

**Comment by gamuniz** [comment]
This issue references the old installation method. Closing
