### ISSUE TITLE
Metrics endpoint squashes json data if multiple entries for data (e.g. awx_instance_info etc)

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#5583]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

If the data metric has multiple entries like:
```
awx_instance_capacity{hostname="some-domain-tower1.com.example.com",instance_uuid="b5c9e65f-f75a-421f-8c14-23405d25fc41"} 54.0
awx_instance_capacity{hostname="some-domain-isolated1.com.example.com",instance_uuid="48d53859-9d1c-431c-9c44-7d08322188e9"} 55.0
awx_instance_capacity{hostname="some-domain-tower2.com.example.com",instance_uuid="066e3aa8-9e9b-4833-bfe6-ecaff4fd7d83"} 54.0
awx_instance_capacity{hostname="some-domain-tower3.com.example.com",instance_uuid="16eacc57-f876-498a-885f-1c1fe193f2df"} 54.0
awx_instance_capacity{hostname="some-domain-tower4.com.example.com",instance_uuid="6bf06e69-9cc2-49e9-bde0-a00648024f48"} 54.0
```

e.g. we are reporting the `awx_instance_capacity` for mutliple instances, then when we do a GET with `ContentType` as `application/json` we only get the last value:
```
    "awx_instance_capacity": {
        "labels": {
            "hostname": "some-domain-tower4.com.example.com",
            "instance_uuid": "6bf06e69-9cc2-49e9-bde0-a00648024f48"
        },
        "value": 54.0
    },
```

##### ENVIRONMENT
* AWX version: tower built from devel
* Ansible version:  X.Y.Z not relevant
* Operating System: rhel 7 (probably not relevant)

##### STEPS TO REPRODUCE

Create a tower cluster w/ at least 2 nodes

##### EXPECTED RESULTS
Expect that we get lists in json of `awx_instance_capacity`, `awx_instance_cpu`, `awx_instance_memory`, `awx_instance_info`, `awx_instance_consumed_capacity`, and `awx_remaining_capacity`

##### ACTUAL RESULTS

Only get one value for each key

##### ADDITIONAL INFORMATION

Will need to do some kind of custom rendering when request asked for `application/json`
Created this bug as a defect for this feature: https://github.com/ansible/awx/issues/5292#issuecomment-568538976

**Comment by ryanpetrello** [comment]
@kdelee I put this in `needs_test`; is that accurate?

**Comment by kdelee** [comment]
Verified by tests that now expect multiple entries
