### ISSUE TITLE
Cannot add admin to Organization with French locale

### ISSUE THREAD

**Issue by naurel06** [ansible/awx#5586]
When trying to add an admin to an Organization with a browser having french language I get this error :
`Invalid search term entered. GET returned: 400 Id roles non valide : undefined.`

No problems when changing my browser to english.
No problems with other roles.

I've just updated my awx to ensure that this issue is still live.

**Comment by ryanpetrello** [comment]
@naurel06 can you please update this ticket with all of the requested information in the bug report template?

https://github.com/ansible/awx/issues/new?template=bug_report.md

Thank you.

**Comment by naurel06** [comment]
Update :

AWX : 9.0.1.0
AWX install method : docker on Linux
Ansible 2.8.5
OS : CentOS 8
Web Browser : Firefox 72.0.1

To reproduce : try to add an admin profile from the "Organization" menu with the browser language set on French.

Expected result : opening a window to add a new admin.
Actual result : Error pop-up 

> "Invalid search term entered. GET returned: 400 Id roles non valide : undefined."

**Comment by jakemcdermott** [comment]
![fr_org_admin_create](https://user-images.githubusercontent.com/9753817/72166233-de8b3f00-3396-11ea-8695-57989d9abd3b.gif)

**Comment by kdelee** [comment]
:/ I am using a fresh 3.6.3 AMI that I built and deployed today. I changed my browser local to french. Performing reproducer in gif creates same problem for me.

![400_french_admin](https://user-images.githubusercontent.com/29239279/74273758-f3812800-4cde-11ea-9bfd-2e319e8c206e.gif)

**Comment by jakemcdermott** [comment]
@kdelee This was for devel. Would you like me to create a backport issue for this?

**Comment by jakemcdermott** [comment]
We added a new issue in a different repo for upcoming release verification.  We will use this issue for devel verification when it is time.

**Comment by elyezer** [comment]
Did the following to verify this:

1) Set Firefox to only suggest French as the language
2) Ensured AWX had two admin users and two organizations
3) Added both users to the Default organization
4) Added both users to the second organization

No issues where found when doing the above steps:

![issue-5586](https://user-images.githubusercontent.com/48132/74344783-182add80-4d7b-11ea-84e2-3b716b566a5a.gif)
