### ISSUE TITLE
View/open playbook contents

### ISSUE THREAD

**Issue by foley-j** [ansible/awx#5588]
##### ISSUE TYPE

  - Feature Idea
 
##### COMPONENT NAME

  - UI
 
##### SUMMARY

It would be pretty useful if there was a link/button on the template UI that would actually display the contents of said playbook. I find myself looking at a template that I want/need to run and trying to remember what was exactly in the guts of the playbook, and then having to log into git/enter MFA/find the playbook or role, etc.

##### ENVIRONMENT
* AWX version: 3.6.0
* AWX install method: n/a
* Ansible version:  2.9.2
* Operating System: n/a
* Web Browser: Chrome

##### ADDITIONAL INFORMATION

A dialog that pops up that displays the local contents of the SCM component in question should quasi easy to implement. If displaying the contents of a playbook is a security risk, than a button that opens said playbook in git would also be great. Obviously, that would be more of a challenge since many different SCMs exist, and not all of them are as user friendlt as git.

**Comment by ryanpetrello** [comment]
Duplicate of https://github.com/ansible/awx/issues/2905
