### ISSUE TITLE
AWX can't create projects 

### ISSUE THREAD

**Issue by siriusckx** [ansible/awx#5591]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
when I create projects with "SCM TYPE" Manual, the "save" button is gray, and can't find "playbook directory" item on the web page.

WARNING: There are no available playbook directories in /var/lib/awx/projects. Either that directory is empty, or all of the contents are already assigned to other projects. Create a new directory there and make sure the playbook files can be read by the "awx" system user, or have AWX directly retrieve your playbooks from source control using the SCM Type option above.

```
[awx@localhost AutoDeploy_project]$ pwd
/var/lib/awx/projects/AutoDeploy_project
[awx@localhost AutoDeploy_project]$ cat AutoDeploy_project.yml 

---
- name: Hello World!
  hosts: all

  tasks:

  - name: Hello World!
    shell: echo "Hi! Tower is working!"

[awx@localhost AutoDeploy_project]$ll
-rw-rw-r--. 1 awx awx 112 1月   4 09:34 AutoDeploy_project.yml
```

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.1
* Operating System: CentOS 7.2
* Web Browser: FireFox

**Comment by ryanpetrello** [comment]
Hey @siriusckx,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
