### ISSUE TITLE
Job execution report in AWX

### ISSUE THREAD

**Issue by unbreakabl3** [ansible/awx#5594]
##### ISSUE TYPE
 - Documentation

##### SUMMARY

When i run ansible-playbook test.yaml, i'm not able to see the job result in AWX

##### ENVIRONMENT
* AWX version: 9.1
* AWX install method: docker on linux
* Ansible version:  2.9.2
* Operating System: Ubuntu 18.04

##### ADDITIONAL INFORMATION

Maybe I'm missing something, but how to see the local ansible execution jobs in AWX?
I'm new in Ansible/AWX. Read a few topic regarding the virtenv now, but still not sure, how i can map /var/lib/awx/venv/ansible from container to localhost...

I have VMware vRA 8, which is use Ansible as a configuration manager. vRA connect to host ansible host (not to AWX) and execute playbooks on it. The monitoring people want to see the executions status in AWX...

Thank you!

**Comment by ryanpetrello** [comment]
Hey @unbreakabl3,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
