### ISSUE TITLE
Special variable ansible_inventory_sources not working in awx

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/awx#5596]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY

Using ansible_inventory_sources variables results in a temporary/dynamic inventory name using awx.

The inventory is sourced from git repository and it is not dynamic.

##### ENVIRONMENT
* AWX version: 6.1.0
* AWX install method: docker on linux
* Ansible version:  2.9.2

##### EXPECTED RESULTS

ansible_inventory_sources should show real inventory name

##### ACTUAL RESULTS

ansible_inventory_sources example shows: "/tmp/awx_56459_fhk7j_ol/tmpqg5ea3af"

**Comment by wenottingham** [comment]
This is an artifact of how inventory is passed in AWX.

All inventory comes from the AWX database - even inventory from SCM is first saved to the database, and then exported to the playbook via a source that reads from the database. So it will be a temporary/dynamic file/pipe each time during a playbook run.
