### ISSUE TITLE
Getting "dh key to small" when syncing projects from bitbucket 6.8.0

### ISSUE THREAD

**Issue by mattch3wie** [ansible/awx#5601]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
DH KEY length issue when syncing projects

##### ENVIRONMENT
* AWX version: 9.1.0
* AWX install method: docker on linux
* Ansible version:  2.8.5
* Operating System: RHEL 7 (Also tested on CENTOS 8)
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Configure project to point to a repo on our on-site  bitbucket instance (v6.8.0) (with either password or keys, doesn't matter)

Try to sync

##### EXPECTED RESULTS

Project successfully connects and downloads code base

##### ACTUAL RESULTS

Project errors with the following message

_Cloning into '/var/lib/awx/projects/_6__sync_try'...
fatal: unable to access 'https://$encrypted$:$encrypted$@bitbucket.creditacceptance.com/scm/~mgalloway/misc.git/': error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small_

##### ADDITIONAL INFORMATION

Issue first presented itself on RHEL 7
It was then tested on CENTOS 8 to ensure it wasn't something with the base server
Both instances were installed via docker-compose per instructions
Issue is not present on an old test server that is running AWX 8.0.0.0 and ansible 2.8.6

**Comment by wenottingham** [comment]
OpenSSL is rejecting the key as too small, this comes from the underlying OS openssl version and there is little that AWX can do. You'll probably need a newer certificate for your bitbucket instance.

**Comment by wenottingham** [comment]
For more info on why OpenSSL is rejecting it: https://weakdh.org/

**Comment by mattch3wie** [comment]
@wenottingham - Thank you for the feedback! My crypto knowledge could be better :_. Question though - The underlying OS you speak of; would that be the OS in the "task" container?

I notice that 9.1.0 is on CENT8 and 8.0.0 CENT7

And since v8.0.0 can sync with no issue and v9.1.0 can't, I feel this all lives in the container.

(unless v9.1.0 has an issue with key BitBucket is using?)

But on the other hand, I have synced this repo on CENT8 with a git outside of the container with no issue so I would think the container CENT would have no issue.

**Comment by wenottingham** [comment]
Yes, it would be expected with the change to CentOS 8 as a base OS - it includes a newer OpenSSL release that does this check. I'm actually surprised that it would work with git outside of the container on CentOS 8.

**Comment by linuxman1** [comment]
Hi, I had this issue on centos 8 and found a workaround and it worked although it may cause security issues, this fix is,
sudo update-crypto-policies --set LEGACY
