### ISSUE TITLE
Remove Scan option from Job Type field of JT Creation form

### ISSUE THREAD

**Issue by tvo318** [ansible/awx#5603]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
![image](https://user-images.githubusercontent.com/7514801/71848879-e6dd3480-308d-11ea-9e3f-19445d404986.png)

##### ENVIRONMENT

- Tower version: 3.6.2
- AWX install method: yolo #8062: Instance URL - https://ec2-54-85-222-225.compute-1.amazonaws.com
- Ansible version: 2.10.0.dev0
- Operating System: Mac Mojave 10.14.6
- Web Browser: Version 79.0.3945.88 (Official Build) (64-bit)

##### STEPS TO REPRODUCE
1. Click **Templates**
2. Select **[+]** > **Job Template**
3. In **Job Type** field, select **Scan**

##### EXPECTED RESULTS
Only see two options from the **Job Type** field: **Run** and **Check** only.

##### ACTUAL RESULTS
See **Job Type** field contains: **Run**, **Check**, and **Scan**.

##### ADDITIONAL INFORMATION
Scan jobs are no longer supported starting with Ansible Tower 3.2.

**Comment by wenottingham** [comment]
What does it do if you choose this and then launch the saved job?

**Comment by tvo318** [comment]
@wenottingham I just ran a simple scan job template using the default inventory and project and "Hello World" playbook and it ran successfully. See the job details here: 
![image](https://user-images.githubusercontent.com/7514801/72180265-06cd6a80-33a4-11ea-9b50-3e2d1f91b9c2.png)

**Comment by kdelee** [comment]
still seeing some references to scan jobs, putting up a PR with my suggested removals

**Comment by kdelee** [comment]
after this and related test update PR go in will close this

**Comment by kdelee** [comment]
closing
