### ISSUE TITLE
Google OAuth2 Not Working

### ISSUE THREAD

**Issue by vexter0944** [ansible/awx#5612]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Cannot log in via Google Oauth

##### ENVIRONMENT
* AWX version: 9.1.0.0.
* AWX install method: docker on linux
* Ansible version:  2.8.5
* Operating System: Ubuntu 18.04/Docker
* Web Browser: Chrome or Edge

##### STEPS TO REPRODUCE

A couple of quick notes about my setup for this:

1.  domain.com is a company .com on the internet where I want to use g-suite user accounts from to login to AWX with - it's the g-suite for our company.

2.  personaldomain.com is my personal domain on the internet that I can use for homelab testing/selfhosting etc - has nothing to do with company at all.

On domain.com in G-Suite - I have the oauth setup and have a client ID created in the Gsuite and have the redirect uri set to https://awx.personaldomain.com/sso/complete/google-oauth2/

On personaldomain.com - have a dns entry setup for awx.personaldomain.com and it seems to be working fine coming through traefik and then I get a login for AWX as expected.  When I setup the Ouath2 for Google - I get the G to click for login - I can click it and it will redirect - and I get to choose a google account to use for login - I pick my username@domain.com gsuite account and the screen refreshes - then it stops.  I get the error in red like the screenshot.

Google OAuth Settings In AWX are as in screenshot.

--

##### EXPECTED RESULTS

allow me to login via g-suite account

##### ACTUAL RESULTS

error stating 'Authentication process canceled.' and will not login

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/23345472/72007067-82011600-3216-11ea-85b0-68debe50bc61.png)
![image](https://user-images.githubusercontent.com/23345472/72007815-25065f80-3218-11ea-8c4d-a7806ebdf891.png)

**Comment by ryanpetrello** [comment]
Hey @vexter0944,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by rebelArtists** [comment]
i'm seeing the same on my end for github oauth, do not believe this should be closed
