### ISSUE TITLE
redis support for fact_caching in ansible

### ISSUE THREAD

**Issue by clammers** [ansible/awx#5615]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Would be great to have redis libraries in standard docker container to make use of fact_caching in redis. 

in requirements/requirements_ansible.in
```
# Redis
redis==2.10.6
```

**Comment by wenottingham** [comment]
AWX has a built-in fact cache already.

**Comment by clammers** [comment]
we need persistent fact_caching and run multiple awx_task container on multiple machines, so facts need be synced. Memcached is only for local instances, or?  How do you get this solved?

**Comment by wenottingham** [comment]
Multiple separate instances sharing a fact cache? That's not something we'd build, as that assumes a global fact namespace which may not be what is desired.
