### ISSUE TITLE
AWX is bloated and complicated to install

### ISSUE THREAD

**Issue by dsamx** [ansible/awx#5625]
I have the following scenario: Create a graphical installer for Linux servers that are managed via ansible.
In the past we had a Windows program (10MB or so) that copied selected Linux packages to a server, executed scripts and installed the packages.
We replaced the install and config tasks with ansible playbooks but what is left is a non-console based method to get the packages to the server and execute the playbooks.
I had the following issues with AWX:
- it only runs in a docker container but on Windows this is incompatible with VirtualBox and other VM programs, so our developers cannot use both properly and maybe it needs to run on an older Windows system too
- the setup of AWX was impossible behind a proxy (I spent two days to test where to configure proxy settings until we used a network connection without proxy)
- the image was way too fat - we had a 8GB VM running the AWX container, no packages included; this is not mobile anymore (or uploadable over a shitty intercontinental connection); a couple hundred MB would be acceptable (assume you want to install a 5MB package with a 8GB installer...)
- the setup is too complicated due to software dependencies; debian had ansible 2.7 but AWX requires 2.8, so following a quite fresh howto from end of 2019 did not work anymore (and trying to get ansible 2.8 with dependencies from Ubuntu was a pain), CentOS7 had a similar problem. I tested the installation with CentOS7, 8 (which had to install el7 packages), debian 10, Ubuntu 19.10 and only Ubuntu had a rather simple setup because ansible and all the python3 stuff was fresh enough.
- choosing the distribution that hosts AWX is also critical: we compile our playbooks into rpm packages and use path variable substitution etc, so we cannot simply checkout the playbook from git - but if AWX runs on Ubuntu we cannot install the rpm anymore and need to support another distribution. It would be nice if AWX could execute the playbook that is installed on the target machine and not have the playbook locally.

So maybe AWX works for big cloud setups or LANs with a certain inventory but it is complete overkill for small setups (like one server), the way it is deployed at the moment and the setup requires features that are too modern for several current distributions.

Having a bunch of small packages makes AWX more versatile for smaller systems and different distributions. Not using docker makes it more interesting for Windows too (btw: the docker installer only requires 1GB and then you need 1-2 more containers with AWX which are also 1GB each).
I bet the AWX core is pretty small.

**Comment by wenottingham** [comment]
AWX is the upstream for Ansible Tower. It is designed to be part of a scalable automation platform that is run at the enterprise level - building an infrastructure for delegating jobs out to multiple teams and users, and executing them in a cluster locally, or even in remote OCP/K8S instances.

As a platform for managing 1-2 servers it may be overkill, yes.
