### ISSUE TITLE
Confusing patternfly asset usage for alphabetical sort

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#5631]
t##### ISSUE TYPE
 - Bug Report

##### SUMMARY

The alphabetical patternfly sort icons are confusing (the arrow seems to imply that it is reverse, going from Z to A, but that's the opposite of what's happening):
![Screenshot from 2020-01-10 12-13-38](https://user-images.githubusercontent.com/19942822/72176905-7d229a80-33ad-11ea-99d4-b77dacbc3de7.png)

It would be good to replace them with these ([from this page](https://patternfly-react.surge.sh/patternfly-4/icons/))

Alphabetical:
![Screenshot from 2020-01-10 13-37-28](https://user-images.githubusercontent.com/19942822/72177292-60d32d80-33ae-11ea-8d08-c2e3aa750498.png)

Reverse:
![Screenshot from 2020-01-10 13-37-32](https://user-images.githubusercontent.com/19942822/72177309-6892d200-33ae-11ea-8827-a3efdc7a68c2.png)

- [x] Resolve the alphabetical sort icons.
- [x] In addition, there is a numerical sort. As part of this issue, it would be nice to double check those as well.

##### ENVIRONMENT
* AWX version: latest

##### STEPS TO REPRODUCE
1. Visit a page like the credentials list.
2. Make a few creds.
3. Try to sort them and match the meaning of the icon to what's actually happening.

**Comment by marshmalien** [comment]
<img width="400" alt="Screen Shot 2020-01-10 at 1 44 07 PM" src="https://user-images.githubusercontent.com/15881645/72178023-f4f1c480-33af-11ea-8411-8fd156eace34.png">

Alphabetical order: Sort Alpha Down Icon
Reverse alphabetical order: Sort Alpha Up Alt Icon

**Comment by dsesami** [comment]
Looks great!
