### ISSUE TITLE
Unable to save timeout settings - gives 400 error

### ISSUE THREAD

**Issue by tvo318** [ansible/awx#5634]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Tried changing and saving Idle Timeout settings but returns error message 400.

##### ENVIRONMENT

- Tower version: 3.6.2 AND 3.7.0
- AWX install method: **For 362**: yolo #8062: Instance URL - https://ec2-54-85-222-225.compute-1.amazonaws.com / **For 370**: yolo #8073: Instance URL -https://ec2-3-82-96-111.compute-1.amazonaws.com
- Ansible version: 2.10.0.dev0
- Operating System: Mac Mojave 10.14.6
- Web Browser: Version 79.0.3945.117 (Official Build) (64-bit)

##### STEPS TO REPRODUCE

1. Go to **Settings > System**
2. In the **Misc. System** tab, go to: **IDLE TIME FORCE LOG OUT**
3. Change value to something else.
4. Click **Save**.

##### EXPECTED RESULTS

Should save the newly entered value.

##### ACTUAL RESULTS

Gives error message as shown here:
![image](https://user-images.githubusercontent.com/7514801/72182906-bfe27380-33a9-11ea-88c9-f14311f320f1.png)

And resets back to original factory setting.

**Comment by kdelee** [comment]
How old is the 3.7.0 instance? That should be fixed in devel.

This is a bug that I've filed for 3.6.2, fix incoming https://github.com/ansible/tower/issues/4060

To work around: put in anything for `LOGIN REDIRECT URL` including a space

**Comment by kdelee** [comment]
In your screenshot it is just behind the modal saying "this field may not be null" in red letters

**Comment by wenottingham** [comment]
Closing as fixed.
