### ISSUE TITLE
[ui_next] Label 'Log In' at the Login screen, needs to be marked for translation

### ISSUE THREAD

**Issue by sshedmake** [ansible/awx#5636]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
With Japanese (dummy translation) google-chrome, label 'Log In' at the ui_next Login screen, appears in English (instead of Japanese)

##### ENVIRONMENT
* AWX version: 9.1.0
* AWX install method: docker on linux
* Ansible version:  2.10.0.dev0
* Operating System: Fedora 31
* Web Browser: google-chrome

##### STEPS TO REPRODUCE
Visit Login screen of ui_next in the preferred language (say Japanese)

##### EXPECTED RESULTS
Label 'Log In' should appear in Japanese

##### ACTUAL RESULTS
Label 'Log In' button appears in English

##### ADDITIONAL INFORMATION
Screenshot showing ui_next Login screen with Japanese (dummy translation) google-chrome, highlighting label 'Log In' appearing in English:

![Screenshot from 2020-01-11 17-47-05_LogIn](https://user-images.githubusercontent.com/12151785/72204375-23999900-349d-11ea-8cb0-5827a9b9dbca.png)

**Comment by mabashian** [comment]
This text comes from the upstream LoginPage PF component.  To fix this, we should pass the same string (wrapped for i18n) through the `loginButtonLabel` prop on `LoginForm`.

**Comment by marshmalien** [comment]
cc @rooftopcellist

**Comment by sshedmake** [comment]
Screenshot verifying label 'Log In' now, marked as translatable string and browser loading its dummy Japanese translation

![Screenshot from 2020-04-12 19-12-43_1](https://user-images.githubusercontent.com/12151785/79103417-218bf280-7d8a-11ea-8b58-9a65d5ea7e18.png)

**Comment by unlikelyzero** [comment]
Removing needs_test until translations land!

**Comment by mabashian** [comment]
If this has been marked do we need to leave it open @unlikelyzero?  This'll stay open for _probably_ months.

**Comment by unlikelyzero** [comment]
It's been marked, so I'll move this ticket to closed and we can create a more comprehensive plan here https://github.com/ansible/tower/issues/4585
