### ISSUE TITLE
Provide enough information for the ui to calculate elapsed time for running jobs

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#5646]
##### ISSUE TYPE
 - Feature Idea

The `started` field for ~running jobs~ **edit:** newly launched jobs  is `null`. This field is needed in order to compute and show an accurate playbook run time while the job is running.

**Comment by ryanpetrello** [comment]
> The started field for running jobs is null.

Huh?

![Kapture 2020-01-14 at 15 24 58](https://user-images.githubusercontent.com/214912/72379774-13bec680-36e2-11ea-940f-0594264f0fbc.gif)

**Comment by jakemcdermott** [comment]
@ryanpetrello
My initial description was incorrect :joy:   `job.status == running"` jobs  _do_ have `started` values. 

It's that _newly launched jobs_  don't have this info when the job details are fetched, and the UI needs some sort of starting time as a basis for calculating the run time.

 I believe it only gets set after the job transitions to running, which usually happens after the job details have been fetched. Unless we want to block the page load until the job status reaches `running` or trigger an http request based off of a websocket event, I think we'd need the `started` time to come in over websockets in some form. Perhaps it can be included in the `status` events?

**Comment by jakemcdermott** [comment]
I worded this issue very poorly :joy:  "running" jobs (as in job.status == "Running") _do_ have `started` fields. 

It's that _newly launched jobs_  don't have this info when the job details are fetched, and the UI needs some sort of starting time as a basis for calculating the run time.

**Comment by wenottingham** [comment]
> I think we'd need the started time to come in over websockets in some form. Perhaps it can be included in the status events?

suggestion: do ^

**Comment by shanemcd** [comment]
We are currently tracking this as a parent issue of https://github.com/ansible/awx/issues/11555. If we decide not to do this, we need to pull that one into our project.

**Comment by AlanCoding** [comment]
I showed how the API can add this in https://github.com/ansible/awx/pull/12270, and the UI can make use of that when it needs it. However, I don't want to merge that with the UI work still unplanned. So I'm closing both that PR and this issue. The related UI issue https://github.com/ansible/awx/issues/11555 is unblocked.
