### ISSUE TITLE
Missing tag 9.1.1?

### ISSUE THREAD

**Issue by MrMEEE** [ansible/awx#5647]
Hi guys

The version in the version file has been bumped to 9.1.1, but latest tag is still 9.1.0.. ?

**Comment by ryanpetrello** [comment]
Hey @MrMEEE,

We're working on cutting a release today (as we speak):

https://github.com/ansible/awx/pull/5655/

**Comment by shanemcd** [comment]
For future reference, the VERSION file is always going to get updated pre-release...

**Comment by MrMEEE** [comment]
Thanks for the info..

**Comment by ryanpetrello** [comment]
https://groups.google.com/forum/#!topic/awx-project/LPoj0LtsZfE
