### ISSUE TITLE
Site stuck in reload state

### ISSUE THREAD

**Issue by hs-hub-world** [ansible/awx#5670]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Not sure if this is happening to anybody else but once in a while (now more frequently) anytime I try to go back to the awx site (https://servername) the page is stuck in the reloading state, I managed to capture some of the errors from the browser console
![image](https://user-images.githubusercontent.com/20629911/72463517-46bb9580-3788-11ea-8f9d-fd385125c89b.png)

When this occurs the only way I am able to get back in by going to one of the api urls 
example: http://<server>/api/v2/job_templates/11/launch
Then login from the API site.
then click on the arrow to go back to ansible site.
![image](https://user-images.githubusercontent.com/20629911/72463799-eda03180-3788-11ea-97c7-afacb24498af.png)

I have confirmed the problem occurs on different browsers during this time (IE, Chome, Firefox)

##### ENVIRONMENT
* AWX version: 9.1.0.0
![image](https://user-images.githubusercontent.com/20629911/72464032-6b643d00-3789-11ea-8e7f-87d75110cd64.png)

* AWX install method: docker on linux
* Ansible version:  X.Y.Z
* Operating System: Centos 7
* Web Browser: Chrome  

##### STEPS TO REPRODUCE
Not sure yet, it's random, I'll keep monitoring. 

##### EXPECTED RESULTS
it's random, but the page is stuck in reloading state you can see the browser keeps reloading the URL.

**Comment by nixocio** [comment]
Reopen if we see this behavior on the new UI.
