### ISSUE TITLE
New Relic Record Deployment

### ISSUE THREAD

**Issue by gjt11** [ansible/awx#5675]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY
New feature for existing Ansibile Module called newrelic_deployment
https://docs.ansible.com/ansible/latest/modules/newrelic_deployment_module.html

##### ENVIRONMENT
* AWX version: 3.5.3
* AWX install method:  linux
* Ansible version:  2.8.6
* Operating System: Red Hat Linux
* Web Browser:

##### STEPS TO REPRODUCE

Run the Module

##### EXPECTED RESULTS

I expect the timestamp to be sent to the New Relic API to record the deployment at the time sent in the timestamp variable.

##### ACTUAL RESULTS

I have been using the module newrelic-deployment.
https://docs.ansible.com/ansible/latest/modules/newrelic_deployment_module.html

New Relic API now has the ability to accept a timestamp, see below.
https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/record-monitor-deployments

When I set the the timestamp variable in my yaml as below, it is then passed to the New Relic API but does not record the time submitted in the timestamp variable. It records it  at the date and time the API received it from Ansible Tower, which is incorrect.

Is it possible to add the timestamp variable to the Ansible Module newrelic_deployment?

The timestamp variable is a string, and is manually added when running the playbook.
The timestamp variable is not taken from the operating system.

##### ADDITIONAL INFORMATION

The purpose of the timestamp variable is to be able to add a retrospective record in New Relic.
for example, if I run the playbook t at 14th January 2020,10:00 UTC, it will record this in New Relic with the time the New Relic API received the requested.
Let's say the current date/times is 14th January 2020,10:00 UTC and we want to need to record a deployment in New Relic, but the deployment was done 8 hours ago at 02:00 UTC
We would then use the timestmap variable with 14th January 2020, 02:00 (this is of course not in the required format)

In the attached screen shot, the 'Time' column is the timestmap variable.
![image](https://user-images.githubusercontent.com/57396978/72515606-19362100-3848-11ea-9ded-d7b32d75b0fe.png)

**Comment by wenottingham** [comment]
This needs to be filed in https://github.com/ansible/ansible - this has nothing to do with AWX.
