### ISSUE TITLE
[RFE] Ability to limit the amount of manually launched jobs/forks

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#5676]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Customer would like the ability to limit the amount of manually launched jobs or forks, similar to the limit of scheduled jobs.

**Comment by wenottingham** [comment]
For resource limiting, or something else? Capacity adjustments + instance groups would likely solve this better.

**Comment by wenottingham** [comment]
@msilmser do you have an update from the customer here?

**Comment by wenottingham** [comment]
Closing, we are unlikely to do this in this way. There is a per-job fork limit now.
