### ISSUE TITLE
Move Created By and Modified By fields

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#5683]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Move **Created By** and **Last Modified** to the very bottom of the Detail List, but before the "full card width" detail items like labels, instance groups, and variables. 

_Actual Result_
<img width="1272" alt="Screen Shot 2020-07-27 at 10 51 00 AM" src="https://user-images.githubusercontent.com/15881645/88558155-2e5eea00-cff9-11ea-962a-5eaa7b27c0a0.png">

_Expected Result_
<img width="1345" alt="Screen Shot 2020-07-27 at 11 02 24 AM" src="https://user-images.githubusercontent.com/15881645/88557952-e8098b00-cff8-11ea-96ba-1c2f20762dba.png">

##### ADDITIONAL INFORMATION
This applies to all Detail views, so whoever picks this up will have to audit ui_next for all occurrences.

**Comment by unlikelyzero** [comment]
@marshmalien still an issue?

**Comment by marshmalien** [comment]
@unlikelyzero Yes, just verified with @trahman73 and it is still an issue.

**Comment by unlikelyzero** [comment]
covered in https://github.com/ansible/tower-qa/pull/5829
