### ISSUE TITLE
Add "external source" enhancements to Users list, detail, and form

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#5685]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Users List
- Denote that a user comes from an external source (ie LDAP) as a tag next to the username

<img width="401" alt="Screen Shot 2020-01-16 at 4 47 33 PM" src="https://user-images.githubusercontent.com/15881645/72565484-f6bffa00-387f-11ea-99c7-597eebe54354.png">

User Detail
- Denote that a user comes from an external source (ie LDAP) as a tag under Type detail label
<img width="1198" alt="Screen Shot 2020-01-16 at 4 48 56 PM" src="https://user-images.githubusercontent.com/15881645/72565639-4bfc0b80-3880-11ea-95ff-0c67080537bc.png">

User Form
- Username field is required if user is not from an external source
- Password field should be hidden if user is from external source (ldap/radius/social auth users)
For reference, see [angular tower users form](https://github.com/ansible/awx/blob/devel/awx/ui/client/src/users/users.form.js#L62)

**Comment by tiagodread** [comment]
PR already merged, closing this issue
