### ISSUE TITLE
Users Form and Detail - UI Cleanup

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#5687]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Detail
* Move fields around to match [mockup](https://tower-mockups.testing.ansible.com/patternfly/users/users-detail/)
* Add **Created** and **Last Modified** Details
  * These fields are missing from `summary_fields`. We'll need to get them added by the api in order to show them??? This will require some discussion with UX/API team. 

Form
* Move form fields around to match the [mockup](https://tower-mockups.testing.ansible.com/patternfly/users/users-add/)
* Org lookup should be the last form field item

Current Form: 
<img width="1039" alt="Screen Shot 2020-01-16 at 4 59 24 PM" src="https://user-images.githubusercontent.com/15881645/72566474-e0b33900-3881-11ea-9aea-151feae2510e.png">

Mockup Form: 
<img width="1196" alt="Screen Shot 2020-01-16 at 4 59 48 PM" src="https://user-images.githubusercontent.com/15881645/72566495-e741b080-3881-11ea-86a3-f4d11ee4d30a.png">

##### ADDITIONAL INFORMATION

User Response Data
```
{
    "id": 6,
    "type": "user",
    "url": "/api/v2/users/6/",
    "related": {
        "named_url": "/api/v2/users/jt_admin/",
        "teams": "/api/v2/users/6/teams/",
        "organizations": "/api/v2/users/6/organizations/",
        "admin_of_organizations": "/api/v2/users/6/admin_of_organizations/",
        "projects": "/api/v2/users/6/projects/",
        "credentials": "/api/v2/users/6/credentials/",
        "roles": "/api/v2/users/6/roles/",
        "activity_stream": "/api/v2/users/6/activity_stream/",
        "access_list": "/api/v2/users/6/access_list/",
        "tokens": "/api/v2/users/6/tokens/",
        "authorized_tokens": "/api/v2/users/6/authorized_tokens/",
        "personal_tokens": "/api/v2/users/6/personal_tokens/"
    },
    "summary_fields": {
        "user_capabilities": {
            "edit": true,
            "delete": true
        }
    },
    "created": "2020-01-16T14:55:06.244656Z",
    "username": "jt_admin",
    "first_name": "",
    "last_name": "",
    "email": "",
    "is_superuser": false,
    "is_system_auditor": false,
    "ldap_dn": "",
    "last_login": null,
    "external_account": null,
    "auth": []
}
```

**Comment by mabashian** [comment]
We won't be able to add created/modified into without an api change but we can re-arrange the form fields to match the mockups.

**Comment by tiagodread** [comment]
@mabashian actual form is not matching to the mockup
![image](https://user-images.githubusercontent.com/12464858/118716803-a05c2600-b7fb-11eb-9fe0-ec322e85be51.png)
