### ISSUE TITLE
Survey is showing default answer instead of showing provided choice

### ISSUE THREAD

**Issue by Saurabh-Thakre** [ansible/awx#5689]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: latest
* Operating System: RHEL 8
* Web Browser: Google Chrome/Firefox

##### STEPS TO REPRODUCE

1. Create a new Job Template.
2. Create a new survey.
3.  Launch the template.
4. Select **disabled** in the survey drop down menu.
5. Now go back to **Other Prompts** menu.
6. Press **Next**.
7. Check that "update system" is set to "**disabled**" instead of **enabled** (see 7).

##### EXPECTED RESULTS

The **update_system** variable should show "**disabled**" as we've selected **disabled** in dropdown.

##### ACTUAL RESULTS

The **update_system** is showing "enabled" which is the default answer instead of showing **"disabled"** which is choosen in drop down

##### ADDITIONAL INFORMATION

![2 (2)](https://user-images.githubusercontent.com/21283108/72590412-9aaeb180-3923-11ea-8524-03901383d3e3.PNG)
![4](https://user-images.githubusercontent.com/21283108/72590468-c0d45180-3923-11ea-8941-ff63e4a090d2.PNG)

![5](https://user-images.githubusercontent.com/21283108/72590589-1a3c8080-3924-11ea-8d27-16ed98fd6a56.PNG)

* Now go back to **OTHER PROMPTS** and then come back to Survey

![6](https://user-images.githubusercontent.com/21283108/72590632-34765e80-3924-11ea-9293-b3c24e818905.PNG)

![7](https://user-images.githubusercontent.com/21283108/72590681-58d23b00-3924-11ea-94b7-b8b92632900e.PNG)

![8](https://user-images.githubusercontent.com/21283108/72590649-40622080-3924-11ea-93b3-61a144afb2a5.PNG)

**Comment by wenottingham** [comment]
Is there a value for the extra_var `update_system` set on the job template itself outside of the survey?

**Comment by Saurabh-Thakre** [comment]
> Is there a value for the extra_var `update_system` set on the job template itself outside of the survey?

@wenottingham No man

**Comment by krentiken** [comment]
hi!
if the value of the variable is equal to "enabled", then the system is updated.

....
      - name: Include update system
        include: tasks/update_system.yml 
        when: update_system == "enabled"
        tags:
        - update_system
....


    ---
      - name: Update all packages
        yum:
          name: "*"
          state: latest

      - name: Check for reboot hint
        shell: LAST_KERNEL=$(rpm -q --last kernel | awk 'NR==1{sub(/kernel-/,""); print $1}'); CURRENT_KERNEL=$(uname -r); if [ $LAST_KERNEL != $CURRENT_KERNEL ]; then echo 'reboot'; else echo 'no'; fi
        ignore_errors: true
        register: reboot_hint

      - name: Rebooting
        shell: "sleep 5 && reboot"
        async: 1
        poll: 0
        when: reboot_hint.stdout.find("reboot") != -1
        register: rebooting

      - name: Wait for server to reboot
        pause: seconds=180
        when: rebooting is changed

**Comment by jakemcdermott** [comment]
This is currently behaving as designed. Your inputs will _not_ be saved until you commit them by advancing to the next page of the prompt. This may be unexpected for some, so it's certainly an enhancement we should do. We've also made a note of  it in the docs.

**Comment by jakemcdermott** [comment]
plan is to address this in the rewrite

**Comment by mabashian** [comment]
This has been addressed in the new UI but I found #8247 while confirming.  Will close this out when we get that fixed.

**Comment by unlikelyzero** [comment]
we will need an explicit testcase for this

**Comment by akus062381** [comment]
Per @unlikelyzero, just execute and stub out.

**Comment by akus062381** [comment]
Coverage added: https://github.com/ansible/tower-qa/pull/6131
Testability issue added: https://github.com/ansible/awx/issues/9702
