### ISSUE TITLE
Inventory variable changes not shown in UI until refresh

### ISSUE THREAD

**Issue by mkayontour** [ansible/awx#569]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI
 

##### ENVIRONMENT
* AWX version: 1.0.1.137
* AWX install method: docker on linux
* Ansible version:  2.4
* Operating System: Debian Strectch
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

Didn't get it reproduced

##### EXPECTED RESULTS

I'm having a inventory defined in awx and when I want to update a variable the variable didn't get safed after all. Even if I remove the variables.

When I restart the Web Container it works again for a short time, in other words I can edit one variable and then I have to restart the container again. 

The `docker logs -f awx_web` don't provide any helpful information also I don't see any connection to the database in the logs of postgres.

**Comment by leifmadsen** [comment]
I ran into this issue, and things did appear to actually be saved, but you need to hard refresh the browser. It looks like the javascript isn't refreshing the contents from the database or wherever the data is stored.

If I hard refresh the page, I will see the items populated, but if I don't, then it either shows as blank, or doesn't update.

**Comment by matburt** [comment]
Seems similar to our other websocket problems which we are tracking in another bug.

**Comment by leifmadsen** [comment]
@matburt if you're tracking in another bug, could you please reference it here?

**Comment by matburt** [comment]
Websocket fixes will happen here: https://github.com/ansible/awx/issues/437

**Comment by matburt** [comment]
On thinking about this some more, I'm wondering if there was a UI error on your console? Can you check the developer/javascript console of your browser for any error messages while saving the form?

**Comment by leifmadsen** [comment]
Trying to save things, and I don't get any console errors on the UI. The only thing I get on the console is this:

`[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

Whenever I save, sometimes it saves, sometimes it doesn't. It seems to be more of a screen refresh issue as far as I can tell, because if I shift+f5 then it'll typically show up. And it doesn't seem to happen every time. Sometimes when I save, it's perfectly fine, and othertimes, it doesn't seem to refresh properly. Haven't seen any errors on the console though.

**Comment by mabashian** [comment]
Seems like there are a couple of things going on here:

1) On refresh the extra variables textarea is not be codemirror-ified properly:
<img width="1378" alt="screen shot 2017-11-07 at 11 28 52 am" src="https://user-images.githubusercontent.com/9889020/32504962-0a5d76d4-c3af-11e7-95f3-77aa9ab72405.png">

It should look like:
<img width="1370" alt="screen shot 2017-11-07 at 11 30 37 am" src="https://user-images.githubusercontent.com/9889020/32504996-1c487f92-c3af-11e7-9f7e-c6f1d7924eb0.png">

I seem to be able to reproduce that pretty consistently by navigating to the inventory form and refreshing the page.

2) The second thing that's going on here is what @leifmadsen and @mkayontour have outlined which is odd behavior when updating extra variables.  I can second @leifmadsen's summary of the bug.  Pretty consistently, if you change the extra variables and hit save they don't appear to update in the refreshed UI.  During my testing, the variables are being properly updated server-side which leads me to believe that this is a display issue.  Refreshing the page does show the updated variables but it also exposes issue 1 above.

I have really strong suspicions that this is tied to our recent upgrades of angular and ui-router but will need to investigate to gather more information.

Suggested workaround:  After editing an inventory, navigate back out to the inventory list and click the link to edit said inventory again.  This should properly display the updated variables.  Refreshing will also work but you'll likely see non-codemirror'd extra vars.

**Comment by mkayontour** [comment]
I can confirm that the behavior occurs on the extra vars, I surely didn't get vars properly displayed when navigating to the inventory again. - but I then waisted not so much time wondering. 

In addition the problem also occurred at the customer site when editing hosts. As you pointed out, changes at the UI,  that could be the form in general. 

on my local container I didn't ran into that issue till now.

**Comment by rromanchuk** [comment]
I can't save anything into variables on chrome o_O but safari is working... I haven't inspected chrome console yet, let me dig into it.
