### ISSUE TITLE
Migrate to Python 3

### ISSUE THREAD

**Issue by JG127** [ansible/awx#5690]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Now Python 2 really, really, really, finally has been deprecated, it would be time to migrate to Python 3. The current configuration obliges custom ansible extensions to be written for Python 2.

**Comment by ryanpetrello** [comment]
@JG127,

AWX's code itself was moved to Python3 quite some time ago, but many of our users still run their playbooks in Ansible under Python2.

We'll continue to support playbook execution under Python2 for as long as Ansible itself does.
