### ISSUE TITLE
Inventory Host Details Sparkline

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#5693]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The Sparkline in HostDetails/InventoryHostDetails does not navigate correctly.
##### ENVIRONMENT
* AWX version: 9.1
* AWX install method:  docker for mac
* Ansible version:  2.10
* Operating System: Mojave
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Host --> click on host that has jobs ---> Click on an item in the spark line.  
##### EXPECTED RESULTS

Navigate to the correct job output page.
##### ACTUAL RESULTS

Broken url
##### ADDITIONAL INFORMATION

At Host Details jobs does not have job.type and we need it to correctly build the url.

**Comment by dsesami** [comment]
Sparkline works, appears to populate correctly, and links to pages normally.
