### ISSUE TITLE
AWX ships analytics bundle multiple times per upload window. 

### ISSUE THREAD

**Issue by benthomasson** [ansible/awx#5708]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX ships analytics bundle multiple times per upload window. 

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.10.0.dev0 
* Operating System: Red Hat Enterprise Linux Server release 7.7 (Maipo) 
* Web Browser: N/A

##### STEPS TO REPRODUCE

Create a clustered environment.   Enable debug logging.  Wait for an upload window (*/6 hour)

> tail -n 10000 -f tower.log | grep 'shipping analytics file'

##### EXPECTED RESULTS

A single bundle upload.

-bash-4.2$ tail -n 10000 -f tower.log | grep 'shipping analytics file'
2020-01-20 18:00:00,875 DEBUG    awx.main.analytics shipping analytics file: /tmp/2afc1cba-4f00-4346-bb8b-a0a70c65aec1_2020-01-20-180000+0000.tar.gz

##### ACTUAL RESULTS

Multiple bundles are uploaded with the same data.    It seems to be uploading every minute for an hour ever 4 hours.   It is sending 60 times more uploads than required. 

> -bash-4.2$ tail -n 10000 -f tower.log | grep 'shipping analytics file'
> 2020-01-20 18:00:00,875 DEBUG    awx.main.analytics shipping analytics file: /tmp/2afc1cba-4f00-4346-bb8b-a0a70c65aec1_2020-01-20-180000+0000.tar.gz
> 2020-01-20 18:01:00,568 DEBUG    awx.main.analytics shipping analytics file: /tmp/2afc1cba-4f00-4346-bb8b-a0a70c65aec1_2020-01-20-180100+0000.tar.gz
> 2020-01-20 18:02:00,673 DEBUG    awx.main.analytics shipping analytics file: /tmp/2afc1cba-4f00-4346-bb8b-a0a70c65aec1_2020-01-20-180200+0000.tar.gz
> 2020-01-20 18:03:00,575 DEBUG    awx.main.analytics shipping analytics file: /tmp/2afc1cba-4f00-4346-bb8b-a0a70c65aec1_2020-01-20-180300+0000.tar.gz
> 2020-01-20 18:04:00,689 DEBUG    awx.main.analytics shipping analytics file: /tmp/2afc1cba-4f00-4346-bb8b-a0a70c65aec1_2020-01-20-180400+0000.tar.gz
> 2020-01-20 18:05:00,549 DEBUG    awx.main.analytics shipping analytics file: /tmp/2afc1cba-4f00-4346-bb8b-a0a70c65aec1_2020-01-20-180500+0000.tar.gz
> 2020-01-20 18:06:00,681 DEBUG    awx.main.analytics shipping analytics file: /tmp/2afc1cba-4f00-4346-bb8b-a0a70c65aec1_2020-01-20-180600+0000.tar.gz
> 2020-01-20 18:07:00,567 DEBUG    awx.main.analytics shipping analytics file: /tmp/2afc1cba-4f00-4346-bb8b-a0a70c65aec1_2020-01-20-180700+0000.tar.gz
> 2020-01-20 18:08:00,587 DEBUG    awx.main.analytics shipping analytics file: /tmp/2afc1cba-4f00-4346-bb8b-a0a70c65aec1_2020-01-20-180800+0000.tar.gz
> 2020-01-20 18:09:00,683 DEBUG    awx.main.analytics shipping analytics file: /tmp/2afc1cba-4f00-4346-bb8b-a0a70c65aec1_2020-01-20-180900+0000.tar.gz
> 2020-01-20 18:10:00,614 DEBUG    awx.main.analytics shipping analytics file: /tmp/2afc1cba-4f00-4346-bb8b-a0a70c65aec1_2020-01-20-181000+0000.tar.gz

**Comment by kdelee** [comment]
Verified this on downstream, won't take long to verify here but still need to do it

**Comment by appuk** [comment]
@ryanpetrello  I've setup the automation analytics credentials and enabled logging too, but I do not see any 'shipping analytics file' in the tower.log file
the analytics gather is working as expected, so not sure what's happening here

**Comment by appuk** [comment]
cc @kdelee @rooftopcellist ^

**Comment by ryanpetrello** [comment]
@appuk,

It looks like this log line is set to a higher verbosity by default (`logger.debug`):

https://github.com/ansible/awx/blob/devel/awx/main/analytics/core.py#L156

...so I wouldn't expect it to show up in logs for production installs by default.

I'm guessing that in @benthomasson's log output in the issue description, he was probably running in an environment with higher log verbosity (perhaps the development environment?).

Are you seeing the analytics data being delivered?  If so, it sounds like it's working okay to me.

**Comment by kdelee** [comment]
@ryanpetrello we did set the logging level to DEBUG to test in the 3.6.3 version and did see the logs

**Comment by ryanpetrello** [comment]
Also worth mentioning in case you're seeing different behavior across stable Tower versions:

If you change the `settings.LOG_AGGREGATOR_LEVEL = DEBUG` in the API/UI in older Towers (pre-3.6), the verbosity change doesn't take effect on the file system until *after* you restart Tower services.  The ability to toggle that setting and see logs start showing up _without_ service restarts is new behavior in 3.6:

https://github.com/ansible/awx/pull/3882
https://github.com/ansible/awx/issues/1998

**Comment by appuk** [comment]
Yes @ryanpetrello , I did restart the tower service after changing the settings 🤔

**Comment by appuk** [comment]
Couldn't directly verify the shipping of analytics bundle, although I did verify that the analytics data is being collected per interval and that multiple nodes don't try and send at once.
Based on the above note, closing the issue.
