### ISSUE TITLE
AWX ships analytics from every node in a cluster

### ISSUE THREAD

**Issue by benthomasson** [ansible/awx#5719]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX ships analytics from every node in a cluster due to the fact that it is run as a celery beat task and celery beat runs on every node in a cluster.    This causes duplicate data to be processed by Automation Analytics.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Build a cluster.  Configure automation analytics.   Look at logging on each node.

##### EXPECTED RESULTS

Only one node should ship analytics. 

##### ACTUAL RESULTS

All nodes ship analytics.

**Comment by kdelee** [comment]
@ryanpetrello @wenottingham I see the PR, do you all have a cluster up and can you suggest a way to test this?

**Comment by wenottingham** [comment]
I do not have a cluster up. Best way to test is probably just to set it to run often (every 30 mintues or so) and watch the logs to see which nodes are gathering & sending when. 

If you can instrument the receiving side as well, that helps, but I don't know how to do that.

**Comment by kdelee** [comment]
I built packages, spun up cluster and tested. Commented on PR...please let me know if you all make more changes as will have to test again

**Comment by kdelee** [comment]
related: https://github.com/ansible/tower/issues/3810

**Comment by kdelee** [comment]
closing this as tested as described on PR

**Comment by ryanpetrello** [comment]
@wenottingham @kdelee I'm not convinced this actually works, and I'd like to reopen it and take another look.

**Comment by appuk** [comment]
Verified that the analytics is only gathered once per interval, hence closing:
```
ec2-3-83-235-132.compute-1.amazonaws.com | CHANGED | rc=0 >>
145:2020-02-10 03:47:40,615 INFO     awx.main.tasks gathered analytics: /tmp/346196d2-3035-460f-96fc-7df17aa0e432_2020-02-10-034740+0000.tar.gz
856:2020-02-10 04:47:40,654 INFO     awx.main.tasks gathered analytics: /tmp/346196d2-3035-460f-96fc-7df17aa0e432_2020-02-10-044740+0000.tar.gz
1577:2020-02-10 05:47:40,607 INFO     awx.main.tasks gathered analytics: /tmp/346196d2-3035-460f-96fc-7df17aa0e432_2020-02-10-054740+0000.tar.gz
2298:2020-02-10 06:47:40,654 INFO     awx.main.tasks gathered analytics: /tmp/346196d2-3035-460f-96fc-7df17aa0e432_2020-02-10-064740+0000.tar.gz
2995:2020-02-10 07:47:40,760 INFO     awx.main.tasks gathered analytics: /tmp/346196d2-3035-460f-96fc-7df17aa0e432_2020-02-10-074740+0000.tar.gz
3711:2020-02-10 08:47:40,780 INFO     awx.main.tasks gathered analytics: /tmp/346196d2-3035-460f-96fc-7df17aa0e432_2020-02-10-084740+0000.tar.gz
4429:2020-02-10 09:47:40,945 INFO     awx.main.tasks gathered analytics: /tmp/346196d2-3035-460f-96fc-7df17aa0e432_2020-02-10-094740+0000.tar.gz
5150:2020-02-10 10:47:40,881 INFO     awx.main.tasks gathered analytics: /tmp/346196d2-3035-460f-96fc-7df17aa0e432_2020-02-10-104740+0000.tar.gz
5870:2020-02-10 11:47:41,067 INFO     awx.main.tasks gathered analytics: /tmp/346196d2-3035-460f-96fc-7df17aa0e432_2020-02-10-114740+0000.tar.gz
6570:2020-02-10 12:47:40,953 INFO     awx.main.tasks gathered analytics: /tmp/346196d2-3035-460f-96fc-7df17aa0e432_2020-02-10-124740+0000.tar.gz
7272:2020-02-10 13:47:41,016 INFO     awx.main.tasks gathered analytics: /tmp/346196d2-3035-460f-96fc-7df17aa0e432_2020-02-10-134740+0000.tar.gz
7946:2020-02-10 14:47:41,050 INFO     awx.main.tasks gathered analytics: /tmp/346196d2-3035-460f-96fc-7df17aa0e432_2020-02-10-144740+0000.tar.gz
```
