### ISSUE TITLE
Update the ansible runtime in the awx_task container

### ISSUE THREAD

**Issue by idelsink** [ansible/awx#5722]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX v9.1.1 is running ansible v2.8.5 while v2.9.4 has been released.

##### ENVIRONMENT
* AWX version: 9.1.1
* AWX install method: docker on linux
* Ansible version:  2.8.5
* Operating System: Ubuntu 18
* Web Browser: Unrelated

##### STEPS TO REPRODUCE

I installed AWX using the install steps for docker.

##### EXPECTED RESULTS

Expected to get the latest ansible version.

##### ACTUAL RESULTS

Got an old ansible version.

##### ADDITIONAL INFORMATION

I need a newer version of Ansible because i'm using the `aws_caller_info` module because the `aws_caller_facts` module is deprecated in favor of the `aws_caller_info` module.

**Comment by wenottingham** [comment]
This will happen in a future build.

**Comment by idelsink** [comment]
So I had an issue regarding reaching a machine over IPv6. Apparently this has already been fixed, see https://github.com/ansible/ansible/issues/56258 but this does impede the use of AWX in a production setup. When is the expected release date of a new version of AWX with a new ansible runtime?

**Comment by wenottingham** [comment]
9.2.0 was released just yesterday.
