### ISSUE TITLE
zuul job containers don't have "diff" command

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#5724]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

The schema change job has been failing with this error:

```
                                "# Ignore differences in whitespace with -b",
                                "diff -u -b reference-schema.json schema.json",
                                "make: diff: Command not found",
                                "make: *** [Makefile:672: detect-schema-change] Error 127",
                                "command terminated with exit code 2"
```

##### STEPS TO REPRODUCE

This check runs on all PRs...need to fix how the container is built to include `diff`

**Comment by kdelee** [comment]
updated to `diff` because that's the real problem

must have been having C++ flash backs

**Comment by ryanpetrello** [comment]
@shanemcd you have time to poke at this in the near future?  Been on my list, but just haven't gotten around to it.

**Comment by shanemcd** [comment]
@ryanpetrello Just in case it isn't obvious, this runs in the context of the development image so adding it should be pretty trivial. I'll try to get a PR up sometime later today unless someone beats me to it.
