### ISSUE TITLE
Machine credential in enviornment variables

### ISSUE THREAD

**Issue by fvzwieten** [ansible/awx#5730]
##### ISSUE TYPE
Machine credentials are not available in environment variables during execution of a job template.

##### SUMMARY
Currently, all credential types expose their details in environment variables during execution of play's in a job template, except for machine credentials. However, there is a common workflow that would greatly benefit from them. This is the workflow of creating a VM using ansible in VMware, Azure, Google Cloud, etc. Each of these 'clouds' have some way of specifying an initial (admin) user to be created inside the VM. It would be great if we can then specify the username and password from a machine credential to these cloud modules so we can, in later job templates use the same credential to execute plays inside these VM's.

This is currently not possible. The only workaround I found was to put the same details of the machine credential in a vault and put the vault credential on the job template that creates the VM, exposing the vault and thus the details in the play.

I propose to make the machine credentials available as environment varaibles during execution of the playbook of the job template to solve this.

**Comment by wenottingham** [comment]
Credentials are delegated; playbooks can be run without access directly to the credentials, as a means to restrict their unauthorized use by people who don't otherwise have access to the credentials. While we accept what this means for credentials that have to be passed as env vars and/or extra vars, for ones that aren't passed that way, we would rather not *expand* that information leak into the playbooks for use.

**Comment by fvzwieten** [comment]
I found a workaround for this that I will document here so people might find this useful.
The machine credentials are available in environment variable ansible_user and ansible_password, but when using connection: local it will switch to user "awx" (when using awx/tower). So, to get the correct credentials when using connection: local I create a dummy host in a pre play without connection: local and then retrieve those to use in a subsequent play to use.

In example code:
---
- name: use machine credentials
  hosts: localhost
  gather_facts: no
  tasks:
  - name: add dummy host
    add_host:
      name: "dummy"
      user: "{{ansible_user}}"
      pwd: "{{ansible_password}}"

  - name: show stored machine credentials
    debug:
      msg: "Username = {{ hostvars['dummy'].user }} Password = {{ hostvars['dummy'].pwd }}"

  - name: show actual machine credentials
    debug:
      msg: "Username = {{ ansible_user }} Password = {{ ansible_password }}"

- name: use machine credentials
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: show stored machine credentials
    debug:
      msg: "Username = {{ hostvars['dummy'].user }} Password = {{ hostvars['dummy'].pwd }}"

  - name: show stored machine credentials
    debug:
      msg: "Username = {{ ansible_user }} Password = {{ ansible_password }}"

Output:
PLAY [use machine credentials] *************************************************

TASK [add dummy host] **********************************************************
changed: [localhost]

TASK [show stored machine credentials] *****************************************
ok: [localhost] => {
    "msg": "Username = ansible Password = P@$$w0rD"
}

TASK [show actual machine credentials] *****************************************
ok: [localhost] => {
    "msg": "Username = ansible Password = P@$$w0rD"
}

PLAY [use machine credentials] *************************************************

TASK [show stored machine credentials] *****************************************
ok: [localhost] => {
    "msg": "Username = ansible Password = P@$$w0rD"
}

TASK [show stored machine credentials] *****************************************
ok: [localhost] => {
    "msg": "Username = awx Password ="
}
