### ISSUE TITLE
vmware_vm_inventory dynamic inventory support

### ISSUE THREAD

**Issue by MrBones757** [ansible/awx#5731]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Implementation of Ansible's vmware_vm_inventory plugin.

I have noticed there is an 'Implement me' here: https://github.com/ansible/awx/blob/6d075b8874e7a352596b7b23caea1ce96db237b9/awx/main/models/inventory.py#L2234

Is there any in-progress plans to implement this plugin?

I've been using the existing inventory script and have found issues with support for grouping by tags and it is quite slow for large inventories. vmware_vm_inventory has work in progress to improve performance (https://github.com/ansible/ansible/issues/56786) and includes tagging functionality already.

I'd be willing to have a look at this myself but didn't want to double up on any WIP.

**Comment by AlanCoding** [comment]
It's not clear that switching to the plugin would address what you're interested in. Although we have changed over to use the plugins, the options (as taken from source variables) still maintain accept options as they were in the script, in this case, https://github.com/ansible/ansible/blob/devel/contrib/inventory/vmware_inventory.ini. If you want the ability to enter options as they are documented for the current inventory plugin, that is https://github.com/ansible/awx/issues/4306

**Comment by wenottingham** [comment]
closing as duplicate
