### ISSUE TITLE
expose K8S/OCP credentials for playbook use

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#5735]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
We have a bearer token credential type that is used for the container group feature.

There does not appear to be a reason it cannot be used for general playbook runs.

The `k8s` ansible module accepts `K8S_AUTH_HOST` and `K8S_AUTH_API_KEY` env vars.

**Comment by shanemcd** [comment]
Note: there are some security concerns regarding the k8s module's usage of these env vars. We'll want to sync up with the core team before implementing this.

**Comment by tima** [comment]
@shanemcd: Here is your best place for that: https://github.com/ansible-collections/kubernetes

/cc @geerlingguy @fabianvf

**Comment by wenottingham** [comment]
To do this we'd also want to vendor in the ansible venv the minimal dependencies used by the OCP & K8S modules. Would be the same ones we already have in the AWX venv.

**Comment by ryanpetrello** [comment]
Also `K8S_AUTH_SSL_CA_CERT` and `K8S_AUTH_VERIFY_SSL`.

**Comment by ryanpetrello** [comment]
@shanemcd is the security issue you're concerned about specific to using the k8s _module_ with environment variables?  My recollection (assuming I'm thinking the same thing from back when we wrote the container groups feature) was that the *k8s **connection plugin*** exposes (sensitive) environment variables in its verbose output.  If that's the case, I don't think that's the same concern _here_ - _this_ ticket is just a matter of injecting secrets into environ vars so that users can make use of https://docs.ansible.com/ansible/latest/modules/k8s_module.html without putting tokens in their playbooks.

**Comment by ryanpetrello** [comment]
Whoever ends up testing this, here's a playbook that provides a good test case:

```
---

- hosts: all
  gather_facts: false
  tasks:
    - name: Get a list of all pods from any namespace
      k8s_info:
        kind: Pod
      register: pod_list

    - name: Print pod names
      debug:
        msg: "pod_list: {{ pod_list | json_query('resources[*].metadata.name')  }} "
```

cc @elyezer

**Comment by elyezer** [comment]
Checked the new changes on the current UI + API by doing the following

1) creating a credential, copied some times
2) Assigned the credential to Job Templates and ran them
3) Made sure a playbook would not work if the credentials was not used
4) Checked the cloud icon was present in the UI

**Comment by elyezer** [comment]
@unlikelyzero are we ready to close this? Anything pending from the UI next perpective?

**Comment by unlikelyzero** [comment]
The z stream work pushed this down to my number 2 priority. I'll put the PR up when ready based on these changes:

https://www.github.com/ansible/tower-qa/tree/k8s-credential-stubs/ui-tests%2Fawx-pf-tests%2Fcypress%2Fintegration%2Fcredential-types

**Comment by elyezer** [comment]
This is verified from the API perspective, final UI work is being done and this will be ready to close once that is done.

**Comment by kdelee** [comment]
@unlikelyzero ping this is now in y'alls court

**Comment by ryanpetrello** [comment]
@unlikelyzero you have any updates on this one?

**Comment by unlikelyzero** [comment]
@ryanpetrello I lumped it into a general credential test refactor which kept creeping in scope. Let me short circuit the coverage and link back to this PR to close it out

**Comment by elyezer** [comment]
I will go ahead and close this one as verified. There are some refactoring happening for credentials test for the ui_next that includes a larger scope than this specific feature, that can be tracked separately on a specific issue.

**Comment by unlikelyzero** [comment]
@elyezer this was not fully verified in the existing UI

**Comment by elyezer** [comment]
@unlikelyzero according to https://github.com/ansible/awx/issues/5735#issuecomment-685027485 I thought it was missing just the tests refactor for the new UI. It is a surprise to me that this hasn't been checked on the current UI, thanks for the heads up.

**Comment by unlikelyzero** [comment]
Sorry for the delay. Closing.
Tested:
- OpenShift or Kubernetes API Bearer Token can be added to a JT during initial JT create.
- OpenShift or Kubernetes API Bearer Token can be added to an existing JT
- Only one OpenShift or Kubernetes API Bearer Token can be added to a JT
- 15 OpenShift or Kubernetes API Bearer Tokens can be seen and filtered for in the Add Credential lookup
- A JT with OpenShift or Kubernetes API Bearer Token can be added to an existing JT can be copied
- A JT with OpenShift or Kubernetes API Bearer Token can be added to an existing JT
- A JT with OpenShift or Kubernetes API Bearer Token can be configured to Prompt on Launch
- Once Run, an OpenShift or Kubernetes API Bearer Token can be seen on the Job Result Output page and correctly navigates to the correct credential edit screen once clicked
- A user with limited permissions can see the OpenShift or Kubernetes API Bearer Token on a JT once configured.

**Comment by kdelee** [comment]
fwiw not all modules in the kubernetes collection use the same env vars https://github.com/ansible-collections/community.kubernetes/issues/289

**Comment by colans** [comment]
If you have client certificate data in your `kubeconfig`, you can't use the Bearer Token credential type.  So I added a feature request for adding a Kubernetes configuration file credential type.  It would also make it easier to simply provide the whole file, even if you are using tokens.  See https://github.com/ansible/awx/issues/15574 for details.
