### ISSUE TITLE
Allow external RabbitMQ instance

### ISSUE THREAD

**Issue by yuha0** [ansible/awx#574]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - Installer

##### SUMMARY

Is it possible to have AWX to connect to an external RabbitMQ broker? I have a powerful, general purpose RabbitMQ cluster so I think managing a dedicated broker for AWX only will add unnecessary overhead in my infrastructure.

**Comment by matburt** [comment]
This isn't currently planned due to the fundamental architecture of Tower and AWX.

**Comment by qk4l** [comment]
Hi, @matburt could you please provide more information about blocker which does not allow to use separate dedicated HA cluster of RabbitMQ?

I can`t get a nut what a difference between connectivity awx-task with RabbitMQ thought  127.0.0.1 versus LAN address example 10.10.0.1 or FQDN.

Thanks.

**Comment by matburt** [comment]
What I'd *really* like to do is move away from RabbitMQ entirely and that's the plan over the next little while. The operational complexity of trying to manage a cluster like this is pretty high. We deploy RabbitMQ on each node and cluster RabbitMQ together to drive the actual clustering interconnectivity.  A lot of time folks are looking for geographic redundancy or a multi-region AWX but in my experience this just isn't a great operational approach to it.

**Comment by matburt** [comment]
It's probably fine if you want to rework the deployment to use your own Rabbit cluster... it's just not what I've planned for the AWX deployment architecture. I'd like to remove the need for RabbitMQ entirely as soon as possible.
