### ISSUE TITLE
SSH Machine Credential Signed Certificate not calling add-key

### ISSUE THREAD

**Issue by VivaLaPanda** [ansible/awx#5741]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When using SSH Signed Cert credential, my job fails to SSH to the server. I see similar issues in the log, but in all cases add-key gets called and then fails. In my case it's not apparent that the provided SSH Signed Key is being used at all.

##### ENVIRONMENT
* AWX version: 5.0.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.1
* Operating System: Windows
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Create a credential type "machine" with an ssh private key and a public key signed by a CA trusted by the target host. This was tested by manually SSHing into the host using the private key and signed public key that are entered into AWX.
Then run any job using the provided credential.

##### EXPECTED RESULTS

I expect authentication to succeed. More generally, I expect the logs to show Ansible adding the signed key and the using it. [The logs](https://pastebin.com/iKsTTQa2) don't show any such behavior occurring, and it's near impossible to determine what exactly is causing the failure.

##### ACTUAL RESULTS

Authentication will fail with the following error https://pastebin.com/J3cmmK5u

**Comment by ryanpetrello** [comment]
@VivaLaPanda you're encountering a bug that was fixed in a later version of AWX (so you'll need to upgrade to a newer version to fix it):

https://github.com/ansible/awx/issues/4139
https://github.com/ansible/awx/pull/4320

https://github.com/ansible/awx/blame/devel/CHANGELOG.md#L106

**Comment by VivaLaPanda** [comment]
Thanks, upgrading fixed it. Sorry for the spurious issue, I was having difficulties determining whether the issue was a problem with that version or something else.
