### ISSUE TITLE
Add field to change inventory of job template in workflow.

### ISSUE THREAD

**Issue by astateofmind01** [ansible/awx#5755]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

When adding jobs to Workflows would be great to add/edit/select the inventory to each step. 

So if i have a playbook that i can run on 20 inventories i don't have to first create 20 jobs and add them in the workflow, i can just have one job template and add it with the inventory i need 20 times.

**Comment by wenottingham** [comment]
I feel like https://github.com/ansible/awx/issues/2941 is a better solution for this.
