### ISSUE TITLE
Installation on a differen Database Schema

### ISSUE THREAD

**Issue by ThomasUllrich666** [ansible/awx#5757]
##### ISSUE TYPE
Choose a database schema if you install AWX

##### SUMMARY
Add a inventory variable pg_schema to the Inventory config file and install the Porstgre Database under this schema. This will allow users how run multiple applications on the database to separate applications (like ansible awx) with the help of schemas

**Comment by ryanpetrello** [comment]
We're unlikely to support this.  AWX is intended to run under its own schema, which is managed by the AWX source tree itself and not customizable.

**Comment by HarishAmeen** [comment]
Is there any plans make the schema name configurable? Its especially useful with AWX is pointed to external DB server thats also hosting other applications.
