### ISSUE TITLE
Git clone from a x509 secured git repository is not working

### ISSUE THREAD

**Issue by linkeal** [ansible/awx#5759]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Cloning a github repository which is secured with certificates does not work in the awx_task container

##### ENVIRONMENT
* AWX version: 9.1.1
* AWX install method: docker
* Ansible version:  2.7.8
* Operating System: Docker container base is CentOS. Host is SLES.
* Web Browser: Chrome

Git version (container): git version 2.18.1
 
##### STEPS TO REPRODUCE

1. Start awx_task container
2. Configure global /etc/gitconfig to use a repository hosted behind certificates
3. git clone repository

##### EXPECTED RESULTS

Successful clone.

##### ACTUAL RESULTS

fatal: unable to access 'http://myrepository.com/repo': SSL certificate problem: unable to get local issuer certificate

##### ADDITIONAL INFORMATION

The exact same procedure works completely fine on a latest ubuntu container though. I couldn't yet figure out if it relates to the exact git version that is installed in the container or something else. I'll investigate further.

**Comment by wenottingham** [comment]
Is this a self-signed cert, or do you have your local CA mapped into the container?

**Comment by linkeal** [comment]
Yes it is self-signed and the CA is mapped into the container and also defined in the gitconfig.
I have now worked around the problem via `ssl_verify = false` in the gitconfig. Probably not even related to AWX but rather the docker base image and its components like git / ca-certificates etc.
