### ISSUE TITLE
Skip Tags and Job Tags Open LabelSelect

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#5760]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When you generate a new skip tag or job tag in a JobTemplate, and press enter to create the chip the dropdown for the LabelSelect also opens

##### ENVIRONMENT
* AWX version: 9.1.1
* AWX install method:  docker for mac
* Ansible version:  2.10
* Operating System: Mojave
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Go to a create or edit a Job Template.  Begin to generate a new skip tag or job tag by typing iin the field.  Press enter to generate the tag.  
##### EXPECTED RESULTS

A chip with the tag name appears in the field and the dropdown closes.  
##### ACTUAL RESULTS

The label tag opens and covers much of the form and the field you were typing in remains open as well.
##### ADDITIONAL INFORMATION

![Tags](https://user-images.githubusercontent.com/39280967/73079261-e0bec480-3e91-11ea-8186-6be150142a24.gif)

**Comment by AlexSCorey** [comment]
Add on, when you press Enter anywhere on the JT form it opens/closes the LabelSelect.  It also will submit the form, given all the validation passes.

**Comment by mabashian** [comment]
Yea, the part where it submits the form is pretty aggravating.  Going to bump up the priority on this one.

**Comment by dsesami** [comment]
While this one is _usable_, I'm going to have to ask if there's a better solution for large amounts of tags -- it actually pushes the entire page upwards when you scroll and looks really weird. can we make it so the tag dropdown itself scrolls?

![Screenshot from 2020-04-01 10-19-22](https://user-images.githubusercontent.com/19942822/78148101-6f0b7580-7402-11ea-86f6-5559bacafb3a.png)

**Comment by dsesami** [comment]
Above comment is handled in https://github.com/patternfly/patternfly/issues/2819. Closing this out.
