### ISSUE TITLE
Cant copy mult files in windows to remote dir.

### ISSUE THREAD

**Issue by wagfeliz** [ansible/awx#5761]
Hi,

I could not use the win_copy as follows, it seems to be not implemented since it cant understand file partners on src input : 

     win_copy:
        src: "c:\temp\*.bkp"
        dest: \\192.168.1.1\bkp\

The only way I could do it was using an remote script, what is not clean.

There is any flag or similar command do the same effect ( windows remote ) ?

Regards,
Wagner.

**Comment by wenottingham** [comment]
Hi, this issue tracker is for issues in AWX itself. This looks like an Ansible usage question, and is better suited for one of our Ansible community communication channels: https://docs.ansible.com/ansible/latest/community/communication.html
