### ISSUE TITLE
Configure Instance Groups on an Individual Host/Host Group Level

### ISSUE THREAD

**Issue by falcon78921** [ansible/awx#5763]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Per a customer's request, they would like to be able to configure instance groups on an individual host/host group level.

**Comment by falcon78921** [comment]
See: https://github.com/ansible/awx/issues/5711#issuecomment-577271776

**Comment by wenottingham** [comment]
This would imply implicitly splitting playbook executions into multiple ansible-playbook calls, and we do not have plans to do this.
