### ISSUE TITLE
HTML escaping in workflow launch dialog

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#5764]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Workflow template:
![Screenshot from 2020-01-24 16-20-13](https://user-images.githubusercontent.com/5208768/73104895-86d7f200-3ec5-11ea-90d7-2221d92f5bfa.png)

Launch dialog:
![Screenshot from 2020-01-24 16-20-25](https://user-images.githubusercontent.com/5208768/73104902-8b040f80-3ec5-11ea-98e6-e1a41a055cef.png)

##### ENVIRONMENT
* AWX version: current

**Comment by blomquisg** [comment]
@wenottingham Do we need this in 3.7?  Sounds like this will be obsolete in 4.0 with pf.

**Comment by wenottingham** [comment]
It can wait until the UI rewrite, but I wouldn't not take a patch that appeared.

**Comment by mabashian** [comment]
This will almost certainly be addressed with a fresh implementation of launch prompting in UI Next.  I'm going to throw this in the project with the expectation that it'll likely move straight to needs_test at some point.

**Comment by mabashian** [comment]
We'll need to add https://github.com/ansible/awx/issues/8249 before we can verify this.

**Comment by mabashian** [comment]
Will add this to #8249
