### ISSUE TITLE
Add retry to logging integrations

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#577]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY

The logging service configured could be down, or suffer a transient error.

Having a minimal level of 'retry' would avoid message/data loss.

##### ADDITIONAL INFORMATION

Not valid for LOG_AGGREGATOR_PROTOCOL=UDP, obvs.

**Comment by shanemcd** [comment]
I think the move to rsyslog got us this?

**Comment by ryanpetrello** [comment]
Yep, it did!
