### ISSUE TITLE
[AWX 9.1.1] Missing "which" command and link to /usr/bin/python

### ISSUE THREAD

**Issue by devops-42** [ansible/awx#5770]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 - Installer

##### SUMMARY
In my playbooks I use the command

```
which python
````

to check, where the python interpreter resides on the machine. In current AWX container (`awx_task`) the `which` command is missing. After adding it manually I checked again and found, that `which` cannot find any `python` binary within the standart $PATH. I need to symlink `/usr/bin/python2.7` to `/usr/bin/python` additionally.

##### ENVIRONMENT
* AWX version: 9.1.1
* AWX install method: docker on linux
* Ansible version:  2.9
* Operating System: CentOS
* Web Browser: n/a

##### STEPS TO REPRODUCE

Install AWX and run a playbook containing:

```
- name: Detect python path
  command: which python
```

##### EXPECTED RESULTS

Ansible finds python in one of the $PATH directories

##### ACTUAL RESULTS

```
"msg": "Child start failed: [Errno 2] No such file or directory. Command was: /usr/bin/python -c \"import codecs,os,sys;_=codecs.decode;exec(_(_(\\\"[OMITTED]\\\".encode(),\\\"base64\\\"),\\\"zip\\\"))\"",
```

##### ADDITIONAL INFORMATION

n/a

**Comment by ryanpetrello** [comment]
@devops-42 this will be resolved in the next published version of AWX (see: https://github.com/ansible/awx/pull/5845)
