### ISSUE TITLE
JT Form Throws Validation Warning Erroneously

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#5775]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
On a job template, when you click on a required field and then enter valid data for that field the jt throws a validation warning until you `onBlur` that field.  
##### ENVIRONMENT
* AWX version: 9.1.1
* AWX install method: docker for mac
* Ansible version:  2.10
* Operating System: Mojave
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Add a JobTemplate.  Click on Inventory, or Project and select 1 from the list.  Notice that when the LookUp modal closes you have a warning beneath the field that says "Select a value for this field".  
##### EXPECTED RESULTS

No warning should show up
##### ACTUAL RESULTS

Warning shows up.
##### ADDITIONAL INFORMATION

![ValidationWarning](https://user-images.githubusercontent.com/39280967/73199308-9a23d100-4102-11ea-92a7-6b31bb47cced.gif)

**Comment by mabashian** [comment]
I'm pretty sure this is no longer an issue - going to close.
