### ISSUE TITLE
Project JobTemplates Tab

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#5777]
##### ISSUE TYPE
Add functionality for the Job Templates tab within a project.

##### SUMMARY
https://tower-mockups.testing.ansible.com/patternfly/projects/projects-templates/

**Comment by dsesami** [comment]
Clicking the job template hyperlink does not work correctly. It simply continues to append the URL after repeated clicks:

![Screenshot from 2020-02-20 13-24-27](https://user-images.githubusercontent.com/19942822/74966080-675cb800-53e4-11ea-8596-6a29580f5c56.png)

**Comment by dsesami** [comment]
https://github.com/ansible/awx/issues/6002 also occurs on this tab.

**Comment by dsesami** [comment]
since #6002 is part of a larger issue, and #6015 is resolved, I'm closing this out. Thanks for the work on this.

**Comment by unlikelyzero** [comment]
@dsesami can you add your test stubs to this PR
