### ISSUE TITLE
Text wrapping looks odd

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#5794]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
This is an inventory host details snippet:
![Screenshot from 2020-01-29 14-37-26](https://user-images.githubusercontent.com/19942822/73391305-ad22d680-42a5-11ea-834d-bbd53099876d.png)

Text wrapping looks a bit awkward when breaking it up by letter here. The immediate thought is to break lines by words, but this could be difficult for longer words. One might consider breaking up items by words, but somehow introducing logic to further break up words if necessary. Worth a bit of experimentation to see what looks best.

##### ENVIRONMENT
* AWX version: latest

**Comment by unlikelyzero** [comment]
We should add test (stubs) for certain string lengths. 
Test minimal, max, wrap, wrap+1

**Comment by unlikelyzero** [comment]
we have visual coverage on almost every detail form
