### ISSUE TITLE
system settings shows new venv but patching returns 'is not a valid virtualenv'

### ISSUE THREAD

**Issue by magick93** [ansible/awx#5795]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I'm going through the process of adding a venv as described on https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md

##### ENVIRONMENT
* AWX version: 9.1.1
* AWX install method: openshift
* Ansible version:  whatever ships with 9.1.1
* Operating System: Centos 7 and ubuntu 18
* Web Browser: Firefox

##### STEPS TO REPRODUCE

1. Go through instructions on https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md
1. Ensure newly created venv shows up http://awx/api/v2/config
1. Attempt to PATCH a project with http://awx/api/v2/projects/16/

##### EXPECTED RESULTS

Expect to be able to assign a venv to a project etc, as it says in the docs (see link above).

##### ACTUAL RESULTS

I get a REST result of:

```
{
    "custom_virtualenv": [
        "/opt/custom-venvs/openshift-install-3.11 is not a valid virtualenv in /var/lib/awx/venv"
    ]
}
```

##### ADDITIONAL INFORMATION

![Selection_015](https://user-images.githubusercontent.com/2173213/73411810-90e96d00-436b-11ea-8744-6360dc81c272.png)

**Comment by wenottingham** [comment]
CUSTOM_VENV_PATHS is a toplevel path where venvs are expected to be located. It is not expected to be a virtual environment itself. You probably want your setting to be just /opt/custom-venvs/

**Comment by magick93** [comment]
Hi @wenottingham 

I'm not sure I understand correctly.

My venv is located at `/opt/custom-venvs/openshift-install-3.11`, and I can see this does exist on the `awx-web` container.

**Comment by magick93** [comment]
Ah, ok - I was meant to run

`HTTP PATCH /api/v2/settings/system/ {'CUSTOM_VENV_PATHS': ["/opt/custom-venvs/"]}`

Not 

`HTTP PATCH /api/v2/settings/system/ {'CUSTOM_VENV_PATHS': ["/opt/custom-venvs/openshift-install-3.11/"]}`
