### ISSUE TITLE
Scheduled Jobs should be able to be restored to a different server / new cluster

### ISSUE THREAD

**Issue by dsglaser** [ansible/awx#5797]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Scheduled Jobs can be restored to the same machine that they started on, but if you are restoring to another machine or a new cluster, they do not get restored. I believe this is because they are keyed on template IDs. They should be able to be restored on a new machine.

**Comment by wenottingham** [comment]
What is the mechanism you are using for restoring them?

**Comment by dsglaser** [comment]
I'm working off customer information, but they said they were doing a setup.sh backup/restore.

**Comment by dsglaser** [comment]
Moved to [Tower issue queue #4110](https://github.com/ansible/tower/issues/4110) per request
