### ISSUE TITLE
Team Edit - values do not get reflected unless the page is refreshed

### ISSUE THREAD

**Issue by appuk** [ansible/awx#5799]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After editing a Team, the old values persist on the Team details page and the updated values are only displayed after refreshing the page

##### STEPS TO REPRODUCE
1. Edit a Team
2. Save the changes
3. check the edited fields

##### EXPECTED RESULTS
The updated values should be displayed

##### ACTUAL RESULTS
Values do not get reflected unless the page is refreshed
![team-edit](https://user-images.githubusercontent.com/11617351/73483084-e1ad9580-436c-11ea-9013-3c0a379f4781.gif)

**Comment by marshmalien** [comment]
Related https://github.com/ansible/awx/issues/5278
