### ISSUE TITLE
How to stop the awx docker containers? Please add it to the readme.

### ISSUE THREAD

**Issue by viktorsmari** [ansible/awx#58]
### Summary

You start the containers with:
`ansible-playbook -i inventory install.yml`

How do you stop them?

### Expected Results:

All containers should be stopped.

**Comment by matburt** [comment]
https://docs.docker.com/engine/reference/commandline/stop/

**Comment by viktorsmari** [comment]
So @matburt,  is this the only way to stop it:
`docker stop awx_task awx_web memcached rabbitmq postgres`
?

I was hoping for something easier like
`docker-compose up`
`docker-compose down`

**Comment by matburt** [comment]
If you use the development environment then you have more options for stopping. For the production container, it's deployed to run under the docker daemon on your server and there are multiple ways to manage running containers in that situation.

Managing production services is up to the user and out of the scope of the AWX project.

**Comment by cfuentea** [comment]
hi @matburt , if i stop all my containers i will lose all the servers and templates saved?

**Comment by mkempster22** [comment]
You wont lose data when stopping or removing the containers as the data from the postgres db container is stored in the location you specified in the inventory file (postgres_data_dir=/path/to/dir)
If you delete that folder you will lose all your data, also note that I think the default directory is still in /tmp for some reason so that may get wiped when rebooting if you have /tmp setup to do that

**Comment by thechitowncubs** [comment]
> So @matburt, is this the only way to stop it:
> `docker stop awx_task awx_web memcached rabbitmq postgres`
> ?
> 
> I was hoping for something easier like
> `docker-compose up`
> `docker-compose down`

You can goto /tmp/awxcompose and docker-compose down from there.

**Comment by J00MZ** [comment]
> docker stop awx_task awx_web memcached rabbitmq postgres

minor correction for those running with default [`docker-compose`](https://github.com/ansible/awx/blob/devel/INSTALL.md#docker-compose) setup:
`sudo docker stop  awx_task awx_web awx_memcached awx_rabbitmq awx_postgres`

**Comment by hendrul** [comment]
docker-compose -f ~/.awx/awxcompose/docker-compose.yml stop

**Comment by HoffiMuc** [comment]
just having a look in the `Makefile` under target `docker-compose:` I'd say:

```
# source from Makefile: (but without '-' in docker-compose
# create containers from image
docker compose -f tools/docker-compose/_sources/docker-compose.yml up --detach

# stop containers
docker compose -f tools/docker-compose/_sources/docker-compose.yml stop
# start containers
docker compose -f tools/docker-compose/_sources/docker-compose.yml start
```
