### ISSUE TITLE
How to correctly upgrade awx version without losing changes. 

### ISSUE THREAD

**Issue by ricalenil** [ansible/awx#580]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME

 - UI

##### SUMMARY
I need to know how to upgrade awx containers in docker without loosing my data.

##### ENVIRONMENT
* AWX version: 1.0.1.83
* AWX install method: docker on linux
* Ansible version:  2.4.0
* Operating System: Ubuntu 16.04
* Web Browser: Firefox

##### STEPS TO REPRODUCE

ansible-playbook -i inventory install.yml

##### EXPECTED RESULTS

upgrade to new version...

##### ACTUAL RESULTS

it migrates again and lost all my data.

**Comment by savealive** [comment]
Had the same issue when upgrading AWX from commit f1813c35ed829b133af6e8f551eba6f40f8c806d. It just started migration job in awx_task container.

**Comment by matburt** [comment]
I made a change a week or so ago: https://github.com/ansible/awx/pull/535

Which probably affected you there. I gave some examples on how to backup and restore your existing data.
