### ISSUE TITLE
Slack notifications failing with "missing_scope"

### ISSUE THREAD

**Issue by tfmm** [ansible/awx#5803]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
New setup, adding slack notifications, slack bot user has access to chat.write scope via Slack. Try to test notifications, get error "missing_scope".

##### ENVIRONMENT
* AWX version: 9.1.1
* AWX install method: docker on linux
* Ansible version:  2.8.5
* Operating System: Ubuntu 18.04
* Web Browser: Chrome, but reproduces in all

##### STEPS TO REPRODUCE

Add slack notification setting with the following info: 
Name: Slack notifications
Organization: <pick one>
Type: Slack
Destination channels: #awx-notifications
Token: <valid oauth token from slack bot settings>

Save notification template, and try to test notifications

##### EXPECTED RESULTS

Notification to show up in referenced slack channel

##### ACTUAL RESULTS

Error message in AWX stating "missing_scope"

##### ADDITIONAL INFORMATION

Bot user currently has all of these scopes:
channels:read
chat:write
im:write
incoming-webhook
links:write
team:read
users:read
users:read.email
users:write

I'm guessing either AWX has not been updated to work with the latest version of Slack bot users, or I'm just missing some random scope, would appreciate any help in identifying it.

**Comment by tfmm** [comment]
Closing this, turns out it was some issue with the bot user on slack end, re-created from scratch, and it's fine now.

**Comment by metabsd** [comment]
Where you find the information about what is the scope needed for that notification template ?
Thx!

**Comment by yurtesen** [comment]
I have added scope `incoming-webhook` I think the documentation is very behind compared to current slack settings....
