### ISSUE TITLE
AWX Ansible debugging

### ISSUE THREAD

**Issue by ghost** [ansible/awx#5811]
##### ISSUE TYPE
 - Debugging

##### SUMMARY

I need to have ability to run and debug application django web application that runs in docker container. There is link on it: https://github.com/ansible/awx I tryed to stop awx_web application from container and run start it from PyCharm IDE. Application starts, but I have default message: AWX is upgrading and after that I don't get login to account page. Can you help me how can I solve mey issue? Thanks for any answers.
When I run application in both places (docker and pycharm) I get next message: Error: That port is already in use. How to add access to the application port in the docker container?

Can you help me how can I solve mey issue? Thanks for any answers.

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method:  docker on linux
* Ansible version:  2.9.4.
* Operating System: Ubuntu 19.10
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

1) Install and deploy awx ansible application with docker on local mashine
2) Localy install python dependences for run application via PyCharm.
3) Turn off container image with awx_web application.
4) Run awx ansible from IDE.

##### EXPECTED RESULTS

Should be page for input login and password.
##### ACTUAL RESULTS

When it starts from IDE in browser there is AWX Upgrading message that not finished.

**Comment by wenottingham** [comment]
If you're looking to install and debug modified AWX, please use the development environment setup documented here: https://github.com/ansible/awx/blob/devel/CONTRIBUTING.md#setting-up-your-development-environment

The installer is intended for non-developer deployments.

**Comment by ghost** [comment]
I took all the steps to configure the debug mode in awx in the container according to the link above. But, unfortunately, I did not see information about how you could bind the development environment (IDE Pycharm as example) to the container so that directly from it you could make your changes in the code and add modules.
Is it possible or awx application must be out of docker container with it's components?

**Comment by ryanpetrello** [comment]
@denis-ovsyannikov AWX doesn't have any form of direct integration with PyCharm (or any other IDE).

**Comment by ghost** [comment]
Way that was discribed allow debug ui-client part (frontend). Is it possible to debug django application in docker container? I understand what awx-ansible do not integrated with pycharm but I think it must be possible way to extend your application with custom modules.
Thank you for any information.

**Comment by ghjm** [comment]
@denis-ovsyannikov It is possible to do this.  The basic steps are:

1. Have the Professional edition of PyCharm.
2. Add a run configuration of type "Python Debug Server."
3. Run the AWX development environment.
4. Get a bash shell Docker as root with `docker exec -it --user 0 tools_awx_1 bash`.
5. Activate the AWX virtualenv with `. /venv/awx/bin/activate`
6. `pip install pydevd-pycharm-<version>` (get the version from your run configuration screen)
7. Edit the code where you want your initial breakpoint and add `import pydevd_pycharm; pydevd_pycharm.settrace('localhost', port=<some-port>, stdoutToServer=True, stderrToServer=True)` (this can also be copied from the run configuration screen)
8. Click the Debug button in PyCharm to start the debug server
9. Run AWX and when it gets to your debug code, it will connect to PyCharm

Note that if you're debugging something within the request/response cycle, you have a limited time available before it will decide to time out.
