### ISSUE TITLE
Workflow Details View

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#5814]
##### ISSUE TYPE
Add workflow details view

##### SUMMARY
https://tower-mockups.testing.ansible.com/patternfly/templates/templates-workflows-detail/

**Comment by unlikelyzero** [comment]
Re-opening for QE

**Comment by dsesami** [comment]
Re: functionality, this works great! Thanks so much.

I've added some style-cleanup for this page in this issue: https://github.com/ansible/awx/issues/6523
