### ISSUE TITLE
Support Prompt on Launch for Workflow Job Template

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#5819]
##### ISSUE TYPE
Some fields in the Workflow Job Template Form need to support Prompt on Launch functionality.  See mock up below.
https://tower-mockups.testing.ansible.com/patternfly/templates/templates-workflows-add/
##### SUMMARY
Current ui supports Prompt on Launch for SCM Branch, Inventory, Variables, and Limit
related to #4967

**Comment by mabashian** [comment]
This issue should probably be worked on in conjunction with #4967

**Comment by mabashian** [comment]
Marking this as blocked until #4967 lands

**Comment by mabashian** [comment]
Once the form work is merged this should be ready to go

**Comment by nixocio** [comment]
See also: https://github.com/ansible/awx/issues/5910

**Comment by dsesami** [comment]
this is good to go and merged 👍
