### ISSUE TITLE
UI refers to creds for projects as SCM Credential but then no such type in Credential Types (is Source Control there)

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#5820]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Different names for the same thing makes it hard to figure out what to do

##### STEPS TO REPRODUCE

"I am making a project. Oh I need SCM Credential. Go to credential create form. Search SCM. sad, no SCM" 

##### EXPECTED RESULTS

Whatever the project says I need to provide, I should be able to find in Credential create form

##### ACTUAL RESULTS

![Screenshot from 2020-02-03 16-09-26](https://user-images.githubusercontent.com/29239279/73691598-a5e23b00-46a0-11ea-9ecc-00d520b9702d.png)
![Screenshot from 2020-02-03 16-08-59](https://user-images.githubusercontent.com/29239279/73691621-b2ff2a00-46a0-11ea-9811-1a404d7852c9.png)

##### ADDITIONAL INFORMATION

want this in ui_next but would be nice in current ui

**Comment by jakemcdermott** [comment]
The solution is just to make the project form say "Source Control Credential" (and not SCM credential) so that it matches the credential form and other places.
