### ISSUE TITLE
Ansible 2.9.4 in AWX?

### ISSUE THREAD

**Issue by MarcusCaepio** [ansible/awx#5827]
Hi all,
on my host system, I already have Ansible 2.9.4 installed.
After writing a playbook with ios_vlans and importing it to AWX, I noticed, that AWX is still running Ansible 2.8.5, where ios_vlans is not implemented. 
When will 2.9.x come to AWX or is there a way to manually update Ansible in AWX?

Cheers,
Marcus

**Comment by shanemcd** [comment]
Hello. The latest version of Ansible will be included when we build new images (the next release of AWX). While the next release is not currently scheduled, I'd imagine we'll put out something in the coming weeks. In the meantime you can either [build the images yourself](https://github.com/ansible/awx/blob/devel/INSTALL.md#official-vs-building-images), use [`custom_venv_dir`](https://github.com/ansible/awx/blob/devel/INSTALL.md#inventory-variables) (for local Docker installs) or [`custom_venvs`](https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md#kubernetes-custom-virtualenvs) (for k8s installs).
