### ISSUE TITLE
Terminate Instance not working

### ISSUE THREAD

**Issue by pavanchelvaraj** [ansible/awx#583]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME

 - API
 
##### SUMMARY

- name: Terminate instances
  hosts: localhost
  connection: local
  tasks:
    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        instance_ids: '{{ ec2.instance_ids }}'

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/root/myplatform/site.yml': line 40, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - name: Terminate instances
      ^ here

The error appears to have been in '/root/myplatform/site.yml': line 40, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - name: Terminate instances
      ^ here

exception type: <class 'ansible.errors.AnsibleParserError'>
exception: no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/root/myplatform/site.yml': line 40, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:
    - name: Terminate instances
      ^ here

##### ENVIRONMENT
ansible 2.4.0.0

* Operating System:
Centos 7

**Comment by pavanchelvaraj** [comment]
---
- name: Create a new Demo EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
      region: ap-southeast-2
      instance_type: t2.micro
      ami: ami-8536d6e7  # Amazon Linux
      keypair: awstestkeypair # pem file name

  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group: launch-wizard-1 # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         exact_count: 1  # default
         count_tag:
            Name: TestPC
         instance_tags:
            Name: TestPC
         vpc_subnet_id: subnet-cdd7f1a9
         assign_public_ip: yes
      register: ec2

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

    **- name: Terminate instances that were previously launched
      ec2:
        region: "{{ region }}"
        instance_type: "{{ instance_type}}"
        state: 'absent'
        instance_ids: '{{ ec2.instance_ids }}'**

**Comment by matburt** [comment]
I'm sorry, we can't help you troubleshoot your ansible playbooks in the AWX bug tracker.

**Comment by pavanchelvaraj** [comment]
Can you please let me know where to post my question.

**Comment by matburt** [comment]
Try on the Ansible mailing list or irc channel: http://docs.ansible.com/ansible/latest/community.html
