### ISSUE TITLE
win_lineinfile does not work from Ansible Tower

### ISSUE THREAD

**Issue by akhilesh-bhople** [ansible/awx#5853]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: Tower 3.5.2
* AWX install method:
* Ansible version:  Ansible 2.8.2
* Operating System: CentOS Linux release 7.6
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

Running win_lineinfile module from a template in Ansible Tower fails to replace the lines in required file in windows, however running the same from ansible cli works as expected.

**Comment by wenottingham** [comment]
Hi, this repo is for bugs in AWX, if you are having issues with Ansible Tower please contact your Red Hat support representative.
