### ISSUE TITLE
$releasever is not set or available on image ansible/awx_task:9.1.1

### ISSUE THREAD

**Issue by Throckmortra** [ansible/awx#5858]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
$releasever is not set or available on image ansible/awx_task:9.1.1

##### ENVIRONMENT
* AWX version: 9.1.1
* AWX install method: docker on linux
* Ansible version:  2.9.3
* Operating System: Amazon Linux 2 
* Web Browser:

##### STEPS TO REPRODUCE

yum update 

##### EXPECTED RESULTS

yum updates successfully 

##### ACTUAL RESULTS

Error: Failed to synchronize cache for repo 'CentOS-AppStream.repo'

##### ADDITIONAL INFORMATION

you can force an update by using sed to replace '$releasever' with '8' in the repo configs. But other tools will break that rely on $releasever being set.

**Comment by Throckmortra** [comment]
output of `python3 -c 'import dnf, pprint; db = dnf.dnf.Base(); pprint.pprint(db.conf.substitutions,width=1)'`

> {'arch': 'x86_64',
 'basearch': 'x86_64',
 'releasever': '8'}

**Comment by ryanpetrello** [comment]
@shanemcd you have any ideas about what's up here?

**Comment by Throckmortra** [comment]
updated to AWX 11 and no longer see this problem.
