### ISSUE TITLE
Job Template Schedule Details

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5859]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Things that should be included:
1) Fields:
    - Name
    - Description
    - Start Date
    - Start Time
    - Local Timezone
    - Repeat Frequency
        - This field is interesting as it should be an aggregation of several different fields.  The expectation here is that this field will describe how frequently the schedule will run and when it will end.  Very similar (if not identical) logic can be found in the old UI for generating [this string](https://user-images.githubusercontent.com/9889020/74182640-6de37680-4c11-11ea-839d-1bdcbf5083fe.png).

    - Occurrences
        - We allow the user to toggle between their local timezone and utc time in the old app.  Whether this is used/necessary is unclear to me at this point.
    - Variables
    - Inventory*
    - SCM Branch*
    - Job Type*
    - Job Tags*
    - Skip Tags*
    - Limit*
    - Diff Mode*
    - Verbosity*
    - Created
    - Last Modified
2) Edit button (rbac permitting)
3) Delete button (rbac permitting)
4) On/Off toggle (rbac permitting - see host details for an example)

*These are fields that override the JT defaults.  They should not be shown if the value is null/empty string.

Link to mockup: https://tower-mockups.testing.ansible.com/patternfly/templates/templates-schedules-detail/

**Comment by dsesami** [comment]
Works like a charm, including prompted fields. The only thing left is formatting the prompted fields header, which is going to be done in https://github.com/ansible/awx/issues/6510.
