### ISSUE TITLE
All input group buttons should be moved to the right side of the text box.

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#5862]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
See the following gif, where I tab through some items on the user page.
![ezgif-7-b9767f55ee9f](https://user-images.githubusercontent.com/19942822/74188484-81e0a580-4c1c-11ea-8fa0-a86d0775a8ed.gif)

When tabbing through, the "reveal password" buttons are encountered before the actual password fields. We'd like to be consistent, and patternfly input groups let us put these buttons on either side of the field. We want to keep the tabbing for accessibility reasons, but all of these buttons attached to text boxes should be on the right side.

Patternfly input group docs: https://www.patternfly.org/v4/documentation/react/components/inputgroup

**Comment by mabashian** [comment]
This could get interesting when we look at cred plugin fields:

<img width="449" alt="Screen Shot 2020-11-16 at 3 22 56 PM" src="https://user-images.githubusercontent.com/9889020/99303925-ab6bd480-281f-11eb-8e2d-2b8013c90fa4.png">

**Comment by mabashian** [comment]
Actually, I'm gonna close this.  After looking at the PF docs and using the tab button there I feel like this is working as expected.
