### ISSUE TITLE
Job Template Add Schedule Form

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5864]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Fields:

1) Name
2) Description (we don't show this in the old UI and I'm not sure why)
3) Start Date (date picker - as far as I know we don't have a component like this in the app currently)
4) Start Time (Three separate number inputs HH24:MM:SS)
5) Local Time Zone (Options for this dropdown come from `/api/v2/schedules/zoneinfo/`)
6) Repeat Frequency
    - None (Run Once)
    - Minute
    - Hour
    - Day
    - Week
    - Month

The following fields are part of a subform that's only shown when the Repeat Frequency is *not* None (Run Once).  This is a little complicated though.  Reference the existing app for more complete examples.

7) Every
    - This field is always shown as long as the Repeat Frequency is *not* None.  The label matches up with the Repeat Frequency (Minute, Hour, Day, etc) and is a number input.
8) On Days
    - This field is only shown when the Repeat Frequency is Week.
    - This field allows the user to select any of the seven days of the week (not limited to a single day).
9) End
    - This field is always shown as long as the Repeat Frequency is *not* None.  The options are Never, After, and On Date.
10) Occurrences
    - This field is only shown if End is After
    - Number Input
11) End Date
    - This field is only shown if End is On Date (see Start Date)
12) End Time (HH24:MM:SS)
    - This field is only shown if End is On Date (see Start Time)
13) On Day*
    - This field is only shown if Repeat Frequency is Month
    - This is a number input that lets the user select the day of the month to run the scheduled job
14) On The*
    - This field is only shown if Repeat Frequency is Month
    - This field lets the user select things like `First Monday`
    - This was achieved in the old app with two separate dropdowns

* 13 and 14 can't both be set at the same time.  We should work with Taufique to streamline the UX here because I think it's a little clunky.

** Ignore all the promptable fields that could exist in this form including Extra Vars, Inventory, SCM Branch, Job Type, Job Tags, Skip Tags, Limit, Diff Mode, and Verbosity.  Those fields will be handled when we hook up prompting in the scheduler.

Link to mockups: https://tower-mockups.testing.ansible.com/patternfly/templates/templates-schedules-add/

**Comment by dsesami** [comment]
This is looking great. I've linked it so that the PR will close the issue on merge.
