### ISSUE TITLE
Job Template Edit Schedule Form

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5865]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
See #5864 for almost all of the details.

Link to mockups: https://tower-mockups.testing.ansible.com/patternfly/templates/templates-schedules-edit/

**Comment by dsesami** [comment]
@mabashian as part of this work, could you add an `Edit` button to the Details view of schedules? It feels like we should be able to visit the form from there.

**Comment by dsesami** [comment]
Superseding issues:

- Adding an edit/delete button to the details page itself is covered by #6171
- @mabashian and I agreed on adding a small piece of text to the form for grammar purposes in this issue: #6718 

Everything else looks solid.

**Comment by dsesami** [comment]
Closed by mistake; should be closed when https://github.com/ansible/awx/pull/6560 merges
