### ISSUE TITLE
RFE "Related" Job Templates tab for Inventories and Credentials

### ISSUE THREAD

**Issue by gamuniz** [ansible/awx#5867]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

It would be beneficial to see what job templates are using a specific inventory or credential. This could be used to gauge impact of deleting specific objects.

Add the job templates like in projects 
![image](https://user-images.githubusercontent.com/18033113/74191447-95423f80-4c21-11ea-8ec8-0f2e45ab9fab.png)

**Comment by mabashian** [comment]
It'll be really easy for us to do this in UI Next

**Comment by jakemcdermott** [comment]
Tags for these items can be easily a added to the templates list in ui_next. As of right now, a user will not be unaware of the potential impact of deleting a credential or inventory as we show warning prompts with this information prior to deletion:

![Screenshot from 2020-02-11 11-34-09](https://user-images.githubusercontent.com/9753817/74257327-aa22df80-4cc2-11ea-9041-fec5d372e6c9.png)
![Screenshot from 2020-02-11 11-35-29](https://user-images.githubusercontent.com/9753817/74257328-aa22df80-4cc2-11ea-9a50-aa7c96d2cf75.png)

Also, we _already_ show this information in the old UI as long as you are in expanded list mode:

![Screenshot from 2020-02-11 11-38-34](https://user-images.githubusercontent.com/9753817/74257684-2d443580-4cc3-11ea-9c87-5fa4ec5fdf57.png)

**Comment by unlikelyzero** [comment]
Added to meta issuehttps://github.com/ansible/awx/issues/8885

**Comment by tiagodread** [comment]
Closing this issue, since this was worked and added via https://github.com/ansible/awx/issues/5546 and https://github.com/ansible/awx/pull/9345

**Comment by tiagodread** [comment]
Reopening this issue since this was not implemented yet in fact. We do show the resources associated before deleting in a modal but  we don't have Job template tab for Credentials and Inventories yet.

**Comment by InnocentK** [comment]
Note: QE will need to add new E2E tests to cover this scenario

**Comment by InnocentK** [comment]
This has now been resolved
