### ISSUE TITLE
How to use ui_next in AWX

### ISSUE THREAD

**Issue by craph** [ansible/awx#5872]
Hello,

I'm using AWX 9.1.1 and I would like to know how to use the new UI.

How can I switch from the current UI to the new one ?

Thank you very much.

Best regards,

**Comment by ryanpetrello** [comment]
Hey @craph,

The new UI is still very much under active development, so I think you'll find some notable gaps in functionality.  That said, if you want give it a test drive, it really is coming along.

@jakemcdermott @mabashian do one of you have instructions available on how to do this?

**Comment by ryanpetrello** [comment]
(closing because this isn't really a bug, more a question, but we can continue the conversation here)

**Comment by craph** [comment]
@ryanpetrello thank you for the update.

Yes I want to do some test :)
