### ISSUE TITLE
Support all default credential types in credential forms

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5879]
##### SUMMARY
https://github.com/ansible/awx/issues/5274 and https://github.com/ansible/awx/issues/5275 are covering adding support for machine and scm credential types.

**Feel free to break this work up into pieces.  Some of these subforms are more complicated than others**

As noted in #5274 the intention at this time is to ignore credential plugin support (lookups on many of the fields).  That work will come later.  This issue is meant to track adding support for the rest of the default credential types:

- [ ] **Amazon Web Services**

<img width="1520" alt="Screen Shot 2020-02-11 at 9 51 36 AM" src="https://user-images.githubusercontent.com/9889020/74247497-25c96000-4cb4-11ea-8f26-8225795d6116.png">

- [ ] **Ansible Tower**

<img width="1528" alt="Screen Shot 2020-02-11 at 9 52 17 AM" src="https://user-images.githubusercontent.com/9889020/74247556-3e397a80-4cb4-11ea-8ace-0ccc6ae4e197.png">

- [ ] **CyberArk AIM Central Credential Provider Lookup**

<img width="1494" alt="Screen Shot 2020-02-11 at 9 53 42 AM" src="https://user-images.githubusercontent.com/9889020/74247670-6aed9200-4cb4-11ea-9e04-1528b548d212.png">

- [ ] **CyberArk Conjur Secret Lookup**

<img width="1501" alt="Screen Shot 2020-02-11 at 9 54 11 AM" src="https://user-images.githubusercontent.com/9889020/74247713-7d67cb80-4cb4-11ea-869c-cdf7de32517f.png">

- [ ] **GitHub Personal Access Token**

<img width="1517" alt="Screen Shot 2020-02-11 at 9 54 44 AM" src="https://user-images.githubusercontent.com/9889020/74247755-907a9b80-4cb4-11ea-901c-a20311024f9e.png">

- [ ] **GitLab Personal Access Token**

<img width="1518" alt="Screen Shot 2020-02-11 at 9 55 13 AM" src="https://user-images.githubusercontent.com/9889020/74247783-a0927b00-4cb4-11ea-83b5-3f91a54a44ce.png">

- [ ] **Google Compute Engine**

<img width="1485" alt="Screen Shot 2020-02-11 at 9 56 03 AM" src="https://user-images.githubusercontent.com/9889020/74247882-c15ad080-4cb4-11ea-8a20-4024f3ca20e7.png">

- [ ] **HashiCorp Vault Secret Lookup**

<img width="1510" alt="Screen Shot 2020-02-11 at 9 57 51 AM" src="https://user-images.githubusercontent.com/9889020/74248047-fff08b00-4cb4-11ea-8412-9511fb338db4.png">

- [ ] **HashiCorp Vault Signed SSH**

<img width="1509" alt="Screen Shot 2020-02-11 at 9 58 25 AM" src="https://user-images.githubusercontent.com/9889020/74248112-1c8cc300-4cb5-11ea-907d-c784633e3de3.png">

- [ ] **Insights**

<img width="1506" alt="Screen Shot 2020-02-11 at 9 59 13 AM" src="https://user-images.githubusercontent.com/9889020/74248183-30d0c000-4cb5-11ea-9424-e8dfef9b7296.png">

- [ ] **Microsoft Azure Key Vault**

<img width="1530" alt="Screen Shot 2020-02-11 at 9 59 44 AM" src="https://user-images.githubusercontent.com/9889020/74248253-49d97100-4cb5-11ea-939a-63bc3dd136f2.png">

- [ ] **Microsoft Azure Resource Manager**

<img width="1496" alt="Screen Shot 2020-02-11 at 10 00 51 AM" src="https://user-images.githubusercontent.com/9889020/74248322-6a093000-4cb5-11ea-969e-29536e018bbe.png">

- [ ] **Network**

<img width="1523" alt="Screen Shot 2020-02-11 at 10 01 17 AM" src="https://user-images.githubusercontent.com/9889020/74248372-7e4d2d00-4cb5-11ea-9156-19d912bb8671.png">

- [ ] **OpenShift or Kubernetes API Bearer Token**

<img width="1519" alt="Screen Shot 2020-02-11 at 10 01 49 AM" src="https://user-images.githubusercontent.com/9889020/74248424-8efda300-4cb5-11ea-9bef-6657884c0cbc.png">

- [ ] **OpenStack**

<img width="1501" alt="Screen Shot 2020-02-11 at 10 02 19 AM" src="https://user-images.githubusercontent.com/9889020/74248474-a0df4600-4cb5-11ea-9a1a-52fa14dc6b21.png">

- [ ] **Red Hat CloudForms**

<img width="1494" alt="Screen Shot 2020-02-11 at 10 02 51 AM" src="https://user-images.githubusercontent.com/9889020/74248510-b18fbc00-4cb5-11ea-879e-c4c13c70d4d6.png">

- [ ] **Red Hat Satellite 6**

<img width="1523" alt="Screen Shot 2020-02-11 at 10 03 30 AM" src="https://user-images.githubusercontent.com/9889020/74248571-ca986d00-4cb5-11ea-8189-bef83713b16c.png">

- [ ] **Red Hat Virtualization**

<img width="1516" alt="Screen Shot 2020-02-11 at 10 04 05 AM" src="https://user-images.githubusercontent.com/9889020/74248625-dedc6a00-4cb5-11ea-99ed-1fe420aa561c.png">

- [ ] **Vault**

<img width="1512" alt="Screen Shot 2020-02-11 at 10 04 36 AM" src="https://user-images.githubusercontent.com/9889020/74248680-f287d080-4cb5-11ea-8d0a-d4af704a4cef.png">

- [ ] **VMware vCenter**

<img width="1478" alt="Screen Shot 2020-02-11 at 10 05 08 AM" src="https://user-images.githubusercontent.com/9889020/74248722-03d0dd00-4cb6-11ea-89e8-917707a0320b.png">

**Comment by jakemcdermott** [comment]
note: remove blocked from https://github.com/ansible/awx/issues/5880 when this is finished

**Comment by mabashian** [comment]
After #5274 and #5275 are done we want to transition away from building static subforms for credentials since we'll need to support both default and custom credential types.  Custom credential types _must_ be generated based on the response from `/api/v2/credential_types/:id`.  Inside that response there is an `inputs` key that looks something like:

```
    "inputs": {
        "fields": [
            {
                "id": "username",
                "type": "string",
                "label": "Username"
            },
            {
                "id": "password",
                "type": "string",
                "label": "Password",
                "secret": true
            }
        ],
        "required": [
            "username",
            "password"
        ]
    },
```

Based on this JSON blob, we'll need to generate fields for the form.  Instead of having the default credential types (machine, aws, gce, etc) be defined statically, all of the credential forms should be generated dynamically by inspecting the response from the aforementioned request.

**Comment by mabashian** [comment]
I'm going to work on the GCE portion of the form first.  After that we'll probably want to focus on supporting the credential plugins before moving on to some sort of dynamic generator.

**Comment by appuk** [comment]
verified the GCE portion of the form along with field validation associated with it, everything works as expected 👍 
hence removing the issue from needs_test and moving to needs_devel for other credential types
