### ISSUE TITLE
Add new API field for searchable items

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#588]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

The list of searchable fields in the UI (in the search 'KEY') is driven off the OPTIONS list for the API, plus `related_search` fields.

However, not all fields returned in OPTIONS are searchable, and some that aren't listed in OPTIONS are.

As we can't change the OPTIONS request (as it's used for GET/POST validation by the UI, etc), we should introduce a new concept of 'searchable fields' in the API that the UI can use to populate the search key.

##### STEPS TO REPRODUCE

Open search key.
Attempt to use all items listed.

**Comment by AlanCoding** [comment]
@mabashian pointed out to me that this is already resolved.

Fields returned in the GET list contain a field `filterable`, which functions exactly as what is described here. This issue seems to have just been lost in the development of that.
