### ISSUE TITLE
Credential Plugins - external credential lookup and form prompt

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#5881]
##### SUMMARY
With credential plugins, linking an input field to an external source involves a prompt with two steps. 

- The prompt is opened by a specific "lookup" button on the individual input field, see https://github.com/ansible/awx/issues/5880
- The first step of the prompt is for selecting the _external credential_  to use as the input source for the field:
<img width="1435" alt="cred_plugin_lookup1" src="https://user-images.githubusercontent.com/9753817/74250718-05e86b00-4cb9-11ea-9619-15af8507c05a.png">

- The second step of the prompt is an auto-generated form for providing metadata for the external secret value:
<img width="1426" alt="cred_plugin_lookup2" src="https://user-images.githubusercontent.com/9753817/74250854-3d571780-4cb9-11ea-85aa-52b7f58bc7c0.png">

do first: https://github.com/ansible/awx/issues/5880

**Comment by unlikelyzero** [comment]
Assigning this to myself to test

**Comment by dsesami** [comment]
Moving assignment because I'm already working on this with Mike's PR here: https://github.com/ansible/awx/pull/7258

**Comment by dsesami** [comment]
@mabashian we can't close this one out until the test button is implemented, yes?

**Comment by mabashian** [comment]
Yea we can close this when #7339 is done

**Comment by dsesami** [comment]
Removing needs_test because this is in limbo until #7339 is done. we'll move it back to needs_test afterwards.

**Comment by mabashian** [comment]
@unlikelyzero If we close #7339, I think we can close this one?

**Comment by unlikelyzero** [comment]
covered in credentials-mock.spec.js
