### ISSUE TITLE
Project Schedules Related Tab

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5888]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
<img width="1680" alt="Screen Shot 2020-02-11 at 10 52 05 AM" src="https://user-images.githubusercontent.com/9889020/74253057-91afc680-4cbc-11ea-88a3-8045e0fc65ac.png">

We'll need to support a few different things here:

1) The schedule list itself (should be able to re-use #4959 with a different endpoint)
2) Add schedule form (should be able to re-use #5864 with a different endpoint)
3) Edit schedule form (should be able to re-use #5865 with a different endpoint)
4) Schedule details view (should be able to re-use #5859 with a different endpoint)

Going to mark this as blocked until #4959, #5859, #5864, and #5865 are done.

**Comment by jlmitch5** [comment]
List has been added, we'll need to add add/edit once that is done.

**Comment by dsesami** [comment]
The issues this depends on have been merged and the differing endpoint works; follow up issues are in #6708 #6171 #6718
