### ISSUE TITLE
Unable to build dev environment

### ISSUE THREAD

**Issue by craph** [ansible/awx#5889]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

I'm unable to build the dev environment (following this documentation : https://github.com/ansible/awx/blob/devel/CONTRIBUTING.md#build-the-base-image to be able to debug and contribute to AWX project.

##### ENVIRONMENT
* AWX version: 9.1.1
* AWX install method: docker on windows
* Ansible version:  X.Y.Z
* Operating System: Windows 10
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Install docker for windows

1. Clone AWX project

1. Follow the documentation : https://github.com/ansible/awx/blob/devel/CONTRIBUTING.md#build-the-base-image and https://github.com/ansible/awx/blob/devel/CONTRIBUTING.md#build-the-base-image

1. make docker-compose-build (inside mobaxterm with make plugin installed)

##### EXPECTED RESULTS

I want to be able to build the AWX dev project

##### ACTUAL RESULTS

```
# Same effect as using --system-site-packages flag on venv creation
rm /venv/ansible/lib/python3.6/no-global-site-packages.txt
rm: cannot remove '/venv/ansible/lib/python3.6/no-global-site-packages.txt': No such file or directory
make: *** [Makefile:190: requirements_ansible_py3] Error 1
The command '/bin/sh -c cd /tmp && VENV_BASE="/venv" make requirements_dev' returned a non-zero code: 2
make: *** [Makefile:682: awx-devel-build] Error 2
```

##### ADDITIONAL INFORMATION

I'm unable to find the file where is specified the ansible version used in AWX

**Comment by ryanpetrello** [comment]
@craph try grabbing the latest `devel` - what you're encountering is the result of a bug in the latest `virtualenv` Python package, which I just merged a fix for yesterday:

https://github.com/ansible/awx/pull/5868
