### ISSUE TITLE
JT Completed Jobs List

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5890]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
<img width="1490" alt="Screen Shot 2020-02-11 at 11 10 36 AM" src="https://user-images.githubusercontent.com/9889020/74254979-3a5f2580-4cbf-11ea-9b57-b04834290154.png">

This will share quite a bit with the component used on `/#/jobs` with a few exceptions.

1) The data comes from a different endpoint: `/api/v2/job_templates/:id/completed_jobs`
2) We don't need to show the type column (type will always be `Job`)

Columns:

1) Status/Name of job.  Links to `/#/jobs/:id`
2) Finish time of job
3) Relaunch button

The user should also be able to delete jobs from this list (rbac restricted)

Link to mockup: https://tower-mockups.testing.ansible.com/patternfly/templates/templates-completed/

**Comment by dsesami** [comment]
Completed Jobs list works great. Sorting, etc. etc. RBAC also appears to behave the way we want it to. :+1:
