### ISSUE TITLE
JT Survey List

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5895]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
** Note that we should build a lot of these components in a generic way.  Workflow job templates have the exact same related tab.**

On initial load, the user should see an empty list.  The list will eventually represent the survey questions themselves.

<img width="1459" alt="Screen Shot 2020-02-11 at 11 44 03 AM" src="https://user-images.githubusercontent.com/9889020/74258350-2bc73d00-4cc4-11ea-85c8-52efa7e1782b.png">

1) Select all checkbox.  This handles selecting/deselecting all the rows.
2) On/Off Toggle.  This field corresponds to the `survey_enabled` field on the JT.  In the old app we have this toggled to `On` when the user comes in to add their first survey question.  Since we're going to be interacting with the api in real time (rather than on a submit) this UX could be interesting.  I'd recommend talking through this with Bill and Taufique.
3) Delete button.  Only enabled when one of the survey questions is selected.  This button should be rbac restricted (system auditors for example can't delete survey questions).
4) Add button.  Clicking this button will take the user to a stand-alone survey form.  This button should be rbac restricted (system auditors for example can't create survey questions).

List row columns:

1) Re-ordering the survey questions is a thing.  In the past, we've let users drag and drop survey questions to a new location.  This has been slightly complicated and buggy in the past.  As a first pass I think we should use simple up/down arrows to allow users to move questions up and down in the queue rather than supporting drag/drop.
2) Checkbox to select row (for deletion)
3) Name of survey question (this should not be a link)
4) Type of question (password, input, textarea, etc)
5) Default value - This is probably worth a conversation with Bill and Taufique.  Some survey questions could have tremendously long default values.  What do we do in that case?
6) Edit button - clicking this button should take the user to the survey question form with all the values filled in.

Link to mockups: https://tower-mockups.testing.ansible.com/patternfly/templates/templates-survey/

**Comment by dsesami** [comment]
Some feedback:

- Lack of column labeling is really hurting here. There is no tooltip or intuitive information on the survey page. If we don't address that in this issue, we need to tackle it in a more systemic-manner.
- ~We do not have information about the name of the variable itself introduced.~ ignore this, it wasn't like this in the old UI either
- We do not have information about whether or not the survey item is required. 
- We do not have a way to handle character limits -- long pieces of text in all of the form fields break the view and don't wrap.
- The select-all button should be re-aligned with the other select buttons, if possible:

![Screenshot from 2020-03-18 14-21-06](https://user-images.githubusercontent.com/19942822/76993755-be8e7380-6923-11ea-9eff-d5811cfdd9dd.png)

@mabashian @AlexSCorey could use your feedback on these items.

**Comment by AlexSCorey** [comment]
@dsesami I agree with the need for headings and with the select all button alignment.  I meant to create a "clean up" issue for the survey that would take all of this kind of feedback and address it at once, assuming doing so made sense.  I think we should also get insight from @trahman73 regarding how to show required items and if we want to show the headings?  Maybe that stuff will be shown in the preview?

https://github.com/ansible/awx/issues/6333

**Comment by dsesami** [comment]
after speaking with @AlexSCorey we'll move most of the issues to the other ticket. For now, I'll move this back to needs_devel so he can tackle the wrapping issue.

**Comment by AlexSCorey** [comment]
In speak with @trahman73 @dsesami we decided that the required item icon will not be rendered on the list but will be rendered in the preview.
