### ISSUE TITLE
search_path for templates not including dependent roles

### ISSUE THREAD

**Issue by dansou901** [ansible/awx#5896]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I've setup two roles. Role a contains just the templates, role b contains tasks. Role a is a dependency for role b. When I run role b from a playbook of an awx project, I except that a task from inside role b can access templates defined in role a without having to define the path to the template. According to official ansible documentation, this has to work (see https://docs.ansible.com/ansible/2.8/user_guide/playbook_pathing.html). However, in recent awx, it just throws an error that the template couldn't be found.

##### ENVIRONMENT
* AWX version: 9.1.1
* AWX install method: docker on linux (docker-compose)
* Ansible version:  2.8.5
* Operating System: Ubuntu 18.04
* Web Browser: Google Chrome 79.0.3945.130

##### STEPS TO REPRODUCE

Create role a which has the folders meta, tasks and templates. In meta, there is a default main.yml which I use for all my roles (Example below for role b). In tasks, the following main.yml is included:
```yml
- name: debug that role is being executed
  debug:
    msg: "Role a is being executed"
```
In templates, the following template test.j2 is included:
```yml
echo {{ foo }} {{ bar }}
```
Then, create role b which contains defaults, meta and tasks. Defaults contains a main.yml with:
```yml
foo: footext
bar: bartext
```
Meta contains a main.yml with:
```yml
---
galaxy_info:
  author: <email address>
  description: debug role for github
  company: <company>
  license: "license (BSD, MIT)"
  min_ansible_version: 2.8
  platforms:
    - name: Ubuntu
      versions:
        - bionic
  categories:
    - system
dependencies:
  - a
```
Note the dependencies list at the end.
Tasks contains the following main.yml:
```yml
- name: template out test.txt
  template:
    src: test.j2
    dest: test.txt
```
At last, create an awx project which contains a requirements.yml under roles with the git sources in it (as this is trivial, I won't include it here) and a playbook.yml which looks like this:
```yml
- name: debug template search paths
  hosts: all
  remote_user: root
  roles:
    - b
```
Now, add that awx project to your awx instance, create a job template which runs playbook.yml and launch it.

##### EXPECTED RESULTS

Task from role a should be executed first, then the template from role a should be found correctly by role b and written out to the target machine.

##### ACTUAL RESULTS

```
PLAY [debug template search paths] *********************************************
TASK [Gathering Facts] *********************************************************
ok: [redacted]
TASK [a : debug that role is being executed] ***********************************
ok: [redacted] => {
    "msg": "Role a is being executed"
}
TASK [b : template out test.txt] ***********************************************
fatal: [redacted]: FAILED! => {"changed": false, "msg": "Could not find or access 'test.j2'\nSearched in:\n\t/tmp/awx_8201_ivl_qi0w/requirements_roles/b/templates/test.j2\n\t/tmp/awx_8201_ivl_qi0w    /requirements_roles/b/test.j2\n\t/tmp/awx_8201_ivl_qi0w/requirements_roles/b/tasks/templates    /test.j2\n\t/tmp/awx_8201_ivl_qi0w/requirements_roles/b/tasks/test.j2\n\t/tmp/awx_8201_ivl_qi0w   /project/templates/test.j2\n\t/tmp/awx_8201_ivl_qi0w/project/test.j2 on the Ansible Controller.\nIf    you are using a module and expect the file to exist on the remote, see the remote_src option"}
```

As a workaround, I can point role b directly to the template from role a defining src as ../requirements_roles/a/templates/test.j2 but that's not very nice. Would be good to have this working as advertised. Thanks!
Regards,
dansou901

**Comment by dansou901** [comment]
This is still happening in AWX 9.2.0 with Ansible 2.9.3.

**Comment by ryanpetrello** [comment]
@AlanCoding you have any ideas on this one?

**Comment by AlanCoding** [comment]
> At last, create an awx project which contains a requirements.yml under roles with the git sources in it (as this is trivial, I won't include it here)

There are still multiple things you could be doing with this. My reading is that it is pulling role `a` as a dependency of role `b`, even as role `b` is sourced from git and not Galaxy itself.

Does the job you're running have the fact cache enabled? Can you give `job_env` as reported in `<host>/api/v2/jobs/N/`?

**Comment by dansou901** [comment]
Just to clarify: I'm not using Galaxy at all, all my roles are sourced from my private GitLab server, which is working fine otherwise. Fact cache is disabled (use_fact_cache=false), job_env is:
```json
    "job_env": {
        "LC_ALL": "en_US.UTF-8",
        "LANG": "en_US.UTF-8",
        "HOSTNAME": "awx",
        "PWD": "/home/awx",
        "HOME": "/var/lib/awx",
        "affinity:container": "=94cbabda470ba64770dcdb5915943b67a06745b7c3cf4ad2a185131e2388774a",
        "SHLVL": "2",
        "LANGUAGE": "en_US.UTF-8",
        "PATH": "/var/lib/awx/venv/ansible/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "_": "/usr/local/bin/supervisord",
        "SUPERVISOR_ENABLED": "1",
        "SUPERVISOR_SERVER_URL": "unix:///tmp/supervisor.sock",
        "SUPERVISOR_PROCESS_NAME": "dispatcher",
        "SUPERVISOR_GROUP_NAME": "tower-processes",
        "LC_CTYPE": "en_US.UTF-8",
        "DJANGO_SETTINGS_MODULE": "awx.settings.production",
        "DJANGO_LIVE_TEST_SERVER_ADDRESS": "localhost:9013-9199",
        "TZ": "UTC",
        "ANSIBLE_FACT_CACHE_TIMEOUT": "0",
        "ANSIBLE_FORCE_COLOR": "True",
        "ANSIBLE_HOST_KEY_CHECKING": "False",
        "ANSIBLE_INVENTORY_UNPARSED_FAILED": "True",
        "ANSIBLE_PARAMIKO_RECORD_HOST_KEYS": "False",
        "ANSIBLE_VENV_PATH": "/var/lib/awx/venv/ansible",
        "AWX_PRIVATE_DATA_DIR": "/tmp/awx_8253_ghupjwj0",
        "VIRTUAL_ENV": "/var/lib/awx/venv/ansible",
        "PYTHONPATH": "/var/lib/awx/venv/ansible/lib/python3.6/site-packages:/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/lib:",
        "JOB_ID": "8253",
        "INVENTORY_ID": "43",
        "PROJECT_REVISION": "cb3ac205015b24165bfa6a10ab59ad5975da7542",
        "ANSIBLE_RETRY_FILES_ENABLED": "False",
        "MAX_EVENT_RES": "700000",
        "ANSIBLE_CALLBACK_PLUGINS": "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/plugins/callback",
        "AWX_HOST": "https://towerhost",
        "ANSIBLE_SSH_CONTROL_PATH_DIR": "/tmp/awx_8253_ghupjwj0/cp",
        "ANSIBLE_COLLECTIONS_PATHS": "/tmp/awx_8253_ghupjwj0/requirements_collections:~/.ansible/collections:/usr/share/ansible/collections",
        "ANSIBLE_ROLES_PATH": "/tmp/awx_8253_ghupjwj0/requirements_roles:~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles",
        "ANSIBLE_STDOUT_CALLBACK": "awx_display",
        "AWX_ISOLATED_DATA_DIR": "/tmp/awx_8253_ghupjwj0/artifacts/8253",
        "RUNNER_OMIT_EVENTS": "False",
        "RUNNER_ONLY_FAILED_EVENTS": "False"
    }
```
I hope that helps you finding the root cause.
Regards,
dansou901

**Comment by AlanCoding** [comment]
Thanks, that disproved the only theory I had, but that's still helpful.

For cases with git-based roles, I really would like to see the structure of `roles/requirements.yml`, and in this case, I would like to know if the role `a` is listed there.

**Comment by dansou901** [comment]
It's looking like this:
```yaml
---
- name: a
  scm: git
  src: git@<gitlaburl>:path/to/a.git
  version: master
- name: b
  scm: git
  src: git@<gitlaburl>:path/to/b.git
  version: master
```
As you can see, role a is listed there.

**Comment by dansou901** [comment]
In addition to that, before you ask: I'm using ssh based git cloning with an SCM Key without passphrase which is configured as deploy key in all Ansible related git repositories.

**Comment by dansou901** [comment]
Bug is still present in 9.3.0

**Comment by dansou901** [comment]
Bump! Still present in 14.1.0

**Comment by dansou901** [comment]
Still present in 15.0.0

**Comment by AlanCoding** [comment]
We have tried to build out test cases for roles & collections from SCM. This is the closest that we have so far:

https://github.com/ansible/test-playbooks/pull/146/files

It makes sense to me that your requirements file includes both `a` and `b`, even though ordinarily you'd only have to provide `b` if they were both on Galaxy, because it would pull in its dependencies. But being from source control... it does not know where to get the dependencies from.

That test case can presumably be built out to replicate the situation you have here. Instead of referencing 1 role, we could create 2 branches, 1 for each of the roles, put them both in the requirements file, have 1 as the dependency as the other, and have 1 reference a template from the other. Specifically, the dependency chain you're looking at is `b->a` right? So the template task is in `b` tasks, referencing a template from `a`.

If this building out of the test case is done, I am not highly convinced that it would result in an AWX issue as opposed to an Ansible issue. If those test branches are made, then the bug can be tried and tested _completely locally_. The point where it is an AWX bug is where it works locally, but does not work in AWX.

**Comment by dansou901** [comment]
That makes sense. Testing this with two different branches in the test playbooks should replicate the issue I'm having right now.
However, I'm not completely sure if I will still need this in the future. I already set up a pulp environment with enabled galaxy plugin which should be able to store all my roles and projects and as I saw in the changelog, you have already improved the handling of custom galaxy endpoints. So maybe my use case will be solved when I have implemented this in my environnment. But it would be a good idea to have the option of using dependent roles also when they are fetched from source control.

**Comment by dansou901** [comment]
This can be closed now. I've switched to using collections and there I have a role in a collection for all of my templates. This role contains the templates and a task to template out the templates. In other collections / roles this template role can then be called with respective variable declaration (include_role with {{ template }} and {{ destination }}). The vars template and destination are then evaluated in the template role which then writes the desired end product. This way I can call the template files directly from everywhere and don't need to put paths in front of it. Just putting this here in case some googler finds it.
