### ISSUE TITLE
JT Survey Add Form

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5899]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Fields:

1) Question (mockup says Name but this is the field where the user will fill in the actual question text).
2) Description
3) Variable Name
4) Answer Type (this is a dropdown with the following options: Text, Textarea, Password, Multiple Choice (single select), Multiple Choice (multiple select), Integer, Float).

The following fields are shown based on the Answer Type

5) Minimum Length (integer > 0).  This field is only shown when Answer Type is Text, Textarea, or Password.
6) Maximum Length (integer > min length).  This field is only shown when Answer Type is Text, Textarea, or Password.
7) Multiple Choice Options (textarea - users must enter one option per line).  This field is only shown when Answer Type is Multiple Choice (single select) or Multiple Choice (multiple select).
8) Minimum (Can be negative.  Could be float or integer depending on Answer Type).  This field is only shown when Answer Type is Float or Integer.
9) Maximum (Can be negative.  Greater than Minimum.  Could be float or integer depending on Answer Type).  This field is only shown when Answer Type is Float or Integer.
10) Default Value (This field is shown for all Answer Types but the _type_ of field is different based that dropdown.  For example, it's a textarea when Answer Type is textarea).
11) Options - Required Question.  This checkbox denotes whether the question is required or not.  It should be checked by default on the Add form.

Clicking the save button should automatically POST to the survey_spec endpoint and add the survey question.

Link to mockup: https://tower-mockups.testing.ansible.com/patternfly/templates/templates-survey-add/

**Comment by dsesami** [comment]
See https://github.com/ansible/awx/issues/5900#issuecomment-605008285

**Comment by dsesami** [comment]
https://github.com/ansible/awx/issues/6464 handles final validation on the multiple choice fields. Closing this out.
