### ISSUE TITLE
UX enhancements of side-navigation

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#590]
Based on some internal discussions between Tower UX and engineering, a number of ux enhancements have been proposed for the new side-navigation.

- Default to the expanded (rather than collapsed) navigation.  From day-to-day use of Tower, it's become clear to several of the Tower engineers that referencing the names of the resources is necessary to accurately and quickly navigate across AWX's many routes.
- Add labels to the various "sections" of nav items.  This should help to further contextualize the types of actions a user would be interested in, with the goal of helping to simplify the experience of using AWX.  While there are a lot of routes within the navigation structure, the actual behaviors are pretty simple when considered in terms of what the user is trying to do.

  - view jobs (i.e. Ansible runs) and visualize other things done in AWX
  - update and change resources involved in running jobs
  - update and change access and user roles
  - manage Tower itself

Hopefully, Labeling similar actions helps make that clearer.
- Prioritize/order navigation based on use within sections.  Certain routes are used more often than others when considering typical use cases.  While separating routes into their sections helps to improve and simplify the UX of navigating around AWX (and we're considering this as the priority at this time), reordering the items within a particular section to have more often used routes at the top should help make things easier for those users who use Tower often.

Here's a mockup that shows these enhancements:

<img width="110" alt="screen shot 2017-11-06 at 5 28 04 pm" src="https://user-images.githubusercontent.com/1342624/32467244-e6bafffe-c317-11e7-9d1a-e8f5f6e30ba7.png">

**Comment by wenottingham** [comment]
@jlmitch5 can this be closed?

**Comment by jlmitch5** [comment]
additional changes:

<img width="721" alt="screen shot 2018-04-05 at 10 39 16 am" src="https://user-images.githubusercontent.com/1342624/38372780-a01daeea-38bd-11e8-8869-283eb24540f0.png">

**Comment by jlmitch5** [comment]
https://github.com/ansible/awx/issues/590

**Comment by jlmitch5** [comment]
also #1331

**Comment by jaredevantabor** [comment]
this is fixed in devel.
