### ISSUE TITLE
JT Survey Edit Form

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5900]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
See https://github.com/ansible/awx/issues/5899 for most of the details.

As noted in https://github.com/ansible/awx/issues/5899 form submission here should directly interact with the survey_spec endpoint updating the question.

**Comment by dsesami** [comment]
@keithjgrant both add and edit forms need some way of clarifying how to format single-select and multi-select options. It is trivial to create modal-overlay 400 errors with the input textbox given, and these 400 errors do not provide any useful information to the end user.

**Comment by keithjgrant** [comment]
@dsesami I was kinda hoping to circle back at some point and make a more intelligent input than just a vanilla textarea, but yeah I agree there needs to be better help text at a minimum

**Comment by dsesami** [comment]
Moving the work for the intelligent input / help text for multiple choice options to https://github.com/ansible/awx/issues/6464. Closing this out.
