### ISSUE TITLE
Add support for surveys on WFJT

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5901]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

The hope is that we've built reusable components ^^ that can be dropped in on the WFJT survey related tab.

The only difference between these two areas is the endpoint that we'll be interacting with.

**Comment by dsesami** [comment]
QE work for this is pending completion of #6333

**Comment by dsesami** [comment]
@AlexSCorey we can put this back in needs_test once https://github.com/ansible/awx/pull/6562 merges.

**Comment by dsesami** [comment]
Cleared this out when I reviewed #6562 . Thanks for all the work on this.
