### ISSUE TITLE
WFJT Access Related Tab

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5902]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Hook it up, should be like all the other access tabs.  See https://github.com/ansible/awx/blob/devel/awx/ui_next/src/screens/Template/Template.jsx#L180 as an example.  The only difference should be that we need to pass in the workflow job template api instance.

**Comment by dsesami** [comment]
This is looking really good. Closing this out.
