### ISSUE TITLE
WFJT Completed Jobs Related Tab

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5903]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
See https://github.com/ansible/awx/issues/5892 and https://github.com/ansible/awx/issues/5890.

Same thing here except that the endpoint we interact with will be `/api/v2/workflow_job_templates/:id/completed_jobs`

**Comment by dsesami** [comment]
This looks great -- no visible issues. Closing it out.
