### ISSUE TITLE
WFJT Notifications Related Tab

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5904]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Hook it up.  https://github.com/ansible/awx/blob/devel/awx/ui_next/src/screens/Organization/Organization.jsx#L205 as reference.  Will need to pass in WorkflowJobTemplatesAPI as the model.

**Comment by dsesami** [comment]
A few questions  --

None of these are blocking items, but I'd like to know what to create issues for, as well as stubs.

* Is adding an approval node planned work? I see start/success/failure.
* Is there any future planned work to add the ability to select/delete notifications from this view? It feels very limited in that sense.
* Clicking a single notification toggle makes all of the toggles flash momentarily. It also flashes a blue border around the list item. It's a bit jarring. Can this be changed?

Example:

![ezgif-3-4bc4addae22d](https://user-images.githubusercontent.com/19942822/77658738-830c2e80-6f4d-11ea-96a6-a6758071b220.gif)

**Comment by dsesami** [comment]
Conferred with @jlmitch5 --

1. Deletion of a notification from this view doesn't make a lot of sense. This should be done from the notification templates view.
2. Approval toggle work is planned here: https://github.com/ansible/awx/issues/6425
3. I'll be creating an issue for this.

Thanks so much, closing this out.
