### ISSUE TITLE
WFJT Schedules Tab

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5905]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
We'll need to support a few different things here:

1) The schedule list itself (should be able to re-use #4959 with a different endpoint)
2) Add schedule form (should be able to re-use #5864 with a different endpoint)
3) Edit schedule form (should be able to re-use #5865 with a different endpoint)
4) Schedule details view (should be able to re-use #5859 with a different endpoint)

Going to mark this as blocked until #4959, #5859, #5864, and #5865 are done.

**Comment by jlmitch5** [comment]
List has been added, we'll need to add add/edit once that is done.

**Comment by dsesami** [comment]
this applies to all the schedules tabs but putting it in one spot; mass-deletion _might_ be causing API issues: https://github.com/ansible/awx/issues/6708#issuecomment-613632975

**Comment by dsesami** [comment]
This feature has been merged; follow up issues are in #6708 #6171  #6718
