### ISSUE TITLE
Job Results - Output Filter

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#5906]
## Job Results - Header
Mockup: https://tower-mockups.testing.ansible.com/patternfly/jobs/jobs-output/

* Add dropdown to filter output by status
* Add dropdown to filter output by verbosity level (this one will require further discussion)

<img width="1498" alt="Screen Shot 2020-02-11 at 1 34 50 PM" src="https://user-images.githubusercontent.com/15881645/74267124-7d2af880-4cd3-11ea-8e2e-e0c23037278e.png">

##### ISSUE TYPE
 - Feature Idea

**Comment by tiagodread** [comment]
@unlikelyzero can we close this issue?

**Comment by unlikelyzero** [comment]
tests added
