### ISSUE TITLE
Host Facts Related Tab

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5907]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Link to mockup: https://tower-mockups.testing.ansible.com/patternfly/hosts/hosts-facts/

**Note that we're talking about both `/#/hosts/:id/facts` and `/#/inventories/:id/hosts/:id/facts`**

This tab is essentially a full page codemirror where the json/yaml from `/api/v2/hosts/:id/ansible_facts/` is displayed.

**Comment by dsesami** [comment]
Facts do not render properly when viewed unless interacted with. 

Before clicking and dragging on the facts:
![Screenshot from 2020-04-01 13-44-05](https://user-images.githubusercontent.com/19942822/78169082-dfc08b00-741e-11ea-9ae4-31d652964065.png)

After:
![Screenshot from 2020-04-01 13-44-32](https://user-images.githubusercontent.com/19942822/78169177-fff04a00-741e-11ea-97c8-34823e90b182.png)

**Comment by dsesami** [comment]
putting back in needs_devel after speaking with @jlmitch5 about it.

**Comment by jlmitch5** [comment]
I'm removing my assignment on this...we can take a look at this codemirror display issue at some point

**Comment by mabashian** [comment]
Closing this, created https://github.com/ansible/awx/issues/7915 instead.
