### ISSUE TITLE
Host Groups Related Tab

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5908]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
**Note that we're talking about `/#/hosts/:id/groups` and `/#/inventories/:id/hosts/:id/groups`**

This tab should list out the groups that this particular host belongs to.  It should also allow the user to add the host to an available group (add button + modal) as well as remove a host from a group.

Link to mockup: https://tower-mockups.testing.ansible.com/patternfly/hosts/hosts-groups/

**Comment by dsesami** [comment]
@jlmitch5 I am currently unable to add or edit the groups list for a host, despite having 3 groups existing in the inventory. is there something I need to do to enable that?

**Comment by dsesami** [comment]
reassigning to @unlikelyzero as he was already working on related things + involved. yall should coordinate to ensure all the different levels of functionality are in a branch you can validate wholesale. :+1: sounds like you need to validate the list itself, then validate add/remove.

**Comment by unlikelyzero** [comment]
Update: this is waiting on me to update with tests

**Comment by mabashian** [comment]
@unlikelyzero is this still in the needs_test queue or can we close it?  Seems like it's been open for a while.

**Comment by unlikelyzero** [comment]
@mabashian yes still needs to be left open. We just recently (July) came up with a way of testing this. It's been on our backburner and `needs_test` ensures that we don't lose sight of our backlog of tech debt.

**Comment by unlikelyzero** [comment]
@akus062381  we will need to do a quick audit on this one

**Comment by akus062381** [comment]
https://github.com/ansible/tower-qa/pull/6062

Taken care of. closing issue.
