### ISSUE TITLE
Support prompting on JT Launch

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5909]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
**It might be a good idea to break this work up into pieces that correspond with the different steps in the wizard.**

When configuring a Job Template, the user can specify whether or not certain fields should be prompted for when the job is launched.  In the UI, we'll need to present these fields to the launching user in a wizard.

Here's a link to the mockups: https://tower-mockups.testing.ansible.com/patternfly/templates/templates-prompt-inventory/

Note that the api provides us with a convenience endpoint: `/api/v2/job_templates/:id/launch/`.  This is where we should pull all of these flags from.

Potential Steps:

1) Inventory
    - This step is only shown if ask_inventory_on_launch is set to true
    - If there's a default inventory it should be selected
    - ~~User can select a different inventory but cannot proceed to the next step unless one is selected.~~
2) Credentials
    - This step is only shown if ask_credential_on_launch is set to true
    - If there are default credentials, they should be selected
    - Default credentials can be removed but they must be replaced with another credential of the same type.  This is enforced by the api.  For example, if there is a default machine credential on the JT then I can replace it with another machine credential but I cannot proceed to the next step without at least one machine credential.
    - The interface for this step is going to look just like the credential modal in the JT form
3) Credential Passwords
    - This step can be shown in one of two situations:
        - Firstly, it should be shown if passwords_needed_to_start is _not_ an empty array _and_ ask_credential_on_launch is set to false.
        - Secondly, it should be shown if ask_credential_on_launch is set to true _and_ any of the selected credentials from that step prompt for passwords.
    - This step is dynamic and should be able to support any number of password fields (the JT could have n number of different vault credentials all prompting for a password).
    - Previously we showed these password fields on the same step as the credentials.  If it's easier to do that here as well then we can explore that.
    - User cannot proceed to the next step until all required passwords are provided
4) Other Prompts
    - This step is shown when one or more of the follow flags is set to true:
        - ask_scm_branch_on_launch
        - ask_tags_on_launch
        - ask_diff_mode_on_launch
        - ask_skip_tags_on_launch
        - ask_job_type_on_launch
        - ask_limit_on_launch
        - ask_verbosity_on_launch
        - ask_variables_on_launch
    - Some of these fields are required (job type and verbosity) and the user must provide values for these fields before they can proceed to the next step.
5) Survey
    - This step is shown when survey_enabled is set to true
    - An extra request to get the survey spec (questions) is required in order to render this step
    - Survey questions will be dynamically rendered based on the survey spec and should be presented in the same order as they appear in the spec.
    - ~~Any required fields must be filled out before the user can proceed to the Preview step.~~
6) Preview
    - This step will _always_ be shown as long as some prompting has occurred (i.e. this wizard is actually shown).
    - This is a read-only step where all the prompted values are combined with JT defaults to give the launching user a snapshot of the configuration they're launching with.
    - Clicking the Launch button should hit the launch endpoint with all the specified overrides.

**Comment by mabashian** [comment]
After some discussion with @jakemcdermott @wenottingham we want to explore giving the users the ability to move freely between steps without performing validation until the end.  This would mean that if step 1 was to select an inventory (required) and the user wanted to do something on step 2 first then they could.  At the end of the process we'd still need to be able to indicate to them that they're missing a required field on step 1.

**Comment by unlikelyzero** [comment]
Adding needs test as a component of this feature card is being merged

**Comment by keithjgrant** [comment]
This issue is largely complete. I have outlined remaining work in additional follow-up issues:

* Credential passwords step is not yet implemented (#7015)
* More explicit user feedback in the preview step (#7016)
* There is some specific logic about when certain credentials are required based on the default credentials of the JT (#7018)

At this point, everything else is ready to be tested.

**Comment by dsesami** [comment]
Some feedback:
- Enabling pretty much all of the prompt on launch fields for the JT and setting default values for ALL of them gives me this error in the console when I hit launch and enter the launch wizard. I am unsure what the error is about, but if you need me to dig I can. here's the traceback:
```
Warning: Failed prop type: Invalid prop `steps[0].name` of type `object` supplied to `PFWizard`, expected `string`.
    in PFWizard (at LaunchPrompt.jsx:55)
    in Formik (at LaunchPrompt.jsx:53)
    in LaunchPrompt (created by I18n)
    in I18n (created by WithI18n)
    in WithI18n (at LaunchButton.jsx:174)
    in LaunchButton (created by Context.Consumer)
    in withRouter(LaunchButton) (created by I18n)
    in I18n (created by WithI18n)
    in WithI18n (at JobTemplateDetail.jsx:378)
    in div (created by CardActions)
    in CardActions (at CardActionsRow.jsx:13)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (at CardActionsRow.jsx:12)
    in CardActionsRow (at JobTemplateDetail.jsx:366)
    in div (created by PFCardBody)
    in PFCardBody (created by Context.Consumer)
    in StyledComponent (created by Styled(CardBody))
    in Styled(CardBody) (at JobTemplateDetail.jsx:166)
    in JobTemplateDetail (created by I18n)
    in I18n (created by WithI18n)
    in WithI18n (at Template.jsx:163)
    in Route (at Template.jsx:162)
    in Switch (at Template.jsx:155)
    in article (created by Card)
    in Card (at Template.jsx:153)
    in section (created by PageSection)
    in PageSection (at Template.jsx:152)
    in Template (created by I18n)
    in I18n (created by WithI18n)
    in WithI18n (at Templates.jsx:96)
    in Route (at Templates.jsx:91)
    in Switch (at Templates.jsx:84)
    in Templates (created by Context.Consumer)
    in withRouter(Templates) (created by I18n)
    in I18n (created by WithI18n)
    in WithI18n (at src/index.jsx:250)
    in Route (at src/index.jsx:246)
    in Switch (at src/index.jsx:261)
    in main (created by Page)
    in div (created by Page)
    in Page (at App.jsx:186)
    in App (created by Context.Consumer)
    in withRouter(App) (created by I18n)
    in I18n (created by WithI18n)
    in WithI18n (at src/index.jsx:90)
    in Route (at src/index.jsx:84)
    in Switch (at src/index.jsx:80)
    in Unknown (at src/index.jsx:79)
    in I18n (at src/index.jsx:77)
    in I18nProvider (at RootProvider.jsx:19)
    in Router (created by HashRouter)
    in HashRouter (at RootProvider.jsx:18)
    in RootProvider (at src/index.jsx:76)
```
```
Warning: Failed prop type: Invalid prop `text` of type `object` supplied to `WizardNavItem`, expected `string`.
    in WizardNavItem (created by WizardToggle)
    in WizardToggle (created by PFWizard)
    in div (created by PFWizard)
    in div (created by Bullseye)
    in Bullseye (created by PFWizard)
    in div (created by Backdrop)
    in Backdrop (created by PFWizard)
    in div (created by FocusTrap)
    in FocusTrap (created by PFWizard)
    in PFWizard (at LaunchPrompt.jsx:55)
    in Formik (at LaunchPrompt.jsx:53)
...etc etc
```

**Comment by keithjgrant** [comment]
@dsesami That’s a known issue filed with patternfly: https://github.com/patternfly/patternfly-react/issues/4134

**Comment by dsesami** [comment]
Haven't tracked down other issues in this one. Given the follow-up issues are outlined, closing this out.
