### ISSUE TITLE
Add credentials of vault type to credential prompt on launch list

### ISSUE THREAD

**Issue by ghost** [ansible/awx#591]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
Add credentials of vault type to the list of available credentials to select when 'prompt on launch' is set for credential in the job template setup.

##### ENVIRONMENT
* AWX version: 1.0.0

##### STEPS TO REPRODUCE

This will allow for vault credentials to be added to a job template run based on a launch-time prompt, as selected from a list of possibilities.

**Comment by AlanCoding** [comment]
Link #352 

Ping @ryanpetrello

**Comment by ryanpetrello** [comment]
Yep, this is a use case I intend to handle in #352.

**Comment by matburt** [comment]
closing as work will be handled in #352
