### ISSUE TITLE
Support prompting on workflow nodes

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5913]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
When a user selects a JT or WFJT with promptable fields while creating or editing a workflow node we want to give that user the ability to fill in the prompts right there in the wizard.  These fields have to be provided with the node and will not be prompted for at launch time.

There's a significant amount of overlap with #5909 and #5910 so hopefully we can re-use some of those same steps here.

Like JT schedules, credentials that require passwords cannot be used in a WF node job.  We don't store those passwords and they can't be provided at launch time so the user will need to _replace_ those credentials if they are present on the JT that's been selected as a node.

Some extra text needs to be added to the inventory step when it's promptable.  The global WFJT Inventory will trump and node level inventory that's provided.  We want to communicate that to the user.  This is probably only necessary if ask_inventory_on_launch is set to true on the outer workflow.

The preview step will differ a little bit from the launch preview step because we'll want to show the JT/WFJT as well as the edge type (success/failure/always).  Probably also need to show something about it's convergence state in the preview as well.

Going to set this as blocked until #5909 and #5910 land.

Link to mockups: https://tower-mockups.testing.ansible.com/patternfly/workflows/workflows-add-step2a/

**Comment by mabashian** [comment]
WFJT prompting hasn't been merged yet but the PR is quite small and I don't think it will impact this work at all so I removed the `blocked` label.

**Comment by mabashian** [comment]
@AlexSCorey moving this into in_progress since I know you've done a lot of work on it already

**Comment by AlexSCorey** [comment]
@mabashian good call, thanks

**Comment by unlikelyzero** [comment]
@AlexSCorey i'll be testing writing up the testcases for this next week

**Comment by AlexSCorey** [comment]
POL bugs reported by QE that should make it into this work if possible.

- [x] Unique IDs for Next, Back and Cancel Buttons

- [ ] Variable field with wrong format like `Foo:Bar` without spacing doesn't display the validation error

- [ ] Trying to launch a JT without enabling the variables POL with survey the variable field doesn't appear on the preview step
