### ISSUE TITLE
Upgrade from 9.1.1 to 9.2

### ISSUE THREAD

**Issue by cs35-owncloud** [ansible/awx#5915]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Upgrading AWX from 9.1.1 to 9.2 fails since the docker image for [awx_web](https://hub.docker.com/r/ansible/awx_web/tags) and [awx_task](https://hub.docker.com/r/ansible/awx_task/tags) do not exist. It seems it has happened a while ago as reported [here](https://github.com/ansible/awx/issues/3199). Maybe I was to fast to upgrade :s Could you publish the 9.2 for both images ? Thanks.

##### ENVIRONMENT
* AWX version: 9.1.1
* AWX install method: docker on linux
* Ansible version:  2.9.3
* Operating System: Debian 10.3
* Web Browser: 

##### STEPS TO REPRODUCE

Simply follow the upgrade process of the [README.md](https://github.com/ansible/awx/blob/devel/INSTALL.md#upgrading-from-previous-versions)

##### EXPECTED RESULTS

AWX should upgrade nicely to 9.2 without any errors.

##### ACTUAL RESULTS

The upgrade process fails when starting the containers:

`TASK [local_docker : Start the containers] ***************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "errors": [], "module_stderr": "", "module_stdout": "", "msg": "Error starting project 404 Client Error: Not Found (\"b'manifest for ansible/awx_web:9.2.0 not found'\")"}`

**Comment by ryanpetrello** [comment]
Hey @cs35-owncloud,

We're publishing and uploading new images this morning.

**Comment by ryanpetrello** [comment]
https://groups.google.com/forum/#!topic/awx-project/LL0SCbAsViw

**Comment by cs35-owncloud** [comment]
Thanks, it works !
I guess I'll wait a bit longer before to upgrade now, the [release](https://github.com/ansible/awx/releases/tag/9.2.0) seemed to be fine though in github.
