### ISSUE TITLE
how can I deploy the awx in kubernetes

### ISSUE THREAD

**Issue by xu5762173** [ansible/awx#592]
I deploy awx with docker-compose, it run correctly : https://github.com/geerlingguy/awx-container

but seems some issues on the kubernetes https://github.com/ansible/awx/issues/86

do we have a plan or project to build? so we can run the awx on kubernetes cluster?

**Comment by matburt** [comment]
We need to migrate the existing Openshift deployment to use K8S. I'm planning on supporting this but haven't quite gotten to it yet.

**Comment by arthur-c** [comment]
Hi @matburt,
Is there a draft of the kubernetes deployment ? I you have any plan/recommandations I'll be glad to hear them as I will start soon to deploy AWX on my cluster

**Comment by b0r1sp** [comment]
+1

**Comment by niso120b** [comment]
Hi @matburt, there is any updates about it?

**Comment by missnebun** [comment]
Really curios about this as well.

**Comment by AIXruth** [comment]
+1

**Comment by yangyingjie1001** [comment]
Do you have one now?

**Comment by flvritski** [comment]
+1

**Comment by ryanpetrello** [comment]
https://github.com/ansible/awx/blob/devel/INSTALL.md#kubernetes
