### ISSUE TITLE
awx cli exit code on job failure

### ISSUE THREAD

**Issue by agrisvv** [ansible/awx#5920]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Need implement different exit code on Job or Workflow  status failure like it was with tower-cli.
It is hard to --monitor output in stream and get failure status

now workaround:
```` 
RESULT=$(awx workflow_job_templates launch "${IDNAME}" --monitor -f human --filter status | tee /dev/tty | tail -1)
````

run failed job:
`````
awx workflow_job_templates launch "${IDNAME}" --monitor -f human
echo $?
`````
result:
````
0
````
expected other code:
````
99 or 1
````

**Comment by ryanpetrello** [comment]
@agrisvv this behavior is *different*, though I'm not entirely sure I agree with this in spirit.  An exit code of `0` suggests to me that the *launch* worked (not necessarily that the job succeeded/failed).

@AlanCoding what's your opinion on this?

**Comment by AlanCoding** [comment]
Launch with monitor is something I'd treat differently from just launch. We certainly need to give some reliable signal for people using the CLI in bash scripts or wherever. You don't want to grep the output. You could recommend a subsequent command to do a get for the job, do jq parse to get status. But to do that you'd need the job id, which is more difficult to get in a launch/monitor combination action. So I don't really have a valid answer by that approach for how it should be done.

The use case seems pretty clear to me. Bash script with an if-else based on final job status. Whatever the recommendation is, we should have something that works relatively well.

**Comment by ryanpetrello** [comment]
Okay, sounds fair.  I'll leave this in `enhancement`.

**Comment by davidban77** [comment]
This is really helpful when working with CI systems that can use awx cli to run jobs

**Comment by ryanpetrello** [comment]
@davidban77 @agrisvv either of you willing to give this patch a shot?

https://github.com/ansible/awx/pull/6081

**Comment by agrisvv** [comment]
> @davidban77 @agrisvv either of you willing to give this patch a shot?
> 
> #6081


Tested in bash script. Tested exit on some command failure in script. Bash exist status are 1 - OK
``````
#!/bin/bash
set -e
echo "test"
awx workflow_job_templates launch "awxtest_workflow_failed" --monitor -f human --filter status 
echo "test2"
````````
``````
echo $?
1
```````
Tested from terminal and result are same exit code are 1 - OK
``````
awx workflow_job_templates launch "awxtest_workflow_failed" --monitor -f human --filter status
``````
``````
echo $?
1
```````

**Comment by davidban77** [comment]
Yep, can confirm as well - thanks!

**Comment by kdelee** [comment]
This also works for me, closing!
