### ISSUE TITLE
CredentialLookup not sending name value to CheckboxListItem

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#5930]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
CheckboxListItem component requires a name value and CredentialLookup is not sending that data.  It results in a console error
##### ENVIRONMENT
* AWX version: 9.1.1
* AWX install method: docker for mac
* Ansible version:  2.10
* Operating System: Mojave
* Web Browser:Chroms

##### STEPS TO REPRODUCE

Go to any form that uses the CredentialLookUp and click on it to open the modal.  
##### EXPECTED RESULTS

No error in the console.

##### ACTUAL RESULTS

Error in the console saying the CheckboxListItem requires a 'name' value.

**Comment by mabashian** [comment]
I _think_ that this must have gotten fixed somewhere along the way because I no longer see an error in the console when opening up credentials lookup(s).

**Comment by mabashian** [comment]
In order to trigger this there has to be at least one credential in the lookup.

**Comment by mabashian** [comment]
Planning to include a fix for this in #5841
