### ISSUE TITLE
AWX does not build on CentOS Stream

### ISSUE THREAD

**Issue by artainis** [ansible/awx#5934]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.4
* Operating System: CentOS Stream
* Web Browser:

##### STEPS TO REPRODUCE

    ansible-playbook -i inventory install.yml -v

##### EXPECTED RESULTS

Successful build

##### ACTUAL RESULTS

TASK [image_build : Build sdist builder image] *************************************************************************************************************************************************************************************************************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Error building awx_sdist_builder - code: 1, message: The command '/bin/sh -c yum -y update && yum -y install epel-release && yum -y install https://centos7.iuscommunity.org/ius-release.rpm' returned a non-zero code: 1
, logs: ['Step 1/10 : FROM centos:7', '\\n', ' ---> 5e35e350aded\\n', 'Step 2/10 : RUN yum -y update && yum -y install epel-release && yum -y install https://centos7.iuscommunity.org/ius-release.rpm', '\\n', ' ---> Running in 016db7e3e6a9\\n', 'Loaded plugins: fastestmirror, ovl\\n', 'De
termining fastest mirrors\\n', '\\x1b[91m\\n\\n One of the configured repositories failed (Unknown),\\n and yum doesn\\'t have enough cached data to continue. At this point the only\\n safe thing yum can do is fail. There are a few ways to work \"fix\" this:\\n\\n     1. Contact the upst
ream for the repository and get them to fix the problem.\\n\\n     2. Reconfigure the baseurl/etc. for the repository, to point to a working\\n        upstream. This is most often useful if you are using a newer\\n        distribution release than is supported by the repository (and the\
\n        packages for the previous distribution release still work).\\n\\n     3. Run the command with the repository temporarily disabled\\n            yum --disablerepo=<repoid> ...\\n\\n     4. Disable the repository permanently, so yum won\\'t use it by default. Yum\\n        will t
hen just ignore the repository until you permanently enable it\\n        again or use --enablerepo for temporary usage:\\n\\n            yum-config-manager --disable <repoid>\\n        or\\n            subscription-manager repos --disable=<repoid>\\n\\n     5. Configure the failing repos
itory to be skipped, if it is unavailable.\\n        Note that yum will try to contact the repo. when it runs most commands,\\n        so will have to try and fail each time (and thus. yum will be be much\\n        slower). If it is a very temporary problem though, this is often a nice\\
n        compromise:\\n\\n            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true\\n\\nCannot find a valid baseurl for repo: base/7/x86_64\\n\\x1b[0m', 'Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container erro
r was\\n14: curl#6 - \"Could not resolve host: mirrorlist.centos.org; Unknown error\"\\n', 'Removing intermediate container 016db7e3e6a9\\n']"}

**Comment by shanemcd** [comment]
```
Could not resolve host: mirrorlist.centos.org
```

At first glance, this looks like a networking problem in your environment. This issue tracker is intended for bugs and enhancements for the AWX application itself. For help troubleshooting your setup, you can post on the [mailing list](https://groups.google.com/forum/#!forum/awx-project) or the [IRC channel](http://webchat.freenode.net/?channels=ansible-awx).

**Comment by artainis** [comment]
Why is the task using a CentOS 7 repository even though I am on CentOS 8 Stream? I am able to ping the website and turned off firewalld while building the docker images. Pinging mirrorlist.centos.org works fine.

Are these yum commands running on the host or inside the docker containers?

**Comment by Macphones92** [comment]
did you ever figure out how to fix this issue
