### ISSUE TITLE
AWX: A server error has occurred

### ISSUE THREAD

**Issue by Gorrah** [ansible/awx#5943]
##### ISSUE TYPE
 - Install Issue

##### COMPONENT NAME
 - Installer

##### SUMMARY
After installing on CentOS 8, using Docker and docker compose, I'm getting an error when trying to load the webpage. Says "A server error has occurred." I looked into the logs in awx_task and found this error: 
```
django.db.utils.OperationalError: could not connect to server: No route to host
        Is the server running on host "postgres" (172.18.0.2) and accepting
        TCP/IP connections on port 5432?
```
I tried allowing that port through the firewall on the CentOS 8 server, but it would stand to reason to me that it needs to be allowed maybe on the postgres container? I'm pretty novice at Linux, so I'm really unsure what to do next here. I'm also new to docker and containers, so any help would be appreciated.
##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method: docker on linux, 
* Ansible version:  2.9.3
* Operating System: CentOS 8/Windows 10 1909(For web browing.)
* Web Browser: Edge Chromium, Chrome, Internet Explorer

##### STEPS TO REPRODUCE

Anytime I navigate to the web address of the server to get the AWX page, I get the "A server error has occurred."

##### EXPECTED RESULTS

Not sure what to place here, beyond I expected it to work! :)

##### ACTUAL RESULTS

<Error page.

**Comment by ryanpetrello** [comment]
Hey @Gorrah,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by Gorrah** [comment]
@ryanpetrello Sorry about that. I thought I had seen troubleshooting issues posted here before. Thanks for pointing me in the right direction!
