### ISSUE TITLE
Unable to install AWX in RHEL7 system: "Unable to load docker-compose. Try `pip install docker-compose`. Error: No module named compose"

### ISSUE THREAD

**Issue by parasharsingh8086** [ansible/awx#5944]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method: docker on linux
* Ansible version:  2.7.8-1.el7ae.noarch
* Operating System: Red Hat Enterprise Linux
* Web Browser:

##### STEPS TO REPRODUCE

Installing Ansible with it's Playbook: ansible-playbook -i inventory install.yml

##### EXPECTED RESULTS

The Install is failing with error msg: 
TASK [local_docker : Render SECRET_KEY file] ***************************************************************************************************************
ok: [localhost]

TASK [local_docker : Start the containers] *****************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to load docker-compose. Try `pip install docker-compose`. Error: No module named compose"}
        to retry, use: --limit @/i01/awx/installer/install.retry

PLAY RECAP *************************************************************************************************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=1

[root@installer]#

**Comment by ryanpetrello** [comment]
Hey @parasharsingh8086,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
