### ISSUE TITLE
WFViz 'Fit to Screen size' action doesn't include all nodes in certain scenarios

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#5953]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
WFViz 'Fit to Screen size' action doesn't include all nodes in certain scenarios. Only one is described below in the repro steps

##### ENVIRONMENT
* AWX version: 9.next
* Operating System: macOS Catalina
* Web Browser: Chrome 80

##### STEPS TO REPRODUCE
1. Create a WFJT with 5 fan-out nodes off of the start
2. Open that WFJT in the WFViz.
3. Click the 'Fit to Screen Size' button

##### EXPECTED RESULTS
1. All 5 nodes come into view

##### ACTUAL RESULTS
1. Only 4 of 5 come into view

##### ADDITIONAL INFORMATION
<img width="1517" alt="Screen Shot 2020-02-16 at 2 40 22 PM" src="https://user-images.githubusercontent.com/12446869/74611506-9a443a80-50ca-11ea-9f22-ddc79fb1aea8.png">

**Comment by AlexSCorey** [comment]
I don't think this is a valid issue any longer.
