### ISSUE TITLE
build static files

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#5957]
##### SUMMARY
Currently, the `ui_next` static files are never written to disk - they live in memory and are served from the development server. This issue is for extending the build tooling to produce static files that can be served from a non-development installation of awx.

**Comment by jakemcdermott** [comment]
Please remove `blocked` label from https://github.com/ansible/awx/issues/5958 when this lands.

**Comment by mabashian** [comment]
@jakemcdermott should we close this issue now that #6954 has landed? Or do we have remaining work items that need to be tracked?

**Comment by jakemcdermott** [comment]
@mabashian we can close
