### ISSUE TITLE
Add ui_next static files to build / install process. 

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#5958]
##### SUMMARY
- Integrate the new ui into existing build / install process.
- ~Current ui will still be the default, but new ui should be reachable after deploying / installing AWX.~

requires: https://github.com/ansible/awx/issues/5957

**Comment by unlikelyzero** [comment]
Note: we should do some "light" QE on this outside of the scope of the cypress tests

**Comment by mabashian** [comment]
@jakemcdermott do we still need to keep this open?

**Comment by mabashian** [comment]
Oh this is different from #5957.  OK I think this is not blocked anymore?  If so feel free to correct the labels.

**Comment by jakemcdermott** [comment]
Done, see https://github.com/ansible/awx/pull/8607
