### ISSUE TITLE
Wrong z-depth for 'Inventory Source' dropdown on Add/Edit WF Graph Node

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#5960]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE
Wrong z-depth for 'Inventory Source' dropdown on Add/Edit WF Graph Node

##### EXPECTED RESULTS
Expect dropdown to be completely visible above footer of modal

##### ACTUAL RESULTS
Dropdown obscured behind footer of modal

##### ADDITIONAL INFORMATION
<img width="1154" alt="Screen Shot 2020-02-17 at 3 15 33 PM" src="https://user-images.githubusercontent.com/12446869/74684140-1e64f380-5199-11ea-8045-0d96ec0231b2.png">

**Comment by nixocio** [comment]
Not sure if this issue itself remains valid. Since the time this issue was filed, we removed a few items from the drop down.

![image](https://user-images.githubusercontent.com/9053044/99577773-d1bd7b80-29a9-11eb-83e4-1244a7c4aa1d.png)

**Comment by marshmalien** [comment]
> Expect dropdown to be completely visible above footer of modal

There is a PatternFly prop that allows the Select to be appended to a higher DOM element. If we add `menuAppendTo={document.body}` to the Select component, it will allow the Select to break out of the modal's overflow behavior. 

https://www.patternfly.org/v4/components/modal#with-dropdown
<img width="873" alt="Screen Shot 2020-11-18 at 2 39 42 PM" src="https://user-images.githubusercontent.com/15881645/99580925-12b78f00-29ae-11eb-873e-54e69a887950.png">

**Comment by AlexSCorey** [comment]
This issue is no longer valid.
