### ISSUE TITLE
Cannot select 'Manual' for 'Inventory Source Sync' or 'Project Sync' on WF Graph Add/Edit Modal

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#5963]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Cannot select 'Manual' 'Inventory Source Sync' on WF Graph Add/Edit Modal

##### ENVIRONMENT
* AWX version: 9.next

##### STEPS TO REPRODUCE
1. Open WF Graph Editor
2. Add / Edit node
3. Select Inventory Source Sync nodetype
4. Attempt to filter by 'Manual'
Note: Can filter by every other type

##### EXPECTED RESULTS
Can select 'Manual' source in the same way that I can select all other sources

##### ACTUAL RESULTS
Inert action on selection of 'Manual'

##### ADDITIONAL INFORMATION
<img width="1259" alt="Screen Shot 2020-02-17 at 3 25 54 PM" src="https://user-images.githubusercontent.com/12446869/74684603-59b3f200-519a-11ea-8c79-7e71ab4ced28.png">

**Comment by mabashian** [comment]
@wenottingham - was looking at this with Keith and we noticed that the UI is specifically filtering out `manual` inventory sources in the old UI.  Additionally, `manual` is not an option in the inventory source form.  Should we be filtering out `manual` inventory sources from the workflow node inventory sources list (`?not__source=`) here in the new UI?  If so, I think we could just get rid of this option in the search.

**Comment by wenottingham** [comment]
I feel like `manual` is a vestigial API artifact that maybe should be going away. cc @ryanpetrello @AlanCoding

**Comment by AlanCoding** [comment]
https://github.com/ansible/awx/blob/cfb633e8a643b0190fa07b6204b339a1d336cbb3/awx/main/migrations/_inventory_source.py#L8-L17

**Comment by dsesami** [comment]
"Manual" as an option was removed from the list successfully for all inventory sync views.

**Comment by unlikelyzero** [comment]
@dsesami did you remove the test stubs?

**Comment by unlikelyzero** [comment]
@dsesami https://github.com/ansible/tower-qa/pull/4848
