### ISSUE TITLE
awx kit provides a bad error message

### ISSUE THREAD

**Issue by benthomasson** [ansible/awx#5964]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When authentication fails awx kit gives a cryptic error message

##### ENVIRONMENT
* AWX version: devel
* AWX install method: mac
* Ansible version:  2.8.2
* Operating System: mac
* Web Browser: N/A

##### STEPS TO REPRODUCE

Attempt to login to awx with bad credentials.

##### EXPECTED RESULTS

> Unauthorized: Unauthorized (401) received - {'detail': 'Authentication credentials were not provided. To establish a login session, visit /api/login/.'}

##### ACTUAL RESULTS

> TypeError: '>=' not supported between instances of 'Unauthorized' and 'int'

##### ADDITIONAL INFORMATION

> akit --base-url httsp://some-awx -c ~/creds/credentials.vault -f load_resources.py -x

**Comment by john-westcott-iv** [comment]
awxkit now appears to give a better message:
```
Valid credentials were not provided.
$ awx login --help
```
