### ISSUE TITLE
Unable to select a Project Sync 'git' type in WF Graph Add/Edit Node

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#5966]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Unable to select a Project Sync 'git' type in WF Graph Add/Edit Node

##### ENVIRONMENT
* AWX version: 9.next

##### STEPS TO REPRODUCE
1. Open WF Graph
2. Navigate to the Add Edit Node modal
3. Attempt to filter the list of 'Project Sync' to git type

##### EXPECTED RESULTS
List of Projects with git type

##### ACTUAL RESULTS
Nothing returned

##### ADDITIONAL INFORMATION

<img width="941" alt="Screen Shot 2020-02-17 at 4 16 54 PM" src="https://user-images.githubusercontent.com/12446869/74686897-ee215300-51a0-11ea-843a-04af251af0b0.png">

**Comment by mabashian** [comment]
This was fixed somewhere along the way:

<img width="1426" alt="Screen Shot 2020-08-26 at 4 10 04 PM" src="https://user-images.githubusercontent.com/9889020/91351649-a0704d80-e7b6-11ea-82ab-523bb6780658.png">

Moving to needs_test

**Comment by dsesami** [comment]
This is blocked by https://github.com/ansible/awx/issues/8124

**Comment by dsesami** [comment]
This works perfectly fine now -- filtering works as expected for project sync list. a stub is present in workflow-viz-project-sync-nodetype.spec
