### ISSUE TITLE
Credential type : hashicorp vault doesn't appears into job template configuration 

### ISSUE THREAD

**Issue by phbureau** [ansible/awx#5974]
Good afternoon,

I have a serious problem. 

##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I have created a credential of type : " Hashicorp vault secret lookup"

![image](https://user-images.githubusercontent.com/43671480/74744532-b7137600-5262-11ea-9032-e45860e2f411.png)

It's fine until now.
When I try to add this credential into a job template, this type of credential doesn't appear. And so I cannot add my credential.
![image](https://user-images.githubusercontent.com/43671480/74744911-56d10400-5263-11ea-925e-d6323ab5a83f.png)

![image](https://user-images.githubusercontent.com/43671480/74744939-63555c80-5263-11ea-9082-622526ebe9dd.png)

And it also doesn't appear in Vault type. 

Thanks for your help !

##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method:  docker-ce on linux,
* Ansible version:  2.9.3
* Operating System: RedHat
* Web Browser: Firefox

**Comment by ryanpetrello** [comment]
Hey @phbureau,

This isn't how credential plugins like Hashicorp Vault are used.  Have a look at this documentation:

https://docs.ansible.com/ansible-tower/latest/html/userguide/credential_plugins.html#ug-credential-plugins
https://github.com/ansible/awx/blob/devel/docs/credentials/credential_plugins.md
