### ISSUE TITLE
Kubernetes deployment not rendered correctly

### ISSUE THREAD

**Issue by donomur** [ansible/awx#5985]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When `openshift_host` is not defined, the k8s deployment template is not indented properly and fails to install.

##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method: k8s
* Ansible version:  2.9.0
* Operating System: Ubuntu Linux
* Web Browser: n/a

##### STEPS TO REPRODUCE

Perform a kubernetes installation without `openshift_host` defined.

##### EXPECTED RESULTS

Installation success.

##### ACTUAL RESULTS

kubectl fails to deploy AWX due to a syntax error (`spec` having the 2 space indent from the indented `if` statement from previous lines)

##### ADDITIONAL INFORMATION

Caused by c94680eaba729307fed25488444e63fd0dda2df1 https://github.com/ansible/awx/pull/5949

**Comment by ryanpetrello** [comment]
addressed by https://github.com/ansible/awx/pull/5986
