### ISSUE TITLE
JOB TYPE or VERBOSITY is not seen at job template detail view 

### ISSUE THREAD

**Issue by JosephJHCho** [ansible/awx#5987]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
UI bug. At job template detail view, one of items 'JOB TYPE' and 'VERBOSITY' is not seen. Just blank. After refresh, it shows or the other is not seen. For example, if JOB TYPE was not seen first, after refresh sometimes VERBOSITY is not seen.

##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.3
* Operating System: Centos 7.7.1908
* Web Browser: Chrome

##### STEPS TO REPRODUCE
1. Register some job templates with all mandatory items selected.
2. Click sequentially each job templates to see details
3. One of job templates detail view is seen with this bug.

##### EXPECTED RESULTS
All items must be seen what I have selected.

##### ACTUAL RESULTS
Item 'JOB TYPE' or 'VERBOSITY' is not seen sometimes.

**Comment by wenottingham** [comment]
Is this self-built, or using the stock image? Do you have a screenshot?

**Comment by JosephJHCho** [comment]
![img1](https://user-images.githubusercontent.com/25745571/74894247-bfd68a00-53d1-11ea-9bce-f4456f66ce74.png)
![img2](https://user-images.githubusercontent.com/25745571/74894250-c36a1100-53d1-11ea-8e24-37b6b01c208f.png)
Two images are same template. And it is stock image not built.

**Comment by ryanpetrello** [comment]
@JosephJHCho do you see any errors or warnings in the browser Developer Console?

cc @mabashian @jakemcdermott

**Comment by JosephJHCho** [comment]
Whether JOB TYPE and VERBOSITY is seen or not, there is always a warning and a info and no errors.
........
WARNING: Tried to load AngularJS more than once.  vendor.08d153df1a615982ffc7.js:24 

[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ vendor.08d153df1a615982ffc7.js:24
........

And I can't reproduce but there was a warning once.
........
nvd3 warning: `fixedTop` has been deprecated.  feature removed after 1.8.1
nv.deprecated @ vendor.08d153df1a615982ffc7.js:196
........

**Comment by JosephJHCho** [comment]
Just for your information. I have tested some other version.
AWX 7.0 was fine but AWX 8.0 have a same problem.

**Comment by dsesami** [comment]
Looks like the fields don't magically vanish. Seems to work. :+1:
