### ISSUE TITLE
Ansible-Router ACL Changes 

### ISSUE THREAD

**Issue by ilayaraja-p** [ansible/awx#5988]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY
Router ACL Changes -
Ansible playbook Execution – While updating the below Router ACL changes in router, The playbook execution status was changed, but the changes are not replicated in Router and not getting any error message.
Please find the below changes.
Changes: If the existing rule sequence number is modified for new rule with same sequence number.
Manual configuration – while updating the same rule change in manual configuration. I’m getting error message % Duplicate sequence number

##### ENVIRONMENT
* Ansible version:  2.8.7

**Comment by wenottingham** [comment]
This sounds like a playbook level issue, which should be discussed in the ansible-project google group, or on the Ansible issue tracker at https://github.com/ansible/ansible. This repo is for issues in AWX itself.
