### ISSUE TITLE
Translate START button in workflow visualizer/output

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5990]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
<img width="319" alt="Screen Shot 2020-02-19 at 8 51 27 AM" src="https://user-images.githubusercontent.com/9889020/74840504-1ae67f00-52f5-11ea-90b4-51af3e81932c.png">

This is a bit more tricky than just wrapping a string in `i18n._(t...)`.  Since the element that houses this text needs to be statically sized we need to know how much space the text will take up before rendering.  The size of the text differs based on the translation.

We've addressed this issue in the old application by appending an element to the body (hidden), measuring the width and using that to actually render the svg element later on.  You can see this behavior here: https://github.com/ansible/awx/blob/devel/awx/ui/client/src/templates/workflows/workflow-chart/workflow-chart.directive.js#L26.

We may have to do something similar or maybe we can come up with a less hacky solution.

**Comment by unlikelyzero** [comment]
Note: please wait until translations before closing this issue

**Comment by unlikelyzero** [comment]
tested and coverage added
