### ISSUE TITLE
Hook up launch button on workflow visualizer

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5991]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
<img width="654" alt="Screen Shot 2020-02-19 at 9 05 36 AM" src="https://user-images.githubusercontent.com/9889020/74841706-191dbb00-52f7-11ea-886e-ff1c2d626d53.png">

This button is currently completely disabled.

This button should be enabled when:

1) The user has permissions to launch the wfjt
2) The workflow has no unsaved changes

Clicking the button should present the user with any available prompts and launch the workflow.  Behavior should match that of the templates list launch button.

**Comment by dsesami** [comment]
The launch button works! and the logic for enabling/disabling works. However, there's no error handling visible for broken template. The launch button is disabled, but we aren't told why. I will be creating a separate issue for that.

**Comment by dsesami** [comment]
https://github.com/ansible/awx/issues/6528 as a follow-up
