### ISSUE TITLE
Hook up documentation button on workflow visualizer

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5992]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
<img width="309" alt="Screen Shot 2020-02-19 at 9 08 26 AM" src="https://user-images.githubusercontent.com/9889020/74841914-7e71ac00-52f7-11ea-80f8-5c0c01d4f46c.png">

This button should always be enabled and it should link the user out to https://docs.ansible.com/ansible-tower/latest/html/userguide/workflow_templates.html#ug-wf-editor (I think).  Clicking this button should open the link in a new tab.

**Comment by dsesami** [comment]
Link works, is enabled as expected :+1:
