### ISSUE TITLE
Inventory should be removable on a JT

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5996]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
We probably made it required initially because we didn't have the prompt on launch option in the form.  When this option becomes available we need to make the inventory removable.

The rule for inventory on JT is that either:

a) A default inventory is provided
or
b) Prompt on launch is checked

As a result, the user should be able to remove the selected inventory.

Marking as blocked until https://github.com/ansible/awx/issues/4967 lands

**Comment by mabashian** [comment]
I went ahead and addressed this in #4967

**Comment by dsesami** [comment]
conferred with @mabashian on this. There was a miscommunication, and this has not been implemented. bouncing back to needs_devel

**Comment by dsesami** [comment]
This looks really good and handles all variations of selecting and unselecting prompt on launch for inventories.
