### ISSUE TITLE
Hook up view node button in workflow visualizer

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5997]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
<img width="828" alt="Screen Shot 2020-02-19 at 9 56 38 AM" src="https://user-images.githubusercontent.com/9889020/74846234-25f1dd00-52fe-11ea-8cab-95285a567a5f.png">

I've got some of this working on https://github.com/mabashian/awx/tree/ui-next-workflows-w-details.

The idea here is that we want to give the user a snapshot of how the node is configured (combined with values from the UJT).

In the modal, we should be showing a lot of the same info that we show in the details view for whatever the UJT is but we should merge in prompt values and denote those overridden values in some way (maybe a different color?)

Here's a link to the mockup:

https://tower-mockups.testing.ansible.com/patternfly/workflows/workflows-detail/

The act of combining all of these values down into a single view is a bit complicated.  We can look at the summary page on the prompt modal (in the old app) for _some_ reference.

**Comment by marshmalien** [comment]
Splitting this into 2 smaller issues:
- [x] Add WF Node Modal detail views #6530
- [ ] Merge Overridden values and show them in the Prompted Values section

**Top Section:** Basic Details (basic values and default prompt values)
**Bottom Section:** Overridden Prompts

![image](https://user-images.githubusercontent.com/15881645/79508069-d7637500-8006-11ea-9340-191b702cf675.png)

**Comment by mabashian** [comment]
@marshmalien refresh my memory - do we still need to implement the bottom section (Overridden Prompts)? Or did that get merged a while ago?  Wondering if this issue is still relevant/in progress.

**Comment by marshmalien** [comment]
@mabashian Oh, that second checkbox would best be done when we hookup the workflow node prompting https://github.com/ansible/awx/issues/5913. Since wf node prompting wasn't hooked up at the time of this issue, I couldn't test that the entire flow from editing a wf node to viewing the wf node preview with overrides worked correctly. Currently, the NodeViewModal does not pass **overrides** to the preview PromptDetail component. The launch prompt PreviewStep component does this correctly and we could use that as a guide whenever wf node prompting is ready.

**Comment by mabashian** [comment]
@marshmalien are we keeping this open until workflow prompting is in place or is this ready to be closed?

**Comment by mabashian** [comment]
Marking this as blocked until #5913 is done

**Comment by mabashian** [comment]
The rest of this should be completed with https://github.com/ansible/awx/pull/8399.  I'll update this issue when appropriate.

**Comment by unlikelyzero** [comment]
https://github.com/ansible/awx/pull/8399#pullrequestreview-553909542
