### ISSUE TITLE
ec2.py Dynamic inventory IPv6 support

### ISSUE THREAD

**Issue by idelsink** [ansible/awx#5998]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Our AWS infrastructure is IPv6 ready. All machines are IPv6 reachable and can be reached via SSH over IPv6. The ec2.py dynamic inventory does not generate IPv6 hosts. Is this something that can be added in the future or is this planned at some point?

**Comment by wenottingham** [comment]
@jladdjr is this covered in the ec2 inventory plugin?

**Comment by jladdjr** [comment]
[This ticket](https://github.com/ansible/ansible/issues/27800) is the only one I could find that tracks progress with enabling IPv6. Based on that ticket it's unclear whether the module works with IPv6 or not.

Will need to try running the plugin to see if the module supports this or not.

**Comment by ryanpetrello** [comment]
@jladdjr 

Seems like it would be pretty simple to test.  I've just made a new VPC that allocates from a public ipv6 block.  Make a VM in that VPC that isn't assigned a public IP automatically, then see if it can be imported into Tower as a host with the correct IPv6 address?

<img width="709" alt="image" src="https://user-images.githubusercontent.com/214912/78897769-ac928300-7a40-11ea-9fa3-cb216eb4d8c4.png">

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/214912/78897841-cf249c00-7a40-11ea-8ee8-668cb5a3bc79.png">

**Comment by ryanpetrello** [comment]
I tested this w/ @AlanCoding's branch which enables collections and it looks like it works to me:

![image](https://user-images.githubusercontent.com/214912/79900416-3137b680-83dc-11ea-814a-d3b3ba923604.png)

Here's a sync I just ran after launching this VM w/ *only* an IPv6 address:

![image](https://user-images.githubusercontent.com/214912/79901081-43662480-83dd-11ea-9537-473e06993b4d.png)

![image](https://user-images.githubusercontent.com/214912/79901151-62fd4d00-83dd-11ea-959b-15129ce4c9dd.png)

Seems like it imports fine to me.

**Comment by kdelee** [comment]
pending inventory plugins from collections feature merge

**Comment by AlanCoding** [comment]
just merged

**Comment by kdelee** [comment]
Can confirm, we are getting the ipv6 addresses w/ updates using the plugin now. Closing
