### ISSUE TITLE
Add support for JSON patch for the API 

### ISSUE THREAD

**Issue by IshwarKanse** [ansible/awx#6006]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Currently when updating a standalone field like AUTH_LDAP_ORGANIZATION_MAP, we have to provide the complete JSON document. With JSON patch we can express a sequence of operations to apply to a target JSON document.

**Comment by dapiced** [comment]
more info :

AWX or Tower need to accept The media type "application/json-patch+json"  not only "application/json" when we do a rest api http patch request

-----------
JSON Patch is part of RFC 6902. It is a standard designed to allow performing operations on JSON documents. JSON Patch can work with the HTTP PATCH method. It is useful to provide partial updates to JSON documents. The media type "application/json-patch+json" is used to identify such patch documents.
--------

**Comment by wenottingham** [comment]
This is not supported by our current REST framework, and so is not planned at this time.

**Comment by ryanpetrello** [comment]
Yea, what @wenottingham said - the framework that we utilize for our API (Django REST Framework) doesn't currently have support for this, so we're unlikely to do this in the near term:

https://github.com/encode/django-rest-framework/issues/1924
