### ISSUE TITLE
The authenticity of host 'master (192.168.122.100)' can't be established.

### ISSUE THREAD

**Issue by zhucaipeng** [ansible/awx#6008]
##### ISSUE TYPE
 - AWX issue ask for help

##### SUMMARY
The authenticity of host 'master (192.168.122.100)' can't be established.
ECDSA key fingerprint is SHA256:EJ3pwgaDLM/kgNOmGQZ/0aHBzHq8LH9ATvVuHOtHGrM.
ECDSA key fingerprint is MD5:ea:e0:b8:a9:3a:1d:8b:c5:90:e3:33:45:46:ee:94:c6.
Are you sure you want to continue connecting (yes/no)

##### ENVIRONMENT
* AWX version: 3.6.2
* AWX install method: ansible-tower-setup-latest.tar.gz
* Ansible version:  2.9.2
* Operating System: CentOS Linux release 7.7.1908 (Core)
* Web Browser: chrome

##### STEPS TO REPRODUCE

Run shell script in ansible playbook (shell module) by Ansible Tower. It stopped in "SUMMARY" above.

##### EXPECTED RESULTS

Ansible Tower can go on running.

**Comment by zhucaipeng** [comment]
remote user ansible is already configured to ssh without prompt password. Why still this issue happen ? Please give some advice to me. Thanks !

**Comment by ryanpetrello** [comment]
Hey @zhucaipeng,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
