### ISSUE TITLE
2097151k isn't enough for everyone (job event id overflow)

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#6010]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

The primary key for `main_jobevent` (and other event tables) is an `int`, which can only handle _at most_ 2B+ events before overflowing:

https://www.postgresql.org/docs/9.1/datatype-numeric.html

```
tower=# select max(id) from public.main_jobevent;
   max
------------
2147483647
```

##### STEPS TO REPRODUCE

Run very chatty playbooks very often across very many devices.

##### EXPECTED RESULTS

![cady-heron](https://media.giphy.com/media/4zQ5yigKckj5u/giphy.gif)

##### ACTUAL RESULTS

![pac-man-bug](https://media.giphy.com/media/DWtn59Up9b5GE/giphy.gif)

**Comment by ryanpetrello** [comment]
The most likely prescription here is to change this column to a `bigint`.  However, that comes with some questions:

- ~If you've already got hundreds of millions of rows, and we do this, how long does the `ALTER TABLE` take on modest hardware?~. **answer: too long**
- How much more disk space does this migration require when the indexes are recomputed?  Is it a reasonable amount/tradeoff?  Note that (in my opinion) this is mostly informational for the purpose of communicating/documenting large discrepancies; if 2B+ rows takes more disk space, you'll just...have to have more disk space 🤷‍♂.
- Does `int` vs `bigint` have a tangible performance impact for some of our more expensive queries against this table at scale (i.e., if you have a job with 100k rows, and then you migrate to `bigint`, are queries against that event set for e.g., the job detail view, notably slower?

**Comment by ryanpetrello** [comment]
Okay, I tested this out today to see what altering this table might look like at scale.  This is an `m5.2xlarge` (so, 8 cores, 32GB of RAM), and a large, high-IOPS disk (which is a requirement with this scale of data anyways).

```sql
awx=> SELECT COUNT(*) FROM main_job;
 count
--------
 750001
(1 row)

awx=> SELECT COUNT(*) FROM main_jobevent;
   count
-----------
 500000009
(1 row)
```

...and here's the migration I generated:

```python
+# Generated by Django 2.2.8 on 2020-02-20 20:05
+
+from django.db import migrations, models
+
+
+class Migration(migrations.Migration):
+
+    dependencies = [
+        ('main', '0108_v370_unifiedjob_dependencies_processed'),
+    ]
+
+    operations = [
+        migrations.AlterField(
+            model_name='jobevent',
+            name='id',
+            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_n>
+        ),
+    ]
```

I ran `awx-manage sqlmigrate`, and got the raw SQL and ran it:

```sql
[root@ip-10-10-0-23 ec2-user]# time psql -h localhost -U awx -f ./bigint.sql
Password for user awx:
BEGIN
```

```sql
awx=> SELECT query FROM pg_stat_activity WHERE state='active';
 SELECT query FROM pg_stat_activity WHERE state='active';
 ALTER TABLE "main_jobevent" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
(2 rows)

awx=> SELECT query FROM pg_stat_activity WHERE state='active';
```

...I'm still waiting 90+ minutes later.

So this *simpler* approach probably isn't viable 😞.

**Comment by kdelee** [comment]
I'm satisfied with the testing we did pre-merge and our upgrade testing should provide some indirect regression coverage. I am considering generating some more job events on the pre-upgrade box but that can happen out of band. Closing
