### ISSUE TITLE
Unable to run install.yml playbook due to below error

### ISSUE THREAD

**Issue by sksaddamhussain** [ansible/awx#6011]
###Below is the error while attempting run the command 'ansible-playbook -i inventory install.yml'

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/app1/setup/awx/installer/roles/local_docker/tasks/compose.yml': line 27, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- block:
    - name: Start the containers
      ^ here

**Comment by ryanpetrello** [comment]
What version of Ansible are you using to install?  Modern versions of AWX require 2.8 or greater.

https://github.com/ansible/awx/blob/devel/INSTALL.md#prerequisites

**Comment by sksaddamhussain** [comment]
issue got fixed after updating ansible to latest Thanks @ryanpetrello
