### ISSUE TITLE
Add tooltip support to VariablesField

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#6019]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Currently missing.

<img width="1423" alt="Screen Shot 2020-02-20 at 4 43 17 PM" src="https://user-images.githubusercontent.com/9889020/74981385-2a062380-5400-11ea-944c-47ffc54eb37a.png">

**Comment by unlikelyzero** [comment]
Covered in pull/5626
