### ISSUE TITLE
Feature Idea: Ability to override "LABEL" and "COLOR" Parameters for Tower/AWX's HipChat Notifications

### ISSUE THREAD

**Issue by saito-hideki** [ansible/awx#602]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

It would be better for users if they could create a single Notification Template per 'DESTINATION CHANNEL' and when enabling the notification in a job template, If users are able to override the defaults placed in the Notification Template.
When sharing the CHANNEL with multiple teams, it is useful to be able to overwrite LABEL and COLOR for each job the team runs.

##### ENVIRONMENT

* AWX version: 1.0.X

##### ADDITIONAL INFORMATION

- If it is able to overide within job template, users do not have to create multiple NOTIFICATION templates for the same HipChat channel.
- For Example UI (Just Idea) : TEMPLATES > %JOB_TEMPLATE% > NOTIFICATIONS > SUCCESS | FAILURE | 'NOTIFICATION LABEL' | 'NOTIFICATION COLOR'

**Comment by shanemcd** [comment]
RIP HipChat
