### ISSUE TITLE
The JSON payload received through webhook notifications has a null value for the friendly_name attribute

### ISSUE THREAD

**Issue by jmereaux** [ansible/awx#6028]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The JSON payload received through webhook notifications has a null value for the ``friendly_name`` attribute.

##### ENVIRONMENT
* AWX version: 9.1.0
* AWX install method: Kubernetes
* Ansible version:  2.8.5
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

- Create a WebHook notification
- Configure a job template to call the webhook notification on success / failure
- Run the job template
- Inspect the json payload received through the webhook

##### EXPECTED RESULTS

The JSON payload has the value `Job` or `Workflow Job` for the friendly_name attribute

##### ACTUAL RESULTS

The JSON payload has a null value for the friendly_name attribute

**Comment by ryanpetrello** [comment]
@jmereaux This variable is intended to be used as a description of what the job *is*.  I'm having trouble reproducing what you're describing in the latest version of AWX:

<img width="485" alt="image" src="https://user-images.githubusercontent.com/214912/76651409-dd16f800-653a-11ea-9617-987b7bf69874.png">

<img width="743" alt="image" src="https://user-images.githubusercontent.com/214912/76651305-9b864d00-653a-11ea-98a5-779e2bb5ec91.png">

<img width="684" alt="image" src="https://user-images.githubusercontent.com/214912/76651471-ff107a80-653a-11ea-8c4d-f5c8de273a97.png">

<img width="517" alt="image" src="https://user-images.githubusercontent.com/214912/76651505-0c2d6980-653b-11ea-824a-03297c7142d4.png">

<img width="492" alt="image" src="https://user-images.githubusercontent.com/214912/76651596-38e18100-653b-11ea-8fb4-91c65bf81194.png">


We _have_ recently fixed a number of bugs related to notification template support - you might want to upgrade and give this another shot on the latest version of AWX (currently, 9.3.0).
