### ISSUE TITLE
issue with running job

### ISSUE THREAD

**Issue by ghost** [ansible/awx#603]
##### ISSUE TYPE
 - Bug Report
 
##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
Hello guys, i have a job without valid project ( no playbook, because my url wrong ) and when i launch this project in job section i see that my job template is running, and i'm don't have ability to delete or terminate this, why? i wanna to force delete this job.i'm click on cancel button, the windows with (Are you sure you want to cancel the job below?) i'm click on ok and nothing changes.
job is still running

##### ENVIRONMENT
* AWX version 1.0.1.120
* AWX install method: , docker on linux
* Ansible version:  2.4.1.0
* Operating System: Ubuntu 16.04
* Web Browser: Mozila

##### STEPS TO REPRODUCE

set the wrong scm url to github and launch project

**Comment by AlanCoding** [comment]
> i have a job without valid project ( no playbook, because my url wrong ) and when i launch this project in job section i see that my job template is running

AWX has projects, which contain info about your source control, and these are updated by clicking the update button

job templates require a valid project (with a known playbook) plus inventory plus credential.

Is that entry in the JOBS tab you mention an update of your project, or a run of the job template? If you never got the playbooks from your project synced, then you couldn't have made a job template.

Could you share the standard out of the job / project update so we can have some diagnostic error info? Project updates, themselves, run a playbook, and this should have some verbosity about the invalid URL.

**Comment by matburt** [comment]
No comment in months, closing
