### ISSUE TITLE
dynamic ansible using CI/CD pipeline azure devops

### ISSUE THREAD

**Issue by onkarthg** [ansible/awx#6036]
hello team
 i am trying to deploy Dynamic taging ansible using ci/cd pipeline when adding ansible agent in ci/cd pipeline and select dynamic ansible after that adding tag for installation of particular software there is no any option. i m adding the document which i follow let me know any one have the solution for this.

refernce link-
https://docs.microsoft.com/en-us/azure/ansible/ansible-manage-azure-dynamic-inventories

**Comment by ryanpetrello** [comment]
Hey @onkarthg,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
