### ISSUE TITLE
LDAPs: Error when trying to connect to LDAP server only supporting TLS1.0

### ISSUE THREAD

**Issue by mmallet-digipok** [ansible/awx#6039]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
In our IT environment, the LDAP server only supports TLS1.0 ciphers. When configuring AWX 9.2.0 to use LDAPs, awx_web says the protocol is unsupported.

After a quick investigation, it seems that this behavior has been introduce with CentOS8 and can be easily fixed (see the additional information section).

I think however one should be able to select the crypo policies to apply on the system. We probably need an inventory variable for that (`crypot_policies` ?).

##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.3
* Operating System: CentOS 7
* Web Browser: Firefox 71
* LDAP server supported ciphers:
   ```
   $ nmap -p 636 --script +ssl-enum-ciphers <ldap server>
   ...
   PORT    STATE SERVICE
   636/tcp open  ldapssl
   | ssl-enum-ciphers:
   |   SSLv3:
   |     ciphers:
   |       TLS_RSA_WITH_3DES_EDE_CBC_SHA - strong
   |       TLS_RSA_WITH_AES_128_CBC_SHA - strong
   |       TLS_RSA_WITH_AES_256_CBC_SHA - strong
   |       TLS_RSA_WITH_DES_CBC_SHA - weak
   |       TLS_RSA_WITH_NULL_SHA256 - broken
   |       TLS_RSA_WITH_RC4_128_MD5 - strong
   |       TLS_RSA_WITH_RC4_128_SHA - strong
   |     compressors:
   |       NULL
   |   TLSv1.0:
   |     ciphers:
   |       TLS_RSA_WITH_3DES_EDE_CBC_SHA - strong
   |       TLS_RSA_WITH_AES_128_CBC_SHA - strong
   |       TLS_RSA_WITH_AES_256_CBC_SHA - strong
   |       TLS_RSA_WITH_DES_CBC_SHA - weak
   |       TLS_RSA_WITH_NULL_SHA256 - broken
   |       TLS_RSA_WITH_RC4_128_MD5 - strong
   |       TLS_RSA_WITH_RC4_128_SHA - strong
   |     compressors:
   |       NULL
   ```

##### EXPECTED RESULTS

One should be able to authenticate against the LDAP server.

##### ACTUAL RESULTS

No one can log in and the awx_web logs show this error:
```
2020-02-24 09:09:06,690 WARNING  django_auth_ldap Caught LDAPError while authenticating fx14318: SERVER_DOWN({'desc': "Can't contact LDAP server", 'info': 'error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol'},)
2020-02-24 09:09:06,700 WARNING  awx.api.generics Login failed for user *** from 172.20.0.3
```

##### ADDITIONAL INFORMATION

To fix, in awx_web container, type:
```
/usr/bin/update-crypto-policies --set LEGACY
```

The setting does not seem to be propagate without a reboot. The command must then be done at deployment time in `installer/roles/local_docker/tasks/compose.yml` after the " Update CA trust in awx_task container" task

**Comment by ryanpetrello** [comment]
@mmallet-digipok,

TLS 1.0 is deprecated - many Linux distributions and browsers either no longer support it, or will stop supporting it soon.

We're very unlikely to add changes to the installer to support enabling TLS 1.0 in CentOS 8, because people *should* upgrade and move forward to better crypto.  That said, if this is still a setup you still need as you transition, it sounds like you're on the right track with editing `installer/roles`.  You may also find this documentation on building your own AWX base image helpful:

https://github.com/ansible/awx/blob/devel/INSTALL.md#official-vs-building-images

**Comment by piellick** [comment]
hi @mmallet-digipok , i'm faced with same problem on redhat 8 and active directory. Is your workarounf working ? I have updated the role, kill the awx_web container and re-apply the playbook but now trouble with root cert .

`CONNECT_ERROR({'desc': 'Connect error', 'info': 'error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed (unable to get local issuer certificate)'},)
`

**Comment by adrime92** [comment]
Hi @mmallet-digipok, i´m facing similar issue. 

> django_auth_ldap Caught LDAPError while authenticating user: CONNECT_ERROR({'desc': 'Connect error', 'info': 'error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol'},)

Any idea what could be happening?

I'm trying to implement your workaround but i'm facing the following error: 

> bash-4.4$ /usr/bin/update-crypto-policies --set LEGACY
> Setting system policy to LEGACY
> rm: cannot remove '/etc/crypto-policies/back-ends/bind.config': Permission denied
> ln: failed to create symbolic link '/etc/crypto-policies/back-ends/bind.config': Permission denied
> Failed updating policies, are you root?

There is no root user in awx-web container, how did you manage to do that?

> bash-4.4$  cat /etc/passwd
> awx:x :1000:0:,,,:/var/lib/awx:/bin/bash

thx in advance!
