### ISSUE TITLE
Feature idea: LDAP Require Group to support nested groups

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#604]
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
 - LDAP Require Group currently only supports the group entered in this field, and not nested groups. Clients would like to see nested groups supported with this field.

##### ENVIRONMENT
* AWX version: any

**Comment by cchurch** [comment]
Nested groups *should be* supported if you configure `AUTH_LDAP_GROUP_TYPE` to one that supports nested group lookups. `AUTH_LDAP_REQUIRE_GROUP` and `AUTH_LDAP_DENY_GROUP` only check whether a user is a member of the specified group, which is dependent on the group type you select.

**Comment by matburt** [comment]
No further comments, so closing.

**Comment by muldertbb** [comment]
awx 1.0.7.2  

required groups don´t handle nesed groups. only flat user groups!

**Comment by rootchord** [comment]
So, just to clarify, if i map a team to an AD group, it CAN NOT handle users in nested groups that are members of that group? any AD group i use with ansible HAS to be flat(users only)?

**Comment by nfj25** [comment]
Just sharing some experiences... I was able to use nested groups in require group with NestedMemberDNGroupType.

**Comment by Harshal-20** [comment]
Can you please provide ldap group type parameters for using nested required group with type NestedMemberDNGroupType?  Thanks
