### ISSUE TITLE
Inventory Group Nested Hosts View errors with a 404

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#6049]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I searched for implemented issues and couldn't find anything.

/inventories/inventory/*num*/groups/*num*/nested_hosts isn't loading in ui_next
 
##### ENVIRONMENT
* AWX version: 9.next

##### STEPS TO REPRODUCE
1. Create an Inventory Group with nested hosts
2. View the #/inventories/inventory/*num*/groups/*num*/nested_hosts page

##### EXPECTED RESULTS
Nested Hosts to be displayed

##### ACTUAL RESULTS
404 messaging page

##### ADDITIONAL INFORMATION

<img width="1159" alt="Screen Shot 2020-02-25 at 9 10 38 AM" src="https://user-images.githubusercontent.com/12446869/75254948-29c6a900-57af-11ea-92c0-7d35dee281c6.png">

**Comment by dsesami** [comment]
Hosts page is blank and doesn't 404 when within a group. Note that adding hosts to this view remains unimplemented and is within the backlog: https://github.com/ansible/awx/issues/6143

**Comment by marshmalien** [comment]
The Inventory Group Host view has been broken up into the following smaller issues: 
Add new host form: #6142
Associate existing host modal: #6143
Disassociate host modal: #6150
