### ISSUE TITLE
Problem with postgres container activation.

### ISSUE THREAD

**Issue by akhilbatra898** [ansible/awx#605]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Unable to establish connection to Postgres during installation

##### ENVIRONMENT
* AWX version: 1.0.1-157-g8f62897
* AWX install method:  docker on linux
* Ansible version:  2.4.0.0
* Operating System: Ubuntu 16.04
* Web Browser: Chrome

##### STEPS TO REPRODUCE

In inventory 
Edit 

`post_gres_dir=local`

Then run

`ansible-playbook -i inventory install.yml`

##### EXPECTED RESULTS

Installation completes and able to access awx web portal

##### ACTUAL RESULTS

Installation completes while skipping Postgres container activation

`

TASK [local_docker : Wait for postgres and rabbitmq to activate] ******************************************************************************
Pausing for 15 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [localhost]

TASK [local_docker : Set properties without postgres for awx_web] *****************************************************************************
skipping: [localhost]

`

##### ADDITIONAL INFORMATION

On checking awx_task log

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: 	TCP/IP connections on port 5432?
127.0.0.1 | FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "unable to connect to database: could not connect to server: Connection refused\n\tIs the server running on host \"postgres\" (172.17.0.2) and accepting\n\tTCP/IP connections on port 5432?\n"
}

**Comment by matburt** [comment]
I'm not sure what `post_gres_dir=local` means

There is a variable called `postgres_data_dir` which needs to point to the absolute path where the postgres container will store it's data.
