### ISSUE TITLE
[Feedback] Collapse mechanism on sidebar nav is disruptive

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#6050]
##### SUMMARY

**WIP**

This is a collection of feedback from the bug bash.

"Sidebar is difficult to work with -- it shouldn’t have to be expanded since we’re using these items very regularly (especially resources, views, access)"

**Comment by jakemcdermott** [comment]
@unlikelyzero This is great feedback but it may be more actionable in one of the patternfly repos.

**Comment by unlikelyzero** [comment]
@jakemcdermott ok, let me label this is WIP and try to get some more structure to this

**Comment by mabashian** [comment]
The sidenav now defaults to an open state.  Will that be satisfactory?  Do we still need this issue @unlikelyzero?

**Comment by unlikelyzero** [comment]
@mabashian I think so. I'll close this for now but ask this in our next bug bash (where this was originally filed)
