### ISSUE TITLE
Page will crash if viewing Org Permission page in specific scenarios

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#6054]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
@dsesami updated w/ repro steps
Page will crash if viewing Org Permission page in specific scenario.

##### ENVIRONMENT
* AWX version: 9.next

##### STEPS TO REPRODUCE
1. Give a user Cred/Inventory/JT/Notification/Project/WF admin permissions (in other words, pretty much full permissions) 
2. As this normal user, try to make a new project and try to click the save button. The button did not work and I saw a 400 Bad Request when inspecting the Network tab in devtools. 
3. After this, if that same user goes to the Organization page for their org, and checks out the access/permissions tab, the entire page crashes.

##### EXPECTED RESULTS

Project saves normally, org access page does not crash.

##### ACTUAL RESULTS

Project does not save, org access page crashes.

**Comment by dsesami** [comment]
closed wrong issue in error; reopening, but testing this now.

**Comment by dsesami** [comment]
I can create a project normally as this user + the org page does not crash, and renders properly.
