### ISSUE TITLE
Add user page has rendering issues on some browsers

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#6055]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The Add User Page has rendering issues in some scenarios.
Note: I cannot reproduce this exactly

##### ENVIRONMENT
* AWX version: devel with 1d3bb97b0770e24fbabc64571379582ac671a255
* Operating System: MacOS Mojave
* Web Browser: Chrome Canary Version 82.0.4070.0 (Official Build)

##### STEPS TO REPRODUCE
TBD

##### EXPECTED RESULTS
1. Form fields to render correctly

##### ACTUAL RESULTS
1. Form fields rendered incorrectly

##### ADDITIONAL INFORMATION
<img width="719" alt="Screen Shot 2020-02-25 at 10 56 58 AM" src="https://user-images.githubusercontent.com/12446869/75265484-f8ee7000-57be-11ea-9565-915b2e7c887b.png">

**Comment by unlikelyzero** [comment]
@appuk i can't seem to reproduce this on chrome canary. Can you try this again?

**Comment by appuk** [comment]
@unlikelyzero I tried this again on a fresh instance and still see the issue:
![Screen Shot 2020-02-26 at 9 38 23 AM](https://user-images.githubusercontent.com/11617351/75355019-df5f2e00-587b-11ea-802a-45f5304ba5f4.png)

let me know if you have any issues in reproducing this

**Comment by unlikelyzero** [comment]
@appuk great! which chrome and os version, exactly?

**Comment by appuk** [comment]
OS: MacOS Mojave
Browser: Chrome Canary Version 82.0.4070.0 (Official Build)

**Comment by unlikelyzero** [comment]
we have coverage for this in the visualintegration/simple-flow.spec.js
