### ISSUE TITLE
Hoverover tooltip for username hovers over the Info button (which uses the same icon as tooltip)

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#6057]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
More of a piece of usability feedback. Hoverover tooltip for username hovers over the Info button (which uses the same icon as tooltip)

"Scroll over the username in top right corner, and you see a weird tooltip named user"

##### ENVIRONMENT
* AWX version: 9.2

##### STEPS TO REPRODUCE
1. Log in and hover over the username in the top right

##### EXPECTED RESULTS
1. Hoverover username tooltip message does not obscure the 'Info' icon element without contrast
-- or ---
2. Info icon element is not shared with other helper icons

##### ACTUAL RESULTS
1. Hoverover masked the info icon without a background contrast

##### ADDITIONAL INFORMATION
<img width="719" alt="Screen Shot 2020-02-25 at 10 56 58 AM" src="https://user-images.githubusercontent.com/12446869/75274124-432c1d00-57d0-11ea-912c-0b490485760c.png">

**Comment by unlikelyzero** [comment]
bumped again

**Comment by tiagodread** [comment]
Reported in `Platform 2.0 Testathon` still valid

**Comment by akus062381** [comment]
resolved
