### ISSUE TITLE
Latest version of the installer wipes the existing DB during an upgrade

### ISSUE THREAD

**Issue by alancivita** [ansible/awx#606]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

Latest version of the installer wipes the existing DB during an upgrade
##### ENVIRONMENT
* AWX version: 1.0.1.157
* AWX install method: docker on linux
* Ansible version:  2.4.0
* Operating System: centos
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Postgres has a persistent volume on /pgsql on local machine
docker stop all-existing -containers
docker rmi old-images
cd installer
ansible-playbook -i inventory install.yml

##### EXPECTED RESULTS

old data should be kept in place.
The pgsql container should use data from /pgdocker local direcotry, as declared in inventory file with postgres_data_dir=/pgdocker

##### ACTUAL RESULTS

Previous database is wiped despite the presence of /pgdocker directory (obviously the postgres_data_dir=/pgdocker has been set in inventory file)
##### ADDITIONAL INFORMATION

This used to work since latest pull.

**Comment by matburt** [comment]
I don't think it's wiped out, but you may need to follow the instructions here: https://github.com/ansible/awx/pull/535

It should be possible to attach postgres to the original directory to dump the data out and load it into a new AWX database deployment.

**Comment by beloniki** [comment]
Version AWX 1.0.3.41 still wipes database.
STEPS TO REPRODUCE: reboot machine.
Docker on linux.
Operating System: debian.
Ansible 2.4.3.0.

**Comment by beloniki** [comment]
[excellent](https://github.com/ansible/awx/pull/535#issuecomment-343338875) idea to store database in tmp directory
