### ISSUE TITLE
Add CompletedJob list to Host, InvHosts, and SmartInv views

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#6061]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
<img width="1339" alt="Screen Shot 2020-02-25 at 3 05 24 PM" src="https://user-images.githubusercontent.com/15881645/75283211-5f37ba80-57e0-11ea-9711-bfbb3532f9c6.png">

This issue tracks the addition of Completed Jobs tab to: 
* Host
* Inventory Host
* Smart Inventory

Columns:
1) Status/Name of job.  Links to `/#/jobs/:id`
2) Finish time of job
3) Relaunch button

The user should also be able to delete jobs from this list (rbac restricted)

Link to smart inventory mockup: https://tower-mockups.testing.ansible.com/patternfly/inventories/inventories-smart-detail/

**Comment by dsesami** [comment]
This is looking great. Selectors are also in place for E2E -- closing this issue out as complete.
