### ISSUE TITLE
Enforce python3 in "inventory" config file

### ISSUE THREAD

**Issue by nkadel** [ansible/awx#6064]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
RHEL 7 and similar systems pick up python2, which is very difficult to suppport, with "/usr/bin/env python" line in first line of "inventory" file.

##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method: docker on linux, docker
* Ansible version:  2.9.3
* Operating System: CentOS 7.7
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Install "docker-compose from EPEL, which uses python3
* sudo yum install /usr/bin/docker-compose

Use inventory file
* ansible-playbook -i inventory install.yml

##### EXPECTED RESULTS
Successful install baseed on "inventory"

##### ACTUAL RESULTS
Installation fails complaining about out-of-date docker-py.

**Comment by jakemcdermott** [comment]
Hi there. Thanks for creating this issue.The inventory file is a configuration file so you're free to change it locally to your liking before running the installer.
