### ISSUE TITLE
REST api job launch not setting requested credential

### ISSUE THREAD

**Issue by araghuraman123** [ansible/awx#6065]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When attempting to launch a job template over the REST api, the credential specified in the request is not getting set on the newly launched job.

##### ENVIRONMENT
* AWX version: 9.0.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.5
* Operating System: Linux
* Web Browser: N/A

##### STEPS TO REPRODUCE

POST to the api/v2/job_templates/id/launch and provide a 'credential' parameter with the numeric ID of the credential to supply to the job template. Samples -

(a) curl --silent --tlsv1.2 -f -k -H "Content-Type:application/json" -H "Accept:application/json" -XPOST -d '{"extra_vars":{"var1":"val1"}, "credential":4}' --user "user1":"pwd1" "https://awx-dev.com/api/v2/job_templates/81/launch/"

(b) curl --silent --tlsv1.2 -f -k -H "Content-Type:application/json" -H "Accept:application/json" -XPOST -d '{"extra_vars":{"var1":"val1"}, "credential":"cred1"}' --user "user1":"pwd1" "https://awx-dev.com/api/v2/job_templates/81/launch/"

##### EXPECTED RESULTS

The job thus launched will have the credential indicated in the request set on it.

##### ACTUAL RESULTS

The job is launched successfully when attempting (a) and (b), but without the specified credential set on it. The "extra_vars" are getting set as expected. The credential id/name specified does exist on the AWX instance. This works fine when launched through the UI itself.

This works with enterprise Tower v3.4.1 using "credential_id" as the attribute name. But that doesn't seem to work with awx either.

**Comment by araghuraman123** [comment]
Additional Info -

Template in question has ask_credential_on_launch set to true. Attempting to launch with "credentials" as a list results in a "400 Bad Request" error. Samples -

(a) curl --silent --tlsv1.2 -f -k -H "Content-Type:application/json" -H "Accept:application/json" -XPOST -d '{"extra_vars":{"var1":"val1"}, "credentials":[4]}' --user "user1":"pwd1" "https://awx-dev.com/api/v2/job_templates/81/launch/"

(b) curl --silent --tlsv1.2 -f -k -H "Content-Type:application/json" -H "Accept:application/json" -XPOST -d '{"extra_vars":{"var1":"val1"}, "credentials":["cred1"]}' --user "user1":"pwd1" "https://awx-dev.com/api/v2/job_templates/81/launch/"

**Comment by wenottingham** [comment]
```
curl --silent --tlsv1.2 -f -k -H "Content-Type:application/json" -H "Accept:application/json" -XPOST -d '{"extra_vars":{"var1":"val1"}, "credentials":[4]}' --user "user1":"pwd1" "https://awx-dev.com/api/v2/job_templates/81/launch/"
```

This is the correct syntax, I've tested it on devel and it works for me.

**Comment by araghuraman123** [comment]
It appears the invocation needs to also list the credential ids that are already saved on the template. Only then does AWX accept any additional credential ids supplied at run-time. So, if the template already has credentials 5 and 6 saved on it, then the curl should be -

curl --silent --tlsv1.2 -f -k -H "Content-Type:application/json" -H "Accept:application/json" -XPOST -d '{"extra_vars":{"var1":"val1"}, "credentials":[4,5,6]}' --user "user1":"pwd1" "https://awx-dev.com/api/v2/job_templates/81/launch/"

...and the job thus launched now has credential 4 set on it. Otherwise, the request is simply rejected with "400 Bad Request".

**Comment by araghuraman123** [comment]
Is this the expected behaviour? Or can this be remediated in future releases? 

Expected result would be for runtime credential choices to be simply added to the saved credentials on the template. Rather than having to supply the whole bunch for every invocation.

**Comment by wenottingham** [comment]
Attempting to 'merge' makes it ambiguous, and removes the ability to override a credential on the template with no credential at all. (Note: this is only supported for non-machine credentials)

**Comment by jakemcdermott** [comment]
The use case you're describing uses the no-longer-supported `credential` key. The example provided by @wenottingham would be the way to do this.

The replace vs merge behavior is by design and not something that is likely to change.
