### ISSUE TITLE
[Feedback] Hoverover tooltip actions become unusable when presenting

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#6066]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
This is an odd one, but when presenting, the hoverover tooltips become non-performant and almost unusable . I'm only filing this because I'm sure that this will be an issue when showing off the new UI in sales demos.

##### ENVIRONMENT
* AWX version: 9.next
* Operating System: fedora
* Web Browser: Chrome 80

##### STEPS TO REPRODUCE
1. Start bluejeans recording/presentation on a Fedora Red Hat laptop
2. Open the UI on a page with tooltips (i.e. /#/templates/job_template/add)
3. Hoverover tooltips

##### EXPECTED RESULTS
1. Tooltips to appear within 1 second of hoverover action

##### ACTUAL RESULTS
1. Tooltips take 3+ seconds to appear on hoverover action

##### ADDITIONAL INFORMATION
Need a video of this in action

**Comment by dsesami** [comment]
This should be resolved at the same time as #6067 in one PR. 

@kialam's advice: 

> you can control how fast the tooltips appear and disappear on mouse over and mouse out by passing it either the entryDelay and/or exitDelay prop.

**Comment by marshmalien** [comment]
The forms (i.e. /#/templates/job_template/add) should be displaying popovers instead of tooltips, so I think we can close this issue.

**Comment by unlikelyzero** [comment]
Covered in pull/5626
