### ISSUE TITLE
[Feedback] Clicking on a tooltip should open text triggered by a hoverover action

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#6067]
##### ISSUE TYPE
 - Bughancement

##### SUMMARY
[Feedback] Clicking on a tooltip should open text triggered by a hoverover action.

##### ENVIRONMENT
* AWX version: 9.next

##### EXPECTED RESULTS
Expect that when clicking on a tooltip icon, the tooltip text would appear instantly

##### ACTUAL RESULTS
Clicking on tooltip icon does not cause tooltip text to appear

**Comment by dsesami** [comment]
Linking with  https://github.com/ansible/awx/issues/6066

**Comment by unlikelyzero** [comment]
Covered in pull/5626
