### ISSUE TITLE
Console error thrown on organization access page

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#6070]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Console error thrown on organization access page. 

```react-dom.development.js:2460 Error: <filter> attribute width: Unexpected end of attribute. Expected length, "".```

##### ENVIRONMENT
* AWX version: 9.next

##### STEPS TO REPRODUCE
1. Navigate to /#/organizations/*num*/access

**Comment by marshmalien** [comment]
Possibly related: https://github.com/patternfly/patternfly-react/pull/3758

**Comment by mabashian** [comment]
Looks like the related upstream PR has been merged.  Should we needs_test this or close it? @unlikelyzero

**Comment by unlikelyzero** [comment]
No longer an issue and we have coverage for this page in organizations-tabs.spec.js
