### ISSUE TITLE
[Feedback] User should be able to type value in lookups

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#6073]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
A web ui user should not have to click on the magnifying glass icon in order to perform a lookup. Example: the Organization search field under the Create New User form only works if I click on the magnifying glass

In legacy awx, you could type the name of the resource

##### ENVIRONMENT
* AWX version: 9.next

##### ADDITIONAL INFORMATION
<img width="614" alt="Screen Shot 2020-02-25 at 5 16 25 PM" src="https://user-images.githubusercontent.com/12446869/75292637-92834500-57f2-11ea-80a9-2fb93e3fd68b.png">

**Comment by jlmitch5** [comment]
as this enhancement is for lookup fields inside forms (which we refer to as lookups) and not list search bar (which does allow you to type and click enter to create the search), I've updated the text of the issue.

**Comment by mabashian** [comment]
I think this is worth looking in to for an initial release.  I do agree that this would be very nice UX behavior.

**Comment by mabashian** [comment]
link https://github.com/ansible/awx/issues/6089 - there's a lot of overlap between these two issues IMO.  We could potentially address both with one set of changes.

**Comment by tiagodread** [comment]
Verified that:

single select lookup can be typed and find results properly
multiple select lookup keep working as is
all e2e tests are passing
