### ISSUE TITLE
[Feedback] Default Dashboard behavior is jarring for first time users of MVP

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#6074]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Because the dashboard is unimplemented with no placeholder, it is jaring for a first time user of the MVP. We should add a placeholder or something to inform the user that the view isn't built yet.

"Some Views are completely blank, such as Dashboard and My View. If my user doesn’t have access to view certain content, I’d posit that the least we could do is very explicitly show a message OR what the content should be like, but disabled?"

At the moment, it's just a blank screen with a console error:

##### ENVIRONMENT
* AWX version: 9.next
<img width="580" alt="Screen Shot 2020-02-25 at 5 18 26 PM" src="https://user-images.githubusercontent.com/12446869/75292876-13424100-57f3-11ea-85ae-fa67d85b27c8.png">

**Comment by mabashian** [comment]
Should we just close this @unlikelyzero?  We won't make ui_next the primary UI until we get the dashboard in place anyway.

**Comment by unlikelyzero** [comment]
@mabashian since the plan is to have a dashboard on the first iteration, this can be closed
