### ISSUE TITLE
Feature request:  TPAM as external vault in Ansible Tower

### ISSUE THREAD

**Issue by SWADESNA** [ansible/awx#6075]
##### ISSUE TYPE
 - Feature Idea
##### COMPONENT
 - UI
##### SUMMARY

- Feature request to include integrations for **Total Privileged Access Management** (TPAM) as secret management system with Ansible Tower.
##### STEPS TO REPRODUCE
- No steps needed as it's a feature request.

**Comment by LohitashwaIBM** [comment]
Is there a tentative timeline by which this feature will be addressed ?

**Comment by wenottingham** [comment]
No one is working on this at this time.

**Comment by LohitashwaIBM** [comment]
Is there a tentative timeline by which this feature will be addressed ? Or is there a way I can increase the priority of this feature to be considered for immediate action ?

**Comment by wenottingham** [comment]
Not at this time, no. This is the only request, and it's a closed source solution we cannot easily integrate with

Given that the product itself has been deprecated by the vendor (https://support.oneidentity.com/product-notification/noti-00000476), I would say we have no plans to add an integration here.

If you need this locally, you can follow the process here (https://github.com/ansible/awx/blob/devel/docs/credentials/credential_plugins.md#writing-custom-credential-plugins) to build your own integration.

**Comment by ryanpetrello** [comment]
Here are some more through instructions/examples on writing custom credential plugins:

https://github.com/ansible/awx/pull/6717
