### ISSUE TITLE
Smart Inventory with multiple host filter

### ISSUE THREAD

**Issue by defrancesco** [ansible/awx#608]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI
-API

##### ENVIRONMENT
* AWX version:AWX 1.0.0.312 
* AWX install method: docker on linux
* Ansible version:  Ansible 2.3.1.0
* Operating System:RHEL 7.x
* Web Browser:All

##### STEPS TO REPRODUCE

- Open the form to create a new smart inventory
- Add as host filter two hosts
![smart](https://user-images.githubusercontent.com/12048567/32691577-15584358-c70a-11e7-8ff8-6341d8084355.png)

- Save
- Open the smart inventory created before and go in the list of hosts
- You can see that the list is emty
- If you do the same actions with only one host in the host filter work fine 

##### EXPECTED RESULTS
Smart inventory with multiple hosts
##### ACTUAL RESULTS
I can add only one host 
##### ADDITIONAL INFORMATION
[](url)

**Comment by AlanCoding** [comment]
Could you please paste here the actual text that you entered into the UI to hit this bug? I don't know how you're adding the host, is it by the host name? Is it by some unique Ansible fact? The actual request data submitted would also be helpful, if you can get that.

Thanks!

**Comment by defrancesco** [comment]
Hi
Yes I add the hostname  below a screeshot for one host is ok but for two no
[image: Immagine incorporata 1]

Regards
Giuseppe

2017-11-10 16:36 GMT+01:00 Alan Rominger <notifications@github.com>:

**Comment by AlanCoding** [comment]
I can't see the image, it's just marked as "[image: Immagine incorporata 1]", probably because github doesn't automatically move email attachments to attachments on the issue. I do get emails from github on issues I participate in, but it is not present there either.

**Comment by defrancesco** [comment]
Added the image on my comment on github

Thanks
Giuseppe

2017-11-10 18:29 GMT+01:00 Alan Rominger <notifications@github.com>:

**Comment by AlanCoding** [comment]
In your screenshot, the two hosts are combined with AND logic. I don't know of any way to combine two terms with OR logic in the UI. But you can do it in the API

https://github.com/ansible/awx/blob/bfea00f6dc6af0fb01057ce38e9d0337e6c589aa/awx/api/templates/api/host_list.md#L3

Example, replicating your syntax: `/api/v2/hosts/?order_by=name&page_size=5&inventory__organization=1&host_filter=search=HostSmart01%20or%20search=HOstSmart02`.

You could use the API browser to create a smart inventory with the OR logic. Does that solve your immediate problem? I'd imagine that support for this is on the UI roadmap eventually.

**Comment by defrancesco** [comment]
Hi
Yes this support is for the UI because now the UI allow to add more than
one host in the host filter, but the system accept only one.
If you add more host in the host filter you will have a smart inventory
with hosts empty.
Anyway with API is ok for me and I will test it as soon as, but I think you
have to test better all cases about smart inventory.

Thanks for your support
Regards
Giuseppe


2017-11-13 21:49 GMT+01:00 Alan Rominger <notifications@github.com>:

**Comment by defrancesco** [comment]
Hi,

I am finding the table in the DB where all playbook changes and stdout are
stored, can you help me? Which is the table on PostGres where all plybook
stdout are stored?

Thanks
Giuseppe

2017-11-10 16:44 GMT+01:00 Giuseppe De Francesco <defrancescorm@gmail.com>:

**Comment by matburt** [comment]
closing since there is a work around. Other questions not related to this issue should be addressed to IRC or mailing list.

**Comment by defrancesco** [comment]
Hi,

I am finding the table in the DB where all playbook changes and stdout are
stored, can you help me? Which is the table on PostGres where all plybook
stdout are stored? See below image

[image: Immagine incorporata 1]

Thanks
Giuseppe



Thanks
Giuseppe

2017-11-10 16:36 GMT+01:00 Alan Rominger <notifications@github.com>:

**Comment by ryanpetrello** [comment]
@defrancesco if you're encountering a new problem, please file a new issue with details at: https://github.com/ansible/awx/issues/new

If you've got a more general question about awx and how it works, try the mailing list or our IRC room on freenode: https://github.com/ansible/awx#get-involved
