### ISSUE TITLE
Duplicate switches, buttons, etc. on hosts list

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#6085]
##### ISSUE TYPE
 - Bug Report

##### STEPS TO REPRODUCE
- sign in as an admin user
- create an inventory
- add a host to that inventory
- navigate to hosts list

##### EXPECTED RESULTS
One on/off toggle, one edit button.

##### ACTUAL RESULTS
![Screenshot from 2020-02-26 12-58-30](https://user-images.githubusercontent.com/9753817/75373496-6b7f4e80-5898-11ea-9deb-55fb2efc732f.png)

**Comment by dsesami** [comment]
There is only one toggle and edit button and one toggle and edit button and one toggle and edit button. :laughing:
