### ISSUE TITLE
Project form doesn't show organization when it is defined

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#6086]
##### ISSUE TYPE
 - Bug Report

##### STEPS TO REPRODUCE
- create an organization
- create a project that uses that organization
- open the edit form for the project

##### EXPECTED RESULTS
The project's organization should be shown as the current value on the `Organization` field.

##### ACTUAL RESULTS
The organization field is blank.

##### ADDITIONAL INFORMATION
![project_no_org](https://user-images.githubusercontent.com/9753817/75375903-1265e980-589d-11ea-9e88-d597903d63c7.gif)

**Comment by dsesami** [comment]
Organization renders normally on the project form, no apparent issues. :+1:
