### ISSUE TITLE
Organization fields (and similar fields) should respond to clicks on the field itself.

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#6089]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Here is an example of the field I'm discussing:
![Screenshot from 2020-02-26 14-28-13](https://user-images.githubusercontent.com/19942822/75380773-a2a82c80-58a5-11ea-892f-abf68456f137.png)

When you click the magnifying glass, a modal appears which lets you choose an organization from the list. Clicking the field itself, however, does not let you edit it in any way. In fact, clicking the field itself does nothing at all. This issue is about making the field do _something_, whether that means opening the modal or something else.

Two parts:
- Confirming that this design does not go against PF design rules (and if it does, seeing what we can do as an alternative or appeal to change the design, because it seems like a limitation)
- Making the change itself so the field responds.

**Comment by jakemcdermott** [comment]
my opinionated and probably wrong list of possible approaches:

- short-term: open the modal when the input area is clicked

- long-term / never: debounced fuzzy search-by-name w/ selectable tags. I think this would be a lot of work, but awesome given how many lookups we have.

- a better idea if you have one

**Comment by mabashian** [comment]
link https://github.com/ansible/awx/issues/6073

**Comment by dsesami** [comment]
I'm upping the priority to medium as this feels like it really should be included :)

**Comment by mabashian** [comment]
I don't think we need this if we do #6073.  I'm going to mark this as blocked until we decide what to do about that other issue.  I think it'd be better UX to be able to type into this field.

**Comment by dsesami** [comment]
@mabashian I am of the opinion that this is actually a dupe of #6073, which offers a direct solution. :) I'll close it and you can address it there. Making the field type-able is a good idea.
