### ISSUE TITLE
Saving Configuration in UI Fails w/ Errors

### ISSUE THREAD

**Issue by canit00** [ansible/awx#609]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Just deployed awx on OCP 3.5 following this [guide](https://developers.redhat.com/blog/2017/10/16/guide-starting-use-awx-top-openshift-upstream-red-hat-ansible-tower/) and now attempting to set up LDAP / AD. When we click save the page refreshes & the filled in boxes stay, however, if you browse to another area data in the fields is lost.

##### ENVIRONMENT
* AWX version: AWX 1.0.1.157
* AWX install method: openshift
openshift v3.5.5.31
kubernetes v1.5.2+43a9be4
* Ansible version: Ansible 2.4.1.0
* Operating System: Red Hat Enterprise Linux Server release 7.3 (Maipo)
* Web Browser: 
Mac OS X 10_12_6 Chrome/61.0.3163.100
Mac OS X 10.12 Firefox/56.0

##### STEPS TO REPRODUCE
Log in with default admin / password > settings > authentication > subcategory LDAP > fill in text fields > click save.

##### EXPECTED RESULTS
Expected settings to be saved.

##### ACTUAL RESULTS
Paged refreshed however data in fields is not saved if you browse to another section in awx.

##### ADDITIONAL INFORMATION
Please note, that we do not have any external load balancers in front of OCP, other than using the native HAProxy.

See the following errors in the logs
>2017/11/10 16:57:24 [error] 39#0: *39 connect() failed (111: Connection refused) while connecting to upstream, client: 10.1.0.1, server: _, request: "PATCH /api/v2/settings/all/ HTTP/1.1", upstream: "uwsgi://[::1]:8050", host: "awxui.openshift.server.com", referrer: "http://awxui.openshift.server.com/"
2017/11/10 16:57:24 [warn] 39#0: *39 upstream server temporarily disabled while connecting to upstream, client: 10.1.0.1, server: _, request: "PATCH /api/v2/settings/all/ HTTP/1.1", upstream: "uwsgi://[::1]:8050", host: "awxui.openshift.server.com", referrer: "http://awxui.openshift.server.com/"
2017-11-10 16:57:24,957 WARNING  awx.api.generics status 400 received by user admin attempting to access /api/v2/settings/all/ from 10.1.0.1
[pid: 34|app: 0|req: 1/22] 10.1.0.1 () {60 vars in 3571 bytes} [Fri Nov 10 16:57:24 2017] PATCH /api/v2/settings/all/ => generated 54 bytes in 439 msecs (HTTP/1.1 400) 7 headers in 248 bytes (1 switches on core 0)
10.1.0.1 - - [10/Nov/2017:16:57:24 +0000] "PATCH /api/v2/settings/all/ HTTP/1.1" 400 65 "http://awxui.openshift.server.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" "167.209.70.250"
error: unexpected EOF

Working on gathering and making all logs available.

**Comment by canit00** [comment]
memcached logs empty. Attaching all other pod logs.

[postgresql_log_description.txt](https://github.com/ansible/awx/files/1462269/postgresql_log_description.txt)
[awx-celery.log](https://github.com/ansible/awx/files/1462266/awx-celery.log)
[awx-rabbit.log](https://github.com/ansible/awx/files/1462265/awx-rabbit.log)
[awx-3303925813-description.txt](https://github.com/ansible/awx/files/1462264/awx-3303925813-description.txt)
[awx-web.log](https://github.com/ansible/awx/files/1462263/awx-web.log)

**Comment by matburt** [comment]
That guide is not an official AWX install guide, please follow the Openshift install instructions found in our INSTALL.md
