### ISSUE TITLE
Update list select all to include dropdown with options

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#6092]
A couple updates to the list toolbar:
- Utilize icon-based action buttons for add/delete
- Move multi-select checkbox to be based off of their bulk select demo (https://www.patternfly.org/v4/documentation/react/demos/bulkselecttable)

For bulk select, there is a slight difference, sense we only have two options, not a third select all (across pages) option, it didn't really make sense to make it a dropdown, as the toggle toggles between the two options.

This work is sitting in a branch here right now:  https://github.com/jlmitch5/awx/tree/toolbar220Updates

![Screen Shot 2020-02-25 at 4 13 38 PM](https://user-images.githubusercontent.com/1342624/75387355-38958480-58b1-11ea-9bfa-0ba2829fd5ea.png)
![Screen Shot 2020-02-25 at 4 14 01 PM](https://user-images.githubusercontent.com/1342624/75387356-38958480-58b1-11ea-9eec-9dd51359b18a.png)
![Screen Shot 2020-02-26 at 1 59 57 PM](https://user-images.githubusercontent.com/1342624/75387357-38958480-58b1-11ea-8c8b-257d9e0a0d3d.png)
![Screen Shot 2020-02-26 at 1 59 45 PM](https://user-images.githubusercontent.com/1342624/75387358-392e1b00-58b1-11ea-96b2-69b318d1a066.png)
![Screen Shot 2020-02-25 at 4 28 06 PM](https://user-images.githubusercontent.com/1342624/75387359-392e1b00-58b1-11ea-9688-18a7d18dcf60.png)

**Comment by jlmitch5** [comment]
@wenottingham trying to figure out if this is wanted for 4.0.

Currently we utilize the textual-buttons, and a non-labeled checkbox.

The design is implemented in that branch, what is left is moving the various list to pass the correct props for being able to show the # selected label (current page size, and current selected size), as well as deleting the isAllSelected prop (as in that branch we now use if current page size === current selected size to indicate the checked state)

**Comment by wenottingham** [comment]
If the icon-based buttons match both a) pre-PF Tower b) other PF apps, we should do that.

**Comment by nixocio** [comment]
As per feedback from @trahman73.

> You can ignore the icon based action buttons part.

**Comment by mabashian** [comment]
I can't find this checkbox pattern anywhere in the current PF docs.  @trahman73 or @marshmalien do y'all know if the select all checkbox is something we still want to change?  If not, we should close this issue.

**Comment by trahman73** [comment]
@mabashian We want to move to using this select pattern.
Guidelines: https://www.patternfly.org/v4/guidelines/bulk-selection
Component: https://www.patternfly.org/v4/components/dropdown/react#split-button-with-text
