### ISSUE TITLE
Deleting a host gives a Not Found error

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#6095]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Deleting a host gives a Not Found error. It is bringing to the inventories page for some reason while it should bring you back to the host list page. 

##### ENVIRONMENT
* AWX version: 9.next

##### STEPS TO REPRODUCE
1. Go to Resources > Host page
2. Create a host
3. After creating the host and being on the details page for that host, hit delete.

##### EXPECTED RESULTS
Host deleted and returned to host list

##### ACTUAL RESULTS
404 error on same resource

##### ADDITIONAL INFORMATION
<img width="624" alt="Screen Shot 2020-02-26 at 4 19 47 PM" src="https://user-images.githubusercontent.com/12446869/75388985-d427f480-58b3-11ea-982e-6e5d6a697745.png">

**Comment by dsesami** [comment]
Deleting a host redirects you to the host lists page. Deleting a host while within the context of the inventory view redirects you to the hosts list for that inventory. :+1:

**Comment by unlikelyzero** [comment]
tests added to https://github.com/ansible/tower-qa/pull/4806
