### ISSUE TITLE
[Feedback] Options information on details view(s) can be confusing

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#6097]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Options information for a project is confusing

##### ENVIRONMENT
* AWX version: 9.next

##### STEPS TO REPRODUCE
1. Add options to a Project like clean after checkout
2. View Project's Details view

##### EXPECTED RESULTS
nonfunky text

##### ACTUAL RESULTS
funky bulletpoints

##### ADDITIONAL INFORMATION

<img width="652" alt="Screen Shot 2020-02-26 at 4 32 02 PM" src="https://user-images.githubusercontent.com/12446869/75390015-890ee100-58b5-11ea-9829-a3da4a886b0a.png">

**Comment by mabashian** [comment]
Perhaps we should rename the label to `Enabled Options`.  There definitely should not be bullet points in this field.  We don't show bullet points on the JT details view:

<img width="657" alt="Screen Shot 2020-09-28 at 10 11 28 AM" src="https://user-images.githubusercontent.com/9889020/94443304-ff88ff80-0172-11eb-92d9-67309dcae87f.png">

**Comment by mabashian** [comment]
This also appears in the launch summary view

**Comment by tiagodread** [comment]
For credentials details, we are displaying the `Options` key even if there is no option enabled, look: 

![image](https://user-images.githubusercontent.com/12464858/116248461-47402b80-a742-11eb-89ea-4d5f1d477c2a.png)

If we change that label to `Enabled Options`, we might want to display a value like `Enabled Options: none`

**Comment by mabashian** [comment]
@tiagodread I think `Enabled Options` should be hidden if there are no enabled options.  I'll fix this while I'm in here.

**Comment by akus062381** [comment]
resolved
