### ISSUE TITLE
Unable to create a WFJT from a Project's Add Job Template tab

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#6100]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Not able to create a Workflow Job Template from the Project’s Job Templates tab. Steps:

##### ENVIRONMENT
* AWX version: 9.next

##### STEPS TO REPRODUCE

1. Visit a project’s detail and click on the Job Templates tab
2. Try to add a new Workflow Template by pressing the `+` button
Note Workflow Not Found Error

##### EXPECTED RESULTS
Add WFJT Page

##### ACTUAL RESULTS
Error Page

##### ADDITIONAL INFORMATION

<img width="557" alt="Screen Shot 2020-02-26 at 5 30 40 PM" src="https://user-images.githubusercontent.com/12446869/75394249-bb244100-58bd-11ea-80a7-7b69d3df14cd.png">

**Comment by AlexSCorey** [comment]
I cannot reproduce this bug and I think it may have been resolved already.  Putting it in needs test for confirmation.

**Comment by unlikelyzero** [comment]
@AlexSCorey fixed!
