### ISSUE TITLE
When Provisioning Callbacks checkbox is selected on JT Add/Edit Form, Host Config Key field is in a bad spot

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#6101]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When Provisioning Callbacks checkbox is selected, Host Config Key field is in a bad spot

##### ENVIRONMENT
* AWX version: 9.next
* OS / Browser version: Ubuntu 18.04 + Firefox nightly

##### STEPS TO REPRODUCE
1. Navigate to JT Add/Edit Form
2. Select the Provision Callbacks checkbox
Note the location of the Host Config Key

##### EXPECTED RESULTS
Host Config Key box to be contained without obscuring other elements on screen

##### ACTUAL RESULTS
Host Config Key box is obscured by Save and Cancel buttons

##### ADDITIONAL INFORMATION

<img width="628" alt="Screen Shot 2020-02-26 at 5 35 31 PM" src="https://user-images.githubusercontent.com/12446869/75394605-7cdb5180-58be-11ea-834e-82f46b0dd1ba.png">

**Comment by mabashian** [comment]
This looks different now:

<img width="1382" alt="Screen Shot 2020-09-28 at 10 12 36 AM" src="https://user-images.githubusercontent.com/9889020/94443430-2a735380-0173-11eb-9bb9-745f0f975dc6.png">
