### ISSUE TITLE
At certain resolutions, JT Advanced Form elements render outside of background

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#6103]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Job template options render outside of the “box” on small browsers

##### ENVIRONMENT
* AWX version: 9.next
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System: Ubuntu 18.04
* Web Browser: Firefox Nightly

##### STEPS TO REPRODUCE
1. Open JT Add/edit Form at a narrow window resolution
2. Open Advanced options
Note the location of the advanced form elements

##### ADDITIONAL INFORMATION
<img width="651" alt="Screen Shot 2020-02-26 at 5 42 10 PM" src="https://user-images.githubusercontent.com/12446869/75394965-55d14f80-58bf-11ea-9f65-0a2524910162.png">

**Comment by unlikelyzero** [comment]
note: we need to add coverage to visual regression testing here

**Comment by mabashian** [comment]
The Advanced section no longer exists.  Lets re-test this.
