### ISSUE TITLE
Column staggering on unified jobs lists

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#6107]
##### ISSUE TYPE
 - Bug Report

##### STEPS TO REPRODUCE
- have a few jobs with varied permissions and job types

##### EXPECTED RESULTS
- columns are aligned

##### ACTUAL RESULTS
![Screenshot from 2020-02-27 09-21-12](https://user-images.githubusercontent.com/9753817/75453870-8efed380-5942-11ea-8618-ed32c404abbb.png)

**Comment by dsesami** [comment]
Staggering is removed, the page is aligned on varied types of jobs.
![Screenshot from 2020-03-09 10-22-13](https://user-images.githubusercontent.com/19942822/76221747-e842ee80-61ef-11ea-8c68-619015e7ad96.png)
