### ISSUE TITLE
Feature: User Story 1: "As an operator I want to visualize the connected network that I have imported into AWX as an inventory so I can understand Ansible playbooks behind the scenes"

### ISSUE THREAD

**Issue by abenokraitis** [ansible/awx#611]
The following feature assumes an inventory is known, and already imported into AWX.

- [x]  Inventory available in toolbox (not organized), not on canvas
- [x]  Define links (via inventory script)
- [x]  Organize the canvas manually using drag-and-drop from the toolbox
- [x]  Provide example inventory scripts
- [ ]  ... include usage of inventory scripts into documentation (@tvo318)
- [ ] Create User Guide documentation from (@benthomasson) Acceptance Docs (@tvo318)
- [x] Export the data on the diagram as SVG and YAML through API for playbooks to consume
- [x] Show links and show interface names

Updated April 3, 2018.

**Comment by abenokraitis** [comment]
Moved into description.

**Comment by shanemcd** [comment]
RIP network UI
