### ISSUE TITLE
Change search filter chips to show label rather than value

### ISSUE THREAD

**Issue by keithjgrant** [ansible/awx#6111]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
In a search filter with a dropdown of options (e.g.: Inventory Source Sync in workflow node), the search options are defined by sets of values + labels. The labels show in the dropdown, but the values are shown in the selected chips.

For example, in the following screenshot, chips should read "Amazon EC2", "Manual", and "File, Directory, or Script":

![Screen Shot 2020-02-26 at 3 29 00 PM](https://user-images.githubusercontent.com/410794/75477899-d771bd80-5951-11ea-99bb-dee6557b4521.png)

Change these chips to display the more human-readable label instead of the API value.

**Comment by jlmitch5** [comment]
this has been tested and merged, closing (cc @dsesami just for a heads up)
