### ISSUE TITLE
Update relevant credential form fields from text area to file picker

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#6113]
the File Picker component is slated for the early March release of PF-react.  Once it is released, we should update the text area based fields (private and public SSH key) to this component.

**Comment by marshmalien** [comment]
PatternFly File Upload: https://www.patternfly.org/v4/documentation/react/components/fileupload

**Comment by mabashian** [comment]
Marking this as blocked until we upgrade PF - unless I'm mistaken and we already have access to this.  I'm thinking about bringing us up to the latest PF early next week.

**Comment by jlmitch5** [comment]
I believe this is now merged in PF-react so can be done, though I'm not sure if we want to tackle this after we move to the more generator based cred form creation or not.

**Comment by mabashian** [comment]
This can probably be combined with https://github.com/ansible/awx/issues/6703

**Comment by dsesami** [comment]
@unlikelyzero is this good to close as we tested file upload?

**Comment by unlikelyzero** [comment]
🎉
