### ISSUE TITLE
AWX Collection user and role modules break when creating or updating an existing object

### ISSUE THREAD

**Issue by squidboylan** [ansible/awx#6128]
##### ISSUE TYPE
 - Bug Report

#### Collection
Updating an object without a `name` field breaks, which also breaks idempotency. Probably because of: https://github.com/ansible/awx/blob/devel/awx_collection/plugins/module_utils/tower_api.py#L534

##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.4
* Operating System: ubuntu 18.04

##### STEPS TO REPRODUCE

Run a playbook that creates a user or role twice, the second time it will fail

##### EXPECTED RESULTS

it should be Idempotent and know how to update those objects

##### ACTUAL RESULTS

```
  PLAY [testhost] ****************************************************************

  TASK [Gathering Facts] *********************************************************
  ok: [testhost]

  TASK [tower_user : Create a User] **********************************************
  fatal: [testhost]: FAILED! => {"changed": false, "msg": "Unable to process update of item due to missing data 'name'"}

  PLAY RECAP *********************************************************************
  testhost                   : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```

**Comment by beeankha** [comment]
This is now fixed for the `tower_user` module per PR https://github.com/ansible/awx/pull/6237.  

`tower_role` is currently blocked from being converted off of `tower-cli`, but this issue will be addressed for that module once that conversion is unblocked.
