### ISSUE TITLE
Information Request - OS Support

### ISSUE THREAD

**Issue by FenixVale** [ansible/awx#6135]
##### ISSUE TYPE
 - Information Request

##### SUMMARY
I haven't been able to find a definitive answer on this. Since AWX is just the upstream variant of Ansible Tower, I wanted to confirm whether AWX still supports Ubuntu as a distribution choice for deployment, despite Tower no longer supporting it.

I ask since CentOS was currently my choice for deploying, but has proven to be exceptionally more of a pain in the ass to get running than when I used Ubuntu for similar things.

**Comment by jakemcdermott** [comment]
AWX deployments run on docker or kubernetes so there isn't really a specific distro needed on the machine you deploy it to.

If you're using the [docker-compose](https://github.com/ansible/awx/blob/devel/INSTALL.md#docker-compose) installation method, just make sure the host meets all the pre-reqs listed in the documentation.
