### ISSUE TITLE
Instructions on using an isolated node issue

### ISSUE THREAD

**Issue by sravany616** [ansible/awx#6139]
##### ISSUE TYPE
 Please provide step by step procedure to configure isolated node as per "Instructions on using an isolated node" https://github.com/ansible/awx/tree/devel/tools/docker-isolated

##### SUMMARY
https://github.com/ansible/awx/tree/devel/tools/docker-isolated does not have proper procedure to configure isolated node which can understand by beginner. Please help with a documentation which can understand by a beginner. 

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by ryanpetrello** [comment]
@sravany616 containerized AWX installs don't support isolated node execution:

https://github.com/ansible/awx/issues/1207

**Comment by sravany616** [comment]
Can you please provide the documentation to install AWX that supports isolated node configuration.

**Comment by ryanpetrello** [comment]
@sravany616 

There _are_ no instructions; it isn't supported in the AWX installer.

If we add support at some point, the work will be tracked at:

https://github.com/ansible/awx/issues/1207
