### ISSUE TITLE
Dashboard: hover over Job Status graph doesn't update popup

### ISSUE THREAD

**Issue by jpmens** [ansible/awx#614]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Hovering or clicking on the Job Status graph in Dashboard brings up a small panel with counts; that used to update when moving along the graph but it no longer does since a few weeks.

![jmbp-4136](https://user-images.githubusercontent.com/60706/32690982-9d4488d0-c700-11e7-826f-42c060d93d88.jpg)

##### ENVIRONMENT
* AWX version: 1.0.1.167
* AWX install method: docker on linux
* Ansible version:  2.4.0.0
* Operating System: CentOS 7.3
* Web Browser: Safari (OS/X), Chrome (OS/X)

##### STEPS TO REPRODUCE

In dashboard, click on the graph. (see screenshot above)

##### EXPECTED RESULTS

Counts should update when moving along the graph

##### ACTUAL RESULTS

Popup neither moves nor are job counts changed

**Comment by gconsidine** [comment]
Thanks, @jpmens. We've identified it as being an issue with the version of a dependency we're including. I'm working on a fix now. Shouldn't be too long, I don't think.
