### ISSUE TITLE
Inventory Group Nested Hosts - Add New Host Form

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#6142]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

* Create route and form for a new inventory group host
* Hook route up to inventory group host list "Add New Host" dropdown item
* Cancel navigates back to inventory group host list
* Save navigates to inventory host detail 
* Error Handling
* I18n

Pathname: `/inventories/:inventory_type/:inventory_id/groups/:group_id/nested_hosts/add`
Breadcrumb: Inventories / Inventory Name / Groups / Group Name / Hosts / Create New Host

Form Fields: 
* Name - required
* Description 
* Variables

<img width="1345" alt="Screen Shot 2020-03-03 at 12 08 31 PM" src="https://user-images.githubusercontent.com/15881645/75800531-b7723d80-5d47-11ea-821c-88201a4a1bc7.png">

**Comment by appuk** [comment]
verified the navigations, form and field validation and everything looks good, hence closing the issue
