### ISSUE TITLE
Inventory Group Nested Hosts - Associate Existing Host Modal

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#6143]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Inventory Group Nested Host List: 
* Show host association modal when a user clicks to add an existing host from dropdown
* Multi-select host list
* Save and Cancel returns user to inventory group host list view
* Error handling  - Alert modal?

Old UI for reference:
<img width="876" alt="Screen Shot 2020-03-03 at 12 21 16 PM" src="https://user-images.githubusercontent.com/15881645/75801755-a32f4000-5d49-11ea-938e-b160f39acca6.png">

**Comment by appuk** [comment]
working as expected, hence closing the issue
