### ISSUE TITLE
credential types can be missing from template credential multiselect

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#6151]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
- Make a few custom credentials.
- Navigate to JT and look for missing cred types in the multicredential lookup.

In the example below, the vault credential type is missing.
![novault](https://user-images.githubusercontent.com/9753817/75817654-8a348800-5d65-11ea-8898-ea145c305a2d.gif)

**Comment by dsesami** [comment]
All custom and included credential types were visible on both add and edit forms on JTs.
