### ISSUE TITLE
Show the actual ansible command being run

### ISSUE THREAD

**Issue by emad-ramlawi** [ansible/awx#6153]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Hi, I tried to making Verbose level 5 to show more output, I wish to see the actual ansible command getting run and not just the output of it.

Many thanks.

**Comment by ryanpetrello** [comment]
Hey @emad-ramlawi,

The job output UI doesn't display this, but it's easy to view from the API itself:

`/api/v2/jobs/N/`

![image](https://user-images.githubusercontent.com/214912/75824144-fec0f400-5d70-11ea-8fee-374a2ff21878.png)
