### ISSUE TITLE
Feature: User Story 5: "As an operator I want to automatically generate a layout of my network so that I do not have to manually organize the network on the canvas."

### ISSUE THREAD

**Issue by benthomasson** [ansible/awx#616]
For large networks manually organizing the canvas can be tedious.  Provide a method to attempt to automatically layout the network given some hints about the network type and the connectivity of the network.   

In general this is a hard problem that might not have a good solution as network engineers add meaning to their diagram by placing certain devices in proximity to other devices which may or may not be connected with physical links.  This is not a replacement for drag-and-drop organization, but a tool to help with an initial layout of a network or parts of a network that are not already organized. 

- [ ] Organize it via a “Layout” button (connect it up, facts, services?)
- [ ]  The tool (or the user) will try to determine (or assist) in the type of network topology for use for placement/rendering
- [ ]  The more hints provided by the user the better (from facts, type information, host vars)
Start with a “ring” and then update better?? OR the user specifies the type of topology via host_vars (metadata)

**Comment by sumkincpp** [comment]
:+1: for this feature.

Some ideas :
- Maybe it's better to have several network layouts for single inventory(not one) based on filters
   - device on/off in inventory or it's `disabled` property in `ansible_topology` subtree
   - groups based display, i.e. leafs at the top, spines at the bottom, twenty in a row
   - inventory based/facts based
- Final layout is achieved through selecting topology type(ring/auto/groups based auto/etc) and some manual optimizations

**Comment by shanemcd** [comment]
RIP network UI
