### ISSUE TITLE
Resource lists labeling

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#6160]
##### ISSUE TYPE
- Feature request

##### SUMMARY
For example, here is the projects list:
![Screenshot from 2020-03-04 09-14-58](https://user-images.githubusercontent.com/19942822/75888739-d6310c80-5df9-11ea-8342-ab48b6aa0918.png)

The git revision and SCM columns aren't terribly clear without previous knowledge of Git and AWX functionality. The information presented should be labeled or its purpose made clearer in some way.

**Comment by mabashian** [comment]
See #6189 

If we had tables then we could have headers and this would be resolved.

**Comment by wenottingham** [comment]
Looks to be implemented in current devel (cc @keithjgrant)

**Comment by unlikelyzero** [comment]
Closing as this was tested in the tables rewrite. Remaining work can be tracked here https://github.com/ansible/awx/issues/6189
