### ISSUE TITLE
Webhook key and credential fields should be visible before creation.

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#6162]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Currently, the webhook key and URL fields are available only when editing a form, and _after_ saving a new form. They're invisible otherwise. This was a somewhat confusing pattern with the old UI as well. It would be good to show what is populated beforehand, to bring it in line with the edit form.

For example, when editing a webhook, we receive this pending message instead of omitting the field entirely:
![Screenshot from 2020-03-04 09-40-31](https://user-images.githubusercontent.com/19942822/75893557-fb754900-5e00-11ea-9d50-11844893e68f.png)

This request is about having a similar pending message for both URL and key when creating a new JT or WFJT.

**Comment by AlexSCorey** [comment]
@dsesami I think this has been resolved in devel, but I'm not entirely sure that I understand what the issue is here.  Can you check the new ui to confirm?

**Comment by mabashian** [comment]
Moving this too needs_test, feel free to kick back if this is still an issue.

**Comment by dsesami** [comment]
This has been established for a while and was implemented a few months back. thanks for the update.
