### ISSUE TITLE
Swap custom CardActionsRow with PF ActionList component

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#6164]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
To properly align and space the card action buttons, we apply style overrides by wrapping the buttons with CardActionsRow. PatternFly Core has a proposal for an ActionList component that we _could_ use to horizontally group action buttons in a Card, List, etc. 

This is issue will require some investigation to see if the new component would serve our purposes and is blocked until it lands in PatternFly React. 

PatternFly Tracking Issue: https://github.com/patternfly/patternfly-next/issues/2021
Also related: https://github.com/patternfly/patternfly-react/issues/3860

![image](https://user-images.githubusercontent.com/15881645/75906344-8dd31800-5e14-11ea-8341-53f73ac678a6.png)

**Comment by mabashian** [comment]
It looks like this feature was merged but hasn't been released yet

**Comment by marshmalien** [comment]
PF Status Update: 
* [Action List component issue](https://github.com/patternfly/patternfly-react/issues/4880) is scheduled for the 11.18.2020 release.
