### ISSUE TITLE
RFE: awx-cli job monitor command

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#6165]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add a monitor parameter to the job resource with cli to be able to monitor currently running jobs. Currently, it is only possible to monitor a job a launch with the --monitor flag.

(similar to https://tower-cli.readthedocs.io/en/latest/api_ref/resources/job.html#tower_cli.resources.job.Resource.monitor)

**Comment by ryanpetrello** [comment]
link: https://github.com/ansible/awx/pull/6790

**Comment by kdelee** [comment]
@ryanpetrello I'm finding this works for jobs launched from job templates and workflows

It is not implemented for `inventory_update` or `project_update` but arguably those could be new RFE's, but they are logical extensions as you can monitor a project update that you launch from the CLI

**Comment by kdelee** [comment]
closing this verified, we can implement the monitor action for other monitorable objects as further enhancement
