### ISSUE TITLE
Add Variables Field to Schedule Details

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#6172]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Link to mockups: https://tower-mockups.testing.ansible.com/patternfly/templates/templates-schedules-detail/

I peeled this out of https://github.com/ansible/awx/pull/6170 because I think it's going to require us to extend the codemirror components to support an initial value of `{}`.  I believe those components are currently expecting a string.  I didn't want to muddy that initial PR with these changes.

**Comment by dsesami** [comment]
Looks great!

**Comment by unlikelyzero** [comment]
Covered by 4560
