### ISSUE TITLE
Survey Preview Functionality

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#6183]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add functionality for survey preview.
https://tower-mockups.testing.ansible.com/patternfly/templates/templates-survey-preview/

**Comment by AlexSCorey** [comment]
This is on hold until survey #5900 and #5899  are merged

**Comment by dsesami** [comment]
Two bugs here:
1) You cannot click the dropdown in the preview modal.
2) Attempting to preview a survey with the multi-select multiple choice question causes the page to crash.

**Comment by dsesami** [comment]
both of the above bugs are handled in #6333 . I will finish out testing on previews there.

**Comment by dsesami** [comment]
Closing this out in favor of #6333
