### ISSUE TITLE
Workflow Job Template Node verbosity option list has an invalid option

### ISSUE THREAD

**Issue by squidboylan** [ansible/awx#6196]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method: docker on linux
* Ansible version: 
* Operating System: Ubuntu 18.04
* Web Browser: Firefox Nightly

##### STEPS TO REPRODUCE

Navigate to `/api/v2/workflow_job_template_nodes/` and click the `OPTIONS` button. Then search for `verbosity`, the 3rd match is: 
```
            "verbosity": {
                "type": "choice",
                "label": "Verbosity",
                "filterable": false,
                "choices": [
                    [
                        "",
                        "---------"
                    ],
                    [
                        0,
                        "0 (Normal)"
                    ],
                    [
                        1,
                        "1 (Verbose)"
                    ],
                    [
                        2,
                        "2 (More Verbose)"
                    ],
                    [
                        3,
                        "3 (Debug)"
                    ],
                    [
                        4,
                        "4 (Connection Debug)"
                    ],
                    [
                        5,
                        "5 (WinRM Debug)"
                    ]
                ]
            },
```

##### EXPECTED RESULTS

The first choice is invalid and shouldnt be there

##### ACTUAL RESULTS

See above

**Comment by kdelee** [comment]
may be best to add unit test coverage for this in awx if possible

@jbradberry was pointing out https://github.com/ansible/awx/pull/5536/files#diff-596536a0e5fde93944c40ae984189f0aR104 may have some faulty logic in it

**Comment by squidboylan** [comment]
This bug is fixed, can we close this or do we want to wait for some unit test coverage?

**Comment by kdelee** [comment]
@squidboylan when you verify the bug is fixed, you have power to close and remove `needs_test`

I do agree that perhaps we could do some unit test coverage for this. If you spend time figuring out how to do that, would be create to move alot of our coverage for OPTIONS type stuff to unit tests as CLI depends heavily on that and is easy AFAIK to do via unit tests.

FWIW I created a node using `null` as verbosity and it worked.
