### ISSUE TITLE
Question: add more AWX task instances to docker stack

### ISSUE THREAD

**Issue by Nightreaver** [ansible/awx#6198]
Hello

Im having a question. After I have successfully deployed AWX on a machine with docker, i wanted to increase the amount of TASK instances for that AWX setup.
I went to the compose folder, edited the docker-compose.yml and duplicated the "task" service.
I gave the container and the service a different name, saved an restarted the stack.

After login to AWX again I can see the additional task instance under instances, but its "dead".
![awx](https://user-images.githubusercontent.com/3270156/76032149-95adcc00-5f7c-11ea-875b-f8ffdd3e613e.JPG)

Its not sending heartbeats, and if I disable the first instance, the second doesn't pick up tasks.
Even if turn it off and on again, and it appears as online for a while, it doesnt work.
I also have been running `/usr/bin/update-ca-trust` on the additional unit, but nothing changed.

I could not really find any information on how to add an instance even after searching for hours now.

Please help.

**Comment by ryanpetrello** [comment]
Hey @Nightreaver,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
