### ISSUE TITLE
External Auth Provider Support

### ISSUE THREAD

**Issue by jaredledvina** [ansible/awx#62]
### Summary

I'd love to see AWX natively support external authentication providers. Specifically, SAML and LDAP auth. I've been going through the WebUI and can't seem to find anything. I have found the Tower documentation stating it's available for that. 

### Environment

* AWX version: 1.0.0.286
* Ansible version:  2.3.1.0
* Operating System: macOS (local dev environment) 
* Web Browser: Google Chrome

**Comment by Caidran** [comment]
Hi Jared,

If you're logged in as the admin account try zooming out on your browser, the 'settings' button appears to be hidden at the bottom of the panel on the left. Once you have that you can setup authentication methods like Azure, LDAP etc. At least this is the case in Chrome on Windows.

**Comment by jaredledvina** [comment]
\o/ YES! The settings button was just hidden. This is wonderful! Thanks for the tip!
