### ISSUE TITLE
Use modified to check if job should be sent to analytics

### ISSUE THREAD

**Issue by Ladas** [ansible/awx#6200]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
It can take several hours for a job to go from pending to successful/failed state and we need to also send the job with a changed state, otherwise the analytics will be incorrect.

##### ENVIRONMENT
* AWX version: all

##### STEPS TO REPRODUCE

Have a long running job

##### EXPECTED RESULTS

Analytics should have the last state of the job present

##### ACTUAL RESULTS

Analytics has the first state of the snapshot taken (`pending` or `running`)

**Comment by Ladas** [comment]
fixed by https://github.com/ansible/awx/pull/6179

**Comment by Ladas** [comment]
cc @rooftopcellist

**Comment by ryanpetrello** [comment]
@Ladas I just want to confirm - you've merged everything you need here, right?

**Comment by Ladas** [comment]
yes, this issue should be fixed now

**Comment by kdelee** [comment]
Works for me, adding test coverage for this too. Closing as verified
