### ISSUE TITLE
Approval job missing started date and elapsed

### ISSUE THREAD

**Issue by Ladas** [ansible/awx#6202]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
`workflowapproval` job under unified jobs has NULL `started` timestamp, leading to elapsed time 0

We need elapsed time in analytics, to be able to subtract the waiting from the real run time.

![Screenshot from 2020-03-06 12-57-51](https://user-images.githubusercontent.com/1737058/76082182-0cfa5480-5fab-11ea-8513-6fed5bc6911b.png)

##### ENVIRONMENT
* AWX version: devel
* AWX install method: yolo (devel from 2020-03-05)

##### STEPS TO REPRODUCE

Add approval step to workflow

##### EXPECTED RESULTS

Approval job in unified jobs will have started time and correct elapsed time

##### ACTUAL RESULTS

Approval job in unified jobs misses started time and elapsed is 0

**Comment by Ladas** [comment]
cc @rooftopcellist @wenottingham

**Comment by appuk** [comment]
I verified this on devel branch, and the workflow job has a non null started and a non zero elapsed fields.
Also added coverage in integration tests, hence closing.
