### ISSUE TITLE
Smart Inventory Filter Key That Contains a Dot

### ISSUE THREAD

**Issue by jmarci** [ansible/awx#6203]
##### ISSUE TYPE
Smart Inventory Filter

##### SUMMARY
Issues building a Smart Inventory with a key that contains a dot(.).

##### ENVIRONMENT
* AWX version: 8.0.0
* AWX  docker
* Ansible version:  2.8.8
* Operating System: CentOS
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Gathering services with service_facts module
  - name: populate service facts
    service_facts:
  },
  "docker.service": {
   "name": "docker.service",
   "state": "running",
   "source": "systemd",
   "status": "enabled"
  },

  - debug:
      var: ansible_facts.services['docker.service'].state

TASK [debug] *****************************************************************************************************************************************************************************************************
ok: [awx] => {
    "ansible_facts.services['docker.service'].state": "running"
}

Attempting to build Smart Inventory filter with following on service(s) key that contains a dot(.). 
ansible_facts.services['docker.service'].state:running

##### EXPECTED RESULTS

Functioning filter.

##### ACTUAL RESULTS

Filter not functioning.

**Comment by ryanpetrello** [comment]
@chrismeyersfsu is there some workaround syntax for this?  I thought I remembered there being one, but I can't find any docs that call it out.

**Comment by kedark3** [comment]
@blomquisg KK here, we'd like to know if there's a fix/workaround too :)

**Comment by joppino** [comment]
You can specify dots by using the urlencode syntax, so:

ansible_facts.services.docker%2Eservice.state.running 

will work and create a filter that will be shown with the dot in the name.

**Comment by TheRealHaoLiu** [comment]
Smart inventories is deprecated in favor of constructed inventory

Check it out https://github.com/ansible/awx/pull/13303
