### ISSUE TITLE
Swap input type=date element for PF Date Picker 

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#6214]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Tracking PF Issues
React: https://github.com/patternfly/patternfly-react/issues/2010
Core: https://github.com/patternfly/patternfly-next/issues/180

This issue is blocked until PF React component merges upstream

**Comment by mabashian** [comment]
I believe this is ready to go - going to move to needs_devel

**Comment by marshmalien** [comment]
PatternFly Status Update:

* They released a beta date picker component upstream - [date picker docs](https://www.patternfly.org/v4/components/date-picker/react)
* Their next priority is the [date component cleanup issue](https://github.com/patternfly/patternfly-react/issues/5057) with target date of 11.18.2020. 
* The PF React [time picker issue](https://github.com/patternfly/patternfly-react/issues/4731) is scheduled for 12.09.2020 
* The PF React [date range picker issue](https://github.com/patternfly/patternfly-react/issues/4732) is scheduled for 12.09.2020

PF-React Date and Time component tracking issue: https://github.com/patternfly/patternfly-react/issues/4711

**Comment by mabashian** [comment]
AFAIK, there are only two places currently where we display date form fields:

https://github.com/ansible/awx/blob/devel/awx/ui_next/src/components/Schedule/shared/FrequencyDetailSubform.jsx#L564-L569

https://github.com/ansible/awx/blob/devel/awx/ui_next/src/components/Schedule/shared/ScheduleForm.jsx#L114-L120

IIRC, this PF component doesn't support time selection so if/when we do this we may need to split the field into date & time.

**Comment by mabashian** [comment]
@AlexSCorey I believe you're current working on this in conjunction with the schedule bug(s).  If that's the case I'll update the assignee/status.

**Comment by mabashian** [comment]
See https://github.com/ansible/awx/issues/10152 and https://github.com/ansible/awx/pull/10237

**Comment by tiagodread** [comment]
This is now implemented with #10291
