### ISSUE TITLE
Is it legal to redistribute awx with a custom header and login logo ?

### ISSUE THREAD

**Issue by frsauvage** [ansible/awx#6222]
Hi,
I just would like to know if I can change the loginheader and logo (top-left)  to redistribute awx in my global solution ?
Because in Apache license, it is written that trademarks should (may) be retain and I don't know exactly what it means as so many people change the logo apparently !
Thank,
Francine

**Comment by jakemcdermott** [comment]
You'll want to change the logo. See: https://github.com/ansible/awx-logos/blob/master/TRADEMARKS.md
