### ISSUE TITLE
ask_variables_on_launch issue on AWX

### ISSUE THREAD

**Issue by leosimony** [ansible/awx#6225]
##### ISSUE TYPE
ask_variables_on_launch is set to true still getting error as undefined variable.

##### SUMMARY
I have created a Job template via API and set the ask_variables_on_launch value to true. Though setting the value as true, playbook fails during execution, saying 'undefined variable'

##### ENVIRONMENT
* AWX version: 9.2.0
* Tower CLI 3.3.8
* API v2
* AWX install method: Installation without Docker on CentOS7
* Ansible version:  2.9.5
* Operating System: CentOS Linux release 7.7.1908 (Core)
* Web Browser: Google Chrome Version 80.0.3987.132 (Official Build) (64-bit)

##### STEPS TO REPRODUCE

>> Created a Job Template for sample.
>> Verify the values of the sample job template for 'project, inventory, playbook' attributes, and its corresponding values.
>> With the values observed from the sample job template, create a new job template via APIv2 and set the value of "ask_variables_on_launch to true" 

* API URL:
* http://awx-server-ip/api/v2/job_templates/

##### EXPECTED RESULTS

Being set the value of 'ask_variables_on_launch' to true, I should be able to execute the playbook by passing extra variable during launch of the playbook and via Survey as well.

##### ACTUAL RESULTS

"msg": "The task includes an option with an undefined variable. The error was: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'it_user'\n\nThe error appears to be in '/tmp/awx_25_ahs6_izp/project/useradd_IT.yml': line 7, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: Adding users\n      ^ here\n",
    "_ansible_no_log": false

--The same error occurred when the value of 'ask_variables_on_launch' set as false.

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/47471901/76210019-3d4f2680-6229-11ea-95f8-04dc9ac4f84d.png)

![image](https://user-images.githubusercontent.com/47471901/76210151-87380c80-6229-11ea-8e8e-2359422c1276.png)

**Comment by AlanCoding** [comment]
> Being set the value of 'ask_variables_on_launch' to true, I should be able to execute the playbook by passing extra variable during launch of the playbook and via Survey as well.

Some information that would be really valuable here:

1. What does the variable you passed look like? You don't have to give passwords (obviously), but is it a dictionary? What's its type and subtypes? Remove your passwords and put in "foo" and "bar" so we can see what the data structure is
2. Could you give us the YAML for this specific task? This looks related to templating the variable, which could be related to server actions of marking vars as unsafe, but I don't know and we need more hints
3. Do the extra_vars for the JT itself already have some entry for this var? What does that look like?

**Comment by leosimony** [comment]
Sorry for the delay. Please don't mind.

1. What does the variable you passed look like? You don't have to give passwords (obviously), but is it a dictionary? What's its type and subtypes? Remove your passwords and put in "foo" and "bar" so we can see what the data structure is

Since this is an adding user's playbook, the variable is just the username.

---
- name: user add
  hosts: all
  vars:
    it_user: leosimon
-- I have defined this vars section in the playbook and called it with with_items in the task level.

2. Could you give us the YAML for this specific task? This looks related to templating the variable, 2. which could be related to server actions of marking vars as unsafe, but I don't know and we need more hints

--One thing I need to mention here is, the project I have added in the AWX is not based on SCM, its Manual type and placed the project directory in /var/lib/awx/projects/. Attached the playbook in the attachment

Do the extra_vars for the JT itself already have some entry for this var? What does that look like?

--The playbook vars definition section has a value. I have added Survey in the job template as well with a multi-select choice option. So that whenever we need to add particular users to servers, we can use the survey section to accomplish. 
Even if we have a variable defined in the playbook, the extra_vars job is to override that value and include the value passed through extra_vars right?
Correct me if I am wrong or I have to do this in some other way.

[adding_users.txt](https://github.com/ansible/awx/files/4316319/adding_users.txt)

**Comment by AlanCoding** [comment]
I cannot understand why you are trying to do `name: "{{ item.it_user }}"`. All you need is `"{{ item }}"`

`it_user` is the variable name of the list, you correctly passed this to `with_items:`. The _elements_ in the loop (as in all such Ansible loops) are referenced by `item` unless you use some other loop control variable.

The multiselect provides a list of strings to the playbook. Your error indicates that `item` is a list, which aligns exactly with my expectations.

I put up my own example at https://github.com/AlanCoding/utility-playbooks/tree/master/issues/6225

You can still ask for help, but I'm closing this because I don't envision a server-side issue coming out of it.

**Comment by leosimony** [comment]
@AlanCoding I am really sorry for being so dumb to make that mistake and wasting your time. I was working on some other config like, 

vars:
  db:
   - name: dbname1
   - name: dbname2

--Called this like "{{ item.name }}"

Keeping this in mind, I used the same on that playbook as well. I was so dumb to do that. 

Thank you for pointing it out politely. Its working fine.

**Comment by prakasharumugaminfy** [comment]
@leosimony @AlanCoding Greetings :) !!!

I need to run a job from terminal using curl command with extra variables. I updated the above suggested item `**("ask_variables_on_launch": true,)**` . After running the Curl command with extra variable, Template Job is executed in tower  but not with the extra variables which passed in cmd.

Couls you please help us if you have any idea on this.

**Curl Command:**

`curl -f -H 'Content-Type: application/json' -XPOST                   -d '{"host_config_key": "fef439-740f-429c-a7r34r2-15r34rr6b76", "extra_vars": "{\"job_id\": \"24\"},{\"job_templates\": \"test99\"}"}'                   https://ansible-tower.com:443/api/v2/job_templates/822/callback/ -k`

**Comment by AlanCoding** [comment]
The `},{` looks out of place. This might work, but not sure.

```
curl -f -H 'Content-Type: application/json' -XPOST -d '{"host_config_key": "fef439-740f-429c-a7r34r2-15r34rr6b76", "extra_vars": "{\"job_id\": \"24\", \"job_templates\": \"test99\"}"}' https://ansible-tower.com:443/api/v2/job_templates/822/callback/ -k
```
