### ISSUE TITLE
Does AWX 9.2.0 include ansible 2.9

### ISSUE THREAD

**Issue by piellick** [ansible/awx#6236]
Hello, no information about that on the latest build , someon could confirme the ansible engine version ?

thanks

**Comment by clammers** [comment]
```
ansible 2.9.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```

**Comment by ryanpetrello** [comment]
Hey @piellick,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
