### ISSUE TITLE
Job detail and job output stops updating 

### ISSUE THREAD

**Issue by wbieniek** [ansible/awx#6243]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
with it 24h after restart AWX stops updating output window

##### ENVIRONMENT
* AWX version: 9.1
* AWX install method: openshift
* Ansible version:  X.Y.Z
* Operating System:RH7
* Web Browser:Chrome

##### ADDITIONAL INFORMATION

This only happens on busy AWX installation with 15 pods and 80-120 concurrent jobs. We never see this issue on AWX deployments with low utilization’s.
Pods restart fixes this issue for few hours.
awx-rabbit log

020-03-10 17:35:12.672 [info] <0.23837.2> closing AMQP connection <0.23837.2> (172.24.21.96:53536 -> 172.24.99.93:5672, vhost: 'awx', user: 'awx')
--
  | 2020-03-10 17:35:14.590 [warning] <0.20900.2> closing AMQP connection <0.20900.2> (172.24.149.227:42590 -> 172.24.99.93:5672, vhost: 'awx', user: 'awx'):
  | client unexpectedly closed TCP connection
  | 2020-03-10 17:35:14.590 [warning] <0.22713.2> closing AMQP connection <0.22713.2> (172.24.149.227:60938 -> 172.24.99.93:5672, vhost: 'awx', user: 'awx'):
  | client unexpectedly closed TCP connection
  | 2020-03-10 17:35:22.879 [info] <0.23886.2> accepting AMQP connection <0.23886.2> (172.24.144.225:51700 -> 172.24.99.93:5672)
  | 2020-03-10 17:35:22.881 [info] <0.23886.2> connection <0.23886.2> (172.24.144.225:51700 -> 172.24.99.93:5672): user 'awx' authenticated and granted access to vhost 'awx'
  | 2020-03-10 17:35:22.887 [info] <0.23886.2> closing AMQP connection <0.23886.2> (172.24.144.225:51700 -> 172.24.99.93:5672, vhost: 'awx', user: 'awx')
  | 2020-03-10 17:35:26.712 [info] <0.23907.2> accepting AMQP connection <0.23907.2> (172.24.99.1:39674 -> 172.24.99.93:5672)
  | 2020-03-10 17:35:26.714 [info] <0.23907.2> connection <0.23907.2> (172.24.99.1:39674 -> 172.24.99.93:5672): user 'awx' authenticated and granted access to vhost 'awx'
  | 2020-03-10 17:35:26.717 [info] <0.23907.2> closing AMQP connection <0.23907.2> (172.24.99.1:39674 -> 172.24.99.93:5672, vhost: 'awx', user: 'awx')
  | 2020-03-10 17:35:27.284 [info] <0.23918.2> accepting AMQP connection <0.23918.2> (172.24.95.216:46200 -> 172.24.99.93:5672)
  | 2020-03-10 17:35:27.287 [info] <0.23918.2> connection <0.23918.2> (172.24.95.216:46200 -> 172.24.99.93:5672): user 'awx' authenticated and granted access to vhost 'awx'
  | 2020-03-10 17:35:28.152 [info] <0.23927.2> accepting AMQP connection <0.23927.2> (172.24.99.1:39788 -> 172.24.99.93:5672)
  | 2020-03-10 17:35:28.154 [info] <0.23927.2> connection <0.23927.2> (172.24.99.1:39788 -> 172.24.99.93:5672): user 'awx' authenticated and granted access to vhost 'awx'
  | 2020-03-10 17:35:28.263 [info] <0.23936.2> accepting AMQP connection <0.23936.2> (172.24.21.96:54388 -> 172.24.99.93:5672)
  | 2020-03-10 17:35:28.266 [info] <0.23936.2> connection <0.23936.2> (172.24.21.96:54388 -> 172.24.99.93:5672): user 'awx' authenticated and granted access to vhost 'awx'
  | 2020-03-10 17:35:29.908 [warning] <0.22525.2> closing AMQP connection <0.22525.2> (172.24.21.96:44558 -> 172.24.99.93:5672, vhost: 'awx', user: 'awx'):
  | client unexpectedly closed TCP connection
  | 2020-03-10 17:35:30.751 [info] <0.23953.2> accepting AMQP connection <0.23953.2> (172.24.16.182:36556 -> 172.24.99.93:5672)
  | 2020-03-10 17:35:30.753 [info] <0.23953.2> connection <0.23953.2> (172.24.16.182:36556 -> 172.24.99.93:5672): user 'awx' authenticated and granted access to vhost 'awx'
  | 2020-03-10 17:35:30.759 [info] <0.23953.2> closing AMQP connection <0.23953.2> (172.24.16.182:36556 -> 172.24.99.93:5672, vhost: 'awx', user: 'awx')

**Comment by wenottingham** [comment]
Are you experiencing this in 9.3.0? We did fix some bugs in this area.

**Comment by jakemcdermott** [comment]
Hey @wbieniek - like other's have mentioned, we've merged quite a bit of work into this area as of late. Please upgrade to the latest version and see if your issue is resolved. If you're still experiencing problems after upgrading, re-open this issue and we'll take another look. Thanks!
