### ISSUE TITLE
Job Template Form (and maybe other forms) don't wrap when given long lines of text

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#6247]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Try to edit a Job Template at a smaller screen width. 
Put a long string of text, maybe rife with typos, like:
```
{"ansible_host": "127.0.0.1", ansible_var: foo "ansible_connection": "local"}
```
This makes the form do this:
![Screenshot from 2020-03-10 16-23-53](https://user-images.githubusercontent.com/19942822/76356647-ac418380-62ec-11ea-81f5-3f61b3502cbb.png)

**Comment by unlikelyzero** [comment]
covered in visual tests
