### ISSUE TITLE
update notifications whitelist

### ISSUE THREAD

**Issue by absynth76** [ansible/awx#6258]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
One of the main deployment information is the tag and/or branch version, or the scm_branch parameter is not available through the job dictionary and so notifications cannot include that common field. Could you please add it to the JOB_FIELDS_WHITELIST  in notifications.yml? thank you.

**Comment by kdelee** [comment]
Works for us! Made notifications w/ this var and verified that it used to throw 400, but now it works.
