### ISSUE TITLE
Template job tags field moving tag text to the left

### ISSUE THREAD

**Issue by MrOwen** [ansible/awx#626]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When inserting too many tags at once, the blue area containing the tags will increasingly (depending on the amount of characters) move to the left until it's no longer visible. A re-focus on the text field resolves this.

##### ENVIRONMENT
* AWX version: 3.2.1 (Tower)
* AWX install method: Tower installer
* Ansible version:  2.4.0.0
* Operating System: RHEL 7.3
* Web Browser: Firefox 57/Chrome 59

##### STEPS TO REPRODUCE

1. Insert the following text into the job tags field on a template: `V-38697,V-38668,V-38593,V-38615,V-38620,V-38621,V-38511,V-38600,V-38601,V-38524,V-38533`
2. Notice the blue field moves to the left inside the text field. If you re-focus on the field, it fixes itself
3. Insert this text into the same field: `V-38697,V-38668,V-38593,V-38615,V-38620,V-38621,V-38511,V-38600,V-38601,V-38524,V-38533,V-38526,V-38532,V-38528,V-38535,V-38537,V-38542,V-38544,V-38539,V-38518,V-38519,V-38605,V-38607,V-38611,V-38614,V-38617,V-38608,V-38610,V-38615,V-38482,V-38569,V-38570,V-38571,V-38475,V-38501,V-38573,V-38658,V-38479,V-38477,V-38480,V-38496,V-38500,V-38642,V-38492,V-38450,V-38451,V-38457`
4. The blue field moves completely out of view (I assume) until you re-focus on the field

##### EXPECTED RESULTS

The blue field should always wholly remain inside the text field.

##### ACTUAL RESULTS

The blue field moves further to the left inside the text field the more text you put in. See screenshot here: ![screenshot](https://i.imgur.com/qglGzXj.png)

##### ADDITIONAL INFORMATION

MacOS and Windows 10 (regardless of browser) exhibit expected behavior. Problem is only on RHEL (haven't been able to test on Fedora yet)

@shanemcd was able to reproduce this bug

**Comment by ryanpetrello** [comment]
Closing due to age.
