### ISSUE TITLE
Release of 9.3.0 has not arrived at Dockerhub

### ISSUE THREAD

**Issue by JonTheNiceGuy** [ansible/awx#6269]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The release of 9.3.0 in the [VERSION](https://github.com/ansible/awx/blob/devel/VERSION) file does not correspond with the release of that [image on Dockerhub](https://hub.docker.com/r/ansible/awx_web/tags). This prevents the installer from completeing.

##### ENVIRONMENT
* AWX version: 9.3.0 intended
* AWX install method: docker on linux
* Ansible version:  2.9.6
* Operating System: Ubuntu 18.04
* Web Browser: N/A

##### STEPS TO REPRODUCE
```
git clone https://github.com/ansible/awx /opt/awx
cd /opt/awx/installer
ansible-playbook -i inventory install.yml
```

##### EXPECTED RESULTS
Installation of docker images for ansible/awx_web:9.3.0, ansible/awx_task:9.3.0

##### ACTUAL RESULTS
Failed to pull image version 9.3.0

##### ADDITIONAL INFORMATION
N/A

**Comment by ryanpetrello** [comment]
Hey @JonTheNiceGuy,

I'm preparing the release this morning.

**Comment by JonTheNiceGuy** [comment]
Fab, thanks @ryanpetrello.

I know I likely hit the "bump" of that this morning because it hadn't flowed through yet, but is there some sort of process around getting the "VERSION" file not to be bumped until after the release is cut on dockerhub? It's not a huge issue, but it did cause some head scratching this morning :)

Alternatively, is it possible to have the installer script check dockerhub to see what "latest" is at the time of deployment, instead of relying on the VERSION file? (I don't really know enough about Docker registries to know whether that's something that can be done from an Ansible script!)

**Comment by ryanpetrello** [comment]
Hey @JonTheNiceGuy,

> Alternatively, is it possible to have the installer script check dockerhub to see what "latest" is at the time of deployment, instead of relying on the VERSION file?

Here's comes my spiel about how `devel` is by nature unstable, and that we *don't* build nightly Docker images.  If you're the type that's running `devel` for something, you should be building your own images 😉, because there are likely to be discrepancies between `HEAD` of this repository and the "latest" Docker image.

In any event, I expect to have the 9.3.0 image published by mid-morning EST.

**Comment by JonTheNiceGuy** [comment]
Ah, to be fair, I hadn't really clocked that I was on `devel` ;) Yep, I'll switch to using tags from now on :)
