### ISSUE TITLE
Request output of ping endpoint in XML format

### ISSUE THREAD

**Issue by mdinwoodie** [ansible/awx#6274]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
When running a curl command against the ping endpoint, the output cannot be requested in XML format. As a use-case, requesting the output in XML format would make it easier to filter data on a load balancer.

**Comment by wenottingham** [comment]
We are not going to add additional formatters that are not supported by our upstream REST library (django rest framework)
