### ISSUE TITLE
VMware inventory timeout

### ISSUE THREAD

**Issue by guliaka** [ansible/awx#6277]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Unable to parse /var/lib/awx/venv/awx/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py as an inventory source

##### ENVIRONMENT
* AWX version: 0.9.2
* AWX install method: docker on linux
* Ansible version:  2.9.6
* Operating System: RHEL 8
* Web Browser: Firefox/Chrome

##### STEPS TO REPRODUCE
Installed on RHEL8 with following script:

#!/usr/bin/bash
## Install epel repo
dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -y
firewall-cmd --zone=trusted --permanent --add-service http
firewall-cmd --zone=trusted --permanent --add-service https
firewall-cmd --reload

dnf install git gcc gcc-c++ nodejs npm gettext device-mapper-persistent-data lvm2 bzip2 python3 python3-pip -y
dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
dnf install https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.13-3.1.el7.x86_64.rpm -y
dnf install docker-ce -y
systemctl start docker
systemctl enable --now docker.service

alternatives --set python /usr/bin/python3

pip3 install docker
pip3 install docker-compose
dnf install -y ansible

git clone https://github.com/ansible/awx.git
git clone https://github.com/ansible/awx-logos.git

cd awx

## Create a folder in /opt/ to hold awx psql data
mkdir -p /opt/awx-psql-data

## Provide psql data path to installer.
sed -i "s|^postgres_data_dir.*|postgres_data_dir=/opt/awx-psql-data|g" installer/inventory

## Create awx-ssl folder in /etc.
mkdir -p /etc/awx-ssl/

## Make a self-signed ssl certificate
openssl req -subj '/CN=secops.tech/O=Secops Tech/C=TR' \
	-new -newkey rsa:2048 \
	-sha256 -days 1365 \
	-nodes -x509 \
	-keyout /etc/awx-ssl/awx.key \
	-out /etc/awx-ssl//awx.crt

## Merge awx.key and awx.crt files
cat /etc/awx-ssl/awx.key /etc/awx-ssl/awx.crt > /etc/awx-ssl/awx-bundled-key.crt

## Pass the full path of awx-bundled-key.crt file to ssl_certificate variable in inventory.
sed -i -E "s|^#([[:space:]]?)ssl_certificate=|ssl_certificate=/etc/awx-ssl/awx-bundled-key.crt|g" installer/inventory

## Change dir to awx and replace awx_official parameter
sed -i -E "s|^#([[:space:]]?)awx_official=false|awx_official=true|g" installer/inventory

## Define the default admin username
sed -i "s|^admin_user=.*|admin_user=awx-admin|g" installer/inventory

## Set a password for the admin
sed -i "s|^admin_password=.*|admin_password=CHANGE_M3|g" installer/inventory

## Enter the installer directory.
cd ~/awx/installer

## Initiate install.yml
ansible-playbook -i inventory install.yml

##### EXPECTED RESULTS

Expected to get vSphere inventory

##### ACTUAL RESULTS

    1.723 INFO     Updating inventory 2: Getty_vi
    2.091 DEBUG    Using base command: python /usr/bin/ansible-inventory -i /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py --playbook-dir /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/plugins/inventory -vvvvv
    2.091 INFO     Reading Ansible inventory source: /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py
    2.096 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    2.096 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    2.097 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1157, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1047, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 215, in load
    return self.command_to_json(base_args + ['--list'])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 198, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
ansible-inventory 2.9.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
[WARNING]:  * Failed to parse /var/lib/awx/venv/awx/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py with script plugin:
Inventory script (/var/lib/awx/venv/awx/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py) had an execution error:
Unable to connect to ESXi server due to [Errno 110] Connection timed out
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/script.py", line 161, in parse
    raise AnsibleParserError(to_native(e))
[WARNING]: Unable to parse /var/lib/awx/venv/awx/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py as an inventory source
ERROR! No inventory was parsed, please check your configuration and options.

**Comment by ryanpetrello** [comment]
Hey @guliaka,

> Unable to connect to ESXi server due to [Errno 110] Connection timed out

Error's right there, look like you can't reach the host ^

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by guliaka** [comment]
I can reach vceneter from host where awx deployed but not from with in
awx_task container.
