### ISSUE TITLE
Workflow Templates Disappearing After Selecting Project Job Templates

### ISSUE THREAD

**Issue by ghost** [ansible/awx#628]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Workflow Templates disappear after selecting PROJECTS ->  some project -> JOB TEMPLATES

##### ENVIRONMENT
* AWX version: 1.0.1.120 ,  1.0.1.203
* AWX install method: docker on linux
* Ansible version:  2.4.1.0
* Operating System: Centos 7.4
* Web Browser: 
*Chrome Version 62.0.3202.75 (Official Build) (64-bit)
*Firefox ESR 52.4.0 (64-bit)

##### STEPS TO REPRODUCE
Click TEMPLATES. The Workflow Templates are present

![initial_templates_list](https://user-images.githubusercontent.com/6487265/32757377-1013ac26-c894-11e7-9d79-7dd308e5e4ac.png)

Click PROJECTS. Select any project(In this example Linux or Windows)

![projects](https://user-images.githubusercontent.com/6487265/32757477-8aa0f8e0-c894-11e7-89ef-8cae4634263d.png)

Click Job Templates at the top right.

![projects_job_templates](https://user-images.githubusercontent.com/6487265/32757555-ed712e7c-c894-11e7-89e0-1641bd3cfa01.png)

Click TEMPLATES from the side menu

![no_workflow_templates](https://user-images.githubusercontent.com/6487265/32757614-35b8a3b8-c895-11e7-968b-cfaeb6b12673.png)

At this point the Workflow Templates are no longer in the TEMPLATES list. The specific Workflow Template in this example (Install zabbix-agent) only uses playbooks belonging to the Linux project and use the same Inventory for all playbooks inside the template. Furthermore, the template is still accessible through the JOBS on the menu bar and if it a Workflow Template that has ran in the past.

##### EXPECTED RESULTS

The Workflow Template should show up in the TEMPLATES list.

##### ACTUAL RESULTS

No Workflow Templates show up in the TEMPLATES list.

##### ADDITIONAL INFORMATION

This issue is reset when you restart the containers.

**Comment by gconsidine** [comment]
Hey @mlobbia,

Thanks for filing the issue -- I was just able to reproduce it locally. We suspect it's related to some state being retained that shouldn't be when bouncing around to those views. In the mean time, you can get back to your full list of templates by refreshing the page. No need to restart your containers.

**Comment by ghost** [comment]
@gconsidine Oh man, I didn't even think to refresh the browser. Thanks for the response!
