### ISSUE TITLE
Please Increase First Name Field to Support Greater than 30 Characters

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/awx#6281]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Increase the ability for both the UI and Django to accept first_name fields beyond 30 (similar to last_name which supports 150 characters).

**Comment by meystel** [comment]
I see the "priority:low" tag. Just to be clear, this is currently affecting 1% of my user base and this percentage is likely to grow with current shifts in staffing towards people with longer first names. Taking a low priority view of internationalization is akin to taking a low priority view of accessibility. Making people change their name just so they can login to a piece of software leaves users with a rather dim view of that software. This isn't really an enhancement request, so much as it is a bug fix request. User name fields should not be limited to 30 characters - humanity is no longer constrained by disk expense like we were in the past.

**Comment by ryanpetrello** [comment]
To be clear, there's not a _lot_ we can do about this without resorting to some pretty hacky stuff in AWX - it's a limitation in an underlying software framework AWX is built on (Django):

https://github.com/django/django/blob/master/django/contrib/auth/models.py#L334

Django recently extended the size of the last name column:

https://code.djangoproject.com/ticket/26993

...but I don't see any evidence of an issue to track extending the first name column.

**Comment by meystel** [comment]
The origin of this issue came through RedHat (paid) Support. The submitter of the RH case has no direct relationship with ansible core community nor, certainly, with Django. But would expect the vendor (RedHat) to take steps to ensure that all underlying software (including Django) is brought up to snuff. In other words, would expect RedHat to push Django to make the necessary change to the first name column as well. I just tried to open a Django bug mimicking 26993 but was unable to do so. Would you please do so?

**Comment by ryanpetrello** [comment]
see: https://code.djangoproject.com/ticket/31371#ticket
see: https://github.com/django/django/pull/12581

**Comment by ryanpetrello** [comment]
Marking this as `blocked` until it gets fixed upstream and until we can update to the latest version of Django (whatever version it lands in - most likely 3.1) cc @matburt @jbradberry

**Comment by ryanpetrello** [comment]
@meystel,

I've contributed a patch to Django which extends the username column to 150 characters, and it was accepted and merged:

https://github.com/django/django/pull/12581#event-3140320765

At some point in the future after it's released, we'll update AWX to the next version of Django (3.1), and AWX will gain this support for longer first names.

**Comment by ryanpetrello** [comment]
Whoever stumbles upon this next: this issue is blocked until Django 3.1 is released, and we can upgrade to it.

**Comment by meystel** [comment]
felixxm merged commit 5f8495a into django:master 6 hours ago. How quickly can awx pick up the change?

**Comment by meystel** [comment]
> @meystel,
> 
> I've contributed a patch to Django which extends the username column to 150 characters, and it was accepted and merged:
> 

Thank you very much!!!

**Comment by jbradberry** [comment]
The Django upgrade has merged, and thus will roll out the door for the next release(s).

PR: https://github.com/ansible/awx/pull/11654
