### ISSUE TITLE
ERROR! Failed to update notifier. Field 'job_metadata' unavailable.

### ISSUE THREAD

**Issue by DionJones615** [ansible/awx#6282]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 7.0.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.4
* Operating System: Ubuntu
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Update notification text to include: {{ job_metadata }}
2. Click Save

##### EXPECTED RESULTS

Expected a JSON string to be returned in my notification as indicated here: https://docs.ansible.com/ansible-tower/latest/html/installandreference/notification_parameters_supported.html

##### ACTUAL RESULTS

ERROR! Popup:  Failed to update notifier. Field 'job_metadata' unavailable.

**Comment by wenottingham** [comment]
What type of notification is this? 

I'd also try with 9.3.0 - we fixed some bugs here very recently (including what fields are actually available - some were advertised as being available that actually are not).
