### ISSUE TITLE
Jobs List ID search should be number input based

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#6288]
![Screen Shot 2020-03-13 at 3 40 16 PM](https://user-images.githubusercontent.com/1342624/76654268-02a70000-6541-11ea-9597-3a77b2f5512c.png)

This should be a number input, not text.  There's code there that should find ID in the integerFields of the QS_CONFIG, and used that to determine if it is a number-based search or not, but it seems like that is not working correctly right now.

**Comment by jlmitch5** [comment]
whoops never got moved to needs_test

**Comment by dsesami** [comment]
Confirmed that jobs list search by ID works correctly now.
