### ISSUE TITLE
Add tabs to sort through job templates based on Jenkins tags

### ISSUE THREAD

**Issue by mdinwoodie** [ansible/awx#6289]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
Add tabs at the top of the job template list that are based on Jenkins tags to allow for easier navigation of job templates.

**Comment by wenottingham** [comment]
This is what labels are for, in general - you put the labels on the job template and you can then filter by labels.

Closing as a duplicate of https://github.com/ansible/awx/issues/2350 in general.
