### ISSUE TITLE
Checkout svn gave a certificate error

### ISSUE THREAD

**Issue by yangliang003** [ansible/awx#629]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### ENVIRONMENT
* AWX version: 1.0.1
* AWX install method: docker on linux
* Ansible version:  2.4.0
* Operating System:centos 7
* Web Browser:chrome

##### STEPS TO REPRODUCE
1,config a project with subversion crendential;
2,run the project;

##### EXPECTED RESULTS
checkout successfully

##### ACTUAL RESULTS
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/svn --non-interactive --trust-server-cert --no-auth-cache --username yangl --password '********' checkout -r HEAD https://10.2.30.79/svn/yl01 /var/lib/awx/projects/_7__yl01_proj", "failed": true, "msg": "svn: E175002: Unable to connect to a repository at URL 'https://10.2.30.79/svn/yl01'\nsvn: E175002: OPTIONS of 'https://10.2.30.79/svn/yl01': Server certificate verification failed: certificate issued for a different hostname, issuer is not trusted (https://10.2.30.79)", "rc": 1, "stderr": "svn: E175002: Unable to connect to a repository at URL 'https://10.2.30.79/svn/yl01'\nsvn: E175002: OPTIONS of 'https://10.2.30.79/svn/yl01': Server certificate verification failed: certificate issued for a different hostname, issuer is not trusted (https://10.2.30.79)\n", "stderr_lines": ["svn: E175002: Unable to connect to a repository at URL 'https://10.2.30.79/svn/yl01'", "svn: E175002: OPTIONS of 'https://10.2.30.79/svn/yl01': Server certificate verification failed: certificate issued for a different hostname, issuer is not trusted (https://10.2.30.79)"], "stdout": "", "stdout_lines": []}

##### ADDITIONAL INFORMATION
1、It worked well when I copy the command and run in the terminal ;
2、Worked well too when I used the ansible playbook to checkout the svn;
3、awx failed screenshot:
![s2 ag yttvb4qgdxkdhwej](https://user-images.githubusercontent.com/16607114/32760012-430430d6-c927-11e7-9d30-5c88b41c06f8.png)

**Comment by wwitzel3** [comment]
Take a look at https://github.com/ansible/awx/blob/0bbc08e5878d41304c4cb6576f1b8d0608658c0c/installer/inventory#L109

Does setting that directory to one containing your CA certs fix the issue?

**Comment by matburt** [comment]
no follow up in several months
