### ISSUE TITLE
Auth Settings update 400 when no galaxy URL set & public disabled

### ISSUE THREAD

**Issue by MrBones757** [ansible/awx#6293]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When public galaxy access is disabled, and no URL is specified, updated to LDAP auth retun 400 with no error reason.

Looking at devtools console in chrome leads to the following error:

vendor.08d153df1a615982ffc7.js:201 Possibly unhandled rejection: {"data":{"PRIMARY_GALAXY_URL":["A URL for Primary Galaxy must be defined before disabling public Galaxy."],"PUBLIC_GALAXY_ENABLED":["A URL for Primary Galaxy must be defined before disabling public Galaxy."]},"status":400,"config":{"method":"PATCH" ............. (censored due to auth settings payload)

##### ENVIRONMENT
* AWX version: 9.3.0
* AWX install method: kubernetes
* Ansible version:  2.9.3
* Operating System:
* Web Browser: Chrome 80.0.3987.132

##### STEPS TO REPRODUCE

- Turn off allow access to public galaxy URL
- DO NOT configure alternate galaxy endpoints
- Make an update to LDAP settings

##### EXPECTED RESULTS

LDAP Settings apply, or an appropriate error is returned.

##### ACTUAL RESULTS

Generic 400 message popup appears (with the following output in the devtools console)

Possibly unhandled rejection: {
    "data": {
        "PRIMARY_GALAXY_URL": [
            "A URL for Primary Galaxy must be defined before disabling public Galaxy."
        ],
        "PUBLIC_GALAXY_ENABLED": [
            "A URL for Primary Galaxy must be defined before disabling public Galaxy."
        ]
    },
    "status": 400,
    "config": {
        "method": "PATCH",
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "jsonpCallbackParam": "callback",
        "url": "/api/v2/settings/all/",
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json;charset=utf-8",
            "X-Requested-With": "XMLHttpRequest",
            "X-CSRFToken": "<TOKEN>"
        },
        "data": {
            <CENSORED DATA PAYLOAD>
        }
    },
    "statusText": "",
    "xhrStatus": "complete"
}

##### ADDITIONAL INFORMATION

Let me know if you need any additional info or screenshots

**Comment by egmar** [comment]
See https://github.com/ansible/awx/pull/5585 According to this PR, you should have at least public Galaxy enabled.

**Comment by AlanCoding** [comment]
There's a setting to disable role downloading completely (`AWX_ROLES_ENABLED`), is that what you want?

**Comment by MrBones757** [comment]
Sorry for the misunderstanding, the issue here was more that the UI returned an error that made no sense.

It wasn't until i had a look at the error returned in the console that i knew what the actual issue was.
If the information is available in the console, it should be surfaced up in the 400 popup so that users know what the actual issue is?

I spent quite a while debugging my ldap config thinking id done something wrong before thinking of checking console logs. I notice that you can no longer disable public galaxy as of 9.3 without having an alternate URL set so this situation shouldnt occur again, but as far as error handling goes i've seen this in a few other places where an error is returned to the user with little to no context unles syou start looking at logs or console messages (don't have examples right now though as iv always dealt with these as they occur)

**Comment by ryanpetrello** [comment]
@jakemcdermott @mabashian can one of you find somebody to take a peek at this?  Thanks 😄

**Comment by mabashian** [comment]
As soon as I toggle ALLOW ACCESS TO PUBLIC GALAXY off this is what the interface looks like:

<img width="1490" alt="Screen Shot 2020-03-17 at 3 11 32 PM" src="https://user-images.githubusercontent.com/9889020/76892857-b2da7880-6861-11ea-9a16-5d9024e726af.png">

When that toggle is clicked we're making a patch to `/api/v2/settings/all` with the payload:

`{"PUBLIC_GALAXY_ENABLED": false}`

The api responds with:

<img width="710" alt="Screen Shot 2020-03-17 at 3 24 32 PM" src="https://user-images.githubusercontent.com/9889020/76893856-6d1eaf80-6863-11ea-9aa2-57ce017ef3e6.png">

I _think_ the issue is that there's no error text showing up underneath the toggle after you click it.

I'll open up a PR to make the interface look like:

<img width="1489" alt="Screen Shot 2020-03-17 at 3 25 26 PM" src="https://user-images.githubusercontent.com/9889020/76893922-8cb5d800-6863-11ea-9384-9913321ae0e0.png">

after the toggle is clicked.

**Comment by dsesami** [comment]
Verified that the LDAP settings can be changed without a 400, and that all the galaxy-related parameters POST successfully now. The form validation with the logic between a primary galaxy server URL and allowing access to public galaxy works.

**Comment by MrBones757** [comment]
Thanks for have a look at this guys! :)
