### ISSUE TITLE
Typo in Japanese tooltip for adding hosts

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#6298]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Go to Inventories -> Add a new host with the green plus button.
The tooltip has a typo:
![Screenshot from 2020-03-16 14-14-46](https://user-images.githubusercontent.com/19942822/76788332-1648a580-6791-11ea-9b9a-2a627cd6d286.png)

Context in english to help you spot the location:
![69465377-44b3f800-0d3e-11ea-9072-f6a5523c6f98](https://user-images.githubusercontent.com/19942822/76788363-282a4880-6791-11ea-941c-ce528d9c5e1e.png)

The text header reads:
> ホスト名
> host name、ip address、または ip address:port を指定してください。例:reo

There is a leftover string `reo` after the 例 that should be deleted. Unsure if you would write 例え or 例, but I would leave that to a native speaker.

**Comment by rh-tchuang** [comment]
Hi, the string has been fixed in Memsource, it will be carried over in the next version.
Cheers.

**Comment by ryanpetrello** [comment]
Thanks @rh-tchuang!
