### ISSUE TITLE
Sort-able information should be visible in resource lists

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#6300]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Based off of #4220 

There are a handful of ways we can sort the Template list:
- Name (Ascending/Descending)
- Modified (Ascending/Descending)
- Last Job Run (Ascending/Descending)
- Inventory (Ascending/Descending)
- Project (Ascending/Descending)
- Type

This is the view as it stands today:
![Screenshot from 2020-03-16 14-42-16](https://user-images.githubusercontent.com/19942822/76790000-5cebcf00-6794-11ea-8871-37ba5f3e407d.png)

As of now, only Name, Last Job Run, and Type (JT or WFJT) are visible on the list. While the sort works, sorting by something like inventory is essentially useless if the user can't identify which templates use that inventory from the list. 

These options are available, AFAIK:
1. Show all sort-able information in the Templates list. This could be crowded, but works.
2. Add non-default information to the list whenever the user decides to use it as a sort. For example, if they would like to sort by inventory, the inventory information appears in the list, and is otherwise hidden.
3. @jlmitch5 mentioned that we should probably move to something similar to the expanded/collapsed viewed in the original UI.

**Comment by mabashian** [comment]
This too would be addressed if we did #6189

**Comment by unlikelyzero** [comment]
Closing to test in  #6189

**Comment by tiagodread** [comment]
All sort-able information now are present on the tables model
![image](https://user-images.githubusercontent.com/12464858/106642105-b6a0e780-6566-11eb-97d5-f2311f44dc54.png)
