### ISSUE TITLE
awx Docker images contain corrupt rpmdb

### ISSUE THREAD

**Issue by JG127** [ansible/awx#6306]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When building a Docker image on top of the official AWX images it is impossible to run yum. There are errors about the rpm database being corrupted. The way it is corrupted makes it impossible to even rebuild the rpm database. 

##### ENVIRONMENT
* AWX version: 9.3.0
* AWX install method: n/a
* Ansible version:  n/a
* Docker version: 19.03.8, build afacb8b7f0
* Operating System: Linux Mint 19.3 amd_64
* Web Browser: n/a

##### STEPS TO REPRODUCE
Make this simple Dockerfile:

```
FROM ansible/awx_web:9.3.0
USER root
RUN yum -y update
```

Run from the command line: 
```
docker system prune -f
docker build .
```

##### EXPECTED RESULTS
The command **yum -y update** should have been executed successfully. 

##### ACTUAL RESULTS
```
$ docker build .
Sending build context to Docker daemon  4.096kB
Step 1/3 : FROM ansible/awx_web:9.3.0
 ---> eb39bec62208
Step 2/3 : USER root
 ---> Running in 2b63c09a626d
Removing intermediate container 2b63c09a626d
 ---> d08ca9d4af78
Step 3/3 : RUN yum -y update
 ---> Running in ab0de35a9db6
error: rpmdb: damaged header #173 retrieved -- skipping.
error: rpmdbNextIterator: skipping h#     173 blob size(55540): BAD, 8 + 16 * il(78) + dl(54284)
CentOS-8 - AppStream                             12 kB/s | 4.3 kB     00:00    
CentOS-8 - Base                                 6.7 kB/s | 3.8 kB     00:00    
CentOS-8 - Extras                               4.4 kB/s | 1.5 kB     00:00    
CentOS-8 - PowerTools                            12 kB/s | 4.3 kB     00:00    
Extra Packages for Enterprise Linux 8 - x86_64  0.0  B/s |   0  B     00:00    
Failed to download metadata for repo 'epel'
Error: Failed to download metadata for repo 'epel'
The command '/bin/sh -c yum -y update' returned a non-zero code: 1
```

##### ADDITIONAL INFORMATION
It is not that uncommon the rpm database breaks. The usual method is to remove the broken files and rebuild the database. Consider the Dockerfile

```
FROM ansible/awx_web:9.3.0
USER root
RUN rm -f /var/lib/rpm/__db*
RUN rpm --rebuilddb
```
Building this Dockerfile results in
```
$ docker build .
Sending build context to Docker daemon  4.096kB
Step 1/5 : ARG awx_release=9.3.0
Step 2/5 : FROM ansible/awx_web:9.3.0
 ---> eb39bec62208
Step 3/5 : USER root
 ---> Running in f46533c6ac9d
Removing intermediate container f46533c6ac9d
 ---> 4a8dffe9b053
Step 4/5 : RUN rm -f /var/lib/rpm/__db*
 ---> Running in 7fb7f6bc4b1d
Removing intermediate container 7fb7f6bc4b1d
 ---> 94d3b540b30d
Step 5/5 : RUN rpm --rebuilddb
 ---> Running in eb9a22ec9ab9
error: rpmdbNextIterator: skipping h#     173 blob size(55540): BAD, 8 + 16 * il(78) + dl(54284)
error: failed to replace old database with new database!
error: replace files in /var/lib/rpm with files from /var/lib/rpmrebuilddb.1 to recover
The command '/bin/sh -c rpm --rebuilddb' returned a non-zero code: 1
```

Even rebuilding the rpm database is not possible. I have no clue where to get from here.

**Comment by hs-hub-world** [comment]
thanks, guys. Is there anything I can do at the moment to manually fix this to proceed forward. Or alternatively, is there a way for me to release an older version that includes the rabbitMQ -?  We are working on an ansible project and we have hit a dead end because of this ;(  Any assistance would be greatly appreciated. 

Thank you
HS

**Comment by jakemcdermott** [comment]
Hi there. Sorry you're having trouble with this. That said, we can't (and don't) support any kind of extensions to the base image or installer. You're totally welcome to do so, but you are on your own in terms of keeping it working once you do.

**Comment by JG127** [comment]
Okay then. Unusual in the Docker ecosystem, but it's your work after all.
Supposing somebody needs to extend the OS in the containers, what is the advised way to do so ?

**Comment by wenottingham** [comment]
This is an upstream issue, not much we can do in awx. See https://bugzilla.redhat.com/show_bug.cgi?id=1680124
