### ISSUE TITLE
Can't group VMWare hosts by tags

### ISSUE THREAD

**Issue by stobias123** [ansible/awx#6320]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I want to group vmware hosts by tags as described in new vmware inventory plugin. I cannot

##### ENVIRONMENT
* AWX version:  3.6.2
* AWX install method: operator
* Operating System: linux
* Web Browser: firefox

##### STEPS TO REPRODUCE

Try to add a vmware dynamic inventory and group by tags (not custom fields)

##### EXPECTED RESULTS

Groups, just like i get with vmware inventory plugin.

##### ACTUAL RESULTS

I only get host os groups.

**Comment by wenottingham** [comment]
That is an ansible tower version. If you are having issues with Ansible Tower please contact your support rep.

(In any case, the VMware inventory plugin is not used at this time. See https://github.com/ansible/awx/issues/3508 for details)
