### ISSUE TITLE
Can't use vault credential with inventory

### ISSUE THREAD

**Issue by stobias123** [ansible/awx#6321]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I followed the guide here -> https://docs.ansible.com/ansible/latest/scenario_guides/vmware_scenarios/vmware_inventory.html#using-vaulted-configuration-files

and encrypted my credentials with vault (the vmware credentials didn't work.)

I cannot use a vault credential to decrypt my inventory file.

##### ENVIRONMENT
* AWX version: 3.6.2
* AWX install method: k8s operator

##### STEPS TO REPRODUCE

Set up `vmware.yml` and encrypt with vault

##### EXPECTED RESULTS

I should be able to decrypt using a vault credential 

or....

use vmware credentials in tower to execute

##### ACTUAL RESULTS

error

**Comment by wenottingham** [comment]
-> #4089
