### ISSUE TITLE
Roles not downloaded during project sync

### ISSUE THREAD

**Issue by chris-p-martin** [ansible/awx#6328]
##### ISSUE TYPE
 - Role download setting on the system not honoured when running project sync

##### SUMMARY
When the "Enable role download" setting is enabled in the settings page of the Ansible AWX server, the project import process skips checking for requirements.yml and downloading of roles.

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: Docker on Linux
* Ansible version:  2.8.5
* Operating System: RHEL7
* Web Browser: Chome

##### STEPS TO REPRODUCE

1. Launch Ansible AWX infrastructure using the inventory and install.yml scripts on GitHub.
2. Ensure "Enable role download" setting
2. Import a project which contains a roles/requirements.yml file. 
3. Start a sync. 
4. Sync will skip the requirements.yml file and downloading of roles

##### EXPECTED RESULTS

I expect the project update process to check for requirements.yml and download roles accordingly. 

##### ACTUAL RESULTS

The detection of a requirements.yml file was skipped

##### ADDITIONAL INFORMATION

This starts to work by commenting out the when clause "when: roles_enabled|bool" in project_updates.yml

**Comment by wenottingham** [comment]
Roles are downloaded when the project is checked out for execution, not when the project revision is synced.

**Comment by egmar** [comment]
It was also discussed here https://github.com/ansible/awx/issues/5826

**Comment by blomquisg** [comment]
Works as expected
