### ISSUE TITLE
Password Store integration

### ISSUE THREAD

**Issue by sparunakian** [ansible/awx#633]
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY

Hi,

Would it be possible to integrate [Password Store](https://www.passwordstore.org/) to AWX, in order to facilitate the use of the [`passwordstore` lookup](https://docs.ansible.com/ansible/latest/playbooks_lookups.html#the-passwordstore-lookup)? At this time, configuring Password Store (and GPG) with AWX is not convenient due to the usage of Docker.

AWX could periodically pull a pass git repository in order to update passwords. It could also push the repository when passwords are registered with the `passwordstore` lookup. It should also manage the GPG key.

Regards

**Comment by wenottingham** [comment]
This should be done with a custom credential type that the lookup plugin would use; it would not be used by AWX itself.

**Comment by sparunakian** [comment]
I don't think Ansible should be the one managing everything. In my opinion Ansible should be the one commiting and pulling/pushing new modifications and AWX should be the one managing the GPG key and the setup of the git repository.

**Comment by wenottingham** [comment]
For this, I'd suggest adding a passwordstore credential plugin, a la the hashivault and CyberArk ones.
(#3098 )
