### ISSUE TITLE
Survey List Clean up

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#6333]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
This issue is designed to be a place to address some small things within the survey list.

- [x] Make sure default passwords are hidden in the list!
![Screenshot from 2020-03-26 15-37-50](https://user-images.githubusercontent.com/19942822/77689567-40138080-6f78-11ea-981d-f09d3c1eb1a4.png)

- [x] Move the select all button to be aligned with the select all buttons on the list.

- [x] Default value column needs some sort of header (like hosts https://tower-mockups.testing.ansible.com/patternfly/hosts/hosts/)

- [x] Survey List items that are required should have a red asterisk next to the question name.

- [x] https://github.com/ansible/awx/issues/6333#issuecomment-605000604

- [x] Add RBAC to Survey- For those that cannot edit the survey (!user_capabilities edit or delete) the tab shown should say View Survey.  Once on the survey action buttons are hidden and the only active button is Preview.

(danny)
linking my comment with a few items in here that we may or may not want to include in this issue: https://github.com/ansible/awx/issues/5895#issuecomment-600788774

**Comment by dsesami** [comment]
small nuance:

1. Select-all (or any) of the survey list items. 
2. Click delete to go to the confirmation modal.
3. Click cancel

In _most_ applications, the items would still be selected; however, they are all deselected.

**Comment by dsesami** [comment]
This was closed in error.

**Comment by dsesami** [comment]
Survey limits don't seem to be honored.
1) Create a text survey named `foo`
2) Make the default value `bar`
3) Set the character limit max to `1`

I would expect this to not be allowed.

**Comment by dsesami** [comment]
Trying to turn on the survey from the list page when the JT is missing a project or inventory results in a 400 with no further information.

**Comment by unlikelyzero** [comment]
@AlexSCorey reopening for `needs_test`

**Comment by dsesami** [comment]
@AlexSCorey I still see the behavior in this comment: https://github.com/ansible/awx/issues/6333#issuecomment-605000604

Do we want to change this?

Everything else looks good.

**Comment by dsesami** [comment]
The above doesn't look like it's happening in devel anymore! :+1:
