### ISSUE TITLE
Adding option in UI for Inventory synced with GCE for VAR "INVENTORY_IP_TYPE:"

### ISSUE THREAD

**Issue by yocode** [ansible/awx#634]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI
 - Installer

##### SUMMARY
In the gce.py script there is an option to set 'INVENTORY_IP_TYPE' to 'internal or 'external'. this instructs gce.py to set the "ansible_ssh_host:" to the private IP instead of defaulting to the public IP. I looking at ways of setting this environmental variable in the docker-compose.yml, but I think it would be way cooler if it was a selectable box on the UI when creating a Dynamic GCE Inventory.

If anyone's open to discuss how to accomplish this then I might take a crack at it.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: docker
* Ansible version:  X.Y.Z
* Operating System: Windows
* Web Browser: Chrome

**Comment by matburt** [comment]
go for it!

**Comment by shanemcd** [comment]
If this is still relevant in the new UI please open a new issue.
