### ISSUE TITLE
Jobs not running with external PostgreSQL database after PR #6034

### ISSUE THREAD

**Issue by egmar** [ansible/awx#6340]
##### ISSUE TYPE
Jobs not running with external PostgreSQL database after PR https://github.com/ansible/awx/pull/6034

##### SUMMARY
Jobs not running with external PostgreSQL database after PR https://github.com/ansible/awx/pull/6034
I've found that the issue is in following code:
https://github.com/ansible/awx/blob/db7f0f9421853f2489ebb2f6b904202986dee99a/awx/main/dispatch/__init__.py#L72-L78

Replacing it with:
```
    conn = psycopg2.connect(dbname=conf['NAME'],
                            host=conf['HOST'],
                            user=conf['USER'],
                            password=conf['PASSWORD'],
                            port=conf['PORT'],
                            sslmode=conf["OPTIONS"]['sslmode'])
```
enables job execution (note: this is specific to my setup which omits some options in credentials.py which are part of default AWX K8S credentials.py.j2 template, specifically I'm not using 'sslrootcert': '{{ ca_trust_bundle }}')

##### ENVIRONMENT
* AWX version: 9.3.0 (devel branch)
* AWX install method: kubernetes
* Ansible version:  2.9.3

##### STEPS TO REPRODUCE

1) Deploy latest AWX devel in Kubernetes with external PostgreSQL database.
2) Execute job

##### EXPECTED RESULTS

Job should execute

##### ACTUAL RESULTS

Job stays in pending with exceptions in `awx-task` log

##### ADDITIONAL INFORMATION

Didn't open a PR since there might be more option in following file, and should be a clever way to enable them in `psycopg2.connect()` method. https://github.com/ansible/awx/blob/devel/installer/roles/kubernetes/templates/credentials.py.j2

**Comment by ryanpetrello** [comment]
Thanks for reporting, @egmar - could you open a PR with the `sslmode` change?

**Comment by egmar** [comment]
Yes, I can, the question is about other options
right now the code also have 'sslrootcert': '{{ ca_trust_bundle }}',

**Comment by ryanpetrello** [comment]
Yea, good point.  Let me chat w/ @chrismeyersfsu about this - maybe there's a better way to handle the connection from those args.

**Comment by egmar** [comment]
I've looked in docs and environment variables could be an option, see:
https://www.psycopg.org/docs/module.html?highlight=connect#psycopg2.connect
> Any other connection parameter supported by the client library/server can be passed either in the connection string or as a keyword. The PostgreSQL documentation contains the complete list of the supported parameters. Also note that the same parameters can be passed to the client library **using environment variables**.

**Comment by ryanpetrello** [comment]
This might be better:

```
 conn = psycopg2.connect(dbname=conf['NAME'],
                            host=conf['HOST'],
                            user=conf['USER'],
                            password=conf['PASSWORD'],
                            port=conf['PORT'],
                            **conf["OPTIONS"])
```

**Comment by egmar** [comment]
ok, let me open the PR then

**Comment by ryanpetrello** [comment]
@egmar I'm gonna open this back up because I'd like to make a point to add some regression testing for this on our end (and the `needs_test` label on an open issue helps us track that work).

**Comment by kdelee** [comment]
@ryanpetrello we have a job that tests openshift installs pointed against rds database, it just does not run every night (RDS has to be set up for it...this is just in backlog for automating / will be covered by the data generation pipeline that is WIP). I set up an rds database and kicked it off. Install worked and all tests are passing, going to call this verified.
