### ISSUE TITLE
DataListCell doesn't wrap

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#6351]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Most of our lists have a text wrapping issue.  Whoever picks up this issue will need to audit all of the lists and use the DataListCell component in `/components` to resolve a wrapping issue.  This has already been implemented in `SurveyList.jsx`

Once https://github.com/patternfly/patternfly-react/issues/3938 has been resolved this issue can be removed/ignored.

##### ENVIRONMENT
* AWX install method:  docker for mac
* Ansible version:  2.9
* Operating System: Mojave
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Go to any list (except survey list) and enter text that is really super long such that it should wrap.
##### EXPECTED RESULTS
The text should wrap
##### ACTUAL RESULTS
The text doesn't wrap

**Comment by mabashian** [comment]
I _think_ this will be resolved the next time we upgrade our PF deps

**Comment by marshmalien** [comment]
PatternFly Status Update:
This [issue](https://github.com/patternfly/patternfly/issues/3087#issuecomment-690734544) was fixed in PF Core v4.40.0
