### ISSUE TITLE
Searching keyword finds more than I expected at Templates menu

### ISSUE THREAD

**Issue by JosephJHCho** [ansible/awx#6359]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Searching keyword finds more than I expected at Templates menu

##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.3
* Operating System: Centos7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Create Job Templates with name prefix N_CAT01_ , R_CAT01_ and   T_CAT01_  serveral kinds.
2. Repeat 1. with changing prefix number  01 to 02, 10, 11.
3. Search with keyword T_CAT10  (or T_CAT11)
4. Results have N_CAT10_xxx (or N_CAT11_xxx)

##### EXPECTED RESULTS

Do not find templates which doesn't have keyword in name

##### ACTUAL RESULTS

One or two job templates not related with keyword was found.

##### ADDITIONAL INFORMATION

![T_CAT10](https://user-images.githubusercontent.com/25745571/77148646-4b2b6400-6ad3-11ea-987a-6c4a92e30ce5.png)
![T_CAT11](https://user-images.githubusercontent.com/25745571/77148650-4c5c9100-6ad3-11ea-90eb-de62446c7049.png)

**Comment by unlikelyzero** [comment]
@JosephJHCho Hey! I just tried to reproduce this and cannot reproduce it unless I set the JT Description field to T_CAT10. The JT Search results includes the Description field as well. 

Could that be the problem?

**Comment by JosephJHCho** [comment]
@unlikelyzero You gave me hint to try this. Description field is blank but playbook name has include that keyword. So If I changed the keyword "name:T_CAT10" then I works fine. Thanks.
