### ISSUE TITLE
[awx-pf] Can't edit job templates

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#6366]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Tried to edit the name and description of a job template. It doesn't change when I click save.

Reproduction:
1. Make a job template
2. Try to edit various things about it. pretty straightforward. I don't see any 400s or anything, though feel free to poke around and see what you find.

**Comment by AlexSCorey** [comment]
https://github.com/ansible/awx/pull/6368#pullrequestreview-379431124
