### ISSUE TITLE
Document connecting to websocket for 3rd parties

### ISSUE THREAD

**Issue by alexshchur** [ansible/awx#6371]
##### ISSUE TYPE
I wasn't able to find any info on how do I connect to websocket. Only this issue: https://github.com/ansible/awx/issues/2468

I've tried to create a Websocket client with Nodejs and subscribe to jobs status changes with this payload:
```
"groups": {"jobs": ["status_changed"], "schedules": ["changed"], "control": ["limit_reached_1"]}
```

but the messages just don't come from the server, although there're no error messages returned from it.

##### SUMMARY 
It's not clear how to connect to websocket server. Can this be documented? Thanks

**Comment by jakemcdermott** [comment]
Hi there. Websocket docs for developers and integrators live here: https://github.com/ansible/awx/blob/devel/docs/websockets.md

**Comment by Huihuihh** [comment]
I think https://github.com/ansible/awx/blob/devel/docs/websockets.md not clear enough
I get a connect like this
```
GET http://host_ip/websocket
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Key: j3yqVPvgFHBbY/DM72JDIg==
Sec-WebSocket-Version: 13
Authorization: Bearer gO9WZeD9dVz3Vv81dXpHl8n8Ae5FFI
```
and could not get any response
