### ISSUE TITLE
API support for child jobs of a workflow job

### ISSUE THREAD

**Issue by tp199314** [ansible/awx#6373]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
I was wondering if there is an API funktion or some kind of variable which contains the IDs of all "child jobs" of a workflow job.
Background of this question is:
I would like to pass diffrent credentials to some jobs inside the workflow. For this i would like to get all "child job id's", check the job template id of each job, and then if needed, pass the required credential to the job via v2/jobs/225/credentials/.

Passing the credentials to a node (via workflow_job_template_nodes/3/credentials/) does not fit my requirement, since i would like to run the jobs in parallel with diffrent credentials.

Please tell me if you would like to have this feature inside awx, or if there is a workaround of other simple code snippets which will do the trick.

Kind regards, tp199314

**Comment by ryanpetrello** [comment]
Hey @tp199314,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
