### ISSUE TITLE
the result formats from "windows" and "linux" using ansible "setup" module seems different

### ISSUE THREAD

**Issue by smilemare** [ansible/awx#6374]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

I'm using ansible tower 3.6.2 for trial now. 
When I using logging aggregator for outputing job result to ELK, I found that the result formats from "windows" and "linux" using ansible "setup" module seems different, so that elasticsearch couldn't index the result into the database.

the error as below:
[WARN ][logstash.outputs.elasticsearch][main] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"logstash", :routing=>nil, :_type=>"_doc"}, #<LogStash::Event:0x1d453650>], :response=>{"index"=>{"_index"=>"logstash-2020.03.21-000001", "_type"=>"_doc", "_id"=>"Gz_1AHEBityPu4K--hoG", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"object mapping for [event_data.res.ansible_facts.ansible_interfaces] tried to parse field [null] as object, but found a concrete value"}}}}

##### ENVIRONMENT
* AWX version: 3.6.2(Ansible tower)
* AWX install method: using setup-bundle from https://releases.ansible.com/ansible-tower/setup-bundle/ to intall
* Ansible version:  2.9.1
* Operating System: 
Red Hat Enterprise Linux Server release 7.4 (Maipo)
* Web Browser: chrome

##### STEPS TO REPRODUCE
1\ configure logging aggregator to logstash,  output the result to elasticsearch and kibana
2\ using SETUP module to get facts from windows and linux hosts.
3\ elasticsearch template setting using auto mode
4\ observe the logstash log

##### EXPECTED RESULTS

the setup module to get facts results from linux can index by elasticsearch

##### ACTUAL RESULTS

when I tried to find the the facts results from linux, I could not find the result in elasticsearch.

**Comment by smilemare** [comment]
facts in json:

**windows host**
"ansible_interfaces": [
          {
            "default_gateway": null,
            "dns_domain": null,
            "macaddress": "00:21:00:A0:03:10",
            "connection_name": "VMware Network Adapter VMnet1",
            "interface_index": 18,
            "interface_name": "VMware Virtual Ethernet Adapter for VMnet1"
          },


**linux host**

"ansible_interfaces": [
          "lo",
          "virbr0",
          "virbr0-nic",
          "ens33"
        ],

**Comment by ryanpetrello** [comment]
@smilemare that fact data comes directly from Ansible (not AWX).  If you're seeing different data on different platforms, you might want to ask in the Ansible IRC or mailing list; this tracker is for bugs in AWX itself.
