### ISSUE TITLE
Host event type and reference errors when opening host details modal for some job events

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#6380]
##### ISSUE TYPE
 - Bug Report

##### STEPS TO REPRODUCE
- Run a few job templates with various tasks and event types
- Click into the host details modal for each line

##### EXPECTED RESULTS
- The modal opens when an event is clickable

##### ACTUAL RESULTS
- Depending on the structure of the host event data for that line, errors due to missing fields can occur and prevent the modal from loading

##### ADDITIONAL INFORMATION
![host_event_type_errors](https://user-images.githubusercontent.com/9753817/77334629-755f6a80-6cfb-11ea-9119-db7e43893d27.gif)

**Comment by dsesami** [comment]
Ran A/B testing on this for the commits; the modal opens and renders correctly
