### ISSUE TITLE
Labels don't save on JT with not Inventory

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#6382]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 2.9
* AWX install method: docker for mac
* Ansible version:  9.3
* Operating System: Mojave
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create a JT with not inventory, but prompt on launch selected for that inventory.  Adds labels to the JT
##### EXPECTED RESULTS

The template saves just fine.

##### ACTUAL RESULTS

The template fails to save. 

##### ADDITIONAL INFORMATION

This is happening because we are sending an OrgId each time we associate a label to a job template, which isn't necessary.  We only need to send the orgID when we generate a brand new label (which is likely the real bug here).   Currently we are getting the orgID from the inventory that is associated with the Job template. It looks like, in the OLD UI, we hit api to get a list of orgs each time a JT is saved.  If no brand new label it associated with that JT it looks like that list of orgs is ignored. If the JT has a brand new generated label the ui seems to use the first organization in the list as the label's org ID.

**Comment by dsesami** [comment]
This bug has been resolved; prompt on launch inventories can be saved.
