### ISSUE TITLE
Options for notification templates not set when using frontend

### ISSUE THREAD

**Issue by tp199314** [ansible/awx#6383]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Options for notification templates are not set when using the frontend. When using the API there is no problem.

##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.3
* Operating System: Ubuntu 18.04 (for AWX), Client is on Windows 10
* Web Browser: Chrome 80.0.3987.149

##### STEPS TO REPRODUCE

1. Choose a notification template
2. Select "Use TLS" or "Use SSL" in the "Options" Menu
3. Hit save - no options will be saved.

1. Going to api/v2/notification_templates/n/
2. In the content, change ""use_ssl": false," to ""use_ssl": true,"
3. Hit Patch - options will be saved and shown correctly in the frontend

##### EXPECTED RESULTS

Options will be saved

##### ACTUAL RESULTS

Options will only be saved when using the API, Fronted does not work

##### ADDITIONAL INFORMATION

**Comment by unlikelyzero** [comment]
Verified on 3.7 and added to a test stub
