### ISSUE TITLE
don't update last_modified datetime on unified_job_templates list endpoint when template is launched.

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#639]
Mockup for context:

<img width="501" alt="mockup" src="https://user-images.githubusercontent.com/1342624/32792954-aa7c9ea0-c932-11e7-8635-11e8b398664b.png">

The goal of showing "modified by" in the list is to give an idea to the user as to when the last time the template form was updated.

If the value is updated on launch, it more-or-less is redundant with the last used information.

**Comment by shanemcd** [comment]
Seems like this got resolved at some point, per @john-westcott-iv who was looking at his dev env.
