### ISSUE TITLE
Error while running docker as sudo on ubuntu server.

### ISSUE THREAD

**Issue by BluGeni** [ansible/awx#64]
### Summary

If you run docker have to run docker as sudo you get this error:

`"Error connecting: Error while fetching server API version: ('Connection aborted.', error(13, 'Permission denied'))`

### Environment

* Operating System: Ubuntu 16.04

### Additional Information:

Followed this guide to fix the issue:
https://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo

Not sure if this is something worth documenting or not. Hopefully this helps save someone some troubleshooting.

**Comment by wwitzel3** [comment]
Thanks @BluGeni. This is a general docker configuration issue, but I think making a note of this is good as others will probably run in to the same problem as they start using awx.
