### ISSUE TITLE
Project Job Templates tab shouldn't allow creation of WFJTs

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#6413]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Not necessarily a bug, but just "too much functionality". When adding a Job Template within the context of the Project page, it automatically associates the project with the JT. This makes sense. However, the add button also allows you to create workflows, which doesn't make a lot of sense because they aren't associated with a single project:

![Screenshot from 2020-03-25 09-43-34](https://user-images.githubusercontent.com/19942822/77543308-e464cc80-6e7d-11ea-9784-fd968939b3b5.png)

The button should only allow you to add a JT.

Steps:
1. Create a project
2. Visit that project's tab called "Job Templates"
3. Attempt to add a template

**Comment by jakemcdermott** [comment]
This is simple enough to fix in ui_next. I'm not convinced it is worth it to fix it in the old ui.

**Comment by dsesami** [comment]
Button directly links to the create new job template form. This makes more sense, thanks. :+1:
