### ISSUE TITLE
Swap custom Toggles with PF Toggle Button Group

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#6414]
##### SUMMARY
When PatternFly's toggle button group lands we should swap our custom button toggles for their component. 

PatternFly Toggle Button issue: https://github.com/patternfly/patternfly/issues/2625
PF React Feature request: https://github.com/patternfly/patternfly-react/issues/3847

_Variables toggle_
<img width="115" alt="Screen Shot 2020-03-25 at 11 03 09 AM" src="https://user-images.githubusercontent.com/15881645/77551117-56421380-6e88-11ea-8226-1edf30468a4f.png">

_Schedule Detail toggle_
<img width="129" alt="Screen Shot 2020-03-25 at 11 03 03 AM" src="https://user-images.githubusercontent.com/15881645/77551119-56daaa00-6e88-11ea-9341-4a8b0b06a1e0.png">

**Comment by mabashian** [comment]
http://patternfly-react.surge.sh/components/toggle-group is a thing now (beta).  So I think we can move forward with this issue.  (We may need to upgrade our PF deps to get it, I'm not sure).

**Comment by unlikelyzero** [comment]
@nixocio was this included in the recent patternfly update you did?
