### ISSUE TITLE
Simple search on SCM type does not work

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#6423]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When searching in the Project list, one can use a search filter called "Type". This is an SCM type, which provides a second dropdown that can filter for Git, Mercurial, etc. 

This search does not return any results.

Recreation steps:
1. Make a project. Don't sync it (unsure if this affects anything). Use Git.
2. Search filter on Git projects.

One expects the project to appear in the list, but the list is empty.

Before:
![Screenshot from 2020-03-25 14-31-38](https://user-images.githubusercontent.com/19942822/77572442-5bfa2200-6ea5-11ea-9c4b-8550aba4d39c.png)

After:
![Screenshot from 2020-03-25 14-31-30](https://user-images.githubusercontent.com/19942822/77572456-61576c80-6ea5-11ea-8e50-a1f975b630d1.png)

**Comment by jlmitch5** [comment]
this has been tested and merged, closing (cc @dsesami just for a heads up)
