### ISSUE TITLE
Add support for approval notification toggle on WFJT notifications

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#6425]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
It's missing from UI Next:

<img width="1382" alt="Screen Shot 2020-03-25 at 12 00 22 PM" src="https://user-images.githubusercontent.com/9889020/77576760-1725b980-6eac-11ea-840b-e7d2841ea484.png">

This should only be visible on WFJT and Org notifications:

<img width="1517" alt="Screen Shot 2020-03-25 at 3 22 09 PM" src="https://user-images.githubusercontent.com/9889020/77577025-80a5c800-6eac-11ea-84a7-e6bbcd6b3617.png">

**Comment by mabashian** [comment]
Probably best to just reference the old UI when working on/verifying this enhancement in case I've missed some details.

**Comment by dsesami** [comment]
Stubs exist, so this can be closed with the merge of #7803
