### ISSUE TITLE
Email notifications are coming even if its disabled

### ISSUE THREAD

**Issue by unbreakabl3** [ansible/awx#6431]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I enabled email notification in Templates on SUCCESS and on FAILURE and started to get the emails. All is ok. After that I disabled the notification on SUCCESS and on FAILURE, but still getting the emails.
I deleted the template and created a new one to test the behavior. Its the same.
The same behavior is for the Projects notifications. Looks like that once its enabled, you cannot to disable it.

![image](https://user-images.githubusercontent.com/13556249/77627074-00846e80-6f4f-11ea-9337-3181b1e7c20a.png)

##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.3
* Operating System: Ubuntu 18.04
* Web Browser: Any

##### STEPS TO REPRODUCE

Enable the email notification in Templates or Projects and disable it.

##### EXPECTED RESULTS

The emails notifications shouldn't come

##### ACTUAL RESULTS

Emails are still coming

**Comment by jakemcdermott** [comment]
Hello.

I tried the steps exactly as you described them and I'm not seeing any email notifications when the notification is disabled.

It's likely you have another notification enabled somewhere - please verify that this isn't the case. If you're still experiencing difficulty you will need to provide more details for us to reproduce the problem. Please include a minimal test case (assume a completely clean install) and specify all resources created, including the test data you used for each field of any resource created. Thanks!

**Comment by unbreakabl3** [comment]
Hello,
I checked all notifications settings 10 times. All notification settings are disabled. 
I’m getting a notifications from the job which is failed or succeeded when I run THIS job. Where else it can be enabled?

**Comment by ryanpetrello** [comment]
@unbreakabl3,

Are any notifications defined or enabled at the organization level?

**Comment by unbreakabl3** [comment]
> 
> 
> @unbreakabl3,
> 
> Are any notifications defined or enabled at the organization level?

All of them are disabled.
I just did the reinstall and all is working well.
Thank you.
