### ISSUE TITLE
Retreive list of  a repository tags to populate a multiple choice list in survey

### ISSUE THREAD

**Issue by sbarbo01** [ansible/awx#6436]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
We use Ansible to deploy applications based on a repository (gitlab/github)...
When playbook is launch, extra variable is used to specify which version to install (eg: version=1.1)
This work but can be cause of error.

It would be better to retreive list of available tags and populate variable in survey to allow the choice of correct version, just like it can be done in jenkins

Regards.

**Comment by wenottingham** [comment]
-> #20
