### ISSUE TITLE
Can enable provisioning callback on inventory-less job templates

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#644]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY

1. Create job template
2. Set inventory to prompt on launch (no default)
3. Enable provisioning callback
4. Hit save

##### ENVIRONMENT
* AWX version: any

##### EXPECTED RESULTS

Error (because that isn't going to work)

##### ACTUAL RESULTS

Succeeds. AWX 500s if you hit the callback.

**Comment by AlanCoding** [comment]
fix is in
