### ISSUE TITLE
Update JobTemplate formik use in order to not require context/formikBag

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#6440]
in #6385 we converted the JT Form to using the useField hooks...in the process there are some quirks of that form that made us have to utilize the formik context.  Specifically:
- organization is currently set via the inventory change...we will be moving this out of the form into the edit/add pages based on the project's organization.
- currently the validation for the inventory is a bit weird (it doesn't use the validators, instead puts the validation text and DOM directly in the form).  It needs the formik context right now because it uses the prompt checkbox in addition to the field value to set required validity.  There might not be an easy way to change this, so we may end up requiring the formik context, but it's worth taking a look to see if this can be done in a more consistent way to the rest of the validation.

**Comment by mabashian** [comment]
I'm unclear on whether or not this is still relevant but it seems like it would be ready for dev if it is.

**Comment by mabashian** [comment]
Closing - I'm not sure that this is still relevant given the number of changes that have been made to this page.
