### ISSUE TITLE
[awx-pf] Job Template Description field is no longer returned by default in Job Template searches

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#6442]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
In the original tower UI, if a user searched on the Job Template Searchfield, both Job Template Name and Job Template Descriptions results were returned. In `ui_next`, only the Job Template Name is returned.

##### ENVIRONMENT
* AWX version: 9.3.0

##### STEPS TO REPRODUCE
1. Create or update a Job Template Description with "afilteredresponse"
2. Open up Job Templates Page and search for "afilteredresponse"

Note that the Job Template is not returned.

##### EXPECTED RESULTS
Users may expect JT Page searches to include JT Names and Description fields

##### ACTUAL RESULTS
Only the JT Name field is filtered

##### ADDITIONAL INFORMATION
See issues like: https://github.com/ansible/awx/issues/6359

**Comment by dsesami** [comment]
since simple search implementation now involves dropdowns with keywords, it might be good to change the way we implement this with a filter to search by Description separately. This is my personal opinion.

**Comment by dsesami** [comment]
#6937 resolves this, as there is now an explicit way to search by description.

**Comment by unlikelyzero** [comment]
@dsesami can we just add a test for search by name and a separate test for search by description?

**Comment by dsesami** [comment]
@unlikelyzero absolutely; they should be separate tests.

**Comment by dsesami** [comment]
Closing this out as stubs were created and merged a while back, but this issue wasn't closed.
