### ISSUE TITLE
failed to add user in credential permissions 

### ISSUE THREAD

**Issue by rajeshwer** [ansible/awx#6450]
Tried to add user to credential with use permission but unsuccessful 

##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.3
* Operating System: oel
* Web Browser: chrome/safari

##### STEPS TO REPRODUCE

select credential 
select permissions
selct user ---> key use----> save ---> working and exits but action was unsuccesful

##### EXPECTED RESULTS
select credential 
select permissions
selct user ---> key use----> save --->  show user with use permissions

**Comment by jakemcdermott** [comment]
Hi there. I can't reproduce this with the steps you provided.

![cred_role_add](https://user-images.githubusercontent.com/9753817/77702590-44976380-6f8f-11ea-8011-e6073c06e69f.gif)

if you're still experiencing difficulty, please provide additional details on how to reproduce what you are experiencing. Include a minimal test case with all resource creation steps explicitly documented, including the test data used for each field.

**Comment by rajeshwer** [comment]
I am running 9.2.0 version pleass find below
 
 ![http://g.recordit.co/3uVJ8JIccy.gif)

**Comment by rajeshwer** [comment]
> Hi there. I can't reproduce this with the steps you provided.
> 
> ![cred_role_add](https://user-images.githubusercontent.com/9753817/77702590-44976380-6f8f-11ea-8011-e6073c06e69f.gif)
> 
> if you're still experiencing difficulty, please provide additional details on how to reproduce what you are experiencing. Include a minimal test case with all resource creation steps explicitly documented, including the test data used for each field.

 I am running 9.2.0 version pleass find below
 
 ![http://g.recordit.co/3uVJ8JIccy.gif)

**Comment by jakemcdermott** [comment]
:wave: Hey there. Please provide a minimal test case (assume a completely new install) with all resource creation steps explicitly documented, including the test data used for every field of every resource you created.
