### ISSUE TITLE
Intermittent errors - 503 and Connection Reset

### ISSUE THREAD

**Issue by rlundatwork** [ansible/awx#6453]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
We are using Jenkins (recently updated) and the Ansible Tower plugin to connect to our AWX tower. Most of the time, it works great, but lately, the tower will some times not respond correctly to Jenkins. Again, this does not happen always, but frequently enough to be a major concern.

When the issue occurs, the error messages I receive in Jenksin are along these lines:

ERROR: Failed to get job status from Tower: Unable to make tower request: Connection reset
ERROR: Failed to get job events from tower: Unexpected error code returned (503)

I have not seen the web interface fail, and the jobs do complete normally. The issue lies in communication between Jenkins and AWX.

Jenkins and all the plugins were recently updated.

The person who installed AWX is no longer with us, and I don't know where else to go to help me troubleshoot this.

##### ENVIRONMENT
* AWX version: 9.0.0.0
* AWX install method: openshift sts
* Ansible version:  2.8.5
* Operating System: N/A
* Web Browser: N/A
* Jenkins: 2.204.2
* Jenkins Ansible plugin: 1.0
* Jenkins Ansible Tower plugin: 0.14.0

##### STEPS TO REPRODUCE

In the Jenkins pipeline, the following code handles the Ansible part:

wrap([$class: 'AnsiColorBuildWrapper', colorMapName: "xterm"]) {
   ansibleTower(   [parameters]  )

This is hard to reproduce as it only fails intermittently.

##### EXPECTED RESULTS

Message in Jenkins pipeline log:

Tower completed the requested job

##### ACTUAL RESULTS

Message in Jenkins pipeline log:

ERROR: Failed to get job status from Tower: Unable to make tower request: Connection reset

or

ERROR: Failed to get job events from tower: Unexpected error code returned (503)

(There may be more messages, but these are the ones I have collected so far)

**Comment by jakemcdermott** [comment]
Hello! Thanks for creating this issue.

> The issue lies in communication between Jenkins and AWX.

You'll need to rule out that this isn't an issue between jenkins<--> AWX plugin itself, first. I think it might be. 

That is not something we support directly.
