### ISSUE TITLE
Survey multiple choice options need improvements and error handling

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#6464]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
From https://github.com/ansible/awx/issues/5900#issuecomment-605008285:
cc @keithjgrant 

> Both add and edit forms for JT surveys need some way of clarifying how to format single-select and multi-select options. It is trivial to create modal-overlay 400 errors with the basic input textbox given, and these 400 errors do not provide any useful information to the end user.

##### STEPS TO REPRODUCE
Put bad input into a job template survey with either single or multi-select. semicolons in random spots, etc, in an attempt to break it. some things work, some don't.

##### EXPECTED RESULTS
Form validation on submission that keeps you on the form page, indicating formatting errors or something similar when met with a 400 error. I would also like information around the box about how to format the survey.

##### ACTUAL RESULTS
400 that takes you back to the survey list, no further information about the error.

**Comment by mabashian** [comment]
@keithjgrant gonna remove you for now - if you do want to jump in on this one feel free to reassign yourself.
