### ISSUE TITLE
[UI] YAML Format input box shows JSON format data

### ISSUE THREAD

**Issue by kedark3** [ansible/awx#6466]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
 I see following Bug, as you may see when I launch JT, it shows "YAML" radio button selected but "JSON" formatted variable. In the background though, you can see I have set the variable in YAML format in the JT itself. When I click JSON and back to YAML, it gets fixed by itself. no loss of functionality just buggy ui 

##### ENVIRONMENT
* Tower 3.6.3 
* AWX install method: setup_bundle on RHEL VM
* Ansible version:  2.9.1
* Operating System: RHEL
* Web Browser: Firefox (seems non relevant to me)

##### STEPS TO REPRODUCE

Create a JT with YAML format Extra vars as shown in screenshot below and "Prompt extra vars" on launch. This will cause you to see the issue. 

##### EXPECTED RESULTS

Format should be YAML if YAML radio button is selected.

##### ACTUAL RESULTS

Format was JSON when Radio button YAML was selected. 

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/8180469/77790128-a234ba00-703a-11ea-819d-eb8702688df4.png)

**Comment by kedark3** [comment]
I think this may be caused by missing `---` on the top of Extra vars input box. But I couldn't reliably test that. There is no loss of functionality though. So low priority bug in my opinion. Just an UX thing.

**Comment by dsesami** [comment]
@jakemcdermott is this tested in awx pf or the angular UI? or both?

**Comment by dsesami** [comment]
this is now handled in ui_next and is stubbed within `job-template-prompt-on-launch.spec.js`
