### ISSUE TITLE
Multiple jobs on a different inventory items

### ISSUE THREAD

**Issue by unbreakabl3** [ansible/awx#6473]
##### ISSUE TYPE
 - Feature Idea/Question

##### SUMMARY
Hello,
We're using a remote REST API calls to create a host inside the inventory and start the existing jobs template on that host. The problem is when during the first run, another host added to same inventory. Another job starting to run, but because in the inventory there are two hosts, the second job will run on **both hosts**.
Is there any possibility, to run simultaneously a few jobs from the same template, but each one of them will be applied only on one host?

Please, excuse me. if I'm missing something.

Thanks a lot!

**Comment by jakemcdermott** [comment]
It sounds like you're already committed to making _some_  prior API calls before launching each job. With that in mind, have you considered using or applying a limit prompt on the job template(s) you are launching to restrict its execution to the specific host?

**Comment by unbreakabl3** [comment]
Hello,
I found the solution. Each time we're triggering the job via REST API, we set the LIMIT attribute with the specific IP. Working like a charm :)
Thanks!
