### ISSUE TITLE
Integrate ansible-cmdb

### ISSUE THREAD

**Issue by jomach** [ansible/awx#6475]
##### ISSUE TYPE
It would be cool if awx could expose https://ansible-cmdb.readthedocs.io/en/latest/usage/ for all inventories.

##### SUMMARY
Have page that is similar to https://ansible-cmdb.readthedocs.io/en/latest/usage/
What do you think?

**Comment by wenottingham** [comment]
This works on a very different model of inventory, and is not planned. (We actually had some fact comparison features in the codebase earlier that were removed due to practicality.)

It is *also* an incompatible license.
