### ISSUE TITLE
Failed to save toggle settings. Returned status: 504 | AWX 9.3.0 

### ISSUE THREAD

**Issue by Aniket-Utekar** [ansible/awx#6476]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 9.3.0
* AWX install method: docker on linux
* Ansible version:  2.9.6
* Operating System: Ubuntu 18.04.4 LTS
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

Not able to save settings in system tab --  "Allow External Users to Create Oauth2 Tokens" option to on.

Giving below error after clicking on "Allow External users to create Oauth2 tokens" as "Failed to save toggle settings. Returned status: 504"
##### EXPECTED RESULTS

When I toggle that option.. It went to working state.. after that it should allow me to click on "Save" button. But state is not changing for this thing.

##### ADDITIONAL INFORMATION

root@ansible-master:~/awx# ansible --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
root@ansible-master:~/awx# docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                    NAMES
f49ab0ce1d29        ansible/awx_task:9.3.0   "/tini -- /bin/sh -c…"   17 hours ago        Up 8 minutes        8052/tcp                 awx_task
27446f28aebb        ansible/awx_web:9.3.0    "/tini -- /bin/sh -c…"   17 hours ago        Up 8 minutes        0.0.0.0:8000->8052/tcp   awx_web
a3e1926e229c        postgres:10              "docker-entrypoint.s…"   17 hours ago        Up 8 minutes        5432/tcp                 awx_postgres
d226d0209c13        redis                    "docker-entrypoint.s…"   17 hours ago        Up 8 minutes        6379/tcp                 awx_redis
b22ba4b35b68        memcached:alpine         "docker-entrypoint.s…"   19 hours ago        Up 8 minutes        11211/tcp                awx_memcached
root@ansible-master:~/awx#

**Comment by jakemcdermott** [comment]
Hello. Sorry you're experiencing difficulty with your awx deployment.

We've been seeing a lot of bug reports mentioning 504s where they're not normally observed. In most cases this is because you've checked out the `devel` branch and ran an upgrade or install using container images pulled from docker hub - this won't work currently because we haven't published the containers yet. You'll need to build them yourself or check out a specific tag (e.g. 9.2) before running any installs or upgrades.
