### ISSUE TITLE
awx cli installer does not install a binary

### ISSUE THREAD

**Issue by jwlogemann** [ansible/awx#6479]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When I run the command pip install "https://github.com/ansible/awx/archive/$VERSION.tar.gz" which is mentioned in the readme it installs a bunch of python scripts in /usr/local/lib/python3.6/site-packages/awx  but there's no 'awx' binary I can run.

##### ENVIRONMENT
Redhat 7.7
##### STEPS TO REPRODUCE

1) pip install "https://github.com/ansible/awx/archive/$VERSION.tar.gz" 
2) awx --help

##### EXPECTED RESULTS

The ouput of the awx command

##### ACTUAL RESULTS

Got this output:
bash: awx: command not found

**Comment by jwlogemann** [comment]
I forgot to add that this is caused by the binary being renamed to 'awx-cli'

**Comment by ryanpetrello** [comment]
Hey @jwlogemann,

The awx release tarball itself is the source code for the AWX server, not the client libraries.

You _can_ install the CLI, which is a package within a subdirectory of the source tree, using a command like this:

`~ pip install "https://github.com/ansible/awx/archive/9.3.0.tar.gz#egg=awxkit&subdirectory=awxkit"`

![image](https://user-images.githubusercontent.com/214912/77927870-b9abb700-7275-11ea-890a-3bccabe0e43c.png)

Here's some additional instructions:

https://github.com/ansible/awx/tree/devel/awxkit/awxkit/cli

**Comment by ryanpetrello** [comment]
related: https://github.com/ansible/awx/pull/6481
