### ISSUE TITLE
Add play and task-level profiling information to job page detail display

### ISSUE THREAD

**Issue by ghost** [ansible/awx#648]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY

Add to AWX play and task level detail to the job details page, including started and elapsed times for individual plays and tasks listed in the job details.

##### ENVIRONMENT

* AWX version: 1.0.0

##### STEPS TO REPRODUCE

This feature would be used to conveniently evaluate the performance of particular plays and tasks in the context of overall job execution, with relevant information in a common location with other job details.

**Comment by matburt** [comment]
I think this would be a lot harder than one would think as ansible doesn't really give us this information and it would have to be inferred (possibly inaccurately). There are also implications on `free strategy` which I would imagine would make this not work very well.

Also... this would require some sort of tracking mechanic which would have the possibility to hurt job event processing performance.

I think the better place to solve this would be on the ansible side and then we could consume it and show it.
