### ISSUE TITLE
modal searches shouldn't be case-sensitive

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#6485]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Tried to search for an Organization when creating a user. "default" doesn't return the "Default" organization. This should be case-insensitive. in addition, this ticket should involve going through similar searches and ensuring that they are case-insensitive.

**Comment by jlmitch5** [comment]
interesting @dsesami we should be appending the __icontains filter to any string-based search key. https://github.com/ansible/awx/blob/22307bba977704a6b738ce92b3b67f61fc3a6383/awx/ui_next/src/components/Search/Search.jsx#L89

I don't know why that's not appending for that key...it seems it should based on the code

**Comment by mabashian** [comment]
This appears to be working to me.  Moving to needs_test.

**Comment by unlikelyzero** [comment]
covered in https://github.com/ansible/tower-qa/pull/5907
