### ISSUE TITLE
Feature: AWX Package Management / Auditing Functionality

### ISSUE THREAD

**Issue by MrBones757** [ansible/awx#6496]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

In our organisation we use Tower / AWX for a majority of internal package deployments.
We're currently undergoing a review of existing tooling in this space and a suggestion was made to see if AWX / Tower can achieve this functionality.

I've had a look though previous issues and cant really see anything about this, though i may have searched some incorrect keywords.

Basically, my idea to achieve this would be to add some mechanism to update a 'package inventory' - perhaps an extended version of the standard job template that exposes some additional fields
- a new 'dashboard' that allows search on application name, version, hostname

Fields would be pretty basic and would require (probably) require two new DB tables:
- one for software definitions (name, id, created, updated, version)
- one for software deployments (id, host, relation to software defn, install date, uninstall date)

An extension to the API that allows you to update these fields from an external source may also be required to allow retrofitting of existing playbooks with a new tower_package module. This woudl also allow several app installs to be completed in a single play.

I understand though that this may not be in the scope of what AWX is designed to do, but i would love some opinions / review on this to see if there is any interest for this kind of functionality.

**Comment by wenottingham** [comment]
See also https://github.com/ansible/awx/issues/6475.

The way I'd suggest doing this now is based on facts and utilizing the fact cache. But generally, at a certain scale, the CMDB probably shouldn't be directly in the Tower inventory.

**Comment by MrBones757** [comment]
Cheers for the feedback
I had suggested that these apps should be separate internally within my team, however floating the idea was still suggested to see if there were any other ideas / want for this integration.

For the purposes of application tracking and auditing though using the fact cache could be viable, though i havent thaught about how this would be implemented, id mainly gone with the API approach for the purposes of external integrations

The other approach to this that i had considered was to create a separate django app using the same elements as AWX (patternfly etc) but host it (in my case) as a separate kubernetes service & using ingress rules / nginx to route to a /cmdb endpoint or something along those lines
