### ISSUE TITLE
Separate vault credential from machine credential

### ISSUE THREAD

**Issue by pfremm** [ansible/awx#65]
### Summary

Separate vault credential from machine credential
### Environment

* AWX version: Any
* Ansible version:  Any

It would be nice to have the vault credential to be defined separately from the machine credential.  This would allow separate vault credentials to be created in Ansible Tower, and then projects or job templates would be able to specify which vault credential to use.

**Comment by pfremm** [comment]
I would be interested in contributing this feature if we can get agreement a PR would be accepted.

**Comment by wenottingham** [comment]
Should already be there (it's in AWX, and will be in a future Tower release)
