### ISSUE TITLE
AWX 6.1 deployment fails on k8s 1.18

### ISSUE THREAD

**Issue by AdrianDutu** [ansible/awx#6500]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
I need to deploy awx 6.1 on kubernetes 1.18.0. 
I had a working setup on kubernetes 1.13. After updating kubernetes I can't deploy awx (with the same settings that were working before). 

Is awx 6.1 supported on the latest versions of kubernetes? I get an error when the playbook has to apply the deployment.yml file.

` {"changed": true, "cmd": "echo '---\napiVersion: v1\nkind: ServiceAccount\nmetadata:\n  name: awx\n  namespace: awx-6-1-0\n\n---\nkind: Service\napiVersion: v1\nmetadata:\n  namespace: awx-6-1-0\n  name: rabbitmq\n  labels:\n    app: awx\n    type: LoadBalancer\nspec:\n  type: NodePort\n  ports:\n   - name: http\n     protocol: TCP\n     port: 15672\n     targetPort: 15672\n   - name: amqp\n     protocol: TCP\n     port: 5672\n     targetPort: 5672\n  selector:\n    app: awx\n\n---\napiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: rabbitmq-config\n  namespace: awx-6-1-0\ndata:\n  enabled_plugins: |\n      [rabbitmq_management,rabbitmq_peer_discovery_k8s].\n  rabbitmq_definitions.json: |\n      {\n
     \"users\":[{\"name\": \"awx\", \"password\": \"321qazxc\", \"tags\": \"\"}],\n        \"permissions\":[\n          {\"user\":\"awx\",\"vhost\":\"awx\",\"configure\":\".*\",\"write\":\".*\",\"read\":\".*\"}\n        ],\n        \"vhosts\":[{\"name\":\"awx\"}],\n        \"policies\":[\n            {\"vhost\":\"awx\",\"name\":\"ha-all\",\"pattern\":\".*\",\"definition\":{\"ha-mode\":\"all\",\"ha-sync-mode\":\"automatic\"}}\n        ]\n      }\n  rabbitmq.conf: |\n      ## Clustering\n      management.load_definitions = /etc/rabbitmq/rabbitmq_definitions.json\n      cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s\n      cluster_formation.k8s.host = kubernetes.default.svc\n      cluster_formation.k8s.address_type = ip\n      cluster_formation.node_cleanup.interval = 10\n      cluster_formation.node_cleanup.only_log_warning = false\n      cluster_partition_handling = autoheal\n      ## queue master locator\n      queue_master_locator=min-masters\n      ## enable guest user\n      loopback_users.guest = false\n\n---\nkind: Role\napiVersion: rbac.authorization.k8s.io/v1beta1\nmetadata:\n  name: endpoint-reader\n  namespace: awx-6-1-0\nrules:\n- apiGroups: [\"\"]\n  resources: [\"endpoints\"]\n  verbs: [\"get\"]\n---\nkind: RoleBinding\napiVersion: rbac.authorization.k8s.io/v1beta1\nmetadata:\n  name: endpoint-reader\n  namespace: awx-6-1-0\nsubjects:\n- kind: ServiceAccount\n  name: awx\nroleRef:\n  apiGroup: rbac.authorization.k8s.io\n  kind: Role\n  name: endpoint-reader\n\n\n---\napiVersion: apps/v1beta1\nkind: StatefulSet\nmetadata:\n  name: awx\n  namespace: awx-6-1-0\nspec:\n  serviceName: awx\n  replicas: 1\n  template:\n    metadata:\n      labels:\n        name: awx-web-deploy\n        service: django\n        app: awx\n    spec:\n      serviceAccountName: awx\n      terminationGracePeriodSeconds: 10\n      containers:\n        - name: awx-web\n
   image: \"ansible/awx_web:6.1.0\"\n          imagePullPolicy: Always\n          ports:\n            - containerPort: 8052\n          volumeMounts:\n            - name: awx-ca-trust-dir\n              mountPath: \"/etc/pki/ca-trust/source/anchors/\"\n              readOnly: true\n            - name: awx-project-data-dir\n              mountPath: \"/var/lib/awx/projects\"\n              readOnly: false\n            - name: awx-application-config\n              mountPath: \"/etc/tower/settings.py\"\n              subPath: settings.py\n              readOnly: true\n\n            - name: \"awx-application-credentials\"\n              mountPath: \"/etc/tower/conf.d/\"\n              readOnly: true\n\n
 - name: awx-secret-key\n              mountPath: \"/etc/tower/SECRET_KEY\"\n              subPath: SECRET_KEY\n              readOnly: true\n\n          resources:\n            requests:\n              memory: \"1Gi\"\n              cpu: \"500m\"\n        - name: awx-celery\n          securityContext:\n            privileged: true\n          image: \"ansible/awx_task:6.1.0\"\n          command:\n            - /usr/bin/launch_awx_task.sh\n          imagePullPolicy: Always\n
          volumeMounts:\n            - name: awx-ca-trust-dir\n              mountPath: \"/etc/pki/ca-trust/source/anchors/\"\n              readOnly: true\n            - name: shared\n              mountPath: \"/opt/awx/shared\"\n
    - name: awx-application-config\n              mountPath: \"/etc/tower/settings.py\"\n              subPath: settings.py\n              readOnly: true\n\n            - name: \"awx-application-credentials\"\n              mountPath: \"/etc/tower/conf.d/\"\n              readOnly: true\n\n            - name: awx-secret-key\n              mountPath: \"/etc/tower/SECRET_KEY\"\n              subPath: SECRET_KEY\n              readOnly: true\n          env:\n            - name: AWX_SKIP_MIGRATIONS\n              value: \"1\"\n          resources:\n            requests:\n              memory: \"2Gi\"\n              cpu: \"1500m\"\n        - name: awx-rabbit\n          image: \"ansible/awx_rabbitmq:3.7.4\"\n
     imagePullPolicy: Always\n          ports:\n            - name: http\n              protocol: TCP\n              containerPort: 15672\n            - name: amqp\n              protocol: TCP\n              containerPort: 5672\n
livenessProbe:\n            exec:\n              command: [\"rabbitmqctl\", \"status\"]\n            initialDelaySeconds: 30\n            timeoutSeconds: 10\n          readinessProbe:\n            exec:\n              command: [\"rabbitmqctl\", \"status\"]\n            initialDelaySeconds: 10\n            timeoutSeconds: 10\n          env:\n            - name: MY_POD_IP\n              valueFrom:\n                fieldRef:\n                  fieldPath: status.podIP\n
    - name: RABBITMQ_USE_LONGNAME\n              value: \"true\"\n            - name: RABBITMQ_NODENAME\n              value: \"rabbit@$(MY_POD_IP)\"\n            - name: RABBITMQ_ERLANG_COOKIE\n              valueFrom:\n                secretKeyRef:\n                  name: \"awx-secrets\"\n                  key: rabbitmq_erlang_cookie\n            - name: K8S_SERVICE_NAME\n              value: \"rabbitmq\"\n          volumeMounts:\n            - name: rabbitmq-config\n
           mountPath: /etc/rabbitmq\n          resources:\n            requests:\n              memory: \"2Gi\"\n              cpu: \"500m\"\n        - name: awx-memcached\n          image: \"memcached:latest\"\n          imagePullPolicy: Always\n          resources:\n            requests:\n              memory: \"1Gi\"\n              cpu: \"500m\"\n      volumes:\n        - name: awx-ca-trust-dir\n          hostPath:\n            path: \"/etc/pki/ca-trust/source/anchors\"\n            type: Directory\n        - name: shared\n          hostPath:\n            path: \"/opt/awx/shared\"\n            type: \"Directory\"\n        - name: awx-project-data-dir\n          hostPath:\n            path: \"/opt/awx/projects\"\n            type: Directory\n        - name: awx-application-config\n          configMap:\n            name: awx-config\n            items:\n              - key: awx_settings\n                path: settings.py\n\n        - name: \"awx-application-credentials\"\n          secret:\n            secretName: \"awx-secrets\"\n            items:\n              - key: credentials_py\n                path: '\"'\"'credentials.py'\"'\"'\n              - key: environment_sh\n
              path: '\"'\"'environment.sh'\"'\"'\n\n        - name: awx-secret-key\n          secret:\n            secretName: \"awx-secrets\"\n            items:\n              - key: secret_key\n                path: SECRET_KEY\n\n
  - name: rabbitmq-config\n          configMap:\n            name: rabbitmq-config\n            items:\n            - key: rabbitmq.conf\n              path: rabbitmq.conf\n            - key: enabled_plugins\n              path: enabled_plugins\n            - key: rabbitmq_definitions.json\n              path: rabbitmq_definitions.json\n---\napiVersion: v1\nkind: Service\nmetadata:\n  name: awx-web-svc\n  namespace: awx-6-1-0\n  labels:\n    name: awx-web-svc\nspec:\n  type: \"NodePort\"\n  ports:\n    - name: http\n      port: 80\n      targetPort: 8052\n  selector:\n    name: awx-web-deploy\n---\napiVersion: v1\nkind: Service\nmetadata:\n  name: awx-rmq-mgmt\n  namespace: awx-6-1-0\n  labels:\n    name: awx-rmq-mgmt\nspec:\n  type: ClusterIP\n  ports:\n    - name: rmqmgmt\n      port: 15672\n      targetPort: 15672\n  selector:\n    name: awx-web-deploy\n---\napiVersion: extensions/v1beta1\nkind: Ingress\nmetadata:\n  name: awx-web-svc\n  namespace: awx-6-1-0\nspec:\n  backend:\n    serviceName: awx-web-svc\n    servicePort: 80\n' | kubectl apply -f -", "delta": "0:00:00.407297", "end": "2020-03-31 12:10:49.993473", "item": "---\napiVersion: v1\nkind: ServiceAccount\nmetadata:\n  name: awx\n  namespace: awx-6-1-0\n\n---\nkind: Service\napiVersion: v1\nmetadata:\n  namespace: awx-6-1-0\n  name: rabbitmq\n  labels:\n    app: awx\n    type: LoadBalancer\nspec:\n  type: NodePort\n  ports:\n   - name: http\n     protocol: TCP\n     port: 15672\n     targetPort: 15672\n   - name: amqp\n     protocol: TCP\n     port: 5672\n     targetPort: 5672\n  selector:\n    app: awx\n\n---\napiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: rabbitmq-config\n  namespace: awx-6-1-0\ndata:\n  enabled_plugins: |\n      [rabbitmq_management,rabbitmq_peer_discovery_k8s].\n  rabbitmq_definitions.json: |\n      {\n        \"users\":[{\"name\": \"awx\", \"password\": \"321qazxc\", \"tags\": \"\"}],\n
    \"permissions\":[\n          {\"user\":\"awx\",\"vhost\":\"awx\",\"configure\":\".*\",\"write\":\".*\",\"read\":\".*\"}\n        ],\n        \"vhosts\":[{\"name\":\"awx\"}],\n        \"policies\":[\n            {\"vhost\":\"awx\",\"name\":\"ha-all\",\"pattern\":\".*\",\"definition\":{\"ha-mode\":\"all\",\"ha-sync-mode\":\"automatic\"}}\n        ]\n      }\n  rabbitmq.conf: |\n      ## Clustering\n      management.load_definitions = /etc/rabbitmq/rabbitmq_definitions.json\n      cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s\n      cluster_formation.k8s.host = kubernetes.default.svc\n      cluster_formation.k8s.address_type = ip\n      cluster_formation.node_cleanup.interval = 10\n
     cluster_formation.node_cleanup.only_log_warning = false\n      cluster_partition_handling = autoheal\n      ## queue master locator\n      queue_master_locator=min-masters\n      ## enable guest user\n      loopback_users.guest = false\n\n---\nkind: Role\napiVersion: rbac.authorization.k8s.io/v1beta1\nmetadata:\n  name: endpoint-reader\n  namespace: awx-6-1-0\nrules:\n- apiGroups: [\"\"]\n  resources: [\"endpoints\"]\n  verbs: [\"get\"]\n---\nkind: RoleBinding\napiVersion: rbac.authorization.k8s.io/v1beta1\nmetadata:\n  name: endpoint-reader\n  namespace: awx-6-1-0\nsubjects:\n- kind: ServiceAccount\n  name: awx\nroleRef:\n  apiGroup: rbac.authorization.k8s.io\n  kind: Role\n  name: endpoint-reader\n\n\n---\napiVersion: apps/v1beta1\nkind: StatefulSet\nmetadata:\n  name: awx\n  namespace: awx-6-1-0\nspec:\n  serviceName: awx\n  replicas: 1\n  template:\n    metadata:\n      labels:\n        name: awx-web-deploy\n        service: django\n
        app: awx\n    spec:\n      serviceAccountName: awx\n      terminationGracePeriodSeconds: 10\n      containers:\n        - name: awx-web\n          image: \"ansible/awx_web:6.1.0\"\n          imagePullPolicy: Always\n          ports:\n            - containerPort: 8052\n          volumeMounts:\n            - name: awx-ca-trust-dir\n              mountPath: \"/etc/pki/ca-trust/source/anchors/\"\n              readOnly: true\n            - name: awx-project-data-dir\n
            mountPath: \"/var/lib/awx/projects\"\n              readOnly: false\n            - name: awx-application-config\n              mountPath: \"/etc/tower/settings.py\"\n              subPath: settings.py\n              readOnly: true\n\n            - name: \"awx-application-credentials\"\n              mountPath: \"/etc/tower/conf.d/\"\n              readOnly: true\n\n            - name: awx-secret-key\n              mountPath: \"/etc/tower/SECRET_KEY\"\n
    subPath: SECRET_KEY\n              readOnly: true\n\n          resources:\n            requests:\n              memory: \"1Gi\"\n              cpu: \"500m\"\n        - name: awx-celery\n          securityContext:\n            privileged: true\n          image: \"ansible/awx_task:6.1.0\"\n          command:\n            - /usr/bin/launch_awx_task.sh\n          imagePullPolicy: Always\n          volumeMounts:\n            - name: awx-ca-trust-dir\n              mountPath: \"/etc/pki/ca-trust/source/anchors/\"\n              readOnly: true\n            - name: shared\n              mountPath: \"/opt/awx/shared\"\n            - name: awx-application-config\n              mountPath: \"/etc/tower/settings.py\"\n              subPath: settings.py\n              readOnly: true\n\n            - name: \"awx-application-credentials\"\n              mountPath: \"/etc/tower/conf.d/\"\n              readOnly: true\n\n            - name: awx-secret-key\n              mountPath: \"/etc/tower/SECRET_KEY\"\n              subPath: SECRET_KEY\n              readOnly: true\n          env:\n            - name: AWX_SKIP_MIGRATIONS\n              value: \"1\"\n          resources:\n            requests:\n              memory: \"2Gi\"\n              cpu: \"1500m\"\n        - name: awx-rabbit\n          image: \"ansible/awx_rabbitmq:3.7.4\"\n          imagePullPolicy: Always\n          ports:\n            - name: http\n
 protocol: TCP\n              containerPort: 15672\n            - name: amqp\n              protocol: TCP\n              containerPort: 5672\n          livenessProbe:\n            exec:\n              command: [\"rabbitmqctl\", \"status\"]\n            initialDelaySeconds: 30\n            timeoutSeconds: 10\n          readinessProbe:\n            exec:\n              command: [\"rabbitmqctl\", \"status\"]\n            initialDelaySeconds: 10\n            timeoutSeconds: 10\n          env:\n            - name: MY_POD_IP\n              valueFrom:\n                fieldRef:\n                  fieldPath: status.podIP\n            - name: RABBITMQ_USE_LONGNAME\n              value: \"true\"\n            - name: RABBITMQ_NODENAME\n              value: \"rabbit@$(MY_POD_IP)\"\n            - name: RABBITMQ_ERLANG_COOKIE\n              valueFrom:\n                secretKeyRef:\n                  name: \"awx-secrets\"\n                  key: rabbitmq_erlang_cookie\n            - name: K8S_SERVICE_NAME\n              value: \"rabbitmq\"\n          volumeMounts:\n            - name: rabbitmq-config\n              mountPath: /etc/rabbitmq\n          resources:\n            requests:\n
         memory: \"2Gi\"\n              cpu: \"500m\"\n        - name: awx-memcached\n          image: \"memcached:latest\"\n          imagePullPolicy: Always\n          resources:\n            requests:\n              memory: \"1Gi\"\n
           cpu: \"500m\"\n      volumes:\n        - name: awx-ca-trust-dir\n          hostPath:\n            path: \"/etc/pki/ca-trust/source/anchors\"\n            type: Directory\n        - name: shared\n          hostPath:\n
path: \"/opt/awx/shared\"\n            type: \"Directory\"\n        - name: awx-project-data-dir\n          hostPath:\n            path: \"/opt/awx/projects\"\n            type: Directory\n        - name: awx-application-config\n
configMap:\n            name: awx-config\n            items:\n              - key: awx_settings\n                path: settings.py\n\n        - name: \"awx-application-credentials\"\n          secret:\n            secretName: \"awx-secrets\"\n            items:\n              - key: credentials_py\n                path: 'credentials.py'\n              - key: environment_sh\n                path: 'environment.sh'\n\n        - name: awx-secret-key\n          secret:\n
    secretName: \"awx-secrets\"\n            items:\n              - key: secret_key\n                path: SECRET_KEY\n\n        - name: rabbitmq-config\n          configMap:\n            name: rabbitmq-config\n            items:\n
     - key: rabbitmq.conf\n              path: rabbitmq.conf\n            - key: enabled_plugins\n              path: enabled_plugins\n            - key: rabbitmq_definitions.json\n              path: rabbitmq_definitions.json\n---\napiVersion: v1\nkind: Service\nmetadata:\n  name: awx-web-svc\n  namespace: awx-6-1-0\n  labels:\n    name: awx-web-svc\nspec:\n  type: \"NodePort\"\n  ports:\n    - name: http\n      port: 80\n      targetPort: 8052\n  selector:\n    name: awx-web-deploy\n---\napiVersion: v1\nkind: Service\nmetadata:\n  name: awx-rmq-mgmt\n  namespace: awx-6-1-0\n  labels:\n    name: awx-rmq-mgmt\nspec:\n  type: ClusterIP\n  ports:\n    - name: rmqmgmt\n      port: 15672\n      targetPort: 15672\n  selector:\n    name: awx-web-deploy\n---\napiVersion: extensions/v1beta1\nkind: Ingress\nmetadata:\n  name: awx-web-svc\n  namespace: awx-6-1-0\nspec:\n  backend:\n    serviceName: awx-web-svc\n    servicePort: 80\n", "msg": "non-zero return code", "rc": 1, "start": "2020-03-31 12:10:49.586176", "stderr": "error: unable to recognize \"STDIN\": no matches for kind \"StatefulSet\" in version \"apps/v1beta1\"", "stderr_lines": ["error: unable to recognize \"STDIN\": no matches for kind \"StatefulSet\" in version \"apps/v1beta1\""], "stdout": "", "stdout_lines": []}`

##### ENVIRONMENT
* AWX version: 6.1.0
* AWX install method: kubernetes
* Ansible version:  2.7
* Operating System: CentOS 7

##### STEPS TO REPRODUCE

Have a kubernetes 1.18 cluster. 
Run the awx 6.1 install playbook.

##### EXPECTED RESULTS

Applying deployment successfully.

##### ACTUAL RESULTS

Applying deployment fails with the above error.

##### ADDITIONAL INFORMATION

I can't use any later version than 6.1 because the os image has upgraded the openssh client and it doesn't like dsa keys (which unfortunately we still use and are in progress of changing but will take time). I had another issue opened and didn't manage to make awx work with dsa keys on openssh 7.

**Comment by ryanpetrello** [comment]
Hey @AdrianDutu,

> Is awx 6.1 supported on the latest versions of kubernetes?

We don't generally address compatibility issues like this on older versions of AWX.  Are you able to reproduce the issue on more recent versions of AWX?

**Comment by AdrianDutu** [comment]
As I said, I can't use a more recent version since 6.1 is the last version that uses openssh 6 and I can't make awx on openssh 7 use dsa keys. I had an issue opened for this but we didn't get to the bottom of  it.

**Comment by ryanpetrello** [comment]
@AdrianDutu it's _likely_ that AWX 7.x diverged on something in k8s installer support that would explain the breakage you're encountering on k8s upgrade, but I don't know what that change might be (given that the change history we're talking about here is 9+ months old at the point).

AWX is _very much_ a rapidly moving open source project, and we don't offer any sort of long term support for stable versions/branches except in situations that involve _very, very high_ security issues; in this case, AWX 6.x is pretty much frozen in time (if we found the culprit, we would be very unlikely to cut a new 6.1.x to address an installer compatability issue like this).
