### ISSUE TITLE
All groups filter on groups list doesn't work for root groups (and display is bad)

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#6503]
![Screen Shot 2020-03-31 at 11 01 02 AM](https://user-images.githubusercontent.com/1342624/78041652-f5f71a00-733e-11ea-8138-c3f9011c006b.png)

the current filter for root groups is parents__isnull = true.  the all groups filter (parents__Isnull = false) is actually showing all _but_ root groups.  we'll have to figure out another way to do that filter (possibly by just removing parents__isnull altogether.

there is also a display issue...the actual value for the tag (true/false), rather than label text explaining what's going on for the tag is confusing.

**Comment by jlmitch5** [comment]
I'm removing my assignment on this as it was stalled.  we'll need to figure out something different here

**Comment by mabashian** [comment]
See https://github.com/ansible/awx/issues/6503 for a suggestion on how to proceed.

**Comment by mabashian** [comment]
Actually - I think this issue should be closed in favor of https://github.com/ansible/awx/issues/8593
