### ISSUE TITLE
Prompted fields on schedules are broken

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#6510]
EDIT: see https://github.com/ansible/awx/issues/6510#issuecomment-692930141

##### ISSUE TYPE
- Bug/Feature-ish

##### SUMMARY
Follow-up to work in https://github.com/ansible/awx/issues/5859

See this screenshot:
![Screenshot from 2020-03-31 15-09-59](https://user-images.githubusercontent.com/19942822/78066651-5a2bd500-7363-11ea-909d-cacfb6ab0fc2.png)

"Prompted Fields" doesn't look like a header for a group of items below it. It just looks like a regular item with no value. The work in this involves creating a proper subsection for prompted fields (if any exist) for the schedule.

**Comment by dsesami** [comment]
Prompted fields on a JT schedule are actually entirely broken now and do not appear at all.

![Screenshot from 2020-09-15 15-29-19](https://user-images.githubusercontent.com/19942822/93255694-42f17000-f768-11ea-89b3-0b7037105de6.png)

**Comment by unlikelyzero** [comment]
Note: we should convert the stubs to tests on at least prompts on schedule details

**Comment by mabashian** [comment]
Linking this with #7692

**Comment by unlikelyzero** [comment]
coverage added
