### ISSUE TITLE
Can't create job templates as project admin in AWX 10.0.0

### ISSUE THREAD

**Issue by CWollinger** [ansible/awx#6512]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Can't create job templates as project admin in AWX 10.0.0

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.6
* Operating System: Ubuntu 18.04 LTS
* Web Browser: Firefox 70

##### STEPS TO REPRODUCE

1. Start AWX 10.0.0
2. Add a new user e.g. `test`
3. Go to the `Demo Project`
4. Add `test` as project admin to the `Demo Project`
5. Login as user `test` and navigate to `Templates`
6. Unable to create new templates. There is no permission.

##### EXPECTED RESULTS

Able to create Templates as project admin. Like in AWX 9.3.0 and before

##### ACTUAL RESULTS

Button for creation doesn’t appear. 
Error from API/URL:
`You do not have permission to add a job template, or there are no projects available.`

##### ADDITIONAL INFORMATION
Only able to edit job templates as project admin. Copy function is not available, too.

**Comment by kdelee** [comment]
Works for me, can close after PR merges

**Comment by anksvault** [comment]
Is there any fix for this? I am also facing the same issue in AWX 10.0.0

**Comment by CWollinger** [comment]
Fixed with 11.0.0
