### ISSUE TITLE
Logout button on the API for ui-next does not work

### ISSUE THREAD

**Issue by appuk** [ansible/awx#6520]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Click on the logout button on the API for ui-next makes a get request instead of a post request, due to which an error is thrown

##### STEPS TO REPRODUCE
1. https://localhost:3000/api
2. click on the logout button
<img width="352" alt="Screen Shot 2020-04-01 at 10 28 17 AM" src="https://user-images.githubusercontent.com/11617351/78149937-98c59c00-7404-11ea-9a9d-f954d1e9e24f.png">

##### EXPECTED RESULTS
The logout should be successfull

##### ACTUAL RESULTS
An error is thrown:
<img width="533" alt="Screen Shot 2020-04-01 at 10 28 34 AM" src="https://user-images.githubusercontent.com/11617351/78149948-9c592300-7404-11ea-8be8-cb87c67542cf.png">

**Comment by dsesami** [comment]
both localhost:3001/api/ and the logout button in the main GUI use GETs, as far as i can tell. logout does work, but there is an incredibly long load time for anything under the /api/ url. @jakemcdermott can you follow up with me on this one?

**Comment by dsesami** [comment]
load times on /api/ are due to something involving websocket proxying that @jakemcdermott is working on and is wholly unrelated. the button works.

**Comment by jakemcdermott** [comment]
reopening for test as https://github.com/ansible/awx/issues/6520#issuecomment-641350592 should be addressed by https://github.com/ansible/awx/pull/7469

**Comment by jakemcdermott** [comment]
reopening for test as #6520 (comment) should be addressed by #7469

**Comment by dsesami** [comment]
both slowdown and logout button are resolved :+1:
