### ISSUE TITLE
"source" button in smart inventory has disappeared

### ISSUE THREAD

**Issue by jwlogemann** [ansible/awx#6521]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
According to the documentation here: https://docs.ansible.com/ansible-tower/latest/html/userguide/inventories.html#amazon-web-services-ec2  you can add EC2 hosts via the "source" button in the smart inventory page.

However in AWX 9.1 that  "source" button in smart inventory has disappeared.

##### ENVIRONMENT
* AWX version: 9.1.0
* AWX install method: docker on linux
* Ansible version:  2.7
* Operating System: Centos 7.7
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Go to the smart inventory page

##### EXPECTED RESULTS

See a "source" button

##### ACTUAL RESULTS

Don't see a "source" button

**Comment by jakemcdermott** [comment]
The section of documentation you linked is for regular inventories, not smart inventories. To my knowledge, the `sources` tab has only ever been something you can access on a regular inventory.

Have you actually observed a `sources` tab on a smart inventory in a prior version?

**Comment by jwlogemann** [comment]
I was under the impression that smart inventories were for dynamic inventories and regular inventories were for lists of hosts, but apparently not.
