### ISSUE TITLE
AWX is demanding a license

### ISSUE THREAD

**Issue by arjunmenonx1** [ansible/awx#653]
ISSUE TYPE
- Bug Report
I tried installing AWX but the webpage shows Ansible Tower and not AWX. 

COMPONENT NAME
- UI
The AWX installation shows the Ansible Tower page and not AWX.

SUMMARY
I tried installing AWX using the following URL:
http://releases.ansible.com/awx/
The installation finishes as expected but the UI shows Tower and not AWX. The repo name is awx but all the packages inside are named 'ansible-tower'. Will there be a tar/rpm/deb package installation in the future?

ENVIRONMENT
* AWX version: 3.2.1
* Ansible version:  2.4.0.0
* Operating System: RHEL 7
* Web Browser: Chrome

SCREENSHOT

This is the webpage I used for the installation:

![tower_rpm](https://user-images.githubusercontent.com/24776005/32834731-a37e0a2e-ca29-11e7-8bad-4561737617c3.JPG)

**Comment by mkempster22** [comment]
This isn't how you install AWX, you have actually installed tower there, you need to follow the instructions in the INSTALL.md on this github project.

AWX unfortunately can't be installed via a simple RPM, it requires Docker or Openshift etc. to install


https://github.com/ansible/awx/blob/devel/INSTALL.md

**Comment by wenottingham** [comment]
Yes, you installed Tower, not AWX.

**Comment by wenottingham** [comment]
FYI, we've removed that link now (https://releases.ansible.com/awx) to avoid this confusion in the future.

**Comment by arjunmenonx1** [comment]
@wenottingham will there be a tar/rpm/deb package installation in the future?
