### ISSUE TITLE
[RFE] Workflow approval requests should have a job ID 

### ISSUE THREAD

**Issue by sugitk** [ansible/awx#6531]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

<img width="532" alt="スクリーンショット 2020-04-02 8 20 21" src="https://user-images.githubusercontent.com/2234991/78195865-aee26380-74bb-11ea-900e-6475a9c9b9fe.png">

The user cannot distinguish the waiting approval to proceed.  I suppose the job ID of the workflow is needed on each of these item.

**Comment by wenottingham** [comment]
@mabashian is this a quick fix we can do?

**Comment by dsesami** [comment]
One can distinguish identical WF runs now. The job IDs are included.

**Comment by softestplease** [comment]
Hello,

Any update on this topic? As I am also trying to get workflow_approval id when the workflow approval node is triggered in order to find the approval user name (approved_or_denied_by)

Cheers
