### ISSUE TITLE
AWX Job not started

### ISSUE THREAD

**Issue by mvineza** [ansible/awx#6532]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I have AWX running inside kubernetes. The components (web and task) connects to postgresql. All of them are containers running as kubernetes pods. For 2 months that setup is running fine without connection issues between the pods.

web (pod) --> postgres (pod)
task(pod) --> postgres (pod)

Due to lack of persistent storage in kubernetes cluster for postgres, I decided to move postgresql outside of kubernetes so it will be now a traditional virtual machine (1 master and 1 slave) instead of a container. Then I deployed pgpool inside kubernetes and remove the postgres pod. The current setup now is:

web (pod) --> pgpool (pod) --> postgres master/slave (virtual machine)
task (pod) --> pgpool (pod) --> postgres master/slave (virtual machine)

During that setup, I encounter connection issues such as some SQL statements are not sent properly to backend postgres. I notice that scenario when I encounter this error from the task pod:

```
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
awx.main.models.jobs.Job.DoesNotExist: Job matching query does not exist.
```

I looked closely and found out that seems some SQL queries are not being handled by pgpool. In effect, the queries never reached the backend postgres servers.

Here an image of the missed job in AWX that corresponds to the missed SQL query. From the image job 2214 is successful and ran, job 2216 is missed, job 2217 is successful, and so on.
 
![image](https://user-images.githubusercontent.com/28911125/78198898-b3f3e280-74bc-11ea-9a02-2e93eff82144.png)

If we open the blank job, it will look like this.

![image](https://user-images.githubusercontent.com/28911125/78199128-6330b980-74bd-11ea-9ec7-69b68e570d98.png)

And it will never run. To cleanup I just needed to delete them.

Checking the pgpool logs, I see the job ID 2217 is there.

```
➜ ~ ☿ kubectl logs dev-pgpool-77949cf588-mx25h | egrep '2020-03-31' | grep dev_execute_command | egrep 'INSERT INTO "main_activitystream"' | egrep '"id": 2217'
2020-03-31 05:04:28: pid 36: LOG: statement: INSERT INTO "main_activitystream" ("actor_id", "operation", "timestamp", "changes", "deleted_actor", "action_node", "object_relationship_type", "object1", "object2", "setting") VALUES (NULL, 'create', '2020-03-31T05:04:28.282003+00:00'::timestamptz, '{"name": "dev_execute_command", "description": "", "job_type": "run", "inventory": "awx-playbooks-dev-1", "project": "awx-playbooks-6", "playbook": "playbooks/execute_command.yaml", "scm_branch": "", "forks": 0, "limit": "", "verbosity": 0, "extra_vars": "{\"command\": \"date\"}", "job_tags": "", "force_handlers": false, "skip_tags": "", "start_at_task": "", "timeout": 0, "use_fact_cache": false, "job_template": "dev_execute_command-18", "allow_simultaneous": false, "instance_group": null, "diff_mode": false, "job_slice_number": 0, "job_slice_count": 1, "id": 2217, "credentials": [], "labels": []}', NULL, 'awx', '', 'job', '', '{}') RETURNING "main_activitystream"."id"
➜ ~ ☿

```
But job id 2216 is not there.

```
➜ ~ ☿ kubectl logs dev-pgpool-77949cf588-mx25h | egrep '2020-03-31' | grep dev_execute_command | egrep 'INSERT INTO "main_activitystream"' | egrep '"id": 2216'
➜ ~ ☿
```

Even though this is probably related to the pgpool setup I made, I want to ask for some insights specially on how awx sends SQL queries to destination postgres endpoint. I'm thinking if there are some settings that I can tweak on AWX side.

##### ENVIRONMENT
* AWX version: 7.0.0
* AWX install method: kubernetes
* Ansible version:  2.9.1
* Operating System: CentOS Linux release 7.7.1908 (Core)
* Web Browser: Chrome 80.0.3987.149
* Pgpool: 4.1.1

##### STEPS TO REPRODUCE

1. Setup master/slave postgres with streaming replication
2. Setup pgpool infront of postgres cluster
3. Point AWX web and tasks to pgpool IP

##### EXPECTED RESULTS

All jobs must run as expected on schedule.

##### ACTUAL RESULTS

Some jobs where not run.

##### ADDITIONAL INFORMATION

I also submitted issue on pgpool bug tracker which may help.
https://www.pgpool.net/mantisbt/view.php?id=601

**Comment by jakemcdermott** [comment]
Hello. Thanks for making this issue.

You don't need to use `pgpool` to use an external database. You're certainly welcome to do it but adding a layer of middleware to pool database connections is a significant change to the system and you're on your own for keeping it working.

The installer will work with _an_ external database automatically, you can see the specific `pg_*` inventory variables you need to set here: https://github.com/ansible/awx/blob/devel/installer/inventory#L81. There's also some details in the docs on using an external db: https://github.com/ansible/awx/blob/devel/INSTALL.md#postgresql

Best of luck. If you're looking for help troubleshooting your deployment, please stop by the ansible-awx irc channel on freenode or try reaching out to the community mailing list - for more details, see: https://www.ansible.com/products/awx-project/faq
