### ISSUE TITLE
Project updates aren't pulling the latest commit

### ISSUE THREAD

**Issue by grahamn-gr** [ansible/awx#6535]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

When performing a project update on an existing project it's not pulling the latest commit. 

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: openshift
* Ansible version:  NA
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Create a new project to point to a Git branch, take note of the revision and the commit in your branch from git. Push a new commit to the branch and take note of the commit and then perform a project update in AWX. You'll see the revision in AWX doesn't reflect the latest commit in the branch. This happens with all variants of SCM Update options (clean/delete/update rev)

If you create a new project with a different name only then does it pull the latest commit.

##### EXPECTED RESULTS

AWX updates the project to the latest commit

##### ACTUAL RESULTS

AWX doesn't update the project to the latest commit. It's stuck with the commit from the first time the project is setup.

**Comment by fosterseth** [comment]
Was not able to replicate this issue on awx 10.0.0 (non cluster install)

My revision always updates to the latest branch revision (via manually running project update, or by launching job with Update Revision on Launch checked)

**Comment by ryanpetrello** [comment]
I also can't replicate this.

**Comment by grahamn-gr** [comment]
I've double checked this again this morning. 

Looks like the problem is that the page isn't always refreshing, when I force a hard load of the page (CTRL+F5) the revision text updates.

**Comment by ryanpetrello** [comment]
@grahamn-gr,

It sounds to me (based on other issues you've filed, like https://github.com/ansible/awx/issues/6534) like you're encountering issues with websocket connectivity/reliability.  Do you see any errors/warnings in your browser development console (also, what web browser are you using)?

**Comment by chillchamp83** [comment]
I am also getting the same issue on AWX 15.0.01, unable to pull latest code from branch 

AWX version: 15.0.1
AWX install method: docker (install.sh) 
Ansible version: 2.9.15
Operating System: Centos 7
Web Browser: Chrome

**Comment by shaulbehr** [comment]
I'm experiencing this bug in Tower 3.8.5. 
Workaround: go to your project settings and change the branch, save, then revert and save again. This apparently makes some internals wake up and go get the latest version.

**Comment by kkashtan-intel** [comment]
Just got this and thought I'm losing my mind. @shaulbehr advice helped. This was so misleading. Source control revisions on AWX were not matching the latest commits on github. AWX 22.7.0. @stanislaw55 please reopen
