### ISSUE TITLE
ec2.ini can't be configured in AWX

### ISSUE THREAD

**Issue by jwlogemann** [ansible/awx#6537]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
To pull in a list of hosts from EC2 I need to setup the ec2.ini correctly to only get the information I need. However the AWX developers have cleverly hidden this file, and not documented how to edit it, so it's impossible to get a list of hosts from EC2

##### ENVIRONMENT
* AWX version: 9.1.0
* AWX install method: docker on linux
* Ansible version:  2.8
* Operating System: Centos 7.7
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Add EC2 as a source to an inventory. Update the inventory. Watch it fail

##### EXPECTED RESULTS

It connects to AWS and gets a list of hosts

##### ACTUAL RESULTS

It connects to AWS and dies with an error: Inventory script
(/var/lib/awx/venv/awx/lib64/python3.6/site-
packages/awx/plugins/inventory/ec2.py) had an execution error: ERROR: "Error
connecting to AWS backend. You are not authorized to perform this operation.",
while: getting EC2 instances

This is because you can't specify what it should pull in the ec2.ini file

**Comment by ryanpetrello** [comment]
Hey @jwlogemann,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
