### ISSUE TITLE
When creating a new resource, if a user selects a required form element and clicks Cancel, form validation is applied and form is not closed

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#6544]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When creating a new resource, if a user selects a required form element and clicks Cancel, form validation is applied and form is not closed or cancelled

##### ENVIRONMENT
* AWX version: 10.0

##### STEPS TO REPRODUCE
1. Create a new resource with a required form element (i.e. Inventory)
2. Select any required field (like name)
3. Click close
Note: Form validation applied without closing the form. Need to Cancel a second time

##### EXPECTED RESULTS
Form is closed when closed button clicked

##### ACTUAL RESULTS
Form validation applied.
Close button needs to be clicked twice

##### ADDITIONAL INFORMATION
<img width="1163" alt="Screen Shot 2020-04-02 at 12 43 06 PM" src="https://user-images.githubusercontent.com/12446869/78275366-853b3380-74df-11ea-90a4-ecf577b36164.png">

**Comment by mabashian** [comment]
I checked this out and it seems like this is now functioning correctly:

![cancel_inv](https://user-images.githubusercontent.com/9889020/99832087-0bb78a80-2b2e-11eb-91aa-4e4e6942fa90.gif)
