### ISSUE TITLE
Not all Associated Groups are displayed on Inventory / Hosts / Groups page

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#6549]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Not all Associated Groups are displayed on Inventory / Hosts / Groups page

##### ENVIRONMENT
* AWX version: 10.0

##### STEPS TO REPRODUCE
TBD

##### ADDITIONAL INFORMATION

<img width="1919" alt="Screen Shot 2020-04-02 at 12 51 33 PM" src="https://user-images.githubusercontent.com/12446869/78296047-0eac2f00-74fb-11ea-8df1-c7e32dc4ce8b.png">

**Comment by unlikelyzero** [comment]
retest in devel

**Comment by unlikelyzero** [comment]
Needs retesting and a functional test for the scenario above

**Comment by tiagodread** [comment]
Verified manually importing groups from inventory source and the groups are displayed on the group tab for a particular host: 

![image](https://user-images.githubusercontent.com/12464858/115079270-4eac3d00-9ed7-11eb-82d6-b5a380a373b4.png)

![image](https://user-images.githubusercontent.com/12464858/115074756-85cb2000-9ed0-11eb-9681-263b79248517.png)
