### ISSUE TITLE
Azure AD username mapings

### ISSUE THREAD

**Issue by local-master** [ansible/awx#6556]
##### ISSUE TYPE
 - Change username mappings for Azure AD configuration

##### SUMMARY
At the moment when configuring Azure AD SSO the username is mapped as NameSurname. It would be nice to be able to change the mapping to a different attribute in Azure AD

**Comment by Klaas-** [comment]
I am having the same issue, but I don't think it's mapped to NameSurname, it is mapped to whatever is in your "Name" field with removal of not allowed chars.
https://github.com/python-social-auth/social-core/blob/master/social_core/backends/azuread.py#L68

I think you can set it to be the e-mail through your settings.py . This seems sufficient for my usage, I have not tried it yet though.
https://github.com/ansible/awx/blob/devel/awx/settings/defaults.py#L491

**Comment by Klaas-** [comment]
Short follow up: SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL works as expected, username is now the mail address with azure ad.
