### ISSUE TITLE
WFJT Details Won't Load for users that do not have Add/Edit Permissions

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#6561]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
If a `template.summary_fields.user_capabilities.edit: false` or  `template.summary_fields.user_capabilities.delete: false`
the WFJT details page won't load.

##### ENVIRONMENT
* AWX version: 2.9
* AWX install method:  docker for mac
* Ansible version:  9.3
* Operating System: Mojave
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create a wfjt with webhooks enabled and a webhook key.  Allow another use to have execute permissions on the wfjt.  Sign in as that other user and click on the wfjt so that it should navigate you to the details page.
##### EXPECTED RESULTS

The details page loads
##### ACTUAL RESULTS

The details page fails to load because the user does not have the proper permissions to hit the api to get the webhook_key.  

##### ADDITIONAL INFORMATION

We need to set up some sort of conditional that if the user does not have proper permissions to get the webhook_key then that api call should not be made. Instead we should probably show `ENCRYPTED` in the field where the webhook_key would be.

@trahman73 can you comment on this?

**Comment by AlexSCorey** [comment]
It is probably not actually blocked but working on this would be easier after #6333 merges

**Comment by trahman73** [comment]
Yes, showing Encrypted is our regular pattern.

**Comment by dsesami** [comment]
This is not implemented yet. Moving to needs_devel.

Also shifting to high-priority as it blocks functionality with no workaround for users.

**Comment by mabashian** [comment]
@AlexSCorey it looks like this is now in progress?  I'm going go update the tags - if that's not correct then let me know.

**Comment by AlexSCorey** [comment]
@mabashian yes I that is right.

**Comment by unlikelyzero** [comment]
Covered by 5488
