### ISSUE TITLE
Workflow identifier field not respected on POST

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#6563]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Can not supply my own value for `identifier` on workflow job template node creation. I *can* PATCH to change the identifer.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE
* Create a workflow job template node w/ `identifier` value `this_does_not_work`

##### EXPECTED RESULTS

* The return created object to have an `identifier` value of `this_does_not_work`

##### ACTUAL RESULTS

* `identifier` has a generated UUID value

##### ADDITIONAL INFORMATION
![workflow_identifier](https://user-images.githubusercontent.com/722880/78377580-c6921880-759d-11ea-8799-e28220b1dc0a.gif)

**Comment by AlanCoding** [comment]
Proposed fix https://github.com/ansible/awx/pull/6572

**Comment by kdelee** [comment]
This will be able to be closed once #6592 goes in
