### ISSUE TITLE
Inventory Source List

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#6573]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Link to mockup: https://tower-mockups.testing.ansible.com/patternfly/inventories/inventories-sources/

Things that we need to support in this list:

Rows should display the name and type.  

In the old UI, we also show an icon next to the name that is gray (hasn't been sync'd yet), green pulsing (sync running), green (successful sync) and red (error/failed sync).  Clicking on this icon takes you to the last sync job.  In the mockups it looks like we follow a similar pattern but we should think through this UX in case another pattern would make more sense.

Each source is syncable/editable/deletable given the proper rbac permissions.

I don't see it in the mockups but there should also be a SYNC ALL button that will start sync's for all the sources in the inventory.

**Comment by AlexSCorey** [comment]
Sync functionality will be addressed in #6777

**Comment by dsesami** [comment]
@AlexSCorey can you give us a brief overview of the status on this? it has both `in_progress` and `needs_test`, so it's hard to figure out what's done or not. Is there any part that is still in development? If so, we can break that out and put it in `in_progress` etc. as needed, just to make sure there's no confusion. Thanks!

**Comment by dsesami** [comment]
since sync functionality is covered elsewhere, closing this one out officially and wrapping up testing there + the add form once that is ready.
