### ISSUE TITLE
Inventory Source Details

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#6574]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Link to mockup: https://tower-mockups.testing.ansible.com/patternfly/inventories/inventories-sources-detail/

This is going to be similar to projects in that there are lots of different types of sources all with different fields.

**Comment by mabashian** [comment]
We may want a sync button on this view(?)

**Comment by dsesami** [comment]
I recommend we add the sync button on this view. Also, since there will be a sync _status_ button available on the main list, that should be visible here as well.

**Comment by dsesami** [comment]
- When you view "Sourced From a Project" sources, it says "Sourced From a Project" in the list view, but the details view just says "scm" in lowercase. Can we have it be the same way the list does? It'll look a bit cleaner, IMO

- Enabled options are listed, and that's really useful. However, we should include the tooltip that's next to them on the add form, so information about what a specific option means is visible in the details view as well.

- Would you like to add the sync button as part of this work, or make it a separate issue? It's up to you.

**Comment by dsesami** [comment]
since #7085 merged this is now closed out, thanks!
