### ISSUE TITLE
Inventory Source Add Form

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#6575]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Link to mockup: https://tower-mockups.testing.ansible.com/patternfly/inventories/inventories-sources-add/

This is a form like projects or credentials where there's a `type` and a subform that's shown when the type is selected. 

Source Subforms
- Sourced from a Project
- Amazon EC2
- Google Compute Engine
- Microsoft Azure Resource Manager
- VMware vCenter
- Red Hat Satellite 6
- Red Hat CloudForms
- OpenStack
- Red Hat Virtualization
- Ansible Tower
- Custom Script

##### NOTE

**For this iteration of the form we're only going to support "Sourced from a Project"**
The other inventory source subforms will be covered in https://github.com/ansible/awx/issues/6899

**Comment by dsesami** [comment]
Moving this to needs_devel since the first requirement was finished, but the next step is supporting all types of inventory sources.

**Comment by dsesami** [comment]
after further reading, #6899 covers other types. that means this particular issue is closed.
