### ISSUE TITLE
Inventory Source Edit Form

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#6576]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Link to mockups: https://tower-mockups.testing.ansible.com/patternfly/inventories/inventories-sources-edit/

See #6575 

Going to mark this as blocked until #6575 is ready

Source Subforms
- Sourced from a Project
- Amazon EC2
- Google Compute Engine
- Microsoft Azure Resource Manager
- VMware vCenter
- Red Hat Satellite 6
- Red Hat CloudForms
- OpenStack
- Red Hat Virtualization
- Ansible Tower
- Custom Script

##### NOTE

**For this iteration of the form we're only going to support "Sourced from a Project"**
The other inventory source subforms will be covered in https://github.com/ansible/awx/issues/6899

**Comment by dsesami** [comment]
this was closed out with the merging of #7028
