### ISSUE TITLE
ui_next fails to login

### ISSUE THREAD

**Issue by ghost** [ansible/awx#6581]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After deploy ui_next I can reach the login windows, but when I try to login it says "There was a problem signing in. Please try again."
This error appears both in a deploy in Kubernetes and with a plain "npm start" on a local directory.
And in both situations there is no error in the log, as I attached below.

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: Kubernetes 1.18.0
* Ansible version:  2.9.5
* Operating System: macOS Catalina
* Web Browser: Mozilla Firefox 74.0

##### STEPS TO REPRODUCE
1. Start ui_next
2. Try to login

##### EXPECTED RESULTS
Login to the AWX dashboard.

##### ACTUAL RESULTS
Login prompt still say "There was a problem signing in. Please try again."

##### ADDITIONAL INFORMATION
Here the log from the container I deployed in Kubernetes (I just erased the URL of AWX).
```
> awx-react@1.0.0 start /ui_next
> webpack-dev-server --config ./webpack.config.js --mode development
[HPM] Proxy created: /api/login/  ->  http://XXX.YYY.svc.cluster.local:80
[HPM] Proxy created: /api  ->  http://XXX.YYY.svc.cluster.local:80
[HPM] Proxy created: /websocket  ->  http://XXX.YYY.cluster.local:80
ℹ ｢wds｣: Project is running at http://0.0.0.0:3001/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from ./dist
ℹ ｢wdm｣:    4193 modules
ℹ ｢wdm｣: Compiled successfully.
```
Also the same error appears even if I use the Ingress FQDN instead of the Service's.

Here a screenshot of the error:
![image](https://user-images.githubusercontent.com/13005894/78509280-492cfa80-778d-11ea-8cbd-4fbd7453e0f2.png)

**Comment by unlikelyzero** [comment]
Please check out awx 16.0.0 to see if this still persists
