### ISSUE TITLE
Cannot Assign Kubernetes Credential to Job Template

### ISSUE THREAD

**Issue by jstewart612** [ansible/awx#6583]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: openshift
* Ansible version:  2.9.5
* Operating System: N/A
* Web Browser: Any

##### STEPS TO REPRODUCE

Create a Kubernetes credential.  Create a Job Template.  Try to associate one with the other using the valid API post of POST https://$AWX_SERVER/api/v2/job_templates/$JOB_ID/credentials/

##### EXPECTED RESULTS

It to work by allowing my job template to have a kubeconfig I can then go and use.

##### ACTUAL RESULTS

{"error": "Cannot assign a Credential of kind `kubernetes`."}

**Comment by ryanpetrello** [comment]
@jstewart612 Kubernetes credentials are intended to be used with Container Group support, not as credentials assigned to a Job Template:

https://docs.ansible.com/ansible-tower/latest/html/administration/external_execution_envs.html#container-groups

**Comment by ryanpetrello** [comment]
It sounds like this is what you want: https://github.com/ansible/awx/issues/5735

**Comment by jstewart612** [comment]
It does yes... apologies for not catching this.  I ended up doing a workaround of injecting a kubeconfig into my awx task container which uses a limited read-only service principal to do the tasks I wanted to do and just using the context argument to the k8s modules in case anyone else sees this.
