### ISSUE TITLE
Inventory Source Schedules

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#6589]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Hook up the schedules related tab on inventory sources.  There's already a generic schedules component that can be used so this should be minimal work.  See projects/jt/wfjt's as an example.

**Comment by mabashian** [comment]
Marking as blocked until #6574 is done

**Comment by dsesami** [comment]
@AlexSCorey you can close this once you merge #7221
