### ISSUE TITLE
Incorrect opacity on SMART INVENTORY and RUN COMMAND buttons in Inventories. 

### ISSUE THREAD

**Issue by trahman73** [ansible/awx#659]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- UI

##### SUMMARY
The SMART INVENTORY and RUN COMMANDS buttons in the Inventory section are lighter than our standard opacity of .65.  This is causing the buttons to appear almost invisible on certain screens.  In the example below, COMPLETED JOBS is set to the correct opacity.
![image](https://user-images.githubusercontent.com/13351591/32853801-7207ba04-ca0a-11e7-830b-79657cfd8f07.png)

##### ENVIRONMENT
* AWX version: 1.0.1.207
* Ansible version:  2.4.1
* Operating System: MacOS
* Web Browser: Chrome/Firefox

##### STEPS TO REPRODUCE
Go to Inventories/All Hosts for the SMART INVENTORY button.
Go to Inventories/Groups and Inventories/Hosts for the RUN COMMANDS button.

##### EXPECTED RESULTS
Disabled buttons should match our standard opacity of .65.

##### ACTUAL RESULTS
Disabled buttons appear much lighter than our standard opacity of .65.

##### ADDITIONAL INFORMATION
This should be a css fix that will not affect API, Testing, or Docs.

**Comment by trahman73** [comment]
Moving this to Tower 3.2.2

**Comment by rahst12** [comment]
Did this get fixed?  I can't hardly see the button.  We're running Ansible Tower 3.2.1 (paid for license).

**Comment by wenottingham** [comment]
No, not fixed yet. Can leave this open to be tracked until it lands if you want.

**Comment by rahst12** [comment]
That'd be helpful!  Is there a way to track what's going into Tower 3.2.2 here?  Like a label or something?

**Comment by wenottingham** [comment]
Not really... contact your RH support rep for Tower-specific things.

**Comment by wenottingham** [comment]
Closing, this should be merged back in.

**Comment by rahst12** [comment]
Any idea if this made it into Ansible Tower?
