### ISSUE TITLE
Team Users Related Tab

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#6593]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Link to mockups: https://tower-mockups.testing.ansible.com/patternfly/teams/teams-users/

This is a bit different from the regular users list so we may want to look at a different component as opposed to sharing (?) not sure.  This list shows the current user which have roles on this particular team.  The list should display information about each user including name/username/role(s).  The add button should open an interface similar to the lookup interface where the user can select other users to add to the team.  Unlike the access list interface, we don't need to select a role in this modal.  See the old app for more details on the expected behavior:

<img width="1531" alt="Screen Shot 2020-04-06 at 11 21 19 AM" src="https://user-images.githubusercontent.com/9889020/78575015-ca6da700-77f8-11ea-8128-766ed90dbcfc.png">
<img width="1517" alt="Screen Shot 2020-04-06 at 11 21 25 AM" src="https://user-images.githubusercontent.com/9889020/78575023-ccd00100-77f8-11ea-8fce-5e4694e558fd.png">
<img width="1532" alt="Screen Shot 2020-04-06 at 11 21 31 AM" src="https://user-images.githubusercontent.com/9889020/78575037-cfcaf180-77f8-11ea-889c-77c355c6ee5d.png">

**Comment by nixocio** [comment]
This issue seems to be similar to https://github.com/ansible/awx/issues/7130

**Comment by mabashian** [comment]
This view already exists, the tab is just named `Access` instead of `Users`.

**Comment by unlikelyzero** [comment]
@akus062381 
1. check that we have coverage in the form of stubs for Teams Access.
2. Update stubs if coverage is missing
3. Execute stubs
4. Add a single working test

**Comment by akus062381** [comment]
Related issues: 
https://github.com/ansible/awx/issues/9467
https://github.com/ansible/awx/issues/9466

**Comment by akus062381** [comment]
Stubs have been added, locators checked, manually tested.
