### ISSUE TITLE
User Teams Related Tab

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#6594]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Here's a link to the mockups: https://tower-mockups.testing.ansible.com/patternfly/users/users-teams/

However, there are a few potential issues with the mockup.

The old app is just a read-only list of teams that shows the team name and the description:

<img width="1525" alt="Screen Shot 2020-04-06 at 11 26 17 AM" src="https://user-images.githubusercontent.com/9889020/78575631-9e065a80-77f9-11ea-915b-59959b74bbf0.png">

The current mockup shows an add button.  This may be _possible_ but isn't currently supported by the app.  If it's doable but not easy lets break that out into an enhancement.  If it's not possible just ignore.  The other thing in the mockups is the ability to delete (remove) teams from this list.  This is also not supported and probably not trivial to implement.  A user could have any number of roles on a team and undoing them dynamically from this list may be tricky.  If it's doable but not easy lets break that out into an enhancement.  If it's not possible just ignore.

We may be able to use the existing Teams list just without the add button.

**Comment by keithjgrant** [comment]
I didn’t implement Add, so I'm breaking that out into a separate enhancement: #7130 

I also agree deletion is a complicated feature here, too. Does it delete the team, or does it just disassociate the user from the team? If the latter, the UI of "Delete" and the trash can icon seem misleading/confusing and might need a little more thought.

**Comment by dsesami** [comment]
closing with the merging of #7129
