### ISSUE TITLE
Include python3-pymongo to 3.7.2 or later in base package dependencies

### ISSUE THREAD

**Issue by mrmibrown** [ansible/awx#6599]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
What problem/issue/behavior are you having trouble with?  What do you expect to see?
We are attempting to use Ansible Tower to manage Mongo, but Ansible requires the pymongo package to be at least 3.7.2 to add/update SCRAM-SHA-256 passwords.
I expect it to work. We were forced to install the pymongo 3.10 whl by hand and will have to put in a workaround in the playbook.

Where are you experiencing the behavior? What environment?
Future production

When does the behavior occur? Frequency? Repeatedly? At certain times?
During playbook deployment when using the mongodb_user module.

What information can you provide around timeframes and the business impact?
High priority project

"We installed the pymongo 3.10 whl by hand as a workaround for the time being.
Is it possible to get a version imported from Fedora (both supported 3.8/3.10 should work) as an appstream so there is no breakage for other customers?"

**Comment by wenottingham** [comment]
This should be done via a custom virtual environment (for now), and via execution environments (https://github.com/ansible/awx/issues/5157) in the future.
