### ISSUE TITLE
Remove workaround for unicode bug in python-memcached

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#660]
`python-memcached` had a unicode handling bug:

https://github.com/linsomniac/python-memcached/issues/79

So we fixed it ourselves in awx:

https://github.com/ansible/awx/commit/64a973ae0249f7995c6800d932499c4710eb0295

This bug is now fixed via https://github.com/linsomniac/python-memcached/pull/135
When a new release of `python-memcached` is available on PyPI, we should remove our fix and update to the latest `python-memcached`.  Namely, we should be able to just revert this block of code:

https://github.com/ansible/awx/commit/64a973ae0249f7995c6800d932499c4710eb0295#diff-5f33708f03c52c38947eae52c21a1407R91

...update the required version of `python-memcached` in https://github.com/ansible/awx/blob/devel/requirements/requirements.txt, and confirm that awx tests still pass.

**Comment by wenottingham** [comment]
There appears to be a 1.59, so removing the `blocked` flag.

**Comment by AlanCoding** [comment]
Tested this with python-memcached==1.59. The test is still failing in the exact same way. The type and code path is identical. We get a `str` for the value from `self.cache.get(key, **kwargs)` and that hasn't changed.

I see no indication that we can remove the patch. The best I could do would be to dig some more and file another bug in the upstream.

**Comment by ryanpetrello** [comment]
Yea, if it's still not fixed upstream, then I'd say keep our patch and close this issue; we'll just carry the actual fix.
