### ISSUE TITLE
Text input search on project credential lookup results in 400 error

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#6600]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Text-searching by name for a credential using the text input of a lookup field on the project form results in a 400 error due to broken url building.

##### STEPS TO REPRODUCE
- have the network tab of the developer tools open
- navigate to the projects form
- type some values into the text input field of the credential lookup and wait a moment

##### EXPECTED RESULTS
- 200-level http codes on the network tab

##### ACTUAL RESULTS
- 400 error

##### ADDITIONAL INFORMATION
![project_form_lookup_search](https://user-images.githubusercontent.com/9753817/78584451-399dc800-7806-11ea-9b1d-7bebfdf2c5c8.gif)

**Comment by jakemcdermott** [comment]
Hang tight, I'll get our l337est UI person on it.

**Comment by ryanpetrello** [comment]
PR: https://github.com/ansible/awx/pull/6588

**Comment by dsesami** [comment]
This appears to work just fine now; seeing 200s on devel.
