### ISSUE TITLE
JT launch results in error 

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#6606]
##### STEPS TO REPRODUCE
- try to launch demo jt

##### EXPECTED RESULTS
- it launches

##### ACTUAL RESULTS
- error

**Comment by mabashian** [comment]
Screenshot of the error:
<img width="1679" alt="Screen Shot 2020-04-08 at 10 15 34 AM" src="https://user-images.githubusercontent.com/9889020/78796408-421c0d00-7984-11ea-9e89-696159aa6e0d.png">

**Comment by mabashian** [comment]
Screenshot:

<img width="1680" alt="Screen Shot 2020-04-08 at 11 32 04 AM" src="https://user-images.githubusercontent.com/9889020/78803416-fb7ee080-798c-11ea-980f-aa1cab052fc9.png">

I'm able to reproduce this by attempting to launch one of the auto-generated JT's from the bulk_data script.  The error from the response indicates there's something going on with credentials:

`Removing Machine credential at launch time without replacement is not supported. Provided list lacked credential(s):  Credential 1 User 0-2,  Credential 6 team 2-7.`

It's possible this is only reproducible for a JT with default machine credentials.

**Comment by mabashian** [comment]
Yea this is most easily reproduced by creating a JT with a default credential and then attempting to launch said JT.

**Comment by dsesami** [comment]
I'm still seeing this currently @mabashian on devel. Same error.

**Comment by dsesami** [comment]
This was a wrong-branch problem on my part. It's all fixed.
