### ISSUE TITLE
Job Template Add Form breaks when selecting playbooks

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#6608]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Create a new Job Template using the Demo Project.
Try to select a playbook in the form.

##### EXPECTED RESULTS
The playbook is selected from the dropdown.

##### ACTUAL RESULTS
Nothing happens. The applicatino eventually staggers. Looking at logs, I see tons of GET calls to the Demo Project.

**Comment by jlmitch5** [comment]
this only happens when you have just 1 project...something is going on with the auto-population logic.  To overcome until this is fixed, just make sure oyu have more than 1 project so auto-population doesn't happen.

**Comment by dsesami** [comment]
This works correctly now, both with only one project and with multiple projects.
