### ISSUE TITLE
Add code collapse and code folding feature to output

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#6613]
##### SUMMARY
Add the expand-collapse toggles to output page for tasks, plays, lines, etc.

**Comment by unlikelyzero** [comment]
@jakemcdermott please sync with @akus062381 and @tiagodread when you begin this work. They do not have all of the context of this functionality.

QE should implement collapsing on different ansible versions and job types (inventory sync, project sync, jt)

**Comment by mabashian** [comment]
Blocked until #10053 merges

**Comment by akus062381** [comment]
resolved

**Comment by nixocio** [comment]
I will re-open this one, it needs to be re-evaluated.

**Comment by nixocio** [comment]
We decide to disable expand/collapse if the job still running.

**Comment by InnocentK** [comment]
Resolved
