### ISSUE TITLE
Dynamically update workflow results interface based on websocket messages

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#6616]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
When a user is on a workflow results page:

<img width="1638" alt="Screen Shot 2020-04-06 at 4 04 50 PM" src="https://user-images.githubusercontent.com/9889020/78600131-5d6e0780-7820-11ea-9120-29a047677924.png">

We want to update the status of jobs on nodes in real time by listening to messages that come across the websocket.

Hopefully by the time someone picks this up, we'll have a websocket implementation in place so the actually subscription process will be trivial.

The code that handles this in the old app is found here: https://github.com/ansible/awx/blob/devel/awx/ui/client/src/workflow-results/workflow-results.controller.js#L264

The gist of it is that we listen for job update messages.  When we get one, we check to see whether or not it belongs to the workflow we're viewing.  If it does, we go out and update the job reference on the node to reflect the new status and redraw the graph.

A user should be able to watch the entire workflow run in real time without any refreshes of the page.

**Comment by mabashian** [comment]
Note that as part of this work we'll want to update the status of the outer workflow job as well:

<img width="1638" alt="Screen Shot 2020-04-06 at 4 04 50 PM" src="https://user-images.githubusercontent.com/9889020/78600554-17657380-7821-11ea-9bc7-6d11c8977cca.png">

When the job actually finishes, we may be issuing a refresh of the job from the api to get all the updated fields that become available after the job finishes.

**Comment by jakemcdermott** [comment]
related, because this is job status subscription https://github.com/ansible/awx/issues/5885
