### ISSUE TITLE
Dynamically update jobs lists based on websocket messages

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#6618]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Socket behavior has changed in the old app - we should make it match up here.  Use https://github.com/ansible/awx/pull/5968#issuecomment-591565513 as a reference for expected behavior.

We'll need to subscribe to the jobs -> status_changed channel to get these updates.

When we get a message:

- If the job in question already exists in our list, we should use the contents of the websocket to update the row. When a job finishes and the sort order is -finished we should attempt to re-sort the list client side with the jobs without a finished timestamp at the top.
- If we get a new job and the sort order is -finished or -started, we should issue a request to see if the user has access to that job (/api/v2/unified_jobs?id__in=...). This request should be time-banded to every 5 seconds. Note that any search parameters applied are maintained in this request. If rows come back, we should add them to the top of the list and trim this list down to match the page size. If the sort order is something else we shouldn't try to add rows.

**Note that there are several other places where the jobs list component is used**

We have a number of completed jobs lists hanging around the app:

Job Template -> completed jobs
Host -> completed jobs
Inventory -> completed jobs
Smart Inventory -> completed jobs
Workflow Job Template -> completed jobs

We'll want to make sure that this logic works for all of these jobs lists.  The resource specific lists above **only show completed jobs** so we'll have to take that into account.

Blocked until #5957, #5958 land

**Comment by jakemcdermott** [comment]
This issue will replace https://github.com/ansible/awx/issues/5885, which I'm closing.

> Create a nice abstraction, hook, utility, etc. for managing websocket subscriptions for job statuses 
> in the new ui. This will be used to drive status icons and other behavior that depends on the status 
> of running jobs.

**Comment by dsesami** [comment]
This will be closed out after test stubs are created.
