### ISSUE TITLE
Dynamically update projects list based on websocket messages

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#6619]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Socket behavior has changed in the old app - we should make it match up here.  Use https://github.com/ansible/awx/pull/5968#issuecomment-591565513 as a reference for expected behavior.

We'll need to subscribe to the jobs -> status_changed channel to get these updates.

When we get a message:

- Rows should be updated using the contents of the websocket message. No requests should be made after initial load.

Blocked until #5957, #5958 land

**Comment by dsesami** [comment]
https://github.com/ansible/awx/pull/7540 was refactored, as part of https://github.com/ansible/awx/pull/7598. this can be closed with that merge.
