### ISSUE TITLE
Add IP/FQDN to Hosts Tables

### ISSUE THREAD

**Issue by rahst12** [ansible/awx#662]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
We often use IP and FQDN to identify servers.  It would reduce multiple steps/clicks if I could add a column(s) in the Hosts tables which show the IP (ansible_ssh_host variable) and FQDN.

Hosts table can be seen from Inventories.

##### ENVIRONMENT
* AWX version: 3.2.1
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.4.0.0
* Operating System: CentOS 7
* Web Browser: Chrome

**Comment by matburt** [comment]
possibly... though this is a very non-trivial thing. I'd argue that you should probably represent the "name" part of the host as whatever you use to actually identify it. Otherwise we'd end up having to parse the vars... which would really be no fun.

**Comment by matburt** [comment]
If anyone were to work on this I'd recommend clear the basic design through us first

**Comment by rahst12** [comment]
@matburt is your triage of this this the same as before?  I'm hoping a year later this might be an easier ask.  What do you think?

**Comment by matburt** [comment]
It's still probably probably non-trivial for what it's worth. What did you have in mind?

**Comment by Testicule** [comment]
AWX version 3.2.1?? In Nov 2017?

I've just updated from git a few weeks ago, and i got awx 3.0.1.
What the hell?

**Comment by ryanpetrello** [comment]
3.2.1 isn't an AWX version, it's a Red Hat Ansible Tower version (so this isn't really where this issue belongs).  This issue was filed right after Red Hat open sourced Tower as AWX (Fall 2017), hence the likely confusion over version numbers.

**Comment by Testicule** [comment]
Ah. Ta for clearing up the confusions Ryan.

**Comment by shanemcd** [comment]
We havent seen any other requests for this and I don't think we could do it without adding a lot of overhead. Thanks for the idea but I'm going to close this.
