### ISSUE TITLE
Dynamically update inventories list based on websocket messages

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#6620]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Socket behavior has changed in the old app - we should make it match up here.  Use https://github.com/ansible/awx/pull/5968#issuecomment-591565513 as a reference for expected behavior.

We'll need to subscribe to the jobs -> status_changed channel to get these updates.

When we get a message:

- For new jobs (status = pending) we should try to find the template it belongs to and add this new job to the front of the recent_jobs array (popping the last job off if length > 10). For all other status updates we should try to find the template+job and update the status/finished timestamp. No GET requests needed.

Blocked until #5957, #5958 land

**Comment by dsesami** [comment]
If I'm right, this is complete with the merge of https://github.com/ansible/awx/pull/7598. Please reopen if that isn't the case.
