### ISSUE TITLE
Unit and functional tests for ui_next occasionally fail with out of memory error in CI

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#6632]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I'm starting to see the occasional failure in zuul due to out-of-memory errors:

![Screenshot from 2020-04-07 11-17-36](https://user-images.githubusercontent.com/9753817/78686823-80042d00-78c1-11ea-8d6e-7734ced7e4b0.png)

We've seen this before and it is probably the job getting oom-killed from exceeding the resource request limit. Last time, we temporarily addressed the issue by increasing that limit. That may be the approach we take this time as well, but first we should investigate the memory usage of the test runs in general and see if there isn't memory leak,  bloat, or other problem that we need to address in the tests themselves.

**Comment by unlikelyzero** [comment]
@jakemcdermott still happening?

**Comment by mabashian** [comment]
It's been a looooooong time since this was filed.  If this pops back up we can reopen.
