### ISSUE TITLE
Inventory VMWARE Host Disabled

### ISSUE THREAD

**Issue by maitrefou** [ansible/awx#6633]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME
UI

##### SUMMARY
When I import VM with PowerOff state on VMWare. the host is marked disabled in my inventory.
How to activate non-powered machines by default
![image](https://user-images.githubusercontent.com/63309234/78697200-b90fc200-7900-11ea-8f7d-abd343636f00.png)

thanks in advance.

##### ENVIRONMENT
* AWX version:9.0.1.0
* AWX install method: ,docker on linux, docker 
* Ansible version:  2.8.5
* Operating System: Centos 7.8
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Go to VMware Inventory 
Sources
synchronization

**Comment by ryanpetrello** [comment]
@maitrefou Can you clarify what you're asking about here?  If you have a VM powered off, AWX will import it as disabled.

If you're having trouble or have questions about how inventory syncing works, you might have more luck on the mailing list or IRC room (this issue tracker is for tracking bugs and enhancements).
