### ISSUE TITLE
Job Template edit form playbook field initializes to unselected value

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#6638]
##### STEPS TO REPRODUCE
- create a job template
- open the edit form for the job template

##### EXPECTED RESULTS
- current playbook value of the job template is shown by the playbook field

##### ACTUAL RESULTS
- playbook field says "CHOOSE A PLAYBOOK"

**Comment by dsesami** [comment]
Editing a JT persists the playbook.
