### ISSUE TITLE
Make capacity percentage display consistent between individual instances and instance groups

### ISSUE THREAD

**Issue by ghost** [ansible/awx#664]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
The sum of the capacity percentage of a single-instance and the capacity percentage of the instance group containing the single instance are very different.

##### ENVIRONMENT
* AWX version: 1.0.0

##### STEPS TO REPRODUCE

Either noting the difference or adjusting the behavior will make the meaning more clear when estimating the remaining capacity available.

**Comment by matburt** [comment]
This is going to be revamped a bit in the future with the capacity changes tracked in another issue.

It's important to realize that capacity is not zero-sum if instances are assigned to multiple groups.
