### ISSUE TITLE
Deleting inventory source should be more verbose

### ISSUE THREAD

**Issue by egmar** [ansible/awx#6648]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When deleting an inventory source, the modal is not verbose enough. Deleting an inventory source is a destructive operation and deletes hosts/groups which were added using respective inventory source.

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: Kubernetes
* Ansible version:  2.9.3
* Web Browser: Google Chrome Version 82.0.4083.0 (Official Build) dev (64-bit)

##### STEPS TO REPRODUCE

1. Create an inventory
2. Add an inventory source.
3. Run sync process
4. Open inventory sources 
5. Click delete inventory source

##### EXPECTED RESULTS

Modal shown below should contain information on impact of deleting the inventory source. 
In least case it should references number of groups and hosts which will be deleted from inventory. 
Ideal implementation should have a more interactive modal, similar to group deletion modal. Specificaly user should be asked whether content imported from inventory source should be deleted or kept. 

##### ACTUAL RESULTS

An empty pop-up with action buttons is presented.

![Screenshot from 2020-04-08 08-16-50](https://user-images.githubusercontent.com/243891/78760090-edc35e00-7980-11ea-82ed-370801d38ee5.png)

##### ADDITIONAL INFORMATION

I've done a bit of debugging and code mangling to see where the problem could be and identified following:

##### Part 1. Why *Delete inventory source* modal is empty

Following code https://github.com/ansible/awx/blob/a26c0dfb8a361fcffbc1f607b5c197587780b57f/awx/ui/client/lib/models/InventorySource.js#L8 impacts directly the content of `Delete Inventory Source` modal. Specifically, it is used in following code https://github.com/ansible/awx/blob/a26c0dfb8a361fcffbc1f607b5c197587780b57f/awx/ui/client/src/inventories-hosts/inventories/related/sources/list/sources-list.controller.js#L161 and outcome in browser is following:
![image](https://user-images.githubusercontent.com/243891/78761822-675c4b80-7983-11ea-9834-4bfecd42d601.png)
Why would `InventorySource` have any relation at all with `WorkflowJobTemplateNode`? This basically explains why the modal doesn't contain any useful information as expected from following code: https://github.com/ansible/awx/blob/a26c0dfb8a361fcffbc1f607b5c197587780b57f/awx/ui/client/src/inventories-hosts/inventories/related/sources/list/sources-list.controller.js#L163-L185

##### Part 2. What happens when code which deletes hosts/groups associated with inventory source is commented

I've commented following lines: https://github.com/ansible/awx/blob/a26c0dfb8a361fcffbc1f607b5c197587780b57f/awx/ui/client/src/inventories-hosts/inventories/related/sources/list/sources-list.controller.js#L111-L130 and as well removed them from here https://github.com/ansible/awx/blob/a26c0dfb8a361fcffbc1f607b5c197587780b57f/awx/ui/client/src/inventories-hosts/inventories/related/sources/list/sources-list.controller.js#L131
With these modification, deleting an inventory source doesn't remove hosts/groups from inventory. As well, it doesn't cause any DB issue. Specifically, seems all the relations are cleaned correctly, while the hosts/groups are not impacted at all. This basically confirms that cleaning whole inventory when deleting an inventory source should be optional.

**Comment by jakemcdermott** [comment]
Depending on the practicality of relating this information in the api, we might not be able to show you a _count_ of hosts, groups, etc. that would be deleted.

That said, we can _certainly_ provide a better warning in the delete prompt to at least inform you that it is a destructive operation (beyond the source itself) and that any hosts and groups related to that source will also be deleted.

**Comment by egmar** [comment]
I do believe the code already has this intent, but it seems to pull data from wrong source, But agree, might be a quite expensive operation on big inventories.
On another note, what about making deletion of hosts/groups optional, in same way how hosts in groups can be promoted when group is deleted. I at least can see an use case for this when inventory source is used for an one time import.

**Comment by unlikelyzero** [comment]
note: we may want to come up with a new pattern in these instances as well https://github.com/ansible/awx/issues/8795 and https://github.com/ansible/awx/issues/7206

**Comment by mabashian** [comment]
This will be addressed by https://github.com/ansible/awx/pull/9345

**Comment by AlexSCorey** [comment]
@egmar
> On another note, what about making deletion of hosts/groups optional, in same way how hosts in groups can be promoted when group is deleted. I at least can see an use case for this when inventory source is used for an one time import.


 I can see a use case for that as well.  I am going to break this use case out into an enhancement to be worked on later, but will address a more verbose warning, with counts, in #9345

**Comment by mabashian** [comment]
Since we've opened #9607 to track the extra work I'm going to close this
