### ISSUE TITLE
excise withRouter (where we can) in favor of hooks

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#6649]
non-class based components where we can do this rn:
- UserEdit
- WorkflowJobTemplatesList
- ProjectsList
- JobTemplatesList
- InventorySourcesList
- JobTemplateForm (of which I think withRouter is not being used...can be straight up removed)
- Template (of which I think withRouter is not being used...can be straight up removed)
- TeamEdit (of which I think withRouter is not being used...can be straight up removed)
- OrganizationForm (of which I think withRouter is not being used...can be straight up removed)
- InventoryGroupForm (of which I think withRouter is not being used...can be straight up removed)

**Comment by dsesami** [comment]
Looking at all of the fields where this might affect things, I don't see any strange regressions; this appears to work well.
