### ISSUE TITLE
Launching job doesn't properly redirect to output

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#6655]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Came in with https://github.com/ansible/awx/pull/6639

Screenshot:

<img width="1679" alt="Screen Shot 2020-04-08 at 10 15 34 AM" src="https://user-images.githubusercontent.com/9889020/78798398-eef78980-7986-11ea-97f5-8cb481e8950d.png">

##### STEPS TO REPRODUCE
Launch a job template

**Comment by dsesami** [comment]
Resolved by https://github.com/ansible/awx/pull/6658

**Comment by appuk** [comment]
the job now launches successfully, hence closing the issue
<img width="1268" alt="Screen Shot 2020-04-14 at 12 19 17 PM" src="https://user-images.githubusercontent.com/11617351/79248816-53648e00-7e4a-11ea-9d4d-7d88650b2958.png">
