### ISSUE TITLE
AWX workflow template creation error

### ISSUE THREAD

**Issue by soloman747** [ansible/awx#666]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When creating a workflow template in a brand new vanilla install, I receive the error message:

ERROR! 
Filtering on password fields is not allowed.

##### ENVIRONMENT
* AWX version: 1.0.1
* AWX install method: docker on linux
* Ansible version:  2.4.1.0
* Operating System: Ubuntu
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Simply attempt to create a new workflow template

##### EXPECTED RESULTS

I expected to be presented with the workflow graph editor

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/29128098/32875933-0013854e-ca60-11e7-80e4-d0920db55803.png)

##### ADDITIONAL INFORMATION

**Comment by AlanCoding** [comment]
I have reproduced this. The request causing trouble is to the endpoint:

`/api/v2/job_templates/?page_size=5&order_by=name&inventory__isnull=false&credential__isnull=false`

If you remove `credential__isnull=false` it works. This is probably fallout from #595, but the error is surfacing in a strange way.

**Comment by AlanCoding** [comment]
Linked merge should solve the problem. Tested construction and saving of workflow.

Thanks for reporting!
