### ISSUE TITLE
AWX Task Installer breaking on KeyError: ('social_django', u'usersocialauth')

### ISSUE THREAD

**Issue by jrichard0725** [ansible/awx#667]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
unable to get awx installer to complete successfully

##### ENVIRONMENT
* AWX version: latest
* AWX install method: docker on linux
* Ansible version:  2.4.1.0
* Operating System: ubuntu 16.04

##### STEPS TO REPRODUCE
Setup the inventory to connect to an existing postgres for the managed ansible tower.
Walk through install guide as written

##### EXPECTED RESULTS
AWX spins up with previous data from the managed tower version intact.

##### ACTUAL RESULTS
It appears to not be able to get paste the social login on install.

Log output: https://pastebin.com/eNdSz2Ya

##### ADDITIONAL INFORMATION
I have followed the steps here: https://github.com/ansible/awx/issues/138 however it did not fix it.

* Removing the /tmp/pgdocker did nothing since my db is external (I believe this to be expected)
* I have tried uninstalling and reinstalling all libraries

If I run it as a brand new install with a local postgresql container, it appears to complete the install just fine. So it appears to be something in the existing db that may need to be cleaned up? I am unsure what and where though if there is anything.

Any help at this point would be so much appreciated.

**Comment by shanemcd** [comment]
So you are trying to point AWX at an existing _Tower_ database?

**Comment by ryanpetrello** [comment]
@jrichard0725,

If you're trying to install awx and point at a pre-existing Tower database,  it's not going to work for a handful of reasons.  The primary one is that awx represents the very latest bleeding-edge development, and your Tower install is a curated, stable release built by Red Hat (based off of awx code at a certain point in time earlier this year).  The error you're running into means that awx has new code in its database definitions that don't work with your older Tower database schema.

There is no supported upgrade path from Ansible Tower to awx; Tower's supported upgrade path is the next released version of Tower.

**Comment by jrichard0725** [comment]
Great - thanks for the heads up. I figured it was something simple 😉
