### ISSUE TITLE
RFE: Workflow "On Changed" branch

### ISSUE THREAD

**Issue by stobias123** [ansible/awx#6672]
##### ISSUE TYPE
Feature Request

##### SUMMARY
I'd like to be able to branch workflow actions only when the previous JT returned "changes".

I have a workflow that looks like this.
```

  ---------------              ---------------              -------------
 | "check mode" |   ----- >   | "approval step"|  ----- > | "remediation" |
  ---------------               ---------------             ---------------
```

I'm testing for drift with the the check mode, and I'd like to just stop and return success at node 2 if there are no changes.

I only want to continue in the workflow, get approval, and remediate if there are changes reported at node 1.

Currently if there are no changes at node1 - and I let the approval time out or deny, I get a failure in the template.

**Comment by wenottingham** [comment]
Jobs do not return 'changed'. -> https://github.com/ansible/awx/issues/5564
