### ISSUE TITLE
Isolated runs choke on rsync's .~tmp~ directories

### ISSUE THREAD

**Issue by domq** [ansible/awx#6675]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

In some circumstances, running an Ansible playbook as an isolated job causes a spurious failure (despite all individual Ansible tasks succeeding), because a stray `.~tmp~` directory pops up in an unexpected place.

##### ENVIRONMENT
* AWX version: AWX 10.0.0
* AWX install method: openshift
* Ansible version:  2.9.5

##### STEPS TO REPRODUCE

- Set `AWX_RESOURCE_PROFILING_ENABLED = True`
- Keep running isolated jobs until the problem shows up

##### EXPECTED RESULTS

All such jobs should succeed or fail depending solely on the underlying Ansible tasks' outcomes

##### ACTUAL RESULTS

Here is an example stack trace (also found in #6280):

```
Traceback (most recent call last): 
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 1468, in run
    ident=str(self.instance.pk)) 
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/isolated/manager.py", line 422, in run   status, rc = self.check() 
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/isolated/manager.py", line 241, in check
     self.consume_events() 
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/isolated/manager.py", line 293, in consume_events
    open(os.path.join(events_path, event), 'r')
IsADirectoryError: [Errno 21] Is a directory: '/tmp/awx_754_hs8ylxru/artifacts/754/job_events/.~tmp~' 
```

**Comment by domq** [comment]
Analysis:

- [`awx/main/isolated/manager.py`](https://github.com/ansible/awx/blob/devel/awx/main/isolated/manager.py) periodically runs the [`awx/playbooks/check_isolated.yml`](https://github.com/ansible/awx/blob/devel/awx/playbooks/check_isolated.yml) playbook, which relies on the [`synchronize`](https://docs.ansible.com/ansible/latest/modules/synchronize_module.html) module
- Said module [forces the `--delay-updates` rsync flag](https://github.com/ansible/ansible/blob/v2.9.5/lib/ansible/modules/files/synchronize.py#L202), which [causes](https://git.samba.org/rsync.git/?p=rsync.git;a=blob;f=rsync.yo;h=bcb33a79b328b7f0f64ab6511e6b571b67298287;hb=HEAD#l2478) rsync to create these `.~tmp~` directories

Suggested fix: add `.~tmp~` to the [`rsync_exclude`](https://github.com/ansible/awx/blob/devel/awx/main/isolated/manager.py#L148) list

**Comment by domq** [comment]
Upon inspecting this further, I believe I have the root cause wrong; now I am suspecting an `rsync` deadlock — According to the logs of my `awx-task` container on Kubernetes, the error pops up exactly 10 minutes after `rsync` starts

I shall close this issue and reopen a new one if I manage to get to the bottom of this.

**Comment by ryanpetrello** [comment]
Thanks @domq - the traceback you reported *does* look legitimate, though, so I merged the PR I opened.

**Comment by domq** [comment]
I wrote up the proper root cause analysis of my issue in #6692.
