### ISSUE TITLE
rsyslogd: properly respect LOG_AGGREGATOR_TCP_TIMEOUT for TCP logging

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#6683]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
In the new rsyslogd-based logging implementation, we should find a way to properly respect `settings.LOG_AGGREGATOR_TCP_TIMEOUT`.

As I recall, the *main* reason for this setting was to avoid having hung Python processes that never time out on requests.  That said, we should probably still do our best to respect it in our rsyslogd-based new implementation.

The `omhttp` module itself has a setting, `healthchecktimeout`, which we're properly passing in:

https://github.com/rsyslog/rsyslog/blob/df17aee50132c7e6898b475bffd9dffef3c54b3b/contrib/omhttp/omhttp.c#L188

This value is used by the `omhttp` module to pass a timeout value to `libcurl` when it performs connectivity checks:

https://github.com/rsyslog/rsyslog/blob/df17aee50132c7e6898b475bffd9dffef3c54b3b/contrib/omhttp/omhttp.c#L1624
https://curl.haxx.se/libcurl/c/CURLOPT_TIMEOUT_MS.html

The TCP and UDP methods, however, are implemented using `omfwd`, which doesn't appear to support a timeout parameter for TCP (so far as I can tell):

https://www.rsyslog.com/doc/v8-stable/configuration/modules/omfwd.html

We should figure out what to do about TCP.  Maybe *hide* the `LOG_AGGREGATOR_TCP_TIMEOUT` field in the UI if the logging type is *not* HTTP/s, or investigate TCP keepalive settings.

**Comment by ryanpetrello** [comment]
cc @rooftopcellist @elyezer

**Comment by ryanpetrello** [comment]
also @wenottingham @gamuniz for general awareness

**Comment by gamuniz** [comment]
@ryanpetrello @rooftopcellist currently that setting doesn't do anything in the new rsyslog world right? Would it be better to obfuscate it until it actually does do something?

**Comment by ryanpetrello** [comment]
Aaaaaactually, maybe we should configure TCP keepalive intervals:

https://www.rsyslog.com/doc/v8-stable/configuration/modules/omfwd.html#keepalive

**Comment by rooftopcellist** [comment]
@gamuniz It didn't, but I just added a commit so that it will. Though this will only apply in the `http/s` context, so we will want to hide it in the UI for tcp and udp.  And if we do something with tcp keepalive intervals, we will want to change the tool tip wording 

https://github.com/ansible/awx/pull/6108/commits/84385bc553cda0665179f5dd249caf3830a15b26

**Comment by wenottingham** [comment]
How is our logger persisting TCP connections? If it's not persisting, TCP keepalive won't do much.

**Comment by ryanpetrello** [comment]
/me reading

https://www.rsyslog.com/doc/v8-stable/configuration/modules/omfwd.html#rebindinterval

> After the configured number of messages has been transmitted, the current connection is terminated and a new one started. Note that this setting applies to both TCP and UDP traffic. For UDP, the new ``connection’’ uses a different source port (ports are cycled and not reused too frequently). This usually is perceived as a ``new connection’’ by load balancers, which in turn forward messages to another physical target system.

(default is zero, though I'm unclear from the docs if 0 == always reconnect, or 0 is effectively -1)

We may need to just watch some logs flow and see what the behavior is.

**Comment by ryanpetrello** [comment]
@wenottingham,

It looks to me like rsyslog itself maintains a persistent TCP connection:

![image](https://user-images.githubusercontent.com/214912/79270686-8f104f80-7e6c-11ea-9fbe-6cd2fe8e67cd.png)

If I sever the link artificially, it re-connects:

![image](https://user-images.githubusercontent.com/214912/79270898-f0382300-7e6c-11ea-9308-e40fa975322d.png)

**Comment by ryanpetrello** [comment]
Yea, I'm not having a lot of luck finding any parameters to `omfwd` that equate to the *intended* behavior of `LOG_AGGREGATOR_TCP_TIMEOUT`.  Given that, I think the best approach here is to just not factor this setting in for TCP-based logging, especially given that the entire point of it was to avoid our Python-based implementation from hanging forever.

**Comment by ryanpetrello** [comment]
If I point rsyslog at a port I'm not listening on, I see `SYN` packets every ~30 seconds or so (regardless of a variety of parameters I've tried passing to `omfwd`):

![image](https://user-images.githubusercontent.com/214912/79272195-19f24980-7e6f-11ea-9f57-4795ceb0da99.png)

...which seems like pretty reasonable behavior to me.

And if I leave things lying around like this for a few minutes and start back up netcat on that port, it immediately notices and starts sending messages again (including the messages that were queued/missed in the interim):

![image](https://user-images.githubusercontent.com/214912/79272311-44dc9d80-7e6f-11ea-9a58-ccb682f833f9.png)

I think the simplest change we could make to address this is to just make this setting affect HTTP/s loggers only.

@rooftopcellist @wenottingham @gamuniz what say you?

**Comment by ryanpetrello** [comment]
Actually, nevermind,  I figured out a config change that does it:

Five second interval (default):

![image](https://user-images.githubusercontent.com/214912/79273294-c41ea100-7e70-11ea-9099-2e37118d8931.png)

Custom 10 second interval:

![image](https://user-images.githubusercontent.com/214912/79273364-e0224280-7e70-11ea-8967-a105b1acca7c.png)

**Comment by elyezer** [comment]
To verify this I had `tcpdump -i lo -vv "dst port 9000"` running and checked that the interval was respected as I updated the setting on the UI. I've also checked that the rsyslog configuration file got updated as expected. Here is an example for the 30 and 60 seconds interval that I've set:

```console
$ cat /var/lib/awx/rsyslog/rsyslog.conf 
$WorkDirectory /var/lib/awx/rsyslog
$MaxMessageSize 700000
$IncludeConfig /var/lib/awx/rsyslog/conf.d/*.conf
main_queue(queue.spoolDirectory="/var/lib/awx" queue.maxdiskspace="1g" queue.type="Disk" queue.filename="awx-external-logger-backlog")
module(load="imuxsock" SysSock.Use="off")
input(type="imuxsock" Socket="/var/run/awx-rsyslog/rsyslog.sock" unlink="on")
template(name="awx" type="string" string="%rawmsg-after-pri%")
module(load="omhttp")
action(type="omhttp" server="localhost" serverport="9000" usehttps="on" skipverifyhost="off" action.resumeRetryCount="-1" template="awx" errorfile="/var/log/tower/rsyslog.err" action.resumeInterval="30")

$ cat /var/lib/awx/rsyslog/rsyslog.conf 
$WorkDirectory /var/lib/awx/rsyslog
$MaxMessageSize 700000
$IncludeConfig /var/lib/awx/rsyslog/conf.d/*.conf
main_queue(queue.spoolDirectory="/var/lib/awx" queue.maxdiskspace="1g" queue.type="Disk" queue.filename="awx-external-logger-backlog")
module(load="imuxsock" SysSock.Use="off")
input(type="imuxsock" Socket="/var/run/awx-rsyslog/rsyslog.sock" unlink="on")
template(name="awx" type="string" string="%rawmsg-after-pri%")
module(load="omhttp")
action(type="omhttp" server="localhost" serverport="9000" usehttps="on" skipverifyhost="off" action.resumeRetryCount="-1" template="awx" errorfile="/var/log/tower/rsyslog.err" action.resumeInterval="60")
```

One thing that I've observed is that when having the external logging configured and enabled, changing the timeout took sometime (couple minutes) to reflect the new timeout but once the new one was picked it worked fine. I could force the refresh by either testing the connection or disabling and enabling the external logging. Do we need to do something about this @ryanpetrello and @rooftopcellist?

**Comment by elyezer** [comment]
Talked to @ryanpetrello offline and it is fine to rsyslog to pick the new timeout after couple minutes after pressing the save button. If the on/off switch or the test button get any interaction then it will pick the new setting immediately.

**Comment by ryanpetrello** [comment]
Yea, I'm fine with the behavior; the goal here was to have a *approximation* of the old behavior so we could actually do something w/ the timeout setting.

**Comment by elyezer** [comment]
With all the above we are good to get this closed :tada:
