### ISSUE TITLE
Github not able to authenticate with AWX containers

### ISSUE THREAD

**Issue by EswanthNTS** [ansible/awx#6691]
##### ISSUE TYPE
 - Bug Report
![image](https://user-images.githubusercontent.com/43998903/79205636-1b535000-7e36-11ea-93cd-c55c93fe4656.png)

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

I have added Github credentials and added the projects.
But it's showing me the error.

**Comment by ryanpetrello** [comment]
Hey @EswanthNTS,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by EswanthNTS** [comment]
Hey @Ryan 

I am not able to authenticate between git hub and AWX its showing some errors.
Could anyone help to fix those issues?

Regards,
Eswanth.N
+919902842524

**Comment by EswanthNTS** [comment]
Adding to it after creating the project is showing the following error.

{
   "stderr_lines": [
       "fatal: repository 'https://github.com/newsuk/Enterprise-Infrastructure-AWS/tree/master/playbooks/CHagent/' not found"
   ],
   "cmd": "/usr/bin/git clone --origin origin https://github.com/newsuk/Enterprise-Infrastructure-AWS/tree/master/playbooks/CHagent /var/lib/awx/projects/_12__git_demo",
   "_ansible_no_log": false,
   "stdout": "Cloning into '/var/lib/awx/projects/_12__git_demo'...\n",
   "changed": false,
   "invocation": {
       "module_args": {
           "force": false,
           "track_submodules": false,
           "reference": null,
           "dest": "/var/lib/awx/projects/_12__git_demo",
           "accept_hostkey": false,
           "clone": true,
           "update": true,
           "ssh_opts": null,
           "repo": "https://github.com/newsuk/Enterprise-Infrastructure-AWS/tree/master/playbooks/CHagent",
           "bare": false,
           "archive": null,
           "recursive": true,
           "executable": null,
           "remote": "origin",
           "refspec": null,
           "separate_git_dir": null,
           "verify_commit": false,
           "umask": null,
           "depth": null,
           "version": "HEAD",
           "key_file": null
       }
   },
   "stderr": "fatal: repository 'https://github.com/newsuk/Enterprise-Infrastructure-AWS/tree/master/playbooks/CHagent/' not found\n",
   "rc": 128,
   "_ansible_delegated_vars": {
       "ansible_host": "localhost"
   },
   "stdout_lines": [
       "Cloning into '/var/lib/awx/projects/_12__git_demo'..."
   ],
   "msg": "fatal: repository 'https://github.com/newsuk/Enterprise-Infrastructure-AWS/tree/master/playbooks/CHagent/' not found"
}
