### ISSUE TITLE
Unable to copy file at remote location through awx

### ISSUE THREAD

**Issue by rishabhgupta1608** [ansible/awx#6693]
##### ISSUE TYPE
FIle is not copying to remote location

Any help will be much appreciated.

I tried ping module for the same host and it is working fine.

##### SUMMARY

I am trying to copy a file to a remote host. However, it seems awx is looking for it in temporary directory which it creates during the processing. I am pulling the playbook from Git.

awx 10
python 3.6
ansible 2.9
linux 7.6
============================================

- name: copy file
  hosts: all
  tasks:
  - name: Copy file
    copy:
      src: /tmp/testcopy.txt 
      dest: /home/rishabh
===========================================

Logs:

Identity added: /tmp/awx_192_clx4mb53/artifacts/192/ssh_key_data (/tmp/awx_192_clx4mb53/artifacts/192/ssh_key_data)
2
ansible-playbook 2.9.5
3
  config file = /etc/ansible/ansible.cfg
4
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
5
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
6
  executable location = /usr/bin/ansible-playbook
7
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
8
Using /etc/ansible/ansible.cfg as config file
9
SSH password: 
10
host_list declined parsing /tmp/awx_192_clx4mb53/tmpe0yrf906 as it did not pass its verify_file() method
11
Parsed /tmp/awx_192_clx4mb53/tmpe0yrf906 inventory source with script plugin
12
12
13
PLAYBOOK: remotecopy.yml *******************************************************
14
1 plays in remotecopy.yml
15
15
16
PLAY [copy file] ***************************************************************
05:59:38
17
18
TASK [Gathering Facts] *********************************************************
05:59:38
19
task path: /tmp/awx_192_clx4mb53/project/remotecopy.yml:1
20
20
<192.168.122.159> ESTABLISH SSH CONNECTION FOR USER: rishabh
21
21
<192.168.122.159> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="rishabh"' -o ConnectTimeout=10 -o ControlPath=/tmp/awx_192_clx4mb53/cp/75e0627c37 192.168.122.159 '/bin/sh -c '"'"'echo ~rishabh && sleep 0'"'"''
22
22
<192.168.122.159> (0, b'/home/rishabh\n', b'')
23
23
<192.168.122.159> ESTABLISH SSH CONNECTION FOR USER: rishabh
24
24
<192.168.122.159> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="rishabh"' -o ConnectTimeout=10 -o ControlPath=/tmp/awx_192_clx4mb53/cp/75e0627c37 192.168.122.159 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/rishabh/.ansible/tmp/ansible-tmp-1586858378.490975-151761252064871 `" && echo ansible-tmp-1586858378.490975-151761252064871="` echo /home/rishabh/.ansible/tmp/ansible-tmp-1586858378.490975-151761252064871 `" ) && sleep 0'"'"''
25
25
<192.168.122.159> (0, b'ansible-tmp-1586858378.490975-151761252064871=/home/rishabh/.ansible/tmp/ansible-tmp-1586858378.490975-151761252064871\n', b'')
26
26
<192.168.122.159> Attempting python interpreter discovery
27
27
<192.168.122.159> ESTABLISH SSH CONNECTION FOR USER: rishabh
28
28
<192.168.122.159> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="rishabh"' -o ConnectTimeout=10 -o ControlPath=/tmp/awx_192_clx4mb53/cp/75e0627c37 192.168.122.159 '/bin/sh -c '"'"'echo PLATFORM; uname; echo FOUND; command -v '"'"'"'"'"'"'"'"'/usr/bin/python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.5'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/libexec/platform-python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python3'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python'"'"'"'"'"'"'"'"'; echo ENDFOUND && sleep 0'"'"''
29
29
<192.168.122.159> (0, b'PLATFORM\nLinux\nFOUND\n/usr/bin/python\n/usr/bin/python2.7\n/usr/libexec/platform-python\n/usr/bin/python\nENDFOUND\n', b'')
30
30
<192.168.122.159> ESTABLISH SSH CONNECTION FOR USER: rishabh
31
31
<192.168.122.159> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="rishabh"' -o ConnectTimeout=10 -o ControlPath=/tmp/awx_192_clx4mb53/cp/75e0627c37 192.168.122.159 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
32
32
<192.168.122.159> (0, b'{"osrelease_content": "NAME=\\"Red Hat Enterprise Linux Workstation\\"\\nVERSION=\\"7.6 (Maipo)\\"\\nID=\\"rhel\\"\\nID_LIKE=\\"fedora\\"\\nVARIANT=\\"Workstation\\"\\nVARIANT_ID=\\"workstation\\"\\nVERSION_ID=\\"7.6\\"\\nPRETTY_NAME=\\"Red Hat Enterprise Linux Workstation 7.6 (Maipo)\\"\\nANSI_COLOR=\\"0;31\\"\\nCPE_NAME=\\"cpe:/o:redhat:enterprise_linux:7.6:GA:workstation\\"\\nHOME_URL=\\"https://www.redhat.com/\\"\\nBUG_REPORT_URL=\\"https://bugzilla.redhat.com/\\"\\n\\nREDHAT_BUGZILLA_PRODUCT=\\"Red Hat Enterprise Linux 7\\"\\nREDHAT_BUGZILLA_PRODUCT_VERSION=7.6\\nREDHAT_SUPPORT_PRODUCT=\\"Red Hat Enterprise Linux\\"\\nREDHAT_SUPPORT_PRODUCT_VERSION=\\"7.6\\"\\n", "platform_dist_result": ["redhat", "7.6", "Maipo"]}\n', b'')
33
33
Using module file /usr/lib/python3.6/site-packages/ansible/modules/system/setup.py
34
34
<192.168.122.159> PUT /var/lib/awx/.ansible/tmp/ansible-local-876ybeyb93p/tmpnz1inl50 TO /home/rishabh/.ansible/tmp/ansible-tmp-1586858378.490975-151761252064871/AnsiballZ_setup.py
35
35
<192.168.122.159> SSH: EXEC sshpass -d10 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="rishabh"' -o ConnectTimeout=10 -o ControlPath=/tmp/awx_192_clx4mb53/cp/75e0627c37 '[192.168.122.159]'
36
36
<192.168.122.159> (0, b'sftp> put /var/lib/awx/.ansible/tmp/ansible-local-876ybeyb93p/tmpnz1inl50 /home/rishabh/.ansible/tmp/ansible-tmp-1586858378.490975-151761252064871/AnsiballZ_setup.py\n', b'')
37
37
<192.168.122.159> ESTABLISH SSH CONNECTION FOR USER: rishabh
38
38
<192.168.122.159> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="rishabh"' -o ConnectTimeout=10 -o ControlPath=/tmp/awx_192_clx4mb53/cp/75e0627c37 192.168.122.159 '/bin/sh -c '"'"'chmod u+x /home/rishabh/.ansible/tmp/ansible-tmp-1586858378.490975-151761252064871/ /home/rishabh/.ansible/tmp/ansible-tmp-1586858378.490975-151761252064871/AnsiballZ_setup.py && sleep 0'"'"''
39
39
<192.168.122.159> (0, b'', b'')
40
40
<192.168.122.159> ESTABLISH SSH CONNECTION FOR USER: rishabh
41
41
<192.168.122.159> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="rishabh"' -o ConnectTimeout=10 -o ControlPath=/tmp/awx_192_clx4mb53/cp/75e0627c37 -tt 192.168.122.159 '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-dkcqawzubflwbdofqlpjnhtakghcxqlx ; /usr/bin/python /home/rishabh/.ansible/tmp/ansible-tmp-1586858378.490975-151761252064871/AnsiballZ_setup.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
42
42
Escalation succeeded
43
43
<192.168.122.159> (0, b'\r\n{"invocation": {"module_args": {"filter": "*", "gather_subset": ["all"], "fact_path": "/etc/ansible/facts.d", "gather_timeout": 10}}, "ansible_facts": {"ansible_fibre_channel_wwn": [], "module_setup": true, "ansible_distribution_version": "7.6", "ansible_distribution_file_variety": "RedHat", "ansible_env": {"LC_CTYPE": "en_US.UTF-8", "LOGNAME": "root", "USER": "root", "QTDIR": "/usr/lib64/qt-3.3", "PATH": "/sbin:/bin:/usr/sbin:/usr/bin", "LANG": "en_US.UTF-8", "TERM": "unknown", "SHELL": "/bin/bash", "LANGUAGE": "en_US.UTF-8", "SHLVL": "1", "SUDO_USER": "rishabh", "HOME": "/root", "USERNAME": "root", "SUDO_UID": "500", "LC_ALL": "en_US.UTF-8", "XDG_SESSION_ID": "11", "_": "/usr/bin/python", "SUDO_COMMAND": "/bin/sh -c echo BECOME-SUCCESS-dkcqawzubflwbdofqlpjnhtakghcxqlx ; /usr/bin/python /home/rishabh/.ansible/tmp/ansible-tmp-1586858378.490975-151761252064871/AnsiballZ_setup.py", "SUDO_GID": "500", "PWD": "/home/rishabh", "MAIL": "/var/mail/rishabh", "LS_COLORS": ""}, "ansible_userspace_bits": "64", "ansible_architecture": "x86_64", "ansible_default_ipv4": {"macaddress": "52:54:00:28:be:a6", "network": "192.168.122.0", "mtu": 1362, "broadcast": "192.168.122.255", "alias": "eth0", "netmask": "255.255.255.0", "address": "192.168.122.159", "interface": "eth0", "type": "ether", "gateway": "192.168.122.1"}, "ansible_swapfree_mb": 1902, "ansible_default_ipv6": {}, "ansible_cmdline": {"BOOT_IMAGE": "/boot/vmlinuz-3.10.0-957.27.2.el7.x86_64", "quiet": true, "rhgb": true, "ro": true, "root": "UUID=f9d999f4-2208-4b09-89f1-9ef9cd5b16de", "vconsole.keymap": "us"}, "ansible_machine_id": "a71160257db945cf99ac37341b94578d", "ansible_userspace_architecture": "x86_64", "ansible_product_uuid": "C787BD66-E5A5-4612-9C63-3CE3D8D1C418", "ansible_pkg_mgr": "yum", "ansible_distribution": "RedHat", "ansible_iscsi_iqn": "iqn.1994-05.com.redhat:8cf458e09665", "ansible_all_ipv6_addresses": ["fe80::ccdd:608a:8e06:14aa"], "ansible_uptime_seconds": 1747, "ansible_kernel": "3.10.0-957.27.2.el7.x86_64", "ansible_system_capabilities_enforced": "True", "ansible_python": {"executable": "/usr/bin/python", "version": {"micro": 5, "major": 2, "releaselevel": "final", "serial": 0, "minor": 7}, "type": "CPython", "has_sslcontext": true, "version_info": [2, 7, 5, "final", 0]}, "ansible_is_chroot": false, "ansible_hostnqn": "", "ansible_user_shell": "/bin/bash", "ansible_product_serial": "PF1J7EV7-RedHat-c787bd66-e5a5-4612-9c63-3ce3d8d1c418", "ansible_form_factor": "Other", "ansible_distribution_file_parsed": true, "ansible_fips": false, "ansible_user_id": "root", "ansible_selinux_python_present": true, "ansible_kernel_version": "#1 SMP Tue Jul 9 16:53:14 UTC 2019", "ansible_local": {}, "ansible_processor_vcpus": 2, "ansible_processor": ["0", "GenuineIntel", "Intel Core Processor (Skylake, IBRS)", "1", "GenuineIntel", "Intel Core Processor (Skylake, IBRS)"], "ansible_ssh_host_key_ecdsa_public": "AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJpzU83XkY9vbbg85JZK8EbBiKxeqGDwJjBjNmiL8oI0b/en5rHEz42YdsPgT0GoEYM/UpZzgA4BKyWJnkXNeOg=", "ansible_user_gid": 0, "ansible_system_vendor": "Red Hat", "ansible_swaptotal_mb": 1906, "ansible_distribution_major_version": "7", "ansible_real_group_id": 0, "ansible_lsb": {"release": "7.6", "major_release": "7", "codename": "Maipo", "id": "RedHatEnterpriseWorkstation", "description": "Red Hat Enterprise Linux Workstation release 7.6 (Maipo)"}, "ansible_machine": "x86_64", "ansible_ssh_host_key_rsa_public": "AAAAB3NzaC1yc2EAAAADAQABAAABAQDE3JNa3JDGR+vietnNjMPCkM7VRRNoyJ9KFkxXLmwpxxGD3hpy1bP4sTK7bwz5FfOoKCBjeXxv4aqp821wZvFvwxtnYEabWRnJ+MZQvzHuCbzL0aKxV45BCcoi2+ykbedIhoeIRsPWTOlGVptuNMFUSjsI95OhWgv4gFOt8T6FIOVCjmAE1J3sKFa2ZFasZygHLLcqOzEmdGFkgygLKeryuEnfyo5M4Y8Armnmusw4yI1IGjyO2A6ve40TrMTd/wpXWRthtrcgo02KHlJWAp9drpXXgQgOmhMHFrk1tAjsxj1ArUq5MmWvXQl0/1sI6yP0BDHglLNKVeOsoXPlsJEN", "ansible_user_gecos": "root", "ansible_processor_threads_per_core": 1, "ansible_eth0": {"macaddress": "52:54:00:28:be:a6", "features": {"tx_checksum_ipv4": "off [fixed]", "generic_receive_offload": "on", "tx_checksum_ipv6": "off [fixed]", "tx_scatter_gather_fraglist": "off [fixed]", "rx_all": "off [fixed]", "highdma": "on [fixed]", "rx_fcs": "off [fixed]", "tx_lockless": "off [fixed]", "tx_tcp_ecn_segmentation": "on", "rx_udp_tunnel_port_offload": "off [fixed]", "tx_tcp6_segmentation": "on", "tx_gso_robust": "off [fixed]", "tx_ipip_segmentation": "off [fixed]", "tx_tcp_mangleid_segmentation": "off", "tx_checksumming": "on", "vlan_challenged": "off [fixed]", "loopback": "off [fixed]", "fcoe_mtu": "off [fixed]", "scatter_gather": "on", "tx_checksum_sctp": "off [fixed]", "tx_vlan_stag_hw_insert": "off [fixed]", "rx_vlan_stag_hw_parse": "off [fixed]", "tx_gso_partial": "off [fixed]", "rx_gro_hw": "off [fixed]", "rx_vlan_stag_filter": "off [fixed]", "large_receive_offload": "off [fixed]", "tx_scatter_gather": "on", "rx_checksumming": "on [fixed]", "tx_tcp_segmentation": "on", "netns_local": "off [fixed]", "busy_poll": "off [fixed]", "generic_segmentation_offload": "on", "tx_udp_tnl_segmentation": "off [fixed]", "tcp_segmentation_offload": "on", "l2_fwd_offload": "off [fixed]", "rx_vlan_offload": "off [fixed]", "ntuple_filters": "off [fixed]", "tx_gre_csum_segmentation": "off [fixed]", "tx_nocache_copy": "off", "tx_udp_tnl_csum_segmentation": "off [fixed]", "udp_fragmentation_offload": "on", "tx_sctp_segmentation": "off [fixed]", "tx_sit_segmentation": "off [fixed]", "tx_checksum_fcoe_crc": "off [fixed]", "hw_tc_offload": "off [fixed]", "tx_checksum_ip_generic": "on", "tx_fcoe_segmentation": "off [fixed]", "rx_vlan_filter": "on [fixed]", "tx_vlan_offload": "off [fixed]", "receive_hashing": "off [fixed]", "tx_gre_segmentation": "off [fixed]"}, "pciid": "virtio0", "module": "virtio_net", "mtu": 1362, "device": "eth0", "promisc": false, "timestamping": ["rx_software", "software"], "ipv4": {"broadcast": "192.168.122.255", "netmask": "255.255.255.0", "network": "192.168.122.0", "address": "192.168.122.159"}, "ipv6": [{"scope": "link", "prefix": "64", "address": "fe80::ccdd:608a:8e06:14aa"}], "active": true, "type": "ether", "hw_timestamp_filters": []}, "ansible_system": "Linux", "ansible_all_ipv4_addresses": ["192.168.122.159"], "ansible_python_version": "2.7.5", "ansible_product_version": "RHEL7", "ansible_service_mgr": "systemd", "ansible_memory_mb": {"real": {"total": 1999, "used": 1925, "free": 74}, "swap": {"cached": 0, "total": 1906, "free": 1902, "used": 4}, "nocache": {"used": 1280, "free": 719}}, "ansible_user_dir": "/root", "gather_subset": ["all"], "ansible_real_user_id": 0, "ansible_virtualization_role": "guest", "ansible_dns": {"nameservers": ["192.168.122.1"], "search": ["ibm.com"]}, "ansible_effective_group_id": 0, "ansible_lo": {"features": {"tx_checksum_ipv4": "off [fixed]", "generic_receive_offload": "on", "tx_checksum_ipv6": "off [fixed]", "tx_scatter_gather_fraglist": "on [fixed]", "rx_all": "off [fixed]", "highdma": "on [fixed]", "rx_fcs": "off [fixed]", "tx_lockless": "on [fixed]", "tx_tcp_ecn_segmentation": "on", "rx_udp_tunnel_port_offload": "off [fixed]", "tx_tcp6_segmentation": "on", "tx_gso_robust": "off [fixed]", "tx_ipip_segmentation": "off [fixed]", "tx_tcp_mangleid_segmentation": "on", "tx_checksumming": "on", "vlan_challenged": "on [fixed]", "loopback": "on [fixed]", "fcoe_mtu": "off [fixed]", "scatter_gather": "on", "tx_checksum_sctp": "on [fixed]", "tx_vlan_stag_hw_insert": "off [fixed]", "rx_vlan_stag_hw_parse": "off [fixed]", "tx_gso_partial": "off [fixed]", "rx_gro_hw": "off [fixed]", "rx_vlan_stag_filter": "off [fixed]", "large_receive_offload": "off [fixed]", "tx_scatter_gather": "on [fixed]", "rx_checksumming": "on [fixed]", "tx_tcp_segmentation": "on", "netns_local": "on [fixed]", "busy_poll": "off [fixed]", "generic_segmentation_offload": "on", "tx_udp_tnl_segmentation": "off [fixed]", "tcp_segmentation_offload": "on", "l2_fwd_offload": "off [fixed]", "rx_vlan_offload": "off [fixed]", "ntuple_filters": "off [fixed]", "tx_gre_csum_segmentation": "off [fixed]", "tx_nocache_copy": "off [fixed]", "tx_udp_tnl_csum_segmentation": "off [fixed]", "udp_fragmentation_offload": "on", "tx_sctp_segmentation": "on", "tx_sit_segmentation": "off [fixed]", "tx_checksum_fcoe_crc": "off [fixed]", "hw_tc_offload": "off [fixed]", "tx_checksum_ip_generic": "on [fixed]", "tx_fcoe_segmentation": "off [fixed]", "rx_vlan_filter": "off [fixed]", "tx_vlan_offload": "off [fixed]", "receive_hashing": "off [fixed]", "tx_gre_segmentation": "off [fixed]"}, "hw_timestamp_filters": [], "mtu": 65536, "device": "lo", "promisc": false, "timestamping": ["rx_software", "software"], "ipv4": {"broadcast": "host", "netmask": "255.0.0.0", "network": "127.0.0.0", "address": "127.0.0.1"}, "ipv6": [{"scope": "host", "prefix": "128", "address": "::1"}], "active": true, "type": "loopback"}, "ansible_memtotal_mb": 1999, "ansible_device_links": {"masters": {}, "labels": {}, "ids": {"sr0": ["ata-QEMU_DVD-ROM_QM00003"]}, "uuids": {"vda1": ["f9d999f4-2208-4b09-89f1-9ef9cd5b16de"], "vda2": ["b7d26130-b27a-4a59-bb04-a8e1e36a0c6c"]}}, "ansible_apparmor": {"status": "disabled"}, "ansible_proc_cmdline": {"BOOT_IMAGE": "/boot/vmlinuz-3.10.0-957.27.2.el7.x86_64", "quiet": true, "rhgb": true, "ro": true, "root": "UUID=f9d999f4-2208-4b09-89f1-9ef9cd5b16de", "vconsole.keymap": "us"}, "ansible_memfree_mb": 74, "ansible_processor_count": 2, "ansible_hostname": "oc8181710604", "ansible_interfaces": ["lo", "eth0"], "ansible_selinux": {"status": "disabled"}, "ansible_fqdn": "localhost.localdomain", "ansible_mounts": [{"block_used": 2966590, "uuid": "f9d999f4-2208-4b09-89f1-9ef9cd5b16de", "size_total": 29603262464, "block_total": 7227359, "mount": "/", "block_available": 4260769, "size_available": 17452109824, "fstype": "ext4", "inode_total": 1844160, "options": "rw,relatime,data=ordered", "device": "/dev/vda1", "inode_used": 180403, "block_size": 4096, "inode_available": 1663757}], "ansible_nodename": "oc8181710604.ibm.com", "ansible_distribution_file_search_string": "Red Hat", "ansible_lvm": {"pvs": {}, "lvs": {}, "vgs": {}}, "ansible_domain": "localdomain", "ansible_distribution_file_path": "/etc/redhat-release", "ansible_virtualization_type": "kvm", "ansible_ssh_host_key_ed25519_public": "AAAAC3NzaC1lZDI1NTE5AAAAIOAUurGLdKEqz5GX+v7eD8Tfv55wk7st8slwniBbhAjd", "ansible_processor_cores": 1, "ansible_bios_version": "0.5.1", "ansible_date_time": {"weekday_number": "2", "iso8601_basic_short": "20200414T055943", "tz": "EDT", "weeknumber": "15", "hour": "05", "year": "2020", "minute": "59", "tz_offset": "-0400", "month": "04", "epoch": "1586858383", "iso8601_micro": "2020-04-14T09:59:43.758041Z", "weekday": "Tuesday", "time": "05:59:43", "date": "2020-04-14", "iso8601": "2020-04-14T09:59:43Z", "day": "14", "iso8601_basic": "20200414T055943757869", "second": "43"}, "ansible_distribution_release": "Maipo", "ansible_os_family": "RedHat", "ansible_effective_user_id": 0, "ansible_product_name": "KVM", "ansible_devices": {"vda": {"scheduler_mode": "mq-deadline", "rotational": "1", "vendor": "0x1af4", "sectors": "62914560", "links": {"masters": [], "labels": [], "ids": [], "uuids": []}, "sas_device_handle": null, "sas_address": null, "virtual": 1, "host": "SCSI storage controller: Red Hat, Inc. Virtio block device", "sectorsize": "512", "removable": "0", "support_discard": "0", "model": null, "partitions": {"vda1": {"sectorsize": 512, "uuid": "f9d999f4-2208-4b09-89f1-9ef9cd5b16de", "links": {"masters": [], "labels": [], "ids": [], "uuids": ["f9d999f4-2208-4b09-89f1-9ef9cd5b16de"]}, "sectors": "59006976", "start": "2048", "holders": [], "size": "28.14 GB"}, "vda2": {"sectorsize": 512, "uuid": "b7d26130-b27a-4a59-bb04-a8e1e36a0c6c", "links": {"masters": [], "labels": [], "ids": [], "uuids": ["b7d26130-b27a-4a59-bb04-a8e1e36a0c6c"]}, "sectors": "3905536", "start": "59009024", "holders": [], "size": "1.86 GB"}}, "holders": [], "size": "30.00 GB"}, "sr0": {"scheduler_mode": "deadline", "rotational": "1", "vendor": "QEMU", "sectors": "2097151", "links": {"masters": [], "labels": [], "ids": ["ata-QEMU_DVD-ROM_QM00003"], "uuids": []}, "sas_device_handle": null, "sas_address": null, "virtual": 1, "host": "IDE interface: Intel Corporation 82371SB PIIX3 IDE [Natoma/Triton II]", "sectorsize": "512", "removable": "1", "support_discard": "0", "model": "QEMU DVD-ROM", "partitions": {}, "holders": [], "size": "1024.00 MB"}}, "ansible_user_uid": 0, "ansible_bios_date": "01/01/2011", "ansible_system_capabilities": ["cap_chown", "cap_dac_override", "cap_dac_read_search", "cap_fowner", "cap_fsetid", "cap_kill", "cap_setgid", "cap_setuid", "cap_setpcap", "cap_linux_immutable", "cap_net_bind_service", "cap_net_broadcast", "cap_net_admin", "cap_net_raw", "cap_ipc_lock", "cap_ipc_owner", "cap_sys_module", "cap_sys_rawio", "cap_sys_chroot", "cap_sys_ptrace", "cap_sys_pacct", "cap_sys_admin", "cap_sys_boot", "cap_sys_nice", "cap_sys_resource", "cap_sys_time", "cap_sys_tty_config", "cap_mknod", "cap_lease", "cap_audit_write", "cap_audit_control", "cap_setfcap", "cap_mac_override", "cap_mac_admin", "cap_syslog", "35", "36+ep"]}}\r\n', b'Shared connection to 192.168.122.159 closed.\r\n')
44
44
<192.168.122.159> ESTABLISH SSH CONNECTION FOR USER: rishabh
45
45
<192.168.122.159> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="rishabh"' -o ConnectTimeout=10 -o ControlPath=/tmp/awx_192_clx4mb53/cp/75e0627c37 192.168.122.159 '/bin/sh -c '"'"'rm -f -r /home/rishabh/.ansible/tmp/ansible-tmp-1586858378.490975-151761252064871/ > /dev/null 2>&1 && sleep 0'"'"''
46
46
<192.168.122.159> (0, b'', b'')
47
47
ok: [192.168.122.159]
48
48
META: ran handlers
49
49
50
TASK [Copy file] ***************************************************************
05:59:44
51
task path: /tmp/awx_192_clx4mb53/project/remotecopy.yml:4
52
52
<192.168.122.159> ESTABLISH SSH CONNECTION FOR USER: rishabh
53
53
<192.168.122.159> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="rishabh"' -o ConnectTimeout=10 -o ControlPath=/tmp/awx_192_clx4mb53/cp/75e0627c37 192.168.122.159 '/bin/sh -c '"'"'echo ~rishabh && sleep 0'"'"''
54
54
<192.168.122.159> (0, b'/home/rishabh\n', b'')
55
55
<192.168.122.159> ESTABLISH SSH CONNECTION FOR USER: rishabh
56
56
<192.168.122.159> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="rishabh"' -o ConnectTimeout=10 -o ControlPath=/tmp/awx_192_clx4mb53/cp/75e0627c37 192.168.122.159 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/rishabh/.ansible/tmp/ansible-tmp-1586858384.219259-28887785123492 `" && echo ansible-tmp-1586858384.219259-28887785123492="` echo /home/rishabh/.ansible/tmp/ansible-tmp-1586858384.219259-28887785123492 `" ) && sleep 0'"'"''
57
57
<192.168.122.159> (0, b'ansible-tmp-1586858384.219259-28887785123492=/home/rishabh/.ansible/tmp/ansible-tmp-1586858384.219259-28887785123492\n', b'')
58
58
<192.168.122.159> ESTABLISH SSH CONNECTION FOR USER: rishabh
59
59
<192.168.122.159> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="rishabh"' -o ConnectTimeout=10 -o ControlPath=/tmp/awx_192_clx4mb53/cp/75e0627c37 192.168.122.159 '/bin/sh -c '"'"'rm -f -r /home/rishabh/.ansible/tmp/ansible-tmp-1586858384.219259-28887785123492/ > /dev/null 2>&1 && sleep 0'"'"''
60
60
<192.168.122.159> (0, b'', b'')
61
61
The full traceback is:
62
Traceback (most recent call last):
63
  File "/usr/lib/python3.6/site-packages/ansible/plugins/action/copy.py", line 464, in run
64
    source = self._find_needle('files', source)
65
  File "/usr/lib/python3.6/site-packages/ansible/plugins/action/__init__.py", line 1178, in _find_needle
66
    return self._loader.path_dwim_relative_stack(path_stack, dirname, needle)
67
  File "/usr/lib/python3.6/site-packages/ansible/parsing/dataloader.py", line 319, in path_dwim_relative_stack
68
    raise AnsibleFileNotFound(file_name=source, paths=[to_native(p) for p in search])
69
ansible.errors.AnsibleFileNotFound: Could not find or access '/tmp/testcopy.txt' on the Ansible Controller.
70
If you are using a module and expect the file to exist on the remote, see the remote_src option
71
fatal: [192.168.122.159]: FAILED! => {
72
    "changed": false,
73
    "invocation": {
74
        "dest": "/home/rishabh",
75
        "module_args": {
76
            "dest": "/home/rishabh",
77
            "remote_src": false,
78
            "src": "/tmp/testcopy.txt"
79
        },
80
        "remote_src": false,
81
        "src": "/tmp/testcopy.txt"
82
    },
83
    "msg": "Could not find or access '/tmp/testcopy.txt' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"
84
}
85
85
86
PLAY RECAP *********************************************************************
05:59:45
87
192.168.122.159            : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
88
===================================================================

**Comment by ryanpetrello** [comment]
Hey @rishabhgupta1608,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
