### ISSUE TITLE
Installation on Arch Linux fails

### ISSUE THREAD

**Issue by inmylo** [ansible/awx#67]
### Summary

Trying to install AWX locally on Arch Linux. Ansible script fails at the task `local_docker : Activate AWX Web Container`:

    fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error starting 
    container 9678e6be283aa929a6aac1a7d22cdf95731b10614fd2ecb1673447788e5204f6: 
    500 Server Error: Internal Server Error (\"driver failed programming external connectivity 
    on endpoint awx_web 
    (b48d02b5b6c05f4fd902de292a6e4efbe896daa7b5bba93b6119022f75de5fe5):  (iptables 
    failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 80 -j DNAT --to-destination 
    172.17.0.5:8052 ! -i docker0: iptables: No chain/target/match by that name.\n (exit 
    status 1))\")"}`

### Environment

* AWX version: 1.0.0.288
* Ansible version: 2.3.2.0
* Operating System: Arch Linux 64bit
* Web Browser: Chromium

### Steps To Reproduce:

Get Arch Linux, install iptables, docker, AWX requirements, clone Git repo, go to **installer** folder and launch `ansible-playbook -i inventory install.yml`.

### Expected Results:

Ansible script finishes without any errors.

### Actual Results:

Got an error during installation, inserted in **Summary**.

### Additional Information:

* There exists **DOCKER** chain in **nat** and **filter** tables
* **DOCKER-ISOLATION** and **DOCKER-USER** also exist in **filter**
* network interface **docker0** exists and is UP

```
[root@dell installer]# cat /proc/net/ip_tables_targets
CHECKSUM
NFLOG
CONNMARK
MASQUERADE
REJECT
LOG
ERROR
```

**Comment by JSkier21** [comment]
What version of npm and nodejs are you running? I can't seem to get it to go as far as you (ansible script doesn't even finish running without several errors).

**Comment by matburt** [comment]
This doesn't seem like a bug in awx so much as an issue with docker on arch linux. Having said that I just ran through the install with Arch and kernel `4.12.8-1-ARCH #1 SMP PREEMPT`

**Comment by matburt** [comment]
@JSkier21 the node/npm requirements are in the CONTRIBUTING.md file.

**Comment by JSkier21** [comment]
@matburt, thanks, I'll try compiling the LTS version of npm. I originally installed the LTS package for node (Arch separates it from npm) and an older package of npm (LTS not available in Arch for that).

**Comment by matburt** [comment]
Lacking any further details, I'm going to close this. If more details come up then let us know.

**Comment by inmylo** [comment]
@matburt , what other details do you need?

**Comment by inmylo** [comment]
Probably it was a problem on my side, after OS update and PC restart installation script has finished normally
