### ISSUE TITLE
Silence error : django.db.utils.IntegrityError when admin user already exist

### ISSUE THREAD

**Issue by ghost** [ansible/awx#6701]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Silence error : django.db.utils.IntegrityError: duplicate key value violates unique constraint "auth_user_username_key" when admin user already exist in database.

This error don't cause any issue, and should be silence like proposed [here](https://github.com/ansible/awx/issues/800)

##### ENVIRONMENT
* AWX version: 9.3.0
* AWX install method: docker on linux
* Ansible version:  2.9.5
* Operating System: Linux Debian Testing
* Web Browser: Firefox:lastest

##### STEPS TO REPRODUCE

Start  an already installed AWX using docker-compose up and see log. 

##### EXPECTED RESULTS

No error in log as there is no issue

##### ACTUAL RESULTS
A big traceback in log due to this exception that can be misunderstood.

**Comment by shanemcd** [comment]
It looks like we reworked this at some point:

https://github.com/ansible/awx/blob/1e690fcd7f2854dda493722f0084a4f22758823b/tools/docker-compose/bootstrap_development.sh#L35-L38
