### ISSUE TITLE
Detail Label text alignment 

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#6705]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The detail label text is currently center-aligned, but it should align vertically to the top. This style update would be a sweeping change, so it would be a good idea to run this through Percy. 

##### EXPECTED RESULTS
_Options Label aligned to the top_

![image](https://user-images.githubusercontent.com/15881645/79257483-af81df00-7e57-11ea-837d-31a841327454.png)

##### ACTUAL RESULTS
_Options Label aligned to the center_
<img width="594" alt="Screen Shot 2020-04-14 at 1 56 31 PM" src="https://user-images.githubusercontent.com/15881645/79257537-c32d4580-7e57-11ea-94d7-9a411035a82f.png">

**Comment by unlikelyzero** [comment]
covered in job-templates.spec.js
