### ISSUE TITLE
can't inject unicode extra vars with custom credentials

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#671]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY

I cannot inject unicode extra vars with a custom credential type.

##### ENVIRONMENT
* AWX version: 1.any

##### STEPS TO REPRODUCE

1. Create a custom credential type
2. Unleash the dragon in the injector
```
extra_vars:
  '🐉🐉🐉': '{{ dragon_name }}'
```

##### EXPECTED RESULTS

Succeeds (this works when setting regular extra_vars)

##### ACTUAL RESULTS

Validation error:
`'\U0001f409\U0001f409\U0001f409' does not match any of the regexes: '^[a-zA-Z_]+[a-zA-Z0-9_]*$'`

**Comment by ryanpetrello** [comment]
We decided not to do this due to a lack of support for unicode extra vars in Ansible itself.
