### ISSUE TITLE
Playbook to instal fails for local docker

### ISSUE THREAD

**Issue by xavileci** [ansible/awx#6715]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The playbook to install aAWX in local docker fail. it's like the compose it's not right

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.7
* Operating System: Debian GNU/Linux 10 (buster)
* Web Browser:

##### STEPS TO REPRODUCE

I've followed the steps defined in this URL: https://computingforgeeks.com/how-to-install-ansible-awx-on-ubuntu-linux/
The steps are:
as root user
1st clone the repository on /opt
2nd mv to /opt/awx/installer
3rd configure inventory
4th Execute:  `ansible-playbook -i inventory install.yml`

##### EXPECTED RESULTS
Execute and playbook to install and start awx service

##### ACTUAL RESULTS

Error executing playbook:

> ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
> 
> The error appears to have been in '/opt/awx/installer/roles/local_docker/tasks/compose.yml': line 45, column 7, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
> - block:
>     - name: Start the containers
>       ^ here

##### ADDITIONAL INFORMATION

I've followed the steps referenced in this URL: https://computingforgeeks.com/how-to-install-ansible-awx-on-ubuntu-linux/

**Comment by ryanpetrello** [comment]
https://github.com/ansible/awx/blob/devel/INSTALL.md#prerequisites

> Ansible Requires Version 2.8+
