### ISSUE TITLE
credential injector validation error isn't user-friendly for "valid yaml, invalid injector"

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#672]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY

When I pass valid YAML for an injector that isn't a valid injector configuration, the error is not user-friendly.

##### ENVIRONMENT
* AWX version: 1.x

##### STEPS TO REPRODUCE

Write a new credential type.

Enter the following YAML as an injector, because you forgot the syntax:
```
extra_vars:
 - 'a': "{{ b }}"
 - 'c': "{{ d }}"
```

##### EXPECTED RESULTS

Not sure, something like:

`List passed, expected dictionary`.

##### ACTUAL RESULTS

`[OrderedDict([('a', '{{ b }}')]), OrderedDict([('c', '{{ d }}')])] is not of type 'object'`

##### ADDITIONAL INFORMATION

Probably applies to inputs as well.

**Comment by AlanCoding** [comment]
fix is in
