### ISSUE TITLE
vCenter dynamic inventory imports hostname in format 'name_uuid'

### ISSUE THREAD

**Issue by alexsuppanz** [ansible/awx#6727]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When using the VMware vCenter dynamic inventory the host name is imported in the format 'name_uuid'.  For example:
`awx_43374ba9-b3f0-74cb-9ac4-fc4fa55bb14b`

When using the limit parameter the hostname has to be in format `awx_*` , otherwise it does not match any hosts.

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.5
* Operating System: CentOS 7.7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Add VMware vSphere as dynamic inventory source and start sync process

##### EXPECTED RESULTS

Hosts are imported with the name as shown in the vCenter UI or using the hostname provided by VMware Tools installed on the VM

##### ACTUAL RESULTS

Host names are imported in the format 'name_uuid'.  For example:
`awx_43374ba9-b3f0-74cb-9ac4-fc4fa55bb14b`

##### ADDITIONAL INFORMATION

Already tried to things to workaround this problem:
Add the following line to the Source Variables of the inventory source
`alias_pattern: {{ config.name }}`

Edited vmware_inventory.py and changed line 228 from `'alias_pattern': '{{ config.name + "_" + config.uuid }}'` to `'alias_pattern': '{{ config.name }}'`

But host names are still shown in format name_uuid

Is this a expected behaviour?
Is anyone else facing this issue? What can be done to change the name of the imported hosts?

**Comment by AlanCoding** [comment]
Have you tried putting this in source variables, as opposed to modifying the code?

```yaml
alias_pattern: "{{ config.uuid }}"
```

https://github.com/ansible/ansible/blob/stable-2.9/contrib/inventory/vmware_inventory.ini#L56

source variables are passed through to the config

https://github.com/ansible/awx/blob/00aa1ad295126e5a62f4cd978e9dcba076ffde1e/awx/main/models/inventory.py#L2238-L2239

**Comment by alexsuppanz** [comment]
This was my first idea, already tried it, but I used `alias_pattern: "{{ config.name }}"` , sine I want the hostname in the inventory, not the uuid.

What's the difference between the vmware_inventory.py of AWX and the vmware_inventory.ini of ansible mentioned by you?

**Comment by AlanCoding** [comment]
Are you doing that with a new inventory, or trying again with your existing inventory? The only thing I can think of is that it's tracking the hosts via the instance_id, and not changing the names to the updated ones.

> What's the difference between the vmware_inventory.py of AWX and the vmware_inventory.ini of ansible mentioned by you?

when an inventory import is ran, the server generates a file similar to the example `vmware_inventory.ini`, and the options you put in should be reflected in that.

**Comment by alexsuppanz** [comment]
Despite the time I spent to identify and reproduce the issue, the solution seems quite simple. I had an quotation mark in `alias_pattern: "{{ config.name }}"` , before the colon. I created a new inventory and fixed the typo, now my hosts are imported with hostnames and without uuid

**Comment by AlanCoding** [comment]
Putting on needs_test to make sure that it does not regress with https://github.com/ansible/awx/pull/6283

**Comment by kdelee** [comment]
@AlanCoding we have regression tests for this option, I'm going to close

**Comment by jram123** [comment]
I am also facing this issue. there is no typo error here. I have tried keeping in source variables and as well as changed in vmware_inventory.py file. But nothing seems worked

**Comment by Shadow2091** [comment]
Yep, the same problem. `alias_pattern: "{{ config.name }}"` didn't work.

**Comment by evoncken** [comment]
The same issue still exists on AWX 19.5.0
Installed via AWX Operator, K3s on AlmaLinux 8.5
```
    # kubectl version --short
    Client Version: v1.22.5+k3s1
    Server Version: v1.22.5+k3s1
```
vCenter inventory plugin returns hostnames in the form "awx_42208b61-bfe2-c3a8-ca82-2ae2218402b0". In vmware_inventory.py around line 230, the alias_pattern seems to be with UUID:
```
    'alias_pattern': '{{ config.name + "_" + config.uuid }}',
```

Perhaps I'm misunderstanding - but this default does not make a lot of sense to me?

**Comment by asmith432** [comment]
@evoncken under Source Variables use the following:
```
---
hostnames: 
- config.name
```
Documentation for reference: https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vm_inventory_inventory.html

**Comment by achebib** [comment]
> The same issue still exists on AWX 19.5.0 Installed via AWX Operator, K3s on AlmaLinux 8.5
> 
> ```
>     # kubectl version --short
>     Client Version: v1.22.5+k3s1
>     Server Version: v1.22.5+k3s1
> ```
> 
> vCenter inventory plugin returns hostnames in the form "awx_42208b61-bfe2-c3a8-ca82-2ae2218402b0". In vmware_inventory.py around line 230, the alias_pattern seems to be with UUID:
> 
> ```
>     'alias_pattern': '{{ config.name + "_" + config.uuid }}',
> ```
> 
> Perhaps I'm misunderstanding - but this default does not make a lot of sense to me?

How do you access tha file? I am unable to find it

**Comment by malacration** [comment]
I'm having the same problem, has anyone managed to solve it?

**Comment by malacration** [comment]
> @evoncken under Source Variables use the following:
> 
> ```
> ---
> hostnames: 
> - config.name
> ```
> 
> Documentation for reference: https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vm_inventory_inventory.html

This worked for me
