### ISSUE TITLE
Job Results Panel not Updating during template execution

### ISSUE THREAD

**Issue by orgito** [ansible/awx#673]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
The Job Results panel does not show tasks progress during the job template execution.

##### ENVIRONMENT
* AWX version: 1.0.1.215
* AWX install method: docker on linux
* Ansible version:  2.4.1.0
* Operating System: Centos 7.4
* Web Browser: Chrome 62

##### STEPS TO REPRODUCE
1) Run a job template

##### EXPECTED RESULTS

The Jop Results screen appears and show the status of the tasks as they execute

##### ACTUAL RESULTS

The Jop Results screen appears but never updates

##### ADDITIONAL INFORMATION

Exiting the job results screen and coming back to it show the newly updated status, but does not keep updating.

**Comment by ryanpetrello** [comment]
@orgito a change recently landed in awx that upgraded Django and a handful of other third party libraries that awx relies on (including one we use for managing websockets). What you're encountering sounds like a bug that's currently being diagnosed in the websocket library:

#615

Stay tuned!
