### ISSUE TITLE
Redirect on lists is broken if the previous page's items are also deleted

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#6734]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Essentially, when deleting all items with the select-all toggle, lists should redirect to the lowest number page which contains items. However, if the previous page is also empty, the list 404s.

##### STEPS TO REPRODUCE
I used credentials for this bug.

1. Create 6 credentials.
2. Hit the select-all checkbox.
3. Set the list so that it only shows 5 per page.
2. Go to the second page, and click delete, so that it deletes all six credentials.

##### EXPECTED RESULTS
an empty credential list on the first page.

##### ACTUAL RESULTS
a 404 on the second page.
![Screenshot_20200416_142405](https://user-images.githubusercontent.com/19942822/79492902-b0994480-7fee-11ea-80e6-33ec43697af1.png)

**Comment by AlexSCorey** [comment]
blocked until we can decide what we are actually going to delete when someone clicks selectAll.  Do we delete only the items in the list that are rendered? Or do we delete all items, even those on other pages?  How do we handle when the user clicks SelectAll and then navigates to another page?  Should select all be clicked?  What about search, sort and filter?

**Comment by AlexSCorey** [comment]
Decisions reached re: SelectAll. Based on conversation with API, UI and Project Manager we decided that SelectAll will only delete those items on the screen.  So, if you select all on page 1, and then move to page 2 and click select all on that page as well only the items on page 2 will be deleted.  

We will keep an eye on https://www.patternfly.org/v4/documentation/react/demos/bulkselecttable and https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/bulk-selection and consider those if/when we adopt PF tables.


![image copy](https://user-images.githubusercontent.com/39280967/80140606-303a8c80-8576-11ea-81b7-6f72298f3198.jpg)

**Comment by AlexSCorey** [comment]
Blocked until #6853 lands.  These issues could be worked on together.

**Comment by mabashian** [comment]
I actually don't really see this as a very likely problem to run in to as long as we only delete the visible rows.  If anything we could have the list redirect back to page 1 when we detect that a user is attempting to access a page that comes back 404.  Or we could just show this error since it's valid.

**Comment by unlikelyzero** [comment]
dropping to low after looking at impact and likelihood that this would come up

**Comment by akus062381** [comment]
this is resolved.
