### ISSUE TITLE
Job output out of order, download not working

### ISSUE THREAD

**Issue by johnjeffers** [ansible/awx#674]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Output in the Job details is out of order, Download Output button is broken.

##### ENVIRONMENT
* AWX version: 1.0.1.215
* AWX install method: docker on linux
* Ansible version:  2.4.1.0
* Operating System: CentOS 7
* Web Browser: Chrome 62

##### STEPS TO REPRODUCE

Run a job, view the output

##### EXPECTED RESULTS

Lines in the job output appear in the correct order.
Download Output button works as expected.

##### ACTUAL RESULTS

Lines in the job output are out of order. See attached screenshots:

<img width="1182" alt="screen shot 2017-11-16 at 2 43 28 pm" src="https://user-images.githubusercontent.com/11821214/32917498-a09ba98e-cadc-11e7-80eb-b0635cfbb953.png">

<img width="1179" alt="screen shot 2017-11-16 at 2 43 45 pm" src="https://user-images.githubusercontent.com/11821214/32917521-acf37342-cadc-11e7-89d1-e4dac2d135a3.png">

Download Output button returns `{"detail":"Not found."}`

**Comment by matburt** [comment]
This will be taken care of here: https://github.com/ansible/awx/issues/200
