### ISSUE TITLE
Use Webhook Fields in WFJT Form

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#6742]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
We just created a webhook fields subform for JT Form.  That same component could also be used for WFJT form.  

The webhook key and the webhook url field need some changes mentioned here https://github.com/ansible/awx/pull/6654#pullrequestreview-395653664

**Comment by nixocio** [comment]
Related to: https://github.com/ansible/awx/pull/6654
