### ISSUE TITLE
Allow metrics endpoint to be retrieved anonymously

### ISSUE THREAD

**Issue by svenstaro** [ansible/awx#6753]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
I think for some monitoring setups it might be helpful to have an option that would allow for retrieving `/api/v2/metrics` without being authenticated. It would be opt-in, though.

**Comment by blomquisg** [comment]
Maybe make this configurable...

**Comment by bryanasdev000** [comment]
+1

**Comment by mamercad** [comment]
+1

**Comment by texasbobs** [comment]
This would be amazing if it was a configurable option.
