### ISSUE TITLE
Ansible Tower REST API to add a host to an inventory is not working

### ISSUE THREAD

**Issue by vivekmandal** [ansible/awx#6754]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Following REST API is not working.
method - POST
/api/v2/inventories/{id}/hosts/

It is giving the exact response as GET method. and not adding the host to an inventory.

##### ENVIRONMENT
* Ansible Tower version: 3.2.5
* Ansible version: 2.9.4

##### STEPS TO REPRODUCE

Tried to execute the REST API through POSTMAN

##### EXPECTED RESULTS

The host should get added to an inventory

##### ACTUAL RESULTS

It gave the response as 200(OK) But showing the same response as we get for GET method

**Comment by ryanpetrello** [comment]
@vivekmandal

3.2.5 isn't an AWX version.  Can you provide an accurate version number?

**Comment by vivekmandal** [comment]
Hi, Actually this is the issue with Ansible Tower and not with AWX specifically. The version for ansible tower is 3.2.5. Below I am attaching the scrrenshot for the same.
![ansible_tower_issue](https://user-images.githubusercontent.com/37260650/79823017-3b43c000-83b0-11ea-8eef-fbfefd20d7f3.PNG)

**Comment by ryanpetrello** [comment]
Hey @vivekmandal,

This is the issue tracker for the open source AWX project; if you need assistance with Red Hat Ansible Tower, please contact Red Hat for support (though I'll note that the version of Ansible Tower you're running is out of date to the point of being beyond EOL - you might just want to consider upgrading to see if your problem goes away).
