### ISSUE TITLE
not able to start local containers

### ISSUE THREAD

**Issue by nishant2019** [ansible/awx#6755]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY

While installing I am getting error
TASK [local_docker : Start the containers] *****************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "errors": [], "module_stderr": "", "module_stdout": "", "msg": "Error starting project 500 Server Error: Internal Server Error (\"Get https://registry-1.docker.io/v2/library/memcached/manifests/alpine: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fmemcached%3Apull&service=registry.docker.io: net/http: TLS handshake timeout\")"}

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=15   changed=2    unreachable=0    failed=1    skipped=97   rescued=0    ignored=0   

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by ryanpetrello** [comment]
Whatever's going on here, it looks like a service issue with `docker.io`, not AWX:

> Error starting project 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/library/memcached/manifests/alpine: 

I suspect this was just a temporary outage, but if not, it's definitely not an issue with AWX.
