### ISSUE TITLE
Satellite 6.7 Inventory foreman_params remains empty

### ISSUE THREAD

**Issue by ghost** [ansible/awx#6758]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

When using satellite6(.7) as inventory source, the foreman_params are not populated whereas with satellite6.6 this worked.

##### ENVIRONMENT
* AWX version: 11.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.5
* Operating System: RHEL 7.7
* Web Browser: Chromium

##### STEPS TO REPRODUCE

- Use satellite6 as inventory and specify a satellite6.7 host
- Sync and check one of the hosts
- foreman_params is empty even when parameters are set

##### EXPECTED RESULTS

Parameters set in satellite are available in AWX

##### ACTUAL RESULTS

foreman_params: {}

##### ADDITIONAL INFORMATION

Satellite 6.6 worked fine but with the recently released update to 6.7 it doesn't work anymore.

**Comment by adgerth** [comment]
Hey everyone, just a quick update. I've updated to 11.1 and it works again. I think this issue can be closed.

**Comment by blomquisg** [comment]
@jladdjr can you talk to the Satellite team to see if something may have changed to cause this?

**Comment by ryanpetrello** [comment]
@adgerth,

We've recently moved to collection based inventory syncs in 11.2.0 - would you mind trying to reproduce this in that version?

**Comment by ghost** [comment]
@ryanpetrello 
I tried it and it seems to work. The foreman_params are being synced over.
