### ISSUE TITLE
rsyslogd: log aggregator settings w/ double quote characters break external logging

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#6760]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
![image](https://user-images.githubusercontent.com/214912/79778925-7fc75100-8307-11ea-9fdd-d7d382eca855.png)

![image](https://user-images.githubusercontent.com/214912/79778935-835ad800-8307-11ea-91be-bf692185e882.png)

**Comment by ryanpetrello** [comment]
cc @elyezer @rooftopcellist

**Comment by one-t** [comment]
Tested on devel using a logstash instance on the tower node. This works correctly now.
