### ISSUE TITLE
PostgreSQL fails to start

### ISSUE THREAD

**Issue by drew-viles** [ansible/awx#677]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY
I've been through the inventory file and adjusted everything as needed leaving the PostgreSQL as it was as I require a container spinning up.

##### ENVIRONMENT
* AWX version: Latest pull from github
* AWX install method: docker on linux
* Ansible version:  ansible 2.4.1.0
* Operating System: Amazon Linux AMI (Centos)
* Web Browser: N/A

##### STEPS TO REPRODUCE

After adjusting my inventory file slightly to update the awxsecret I have run the playbook: `ansible-playbook -i inventory install.yml`

This completed without any errors but then the PostgreSQL container is rebooting.
I have also tried this with all default settings in the inventory file to ensure it's nothing I've done.

##### EXPECTED RESULTS
As this is a fresh configuration I would expect all containers to spin up without errors.

##### ACTUAL RESULTS

On checking docker I get the following output
`$docker ps -a`
`6100ea4c99b3        postgres:9.6              "docker-entrypoint.sh"   7 minutes ago       Restarting (1) 56 seconds ago   5432/tcp                             postgres`

##### ADDITIONAL INFORMATION

Checking the logs with `docker logs -f 6100ea4c99b3` is spitting out the following error: 

> FATAL:  could not open directory "pg_tblspc": No such file or directory
> LOG:  database system is shut down

**Comment by matburt** [comment]
Can you try removing the directory you assigned to the postgres container and removing the postgres container itself and then re-running the setup playbook?

**Comment by drew-viles** [comment]
Hi,

I haven't manually assigned any dirs to this container to be used so have nothing to delete (that I'm aware of anyway)
Doing a locate on the VM is not returning anything that looks like it would be associated with the pg container either.

I'm not sure if it helps but this is a basic AWS EC2 VM which I'm using as a sandbox to test this before pushing through to the EC2 container service. This was working last week during initial testing and seems to have failed with the latest pull of the AWX code from github.

I've tried killing and removing the container and the associated image however I get the same result with the same error in the log:

> 784bea4e2624        postgres:9.6              "docker-entrypoint.sh"   32 seconds ago      Restarting (1) 8 seconds ago   5432/tcp                             postgres

With the directory you mentioned is this something that should be added now as I'm unable to see any option in the inv file.

Let me know if you require more info on this from my end and I'll keep digging on my side in the mean time.

**Comment by tchia04** [comment]
I had the same error. I had to nuke my /tmp/pg_docker directory and start from scratch and it came up fine.  I didn't have any important stuff in the postgres database so it was fine but I am worried to encounter this issue again

**Comment by ghost** [comment]
@tchia04 it's not a great idea to keep your Postgres database in a temp directory:  you'll lose that on reboot.

**Comment by drew-viles** [comment]
@tchia04 Thanks for that. It has sorted it out.

So the scenario is that I've not changed anything in the inventory file and wanted to get the base docker images up and running for AWX.
It seems an old run has left its PgSQL data in /tmp/pg_docker, not specified by me so can only presume this is something the playbook does by default or more likely a default for PgSQL

To resolve this in the end I've had to remove the /tmp/pg_docker directory, remove all docker containers and images and re-run the playbook.

This is now working again without issue.

Thanks for the help one this everyone.

**Comment by rladigital** [comment]
I have been having this exact issue. However whenever I get everything setup as I want, I get an issue with the Postgres database and I lose my entire setup. As I cannot bring the Postgres database back up with the data that is stored in /tmp/pgdocker. Any ideas how I can maintain this data persistently as currently I cannot make AWX work if I am concerned that the setup will break at anytime.

**Comment by ghost** [comment]
@rladigital just change the following value in installer/inventory.yml

# Standalone Docker Install
postgres_data_dir=/tmp/pgdocker

Stop your postgres container, rsync on your host from old path to new, docker rm the postgres container, re-run installer, happy days :D

**Comment by matburt** [comment]
Alternatively, follow the instructions in the install guide for pointing at a persistent postgres service managed by you: https://github.com/ansible/awx/blob/devel/INSTALL.md#postgresql-1
