### ISSUE TITLE
The information stored by the host is not visible in the group in awx-ui

### ISSUE THREAD

**Issue by bgkim0420** [ansible/awx#6771]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When registering an existing host in Group Management after adding a host the  description appears blank  in awx ui.

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method:  docker on linux
* Ansible version:  2.9.5
* Operating System: Centos 7.7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. inventoryries
2. inventory list -> hosts -> add host Name : target server ip, description : server ip
3. inventory list -> Groups -> Create Group -> hosts -> existing host

##### EXPECTED RESULTS

All information be visible.

##### ACTUAL RESULTS

Target Name only shown.

##### ADDITIONAL INFORMATION

![add host](https://user-images.githubusercontent.com/64085183/79873164-b2656c80-8421-11ea-9c5a-a229ed44ff01.png)
![existing hosts](https://user-images.githubusercontent.com/64085183/79873169-b2fe0300-8421-11ea-8e5f-7f66f75e54b8.png)

**Comment by marshmalien** [comment]
Thank you for reporting this issue. I'm closing this for now because we plan on removing the host description from table views in the future.
