### ISSUE TITLE
RFE: ad hoc command for network devices

### ISSUE THREAD

**Issue by akira6592** [ansible/awx#6772]
### ISSUE TYPE
 - Feature Idea

##### SUMMARY

On the ad hoc command execution screen, I can select several modules (eg command, yum).
However, it looks like nothing is available for network devices.
Neither the ping module nor the setup module works well for network devices.

So I would be happy to be able to use the cli_command module.

![image](https://user-images.githubusercontent.com/16851744/79875123-26087900-8424-11ea-9c9b-23c959e80218.png)

**Comment by ryanpetrello** [comment]
You can whitelist the commands available for adhoc here (you'll want to add `cli_command`):

![image](https://user-images.githubusercontent.com/214912/79876358-f1130c80-83b8-11ea-94ad-c9257a29661b.png)

![image](https://user-images.githubusercontent.com/214912/79876232-c7f27c00-83b8-11ea-9a07-415d709adaeb.png)

**Comment by akira6592** [comment]
@ryanpetrello Thank you! I was able to achieve what I wanted to do.
