### ISSUE TITLE
Docker Compose v3 update 

### ISSUE THREAD

**Issue by shaynecm** [ansible/awx#6775]
##### ISSUE TYPE
Can the docker-compose files be upgraded to v2 or ideally v3 this will stop the install issue being locked to docker-compose v1.9 
##### SUMMARY

if the layout is updated to these files it will allow for docker-compose to run on the newer version and make installing on the newer Linux distributions easier.

**Comment by ryanpetrello** [comment]
FYI, we're probably unlikely to tackle this in the near future - we're currently in the midst of exploring a move away from Docker and to podman cc @shanemcd

**Comment by Commifreak** [comment]
AWX-team is about to drop awx docker support?!

**Comment by ryanpetrello** [comment]
Hey @Commifreak,

Sorry, I did a poor job communicating here, and didn't mean to alarm anyone - we're currently working on adding support for podman as part of a larger initiative to move to a container-based playbook execution model in AWX; in practice, much of this work is likely to actually end up in `ansible-runner` (which is what awx relies on).  Our goal is for runner to work transparently with podman _or_ docker. 

Something we've _discussed_ as a part of this work is moving awx from docker-compose to podman/podman-compose for "development environment" installs; that's unlikely, however, to be the type of change we'd make in the short term, and isn't a decision we'd make lightly without discussing at length with the community.  In any event, please don't take my comment above as any sort of commitment or communication that we're just "dropping Docker support" (and again, I apologize if it came across that way).

In relation to this ticket, if somebody feels like opening a PR to address the docker-compose version, we'd take a look 👍, we're just unlikely to dive into it at this moment.

**Comment by TimoStramann** [comment]
Any update on the podman integration, @ryanpetrello ? Would be really interesting since more and more enterprises start upgrading to RHEL8 which has certain problems with docker but supports podman otb.

**Comment by ryanpetrello** [comment]
Hey @TimoStramann,

Moving playbook execution in awx to _always_ happen in containers (via Docker/podman or the k8s API, depending on your install platform) is still on our radar, but work hasn't started on it yet.

When this works starts, this is the place we'll be tracking progress:

https://github.com/ansible/awx/issues/7060
