### ISSUE TITLE
docker-compose v3 files

### ISSUE THREAD

**Issue by shaynecm** [ansible/awx#6776]
##### ISSUE TYPE
Can the docker-compose files be upgraded to v2 or ideally v3 this will stop the install issue being locked to docker-compose v1.9 
##### SUMMARY

if the layout is updated to these files it will allow for docker-compose to run on the newer version and make installing on the newer Linux distributions easier.

**Comment by ryanpetrello** [comment]
duplicate of https://github.com/ansible/awx/issues/6775
