### ISSUE TITLE
Add sync functionality to User Source List

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#6777]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add functionality to sync on user list source.  Related to https://github.com/ansible/awx/issues/6573

**Comment by AlexSCorey** [comment]
blocked until https://github.com/ansible/awx/pull/6740 merges

**Comment by dsesami** [comment]
this wasn't updated but is done with the  merge of #6900
