### ISSUE TITLE
Task: Check if Postgres 9.6 is being used

### ISSUE THREAD

**Issue by Yiyito11** [ansible/awx#6778]
##### ISSUE TYPE
 - when running that part of the playbook is getting following error:

```
TASK [kubernetes : Check if Postgres 9.6 is being used] *************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "POD=$(kubectl -n awx  get pods -l=name=postgresql --field-selector status.phase=Running -o jsonpath=\"{.items[0].metadata.name}\")\nkubectl exec -ti $POD -n awx -- bash -c \"psql -U awx -tAc 'select version()'\"\n", "delta": "0:00:00.884688", "end": "2020-04-21 13:09:38.391281", "msg": "non-zero return code", "rc": 1, "start": "2020-04-21 13:09:37.506593", "stderr": "error: error executing jsonpath \"{.items[0].metadata.name}\": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:\n\ttemplate was:\n\t\t{.items[0].metadata.name}\n\tobject given to jsonpath engine was:\n\t\tmap[string]interface {}{\"apiVersion\":\"v1\", \"items\":[]interface {}{}, \"kind\":\"List\", \"metadata\":map[string]interface {}{\"resourceVersion\":\"\", \"selfLink\":\"\"}}\n\n\nerror: expected 'exec (POD | TYPE/NAME) COMMAND [ARG1] [ARG2] ... [ARGN]'.\nPOD or TYPE/NAME and COMMAND are required arguments for the exec command\nSee 'kubectl exec -h' for help and examples", "stderr_lines": ["error: error executing jsonpath \"{.items[0].metadata.name}\": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:", "\ttemplate was:", "\t\t{.items[0].metadata.name}", "\tobject given to jsonpath engine was:", "\t\tmap[string]interface {}{\"apiVersion\":\"v1\", \"items\":[]interface {}{}, \"kind\":\"List\", \"metadata\":map[string]interface {}{\"resourceVersion\":\"\", \"selfLink\":\"\"}}", "", "", "error: expected 'exec (POD | TYPE/NAME) COMMAND [ARG1] [ARG2] ... [ARGN]'.", "POD or TYPE/NAME and COMMAND are required arguments for the exec command", "See 'kubectl exec -h' for help and examples"], "stdout": "", "stdout_lines": []}
```
Anyway I connect directly to container with  `kubectl exec -ti awx-postgresql-postgresql-0 -n awx bash` and I check version manually with : `psql --version` which returned newer version: **_(PostgreSQL) 11.5_**. Is it ok If I comment this task and continue? Is version 11.5 ok for this deploment for AWX?
I gues I should also comment tasks: 

**_name: Upgrade Postgres if necessary_**
**_name: Set env var for pg upgrade_**
**_name: Wait for change to take affect_**
_and some other here related to postgress update...._
and continue from task:

**_Set image names if using custom registry_**

is this correct?

##### SUMMARY
Steps to follow after POSTGRESS installation

**Comment by ryanpetrello** [comment]
@Yiyito11,

We don't generally test AWX on versions other than the version supported at the time we publish, but I wouldn't expect *newer* versions of postgres to cause issues for you (so I'd say, try commenting that task out, but the usual "you break it, you bought it" open source expectations apply here).

The goal of the task you've listed here is to detect 9.6 (older versions of AWX) and perform an upgrade to pg 10.

Whatever version of AWX you're running, you might want to consider upgrading - AWX has been running on postgres10 for some time now.
