### ISSUE TITLE
Configure Tower in Tower SAML field SOCIAL_AUTH_SAML_SECURITY_CONFIG

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#678]
The API will (PR pending) add the field `SOCIAL_AUTH_SAML_SECURITY_CONFIG` to the saml settings endpoint to support the 2-factor SAML feature https://github.com/ansible/awx/issues/48

The UI should expose that dict field in configure tower in tower.

**Comment by cchurch** [comment]
Should we also include `SOCIAL_AUTH_SAML_SP_EXTRA` and `SOCIAL_AUTH_SAML_EXTRA_DATA` to support any advanced and unforeseen uses?

https://python-social-auth.readthedocs.io/en/latest/backends/saml.html#advanced-settings

**Comment by chrismeyersfsu** [comment]
The API code has landed. https://github.com/ansible/awx/pull/721

There are 3 new fields that need exposing in the UI:

```
SOCIAL_AUTH_SAML_SECURITY_CONFIG, SOCIAL_AUTH_SAML_SP_EXTRA, SOCIAL_AUTH_SAML_EXTRA_DATA
```

**Comment by wenottingham** [comment]
@chrismeyersfsu @jakemcdermott can this be closed?

**Comment by wenottingham** [comment]
Yes, this landed.
