### ISSUE TITLE
RFE: Add AWS S3 as a SCM type

### ISSUE THREAD

**Issue by mdinwoodie** [ansible/awx#6789]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
"It would be useful if we could use AWS S3 as an alternative SCM Type. The authentication to AWS could be done either with IAM Role or Access/Secret Keys. Functionality would work like git with a manual refresh process to pull in new code."

**Comment by wenottingham** [comment]
The key feature we rely on from SCMs is the concept of a revision to lock to; using S3 doesn't do this.

**Comment by wenottingham** [comment]
Updated to add: a community contributor contributed https://github.com/ansible/awx/issues/7954 - this may help for your use case.
