### ISSUE TITLE
ERROR! No inventory was parsed, please check your configuration and options.

### ISSUE THREAD

**Issue by surfer190** [ansible/awx#6795]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX cannot use my inventory - it see's the yaml inventory as a python script and errors out.

##### ENVIRONMENT
* AWX version: AWX 11.0.0
* AWX install method: docker on linux
* Ansible version: 2.9.5
* Operating System: CentOS Linux release 7.7.1908
* Web Browser: Firefox 75.0

##### STEPS TO REPRODUCE

1. Create this playbook:

```
---
- hosts: all
  connection: local
  
  vars:
    storage_gb: 50
    storage_mb: "{{ storage_gb * 1024 }}"
  
  tasks:
    - name: Debug storage size mb
      debug:
        msg: 'Ensure this is 51200: {{ storage_mb }}'
```

2. Create an inventory as follows:

`localhost`

with host vars:

```
---
ansible_connection: local
```

3. Create a job template using the playbook and inventory

Launch it

##### EXPECTED RESULTS

I expect the playbook to run:

```
PLAY [all] ************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************
ok: [localhost]

TASK [Debug storage size mb] ******************************************************************************************************
ok: [localhost] => {
    "msg": "Ensure this is 51200: 51200"
}

PLAY RECAP ************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
``` 

##### ACTUAL RESULTS

```
[WARNING]:  * Failed to parse /tmp/awx_43_m6jb7ss6/tmpc8eyn0p8 with script
plugin: Inventory script (/tmp/awx_43_m6jb7ss6/tmpc8eyn0p8) had an execution
error: env: ‘python’: No such file or directory
[WARNING]:  * Failed to parse /tmp/awx_43_m6jb7ss6/tmpc8eyn0p8 with yaml
plugin: Syntax Error while loading YAML.   did not find expected key  The error
appears to be in '/tmp/awx_43_m6jb7ss6/tmpc8eyn0p8': line 3, column 40, but may
be elsewhere in the file depending on the exact syntax problem.  The offending
line appears to be:  # -*- coding: utf-8 -*- print('{"all": {"hosts":
["localhost"]}, "_meta": {"hostvars": {"localhost": {"ansible_connection":
"local", "remote_tower_enabled": "true"}}}}')
^ here We could be wrong, but this one looks like it might be an issue with
unbalanced quotes. If starting a value with a quote, make sure the line ends
with the same set of quotes. For instance this arbitrary example:      foo:
"bad" "wolf"  Could be written as:      foo: '"bad" "wolf"'
[WARNING]:  * Failed to parse /tmp/awx_43_m6jb7ss6/tmpc8eyn0p8 with ini plugin:
host range must be begin:end or begin:end:step
[WARNING]: Unable to parse /tmp/awx_43_m6jb7ss6/tmpc8eyn0p8 as an inventory
source
ERROR! No inventory was parsed, please check your configuration and options.
```

**Comment by surfer190** [comment]
Whoops, this was my mistake. The custom venv I created didn't have the dependenices installed - psutil and ansible.

After I did install ansible with the custom venv I got this error when running a play:

`Traceback (most recent call last): File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 1481, in run res = ansible_runner.interface.run(**params) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/ansible_runner/interface.py", line 178, in run r.run() File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/ansible_runner/runner.py", line 179, in run use_poll=self.config.pexpect_use_poll, File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 204, in __init__ self._spawn(command, args, preexec_fn, dimensions) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 303, in _spawn cwd=self.cwd, **kwargs) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 314, in _spawnpty return ptyprocess.PtyProcess.spawn(args, **kwargs) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/ptyprocess/ptyprocess.py", line 330, in spawn raise exception OSError: [Errno 2] No such file or directory: b'/opt/awx_venvs/provisioning/bin/ansible-playbook' `

**Comment by surfer190** [comment]
I ended up using the kubernetes deployment.

**Comment by dannyvanderaa** [comment]
> Whoops, this was my mistake. The custom venv I created didn't have the dependenices installed - psutil and ansible.
> 
> After I did install ansible with the custom venv I got this error when running a play:
> 
> `Traceback (most recent call last): File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 1481, in run res = ansible_runner.interface.run(**params) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/ansible_runner/interface.py", line 178, in run r.run() File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/ansible_runner/runner.py", line 179, in run use_poll=self.config.pexpect_use_poll, File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 204, in __init__ self._spawn(command, args, preexec_fn, dimensions) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 303, in _spawn cwd=self.cwd, **kwargs) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 314, in _spawnpty return ptyprocess.PtyProcess.spawn(args, **kwargs) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/ptyprocess/ptyprocess.py", line 330, in spawn raise exception OSError: [Errno 2] No such file or directory: b'/opt/awx_venvs/provisioning/bin/ansible-playbook' `

Where you able to solve this issue?
