### ISSUE TITLE
[ui_next] Toggle text 'of', at the pagination options/navigation menu, needs to be marked for translations

### ISSUE THREAD

**Issue by sshedmake** [ansible/awx#6800]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
With Japanese (dummy translation) google-chrome, toggle text 'of', at the Pagination Options menu, appears in English (instead of Japanese)

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: docker on linux
* Ansible version:  2.10.0.dev0
* Operating System: Fedora 31
* Web Browser: google-chrome

##### STEPS TO REPRODUCE
1. Do a successfull login to the ui_next interface in the preferred language (say Japanese)
2. Navigate to ~/templates screen or ~/templates/workflow_job_template 'visualizer' screen
3. Observe the toggle text 'of' at Pagination options/navigation menu 

##### EXPECTED RESULTS
Toggle text 'of' should appear in Japanese

##### ACTUAL RESULTS
Toggle text 'of' appears in English

##### ADDITIONAL INFORMATION
1. Screenshot highlighting toggle text 'of', at the pagination options/navigation menu, appearing in English:

![output_1](https://user-images.githubusercontent.com/12151785/80010283-d4c1bd80-84e7-11ea-9300-27cce370cb35.gif)

2. Affects pagination nav of other forms (within the Resources and Access nav links) too

**Comment by mabashian** [comment]
This string comes from this component: http://patternfly-react.surge.sh/components/pagination in the upstream PF repo.  I will open up an issue with them to see how we should proceed.

**Comment by unlikelyzero** [comment]
From the patternfly sync up. Can be passed as a prop http://patternfly-react.surge.sh/components/pagination/#props

This was only recently added.

**Comment by wenottingham** [comment]
@unlikelyzero @mabashian is this in the version we're currently using, or would we need a rebase for it?

**Comment by mabashian** [comment]
Mmmmm yea i see where we can pass some strings in but I still see this one in their source code:  https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/Pagination/Navigation.tsx#L207

Here's what they let us control:

```
{
  items: '',
  page: '',
  itemsPerPage: 'Items per page',
  perPageSuffix: 'per page',
  toFirstPage: 'Go to first page',
  toPreviousPage: 'Go to previous page',
  toLastPage: 'Go to last page',
  toNextPage: 'Go to next page',
  optionsToggle: 'Items per page',
  currPage: 'Current page',
  paginationTitle: 'Pagination',
}
```

So yea, as far as this one in particular goes I think we're still waiting on a solution from PF.

**Comment by redallen** [comment]
Currently you can pass a custom `toggleTemplate` to Pagination to format the "2 of 4 pages" using props from [ToggleTemplate](https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/Pagination/ToggleTemplate.tsx):
![image](https://user-images.githubusercontent.com/47335686/112039131-1143d200-8b1a-11eb-8d8a-9c836fc6ce5c.png)

The accessible label @mabashian mentioned can't be changed without an `ofWord` convenience prop I've just added for you in that cover both the `ToggleTemplate` and accessible label*: https://github.com/patternfly/patternfly-react/pull/5563

**Comment by unlikelyzero** [comment]
@redallen will this be made available in the next release?

**Comment by redallen** [comment]
It's available in the current prerelease:
```json
"@patternfly/patternfly": "4.96.2",
"@patternfly/react-catalog-view-extension": "4.10.28",
"@patternfly/react-charts": "6.14.11",
"@patternfly/react-code-editor": "4.2.17",
"@patternfly/react-core": "4.106.1",
"@patternfly/react-icons": "4.9.9",
"@patternfly/react-inline-edit-extension": "4.6.64",
"@patternfly/react-styles": "4.9.4",
"@patternfly/react-table": "4.24.0",
"@patternfly/react-tokens": "4.10.9",
"@patternfly/react-topology": "4.8.14",
"@patternfly/react-virtualized-extension": "4.7.0",
```
 and will be in the next release.

**Comment by tiagodread** [comment]
This is fixed for pagination within modals:
![image](https://user-images.githubusercontent.com/12464858/127690593-45cc54f9-bd10-408b-aa8b-4d5504e2ef35.png)
 
But not for the main lists i.e Inventory, Projects, Job templates
![image](https://user-images.githubusercontent.com/12464858/127692675-cd06e25d-8d54-4eaf-9678-b6a6da2b3897.png)

![image](https://user-images.githubusercontent.com/12464858/127697480-6e1baee4-0d07-4b9e-99bb-f174e6c7c2b6.png)
