### ISSUE TITLE
[ui_next] Button text 'Clear all filters', needs to be marked for translations

### ISSUE THREAD

**Issue by sshedmake** [ansible/awx#6801]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
With Japanese (dummy translation) google-chrome, button text 'Clear all filters' at all the forms within the Resources/Access nav link, appears in English (instead of Japanese)

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: docker on linux
* Ansible version:  2.10.0.dev0
* Operating System: Fedora 31
* Web Browser: google-chrome

##### STEPS TO REPRODUCE
1. Do a successfull login to the ui_next interface in the preferred language (say Japanese)
2. Navigate to any nav item within the Resources/Access nav link
3. Input some search text in the input form-control and hit Enter

##### EXPECTED RESULTS
Button text 'Clear all filters' should appear in Japanese

##### ACTUAL RESULTS
Button text 'Clear all filters' appears in English

##### ADDITIONAL INFORMATION
1. Screenshot higlighting 'Clear all filters' appearing in English at ~/templates screen, with Japanese google-chrome:

![testcase 02_step 05_ja_1587522723736_1](https://user-images.githubusercontent.com/12151785/80010799-8e209300-84e8-11ea-963a-1ede4d27a53d.png)

2. Affects input form-control of other nav items within the Resources/Access nav links too

**Comment by tiagodread** [comment]
This bug was addressed in #8510
