### ISSUE TITLE
Skip days in scheduling

### ISSUE THREAD

**Issue by slm0n87** [ansible/awx#6815]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
We have scheduled jobs which run periodically but should **not** run on holidays.
Currently we manually disable this job or change the "start time" to a later day.

Specially in highly automated environments I could imagine that issue affects some users.
Greets
Simon

**Comment by wenottingham** [comment]
This would not be done for 'holidays'; recurrence rules can exclude specific dates, so those would need to be entered in full  Y/M/D for this to be supported.

**Comment by slm0n87** [comment]
Fine for me by excluding days in scheduling.

**Comment by mabashian** [comment]
@keithjgrant this seems like the same thing as: https://github.com/ansible/awx/issues/12542.  If they're duplicates can we close one of them?

**Comment by keithjgrant** [comment]
closing as duplicate of #12542
