### ISSUE TITLE
[10.0.0 through 11.1.0] Line numbers doubled

### ISSUE THREAD

**Issue by Commifreak** [ansible/awx#6816]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

While any job is running, the output shows doubled line numbers

##### ENVIRONMENT
* AWX version: 11.1.0
* AWX install method: docker on linux
* Ansible version:  2.9.5
* Operating System: Ubuntu 18.04 LTS
* Web Browser: Firefox 75

##### STEPS TO REPRODUCE

1. Run a playbook
2. Look at job output console
3. doubled line numbers

##### EXPECTED RESULTS

No doubled line numbers, like before 10.0.0

##### ACTUAL RESULTS

![awx_dbl](https://user-images.githubusercontent.com/87267/80095951-19416d80-8569-11ea-995f-6844cd4dc784.jpg)
![doubled2](https://user-images.githubusercontent.com/87267/80097357-71796f00-856b-11ea-83f2-75fa45bbedb6.jpg)

**Comment by AlanCoding** [comment]
Fixed by @ghjm in https://github.com/ansible/ansible/pull/68520

Upgrade to Ansible 2.9.7 and report if issue persists.
