### ISSUE TITLE
fix per-minute stats on awx-manage run_wsbroadcast --status

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#6817]
`awx-manage run_wsbroadcast --status` events per minute calculate isn't quite correct. Run something that continues to emit events. Let it run a bit and observe it. After about a minute it sort of resets.

**Comment by kdelee** [comment]
Going to call this good, this tool is mostly for developer/support consumption to diagnose whats going on on this system and I'm  slightly wary of asserting on stats that may be fluctuating and prone to influence of other tests in our regression test suite, so do not plan to add a test at this time. Closing
