### ISSUE TITLE
Support Perforce as SCM type

### ISSUE THREAD

**Issue by tchia04** [ansible/awx#682]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Currently Perforce SCM type supported is not supported

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by wenottingham** [comment]
AWX uses ansible  modules to access source control; nothing will be added to AWX that doesn't have existing Ansible modules.

**Comment by tchia04** [comment]
Hi wenottingham, 
Are you saying AWX will not support perforce until there is a perforce source control module listed on this page?
http://docs.ansible.com/ansible/latest/list_of_source_control_modules.html

**Comment by tchia04** [comment]
I have opened an issue from the ansible git repo at https://github.com/ansible/ansible/issues/33106

**Comment by wenottingham** [comment]
That is a necessary but not sufficient prerequisite. To be frank, we're not really that interested in supporting source control systems we can't test or verify against, and this is the first time anyone's ever asked for it.

**Comment by cchurch** [comment]
Someone did ask about it once, and nothing ever came of it: https://groups.google.com/d/topic/ansible-project/_a4Fi32fdso/discussion

**Comment by inequity** [comment]
I am also interested in this, but if necessary will just mirror my ansible code into git.
