### ISSUE TITLE
tower_workflow_job_template is missing the notification_templates_ arguments

### ISSUE THREAD

**Issue by idelsink** [ansible/awx#6828]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
`tower_workflow_template` is missing the `notification_templates_started`, `notification_templates_success` and `notification_templates_error` arguments.
`tower_job_template` does have these arguments.

**Comment by AlanCoding** [comment]
`tower_workflow_template` is deprecated in favor of `tower_workflow_job_template`.

However, that is missing these too, and it they should be added.

**Comment by beeankha** [comment]
Closing this issue, due to PR https://github.com/ansible/awx/pull/6964 getting merged.
