### ISSUE TITLE
Separate installation

### ISSUE THREAD

**Issue by djuwa4** [ansible/awx#6829]
Hello! Our customers decided to complicate our life a little. According to the technical specifications, they want to install AWX Ansible in this form: ansible/awx_task:latest container: latest must be installed in Kubernetes whereas ansible/awx_web:latest, memcached:alpine, rabbitmq:3, postgres:9.6 installed in Docker Compose. All AWX Ansible containers should work as if they were all installed in the same environment.
I want to know if this is real? And if so, what steps do I need to take?

**Comment by shanemcd** [comment]
Hi @djuwa4, nope this is not real.

**Comment by chrismeyersfsu** [comment]
@djuwa4 take a look at the container group feature. https://docs.ansible.com/ansible-tower/latest/html/administration/external_execution_envs.html#container-groups

**Comment by djuwa4** [comment]
Thanks for the answers, special thanks for the link!
