### ISSUE TITLE
tower_workflow_template module is missing the scm_branch and ask_scm_branch_on_launch arguments

### ISSUE THREAD

**Issue by idelsink** [ansible/awx#6830]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The `tower_workflow_template` module is missing the `scm_branch` and `ask_scm_branch_on_launch` arguments. I currently use the CLI to set these variables, but I would rather use the `tower_workflow_template` module.

**Comment by AlanCoding** [comment]
`tower_workflow_template` is deprecated with `tower_workflow_job_template` as its replacement (with a different approach to the workflow schema). The newer module has these options, and we don't want to add new stuff to the deprecated module.
