### ISSUE TITLE
Allow using Network Modules for ad-hoc commands

### ISSUE THREAD

**Issue by orgito** [ansible/awx#684]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Allow using network modules (ios_command, aireos_command, etc) for ad-hoc commands. 

##### ENVIRONMENT
* AWX version: 1.0.1.223
* AWX install method: docker on linux
* Ansible version:  2.4.1
* Operating System: Centos 7.4
* Web Browser: Chrome 62

##### STEPS TO REPRODUCE
- Select a group or host in the inventory that contains network devices. 
- Click RUN COMMAND

##### EXPECTED RESULTS
The user should be able to select the Network Credential and set the connection method to local thus allowing the execution of network modules.

##### ACTUAL RESULTS
It is only possible to select Machine Credentials and there is no option to set the connection type as local, making it impossible to successfully run network modules.

**Comment by wenottingham** [comment]
Not being able to set ansible_connection to 'local' is intentional.... granting access to run ad-hoc commands on a set of inventory machines shouldn't grant access to run them on the AWX/Tower server.

**Comment by orgito** [comment]
So it is not possible to run network modules as ad-hoc commands?

**Comment by wenottingham** [comment]
It is not possible to set 'ansible_connection' on an ad-hoc command. You can always edit the available list of ad-hoc commands to allow for network modules, but it would need to take that into account.

Ad-hoc commands may be updated to take other kinds of credentials in the future... that's an engineering item.
