### ISSUE TITLE
routeros_facts – Collect facts from remote devices running MikroTik RouterOS

### ISSUE THREAD

**Issue by novonet** [ansible/awx#6840]
routeros_facts – getting error 

Hello I'm experience  trouble when run playbook with  routeros_facts –module;

This is my module:
---
- name: Mikrotik test script
  hosts: mikrotik
  connection: network_cli
  gather_facts: no
  tasks:
  
  - name: gather facts
    routeros_facts:
      gather_subset: all

This is the error:

SSH password: 
PLAY [Mikrotik test script] ****************************************************
TASK [gather facts] ************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: None
fatal: [192.168.89.33]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-196200k2awbe/ansible-tmp-1587827109.4403489-144828317700131/AnsiballZ_routeros_facts.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-196200k2awbe/ansible-tmp-1587827109.4403489-144828317700131/AnsiballZ_routeros_facts.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-196200k2awbe/ansible-tmp-1587827109.4403489-144828317700131/AnsiballZ_routeros_facts.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.routeros.routeros_facts', init_globals=None, run_nam…
PLAY RECAP *********************************************************************
192.168.89.33              : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

the awx version is:  AWX 11.0.0

**Comment by wenottingham** [comment]
This looks like an issue with your playbook and/or the module itself. Please file this at https://github.com/ansible/ansible/. 

This repo is for issues in AWX itself.
