### ISSUE TITLE
Possibility to disable new host functionnality

### ISSUE THREAD

**Issue by Tioborto** [ansible/awx#6844]
##### ISSUE TYPE
 - Possibility to disable to add a new host in the inventory
 - Possibility to only add an existing host in inventory groups

##### SUMMARY

I work in a large organization in France. 
We want to automatically manage the servers by product and have a synchronization with our repository. 
To do this, we want to leave the possibility for users to create groups but only add existing hosts and not new ones.
Is it possible to hide the button for adding a new host at the hosts level of an inventory and groups?

**Comment by wenottingham** [comment]
The only way to restrict host creation in the UI/API is to remove the ability to administer the inventory entirely.

The recommendation is to do this mapping somewhere other than in the API - either via `group_by` in the playbooks, or to pull the inventory from a CMDB or cloud source.
