### ISSUE TITLE
Add tower_credential_input_source module to awx_collection

### ISSUE THREAD

**Issue by Tompage1994** [ansible/awx#6845]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
At present there is no way to add credential_input_sources. This functionality is possible via 
```sh 
awx credential_input_sources create
```

At present the only way to achieve this is to use the command module which is undesirable.

**Comment by kdelee** [comment]
Tests were added for this that are passing, going to call this verified. @squidboylan can chime in if he thinks there is anything missing
