### ISSUE TITLE
Redis HA (high availability): Question

### ISSUE THREAD

**Issue by NizarSteria** [ansible/awx#6850]
##### ISSUE TYPE
 - Redis HA (high availability)

##### SUMMARY
We have replaced RabbitMQ by Redis. When we make an architecture Awx HA. It is necessary to make Redis HA or with a single redis we can do this architecture ?

If I understand redis is temporary solution and we plan on replacing this with a postgres message broker https://github.com/ansible/awx/pull/5441.

**Comment by ryanpetrello** [comment]
Hey @NizarSteria,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you have questions about an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
