### ISSUE TITLE
Choose Inventory when creating Ansible Tower Schedules 

### ISSUE THREAD

**Issue by michael-tam** [ansible/awx#6852]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
 When creating a schedule for a Job Template, we are held to use the default inventory for the Job Template.  Therefore, we need to create/maintain multiple job templates in order to schedule a job template to execute against different inventory.

We should be able to have a single job template, can create multiple schedules, but within each schedule we should be able to choose which inventory to run the Job Template against.

**Comment by wenottingham** [comment]
If the template has promptable fields, you should already be able to set those prompts when the schedule is created.

**Comment by michael-tam** [comment]
I did not notice and realize that I had to click the Prompt Button on the schedule but it makes complete sense now.  Thank you!
