### ISSUE TITLE
[ui_next] Survey, SurveyList button 'Preview' and 2 button(s): 'x more' and 'Show Less' under type 'multiple-choice (multi-select)', needs to be marked for translations

### ISSUE THREAD

**Issue by sshedmake** [ansible/awx#6861]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
With Japanese (dummy translation) google-chrome, SurveyList button 'Preview' and 2 button(s): 'x more' and 'Show Less' under type 'multiple-choice (multi-select)', at 'Templates > Survey' screen, appears in English (instead of Japanese)

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: docker on linux
* Ansible version:  2.10.0.dev0
* Operating System: Fedora 31
* Web Browser: google-chrome

##### STEPS TO REPRODUCE
1. Do a successful login to the ui_next interface in the preferred language (say Japanese)
2. Navigate to 'Templates > Survey' screen
3. Observe the text on: 2 buttons under type 'multiple-choice (multi-select)' and SurveyList button 'Preview', respectively

##### EXPECTED RESULTS
Content should appear in Japanese

##### ACTUAL RESULTS
1. Text on button(s): 'x more' | 'Show Less', appear in English

2. Text on buton: 'Preview', appear in English

##### ADDITIONAL INFORMATION
1. Screenshot higlighting, SurveyList button 'Preview' and 2 button(s): 'x more' and 'Show Less' under type 'multiple-choice (multi-select)' / mcms, appearing in English at 'Templates > Survey' screen, with Japanese google-chrome:

![output](https://user-images.githubusercontent.com/12151785/80522992-0a185080-89ab-11ea-83a4-a959f9d53281.gif)

**Comment by AlexSCorey** [comment]
@sshedmake Thanks for bringing this to our attention.  This also is a problem with a patternfly component. I have filed an issue with them.  It can be tracked here https://github.com/patternfly/patternfly-react/issues/4174

**Comment by unlikelyzero** [comment]
@jakemcdermott @nixocio this is ready for test?

**Comment by sshedmake** [comment]
With Japanese dummy (not actual) translations, the said strings, now, looks marked as translatable strings:

![output](https://user-images.githubusercontent.com/12151785/83065557-507fce80-a081-11ea-9f5e-4d3219d4cf0e.gif)

**Comment by unlikelyzero** [comment]
@rooftopcellist and @nixocio we are going to remove the `needs_test` marker until this is available for testing with full translations

**Comment by nixocio** [comment]
@unlikelyzero, I tried to capture [here](https://github.com/ansible/awx/blob/devel/awx/ui_next/CONTRIBUTING.md#marking-an-issue-to-be-translated) the work flow for issues related to internationalization. I wonder when is the proper moment to add `needs_test` as part of this work flow. Suggestions?

**Comment by rooftopcellist** [comment]
It looks as though this is fixed re: [this comment](https://github.com/ansible/awx/issues/6861#issuecomment-634904436).  This should have been covered in the last batch of translated strings.  Please re-open if you are still seeing the issue.
