### ISSUE TITLE
Add Copy Support for Projects and Inventories

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#6863]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
See #4969

**Comment by dsesami** [comment]
Some feedback:
- A copied project in the project list is missing Git revision info in the list (the sequence of characters and numbers that tells you the latest commit). However, copying the copy makes the Git revision appear, but then that second copy is missing the Git revision afterwards. Sorting also seems to fix it, so I guess the Git info is there, it's just not being rendered for some reason initially.

- An auditor is able to view the copy button for random projects with no apparent common aspects. I'm not really sure what makes those different in the copy list. However, clicking it causes an unauthorized error.

![Screenshot_20200515_132422](https://user-images.githubusercontent.com/19942822/82078782-b480bb00-96af-11ea-9a22-90c0c869caa4.png)


- The copying timestamp is off. While it should be `Name @ 1:25:39 PM`, it is `Name @ 1:25: 39 PM`. Note the space after the second colon.

**Comment by AlexSCorey** [comment]
> Some feedback:
> 
> * A copied project in the project list is missing Git revision info in the list (the sequence of characters and numbers that tells you the latest commit). However, copying the copy makes the Git revision appear, but then that second copy is missing the Git revision afterwards. Sorting also seems to fix it, so I guess the Git info is there, it's just not being rendered for some reason initially.

A newly copied Project needs to be syned before the revision will apear

> * An auditor is able to view the copy button for random projects with no apparent common aspects. I'm not really sure what makes those different in the copy list. However, clicking it causes an unauthorized error.

Sys Auditors cannot see the copy button any more based on the ui in devel.

> ![Screenshot_20200515_132422](https://user-images.githubusercontent.com/19942822/82078782-b480bb00-96af-11ea-9a22-90c0c869caa4.png)
> 
> * The copying timestamp is off. While it should be `Name @ 1:25:39 PM`, it is `Name @ 1:25: 39 PM`. Note the space after the second colon.

The time stamp has also been fixed and is working properly in devel.
@dsesami

**Comment by dsesami** [comment]
@AlexSCorey and I are discussing a placeholder for the git commit when a project hasn't been synced yet.

**Comment by dsesami** [comment]
@AlexSCorey I've confirmed that the time stamp spacing issue still exists in devel. I'd like to keep this open until that last fix is put in.

**Comment by AlexSCorey** [comment]
@dsesami I think we have checked all the boxes for this issue.  If you agree, please close it.
