### ISSUE TITLE
Add Copy Support for Inventory Scripts 

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#6864]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
See #4969

**Comment by AlexSCorey** [comment]
Blocked until Inventory Scripts list goes in.

**Comment by unlikelyzero** [comment]
@AlexSCorey @mabashian is this specifically for inventory scripts? Aren't those being removed? Is this supposed to be for copy inventory source?

**Comment by AlexSCorey** [comment]
@unlikelyzero This can actually be closed because Inventory Scripts has been removed from the new UI.
