### ISSUE TITLE
Add Copy Support for Notifications

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#6865]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
See #4969

**Comment by AlexSCorey** [comment]
blocked until Notifications list goes in.

**Comment by unlikelyzero** [comment]
no longer blocked

**Comment by mabashian** [comment]
This exists in devel now:

<img width="1479" alt="Screen Shot 2021-02-03 at 1 03 41 PM" src="https://user-images.githubusercontent.com/9889020/106789443-46ef3300-6620-11eb-9d99-6b9453aa97b5.png">

**Comment by unlikelyzero** [comment]
@akus062381 will be taking this.
I believe that stubs or test coverage should be in /notifications/notification-templates-CRUD.spec.js
1. Execute stubs in this area
2. Add a real test

**Comment by akus062381** [comment]
This is going to be on the notifications-crud.spec.js doc. Should see what other copy resource tests exist and base off those.

**Comment by akus062381** [comment]
Tests exist in notifications-operations.spec.js for the copy function. Should be all set here.
