### ISSUE TITLE
WorkFlowJobTemplate should accept variable as Template.jsx 

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#6869]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Missing variable from `WorkflowJobTemplate`
See:

https://github.com/ansible/awx/blob/def3114b5bc817999d466920a4c82c33f2167608/awx/ui_next/src/screens/Template/WorkflowJobTemplate.jsx#L204

Should accept variable in the Redirect above to be consistent with `Template.jsx`

From `Template.jsx`.

```jsx
          <Redirect
            from="/templates/:templateType/:id"
            to="/templates/:templateType/:id/details"
            exact
          />
```

**Comment by AlexSCorey** [comment]
These 2 files should use the same pattern for the routing path.  Template.jsx  has a `:templateType` param and  WorkflowJobTemplate.jsx just hard codes the template type.  We should be consistent between these 2 files because they are so closely related.

**Comment by AlexSCorey** [comment]
This was filed to help @nixocio with some work he was doing.  We found a different way to do that work.  The work described in this issue should be done at some point, but it doesn't affect performance, or functionality.

**Comment by unlikelyzero** [comment]
@AlexSCorey @nixocio has this been addressed?
