### ISSUE TITLE
[Organisational process] Inventories process in large company

### ISSUE THREAD

**Issue by Tioborto** [ansible/awx#6871]
##### ISSUE TYPE
 - Organisational process

##### SUMMARY

I contact you to get information on the processes to have in a large company.

We have a fleet of many machines (more than 12000) in a reference (Service Now).
We want to create them automatically by product via an admin account in the AWX organizations to which they correspond, while allowing normal users to assign them in inventories as they wish (adding only the machines already created). On the other hand, they should not be able to create new machines themselves.
How can we do this without removing their right to add variables on hosts or the ability to create groups?

Thanks in advance for your help

##### ENVIRONMENT
* AWX version: 9.3.0
* AWX install method: docker on linux

**Comment by wenottingham** [comment]
If you're asking whether you can give them administrator access to edit hosts, and group them, without being able to add new hosts, the answer is "you can't". There is only one 'admin' permission on an inventory.

The answer would be to do `group_by` and add variables at the playbook level.
