### ISSUE TITLE
No prompt is shown for credentials

### ISSUE THREAD

**Issue by aagl** [ansible/awx#688]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI?

##### SUMMARY
After upgrading to the latest image version i am no longer able to enter password for credentials on template run

##### ENVIRONMENT
* AWX version: 1.0.1.223
* AWX install method: openshift, docker on linux
* Ansible version:  2.4.1.0
* Operating System: Fedora 26, Win 10
* Web Browser: Chrome Version 62.0.3202.94 (Official Build) (64-bit)
Firefox 57.0 (64-bit)

##### STEPS TO REPRODUCE
Upgrade image from 1.0.1.157
I am able to reproduce this on both openshift and local docker install

##### EXPECTED RESULTS
Input credential password / passphrase on template run

##### ACTUAL RESULTS
When i select credential to run template with, no prompt is shown to enter user password / credential passphrase, although "Prompt on launch" checkbox is selected

##### ADDITIONAL INFORMATION
Everything is working as expected if i fallback image version to 1.0.1.157 and restore database dump
Browser messages:
Chrome:
```
vendor.d87a41df630ddbb05a83.js:436 TypeError: Cannot read property 'id' of undefined
    at app.c423dc9b4209ee356612.js:403
    at Scope.$digest (vendor.d87a41df630ddbb05a83.js:436)
    at ChildScope.$apply (vendor.d87a41df630ddbb05a83.js:436)
    at HTMLTableCellElement.<anonymous> (vendor.d87a41df630ddbb05a83.js:436)
    at HTMLTableCellElement.dispatch (vendor.d87a41df630ddbb05a83.js:29)
    at HTMLTableCellElement.elemData.handle (vendor.d87a41df630ddbb05a83.js:29)
(anonymous) @ vendor.d87a41df630ddbb05a83.js:436
```

Firefox:
```
ReferenceError
columnNumber: 155752
fileName: "https://awx-url/static/js/app.c423dc9b4209ee356612.js"
lineNumber: 403
message: "event is not defined"
stack: "$rootScope.removeConfigReady</</<@https://awx-url/static/js/app.c423dc9b4209ee356612.js:403:155752\nprocessQueue@https://awx-url/static/js/vendor.d87a41df630ddbb05a83.js:436:133449\nscheduleProcessQueue/<@https://awx-url/static/js/vendor.d87a41df630ddbb05a83.js:436:134342\n$digest@https://awx-url/static/js/vendor.d87a41df630ddbb05a83.js:436:145232\n$apply@https://awx-url/static/js/vendor.d87a41df630ddbb05a83.js:436:148000\ninterval/promise.$$intervalId<@https://awx-url/static/js/vendor.d87a41df630ddbb05a83.js:436:111125\n"
__proto__: Object { stack: "", … }

```

**Comment by apollo13** [comment]
Can we push the priority to high here? it massively limits the usefulness and might give people a bad idea ala saving the passwords in awx itself…

**Comment by hiddenicon** [comment]
I'm seeing the same issue eve on the latest 1.0.2.293 fresh install. No prompt for credentials on template run.

Added: Same issue with 1.0.2.301 as well.

**Comment by surian** [comment]
Same issue on 1.0.2.335.

No prompt to type password/passphrase is shown when "ask on execution" is enabled on a credentials when running a template. There is only a blank pop-up and we can't continue to enter execution parameters as we can't enter the password/passphrase (next or launch button is unusable).

If credentials to use is also asked on execution, we can select the credentials but there is no prompt shown for the password/passphrase and when clicking on "launch", there is an error pop-up showing the message "ssh_password".

Any idea on an ETA for this issue? This prevent to use AWX in production with some use cases.

**Comment by LarsMilland** [comment]
I can confirm the issue on 1.0.2.335. 

With credentials configured as show in the attached images AWX comes out with just an error that it is missing the ssh_password.

![image](https://user-images.githubusercontent.com/10956558/34724243-6e6eccc0-f54d-11e7-8244-6faad1516380.png)

![image](https://user-images.githubusercontent.com/10956558/34724128-0f70fa36-f54d-11e7-808c-f218e2bcc995.png)

![image](https://user-images.githubusercontent.com/10956558/34724140-1841c636-f54d-11e7-8469-f0078bd41478.png)

**Comment by kladiv** [comment]
+1 same bug (i hope high priority)

**Comment by FloThinksPi** [comment]
Also seeing this in 1.0.2.0

**Comment by FloThinksPi** [comment]
Sooo , to help progress here, i analysed the code a bit and found no issues with 

https://github.com/ansible/awx/search?utf8=%E2%9C%93&q=ssh_password_required&type=
![image](https://user-images.githubusercontent.com/5863788/35105376-d36aadcc-fc6b-11e7-8604-9b40092f1557.png)

So i suspect the issue to be related to this:

https://github.com/ansible/awx/blob/cd8a4b46698be41b20ab915c00f19b9ec804e235/awx/ui/client/src/job-submission/job-submission.controller.js#L125-L140

Maybe the `passwords_needed_to_start` variable is missing `ssh_password` ?

EDIT: 

passwords_needed_to_start is defenitly valid as a the REST Response is perfectly fine and contains `ssh_password` and the other values BUT i suspect the variable not getting parsed correctly and thus the code above does not set the `ssh_password_required` variable correctly because this also affects Passphrases and Privilege Escalation Passwords

**Comment by FloThinksPi** [comment]
Related to - #932 ? @AlanCoding

**Comment by FloThinksPi** [comment]
It seems , that his is not related as i merged #973  into 1.0.3.0 and still got no credential popup on lunch.

![image](https://user-images.githubusercontent.com/5863788/35854067-98f885a6-0b2f-11e8-8b1c-6f623331122f.png)

**Comment by FloThinksPi** [comment]
As a workaround one can create a survey and replace the ssh_password value. In the credentials save a random pw. 

![image](https://user-images.githubusercontent.com/5863788/35855298-11dafb2c-0b33-11e8-95b1-45c27a654eca.png)

**Comment by apollo13** [comment]
This seems to be fixed on the devel branch:
![image](https://user-images.githubusercontent.com/81547/38489849-d446fcbc-3be7-11e8-86e2-573d50f44f01.png)

**Comment by FloThinksPi** [comment]
Uh Nice to her that. It would bei interresting to know which Commit or commits fixed that as i am backporting fixes Into a own Version because we cannot Upgrade Major Versions due to Database incompatibillity :) . I went quickly over The Last commits but didnt find a responsible one

**Comment by jaredevantabor** [comment]
This is fixed in devel now.
