### ISSUE TITLE
After Reboot of Linux VM, unable to login to AWX UI with admin user

### ISSUE THREAD

**Issue by parasharsingh8086** [ansible/awx#6882]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY
<! Trying to login to AWX UI as admin user but unable to authenticate. tried changing password of admin user, but still unable to login. Tried creating new Superuser, and tried login, but not able to authenticate 

[root@installer]# docker container list
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS
65c557c0795c        ansible/awx_task:9.2.0       "/tini -- /bin/sh ..."   2 months ago        Up 4 days           8052/tcp
351d03535368        postgres:10                  "docker-entrypoint..."   2 months ago        Up 4 days           5432/tcp
ca93079fba25        memcached:alpine             "docker-entrypoint..."   2 months ago        Up 4 days           11211/tcp
0aa178b007a4        ansible/awx_rabbitmq:3.7.4   "docker-entrypoint..."   2 months ago        Up 4 days           4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 25672/tc
[root@installer]# ansible-playbook -i inventory  install.yml^C
[root@installer]# docker exec -it awx_task bash
bash-4.4# awx-manage

bash-4.4# awx-manage changepassword admin
Changing password for user 'admin'
Password:
Password (again):
Password changed successfully for user 'admin'
bash-4.4# awx-manage changepassword admin
Changing password for user 'admin'
Password:
Password (again):
Password changed successfully for user 'admin'
bash-4.4# awx-manage createsuperuser
Username (leave blank to use 'root'): parashar
Email address: abc@abc.com
Password:
Password (again):
Superuser created successfully.
bash-4.4# exit
[root@installer]#

Upon login showing "Invalid username and/or password. Please try again."
>

##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method: docker on linux
* Ansible version:  2.7.8
* Operating System: RHEL 7.7
* Web Browser: Chrom

**Comment by wenottingham** [comment]
This is likely an issue with your install, probably due to how you configured the database. See #1890 and similar issues.

If you continue to have issues, we suggest starting with the IRC channel and/or the mailing list - https://github.com/ansible/awx/#get-involved
