### ISSUE TITLE
Ansible Tower : Saml attribute mapping with group

### ISSUE THREAD

**Issue by neerajbaraiud016** [ansible/awx#6883]
Hi There,

Need assistance on mapping groups to tower Org.

Below code didn't worked, kindly suggest.

"SOCIAL_AUTH_SAML_TEAM_ATTR": {
"saml_attr": "MyGroup",
"remove": true,
"team_org_map": [
{ "team": "MyTeam-A", "organization": "MyOrgA" }

,
{ "team": "MyTeam-B", "organization": "MyOrgB" }

,
{ "team": "MyTeam-C", "organization": "MyOrgC" }

,
{ "team": "MyTeam-D", "organization": "MyOrgD" }

]
}
}

Looking for below variables values :

 "SOCIAL_AUTH_SAML_ORGANIZATION_ATTR": {}
    "SOCIAL_AUTH_SAML_TEAM_ATTR": {}

**Comment by wenottingham** [comment]
This repository is for tracking bugs and issues in AWX.

If you need help with using/configuring AWX, please try the IRC channel or mailing list.
If you need help with using/configuring Ansible Tower, please contact your Red Hat support representative.
