### ISSUE TITLE
[ui_next] Button 'Create' - to create selectable (custom) Labels and Job Tags, at 'Templates > JT > Edit Details' screen, needs to be marked for translations

### ISSUE THREAD

**Issue by sshedmake** [ansible/awx#6887]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
With Japanese (dummy translation) google-chrome, button 'Create' - to create selectable (custom) Labels and Job Tags, at 'Templates > JT > Edit Details' screen, appears in English (instead of Japanese)

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: docker on linux
* Ansible version:  2.10.0.dev0
* Operating System: Fedora 31
* Web Browser: google-chrome

##### STEPS TO REPRODUCE
1. Do a successful login to the ui_next interface in the preferred language (say Japanese)
2. Navigate to breadcrumb 'Templates > Demo Job Template > Edit Details'
3. While creating few selectable (custom) Labels and Job Tags, observe the text over the button 'Create'

##### EXPECTED RESULTS
Content should appear in Japanese

##### ACTUAL RESULTS
'Create' appears in English

##### ADDITIONAL INFORMATION
1. Screenshot higlighting text over the button 'Create', at 'Templates > JT > Edit Details' screen, appearing in English, with Japanese google-chrome:

![Screenshot from 2020-04-27 19-42-47_11](https://user-images.githubusercontent.com/12151785/80698440-1b22a800-8af8-11ea-95e4-5ea7861ea801.gif)

**Comment by AlexSCorey** [comment]
@sshedmake thank you for bringing this to our attention.  This is an issue with pattern-fly's Select component.  I have filed an issue with them and that can be tracked here https://github.com/patternfly/patternfly-react/issues/4173
