### ISSUE TITLE
Internal Server error after installation

### ISSUE THREAD

**Issue by bdietric5** [ansible/awx#6888]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 11.1.0
* AWX install method: docker on linux, docker for mac
* Ansible version:  2.9.7
* Operating System: Debian 10
* Web Browser: Firefox

##### STEPS TO REPRODUCE
Commands to execute
     apt-get install git
      git clone -b x.y.z https://github.com/ansible/awx.git
      git clone -b 11.1.0  https://github.com/ansible/awx.git
      apt-get install     apt-transport-https     ca-certificates     curl     gnupg-agent     software-properties-common
     curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
      apt-key fingerprint 0EBFCD88
     add-apt-repository    "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"
   apt-get update
   apt-get install docker-ce docker-ce-cli containerd.io
   nano /etc/apt/sources.list and add deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main into it.
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
    sudo apt update
     apt install ansible
     apt-get install python3-pip
     pip3 install docker
     apt -y upgrade
     apt -y install curl dirmngr apt-transport-https lsb-release ca-certificates
     curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
     apt-get install gcc g++ make
     apt -y install nodejs
     sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
     sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 2
    cd awx/installer/
    nano inventory and add dockerhub_version=latest
   curl -s https://api.github.com/repos/docker/compose/releases/latest   | grep browser_download_url   | grep docker-compose-Linux-x86_64   | cut -d '"' -f 4   | wget -qi -
     chmod +x docker-compose-Linux-x86_64
     sudo mv docker-compose-Linux-x86_64 /usr/local/bin/docker-compose
    docker-compose version
   pip3 install docker-compose
     pip3 install ansible
     mkdir /var/lib/pgdocker
     mkdir ~/awx/awxcompose
    ansible-playbook -i inventory install.yml
   docker logs -f awx_task

##### EXPECTED RESULTS
I thought that i will be able to access to the awx web interface with http://localhost:80

##### ACTUAL RESULTS
But i only have a page with internal server error.
While i'm running docker logs -f awx_task i obtain many errors that i don't understand: 
[error.txt](https://github.com/ansible/awx/files/4557683/error.txt)
[test.txt](https://github.com/ansible/awx/files/4557684/test.txt)

Thanks for your help.

**Comment by ryanpetrello** [comment]
Hey @bdietric5,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
