### ISSUE TITLE
SESSION_COOKIE_AGE is ignored, meaning that the AWX web interface times out too often

### ISSUE THREAD

**Issue by macau23** [ansible/awx#6889]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The AWX web interface constantly times out when idle for a short amount of time. This makes it very frustrating to use. The setting to change this does not work.

##### ENVIRONMENT
* AWX version: 11.1.0
* AWX install method: docker on linux using the official ansible installer method
* Ansible version:  ansible-2.9.7-1.el8.noarch
* Operating System: CentOS Linux release 8.1.1911 (Core)
* Web Browser: FF

##### STEPS TO REPRODUCE

The [docs](https://docs.ansible.com/ansible-tower/latest/html/administration/authentication_timeout.html) say I can increase the timeout by setting `SESSION_COOKIE_AGE`

If I do this in AWX;

```
$ cat awx/awx/settings/local_settings.py
SESSION_COOKIE_AGE = 86400
```
and re-run the installer.

##### EXPECTED RESULTS

Longer timeout (1 day).

##### ACTUAL RESULTS

Not a longer timeout.

**Comment by ryanpetrello** [comment]
@macau23,

Could you verify that `/api/v2/settings/authentication/` shows `SESSION_COOKIE_AGE ` value you anticipate?  If not, could you try setting this value in the API instead and seeing if it works?

```
HTTP PATCH /api/v2/settings/authentication/
{
    "SESSION_COOKIE_AGE": ...
}
```

**Comment by macau23** [comment]
@ryanpetrello the API page shows:

    "SESSION_COOKIE_AGE": 1800,

I can patch it to add a "1":

    "SESSION_COOKIE_AGE": 18100,

**Comment by ryanpetrello** [comment]
@macau23,

After you set the value using the API, does it take effect?  If you've done this:

```
$ cat awx/awx/settings/local_settings.py
SESSION_COOKIE_AGE = 86400
```

...and `/api/v2/settings/authentication/` shows `1800` (the default), then your changes likely just aren't taking effect (likely because you haven't restarted services after editing the settings file).

**Comment by macau23** [comment]
> After you set the value using the API, does it take effect?

I didn't actually test this, I only tested if the API saw the change. I will check.

> (likely because you haven't restarted services after editing the settings file).

Doesn't the ansible playbook do this when I re-run it?

**Comment by ryanpetrello** [comment]
> Doesn't the ansible playbook do this when I re-run it?

If you mean the install playbook, I'd expect it to.

What stands out to me is that your API endpoint was reporting `1800`, which doesn't match what you put in `awx/awx/settings/local_settings.py`, so I suspect there's just some slight mistake or misconfig here.  Just updating the API directly is really the most foolproof way of adjusting this value.

**Comment by macau23** [comment]
> Just updating the API directly is really the most foolproof way of adjusting this value.

I should use the web interface to update the value rather than using Ansible? 😲

**Comment by ryanpetrello** [comment]
@macau23 

I suspect there's something wrong the inventory/install path.  I'm trying to determine if the issue is properly *setting* the config value, **or** whether or not AWX is *respecting it*.  Based on your comments, it seems clear that setting it via the API *actually* changes the value, so I'm trying to figure out if you still see the issue if you set it via the API.

**Comment by macau23** [comment]
I am sorry but AWX became too much for me to install, so I am unfortunately no longer using it. I won't be able to test a fix. If you want to close the ticket please do.
