### ISSUE TITLE
local_docker install `awx_sdist_builder` container not removed after a built

### ISSUE THREAD

**Issue by vin-c** [ansible/awx#6894]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
local_docker install `awx_sdist_builder` container not removed after a built

##### ENVIRONMENT
* AWX version: 11.1.0
* AWX install method: docker on linux
* Ansible version:  2.9.7
* Operating System: debian10
* Web Browser: N/A

##### STEPS TO REPRODUCE

launch installer with local build option

##### EXPECTED RESULTS

cleaning of any container needed to build image

##### ACTUAL RESULTS

`awx_sdist_builder` container not removed after a built

##### ADDITIONAL INFORMATION

Is it a bug of a missing cleanup ?

**Comment by shanemcd** [comment]
The local docker install was removed a while back. For the current installation docs please see. https://github.com/ansible/awx/blob/devel/INSTALL.md
