### ISSUE TITLE
Playbook processing error at the stage: TASK [kubernetes : Migrate database]

### ISSUE THREAD

**Issue by djuwa4** [ansible/awx#6896]
##### ISSUE TYPE
Installation error (when processing a playbook)

##### SUMMARY
Playbook launch fails

##### ENVIRONMENT
* AWX version: 11.0.0
* AWX install method: Kuberenetes (kubespray)
* Ansible version:  ansible 2.9.6
* Operating System: CentOs 7
* Postgresql: 9.2.24 (Manual setting)

##### STEPS TO REPRODUCE

I run: ansible-playbook -i inventory install.yml

##### EXPECTED RESULTS

Installed AWX in Kuberenetes

##### ACTUAL RESULTS

Error:
TASK [kubernetes : Migrate database] *******************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "kubectl -n awx exec ans                                                                                                                                                             ible-tower-management --  bash -c \"awx-manage migrate --noinput\"\n", "delta":                                                                                                                                                              "0:00:22.845407", "end": "2020-04-30 17:56:20.748698", "msg": "non-zero return c                                                                                                                                                             ode", "rc": 1, "start": "2020-04-30 17:55:57.903291", "stderr": "Traceback (most                                                                                                                                                              recent call last):\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/                                                                                                                                                             django/db/backends/base/base.py\", line 217, in ensure_connection\n    self.conn                                                                                                                                                             ect()\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/back                                                                                                                                                             ends/base/base.py\", line 195, in connect\n    self.connection = self.get_new_co                                                                                                                                                             nnection(conn_params)\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-package                                                                                                                                                             s/django/db/backends/postgresql/base.py\", line 178, in get_new_connection\n                                                                                                                                                                 connection = Database.connect(**conn_params)\n  File \"/var/lib/awx/venv/awx/lib                                                                                                                                                             /python3.6/site-packages/psycopg2/__init__.py\", line 126, in connect\n    conn                                                                                                                                                              = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.Oper                                                                                                                                                             ationalError: could not translate host name \"kub-master-1\" to address: Name or                                                                                                                                                              service not known\n\n\nThe above exception was the direct cause of the followin                                                                                                                                                             g exception:\n\nTraceback (most recent call last):\n  File \"/usr/bin/awx-manage                                                                                                                                                             \", line 8, in <module>\n    sys.exit(manage())\n  File \"/var/lib/awx/venv/awx/                                                                                                                                                             lib/python3.6/site-packages/awx/__init__.py\", line 152, in manage\n    execute_                                                                                                                                                             from_command_line(sys.argv)\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-p                                                                                                                                                             ackages/django/core/management/__init__.py\", line 381, in execute_from_command_                                                                                                                                                             line\n    utility.execute()\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-p                                                                                                                                                             ackages/django/core/management/__init__.py\", line 375, in execute\n    self.fet                                                                                                                                                             ch_command(subcommand).run_from_argv(self.argv)\n  File \"/var/lib/awx/venv/awx/                                                                                                                                                             lib/python3.6/site-packages/django/core/management/base.py\", line 323, in run_f                                                                                                                                                             rom_argv\n    self.execute(*args, **cmd_options)\n  File \"/var/lib/awx/venv/awx                                                                                                                                                             /lib/python3.6/site-packages/django/core/management/base.py\", line 364, in exec                                                                                                                                                             ute\n    output = self.handle(*args, **options)\n  File \"/var/lib/awx/venv/awx/                                                                                                                                                             lib/python3.6/site-packages/django/core/management/base.py\", line 83, in wrappe                                                                                                                                                             d\n    res = handle_func(*args, **kwargs)\n  File \"/var/lib/awx/venv/awx/lib/py                                                                                                                                                             thon3.6/site-packages/django/core/management/commands/migrate.py\", line 87, in                                                                                                                                                              handle\n    executor = MigrationExecutor(connection, self.migration_progress_cal                                                                                                                                                             lback)\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/mig                                                                                                                                                             rations/executor.py\", line 18, in __init__\n    self.loader = MigrationLoader(s                                                                                                                                                             elf.connection)\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/djan                                                                                                                                                             go/db/migrations/loader.py\", line 49, in __init__\n    self.build_graph()\n  Fi                                                                                                                                                             le \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/migrations/load                                                                                                                                                             er.py\", line 212, in build_graph\n    self.applied_migrations = recorder.applie                                                                                                                                                             d_migrations()\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/djang                                                                                                                                                             o/db/migrations/recorder.py\", line 73, in applied_migrations\n    if self.has_t                                                                                                                                                             able():\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/mi                                                                                                                                                             grations/recorder.py\", line 56, in has_table\n    return self.Migration._meta.d                                                                                                                                                             b_table in self.connection.introspection.table_names(self.connection.cursor())\n                                                                                                                                                               File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/ba                                                                                                                                                             se/base.py\", line 256, in cursor\n    return self._cursor()\n  File \"/var/lib/                                                                                                                                                             awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py\", line                                                                                                                                                              233, in _cursor\n    self.ensure_connection()\n  File \"/var/lib/awx/venv/awx/l                                                                                                                                                             ib/python3.6/site-packages/django/db/backends/base/base.py\", line 217, in ensur                                                                                                                                                             e_connection\n    self.connect()\n  File \"/var/lib/awx/venv/awx/lib/python3.6/s                                                                                                                                                             ite-packages/django/db/utils.py\", line 89, in __exit__\n    raise dj_exc_value.                                                                                                                                                             with_traceback(traceback) from exc_value\n  File \"/var/lib/awx/venv/awx/lib/pyt                                                                                                                                                             hon3.6/site-packages/django/db/backends/base/base.py\", line 217, in ensure_conn                                                                                                                                                             ection\n    self.connect()\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-pa                                                                                                                                                             ckages/django/db/backends/base/base.py\", line 195, in connect\n    self.connect                                                                                                                                                             ion = self.get_new_connection(conn_params)\n  File \"/var/lib/awx/venv/awx/lib/p                                                                                                                                                             ython3.6/site-packages/django/db/backends/postgresql/base.py\", line 178, in get                                                                                                                                                             _new_connection\n    connection = Database.connect(**conn_params)\n  File \"/var                                                                                                                                                             /lib/awx/venv/awx/lib/python3.6/site-packages/psycopg2/__init__.py\", line 126,                                                                                                                                                              in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kw                                                                                                                                                             async)\ndjango.db.utils.OperationalError: could not translate host name \"kub-ma                                                                                                                                                             ster-1\" to address: Name or service not known\n\ncommand terminated with exit c                                                                                                                                                             ode 1", "stderr_lines": ["Traceback (most recent call last):", "  File \"/var/li                                                                                                                                                             b/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py\", li                                                                                                                                                             ne 217, in ensure_connection", "    self.connect()", "  File \"/var/lib/awx/venv                                                                                                                                                             /awx/lib/python3.6/site-packages/django/db/backends/base/base.py\", line 195, in                                                                                                                                                              connect", "    self.connection = self.get_new_connection(conn_params)", "  File                                                                                                                                                              \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/postgres                                                                                                                                                             ql/base.py\", line 178, in get_new_connection", "    connection = Database.conne                                                                                                                                                             ct(**conn_params)", "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/                                                                                                                                                             psycopg2/__init__.py\", line 126, in connect", "    conn = _connect(dsn, connect                                                                                                                                                             ion_factory=connection_factory, **kwasync)", "psycopg2.OperationalError: could n                                                                                                                                                             ot translate host name \"kub-master-1\" to address: Name or service not known",                                                                                                                                                              "", "", "The above exception was the direct cause of the following exception:",                                                                                                                                                              "", "Traceback (most recent call last):", "  File \"/usr/bin/awx-manage\", line                                                                                                                                                              8, in <module>", "    sys.exit(manage())", "  File \"/var/lib/awx/venv/awx/lib/p                                                                                                                                                             ython3.6/site-packages/awx/__init__.py\", line 152, in manage", "    execute_fro                                                                                                                                                             m_command_line(sys.argv)", "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-pa                                                                                                                                                             ckages/django/core/management/__init__.py\", line 381, in execute_from_command_l                                                                                                                                                             ine", "    utility.execute()", "  File \"/var/lib/awx/venv/awx/lib/python3.6/sit                                                                                                                                                             e-packages/django/core/management/__init__.py\", line 375, in execute", "    sel                                                                                                                                                             f.fetch_command(subcommand).run_from_argv(self.argv)", "  File \"/var/lib/awx/ve                                                                                                                                                             nv/awx/lib/python3.6/site-packages/django/core/management/base.py\", line 323, i                                                                                                                                                             n run_from_argv", "    self.execute(*args, **cmd_options)", "  File \"/var/lib/a                                                                                                                                                             wx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py\", line 3                                                                                                                                                             64, in execute", "    output = self.handle(*args, **options)", "  File \"/var/li                                                                                                                                                             b/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py\", lin                                                                                                                                                             e 83, in wrapped", "    res = handle_func(*args, **kwargs)", "  File \"/var/lib/                                                                                                                                                             awx/venv/awx/lib/python3.6/site-packages/django/core/management/commands/migrate                                                                                                                                                             .py\", line 87, in handle", "    executor = MigrationExecutor(connection, self.m                                                                                                                                                             igration_progress_callback)", "  File \"/var/lib/awx/venv/awx/lib/python3.6/site                                                                                                                                                             -packages/django/db/migrations/executor.py\", line 18, in __init__", "    self.l                                                                                                                                                             oader = MigrationLoader(self.connection)", "  File \"/var/lib/awx/venv/awx/lib/p                                                                                                                                                             ython3.6/site-packages/django/db/migrations/loader.py\", line 49, in __init__",                                                                                                                                                              "    self.build_graph()", "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-pac                                                                                                                                                             kages/django/db/migrations/loader.py\", line 212, in build_graph", "    self.app                                                                                                                                                             lied_migrations = recorder.applied_migrations()", "  File \"/var/lib/awx/venv/aw                                                                                                                                                             x/lib/python3.6/site-packages/django/db/migrations/recorder.py\", line 73, in ap                                                                                                                                                             plied_migrations", "    if self.has_table():", "  File \"/var/lib/awx/venv/awx/l                                                                                                                                                             ib/python3.6/site-packages/django/db/migrations/recorder.py\", line 56, in has_t                                                                                                                                                             able", "    return self.Migration._meta.db_table in self.connection.introspectio                                                                                                                                                             n.table_names(self.connection.cursor())", "  File \"/var/lib/awx/venv/awx/lib/py                                                                                                                                                             thon3.6/site-packages/django/db/backends/base/base.py\", line 256, in cursor", "                                                                                                                                                                 return self._cursor()", "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-p                                                                                                                                                             ackages/django/db/backends/base/base.py\", line 233, in _cursor", "    self.ensu                                                                                                                                                             re_connection()", "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/dj                                                                                                                                                             ango/db/backends/base/base.py\", line 217, in ensure_connection", "    self.conn                                                                                                                                                             ect()", "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/ut                                                                                                                                                             ils.py\", line 89, in __exit__", "    raise dj_exc_value.with_traceback(tracebac                                                                                                                                                             k) from exc_value", "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/                                                                                                                                                             django/db/backends/base/base.py\", line 217, in ensure_connection", "    self.co                                                                                                                                                             nnect()", "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/                                                                                                                                                             backends/base/base.py\", line 195, in connect", "    self.connection = self.get_                                                                                                                                                             new_connection(conn_params)", "  File \"/var/lib/awx/venv/awx/lib/python3.6/site                                                                                                                                                             -packages/django/db/backends/postgresql/base.py\", line 178, in get_new_connecti                                                                                                                                                             on", "    connection = Database.connect(**conn_params)", "  File \"/var/lib/awx/                                                                                                                                                             venv/awx/lib/python3.6/site-packages/psycopg2/__init__.py\", line 126, in connec                                                                                                                                                             t", "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)"                                                                                                                                                             , "django.db.utils.OperationalError: could not translate host name \"kub-master-                                                                                                                                                             1\" to address: Name or service not known", "", "command terminated with exit co                                                                                                                                                             de 1"], "stdout": "", "stdout_lines": []}

**Comment by ryanpetrello** [comment]
Looks like the database isn't available:

`django.db.utils.OperationalError: could not translate host name "kub-master- 1" to address: Name or service not known"`

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
