### ISSUE TITLE
Support all source types in inventory source forms

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#6899]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
#6576 and #6575 will add support for "Sourced from a Project"

Source Subforms
- [x] Sourced from a Project
- [x] Amazon EC2
- [x] Google Compute Engine
- [x] Microsoft Azure Resource Manager
- [x] VMware vCenter
- [x] Red Hat Satellite 6
- [x] Red Hat CloudForms
- [x] OpenStack
- [x] Red Hat Virtualization
- [x] Ansible Tower
- [x] Custom Script

**Comment by dsesami** [comment]
completed with the merge of #7287
