### ISSUE TITLE
Feature: Settings menu reorganization

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#69]
AWX Feature Spec - Settings menu re-org
=======================================

User Persona
------------
Administrator
Org admin
Automation user

Usage Cases
-----------

We have a bit of a conceptual and place mishmash between:
* top-row menu items
* assorted cards under settings
* the actual 'Configure AWX' card and its tabs

The goal is to audit and rearrange to properly sort out:
* items for normal usage by automation users
* items for org admin+ users to configure as "things in AWX for others to use"
* items for system admin to configure re: "the operation of AWX itself"

Current items and locations:
* Projects (top bar)
* Inventories (top bar)
* Templates (top bar)
* Jobs (top bar)
* User link (top bar)
* Settings (top bar)
* Portal mode (top bar)
* Help/Manual (top bar)
* Logout (top bar)
* Orgs (settings)
* Users (settings)
* Teams (settings)
* Credentials (settings)
* Management jobs (settings)
* Inventory scripts (settings)
* Notifications (settings)
* View License (settings)
* Instance Groups (settings)
* Configure AWX (settings)
* Auth (Configure AWX, with dropdown tabs)
* Random Job Stuff (Configure AWX)
* System Misc (Configure AWX, under tab)
* Logging (Configure AWX, under tab)
* Activity Stream (Configure AWX, under tab)
* Random UI Settings (Configure AWX)
* About AWX (settings)

API Considerations
------------------
Little to none

UI/UX Considerations
--------------------
Yes!

Docs
----

QA Suggestions
--------------

Notes
-----

Updates/Changelog
2017-09-08: intiial/updated version

**Comment by wenottingham** [comment]
example mockups: https://tower-mockups.testing.ansible.com/mockups/settings/
https://tower-mockups.testing.ansible.com/mockups/settings/settings-auth/

**Comment by mabashian** [comment]
link https://github.com/ansible/awx/pull/2069

**Comment by mabashian** [comment]
Including some screenshots of what #2069 looks like:

<img width="1286" alt="screen shot 2018-09-18 at 10 18 08 am" src="https://user-images.githubusercontent.com/9889020/45693971-45df0900-bb2c-11e8-99f1-37b154e1b7c4.png">
<img width="1300" alt="screen shot 2018-09-18 at 10 18 02 am" src="https://user-images.githubusercontent.com/9889020/45693972-45df0900-bb2c-11e8-9d8b-af9e69eaa616.png">
<img width="1301" alt="screen shot 2018-09-18 at 10 17 55 am" src="https://user-images.githubusercontent.com/9889020/45693973-45df0900-bb2c-11e8-9b5e-671313108fd3.png">
<img width="1314" alt="screen shot 2018-09-18 at 10 17 46 am" src="https://user-images.githubusercontent.com/9889020/45693974-45df0900-bb2c-11e8-86c7-43604736203c.png">
<img width="405" alt="screen shot 2018-09-18 at 10 17 39 am" src="https://user-images.githubusercontent.com/9889020/45693975-46779f80-bb2c-11e8-8cc0-d1fcebd71189.png">
<img width="1270" alt="screen shot 2018-09-18 at 10 17 34 am" src="https://user-images.githubusercontent.com/9889020/45693976-46779f80-bb2c-11e8-9f3d-cb299909fcaf.png">

**Comment by mabashian** [comment]
The work left to do here is to test and merge the `uiToMergeDevel` branch into devel

**Comment by mabashian** [comment]
Note that the original issue includes work that was completed when the side-nav was added.  For clarity: this issue specifically tracks changes to the settings page(s) starting [here](https://tower-mockups.testing.ansible.com/mockups/settings/settings/).  You'll note in the mockups that individual settings forms look like:

<img width="1374" alt="screen shot 2018-09-18 at 10 40 22 am" src="https://user-images.githubusercontent.com/9889020/45695396-50e76880-bb2f-11e8-9a47-be9fd9b7e454.png">

^^ These changes are not included in this PR and are not part of the acceptance criteria to merge this.  The primary change to these forms was to move away from dropdown subnav's to simple tab navigation like so:

<img width="1239" alt="screen shot 2018-09-18 at 10 42 18 am" src="https://user-images.githubusercontent.com/9889020/45695520-986df480-bb2f-11e8-852c-cb9a8add9e6b.png">

**Comment by jlmitch5** [comment]
Just a note on the settings reorg.  The extra pane with the settings items has issues displaying when the browser height is smaller than the side nav needs and it has to scroll.  We looked for CSS-only ways of getting this fixed, but unfortunately, we couldn't find one that worked great.  Might need to revisit how we do the position or bring in JS to help somehow.

**Comment by jlmitch5** [comment]
While most of this work is complete and currently resides in the uiToMergeDevel branch, follow-up enhancements and the necessary qe and documentation work needed to complete the feature is being tracked in https://github.com/ansible/awx/projects/9

after all those tasks are marked as done, this card can be verified and closed.

**Comment by jlmitch5** [comment]
merged into awx https://github.com/ansible/awx/pull/2383
