### ISSUE TITLE
Inventory Source List Sync All Button

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#6903]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add a button to the toolbar of the Inventory Source List that is a SyncAll button. It should be a secondary PF button after the Delete Button in the toolbar.  RBAC it should come from and OPTIONS request to /inventories/id/inventory_sources and check if the user can POST.

**Comment by dsesami** [comment]
This one is strange because I might have to go back to it after websockets merge. but the appropriate API calls seem to work. approving the relevant PR.

**Comment by dsesami** [comment]
Linked this issue to be retested when inventory source list websockets are active. For now, the requirements have been fulfilled, so closing it out.
