### ISSUE TITLE
11.2.0 vmware_vm_inventory source variables not passing through

### ISSUE THREAD

**Issue by MrBones757** [ansible/awx#6906]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Following the upgrade to 11.2.0, the vm_vm_inventory plugin does not seem to be accepting source variables from the UI. Customisation to settings are not reflected in the inventory output.

##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: kubernetes
* Ansible version:  2.9.7
* Operating System: 
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create a vmware inventory source with the following settings:

compose:
  ansible_host: guest.hostName
  ansible_ssh_host: guest.hostName

run inventory refresh. 

##### EXPECTED RESULTS

ansible_host and ansible_ssh_host should use the hostname of the device rather than ip and tags should be present.

##### ACTUAL RESULTS

ansible_host and ansible_ssh_host still contain IP address.

##### ADDITIONAL INFORMATION

Have tried other parameters too.

the hostname field doesnt appear to work
the with_tags field also doesnt do anything that i can see
no errors outputted when debug level enabled.

vmmware_vm_inventory.yml file in /tmp at runtime looks like this (missing custom values):

compose:
  ansible_host: guest.ipAddress
  ansible_ssh_host: guest.ipAddress
  ansible_uuid: 99999999 | random | to_uuid
  availablefield: availableField
  configissue: configIssue
  configstatus: configStatus
  customvalue: customValue
  effectiverole: effectiveRole
  guestheartbeatstatus: guestHeartbeatStatus
  layoutex: layoutEx
  overallstatus: overallStatus
  parentvapp: parentVApp
  recenttask: recentTask
  resourcepool: resourcePool
  rootsnapshot: rootSnapshot
  triggeredalarmstate: triggeredAlarmState
filters:
- runtime.powerState == "poweredOn"
keyed_groups:
- key: guest.guestId
  prefix: ''
  separator: ''
- key: '"templates" if config.template else "guests"'
  prefix: ''
  separator: ''
plugin: community.vmware.vmware_vm_inventory
properties:
- availableField
- configIssue
- configStatus
- customValue
- datastore
- effectiveRole
- guestHeartbeatStatus
- layout
- layoutEx
- name
- network
- overallStatus
- parentVApp
- permission
- recentTask
- resourcePool
- rootSnapshot
- snapshot
- tag
- triggeredAlarmState
- value
- capability
- config
- guest
- runtime
- storage
- summary
strict: false
with_nested_properties: true

**Comment by AlanCoding** [comment]
The documentation for this is correct

https://github.com/ansible/awx/blob/d688f7b833bd963b8ecbb01bd6f3c9d8347ee0ab/awx/ui/client/src/inventories-hosts/inventories/related/sources/sources.form.js#L241-L244

It's not expecting the script, not the plugin options. Within the [ini](https://github.com/ansible-collections/vmware/blob/master/scripts/inventory/vmware_inventory.ini) these type of options are `alias_pattern` and `host_pattern`.

That is https://github.com/ansible/awx/issues/4306 / https://github.com/ansible/awx/issues/5150

**Comment by MrBones757** [comment]
Thanks for the reply.
Just to confirm, awx has moved to using the new vmware_vm_inventory plugin from the VMware collection as of awx 11.2.0 but we are still maintaining the use of the old variables from the script rather than the plugin?

This seems alittle odd given the plugin has completely different options to the script - iassume you have an interpretation layer to convert between the two formats ( I'm not that familiar with this part of the codebase)?
I won't be able to verify this untill Monday my time most likely .
