### ISSUE TITLE
Crendential: ssh private key don't work

### ISSUE THREAD

**Issue by yangliang003** [ansible/awx#691]
##### ISSUE TYPE

 - Bug Report
 - Document

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

I use the ssh public key authentication, it works well when I run the task with ansible.And when I set an wrong private key in awx,it works well too. So what does the ssh private key used for?
##### ENVIRONMENT
* AWX version: 1.0.1
* AWX install method: docker on linux
* Ansible version:  2.4.0.0
* Operating System:centos 7
* Web Browser:
chrome
##### STEPS TO REPRODUCE
1、Make the ansible to run successfuly with the ssh public key authentication;
2、Set a wrong ssh private key in the awx,the template run well too;

##### EXPECTED RESULTS
Two questions:
1、I generate the ssh private key in the ansible master node(same as the awx task node),it that right?
2、It seems that the ssh private key effecs nothing?

**Comment by matburt** [comment]
Sounds like you may have the private key loaded in awx? The private key is used during the connection as is normally required by ssh-agent.

It seems like this is better targeted at a mailing list post or irc question.
