### ISSUE TITLE
Inventory files cannot be synced from projects based on non-default git branches

### ISSUE THREAD

**Issue by Throckmortra** [ansible/awx#6923]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When creating an inventory from a project that is based on a non-default git branch, inventory fails to sync because it only checks out the default branch regardless of the setting in the project

##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.7
* Operating System: Centos8
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Create a new project with the non-default git branch specified that contains your inventory file
2. create an inventory based on this project. Use drop-down to specify the inventory file (the file does show up in the drop down)
3. Attempt to sync inventory

##### EXPECTED RESULTS
Inventory syncs successfully 

##### ACTUAL RESULTS
```
1.649 INFO     Updating inventory 11: K8S
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1139, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1026, in handle
    source = self.get_source_absolute_path(self.source)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 326, in get_source_absolute_path
    raise IOError('Source does not exist: %s' % source)
OSError: Source does not exist: /tmp/awx_260_do3od8vj/project/inventory/k8s/hosts
```

**Comment by fosterseth** [comment]
I was not able to reproduce this bug on 11.2.0

do you have any more information that might help us recreate this issue?

I pulled from https://github.com/fosterseth/playbooks.git `bark` branch (inventory.ini is the inventory source file) if you want test it on that

**Comment by Throckmortra** [comment]
@fosterseth in my case, the hosts file i'm attempting to use does not exist in the default (master) 

might be related to this https://github.com/ansible/awx/issues/5692

**Comment by fosterseth** [comment]
@Throckmortra 

That issue is slightly different. You can specify a branch on the job template. In that case, it should launch a project update with that branch (overriding whatever is listed under "branch" on that project). However, their issue is that the inventory source will still be pulled from whatever branch was listed on the project.

From what you described, you aren't seeing this error after launching a job template. You are manually launching the inventory sync right?

**Comment by Throckmortra** [comment]
correct, i can't launch a job template targeting these hosts since the inventory is never synced

I am trying to manually sync. I have created a separate project that specifically looks at this branch containing the host file i want.

**Comment by fosterseth** [comment]
sometimes the inventory source file will show a file that doesn't exist in that project and branch -- which gives the error you posted

e.g.

inv1 source file selected
change filename from inv1 to inv2 in git branch and run project update
go back to inventory source and click drop down menu. It will show inv2, but also inv1 (even though inv1 no longer exists in this project branch)

if you click inv1 and try running inventory update, it will fail with the `Source does not exist`

Try running a project update (with clean and delete on update enabled just this once)
create a new inventory and inventory source -- that way only valid files will show in the inventory pull down menu

**Comment by Throckmortra** [comment]
@fosterseth sorry, turns out my SCM credential was broken and scm syncs were silently failing (despite showing green in the UI) 

I'll close this. Thanks for your help
