### ISSUE TITLE
Figure out resource profiling in Ansible 2.10 and higher

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#6925]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The instructions here:

https://github.com/ansible/awx/blob/devel/docs/performance_data.md

Will break with Ansible 2.10, because it relies on a callback plugin that is moved out of ansible-base.

##### STEPS TO REPRODUCE

follow instructions

##### EXPECTED RESULTS

works

##### ACTUAL RESULTS

does not work

> The data is stored under /var/log/tower/playbook_profiling. A new folder is created for each job run. The folder's name is set to the job's ID.

Basically, that folder doesn't get populated, and playbooks show that something went wrong. Needs investigation.

##### ADDITIONAL INFORMATION

Settings are applied in AWX, passed to ansible-runner

https://github.com/ansible/awx/blob/d688f7b833bd963b8ecbb01bd6f3c9d8347ee0ab/awx/main/tasks.py#L1013-L1018

Then Ansible runner enables the plugin, assuming that it is _available_ in the default search paths.

https://github.com/ansible/ansible-runner/blob/f73705bf9b09424c9e5353d7f5119147e844eaa5/ansible_runner/runner_config.py#L210

However, since that plugin moved to ~`community.general`~ `ansible.posix`, a step is missing. Actually 2 or 3 steps...

 - the community.general collection needs to be installed
 - (sometimes implied) that collection needs to be in the collection search paths
 - the plugin needs to be enabled with the fully qualified name

These will require fixes to `ansible-runner`, but the contract of how the collection gets installed needs to be solved in a inter-repo sense. Or maybe that gets left to the user. Or maybe the plugin gets moved to another collection...

Ping @jladdjr @sivel

**Comment by sivel** [comment]
I believe runner makes use of `cgroup_perf_recap` which lives in [`ansible.posix`](https://github.com/ansible-collections/ansible.posix)

**Comment by jladdjr** [comment]
> However, since that plugin moved to community.general

echoing sivel, the routing info shows ansible.posix:
https://github.com/jladdjr/ansible/blob/devel/lib/ansible/config/routing.yml#L8255-L8256

**Comment by jladdjr** [comment]
compared the cgroup_perf_recap plugin in ansible-stable-2.9 to the version in ansible.posix:
https://gist.github.com/jladdjr/b96fb91d16922c2aeb4a0832dadc0cf6#file-cgroup_perf_recap_changes-L25

I haven't had a chance to test this theory out, but it looks like those changes would have the effect of turning off the writing of profiling data by default, whereas I'm guessing that it was turned on by default before.

**Comment by sivel** [comment]
I don't explicitly remember the change, but it was done in https://github.com/ansible/ansible/pull/64988

**Comment by AlanCoding** [comment]
Sorry, gave the wrong collection, got confused by seeing the [memory](https://github.com/ansible-collections/community.general/blob/master/plugins/callback/cgroup_memory_recap.py) module in community. That's not relevant, it's the performance callback which is used, per the `ansible-runner` line I linked.

**Comment by wenottingham** [comment]
https://github.com/ansible/awx/issues/5283 is probably the larger problem anyway.

**Comment by AlanCoding** [comment]
closing this to consolidate. #5283 is the issue for this
