### ISSUE TITLE
organization definition for job_template

### ISSUE THREAD

**Issue by europ** [ansible/awx#6929]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
I want to request an **organization definition for each job_template** as it is available in inventory and project.

Tower 3.5.1 does not support the use case *"move a specific job_template to a different organization"* as it is supported for inventory and project in UI as well as via CLI. However, it can be done indirectly through inventory and project. It sounds strange but it surprisingly works as a workaround.

**Comment by AlanCoding** [comment]
job_template organization is derived from its project.

**Comment by wenottingham** [comment]
Closing. If you use a current version of AWX, you will note an organization field on the job template itself (as noted, derived from the project.)
