### ISSUE TITLE
Username field is limited to 30 characters

### ISSUE THREAD

**Issue by jainnikhil30** [ansible/awx#693]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

Currently username field is limited to max 30 characters. Its possible to have username >30 chars, especially in case where email id is used as the username. It should be either increased or at least  be configurable to change the max size.

##### ENVIRONMENT
* AWX version: 1.0

**Comment by wenottingham** [comment]
should be fixed by https://github.com/ansible/awx/issues/84
