### ISSUE TITLE
ansible requirements.yml download from private gitlab repo

### ISSUE THREAD

**Issue by fvahid** [ansible/awx#6933]
##### ISSUE TYPE
 - use credential to access private gitlab repo

##### SUMMARY
We need download galaxy-install download from private repository , I can't find any solution to resolve this issue but I found out add ssh private key to docker file 
we use git:// url in requirement and we don't use https:// so need key file auth 
so please add this feature , can access git:// repo in requiement by adding ssh credential section

**Comment by wenottingham** [comment]
This works if the requirements repos use the same keys as the project repo itself.

Outside of that, even if it was supported, there would be issues when the requirements repo accepts the key but with different access permissions.

We suggest standardizing on a shared deploy key.

**Comment by fvahid** [comment]
@wenottingham project key and requiremnet repo key is same but still I have problem

**Comment by wenottingham** [comment]
What do you mean by "add ssh private key to docker file"? That's not how this is done; you need the key to be the SCM credential used for the project.

**Comment by fvahid** [comment]
@wenottingham thank you for reply, I mean we can create ssh private key inside /root/.ssh/id_rsa inside awx_task container ,, so it's no good idea to do that . so I added key into SCM credential section but my problem not resolve. as you know for pull and clone project git repo I used SCM git credential type and use ssh private key because for clone project I use git://reponame url , but for clone repository inside inventory I used https://gilab repository and I need use user and password there

**Comment by fvahid** [comment]
Here is error when ansible awx can't download requrirements.yml 
Traceback (most recent call last): File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/tasks.py", line 1227, in run self.pre_run_hook(self.instance, private_data_dir) File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/tasks.py", line 1797, in pre_run_hook sync_task.run(local_project_sync.id) File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/tasks.py", line 683, in _wrapped return f(self, *args, **kwargs) File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/tasks.py", line 1392, in run raise AwxTaskError.TaskError(self.instance, rc) Exception: project_update 730 (failed) encountered an error (rc=2), please see task stdout for details.

**Comment by wenottingham** [comment]
> I used SCM git credential type and use ssh private key because for clone project I use git://reponame url , but for clone repository inside inventory I used https://gilab repository and I need use user and password there

You can't do this. It needs to be ssh for both, using the same key.
