### ISSUE TITLE
Allow for docker logging drivers

### ISSUE THREAD

**Issue by neb14** [ansible/awx#6941]
##### ISSUE TYPE
 - Currently the local install using docker compose always defaults to jsonlog.  This will allow for other docker logging drivers to be utilized

##### SUMMARY
I created https://github.com/ansible/awx/pull/6938 to allow for this functionality.

**Comment by TheRealHaoLiu** [comment]
closing, PR https://github.com/ansible/awx/pull/6938 merged

**Comment by shanemcd** [comment]
The local docker install was removed a while back. For the current installation docs please see. https://github.com/ansible/awx/blob/devel/INSTALL.md
