### ISSUE TITLE
Progress bar for task

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#6944]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
It would be great if AWX could show some kind of progress bar for how many tasks out of expected tasks were executed. This may not be easy to implement as many ansible playbooks don't have predetermined set of tasks, but they vary based on some variables, but still would be cool.

Example:
You run some task on 20 servers, AWX calculates this task will have 500 individual steps and show progress bar of how many is done

**Comment by TheRealHaoLiu** [comment]
Due to the dynamic nature of ansible-playbook it will be difficult to determine the progress of the task
