### ISSUE TITLE
Missing run of "update-ca-trust extract" when the variable "ca_trust_dir" is setup in the installer

### ISSUE THREAD

**Issue by vlours** [ansible/awx#6957]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I've been facing the error "_SSL certificate problem: unable to get local issuer certificate_" when adding a custom certificate used by a GIT (bitbucket) repository.

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: openshift
* Ansible version:  2.9.5
* Operating System: awx-task is running `CentOS Linux release 8.1.1911 (Core)`
* Web Browser: Firefox 60.5.0esr

##### STEPS TO REPRODUCE

Use the AWX installer with openshift config to deploy a custom certificate.

- Get a certificate is stored on the Openshift worker nodes in `/etc/pki/ca-trust/source/anchors`
- Set the ca_trust_dir variable in the inventory file`ca_trust_dir=/etc/pki/ca-trust/source/anchors`
- Run the installer
- The mount point is present in the container awx-task:
```sh-4.4$ mount | grep ca-trust
/dev/sda3 on /etc/pki/ca-trust/source/anchors type xfs (ro,relatime,seclabel,attr2,inode64,prjquota)
```

But at the end, I face the "_SSL certificate problem: unable to get local issuer certificate_" error message, when trying to refresh my projects.

Running the command `update-ca-trust extract` in the awx-task containers fix the issue and allow the projects to synchronize.

##### EXPECTED RESULTS

To get the `update-ca-trust extract` command automatically executed in the **awx-task container** if the variable`ca_trust_dir` is defined.

##### ACTUAL RESULTS

Certificate is not extracted.
"_SSL certificate problem: unable to get local issuer certificate_" error message

##### ADDITIONAL INFORMATION

I was able to fix the issue by including the follogin code in the file "awx/installer/roles/kubernetes/templates/launch_awx.yml.j2"

```
[installer]$ git status
On branch devel
Your branch is up to date with 'origin/devel'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   roles/kubernetes/templates/launch_awx.yml.j2

no changes added to commit (use "git add" and/or "git commit -a")
```
```
[installer]$ git diff  
diff --git a/installer/roles/kubernetes/templates/launch_awx.yml.j2 b/installer/roles/kubernetes/templates/launch_awx.yml.j2
index eb08d9e6c..645986602 100644
--- a/installer/roles/kubernetes/templates/launch_awx.yml.j2
+++ b/installer/roles/kubernetes/templates/launch_awx.yml.j2
@@ -17,6 +17,9 @@ data:
     ANSIBLE_REMOTE_TEMP=/tmp ANSIBLE_LOCAL_TEMP=/tmp ansible -i "127.0.0.1," -c local -v -m wait_for -a "host=$DATABASE_HOST port=$DATABASE_PORT" all
     ANSIBLE_REMOTE_TEMP=/tmp ANSIBLE_LOCAL_TEMP=/tmp ansible -i "127.0.0.1," -c local -v -m wait_for -a "path=/var/run/redis/redis.sock" all
 
+{% if ca_trust_dir is defined %}
+    update-ca-trust extract
+{% endif %}
 
     if [ -z "$AWX_SKIP_MIGRATIONS" ]; then
         awx-manage migrate --noinput

```

This patch will add the `update-ca-trust` command only when `ca_trust_dir` variable is defined.

There is maybe a better way to do it, that's why I've opened a Bug report in the first place.

**Comment by shanemcd** [comment]
This issue is no longer relevant since we introduced the awx-operator.
