### ISSUE TITLE
Check External PostgreSQL Server Version Before Proceeding with Install/Upgrade

### ISSUE THREAD

**Issue by imareporter** [ansible/awx#6962]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

When installing/upgrading AWX, an user is requesting that a check be done on external PostgreSQL servers to ensure that the system requirements are being followed. In later releases of AWX, PostgreSQL 10 is now required (https://github.com/ansible/awx/blob/devel/INSTALL.md#system-requirements), instead of PostgreSQL 9.6, which was used up to 11.0.0 (https://github.com/ansible/awx/blob/11.0.0/INSTALL.md). 

EXAMPLE:

- When running the setup playbook, check the external PostgreSQL server's version (e.g. `SELECT version();`).
- If the server version does not meet the requirements for the AWX release, then fail the install/upgrade.

Currently, if you have an AWX-based system that uses an external PostgreSQL 9.6 server and perform an upgrade to a release that requires PostgreSQL 10, the setup playbook won't interfere and permits the upgrade.

**Comment by shanemcd** [comment]
This install method no longer exists. Current install steps are documented in https://github.com/ansible/awx/blob/devel/INSTALL.md.
