### ISSUE TITLE
Allow Host Description to be populated on Inventory Import

### ISSUE THREAD

**Issue by pvik** [ansible/awx#6966]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Currently when inventory is being populated from a custom script, the Host description is always 'imported'.

![description always imported](https://i.imgur.com/Rsds4DP.png)

It would be nice to specify this to something else, during the import process itself.

Say, if there is a `description` field present in the JSON payload, use that to populated the Host description in AWX as well.

I think updating these 2 lines: [1](https://github.com/ansible/awx/blob/c0e07198cf3d35bf98ac98a89fb13d63874055ef/awx/main/management/commands/inventory_import.py#L780), [2](https://github.com/ansible/awx/blob/c0e07198cf3d35bf98ac98a89fb13d63874055ef/awx/main/management/commands/inventory_import.py#L656) should satisfy this.

**Comment by wenottingham** [comment]
See https://github.com/ansible/awx/pull/6265

**Comment by pvik** [comment]
thanks!
Closing this issue.

**Comment by jneedle** [comment]
@one-t I think this can be closed.  Can you verify?
