### ISSUE TITLE
URI module will write password as plaintext to job_events within the API

### ISSUE THREAD

**Issue by mattcrossm** [ansible/awx#697]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
uri module will output the password argument in plaintext to the event_data.task_args field within the job_events list

##### ENVIRONMENT
* AWX version: 1.0.1.50
* AWX install method: docker on linux
* Ansible version:  2.4.0.0
* Operating System: Red Hat Enterprise Linux
* Web Browser: Chrome

##### STEPS TO REPRODUCE

examine the job_events list for any job that includes a uri task with a password

##### EXPECTED RESULTS

blanked out password similar to how vault passwords are handled within job_events

##### ACTUAL RESULTS

"event_data": {
                "play_pattern": "linux",
                "play": "Generate oAuth Token",
                "event_loop": null,
                "task_args": "body=username=username&password=password"

*username and password have been substituted

**Comment by grahamneville** [comment]
I've seen similar issues with the network modules having their passwords in cleartext when being passed to the log aggregator and also being logged in the Postgres database, dispite the fact they have no_log: true within the modules.

**Comment by wwitzel3** [comment]
The issue here is that the password is being provided in the body of the uri module. There is no way for awx to know what is and is not a password in arbitrary URL parameters. You can use the `password` option of the uri module and that will not be displayed in the job event output.
