### ISSUE TITLE
Missing external logging deactivation message with actor

### ISSUE THREAD

**Issue by tessier-marc** [ansible/awx#6976]
##### ISSUE TYPE
 - Forensics data in external logging is incomplete, as the disabling of external logging doesn't send a message with the actor and timestamp of the action that disabled external logging

##### SUMMARY
When disabling External Logging, no message is logged on the activity stream log.  While it is easy to notice that logging is disabled from a lack of message in the external logging system, the fact that a message is not sent prior to changing the value of LOG_AGGREGATOR_ENABLED to false doesn't show us the full timestamp and actor who disabled the feature, as it would when the setting is enabled : 

{"cluster_host_id":"ansible-tower-0","operation":"update","@timestamp":"2020-05-04T17:49:49.157Z","host":"ansible-tower-0","@version":"1","changes":{"value":[false,true]},"tower_uuid":null,"object1":"setting","message":"Activity Stream update entry for setting","port":50022,"relationship":"","actor":"private","object2":"","stack_info":null,"logger_name":"awx.analytics.activity_stream","level":"INFO"}

**Comment by ryanpetrello** [comment]
@tessier-marc this is almost certainly going to be a race condition related to how logs actually get shipped - the way that the external log aggregation works is that when you turn it *off*, the background service (`rysyslogd`) that ships logs exits and stops running.  It's likely that it's being terminated *before* rsyslogd actually ships the message representing the disablement.

If you want to capture who *disabled* external log aggregation, you might want to check out the *activity stream* instead e.g., `/api/v2/activity_stream/?object1=setting&order_by=-timestamp`

<img width="494" alt="image" src="https://user-images.githubusercontent.com/214912/81441560-fb1a6680-913f-11ea-9ac4-e159525d4d32.png">

**Comment by tessier-marc** [comment]
This is not a current possibility of our SIEM system and while possible for our Ansible tower team, will not be available to our security incident response team.

**Comment by ryanpetrello** [comment]
@tessier-marc are you running AWX or Ansible Tower?  This issue tracker is for the upstream AWX open source project, not Red Hat's product.

**Comment by tessier-marc** [comment]
Ansible Tower, I was refered here to open a feature request by Redhat following a case as they say this behavior came from upstream in the AWX project.
