### ISSUE TITLE
Project lookup shows a required error message when field has a value

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#6977]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Project field displays error message "Select a value for this field" when the field has a project value. The project field validation runs and the error message disappears only after firing an onBlur event by clicking on the page. 

Note: The validation behavior is correct on the Inventory lookup.

![proj bug](https://user-images.githubusercontent.com/15881645/81441812-6c5a1980-9140-11ea-9f57-0c46e0137389.gif)

##### STEPS TO REPRODUCE
1. Navigate to JT Add form
2. Select a project from the project lookup

##### EXPECTED RESULTS
Project field is valid and no error message is shown

##### ACTUAL RESULTS
Project field is invalid and error message is shown

**Comment by dsesami** [comment]
This is resolved within #7028. you can close it when that merges.
