### ISSUE TITLE
[Disabling host from imported inventory]

### ISSUE THREAD

**Issue by Warkdev** [ansible/awx#6978]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Hello, when working out with manually created inventories in Ansible Tower, we're able to disable hosts by using the mini-slider on-off. I was wondering if there was any syntax which would allow the same behavior when importing an inventory from any Source control repository ?

Thanks.

**Comment by wenottingham** [comment]
SCM_ENABLED_VAR/SCM_ENABLED_VALUE in settings. You may have to do this via a python file in the container.

**Comment by anxstj** [comment]
Here's some more documentation for someone who stumbles over this issue:

This was tested with AWX 11.2.0.

Here's an inventory example:
```
{
  "_meta": {
    "hostvars": {
      "host.example.com": {
        "ansible_connection": "ssh",
        "ansible_host": "192.0.2.11",
        "ansible_port": 22,
        "enabled": false,
        "tags": []
      }
    }
  },
  "all": {
    "hosts": [
      "host.example.com"
    ]
  }
}
```
The inventory has an additional attribute `enabled`. Now AWX must be made aware of this attribute. This happens in the `defaults.py` file which must be changed in the source code and then the container must be rebuild.

Here's an example patch:
```
--- a/awx/settings/defaults.py
+++ b/awx/settings/defaults.py
@@ -894,8 +894,8 @@ CUSTOM_EXCLUDE_EMPTY_GROUPS = False
 # ---------------------
 # ----- SCM -----
 # ---------------------
-#SCM_ENABLED_VAR =
-#SCM_ENABLED_VALUE =
+SCM_ENABLED_VAR = 'enabled'
+SCM_ENABLED_VALUE = 'true'
 SCM_GROUP_FILTER = r'^.+$'
 SCM_HOST_FILTER = r'^.+$'
 SCM_EXCLUDE_EMPTY_GROUPS = False
```
Please notice that SCM_ENABLED_VAR has the value "enabled" and SCM_ENABLED_VALUE has the value "true". For what I know, both variables must be set. It's not enough to only set SCM_ENABLED_VAR and leave SCM_ENABLED_VALUE commented.
