### ISSUE TITLE
websockets stop working after rabbitmq container restart

### ISSUE THREAD

**Issue by Labutin** [ansible/awx#698]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
AWX task and was stop working after restart container with RabbitMQ

##### ENVIRONMENT
* AWX version: 1.0.1.167
* AWX install method: docker on linux
* Web Browser: FireFox

##### STEPS TO REPRODUCE

Just restart container with RabbitMQ. Web and Task containers will lost connection.

##### EXPECTED RESULTS

Continue working.

##### ACTUAL RESULTS

In Web showing pending status for jobs.

**Comment by matburt** [comment]
I reproduced this... sort-of. Does refreshing your page show the jobs having run? What I notice is that everything seems to work except for websockets.

**Comment by Labutin** [comment]
Yes, if you refresh web page manually you will see playbook progress. But even after the manual refresh, it will not start an automatic update.
