### ISSUE TITLE
AWX login implementation never triggers "Save this password" event in Firefox

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#6984]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When you login to AWX it's done via some kind of JS hack I guess, that is completely invisible to  firefox and the browser doesn't even know that you triggered the login event (despite it recognizes the login form and allows you to re-use credentials from other websites). However it never ask you to  remember or update the password, making it necessary to re-enter it every time.

##### ENVIRONMENT
* AWX version: 11.0.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System: MacOS
* Web Browser: Firefox 74.0

##### STEPS TO REPRODUCE

Just login to AWX via Firefox (version 74.0 or any other), you will not be prompted to save login

##### EXPECTED RESULTS

Firefox should ask to remember login just as with any other website

##### ACTUAL RESULTS

Nothing happens

**Comment by unlikelyzero** [comment]
@blomquisg are you asking us to test that this works in pf?

**Comment by ryanpetrello** [comment]
(I'll answer for him) Yes.

**Comment by benapetr** [comment]
@unlikelyzero  what is "pf"?

**Comment by unlikelyzero** [comment]
Save Password is triggered on Firefox ESR in `ui_next`.

**Comment by unlikelyzero** [comment]
This issue is fixed in the `ui_next` project. For more information, please see https://github.com/ansible/awx/tree/devel/awx/ui_next
