### ISSUE TITLE
Uninstall windows package script is running perfect but not installing the package 

### ISSUE THREAD

**Issue by rupeshrvk** [ansible/awx#6985]
ansible --version 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]

- name: Uninstall  packages
  hosts: all
  tasks:
    - name: Uninstall Mozila Firefox
      win_package: 
             path: C:\Program Files(x86)\Mozilla Maintenance Service\Uninstall.exe
             product_id: Firefox
             arguments: /S
             state: absent

Output : 
root@puppet-master:~/ansible# ansible-playbook ping.yaml -vvv
ansible-playbook 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin

PLAYBOOK: ping.yaml ************************************************************************************************************
1 plays in ping.yaml

PLAY [Uninstall  packages] *****************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************
task path: /root/ansible/ping.yaml:1
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/windows/setup.ps1
Pipelining is enabled.
<192.168.142.170> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5985 TO 192.168.142.170
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/windows/setup.ps1
Pipelining is enabled.
<192.168.142.171> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5985 TO 192.168.142.171
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
ok: [192.168.142.171]
ok: [192.168.142.170]
META: ran handlers

TASK [Uninstall Mozila Firefox] ************************************************************************************************
task path: /root/ansible/ping.yaml:4
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/windows/win_package.ps1
Pipelining is enabled.
<192.168.142.170> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5985 TO 192.168.142.170
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/windows/win_package.ps1
Pipelining is enabled.
<192.168.142.171> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5985 TO 192.168.142.171
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
ok: [192.168.142.170] => {
    "changed": false,
    "reboot_required": false
}
ok: [192.168.142.171] => {
    "changed": false,
    "reboot_required": false
}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************************************************************
192.168.142.170            : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
192.168.142.171            : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by wenottingham** [comment]
This repo is for issues with awx itself; this looks to be an issue with your playbook. You're best off talking to the ansible project itself via IRC or the mailing lists as noted here: https://docs.ansible.com/ansible/latest/community/index.html
