### ISSUE TITLE
No job output

### ISSUE THREAD

**Issue by lucaslan** [ansible/awx#699]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

When you start a job there is no output and when you go to JOBS and check the output from a job it only shows the output if the job was successfull

##### ENVIRONMENT
* AWX version: 1.0.1.225
* AWX install method: Docker
* Ansible version:  2.4.1.0
* Operating System: RHEL7
* Web Browser: Firefox 39.0.3 / Google Chrome 62.0.3202.94 

##### STEPS TO REPRODUCE

Just run a job

##### EXPECTED RESULTS

View the output 

##### ACTUAL RESULTS

When you start a job there is no output and when you go to JOBS and check the output from a job it only shows the output if the job was successfull.

The output files are in /var/lib/awx/job_status on the awx_task container, I already tried to install AWX again in another machine and I got the same issue

**Comment by fsidnenko** [comment]
Is it a duplicate issue of https://github.com/ansible/awx/issues/654 and then https://github.com/ansible/awx/issues/615 ?

**Comment by lucaslan** [comment]
Yes!! sorry

**Comment by ryanpetrello** [comment]
Should now be fixed via https://github.com/ansible/awx/pull/720
