### ISSUE TITLE
Link inventory scripts with multiple organizations

### ISSUE THREAD

**Issue by nbruniaux** [ansible/awx#6996]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Hello,

In my instance of awx, I use a custom inventory script which extracts my hosts from my cmdb and classifies them by group according to various parameters. I also have several organizations defined.

The problem is when a user from organization A wants to create an inventory using the dynamic script attached to organization B, the script is not visible to the user from organization A.

It would be necessary to duplicate the inventory script for each organization which can be quickly difficult to manage in the event of changes.

The solution would be to be able to link the inventory script to several organizations!

**Comment by wenottingham** [comment]
This feature is actually deprecated (in favor of inventory plugins from collections and inventory from projects), so this is not going to happen.
