### ISSUE TITLE
ANY/ALL convergence setting doesn't save sometimes for approval nodes

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#6998]
##### ISSUE TYPE
 - Bug Report

##### STEPS TO REPRODUCE
- Create and save workflow that looks like this:
![Screenshot from 2020-05-12 10-12-06](https://user-images.githubusercontent.com/9753817/81702291-12579d80-9439-11ea-9e3a-1039c131bc5c.png)
- Open the workflow visualizer for the workflow, change the convergence setting of the approval node to `ALL` and save.

##### EXPECTED RESULTS
- The new convergence setting should save and the approval node should now have an `ALL` tag.
- There should be api requests in the console log showing that the updated convergence values were sent to the API by the browser.

##### ACTUAL RESULTS
- The convergence setting doesn't save
- No requests in the browser console logs showing the updated convergence setting.

##### ADDITIONAL INFORMATION
Interestingly, the topology of the workflow seems to be a factor. if you create a workflow that looks like this:
![Screenshot from 2020-05-12 10-04-55](https://user-images.githubusercontent.com/9753817/81702626-898d3180-9439-11ea-8339-4883673a0cb8.png)
The approval node's convergence setting can be updated as expected.

**Comment by kdelee** [comment]
@dsesami @unlikelyzero @shebangbash this one is hanging out from a while back, should be easy as we already verified it for the tower patch release

**Comment by unlikelyzero** [comment]
@kdelee i'll take non-4.0 tasks. Feel free to @ or assign me directly

**Comment by unlikelyzero** [comment]
https://github.com/ansible/tower-qa/issues/5211
