### ISSUE TITLE
RFE: Make installer able to check for users coming from AD, LDAP, etc. 

### ISSUE THREAD

**Issue by agilleyrh** [ansible/awx#6999]
##### ISSUE TYPE
 - Add support for the installer to check for rabbitmq, PostgreSQL, or other services that are defined in AD or other sources. 

##### SUMMARY
The installer will fail with nontrivial errors when service user accounts come from sources like AD, LDAP, etc... 

Having the installer do a `getent` or something would likely help here. With some large companies when these users are stored in services like AD it requires them to modify the installer to get it working.

**Comment by wenottingham** [comment]
... what requires modification? All the service RPMs should check for the user before adding it.

**Comment by wenottingham** [comment]
Also, this isn't relevant for the AWX container installer.
