### ISSUE TITLE
Feature: Automatic API docs generation

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#70]
AWX Feature Spec - Automatic API docs generation
=======================================

User Persona
------------
Person writing API integrations

Usage Cases
-----------

We have a lovely, browseable, API with docs. However, people want to be able
to browse the API docs (or historical API docs) without standing up Tower.
Ergo, we should automatically generate them.

API Considerations
------------------
TBD.

UI/UX Considerations
--------------------
None.

Docs
----

QA Suggestions
--------------

Notes
-----

per @j00bar:

Check out generating Sphinx docs from DRF autodocs via Swagger YAML specifications
https://github.com/marcgibbons/django-rest-swagger
https://github.com/unaguil/sphinx-swagger

Updates/Changelog
2017-09-08: initial version

**Comment by ryanpetrello** [comment]
I've merged in support for generating a Swagger document:

https://github.com/ansible/awx/pull/1124

I'm working with @shanemcd next to get this built nightly and hosted at a public URL.

**Comment by rob-64** [comment]
@ryanpetrello is the swagger now being published by chance?

**Comment by ryanpetrello** [comment]
@rob-64 it's not currently, but it's pretty easy to generate the file from source yourself if you want to view it in a third party Swagger browsing tool (like https://swagger.io/tools/swagger-ui/).

If you set up a local Docker environment: https://github.com/ansible/awx/blob/devel/CONTRIBUTING.md#setting-up-your-development-environment

You can run `make swagger` from inside the container:
```shell
$ docker exec -it tools_awx_1 bash
[root@awx]# cd /awx_devel && make swagger
```

...and it will produce a `swagger.json` file that represents the Swagger doc (generating the file takes a minute or two).

```shell
[root@awx awx_devel]# head -n15 swagger.json
{
  "swagger": "2.0",
  "info": {
    "title": "Ansible Tower API",
    "description": "",
    "version": "1.0.5.807"
  },
  "host": null,
  "schemes": [
    "https"
  ],
  "paths": {
    "/api/v2/hosts/{id}/ansible_facts/": {
      "get": {
        "description": "\nMake GET request to this resource to retrieve a single host\nrecord containing the following fields:\n\n* `id`: Database ID for this host...
```
