### ISSUE TITLE
Ansible Tower (3.2.1) Scheduled Jobs Revert to Los Angeles Time Regardless

### ISSUE THREAD

**Issue by superky13** [ansible/awx#700]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI
 -

##### SUMMARY

Ansible Tower (3.2.1) Scheduled Jobs Revert to Los Angeles Time Regardless; changing to another timezone (ie. New York/EST) in the schedule drop down is not respected after a save; it's always changed back to Los Angeles.  This leaves us having to account for the time difference when choosing a time for the scheduled template to run. 

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:
3.2.1
RHEL 7.3
Chrome/FFX/IE

##### STEPS TO REPRODUCE
Login to the Tower UI; create a new schedule from an existing template; chose a non-default timezone from the dropdown; save; schedule is relative to Los Angeles time instead of the timezone chosen (in our case New York/EST).  Also tower boxes and db servers in the cluster have a local timezone of New York, for reference.

##### EXPECTED RESULTS

Schedules run according to timezones chosen

##### ACTUAL RESULTS

Schedules run relative to Los Angeles timezone; so if 9PM EST was chosen as the schedule, once saved, it is reported as scheduled at 9PM PST

**Comment by wenottingham** [comment]
For Ansible Tower issues, please contact your Red Hat support rep.

**Comment by cgrimm-redhat** [comment]
@wenottingham FYI @KWRitchie is a RH Consultant on-site.  Recommendations other than opening up the issue here?

**Comment by wenottingham** [comment]
As stated - for Tower things, go through support.
