### ISSUE TITLE
Empty state appears briefly after adding a survey

### ISSUE THREAD

**Issue by appuk** [ansible/awx#7004]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After adding a Survey, the Empty state page appears briefly before the survey list actually populates with the newly added survey

##### STEPS TO REPRODUCE
1. Create a JT
2. Go to the surveys tab
3. Add a new survey
4. click save

##### EXPECTED RESULTS
The page should be directed to the Survey list page and the newly added survey should be present

##### ACTUAL RESULTS
The page redirects to the Survey list page, but it does not populate the survey list immediately causing it to show the Empty state for like a second
This also causes Flake in the Cypress tests, but overall the behavior is a bit annoying

![survey](https://user-images.githubusercontent.com/11617351/81752280-3047f100-947f-11ea-9784-8f64b9447b1d.gif)

**Comment by unlikelyzero** [comment]
still an issue. Should be tracking in https://github.com/ansible/awx/issues/4212

**Comment by tiagodread** [comment]
This was fixed by https://github.com/ansible/awx/pull/8802, once this PR is merged we can safely close this issue

**Comment by tiagodread** [comment]
Fixed
