### ISSUE TITLE
Allow associating host to inventory/group using awx cli

### ISSUE THREAD

**Issue by jainnikhil30** [ansible/awx#7005]
##### ISSUE TYPE
Feature Request

##### SUMMARY
There should be a way to associate host to inventory/group. Something like following:

awx host associate --host my.host.com --inventory test --group test

**Comment by AlanCoding** [comment]
Duplicate of https://github.com/ansible/awx/issues/6056?

**Comment by JosephJHCho** [comment]
#6056 is about "awx-cli" but the request is about "awx" which is installed by"pip3 install https://github.com/ansible/awx/archive/11.2.0.tar.gz#egg=awxkit&subdirectory=awxkit".  For my understanding it seems  different issue.

**Comment by swills** [comment]
Sorry to comment on an old issue, but I can't seem to find how to do this from the cli and the docs haven't seemed to have helped. How does one add a host to a group via `awx` cli?
