### ISSUE TITLE
Openstack inventory update does not work

### ISSUE THREAD

**Issue by GabboPenna** [ansible/awx#7006]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Openstack inventory update does not work

##### ENVIRONMENT
* AWX version: 11.1 e 11.2
* AWX install method: docker on linux
* Ansible version:  2.9.7
* Operating System: CentOS Linux release 8.1.1911
* Web Browser: Firefox 76.0.1

##### STEPS TO REPRODUCE
- Install awx
- Create Openstack Credentials
- Create Inventories
- Create Sources Inventories 
- Run Sync

##### EXPECTED RESULTS
We have in the same enviroments a redhat 3.6.4 tower that works without problems.

##### ACTUAL RESULTS

Failure: Unable to establish connection to http://192.168.93.133:8774/v2.1/servers/detail: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying in 0.5s.
38
Failure: Unable to establish connection to http://192.168.93.133:9696/v2.0/networks.json: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying in 0.5s.
39
Failure: Unable to establish connection to http://192.168.93.133:8774/v2.1/servers/0f59d778-8d3c-43e5-b8f0-c873d74c31b5: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')). Retrying in 0.5s.
40
[WARNING]: * Failed to parse /tmp/awx_1_uqo41nl1/openstack.yml with auto
41
plugin: Unable to establish connection to
42
http://192.168.93.133:8774/v2.1/servers/0f59d778-8d3c-43e5-b8f0-c873d74c31b5:
43
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
44 

[WARNING]: Unable to parse /tmp/awx_1_uqo41nl1/openstack.yml as an inventory
87
source
88
ERROR! No inventory was parsed, please check your configuration and options.
89

**Comment by ryanpetrello** [comment]
Seems like your AWX environment can't reach your OpenStack environment:

`Failure: Unable to establish connection to http://192.168.93.133:9696/v2.0/networks.json: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

**Comment by GabboPenna** [comment]
> 
> 
> Seems like your AWX environment can't reach your OpenStack environment:
> 
> `Failure: Unable to establish connection to http://192.168.93.133:9696/v2.0/networks.json: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

@ryanpetrello Thanks. but, the curl from container awx to openstack work properly:

```
curl -s -H "X-Auth-Token: $TOKEN" http://192.168.93.133:8774/v2.1/flavors
{"flavors": [{"id": "0311052f-e1a0-4720-9497-43a060e16214", "name": "m1.xlarge", "links":  
<OMITTED>
```
So there are no connectivity issues.

**Comment by ryanpetrello** [comment]
@GabboPenna the error you reported is a different port and path than what you tried in `curl`:

`http://192.168.93.133:9696/v2.0/networks.json`

**Comment by ryanpetrello** [comment]
Also, do you have some sort of proxy in the middle?

You'll also want to verify that you're testing connectivity from your task container, not the web one (as that's where inventory imports actually run); what you're encountering here is almost certainly some type of network connectivity issue between your Docker container(s) and your OpenStack cluster.

**Comment by GabboPenna** [comment]
@ryanpetrello No proxy, but we noticed that from the container the GET to openstacks do not always come back OK. On the base OS, it's always ok.. i think it's a problem on docker

**Comment by ryanpetrello** [comment]
@GabboPenna yea, this really does sound like something specific to your Docker networking.

**Comment by GabboPenna** [comment]
@ryanpetrello The installation of awx on docker is located in a vm on an openstack environment.. do you have any advice?

**Comment by GabboPenna** [comment]
Solved, the problem was the mtu of the docker network.
Before redploying awx we modified the docker-compose template:

/installer/roles/local_docker/templates/docker-compose.yml.j2

```
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1442
```

**Comment by ryanpetrello** [comment]
Glad you all got it worked out @GabboPenna 👍
