### ISSUE TITLE
The capacity percentage for an instance can be negative when work is assigned beyond capacity

### ISSUE THREAD

**Issue by ghost** [ansible/awx#701]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
If an instance in an instance group is at or over capacity, but the instance group is not over capacity, that instance can still get more jobs and, when the capacity is exceeded, the percentage will become negative for the instance.

##### ENVIRONMENT
* AWX version: 1.0.1

##### STEPS TO REPRODUCE

Launch several jobs against a particular instance group, such that the capacity of a particular instance is exceeded.

##### EXPECTED RESULTS

The instance that is at capacity would not be assigned additional work, but work would rather be assigned to the node on which capacity remains

##### ACTUAL RESULTS

The work may be assigned to the instance that is at or above capacity.

**Comment by ryanpetrello** [comment]
Resolved in 1.0.7
