### ISSUE TITLE
Source Control Branch missing from Prompt on launch

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#7011]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
`Source Control Branch` missing from `Prompt on launch`

##### STEPS TO REPRODUCE
1 - Select `Allow Branch Override` in a project.
2 - Select `Prompt on launch` for the  Source Control Branch field in a job template associated to the project above.
3 - Launch the job template.

##### EXPECTED RESULTS
To Source Control Branch to be present on Prompt on launch.

##### ACTUAL RESULTS
![missing_scm_job_template_launch](https://user-images.githubusercontent.com/9053044/81834858-8bc1bf80-950f-11ea-9f64-34c415359ebf.gif)

**Comment by acelinkio** [comment]
AWX 19.3.0 this is still the case.  I was able to force it by using the awx.awx.tower_job_template module but am skeptical if it works as intended
