### ISSUE TITLE
AWX SCM Project not actually updating.

### ISSUE THREAD

**Issue by lanceofwhichwedream** [ansible/awx#7012]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
SCM Project inventory update completes, but template created for newly created playbook fails to find playbook.

I have an awx instance on docker that I upgraded from version 9.0.0 to version 11.1.0. The project is an SCM type that links to gitlab. After I upgraded to 11.1.0, I made a new playbook, updated the project and created a new template for that playbook, when I tried to run it, the jbo ended up failing saying that it couldn't find the playbook.

I ended up creating a new project, changing the template to that project and the job ran fine. I also changed the project for the template back to the initial project and the job ran fine again. 

##### ENVIRONMENT
* AWX version: 11.1.0
* AWX install method: docker on linux
* Ansible version:  2.9.5
* Operating System: Ubuntu Bionic
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Upgrade awx with preexisting SCM project, create new playbook, update the project, create new template, run template.

##### EXPECTED RESULTS

Successful run of the template

##### ACTUAL RESULTS

ERROR! the playbook: $PLAYBOOK_NAME.yml could not be found

##### ADDITIONAL INFORMATION

Will provide requested info given method to obtain it.

**Comment by AlanCoding** [comment]
Think this was resolved in bf65b40241d60e99e49b3109a33c26f26cd418ec

Not yet out in a release, will be soon.

Also see #6812
