### ISSUE TITLE
JT Launch prompts: Credential Passwords step

### ISSUE THREAD

**Issue by keithjgrant** [ansible/awx#7015]
Follow-up for #5909 

##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
This is the final step that needs to be coded up for the JT Launch prompt. Criteria:

- This should be the third step, immediately following the Credentials step
- This step can be shown in one of two situations:
    - Firstly, it should be shown if passwords_needed_to_start is _not_ an empty array _and_ ask_credential_on_launch is set to false.
    - Secondly, it should be shown if ask_credential_on_launch is set to true _and_ any of the selected credentials from that step prompt for passwords.
- This step is dynamic and should be able to support any number of password fields (the JT could have n number of different vault credentials all prompting for a password).
~~- Previously we showed these password fields on the same step as the credentials.  If it's easier to do that here as well then we can explore that.~~
~~- User cannot proceed to the next step until all required passwords are provided~~

**Comment by mabashian** [comment]
Moving this to blocked while waiting for prompt on launch refactors

**Comment by mabashian** [comment]
A good portion of this work is already completed here: https://github.com/mabashian/awx/tree/7015-prompt-cred-passwords but this branch includes passwords with the credential step.  If we want to split them out into 2 steps then this will need to be refactored (in addition to refactoring after POL changes).

**Comment by unlikelyzero** [comment]
https://github.com/ansible/awx/pull/7281#issuecomment-691218496 note to cover

**Comment by one-t** [comment]
Just want to check, are we expecting this PR to add prompting for schedules or will that be covered in another one? Currently that functionality does not appear to be implemented.

**Comment by mabashian** [comment]
@one-t good question.  Schedule prompting will be handled right after this PR merges.  https://github.com/ansible/awx/issues/7692

**Comment by unlikelyzero** [comment]
@one-t in this case, we will put a stubbed out test in the schedules folder with a //TBI link to where the test will be implemented

**Comment by unlikelyzero** [comment]
https://github.com/ansible/awx/pull/9028#pullrequestreview-571571287
