### ISSUE TITLE
JT Launch prompts: credential validation improvements

### ISSUE THREAD

**Issue by keithjgrant** [ansible/awx#7018]
Follow-up for #5909

##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
In the Credentials step of the JT launch prompt, the following behavior should be enforced:

Default credentials can be removed but they must be replaced with another credential of the same type. This is enforced by the api. For example, if there is a default machine credential on the JT then I can replace it with another machine credential but I cannot proceed to the next step without at least one machine credential.

**Comment by unlikelyzero** [comment]
@keithjgrant added enhancement instead of feature as this seems like it may not be 100% critical for launch. Is that correct?

**Comment by mabashian** [comment]
Gonna close this in favor of #8200
