### ISSUE TITLE
Postgres container issues, stuck in a loop of restarting. Data not persisting.

### ISSUE THREAD

**Issue by rladigital** [ansible/awx#702]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

Installs correctly and runs fine. However after some time the Postgres database stops working and gets stuck restarting. I can fix this by removing all containers and rerunning setup playbook but the data does not seem to persist and I have repeatedly lost everything. 

How can I ensure the data remains persistent? 
What would the recommended process be for restarting the postgres container if it goes wrong?

##### ENVIRONMENT
* AWX version: Latest
* AWX install method: docker on linux
* Ansible version:  2.4.0
* Operating System: Centos 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Following standard install and over a given amount of time the Postgres container will get stuck in a loop of restarting itself. Causing the web container to give an error of "Connection refused by XX.XX.XX.XX"

##### EXPECTED RESULTS

n/a

##### ACTUAL RESULTS

n/a

##### ADDITIONAL INFORMATION

n/a

**Comment by philippwiesner** [comment]
We had a similar issue in our environment. The issue was related to SystemD cleaning up the /tmp directory and deleting the persistent postgres data dir files. Best way would be to change the persistent data directory to some other place than /tmp .

**Comment by mkempster22** [comment]
Is this linked to #438 & #535 ?

**Comment by imoes** [comment]
Not the Standard port? pg_port=5432

**Comment by matburt** [comment]
We'll have a fix for #535 in soon... #438 was resolved a while ago and might have an impact on you (or systemd as mentioned earlier).

For more permanence you may want to set up an external postgres and point the awx install at that, see: https://github.com/ansible/awx/blob/devel/INSTALL.md#postgresql-1
