### ISSUE TITLE
Ansible Network automation Status always throws Changed=1

### ISSUE THREAD

**Issue by tamil93-ss** [ansible/awx#7022]
Hi guys,

Below is my code and output

I have one router and executed the code but the status of the changed=1 remains same, kindly help on this

---

- name: Ospf Config
  hosts: router
  gather_facts: true
  connection: local

  tasks:
    - name: Router ospf config
      ios_config:
        lines:
          - network 1.1.1.1 255.255.255.255 area 0
        parents: router ospf 2
        
      
      
      register: output

    - debug: var=output

OUtput:

PLAY [Ospf Config] ***************************************************************************************************************************************************************************************************************************

TASK [Router ospf config] ********************************************************************************************************************************************************************************************************************
changed: [R1]

TASK [debug] *********************************************************************************************************************************************************************************************************************************
ok: [R1] => {
    "output": {
        "banners": {},
        "changed": true,
        "commands": [
            "router ospf 2",
            "network 1.1.1.1 255.255.255.255 area 0"
        ],
        "failed": false,
        "updates": [
            "router ospf 2",
            "network 1.1.1.1 255.255.255.255 area 0"
        ]
    }
}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
R1                         : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Evenafter the same execution of the file same status is coming

**Comment by wenottingham** [comment]
This repo is for issues in the AWX application/execution framework.

This appears to be an issue with your playbook, we suggest looking into the Ansible community resources here: https://docs.ansible.com/ansible/latest/community/communication.html#communication

**Comment by tamil93-ss** [comment]
Thank you bro.
