### ISSUE TITLE
Inventory Groups Host List Alert Modal

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#7024]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Alerts are not rendering properly.
##### ENVIRONMENT
* AWX version:11.02
* AWX install method: docker for mac
* Ansible version:  2.10
* Operating System: Mojave
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Force errors to be thrown on the associate and disassociate api calls( I passed in strings for id instead of integers).  The click on associate, see error, close error, then click on disassociate. Notice that no error is thrown.

##### EXPECTED RESULTS

Proper Alert Modal shows up
##### ACTUAL RESULTS

No Alert Modal show sup
##### ADDITIONAL INFORMATION
 In this code we are using the same modal for both types of alerts.  I believe the first alert is not being cleared  properly so that the second alert can be rendered.

![error](https://user-images.githubusercontent.com/39280967/81957186-3f8f8180-95da-11ea-971d-ceb75aed38c8.gif)

**Comment by dsesami** [comment]
Approved PR -- when @marshmalien merges it this can be closed.
