### ISSUE TITLE
satellite custom group_prefix not getting applied to all groups

### ISSUE THREAD

**Issue by jladdjr** [ansible/awx#7031]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The `satellite6_group_prefix` satellite source vars should replace the default `foreman_` prefix with a custom one when creating host groups. This prefix is not being applied to all groups. Namely, it is missing from the groups we create here:

https://github.com/ansible/awx/blob/devel/awx/main/models/inventory.py#L2605-L2622

##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: any
* Ansible version:  2.9+ (needed to enable use of inv. plugins)
* Operating System: any
* Web Browser: any

##### STEPS TO REPRODUCE

1. Create a satellite inventory
2. In inv. source section, set `satellite6_group_prefix: newprefix_`
3. Confirm not all groups have new prefix.

##### EXPECTED RESULTS

All groups use new prefix.

##### ACTUAL RESULTS

![Screen Shot 2020-05-14 at 1 28 34 PM](https://user-images.githubusercontent.com/4440360/81982578-eda12880-95e6-11ea-849a-244551762ef0.png)

##### ADDITIONAL INFORMATION

[This section](https://github.com/ansible/awx/blob/devel/awx/main/models/inventory.py#L2605-L2622), mentioned in the description, is a part of awx's 'compatibility layer' that bridges the differences between foreman's script and plugin. We need to update this section so that it takes the custom prefix into consideration.

**Comment by jladdjr** [comment]
Have a fix up at https://github.com/ansible/awx/pull/7044. Verified locally and is looking good. Looks like we may be running into some gating issues w/ PRs atm.

**Comment by jladdjr** [comment]
The fix for this just got in. (cc @kdelee)

**Comment by kdelee** [comment]
Tested this out manually and it works. Going to work on getting us some regression coverage here, this should be easy to do. Closing as verified will mention issue when I put up PR for tests
