### ISSUE TITLE
Fix delete button styles across ui-next

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#7041]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Delete buttons should only use the "danger" variant on the delete confirmation screen (delete modal). In other words, if the delete action button triggers a destructive and impossible to undo action, use the "danger" variant. Delete buttons that trigger the delete modal confirmation screen should use the "secondary" variant.  

This is a sweeping update across all lists, forms, and modals. 

cc @trahman73 

##### STEPS TO REPRODUCE
* Navigate to templates list
* Select a template 
* View delete button

##### EXPECTED RESULTS
* Delete button should be styled with the secondary variant
<img width="792" alt="Screen Shot 2020-05-15 at 2 09 06 PM" src="https://user-images.githubusercontent.com/15881645/82082246-a9308e00-96b5-11ea-85dd-b0df48e91791.png">

##### ACTUAL RESULTS
* Delete button is styled with the danger variant
<img width="798" alt="Screen Shot 2020-05-15 at 2 00 00 PM" src="https://user-images.githubusercontent.com/15881645/82082127-7ab2b300-96b5-11ea-9ff7-37049244b6ab.png">

##### ADDITIONAL INFORMATION
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/buttons-and-links

**Comment by nixocio** [comment]
See: https://github.com/ansible/awx/issues/7722

**Comment by nixocio** [comment]
Part of this work was already covered here https://github.com/ansible/awx/pull/7733

The same styling should be applicable to `dissociate` button per @trahman73  feedback.

See: https://tower-mockups.testing.ansible.com/patternfly/instance-groups/instance-groups-instances/
