### ISSUE TITLE
AWX with ecs fargate support

### ISSUE THREAD

**Issue by Ragulb89** [ansible/awx#7056]
##### ISSUE TYPE
 - Feature Idea
    - create a service discovery names for awx_task and awx_web so it can be communicated outside the VM and discover each other, this will be useful to launch awx in fargate ecs.
##### SUMMARY

  - unable to launch awx in fargate because awx_task and awx_web is unable to discover each other.

**Comment by wenottingham** [comment]
For scalable installs, our target is kubernetes/openshift. We are not investigating other container deployments at this time outside of local docker-compose for testing.
