### ISSUE TITLE
Define a schema for execution environments

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#7057]
This is a subtask of a larger enhancement/initiative surrounding execution environments: https://github.com/ansible/awx/issues/5157

AWX needs to expand to provision and manage execution environments, including how they get to execution nodes.

**What is an execution environment?**

An execution environment definition consists of:
- an ansible version
- a python version (defaults to system python)
- a set of required python libraries
- zero or more collections (optional). This could be sourced from the requirements present in a playbook repo
- python dependencies of those collections

The concept of specifying a set of collections for an environment is to resolve and install their dependencies. The collections themselves are not required to be in the environment (and arguably should not be.)

An execution environment is built from this definition. This will likely be a container image.

**Comment by ryanpetrello** [comment]
Experimental implementation work has begun on this for defining this schema definition and the tooling used to build actual execution environments:

https://github.com/ansible/ansible-builder/tree/devel/ansible_builder

**Comment by AlanCoding** [comment]
Some basic sense of how the format is shaping up can be found in the tests:

https://github.com/ansible/ansible-builder/blob/devel/test/test_main.py#L25

I really want to hit the ground running by hooking this into real collections.

**Comment by kdelee** [comment]
For testing: this will be for testing https://github.com/ansible/ansible-builder/ . We could build simple on repo testing of the YAML files just making sure it can consume it and has sane error messages and validates that it generates a valide ContainerFile -- but if you are missing some dependencies, that's on you. Will test building our OWN execution environments in a later step. Does not include testing any built container images.

Use case we want to make sure we address is that users can specify collections without having to know all the deps (that may change) of the collections. E.g. specify you are using CollectionABC, it will fetch data from galaxy that CollectionABC relies on python-package-foo and adds a step in the ContainerFile that installs it in some sane way that will then be usable by runner

**Comment by kdelee** [comment]
@AlanCoding can you provide update on this. AFAIK we are pretty close to having this pinned down

**Comment by AlanCoding** [comment]
See section on "Execution Environment Definition" https://github.com/ansible/ansible-builder

We have contributed this upstream for a lot of collections, openstack may soon be the only notable absence.

It has become a priority to move that to https://ansible-builder.readthedocs.io/en/latest/ before Fest, which is in progress.

My only remaining concern is https://github.com/ansible/galaxy-importer/pull/92, in that, if it gets added to Galaxy data there, I'm worried about giving different answers from what `ansible-builder` gives.

In any case, it would seem hard to change the schema, because it has been accepted by several collections already.

**Comment by kdelee** [comment]
The schema has been defined and adopted, and is used in production of the default execution environment which has been validated. Any specific enhancements or bugs will be filed in seperate issues
