### ISSUE TITLE
Build and publish official default execution environments

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#7058]
This is a subtask of a larger enhancement/initiative surrounding execution environments: https://github.com/ansible/awx/issues/5157

Automate the process of building and shipping a set of default execution environments using the schemas and tooling defined in:  https://github.com/ansible/awx/issues/7057

This work involves shipping a set of default execution environments for all supported AWX platforms, and support for any downstream implementations:

- Take the existing requirements from the default virtual environments today, and use this to compose default execution environments.
- Develop a mechanism for pinning and incrementing dependency versions (to support newer software releases, and to address security issues) as we do today.

**Comment by ryanpetrello** [comment]
Specifically, we'll need to identify a set of requirements to have continuity in the behavior of AWX _today_.  At a very minimum, we'll need:

- A "kitchen-sink" like environment that includes effectively what represents Ansible 2.9 (today) - all of the content users are likely to want to continue to have for their playbooks to run as they do today.
- An execution environments specifically for inventory updates and/or project updates:
    - SCM requirements for svn, git, potentially hg
    - Content necessary for syncing with third party inventory sources, ec2, gce, etc...

**Comment by ryanpetrello** [comment]
Additionally, what will be the distribution mechanism for these default environments (e.g., Quay)?  What will that look like when you install AWX (will it be seamless?)

**Comment by AlanCoding** [comment]
> SCM requirements for svn, git, potentially hg

The svn part of that is

```
RUN dnf -y install subversion
```

from `installer//roles/image_build/templates/Dockerfile.j2`

Even if we develop `ansible-builder` and the collections to the point of having the needed metadata, this would be unworkable because svn is in ansible-base (same applies for git). So it would be a customization layer, which is to say, the same as writing the Containerfile ourselves.

Whether or not `mercurial` gets thrown in is a separate question due to `community.general`.

Git seems inconsistent in different installers between `dnf -y install git-core` and just `git`

**Comment by AlanCoding** [comment]
Link https://github.com/ansible/awx/pull/7971

several points made here should be ready to get incorporated into that.

**Comment by AlanCoding** [comment]
Picking up from prior comments here:

Lately we have been trending toward a model where we just have 1 execution environment that replaces the current Ansible virtual environment. In addition to this, we still have the base image, that is built from:

https://github.com/ansible/ansible-runner/blob/devel/Dockerfile

I think that @shanemcd has sufficiently made the case that this is non-trivial to maintain. Users who want to build their own EEs, with or without builder, should start from that using a `FROM`.

Speaking strictly for the purpose of AWX functionality, we just need this 1 execution environment. That will work for jobs/inventory/projects. If people _don't want_ the content that it has, they can use the base image.

**Comment by AlanCoding** [comment]
Putting final thoughts here:

For QE needs, we want to produce a series of execution environments, for now, for 2.9, 2.10, and devel, these are the Ansible major versions. We have a demo working to produce these for the _base_ runner image:

https://quay.io/repository/ansible/ansible-runner?tab=tags

See the tags like `devel.stable-2.9`, that means `ansible-runner` devel branch with Ansible `stable-2.9` branch.

We need to build on top of these to create the default execution environment so we can test them all. For speed, we can start by building 1 image, just with Ansible devel, and then copy over collections at `/usr/share/ansible/collections` using a multistage build. So this would involve some hacks on top of general `ansible-builder`.

I want to be clear, we would still only have 1 official image (probably with the latest stable Ansible), this would just be for doing testing.

**Comment by AlanCoding** [comment]
Proposed resolution for mercurial https://github.com/ansible/awx/pull/8727

**Comment by kdelee** [comment]
We have an official image for AWX, other downstream work is tracked downstream
