### ISSUE TITLE
Produce and document a process for AWX users to produce custom execution environments

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#7059]
This is a subtask of a larger enhancement/initiative surrounding execution environments: https://github.com/ansible/awx/issues/5157

AWX users should be able to utilize the schema definition and tooling defined in https://github.com/ansible/awx/issues/7057 to build custom execution environments.  The output of this tooling is a `Dockerfile/Containerfile`.

**Comment by ryanpetrello** [comment]
Open question: to what extent should this process attempt to identify and resolve dependency conflicts when building custom execution environments?  One thought that has been tossed around is to utilize the poetry library to aid in conflict discovery and resolution, but it sounds like certain types of conflicts will always require some form of human intervention.

**Comment by kdelee** [comment]
@beeankha can you keep @yagomarques and @shebangbash up to date on anything you produce, so they can read it and bring questions/comments?

**Comment by nixocio** [comment]
See: https://github.com/ansible/awx/issues/9846

**Comment by AlanCoding** [comment]
somewhat related https://github.com/ansible/awx/pull/10464

this is on the triage list, what are we trying to do here?

**Comment by beeankha** [comment]
This work is starting to become finalized and transferred into ASCII Doc format in the downstream docs repo; closing this issue.
