### ISSUE TITLE
When variables are added in the edit screen of a group, the text area clears and is empty after save.

### ISSUE THREAD

**Issue by midekra** [ansible/awx#706]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
Within the edit of a group in the inventory edited variables clears and is empty after 'save' 

##### ENVIRONMENT
* AWX version 1.0.1.157
* AWX install method: openshift
* Ansible version 2.4.1.0 
* Operating System: centos 7
* Web Browser: Google Chrome / Firefox

##### STEPS TO REPRODUCE
Create Inventory -> Add Group -> Edit Group -> Add Group -> Add Variables (YAML/JSON) in the text area -> SAVE

##### EXPECTED RESULTS
Variables are saved in the text area and shown in the UI

##### ACTUAL RESULTS
Variables text area clears and is empty.

##### ADDITIONAL INFORMATION
Seems that for some groups it works and is saved, but for others it doesn't.

**Comment by dantheta** [comment]
I've seen this too.

Switching between details and groups tabs reloads the variables text field, and can allow you to confirm that the values were saved.

**Comment by awithrow9** [comment]
@midekra can you tell us if you still see this with a more recent version?

**Comment by dantheta** [comment]
I saw this with version 1.0.4.

**Comment by wenottingham** [comment]
Please test with 1.0.6, sorry for the delay.

**Comment by midekra** [comment]
My apologies for my late reply. But it seems to be fixed.
I'm running 1.0.6.

Thanks a bunch!
