### ISSUE TITLE
POSTing to create workflow approval node (node without UJT) ignores all_parents_must_converge

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7063]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
![all_parents](https://user-images.githubusercontent.com/9889020/82239367-abd5f200-9906-11ea-8c60-39ef86625ff8.gif)

Relates to https://github.com/ansible/awx/issues/6998

##### STEPS TO REPRODUCE
1. Create an empty workflow
2. Attempt to POST to `/api/v2/workflow_job_templates/:id/workflow_nodes/` with the following payload:

```
{
    "all_parents_must_converge": true
}
```

##### EXPECTED RESULTS
A node is created with `all_parents_must_converge` set to `true`

##### ACTUAL RESULTS
A node is created with `all_parents_must_converge` set to `false`

##### ADDITIONAL INFORMATION
The use case here is approval nodes.  In order to create an approval node in the UI we make this initial POST request to create the node.  After we have a node, we create the corresponding approval template.  If the user were to attempt to create a new approval node in the UI where `all_parents_must_converge` was set to true it would currently save but `all_parents_must_converge` would be set to false.

If this becomes problematic to fix, the UI could always issue a 3rd request to go back and PATCH the node from the first request but this would be less desirable.

**Comment by mabashian** [comment]
I'm marking this as `priority:high` since https://github.com/ansible/awx/issues/6998 was marked `priority:high`.

**Comment by ryanpetrello** [comment]
@mabashian did a fix for this get merged upstream that needs a back port, or are we still actually in `needs_devel`?

**Comment by kdelee** [comment]
We now have test coverage for this and have been testing on devel, closing as verified
