### ISSUE TITLE
Determine how to handle registry authentication for execution environments

### ISSUE THREAD

**Issue by shanemcd** [ansible/awx#7066]
This is a subtask of a larger enhancement/initiative surrounding execution environments: #5157

Execution Environments may require a credential to pull from a protected registry. Different execution environments may come from different registries. We need a way to handle the authentication process that does not involve a shared global config. Whatever we do should be secure in terms of file permissions.

**Comment by ryanpetrello** [comment]
This work will likely encompass new data model and API work to define credential types for interacting with registries, and associating the necessary credentials to defined execution environments (see: https://github.com/ansible/awx/issues/7064)

**Comment by kdelee** [comment]
Right now errors when pulling images for ContainerGroups can be rather opaque/difficult to realize that is the problem. When we switched to a registry for default images downstream this came up https://github.com/ansible/tower/issues/4402.

Would be good to figure out a less opaque way of surfacing problems when pulling images.

**Comment by AlanCoding** [comment]
@jbradberry https://github.com/ansible/awx/pull/8113 seems like it's starting toward this. It defines some credential inputs, but I don't know if it sets up injectors? And we're a ways away from this being testable I think

**Comment by AlanCoding** [comment]
This is looking more and more difficult to me. The `podman` executable on traditional installs is invoked by `ansible-runner worker`. That means that we need to send the credentials over receptor before we can apply them. These credentials are not for the `ansible-playbook` process, so that means it needs to be a part of the ansible-runner interface. It can't just be added onto the environment variables for the job.

Then, the OCP deployments will need its own way to handle this.

**Comment by AlanCoding** [comment]
I would start with quay.io (which may also work the same for dockerhub).

Although tokens would be preferable, https://docs.quay.io/api/ establishes that the pattern may be the same as username/pass, with "$oauthtoken" as the username.

It may be expecting this gets written to `~/.docker/config.json`, and how they can be implemented in the credential type injector, need to get pinned down.

**Comment by kdelee** [comment]
@rebeccahhh @shanemcd whats the status on this? I know at this point we can associate a credential with an EE, but I never got caught up on whether or not we are applying the credential to the actual container pull step

**Comment by ryanpetrello** [comment]
`state:needs_devel` is accurate here (I don't think the work has started yet to hook the credential into the container pull step)

**Comment by kdelee** [comment]
@yagomarques @rebeccahhh some things to try out during development
- [x] verify we have ability to trust an insecure registry (e.g. disable tls verify). I'm guessing there should be a "tls verify" boolean on the registry credential
- [x] Verify we can pull from quay with username/token
- [x] verify we can pull from GCR with json file token (has a dummy username + big token that is actually a json file)
- [x] verify we can pull from pulp registry provided by galaxy_ng (ping @hendersonreed @ironfroggy about how to run devel version of galaxy_ng)

**Comment by kdelee** [comment]
https://www.projectatomic.io/blog/2018/05/podman-tls/ may be of interest for reading

**Comment by hendersonreed** [comment]
For setting up the galaxy_ng dev environment, there's a setup guide [here](https://github.com/ansible/galaxy_ng/wiki/Development-Setup). If you have any questions or problems, feel free to reach out about it!

**Comment by kdelee** [comment]
@Zokormazo this issue relates to the PR https://github.com/ansible/tower-qa/issues/6342 I sent you and if we could work in a last few verification steps while you are verifying https://github.com/ansible/awx/pull/10204 I think we can close this soon.

Two notable ones are using the new `tls-verify` boolean and pulling an image from Automation Hub. If those two things were used during the Testathon, then we can probably just close this issue.

**Comment by Zokormazo** [comment]
@gamuniz and @chrismeyersfsu made the full flow during testathon: ansible-builder -> hub -> controller . It works

**Comment by Zokormazo** [comment]
Registry authentication is covered on https://github.com/ansible/tower-qa/pull/6224
For container groups we have https://github.com/ansible/awx/issues/10114
For hub push, pulling etc: https://github.com/ansible/tower-qa/issues/6342

So I'm closing this
