### ISSUE TITLE
PG_PORT variable doesn't fit 

### ISSUE THREAD

**Issue by imoes** [ansible/awx#707]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
 - Docker_Container
/usr/bin/launch_awx_task.sh
##### SUMMARY
in /usr/bin/launch_awx_task.sh
line 18 the port option is missing :
fixed line: ANSIBLE_REMOTE_TEMP=/tmp ANSIBLE_LOCAL_TEMP=/tmp ansible -i "127.0.0.1," -c local -v -m postgresql_db -U $DATABASE_USER -a "name=$DATABASE_NAME owner=$DATABASE_USER login_user=$DATABASE_USER login_host=$DATABASE_HOST login_password=$DATABASE_PASSWORD port=$DATABASE_PORT" all

**Comment by matburt** [comment]
Fixed in #762
