### ISSUE TITLE
Tune the Docker image size

### ISSUE THREAD

**Issue by JG127** [ansible/awx#7072]
##### ISSUE TYPE
 - Improvement request

##### SUMMARY
The default AWX images are huge. As a consequence they have a long download time and a long extraction time. These days the former is especially a problem for people working from home using VPN, due to the Covid virus.

The images amount to 2.5GB each. Although Docker caching will reduce the downloaded volume.

##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.7
* Operating System: Centos 7
* Web Browser: n/a

##### STEPS TO REPRODUCE

pull awx_task:11.2.0
pull awx_web:11.2.0

##### EXPECTED RESULTS

The pull commands to finish quicker due to reduced image sizes

##### ACTUAL RESULTS

These two commands take quite a long time to complete. Although the second is of course faster due to Docker caching the layers.

##### ADDITIONAL INFORMATION

The experimental Docker squash didn't make any noticeable difference.

**Comment by JG127** [comment]
Suppose I'd like to give it go myself, by rewriting the Docker files, what files should I look to ?

**Comment by ryanpetrello** [comment]
@JG127 we've _actually_ recently made a change to move to two-stage container builds, which we think will drastically help here, but it won't be out until the next major version of AWX is available:

https://github.com/ansible/awx/pull/7017
