### ISSUE TITLE
Unable to toggle host on/off as superuser

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7074]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
<img width="1490" alt="Screen Shot 2020-05-19 at 8 46 14 AM" src="https://user-images.githubusercontent.com/9889020/82327971-396c1d00-99ad-11ea-8857-e12a5f598f8c.png">
<img width="1434" alt="Screen Shot 2020-05-19 at 8 46 06 AM" src="https://user-images.githubusercontent.com/9889020/82327974-3a9d4a00-99ad-11ea-9330-c1aa1a3b2f89.png">

##### STEPS TO REPRODUCE
1. Log in as superuser
2. Create a host manually
3. Check on/off toggle in details/list view

##### EXPECTED RESULTS
To be able to toggle

##### ACTUAL RESULTS
Toggle disabled

**Comment by marshmalien** [comment]
I'm not able to reproduce this on devel. I logged in as a super_user and was able to toggle a host in an inventory host list and inventory host detail view. 
![host](https://user-images.githubusercontent.com/15881645/82482062-44ee3f80-9aa4-11ea-9976-e1352d3f098d.gif)

**Comment by mabashian** [comment]
@marshmalien thanks for looking in to this.  I'm going to close.  This was an issue with a change I made locally colliding with something that came in devel while I was gone.  I should have more thoroughly checked devel.
