### ISSUE TITLE
Survey to properly escape trailing backslash

### ISSUE THREAD

**Issue by davidtluong** [ansible/awx#7086]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Currently, AWX does not escape a trailing backslash when used with surveys.  Desired functionality would be to allow the character `\` to be at the end without needing a manual escape from the user.

**Comment by wenottingham** [comment]
Please provide more details on the desired use case here, I'm not parsing where you want this to happen.

**Comment by wenottingham** [comment]
We pass values literally, we do not have context on what the playbook might need to interpret escapes.
