### ISSUE TITLE
Approval workflow notification fails to be sent to PagerDuty

### ISSUE THREAD

**Issue by JJCella** [ansible/awx#7094]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Approval workflow job notification fails to be sent to PagerDuty (all others notif backends are working for approval notifications) No issues with Start /  Success / Failure notifications.

##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.7
* Operating System: Ubuntu 18.04 LTS
* Web Browser: Firefox 76

##### STEPS TO REPRODUCE

- Configure a new PagerDuty service
- Add a new Event API V2 Integration
- Add a new PagerDuty notification template in AWX (fill all fields but don't customize messages)
- Create a new workflow job with at least an approval node (fill all fields)
- Enable PagerDuty notification on approval
- Run the workflow job

##### EXPECTED RESULTS

The approval notification should be successfully sent

##### ACTUAL RESULTS

Notification fails to be sent (with stack trace) "Description is missing or blank"

##### ADDITIONAL INFORMATION

> 2020-05-19 10:17:25,818 ERROR    awx.main.notifications.pagerduty_backend Exception sending messages: {'status': 'invalid event', 'message': 'Event object is invalid', 'errors': ['Description is missing or blank']} (99999): []
> 2020-05-19 10:17:25,821 ERROR    awx.main.tasks Send Notification Failed {'status': 'invalid event', 'message': 'Event object is invalid', 'errors': ['Description is missing or blank']} (99999): []
> Traceback (most recent call last):
>   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/pygerduty/__init__.py", line 597, in execute_request
>     response = (self.opener.open(request, timeout=self.timeout).
>   File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
>     response = meth(req, response)
>   File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
>     return self._call_chain(*args)
>   File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
>     result = func(*args)
>   File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 400: Bad Request
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 340, in send_notifications
>     sent = notification.notification_template.send(notification.subject, notification.body)
>   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/notifications.py", line 196, in send
>     return backend_obj.send_messages([notification_obj])
>   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/notifications/pagerduty_backend.py", line 70, in send_messages
>     client=m.from_email)
>   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/pygerduty/__init__.py", line 593, in trigger_incident
>     client=client, client_url=client_url, contexts=contexts)
>   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/pygerduty/__init__.py", line 557, in create_event
>     response = self.execute_request(request)
>   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/pygerduty/__init__.py", line 603, in execute_request
>     raise BadRequest(self.json_loader(err.read().decode("utf-8")))
> pygerduty.exceptions.BadRequest: {'status': 'invalid event', 'message': 'Event object is invalid', 'errors': ['Description is missing or blank']} (99999): []
>

**Comment by wenottingham** [comment]
This should be fixed in AWX 13.0.0: https://github.com/ansible/awx/pull/7169
