### ISSUE TITLE
Integrate with Windows 

### ISSUE THREAD

**Issue by awscloudarch87** [ansible/awx#7097]
I would like to integrate my existing AWX with Windows server and do some automation, can anyone please help me with guidelines.

P.S. Automation in the sense in this scenario, start/restart/stop a service, start/restart/stop a server.

Thanks in advance for your suggestions!

**Comment by cr0cdev** [comment]
Hi!

This can be done via AWX, but understand that AWX is just a GUI for Ansible. You have to write the Ansible playbooks and roles for Windows servers.
You can find more information from here:
https://docs.ansible.com/ansible/latest/user_guide/windows_setup.html

From there you need to check the Ansible documentation to create the playbook and then setup a job in AWX to run that playbook.

**Comment by awscloudarch87** [comment]
Ok, Thank you very much for your quick response! I will give a try.
