### ISSUE TITLE
End Date & Time in Schedule is incorrectly inserted as UTC

### ISSUE THREAD

**Issue by batemanst** [ansible/awx#710]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI
- API

##### SUMMARY
End Date & Time in a Schedule is incorrectly inserted into the database as UTC without timezone conversion, which puts the schedule end date/time at a different time than intended.

Our current workaround is to specify the date/time already converted to UTC, i.e.:

Bug:

Start date: 11/21/17 - 12:00:00 CST
End date: 11/23/17 - 12:00:00 CST <---- this end date/time will actually be 06:00:00 CST in the DB

Workaround:

Start date: 11/21/17 - 12:00:00 CST
End date: 11/23/17 - 18:00:00 UTC <---- this end date/time will actually be 12:00:00 CST in the DB

##### ENVIRONMENT
* AWX version: 1.0.1.223
* AWX install method: official image
* Ansible version:  2.4.1
* Operating System: Centos 7.6
* Web Browser: Chrome/Safari

##### STEPS TO REPRODUCE

In Schedules:

1. Set a non-UTC local time zone
2. Specify an end date & time
3. Save Schedule
4. Look at the DB row or refresh the UI, the time will now show an incorrect time.

##### EXPECTED RESULTS

End date & time should be in local time, and should be inserted into the DB with time zone conversion.

##### ACTUAL RESULTS

End time is inserted directly as UTC with no time zone conversion (workaround pictured)

<img width="1333" alt="screen shot 2017-11-24 at 2 40 35 pm" src="https://user-images.githubusercontent.com/2091431/33223521-ea104314-d125-11e7-99c3-1c525d43a477.png">

<img width="612" alt="screen shot 2017-11-24 at 2 42 45 pm" src="https://user-images.githubusercontent.com/2091431/33223536-0bb8a9b6-d126-11e7-84f0-a19ca1130b93.png">

**Comment by AlanCoding** [comment]
Thanks for the report. This is on the agenda within the current development cycle.

**Comment by wenottingham** [comment]
This should be fixed if you update to the latest build. Please try that out.
