### ISSUE TITLE
manually project update doesn't synchronize galaxy roles

### ISSUE THREAD

**Issue by sugitk** [ansible/awx#7122]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When `project update` manually, it doesn't synchronize galaxy roles using requirements.yml.  

##### ENVIRONMENT
* AWX version: Tower 3.7.0
* Ansible version:  2.9.9
* Operating System: RHEL 7.8

##### STEPS TO REPRODUCE

1) Create a new project using `SCM URL` as https://github.com/sugitk/project_update_sample.git
2) Click synchronization icon
3) Check the job result, it shows that the `JOB_TAGS` was `update_git` hence the task `Install content with ansible-galaxy command if necessary` didn't work.

##### EXPECTED RESULTS

`JOB_TAGS` applied as `install_roles` and the galaxy roles can be updated

##### ADDITIONAL INFORMATION

When I create a new job template using this project and ran this JT, this `requirements.yml` worked.  Is it intentional?

**Comment by wenottingham** [comment]
Yes, we pull at runtime, not project revision update time.
