### ISSUE TITLE
Update credential details to display fields configured using cred plugins

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7127]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Credential details needs to be updated to display fields that are configured to be pulled from an external source (credential plugins).  I'm not sure that the UX has been worked out for this but we'd want to show:

1) Field name
2) Selected credential
3) Metadata (this could be multiple fields)

To set this scenario up you'd first need to create a credential and configure one of the fields to pull from an external secret store.

I'm marking this as blocked until https://github.com/ansible/awx/pull/7125 gets merged

**Comment by unlikelyzero** [comment]
need to test

**Comment by unlikelyzero** [comment]
Needs coverage

**Comment by unlikelyzero** [comment]
@akus062381 there should be enough in our existing codebase to quickly add a test to verify the Credentials/Details page's use of External Credential references

Also, need to add a visual test or visual test stub

**Comment by akus062381** [comment]
Manually tested.
Testability needed - see https://github.com/ansible/awx/issues/9687
Stubs added for coverage- see https://github.com/ansible/tower-qa/pull/6124
