### ISSUE TITLE
Users Team view: add to team

### ISSUE THREAD

**Issue by keithjgrant** [ansible/awx#7130]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
On the User Teams page, implement an "Add" button to add the user to teams. Mockup: https://tower-mockups.testing.ansible.com/patternfly/users/users-teams-add/

This is broken out from #6594

**Comment by nixocio** [comment]
Related - https://github.com/ansible/awx/issues/6593

**Comment by tiagodread** [comment]
PR already merged and tests in place

**Comment by unlikelyzero** [comment]
Hey, I don't see coverage for the dissociate case. 
All I see is 
user-tabs.spec.js
context.skip('Teams tab', function() {}) //TBI```

**Comment by tiagodread** [comment]
@unlikelyzero this PR covers association and disassociation https://github.com/ansible/tower-qa/pull/5675

**Comment by tiagodread** [comment]
PR already merged, tests in place, closing this issue.
