### ISSUE TITLE
AWX upgrade v6.0.0 to v10.0.0 - Permission denied postgres/pgdata/PG_VERSION

### ISSUE THREAD

**Issue by jklasd8899** [ansible/awx#7131]
##### ISSUE TYPE
 - Bug Report

AWX upgrade v6.0.0 to v10.0.0 - Permission denied postgres/pgdata/PG_VERSION

##### SUMMARY
Trying to upgrade AWX from v6.0.0 to v10.0.0. 
Receiving an error at this step - TASK [local_docker : Check for existing Postgres data]

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "checksum_algorithm": "sha1",
            "follow": false,
            "get_attributes": true,
            "get_checksum": true,
            "get_md5": false,
            "get_mime": true,
            "path": "/app/automation/ansible/postgres/pgdata/PG_VERSION"
        }
    },
    "msg": "Permission denied"
}

##### ENVIRONMENT
* AWX version: 6.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.3
* Operating System: Centos 7
* Web Browser:

##### STEPS TO REPRODUCE

Current AWX version v6.0.0

Checkout v10.0.0 installation AWX branch 

ansible-playbook -i inventory install.yml

 
##### EXPECTED RESULTS

Successful upgrade to AWX v10.0.0

##### ACTUAL RESULTS

Receiving an error at this step - TASK [local_docker : Check for existing Postgres data]

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "checksum_algorithm": "sha1",
            "follow": false,
            "get_attributes": true,
            "get_checksum": true,
            "get_md5": false,
            "get_mime": true,
            "path": "/app/automation/ansible/postgres/pgdata/PG_VERSION"
        }
    },
    "msg": "Permission denied"
}

##### ADDITIONAL INFORMATION

drwx------. 19 polkitd root 4096 May 22 14:27 pgdata

**Comment by ryanpetrello** [comment]
Hey @jklasd8899,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by ryanpetrello** [comment]
You might have better luck with this type of version jump just backing up your database and deploying a new version - I'd also recommend moving to the latest support version, 11.2.0.
