### ISSUE TITLE
Enforce password policy for users

### ISSUE THREAD

**Issue by davidtluong** [ansible/awx#7133]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The request is for the ability to set password policies for users for both the UI and REST API that can be set and enforced for local users.  Currently, there is no ability to define password complexity requirements for locally created users.

**Comment by kitos9112** [comment]
Hi team,

Are there plans around this feature request?

**Comment by vdealba** [comment]
Hi team, 
I have exactly the same issue. Any update?

**Comment by jainnikhil30** [comment]
similar old RFE here: https://github.com/ansible/awx/issues/1846

**Comment by wenottingham** [comment]
https://github.com/ansible/awx/pull/9999
