### ISSUE TITLE
How can I install and use NAPALM-ANSIBLE in AWX?

### ISSUE THREAD

**Issue by codesupremo** [ansible/awx#7137]
##### ISSUE TYPE
 - How can I install and use NAPALM-ANSIBLE in AWX?

##### SUMMARY

Is it possible to install and use NAPALM-ANSIBLE in AWX?

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.5
* Operating System: CentOS 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Unable to reproduce

##### EXPECTED RESULTS

To be able to use napalm_validate module

##### ACTUAL RESULTS

Unable to use napalm_validate module by NAPALM

**Comment by ryanpetrello** [comment]
Hey @codesupremo,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
