### ISSUE TITLE
uri module need to set the interpreter with virtualenv

### ISSUE THREAD

**Issue by chris93111** [ansible/awx#7138]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

jobs with uri module need to set the interpreter with virtualenv 
virtualenv = python2.7 ansible 2.7.5
connection = local

{
    "_ansible_parsed": false,
    "_ansible_no_log": false,
    "module_stderr": "/bin/sh: /usr/bin/python: No such file or directory\n",
    "changed": false,
    "module_stdout": "",
    "rc": 127,
    "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error"
}

##### ENVIRONMENT
* AWX version: 11.2
* AWX install method: docker on linux
* Ansible version:  2.7.5
* Operating System: Redhat
* Web Browser: Chrome

##### STEPS TO REPRODUCE

plays with :
  connection: local 
  virtualenv:
    python2.7
    ansible2.7.5
  use module uri

- name: Check healty server consul
  uri:
    url: "http://{{iac_consul_server}}:{{iac_consul_port}}/v1/status/leader"
  register: init_consul_serveur_health
  check_mode: false

##### EXPECTED RESULTS

use python of virtualenv

##### ACTUAL RESULTS

/usr/bin/python: No such file or directory

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/27526373/82763363-5d918900-9e07-11ea-9336-acbce65d34da.png)

**Comment by chris93111** [comment]
Hi with ansible_python_interpreter: /usr/bin/python2.7 it's work , but i don't know if is best solution

**Comment by ryanpetrello** [comment]
Yep, that's what you want.

https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html#local-playbooks

> If you set the connection to local and there is no ansible_python_interpreter set, modules will run under /usr/bin/python and not under {{ ansible_playbook_python }}. Be sure to set ansible_python_interpreter: “{{ ansible_playbook_python }}” in host_vars/localhost.yml, for example. You can avoid this issue by using local_action or delegate_to: localhost instead.
