### ISSUE TITLE
SumoLogic external logging in Ansible Tower 3.7 does not work

### ISSUE THREAD

**Issue by luckylittle** [ansible/awx#7139]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
SumoLogic collector is typically URL with token in base64 format ending with two equal signs `==`. When this is saved in Tower, the incorrect URL will be stored in `/var/lib/awx/rsyslog/rsyslog.conf` where it automatically replaces those signs with `%3D%3D`. Underlying curl used by `rsyslogd` will further try to encode it and ends up with `%253D%253D`.

##### ENVIRONMENT
* AWX version: Red Hat Tower `3.7.0`
* AWX install method: https://releases.ansible.com/ansible-tower/setup-bundle/ansible-tower-setup-bundle-3.7.0-4.tar.gz
* Ansible version:  Red Hat Ansible `2.9.7`
* Operating System on the server: Red Hat Enterprise Linux release 8.2 (Ootpa)
* Web Browser: Chrome `80.0.3987.122` (Official Build) (64-bit) on Red Hat Enterprise Linux release 8.0 (Ootpa)

##### STEPS TO REPRODUCE
1. `https://<TOWER>/#/settings/system` - LOGGING
2. Logging aggregator type: `sumologic`
3. Logging aggregator: `https://<REDACTED>.sumologic.com/receiver/v1/http/<LONG TOKEN>==`

##### EXPECTED RESULTS

Integration with SumoLogic works. Logs will appear in the SumoLogic collector.

##### ACTUAL RESULTS

Integration with SumoLogic does not work due to incorrect parsing of the URL where external logs will be sent to. Logs do not appear in the SumoLogic collector.

##### ADDITIONAL INFORMATION

`cat /var/lib/awx/rsyslog/rsyslog.conf`

```
$DebugFile <REDACTED>
$DebugLevel 2
$WorkDirectory /var/lib/awx/rsyslog
$MaxMessageSize 700000
$IncludeConfig /var/lib/awx/rsyslog/conf.d/*.conf
main_queue(queue.spoolDirectory="/var/lib/awx" queue.maxdiskspace="1g" queue.type="Disk" queue.filename="awx-external-logger-backlog")
module(load="imuxsock" SysSock.Use="off")
input(type="imuxsock" Socket="/var/run/awx-rsyslog/rsyslog.sock" unlink="on")
template(name="awx" type="string" string="%rawmsg-after-pri%")
module(load="omhttp")
action(type="omhttp" server="<REDACTED>.sumologic.com" serverport="443" usehttps="on" allowunsignedcerts="off" skipverifyhost="off" action.resumeRetryCount="-1" template="awx" errorfile="/var/log/tower/rsyslog.err" action.resumeInterval="5" restpath="receiver/v1/http/<LONG TOKEN>%3D%3D")
```

When the correct URL is hardcoded into the above file, the collection works.

**Comment by luckylittle** [comment]
@stoolrossa confirmed for me that this works like a charm in Tower `3.6.4`, so it must be related to the new robust implementation based on rsyslogd...

**Comment by rooftopcellist** [comment]
@luckylittle As you said, this is definitely a bug with how the the rsyslog.conf gets gets written.  Thank you for the detailed information.  I will have a patch up shortly.

**Comment by ryanpetrello** [comment]
I'm having trouble reproducing this in certain environments, see comment here:

https://github.com/ansible/awx/pull/7159#issuecomment-634718764

**Comment by ryanpetrello** [comment]
So in my testing, I *am* seeing that sumologic is replying with an HTTP 401, but I don't see evidence that rsyslogd or libcurl are sending a "double-escaped" `%253D` for an `=`.

Here's AWX pointed at a local TCP server with a URL path from a sumologic account @rooftopcellist and I signed up for:

```shell
~ bash-4.4$ tail -n1 /var/lib/awx/rsyslog/rsyslog.conf
action(type="omhttp" server="localhost" serverport="8000" usehttps="off" allowunsignedcerts="off" skipverifyhost="off" action.resumeRetryCount="-1" template="awx" errorfile="/var/log/tower/rsyslog.err" action.resumeInterval="5" restpath="receiver/v1/http/REDACTED%3D%3D")
```

```shell
~ tcpdump -ilo 'dst port 8000' -Avv
.5...5..POST /receiver/v1/http/REDACTED%3D%3D HTTP/1.1
Host: localhost:8000
Accept: */*
Content-Type: application/json; charset=utf-8
Content-Length: 239
```

**Comment by ryanpetrello** [comment]
Okay, dug into this a bit with @rooftopcellist and did some RFC reading, and I think this bug report is correct - we're too aggressive in our escaping of `=` as a component of the URL path.  I *don't*, however, think this issue is specific to sumologic.  @luckylittle does a diff like this resolve the issue for you?

```diff
diff --git a/awx/main/utils/external_logging.py b/awx/main/utils/external_logging.py
index 743e0f45ab..16bc8856a8 100644
--- a/awx/main/utils/external_logging.py
+++ b/awx/main/utils/external_logging.py
@@ -78,7 +78,7 @@ def construct_rsyslog_conf_template(settings=settings):
             f'action.resumeInterval="{timeout}"'
         ]
         if parsed.path:
-            path = urlparse.quote(parsed.path[1:])
+            path = urlparse.quote(parsed.path[1:], safe='/=')
             if parsed.query:
                 path = f'{path}?{urlparse.quote(parsed.query)}'
             params.append(f'restpath="{path}"')
```

**Comment by rooftopcellist** [comment]
I have updated the PR to follow this approach and it is working correctly.  

In the rsyslog.conf, I now see:
```
action(type="omhttp" server="endpoint6.collection.us2.sumologic.com" serverport="443" usehttps="on" allowunsignedcerts="off" skipverifyhost="off" action.resumeRetryCount="-1" template="awx" errorfile="/var/log/tower/rsyslog.err" action.resumeInterval="5" restpath="receiver/v1/http/<REDACTED>==")
```

and I am seeing logs in Sumologic now:

![image](https://user-images.githubusercontent.com/11698892/83048583-d109e500-a017-11ea-8204-8da462e5ae99.png)

**Comment by stoolrossa** [comment]
> Okay, dug into this a bit with @rooftopcellist and did some RFC reading, and I think this bug report is correct - we're too aggressive in our escaping of `=` as a component of the URL path. I _don't_, however, think this issue is specific to sumologic. @luckylittle does a diff like this resolve the issue for you?
> 
> ```diff
> diff --git a/awx/main/utils/external_logging.py b/awx/main/utils/external_logging.py
> index 743e0f45ab..16bc8856a8 100644
> --- a/awx/main/utils/external_logging.py
> +++ b/awx/main/utils/external_logging.py
> @@ -78,7 +78,7 @@ def construct_rsyslog_conf_template(settings=settings):
>              f'action.resumeInterval="{timeout}"'
>          ]
>          if parsed.path:
> -            path = urlparse.quote(parsed.path[1:])
> +            path = urlparse.quote(parsed.path[1:], safe='/=')
>              if parsed.query:
>                  path = f'{path}?{urlparse.quote(parsed.query)}'
>              params.append(f'restpath="{path}"')
> ```

I tested the above suggested change and this did resolve the issue occurring in our Tower installation.

The comment about it affecting more than just sumologic collectors would seem correct - we had been testing with "other" as the Logging Aggregator Type as well, for which both seem to use the omhttp module in rsyslog, which seems to use curl under the covers.  My assumption is that any external logger that uses HTTPS/HTTP as the protocol would be affected.

**Comment by kdelee** [comment]
Verified that the problematic `==` is now allowed in the URL by setting the following:
![Screenshot from 2020-06-08 13-55-24](https://user-images.githubusercontent.com/29239279/84063880-bd536c80-a98f-11ea-825c-53accf36b939.png)


Then in Settings file this is properly conserved: in `/var/lib/awx/rsyslog/rsyslog.conf`

```
action(type="omhttp" server="example.com" serverport="2342" usehttps="on" allowunsignedcerts="off" skipverifyhost="off" action.resumeRetryCount="-1" template="awx" errorfile="/var/log/tower/rsyslog.err" action.resumeInterval="5" restpath="receiver/v1/http/2342342134132==")
```
