### ISSUE TITLE
awx_* variables not working in workflow child jobs

### ISSUE THREAD

**Issue by traittinen** [ansible/awx#714]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

awx_* & tower_* variables (e.g. awx_user_name & awx_job_id) are not passed to workflow job templates. For single jobs they work as planned.

##### ENVIRONMENT
* AWX version: 1.0.1.223
* AWX install method: docker on linux
* Ansible version:  2.4.1.0
* Operating System: CentOS7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create a single playbook that uses awx_* variables, e.g.

```
  tasks:
    - name: Debugging
      debug: msg="Configured by Ansible AWX (User {{ awx_user_name }}, Job ID {{ awx_job_id }})"
```

Run the job separately vs. in a workflow. 

##### EXPECTED RESULTS

Variables should work with workflow jobs as they work with singe jobs.

##### ACTUAL RESULTS

The job fails in workflow with the following error message:

FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'awx_user_name' is undefined\n\nThe error appears to have been in '/var/lib/awx/projects/_6__junos_ansible/workflow_debug1.yml': line 9, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: Debugging\n      ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'awx_user_name' is undefined"}

**Comment by AlanCoding** [comment]
This is duplicate with #237, so I'm going to close so we're not tracking it in 2 places, but I'll go over the points you made here and make sure to comment or edit the other issue with those.
