### ISSUE TITLE
Add Webhook Support for Gogs/Gitea

### ISSUE THREAD

**Issue by imareporter** [ansible/awx#7140]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Add webhook support for Gogs/Gitea. Gitea is a fork of the Gogs project.

See: https://gogs.io/docs/features/webhook
See: https://docs.gitea.io/en-us/webhooks/

**Comment by wenottingham** [comment]
-> #6529

**Comment by erpadmin** [comment]
https://github.com/go-gitea/gitea/issues/7788
