### ISSUE TITLE
Couldnt able to connect Windows host from AWX

### ISSUE THREAD

**Issue by awscloudarch87** [ansible/awx#7141]
While trying to connect windows host from my AWX, I'm getting below error, can anyone please suggest/help. TIA

Its my EC2 instance and I have installed winrm from that windows machine and opend 5985 port at SG level.

{
    "unreachable": true,
    "msg": "plaintext: HTTPConnectionPool(host='X.X.X.X', port=5985): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc520bbd320>, 'Connection to X.X.X.X timed out. (connect timeout=30)'))",
    "changed": false
}

**Comment by wenottingham** [comment]
This repository is for issues in AWX itself. This looks like an issue with your playbook and/or networking. You're best off talking the overall Ansible community here: https://docs.ansible.com/ansible/latest/community/communication.html#communication
