### ISSUE TITLE
Missing extra variable from the preview on prompt on launch

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#7142]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Missing extra variable from the preview on prompt on launch.

![preview_missing_extra_variable](https://user-images.githubusercontent.com/9053044/82911541-017b5180-9f3a-11ea-855b-eb96824b9fe4.gif)

##### STEPS TO REPRODUCE

1 - Create a Job Template with an extra variable
![image](https://user-images.githubusercontent.com/9053044/82912601-494ea880-9f3b-11ea-9c62-41e71db4d31b.png)
2 - Select any option to `Prompt on launch` - Source Control for instance.
3 - Launch the Job Template.
4 - Verify `Preview`.

##### EXPECTED RESULTS
Extra variable to be shown as part of the preview.

##### ACTUAL RESULTS
Extra variable not shown as part of the preview.

**Comment by dsesami** [comment]
This is resolved by #7172 and can be closed when that merges.
