### ISSUE TITLE
Upgrade ansible awx to 11.2.0

### ISSUE THREAD

**Issue by pradyunvalluri** [ansible/awx#7144]
Hi

I am trying to upgrade current awx(web & task) 7.0.0 to 11.2.0 .
However after the upgrade awx web UI is not accessible.
I learned that, starting from v9.0.3 , rabbitmq has been replaced with redis..
I tried to replace rabbitmq with redis in the docker stack. However awx task is throwing following exceptions.
**"File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/connection.py", line 557, in connect
   raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 2 connecting to unix socket: /var/run/redis/redis.sock. No such file or director**"

can you please suggest what is the cause of the error. can you please suggest me setting that i need to include in the stack/compose file to solve the error.
we are using docker swam and portainer.

Let me know if you need any other details from my end.
Regards
Prabhu

**Comment by ryanpetrello** [comment]
Hey @pradyunvalluri,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
