### ISSUE TITLE
Editing a schedule results in a NaN error on the start date

### ISSUE THREAD

**Issue by masbahnana** [ansible/awx#7145]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Editing a schedule 
![Screenshot_2020-05-26 Ansible AWX](https://user-images.githubusercontent.com/35573203/82923003-3dcaa400-9f72-11ea-90f2-42672d873b3a.png)

##### ENVIRONMENT
* AWX version: latest
* Operating System: mac
* Web Browser: chrome

##### STEPS TO REPRODUCE
1 - I create a job template
2 - I try to editing 

##### EXPECTED RESULTS
Save the schedule normally 

##### ACTUAL RESULTS

Error in the screenshot

**Comment by unlikelyzero** [comment]
@NatOps would you mind filling in your browser and OS version more specifically? The functionality surround the startdate takes into account the browser's date IIRC

**Comment by mabashian** [comment]
We're going to need more information about how the schedule was created initially so that we can reproduce locally

**Comment by masbahnana** [comment]
@unlikelyzero I use MacOs Catalina version 10.15.4 and the browse is Firefox version 76.0.1.

**Comment by masbahnana** [comment]
@mabashian I followed:
1) Views -> Schedules: I create the schedule. 
2) Views -> Schedules -> Click on my schedule and click in edit e the NaN error appears in Start date/time*

**Comment by mabashian** [comment]
OK I know I've seen this bug before but now I can't reproduce.  Also, the datetime-local input isn't supported in FF currently: https://bugzilla.mozilla.org/show_bug.cgi?id=1306217.  As a result, the field is just a text input in FF.  I'm inclined to leave this be until PF implements a date/time picker: https://github.com/patternfly/patternfly-react/issues/4504

At that point, this will probably go away...

**Comment by marshmalien** [comment]
PatternFly Status Update:

* They released a beta date picker component upstream - [date picker docs](https://www.patternfly.org/v4/components/date-picker/react)
* Their next priority is the [date component cleanup issue](https://github.com/patternfly/patternfly-react/issues/5057) with target date of 11.18.2020. 
* The PF React [time picker issue](https://github.com/patternfly/patternfly-react/issues/4731) is scheduled for 12.09.2020 
* The PF React [date range picker issue](https://github.com/patternfly/patternfly-react/issues/4732) is scheduled for 12.09.2020

PF-React Date and Time component tracking issue: https://github.com/patternfly/patternfly-react/issues/4711

**Comment by unlikelyzero** [comment]
@marshmalien will the datetime picker include this functionality? https://github.com/ansible/awx/issues/5524

**Comment by Hetti** [comment]
I also just encountered this bug.
By editing a schedule, NaN is shown as date.
Browser: 86.0.1 (64-Bit) on Arch Linux
AWX 17.1.0

**Comment by mabashian** [comment]
See https://github.com/ansible/awx/pull/10291.  We've fundamentally changed these fields and this should be addressed in the next release.
