### ISSUE TITLE
Add load loading state to JobTypeRedirect

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#7156]
This issue is a place-holder to be explored,  related to the comment below:

https://github.com/ansible/awx/blob/d42f57d726c74d1f74c7114f522e15fc72d706a4/awx/ui_next/src/screens/Job/JobTypeRedirect.jsx#L70

**Comment by mabashian** [comment]
Closing - this has been addressed

**Comment by nixocio** [comment]
@mabashian, Thanks for looking those issues with `TODO` I will send a PR to remove the `TODO` from the code basis.

**Comment by unlikelyzero** [comment]
@nixocio assigning to you to close

**Comment by nixocio** [comment]
@unlikelyzero, I verified the code, and `TODO`  was already removed. Closing this one.
