### ISSUE TITLE
Add status from the websockets for JobDetail

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#7157]
This issue is a place-holder to be explored,  related to the comment below:

https://github.com/ansible/awx/blob/d42f57d726c74d1f74c7114f522e15fc72d706a4/awx/ui_next/src/screens/Job/JobDetail/JobDetail.jsx#L126

**Comment by mabashian** [comment]
Yea this is still an issue - the status icon doesn't update dynamically on the job output page

**Comment by unlikelyzero** [comment]
Can close alongside the merge of 5501

**Comment by nixocio** [comment]
This issue was addressed by https://github.com/ansible/awx/pull/8726

**Comment by unlikelyzero** [comment]
https://github.com/ansible/awx/pull/8726#issuecomment-772746083
