### ISSUE TITLE
Improve error handling for AddResourceRole

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#7160]
This issue is a place-holder to be explored, related to the comment below:

https://github.com/ansible/awx/blob/1b1a93dd4bd473670f46f134938dc67daf998946/awx/ui_next/src/components/AddRole/AddResourceRole.jsx#L131

**Comment by mabashian** [comment]
Confirmed that this error is still unhandled

**Comment by nixocio** [comment]
This issue is now fixed.
