### ISSUE TITLE
Improve error handling for useSteps

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#7164]
This issue is a place-holder to be explored, related to the comment below:
https://github.com/ansible/awx/blob/1b1a93dd4bd473670f46f134938dc67daf998946/awx/ui_next/src/components/LaunchPrompt/useSteps.js#L21

**Comment by unlikelyzero** [comment]
@nixocio does this need to be closed?

**Comment by mabashian** [comment]
Yea this has been addressed.  Closing
