### ISSUE TITLE
[ui_next] Template with ask-variables-on-launch opens up the 'Prompts' modal dialog, however, 3 modal footer buttons: 'Next', 'Back' and 'Cancel', needs to be marked for translations

### ISSUE THREAD

**Issue by sshedmake** [ansible/awx#7170]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
With Japanese (dummy translation) google-chrome, Template with ask-variables-on-launch opens up the 'Prompts' modal dialog/wizard, however, 3 modal footer buttons: 'Next', 'Back' and 'Cancel', appears in English (instead of Japanese)

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: docker on linux
* Ansible version:  2.10.0.dev0
* Operating System: Fedora 31
* Web Browser: google-chrome

##### STEPS TO REPRODUCE
1. Do a successful login to the ui_next interface in the preferred language (say Japanese)
2. Navigate to 'Templates > Demo Job Template > Edit Details' screen
3. For template-ask-variables-on-launch, select 'Prompt on Launch' checkbox
4. Click 'Save'
5. From 'Templates > Demo Job Template > Details' screen, click 'Launch'
6. 'Prompts' modal dialog/wizard opens up
7. Observe the text on 3 footer buttons: 'Next', 'Back' and 'Cancel'

##### EXPECTED RESULTS
Content should appear in Japanese

##### ACTUAL RESULTS
Text appears in English

##### ADDITIONAL INFORMATION
1. Screenshot higlighting, 3 modal footer buttons of 'Prompts' dialog: 'Next', 'Back' and 'Cancel', appearing in English at 'Templates > Demo Job Template > Details' screen, with Japanese google-chrome:
![output](https://user-images.githubusercontent.com/12151785/83052720-58357800-a06d-11ea-8417-57d02716924a.gif)

<!-- Include any links to s

**Comment by dsesami** [comment]
@sshedmake can you verify this has been marked as translated?

**Comment by sshedmake** [comment]
@dsesami , yep verified that, the said strings have been now marked as translatable strings.

Here's how:

1. Screenshot showing said strings with dummy Japanese translation (with Japanese google-chrome)

![7170_prompts-modal_footer-butons_now_marked_2](https://user-images.githubusercontent.com/12151785/94543343-933bf800-0267-11eb-9117-466c56a735cb.gif)
