### ISSUE TITLE
awx-cli: add support to modify http_method for webhook notification_templates

### ISSUE THREAD

**Issue by mdinwoodie** [ansible/awx#7173]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Currently, the http_method field for webhook notification_templates isn't an option to modify using awx-cli. This RFE is to add support for modifying this field with awx-cli.

**Comment by AlexSCorey** [comment]
@mdinwoodie You can modify the notification_cofiguration, in which you can modify the http method

**Comment by AlexSCorey** [comment]
I believe that this issue is resolved as the user can modify the `notification_configuration` including the HTTP method in awx cli.
