### ISSUE TITLE
Is it possible to add a subpath to awx url ?

### ISSUE THREAD

**Issue by stephle** [ansible/awx#7179]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - Installer

##### SUMMARY
Is it possible to add a subpath to awx url ?

##### ENVIRONMENT
* AWX version: 2.9.7
* AWX install method: docker on linux
* Ansible version:  2.9.9-1
* Operating System: centos8
* Web Browser: firefox

##### ADDITIONAL INFORMATION
Is it possible to change awx default url from http://myhost to http://myhost/subpath/ ?
Many thanks

(I hope it's the good place to ask, sorry if it's not)

**Comment by ryanpetrello** [comment]
Hey @stephle,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

You could *probably* do something like this by monkeying around with AWX's nginx configuration, but it's not something that's really supported out of the box (and it's hard to say how things like the UI would react to it, as there's likely hardcoded URL `/api/v2/` paths in multiple places).
