### ISSUE TITLE
Add option to make job execution directories created in /tmp world readable

### ISSUE THREAD

**Issue by LukWe99** [ansible/awx#7180]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

AWX creates a job execution directory inside the awx_task container located in /tmp for every single job execution. These directories named /tmp/awx_<job_id>_xxxxxxxx are created with 0700 and root:root permissions. Therefore only the root user can read the playbook contents inside this directory. This causes issues when working with e.g. the stat module delegated to localhost (which is the awx_task container in this case) as non-root user. So I would appreciate a possibility to create these directories in /tmp with 0755 permissions. 

##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.7
* Operating System: not relevant
* Web Browser: not relevant

##### STEPS TO REPRODUCE

I added my deployment user inside awx_task container. This user is used to connect to the destination host to execute the Playbook there. 
Inside the playbook (which may not be edited by me) the stat module is used to gather stats about a file inside the playbook directory (using the playbook_dir variable). 

##### EXPECTED RESULTS

Stat module returning stats about the file. 

##### ACTUAL RESULTS

As the playbook is copied to a directory /tmp/awx_<job_id>_xxxxxxxx with 0700 and root:root permissions before execution, my non-root deployment user is not able to gather stats about a file inside this playbook. Therefore the stat module returns a "Permission denied" error and no stats about the file. 

##### ADDITIONAL INFORMATION

To solve the Problem I would suggest to add an option inside AWX to set the permissions for the temporary job execution directories (e.g. to 0755 instead of 0700). So AWX should then create the /tmp/awx_<job_id>_xxxxxxxx directories with the given permissions (e.g. 0755 instead of 0700).

**Comment by wenottingham** [comment]
I'm not 100% sure what you're trying to do, but this isn't the right solution. We use process isolation to isolate playbooks from each other; if you're trying to peek in the runtime playbook repo from outside while in the container, that's not a supported feature.
