### ISSUE TITLE
RFE: Customize payload for Test Notification

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#7181]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Some customers restrict the endpoint for webhook notifications to only allow specific payloads. Allowing for custom payloads will allow customers to get around this potentially failing due to that restriction when they would see a failure with a test, but a success when the actual notification fires. 

An alternative to allowing users to customize this would be to expose what we are sending to enable users to allow that at the webhook endpoint.

Example error:
```
2020-05-27 17:57:10,314 ERROR    awx.main.notifications.webhook_backend Error sending notification webhook: [{"message":"Unexpected parameter encountered during deserialization: body at [line:1, column:11]","errorCode":"JSON_PARSER_ERROR"}]
```

**Comment by ryanpetrello** [comment]
I think we're unlikely to build a custom thing for this - it might be better to just document *what* the default payload is.

**Comment by elyezer** [comment]
As mentioned by https://github.com/ansible/awx/issues/7181#issuecomment-636083151, the solution to this would be updating the docs and that is now done. With that we can consider this as being done and verified.
