### ISSUE TITLE
Confusing JT activity stream entry when canceling a job

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#719]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Canceling a job results in an activity stream entry for its related job template, although the user was not editing the JT.

##### ENVIRONMENT
* AWX version: 1.0.1
* AWX install method: docker for mac
* Ansible version:  N/A
* Operating System:
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Launch a job template. Cancel the job it spawns. Inspect activity stream for job templates.

##### EXPECTED RESULTS

No entry.

Maybe a related entry for the job model?

##### ACTUAL RESULTS

Got this entry in the UI by user "System":

```json
{
 "current_job": [
  "2017-11-21 20:20:39.540844+00:00-74-successful",
  null
 ],
 "last_job": [
  "2017-11-21 20:11:50.543293+00:00-50-canceled",
  "2017-11-21 20:20:39.540844+00:00-74-successful"
 ],
 "last_job_failed": [
  true,
  false
 ],
 "last_job_run": [
  "2017-11-22 01:53:54.496975+00:00",
  "2017-11-22 01:54:22.307195+00:00"
 ],
 "status": [
  "running",
  "successful"
 ]
}
```

In the API:

https://gist.github.com/AlanCoding/48ea62f3b7293fb102b45086843f9ef0

##### ADDITIONAL INFORMATION

N/A

**Comment by ryanpetrello** [comment]
Fixed in 1.0.7
