### ISSUE TITLE
Invalid HTTP request when Conjur credential secret has a space in the name

### ISSUE THREAD

**Issue by AndrewCopeland** [ansible/awx#7191]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Invalid HTTP request when Conjur credential secret has a space in the name

##### STEPS TO REPRODUCE

Create a conjur credential containing a space.
When retrieving the credential a 404 is returned from conjur.
The reason for this is because the conjur credential plugin url encodes the secretID with a `+` however conjur is expecting a `%20`.

##### EXPECTED RESULTS

To get back the credential content.

##### ACTUAL RESULTS

AWX fails to retrieve the credential and a 404 is returned.

**Comment by ryanpetrello** [comment]
Hey @AndrewCopeland,

Mind giving this PR at try?

https://github.com/ansible/awx/pull/7200

**Comment by Tovli** [comment]
Hi,
Can you say when will this fix be released? what version could we see it in?

**Comment by Tovli** [comment]
This is related to:
https://github.com/ansible/awx/pull/7249

**Comment by ryanpetrello** [comment]
@Tovli,

https://github.com/ansible/awx/pull/7214/

**Comment by Tovli** [comment]
Thanks. So we should see it in version 12.
That's great.
Any date/month that you plan to release this version in?

**Comment by ryanpetrello** [comment]
Hey @Tovli,

Probably somewhere in the coming weeks.  I'd say "likely by the end of June".

**Comment by Tovli** [comment]
@ryanpetrello 
I actually see a release of 12.0.0 but this issue is open
Wasn't it part of 12.0.0 after all?

**Comment by ryanpetrello** [comment]
Hey @Tovli,

The changes in question should be in the 12.0.0 release.  We keep issues open until we've done actual per-issue verification on our end (that's what the `state:needs_test` label on this issue represents).

**Comment by one-t** [comment]
Tested - this is now working as expected
