### ISSUE TITLE
BUG: Azure CLI commands doesn't work in AWX virtenv,  

### ISSUE THREAD

**Issue by Sreenadh8** [ansible/awx#7195]
##### ISSUE TYPE
 Azure CLI commands doesn't work in AWX virtual environment

##### SUMMARY

Considering the fact that Ansible doesn't have all the module for Azure, we need to run few Azure CLI commands, hence CLI installed in AWX task container. But unable to execute the playbooks from awx 9.3.0 web and gets the following described error.

sample playbook:

              - name: Determine whether Azure backup enabled or not.
                shell: az backup protection check-vm --vm-id "{{id}}"
                register: check_backup
                delegate_to: localhost

  Error while executing task:

/usr/bin/python3.6: No module named azure.cli.__main__; 'azure.cli' is a package and cannot be directly executed

##### ENVIRONMENT
* AWX version: 9.3.0
* AWX install method:  docker on linux,
* Ansible version:  2.9.5
* Operating System: CentOS 7.5
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

* log-in to Docker task container
* pip3 install azure-cli
* write a simple azure playbook with azure cli commands and execute it from AWX GUI.

##### EXPECTED RESULTS

Should be able to execute Azure commands from AWX VirtEnv

##### ACTUAL RESULTS

/usr/bin/python3.6: No module named azure.cli.__main__; 'azure.cli' is a package and cannot be directly executed

##### ADDITIONAL INFORMATION

Please help us to fix this...or provide a workaround

**Comment by wenottingham** [comment]
see https://github.com/ansible/awx/issues/5453
