### ISSUE TITLE
Add an option for SCM to get last known working revision version

### ISSUE THREAD

**Issue by Saurabh-Thakre** [ansible/awx#7197]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Add an option as checkbox/option for **Projects** to select **last known working version**. It will give flexibility as to have an option If the SCM is failing for any sort of reason and we're not able to launch the Job. Because Job will fail as well with an error `project_update failed for..`

**Comment by wenottingham** [comment]
This isn't really practical.

Any node may not have a version checked out, so 'last known working' cannot be a global known state. Plus then you have to get into the semantics of what the last known state is working for - is it that it's able to be checked out? That the job ran? If multiple jobs exist in the project, which jobs results drive this?
