### ISSUE TITLE
AWX Project is not updating automatically new file from GitHub

### ISSUE THREAD

**Issue by awscloudarch87** [ansible/awx#7199]
Today I have already one YAML file in my GitHub by referring that I have created a new Project and then while creating a new template I can see that first YAML as playbook.

Now I have created my second YAML file in same GitHub and when I try to create a new template the second YAML file is not visible which is unexpected.

As a workaround, after 2nd file creation when I create a fresh project and then create new template then only I can see first and second playbook. why cant we continue with same project for all new YAML Files? 

Is it something that I'm missing or always when I create a new YAML file in GitHub every next time I need to create a new project? can you anyone please confirm if this is a bug or I missed some options. kindly confirm. TIA.

**Comment by wenottingham** [comment]
You need to update the project, either on a scheduled basis, on launch, or by clicking the update button. See https://docs.ansible.com/ansible-tower/latest/html/userguide/projects.html for downstream documentation.

In any case, this repo is for bug reports with AWX itself. Usage questions are best discussed on the awx-project list or ansible-awx IRC channels. See https://github.com/ansible/awx/#get-involved
