### ISSUE TITLE
RFE: Allow specifying variables (inventory_hostname) in "PATH TO SECRET" in Machine Credential with External Vault Credential

### ISSUE THREAD

**Issue by hiyokotaisa** [ansible/awx#7211]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

When creating a machine credential using a HashiCorp Vault Secret Lookup a `PATH TO SECRET` and a `KEY NAME` must be specified. These values cannot contain variables (such as inventory_hostname). This means that every machine would need to have a credential defined within Tower which is not scalable when there are hundreds or thousands of machines being managed by AWX. Other external vault types work the same although the fields that need to be filled in when creating the machine credential are named different.

The request is to be able to utilize variables when looking up credentials from an external vault. 

E.g. setting `PATH TO SECRET` to `project/test/{{ inventory_hostname}}`

![Screenshot from 2020-06-02 10-28-10](https://user-images.githubusercontent.com/4246532/83469910-d81f7000-a4bb-11ea-829e-56426a6e1b10.png)

Currently, AWX is not able to use variables in there.

**Comment by wenottingham** [comment]
The credential is not looked up per machine, that is not how this works.

A credential plugin is used to pass a single credential to the playbook, used for all machines.

**Comment by wenottingham** [comment]
See #286

**Comment by TheSecMaven** [comment]
commented on 286. this makes AWX hard to use at a scale of thousands of servers.
