### ISSUE TITLE
Replace route config function with exported array

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#7215]
## SUMMARY
When the next major version of lingui is released and we upgrade to it, change [`src/routeConfig.js`](https://github.com/ansible/awx/blob/devel/awx/ui_next/src/routeConfig.js) so that it imports the `i18n` /  translation helper directly and exports an array instead of a function.

## Additional Information
[When lingui3 lands, we'll be able to import the translation util directly](https://github.com/lingui/js-lingui/issues/390#issuecomment-438173038) instead of needing to render a component first.

**Comment by mabashian** [comment]
blocked by #8356

**Comment by jakemcdermott** [comment]
This is done - we now directly import translation functions. We kept the route config as an exported function to handle some RBAC scenarios for navigation controls.
