### ISSUE TITLE
API Endpoint or Module to operate on Synchronize inventory source button

### ISSUE THREAD

**Issue by devcon6** [ansible/awx#7217]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Is there any way that we could trigger inventory source to synchronize besides:

- the explicit button click
- the project being refreshed if we allowed update when project is updated 

Maybe an API endpoint that could trigger that or Tower module to call in a Playbook ?

**Comment by wenottingham** [comment]
This has always been part of the API, if you open the browser console and watch the REST requests when you click the button you can see what's going on.

As a usage question, this is better targeted for the mailing list or IRC channel - see https://github.com/ansible/awx#get-involved for details.

**Comment by devcon6** [comment]
Thank you for the help.
I've proceeded as you suggested by calling this endpoint **/api/v2/inventory_sources/{id}/update/** with **POST** method (empty content) and I've managed to trigger the execution of the Synchronize button.
Many thanks.
