### ISSUE TITLE
Clicking directly on text in Permissions modal doesn't work

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#7220]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
![Screenshot_20200602_134825](https://user-images.githubusercontent.com/19942822/83552467-d5cb0f00-a4d7-11ea-8515-aaec528a1c33.png)

If I try to click anywhere else in the "Demo Job Template" box, it works mostly normally.
However, clicking the text itself (see mouse position in screenshot) doesn't check/uncheck the box for some reason.

##### ENVIRONMENT
* Operating System: Fedora
* Web Browser: Chrome

##### STEPS TO REPRODUCE
1. Create a user and a template or something
2. Try to go to the User -> Access -> add permissions
3. Get to the step in the screenshot above and try clicking in different areas of the checkbox block.

##### EXPECTED RESULTS
Clicking anywhere in the block will set/unset the checkbox

##### ACTUAL RESULTS
Clicking the text doesn't set/unset the checkbox.

**Comment by unlikelyzero** [comment]
@dsesami do you mind retesting this?

**Comment by dsesami** [comment]
This is still a problem as of 9/16

**Comment by unlikelyzero** [comment]
closing for https://github.com/ansible/awx/issues/8852 because it contains an additional side effect
