### ISSUE TITLE
[Foreman] (Satellite 6) source host_filters no longer working

### ISSUE THREAD

**Issue by jadestorm** [ansible/awx#7225]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
In upgrading from 11.0.0 to 11.2.0, I found that my inventory source host_filters were no longer being honored.  Instead, they were pulling the entire list of hosts from Foreman as if no filter was applied.  (for example host_filters: 'os = windows'  should only pull windows hosts)

##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: docker on linux
* Ansible version:  [whatever is in the task container]
* Operating System: RHEL7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Set up an Inventory with a Red Hat Satellite 6 source as you normally would.
2 In Source Variables put something like:
```
---
host_filters: 'os = windows'
```
3. Run the source pull -- you'll see it ignores the filter completely and pulls all of your hosts from Foreman.

##### EXPECTED RESULTS

I expect it to honor the host_filters setting as it did in 11.0.0.  =)  I should have ended up with a handful of Windows hosts we have in Foreman.

##### ACTUAL RESULTS

I got all hosts from Foreman, Linux and Windows alike.

##### ADDITIONAL INFORMATION

I didn't see anything in the debug output that looked relevant.

**Comment by jadestorm** [comment]
(BTW I looked at "blame" on the foreman.py inventory plugin and I see nothing that has changed recently that seems related)

**Comment by jadestorm** [comment]
Also rolling back to 11.0.0 immediately fixed the issue.

**Comment by jainnikhil30** [comment]
@jadestorm this is a known issue in the foreman plugin that awx uses. Already fixed in the plugin 

https://github.com/theforeman/foreman-ansible-modules/pull/823

Waiting for the release of respective collection, so that it can be used in awx.

**Comment by jadestorm** [comment]
Fantastic!  Thank you!

**Comment by jladdjr** [comment]
* Just merged a change that pins awx to the 0.8.1 version of the foreman collection (that was released this morning), and
* .. confirmed that 0.8.1 includes the [fix for host_filters ](https://github.com/theforeman/foreman-ansible-modules/pull/823)

**Comment by jladdjr** [comment]
cc @kdelee

**Comment by kdelee** [comment]
confirmed on awx 12.0.0 this is now working, closing (adding test coverage downstream)
