### ISSUE TITLE
Adding personnal credentials

### ISSUE THREAD

**Issue by saez0pub** [ansible/awx#723]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
When I run a tasks, I want to be prompted for the user running the playbook

##### ENVIRONMENT
* AWX version: 1.0.1.225
* AWX install method: docker on linux
* Ansible version:  2.4.1.0 
* Operating System: Linux
* Web Browser: Firefox, Chromium

##### STEPS TO REPRODUCE

* When I create a credential entry
* At the username entry
* I want to prompt at runtime

##### EXPECTED RESULTS

At the launch of a task, The user name is prompted because I can't predict wich sername will be used and the connection oto the server muste be with a personnal user for security reasons.

##### ACTUAL RESULTS

I can't choose the username without creating a credential entry foreach user.

**Comment by wenottingham** [comment]
This is a fundamental restriction on how Tower's credentials are implemented; sorry.

May be considered as part of https://github.com/ansible/awx/issues/286

**Comment by olokolo250** [comment]
Don't understand your reply wenottingham, those two links in #286 provide the basics about the AWX credentials, dont see any possibility to add more ssh keys for one user. If its possible the docs are just not explanatory enough.

**Comment by wenottingham** [comment]
To be more clear: this *can not work* with how credentials are currently implemented, period. #286 is about how credentials could be changed in the future... that request may be considered then.
