### ISSUE TITLE
Allow search for actions performed by user in activity stream

### ISSUE THREAD

**Issue by davidtluong** [ansible/awx#7230]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Right now there's no way to search for actions performed by a certain user in activity stream.  The request is for there to be a field that you can search for by username and return the actions performed by the user.

**Comment by wenottingham** [comment]
You can tack `actor__username:<username>` into the URL bar and this will work.

This should be fixed in the UI rewrite to be supported in the search widget.

**Comment by mabashian** [comment]
This was addressed in #9083 

<img width="1503" alt="Screen Shot 2021-02-04 at 11 27 04 AM" src="https://user-images.githubusercontent.com/9889020/106923341-f50be300-66db-11eb-8b1b-077d33fa2a7f.png">
