### ISSUE TITLE
Slack notification and slack task "delegate_to: localhost" fail in awx docker container

### ISSUE THREAD

**Issue by soloman747** [ansible/awx#724]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Cannot send slack notifications or use the slack ansible module in playbooks. 

##### ENVIRONMENT
* AWX version: 1.0.1.231
* AWX install method: docker on linux
* Ansible version:  2.4.1.0
* Operating System: Ubuntu
* Web Browser: Firefox

##### STEPS TO REPRODUCE
Simply create a slack channel, create a webhook integration, and attempt to use it as a notification, or create a playbook with a slack module and try to run it. It works just fine when running the playbook via the host machine, but it never completes from within the docker container.

##### EXPECTED RESULTS

Both the notification test from within the AWX ui and the playbook with a slack module task should work.

##### ACTUAL RESULTS

The notification test failed. The playbook with the slack module task failed. The playbook succeeded using "ansible-playbook" command on the host machine, with a "delegate_to: localhost."

**Comment by matburt** [comment]
It sounds like perhaps the service inside the container can't access the slack services? I can't seem to reproduce this and things are working fine here.

Can you provide some more details on whether services running in your containers are able to access the internet?

**Comment by soloman747** [comment]
Services running inside the container are able to access the internet just fine. I tested by performing curl requests from the web and the task containers to multiple internet urls, and they all work. Another test I performed was temporarily changing the hosts file entry for localhost to the ip of the host, rather than the 127.0.0.1 loopback of the container. That works as well. I also attempted creating a webhook notification to a slack notification job template I created. I have it set up to send a notification on success or failure to a slack channel. The job template works when I run it manually. The role works when I run it manually from command line. The webhook notification, however, does not work. 

I am willing to provide you with whatever information or data is necessary to resolve the problem, just send me a list of things to collect. I am currently at the hospital for the birth of my child but I'll get back to you as soon as humanly possible.

**Comment by wenottingham** [comment]
Apologies for not responding sooner. Is this still happening in current releases?

**Comment by soloman747** [comment]
No. I think you can close this out.


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Bill Nottingham <notifications@github.com> Date: 6/1/18  12:47 PM  (GMT-06:00) To: ansible/awx <awx@noreply.github.com> Cc: soloman747 <steven_king@inbox.com>, Author <author@noreply.github.com> Subject: Re: [ansible/awx] Slack notification and slack task "delegate_to:
  localhost" fail in awx docker container (#724) 
Apologies for not responding sooner. Is this still happening in current releases?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/ansible/awx/issues/724#issuecomment-393958140","url":"https://github.com/ansible/awx/issues/724#issuecomment-393958140","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ansible/awx","title":"ansible/awx","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ansible/awx"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wenottingham in #724: Apologies for not responding sooner. Is this still happening in current releases?"}],"action":{"name":"View Issue","url":"https://github.com/ansible/awx/issues/724#issuecomment-393958140"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [ansible/awx] Slack notification and slack task \"delegate_to: localhost\" fail in awx docker container (#724)",
"sections": [
{
"text": "",
"activityTitle": "**Bill Nottingham**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@wenottingham",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ansible/awx\",\n\"issueId\": 724,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"ansible/awx\",\n\"issueId\": 724\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/ansible/awx/issues/724#issuecomment-393958140"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 280183784\n}"
}
],
"themeColor": "26292E"
}
