### ISSUE TITLE
500 error on unauthenticated HTTP GET to nested workflow endpoint

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#7243]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Not a huge deal, just something I noticed while debugging some unrelated test failures: If you make a GET request to ` api/v2/workflow_job_template_nodes/n/create_approval_template/` when unauthenticated, you'll get a 500 instead of a 401. It seems to work fine if you're logged in.

##### STEPS TO REPRODUCE
- make a workflow with nodes
- log out
- open browser dev tools and network tab
- visit ` api/v2/workflow_job_template_nodes/n/create_approval_template/` in api browser

##### EXPECTED RESULTS
401

##### ACTUAL RESULTS
500

##### ADDITIONAL INFORMATION
![Screenshot from 2020-06-03 19-11-23](https://user-images.githubusercontent.com/9753817/83697865-08efca00-a5ce-11ea-9d0c-0173751041df.png)

**Comment by wenottingham** [comment]
Can you grab the server error from the logs?

**Comment by jakemcdermott** [comment]
```
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/rest_framework/views.py", line 493, in dispatch
    self.initial(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/rest_framework/views.py", line 411, in initial
    self.check_permissions(request)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/api/views/__init__.py", line 3076, in check_permissions
    if not request.user.can_access(models.WorkflowJobTemplate, 'read', obj):
AttributeError: 'AnonymousUser' object has no attribute 'can_access'
```

**Comment by kdelee** [comment]
We now correctly get a 401, closing as verified
