### ISSUE TITLE
Registered variable value not available when running on isolated node

### ISSUE THREAD

**Issue by harkanwalSingh** [ansible/awx#725]
##### ISSUE TYPE

 - Bug Report
 

##### COMPONENT NAME

 - API
 
##### SUMMARY

I am not able to use the registered task value when executed playbook using isolated node functionality.
##### ENVIRONMENT
* AWX version: 3.4.1
* AWX install method:  docker on linux,
* Ansible version:  2.4
* Operating System: Oracle Linux
* Web Browser: Chrome

##### STEPS TO REPRODUCE

---
- hosts: all
  connection: local

  tasks:

    - name: Include user credentials
      include_vars:
       dir: 'vars'
       files_matching: "{{ inventory_hostname}}.yml"

    - name: Check Configure Extended access list
      tags:
           - acl
      ios_config:
        provider: "{{ cli_n }}"
        match: exact
        parents:
             - ip access-list extended ABC
        lines:
             - permit tcp 192.168.102.0 0.0.0.255 any eq www
           
        before: "no ip access-list extended ABC"
      check_mode: yes
      register: Result_A

    - debug:
        msg: "{{ Result_A }}"

##### EXPECTED RESULTS

Registered variable key value pair.
##### ACTUAL RESULTS
TASK [debug] *******************************************************************17:17:25
83
ok: [10.1.2.2] => {

    "msg": "Hello world!"

}

Registered variable value not retrieved when running playbook on ISOLATED instance..
##### ADDITIONAL INFORMATION
It works fine with Normal instance. i.e. using Tower/controller node.

**Comment by wenottingham** [comment]
Please upload the full playbook log.

**Comment by wenottingham** [comment]
Also, what AWX version? `3.4.1` is only a version if you're a time traveler here from the future.

**Comment by wenottingham** [comment]
Closing, please reopen with requested info  when available.
