### ISSUE TITLE
AWX Container fail to start,  pull access denied for ansible/awx 

### ISSUE THREAD

**Issue by iamraj007** [ansible/awx#7251]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by ryanpetrello** [comment]
duplicate of https://github.com/ansible/awx/issues/7246
