### ISSUE TITLE
Implement `Replace` functionality for credential passwords

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7256]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
<img width="517" alt="Screen Shot 2020-06-04 at 2 43 46 PM" src="https://user-images.githubusercontent.com/9889020/83798242-f9c25800-a671-11ea-8ab8-58b0583e82b7.png">

In the old UI, password fields in the credential subform are disabled on edit and we force the user to click this replace button in order to enable it and make a change.

@wenottingham @trahman73 is this a UX pattern that we want to carry over to the new app?  Right now the field looks like:

<img width="473" alt="Screen Shot 2020-06-04 at 2 48 10 PM" src="https://user-images.githubusercontent.com/9889020/83798579-75240980-a672-11ea-91fb-bb62d7743ead.png">

and the user can type in the input to overwrite:

<img width="482" alt="Screen Shot 2020-06-04 at 2 48 18 PM" src="https://user-images.githubusercontent.com/9889020/83798605-7ead7180-a672-11ea-8d79-b01312e2fe3c.png">

If we do want it - is it critical for an initial release?

**Comment by mabashian** [comment]
Actually @jakemcdermott brought up a good point - maybe this button is used to remove a value from the field if necessary.  Not all the password fields are required so there is a use case for needing to remove a password but not replace it.

**Comment by trahman73** [comment]
After our internal discussion, it seems we would want to carry over the same UX. Just want to make sure we have tooltips with explanation over the action icons. @wenottingham can let us know if this needs to be part of the initial release.

**Comment by mabashian** [comment]
OK so after looking at the old UI, I think this is how the button works.

1) When the page is initially loaded and the user hasn't interacted with the field the tooltip on the button says `Replace`.
2) Clicking the button when it says `Replace` sets the value of the field to an empty string
3) The button now says `Revert`
4) Clicking the button when it says `Revert` sets the value of the field back to it's initial value (which I think is always `$encrypted$`

Note that this button should only appear when _editing_ the credential.  It should not appear when adding.

**Comment by tiagodread** [comment]
We had a failure related to this change, which I'll be working on before we close the issue

**Comment by tiagodread** [comment]
Fixed, closing
