### ISSUE TITLE
Install fails because there is no awx image on docker hub

### ISSUE THREAD

**Issue by kaf3773** [ansible/awx#7259]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

As a result of the change made yesterday of

"Moved to a single container image build instead of separate awx_web and awx_task images. The container image is just awx (https://github.com/ansible/awx/pull/7228)"

This causes the install to fail for those of us using dockerhub because there are no images there yet for awx. 

Appreciate if this can be resolved.

Thanks
##### ENVIRONMENT
* AWX version: 12.0.0
* AWX install method: docker on linux
* Ansible version: 2.9.9
* Operating System: CentOS 7
* Web Browser: Google Chrome

**Comment by wenottingham** [comment]
see https://github.com/ansible/awx/issues/7246
