### ISSUE TITLE
awx-cli changing HTTP method from PUT to POST

### ISSUE THREAD

**Issue by davidtluong** [ansible/awx#7260]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
awx-cli modify changes header from put to post for `notification_templates`.  POST does not seem like a valid action for a `notification_templates` object.

These are the actions allowed on it:
```
GET, PUT, PATCH, DELETE, HEAD, OPTIONS
```
##### ENVIRONMENT
* AWX version: Tower 3.6.4
* AWX install method: Ansible Tower

##### STEPS TO REPRODUCE
Use modify on awx-cli on a notification_template specifying headers, inspect before and after, example:
```
/usr/bin/awx-cli notification_template modify ${TOWER_WEBHOOK_TEMPLATE} --headers ${SCRIPT_HOME}/new_sf_eft_oauth_headers_${SF_ENV}.txt
```

##### EXPECTED RESULTS

It should stay as a PUT

##### ACTUAL RESULTS

HTTP method turned into POST

##### ADDITIONAL INFORMATION

Script to examine the before and after:
```
ls

echo ""

echo ""
echo "Dumping Current WebHook Notifications Template 3"
/usr/bin/awx-cli notification_template get 3 --format json > webhook_notification_before.json
echo "--"
echo ""

echo ""
echo "headers & http method (before):"
cat webhook_notification_before.json | jq .notification_configuration.headers
cat webhook_notification_before.json | jq .notification_configuration.http_method
echo "--"
echo ""

echo ""
echo "Modifying Webhook Notification Headers:"
/usr/bin/awx-cli notification_template modify 3 --headers new_headers.txt
echo "--"
echo ""


echo ""
echo "Dumping Altered WebHook Notifications Template 3"
/usr/bin/awx-cli notification_template get 3 --format json > webhook_notification_after.json
echo "--"
echo ""

echo ""
echo "headers & http method (after):"
cat webhook_notification_after.json | jq .notification_configuration.headers
cat webhook_notification_after.json | jq .notification_configuration.http_method
echo "--"
echo ""
```

**Comment by ryanpetrello** [comment]
Hey @rh-dluong,

`awx-cli` is deprecated, and no longer supported:

https://github.com/ansible/tower-cli

Give the new official AWX CLI a shot instead:

https://github.com/ansible/awx/blob/devel/INSTALL.md#installing-the-awx-cli

**Comment by davidtluong** [comment]
Hello @ryanpetrello ,this issue is on awx-cli and not tower-cli, can we please reopen the issue?

**Comment by ryanpetrello** [comment]
@rh-dluong,

`/usr/bin/awx-cli` is https://github.com/ansible/tower-cli (just confusingly named)

```shell
~/venvs/tmp-b58f3a71a8f90c9 pip install git+https://github.com/ansible/tower-cli.git
...
~/venvs/tmp-b58f3a71a8f90c9 cat `which awx-cli`
#!/home/ryanpetrello/venvs/tmp-b58f3a71a8f90c9/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from tower_cli.cli.run import cli        # <---------------------
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(cli())
```

If you'd like to use the **new** _official_ awx CLI (which is different from what you're using in your examples, and is a _newer_ component that's part of awx and recent versions of Tower), instructions are here:

https://github.com/ansible/awx/blob/devel/INSTALL.md#installing-the-awx-cli
https://docs.ansible.com/ansible-tower/latest/html/towercli/usage.html#installation

**Comment by davidtluong** [comment]
Haha, yes, my mistake, the team was just explaining the dizzying nomenclature of tower-cli/awx-cli/awx.  I'll try it out on the newer awx tool.  Thanks!
