### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by angelocustodio** [ansible/awx#7263]
##### ISSUE TYPE
 - Bug Report
    - Problem with installation
##### SUMMARY

- Problem with installation

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method:  docker on linux
* Ansible version:  ansible 2.9.9
* Operating System: Centos 7 e 8
* Web Browser: google chrome

##### ADDITIONAL INFORMATION

TASK [local_docker : Start the containers] *************************************
fatal: [localhost]: FAILED! => {"changed": false, "errors": [], "module_stderr": "", "module_stdout": "", "msg": "Error starting project 404 Client Error: Not Found (\"b\"pull access denied for ansible/awx, repository does not exist or may require 'docker login'\"\")"}

![erro 2](https://user-images.githubusercontent.com/46909368/83819970-b849a100-a6a1-11ea-95c1-42955e82b983.PNG)

**Comment by wenottingham** [comment]
see #7246
