### ISSUE TITLE
Mattermost Notification fails on latest release

### ISSUE THREAD

**Issue by the02** [ansible/awx#7264]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Trying to send a (test) notification to a Mattermost Channel fails with
```
 mattermostinfo: Notification failed.
Error sending notification mattermost: {"id":"api.webhook.incoming.error","message":"Could not decode the multipart payload of incoming webhook.","detailed_error":"","request_id":"<request ID>","status_code":400}
```
##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.7
* Operating System: CentOS 7.8
* Web Browser: Chrome,Chromium,Firefox
* Mattermost Server Version: 5.22.1

##### STEPS TO REPRODUCE
- Create an incomming webhook
- Create a mattermost notification
- Send a test notification

##### EXPECTED RESULTS
Having a notification in the Channel

##### ACTUAL RESULTS

Sending failed with above error message

##### ADDITIONAL INFORMATION

The error message in the mattermost log shows
```
{"level":"error","ts":1591342011.6592789,"caller":"mlog/log.go:175","msg":"Could not decode the multipart payload of incoming webhook.","path":"/
hooks/<hook ID>","request_id":"<request ID>","ip_addr":"<IP Address>","user_id":"","method":"POST","err_where":"
incomingWebhook","http_code":400,"err_details":"mime: no media type"}
```
---
edit: some ID removed in the log sample, mattermost server version added

**Comment by apollo13** [comment]
This was broken and fixed in upstream (mattermost) https://github.com/mattermost/mattermost-server/commit/beadeaf8b56f9c4e33e70069e55e5cdf12981cf6 -- But might take a while to go into a release.

Apparently AWX sends the wrong (or no) content-type

**Comment by apollo13** [comment]
@wenottingham I have attached a PR #7280 which fixes it for me.
