### ISSUE TITLE
Launching a job with API fails to override extra_vars

### ISSUE THREAD

**Issue by staranto** [ansible/awx#7274]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Launching a template where `ask_variables_on_launch = true`.  The extra_vars payload I pass in via `curl --data` does not override the default values from the template.

##### ENVIRONMENT
* AWX version: 3.7.0
* Ansible version:  2.9.1
* Operating System: RHEL

##### STEPS TO REPRODUCE

`/api/v2/job_templates/336` returns 
```
{
  "id": 336,
   -- snip --
   "extra_vars": "var1: \"{{ tower_user_name }}\"",
   "ask_variables_on_launch": true,
   -- snip --
}
```

The template is launched with
```
curl -k -s -L -X POST \
'https://tower-server/api/v2/job_templates/336/launch' \
-H 'Content-Type: application/json' -H 'Authorization: Bearer xxxyyyzzz' \
--data '{"extra_vars": {"var1": "value1"}}'
```

##### EXPECTED RESULTS

I expect the job to launch with the extra_var `var1=value1` as overridden by the `curl --data`.

##### ACTUAL RESULTS

`/api/v2/jobs/2085` returns
```
{
  "id": 2085,
  -- snip --
  "extra_vars": "{\"var1\": \"{{ tower_user_name }}\"}", 
}
```
This is confirmed by looking at the job from Tower UI.  The job is launched with var1 equal to the user associated with the token as specified in the default extra_vars.

**Comment by wenottingham** [comment]
This is an Ansible Tower version string (and mentions Tower).

This repo is for AWX issues and similar upstream feature requests; if you're having issues with Ansible Tower, please contact your Red Hat support rep.
