### ISSUE TITLE
container start fails behind proxy

### ISSUE THREAD

**Issue by therealrobopablo** [ansible/awx#7275]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
launching AWX install fails with a TLS error. Server is behind company firewall. Strangely, it worked fine last month. 

##### ENVIRONMENT
* AWX version: 11.0.0
* AWX install method: docker on linux
* Ansible version:  2.95
* Operating System: CentOS7
* Web Browser: Chrome, EDGE

##### STEPS TO REPRODUCE

Clone repo, launch installer 

##### EXPECTED RESULTS

AWX is installed and containers started

##### ACTUAL RESULTS

Start Containers fails with: "TASK [local_docker : Start the containers] **************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "errors": [], "module_stderr": "", "module_stdout": "", "msg": "Error starting project 500 Server Error: Internal Server Error (\"Get https://registry-1.docker.io/v2/: proxyconnect tcp: tls: first record does not look like a TLS handshake\")"}
"

##### ADDITIONAL INFORMATION

This occurred when working on some reconfigure work. Containers were running previously, behind the firewall. I cloned a fresh version with defaults (that I used to do the initial work) and received the same error. There may have been a firewall change, researching that. Just making sure there wasn't an additional setting I need. I can curl the docker.io site and get a return. Also, running yum updates etc work. I tried disabling the dockerhub setting to try to do a local build and get the same error.

**Comment by wenottingham** [comment]
That error is coming from either dockerhub itself, or from a proxy that sits between you and dockerhub. There's not much we can do in the installer here.

**Comment by therealrobopablo** [comment]
Yes, thanks! I found the "fix" here.
https://github.com/docker/for-linux/issues/415

There were no changes on the server side, but fro some reason it happened. :(  I applied the settings in the link and it came up.  Thanks!
