### ISSUE TITLE
Refresh Inventory with Workflow

### ISSUE THREAD

**Issue by rads18** [ansible/awx#7276]
##### ISSUE TYPE

- Feature Idea
 - Documentation

##### COMPONENT NAME

 - UI

##### SUMMARY
This is more like a consult on a scenarios i am working on, i could not get a response anywhere. So hoping to get some feedback on my approach.

I have automation that pulls large host data/meta data from an API and then parses and creates a json.  Then there is a parser role(that lookup that json) that allows specific hosts passed to it to create inventory on fly with meta refresh inventory call. Then the second play in that playbook uses that refreshed inventory. 

This solution has worked well for me so far with the use of refreshed inventory within the same playbook (job template).  Additionally i don't have to maintain multiple inventory lifecycle as the inventory are created and dissolved during the run.

Here is the scenario i need to solution based on what i have now:
I want to make the parser role available to enterprise via job template, and then share it with the teams on our tower. This way enterprise can simply add that template to their workflow and use it.

Is it possible to run meta refresh in one work flow job template and then use that refreshed inventory for the following job template?

Please advise.

##### ENVIRONMENT
* AWX version: 3.6.4
* Ansible version:  2.9.1
* Operating System: RHEL
* Web Browser: Chrom

**Comment by wenottingham** [comment]
`meta: refresh_inventory` is not supported in AWX. You'd have to do an AWX inventory refresh.

(Also, those look like Ansible Tower version numbers. If you're having issues with Ansible Tower, you should contact your Red Hat support rep.)

**Comment by rads18** [comment]
Hi Wenottingham,  
Can you elaborate what do you mean by meta: refresh_inventory is not supported in AWX ?
I am using it on these version listed above without issue

Also works on one of my test dev instance
AWX 7.0.0.0 
Ansible 2.8.4

https://docs.ansible.com/ansible/latest/modules/meta_module.html

Thanks

**Comment by wenottingham** [comment]
>  Can you elaborate what do you mean by meta: refresh_inventory is not supported in AWX ?

It doesn't do anything - it does not and cannot cause the inventory stored in AWX to refresh. The node where the playbook is running may not even have access to the AWX instance.
