### ISSUE TITLE
Cannot Sort by Name of Schedule on WFJT Schedules list

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#7279]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Cannot Sort by Name of Schedule on WFJT Schedules list

##### ENVIRONMENT
* AWX version: 11.0

##### STEPS TO REPRODUCE
1. Create two schedules for a WFJT
2. On the WFJT Schedules tab, click the sort button

##### EXPECTED RESULTS
Expect the order of Schedules to sort by alphabetical order

##### ACTUAL RESULTS
Nada

##### ADDITIONAL INFORMATION
The URL is constructed like /#/templates/workflow_job_template/32/schedules?schedule.order_by=-unified_job_template__polymorphic_ctype__model

**Comment by unlikelyzero** [comment]
Note: need to add this testcase when state:needs_test

**Comment by mabashian** [comment]
This got fixed somewhere along the way

![schedule_sort](https://user-images.githubusercontent.com/9889020/106788042-7604a500-661e-11eb-9754-cb72e44a5f29.gif)

**Comment by unlikelyzero** [comment]
QE will add a test case for sort of job templates list

**Comment by unlikelyzero** [comment]
@akus062381 since this is a high severity regression, it should be worth adding a basic test for sort on JT Schedules (if one doesn't yet exist) and update stubs on resource schedule tabs

**Comment by akus062381** [comment]
https://github.com/ansible/tower-qa/pull/6095

This PR addresses this issue.
