### ISSUE TITLE
When using AWX on plain HTTP, Social Auth is failing

### ISSUE THREAD

**Issue by ewjoachim** [ansible/awx#728]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY
When user AWX without HTTPS (plain HTTP), logging in with the GitHub OAuth button fails.

##### ENVIRONMENT
* AWX version: 1.0.1.229
* AWX install method: docker on linux
* Ansible version:  2.4.1.0
* Operating System: debian stretch
* Web Browser: firefox

##### STEPS TO REPRODUCE

* Setup AWX, access through port 80 (default)
* Setup GitHub Org auth (but really, it's the same with any Social Auth plugin)
* Log in using the social auth

##### EXPECTED RESULTS

You're logged-in

##### ACTUAL RESULTS

You're not.
awx_web has a log saying :
```
2017-11-28 17:57:48,299 ERROR    social Session value state missing.
```
on the `GET /sso/complete/github-org/` call.

##### ADDITIONAL INFORMATION

The session to persist the `state` parameter between the initial and the `complete` view of the oauth dance is defined by:
https://github.com/ansible/awx/blob/9ed2a0da8f4883a7d6311de2958a01e70605b062/awx/settings/defaults.py#L492

Which uses the default Django session store, which uses a secure cookie due to
https://github.com/ansible/awx/blob/9ed2a0da8f4883a7d6311de2958a01e70605b062/awx/settings/defaults.py#L188

So, if we're not using HTTPS, the cookie will not be sent on the second call, so the session will not be retrieved, the `state` value is absent and the oauth dance fails.

##### WORK AROUND

I guess either use HTTPS or override the SESSION_COOKIE_SECURE to False.

**Comment by matburt** [comment]
I guess I could go either way on this. If one needs social auth we could just require the use of an ssl terminator.

**Comment by ewjoachim** [comment]
I think if HTTPS was explicitely noted as a requirement in the doc when using social auth (which is, I think, important to secure the token), I wouldn't have had the problem. But it would be even better to actually disable the oauth buttons when using raw HTTP.

Note : when I put my nginx front, I also lost some time because of a missing `proxy_set_header X-Forwarded-Proto $scheme;` directive, and had to do a bit of research on how to configure the websocket proxy too. I can share my final nginx configuration if you think we can put it somewhere in the docs.

**Comment by awithrow9** [comment]
I think we should then update documentation to require HTTPS

**Comment by ewjoachim** [comment]
Any solution will do as long as people like me don't get to spend hours manually editing the code inside their docker to understand what's wrong. Documentation, a proper error log, or explicitely disabling social auth on HTTP, any means will do :)

**Comment by rromanchuk** [comment]
I have SSL termination at the load balancer, when i use an nginx proxy,  social oauth stops working with 

_Authentication failed: The redirect_uri MUST match the registered callback URL for this application._  

Inspecting the redirect_uri  query param,  the proto has been changed to http. Both awx server location and oauth callback configurations are properly configured with https.  If i instead send ssl terminated load balancer traffic directly to `0.0.0.0:8000` everything works fine, so theres clearly something wrong with my location block, upstream isn't happy with what i'm forwarding. 

Anyone load balancing (specifically terminating ssl at the load balancer, NOT the host) and using a nginx proxy have any config insights to share?

https://awx.domain.tld (433)   -> Load Balancer -> nginx:80  -> awx_web:8000 🙅 oauth fails 🙅

https://awx.domain.tld (433)   -> Load Balancer ->  awx_web:8000 👍 oauth works 👍

```
upstream awx {
  server 127.0.0.1:8000;
}


server {
  listen 80;
  listen [::]:80;
  server_name awx.domain.tld;

  location / {
    proxy_http_version 1.1;
    proxy_set_header   Host               $host;
    proxy_set_header   X-Real-IP          $remote_addr;
    proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto  $scheme;
    proxy_set_header   Upgrade            $http_upgrade;
    proxy_set_header   Connection         "upgrade";

    proxy_pass http://awx;
  }
}
```

**Comment by rromanchuk** [comment]
I was able to fix this by adding the following set_headers

```
proxy_set_header X-Forwarded-Port 443;
proxy_set_header   X-Forwarded-Proto  https;
```

The load balancer will only ever deliver terminated https/443, so i just hardcoded these forward headers, upstream awx config must have assumed http/80 causing scheme mismatch in the oauth flow.

**Comment by shanemcd** [comment]
These issues should be resolved in the awx-operator.
