### ISSUE TITLE
AWX 11.2.0 can't access to the UI

### ISSUE THREAD

**Issue by zdriic** [ansible/awx#7294]
##### ISSUE TYPE
 - Documentation ?

##### COMPONENT NAME
 - UI

##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: kubernetes on docker
* Ansible version:  2.9.5
* Operating System: ubuntu
* Web Browser: Firefox 77.0.1

##### STEPS TO REPRODUCE

Hi

I try to deploy AWX 11.2.0 with Kubernetes the deployment seems to be OK but I have an issue when I try to access to the UI.

Note : I want to deploy AWX on 2 nodes from my Cluster K8S ( 1 master and 2 nodes)

In my inventory file I have set this :

[tower]
myHost ansible_ssh_user=root ansible_ssh_private_key_file=/root/.ssh/....
_(myHost is not an IP adress in this case)
(myHost is the hostname of my MASTER k8s cluster)_

[all:vars]
ansible_python_interpreter="/usr/bin/env python3"

kubernetes_context=kubernetes-admin@kubernetes
kubernetes_namespace=awx

kubernetes_ingress_hostname=myHost.myDomain.com

awx_task_hostname=awx
awx_web_hostname=awxweb
postgres_data_dir="~/.awx/pgdocker"
host_port=80

..and some conf for proxy

And after the deployment, the container AWX are up on my 2 nodes ( kubernetes_deployment_replica_size: 2 ) but I have this :

kubectl get svc --namespace awx
NAME          TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
awx-web-svc   NodePort   10.100.xx.yyy   <none>        80:30913/TCP   3d21h

kubectl get ing --namespace awx
NAME          HOSTS                             ADDRESS   PORTS   AGE
awx-web-svc   myHost.myDomain.com             80      3d21h

Test URL : myHost.myDomain.com

404 page not found

Could you help me to the web UI access ?
Did I forget to set something up ?
Cluster kube = 1 Master + 2 nodes

In the "host" part of the inventory file, should I put the hostname of the 2 nodes ? the hostname of the master only (as I did) ?

Thanks in advance
Note : This topic is created here https://groups.google.com/forum/#!topic/awx-project/YqxzjSoMqAE

##### EXPECTED RESULTS

Access to the UI

##### ACTUAL RESULTS

Test URL : myHost.myDomain.com

404 page not found

**Comment by ryanpetrello** [comment]
Hey @zdriic,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, your topic you created on the mailing list is the best place to get it.

**Comment by zdriic** [comment]
Hi @ryanpetrello 
Could you help me on the [topic ](https://groups.google.com/forum/#!topic/awx-project/YqxzjSoMqAE) regarding the deployment of AWX on Kube ?

Thanks ! :)

**Comment by ryanpetrello** [comment]
Hey @zdriic,

Nothing in particular stands out to me.

> and some conf for proxy

This feels like something that could be proxy-related to me.  If you find anything you believe is a bug in the installer while investigating let us know and we'll take a look.

**Comment by dayatto** [comment]
Hi @ryanpetrello 

Can you help me, about my case installation ansible awx.
i have success install ansible, but can't access like a this discuss. Just dispay page not found. Any idea or suggest ?
Thanks a lot

**Comment by ryanpetrello** [comment]
Hey @dayatto,

I'm no longer an active contributor to AWX.  @shanemcd and @AlanCoding may have some ideas.  Best of luck!
