### ISSUE TITLE
Custom Credential Types

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#7298]
Issue to track work related to Custom Credential Types. 

1. Modify routing system to add those new routes. https://github.com/ansible/awx/issues/7301
2. List Custom Credential Types https://github.com/ansible/awx/issues/7324
3. Add Custom Credential Types https://github.com/ansible/awx/issues/7325
4. Edit Custom Credential Types https://github.com/ansible/awx/issues/7326
5. Delete Custom Credential Types https://github.com/ansible/awx/issues/7327
6. Add Details page Custom Credential Types https://github.com/ansible/awx/issues/7430

See mockup: https://tower-mockups.testing.ansible.com/patternfly/cred-types/cred-types/

**Comment by nixocio** [comment]
Closing this one - Since the listed items were completed.

**Comment by unlikelyzero** [comment]
@nixocio i noticed that we had 0 test coverage here. I'm going to open this meta issue to track that work

**Comment by unlikelyzero** [comment]
@one-t this is our second biggest blind spot. Can you take some time to ensure we have adequate functional testing in this area?

**Comment by unlikelyzero** [comment]
@akus062381 Can you go through our stubs to verify that we have outlined all of the acceptance criteria of these linked issues?

**Comment by akus062381** [comment]
@unlikelyzero I checked all around and it seems like coverage is existing for these issues. I am closing this.
