### ISSUE TITLE
Project sync failed git scm

### ISSUE THREAD

**Issue by tota45** [ansible/awx#7303]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Project sync job appears to be successful (green output), but "revision" field is not updated with the last commit as expected, Job output stop after the "delete project before update" task : 
![image](https://user-images.githubusercontent.com/26538843/84174900-76dd3b00-aa7f-11ea-99e4-018194bcc976.png)
After this "failed" project sync, I can observe, awx_task content is successfully fetched (with the last commit) on /var/lib/awx/projects/my_project. HEAD is on the last commit.
Then, if a template is executed on AWX, AWX move the HEAD on an old commit in (/var/lib/awx/projects/my_project)
This Issus does not happen when the git project is lightweight, but happen with a heavier project (50Mo)
It looks like the project sync playbook failed in timeout before update the awx database.
##### ENVIRONMENT
* AWX version: 11.2
* AWX install method: docker on linux centos7
* Ansible version:  2.9.9
* Operating System: centos7
* Web Browser: firefox

##### STEPS TO REPRODUCE
step-1:
   Install a fresh AWX 11.2 instance
   Create a new git project with 1 file
   Create a new project on AWX with a GIT SCM source, 
   Execute project synchronization, 
   => everything is successful ("revision field is updated")
step-2:
   add a branch to your git project, with one file
   Execute project synchronization, 
   => everything is successful ("revision field is updated")
step-3:
   update your branch with additional files more than (50Mo) (playbooks, role, whatever...)
     Execute project synchronization, 
   => Project sync job appears to be successful (green output), but "revision" field is not updated with the last commit as expected, 

##### EXPECTED RESULTS
Project synchronization is fast and successful

**Comment by gamuniz** [comment]
@tota45 This feels like an issue that was fixed in 12.0. Are you able to edit the project_update.yml and no_log the delete on update task? That should allow the rest of the playbook to complete.

**Comment by tota45** [comment]
Thanks @gamuniz That's way better. Hope the fix will be applied on 12.0

**Comment by ryanpetrello** [comment]
@tota45 @gamuniz I suspect this is the issue you're referring to?

https://github.com/ansible/awx/pull/6910
https://github.com/ansible/awx/commit/bf65b40241d60e99e49b3109a33c26f26cd418ec

If so, this fix *is* in 12.0.0.
