### ISSUE TITLE
Launching large number of workflows can cause playbook runs  not being processed

### ISSUE THREAD

**Issue by momcilo78** [ansible/awx#7318]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Launching large number of workflows can cause playbook runs  not being processed. In #7136 I reported the performance issue when launching workflows. To "solve" this I came with the cunning plan: use threaded launching. Since I considered to deploy at least 3 awx instances behind the load balancer I wanted to check on how far I can go with a single instance first. 

Sadly it appears large number of workflows can "starve" the playbook runs of execution times, and system can spend long time without being able to execute any playbook run (and consequently workflow). I believe that in this case it spends most of it time on checking if any of the workflow related playbook runs did finish. It appears that workflows occupy the complete execution capacity, so very few playbook runs actually execute. 

##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.7
* Operating System: CentOS 8
* Web Browser: Irrelevant

##### STEPS TO REPRODUCE

Prepare standalone awx based on docker with 4 cores and 8 GB RAM.

1. prepare a workflow template consisting of 2 chained (All) playbooks (e.g. git-unsuspend account and jira-resolve issue). 
2. launch the 5 series of 200 workflows over 30 threads over REST API. 
3. Wait some time, until there are enough workflows in "running" state to actually choke the execution of playbooks. 
4. Observe the playbook jobs running on instance, most likely you will see 0, with occasional rare activity. 

##### EXPECTED RESULTS

1. many concurrent workflows in running state
2. playbook runs continue to execute despite large number of workflows being active.

##### ACTUAL RESULTS

1. many concurrent workflows in running state
2. playbooks do not get executed almost at all. Consequently no luck work workflows either. 

Given the fact that playbook runs are the ones pulling the weight, I would expect them to be prioritized over workflow runs, which despite being higher level abstraction are mostly "passive" and wait for the actual results from playbook runs.

In fact, the total throughput of the system is many times smaller then single thread invocation of workflows.

##### ADDITIONAL INFORMATION

**Comment by wenottingham** [comment]
"4 cores and 8 GB RAM" 
"5 series of 200 workflows"

So, 1000 simultaneous workflow jobs? That's not going to work in 8GB of RAM.

**Comment by wenottingham** [comment]
Closing this; your cluster is underprovisioned.
