### ISSUE TITLE
RFE: Allow AWX for customizable live update for UI

### ISSUE THREAD

**Issue by hiyokotaisa** [ansible/awx#7330]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

AWX is able to modify `UI_LIVE_UPDATES_ENABLED` to disable auto page refreshing on all of Tower UI. However, it would be great if the live update is enabled on job result but disabled for the other at the same time.

The use-case is disabling UI live update to avoid the modify will be lost when I creating Job Template but I would like to enable it when I launch the Job Template.

**Comment by wenottingham** [comment]
Is this still an issue in AWX? I believe this was fixed a few releases ago.

**Comment by ryanpetrello** [comment]
Yea, I think given the changes we made to the UI in recent versions (thanks for @rebeccahhh and @mabashian's work), we might just want to close this one.

**Comment by rebeccahhh** [comment]
I'm fine closing it as long as it actually fully addresses the original ask.

**Comment by blomquisg** [comment]
@hiyokotaisa if this isn't addressed by what's already released, go ahead and reopen
