### ISSUE TITLE
SAML Configuration - No visible errors and removal of configuration

### ISSUE THREAD

**Issue by Blusafur** [ansible/awx#7335]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When saving SAML configuration such as SAML TEAM MAP and SAML TEAM ATTRIBTUE MAPPING, setting are lost after clicking the save button and stay on the screen, but after refresh the settings are gone with no visible errors.

##### ENVIRONMENT
* AWX version: Tested on 11.2.0 and 9.2.0
* AWX install method: Docker on CentOS
* Ansible version:  2.9.6 (AWX 11.2.0) and 2.9.3 (AWX 9.2.0)
* Operating System: CentOS Linux 7 (Core) for both versions
* Web Browser: Firefox 68.9.0 and Chrome 83.0.4103.61

##### STEPS TO REPRODUCE

Go to Settings -> Authentication -> SAML

Paste the below in the SAML TEAM MAP section (names changed):
{
    "saml_attr": "MemberOf",
    "remove": true,
    "team_org_map": [
    {
        "team": "fake.team",
        "organization": "Fake - Org"
    }
  ]
}

Click the Save button

##### EXPECTED RESULTS

The working notification displays for a little bit, then either a notification saying saved should come up or a parsing error should popup telling you what you did wrong and at what location.

##### ACTUAL RESULTS

The working notification displays for a little bit, and the page scrolls to the top. No notification of being saved or an error pops up. The settings you entered are still on the page. If you do a hard refresh of the SAML settings page or navigate to another page and come back, the settings you just entered have disappeared.

##### ADDITIONAL INFORMATION

I am trying this while trying to map a SAML "MemberOf" attribute to a team. If you have any better examples or documentation that would be helpful as well. The official documentation doesn't give a clear cut example of doing this.

**Comment by blomquisg** [comment]
@one-t can you take a look at this?  Is there any documentation that might help?

**Comment by blomquisg** [comment]
@Blusafur can you include the network console logs?

**Comment by one-t** [comment]
Hi, @Blusafur - can you provide redacted screenshots of the whole saml config? 

Thanks!

**Comment by wenottingham** [comment]
Closing, please reopen when you have the requested information.
