### ISSUE TITLE
Add Test button to credential form for external credential types

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7339]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
This is sort of related to #7338 in that they both interact with the same endpoint but the UX is a bit different on this button.  To be clear, this is the button we're talking about in this issue:

<img width="1513" alt="Screen Shot 2020-06-15 at 11 32 07 AM" src="https://user-images.githubusercontent.com/9889020/84676834-f180dd00-aefb-11ea-8ac1-0362ca54a84a.png">

Clicking on that button should open up a modal that looks like:

<img width="818" alt="Screen Shot 2020-06-15 at 11 33 09 AM" src="https://user-images.githubusercontent.com/9889020/84676929-0493ad00-aefc-11ea-807d-26d3968038d4.png">

These are the same form fields present in the Metadata step of the credential plugin wizard (based on credential type).

Once a user fills in the required fields and submits, a request to `/api/v2/credentials/:id/test` should be issued and an alert shown in the upper right corner indicating the result of the test:

<img width="1274" alt="Screen Shot 2020-06-15 at 11 34 41 AM" src="https://user-images.githubusercontent.com/9889020/84677091-399fff80-aefc-11ea-9d39-6679847d2a35.png">

**Comment by mabashian** [comment]
@unlikelyzero I think we can close this now?

**Comment by unlikelyzero** [comment]
covered by credential-mock
