### ISSUE TITLE
Source variables not filtering when running vCentre inventory sync.

### ISSUE THREAD

**Issue by MattMonkman** [ansible/awx#7347]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Source variables not filtering when running vCentre inventory sync.
All vm hosts and all properties are synchronised.

##### ENVIRONMENT
* AWX version: 12.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.9
* Operating System: Centos 8
* Web Browser: Chrome
*vCentre version: 6.7

##### STEPS TO REPRODUCE
Post AWX install steps:
Configured authentication with kerberos as per Ansible doc.
Created vCentre credentials
Created vCentre inventory

Added the following to the Source Variables section;

alias_pattern: "{{ config.name }}"
host_filters: "{{ guest.gueststate == 'running' }}"
properties:
  prop01: "config.name"
  prop02: "guest.hostName"
  prop03: "guest.ipAddress"
  prop04: "guest.guestId"
  prop05: "guest.guestState"
  prop06: "guest.guestFamily"
  prop07: "config.annotation"

Saved, and ran the inventory sync.

##### EXPECTED RESULTS

Import VM hosts without the GUID in the name, in a running state and with a set of properties (host variables) matching the above.

##### ACTUAL RESULTS

All vm hosts are imported regardless of running state, GUID in the name, and with up to 2400 host variables.

Sync log has errors;

    2.025 INFO     Updating inventory 2: vcentre
    2.463 DEBUG    Using base command: python /usr/bin/ansible-inventory -i /tmp/awx_14_vj6lh2p9/vmware_vm_inventory.yml --playbook-dir /tmp/awx_14_vj6lh2p9 -vvvvv
    2.464 INFO     Reading Ansible inventory source: /tmp/awx_14_vj6lh2p9/vmware_vm_inventory.yml
    2.465 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    2.465 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/usr/pgsql-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    2.465 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
   21.188 ERROR    ansible-inventory 2.9.9
   21.189 ERROR      config file = /etc/ansible/ansible.cfg
   21.189 ERROR      configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
   21.189 ERROR      ansible python module location = /usr/lib/python3.6/site-packages/ansible
   21.189 ERROR      executable location = /usr/bin/ansible-inventory
   21.189 ERROR      python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
   21.189 ERROR    Using /etc/ansible/ansible.cfg as config file
   21.189 ERROR    setting up inventory plugins
   21.189 ERROR    Parsed /tmp/awx_14_vj6lh2p9/vmware_vm_inventory.yml inventory source with auto plugin
   21.415 DEBUG    Finished loading from source: /tmp/awx_14_vj6lh2p9/vmware_vm_inventory.yml

This entry appears for every host "<hostname> has no "config.instanceuuid" variable"

##### ADDITIONAL INFORMATION
All of the config has been complete in the gui.
I have installed awx twice from scratch on vanilla Centos 8 vm's with exactly the same result
Instance filters do work, ie {{ _"string"_ in config.name }}

**Comment by AlanCoding** [comment]
> Import VM hosts without the GUID in the name

Are we missing some information here? I don't see anything in source variables indicating filtering on name.

**Comment by MattMonkman** [comment]
I thought **alias_pattern: "{{ config.name }}"** names the imported host
correctly, as it is in vcentre, without the guid appended to it?

**Comment by AlanCoding** [comment]
Now I see your meaning. I was reading that wrong.

I don't expect that the `properties` will be respected here, but that doesn't do anything to explain the error you are getting. The only place I see `config.instanceUuid` referenced is in the default properties (of the plugin itself), which should not be getting used in any templating that I can find.

To be sure I'm reading right, you're saying that there's a log message with this warning, and that the hosts still get imported? What is the exact syntax of that log message?

Is this a fresh inventory, or an existing inventory migrated from a prior AWX version?

**Comment by MattMonkman** [comment]
Thanks Alan.  My phrasing may be a little loose.  I'm brand new to AWX.

Yes, all hosts are still imported.  Fresh inventory created after AWX install.

WIth respect to properties not being honoured in the source variables, where would these be configured?

I've attached the inventory job log.

[inventory_log.txt](https://github.com/ansible/awx/files/4788306/inventory_log.txt)

**Comment by MattMonkman** [comment]
apologies.  previous log was captured with Instance Filter populated, not source variables.

attached correct now.

[inventory_log.txt](https://github.com/ansible/awx/files/4788396/inventory_log.txt)

**Comment by MattMonkman** [comment]
Hello.  Any further thoughts on this?

**Comment by AlanCoding** [comment]
There were some major changes that happened in 9eaee801a742751632b8490c740a9565178a28b5, related specifically to the id variable. This is a separate subject from using alias_patterns, which is expected to work. However, logs related to the `config.instanceuuid` are all over your output, and it seems likely that they may be complicating the issue. That fix landed in 13.0.0, so the logs make sense, and those warnings should be resolved with an upgrade.

**Comment by wenottingham** [comment]
This has all changed in AWX 14.0 or later, please try that?

**Comment by elyezer** [comment]
See here for more information https://github.com/ansible/awx/issues/5150#issuecomment-669495939
