### ISSUE TITLE
the connection plugin 'community.kubernetes.kubectl' was not found

### ISSUE THREAD

**Issue by svenstaro** [ansible/awx#7349]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Running any playbook in my container group inside OpenShift results in an error: `the connection plugin 'community.kubernetes.kubectl' was not found`.

This started happening after the upgrade to 12.0.0. Before everything ran smoothly.

##### ENVIRONMENT
* AWX version: 12.0.0
* AWX install method: openshift
* Ansible version:  2.9.9
* ansible-runner: 1.4.6 off of Docker Hub
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

1. Make a container group
2. Have an OpenShift cluster set up to go with this
3. Run a playbook on the container group

##### EXPECTED RESULTS

A new container should spawn which should then proceed to run the playbook fine.

##### ACTUAL RESULTS

A new container spawns and I get a failure stating `the connection plugin 'community.kubernetes.kubectl' was not found`.

##### ADDITIONAL INFORMATION

 PLAY [Prepare data, dispatch job in isolated environment.] ********************* TASK [synchronize job environment with isolated host] ************************** skipping: [awx-job-11809] TASK [synchronize job environment with remote job container] ******************* changed: [awx-job-11809 -> localhost] TASK [stat] ******************************************************************** ok: [awx-job-11809 -> localhost] TASK [create a named pipe for secret environment data] ************************* skipping: [awx-job-11809] TASK [spawn the playbook] ****************************************************** fatal: [awx-job-11809]: FAILED! => {"msg": "the connection plugin 'community.kubernetes.kubectl' was not found"} PLAY RECAP ********************************************************************* awx-job-11809 : ok=2 changed=1 unreachable=0 failed=1 skipped=2 rescued=0 ignored=0

Sorry for formatting, this is a raw log from AWX.

**Comment by ryanpetrello** [comment]
@AlanCoding @fosterseth one of you have context on this?  Looks related to a recent change (4da0e0dd804ada784b7072ea423b459fcfc501b2)

**Comment by ryanpetrello** [comment]
@svenstaro I'm not certain what your downstream build process is since you're using OpenShift with awx, but you likely need to make sure that if you're building images, you're including this sort of thing in that process (i.e., actually installing the `community.kubernetes` collection in your image):

https://github.com/ansible/awx/commit/4da0e0dd804ada784b7072ea423b459fcfc501b2#diff-aa83aff711527c101c32088c8adc7a37

**Comment by svenstaro** [comment]
We're using the official ansible-runner images. Turns out our outdated configuration was the problem:

```
-      INVENTORY_COLLECTIONS_ROOT = '/var/lib/awx/vendor/inventory_collections'
+      AWX_ANSIBLE_COLLECTIONS_PATHS = '/var/lib/awx/vendor/awx_ansible_collections'
```

So not really a bug. Hopefully, other people whose configuration is also outdated between the upgrades (there are bound to be some) will find this issue and this'll help them.
