### ISSUE TITLE
Enforce feature-completeness of the AWX collection

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#7353]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The AWX collection has a [module generator](https://github.com/ansible/awx/blob/devel/awx_collection/tools/generate.yml) that will use the API OPTIONS to produce a module with all of the same fields that the API has.

However, that has only be employed for adding new modules. We also need to devise a way to keep the collection up-to-date with API changes through some form of automation.

For a first pass, we would like to enforce that:

 - all top-level endpoints from the API (or other metric) have a module corresponding to them
 - every module has all of the fields that the API has

We can still keep exclusion lists and other exceptions, as necessary.

If we create this enforcement mechanism, we could run it in the Zuul CI so that we know that it's being kept up with every merge.

**Comment by beeankha** [comment]
PR https://github.com/ansible/awx/pull/7963 has been merged, closing this issue!
