### ISSUE TITLE
Add ability to cancel jobs from jobs list

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7364]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
We need to provide a way for users to cancel a job from the jobs list.  Currently only relaunch and delete are possible:

<img width="1420" alt="Screen Shot 2020-06-17 at 5 34 14 AM" src="https://user-images.githubusercontent.com/9889020/84881684-36238a00-b05c-11ea-9b7d-6fe40f9e57b2.png">

There are two options:

1) We could add a cancel icon to each row (like the old app)
2) We could add another list level action button next to `Delete` and allow users to select multiple rows before clicking `Cancel`.  This would behave like batch delete where we still make individual requests for each job.

@wenottingham @trahman73 any preference on one or the other?

**Comment by trahman73** [comment]
@mabashian I'm fine with either option, but after our discussion it sounds like option 1 would be easier to implement.

**Comment by wenottingham** [comment]
I think we're going to get asked for the "batch" variant, so if it's doable, that would be nice.

**Comment by tiagodread** [comment]
Test and stubs in place PR already merged
