### ISSUE TITLE
Unable to launch task template when using a vcenter credential

### ISSUE THREAD

**Issue by koutido** [ansible/awx#737]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

While launching a task, I couldn't go to next step when I chose a vmware vcenter credential.

##### ENVIRONMENT
* AWX version: 1.0.1
* AWX install method: docker on linux
* Ansible version:  2.4.0
* Operating System: CentOS 7
* Web Browser: Firefox 56

##### STEPS TO REPRODUCE

- Create project with a playbooks which create a resource_pool on a vcenter
- Create un vmware vcenter credential
- Create a new inventory and add the vcenter host
- Create a job template with those all elements
- Launch the job template using vcenter credential 

##### EXPECTED RESULTS

=> we can't click on the "Next" button

**Comment by koutido** [comment]
Hello,

Someone could find the solution for this issue ?

Best regard

**Comment by awithrow9** [comment]
@koutido  can you let us know if you're still seeing this?

**Comment by wenottingham** [comment]
This should be fixed in current releases (1.0.6). Please reopen if you're still seeing this.
