### ISSUE TITLE
Cannot read hosts from Amazon EC2 as source

### ISSUE THREAD

**Issue by princemandlewala** [ansible/awx#7371]
##### ISSUE TYPE

 - Bug Report
`    2.118 INFO     Updating inventory 5: AWS Stage - Test
    2.610 DEBUG    Using base command: python /usr/bin/ansible-inventory -i /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/plugins/inventory/ec2.py --playbook-dir /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/plugins/inventory -vvvvv
    2.610 INFO     Reading Ansible inventory source: /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/plugins/inventory/ec2.py
    2.615 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    2.615 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/usr/pgsql-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    2.615 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1139, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1029, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 215, in load
    return self.command_to_json(base_args + ['--list'])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 198, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
ansible-inventory 2.9.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
[WARNING]:  * Failed to parse /var/lib/awx/venv/awx/lib/python3.6/site-
packages/awx/plugins/inventory/ec2.py with script plugin: Inventory script
(/var/lib/awx/venv/awx/lib/python3.6/site-
packages/awx/plugins/inventory/ec2.py) had an execution error: ERROR:
"Authentication error retrieving ec2 inventory.  - AWS_ACCESS_KEY_ID and
AWS_SECRET_ACCESS_KEY environment vars found but may not be correct  - No Boto
config found at any expected location '/etc/boto.cfg, ~/.boto,
~/.aws/credentials'", while: getting EC2 instances
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/script.py", line 161, in parse
    raise AnsibleParserError(to_native(e))
[WARNING]: Unable to parse /var/lib/awx/venv/awx/lib/python3.6/site-
packages/awx/plugins/inventory/ec2.py as an inventory source
ERROR! No inventory was parsed, please check your configuration and options.`

##### COMPONENT NAME

 - Installer

##### SUMMARY

I am trying to add Amazon EC2 as a source for my inventory. I am seeing the above error. I have added the credentials as well as I am using the credentials having admin access to the account. I am not sure what is happening.
##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.9.5
* Operating System: 
* Web Browser: 

##### STEPS TO REPRODUCE

1. Create new inventory
2. Add Amazon EC2 as a source in new ansible inventory. 
3. Add credential as Amazon account credential
4. Try for all regions
5. Group by region
6. Update Options should be selected as "Update on Launch"
Try to sync the source.
 
##### EXPECTED RESULTS

My expected result was to see the hosts from my account to be pulled.
##### ACTUAL RESULTS

I get the above error and no hosts to be pulled by AWX from my AWS account

**Comment by blomquisg** [comment]
I see this error in your output:

> `"Authentication error retrieving ec2 inventory. - AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment vars found but may not be correct - No Boto config found at any expected location '/etc/boto.cfg, ~/.boto, ~/.aws/credentials'"`

Please re-verify your credentials and configuration.

**Comment by princemandlewala** [comment]
hi @blomquisg ,
We have exported the variables from where we are running the AWX. It still didn't worked. Is there any tutorial we can follow?
Thanks,
Priyance

**Comment by Gortex** [comment]
@blomquisg The credentials are correct and can be used directly on the AWX instance using the aws-cli.  This appears to be an issue with AWX.  Please re-open the bug until we can confirm what the actual issue is.

**Comment by mihai-satmarean** [comment]
hi, we have the same issue
  < AWX 11.1.0  >
 -------------- 
        \   ^__^
         \  (oo)\_______
            (__)      A )\/\
                ||----w |
                ||     ||

Ansible 2.9.5
Copyright © 2019 Red Hat, Inc.
Visit Ansible.com for more information.
