### ISSUE TITLE
Add netcat to AWX

### ISSUE THREAD

**Issue by szollin** [ansible/awx#7384]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

When trying execute against a host that needs to be accessed by a SOCKS proxy, the available ssh & ProxyCommand combo [documented here](https://docs.ansible.com/ansible-tower/latest/html/administration/tipsandtricks.html#setting-up-a-jump-host-to-use-with-tower) does not work. The use of netcat (the nc command) is needed. 

##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.7
* Operating System: Ubuntu 20.04
* Web Browser: Chrome 83.0.4103.106

##### STEPS TO REPRODUCE

A user should be able to go to their inventory, choose either a group or a host, and add this block to the variable.

```
---
ansible_user: awx
ansible_connection: ssh
ansible_ssh_common_args: '-o ProxyCommand="nc -x <proxy_address>:<port_number> %h %p"'
```

##### ADDITIONAL INFORMATION

The way I found out that netcat wasn't available was doing `docker exec -ti awx_task bash` and running `which nc`. I also did `docker exec -ti awx_web bash` and ran `which nc` in there as well.

**Comment by ryanpetrello** [comment]
Hey @szollin,

We're unlikely to add `nmap-ncat` to our runtime requirements, but if you'd like to build your own image (https://github.com/ansible/awx/blob/devel/INSTALL.md#official-vs-building-images), there is a flag which installs `nc` and other similar dev/test tools:

https://github.com/ansible/awx/blob/devel/installer/roles/image_build/templates/Dockerfile.j2#L96

**Comment by szollin** [comment]
Thanks. I will give that a shot.

**Comment by cnukwas** [comment]
> Hey @szollin,
> 
> We're unlikely to add `nmap-ncat` to our runtime requirements, but if you'd like to build your own image (https://github.com/ansible/awx/blob/devel/INSTALL.md#official-vs-building-images), there is a flag which installs `nc` and other similar dev/test tools:
> 
> https://github.com/ansible/awx/blob/devel/installer/roles/image_build/templates/Dockerfile.j2#L96

Tried to install jq, wget and few other utilities by updating the Dockerfile.j2 while building our own images but those are not installed in awx-web docker image?
Is this some kind of bug in the latest version or we can install other tools only when build_dev = true?

Thanks
