### ISSUE TITLE
Sporadically receiving HTTP 404 when calling /launch

### ISSUE THREAD

**Issue by alxndr13** [ansible/awx#7386]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Sometimes calling the /launch Endpoint of a Job Template returns a 404, when the template is clearly available. 

##### ENVIRONMENT
* AWX version: 11.2.0 and 12.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.9
* Operating System: RedHat Enterprise Linux 7.7
* Web Browser: Firefox / Google Chrome

##### STEPS TO REPRODUCE
It is not reliably reproducible. 

- Do a GET or POST Request to: /api/v2/job_templates/templatename++orgname/launch/

##### EXPECTED RESULTS

401 or 201 (depending on logged in state)

##### ACTUAL RESULTS

404

Log from awx_web container: (removed sensitive information)
```
2020-06-19 06:48:06,620 WARNING  django.request Not Found: /api/v2/job_templates/templatename++orgname/launch/
2020-06-19 06:48:06,620 WARNING  django.request Not Found: /api/v2/job_templates/templatename++orgname/launch/
[pid: 77|app: 0|req: 17/102] 172.18.0.1 () {52 vars in 3075 bytes} [Fri Jun 19 06:48:06 2020] GET /api/v2/job_templates/templatename++orgname/launch/ => generated 12304 bytes in 98 msecs (HTTP/1.1 404) 6 headers in 295 bytes (1 switches on core 0)
172.18.0.1 - - [19/Jun/2020:06:48:06 +0000] "GET /api/v2/job_templates/templatename++orgname/launch/ HTTP/1.1" 404 12304 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0" "10.100.X.X"


```

##### ADDITIONAL INFORMATION
The issue occurs mysteriously often when the endpoint is called from our jenkins instance. 

Pipeline Log:
```
[INFO] Request URI: https://awx.company.org/api/v2/job_templates/templatename++orgname/launch/
[INFO] Request Method: POST
[INFO] Request Headers: {Accept=application/json;charset=UTF-8, Content-Type=application/json;charset=UTF-8, Content-Length=286}
[INFO] Request Body: {"extra_vars":{"appname":"superniceapp","url":"someurl"}}
[INFO] Response Status Code: 404
[INFO] Response Headers: {Server=nginx/1.16.1, Date=Fri, 19 Jun 2020 08:13:30 GMT, Content-Type=application/json, Content-Length=55, Connection=keep-alive, Vary=Accept, Accept-Language, Origin, Cookie, Content-Language=en, X-API-Total-Time=0.028s}
[INFO] Response Body: {"detail":"The requested resource could not be found."}
```

**Comment by blomquisg** [comment]
@alxndr13 can you share some details about your environment? Are you running behind a proxy?

**Comment by alxndr13** [comment]
@blomquisg yes, we are running behind nginx. We only use it for tls termination.

`nginx.conf`:

```
location / {
            proxy_pass http://127.0.0.1:81;
            proxy_set_header Host $host;
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }
```

**Comment by wenottingham** [comment]
What roles on the template and its associated organization does the calling user have?

**Comment by alxndr13** [comment]
@wenottingham Thanks for your response. 

We tried it with two different users:
- The first one "alpha" is a system admin and additionally has the execute role for the template.
- the second one: "beta", has the execute role for the template.

**Comment by wenottingham** [comment]
Does the "beta" user have any rights on the organization the template belongs to?

**Comment by alxndr13** [comment]
@wenottingham yes, he is a regular member. :)

**Comment by alxndr13** [comment]
Is there anything else i can provide to solve this mystery? We'll try to fallback to the Job Template ID when calling `/launch`, i'll keep you guys updated if that changes anything.

**Comment by ryanpetrello** [comment]
Hey @alxndr13,

I'm equally stumped on this one - it's possible there *could* be some latent bug in the code that maps `templatename++orgname` to an ID, causing it to fail _sometimes_, but I'm not able to reproduce anything like this :/

**Comment by alxndr13** [comment]
@ryanpetrello We just switched yesterday from `templatename++orgname` to only `templatename` and the 404's are gone. The combination seems to be the problem. 

Thanks for your help :)

**Comment by pradeep-git23** [comment]
Hi, i am also facing the same issue and its not regular also its occurs for me only while executing project sync from AWX. 
Also, it is occuring in middle of project sync job where half job is executed and it stuck in a play "PLAY [Install content with ansible-galaxy command if necessary] ****************
".

Kindly help.
