### ISSUE TITLE
Custom job name when launching a job_template

### ISSUE THREAD

**Issue by mrhockeymonkey** [ansible/awx#739]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Allow jobs to be named when launching them from a template

##### ENVIRONMENT
* AWX version: 1.0.1.8
* AWX install method: docker on linux
* Ansible version:  2.4.0.0
* Operating System: rhel-7
* Web Browser: chrome

##### ADDITIONAL INFORMATION
I used to have the ability with api/v1/ to create a job with a given name based off of a template. This allowed me to make jobs with meaningful names (i.e. that contained hostnames or other information). 

Now that I have moved to using api/v2/ it looks as if you can only launch a job based off of a template by targeting **api/v2/job_templates/<id>/launch** which results in a job with the same name of the template. 

It would be nice to have some way to rename each instance of a job to reflect something a bit more human readable. Either this option exists and I'm doing it wrong, in which case sorry/please point me in the right direction, or can this be considered as a feature.

**Comment by mrhockeymonkey** [comment]
After a little more digging I have found a solution but it feels like a bit of a workaround (Script Below). In api/v2 the POST method was removed from api/v2/jobs/ but it is still present at api/v2/job_templates/<template_id>/jobs

However calling this has some issues:

* The Job doesn't start, Instead i need to POST to api/v2/jobs/<job_id>/relaunch. This however creates another new instance of the job and leave the non-started one behind which isn't nice
* The vault credential is not passed to the created job, i have to specify it seperatly


```powershell
#Authenticate to AWX
$Token = irm -Method post -Uri "http://awx/api/v2/authtoken/" -ContentType 'application/json' -Body $(@{username = 'admin'; password = 'password'} | ConvertTo-Json)

$Common = @{
    ContentType = 'application/json'
    Headers = @{Authorization = "token $($Token.token)"}
}

# Create a body to POST
$Body = @{
    name = 'Build new server named xyz'
    description = 'some description'
    limit = 'xyz.domain.net'
    vault_credential = 4 # the id of the vault cred we need, this doesnt seem to come from the template
    allow_simulataneous = $true
    extra_vars = @{
        ilo_addr = '172.16.1.1'
        skip_pxe = 'yes'
    }
} | ConvertTo-Json

#Create a new job (this does not start)
$Job = Invoke-RestMethod -Method post -Uri "http://awx/api/v2/job_templates/5/jobs" @common -body $Body

# Relaunch the job to get it running
$JobRelaucnh = Invoke-RestMethod -Method post -Uri "http://awx$($Job.related.relaunch)" @common -body $Body
```

I'm hoping there is a better way or that these two issues are bugs that can be resolved

Nb: I have to use powershell for this task instead of the preferred tower-cli. I have looked at [what tower-cli does](https://github.com/ansible/tower-cli/blob/master/tower_cli/resources/job.py) but it looks like it can only launch a template, not make a new job with custom name based off of a template as i require.

**Comment by parinapatel** [comment]
+1

**Comment by AlanCoding** [comment]
The only version of this that makes sense to me is templating survey variables.

**Comment by mrhockeymonkey** [comment]
To be honest I'm happy for this to be closed off as not needed. We have moved on and don't really require this feature.

**Comment by coudenysj** [comment]
Hi, I would like to reopen this feature request.

We have a lot jobs launched from a small set of job templates, and now the overview page of AWX just shows us the name of the template.

Is it possible to launch a template, and supplying a name for it?

**Comment by AlanCoding** [comment]
For my alternative proposal, say I have a job that builds or deploys a version of some software, then the job name could be "Build package version 6.2.3". Say it uses standard templating.

That could be done with little to no UI involvement, and would probably be a relatively comfortable idea for many users.

Also, the burden of inputting a new job name _just_ for the purpose of naming a job sounds not worth it for the user.

**Comment by coudenysj** [comment]
Well yes, it should be optional by default (using the same naming it uses now if you don't supply anything).

Is there anything I can do to help adding this functionality?

**Comment by coudenysj** [comment]
@AlanCoding Is this something the project would be interested in? If so, how can I help to make it happen?

**Comment by anemyte** [comment]
+1 for the feature. It is really hard to find logs from some specific run using only job ID.

**Comment by nikat** [comment]
+1 for this feature

**Comment by k8s4** [comment]
+1 
I agree too

**Comment by martinsoenen** [comment]
Hi,

Can we get any news about this please ? I'd be interested too.

Thanks by advance

**Comment by AlanCoding** [comment]
https://github.com/ansible/awx/pull/14049

**Comment by pHiney** [comment]
> To be honest I'm happy for this to be closed off as not needed. We have moved on and don't really require this feature.

That's disappointing. Cause it is needed.
