### ISSUE TITLE
[awx-pf] AWX crashes in certain scenarios on Firefox

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#7393]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
![Screenshot_20200617_095144](https://user-images.githubusercontent.com/19942822/85163218-87847280-b230-11ea-9e71-42e16542c04a.png)

This is perhaps the simplest example. If you go to a host -> Details, in chrome the X next to the inventory chip is disabled. However, it is enabled in FF, and crashes the application with null errors if clicked.

Another scenario where this occurs is if you have a prompt-on-launch inventory. When clicking Launch and selecting an inventory, a chip appears at the top of the screen which shows you which inventory is currently selected. Clicking the X which is enabled here breaks the screen with null errors as well.

Another one is when creating a Team. If you click the X to remove the org associated with a team, the page crashes. I think the X is supposed to be disabled in FF.

Whatever is making the X button shown on these chips where it is not supposed to be shown in Firefox needs to be audited throughout the application, or null errors need to be fixed where the X's should work normally.

##### ENVIRONMENT
* Operating System: Fedora
* Web Browser: Firefox ESR

##### STEPS TO REPRODUCE
The simplest example is as follows:
1. Make an Inventory and some hosts, assign them to a group.
2. Go to Hosts->Group details
3. Click the X to remove the inventory in the details.

##### EXPECTED RESULTS
Normal removal, validation, etc.

##### ACTUAL RESULTS
Entire page crashes with a null error.

**Comment by unlikelyzero** [comment]
@dsesami do you mind retesting this?

**Comment by dsesami** [comment]
The inventory chip no longer has an x. Note: Since this is an element that no longer exists at all, I am unsure of what automation would look like to assert for something that never appears.
