### ISSUE TITLE
[awx-pf] Prompt on launch is unusable at smaller widths on firefox

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#7394]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Viewing the JT prompt on launch modal at less than full-screen widths on firefox pushes the "Next"/"Save" type buttons used to proceed through the launch wizard off-screen. This prevents the user from actually being able to use the wizard. Scrolling is also not available.

##### ENVIRONMENT
* Operating System: Fedora
* Web Browser: Firefox ESR

##### STEPS TO REPRODUCE
1. Open a new job template and set several values to be prompted at launch.
2. Launch the JT to start the prompting wizard.
3. Shrink the screen width to something smaller, likely half-size on your own screen.

##### EXPECTED RESULTS
I can proceed through the wizard normally.

##### ACTUAL RESULTS
The bottom of the wizard is shoved off screen, making some buttons unclickable. I cannot scroll down to view these items.

**Comment by unlikelyzero** [comment]
Cannot reproduce, however we have coverage in visualintegration
