### ISSUE TITLE
[awx-pf] assorted UI issues in Firefox

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#7395]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
This issue is meant to try to cover various "smaller" issues with alignment and appearance with ui_next in Firefox.

- [ ] Text wrapping on details (like the details page of various items) doesn't seem to work right.
- [ ] Magnifying glasses on forms (like when selecting an org for a template) don't have the box around them which indicates that they're buttons.
![Screenshot_20200617_093911](https://user-images.githubusercontent.com/19942822/85165582-0c24c000-b234-11ea-853a-c2845a620078.png)
- [ ] Create > 5 inventories, then set a job template to prompt for an inventory. When selecting an inventory from the modal, a pagination element appears. However, there is a second set of arrows inside the "current page" box which do change the number in the box, but don't change anything else. These are visible on hover in chrome, and should be checked in both browsers.
![Screenshot_20200617_094224](https://user-images.githubusercontent.com/19942822/85165748-4726f380-b234-11ea-919a-df33a2049f92.png)
- [ ] Tooltips on all forms are weirdly out of alignment when compared to chrome.
- [ ] When viewing the form for a new survey for a job template, tooltips and the "Required" button are out of alignment.
![Screenshot_20200617_095845](https://user-images.githubusercontent.com/19942822/85165854-6d4c9380-b234-11ea-85a0-0f012771bff4.png)

* Operating System: Fedora
* Web Browser: Firefox ESR

**Comment by mabashian** [comment]
We should probably treat this issue as a general reminder to click through FF and make sure we don't have breakage.

**Comment by mabashian** [comment]
> Text wrapping on details (like the details page of various items) doesn't seem to work right.

^^ wasn't able to reproduce this one

> Magnifying glasses on forms (like when selecting an org for a template) don't have the box around them which indicates that they're buttons.

^^ wasn't able to reproduce this one

> Create > 5 inventories, then set a job template to prompt for an inventory. When selecting an inventory from the modal, a pagination element appears. However, there is a second set of arrows inside the "current page" box which do change the number in the box, but don't change anything else. These are visible on hover in chrome, and should be checked in both browsers.

^^ This is exactly how it works in the PF docs (we are just using a wrapped version of the PF Pagination component).  So I don't think this is our issue (if it's even an issue).  See http://patternfly-react.surge.sh/components/pagination in both Chrome and FF.

> Tooltips on all forms are weirdly out of alignment when compared to chrome.

^^ wasn't able to reproduce this one

> When viewing the form for a new survey for a job template, tooltips and the "Required" button are out of alignment.

Here's chrome:

<img width="1675" alt="Screen Shot 2021-06-02 at 11 12 46 AM" src="https://user-images.githubusercontent.com/9889020/120505980-8130cd00-c393-11eb-95a5-0b500a887b05.png">

Here's firefox:

<img width="1671" alt="Screen Shot 2021-06-02 at 11 12 23 AM" src="https://user-images.githubusercontent.com/9889020/120506004-868e1780-c393-11eb-8e7b-68d011773fca.png">

I think this looks fine.

@tiagodread @one-t @akus062381 I don't think any of this is still relevant.  I'm going to close but if you'd like to verify feel free to re-open and apply needs_test.
