### ISSUE TITLE
CodeCommit project source

### ISSUE THREAD

**Issue by nickjmv** [ansible/awx#7397]
Proposed feature:
 
- It would come in handy if we could pull our code from CodeCommit but I'm unable to make this work atm.
Unless someone could guide me through it it would be a nice feature in the future.

**Comment by ryanpetrello** [comment]
@nickjmv shouldn't this just work?  AWX supports pulling code from git repositories - isn't CodeCommit just a service for hosted git repositories?

**Comment by nickjmv** [comment]
Yes I found a solution this morning. I had to use https credentials instead of SSH I think..
