### ISSUE TITLE
Missing Credential in Job Template API Payload AWX 7.0.0.0

### ISSUE THREAD

**Issue by richzzzz** [ansible/awx#7398]
##### ISSUE TYPE
 - Missing Credential in Job Template API Payload AWX 7.0.0.0
##### SUMMARY
We recently migrated from AWX 1.0.8.0 to AWX 7.0.0.0. 

We had a job that used the Tower API endpoint to create a template and attach appropriate credentials to it during creation.  The payload example was like below with Credential as one of the keys.  This allowed us to attach the credential to the template at time of creation via the template API endpoint. This seems to be no longer available in AWX 7.0.0.0.

Here is the payload for old version 1.0.8.0 that had 'credential' and worked:

AWX 1.0.8.0
{
    "name": "",
    "description": "",
    "job_type": "run",
    "inventory": null,
    "project": null,
    "playbook": "",
    "forks": 0,
    "limit": "",
    "verbosity": 0,
    "extra_vars": "",
    "job_tags": "",
    "force_handlers": false,
    "skip_tags": "",
    "start_at_task": "",
    "timeout": 0,
    "use_fact_cache": false,
    "host_config_key": "",
    "ask_diff_mode_on_launch": false,
    "ask_variables_on_launch": false,
    "ask_limit_on_launch": false,
    "ask_tags_on_launch": false,
    "ask_skip_tags_on_launch": false,
    "ask_job_type_on_launch": false,
    "ask_verbosity_on_launch": false,
    "ask_inventory_on_launch": false,
    "ask_credential_on_launch": false,
    "survey_enabled": false,
    "become_enabled": false,
    "diff_mode": false,
    "allow_simultaneous": false,
    **"custom_virtualenv": null,
    "credential": null,**
    "vault_credential": null
}

##### ENVIRONMENT
* AWX version: 7.0.0.0
* AWX install method: openshift, on linux
* Ansible version: 2.8.4
* Operating System: RHEL
* Web Browser: Chrome

##### STEPS TO REPRODUCE

AWX 1.0.8.0 with ansible 2.6.4 had 'credential' available in the payload (as shows above) for Job template API endpoint. This is not available on migration to AWX 7.0.0.0 and ansible  2.8.4. Payload below.

AWX 7.0.0.0  new version , no 'credential' in payload, no way to attach a credential to a template during creation:

{
    "name": "",
    "description": "",
    "job_type": "run",
    "inventory": null,
    "project": null,
    "playbook": "",
    "scm_branch": "",
    "forks": 0,
    "limit": "",
    "verbosity": 0,
    "extra_vars": "",
    "job_tags": "",
    "force_handlers": false,
    "skip_tags": "",
    "start_at_task": "",
    "timeout": 0,
    "use_fact_cache": false,
    "host_config_key": "",
    "ask_scm_branch_on_launch": false,
    "ask_diff_mode_on_launch": false,
    "ask_variables_on_launch": false,
    "ask_limit_on_launch": false,
    "ask_tags_on_launch": false,
    "ask_skip_tags_on_launch": false,
    "ask_job_type_on_launch": false,
    "ask_verbosity_on_launch": false,
    "ask_inventory_on_launch": false,
    "ask_credential_on_launch": false,
    "survey_enabled": false,
    "become_enabled": false,
    "diff_mode": false,
    "allow_simultaneous": false,
    "custom_virtualenv": null,
    "job_slice_count": 1
}

##### ACTUAL RESULTS

Any assistance or workaround is much appreciated!

**Comment by ryanpetrello** [comment]
Hey @richzzzz,

Years ago, we added support for managing assignment of multiple credentials to Job Templates.  As part of this, a new endpoint was introduced for attaching and detaching credentials, `/api/v2/job_templates/N/credentials/`, and the old method for attaching a singular credential (what you've been using) was deprecated:

https://github.com/ansible/awx/blob/devel/docs/credentials/multi_credential_assignment.md

In a recent version of AWX (it looks like 7.0.0 to me), we officially removed support for the old method after a prolonged deprecation period.  Try the new method instead:

```http
POST /api/v2/job_templates/N/credentials/

{
    "credential": 123,
    "associate": true
}
```

```http
POST /api/v2/job_templates/N/credentials/

{
    "credential": 123,
    "disassociate": true
}
```

**Comment by marcos-bonfanti-me** [comment]
Hi, this is not working
`{
    "name": [
        "This field is required."
    ],
    "credential_type": [
        "This field is required."
    ]
}`


How can we add new credentials via API, I can't find this in the documentation

**Comment by rockesh7** [comment]
> Hi, this is not working `{ "name": [ "This field is required." ], "credential_type": [ "This field is required." ] }`
> 
> How can we add new credentials via API, I can't find this in the documentation

Hi @marcos-bonfanti refer this https://docs.ansible.com/ansible-tower/latest/html/towerapi/api_ref.html#/Job_Templates/Job_Templates_job_templates_credentials_create
