### ISSUE TITLE
awx_redis exited with code 132

### ISSUE THREAD

**Issue by tsdragon** [ansible/awx#7407]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Redis container exiting with code 132

##### ENVIRONMENT
* AWX version: 12.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.4
* Operating System: RHEL 7
* Web Browser: N/A

##### STEPS TO REPRODUCE
Run install.yml

##### EXPECTED RESULTS
Redis container starts with the rest of the containers

##### ACTUAL RESULTS

Redis container stuck in boot loop, container state constantly says "Rebooting"

##### ADDITIONAL INFORMATION

The redis container exits too quickly for logs to even be generated.  if I navigate to the awxcompose folder that was created and attempt to run docker-compose up to monitor startup of the stack, the second line is 
```awx_redis exited with code 132```

**Comment by wenottingham** [comment]
We'd need whatever logs here you can get; there isn't enough here to determine.

**Comment by wenottingham** [comment]
Closing, please reopen if/when you have the required information.
