### ISSUE TITLE
AWX HA (2 instances) Invalid search term entered. GET returned: 500 Une erreur serveur s'est produite.

### ISSUE THREAD

**Issue by bouluad** [ansible/awx#7409]
I have a HA AWX with 2 instances (actif /actif) with a LB (HAPROXY), everything works good, but when i try to run a job works but i get 500 error when i try te see the job details.
Log :

awx.main.models.events.ProjectUpdateEvent.MultipleObjectsReturned: get() returned more than one ProjectUpdateEvent -- it returned 2

##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by ryanpetrello** [comment]
@bouluad 

Please update this issue with the requested environmental data:

> AWX version: X.Y.Z
> AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
> Ansible version: X.Y.Z
> Operating System:
> Web Browser:
