### ISSUE TITLE
Add `description` to the default search options on relevant lists

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7410]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
~~Seems reasonable that a user may want to search by description on this list.  That would make the defaults:~~

~~Name~~
~~Description~~
~~Created By~~
~~Modified By~~

Repurposing this as I think there are a number of lists that could benefit from adding this option to the default search.

- Organizations list
- Teams list
- Notifications list

**Comment by nixocio** [comment]
I clarified with @trahman73 about this feature. Even though `description` is not displayed on the on the list itself, the `description` field should be added as part of the search option.

**Comment by dsesami** [comment]
This looks great, is stubbed intrinsically as it isn't adding anything we haven't already specified, and will be closed by #8229
