### ISSUE TITLE
Add edit button to Organization -> Teams list rows

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7412]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
If the user has the proper permissions to edit a team we should provide them with an edit button on this list:

<img width="1452" alt="Screen Shot 2020-06-22 at 1 12 44 PM" src="https://user-images.githubusercontent.com/9889020/85316105-2ce65300-b48a-11ea-83a1-f7af2eeb2958.png">

which would redirect them to `/#/teams/:id/edit`.

This would be consistent with list behavior throughout the app.

**Comment by dsesami** [comment]
This can be closed with the merge of #7444
