### ISSUE TITLE
auto-logout warning is behind survey editor

### ISSUE THREAD

**Issue by tp199314** [ansible/awx#7417]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
I was editing a survey of a job template for a long time with many modifications and additions. Sadly, AWX ran into some kind of timeout and when hitting "save" i got the login screen. 

##### ENVIRONMENT
* AWX version: 12.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.9
* Operating System: Ubuntu (AWX Server) Windows 10 (Client)
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Open job template
2. Hit "edit survey"
3. Edit something and wait a huge amount of time (or so)
4. Hit "save"

##### EXPECTED RESULTS

Would be nice to deactivate the timeout or to prevent dataloss in another way.

##### ACTUAL RESULTS

Got redirected to login screen - all added/edited data was gone.

##### ADDITIONAL INFORMATION

I noticed, that there were a auto-logout-warning the other day, maybe it is possible to show this in front of the survey-edit-screen. :)

**Comment by wenottingham** [comment]
> I noticed, that there were a auto-logout-warning the other day, maybe it is possible to show this in front of the survey-edit-screen. :)

That's the bug. We'll look at this in the ongoing UI rewrite.
