### ISSUE TITLE
Unable to install AWX

### ISSUE THREAD

**Issue by akai257** [ansible/awx#7421]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: Latest 
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  Latest 
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

fatal: [localhost]: FAILED! => {
    "assertion": "postgres_data_dir is defined and postgres_data_dir != ''",
    "changed": false,
    "evaluated_to": false,
    "msg": "Set the value of 'postgres_data_dir' in the inventory file."
}
##### EXPECTED RESULTS

Ansible version 2.10

**Comment by ryanpetrello** [comment]
Hey @akai257,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

You may want to take a glance at this part of the install docs; deploying "Latest" can mean a lot of things to different people, and you might want to ensure that you're _actually_ deploying the latest _stable_ release of AWX (12.0.0).

https://github.com/ansible/awx/blob/devel/INSTALL.md#clone-the-repo

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
