### ISSUE TITLE
Add Ability to Generate User Reports For Auditing Purposes

### ISSUE THREAD

**Issue by imareporter** [ansible/awx#7423]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

An user is requesting the ability to generate auditing reports (e.g. HTML, PDF) for Tower users. They're requesting a user list that shows:

- Which projects an user has access to
- Which roles the user has across Tower resources (e.g. projects)

Though it's possible to generate a custom solution around the Tower API, it would be more user-intuitive if this could be an inherent ability in Tower.

**Comment by wenottingham** [comment]
This is /api/v2/users/N/roles (and/or access_list), and is viewable under the 'permissions' tab for a user. We do not have plans to do reporting beyond that until/if there is a much more general reporting framework.
