### ISSUE TITLE
Please provide release notes

### ISSUE THREAD

**Issue by JG127** [ansible/awx#7428]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Compile human readable release notes describing for each release what changes have been made. Changes like bug fixing, added features, changes in the used software (i.e. Postgres, Memcached, ...), improvement in performance, how to migrate, etc...

It would help people immensely to decide whether to do an upgrade or stay put. Especially for the non-technical users. 

One might argue you 'just' have to check the commit history for that. However, even to the technically savvy people commit comments like "Merge PR xyz" don't suggest much about the final implications for AWX.

**Comment by ryanpetrello** [comment]
Yep, this exists, and we publish it here:

https://github.com/ansible/awx/blob/devel/CHANGELOG.md

Also, our release announcements on the mailing list generally include this information:

https://groups.google.com/forum/#!topic/awx-project/8Y5cftbetjE

**Comment by JG127** [comment]
I stand corrected ! :-)
