### ISSUE TITLE
inventory script with project source not work in ui

### ISSUE THREAD

**Issue by chris93111** [ansible/awx#7429]
##### ISSUE TYPE
 - Bug Repor

##### SUMMARY

because inventory script /api/v2/inventory_scripts/ is deprecated i try to migrate to project_source 

the refresh source in awx stuck but cmd awx-manage inventory_import is work. 

##### ENVIRONMENT
* AWX version: 12.0.0
* AWX install method: docker
* Ansible version:  2.9.9
* Operating System: redhat
* Web Browser: chrome

##### STEPS TO REPRODUCE

set source to inventory with project and target script python , default venv and try refresh (verbose mode)

##### EXPECTED RESULTS

inventory import success or display error in ui 

##### ACTUAL RESULTS

the refresh job stuck

    2.567 INFO     Updating inventory 64: equipe_itg
    3.120 DEBUG    Using base command: python /usr/bin/ansible-inventory -i /tmp/awx_253_8cmyst9w/project/get_inventory/consul/cmdb_ansible.py --playbook-dir /tmp/awx_253_8cmyst9w/project/get_inventory/consul -vvvvv
    3.120 INFO     Reading Ansible inventory source: /tmp/awx_253_8cmyst9w/project/get_inventory/consul/cmdb_ansible.py
    3.122 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible/
    3.122 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/usr/pgsql-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    3.122 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages: 

##### ADDITIONAL INFORMATION

manually exec cmd work correctly 

python /usr/bin/ansible-inventory -i /tmp/awx_253_8cmyst9w/project/get_inventory/consul/cmdb_ansible.py --playbook-dir /tmp/awx_253_8cmyst9w/project/get_inventory/consul -vvvvv

or

/var/lib/awx/venv/awx/bin/python3 /var/lib/awx/venv/awx/bin/awx-manage inventory_import --inventory-id 64 --venv /var/lib/awx/venv/ansible/ --group-filter ^.+$ --host-filter ^.+$ --source /tmp/awx_245_v_3e74cs/project/get_inventory/consul/cmdb_ansible.py -v2

    2.464 INFO     Updating inventory 64: equipe_itg
    3.279 DEBUG    Using base command: python /usr/bin/ansible-inventory -i /tmp/awx_245_v_3e74cs/project/get_inventory/consul/cmdb_ansible.py --playbook-dir /tmp/awx_245_v_3e74cs/project/get_inventory/consul -vvvvv
    3.280 INFO     Reading Ansible inventory source: /tmp/awx_245_v_3e74cs/project/get_inventory/consul/cmdb_ansible.py
    3.282 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible/
    3.282 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/ansible/bin:/usr/pgsql-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    3.282 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
    8.986 ERROR    ansible-inventory 2.9.9
    8.986 ERROR      config file = /etc/ansible/ansible.cfg
    8.986 ERROR      configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
    8.986 ERROR      ansible python module location = /usr/lib/python3.6/site-packages/ansible
    8.986 ERROR      executable location = /usr/bin/ansible-inventory
    8.986 ERROR      python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
    8.986 ERROR    Using /etc/ansible/ansible.cfg as config file
    8.986 ERROR    setting up inventory plugins
    8.986 ERROR    host_list declined parsing /tmp/awx_245_v_3e74cs/project/get_inventory/consul/cmdb_ansible.py as it did not pass its verify_file() method
    8.986 ERROR    Parsed /tmp/awx_245_v_3e74cs/project/get_inventory/consul/cmdb_ansible.py inventory source with script plugin
    8.987 DEBUG    Finished loading from source: /tmp/awx_245_v_3e74cs/project/get_inventory/consul/cmdb_ansible.py
    8.987 INFO     Processing JSON output...
    8.987 DEBUG    Loaded group: all
    8.987 DEBUG    Loaded group: integration_cnaf_va_linux_apache_standard
    8.987 DEBUG    Adding child group integration_cnaf_va_linux_apache_standard to parent all
2020-06-24 10:04:49,329 DEBUG    awx.main.models.inventory Going to update inventory computed fields, pk=64
2020-06-24 10:04:49,368 DEBUG    awx.main.models.inventory Finished updating inventory computed fields, pk=64, in 0.038 seconds
    9.283 INFO     Inventory import completed for  (equipe_itg - 29) in 6.8s

vault_password appear when cancel job in ui 

![image](https://user-images.githubusercontent.com/27526373/85540266-13bedd00-b617-11ea-9be0-b0ddd4adc825.png)

**Comment by chris93111** [comment]
with 13.0.0 it's same

**Comment by blomquisg** [comment]
@AlanCoding I wonder if this is similar to #7443 .  Can you check both of these out?

**Comment by wenottingham** [comment]
That error implies that you have vaulted variables (in group_vars or host_vars) adjacent to the inventory script, so it's asking for a vault password. Can you check that, and move them out of the way?

**Comment by chris93111** [comment]
@wenottingham it's right , i have isolate the script inventory in other git and is work 

so global project with vaulted vars it's not compatible with inventory script in scm ?

**Comment by wenottingham** [comment]
Inventory-adjacent whole vaulted files do not work. See https://github.com/ansible/awx/issues/2597 and other issues.

I'm going to close this as working as expected.

**Comment by chris93111** [comment]
ok thanks
