### ISSUE TITLE
URL absolute instead of relative

### ISSUE THREAD

**Issue by keith6014** [ansible/awx#7439]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Some links are absolute instead of relative.

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker
* Ansible version:  2.9.10
* Operating System: Linux
* Web Browser: Chrome/IE

##### STEPS TO REPRODUCE

Connect to AWX. At home page, links in dashboard-list for jobs, dashboard-count and activity-stream are absolute.

##### EXPECTED RESULTS

Relative links (awx/#/...)  . "awx" is from a URI path

##### ACTUAL RESULTS

Absolute links (/#/...)

##### ADDITIONAL INFORMATION

This affects when I upstream a proxy (nginx). When I click on a link such as: "Hosts", it goes to #/hosts where as it should goto /awx/hosts". This breaks nginx upstreams.

**Comment by wenottingham** [comment]
-> #3879
