### ISSUE TITLE
select button missing in webhook select credential

### ISSUE THREAD

**Issue by mikemurray86** [ansible/awx#7441]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
when setting up a new webhook and selecting a credential there is no way to confirm the credential selection

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.10
* Operating System: ubuntu 18.04
* Web Browser: Chrome, Edge

##### STEPS TO REPRODUCE

1. create new gitlab personal access token credential
2. configure job template to use webhook. 
3. attempt to select previously created credential in the webhook credential field 

##### EXPECTED RESULTS

select button visible to select the credential

##### ACTUAL RESULTS

list of credentials displayed with no way to select the credential 

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/547513/85634005-b424f980-b637-11ea-9394-9a150765dfc5.png)

**Comment by wenottingham** [comment]
@mabashian is this jquery upgrade fallout, or something else?

**Comment by blomquisg** [comment]
@jakemcdermott can you answer @wenottingham's question?

**Comment by wenottingham** [comment]
This should be fixed in the next AWX release, please try when that's available.

**Comment by fidanf** [comment]
Still appears in 15.0.1
