### ISSUE TITLE
EC2 Inventory Sync Issues with v13.0.0

### ISSUE THREAD

**Issue by JRNC** [ansible/awx#7443]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWS EC2 inventory sync is no longer pulling down hosts after moving to version 13.0.0, but job status completes as successful.

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.10
* Operating System: RHEL 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Attempt to run an EC2 inventory sync on AWX v13.0.0

##### EXPECTED RESULTS

The EC2 inventory sync would pull down more than 0 hosts and update the facts for the hosts in the inventory.

##### ACTUAL RESULTS

    3.064 INFO     Updating inventory 8: Windows_Servers
    3.740 INFO     Reading Ansible inventory source: /tmp/awx_9945_1ckq7nqv/aws_ec2.yml
    3.742 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    3.742 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/usr/pgsql-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    3.742 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
    5.288 ERROR    ansible-inventory 2.9.10
    5.288 ERROR      config file = /etc/ansible/ansible.cfg
    5.288 ERROR      configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
    5.288 ERROR      ansible python module location = /usr/lib/python3.6/site-packages/ansible
    5.288 ERROR      executable location = /usr/bin/ansible-inventory
    5.288 ERROR      python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
    5.289 ERROR    Using /etc/ansible/ansible.cfg as config file
    5.289 ERROR    Parsed /tmp/awx_9945_1ckq7nqv/aws_ec2.yml inventory source with auto plugin
    5.289 INFO     Processing JSON output...
    5.289 INFO     Loaded 1 groups, 0 hosts
2020-06-25 14:12:04,531 DEBUG    awx.main.models.inventory Going to update inventory computed fields, pk=8
2020-06-25 14:12:04,555 DEBUG    awx.main.models.inventory Finished updating inventory computed fields, pk=8, in 0.023 seconds
    5.345 INFO     Inventory import completed for AWS - US-EAST-1 (N. Virginia) - EC2 - Windows - Prod in 2.3s

##### ADDITIONAL INFORMATION

Instance Filters: tag:Platform=Windows*,tag:Environment=PROD

Source Variables: 
hostname_variable: 'tag:name=value'
destination_format: "{0}.OUR.DOMAIN.COM"
destination_format_tags: Name
stack_filters: True

**Comment by blomquisg** [comment]
@AlanCoding can you look at that error output?

**Comment by ryanpetrello** [comment]
What version of AWX did you upgrade from?

**Comment by JRNC** [comment]
@ryanpetrello I went from 12.0.0 to 13.0.0

**Comment by AlanCoding** [comment]
Do you know if it's a particular instance filter giving trouble? Like `tag:Platform=Windows*`? We have some tests fairly similar to this syntax and nothing easily comes to my mind.

**Comment by JRNC** [comment]
@AlanCoding, I did a bunch of trial and error with a temporary inventory. The filters seem to be fine, but I'm assuming that an update to the EC2 inventory plugin is no longer properly leveraging the hostname_variable source variable. In addition to that, when testing different syntax, the error message refers back to using 'tag:name=value', which does not work.

Error message when attempting different syntax for hostname_variable:
[WARNING]:  * Failed to parse /tmp/awx_10028_sg5bqx_f/aws_ec2.yml with auto
plugin: To name a host by tags name_value, use 'tag:name=value'.

**Comment by JRNC** [comment]
It appears as though using 'tag:Name' for the hostname_variable will provide the desired result (this value is case sensitive). This might be a matter of documentation/fixing the wording for the error and/or creating some backwards compatibility for source variable syntax that worked previously.

**Comment by JRNC** [comment]
Unfortunately, it also looks like the destination_format and destination_format_tags source variables aren't working properly. The inventory sync will complete successfully, but there is no "ansible_host" variable set for any of the hosts that are pulled down from AWS.

**Comment by JRNC** [comment]
For anyone who is running into the same thing, this can be used for a workaround:

destination_variable: tags.Name + ".OUR.DOMAIN.COM"

It looks like this is the conditional statement to target for the bugfix: https://github.com/ansible/awx/blob/d8f6ea3fe89eaa6aea375dfa0280b43c66899ae0/awx/main/models/inventory.py#L1987-L1991

If project contributors agree with this approach, it looks like something along the lines of an additional conditional statement could be written beforehand to look for the destination_format and destination_format_tags source_vars and set the destination_variable to those source_vars concatenated. I guess it is a question of whether backwards compatibility should be built in or documentation should be updated (possibility with a deprecation warning when destination_format and destination_format_tags are used).

**Comment by wenottingham** [comment]
Please try AWX 15.0 - we change how inventory is configured in that release and we think you should be able to accomplish what you need there.
