### ISSUE TITLE
Add smart inventory detail view 

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#7456]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
1) Fields:
    - Name
    - Description
    - Type
    - Activity 
    - Organization
    - Smart host filter
    - Instance groups
    - Variables
    - Created by
    - Modified by
2) Edit button (rbac permitting)
3) Delete button (rbac permitting)

Link to mockup: https://tower-mockups.testing.ansible.com/patternfly/inventories/inventories-smart-detail/

**Comment by dsesami** [comment]
There was an issue involving the smart host filter chip that i discussed with @marshmalien in that long filters would run off the page. however, we agreed on adding an ellipsis to shorten it, and she will handle it as part of the work on the #7472 / #7473  work.
