### ISSUE TITLE
Add support for cluster mode with docker-compose method of deploy

### ISSUE THREAD

**Issue by bryanasdev000** [ansible/awx#7458]
##### ISSUE TYPE
Add support for cluster mode with docker-compose method of deploy

##### SUMMARY
With the official role we can already set up the `docker-compose.yml` on multiple machines but they will not go in cluster mode as all will report as awx (both in `CLUSTER_HOST_ID` and by the hostname of the `awx_task `container), if we change the `settings.py` to get the `CLUSTER_HOST_ID` by environment variable, the hostname in `docker-compose.yml` (paired with `CLUSTER_HOST_ID`) and send `CLUSTER_HOST_ID` in `environment.sh.j2` we can easily create an AWX cluster running on top of a few simple docker-composes.

I am already working on this possibility, but I would like to know how much these changes will impact the deployment through Kubernetes or OpenShift since it will affect the image of the container.

Link to my fork: https://github.com/bryanasdev000/awx/commits/clustering

I would also like to understand the role of UUID in this case (join / left of the cluster) since a quick look at the code shows me that it uses hostname and `CLUSTER_HOST_ID` only.

**Comment by ryanpetrello** [comment]
Hey @bryanasdev000,

Unfortunately, we don't have any long-term plans to support this.

Here's a duplicate issue w/ a comment that describes why:

https://github.com/ansible/awx/issues/3627#issuecomment-480251701

**Comment by bryanasdev000** [comment]
Hi @ryanpetrello!

I understand, well then I will close the issue, I will try to keep my fork in my spare time, since in the current version it requires little maintenance beyond the execution of the docker role.

Thank you.

**Comment by ryanpetrello** [comment]
Hey @bryanasdev000,

As with any contribution/fork like this, please feel free to contact me if you notice we've unintentionally broken something, or you've just got questions about AWX in general, and I'm happy to answer questions and oblige in general!

**Comment by bryanasdev000** [comment]
> Hey @bryanasdev000,
> 
> As with any contribution/fork like this, please feel free to contact me if you notice we've unintentionally broken something, or you've just got questions about AWX in general, and I'm happy to answer questions and oblige in general!

Ok, thank you very much!
