### ISSUE TITLE
Allow networking credentials to be used to configure a template alone.

### ISSUE THREAD

**Issue by benthomasson** [ansible/awx#747]
Networking credentials should be sufficient to configure a template without an SSH credential.

<img width="357" alt="screen shot 2017-11-30 at 8 44 21 am" src="https://user-images.githubusercontent.com/44381/33433831-2e5f0828-d5ab-11e7-9aac-844b8fca19b7.png">

**Comment by ryanpetrello** [comment]
This is a situation where the UI hasn't caught up w/ the API changes in https://github.com/ansible/awx/pull/595.

https://github.com/ansible/awx/blob/bfea00f6dc6af0fb01057ce38e9d0337e6c589aa/awx/ui/client/src/templates/job_templates/multi-credential/multi-credential.directive.js#L43

This SSH requirements is specific to the UI, and can just be removed now - the API won't complain if you only send it one net credential.

**Comment by benthomasson** [comment]
I have a work-around for this that uses machine credentials and there is a new network_cli credential type that is coming and it is compatible with machine credentials.

**Comment by jakemcdermott** [comment]
resolved by: https://github.com/ansible/awx/pull/976
