### ISSUE TITLE
Smart Inventory Add Form

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#7472]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Fields:
1. Name 
    * Required
2. Description 
3. Organization 
    * Required
    * Organizations populate from `/api/v2/organizations/?page_size=5&order_by=name&role_level=inventory_admin_role`
4. Smart host filter
    * Required
    * In the old UI we disable this field until Organization has a value 
    * Hosts populate from ` /api/v2/hosts/?order_by=name&page_size=5&inventory__organization=:org-id`
    * Lookup UX will need to consider how to populate filter keys: https://github.com/ansible/awx/issues/5513
    * The host filter supports relational queries, `and` `or` boolean logic, and expression grouping via `()`. I'm not sure what the UX will look like, but this advanced filter work will probably follow the same pattern as advanced search. 
        * Example: `(name=my_host and groups__name="my group") or (name=my_host2 and groups__name=my_group2)`
5. Instance groups
    * Instance groups populate from `/api/v2/instance_groups/?order_by=name&page_size=5`
6. Variables

Action Buttons:
1. Cancel
    * Navigate to Inventories list
2. Save 
    * Navigate to Smart inventory detail on successful save

Link to mockup: https://tower-mockups.testing.ansible.com/patternfly/inventories/inventories-smart-add/

**Comment by dsesami** [comment]
closed with the merge of #7644
