### ISSUE TITLE
Smart Inventory Edit Form

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#7473]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
More details in smart inventory add form issue: #7472 

Fields:
1. Name 
    * Required
2. Description 
3. Organization 
    * Required
    * Organizations populate from `/api/v2/organizations/?page_size=5&order_by=name&role_level=inventory_admin_role`
4. Smart host filter
    * Required
    * In the old UI we disable this field until Organization has a value 
    * Hosts populate from ` /api/v2/hosts/?order_by=name&page_size=5&inventory__organization=:org-id`
    * Mockup:  https://tower-mockups.testing.ansible.com/patternfly/inventories/inventories-smart-edit-filter/
5. Instance groups
    * Instance groups populate from `/api/v2/instance_groups/?order_by=name&page_size=5`
6. Variables

Action Buttons:
1. Cancel
    * Navigate to inventories list
2. Save 
    * Navigate to smart inventory detail

Link to mockup: https://tower-mockups.testing.ansible.com/patternfly/inventories/inventories-smart-edit/

**Comment by dsesami** [comment]
closed with the merge of #7644
