### ISSUE TITLE
[awx_collection] Manage users in teams; manage teams/users in templates

### ISSUE THREAD

**Issue by iridian-ks** [ansible/awx#7475]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Right now, I'm generating maybe ~100 job templatres with Ansible. Some of the jobs are duplicates and simply prefill different variables (environments, etc...). Different users have access to different environments. We use the automatic LDAP mapping to get users into Organizations, but it looks like a job/workflow template can only be a part of a single organization so creating these jobs and handing them off to different teams by leveraging the awx_collection seems impossible (at the moment) (I could also just be missing something).

My initial thought is to create Teams under my Organization and put users in those teams. Basically, a team per environment. Then map the job templates to those teams. When those users login they then see only the jobs they have access to. For example, devs can access dev environments and wouldn't be able to accidentally modify variables to target production, etc.

Either under `tower_team` or `tower_user` I feel like we should be able to add users to a team. It looks like that's not possible right now?

Also, under `tower_job_template` we should be able to manage the users/teams that have access to them. That also doesn't seem to be possible, right now?

I was very surprised to see the lack of functionality and my first thought is that I'm simply missing something, which might be the case and I'm just not smart enough to find the right module to manage the mappings.

**Comment by wenottingham** [comment]
This is what `tower_role` is for.

**Comment by iridian-ks** [comment]
I knew I was missing something... sometimes in Ansible module documentation you can find related modules. I'm wondering if I could take a stab at providing links in the docs so that `tower_team` and `tower_job_template` can link out to `tower_role`. Maybe that could help others?

**Comment by wenottingham** [comment]
Closing this specific issue, as the functionality is there.
