### ISSUE TITLE
RBAC in Ansible tower/AWX

### ISSUE THREAD

**Issue by vidyasagarreddyc** [ansible/awx#7481]
I am exposing multiple options in RBAC, For multi tenancy environment, I planned to create two org company-A and Company-B.

Created admin-usr-A to company-A org, and read-usr-A to company-A

similarly, Created admin-usr-B to company-B org, and read-usr-B to company-B

I have assigned admin permissions to user admin-usr-A in  company-A

when I am able to login as admin-usr-A,   admin-usr-A can see other users that belongs to other organization in that case admin-usr-B information like (email info), We can also create team and add other organization team members, 

It is fine do by system administrator, but not org admin

Is there way we can isolate complete info including users for org admins

**Comment by ryanpetrello** [comment]
Hey @vidyasagarreddyc,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
