### ISSUE TITLE
no update of project git revision number in webgui

### ISSUE THREAD

**Issue by ReinerNippes** [ansible/awx#7482]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After updating a project hosted on git the git revision in the expanded view in the web gui is not updated. One has to reload the web page to do so.

##### ENVIRONMENT
* AWX version: 11.2
* AWX install method: docker
* Ansible version:  2.9.9
* Operating System: Ubuntu 20.04
* Web Browser: Firefox

##### STEPS TO REPRODUCE

update a git based project 

##### EXPECTED RESULTS

git revision number changes

##### ACTUAL RESULTS

git revision number didn't changes

**Comment by unlikelyzero** [comment]
@ReinerNippes please follow this ticket: https://github.com/ansible/awx/issues/8811
