### ISSUE TITLE
Add 'ask_scm_branch' parameter support

### ISSUE THREAD

**Issue by soapjam** [ansible/awx#7486]
##### ISSUE TYPE
Feature request for adding 'ask_scm_branch' parameter to 'tower_job_template' module.

##### SUMMARY
Hello!
In our company we're actively using 'SCM branch' parameter in all AWX templates and also we've started to use playbooks for automated templates configuration, but I found that there is not ability to set "Prompt on launch" checkbox in 'tower_job_template' module. Could you please review this request? I believe it will be very helpful not only for my team, thanks in advance!

**Comment by AlanCoding** [comment]
https://github.com/ansible/awx/blob/6e6aa1fdabf712c4469b6651474f027b321c06df/awx_collection/plugins/modules/tower_job_template.py#L133

This has been around for a little while in the `awx.awx` collection now. So I'm going to close as resolved.
