### ISSUE TITLE
indicate the lookup for instance groups (possibly content source in the future) is ordered

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#7487]
there is currently no indication in the UI that this data is ordered, and the order in which they are selected sets the execution precedence.  We should consider making that lookup/the selected area order-able, as well as give the user a note that the order matters.

this may also be the case for a content source if we decide to make that hub content source stuff hav e aui

**Comment by wenottingham** [comment]
@trahman73 do we have a design for this in the new UI?

**Comment by trahman73** [comment]
@wenottingham @jlmitch5 We can take the Instance Group list view (mockup below) and apply the PatternFly draggable list component (link below). We would need some explanation text to tell the user that the selected order sets the execution precedence.

IG List View: https://tower-mockups.testing.ansible.com/patternfly/instance-groups/instance-groups-instances/
PF Draggable List: https://www.patternfly.org/v4/components/data-list#draggable

**Comment by mabashian** [comment]
link #9127 <-related.  The same thing applies to IG's

**Comment by mabashian** [comment]
Since @marshmalien is working on https://github.com/ansible/awx/issues/9127 currently it's probably wise to hold off on this one so that we can either leverage her work or at least make sure this implementation matches up with the same UX pattern(s).

Going to mark as blocked for now.

**Comment by akus062381** [comment]
resolved
