### ISSUE TITLE
Permission denied when system admin trys to access system menu

### ISSUE THREAD

**Issue by szollin** [ansible/awx#7490]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When a user that has the system administrator permission clicks on System or any of the submenus inside of system, nothing loads. When running `docker logs -f --tail 1 awx_web` and clicking on the System menu option, the following error appears. Personal information has been removed from the log output.

```
[01/Jul/2020:00:55:20 +0000] "OPTIONS /api/v2/settings/all/ HTTP/1.1" 200 64650 "https://awx.host.url.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36" "-"
2020/07/01 00:55:20 [crit] 82#0: *450 open() "/var/lib/nginx/tmp/uwsgi/5/00/0000000005" failed (13: Permission denied) while reading upstream, client: <ipaddress>, server: _, request: "OPTIONS /api/v2/settings/all/ HTTP/1.1", upstream: "uwsgi://127.0.0.1:8050", host: "awx.host.url.com", referrer: "https://awx.host.url.com/"
[pid: 78|app: 0|req: 116/429] <ipaddress> () {62 vars in 4206 bytes} [Wed Jul  1 00:55:20 2020] OPTIONS /api/v2/settings/all/ => generated 288657 bytes in 461 msecs (HTTP/1.1 200) 10 headers in 310 bytes (1 switches on core 0)
[01/Jul/2020:00:55:21 +0000] "GET /api/v2/config/ HTTP/1.1" 200 821 "https://awx.host.url.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36" "-"
[pid: 77|app: 0|req: 156/430] <ipaddress> () {56 vars in 4047 bytes} [Wed Jul  1 00:55:20 2020] GET /api/v2/config/ => generated 821 bytes in 523 msecs (HTTP/1.1 200) 10 headers in 301 bytes (1 switches on core 0)
```

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.6
* Operating System: Ubuntu 20.04
* Web Browser: Google Chrome 83.0.4103.116

##### STEPS TO REPRODUCE

Log in with a user that has system administrator permissions
Click System

##### EXPECTED RESULTS

Loads the System page

##### ACTUAL RESULTS

It pops up the loading screen but, nothing loads

##### ADDITIONAL INFORMATION

None

**Comment by szollin** [comment]
I reinstalled just in case there was something weird with the install and it is still doing it. What next steps would you like me to take? Do you need more information?

**Comment by wenottingham** [comment]
-> #7406
