### ISSUE TITLE
[ui_next] 404s should be propagated to the Edit page for resources

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#7500]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
1. Create a resource, one that has an edit form. Think Job Templates, projects; for this example, I used the applications page.
2. Open the edit form in a new tab.
3. On the original tab, delete the resource. 
4. Go to the edit form on the now-deleted resource, and try to save it.

The network tab shows a 404, but there is no visual feedback in the UI. We should include that as part of the red-box error message that appears at the bottom of the form when form validation errors occur.

**Comment by unlikelyzero** [comment]
@dsesami can you verify that still happens?

**Comment by dsesami** [comment]
There is now visual feedback. This is clear enough, IMO, and can be closed.

![Screenshot from 2020-09-15 15-35-41](https://user-images.githubusercontent.com/19942822/93256285-21dd4f00-f769-11ea-851d-c1d5a8f2f4aa.png)
