### ISSUE TITLE
YAML code editor inconsistent pretty print

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#7505]
### Steps to Recreate
```
a: b
c: d
e: [f, g, true]
```
Save a job template with the above yaml as extra vars. The first image below is the result of that save. The second image is after toggling `json` and back to `yaml`

### Expected
![image](https://user-images.githubusercontent.com/722880/86271592-28f9b580-bb9b-11ea-8b39-087eb9c79dba.png)

### Actual
![image](https://user-images.githubusercontent.com/722880/86271599-2d25d300-bb9b-11ea-9010-f07c3757484f.png)

**Comment by mabashian** [comment]
@tiagodread @one-t @akus062381 I believe that @keithjgrant fixed this with his editor changes:

![vars](https://user-images.githubusercontent.com/9889020/115883323-a983ee00-a41b-11eb-9416-5f329bf4fddc.gif)

I'm gonna move this over to needs_test

**Comment by akus062381** [comment]
verified manually and added stub for coverage.
