### ISSUE TITLE
Launch Job click-box not centered

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#7507]
![image](https://user-images.githubusercontent.com/722880/86272236-395e6000-bb9c-11ea-9af1-2b0adcea5237.png)
Left click and hold down on the job launch but don't release. Note the black box around the launch icon. It's skewed left and not centered.

**Comment by unlikelyzero** [comment]
likely the same issue as https://github.com/ansible/awx/issues/8851
