### ISSUE TITLE
Row outlined without checking or unchecking box

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#7508]
![image](https://user-images.githubusercontent.com/722880/86272356-6f9bdf80-bb9c-11ea-93f7-8ac7c9feee3d.png)
Click on a row and don't let your mouse up, drag it down as if you were highlighting to copy. The black box outlines the row, but the checkbox doesn't check nor uncheck. I'd expect the black box to not remain outlined on the row.

**Comment by mabashian** [comment]
Yea this is behavior that comes in as a result of our use of one of the PF components iirc.  I'd have to look to see if it's something we can toggle off.  Maybe they have a reason for focusing rows like this but idk off the top of my head.

**Comment by unlikelyzero** [comment]
moving to https://github.com/ansible/awx/issues/8852
