### ISSUE TITLE
Painful process to assign permissions for a Team when the list of inventories and credentials are considerable big.

### ISSUE THREAD

**Issue by cesan3** [ansible/awx#751]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

We currently have around 1000 inventories and 1000 credentials.
We want to assign permissions to certain team to a subset of inventories and credentials, (250 or 500).

Currently, the list of those objects only displays 5 elements per page and we currently don't have a select all checkbox, to make this process easier.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: docker on linux
* Ansible version:  2.4.0
* Operating System: Fedora
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Have 1000 Inventories and 1000 Credentials.
Creates 2 Teams and assign permission to 500 Inventories and 500 Credentials each.

##### EXPECTED RESULTS

This is a simple process, where I can list pages of 100 or more Items and I have a select-all checkbox to help me in the process.

We have an API point to perform this operation easilly and automated.

##### ACTUAL RESULTS

"My mouse left button doesn't work any more after my second round, and I will need phisio for my forefinger (kidding)".  The process is time consuming and annoying.

##### ADDITIONAL INFORMATION

We'd like to have an easy way via the API to automate the permission assignements...

**Comment by wenottingham** [comment]
`tower-cli role grant --team<TEAM>  <resource>` works on the API side, and should be easily scriptable if you want to automate it.

**Comment by matburt** [comment]
You can also just interface with the api roles directly to do that...  see `towerhost.tld/api/v2/`
