### ISSUE TITLE
Row checkbox deadspot

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#7510]
##### SUMMARY
There seems to be a deadspot 10-50 pixels below a resource row checkbox

##### STEPS TO REPRODUCE

Click between 10-50 pixels below a checkbox

##### EXPECTED RESULTS

Check box to check and uncheck

##### ACTUAL RESULTS

Row black box highlights.

**Comment by unlikelyzero** [comment]
covered in https://github.com/ansible/awx/issues/8852
