### ISSUE TITLE
Mobile friendly nav wacky when entries have the same name under different categories

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#7511]
##### SUMMARY
Rows per page is not respected when copying resources.

##### STEPS TO REPRODUCE

* Shrink browser until mobile view
* On the nav, click Settings --> Jobs

##### EXPECTED RESULTS

* Only the `Settings` category to be expanded

##### ACTUAL RESULTS

* `Views` category and `Settings` expand

![image](https://user-images.githubusercontent.com/722880/86275735-b809cc00-bba1-11ea-9e5f-c9bea474df30.png)
![image](https://user-images.githubusercontent.com/722880/86275755-c526bb00-bba1-11ea-834b-8729ffcda438.png)

**Comment by dsesami** [comment]
It looks like this works without issue now.
