### ISSUE TITLE
Required drop-down select boxes provide no feedback on save

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#7512]
![image](https://user-images.githubusercontent.com/722880/86276596-256a2c80-bba3-11ea-8379-11c13f2914c2.png)

Text boxes that are required give nice feedback when you click save and haven't provided a value. Single-select drop-down boxes that are required provide no feedback when save is clicked. This makes it feel like the save button is broken.

**Comment by dsesami** [comment]
dropdowns properly provide feedback. 👍
