### ISSUE TITLE
JT Survey select all checkbox visible when no survey entries

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#7513]
![image](https://user-images.githubusercontent.com/722880/86277499-cb6a6680-bba4-11ea-8d45-6b04dd7cc790.png)
The "select all" checkbox is displayed even when there are no items to select. Also, what the on/off toggle does isn't super clear.

edit: I've noticed that showing the "select all" checkbox when there are no results is a normal pattern in the new UI. I guess because there isn't a sort-by nor a search box, it just looked different. The on/off toggle, however, is not a normal pattern and is confusing in this case.

**Comment by unlikelyzero** [comment]
During `needs_test` verification, please add testcase (or stub)

**Comment by unlikelyzero** [comment]
Fixed with an empty state update
