### ISSUE TITLE
reconfigure_rsyslog assumes it is enabled and has a supervisor

### ISSUE THREAD

**Issue by kapouer** [ansible/awx#7514]
I've been busy making a debian package for awx 13.0.0 using virtualenv,
and in debian, assuming rsyslog isn't correct, so when i tried to disable it,
https://github.com/ansible/awx/blob/e3e69b4c6b48fb3c6384b41c85e4ac3b2f23e063/awx/main/utils/external_logging.py#L114
was called anyway.

It would be great this function was not assuming things about the environment.
LOG_AGGREGATOR_ENABLED should be used ? I don't know.

**Comment by ryanpetrello** [comment]
Hey @kapouer,

AWX's entire logging integration is based on rsyslogd, and it assumes rsyslogd is available, so none of this is going to work in environments where rsyslogd isn't available.

**Comment by kapouer** [comment]
OK.
(though it does work with proper logger config and a check in that reconfigure_syslog function... but i don't want to look like arguing).
