### ISSUE TITLE
Refactor FormSubmitError to use fully unit tested util

### ISSUE THREAD

**Issue by keithjgrant** [ansible/awx#7515]
##### ISSUE TYPE
 - Improvement

##### SUMMARY
The FormSubmitError component does some complicated parsing of API error responses, which it then passes to Formik and/or displays as a general error to the user. This logic should be moved into a util function with a full array of unit tests to account for all the various structures that the API might return.

**Comment by keithjgrant** [comment]
@mabashian — I'd like to pick your brain a bit on some of the changes you made here to make sure I understand all the permutations of these error messages before proceeding.

**Comment by AlexSCorey** [comment]
We have a util, in there also `getErrorMessage` used by `<ErrorDetail>` which could be use to generate the error messages for `<FormSubmitError>`
