### ISSUE TITLE
Change `Completed Jobs` tabs to `Jobs`

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#7516]
##### STEPS TO REPRODUCE

* Launch a job
* go to that JT's Completed Jobs tab
* Relaunch
* Quickly click back

##### EXPECTED RESULTS

For the newly launched and running job to not be in the list

##### ACTUAL RESULTS

Running job is in the list

##### ADDITIONAL INFORMATION

Maybe completed jobs tab is intended to show all jobs for the job template. In that case rename it.

**Comment by unlikelyzero** [comment]
During `needs_test` verification, please add testcase (or stub)

**Comment by mabashian** [comment]
@wenottingham Chris brings up an interesting point.  We can certainly filter this list down to only completed jobs or we could repurpose this list to show all jobs for a particular JT.

**Comment by mabashian** [comment]
My vote here would be to simply change the name of the tab from `Completed Jobs` to `Jobs`.  I don't see any harm in listing all the jobs for a particular resource.  Whatever we decide, we should apply the change to all the places where we have `Completed Jobs` tabs.
