### ISSUE TITLE
Delete role in User Access list results in 404

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#7517]
##### SUMMARY
Deleting a user role in the UI results in a 404

##### STEPS TO REPRODUCE

* Add a role to user via user --> Access
* Delete that added role

##### EXPECTED RESULTS

* For the role to be deleted

##### ACTUAL RESULTS

* 404 popup

![image](https://user-images.githubusercontent.com/722880/86280012-053d6c00-bba9-11ea-8b09-04d3a52c4f54.png)

Note the url has an extra `/`

Also note the `{0}`. This may be fixed and related to translation fixup work.

![image](https://user-images.githubusercontent.com/722880/86280343-97de0b00-bba9-11ea-8dcc-94a27ccf596a.png)

**Comment by unlikelyzero** [comment]
During `needs_test` verification, please add testcase (or stub)

**Comment by unlikelyzero** [comment]
Assigning to myself to test

**Comment by AlexSCorey** [comment]
@unlikelyzero I am unable to reproduce this bug at this time.  Can you test to confirm that it is resolved?

**Comment by unlikelyzero** [comment]
covered in user-tabs.spec.js
