### ISSUE TITLE
JT survey edit breadcrumb clicking goes to blank view

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#7522]
##### STEPS TO REPRODUCE

* Create a JT with a survey
* Add a survey item
* Click to edit that survey item
* Note the breadcrumbs at the top, click "Edit Question"

##### EXPECTED RESULTS

Probably for it to not be clickable

##### ACTUAL RESULTS

Sent to a blank view. Also note the "Back to Templates" is blue and underlined when I am editing a survey question. The survey question should probably be the thing blue and underlined.

![image](https://user-images.githubusercontent.com/722880/86284135-45541d00-bbb0-11ea-99c5-175633ea8273.png)

![image](https://user-images.githubusercontent.com/722880/86284123-4127ff80-bbb0-11ea-8eda-88d8c6847422.png)

**Comment by unlikelyzero** [comment]
During `needs_test` verification, please add testcase (or stub)

**Comment by mabashian** [comment]
`Edit Question` should not be a link in this case

**Comment by tiagodread** [comment]
Verified that:

The user can create and edit a JT survey
Can navigate to survey list using breadcumb links
Can enable survey
Can delete survey
Can launch a JT with survey enabled

Added coverage in 5819
