### ISSUE TITLE
Can't import/export inventory sources with custom inventory script

### ISSUE THREAD

**Issue by elyezer** [ansible/awx#7528]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

When trying to export an inventory with a custom inventory script the following message is printed:

```
This endpoint is deprecated: /api/v2/inventory_scripts/1/
Foreign key 'source_script' export failed for object /api/v2/inventory_sources/24/, setting to null
```

And that generates an inventory source with partial data exported since the `source_script` is not being populated. For example

```json
    {
      "credential": null,
      "custom_virtualenv": null,
      "description": "",
      "group_by": "",
      "instance_filters": "",
      "inventory": {
        "name": "inventory-custom",
        "organization": {
          "name": "Ansible, Inc",
          "type": "organization"
        },
        "type": "inventory"
      },
      "name": "inventory-custom",
      "natural_key": {
        "inventory": {
          "name": "inventory-custom",
          "organization": {
            "name": "Ansible, Inc",
            "type": "organization"
          },
          "type": "inventory"
        },
        "name": "inventory-custom",
        "type": "inventory_source"
      },
      "overwrite": true,
      "overwrite_vars": false,
      "related": {
        "notification_templates_error": [],
        "notification_templates_started": [],
        "notification_templates_success": [],
        "schedules": []
      },
      "source": "custom",
      "source_path": "",
      "source_project": null,
      "source_regions": "",
      "source_vars": "{\"NUM_HOSTS\": \"5\"}",
      "timeout": 0,
      "update_cache_timeout": 0,
      "update_on_launch": true,
      "update_on_project_update": false,
      "verbosity": 1
    },
```

According to https://github.com/ansible/awx/blob/a0413b7e0bbba6af3c6927bdf5942f2e0c78c3e2/awxkit/awxkit/api/pages/api.py#L14-L26 custom inventory scripts are not part of the exportable resources and with that the import/export should either skip and warn about it or fully support importing/exporting inventory sources with custom inventory scripts

##### ENVIRONMENT
* AWX version: devel
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

1) Create an inventory script
2) Create an inventory and set its inventory source to use the custom inventory script created on step 1
3) Export both the inventory and inventory source
4) Import the exported data on a fresh instance and check the imported entities

##### EXPECTED RESULTS

Import/export should not partially export/import inventory sources with custom inventory scripts.

##### ACTUAL RESULTS

Import/export is partially exporting and importing inventory sources with custom inventory scripts

**Comment by chrismeyersfsu** [comment]
Now that inventory plugins are a thing, custom inventory scripts may be going away soon. That would make this much less of a priority.

**Comment by elyezer** [comment]
@chrismeyersfsu does it make sense to skip exporting incomplete data then? Like currently the inventory source is exported but not the script so when importing it will be a broken one.

**Comment by AndrewSav** [comment]
Is there any documentation how to plug in a custom inventory plug in in tower/awx? Or how to _write_ a custom inventory plug  for that matter?

**Comment by wenottingham** [comment]
Closing export of inventory script data as "wontfix"
