### ISSUE TITLE
'Next' button is missing from credential plugin prompt

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#7530]
##### ISSUE TYPE
Seems to be devel only. Did not reproduce on recent release. I do not know the cause nor am I closer to it after an hour digging into this. I think I may need to bisect the devel commits to find it.

![Screenshot from 2020-07-01 19-30-41](https://user-images.githubusercontent.com/9753817/86300997-b0165000-bbd2-11ea-976d-fc3ae464ee85.png)

**Comment by jakemcdermott** [comment]
relevant:

![fuck](https://user-images.githubusercontent.com/9753817/86302488-d9d17600-bbd6-11ea-916c-f62551f790a8.gif)
![fuuck](https://user-images.githubusercontent.com/9753817/86302490-dc33d000-bbd6-11ea-8869-2a289080de59.gif)

**Comment by unlikelyzero** [comment]
Covered by 5517
