### ISSUE TITLE
awx installation error on RHEL 7.7

### ISSUE THREAD

**Issue by amitchauhan1502** [ansible/awx#7532]
I am getting below error while installing awx (from latest source clone):

 ansible-playbook -i inventory install.yml

TASK [local_docker : Create Docker Compose Configuration] ****************************************************************************
failed: [localhost] (item=environment.sh) => {"changed": false, "item": "environment.sh", "msg": "AnsibleError: Unexpected templating type error occurred on (DATABASE_USER={{ pg_username|quote }}\nDATABASE_NAME={{ pg_database|quote }}\nDATABASE_HOST={{ pg_hostname|default('postgres')|quote }}\nDATABASE_PORT={{ pg_port|default('5432')|quote }}\nDATABASE_PASSWORD={{ pg_password|default('awxpass')|quote }}\n{% if pg_admin_password is defined %}\nDATABASE_ADMIN_PASSWORD={{ pg_admin_password|quote }}\n{% endif %}\nAWX_ADMIN_USER={{ admin_user|quote }}\nAWX_ADMIN_PASSWORD={{ admin_password|quote }}\n): 'int' object is not iterable"}
changed: [localhost] => (item=credentials.py)

ansible: 2.4.2.0
RHEL: 7.7
python: 2.7 and 3.6 (getting same error when run with both versions)

**Comment by ryanpetrello** [comment]
> ansible: 2.4.2.0

https://github.com/ansible/awx/blob/devel/INSTALL.md#prerequisites
