### ISSUE TITLE
"ModuleNotFoundError: No module named 'ansible'" in a new VENV

### ISSUE THREAD

**Issue by duhlig** [ansible/awx#7533]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME
 - API

##### SUMMARY
I tried to follow https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md as close as possible. First tests (possibly incomplete) with the new venv seemed successful. Now the inventory sync failes. I'm sure it's my fault, but I don't see it.

Please advise what I could check.

Kind regards,
Dietmar

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.5
* Operating System: Oracle Linux 7.8
* Web Browser:

##### STEPS TO REPRODUCE

Follow https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md (see below). Log in to your Docker host.

```
su - awx
cd .awx/awxcompose
vi docker-compose.yml
--> in "web:" and "task:"
    volumes:
       …
      - "~/venv:/opt/custom_venvs/:rw"
docker-compose up

docker exec -it CONTAINER_ID /bin/bash

virtualenv /opt/custom_venvs/rdsintra
/opt/custom_venvs/rdsintra/bin/pip install /opt/custom_venvs/pykeepass-3.2.0.tar.gz
(I also manually installed dependencies to pykeepass. This machine has no direct internet access.)
```

I installed psutil into the Docker volume from within the Docker host as the container image doesn't include gcc. It's just luck that both Linuxes are close enough...

Last I assigned the venv to my organization, to the project, and the template, as stated in https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md#assigning-custom-virtualenvs.

##### EXPECTED RESULTS

Inventory should get synced.

##### ACTUAL RESULTS

Problem: Inventory sync failes:
```
    4.546 INFO     Updating inventory 9: DB Phase 1 - SE
    5.522 INFO     Reading Ansible inventory source: /tmp/awx_1746_v4upcq0x/project/roles/rdsintra/inv_phase1.yml
    5.526 INFO     Using VIRTUAL_ENV: /opt/custom_venvs/rdsintra/
    5.526 INFO     Using PATH: /opt/custom_venvs/rdsintra/bin:/var/lib/awx/venv/awx/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    5.527 INFO     Using PYTHONPATH: /opt/custom_venvs/rdsintra/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1151, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1041, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 215, in load
    return self.command_to_json(base_args + ['--list'])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 198, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
Traceback (most recent call last):
  File "/usr/bin/ansible-inventory", line 34, in <module>
    from ansible import context
ModuleNotFoundError: No module named 'ansible'
```

##### ADDITIONAL INFORMATION

None.

**Comment by ryanpetrello** [comment]
@duhlig have you tried installing Ansible directly into the custom virtualenv e.g.,

```shell
~ /opt/custom_venvs/rdsintra/bin/pip3 install "ansible==2.9.5"
```

**Comment by duhlig** [comment]
> have you tried installing Ansible directly into the custom virtualenv

No, I didn't. Maybe I don't understand the principle of Python VENV. I thought there must be a standard Ansible installation inside the Docker image, and the VENV would contain only the difference to this.

In my case the template and the inventory are based both on the same SCM project. My current workaround is to unset the custom_venv of this project when synchronizing the inventory and to set it when executing the playbook. Don't know why but this works.

@ryanpetrello Should I install Ansible in every custom VENV? The above mentioned configuration instructions are not clear about this.

Kind regards,
Dietmar

**Comment by ryanpetrello** [comment]
@duhlig,

It depends on how you created the virtualenv itself.  The default virtualenv that comes with AWX uses the `--system-site-packages` flag, which means it inherits packages from the system Python `site-packages` (including the system-installed Ansible).  If you didn't set up your custom virtualenv this way, though (the docs don't suggest it - they suggest you install a specific Ansible yourself) - you'll have to install Ansible in the custom virtualenv.

If `pip install ansible` in the custom virtualenv works, great.  If you'd rather just inherit from the base system Ansible, look at your custom virtualenv, and if you notice a file in there called `no-global-site-packages.txt`, then delete it.

**Comment by duhlig** [comment]
I see. I will check this tomorrow.
Thanks a lot.

**Comment by duhlig** [comment]
It works. Great! Thanks! Learned something again.

**Comment by anshubairwa** [comment]
Hi folks,
try to this command  ansible-inventory --list -y
but showing this error :- 

Traceback (most recent call last):
  File "/usr/bin/ansible-inventory", line 34, in <module>
    from ansible import context
ModuleNotFoundError: No module named 'ansible'


Please help to solve about it.
