### ISSUE TITLE
Edit Schedule view is broken in AWX 13.0.0

### ISSUE THREAD

**Issue by kenchrcum** [ansible/awx#7534]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Schedules cannot be edited in AWX 13.0.0. It seems to be some kind of templating error.

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker
* Ansible version:  2.9.10
* Operating System: centos
* Web Browser: chrome

##### STEPS TO REPRODUCE

Install fresh AWX deployment and click on Schedules -> Cleanup Activity Schedule

##### EXPECTED RESULTS

Possibility to edit Scheduled Job

##### ACTUAL RESULTS

![awx-schedule-bug](https://user-images.githubusercontent.com/21356628/86352136-9d992680-bc65-11ea-8795-071af4b314ff.png)

**Comment by Luke239847** [comment]
Got the same errors.
Seems to occur only when the _Repeat Frequency_ is set to "Week"

**Comment by jakemcdermott** [comment]
Hey @kenchrcum  - we've just merged a patch for this. It'll be fixed in the next release of awx.

**Comment by Aech1977** [comment]
is there a workaround until this pull request is approved and merged (or did it happen already and I'm just dense)?

**Comment by ryanpetrello** [comment]
@Aech1977 the fix has merge into AWX, but we haven't made an official release of AWX since then (we're likely going to release a new version in the coming weeks).

**Comment by Aech1977** [comment]
I'll sit tight then.  Thanks.  Another dumb question I know I came across it before but where can I see release versions?
Thanks for the speedy response.

**Comment by ryanpetrello** [comment]
Hey @Aech1977,

New releases show up here: https://github.com/ansible/awx/releases
We publish official images to Dockerhub: https://hub.docker.com/r/ansible/awx

Additionally, we have an official changelog at: https://github.com/ansible/awx/blob/devel/CHANGELOG.md

...and we announce releases on our mailing list: https://groups.google.com/forum/#!forum/awx-project

**Comment by Aech1977** [comment]
thanks

**Comment by kenchrcum** [comment]
Fix in version 14.0.0 verified. Thank you everybody :)
