### ISSUE TITLE
Project Hooks

### ISSUE THREAD

**Issue by hypery2k** [ansible/awx#7535]
##### ISSUE TYPE
- In some scenarios it is helpful to have hook within a template/job (e.g. run a git-secret decrypt script after creation job folder)

##### SUMMARY
- Would be great a at least have a pre- and post hook running certain commands before or after template/job execution

**Comment by wenottingham** [comment]
This is really unlikely. The way AWX is designed is for (mostly) stateless job execution,and is moving even further in that regards with containerized execution disconnected from the host AWX environment. If additional steps need done, they should be tasks/roles in the playbook.
