### ISSUE TITLE
AWX Backup and Restore scripts do not work on current AWX versions

### ISSUE THREAD

**Issue by kbrighton** [ansible/awx#7538]
##### ISSUE TYPE
 - AWX Backup and Restore scripts do not work on current AWX versions

##### SUMMARY
AWX 12 and higher still expect that SCL is used to install the postgres utilities, though when they're using a CentOS 8 based image, they can natively install the proper version, using dnf modules, rather than utilizing the SCL version of the package.

##### ENVIRONMENT
* AWX version: 12.0.0
* AWX install method: EKS
* Ansible version:  2.9.6
* Operating System: Linux
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Run the native backup and restore scripts on a kubernetes instance of AWX.

##### EXPECTED RESULTS

An AWX backup to be taken

##### ACTUAL RESULTS

An error message saying that SCL isn't installed, and after installation of scl-utils, the message that rh-postgres10 isn't installed.

##### ADDITIONAL INFORMATION

The error appears to be in this part of the playbook, and changing it to this will fix it.  If this appears to be the proper solution, then I'll make a pull request with this fix.

- name: Dump database
  shell: |
    {{ kubectl_or_oc }} -n {{ kubernetes_namespace }} exec ansible-tower-management -- \
      bash -c "PGPASSWORD={{ pg_password | quote }} \
        pg_dump --clean --create \
          --host='{{ pg_hostname | default('postgresql') }}' \
          --port={{ pg_port | default('5432') }} \
          --username='{{ pg_username }}' \
          --dbname='{{ pg_database }}'" > {{ playbook_dir }}/tower-openshift-backup-{{ now }}/tower.db
  no_log: true

**Comment by shanemcd** [comment]
I dont think this is relevant anymore now that the operator exists. If you are still having issues with backup and restore, please open an issue on the awx-operator repo.
