### ISSUE TITLE
HashiCorp Vault Secret Lookup: Test button don't work

### ISSUE THREAD

**Issue by stasonspb** [ansible/awx#7546]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Can't get test form for Lookup type credential

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method:  docker on linux
* Ansible version:  2.9.10
* Operating System: linux
* Web Browser: Firefox, Chrome

##### STEPS TO REPRODUCE

Add a new credential
type: “HashiCorp Vault Secret Lookup”
set: Name, Server URL, Token
Click the "test" button

##### EXPECTED RESULTS

get the form "Test External Credential"
![image](https://user-images.githubusercontent.com/16939849/86481748-45dbe780-bd59-11ea-9d39-bba164335a21.png)

##### ACTUAL RESULTS

get nothing

##### ADDITIONAL INFORMATION

Same problem for another Lookup credential type(CyberArk Conjur Secret Lookup and CyberArk AIM Central Credential Provider Lookup)
Button works on version 12.0.0

**Comment by ryanpetrello** [comment]
Hey @stasonspb,

Thanks for reporting this - this looks related to a recent dependency upgrade we made (to jQuery cc @jakemcdermott).

This should be resolved in the next release of AWX: https://github.com/ansible/awx/pull/7553

**Comment by venu-devannagari** [comment]
Hi did it resolved..

**Comment by stasonspb** [comment]
For me issue is resolved in the latest version(14.0.0)

**Comment by wenottingham** [comment]
Closing as fixed.
