### ISSUE TITLE
Sort on lists does not have a consistent, deterministic 'finished' or 'ready' state

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#7548]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Sort on lists does not have a consistent, deterministic 'finished' or 'ready' state. This makes test automation non-deterministic. The reason I bring this up now, is that the behavior is being seen on a small dataset with few resources. Whatever solution we come up with should be to handle large datasets.

Our sort list test performs the following:
1. Create Resource 'A' and 'B'
2. Navigate to Resource List by url
3. Verify that Resource 'A' and 'B' are listed
4. Click 'Sort' by 'Name' 'A->Z' button.
5. Verify that the url is `schedules?schedule.order_by=name`
    Verify the resource order by the aria-label attribute.
6. Click 'Sort' by 'Name' 'Z->A' button.
7. Verify that the url is `schedules?schedule.order_by=-name`
    Verify the resource order by the aria-label attribute.

Problems:
The time between step 6 and 7 can be greater than 5seconds. We know this because we cheated and inserted a 5s wait.
The previous order of elements on screen is incorrect until it is refreshed.
The time between the XHR request being received that the resource order changing to match the sort order varies.
The time between the sort order changing and the url updating varies.
The time between 'Sort' button click and the 'Sort' button element updating to 'Z->A' does not reflect the state of the listed resources.

Solutions:
1. Do not show list of resources until order is resource order is correct. i.e. Click on the sort button should hide resources until they're refreshed and displayed in the specified order.
2. Provide some indication that the sort order is correct.
3. Potentially implement OUIA pagesafe attribute

##### ADDITIONAL INFORMATION

https://dashboard.cypress.io/projects/ui2mq7/runs/1456/failures/bfd7df5e-48b7-457d-acd2-1f919c22ffb4/video
https://dashboard.cypress.io/projects/ui2mq7/runs/1498/failures/3895008f-bb6e-4022-bfbf-60d3d8d1faee/video

**Comment by mabashian** [comment]
Skeleton loading

**Comment by keithjgrant** [comment]
Ideally, I'd like to find a solution that doesn't hide the list while loading a new list, because this can cause the page to jump around and/or generally draw more of the user's attention to the slow load time. I'm inclined to look for a way we could show a loading indicator somewhere while an updated list is loading.

**Comment by keithjgrant** [comment]
I think skeletons might be the right call here... we need to upgrade PF to the latest version for that, but I have proven it out:

![list-skeleton](https://user-images.githubusercontent.com/410794/98286906-8347c000-1f59-11eb-966a-74c468cfe196.gif)

**Comment by unlikelyzero** [comment]
@AlexSCorey @keithjgrant this ticket will be solved by skeleton loading here https://github.com/ansible/awx/issues/4212

**Comment by keithjgrant** [comment]
Look at #9010 while working on this… it might make sense to address them together

**Comment by unlikelyzero** [comment]
@akus062381 can you see if we had a test for this scenario that was set to skipped?

**Comment by akus062381** [comment]
This is taken care of and tests have been written and merged into the code
