### ISSUE TITLE
AWX 13.0: libvirt module is unusable

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx#7550]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I cannot use the virt ansible module in AWX 13.0 anymore, seems that the awx_task image is missing some dependencies.

##### ENVIRONMENT
* AWX version: 13.0
* AWX install method: docker on linux
* Ansible version:  2.9.10
* Operating System: Docker container running on openSUSE Leap 15.2
* Web Browser: Firefox

##### STEPS TO REPRODUCE

open a shell in the awx_task container, then try to use the virt module like so:
`lemmy@akari:~/Work/Ansible/updates> docker exec -ti  awx_task /bin/bash --login

[root@awx /]# ansible -m virt -a command=list_vms localhost
localhost | FAILED! => {
    "changed": false,
    "msg": "The `libvirt` module is not importable. Check the requirements."
}
`
##### EXPECTED RESULTS

I would expect that to fail because there is no running libvirt inside the awx_task container, but not with what looks like there's a python module missing.

##### ACTUAL RESULTS

localhost | FAILED! => {
    "changed": false,
    "msg": "The `libvirt` module is not importable. Check the requirements."
}

##### ADDITIONAL INFORMATION

AWX runs with self-built images because I need https.
I have a playbook that updates all VMs on any given host, and that playbook still works fine when I run it manually from my workstation, but it does not work anymore from inside AWX - but it used to work just fine before I upgraded to 13.0 (was running 11.2 before).

**Comment by wenottingham** [comment]
See https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md - this is what custom virtual environments are for - adding the dependencies you need for certain modules.

**Comment by lemmy04** [comment]
you're kidding, right? users are supposed to mess around with the virtualenvs inside the running containers to get things to work that used to work just fine in a previous version, and are standard ansible modules?

**Comment by wenottingham** [comment]
We have never included the libvirt python bindings in the ansible environment used in AWX. I'm not sure how it worked for you beforehand.

```
[notting@nostromo: ~/prog/awx/requirements]$ docker pull ansible/awx_task:11.2.0
11.2.0: Pulling from ansible/awx_task
8a29a15cefae: Already exists 
<docker noise snipped>
...
[notting@nostromo: ~/prog/awx/requirements]$ docker run -it ansible/awx_task:11.2.0 bash
bash-4.4$ ls /usr/lib*/python3.6/site-packages/*virt*
ls: cannot access '/usr/lib*/python3.6/site-packages/*virt*': No such file or directory
bash-4.4$ . /var/lib/awx/venv/ansible/bin/activate
(ansible) bash-4.4$ pip freeze | grep virt
ovirt-engine-sdk-python==4.3.0
virtualenv==16.7.10
```

**Comment by lemmy04** [comment]
all I know is that it worked, and that the "virt" module is a standard ansible module, so I'd assume it should "just work" in awx as well as manually. my guess is that it came pulled in via rpm dependencies until recently when the images are being build, but now it's not anymore. Would have to roll my checkout back to the last version that worked, and compare.

**Comment by lemmy04** [comment]
I just tried the same thing that you're doing there, and you are right, there is no libvirt python module around, and any "ansible -m virt" from inside the container fails on 11.2 just the same way as it does now in 13.0... I am mystified.

all i can say for sure is this:
my playbook's at https://eregion.kicks-ass.net/git/?p=updates.git;a=blob_plain;f=update-vms-v1.yml;hb=HEAD and it used to work in AWX 11.2, and it still works on the shell, but it breaks with "The `libvirt` module is not importable. Check the requirements." in AWX 13.0.

I still consider that a bug. Managing VMs is a thing that AWX should be able to do with libvirt the same was as it does with "bigger" tools.

**Comment by lemmy04** [comment]
So just to make sure I installed AWX 11.2.0 on another host, and my play to manage libvirt VMs **works** there, but not in my AWX 13.0.0 instance.

**Comment by lemmy04** [comment]
ok now I am really confused.

I installed AWX 13.0.0 on my test host, and before that I switched from python 2 to python 3 using update-alternatives... and guess what, my play works there. So I re-deployed 13.0.0 on my production AWX, also switching to python3 before that, and there my play works again, too.

I do not understand that.

**Comment by wenottingham** [comment]
You mentioned that this was self-built? If you're inheriting a libvirt-python from the system/image you're starting from, which python interpreter you use will make a difference.

**Comment by lemmy04** [comment]
I always thought docker images are built based on the base image and nothing else? You know, the "FROM" line in your docker file?

Anyway, if this is the case it should be in the docs somewhere.

**Comment by wenottingham** [comment]
> I always thought docker images are built based on the base image and nothing else? You know, the "FROM" line in your docker file?

Yes, just that when someone says "self-built", I don't want to assume they haven't modified the docker or build configuration.

**Comment by lemmy04** [comment]
That's a good way of thinking there. But all I have modified is the inventory file... so I really don't get it.

**Comment by lemmy04** [comment]
Updating to 14.0.0, same thing happened... I wish i could get rid of python2 alltogether

**Comment by ryanpetrello** [comment]
@lemmy04 is this a duplicate of https://github.com/ansible/awx/issues/7998, or something else?
