### ISSUE TITLE
Form Labels

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#7556]
##### ISSUE TYPE
Bug
##### SUMMARY
Since the PF4 upgrade the look up labels have been misaligned with their tooltip icon.  This needs to be fixed.  While fixing this we should also utilize PF's popover component that introduces clickable tooltip.  When bringing this in be aware that this change doesn't impact the prompt on launch fields.  Ie. when prompt on launch is clicked, the tooltip should not expand and vice versa

Also, a promptable label does not align with other labels. It doesn't have as much space between the label and the field.  
##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: docker for mac
* Ansible version:  2.9.10
* Operating System: Mojave
* Web Browser:Chrome

##### STEPS TO REPRODUCE

1)Go to any form that has a look up with a tooltip.  2)Go to any form that has a promptable field.  The screen shot is on Job Template form.
##### EXPECTED RESULTS

1) the tooltip icon is aligned with the label name
2)The label is aligned with other, non-promptable labels.
##### ACTUAL RESULTS

Neither is aligned.
##### ADDITIONAL INFORMATION
![Screen Shot 2020-07-06 at 11 19 21 AM](https://user-images.githubusercontent.com/39280967/86615401-66d35100-bf82-11ea-9d89-4d05f391eba7.png)

**Comment by unlikelyzero** [comment]
@AlexSCorey would you mind running the PF percy tests once this is ready?

**Comment by unlikelyzero** [comment]
Covered in pull/5626
