### ISSUE TITLE
List Instance Groups

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#7557]
ISSUE TYPE

    Feature Idea

SUMMARY

Add support for list Instance Groups

**Comment by unlikelyzero** [comment]
@nixocio please reach out to @dsesami or myself when you're nearing completion

**Comment by mabashian** [comment]
@nixocio I see that #7633 has merged, does that mean that this issue should be closed?

**Comment by unlikelyzero** [comment]
@mabashian we're leaving this open to link back to the test stubs or net new functional tests

**Comment by nixocio** [comment]
@unlikelyzero, I just closed 2 issues related to instance groups yesterday. I will re-open them.

**Comment by dsesami** [comment]
This is looking really good, stubs are open and can track this, so this can be closed.
