### ISSUE TITLE
Job Template admin gets erroneous errors without project permission

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#756]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
User with job template admin but not project admin has bad UX.

##### ENVIRONMENT
* AWX version: 1.0.1
* AWX install method: docker for mac
* Ansible version:  N/A
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

 - Create a new user
 - Give user admin role to a job template
 - as that user, navigate to the job template page in the UI

##### EXPECTED RESULTS

Everything okay

##### ACTUAL RESULTS

![screen shot 2017-12-01 at 9 24 33 am](https://user-images.githubusercontent.com/1385596/33487170-5edbb8a0-d67a-11e7-85ff-54b64cdf1102.png)

**Comment by wenottingham** [comment]
see #1149
