### ISSUE TITLE
Add email as a default search option to Users list

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7561]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
I know that we don't display the email address in the list itself but I could see a situation where someone may want to search based on it on this list.

**Comment by mabashian** [comment]
This is available via the advanced option now.  Im going to leave this open though in case we still want to do it.

**Comment by nixocio** [comment]
Acceptance criteria
Email should be the default key for User List.

**Comment by tiagodread** [comment]
A few e2e tests around this context may require an update

**Comment by InnocentK** [comment]
Resolved: acceptance criteria met
