### ISSUE TITLE
Can't attribute superuser to ldap user UI

### ISSUE THREAD

**Issue by chris93111** [ansible/awx#7566]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

In ui it's not possible to assign role superuser to ldap user (default admin account used)

it's work with patch user api 

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker
* Ansible version:  2.9
* Operating System: redhat
* Web Browser: chrome

##### STEPS TO REPRODUCE

try to assign superuser to ldap account

##### EXPECTED RESULTS

superuser attribute with ui

##### ACTUAL RESULTS

validate gray icon

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/27526373/86814280-7a191600-c081-11ea-91f0-d8459f775961.png)

**Comment by wenottingham** [comment]
Did this just stop working  in 13.0?

**Comment by chris93111** [comment]
@wenottingham i thinks yes i not see this error in 12 but it's not impossible

**Comment by wenottingham** [comment]
@jakemcdermott is this something that https://github.com/ansible/awx/pull/7553 would fix?

**Comment by blomquisg** [comment]
@chris93111 can you try this in AWX 14.0?

**Comment by chris93111** [comment]
Ok i try thanks

**Comment by chris93111** [comment]
@blomquisg it's work thanks

**Comment by wenottingham** [comment]
Thanks for checking.
