### ISSUE TITLE
System admin created labels can be created with an unexpected organzation

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#7567]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
1. Have two organizations (id 2 and id 3)
2. Have a job template XYZ, in organization 2
3. Log in as superuser, who is not a member of any organization
4. Add some new labels to job template XYZ

##### ENVIRONMENT
* AWX version: current

##### STEPS TO REPRODUCE

see above

##### EXPECTED RESULTS

Labels created in organization 2, as that's the org of the JT

##### ACTUAL RESULTS

Labels created in organization 3

**Comment by mabashian** [comment]
@wenottingham I was testing this out and I came across a scenario which I think is not working correctly but i'm not sure.  I think the bug as you outlined it is fixed(?) but if the superuser changes the project to a project in a different org _and_ adds a new label the label gets associated with the org from the previous project.  That's not the ideal behavior right?  If the project changes to a different org then any net-new labels should go to the new org right?

**Comment by wenottingham** [comment]
My answer is "hm".

I think changing the org of something from A->B shouldn't change existing labels on it, but in theory it should change the new labels going forwards. But I'm guessing the UI code won't use the new org until *after* it's saved?
