### ISSUE TITLE
RFE: Selection of preferred or default instance group

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#7569]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Allow users to select a default instance group for jobs to run. While we do allow instance groups to be selected at the Org/Inv/JT level, this still lets jobs overflow into other instance groups. A large use case for customers is to use instance groups to limit what nodes jobs run on. 

A potential fix could be a checkbox (or another mechanism) that dictates that if an IG is set at the JT or Inv, queue jobs only against that instance group.

**Comment by wilpig** [comment]
This one seems like a clear case where the priority should be Least -> Most, Organization -> Inventory -> Playbook.

When jobs process if the playbook has a group set it would run there, if that is blank then it could check the inventory level, if that too is blank then it would check at the organization, then finally just run on any system.  We have firewall rules that limit some of our tower servers to only talk to specific servers in the enterprise so being able to lock down a job to a specific set of servers is important.

Ideally we'd be able to lock down organizations to specific instance groups so they couldn't pick any of them but that's another request.

**Comment by wenottingham** [comment]
-> https://github.com/ansible/awx/issues/6134
