### ISSUE TITLE
Issues with editing schedule in AWX

### ISSUE THREAD

**Issue by Aech1977** [ansible/awx#7573]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
All of a sudden when I try to edit a schedule I created it gives a bunch of string messages in place of where the guid buttons and names are

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.2
* Operating System: CentOS 7.5
* Web Browser: Chrome (but also happens in Safari

##### STEPS TO REPRODUCE

Login to AWX interface, go to schedule select a schedule created and it brings you to a page where you can edit a schedule

##### EXPECTED RESULTS

Expect it to show me the actual schedule page so I can make changes

##### ACTUAL RESULTS

 shows it's working in the corner and shows the fields all with string.get names underneath and nothing works.  Happens to all the schedules below my 9th one.

##### ADDITIONAL INFORMATION

<img width="1485" alt="Screen Shot 2020-07-07 at 3 29 16 PM" src="https://user-images.githubusercontent.com/50711744/86833873-1b936e00-c068-11ea-8f50-16c8093464f2.png">

**Comment by Aech1977** [comment]
I have restarted the postgres DB and restarted all associated docker containers including the host AWX is deployed on itself.

**Comment by jakemcdermott** [comment]
Hey @Aech1977 - we've just merged a patch for this. It'll be fixed in the next release of awx.

related: https://github.com/ansible/awx/issues/7534

**Comment by Aech1977** [comment]
thanks
