### ISSUE TITLE
RabbitMQ Should Only Listen to Nodes Designated in Inventory

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/awx#758]
##### ISSUE TYPE

 - Bug

##### COMPONENT NAME

 - Installer

##### SUMMARY
Configure RabbitMQ on install to listen only to nodes defined in the [tower] group as discussed in the [https://www.rabbitmq.com/networking.html](RabbitMQ networking) documentation.

##### ENVIRONMENT
* AWX version: 1+

##### ADDITIONAL INFORMATION

An example of the configs for a single node install:

```
# cat /etc/rabbitmq/rabbitmq.conf
[
 {rabbit,
  [{loopback_users, []},
   {tcp_listeners, [{"127.0.0.1",5672]},
   {cluster_partition_handling, pause_minority}]}
].
```
```
# cat /etc/rabbitmq/rabbitmq-env.conf
NODENAME=rabbitmq@localhost
USE_LONGNAME=false
NODE_IP_ADDRESS=127.0.0.1
```

**Comment by ryanpetrello** [comment]
Closing this issue, as we're removing AWX's usage of RabbitMQ entirely (see: https://github.com/ansible/awx/issues/5443)
