### ISSUE TITLE
UI Bug on editing existing Schedule for a Job

### ISSUE THREAD

**Issue by rahadianir** [ansible/awx#7587]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI
 

##### SUMMARY
an interface bug when trying to edit existing scheduler for a job

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.10
* Operating System: Mac Os
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Open a job/template, then edit the schedule for it

##### EXPECTED RESULTS

Usual stuff without any variables like "string" etc shows up

##### ACTUAL RESULTS

Variables and other things shows up

##### ADDITIONAL INFORMATION

<img width="1245" alt="Screenshot 2020-07-09 at 13 12 53" src="https://user-images.githubusercontent.com/32757757/87004667-00e80300-c1e8-11ea-9979-321e49a4f987.png">

**Comment by jakemcdermott** [comment]
Hey @risyard 

Thanks for the bug report. We merged a patch for this recently. It'll be fixed in the next release of awx.

related: https://github.com/ansible/awx/issues/7534
