### ISSUE TITLE
  vCenter sourced inventory: manually adding host_vars causes instance_id of host to be removed and host re-added to inventory 

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#7591]
Comments
@ mdinwoodie
mdinwoodie commented on May 26
ISSUE TYPE

    Bug Report

SUMMARY

For a vCenter sourced inventory, making a manual change to the host_vars for any imported host causes the instance_id to be removed. This seems to cause the host to be re-added to the inventory during a sync, removing any manually added host_vars.
ENVIRONMENT

    Taters version 3.6.4

STEPS TO REPRODUCE

    Create a vCenter sourced inventory, with the "overwrite" option checked and "overwrite variables" unchecked
    Run a vCenter inventory sync
    Once complete, manually add a host_var to any host through the UI
    Run another vCenter inventory sync

EXPECTED RESULTS

Inventory syncs successfully and does not remove any manually added host_vars.
ACTUAL RESULTS

The modified host is deleted and re-added to inventory, removing any manually added host_vars.
ADDITIONAL INFORMATION

When checking the ./api/v2/hosts/N/ endpoint for the modified host, we see the instance_id has been removed. A workaround we found is to PATCH the instance_id of any modified hosts prior to running another inventory sync. Doing this, the host is not deleted/re-added to the inventory and the manually added host_vars are not removed.

**Comment by unlikelyzero** [comment]
Coverage added in 5515
