### ISSUE TITLE
Rename users and access tabs

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#7595]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Task: Update subtab names

<img width="366" alt="Screen Shot 2020-07-09 at 3 22 26 PM" src="https://user-images.githubusercontent.com/15881645/87082005-4d3b3f00-c1f8-11ea-856a-a138f5da3081.png">

<img width="506" alt="Screen Shot 2020-07-09 at 3 25 40 PM" src="https://user-images.githubusercontent.com/15881645/87082160-8ecbea00-c1f8-11ea-9ab9-80d14a9c4065.png">

[These tables](https://docs.google.com/spreadsheets/d/1DSgZC1JJYI6oCp47QRjWhDAc3CznB6tDZI3GuhxLdqc/edit?usp=sharing) show the sub-tabs titles and content for each top-level view (User, Team, Organization) in the old and new UI. Under **User** and **Team**, I’ve crossed out the current list tab title and replaced it with the new proposed name. These new names should make the tab titles and their list content more consistent across these objects.

Currently, the “Access” tab in Users and Teams shows assigned resource roles, but in Organization, the same tab shows a list of users that have access to the organization via some role. Basically, the idea is to rename the tabs to match the API endpoint we are receiving information from.

##### ADDITIONAL INFORMATION
https://docs.google.com/spreadsheets/d/1DSgZC1JJYI6oCp47QRjWhDAc3CznB6tDZI3GuhxLdqc/edit?usp=sharing

cc @tvo318 @trahman73

**Comment by unlikelyzero** [comment]
Please run through the e2e suite. This will likely break some tests that depend on the tabs

**Comment by mabashian** [comment]
@unlikelyzero looks like this got merged without test.  Applying needs_test now.

**Comment by unlikelyzero** [comment]
Adding @akus062381 to this to cover as a part of the access list testing on JT forms

**Comment by akus062381** [comment]
Read what's listed and figure out if the current implementation is correct.

**Comment by akus062381** [comment]
There is a Google doc where I have compiled everything, and specifies some issues discovered here. 
This is in progress- will meet with Dev to determine which are bugs and which aren't, and file bug reports accordingly.

**Comment by akus062381** [comment]
this has been handled by breaking smaller issues out into their own issue files.
