### ISSUE TITLE
redis is not starting with AWX releases: 11.1/11.2/12/13 @RHEL 7.8

### ISSUE THREAD

**Issue by ghost** [ansible/awx#7597]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
REDIS is not working.

##### ENVIRONMENT
* AWX version: 11.1 / 11.2 / 12 / 13
* AWX install method: docker on linux
* Ansible version:  ansible 2.8.3
* Operating System: RHEL 7.8
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Tested on all 4(!) releases *and* with the actual HEAD version in github.
All show the same error: Redis is not starting (the unix socket is missing. see below).

Maybe it's a problem with RHEL 7.8 ?

##### EXPECTED RESULTS

redis should start without errors on RHEL 7.8

##### ACTUAL RESULTS

Installed AWX. Redis socket is not present:

redis.exceptions.ConnectionError: Error 2 connecting to unix socket: /var/run/redis/redis.sock. No such file or directory.

##### ADDITIONAL INFORMATION

Complete Error mesage  

2020-07-09 19:50:23,596 ERROR    awx.main.commands.run_callback_receiver encountered an error communicating with redis. Reconnect attempt in 30 seconds
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/connection.py", line 552, in connect
    sock = self._connect()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/connection.py", line 905, in _connect
    sock.connect(self.path)
FileNotFoundError: [Errno 2] No such file or directory
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/dispatch/worker/base.py", line 126, in run
    res = queue.blpop(self.queues)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/client.py", line 1865, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/client.py", line 875, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/connection.py", line 1185, in get_connection
    connection.connect()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/connection.py", line 557, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 2 connecting to unix socket: /var/run/redis/redis.sock. No such file or directory.
2020-07-09 19:50:23,596 ERROR    awx.main.commands.run_callback_receiver encountered an error communicating with redis. Reconnect attempt in 30 seconds
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/connection.py", line 552, in connect
    sock = self._connect()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/connection.py", line 905, in _connect
    sock.connect(self.path)
FileNotFoundError: [Errno 2] No such file or directory
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/dispatch/worker/base.py", line 126, in run
    res = queue.blpop(self.queues)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/client.py", line 1865, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/client.py", line 875, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/connection.py", line 1185, in get_connection
    connection.connect()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/connection.py", line 557, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 2 connecting to unix socket: /var/run/redis/redis.sock. No such file or directory.

Config  

cat << EOF >$awxdir/installer/inventory
localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python"

[all:vars]
dockerhub_base=ansible

awx_task_hostname=awx
awx_web_hostname=awxweb
host_port=80
host_port_ssl=443

docker_compose_dir=/opt/awxcompose
postgres_data_dir=/opt/pgdocker

pg_hostname=172.16.17.124
pg_database=awx
pg_port=5432
pg_username=awx
pg_password=$DBPASS

admin_user=admin
admin_password=$ADMINPASS

create_preload_data=false
secret_key=$SECRET
awx_official=true

http_proxy=http://$http_proxy
https_proxy=http://$http_proxy
EOF

Installed packages  
  
yum install -y ansible git docker make automake python2-pip nodejs || exit 1
yum install -y gcc gcc-c++ gettext device-mapper-persistent-data lvm2 bzip2 python3-pip || exit 1

Firewall disabled  

systemctl stop firewalld
systemctl disable firewalld

Proxy is set  

http_proxy=10.140.209.54:3128
https_proxy=$http_proxy
HTTP_PROXY=$http_proxy
HTTPS_PROXY=$http_proxy
export http_proxy https_proxy HTTP_PROXY HTTPS_PROXY

also for docker  

mkdir /etc/systemd/system/docker.service.d
cat << EOF >/etc/systemd/system/docker.service.d/http-proxy.conf
[Service]
Environment="HTTP_PROXY=$http_proxy"
Environment="HTTPS_PROXY=$http_proxy"
Environment="NO_PROXY=localhost,127.0.0.1"
EOF

mkdir /root/.docker
cat << EOF >/root/.docker/config.json
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://$http_proxy",
     "httpsProxy": "http://$http_proxy",
     "noProxy": "localhost,127.0.0.1"
   }
 }
}
EOF

**Comment by wenottingham** [comment]
I'm not sure what specifically is happening here that would be specific to RHEL 7.8, as it's all under docker. Check the SELinux logs?

**Comment by ghost** [comment]
Yes - you are right. It's all under docker. And the message comes from the awx_task container.
I have checked the filesystem in the docker container: There is no /var/run/redis/redis.sock file.

(py_venv) [adminext@vlx24001 awx]$ sudo docker exec -it awx_task bash
bash-4.4# ls -la  /var/run/redis/
total 0
drwxrwxrwx. 2 root root  6 Jul  9 19:25 .
drwxr-xr-x. 1 root root 34 Jul  9 19:26 ..

This should be created by the scripts running in the docker container ?!
I will disable SE-Linux and i will retry the installation. After that i will give you a feedback.

**Comment by ghost** [comment]
Disabled SE-Linux. Now it works. Very strange.
We haven't defined any custom SE-Linux rules (as far as i know).

Is there a detailed Installation handbook for AWX ? Maybe i missed something.

best regards,
Michael H.G. Schmidt

**Comment by ghost** [comment]
Ok. I tried to fix the selinux rules in RHEL 7.8 (standard installation!).
But this is not possible with "audit2allow".

Please provide a script to fix the selinux rules for awx. Will you ?
Thanks in advance.

best regards,
M. Schmidt

**Comment by ryanpetrello** [comment]
Hey @mhgschmidt,

We don't really have such a script - you might want to check your SELinux audit logs and see if you can find any clues.  If we figure out what's up, perhaps we could suggest a fix in the installer, or turn this into a known issue for RHEL 7.8.

**Comment by ryanpetrello** [comment]
@mhgschmidt for what it's worth, I've just spun up a vanilla RHEL 7.8 in ec2 and tried installing AWX 13.0.0 there, and I'm not encountering the issue you've described:

```
[ec2-user@ip-10-149-136-29 ~]$ head /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.8 (Maipo)"
[ec2-user@ip-10-149-136-29 ~]$ getenforce
Enforcing
```

```
[ec2-user@ip-10-149-136-29 ~]$ docker ps -a
CONTAINER ID        IMAGE                COMMAND                  CREATED              STATUS              PORTS                  NAMES
bb336d12fc87        ansible/awx:13.0.0   "tini -- /usr/bin/la…"   About a minute ago   Up About a minute   8052/tcp               awx_task
dd03eec120fe        ansible/awx:13.0.0   "tini -- /bin/sh -c …"   About a minute ago   Up About a minute   0.0.0.0:80->8052/tcp   awx_web
b49432ad831b        postgres:10          "docker-entrypoint.s…"   About a minute ago   Up About a minute   5432/tcp               awx_postgres
e48338a65892        redis                "docker-entrypoint.s…"   About a minute ago   Up About a minute   6379/tcp               awx_redis
```

<img width="547" alt="image" src="https://user-images.githubusercontent.com/214912/87444548-ec7b8000-c5c4-11ea-9464-308fecdadb97.png">

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/214912/87444670-12088980-c5c5-11ea-904e-8483a47d4029.png">


I used these instructions to install:

https://github.com/ansible/awx/blob/devel/INSTALL.md#docker-compose

**Comment by alexhaydock** [comment]
I can reproduce this on RHEL 7.8.

I believe it's down to the lack of `:z` tags on the Redis socket in [docker-compose.yml.j2](https://github.com/ansible/awx/blob/devel/installer/roles/local_docker/templates/docker-compose.yml.j2).

You will notice in that file that the PostgreSQL data is bind-mounted with an uppercase `:Z`, which [allows Docker to automatically configure the SELinux labels](https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label) for the files/directories bind-mounted into this specific container. But the Redis socket and config don't have this, or the label which the socket should have (lowercase `:z`) which would allow it to be bind-mounted into both the Redis container and the `awx_task` container.

@ryanpetrello Did you reproduce this using the upstream Docker package from Docker Inc, or with the `docker` package from the RHEL repo? My guess would be that @mhgschmidt is using the RHEL package (which ships with SELinux enabled for the Docker daemon), and you are using the Docker Inc package, which doesn't and so wouldn't present this issue. I may be wrong though!

**Comment by christianeiselt** [comment]
> I can reproduce this on RHEL 7.8.
> 
> I believe it's down to the lack of `:z` tags on the Redis socket in [docker-compose.yml.j2](https://github.com/ansible/awx/blob/devel/installer/roles/local_docker/templates/docker-compose.yml.j2).
> 
> You will notice in that file that the PostgreSQL data is bind-mounted with an uppercase `:Z`, which [allows Docker to automatically configure the SELinux labels](https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label) for the files/directories bind-mounted into this specific container. But the Redis socket and config don't have this, or the label which the socket should have (lowercase `:z`) which would allow it to be bind-mounted into both the Redis container and the `awx_task` container.

I also can reproduce this on CentOS 7 (1810) and with your help I was able to get the container running by adding `,z` to the relevant lines. After that the playbook ran just fine and the container keeps running. Still no AWX web site though, but this seems to be a different issue...

![Bildschirmfoto 2020-08-18 um 20 01 34](https://user-images.githubusercontent.com/21975779/90548721-ab5f2880-e18d-11ea-8b6f-da840b1ee4bb.png)
