### ISSUE TITLE
Re-evaluate the usage of translations files during development

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#7602]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Now that we started to generate build files for the new UI, a series of `.po and .js` files were generated. Not being able to ignore or removed from `src/locales/messages/` since they are required during development.

https://github.com/ansible/awx/blob/d10fdda45336f8e210e6df25480d5d6e7f172765/awx/ui_next/src/App.jsx#L17

This is the work flow described by `lingui.js` project for a react app.

https://lingui.js.org/tutorials/setup-cra.html

 To be explored: 

https://lingui.js.org/guides/dynamic-loading-catalogs.html

**Comment by jakemcdermott** [comment]
Adding a note so we remember to remove this work-around once we finish work on this issue: https://github.com/ansible/awx/commit/c0d8474ac6e2c85521b82bec8f3b0bd2990ae755

**Comment by rooftopcellist** [comment]
@nixocio This PR will remove the `messages.js` files, the are git-ignored, so they will no longer be an issue when the ui is built.  
https://github.com/ansible/awx/pull/9483

**Comment by jakemcdermott** [comment]
@nixocio I think this may be resolved with @rooftopcellist 's pr. Can you take a look?

**Comment by nixocio** [comment]
> @nixocio I think this may be resolved with @rooftopcellist 's pr. Can you take a look?

@jakemcdermott yeah, I started with a clean slate - I removed all files from `awx/awx/ui_next/src/locales`.

After `npm run start`. 
```
(base) ➜  locales git:(ui_delete_2) tree .
.
├── en
│   ├── messages.js
│   └── messages.po
├── es
│   ├── messages.js
│   └── messages.po
├── fr
│   ├── messages.js
│   └── messages.po
├── ja
│   ├── messages.js
│   └── messages.po
├── nl
│   ├── messages.js
│   └── messages.po
└── zh
    ├── messages.js
    └── messages.po

6 directories, 12 files
```

**Comment by nixocio** [comment]
@jakemcdermott, based on the above I consider this issue verified. Closing.
