### ISSUE TITLE
Enable html in custom login text

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#7603]
### summary
see: https://github.com/ansible/awx/pull/7585 --> https://github.com/ansible/awx/issues/7600

- Could try to use `__dangerouslySetInnerHTML` along with `html-entities` to sanitize (like we do for job events: https://github.com/ansible/awx/blob/devel/awx/ui_next/src/screens/Job/JobOutput/JobEvent.jsx#L55)

- If that doesn't work we'd probably need to first put in a request to pf-react to explicitly enable passing a `React.ReactNode` to the LoginPage component for the `textContent` prop like they do for the `helperText` prop: https://patternfly-react.surge.sh/documentation/react/components/loginpage

**Comment by mabashian** [comment]
@jakemcdermott bumping this up to high as it seems like something we supported in the old UI.  If you think differently feel free to readjust.

**Comment by tiagodread** [comment]
@one-t can we close this?
