### ISSUE TITLE
Can't edit credential secrets

### ISSUE THREAD

**Issue by ronjarrell** [ansible/awx#7606]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I can create a credential just fine, for instance a Google Compute Engine credential, and import the json file.
After that, there's no button to clear the encrypted password and allow me to upload a new version of the key.
This seems to apply to all my credentials that had that button before 13.0.0.

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.6
* Operating System: Centos 7 on tower, Mac on client
* Web Browser: chrome

##### STEPS TO REPRODUCE

Create credential.
Upload secret
Try to upload new secret.

##### EXPECTED RESULTS

Expeced to be able to update secret

##### ACTUAL RESULTS
Lots of clicking an no ability to edit fields.

**Comment by jakemcdermott** [comment]
**expected:**

![Screenshot from 2020-07-13 09-04-52](https://user-images.githubusercontent.com/9753817/87307692-0c894180-c4e8-11ea-8e1c-ee08a64421f2.png)



**actual:**

![Screenshot from 2020-07-13 09-01-25](https://user-images.githubusercontent.com/9753817/87307711-11e68c00-c4e8-11ea-8ddc-0f2a2eb5f1d4.png)

**Comment by jakemcdermott** [comment]
Hey @ronjarrell - we merged a patch for this to devel. It'll be fixed in the next release of awx.

**Comment by ronjarrell** [comment]
Excellent!

**Comment by unlikelyzero** [comment]
Verified and added to our coverage in 7606
