### ISSUE TITLE
Filter in source inventory by Azure

### ISSUE THREAD

**Issue by Tomelin** [ansible/awx#7612]
Hi guys,

I have source inventory by Azure and need to create the filter with this informations:
- The VMs is running
- The OS is Linux
- The name contains lnx

I create this filter but not working
host_filters: "{{ powerstate == 'running' }} and {{ 'lnx' in computer_name }} and {{ os_profile.system == 'linux' }}"
or 
host_filters: "{{ ( powerstate == 'running' ) and ( 'lnx' in computer_name ) and ( os_profile.system == 'linux' )  }}"

How can create the filter in source inventory?

**Comment by jakemcdermott** [comment]
Hey Tomelin,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
