### ISSUE TITLE
CyberArk AIM Central Credential Secret Lookup fails due to forced HTTP/2

### ISSUE THREAD

**Issue by infamousjoeg** [ansible/awx#7617]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When using or testing the CyberArk AIM Central Credential Provider Lookup, no test status message notification is returned.  After approximately 60 seconds or so, it will return ‘Test Failed’ with no further information as to the error.

##### ENVIRONMENT
* Tower version: 3.6.3+
* Tower install method: ansible
* Ansible version:  X.Y.Z
* Operating System: RHEL 8
* Web Browser: Mozilla Firefox 78.02

##### STEPS TO REPRODUCE

1. Setup CyberArk AIM Central Credential Lookup to point to your Central Credential Provider web service in the URL field.
2. Enter in the Application ID assigned for access to the secrets' safe.
3. Add any optional client certificate and key data needed for client certificate authentication to the web service and Certificate Serial Number verification for CyberArk authentication.
4. Click "Test" and nothing will happen.

##### EXPECTED RESULTS

Within 5 seconds, a toast notification message should appear and say whether the 'Test Succeeded' or 'Test Failed'.  If 'Test Failed' is received, clear and concise error message information is provided for debugging.

##### ACTUAL RESULTS

Nothing happens.  If you're lucky, about 60 seconds later you will receive a 'Test Failed' toast notification message with no error message output.

##### ADDITIONAL INFORMATION

**The following tests were ran on Tower v3.7.1 and v3.6.4 all with the same issue.**
**_The first working version was v3.6.2, which I am back on again._**
_Test #1: curl from Tower host_
To test this, I SSH’ed into the Tower host itself.  I used `curl` to communicate with our Central Credential Provider web service and gave all the same information as was setup in the Lookup.  The test failed.  The failure was due to HTTP/2 being used and the error message requested the usage of HTTP/1.1 instead.
 
_Test #2: curl from Tower host with --http1.1 flag set_
I then used the same `curl` command again and added the flag, `--http1.1`, to require HTTP/1.1 to be used regardless of the default setting.  The test was successful.
 
_Test #3: curl from Tower host with CURLOPT_HTTP_VERSION=CURL_HTTP_VERSION_1_1_
Finally, I tested setting the environment variable for the CURLOPT_HTTP_VERSION to 1.1 and the test failed again.  Apparently, the only way it would work is by setting the `--http1.1` flag on the `curl` request.

With all of that done, is there a way to configure the CyberArk AIM Central Credential Provider Lookup to force HTTP/1.1 instead of HTTP/2 and avoid these issues?  Is there a way to set the entire Tower host to enforce HTTP/1.1 only?  Finally, if none of those are possibilities, would it be possible to update the `curl` command our plugin uses to have a hardcoded `--http1.1` appended to the requests?

**Comment by infamousjoeg** [comment]
@izgeri

**Comment by jakemcdermott** [comment]
Thanks for the bug report.

> The following tests were ran on Tower v3.7.1 and v3.6.4 all with the same issue.
The first working version was v3.6.2, which I am back on again.

Strange. The plugin code doesn't change between 3.6.2 and 3.6.3 at all. Nevertheless, _something_ must have changed or you wouldn't be observing this behavior. 

Are you sure the requests emitted by the _tower plugin_ (not curl) go from HTTP/1 to HTTP/2 when you change from version 3.6.2 to 3.6.3? :thinking: That's a good bit of info for tracking this bug down if you can confirm it.

**Comment by wenottingham** [comment]
The plugin does this:

```
    with CertFiles(client_cert, client_key) as cert:
        res = requests.get(
            request_url + request_qs,
            timeout=30,
            cert=cert,
            verify=verify,
        )
```

Requests doesn't *do* HTTP/2 requests, so whatever you're seeing, it's not that.

**Comment by wenottingham** [comment]
I think you're seeing https://github.com/ansible/awx/issues/6986 until proven otherwise.

**Comment by jakemcdermott** [comment]
I think you're right @wenottingham. This sounds very similar to #6986 (and we haven't backported that to any of the versions in mentioned)

**Comment by jakemcdermott** [comment]
yep. @infamousjoeg I believe this is already fixed on devel by @ryanpetrello: https://github.com/ansible/awx/pull/7175

We're also slated to backport it to the upcoming release.

**Comment by wenottingham** [comment]
Also, @infamousjoeg - please try that linked PR and confirm it works for you.

**Comment by infamousjoeg** [comment]
Will do, thank you @wenottingham and @jakemcdermott -- I suspect you're correct as my tests included Client Certificate & Key data.  I will follow up with more info.

**Comment by wenottingham** [comment]
This is fixed in our testing. Please reopen if this does not work for you.
