### ISSUE TITLE
Failure when accessing a project with submodules using git over HTTPS creds with gitlab access token

### ISSUE THREAD

**Issue by dojones1** [ansible/awx#7623]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Pulling repos with submodules using gitlab access tokens fails to pull the submodules even though they are hosted on the same server .
It works for the main repo pull, but the submodule pull appears to assume that we should use SSH key (which has of course not been provided).

##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.3
* Operating System: Centos
* Web Browser: Chrome 83.0.4103.116

##### STEPS TO REPRODUCE

Submodule repo held on Bitbucket
Primary Repo held on Bitbucket
- created with a submodule which refers to the submodule repo.

Access Token created for user on Bitbucket

Create AWX credentials using the access token
Create AWX project which pulls code base using Git over HTTPS using the AWX credential (User access Token)
Update the AWX project

##### EXPECTED RESULTS

Project would successfully update

##### ACTUAL RESULTS

{
    "cmd": "/usr/bin/git submodule foreach /usr/bin/git fetch",
    "rc": 1,
    "stdout": "Entering 'services/webscape-ui'\n",
    "stderr": "fatal: remote error: Repository not found\nThe requested repository does not exist, or you do not have permission to\naccess it.\nStopping at 'services/webscape-ui'; script returned non-zero status.\n",
    "msg": "fatal: remote error: Repository not found\nThe requested repository does not exist, or you do not have permission to\naccess it.\nStopping at 'services/webscape-ui'; script returned non-zero status.",
    "invocation": {
        "module_args": {
            "dest": "/var/lib/awx/projects/_19__monorepo",
            "repo": "https://$encrypted$:$encrypted$@url/scm/proj/monorepo.git",
            "version": "elk-deploy",
            "force": true,
            "remote": "origin",
            "clone": true,
            "update": true,
            "verify_commit": false,
            "gpg_whitelist": [],
            "accept_hostkey": false,
            "bare": false,
            "recursive": true,
            "track_submodules": false,
            "refspec": null,
            "reference": null,
            "depth": null,
            "key_file": null,
            "ssh_opts": null,
            "executable": null,
            "umask": null,
            "archive": null,
            "separate_git_dir": null
        }
    },
    "stdout_lines": [
        "Entering 'services/submodule'"
    ],
    "stderr_lines": [
        "fatal: remote error: Repository not found",
        "The requested repository does not exist, or you do not have permission to",
        "access it.",
        "Stopping at 'services/submodulei'; script returned non-zero status."
    ],
    "_ansible_no_log": false,
    "changed": false
}

**Comment by wenottingham** [comment]
This can't work this way - the way it works for the checkout is we interpolate the token into the URL.

AWX does not parse the submodules (git itself does), and cannot do this interpolation there.

**Comment by brlin-tw** [comment]
For drone CI it is possible to specify a map of private HTTPS repo URLs <--> private SSH repo URLs to workaround the problem, is that feasible in AWX?
