### ISSUE TITLE
Handle project and galaxy caching in Execution Environments

### ISSUE THREAD

**Issue by shanemcd** [ansible/awx#7625]
##### ISSUE TYPE
 - Feature Idea

We need to ensure the work done in https://github.com/ansible/awx/issues/5518 does not regress once we move to Execution Environments.

**Comment by AlanCoding** [comment]
I hope that I now have https://github.com/ansible/awx/pull/7643 stabilized. Let me give a synopsis of the interfaces here.

The playbook variables `roles_destination` and `collections_destination` are being removed in that pull request. Those were destinations in a job folder, which we had to give access to via bubblewrap. I want to be very specific about this - project updates should only need special access to the projects folder.

The way that's done is exposing `settings.PROJECTS_ROOT` as a bubblewrap show path. This gives access to all project folders, which might not be ideal. If you wanted to be more explicit, you could give it access to _only_ the folders:

 - `/var/lib/awx/projects/_42__project_name`
 - `/var/lib/awx/projects/.__awx_cache/_42__project_name`

The first one is the project folder, which has been a thing for as long as Ansible Tower has. The latter has everything we need for role & collection caching. Obviously, you should expect the project update to be writing to and making changes to these folders.

In my initial implementation (now abandoned), I hit one surprising issue which I want to disclose:

```
awx_1       | 2020-07-17 20:42:54,869 ERROR    awx.main.tasks project_update 93 (running) Post run hook errored.
awx_1       | Traceback (most recent call last):
awx_1       |   File "/awx_devel/awx/main/tasks.py", line 1499, in run
awx_1       |     self.post_run_hook(self.instance, status)
awx_1       |   File "/awx_devel/awx/main/tasks.py", line 2410, in post_run_hook
awx_1       |     os.rename(stage_subpath, dest_subpath)
awx_1       | OSError: [Errno 18] Invalid cross-device link: '/var/lib/awx/projects/.__awx_cache/_67__branch_override_with_different_role_requirements_/stage/requirements_roles' -> '/tmp/awx_92_7a3rost5/requirements_roles'
```

This came from the fact that our _development environment maps the project folder_, and I tried to use `os.rename` to move some cache content from inside the project folder to the job private data directory under `/tmp`. That's not allowed, you can copy across volumes, but you can't _move_ it.

Obvious solution to that - don't design anything to move stuff between folders which might be in different volumes. We shouldn't be doing any of that with the updated PR. Even if you mounted separate volumes for the project folder and the project's cache folder, I don't anticipate problems.

**Comment by AlanCoding** [comment]
The issues we had here have been resolved. The main `execution-environments` branch has not been merged, but otherwise I'm good to close it.

Some of this may still get re-worked as we finalize the OCP solution, which may have a long-lived container, which will have to mount the global projects directory.

**Comment by akus062381** [comment]
@AlanCoding - can you please explain how and when the collections are cached? When are they first downloaded, and under what circumstance(s) are they redownloaded? What exactly do we want to verify?

**Comment by AlanCoding** [comment]
I don't think there is anything to be done. Everything needed is moved into the job private_data_dir before it goes to the container or container group. @shanemcd are you good to close this?

**Comment by wenottingham** [comment]
Talked to @shanemcd , this is good to close.
