### ISSUE TITLE
fix ui_next list discrepancies

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#7626]
lists need to be audited for a consistent look and feel

- try to make sections align across lists (if possible, some may be based on the contents).
- all counts should be in separate sections (i.e. organization team/member counts should be spaced)
- all sections that are not name should include a black bold label

**Comment by mabashian** [comment]
@jlmitch5 you think we still need this?

**Comment by unlikelyzero** [comment]
added to coverage https://github.com/ansible/awx/issues/6189

**Comment by tiagodread** [comment]
Closing this issue because all these items are being addressed on https://github.com/ansible/awx/issues/6189
