### ISSUE TITLE
Unable to create Smart Inventory from information of Inventory created in different Organizations

### ISSUE THREAD

**Issue by garamirseokim** [ansible/awx#7630]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Unable to create Smart Inventory from information of Inventory created in different Organizations even if users have inventory "Admin" permission.

##### ENVIRONMENT
Ansible Tower version: 3.7.0 and 3.6.2
Operating System: RHEL 7.7

##### STEPS TO REPRODUCE

**Creating Access**
Login to Dashboard as admin user 

1. Create Organization "ORG-GROUP" and "ORG-TEAM"
2. Create Team "MY-TEAM" (Organization is ORG-TEAM)
3. Create User "testuser" (Organization is ORG-TEAM)
4. Register "testuser" with "MY-TEAM" Team
5. Inventory Create "Test Inventory" and register some hosts (Organization is ORG-GROUP)
6. Assign Admin Role of "Test Inventory" to Team "MY-TEAM"

**Creating Smart Inventory**
Login to Dashboard again as testuser user

7. Make sure "Test Inventory" is existing in Inventory
8. Check that the host can be listed from the HOST tab of "Test Inventory" and you are able to see the host list.

 ![image](https://user-images.githubusercontent.com/58404577/87636837-abca6500-c784-11ea-8522-ee9cae0ff48a.png)
 
9. Try to create a Smart Inventory

##### EXPECTED RESULTS

Able to search the host list from Dynamic/Static Inventory(Test Inventory) to create Smart Inventory with user "testuser".

##### ACTUAL RESULTS

Unable to search any host from Dynamic/Static Inventory(Test Inventory) to create a Smart Inventory with user "testuser". 
![image](https://user-images.githubusercontent.com/58404577/87636088-82f5a000-c783-11ea-8aa2-34b59461a1df.png)

##### ADDITIONAL INFORMATION

None

**Comment by wenottingham** [comment]
Note that the smart inventory will still be limited to a particular organization. Can you create it via the API?

**Comment by garamirseokim** [comment]
@wenottingham I was able to create a Smart Inventory via API but I can't see the host list. Is there any other workaround?

``` 
{
    "name": "newSmartInventory",
    "description": "",
    "organization": 3,
    "kind": "smart",
    "host_filter": null,
    "variables": "",
    "insights_credential": null,
    "host_filter": "name__icontains=192.168.100.222"
}

**Comment by wenottingham** [comment]
You have `host_filter` twice in that output, I don't think that's the actual definition?

**Comment by garamirseokim** [comment]
@wenottingham Thank you for your feedback. I tried it again with single ``` host_filter ``` as below but I still can't see the host list. 
``` 
{
    "name": "newSmartInventory",
    "description": "",
    "organization": 3,
    "kind": "smart",
    "variables": "",
    "insights_credential": null,
    "host_filter": "name__icontains=192.168.100.222"
}
```

**Comment by TheRealHaoLiu** [comment]
Smart inventories is deprecated in favor of constructed inventory #13303
