### ISSUE TITLE
Error Message Issue when creating duplicate host in an inventory.

### ISSUE THREAD

**Issue by ghost** [ansible/awx#764]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
When you try to add a host to an inventory and the host already exists then you get a cryptic error message.

![update_awx_task_awx_web2](https://user-images.githubusercontent.com/6487265/33577820-20de9884-d8f9-11e7-9cb0-a32fb6ccc189.png)

Here is the console:

![update_awx_task_awx_web_error](https://user-images.githubusercontent.com/6487265/33577836-2da1b81c-d8f9-11e7-82af-f231bff666d9.png)

##### ENVIRONMENT
* AWX version:  AWX 1.0.1.268
* AWX install method:  docker on linux 
* Ansible version:  2.4.2.0
* Operating System: CENTOS 7.4
* Web Browser: Google Chrome 

##### STEPS TO REPRODUCE

Create an Inventory.
Add a host with name Test1
Try to add another host named Test1

##### EXPECTED RESULTS

An error message that states duplicate host

##### ACTUAL RESULTS

Cryptic Message seen above

**Comment by jaredevantabor** [comment]
moving to testing.

**Comment by ghost** [comment]
![update_awx_task_awx_web_error1](https://user-images.githubusercontent.com/6487265/33626761-64db81b6-d9b0-11e7-9ad1-365f8f17aea1.png)

This bug has been resolved. The above is the new result.
