### ISSUE TITLE
Details page for Instance Groups

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#7640]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add details page for Instance Groups

**Comment by mabashian** [comment]
@nixocio I see that #7742 has merged, does that mean we can close this issue?

**Comment by nixocio** [comment]
@unlikelyzero, I am re-opening this one. Based on your feedback.

**Comment by dsesami** [comment]
This is closed out, but https://github.com/ansible/awx/pull/7929#pullrequestreview-476936979 needs to be addressed (separately). I am following up with @nixocio to see if there is an issue for it.
