### ISSUE TITLE
Generate Custom Reports From Job Template Runs

### ISSUE THREAD

**Issue by imareporter** [ansible/awx#7647]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Per an user's request, they would like to generate custom reports based on job template runs via the Tower UI. For example, when patching remote systems, they would like to generate a pie chart where it shows systems that were successful (`ok` in `PLAY RECAP`), systems that failed (`failed` in `PLAY RECAP`), and systems that were missed (`unreachable` in `PLAY RECAP`).

**Comment by wenottingham** [comment]
This is not something we plan to do directly in the interface at this time; all the data is available in the API for them to generate custom reports.
