### ISSUE TITLE
Project sync runs forever

### ISSUE THREAD

**Issue by anxstj** [ansible/awx#7650]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Updating a project works without issues, except the Job is marked as "still running" and canceling is not possible. Which blocks every associated Job Template from running.

##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: docker
* Ansible version:  2.9.9
* Operating System: Debian 10
* Web Browser: Firefox 78

##### STEPS TO REPRODUCE

I have only one of many projects where this happens. The project looks like:

Create a project with the following settings:
* Name: myname
* Description: mydescription
* Organization: myorganization
* SCM Type: Git
* SCM URL: git@mygitlab.example.com:myuser/myproject.git
* SCM Branch: 
* SCM Refspec:
* SCM Credential: <Source Control Credential: SSH Key>
* SCM update options:
  * [x] clean
  * [x] Delete on update
  * [x] update revision on launch (300 seconds cache timeout)
  * [ ] allow branch override

Triggering a resync via projects directly or indirectly via launching an associated job template results in the same result: The update works, but the job itself never finished (see attached picture).

Other observations:
* Canceling the job is not possible.
* The job will never terminate. It runs for days.
* Deleting the job via `awx-manage shell_plus` removes the job, but often (not always) it gets stuck again on the next start.
* After the job was deleted, the project status is still shown as "SCM update currently running".  Canceling will result in the following message: 
```
An SCM update does not appear to be running for project: myproject
```

##### EXPECTED RESULTS

The job should finish as successful.

##### ACTUAL RESULTS

The job keeps running forever.

##### ADDITIONAL INFORMATION

I find it hard to debug this misbehavior. There seems no reason why the sync job is still in status running. Any help to debug is well appreciated.

![grafik](https://user-images.githubusercontent.com/51952982/87921541-0280b900-ca7b-11ea-8c5f-26788d207b0d.png)

```
GET /api/v2/projects/448/project_updates/
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
X-API-Node: awx
X-API-Product-Name: AWX
X-API-Product-Version: 11.2.0
X-API-Time: 0.346s

{
    "count": 229,
    "next": "/api/v2/projects/448/project_updates/?page=2",
    "previous": null,
    "results": [
        ...
        {
            "id": 61035,
            "type": "project_update",
            "url": "/api/v2/project_updates/61035/",
            "related": {
                "created_by": "/api/v2/users/15/",
                "credential": "/api/v2/credentials/60/",
                "unified_job_template": "/api/v2/projects/448/",
                "stdout": "/api/v2/project_updates/61035/stdout/",
                "project": "/api/v2/projects/448/",
                "cancel": "/api/v2/project_updates/61035/cancel/",
                "scm_inventory_updates": "/api/v2/project_updates/61035/scm_inventory_updates/",
                "notifications": "/api/v2/project_updates/61035/notifications/",
                "events": "/api/v2/project_updates/61035/events/"
            },
            "summary_fields": {
                "organization": {
                    "id": 6,
                    "name": "D1-My organization",
                    "description": ""
                },
                "project": {
                    "id": 448,
                    "name": "D27 - so/profiles/esxi_rsyslog.old",
                    "description": "sets rsyslog proxy",
                    "status": "running",
                    "scm_type": "git"
                },
                "credential": {
                    "id": 60,
                    "name": "deploy key (ro)",
                    "description": "Gitlab Deploy Key (read-only)",
                    "kind": "scm",
                    "cloud": false,
                    "kubernetes": false,
                    "credential_type_id": 2
                },
                "unified_job_template": {
                    "id": 448,
                    "name": "so/profiles/esxi_rsyslog.old",
                    "description": "sets rsyslog proxy",
                    "unified_job_type": "project_update"
                },
                "instance_group": {
                    "id": 1,
                    "name": "tower",
                    "is_containerized": false
                },
                "created_by": {
                    "id": 15,
                    "username": "myuser",
                    "first_name": "my",
                    "last_name": "user"
                },
                "user_capabilities": {
                    "delete": true,
                    "start": true
                }
            },
            "created": "2020-07-20T08:00:53.343861Z",
            "modified": "2020-07-20T08:00:54.067458Z",
            "name": "so/profiles/esxi_rsyslog.old",
            "description": "sets rsyslog proxy",
            "unified_job_template": 448,
            "launch_type": "manual",
            "status": "running",
            "failed": false,
            "started": "2020-07-20T08:00:54.528027Z",
            "finished": null,
            "canceled_on": null,
            "elapsed": 5943.322819,
            "job_explanation": "",
            "execution_node": "awx",
            "local_path": "_448__d27_soprofilesesxi_rsyslog",
            "scm_type": "git",
            "scm_url": "git@gitlab.example.com:myuser/myprjoject.git",
            "scm_branch": "master",
            "scm_refspec": "",
            "scm_clean": true,
            "scm_delete_on_update": true,
            "credential": 60,
            "timeout": 0,
            "scm_revision": "79155336c79db3ea44efb1aa055efdc7633b7999",
            "project": 448,
            "job_type": "check",
            "job_tags": "update_git,delete"
        }
```

```
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: text/plain ;utf-8
Vary: Accept
X-API-Node: awx
X-API-Product-Name: AWX
X-API-Product-Version: 11.2.0
X-API-Time: 0.030s

Enter passphrase for /tmp/awx_61035_flh_6b4q/artifacts/61035/ssh_key_data: 
Identity added: /tmp/awx_61035_flh_6b4q/artifacts/61035/ssh_key_data (deploy)

PLAY [Update source tree if necessary] *****************************************

TASK [delete project directory before update] **********************************
changed: [localhost]

TASK [update project using git] ************************************************
changed: [localhost]

TASK [Set the git repository version] ******************************************
ok: [localhost]

TASK [Repository Version] ******************************************************
ok: [localhost] => {
    "msg": "Repository Version 79155336c79db3ea44efb1aa055efdc7633b7999"
}

PLAY [Install content with ansible-galaxy command if necessary] ****************

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

**Comment by ryanpetrello** [comment]
Hey @anxstj,

This sounds a lot like a performance issue we resolved in 12.0.0:

https://github.com/ansible/awx/commit/bf65b40241d60e99e49b3109a33c26f26cd418ec

**Comment by anxstj** [comment]
Is there anything I can check to verify that it is the mentioned performance issue?

You mentioned a commit in tower (which I can not read), do you have the corresponding awx commit as well?

**Comment by anxstj** [comment]
Just to be sure that there is no misunderstanding: This is a **project** update, not an inventory update. The project contains only playbooks and roles.

**Comment by ryanpetrello** [comment]
Hey @anxstj sorry about that - I pasted the wrong URL.  I've updated it above.

**Comment by gamuniz** [comment]
@ryanpetrello it might be https://github.com/ansible/awx/blob/11.2.0/awx/main/models/projects.py#L202 you changed in a later version

**Comment by ryanpetrello** [comment]
Good call @gamuniz.  @anxstj honestly I'd just recommend upgrading, it sounds like what you're encountering is one of a series of issues we resolved in recent versions of AWX.

**Comment by anxstj** [comment]
@ryanpetrello thank you for your efforts.
I will upgrade tomorrow and report back here.

**Comment by anxstj** [comment]
I wasn't able to reproduce the issue with AWX 13.0.0.
Thank you for your support. I will close this issue now.
