### ISSUE TITLE
Preflight check for node version

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#7651]
##### ISSUE TYPE
Add a preflight check that runs before `install` and `build` that checks for the expected version of node & fail loudly with an informative error message when there is a version mismatch.

**Comment by jakemcdermott** [comment]
https://github.com/ansible/awx/pull/7652

**Comment by dsesami** [comment]
Tried this out with nvm (`nvm use 8`) to switch to node 8.12. I was unable to verify that `make ui-devel-next`, `npm run build`, and `npm start` raised errors -- seemed to go through just fine. I'm wondering if I have something misconfigured. I'd like to follow up with you on this one so we can make sure it works.

**Comment by dsesami** [comment]
This worked out after a `make clean-ui`. Works great!
