### ISSUE TITLE
Make Variables/Artifacts labels match style of other labels in Job Details

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7654]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
<img width="1409" alt="Screen Shot 2020-07-20 at 9 45 11 AM" src="https://user-images.githubusercontent.com/9889020/87944908-02c68780-ca6e-11ea-9904-3ad11a786c86.png">

They need to be bold/maybe larger font?

**Comment by mabashian** [comment]
This got fixed somewhere along the way

**Comment by unlikelyzero** [comment]
covered in job-templates.spec.js
