### ISSUE TITLE
Add ability to cancel a job from details/output view while job is running

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7657]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
It looks like we're currently _always_ showing the delete button on a job (rbac permitted):

<img width="1381" alt="Screen Shot 2020-07-20 at 10 02 36 AM" src="https://user-images.githubusercontent.com/9889020/87947367-35be4a80-ca71-11ea-9a49-f0167f539938.png">

When a job is pending/waiting/running then we should be showing a Cancel button rather than the delete button.  You can see the logic outlined in the old app here: https://github.com/ansible/awx/blob/devel/awx/ui/client/features/output/details.partial.html#L10-L41

**Comment by nixocio** [comment]
Just to add that we also show the `Cancel job` and `Delete` for completed jobs, for example.

![image](https://user-images.githubusercontent.com/9053044/96042573-99230300-0e3b-11eb-95e3-48d84a0c1330.png)

**Comment by mabashian** [comment]
Closing - this will be tracked in #8848

**Comment by unlikelyzero** [comment]
@mabashian this was not completed as a part of https://github.com/ansible/awx/issues/8848

**Comment by unlikelyzero** [comment]
This needs to be updated in our tests

**Comment by tiagodread** [comment]
Added a test to cover this scenario in e2e
