### ISSUE TITLE
OpenStack dynamic inventory fails to sync

### ISSUE THREAD

**Issue by sdwallinga** [ansible/awx#766]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Cannot use built-in OpenStack dynamic inventory plugin, script fails with unhelpful errors. 

##### ENVIRONMENT
* AWX version: 1.0.1.10
* AWX install method: docker on linux
* Ansible version:  2.4.0

##### STEPS TO REPRODUCE

Create OpenStack credential with project details
Create new inventory
Create OpenStack source using credential
Launch a 'Sync' job

##### EXPECTED RESULTS

Dynamic inventory is successfully loaded into AWX

##### ACTUAL RESULTS

Here is the stdout from the sync job: 
```
2017-12-04 21:52:08,944 INFO awx.main.commands.inventory_import Updating inventory 17: OpenStack-Dynamic 
2017-12-04 21:52:08,970 INFO awx.main.commands.inventory_import Reading Ansible inventory source: /usr/lib/python2.7/site-packages/awx/plugins/inventory/openstack.py 
Traceback (most recent call last): 
File "/usr/bin/awx-manage", line 9, in <module> 
  load_entry_point('awx==1.0.1.10', 'console_scripts', 'awx-manage')() 
File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 107, in manage 
  execute_from_command_line(sys.argv) 
File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line 
  utility.execute() 
File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute 
  self.fetch_command(subcommand).run_from_argv(self.argv) 
File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv 
  self.execute(*args, **cmd_options) 
File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute 
  output = self.handle(*args, **options) 
File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 661, in handle 
  return self.handle_noargs(**options) 
File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 1000, in handle_noargs 
  self.is_custom) 
File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 243, in load_inventory_source 
  is_custom=is_custom).load() 
File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 179, in load 
  data = self.command_to_json(base_args + ['--list']) 
File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 163, in command_to_json 
  self.method, proc.returncode, stdout, stderr)) 
RuntimeError: ansible-inventory failed (rc=4) with stdout: 

stderr: 
ERROR! Could not parse inventory source /usr/lib/python2.7/site-packages/awx/plugins/inventory/openstack.py with available plugins: 
Plugin script failed: Inventory script (/usr/lib/python2.7/site-packages/awx/plugins/inventory/openstack.py) had an execution error: Error fetching server list on devstack::  

Plugin ini failed: /usr/lib/python2.7/site-packages/awx/plugins/inventory/openstack.py:48: Expected key=value host variable assignment, got: argparse 
```

##### ADDITIONAL INFORMATION

I'm able to run the script manually (`openstack.py --list`) from the awx_web container using an os-client-config rc file with identical credentials.

**Comment by AlanCoding** [comment]
Although the error is wrapped several times, it still returned a kernel of the real error.

> Error fetching server list on devstack::  

I can replicate your scenario, simply by taking my valid openstack credentials, and replacing the host used in the credential with a `.invalid` address. It gives the same error about fetching the server list on devstack.

The layers of wrapping on going on:

 - AWX runs its own task execution environment
 - that environment runs the import management command (Django-ish)
 - that command runs ansible-inventory
 - ansible-inventory uses the script plugin to parse code from https://github.com/ansible/ansible/blob/devel/contrib/inventory/openstack.py
 - that openstack inventory script imports a universe of OpenStack-specific python libraries
 - those libraries use other libraries, which read your cloud configuration, and make requests to your server
 - you server then returns information about host content which goes back up the chain

My best guess is that the other libraries are throwing this particular exception, but the reason they are throwing it is fully compatible with a basic connectivity problem to your server.

It might help you to know that in my openstack credential url looks like `http://server.foo.invalid:5000/v2.0/`, and that it has a username and password. Most likely scenario I'd guess is that your credential isn't fully replicating the resources you have laid down when doing the manual testing. If you want to dig further, you can post the details of the credential you created.

**Comment by sdwallinga** [comment]
Really appreciate the detailed response -- I was able to solve the issue thanks to your clarification about the separate task execution environment. The credential was correct and functioning properly. I was poking around to glean some information from the `awx_task` environment and ended up rebuilding both containers. Turns out, our OpenStack catalog had a simple hostname as the internal URL for our cinder endpoint, which borked the request since it didn't know how to reach it. I had solved this (for manual script execution) by adding an entry to `/etc/hosts` on the `awx_web` container, which, in hindsight, wouldn't be respected by `awx_task`. We corrected the endpoint URL in our OpenStack and it works great! 

Thanks again.

**Comment by shortsteps** [comment]
@sdwallinga, I have the same issue you posted. Could you please help me with further clarification on how you solved?

I've just installed AWX (1.0.1.272), with Docker installation method and Ansible 2.4.0.
First of all, I would like to reproduce the successfull sync from inside awx_task container, but running `openstack.py --list` manually gets me to this error:

```
[root@awx ~]# ./openstack.py --list
Traceback (most recent call last):
  File "./openstack.py", line 66, in <module>
    import os_client_config
ImportError: No module named os_client_config
```
What am I missing? Did you install something inside the container?
I used that [opestack.py](https://raw.githubusercontent.com/ansible/ansible/devel/contrib/inventory/openstack.py), as suggested in Ansible docs.
Thanks a lot

**Edit**: just to add some details, my AWX is an instance of my Openstack Tenant itself.  The OS_AUTH_URL is publicly reachable and I tested from inside awx_task container that it can reach it and it can reach also all the endpoint listed in my API Access section in Horizon.

**Partially solved**: I've solved that issue from inside the container installing that missing packages
```
yum install python-devel gcc
pip install --upgrade pip
pip install python-openstackclient
pip install shade
```
I'm now able to retrieve my inventory from awx_task cli.

However, error persist from UI. Could you please explain better how you solved (endpoint issue and how you discover it)?
Thank you very much

**Comment by shortsteps** [comment]
So sorry guys, I solved. I confused Project Id with Project Name creating credential from UI.
