### ISSUE TITLE
Add workflow output details tab contents

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7660]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
<img width="1678" alt="Screen Shot 2020-07-20 at 10 52 28 AM" src="https://user-images.githubusercontent.com/9889020/87951897-2a6e1d80-ca77-11ea-9b0c-2d20dc6cc48f.png">

Here's what we listed out in the old app:

<img width="501" alt="Screen Shot 2020-07-20 at 10 53 08 AM" src="https://user-images.githubusercontent.com/9889020/87951950-3954d000-ca77-11ea-804b-d6b2c8a3392a.png">

but there could be other things that we _can_ show - inspect the OPTIONS for the job to see if there are other fields that would be useful.

**Comment by unlikelyzero** [comment]
covered in workflow-tabs.spec.js
