### ISSUE TITLE
Add link to visualizer graph for workflows on Templates List

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7663]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
<img width="1462" alt="Screen Shot 2020-07-20 at 11 45 03 AM" src="https://user-images.githubusercontent.com/9889020/87957631-85efd980-ca7e-11ea-8bc8-496972011355.png">

Clicking this icon should take the user straight to `/templates/workflow_job_template/:id/visualizer` (the visualizer tab)

**Comment by tiagodread** [comment]
This feature was merged, tests are written. 👍🏽
