### ISSUE TITLE
Support workflow launch from Templates List

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7664]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Button is currently missing:

<img width="1415" alt="Screen Shot 2020-07-20 at 12 01 18 PM" src="https://user-images.githubusercontent.com/9889020/87959345-bdf81c00-ca80-11ea-8c5c-544968d3d277.png">

Note that this is separate from https://github.com/ansible/awx/issues/5910 although the work could be done at the same time.

**Comment by mabashian** [comment]
This was completed at some point

**Comment by unlikelyzero** [comment]
covered in workflow-operations
