### ISSUE TITLE
API should not accept modification of local_path for nom-manual projects

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#7665]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The API will accept a PATCH to edit `local_path` for a git project, but the change will not take effect.

Some version of a 400 error would be preferable to this. This is a valid field to edit in the case of manual projects, so there's no valid justification that it's "not a field".

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: N/A
* Ansible version:  N/A

##### STEPS TO REPRODUCE

PATCH `/api/v2/projects/6/`

```json
{
  "description": "asdf",
  "local_path": "_6__demo_project_edited"
}
```

##### EXPECTED RESULTS

One of:

 - the local_path value changes to "_6__demo_project_edited"
 - get error

##### ACTUAL RESULTS

No error

description changes to "asdf"

the `local_path` remains at prior value of "_6__demo_project"

**Comment by kdelee** [comment]
Tested this with doing PATCH to a project with:

```
{
    "local_path": "_188__project_FOOEDIT"
}
```

got expected:
```
{
    "local_path": [
        "Cannot change local_path for git-based projects"
    ]
}
```

works for me! thanks
