### ISSUE TITLE
Disabled state for a workflow node doesn't completely cover node

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7668]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
<img width="1679" alt="Screen Shot 2020-07-20 at 1 09 26 PM" src="https://user-images.githubusercontent.com/9889020/87965847-68c10800-ca8a-11ea-824c-fd8852d97016.png">

In this screenshot, the entire node should be greyed out, not just the name of the node.

**Comment by mabashian** [comment]
In order to get the workflow in this state you need to click on the link icon for the second node (Ping)

**Comment by unlikelyzero** [comment]
This will need a visual test

**Comment by akus062381** [comment]
This hasn't been implemented, moving back to needs_devel @wenottingham
