### ISSUE TITLE
Add support for convergence any/all on workflow nodes

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7669]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
In old tower we added this field:

<img width="1673" alt="Screen Shot 2020-07-20 at 1 18 32 PM" src="https://user-images.githubusercontent.com/9889020/87966675-99ee0800-ca8b-11ea-8d50-95041afa2e41.png">

We'll need to add the same field to the workflow node wizard in ui_next.

**Comment by mabashian** [comment]
Probably best to do this after #8399 lands to avoid some nasty conflicts.

**Comment by jlmitch5** [comment]
This has been verified cc @unlikelyzero
