### ISSUE TITLE
Cannot Delete Last workflow survey question

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7670]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
<img width="1483" alt="Screen Shot 2020-07-20 at 1 25 35 PM" src="https://user-images.githubusercontent.com/9889020/87967264-93ac5b80-ca8c-11ea-8050-66400bb6a019.png">

If you create a survey question for a workflow job template and then try to delete that question you get the above error.  It appears as if we're trying to delete the question from `/api/v2/job_templates/:id/survey_spec` instead of `/api/v2/workflow_job_templates/:id/survey_spec`

##### STEPS TO REPRODUCE
1. Create a survey for a WFJT
2. Enable surveys for WFJT
3. Select Survey
4. Attempt to delete Survey
Note: 404

also

1. Create many surveys for a WFJT
2. Enable surveys for WFJT
3. Select All surveys
4. Attempt to delete all surveys
Note: 404

**Comment by unlikelyzero** [comment]
likely the same as https://github.com/ansible/awx/issues/7636

**Comment by AlexSCorey** [comment]
@unlikelyzero @tiagodread this appears to be resolved.  Probably when #7636 was resolved as well.  Can you confirm?

**Comment by unlikelyzero** [comment]
Updated title and repro steps. It was filed here as well https://github.com/ansible/awx/issues/8558

**Comment by tiagodread** [comment]
PR merged, added e2e for it
