### ISSUE TITLE
Add organization to inventory list rows

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7673]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Here's the old UI:

<img width="1519" alt="Screen Shot 2020-07-20 at 1 46 11 PM" src="https://user-images.githubusercontent.com/9889020/87969064-7200a380-ca8f-11ea-89b9-52419ec16907.png">

and here's the new UI:

<img width="1433" alt="Screen Shot 2020-07-20 at 1 46 54 PM" src="https://user-images.githubusercontent.com/9889020/87969107-8644a080-ca8f-11ea-9893-1784b844e3b7.png">

**Comment by tiagodread** [comment]
PR already merged, verified that the user can navigate successfully to the organization details from inventories list.
