### ISSUE TITLE
Add Groups/Hosts/Sources count to inventory list rows

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7674]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
See mockup:

<img width="1514" alt="Screen Shot 2020-07-20 at 1 52 27 PM" src="https://user-images.githubusercontent.com/9889020/87969522-4e8a2880-ca90-11ea-835b-6a30aadbbfcf.png">

These values come from total_hosts, total_groups, and total_inventory_sources

**Comment by asohh** [comment]
Hey,

I have an idea very close to this. What do you think about adding links to the Groups, Hosts and Sources tabs to the count of it?

**Comment by tiagodread** [comment]
Hey @asohh good idea! would you mind opening a new feature request with your idea and adding more details to it so we can discuss it?

PR already merged, closing this.
