### ISSUE TITLE
Add inventory kind and organization name as default search options on Inventory List

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7675]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
I think both of these would be really useful as defaults.

1) Inventory kind: This would be a boolean where the user could select Inventory or Smart Inventory to trim down the list to only inventories that match that kind.
2) Organization name: If we're going to do https://github.com/ansible/awx/issues/7673 then I think giving users a quick way to search for it would be nice.  The payload would look like `organization__name=WhateverTheSearchIs`

**Comment by mabashian** [comment]
Note that I just added logic to remove smart inventories from the inventory lookup in the hosts form.  For this form in particular we won't want `kind` to be a default search option since we're already filtering by that key.

**Comment by nixocio** [comment]
Already verified.
