### ISSUE TITLE
Clicking inventory sync status icon on Inventory List should navigate the user to filtered Inventory -> Completed Jobs

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7678]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
In the old UI we should show a popover with the recent inventory sync's listed out like so:

<img width="509" alt="Screen Shot 2020-07-20 at 2 41 13 PM" src="https://user-images.githubusercontent.com/9889020/87973808-1508eb80-ca97-11ea-949b-19f11dbfc98c.png">

We already have a view for this though (completed jobs).  We should send the user over to this view when they click on the icon but we should pre-filter the list down to only inventory source sync jobs.  Like so:

<img width="1680" alt="Screen Shot 2020-07-20 at 2 42 31 PM" src="https://user-images.githubusercontent.com/9889020/87973939-48e41100-ca97-11ea-87df-a9e4dad48775.png">

**Comment by mabashian** [comment]
This is going to replace some existing functionality so I think it's important to consider for an initial release.

**Comment by mabashian** [comment]
<img width="1441" alt="Screen Shot 2021-02-10 at 2 13 22 PM" src="https://user-images.githubusercontent.com/9889020/107559495-2b4cd500-6baa-11eb-80ce-c5cf440b1dd1.png">

The inventory list has changed with the move to tables.  The expectation here would be to click on the sync status (when available) and have that direct the user to the filtered jobs list.

**Comment by unlikelyzero** [comment]
@mabashian @wenottingham this would be a great candidate to kick out of 4.0

**Comment by marshmalien** [comment]
Acceptance Criteria
* When an inventory has inventory sources, the sync status label should redirect user to pre-filtered list of inventory sync jobs.

**Comment by akus062381** [comment]
resolved
