### ISSUE TITLE
Support Pending Delete on inventory list rows

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7680]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Since it can take a really long time to delete inventories, the API will actually mark inventories using the `pending_deletion` field to let us know that they are in the process of deleting an inventory.  When we detect a row with this field set to true we should remove all the action icons in favor of some text that says `Pending delete` or `Pending deletion`.  We probably also want to generally disable the row as users won't be able to take any actions on it while it's in this state.

**Comment by mabashian** [comment]
As part of this we may want to investigate updating this modal with a bit more information about pending delete:

<img width="1486" alt="Screen Shot 2020-07-20 at 3 03 30 PM" src="https://user-images.githubusercontent.com/9889020/87975871-31f2ee00-ca9a-11ea-9454-094060c0992a.png">

like we do here:

<img width="877" alt="Screen Shot 2020-07-20 at 3 04 02 PM" src="https://user-images.githubusercontent.com/9889020/87975930-4636eb00-ca9a-11ea-925c-83d685deda8e.png">

**Comment by dsesami** [comment]
Fixed by #8041. Stubbed in inventory-crud.spec
