### ISSUE TITLE
Hide sync icon for smart inventory rows in Inventory List

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7681]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
<img width="1407" alt="Screen Shot 2020-07-20 at 3 05 48 PM" src="https://user-images.githubusercontent.com/9889020/87976119-901fd100-ca9a-11ea-9fd2-976a80a7f55b.png">

Smart inventories don't have sources so this icon is not relevant

**Comment by tiagodread** [comment]
Verified that sync icon is displayed only for inventories
