### ISSUE TITLE
Add smart inventory -> hosts related tab

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7683]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
<img width="1412" alt="Screen Shot 2020-07-20 at 4 52 08 PM" src="https://user-images.githubusercontent.com/9889020/87985316-5efacd00-caa9-11ea-81f8-5cc5ffdf16e2.png">

This list is populated from `/api/v2/inventories/:id/hosts/`.

Like the hosts related tab for regular inventories, this list should have a button that allows users to execute an adhoc command against selected hosts.

**Comment by dsesami** [comment]
This requires two more 
adhoc command button - https://github.com/ansible/awx/issues/6603
detail view - https://github.com/ansible/awx/issues/7806

moving to in_progress as part of that.

**Comment by mabashian** [comment]
#6603 and #7806 have both been completed.  @unlikelyzero should this be closed or go back to needs_test?

**Comment by unlikelyzero** [comment]
covered in smart-inventory-tabs.spec.js
