### ISSUE TITLE
Filtering inventory groups by root/all throws error

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7690]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
![root_groups](https://user-images.githubusercontent.com/9889020/88068108-c82c2000-cb3d-11ea-8fe6-7e2171e0ce89.gif)

<img width="1674" alt="Screen Shot 2020-07-21 at 10 34 59 AM" src="https://user-images.githubusercontent.com/9889020/88068175-db3ef000-cb3d-11ea-860f-8badd6d2b882.png">

**Comment by mabashian** [comment]
@jakemcdermott this still in_progress?

**Comment by mabashian** [comment]
@unlikelyzero I tried to reproduce this behavior in devel but was unable to do so.  It appears as if this has been fixed but I don't know which PR to credit.  Either way, going to move this to needs_test for now.

I did file https://github.com/ansible/awx/issues/8593 while confirming this fix.

**Comment by unlikelyzero** [comment]
covered in inventory-tabs.spec
