### ISSUE TITLE
Inventory groups nested groups list

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7691]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
I _believe_ this list is unimplemented.  I can't find anything in the codebase that would indicate that it's built but misconfigured.

<img width="1678" alt="Screen Shot 2020-07-21 at 10 46 07 AM" src="https://user-images.githubusercontent.com/9889020/88069481-81d7c080-cb3f-11ea-8932-047af9d3e0a9.png">

We may just reuse the groups list but pull the data from `/api/v2/groups/:id/children/` instead of `/api/v2/inventories/:id/groups/`.  This list should also have an add button (like the top level group list) where a user can add a new or existing group.

**Comment by AlexSCorey** [comment]
duplicate. closing in favor of #7691

**Comment by AlexSCorey** [comment]
This is addressed by #8261 and #8262
