### ISSUE TITLE
Support promptable fields on schedules

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7692]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
When creating/editing a schedule for a JT or a WFJT we need to expose fields that are promptable on launch in the form so that the user can specify values for those fields before saving the schedule.  In the old UI we exposed all the promptable fields (except extra variables) through a button beneath the form like so:

![schedule_prompts](https://user-images.githubusercontent.com/9889020/88088499-80ff5880-cb58-11ea-9fc9-6930f27988e8.gif)

~~We could follow the same pattern in ui_next but I've never really loved that pattern and it's a bit of a one-off solution.  I can't think of any other forms where some of the fields are in the form and the rest are in a modal that gets opened after clicking a button.  We did that originally because we could reuse the launch prompt code and get it done pretty quickly.  I feel like these prompts are _part_ of the form and while it _could_ make the form quite long (particularly the survey portion) I'm wondering if these promptable fields should just be included in the form.  This would reduce clicks and potentially make the schedule form much easier to read/understand if all the fields were visible in once place.~~

There's also odd inconsistencies with extra variables where that gets shown in the form and not in the modal.  I just feel like it'd be better if it was all in one form or if we rethought the UX of creating a schedule in general.

@trahman73 @wenottingham I'm open to discussion on this one if you all have strong feelings and/or other ideas.

UI team decided to duplicate the workflow from the old ui.  1 thing to consider, and an areas of improvement, is to figure out a way to let the user know that there is some missing, required, prompt data (ie. inventory). @trahman73

**Comment by mabashian** [comment]
I'm going to mark this as blocked until we nail down the UX

**Comment by unlikelyzero** [comment]
To the future tester: we should audit cypress/integration/job-templates/job-template-prompt-on-launch.spec.js for applicable testcases

**Comment by AlexSCorey** [comment]
after conversation with @trahman73 @mabashian @wenottingham we decided that this issue should utilize a single form that has headers for the Schedule form, and then a sub section for the Promptable fields. Will probably need another sub section to differentiate Surveys from the rest of the Promptable fields.  Mock up to come....

**Comment by AlexSCorey** [comment]
Met with the UI team today to discuss this issue. We decided that for several reasons we will duplicate the workflow on from the old ui.

**Comment by unlikelyzero** [comment]
These may or may not need to split out into this ticket https://github.com/ansible/awx/issues/8692

**Comment by tiagodread** [comment]
@AlexSCorey could you add ouiaID properties for testability before closing this issue? We can sync on it if you want

**Comment by unlikelyzero** [comment]
coverage added
