### ISSUE TITLE
Make date in project sync job status look nice

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7694]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Here's what it looks like:

<img width="615" alt="Screen Shot 2020-07-21 at 2 53 36 PM" src="https://user-images.githubusercontent.com/9889020/88094776-1b17ce80-cb62-11ea-8823-59af2e1635c9.png">

Here's what the corresponding date looks like on a job on the templates list:

<img width="698" alt="Screen Shot 2020-07-21 at 2 53 45 PM" src="https://user-images.githubusercontent.com/9889020/88094807-27039080-cb62-11ea-9e62-b2da856427a8.png">

**Comment by dsesami** [comment]
Project status locale has been updated properly :+1:
