### ISSUE TITLE
Cannot edit credential secret fields in UI

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#770]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Can not edit secret fields for credentials, like password.

Creating new credentials is not a problem.

##### ENVIRONMENT
* AWX version: 1.0.1
* AWX install method: docker for mac
* Ansible version:  N/A
* Operating System: Mac
* Web Browser: both Firefox and Chrome

##### STEPS TO REPRODUCE

Create a machine credential with a username and password.

Navigate back to that credential and attempt to edit password.

##### EXPECTED RESULTS

password edited.

##### ACTUAL RESULTS

Cannot edit password, here I am clicking:

![password_edit](https://user-images.githubusercontent.com/1385596/33613147-d6deb814-d9a1-11e7-8501-fd9efcb311dd.gif)

##### ADDITIONAL INFORMATION

No information in JS logs.

**Comment by mabashian** [comment]
I believe that the function being called when _REPLACE_ is being clicked is defined here:

https://github.com/ansible/awx/blob/devel/awx/ui/client/lib/components/input/secret.directive.js#L34

As best as I can tell `toggleRevertReplace` is not defined anywhere so nothing is happening.  That's consistent with the report of no errors in the console.  I'll have to look and see if this logic was removed or if it just wasn't ever implemented.

**Comment by jakemcdermott** [comment]
should be resolved by https://github.com/ansible/awx/pull/771
