### ISSUE TITLE
Add shortcut to create smart inventory from /#/hosts list

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7700]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
In the old UI we had this button on the Hosts list that would let users create a smart inventory using the current search filter items:

<img width="1535" alt="Screen Shot 2020-07-21 at 5 21 39 PM" src="https://user-images.githubusercontent.com/9889020/88108396-c0d53880-cb76-11ea-8579-bdf0e2b97b1c.png">
<img width="1532" alt="Screen Shot 2020-07-21 at 5 22 05 PM" src="https://user-images.githubusercontent.com/9889020/88108397-c16dcf00-cb76-11ea-8060-b69a5f36edd3.png">

All it would do is pass the search params though to the form and then pre-populate that field.  I think we should do something similar in ui_next.  The button is only clickable when the user has specified at least one search term so the button could be shown only after a search is executed _or_ we could always show it and just disable it when there are no searches.

**Comment by tiagodread** [comment]
Tests covered by ansible/tower-qa#5867
