### ISSUE TITLE
"Type" sort is extraneous in schedule tab for resources

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#7706]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The default sort in the UI for schedules is "Type". For example, with Job Templates, the type is "Playbook Run". This sort makes sense for the main schedules view, `/schedules`, but doesn't make sense at all when dealing with tabs like Job Template > Schedules. It's the default sort in that view, but doesn't do anything because all items in these sub-tabs are the same type.

This issue is satisfied by removing "Type" from the sort choices for the Project > schedule, Job template > schedule, etc. views (there are more, this is not an exhaustive list). The default sort should also be set to "Name", or something else if there is a more intuitive sort for that list.

**Comment by mabashian** [comment]
We should just make the default whatever it is in the old UI so long as it's not `type`

**Comment by unlikelyzero** [comment]
Verified in 5659
