### ISSUE TITLE
docker-compose install, missing value in docker-compose template for redis launch command

### ISSUE THREAD

**Issue by KelvinPriceDSL** [ansible/awx#7710]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
awx_redis container won't launch because launch command in docker-compose file is wrong

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker

##### STEPS TO REPRODUCE

run install with docker-compose options

##### EXPECTED RESULTS

awx_redis container launches successfully

##### ACTUAL RESULTS

awx_redis container goes in to restart loop because of failure

##### ADDITIONAL INFORMATION

the docker-compose template file (awx/installer/roles/local_docker/templates/docker-compose.yml.j2) has on line 141:

    command: ["/usr/local/etc/redis/redis.conf"]

it should have:

    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

**Comment by ryanpetrello** [comment]
@KelvinPriceDSL,

At first glance, this does look wrong to me, however following the installation instructions for AWX, I'm not seeing the restart loop you're describing.

What command are you running, and what error are you seeing?

**Comment by shanemcd** [comment]
The code for the Redis container suggests this is fine: https://github.com/docker-library/redis/blob/bfd904a808cf68d4b5ecc267bb4d4a1a0ca5f921/6.0/docker-entrypoint.sh#L4-L8

Echoing what @ryanpetrello said above. What is the actual error you are seeing?

**Comment by KelvinPriceDSL** [comment]
What I saw was that after launching with docker-compose, the awx_redis container kept failing and restarting in a loop and never actually came up and stayed up.

Running `docker logs awx_redis` showed that it had errors accessing /usr/local/etc/redis/redis.conf, from what I could tell the file was there but was not executable and the contents were not a valid script anyway.  It didn't make sense to me anyway that the launch command was just the name of a configuration file.

Googling for redis and docker compose information, I found an example that had ["redis-server", "/usr/local/etc/redis/redis.conf"] for the command so I edited the docker-compose.yml produced by the install accordingly and ran `docker-compose down`, `docker-compose up -d --force-recreate` and all the awx containers launched correctly.  This made sense to me as it now had both a command to run and a parameter to that command.

**Comment by KelvinPriceDSL** [comment]
> The code for the Redis container suggests this is fine: https://github.com/docker-library/redis/blob/bfd904a808cf68d4b5ecc267bb4d4a1a0ca5f921/6.0/docker-entrypoint.sh#L4-L8
> 
> Echoing what @ryanpetrello said above. What is the actual error you are seeing?

That script refers to $1, my understanding of docker may be incorrect here, but to me ["filename"] would make filename $0 and $1 would be empty, but ["command", "filename"] would make command $0 and filename $1.

**Comment by ryanpetrello** [comment]
@KelvinPriceDSL are you _manually_ running `docker-compose` pointed at AWX's compose config?  That's not generally how you install AWX in a local Docker environment.

Please have a look over these instructions (which I've confirmed do work):

https://github.com/ansible/awx/blob/devel/INSTALL.md#docker-compose

**Comment by KelvinPriceDSL** [comment]
> @KelvinPriceDSL are you _manually_ running `docker-compose` pointed at AWX's compose config? That's not generally how you install AWX in a local Docker environment.
> 

I manually ran docker-compose _after_ editing the docker-compose.yml file _after_ the install failed to launch.

**Comment by ryanpetrello** [comment]
@KelvinPriceDSL for what it's worth, I was able to reproduce this on a recent new install I did, and I found that the issue only occurred with SELinux enabled.

**Comment by shanemcd** [comment]
To expand upon this a bit, it seems like this is an SELinux issue when running moby-engine. Until that package is fixed, installing docker-ce from the Fedora 31 repos works.

**Comment by KelvinPriceDSL** [comment]
> @KelvinPriceDSL for what it's worth, I was able to reproduce this on a recent new install I did, and I found that the issue only occurred with SELinux enabled.

Yeh, selinux was enabled on my test build machine and `semanage fcontext -a -t svirt_sandbox_file_t  $compose_dir` followed by a `restorecon -R` was being run against the parent dir of the awxcompose dir for another app also using docker-compose.  Turns out the "redis-server" isn't needed and I could have just re-launched awx and it would have been fine.

Perhaps a better fix would be adjusting the docker-compose.yml to mount the redis.conf and redis.socket "volumes" with :Z instead of :ro or :rw , maybe mount them one of the 2 ways depending on a flag indicating whether selinux is enabled on the target machine or not
