### ISSUE TITLE
Gitops for Job Specs and Workflows

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [ansible/awx#7711]
##### ISSUE TYPE
 - Feature Idea

* Idea came watching excellent talk https://www.youtube.com/watch?v=87Tag9wyfs8

* basically, at the end of the talk, one auditor points out that the Job Spec in Ansible tower / AWX, is not done using git operations.
* I think there is also the workflows features (orchestration of Jobs) that falls in the scope of the idea I come up with (workflows operated trough git as well)
* I think I know how it should be implemented : 
  * The Job Template, and also Ansible Tower Workflows, should be on a by-repo basis configurable, 
  * using a `ansible-tower.yaml`, or `awx.yaml`  versioned with the source code
  * just like like there are `drone.yml` `gitlab-ci.yml` `circle-ci.yml` `travis-ci.yml` `atlantis.yaml` etc....

##### SUMMARY

Make JobSpecs and Workflows CRUD Operations possible through gitops

**Comment by AlanCoding** [comment]
Does that come down to #526? My current reading is that this is probably a duplicate, but I would like if you could comment with your thoughts on implementation there.

**Comment by ryanpetrello** [comment]
@AlanCoding I agree, I think this issue is close enough in spirit to the problem described in #526 that I'm willing to call it a duplicate cc @chrismeyersfsu @wenottingham

**Comment by wenottingham** [comment]
Closing as duplicate.

**Comment by Jean-Baptiste-Lasselle** [comment]
hi @AlanCoding @ryanpetrello totally a duplicate, absolutely (just read #526 ) : never the less, I think it should be extended to Ansible Tower / AWX workflows
