### ISSUE TITLE
AWX not use vmware_vm_inventory.py (and no tags from vCenter)

### ISSUE THREAD

**Issue by bvivi57** [ansible/awx#7715]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
- vCenter Inventory

##### SUMMARY
Despite the use of a "virtualenv" with the necessary dependencies (VMware vSphere Automation), I don't have any tags associated to my VMs that go up in my AWX inventory.

##### ENVIRONMENT
* AWX version: AWX 13.0.0
* AWX install method: Kubernetes
* Ansible version:  2.9.10
* Operating System: Ubuntu 20.04
* Web Browser: Firefox 78.0.2
* vCenter : 6.7.16243230 

##### STEPS TO REPRODUCE

1) Deploy AWX on Kubernetes

2 ) Create virtualenv with vmware sdk 
- https://docs.ansible.com/ansible-tower/3.4.5/html/upgrade-migration-guide/virtualenv.html
- https://github.com/vmware/vsphere-automation-sdk-python
(create virtualenv on task and web container)

3) Select your virtualenv for your source inventory for vmware (and use values "use tags: true on source variable) and lauch inventory

##### EXPECTED RESULTS
tag value for each VM on Variables Details in Inventory 

##### ACTUAL RESULTS
no tag

##### ADDITIONAL INFORMATION
I tried to force the "true" parameter for the tags directly in the plugin code in the containers 
(/usr/lib/python3.6/site-packages/ansible/plugins/inventory/vmware_vm_inventory.py)

If I delete the plugin file from the containers, I get no error. I just have the impression that AWX doesn't use this plugin and continues to use a simple scripting inventory method (which I thought was not recommended anymore).

https://docs.ansible.com/ansible-tower/latest/html/userguide/inventories.html#inventory-plugins

**Comment by wenottingham** [comment]
Arbitrary source variables are not currently put into the plugin configuration, that is why you're seeing it not be honored.

**Comment by bvivi57** [comment]
Thanks for your help.

Why modifying the plugin directly in the containers has no impact, or even deleting it. Does it exist elsewhere in the tree ?

**Comment by wenottingham** [comment]
The file in plugins/inventory you deleted was the old script that is included for Ansible 2.8 compatibility.

**Comment by jsalatiel** [comment]
Is there currently any way to group by tags since we can not use with_tags: True ?

**Comment by cardinal83** [comment]
Here https://github.com/ansible-collections/vmware/issues/160#issuecomment-627041751 is possible solution, but not works for me on AWX 14.0.0.
Anyone this solution works?

**Comment by mvebe** [comment]
You can manually adjust this with:

vi /var/lib/awx/vendor/awx_ansible_collections/ansible_collections/community/vmware/plugins/inventory/vmware_vm_inventory.py
    289         self.with_tags = True #with_tags
which i've just tested as working.

Also,

in AWX GUI -> source vmware vsphere -> question mark at source variables:
Override variables found in vmware.ini and used by the inventory update script. For a detailed description of these variables view vmware_inventory.ini in the vmware community repo.

This is incorrect vmware_inventory.ini is for another plugin which is deprecated.

**Comment by kdelee** [comment]
@wenottinghamth sounds like this is a WONTFIX. Nothing to test, going to close.
