### ISSUE TITLE
 Add running parameters to the template job

### ISSUE THREAD

**Issue by Leif160519** [ansible/awx#7716]
##### ISSUE TYPE
 - Add running parameters to the template job, just like the parameters added when running ansible-playbook on the command line

##### SUMMARY
I want to add running parameters to the template job, such as --list-hosts. This function is useful before pre-execution. I hope to add this function, or if awx already has this function, what should I do? Thanks!

**Comment by Leif160519** [comment]
I searched the official documents, but did not find similar steps. I hope someone can give me an idea, thank you!

**Comment by wenottingham** [comment]
In AWX, a job is a single playbook run in isolation; we have no plans to add pre/post steps. See https://github.com/ansible/awx/issues/7535 for more details.

Can you describe more why you'd need this?

**Comment by Leif160519** [comment]
> In AWX, a job is a single playbook run in isolation; we have no plans to add pre/post steps. See #7535 for more details.
> 
> Can you describe more why you'd need this?


I just want to confirm the machines that take effect after the script is executed to prevent mistakes, because there are hundreds of machines to prevent mistakes

**Comment by wenottingham** [comment]
That's not something we'd add in that way.

You can use an approval node in a workflow to implement this if you are concerned with how the playbook host pattern may match inventory.
