### ISSUE TITLE
awx 13.0.0 not accessible if set to use ssl and serve on 80 and 443

### ISSUE THREAD

**Issue by awright424** [ansible/awx#7718]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.11
* Operating System: ubuntu 18.04
* Web Browser: chrome latest

##### STEPS TO REPRODUCE

installed awx using docker. set it to use both ports 80 and 443 and supplied goddady .crt file for the ssl with no key.

##### EXPECTED RESULTS

I see awx listening on 80 and 443

##### ACTUAL RESULTS

I am unable to access awx through port 80 or 443.

##### ADDITIONAL INFORMATION

changing it to only 443 does not work as well. I changed it to only port 80 and that was fine. I did this in azure and made sure ports where open to the instance as well.

**Comment by shanemcd** [comment]
Hi @awright424,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
