### ISSUE TITLE
Unable to authenticate via AD/LDAP

### ISSUE THREAD

**Issue by reecewebb** [ansible/awx#772]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Fresh install of AWX, login via AD/LDAP authentication isn't working. There aren't any issues that I can see, I do see an LDAPError warning while tailing the awx_web log. I'm banging my head against the wall so hoping there's something obvious that I'm missing.

##### ENVIRONMENT
* AWX version: 1.0.1.272
* AWX install method: docker on linux
* Ansible version: 2.4.2.0
* Operating System: RHEL 7.4
* Web Browser: Chrome 64, Firefox 59

##### STEPS TO REPRODUCE
Configure AD/LDAP authentication, attempt to login.

##### EXPECTED RESULTS
Login via AD/LDAP should work.

##### ACTUAL RESULTS
# docker logs -f awx_web
...
2017-12-05 18:25:38,316 DEBUG    django_auth_ldap search_s('OU=Users,OU=RAD,OU=Customers,OU=ITFS,DC=campus,DC=net,DC=ucsf,DC=edu', 2, '(sAMAccountName=%(user)s)') returned 1 objects: cn=webb\, reece,ou=users,ou=rad,ou=customers,ou=itfs,dc=campus,dc=net,dc=ucsf,dc=edu
2017-12-05 18:25:38,334 WARNING  django_auth_ldap Caught LDAPError while authenticating rewebb: REFERRAL({'info': 'Referral:\nldap://campus/cn=rad%20ansible%20users,ou=groups,ou=department,ou=radiology,dc=campus', 'desc': 'Referral'},)
2017-12-05 18:25:38,379 WARNING  awx.api.views Login failed for user rewebb
2017-12-05 18:25:38,380 WARNING  awx.api.generics status 400 received by user AnonymousUser attempting to access /api/v2/authtoken/ from 192.168.65.248
[pid: 27|app: 0|req: 33/148] 192.168.65.248 () {54 vars in 1154 bytes} [Tue Dec  5 18:25:38 2017] POST /api/v2/authtoken/ => generated 58 bytes in 173 msecs (HTTP/1.1 400) 9 headers in 311 bytes (1 switches on core 0)
192.168.65.248 - - [05/Dec/2017:18:25:38 +0000] "POST /api/v2/authtoken/ HTTP/1.1" 400 58 "http://bunker.radiology.ucsf.edu:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3278.0 Safari/537.36" "-"

##### ADDITIONAL INFORMATION
{
    "AUTH_LDAP_SERVER_URI": "ldaps://<fqdn>:636",
    "AUTH_LDAP_BIND_DN": "<bind_dn>",
    "AUTH_LDAP_BIND_PASSWORD": "$encrypted$",
    "AUTH_LDAP_START_TLS": false,
    "AUTH_LDAP_CONNECTION_OPTIONS": {
        "OPT_X_TLS_REQUIRE_CERT": 0,
        "OPT_NETWORK_TIMEOUT": 30,
        "OPT_REFERRALS": 0
    },
    "AUTH_LDAP_USER_SEARCH": [
        "OU=<user_ou>",
        "SCOPE_SUBTREE",
        "(sAMAccountName=%(user)s)"
    ],
    "AUTH_LDAP_USER_DN_TEMPLATE": null,
    "AUTH_LDAP_USER_ATTR_MAP": {
        "first_name": "givenName",
        "last_name": "sn",
        "email": "mail"
    },
    "AUTH_LDAP_GROUP_SEARCH": [
        "OU=<group_ou>",
        "SCOPE_SUBTREE",
        "(objectClass=group)"
    ],
    "AUTH_LDAP_GROUP_TYPE": "ActiveDirectoryGroupType",
    "AUTH_LDAP_REQUIRE_GROUP": "CN=<required_group>",
    "AUTH_LDAP_DENY_GROUP": null,
    "AUTH_LDAP_USER_FLAGS_BY_GROUP": {},
    "AUTH_LDAP_ORGANIZATION_MAP": {
        "<org>": {
            "users": [
                "CN=<user_group>"
            ],
            "admins": "CN=<admin_group>",
            "remove_admins": false,
            "remove_users": false
        }
    },
    "AUTH_LDAP_TEAM_MAP": {
        "<team>": {
            "organization": "<org>",
            "users": "CN=<user_group>",
            "remove": true
        },
    }
}

**Comment by MogiePete** [comment]
Use the settings listed by @dandandanp here: [Configuring AWX to connect to Active Directory](https://github.com/ansible/awx/issues/496) for configuring LDAP Sync to Active Directory. His settings worked for me.

Also, to trust our internal LDAPS server I had to import our Root CA Chain into aws_web for LDAPS to work properly.

**Comment by reecewebb** [comment]
Thanks, I actually did try those settings during my testing, same result. Also, I have "OPT_X_TLS_REQUIRE_CERT=0", which I believe disables cert validation?

**Comment by reecewebb** [comment]
Doh, there was an unrelated change made by one of our AD admins, I have this working now.

**Comment by mandeepmanj** [comment]
2018-02-14 23:25:14,884 WARNING  awx.api.views Login failed for user msmanj
2018-02-14 23:25:14,885 WARNING  awx.api.generics status 400 received by user AnonymousUser attempting to access /api/v2/authtoken/ from 172.29.230.242
[pid: 54|app: 0|req: 501/2089] 172.29.230.242 () {48 vars in 861 bytes} [Wed Feb 14 23:25:14 2018] POST /api/v2/authtoken/ => generated 58 bytes in 265 msecs (HTTP/1.1 400) 10 headers in 337 bytes (1 switches on core 0)

**Comment by smnmtzgr** [comment]
@MogiePete How have you imported your Root CA Chain into awx_web?

**Comment by MogiePete** [comment]
@smnmtzgr 
We build our imagine locally and modified the awx_web dockerfile to add the root_ca.pem file and import it using the code below.

`#Install Root CA for LDAP
ADD Root_CA.pem /etc/pki/ca-trust/source/anchors/Root_CA.pem
RUN update-ca-trust enable && \
    update-ca-trust extract
`

**Comment by MogiePete** [comment]
@smnmtzgr
We build our imagine locally and modified the awx_web dockerfile to add the root_ca.pem file and import it using the code below.

#Install Root CA for LDAP
ADD Root_CA.pem /etc/pki/ca-trust/source/anchors/Root_CA.pem 
RUN update-ca-trust enable && \ 
update-ca-trust extract
