### ISSUE TITLE
Update AddDropDownButton to show down caret

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#7721]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
From feedback from @trahman73.

> Add a down caret to the Add button to show users that there will be additional choices.

Example:

<img width="935" alt="Screen Shot 2020-07-24 at 11 12 56 AM" src="https://user-images.githubusercontent.com/9053044/88408490-a03cf680-cda1-11ea-94bf-a0abad01445e.png">

**Comment by tiagodread** [comment]
Tests in place PR already merged
