### ISSUE TITLE
hostvars is undefined with delegate_to

### ISSUE THREAD

**Issue by arndttob** [ansible/awx#7725]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When using delegate_to within a task, any variable of the remote system seem to be undefined.
The same issue is documented in the git repo for ansible (https://github.com/ansible/ansible/issues/70334). 

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.10
* Operating System: Debian 10 (Buster)
* Web Browser: Chromium

##### STEPS TO REPRODUCE
Create a playbook with the following task:  
  
    -  
      name: Remove Fingerprint from known_hosts-file  
      command: sed -i '/'{{ ansible_host }}'/d' /root/.ssh/known_hosts  
      delegate_to: localhost  

##### EXPECTED RESULTS

All lines related to the hostname should be removed from the '/root/.ssh/known_hosts'-File located on localhost.

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/6782989/88522076-23ef2100-cff6-11ea-8b79-252326fc68c4.png)

##### ADDITIONAL INFORMATION

The hostlist is generated dynamically during execution of the playbook with add_hosts.

**Comment by arndttob** [comment]
I also tested it with AWX Version 11.2.0. Here, it works as expected.

**Comment by wenottingham** [comment]
This is an ansible bug, it should be tracked in the issue you referenced.
