### ISSUE TITLE
Add title under breadcrumb

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7727]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
<img width="1460" alt="Screen Shot 2020-07-27 at 1 11 29 PM" src="https://user-images.githubusercontent.com/9889020/88570850-c5806d80-d00a-11ea-8960-15e0861248f8.png">

We used to have something like this supported in the breadcrumb component but I think that support was dropped.  If we want to do something like this now we'll have to add it ourselves.

Will be important to work with @trahman73 to determine when/where to add this.

**Comment by mabashian** [comment]
We're now simply following the PF pattern for breadcrumbs.  Closing

**Comment by unlikelyzero** [comment]
https://github.com/ansible/awx/pull/9083#issuecomment-765005073
