### ISSUE TITLE
Being able to do a "pause" during a running job in tower

### ISSUE THREAD

**Issue by dapiced** [ansible/awx#7734]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 
 - UI
 

##### SUMMARY

Sometime we need to use tower-cli to cleanup inventory, but if jobs is runnings, the inventory is block for tower-cli

Being able to do a "pause" during a running job in tower, like a PAUSE BUTTON

##### ENVIRONMENT
* AWX version: 3.6.3
* AWX install method: on prem. 
* Ansible version:  2.9.5
* Operating System: redhat 7
* Web Browser: chrome

##### STEPS TO REPRODUCE

Being able to do a "pause" during a running job in tower, like a PAUSE BUTTON

**Comment by wenottingham** [comment]
We have no plans to add this. For a pause step, add a approval node in a workflow; that can pause until approved, or until timeout.
