### ISSUE TITLE
Installer: "when: kubernetes_awx_image is not defined" will never match, due to defaults

### ISSUE THREAD

**Issue by philipsd6** [ansible/awx#7735]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
`kubernetes_awx_image:` is set in `installer/roles/kubernetes/tasks/main.yml` *only* when `kubernetes_awx_image` is not defined. However, `kubernetes_awx_image` is hardcoded in `installer/roles/kubernetes/defaults/main.yml` as `ansible/awx`, so this test will never set the variable otherwise:

    $ rg -B4 -A1  kubernetes_awx_image installer/roles/kubernetes/tasks/
    installer/roles/kubernetes/tasks/main.yml
    191-- name: Set image names if using custom registry
    192-  block:
    193-    - name: Set awx image name
    194-      set_fact:
    195:        kubernetes_awx_image: "{{ docker_registry }}/{{ docker_registry_repository }}/{{ awx_image }}"
    196:      when: kubernetes_awx_image is not defined
    197-  when: docker_registry is defined
    $ rg kubernetes_awx_image installer/roles/kubernetes/defaults/
    installer/roles/kubernetes/defaults/main.yml
    12:kubernetes_awx_image: "ansible/awx"

I ran into this problem because I was using `docker_registry_repository` to point to a different repository than `ansible` in my private registry, defined with `docker_registry`

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: openshift
* Ansible version:  2.11.0.dev0
* Operating System: Ubuntu 20.04 LTS
* Web Browser: Firefox, not that it matters.

##### STEPS TO REPRODUCE

1. Define `docker_registry` as `example.com:5000` in your inventory vars
2. Define `docker_registry_repository` as `localrepo` in your inventory vars
3. Run the OpenShift installation and note that the deployment is trying to pull `ansible/awx` **not** `example.com:5000/localrepo/awx`

##### EXPECTED RESULTS
I expect my built image that was pushed to my private registry is used when I specify `docker_registry` and `docker_registry_repository`

##### ACTUAL RESULTS
The deployment in OpenShift is actually trying to pull `ansible/awx`, but since it doesn't have access to Dockerhub, it times out.

**Comment by shanemcd** [comment]
The code referenced here no longer exists. The current installation steps are documented at https://github.com/ansible/awx/blob/devel/INSTALL.md.
