### ISSUE TITLE
Change the icon used to log out of the web UI

### ISSUE THREAD

**Issue by mrmibrown** [ansible/awx#7737]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Quote from the user:
"web interface uses power icon for logging out"

Description
"The web interface should not use the power icon for logging out.  
1.  It's the wrong icon, which leads to user confusion 
2.  It will train users to think the power icon always represents logging out, which could lead to inadvertent shutdowns.  

Replace it with a standard Exit icon."

**Comment by ryanpetrello** [comment]
The new UI based on patternfly doesn't use this icon anymore:

![image](https://user-images.githubusercontent.com/214912/88692801-7d298400-d0cc-11ea-855b-ad6eff7e7019.png)

**Comment by jakemcdermott** [comment]
Yep. resolved in the new ui. Sit tight.
