### ISSUE TITLE
Pass 2 of making options requests to get possible keys for advanced search

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#7740]
There are a handful of screens that don't have anything populated in the options for the key typeahead, as they don’t use the useRequest hook yet. In terms of work, I think it makes sense that they should be converted first so that they can grab the options request to get possible advanced keys.

- UserList.jsx - https://github.com/ansible/awx/pull/7743
- WFJTList - https://github.com/ansible/awx/pull/7745
- (Templates) ProjectsList.jsx - https://github.com/ansible/awx/pull/7752
- JTList - https://github.com/ansible/awx/pull/7754
- InventorySourcesList.jsx - https://github.com/ansible/awx/pull/7755
- ProjectJobTemplatesList.jsx - https://github.com/ansible/awx/pull/7759
- OrganizationTeamList.jsx - https://github.com/ansible/awx/pull/7761
- InventoryGroupsList.jsx - https://github.com/ansible/awx/pull/7765
- ResourceAccessList.jsx - https://github.com/ansible/awx/pull/7772
- AddResourceRole lists
- UserAndTeamAccessAdd /SelectResourceStep lists*
- AssociateModal lists*
- NotificationList.jsx - https://github.com/ansible/awx/pull/7785
- OrganizationLookup - https://github.com/ansible/awx/pull/7786

*these actually need to be passed an additional options request from the places they are called, they have useRequest in use right now, so bit of a different conversion

**Comment by mabashian** [comment]
I'm gonna slowly chip away at this list - if anyone else is interested in grabbing some of these just let me know so that we don't duplicate efforts.

I'll probably do each component in a separate PR

**Comment by mabashian** [comment]
I think these:

```
AddResourceRole lists
UserAndTeamAccessAdd /SelectResourceStep lists*
AssociateModal lists*
```

will be a bit easier to address once #7739 merges since we'll be able to add the options request and hook up advanced search at the same time.

So I'm gonna throw this back into needs_devel for that work

**Comment by jlmitch5** [comment]
DONE: As part of the follow up to this, we want to slightly tweak the logic of the options calls to get search keys in all the existing places

![Screen Shot 2020-08-05 at 1 49 15 PM](https://user-images.githubusercontent.com/1342624/89447125-7aa9d880-d723-11ea-91d2-f4be8dee200d.png)

**Comment by jlmitch5** [comment]
DONE: Another issue we want to fix is grabbing the UJT (not JT options) for the template list (as it was returning keys that were causing invalid searches)

**Comment by unlikelyzero** [comment]
@jlmitch5 @mabashian putting this into needs_test since all of the associate PRs have merged

**Comment by unlikelyzero** [comment]
The Credentials Advanced Search is missing Keys

**Comment by unlikelyzero** [comment]
@mabashian putting back into devel based on https://github.com/ansible/awx/issues/7740#issuecomment-729036891

**Comment by mabashian** [comment]
@unlikelyzero it looks like the credentials list advanced search has keys now:

<img width="1677" alt="Screen Shot 2021-02-17 at 11 06 15 AM" src="https://user-images.githubusercontent.com/9889020/108231888-38207a00-7110-11eb-84b6-f3f470d27b98.png">

I checked the credential lookup as well:

<img width="1195" alt="Screen Shot 2021-02-17 at 11 07 20 AM" src="https://user-images.githubusercontent.com/9889020/108231996-52f2ee80-7110-11eb-8995-29ee1503f7cf.png">

**Comment by unlikelyzero** [comment]
@akus062381 please verify this case with a few stubs on this Select Credential Modal
- Can search for Machine credentials by 'Name'
- Can search for Custom Credenials by 'ID'
- Can search for Non-tower-managed keys with an explicit query

**Comment by akus062381** [comment]
All set. Closing this issue.
