### ISSUE TITLE
Update advanced search key options to be grouped

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#7741]
https://github.com/patternfly/patternfly-react/pull/4622 -- blocked until this PR merges and we update to get that code

Currently, there are two sets of keys displayed in the options for this typeahead--the direct keys of the resource, and the related search fields. Since there is currently a bug with PF support of select groups with typeaheads, I have to concat and dedup these two list of options together.

Related to this work, the related search fields are special in that when no prefix or lookup is specified, we want to allow the user to access the fuzzy search for these related resources, so I append the __search lookup when that is the case. Because there are some cases where a related key is both a direct key (usually the id of which resource it is connected to), as well as a related search key with which you can search the fields of that resource, I do not do the __search appending if it is in both sets of options.

So the work involved here is:
- stop concat/deduping the list into allKeys https://github.com/ansible/awx/pull/7739/files#diff-c0fc4cf1aeb8368f537c5f44b71be4d7R35 and update the key options to be grouped.
- update the handleAdvancedSearch function to be aware of which group the key came from, so that we can do the __search lookup add if it was selected from the related group https://github.com/ansible/awx/pull/7739/files#diff-c0fc4cf1aeb8368f537c5f44b71be4d7R54

**Comment by unlikelyzero** [comment]
@jlmitch5 @mabashian @wenottingham removing state:blocked as the upstream pf PR component has merged

**Comment by tiagodread** [comment]
This was addressed by #11208
