### ISSUE TITLE
Add instance group

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#7744]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add instance group.

**Comment by mabashian** [comment]
@nixocio I see that #7776 has merged, does that mean we can close this issue?

**Comment by nixocio** [comment]
@unlikelyzero, I am re-opening this one. Based on your feedback.

**Comment by dsesami** [comment]
I'll close this out with the addition of some stubs and automation, which are incoming.
edit: automation was already added in instance-group-crud.spec, so closing.
