### ISSUE TITLE
Create the Settings skeleton 

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#7746]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Mockup: https://tower-mockups.testing.ansible.com/patternfly/settings/settings/

**Tasks**
* Create a responsive settings navigation landing page
* Configure breadcrumbs
* Stub out route files
* Each link should navigate to a detail view
* Each detail view should have an edit button that navigates to an edit view
* Each edit view should have a cancel button that navigates to the detail view

**Not in Scope**
* The form or detail content

**Comment by mabashian** [comment]
@marshmalien I see that #7747 has merged, does that mean we can close this issue?

**Comment by dsesami** [comment]
This looks really good. :+1:
