### ISSUE TITLE
Callback is not working since upgrading from AWX version 10 to 13

### ISSUE THREAD

**Issue by wbieniek** [ansible/awx#7749]
##### ISSUE TYPE
Callback is not working after upgrading to AWX 13 from AWX 10. 

##### SUMMARY
[root@cilsdbxd55343 ~]# curl -k  --data 'host_config_key=0cf80425-45d8-4e24-9e70-2b3072aa9e9e' https://cpc-awx-stage.apps.gp-1-nonprod.openshift.cignacloud.com:443/api/v2/job_templates/9/callback/ -vvv
* About to connect() to cpc-awx-stage.apps.gp-1-nonprod.openshift.cignacloud.com port 443 (#0)
*   Trying 10.25.130.104...
* Connected to cpc-awx-stage.apps.gp-1-nonprod.openshift.cignacloud.com (10.25.130.104) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=cpc-awx-stage.apps.gp-1-nonprod.openshift.cignacloud.com,OU=SSL,O=Cigna Test,C=US
* 	start date: Jun 12 13:17:33 2020 GMT
* 	expire date: Sep 10 13:17:33 2020 GMT
* 	common name: cpc-awx-stage.apps.gp-1-nonprod.openshift.cignacloud.com
* 	issuer: CN=CignaB1IssusingCA01,DC=silver,DC=com
> POST /api/v2/job_templates/9/callback/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: cpc-awx-stage.apps.gp-1-nonprod.openshift.cignacloud.com
> Accept: */*
> X-Forwarded-For: 10.25.249.96
> Content-Length: 52
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 52 out of 52 bytes
< HTTP/1.1 400 Bad Request
< server: nginx
< date: Wed, 29 Jul 2020 11:56:36 GMT
< content-type: application/json
< content-length: 42
< vary: Accept, Accept-Language, Origin, Cookie
< allow: GET, POST, HEAD, OPTIONS
< x-api-product-version: 12.0.0
< x-api-product-name: AWX
< x-api-node: awx-7c4656c5c5-q7stf
< x-api-time: 0.260s
< content-language: en
< x-api-total-time: 0.342s
< set-cookie: 8f2df32fd9818809b01f93c091d343d6=04b05526fc16ac7ab50534e0b3b3c3a3; path=/; HttpOnly; Secure
<
* Connection #0 to host cpc-awx-stage.apps.gp-1-nonprod.openshift.cignacloud.com left intact
{"msg":"No matching host could be found!"}

[root@cilsdbxd55343 ~]# curl -k -H 'X-Forwarded-For: 10.25.249.96' --data 'host_config_key=0cf80425-45d8-4e24-9e70-2b3072aa9e9e' https://cpc-awx-stage.apps.gp-1-nonprod.openshift.cignacloud.com:443/api/v2/job_templates/9/callback/ -vvv
* About to connect() to cpc-awx-stage.apps.gp-1-nonprod.openshift.cignacloud.com port 443 (#0)
*   Trying 10.25.130.104...
* Connected to cpc-awx-stage.apps.gp-1-nonprod.openshift.cignacloud.com (10.25.130.104) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=cpc-awx-stage.apps.gp-1-nonprod.openshift.cignacloud.com,OU=SSL,O=Cigna Test,C=US
* 	start date: Jun 12 13:17:33 2020 GMT
* 	expire date: Sep 10 13:17:33 2020 GMT
* 	common name: cpc-awx-stage.apps.gp-1-nonprod.openshift.cignacloud.com
* 	issuer: CN=CignaB1IssusingCA01,DC=silver,DC=com
> POST /api/v2/job_templates/9/callback/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: cpc-awx-stage.apps.gp-1-nonprod.openshift.cignacloud.com
> Accept: */*
> X-Forwarded-For: 10.25.249.96
> Content-Length: 52
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 52 out of 52 bytes
< HTTP/1.1 400 Bad Request
< server: nginx
< date: Wed, 29 Jul 2020 12:44:47 GMT
< content-type: application/json
< content-length: 42
< vary: Accept, Accept-Language, Origin, Cookie
< allow: GET, POST, HEAD, OPTIONS
< x-api-product-version: 12.0.0
< x-api-product-name: AWX
< x-api-node: awx-7c4656c5c5-q7stf
< x-api-time: 0.246s
< content-language: en
< x-api-total-time: 0.398s
< set-cookie: 8f2df32fd9818809b01f93c091d343d6=04b05526fc16ac7ab50534e0b3b3c3a3; path=/; HttpOnly; Secure
<
* Connection #0 to host cpc-awx-stage.apps.gp-1-nonprod.openshift.cignacloud.com left intact
{"msg":"No matching host could be found!"}[root@cilsdbxd55343 ~]#

2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:16:3e:5d:c7:a2 brd ff:ff:ff:ff:ff:ff
    inet 10.25.249.96/20 brd 10.25.255.255 scope global dynamic eth0
       valid_lft 82974sec preferred_lft 82974sec
    inet6 fe80::f816:3eff:fe5d:c7a2/64 scope link
       valid_lft forever preferred_lft forever
[root@cilsdbxd55343 ~]#

Yes, hosts is part of inventory

##### ENVIRONMENT
* AWX version: 13
* AWX install method: openshift
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### ACTUAL RESULTS

2020-07-29 11:59:25,663 WARNING  awx.api.generics status 400 received by user AnonymousUser attempting to access /api/v2/job_templates/9/callback/ from 100.126.41.1
2020-07-29 11:59:25,667 WARNING  django.request Bad Request: /api/v2/job_templates/9/callback/
2020-07-29 11:59:25,667 WARNING  django.request Bad Request: /api/v2/job_templates/9/callback/
[pid: 85|app: 0|req: 652/1765] 100.126.41.1 () {62 vars in 1462 bytes} [Wed Jul 29 11:59:25 2020] POST /api/v2/job_templates/9/callback/ => generated 42 bytes in 384 msecs (HTTP/1.1 400) 10 headers in 318 bytes (1 switches on core 0)

##### ADDITIONAL INFORMATION
It looks that issue only happens on Openshift 4.x, Openshift 3.x works as it should 
log from Openshift 4.x
100.126.42.1 - - [29/Jul/2020:20:17:53 +0000] "POST /api/v2/job_templates/9/callback/ HTTP/1.1" 400 42 "-" "curl/7.29.0" "10.25.249.96, 10.25.130.105"
ip 10.25.130.105 is F5, which is not part of the inventory and should not be there anyway

log from openshift 3.x
/api/v2/job_templates/9/callback/ HTTP/1.1" 201 0 "-" "curl/7.29.0" "10.25.249.96, 10.25.249.96"
this works as it should

**Comment by chrismeyersfsu** [comment]
https://docs.ansible.com/ansible-tower/3.7.1/html/installandreference/proxy-support.html#proxy-support

**Comment by ryanpetrello** [comment]
Hey @wbieniek,

Issues with the callback endpoint can be tricky to troubleshoot, especially if there's any sort of proxy or similar in front of it.  This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by shanemcd** [comment]
This sound like something support could help with, if you were paying for Tower 😄
