### ISSUE TITLE
Delete button tooltip missing username when user cannot be deleted

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7751]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
<img width="1158" alt="Screen Shot 2020-07-29 at 8 35 41 AM" src="https://user-images.githubusercontent.com/9889020/88800722-9850ce00-d176-11ea-8650-eec148f2351e.png">

If you're logged in as a superuser and you select your own superuser account to be deleted the tooltip is missing the username.  IIRC we should be listing out all the resources that you don't have the ability to delete in that tooltip.

**Comment by tiagodread** [comment]
PR already merged

**Comment by unlikelyzero** [comment]
Re-opening to add coverage for https://github.com/ansible/awx/pull/8230

**Comment by mabashian** [comment]
@unlikelyzero looks like this could be closed?

**Comment by unlikelyzero** [comment]
needs additional tests added

**Comment by unlikelyzero** [comment]
https://github.com/ansible/tower-qa/pull/5626
