### ISSUE TITLE
awx_web can't connect to awx_postgres database centos 8

### ISSUE THREAD

**Issue by p3Lsh** [ansible/awx#7771]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
awx_web can't connect to awx_postgres database.

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker
* Ansible version:  2.9.11
* Operating System: centos 8
* Web Browser: Firefox 68.10.0esr (64-bit)

##### STEPS TO REPRODUCE

yum install -y epel-release -y && yum install -y jq
yum install centos-release-ansible-29.noarch
yum install -y yum-utils device-mapper-persistent-data lvm2
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
dnf install https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
yum -y install docker-ce
systemctl enable docker && systemctl start docker
yum install python3
pip3 install ansible
pip3 install docker-compose
wget https://github.com/ansible/awx/archive/13.0.0.zip
unzip 13.0.0.zip
setenforce 0
cd /root/awx-13.0.0/installer
ansible-playbook -i inventory install.yml

playbook runs without errors, web server takes ~ 5 Minutes to be reachable.

##### EXPECTED RESULTS

Connection between awx_web and awx_postgres database

##### ACTUAL RESULTS

No connection between awx_web and awx_postgres database

##### ADDITIONAL INFORMATION

Greetings,

I found the bug when I tried to install a new AWX instance. When I tried to access the web application, I was greeted by an "A server error has occurred."
The log of awx_web showed:
`django.db.utils.OperationalError: could not connect to server: No route to host
        Is the server running on host "postgres" (172.20.0.2) and accepting
        TCP/IP connections on port 5432?
`
when I connect to the postgres db from the host, there is no problem. awx_web can ping awx_postgres, but when I try to nc to the port from awx_web, I get an "No route to host", using the postgres client from awx_web also doesn't work. I assumed an error in iptables. I added an rule for DOCKER chain which allowed all traffic, but no difference.

The inventory file is completely unchanged. I also found a post about problems with the default docker-ce. I tried the same with a manual installation of docker-ce direct from docker but with the same outcome.
If you need more logs etc. feel free to ask.

**Comment by ryanpetrello** [comment]
Hey @p3Lsh,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
