### ISSUE TITLE
Remove Inventory Scripts

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#7775]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
We are removing inventory scripts from awx. This ticket tracks the API work necessary to do that for docs and QE.

##### Related Issues
Related ui_next issue: https://github.com/ansible/awx/pull/7577
Related docs issue referenced below
Related tests issue referenced below

**Comment by unlikelyzero** [comment]
@AlexSCorey @mabashian This was on the list of todo's for feature parity. Do we want to keep this ticket https://github.com/ansible/awx/issues/9267 open?

**Comment by AlanCoding** [comment]
@wenottingham are we thinking about any migration solution for this?

**Comment by wenottingham** [comment]
If practical: dump the script to the local filesystem somewhere just as a reference. No migration of sources; they will fail to update on upgrade.

**Comment by AlanCoding** [comment]
@jbradberry what should expectations be for import/export where a user made use of custom inventory scripts in a prior version?

**Comment by jbradberry** [comment]
@AlanCoding to my best recollection, inventory scripts are not even supported in awx-cli import/export.  Do we care enough about these things to leave an API endpoint active (and marked as deprecated) for a release cycle, and make them available to export?  I'm thinking that the answer is probably 'no', but if we do, I don't imagine it would be difficult to support the export.

**Comment by AlanCoding** [comment]
The PR has been updated with this approach for the migration:

 - Inventory sources of the "custom" type are deleted in the migration, and hosts/groups from them remain and can be manually edited
 - The `CustomInventoryScript` model & table will be kept, but with ForeignKeys removed
   - Users will be able to export a `.tar` file with the scrips with an `awx-manage` command (name `export_custom_scripts` for now)

**Comment by elyezer** [comment]
All verification was done pre-merge. Also tests were updated to make sure we can test both 4.0+ or <4.0 versions. I waited a few days to make sure we would not have issues after the merge of the related tower-qa PR.

There is one test failure that I suspect that may be related to this, I will double check and close this after addressing it.

**Comment by elyezer** [comment]
Final checks were made and we are good to get this one closed.
