### ISSUE TITLE
Update Instance Group Form to use Slider when available

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#7777]
### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Once slider component is available update Instance Group Form to use this one.

Mock up: https://tower-mockups.testing.ansible.com/patternfly/instance-groups/instance-groups-add/

See: https://github.com/patternfly/patternfly/issues/296

Also: https://github.com/patternfly/patternfly-react/issues/5187

**Comment by nixocio** [comment]
See: https://github.com/ansible/awx/pull/7776

**Comment by marshmalien** [comment]
Status Update: 
The Slider component is currently scheduled for PatternFly's 02.17.2021 release date, but we trying to get the Slider pulled into their 01.28.2021 release. Will continue to monitor.

**Comment by marshmalien** [comment]
Slider added to PF-React here: https://github.com/patternfly/patternfly-react/pull/5358

**Comment by mabashian** [comment]
Lets hold off on this for a bit

**Comment by nixocio** [comment]
After feedback from @shanemcd, it was decided to use the same implementation details from the old ui.

**Comment by unlikelyzero** [comment]
@nixocio will this get the new slider component from patternfly?

**Comment by nixocio** [comment]
> @nixocio will this get the new slider component from patternfly?

That is the idea.

**Comment by unlikelyzero** [comment]
@one-t, do you mind taking this one? I know you have some extensive experience here

**Comment by nixocio** [comment]
I started working on this issue, and I realized that there is a newer version of this component.

<img width="1489" alt="image" src="https://user-images.githubusercontent.com/9053044/114444975-7df04080-9b9d-11eb-84bb-084b0a01fe01.png">

And this new version seems to be affected by this https://github.com/patternfly/patternfly-react/issues/5464

I will explore a few solutions for the time being.

**Comment by tiagodread** [comment]
PR already merged
