### ISSUE TITLE
Update layout for details page

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#7778]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
As per feedback from @trahman73. 

> we want to move the text next to the label instead of trying to line them all up.

Current version:
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/9053044/88974416-95dd9980-d286-11ea-996c-37945dda4c56.png">

Updated version:
![image (1)](https://user-images.githubusercontent.com/9053044/88974586-ddfcbc00-d286-11ea-9fbf-b2dea70c1298.png)

Evaluate all screens affected by this change.

**Comment by mabashian** [comment]
Closing - not going to worry about detail layout with the new UI in flight
