### ISSUE TITLE
Add management jobs to workflow selection options

### ISSUE THREAD

**Issue by ghost** [ansible/awx#779]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
Add AWX management jobs as options that can be selected as workflow nodes.

##### ENVIRONMENT
* AWX version: 1.0.1

##### STEPS TO REPRODUCE

The option of incorporating AWX management jobs into an AWX workflow would enhance the ability to use AWX to automate management of the AWX machine by allowing the coordination f internal and external tasks that may be required.  For example, backups could be triggered in an external database system immediately preceding the automated cleanup of the database.

**Comment by wenottingham** [comment]
As I understand it, system jobs aren't exactly launched in the same way, so there's an amount of plumbing that would be required to make this practical if desired.

**Comment by AlanCoding** [comment]
Closing this, I made https://github.com/ansible/awx/issues/790 just to have a clear separation between API and UI.
