### ISSUE TITLE
Using "yaml" as a format when exporting a resource on Python 3 generates garbage

### ISSUE THREAD

**Issue by zedr** [ansible/awx#7795]
##### ISSUE TYPE
 - If one runs the command `awx export -f yaml` using a Python 3 interpreter, the literal representation of the generated bytestring will be printed, instead of the proper, parseable YAML representation.

##### SUMMARY
The command `awx export -f yaml` will print the literal representation of the generated bytestring, e.g. `b"workflow_job_templates:\n- allow_simultaneous: true\n ...` if the interpreter is Python 3. This happens because the behaviour of the `print()` function, in respect to how it handles bytestrings (`bytes`), has changed compared to Python 2.

For example:
```
Python 2.7.5 (default, Mar 20 2020, 17:08:22) 
>>> print(b'hello')
hello
```

```
Python 3.6.8 (default, Sep 26 2019, 11:57:09)
>>> print(b'hello')
b'hello'
```

In `awxkit.awxkit.cli.resource.py:231`:
```
            formatted = format_response(
                Page.from_json(response, connection=connection),
                fmt=client.get_config('format'),
                filter=_filter
            )
           print(formatted)
```
`formatted` is always of type `str` in Python 2. In Python 3 it is of type `str` if the JSON formatter is chosen, and of type `bytes` if the YAML formatter is chosen.

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: source
* Ansible version:  2.9.10
* Operating System: Linux (RHEL 7)
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

1. Install awx in a Python 3 virtual environment
2. `awx -f yaml export`

##### EXPECTED RESULTS

The command will should print a parseable representation of the YAML payload, e.g. (ellipsed for brevity)

```yaml
workflow_job_templates:
- allow_simultaneous: true
...
```

##### ACTUAL RESULTS

The command will print the following garbage on stdout (ellipsed for brevity):
```
b"workflow_job_templates:\n- allow_simultaneous: true\n ...`
```

**Comment by kdelee** [comment]
Tests passing with patch merged, also verified manually locally using `awx me -f yaml` as well as ` awx workflow_job_templates list -f yaml` going to call this verified, thanks for the patch!
