### ISSUE TITLE
Support for Spacewalk?

### ISSUE THREAD

**Issue by mattthehearn** [ansible/awx#780]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY
I've been doing some finagling to try and set up credentials to allow AWX to pull an inventory from my Spacewalk environment.  Spacewalk is essentially Satellite 5.6; at this time, AWX only works with Satellite 6, and the APIs don't seem to line up.  I poked at the foreman.py code and can see it's looking for API calls that aren't listed in Spacewalk's configuration.  I'll try and see if I can fiddle with it myself, but hopefully somebody smarter than I am is already working on it. :)

##### ENVIRONMENT
* AWX version: 1.0.1
* AWX install method: docker on linux
* Ansible version:  2.4.1.0
* Operating System: Centos 7
* Web Browser: Chrome 62.0.3202.94

##### STEPS TO REPRODUCE

Add credentials as you would for a Satellite server.  Make a new inventory and add the credentials as a source.  Sync.  

##### EXPECTED RESULTS

Enjoy having all your active servers in Satellite now in an inventory in AWX.

##### ACTUAL RESULTS

Right now I get this error:

Plugin ini failed: /usr/lib/python2.7/site-packages/awx/plugins/inventory/foreman.py:24: Expected key=value host variable assignment, got: __future__

Because the api/v2/hosts?{params} url is not a feature of the Spacewalk, aka Satellite 5, API.

**Comment by wenottingham** [comment]
I think you're looking for https://github.com/ansible/ansible/blob/devel/contrib/inventory/spacewalk.py?

**Comment by mattthehearn** [comment]
That's pretty handy, but 1) seems to require that ansible and spacewalk are running on the same server, which isn't necessarily the case in a given environment (it isn't in mine, for one), and 2) it's unclear how that ties in to AWX.  Though I guess I can leverage that code into AWX somehow.

**Comment by AlanCoding** [comment]
You can make an inventory source, sourced from a project that points to the core Ansible repo. That'll allow you to start running that script from AWX right away, and then you'll get into the problems with dependencies and the actual script expectations.

**Comment by matburt** [comment]
^ That's probably the best we are going to be able to offer right now. You can take it on yourself to modify the foreman script.

**Comment by mattthehearn** [comment]
In the end I wrote a simple Python script to interface directly with the Spacewalk API and used that to pull in the data.  Works a treat.  Thanks all!

**Comment by ninjaplatypus** [comment]
@mattthehearn Would you mind sharing your python script?  I find myself in a similar boat with AWX and spacewalk.

**Comment by sairohitdasa** [comment]
> In the end I wrote a simple Python script to interface directly with the Spacewalk API and used that to pull in the data. Works a treat. Thanks all!

@mattthehearn Would you mind sharing your python script for Spacewalk API, it would be very helpful as I am in struck in between the process of fetching inventory
