### ISSUE TITLE
Add smart inventory host detail view 

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#7806]
##### ISSUE TYPE
 - Feature Idea

This view is almost identical to the inventory host detail except we won't allow the user to edit, delete, enable, or disable the host. 

##### SUMMARY
* Add smart inventory host detail route `/inventories/smart_inventory/:inventory_id/hosts/:host_id/details`
* Hookup link to smart inventory host detail from smart inventory host list items
* Tabs: 
  * Back to Hosts 
    * Navigates back to smart inventory host list
  * Details (active)
* Details: 
  * Name
  * Activity stream
  * Inventory - Do we want to show the standard inventory? 
  * Description
  * Variables
  * Created
  * Last modified
* No edit or delete action buttons
* Read-only host toggle 

##### OLD UI FOR REFERENCE
<img width="724" alt="Screen Shot 2020-08-03 at 5 23 24 PM" src="https://user-images.githubusercontent.com/15881645/89228658-0ef22f00-d5ae-11ea-92e6-bf3600e49d66.png">

**Comment by dsesami** [comment]
confirmed with @marshmalien that we're removing the toggle in this host details PR -- once that's applied, i'll do a final pass and then we can merge.

**Comment by dsesami** [comment]
This will close with the merge of #7919
