### ISSUE TITLE
Improve support for fetching content from multiple Galaxy-like endpoints

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#7813]
Today, AWX users can specify Ansible role/collection dependencies in their SCM repositories in a `requirements.yml` file, and AWX will install these as part of the Project Update.  Currently, AWX has support for pulling this content from https://galaxy.ansible.org or *one* Galaxy-like API such as Red Hat's cloud-based Ansible Automation Hub.

The model for configuring Galaxy credentials today is too simple (you can only specify *one* "private" Galaxy, ordering is complicated, and it's a set of *global* settings that can't be differentiated per Organization).

This issue is meant to track a change to this interface whereby Galaxy credentials will be assigned to Organizations, and can be unlimited and ordered as the user sees fit.

### Scope of API Change

- [x]  Introduce a new CredentialType of e.g., `kind="galaxy"` which represents a content source for fetching collections defined in `requirements.yml` when project updates are run (e.g., galaxy.ansible.com, cloud.redhat.com, on-premise Automation Hub).  This new type will represent a URL and (optional) authentication details necessary to construct the environment variables _when a project update runs_ `ansible-galaxy collection install` as described in https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#configuring-the-ansible-galaxy-client. It will have fields which map directly to the configuration options exposed to the Ansible Galaxy CLI, e.g., per-server:
    - `url` (required str)
    - `auth_url` (optional str)
    - `token` (optional str, encrypted)

Note that a URL will *always* be required, but authentication (as in the case of galaxy.ansible.com) is optional. 

**This new solution _will not_ support basic authentication, because several of these APIs will be removing support for basic auth in the next year** (see: https://github.com/ansible/awx/pull/7811/)

- [x]  Add an API endpoint for associating an _ordered list_ of these credentials _at the Organization level_.  For example, an Organization may have an empty list (the default), or one or more items in the list (i.e., Public Galaxy, _then_ On-Prem AH).  This might be something like:

`/api/v2/organizations/N/galaxy_credentials/`

- [x]  Write code to detect and migrate the *existing* Galaxy-oriented setting values in such a way that post-upgrade, proper credentials are created and attached to _every_ Organization in the AWX install:
    - `PRIMARY_GALAXY_URL`
    - `PRIMARY_GALAXY_USERNAME`
    - `PRIMARY_GALAXY_PASSWORD`
    - `PRIMARY_GALAXY_TOKEN`
    - `PRIMARY_GALAXY_AUTH_URL`
    - `PUBLIC_GALAXY_ENABLED`

In other words, after upgrading, you should find that *every* organization that existed prior to upgrade now has a list of (one or more) "Galaxy" credentials associated with it.

Additionally, post-upgrade, these settings should not be visible (or editable) from `/api/v2/settings/jobs/`.

- [x]  Change the `awx.main.tasks` code such that when a project update runs, it looks at the list of Galaxy/AH credentials assigned to the organization, and (respecting the defined order) builds the appropriate environment variables to properly configure the `ansible-galaxy` CLI.  See: https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#configuring-the-ansible-galaxy-client

> As well as being defined in the ansible.cfg file, these server options can be defined as an environment variable. The environment variable is in the form `ANSIBLE_GALAXY_SERVER_{{ id }}_{{ key }}` where `{{ id }}` is the upper case form of the server identifier and `{{ key }}` is the key to define. For example I can define token for release_galaxy by setting `ANSIBLE_GALAXY_SERVER_RELEASE_GALAXY_TOKEN=secret_token`.

For example:

```
ANSIBLE_GALAXY_SERVER_LIST=server1,server2
ANSIBLE_GALAXY_SERVER_SERVER1_URL=https://galaxy.ansible.com
ANSIBLE_GALAXY_SERVER_SERVER2_URL=https://cloud.redhat.com/api/automation-hub/
ANSIBLE_GALAXY_SERVER_SERVER2_AUTH_URL=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
ANSIBLE_GALAXY_SERVER_SERVER2_TOKEN=secret123
```

In this way, when `awx/playbooks/project_update.yml` runs `ansible-galaxy collection install`, it will attempt the servers in order:

> The GALAXY_SERVER_LIST option is a list of server identifiers in a prioritized order. When searching for a collection, the install process will search in that order, e.g. automation_hub first, then my_org_hub, release_galaxy, and finally test_galaxy until the collection is found.

- [x]  Continue to support `GALAXY_IGNORE_CERTS` as a global setting, as the `ansible-galaxy` CLI doesn't currently have the ability to specify this value at a per-server level.

- [x]  We should ensure that this implementation _continues_ to provide support for the use case where users want to fetch roles directly from public Galaxy _even if_ galaxy.ansible.com is not the _first_ credential in the list for the Organization).

### Scope of UI Change

- [x] the organization add/edit form will need a non-required credential lookup field for credentials of `kind=galaxy`.  A note is needed to let the user know the order of these credentials matters (order sets precedence for the sync and lookup of the content)

- [x] Remove the global "Galaxy" settings from `/#/settings/jobs`.

**Comment by mabashian** [comment]
@ryanpetrello 

> the organization add/edit form will need a non-required credential lookup field for credentials of kind=galaxy

It sounds like users can select multiple galaxy credentials in this lookup - is that right?  And we need to maintain the order in which the credentials are selected when POSTing?

@trahman73 @wenottingham will it be important for us to build a UX story around re-ordering these credentials or will we just tell them to remove and re-add credentials when they want to change the order?

**Comment by ryanpetrello** [comment]
@mabashian yep - our anticipation is that this will work just like the Organization instance group picker, only you're picking Credentials of a certain kind.

> will it be important for us to build a UX story around re-ordering these credentials

There isn't really support at the API level for reordering these relations (currently, I may see if I can add it).  Today the way the instance group one works is you add/remove, and the UI sends associate/disassociate in order.

**Comment by mabashian** [comment]
Oh right I forgot about Instance Groups - we can use that as a template if needed.  Sounds good @ryanpetrello.

**Comment by elyezer** [comment]
Now that https://github.com/ansible/awx/pull/7817 is merged we can consider this as being verified from the API perspective. All verification was done before merging.

**Comment by unlikelyzero** [comment]
Verified from the UI perspective. I would like to have someone from the tower team run through the docs during hardening.
Also, should we verify each of the deployment models before closing this @Spredzy @elyezer ?

Issues:

- Add/ Edit Credential form does not list Organization as a required field when creating or editing an 'Ansible Galaxy/Automation Hub API Token' credential
- In-line helper text for 'Ansible Galaxy/Automation Hub API Token' could be more helpful

Tests:
Can create an Ansible Galaxy/Automation Hub API Token credential type
Can create an Ansible Galaxy/Automation Hub API Token credential type configured for cloud.redhat
Can create an Ansible Galaxy/Automation Hub API Token credential type configured for an on-prem AH server
Can assign a Ansible Galaxy/Automation Hub API Token credentials to a new Organization
Can assign multiple Ansible Galaxy/Automation Hub API Token credentials to a new Organization
Can assign a Ansible Galaxy/Automation Hub API Token credentials to an existing Organization
Can assign multiple Ansible Galaxy/Automation Hub API Token credentials to an existing Organization
Can remove Ansible Galaxy/Automation Hub API Token credentials from an existing Organization
If a project cannot reach the first Ansible Galaxy/Automation Hub API Token credential server configured, it will fallback to the second Ansible Galaxy/Automation Hub API Token credential

**Comment by elyezer** [comment]
@unlikelyzero can we close this?

**Comment by unlikelyzero** [comment]
@elyezer the last comment still stands :)

If you don't think we should verify the deployment models before closing this ticket, then it can be closed.

**Comment by elyezer** [comment]
@unlikelyzero the deployment models (different types or installation and what not) are being tracked by separate tickets, for example https://github.com/ansible/tower-packaging/issues/898 and https://github.com/ansible/tower/issues/4373. So I think we are good to close this one as this was focusing on the ability of having the AH/Galaxy configuration per Org.
