### ISSUE TITLE
Add the ability to change the TZ timestamp on splunk for the events sending from Ansible Tower.

### ISSUE THREAD

**Issue by Saurabh-Thakre** [ansible/awx#7815]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

If we change the Timezone on Ansible Tower for Tower logging either by creating a /etc/tower/conf.d/custom_timezone.py with following 

~~~
TIME_ZONE = "Asia/Tokyo"
~~~

Or either you pass it from Settings>Jobs>**EXTRA ENVIRONMENT VARIABLES** with following
~~~
{
 "TZ": "Asia/Tokyo"
} 
~~~

We can see the change in the Ansible Tower logs but the Splunk logs still shows the UTC timezone timestamp. Having an ability to change the TZ for the events we ship to Splunk.

**Comment by ryanpetrello** [comment]
Don't do this.  Treat timestamps everywhere as UTC, and normalize/convert them at the presentation layer.  Surely Splunk has some capability for coercing UTC logs into the timezone of your choosing?
