### ISSUE TITLE
InventorySource new fields

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#7819]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
UI work related to https://github.com/ansible/awx/issues/5150

`InventorySource` will have fields `enabled_var, enabled_value, host_filter` The meaning of which are described below.

| **Field**     | **Type** | Description                                                  |
| ------------- | -------- | ------------------------------------------------------------ |
| enabled_var   | string   | Retrieve the enabled state from the given dict of host variables.  The enabled variable may be specified as 'foo.bar', in which case the lookup will traverse into nested dicts, equivalent to: `from_dict.get('foo', {}).get('bar', default)` |
| enabled_value | string   | Only used when `enabled_var` is set. Value when the host is considered enabled. For example if `enabled_var='status.power_state'` and `enabled_value='powered_on'` with host variables: <br />{<br/>  "status": {<br/>    "power_state": "powered_on",<br/>    "created": "2020-08-04T18:13:04+00:00",<br/>    "healthy": true<br/>  },<br/>  "name": "foobar",<br/>  "ip_address": "192.168.2.1"<br/>}<br /><br />The host would be marked enabled. If `power_state` where any value other than `powered_on` then the host would be disabled when imported into Tower. |
| host_filter   | string   | Regex where only matching hosts will be imported into Tower. |

**Comment by jakemcdermott** [comment]
This is done & ready for testing once the related api changes land: https://github.com/ansible/awx/pull/7763

**Comment by dsesami** [comment]
adjustments and comments here: https://github.com/ansible/awx/pull/7763#pullrequestreview-473813458
