### ISSUE TITLE
Run Command is not working

### ISSUE THREAD

**Issue by tchia04** [ansible/awx#782]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
When I perform an ad-hoc Run command, I got "stdout capture is missing"

##### ENVIRONMENT
* AWX version: AWX 1.0.1.231  >
* AWX install method: docker on linux
* Ansible version:  Ansible 2.4.1.0 
* Operating System: Redhat 7
* Web Browser: chrome on Windows

##### STEPS TO REPRODUCE

1) select an inventory such as the "Demo Inventory"
2) Click on the host button and select the localhost host.
3) click the checkbox next to localhost and click on "Run command" 
4) Select the setup module and select "Demo Credential" and click launch
5) The error message "stdout capture is missing" under standard out

##### EXPECTED RESULTS
display the result of the setup module execution.

##### ACTUAL RESULTS

The error message "stdout capture is missing" under standard out

**Comment by tchia04** [comment]
I perform the same steps on ansible tower and it worked perfectly.

**Comment by ryanpetrello** [comment]
Hey @tchia04, this is a known issue we're working on resolving: https://github.com/ansible/awx/issues/200

Thanks!
