### ISSUE TITLE
HashiCorp Vault Secret Lookup: Unable to create Machine credential with HashiCorp Vault Secret Lookup as Input Source

### ISSUE THREAD

**Issue by amtilghman** [ansible/awx#7826]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Unable to create Machine credential with HashiCorp Vault Secret Lookup as Input Source

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.10
* Operating System: CentOS Linux release 7.8.2003 (Core)
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Add a new credential
type: “HashiCorp Vault Secret Lookup”
set: Name, Server URL, Token
Click the "SAVE" button

Add a new credential
type: “Machine”
set: Name, Username
Click the Magnifyng glass under "SSH PRIVATE KEY"
Select the previously create HashiCorp Vault

##### EXPECTED RESULTS

Next button is displayed

##### ACTUAL RESULTS

No Next button is displayed, unable to create machine credential with HashiCorp Vault Secret Lookup as Input Source

##### ADDITIONAL INFORMATION

Screenshot showing the missing next button:
![screenshot](https://user-images.githubusercontent.com/13816186/89359690-eb1a1080-d6b5-11ea-8224-f5dbc215c200.png)

Button appears on version 12.0.0

This is a gif image that depicts the process when it is working
https://user-images.githubusercontent.com/9753817/54286783-deee5a00-457a-11e9-85bb-831d03196cd0.gif

**Comment by wenottingham** [comment]
dup of #7530
