### ISSUE TITLE
working with localhost has unexpected behaviour.

### ISSUE THREAD

**Issue by phospi** [ansible/awx#7827]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Setting 'localhost' is not usable via job template limit.

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker on linux, docker for mac
* Ansible version:  2.9.10
* Operating System: CentOS
* Web Browser: Chrome

##### STEPS TO REPRODUCE
 - Create a Job Template
 - Select any inventory (which does not contain a host called 'localhost')
 - Configure Job Template with special playbook
 - Set limit to 'localhost'
 - The selected playbook includes the following config: 'hosts: "{{ ansible_limit }}" '

##### EXPECTED RESULTS
The ansible engine usually can always work with localhost.
https://docs.ansible.com/ansible/latest/inventory/implicit_localhost.html

I expect awx to identify 'localhost' as a special keyword and pass it to the playbook. When localhost is written directly like this in playbook 'hosts: localhost', it works.

##### ACTUAL RESULTS
AWX Job does not run and returns the following error: 
ERROR! Specified hosts and/or --limit does not match any hosts

##### ADDITIONAL INFORMATION
I think this is a minor issue because if I want to run a playbook against localhost I can set this directly in the playbook. However, in my opinion it's a bug nonetheless because awx should be able to recognize 'localhost'.

**Comment by wenottingham** [comment]
This behavior is consistent with ansible, as far as I can tell.
```
[notting@nostromo: ~/prog/scratch/oof]$ cat i
[all]
a
b
c
[notting@nostromo: ~/prog/scratch/oof]$ cat test.yml
---
- hosts: "{{ ansible_limit }}"
  gather_facts: false
  
  tasks:
    - name: oof
      command: ls
[notting@nostromo: ~/prog/scratch/oof]$ ansible-playbook  -i i test.yml --limit localhost
ERROR! Specified hosts and/or --limit does not match any hosts
```

**Comment by phospi** [comment]
The behaviour 'cannot resolve undefined "ansible_limit" in ansible engine' might be consistent.

But funny enough if you stay with 'hosts: "{{ ansible_limit }}"' for any limit in awx that is not 'localhost', it works. AWX fills variable 'ansible_limit' automatically. It does work with every host from an AWX inventory. But the special case of 'localhost' which should be available all the time, is not respected.

**Comment by phospi** [comment]
@wenottingham I request re-opening this issue.

**Comment by wenottingham** [comment]
This would need changed in ansible itself; that is tracked at https://github.com/ansible/ansible. AWX isn't going to interpret this differently than Ansible itself does.
