### ISSUE TITLE
Collapse toolbar additionalControls when advancedSearch is displayed

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#7831]
Currrently there is not enough room for these elements to be displayed as they are...we'll move to a kebab.

**Comment by unlikelyzero** [comment]
Note: this will require require a retest. Please make sure that all e2e tests are passing

**Comment by unlikelyzero** [comment]
One test is currently failing due to a previous merge. This is good to merge!

**Comment by unlikelyzero** [comment]
@jlmitch5 @wenottingham @mabashian there are enough issues that I think we should move this back into `needs_devel`
https://github.com/ansible/awx/issues/8020
https://github.com/ansible/awx/issues/8017
https://github.com/ansible/awx/issues/7938

**Comment by tiagodread** [comment]
Closing this one, we are moving the toolbar buttons to a kebab for all lists when there is no space to show them, #8020 and #7938 are still valid and we should keep track of the work there.
