### ISSUE TITLE
Advanced search: certain lookups (suffixes) invalid for certain types of keys.

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#7834]
![89440610-de2f0880-d719-11ea-8b09-d29297428d2e](https://user-images.githubusercontent.com/1342624/89447526-16d3df80-d724-11ea-880e-e8bbaffeed39.png)

In the above example, iexact is invalid for the "id" key, because id expects a number.  This enhancement would filter the list of lookups based on the key selected's type.

my guess is that it's doable...we could probably filter that list based on what "type" the key they select is.  but that's a pretty sizeable enhancement (we need to get that from the options request, pass it to advanced search, check to see what type of key it is upon selection and then filter the possible options list)

I feel that we should triage this ask to see if we really want to add this for 4.0

**Comment by mabashian** [comment]
The enhancement that @jlmitch5 outlines is definitely worthwhile so I think we should keep this issue open.

The fact that we can trigger a 500 by doing this is not great so I'm going to open up an api issue to see if they can return a 4xx error instead to give the user a little better message.

**Comment by mabashian** [comment]
Link https://github.com/ansible/awx/issues/9222

**Comment by unlikelyzero** [comment]
still accurage

**Comment by nixocio** [comment]
This one seems to be related to https://github.com/ansible/awx/issues/9956
