### ISSUE TITLE
Support Galaxy Credentials field on Organization

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7835]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
As part of https://github.com/ansible/awx/pull/7817 we added a credential field to the org form that lets a user select credentials of kind=galaxy.  This field behaves like the instance groups lookup where the user can select N number of credentials and the order that they select them is the order that we should save them.

**Comment by mabashian** [comment]
I've got this mostly working here: https://github.com/mabashian/awx/tree/7835-galaxy-cred-org

I'm going to wait for https://github.com/ansible/awx/pull/7817 to merge though before opening up a PR so as not to muddy the waters on that original PR.

**Comment by ryanpetrello** [comment]
Hey @mabashian heads up, #7817 merged today.

**Comment by unlikelyzero** [comment]
what's the dealio. needs_test?

**Comment by mabashian** [comment]
@unlikelyzero should have a PR up today.  Rebase has been a bit messy.

**Comment by mabashian** [comment]
@unlikelyzero can we close this one?

**Comment by unlikelyzero** [comment]
@mabashian we don't have good coverage here. I'm going to leave this open to reassess

**Comment by akus062381** [comment]
We have test coverage with the exception of what is contained in the following link

https://github.com/ansible/awx/issues/9127
