### ISSUE TITLE
Failed to install awx on openshift

### ISSUE THREAD

**Issue by promogekko** [ansible/awx#784]
##### ISSUE TYPE
 - Bug Report 

##### COMPONENT NAME
 - Installer

##### SUMMARY
When running installer that's failed 

##### ENVIRONMENT
latest version of AWX
docker 	17.12.0-ce-rc1
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
etcd 3.2.8

##### STEPS TO REPRODUCE
change inventory to set up the openshift environment 

##### EXPECTED RESULTS

ansible ok 

##### ACTUAL RESULTS
TASK [openshift : Apply Deployment] ***************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "oc apply -f /tmp/awx-config/deployment.yml", "delta": "0:00:00.638243", "end": "2017-12-10 13:32:58.643352", "msg": "non-zero return code", "rc": 1, "start": "2017-12-10 13:32:58.005109", "stderr": "Error from server (BadRequest): error when creating \"/tmp/awx-config/deployment.yml\": Deployment in version \"v1beta1\" cannot be handled as a Deployment: [pos 2205]: json: expect char '\"' but got char '5'", "stderr_lines": ["Error from server (BadRequest): error when creating \"/tmp/awx-config/deployment.yml\": Deployment in version \"v1beta1\" cannot be handled as a Deployment: [pos 2205]: json: expect char '\"' but got char '5'"], "stdout": "service \"awx-web-svc\" configured\nroute \"awx-web-svc\" configured", "stdout_lines": ["service \"awx-web-svc\" configured", "route \"awx-web-svc\" configured"]}
	to retry, use: --limit @/home/centos/Dev/awx/installer/install.retry

**Comment by matburt** [comment]
hmm I wonder what part of the templated `deployment.yml` it's having trouble with. Could you show me what the post-templated version of that file looks like?

**Comment by pedroclopes93** [comment]
i'm facing the same issue.

**Comment by madhakish** [comment]
Missing () around the {{}} for pg_host, it's escaping the double-quotes passed by the inventory. The error is complaining about a missing double quote around an integer value. Fixed in my local fork and it is working again.

This indeed breaks when attempting to deploy to OSE using the deployment.yml.j2 template.

[deployment.yml.j2.zip](https://github.com/ansible/awx/files/1549697/deployment.yml.j2.zip)

**Comment by matburt** [comment]
Fixed in: https://github.com/ansible/awx/commit/282290e151897a4c48d8cda455a397b733c90db4
