### ISSUE TITLE
Hide delete button for user who doesn't have permission to delete anything on the list

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#7841]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
As per group discussion and feedback from @trahman73. It was decided to hide the delete button for system auditor user type.

Currently:

![image](https://user-images.githubusercontent.com/9053044/89466852-8d7fd580-d742-11ea-993a-08da577f94c0.png)

**Comment by AlanCoding** [comment]
It is possible to have system auditor permission, but still have other types of admin permission (which allows deleting). I just want to be sure we're on the same page about that.

**Comment by nixocio** [comment]
@AlanCoding, AFAIK that is the end goal. Hiding the delete button for `system auditor` is already implemented in the current UI, we will basically mimic same feature in the new UI.

**Comment by mabashian** [comment]
IDK if we really want to do this.  I think this title is misleading... as Alan points out, an auditor _may_ be granted the necessary permissions to delete something.  I think what this issue should say is:

`Hide delete button for user who doesn't have permission to delete anything on the list`

Which is possible on a page my page basis but the user could have permissions to delete something on the second page.

I want to make sure we're aware of the exact UX implications of doing this before we dive in.

**Comment by wenottingham** [comment]
> Which is possible on a page my page basis but the user could have permissions to delete something on the second page.

I'm not sure I'd want to hide it in a scenario like this. Only on an individual object.
