### ISSUE TITLE
Add possibility to map AttributeValue to team and other mappings.

### ISSUE THREAD

**Issue by planeturban** [ansible/awx#7843]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

As things are right now the AttributeValue set in the `SAML team map` has to map to the team name in AWX. This poses a problem when the access groups from the SAML provider are numerical or just plain gibberish (GServAWXAnsiblePaaS) due to company wide naming conventions, aka "reasons". 

**Proposal**: add attribute_value in map. Left blank, it maps to `team`.

````json
    "saml_attr": "User.Teams",
    "remove": true,
    "team_org_map": [
    {
        "team": "PaaS Services",
        "organization": "Default",
        "attribute_value": "GServAWXAnsiblePaaS"  
    }
  ]
}

**Comment by john-westcott-iv** [comment]
Thanks for bring this to our attention. Per the [docs](https://docs.ansible.com/automation-controller/latest/html/administration/ent_auth.html#saml-settings) this is now possible:
```
You could create an alias to override both Teams and Orgs in the SAML Team Attribute Mapping. This option becomes very handy in cases when the SAML backend sends out complex group names, like in the example below:
```

```
{
 "remove": false,
 "team_org_map": [
  {
   "team": "internal:unix:domain:admins",
   "organization": "Default",
   "team_alias": "Administrators"
  },
  {
   "team": "Domain Users",
   "organization_alias": "OrgAlias",
   "organization": "Default"
  }
 ],
 "saml_attr": "member-of"
}
```

Closing this issue.
