### ISSUE TITLE
Add track_submodules option for Git projects

### ISSUE THREAD

**Issue by EzraBrooks** [ansible/awx#7846]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
With the advent of Git submodules supporting branch specifiers in the `.gitmodules` file, and being able to use `git submodule update --remote` to update the reference easily, it's become feasible to use submodules as a living reference to other repositories instead of just a snapshot of those repos in time. Other deployment tools i.e. Jenkins often have the ability to run `git submodule update --remote` at the beginning of a job, and it would be very useful for my team if AWX could do the same.

The `git` module in Ansible has this argument implemented already - `track_submodules` - but it is not exposed in the frontend in AWX.

**Comment by juanvalino** [comment]
+1

**Comment by shanemcd** [comment]
Looks like this got added in https://github.com/ansible/awx/pull/9219
