### ISSUE TITLE
Dispatcher unable to handle absent nodes

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#7848]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

To start, we are backing up a cluster and restoring to servers in a different data center which may have different names. In the database the main_instance table has entries with the same UUIDs but different hostnames. When this happens the dispatcher for running jobs becomes unreachable and you can no longer cancel jobs. 

PR https://github.com/ansible/awx/pull/7823 fixes a 500 error from happening within the UI when trying to cancel a job running on a non-reachable dispatcher. While it works for a job template, workflow job templates appear to "resurrect" themselves in the UI. https://drive.google.com/file/d/1KBdTjOeY1Jag1eISlKbR9WJhiwwv9x_k/view?usp=sharing This appears to be happening because on a workflow only the cancel_flag is set too True and then the dispatcher picks up this flag and actually performs the job cancel. So the UI makes it looked canceled but then (after the status is reloaded) the UI puts it back into its running state.

Should the reaper logic should be updated to handle dispatcher processes which have been lost and will not return?

##### ENVIRONMENT
* AWX version: 13.0.0 (Tower 3.7.1)
* AWX install method: Tower Cluster
* Ansible version:  X.Y.Z
* Operating System: RHEL
* Web Browser: Any

##### STEPS TO REPRODUCE
Build a 3 node cluster with external database.
Start a workflow running on the cluster.
Backup the cluster.

Restore the backup into a new 3 node cluster.
The workflow that was running in the old cluster during the backup will not be cancelable. 
NOTE: there is a PR to the backup code #841 which will auto-cancel running jobs during a restore. If the above is tested with that PR this will not be reproducible.

##### EXPECTED RESULTS
Canceling a job in the UI will result in the job being canceled.

##### ACTUAL RESULTS
Jobs are stuck running in queue.

**Comment by wenottingham** [comment]
`with the same UUIDs but different hostnames`

How???

**Comment by ryanpetrello** [comment]
To reproduce something like this in a fairly contrived way:

1.  Launch a job and let it finish.
2.  `Job.objects.filter(pk=N).update(status='running', execution_node='some-nonsense.example.org')`
3. Even if you restart services, this just stays in `running` forever.

**Comment by kdelee** [comment]
Tried this out and worked like charm! Thanks

```
awx_1       | 2020-09-15 20:52:14,460 ERROR    awx.main.scheduler some-nonsense.example.org is not a registered instance; reaping job 2 (running)
awx_1       | 2020-09-15 20:52:14,576 ERROR    awx.main.dispatch job 2 (failed) is no longer running; reaping
```
