### ISSUE TITLE
Install.yml - Activate postgres container, Error while fetching API, permission denied (Ubuntu 16.04)

### ISSUE THREAD

**Issue by peterducai** [ansible/awx#786]
Got this issue on Ubuntu 16.04.3 and also 17.10..  (it works on fedora 26 with docker-ce 17.09)
```
git clone awx
cd awx/installer
ansible-playbook -i inventory install.yml 
```
then getting
```
TASK [local_docker : Activate postgres container] ********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', error(13, 'Permission denied'))"}
	to retry, use: --limit @/home/daemonna/awx/installer/install.retry

```

and fails also with -e "ansible_python_interpreter=python"

using ansible 2.4.2 (installed through PIP), Docker version 1.13.1, build 092cba3 (on Ubuntu), docker running (and docker pull postgres downloads image without problems)

```
TASK [local_docker : Activate postgres container] *************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', error(13, 'Permission denied'))"}
	to retry, use: --limit @/home/daemonna/awx/installer/install.retry
```
sudo is with NOPASSWD, no permission denied for anything else.

BTW same error even if switching to latest docker **17.09.0-ce** ip

**Comment by matburt** [comment]
Either docker isn't running or (more likely) you don't have permission to access the service. Make sure the user you are connecting as can connect to the docker service.
