### ISSUE TITLE
awx 9.3.0 to 10.0/13.0 migration fail (awx-manage)

### ISSUE THREAD

**Issue by mnhan3** [ansible/awx#7865]
AWX:9.3.0
platform: openshift 3.11
postgres version: 10 (external database)
awx_user: awx
schema: awx
owner: awx

Previous migrated from 9.0.1 to 9.3.0 no issue.

attempting to migrate to 10.0 or 13.0 errors at

>         "Traceback (most recent call last):",
>         "  File \"/usr/bin/awx-manage\", line 8, in <module>",
>         "    sys.exit(manage())",
>         "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py\", line 152, in manage",
>         "    execute_from_command_line(sys.argv)",
>         "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py\", line 381, in execute_from_command_line",
>         "    utility.execute()",
>         "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py\", line 375, in execute",
>         "    self.fetch_command(subcommand).run_from_argv(self.argv)",
>         "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py\", line 323, in run_from_argv",
>         "    self.execute(*args, **cmd_options)",
>         "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py\", line 364, in execute",
>         "    output = self.handle(*args, **options)",
>         "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py\", line 83, in wrapped",
>         "    res = handle_func(*args, **kwargs)",
>         "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/commands/migrate.py\", line 234, in handle",
>         "    fake_initial=fake_initial,",
>         "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/migrations/executor.py\", line 117, in migrate",
>         "    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)",
>         "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/migrations/executor.py\", line 147, in _migrate_all_forwards",
>         "    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)",
>         "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/migrations/executor.py\", line 245, in apply_migration",
>         "    state = migration.apply(state, schema_editor)",
>         "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/migrations/migration.py\", line 124, in apply",
>         "    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)",
>         "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/migrations/operations/special.py\", line 190, in database_forwards",
>         "    self.code(from_state.apps, schema_editor)",
>         "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/migrations/0109_v370_job_template_organization_field.py\", line 16, in rebuild_jt_parents",
>         "    rebuild_role_parentage(apps, schema_editor, models=('jobtemplate',))",
>         "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/migrations/_rbac.py\", line 280, in rebuild_role_parentage",
>         "    content_object = ct_model.objects.get(pk=role.object_id)",
>         "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/manager.py\", line 82, in manager_method",
>         "    return getattr(self.get_queryset(), name)(*args, **kwargs)",
>         "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py\", line 408, in get",
>         "    self.model._meta.object_name",
>         "__fake__.DoesNotExist: JobTemplate matching query does not exist.",
>         "command terminated with exit code 1"

Appreciate any help to migrate to 13.0 if possible without loosing data.

**Comment by ryanpetrello** [comment]
Hey @mnhan3,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install or upgrade, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
