### ISSUE TITLE
Job with rescued tasks marked as failed

### ISSUE THREAD

**Issue by tmanninger** [ansible/awx#7869]
##### ISSUE TYPE
 - If a job have rescued tasks, but no failed tasks, AWX marks the job as failed:

```
PLAY RECAP *********************************************************************
host1 : ok=43   changed=27   unreachable=0    failed=0    skipped=24   rescued=1    ignored=0   
host2: ok=26   changed=16   unreachable=0    failed=0    skipped=26   rescued=0    ignored=0   
host3 : ok=133  changed=20   unreachable=0    failed=0    skipped=62   rescued=1    ignored=0   
host4 : ok=62   changed=16   unreachable=0    failed=0    skipped=40   rescued=0    ignored=2   
host5: ok=30   changed=18   unreachable=0    failed=0    skipped=26   rescued=0    ignored=2   
host6 : ok=26   changed=16   unreachable=0    failed=0    skipped=26   rescued=0    ignored=2
```

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker 
* Operating System: Debian 9

##### EXPECTED RESULTS

The job should me marked as successful by AWX (and not failed)

**Comment by AlanCoding** [comment]
I attempted to reproduce with content at https://github.com/ansible/test-playbooks/pull/152

I found that the AWX job was marked as successful, as expected.

If you can give me a playbook that will replicate the behavior, I will test it. Right now, with the simple rescued task, I can't see any bugs.

**Comment by tmanninger** [comment]
Hi @AlanCoding,

Now i can reproduce the issue with a simple playbook, but i think it's an ansible bug, see this new created issue:
https://github.com/ansible/ansible/issues/71306

**Comment by AlanCoding** [comment]
Nice, I left a detailed reply in that issue. I believe you found a real bug.

Closing this, as there is nothing to do on the AWX side.
