### ISSUE TITLE
Notification Details: Display custom notification messages

### ISSUE THREAD

**Issue by keithjgrant** [ansible/awx#7877]
Follow-up on #7867

Display the custom notification text, if different than the default messages.

##### ISSUE TYPE
 - Feature Idea

**Comment by unlikelyzero** [comment]
@keithjgrant , @tiagodread and @unlikelyzero will be testing this when it's first available for `state:needs_review`. We've got most of the tests already written

**Comment by tiagodread** [comment]
Everything OK, tests are written and the PR already merged
