### ISSUE TITLE
Ansible Playbook sending multiple mails when it gets executed

### ISSUE THREAD

**Issue by sowmian** [ansible/awx#7883]
Hi All,

I've been writing a new Playbook to gather some information about one agent to see whether it is installed / Updated on all the dev servers where the list of Dev servers are mentioned in an /etc/ansible/hosts under dev_servers group. If I execute the below playbook it is executing well but when it completes and try to send the information in the mail it is sending a bunch of emails, Instead, I need to have one email which can have all the details. How to achieve this?

hosts: "{{ hosts_group }}"
user: ansadm
become_user: root
become: yes
become_method: sudo
gather_facts: no
tasks:
name: Get Freshclam Status
shell:
cmd: "freshclam -V"
register: FreshClam_output
debug: msg="{{ FreshClam_output.stdout}}"
name: Send Email
mail:
host: mail.onemagnify.corp
port: 25
from: Email1@gmail.com
to: Email2@gmail.com
subject: FreshClam - Report
body: "{{ lookup('file', '/etc/ansible/playbooks/common/freshclam_dev.out') }}"

**Comment by ryanpetrello** [comment]
Hey @sowmian,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
