### ISSUE TITLE
[UI] Execution environments

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#7884]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Issue to track the progress of UI work related to execution environments.

~1 - Update navigation bar and routing system to add execution environments. https://github.com/ansible/awx/issues/7885~
~2 - List execution environments - https://github.com/ansible/awx/issues/7886~
~3 - Add/Edit execution environments - https://github.com/ansible/awx/issues/7887~
~4 - Add details execution environments - https://github.com/ansible/awx/issues/8171~
~5 - Add access view for execution environments - https://github.com/ansible/awx/issues/8190~
~6 - Add execution environments view for organizations -  https://github.com/ansible/awx/issues/8210 -> #8337-> #9384~
~7 - Update usage of user_capabilities for execution environments - https://github.com/ansible/awx/issues/8216~
~8 - Add option to select a default global EE on settings - https://github.com/ansible/awx/issues/9088~
~9 - Update EE Add/List/Edit/Details with latest API changes - https://github.com/ansible/awx/issues/9087 ->  #9179~
~10 - Add execution environment field to a few screens - https://github.com/ansible/awx/issues/9189~
~11 -  Remove the custom venv fields from the UI - https://github.com/ansible/awx/issues/9190~
~12 -  Surface missing-resource warnings on list items for UJTs that were using custom virtualenvs - https://github.com/ansible/awx/issues/9207~
~13 - A pull option to EE - https://github.com/ansible/awx/issues/9109~
~14 - User should not modify name and image managed by awx. https://github.com/ansible/awx/issues/9250~
~15 - Add EE to the Activity Stream - https://github.com/ansible/awx/issues/9308~
~16 - Add copy functionality to EE - https://github.com/ansible/awx/issues/9307~
~17 - Re-evaluate RBAC for EE as per latest API changes - https://github.com/ansible/awx/issues/9416~
18 - Filter by container registry credential to be associated with EE - https://github.com/ansible/awx/issues/9628
~19 - Remove EE field from Project screen - https://github.com/ansible/awx/issues/9719~
~20 - Add screen to represent EE unified job templates endpoint - https://github.com/ansible/awx/issues/9723~
21 - Add link to the docs in how to replace a custom virtual env with an EE - https://github.com/ansible/awx/issues/9846
~22 - EE RBAC violation when EE org changes - https://github.com/ansible/awx/issues/9769~
~23 - Add option to select EE when launching ad-hoc commands - https://github.com/ansible/awx/issues/9864~

### Bugs
~1 - Unable to select non-global execution environments for organizations https://github.com/ansible/awx/issues/9592~
~2 - Organization should be used to filter EE related to certain resources - https://github.com/ansible/awx/issues/9770~

To be expanded.

See: https://tower-mockups.testing.ansible.com/patternfly/exec-env/exec-env/
API changes:  https://github.com/ansible/awx/issues/5157 and https://github.com/ansible/awx/issues/7062

**Comment by dsesami** [comment]
@nixocio me and john would like to follow up with you on the progress of this ticket to understand where everything is at, what is testable, and what we should be looking out for next.

update -- this is a general issue that also exists with the main jobs list, and will be handled in another issue.

**Comment by AlanCoding** [comment]
It looks like this only covers the listing / editing of the execution environments themselves (and related credentials). Additionally, people need to be able to add them to other objects so they can be used in jobs. @jbradberry can correct me

 - organization
   - `default_environment` field
 - project
   - `default_environment` field
 - inventory source
   - `execution_environment` field
 - job template
   - `execution_environment` field

**Comment by nixocio** [comment]
ok, I will file issues to reflect those other requirements.

What about adding the default global EE? Is it going to be part of `settings` endpoint? This issue here https://github.com/ansible/awx/issues/9088

**Comment by AlanCoding** [comment]
Yeah, that also needs to be in there and that issue for the global default looks fine to me.

**Comment by jbradberry** [comment]
Should they show up on the job detail page?  Shows which EE was used to execute them.

**Comment by nixocio** [comment]
> Should they show up on the job detail page? Shows which EE was used to execute them.

I can add an issue to track this, and I will probably need to follow up with you all later when implementing this.

**Comment by AlanCoding** [comment]
Good point @jbradberry, all the fields I listed in the above comment https://github.com/ansible/awx/issues/7884#issuecomment-768394443 are strictly editable fields. It's non-obvious what EE a job used. The API should report that, and it should be in the UI jobs page just like custom venv used to be.

Ping @yagomarques, in integration tests, after we do `job = jt.launch()`, where the job uses an EE, we should make assertions that `job.execution_environment` is the correct one, in addition to the other assertions we make.

**Comment by jbradberry** [comment]
Are we tracking the need to remove the custom venv fields from the UI?

**Comment by unlikelyzero** [comment]
@jbradberry @AlanCoding is there a good list of changes which will impact the settings pages?

**Comment by nixocio** [comment]
> Are we tracking the need to remove the custom venv fields from the UI?

I filed an issue. https://github.com/ansible/awx/issues/9190

**Comment by tiagodread** [comment]
Related: https://github.com/ansible/awx/issues/9432, https://github.com/ansible/awx/issues/9441

**Comment by tiagodread** [comment]
Related: https://github.com/ansible/awx/issues/9448

**Comment by nixocio** [comment]
The core work related to EE was already completed and tested. Closing this one.
