### ISSUE TITLE
List execution environments

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#7886]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
List execution environments

**Comment by dsesami** [comment]
This is going to be checked off along with https://github.com/ansible/awx/issues/7887, which is in needs_review because of some minor changes that will be made.

**Comment by dsesami** [comment]
Couple of things:
1) Organization doesn't make sense here. What org is associated with an EE? There is no field for this, I think.
2) Sorting by description when that description is not visible is weird. This is an issue in other places as well, but do we want to address that here?

![Screenshot from 2020-09-22 10-01-42](https://user-images.githubusercontent.com/19942822/93892549-a3c5fe80-fcba-11ea-9b70-f19a6623dd10.png)

**Comment by jbradberry** [comment]
> Couple of things:
> 
>     1. Organization doesn't make sense here. What org is associated with an EE? There is no field for this, I think.
> 
>     2. Sorting by description when that description is not visible is weird. This is an issue in other places as well, but do we want to address that here?
> 
> 
> ![Screenshot from 2020-09-22 10-01-42](https://user-images.githubusercontent.com/19942822/93892549-a3c5fe80-fcba-11ea-9b70-f19a6623dd10.png)

@dsesami that is incorrect, there is an (optional) owning Organization for each EE.  This is just a straightforward nullable foreign key on the EE model.

I think that this list needs to have the Organization showing for each EE when there is one associated.

**Comment by dsesami** [comment]
@jbradberry good to know. i've updated the add/edit/details issues with information about the optional org field.

**Comment by nixocio** [comment]
I will also update the list to display organizations.

**Comment by unlikelyzero** [comment]
moving to https://github.com/ansible/awx/issues/7884
