### ISSUE TITLE
Add/Edit execution environments

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#7887]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add/Edit execution environments

**Comment by dsesami** [comment]
Currently, the image name field looks like this:

![Screenshot from 2020-09-21 15-54-22](https://user-images.githubusercontent.com/19942822/93814703-e3d9a280-fc22-11ea-9123-1112425c499d.png)

Based on what I understand, ansible/awx would be a valid image name if someone was using podman. does that mean this field doesn't only have URLs? also, can we add tooltip info to show more details about valid formats? We might also change the field from "Image name" to "fully qualified image name", or something else. I'll leave that to devs to decide.

**Comment by dsesami** [comment]
Also -- does the description field have a character limit? this should be checked. it can go indefinitely as far as i can tell, and the API accepts that. there should be a limit.

**Comment by nixocio** [comment]
@dsesami , right now I added a validation to verify that is a valid URL. If we decide that is not the case, I can update that.

**Comment by dsesami** [comment]
based on feedback from https://github.com/ansible/awx/issues/7886#issuecomment-696769284, we need to add an optional organization field here.

**Comment by dsesami** [comment]
(mistakenly closed)

**Comment by nixocio** [comment]
After followed up with @jbradberry.

There are at least 2 scenarios to be added.

*   User is a `system_administrator`. 
    1.  This one can create globally available execution environment, providing `organization` as null.
    2.  This one can create execution environment to a specific organization, providing `organization` id to the API.

* User is `organization admin`.
  1. This one can create execution environments only to the organizations that this user is admin.

I will follow up with @trahman73 , and @jakemcdermott about a possible layout update for the Add/Edit views.

**Comment by dsesami** [comment]
assigning john and tiago in case handoff is needed

**Comment by unlikelyzero** [comment]
moving to https://github.com/ansible/awx/issues/7884
