### ISSUE TITLE
Whitelist a callback plugin

### ISSUE THREAD

**Issue by jerryhwg** [ansible/awx#7889]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

https://docs.ansible.com/ansible/latest/plugins/callback.html

In ansible-playbook command line, I can choose which callback plugin to whitelist(enable) in a playbook run.
e.g. a custom callback plugin : notify_me
```
ANSIBLE_CALLBACK_WHITELIST=notify_me ansible-playbook node-build.yml
```
It's not possible to do so with AWX.

**Comment by wenottingham** [comment]
See AWX_ANSIBLE_CALLBACK_PLUGINS in settings. We cannot directly do an override via ANSIBLE_CALLBACK_WHITELIST due to how AWX needs to run its own callback.
