### ISSUE TITLE
Ansible Tower working with AWS services

### ISSUE THREAD

**Issue by dhikrahashim** [ansible/awx#7890]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY

I am trying to run a playbook from ansible tower to fetch all the listed host zone from the aws r53. We are using assume role and we have allowed ansible tower instance to fetch data from other AWS accounts.

 statement = {
    sid    = "AnsibleInventoryPermissions"
    effect = "Allow"

    actions = [
      "ec2:Describe*",
      "route53:ListHostedZones",
      "route53:ListResourceRecordSets",
      "rds:Describe*",
      "elasticache:Describe*"
    ]

    resources = [
      "*",
    ]
  }
} 
##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### ADDITIONAL INFORMATION

Playbook I used

---
- name: Route53 entry lists
  hosts: localhost
  gather_facts: true
  connection: local
  tasks:
  - name: List all hosted zones
    route53_info:
      query: hosted_zone
    register: record_sets
  - name: PRINT OUT RECORD SETS
    debug:
      var: record_sets

**Comment by ryanpetrello** [comment]
Hey @dhikrahashim,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by dhikrahashim** [comment]
If the question related to Tower then where I need to ?

**Comment by ryanpetrello** [comment]
Hey @dhikrahashim,

If you have questions about how to use and operate Ansible Tower, you'll have to reach out to Red Hat support services - this issue tracker is for the upstream open source AWX project.
