### ISSUE TITLE
missed button save when select webhook credential

### ISSUE THREAD

**Issue by Kiviby** [ansible/awx#7892]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

when setting up a new webhook and selecting a credential there is no way to confirm the credential selection

##### ENVIRONMENT
* AWX version: 14.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.11
* Operating System: RHEL 7.8
* Web Browser: Chrome, Firefox

##### STEPS TO REPRODUCE

create new gitlab personal access token credential
configure job template to use webhook.
attempt to select previously created credential in the webhook credential field

##### EXPECTED RESULTS

select button visible to select the credential

##### ACTUAL RESULTS
list of credentials displayed with no way to select the credential 

##### ADDITIONAL INFORMATION

![missed_save](https://user-images.githubusercontent.com/69573805/90012961-03d58800-dcad-11ea-880a-ad67179e9666.PNG)

**Comment by jakemcdermott** [comment]
most likely related to latest version bump of jquery & other dependencies. See fixes for similar issues: https://github.com/ansible/awx/pull/7553

**Comment by Kiviby** [comment]
in awx 13.0.0.  same problem  #7441

**Comment by jakemcdermott** [comment]
Note to anyone who works on this: removing any self-closing tags found in the following code will probably fix this bug so try that first:

[workflow-add.controller.js#L129-L158](https://github.com/ansible/awx/blob/devel/awx/ui/client/src/templates/workflows/add-workflow/workflow-add.controller.js#L129-L158)
[workflow-edit.controller.js#L168-L197](https://github.com/ansible/awx/blob/devel/awx/ui/client/src/templates/workflows/edit-workflow/workflow-edit.controller.js#L168-L197)
[job-template-add.controller.js#L111-L140](https://github.com/ansible/awx/blob/devel/awx/ui/client/src/templates/job_templates/add-job-template/job-template-add.controller.js#L111-L140)
[job-template-edit.controller.js#L161-L189](https://github.com/ansible/awx/blob/devel/awx/ui/client/src/templates/job_templates/edit-job-template/job-template-edit.controller.js#L161-L189)

See  #7553 for example of fixes for similar issues

**Comment by tobgen** [comment]
Version 14.1.0 and 15.0.0 is affected by this as well.

**Comment by DejfCold** [comment]
@tobgen The change was merged the day (1 oct) after the tag was created (30 sept) - #8304

**Comment by unlikelyzero** [comment]
PIpelines are borked due to galaxy. Will test next week

**Comment by unlikelyzero** [comment]
Covered in job-template-operations.spec.js
