### ISSUE TITLE
.gitignore-list files not found

### ISSUE THREAD

**Issue by DySprozin** [ansible/awx#7898]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Not found files from git project, which added manualy

##### ENVIRONMENT
* AWX version: 14.0.0
* AWX install method:  docker on linux
* Ansible version:  2.9.11
* Operating System: Ubuntu 16.04
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

Create gitlab project. Git pull. Create manualy file in the .gitignore directory (ex. /data/awx/projects/_19__gitlab_system/roles/test/files/test.txt). Run playbook:

```
- name: list files
  local_action: command ls -Ra ./
  register: zzz

- name: debug
  debug:
    msg: "{{zzz.stdout_lines}}"
```

##### EXPECTED RESULTS

output list files, including file test.txt

##### ACTUAL RESULTS

output list files, EXcluding file test.txt (list git files only, except manually added files)

##### ADDITIONAL INFORMATION

I dont want to store role folder /files/ in the git, any solutions?

**Comment by wenottingham** [comment]
This is (generally) a consequence of what you see in https://github.com/ansible/awx/issues/7897.

If it's about the roles thesmelves, I would use roles from git, or collections from galaxy/hub.
If it's about data files the roles use, I would use some sort of artifact/file storage and pull them as needed in the playbook.

AWX is designed so playbook runs are as stateless as possible, as they could be assigned to arbitrary execution nodes, spawned in a container platform, and more. We can't rely on manual edits to checked out source control.
