### ISSUE TITLE
Add UI support for management jobs in workflows

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#790]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
The UI allows 3 types of templates in workflows, this issue is to add the option to add system job templates.

##### ADDITIONAL INFORMATION

Creating a break-off issue from #779.

The API for doing this works fine. You can add a System Job Template to a workflow, and also specify `extra_vars`, which are needed for many of them.

The difficult determination that needs to be made is how the UI would present the options for the extra_vars that go into the system job without making it way too complicated.

**Comment by mabashian** [comment]
Exposing system jobs in that list would be trivial.  We'd just need to tweak the GET request to include system jobs in addition to job templates and workflows.  There'd be some other UX considerations for sure like adding a S icon like the P (project), I (inventory) and W (workflow) icons that we currently have.

As Alan pointed out, the tricky part would be exposing the form fields:

<img width="1366" alt="screen shot 2018-11-26 at 3 16 09 pm" src="https://user-images.githubusercontent.com/9889020/49039606-416b4800-f18e-11e8-8c3a-e3685ed93019.png">

in the workflow node form.  We could potentially leverage the PROMPT modal for this and make them required fields.  Alternatively we could just expose those fields under the list when a system job is selected.

**Comment by wenottingham** [comment]
At some point I think system jobs should probably be a real project with real survey specs, etc. But that's probably an unpleasant migration.

**Comment by tiagodread** [comment]
This was added by #10572
