### ISSUE TITLE
Configure Organization Admins to not be able to rename organizations

### ISSUE THREAD

**Issue by davidtluong** [ansible/awx#7902]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Currently, organization admins can rename an organization.  However, if the organization was created by an LDAP or SAML configuration, this leads to the proliferation of organizations.  Organization Admins should NOT be able to rename organizations, or this should at least be configurable.

**Comment by ffirg** [comment]
Thank you for the suggestion, but this isn't something we'll be taking forward. Having sub-levels of capabilities for an Admin would horribly complicate the RBAC model.
