### ISSUE TITLE
Why is the variable not defined when passing variables in source variables for a dynamic inventory?

### ISSUE THREAD

**Issue by IlyaNakhaichuk** [ansible/awx#7913]
i add parameter "with_tags: True" to awx ui in source variables, but when looking at host parameters, i don't see tags showing up.
 
You can achieve the appearance of tags only by changing the file /var/lib/awx/vendor/inventory_collections/ansible_collections/community/vmware/plugins/inventory/vmware_vm_inventory.py, replacing with_tags = self.get_option ('with_tags') with with_tags ="True".

Why can't I override the with_tags parameter from False to True through source variables?

**Comment by wenottingham** [comment]
-> #7715
