### ISSUE TITLE
Error Handling for Prompt on Launch

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#7914]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When a user lauches a template that uses Prompt on Launch, and that action throws a content error.

##### ENVIRONMENT
* AWX version: 11.2
* AWX install method:docker for mac
* Ansible version:  2.9.10
* Operating System:Mojave
* Web Browser:Chrome

##### STEPS TO REPRODUCE
Find a job template that has a Prompt on Launch item.  Click the launch button but force it to throw a content error.

##### EXPECTED RESULTS
The content error is displayed in a modal/wizard because the POL is a wizard

##### ACTUAL RESULTS
It shows the error on the screen, details/list view

##### ADDITIONAL INFORMATION
See copy button (https://github.com/ansible/awx/tree/devel/awx/ui_next/src/components/CopyButton) or Ad Hoc Commands for examples on how to handle this error

![Screen Shot 2020-08-17 at 9 51 02 AM](https://user-images.githubusercontent.com/39280967/90404943-1830d080-e071-11ea-9513-9639063b36f3.png)
![Screen Shot 2020-08-17 at 9 52 04 AM](https://user-images.githubusercontent.com/39280967/90404944-18c96700-e071-11ea-84d9-ff90ff192f9f.png)

**Comment by unlikelyzero** [comment]
will cover in https://github.com/ansible/awx/issues/8788

**Comment by mabashian** [comment]
So much has changed with launch prompting.  I tried this out by forcing an error and this is what it looks like now:

<img width="1666" alt="Screen Shot 2021-02-04 at 11 07 19 AM" src="https://user-images.githubusercontent.com/9889020/106920584-3d75d180-66d9-11eb-9753-b80d5261c953.png">

**Comment by unlikelyzero** [comment]
No unit test coverage added.

QE will add coverage for this case as 'medium' priority

**Comment by unlikelyzero** [comment]
@AlexSCorey @mabashian can you give us a working example of how to reproduce this problem?

**Comment by akus062381** [comment]
@AlexSCorey can you please help me with this? I am unable to reproduce.

**Comment by AlexSCorey** [comment]
@akus062381 @unlikelyzero I believe this issue has been resolved. Based on my testing just now, and Mike's image above it have been resolved.  I am closing this now.
