### ISSUE TITLE
Host facts do not render properly when viewed unless interacted with

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#7915]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
See https://github.com/ansible/awx/issues/5907#issuecomment-607394959

Decided to make this issue to track this specific bug so that we can close #5907

**Comment by mabashian** [comment]
@unlikelyzero I tested this one out locally and the facts seem to be displaying properly for me.  I'm going to move this to needs_test for now.

**Comment by unlikelyzero** [comment]
Since we're about to reimplement codemirror, let's retest this at that time.

**Comment by unlikelyzero** [comment]
@keithjgrant assigning to you to address in the ace editor work

**Comment by keithjgrant** [comment]
@unlikelyzero as far as I can tell, this is no longer an issue with the new code editor. Can you confirm?
