### ISSUE TITLE
LDAPError while authenticating user

### ISSUE THREAD

**Issue by ghost** [ansible/awx#7923]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Ansible AWX won't connect to LDAP server over port 389.

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker on linux
* Ansible version: 2.9.10
* Operating System: 8.2.2004
* Web Browser: Firefox 79.0

##### STEPS TO REPRODUCE

Settings > Authentication > LDAP

LDAP SERVER URI
ldap://fqdn.company.com:389

LDAP BIND DN
`CN=<snip>,OU=<snip>,OU=<snip>,OU=<snip>,OU=<snip>,DC=<snip>,DC=<snip>`

LDAP BIND PASSWORD
`<snip>`

LDAP GROUP TYPE
ActiveDirectoryGroupType

LDAP REQUIRE GROUP
`CN=<snip>,OU=<snip>,OU=<snip>,OU=<snip>,OU=<snip>,DC=<snip>,DC=<snip>`

LDAP START TLS
Disabled

LDAP USER SEARCH
```
[
 "DC=<snip>,DC=<snip>",
 "SCOPE_SUBTREE",
 "(sAMAccountName=%(user)s)"
]
```

LDAP GROUP SEARCH
```
[
 "DC=<snip>,DC=<snip>",
 "SCOPE_SUBTREE",
 "(objectClass=group)"
]
```

LDAP USER ATTRIBUTE MAP
```
{
 "first_name": "givenName",
 "last_name": "sn",
 "email": "mail"
}

```
##### EXPECTED RESULTS

Login to Ansible AWX web UI using AD user account successfully.

##### ACTUAL RESULTS

Cannot login to Ansible AWX web UI using AD user account. Results in the following error:

`Invalid username and/or password. Please try again.`

##### ADDITIONAL INFORMATION

2020-08-18 04:13:07,212 WARNING  django_auth_ldap Caught LDAPError while authenticating `<user>`: SERVER_DOWN({'desc': "Can't contact LDAP server"},)
2020-08-18 04:13:07,338 WARNING  awx.api.generics Login failed for user `<user>` from `<IP>`
2020-08-18 04:13:07,480 WARNING  django.request Unauthorized: /api/login/
2020-08-18 04:13:07,480 WARNING  django.request Unauthorized: /api/login/

Note: running the following directly on the Ansible server CLI is successful:

`ldapsearch -x  -H ldap://fqdn.company.com:389 -D "CN=<snip>,OU=<snip>,OU=<snip>,OU=<snip>,OU=<snip>,DC=<snip>,DC=<snip>" -w <snip> -b "DC=<snip>,DC=<snip>"
`

**Comment by smaksimus** [comment]
Just to add Ansible AWX had HTTPS (SSL from CA) enabled during installation. Could that be having an impact?

**Comment by wenottingham** [comment]
Yes, it's likely something to do with how it's verifying the cert for your LDAP server.

You'll want to configure it with AUTH_LDAP_GLOBAL_OPTIONS and similar items.  https://django-auth-ldap.readthedocs.io/en/latest/reference.html#auth-ldap-global-options

**Comment by smaksimus** [comment]
I've re-installed my instance of Ansible and without HTTPS and the LDAP issue still persists.

**Comment by wenottingham** [comment]
It's not about HTTPS, it's about the SSL/TLS connection from AWX to LDAP.

See https://github.com/ansible/awx/issues/411 for some examples (either setting LDAP options, or passing a cert bundle into the deployment.

At this point I do not think this is an issue with AWX itself - if you have issues with the solutions above, it's probably best to start on the mailing list or IRC channel - see https://github.com/ansible/awx#get-involved for details.

**Comment by smaksimus** [comment]
> 
> 
> It's not about HTTPS, it's about the SSL/TLS connection from AWX to LDAP.
> 
> See #411 for some examples (either setting LDAP options, or passing a cert bundle into the deployment.
> 
> At this point I do not think this is an issue with AWX itself - if you have issues with the solutions above, it's probably best to start on the mailing list or IRC channel - see https://github.com/ansible/awx#get-involved for details.

Except SSL/TLS has not been configured anywhere. Same exact issue on fresh installation on CentOS 7.8.2003, identical configuration without certs/SSL/TLS/etc.
