### ISSUE TITLE
tower_project should not check for credentials on state=absent

### ISSUE THREAD

**Issue by DLV111** [ansible/awx#7924]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
awx.awx.tower_project checks for credential on state == absent, and it shouldn't care if we're removing it (eg credential gets removed before this is called)

##### ENVIRONMENT
* AWX version: 3.7.1
* AWX install method: Ansible Tower 3.7.1 - setup.sh
* Ansible version:  2.9.1
* Operating System: Red Hat 7.9
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create a project with a credential
Remove the credential before removing the project

##### EXPECTED RESULTS

Project should be removed

##### ACTUAL RESULTS

Error is received when trying to remove it.
fatal: [awx-node01]: FAILED! => {"changed": false, "msg": "The credentials git_creds was not found on the Tower server"}

**Comment by masbahnana** [comment]
I tested this using this playbook 
```- hosts: localhost
  collections:
    - awx.awx
  vars:
    prefix: natalia
    proj_name: "{{ prefix }}_project"
    organization_name: "{{ prefix }}_org"
  tasks:
    - name: Create "{{ organization_name }}"
      tower_organization:
        name: "{{ organization_name }}"
    - name: a scm cred
      tower_credential:
        name: project_cred
        credential_type: "Source Control"
        organization: "{{ organization_name }}"
        inputs:
          username: foo
          password: foo
    - name: Create "{{ proj_name }}"
      tower_project:
        name: "{{ proj_name }}"
        credential: project_cred
        organization: "{{ organization_name }}"
        scm_type: git
        scm_url: https://github.com/ansible/test-playbooks.git
    - name: Delete "{{ proj_name }}"
      tower_project:
        name: "{{ proj_name }}"
        organization: "{{ organization_name }}"
        state: absent
```

everything works and you can delete project :D
