### ISSUE TITLE
AnsibleTower integration with 3rd party ITSM tool

### ISSUE THREAD

**Issue by Aniket-Utekar** [ansible/awx#7928]
##### ISSUE TYPE
 - Feature Idea
-- AWX to ITSM Tools integration using oAUTH Token Base

##### SUMMARY

1.  How we can integrate ITSM tools like serviceNow with AWX tower.
-- I am able to integrate servicenow to AWX via oAUTH.
-- But through AWX to serviceNow i am not able to integrate with oAUTH .. Only able to use basic authencation mechanism to integrate.

So is it possible to integrate AWX Tower to Servicenow with oAUTH 2.0 token base. ?
If yes what parameters we need to have in playbooks ?

**Comment by wenottingham** [comment]
Hi -

This repository is specifically for bug reports with AWX. This looks like a usage question, and is therefore better targeted at the mailing list or IRC channel. Please see https://github.com/ansible/awx#get-involved for details.
