### ISSUE TITLE
Expose `Authentication` sub category in UI

### ISSUE THREAD

**Issue by jangsutsr** [ansible/awx#793]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
`/api/v2/settings/authentication/` is a valid API endpoint for general authentication settings like auth token timeout, and will be the place for the coming session and OAuth settings. It would be better that UI exposes them.

**Comment by jaredevantabor** [comment]
@jlmitch5 is this still in progress?

**Comment by rooftopcellist** [comment]
Link: https://github.com/ansible/tower/issues/1976
