### ISSUE TITLE
Deprecate mercurial support

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#7932]
##### ISSUE TYPE
 - Deprecation

Mark mercurial project updates as deprecated, to be removed in a future release

##### SUMMARY

Warning should probably be displayed during project updates of mercurial sourced projects, not sure where else

**Comment by AlanCoding** [comment]
Just add 1 task here to warn:

https://github.com/ansible/awx/blob/devel/awx/playbooks/project_update_hg_tasks.yml

I'm not sure exactly what task to use for this... but presumably anything could work.

**Comment by ryanpetrello** [comment]
cc @tvo318

**Comment by kdelee** [comment]
LGTM, thanks!
