### ISSUE TITLE
[ui next] Advanced Search on modals have a few issues

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#7938]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
If an Advanced Search option is available on modals, it does not render well with the narrow width of the modal.
1. The elements in an advanced search are pushed off screen
2. The Kebab is triggered by is not used
3. Z-depth of dropdown for keyfields is not observed. Obscured by modal footer

##### ENVIRONMENT
* Operating System: MacOS 10.15.5
* Web Browser: Chrome 83

##### STEPS TO REPRODUCE
1. Find a modal which can contain an advanced search i.e. External Secret Management System
2. Use advanced search options to construct a query
Note: elements pushed outside of modal and kebab action is triggered
Note: dropdown element for lookup type is rendered below modal footer

##### EXPECTED RESULTS
1. All advanced search options to be visible and accessible
2. Kebab element to only be present when useful.

##### ACTUAL RESULTS
1. Advanced search elements pushed outside of modal
2. Empty Kebab

##### ADDITIONAL INFORMATION

![Screen Shot 2020-08-19 at 12 51 30 PM](https://user-images.githubusercontent.com/12446869/90665948-ba3fec80-e21a-11ea-83a6-7341dc8acc34.png)

![Screen Shot 2020-08-19 at 2 02 54 PM](https://user-images.githubusercontent.com/12446869/90673125-3fc89a00-e225-11ea-9d2b-2e6411d008a0.png)

**Comment by tiagodread** [comment]
The same problem happens outside a modal if your screen resolution is less than `1723px`:

![image](https://user-images.githubusercontent.com/12464858/91353472-b1728c00-e7c1-11ea-908e-8bcbacc46c22.png)

**Comment by AlexSCorey** [comment]
Tool bar going off the screen on a list view.
![Screen Shot 2020-11-02 at 11 21 47 AM](https://user-images.githubusercontent.com/39280967/97892142-a5450680-1cfd-11eb-9805-ea817e097bd6.png)
