### ISSUE TITLE
[ui next] Double error text if attempting to edit credential type

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#7939]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When attempting to edit a credential type, the form error handling will display two errors.

##### STEPS TO REPRODUCE
1. Create a 'Machine' type credential "A"
2. Create a custom credential type "Custom"
3. Modify the credential type of "A" to use "Custom"

##### EXPECTED RESULTS
A single error messages
Error text in Red

##### ACTUAL RESULTS
Two error messages
One error text in black

##### ADDITIONAL INFORMATION
![Screen Shot 2020-08-19 at 12 54 47 PM](https://user-images.githubusercontent.com/12446869/90666557-9204bd80-e21b-11ea-8414-489a8ccec011.png)

**Comment by mabashian** [comment]
<img width="1420" alt="Screen Shot 2020-11-16 at 4 51 35 PM" src="https://user-images.githubusercontent.com/9889020/99312404-01df1000-282c-11eb-9179-ad1cac7264d1.png">

**Comment by mabashian** [comment]
@unlikelyzero this looks like it was fixed.

**Comment by unlikelyzero** [comment]
this is covered in https://github.com/ansible/tower-qa/blob/devel/ui-tests/awx-pf-tests/cypress/visualintegration/credentials.spec.js
