### ISSUE TITLE
responsiveness of toolbar in modals with advanced search doesn't work great

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#7941]
this should probably wrap in a pretty way

![Screen Shot 2020-08-19 at 12 44 13 PM](https://user-images.githubusercontent.com/1342624/90667948-4fdc7b80-e21d-11ea-8f93-0c4b444430b6.png)

**Comment by unlikelyzero** [comment]
closing as a dupe of https://github.com/ansible/awx/issues/7938
