### ISSUE TITLE
Strip out failed hosts/allow successful hosts to proceed between workflow node steps

### ISSUE THREAD

**Issue by gforster** [ansible/awx#7953]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Would benefit greatly from the ability to "split" the current inventory to allow successful hosts to proceed and send failed hosts in their own direction. Currently, if one host fails on a single task, all hosts fail during that step. The best current workaround (that I can figure) is to add an approval node on failure and either manually remediate the failed hosts or disable them from the inventory and then approve the workflow moving on. 

The idea could be extended further to be able to proceed with various subsets of the inventory - say running against a group in a node and only proceeding with those that have no changes (All OK) or stripping out the unreachable ones or whatever else. Again, potentially sending them along different workflow paths.  

Use cases: Remediating existing servers, patching, decomissioning servers in "bad" states, etc.

**Comment by wenottingham** [comment]
-> #7198
