### ISSUE TITLE
Add Remote Archive SCM Type to support using artifacts and releases as projects

### ISSUE THREAD

**Issue by philipsd6** [ansible/awx#7954]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Our development teams use a software development lifecycle process that builds a versioned artifact for the final product. This process has been extended to the development of Ansible projects, which include the roles, modules, plugins, and playbooks required for the project's goals. The build process produces an immutable artifact in [Artifactory](https://jfrog.com/artifactory/), and our users need to be able to pull that artifact into AWX instead of pulling it from the git repository used in development. 

A generic feature to pull archives from a remote URL would fill this use case, as well as other use cases, such as [GitHub Releases](https://github.com/philipsd6/test-playbook/releases)

From the UI perspective, all that is necessary for this SCM type is the SCM URL field, as there is no generic concept of branch/ref spec/version for artifact URLs. 

To kick off this discussion, PR #7911 implements the feature as I envision it for general use.

**Comment by philipsd6** [comment]
@jakemcdermott if you let me know where I can add documentation for this new feature, I will be happy to write it up.

**Comment by unlikelyzero** [comment]
To test:

- Add new Project with Remote Archive type
- Perform project sync successfully
- Remove artifact (or reference a missing artifact version) and verify that project sync is not successful and contains helpful error text

**Comment by dsesami** [comment]
This has been tested and is functional -- there is a small follow-up issue about tooltips which will be filed separately. This tooltip should have a black background like other tooltips, and the links should maybe be formatted.

![Screenshot from 2020-09-14 15-46-02](https://user-images.githubusercontent.com/19942822/93132949-75399980-f6a4-11ea-8a65-6228c5a4ab00.png)
