### ISSUE TITLE
Add/Edit container group

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#7955]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add/Edit container group.

See: https://tower-mockups.testing.ansible.com/patternfly/instance-groups/instance-groups-container-add/

**Comment by nixocio** [comment]
I ended up working in adding/editing a container group at the same time, since they are highly coupled - sharing the same form.

**Comment by mabashian** [comment]
@nixocio is this issue still valid?  I see that #8070 has merged.  Should this be closed?

**Comment by nixocio** [comment]
@mabashian, @dsesami verified this one. Can we close this one @dsesami?

**Comment by dsesami** [comment]
This was captured within the scope of other verification and was stubbed out etc., this is good to close.
