### ISSUE TITLE
limiting the jobs running on the same host 

### ISSUE THREAD

**Issue by binbinhui** [ansible/awx#7968]
How can I limit the jobs running on the same host?  I have two templates running on the different jobs and both running on the same host. Both templates are trigger by the pull requests from the git repo, if template A is running,  someone do a pull request in git repo for templates B. Both templates will run at the same time in the same host. Templates A will get fail because template B overwrites the job in the templates A. How can I set if template A is running, Template B will be in waiting mode. Once A finishes then B will start. Thanks

**Comment by wenottingham** [comment]
This is not a feature of AWX. If you have conflicts in resources used in different playbooks, you will need to reorganize your playbooks in order to avoid the conflict. 

For a single template, disabling `allow_simultaneous` will handle this.
