### ISSUE TITLE
Missing requests-credssp pyhton module in awx docker container

### ISSUE THREAD

**Issue by damhau** [ansible/awx#797]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Credssp

##### SUMMARY
Missing requests-credssp pyhton module in awx docker container

##### ENVIRONMENT
* AWX version: 1.0.1 (not sure)
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: CentOS Linux release 7.4.1708
* Web Browser: Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)

##### STEPS TO REPRODUCE
Try to connect to a windows host with credssp by setting "ansible_winrm_transport: credssp"

##### EXPECTED RESULTS
Login to windows remote management with provided user account

##### ACTUAL RESULTS
Error about missing requests-credssp

##### ADDITIONAL INFORMATION
Solved by doing the following:

docker exec -it awx_task bash
. /var/lib/awx/venv/ansible/bin/activate
pip install requests-credssp

**Comment by matburt** [comment]
glad you could work it out.
