### ISSUE TITLE
Inventory Host Facts display strange loading behavior

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#7977]
**expected behavior**
The details should appear loading until the data request resolves.

**actual behavior**
The fact component displays momentarily, disappears, then shows again when the request resolves.

**additional information**
![host_facts_load1](https://user-images.githubusercontent.com/9753817/91073160-a0cae600-e608-11ea-8936-a4d7d110413f.gif)

**Comment by dsesami** [comment]
This appears to simply no longer flicker. :100:
