### ISSUE TITLE
Make it possible to automate AWX deployment

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#799]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - Installer

##### SUMMARY
It would be really nice to make it possible to add more steps to installation that could be automated, right now I can preconfigure admin password etc but I would like to automate more steps in AWX installation:

* Preconfigure organization
* Preconfigure inventory scripts and inventories
* Preconfigure authentication over LDAP
* Preconfigure projects

etc...

Right now probably only solution would be to create awx template VM and fork it

**Comment by wenottingham** [comment]
That is what https://github.com/ansible/tower-cli (and the corresponding ansible modules) are for.

**Comment by benapetr** [comment]
@wenottingham how about mentioning this somewhere, so that people don't have to create similar issues?

It's nowhere to find in documentation for AWX (which pretty much boils down to its readme right now)

**Comment by wenottingham** [comment]
It's mentioned in the Tower documentation (while admittedly not the AWX documentation, it's what we do point to currently from a user's guide standpoint).  We're looking in the next few months to update the Ansible modules to more clearly state they're for both AWX and Tower.
