### ISSUE TITLE
[ui_next] Jobs list does not indicate whether or not the timestamp is a start time or end time

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#7995]
This is notably present in both the main jobs list and the Instance Groups -> Jobs tab, but is likely present everywhere the jobs list is reused. Originally identified within https://github.com/ansible/awx/issues/7930

![Screenshot from 2020-08-25 15-38-48](https://user-images.githubusercontent.com/19942822/91219712-160de800-e6e9-11ea-834e-55ac0b31bddf.png)

The timestamp used on these jobs (example is `8/25/2020`) has no indication of whether or not it is a start or finish time. This can be confusing for users. This should be refactored to either show start AND finish time, or label the timestamp.

**Comment by mabashian** [comment]
#6189

**Comment by unlikelyzero** [comment]
closing to test in #6189
