### ISSUE TITLE
User type auditor can't see Job template details

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#7996]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
As an auditor user I can't see the details from a specific job template because I don't have permission for that

##### ENVIRONMENT
* AWX version: 14.0.0
* AWX install method: docker for mac
* Ansible version:  2.9.11
* Operating System: macOs
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Logged in as an Auditor User:

1. Navigate to templates
2. Select a template

##### EXPECTED RESULTS

The auditor user should be able to see everything about the job template.

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/12464858/91220372-72c1d080-e6f2-11ea-8a47-dd590067f8ee.png)

**Comment by mabashian** [comment]
@tiagodread @unlikelyzero tested this one out locally and was no longer able to reproduce:

<img width="1477" alt="Screen Shot 2020-11-23 at 3 11 01 PM" src="https://user-images.githubusercontent.com/9889020/100010356-25f79f80-2d9e-11eb-921c-082dee10ad30.png">

I think that request noted in the error was being erroneously made.  I don't see that request being made anymore.

**Comment by tiagodread** [comment]
> @tiagodread @unlikelyzero tested this one out locally and was no longer able to reproduce:
> 
> <img alt="Screen Shot 2020-11-23 at 3 11 01 PM" width="1477" src="https://user-images.githubusercontent.com/9889020/100010356-25f79f80-2d9e-11eb-921c-082dee10ad30.png">
> 
> I think that request noted in the error was being erroneously made. I don't see that request being made anymore.

Yeah, I also was unable to reproduce this one, I think we can safely close it too.

**Comment by unlikelyzero** [comment]
@tiagodread can you verify that we do have coverage for this one

**Comment by tiagodread** [comment]
@unlikelyzero Yes, we cover this in auditor-journey.spec.js
