### ISSUE TITLE
Create tower_application module

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#8010]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Per PR #7963 we are missing a module to interact with the applications endpoint

**Comment by john-westcott-iv** [comment]
Started in https://github.com/ansible/awx/pull/7845

**Comment by john-westcott-iv** [comment]
Resolved by #8205

**Comment by appuk** [comment]
I used the tower_application module to create, update and delete an application, and everything seems working.

@john-westcott-iv Although while using the module, client_type and authorization_grant_type fields were required, and the docs had no mention of that. do you have any idea why is that and if it needs change in the docs?

**Comment by ryanpetrello** [comment]
@beeankha or @john-westcott-iv can one of you take a peek at this as you have available time?

**Comment by jbradberry** [comment]
I've just taken a peek at this, and see that those two fields are required fields on the model.

https://github.com/ansible/awx/blob/a7a3609e48eab7faf9e5968f43321234dc1d70fa/awx/main/models/oauth.py#L74-L87

The docs definitely should be updated to reflect that.

**Comment by ryanpetrello** [comment]
@jbradberry pointed out that these maybe shouldn't actually be required (what if you pass `state:absent`?)

cc @appuk

**Comment by kdelee** [comment]
Thats what we were wondering.

Maybe we could use the `description` field to say they are required for creation.

**Comment by ryanpetrello** [comment]
@kdelee unless you all feel strongly, I'm gonna vote for "meh".  If you don't specify these args for create, does it give you some reasonable/discernable error message?

**Comment by ryanpetrello** [comment]
```
TASK [tower_application : Fail to create an application] ***********************
fatal: [testhost]: FAILED! => {"changed": false, "msg": "Unable to create application AWX-Collection-tests-tower_application-app4-DMbVfwBWmgcDgzDH: {'client_type': ['This field is required.'], 'authorization_grant_type': ['This field is required.']}"}
```

Yea, this is a bug 'ol "meh" from me.

**Comment by appuk** [comment]
@ryanpetrello yes it does give an error message, we can close this out! 👍

**Comment by ryanpetrello** [comment]
Thanks @appuk!
