### ISSUE TITLE
Create a tower_instance_group module

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#8011]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Per PR #7963 we are missing a module to interact with the instance_groups endpoint

**Comment by appuk** [comment]
@beeankha I was able to create and edit an instance group using this module, but when I tried to delete the object using `state: absent`, it did not delete the instance group, and the task passed as ok

**Comment by ryanpetrello** [comment]
@beeankha or @john-westcott-iv can one of you take a peek at this as you have available time?

**Comment by jbradberry** [comment]
After taking a quick look at the merged PR, it looks to me as if the problem is a minor typo, `if state is 'absent'` instead of `if state == 'absent'`.

**Comment by ryanpetrello** [comment]
@appuk can you give this another try?

**Comment by appuk** [comment]
The instance group is deleted on stating `state: absent`, Hence closing!
