### ISSUE TITLE
AWX not updating or showing the new playbooks added to the git repository

### ISSUE THREAD

**Issue by AnishAnil** [ansible/awx#8018]
##### ISSUE TYPE
 AWX not updating or showing the new playbooks added to the git repository

##### SUMMARY

AWX not updating or showing the new playbooks added to the git repository. 

I have AWX installed on Ubuntu using a docker compose on AWS EC2 Instance and is working as expected and able to login to AWX. Initially we started saving the playbooks on instances using the "machine" option but then faced the issue where the playbooks were not updated. Eventually googling, i found that the playbooks needs to exist on both the containers or should be in a shared volume else we will see similar issues and the alternate recommended option was to store them in a git repository.
Since we didn't want to overdo it, we choose to use SCM as an option.

**First Time:**

- We have added the playbooks into the git repo --> public 
- Create the Inventory add the hosts 
- Create Project choose SCM and provided the credentials and also the giturl for fetching the playbooks.
- Create a template and then choose the appropriate playbook and save
- Press the golden "Rocket" and the playbook is executed on the host.

Now comes the issue:

- Edit the playbook in the git repo and add new tasks to the existing playbook. 
- commit and push into git 
- These tasks are not listed in the current playbook existing already on AWX --> BAsicall AWX is not refreshed with the new contents added in the playbook.
- Create a new playbook and even that does not come up in the template section to run them

**Workaround:** 
Delete the Project and the template
Create a new one and everything seems to work seamlessly with the new updated file and contents until we edit the playbook or add new playbooks.

Bootlenecks:

We are integrating AWX job template with our Server for remediation jobs and the template -id cannot be changed often,
Now everytime, i delete and recreate the project and the template a new ID is created. 
Template_ID which needs to get updated in our system else the integration fails.

##### ENVIRONMENT
* AWX version:  AWX 14.0.0
* AWX install method: docker on ubuntu, -->Using Docker Compose on Ubuntu
* Ansible version:  Ansible 2.9.11
* Operating System: Ubuntu 18.04
* Web Browser: Chrome/Firefox

##### STEPS TO REPRODUCE

	Install AWX on Ubuntu using Docker compose
	create a git repo and add one playbook
	login to AWX
	create a inventory and add a host
	create a project --> with SCM
	create a template and choose the playbook
	Run it
	ensure it is successful
	edit the playbook in git repo with new tasks  or add a new plabook to the git repo and commit it
	check the playbook on AWX, it is not updated with the new contents

##### EXPECTED RESULTS

The new playbooks should be listed automatically or the contents of it should be updated and a delete and recreate should not be the intended action

##### ACTUAL RESULTS

The new playbooks added to the git repo is not refreshed on AWX on the browser.
The existing playbook does not show the new contents

CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                  NAMES
1025b62598f2        ansible/awx:14.0.0   "tini -- /usr/bin/la…"   2 days ago          Up 2 days           8052/tcp               awx_task
3f43d3674024        ansible/awx:14.0.0   "tini -- /bin/sh -c …"   2 days ago          Up 2 days           0.0.0.0:80->8052/tcp   awx_web
eb14301ea455        postgres:10          "docker-entrypoint.s…"   2 days ago          Up 2 days           5432/tcp               awx_postgres
458068c5dac0        redis                "docker-entrypoint.s…"   2 days ago          Up 2 days           6379/tcp               awx_redis

**Comment by wenottingham** [comment]
> Edit the playbook in the git repo and add new tasks to the existing playbook.
> commit and push into git
> These tasks are not listed in the current playbook existing already on AWX --> BAsicall AWX is not refreshed with the new contents added in the playbook.

You need to update the project after adding new playbooks to the repo. You can do this on a schedule if you like

In any case, this is a usage issue. This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by jshirley-incomm-zz** [comment]
I was able to get the updated Playbook from Git to show in Ansible after I deleted the Project and started over, once you save it and add a new job to it you should see your playbook populate, hope this helps

**Comment by NikhilMasur** [comment]
you need to go to the Inventory select Sources option and then click on sync option below to fetch your project changes from git repository to Ansible Tower/AAP
