### ISSUE TITLE
Update Facts with package_facts

### ISSUE THREAD

**Issue by gforster** [ansible/awx#8025]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

running the `package_facts` module on a given host does not update the facts for that host.

Unsure, but this might be applicable to other `*_facts` modules like `ios_facts` as well.

**Comment by wenottingham** [comment]
When you mean 'the facts for that host', do you mean the fact cache when fact caching is enabled, or just variables/facts used by the playbook?

**Comment by gforster** [comment]
Sorry for the confusion, @wenottingham . I do mean the fact cache when fact caching is enabled (persistent beyond the playbook run).

**Comment by blomquisg** [comment]
@jbradberry can you see if you can reproduce this?

**Comment by jbradberry** [comment]
Setting up a project that consists only of the following playbook, test.yml:

    ---
    - hosts: all
      tasks:
        - name: Ping
          ping:
            data: pong

        - name: Gather the package facts
          package_facts:
            manager: apt

I get a successful job run like so using the latest on devel,

![Screenshot_2020-10-13 Ansible AWX 5 - Test Fact Cache](https://user-images.githubusercontent.com/685957/95904159-1def1d80-0d65-11eb-8715-4af53df369a7.png)

and facts in the cache like so,

![Screenshot_2020-10-13 Ansible AWX FACTS](https://user-images.githubusercontent.com/685957/95904187-26475880-0d65-11eb-8543-2d89e6793554.png)

So, I am unable to reproduce.

**Comment by ryanpetrello** [comment]
I also am having trouble reproducing this on the latest AWX:

![image](https://user-images.githubusercontent.com/214912/96607528-732bb180-12c6-11eb-9c40-62e272fd18f7.png)

![image](https://user-images.githubusercontent.com/214912/96607558-7888fc00-12c6-11eb-8d34-cde7980391cf.png)

![image](https://user-images.githubusercontent.com/214912/96607611-83dc2780-12c6-11eb-9d8e-d287aa738bc1.png)

![image](https://user-images.githubusercontent.com/214912/96607671-93f40700-12c6-11eb-839c-315fe9064b22.png)

**Comment by dberardo-com** [comment]
related to this issue. is it possible to cache package_facts and execute the check with/without cache conditionally? that would speed up plays
