### ISSUE TITLE
AWX Email Notification Not Working 

### ISSUE THREAD

**Issue by gp185132-ncr** [ansible/awx#8026]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Hi ,

Iam new to AWX , and iam trying to send an Email Notification on state success of my Job Template which takes Backup of Configuration in a Device .
The Job template is running fine with success but the Email Notification is not being generated on success .
I would like to confirm on below Necessary parameters (*) while configuring Email type Notifcation
What should be given in below parameters :-
HOST:- Is it the Host/Server where AWX GUI is installed or some other host?
PORT :- is it the Port of AWX GUI which is 80/443 or is it Mail Client/SMTP port and what port number ?
SENDER EMAIL :- is it my user made on AWX GUI server or from root user ?

Note ;- AWX has been installed as root user.

![EMAIL_Notification](https://user-images.githubusercontent.com/70205964/91454237-5bbfe180-e89e-11ea-814b-c949f706cfe8.JPG)

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method:docker on linux
* Ansible version:  2.9.11
* Operating System: Oracle Linux Server release 7.5
* Web Browser: Chrome

##### EXPECTED RESULTS

Email Notification should be send on success Job execution.

##### ACTUAL RESULTS

Job is running fine , but Email Notification is not going.

**Comment by wenottingham** [comment]
This is a user question about how to set up the notifications (you need to set details for your mail server).

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
