### ISSUE TITLE
Add expand to variable fields

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#8031]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add feature to expand variables fields.

As an example, in the classic ui.

![expand](https://user-images.githubusercontent.com/9053044/91487714-30c49600-e87c-11ea-844d-475204355895.gif)

**Comment by nixocio** [comment]
Not sure if copy data should be added as well.

**Comment by akus062381** [comment]
still waiting for development

**Comment by mabashian** [comment]
@keithjgrant

**Comment by unlikelyzero** [comment]
This has been added with coverage
