### ISSUE TITLE
Per Job Template Job Retention for Cleanup Management Jobs

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/awx#8032]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

The feature should allow all jobs related to specified job template be exempt from the removal of job history in Ansible Tower.

**Comment by TheRealHaoLiu** [comment]
This is currently not possible after after we moved to partitioned tables for job events. A separate partition is created for each hour. There is no performant method of querying these tables for a specific job, and reworking that system would be quite an undertaking.
