### ISSUE TITLE
Ability to create a Custom Credential script

### ISSUE THREAD

**Issue by p-avery** [ansible/awx#8042]
##### ISSUE TYPE
 - Feature Idea
Ability to create a Custom Credential Script

##### SUMMARY

Just as we have the ability to create a custom inventory script, it would be beneficial have the ability to create custom credential plugin scripts, then we can add credential plugins to other credential stores that are not in the pre packaged list.

**Comment by wenottingham** [comment]
This wouldn't be done in this way - storing code in a database is the wrong way to go (and completely fails in case of it having dependencies).

We've already deprecated custom inventory scripts in the db, and that feature will be removed. For custom credential types, just install the plugin alongside the others. See https://github.com/ansible/awx-custom-credential-plugin-example#awx-custom-credential-plugin-example for installation details.
