### ISSUE TITLE
Inventory Source form's 'Inventory file' dropdown is deselected during Edit

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8044]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Inventory Source form's 'Inventory file' dropdown is deselected during Edit. Previous option is not selected and form cannot be saved.

##### ENVIRONMENT
* AWX version: 40603c213af13ed40b7268aa6bd7f660fab3c112

##### STEPS TO REPRODUCE
1. Navigate to Inventory Source page
2. Edit existing Inventory Source
Note: 'Inventory file' select dropdown is deselected and form cannot be saved without modification.

##### EXPECTED RESULTS
Edit an Inventory Source form keeps the previous 'Inventory file' selected

##### ACTUAL RESULTS
'Inventory file' select dropdown is deselected and form cannot be saved without modification.

**Comment by tiagodread** [comment]
Test covered by 5587 👍🏽
