### ISSUE TITLE
User type auditor can try to edit a Workflow template

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#8052]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
As an auditor user I can try to edit a workflow template on visualizer graph
See: https://github.com/ansible/awx/issues/7663

##### ENVIRONMENT
* AWX version: 14.0.0
* AWX install method: docker for mac
* Ansible version:  2.9.11
* Operating System: Mojave
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Logged in as an Auditor User:

1. Navigate to Templates
2. Select a Workflow template
3. Navigate to Visualizer tab

##### EXPECTED RESULTS

The user shouldn’t be able to edit a workflow template

##### ACTUAL RESULTS

The user can try to add nodes to workflows, but clicking on `Save` button the request response is 403 forbidden

##### ADDITIONAL INFORMATION

![workflow-templates](https://user-images.githubusercontent.com/12464858/91861635-6fbf6680-ec43-11ea-9f6d-db4bd5c8a707.gif)

**Comment by mabashian** [comment]
Note that the user actually shouldn't see a START button in the above GIF.  I've fixed that in #8055.

**Comment by tiagodread** [comment]
Test stubs written and PR already merged.
