### ISSUE TITLE
Websocket output page doesn't always properly update

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#8053]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I don't know if this only happens with "problematic" adhoc jobs or for all jobs (I tried this with an ad hoc command on @AlexSCorey 's branch with a malformed command, but sometimes the websocket updates don't seem to come through properly. I also don't think this is related to that PR.

Try these steps:
1. Launch a job that's going to fail for some reason.
2. Sit on the output page where you can see the ansible output.

It doesn't seem to always update. The final "failure" result would only occur if I refreshed -- otherwise it would eternally sit in progress. Also, sometimes only the small sparkline box would turn red, but the large bar that is on top of the output would not turn red until I refreshed.

As you can see here, the in progress box is visible and the bar is gray, as if the job was still moving, but the job has already been done for a while and won't update until it's refreshed:
![Screenshot from 2020-09-01 11-29-34](https://user-images.githubusercontent.com/19942822/91872979-84e9c480-ec46-11ea-8bbe-b0922668fee7.png)

**Comment by jakemcdermott** [comment]
related & possibly overlaps w/ some work done for: https://github.com/ansible/awx/pull/7940

**Comment by mabashian** [comment]
A _lot_ has changed since this issue was opened.  #9208 includes a refactor under the hood from a class based component to a functional component.  It's possible this issue still exists but I think this should be re-tested as there's a very good chance it's been fixed.

**Comment by unlikelyzero** [comment]
This will need to be tested within https://github.com/ansible/awx/pull/9208

**Comment by akus062381** [comment]
this has been fixed.
