### ISSUE TITLE
Ansible v2.5 with cdrom support in vmware_guest support in AWX?

### ISSUE THREAD

**Issue by jariley** [ansible/awx#806]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

I did a fresh install of AWX on 12/7/17 and I am receiving "Unsupported parameters for (vmware_guest) module: cdrom" when I attempt to utilize this new parameter that was supposed to be implemented in Ansible 2.5 via the ansible fix #21112. Is Ansible 2.5 not getting bundled into the AWX container, or is there an issue with this enhancement?

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: docker on linux
* Ansible version:  X.Y.Z
* Operating System: RHEL 7
* Web Browser:

**Comment by wenottingham** [comment]
Ansible 2.5 has not been released yet, it would not be pulled in before it's released.
