### ISSUE TITLE
Advanced search on tokens does not function

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#8062]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The user is presented a localized version of the time of expiration when visiting the Tokens tab for a specific user.

For example, the UI might display this information:
> Expires 1/4/3020, 10:08:49 AM

But the API provides this information:
> `expires: "3020-01-04T15:08:49.497519Z"`

This is converted by the UI using `Date().toLocaleString()`. If the user provides a localized string, like 1/4/3020, the advanced search returns a 400. It also seems to 400 with different substrings of the ISO-formatted string copied from the API, so it doesn't really work at all. This should be double-checked with all API values that use Date() items.

#### STEPS TO REPRODUCE
1. Create a user
2. Assign that user a few tokens
3. View the `Expires` value of the tokens, then try to perform some advanced searches on the `expires` value

**Comment by mabashian** [comment]
I don't consider this to be a bug at all.  The filter works as long as the user provides the string as it's represented in the db:

<img width="1478" alt="Screen Shot 2021-02-03 at 12 04 53 PM" src="https://user-images.githubusercontent.com/9889020/106782428-24591c00-6618-11eb-8558-3d39ef46fe7c.png">

I think what Danny was asking for was a more user friendly way to provide a date in the search.  This would be a non-trivial task and would require a lot of thought and documentation.

**Comment by nixocio** [comment]
There is another issue to track the advanced search for dates. Closing this one.
