### ISSUE TITLE
Inventory Sync websocket event does not update workflow node status indicator when finished

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8063]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Inventory Sync websocket event does not update sparkline element when finished.

##### ENVIRONMENT
* AWX version: 77b1afe6fd7299c9fa764cd04f62a1afd73159f9

##### STEPS TO REPRODUCE
1. Create an Inventory Sync
2. Launch Inventory Sync via WFJT or within Inventories Relaunch Job tab
Note: Job status ends but sparkline element never finishes

##### EXPECTED RESULTS
Job finishes and Inventory Sync element updates

##### ACTUAL RESULTS
Job starts, element updates to match the running state but does not updated after inventory sync job finishes

##### ADDITIONAL INFORMATION
![inventory_sync_never_finish](https://user-images.githubusercontent.com/12446869/92022828-de76ef80-ed29-11ea-9c1b-82e1fdedde55.gif)

**Comment by mabashian** [comment]
@tiagodread not able to reproduce this one on my end.  This issue is ~9 months old and might have been fixed somewhere along the way.

**Comment by tiagodread** [comment]
I was not able to reproduce this bug anymore.
