### ISSUE TITLE
PRoot inside container

### ISSUE THREAD

**Issue by keilr** [ansible/awx#8067]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Is this comment still valid?
https://github.com/ansible/awx/blob/77b1afe6fd7299c9fa764cd04f62a1afd73159f9/installer/roles/image_build/files/settings.py#L25-L26

Is there a way to activate PRoot inside containers in the meantime?

cc @matburt

**Comment by matburt** [comment]
This is a legacy property that comes from how Tower/AWX uses process isolation. At one time it used proot before switching to bwrap. The property here is still used even if its name doesn't identify the correct technology that it uses.

**Comment by keilr** [comment]
@matburt thank you for the answer. Why not enabling it for the docker compose install scenario? Bubblewrap seems to work after enabling privileged mode for the awx_task container.
