### ISSUE TITLE
Add details page for container groups

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#8073]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add details page for container groups

**Comment by nixocio** [comment]
@unlikelyzero, can we close this one?

**Comment by unlikelyzero** [comment]
@nixocio we will not be in the critical path for EE but will still be in the critical path for Container Groups. In this case, Danny didn't link to the tests which covered this functionality nor the PR which was in progress. We will leave this post-merge needs_test issue up to ensure that we had and have adequate coverage.

For now, our priority will remain the open awx pulls and get back to these post-merge needs_test issues

**Comment by nixocio** [comment]
Thanks @unlikelyzero.

**Comment by tiagodread** [comment]
Covered by:
- container-group-crud.spec.js
- container-group-operations.spec.js
- container-group-tabs.spec.js

Closing this issue.
