### ISSUE TITLE
LIMIT value as input for callback plugin

### ISSUE THREAD

**Issue by jerryhwg** [ansible/awx#8079]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

https://docs.ansible.com/ansible/latest/plugins/callback.html

In ansible-playbook command line, run like
```
ansible-playbook worker.yml --extra-vars "host_limit=linux1"
```
I can make a callback plugin to retrieve a variable like this way and use the returned value.
```
vm = play.get_variable_manager()
self.hosts = vm.extra_vars["host_limit"]
```
We prefer to use **LIMIT** option for the ansible target hosts in AWX.

A callback plugin can retrieve the value of LIMIT and use the returned value as an input string for callback operation.

**Comment by ryanpetrello** [comment]
Hey @jerryhwg,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, the best place is the mailing list:

https://groups.google.com/d/msgid/awx-project/6842913a-d6ef-4582-a42d-d4217b14dcccn%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by jerryhwg** [comment]
> Hey @jerryhwg,
> 
> This issue tracker is for tracking feature enhancements and bugs to AWX itself.
> 
> If you need help troubleshooting an AWX install, the best place is the mailing list:
> 
> https://groups.google.com/d/msgid/awx-project/6842913a-d6ef-4582-a42d-d4217b14dcccn%40googlegroups.com?utm_medium=email&utm_source=footer

Okay, btw, do you mean it's possible, so I need to find a way how to do it thru troubleshooting?
