### ISSUE TITLE
Clarify inventory vs. inventory source in inventory update detail view

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#808]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
The UI for inventory update page is confusing regarding its source inventory & inventory source

##### STEPS TO REPRODUCE

Navigate to inventory update detail page in the UI, like

`http://myserver.invalid:8013/#/inventory_sync/1083`

##### EXPECTED RESULTS

Coherent links to the inventory, as well as the inventory source that it came from, or some other disambiguation thereof.

##### ACTUAL RESULTS

![screen shot 2017-12-12 at 4 17 52 pm](https://user-images.githubusercontent.com/1385596/33909051-535ef064-df58-11e7-9a59-fed219856ea2.png)

NAME links to inventory source.

Not obvious what "NAME" is - name of what? Name of inventory, inventory source, or inventory update.

Suggested:

 - INVENTORY: foo inventory (linked, i.e. `/#/inventories/inventory/8`)
 - SOURCE: fetch foobar (linked, i.e. `/#/inventories/inventory/8/inventory_sources/edit/29`)

##### ADDITIONAL INFORMATION

API PR https://github.com/ansible/awx/pull/807 names the inventory updates based on a combination of the inventory & inventory source (applies to list view in UI). This will still lead to a confusing situation if the UI continues to link to the inventory source with no other information.

**Comment by wenottingham** [comment]
See also https://github.com/ansible/awx/issues/1216

**Comment by AlanCoding** [comment]
the NAME entry is no longer present, and looking at the entire UI for this page, the link confusion is now resolved.
