### ISSUE TITLE
increase verbosity in workflow approval window

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#8085]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Customer request: 

> We have multiple approval generated for multiple workflows and many times for same workflow. It is very difficult for users to identify that this approval is for which user and what is the job id of this approval. We have to open each and every workflow and then figure out job id and then decide which to approve or reject. 

Adding additional information to the approval window itself would help alleviate this hurdle where approval nodes are heavily utilized.

**Comment by wenottingham** [comment]
What version? We added additional details in AWX 11.2.

**Comment by msilmser** [comment]
Customer issue was opened against Tower 3.7.0

**Comment by unlikelyzero** [comment]
@msilmser @wenottingham this is available and tested in awx 16.0.0

**Comment by unlikelyzero** [comment]
filed as https://github.com/ansible/awx/issues/7112
