### ISSUE TITLE
Align details in User List

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#8086]
- Bug Report

##### SUMMARY
User list page is displaying data in the following format.

<img width="1480" alt="image" src="https://user-images.githubusercontent.com/9053044/92254563-15badd00-ee9f-11ea-8690-2f3e82b633da.png">

**Comment by mabashian** [comment]
This also gets addressed if/when we move to tables so I'm inclined to mark this as blocked so that it doesn't get worked until tables are situated.

link https://github.com/ansible/awx/issues/6189

**Comment by unlikelyzero** [comment]
closing to address in https://github.com/ansible/awx/issues/6189
