### ISSUE TITLE
List jobs related to container groups

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#8091]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
List Jobs related to container groups.

**Comment by dsesami** [comment]
see https://github.com/ansible/awx/pull/8070#issuecomment-690260512 -- this will be followed up on soon.

**Comment by dsesami** [comment]
Jobs that are already complete can still be canceled, which seems like a bug. This interaction (similar to the select -> delete flow) seems odd for a cancel operation. should this be a one-click ⛔ symbol like elsewhere when canceling jobs, and not require two clicks?

**Comment by dsesami** [comment]
This issue is split out to https://github.com/ansible/awx/issues/8207. Once automation is in place for this issue, it can be closed.

**Comment by dsesami** [comment]
automation for this is in instance-groups/container-group-tabs.spec
