### ISSUE TITLE
tower_credential module does not support hashivault_ssh

### ISSUE THREAD

**Issue by haribhauhud** [ansible/awx#8095]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Ansible tower_credential module does not support "HashiCorp Vault Signed SSH" credential.
![image](https://user-images.githubusercontent.com/55002070/92494154-fa3f3180-f212-11ea-883c-80c56da3458a.png)

**Comment by blomquisg** [comment]
@codersplanet are you using the module from the AWX collection?

**Comment by haribhauhud** [comment]
> @codersplanet are you using the module from the AWX collection?

No @blomquisg
