### ISSUE TITLE
Inventory does not update host list if sources are deleted

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#8098]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Essentially, if you launch a template with an inventory that was synced with a source, and then delete that source, the inventory then cannot be synced and becomes "stale".

It should be noted that deleting an inventory source deletes its respective hosts automatically in the old UI. 

##### STEPS TO REPRODUCE
1. Create a job template, WFJT, whatever can utilize a specific inventory.
2. In the inventory, add a source from the Sources tab > using ansible/test-playbooks > from Project root > something like "Create 10 hosts" as your initialization file.
3. Sync the source so 10 hosts appear. these are blank hosts, so they won't work.
4. Launch a job. As expected, it fails as it cannot connect to blank hosts.
5. Go back to the inventory and delete the bad inventory source.
6. Go back to the job and try to launch it again.

##### EXPECTED RESULTS
There is some way to update/re-sync the inventory automatically so it only uses the default localhost host and passes, after the inventory source with the empty hosts is deleted.

##### ACTUAL RESULTS
The host list cannot be re-synced as a whole, and the empty hosts are "stale" and stay. They can be manually deleted from the Inventory > Hosts tab, but this seems non-ideal. The old UI deletes this automatically.

**Comment by nixocio** [comment]
In order to recreate this issue.

Go to`Inventories>{anyInventory}Sources>Create new source`.

Create a source inventory which related project contains a file like, `foo.ini`:

```
host1
host2
host3
host4
host5
host6
host7
host8
host9
host10

```

**Comment by mabashian** [comment]
@unlikelyzero moving this to needs_test since #8519 has merged.  Feel free to close if you already have coverage.

**Comment by unlikelyzero** [comment]
closing with https://github.com/ansible/awx/pull/8519#pullrequestreview-530295121
