### ISSUE TITLE
Inventory sources cannot be scheduled

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#810]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
inventory sources cannot be scheduled

##### ENVIRONMENT
* AWX version: 1.0.1-319
* AWX install method: docker for mac
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

POST to `/api/v2/inventory_sources/N/schedules/`

```json
{"name":"asdf","rrule":"DTSTART:20171104T040000Z RRULE:FREQ=DAILY;INTERVAL=1;COUNT=1"}
```

##### EXPECTED RESULTS

creates schedule

##### ACTUAL RESULTS

400

```json
{
    "_exclude_errors": [
        "Field is not allowed on launch."
    ]
}
```

**Comment by jakemcdermott** [comment]
👍

**Comment by pjmcquade** [comment]
Has this been resolved?  I see this occuring for me:

Ansible Tower v3.4.2
Core:
ansible 2.7.8
  config file = /home/a769/.ansible.cfg
  configured module search path = [u'/home/a769/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

----

Trying to run this:

tower-cli schedule create --name "test-schedule" --inventory-source "test-source" --enabled true --inventory "test-inventory" --rrule "DTSTART;TZID=America/Toronto:20190318T000000 RRULE:FREQ=HOURLY;INTERVAL=1" --force-on-exists

yields:

Params: None
Data: {"enabled": true, "unified_job_template": 128, "inventory": 42, "rrule": "DTSTART;TZID=America/Toronto:20190318T000000 RRULE:FREQ=HOURLY;INTERVAL=1", "name": "test-schedule"}

Response: {"inventory":["Field is not allowed on launch."]}

Any ideas?

**Comment by sugitk** [comment]
@pjmcquade  I also reproduced the issue.

**Comment by AlanCoding** [comment]
That's not the same error, it is trying to tell you that `--inventory "test-inventory"` is not something you and provide for that job template because it has not set `ask_inventory_on_launch`.

**Comment by AlanCoding** [comment]
wait, inventory sources cannot do that. So inventory update schedules just never take the inventory parameter. Inventory sources are tired to the inventory they are part of. There is no need to specify that inventory a second time when creating a schedule.
