### ISSUE TITLE
CA provided certificate not working.

### ISSUE THREAD

**Issue by gp185132-ncr** [ansible/awx#8115]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Iam trying to run AWX as https for which our CA has provided .cer file which I put in my inventory file for awx along with .key file in below two parameters 
ssl_certificate=/u000/awx/certs/rpc12639.cer
ssl_certificate_key=/u000/awx/certs/rpc12639.key

Post saving and try running installation again of awx , when i can see port mapping being formed as below for awx_web container :-

CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                                         NAMES
f9faaafdfdfe        ansible/awx:14.0.0   "tini -- /usr/bin/la…"   31 minutes ago      Up 31 minutes       8052/tcp                                      awx_task
02023cef4cb4        ansible/awx:14.0.0   "tini -- /bin/sh -c …"   31 minutes ago      Up 31 minutes       0.0.0.0:80->8052/tcp, 0.0.0.0:443->8053/tcp   awx_web

But when i hit URL :-  https://rpc12639.corp.ncr.com:443 , Its saying me that the page doesn't exist . What other changes i need to do in order to make AWX work on https? I even tried changing format .cer to .crt tht didn't work.

##### ENVIRONMENT
* AWX version: 14.0.0.
* AWX install method:  docker on linux
* Ansible version:  2.9.10
* Operating System: Oracle Red Hat linux
* Web Browser: Chrome 

##### STEPS TO REPRODUCE

1. Generate a .csr file and .key . and CA will provide .cer file for that .csr file.
2. add the .key and .cer file in awx inventory file under attributes :- ssl_certificate and ssl_certificate_key.
3. install AWX .
4. check the url 

##### EXPECTED RESULTS

able to open AWX login page on https:443

##### ACTUAL RESULTS
URL not opening . THis site can't be reached.

**Comment by gp185132-ncr** [comment]
Hi All ,

Could you please help here in this issue for AWX?

**Comment by ryanpetrello** [comment]
Hey @gp21081994,

If you're just asking for debugging help or technical support, you might get a faster response at:

- http://webchat.freenode.net/?channels=ansible-awx
- https://groups.google.com/forum/#!forum/awx-project

We generally limit this issue tracker to tracking verified bugs or feature enhancements due to limited volunteer time to respond to troubleshoot installs.
