### ISSUE TITLE
The work template is scheduled according to the week, and problems can occur

### ISSUE THREAD

**Issue by thisID** [ansible/awx#8117]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

I created a working template and set it up for execution every Monday night at 23:00。
The work template is scheduled according to the week, and problems can occur，
If according to the time, day, month, year, then there is no problem。
##### ENVIRONMENT
* AWX version: 13
* AWX install method:  docker on linux
* Ansible version:  2.9.10
* Operating System: Red Hat Enterprise Linux server release 7.2(Maipo)
* Web Browser: cheom

##### STEPS TO REPRODUCE

I created a working template and set it up for execution every Monday night at 23:00，The following problem occurs。
![image](https://user-images.githubusercontent.com/23741243/92696369-57a2c200-f37c-11ea-8c27-8ae45a608825.png)

##### EXPECTED RESULTS

When I re-enter the Settings, this is what I see。I waited a long time, and the interface stayed like that。
![image](https://user-images.githubusercontent.com/23741243/92696145-0c88af00-f37c-11ea-880c-267bf6c98c93.png)

**Comment by ryanpetrello** [comment]
@mabashian @jakemcdermott any ideas here?

**Comment by wenottingham** [comment]
Is this fixed with the jquery update in 14?

**Comment by mabashian** [comment]
@thisID any chance you could provide us a screenshot of the browsers console when you navigate to this page.  I suspect the error there will help explain what's going on.

**Comment by thisID** [comment]
> @thisID，当您导航到此页面时，有机会向我们提供浏览器控制台的屏幕截图。我怀疑那里的错误将有助于解释发生了什么。

![image](https://user-images.githubusercontent.com/23741243/93040163-e6b12200-f67b-11ea-8e14-473a6296dad9.png)
![image](https://user-images.githubusercontent.com/23741243/93040168-eb75d600-f67b-11ea-9b49-f58ffbe9e844.png)

**Comment by thisID** [comment]
> @thisID，当您导航到此页面时，有机会向我们提供浏览器控制台的屏幕截图。我怀疑那里的错误将有助于解释发生了什么。

![image](https://user-images.githubusercontent.com/23741243/93040452-a3a37e80-f67c-11ea-8891-5f8fa51f0188.png)
![image](https://user-images.githubusercontent.com/23741243/93040463-a7cf9c00-f67c-11ea-81e5-fc27acb1265a.png)

**Comment by wenottingham** [comment]
Can you try this on 14.x?

**Comment by blomquisg** [comment]
@thisID try this out on the newest version of AWX and let us know if you have the same problem.
