### ISSUE TITLE
Downloading the log of job result in "Not found."

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#812]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
When you click download icon for log you are redirected to some JSON document that only say:

{"detail":"Not found."}

##### ENVIRONMENT
* AWX version: 1.0.1 (master has same problem)
* AWX install method:  docker on linux
* Ansible version:  X.Y.Z
* Operating System: RedHat
* Web Browser: firefox

##### STEPS TO REPRODUCE
Just try to download a log

##### EXPECTED RESULTS

Log will downolad

##### ACTUAL RESULTS
Log doesn't download

**Comment by goranvrbaski** [comment]
I can confirm this issue. Same behaviour on my instance of awx.

**Comment by matburt** [comment]
This will be covered here: https://github.com/ansible/awx/issues/200
