### ISSUE TITLE
WFJT Details link is broken

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#8124]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The OPTIONS call on workflow job templates is broken, so you cannot view the details of any WFJT.

##### STEPS TO REPRODUCE
1. Make a WFJT and try to view it.

##### EXPECTED RESULTS
You can see it.
##### ACTUAL RESULTS

There is a double slash in the OPTIONS call, resulting in a 404.
``` OPTIONS /api/v2/workflow_job_templates//8/ 404```

We should make a test for creating a WFJT and viewing the details before closing this.

**Comment by dsesami** [comment]
https://github.com/ansible/awx/pull/8125

**Comment by mabashian** [comment]
As far as I can tell #8125 addresses this so I moved this into in_progress

**Comment by dsesami** [comment]
fixed with the merge of #8125
