### ISSUE TITLE
Include documentation with installation for configurations isolated from the internet

### ISSUE THREAD

**Issue by mrmibrown** [ansible/awx#8128]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Request to include documentation with each installation, ideal for configurations isolated from the internet.  

"I have Tower in a Air-Gapped network and the documentation would be very helpful to have on the tower server

This is the most important material I am looking for right now:
https://docs.ansible.com/ansible/2.8/modules/modules_by_category.html

the documentation that I am seeking is for Tower 3.5.2, Ansible 2.8.2"

**Comment by wenottingham** [comment]
This isn't relevant to upstream AWX.
