### ISSUE TITLE
Question: What's the minimum permission required for users to see the "copy button" on the "Job Template"?

### ISSUE THREAD

**Issue by pan3793** [ansible/awx#8137]
##### ISSUE TYPE

 - Question

##### SUMMARY

What's the minimum permission required for users to see the "copy button" on the "Job Template"?

A normal user who is granted to create/edit/delete job templates, but can't copy it, which make no sense. 

After several attempts to adjust the permissions, we found that only the system administrator can see the "copy button" on the Templates page.

##### ENVIRONMENT
* AWX version: 12.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.9
* Operating System: CentOS 7
* Web Browser: Chrome

**Comment by jakemcdermott** [comment]
Hello,

It depends on the job template. To copy a job template, you need to have sufficient permissions to create a new job template with _all_ of the related fields currently on that job template. This means that insufficient permissions on a related item (e.g its project or one of its credentials) could could make it so you can't copy that job template.

Check that you can create / edit all of the related items on that JT. If you feel like you're encountering a bug in that you should be able to copy a JT but can't, please open a new bug report issue with exact steps to reproduce the bug from a clean system (include all objects created, input values used, etc.) and we will take a look.

If you still have questions about awx usage, please reach out to our community mailing list or irc channel:
- https://groups.google.com/forum/#!forum/awx-project
- http://webchat.freenode.net/?channels=ansible-awx
