### ISSUE TITLE
Build AWX on RHEL7 Docker Image

### ISSUE THREAD

**Issue by xoxys** [ansible/awx#814]
##### SUMMARY
I try to build AWX based on a RHEL7 Docker Image. Building the sdist image works well but i get some strange errors while building web image.

##### ENVIRONMENT
* AWX version: master
* AWX install method: linux
* Ansible version:  2.4.0
* Operating System: RHEL7
* Web Browser:

##### ACTUAL RESULTS
npm-debug.log
...
161795 error Linux 3.10.0-693.2.2.el7.x86_64
161796 error argv "/usr/bin/node" "/usr/bin/npm" "--unsafe-perm" "--prefix" "awx/ui" "install" "awx/ui"
161797 error node v6.12.0
161798 error npm  v3.10.10
161799 error code ELIFECYCLE
161800 error contextify@0.1.15 install: `node-gyp rebuild`
161800 error Exit status 1
161801 error Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
161801 error Make sure you have the latest version of node.js and npm installed.
161801 error If you do, this is most likely a problem with the contextify package,
161801 error not with npm itself.
161801 error Tell the author that this fails on your system:
161801 error     node-gyp rebuild
161801 error You can get information on how to open an issue for this project with:
161801 error     npm bugs contextify
161801 error Or if that isn't available, you can get their info via:
161801 error     npm owner ls contextify
161801 error There is likely additional logging output above.
161802 verbose exit [ 1, true ]

**Comment by matburt** [comment]
There's not really enough information here to help you. I think there is an npm log that's populated as part of the build.

Having said that, the official image is based on CentOS 7 and I don't see changing that here.
