### ISSUE TITLE
nginx upgrade 1.14 to 1.18

### ISSUE THREAD

**Issue by hemanth1989** [ansible/awx#8149]
My containers are running on nginx 1.14 which is outdated and want to upgrade to 1.18, but nginx is pre installed in a container and created a docker image using the container. And we are using that image for the awx.

Can someone please suggest the best way to upgrade the nginx.

**Comment by wenottingham** [comment]
You'd need to rebuild the container with an nginx package of your own.  See https://github.com/ansible/awx/blob/devel/INSTALL.md#official-vs-building-images and installer/roles/image_build.

Closing this issue - this issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by wenottingham** [comment]
Also don't literally post the same question to the issue tracker and the mailing list at the same time.
