### ISSUE TITLE
[ui_next] Enabling prompt on Launch on all options on JTs generates console error.

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8156]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
We had a patternfly dependency which generated some console errors. It's not clear if those were handled back in June when we upgraded to 4.0. Opening this as a separate issue to retest. https://github.com/ansible/awx/issues/5909#issuecomment-634904951

```Enabling pretty much all of the prompt on launch fields for the JT and setting default values for ALL of them gives me this error in the console when I hit launch and enter the launch wizard. ```

##### ENVIRONMENT
* AWX version: devel ~June

##### STEPS TO REPRODUCE
Enable Prompt on Launch fields for a JT / WFJT

##### EXPECTED RESULTS
No console errors

##### ACTUAL RESULTS
lots of console errors

##### ADDITIONAL INFORMATION
https://github.com/ansible/awx/issues/5909#issuecomment-634904951

https://github.com/patternfly/patternfly-react/issues/4134

**Comment by unlikelyzero** [comment]
@tiagodread @dsesami note: when we retest this, we should verify the behavior on all prompted forms / wizards. It's not 100% clear if upstream _actually_ solved this issue. https://github.com/patternfly/patternfly-react/issues/4134

**Comment by unlikelyzero** [comment]
May be related to https://github.com/ansible/awx/issues/6510

**Comment by dsesami** [comment]
console errors do not appear in the prompt on launch flow anymore. :+1:
