### ISSUE TITLE
awx collection tower_api lookup plugin: options are ignored

### ISSUE THREAD

**Issue by keilr** [ansible/awx#8157]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
awx.awx.tower_api plugin does not read the options

##### ENVIRONMENT
* AWX version: 14.1.0
* Ansible version:  2.9.9, 2.10.0rc1

##### STEPS TO REPRODUCE
```
$ cat playbook.yml 
- hosts: localhost
  tasks:
    - name: debug all organizations in a loop  # use query to return a list
      debug:
        msg: "Organization description={{ item['description'] }} id={{ item['id'] }}"
      loop: "{{ query('awx.awx.tower_api', 'organizations', host='example.com') }}"
      loop_control:
        label: "{{ item['name'] }}"


$ ansible-playbook playbook.yml 

PLAY [localhost] ********************************************************

TASK [Gathering Facts] **************************************************
ok: [localhost]

TASK [debug all organizations in a loop] ********************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'awx.awx.tower_api'. Error was a <class 'ansible.errors.AnsibleError'>, original message: There was an unknown error when trying to connect to https://127.0.0.1/api/v2/organizations/: URLError <urlopen error [Errno 111] Connection refused>"}
```

##### EXPECTED RESULTS

lookup plugin should query `example.com` instead of `127.0.0.1`

##### ACTUAL RESULTS

lookup plugin options are ignored

**Comment by keilr** [comment]
cc @john-westcott-iv @AlanCoding

**Comment by AlanCoding** [comment]
Is https://github.com/ansible/awx/pull/8159 addressing this?

**Comment by keilr** [comment]
Yes, that PR will fix it :) Thanks a lot for the info and for the fix! Will it makte it to the next ansible 2.10 rc release?

**Comment by nesanton** [comment]
The PR addresses it indeed: The options are now taken from the direct params.
But plugin still cannot fallback to environment vars or tower_cli config, like modules do. Can this be added cheaply?

**Comment by AlanCoding** [comment]
The config file is how we test these in integration tests like:

https://github.com/ansible/awx/blob/56c5a39087fdee71227e7f2c022d086fd4e47efa/awx_collection/tests/integration/targets/tower_lookup_api_plugin/tasks/main.yml#L53

Are you sure that the config file is not working right now? Do you have other env vars or something taking higher precedence?

**Comment by john-westcott-iv** [comment]
Are your config files on the tower control node? A plugin is executed there instead of on a target node.

**Comment by nesanton** [comment]
> The config file is how we test these in integration tests like:
> 
> https://github.com/ansible/awx/blob/56c5a39087fdee71227e7f2c022d086fd4e47efa/awx_collection/tests/integration/targets/tower_lookup_api_plugin/tasks/main.yml#L53
> 
> Are you sure that the config file is not working right now? Do you have other env vars or something taking higher precedence?

> Are your config files on the tower control node? A plugin is executed there instead of on a target node.

Indeed, I messed up my config while trying to make it work before the #8159.
Config works!

Yet, I cannot make it work with environment, which goes smooth for `tower_project` task in the same playbook

So, with empty config:

```yaml
- hosts: localhost
  gather_facts: false
  environment:
    TOWER_HOST: tower.example.org
    TOWER_USERNAME: username
    TOWER_PASSWORD: password
    TOWER_VERIFY_SSL: false
  tasks:

    # This works
    - awx.awx.tower_project:
        name: "Test Project"
        organization: "Default"
        
    # This fails trying to connect to 127.0.0.1.
    # If I provide, say, host and credential directly or in the config, it'll fail on self-signed cert, etc.
    - set_fact:
        tower_users: "{{ query('awx.awx.tower_api', 'users', query_params={}) }}"
```

**Comment by john-westcott-iv** [comment]
This is going to be related to how the environment and ansible work. 

From https://docs.ansible.com/ansible/latest/user_guide/playbooks_environment.html: `You can use the environment keyword at the play, block, or task level to set an environment variable for an action on a remote host`.

From https://docs.ansible.com/ansible/latest/plugins/lookup.html: `Like all templating, lookups execute and are evaluated on the Ansible control machine`.

Summarized, the environment setting within the playbook affects subsequent processes created by ansible (i.e. for an SSH connection to a client) and the lookup plugin runs under the current ansible process on the control node. Therefore your call to `awx.awx.tower_api` truly does not have the environment setup using this method. To prove this call your playbook after exporting environment variables in your shell. i.e.:
```
export TOWER_HOST=tower.example.org
export TOWER_USERNAME=username
export TOWER_PASSWORD=password
export TOWER_VERIFY_SSL=False
ansible-playbook my_playbook.yml
```
After doing this, the environment will be setup for the ansible process running on the control node and the plugin should now properly have access to them.

**Comment by nesanton** [comment]
Thanks @john-westcott-iv, it makes perfect sense now!
Hope this helps other confused souls like mine ;)

**Comment by squidboylan** [comment]
Closing this because a fix has been merged (along with tests)
