### ISSUE TITLE
The container awx-web take too much time to start listening on port 8052 when liveness and readiness probes are set

### ISSUE THREAD

**Issue by boutobza** [ansible/awx#8163]
##### SUMMARY

i' am trying to set liveness and readiness probes for my AWX but i am facing a issue with the time it takes the container awx_web to start listening on the port 8052 (about 5min) while without the probes the container starts listening on the designated port only after few seconds (10-15s)

Liveness & Readiness section in my deployment for the container awx_web

          ports:
          - name: http
            containerPort: 8052 # the port of the container awx_web
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8052
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8052
            initialDelaySeconds: 5
            periodSeconds: 5

##### ENVIRONMENT
* AWX version: 9.3.0
* AWX install method: kubernetes

**Comment by shanemcd** [comment]
Although this installer no longer exists, liveness probes are being added to awx-operator here: https://github.com/ansible/awx-operator/pull/1188
