### ISSUE TITLE
Implement Missing Swagger attributes to allow for Automatic Code Generation of Clientside SDKs

### ISSUE THREAD

**Issue by rorychatterton** [ansible/awx#8164]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Today the Swagger documentation for AWX is primarily used for the purposes of documentation of the API endpoints.

Swagger as a standard provides a powerful way for customers to generate client SDKs in the language of their choice. In my case, I'd like to use the generated swagger file with [Go Swagger](https://github.com/go-swagger/go-swagger) to generate an SDK for use in Terraform.

The current swagger documentation is missing key attributes to make this usable. The key limitation I have seen is that while parameter objects are well defined, response models are not. As a result, code generators aren't able to automate furling/unfurling of payload responses.

For Example, in the documentation of the applications API, the "examples" responses is given, showing the schema, while the "schema" model is missing. 
```json
"/api/v2/applications/": {
            "post": {
                "responses": {
                    "201": {
                        "description": "",
                        "examples": {
                            "application/json": {
                                "authorization_grant_type": "password",
                                "client_id": "xxxx",
                                 ... etc
                                    }
                                },
                            }
                        }
                    },
```

In other circumstances, the example and body is missing entirely, such as the get request of the same endpoint:
```json
"/api/v2/applications/": {
            "get": {
                "responses": {
                    "200": {
                        "description": ""
                    }
                },
```

The feature proposal is to:
- Update the swagger definition to embed the missing fields 

Additional enhancements could include:
- Providing a swagger.yml endpoint in the documentation for Ansible Tower rather than hardcoding it into the HTML docs
- Using the swagger.yml to run contract testing against the APIs to search for examples where API contracts are being broken between versions.

**Comment by f0rkz** [comment]
This would be an amazing feature!

**Comment by golimix** [comment]
api first program design not work well with the django model first

you can use the [swagger.yaml](https://github.com/go-limix/awx-client/blob/adf61f4e2171272be9235b5e7969734f8f706583/api/swagger.yaml)

**Comment by rorychatterton** [comment]
| API first program design not work well with the django model first

I'm not sure I understand what is meant by this. We aren't talking about API first with Django.

Thankyou for sharing the swagger file, unfortunately it has the same issue as described in this post (lack of response body), meaning it cannot be used for the use case I had originally intended (Writing a Terraform Provider to manage AWX Objects).

It looks like there isn't any appetite to fix this, and maybe a deeper issue around DRF + Annotation/Typehints as a dynamic language that make this more complex to solve. Closing this item as a number of 3rd party Terraform Providers now exist.
