### ISSUE TITLE
Permit variables at the Ansible Tower cluster level.

### ISSUE THREAD

**Issue by smatterchew** [ansible/awx#8170]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

We have multiple Ansible Tower clusters that support different requirements (regional/GBU/security context).  The plays we write often need to be aware of the cluster it is running from to make decisions or discover adjacent resources.  For instance, the host decom play needs to know which instance of Satellite/Spacewalk needs to be updated during the process.

I would like the ability to add variables at the cluster level that are folded in just like the inventory/group/host/etc variables are provided at runtime.

**Comment by ryanpetrello** [comment]
Hey @smatterchew,

This issue tracker is for the open source AWX project, not Red Hat's Ansible Tower product.  Please reach out to a Red Hat support representative about this request.
