### ISSUE TITLE
Add details page for Execution Environments

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#8171]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add details page for execution environments.

See: https://tower-mockups.testing.ansible.com/patternfly/exec-env/exec-env-detail/

**Comment by dsesami** [comment]
should this capitalize "Back to Execution Environments"? We capitalize this elsewhere:
![Screenshot from 2020-09-22 09-57-37](https://user-images.githubusercontent.com/19942822/93892142-2ef2c480-fcba-11ea-8a32-dfb5a3e52e03.png)
Templates is capitalized here:
![Screenshot from 2020-09-22 09-58-18](https://user-images.githubusercontent.com/19942822/93892152-31551e80-fcba-11ea-97cb-23ae48a9225e.png)

**Comment by dsesami** [comment]
based on feedback from https://github.com/ansible/awx/issues/7886#issuecomment-696769284, we should add organization info here.

**Comment by unlikelyzero** [comment]
closing as we will not be testing each of these tickets separately

**Comment by tiagodread** [comment]
We can close this when the awx and test PR land
