### ISSUE TITLE
How to load the default group_vars variables?

### ISSUE THREAD

**Issue by JamesYuan** [ansible/awx#8173]
##### ISSUE TYPE
It seems the awx cannot load the default group_vars variables even it is in the root directory of ansible project. Or am I wrong? Is there a setting?

Or not, whether it is possible link the "group_vars" as a symbol which will be in same directory of the awx "generated" inventory file?

Thank you.
James.

**Comment by wenottingham** [comment]
This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
