### ISSUE TITLE
Users can’t go to next field using TAB key after CodeMirror Field type

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#8176]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Trying to navigate using only the TAB key, when I try to go to the next field from a CodeMirror field isn’t possible.

##### ENVIRONMENT
* AWX version: 2.9.11
* AWX install method: docker for mac
* Ansible version:  14.1.0
* Operating System: Catalina
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Navigate to Job Templates
2. Click on Add button
3. Navigate through the fields using TAB key

##### EXPECTED RESULTS

The user can navigate through all fields using TAB key

##### ACTUAL RESULTS

Using TAB from the CodeMirror field just apply tab inside the code block.

##### ADDITIONAL INFORMATION

![chrome-capture (7)](https://user-images.githubusercontent.com/12464858/93602361-e759f900-f998-11ea-95b5-004fbb53fdf9.gif)

**Comment by keithjgrant** [comment]
This is a tricky problem... users need to be able to type a tab character, so I'm not sure there's a great solution. Maybe see if we can make Shift-Tab move to the next field? (assuming we can get that behavior in cooperation with the CodeMirror library).

…Unless we’re ok disallowing tabs in the codemirror altogether?

**Comment by mabashian** [comment]
Swapping needs_devel for needs_info on this one.  I don't think there's a clear solution to this problem.

**Comment by keithjgrant** [comment]
Fixed with the new code editor component. See #9281 for details on keyboard controls
