### ISSUE TITLE
Add Setting detail views 

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#8183]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Mockup: https://tower-mockups.testing.ansible.com/patternfly/settings/settings/

This issue tracks adding the Detail view to all setting views. 

* Setting content should be derived from the setting OPTIONS request
* Setting fields without a value should have a Detail value of "Unconfigured"
* Setting fields with sensitive information should have a Detail value of "Encrypted"

**RBAC**

* RBAC side-nav rules will be handled by this issue: https://github.com/ansible/awx/issues/4426 
* Only superusers and system auditors have permission to view settings
  * Redirect users without setting permissisons to home "/"
* Only superusers have permission to edit settings
  * If user is not a superuser, hide the edit button

**VIEWS**

- <a href="#user-content-activity-stream">Activity Stream</a>
- <a href="#user-content-azure">Azure AD</a>
- Github
    - <a href="#user-content-github-default">GitHub Default</a>
    - <a href="#user-content-github-organization">GitHub Organization</a>
    - <a href="#user-content-github-team">GitHub Team</a>
- <a href="#user-content-google">Google OAuth 2</a>
- <a href="#user-content-jobs">Jobs</a>
- LDAP
    - <a href="#user-content-ldap">Default</a>
    - LDAP 1
    - LDAP 2
    - LDAP 3
    - LDAP 4
    - LDAP 5
- <a href="#user-content-logging">Logging </a>
- <a href="#user-content-system">Miscellaneous </a>
- <a href="#user-content-radius">RADIUS </a>
- <a href="#user-content-saml">SAML </a>
- <a href="#user-content-tacacs">TACACS </a>
- <a href="#user-content-ui">User Interface</a>

<h2 id="activity-stream">Activity Stream</h2>

  * Enable Activity Stream
  * Enable Activity Stream for Inventory Sync

  
<h2 id="azure">Azure AD</h2>

  * Azure AD OAuth2 Callback URL
  * Azure AD OAuth2 Key
  * Azure AD OAuth2 Secret
  * Azure AD OAuth2 Organization Map
  * Azure AD OAuth2 Team Map

<h2 id="github-default">Github Default</h2>

  * GitHub OAuth2 Callback URL
  * GitHub OAuth2 Key
  * GitHub OAuth2 Secret
  * GitHub OAuth2 Organization Map
  * GitHub OAuth2 Team Map

<h2 id="github-organization">Github Organization</h2>

  * GitHub Organization OAuth2 Callback URL
  * GitHub Organization OAuth2 Key
  * GitHub Organization OAuth2 Secret
  * GitHub Organization Name 
  * GitHub OAuth2 Organization Map
  * GitHub OAuth2 Team Map

<h2 id="github-team">Github Team</h2>

  * GitHub Team OAuth2 Callback URL
  * GitHub Team OAuth2 Key
  * GitHub Team OAuth2 Secret
  * GitHub Team ID
  * GitHub Team OAuth2 Organization Map
  * GitHub Team OAuth2 Team Map

<h2 id="google">Google OAuth 2</h2>

  * Google OAuth2 Callback URL
  * Google OAuth2 Key
  * Google OAuth2 Secret
  * Google OAuth2 Whitelisted(?) Domains
  * Google OAuth2 Extra Arguments
  * Google OAuth2 Organization Map
  * Google OAuth2 Team Map

<h2 id="jobs">Jobs</h2>

  * Ansible Modules Allowed for Ad Hoc Jobs
  * Job execution path
  * Maximum Scheduled Jobs
  * Paths to expose to isolated jobs
  * Ansible Callback Plugins
  * Paths to hide from isolated jobs
  * Enable job isolation
  * Default Job Timeout
  * Default Inventory Update Timeout
  * Default Project Update Timeout
  * Per-Host Ansible Fact Cache Timeout
  * Maximum number of forks per job
  * Run Project Updates With Higher Verbosity
  * Enable Role Download
  * Enable Collection(s) Download
  * Follow symlinks
  * Isolated host key checking
  * Isolated status check interval
  * Isolated launch timeout
  * Isolated connection timeout
  * Enable detailed resource profiling on all playbook runs
  * Extra Environment Variables
  
<h2 id="ldap">LDAP Default</h2>

  * LDAP Server URI
  * LDAP Bind DN
  * LDAP Bind Password
  * LDAP User DN Template
  * LDAP Group Type
  * LDAP Require Group 
  * LDAP Deny Group
  * LDAP Start TLS
  * LDAP User Search
  * LDAP Group Search
  * LDAP User Attribute Map
  * LDAP Group Type Parameters
  * LDAP User Flags by Group
  * LDAP Organization Map
  * LDAP Team Map
 
<h2 id="logging">Logging</h2>

  * Enable external logging 
  * Logging aggregator
  * Logging aggregator port
  * Logging aggregator type
  * Logging aggregator username
  * Logging aggregator password/token
  * Loggers sending data to log aggregator form
  * Log system tracking facts individually
  * Logging aggregator protocol
  * TCP connection timeout
  * Logging aggregator level threshold
  * Enable/Disable HTTPS certificate verification
  
<h2 id="system">Miscellaneous System</h2>

  * Base URL of the Tower host
  * All Users Visible to Organization Admins
  * Organization Admins Can Manage Users and Teams
  * Idle Time Force Log Out
  * Maximum number of simultaneous logged in sessions
  * Enable HTTP Basic Auth
  * Allow External Users to Create OAuth2 Tokens
  * Login redirect override URL
  * Access Token Expiration (OAUTH2_PROVIDER)
  * Refresh Token Expiration (OAUTH2_PROVIDER)
  * Authorization Code Expiration (OAUTH2_PROVIDER)
  * Remote Host Headers
  * Custom virtual environment paths
  * Gather data for Automation Analytics
  * Red Hat customer username
  * Red Hat customer password
  * Automation Analytics upload URL
  * Automation Analytics Gather Interval
  
<h2 id="radius">RADIUS</h2>

  * Radius Server
  * Radius Port
  * Radius Secret
  
<h2 id="saml">SAML</h2>

  * SAML Assertion Consumer Service (ACS) URL
  * SAML Service Provider Metadata URL
  * SAML Service Provider Entity ID
  * SAML Service Provider Public Certificate
  * SAML Service Provider Private Key
  * SAML Service Provider Organization Info
  * SAML Service Provider Technical Contact
  * SAML Service Provider Support Contact
  * SAML Enabled Identity Providers
  * SAML Organization Map
  * SAML Organization Attribute Mapping
  * SAML Team Map
  * SAML Team Attribute Mapping
  * SAML Security Config
  * SAML Service Provider Extra Configuration Data
  * SAML IDP to extra_data attribute mapping
  
<h2 id="tacacs">TACACS</h2>

  * TACACS+ Server
  * TACACS+ Port
  * TACACS+ Secret
  * TACACS+ Auth Session Timeout
  * TACACS+ Authentication Protocol
  
<h2 id="ui">User Interface</h2>

  * User analytics tracking state
  * Custom logo
  * Custom logo info

**Comment by tiagodread** [comment]
Tests in place 👍🏽
