### ISSUE TITLE
CredentialLookup does not enforce required prop

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#8184]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
CredentialLookup does not enforce required prop

##### STEPS TO REPRODUCE
Go to any screen that uses the `CredentialLookup` component with `required` prop set, for instance, `https://localhost:3001/next/inventories/inventory/2/sources/add` and elect source `Ansible Tower`.
 Credential is required but no validation will be triggered if a credential is not provided.

For that particular case, the validation that we have in place is provided by the API.

![image](https://user-images.githubusercontent.com/9053044/93636285-a75b3c00-f9c1-11ea-9ba6-0a2015e9200c.png)

**Comment by nixocio** [comment]
The issue itself was not on the `CredentialLoookup` component.

 @mabashian helped me, and discovered that when using `CredentialLoookup` with the required prop,  `UseField` hook needs to have the  `validate` argument.  I will update all components using `CredentialLoookup` with the `required` prop.

**Comment by dsesami** [comment]
This will be closed after stubs are added. #8239 has been marked for merge.

**Comment by dsesami** [comment]
stubs are in `inventories/inventory-sources.spec`.
