### ISSUE TITLE
AWX 14 Fails to Run Playbook Connecting to Cisco Devices

### ISSUE THREAD

**Issue by raydoherty** [ansible/awx#8188]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Ansible AWX fails to run a play on cisco devices with the following error:
ImportError: cannot import name '_PERM_BITS

##### ENVIRONMENT
* AWX version: 14.1.0
* AWX install method: docker container from install from AWX install playbook
* Ansible version:  2.9.13 (but also failed on all version of 2.9.x)
* Operating System: Ubuntu 20.04 Server(also tried Centos 8 with the same results)
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Install ansible
install docker
install docker-compose
run play using the cisco ios_command module

##### EXPECTED RESULTS

Play logs into router and runs the command

##### ACTUAL RESULTS

The play fails 

##### ADDITIONAL INFORMATION

ansible-playbook 2.9.13
  config file = /tmp/awx_23_w8x5irmh/project/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

The full traceback is:
Traceback (most recent call last):
  File "/var/lib/awx/.ansible/tmp/ansible-local-4901bzlx1bp/ansible-tmp-1600679296.6198432-81909963448880/AnsiballZ_ios_command.py", line 102, in <module>
    _ansiballz_main()
  File "/var/lib/awx/.ansible/tmp/ansible-local-4901bzlx1bp/ansible-tmp-1600679296.6198432-81909963448880/AnsiballZ_ios_command.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/var/lib/awx/.ansible/tmp/ansible-local-4901bzlx1bp/ansible-tmp-1600679296.6198432-81909963448880/AnsiballZ_ios_command.py", line 37, in invoke_module
    from ansible.module_utils import basic
  File "/tmp/ansible_ios_command_payload_417s0_dz/ansible_ios_command_payload.zip/ansible/module_utils/basic.py", line 139, in <module>
ImportError: cannot import name '_PERM_BITS'
fatal: [x.x.x.x]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-local-4901bzlx1bp/ansible-tmp-1600679296.6198432-81909963448880/AnsiballZ_ios_command.py\\", line 102, in <module>\\n    _ansiballz_main()\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-local-4901bzlx1bp/ansible-tmp-1600679296.6198432-81909963448880/AnsiballZ_ios_command.py\\", line 94, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-local-4901bzlx1bp/ansible-tmp-1600679296.6198432-81909963448880/AnsiballZ_ios_command.py\\", line 37, in invoke_module\\n    from ansible.module_utils import basic\\n  File \\"/tmp/ansible_ios_command_payload_417s0_dz/ansible_ios_command_payload.zip/ansible/module_utils/basic.py\\", line 139, in <module>\\nImportError: cannot import name '_PERM_BITS'\\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\\nSee stdout/stderr for the exact error",
    "rc": 1

**Comment by ryanpetrello** [comment]
Hey @raydoherty whatever's going on here looks like an issue with Ansible itself to me (this traceback is from the `ansible-playbook` process) - have you tried reaching out to their mailing list or IRC room?

**Comment by raydoherty** [comment]
Yes...i logged into the container and in the venv and run ansible engine and the error is the same.  I will move the report there.
