### ISSUE TITLE
Selecting prompt on launch on vault password erroneously shows field error after entering password

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#8195]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
![vault_prompt_pass](https://user-images.githubusercontent.com/9889020/93885835-ad4b6880-fcb2-11ea-8822-c28bbe91724a.gif)

If you don't enter anything into the input before clicking the prompt on launch button then the validation seems to behave properly.

The expected behavior here is that the field error should not be shown if the user selects prompt on launch _or_ provides a default password.

Marking this as low since it seems like clicking the Save button clears the field error allowing the user to successfully save the credential.

**Comment by mabashian** [comment]
Clicking save actually wipes this error.  Clicking save again allows the user to save the form so bumping this down to `medium` as there's a fairly straightforward work around.

**Comment by akus062381** [comment]
resolved
