### ISSUE TITLE
Privilege Escalation Method dropdown shows no options

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#8196]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
![priv_esc](https://user-images.githubusercontent.com/9889020/93886865-ef28de80-fcb3-11ea-9627-b2f445690f8c.gif)

Not sure what happened to break this but I think this field should present the user with all the options _and_ allow them to type ahead to filter the list down.  I included the old UI at the end of the gif for reference.

**Comment by tiagodread** [comment]
PR already merged tests covered by 5679
