### ISSUE TITLE
Enforce credential replacement rules on job launch prompt

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#8200]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When launching a job template/configuring a schedule/configuring a workflow node where the job template prompts for credentials, a user should not be able to remove a credential without replacing it with one of the same type.  For example, if a job template has a default machine credential, the user must use that default or replace it with another machine credential.  This applies to all credential types.  Vault credentials have slightly different rules since a user can specify multiple default vault credentials.  If a job template has a default vault credential with ID: `foo` then the user must use that default or replace it with another vault credential with ID: `foo`.

In the old UI we showed this message on the prompt step if a user removed one of the default credentials:

<img width="780" alt="Screen Shot 2020-09-22 at 12 39 26 PM" src="https://user-images.githubusercontent.com/9889020/93911688-b64b3280-fcd0-11ea-8782-997a0c656842.png">

<img width="822" alt="Screen Shot 2020-09-22 at 12 40 11 PM" src="https://user-images.githubusercontent.com/9889020/93911755-cd8a2000-fcd0-11ea-9bb2-0e89ae33f361.png">

We should probably consider showing something similar to let the user know what the expectation is.

**Comment by unlikelyzero** [comment]
Note: we will need to add this to our coverage

**Comment by mabashian** [comment]
Same thing applies to workflow nodes and schedules.

**Comment by mabashian** [comment]
Wait until #8399 merges

**Comment by akus062381** [comment]
coverage added in 
https://github.com/ansible/tower-qa/pull/5871
