### ISSUE TITLE
Launching job with vault password 400s when default machine cred is replaced

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#8202]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Really odd behavior that I came across while building out credential prompting in the new UI.  This can be reproduced via the API browser though.

I created a JT with a default machine credential (that prompted for some passwords) and a default vault credential (that prompted for password).

If I swap the machine credential for one that does not prompt for a password then the API responds with a 400 on launch complaining about the vault password: `{"passwords_needed_to_start":["vault_password.A"]}`

In the example below credential with ID = 1 is the machine credential that prompts for ssh and become passwords.  Credential ID = 2 is the machine credential that does not prompt for passwords.  Credential ID = 4 is the vault credential that prompts for password.

A normal launch without changing credentials:

![good_launch](https://user-images.githubusercontent.com/9889020/93922608-26ad8000-fce0-11ea-8b61-8604ec329d83.gif)

A launch where I change the machine credential:

![bad_launch](https://user-images.githubusercontent.com/9889020/93922684-493f9900-fce0-11ea-93a5-891b46041a13.gif)

**Comment by one-t** [comment]
Confirmed that this is now working as expected in devel.
