### ISSUE TITLE
Refresh of page on asssociate instance groups breaks UI

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#8203]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Refresh of page on associate instance groups breaks UI. `me` variable will be undefined. 

##### STEPS TO REPRODUCE

Logged as system admin, go to `https://localhost:3001/next/instance_groups/1/instances`, for instance, attempt to refresh the page a few times.

##### EXPECTED RESULTS

Regular page refresh.

##### ACTUAL RESULTS

UI breaks due to a missing, `me`, variable.

**Comment by nixocio** [comment]
This issue was already addressed by https://github.com/ansible/awx/pull/8179

**Comment by unlikelyzero** [comment]
@unlikelyzero i will be testing this post-merge

**Comment by unlikelyzero** [comment]
covered in corner-cases.spec.js
