### ISSUE TITLE
Remove any remaining `window.liveUpdates` behavior from lists

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#8211]
Based on modifications / optimizations to the api and ui in recent releases/prs and [some discussions](https://github.com/ansible/awx/pull/8193#discussion_r492785047), we no longer need to modify list behavior based on `window.liveUpdates`. This issue is for removing any remaining code that uses `window.liveUpdates` for lists.

**Comment by unlikelyzero** [comment]
@jakemcdermott is this done as a backport from 3.7.3 to devel?

**Comment by wenottingham** [comment]
Closed, no longer relevant.
