### ISSUE TITLE
Add the ability to toggle on/off GALAXY_IGNORE_CERTS in the UI

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#8215]
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/214912/94013458-1a750180-fd78-11ea-930b-7211a353fb51.png">

see: https://github.com/ansible/awx/pull/8213

**Comment by dsesami** [comment]
I've verified that this works in the legacy UI successfully. @tiagodread is free to close this out after https://github.com/ansible/awx/pull/8186 is verified and merged.

**Comment by tiagodread** [comment]
#8186 verified and merged, we can close this out.
