### ISSUE TITLE
Update usage of user_capabilities for Execution Environments

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#8216]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Update usage of summary_fields for Execution Environments. `user_capabilities` was added as part of `summary_fields` for EE. Update the `ToolbarDeleteButton` component.

**Comment by nixocio** [comment]
See: https://github.com/ansible/awx/pull/8208

**Comment by unlikelyzero** [comment]
@nixocio is this on the EE branch or on devel?

**Comment by unlikelyzero** [comment]
moving to https://github.com/ansible/awx/issues/7884
