### ISSUE TITLE
[Notification template] "name" field triggers unexpected GET requests

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#8219]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Trying to create a new notification template every char filled on the name field trigger a GET request for `/api/v2/organizations/`

note: this causes significant performance slowdown in the UI.

##### ENVIRONMENT
* AWX version: 2.9.11
* AWX install method:docker for mac
* Ansible version:  14.1.0
* Operating System: Catalina
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Navigate to Notification template
2. Open the network tab on browser
3. Type something on the name field

##### EXPECTED RESULTS

No API request should be made

##### ACTUAL RESULTS

Get request for `/api/v2/organizations/?order_by=name&page=1&page_size=5` on every character filled 

##### ADDITIONAL INFORMATION

![notification](https://user-images.githubusercontent.com/12464858/94059348-a870dc80-fdb8-11ea-86fd-87f58742ef1b.gif)

**Comment by tiagodread** [comment]
This problem is happening for each field for each notification type.

**Comment by dsesami** [comment]
It appears that this also occurs when doing Container Groups > New > selecting a credential.

**Comment by tiagodread** [comment]
Tests are OK, PR already merged.
