### ISSUE TITLE
 The notifications through webhook notification type for Approved Message Body,Workflow Denied Message Body not getting to microsoft teams from AWX.Remaining success,started,failure notifications are working fine.

### ISSUE THREAD

**Issue by venu1428** [ansible/awx#8225]
ISSUE TYPE
Bug
COMPONENT NAME
UI
SUMMARY
I have setup webhook notification configuration to microsoft teams from awx.I have get the notificcations for sucess,failure,start cases but not getting notification for Workflow Approved Message Body,Workflow Denied Message Body.

I have used default the Workflow Approved Message Body  to test but failed to get the notifications.

{
    "@type": "MessageCard",
    "summary": "Workflow approval node was need review: {{ approval_node_name }}",
    "title": "Workflow approval node was need review: {{ approval_node_name }}",
    "themeColor": "FF0000",
    "potentialAction": [
        {
            "@type": "ViewAction",
            "name": "View workflow job on AWX",
            "target": [
                "{{ workflow_url }}"
            ]
        }
    ]
}

ENVIRONMENT
AWX version: 13.0.0
AWX install method: docker on Centos
Ansible version: 2.9.10
Operating System: Centos
Web Browser: Firefox
"content-type": "application/json"
Http method: POST

STEPS TO REPRODUCE
as described here:
https://docs.ansible.com/ansible-tower/latest/html/userguide/notifications.html#webhook

and here:
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors

EXPECTED RESULTS
Expecting the notifications needs to come to microsoft teams for approval
ACTUAL RESULTS
I am getting error not getting notifications for approval node messages.I have enabled all the notifications in template.

**Comment by blomquisg** [comment]
Can you include the error you're seeing?

**Comment by blomquisg** [comment]
@beeankha could this be similar to the fix you did for pager-duty?

**Comment by venu1428** [comment]
Hi @blomquisg for below it was working
{
    "@type": "MessageCard",
    "@context": "https://schema.org/extensions",
    "summary": "Workflow approval node got Approved: {{ approval_node_name }}",
    "title": "Workflow approval node got Approved: {{ approval_node_name }}",
    "themeColor": "008000",
}
but when I put any action payload the things are not replicated.like above potential action one.

It is not failed in recent notification for the webhook.
not showing any erros outside.
Thank you for the responce.
