### ISSUE TITLE
AWX API PATCH request to alter a job template's name not working as expected

### ISSUE THREAD

**Issue by fourstepper** [ansible/awx#8227]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### ENVIRONMENT
* AWX version: 14.1.0
* AWX install method: docker on linux
* Ansible version: 2.9.11
* Operating System: Linux

##### STEPS TO REPRODUCE

I am trying to make a PATCH request to the AWX API to update the name of a job template. This is how the API request looks like: https://www.getpostman.com/collections/d37784174ccd7ef82280

From the documentation I understand that the PATCH request should modify any specified parameters described in the data json structure, which I believe I have done.

Thank you for any pointers!

##### EXPECTED RESULTS

The name of the targeted job template would be changed and printed in the API output.

##### ACTUAL RESULTS

Unfortunately, the template's name doesn't change and the output is basically the same as if I called a get_templates GET request

##### ADDITIONAL INFORMATION

I am unsure if I am using the API wrong or if this is a bug, unfortunately. I am referencing the official documentation of Ansible Tower from [here](https://docs.ansible.com/ansible-tower/latest/html/towerapi/api_ref.html)

**Comment by ryanpetrello** [comment]
@fourstepper,

I'm having trouble reproducing this.  Can you share your reproduction steps with something like curl?

```shell
~ curl -sk "https://ryan:ryan@awx.example.org/api/v2/job_templates/5/" | jq '.name'
"Demo Job Template"
~ curl -sk "https://ryan:ryan@awx.example.org/api/v2/job_templates/5/" -X PATCH -d '{"name": "Testing 1 2 3"}' -H "Content-Type:application/json"
~ curl -sk "https://ryan:ryan@awx.example.org/api/v2/job_templates/5/" | jq '.name'
"Testing 1 2 3"
```

**Comment by fourstepper** [comment]
Hi @ryanpetrello, thanks for your reply.

I will provide some examples first thing tomorrow, I'm unfortunately out of the office for today.

**Comment by fourstepper** [comment]
Hello @ryanpetrello, I have tested this today agian and sucessfully discovered that the problem was a missing trailing forwardslash

Thanks for the help!
