### ISSUE TITLE
Google chat notification always give 400

### ISSUE THREAD

**Issue by naveenmykaarma** [ansible/awx#8231]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I am trying to add google chat webhook notifications but it always throw 400. 

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.9.10
* Operating System: centos 7 
* Web Browser: google chrome

##### STEPS TO REPRODUCE

1. Go to notification area
2. Create notification
3. Add name, organization, webhook
4. In HTTP header 
{
  "Content-Type": "application/json"
}
5. Save and Test

##### EXPECTED RESULTS

Message should reach destination

##### ACTUAL RESULTS

Error Sending Webhook notification : 400

##### ADDITIONAL INFORMATION
Please see attached file. 

![3](https://user-images.githubusercontent.com/37445527/94196927-a864ff80-fed2-11ea-85ba-e277ef9a3973.PNG)
![2](https://user-images.githubusercontent.com/37445527/94196605-40161e00-fed2-11ea-9418-6a8f1b63aa21.PNG)

**Comment by ryanpetrello** [comment]
Hey @naveenmykaarma,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
