### ISSUE TITLE
POST request to api/v2/inventories endpoint does not create an inventory and returns 200 OK response same as GET request

### ISSUE THREAD

**Issue by alireza-esmaeeli** [ansible/awx#8233]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I'm experimenting with AWX REST API to evaluate it's production readiness level. When I send a POST request to /api/v2/inventories endpoint with postman and administrative permissions to create an inventory, I get a response back exactly the same as GET request to this url.

##### ENVIRONMENT
* AWX version: 14.1.0
* AWX install method: docker on linux
* Ansible version:  2.9.2
* Operating System: ubuntu 18.04
* Web Browser:

##### STEPS TO REPRODUCE

Send a POST request to /api/v2/inventories endpoint with a json payload sush as:
{
  "name": "anyname"
  "organization": 1
}

##### EXPECTED RESULTS

201 Created

##### ACTUAL RESULTS

200 Ok

##### ADDITIONAL INFORMATION

Here is the POST request and response sequence:

POST /api/v2/inventories HTTP/1.1
Authorization: Basic YWRtaW46cGFzc3dvcmQ=
Content-Type: application/json
User-Agent: PostmanRuntime/7.26.5
Accept: */*
Postman-Token: ceac2092-7e1a-4ed7-b1e2-1c3564c1eb65
Host: ******
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 47
Cookie: csrftoken=YqbCdgJPWEE7kM7JBV8g5HI3vkj0i7gqQFYfuW8y4DORO7lQdhUNIInOnqu1jHqH

{
    "name": "newinv",
    "organization": 1
}

HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Fri, 25 Sep 2020 08:19:57 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 0
Connection: keep-alive
Location: /api/v2/inventories/
Vary: Accept-Language, Origin, Cookie
Content-Language: en
X-API-Total-Time: 0.068s
Strict-Transport-Security: max-age=15768000
Content-Security-Policy: default-src 'self'; connect-src 'self' ws: wss:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' *.pendo.io; img-src 'self' *.pendo.io data:; report-uri /csp-violation/
X-Content-Security-Policy: default-src 'self'; connect-src 'self' ws: wss:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' *.pendo.io; img-src 'self' *.pendo.io data:; report-uri /csp-violation/
X-Frame-Options: DENY

**Comment by ryanpetrello** [comment]
@alireza-esmaeeli,

The HTTP 301 response is redirecting you to `/api/v2/inventories/` because you forgot to put in a trailing slash.

**Comment by alireza-esmaeeli** [comment]
Oops! Thank you for your reply, I appreciate it.
