### ISSUE TITLE
Fix Kebabified Toolbar Buttons

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#8237]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
On some lists, where we have one off buttons (add, edit) the kebabified buttons do not render properly when advanced search is activated.  

Those lists are:

- [x] Inventory Host Groups List

- [x] Inventory Groups Host List

- [x] Inventory Groups Nested Groups List

##### ENVIRONMENT
* AWX version: 14.1
* AWX install method: docker for mac
* Ansible version:  2.9.1
* Operating System: Mojave
* Web Browser:Chrome

##### STEPS TO REPRODUCE
Go to any of the lists above.  In the search drop down select Advanced then click on the kebabed icon on the right hand side of the toolbar to see the buttons appear.  

##### EXPECTED RESULTS

![Screen Shot 2020-09-25 at 11 29 31 AM](https://user-images.githubusercontent.com/39280967/94285965-6a8fc780-ff22-11ea-9ef9-f71bf31fd171.png)

##### ACTUAL RESULTS

![Screen Shot 2020-09-25 at 11 30 23 AM](https://user-images.githubusercontent.com/39280967/94286092-898e5980-ff22-11ea-9e25-81016787917d.png)

**Comment by tiagodread** [comment]
PR already merged, worked as expected

**Comment by tiagodread** [comment]
More places with button inside kebab:

**Job Templates:**

- [x]  Access tab -> advanced search -> kebab -> Add

![image](https://user-images.githubusercontent.com/12464858/97215814-b6dd5a00-17a3-11eb-811f-cab797505ce6.png)

- [x] Access tab -> Add -> Users or team -> advanced search -> kebab -> empty (same happen in WFJT Node) 

![image](https://user-images.githubusercontent.com/12464858/97216158-2e12ee00-17a4-11eb-8ac0-0eaf7aeaaaa5.png)

**Credentials:**

- [x] Access tab -> advanced search -> kebab -> Add

![image](https://user-images.githubusercontent.com/12464858/97216432-93ff7580-17a4-11eb-9284-078691212ce5.png)

**Projects:**

- [x] Access tab -> advanced search -> kebab -> Add

![image](https://user-images.githubusercontent.com/12464858/97216573-d1640300-17a4-11eb-9fbf-2cbd4381e515.png)
- [x] Notifications -> advanced search -> kebab -> empty

![image](https://user-images.githubusercontent.com/12464858/97216947-50593b80-17a5-11eb-8446-11892ccde77c.png)

**Inventories**

- [x] Access tab -> advanced search -> kebab -> Add

![image](https://user-images.githubusercontent.com/12464858/97217162-9f06d580-17a5-11eb-90ac-605fd0cdcdcb.png)

- [x] Groups tab -> advanced search -> kebab -> delete

![image](https://user-images.githubusercontent.com/12464858/97217287-cfe70a80-17a5-11eb-808a-ba9770aa70d0.png)

**Hosts**

- [x] Groups tabs -> advanced search -> kebab -> Add

![image](https://user-images.githubusercontent.com/12464858/97217542-353afb80-17a6-11eb-9b13-7004181f235e.png)

**Organizations**

- [x] Access tab -> advanced search -> kebab -> Add

![image](https://user-images.githubusercontent.com/12464858/97217676-674c5d80-17a6-11eb-9d6f-bf4910f75b0f.png)

**Teams**

- [x] Access tab -> advanced search -> kebab -> Add

![image](https://user-images.githubusercontent.com/12464858/97217936-babeab80-17a6-11eb-8c37-f8e1b0475f0b.png)

- [x] Roles tab -> advanced search -> kebab -> Add

![image](https://user-images.githubusercontent.com/12464858/97218035-e04bb500-17a6-11eb-85ab-c82d9c91c3c5.png)

**Instance groups**

- [x] Instance tab -> advanced search -> kebab -> Associate
![image](https://user-images.githubusercontent.com/12464858/97218200-230d8d00-17a7-11eb-89dd-28b3f92e43e2.png)

**Comment by AlexSCorey** [comment]
Sweet, thanks for finding and documenting these issues

**Comment by AlexSCorey** [comment]
@tiagodread can this be closed?

**Comment by tiagodread** [comment]
@AlexSCorey i'm finishing the test to cover this feature, then we can close.

**Comment by tiagodread** [comment]
PR already merged, tests covered by 5696
