### ISSUE TITLE
Add label `controller` to identify controller instance group

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#8244]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add label `controller` to identify a controller instance group.

See: https://docs.ansible.com/ansible-tower/3.7.2/html/administration/external_execution_envs.html#ag-clustering-isolated-igs

**Comment by unlikelyzero** [comment]
@nixocio is this on the EE branch?

**Comment by nixocio** [comment]
@unlikelyzero , this work is related to instance groups. This work will be on EE since that branch was rebased against devel, but this work is not related to EE.

**Comment by unlikelyzero** [comment]
Implemented in https://github.com/ansible/awx/pull/8162 moving to needs_test

**Comment by akus062381** [comment]
related to isolated nodes, which are being removed
see this link: https://github.com/ansible/tower-qa/pull/5957
