### ISSUE TITLE
Run project updates in Execution Environments

### ISSUE THREAD

**Issue by shanemcd** [ansible/awx#8245]
Solution needs to work on both VM and k8s based installations.

For k8s, I propose an architecture along the lines of:
![Tower 4 0 Pod Topology](https://user-images.githubusercontent.com/773186/94439943-0f064980-016f-11eb-8cb1-d93dc7b67d5c.png)

**Comment by AlanCoding** [comment]
@shanemcd I'm guessing this issue is out of date?

**Comment by shanemcd** [comment]
Which part? The topology still looks right to me. We need a separate EE in the pod unless we want to install Ansible in the task container (we don't).

**Comment by AlanCoding** [comment]
Right, this is actively in progress in https://github.com/ansible/awx/pull/8598.
