### ISSUE TITLE
Hide extra vars option in the GUI

### ISSUE THREAD

**Issue by tom0010** [ansible/awx#8246]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Soon as @wenottingham has commented and said
```Password variables aren't sent encrypted, they're just stored encrypted and not retrievable later.```
in https://github.com/ansible/awx/issues/6030.

Would it be possible to potentially put in a toggle or option to hide extra vars from the GUI? 

This would mean that when using the API you can pass "encrypted" or "secret" values and the people whom have access from the GUI would not be able to see them? We can use `no_log: true`, which helps, but I feel that this feature would give us something extra. 
Of course, probably you *could* still query the API and then it probably would present the extra vars anyway, but the standard user wouldn't normally know how to do that.

**Comment by wenottingham** [comment]
Anything stored as 'encrypted' in the database will be shown as `$encrypted$` in the extra vars screen.

**Comment by tom0010** [comment]
@wenottingham that is fine, I'm not asking to show the extra vars screen. I'm actually asking for quite the opposite, for us to have an option to not show the extra vars screen to any/all users in the GUI just before we execute the playbook. Whether that be a toggle in GUI or an option in the API payload or something else.
**For example:** 
`display_extra_vars: true`
`display_extra_vars: false`

**Comment by wenottingham** [comment]
Yes, but I'm not sure what this would accomplish. Your description of "This would mean that when using the API you can pass "encrypted" or "secret" values and the people whom have access from the GUI would not be able to see them" doesn't make sense - anything that's a password type (in a survey) isn't visible to the UI.
