### ISSUE TITLE
Survey extra vars not shown in prompt preview unless they're password fields

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#8247]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
If you have a JT with a single survey question (in my case it was a single select dropdown), the value for the survey question is not shown in an extra vars section of the preview step.

![survey_preview](https://user-images.githubusercontent.com/9889020/94462361-6a453580-0189-11eb-8c9f-d424e4200b5f.gif)

Here's what it used to look like:

![survey_preview](https://user-images.githubusercontent.com/9889020/94462459-8ba62180-0189-11eb-8624-6a9741cbdf91.gif)

Here's the logic that aggregates the extra vars: https://github.com/ansible/awx/blob/devel/awx/ui_next/src/components/LaunchPrompt/steps/PreviewStep.jsx#L36-L44

**Comment by mabashian** [comment]
After this gets fixed please confirm that https://github.com/ansible/awx/issues/5689 is addressed e2e

**Comment by mabashian** [comment]
I fixed this in https://github.com/ansible/awx/pull/8399

**Comment by unlikelyzero** [comment]
covered in https://github.com/ansible/awx/pull/8399#pullrequestreview-553909542
