### ISSUE TITLE
Add resource name to launch wizard

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#8249]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
When launching a JT/WFJT/etc, it would be nice to display the name of the resource that you're launching in the wizard.  Right now we display: `Prompts`

<img width="1459" alt="Screen Shot 2020-09-28 at 1 09 07 PM" src="https://user-images.githubusercontent.com/9889020/94464002-d032bc80-018b-11eb-8838-4785aacf72e8.png">

**Comment by unlikelyzero** [comment]
if we do this, please test the HTML Escaping bug #5764

**Comment by mabashian** [comment]
Please make sure that entities are working when this is implemented.  See #5764
