### ISSUE TITLE
project_sync module in the collection

### ISSUE THREAD

**Issue by nesanton** [ansible/awx#8256]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Would a module for project_sync (and maybe inventory_source_sync) be a good idea? It does not seem to be possible with the tower_project module. Or am I missing something? I see how triggering a workflow that has project sync step in it may be a solution. But I feel like there can be use for the module e.g. for SCM CI jobs etc.

We can make it sort of idempotent or at least report the change by checking `scm_revision` before and after. 
If you think such a module is a good idea, I can try to work on it.

**Comment by AlanCoding** [comment]
Let me see if I can link the right things:

Inventory source updating was introduced to `devel` branch 21 days ago https://github.com/ansible/awx/pull/8033

Ad hoc command modules were merged about 2 hours ago https://github.com/ansible/awx/pull/8228

Project update https://github.com/ansible/awx/pull/7873

**Comment by nesanton** [comment]
What a great summary indeed! Thanks
