### ISSUE TITLE
Working Loader prevents interaction with UI

### ISSUE THREAD

**Issue by timothyanderson82** [ansible/awx#8258]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
The "Working Loader" continuosly interupts interactions with the UI. currently we havea round 270 templates and 56 schedules. Alot of the schedules run every minute. without even interacting with the UI the Working Loader will show and prevent interaction with the UI. Often you will need to click a Template about 3 times to get a response from the ui

##### ENVIRONMENT
* AWX version: 3.0.1.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version: 2.8.1
* Operating System: RHEL7
* Web Browser: Chrome 85.0.4183.121

##### STEPS TO REPRODUCE

When you have multiple schedules running every minute the UI will show the working loader every few seconds and while its showing you cannot interact with the UI. this is the url that presents the wrking loader every few secons:
http://towerhost/api/v2/unified_job_templates/?page_size=20&order_by=name&type=workflow_job_template,job_template

##### EXPECTED RESULTS

The working Loader should only show when i interact with the UI, not when background tasks are running. 

##### ACTUAL RESULTS

The loader shows without interaction preventing me from interacting with the ui
![Loader](https://user-images.githubusercontent.com/31364567/94542773-7db7d580-0249-11eb-9950-91e44e29373f.png)

**Comment by ryanpetrello** [comment]
Hey @WireFuCo - we've made a number of changes in more modern versions of AWX (the version you're running is a year and a half old now) that help address this issue - please give those a try and let us know if you're still seeing issues.
