### ISSUE TITLE
(K8s) Add resource request values for Postgres Helm Chart

### ISSUE THREAD

**Issue by uvu9Ba** [ansible/awx#8264]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Currently it is only possible to set resource limits for Postgres. It should also be possible to increase the default resource requests via variable e.g. `pg_cpu_request` & `pg_mem_request`.

https://github.com/ansible/awx/blob/devel/installer/roles/kubernetes/templates/postgresql-values.yml.j2

```
{% if pg_cpu_limit is defined or pg_mem_limit is defined %}
resources:
  limits:
{% if pg_cpu_limit is defined %}
    cpu: {{ pg_cpu_limit | string }}m
{% endif %}
{% if pg_mem_limit is defined %}
    memory: {{ pg_mem_limit | string }}Gi
{% endif %}
{% endif %}
```

**Comment by TheRealHaoLiu** [comment]
this deployment method is no longer supported please see https://github.com/ansible/awx-operator
