### ISSUE TITLE
(K8s) Update of Postgres Helm values after initial setup

### ISSUE THREAD

**Issue by uvu9Ba** [ansible/awx#8266]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Currently it is not possible to update postgres values via `install.yml` after initial setup. The Helm task will be skipped after the initial setup.

https://github.com/ansible/awx/blob/devel/installer/roles/kubernetes/tasks/main.yml#L121

```
- name: Get Postgres Service Detail
  shell: "{{ kubectl_or_oc }} describe svc {{ postgresql_service_name }} -n {{ kubernetes_namespace }}"
  register: postgres_svc_details
  ignore_errors: true
  when: "pg_hostname is not defined or pg_hostname == ''"
```

```
- name: Deploy PostgreSQL (Kubernetes)
  block:
[...]
    - name: Deploy and Activate Postgres (Kubernetes)
      shell: |
        helm repo add stable https://kubernetes-charts.storage.googleapis.com
        helm repo update
        helm upgrade {{ postgresql_service_name }} \
          --install \
          --namespace {{ kubernetes_namespace }} \
          --version="8.3.0" \
          --values {{ values_file.path }} \
          stable/postgresql
      register: kubernetes_pg_activate
      no_log: true
[...]
  when:
    - pg_hostname is not defined or pg_hostname == ''
    - postgres_svc_details is defined and postgres_svc_details.rc != 0 # <---------
    - kubernetes_context is defined
```

**Comment by uvu9Ba** [comment]
@shanemcd is this when condition for the helm task needed to prevent unattended Postgres updates?

**Comment by shanemcd** [comment]
Historically, we have just skipped the process of re-running this command if a database already exists. 

You are free to send a patch, but just a heads up - we're working on https://github.com/ansible/awx-operator, which will become the new way to deploy AWX on k8s when we decide it's ready for primetime.

**Comment by shanemcd** [comment]
Closing as we no longer use helm for this.
