### ISSUE TITLE
Error is incorrect for missing org in Notification Templates.

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#8268]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Form error handling isn't quite correct for organizations within notification templates. It is either missing, or uncolored text.

##### STEPS TO REPRODUCE
1. To get the first bug, simply go to Notifications > Add. Then click Save without filling out the required fields. All the required fields will go red and show red error text, but the Organization page will show no feedback.
2. To get the second bug, which is probably just a variant of the first bug, fill in all the required fields except the organization. If you click save, you will get the error message under Organization, but it will be black instead of red.

**Comment by unlikelyzero** [comment]
retest now that https://github.com/ansible/awx/pull/8339 landed
