### ISSUE TITLE
VMWare Source does not see templates

### ISSUE THREAD

**Issue by alexseys** [ansible/awx#8271]
##### ISSUE TYPE
- General Inquiry

##### COMPONENT NAME
 - UI

##### SUMMARY
Have a playbook that updates templates os patches
works just fine via ansible cli
but none of templates are shown by vmware vcenter source

##### ENVIRONMENT
* AWX version: 14.1
* AWX install method:  docker on linux 
* Ansible version:  AWX 14.1.0 
* Operating System: Ubuntu 18
* Web Browser: Firefox

##### STEPS TO REPRODUCE
Create an inventory -> Sources -> New Source:
Name: test vmware source
Source: Vmware VCenter
Credentials: VMware credentials

##### EXPECTED RESULTS
Expect to see all templates in Hosts 

##### ACTUAL RESULTS
None of the existing templates are listed in inventory hosts

**Comment by blomquisg** [comment]
@goneri can you look at this and see if this is working as designed or something that's actually broken.

/cc @AlanCoding

**Comment by AlanCoding** [comment]
Could we get some information about the Ansible version you're using? And if you're using the collection in your local testing, what version of the VMWare collection are you using?

**Comment by alexseys** [comment]
Thank you very much for getting to this!

$ ansible --version
ansible 2.9.2
  config file = /ansible/ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

I do not use a collection, i connect directly to vsphere:

$cat roles/ansible-vsphere-update-templates/tasks/create_vm_from_template.yml
`---
- name: set default vlan name
  set_fact:
    vlan_name: "{{ vm_Network }}"

- name: Create a VM from a template on cluster
  vmware_guest:
    datacenter: "{{ vm_DataCenter }}"
    cluster: "Cluster"
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    validate_certs: no
    folder: "{{ folder_name }}"
    name: "{{ tmp_vm_name }}_{{ random_number }}"
    annotation: "Template update by ansible on {{ creationdate }} "
    state: poweredon
    template: "{{ template_name }}"
    disk:
    - size_gb: '32'
      type: thin
      datastore: "{{ vm_DataStore }}"
    hardware:
      memory_mb: "2048"
      num_cpus:  "1"
      hotadd_cpu: True
      hotremove_cpu: True
      hotadd_memory: True
    networks:
    - name: "{{ vlan_name }}"
      start_connected: True
    wait_for_ip_address: yes
  delegate_to: localhost
  register: vmfacts`

Thank you!
Alexsey

**Comment by AlanCoding** [comment]
Is the expectation that `template_name` comes from the inventory hostvars? I want to get this a little better isolated from the role that you're running, back to the missing data in the inventory data that the update produces.

**Comment by alexseys** [comment]
template_name var is coming in form external variable.:

 $ansible-playbook -i tmpl_inventory update_template.yml --vault-password-file=/root/.esx_vault -e template_name=CentOS

I do this, at this time, to update templates one by one.

Thank you!

**Comment by AlanCoding** [comment]
Then I don't understand what this has to do with VMWare inventory. You're not trying to pass extra vars to the inventory update, are you? That's a new feature in Ansible 2.11 https://github.com/ansible/ansible/pull/70970, and I think irrelevant of this.

If you're expecting the extra var to be passed into the `ansible-playbook` run, then from where? From the VMWare credential?

**Comment by alexseys** [comment]
Hm, it appears i forgot to hit comment button, last week, my apologies
Issue is not with variables at all, issue is I do not see names of templates  from vmware inventory. 
All VMs are there, none of templates are shown!

Thank you.

**Comment by wenottingham** [comment]
@Goneri @Akasurde is the vmware inventory designed to pull templates, or hosts only?

**Comment by wenottingham** [comment]
The docs specifically say it pulls VMs. See https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vm_inventory_inventory.html

If you want it to pull templates, that would be an enhancement request to file at https://github.com/ansible-collections/vmware
