### ISSUE TITLE
Tower has no ability to allow permissions to a group of Tower objects within an organization

### ISSUE THREAD

**Issue by tchellomello** [ansible/awx#8275]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Creating a team, and then trying to add permissions, like as "Job Templates", "Workflow Templates", "Projects", "Inventories", "Credentials" and "Organizations" currently meet part of the ideal RBAC environment.

The requirement would be to create a group or collection of Tower objects (i.e. inventories, templates, credentials, projects) so it could then assign permissions for teams or users. For example, create a collection of inventories with all the inventories that relate to one specific application. Then it could be assigned to a team or multiple teams of users to have certain permissions to that group, with each inventory in the group having the same permissions. All of the users in the assigned teams would then have the same permissions to all of the inventories in the collection. 

Where this differs from adding all the inventories permissions to the user team as described in the process you mentioned is that this would easily allow multiple teams to have the same permissions for a group of objects (inventories, credentials, templates, etc). This would make it a lot easier when a new inventory (just using as an example but could be any of the other objects mentioned) is created that needs to have the proper permissions assigned to it. The inventory could just be added to the collection and then all of the associated teams then have the correct permissions on it. 

This could be solved by allowing the creation of collections for inventories, templates, credentials, and projects. Essentially teams but for tower objects.

**Comment by gamuniz** [comment]
@tchellomello Thanks for contributing this idea, we are likely not moving in this direction. Closing.
