### ISSUE TITLE
Make org a required field for galaxy credentials

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#8276]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
<img width="1429" alt="Screen Shot 2020-09-30 at 11 29 07 AM" src="https://user-images.githubusercontent.com/9889020/94706492-4102e180-0310-11eb-904f-68234cee0489.png">

Ideally we don't want to see this error in the UI

**Comment by tiagodread** [comment]
Verified that Org is required only for Galaxy type, also added a stub for it in 5744
