### ISSUE TITLE
Add git-lfs to the awx_task container

### ISSUE THREAD

**Issue by pasta88** [ansible/awx#8278]
I think it would be good idea to add git-lfs package into awx_task container. I believe some users use it.

**Comment by jerosa** [comment]
This would be really helpful, just the installation of git-lfs inside the containers will be enough.

Currently as a workaround once you run the docker-compose, we execute `yum install git-lfs` in all  "awx_task" containers. However we need to check the "delete on update" checkbox in all the projects created in AWX to ensure that the repository is being cloned with LFS installed.

**Comment by jetxeberria** [comment]
Making LFS available when AWX starts will be really useful due 2 reasons:
- prevent the activation of LFS by sending commands to containers
- prevent repository deleting and cloning before launching every template
