### ISSUE TITLE
RFE for better documentation on authentication type mix and match with best practices

### ISSUE THREAD

**Issue by lsantiag86** [ansible/awx#828]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Documentation needs to be more clear on what types of auth you can mix and match and what results to expect

##### ENVIRONMENT
* Ansible Tower 3.2.1
* Ansible Version 2.4.0
* Red Hat Enterprise Linux Server release 7.4
* Web Browser: Firefox

##### STEPS TO REPRODUCE

n/a

##### EXPECTED RESULTS
more clear understanding

##### ACTUAL RESULTS
not clear understanding

**Comment by wenottingham** [comment]
Hi, we do not track the Tower documentation fixes directly in this repo; closing this.
