### ISSUE TITLE
Inventory helper is misaligned on JT form

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#8283]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When making a new JT, if you are missing an inventory, the error is to the right of the element, rather than below it.
![Screenshot from 2020-09-30 15-53-15](https://user-images.githubusercontent.com/19942822/94733067-33138780-0335-11eb-96f9-ad35885dacf2.png)

Make a new JT, and try to click save without filling in any fields to see this error.

**Comment by tiagodread** [comment]
Fix already merged 👍🏽
