### ISSUE TITLE
AzureAD settings form 

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#8286]
##### ISSUE TYPE
 - Feature Idea

URL: `/next/settings/azure/edit`

* Help text should be displayed in the form field popover
* Handle errors
* Internalization

#### Fields
  * Azure AD OAuth2 Callback URL
	  * Read-only
	  * Depends on `TOWER_URL_BASE`
	  * No revert 
  * Azure AD OAuth2 Key
	  * Text field
  * Azure AD OAuth2 Secret
	  * Encrypted
  * Azure AD OAuth2 Organization Map
	  * CodeMirror field
  * Azure AD OAuth2 Team Map
	  * CodeMirror field
  * Action Buttons
	  * Save
	  * Cancel
	  * Revert all

<img width="804" alt="Screen Shot 2020-09-30 at 4 14 47 PM" src="https://user-images.githubusercontent.com/15881645/94735013-13ca2980-0338-11eb-9d47-7c40d46cced3.png">

**Comment by unlikelyzero** [comment]
covered by https://github.com/ansible/tower-qa/pull/5734
