### ISSUE TITLE
Activity stream settings form 

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#8287]
##### ISSUE TYPE
 - Feature Idea

URL: `/next/settings/activity_stream/edit`

* Help text should be displayed in the form field popover
* Handle errors
* Internalization

##### ISSUE TYPE
 - Feature Idea

#### Fields
  * Enable Activity Stream
	  * Toggle
	  * Required
  * Enable Activity Stream for Inventory Sync
	  * Toggle
	  * Required
  * Action Buttons
	  * Save
	  * Cancel
	  * Revert all

**Comment by unlikelyzero** [comment]
covered by https://github.com/ansible/tower-qa/pull/5734
