### ISSUE TITLE
Refreshing certain schedule lists can lock up the browser tab

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#829]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
I believe this is a direct result of the ui-router upgrade several weeks back.  Template/Workflow/Project schedule states are actually standalone states and not part of any state tree (ex: templates).  As a result of this, when the user refreshes the page, the ancestor breadcrumb states are not actually being generated and the breadcrumb lib gets stuck attempting to traverse the trail.

##### ENVIRONMENT
* Web Browser: likely any

##### STEPS TO REPRODUCE

1. Create a Job Template
2. Navigate to the schedule list for that JT
3. Refresh the page

##### EXPECTED RESULTS

Schedule list to render

##### ACTUAL RESULTS

Page partially renders, browser tab locks up

##### ADDITIONAL INFORMATION

@wenottingham, I think that we can kill two birds with one stone here.  The easiest way to fix this would be to move the schedule states into the appropriate tree.  For example:

Currently:
`templates` (list)
`templates.editJobTemplate` (edit form)
`jobTemplateSchedules` (schedule list)

Proposed:
`templates` (list)
`templates.editJobTemplate` (edit form)
`templates.editJobTemplate.schedules` (schedule list)

^^ this is what I think we should do for https://github.com/ansible/awx/issues/446 which would be both an enhancement and a bug fix

**Comment by scottlackey** [comment]
Also having this issue, selecting edit on existing schedules causes the browser tab to lock

**Comment by martynfielding** [comment]
Experiencing same issue here when attempting to edit an existing schedule.

**Comment by worsco** [comment]
Try this crazy "magic": After you create that FIRST template, DELETE it.  Then, create another template, and try to edit that template.  I found if I did the the above, I could edit the second created template.  Yes, this is a bug.

**Comment by jaredevantabor** [comment]
this is fixed now in devel
