### ISSUE TITLE
Jobs settings form

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#8290]
##### ISSUE TYPE
 - Feature Idea

URL: `/next/settings/jobs/edit`

* Help text should be displayed in the form field popover
* Handle errors
* Internalization

##### ISSUE TYPE
 - Feature Idea

#### Fields
  * Job execution path
	  * Required
	  * Text
  * Maximum Scheduled Jobs
	  * Required
	  * Integer
  * Enable job isolation
	  * Required
	  * Toggle
  * Default Job Timeout
	  * Integer
	  * Default value: 0
  * Default Inventory Update Timeout
	  * Integer
	  * Default value: 0
  * Default Project Update Timeout
	  * Integer 
	  * Default value: 0
  * Per-Host Ansible Fact Cache Timeout
	  * Integer
	  * Default value: 0
  * Maximum number of forks per job
	  * Integer
	  * Default value: 200
  * Run Project Updates With Higher Verbosity
	  * Required
	  * Toggle
  * Enable Role Download
	  * Toggle
  * Ignore Ansible Galaxy ssl certificate verification
	  * Toggle
  * Enable Collection(s) Download
	  * Toggle
  * Follow symlinks
	  * Toggle
  * Isolated host key checking
	  * Toggle
  * Isolated status check interval
	  * Required
	  * Integer
	  * Default value: 1
  * Isolated launch timeout
	  * Required
	  * Integer
	  * Default value: 0
  * Isolated connection timeout
	  * Integer
	  * Default value: 10
  * Enable detailed resource profiling on all playbook runs
	  * Toggle
  * Paths to hide from isolated jobs
	  * CodeMirror
	* Paths to expose to isolated jobs
	  * CodeMirror
  * Ansible Callback Plugins
	  * CodeMirror
  * Ansible Modules Allowed for Ad Hoc Jobs
	  * CodeMirror
  * Extra Environment Variables
	  * CodeMirror
  * Action Buttons
	  * Save
	  * Cancel
	  * Revert all

**Comment by GerardusKoetje** [comment]
can i change Isolated Status Check Interval manual somewhere?

**Comment by tiagodread** [comment]
Closing this with the merge of https://github.com/ansible/awx/pull/8661
covered by https://github.com/ansible/tower-qa/pull/5918
