### ISSUE TITLE
LDAP [Default, 1-5] settings form

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#8291]
##### ISSUE TYPE
 - Feature Idea

URL: `/next/settings/ldap/:category/edit`

* Help text should be displayed in the form field popover
* Handle errors
* Internalization

##### ISSUE TYPE
 - Feature Idea

#### LDAP Default
  * LDAP Server URI
	  * Text
  * LDAP Bind DN
	  * Text
  * LDAP Bind Password
	  * Encrypted
  * LDAP User DN Template
	  * Text
  * LDAP Group Type
	  * Group
  * LDAP Require Group 
	  * Text
  * LDAP Deny Group
	  * Text
  * LDAP Start TLS
	  * Toggle
  * LDAP User Search
	  * CodeMirror
  * LDAP Group Search
	  * CodeMirror
  * LDAP User Attribute Map
	  * CodeMirror
  * LDAP Group Type Parameters
	  * CodeMirror
  * LDAP User Flags by Group
	  * CodeMirror
  * LDAP Organization Map
	  * CodeMirror
  * LDAP Team Map
	  * CodeMirror
  * Action Buttons
	  * Save
	  * Cancel
	  * Revert all

<img width="894" alt="Screen Shot 2020-09-30 at 4 47 52 PM" src="https://user-images.githubusercontent.com/15881645/94737957-b1275c80-033c-11eb-975e-9f6667477b43.png">

**Comment by tiagodread** [comment]
Tests covered by https://github.com/ansible/tower-qa/pull/5846
