### ISSUE TITLE
Logging system form 

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#8292]
##### ISSUE TYPE
 - Feature Idea

URL: `/next/settings/logging/edit`

* Help text should be displayed in the form field popover
* Handle errors
* Internalization

##### ISSUE TYPE
 - Feature Idea

#### Fields
  * Logging aggregator
	  * Text
  * Logging aggregator port
	  * Text
  * Logging aggregator type
	  * Select
  * Logging aggregator username
	  * Text
  * Logging aggregator password/token
	  * Encrypted
  * Loggers sending data to log aggregator form
	  * CodeMirror
  * Log system tracking facts individually
	  * Toggle
  * Logging aggregator protocol
	  * Select
  * TCP connection timeout
	  * Required
	  * Hide if logging aggregator protocol === "UDP"
  * Logging aggregator level threshold
	  * Select
  * Enable/Disable HTTPS certificate verification
	  * Switch
  * Action Buttons
	  * Save
	  * Cancel
	  * Revert all
	  * Test Logging
* Enable External Logging
    * In the old ui, this toggle is disabled when: 
```
disabled="(!LOG_AGGREGATOR_ENABLED && 
(!requiredLogValues.LOG_AGGREGATOR_HOST || 
requiredLogValues.LOG_AGGREGATOR_HOST === '' || 
!requiredLogValues.LOG_AGGREGATOR_TYPE || 
requiredLogValues.LOG_AGGREGATOR_TYPE === '')) || 
$rootScope.user_is_system_auditor"
```

**Comment by unlikelyzero** [comment]
covered by https://github.com/ansible/tower-qa/pull/5734
