### ISSUE TITLE
Misc. system settings form 

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#8293]
##### ISSUE TYPE
 - Feature Idea

URL: `/next/settings/miscellaneous_system/edit`

* Help text should be displayed in the form field popover
* Handle errors
* Internalization

##### ISSUE TYPE
 - Feature Idea

#### Fields
  * Base URL of the Tower host
	  * Required
	  * URL Text field
  * All Users Visible to Organization Admins
	  * Required
	  * Toggle
  * Organization Admins Can Manage Users and Teams
	  * Required
	  * Toggle
  * Idle Time Force Log Out
	  * Required
	  * Integer
	  * Default: 1800
  * Maximum number of simultaneous logged in sessions
	  * Required
	  * Integer
	  * Default: -1
  * Enable HTTP Basic Auth
	  * Required
	  * Toggle
  * Allow External Users to Create OAuth2 Tokens
	  * Toggle
  * Login redirect override URL
	  * Text
  * Access Token Expiration (OAUTH2_PROVIDER)
	  * Required
	  * Integer
	  * Default: 600
  * Refresh Token Expiration (OAUTH2_PROVIDER)
	  * Required
	  * Integer
	  * Default: 2628000
  * Authorization Code Expiration (OAUTH2_PROVIDER)
	  * Required
	  * Integer
	  * Default: 31536000000
  * Remote Host Headers
	  * Required
	  * CodeMirror
  * Custom virtual environment paths
	  * CodeMirror
  * Gather data for Automation Analytics
	  * Toggle
  * Red Hat customer username
	  * Text
  * Red Hat customer password
	  * Encrypted
  * Automation Analytics upload URL
	  * URL text field
  * Automation Analytics Gather Interval
	  * Integer
	  * Default: 14400
  * Action Buttons
	  * Save
	  * Cancel
	  * Revert all

<img width="927" alt="Screen Shot 2020-09-30 at 5 12 37 PM" src="https://user-images.githubusercontent.com/15881645/94740166-29435180-0340-11eb-9737-e5a471db8625.png">

**Comment by unlikelyzero** [comment]
covered by https://github.com/ansible/tower-qa/pull/5734
