### ISSUE TITLE
SAML settings form

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#8295]
##### ISSUE TYPE
 - Feature Idea

URL: `/next/settings/saml/edit`

* Help text should be displayed in the form field popover
* Handle errors
* Internalization

##### ISSUE TYPE
 - Feature Idea

#### Fields
  * SAML Assertion Consumer Service (ACS) URL
	* Read-only
	* Depends on `TOWER_URL_BASE`
	* No revert 
  * SAML Service Provider Metadata URL
	* Read-only
	* Depends on `TOWER_URL_BASE`
	* No revert 
  * SAML Service Provider Entity ID
	  * Text
  * SAML Service Provider Public Certificate
	  * Required
	  * CodeMirror
  * SAML Service Provider Private Key
	  * Required
	  * CodeMirror
  * SAML Service Provider Organization Info
	  * Required
	  * CodeMirror
  * SAML Service Provider Technical Contact
	  * Required
	  * CodeMirror
  * SAML Service Provider Support Contact
	  * Required
	  * CodeMirror
  * SAML Enabled Identity Providers
	  * CodeMirror
  * SAML Organization Map
	  * CodeMirror
  * SAML Organization Attribute Mapping
	  * CodeMirror
  * SAML Team Map
	  * CodeMirror
  * SAML Team Attribute Mapping
	  * CodeMirror
  * SAML Security Config
	  * CodeMirror
  * SAML Service Provider Extra Configuration Data
	  * CodeMirror
  * SAML IDP to extra_data attribute mapping
	  * CodeMirror
  * Action Buttons
	  * Save
	  * Cancel
	  * Revert all

**Comment by akus062381** [comment]
covered by https://github.com/ansible/tower-qa/pull/5890
