### ISSUE TITLE
UI settings form

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#8297]
##### ISSUE TYPE
 - Feature Idea

URL: `/next/settings/ui/edit`

* Help text should be displayed in the form field popover
* Handle errors
* Internalization

##### ISSUE TYPE
 - Feature Idea

#### Fields
  * User analytics tracking state
	  * Select
	  * Disabled for open source awx license
	  * Select options
		  * off
		  * anonymous
		  * detailed
  * Custom logo
	  * [File upload](https://www.patternfly.org/v4/documentation/react/components/fileupload)
  * Custom logo info
	  * Textarea
  * Action Buttons
	  * Save
	  * Cancel
	  * Revert all

<img width="930" alt="Screen Shot 2020-09-30 at 5 26 09 PM" src="https://user-images.githubusercontent.com/15881645/94741379-0ca81900-0342-11eb-9b72-3b7e8b2739ab.png">

**Comment by akus062381** [comment]
QE to add custom logo test

**Comment by unlikelyzero** [comment]
added coverage
