### ISSUE TITLE
Builder image for sdist creation

### ISSUE THREAD

**Issue by shanemcd** [ansible/awx#83]
### Summary

After witnessing the majority of issues that people have been experiencing yesterday and today, we should create a builder image that handles the creation of the sdist. Supporting every OS is probably untenable.

We'll want to bind-mount the project root and dump out the artifact(s) in the appropriate location(s).

### Additional Information:

Base image should be `FROM centos:7` and install the dependencies necessary for creating the sdist to hand off to the other image builds.

**Comment by BastienM** [comment]
A better solution would be to have a CI building the images then distribute them via Docker Hub or Quay.

Most the settings that are available could be integrated into the entrypoints to leverage Docker's environment variables in order to opt in/out features or specify options value.

**Comment by ghost** [comment]
Yes i agree @BastienM.
Is there a valid reason why there isnt an official Dockerimage available on the hub and just a docker-compose.yaml for the DB etc. ? Would be interesting :)

**Comment by geerlingguy** [comment]
@Numblesix - there is an image available, but no, it's not official:

    curl -O https://raw.githubusercontent.com/geerlingguy/awx-container/master/docker-compose.yml
    docker-compose up -d

I'm working on it in this project: https://github.com/geerlingguy/awx-container — for now I hope it's a good stopgap until AWX has a more official prebuilt image.

(And it's two images, corresponding to the two Dockerfiles AWX ships with, [awx_web](https://hub.docker.com/r/geerlingguy/awx_web/) and [awx_task](https://hub.docker.com/r/geerlingguy/awx_task/)).

**Comment by ghost** [comment]
@geerlingguy Nice to see that :) 
ive you need some help you let me know :+1:

**Comment by BastienM** [comment]
@geerlingguy : Had a quick look at your docker-compose, you should probably drop the `links` for `depends_on`.
The former has been deprecated since v1.12 or v1.13 (when networking went live).

The rest is looking good :)

**Comment by matburt** [comment]
This is done in #104
