### ISSUE TITLE
Workflow GUI issue

### ISSUE THREAD

**Issue by ssarkarnetip** [ansible/awx#830]
This is with the workflow editor.  I create a new workflow.  I put in the details.  Added the permissions and sent a notification.  Went to job flow editor.  It would not come up.

I found that issue is that if you just click details and go to the job flow editor is that it works.
  
[AWX Bug.docx](https://github.com/ansible/awx/files/1557158/AWX.Bug.docx)

**Comment by ElliotGo** [comment]
I have the same issue @ssarkarnetip 

**ISSUE TYPE**
Bug Report

**COMPONENT NAME**
UI

**SUMMARY**
Workflow Editor will not popup when clicking "WORKFLOW EDITOR" button...

**ENVIRONMENT**
AWX Version: AWX 1.0.2.303
AWX install method: docker on linux
Operating System: WIN10
Ansible version: 2.4.1.0
Browser: Chrome 62.0.3202.94 64bit

**steps to reproduce**
1. create a workflow template and save
2. click "WORKFLOW EDITOR" button

**Expected result**
workflow editor page should show after clicking "WORKFLOW EDITOR" button

**Actual result**
Nothing would happen after clicking "WORKFLOW EDITOR" button

**Error Message**
![image](https://user-images.githubusercontent.com/28291313/34400393-b8af32c4-ebcb-11e7-91ca-0fe985cc45f9.png)

**Comment by ElliotGo** [comment]
link with this issue: https://github.com/ansible/awx/issues/891

**Comment by jakemcdermott** [comment]
👋 
This should be resolved by https://github.com/ansible/awx/pull/919
