### ISSUE TITLE
Allow creation of System Jobs through the UI/API

### ISSUE THREAD

**Issue by Warkdev** [ansible/awx#8301]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Hello, I came around an interesting use case that we've in our environment. We're extensively using a custom Ansible Module to interact with our appliances. This module is being updated regularly and is core of all deployments. We're using Tower to update this module (with a simple playbook) and we'd like to have this job executed only when no other job is currently running and blocking future jobs. 

I came across the fact that System Jobs were precisely doing this. Would it be possible to allow us to create a System Job through the UI ?

Regards,
Cédric Servais

**Comment by wenottingham** [comment]
If you want to launch existing system jobs, they're available via /api/v2/system_job_templates.

If you want to create a new system job template definition via the API... you can't. The system isn't extensible in that way.
