### ISSUE TITLE
Job output scroll next raises an error when no data available

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#8303]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Job output scroll next raises an error.

##### STEPS TO REPRODUCE
1. Launch a Job
2. Go to Job output
3. Before the job output is added click to `scroll next`.

<img width="1444" alt="image" src="https://user-images.githubusercontent.com/9053044/94818958-b3d19280-03cc-11eb-891d-891b48e6a807.png">

4 - The following error will be displayed.

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/9053044/94818699-66edbc00-03cc-11eb-9a5e-2e5b71f9334d.png">

##### ADDITIONAL INFORMATION

It seems like we can add a conditional to just display those controls once we have data available. It does require further investigation.

**Comment by unlikelyzero** [comment]
Cannot reproduce but added to job-result-output.spec.js
