### ISSUE TITLE
Official Helm Chart for AWX

### ISSUE THREAD

**Issue by luhahn** [ansible/awx#8320]
For our project setup it is way easier to use Helm Charts instead of the existing ansible-kubernetes installer.
Would it be possible to have an official AWX helm chart?

We already created a chart based on the kubernetes templates included in your kubernetes installer. It is still under development, but works really well.

https://github.com/novumrgi/helm/tree/master/charts/awx

**Comment by wenottingham** [comment]
Our plans are to have an operator in the future; we do not have plans for a helm chart.
