### ISSUE TITLE
RFE: Job view list should have 'caller' schedule name column

### ISSUE THREAD

**Issue by swatinarvekar** [ansible/awx#8321]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
- UI

##### SUMMARY
The job list doesn't show who ran each job. Desire to have the schedule name (in case trigger by schedule) that made the call or have schedule type like scheduled with schedule name / manual with user name.

Customer Explanation: 
- We use Tower to schedule templates, each schedule performs a different function for the same template. However all jobs and notifications are showing only the template name, so all look the same. How can we customize the output so that we see the name of the schedule?
- Instead of opening every single job in the UI to see the schedule name (LAUNCHED BY)  we need to be able to see the scheduler within the main view, or even with the extended details view.
- Having either the schedule name added to custom notifications and job views, or having labels added to schedules (I believe they can only be set at the template level currently), or even better both, as that'll help with searching too.

##### STEPS TO REPRODUCE
1. Create one schedule named **My Schedule 1** for your job template.
2. Create another schedule named **My Schedule 2** for the same job template.
3. Navigate to the Jobs page.

##### EXPECTED RESULTS
To have a way to differentiate the caller of the jobs (My Schedule 1/ My Schedule 2)

##### ACTUAL RESULTS
Can't figure out the caller of the template (same applies to  project and Inventory source)

ADDITIONAL INFORMATION

Can't easily find which scheduler triggers the template. See the screenshot below:

![compact_view](https://user-images.githubusercontent.com/30921032/95072930-a3e9e380-0729-11eb-8454-a4912fe61697.png)
![expanded_view](https://user-images.githubusercontent.com/30921032/95072936-a51b1080-0729-11eb-954b-38191dbc6248.png)

Here job 207 was started as per schedule while job 208 was started manually.

**Comment by jakemcdermott** [comment]
This sounds good to me. Schedule information available to us in the rest api in the job list view (summary fields) so I consider this something we can add in the new ui once we've established a pattern for "expanded" lists:

![Screenshot from 2020-10-07 14-48-44](https://user-images.githubusercontent.com/9753817/95374341-3619f500-08ac-11eb-9ff6-3d128738a2d0.png)

**Comment by mabashian** [comment]
We've now got the expanded row view in the jobs list:

<img width="1379" alt="Screen Shot 2021-11-30 at 9 25 56 AM" src="https://user-images.githubusercontent.com/9889020/144065304-0da7b0de-fe5c-41b5-9098-f93b57d91d58.png">

There's no technical blocker to adding this (schedule name) in the expanded row.

**Comment by akus062381** [comment]
resolved
