### ISSUE TITLE
Don't Require Project Re-Syncs

### ISSUE THREAD

**Issue by bgeels** [ansible/awx#8332]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
It seems like a project revision will deem itself too old and cause a re-sync after some amount of time. This is without any **SCM Update Options** on the project checked. This can be problematic because if there's intermittent issues talking to the SCM source it will cause failures for scheduled **Job Templates** that use that **Project** when there's no reason to.

It would be nice to be able to turn this off or have it just use the previous revision instead of causing the job to fail.

**Comment by wenottingham** [comment]
> It seems like a project revision will deem itself too old and cause a re-sync after some amount of time.

At launch time, the revision of the project that is intended to be launched will be checked out/downloaded if it does not already exist on the executing node. It's not about too old, it just making sure the required revision is present.

What you're looking for is (mostly) #289. Closing as a duplicate.

**Comment by bgeels** [comment]
I think https://github.com/ansible/awx/issues/287 is closer, i.e. don't have jobs success be dependent on the SCM being reachable.

https://github.com/ansible/awx/blob/devel/awx/playbooks/project_update.yml

It seems like the way tags are applied to each section in the **project_update** play this should be possible. I'd think the tags would be applied based on the **SCM Update Options** but I'm not sure where / how those are applied.

However, looking through the job history for the scheduled runs, it looks like the tags that get applied to that play vary. Sometimes it's just **install_roles** and other times it's **update_git**, **install_roles**, and **install_collections**. When really I want none of these applied for **Job Template** runs.

**Comment by wenottingham** [comment]
Those will all be applied, unilaterally, if they need to be.

update_git - if the revision is not present
install_roles/install_collections - if the dependencies are not present in the cache

To not do them would not run the job reliably.

**Comment by bgeels** [comment]
For **update_git**, is revision the most recent revision according to what the configured SCM says? If so is there a way to tell it that it's ok if _a revision_ exists? i.e. as long as we've checked out the project at some point and it still exists we're good.

Then for **install_roles/install_collections**. What triggers the cache to be cleared for a given **role** or **collection**? Any way to stop that from occurring?

> To not do them would not run the job reliably.
This is b/c any of these things ( scm checkout, role, or collection ) may not exist or is there something else to consider there?

**Comment by wenottingham** [comment]
> For update_git, is revision the most recent revision according to what the configured SCM says?

It is the revision that was recorded in the last project update. This isn't configurable, as we want to make sure that if the project says it's using revsion abcdef, that all job runs will use that revision.

> Then for install_roles/install_collections. What triggers the cache to be cleared for a given role or collection?

It's tied to the ID of a project update used for a previous job run. So if a prior job run on the node used project udpate id 12345, that's what the cache ID is keyed off of. If another project update happens, or is needed (because something is missing) the cache is invalidated.

**Comment by bgeels** [comment]
Ok so if I'm understanding correctly none of those tags should be applied unless a project was re-synced? Also, a project will not be re-synced unless it's manually re-synced or the **SCM Update Option**, **Update Revision on Launch** is checked for the project?

**Comment by wenottingham** [comment]
Or if the content hasn't been synced to the node the job is running on.

**Comment by bgeels** [comment]
Gotcha, ok. I think I may have seen a scenario where those tags were applied outside of that criteria. Need to watch it closely and see if it happens again. I'm not on the latest, currently running 13.0.0. However, I didn't see anything in the change logs that would suggest a recent related bug fix. Thank you for your thorough replies, I really appreciate it!
