### ISSUE TITLE
notification_templates module uses python str instead of json

### ISSUE THREAD

**Issue by jfugate** [ansible/awx#8334]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When trying to apply notification_template configs via yaml, it fails to transform a message from python dict to json

##### ENVIRONMENT
* AWX version: 15.0.0
* AWX install method: official AWX installer + k8s
* Ansible version:  2.9.13
* Operating System: Linux
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Deploy version 15.0.0 per official awx installer on k8s. 
Create playbook to create a notification_template ex:
```
---
- name: foobar
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
 
  tasks:
  - name: Add AWX Notifications Test
    collections: [awx.awx]
    vars:
      default_values:
        state: present
    tower_notification:
        name: Dummy
        description: ''
        organization: my org
        notification_type: 'pagerduty'
        notification_configuration:
          token: '$encrypted'
          subdomain: subdomain.pagerduty.com
          service_key: "mysecretkey"
          client_name: 'AWX'
```
##### EXPECTED RESULTS

Notification template deployed/created.

##### ACTUAL RESULTS

Stack trace stating that there is invalid json (uses python dict instead)

##### ADDITIONAL INFORMATION

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: tower_cli.exceptions.TowerCLIError: Provided json file format invalid. Please recheck.
fatal: [localhost]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "/opt/barracuda/awx-shared/venvs/playbooks-bco/lib/python3.6/site-packages/tower_cli/resources/notification_template.py", line 169, in _separate
        data = json.loads(result[field])
      File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib64/python3.6/json/decoder.py", line 355, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
 
    During handling of the above exception, another exception occurred:
 
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-tmp-1602009561.7266166-3109-195595476711391/AnsiballZ_tower_notification.py", line 102, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-tmp-1602009561.7266166-3109-195595476711391/AnsiballZ_tower_notification.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-tmp-1602009561.7266166-3109-195595476711391/AnsiballZ_tower_notification.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible.modules.web_infrastructure.ansible_tower.tower_notification', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_tower_notification_payload_zix_f93j/ansible_tower_notification_payload.zip/ansible/modules/web_infrastructure/ansible_tower/tower_notification.py", line 393, in <module>
      File "/tmp/ansible_tower_notification_payload_zix_f93j/ansible_tower_notification_payload.zip/ansible/modules/web_infrastructure/ansible_tower/tower_notification.py", line 379, in main
      File "/opt/barracuda/awx-shared/venvs/playbooks-bco/lib/python3.6/site-packages/tower_cli/resources/notification_template.py", line 300, in modify
        self.get(**copy.deepcopy(kwargs))
      File "/opt/barracuda/awx-shared/venvs/playbooks-bco/lib/python3.6/site-packages/tower_cli/resources/notification_template.py", line 422, in get
        self._separate(kwargs)
      File "/opt/barracuda/awx-shared/venvs/playbooks-bco/lib/python3.6/site-packages/tower_cli/resources/notification_template.py", line 172, in _separate
        raise exc.TowerCLIError('Provided json file format '
    tower_cli.exceptions.TowerCLIError: Provided json file format invalid. Please recheck.
  module_stdout: |-
    {'token': '$encrypted', 'subdomain': 'subdomain.pagerduty.com', 'service_key': 'mysecretkey', 'client_name': 'AWX'}
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

**Comment by blomquisg** [comment]
@beeankha and @john-westcott-iv, can you take a look at this?

**Comment by john-westcott-iv** [comment]
Can you double check your collection installation? If I look at your stack trace it's referencing TowerCLI:
```
The error was: tower_cli.exceptions.TowerCLIError: Provided json file format invalid.
```
However, the new AWX collection no longer uses TowerCLI.

As a quick test you can try explicitly telling ansible to use tower_notification from awx.awx by calling tower_notification as `awx.awx.tower_notification`:
```
  - name: Add AWX Notifications Test
    collections: [awx.awx]
    vars:
      default_values:
        state: present
    awx.awx.tower_notification:
    ...
```

**Comment by ryanpetrello** [comment]
Yea, this looks to me like something messed up w/ an older version of the software.  Please make sure you're using the latest version of: https://galaxy.ansible.com/awx/awx

**Comment by jfugate** [comment]
Thanks, this helped out actually. I didn't realize the difference between these two:

```
- name: Add AWX Notifications
  collections: [awx.awx]
  tower_notification: "{{ default_values | combine(item) }}"
```
and
```
- name: Add AWX Notifications
  collections: [awx.awx]
  tower_notification_template: "{{ default_values | combine(item) }}"
```

**Comment by simplyprasu** [comment]
Hi Friends,
I need some help to create the ansible notification playbook .I am getting some errors while creating the modules.

{
  "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1655119477.5785654-637-106904318472726/AnsiballZ_notification_template.py\", line 100, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1655119477.5785654-637-106904318472726/AnsiballZ_notification_template.py\", line 92, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1655119477.5785654-637-106904318472726/AnsiballZ_notification_template.py\", line 41, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python2.6/runpy.py\", line 136, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/usr/lib64/python2.6/runpy.py\", line 54, in _run_module_code\r\n    mod_loader, pkg_name)\r\n  File \"/usr/lib64/python2.6/runpy.py\", line 34, in _run_code\r\n    exec code in run_globals\r\n  File \"/tmp/ansible_tower_notification_payload_5SweNg/ansible_tower_notification_payload.zip/ansible_collections/awx/awx/plugins/modules/notification_template.py\", line 316, in <module>\r\n  File \"/tmp/ansible_tower_notification_payload_5SweNg/ansible_tower_notification_payload.zip/ansible_collections/awx/awx/plugins/module_utils/controller_api.py\", line 5, in <module>\r\n  File \"/tmp/ansible_tower_notification_payload_5SweNg/ansible_tower_notification_payload.zip/ansible_collections/awx/awx/plugins/module_utils/controller_module.py\", line 241\r\n    raise ConfigFileException(\"An unknown exception occured trying to ini load config file: {0}\".format(e)) from e\r\n                                                                                                               ^\r\nSyntaxError: invalid syntax\r\n",
  "module_stderr": "Shared connection to vrdevafs001.iggroup.local closed.\r\n",
  "exception": "Traceback (most recent call last):\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1655119477.5785654-637-106904318472726/AnsiballZ_notification_template.py\", line 100, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1655119477.5785654-637-106904318472726/AnsiballZ_notification_template.py\", line 92, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1655119477.5785654-637-106904318472726/AnsiballZ_notification_template.py\", line 41, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python2.6/runpy.py\", line 136, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/usr/lib64/python2.6/runpy.py\", line 54, in _run_module_code\r\n    mod_loader, pkg_name)\r\n  File \"/usr/lib64/python2.6/runpy.py\", line 34, in _run_code\r\n    exec code in run_globals\r\n  File \"/tmp/ansible_tower_notification_payload_5SweNg/ansible_tower_notification_payload.zip/ansible_collections/awx/awx/plugins/modules/notification_template.py\", line 316, in <module>\r\n  File \"/tmp/ansible_tower_notification_payload_5SweNg/ansible_tower_notification_payload.zip/ansible_collections/awx/awx/plugins/module_utils/controller_api.py\", line 5, in <module>\r\n  File \"/tmp/ansible_tower_notification_payload_5SweNg/ansible_tower_notification_payload.zip/ansible_collections/awx/awx/plugins/module_utils/controller_module.py\", line 241\r\n    raise ConfigFileException(\"An unknown exception occured trying to ini load config file: {0}\".format(e)) from e\r\n                                                                                                               ^\r\nSyntaxError: invalid syntax\r\n",
  "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
  "rc": 1,
  "_ansible_no_log": false,
  "changed": false
}

**Comment by john-westcott-iv** [comment]
@simplyprasu, this message looks more like a request for help than a bug report. From a quick look it appears like an issue with how you are setting up your task in your playbook. Please reach out to the [AWX mailing list or IRC channel](https://github.com/ansible/awx/tree/devel/#get-involved) for support; it would be helpful if you included the task from your playbook that is failing along with these messages. In the future, the mailing list would be the best place for support or, if what you have appears to be an actual bug, opening a new github issue would be better than responding to a closed thread. Closed issues are typically not monitored.
