### ISSUE TITLE
Inventory Source Details Missing in 15.0.0

### ISSUE THREAD

**Issue by JRNC** [ansible/awx#8335]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After updating from 13.0.0 to 15.0.0 you cannot view the details of inventory sources.
![image](https://user-images.githubusercontent.com/62308097/95251566-bf1c2800-07e9-11eb-9436-4d6e852a07b9.png)

##### ENVIRONMENT
* AWX version: 15.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.13
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Update to 15.0.0 with pre-existing inventory sources and then attempt to view or edit their details.

##### EXPECTED RESULTS

Able to view inventory source details.

##### ACTUAL RESULTS

An unresolved variable "{{ name }}" appears and none of the inventory details

**Comment by JRNC** [comment]
There are also issues with creating a new inventory source in 15.0.0:

![image](https://user-images.githubusercontent.com/62308097/95252095-82046580-07ea-11eb-9cbd-7a11f4e75e90.png)

**Comment by JRNC** [comment]
These appear to be frontend issues, as syncs of pre-existing sources appear to still work properly.

**Comment by wenottingham** [comment]
@jakemcdermott @mabashian can you have someone see what's up here?

**Comment by jakemcdermott** [comment]
@JRNC I haven't been able to reproduce this bug based on the information you've provided so far. Would you please provide some exact steps to reproduce from a clean starting state? (specific inventory and inventory input values used, pages visited, etc.) 

If you see any errors in your browser's logs (Open dev tools by pressing F12 before the bug happens), please also include those in the bug report as well. Thank you!

**Comment by jakemcdermott** [comment]
@wenottingham @JRNC it's possible you _may_ be running into something we listed in the changelogs for v13, which mentions that some inventory sources will no longer work.

https://github.com/ansible/awx/commit/f76c57b1ec9fd994d759c058eb16c4456790b6a6#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR5

**Comment by JRNC** [comment]
I believe that there may have been a delay in some type of post-upgrade management job in 15.0.0 that converts the source variables. Today, the bug is no longer exhibited, but the source variables for all of my inventory sources have been reformatted to start with compose: followed by a much longer set of indented variables. I guess my issue has resolved itself, but I believe that there may be a delay in the job that is doing this reformatting that could cause issues/confusion for folks if they attempt to work in the inventories section shortly after install/upgrade..

**Comment by jakemcdermott** [comment]
@JRNC  Yep, that sounds likely. Any post-install jobs or migration tasks won't be instantaneous. We _usually_ try and show a migration page ("Awx is currently loading") but it doesn't happen in all cases or for all types of tasks.

Overall it sounds like the original issue is resolved for you though so I'm going to close this.
