### ISSUE TITLE
[RFE] Add visual cues to UI

### ISSUE THREAD

**Issue by mdinwoodie** [ansible/awx#8336]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
This RFE is to add more visual cues to the user interface. As an example: when a label is applied to a job template, assign a unique color-coded background to the list item on the Templates screen (each label would have a different color).

**Comment by wenottingham** [comment]
That does not work when templates can have any number of labels.

#2058 seems like a better answer.
