### ISSUE TITLE
tower_job_template.py

### ISSUE THREAD

**Issue by jpell958** [ansible/awx#8338]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Similar to our issue #7766, we found that this module ignores setting any job template Boolean or Integer parameter values, to its default value.  For example the following parameters can no longer be set as Zero or False after it has been modified via GUI or Tower_Module

        timeout: 3600
        allow_simultaneous: true
        ask_limit_on_launch: true

We only tested a handful of parameters but expect that they all behave in the same way.  We request that all parameters for this module be fully tested

##### ENVIRONMENT

- AWX version: 13.0.0
- AWX install method: we developed an Ansible script to install
- Ansible version: 2.9.11
- Operating System: RHEL Linux 7
- Web Browser: Chromium Edge

##### STEPS TO REPRODUCE

Set any parameter value to something other than its default via GUI or tower_job_template module and then try to set the value back to its default value using tower_job_template module.

##### EXPECTED RESULTS

Module should follow the behavior of AWX GUI and allow parameters to be changed back to their default values

##### ACTUAL RESULTS

Parameter value remains as previously set and will not change back to its default value as directed by tower_job_template payload parameters

##### ADDITIONAL INFORMATION

none

**Comment by wenottingham** [comment]
What version of the module? Is it from the 13.0 collection?

**Comment by jpell958** [comment]
Yes - We are using Tower Module 13 with AWX 13
BTW - Same behavior on AWX 15and Modules 15- just tested today
