### ISSUE TITLE
Host details variables showing JSON format without indentation on load

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#8343]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Host details variables showing JSON format without indentation on load

##### ENVIRONMENT
* AWX version: 15.0.0
* AWX install method:docker for mac
* Ansible version:  2.9.13
* Operating System: Catalina
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Navigate to Hosts
2. Select a host which has variables

##### EXPECTED RESULTS

The CodeMirror should show the JSON indented 

##### ACTUAL RESULTS

The JSON is displayed without indentation

##### ADDITIONAL INFORMATION

![host](https://user-images.githubusercontent.com/12464858/95344624-3ad0b000-0890-11eb-9b4a-11f00ac154fd.gif)

**Comment by mabashian** [comment]
@tiagodread lets retest this one - I think this has probably been fixed since it was filed.

**Comment by tiagodread** [comment]
This is now fixed with ace editor
