### ISSUE TITLE
Provide an interface to display when AWX is upgrading

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#8355]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
We currently have https://github.com/ansible/awx/blob/devel/awx/ui/client/installing.template.ejs that gets displayed via this view: https://github.com/ansible/awx/blob/d8c4f118c23fde9f59f38334974381264d22f120/awx/ui/views.py#L26-L30.  Technically we could continue to use this template so long as it's included in the bundle.

I'm creating this issue so that we don't forget to either:

A) Make sure that installing.template.ejs continues to work with ui_next
or
B) Build a view like this using React/PF

**Comment by akus062381** [comment]
QE needs to add coverage here.

**Comment by unlikelyzero** [comment]
This feature was not tested by QE pre-merge so we will need regular feature testing to occur before it's closed

**Comment by tiagodread** [comment]
Tested manually and the logo has a brand text in white along with the background white you can't read the text.
cc @mabashian @wenottingham 
![Screenshot from 2021-05-19 16-14-01](https://user-images.githubusercontent.com/12464858/118871522-09a46d80-b8be-11eb-92b8-287fb986999c.png)

The text is also not aligned in 1024x768
![image](https://user-images.githubusercontent.com/12464858/118872818-5fc5e080-b8bf-11eb-80b8-8bc3e1d6c14e.png)

**Comment by tiagodread** [comment]
Steps to verify this page:

Edit  the file `/var/lib/awx/venv/awx/lib/python3.8/site-packages/awx/main/middleware.py` setting:
```
class MigrationRanCheckMiddleware(MiddlewareMixin):
    def process_request(self, request):
        executor = MigrationExecutor(connection)
        plan = executor.migration_plan(executor.loader.graph.leaf_nodes())
        plan = True
        if bool(plan) and getattr(resolve(request.path), 'url_name', '') != 'migrations_notran':
            return redirect(reverse("ui_next:migrations_notran"))
```
restart the server

**Comment by nixocio** [comment]
This one seems to be a regression related to rename of the products. 

@tiagodread https://github.com/ansible/awx/pull/9123#issuecomment-769454116 that was before we changed certain variables. 

https://user-images.githubusercontent.com/9753817/106208976-3ce9b200-6192-11eb-88e8-0b916776554d.gif

**Comment by tiagodread** [comment]
https://user-images.githubusercontent.com/9053044/119563297-5c29d200-bd75-11eb-87ac-65919554b16e.mov
