### ISSUE TITLE
Upgrade lingui library

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#8356]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Upgrade lingui library to latest stable version. 

This will accomplish two goals:
1. Allow for native pseudolocalization support. More about that [here](https://github.com/ansible/awx/issues/9285)
2. Get rid of the console error warnings that is causing so much noise that dev and QE ignore valuable information

<img width="872" alt="image" src="https://user-images.githubusercontent.com/9053044/95508753-78f9cc80-0981-11eb-87a8-e61ccd7b6123.png">

**Comment by unlikelyzero** [comment]
Before this merges, we should try to measure console log output from cypress between branches

**Comment by AlexSCorey** [comment]
@unlikelyzero I was also thinking that we should do visual regression testing on it as well.

**Comment by mabashian** [comment]
https://lingui.js.org/releases/migration-3.html

**Comment by rooftopcellist** [comment]
This will also allow us to run `lingui extract-template` to create `messages.pot` for the UI strings.  This is needed for translations.  

I have tested this out with `@lingui/cli@3.4.0`.  There are other changes needed to get the build/complile targets working, but it worked for running `extract-template`.  

In case it is useful to whoever works on this feature, my diff was:
```
[chadams@chadams-work awx]$ git diff awx/ui_next/package.json
diff --git a/awx/ui_next/package.json b/awx/ui_next/package.json
index 0d470a17ca..7b2f350a0d 100644
--- a/awx/ui_next/package.json
+++ b/awx/ui_next/package.json
@@ -32,7 +32,7 @@
   "devDependencies": {
     "@babel/polyfill": "^7.8.7",
     "@cypress/instrument-cra": "^1.4.0",
-    "@lingui/cli": "^2.9.2",
+    "@lingui/cli": "^3.4.0",
     "@lingui/macro": "^2.9.1",
     "@nteract/mockument": "^1.0.4",
     "babel-core": "^7.0.0-bridge.0",
@@ -64,6 +64,7 @@
     "lint": "eslint --ext .js --ext .jsx .",
     "add-locale": "lingui add-locale",
     "extract-strings": "lingui extract",
+    "extract-template": "lingui extract-template",
     "compile-strings": "lingui compile",
```

Then I installed it and ran the extract-template command:
```
npm install @lingui/cli@3.4.0
npm --prefix awx/ui_next --loglevel warn run extract-template
```

**Comment by rooftopcellist** [comment]
These `lingui` [configuration docs](https://lingui.js.org/ref/conf.html#locales) will probably be useful as well.  We will need to add the following to `ui_next/.linguirc`

```
 "locales": ["es", "fr", "nl", "ja", "zh"],
```

**Comment by AlexSCorey** [comment]
This has been completed with the merge of https://github.com/ansible/awx/pull/9537
