### ISSUE TITLE
How to delete pending jobs 

### ISSUE THREAD

**Issue by wbieniek** [ansible/awx#8357]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I have thousands pending jobs stuck in AWX cluster and none are being process.
Old method is not working 

from awx.main.models import UnifiedJob
for i in UnifiedJob.objects.filter():
    if(i.status == 'pending'):
      i.delete()

##### ENVIRONMENT
* AWX version: 13.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by ryanpetrello** [comment]
Something like this work?

```python
from awx.main.models import UnifiedJob
UnifiedJob.objects.filter(status='pending').delete()
```

**Comment by wbieniek** [comment]
I was abled to used this code below, but this time was not working. End up restarting pods and resubmitting code below and worked as it should. 

from awx.main.models import UnifiedJob
for i in UnifiedJob.objects.filter():
    if(i.status == 'pending'):
      i.delete()
