### ISSUE TITLE
awx cli extra_vars not working

### ISSUE THREAD

**Issue by Besstheone** [ansible/awx#8359]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
awxkit (version 15.0.0) not accepting extra_vars on prompt but working with files

##### ENVIRONMENT
* AWX version: 15.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.13
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

call awx cli with extravars
![image](https://user-images.githubusercontent.com/39663221/95584991-773e1080-0a36-11eb-8628-a9b707ede94b.png)

##### EXPECTED RESULTS
job launched
##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/39663221/95585011-81f8a580-0a36-11eb-96f1-0940460c54d4.png)

**Comment by ryanpetrello** [comment]
Hey @Besstheone,

The `--extra-vars` argument is supposed to be valid JSON/YAML, not Ansible-style extra vars.  I'll open a PR that clarifies this a bit (instead of this confusing error message).

**Comment by kdelee** [comment]
@elyezer happened to be in the neighborhood and tried this out, I think we can close it

This command:
```
awx job_templates launch --extra_vars vm_name=foo
```

makes this error come out:
```
awx job_templates launch: argument --extra_vars: vm_name=foo is not valid JSON or YAML
```
