### ISSUE TITLE
RFE: Add configurable verbosity for all log aggregator handlers

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/awx#836]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

Some log handlers like activity stream might cause issues with logging servers due to the sheer volume of events sent from AWX/Tower. This request is to add configurable fields to switch off certain events from being sent through the log aggregator to the logging server without having to filter on the logging server side.

##### ENVIRONMENT
* AWX version: 1+

**Comment by wenottingham** [comment]
activity streams don't have any concept that could conceivably be treated as verbosity to filter on. If activity stream is creating such a volume (compared to thing like job events), that is likely a bug that should be tracked and fixed in that context.
