### ISSUE TITLE
TESTING.md failing ansible sanity test

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#8360]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

```
The test `ansible-test sanity --test no-smart-quotes` failed with 2 errors:
Stacktrace
TESTING.md:12:4: use ASCII quotes `'` and `"` instead of Unicode quotes
TESTING.md:59:68: use ASCII quotes `'` and `"` instead of Unicode quotes
```

The collections test are failing on this, needs to get fixed. Not sure if its a matter of ignoring that file or if that file has to conform the the rules around quotation marks as well.

**Comment by kdelee** [comment]
looks like there is a PR up for it https://github.com/ansible/awx/pull/8306

**Comment by ryanpetrello** [comment]
I think this is ready to verify @kdelee

**Comment by ryanpetrello** [comment]
This is working now, so I'm gonna close it:

![image](https://user-images.githubusercontent.com/214912/95901513-77ede400-0d61-11eb-8c95-a1abf774f207.png)
