### ISSUE TITLE
Merge Add Dropdown buttons for List Toolbar

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#8361]
##### ISSUE TYPE
-enhancement

##### SUMMARY
We have 2 buttons to add a dropdown to a toolbar for a list.  1 is AddDropDownButton (https://github.com/ansible/awx/blob/019ad9da738eb84f78abfa38034692645f1d89bb/awx/ui_next/src/components/AddDropDownButton/AddDropDownButton.jsx) and the other is AddDropdown, which will merge with https://github.com/ansible/awx/pull/8263.  

These 2 buttons should be merged.  We also want to be sure that we have enhanced unit testing when we do merge them.  This to be aware of are:
1) Whether clicking opens a modal, or navigates to an add form.
2) What happens to the button when Advance Search is activated. It should render the dropdown items as a string, but as a button.
3) During Advance Search, if the user clicks add to open a modal, be sure the modal does not close erroneously.

This is blocked until https://github.com/ansible/awx/pull/8263 merges

**Comment by tiagodread** [comment]
PR already merged and test in place
