### ISSUE TITLE
api/v2/metrics/?format=json missing data

### ISSUE THREAD

**Issue by dnguyen9** [ansible/awx#8362]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

/api/v2metrics/format=json endpoint is missing critical information related to other nodes when clustered together such as 

awx_instance_consumed_capacity
awx_instance_remaining_capacity
awx_instance_status_total
awx_instance_launch_type_total
awx_instance_info
awx_instance_cpu
awx_instance_capacity

##### ENVIRONMENT
* AWX version: 15
* AWX install method: custom
* Ansible version:  2.9
* Operating System: Windows 10
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Hit the endpoint as json. 

##### EXPECTED RESULTS

expect json format should have the same as api/text format.
<div>
# HELP awx_system_info AWX System Information
# TYPE awx_system_info gauge
awx_system_info{ansible_version="2.9.14",external_logger_enabled="True",external_logger_type="splunk",insights_analytics="False",install_uuid="8722b59e-67e0-4883-a310-6fe76428ced5",license_expiry="0",license_type="open",pendo_tracking="off",tower_url_base="https://vio-awx1.nj.lab.corporate.com",tower_version="15.0.0"} 1.0
# HELP awx_organizations_total Number of organizations
# TYPE awx_organizations_total gauge
awx_organizations_total 1.0
# HELP awx_users_total Number of users
# TYPE awx_users_total gauge
awx_users_total 1.0
# HELP awx_teams_total Number of teams
# TYPE awx_teams_total gauge
awx_teams_total 0.0
# HELP awx_inventories_total Number of inventories
# TYPE awx_inventories_total gauge
awx_inventories_total 3.0
# HELP awx_projects_total Number of projects
# TYPE awx_projects_total gauge
awx_projects_total 3.0
# HELP awx_job_templates_total Number of job templates
# TYPE awx_job_templates_total gauge
awx_job_templates_total 3.0
# HELP awx_workflow_job_templates_total Number of workflow job templates
# TYPE awx_workflow_job_templates_total gauge
awx_workflow_job_templates_total 0.0
# HELP awx_hosts_total Number of hosts
# TYPE awx_hosts_total gauge
awx_hosts_total{type="all"} 2.0
awx_hosts_total{type="active"} 2.0
# HELP awx_schedules_total Number of schedules
# TYPE awx_schedules_total gauge
awx_schedules_total 4.0
# HELP awx_inventory_scripts_total Number of invetory scripts
# TYPE awx_inventory_scripts_total gauge
awx_inventory_scripts_total 0.0
# HELP awx_sessions_total Number of sessions
# TYPE awx_sessions_total gauge
awx_sessions_total{type="all"} 1.0
awx_sessions_total{type="user"} 1.0
awx_sessions_total{type="anonymous"} 0.0
# HELP awx_custom_virtualenvs_total Number of virtualenvs
# TYPE awx_custom_virtualenvs_total gauge
awx_custom_virtualenvs_total 1.0
# HELP awx_running_jobs_total Number of running jobs on the Tower system
# TYPE awx_running_jobs_total gauge
awx_running_jobs_total 0.0
# HELP awx_pending_jobs_total Number of pending jobs on the Tower system
# TYPE awx_pending_jobs_total gauge
awx_pending_jobs_total 0.0
# HELP awx_status_total Status of Job launched
# TYPE awx_status_total gauge
awx_status_total{status="successful"} 16.0
# HELP awx_instance_capacity Capacity of each node in a Tower system
# TYPE awx_instance_capacity gauge
awx_instance_capacity{hostname="awx-isolated-01.nj.lab.corporate.com",instance_uuid="4224b774-ff7a-8496-9dc4-0895561fa75f"} 0.0
awx_instance_capacity{hostname="awx-isolated-02.nj.lab.corporate.com",instance_uuid="4224f2d3-6844-df70-c2d4-7bddeff74290"} 0.0
awx_instance_capacity{hostname="awx-isolated-03.nj.lab.corporate.com",instance_uuid="4224a483-ef81-c07b-e9df-feb0330d2530"} 0.0
awx_instance_capacity{hostname="vio-awx1.nj.lab.corporate.com",instance_uuid="4224675c-2702-267e-1a08-d8318c974b66"} 606.0
awx_instance_capacity{hostname="vio-awx3.nj.lab.corporate.com",instance_uuid="4224e8f2-f0f8-baf8-e110-7c70fea95cd2"} 606.0
awx_instance_capacity{hostname="vio-awx4.nj.lab.corporate.com",instance_uuid="42244c26-57b1-2296-b0d4-9ea3a7b0a808"} 606.0
# HELP awx_instance_cpu CPU cores on each node in a Tower system
# TYPE awx_instance_cpu gauge
awx_instance_cpu{hostname="awx-isolated-01.nj.lab.corporate.com",instance_uuid="4224b774-ff7a-8496-9dc4-0895561fa75f"} 0.0
awx_instance_cpu{hostname="awx-isolated-02.nj.lab.corporate.com",instance_uuid="4224f2d3-6844-df70-c2d4-7bddeff74290"} 0.0
awx_instance_cpu{hostname="awx-isolated-03.nj.lab.corporate.com",instance_uuid="4224a483-ef81-c07b-e9df-feb0330d2530"} 0.0
awx_instance_cpu{hostname="vio-awx1.nj.lab.corporate.com",instance_uuid="4224675c-2702-267e-1a08-d8318c974b66"} 8.0
awx_instance_cpu{hostname="vio-awx3.nj.lab.corporate.com",instance_uuid="4224e8f2-f0f8-baf8-e110-7c70fea95cd2"} 8.0
awx_instance_cpu{hostname="vio-awx4.nj.lab.corporate.com",instance_uuid="42244c26-57b1-2296-b0d4-9ea3a7b0a808"} 8.0
# HELP awx_instance_memory RAM (Kb) on each node in a Tower system
# TYPE awx_instance_memory gauge
awx_instance_memory{hostname="awx-isolated-01.nj.lab.corporate.com",instance_uuid="4224b774-ff7a-8496-9dc4-0895561fa75f"} 0.0
awx_instance_memory{hostname="awx-isolated-02.nj.lab.corporate.com",instance_uuid="4224f2d3-6844-df70-c2d4-7bddeff74290"} 0.0
awx_instance_memory{hostname="awx-isolated-03.nj.lab.corporate.com",instance_uuid="4224a483-ef81-c07b-e9df-feb0330d2530"} 0.0
awx_instance_memory{hostname="vio-awx1.nj.lab.corporate.com",instance_uuid="4224675c-2702-267e-1a08-d8318c974b66"} 6.5705582592e+010
awx_instance_memory{hostname="vio-awx3.nj.lab.corporate.com",instance_uuid="4224e8f2-f0f8-baf8-e110-7c70fea95cd2"} 6.5705582592e+010
awx_instance_memory{hostname="vio-awx4.nj.lab.corporate.com",instance_uuid="42244c26-57b1-2296-b0d4-9ea3a7b0a808"} 6.5705582592e+010
# HELP awx_instance_info Info about each node in a Tower system
# TYPE awx_instance_info gauge
awx_instance_info{enabled="True",hostname="awx-isolated-01.nj.lab.corporate.com",instance_uuid="4224b774-ff7a-8496-9dc4-0895561fa75f",last_isolated_check="None",managed_by_policy="True",version=""} 1.0
awx_instance_info{enabled="True",hostname="awx-isolated-02.nj.lab.corporate.com",instance_uuid="4224f2d3-6844-df70-c2d4-7bddeff74290",last_isolated_check="None",managed_by_policy="True",version=""} 1.0
awx_instance_info{enabled="True",hostname="awx-isolated-03.nj.lab.corporate.com",instance_uuid="4224a483-ef81-c07b-e9df-feb0330d2530",last_isolated_check="None",managed_by_policy="True",version=""} 1.0
awx_instance_info{enabled="True",hostname="vio-awx1.nj.lab.corporate.com",instance_uuid="4224675c-2702-267e-1a08-d8318c974b66",last_isolated_check="None",managed_by_policy="True",version="15.0.0"} 1.0
awx_instance_info{enabled="True",hostname="vio-awx3.nj.lab.corporate.com",instance_uuid="4224e8f2-f0f8-baf8-e110-7c70fea95cd2",last_isolated_check="None",managed_by_policy="True",version="15.0.0"} 1.0
awx_instance_info{enabled="True",hostname="vio-awx4.nj.lab.corporate.com",instance_uuid="42244c26-57b1-2296-b0d4-9ea3a7b0a808",last_isolated_check="None",managed_by_policy="True",version="15.0.0"} 1.0
# HELP awx_instance_launch_type_total Type of Job launched
# TYPE awx_instance_launch_type_total gauge
awx_instance_launch_type_total{launch_type="dependency",node="vio-awx1.nj.lab.corporate.com"} 6.0
awx_instance_launch_type_total{launch_type="manual",node="vio-awx1.nj.lab.corporate.com"} 9.0
awx_instance_launch_type_total{launch_type="manual",node="vio-awx3.nj.lab.corporate.com"} 1.0
# HELP awx_instance_status_total Status of Job launched
# TYPE awx_instance_status_total gauge
awx_instance_status_total{node="vio-awx1.nj.lab.corporate.com",status="successful"} 15.0
awx_instance_status_total{node="vio-awx3.nj.lab.corporate.com",status="successful"} 1.0
# HELP awx_instance_consumed_capacity Consumed capacity of each node in a Tower system
# TYPE awx_instance_consumed_capacity gauge
awx_instance_consumed_capacity{hostname="awx-isolated-01.nj.lab.corporate.com",instance_uuid="4224b774-ff7a-8496-9dc4-0895561fa75f"} 0.0
awx_instance_consumed_capacity{hostname="awx-isolated-02.nj.lab.corporate.com",instance_uuid="4224f2d3-6844-df70-c2d4-7bddeff74290"} 0.0
awx_instance_consumed_capacity{hostname="awx-isolated-03.nj.lab.corporate.com",instance_uuid="4224a483-ef81-c07b-e9df-feb0330d2530"} 0.0
awx_instance_consumed_capacity{hostname="vio-awx1.nj.lab.corporate.com",instance_uuid="4224675c-2702-267e-1a08-d8318c974b66"} 0.0
awx_instance_consumed_capacity{hostname="vio-awx3.nj.lab.corporate.com",instance_uuid="4224e8f2-f0f8-baf8-e110-7c70fea95cd2"} 0.0
awx_instance_consumed_capacity{hostname="vio-awx4.nj.lab.corporate.com",instance_uuid="42244c26-57b1-2296-b0d4-9ea3a7b0a808"} 0.0
# HELP awx_instance_remaining_capacity Remaining capacity of each node in a Tower system
# TYPE awx_instance_remaining_capacity gauge
awx_instance_remaining_capacity{hostname="awx-isolated-01.nj.lab.corporate.com",instance_uuid="4224b774-ff7a-8496-9dc4-0895561fa75f"} 0.0
awx_instance_remaining_capacity{hostname="awx-isolated-02.nj.lab.corporate.com",instance_uuid="4224f2d3-6844-df70-c2d4-7bddeff74290"} 0.0
awx_instance_remaining_capacity{hostname="awx-isolated-03.nj.lab.corporate.com",instance_uuid="4224a483-ef81-c07b-e9df-feb0330d2530"} 0.0
awx_instance_remaining_capacity{hostname="vio-awx1.nj.lab.corporate.com",instance_uuid="4224675c-2702-267e-1a08-d8318c974b66"} 606.0
awx_instance_remaining_capacity{hostname="vio-awx3.nj.lab.corporate.com",instance_uuid="4224e8f2-f0f8-baf8-e110-7c70fea95cd2"} 606.0
awx_instance_remaining_capacity{hostname="vio-awx4.nj.lab.corporate.com",instance_uuid="42244c26-57b1-2296-b0d4-9ea3a7b0a808"} 606.0
# HELP awx_license_instance_total Total number of managed hosts provided by your license
# TYPE awx_license_instance_total gauge
awx_license_instance_total 0.0
# HELP awx_license_instance_free Number of remaining managed hosts provided by your license
# TYPE awx_license_instance_free gauge
awx_license_instance_free 0.0
</div>
##### ACTUAL RESULTS

Note i am hitting my "https://vio-awx1.nj.lab.corporate.com" and it is returning result for vio-awx4 nodes
`{
  "awx_system_info": {
    "labels": {
      "ansible_version": "2.9.14",
      "external_logger_enabled": "True",
      "external_logger_type": "splunk",
      "insights_analytics": "False",
      "install_uuid": "8722b59e-67e0-4883-a310-6fe76428ced5",
      "license_expiry": "0",
      "license_type": "open",
      "pendo_tracking": "off",
      "tower_url_base": "https://vio-awx1.nj.lab.corporate.com",
      "tower_version": "15.0.0"
    },
    "value": 1
  },
  "awx_organizations_total": {
    "labels": {},
    "value": 1
  },
  "awx_users_total": {
    "labels": {},
    "value": 1
  },
  "awx_teams_total": {
    "labels": {},
    "value": 0
  },
  "awx_inventories_total": {
    "labels": {},
    "value": 3
  },
  "awx_projects_total": {
    "labels": {},
    "value": 3
  },
  "awx_job_templates_total": {
    "labels": {},
    "value": 3
  },
  "awx_workflow_job_templates_total": {
    "labels": {},
    "value": 0
  },
  "awx_hosts_total": {
    "labels": {
      "type": "active"
    },
    "value": 2
  },
  "awx_schedules_total": {
    "labels": {},
    "value": 4
  },
  "awx_inventory_scripts_total": {
    "labels": {},
    "value": 0
  },
  "awx_sessions_total": {
    "labels": {
      "type": "anonymous"
    },
    "value": 0
  },
  "awx_custom_virtualenvs_total": {
    "labels": {},
    "value": 1
  },
  "awx_running_jobs_total": {
    "labels": {},
    "value": 0
  },
  "awx_pending_jobs_total": {
    "labels": {},
    "value": 0
  },
  "awx_status_total": {
    "labels": {
      "status": "successful"
    },
    "value": 16
  },
  "awx_instance_capacity": {
    "labels": {
      "hostname": "vio-awx4.nj.lab.corporate.com",
      "instance_uuid": "42244c26-57b1-2296-b0d4-9ea3a7b0a808"
    },
    "value": 606
  },
  "awx_instance_cpu": {
    "labels": {
      "hostname": "vio-awx4.nj.lab.corporate.com",
      "instance_uuid": "42244c26-57b1-2296-b0d4-9ea3a7b0a808"
    },
    "value": 8
  },
  "awx_instance_memory": {
    "labels": {
      "hostname": "vio-awx4.nj.lab.corporate.com",
      "instance_uuid": "42244c26-57b1-2296-b0d4-9ea3a7b0a808"
    },
    "value": 65705582592
  },
  "awx_instance_info": {
    "labels": {
      "enabled": "True",
      "hostname": "vio-awx4.nj.lab.corporate.com",
      "instance_uuid": "42244c26-57b1-2296-b0d4-9ea3a7b0a808",
      "last_isolated_check": "None",
      "managed_by_policy": "True",
      "version": "15.0.0"
    },
    "value": 1
  },
  "awx_instance_launch_type_total": {
    "labels": {
      "launch_type": "manual",
      "node": "vio-awx3.nj.lab.corporate.com"
    },
    "value": 1
  },
  "awx_instance_status_total": {
    "labels": {
      "node": "vio-awx3.nj.lab.corporate.com",
      "status": "successful"
    },
    "value": 1
  },
  "awx_instance_consumed_capacity": {
    "labels": {
      "hostname": "vio-awx4.nj.lab.corporate.com",
      "instance_uuid": "42244c26-57b1-2296-b0d4-9ea3a7b0a808"
    },
    "value": 0
  },
  "awx_instance_remaining_capacity": {
    "labels": {
      "hostname": "vio-awx4.nj.lab.corporate.com",
      "instance_uuid": "42244c26-57b1-2296-b0d4-9ea3a7b0a808"
    },
    "value": 606
  },
  "awx_license_instance_total": {
    "labels": {},
    "value": 0
  },
  "awx_license_instance_free": {
    "labels": {},
    "value": 0
  }
}`

**Comment by wenottingham** [comment]
filed twice
