### ISSUE TITLE
Add logic for management jobs

### ISSUE THREAD

**Issue by blaira89** [ansible/awx#8371]
##### SUMMARY
 - Currently, removing old activity stream data is simple expiration style
 - This leads to history for job templates not run prior to X date being removed, unable to view historical data for the job template i.e old extra variables
 - Request would be to add logic, such as the ability to keep at least X amount of activity stream logs, per job template
 - Any other logic feature that satisfies the requirements would be valued, if there is a better approach.

**Comment by wenottingham** [comment]
-> #8032
