### ISSUE TITLE
Link workflow approval node to approval details in output

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#8374]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
In workflows with approval steps we should navigate the user to the details view of the approval when they click on the node in the output:

<img width="1622" alt="Screen Shot 2020-10-12 at 2 22 03 PM" src="https://user-images.githubusercontent.com/9889020/95778602-786d7880-0c96-11eb-9f50-f30e74c117db.png">

should take the user to:

<img width="1680" alt="Screen Shot 2020-10-12 at 2 23 02 PM" src="https://user-images.githubusercontent.com/9889020/95778619-7e635980-0c96-11eb-802a-e28b49eff0dd.png">

This would be consistent with our behavior for other node types.

**Comment by mabashian** [comment]
Blocked until #8375 lands

**Comment by akus062381** [comment]
Resolved
