### ISSUE TITLE
Expose the host facts for smart inventories in the UI

### ISSUE THREAD

**Issue by mrmibrown** [ansible/awx#8377]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
This is a request to expose the host facts for smart inventories in the UI.

EXPECTED RESULTS
Host facts can be seen in the UI at: TOWER>INVENTORIES>(SMART_INVENTORY_NAME)>HOSTS>FACTS
There is no 'FACTS' page for smart inventory hosts.

ACTUAL RESULTS
Host facts can only be seen in the UI at: TOWER>INVENTORIES>(INVENTORY_NAME)>HOSTS>FACTS

**Comment by mabashian** [comment]
Note that the new UI currently behaves in the same way.  Host facts are not accessible on a smart inventory host but I think this could be easily added.

**Comment by TheRealHaoLiu** [comment]
Smart inventories is deprecated in favor of constructed inventory 

Check out #13303
