### ISSUE TITLE
I cannot search in the drop-down search box of PlayBook.

### ISSUE THREAD

**Issue by KongNan** [ansible/awx#8378]
##### ISSUE TYPE
 -Bug Report

##### SUMMARY
I tried to enter the full name of the PlayBook file, or part of it, or start from the path. But as soon as you start typing, the PlayBook list below the search box disappears immediately, and no matching PlayBook can be found after pressing Enter.

I was worried whether it was a Chinese character problem, so I changed to a project without Chinese characters, but it also had this problem.

Is there a problem with my operation?

##### ENVIRONMENT
* AWX version: 14.1.0
* AWX install method: docker on linux
* Ansible version: 2.9.11
* Operating System: windows 10
* Web Browser: chrome 85

##### STEPS TO REPRODUCE

* 1、Drop down PlayBook list box
* 2、Type a "p" in the search box 
* 3、Press Enter

##### EXPECTED RESULTS

Show filtered playbooks.

##### ACTUAL RESULTS
The filter result below disappears immediately.
And prompt an error after press Enter.

**Comment by unlikelyzero** [comment]
@kongnan have you had a chance to use the ui_next project?

@jakemcdermott @wenottingham this does not appear to be a component with https://patternfly-react.surge.sh/components/dropdown

Should we make a new github issue to associate the typeahead/embedded search within a dropdown with ui_next as an enhancement?

**Comment by KongNan** [comment]
> @KongNan have you had a chance to use the ui_next project?

Oh, I don't know what's "the ui_next" project.   :(

**Comment by unlikelyzero** [comment]
@KongNan it is the next ui. You can pull it down to test it with these instructions: https://github.com/ansible/awx/tree/devel/awx/ui_next

Adding a link to the RFE https://github.com/ansible/awx/issues/8473

**Comment by AlexSCorey** [comment]
@KongNan @unlikelyzero linking https://github.com/ansible/awx/issues/8473

**Comment by AlexSCorey** [comment]
closing in favor of https://github.com/ansible/awx/issues/8473
