### ISSUE TITLE
configurable max scheduled jobs per template 

### ISSUE THREAD

**Issue by ammygill** [ansible/awx#8379]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
 I have a one particular template which i want to run for more than the number of max scheduled  jobs and I can't increase the max schduled jobs considering the requierement. Currently my jobs are failing after the max scheduled jobs. So looking forward for a solution to either ignore the  “maximum scheduled jobs” setting for that one particular template or the rest of the jobs come in the queue instead of failing.

**Comment by wenottingham** [comment]
Why are you unable to increase SCHEDULE_MAX_JOBS? That's what that configuration parameter is for.

**Comment by ammygill** [comment]
customer is having Project requirements. thats why he can't change the value from 10 to any higher value.

**Comment by wenottingham** [comment]
I'm not sure what you mean by that.

**Comment by wenottingham** [comment]
Closing, recommendation is to set the global flag
