### ISSUE TITLE
Building AWX CLI Documentation docs not clear

### ISSUE THREAD

**Issue by w7089** [ansible/awx#8380]
[Building AWX CLI Documentation ](https://github.com/ansible/awx/blob/devel/INSTALL.md#building-the-cli-documentation ) states:

> 
> To build the docs, spin up a real AWX server, pip install sphinx sphinxcontrib-autoprogram, and run:
> 
> ~ TOWER_HOST=https://awx.example.org TOWER_USERNAME=example TOWER_PASSWORD=secret make clean html
> ~ cd build/html/ && python -m http.server
> Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ..

Where should the commands run? I tried in cloned awx repo and it didn't work.

**Comment by ryanpetrello** [comment]
Hey @w7089,

You're right, these docs are a little unclear - I'll update them.

You'll want to run these commands from the same folder as the CLI source code itself.  I tried a moment ago, and it seems to work for me:

https://github.com/ansible/awx/pull/8382
