### ISSUE TITLE
[15.0] Error starting project Encountered errors while bringing up the project

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/awx#8383]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX fails to start awx_redis container.

##### ENVIRONMENT
* AWX version: 15.0.0
* AWX install method:  docker compose on linux
* Ansible version: 2.10.0
* Operating System: Ubuntu 20.10
* docker-ce: ```5:19.03.13~3-0~ubuntu-focal```

##### STEPS TO REPRODUCE
0.1. Run inside Python3 virtual env
0.2. Install latest ansible, wheel, docker-compose and redis with pip3
1. Checkout 15.0.0 & create new build branch
2. Modify installer/inventory with:
  - awx_official=true
  - docker_compose_dir=/some/folder
  - host_port=<some_available_port>
  - logging_driver=journald
  - pg_database=awx
  - pg_hostname=<some_private_ip_address>
  - pg_password=some_password
  - pg_port=<<some_pg_used_port>
  - pg_sslmode=require
  - pg_username=awx
  - postgres_data_dir=''
  - project_data_dir=/some/other/folder
  - secret_key=some_password
  - use_docker_compose=true
2. Restart PostgreSQL 10 AWX Cluster
3. Build as non-root with:
```
export awx_version="15.0.0"
cd installer
ansible-playbook -i inventory install.yml
```

##### EXPECTED RESULTS

All AWX docker containers should be created & running

##### ACTUAL RESULTS
I removed from the log all skipped tasks:
```
< PLAY [Build and deploy AWX] >
 -----------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

...
< TASK [local_docker : Generate broadcast websocket secret] >
 -----------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [localhost]
...
< TASK [local_docker : Set DockerHub Image Paths] >
 -------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [localhost]
 _______________________________________________________
/ TASK [local_docker : Create                           \
\ /media/SAMSUNG5-Virtual/awx/docker-compose directory] /
 -------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [localhost]
 _____________________________________________________
< TASK [local_docker : Create Redis socket directory] >
 -----------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [localhost]
 ___________________________________________________________
< TASK [local_docker : Create Docker Compose Configuration] >
 -----------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [localhost] => (item={'file': 'environment.sh', 'mode': '0600'})
changed: [localhost] => (item={'file': 'credentials.py', 'mode': '0600'})
changed: [localhost] => (item={'file': 'docker-compose.yml', 'mode': '0600'})
changed: [localhost] => (item={'file': 'nginx.conf', 'mode': '0600'})
changed: [localhost] => (item={'file': 'redis.conf', 'mode': '0664'})
 ______________________________________________
< TASK [local_docker : Render SECRET_KEY file] >
 ----------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [localhost]
 ____________________________________________
< TASK [local_docker : Start the containers] >
 --------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [localhost]: FAILED! => {"changed": false, "errors": [], "module_stderr": "Creating awx_redis ... \n\u001b[1A\u001b[2K\nCreating awx_redis ... \n\u001b[1B", "module_stdout": "latest: Pulling from library/redis\nDigest: sha256:91aef272c7b25e27d0f381ea6bca3e512e94b4922fcb5edb06217c508bc62007\nStatus: Downloaded newer image for redis:latest\n15.0.0: Pulling from ansible/awx\nDigest: sha256:43d7520884870307c3979862770f95744d4dbccae2a9f17586a55c493549ff87\nStatus: Downloaded newer image for ansible/awx:15.0.0\n", "msg": "Error starting project Encountered errors while bringing up the project."}
```
Unfortunately, the container has no log:
```
# docker ps --all
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
a0e94e5e57ee        redis               "docker-entrypoint.s…"   About an hour ago   Created             6379/tcp            awx_redis

# docker logs --details -f awx_redis
#
```

**Comment by ryanpetrello** [comment]
Hey @jean-christophe-manciot,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, you'll probably get a quicker response on our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by jean-christophe-manciot** [comment]
@ryanpetrello 

What makes you think this is not a bug related to AWX itself?
I had no such issue with earlier releases.

**Comment by ryanpetrello** [comment]
Hey @jean-christophe-manciot,

> What makes you think this is not a bug related to AWX itself?

It could be, it's just that we generally avoid triaging issues in this bug tracker (especially installation issues) until we have an explicit way to reproduce, and because we're a small team, we lean a lot on the community via IRC and the mailing list to facilitate that process.

I've just spun up an AWX 15.0.0 on a local Fedora box of mine, and it seems to work fine for me.

I _think_ that `Encountered errors while bringing up the project` is an error from `docker-compose` itself.  Here's the setup I have that's working:

```
~ docker -v
Docker version 19.03.12, build 48a66213fe
~ docker-compose --version
docker-compose version 1.25.4, build unknown
~ cat /etc/os-release
NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
~ grep "^pg_" inventory
pg_hostname=172.19.0.1
pg_username=awx-dev
pg_password=AWXsome1
pg_database=awx-dev
pg_port=5432
~ docker exec -it awx_web bash -c 'sudo yum install nc && nc -vz 172.19.0.1 5432'
Last metadata expiration check: 0:01:48 ago on Thu 15 Oct 2020 01:38:31 PM UTC.
Package nmap-ncat-2:7.70-5.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 172.19.0.1:5432.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
```

![image](https://user-images.githubusercontent.com/214912/96137277-7ab81880-0eca-11eb-9d36-35eeb79df716.png)

**Comment by jean-christophe-manciot** [comment]
@ryanpetrello 

You thought right: forcing ```docker-compose==1.25.4``` instead of the **latest (1.27.4)** is a workaround.
However:
-  1.25.4 is an old version
- it is difficult to conclude that it is a docker-compose issue rather an AWX one given the lack of logging. For instance:
  + the expected format of the docker-compose file may have changed
  + some options may also have changed

**Comment by ryanpetrello** [comment]
Hey @jean-christophe-manciot,

I tried my test again in the same environment using the latest `docker-compose` available on PyPI:

```
~/dev/awx/installer docker-compose -v
docker-compose version 1.27.4, build unknown
~/dev/awx/installer ansible-playbook -i inventory install.yml
```

...and everything comes up just fine for me:

```
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                  NAMES
12b395b9b334        ansible/awx:15.0.0   "/usr/bin/tini -- /u…"   33 seconds ago      Up 31 seconds       8052/tcp               awx_task
d85ddd914603        ansible/awx:15.0.0   "/usr/bin/tini -- /b…"   34 seconds ago      Up 31 seconds       0.0.0.0:80->8052/tcp   awx_web
b34af1c366b0        redis                "docker-entrypoint.s…"   34 seconds ago      Up 31 seconds       6379/tcp               awx_redis
```

![image](https://user-images.githubusercontent.com/214912/96471583-7e66da80-11fd-11eb-9433-d721ffc1a0dc.png)

I'm not exactly sure what's up with your reproduction, but if you find any additional details, or evidence of an AWX bug, please post them here and I'll review.
