### ISSUE TITLE
Project not updated on launch

### ISSUE THREAD

**Issue by stanislaw55** [ansible/awx#8388]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

I have project `A` which has specified Git repository as its source, with branch `master`. SCM Update options which are selected are **Update revision on launch** and **Clean**. After pushing new commit to `master` branch, project `A` is not updated. I have to manually trigger update.

This may look like duplicate of https://github.com/ansible/awx/issues/6535 but it's not since it is not issue with UI but with actual revision used in a project.

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker
* Ansible version:  2.9.10
* Operating System: CentOS 7
* Web Browser: not relevant

##### EXPECTED RESULTS

Project revision is updated to latest commit.

##### ACTUAL RESULTS

Project revision is not updated.

##### ADDITIONAL INFORMATION

Project has `roles/requirements.yml` file with dependencies from private Git repository.

**Comment by blomquisg** [comment]
@beeankha can you try to reproduce this?

**Comment by thedoubl3j** [comment]
hey @stanislaw55 I was unable to reproduce the bug. Do you have any other context to the bug like errors or anything like that? Below is my working environment. 

**Environement**
- AWX version: 15.0.1
- AWX install method: docker
- Ansible version: 2.9.11
- Operating System: Fedora 31
- Web Browser: not relevant

**Comment by stanislaw55** [comment]
Hey @thedoubl3j 
No, unfortunately I have not. Maybe I'll just try to upgrade and see if it works.

**Comment by thedoubl3j** [comment]
sounds good @stanislaw55 if you hit again with an upgrade, drop the steps (as specific as you can make them) here and I will reproduce following those steps. I did this time as well but if it breaks again, I want to get as close to your setup as possible in regards to awx projects etc.

**Comment by stanislaw55** [comment]
Update to newer version fixed it
