### ISSUE TITLE
Trigger "SCM Update" via webhook

### ISSUE THREAD

**Issue by felsgaertner** [ansible/awx#8391]
##### ISSUE TYPE Feature request

Web hooks can be used to start jobs from templates, but not for internal procedures like updating projects.

As a user, I want GitLab (or any other supported SCM) to automatically trigger an SCM project update using a web hook. E.g. a push or merge to the master branch should request a project update on AWX. (Finally the trigger conditions are defined in the web hooks in Gitlab.)

Advantage: the SCM Update runs only on demand, I do neither need to schedule a repeating update job, nor to enable "update on launch" - therefore reducing load on the SCM installation.

##### SUMMARY

SCM Updates are triggered from SCM on demand.

**Comment by garnser** [comment]
This is doable, if you have your pipeline request https://ansibletower/api/v2/projects/<PROJECTID>/update/ and it will trigger an SCM update.

**Comment by wenottingham** [comment]
You can also point the webhook at a workflow that does the project update (and then anything else that is required).

**Comment by felsgaertner** [comment]
@wenottingham , thanks for the hint.

It works, I will close the issue.
