### ISSUE TITLE
Feature: update Django to 1.11 and Celery 4.0

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#84]
### Summary

django-1.8 goes EOL in April 2018. We should upgade to Django-1.11, the latest LTS.

This probably involves fixing a large variety of minor things.

### Environment

* AWX version: now

**Comment by wwitzel3** [comment]
We should consider setting this to `False`
https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-DATABASE-DISABLE_SERVER_SIDE_CURSORS

The documentation for https://docs.djangoproject.com/en/1.11/ref/models/querysets/#django.db.models.query.QuerySet.iterator makes me think we might need to explicitly set it even though the default value for this is `False`. My point is, we want server side cursors for `iterator`.

**Comment by chrismeyersfsu** [comment]
Some thoughts on the new Celery 4.0 features that might benefit us:
* event batching, maybe useful for event processing performance optimization
* pytest plugin. Could remove our is_testing detection code in our production code paths.
* New celery.worker.state.requests enables O(1) loookup of active/reserved tasks by id. Might speed up our querying of active celery tasks that we do in the our periodic database <-> celery rectification. Also in our api/v1/ping output.

There is a large list of changes from 3 -> 4 in Celery that we would have to account for. Doesn't seem to be any fundamental differences that would be show stoppers. http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#upgrading-from-celery-3-1

**Comment by ryanpetrello** [comment]
🎉
