### ISSUE TITLE
Docs: ansible-tower-service not installed in /usr/bin as mentioned

### ISSUE THREAD

**Issue by naltun** [ansible/awx#840]
##### ISSUE TYPE
 - Documentation

##### COMPONENT NAME
 - Installer

##### SUMMARY

The [Ansible Tower Administration Guide docs](https://docs.ansible.com/ansible-tower/latest/html/administration/init_script.html) say, regarding the `ansible-tower-service` script: `The services script resides in /usr/bin/ansible-tower-service`. My instance of AWX does not have the service script in `/usr/bin` like described. After searching through the files, I found the script in `awx/tools/scripts`, where I initially cloned the repo.

##### ENVIRONMENT
* AWX version: 1.0.2 (latest from the master branch as of 2017-12-14)
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: Linux
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Follow the [INSTALL documentation](https://github.com/ansible/awx/blob/devel/INSTALL.md) and install for Docker on Linux.

##### EXPECTED RESULTS

The `ansible-tower-service` script should _also_ be installed in `/usr/bin` but it resides _only_ in `/home/user/awx/tools/scripts/`.

##### ACTUAL RESULTS

`ansible-tower-service` remains outside of `/usr/bin`

##### ADDITIONAL INFORMATION
None

**Comment by matburt** [comment]
This utility is just not included in the AWX distribution because, at the moment anyway, it's just a different layout since the containers are more distributed.

I'd advise, if you need to restart service that you restart the relevant containers.
