### ISSUE TITLE
Add additional filters to dashboard graph

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#8401]
In the transition from nvd3 to using the graphs based on automation analytics line chart, we've lost the status-based and hour-based (last 24 hours) filters.

This tracks adding those back (which will be done after they are added to automation analytics in order to stay in sync.

**Comment by unlikelyzero** [comment]
Marking as enhancement instead of feature in case we want to push past GA

**Comment by tiagodread** [comment]
Missing filter by view successful and failed?
![image](https://user-images.githubusercontent.com/12464858/100460523-1631d100-30a6-11eb-8b3f-18bb159643b7.png)

**Comment by mabashian** [comment]
I'm marking this as `high` but also `blocked`.  @jlmitch5 when you get back lets touch base on this one.

**Comment by unlikelyzero** [comment]
@tiagodread , this should be relatively straightforward to implement

**Comment by mabashian** [comment]
I think we're going to have to roll this ourselves.  Removing the blocked label and putting this back in needs_devel.
