### ISSUE TITLE
Installer missing docker_image command in Ansible 2.10.2

### ISSUE THREAD

**Issue by marcolussetti** [ansible/awx#8407]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Installer does not run in my environment complaining that docker_image cannot be found.

##### ENVIRONMENT
* AWX version: 15.0
* AWX install method: docker on linux
* Ansible version:  2.10.2
* Operating System: Centos 8.2
* Web Browser: N/A

##### STEPS TO REPRODUCE
1. Blank CentOS 8.2 install
2. `pip install ansible`
3. Edit inventory as appropriate
4. Run installer

##### EXPECTED RESULTS
Playbooks run to completion, and AWX is installed.

##### ACTUAL RESULTS
Playbook errors out noting that docker_image is not recognized.

**Comment by marcolussetti** [comment]
Installing the appropriate collection with `ansible-galaxy collection install community.general` fixes the issue.

**Comment by ryanpetrello** [comment]
Install instructions added at: https://github.com/ansible/awx/pull/8408 (thanks @marcolussetti)
