### ISSUE TITLE
"AWX is Upgrading" forever after building 1.0.2.285 and upgrading from 1.0.1.231 on Docker

### ISSUE THREAD

**Issue by worsco** [ansible/awx#841]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

Browser constantly loops page that "AWX is Upgrading" when  upgrading from 1.0.1.231 to 1.0.2.285
##### ENVIRONMENT
* AWX version: 1.0.2.285
* AWX install method: docker on linux
* Ansible version:  2.4.1.0
* Operating System: CentOS Linux release 7.4.1708 (core)
* Web Browser:
Firefox Quantum 57.0.2
##### STEPS TO REPRODUCE

Install and build AWX with Docker using the "ansible-playbook -i inventory install.yml" method using local build (not "official Ansible images") for 1.0.1.231.

Then sync local git repo with AWX github repo.

Build new AWX 1.0.2.285 and using the "ansible-playbook -i inventory install.yml" method using local build (not "official Ansible images").

##### EXPECTED RESULTS

Expected that after containers awx_task and awx_web built and deployed that AWX would migrate in-place and web UI would become available.

##### ACTUAL RESULTS

Browser loops with "AWX is Upgrading"

##### ADDITIONAL INFORMATION

```
# docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                                NAMES
d7d408ddca86        awx_task:1.0.2.285   "/tini -- /bin/sh ..."   About an hour ago   Up About an hour    8052/tcp                             awx_task
3d50773d6458        awx_web:1.0.2.285    "/tini -- /bin/sh ..."   About an hour ago   Up About an hour    0.0.0.0:80->8052/tcp                 awx_web
82de31282fc5        postgres:9.6         "docker-entrypoint..."   2 days ago          Up 2 days           5432/tcp                             postgres
ac0d995dbfa5        memcached:alpine     "docker-entrypoint..."   2 days ago          Up 2 days           11211/tcp                            memcached
3e40a9aa884f        rabbitmq:3           "docker-entrypoint..."   2 weeks ago         Up 2 days           4369/tcp, 5671-5672/tcp, 25672/tcp   rabbitmq
```
```
# docker stats --no-stream
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
d7d408ddca86        0.37%               457.2MiB / 15.51GiB   2.88%               4.21MB / 5.38MB     0B / 1.08MB         12
3d50773d6458        0.16%               653.9MiB / 15.51GiB   4.12%               9.95MB / 7.87MB     106kB / 0B          12
82de31282fc5        0.02%               3.16MiB / 15.51GiB    0.02%               289MB / 220MB       0B / 3.16GB         6
ac0d995dbfa5        0.05%               8.258MiB / 15.51GiB   0.05%               77.3MB / 52.9MB     0B / 0B             10
3e40a9aa884f        0.15%               73.55MiB / 15.51GiB   0.46%               95.1MB / 96.1MB     0B / 596MB          77
```

**Comment by worsco** [comment]
awx_task container logs from after new container build/deployment
[awx_task_container_log.txt](https://github.com/ansible/awx/files/1559680/awx_task_container_log.txt)

awx_web container lgos from after new container build/deployment
[awx_web_container_log.txt](https://github.com/ansible/awx/files/1559681/awx_web_container_log.txt)

**Comment by matburt** [comment]
Please see: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/awx-project/PQLxKl5Rj9s/UGy-3VaCCQAJ

**Comment by worsco** [comment]
acknowledged, thank you, understood ... no simple migration from 1.0.1 to anything higher than 1.0.2.0.
