### ISSUE TITLE
awx.awx.tower_api : Failed to extract token information from login response

### ISSUE THREAD

**Issue by jazzdroid** [ansible/awx#8414]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
  - Collection awx.awx

##### SUMMARY
I trying to use awx.awx.tower_api lookup but I get an error related to token auth.
Failed to extract token information from login response: the JSON object must be str, not 'bytes'

I follow the same example in documentation. I pass my vars directly in the lookup but nothing. 

##### ENVIRONMENT
* AWX version: 3.7.1
* Ansible version:  2.9.11
* Operating System: RHEL7
* collection awx version 15.0.0
* Python = 3.5.1

##### STEPS TO REPRODUCE

User and password are created in   Tower and I can login. Tested with tower_receive module and it's ok.  

Execute: ansible-playbook get_orgs_from_tower.yml
---
    - hosts: localhost
      vars:
        collections:
            - awx.awx
      tasks:
        - name: debug all organizations in a loop  # use query to return a list
          debug:
            msg: "Organization description={{ item['description'] }} id={{ item['id'] }}"
          loop: "{{ query('awx.awx.tower_api', 'organizations', host='myhost', username='myadmin', password='mypassword') }}"
          loop_control:
            label: "{{ item['name'] }}"

##### ACTUAL RESULTS

fatal: [localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'awx.awx.tower_api'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Failed to extract token information from login response: the JSON object must be str, not 'bytes'"
}

##### ADDITIONAL INFORMATION
Also I tried to get a token by uri module using url: "https://host/api/v2/tokens/" with same credentials and it results were ok.

**Comment by jazzdroid** [comment]
I think it's something about encoding in my test machine or python version or some package version. I tested in another and it works. 

In the affected machine I debug the module and it returns in the response of token:  b'{JSON RESPONSE} with a b at the beggining.

**Comment by ryanpetrello** [comment]
@jazzdroid are you using python2 on one machine, and python3 on another (could be a bug in python2 only) cc @beeankha @john-westcott-iv

**Comment by blomquisg** [comment]
@jazzdroid if you're still seeing a problem here, please reopen

**Comment by phgogo** [comment]
I had the same error and spent way to much time debugging it.

The Issue was, that i upgraded the version of my collection, which lead to two changes:

- The login variables previously called `toweer_username`, `tower_password`... needed to be renamed to `controller_username` etc.
- The var `controller_host` expects a bare hostname only. The old var `tower_host` needed the format `http://host:port`

After adjusting accordingly, the error disappeared
