### ISSUE TITLE
Set up dependency bot

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#8425]
- Bot should open PRs to devel to patch problematic dependencies
- Workflow: PR opened -> Unit & Functional Tests Pass -> QE runs tests -> merge. ex: https://github.com/ansible/awx/pull/8315, https://github.com/ansible/awx/issues/8424

Lots of options to choose. Pick the simplest one.

**Comment by jakemcdermott** [comment]
(post 4.0)

**Comment by unlikelyzero** [comment]
@jakemcdermott we have some similar plans on https://github.com/ansible/tower-qa/issues/3434 . I think dependabot makes more sense. I think we should sync on this

**Comment by unlikelyzero** [comment]
@jakemcdermott here's an example in clouddot https://github.com/RedHatInsights/catalog-ui/blob/master/.dependabot/config.yml
