### ISSUE TITLE
Use single source of truth / variable for all doc link-outs in ui next

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#8428]
This is somewhat of an auditing card as it may already be done in which case we can move this over to test-verification-and-close.

Goal: We want all doc links to stay up-to-date and point to the right version automatically. Preferably this should be done in a way that requires no code changes from release to release but if we need to use a variable, just make sure everything is using the same variable (e.g imported from the same file) so the maintenance is minimal.

**Comment by GeorgeSheridan** [comment]
Should this issue be labeled as Good First Issue?

We are doing research about how to help newcomers onboarding in an open source project and how to accelerate the issue resolving process.
We have developed a tool to automatically label the Good First Issue (GFI), i.e., the issue which is good for newcomers. 
We first extract 72 features from different dimensions of issue reports, such as readability, semantic meaning, associated code snippets, etc, and experimentally investigate to what extent these features correlate with GFI. Results turn out that a large portion of these features do have a medium to large correlation with GFI. 
We then build a machine learning model based on these features to predict GFI. The experiments on a dataset of 12k issues from Github show that 0.90 AUC can be achieved. 

Our tool shows that this issue has a very large possibility to be a GFI. 
Could you please tell us whether it should be labeled as a GFI?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by mabashian** [comment]
Closing in favor of https://github.com/ansible/awx/issues/8428

**Comment by unlikelyzero** [comment]
We will need to add 2-3 checks for href links to the cypress tests.

1. for ansible core
2. for a context-specific guide like workflow viz
3. for a generic doc link

**Comment by tiagodread** [comment]
We need implement the same utility function to get the actual version of the product and make asserts in cypress test

**Comment by tiagodread** [comment]
Working on a test case to cover this

**Comment by akus062381** [comment]
> Working on a test case to cover this

@tiagodread let me know how I can help!
