### ISSUE TITLE
Inventory variables are not being used in playbook runs

### ISSUE THREAD

**Issue by bellackn** [ansible/awx#8437]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Inventory variables are not being used in templates when inventory source is AWS EC2.

##### ENVIRONMENT
* AWX version: 15.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.14
* Operating System: RHEL 8
* Web Browser: Firefox, Chrome

##### STEPS TO REPRODUCE

1. Add an inventory `foo`
2. Add an AWS EC2 source `foo-ec2-source` to that inventory
3. Add a variable `{"foo": "bar"}` to the `foo` inventory variables
4. Create a template with a playbook that uses this variable, like
   ```
   - hosts: "&{{ foo }}:something
     [...]
   ```
5. Launch the template with the `foo` inventory

##### EXPECTED RESULTS

The playbook shows that the variable `foo` is present and replaces it with `bar`.

##### ACTUAL RESULTS

```
TASK [foo] ***
skipping: [localhost]
ERROR! The field 'hosts' has an invalid value, which includes an undefined variable. The error was: 'foo' is undefined
The error appears to be in '/tmp/awx_211_85u0d60g/project/ansible/my-playbook.yml': line 4, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- hosts: "&{{ foo }}:something"
  ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:
    with_items:
      - {{ foo }}
Should be written as:
    with_items:
      - "{{ foo }}"
```

##### ADDITIONAL INFORMATION

The variable shows up correctly when I enter it using a survey. Hardcoding it in the template also works, but this is not an option in my case.

**Comment by wenottingham** [comment]
I think what you're doing here doesn't make sense.

When evaluating the `hosts` line, the variables that are in scope are extra vars (which can come from surveys).

Inventory vars are applied to all hosts in the inventory. They can't be used for host specifiers.
