### ISSUE TITLE
Custom Python venv does not replace ansible

### ISSUE THREAD

**Issue by ghost** [ansible/awx#8440]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX 15.0.1 does not contain Ansible 2.10.x or newer.  This causes the download of collections from git repositories to fail.  In an attempt to get the latest version of Ansible for the project sync I created a virtual environment with Ansible 2.10.2 and attempt a project sync with the custom env.

The ansible-galaxy download of the collections in "collections/requirements.yml" fail with the same error as seen in the base env with ansible 2.9.14.  This leads me to believe that the project sync is not using ansible from the custom python env.

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker on linux
* Ansible version:  2.10.2?
* Operating System: CentOS 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE
- Install python custom environments support
- Create custom environment with Ansible 2.10.0 or newer
- Add a scm project which contain an "collections/requirements.yml" file
  - the file should contain a SCM/git based collection requirement (based on Ansible 2.10.x)
- Set custom environment for the scm project
- Run sync

##### EXPECTED RESULTS
Collection from SCM/git repository successfully downloaded using ansible-galaxy.

##### ACTUAL RESULTS
Project sync fails with syntax error as seen here https://github.com/ansible/awx/issues/8257.

##### ADDITIONAL INFORMATION
When will Ansible 2.10.x be shipped with AWX?

**Comment by wenottingham** [comment]
It won't be, most likely.

See https://github.com/ansible/awx/issues/5157
