### ISSUE TITLE
Username is a required field

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#8453]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Username is a required field by the API.

![Screenshot_2020-10-25 Ansible AWX(1)](https://user-images.githubusercontent.com/9053044/97114170-47913880-16c5-11eb-8e10-621b6b72e1b2.png)

**Comment by tiagodread** [comment]
Tests covered by 5658 and PR already merged
