### ISSUE TITLE
Form Validation for invalid JSON File has changed

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8458]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Form Validation for invalid JSON File has changed. Let's figure out which one we want to have.

##### ENVIRONMENT
* AWX version: d550487bc8cbdfd333e5881b9fc6192b63252d3a

##### STEPS TO REPRODUCE
1. Create or Edit a GCE Credential Type
2. Upload a JSON file without a client_email
3. Save

##### EXPECTED RESULTS
I'm not sure if we want the API validation error or clientside validation error in this case

##### ACTUAL RESULTS
I'm not sure if we want the API validation error or clientside validation error in this case

##### ADDITIONAL INFORMATION

[applitools link](https://eyes.applitools.com/app/sessions/00000251798598654768/00000251798598653125/steps/1?accountId=-aUNI-mIdEuhpe8oOdKO7Q~~&regionDimensions=top%28502%29left%28197%29width%281%29height%280%29&regionId=fb7c2517-b182-4bb1-8028-5a9cbdf69579)

**Comment by unlikelyzero** [comment]
@keithjgrant let's sync on this one when you get a chance

**Comment by keithjgrant** [comment]
@unlikelyzero We're good to close this now, right?

**Comment by unlikelyzero** [comment]
Yes. Thanks!
