### ISSUE TITLE
Job template survey float doesn’t work 

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#8460]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Trying to create a job template survey type Float when hit save the API return `{"error":"Default value 2 in survey question 0 expected to be float."}`. This happens on the old and new UI

See more: https://github.com/ansible/awx/pull/8419
Also related: https://github.com/ansible/awx/issues/8222

##### ENVIRONMENT
* AWX version: 15.0.0
* AWX install method: docker for mac
* Ansible version:  2.9.3
* Operating System: Catalina
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Navigate to Job templates
2. Click on Job template
3. Click on Survey tab
4. Create a `Float` survey type like question: 1.0+1.0 default: 2.0

OR use this payload on the `/api/v2/job_templates/<id>/survey_spec/` to create a new survey

```
{
    "description": "",
    "name": "",
    "spec": [
        {
            "choices": "",
            "default": 2,
            "max": 1024,
            "min": 0,
            "new_question": true,
            "question_description": "",
            "question_name": "1.0+1.0",
            "required": true,
            "type": "float",
            "variable": "float"
        }
    ]
}
```

##### EXPECTED RESULTS

The API can successfully save 2 as float (2.0) even passing as integer

##### ACTUAL RESULTS

The API returns `{"error":"Default value 2 in survey question 0 expected to be float."}`

##### ADDITIONAL INFORMATION

![survey](https://user-images.githubusercontent.com/12464858/97207605-fc485a00-1798-11eb-8b4a-99cbfe757b37.gif)

**Comment by unlikelyzero** [comment]
Adding `component:ui` as it does not function there, either. May not have ever worked so not using `qe:regression`label

**Comment by shanemcd** [comment]
When someone picks this up, we just need to review and merge the PR above, and let QE decide if they want to add tests.

**Comment by InnocentK** [comment]
Resolved
