### ISSUE TITLE
Remove activity for inventory details page

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#8467]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Remove activity for inventory details page. Currently is stated as `Coming soon`.

<img width="1491" alt="image" src="https://user-images.githubusercontent.com/9053044/97329469-733f2a80-184d-11eb-975e-fd7690a80fa1.png">

This information is already present on the `Completed jobs` tab. It was decided to remove from details page.

**Comment by tiagodread** [comment]
PR already merged, we already have a visual test to cover it.
