### ISSUE TITLE
Update JT Edit form's Playbook component to include typeahead select

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8473]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
The current JT Edit form uses a standard dropdown component. In the old ui, typeahead was possible (but not great). There is an available component here:
https://www.patternfly.org/v4/components/select/#custom-filtering

##### ENVIRONMENT
* AWX version: 0d3c9ebc2b748e65e45c9a11bcc1f65f5c8a5b0a

##### ADDITIONAL INFORMATION
Current Implementation
![Screen Shot 2020-10-28 at 7 50 48 AM](https://user-images.githubusercontent.com/12446869/97432438-5577d100-18f2-11eb-9a7d-83529b5bbcfc.png)

Classic UI:
![Screen Shot 2020-10-28 at 7 52 07 AM](https://user-images.githubusercontent.com/12446869/97432533-7e986180-18f2-11eb-829d-32bc1edd6520.png)

**Comment by AlexSCorey** [comment]
@unlikelyzero this seems to be a duplicate of https://github.com/ansible/awx/issues/8378.  I'm linking them here, but I think we should close 1 or the other.  Do you have a preference?

**Comment by unlikelyzero** [comment]
@AlexSCorey i opened this one because the last one was specific to a bug in 3.X 'component:ui' I think we should keep them separate but linked

**Comment by AlexSCorey** [comment]
for reference: https://github.com/ansible/awx/issues/8378

**Comment by unlikelyzero** [comment]
We have coverage here
