### ISSUE TITLE
user detail link in toolbar broken

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#8478]
the link for getting to the currently logged in users details from the top toolbar is malformed.  (Link on top right here):

<img width="1680" alt="Screen Shot 2020-10-28 at 1 51 47 PM" src="https://user-images.githubusercontent.com/1342624/97476455-cafc9500-1924-11eb-95bb-94af514e938f.png">

**Comment by jakemcdermott** [comment]
:+1: tested. it works!

**Comment by unlikelyzero** [comment]
@jakemcdermott we don't have any coverage for this one in the tests. If you don't mind, i'm going to re-open this for post-merge testing

**Comment by unlikelyzero** [comment]
Note: this is a dupe of https://github.com/ansible/awx/issues/7526

**Comment by unlikelyzero** [comment]
@jakemcdermott this re-re-regressed

**Comment by unlikelyzero** [comment]
Going to close this in favor of https://github.com/ansible/awx/issues/8998
