### ISSUE TITLE
Job Schedule with configurable limit

### ISSUE THREAD

**Issue by mkempster22** [ansible/awx#848]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
When setting a schedule for a job (for example a template that performs a reboot with its inventory set to 'dev servers') be able to set a limit in the schedule to have that scheduled run to only reboot the limited server, this way you could have 3 different schedules run the same jobs against different servers at different times.

Currently it will only use the hardcoded limit in the job template which is less flexible and also causes and issue that if someone changes that limit after you schedule a job then when the job comes to run it will use the current limit set which is dangerous

##### ENVIRONMENT
* AWX version: N/A
* AWX install method: docker on linux
* Ansible version:  N/A
* Operating System: N/A
* Web Browser: N/A

##### STEPS TO REPRODUCE
When clicking +ADD to add a schedule for a job have a text box for the limit to apply to that run

**Comment by mkempster22** [comment]
Just noticed #169 appears to be very similar but minus having a limit not just separate inventories. Maybe just include limits on that feature idea

**Comment by wenottingham** [comment]
Should be handled by #169.
