### ISSUE TITLE
Source variables not working when running vCenter inventory sync

### ISSUE THREAD

**Issue by mvrk69** [ansible/awx#8484]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Source variables to override the ones in vmware_inventory.ini as described in the documentation don't work.

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: kubernetes
* Ansible version:  2.9.5
* Operating System: Fedora 31

##### STEPS TO REPRODUCE

I set this 2 variables in the SOURCE VARIABLES field
alias_pattern: config.name
host_pattern: guest.hostname

##### EXPECTED RESULTS

It should import the host from vCenter using only the name of the VM instead of name_uuid and use the dns hostname instead of ip.

##### ACTUAL RESULTS

It still imports the hosts as name_uuid and ip address in the ansible_host

**Comment by wenottingham** [comment]
You need to enter a config as described here:

https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vm_inventory_inventory.html

We'll get the tooltip updated.

**Comment by mvrk69** [comment]
thanks for the info. doing like described on that document works perfectly.

**Comment by ryanpetrello** [comment]
The tooltip will be updated in the next version of AWX.

**Comment by jsalatiel** [comment]
@mvrk69  Would you mind to share your final configuration to make this work ?

**Comment by mvrk69** [comment]
> @mvrk69 Would you mind to share your final configuration to make this work ?

plugin: community.vmware.vmware_vm_inventory
strict: False
validate_certs: False
with_tags: False
properties:
\- "name"
\- "config.cpuHotAddEnabled"
\- "config.cpuHotRemoveEnabled"
\- "config.instanceUuid"
\- "config.hardware.numCPU"
\- "config.template"
\- "config.name"
\- "config.uuid"
\- "guest.hostName"
\- "guest.ipAddress"
\- "guest.guestId"
\- "guest.guestState"
\- "runtime.maxMemoryUsage"
\- "customValue"
\- "summary.runtime.powerState"
\- "config.guestId"
\- "guest.toolsStatus"
\- "guest.toolsRunningStatus"
\- "config.guestFullName"
\- "runtime.powerState"
\- "config.version"
\- "config.bootOptions"
\- "config.firmware"
\- "config.cpuAllocation"
\- "config.memoryAllocation"
compose:
  ansible_host: 'guest.hostName'
hostnames: 
\- config.name
resources:
\- folder:
  \- TEST
filters: 
\- config.template is false

**Comment by jsalatiel** [comment]
Thanks
