### ISSUE TITLE
Error at installing awx-9.0.1  in kubernetes 1.17.4

### ISSUE THREAD

**Issue by djuwa4** [ansible/awx#8485]
##### ISSUE TYPE
```
error: error parsing STDIN: error converting YAML to JSON: yaml: line 56: found a tab character where an indentation space is expected", "stderr_lines"
##### SUMMARY
<!-- Briefly describe the problem. -->
```
##### ENVIRONMENT
AWX version: awx-9.0.1
AWX install method: kubernetes
Ansible version: ansible 2.9.6
Operating System: CentOS Linux release 7.7.1908 (Core)
kubernetes version: 1.17.4
Web Browser:

##### STEPS TO REPRODUCE

ansible-playbook -i inventory install.yml

##### EXPECTED RESULTS

installing awx in kubernetes

##### ACTUAL RESULTS

Error:
```
USE_X_FORWARDED_PORT = True\n\n    AWX_CONTAINER_GROUP_DEFAULT_IMAGE = \"ansible/ansible-runner\"\n", 
"msg": "non-zero return code", "rc": 1, "start": "2020-10-29 11:14:11.011088", 
"stderr": "error: error parsing STDIN: error converting YAML to JSON: yaml: line 56: 
found a tab character where an indentation space is expected", "stderr_lines": 
["error: error parsing STDIN: error converting YAML to JSON: yaml: line 56: 
found a tab character where an indentation space is expected"], "stdout": "", "stdout_lines": []}
```
The error output starts with these lines:
```
failed: [localhost] (item = apiVersion: v1
kind: ConfigMap
metadata:
   name: awx-config
   namespace: awx
data:
   awx_nginx_conf: |
     #user awx;
```
As I understand it, the error indicates incorrect syntax in the configmap.yml.j2 file. Am I getting it right?
##### ADDITIONAL INFORMATION
I created a public branch with my error txt file and configmap.yml.j2:
https://github.com/djuwa4/awxerrors

**Comment by djuwa4** [comment]
I edited the file in notepad ++ There really was no indentation on line 72, but I still get the error.

**Comment by djuwa4** [comment]
Strange, but in nano I saw too much indentation on line 72.
In general, I solved this problem. The problem is in version awx-9.0.1 on line 72 of the configmap.yml.j2 file.

**Comment by wenottingham** [comment]
awx-9 is *very* old at this point, and is not maintained. Please try the current release (15.0.1) and reopen if you see issues.
