### ISSUE TITLE
Implement Management Jobs for AWX PF

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8488]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
Management Jobs

**Comment by unlikelyzero** [comment]
linked to https://github.com/ansible/awx/pull/8103

**Comment by AlexSCorey** [comment]
Assigned jake because he already has the work ready for PR for this.

**Comment by unlikelyzero** [comment]
covered in https://github.com/ansible/tower-qa/pull/5743
