### ISSUE TITLE
Dynamic inventory sync from an isolated node

### ISSUE THREAD

**Issue by mrmibrown** [ansible/awx#8494]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
This is a request for a feature to allow a dynamic inventory sync from an isolated node.

RELATED ARTICLE: 
https://access.redhat.com/solutions/3825471

We are trying to get a dynamic inventory script to run on an isolated node in the oracle cloud.
I see here in the below article that this is not possible because: "Isolated nodes only have minimal required packages which are needed to run a job"

However, if we install the necessary packages, then they do have the ability to.

This is VERY much needed for the following reasons:
  - We do not want to install the OCI python SDK on the main tower nodes.
  - The nodes in the oracle cloud have "instance principals" which grants them access to all cloud resources.  Main tower nodes do not have this, nor do we want to manage account tokens for this.

**Comment by wenottingham** [comment]
With the changes we are making to inventory updates (https://github.com/ansible/awx/issues/7061) we are not going to do this directly in this way. We'd have to consider this in that context.
