### ISSUE TITLE
Jobs not refreshing - websocket 404 error

### ISSUE THREAD

**Issue by mskender** [ansible/awx#8498]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Jobs not refreshing - websocket 404 error 

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: kubernetes 1.18
* Ansible version:  2.9.6
* Operating System: linux
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Run any jobs from the UI. 

##### EXPECTED RESULTS

Jobs autoscrolls/refreshes going through various tasks in the play

##### ACTUAL RESULTS

Job does not refresh itself, now it's static and needs manual refresh.
Also, I'm getting the following in the awx-web container:

```
10.8.122.216 - - [30/Oct/2020:12:44:30 +0000] "GET /websocket/ HTTP/1.1" 404 3880 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0" "172.20.41.1"

2020-10-30 12:44:42,339 WARNING  django.request Not Found: /websocket/

2020-10-30 12:44:42,339 WARNING  django.request Not Found: /websocket/

2020-10-30 12:44:42,339 WARNING  Not Found: /websocket/
```

##### ADDITIONAL INFORMATION

The install is done via 

`ansible-playbook -i awx-inventory  awx-$version/installer/install.yml`

Relevant snips from awx-web container:

```
upstream daphne {
        server 127.0.0.1:8051;
    }

 location /websocket {
            # Pass request to the upstream alias
            proxy_pass http://daphne;
            # Require http version 1.1 to allow for upgrade requests
            proxy_http_version 1.1;
            # We want proxy_buffering off for proxying to websockets.
            proxy_buffering off;
            # http://en.wikipedia.org/wiki/X-Forwarded-For
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # enable this if you use HTTPS:
            proxy_set_header X-Forwarded-Proto https;
            # pass the Host: header from the client for the sake of redirects
            proxy_set_header Host $http_host;
            # We've set the Host header, so we don't need Nginx to muddle
            # about with redirects
            proxy_redirect off;
            # Depending on the request value, set the Upgrade and
            # connection headers
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }
```
   

Running daphne process:

`awx         80  0.6  0.2 2082112 132252 ?      Sl   12:31   0:06 /var/lib/awx/venv/awx/bin/python3 /var/lib/awx/venv/awx/bin/daphne -b 127.0.0.1 -p 8051 awx.asgi:channel_layer`

**Comment by jakemcdermott** [comment]
:wave: I just deployed latest devel to gke using the installer and websockets seem to be working fine. Can you share an exact inventory, set of playbook variables, and steps to reproduce this bug from a completely fresh install? Thanks!

**Comment by mskender** [comment]
Here's the inventory I'm installing from:

```
localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python3"

[all:vars]

dockerhub_base=ansible

kubernetes_context=default
kubernetes_namespace=awx


kubernetes_ingress_hostname=awx.redacted.local
kubernetes_ingress_tls_secret=wild.redacted.local
kubernetes_ingress_annotations={ 'kubernetes.io/ingress.class': 'ingress-nginx-local', 'nginx.ingress.kubernetes.io/whitelist-source-range': '172.20.41.0/24,172.20.42.0/24' }


awx_task_hostname=awx
awx_web_hostname=awxweb

postgres_data_dir="~/.awx/pgdocker"
host_port=80
host_port_ssl=443
docker_compose_dir="~/.awx/awxcompose"


pg_hostname=psql01.k8s.redacted.local
pg_username=awx
pg_password=redacted
pg_database=awx
pg_port=5432


admin_user=admin
admin_password=password

create_preload_data=False

secret_key=redacted
```

This is the inventory I have used today to reinstall (after dropping namespace first, of course).
Please note that I'm using baremetal MetalLB plugin for implementing LoadBalancer and also self-deployed Nginx Ingress controller. 
However, this is the first time I'm actually having trouble with LB/Ingress despite running dozen of namespaces. 
AWX runs great as well, except /websockets URL.

**Comment by jakemcdermott** [comment]
> Please note that I'm using baremetal MetalLB plugin for implementing LoadBalancer and also self-deployed Nginx Ingress controller.
However, this is the first time I'm actually having trouble with LB/Ingress despite running dozen of namespaces.

Hello!

Thanks for the information. This is more than likely a system configuration issue with the added load balancer setup than an actual bug with the installer code provided in this repo.

The best place to look for help with debugging your awx installation or technical assistance would be the awx community mailing list or irc channel:

- http://webchat.freenode.net/?channels=ansible-awx
- https://groups.google.com/forum/#!forum/awx-project


Thank you and have a nice day!

**Comment by unixfy** [comment]
I am experiencing this same issue and do not have a load balancer in front of AWX. Deployed using the default config & docker-compose.
