### ISSUE TITLE
Unable to install AWX - Playbook fails 

### ISSUE THREAD

**Issue by Cadjoe** [ansible/awx#8502]
##### ISSUE TYPE
 - ERROR! couldn't resolve module/action 'docker_image'. This often indicates a misspelling, missing collection, or incorrect module path.

##### SUMMARY
```
ERROR! couldn't resolve module/action 'docker_image'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/mattermo@ansible/awx/installer/roles/image_build/tasks/main.yml': line 44, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Build sdist builder image
  ^ here
```

##### ENVIRONMENT
* AWX version: 14.1.0
* AWX install method:  docker on linux
* Ansible version:  2.10.1
* Operating System: Oracle Linux 8
* Web Browser: ---

##### STEPS TO REPRODUCE

I followed the AWX [installation guide](https://github.com/ansible/awx/blob/devel/INSTALL.md#docker-compose). Made changes to the inventory file and made changes to the following fields below:
```
 awx_task_hostname=awx
 awx_web_hostname=awxweb
 ssl_certificate="~/certs/sslcert.pem"
 ssl_certificate_key="~/certs/private.key"
 postgres_data_dir=/var/lib/pgdocker
 host_port=8080
 
 docker_compose_dir=/var/lib/awxcompose
 
 pg_username=awx
 pg_password=pgpss
 pg_database=awx
 pg_port=5432
  
 admin_user=admin
 admin_password=awxadminpass
 
create_preload_data=True

 secret_key=secretkey
 awx_alternate_dns_servers="10.10.0.1,10.10.0.2"
 project_data_dir=/var/lib/awx/projects
```

Finally ran the installer:
```
sudo ansible-playbook -i inventory install.yml
```
##### EXPECTED RESULTS

The playbook to run and docker to install the AWX containers.

##### ACTUAL RESULTS

>>> See summary above

##### ADDITIONAL INFORMATION

I've tried this on both 14.1.0 and latest branch with both producing the same result. I'm not sure if it's something I'm missing out on in the playbook or it's the playbook itself as indicated in the resulting output.

**Comment by ryanpetrello** [comment]
Hey @Cadjoe,

There's some extra requirements if you're using Ansible 2.10+

You'll want to move to either 15.0.1 or incorporate the changes from this diff:

https://github.com/ansible/awx/commit/9818440d0f91ce4b4fee513fba73dcc99f188271#diff-09b140a43ebfdd8dbec31ce72cafffd15164d2860fd390692a030bcb932b54a0
