### ISSUE TITLE
 Log rsyslog failures with a counter

### ISSUE THREAD

**Issue by mrmibrown** [ansible/awx#8505]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
This is a request to log rsyslog failures with a counter to provide more transparency when a message is dropped.

To help avoid the silent dropping of messages it would be good to have metrics keep a counter that is incremented every time a log message is dropped. Maybe have a "dropped external logger message" category that has sub counts for messages dropped because of blocked I/O and connection refused.

Related PR: https://github.com/ansible/awx/pull/7292

**Comment by wenottingham** [comment]
Where is this expected to count? When rsyslog refuses the message? When rsyslog can't send it to wherever?

I'm skeptical this is practical in the current architecture.

**Comment by ryanpetrello** [comment]
I tend to agree; if the rsyslogd daemon is unresponsive over a local domain socket, 🤷

**Comment by blomquisg** [comment]
This is essentially a dup of https://github.com/ansible/awx/issues/8576.  We don't see a compelling reason to include this.

**Comment by suryarao67** [comment]
Hello,

If there is no counter and no messages indicating messages are dropped, how do support teams even become aware of this? Bear in mind that these logs often may contain critical data which cannot be lost. Silent dropping is not good. There must be an indication when messages are being dropped..somewhere.

**Comment by wenottingham** [comment]
That would be in the rsyslog error log in /var/log/tower.

**Comment by wenottingham** [comment]
That would be in the rsyslog error log inside the container.

**Comment by suryarao67** [comment]
If rsyslog itself was unresponsive, the Tower process would drop the external log messages being sent to rsyslog to avoid blocking. In that case I don't think there will be anything inside rsyslog error log. Please confirm?

**Comment by wenottingham** [comment]
rsyslog has not been unresponsive in our testing - if this is a continuous issue in some environment, that is something that we would need details about the AWX deployment.

As for logging failures, I don't know that it makes sense to log a failure when you can't log, but perhaps we can expose a count of failed logs via our prometheus metrics that are being enhanced to store some per-node metrics for a future release. CC'ing @fosterseth .

**Comment by suryarao67** [comment]
> rsyslog has not been unresponsive in our testing - if this is a continuous issue in some environment, that is something that we would need details about the AWX deployment.

If rsyslog has never been observed to be unresponsive, then I am confused as to why the need arose to drop messages as part of PR# [7292](https://github.com/ansible/awx/pull/7292)

If rsyslog was responding but the external log aggregator was unresponsive, then rsyslog has a mechanism to queue messages locally on disk and retry ( if I am not mistaken ). Our observation was that Tower processes blocked sending messages with the result being Tower pod evictions and Tower being unresponsive.

>As for logging failures, I don't know that it makes sense to log a failure when you can't log, but perhaps we can expose a count of failed logs via our prometheus metrics that are being enhanced to store some per-node metrics for a future release. CC'ing @fosterseth .
Interested to know the timelines for the above

**Comment by wenottingham** [comment]
> If rsyslog has never been observed to be unresponsive, then I am confused as to why the need arose to drop messages as part of PR# 7292

That PR was fixing it to not break when rsyslog is misconfigured by the user. We have not seen issues in AWX beyond that.

> Our observation was that Tower processes blocked sending messages with the result being Tower pod evictions and Tower being unresponsive.

If you have an issue with a downstream distribution of AWX that requires debugging and support, please talk to Red Hat support; this is not the place for that.

**Comment by ryanpetrello** [comment]
Recent versions of AWX actually *should* print a verbose failure to stderr.  I've got a PR that makes them a bit _less_ verbose:

https://github.com/ansible/awx/pull/9452#issuecomment-791558081

I think a counter is the wrong approach here, because it doesn't actually communicate the context of the failure.

**Comment by suryarao67** [comment]
Thanks @ryanpetrello 
Is it possible to get some sample failure log printed to stderr please?

**Comment by ryanpetrello** [comment]
@suryarao67

Here's an example of what this looks like in older versions of AWX.  I made a change in AWX >= 18.0.0 to make it a little *less* verbose:

https://github.com/ansible/awx/pull/9452#issuecomment-791558081

**Comment by kdelee** [comment]
@ryanpetrello can you provide some thoughts on any verification you are looking for on this feature?

**Comment by ryanpetrello** [comment]
1.  Enable external logging.
2. Manually stop rsyslogd via `supervisorctl stop ...`
3. Do something that emits a log (log out/in).
4. Verify that a reasonable error (describing that rsyslogd is offline) shows up in AWX logs in (both K8S and non-K8S installs) that includes the "missed" error message.

**Comment by Zokormazo** [comment]
Followed the instructions on https://github.com/ansible/awx/issues/8505#issuecomment-808498582 and I can see this on stderr:

```
# cat /proc/45224/fd/2
2021-04-13 10:55:04 ERROR rsyslogd was unresponsive: FileNotFoundError: [Errno 2] No such file or directory
```

But not on awx logs.

**Comment by Zokormazo** [comment]
```
2021-04-13 12:42:46 ERROR rsyslogd was unresponsive: FileNotFoundError: [Errno 2] No such file or directory
worker exiting gracefully pid:462
```

Much better inside containers
