### ISSUE TITLE
deprecated apiVersion for ingress

### ISSUE THREAD

**Issue by AdamWyzgol** [ansible/awx#8507]
### SUMMARY
When installing on Kubernetes 1.19.3 I got an warning: 
extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

**Comment by gary1998** [comment]
kindly update the extension name from `extensions/v1beta1` to `networking.k8s.io/v1` with an if condition [here](https://github.com/ansible/awx/blob/8206874158ce555381087c47d28306f32f951a40/installer/roles/kubernetes/templates/deployment.yml.j2#L535). This would do the required work.
More clearly, it should look like this:
`apiVersion: {{ 'networking.k8s.io/v1' if kube_api_version is version('1.14', '>=') else 'extensions/v1beta1' }}`

**Comment by kdelee** [comment]
@shanemcd is this resolved by moving to the operator?

**Comment by shanemcd** [comment]
Looks we're still using `extensions/v1beta1` there too: https://github.com/ansible/awx-operator/blob/51e384292c15e0c6d8eaf89c3d0d6afd41fd8b94/roles/installer/templates/tower_ingress.yaml.j2#L3

**Comment by ryanpetrello** [comment]
Would you open this as an issue in http://github.com/ansible/awx-operator instead?  Thanks.
