### ISSUE TITLE
Notification integration with Hipchat shows incorrect Host in URL

### ISSUE THREAD

**Issue by grahamneville** [ansible/awx#851]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Once Hipchat integration is setup on AWX for job notifications and a message is posted to a Hipchat channel the URL shown is http://towerhost. The hostname needs to be configurable so it can actually be a hostname that is reachable.

##### ENVIRONMENT
* AWX version: 1.0.1.8
* AWX install method: docker on linux
* Ansible version:  2.4.0.2
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Setup AWX to Hipchat integration for notifications and then add the notification to a job then run the job and check the Hipchat channel.

##### EXPECTED RESULTS

The URL that is presented in the channel is reachable.

##### ACTUAL RESULTS

http://towerhost isn't reachable.

**Comment by wenottingham** [comment]
See the TOWER_URL_BASE configuration setting.

**Comment by wenottingham** [comment]
Please reopen if that doesn't work for you.
