### ISSUE TITLE
OpenSource AWX Webgui always redirect to AWX Subscription-Page

### ISSUE THREAD

**Issue by klausfranken** [ansible/awx#8511]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

It its always a redirection to AWX Subscription page because /var/lib/awx/.tower_version always exists in awx_web container

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.13
* Operating System: Ubuntu 18.04.5 LTS
* Web Browser: Firefox 82.0.2

##### STEPS TO REPRODUCE

awx/installer/inventory
```
#dockerhub_base=ansible
use_container_for_build: True
awx_official: False
create_preload_data: False
```

##### EXPECTED RESULTS

Login to AWX-Webgui

##### ACTUAL RESULTS

After successfully logged in, I was redirected to http://localhost:8083/#/license
But I want to use OpenSource AWX

##### ADDITIONAL INFORMATION

The misbehaviour comes from commit https://github.com/ansible/awx/commit/c139a998b82761cd5405ee1caa1847f3a23d89b9?_pjax=%23js-repo-pjax-container

The condition in common.py line 207:
`if os.path.exists('/var/lib/awx/.tower_version'):`
is always true, because the file exist always in awx_web container.

Ugly workaround: after starting all containers, remove `/var/lib/awx/.tower_version` in `awx_web` container.

**Comment by ryanpetrello** [comment]
Hey @klausfranken,

Thanks for reporting this - I'll take a closer look and get a fix merged on Monday.  In the meantime, I think this should fix the issue if you want to give it a whirl:

https://github.com/ansible/awx/pull/8512

**Comment by klausfranken** [comment]
Hi @ryanpetrello,

#8512 / https://github.com/ansible/awx/pull/8512/commits/c64f2552d1b9f18b404cbc756659aa6f53816207  works for me (in case of the OpenSource licence, I don't know what REDHAT_CANDLEPIN_HOST is)

Thanks
Klaus

**Comment by ryanpetrello** [comment]
Hey @klausfranken, we ended up fixing this another way via https://github.com/ansible/awx/pull/8516

Thanks for reporting - go ahead and give `devel` another try (keep in mind you'll have to build your own custom image until the next release of AWX is out).

https://github.com/ansible/awx/blob/devel/INSTALL.md#clone-the-repo

> Please note that deploying from HEAD (or the latest commit) is not stable, and that if you want to do this, you should proceed at your own risk (also, see the section #official-vs-building-images for building your own image).

**Comment by klausfranken** [comment]
Hi @ryanpetrello ,
I built a new image. Works for me. 
Thanks,
Klaus
