### ISSUE TITLE
kex_exchange_identification when using Bastion Host

### ISSUE THREAD

**Issue by kev-mas** [ansible/awx#8514]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

We run up our infrastructure with Terraform in AWS, and we have two inventories setup in AWX. One imports two of the instances and their public IPs, while the other imports all the other instances with their private IPs.
After the first import, we were able to use AWX to run playbooks against the public instance, and against the private instances using one of the public instances as bastion host using the following inventory variable

```ansible_ssh_common_args: '-o ProxyCommand="ssh -A -o StrictHostKeyChecking=no -W %h:%p -q ubuntu@toolbox.mvrv3-dev.mvr.cloud"' ```

We then used Terraform to destroy the infrastructure and recreate it. We then synced the inventories again to update them and to be able to run playbooks against the instances again, but although we were able to run commands and playbooks against the public instances, we were not able to run them against the private instances  through the bastion host, getting the following error

```
{
    "unreachable": true,
    "msg": "Failed to connect to the host via ssh: kex_exchange_identification: Connection closed by remote host",
    "changed": false
} 
```

We researched and tested many different fixes but nothing seemed to work. When the Task container crashed and we used docker-compose up to recreate it, it worked again.
We destroyed and recreated the infrastructure with Terraform again, and encountered the same issue again.
It looks like every time the environment is destroyed and recreated, the AWX containers need to be recreated too, in our case now, using `docker-compose up -d --force-recreate`

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.14
* Operating System: Ubuntu 18.04.5 LTS
* Web Browser: Firefox 82.0.2 (64-bit)

##### STEPS TO REPRODUCE

Create Inventory and set the following variables:

```
ansible_user: ubuntu
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_common_args: '-o ProxyCommand="ssh -A -o StrictHostKeyChecking=no -W %h:%p -q username@bastion.hotst.com"'
```

##### EXPECTED RESULTS

Playbooks and Workflows to run on Inventory instances through Bastion Host

##### ACTUAL RESULTS

```
{
    "unreachable": true,
    "msg": "Failed to connect to the host via ssh: kex_exchange_identification: Connection closed by remote host",
    "changed": false
} 
```

**Comment by kev-mas** [comment]
Further investigating this, it seems to be caused by the `known_hosts` file within the AWX_Task container (`/root/.ssh/known_hosts`). We've done multiple tests. 

We create and destroy our environment with Terraform for Development purposes. Once created, we run playbooks and workflows against the servers. Once that is done, if we destroy the environment and re-create it with Terraform, and try to run playbooks again, we get the error

```
{
    "unreachable": true,
    "msg": "Failed to connect to the host via ssh: kex_exchange_identification: Connection closed by remote host",
    "changed": false
} 
```

If we then delete the `/root/.ssh/known_hosts` file inside the AWX_Task container and run the playbooks again, it works fine.

It seems AWX doesn't refresh the file when re-syncing the invetories, or has problems when new hosts get added with hostnames that are the same as previous environments. The IPs of our instances change everytime we destroy and re-create the environment.

As a work around we've found that using the following inventory variable works:

```
ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ProxyCommand="ssh -A -i /etc/tower/AWS-KEY.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p -q username@bastion-host"'
```

But is this the expected behavior? I would expect AWX to not fail with this error...

**Comment by wenottingham** [comment]
I think this is just ssh + ansible behavior.
AWX sets ANSIBLE_HOST_KEY_CHECKING off by default. This passes '-o StrictHostKeyChecking=no'.

However, that could still cause some failures with respect to known hosts entries existing. From the SSH manpage:

```
If this flag is set to “no” or “off”, ssh will automatically add new host keys to the user known hosts files and allow connections to hosts with changed hostkeys to proceed, subject to some restrictions. 
```

You may be hitting one of those restrictions. When just testing on the commandline, do you have to set UserKnownHostsFile=/dev/null as well?

**Comment by blomquisg** [comment]
Reopen if you still see this happening.
