### ISSUE TITLE
Possibility to track users using Google analytics

### ISSUE THREAD

**Issue by Tioborto** [ansible/awx#8515]
##### ISSUE TYPE
 - Possibility to track users using Google analytics by adding an ID in the interface

##### SUMMARY
It would be interesting to be able to add the ID provided by Google Analytics within the interface in order to follow the users' adherence to the product.

**Comment by wenottingham** [comment]
I suspect this isn't ever something we would add upstream in this way. For a downstream users, I suspect adding a tracker would be done by hooking into the UI build process to add it there.

**Comment by Tioborto** [comment]
Thank you @wenottingham for your prompt response.
Can you tell me where I can correct the front to add the analysis parameters, please?

**Comment by wenottingham** [comment]
That would be something you would figure out how to do downstream in your fork/build.
