### ISSUE TITLE
Job Template scheduling with different inventories

### ISSUE THREAD

**Issue by grahamneville** [ansible/awx#852]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
It should be possible to schedule a job template to run against different inventories rather than having to have a copy of a template with a different Inventory in each. This way I can schedule jobs to run at different times against different inventories using the same job template.

##### ENVIRONMENT
* AWX version: 1.0.1.8
* AWX install method: docker on linux
* Ansible version:  2.4.0.2
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

When setting up a schedule for a job template the inventory can be chosen.

**Comment by wenottingham** [comment]
this is https://github.com/ansible/awx/issues/169
