### ISSUE TITLE
Can i delete my cache 

### ISSUE THREAD

**Issue by dugs951** [ansible/awx#8522]
Hi,

i have 50GB drive on my AWX Server and all days after Update i have more dates on my AWX drive.
I think he make cache.
How i can delete cache from my awx server?

**Comment by ryanpetrello** [comment]
Hey @dugs951,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
