### ISSUE TITLE
Unable to associate workflow nodes on success / failure with awx cli

### ISSUE THREAD

**Issue by jmhbnz** [ansible/awx#8523]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I'm using AWX cli to automate the configuration of an instance as code and cannot seem to find any functionality to associate a workflow job template node to other workflow job template nodes on success / failure to create the required end to end business process.

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX CLI version: 15.0.1
* AWX install method: openshift
* Operating System: Linux (Pip install of awxkit)

##### STEPS TO REPRODUCE
- Pip install awxkit
- Search through documentation and awx cli help to attempt to find a node associate on success / failure option.

##### EXPECTED RESULTS
In the previous versions of `awx-cli` one could run `awx-cli node (associate_always_node | associate_failure_node | associate_success_node)`.
In the even earlier tower-cli similar functionality was available. 

##### ACTUAL RESULTS
I can't see how to do this with the new awx cli.

**Comment by wenottingham** [comment]
-> https://github.com/ansible/awx/issues/7414
