### ISSUE TITLE
Incorrect element ID for instance groups layout

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8530]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The Instance Group Page has an underscore in the element ID. `#instance_group-list-toolbar` should be `#instance-group-list-toolbar`
##### ENVIRONMENT
* AWX version: 114bcd0349d571a082dc7ca92cb68980cdcec214

**Comment by mabashian** [comment]
I'm assuming the id should be `instance-group-list-toolbar`.  The two strings listed initially look exactly the same to me.

**Comment by unlikelyzero** [comment]
@mabashian yes exactly

**Comment by one-t** [comment]
Hey, @mabashian - can you rebase this to pick up the node version update? Thanks!
