### ISSUE TITLE
Show vault id in credentials list in JT credential field lookup

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#8532]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
<img width="1220" alt="Screen Shot 2020-11-03 at 2 43 04 PM" src="https://user-images.githubusercontent.com/9889020/98033102-00045e00-1de3-11eb-9211-3cd1d04b412d.png">

We indicate to the user that they can only select one vault credential per ID but we don't show them the ID's.

**Comment by nixocio** [comment]
Also, we show the vault id as part of the chip of the credential in the old ui. 

<img width="514" alt="image" src="https://user-images.githubusercontent.com/9053044/98164913-019d5700-1eb3-11eb-952f-9cc91d57206c.png">

**Comment by tiagodread** [comment]
Covered by https://github.com/ansible/tower-qa/pull/5837
