### ISSUE TITLE
Got "IndexError: list index out of range error" with cisco.ios.ios_banner module

### ISSUE THREAD

**Issue by JeromeH27** [ansible/awx#8536]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Got "IndexError: list index out of range error" with cisco.ios.ios_banner module(from cisco.ios collection version 1.1.0)

##### ENVIRONMENT
* AWX version: 14.1.0
* AWX install method: docker on linux
* Ansible version:  2.10.1
* Operating System: Linux Centos
* Web Browser: Google Chrome 86.0.4240.111

##### STEPS TO REPRODUCE
I got issue when I'm trying to use ios_banner() module

with this task:
- name: Remove the motd banner
  cisco.ios.ios_banner:
    banner: motd
    state: absent

I got this error:
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndexError: list index out of range

Full log:
{
    "module_stdout": "",
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-26937a9dunh_p/ansible-tmp-1604506122.621979-27001-69523189820354/AnsiballZ_ios_banner.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-26937a9dunh_p/ansible-tmp-1604506122.621979-27001-69523189820354/AnsiballZ_ios_banner.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-26937a9dunh_p/ansible-tmp-1604506122.621979-27001-69523189820354/AnsiballZ_ios_banner.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_banner', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.ios.ios_banner_payload__6luoylx/ansible_cisco.ios.ios_banner_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_banner.py\", line 188, in <module>\n  File \"/tmp/ansible_cisco.ios.ios_banner_payload__6luoylx/ansible_cisco.ios.ios_banner_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_banner.py\", line 177, in main\n  File \"/tmp/ansible_cisco.ios.ios_banner_payload__6luoylx/ansible_cisco.ios.ios_banner_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_banner.py\", line 133, in map_config_to_obj\nIndexError: list index out of range\n",
    "exception": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-26937a9dunh_p/ansible-tmp-1604506122.621979-27001-69523189820354/AnsiballZ_ios_banner.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-26937a9dunh_p/ansible-tmp-1604506122.621979-27001-69523189820354/AnsiballZ_ios_banner.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-26937a9dunh_p/ansible-tmp-1604506122.621979-27001-69523189820354/AnsiballZ_ios_banner.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_banner', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.ios.ios_banner_payload__6luoylx/ansible_cisco.ios.ios_banner_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_banner.py\", line 188, in <module>\n  File \"/tmp/ansible_cisco.ios.ios_banner_payload__6luoylx/ansible_cisco.ios.ios_banner_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_banner.py\", line 177, in main\n  File \"/tmp/ansible_cisco.ios.ios_banner_payload__6luoylx/ansible_cisco.ios.ios_banner_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_banner.py\", line 133, in map_config_to_obj\nIndexError: list index out of range\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1,
    "_ansible_no_log": false,
    "changed": false
}

##### EXPECTED RESULTS

Remove MOTD banner on the switch

##### ACTUAL RESULTS

I got error describe above

##### ADDITIONAL INFORMATION

I didn't get any errors with this task
- name: Remove Exec banner
  cisco.ios.ios_config:
    lines: banner exec C C

Regards

**Comment by ryanpetrello** [comment]
Hey @JeromeH27,

```python
"ansible_collections/cisco/ios/plugins/modules/ios_banner.py", line 133, in map_config_to_obj\nIndexError: list index out of range\n",
```

This doesn't look like a bug in AWX.

https://github.com/ansible-collections/cisco.ios/issues

**Comment by ryanpetrello** [comment]
https://github.com/ansible-collections/cisco.ios/issues/50
