### ISSUE TITLE
Permission and support custom OS rpm packages installation 

### ISSUE THREAD

**Issue by nicolas-g** [ansible/awx#8537]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
People need to have sudo access or be able to install OS packages inside AWX Kubernetes Pod **awx-web** container, right now when you try to install something with yum you get the bellow error due to permissions : 
```
yum install <PACKAGE_NAME>
Error: This command has to be run under the root user.
```

Most of the Ansible modules require python pip packages which we can install through [custom virtual envs](https://docs.ansible.com/ansible-tower/latest/html/upgrade-migration-guide/virtualenv.html#preparing-a-new-custom-virtualenv), but many modules do required system packages and not pip, as for example the [helm module](https://docs.ansible.com/ansible/2.10/collections/community/kubernetes/helm_module.html) requires the helm binary to be installed.

Giving sudo access when you access the Pod or define variables for the Kubernetes AWS installer to install custom yum pacakges like we do with custom virtual envs will help people solve this issue.

**Comment by wenottingham** [comment]
Yea, no. Modifying the system image at runtime is a bad idea.

This will be solved by https://github.com/ansible/awx/issues/7060 / https://github.com/ansible/awx/issues/5157.

**Comment by nicolas-g** [comment]
> Yea, no. Modifying the system image at runtime is a bad idea.

It is but that should be something for the users to decide, there are tools users need permissions to install for troubleshooting reasons.

**Comment by bobby0724** [comment]
Is there a workaround for this i need to install kerberos packages in the awx-task container in order to support windows hosts

**Comment by nicolas-g** [comment]
@bobby0724 the only solution I found was to create my own custom image based on the AWX docker image.

For example, this is how your Dockerfile will look like:
```
FROM ansible/awx:15.0.1
USER root
RUN yum install kerberos -y
```

You build and push your new image to a Docker registry and update your deployment configs to download your new custom image.

**Comment by cnukwas** [comment]
> @bobby0724 the only solution I found was to create my own custom image based on the AWX docker image.
> 
> For example, this is how your Dockerfile will look like:
> 
> ```
> FROM ansible/awx:15.0.1
> USER root
> RUN yum install kerberos -y
> ```
> 
> You build and push your new image to a Docker registry and update your deployment configs to download your new custom image.

What changes need to be made for this to work since I tried to add few additional tools to be installed during docker image build by adding lines to Dockerfile.j2 but those don't appear to be picked up during the install/build process?
We need to add custom tools related to Open LDAP, jq, wget and few other utilities to awx-web container image.

Thanks
