### ISSUE TITLE
Required fields should be indicated in survey preview

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#8539]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
<img width="1051" alt="Screen Shot 2020-11-04 at 3 17 39 PM" src="https://user-images.githubusercontent.com/9889020/98163544-f6e1c280-1eb0-11eb-8f3b-8703976298b8.png">

The purpose of this view is to give the user an idea of what a launching user will see.  We should indicate required fields with the same red asterisk that we use in forms/in the launch modal.

**Comment by tiagodread** [comment]
Tests covered by https://github.com/ansible/tower-qa/pull/5698
