### ISSUE TITLE
User can’t proceed after clicking in a host on the smart inventory host filter modal 

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#8542]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
User can’t proceed after clicking in a host on the smart inventory host filter modal 

##### ENVIRONMENT
* AWX version: 15.0.0
* AWX install method: docker for mac
* Ansible version:  2.9.13
* Operating System: Catalina
* Web Browser: Chrome and Firefox

##### STEPS TO REPRODUCE

1. Navigate to inventories
2. Add smart inventory
3. Fill in organization
4. Click on host filter lookup button
5. Click on a host
 
##### EXPECTED RESULTS

The `Select` button should be enabled after clicking on a host

##### ACTUAL RESULTS

The `Select` button is disabled and the user cannot move forward 

##### ADDITIONAL INFORMATION

![smart](https://user-images.githubusercontent.com/12464858/98168807-e1c55d80-1ec9-11eb-9c69-e3757c035988.gif)

**Comment by unlikelyzero** [comment]
@tiagodread did this used to work and now it doesn't?

**Comment by marshmalien** [comment]
You shouldn't be able to click on the hosts in this modal. Instead of selecting hosts from a list, you create a search tag that contains the hosts you want.

https://docs.ansible.com/ansible-tower/latest/html/userguide/inventories.html#add-a-new-inventory
>Therefore, to populate the Smart Host Filter field, you are specifying a tag that contains the hosts you want, not actually selecting the hosts themselves. Enter the tag in the Search field and press [Enter].

**Comment by tiagodread** [comment]
Yeah, I opened this bug wrong, I totally misunderstood the feature, i'm so sorry.

I've some considerations here:

1. Without reading the documentation, the UI wasn’t intuitive enough to provide understanding.
2. This modal list works different from most others
3. The smart inventory form is missing helps popovers especially for the field `Host Filter` 
4. The host filter modal contains link to hosts for each item, which can easily move the user to host details (the old UI is a list without link)
5. The host filter modal is missing the `Key` button that contains very useful information about how to perform search

I'll be opening another issue to address the items above.

**Comment by tiagodread** [comment]
Opened #8548 to address these items closing this issue
