### ISSUE TITLE
Have AWX containers with Helm installed

### ISSUE THREAD

**Issue by nicolas-g** [ansible/awx#8551]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Due to access restrictions there is no way to install extra rpm OS packages there fore limiting the use of running Ansible jobs from Tower.

AWX`kubectl` comes with `kubectl` already installed, will be nice to also have `helm` pre-installed so we can run Ansible playbooks that depend on `helm` from AWX as well.

**Comment by wenottingham** [comment]
On a practical level, due to the move to separate execution environments in the future, this would just need to be redone in a couple of months when #7060 / #5157 land.

The way to do this would be to put it in the same place in the image_build role where kubectl is installed.

**Comment by nicolas-g** [comment]
@wenottingham I'v just tested locally with no errors and submitted  PR #8552 .

**Comment by ryanpetrello** [comment]
Addressed via https://github.com/ansible/awx/pull/8552, thanks!
