### ISSUE TITLE
ERROR! Unexpected Exception, this is probably a bug: No module named psutil - While running job on isolated node

### ISSUE THREAD

**Issue by Gopinath-G** [ansible/awx#8555]
##### SUMMARY

While Running job on isolated node it ends up with below error, Please suggest some fix or workaround.

ERROR! Unexpected Exception, this is probably a bug: No module named psutil 

##### ENVIRONMENT
* AWX version: AWX 15.0.1
* AWX install method: docker
* Ansible version:  2.9.14
* Operating System: RHEL 7
* Web Browser: chrome Version 86.0.4240.183

##### STEPS TO REPRODUCE
Install AWX instance with isolated node and instance group
Run a ping command on inventory host mapped to isolated node instance group
ended up with below error in debug mode

##### EXPECTED RESULTS

Identity added: /tmp/awx_143_7cr6781n/artifacts/143/ssh_key_data (/tmp/awx_143_7cr6781n/artifacts/143/ssh_key_data)
ansible 2.8.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Mar 20 2020, 17:08:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /tmp/awx_143_7cr6781n/inventory as it did not pass it's verify_file() method
Parsed /tmp/awx_143_7cr6781n/inventory inventory source with script plugin
**ERROR! Unexpected Exception, this is probably a bug: No module named psutil**
the full traceback was:
Traceback (most recent call last):
  File "/usr/bin/ansible", line 110, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/adhoc.py", line 169, in run
    result = self._tqm.run(play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 187, in run
    self.load_callbacks()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 134, in load_callbacks
    self._stdout_callback = callback_loader.get(self._stdout_callback)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 558, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 536, in _load_module_source
    module = imp.load_source(to_native(full_name), to_native(path), module_file)
  File "/usr/local/lib/python3.6/site-packages/ansible_runner/callbacks/minimal.py", line 44, in <module>
    from display_callback import AWXMinimalCallbackModule  # noqa
  File "/usr/local/lib/python3.6/site-packages/ansible_runner/display_callback/__init__.py", line 21, in <module>
    from . import cleanup  # noqa (registers control persistent cleanup)
  File "/usr/local/lib/python3.6/site-packages/ansible_runner/display_callback/cleanup.py", line 27, in <module>
    import psutil
**ImportError: No module named psutil**

##### ADDITIONAL INFORMATION

Tried running after manually installing psutil modules still it ends up with same error..!!!

Package         Version
--------------- -------
ansible         2.9.14
asn1crypto      0.24.0
**psutil          5.7.3**
psycopg2        2.7.5
pyasn1          0.3.7
pycparser       2.14
PyNaCl          1.3.0
.
.
.

bash-4.4#
![Error_bug](https://user-images.githubusercontent.com/65112067/98370687-f7b95680-2060-11eb-955e-e309c18d319f.png)

**Comment by ryanpetrello** [comment]
> Install AWX instance with isolated node and instance group

AWX doesn't actually support isolated nodes (it's a feature that existed in Red Hat's Ansible Tower product before we open sourced, and it didn't translate well to AWX's container-based deployment), so I'm not sure how you got into this state.

**Comment by Gopinath-G** [comment]
> > Install AWX instance with isolated node and instance group
> 
> AWX doesn't actually support isolated nodes (it's a feature that existed in Red Hat's Ansible Tower product before we open sourced, and it didn't translate well to AWX's container-based deployment), so I'm not sure how you got into this state.

I managed to configure it with traditional procedure of installing ansible tower by defining isolated group and vars in inventory file. 

ex:

[isolated_group_DMZ]
Node1

[isolated_group_DMZ:vars]
controller=tower

**Comment by ryanpetrello** [comment]
Yep, understood.  If you dig in, there's *probably* some way to hack some of the code together to work on Docker-based installs, but awx doesn't really support it in its current state; isolated nodes just aren't available for container-based deployments in awx. We're working on a more general execution node framework that will allow this type of functionality in the future (which will provide similar functionality to isolated nodes): https://github.com/ansible/awx/issues/1207

**Comment by Gopinath-G** [comment]
Finally, Issue was fixed by changing ansible python_interpreter to /usr/bin/python3..

**Comment by Gopinath-G** [comment]
> Yep, understood. If you dig in, there's _probably_ some way to hack some of the code together to work on Docker-based installs, but awx doesn't really support it in its current state; isolated nodes just aren't available for container-based deployments in awx. We're working on a more general execution node framework that will allow this type of functionality in the future (which will provide similar functionality to isolated nodes): #1207

That would be great..!! really looking forward for it.. Thanks :)

**Comment by ryanpetrello** [comment]
@Gopinath-G,

I should point out - it _sounds like_ you're using or at some point in the past _have been using_ Red Hat's Tower product.  If that's the case, we don't provide support for that here upstream - in the future you'll want to contact Red Hat directly for this type of support for their product.

**Comment by Gopinath-G** [comment]
> @Gopinath-G,
> 
> I should point out - it _sounds like_ you're using or at some point in the past _have been using_ Red Hat's Tower product. If that's the case, we don't provide support for that here upstream - in the future you'll want to contact Red Hat directly for this type of support for their product.

@ryanpetrello 

Actually I just found the procedure while experimenting isolated node feature with AWX.. but never the less as you mentioned i understand the risk that it is not meant for and either not supported with docker based AWX deployments but at least the  experiment was successful..

Looking forward for the above mentioned new framework..

Thanks..!!!
