### ISSUE TITLE
workflow visualizer: Add more metadata to nodes

### ISSUE THREAD

**Issue by faroukellouze** [ansible/awx#8562]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

When you use the workflow visualizer and add multiple nodes with the same job template but with different params(such as inventories, survey values...), or when using it in job slicing, the nodes(or boxes) will look all the same which requires more navigation to know what was executed and where.

![image](https://user-images.githubusercontent.com/11664152/98560269-deeeb200-22a7-11eb-98a1-3a2be7911f0d.png)
 

It will be nice to have more metadata(like tooltips etc...) on every node

**Comment by AlexSCorey** [comment]
@faroukellouze If we add additional data what additional data in that node would be helpful

**Comment by faroukellouze** [comment]
For example, in Job Slicing, you can show on which hosts each slice got executed(maybe top 3 hosts if each slice was executed on a large number of hosts). Also in the case of a JT node(in case of workflow template), you can show what inventory was selected and maybe some of the extra-vars.

**Comment by mabashian** [comment]
Real estate is a bit tight on the nodes themselves.  With our new UI, we have some help text that gets shown in the upper left corner whenever you hover over a node.  The idea is that extra data could be displayed here.

<img width="1109" alt="Screen Shot 2020-11-10 at 11 23 24 AM" src="https://user-images.githubusercontent.com/9889020/98701467-50317200-2347-11eb-91d0-4052091e5971.png">

We've also added the ability to "view" a node with a single click.  This will show you a read-only view of how the node is configured so you don't have to back through all the edit steps.

<img width="1677" alt="Screen Shot 2020-11-10 at 11 24 23 AM" src="https://user-images.githubusercontent.com/9889020/98701482-545d8f80-2347-11eb-9efe-f2a3cf3bb27d.png">

**Comment by faroukellouze** [comment]
I'm sorry for my late response :(

> We've also added the ability to "view" a node with a single click. This will show you a read-only view of how the node is configured so you don't have to back through all the edit steps.

This modal is brilliant :).

> With our new UI, we have some help text that gets shown in the upper left corner whenever you hover over a node. The idea is that extra data could be displayed here.

For this feature, I think that the help text still shows the obvious. I mean you are showing the name and type of the node which are very obvious and do not require a help text. I think maybe if the help text, depending on the type of the node, should show more data like the hostname when you're doing sliced jobs, or the inventory name when your doing a JT node.

**Comment by unlikelyzero** [comment]
@faroukellouze i think you're asking for https://github.com/ansible/awx/issues/2032 . Please re-open this issue if #2032 doesn't fully capture your use case!
