### ISSUE TITLE
Add checklist of hosts when prompting LIMIT on launching a template

### ISSUE THREAD

**Issue by faroukellouze** [ansible/awx#8564]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

When prompting the LIMIT option on launching templates, you only get to pass the pattern you want as a string, which is very useful when writing complex patterns. However, when you just want to limit the job on some hosts using the pattern `hostname1:hostname2` (which is the basic and simple usage), it will be nice if we have a checklist of all hosts in the used inventory, which will append a host to the pattern when you select it.
The checklist can be shown/hidden based on a toggle button that switches between basic/advanced options of the LIMIT feature or it could always be shown and used to append hosts to the existing pattern.
The reason behind my request is that I'm trying to build playbooks that are very easy to use by persons with zero knowledge of Ansible and AWX. Making these users just pick the target hosts of the job is much easier than asking them to write patterns. Also, you always have to navigate to the host list to remember the hostnames when you write patterns which means more navigations, etc.

**PS:**
By the way, this feature already exists when you just want to run ad-hoc commands and that's where I got the idea from
 
![image](https://user-images.githubusercontent.com/11664152/98655880-47896d80-2340-11eb-8cc9-3fb0444dd62e.png)

**Comment by wenottingham** [comment]
-> #1179
