### ISSUE TITLE
Feature Request: installer/inventory should offer mounting the plugins directory

### ISSUE THREAD

**Issue by JohnLar42** [ansible/awx#8565]
Currently the directories /var/lib/awx/.ansible/plugins  or /usr/share/ansible/plugins  are not mounted or volumes, so any plugins you add are lost if the docker container has to be rerun.  I added it is a variable in my inventory and into my templated docker-compose.
I'm surprised others have not needed this feature yet.

**Comment by wenottingham** [comment]
The recommendation is to not to modify the execution image.

This will be even more the case after we move to execution environments (https://github.com/ansible/awx/issues/5157 and https://github.com/ansible/awx/issues/7058)

In the meantime, we recommend plugin configs in source control (with the plugin in that project if needed)

**Comment by JohnLar42** [comment]
My issue is that I need a plugin to get a credential from a Vault that is used to login to git  Yes, I can/should source control my AWX config, but I can't put the plugin into a specific project as it is universal.
