### ISSUE TITLE
Project requirements installation doesn't use custom virtualenv

### ISSUE THREAD

**Issue by petracvv** [ansible/awx#8572]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When using a custom virtualenv with AWX and setting it as the environment for a project, AWX doesn't use it for running the ansible-galaxy commands to install dependencies. We are running into issues with that because we are using Ansible 2.10 in that virtualenv and are using the meta/requirements.yml method for defining dependencies which is not present in Ansible 2.9. This makes the ansible-galaxy installation not resolve all our dependencies.

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker on linux (docker-compose)
* Ansible version:  2.10.3
* Operating System: RHEL8
* Web Browser: Firefox

##### STEPS TO REPRODUCE

1. Create a new venv on your AWX host. Install psutil and ansible 2.10 into it.
2. Add the venv to the CUSTOM_VENV_PATHS setting in the AWX settings/system screen
3. Create 2 roles in git repositories, role1 and role2. Role 1 has the following in its `meta/requirements.yml`
    ```
    - src: git@<git-host>/role2
      scm: git
      version: master
    ```
4. Create a git repository for an ansible project and add the following to `roles/requirements.yml`;
    ```
     - src: git@<git-host>/role1
      scm: git
      version: master
    ```
5. Create an AWX project with the ansible project as the SCM source and set the Ansible Environment to the new custom venv with Ansible 2.10
6. Sync the project

##### EXPECTED RESULTS

I expect that both roles role1 and role2 are installed into the project for running ansible tasks because it used the Ansible version in the custom venv.

##### ACTUAL RESULTS

Only role1 is installed, because it used the Ansible version that ships with AWX which does not support this dependency method

##### ADDITIONAL INFORMATION

Otherwise, I was curious about the timeline for having Ansible 2.10 as the default version in AWX.

**Comment by wenottingham** [comment]
Custom env on a project is for "all JTs run from that project", not for the project_update.yml. Given the move to execution environments (https://github.com/ansible/awx/issues/5157 and https://github.com/ansible/awx/issues/7058), I'm not sure that will change - it certainly won't change in that direct way of using the custom venv.

2.10 will likely never be the 'default' version - the above move to execution environments is where future releases of ansible will live.

**Comment by petracvv** [comment]
OK, I see. Then what execution environment would the project_update.yml run in? Would that be something configurable?
Either way, I guess I'll have to look at alternatives for specifying our dependencies; or start moving to collections.

**Comment by wenottingham** [comment]
That will be tracked in https://github.com/ansible/awx/issues/8245

**Comment by blomquisg** [comment]
Since Execution Environments and Collections are replacing Virtual Environments, we're gonna close this to be tracked against #8245

**Comment by noesberger** [comment]
> OK, I see. Then what execution environment would the project_update.yml run in? Would that be something configurable?
> Either way, I guess I'll have to look at alternatives for specifying our dependencies; or start moving to collections.

Hi, did you found a solution? I have the same problem. I have custom collections in a internal git and I can't specify them in the requirements file, because this is a feature of 2.10. I need to find a way to use Ansible 2.10 also for Project syncs.
