### ISSUE TITLE
Ansible tower installation error

### ISSUE THREAD

**Issue by kcskribbl** [ansible/awx#8574]
##### ISSUE TYPE
 - Not able to install Ansible tower

**Comment by ryanpetrello** [comment]
Hey @tokarthikc,

This issue tracker is for the open source Ansible AWX project, not Red Hat's product.  Please contact Red Hat directly for help with support issues.

**Comment by ryanpetrello** [comment]
For what it's worth, it doesn't look like Oracle Linux is a supported platform for the version of Tower you're running (based on these published Red Hat docs):

https://docs.ansible.com/ansible-tower/latest/html/installandreference/requirements_refguide.html

**Comment by tokarthikc** [comment]
@ryanpetrello thank you. Does open source Ansible AWX project support Oracle Linux as supported platform?

**Comment by ryanpetrello** [comment]
@tokarthikc we don't have any plans to, no.  Also, if you're looking for something that's "supported", AWX isn't it:

https://www.ansible.com/products/awx-project/faq
