### ISSUE TITLE
RFE: Enhance the handling of external logging errors when a blocking i/o error is returned

### ISSUE THREAD

**Issue by hiyokotaisa** [ansible/awx#8576]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

In AWX PR #7292  a change was made to drop messages being sent to an external logger if a blocking i/o error is returned.

This RFE is to request an enhancement to the error handling when a blocking i/o error is returned so that messages being sent are not lost.

I can see the following comment on the commit (https://github.com/ansible/awx/pull/7292/commits/71640490621db31c29221c985b2b183f324e7247) that explains why it drops the message:

```
            # for <some reason>, rsyslogd is no longer reading from the domain socket, and
            # we're unable to write any more to it without blocking (we've seen this behavior
            # from time to time when logging is totally misconfigured;
            # in this scenario, it also makes more sense to just drop the messages,
            # because the alternative is blocking the socket.send() in the
            # Python process, which we definitely don't want to do)
```

But it would be great if it will have more robust handling of errors so that sending messages to the external logger can be retried at a later time to avoid the possibility of losing messages.

**Comment by ryanpetrello** [comment]
AWX's external logging system requires rsyslogd to be running and properly configured to accept and manage logs (and we don't have plans to implement _another_ failsafe).

If something else is needed, it can be accomplished by modifying your AWX's Python-based logging configuration to log via some alternative mechanism (such as a backup copy to the file system):

https://docs.python.org/3/library/logging.handlers.html#rotatingfilehandler
