### ISSUE TITLE
Add inventory as part of dynamic host filter

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#8581]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add inventory as part of dynamic host filter.

![image](https://user-images.githubusercontent.com/9053044/98982779-e30c1100-24ed-11eb-826b-db5327144719.png)

![image](https://user-images.githubusercontent.com/9053044/98982949-1cdd1780-24ee-11eb-84cf-30e2bf8f7f8e.png)

**Comment by unlikelyzero** [comment]
Covered by https://github.com/ansible/tower-qa/pull/5727
