### ISSUE TITLE
Ansible Email Notification: extra_vars appears as Unicode when Chinese is included

### ISSUE THREAD

**Issue by linora** [ansible/awx#8584]
##### ISSUE TYPE
- Feature Idea

##### SUMMARY

---

### Env：

**【AWX】**
- Version: 15.0.1
- Running in: Docker in CentOS 7 x86_64

**【Ansible】**
- Version: 2.9.14
- Python version: 3.6.8

---

When I provide the Chinese parameters in the extra_vars, the Ansible mail notification shows that this part of the Chinese is Unicode, as follows:

Job #111 had status running, view details at http://192.xxx.xxx.xxx/#/jobs/playbook/111

```json
{
   "id": 111,
   "name": "xxx/xxx/deploy_backup_job",
   "url": "http://192.xxx.xxx.xxx/#/jobs/playbook/111",
   "created_by": "xxx.xxx@xxx.com",
   "started": "2020-11-13T03:24:49.042308+00:00",
   "finished": null,
   "status": "running",
   "traceback": "",
   "inventory": "xxx/demo/dev001",
   "project": "xxx/db_base/proj001",
   "playbook": "playbooks/sop_xxx.yml",
   "credential": "xxx/os/xxx",
   "limit": "",
   "extra_vars": "{ \"xxx\": \"\\u6d4b\\u8bd5\\u6a21\\u5757\"}",
   "hosts": {}
}
```

**Comment by ryanpetrello** [comment]
Might be related to https://github.com/ansible/awx/issues/7400

**Comment by shanemcd** [comment]
It looks like this was resolved along with https://github.com/ansible/awx/issues/7400. If you are still seeing this, please open a new issue.
