### ISSUE TITLE
DNS servers in docker-compose.yml do not transfer to container /etc/resolv.conf

### ISSUE THREAD

**Issue by ghost** [ansible/awx#8585]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After editing the inventory file and adding the values for awx_alternate_dns_servers to the company's DNS servers they populate in the docker-compose.yml 

```
    dns_search:
      - americas.global-legal.com
      - asia.global-legal.com
      - emea.global-legal.com
    dns:
      - 10.2.6.13
      - 10.6.6.17
      - 10.2.2.17
```
The search domains appear correctly but the nameserver does not. 
 
##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.14
* Operating System: Centos 7.8.2003
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Edit the inventory file and add the name servers to the awx_alternate_dns_servers stanza. 

Run install.yml

##### EXPECTED RESULTS

Result 1. Log onto the awx_web or the awx_task container ping a server by name - ping responds with IP address and ping results
Result 2. cat /etc/resolv.conf:
`search americas.global-legal.com asia.global-legal.com emea.global-legal.com
nameserver 10.2.2.13
nameserver 10.6.2.17
nameserver 10.2.2.17
options ndots:0
` 

##### ACTUAL RESULTS

Result 1. Name or service not known
Result 2. cat /etc/resolv.conf
`search americas.global-legal.com asia.global-legal.com emea.global-legal.com
nameserver 127.0.0.11
options ndots:0
`

##### ADDITIONAL INFORMATION
I have tried this with one, two and three values in the server list.

**Comment by lemmy04** [comment]
you're running awx in a local_docker setup, right?

**Comment by ghost** [comment]
Yes I am. I will retract this bug since it is not a bug. The docker container uses the DNS server that is a part of the docker installation and is referenced by 129.0.0.11. I rebuilt my machine and was able to ping external machines using the search domains that are placed in the /etc/resolv.conf of all the containers. I guess I had a messed up installation and did not understand the internal Docker DNS.
