### ISSUE TITLE
Feature: Remove OPTIONS method from API

### ISSUE THREAD

**Issue by garamirseokim** [ansible/awx#8589]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

- AWX version: Ansible Tower 3.7
- If the OPTIONS method is not required for AWX to work, our customer needs to disable OPTIONS method in API according to their security guidelines to pass their security scanner check.

![スクリーンショット 2020-11-16 10 57 31](https://user-images.githubusercontent.com/58404577/99205076-34284780-2803-11eb-8f90-4d4eaa118d35.png)

**Comment by ryanpetrello** [comment]
AWX will not work without HTTP OPTIONS enabled - notable components of the user interface and the official CLI rely on it to properly function.
