### ISSUE TITLE
email notification support ms exchange server

### ISSUE THREAD

**Issue by linora** [ansible/awx#8590]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

email notification support MS Exchange mailbox?

**Comment by wenottingham** [comment]
The email notification speaks standard SMTP. It is unlikely we will update it for anything specific to MS Exchange.

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
