### ISSUE TITLE
AWX won't install, upgrading stuck, python errors

### ISSUE THREAD

**Issue by jangel97** [ansible/awx#8592]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

I am trying to install AWX in Debian 10, docker on linux. The Upgrading process is stucked.
![image](https://user-images.githubusercontent.com/38217290/99275156-71a0cb00-282b-11eb-9b5a-b797bd2c55b5.png)

##### ENVIRONMENT
* AWX version: 15.0.1 (Release: https://github.com/ansible/awx/archive/15.0.1.tar.gz)
* AWX install method: docker on linux
* Ansible version:  2.10.3
* Operating System: Debian 10
* Web Browser: Google Chrome 80.0.3987.149  

##### INVENTORY
```
localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python"
[all:vars]
dockerhub_base=ansible
use_docker_compose=true
awx_task_hostname=awx
awx_web_hostname=awxweb
postgres_data_dir="~/.awx/pgdocker"
host_port=80
host_port_ssl=443
docker_compose_dir="~/.awx/awxcompose"
pg_username=awx
pg_password=awxpass
pg_database=awx
pg_port=5432
admin_user=admin
admin_password=Redhat01.
create_preload_data=True
secret_key=cbdd4c70bbf82d572bfdd454b2817164e6b8061b8c8b4937d9134294d30e33
```

##### ERRORS NOTICED
awx_task:
```
awx_task    | django.db.utils.ProgrammingError: relation "main_instance" does not exist
awx_task    | LINE 1: SELECT (1) AS "a" FROM "main_instance" WHERE "main_instance"...
```

awx_postgres:
```
awx_postgres | 2020-11-16 15:52:17.938 UTC [1224] ERROR:  relation "django_migrations" does not exist at character 124
awx_postgres | 2020-11-16 15:52:17.876 UTC [1224] ERROR:  relation "conf_setting" does not exist at character 158
```
This is happenning with releases 15.0.1, 15.0.0 and latest pushed commit in `devel` branch.

Is it some issue regarding my inventory file? Is it a bug? If you need anymore information do not hesitate to ask. 

Thanks in advance!

**Comment by francilioaraujo** [comment]
@jangel97 the same happened to me. I solved it restarting the awx_task container. It seems the script does not apply all migrations the first time, but restarting the container it completes. I also saw a CRIT log line about supervisord running with root user, but I don't know if this has something related to this bug.

**Comment by jangel97** [comment]
Hello @francilioaraujo, I don't know why but today morning I redeployed release 15.0.1 and it worked from scratch!

In any case thank you!
