### ISSUE TITLE
Filtering group list by Group type -> Show all groups does not show all groups

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#8593]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
It actually shows all non-root groups (i.e. groups that have at least 1 parent: `parents__isnull=false`.

I'd propose we get rid of this option:

<img width="487" alt="Screen Shot 2020-11-16 at 12 56 39 PM" src="https://user-images.githubusercontent.com/9889020/99289667-40b09e00-280b-11eb-836f-b04fe5967c0b.png">

Since the default behavior of this list is to show all groups, this list is redundant.

**Comment by mabashian** [comment]
Duplicate of https://github.com/ansible/awx/issues/6503.  Closing

**Comment by mabashian** [comment]
Actually, this is a bit different from #6503 so going to keep this open.

**Comment by akus062381** [comment]
resolved
