### ISSUE TITLE
AWX 15.0.1: AWS EC2 Dynamic Source Inventory warning

### ISSUE THREAD

**Issue by paulthorburn** [ansible/awx#8595]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I did fresh install of AWX 15.0.1 and when I try to sync aws inventory the hosts appear but they have no tags or details and the job logs show a warning "has no "ec2_id" variable(s)".  I don't have this issue with my old server which is running 11.1.0

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.6
* Operating System: Ubuntu 20.04
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Under Inventories -> Add new inventory -> Click on Sources tab -> Create a new source -> Choose Source Amazon EC2 -> Save -> Sync

##### EXPECTED RESULTS

All my ec2 instances to be populated with tags and groups to be created

##### ACTUAL RESULTS

The host is there with either the Public IPv4 DNS or Private IPv4 DNS name and one group aws_ec2. There is a warning in the job log WARNING  Host "ip-X.X.X.X.us-west-2.compute.internal" has no "ec2_id" variable(s)

##### ADDITIONAL INFORMATION
![image](https://user-images.githubusercontent.com/48079072/99320667-ffc38400-2820-11eb-810e-082ed36075d1.png)

**Job Log**
`    1.812 INFO     Updating inventory 2: AWS
    1.824 INFO     Reading Ansible inventory source: /tmp/awx_5_21w2pa6x/aws_ec2.yml
    1.825 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    1.826 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/usr/pgsql-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    1.826 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
    2.921 ERROR    ansible-inventory 2.9.14
    2.924 ERROR      config file = /etc/ansible/ansible.cfg
    2.924 ERROR      configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
    2.924 ERROR      ansible python module location = /usr/lib/python3.6/site-packages/ansible
    2.924 ERROR      executable location = /usr/bin/ansible-inventory
    2.924 ERROR      python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
    2.925 ERROR    Using /etc/ansible/ansible.cfg as config file
    2.925 ERROR    Parsed /tmp/awx_5_21w2pa6x/aws_ec2.yml inventory source with auto plugin
    2.927 INFO     Processing JSON output...
    2.929 INFO     Loaded 1 groups, 2 hosts
    2.941 WARNING  Host "ip-x-x-x-x.ca-central-1.compute.internal" has no "ec2_id" variable(s)
    2.942 WARNING  Host "ip-x-x-x-x.ca-central-1.compute.internal" has no "ec2_id" variable(s)
2020-11-16 22:56:28,843 DEBUG    awx.main.models.inventory Going to update inventory computed fields, pk=2
2020-11-16 22:56:28,890 DEBUG    awx.main.models.inventory Finished updating inventory computed fields, pk=2, in 0.046 seconds
    3.338 INFO     Inventory import completed for AWS ITOps Account in 1.5s
`

**Comment by snooyen** [comment]
I'm seeing a similar issue -- in AWX >= 15.0.0, AWS EC2 Dynamic Inventories are not importing groups/tags.

Confirmed to be working as expected in 14.1.0 though

**Comment by snooyen** [comment]
@wenottingham related to #8569 ?

**Comment by wenottingham** [comment]
Likely unrelated.

If this is a fresh deployment, this looks to be the results of an intentional change in 15.x - we use a default plugin configuration by default. If you want specific sets of groups, put them in the plugin config. See some examples here. https://docs.ansible.com/ansible-tower/3.8.0/html/installandreference/inventory_plugins_templates.html#ir-inv-plugin-templates-reference

**Comment by gamuniz** [comment]
@s-hertel do we know why we throw that error for ec2_id?

`WARNING Host "ip-x-x-x-x.ca-central-1.compute.internal" has no "ec2_id" variable(s)`

**Comment by snooyen** [comment]
@wenottingham So we need to take the templates there, stick them in our project and source from our project?  Otherwise I'm unsure how to translate this to reconfigure the provided AWS EC2 Inventory Plugin

**Comment by paulthorburn** [comment]
@snooyen @gamuniz  i just took the config that wenottingham had linked to and pasted it into my source variables and now its working.

![image](https://user-images.githubusercontent.com/48079072/99837778-fab24d80-2b1c-11eb-9638-53cb644dbcb5.png)

**Comment by wenottingham** [comment]
Correct - we want you to have the full ability to configure how the sources are grouped, tagged, and any other options. We do migrate on upgrade older configs, but new configurations are just the plugin default, so they can be configured in the way you need.

AWS happens to be the one that requires the most custom configuration to match the prior legacy-script-compatible configuration.

**Comment by paulthorburn** [comment]
@wenottingham Since all the Source Variables are required to make the plugin work couldn't it pre-populate the field with the template when you chose your Source (i.e AWS, GCC, VMware etc..). Also it would help if the Source Variable tooltip was updated to point to the URL you provided as it currently says look in EC2.ini which isn't applicable any more.

**Comment by wenottingham** [comment]
If the plugin does not *function* (throws errors) without source variables, that is a bug we will look at and will try and fix.

If it's about the groups attached to the host, we are trying to move to match the default behavior of the plugins. Grouping by custom attributes is still available.

Tooltips were fixed here https://github.com/ryanpetrello/awx/commit/48934e85444dba1ad310311b8f95520e23915ad7, it's just not in a release yet.

**Comment by paulthorburn** [comment]
Sorry i should clarify, when you don't enter any Source Variables it works in the sense that it adds ec2 instances, the job log is just filled with a bunch of WARNINGS regarding 'has no "ec2_id" variable(s)' that i previously mentioned.

**Comment by wenottingham** [comment]
See https://github.com/ansible/awx/issues/8741#issuecomment-742823720

Closing as a duplicate with the wording there.
