### ISSUE TITLE
[ui_next] Logo appears too small on About modal

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8597]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Logo appears too small on About modal

##### ENVIRONMENT
* AWX version: b338da40c534d1b2809b5426b61f13eff7770434
* Operating System: Doesn't seem to matter
* Web Browser: Doesn't seem to matter

##### STEPS TO REPRODUCE
1. Click on About modal

##### EXPECTED RESULTS
Larger logo

##### ACTUAL RESULTS
Small logo

##### ADDITIONAL INFORMATION
![Screen Shot 2020-11-17 at 10 15 53 AM](https://user-images.githubusercontent.com/12446869/99408152-e6bce080-28bd-11eb-8b6d-4be7027916c2.png)

**Comment by mabashian** [comment]
Patternfly has a max height of 40px on that image.  cc @trahman73 if you feel like we should override this feel free to re-open.
