### ISSUE TITLE
[ui_next] Launched By sorting doesn't make sense on Jobs lists

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8599]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Launched By sorting doesn't make sense on Jobs lists. Nothing is shown.

##### ENVIRONMENT
* AWX version: 10664d1931d789c281e2c9d3d2f14c0a69cb9e13

##### STEPS TO REPRODUCE
1. Go to any Jobs List.
2. Change sort to 'Launched By'

##### EXPECTED RESULTS
Sorted by some attribute present on the rows/columns/list

##### ACTUAL RESULTS
Sorted by an invisible attribute 👻 

##### ADDITIONAL INFORMATION
![Screen Shot 2020-11-17 at 10 51 45 AM](https://user-images.githubusercontent.com/12446869/99412664-fd196b00-28c2-11eb-8189-bf86652d0253.png)

**Comment by mabashian** [comment]
Since the jobs list has been converted this is no longer an issue.  Can only sort by the columns present in the form.

<img width="1426" alt="Screen Shot 2021-02-03 at 4 13 42 PM" src="https://user-images.githubusercontent.com/9889020/106810375-dacdf880-663a-11eb-9703-ea73511e77e1.png">
