### ISSUE TITLE
Hosts not showing facts

### ISSUE THREAD

**Issue by mdbv** [ansible/awx#860]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

I can view a host's facts from the api, but not from the UI.

##### ENVIRONMENT
* AWX version: 1.0.2
* AWX install method: docker on linux
* Ansible version:  2.4.1.0
* Operating System: CentOS Linux release 7.4.1708 (Core)
* Web Browser: Chrome 63.0.3239.84

##### STEPS TO REPRODUCE

fresh install, only localhost in hosts

##### EXPECTED RESULTS

To be able to view ansible_facts for localhost via the UI

##### ACTUAL RESULTS

ansible_facts are not viewable via the UI, but can be retrieved via API

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/20052686/34120470-08aabd7a-e3e3-11e7-9224-e502f38aed59.png)
![image](https://user-images.githubusercontent.com/20052686/34120677-b61e71fe-e3e3-11e7-826f-a35f3a831396.png)

**Comment by worsco** [comment]
I went back to 1.0.0.557 (a Docker deployment of AWX) to check that facts display in the web UI.  I can confirm that FACTS do display in AWX 1.0.0.577 in the web UI and in the API.  

FACTS do not display in the web UI in any current version (up to today) of 1.0.2.x. However, FACTS do show up in the API (as this issue reports).

**Comment by worsco** [comment]
Issue persists (no facts in web UI) in AWX 1.0.2.327, Docker edition.  I can view facts through "http://my.example.local/api/v2/hosts/1/ansible_facts", but not in "http://my.example.local/#/hosts/1/ansible_facts?host_search=page_size:20;order_by:name"

**Comment by itcrowdsource** [comment]
Same here. Unable see the facts with version AWX 1.0.2.327

**Comment by mabashian** [comment]
https://github.com/ansible/awx/pull/957 should address this bug - waiting for all the checks to pass before merging.

**Comment by mabashian** [comment]
#957 is now merged.  I'm going to close this issue for now but will re-open if the bug persists.

**Comment by anthonyd-cd** [comment]
hello, sorry kinda new to Ansible/AWX here but I have this issue. The file awx/ui/client/src/inventories-hosts/shared/ansible-facts/ansible-facts.controller.js appears to be updated correctly as I just installed this 7 days ago. When I go to facts it's still empty though on the jobs "playbooks" themselves I can see that it does gather facts like so:

 },
        "facter_hostname": "apache",
        "facter_operatingsystem": "Ubuntu",
        "module_setup": true,
        "facter_uptime_hours": 4,
        "ohai_block_device": {
            "ram14": {
                "removable": "0",
                "size": "131072"
            },
            "ram15": {
                "removable": "0",
                "size": "131072"
            },
            "ram12": {
                "removable": "0",
                "size": "131072"
            },
            "ram13": {
                "removable": "0",
                "size": "131072"
            },
            "ram10": {
                "removable": "0",
                "size": "131072"
            },
            "ram11": {
                "removable": "0",
                "size": "131072"

but when I go to the actual host itself, i see nothing in the facts, should I not see the same info in both places? 

![image](https://user-images.githubusercontent.com/35614549/35746791-e275a258-07fc-11e8-8315-772440085954.png)

**Comment by jakemcdermott** [comment]
~duplicate / likely~ possibly related to https://github.com/ansible/awx/issues/1110

**Comment by theiamdude** [comment]
I am having the same issue in 2.0.1. and even the API does not return the facts collected from ansible setup module.

**Comment by chrismeyersfsu** [comment]
@theiamdude did you enable fact cache on the job template?

**Comment by Commifreak** [comment]
Same here (AWX 2.1.2.0) - Facts are gathered but not showed on host-page. The tick-box `Use Fact Cache` is OFF. Should it be enabled?

**Comment by chrismeyersfsu** [comment]
Yes it should be turned on (ticked) for facts too be gathered

**Comment by rrraju-kreddy** [comment]
do we have solution onfacts, i still see no facts visible in web gui
