### ISSUE TITLE
[ui_next] Cancel Jobs Button is available for completed Jobs

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8600]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Cancel Jobs Button is available for completed Jobs. Results in inert action

##### ENVIRONMENT
* AWX version: b338da40c534d1b2809b5426b61f13eff7770434

##### STEPS TO REPRODUCE
1. Run a Job
2. Navigate to list view with the completed Job (i.e. /jobs/)
3. Select a completed Job and click Cancel

##### EXPECTED RESULTS
1. Cancel disabled for jobs which are already completed
2. Feedback to let the user know that action cannot be performed. This is important in the case where a user has several jobs to cancel alongside completed jobs.

##### ACTUAL RESULTS
1. Cancel button appears for jobs which are completed
2. Inert Action on Cancel operation

##### ADDITIONAL INFORMATION
![Screen Shot 2020-11-17 at 11 00 54 AM](https://user-images.githubusercontent.com/12446869/99413831-2f779800-28c4-11eb-914e-38249b0129ac.png)

**Comment by mabashian** [comment]
IMO we should do this: https://github.com/ansible/awx/issues/7516#issuecomment-746449855.  In which case this button is fine and this issue could be closed.  If we don't end up doing that then yes, we should remove this button from this list.

**Comment by mabashian** [comment]
Closing in favor of #7516 (comment)
