### ISSUE TITLE
[ui_next] Clickaway from Navbar does not collapse Navbar

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8601]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The Navbar does not automatically close when a clickaway is performed. This ticket is filed as a ux issue to discuss what the intended implementation will be for NavBar collapse

##### ENVIRONMENT
* AWX version: b338da40c534d1b2809b5426b61f13eff7770434

##### STEPS TO REPRODUCE
1. Expand NavBar
2. Clickaway on a forrm

##### EXPECTED RESULTS
NavBar to collapse when clicking away from NavBar

##### ACTUAL RESULTS
NavBar remains open until the Hamburger is clicked

**Comment by mabashian** [comment]
This is how the PF component works.  We can open an issue against the lib but I don't think we want to deviate from the base behavior.  cc @trahman73 if you feel differently feel free to re-open.
