### ISSUE TITLE
[ui_next] JT Schedule form displays an Odd message if JT has Survey

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8602]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
JT Schedule form displays an Odd message if JT has Survey

##### ENVIRONMENT
* AWX version: b338da40c534d1b2809b5426b61f13eff7770434

##### STEPS TO REPRODUCE
1. Create a JT with a Survey
2. Attempt to set a schedule for the JT

##### EXPECTED RESULTS
No errors

##### ACTUAL RESULTS
'text' value missing, 'textarea' value missing, 'integer' value missing, 'multiplechoice' value missing, 'multiselect' value missing

##### ADDITIONAL INFORMATION
![Screen Shot 2020-11-17 at 11 14 27 AM](https://user-images.githubusercontent.com/12446869/99415687-1374f600-28c6-11eb-98d0-c9d9f5c4461d.png)

**Comment by mabashian** [comment]
Being tracked by https://github.com/ansible/awx/issues/7692
