### ISSUE TITLE
[ui_next] Credentials advanced search is missing Keys in dropdown

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8603]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
No Keys shown on advanced Search query for Credentials. Other resources may be affected so marking as high priority.

##### ENVIRONMENT
* AWX version: b338da40c534d1b2809b5426b61f13eff7770434

##### STEPS TO REPRODUCE
1. Navigate to Credentials form
2. Select Advanced Search and Click on Keys dropdown

##### EXPECTED RESULTS
Keys available for query

##### ACTUAL RESULTS
No Keys in dropdown

##### ADDITIONAL INFORMATION
![Screen Shot 2020-11-17 at 11 21 37 AM](https://user-images.githubusercontent.com/12446869/99416653-13c1c100-28c7-11eb-8218-d2aa03c0b40e.png)

**Comment by tiagodread** [comment]
Tests covered by https://github.com/ansible/tower-qa/pull/5831
