### ISSUE TITLE
AWX collection: instance_group for projects and templates support

### ISSUE THREAD

**Issue by a-dawg** [ansible/awx#8604]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
This is needed when using multiple instance group. For now no options is available from the job_templates or inventory objects

**Comment by wenottingham** [comment]
What do you mean? Instance groups can be assigned at the org, inventory, etc. level.

**Comment by a-dawg** [comment]
my bad, I meant this is not available from the awx collection

**Comment by sean-m-sullivan** [comment]
Note for myself as looking at this. Instance group should be part of 
tower_inventory
tower_organization
tower_job_template

**Comment by beeankha** [comment]
PR https://github.com/ansible/awx/pull/9804 takes care of `tower_inventory`, `tower_job_template` and `tower_organization` modules and has been merged! :tada:

**Comment by AlanCoding** [comment]
resolved
