### ISSUE TITLE
Credential field missing from adhoc command output details

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#8606]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Here's the output details:

<img width="1680" alt="Screen Shot 2020-11-17 at 12 46 34 PM" src="https://user-images.githubusercontent.com/9889020/99427155-0d394680-28d3-11eb-83e7-797b0dfb26a4.png">

Here's the object:

<img width="674" alt="Screen Shot 2020-11-17 at 12 46 48 PM" src="https://user-images.githubusercontent.com/9889020/99427179-14605480-28d3-11eb-839d-312cf29f8134.png">

##### STEPS TO REPRODUCE
1. Launch an adhoc command and select a machine credential
2. Observe output results

##### EXPECTED RESULTS
Selected credential to be listed

##### ACTUAL RESULTS
Selected credential is not listed

**Comment by tiagodread** [comment]
Closing this issue, the PR was merged and test are covered in 5745
