### ISSUE TITLE
Notification sender email not shown

### ISSUE THREAD

**Issue by shortsteps** [ansible/awx#861]
Hi all,
I've just installed AWX and configured a Notification template.
I use Gmail smtp server, I correctly authenticate and send test email with admin@mydomain user/pass. I set the "Sender mail" to awx@mydomain (this account doesn't exist), however the mail arrives as "admin@mydomain" sender. 

Any help? Maybe I'm not correctly undestanding that field.

Thanks a lot.

**Comment by cchurch** [comment]
You'll need to add awx@mydomain as an alias to the admin@mydomain account (https://support.google.com/a/answer/33327?hl=en), and then setup admin@mydomain to be able to send as awx@mydomain (https://support.google.com/mail/answer/22370). Google's SMTP servers will rewrite the `From:` header if it's not from a known address.

**Comment by shortsteps** [comment]
@cchurch , thanks a lot. It worked.
