### ISSUE TITLE
Cannot add approval node to a previously deleted node

### ISSUE THREAD

**Issue by fosterseth** [ansible/awx#8613]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: awx: 15.0.1
* Operating System: fedora 32
* Web Browser: chrome

##### STEPS TO REPRODUCE

1. Copy a JT (demo, for example).
2. Create a workflow, add a single node with this JT. Save.
3. Delete this JT.
4. Go to workflow template visualizer and add an approval node for the `Deleted` square. Clicking Save will just hang.

However, you can successfully add the approval node via the API by posting to `api/v2/workflow_job_template_nodes/8/create_approval_template/`

**Comment by ryanpetrello** [comment]
😶 hang?

Is there an HTTP request made?  Any errors in the browser dev console?

**Comment by fosterseth** [comment]
Went back to check, there are errors in the browser console, and no HTTP requests are made

![image](https://user-images.githubusercontent.com/8745776/99552628-387f6c80-298b-11eb-84d2-d90a3b23aa36.png)

**Comment by unlikelyzero** [comment]
@wenottingham this edgecase looks like a great issue to ignore in the classic experience

**Comment by nixocio** [comment]
This behavior is not present on the new UI.
