### ISSUE TITLE
AWX Project sync fails to fetch collections when it's from a private git repo

### ISSUE THREAD

**Issue by nicolas-g** [ansible/awx#8625]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Installed AWX version **14.1.0** / Ansible **2.9.11**, we have a project in AWX that is failing to sync with our Github repo that using Ansible collections. Our collections are hosted in our private Github repo, we know that support for private collections was added in Ansible **2.10** as per [issue 8257](https://github.com/ansible/awx/issues/8257).

For this reason we have successfully created a virtual env in AWX with Ansible **2.10** installed, the custom virtual env can be successfully used by our jobs but the Github project job sync fails which is the step executed before a job can start running.

##### ENVIRONMENT
* AWX version: 14.1.0
* AWX install method: Kubernetes
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Create a Project in AWX to clone the git repo with your Ansible code
Set to use a custom virtual env where you have Ansible **2.10.3** installed 

**requirements.yml** or **collections/requirements.yml**
```
collections:
  - name: git@github.com:ExampleOrg/my_private_collections.git
    type: git
    version: master
```

##### EXPECTED RESULTS

AWX Project sync job should run successfully with no errors and install collections.

##### ACTUAL RESULTS

When you click on Project sync it fails:
```
Identity added: /tmp/awx_94_779m6jh3/artifacts/94/ssh_key_data (user@USDETMB)
PLAY [Update source tree if necessary] *****************************************
TASK [update project using git] ************************************************
changed: [localhost]
TASK [Set the git repository version] ******************************************
ok: [localhost]
TASK [Repository Version] ******************************************************
ok: [localhost] => {
    "msg": "Repository Version a596d5475fccb8e3607ae34789f8002f9b12fb86"
}
PLAY [Install content with ansible-galaxy command if necessary] ****************
TASK [detect requirements.yml] *************************************************
ok: [localhost]
TASK [fetch galaxy roles from requirements.yml] ********************************
skipping: [localhost]
TASK [detect collections/requirements.yml] *************************************
ok: [localhost]
TASK [fetch galaxy collections from collections/requirements.yml] **************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["ansible-galaxy", "collection", "install", "-r", "collections/requirements.yml", "--collections-path", "/var/lib/awx/projects/.__awx_cache/_25__decisioning_ansible/stage/requirements_collections"], "delta": "0:00:00.507362", "end": "2020-11-18 15:19:28.115890", "msg": "non-zero return code", "rc": 1, "start": "2020-11-18 15:19:27.608528", "stderr": "ERROR! Invalid collection name 'git@github.com:ExampleOrg/my_private_collections.git', name must be in the format <namespace>.<collection>. Please make sure namespace and collection name contains characters from [a-zA-Z0-9_] only.", "stderr_lines": ["ERROR! Invalid collection name 'git@github.com:ExampleOrg/my_private_collections.git', name must be in the format <namespace>.<collection>. Please make sure namespace and collection name contains characters from [a-zA-Z0-9_] only."], "stdout": "Process install dependency map\n|\b", "stdout_lines": ["Process install dependency map", "|\b"]}
PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
```
When I run Ansible from my local machine don't get any errors using the same collections.

##### ADDITIONAL INFORMATION
NA

**Comment by wenottingham** [comment]
This is (effectively) https://github.com/ansible/awx/issues/8572 - we don't use custom venvs for project updates.
