### ISSUE TITLE
Credentials have unexpected summary_fields host, project

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#863]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Unexpected fields in credential summary fields

##### ENVIRONMENT
* AWX version: 1.0.2-301
* AWX install method: docker for mac
* Ansible version:  N/A
* Operating System: N/A
* Web Browser: N/A

##### STEPS TO REPRODUCE
GET /api/v2/credentials/

inspect summary_fields

##### EXPECTED RESULTS
no related host or project, these don't make sense

##### ACTUAL RESULTS
```json
"summary_fields": {
    "host": {},
    "project": {},
    ...
```

**Comment by AlanCoding** [comment]
4/1/2019 still a bug, ping @jakemcdermott, suspect this is related to `__getattr__`, we should re-test issue after https://github.com/ansible/awx/pull/3098

**Comment by ryanpetrello** [comment]
@AlanCoding @jakemcdermott one of you want to verify this and see if we can close it?

**Comment by AlanCoding** [comment]
5/3/2019 confirmed this bug still exists. Example credential - AWS type shows it. Right now I cannot find any credential which does not show these empty fields (only looking on first page).

**Comment by TheRealHaoLiu** [comment]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/44379968/230927637-130ebf2b-1fed-49db-a9a5-461b1aa5f906.png">
doesn't seem like it's there anymore

**Comment by AlanCoding** [comment]
Confirming - I don't see these anymore either.
