### ISSUE TITLE
Add conditional option to prevent backing up venvs

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#8632]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add an optional conditional for backing up venvs. In some situations, customers may wish to only backup the DB portion of Tower and not all the venvs. Adding a when conditional defaulted to true that can be passed to the include could solve this.

**Comment by smatterchew** [comment]
This would be handy for us.  We install our virtual environments on shared remote storage using an Ansible play, attaching it to each node that requires it.  For us, backing up these environments is extra time and disk space.

**Comment by wenottingham** [comment]
As we are removing venv support from awx, we wouldn't do this here.
