### ISSUE TITLE
Difference between metrics on interface and API

### ISSUE THREAD

**Issue by Tioborto** [ansible/awx#8637]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
We notice a difference between the metrics reported in the "instance groups" tab and what is reported by the API /metrics.

##### ENVIRONMENT
* AWX version: 15.0.0
* AWX install method: kubernetes
* Ansible version:  2.9.13

##### STEPS TO REPRODUCE

Go to `Instance Groups` and show `TOTAL JOBS` key -> **450 jobs**
![image](https://user-images.githubusercontent.com/29703972/99677957-950d8500-2a7a-11eb-9740-e975391d0bb5.png)

Compare with api/v2/metrics `awx_instance_status_total` data -> Total = **296 jobs**
```
# HELP awx_instance_status_total Status of Job launched
# TYPE awx_instance_status_total gauge
awx_instance_status_total{node="awx-58fdc7f96b-mc6r5",status="successful"} 177.0
awx_instance_status_total{node="awx-58fdc7f96b-mc6r5",status="failed"} 30.0
awx_instance_status_total{node="awx-58fdc7f96b-mc6r5",status="canceled"} 4.0
awx_instance_status_total{node="awx-58fdc7f96b-mc6r5",status="running"} 3.0
awx_instance_status_total{node="awx-54bb89d4c7-jj4n2",status="successful"} 8.0
awx_instance_status_total{node="awx-58fdc7f96b-sl225",status="running"} 2.0
awx_instance_status_total{node="awx-58fdc7f96b-sl225",status="canceled"} 3.0
awx_instance_status_total{node="awx-58fdc7f96b-sl225",status="successful"} 43.0
awx_instance_status_total{node="awx-58fdc7f96b-sl225",status="failed"} 26.0
```

Compare with api/v2/metrics `awx_status_total` data -> Total = **323 jobs**
```
# HELP awx_status_total Status of Job launched
# TYPE awx_status_total gauge
awx_status_total{status="failed"} 63.0
awx_status_total{status="canceled"} 9.0
awx_status_total{status="running"} 7.0
awx_status_total{status="successful"} 244.0
```

##### EXPECTED RESULTS

Same number everywhere

**Comment by blomquisg** [comment]
@kdelee Did you file something similar to this?  If so, can you link it here and close this as a dup?

**Comment by ryanpetrello** [comment]
@fosterseth do you think this could be related to your recent bug fix?

**Comment by fosterseth** [comment]
@ryanpetrello yes I believe this is related, and should be fixed with my PR

**Comment by ryanpetrello** [comment]
@shanemcd @kdelee I've classified this as `needs_test`, because it looks related to @fosterseth's recent bug fix (https://github.com/ansible/awx/pull/9671)

**Comment by kdelee** [comment]
This has been verified elsewhere, closing as a duplicate
