### ISSUE TITLE
Cannot schedule Repeat Frequency to None

### ISSUE THREAD

**Issue by joshed17** [ansible/awx#8638]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Cannot set template schedule Repeat Frequency to "None".

##### ENVIRONMENT
* AWX version:AWX 7.0.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.4
* Operating System: 
* Web Browser:

##### STEPS TO REPRODUCE

Going to a Job Template, set the repeat Frequency to “None(run once)”, save it. 

##### EXPECTED RESULTS

I expect to see “None(run once)” when I select the repeat Frequency to that option.

##### ACTUAL RESULTS

When you go back to the created schedule, the schedule is set automatically to Daily. It also happens with existing schedules.

##### ADDITIONAL INFORMATION

NA

**Comment by unlikelyzero** [comment]
@joshed17 have you tried this on the most recent version of AWX? 7.0.0 is quite old

**Comment by mabashian** [comment]
These two things are functionally the same, just presented differently:

<img width="1555" alt="Screen Shot 2020-11-20 at 11 29 22 AM" src="https://user-images.githubusercontent.com/9889020/99824481-c42c0100-2b23-11eb-8582-35d38563135e.png">

<img width="1535" alt="Screen Shot 2020-11-20 at 11 29 41 AM" src="https://user-images.githubusercontent.com/9889020/99824494-c8581e80-2b23-11eb-9a34-a97d8743f57d.png">

The `None (Run Once)` option is just a shortcut for the form configuration in the second screenshot.  It's probably possible that we could detect this and maintain the exact same form field values in the edit scenario but functionally, they are the same.

**Comment by mabashian** [comment]
If we did attempt to detect this scenario and display `None (Run Once)` then we'd have the same problem in the other direction.  If you filled out the Add form to match the second screenshot, we'd display the Edit form as `None (Run Once)`.  Without storing more info in the db we won't be able to adequately solve this problem.
