### ISSUE TITLE
View total number of duplicated managed nodes in the AWX Dashboard

### ISSUE THREAD

**Issue by rcdlinux** [ansible/awx#8645]
##### ISSUE TYPE
- If we have a temporary inventory for managed hosts which are making the inicial setup and bootstrap process in the environment, those hosts are temporarily duplicated into the main inventory and they are added and counted as the total number of managed hosts in AWX Dashboard.

 
##### SUMMARY

- This behavior is showing that there are more hosts into the inventory and causing a concern about finding what is the right number of hosts in use because the AWX Dashboard is showing the total number of hosts from all inventories. Since this is a standard behavior, a way to view/identify the total number of duplicated managed nodes in the database regardless of the inventory used will be very helpful because the total number of hosts displayed nowadays don't do that.

**Comment by ryanpetrello** [comment]
Hey Roberto,

This issue tracker is for the open source Ansible AWX project.  If you've got questions or a support issue with Ansible Tower, please reach out directly to Red Hat.

**Comment by rcdlinux** [comment]
Hi Ryan!

I've edited the request to best fit with AWX Project, could you reconsider it as a RFE to the project? It really will help a lot!

Thank you very much!

**Comment by wenottingham** [comment]
This isn't really something we target in AWX from a UI view; you can see this data in /api/v2/metrics (active hosts).
