### ISSUE TITLE
Test queries needs update

### ISSUE THREAD

**Issue by sophie200** [ansible/awx#8646]
https://github.com/ansible/awx/blob/b6a55e53d525655a116b99e9b825c9f9a87845e1/awx/main/tests/functional/test_projects.py#L202

https://github.com/ansible/awx/blob/b6a55e53d525655a116b99e9b825c9f9a87845e1/awx/main/tests/functional/api/test_rbac_displays.py#L317

I'm wondering what the protocol here is when updating queries that reference deleted or renamed fields in tests. For example, in the lines above the deleted field 'organization' in both the project and workflowjobtemplate model was deleted in previous migrations, yet they're still referenced here in these tests. So, what's the protocol when updating these test queries?

**Comment by wenottingham** [comment]
Hi - this is not really the place for this sort of discussion. This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you're developing new things and want to talk to the developers, please try the IRC channel or mailing list:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
