### ISSUE TITLE
Add library license checks for new ui

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#8647]
For the old ui, we do automatic licensing checks for 3rd party libraries: https://github.com/ansible/awx/blob/devel/awx/ui/utils/get_licenses.js

This issue is for duplicating that process (or making an equivalent one) for the new ui.

**Comment by mabashian** [comment]
@jakemcdermott It looks like you've got something cooking for this.  If I'm mistaken feel free to undo my label/assignment changes.

**Comment by jakemcdermott** [comment]
@wenottingham ended up fixing this https://github.com/ansible/awx/pull/8763

closing
