### ISSUE TITLE
Create Foreman inventory with hostname/shortname only 

### ISSUE THREAD

**Issue by rcdlinux** [ansible/awx#8648]
##### ISSUE TYPE
 - The foreman collection/plugin used in AWX can't filter the FQDN of hosts imported only by its hostname/shortname. If Foreman has all hosts registered as "host.domain" this is the name imported by AWX. 

##### SUMMARY

- A feature or variable which we could enable in the plugin to remove the domain part from "host.domain" when importing a Foreman inventory would be very useful to have a inventory only with hostname/shortname of hosts imported from Foreman.

**Comment by wenottingham** [comment]
This would need to be an option in the plugin, and then in could be specified in the AWX plugin config.

That would need to be filed at https://github.com/theforeman/foreman-ansible-modules/issues.

**Comment by benjdudas** [comment]
RFE opened with plugin maintainers: https://github.com/theforeman/foreman-ansible-modules/issues/1070

**Comment by rcdlinux** [comment]
Hi team,

We have now [one option](https://github.com/theforeman/foreman-ansible-modules/issues/1070) to configure the hostname in Foreman. Can we have it on next versions of AWX/Tower?

Thank you all!

**Comment by wenottingham** [comment]
The change mentioned in that linked PR would need to be in a released collection version before it would be picked up by AWX.

**Comment by wenottingham** [comment]
This should be in currently released/used theforeman.foreman and redhat.satellite collections.

**Comment by rcdlinux** [comment]
Thank you @wenottingham !!!

Best regards,

**Comment by rcdlinux** [comment]
Sorry, reopening because I've closed it too early (state:needs_test ) ;-)

**Comment by Zokormazo** [comment]
This feature was released on 1.5 . We are using 2.x now on our default ees
