### ISSUE TITLE
Implement update_password option

### ISSUE THREAD

**Issue by grumpy-penguin** [ansible/awx#8652]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Some fields return value $encrypted$ when it has been set and null when a value hasn't been applied. This is usually the case for passwords. Where such fields exist it and it makes sense (for example with awx.awx.tower_settings), implement an option similar to ansible.builtin.user where update_password can either be on_create or always.

Current behaviour is if a lookup is used to source a secret from an external source the task will always change.

**Comment by AlanCoding** [comment]
Resolved

https://github.com/ansible/awx/blob/1d340c5b4e91399e98926b3a681ebcefc4d02697/awx_collection/plugins/modules/user.py#L63-L68
