### ISSUE TITLE
Azure Resource Manager Source do not use default parameters and source variables

### ISSUE THREAD

**Issue by VitaliyFedorov** [ansible/awx#8653]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Azure Resource Manager Source use `default_inventory_hostname` azure property instead of `name` to set host name for host in inventory
Azure Resource Manager Source do not create any groups with no source variables or with any source variables specified.

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.14
* Operating System: Ubuntu 18.04
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Do clean install from https://github.com/ansible/awx/blob/devel/INSTALL.md
2. Add Azure Resource Manager Credential
3. Add Empty Inventory
4. Add Azure Resource Manager Inventory Source
5. Run Sync of Azure Resource Manager Inventory Source manually

##### EXPECTED RESULTS

Host name of hosts after sync should be the same as azure machine name
Inventory Group for each azure resource group should be created

##### ACTUAL RESULTS

All virtual machines synced in inventory hosts but without proper name (e.g. vm name is vm-01, but host name is vm-01_b7dd)
No new inventory groups is created

**Comment by wenottingham** [comment]
Does it work if you add the appropriate configuration items as documented here for the groups that you want? https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_inventory.html

**Comment by wenottingham** [comment]
We have moved to default configurations for sources in 15.0.1, to allow you to specify the configuration you want, as noted in the prior comment.

**Comment by VitaliyFedorov** [comment]
Very sorry for long response.
@wenottingham your suggestion is work like a charm
Looks like problem in documentation and in `Source Variables` field annotation

> Use the Source Variables field to override variables found in azure_rm.ini and used by the inventory update script. Enter variables using either JSON or YAML syntax. Use the radio button to toggle between the two. For a detailed description of these variables, view the azure_rm.ini inventory script in the Ansible Collections GitHub repo.
https://docs.ansible.com/ansible-tower/latest/html/userguide/inventories.html#ug-source-azure

So `Source Variables` is **NOT** override variables from azure_rm.ini, they override variables from https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_inventory.html

So please fix it, because it's lead to misunderstood.
