### ISSUE TITLE
[RFE] To configure the maximum number of simultaneous logged in sessions for Web UI and API separately

### ISSUE THREAD

**Issue by sugitk** [ansible/awx#8662]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

"Maximum number of simultaneous logged in sessions" parameter can manage the maximum number of sessions for each user.  The customer wants to manage them separately.

**Comment by wenottingham** [comment]
A login is a login to the API, UI sessions are a subset of that.

There's nothing separate to track.

**Comment by ryanpetrello** [comment]
Also, there's no such thing as "an API login".  While the UI has persistent browser sessions, API requests are stateless (you either use basic auth, or an HTTP header for your OAuth2 token).
