### ISSUE TITLE
AWX supporting multiple requirements.yml within the same project/repo

### ISSUE THREAD

**Issue by xding2020** [ansible/awx#8665]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

According to the [project_update.yml](https://github.com/ansible/awx/blob/devel/awx/playbooks/project_update.yml), it needs requirements.yml to be exactly at <project-top-level-directory>/roles/requirements.yml. However, putting multiple requiremensts.yml (e.g. for different envs) in the same repo is also widely used, such as architecture below:
repo
├── inventory
│   └── inventory
└── playbook
    ├── prod
    │   ├── deploy.yml
    │   └── requirements.yml
    ├── qe
    │   ├── deploy.yml
    │   └── requirements.yml
    ├── stage
    │   ├── deploy.yml
    │   └── requirements.yml
    └── test
        ├── deploy.yml
        └── requirements.yml

This will avoid a lot of redundancy and make the project easier to maintain. Also it allows using different versions of ansible roles for different deployment environments. 

Edit:
This could be achieved by using a customized project_update.yml. But it would be very nice for awx to get it officially supported.

**Comment by wenottingham** [comment]
-> #106
