### ISSUE TITLE
Cloud inventory sources give "Inventory File" field although it is not relevant

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#8669]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The "Inventory file" entry in the inventory source page (API `source_path` field) is only relevant to SCM inventory sources (and maybe "file" type), but it is showing up for types like EC2.

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: N/A
* Ansible version:  N/A
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Create an EC2 inventory source

##### EXPECTED RESULTS

Only relevant fields

##### ACTUAL RESULTS

![Screenshot from 2020-11-24 14-02-15](https://user-images.githubusercontent.com/1385596/100139892-248dac00-2e5e-11eb-807e-10b491d6a0f3.png)

The Inventory file entry is not relevant to this source, and it is incorrect to say that it is `/`, meaning root.

**Comment by unlikelyzero** [comment]
No unit tests added.

We should add a unit test or simple e2e test

**Comment by unlikelyzero** [comment]
@akus062381 please perform manual verification and ensure testability on this details page

**Comment by akus062381** [comment]
Manually verified, testability verified, stubs added
