### ISSUE TITLE
[ui_next] Relaunch against failed hosts

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8670]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
We may need to add Relaunch Jobs against failed hosts for feature parity for the next release of Tower. I don't know if this feature is worth the complexity of testing, development, and support.

This would be on the Jobs List and Job Result Output

**Comment by unlikelyzero** [comment]
@mabashian @wenottingham discuss

**Comment by wenottingham** [comment]
Yes, we should reimplement this in the new UI if it is not in the current version of it.

**Comment by dolgovas** [comment]
very-very need feature

**Comment by one-t** [comment]
Unit test coverage looks great on this one and I've verified this functionality works as expected.

**Comment by unlikelyzero** [comment]
Re-opening for stubs and a functional test. This feature was only discovered for feature parity due to our test automation backlog. Unit test coverage is essential, but the value of e2e testing is that we discover the user impact that _unrelated changes_ have on this functionality.

https://github.com/ansible/awx/issues/3155
https://github.com/ansible/awx/issues/3319
https://github.com/ansible/awx/issues/3290

**Comment by unlikelyzero** [comment]
@akus062381 will automate these tests

**Comment by akus062381** [comment]
these tests have been automated. closing this issue.
