### ISSUE TITLE
Inventories with sources can be copied in the ui_next

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#8673]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Any inventory with sources can not be copied in the old UI, but you can do that in the ui next

##### STEPS TO REPRODUCE

1. Create an inventory
2. Navigate to Sourced tab
3. Create a source
4. Navigate to inventories list
5. Click on copy inventory button
 
##### EXPECTED RESULTS

The user should see a tooltip with the message "inventory with sources cannot be copied" on hover over copy button and this button should be disabled

##### ACTUAL RESULTS

This copy button is enabled and the user can copy the inventory
![copy](https://user-images.githubusercontent.com/12464858/100152414-6e3bbe00-2e81-11eb-8934-98501acd71f9.gif)

**Comment by nixocio** [comment]
Related to: https://github.com/ansible/awx/issues/7679

**Comment by mabashian** [comment]
Yea, this will be solved by https://github.com/ansible/awx/issues/7679.

If we decide that we don't want to do https://github.com/ansible/awx/issues/7679 then we should remove the copy button from rows with sources.
