### ISSUE TITLE
Show copy resource success toast on all pages where resources can be copied

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#8674]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Success toast isn’t displayed when copying resources

##### STEPS TO REPRODUCE

1. Navigate to inventories
2. Copy an inventory

##### EXPECTED RESULTS

The user should be able to see on the top right of the screen a success toast (like the old UI)

##### ACTUAL RESULTS

The resource is copied but the toast isn’t displayed 

##### ADDITIONAL INFORMATION

- Need to verify others parts that this toast is displayed

![toast](https://user-images.githubusercontent.com/12464858/100152892-26696680-2e82-11eb-90e5-85f12cc6dcbb.gif)

**Comment by keithjgrant** [comment]
mockup for a page with a similar alert here: https://tower-mockups.testing.ansible.com/patternfly/exec-env/exec-env-detail-test/

**Comment by InnocentK** [comment]
Resolved
