### ISSUE TITLE
The user can’t copy notification templates

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#8675]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
In the notification template list item, the user cannot copy a notification template

##### STEPS TO REPRODUCE

1. Navigate to notification template
2. Create a new notification template
3. Try to copy this template from notifications list

##### EXPECTED RESULTS

The notification list item should contain a button to copy the notification

##### ACTUAL RESULTS

None copy button is displayed

##### ADDITIONAL INFORMATION
Old:

![image](https://user-images.githubusercontent.com/12464858/100153415-d6d76a80-2e82-11eb-8179-dedd3f258264.png)

New

![image](https://user-images.githubusercontent.com/12464858/100153453-e2c32c80-2e82-11eb-9d8a-98b8b3abcc9e.png)

**Comment by mabashian** [comment]
This is a dupe of #7879
