### ISSUE TITLE
Allow chaining undefined attributes in custom notification templates.

### ISSUE THREAD

**Issue by willhaines** [ansible/awx#8677]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

In the template syntax for custom webhook notifications, it is not currently possible to express

    foo.bar if foo and foo.bar are defined, otherwise "baz"

In ansible playbooks this can be done with the [default](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#providing-default-values) filter because undefined values get "chained" rather than raising exceptions. My example would look like this:

    {{ foo.bar | default('baz') }}

In AWX, the same expression would raise an UndefinedError if foo was undefined. This functionality was [implemented in ansible](https://github.com/ansible/ansible/commit/9c35f18dd6904345f65bad116876964a7a8816c9) with a custom class, but Jinja2 >= 2.11.x now includes a [ChainableUndefined](https://jinja.palletsprojects.com/en/2.11.x/api/#jinja2.ChainableUndefined) class that provides the same functionality.

This currently impacts the workaround proposed for #885

**Comment by kdelee** [comment]
Tests added downstream verify this change. thanks!
