### ISSUE TITLE
Installer Playbook Error

### ISSUE THREAD

**Issue by FloThinksPi** [ansible/awx#868]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Installer Playbook has error in release 1.0.2 and Master branch. 1.0.1 works fine.
This occured when trying to upgrade from AWX 1.0.1.X to 1.0.2.0

The install was aborted.

##### ENVIRONMENT
* AWX version: 1.0.1.X
* AWX install method: docker
* Ansible version:  2.1.x
* Operating System: RHEL 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Checkout 1.0.2 Tag or Master. Stop and delete all container, then run the installer.

##### EXPECTED RESULTS

AWX installs without error in Playbook

##### ACTUAL RESULTS

This (Syntax)Error?
```
RROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/root/awx/installer/check_vars/tasks/main.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- include_tasks: check_openshift.yml
  ^ here


The error appears to have been in '/root/awx/installer/check_vars/tasks/main.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- include_tasks: check_openshift.yml
  ^ here
```

**Comment by mkempster22** [comment]
This is because you are using an ansible version below the requirement of 2.4, If you can't upgrade to 2.4 then you can change the syntax of that file from 'include_tasks' to the old way (i think it was just 'include:')

Duplicate of #690 ?

**Comment by FloThinksPi** [comment]
@mkempster22 Thank you for your response, you are completely right.
As for RHEL7, the ansible package is now at 2.4.1.0 and with this version, all worked fine.
```
============================================================================================================================
 Package                       Arch                Version                     Repository                              Size
============================================================================================================================
Updating:
 ansible                       noarch              2.4.1.0-1.el7               rhel-7-server-extras-rpms              7.6 M
```
