### ISSUE TITLE
RFE: Make it possible for workflows to run in batches

### ISSUE THREAD

**Issue by xstasi** [ansible/awx#8681]
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY

A customer would like to run a workflow on a pool of machines splitting the run in batches, akin to the `serial:` feature of Ansible. 

Using `serial` itself though would mean that only a certain step of the workflow is batched up, while the requirement is for the whole workflow to complete on one batch before moving to the next one.

**Comment by wenottingham** [comment]
Given how inventory works in a workflow, and how different workflow steps could have entirely different inventories attached, I don't think this is a feasible thing to implement in the current way workflows work. Even if there was a way to do this, it would need to be entirely separate workflow runs unrelated to each other.

My suggestion would be if there is a desire to canary test workflows, is to use promptable limits and chain multiple workflow executions with different prompted limits.
