### ISSUE TITLE
Tower_Job_Template missing instance_groups

### ISSUE THREAD

**Issue by gdykeman** [ansible/awx#8687]
@AlanCoding @IPvSean 

##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Tower_job_template module does not include a field to define instance groups.

##### STEPS TO REPRODUCE

tower_job_template module does not include a parameter for setting instance_groups.  

##### EXPECTED RESULTS
tower_job_template:
  instance_groups: <instance_group_name>

##### ACTUAL RESULTS
Does not exist

**Comment by unlikelyzero** [comment]
@gdykeman which version

**Comment by gdykeman** [comment]
@unlikelyzero 
Latest in awx_collection
https://github.com/ansible/awx/blob/devel/awx_collection/plugins/modules/tower_job_template.py

**Comment by wenottingham** [comment]
-> #8604
