### ISSUE TITLE
[ui_next] Cannot sort Schedules list by Job Type

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8690]
##### ISSUE TYPE
 - Bug Report
 - Enhancement

##### SUMMARY
In the initial design of schedules, we wanted to allow the user to sort by type. https://github.com/ansible/awx/issues/5857
This currently is not implemented. Filing as a bughancement.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by AlexSCorey** [comment]
Sorting by type will probably not work here until the upstream api bug is fixed.
