### ISSUE TITLE
[ui_next] Cannot add Survey to Scheduled Jobs

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8692]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Surveys are not shown for Scheduled Jobs -- both WFJT and JT

##### ENVIRONMENT
* AWX version: 1e66a977c767fa3a7b5e9960af90afb6875d7015

##### STEPS TO REPRODUCE
1. Attempt to create a schedule with prompted values

##### ADDITIONAL INFORMATION
<img width="1364" alt="Screen Shot 2020-11-25 at 6 05 39 PM" src="https://user-images.githubusercontent.com/12446869/100290229-d99c9300-2f48-11eb-88cd-43b5cc51f7d5.png">

**Comment by mabashian** [comment]
This is being tracked here: https://github.com/ansible/awx/issues/7692
