### ISSUE TITLE
[RFE]: Allow workflows to have multliple, programmable, parallel starting points

### ISSUE THREAD

**Issue by xstasi** [ansible/awx#8694]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

A customer needs to run the same workflow on different parts of their infrastructure, which need to be determined programmatically. Specifically, their use case is patching their whole estate by using a patching workflow that behaves differently according to the group it's being run on.

They are now launching all the jobs separately, but this is very hard to track as each job gets lost in the sea of jobs. They would like to have a holistic view of all the workflow runs that are part of the same operation.

One possible idea is to have a workflow template accept some parameter with an array of inventory groups, duplicating the starting point for each of them.

**Comment by wenottingham** [comment]
Is the goal to just "run a workflow on multiple inventories"?

**Comment by xstasi** [comment]
That is part of the goal indeed, running the workflow on multiple inventories. That is already possible of course using separate job templates, but it does not really scale: when the possible inventories are in the hundreds it becomes unfeasible to maintain them. 

Even having a huge inventory and running the workflow multiple times through "limit" would be problematic: for one, hundreds of jobs of the same template running simultaneously are hard to keep track of, and secondarily, this would be even messier when workflows need to be split further for canary runs (see: #8681).

That is why having a unified entity (not necessarily the workflow itself, but maybe some sort of workflow-of-workflows?) would be useful.

**Comment by ffirg** [comment]
We are not looking to implement this feature, as in real practical situations it's likely to break a lot of workflows, which are designed to be run end-to-end for consistent, reliable and repeatable automation. You can achieve what this is asking for using workflows inside workflows today with some simple logical evaluations/assertions.
