### ISSUE TITLE
issue running the install playbook on fedora 26

### ISSUE THREAD

**Issue by aoyawale** [ansible/awx#87]
### Summary
While the running the install playbook, it fails because it cannot find docker-py.
`
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "api_version": null, 
            "archive_path": null, 
            "buildargs": null, 
            "cacert_path": null, 
            "cert_path": null, 
            "container_limits": null, 
            "debug": false, 
            "docker_host": null, 
            "dockerfile": "Dockerfile", 
            "filter_logger": false, 
            "force": false, 
            "http_timeout": null, 
            "key_path": null, 
            "load_path": null, 
            "name": "awx_web", 
            "nocache": "False", 
            "path": "/tmp/docker-image", 
            "pull": true, 
            "push": false, 
            "repository": null, 
            "rm": true, 
            "ssl_version": null, 
            "state": "present", 
            "tag": "1.0.0.273", 
            "timeout": null, 
            "tls": null, 
            "tls_hostname": null, 
            "tls_verify": null, 
            "use_tls": "no"
        }
    }, 
    "msg": "Failed to import docker-py - cannot import name DependencyWarning. Try `pip install docker-py`"
}
`

### Steps To Reproduce:
Install the required applications by following the installer.md and run the installer playbook on fedora 26.

### Expected Results:
it should find docker-py and continue the install

### Actual Results:
"msg": "Failed to import docker-py - cannot import name DependencyWarning. Try `pip install docker-py`"

**Comment by bcambl** [comment]
> Try `pip install docker-py`

**Comment by Zokormazo** [comment]
I had the same issue with docker-py on fedora.

Uninstall docker-py and install docker from pip

**Comment by matburt** [comment]
Looks like there's a solution, closing.
