### ISSUE TITLE
Need a better UI login redirect

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#8704]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The new UI gives error messages from the API fairly unedited. This is great in most cases, but when my login has expired and I need to login again, the API advice is taken out of context, and the UI should build something that correctly links to its own login.

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: N/A
* Ansible version:  N/A
* Operating System:
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Launch an inventory update

go get coffee and return 30 minutes later

go back and click the relaunch button

##### EXPECTED RESULTS

Prompted for my password because I have been logged out due to inactivity

##### ACTUAL RESULTS

Given this

![Screenshot from 2020-11-30 11-05-01](https://user-images.githubusercontent.com/1385596/100633706-66a26c00-32fc-11eb-92b7-8c35eabffe2f.png)

##### ADDITIONAL INFORMATION

Most of that information is correct, but I file this because the final sentence is not quite right:

> To establish a login session, visit /api/login/.

I guess you could go there, but it redirects you to the API browser at /api/, not the UI at `/#/`. The authentication still works, but I feel like users would expect something a little bit better than this.

**Comment by unlikelyzero** [comment]
@AlanCoding i think this would be solved by https://github.com/ansible/awx/issues/8272 , but at least we're handling the specifics of the behavior better than we did in the old ui https://github.com/ansible/awx/issues/3319

**Comment by AlanCoding** [comment]
> When user is automatically logged out for being idle, show a message on the logout page so they know what happened

I guess that does cover it, and I'll close this. The statement seems to take as an assumption that the timeout causes a redirect, but I'm not clear on what the "logout page" refers to.
