### ISSUE TITLE
Allow containers to use internal yum/dnf repos

### ISSUE THREAD

**Issue by gamethis** [ansible/awx#8705]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
due to security restraints I need to be able to use internal repos for the images that are built.
currently when the docker image is used it points external public repos.
I would like to see some variables added in to point the `baseurl`for each of the yum repos in centos8 container to point to my internal repositories. when building awx instance.

**Comment by wenottingham** [comment]
The baseurls in the repos inside the container come from CentOS itself; if you want to do this, you'd need to point at a different CentOS base image. We're not going to rewrite the yum repo files from CentOS itself.
