### ISSUE TITLE
The user is unable to remove the organization from the credentials form

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#8707]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Trying to edit a credential removing the organization and hit save looks like this information was not updated on the details tab and the edit form.

##### STEPS TO REPRODUCE

1. Create a new organization (fill in the organization field)
2. Edit this credential removing the organization and hit save

##### EXPECTED RESULTS
The organization field is unset on details and edit form

##### ACTUAL RESULTS

![cred1](https://user-images.githubusercontent.com/12464858/100647655-982c2f00-331e-11eb-9603-ad6208106865.gif)

**Comment by unlikelyzero** [comment]
@akus062381 please perform manual verification and check for testability

**Comment by akus062381** [comment]
Manually checked and verified that this is functional.
testability also verified
