### ISSUE TITLE
job_explanation and result_traceback are not shown for failed jobs

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#8709]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Inventory updates (and maybe other job types, have not checked) with "error" status are not displaying information in the UI that is expected to be shown.

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: N/A
* Ansible version:  N/A
* Operating System:
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Run an inventory update that produces a traceback in the task system... you could modify the code to raise an exception manually, which might be the easiest way to do this.

##### EXPECTED RESULTS

The old UI would show information from 2 important fields:

 - `job_explanation`
 - `result_traceback`

It selectively shows these when:

```json
    "status": "error",
```

##### ACTUAL RESULTS

Not enough detail:

![Screenshot from 2020-11-30 14-07-11](https://user-images.githubusercontent.com/1385596/100653168-fd2f5700-3315-11eb-82b9-c04506730f33.png)

##### ADDITIONAL INFORMATION

This is important for cases like license errors or when allocated host limit is exceeded (either system-wide or org-specific)

**Comment by unlikelyzero** [comment]
https://github.com/ansible/awx/pull/8726#issuecomment-772746083
