### ISSUE TITLE
No error is raised when editing a credential type that does require organization

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#8712]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

No error is raised when editing a credential which credential type does require an organization to be created.

##### ENVIRONMENT
* AWX version devel.
* AWX install method: docker

##### STEPS TO REPRODUCE

1. Create a credential of type `Ansible Tower`, and do not provide an Organization.
2. Patch the just created credential to change its type to `Ansible Galaxy/Automation Hub API Token`, do not provide an Organization.
3. No error is raised from the API.

##### EXPECTED RESULTS

* Error to be raised.

##### ACTUAL RESULTS

* Error is not raised.

##### ADDITIONAL INFORMATION

Validation was added to the UI side. See: https://github.com/ansible/awx/pull/8594#issuecomment-734985691

**Comment by wenottingham** [comment]
We should fix this by disallowing the switch of credential type on an existing credential.

**Comment by nixocio** [comment]
The fix suggested above was added. 
<img width="1456" alt="image" src="https://user-images.githubusercontent.com/9053044/135276840-5ea996fd-8881-424b-923d-08577682d41e.png">
