### ISSUE TITLE
postgresql db size very large and keeps growing

### ISSUE THREAD

**Issue by shen3lu4** [ansible/awx#8713]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Scheduled clean up job to remove jobs older than 20 days every week. And I can see older jobs being removed from the jobs webpage. However, the database doesn't seem to reduce in size. It is currently over 1.1TB and growing. We only have a handful of projects/templates configured in the system. What else could be taking the space?

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: Kubernetes
* Ansible version:  2.7.7
* Operating System: Linux
* Web Browser: Chrome

##### EXPECTED RESULTS

I expect the postgresql volume size to shrink after the cleanup but it doesn't. 

##### ACTUAL RESULTS

The postgresql volume kept growing.

**Comment by shanemcd** [comment]
Hello. AWX 3.0.1 came out nearly 2 years ago at this point. Please upgrade to a more recent version and see if it helps.

**Comment by shen3lu4** [comment]
@shanemcd Thanks yes that's our plan but was hoping to reduce the size of the volume before doing that.

In order to upgrade to the latest awx release from 3.0.1 there are many releases in between. We cannot find info about an upgrade path. Do you have any recommendation on which intermediate releases can be skipped? We used to follow the tower upgrade documentation but it looks like the awx version # has deviated from tower version # 

Thanks in advance!

**Comment by shanemcd** [comment]
The only recommendation I can provide is that you perform a backup beforehand.

In any case, this issue tracker is for bugs in AWX itself. If you need help beyond that, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
