### ISSUE TITLE
Cannot Install AWX with option of building your own image instead of dockerhub 

### ISSUE THREAD

**Issue by iamgp21** [ansible/awx#8714]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 14.0.0
* AWX install method:  docker on linux
* Ansible version:  2.9.10
* Operating System:  Oracle Linux
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

Modify the inventory files as per below :-  have removed/commented attribute :- dockerhub_base=ansible

[all:vars]

# Remove these lines if you want to run a local image build
# Otherwise the setup playbook will install the official Ansible images. Versions may
# be selected based on: latest, 1, 1.0, 1.0.0, 1.0.0.123
# by default the base will be used to search for ansible/awx

# Openshift Install
# Will need to set -e openshift_password=developer -e docker_registry_password=$(oc whoami -t)
#           or set -e openshift_token=TOKEN
# openshift_host=127.0.0.1:8443
# openshift_project=awx
# openshift_user=developer
# openshift_skip_tls_verify=False
# openshift_pg_emptydir=True

# Kubernetes Install
# kubernetes_context=test-cluster
# kubernetes_namespace=awx
# kubernetes_web_svc_type=NodePort
# Optional Kubernetes Variables
# pg_image_registry=docker.io
# pg_serviceaccount=awx
# pg_volume_capacity=5
# pg_persistence_storageClass=StorageClassName
# pg_persistence_existingclaim=postgres_pvc
# pg_cpu_limit=1000
# pg_mem_limit=2

# Kubernetes Ingress Configuration
# You can use the variables below to configure Kubernetes Ingress
# Set hostname
# kubernetes_ingress_hostname=awx.example.org
# Add annotations. The example below shows an annotation to be used with Traefik but other Ingress controllers are also supported
# kubernetes_ingress_annotations={'kubernetes.io/ingress.class': 'traefik', 'traefik.ingress.kubernetes.io/redirect-entry-point': 'https'}
# Specify a secret for TLS termination
# kubernetes_ingress_tls_secret=awx-cert

# Kubernetes and Openshift Install Resource Requests
# These are the request and limit values for a pod's container for task/web/redis/management.
# The total amount of requested resources for a pod is the sum of all
# resources requested by all containers in the pod
# A cpu_request of 1500 is 1.5 cores for the container to start out with.
# A cpu_limit defines the maximum cores that that container can reserve.
# A mem_request of 2 is for 2 gigabytes of memory for the container
# A mem_limit defines the maximum memory that that container can reserve.
# Default values for these entries can be found in ./roles/kubernetes/defaults/main.yml
# task_cpu_request=1500
# task_mem_request=2
# task_cpu_limit=2000
# task_mem_limit=4
# web_cpu_limit=1000
# web_mem_limit=2
# redis_cpu_limit=1000
# redis_mem_limit=3
# management_cpu_limit=2000
# management_mem_limit=2

# Common Docker parameters
awx_task_hostname=awx
awx_web_hostname=awxweb
postgres_data_dir=/u000/pgdocker
host_port=80
host_port_ssl=443
ssl_certificate=/u000/certs/rpc12639.corp.ncr.com.crt
# Optional key file
ssl_certificate_key=/u000/certs/rpc12639.corp.ncr.com.key
docker_compose_dir=/u000/awxcompose

# Required for Openshift when building the image on your own
# Optional for Openshift if using Dockerhub or another prebuilt registry
# Required for Docker Compose Install if building the image on your own
# Optional for Docker Compose Install if using Dockerhub or another prebuilt registry
# Define if you want the image pushed to a registry. The container definition will also use these images
# docker_registry=172.30.1.1:5000
# docker_registry_repository=awx
# docker_registry_username=developer

# Set pg_hostname if you have an external postgres server, otherwise
# a new postgres service will be created
#pg_hostname=rpc12637.corp.ncr.com
pg_username=awx
# pg_password should be random 10 character alphanumeric string, when postgresql is running on kubernetes
# NB: it's a limitation of the "official" postgres helm chart
pg_password=awxpass
pg_database=awx
pg_port=5432
#pg_sslmode=require

# The following variable is only required when using the provided
# containerized postgres deployment on OpenShift
# pg_admin_password=postgrespass

# Use a local distribution build container image for building the AWX package
# This is helpful if you don't want to bother installing the build-time dependencies as
# it is taken care of already.
# NOTE: IMPORTANT: If you are running a mininshift install, using this container might not work
#                  if you are using certain drivers like KVM where the source tree can't be mapped
#                  into the build container.
#                  Thus this setting must be set to False which will trigger a local build. To view the
#                  typical dependencies that you might need to install see:
#                  installer/image_build/files/Dockerfile.sdist
#use_container_for_build=true

# This will create or update a default admin (superuser) account in AWX, if not provided
# then these default values are used
admin_user=admin
admin_password=password

# Whether or not to create preload data for demonstration purposes
create_preload_data=True

# AWX Secret key
# It's *very* important that this stay the same between upgrades or you will lose the ability to decrypt
# your credentials
secret_key=awxsecret

# By default a broadcast websocket secret will be generated.
# If you would like to *rerun the playbook*, you need to set a unique password.
# Otherwise it would generate a new one every playbook run.
# broadcast_websocket_secret=

# Build AWX with official logos
# Requires cloning awx-logos repo as a sibling of this project.
# Review the trademark guidelines at https://github.com/ansible/awx-logos/blob/master/TRADEMARKS.md
#awx_official=true

# Proxy
#http_proxy=http://proxy:3128
#https_proxy=http://proxy:3128
#no_proxy=mycorp.org

# Container networking configuration
# Set the awx_task and awx_web containers' search domain(s)
#awx_container_search_domains=example.com,ansible.com
# Alternate DNS servers
#awx_alternate_dns_servers="10.1.2.3,10.2.3.4"

# AWX project data folder. If you need access to the location where AWX stores the projects
# it manages from the docker host, you can set this to turn it into a volume for the container.
project_data_dir=/u000/projects

# AWX custom virtual environment folder. Only usable for local install.
#custom_venv_dir=/opt/my-envs/

# CA Trust directory. If you need to provide custom CA certificates, supplying
# this variable causes this directory on the host to be bind mounted over
# /etc/pki/ca-trust in the awx_task and awx_web containers.
# If you are deploying on openshift or kubernetes, set the variable to /etc/pki/ca-trust instead,
# as the awx_web and awx_task containers will not run the `update-ca-trust` command.
#ca_trust_dir=/etc/pki/ca-trust/source/anchors

# Include /etc/nginx/awx_extra.conf
# Note the use of glob pattern for nginx
# which makes include "optional" - i.e. not fail
# if file is absent
#extra_nginx_include="/etc/nginx/awx_extra[.]conf"

# Docker compose explicit subnet. Set to avoid overlapping your existing LAN networks.
#docker_compose_subnet="172.17.0.1/16"
#
# Allow for different docker logging drivers
# By Default; the logger will be json-file, however you can override
# that by uncommenting the docker_logger below.
# Be aware that journald may rate limit your log messages if you choose it.
# See: https://docs.docker.com/config/containers/logging/configure/
# docker_logger=journald
#

# Add extra hosts to docker compose file. This might be necessary to
# sneak in servernames. For exmaple for DMZ self-signed CA certificates.
# Equivialent to using the --add-host parameter with "docker run".
#docker_compose_extra_hosts="otherserver.local:192.168.0.1,ldap-server.local:192.168.0.2"

##### EXPECTED RESULTS

Need to have awx installed with own build images instead of dokcerhub ones.

##### ACTUAL RESULTS

TASK [image_build : Stage sdist] ***************************************************************************************************************************************
task path: /u000/awx/installer/roles/image_build/tasks/main.yml:97
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: gp185132
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1606809998.84-32854-213549741070737 && echo ansible-tmp-1606809998.84-32854-213549741070737="` echo /root/.ansible/tmp/ansible-tmp-1606809998.84-32854-213549741070737 `" ) && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1606809998.84-32854-213549741070737/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/copy.py", line 464, in run
    source = self._find_needle('files', source)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 1198, in _find_needle
    return self._loader.path_dwim_relative_stack(path_stack, dirname, needle)
  File "/usr/lib/python2.7/site-packages/ansible/parsing/dataloader.py", line 327, in path_dwim_relative_stack
    raise AnsibleFileNotFound(file_name=source, paths=[to_native(p) for p in search])
AnsibleFileNotFound: Could not find or access '../dist/awx-14.0.0.tar.gz'
Searched in:
        /u000/awx/installer/roles/image_build/files/../dist/awx-14.0.0.tar.gz
        /u000/awx/installer/roles/image_build/../dist/awx-14.0.0.tar.gz
        /u000/awx/installer/roles/image_build/tasks/files/../dist/awx-14.0.0.tar.gz
        /u000/awx/installer/roles/image_build/tasks/../dist/awx-14.0.0.tar.gz
        /u000/awx/installer/files/../dist/awx-14.0.0.tar.gz
        /u000/awx/installer/../dist/awx-14.0.0.tar.gz on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "dest": "/tmp/docker-image/awx-14.0.0.tar.gz",
        "module_args": {
            "dest": "/tmp/docker-image/awx-14.0.0.tar.gz",
            "src": "../dist/awx-14.0.0.tar.gz"
        },
        "src": "../dist/awx-14.0.0.tar.gz"
    },
    "msg": "Could not find or access '../dist/awx-14.0.0.tar.gz'\nSearched in:\n\t/u000/awx/installer/roles/image_build/files/../dist/awx-14.0.0.tar.gz\n\t/u000/awx/installer/roles/image_build/../dist/awx-14.0.0.tar.gz\n\t/u000/awx/installer/roles/image_build/tasks/files/../dist/awx-14.0.0.tar.gz\n\t/u000/awx/installer/roles/image_build/tasks/../dist/awx-14.0.0.tar.gz\n\t/u000/awx/installer/files/../dist/awx-14.0.0.tar.gz\n\t/u000/awx/installer/../dist/awx-14.0.0.tar.gz on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"
}

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=13   changed=1    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0

Throwing error :- AnsibleFileNotFound: Could not find or access '../dist/awx-14.0.0.tar.gz'

**Comment by iamgp21** [comment]
Hi Could anyone help here ?

**Comment by shanemcd** [comment]
In the future it would be helpful if you took the time to properly format your issue. In any case, this issue tracker if for bugs in AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
