### ISSUE TITLE
Why Cloudforms inventory source disappear in the newest releases?

### ISSUE THREAD

**Issue by riccardodorh280** [ansible/awx#8720]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

 Hello Guys,
i currently have (and i really appreciate) an installation of AWX version 3.
Now i moved to AWX 14.1 and after the installation process i noticed that there is no Cloudforms Inventory Source and this is a big problem for my organization because we use cloudforms to manage lots of ovirt installation and to expose playbook through buttons on vm. So basically when we want to do something we push a button on cloudforms and it call awx passing the vm name as a limit of the job template. Now that i see that Cloudforms Inventory Source has dissapear how can we reintroduce them? Why it disappear? Is there a possibility to solve this huge problem?

Thank you
##### ENVIRONMENT
* AWX version: 14.1
* AWX install method:  docker on linuxr
* Ansible version:  2.9
* Operating System: rhel7
* Web Browser:

##### STEPS TO REPRODUCE

you can see the problem if you go to Inventory > Source and try to search Cloudforms 

##### EXPECTED RESULTS

I expected to see cloudforms as i saw on older versions

##### ACTUAL RESULTS

Cloudforms Source disappear and i basically not able to perform jobs on vm and infrastructure that i manage with cloudforms.

**Comment by ryanpetrello** [comment]
Hey @riccardodorh280,

In recent versions of AWX, we've moved to syncing inventory via [Ansible inventory plugins](https://docs.ansible.com/ansible/latest/plugins/inventory.html) from [collections](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html), and removed support for legacy inventory scripts.

Cloudforms does not have a community-supported plugin implementation, so we deprecated and removed support for it over several releases of AWX.

**Comment by haloss1** [comment]
@riccardodorh280 I've developed a Ansible Plugin for getting ManageIQ (CloudForms) hosts as Ansible inventory items:
https://gitlab.com/Haloss1/manageiq_inventory
