### ISSUE TITLE
Projects start SCM update even when they should not.

### ISSUE THREAD

**Issue by valerio-gr** [ansible/awx#873]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - awx_task(?)

##### SUMMARY
A template based on a project with all the SCM UPDATE OPTIONS unflagged still triggers an SCM update when launched.

##### ENVIRONMENT
* AWX version: 1.0.1.8

##### STEPS TO REPRODUCE
Create a project based on git scm. Leave the SCM UPDATE OPTIONS unflagged.
Create a template based on the project that runs the following playbook:

---
# TEST PLAYBOOK
- name: TEST SCM UPDATE OPTIONS BUG
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
   - name: Create a local file
     file:
      state: touch
      path: "test.txt"

   - name: Stage the file
     shell: |
       git add -A

##### EXPECTED RESULTS
The template can be run any number of time without any failure

##### ACTUAL RESULTS
The template runs fine the first time but the second time it breaks with error: SCM Update failed
The error happens because locally, there are staged and uncommited changes but the SCM Update should not have been triggered to begin with because the SCM UPDATE OPTIONS were left unflagged.

**Comment by wenottingham** [comment]
A checkout is always done before job runs; this is intentional behavior. (On cluster nodes, the checkout may not be present before the job runs.)
