### ISSUE TITLE
awx.awx.tower_settings does not return expected changes when running in check mode with diff

### ISSUE THREAD

**Issue by rozgonik** [ansible/awx#8731]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Running the module with check and diff mode simultaneously does not return the list of expected changes. It only returns that the module will change some unknown thing (by setting the `changed` variable true).
As check and diff mode is mainly used for, erm.. checking, this makes it hard to actually check the correct invocation of the module, especially when multiple settings are set.

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.10
* Operating System: Debian 10
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Task extract:
```
- name: Set LDAP
  tower_settings:
    settings:
      AUTH_LDAP_SERVER_URI: "ldap://ldap.example.com:389"
      AUTH_LDAP_BIND_DN: CN=user,DC=example,DC=com
      AUTH_LDAP_BIND_PASSWORD: password
      AUTH_LDAP_START_TLS: true
```
Make sure that some of these settings have a different value in AWX.
Run the task with and without check&diff mode.

##### EXPECTED RESULTS
Expected at least some insight why the module reports changed status when running with check&diff mode.

For eg if AWX server's AUTH_LDAP_SERVER_URI is `ldap://nonexistent.com:389`, then running check&diff mode could produce similar output when running in normal mode:
```
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "settings": {
                "AUTH_LDAP_SERVER_URI": "ldap://ldap.example.com:389",
                "AUTH_LDAP_BIND_DN": "CN=user,DC=example,DC=com",
                "AUTH_LDAP_BIND_PASSWORD": "password",
                "AUTH_LDAP_START_TLS": true
            },
            <...other module args ...>
        }
    },
    "old_values": {
        "AUTH_LDAP_SERVER_URI": "ldap://nonexistent.com:389"
    },
    "values": {
        "AUTH_LDAP_SERVER_URI": "ldap://ldap.example.com:389"
    }
}
```

##### ACTUAL RESULTS
Running the module with check&diff mode produces less usable output regarding the variables to be changed:
```
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "settings": {
                "AUTH_LDAP_SERVER_URI": "ldap://ldap.example.com:389",
                "AUTH_LDAP_BIND_DN": "CN=user,DC=example,DC=com",
                "AUTH_LDAP_BIND_PASSWORD": "password",
                "AUTH_LDAP_START_TLS": true
            },
            <...other module args ...>
        }
}
```
##### ADDITIONAL INFORMATION

As i see the main reason behind such behaviour is because a [new json_response dict is created](https://github.com/ansible/awx/blob/29926ba5d99b760b32de35e07c211fd3e7691c8d/awx_collection/plugins/modules/tower_settings.py#L136) in the module's code, but the [check_mode exit point](https://github.com/ansible/awx/blob/29926ba5d99b760b32de35e07c211fd3e7691c8d/awx_collection/plugins/module_utils/tower_api.py#L85) uses its own `json_output` dict.

Edit:
Completely forgot about diff mode, but ofc thats where i expect to see the detailed changes.

**Comment by sean-m-sullivan** [comment]
Should this be added to other modules as well, and should we add a diff/check mode integration test for the collection.
