### ISSUE TITLE
Porting the docker-compose build on ppc64le

### ISSUE THREAD

**Issue by sanjaymsh** [ansible/awx#8739]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

I am porting awx build on ppc64le and using centos8-ppc64le. So during building it on ppc64le, i am observing issues like below : 
"
/venv/awx/bin/pip uninstall --yes -r requirements/requirements_tower_uninstall.txt
make: /venv/awx/bin/pip: Command not found
make: *** [Makefile:206: requirements_awx] Error 127
Error: error building at STEP "RUN cd /tmp && make requirements_awx requirements_ansible_py3": error while running runtime: exit status 2
make: *** [Makefile:684: docker-compose-build] Error 125
"
##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker :: docker on linux
* Ansible version:  2.9.14
* Operating System:CentOS-8 ( ppc64le )
* Web Browser:Chrome

##### STEPS TO REPRODUCE

1)  make docker-compose-build
##### EXPECTED RESULTS

It should be successfully build the docker-compose.
##### ACTUAL RESULTS
Error: make: /venv/awx/bin/pip: Command not found

Its not finding the 'pip' to execute the command. So we need to provide the pip in VENV. I tested it locally in my system. and it passed successfully. 
##### ADDITIONAL INFORMATION
1) I got this kind of error "make: /venv/awx/bin/pip: Command not found"  at so many places in Makefile. And i use the same fix. And it was fixed. 
2) Similarly, i found that some of the versions of packages/libs in requirement*.txt are not supporting for ppc64le. So i upgraded it locally and tested. That one also worked.

Please look into this and confirm me on this. Shall i go ahead and raise a PR for the same?

Thanks !!

**Comment by sanjaymsh** [comment]
For more detailed info on it, tagging @seth-priya.

Thanks !!

**Comment by wenottingham** [comment]
Hi -

Please see https://groups.google.com/g/awx-project/c/47MjWSUQaOc/m/1-Jh0fy3AgAJ. The docker-compose installation method is going away in the future, and so we won't be adding new changes for that specifically.

For the image build, the very first task in the docker file installs python3-pip. Maybe that package for your OS is broken?
