### ISSUE TITLE
Cleanup related to execution-environments

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#8740]
This is purely for development purposes and tracks with the open PR:

https://github.com/ansible/awx/pull/8030

Relevant functionality will be satisfied by new systems, but removal of the old systems may be delayed until later in the development of the PR, or maybe after merge.

 - [x] Isolated jobs should be removed, this includes the `controller` relationship, several python modules, several supporting playbooks, lots of installer logic, property `is_controller`, and probably more. This is replaced by receptor.
   - [x] Delete the `make docker-compose-isolated` target, any new execution plane testing will probably be ground-up
 - [x] Custom venv migration solution tracked in https://github.com/ansible/awx/issues/7062
 - [x] Custom virtual environments should be removed, this entails a field shared by several models, as well as task logic like `add_ansible_venv`, some logic in the models, settings like `ANSIBLE_VENV_PATH`, and so on.
   - ~this may require a migration tool to map old custom venvs to EE image URLs~ (wontfix)
   - [x] remove `custom_virtualenvs` from `/api/v2/config/`
 - [x] Vendoring of collections gets removed, see the setting `AWX_ANSIBLE_COLLECTIONS_PATHS`. Anything that installed to this location gets removed, anything that references that gets removed. The `requirements/collection_requirements.yml` file stays, it is used by the execution environment definition.
   - We may remove the install of Ansible itself (it is a global install) from the web/task container images
   - [x] Ansible version is reported at `/api/v2/config/` endpoint, this is removed
 - [x] The default Ansible virtual environment, sourced from `requirements/requirements_ansible.txt` gets removed. I made an attempt somewhat at https://github.com/ansible/awx/pull/7971, but there's much more to do
 - [x] Removal of bubblewrap as a dependency, and all python logic concerned with it
   - [x] `build_params_process_isolation`, `should_use_proot`, etc.
 - Custom inventory scripts model will be removed, not tracked here, see https://github.com/ansible/awx/issues/7775

More items may still be added to this list.

**Comment by shanemcd** [comment]
- [x] Stop installing ansible from devel
- [x] Remove dependency on community.general from runtime and installer
- [x] Remove usage of Ansible from launch scripts
- [x] Remove Ansible from control plane entirely

**Comment by AlanCoding** [comment]
I want to pitch the idea that, for initial merge, we remove the serializer fields (just a few lines). That way, we can correctly adjust integration tests, the UI, and the AWX collection. Then later on we can do the actual migrations and installer work.

**Comment by AlanCoding** [comment]
- [ ] Remove `AWX_PRIVATE_DATA_DIR` from inventory update job environment variables. This was only used internally, mainly by `awx-manage import_inventory` historically (which is irrelevant now), but we still use it internally as a hack in task logic and tests, so these must be refactored

**Comment by AlanCoding** [comment]
Fallout from:

https://github.com/ansible/awx/pull/8598

 - [x] All of the `build_cwd` methods in `tasks.py` should be deleted, no longer used

**Comment by AlanCoding** [comment]
We should no longer need `libcurl-devel`, or any other libcurl anywhere, because it's for pycurl, which is in the EE

**Comment by jbradberry** [comment]
@AlanCoding note, we should _not_ remove the `custom_virtualenv` fields for 4.0.  We want to be able to detect the need for users to transition their templates away from using custom venvs.  This issue was raised in today's Support/Engineering Sync meeting.

**Comment by AlanCoding** [comment]
That was written before we had an outline of how the migration solution was going to work. My speculative picture was that someone would write a migration tool, which would run to migrate the fields, and then delete the custom venv fields. I don't have a link for the specific form of that solution right now, but discussions have been to keep the field for the initial release. @rebeccahhh is the authority on that

**Comment by rebeccahhh** [comment]
yes we're keeping them. @shanemcd and I discussed this yesterday as well, we want to keep the custom venvs for 4.0 and given support agrees I think it's decided.

**Comment by AlanCoding** [comment]
I did a once-over of the things in this issue, and the mentions of `custom_virtualenv` still look valid.

We are keeping the fields, but purely for informative purposes. The AWX code should not retain any of the logic to use them. We shouldn't report the available paths in the config endpoint. We shouldn't leave them as editable fields, except to delete them. We shouldn't keep any methods to add the venv to the job environment, or get the Ansible version from it, etc.

And of course the field's help text should be updated to note that it's _non-functional_ and will be removed.

**Comment by ryanpetrello** [comment]
@shanemcd @rebeccahhh I looked at the checklist items above, and I *think* we've either addressed, or *are* addressing everything in this list (as part of planned work in other filed tickets).

Should we close this?

**Comment by AlanCoding** [comment]
I can still search and see settings like `ANSIBLE_VENV_PATH` and `AWX_ANSIBLE_COLLECTIONS_PATHS` in the code. The existence of these settings is nonsensical with how AWX functions now.

I would like to keep this open until I can get a gut check that we have deleted obviously dead code.

My focus here is not feature tracking, but keeping up with things that we didn't delete (but plan to) when one of the features was merged.

**Comment by shanemcd** [comment]
I think we can close this now.

**Comment by AlanCoding** [comment]
Another one https://github.com/ansible/awx/pull/10359

**Comment by AlanCoding** [comment]
What I said about `AWX_PRIVATE_DATA_DIR` is the only semi-valid point remaining.

But then again, some docs are super wrong too.
