### ISSUE TITLE
Dynamic AWS inventory source overwrite existing variables when host already exist

### ISSUE THREAD

**Issue by anthoc** [ansible/awx#8741]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

We are using multiple inventory source for the same inventory and for same hosts.
Some variable are from a dynamic AWS source (like infrastructure information)
Some are from a yml file pulled on a gitlab server (custom variables)
Some are declared manually inside the variables field of the host in the AWX dashboard.

We configured each source with "overwrite" checked, and "overwrite variables" unchecked

When we are running an inventory sync from the gitlab source, the variables added from aws sync and manually added are still there when the sync is done.

When we are running an inventory sync from the AWS source, only the AWS variables are there after the sync, all the variables obtained from gitlab sync and manually added are removed. 

And the group issued from gitlab source are gone too.

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker
* Ansible version:  2.9.14
* Operating System: Debian 10
* Web Browser: Google Chrome 87.0.4280.88

##### STEPS TO REPRODUCE

- Add an AWS source in an inventory with "overwrite checked" and "overwrite variables" unchecked
- Add a gitlab source in the same inventory with "overwrite checked" and "overwrite variables" unchecked
- Sync the gitlab source => the host is created and gitlab variables and groups are added
- Sync the AWS source => gitlab variables and groups are removed, AWS variables and groups are added
- Sync the gitlab source => gitlab variables and groups are added and AWS variables and groups are still there

##### EXPECTED RESULTS

I am not sure, but I expected the same behaviour from both sources (aws and gitlab).
From what I understood, with this configuration variables issued from different sources are supposed to coexist when the host have the same name. 

##### ACTUAL RESULTS

Existing variables from other sources are always removed by AWS source (maybe the host is completely recreated)

**Comment by anthoc** [comment]
Actually I checked, and even if the host have the same name, AWS inventory source always completely recreate the host (the ID is different) when there are variables manually added or from a different source, whereas gitlab source just append the variables to the existing host, when we trigger the sync from AWS.

**Comment by anthoc** [comment]
I enabled the DEBUG mode in the option of the AWS source and here is what I saw : 

```
14.483 DEBUG Finished loading from source: /tmp/awx_730_09rh8iqc/aws_ec2.yml
14.483 INFO  Processing JSON output...
14.483 DEBUG Loaded group: all
14.483 DEBUG Loaded group: aws_ec2
14.484 DEBUG Adding child group aws_ec2 to parent all
14.484 DEBUG Loaded group: prod
14.484 DEBUG Adding child group prod to parent all
14.484 DEBUG Loaded host: webserver1
14.484 DEBUG Adding host webserver1 to group aws_ec2
14.484 DEBUG Adding child group aws_ec2 to parent all
14.484 DEBUG Adding host webserver1 to group prod
14.484 DEBUG Adding child group prod to parent all
14.485 INFO  Loaded 2 groups, 1 hosts
14.513 WARNING  Host "webserver1" has no "ec2_id" variable(s)
14.805 DEBUG Deleted host "webserver1"
15.098 DEBUG Inventory variables unmodified
15.108 DEBUG Group "aws_ec2" variables unmodified
15.114 DEBUG Group "prod" variables unmodified
15.141 DEBUG Host "webserver1" added
15.199 DEBUG Host "webserver1" added to group "aws_ec2"
15.224 DEBUG Host "webserver1" added to group "prod"
```


So i added the following to my source variables : 

```
compose:
  ec2_id: instance_id
```

And it is working now but I cannot figure out why such a thing is necessary.

**Comment by wenottingham** [comment]
cc @AlanCoding 

What I think is happening here is that our tracking of when an instance is 'new' versus 'updated' is based on certain variables (in the ec2 case, ec2_id). 

For sources where that variable has to be done via compose, and where we don't have a default config, this causes misbehavior.

Or, should we flip the default EC2_INSTANCE_ID_VAR from `ec2_id` to `instance_id`?

**Comment by wenottingham** [comment]
This is fixed with https://github.com/ansible/awx/pull/8908, and should be in the next AWX release.

**Comment by elyezer** [comment]
I was able to verify this by doing the following:

1. Created an inventory and an EC2 inventory source with overwrite option checked (no source vars)
2. Synced the inventory source
3. Synced again and made sure hosts were not removed and added by watching the output and checking that hosts with a given name was added with another ID

See below a sample trimmed output:

```
   14.224 DEBUG    Host "host1.us-west-1.compute.internal" variables unmodified
   14.225 DEBUG    Host "host2.us-west-1.compute.internal" variables unmodified
   14.225 DEBUG    Host "host3.us-west-1.compute.internal" variables unmodified
   14.258 DEBUG    Host "host1.compute-1.amazonaws.com" already in group "aws_ec2"
   14.258 DEBUG    Host "host2.compute-1.amazonaws.com" already in group "aws_ec2"
   14.258 DEBUG    Host "host3.compute-1.amazonaws.com" already in group "aws_ec2"
```
