### ISSUE TITLE
Surveys break upgrading from .289 to .301

### ISSUE THREAD

**Issue by mkempster22** [ansible/awx#875]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI / API ?

##### SUMMARY
After upgrading from 1.0.2.289 to .301 trying to launch any job with a survey or edit the survey receives an error: "Failed to get job template details. GET returned status: undefined"

Possible relation to #704 

##### ENVIRONMENT
* AWX version: 1.0.2.301
* AWX install method: docker on linux
* Ansible version:  2.4.0/2.4.2
* Operating System: RHEL 7
* Web Browser: Chrome & IE

##### STEPS TO REPRODUCE
Upgrade AWX to .301 Existing surveys will now be broken. Surveys have been created on versions .289 and below

##### EXPECTED RESULTS

Survey should launch or be editable as normal

##### ACTUAL RESULTS

"Failed to get job template details. GET returned status: undefined"

##### ADDITIONAL INFORMATION

I have tried this a few different times by recovering to a .289 backup. Also note that if you launch a workflow with a node that has a broken survey in it it will get stuck in running mode with no extra info and won't be able to be removed via GUI or API or any other means

**Comment by cwegener** [comment]
I just noticed some problems with adding new surveys to job templates.

Adding new surveys to job templates doesn't appear to work.

**Comment by mkempster22** [comment]
Tested on:

.301
.303
.307
.315
.322

Same issues with Job templates and the work flow editor not launching ( #891 )

**Comment by mkempster22** [comment]
Been looking into all the issues getting similar issues. Looks like there were some big changes to .300+ (API related) that has broken a lot of functionality around the WebUI such as launching jobs with any sort of prompts, jobs getting stuck at pending and the workflow editor not launching.

**Comment by shortsteps** [comment]
I guess #891 and #894 are related, I experience the same on 1.0.2.303

**Comment by mkempster22** [comment]
Same issue on .322

**Comment by quenck** [comment]
The same on my Box:

**ENVIRONMENT**

- AWX version: AWX 1.0.2.322
- AWX install method: docker on linux
- Ansible version: 2.4.2.0
- Operating System: Debian 9
- Web Browser: Chrome

**Comment by ewithak** [comment]
Looks like it's finally working in 1.0.2.327! Workflow editing is also working

**Comment by quenck** [comment]
Confirmed, working on 1.0.2.327
