### ISSUE TITLE
LDAP Settings for a FreeIPA (iDM) Backend

### ISSUE THREAD

**Issue by michaelsmoody** [ansible/awx#876]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME

- Authentication

##### SUMMARY
I felt that this information might be helpful for others attempting this, so here are the relevant settings for LDAP for a FreeIPA backend (so far, I'll update if anything else changes). Note that {{ }} mean you need to substitute for your details.

##### ENVIRONMENT
* AWX version: 1.0.2
* AWX install method: docker on linux
* Ansible version:  2.4.x
* Operating System:
* Web Browser:

LDAP Server URI (I use multiple, for resiliency):
ldaps://{{serverip1}}:636 ldaps://{{serverip2}}:636 ldaps://{{serverip3}}:636

LDAP BIND DN (created a bind account with ldif)
uid=awx-bind,cn=sysaccounts,cn=etc,dc=example,dc=com

LDAP BIND PASSWORD:
{{yourbindaccountpassword}}

LDAP USER DN TEMPLATE:
uid=%(user)s,cn=users,cn=accounts,dc=example,dc=com

LDAP GROUP TYPE:
NestedMemberDNGroupType

LDAP GROUP SEARCH:
[
 "cn=groups,cn=accounts,dc=example,dc=com",
 "SCOPE_SUBTREE",
 "(objectClass=groupOfNames)"
]

LDAP USER ATTRIBUTE MAP:
{
 "first_name": "givenName",
 "last_name": "sn",
 "email": "mail"
}

LDAP USER FLAGS BY GROUP:
{
 "is_superuser": "cn={{superusergroupname}},cn=groups,cn=accounts,dc=example,dc=com"
}

LDAP ORGANIZATION MAP:
{
 "{{yourorganizationname}}": {
  "admins": "cn={{admingroupname}},cn=groups,cn=accounts,dc=example,dc=com",
  "remove_admins": false
 }
}

**Comment by ewithak** [comment]
Thanks for this! I was able to use it and get freeipa authentication working in AWX. 
I also added a user account search option as I use it for all my other freeipa authenticated systems:

[
 "cn=groups,dc=example,dc=com",
 "SCOPE_SUBTREE",
 "(uid=%(user)s)"
]

**Comment by matburt** [comment]
While some nice information it might be helpful if it were added in the docs/ section or in the installer help section as a PR rather than in an issue.

**Comment by perkooo** [comment]
Thanks for help, useful post that also helped me for setting up LDAP in AWX with FreeIPA !

**Comment by jeffcpullen** [comment]
Fantastic write up, this helped a ton.
