### ISSUE TITLE
[ui_next] Remove User from Team's list

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8767]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The Team's list shows a list of users under 'Access'. We should allow users to be removed from a Team in the same way that they're removed from an Organization

**Comment by mabashian** [comment]
Users can be removed from a team like so:

![remove_user_team](https://user-images.githubusercontent.com/9889020/106808019-d94f0100-6637-11eb-908b-8b2d0a3ac1d4.gif)

so I don't think this is an issue anymore?

**Comment by mabashian** [comment]
cc @unlikelyzero i'd definitely consider this feature parity so bumping to high but let me know if I'm misunderstanding the reproducing steps because i think this can be retested/maybe closed.

**Comment by unlikelyzero** [comment]
@mabashian let's sync on this when you have a chance

**Comment by akus062381** [comment]
https://github.com/ansible/tower-qa/blob/6cccd957dbc744dd7a13ab9a12728eb959fecf11/ui-tests/awx-pf-tests/cypress/integration/teams/team-operations.spec.js#L52

We have coverage.
