### ISSUE TITLE
[ui_next] Users/n/tokens page is missing tabs

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8772]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Users/n/tokens page is missing tabs

##### ENVIRONMENT
* AWX version: 12/7/20

##### STEPS TO REPRODUCE
1. Navigate to Users/n/tokens

##### EXPECTED RESULTS
Other tabs like details

##### ACTUAL RESULTS
No tabs

##### ADDITIONAL INFORMATION

<img width="1646" alt="Screen Shot 2020-12-07 at 10 11 33 AM" src="https://user-images.githubusercontent.com/12446869/101368154-d1abef80-3874-11eb-974c-ecf6ea652549.png">

**Comment by nixocio** [comment]
This one is fixed.
