### ISSUE TITLE
UI shows "Invalid Date" for job that is launched and "Running"

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#8784]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

`FINISHED` time says `Invalid Date` on job that says it is `Running`

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Launch job that takes a while to get started, like a job on isolated node

##### ADDITIONAL INFORMATION

![Screenshot from 2020-12-07 19-16-29](https://user-images.githubusercontent.com/29239279/101420775-e8783380-38c0-11eb-9772-ec9b9bb36425.png)

**Comment by mabashian** [comment]
We don't show the finished field while it's running anymore so I don't think this is an issue.

<img width="1399" alt="Screen Shot 2021-02-03 at 3 47 38 PM" src="https://user-images.githubusercontent.com/9889020/106807630-5af25f00-6637-11eb-83b4-a2db06939d15.png">

**Comment by unlikelyzero** [comment]
No unit test added.

Need to add functional tests for this test

**Comment by one-t** [comment]
> We don't show the finished field while it's running anymore so I don't think this is an issue.
> 
> <img alt="Screen Shot 2021-02-03 at 3 47 38 PM" width="1399" src="https://user-images.githubusercontent.com/9889020/106807630-5af25f00-6637-11eb-83b4-a2db06939d15.png">

This is correct, I've verified we don't show this field on currently running jobs.
