### ISSUE TITLE
Collections are not cached 

### ISSUE THREAD

**Issue by 0xbentang** [ansible/awx#8785]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Collections are re-downloaded whenever a job runs. The document mentions `Roles and collections are locally cached for performance reasons, and you will need to select Update Revision on Launch in the project SCM Update Options to ensure this:`

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.14
* Operating System: Ubuntu 18.04
* Web Browser: Firefox

##### STEPS TO REPRODUCE

1. I have a Git project, with a file in `collections/requirements.yml`

```
collections:
  - name: community.general
    version: 1.2.0
    source: https://galaxy.ansible.com
```

my `ansible.cfg` contains the following line

```
[defaults]
roles_path = roles/
collections_paths = collections/
```

2. On AWX, create the project and enable UPDATE REVISION ON LAUNCH
3. Create a template with a job in that project
4. Execute the template for the first time, collections will be downloaded
5. Execute the template again

##### EXPECTED RESULTS

5. Execute the template again -> it should use the the cached collection, without downloading again

##### ACTUAL RESULTS

5. Execute the template again -> it re-downloaded the collection

##### ADDITIONAL INFORMATION

N/A

**Comment by wenottingham** [comment]
The docs specifically say: "to ensure that the upstream role is re-downloaded before each job run".

In other words, you set update on launch to ensure you get the behavior you note.
