### ISSUE TITLE
Could not set source_variable when user tower plugin

### ISSUE THREAD

**Issue by dolgovas** [ansible/awx#8786]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
when add source inventory with tower_plugin it wan't work, because source_variable null, and input for it want show
##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.14
* Operating System: macOs
* Web Browser: Firefox

##### STEPS TO REPRODUCE

add source with tower plugin

##### EXPECTED RESULTS

i must choose from wich inventory i want get hosts

##### ACTUAL RESULTS

error when sync source

**Comment by dolgovas** [comment]
![изображение](https://user-images.githubusercontent.com/43605609/101468605-b4e6e900-3954-11eb-807d-d68474672a55.png)
![изображение](https://user-images.githubusercontent.com/43605609/101468713-d6e06b80-3954-11eb-88b5-d93c296a1356.png)

**Comment by wenottingham** [comment]
What does your configuration look like?

**Comment by dolgovas** [comment]
![изображение](https://user-images.githubusercontent.com/43605609/101596065-79f0be00-3a05-11eb-940f-f6d94c1ffe95.png)

**Comment by wenottingham** [comment]
This was fixed in https://github.com/ansible/awx/commit/0fbc02864e5fb1a21c7ce37869d0becf0f40c576, which is post-15.0.1. It should be fixed in the next release.
