### ISSUE TITLE
[ui_next] SCM Branch override is totally borked for JT, WFJT, and WFViz Node Add/Edit forms

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8788]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When enabling SCM Branch override, the JT Add/Edit and WFViz Node Add/Edit forms. This seems to be broken across the application.

##### ENVIRONMENT
* AWX version: be08e0ce695dc2d6b2b260b93dc23939ce4fcd6f

##### STEPS TO REPRODUCE
JT Add/Edit
1. Add SCM Branch override to an existing project.
2. Save and Sync
3. Add or Edit a JT Form sourcing that project.
No option to provide SCM Branch

WorkflowViz Node Add/Edit forms
1. Add SCM Branch override to an existing project.
2. Save and Sync
3. Add a JT to that project
4. Open Workflow Viz for a Workflow.
5. Add JT from step 3 to Workflow.
Note: cannot Save to close wizard

**Comment by mabashian** [comment]
@tiagodread reported some broken validation behavior in the WF node prompt wizard involving this bug.  To whoever fixes this: please also look at the launch/wf prompt wizards and make sure that validation is running correctly and errors are displayed correctly under the field.

**Comment by mabashian** [comment]
This is going to be partially blocked until https://github.com/ansible/awx/pull/8399 merges

**Comment by unlikelyzero** [comment]
retest https://github.com/ansible/awx/issues/7914

**Comment by hjkatz** [comment]
I'm not sure if this is related or if it should be reported as a new issue, however, when editing a template for a Project that has SCM branch override enabled, sometimes the SCM branch override input is missing.

Expected UI:
![image](https://user-images.githubusercontent.com/2234516/103798946-6478af00-5018-11eb-851b-cc73368edebb.png)

When I select a playbook:
![image](https://user-images.githubusercontent.com/2234516/103798973-6e9aad80-5018-11eb-9e3e-962c2a50aae9.png)

Then I save and revisit the edit for this template:
![image](https://user-images.githubusercontent.com/2234516/103799012-7d816000-5018-11eb-8150-1842ca47c525.png)

See how the SCM branch override input is missing?

When I click on the 🔍  for Project, then reselect the selected project:
![image](https://user-images.githubusercontent.com/2234516/103799068-938f2080-5018-11eb-9cf8-70015d468477.png)

Then the playbook field is removed, but the SCM branch override is still missing:
![image](https://user-images.githubusercontent.com/2234516/103799106-a144a600-5018-11eb-81e5-097cc1810dd0.png)

Finally, if I repeat clicking on the 🔍  for Project and reselect the selected project, then the SCM branch field will appear (and the playbook field will be empty):
![image](https://user-images.githubusercontent.com/2234516/103799177-bc171a80-5018-11eb-9afd-4cb7018bfe70.png)

I think there is something funky going on with the interaction between fields Project, Playbook, and Source Control Branch.

**Comment by hjkatz** [comment]
What's the status of this issue?

**Comment by nixocio** [comment]
hey @one-t, I will go ahead and close this one since you already verified this one.
