### ISSUE TITLE
Add extra text to the workflow inventory step when it's promptable

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#8789]
##### SUMMARY

This is a follow-up on https://github.com/ansible/awx/issues/5913 specifically for:

> Some extra text needs to be added to the inventory step when it's promptable. The global WFJT Inventory will trump and node level inventory that's provided. We want to communicate that to the user. This is probably only necessary if ask_inventory_on_launch is set to true on the outer workflow.

See also: https://github.com/ansible/awx/pull/8399#issuecomment-740205736

**Comment by mabashian** [comment]
Blocked until https://github.com/ansible/awx/pull/8399 merges

**Comment by akus062381** [comment]
a stub needs to be added

**Comment by mabashian** [comment]
<img width="845" alt="Screen Shot 2021-02-24 at 1 12 05 PM" src="https://user-images.githubusercontent.com/9889020/109045749-f65c7a00-76a1-11eb-8f48-1e73b5f60e04.png">

**Comment by tiagodread** [comment]
PR merged and tests in place.
