### ISSUE TITLE
installer inventory should allow 'cmd line'/'run time' over-rides for its playbook default values

### ISSUE THREAD

**Issue by TheBigBear** [ansible/awx#879]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - Installer

##### SUMMARY
the hard coded values for secrets, passwords, ports, directories etc should only use defaults if nothing else has been passed as an argument

##### ENVIRONMENT
* AWX version: 1.0.2
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.4.2

##### ADDITIONAL INFORMATION
the following vars should be allowing and override

dockerhub_base=ansible
dockerhub_version=latest
awx_secret_key=awxsecret
openshift_host=127.0.0.1:8443
awx_openshift_project=awx
openshift_user=developer
awx_node_port=30083
postgres_data_dir=/tmp/pgdocker
host_port=80
docker_registry=172.30.1.1:5000
docker_registry_repository=awx
docker_registry_username=developer
docker_remove_local_images=False
pg_hostname=postgresql
pg_username=awx
pg_password=awxpass
pg_database=awx
pg_port=5432
use_container_for_build=true
awx_official=false
http_proxy=http://proxy:3128
https_proxy=http://proxy:3128
no_proxy=mycorp.org
awx_container_search_domains=example.com,ansible.com

**Comment by matburt** [comment]
do extra vars not always take precedence over those defined in inventory?

http://docs.ansible.com/ansible/latest/playbooks_variables.html

I'm failing to see how this is an issue?

**Comment by wenottingham** [comment]
Closing - please reopen with the info requested if needed.
