### ISSUE TITLE
document special _awx_description variable

### ISSUE THREAD

**Issue by azrdev** [ansible/awx#8793]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
#6966 /  #6265 added a host/group-variable `_awx_description` to be used by external inventory sources. This var should be mentioned in the documentation.

**Comment by tvo318** [comment]
Need to include mention of this variable in this section: https://docs.ansible.com/automation-controller/4.1.0/html/administration/scm-inv-source.html#ag-inv-import

**Comment by azrdev** [comment]
@tvo318 can you point to the code that extends the docs?

**Comment by tvo318** [comment]
@azrdev yes, sure it is in the PR indicated above: https://github.com/ansible/product-docs/pull/1715/files#diff-60eede4d18c8e3cd61c67f8cc00d542a65ac7a652b0ec927e3bf973f2d06ab4f

**Comment by azrdev** [comment]
I do not see any indication of said PR, so thank you for providing the link explicitly!

Edit: I do not see the repo, so probably it's private which explains the (in)visible reference.
