### ISSUE TITLE
Color-blind UI  

### ISSUE THREAD

**Issue by cbois** [ansible/awx#8797]
##### ISSUE TYPE
 - UI : Support "Color-Blind" mode

##### SUMMARY
Color-blind users are "discouraged" to use AWX : Icons displayed in views are quite difficult to differentiate.

For example, here is the `jobs view` (the application Chromatic Vision Simulator was used to illustrate)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/23309218/101643316-4d07cf80-3a34-11eb-9778-4b85ced285d6.png)

Is there a way to implement a more compliant set of icons (or themes)? 

Thanks a lot for this great tool!

**Comment by wenottingham** [comment]
We've just landed a new user interface that will be in the next AWX release (16.0). We'd love your feedback on that.

**Comment by cbois** [comment]
We'll be pleased to bring you some feedback with this version!
Thanks!

(@cchopin 👈 We need YOU!)

**Comment by cchopin** [comment]
I will do a feedback as soon as we install the new version!

Colorblind FTW

**Comment by ryanpetrello** [comment]
Hey @cchopin @cbois just a heads up, we've actually just released a new version of AWX (16.0.0) that includes the rewrite of our user interface.  Give it a whirl and let us know how we can improve.

**Comment by cbois** [comment]
Hello @ryanpetrello 
Is there a demo or sandbox environment anywhere?

We'll upgrade our version to 16.0.0, but not today for sure!

**Comment by ryanpetrello** [comment]
Hey @cbois,

 We don't currently have a public sandbox deployment of AWX for a number of reasons (partially cost, but also, it's technically a system that's meant to run arbitrary playbooks/Python code, so locking it down in a fashion that would thwart anonymous evil-doers would also probably not be a good showcase of AWX's feature set 😄!)

**Comment by unlikelyzero** [comment]
@cbois we've done a considerable amount of work to ensure that we have followed the WCAG rulesets. Please let us know when you pull this down to give it a try!

**Comment by unlikelyzero** [comment]
@tiagodread and @keithjgrant will be addressing a11y rules and I believe that visual impairment relates to color contrasts, is that correct @cbois ?

**Comment by keithjgrant** [comment]
@unlikelyzero it also relates to ambiguous colors (especially red v. green). The old UI had a lot of red/green icons to indicate job status. I've confirmed that the job list now uses distinct icons and text labels, so this isn't an issue there, but our old red/green status boxes still live on if you dig into some details pages, etc, so those should probably be updated to some sort of treatment along the same lines as the job list.

**Comment by wenottingham** [comment]
Hi - 

We've landed the new UI, which uses components from patternfly which undergo their own a11y testing, and we also have a small set of a11y test for the app itself. I'm going to close this, and encourage folks to open issues where they still see problems.
