### ISSUE TITLE
Job console messes up text and scrolling

### ISSUE THREAD

**Issue by yurtesen** [ansible/awx#8805]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I am using AWX 15.0.1. I tried to enable showing less information in job output using global job environment variables:
```
 "ANSIBLE_DISPLAY_SKIPPED_HOSTS": "no",
 "ANSIBLE_DISPLAY_OK_HOSTS": "no",
```
First things look normal, but many `included: ...` statements later some empty lines start coming in from bottom and then the scroll follow option stops working. If I try to manually go up/down then lines appear disappear sort of randomly.

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker
* Ansible version:  2.9.14
* Operating System: Ubuntu 20.04
* Web Browser: Firefox

##### STEPS TO REPRODUCE

1- Setup global environment variables:
```
 "ANSIBLE_DISPLAY_SKIPPED_HOSTS": "no",
 "ANSIBLE_DISPLAY_OK_HOSTS": "no",
```
2- Run a task with lots of `task_include` statements which print `included: ....` type lines.

##### EXPECTED RESULTS

The job console should not be confused.

##### ACTUAL RESULTS

Previous page, next page and first/last page buttons show somewhat random number of lines per page.

##### ADDITIONAL INFORMATION

I think it may be happening due to `include_tasks` task is printing `included: ... ` statements without first printing `TASK [...........] ******` line. But that is a hunch right now....

**Comment by mabashian** [comment]
@yurtesen we've made a number of changes to the way the output works recently.  If this is still an issue please reopen.
