### ISSUE TITLE
Enabling Job output filter during running

### ISSUE THREAD

**Issue by sugitk** [ansible/awx#8806]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

When running a very large job, a customer wants to filter the output only in `PLAY` lines in order to see the proceeding job.  At the current version of Tower cannot set/configure a filter when running, it will be helpful to enable the filter for the purpose.  Also if it enabled the `collapse` (+/- icon) during the running job, the UI could be more friendly.

It may be possible to consider with the existing issue #5906

**Comment by wenottingham** [comment]
If you want to see only PLAY lines and no specific host task details, set AWX_UI_LIVE_UPDATES_ENABLED=False.

**Comment by sugitk** [comment]
Thank you, I tested on Tower 3.7.4 and 3.8.0.  The parameter was "UI_LIVE_UPDATES_ENABLED" in settings.

* 3.7.4
I couldn't get the changes in the output.

* 3.8.0
The details were hidden, only `PLAY` and `TASK` lines were shown.  The customer's request was to hide the `TASK` line as well, but I will instruct this way.
 
<img width="744" alt="スクリーンショット 2020-12-11 8 51 34" src="https://user-images.githubusercontent.com/2234991/101843682-15ad3600-3b8e-11eb-88bd-926383efd619.png">

**Comment by wenottingham** [comment]
Correct, this is a change we made in 3.8.x to help speed up event processing.
