### ISSUE TITLE
Remove usage of Ansible from all launch scripts

### ISSUE THREAD

**Issue by shanemcd** [ansible/awx#8808]
In the future, Ansible will only exist inside of an Execution Environment. In order to do that, we need to remove any need for Ansible on the control plane. I have identified the following locations:

https://github.com/ansible/awx/blob/devel/tools/docker-compose/bootstrap_development.sh#L4-L13
https://github.com/ansible/awx/blob/devel/installer/roles/image_build/files/launch_awx.sh#L10-L11
https://github.com/ansible/awx/blob/devel/installer/roles/image_build/templates/launch_awx_task.sh.j2#L10-L11
https://github.com/ansible/awx/blob/devel/installer/roles/kubernetes/templates/launch_awx.yml.j2#L17-L18
https://github.com/ansible/awx/blob/devel/installer/roles/kubernetes/templates/launch_awx.yml.j2#L48-L49

We’re currently using ansible to connect to postgres and make sure a database / user exists. I think we should stop doing that. And just use whatever environment variables the postgresql images support.

Per suggestion from @ryanpetrello, this could be easily achieved by wrapping something like this in a retry loop:

```
>>> sock = socket.socket(family=socket.AF_INET, type=socket.SOCK_STREAM, proto=0, fileno=None)
>>> sock.connect(('example', 80))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
>>> sock.connect(('example.com', 80))
>>>
```

**Comment by ryanpetrello** [comment]
@shanemcd I think this is closable, so I've closed it:

```
~ dsh
bash-4.4$ which ansible
which: no ansible in (/var/lib/awx/venv/awx/bin/:/usr/pgsql-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
```
