### ISSUE TITLE
[ui_next] Project revision doesn't update after SCM Sync on Project Lists

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8811]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Project revision doesn't update after SCM Sync on Project Lists. Need to refresh

##### ENVIRONMENT
* AWX version: 12/12

##### STEPS TO REPRODUCE
1. Load a project list like /projects/
2. Perform a project sync in which the gitsha value changes
3. Note that the project status has updated but the "copyable" git sha value has not updated and a user could copy the wrong value to keyboard

##### EXPECTED RESULTS
1. Project git sha to match updated value

##### ACTUAL RESULTS
1. Previous git sha value shown

**Comment by unlikelyzero** [comment]
Filing as low because it can be fixed on refresh and it didn't ever work on the old ui (as far as I can tell)

**Comment by unlikelyzero** [comment]
@ryanpetrello @chrismeyersfsu i'd put this into the bughancement category

**Comment by wenottingham** [comment]
Closing, tracking elsewhere.
