### ISSUE TITLE
[ui_next] Can create a user with a single character password

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8815]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Can create a user with a single character password. This is obviously not secure. Not sure how much enforcement we want to put in palce

##### ENVIRONMENT
* AWX version: 12/10 devel

##### ADDITIONAL INFORMATION

Generally speaking, I think we should avoid getting to involved in account security, but a single character password is a pretty low bar.

**Comment by wenottingham** [comment]
Is this any different than the old UI?

**Comment by mabashian** [comment]
I don't think we've ever had any password requirement validation in the UI

**Comment by wenottingham** [comment]
Closing this as working as expected; the suggestion is to do this in your connected IdP. See also https://github.com/ansible/awx/issues/4553
