### ISSUE TITLE
[ui_next] Users with poor network connectivity have a poor experience on API heavy pages

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8820]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Basically we have some forms which need to generate many calls and this has a negative impact on the user experience.

On Workflow Viz Wizard, each step generates many queries and provides a poor experience if you're on a bad connection.

Generally, i think this can be solved with skeleton loading and lazy loading but we should also look at ways to reduce the number of calls made on certains pages/modals

**Comment by unlikelyzero** [comment]
```
Wf node modal makes API calls every time I select a different JT and this disables the save button for a while. This is annoying. Seems like its trying to generate whether I get next steps. No caching is happening because when I switch between JTs it lags a ton and does not seem to reuse info
```

**Comment by mabashian** [comment]
>Wf node modal makes API calls every time I select a different JT and this disables the save button for a while

I'm not sure that we can really do anything about that.  We _have_ to hit the launch endpoint to see whether or not there's any promptable fields or passwords needed on the template.

In general if we're making duplicate requests where something _could_ be cached then I guess that's something to explore but this issue feels nebulous.  I'm not sure what the action item actually is.

**Comment by wenottingham** [comment]
Closing, this should be tracked as separate items on specific pages where there are issues.
