### ISSUE TITLE
[ui_next] Cannot add one user to multiple organizations in Users/N/Organizations view

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8825]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Can’t add an user to multiple orgs (we can for teams though)

##### ENVIRONMENT
* AWX version: 12/10

##### STEPS TO REPRODUCE
Go to Users page / Organizations.
Note: cannot add multiple organizations at this view

##### EXPECTED RESULTS
Add more orgs

##### ACTUAL RESULTS
cannot add

##### ADDITIONAL INFORMATION
![Screen Shot 2020-12-10 at 1 35 34 PM](https://user-images.githubusercontent.com/12446869/101814780-99164b00-3aec-11eb-877d-c76ea4ee7b5d.png)

**Comment by wenottingham** [comment]
This isn't an associate view, that's done via roles.
