### ISSUE TITLE
[ui_next] [UX] Inline form validation is applied when canceling an edit instead of <back> action

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8826]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The inline form validation on an add/edit form is applied when hitting the cancel button. This prevents the user from being navigated back on first click of cancel button.

##### ENVIRONMENT
* AWX version: 12/10

##### STEPS TO REPRODUCE
1. Create an organization
2. Click on the 'Name' field
3. Click on the 'Cancel' button
Note: user has to click cancel button twice because form validation is applied initially

##### EXPECTED RESULTS
First cancel press should navigate the user back to previous page

##### ACTUAL RESULTS
inline form validation applied
User navigated back to previous page

##### ADDITIONAL INFORMATION
![Screen Shot 2020-12-10 at 1 39 43 PM](https://user-images.githubusercontent.com/12446869/101815188-2d80ad80-3aed-11eb-8f7a-28c83e304339.png)

**Comment by AlexSCorey** [comment]
Putting this in needs test because I don't think this is a valid issue any more.

**Comment by tiagodread** [comment]
@AlexSCorey this is still a valid bug, look:


https://user-images.githubusercontent.com/12464858/128750953-8c996e9a-3905-420f-a627-85c954e3e180.mp4
