### ISSUE TITLE
[ui_next] [ux] when using yaml editing, tabbing into code mirror should go past '---'

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8827]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
At the moment, Tabbing into a codemirror field puts the user into the first line of syntax instead of firstline of yaml field.

![Screen Shot 2020-12-10 at 1 42 32 PM](https://user-images.githubusercontent.com/12446869/101815474-9b2cd980-3aed-11eb-9b53-e805a440f103.png)

**Comment by unlikelyzero** [comment]
```It would be great to have a new line when the default value is a yaml file. The current way, see below, we have to always press enter to start typing. I think a better experience would be to have the new line so we could click on line two and start typing right way.```

**Comment by unlikelyzero** [comment]
```Tab navigation gets stuck in variables text box```

**Comment by mabashian** [comment]
link https://github.com/ansible/awx/pull/9281 which may address this

**Comment by mabashian** [comment]
yea #9281 addresses this
