### ISSUE TITLE
[ui_next] User should not be able to change credential types for existing credentials

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8828]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Generally, giving the user the ability to switch between credential types after a credential is created causes lots of complexity with very little benefit

##### ENVIRONMENT
* AWX version: 12/10

##### STEPS TO REPRODUCE
1. Create a credential
2. Modify credential type
Note: dragons and form errors

##### EXPECTED RESULTS

I think we should remove this functionality until we can map out the intent.

##### ACTUAL RESULTS
Dragons

**Comment by mabashian** [comment]
_yes_

**Comment by unlikelyzero** [comment]
@wenottingham i think we should prioritize this for the next release so that we can dramatically reduce the complexity in testing this

**Comment by yagomarques** [comment]
![image](https://user-images.githubusercontent.com/18562328/114591798-a12ff400-9c60-11eb-9d95-439882e55bec.png)
it's working, the field are locked to modify.
