### ISSUE TITLE
Allow per host independent execution of workflow

### ISSUE THREAD

**Issue by ghost** [ansible/awx#883]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Allow execution of a workflow on a per host basis, where a particular host may take either a success path or a failure path depending on task outcomes for only that host.

##### ENVIRONMENT
* AWX version: 1.0.1

##### STEPS TO REPRODUCE

This enhancement would allow finer-grained control of the path that particular hosts take through a workflow and would reduce the problem of a workflow node failure causing hosts to fail to complete the workflow that otherwise could.

**Comment by wenottingham** [comment]
This is changing how playbooks work at a rather fundamental level, and passing complex limits between playbooks that didn't exist before, in ways that may prevent playbooks from working properly. I don't see us doing this.
