### ISSUE TITLE
[ui_next] Cannot create schedules for workflow jobs

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8831]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Cannot create schedules for workflow jobs

##### ENVIRONMENT
* AWX version: 12/10

##### STEPS TO REPRODUCE
1. Navigate to a workflow job template schedules tab
2. Create schedule and save
Note: error message

##### ADDITIONAL INFORMATION
<img width="660" alt="Screen Shot 2020-12-10 at 1 54 24 PM" src="https://user-images.githubusercontent.com/12446869/101816695-55711080-3aef-11eb-9a0f-ff5e89eeba2a.png">

**Comment by mabashian** [comment]
Based on the error in the screenshot it looks like someone was trying to create a schedule for a WF that had a survey.  This is/was not yet supported and is being tracked here: https://github.com/ansible/awx/issues/7692.

I tested out a generic case where no prompts were necessary and I was able to create a schedule.
