### ISSUE TITLE
[ui_next] SCM Inventory Source Update Details view has no link to the project Sync which caused it

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8839]
##### ISSUE TYPE
 - Bug Report
 - Enhancement

##### SUMMARY
It is very common that the sync fails because the source_project_update fails, and having a link to it is absolutely critical for usability.
It would also be nice to have a link to the inventory source & the source project (as opposed to the source update). However, I guess we can get by without these. If we don’t have a link to the source project update, it leaves resources totally orphaned.

##### ENVIRONMENT
* AWX version: 12/10

##### ADDITIONAL INFORMATION

![Screen Shot 2020-12-10 at 3 48 16 PM](https://user-images.githubusercontent.com/12446869/101828205-3b3f2e80-3aff-11eb-8fee-455473bdff49.png)

**Comment by unlikelyzero** [comment]
@one-t looks like it failed to merge. Leaving this open until it merges

**Comment by unlikelyzero** [comment]
closing now that #8992 merged

**Comment by AlanCoding** [comment]
This page still has no link to the source project update. It just contains a link to the source _project_.
