### ISSUE TITLE
[ui_next] Project details view needs sync button

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8847]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Can only update projects from the list view, but can update inventory sources from the detail view and list view.
https://tower-mockups.testing.ansible.com/patternfly/projects/projects-detail/

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by kannurkars** [comment]
looks like this fix broke job output of the failed jobs, 
Ref: #9117
even tough api/v2/project_updates/110/stdout has the output of the job it says internel server error in job out page in UI.

```
HTTP 500 Internal Server Error
Content-Type: application/json
Vary: Accept

{
    "detail": "A server error has occurred."
}
```

**Comment by unlikelyzero** [comment]
https://github.com/ansible/awx/pull/9003#issuecomment-755752991
