### ISSUE TITLE
[ui_next] Clicking on Text within a modal doesn't select but DOES issue api requests

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8852]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Clicking on Text within a modal doesn't select but DOES issue api requests.

##### ENVIRONMENT
* AWX version: 12/10

##### STEPS TO REPRODUCE
1. Open modal with checkboxes like Add Team Roles to User
2. Click on the name of the resource or object in the list
3. Object's checkbox not selected but API requests fired off.

##### EXPECTED RESULTS
Selected items should be selected

##### ACTUAL RESULTS
Not selected with checkbox

##### ADDITIONAL INFORMATION
<img width="630" alt="Screen Shot 2020-12-10 at 6 15 00 PM" src="https://user-images.githubusercontent.com/12446869/101841296-a72b9200-3b13-11eb-9756-d834140a9673.png">

**Comment by unlikelyzero** [comment]
@tiagodread i'm positive that you've filed this one already but cannot find it

**Comment by unlikelyzero** [comment]
Note, this is filed here: 
https://github.com/ansible/awx/issues/7220 
https://github.com/ansible/awx/issues/7510 
https://github.com/ansible/awx/issues/7508

and was reported in each bug bash.

I'm going to keep this one open and close the others

**Comment by tiagodread** [comment]
PR already merged working as expected!
