### ISSUE TITLE
[ui_next] Notification failure message is not show on notification template listview

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8853]
##### ISSUE TYPE
 - Feature Parity?

##### SUMMARY
Notification failure message is not show on notification template listview. This may or may not have been required for feature parity

##### ENVIRONMENT
* AWX version: 12/10

##### STEPS TO REPRODUCE
Create a notification template which will result in a failed execution or error
Navigate the the listview of that notification template.
Note: failed without message

##### EXPECTED RESULTS
Failure reason displayed in line or on hoverover

##### ACTUAL RESULTS
Just overall Failed Result

##### ADDITIONAL INFORMATION

<img width="621" alt="Screen Shot 2020-12-10 at 6 22 00 PM" src="https://user-images.githubusercontent.com/12446869/101841771-9d565e80-3b14-11eb-9342-ba110aa947b5.png">

**Comment by mabashian** [comment]
@AlexSCorey you still working on this?  If so feel free to re-assign and update the labels.

**Comment by mabashian** [comment]
I think https://github.com/ansible/awx/issues/9223 is what we need for feature parity.  What you're describing here is a good enhancement _but_ it requires an extra request for every row on the page.  It would be really nice to be able to show a tooltip with the error in it but that value comes from `/api/v2/notifications/:id` whereas the list is populated via `/api/v2/notification_templates/:id`.  The api does return `recent_notifications` to us in this list but that does not include the error:

```
        "recent_notifications": [
            {
                "id": 3,
                "status": "failed",
                "created": "2021-02-03T20:13:00.200339Z"
            },
            {
                "id": 1,
                "status": "failed",
                "created": "2021-02-03T20:11:08.815978Z"
            }
        ]
```

**Comment by jladdjr** [comment]
@mabashian I think https://github.com/ansible/awx/pull/10094 should give you what you need in order to get notification errors directly from `api/v2/notification_templates`.

**Comment by jladdjr** [comment]
Chatted with @AlexSCorey who said it'd be fine to go ahead and get the API side of things in and the UI side can follow up separately. Applied `mergeit` on https://github.com/ansible/awx/pull/10094 so that should be in soon.

Removing API label on this ticket since (afaict) the needed API support is now in. @AlexSCorey , if you find that you're needing anything else from the API, just give a holler.

**Comment by mabashian** [comment]
Closing - toast should now be displayed
