### ISSUE TITLE
When upgrading to ui_next, the browser cookies need to be cleared to access the /settings/ page

### ISSUE THREAD

**Issue by Lobout** [ansible/awx#8861]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
after install the settings section works, but then stops working with an error with no data in it

##### ENVIRONMENT
* AWX version: 16.0
* AWX install method: docker on linux
* Ansible version:  2.9.15
* Operating System: RHEL 7
* Web Browser: Opera/Firefox/Chromium Edge

##### STEPS TO REPRODUCE

upgrade/install server, go to settings section, navigate away wait some time and try to navigate back

##### EXPECTED RESULTS

expect to see the settings for the application

##### ACTUAL RESULTS

Something went wrong...
There was an error loading this content. Please reload the page. Back to Dashboard.

**Comment by unlikelyzero** [comment]
@Lobout , how long were you away from the settings page? It's possible that you experienced a timeout / session expiration.

**Comment by Lobout** [comment]
It varied in my quick tests.  anywhere from a couple minutes to an hour.    I even closed my browser, logged back in and the settings page gave the same error.   I restarted the containers and logged in again and it comes back.  but it then stops working again.

**Comment by Lobout** [comment]
if there are any logs i can collect to provide you please let me know

**Comment by Lobout** [comment]
so If i clear the cache in my browser this fixes the issue.  It seems that when the cache becomes stale the issue appears

**Comment by unlikelyzero** [comment]
@Lobout the only important logs would have been the console warnings/errors which must have been cleared already. I'm glad that everything is working now

**Comment by Lobout** [comment]
I have to keep clearing my browser cache when going to the settings page.  This is a bit of a pain, but workable until there is a fix.

**Comment by jakemcdermott** [comment]
Yep, this looks like an unhandled session timeout. Thanks for letting us know @Lobout! 

We'll be merging code into devel to properly handle this soon, but it hasn't landed yet. You'll very likely see this addressed in the next awx release.

see: https://github.com/ansible/awx/issues/4205

Closing this issue for now as we're tracking the work in the issue above.

**Comment by Avi0** [comment]
Settings page does not work for me regardless of cookies, cache, anything else. Does not work even in a private browser session. Same error, "There was an error loading this content. Please reload the page. Back to Dashboard.".

Update: settings page works only intermittently. Console shows error:

2.a3befcbb.chunk.js:sourcemap:2 OPTIONS https://[redacted]/api/v2/settings/all/ net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)

**Comment by unlikelyzero** [comment]
@Avi0 that is a net new issue. Please check our issue tracker to see if it may be an old bug like https://github.com/ansible/awx/issues/1855 . If it's not, please file a new issue and we'll take a look!
