### ISSUE TITLE
System auditor users can create credentials

### ISSUE THREAD

**Issue by jpclipffel** [ansible/awx#8864]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
System auditors can create new credentials, edit them and remove them. 

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: kubernetes
* Ansible version:  2.9.14
* Operating System: Windows 10
* Web Browser: Firefox

##### 1 - Create the user

* Create a new local user:
  * User type: **System Auditor**
  * Organization: Any organization, let's say **myCompany**

The system auditor user now have the following permissions (reviewed at **Users** > *user name* > **Permissions** tab):

| Name | Type | Role |
|-------|------|------|
| *myCompany* | Organization | Member |
| | | System Auditor |

**Important note:** the system auditor user is not a member of any team and have no other permission set.

##### 2 - Create a credential

* Login with the new user
* Go to **Credentials**
* Create a new credential (same behavior observed for multiple credential types: AWX, Tower, GitHub PAT, Machine)
  * Fill all required fields
  * **Organization** field left empty (no organization shown to choose from)
* Save

The system auditor user has now the role **Admin** for the newly created credential:

| Name | Type | Role |
|-------|------|------|
| *myCompany* | Organization | Member |
| | | System Auditor |
| *myCredential* | Credential | Admin | 

##### 3 - Removing organization permissions

Removing the system auditor user from the organization *myCompany* does not prohibit the system auditor user from creating credentials.

##### EXPECTED RESULTS

System auditor user should not be allowed to create new credentials.

##### ACTUAL RESULTS

System auditor users can create credentials out of an organization, edit them and delete them.

##### ADDITIONAL INFORMATION

I tried to create, edit and delete other resources using the same system auditor users (one being a member of the organization **myCompany**, another having no organization at all). The users cannot create, edit or delete the resources (which is the expected behavior).

Tested resources:

* Templates
* Projects
* Inventories (including single inventory, single host and inventory sources)
* Inventory Scripts
* Organizations
* Users
* Teams
* Credential Types
* Notifications

**Comment by wenottingham** [comment]
All users (including auditors) have the ability to create their own, "personal", credentials.

See #1126.
