### ISSUE TITLE
no source_vars field for RHV credentials

### ISSUE THREAD

**Issue by natman** [ansible/awx#8872]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

There is currently no way in UI to add source_vars for RHV credentials type so as to build the ovirt.yml inventory read by ansible-inventory. The only way to do such a thing is to inject json with curl or with awx inventory_source --source-vars option. The field does exist in other credential types AWS etc...

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.14
* Operating System: centos 7
* Web Browser: firefox 84

**Comment by wenottingham** [comment]
-> #8786
