### ISSUE TITLE
[Docs] List of Available Settings?

### ISSUE THREAD

**Issue by hjkatz** [ansible/awx#8876]
##### ISSUE TYPE
 - Docs

##### SUMMARY

Where can I find a list of settings available to configure for an installed AWX instance?

I've found some sources in the code that indicate the settings are spread out, but I'm not sure which file is the source of all the available settings.

* https://github.com/ansible/awx/blob/devel/awx/main/conf.py
* https://github.com/ansible/awx/blob/devel/awx/settings/defaults.py
* https://github.com/ansible/awx/blob/devel/awx/conf/conf.p

Specifically I'm trying to use the `awx.axw.tower_settings` module, but I'm not sure exactly _which_ settings I can use.

Any help would be greatly appreciated, thanks!

**Comment by jakemcdermott** [comment]
:wave: hello, thanks for creating this issue.

Settings are dynamically generated by the API. Changes are made all of the time. Your best option for a comprehensive list of all available settings is the ui (or interactive rest api documentation for the settings endpoint .. `/api/v2/settings/`)

I'm closing this issue for now, as this github project is for tracking work for the awx project. If you have additional questions, drop by the `ansible-awx` freenode channel on irc or check out our community mailing list.

**Comment by hjkatz** [comment]
If I were to view the settings listed in the UI, then how could I know which settings map to what values in the `awx.awx.tower_settings` module?

**Comment by wenottingham** [comment]
You're probably better off looking at the browseable API at /api/v2/settings/all for that info.

**Comment by hjkatz** [comment]
I figured out the problem, the `/api/v2/settings/all` interface is only browseable as the AWX admin user.
