### ISSUE TITLE
Error running latest AWX 16.0.0 - "Request user is not authenticated to use websocket."

### ISSUE THREAD

**Issue by tstahnke2** [ansible/awx#8881]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY
we are using Azure AD authentication to login to AWX 16.0.0. When viewing running job output, we are seeing error messages in the logs that specify only the below errors. The impact of this bug is that we can't see live job output; our exact same config worked great in awx 15.0.1

2020-12-13T21:45:00.679203820Z 169.254.130.1 - - [13/Dec/2020:21:45:00 +0000] "GET /websocket/ HTTP/1.1" 101 21 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36" "10.111.8.33:53600"
2020-12-13T21:45:02.697822850Z 2020-12-13 21:45:02,697 ERROR    awx.main.consumers Request user is not authenticated to use websocket.
2020-12-13T21:45:02.697875151Z 2020-12-13 21:45:02,697 ERROR    awx.main.consumers Request user is not authenticated to use websocket.
2020-12-13T21:45:02.699664385Z 2020-12-13 21:45:02,697 ERROR    Request user is not authenticated to use websocket.

In the web browser, this is the error that the client sees:

WebSocket is already in CLOSING or CLOSED state.
t @ useWebsocket.js:16
(anonymous) @ useWebsocket.js:33
setTimeout (async)
Mm.o.current.onclose @ useWebsocket.js:32

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.15
* Operating System: Windows 10 (client)
* Web Browser: Microsoft Edge (latest), or Chrome

##### STEPS TO REPRODUCE
Login with Azure AD to awx, then try to view a running job

##### EXPECTED RESULTS

Websockets should be able to retain auth information. Also, job output should stream as expected.

##### ACTUAL RESULTS

Job output doesn't stream to the output window in realtime.

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/45852091/102025289-e7ce1a00-3d64-11eb-8a65-9855ac26fbad.png)

**Comment by unlikelyzero** [comment]
@jakemcdermott is this a dupe of https://github.com/ansible/awx/issues/8596

**Comment by jakemcdermott** [comment]
@unlikelyzero I don't believe so.

**Comment by jakemcdermott** [comment]
:wave: Thanks for creating this issue. This bug is addressed by https://github.com/ansible/awx/pull/8877. You should see this fixed in the next awx community release.

**Comment by tstahnke2** [comment]
Thanks, that appears to be working, I was able to apply the patch to our image :) Now the output isn't updating until the job is done, I'm going to have to dig and see if it's something in my config...

**Comment by thorian93** [comment]
@tstahnke2 any news? I see the same errors in my log in Version 17.0.1 and I also have the issue, that the job output is not updating as described in #8994.
