### ISSUE TITLE
Poor API performance for large jobs

### ISSUE THREAD

**Issue by jplitza** [ansible/awx#8883]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Paged API responses take longer if the total result set is larger.

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.14
* Operating System: Ubuntu 20.04
* Web Browser: Firefox 83.0

##### STEPS TO REPRODUCE

Run a job with a handful of hosts and a handful of tasks, and one with hundreds of hosts and hundreds of tasks. Then query the job_events for both.

##### EXPECTED RESULTS

While the larger job has more job_events, each paged result should be delivered in the same time as a paged result of the smaller job.

##### ACTUAL RESULTS

The delivery of 200 job_events in one page takes more than 60 seconds for the large task with a total of 207,957 job_events to return, whereas the delivery of 200 job_events in one page of the small task, where only 6,376 job_events have to be returned, only takes ~1 second (so the effect even seems to be non-linear :scream:).

##### ADDITIONAL INFORMATION

I guess this is caused by the API always returning the total number of results. Filtering doesn't seem to have any influence.

**Comment by jplitza** [comment]
I may add that the storage the database is on isn't the fastest. So I looked into what's going on on the database level, and sure enough, even the COUNT(*) query takes over 50 seconds. I'm no expert on PostgreSQL, but apparently the [BRIN index](https://www.postgresql.org/docs/9.5/brin-intro.html) used for the job_id column in the main_jobevent requires that the database reads all relevant rows anyway, in order to verify that they really have that job ID.

And indeed, when I recreated the index main_jobevent_job_id_brin_idx as btree, the duration of the COUNT(*) query dropped to 5 seconds, and each paged result from the API is now served in 10-15 seconds.

So I don't know about any adverse effects this change would have, but regardless of the scale, re-serving the total count of items with each answer seems a waste of resources when we have to fetch it from the DB every time.

**Comment by jplitza** [comment]
I'm getting the impression that I'm using the API in an unintended way…
When advancing through the pages of the response, the response time increases, even with the btree index. An not only response time: Memory usage of the *uwsgi* process is rocketing as well, taking up several GB.
Guess I will have to take a deep dive into how the API handles its requests. I would have expected that the page and page_size parameters are translated into an SQL LIMIT clause, which could maybe explain longer database query duration, but not increased memory usage in uwsgi.

**Comment by ryanpetrello** [comment]
related: https://github.com/ansible/awx/issues/9039

**Comment by ryanpetrello** [comment]
@jplitza do you have some notion of the total number of events in the system e.g.,

```sql
awx-dev=> SELECT max(id) FROM main_jobevent;
```

**Comment by ryanpetrello** [comment]
@jplitza it's been awhile, but we're working on merging in support for table partitioning for this data in an upcoming release of AWX, and I expect you to see notable performance improvements when that work lands: https://github.com/ansible/awx/issues/9039
