### ISSUE TITLE
Prompt on launch broken for machine ssh key passwords on new ui

### ISSUE THREAD

**Issue by dansou901** [ansible/awx#8889]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
On the new Web interface, when using machine credentials with ssh keys which are configured to prompt for a password on job launch, it doesn't ask for a password. For now, password protected ssh keys can only be used with saved passwords, not with prompt on launch.

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.6
* Operating System: Ubuntu x64
* Web Browsers: Firefox, Chrome

##### STEPS TO REPRODUCE

Add a machine credential and insert an ssh private key which is password protected, set prompt on launch for the passphrase of the key. Then, use this credential in a job template.

##### EXPECTED RESULTS

When starting the job template and selecting the credential, it should ask for a passphrase.

##### ACTUAL RESULTS

The ui never asks for a passphrase and the job fails due to being unable to unlock the ssh key.

##### ADDITIONAL INFORMATION

I upgraded from a previous 15.0.1 install.

**Comment by mabashian** [comment]
This is a known issue: https://github.com/ansible/awx/issues/7015.  https://github.com/ansible/awx/pull/8399 contains a lot of refactoring to the launch prompt.  Once we get that PR merged we'll be able to add password prompting shortly thereafter.

**Comment by dansou901** [comment]
Thanks for the fast reply! Didn't find those merge requests, should have spent more time on searching. Good to know that it's already being worked on!
