### ISSUE TITLE
Advanced search host filter chips not rendered in smart inventory form

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#8890]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
This logic here: https://github.com/ansible/awx/blob/devel/awx/ui_next/src/components/Lookup/HostFilterLookup.jsx#L275 means that we will only ever render chips that fit our default search options.  If you create a filter using the advanced search it _appears_ to not work (even though it is working, just not rendering).

![host_filter](https://user-images.githubusercontent.com/9889020/102125727-1d800b00-3e18-11eb-8ef8-1643f0336d98.gif)

**Comment by nixocio** [comment]
I was not able to re-create this on devel. It seems like it was already fixed.

**Comment by akus062381** [comment]
this is all set. closing

**Comment by akus062381** [comment]
@mabashian - Tiago brought something to my attention that I had missed before, that when you perform an advanced search here, the chip showing the filter parameter is not visible. It is only visible when performing a basic search. I am reopening this and putting it back into needs_devel

**Comment by tiagodread** [comment]
The modals in general is not displaying all items in the toolbar when there is only on item in the list because looks like the modal adjust the high according to the number of items in the list. I Wonder if the modal should have a defined high even if there is only one item, to avoid this behaviour @mabashian 

![image](https://user-images.githubusercontent.com/12464858/118705936-32116680-b7ef-11eb-88e6-33bdaad614ce.png)

**Comment by mabashian** [comment]
OK, it seems like there are some fields where the chip is displayed correctly but there are some advanced fields where it is not.  If you search for `id` or `inventory` for example (both id's) the chip renders correctly.  If you search for `name`, `description`, or `type` the chip does not render correctly.

Example using name:

![host_filter](https://user-images.githubusercontent.com/9889020/118708343-9d583a00-b7e9-11eb-9322-de0ea0812895.gif)

**Comment by akus062381** [comment]
this is fixed and verified! stubs already exist.
