### ISSUE TITLE
no error message when saving a webhook notification w/incorrectly formatted custom message

### ISSUE THREAD

**Issue by rebeccahhh** [ansible/awx#8898]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Custom messages for webhook notifications require dictionary format (with double quotes) to save. If you create a webhook notification and try to save it without this format there is no warning or error in the UI. It won't save (which is good) but has no indicator to notify the user of their mistake.

##### ENVIRONMENT
* AWX version: awx: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.15
* Operating System: fedora 30
* Web Browser: firefox

##### STEPS TO REPRODUCE
1. Click "Add" to begin creating a new notification template in the UI.
2. Choose "Webhook" from the choices and fill out basic info
3. Toggle on the option for "Customize messages…"
4. put anything except a valid dictionary into the fields below

##### EXPECTED RESULTS
An error message

##### ACTUAL RESULTS
Nothing happens, the page remains unchanged, but in the debug output there is visible `WARNING  django.request Bad Request`

##### ADDITIONAL INFORMATION
may fit in nicely with #8677

**Comment by jakemcdermott** [comment]
Hopefully helpful info for scoping:

After looking into this, I _think_ there's two parts to this issue:

1. (Potentially tricky) Sometimes, field-specific errors near the top of the form are completely out of view by the time you've scrolled far enough to save. This is especially likely if the custom messages are toggled on, as they take up a lot of space. This may require some ux discussion.  Maybe we trigger client-side validation on the notification fields before expanding the custom messages? That would provide an opportunity to see the field errors before moving further down the form.

2. The other part of this may be a matter of adding some field-specific validation on the CM inputs to detect json errors prior to submit
.

I'm not entirely sure [2] is a real problem or just a side-effect of [1]. I did, however, run into [1] several times organically. Once I began making sure I wasn't making any errors further up the form, I wasn't able to create a custom message that _wouldn't_ save to the DB.

**Comment by unlikelyzero** [comment]
@jakemcdermott how does this relate to https://github.com/ansible/awx/issues/8816

**Comment by jakemcdermott** [comment]
@unlikelyzero Probably a duplicate, and there is a good chance that the issue described in #8816  actually [1] (from above) in disguise. It's worth a re-test just to confirm.

**Comment by wenottingham** [comment]
-> #8898

**Comment by wenottingham** [comment]
Er, -> #6094
