### ISSUE TITLE
If a Credential is configured with POL fields, JT launches do not work

### ISSUE THREAD

**Issue by apollo13** [ansible/awx#8902]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Starting a template with an ssh machine credential that is configured to prompt for the private key fails:
![image](https://user-images.githubusercontent.com/81547/102200884-b0c34a00-3ec5-11eb-9795-de9ddfc69fc0.png)

Please note that the prompts do not even offer the option to provide the credentials

##### ENVIRONMENT
* AWX version: 16.0.0.
* AWX install method: docker on linux
* Ansible version:  2.9.15
* Operating System: Fedora 33
* Web Browser: Firefox 83

##### STEPS TO REPRODUCE

 * Create a maschine credential with an encrypted SSH key and "SSH private key password" set to "Prompt on launch"
 * If you want also create a vault credential with "Prompt on launch"
 * Assign the newly created credentials to any template
 * Try running the template

##### EXPECTED RESULTS

 * The template should prompt for the credentil passwords

##### ACTUAL RESULTS

 * Failure to start the task because required dependencies are not satisfied.

**Comment by BitProcessor** [comment]
Experiencing same problem.

**Comment by unlikelyzero** [comment]
Note: this likely affects JT Schedules and Workflow Node Prompts, too

**Comment by apollo13** [comment]
Sorry, the boards view played tricks on me :/

**Comment by apollo13** [comment]
@unlikelyzero Can you move this back to "Backlog" so it gets picked up? I accidentally moved it to "In Progess" via close/open.

**Comment by unlikelyzero** [comment]
@apollo13 thanks for filing this. It turns out that this is already a known gap in the current implementation. You can subscribe to https://github.com/ansible/awx/issues/7015 to see when it's going to be merged and available in devel!
