### ISSUE TITLE
Add proper validation to CodeMirrorField component

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#8906]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
It doesn't look like this was ever really implemented.  There's a prop on the component where you _could_ pass in a validate function but we don't actually do that in any of the places.

The idea here is that we want to validate the field for malformed yaml/json and _at a minimum_ show an error beneath the field.

The reason why I think this is going to be difficult is because we have to deal with formik.  By default, formik is going to run validation on _change_ and on _blur_.  In the case of these codemirror fields we definitely don't want to validate on change (each keystroke) since this would show errors constantly.  We probably only want to validate on blur.  This can be configured at the _form_ level with a prop passed to `<Formik ... ` but that would mean _all_ the fields in the form would only validate on blur.  We may have to come up with a clever solution here to only validate these codemirror fields on blur but validate the rest of the form on change and blur.

This is particularly important for places with prompts.  We manipulate/combine extra vars and survey values later on during the process and having unvalidated data makes error handling difficult.

This may also tie in to https://github.com/ansible/awx/issues/8905

**Comment by jakemcdermott** [comment]
May also be related to: https://github.com/ansible/awx/issues/8898#issuecomment-744838149 ?

Not really sure, but I think adding form-like field validation might help there?

**Comment by unlikelyzero** [comment]
and also related to #8816

**Comment by akus062381** [comment]
waiting on implementation
https://github.com/ansible/awx/issues/8905

**Comment by keithjgrant** [comment]
> The reason why I think this is going to be difficult is because we have to deal with formik. By default, formik is going to run validation on _change_ and on _blur_. In the case of these codemirror fields we definitely don't want to validate on change (each keystroke) since this would show errors constantly.

Our normal tactic is to wait until the first onBlur event to begin validating a field. Is there a reason that approach wouldn't work here?

**Comment by unlikelyzero** [comment]
@one-t is workin' on it
