### ISSUE TITLE
Malformed yaml can crash the launch/workflow node prompt wizard

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#8907]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
This should actually be addressed by https://github.com/ansible/awx/issues/8906.  If we had validation on the extra variables field then the user would address this there.

This bug won't make it's way into devel until https://github.com/ansible/awx/pull/8399 merges.

##### STEPS TO REPRODUCE
1. Create a JT that prompts for extra variables
2. Launch the JT
3. Enter the following text in the extra variables field:

```
---
foo: bar
foobar
```

4. Go to the preview step

##### EXPECTED RESULTS
Error was shown before going to preview step

##### ACTUAL RESULTS
Page crashes when we attempt to transform the extra vars.

**Comment by mabashian** [comment]
Here's the actual error that gets thrown:

`YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 4, column 1:`

**Comment by mabashian** [comment]
@keithjgrant you think this is covered by the ace editor PR?  If so can we retest?

**Comment by keithjgrant** [comment]
Yes, my PR should prevent this from happening. Is it worth adding additional handling to the page in case any pre-existing bad data gets fetched?

**Comment by tiagodread** [comment]
The PR was merged, bug fixed.
