### ISSUE TITLE
Yum Module python2-dnf error

### ISSUE THREAD

**Issue by Keith-Nowosielski-SJSU** [ansible/awx#8911]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

I keep getting this error on my RHEL 6-7 systems when I try using the YUM Module for patching or installing packages.

```
TASK [Linux Patching | RHEL YUM - "['*']"] *************************************
13:17:43 32 fatal: [servername]: FAILED! => {"changed": false, "cmd": "dnf install -y python2-dnf", "msg": "[Errno 2] No such file or directory", "rc": 2}
```

Ansible Controller: Ansible-awx official container image version 15.0.1Ansible Controller: CentOS 8Ansible Controller: Local Ansible Version 2.9.15Ansible Controller: Local Python 3.6.8

I'm listing both the container specs and the local host specs because the same play works on the local host running plan ole Ansible.

The RHEL systems don't seem to have python 3 installed. They do have Python2 and Python2.7.

I've seen others have similar issues however each post I've seen doesn't often give a definitive answer to what solved their problem, or it does which is usually to set the ansible_python_interpreter to a specific version, which I've tried doing that from both the playbook and the inventory group for python versions 2 and 3 as well as just using the /usr/bin/python directory.

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: Podman pod using ansible official awx container image from docker hub. 
* Ansible version:  2.9.14
* Operating System: CentOS 8
* Web Browser: Chrome87

##### STEPS TO REPRODUCE

Run Ansible playbook from awx 
Specific task - 

    - name: Linux Patching | RHEL YUM 
      yum: 
        name: "*"
        state: "latest"
      when: 
        - ansible_os_family == "RedHat" 
      tags: 
      - patching
      - updates  
      - rhel

##### EXPECTED RESULTS

 Yum update -y
 Yum install -y 

##### ACTUAL RESULTS

[job_685.txt](https://github.com/ansible/awx/files/5699520/job_685.txt)

fatal: [servername]: FAILED! => {"changed": false, "cmd": "dnf install -y python2-dnf", "msg": "[Errno 2] No such file or directory", "rc": 2}

**Comment by wenottingham** [comment]
This issue tracker is for tracking feature enhancements and bugs to AWX itself.

That looks to be an issue with the yum module in Ansible. Please file that at http://github.com/ansible/ansible, or visit the upstream Ansible google group at:

https://groups.google.com/forum/#!forum/ansible-project

**Comment by Keith-Nowosielski-SJSU** [comment]
Are you sure? I only ask because I'm only experiencing this issue in awx both version 10 and 15. It seems to work fine in ansible 2.9.15.
