### ISSUE TITLE
Incorrect coding example in Automation Hub ansible.tower.tower_license module document

### ISSUE THREAD

**Issue by unnecessary-username** [ansible/awx#8913]
I am Tong He from Red Hat Multi-Product Entitlement QE Team.

##### ISSUE TYPE
 - Bug Report

##### SUMMARY

The coding example given in Automation Hub ansible.tower.tower_license module's document is definitely wrong.
-  name: Set the license using a file
   license: <--This indicates license module, which cannot be recognized. Should be tower_license here.
   manifest: "/tmp/my_manifest.zip"
   eula_accepted: True

##### ENVIRONMENT
* Automation Hub version: 4.2

##### STEPS TO REPRODUCE

https://cloud.redhat.com/ansible/automation-hub/repo/published/ansible/tower/content/module/tower_license
https://access.redhat.com/solutions/3065701

##### EXPECTED RESULTS

A simple one:
![image](https://user-images.githubusercontent.com/68936428/102311797-754d7c00-3fa8-11eb-8b58-fdd463910516.png)

Maybe a more thorough one:
![image](https://user-images.githubusercontent.com/68936428/102311815-80081100-3fa8-11eb-800d-7fa729245854.png)

**Comment by tiagodread** [comment]
Verified locally and now is fixed!
