### ISSUE TITLE
Dynamic inventory source variables ignored

### ISSUE THREAD

**Issue by Jeroen7V** [ansible/awx#8914]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

When using source variables in a dynamic VMware inventory, most variables aren't processed. So far the 'port' variable is the only one we found which is being processed. Other variables such as 'alias_pattern' and 'host_filters' do not overwrite the default configuration of [vmware.ini](https://github.com/ansible-collections/community.vmware/blob/main/scripts/inventory/vmware_inventory.ini).

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/2264540/102336476-7fb04b80-3f91-11eb-807f-7d9a069ff3ed.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/2264540/102336461-7b842e00-3f91-11eb-94ec-6182073e1f54.png)
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/2264540/102336974-2d235f00-3f92-11eb-8c9f-d86306b508f0.png)

In the screenshots we placed the "alias_patern" source variable to overwrite the alias with a "\_PREFIX\_" followed by the uuid. However after a fresh run (deleted all hosts) the alias stays at the default value.

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.10.3
* Operating System: Ubuntu 18.04.2 LTS
* Web Browser: Firefox/Chrome

##### STEPS TO REPRODUCE

Create a dynamic inventory using VMware and try to use source variables to overwrite certain values.

##### EXPECTED RESULTS

The variables should be overwriting using the values in the "Source variables" field.

##### ACTUAL RESULTS

The values in the "Source variables" field are ignored and the default values are used.

**Comment by wenottingham** [comment]
The vmware inventory source is not using the VMware inventory script as defined in [vmware.ini](https://github.com/ansible-collections/community.vmware/blob/main/scripts/inventory/vmware_inventory.ini).

It uses the VMware inventory plugin, which is configured [in this way](https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vm_inventory_inventory.html)

You'll need to adjust your configuration in that manner.
