### ISSUE TITLE
Job Details missing source workflow link

### ISSUE THREAD

**Issue by adpavlov** [ansible/awx#8915]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.15
* Operating System: Mac OS 11
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Start workflow and go to any sub job
##### EXPECTED RESULTS

To have a link to source workflow that started this job
##### ACTUAL RESULTS
No link to source workflow as it was in previous AWX UI

**Comment by mabashian** [comment]
@adpavlov thanks for reporting this.  https://github.com/ansible/awx/pull/9035 should add this functionality back in to the details view.

**Comment by akus062381** [comment]
The test PR has not merged, here is the link
https://github.com/ansible/tower-qa/pull/5905
