### ISSUE TITLE
job can't be canceled if it was started from workflow

### ISSUE THREAD

**Issue by adpavlov** [ansible/awx#8916]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.15
* Operating System: Mac OS
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Start workflow execution and attempt to stop any child job
##### EXPECTED RESULTS
job to be stopped

##### ACTUAL RESULTS
Failed to cancel one or more jobs
You don't have privileges for this operation.

**Comment by AlanCoding** [comment]
We have a provision to allow users to cancel jobs that they, themselves, started.

https://github.com/ansible/awx/blob/d93d0f00ee37e0dbda8d11561c5068c6b8f88a67/awx/main/access.py#L1664-L1665

However, in this case, the user may have `execute_role` to the workflow, but not to the job in the workflow. If this is the case, then maybe this is better as a UI issue to provide the suggestion to cancel the entire workflow, which will subsequently cancel the job.

**Comment by adpavlov** [comment]
I have users authorized in LDAP and assigned to group which have following roles.
Am I missing something? At least I can say that user didn't change and there was no such issue in previous AWX UI.

![image](https://user-images.githubusercontent.com/51116816/102937376-0f3a8a80-44bb-11eb-9ad6-71e7d0c6b2e3.jpeg)

**Comment by ryanpetrello** [comment]
I'm not able to reproduce this in the new UI in AWX 18.0.0+

If you're still encountering this in the latest release @adpavlov, please let us know:

![Kapture 2021-04-12 at 15 45 58](https://user-images.githubusercontent.com/214912/114452364-5baef080-9ba6-11eb-978c-e3afe6d336fa.gif)
