### ISSUE TITLE
Can't launch job_template if scm_branch 'prompt on launch' not set

### ISSUE THREAD

**Issue by adpavlov** [ansible/awx#8917]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.15
* Operating System: Mac OS 11
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Configure job template as following without prompting Source control branch as inventory is custom script and launch it

![image](https://user-images.githubusercontent.com/51116816/102344492-0888b080-3fad-11eb-96ea-eecc06e07bb5.jpeg)

##### EXPECTED RESULTS

Job to be executed
##### ACTUAL RESULTS

Failure in starting job

![image](https://user-images.githubusercontent.com/51116816/102344617-3837b880-3fad-11eb-9e72-fb7c79575d5d.jpeg)

##### ADDITIONAL INFORMATION
json request:
`{"inventory_id":24,"job_type":"","limit":"all","job_tags":"","skip_tags":"","extra_vars":{},"scm_branch":""}`

response:
`{"scm_branch":["Field is not configured to prompt on launch."]}`

In POST actions it defined as optional and it was like this in previous AWX

```
    "actions": {
        "POST": {
            "ask_limit_on_launch": {
                "type": "boolean",
                "required": false,
                "label": "Ask limit on launch",
                "filterable": true,
                "default": false
            },
            "ask_scm_branch_on_launch": {
                "type": "boolean",
                "required": false,
                "label": "Ask scm branch on launch",
                "filterable": true,
                "default": false 
```

**Comment by unlikelyzero** [comment]
@adpavlov thank you for filing this. Please follow https://github.com/ansible/awx/issues/8788 for updates
