### ISSUE TITLE
Missing ring bell icon for approval nodes

### ISSUE THREAD

**Issue by adpavlov** [ansible/awx#8918]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.15
* Operating System: Mac OS
* Web Browser:

##### STEPS TO REPRODUCE

In previous versions there was a ring bell icon that showed active approvals
##### ACTUAL RESULTS
Such icon and functionality is missing in awx 16.0.0

**Comment by unlikelyzero** [comment]
@adpavlov there is now a new way of interacting with Workflow Approvals. Please check out the 'Workflow Approvals' listview. Please follow this ticket to track the implementation of the pending workflow approval count https://github.com/ansible/awx/issues/8918

**Comment by unlikelyzero** [comment]
@sugitk filed the same request here https://github.com/ansible/awx/issues/8273#issuecomment-743995148
