### ISSUE TITLE
waiting... indefinitely when deleting inventory source 

### ISSUE THREAD

**Issue by madeinoz67** [ansible/awx#892]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

When trying to delete an inventory source the spinning gear icon is displayed and no UI elements works, i.e. cant click on anything.

Only way out is browser back button, however source is not deleted.  Only way to remove is to remove the inventory

##### ENVIRONMENT
* AWX version: 1.0.2.303
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: 
     Client - macOS 
     server - centos-release-7-4.1708.el7.centos.x86_64
* Web Browser: 
safari 11.0.2 (13604.4.7.1.3
Chrome Version 63.0.3239.84

##### STEPS TO REPRODUCE

1.  from within any inventory that has a source

1.  click the delete button on the source to remove

1. confirm by clicking "delete"

1. spinning gear is displayed in lower right saying "working..."

  

##### EXPECTED RESULTS

1. source is removed from inventory

##### ACTUAL RESULTS

1. spinning gear and "Working" being displayed indefinitely

1. UI is blocked, i.e. cant click on anything, with the exception of the browser back button.

1. source is not removed

**Comment by bcbrockway** [comment]
Also getting this using v1.0.2.

**Comment by steaksauce-** [comment]
I have the same issue on AWX 1.0.2.307 using the docker installation method.

Additionally, I cannot use GUI to add playbooks to a workflow template

**Comment by madeinoz67** [comment]
can confirm that this is fixed in 1.0.2.327 version of docker image for me

**Comment by madeinoz67** [comment]
re-opened my mistake, this issues still appears to be be in 1.0.2.327

**Comment by matburt** [comment]
Can you grab the error from the browser javascript console?

**Comment by madeinoz67** [comment]
```
vendor.0466fc5a44f29b71da5b.js:570 TypeError: Rest.destroy(...).success is not a function
    at Object.deleteHosts (app.889b90db8980309457bb.js:29)
    at Scope.action [as promptAction] (app.889b90db8980309457bb.js:29)
    at fn (eval at compile (vendor.0466fc5a44f29b71da5b.js:570), <anonymous>:4:156)
    at callback (vendor.0466fc5a44f29b71da5b.js:570)
    at Scope.$eval (vendor.0466fc5a44f29b71da5b.js:570)
    at Scope.$apply (vendor.0466fc5a44f29b71da5b.js:570)
    at HTMLAnchorElement.<anonymous> (vendor.0466fc5a44f29b71da5b.js:570)
    at HTMLAnchorElement.dispatch (vendor.0466fc5a44f29b71da5b.js:29)
    at HTMLAnchorElement.elemData.handle (vendor.0466fc5a44f29b71da5b.js:29)
```

**Comment by madeinoz67** [comment]
just a note that the above error was in 1.0.2.337 docker image

**Comment by mabashian** [comment]
This should be fixed by https://github.com/ansible/awx/pull/971
