### ISSUE TITLE
Prevent users from selecting credentials that prompt for passwords on workflow nodes

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#8921]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
This is residual work from #8399.  If a Job Template references credentials that prompt for passwords then that template cannot be used in a workflow.  Additionally, if the JT prompts for credentials a user should not be able to select a credential that prompts for password(s).  Attempting to save this node will result in an error from the api.

![image (1)](https://user-images.githubusercontent.com/9889020/102362689-b16de600-3f82-11eb-9a23-2b06706a787f.png)

**Comment by AlexSCorey** [comment]
We need to do something similar for schedules

**Comment by tiagodread** [comment]
scenario from https://github.com/ansible/awx/pull/9210

- The credential password prompt is not being required on the schedule modal wizard:
1. Create a machine credential OR a vault credential with prompt enabled for password
2. Create a JT and mark Credentials as prompt
2. Create a schedule for this JT
3. On the Credentials step choose the credential created before (with prompt)

The step `Credential passwords` step to fill the credential password isn't displayed: 

![schedules7](https://user-images.githubusercontent.com/12464858/107773720-d54c6e80-6d1c-11eb-90bf-03099846dfdf.gif)

**Comment by mabashian** [comment]
Yea @tiagodread the credential password step shouldn't be shown in that case because the user shouldn't be able to select a credential that prompts for passwords on a schedule/workflow node.  We'll make sure to address that when working this issue.

**Comment by mabashian** [comment]
The UX in the old UI is pretty poor here:

<img width="1664" alt="Screen Shot 2021-02-24 at 1 13 34 PM" src="https://user-images.githubusercontent.com/9889020/109045918-29067280-76a2-11eb-962c-21fdf30d9ed0.png">

The row is selectable but the button stays disabled giving no indication as to why.

I think we should disable the row and add a tooltip explaining that JT's that have credentials that prompt for passwords are not permitted in workflow nodes.

**Comment by mabashian** [comment]
Note that the described case above is slightly different but related to credential password prompting.  We should fix both.

**Comment by mabashian** [comment]
Here's what we need to do here:

1) Prevent users from _selecting_ credentials that prompt for passwords on workflow nodes/schedules where credential is promptable
2) If a JT prompts for credentials and a default credential prompts for passwords then the credential must be replaced with one that does not prompt for password(s) in the schedule/wf node before it can be saved.
3) Prevent users from _selecting_ job templates on workflow nodes where credentials are not promptable and default credential(s) prompt for passswords

**Comment by tiagodread** [comment]
PR already merged, verified #8921 (comment) and #8921 (comment) did some exploratory testing around this feature and worked as expect.
