### ISSUE TITLE
JT Prompt Modal obscures pagination controls if resource is selected

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8923]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
JT Prompt Modal obscures pagination controls if item is selected. This MIGHT be specific to the Credential step in the wizard, but I'm filing generically. 

##### ENVIRONMENT
* AWX version: 12/16

##### STEPS TO REPRODUCE
1. Create a JT with Credential POL with at least 5 available Credentials
2. Launch JT
Note: modal obscures pagination view but is still usable after scroll

##### EXPECTED RESULTS
No need to scroll with simple use case of pagination in a modal

##### ACTUAL RESULTS
Need to scroll within a modal list to use pagination

##### ADDITIONAL INFORMATION
<img width="1288" alt="Screen Shot 2020-12-16 at 12 18 57 PM" src="https://user-images.githubusercontent.com/12446869/102383826-fa7d6480-3f99-11eb-93b4-b229fcf77807.png">

**Comment by AlexSCorey** [comment]
@unlikelyzero do you all still need this issue open?

**Comment by unlikelyzero** [comment]
@AlexSCorey sorry, will close!
