### ISSUE TITLE
[ui_next] template variable names are shown instead of values if there are no entities to show (Jobs, Templates, etc.)

### ISSUE THREAD

**Issue by itg-dave** [ansible/awx#8924]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.16
* Operating System: Debian 10 4.19.0-13-amd64
* Web Browser: Firefox 84

##### STEPS TO REPRODUCE

1. Install awx via docker-compose.
2. Open web-UI.
3. Click through Jobs, Templates etc.

##### EXPECTED RESULTS

The actual values of variables are shown.

##### ACTUAL RESULTS

The variable names like `{pluralizedItemName}` are shown.
 
##### ADDITIONAL INFORMATION

See attached screenshots.
<img width="814" alt="Screen Shot 2020-12-16 at 18 04 47" src="https://user-images.githubusercontent.com/19846542/102383829-4517d480-3fcc-11eb-9108-533c50562a53.png">
<img width="1121" alt="Screen Shot 2020-12-16 at 18 27 12" src="https://user-images.githubusercontent.com/19846542/102383896-5d87ef00-3fcc-11eb-803e-a902e42fbf81.png">

**Comment by jakemcdermott** [comment]
:wave: Hello, @Dave3o3. Thanks for creating this issue. The bug you're describing appears to be the same one as https://github.com/ansible/awx/issues/8884. Thanks to the great info from you and other community members, we've narrowed down the possible causes and are working on a fix for the next awx release.

We'll continue to track the remaining work for this bug in the other issue: https://github.com/ansible/awx/issues/8884
