### ISSUE TITLE
[ui_next] job view variables are printed instead of values.

### ISSUE THREAD

**Issue by itg-dave** [ansible/awx#8926]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.16
* Operating System: Debian 10 4.19.0-13-amd64
* Web Browser: Firefox 84

##### STEPS TO REPRODUCE

1. Install awx via docker-compose.
2. Open web-UI.
3. Click on Views -> Jobs

##### EXPECTED RESULTS

The actual values of variables are shown.

##### ACTUAL RESULTS

The variable names are shown.
 
##### ADDITIONAL INFORMATION

See attached screenshots.
<img width="1126" alt="Screen Shot 2020-12-16 at 18 26 07" src="https://user-images.githubusercontent.com/19846542/102384983-97a5c080-3fcd-11eb-96fa-b79e81712fae.png">
<img width="841" alt="Screen Shot 2020-12-16 at 18 34 36" src="https://user-images.githubusercontent.com/19846542/102384987-983e5700-3fcd-11eb-9567-cfbbb6961eb8.png">

**Comment by unlikelyzero** [comment]
@dagwieers what language is your browser set to? German?

**Comment by jakemcdermott** [comment]
:wave: Hello, @Dave3o3. Thanks for creating this issue. The bug you're describing appears to be the same one as https://github.com/ansible/awx/issues/8884. Thanks to the great info from you and other community members, we've narrowed down the possible causes and are working on a fix for the next awx release.

We'll continue to track the remaining work for this bug in the other issue: https://github.com/ansible/awx/issues/8884

**Comment by itg-dave** [comment]
> @dagwieers what language is your browser set to? German?

indeed, after setting to English, the issue disappeared
