### ISSUE TITLE
"User Details" on gui top far right-hand-side user icon pulldown, missing "#" from URL redirect 

### ISSUE THREAD

**Issue by ntlartey** [ansible/awx#8927]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

"User Details" on gui top far right-hand-side user icon pulldown, missing "#" from URL redirect 

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: openshift
* Ansible version:  2.9.15
* Operating System: centOS 8
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

1) do standard install
2) issue shows with admin user or any new user added subsequently

##### EXPECTED RESULTS

        Expected to see user details as shown correctly when selecting left hand side column 
        -> Users -> click user id 
                       -> click Details (column/tab)

##### ACTUAL RESULTS

get redirected to page:
       "Not Found
         The requested resource could not be found."

e.g URL = e.g. https://mytower.com/users/1/details.

##### ADDITIONAL INFORMATION

Problem is fixed by adding the missing # before the user context e.g. https://mytower.com/#/users/1/details.

**Comment by teebee** [comment]
Is there also a broken image (https://mytower.com/static/assets/logo-header.svg) displayed on the incorrectly redirected page?

**Comment by ntlartey** [comment]
No, I have customized logos under the media subpath. Why? Does this cause the issue I see? I don't see how logos could affect urls TBH.

**Comment by unlikelyzero** [comment]
@ntlartey thanks for filing this! This is a known issue. Please follow this ticket for updates https://github.com/ansible/awx/issues/8478
