### ISSUE TITLE
awx 16.0.0 licence missing

### ISSUE THREAD

**Issue by abdel-ops** [ansible/awx#8931]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
after awx 16.0.0 installation with local docker method , i got 403 return api when i try to launch any job with message licence is missing .

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method:  docker on linux,
* Ansible version:  2.9.9
* Operating System: centos 7.8
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Install awx 16.0.0 on docker linux , 
create a job template
launch job template

##### EXPECTED RESULTS

job launched

##### ACTUAL RESULTS
![image](https://user-images.githubusercontent.com/60286045/102409542-853c7e80-3fef-11eb-9cb8-43b398af7a5b.png)

**Comment by unlikelyzero** [comment]
@abdel-ops this looks familiar, however it is not readily reproducible.

Your error message implies that it's a Workflow. Can you give us so more details about the organization, inventory, prompting or credential so that we can reproduce this on our side?

**Comment by unlikelyzero** [comment]
@abel-ops try deleting the web container and tools_awx_1 and redeploy with docker-compose
