### ISSUE TITLE
Websockets defaults to wss when connecting unsecurely

### ISSUE THREAD

**Issue by garnser** [ansible/awx#8932]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When using AWX in a non-ssl environment with a http URL it still prefers using wss:// rather than ws:/ causing SSL termination issues towards the end-client.

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.15
* Operating System: CentOS 8
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Access the job view in your browser
2. In your console you'll find
`WebSocket connection to 'wss://<IP>:8080/websocket/' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR`

##### EXPECTED RESULTS

Looking through the code I would expect that the websocket should default to a non-ssl connection, however it seams like there's some defaults which is hardcoded to https and there's documentation lacking as to wether this is modifiable using ENV vars or AWX settings for BROADCAST_WEBSOCKET_PROTOCOL

##### ACTUAL RESULTS

Websocket connection defaults to SSL (wss://).

**Comment by jakemcdermott** [comment]
:wave: Hello! Thanks for creating this issue, @garnser 

I've merged a [patch](https://github.com/ansible/awx/pull/8877) for this bug to devel and it'll be included with the next awx release.
