### ISSUE TITLE
Missing Inventory Script

### ISSUE THREAD

**Issue by nvg14** [ansible/awx#8934]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Missing inventory script tab

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.6
* Operating System: Ubuntu
* Web Browser: Chrome

Hi,

I have recently installed the AWX through the docker-compose method.
In version 16.0.0 the functionality of dynamic inventory is unavailable.
In the left pane, the inventory script is missing.

Is this expected? If so, any plan to release this in the near future?

**Comment by nvg14** [comment]
I have seen the changelog of 8.0.0 - Deprecated /api/v2/inventory_scripts/ (this endpoint - and the Custom Inventory Script feature - will be removed in a future release of AWX)

Is this the reason?

**Comment by wenottingham** [comment]
Yes.
