### ISSUE TITLE
waiting... indefinitely when adding survey to template

### ISSUE THREAD

**Issue by madeinoz67** [ansible/awx#894]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

When trying to add a survey to any template the spinning gear icon is displayed and no UI elements works, i.e. cant click on anything.

Only way out is browser back button, however source is not deleted. 

##### ENVIRONMENT
* AWX version: 1.0.2.303
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: 
     Client - macOS 
     server - centos-release-7-4.1708.el7.centos.x86_64
* Web Browser: 
safari 11.0.2 (13604.4.7.1.3
Chrome Version 63.0.3239.84

##### STEPS TO REPRODUCE

1.  from within any template

1.  click the add survey button

1. spinning gear is displayed in lower right saying "working..."

1. All UI is blocked, only way out is browser back button.

  

##### EXPECTED RESULTS

1. survey workflow screen is displayed

1. survey can be created as per normal

##### ACTUAL RESULTS

1. spinning gear and "Working" being displayed indefinitely

1. UI is blocked, i.e. cant click on anything, with the exception of the browser back button.

**Comment by madeinoz67** [comment]
seems similar issue to https://github.com/ansible/awx/issues/892 and https://github.com/ansible/awx/issues/893

**Comment by shortsteps** [comment]
Still the same in 1.0.2.319

**Comment by madeinoz67** [comment]
can confirm that this has been fixed in v1.0.2.327 docker image and is working for me
