### ISSUE TITLE
Use the "Latest" tag for releases

### ISSUE THREAD

**Issue by hartman17** [ansible/awx#8940]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Please utilize tagging the latest release in Github when creating new releases. We are hitting the Github api to gather latest versions for our projects and we cannot use this for ansible/awx since there is no release tagged as "Latest"

**Comment by unlikelyzero** [comment]
Note: we'd also like to have this in QE

**Comment by wenottingham** [comment]
@Spredzy do you know how we'd automate this as part of the GH release process?

**Comment by ryanpetrello** [comment]
We'll address this in the next release of awx, thanks!

**Comment by ryanpetrello** [comment]
@hartman17

Latest release currently points at 16.0.0, thanks.

```json
curl -s https://api.github.com/repos/ansible/awx/releases/latest | head
{
  "url": "https://api.github.com/repos/ansible/awx/releases/36237426",
  "assets_url": "https://api.github.com/repos/ansible/awx/releases/36237426/assets",
  "upload_url": "https://uploads.github.com/repos/ansible/awx/releases/36237426/assets{?name,label}",
  "html_url": "https://github.com/ansible/awx/releases/tag/16.0.0",
  "id": 36237426,
  "author": {
```
