### ISSUE TITLE
Http requests /me and /config been made twice on refresh

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#8942]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Some pages, when you refresh the page the /me and /config requests are being made twice

##### STEPS TO REPRODUCE

1. Navigate to a page
2. Refresh the page reloading or force reload

##### EXPECTED RESULTS

The request for /me and /config not being executed twice

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/12464858/102522716-608aea00-4075-11eb-8b5c-ed9397c4243c.png)

**Comment by mabashian** [comment]
This should be addressed by https://github.com/ansible/awx/pull/10133

**Comment by akus062381** [comment]
this is fixed.
