### ISSUE TITLE
There is a strange ansible_ssh_pass problem

### ISSUE THREAD

**Issue by chenyulong021** [ansible/awx#8946]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### ENVIRONMENT
* Ansible version:  2.10.1
* Operating System: CentOS Linux release 7.7.1908 (Core)
* Web Browser:

##### STEPS TO REPRODUCE

my hosts config file is nginxhosts, one line of this file follow:
10.7.13.95 ansible_ssh_host=10.7.13.95 ansible_ssh_user=root  ansible_ssh_pass="7#5OX:~}44Zz"
afterwards I run command:
ansible  -i nginxhosts 10.7.13.95  -m raw -a "hostname " -vvv
##### EXPECTED RESULTS

ansible 2.10.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /opt/product-deploy/appmigration/nginxhosts as it did not pass its verify_file() method
auto declined parsing /opt/product-deploy/appmigration/nginxhosts as it did not pass its verify_file() method
Parsed /opt/product-deploy/appmigration/nginxhosts inventory source with ini plugin
META: ran handlers
<10.7.13.95> ESTABLISH SSH CONNECTION FOR USER: root
<10.7.13.95> SSH: EXEC sshpass -d11 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/4dd19e066e -tt 10.7.13.95 'uname -a '
<10.7.13.95> (5, b'', b'Permission denied, please try again.\r\n')
10.7.13.95 | UNREACHABLE! => {
    "changed": false,
    "msg": "Invalid/incorrect password: Permission denied, please try again.",
    "unreachable": true
}
##### ACTUAL RESULTS

first,I confirm the password 7#5OX:~}44Zz is correct. I can  manually connect 10.7.13.95 by ssh with this password.

##### ADDITIONAL INFORMATION

I have tried to change password of 10.7.13.95. There is a finding that if the  password start with  digit#  such as 7#5OX:~}44Zz  then the above error occured. 
I have tried to find solution from internet but i failed.I think that it is a bug maybe.

**Comment by wenottingham** [comment]
This issue tracker is for tracking feature enhancements and bugs to AWX itself.

This looks like a generic issue with either your playbook or Ansible itself. Try the mailing list or IRC channel for Ansible:

http://webchat.freenode.net/?channels=ansible
https://groups.google.com/forum/#!forum/ansible-project
