### ISSUE TITLE
"my view" is gone

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx#8947]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
after upgrading to AWX 16.0.0, "my view" is gone.

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  n/a
* Operating System: openSUSE Leap 15.2
* Web Browser: Firefox, any other

##### STEPS TO REPRODUCE

AWX used to have this "my view" page, has that been removed from 16.0.0 on purpose?

**Comment by jakemcdermott** [comment]
Hello!

Yes, we've permanently removed "My view" / "Portal mode". There was a lot of functional overlap between it and the dashboard. With the new tabbed lists on the dashboard, you can see a similar dual list view of recent jobs on the dashboard.
