### ISSUE TITLE
Hipchat certificate verification is ignored

### ISSUE THREAD

**Issue by btarraso** [ansible/awx#895]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Hipchat plugin (notifications)

##### SUMMARY
Hipchat is a way to create notificatons to the Tower Rest API. By not verifying that certificate, this could lead in a MiTM attack or most probably in an information leak.

##### ENVIRONMENT
* AWX 3.2.2 
* AWX 3.3.X (development)

##### STEPS TO REPRODUCE
Ideally, this line should actually verify the certificate by setting verify=True (currently the value is False):
https://github.com/ansible/awx/blob/devel/awx/main/notifications/hipchat_backend.py#L41

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A

##### ADDITIONAL INFORMATION
N/A

**Comment by matburt** [comment]
I think I set this because of issues with standalone Tower installs and self-hosted hipchat servers. I'm open to someone coming up with an elegant fix that supports self-signed certificates AND full certificate verification.

**Comment by ryanpetrello** [comment]
Probably not happening, HipChat is (soon to be) no more.
