### ISSUE TITLE
Workflow JT Annotations

### ISSUE THREAD

**Issue by mamercad** [ansible/awx#8954]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

It would be nice to have the ability to annotate Workflow Job Template (Nodes as well as Links), e.g., to provide a human-friendly description of the purpose of a Node, or, the reason why a link is set to "always".

**Comment by wenottingham** [comment]
This looks to be more or less https://github.com/ansible/awx/issues/4344 and #2032 .

Closing as duplicate.
