### ISSUE TITLE
Cannot run job template on fresh install

### ISSUE THREAD

**Issue by terra-nova** [ansible/awx#896]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

On a fresh install to local docker, I get an error when attempting to run a job on a newly created job template.

Error message in AWX UI:

```
Failed to get job template details. GET returned status: undefined
```

awx_web log:

```
[pid: 25|app: 0|req: 610/1551] 10.0.6.36 () {54 vars in 2333 bytes} [Thu Dec 28 09:42:33 2017] GET /api/v2/job_templates/9/launch/ => generated 726 bytes in 115 msecs (HTTP/1.1 200) 9 headers in 255 bytes (1 switches on core 0)
10.0.6.36 - - [28/Dec/2017:09:42:34 +0000] "GET /api/v2/job_templates/9/launch/ HTTP/1.1" 200 726 "https://ansible.foo.bar/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:57.0) Gecko/20100101 Firefox/57.0" "10.5.101.154"
10.0.6.36 - - [28/Dec/2017:09:42:34 +0000] "OPTIONS /api/v2/job_templates/9/launch/ HTTP/1.1" 200 5091 "https://ansible.foo.bar/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:57.0) Gecko/20100101 Firefox/57.0" "10.5.101.154"
[pid: 28|app: 0|req: 491/1552] 10.0.6.36 () {58 vars in 2431 bytes} [Thu Dec 28 09:42:34 2017] OPTIONS /api/v2/job_templates/9/launch/ => generated 5091 bytes in 145 msecs (HTTP/1.1 200) 9 headers in 256 bytes (1 switches on core 0)
10.0.6.36 - - [28/Dec/2017:09:42:34 +0000] "GET /api/v2/credential_types/ HTTP/1.1" 200 13569 "https://ansible.foo.bar/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:57.0) Gecko/20100101 Firefox/57.0" "10.5.101.154"
[pid: 25|app: 0|req: 611/1553] 10.0.6.36 () {54 vars in 2321 bytes} [Thu Dec 28 09:42:34 2017] GET /api/v2/credential_types/ => generated 13569 bytes in 146 msecs (HTTP/1.1 200) 9 headers in 257 bytes (1 switches on core 0)
```

Editing the job template through the web UI works.

The issue may be related to #875 (same error message).

##### ENVIRONMENT
* AWX version: 1.0.2.303
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: CentOS 7.4 x64
* Web Browser: Mozilla Firefox 57

##### STEPS TO REPRODUCE

- create new template for running an Ansible playbook from the project's Git repository
- attempt to run template through UI

##### EXPECTED RESULTS

Ansible playbook run is triggered

##### ACTUAL RESULTS

I get an error message

**Comment by madeinoz67** [comment]
same error being experienced.  

Further to the above:

Job template will fail if any "prompt at launch" options are selected. 

If all "prompt at launch" options are unselected job will run.

AWX version: 1.0.2.303
AWX install method: docker on linux
Ansible version: 2.4.2.0
Operating System:
Client - macOS
server - centos-release-7-4.1708.el7.centos.x86_64
Web Browser:
safari 11.0.2 (13604.4.7.1.3
Chrome Version 63.0.3239.84

**Comment by quenck** [comment]
It seems to be fixed in 1.0.2.327

**Comment by madeinoz67** [comment]
can confirm that is is now working for me in 1.0.2.327 docker image

**Comment by jakemcdermott** [comment]
I believe this is resolved - thanks for confirming, quenck and madeinoz67
