### ISSUE TITLE
User type auditor can try to add roles to a user 

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#8961]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
System auditors can navigate through Add roles wizard flow

##### STEPS TO REPRODUCE

1. Log in as auditor user
2. Navigate to Roles tab for this user
3. Click on Add button

##### EXPECTED RESULTS

The add button shouldn’t appear

##### ACTUAL RESULTS
![image](https://user-images.githubusercontent.com/12464858/102815235-d01d1400-43aa-11eb-81b3-452c3d408a9a.png)

**Comment by mabashian** [comment]
This was resolved by #9048
