### ISSUE TITLE
Job output page broken when navigating directly by URL

### ISSUE THREAD

**Issue by marshmalien** [ansible/awx#8962]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Job output page displays Not Found error when navigating via URL from one job output page to another job output page with a different job type.

![loading broken](https://user-images.githubusercontent.com/15881645/102817273-7bbf6780-439d-11eb-9b66-d5e2e5f3975c.gif)

##### STEPS TO REPRODUCE
1. Navigate to a playbook run job output page `/jobs/playbook/:jobId/output`
2. Update URL to a project update job output page `/jobs/project/:projectId` (do not include a trailing `/output`)
    * Refreshing the browser removes the error and successfully renders page

##### EXPECTED RESULTS
Job output page successfully renders with no error

##### ACTUAL RESULTS
Error 404 "Not Found" after network request to `/api/v2/project_updates/:jobId/events/?order_by=start_line&page_size=5`

**Comment by unlikelyzero** [comment]
No Unit Tests were added in the PR.

QE Coverage will need to be added for this route and the WFJT routes for completed jobs and jobs which are currently running

**Comment by one-t** [comment]
These items are already stubbed out and present in the backlog.
