### ISSUE TITLE
Workflow template nodes prompts to customize templates are missing 

### ISSUE THREAD

**Issue by jetxeberria** [ansible/awx#8965]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

On AWX 15.0.1 when we created a workflow template we could customize the tags of the nodes when we added them.  
On AWX 16.0.0 customizing tags of the nodes is no longer available
Workflow templates defined with AWX 15.0.1 and run with AWX 16.0.0 successfully applies the tags defined on the node.
Customizing nodes on a workflow is extremely useful for us as we've base templates whose behavior we tune via tags. Otherwise, we've to create a new template for each tag combination and create another workflow template to consume that customized node.

##### ENVIRONMENT

Not working environment:
* AWX version: 16.0.0
* AWX Install method: Docker on linux
* Ansible version: 2.9.15
* OS: Ubuntu 20.04
* Web browser: Firefox 84.0

Working environment:
* AWX 15.0.1
* AWX Install method: Docker on linux
* Ansible version: 2.9.15
* OS: Ubuntu 20.04
* Web browser: Firefox 84.0

##### STEPS TO REPRODUCE

Create a workflow template using as nodes templates that have tag prompt

##### EXPECTED RESULTS

When adding a new template node, prompt appears to answer for template customization tags

##### ACTUAL RESULTS

When adding a new template node, NO prompt appears to answer for template customization tags. i.e. template nodes can't be customized

##### ADDITIONAL INFORMATION

May this issue (https://github.com/ansible/awx/issues/5913) solve the problem? When will be released?

May be related with: https://github.com/ansible/awx/issues/8958

**Comment by unlikelyzero** [comment]
@jetxeberria thank you for filing this issue. That functionality was not yet ready for 16.0.0 and is now in devel https://github.com/ansible/awx/commit/20231041e60e83e4e79c6d0811219f0a31acc638 and will be available in the next release!
