### ISSUE TITLE
[RFE] Distribute license based on Organization level.

### ISSUE THREAD

**Issue by SWADESNA** [ansible/awx#8974]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

The Customer needs the license distribution control in Organization level.
As of now if license is available in tower, its automatically available to all organization by default.

Customer is looking for below scenario:
If OrgA buy 10 license then his 10 license should we allowed to used within the OrgA and not to other organizations

**Comment by wenottingham** [comment]
Hi -
This isn't relevant for AWX itself, and should probably be tracked in a downstream repo.
