### ISSUE TITLE
AWX 16.0.0 unable to launch templates

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/awx#8975]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

- Output is not shown when launching a template unless window tab is changed
- The prompt is closed when browsing through inventories in the prompt window

The interface is a step up and looking forward to the next releases with bug fixes.

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.15

**Comment by garnser** [comment]
The symptoms you're describing sounds similar to #8932.

Have a look in your browser console and see if you're seeing similar failures.

**Comment by unlikelyzero** [comment]
Thanks @nicolaibaralmueller for filing the issue. @garnser is right, you're likely hitting a known issue which will be available in the next release. I'll close this for now. If you find other reproduction steps, please re-open this issue or file another!
