### ISSUE TITLE
The ansible.tower.tower_workflow_job_template collections module does not create a survey when the spec includes a textarea parameter.

### ISSUE THREAD

**Issue by mrmibrown** [ansible/awx#8976]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The ansible.tower.tower_workflow_job_template collections module does not create a survey when the spec includes a textarea parameter.

##### ENVIRONMENT
* TOWER version: 3.8.0
* Ansible version:  3.9.15
* Operating System: RHEL v7.7
* Web Browser: Google Chrome v85.0.4183.83 (Official Build) (64-bit)

##### STEPS TO REPRODUCE
1) 
Install the ansible-tower collection:
  ansible-galaxy collection install ansible-tower-3.8.0.tar.gz -p ./collections/

2)
Create a sample playbook to test:
~~~
---
- name: WF template module checker
  hosts: localhost

  tasks:

  - name: Create Workflow Job Templates
ansible.tower.tower_workflow_job_template:
      name: My AutoWFtest
      description: This is my autowftest
      organization: Default
      survey_enabled: yes
      survey: {
            "question_name": "How do you feel?",
            "question_description": "",
            "required": false,
            "type": "textarea",
            "variable": "current_feelings",
            "min": 0,
            "max": 4096,
            "default": "",
            "choices": "",
            "new_question": true
        }
      state: present
      validate_certs: no
      tower_host: {{ twr_host }}
      tower_password: {{ twr_password }}
      tower_username: admin
~~~

##### EXPECTED RESULTS

The workflow job template will be created along with the survey.

##### ACTUAL RESULTS

Only the workflow job template is created.

##### ADDITIONAL INFORMATION
The workflow is created but the survey spec which includes the textarea parameter is ignored

**Comment by wenottingham** [comment]
See https://github.com/ansible/awx/issues/8945#issuecomment-748326229, this isn't a valid survey spec.
