### ISSUE TITLE
Cant open running job in new tab from workflow view by right click on job block

### ISSUE THREAD

**Issue by dimorozoff** [ansible/awx#8978]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Cant open running job in new tab from workflow view by right click on job block
##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: 
* Ansible version:  2.9.15
* Operating System: win 7
* Web Browser: chrome/firefox

##### STEPS TO REPRODUCE
1. Launch workflow
2. move to workflow visualizer
3. right click on running of finished job block
4. "Open in new tab" is missing from the dropdown menu.

##### EXPECTED RESULTS
"Open in new tab" presented in the dropdown menu for running or finished jobs in running or finished workflow visualizer

**Comment by unlikelyzero** [comment]
@dimorozoff Thanks for filing this issue! It sounds like you've encountered an existing issue which is already tested and fixed in devel. https://github.com/ansible/awx/issues/8881 Please look out for the next awx release to see if the problem persists

**Comment by unlikelyzero** [comment]
@dimorozoff thank you for filing this issue! This is actually a consequence of a functionality which is under active development. To track that work, please follow and subscribe to this issue! https://github.com/ansible/awx/issues/8374
