### ISSUE TITLE
Workflow job template credentials

### ISSUE THREAD

**Issue by stahloss** [ansible/awx#8981]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
We have a situation where we want to deploy a large set of services to a specific namespace on Openshift. Ultimately, this will involve starting a single workflow template will start a large amount of workflow jobs which in turn will start jobs what have default credentials set. This default credential is not the one we need to use at the workflow level.

We know the current approach is to set the credentials per workflow node, but his is going to be a cumbersome task for our really big composite workflow scenario. Not to mention these workflows can be launched concurrently.

Therefore we'd like to issue this feature request to add the option of specifying credentials at the workflow template level, that will be used recursively and atomically for all jobs launched by this workflow.

Related issue: #881

**Comment by wenottingham** [comment]
-> #7859
