### ISSUE TITLE
Collection: generate error if job template survey is rejected

### ISSUE THREAD

**Issue by t-readyroc** [ansible/awx#8986]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
When creating a job template (or workflow job template) via the collection, generate an error if the template's associated survey spec is rejected.

Current behavior is to silently pass ("changed") while the survey is not added. Any malformation in the survey spec will result in the survey not being created along with the template, however, no error is presented to the end user.

**Comment by t-readyroc** [comment]
See #8987 for what led me to create this issue.

**Comment by wenottingham** [comment]
This would help with things like https://github.com/ansible/awx/issues/8945 and  https://github.com/ansible/awx/issues/8976
