### ISSUE TITLE
maven_artifacts module artifacts download issue with -bin-tar.gz extension from nexus repository

### ISSUE THREAD

**Issue by Git-Durgesh** [ansible/awx#8989]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY
maven_artifacts module artifacts issue- how do we download any artifacts with -bin-tar.gz extension from nexus repository

A small query, how we can use extension for this type of artifacts artifact_name-version-bin.tar.gz while downloading the artifacts from nexus by using maven_artifacts module in ansible playbook
- name: Download a WAR File to the Tomcat webapps directory to be deployed
  community.general.maven_artifact:
    group_id: com.company
    artifact_id: web-app
    extension: war
    repository_url: 'https://repo.company.com/maven'
    dest: /var/lib/tomcat7/webapps/web-app.war

i want to pass extension like -bin.tar.gz 

##### ENVIRONMENT

* Ansible version:  2.x

##### ADDITIONAL INFORMATION

Normally we pass extension like jar, war,zip so whatever thing we add as extension in maven_artifacts it append with dot extension. I tried with dest option as well but we need to specify the extension like -bin.tar.gz because it would accept only jar.

So how do we download maven artifacts with extension like -bin.tar.gz with ansible

**Comment by wenottingham** [comment]
This issue tracker is for tracking feature enhancements and bugs to AWX itself.

The issue you filed appears to be in an Ansible module itself, and should be filed at https://github.com/ansible-collections/community.general.
