### ISSUE TITLE
Add ability to disable SSL/HTTPS for websocket

### ISSUE THREAD

**Issue by pfrayer** [ansible/awx#8993]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
When running AWX with several nodes (instance groups), it could be nice to add the ability to disable SSL/HTTPS for websocket communication between nodes.

Here is an overview of my setup:
![awx](https://user-images.githubusercontent.com/7125014/103521923-dff02a00-4e79-11eb-9e68-a33dc93e60a7.png)

- I run several AWX instances on different nodes, running through `docker-compose`. My instances are grouped as an instance group
- Each node has a `nginx` server, listening on port `80`
- On top on all these nodes, I have a load balancer that manage my SSL/HTTPS configuration, listening on port `443`

This setup works. The only issue I have with it is the websocket communication between my nodes: as this websocket communication always try to use SSL/HTTPS, it fails as my nodes don't have it and don't listen on `443` (it is managed on the load-balancer side).

It can be seen on the AWX logs:

```
WARNING  awx.main.wsbroadcast Connection from node01.awx.mycompany.com to node02.awx.mycompany.com timed out.
```

In the `settings.py` configuration file, it could be nice to have something like:

```python
WEBSOCKET_PORT = 80
WEBSOCKET_SSL = False
```

If you have any other proposal that could work with this kind of setup (where SSL can't be managed on AWX nodes directly), I'm also open for it :)
Thanks !

**Comment by ryanpetrello** [comment]
@pfrayer,

Do these give you what you want?

```
BROADCAST_WEBSOCKET_PORT = 80
BROADCAST_WEBSOCKET_VERIFY_CERT = False
```

**Comment by pfrayer** [comment]
Hello @ryanpetrello 

Yes it does ! I didn't knew these settings exist. Are they documented somewhere ? 

Anyway thanks a lot, websocket broadcast works in my setup now :+1:
