### ISSUE TITLE
AWX 16.0.0 UI not auto refreshing job output

### ISSUE THREAD

**Issue by dimovstanimir** [ansible/awx#8994]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Once I launch a template job the output of the job is not refreshing automatically and I need to click multiple times refresh so I can track the status of the job. Even if the job has finished I am not getting a single output line unless I refresh the browser.

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.6(ansible --version, but in AWX about page says 2.9.15)
* Operating System: Ubuntu 20.04 LTS
* Web Browser: Chrome

It stays stuck like you can see in the attached screenshot unless I refresh the browser.

![image](https://user-images.githubusercontent.com/29769671/103532903-ca3c2e00-4e94-11eb-9ffd-20209c16e03b.png)

**Comment by unlikelyzero** [comment]
@dimovstanimir  Thanks for filing this issue! It sounds like you've encountered an existing issue which is already tested and fixed in devel. #8881 Please look out for the next awx release to see if the problem persists. Feel free to reopen this issue or file another

**Comment by dimovstanimir** [comment]
> @dimovstanimir Thanks for filing this issue! It sounds like you've encountered an existing issue which is already tested and fixed in devel. #8881 Please look out for the next awx release to see if the problem persists. Feel free to reopen this issue or file another

Thanks for the fast response John. I'll try with the next release and see if it happens again.

By the way, do you know when is the new release expected?

**Comment by unlikelyzero** [comment]
@dimovstanimir not sure. I'd just subscribe to the github releases subscription service to find out. Are you set up to autodeploy on awx release changes?

**Comment by dimovstanimir** [comment]
> @dimovstanimir not sure. I'd just subscribe to the github releases subscription service to find out. Are you set up to autodeploy on awx release changes?

No and I don't know how to setup for the autodeploy of awx release changes.

Can you walk me through it?

**Comment by dimovstanimir** [comment]
Guys the same issue is also present in AMX version 17.0.1.

Just wanted to let you know that.

There are even other issue opened related to the newest release - check here https://github.com/ansible/awx/issues/9242 .

**Comment by lorenzgith** [comment]
Also in 18.0.0!!

**Comment by tobsome** [comment]
Any updates here?

**Comment by shanemcd** [comment]
Please follow along at https://github.com/ansible/awx/issues/9747
