### ISSUE TITLE
Changes required for Ansible playbook to use custom AWX docker image

### ISSUE THREAD

**Issue by cnukwas** [ansible/awx#8997]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

I see mention of docker_registry_repository to pull and push images to docker or other private registry, but don't see any information on how to pull AWX images from a private registry other than public docker hub registry.

We're setting up AWX but unable to build our own docker images for Kubernetes environment since our network is very restrictive and running into all kinds of issues when Ansible tries to build npm, pip, nodejs and other software.
So I gave up building our own AWX docker image after multiple attempts. At the end our requirement is to be able to add LDAP utilities, jq, wget, and few other custom utilities and use that image instead of docker hosted AWX image.

I created a simple Dockerfile as below and able to create an image with jq, wget, and gcc just to prove that it's working,
Now how do I make use of this image instead of the default AWX docker image for Kubernetes deployment. I am aware of workaround where I can modify Kubernetes runtime deployment configuration to use a different image and registry and let Kubernetes pull AWX image from there, but would like to know if there is a better way than this.

````
FROM ansible/awx:16.0.0

USER root
RUN dnf install -y jq
RUN dnf install -y wget
RUN dnf install -y gcc
````

Any ideas on what changes need to be made to achieve this?

Thanks

**Comment by ryanpetrello** [comment]
Hey @cnukwas,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by cnukwas** [comment]
Sure, not seeing much traction there, will still give a try or go with a workaround.

**Comment by cnukwas** [comment]
Found out that it's actually very simple to use a different AWX image. This is what I did and it's working fine in Kubernetes cluster.

Created an image as mentioned below with base AWX image, tag and push that image to internal private registry.

```
FROM ansible/awx:16.0.0
USER root
RUN dnf install -y jq
RUN dnf install -y wget
RUN dnf install -y gcc
```
After that all I had to do was update awx/installer/roles/kubernetes/defaults/main.yml with following changes and leave following inventory entries as is.

inventory file:
```
dockerhub_base=ansible
dockerhub_version=latest
```
awx/installer/roles/kubernetes/defaults/main.yml changes:
```
kubernetes_awx_version: "16.0.0"
kubernetes_awx_image: mydockerregistry.com/myteam/awx"
```

Added entry for secret to be used by awx serviceaccount during Kubernetes deployment as part of imagePullSecrets that's required to pull images from a private registry.

kubernetes_image_pull_secrets: myimagepullsecret

Run Ansible playbook as we do after making above changes and you should see correct images being used for AWX.

This helps us to use new AWX releases without much hassle and not lose existing AWX projects, Orgs, Teams, etc.. since those are saved in PostgreSQL DB. I guess we have to deal with that situation when we update the DB but should work fine since the DB data is stored on a mounted NFS drive, instead of the local Kubernetes worker node.
