### ISSUE TITLE
UI: Cannot Add/Edit/View Custom Inventory Scripts

### ISSUE THREAD

**Issue by gmtime** [ansible/awx#8999]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Until 15.0.1 it was possible to add and manage Custom Inventory Scripts. After upgrading to 16.0.0 there seem to be no way to add/view/edit custom scripts.

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Operating System: Linux
* Web Browser: any

##### STEPS TO REPRODUCE

1. login into AWX
2. go to Inventories
3. click in "Add" to create new inventory
4. provide "Name" and click on "Save" button
5. click on "Sources"
6. click on "Add" to add new source
7. provide "Name" 
7. click on "Source" and choose "Custom Script"
8. click on "Save" (not working)

##### EXPECTED RESULTS

1. clicking on "Save" should work (should create new source)
2. should be able to add/edit/view custom script

##### ACTUAL RESULTS

1. "Save" button does nothing
2. Not possible to add/edit/view custom script

**Comment by AlexSCorey** [comment]
@gmtime Inventory Scripts was deprecated in the new UI but is still available via the API.  However, we do plan to deprecate them in the API as well.
