### ISSUE TITLE
Error during SCM Update - getpwuid(): uid not found: 1000

### ISSUE THREAD

**Issue by mrjoshuap** [ansible/awx#90]
### Summary

I've performed an installation of AWX on OpenShift (specifically using minishift w/CDK & DevSuite) following the installation guide.  I am able to successfully login, add credentials, create projects and navigation seems to work properly.

However, when I attempt to update the SCM for a project, it fails with an error about uid 1000 not found.

I've not tried any other tasks -- primarily because all of my playbooks, inventory scripts and other useful bits are in my SCM.

### Environment

* AWX version: 1.0.0.286
* Ansible version:  2.3.1.0-1
* Operating System: CentOS Linux release 7.3.1611 (Core)
* Web Browser: Chrome 60.0.3112.113 (Official Build) (64-bit)

### Steps To Reproduce:

* Perform install of AWX on OpenShift
* Add Credentials
* Add Project and SCM
* Try to update SCM

### Expected Results:

I would expect the project to be checked out properly, however, it is not.

### Actual Results:

```
Using /etc/ansible/ansible.cfg as config file

PLAY [all] *********************************************************************

TASK [delete project directory before update] **********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'getpwuid(): uid not found: 1000'
fatal: [localhost]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```

**Comment by matburt** [comment]
That's interesting. Minishift/OpenShift will usually randomize the uid and I was accounting for that in the OpenShift role

**Comment by mrjoshuap** [comment]
@matburt I will add that this is a duplicate of #89 so if we want to close this one, @geerlingguy has done more investigation.
