### ISSUE TITLE
Add python-etcd library to official build

### ISSUE THREAD

**Issue by akcrisp** [ansible/awx#900]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - Installer

##### SUMMARY
Using etcd as a inventory source errored (python-etcd library not found) until I pip installed python-etcd into the awx task (also added it to web) containers.

##### ENVIRONMENT
* AWX version: 1.0.1
* AWX install method: docker on linux
* Ansible version:  2.4.1.0-1
* Operating System: RHEL 7.4
* Web Browser: Chrome

**Comment by matburt** [comment]
We have a plan for adding external libraries in the future. For the moment you'll need to add it to the image and build it on your own.
