### ISSUE TITLE
Ability to include openssl certs for things like ldaps

### ISSUE THREAD

**Issue by akcrisp** [ansible/awx#901]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI
 - Installer

##### SUMMARY
In order to use ldaps - we need to install custom certs in the awx web container. It would be good if the installer provided a documented method for allowing this either via loopback mount to underlying docker host or being able to specify files in the inventory for inclusion.

##### ENVIRONMENT
* AWX version: 1.0.1
* AWX install method: docker on linux
* Ansible version:  2.4.1.0-1
* Operating System: RHEL 7.4
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Attempt to configure ldaps in UI. Fails to connect until ssl certs present.

You can manually fix this "on the fly" by doing -

docker cp RootCa.pem <container>:/RootCa.pem
docker exec -it <container> /bin/bash
cp /RootCa.pem /etc/pki/ca-trust/source/anchors/
update-ca-trust extract

**Comment by derekmwright** [comment]
+1

I've also gotten around this by using a Dockerfile that builds from the awx_web/task containers on Docker Hub and moves the CA Trust into place, example:

```
FROM docker.io/ansible/awx_web:1.0.1.316
USER root
ADD http://path/to/ca/trust/ca-trust.pem /etc/pki/ca-trust/source/anchors/
RUN [ "chmod", "0644", "/etc/pki/ca-trust/source/anchors/ca-trust.pem" ]
RUN [ "/usr/bin/update-ca-trust" ]
USER 1000
```

Then build and push this image to a local registry (OpenShift) instead

**Comment by shanemcd** [comment]
If this is still a problem, please open an issue at http://github.com/ansible/awx-operator
