### ISSUE TITLE
User can add multiple Vault Credentials with same Vault ID to job template

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#9014]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
A user can end up with a job template that has multiple vault credentials that have the same vault ID.

##### ENVIRONMENT
* AWX version: 14.1
* AWX install method:  docker for mac
* Ansible version:  2.9.16
* Operating System:Mojave
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create 2 vault credentials with different vault IDs.  Add them both to a job template.  Save job template.  Edit 1 of the vault credentials so that it has the same vault id as the other.  Go back to the job template form or details view.

##### EXPECTED RESULTS

Not sure.  Some sort of warning or icon or something.  @trahman73 what would you expect the UX to be here?

##### ACTUAL RESULTS
See that those credentials are still attached to that job template

##### ADDITIONAL INFORMATION

![vault](https://user-images.githubusercontent.com/12464858/103770751-45bced00-5005-11eb-8584-739f9f4e7328.gif)

**Comment by jakemcdermott** [comment]
Discussed w/ the api team. Current plan is to make the vault-id non-editable, like we do for credential type.

**Comment by harshakhmk** [comment]
Can I work on this issue?

**Comment by rebeccahhh** [comment]
@harshakhmk we welcome contributions at any time. :)
