### ISSUE TITLE
UI: Clicking on "Management Jobs" gives blank page

### ISSUE THREAD

**Issue by ghost** [ansible/awx#9015]
ISSUE TYPE
Bug Report
SUMMARY
Clicking on "Management Jobs" in the left corner gives blank page.

ENVIRONMENT
AWX version: 16.0.0
AWX install method: docker on linux
Operating System: Linux
Web Browser: any
STEPS TO REPRODUCE
login into AWX
click on the Management Jobs in the left corner

EXPECTED RESULTS
Management Jobs menu

ACTUAL RESULTS
Empty page

ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/8328746/103754601-3a71bd80-5015-11eb-8348-ec86b6c42ad6.png)

**Comment by jakemcdermott** [comment]
Hello! The code for the management jobs view hasn't been merged into devel yet, but will be soon. It'll be added in one of the upcoming AWX releases.

see: https://github.com/ansible/awx/issues/8488

**Comment by andrewsav-bt** [comment]
@jakemcdermott it appears that is' not just the view, those jobs do not seem to run at all after upgrade to 17.0.1. Could you please confirm?
![chrome_PKK5eQSDBu](https://user-images.githubusercontent.com/27190911/106544520-8bb99200-656c-11eb-8e4f-cf49ab0146cc.png)

No "Next run" value to be seen.
