### ISSUE TITLE
Observability and metrics - Broadcast metrics to all Tower nodes

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#9020]
AWX currently exposes Prometheus metrics. Any node in AWX can serve the same set of metrics. It is not required to hit each AWX node in order to get the complete metrics picture. In order to continue with this pattern, every node will need to know every other nodes metric data.

Luckily we already have a mechanism for exchanging data between AWX nodes, the websocket broadcast backplane. https://github.com/ansible/awx/blob/devel/awx/main/routing.py#L31 A new route can be created to facilitate this metric data exchange. _Maybe_ the existing broadcast route can be reused and channel groups can be leveraged to separate the traffic. Data gotten from this channel should be saved to Redis. Data should be broadcast over this channel on same sane interval (1 - 5 seconds)

**Comment by ryanpetrello** [comment]
Closing, cc @kdelee @fosterseth
