### ISSUE TITLE
Harden admin login security

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/awx#9030]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
awx: 16.0.0

Considering that:
1. admin username cannot be changed or removed and replaced by another system administrator with a random username only known to the legitimate system admin
2. admin password can be potentially cracked with a brute-force attack

I propose to harden the security of the admin login process by:
1. limiting the number of unsuccessful logins with a configurable value
2. adding some MFA options such as:
- security key
  + FIDO: U2F
  + FIDO2: WebAuthn & CTAP
- authentication app such as Google authenticator

**Comment by wenottingham** [comment]
This is what integration into a 3rd-party IDP is for; that way these restrictions (and others) can be set and controlled at an organization level for all users.

**Comment by jean-christophe-manciot** [comment]
One of us is missing something:
- I am fully aware of the 3rd party IDP integration possibility with AWX.
- But how do you control access at the same time to the "Welcome to Ansible AWX! Please Sign In." login page?

**Comment by wenottingham** [comment]
I'm not sure what you mean by that.

For configured IDPs (LDAP, SAML, etc), all the login handing (lockout, password complexity, 2FA, etc) are implemented in the IDP.  For web-based methods (OAuth, SAML) the login page redirects to those IDPs. For password-based methods (LDAP), the password is checked, and the IDP can refuse for whatever reason it wants to.
