### ISSUE TITLE
Add support for AWS Session Manager

### ISSUE THREAD

**Issue by piotrplenik** [ansible/awx#9031]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Add AWS Session Manager library to establish connection to EC2 Windows and Linux Instances. 

##### Documentation:

 - https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager.html
 - https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html

**Comment by wenottingham** [comment]
Repeating comment from the PR: 

We are unlikely to add this to the base image unless https://docs.ansible.com/ansible/latest/collections/community/aws/aws_ssm_connection.html is moved to the core supported set of connection plugins.

In the future, when execution environments are available (https://github.com/ansible/awx/issues/5157), this would be the sort of thing that would go into an execution environment that you'd use.

**Comment by mabashian** [comment]
Now that execution environments are available I'd recommend going down that route to support this functionality.
