### ISSUE TITLE
Implement PostgreSQL event partitioning for better performance and manageability

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#9039]
Users of awx are storing increasingly large amounts of event data (which are emitted any time an Ansible playbook, inventory, or any other automation unit is run).  Currently, events are stored in a set of tables by category, which by default grow in a fairly unbounded way:

```sql
main_adhoccommandevent
main_inventoryupdateevent
main_projectupdateevent
main_systemjobevent
main_jobevent
```

Over time, our largest users have begun to encounter growing pains managing this data.  A number of critical components of AWX interact with these tables.  For example:

1.  Parallel playbook runs write into these tables potentially at very high rates.  As table size grows over time, it becomes increasingly time and disk consumptive to maintain very large B-Tree indexes for important columns on these tables.

2. A number of internal ORM properties utilize these tables to determine if a Job is "finished" (e.g., `UnifiedJob.event_processing_finished`).  Even though we employ indexes for many of these queries, performance is affected when you venture into the realm of billions of rows, and if you're running these queries with any regularity (which can happen on certain stdout views).

3. Various APIs are available, and used by the UI to drive the display of historical job output.  This is almost exclusively the type of access that is indexed by a specific Job identifier (i.e., show me all the events for Job XYZ, sorted by e.g., line number).  This too can be extremely expensive at large scale: https://github.com/ansible/awx/issues/7405.
 
4. Event data can optionally be collected (and shipped to third party services) via AWX's analytics gathering framework.  This is generally done in large chunks, which can be expensive to read from large, long-lived tables.

5.  Cleaning up this data is also expensive and time consuming, because it involves indexed queries and bulk updates against tables that are actively being written to.  Additionally, deleting large chunks of singular tables requires periodic table vacuuming, which is also very expensive at this scale.

Moving to PostgreSQL 12 will *help*, because there have been some notable optimizations, especially in index utilization and query planning.  However, that's likely just a band-aid.  All of these operations become increasingly more expensive and time consuming as these tables continue to scale in an unbounded way into billions or tens of billions of rows.

This data is very much _write-once_ (in other words, it's almost never modified after the fact).  To alleviate some of these concerns, we'd like to explore introducing PostgreSQL table partitioning for these tables, so that we can segment this data into more manageable, logical partitions:

https://www.postgresql.org/docs/12/ddl-partitioning.html

> Query performance can be improved dramatically in certain situations, particularly when most of the heavily accessed rows of the table are in a single partition or a small number of partitions.

> When queries or updates access a large percentage of a single partition, performance can be improved by taking advantage of sequential scan of that partition instead of using an index and random access reads scattered across the whole table.

> Bulk loads and deletes can be accomplished by adding or removing partitions, if that requirement is planned into the partitioning design. Doing ALTER TABLE DETACH PARTITION or dropping an individual partition using DROP TABLE is far faster than a bulk operation. These commands also entirely avoid the VACUUM overhead caused by a bulk DELETE.

> Seldom-used data can be migrated to cheaper and slower storage media.

Because of how PostgreSQL partitioning works, I don't foresee any significant changes we'll need to make to the ORM and/or API (because from Python's perspective, `main_jobevent` is just a table - it doesn't need to be aware that under the hood, there's partitioning going on).

Specifically, we'd like to:

1.  Develop an approach for automatically partitioning these tables on some reasonable interval.  Given the scale of datasets we've encountered with users, we think "hourly partitions" makes the most sense.  This work will involve:

    a.  Introducing some mechanism for discovering and automatically creating "the next hour's partition", or creating it as necessary at insertion time as a last-ditch effort.  This must be something that is robust enough to gracefully handle failure and ensure that necessary partitions are always created.  We'll likely need to select _a column_ to partition on; we may need to introduce a new column to represent this new partition key, because I don't think we currently have anything that represents "the day" or "the hour" the event was created.

    b.  We might want to explore out-of-the-box solutions like https://github.com/pgpartman/pg_partman, but I expect it may be overkill for our needs, and cumbersome to configure as a PostgreSQL extension in our entire matrix of supported platforms.  @Ladas also has some direct experience with this in his ongoing Analytics work in a _very_ similar stack - let's discuss it with him 😄

2.  Implement a strategy for migrating existing data.  This *may* be as simple as taking all pre-upgrade data and placing it in one default "initial" partition, with the idea being that _over time_, new data will begin to become partitioned, and that going forward, performance gains will be observed for *that* data.  I'm unclear on the mechanics of taking an *existing* table and replacing it with partitions.  There will likely be some sneaky progressive schema changes in a Django migration.  We'll also need to make sure we understand what the cost of this migration is at scale (much like our previous migration of the primary key to a `bigint`, we'll need to solve this in a way that results in minimal downtime).

3.  Change our approach to how we clean up old event data in our cleanup System Jobs.  I envision an approach where we actually have some configurable option of dropping all partitions over a certain "age".  In this way, users can have event data auto-partitioned into per-hour tables, and they can periodically drop old partitions.  We can also set some sane default e.g., "only keep two weeks of event data".  This approach will be *notably* more performant than the current cost of cleaning up old events in one giant, long-running table (we also won't have to deal w/ the vacuum cost of large table deletes, because we're just deleting entire partitions at once).

4.  Rethink how we gather and ship this data in our analytics framework.  It's very likely that we'll move to an approach where instead of running a periodic (every four hour) query to fetch data, we instead track the _last partition_ we shipped, and next time, we just ship whichever partitions haven't been sent.  This idea can be expanded on further as part of https://github.com/ansible/tower/issues/4478 (cc @Ladas @jbradberry)

5.  Given that event data is almost exclusively accessed in the context of its relationship to a playbook/automation run, I'd like to completely remove the global `/api/v2/job_events/` view, as it's extremely expensive to utilize at high scale, doesn't have much utility, and its primary use case is _maybe_ monitoring total events in the system (and polling an API to monitor for new event data is a bad idea).

A critical part of succeeding in this endeavor will involve implementing this solution and then also verifying it for very large scale data sets to ensure that we've seen improvements for the use cases described above.

**Comment by ryanpetrello** [comment]
related issues:

https://github.com/ansible/awx/issues/6680
https://github.com/ansible/tower/issues/4693

**Comment by ryanpetrello** [comment]
One open question is "what do we partition on".

There is an upper limit to **total** partitions where we start to lose some of the benefits of partitioning.  So we wouldn't want to e.g., partition by minute, or partition by something that had the potential to grow in a large, unbounded way, like the ID of the job itself.  Partitioning on dates also makes some sense, because many of our operations on this data is date-based (e.g., "send recent event data to analytics", and "clean up data that's older than X days")

One thought we had was to take the *creation date* of the job, and partition on some new denormalized column on the event table, which effectively represents "hours since epoch".

For example, if a job starts at 1:00, and another job starts at 1:20, and both jobs run for 4 hours, all of their events for both jobs will end up in the "1:00 to 2:00 partition".  In this way, given that we generally access events *based on their job*, we know all the events for a certain job will always be in the same partition.

Partitioning by hour ranges also gives us a reasonable upper bound on partition size - we certainly have users that generate and manage billions of events, but they generate this scale of data over _days or weeks_, not _hours_.

One challenge of per-hour partitions is that we have to be very sure we properly pre-create the partition ahead of time (via some scheduled background process), or (as a last-ditch effort) via some type of trigger (or potentially a query we actually run when periodically as events are inserted).

**Comment by ryanpetrello** [comment]
cc @psuriset @jhutar

**Comment by Ladas** [comment]
@ryanpetrello 

**ad 1)** I am experimenting with declarative partitioning, which should be able to use any timestamps (I am using just dates now)

so something like:
```sql
CREATE TABLE main_jobevent (
    job_created timestamp NOT NULL,
    --- other cols
) PARTITION BY RANGE (created);

CREATE TABLE IF NOT EXISTS main_jobevent_20200101_00
PARTITION OF main_jobevent
FOR VALUES FROM ('2019-01-01 00:00:00') TO ('2020-01-01 00:01:00');

CREATE TABLE IF NOT EXISTS main_jobevent_20200101_01
PARTITION OF main_jobevent
FOR VALUES FROM ('2020-00-01 00:01:00') TO ('2019-01-01 00:02:00');

-- some cron job can be creating hourly partitions for the future
```

We can put here any ranges, for analytics I was thinking about making the ranges dynamic, based on introspection. The idea is that for small customer we should have partitions with bigger intervals (or ideally just 1 table really) for bigger customers we would have partitions for smaller intervals. This would make it a bit harder to identify partition tables to drop (to keep e.g. only last 2 weeks) We'd need to parse the expr from e.g. 
```sql
select relname, pg_get_expr(relpartbound, oid) from pg_class where relispartition and relname~'main_jobevent' order by relname;
```

**ad 2)** I think we could rename  existing `main_jobevent`, then use the `bigint` migration job approach to copy data to the new partitioned table (just last 2 weeks?), while the new events would be inserted into the new partitioned tables.

**ad 3)** detach partition and drop table should be blazing fast (although detach partition might require exclusive lock, I'd need to check, it should be still super fast though). Then there is no need need for vacuuming of the deleted records

https://www.postgresql.org/docs/12/ddl-partitioning.html#DDL-PARTITIONING-DECLARATIVE-BEST-PRACTICES

**ad 4/5)** Right, so here we'll need to gather all the queries we run on the event tables and decide on partitioning key based on that

The basic idea is that we'll need to use the partitioning key in every `where` condition, to get the benefits, otherwise the query can get very slow. E.g. if we'd partition by `job_created` timestamp that we'd put into events table, then:

`select * from main_jobevent where job_created='2020-00-01 00:01:23'::timestamp AND job_id=XY limit 20` should query just the 1 partition `FOR VALUES FROM ('2020-00-01 00:01:00') TO ('2019-01-01 00:02:00');`. And it will use sequential scan or job_id index scan based on how much data planner think we'll need to go through.


But if we'd just do `select * from main_jobevent where job_id=XY limit 20`, the query will become way slower than if we wouldn't use partitioning. For 14 days our hourly partitions it would have to do 14x24=336 sequential/index scans. It will do it in parallel based on amount of available parallel workers, but it will still be way slower than 1 table sequential/index scan (which can be parallelized too)

-------------------

That being said, the `job_created` should go well for fetching job's events (given we'd drop `/api/v2/job_events/`). It should work well for inserts, since we have the job_id, we can easily join to jobs table to get the timestamp. And it should work well for dropping events, if we will also drop jobs older than 2 weeks. 

But for analytics, this might be tricky. Since the approach of: `send all events bigger than last timestamp or primary id` would scan all partitions. I forgot if we're updating job timestamp after we insert all events? In that case, we could use a min(job_created) timestamp of changed jobs (from the last timestamp), to limit what partitions to look on, still using the last event primary key value. (I think)

**Comment by jhutar** [comment]
I think we most frequently access the data via `job_id=XY`, so what about partitioning by that?

**Comment by jhutar** [comment]
You Ladas and Ryan have much bigger insight into this, but for me, I think we lack some way how to measure a success here (well, this sounds like first chapter of "How to become a PM in 100 easy steps" book). What about defining some benchmark? If we have some, we can help with measuring different variants.

I was thinking about something like:

1. Populate the table with this file and measure time: 1B of rows like `INSERT INTO main_jobevent ...` - to measure writes to the table
2. Run ANALYSE on the table - this should not be needed in real world, only needed in our case when we created the table content quickly in previous step
3. Read events for every job ID and measure, i.e. lots of `SELECT * FROM main_jobevent WHERE job_id=...` - this would be simulate read perf
4. Dump content of the table with `COPY ...` - this would be to simulate how AA reads from the table
5. Delete and vacuum empty space in same way as Tower is used to delete old data - this would be to check how deleting part of the data performs

And we could add much more tests here, but if we have this, we can benchmark multiple solutions on DB level (maybe even with Tower down) and compare with current implementation. It would not be exact (we would be talking directly to the DB so actual queries might be different than what Tower uses), but still, we would have at least some number to compare.

CC @mcharanrm

**Comment by ryanpetrello** [comment]
@jhutar 

> I think we most frequently access the data via job_id=XY, so what about partitioning by that?

This would likely result in too many partitions for Postgres to handle (some users run tens or hundreds of millions of jobs over time).

**Comment by ryanpetrello** [comment]
@Ladas thanks for your comment, it’s very helpful.  Regarding creating new partitions, one thought I had was maybe we could do partition creation *when a job is created*.  In other words, when we know a job’s creation date, we could use e.g., an advisory lock to make sure the appropriate ranged partition for that hour existed.  In this way, we’d only create partitions we needed; if you ran zero jobs over a weekend, you wouldn’t needlessly be left with 48 empty partitions.

In terms of managing partitions (deciding what to ship to Analytics, deciding what to clean up periodically) I’m sure there’s got to be some way PostgreSQL-specific way (some table with metadata) to introspect partitions based on their range, and discover “old” ones.  I expect this to be fairly manageable considering that we’re probably taking about at most thousands of partitions for most use cases (24 hour intervals x 365 days = ~8800 partitions).

**Comment by ryanpetrello** [comment]
@jhutar 

Yep, I think we’ll want to set up environments with 1B+ events and measure the timing of some of these outlined use cases as you suggested, and then compare the same operations in the new version with *new* data that’s partitioned hourly e.g.,

1. Prefill 1B+ events with some ~old creation date.
2. Run a new job and measure event write latency, measure API responsive for events associated with that job.
3. Measure perf of analytics gather, and ensure that the perf issues we’ve seen in the past are alleviated.
4.  Migrate to new partitions, run a new job, and repeat 1-3 above and compare.

One thing we may want to consider is putting together a more natural dataset generated over days, and using either a DB backup/restore or image snapshot to represent the database (because generating this data is very time consuming, and we also likely want to verify our performance against data that matches real world usage).

Another thing to point out - on our first pass at this problem, I don’t care _as much_ about the performance of *old* data.  I think it’s fully possible that most/all pre-upgrade data goes in its own very large “default” partition.  Examining and re-partitioning a dataset of billions of rows is going to be very slow and expensive, and given the data retention most of our users have been subject to for awhile (our largest users run cleanups very regularly cc @gamuniz), my opinion is that our best initial approach is probably to improve performance of new inserted data (or perhaps only partitioning data from some reasonable timeframe on upgrade, like the last few days). In any event, we can explore this as follow-on work, but my first priority is optimizing *new* events as they’re created to ensure that it actually yields the performance benefits we’re hoping to see.

**Comment by gamuniz** [comment]
@ryanpetrello in my experience users which utilize awx at scale are only interested in current failures with minimal historical dataset. Currently job events captured from ansible itself are very verbose and can turn a 2kb output file into a 10mb job events entry. So they're shipping those logs into an aggregator rather than paying the storage cost twice, they clean up the database regularly(1 or 2 weeks of data). All this is to say that I'd bet users would be okay with speedier performance in the inserts and not worry about older historical data being slightly slower to fetch.

**Comment by Ladas** [comment]
@jhutar yeah, we'll need to benchmark we're making the queries faster. So far @ryanpetrello was just trying to design it the way we think we'll be faster.

The test cases you're mentioning make sense. We should just repeat with 2B, 4B, 8B, etc. And crosscheck with number of partitions existing.

Btw, I was originally looking at this benchmark, seeing how many partitions I should be counting with as max (it's pg11 vs pg12) https://www.2ndquadrant.com/en/blog/postgresql-12-partitioning/

**Comment by jhutar** [comment]
Hello @ryanpetrello I did not meant one partition per `job_id`, but range of sat 1k `job_id`s per partition. Something like:

```
CREATE TABLE main_jobevent (
    job_id integer NOT NULL,
    --- other cols
) PARTITION BY RANGE (job_id);

CREATE TABLE IF NOT EXISTS main_jobevent_1
PARTITION OF main_jobevent
FOR VALUES FROM (0) TO (1000);

CREATE TABLE IF NOT EXISTS main_jobevent_2
PARTITION OF main_jobevent
FOR VALUES FROM (1001) TO (2000);
```

This should provide important performance boost for queries with `WHERE job_id=XY` compared to partitions partitioned by `created` day.

**Comment by ryanpetrello** [comment]
@jhutar that's an interesting idea, too, and worth exploring.  We really have two sets of main queries we do here.

"Show me all events for job X" ---> job output
"Give me recent events on <interval> so I can collect/ship metrics/delete them".  ---> analytics/cleanup

We'd still have to be careful that we sized the ranges properly, though - I've seen users with tens or hundreds of millions of jobs, and if we get the partition size wrong, that's still a lot of partitions.  Going with hourly partitions might give us more confidence that we won't create a ton of partitions unexpectedly.

**Comment by ryanpetrello** [comment]
@jladdjr the last time we looked at the bigint migration, the `ALTER TABLE` operation was prohibitively expensive (https://github.com/ansible/awx/issues/6010#issuecomment-589027945).  @Ladas has pointed me at some new pg11+ features that suggest adding a _new_ column with a default might actually be fairly painless:

https://dataegret.com/2018/03/waiting-for-postgresql-11-pain-free-add-column-with-non-null-defaults/

@jladdjr in terms of a first pass at migration, this is sort of what I currently have in mind:

1.  Preload a large number of events in the current table.
2. Experiment with how long it takes to add a new datetime column on which we'll partition.  This column might be called `job_created` or similar, but will represent the denormalized datetime of the associated job/project update/whatever.

If step 2 is sufficiently fast for large data sets, we can probably come up with a migration that replaces the current tables with new ones, each of which have a *default* partition on a range like:  `(5 years ago, now)` and we could shovel the *old* data into that default partition.  We'll need to research and experiment on the most efficient way to take an existing table and convert it to a single partition setup.

```sql
CREATE TABLE main_jobevent_legacy PARTITION OF main_jobevent
    FOR VALUES FROM ('2018-01-01') TO ('YYYY-MM-DD 9:00')
    IF NOT EXISTS;
```

The idea is that *after* upgrade, you'll have a `main_jobevent` and one default partition, and all the old data will be in that partition.  Going forward, any new jobs - _as they are created_ - will check for the need for a new partition and create it if necessary, e.g.,

```sql
CREATE TABLE main_jobevent_NNNNN PARTITION OF main_jobevent
    FOR VALUES FROM ('YYYY-MM-DD 09:00') TO ('YYYY-MM-DD 10:00')
    IF NOT EXISTS;
```

Maybe the `NNNNN` here could be some deterministic "hours since epoch", e.g.,

```python3
>>> (job.created - datetime.datetime(1970, 1, 1)).total_seconds() //  3600
447257.0
```

**Comment by jladdjr** [comment]
> in terms of a first pass at migration, this is sort of what I currently have in mind...

@ryanpetrello - sounds good. Spinning up an environment now to run some tests on the migration scenarios outlined here.

**Comment by ryanpetrello** [comment]
@jladdjr here's a previous migration that shows some examples for monkeying with the database _without_ explicitly using the ORM (issuing raw queries):

https://github.com/ansible/awx/blob/devel/awx/main/migrations/0113_v370_event_bigint.py#L6

**Comment by Ladas** [comment]
so I've been checking if the default partition could be good and also what we need to do to attach partition without need of a sequential scan, check section ATTACH for default https://www.postgresql.org/docs/12/sql-altertable.html

so if we would do
 1. rename main_job_event to main_job_event_partition_default
 2. create new parent partition table table main_job_event
 3. add job_created with default value to main_job_event_partition_default
 4. add unique index to main_job_event_partition_default (same as for the parent table, should be unique index for cols  (job_created, job_id, id)   ) and make sure there are the same indexes as on the parent table --> as written in doc link above, we need to avoid the sequential scan that can happen as part of attaching
 5. attach the  main_job_event_partition_default as default partition of main_job_event
 6. create hourly partitions and after x weeks, drop the default partition (edited) 

-----

So everything should be fast, except adding the new unique index, right? On huge tables, this might force us to rather copy the data in batches. (we'll need to measure it)

As for the default partition, PG will insert there if the job_created doesn't match any partitions and I'd expect that it would scan that default partition for every query we do. So it will probably act similar to <-4 years, now> partition, but using this defined interval would skip the partition scan for the new jobs, which sounds better.

**Comment by kdelee** [comment]
@michaeltcoelho @appuk heads up this is supposed to happen slowly over the course of several months. There will be impact on the analytics bundle generated, and we'll want your involvement

**Comment by chrismeyersfsu** [comment]
PR https://github.com/jladdjr/awx/pull/18

**Comment by kdelee** [comment]
This is now merging and has been extensively tested. I think we are ready to close unless you have anything to add @jladdjr @chrismeyersfsu in which case you can re-open

**Comment by kdelee** [comment]
https://github.com/ansible/awx/pull/10023#pullrequestreview-676468175 has the mergit label, closing

**Comment by AlanCoding** [comment]
related, also merging now https://github.com/ansible/awx/pull/10373
