### ISSUE TITLE
How to import role tags to awx?

### ISSUE THREAD

**Issue by zyayun** [ansible/awx#9042]
##### ISSUE TYPE
 - I hava exist some ansible role,I want to import tags of role to awx。Please help me,How to do ？

**Comment by ryanpetrello** [comment]
Hey @zyayun,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
