### ISSUE TITLE
awx.awx.tower_export returns empty inventory

### ISSUE THREAD

**Issue by natman** [ansible/awx#9051]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Module awx.awx.tower_export returns empty inventory when inventory source are associated.

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker on linux
* Ansible version: 2.10.4
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE
Create an inventory
Associate some inventory source
Configure playbook with that task:

- tower_export
    inventory: 13
  register: result
- debug: var=result
returns an empty string while the inventory does exist.

##### EXPECTED RESULTS

inventory details.

##### ACTUAL RESULTS

Empty string

##### ADDITIONAL INFORMATION

The result is not empty anymore when there is no source inventory configured for the same inventory.
Any other module parameters work as expected.

**Comment by wenottingham** [comment]
@jbradberry is this what https://github.com/ansible/awx/pull/9046 is for?

**Comment by jbradberry** [comment]
> @jbradberry is this what #9046 is for?

Yeah, exactly.  I had thought that the old tool filtered these out, but it seems to not be the case.
