### ISSUE TITLE
dialog box doesn't appear for credentials with "Prompt on launch" 

### ISSUE THREAD

**Issue by AndreiBanaru** [ansible/awx#9055]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
We have machine credentials configured with **Prompt on launch** for password.
When executing a template we don't get a dialog box in order to input the password, In turn we receive a 400 error:
![image](https://user-images.githubusercontent.com/38393163/104213621-cc732f00-5436-11eb-86ea-21678db41167.png)

And in developer mode inside Chrome:
![image](https://user-images.githubusercontent.com/38393163/104213787-fa587380-5436-11eb-8f59-531ce9ff782b.png)

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.15
* Operating System: RHEL 7.8
* Web Browser: Chrome 87.0.4280.88

##### STEPS TO REPRODUCE

1. Create credentials. Set type to Machine. Type in the Username. Select Prompt on launch for Password and Privilege Escalation Password. Hit Save.
2. Create a job template. Choose an Inventory, a project and a Playbook. Select Prompt on launch for Credentials for Limit. Hit Save.
3. Execute the template just created. Select the credentials created at step 1. Configure the limits. Hit Launch.

##### EXPECTED RESULTS

A dialog box should pop up and ask for credentials.

##### ACTUAL RESULTS

400 error
![image](https://user-images.githubusercontent.com/38393163/104214567-e103f700-5437-11eb-8a1d-7538cac073dc.png)

**Comment by unlikelyzero** [comment]
Thank you for finding and filing this issue! We are following the development of this functionality in this ticket: https://github.com/ansible/awx/issues/7015 . Please subscribe to that issue to keep up with the fix!
