### ISSUE TITLE
Observability and metrics - metrics dashboard

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#9056]
We want to view the metrics we expose. Ideally, we don't require there to be a Prometheus instance gathering the prometheus data that we expose in order to get a basic view of Tower metrics. We want a view of graphs that can display the basic prometheus data types: Counter, Gauge, Histogram over time. Over time means that when the dashboard is opened, the metrics will be gathered either from the exposed prometheus endpoint or from a special websocket group that we add. No data will be loaded from the past.  If the dashboard is refreshed, the metric history is lost and starts over.

The dashboard will be useful for debugging a problem or suspected problem live.

Once https://github.com/ansible/awx/issues/9012 and https://github.com/ansible/awx/issues/9019 land the UI will have something to consume.

**Comment by unlikelyzero** [comment]
@chrismeyersfsu can you help me understand when work might begin on the ui component

**Comment by mabashian** [comment]
@unlikelyzero I'll try to explain as best as I understand it.  @chrismeyersfsu can probably provide more color.  The basic idea is that there will be a `metrics` endpoint that the UI can periodically query.  The ask here is for us to build a single page that displays a graph.  The data used to populate that graph will come from polling that metrics endpoint on some interval.  It'll be our responsibility on the client to store the necessary data and update the graph.  There's no storage mechanism on the backend.  If the user refreshes the page, they start with a fresh, empty graph.  As we poll that endpoint, the graph will update.  The user also needs the ability to select which field on that endpoint they want to see graphed so there will probably be a dropdown somewhere (akin to the dashboard graph dropdowns).

**Comment by wenottingham** [comment]
Copying some discussion from the meeting:
- This needs to be somewhere in the UI, and RBAC'd so only system admins see it (it's not part of any other user persona)
- Logically, this is part of managing the cluster. The other part of the UI that fits here is Instance Groups, so it fits alongside/with that.

cc @trahman73 for ideas on how to organize this, as either another menu item or a new combo menu item.

**Comment by trahman73** [comment]
This makes sense to live under the Admin menu subset as a stand alone page. The page can contain a filter toolbar component with the graph component underneath.

**Comment by chrismeyersfsu** [comment]
@mabashian On top of basic plotting. It's looking like we are going to need at least a `division` operator. For example, we have two related metrics `events_inserted` and `time_to_insert_events_total`. We want to be able to visualize events inserted per second over time, which would be `events_inserted` / `time_to_insert_events_total`.

Another useful feature would be aggregating the same metric across multiple hosts. This gives us the health of the subsystem rather than just the individual host.

**Comment by wenottingham** [comment]
> The dashboard will be useful for debugging a problem or suspected problem live.

This is where I'm stuck.

If this is only useful for "people who understand the metrics as much as API engineering does to determine what's good/bad and what's going on", it doesn't go in the UI - it goes in an awx-manage command that can be run and dumped somewhere.

**Comment by wenottingham** [comment]
Chatted with @chrismeyersfsu - I think for the first iteration of this we'll have it as a non-default route that can be accessed by knowing the proper URL (not linked). 

For the division, I think instead we'll just have the derived metrics here https://github.com/ansible/awx/issues/9019#issuecomment-777632056 directly graphable (rather than having the user choose to derive them).

**Comment by AlexSCorey** [comment]
Removing my name this issue was resolved with https://github.com/ansible/awx/pull/9776
