### ISSUE TITLE
Display tags for job execution on job page

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#9060]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

In the new UI I don't see a way to see the tags that a project update was launched with. This was previously available in the details section.

**Comment by mabashian** [comment]
Note that this comes from the `job_tags` attribute on unified jobs.

**Comment by tiagodread** [comment]
PR already merged, we can safely close this issue when https://github.com/ansible/tower-qa/pull/5968 was merged.
