### ISSUE TITLE
Enabling analytics gathering causes unnecessary activity stream noise

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#9064]
1.  Turn on analytics gathering, and set a low gather interval.
2.  Every time gather runs successfully, we get a new activity stream record:

<img width="871" alt="image" src="https://user-images.githubusercontent.com/214912/104342130-81096100-54c8-11eb-94f2-4762737ab521.png">

**Comment by ryanpetrello** [comment]
see: https://github.com/ansible/awx/pull/9063

**Comment by kdelee** [comment]
We are NOT recording this any more -- works for me. Thanks
