### ISSUE TITLE
RFE: Add Inventory Reporting Capability to AWX/Tower/AAP

### ISSUE THREAD

**Issue by harrytruman** [ansible/awx#9067]
##### ISSUE TYPE
AWX/Tower has the ability to store inventory details and cached inventory facts. But given the tendency for new Ansible users to start their automation journey with inventory management, there are limited features that allow those facts/vars to be viewed or exported in any formal capacity.

##### SUMMARY
For anybody who is already managing inventories and caching facts, a basic, customizable “inventory report” would allow users to easily pick and choose the hosts and associated facts/vars that are already being retrieved and cached. Currently, this repo is one of the most frequently used tools by new users who want a basic inventory report:
https://github.com/network-automation/ansible_inventory_report

**Comment by wenottingham** [comment]
What is the goal of this report - what are you looking to see?

There is API based export, that is also available with the CLI and the module collection.h

**Comment by blomquisg** [comment]
@harrytruman if you have more details, feel free to re-open this request.
