### ISSUE TITLE
AWX 16.0.0 : Unable to sync my vcenter dynamic inventory

### ISSUE THREAD

**Issue by ghost** [ansible/awx#9072]
ISSUE TYPE

- Bug report

SUMMARY

Upon upgrading from 9.0 to 16.00 I no longer able to sync my vcenter dynamic inventory objects within the GUI after creating new VMs on VMware.

ENVIRONMENT

- AWX version: 16.0.0
- AWX install method: docker
- Ansible version: ansible-2.9.15
- VMware : vCenter 6.5
- Operating System: Debian 10
- Web Browser: Chrome, Firefox

STEPS TO REPRODUCE

When running the job for vmware inventory sync the job is failling after creating several VMs on VMWare :
```
[WARNING]:  * Failed to parse /tmp/awx_11590_n0ivhtow/vmware_vm_inventory.yml
with auto plugin: Could not template any hostname for host, errors for each
preference: config.name + "_" + config.uuid: 'config' is undefined
```
I precise "after creating VMs on VMware" because before this action, inventories was fine.

ALREADY TRIED

Change "Source variables by alias_pattern: "{{ config.name }}" in existing inventory
Change "Source variables by alias_pattern: "{{ config.uuid }}" in existing inventory
Create a new inventory with no "Source variables"
Create a new inventory with "alias_pattern: "{{ config.name }}" in Source variables"
Create a new inventory with "alias_pattern: "{{ config.uuid }}" in Source variables"

Similar to this bug : https://github.com/ansible/awx/issues/7052

**Comment by w4hf** [comment]
hello @damienreyre 
I see you closed this issue. Did you found the root cause ?
I'm having a very similar issue and I'm interested in the solution.
Thanks.

**Comment by ghost** [comment]
Hello @w4hf
I didn't find a solution about its problem.
I used regex for looking for my VMs (Host Filter).

Cheers
