### ISSUE TITLE
Checkboxes and status boxes look identical at start

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#9074]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

In the new UI the status box icon (the thing that turns red/green) is very close in size to the checkboxes. If there is any lag between something like a project sync request and its start the status box can appear like a second checkbox. Should we go back to the circles or something else to distinguish them?

**Comment by mabashian** [comment]
We show the status differently now:

<img width="170" alt="Screen Shot 2022-04-04 at 8 31 27 PM" src="https://user-images.githubusercontent.com/9889020/161655257-85483308-a10a-4bb4-ba1d-bfbfb4b8ea4d.png">

I think we can close this
