### ISSUE TITLE
project collections containing git collections fail to install

### ISSUE THREAD

**Issue by haught** [ansible/awx#9076]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When using a project from git that has collections from git the syncing fails

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker
* Ansible version:  2.9.16, 2.10.4 custom_env
* Operating System: Linux
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Have a git project containing
collections/requirements.yml
```yaml
---
collections:
  - name: https://github.com/ansible-collections/community.network.git
    type: git
    version: main
```
manually installing works fine: ```ansible-galaxy collection install -r collections/requirements.yml -p collections```

syncing project fails with error below

##### EXPECTED RESULTS

AWX will pull in collections from git

##### ACTUAL RESULTS

```
ERROR! Collection artifact at &apos;/var/lib/awx/.ansible/tmp/ansible-local-1358p3f_xw4a/tmp8w7_acap/community.network9yd8511k.git&apos; is not a valid tar file.
```

##### ADDITIONAL INFORMATION

The reason I am doing this is to pull in my own internal github repo that also fails in the same way but that can't be reproduced by you. Pulling in ```- name: cisco.ios``` and others works fine - just the git ones in a collection are failing. Roles from git work fine.

**Comment by wenottingham** [comment]
-> #9075
