### ISSUE TITLE
Allow hosts sourced from dynamic inventory to be manually disabled

### ISSUE THREAD

**Issue by ghost** [ansible/awx#908]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Add functionality to allow the on/off host enabled flag to be set manually in the Tower inventory hosts display for hosts that were sourced from an external dynamic inventory, overriding the flag set in the inventory sync.

##### ENVIRONMENT

* AWX version: 1.0.1

##### STEPS TO REPRODUCE

This change would allow hosts to be manually excluded from job runs, according to a manual action in the UI without requiring a change to the inventory source data.

**Comment by wwitzel3** [comment]
You could make a Smart Inventory for the job run that would exclude the undesired hosts.

**Comment by wenottingham** [comment]
I believe this was changed in a later AWX release. Please try with AWX 19 or later and re-file if it's still an issue.
