### ISSUE TITLE
RFE:  Add counter that indicates how many messages have been dropped for external logging

### ISSUE THREAD

**Issue by hiyokotaisa** [ansible/awx#9080]
Related: #8576

##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
We need some sort of a counter that indicates how many messages have been dropped as described below. This will alert us to immediately check what the issue with rsyslogd or Logstash is happening at that time.

In reviewing the PR for the external logging fix (https://github.com/ansible/awx/pull/7292) I noticed that when there is a BlockingIOError (or a ConnectionRefused) error encountered that the log message is just dropped. This makes sense so that the dispatcher processes (or other processes) don't hang waiting for rsyslog to be available again. The issue that arises is that there is no indication when external logging messages are being dropped. 

This can have impacts as the external logging is used for information requests (such as GDPR requests).

To help avoid this silent dropping of messages it would be good to have metrics keep a counter that is incremented every time a log message is dropped. Maybe have a "dropped external logger message" category that has sub counts for messaged dropped because of blocked I/O and connection refused. 

Having the metrics available would allow for an alerting system (such as Grafana) to create an alert/notification when AWX is having a problem sending messages to the external logger.

**Comment by chrismeyersfsu** [comment]
Our use of rsyslog is fire and forget, from AWX's perspective. You can hook into watching `/var/log/tower/rsyslog.err` to gather external logging failures.

**Comment by blomquisg** [comment]
The best we could hope to do here is send an error to stderr.

**Comment by sugitk** [comment]
Can we configure `/var/lib/awx/rsyslog/rsyslog.conf` in order to be more stable?
For example, `queue.saveOnShutdown="on"` is effective? 

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/configuring-a-remote-logging-solution_configuring-basic-system-settings#configuring-remote-logging-over-tcp_configuring-a-remote-logging-solution

**Comment by suryarao67** [comment]
May I know what information is/will be logged to /var/log/tower/rsyslog.err when messages are dropped and is logged as what log category?

**Comment by ryanpetrello** [comment]
@chrismeyersfsu @suryarao67 

`/var/log/tower/rsyslog.err` is specific to the `omhttp` module if you're shipping logs via http/s (it doesn't support tcp/udp).

It generally logs connection issues and HTTP-level errors rsyslogd may encounter while attempting to ship logs to e.g., ELK, Splunk, etc...  If rsyslogd _isn't running_, you're not going to see errors in `/var/log/tower/rsyslog.err`.

**Comment by wenottingham** [comment]
See https://github.com/ansible/awx/issues/8505, this is a duplicate.
