### ISSUE TITLE
Private key new line missing cause "invalid format" when playbook trying to use it

### ISSUE THREAD

**Issue by lkthomas** [ansible/awx#9082]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I was trying to follow the setup jump host by creating a new credential type on AWX, but after ran by injector from the new credential type, the private key last went missing, this cause ssh failed and resulting in an "Invalid format" error; I managed to copy the key which created by the job and diff it against my working private key, both key looks the same, but only missing new line:

```
diff awx-failed.key working.key
8c8
< -----END OPENSSH PRIVATE KEY-----
\ No newline at end of file
---
> -----END OPENSSH PRIVATE KEY-----
```

Does the guide missing a step to add a new line or it's actually AWX bug?

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker on Linux
* Ansible version:  2.9.14
* Operating System: Ubuntu
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

The guide that I followed: https://developer.ibm.com/recipes/tutorials/multiple-jumphosts-in-ansible-tower-part-1/#r_step2

1. Create a new credential type
2. insert private key
3. try to use that new key on the playbook
4. error showing as "invalid format"

##### EXPECTED RESULTS

The private key should parse correctly with a new line

##### ACTUAL RESULTS

ssh invalid format error appears

##### ADDITIONAL INFORMATION
![image](https://user-images.githubusercontent.com/581053/104576260-ed37c080-5692-11eb-8861-4a35c9486a94.png)

**Comment by wenottingham** [comment]
It's a ssh-add limitation, we can't fix it in AWX. Only happens for certain types of keys. See https://github.com/ansible/ansible-runner/issues/544#issuecomment-719004397
