### ISSUE TITLE
Inventory not passing Source Variables to Inventory Scripts

### ISSUE THREAD

**Issue by Mercwri** [ansible/awx#9092]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Running the VMware Inventory script it does not appear to accept Source Variables to define the created hosts.

##### ENVIRONMENT
* AWX version: 16.0.0.
* AWX install method: kubernetes
* Ansible version:  2.9.15
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE
Create Inventory
Add vsphere source
Define source variables eg.
  `alias_pattern: "{{config.name}}"`
Run Sync

##### EXPECTED RESULTS
Inventory names to populate as the guestnames in Vsphere eg:

some-vm

##### ACTUAL RESULTS
Default Behavior of the script occurs and the names are imported as

some-vm_UUID

**Comment by wenottingham** [comment]
That is an option for the old inventory script, which is not used. The inventory source needs configured as described here: https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vm_inventory_inventory.html
