### ISSUE TITLE
Please document how to install older versions of AWX

### ISSUE THREAD

**Issue by enscogit** [ansible/awx#9096]
##### ISSUE TYPE
 - Documentation improvement

**Comment by shanemcd** [comment]
@enscogit  We don't support installing older versions of AWX. We recommend folks to use the latest version and to upgrade often, as it is a fast-moving project with no long term support.

**Comment by enscogit** [comment]
I require the ability to use LDAP for authentication. From what I can tell, the current (latest) version does not have the authentication configuration forms portion of the interface completed. How do I configure LDAP auth in the latest version without using the interface?
