### ISSUE TITLE
Job output not being updated in awx 16.0.0

### ISSUE THREAD

**Issue by momcilo78** [ansible/awx#9105]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Launching Template job results in Output tab not being updated. Switching to different tab (Details) and back results in output to be shown.

Not sure if this is the result of new UI, and if this issue is local just to myself.

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.10.4
* Operating System: Centos 8
* Web Browser: Firefox, Edge

Note: I could not test in chrome due to the javascript crashing with "TypeError: Yx(...).flatMap is not a function" on frontpage.

##### STEPS TO REPRODUCE

1. Run job
2. Wait for output
3. Job completes without output being displayed
4. Click Details
5. Click Output, output gets displayed

##### EXPECTED RESULTS

Output displayed as progressing the execution.

##### ACTUAL RESULTS

No output even if job is complete.

##### ADDITIONAL INFORMATION

* Firefox console displays following message: Firefox can’t establish a connection to the server at wss://localhost/websocket/. 
* WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.

Is there an additional port that needs to be opened? In my case I have create a VM that is NAT-ed (need to piggy-back through VPN to reach the target), and to access the awx web interface I use the port forwarding on ports 80/443.

**Comment by ryanpetrello** [comment]
Hey @momcilo78,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by momcilo78** [comment]
Hey @ryanpetrello. Please reconsider: I am not looking for support for the installation, but as part of the smoke test to prove that awx 16.0.0 and ansible 2.10.4 can work together, I noticed that in all 3 browsers new UI does not work without errors. I gather that you did notice this with 16.0.0 and its stock images based on ansible 2.9.15?
