### ISSUE TITLE
A pull option for execution environments

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#9109]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Scenario:

I have an execution environment that targets some `:latest` image on quay.io. The image has a bug, I run a job, and it fails. The bug is fixed, and someone uploads a new version of that imate.

AWX needs a way for the user to force the worker node to refresh the image from the registry.

Earlier we discussed a `pull` field for the `ExecutionEnvironment` model (@jbradberry started on the model change), but right now I don't see mention of this in any other existing issues.

This would be an important feature gap, but it's not necessarily planned for the initial roll-out of execution environments.

**Comment by shanemcd** [comment]
I thought we had this on the EE branch? Did it get removed at some point? I would love to see this in our initial effort.

**Comment by jbradberry** [comment]
> I thought we had this on the EE branch? Did it get removed at some point? I would love to see this in our initial effort.

Uh, you removed it.

**Comment by AlanCoding** [comment]
Let's talk about the full implementation.

https://github.com/ansible/ansible-runner/blob/3d4a6c2ac42bdf0669feed19cdd6f9800ec9f57d/ansible_runner/runner_config.py#L846-L847

Maaaybe this would be achieved by the ansible-runner setting `container_options=['--pull']`?

EDIT: this was wrong, keep reading...

**Comment by shanemcd** [comment]
@jbradberry Wasn't it in the wrong place?

Edit: I remember now: your original implementation put it on the mix-in, which we decided against. We still need to add this option at the EE level.

**Comment by shanemcd** [comment]
I remember now: your original implementation put it on the mix-in, which we decided against. We still need to add this option at the EE level.

**Comment by shanemcd** [comment]
@rebeccahhh This should be pretty easy to add. Can you look into this if you have time this week?

**Comment by shanemcd** [comment]
@AlanCoding According to the man pages for podman/docker:

```
--pull string                    Pull image before running ("always"|"missing"|"never") (default "missing")
```

So I think we would want `--pull=always`.

**Comment by AlanCoding** [comment]
wouldn't you want to give all the options? What if someone wanted to populate the cache manually and use "never" for security reasons?

To set expectations of how this operates, I experimented with this locally:

```
time podman run --rm --tty --interactive quay.io/ansible/ansible-runner:devel whoami
time podman run --rm --tty --interactive quay.io/ansible/ansible-runner:devel whoami --pull=always
time podman run --rm --tty --interactive quay.io/ansible/ansible-runner:devel whoami --pull=always
time podman run --rm --tty --interactive quay.io/ansible/ansible-runner:devel whoami --pull=always
```

I started with a stale image.
 - The first one ran in 0.5 seconds
 - Next command ran in 30 seconds
 - every time after that took 1-2 seconds

So it looks like "always" is isn't completely dumb, and a pretty sensible option. I think it checks the repo that the layer checksums are correct. It might almost make sense for it to be the default.

**Comment by tiagodread** [comment]
The pull option was already added on UI

**Comment by gstorme** [comment]
This is only working if the image has a :latest tag.
I had an image with the :test tag, and the "always pull container before running" set on the execution environment, but upon running: `Container image "git.masked:4567/gregory/awx:test" already present on machine`

And when the image has a :latest tag, it's always pulled, whatever the pull setting is on the execution environment.
