### ISSUE TITLE
Job stdout broken

### ISSUE THREAD

**Issue by mkempster22** [ansible/awx#911]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
stdout on job runs not showing properly. Only shows some weird json and you can't close the output, the only way to get rid of the dialogue is to delete the last part of the URL in your browser to go back to just having the job run e.g: go from http://awx_server/#/jobs/872/host-event/10640/json --> http://awx_server/#/jobs/872/

This new update seems to have broken a lot of webui functionality such as #875 I assume they are all somewhat related to a change in code?

##### ENVIRONMENT
* AWX version: AWX 1.0.2.301 & .303
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: RHEL7
* Web Browser: Chrome (Tested on IE as well)

##### STEPS TO REPRODUCE
Run a job, Click on the results of a task to get stdout

##### EXPECTED RESULTS
Usual stdout to be shown

##### ACTUAL RESULTS
![awx_ui_error](https://user-images.githubusercontent.com/1752478/34518097-a89dd0f8-f075-11e7-89a8-34dcf578a91b.PNG)

**Comment by quenck** [comment]
The same on my Box:

**ENVIRONMENT**

- AWX version: AWX 1.0.2.322
- AWX install method: docker on linux
- Ansible version: 2.4.2.0
- Operating System: Debian 9
- Web Browser: Chrome

**Comment by quenck** [comment]
It seems to be fixed in 1.0.2.327...
