### ISSUE TITLE
Ability to limit Email Notifications based on Domain name

### ISSUE THREAD

**Issue by p-avery** [ansible/awx#9110]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Would like the ability to limit E-Mail notifications on Domain name, this would allow a stricter security to deny users from adding in notifications to emails outside of the trusted domain

**Comment by wenottingham** [comment]
If the concern is where a user with access to jobs can send email information on the job, this should be done in the SMTP infrastructure, not in AWX.  There is nothing that prevents the same user from copying information from the API and emailing it by hand.
