### ISSUE TITLE
SSO login redirect override URL is not working

### ISSUE THREAD

**Issue by gmtime** [ansible/awx#9115]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After upgrading to 16.0.0, SSO Login redirect override URL is no longer working.

"Settings->System->Miscellaneous System settings->Details" correctly shows "Login redirect override URL" setting (for example: /sso/login/saml/?idp=MYIDP), but editing is not possible and users are no longer automatically redirected.

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Operating System: any
* Web Browser: any

##### STEPS TO REPRODUCE
1. go to Settings->System->Miscellaneous System settings->Details
2. click on Edit
3. "Login redirect override URL" edit field is missing

##### EXPECTED RESULTS
1. go to Settings->System->Miscellaneous System settings->Details
2. click on Edit
3. enter data for "Login redirect override URL"
4. users automatically redirected to SSO

##### ACTUAL RESULTS
1. it's not possible to add/edit SSO override URL ("Login redirect override URL")
2. users are not redirected to SSO

##### ADDITIONAL INFORMATION

Also, would it be possible, when using SSO, to have SSL (SAML) icon and text dominantly displayed inside the login box? Currently, there is no text and the icon (UserCircleIcon) is too small. For SSO (SAML) users it is difficult to figure out that in order to login one needs to click on that tiny-microscopic-icon.

**Comment by ryanpetrello** [comment]
@mabashian @jakemcdermott do you have an issue to track adding this support back into the new UI (if not, we can use this one)?

https://github.com/ansible/awx/issues/1886
https://github.com/ansible/awx/pull/5479

**Comment by jakemcdermott** [comment]
:wave: Hello, @gmtime I couldn't reproduce this. I see the redirect override field and can update its value:

![login-redirect-url](https://user-images.githubusercontent.com/9753817/105200482-dfa88d80-5b0d-11eb-9eb0-a9828b85e061.gif)

I used an admin user on a fresh install. Are there any additional set up steps I should do? If you can still reproduce the bug, would you be able to post a screenshot?

**Comment by ryanpetrello** [comment]
@jakemcdermott I think they're suggesting that after successful login, the browser is not _redirecting_ to this URL i.e.,

https://github.com/ansible/awx/pull/5479/files#diff-82df1a8c96813927cf31345d61c02a0f7532cd8880d699ee7b23e041afb0259dR388

**Comment by gmtime** [comment]
Correct, it's not redirecting. Also, I don't seem to be able to edit the redirect URL (see screenshots). There is also a question of having really small SSO icon (hard to find).
<img width="1370" alt="Screen Shot 2021-01-20 at 17 51 03" src="https://user-images.githubusercontent.com/13539129/105208541-164fc980-5b49-11eb-84e9-e9471270c106.png">
<img width="1370" alt="Screen Shot 2021-01-20 at 17 51 27" src="https://user-images.githubusercontent.com/13539129/105208584-236cb880-5b49-11eb-9329-f85fa1217876.png">
<img width="556" alt="Screen Shot 2021-01-20 at 17 49 50" src="https://user-images.githubusercontent.com/13539129/105208619-2e274d80-5b49-11eb-999f-2a2e3726c286.png">

**Comment by gmtime** [comment]
BTW, that's an upgrade from 15.0.1 to 16.0.0 - I did not try with the fresh install.

**Comment by gmtime** [comment]
Regarding Login and SSO, it would be great it we could customize SSO label and icon (e.g. "MyCompany SSO Users Log In Here")

**Comment by gmtime** [comment]
> @jakemcdermott I think they're suggesting that after successful login, the browser is not _redirecting_ to this URL i.e.,
> 
> https://github.com/ansible/awx/pull/5479/files#diff-82df1a8c96813927cf31345d61c02a0f7532cd8880d699ee7b23e041afb0259dR388

@ryanpetrello, @jakemcdermott, just a small correction: it's not that after successful login the browser is not _redirecting_, it's the login process itself.

Before 16.0.0, with _Login Redirect Override URL_ users were immediately redirected to SSO page to login - now we always get AWX login page. Clicking on SAML icon will execute SSO process correctly and users will login correctly - that works - but transparent SSO login does not work any more.

**Comment by mabashian** [comment]
This smells like ui-specific issue to me so I'm going to remove the api label.

**Comment by balonik** [comment]
AWX 17.1.0 has the same issue with Login redirect override URL.

And I have raised another issue for the Login icons https://github.com/ansible/awx/issues/9554

**Comment by jakemcdermott** [comment]
Additional notes on expected behavior - The auto-redirect should only kick-in when there is exactly one SSO provider configured. If there is more than one then we don't redirect
