### ISSUE TITLE
WSUS Dynamic Inventory

### ISSUE THREAD

**Issue by Smuggla** [ansible/awx#912]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
- Inventory

##### SUMMARY

WSUS Dynamic Inventory

Would be awesome to use WSUS as a Dynamic Inventory for Patching and upgrades!

Didn't know if anyone had tried this?

I experimented with some IronPython when I had some cycles.

```
import clr
clr.AddReference('Microsoft.UpdateServices.Administration')
import Microsoft.UpdateServices.Administration
```

**Comment by wenottingham** [comment]
We pull all dynamic inventory support from upstream Ansible, see https://github.com/ansible/ansible/tree/devel/contrib/inventory and https://github.com/ansible/ansible/tree/devel/lib/ansible/plugins/inventory. It would need to be something that exists there first.
