### ISSUE TITLE
[ui_next] Activity Stream Settings Page Feature

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#9122]
##### ISSUE TYPE
 - Feature

##### SUMMARY
The Activity Stream Settings is available but does not function.

**Comment by akus062381** [comment]
We have implemented the activity stream page but not the activity stream settings

**Comment by mabashian** [comment]
@unlikelyzero @akus062381 this looks like's it's implemented in devel to me?

![activity_settings](https://user-images.githubusercontent.com/9889020/108233930-4079b480-7112-11eb-91dc-7a1692b8330d.gif)

Here's what it looked like in the old ui:

<img width="1524" alt="Screen Shot 2021-02-17 at 11 19 15 AM" src="https://user-images.githubusercontent.com/9889020/108233954-47a0c280-7112-11eb-9cfb-d3fdae378abf.png">

**Comment by unlikelyzero** [comment]
@mabashian the toggles _work_ but IIRC they're not wired up

**Comment by tiagodread** [comment]
Double checked this issue, this is working on devel. Toggling the toogle will not trigger the request, the form is saved hitting the `Save` button on the bottom.
cc @mabashian @unlikelyzero

**Comment by mabashian** [comment]
thanks @tiagodread !
