### ISSUE TITLE
login page ui tweaks

### ISSUE THREAD

**Issue by jlmitch5** [ansible/awx#9126]
![Screen Shot 2021-01-20 at 12 54 28 PM](https://user-images.githubusercontent.com/1342624/105369911-0380d780-5bd1-11eb-9be8-02855c75ac1e.png)

- We should make sure logo is the white text version (not sure exactly how that branding gets added, may need to be a separate issue)
- We should move "Please sign in." to secondary text (and it should be sentence cased).  like this shows https://www.patternfly.org/v4/components/login-page/react/basic/

**Comment by jakemcdermott** [comment]
Also:

"Sign in"
"Login"

(Should pick one, or at least not show both on the same page)

**Comment by tiagodread** [comment]
The login page with the white brand logo 

![image](https://user-images.githubusercontent.com/12464858/119698839-06fac880-be28-11eb-8bf1-1b4bb9934fe5.png)
