### ISSUE TITLE
[ui_next] Update AH/Galaxy Credential ordering on Orgs to make it more apparent how it impacts precedence

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#9127]
##### ISSUE TYPE
 - Feature

##### SUMMARY
In 3.8, we added the ability to specify multiple Galaxy Credentials to an Org so that users could specify precedence of ansible content. 

i.e. 
```
1. cloud.redhat
2. on prem AH
3. Public Galaxy

```

This ticket captures the work to make it more apparent to the users of ui_next without necessarily introducing net new feature work for feature parity.

**Comment by mabashian** [comment]
I'm moving this to high but I honestly can't remember how this worked in the old UI.  I don't _think_ we had some kind of "ordering" of credentials but I'd have to spin it up to confirm.

@unlikelyzero have you laid eyes on the old modal?  Does it have some help text or something that we're missing in the new UI?

**Comment by unlikelyzero** [comment]
@mabashian it was implicit and we intentionally skipped a good implementation to cover it in ui_next

**Comment by wenottingham** [comment]
Yes, we didn't do anything here before and just had in the docs that you essentially you had to "add in the order you want" - if you needed to reorder, you may have needed to deselect everything and start from scratch. CC @ryanpetrello

**Comment by wenottingham** [comment]
Instance group ordering had the same issue.

**Comment by mabashian** [comment]
OK, just looked at the new UI and the order that you select the credentials does not match the order in which we supply them to the API so regardless of whether we add some sort of re-ordering feature to this modal we need to fix the request(s) so that the order is preserved.

**Comment by marshmalien** [comment]
There is a pattern in the multi-credential lookup modal where we show a help banner when a user selects "Vault" credentials. We should show a similar banner telling the user that "order matters" in the new UX.
<img width="1109" alt="Screen Shot 2021-04-06 at 4 28 47 PM" src="https://user-images.githubusercontent.com/15881645/113774532-6a545e00-96f5-11eb-9bae-6b5fcaf28e0f.png">

**Comment by unlikelyzero** [comment]
@marshmalien can you work with @tiagodread on this one?

**Comment by trahman73** [comment]
Example...
![image](https://user-images.githubusercontent.com/13351591/121428531-ea8c7f00-c943-11eb-80bd-1085038385b2.png)

**Comment by tiagodread** [comment]
This is now implemented.
