### ISSUE TITLE
Defined variables in Template and deleted after (in launch) are passed anyway to the job(run)

### ISSUE THREAD

**Issue by misejoh** [ansible/awx#9132]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI (?)

##### SUMMARY
Defined (previously configured) variables in Template and deleted after (in the launch phase) are passed to the job(run)

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.15
* Operating System: Debian 9
* Web Browser: Chrome

##### STEPS TO REPRODUCE

-Created project form gitlab repositoy, playbooks are previously tested. (And other jobs are running fine)
-Created some templates, all of them working fine but this one. Predefined some optional fields: Inventory, credentials, variables. And some checked to be prompted on launch: Inventory, credentials, variables and limit.

Variables value: (YAML)
```
---
obtain: "locally" #some comment
```

-At run/lauch time, I continue with the predefined inventory, predefined credentials, specify one host to limit the execution and delete the variables, leaving just '---' in the box.
-Launch the job (in the preview looks ok the variable field/box)
-Once is launched, in the Details tab, it appears again the variable passed to the job. It also happens if I comment the variable:

```
---
#obtain: "locally"
```

##### EXPECTED RESULTS

As explained before, the expected would be to not pass a variable that is deleted in the Launch steps

##### ACTUAL RESULTS

The variable is passed to the Job despite it is deleted

##### ADDITIONAL INFORMATION

Anything is requested I'll attach it, in a reply.

Thanks!

**Comment by chrismeyersfsu** [comment]
It is a bit confusing. AWX takes the union of the extra vars + the prompt vars (if conflict then prompt vars overwrite). This is not a regression. It has always been like this.
