### ISSUE TITLE
Docker pull fails

### ISSUE THREAD

**Issue by domenicbove** [ansible/awx#9134]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Dockerhub pull fails, can you rebuild the image

```
% docker-compose run --rm --service-ports task awx-manage migrate --no-input
Pulling web (ansible/awx:17.0.0)...
ERROR: manifest for ansible/awx:17.0.0 not found: manifest unknown: manifest unknown
```

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by ryanpetrello** [comment]
This will be fixed later today when I tag and release 17.0.0.
