### ISSUE TITLE
Inventory variables not loaded until host is found in inventory

### ISSUE THREAD

**Issue by jetxeberria** [ansible/awx#9139]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 17.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.16
* Operating System: ubuntu 20.04
* Web Browser: Firefox 84.0.2

##### STEPS TO REPRODUCE

- Define a playbook "test.yml" with contents:

```
- hosts: "awx_server_work"
  become: yes
  gather_facts: no

  tasks:
    - name: Debug inventory awx_env
      debug:
        msg: "test var: {{awx_env}}"
```

- Define a template in AWX that uses that playbook

![Screenshot from 2021-01-22 11-39-14](https://user-images.githubusercontent.com/29378521/105480970-b2431780-5ca6-11eb-8ddc-e52244fdea6e.png)

- Create a test_inventory and add inventory variables:
  - test_var: "hello world"
  - awx_env: "work"

![Screenshot from 2021-01-22 11-37-57](https://user-images.githubusercontent.com/29378521/105480663-524c7100-5ca6-11eb-9d1d-088453a010c9.png)

**UP TO HERE IT WORKS AS EXPECTED:**

![Screenshot from 2021-01-22 11-45-11](https://user-images.githubusercontent.com/29378521/105481432-54fb9600-5ca7-11eb-9c97-ab94acf73a94.png)

**But, if we modify the playbook 'test.yml' and add variable {{awx_env}} to host field, it fails**:

```
- hosts: "awx_server_{{awx_env}}"
  become: yes
  gather_facts: no

  tasks:
    - name: Debug inventory awx_env
      debug:
        msg: "test var: {{awx_env}}"
```

##### EXPECTED RESULTS

The output shown in last image. 

##### ACTUAL RESULTS

ERROR! The field 'hosts' has an invalid value, which includes an undefined variable. The error was: 'awx_env' is undefined

##### ADDITIONAL INFORMATION

I suspect the behavior is that "inv_test" inventory variables are not being loaded until host "awx_server_work" is found in the inventory. 

I'm not sure if this is a bug or a new feature request. 

Template is already linked with 'inv_test' inventory, or could be prompted in launch time. Then, could inventory global variables be loaded before trying to run the target playbook?

This way we could select a host dynamically based on the variables of inventory. We could change target host with a single change in inventory variable.

Details of our infrastructure to understand our needs:
- We have 2 instances of AWX:
  - one for LIVE purposes 
  - another one for WORK purposes (testing)
- In both instances we've one inventory analogous to 'inv_test' (with other name). 
- We have a host defined in each inventory named 'awx_server_live' and 'awx_server_work'  (for LIVE and WORK instances respectively)
  - We need that these inventories have different names, because we use a logic to create VPN users based on the name of the host
- We would like that the templates defined both on LIVE and WORK can use same playbooks

**Comment by wenottingham** [comment]
You can't use inventory variables in the host specifier in this way, only extra variables.

Example from the CLI:
```
[notting@nostromo: ~/prog/scratch/test1]$ cat i
[all]
a
b
c

[all:vars]
fred=a
[notting@nostromo: ~/prog/scratch/test1]$ cat test.yml
---
- hosts: "{{ fred }}"
  gather_facts: false
  
  tasks:
  - debug: msg="hello"
[notting@nostromo: ~/prog/scratch/test1]$ ansible-playbook  -i i test.yml 
ERROR! The field 'hosts' has an invalid value, which includes an undefined variable. The error was: 'fred' is undefined

The error appears to be in '/usr/local/prog/scratch/test1/test.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- hosts: "{{ fred }}"
  ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"
[notting@nostromo: ~/prog/scratch/test1]$ ansible-playbook  -i i test.yml  -e fred=a

PLAY [a] ***************************************************************************************************************************

TASK [debug] ***********************************************************************************************************************
ok: [a] => {
    "msg": "hello"
}

PLAY RECAP *************************************************************************************************************************
a                          : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
