### ISSUE TITLE
Cannot set LDAP Group Type to values other then NestedMemberDNGroupType and MemberDNGroupType

### ISSUE THREAD

**Issue by jaytradertee** [ansible/awx#9141]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When trying to set the LDAP Group Type to ActiveDirectoryGroupType, I get the exception: 

"AUTH_LDAP_GROUP_TYPE_PARAMS": ["Invalid key(s): \"member_attr\"."" 

I tried all the group types as described in https://django-auth-ldap.readthedocs.io/en/stable/groups.html#types-of-groups

NestedMemberDNGroupType and MemberDNGroupType were accepted
. 
PosixGroupType, GroupOfNamesType, NestedGroupOfNamesType, NestedGroupOfUniqueNamesType, ActiveDirectoryGroupType, NestedActiveDirectoryGroupType, OrganizationalRoleGroupType and NestedOrganizationalRoleGroupType throw the exception above.

I was able to select ActiveDirectoryGroupType in AWX 15.0.1/Ansible 2.9.14.

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on Centos 8
* Ansible version:  2.9.15
* Operating System: Centos 8
* Web Browser: Chrome 87.0

##### STEPS TO REPRODUCE

1. Go To http://<AWX Host>/api/v2/settings/ldap/
2. Modify the value of "AUTH_LDAP_GROUP_TYPE": "<change to group type as described above>",
3. Click Put.

##### EXPECTED RESULTS

1. Go To http://<AWX Host>/#/settings/ldap/default/details
2. See the value defined under LDAP Group Type.

##### ACTUAL RESULTS

Error thrown, no changes made.

##### ADDITIONAL INFORMATION

![exception](https://user-images.githubusercontent.com/13001689/105500279-afd5c300-5c90-11eb-83d1-dc04ddbbffc8.png)

**Comment by wenottingham** [comment]
AUTH_LDAP_GROUP_TYPE_PARAMS is dependent on the group type - certain parameters aren't valid for certain group types.

If you are changing GROUP_TYPE, you many need to set GROUP_TYPE_PARAMS at the same time.

**Comment by jaytradertee** [comment]
I removed AWX's default value and it accepted that. What's strange is all other values (LDAP User Search, LDAP Group Search, LDAP User Attribute Map, etc) are all blank except for LDAP Group Type Parameters. Switching it to blank made me able to accept the values for the other GROUP_TYPES. 

{
  "member_attr": "member",
  "name_attr": "cn"
}

According to the Ansible Tower documentation all LDAP Group Types should be able to use those default values.

https://docs.ansible.com/ansible-tower/latest/html/administration/ldap_auth.html
Each LDAP Group Type can potentially take different parameters. Tower exposes LDAP_GROUP_TYPE_PARAMS to account for this. LDAP_GROUP_TYPE_PARAMS is a dictionary, which will be converted by Tower to kwargs and passed to the LDAP Group Type class selected. There are two common parameters used by any of the LDAP Group Type; name_attr and member_attr. Where name_attr defaults to cn and member_attr defaults to member:

**Comment by wenottingham** [comment]
cc @tvo - I think we need to change that docs paragraph - not all group types take member_attr.

**Comment by jaytradertee** [comment]
Thank you for your help, I very much appreciate it.
