### ISSUE TITLE
virtual environment python interpreter

### ISSUE THREAD

**Issue by csamarajeewa** [ansible/awx#9146]
##### ISSUE TYPE
 - Feature Idea

Virtual environment doesn't seem to use the correct python interpreter when activated. 

##### SUMMARY

AWX doesn't seem to use the python interpreter from the venv when the environment is activated . I had to manually set  ansible_python_interpreter: path-to-venv-interpreter variable for my job to work successfully.

**Comment by AlanCoding** [comment]
This will be solved with execution environments https://github.com/ansible/awx/issues/5157

**Comment by rebeccahhh** [comment]
There will be instructions on how to migrate/avoid this once the work with execution environments. Leaving this open until migration instructions are available.

**Comment by ryanpetrello** [comment]
Hey @csamarajeewa,

👋 The latest version of AWX (18.0.0) no longer uses virtualenvs (see: https://github.com/ansible/awx/issues/5157)
