### ISSUE TITLE
running a Project Sync skips all role detection/fetching.

### ISSUE THREAD

**Issue by steelcowboy** [ansible/awx#9151]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Even though roles show to be enabled in the WebUI and Galaxy Credentials are defined, running a Project Sync skips all role detection/fetching.

##### ENVIRONMENT
* AWX version: 17.0.0
* AWX install method: docker on Linux
* Ansible version: 2.9.16
* Operating System: Ubuntu 20.10
* Web Browser: Google Chrome v88

##### STEPS TO REPRODUCE

1. Ensure Role Download is enabled in Settings -> Jobs
2. Ensure Ansible Galaxy credentials are defined, from diving into the code this seems to be a requirement: https://github.com/ansible/awx/blob/b913d8411afe50c8d6e21aa9ce5ffb421e25374c/awx/main/tasks.py#L2183
  a. For the Ansible Galaxy credentials, I created a new credential of type "Ansible Galaxy/Automation Hub API Token" and with a Galaxy server URL of "https://galaxy.ansible.com"
3. Import a project that contains a `roles/requirements.yml` file
4. Edit `/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/playbooks/project_update.yml` to include a debug statement to print the value of `roles_enabled`
5. Run a project sync

**Roles are enabled**:
![Screenshot from 2021-01-24 13-04-36](https://user-images.githubusercontent.com/9201644/105643445-bad15480-5e44-11eb-88ad-6dcc03206d56.png)
**Galaxy credentials are defined**:
![Screenshot from 2021-01-24 13-03-41](https://user-images.githubusercontent.com/9201644/105643448-bc9b1800-5e44-11eb-9a39-5600f25cb7ad.png)

##### EXPECTED RESULTS
I should see the detection for roles/requirements.y(a)ml occur, and `roles_enabled` in the Ansible playbook should be set to true.

##### ACTUAL RESULTS
```
PLAY [Install content with ansible-galaxy command if necessary] ****************

TASK [check if roles are enabled] **********************************************
ok: [localhost] => {
    "roles_enabled": false
}

TASK [detect roles/requirements.(yml/yaml)] ************************************
skipping: [localhost] => (item={'ext': '.yml'}) 
skipping: [localhost] => (item={'ext': '.yaml'}) 
```

##### ADDITIONAL INFORMATION
Previous discussion of this bug occurred in #1632. Reading the code I'd expect to see some logging from the aforementioned `tasks.py`, but I could not find any message about missing Galaxy Credentials in `/var/log/tower`.
https://github.com/ansible/awx/blob/b913d8411afe50c8d6e21aa9ce5ffb421e25374c/awx/main/tasks.py#L2165-L2171

**Comment by AlanCoding** [comment]
Same root issue as others ~like https://github.com/ansible/awx/issues/4675~, but a little more specific about the UX. Ping @ryanpetrello

**Comment by blomquisg** [comment]
@AlanCoding how is this related to #4675?  Can you add some more about what you're thinking here?

**Comment by AlanCoding** [comment]
Oops, I did link the wrong issue. See https://github.com/ansible/awx/issues/8765 or https://github.com/ansible/awx/issues/8341

A Galaxy credential must be associated with the organization of the project, or else the `roles_enabled` setting will be set to False and no `ansible-galaxy` commands will be ran. This was an intentional change.

**Comment by steelcowboy** [comment]
I didn't show it in my screenshot, but I just confirmed that the credential and the project are part of the same organization

**Comment by EmmanuelROLLAND** [comment]
hello
in your awx/main/tasks.py, if you update it in the container replacing:
            'roles_enabled': galaxy_creds_are_defined and settings.AWX_ROLES_ENABLED,
by
            'roles_enabled': settings.AWX_ROLES_ENABLED,
and do a docker-compose restart
Does running a Project Sync agin still skips all role detection/fetching ?
I test yesterday with •AWX version: 17.0.1 and both tasks.py works fine !

**Comment by chrisbalmer** [comment]
> I didn't show it in my screenshot, but I just confirmed that the credential and the project are part of the same organization

If you edit the organization (not the credential), there is a special field in there to associate a specific Galaxy Credential with the organization. This is different than the credential's own organization mapping. So there are two spots where the credential is linked to the org.

It took me a while to catch that second spot but it fixed the problem for me.

It's mentioned [here in #2](https://docs.ansible.com/ansible-tower/latest/html/userguide/projects.html#ug-collections-in-tower) but I couldn't find it in other documentation spots for orgs.

**Comment by chrismeyersfsu** [comment]
The project update should print out why it decided not to sync `requirements.yml` content.

**Comment by fourstepper** [comment]
I agree with @chrismeyersfu - this would be great.

I have hit this, at https://github.com/ansible/awx/issues/10122

**Comment by AlanCoding** [comment]
@chrismeyersfsu @fourstepper the open PR https://github.com/ansible/awx/pull/10068 attempts to add elaboration in the project update playbook. You can get a sense of the behavior by looking at the diff.

**Comment by Zokormazo** [comment]
Verified!

**Comment by fourstepper** [comment]
Looks good to me, thanks @AlanCoding

**Comment by mihai-satmarean** [comment]
> > I didn't show it in my screenshot, but I just confirmed that the credential and the project are part of the same organization
> 
> If you edit the organization (not the credential), there is a special field in there to associate a specific Galaxy Credential with the organization. This is different than the credential's own organization mapping. So there are two spots where the credential is linked to the org.
> 
> It took me a while to catch that second spot but it fixed the problem for me.
> 
> It's mentioned [here in #2](https://docs.ansible.com/ansible-tower/latest/html/userguide/projects.html#ug-collections-in-tower) but I couldn't find it in other documentation spots for orgs.

we are using the awx collection to automate the tower configuration, any idea how to do this from the ansible awx module?

**Comment by AlanCoding** [comment]
^ the organization module https://github.com/ansible/awx/blob/devel/awx_collection/plugins/modules/organization.py

has a `galaxy_credentials` option.

**Comment by sepiaops** [comment]
> > I didn't show it in my screenshot, but I just confirmed that the credential and the project are part of the same organization
> 
> If you edit the organization (not the credential), there is a special field in there to associate a specific Galaxy Credential with the organization. This is different than the credential's own organization mapping. So there are two spots where the credential is linked to the org.
> 
> It took me a while to catch that second spot but it fixed the problem for me.
> 
> It's mentioned [here in #2](https://docs.ansible.com/ansible-tower/latest/html/userguide/projects.html#ug-collections-in-tower) but I couldn't find it in other documentation spots for orgs.

This solved the issue for me too..
