### ISSUE TITLE
[execution-environments] Report receptor unit_id in API for manual debugging

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#9153]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The API should give the unit_id for a job, or otherwise document how the user can figure out the unit_id from other fields.

If use case is that an error happens and a user or support personnel need to shell into the server and manually run `receptorctl` commands to poke at what happened. Ping @gamuniz 

These commands follow the pattern of:

 - `receptorctl work status {unit_id}`
 - `receptorctl work cancel {unit_id}`
 - `receptorctl work release {unit_id}`

Although the user shouldn't ever have need to call cancel or release... things can always go wrong!

**Comment by kdelee** [comment]
@ryanpetrello @AlanCoding what is the PR related to this?

**Comment by AlanCoding** [comment]
@kdelee https://github.com/ansible/awx/pull/9892 which is merged now

**Comment by kdelee** [comment]
@AlanCoding @shanemcd I notice this only on container group jobs. Is that expected? I'm still not 100% up to date on if receptor is used at all when jobs are ran locally on the tower nodes

**Comment by ryanpetrello** [comment]
This should be available both on container group jobs, and normal instance group runs.

**Comment by kdelee** [comment]
Hmm, nevermind, must have gotten confused. I am seeing it on regular jobs now.

I'll sprinkle in some assertions about this being populated on different types of jobs, but seeing as it is mostly a debugging tool, I'm going to close this

**Comment by ryanpetrello** [comment]
> but seeing as it is mostly a debugging tool

Yep, I think that's the primary use case here.
