### ISSUE TITLE
[execution-environments] In some cases, AWX fails to release job that had error

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#9154]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Run a job that had an error due to some receptor configuration problem (more detailed specifics TBD).

Make sure there are no jobs running in the system.

Now shell into the server and check `receptorctl work list`

Expected result: nothing listed

Actual result:

```
bash-4.4$ receptorctl work list
{'2ntorWZp': {'Detail': 'Error creating pod: At least one container must be '
                        'named worker',
              'ExtraData': {'Command': '',
                            'Image': '',
                            'KubeConfig': '',
                            'KubeNamespace': 'eon9jxmrgo',
                            'KubePod': '',
                            'KubeTLSCAData': '',
                            'KubeVerifyTLS': True,
                            'Params': '',
                            'PodName': ''},
              'State': 3,
              'StateName': 'Failed',
              'StdoutSize': 0,
              'WorkType': 'ocp'},
...
```

The `result_traceback` in the job reports the error. However, as of https://github.com/ansible/awx/pull/8598, the code that throws the error isn't wrapped in a try-except such that the release command will still be ran.

**Comment by ryanpetrello** [comment]
Yep, I've experienced this, too.  It's pretty easy to reproduce by just putting in a container group URL that's nonsense (like example.org).

**Comment by AlanCoding** [comment]
Ping @yagomarques, I want to start gathering observations like this, and eventually put them in the test plan.

**Comment by AlanCoding** [comment]
We have added a test for this, but still leaving on needs_test to allow for QE review.

We might want to check that after our runs have finished there's no unreleased work. Just a thought.

**Comment by masbahnana** [comment]
The tests have already been verified and validated, let's wait for the branch to be merge in the devel.

**Comment by AlanCoding** [comment]
@shebangbash the execution-environments branch has been merged. Is this ready to be closed?

**Comment by AlanCoding** [comment]
This is not working in all cases, but those cases have not been identified yet.

**Comment by kdelee** [comment]
We've added some more coverage for specific cases, but keeping this open without specifics of what the bug is or the missing test cases is not very useful. Going to close and suggest that we open new issues for pending problems

**Comment by AlanCoding** [comment]
The updated failure is now:

Run_Integration_Tests___test_receptorctl_work_units_cleanup

```
Error Message
AssertionError: {'D5fvYsNn': {'Detail': 'exit status 0',
                'ExtraData': None,
                'State': 2,
                'StateName': 'Succeeded',
                'StdoutSize': 11870,
                'WorkType': 'local'},
   'IwevsQ0Q': {'Detail': 'exit status 0',
                'ExtraData': None,
                'State': 2,
                'StateName': 'Succeeded',
                'StdoutSize': 11858,
                'WorkType': 'local'},
   'c9j9ASIg': {'Detail': 'exit status 0',
                'ExtraData': None,
                'State': 2,
                'StateName': 'Succeeded',
                'StdoutSize': 11822,
                'WorkType': 'local'}}
assert 3 == 0
  +3
  -0
Stacktrace
Traceback (most recent call last):
  File "/home/ec2-user/tower-qa/tests/api/execution_environments/test_receptor_integration.py", line 71, in test_receptorctl_work_units_cleanup
    assert len(work_data.keys()) == 0, result['stdout']  # some work was not released
AssertionError: {'D5fvYsNn': {'Detail': 'exit status 0',
                'ExtraData': None,
                'State': 2,
                'StateName': 'Succeeded',
                'StdoutSize': 11870,
                'WorkType': 'local'},
   'IwevsQ0Q': {'Detail': 'exit status 0',
                'ExtraData': None,
                'State': 2,
                'StateName': 'Succeeded',
                'StdoutSize': 11858,
                'WorkType': 'local'},
   'c9j9ASIg': {'Detail': 'exit status 0',
                'ExtraData': None,
                'State': 2,
                'StateName': 'Succeeded',
                'StdoutSize': 11822,
                'WorkType': 'local'}}
assert 3 == 0
  +3
  -0
```

It was suspected that this may be resolved by WIP in receptor now.

**Comment by shanemcd** [comment]
I think we probably need another reaper task here. In order to do this, we'll need to take the `unitid` we get back from receptor, store it on the job, and query for things that are not actually running, similar to what we do in https://github.com/ansible/awx/blob/862f40a643eccb8540d6e2d6c2adb577f5720542/awx/main/tasks.py#L476

**Comment by AlanCoding** [comment]
We're still seeing this, so I'll put the needs_devel label on.

**Comment by tiagodread** [comment]
`Run_Integration_Tests___test_receptorctl_work_units_cleanup` is passing now

![image](https://user-images.githubusercontent.com/12464858/122937996-c0c25780-d348-11eb-9f95-2bce6cc65809.png)
