### ISSUE TITLE
Sync button "box" is offcentered

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#9158]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

When clicking on the sync icon on project screens the selection box put around it is not centered.

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.3
* Operating System: Fedora
* Web Browser: Chrome on OS X

##### STEPS TO REPRODUCE

Create a project, click on the sync button

##### EXPECTED RESULTS

Box would be centered

##### ACTUAL RESULTS

Box is offset

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/32551173/105752571-75c92300-5f15-11eb-9a9f-fe063805c4bb.png)

**Comment by unlikelyzero** [comment]
@john-westcott-iv thank you for filing this issue. It appears to be a problem across the app. I'm closing the 3 duplicate issues and using your format to file a new generic issue.

https://github.com/ansible/awx/issues/9158
https://github.com/ansible/awx/issues/8851
https://github.com/ansible/awx/issues/7507
