### ISSUE TITLE
AWX 17.0.0 VCenter Dynamic Inventory Hostname unable to change format

### ISSUE THREAD

**Issue by Lobout** [ansible/awx#9161]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When using the VMware vCenter dynamic inventory the host name is imported in the format 'name_uuid'. For example: AWX_42338701-e6b6-690c-e553-9405a9a0180c

##### ENVIRONMENT
* AWX version: 17.0.0
* AWX install method: Docker on Linux
* Ansible version:  2.9.16
* Operating System: Centos Stream 8.3
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Add VMware vSphere as dynamic inventory source and start sync process

##### EXPECTED RESULTS

Host to be imported using the alias of the config.name value

##### ACTUAL RESULTS

Hosts are imported using the name formatted as config.name_config.uuid for example : AWX_42338701-e6b6-690c-e553-9405a9a0180c

##### ADDITIONAL INFORMATION

Add the following line to the Source Variables of the inventory source
alias_pattern: {{ config.name }}

Edited vmware_inventory.py and changed lline from 'alias_pattern': '{{ config.name + "_" + config.uuid }}' to 'alias_pattern': '{{ config.name }}'

But host names are still shown in format name_uuid

This appears to be a duplicate of bug 6727, but none of the workarounds listed in it are not working.

**Comment by wenottingham** [comment]
`alias_pattern` is a configuration value for the old VMware inventory source.

You need to configure it as provided here: https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vm_inventory_inventory.html

**Comment by roostercactus** [comment]
In your vSphere inventory source put this in the Source variables box (as yaml)

hostnames:
  - 'config.name'

this will populate your inventory from vSphere as hostname only...and not hostname+uuid.  no need to edit any python files directly.

the dot shown above should be a dash (i can't make it format correctly)
