### ISSUE TITLE
Notification Template - workflow_url variable

### ISSUE THREAD

**Issue by djj106** [ansible/awx#9162]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY

The workflow_url variable in a notification template returns a url constructed like: https://example.com/#/workflows/249335

This URL appears to be invalid with the new UI.

##### ENVIRONMENT
* AWX version: 17.0.0
* AWX install method: docker on linux
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by kdelee** [comment]
taking off api label, api has been updated to use correct route in UI

Thanks!

**Comment by djj106** [comment]
resolved in 17.0.1
