### ISSUE TITLE
Allow a Team to be Assigned as Team Admin to Another Team

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/awx#9164]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Similar to assigning a user as a team admin, all a team to be added as a team admin of a different team.

**Comment by AlanCoding** [comment]
The problems with doing this are the same as https://github.com/ansible/awx/issues/3600

Without some new permissions view in the UI, circular (or non-circular and complex) permissions like this would be unmanageable in the UI.

**Comment by jakemcdermott** [comment]
@AlanCoding @jamesmarshall24 Since this appears to be a duplicate of https://github.com/ansible/awx/issues/3600, I'm closing this issue and adding a reference to it in  https://github.com/ansible/awx/issues/3600.
