### ISSUE TITLE
awx 17.0.1 adding a job schedule won't prompt for "limit"

### ISSUE THREAD

**Issue by kapouer** [ansible/awx#9173]
Adding a schedule from an existing job template with a "prompt for limit" option, does not prompt for limit.
Existing schedules don't show the limit they have limit either.

**Comment by lcarangelo** [comment]
This happen also in templates that are present in a workflow.
It's a CRITICAL issue.
In my case, workflow does not not have INVENTORY and Limits populated or set to prompt on launch , instead node/templates in it have different inventory and limits configured per each template (template configured as prompt on launch).
When I start the WF, each template run on all the inventory associate to it and DO NOT apply the limits that have been set via edit node during WF design / visualizer.

**Comment by lcarangelo** [comment]
https://docs.ansible.com/ansible-tower/latest/html/userguide/workflow_templates.html
PARAGRAPH 7 
_If a job template used in the workflow has Prompt on Launch selected for any of its parameters, a Prompt button appears, allowing you to change those values at the node level. Use the wizard to change the value(s) in each of the tabs and click Confirm in the Preview tab._

This does not work for LIMIT (it was working on versione 12 ). 
Please let me know as soon it's fixed. Version 17.0.1 (also 17.0.0) is unusable.

**Comment by mabashian** [comment]
This is being tracked here: https://github.com/ansible/awx/issues/7692
