### ISSUE TITLE
Proxy error on new installation on project scm update

### ISSUE THREAD

**Issue by Syntax3rror404** [ansible/awx#9174]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 17.0.0
* AWX install method: docker
* Ansible version:  2.9
* Operating System: CentOS 7
* Web Browser: Chrome latest

##### STEPS TO REPRODUCE

DNS added to the Compose, otherwise the GIT server cannot be reached via DNS names.

##### EXPECTED RESULTS

Git projects can be pulled from awx.

##### ACTUAL RESULTS

Git server can be pinged within the container. The same error always occurs with a git clone:
`fatal: unable to access '<ADDRESS>': Could not resolve proxy: ''`

We don't have or need any proxy.

**Comment by ryanpetrello** [comment]
Hey @Syntax3rror404,

Based on the description, I suspect this is probably something specific to your Docker or networking setup.  This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
