### ISSUE TITLE
In continuation of being inclusive update django-cors-headers

### ISSUE THREAD

**Issue by jainnikhil30** [ansible/awx#9177]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

This is in continuation to this commit:
https://github.com/ansible/awx/commit/78229f58715fbfbf88177e54031f532543b57acc

django-cors-headers have updated certain environment variables as part of being inclusive:

https://github.com/adamchainz/django-cors-headers/blob/master/HISTORY.rst#350-2020-08-25

We have been using django-cors-headers==3.2.1 for sometime now, we updated django but not the django-cors-headers. We should do that at some point. We use CORS_ORIGIN_REGEX_WHITELIST and mention about it in docs as well here:

https://docs.ansible.com/ansible-tower/latest/html/administration/oauth2_token_auth.html#application-using-authorization-code-grant-type

**Comment by kdelee** [comment]
I can confirm this has been replaced in awx and in the docs
