### ISSUE TITLE
AWX fails with: lxc command not found in PATH

### ISSUE THREAD

**Issue by killua-eu** [ansible/awx#9184]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Awx jobs fail to run against hosts with `ansible_connection: lxd` failing with 

```
When running a job with a host using the lxd ansible_connection, I get
fatal: [proxy01]: FAILED! => {"msg": "lxc command not found in PATH"}
```

##### ENVIRONMENT
* AWX version: 15.0.0.1
* AWX install method: docker on linux
* Ansible version: 2.9.14
* Operating System: Ubuntu
* Web Browser: Any

##### STEPS TO REPRODUCE

- install ansible
- connect to a host via lxd

##### EXPECTED RESULTS

No failure

##### ACTUAL RESULTS

```
When running a job with a host using the lxd ansible_connection, I get
fatal: [proxy01]: FAILED! => {"msg": "lxc command not found in PATH"}
```

##### ADDITIONAL INFORMATION

-

**Comment by jakemcdermott** [comment]
You'll need to make sure `lxc` is installed and reachable on the PATH for the `awx` user. I'm not sure this is available by default with the official images.

Note that awx is running on a container and generally doesn't have access to any commands or binaries that are on the host machine running the container.

If you have any questions about customizing or configuring your awx install, please reach out to the community mailing list or join the `ansible-awx` irc channel on freenode.

Thanks and happy automating!

**Comment by killua-eu** [comment]
Yeah, the problem is the containers are rhel8 based which redhat doesnt build the lxc binary so either

- lxc gets built properly upstream
- lxc gets build correctly on docker compose
- a bindmount will be required.
- the corresponding ansible module won't depend on a binary but rather a python library. 

Lovely. Since this relates to https://github.com/ansible/ansible/issues/66597 , maybe @hnakamur might have some ideas? I'm not sure how things change with ansible 2.10, but the connection plugin with 2.9 should have all dependencies installed, otherwise awx will break.

**Comment by hnakamur** [comment]
The lxc command is not needed by the lxd_container module, but is needed by the lxd connection plugin.
https://github.com/ansible-collections/community.general/blob/9c648c8e3acedf0881c9fbeb08b353230457c945/plugins/connection/lxd.py#L64.

The lxd connection plugin is used when you use `ansible_connection: lxd`.

**Comment by killua-eu** [comment]
Hey @hnakamur , yep thats exactly what I'm using - `ansible_connection: lxd` .. thats why things fail on me.
