### ISSUE TITLE
Remove the custom venv fields from the UI

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#9190]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Remove the custom venv fields from the UI. Every place that shows a custom virtual env should display the execution environment. For instance, Job Details output.

**Comment by AlanCoding** [comment]
Ping @rebeccahhh and @shanemcd, there was talk of having some placeholder tooltips (this may not be the right word) for how to migrate these fields. I want to get you in the loop for that discussion.

**Comment by unlikelyzero** [comment]
@mabashian this is required for EE environments

**Comment by tiagodread** [comment]
@one-t could we close this issue?
