### ISSUE TITLE
Job detail container group links to wrong page

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#9191]
##### ISSUE TYPE
 - Bug Report

##### STEPS TO REPRODUCE
- create a container group
- create a job template that uses that container group
- launch the job template
- navigate to details page of launched job and click the instance group link

##### EXPECTED RESULTS
- link label says "Container group"
- link routes to container group details

##### ACTUAL RESULTS
- link label says "Instance group"
- link routes to instance group details, which causes unexpected issues on load

**Comment by unlikelyzero** [comment]
@akus062381 can you double check that you added coverage here?

**Comment by akus062381** [comment]
This is all set, coverage added
