### ISSUE TITLE
Add project update to the awx.awx.tower_project ansible module

### ISSUE THREAD

**Issue by natman** [ansible/awx#9194]
##### ISSUE TYPE
Add project update to the awx.awx.tower_project ansible module

##### SUMMARY
We are able to launch a project update with awxkit but not with the pendant ansible module in 16.0.0

**Comment by wenottingham** [comment]
See #8686, etc

**Comment by sean-m-sullivan** [comment]
@natman Pulled that in, and tested it, please follow the old issue and the PR.
