### ISSUE TITLE
AWX 17.0.1: have to log in twice

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx#9197]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Sometimes I have to log in twice to AWX

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.17
* Operating System: openSUSE Leap 15.2
* Web Browser: Firefox on linux and windows.

##### STEPS TO REPRODUCE

Sometimes when I log in to AWX I get a popup that i can't read because it disappears too fast, and are redirected to the login page and have to log in again.

##### EXPECTED RESULTS

I would expect that logging in on AWX would actually log me in.

##### ACTUAL RESULTS

I log in to AWX, then I get a popup that i can't read because it disappears too fast, and are redirected to the login page and have to log in again.

##### ADDITIONAL INFORMATION

just guessing: could this be happening because the previous session timed out or the browser was just closed, instead of properly logging out of AWX?

**Comment by jakemcdermott** [comment]
I've observed this as well. There's a scenario where we need to clear some session state after it expires.

**Comment by lemmy04** [comment]
this still exists in 17.1.0 - and since standalone docker deployments aren't supported after (from what i understand from the devel repo) I won't be able to update any further...

**Comment by ryanpetrello** [comment]
@lemmy04,

Just a heads up, you can still run AWX on Docker (though you'll have to build your own images), but the install method is changing in the next major release.  See:

https://github.com/ansible/awx/tree/devel/tools/docker-compose
https://github.com/ansible/awx/blob/devel/tools/docker-compose/docs/data_migration.md

**Comment by lemmy04** [comment]
So I won't be able to update to an actual RELEASE anymore, unless I use locally built images, which is NOT an official release, or I build myself a local kubernetes cluster?

**Comment by ryanpetrello** [comment]
@lemmy04,

Our releases are not published images, though historically we've provided these as a nicety to the community (there are several third-party distributions of AWX that are not container image-based).  Our official releases are source distributions which have been and will continue to be published here:

https://github.com/ansible/awx/releases

Starting in 18.0.0, you can still deploy these in Docker + docker-compose using the instructions at https://github.com/ansible/awx/tree/devel/tools/docker-compose#overview

There's even a one-line make target for building the Docker image locally:

`~ make docker-compose-build`

**Comment by lemmy04** [comment]
Just for the record: I'm having this issue in AWX 19.0.0, too.

**Comment by tiagodread** [comment]
This is being fixed by #9908
