### ISSUE TITLE
Install failed on Build base web image

### ISSUE THREAD

**Issue by zochamx** [ansible/awx#92]
### Summary

All prerequisites installed, yum works normally behind proxy all env proxy variables has been set correctly (os, yum, npm, docker). Though installation failed on: 

TASK [image_build : Build base web image]

### Environment

* Ansible version:  2.3.1.0
* Operating System: centos 7.3
* npm: 3.10.10
* node: 6.11.1

### Error:

TASK [image_build : Build base web image] ***************************************************************
fatal: [localhost -> localhost]: FAILED! => {
"changed": false, 
"failed": true, 
"msg": "Error building awx_web - code: 1, message: The command '/bin/sh -c yum -y install epel-release &&     yum -y localinstall http://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm &&     yum -y update &&     yum -y install ansible git curl python-psycopg2 python-pip python-setuptools libselinux-python setools-libs yum-utils sudo acl make postgresql-devel nginx python-psutil libxml2-devel libxslt-devel libstdc++.so.6 gcc cyrus-sasl-devel cyrus-sasl openldap-devel libffi-devel python-pip xmlsec1-devel swig krb5-devel xmlsec1-openssl xmlsec1 xmlsec1-openssl-devel libtool-ltdl-devel bubblewrap gcc-c++ python-devel &&     pip install virtualenv supervisor &&     VENV_BASE=/var/lib/awx/venv make requirements_ansible &&     VENV_BASE=/var/lib/awx/venv make requirements_awx &&     yum -y remove gcc postgresql-devel libxml2-devel libxslt-devel cyrus-sasl-devel openldap-devel xmlsec1-devel krb5-devel xmlsec1-openssl-devel libtool-ltdl-devel gcc-c++ python-devel &&     yum -y clean all &&     rm -rf /root/.cache' returned a non-zero code: 1, logs: [u'Step 1/31 : FROM centos:7\\n', u' ---> 328edcd84f1b\\n', u'Step 2/31 : USER root\\n', u' ---> Using cache\\n', u' ---> 2106f52732ad\\n', u'Step 3/31 : ADD https://github.com/krallin/tini/releases/download/v0.14.0/tini /tini\\n', u'\\n', u' ---> Using cache\\n', u' ---> 7ff284c81c77\\n', u'Step 4/31 : RUN chmod +x /tini\\n', u' ---> Using cache\\n', u' ---> 142c92729ca8\\n', u'Step 5/31 : ADD Makefile /tmp/Makefile\\n', u' ---> Using cache\\n', u' ---> 10bab565dd05\\n', u'Step 6/31 : RUN mkdir /tmp/requirements\\n', u' ---> Using cache\\n', u' ---> 8fba8325ca46\\n', u'Step 7/31 : ADD requirements/requirements_ansible.txt requirements/requirements_ansible_uninstall.txt requirements/requirements_ansible_git.txt requirements/requirements.txt requirements/requirements_tower_uninstall.txt requirements/requirements_git.txt /tmp/requirements/\\n', u' ---> Using cache\\n', u' ---> 81a14f198012\\n', u'Step 8/31 : WORKDIR /tmp\\n', u' ---> Using cache\\n', u' ---> 81e98fa58646\\n', u'Step 9/31 : RUN mkdir -p /var/lib/awx/public/static\\n', u' ---> Using cache\\n', u' ---> d8d6dcea5339\\n', u'Step 10/31 : RUN chgrp -Rf root /var/lib/awx && chmod -Rf g+w /var/lib/awx\\n', u' ---> Using cache\\n', u' ---> c24a484eb552\\n', u'Step 11/31 : RUN yum -y install epel-release &&     yum -y localinstall http://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm &&     yum -y update &&     yum -y install ansible git curl python-psycopg2 python-pip python-setuptools libselinux-python setools-libs yum-utils sudo acl make postgresql-devel nginx python-psutil libxml2-devel libxslt-devel libstdc++.so.6 gcc cyrus-sasl-devel cyrus-sasl openldap-devel libffi-devel python-pip xmlsec1-devel swig krb5-devel xmlsec1-openssl xmlsec1 xmlsec1-openssl-devel libtool-ltdl-devel bubblewrap gcc-c++ python-devel &&     pip install virtualenv supervisor &&     VENV_BASE=/var/lib/awx/venv make requirements_ansible &&     VENV_BASE=/var/lib/awx/venv make requirements_awx &&     yum -y remove gcc postgresql-devel libxml2-devel libxslt-devel cyrus-sasl-devel openldap-devel xmlsec1-devel krb5-devel xmlsec1-openssl-devel libtool-ltdl-devel gcc-c++ python-devel &&     yum -y clean all &&     rm -rf /root/.cache\\n', u' ---> Running in 0fdbb8298efb\\n', u'Loaded plugins: fastestmirror, ovl\\n', u'\\x1b[91m\\n\\n One of the configured repositories failed (Unknown),\\n and yum doesn\\'t have enough cached data to continue. At this point the only\\n safe thing yum can do is fail. There are a few ways to work \"fix\" this:\\n\\n     1. Contact the upstream for the repository and get them to fix the problem.\\n\\n     2. Reconfigure the baseurl/etc. for the repository, to point to a working\\n        upstream. This is most often useful if you are using a newer\\n        distribution release than is supported by the repository (and the\\n        packages for the previous distribution release still work).\\n\\n     3. Run the command with the repository temporarily disabled\\n            yum --disablerepo=<repoid> ...\\n\\n     4. Disable the repository permanently, so yum won\\'t use it by default. Yum\\n        will then just ignore the repository until you permanently enable it\\n        again or use --enablerepo for temporary usage:\\n\\n            yum-config-manager --disable <repoid>\\n        or\\n            subscription-manager repos --disable=<repoid>\\n\\n     5. Configure the failing repository to be skipped, if it is unavailable.\\n        Note that yum will try to contact the repo. when it runs most commands,\\n        so will have to try and fail each time (and thus. yum will be be much\\n        slower). If it is a very temporary problem though, this is often a nice\\n        compromise:\\n\\n            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true\\n\\nCannot find a valid baseurl for repo: base/7/x86_64\\n\\x1b[0m', u'Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was\\n14: curl#7 - \"Failed to connect to 2607:f8f8:700:12::10: Network is unreachable\"\\n', u'Removing intermediate container `0fdbb8298efb\\n']"}`

### Additional Information:

yum is working correctly I tried to install all of the packages of the error without any problem. 
Is there anything else I am missing ?

**Comment by aoyawale** [comment]
`
u'Loaded plugins: fastestmirror, ovl\n', u'\x1b[91m\n\n One of the configured repositories failed (Unknown),\n and yum doesn\'t have enough cached data to continue. At this point the only\n safe thing yum can do is fail. There are a few ways to work "fix" this:\n\n 1. Contact the upstream for the repository and get them to fix the problem.\n\n 2. Reconfigure the baseurl/etc. for the repository, to point to a working\n upstream. This is most often useful if you are using a newer\n distribution release than is supported by the repository (and the\n packages for the previous distribution release still work).\n\n 3. Run the command with the repository temporarily disabled\n yum --disablerepo= ...\n\n 4. Disable the repository permanently, so yum won\'t use it by default. Yum\n will then just ignore the repository until you permanently enable it\n again or use --enablerepo for temporary usage:\n\n yum-config-manager --disable \n or\n subscription-manager repos --disable=\n\n 5. Configure the failing repository to be skipped, if it is unavailable.\n Note that yum will try to contact the repo. when it runs most commands,\n so will have to try and fail each time (and thus. yum will be be much\n slower). If it is a very temporary problem though, this is often a nice\n compromise:\n\n yum-config-manager --save --setopt=.skip_if_unavailable=true\n\nCannot find a valid baseurl for repo: base/7/x86_64\n\x1b[0m', u'Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was\n14: curl#7 - "Failed to connect to 2607:f8f8:700:12::10: Network is unreachable"\n', u'Removing intermediate container 0fdbb8298efb\\n']"}
`
looks like yum can't reach certain repos and fail to install.

**Comment by zochamx** [comment]
yes this is what I understood too, but this is happening only in specific task, otherwise yum can reach anything. I can perform `yum update` or `yum install <anything>`. The only way I was able to reproduce the error was via this playbook!

**Comment by aoyawale** [comment]
do you have any repo broken in /etc/yum.repos.d/ ? can you reach `http://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm`
and this 
`
Cannot find a valid baseurl for repo: base/7/x86_64\n\x1b[0m', u'Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container 
`

**Comment by zochamx** [comment]
Yes I can reach every repo I have, now I notice that it's trying to execute that, in a docker container so I added in `aws/installer/image_build/templates/Dockerfile.j2` my proxy as an ENV variable and I am waiting the build.

By adding the above in Dockerfile.j2 template the installation worked perfectly.
