### ISSUE TITLE
inventory file field doesn't show yaml file type

### ISSUE THREAD

**Issue by adrianovieira** [ansible/awx#9202]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Drop down list doesn't show `.yml` files

![image](https://user-images.githubusercontent.com/5561794/106498247-dfa97580-649d-11eb-8243-f7479344ac28.png)

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.16+
* Operating System: centos-7 also tried on centos-8
* Web Browser: firefox-85 or chromiun-87

##### STEPS TO REPRODUCE

create any `.yml` files on a source project, e.g.:
```
/ (root)
|__host
|__one.yml
|__/inventories
     |__common.ini
     |__another.yml
```
##### EXPECTED RESULTS

Also show _yaml_ files at the drop down list

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/5561794/106498247-dfa97580-649d-11eb-8243-f7479344ac28.png)

**Comment by jakemcdermott** [comment]
I think the file _detection and display_ is a known issue for some types of project configurations and inventory files: https://github.com/ansible/awx/issues/232#issuecomment-331244508 we don't have a fix planned for this any time soon.

cc @AlanCoding / @ryanpetrello / @chrismeyersfsu can confirm

That said, my understanding is that you should still be able to manually _type in_ any valid inventory file and have it work, even if that file isn't detected and displayed. We have a [PR open for that bug](https://github.com/ansible/awx/pull/9120) and it'll be included in an upcoming awx release.

cc @AlexSCorey

**Comment by jakemcdermott** [comment]
Closing - see https://github.com/ansible/awx/issues/9202#issuecomment-771692815

Looks like file detection and display is a known issue https://github.com/ansible/awx/issues/232#issuecomment-331244508 / wontfix and we'll have a patch merged into devel soon for manual type-in of inventory file names: https://github.com/ansible/awx/pull/9120

**Comment by TristisOris** [comment]
same problem.

awx 19.2.2
awx operator 0.12.0

**Comment by jseifeddine** [comment]
same problem Ansible AWX 23.5.2

**Comment by Pete1979** [comment]
same issue. 
awx operator 2.19.1.
awx 24.6.1
typing relative path does not work. it just pops back to / (project root) when entering a patch and hitting enter.
