### ISSUE TITLE
Does the new version of AWX support Chinese?

### ISSUE THREAD

**Issue by 1121437613** [ansible/awx#9204]
Does the new version of AWX support Chinese?
I deployed the latest version of AWX and the UI is in English. How can I change it to Chinese?

**Comment by AlexSCorey** [comment]
@1121437613 none of our strings have been translated yet.  We are still working on that.  Check back soon!

**Comment by jakemcdermott** [comment]
:wave: 

Yes - The new ui will have translations for all of the same languages that are available with the old ui. They'll be added in a future release of awx.

If you have any questions, please reach out to our community mailing list or join our `#ansible-awx` irc channel on freenode.

Thanks and happy automating!
