### ISSUE TITLE
[execution-environments] Image cleanup

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#9212]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Steps:

 - User creates a new EE that references a new custom image
 - Runs jobs with this EE
 - Deletes the EE through the API

Over time, the user accumulates bulky images, on the scale of 100s of Gb.

The API needs to provide some means of deleting both

 - Images no longer referenced by an execution environment in the API
 - Dangling images

If not, some users can run out of space.

**Comment by AlanCoding** [comment]
Locally, I find that the podman prune command isn't thorough enough, I get by that running

```
podman rmi $(podman images --filter "dangling=true" -q) -f
```

and I have to run this multiple times, unfortunately. I don't know what to tell you for the AWX solution here.

**Comment by jbradberry** [comment]
cc @unlikelyzero

**Comment by unlikelyzero** [comment]
Might need to be a management job

**Comment by shanemcd** [comment]
Some thoughts:

- This management job should only exist on installs where `settings.IS_K8S = False`.
- The command Alan mentioned in https://github.com/ansible/awx/issues/9212#issuecomment-771964900 should be good enough for us.

**Comment by shanemcd** [comment]
@fosterseth You can see an example of how the original management jobs were created here: https://github.com/ansible/awx/blob/devel/awx/main/migrations/0002_squashed_v300_release.py#L32-L53

**Comment by AlanCoding** [comment]
My for testing here is that we check to see if any unexpected images are present at the end of an integration test run.

**Comment by Zokormazo** [comment]
Tested manually, the cleaner works.

https://github.com/ansible/tower-qa/issues/6497 for automation debt
