### ISSUE TITLE
AWX 17.0.0 - Email notification cannot unselect Email Options to disable SSL/TLS

### ISSUE THREAD

**Issue by jjbaumgartner** [ansible/awx#9213]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Email notifications in AWX 17 require TLS/SSL email options to be set.  There is no way in the web interface to unselect the SSL/TLS options completely.

##### ENVIRONMENT
* AWX version: 17.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.16
* Operating System:  Debian Buster
* Web Browser:  Chrome 88.0.4324.104

##### STEPS TO REPRODUCE

1. Add a new Notification
2. Set **Type** to E-mail
3. Set other fields appropriately
4. Do NOT change **E-mail options** field
5. Click **Save**

##### EXPECTED RESULTS

Allow saving of notification with no email options selected.

##### ACTUAL RESULTS

Form alerts that Email options have not been selected.

##### ADDITIONAL INFORMATION

The email options field needs to allow the option of not using SSL or TLS.  Suggested action is to add "None" as an email option in the drop-down field.

We do not have SSL- or TLS-enabled SMTP relays internally.

Workaround:  I have manually updated the notification configuration behind the scenes by updating the database, setting both tls and ssl to false in the notification configuration.

**Comment by mabashian** [comment]
<img width="496" alt="Screen Shot 2021-02-03 at 2 15 58 PM" src="https://user-images.githubusercontent.com/9889020/106797236-5b382d80-662a-11eb-8112-eade6548fdf8.png">

There should be two checkboxes here instead of a dropdown.

**Comment by gitjon2015** [comment]
I agree that this update/version should not force SSL or TLS only for email.

In case it helps others to get simple email notifications working again while a fix is being worked on, I had to update my Notification template via api to set the following:

http://<your_url>/api/v2/notification_templates/<your_template_id/
under     "notification_configuration": 
 "use_ssl": false,
 "use_tls": false

**Comment by chapai518** [comment]
Please add a security disable for notifications, faced the same issue in the 18.0 release, temporarily bypassed as written in the comment gitjon2015 above.

**Comment by tiagodread** [comment]
Fixed.
