### ISSUE TITLE
Inventory Script Behaves Differently as Custom Script vs. Sourced From Project

### ISSUE THREAD

**Issue by hakan458** [ansible/awx#9217]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When using an inventory script as the source for an inventory, there is different behavior when getting the script from a git project versus a "custom script" through the UI.

I had to write a custom inventory script in order to sync inventory from a git project, due to some of the host vars being encrypted. There is no way to pass the vault key / vault-password-file to the inventory sync job on AWX, so I wrote a script which basically just runs ansible-inventory but I managed to pass the vault password file to it. When I save this script into AWX through the UI under Inventory Scripts, then under the inventory itself, choose this "Custom Script", it runs just as expected. 

I checked this same exact script into the git project itself, and chose it as the inventory source (sourced from a project), and it does not run the same way as it does when it is a "Custom Script" 

With the custom script:
```
Using base command: python /usr/bin/ansible-inventory -i /tmp/awx_608_0yrx4ggj/tmp7o5t0kkf --playbook-dir /tmp/awx_608_0yrx4ggj -vvvvv
```

With the same script sourced from git project:
```
Using base command: python /usr/bin/ansible-inventory -i /tmp/awx_606_ohqucyvf/project/inventories/development/get_inventory.py --playbook-dir /tmp/awx_606_ohqucyvf/project/inventories/development -vvv
```

So instead of the script running as ansible-inventory itself, the script is passed as an argument to the inventory flag, for the default ansible-inventory script it seems.

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker compose
* Ansible version:  2.9.10
* Operating System: Ubuntu
* Web Browser: Chrome

##### STEPS TO REPRODUCE

This script was written specifically to work with my git project but could modify it to make it work for another. Once again I tried many ways to get the inventory in AWX but all failed due to the fact that there are vault encrypted vars in the host_vars, and AWX does not provide a way to pass a vault key to inventory sync jobs (equivalent of --vault-password-file from cmd line). 

Put the following script in inventory scripts through AWX UI, and attach it as a source to an inventory. Run the script and it works as expected, all hosts are synced along with host vars, etc. 

With the same script, checked into my git project, and used as the source for the same inventory, does not work. I believe its due to the difference in the `ansible-inventory` command shown above.

```
#!/usr/bin/env python3

import json
import os
import subprocess as sp

project_root_dir = '/var/lib/awx/projects'
projects = os.listdir(project_root_dir)
napalm_fortinet_dir = ''

for directory in projects:
	if directory.endswith('napalm_fortinet'):
		napalm_fortinet_dir = directory

vault_key = os.getenv('AWS_SECRET_ACCESS_KEY')
vault_key_file = '/tmp/vault_key'
with open(vault_key_file, 'w') as outfile:
	outfile.write(vault_key)

os.chdir(os.path.join(project_root_dir, napalm_fortinet_dir))
result = sp.check_output("ansible-inventory -i inventories/development/hosts --list --vault-password-file {}".format(vault_key_file), shell=True)
result = result.decode('utf-8')
print(json.dumps(json.loads(result)))
```

##### EXPECTED RESULTS

I expect the script to produce the same results whether its run as a "Custom Script" or a inventory script sourced from my git project. 

##### ACTUAL RESULTS

When sourced from the git project it is unable to import the inventory

##### ADDITIONAL INFORMATION

The only way of passing my vault key to the inventory script was to put it in a credential type "AWS" because none of the vault keys I had stored in AWX credentials were showing up in the drop down for credential in the inventory source. Only one I got to appear was of type AWX. 

I could've avoided all of this if AWX had an option to pass a vault key to the inventory sync job.

**Comment by jakemcdermott** [comment]
:wave: Hello. We've actually removed `custom inventory scripts` entirely from the awx in the latest version. It's no longer a feature we support. Moving forward, you'll need to make sure that any inventory script you use works with the `ansble-inventory` command used by project-sourced inventories.

Thanks and happy automating.
