### ISSUE TITLE
[ui_next] Paging credentials closes the launch popup

### ISSUE THREAD

**Issue by jitteryjuice** [ansible/awx#9218]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After upgrading AWX from 14.1.0 (to 15.0.1 to 16.0.0) to 17.0.1 it has been noticed that if you launch a job template from the templates menu (that has been found via filtering, or via pagination) using the "Launch Template" button, and paginating the credential list results in the Modal popup closing and the URL that was filtered returning to the root templates URL.

If Launching the template from within the Template itself, the issue is not apparent. In summary, paginating the credentials in the popup modal from the templates list causes the root URL to reset and the filtering/pagination to be lost.

##### ENVIRONMENT
* AWX version: 17.0.0.1
* AWX install method: Kubernetes
* Ansible version:  2.9.17
* Operating System: Container host - Ubuntu Server, using awx container
* Web Browser: Chrome/Edge/Firefox/Brave

##### STEPS TO REPRODUCE

- Install AWX 17.0.1 using Kubernetes
- Configure multiple templates (to exceed default 20 per page)
- Paginate template list to 2nd page or higher
- Click "Launch Template" from one of the templates in the list
- Paginate the credential list
- Watch modal close, and the search results be reset

##### EXPECTED RESULTS

- The credential is selected and applied to the launch template

##### ACTUAL RESULTS

- The launch template modal is closed, search filter emptied and the progress lost
- The URL in the address bar is reset prior to launch template is clicked

##### ADDITIONAL INFORMATION

- The time between modal closing and URL change is too fast for screen capture
- Can upload additional photos upon request
- URL Changes Observed
  - URL in Template List before launching template: https://awx.my.domain/#/templates?template.page=2
  - URL after paginating credential list: https://awx.my.domain/#/templates?credential.page=2
- Happy to provide a PR, however I am not too familiar with react/the code base surrounding the issue. If pointed in the right direction, id be happy to do further investigation into the issue.

**Comment by MrBones757** [comment]
I will also be able to provide info here in addition to @j-shade as we have access to the same instance / environment

**Comment by mabashian** [comment]
Here's the bug in action

![cred_page](https://user-images.githubusercontent.com/9889020/106796630-9b4ae080-6629-11eb-89a6-d0e9a50e40c9.gif)

**Comment by MrBones757** [comment]
@j-shade and I attempted to have a look at this issue today locally, but our lack of react experience wasn't particularly helpful and we didn't get very far.

**Comment by ghost** [comment]
I am also seeing this issue on 17.0.0 either by paging through credentials in wizard or doing a search.  Sometimes if you paginate slowly (i have more than 2 pages of credentials), it does not close.

**Comment by ghost** [comment]
Still an issue in 17.1

**Comment by emulanob** [comment]
Also seeing this fairly regularly on 17.1.0. As a workaround, I launch the template from the template page, and not from the templates list.

**Comment by akus062381** [comment]
this issue is resolved

**Comment by rchaud** [comment]
@akus062381 @emulanob @csdozier @j-shade Are you guys still experiencing this issue? It seems I am having it in 21.14.0 when I change a Credential Type from Machine to VMware the popup closes on its own.
