### ISSUE TITLE
Passing a bad lookup type modifier in api request triggers 500 error

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#9222]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Send a request like `/api/v2/jobs/?id__iexact=1`

<img width="1680" alt="Screen Shot 2021-02-03 at 12 28 26 PM" src="https://user-images.githubusercontent.com/9889020/106785392-56b84880-661b-11eb-9288-fa50845636f7.png">

`iexact` isn't supported on the `id` field.  What I'm hoping for is a nice 4xx error that says that modifier is not supported.

The impetuous for this issue came from https://github.com/ansible/awx/issues/7834.  The advanced search in the UI allows the user to select from a static list of modifiers in the `Advanced` section.  I left that issue open as a UI enhancement to attempt to trim that list down to only modifiers that will work with a particular field.

**Comment by AlanCoding** [comment]
@sarabrajsingh are you still working on this right now? If now I'd like to keep it in the On Deck issues for anyone to pick up as able.

**Comment by rebeccahhh** [comment]
There is a theory that this may change with the in progress Django upgrade. 
@jbradberry I believe recommended this wait until that's complete to recreate/resolve.

**Comment by AlanCoding** [comment]
Marked as blocked

**Comment by AlanCoding** [comment]
Confirmed that `/api/v2/jobs/?id__iexact=1` gives a 500 with current devel. I believe this is ready to be worked on.

**Comment by jay-steurer** [comment]
PR merged. Closing it.
