### ISSUE TITLE
Inventory host search using equals rather than contains

### ISSUE THREAD

**Issue by djj106** [ansible/awx#9226]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Searching for a host in inventory looks for an exact match rather than using contains. Searching for other things (job templates, etc) use the contains method. I'm assuming they should all be using contains to be consistent.

Url example when searching for a host in inventory:
https://awx.company.net/#/inventories/inventory/2/hosts?host.name=demo

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by mabashian** [comment]
Yea, it should be `__icontains` by default to match the UX of the other lists.

**Comment by AlexSCorey** [comment]
This was resolved by https://github.com/ansible/awx/commit/0ac6ba9c99097a0a7d175dba731d36ac205759c3
![Screen Shot 2021-06-18 at 10 46 59 AM](https://user-images.githubusercontent.com/39280967/122579200-ab84ba80-d022-11eb-9ff7-f8fcae5b1c22.png)
