### ISSUE TITLE
Inventories Variable text box does not pop out or expand

### ISSUE THREAD

**Issue by derekleegh** [ansible/awx#9228]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 17.0.0
* AWX install method: docker on linux
* Ansible version: 2.9.16
* Operating System: Linux
* Web Browser: Chrome

##### STEPS TO REPRODUCE

The inventory variable box does not expand anymore like it used to be. 
![image](https://user-images.githubusercontent.com/32130581/106833943-568e7a80-66f9-11eb-810e-999ebeec694f.png)

This increases the difficulty to format properly Ansible vault values as well as YAML format.

Can we bring back the pop out of the variable box please?

Cheers

**Comment by jakemcdermott** [comment]
Hi @guohaolee 

This is on our radar and will be added to the new ui in an upcoming awx release.

See: https://github.com/ansible/awx/issues/8031

Thanks and happy automating.
