### ISSUE TITLE
[ui_next] Template launch prompt can only utilize one custom credential at a time

### ISSUE THREAD

**Issue by jitteryjuice** [ansible/awx#9230]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Launching a template with custom credentials (or a template without and adding one), then selecting a secondary custom credential replaces the first. Custom credentials are showing as "cloud" credentials, despite being a different custom credential type in the credential list.

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: Kubernetes
* Ansible version:  2.9.17
* Operating System: Ubuntu Base, AWX Container
* Web Browser: Chrome/Edge/Firefox

##### STEPS TO REPRODUCE

1. Launch a template
2. Select Inventory
3. Select a custom credential
4. Select a secondary, different custom credential
5. Watch the first custom credential be replaced

##### EXPECTED RESULTS
Both custom credentials to be in the credential list for the template launch modal

##### ACTUAL RESULTS
Only the last selected custom credential is appearing in the credential list, with the previous being replaced by the most recently selected one.

##### ADDITIONAL INFORMATION
First selected custom credential:
![custom_credential_existing](https://user-images.githubusercontent.com/8851024/106838499-62694500-66d7-11eb-8a82-d6a4891c1e80.png)
Secondary custom credential:
![custom_credential_replaced](https://user-images.githubusercontent.com/8851024/106838516-6d23da00-66d7-11eb-914b-96398ccc6ba6.png)

**Comment by jakemcdermott** [comment]
> Select a secondary, different custom credential

Thanks @j-shade - good find. Each custom credential type should be it's own category in the dropdown and you should be able to select at least one of each.

**Comment by maksym-bordun-ynd** [comment]
The issue was already described in https://github.com/ansible/awx/issues/8878, but no news since then.

**Comment by unlikelyzero** [comment]
Need to add a stub for this one and retest

**Comment by akus062381** [comment]
All set.
