### ISSUE TITLE
AXW Smart Inventory advanced host filter not working at GUI

### ISSUE THREAD

**Issue by tgoehler** [ansible/awx#9232]
##### COMPONENT NAME
 - UI

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux,
* Ansible version:  2.9.17
* Operating System: CentOS7
* Web Browser: Firefox 84.0.2

##### STEPS TO REPRODUCE
tried to create a smart inventory with advanced type  host filter like:
name__exact=localhost or name__regex=b[12]-worker

when defining the filter the host are selected fine. After pressing "Select" and returning to the particular  inventorys details edit window and the smart host filter field is empty. Now when pressing save I get "An server error has occurred"

 If I define the filter through the API it works

POST
/api/v2/inventories/

{
    "name": "testinventory",
    "description": "",
    "organization": 2,
    "kind": "",
    "host_filter":  "name__regex=b[12]-worker or name__exact=localhost",
    "variables": "",
    "insights_credential": null
}

##### EXPECTED RESULTS
I expect the that the constucted filter is accepted after pressing "Select"

##### ACTUAL RESULTS

GUI unusable to create smart inventories using advanced host filters

##### ADDITIONAL INFORMATION
I saw a similar issue raised in 2018 which is tagged as closed but it seems not to be the case

**Comment by tgoehler** [comment]
**Issue Type:**
- Bug

**Comment by tgoehler** [comment]
sorry, the correct Json looks like this
{
"name": "testinventory",
"description": "",
"organization": 2,
"kind": "smart",
"host_filter": "name__regex=b[12]-worker or name__exact=localhost",
"variables": "",
"insights_credential": null
}

**Comment by unlikelyzero** [comment]
@jakemcdermott I'm going to attach this to our Advanced Search Meta Issue https://github.com/ansible/awx/issues/8480

**Comment by unlikelyzero** [comment]
From a duplicate issue:

Prequisites: one inventory with one group "centos" and a second group "ubuntu" server

1. Create a smart inventory based upon existing groups (ie. "centos" or "ubuntu")
2. Create a host filter advanced search with an "or" selection
   1. Name --> advanced
   2. Key --> groups
   3. LookupType --> icontains --> centos --> search
   4. LookupType --> icontains --> ubuntu --> search
   5. Result: all linux centos and ubuntu hosts
   6. Select
3. Save --> Error: Invalid query groups__search=ubuntu and groups__search=centos

With the use of the AWX cli the following search filter is working
awx-cli inventory create --name "Linux_Test_Group_OR" --organization 5  --kind smart --host-filter "groups__name__icontains=centos or groups__name__icontains=ubuntu" -d "All Linux server" -v

After the execution this Smart inventory is visible and can be used on the related hosts

**Comment by kladiv** [comment]
+1
In my opinion it's an high priority issue

**Comment by unlikelyzero** [comment]
still accurate

**Comment by rverhe** [comment]
Have the same issue. During the query build i get the matched hosts! 
But after the save it shows 0 hosts in the dynamic inventory.
Also having no luck with the api call: ?host_filter with the same params.

**Comment by Thomastouma** [comment]
Experiencing the same issue.

Building a smart inventory filter query and displaying the hosts matching the filter works, but when saving the smart inventory an error is displayed stating that the query is invalid.

`filter_url: smart_hosts.inventory_sources__search=icinga2_dynamic&smart_hosts.variables__regex=^((%3F!%3B).)*%24`

I get the same error message when trying to build the smart inventory from awx-cli.
`awx-cli inventory create --name "hosts_with_single_ip" --organization 3 --kind smart --host-filter 'inventory_sources__search=icinga2_dynamic&variables__regex=^((?!;).)*$'`

**Comment by nixocio** [comment]
Note that `not` operator is not implemented yet - https://github.com/ansible/awx/issues/2817#issuecomment-663692907

**Comment by mabashian** [comment]
@nixocio I moved this to `in_progress` since I know you're actively working on this one and we've talked about it.

**Comment by tiagodread** [comment]
#10347 adressed part of this issue, I've filed #10400 to keep track on a different bug found while working on this.

**Comment by DnaMes** [comment]
+1

**Comment by marilinnerud1** [comment]
+1
