### ISSUE TITLE
Unable to launch two instances of AWX on same host in parallel

### ISSUE THREAD

**Issue by jheinitz** [ansible/awx#9233]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Moin!

Before upgrading my production instance of AWX, I tried to bring up a second instance of AWX on the same server to validate the upgrade process. I ran the install.yml playbook and specified a different compose directory and pgdocker directory. Finally the install.yml playbook was unable to bring up the second instance of AWX because the container names awx_redis, awx_postgres etc. are already in use by the first instance. 

The deployed docker-compose.yml file should have an option to customize the names or add an optional additional extention to avoid this kind of name clash.

Furthermore I would like to thank all of you for your great work. This is really a great tool! Keep on going!

Best regards

Jens

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.17
* Operating System: CentOS Linux 8
* Web Browser: Google Chrome

**Comment by wenottingham** [comment]
The docker-compose installer is being removed. See https://github.com/ansible/awx/issues/9125 and https://groups.google.com/g/awx-project/c/47MjWSUQaOc/m/1-Jh0fy3AgAJ.

Because  of that, this isn't something we'll work on.
