### ISSUE TITLE
 Сhange font color or return white theme

### ISSUE THREAD

**Issue by ronik010** [ansible/awx#9234]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

We are using awx 17.0.0.
Is there any way to customize the font color in the job output or return the white theme?

**Comment by jakemcdermott** [comment]
:wave: Hello. There isn't a way to customize the color scheme at the moment. A prerequisite for this is a user-preferences system - this is a new feature that we hope to get to in the future, and you can read about it here: https://github.com/ansible/awx/issues/278
