### ISSUE TITLE
Execute Job for Host

### ISSUE THREAD

**Issue by DanyD** [ansible/awx#9236]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
As user we have very often the case that we need to trigger a job for a specific host. This is not always the full inventory and many times a manual selection. To make this step easier I am missing two different navigation / ux scenarios:

**Lookup of hosts in "LIMIT" field** 
In this case we are using the Templates and launch a template. After we select the group we already have the ability to show a "LIMIT" field to specify only certain hosts. This LIMIT field could be extended to already display a select list of all hosts as suggest in this selected inventory to facilitate selection and avoid input errors due to manual writing. The select list should include hostname AND description.

**Start a job coming from the hosts lists**
In this case we are navigating the inventory host table. Similar to the Run Command multi host option above the table we suggest a "Run Job" which allows us to select a Job Template and passes the selected hosts to the Job Template as default values

**Comment by wenottingham** [comment]
This is https://github.com/ansible/awx/issues/1179, closing as duplicate

**Comment by DanyD** [comment]
I would suggest to keep the "Start a job coming from the host list"as a separate issue as this reflects a slightly different use case. What do you think?
