### ISSUE TITLE
UX - Wizard Button Order

### ISSUE THREAD

**Issue by DanyD** [ansible/awx#9237]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

![image](https://user-images.githubusercontent.com/2473614/106886068-bf6af800-66e3-11eb-83ad-9de39575f364.png)

Just a small subjective suggestion, but I felt that the order of the buttons in the Wizard is a bit strange at least compared to the typical wizard interfaces. I would suggest to place the Cancel link on the left hand side and place the next and back button on the right hand side in swapped order. 

| CANCEL  ..................................................................................   BACK  |  NEXT > |

**Comment by AlexSCorey** [comment]
@DanyD Thanks for reaching out to us.  We always want to hear from our users. You are touching on something that we also had a conversation about but came the decision about button placement with the help of patternfly, our component library.  You can read a bit more [here](https://www.patternfly.org/v4/components/button/design-guidelines#button-placement ) and on the patternfly [blog](https://medium.com/patternfly/button-placement-on-forms-aa57a81f7d)
