### ISSUE TITLE
Limits are not applied in templates of a workflow

### ISSUE THREAD

**Issue by lcarangelo** [ansible/awx#9241]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

https://docs.ansible.com/ansible-tower/latest/html/userguide/workflow_templates.html
PARAGRAPH 7
If a job template used in the workflow has Prompt on Launch selected for any of its parameters, a Prompt button appears, allowing you to change those values at the node level. Use the wizard to change the value(s) in each of the tabs and click Confirm in the Preview tab.

This does not work for LIMIT (it was working on versione 12 ).
Please let me know as soon it's fixed. Version 17.0.1 (also 17.0.0) is unusable.

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  9.8
* Operating System: CentOS 7
* Web Browser:

##### STEPS TO REPRODUCE

Create a workflow without inventory and limit.
Build the workflow with at least one template that with prompt on lunch for inventory and limits.
Use wizard to change inventory and limits (choose only one server of your inventory) and save.
Run the workflow .
During the execution limits are not applied on templates that is executed on all servers of the inventory instead.

**Comment by sangdrax8** [comment]
I believe I am seeing this as well.

To be clear, in my case if there is a Template, that is then used in a single Workflow.  Limits are applied.

The following limit is passed into the template from the workflow
- Delete VM Template
- - Limit set to prompt
- Delete Workflow using Delete VM Template
- - Limit set on launch and passed to the template in question

What doesn't work, is then using THAT workflow in another workflow.

- Delete group Workflow
- - Using Delete Workflow above
- - Select limits from prompt for multiple copies of Delete Workflow

The Main workflow here doesn't set limits, but picks them from the prompts for each instance it builds up.  When launching, the limits are not passed in and it is run against the entire inventory

**Comment by sangdrax8** [comment]
I stand corrected.  I thought this was working partially, however it seems it is worse than I expected.  The only limit I seem to get working is if a Workflow prompts and sets the limit for all templates in the workflow. 

If I don't prompt at the workflow level, and try and pick a limit per template in the workflow directly, those templates do not get the limit applied.

I am testing version 15, and seeing this issue.  We are testing 17.01 but the above reports indicates I will likely not see this working there either.

**Comment by mabashian** [comment]
> If I don't prompt at the workflow level, and try and pick a limit per template in the workflow directly, those templates do not get the limit applied.

Expanding on the test case here:

1) Create a workflow job template that does not have a default limit and does not prompt for limit
2) Create a job template that does have a default limit `foo` and does prompt for limit
3) Go to visualizer for workflow from step 1
4) Add a node that points to the job template from step 2
5) Apply a new limit `bar` while creating the node from step 4
6) Save workflow
7) Launch workflow
8) Navigate to node job and notice that limit is not `bar` but `''`

**Comment by nixocio** [comment]
This issue seems to be fixed as a side effect of https://github.com/ansible/awx/pull/10195. I got a commit before that fix was added and the issue was present there, I got the latest devel and the issue was not there anymore.
