### ISSUE TITLE
Navigating back from the job template launch page from the Job Launch Details page will result in critical failure

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#9246]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When navigating to container group description by going through the details page of a job template, and then clicking the back button, the app has a critical error only visible in development and not production.

##### STEPS TO REPRODUCE

Click on the Templates menu button on left side of screen.
Navigate to the third screen of job template options.
Find and click on the job template called Test Template.
Click the Launch button.
Click on the Details menu button.
Click the link given for the Container Group name (in this case, 'Name of test group').
After page loads, click the back button one time.
Click back a second time. The bug should appear.
If it does not, click back one more time and then click the forward button. Somewhere in this navigating you will see the error appear.

##### EXPECTED RESULTS

The user should be able to click back or forward button without issues and be able to navigate the site.

##### ACTUAL RESULTS

A TypeError message appeared.

![Screen Shot 2021-02-04 at 5 12 58 PM](https://user-images.githubusercontent.com/63685497/107049770-82147200-6798-11eb-85f8-ab693f33292f.png)

**Comment by AlexSCorey** [comment]
I can't reproduce

**Comment by unlikelyzero** [comment]
stub

**Comment by akus062381** [comment]
This has been fixed.
