### ISSUE TITLE
Allow Instance Groups to be attached to Projects

### ISSUE THREAD

**Issue by hjkatz** [ansible/awx#9247]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

According to the [instance group docs](https://docs.ansible.com/ansible-tower/3.8.1/html/administration/external_execution_envs.html#instance-groups) an Instance Group can be assigned to the following:
* Job Template
* Inventory
* Organization (by way of Project)

What's up with that last one? Why can't we attach Instance Groups directly to Projects?

I think this makes the most sense (even more than attaching to Organization or Inventory). Here's my reasoning:

Projects contain the source code of the playbooks/roles/tasks/plugins that will be run with `ansible-playbook`. These playbooks/roles/etc contain syntax that's _specific to an ansible environment_ such as ansible version, ansible settings/configuration, and even which plugins/collections/python-packages are enabled/disable/available. Since the boundary of dependencies exists within the Project and since Organizations can have multiple Projects, then it makes the most sense to me that Projects should be able to specify an Instance Group. This is because Instance Groups strictly represent exactly the dependencies needed for a Project's source code to execute _correctly_! Instance Groups help to configure the python packages/dependencies as well as other environmental settings for ansible (such as version or configuration via envars).

What do y'all think?

**Comment by wenottingham** [comment]
Yes, that makes sense. But as we're moving the content/plugins/python/etc to execution environments, that's what we'd want to potentially attach to a project, not an instance group.

Closing this, as this will be solved at the EE layer, not the IG layer.

**Comment by hjkatz** [comment]
@wenottingham What do you mean by "execution environments"? For the case of Instance Groups we're using Container Groups. Perhaps I'm reading the wrong documentation, could you point me in the correct direction?

**Comment by wenottingham** [comment]
See https://github.com/ansible/awx/issues/5157 - all execution is moving to containerized execution in what are called 'execution environments' (ansible + collections).

As a side effect of that overall move, we'll have a new iteration of container groups that is enhanced to run with an aribitrary execution environment (and not require the definition on the container group).

**Comment by hjkatz** [comment]
Beautiful, thank you! I look forward to that feature :)
