### ISSUE TITLE
Unable to Clone SCM on Kubernetes

### ISSUE THREAD

**Issue by jacobwoffenden** [ansible/awx#9248]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Initial source control update fails

##### ENVIRONMENT
* AWX version: 17.0.0
* AWX install method: Kubernetes
* Ansible version:  2.9.16
* Operating System: n/a 
* Web Browser: n/a

##### STEPS TO REPRODUCE

Deploy AWX 17.0.0 to Kubernetes with `task_security_context_privileged: 'false'`
Configure SCM redential
Configure git project

##### EXPECTED RESULTS

For initial SCM update to pass

##### ACTUAL RESULTS

Fails with 

```
bwrap: No permissions to creating new namespace, likely because the kernel does not allow non-privileged user namespaces. On e.g. debian this can be enabled with 'sysctl kernel.unprivileged_userns_clone=1'.
```

**Comment by jacobwoffenden** [comment]
Looks like a duplicate of https://github.com/ansible/awx/issues/5224. Unfortunately I am unable to run privileged containers

**Comment by wenottingham** [comment]
Yes, it is. We're getting past that soon, but not in 17.x. Closing as a duplicate.

**Comment by jacobwoffenden** [comment]
Thanks, @wenottingham. Have implemented https://github.com/ansible/awx/issues/7916#issuecomment-676564985 for now.
