### ISSUE TITLE
Run Inventory Sync Jobs on Instance/Container Groups

### ISSUE THREAD

**Issue by EStork09** [ansible/awx#9253]
##### ISSUE TYPE
 - Ability to run Inventory Sync jobs for Inventory Sources on Instance or Container Groups

##### SUMMARY
Currently today when you run an inventory sync job despite having an instance group selected the job will always run on the tower awx-task container. If there is an instance group or container group in the environment, you cannot use that to pull the inventory source, resulting in awx having direct access to that inventory source along with the instance/container groups. Is there a way that we could run the inventory sync job on the instance group and pull the information similar to a regular job template?
This would also reduce the need to introduce additional venv (with additional inventory packages) on the awx instance and reduce the amount of jobs running on the tower instance group.

**Comment by wenottingham** [comment]
See https://github.com/ansible/awx/issues/9247#issuecomment-774224343 ; this is in the process of changing, and the instance group isn't quite the right model here.

**Comment by blomquisg** [comment]
@shanemcd do we already have a plan for this in our Execution Environment model?

**Comment by shanemcd** [comment]
Yes, under the new model, Inventory Syncs will no longer happen on the control plane. They will effectively behave the way that's described here.

**Comment by bergmannf** [comment]
When using the newest version of the AWX operator it is already deploying the new support for execution environments, but those are not correctly syncing the inventory sources either (it seems to be a path issue though) - might this be related to this new model?

More information is here https://github.com/ansible/awx-operator/issues/146 - as I am very uncertain if this is related to the EE model or only to the AWX operator.

**Comment by kladiv** [comment]
Same issue https://github.com/ansible/awx/issues/9704

**Comment by one-t** [comment]
Verified that inventory syncs are now happening in the container group. This is now working as expected
![sync](https://user-images.githubusercontent.com/28987580/114632503-acd8e600-9c73-11eb-97c3-bda2748f9dee.gif)

**Comment by maveleo** [comment]
> Verified that inventory syncs are now happening in the container group. This is now working as expected ![sync](https://user-images.githubusercontent.com/28987580/114632503-acd8e600-9c73-11eb-97c3-bda2748f9dee.gif)

The source sync for an inventory is still happening on the default group in 19.X 
Has this been verified in a version > 17.1.0 ? 
I filed this in https://github.com/ansible/awx/issues/11542
