### ISSUE TITLE
Relax client-side email validation rules

### ISSUE THREAD

**Issue by dertom** [ansible/awx#9254]
I want to setup the email address awx@ser02.anti.design for notification, but awx said "invalid email address".

**Comment by ryanpetrello** [comment]
Hey @dertom,

Can you update or refile this issue with the details requested in the New Issue template (including awx version, etc)?

https://github.com/ansible/awx/issues/new?assignees=&labels=&template=bug_report.md

**Comment by tchellomello** [comment]
@ryanpetrello  It happens on AWX 17.0.1 

![image](https://user-images.githubusercontent.com/809840/107276160-a2566200-6a20-11eb-9737-c18cac765e00.png)

**Comment by dertom** [comment]
##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.17

I hope thats anything you need. Thank you!

**Comment by mabashian** [comment]
link https://github.com/ansible/awx/pull/9290

**Comment by unlikelyzero** [comment]
Covered in unit tests added to attached PR:

https://github.com/ansible/awx/pull/9290
