### ISSUE TITLE
[db_partitioning] implementing bigint-style migration

### ISSUE THREAD

**Issue by jladdjr** [ansible/awx#9257]
Current migration is a simple / naive `insert` that dumps all rows. Want to handle this instead the same way that we did here:

https://github.com/ansible/awx/blob/devel/awx/main/migrations/0113_v370_event_bigint.py

**Comment by jladdjr** [comment]
The bigint style migration uses [FakeAlterField](https://github.com/jladdjr/awx/blob/db_partition/awx/main/migrations/0113_v370_event_bigint.py#L93) which allows us to:
* use raw sql to make changes
* while still letting django know about the model changes

That is clever.

**Comment by ryanpetrello** [comment]
<img src="https://www.reactiongifs.us/wp-content/uploads/2013/03/oh_i_get_it_fight_club.gif">

**Comment by jladdjr** [comment]
oh, gosh, now I'm going to have to rewatch that

**Comment by jladdjr** [comment]
This just in from @jbradberry:
https://django-postgres-extra.readthedocs.io/en/master/table_partitioning.html#table-partitioning

Digesting that now.

**Comment by ryanpetrello** [comment]
Hey, that's a great find!

**Comment by jladdjr** [comment]
yeah, seriously, this could be a game-changer

**Comment by ryanpetrello** [comment]
I think my biggest question is what migration from a normal table to partitions *looks like* with this (just to make sure it's not slow/imperformant for our scale).

**Comment by jladdjr** [comment]
right, was just wondering the same thing. the example seems to create something from scratch, haven't seen a migration to something partitioned

**Comment by jladdjr** [comment]
@jbradberry also just pointed out that this is a 3rd party library. In response, I asked him how "wild west-y" 3rd party django libs can be. Trying to dig into that a bit.

https://github.com/SectorLabs/django-postgres-extra

![image](https://user-images.githubusercontent.com/4440360/107281462-8fd32d00-6a0e-11eb-94d0-581a30914bfb.png)

What has our experience with 3rd party django libs been like to date?

**Comment by jladdjr** [comment]
Having read through django-postgres-extra's overview, I'm wondering if it's worth adopting this 3rd party library. They mention "an experimental helper class that can be called periodically to automatically create new partitions". If this weren't experimental and we could outsource partition creation to something stable I think I'd be more sold on this. As it stands, though, while I was reading through this I found myself thinking "what does that give us beyond doing a sql command to get that done?" The answer that kept coming to mind was "the liability of using a 3rd party lib for a tricky operation".

I'm not sure if I want to jump to using a 3rd party for something like this. If it solidifies, maybe we migrate to something like this in the future? I think I'm afraid of a 3rd party lib doing something strange that I don't understand more than I'm afraid of raw SQL at this point.

**Comment by ryanpetrello** [comment]
> an experimental helper class that can be called periodically to automatically create new partitions

Yea, I have the same read.  I'd recommend getting something basic implemented w/ SQL before involving additional third-party Django plugins. If we want to refactor or improve our approach later, we can.

**Comment by jladdjr** [comment]
The bigint migration -- as in, the literal migration itself -- seems to be only a part of what's needed in order to migrate events asynchronously / in the background. 

Full bigint context here:
https://github.com/ansible/awx/pull/6032/files

In particular there's:
* https://github.com/ansible/awx/pull/6032/files#diff-260d2b10b9e9600fbed330085498bd672c178a823afd195a0bf61cd8941bd05fR83, and
* https://github.com/ansible/awx/pull/6032/files#diff-6fb7bd98930ec6a05c1ae9296b41b63921e1813dcee53895f16769f910917c38R705

.. for migrating events.

**Comment by jladdjr** [comment]
@ryanpetrello spun up a pre-4.0 instance, loaded it with a reasonable amount of data, attempted a migration to partition tables and the result was a never ending migration

.. plus he pointed out that the naive migration duplicates all the rows, _then_ removes the original batch, which will double the disk space.

Both of those won't work in the perfscale env, so he's looking into getting this working. Things seem promising so far.

**Comment by jladdjr** [comment]
@ryanpetrello pointed out how we've had a table-to-table async migration lying dormant, that we can maybe re-purpose and flip on:
https://github.com/ansible/awx/commit/16848e9154b5a15e1051439c491d20d6feb03e23#diff-6fb7bd98930ec6a05c1ae9296b41b63921e1813dcee53895f16769f910917c38

@ryanpetrello also pointed out that the 3.8 bigint migration is no longer needed because of deprecated tower versions.

**Comment by jladdjr** [comment]
Knocked this out with a ton of help from @ryanpetrello - thank you!
