### ISSUE TITLE
[db_partitioning] adapt job runs to use new partitioned tables

### ISSUE THREAD

**Issue by jladdjr** [ansible/awx#9259]
In order to create partitions, the job_event tables will need to have a new, denormalized column. Update job runs to ensure that when we're saving events, our saves / inserts take the new column into account.

**Comment by jladdjr** [comment]
I _thought_ that what I was doing [here](https://github.com/jladdjr/awx/blob/1ed34380bb4c1e7354e0431a3371be789d04a08a/awx/main/migrations/0124_event_partitions.py#L43) would work, but after doing the raw sql update to add a new column, Django is left in the dark about the new column's existence.

![image](https://user-images.githubusercontent.com/4440360/107272193-31a04d00-6a02-11eb-9019-d851a452075b.png)


Chatted with @jbradberry who looked at looked at https://github.com/jladdjr/awx/blob/db_partition/awx/main/migrations/0113_v370_event_bigint.py and spotted how that handles things correctly. I knew the bigint migration made things more _performant_ but didn't realize it was handling the row addition differently. Studying that now to see how I can adapt that. May just adapt the whole approach since we want this to be performant anyways.

**Comment by jladdjr** [comment]
yep, I need this:
https://github.com/jladdjr/awx/blob/db_partition/awx/main/migrations/0113_v370_event_bigint.py#L77-L82

**Comment by jladdjr** [comment]
think we want something like this:

![image](https://user-images.githubusercontent.com/4440360/107285895-a8464600-6a14-11eb-8c9c-fcf99c4695d3.png)

Using FakeAdd instead of FakeAlter. Tweaked the model's args to what I think should be the appropriate values.

**Comment by jladdjr** [comment]
This tells Django about the field's existence, but doesn't actually insert the job_created value when we're defining events. That will be the next thing to figure out if this works.

**Comment by jladdjr** [comment]
reverting awx to test changes - rough notes:

![image](https://user-images.githubusercontent.com/4440360/107291143-8bae0c00-6a1c-11eb-914f-cdd27396a7ab.png)

---

.. as [script](https://gist.github.com/jladdjr/f0a842a7e24ac63cda87f461a8f13fae)

**Comment by jladdjr** [comment]
Looks like after doing a partition I can still see events from an old job:

![image](https://user-images.githubusercontent.com/4440360/107292541-e21c4a00-6a1e-11eb-9091-25291bff6a53.png)

![image](https://user-images.githubusercontent.com/4440360/107292623-02e49f80-6a1f-11eb-9f24-792465d7ba16.png)


Still need to update other job things, I'm sure, but that's nice to see

**Comment by jladdjr** [comment]
Ran a regular job, fails so save events because of our new column:

![image](https://user-images.githubusercontent.com/4440360/107292895-7090cb80-6a1f-11eb-979d-ebf78836a839.png)

`psycopg2.errors.NotNullViolation: null value in column "id" violates not-null constraint`.

Not surprising, time to fix this.

**Comment by jladdjr** [comment]
minor changes pushed earlier to get new main_jobevent column registered with Django. One key thing that I verified here is that [by default model fields are not allowed to be null](https://docs.djangoproject.com/en/3.1/ref/models/fields/#blank), which will be important with the column that we're keying off of to determine which partition a given row belongs to:

https://github.com/jladdjr/awx/commit/2e54a4dfeee06317a48ca794b74c28e85e7ff953

**Comment by jladdjr** [comment]
have been poking around [CallbackBrokerWorker -> perform_work()](https://github.com/jladdjr/awx/blob/db_partition/awx/main/dispatch/worker/callback.py#L128):

* .. running sdb to better understand how events are created and saved
* .. seeing how we can access the associated unified job
* .. thinking about how we could look up the UJ's creation date and cache it (to avoid adding 1 DB lookup per event 😨 ) since anything in the callback receiver is going to be super-sensitive performance wise

Putting a bookmark in things here, ran out of time for now. Will pick back up tonight / tmrw.

**Comment by jladdjr** [comment]
Continuing to poke around. After making some test changes to set a dummy date for `job_created`, I'm getting:
![image](https://user-images.githubusercontent.com/4440360/107322459-5f64b080-6a59-11eb-8855-0b9889bda1f7.png)

.. so I think I broke an index for id.

**Comment by jladdjr** [comment]
Things _seem_ okay..

![image](https://user-images.githubusercontent.com/4440360/107323365-fc741900-6a5a-11eb-855d-a13af49e4561.png)

nope, I think I dropped the sequence somehow:
![image](https://user-images.githubusercontent.com/4440360/107323801-c6836480-6a5b-11eb-88b8-98b97f311a82.png)

**Comment by jladdjr** [comment]
Got it - when copying the table I needed to _at least_ use `INCLUDING DEFAULTS` (setting the next value of a column using a sequence is a kind of default, apparently, which makes sense). I say 'at least' because now I'm seeing that I didn't use `INCLUDING ALL` which is [what the bigint migration did](https://github.com/jladdjr/awx/blob/db_partition/awx/main/migrations/0113_v370_event_bigint.py#L34). I'll try using that.

**Comment by jladdjr** [comment]
[Pushed](https://github.com/jladdjr/awx/commit/011c7dcd206366a80d1cdeb7728f698842de1ca3). Turning the crank (resetting the db) to see if that fixed things.

**Comment by jladdjr** [comment]
![image](https://user-images.githubusercontent.com/4440360/107324967-cab08180-6a5d-11eb-9fd8-266f46057faf.png)

![image](https://user-images.githubusercontent.com/4440360/107324998-d603ad00-6a5d-11eb-89f7-67116ef362df.png)

Constraint violated. Seems like bringing in main_jobevent's metadata and trying to create a partitioned table at the same time crossed the streams. Need to find out why.

This happened while awx was running the migration, well before I even had a chance to run any jobs.

**Comment by jladdjr** [comment]
https://www.postgresql.org/docs/current/ddl-partitioning.html provides some background on what's happening here (under the Limitations section):

![image](https://user-images.githubusercontent.com/4440360/107325901-6989ad80-6a5f-11eb-99b7-c618c593e9e2.png)

looking at the original (pre-partioning) schema for main_jobevent (from a pg_dump):

![image](https://user-images.githubusercontent.com/4440360/107325588-dc465900-6a5e-11eb-8ef5-b7c6b78a98cc.png)

![image](https://user-images.githubusercontent.com/4440360/107326224-eb79d680-6a5f-11eb-82b5-6e7cce170bd9.png)

The `PRIMARY KEY` constraint implies uniqueness.

Calling it a night, but will need to figure out how to:
* keep `id` set as a primary key
* .. while also satisfying the requirement that `Unique constraints (and hence primary keys) on partitioned tables must include all the partition key columns`.

I can half-see what they're asking for there, but will need to search around and try to see how other folks handle this.

**Comment by jladdjr** [comment]
where were we? that's right, I broke an index, let's see about that

**Comment by jladdjr** [comment]
https://www.postgresql.org/docs/current/sql-createtable.html

![image](https://user-images.githubusercontent.com/4440360/107441912-f594e700-6aea-11eb-87de-96efade60b65.png)

**Comment by jladdjr** [comment]
> PostgreSQL can only enforce uniqueness in each partition individually.

I think this is the key (no pun intended):
* Because postgres can't enforce uniqueness for an entire partitioned table
* .. but instead can only enforce this inside of each partition
* .. any existing unique constraints that we had (which would include `primary key`, since [`primary key => unique not rull`](https://www.postgresql.org/docs/12/ddl-constraints.html#DDL-CONSTRAINTS-PRIMARY-KEYS)) _have to be converted to [composite primary keys](https://www.postgresql.org/docs/12/ddl-constraints.html#DDL-CONSTRAINTS-PRIMARY-KEYS)_ _that include the partition key_

okay, that is starting to make sense. so how do we implement this in our migration?

[SO suggests](https://stackoverflow.com/questions/8761570/how-can-i-alter-a-primary-key-constraint-using-sql-syntax) that you can't just alter existing constraints, they must be dropped and recreated.

so can we:
* do this programatically?
* or do we just spell out what each constraint should be?

will see how hard it is to do the first option

**Comment by jladdjr** [comment]
Seems like maybe I only need to worry about the PRIMARY KEY constraint for `id`. Giving this a shot:

* copy over primary key constraint (don't want to have to drop a whole bunch of things with `EXCLUDE INDEXS`)
* then drop / recreate primary key constraint specifically

![image](https://user-images.githubusercontent.com/4440360/107448504-a3f25980-6af6-11eb-9d12-29374fed57ff.png)

restoring db and attempting migration again..

**Comment by jladdjr** [comment]
`DETAIL:  PRIMARY KEY constraint on table "main_jobevent" lacks column "job_created" which is part of the partition key.`

nope, really just can't create the old primary key constraint on the new parent partition at all

**Comment by jladdjr** [comment]
Trying this instead:

![image](https://user-images.githubusercontent.com/4440360/107448843-4f031300-6af7-11eb-8d6e-fc0510470f4f.png)

Migration went through - can see the new primary key!

![image](https://user-images.githubusercontent.com/4440360/107449042-b4ef9a80-6af7-11eb-8d28-15cf30589fed.png)

...

and here are the indexes:
![image](https://user-images.githubusercontent.com/4440360/107449148-e9fbed00-6af7-11eb-838a-3b4846cc4194.png)

**Comment by jladdjr** [comment]
on second thought, I should be able to drop the primary key constraint on the old table - I think that's what I was intending to do, just got the order of statements mixed up:

![image](https://user-images.githubusercontent.com/4440360/107449324-38a98700-6af8-11eb-9ee2-61f0974c8b48.png)

result:
`psycopg2.errors.DependentObjectsStillExist: cannot drop index main_jobevent_pkey1 because constraint main_jobevent_pkey1 on table main_jobevent_old requires it`

**Comment by jladdjr** [comment]
will need to put a bookmark in things here - up next: figure out how to drop not just the pkey index, but the constraint itself - maybe all I need to do is drop the constraint

**Comment by ryanpetrello** [comment]
@jladdjr

I perused over your comment history, and it's looking like you're making some good progress on the schema changes.

Regarding:

https://github.com/ansible/awx/issues/9259#issuecomment-775577491

In terms of "how do I actually set `job_created` on the event, I'd suggest putting this data into the event dict **before** it actually goes into redis (and then on to the callback receiver to be converted to ORM objects and saved into the database).

Check out this code:

https://github.com/jladdjr/awx/blob/db_partition/awx/main/tasks.py#L1213

This `event_handler` function is where events come back from *runner's interface*, and where we stick them into redis.  You'll notice in this function that we've got placed where we add/modify things in the event dict *before* it goes to redis.  This area of code is sensitive, so you have to think hard about any potential join operations or queries you add per-event.  At this point in time in the code, though, we have a loaded reference to `self.instance`, which we could use, e.g.,

```python
event_data['job_created'] = self.instance.created
```

Now.  I would encourage you to read these links below about how the callback receiver translates this event `dict` into event ORM objects *but* I want to point out some loaded guns I'm aware of from the last time I worked on something like this.  In fact, here's a commit where you can see things I touched the last time I added a new field to the event payload:

https://github.com/ansible/awx/commit/b5225bd80db71fe06d47a5e3febb0c854e7d8974

You'll notice in the above commit that there's some code _run by the callback receiver_ which determines *which fields* in this event struct should get translated into the actual composed `XXXEvent` columns/attributes later, so you'll want to add this new key (`job_created`) there.

https://github.com/ansible/awx/blob/devel/awx/main/models/events.py#L31-L32
https://github.com/ansible/awx/blob/devel/awx/main/models/events.py#L123
https://github.com/ansible/awx/blob/devel/awx/main/models/events.py#L600

**Comment by jladdjr** [comment]
@ryanpetrello this is all super-helpful. Thanks for reading through the state of things and weighing in 👍 

What you've pointed out has helped me realize a misconception that I think I had about `BaseTask.event_handler`. I had been thinking that this was a method that serviced any events that our callback receiver happened to receiver _throughout its lifetime_. But, after looking at how you've used `BaseTask.run`, it looks like BaseTask must get instantiated _for each job run_ (which it says right there in the comments).

So, instead of needing to come up with some kind of cache in _event_handler_, we can just note some of the job info there and the _event_handler_ method will have the context that it needs, just like you've done.

I'm being a little loose with my wording here about "noting job info", "getting job context". Per "you have to think hard about any potential join operations or queries you add per-event", will need to be careful about how things are accessed.

**Comment by ryanpetrello** [comment]
Yep, getting this right is all about how the data flows through the system and where it makes sense to inject new metadata into the event payload.  The answer to that is generally "inject it at the moment in time where you've already got what you need in-memory; don't look it up later, because every additional bit of latency per-event adds up to lot of extra time".  So:

1.  `ansible-playbook` runs, and emits data that represents events `runner_on_ok`, etc...  This is the first opportunity we have to introduce metadata beyond what Ansible itself includes in the payload.  Here's an example: https://github.com/ansible/ansible-runner/blob/devel/ansible_runner/display_callback/events.py#L150-L158

2. This event data makes its way through ansible runner and back to the event callback we've defined in `awx.main.tasks.BaseTask:event_handler`.  Every time *every* job runs, some `BaseTask` object (or subclass) is created (this code all runs in a task in an `awx-manage run_dispatcher` process), and the event callback is invoked once per event (you can test this by sticking an `sdb.set_trace()` inside that function and running a small playbook and looking at the events one by one as they come in over this interface).

3. In that callback function, we have a _second_ opportunity to modify or inject some additional context (like info about a related _parent_ workflow (for example: https://github.com/ansible/awx/blob/devel/awx/main/tasks.py#L1247-L1252) - or in the case of this issue, the creation time of the associated `UnifiedJob`).  The big flashing DANGER warning exists there to point out to people that they should be sure that any extra context they add isn't expensive to produce (i.e., more database queries).

4. The event data is stuffed into a queue in redis so we can parallelize the database saves later (which is the _most_ expensive/time consuming part of the whole process).

5. Some callback receiver process on the other end takes it out of redis, transforms the event data into a `JobEvent` (or similar) object, maybe does some _more_ processing of it in `awx.main.models.events` code (for doing things like generating the `.failed` and `.changed` attributes e.g., https://github.com/ansible/awx/blob/devel/awx/main/models/events.py#L772-L776) and saves it into the database.

In your example here, you can either add the extra context about the job's creation time at step 5 (expensive, because it requires us to do a `UnifiedJob.objects.get(id=event.job_id)` as the callback receiver code only has the JSON event data to reference).

**OR** you can do it at step 3, when we already have the related `UnifiedJob` available to reference (because at this moment in time, `self.instance` is a reference to the `UnifiedJob` that's being run).

**Comment by jladdjr** [comment]
Just pushed https://github.com/jladdjr/awx/commit/7838ee6153a901f6cf459e805d4aa82218bdb153

Migration went through! And I can see the new pkey constraint:
![image](https://user-images.githubusercontent.com/4440360/107572603-57178d00-6ba1-11eb-8493-90edeaa9d78b.png)

**Comment by jladdjr** [comment]
Verified that job detail pages for existing jobs are still working.

So. Now I can get back to updating job event processing to handle the partition key. To do this, I'll be "keying off of" https://github.com/ansible/awx/issues/9259#issuecomment-776755537 🥁

**Comment by jladdjr** [comment]
Okay, let's break down what needs to happen here:

Step 1: Update our callback receiver so that we append events with job creation data
* BaseTask.__init__ needs to support a new attribute, `job_created`, because as @ryanpetrello points out this is when we have the data and can record it with minimal cost
* BaseTask.event_handler needs to set event_data['job_created']

Steph 2: Update our Event models so that they include the `job_created` field when they get saved
* BasePlaybookEvent.create_from_data needs to apply new job_created field to events
* Need to add job_id to the list of VALID_KEYS for each event class

**Comment by jladdjr** [comment]
Took a stab at ^, running into:

![image](https://user-images.githubusercontent.com/4440360/107590605-5db3fd80-6bbd-11eb-8de9-c3c552ca744b.png)

we're in the event handler..
```
awx_1       |     super(RunProjectUpdate, self).event_handler(event_data)
```

.. which, at this point, is calling the dispatcher..
```
awx_1       |   File "/awx_devel/awx/main/tasks.py", line 1278, in event_handler
awx_1       |     self.dispatcher.dispatch(event_data)
```

.. which looks like it is wanting to send / serialize it..
```
awx_1       |   File "/awx_devel/awx/main/queue.py", line 35, in dispatch
awx_1       |     self.connection.rpush(self.queue, json.dumps(obj, cls=AnsibleJSONEncoder))
```

.. but:
`awx_1       | TypeError: Object of type 'datetime' is not JSON serializable`

**Comment by jladdjr** [comment]
~redis~ json is not very excited about serializing datetime objects before we hand them over to redis. `self.connection` here is a redis connection object.

![image](https://user-images.githubusercontent.com/4440360/107590930-52150680-6bbe-11eb-809a-a995a93d0663.png)

**Comment by jladdjr** [comment]
what about using https://docs.python.org/3/library/datetime.html#datetime.datetime.timestamp to serialize?

.. that would convert the datetime to (number of seconds since unix epoch in UTC)
.. we could then convert that back to a datetime using `datetime.fromtimestamp(timestamp, tz)`

bookmarking things here for now

**Comment by jladdjr** [comment]
back at it - looking into ^

**Comment by jladdjr** [comment]
looks like we're already in the business of handling special cases when it comes to serialization:
![image](https://user-images.githubusercontent.com/4440360/107597750-682bc280-6bd0-11eb-99dd-454dab6f77c9.png)

https://docs.python.org/3.6/library/json.html#json.dump basically says to do what we're already doing. `default` refers to the default serialization method (not to be confused with the _default_ arg that dump takes, which is a function that provides a default for anything that can't be deserialized. We don't want something _that_ general here, we know what case we're trying to handle).

![image](https://user-images.githubusercontent.com/4440360/107598119-b8efeb00-6bd1-11eb-8fea-2423b41c630b.png)

now the question is, how do we handle this on the other end, and _where is_ "the other end"?

The other end corresponds to step 5 of [the event pipeline](https://github.com/ansible/awx/issues/9259#issuecomment-776921989) - the callback receiver.

**Comment by jladdjr** [comment]
If we convert the datetime to a unix epoch timestamp (that will be relative to UTC), it looks like it will then get received at:

`awx/main/dispatch/worker/callback.py::read()`

![image](https://user-images.githubusercontent.com/4440360/107598495-cce81c80-6bd2-11eb-8936-150939f90bbc.png)

**Comment by jladdjr** [comment]
I was going to take things a step further and say that we should create a json deserializer to convert the serialized time back into a datetime, when I saw this:

https://github.com/ansible/awx/blob/devel/awx/main/models/events.py#L416

There's already a pattern here for handling datetime objects. This handles datetime at the point where the event objects are being created / persisted. How are those fields not throwing deserialization errors when the event handler first sends the event info over to redis?

**Comment by jladdjr** [comment]
Look at that - the display callback for AnsibleRunner converts the datetime:
https://github.com/ansible/ansible-runner/blob/devel/ansible_runner/display_callback/events.py#L158

![image](https://user-images.githubusercontent.com/4440360/107599413-43861980-6bd5-11eb-9256-79e821089420.png)

I'm not sure that we want to take that approach, though. So, maybe we go back to the earlier thought with creating a special json deserializer.

**Comment by jladdjr** [comment]
Wait, nope, we don't want the special json deserializer, that doesn't follow the pattern I spotted. Instead of using `timestamp`, I'll follow the existing pattern and:
* use str(<datetime>) to serialize `job_created`
* .. and [django's parse_datetime](https://docs.djangoproject.com/en/2.2/ref/utils/#django.utils.dateparse.parse_datetime) to deserialize, like we're doing [here](https://github.com/ansible/awx/blob/909c2513ac6a51934cb1ad130c50dd52c4c36113/awx/main/models/events.py#L423)

**Comment by jladdjr** [comment]
hopefully this wraps up the job_created serialization issue:
https://github.com/jladdjr/awx/commit/07fe0c4f266b16904d13af87775077bc0cea3cc5

**Comment by jladdjr** [comment]
![image](https://user-images.githubusercontent.com/4440360/107603322-29eacf00-6be1-11eb-955e-38ef8442a874.png)

posted a tweak so that we're just posted `job_created` for regular JobEvent models at this point (since the migration we have in place is only migrating main_jobevent and not the other job event tables). That seems to fix this issue afaict.

**Comment by jladdjr** [comment]
Ran a job.. it passed! 

`select id, created, modified, event, play, task, job_created from main_jobevent_part1;`

![image](https://user-images.githubusercontent.com/4440360/107604192-1e4cd780-6be4-11eb-85f1-1f7c6b54141b.png)

![image](https://user-images.githubusercontent.com/4440360/107604239-5b18ce80-6be4-11eb-959a-19221178fe46.png)


The events have the `job_created` field populated
.. they all have the same value
.. the value matches the unified job's created time
.. and everything got put in the right partition.

\o/

**Comment by jladdjr** [comment]
Will close this for now. Will need to revisit parts of this when we flip on migrations for other job event tables, but for now think I can dig into other things.
