### ISSUE TITLE
Inventory source "Custom Script" has no source detail fields

### ISSUE THREAD

**Issue by mattthehearn** [ansible/awx#9267]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

When I try to add a source to an inventory, I want to try and create a custom script to replace the Dynamic Inventory Scripts that seem to no longer be supported.  However, when I select "Custom Script" in the dropdown, it offers no fields under "Source Detail", and can't be saved.

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.17
* Operating System: Ubuntu 18
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create a new inventory:
- Click "Inventories"
- Click "Add" and select "Add inventory" (not a smart inventory)
- Give it a name and save it.

Attempt to create and add a source:
- Select the new inventory
- Click Sources
- Click "Add"
- Give the new source a name
- Click the Source dropdown and select "Custom Script"

##### EXPECTED RESULTS

I would expect to see some fields that I could use to either put script code in a text box, or better yet, point the source to a Git repository containing my dynamic inventory script.

##### ACTUAL RESULTS

No fields appear under "Source details", so I can't give AWX any information about my inventory script.

##### ADDITIONAL INFORMATION

![New Source](https://user-images.githubusercontent.com/14980647/107308021-d8620900-6a55-11eb-82ee-e59e73605526.png)

**Comment by tonyhogsten** [comment]
Have the same issue. We have installed AWX the same way as described above.

**Comment by unlikelyzero** [comment]
@AlexSCorey as a part of this, I think we might want to add a note in the tooltip users for folks who are learning that this is being removed

**Comment by mattthehearn** [comment]
Out of curiosity, what's being removed?  All means of using inventory scripts?  Will there be no way to have dynamic inventories going forward other than the ones built-in that connect to various cloud providers?

**Comment by wenottingham** [comment]
The ability to store scripts in the database for use... you can still use any inventory source from a custom collection or a script that is in a SCM repo.

**Comment by mattthehearn** [comment]
Interesting.  The python script that I was using as an inventory source with AWX 1.0.6 isn't working with any AWX version I've tested after 15, even after updating it for python3, and the Tower documentation seemed to imply that inventory scripts were removed as of 3.8.1.  I'll keep playing with that and open a separate issue if I can't get it working.

**Comment by seaman25** [comment]
Hi folks, I'm facing the same issue. Could anyone please help double confirm if this is actually considered a bug? Does the comment from @unlikelyzero mean that the `Custom Script` option will be removed from the source list soon?

Btw, I tried to select `Sourced from a Project` as the type of my source, but from the drop-down list of `Inventory file` I didn't see my python scripts (the shell scripts in my repository were listed though). Is there any way to get the python scripts work as the inventory source? To be more specific, we are trying to use that python script to select some pods from an OpenShift cluster as the target hosts.

Any ideas or suggestions will be appreciated, thanks! 😄

**Comment by wenottingham** [comment]
The custom inventory script *is* going away - it's not in the new UI in general, and it only shows up as an option as it's not removed from the API yet.

What you want to do is what you suggest - run it from a project. As to what you can select, I think you're running into https://github.com/ansible/awx/issues/9043

**Comment by mattthehearn** [comment]
@seaman25 For some reason, I couldn't get python scripts to work as inventory sources; the inventory parser never was able to run it.  It was able to run a simple bash script, however.  I'm not sure if that's a bug or something broken with my code (the python scripts I have work fine outside of AWX, and worked with a much older version of AWX).  You might try testing to see if a bash script will do what you need for now.

**Comment by yangzhang-ibm-au** [comment]
> The custom inventory script _is_ going away - it's not in the new UI in general, and it only shows up as an option as it's not removed from the API yet.
> 
> What you want to do is what you suggest - run it from a project. As to what you can select, I think you're running into #9043

@wenottingham Thanks for your confirmation! Yes, I will use a script in my project instead.

**Comment by yangzhang-ibm-au** [comment]
> @seaman25 For some reason, I couldn't get python scripts to work as inventory sources; the inventory parser never was able to run it. It was able to run a simple bash script, however. I'm not sure if that's a bug or something broken with my code (the python scripts I have work fine outside of AWX, and worked with a much older version of AWX). You might try testing to see if a bash script will do what you need for now.

Yeah, my python script worked with AWX 15.0.1. I will check if a bash script can do the job anyway. Thanks for your suggestion!

**Comment by seaman25** [comment]
> The custom inventory script _is_ going away - it's not in the new UI in general, and it only shows up as an option as it's not removed from the API yet.
> 
> What you want to do is what you suggest - run it from a project. As to what you can select, I think you're running into #9043

@wenottingham Thanks for your confirmation! Yes, I will use a script in my project instead.

**Comment by seaman25** [comment]
> @seaman25 For some reason, I couldn't get python scripts to work as inventory sources; the inventory parser never was able to run it. It was able to run a simple bash script, however. I'm not sure if that's a bug or something broken with my code (the python scripts I have work fine outside of AWX, and worked with a much older version of AWX). You might try testing to see if a bash script will do what you need for now.

Yeah, my python script worked with AWX 15.0.1. I will check if a bash script can do the job anyway. Thanks for your suggestion!

**Comment by yangzhang-ibm-au** [comment]
Btw, I got from a colleague that the issue will be fixed in a future version which contains this https://github.com/ansible/awx/pull/9120.

**Comment by seaman25** [comment]
Btw, I got from a colleague that the issue will be fixed in a future version which contains this #9120.

**Comment by jonathan2324** [comment]
@mattthehearn @wenottingham Did yall ever get your dynamic python inventory files working? I am currently on 16.0.0 release and my python script shows up from sourced from project but when I try to sync I get errors. Did you have any success with 15.0.1 version?

**Comment by brskq** [comment]
@seaman25 @mattthehearn @jonathan2324 I had initially created an inventory plugin which worked well with Ansible, but was incompatible with AWX. I digged quite a lot and then came across the following guide which works well:
[Jeff Geerling - Creating custom dynamic inventories for Ansible](https://www.jeffgeerling.com/blog/creating-custom-dynamic-inventories-ansible)

I'm using the _Sourced from a Project_ source. I've specified my Python file as the Inventory file and I've set **Source variables** to the following as I need different sources for my dynamic inventory:

```yaml
---
NON_ANSIBLE_INVENTORY: https://...
```

I'm able to access `NON_ANSIBLE_INVENTORY` from Python `os.environ`.

About:
```txt
 ______________ 
<  AWX 17.0.1  >
 -------------- 
          \
          \   ^__^
              (oo)\_______
              (__)      A )\
                  ||----w |
                  ||     ||
                    

Ansible Version
    2.9.17
```

**Comment by AlexSCorey** [comment]
There may be a few lists in the new UI that have Inventory Scripts or Custom Scripts in the list.  Those list items are generated from the API. Once the API removes what they have for Inventory Scripts, those list should render the correct options.  As such I am moving this from a UI bug to an API bug

**Comment by smithlabs** [comment]
> @seaman25 @mattthehearn @jonathan2324 I had initially created an inventory plugin which worked well with Ansible, but was incompatible with AWX. I digged quite a lot and then came across the following guide which works well:
> [Jeff Geerling - Creating custom dynamic inventories for Ansible](https://www.jeffgeerling.com/blog/creating-custom-dynamic-inventories-ansible)
> 
> I'm using the _Sourced from a Project_ source. I've specified my Python file as the Inventory file and I've set **Source variables** to the following as I need different sources for my dynamic inventory:
> 
> ```yaml
> ---
> NON_ANSIBLE_INVENTORY: https://...
> ```
> 
> I'm able to access `NON_ANSIBLE_INVENTORY` from Python `os.environ`.
> 
> About:
> 
> ```
>  ______________ 
> <  AWX 17.0.1  >
>  -------------- 
>           \
>           \   ^__^
>               (oo)\_______
>               (__)      A )\
>                   ||----w |
>                   ||     ||
>                     
> 
> Ansible Version
>     2.9.17
> ```

Did this work for you in AWX or just Ansible? I'm running into issues where it is saying not a valid inventory source. Would love to ask you more about it on a private Slack/Discord.

**Comment by brskq** [comment]
@smithlabs It works in both AWX and Ansible. I'm only reachable through https://element.io/. Send me your username and I'll message you.

![ansible_awx-15](https://user-images.githubusercontent.com/64258427/113105425-16c3ab00-91f1-11eb-98aa-bd5f207cdedb.png)

**Comment by smithlabs** [comment]
> @smithlabs It works in both AWX and Ansible. I'm only reachable through https://element.io/. Send me your username and I'll message you.
> 
> ![ansible_awx-15](https://user-images.githubusercontent.com/64258427/113105425-16c3ab00-91f1-11eb-98aa-bd5f207cdedb.png)

@brskq
Awesome. smithlabs on Element.

**Comment by smithlabs** [comment]
> @smithlabs It works in both AWX and Ansible. I'm only reachable through https://element.io/. Send me your username and I'll message you.
> 
> ![ansible_awx-15](https://user-images.githubusercontent.com/64258427/113105425-16c3ab00-91f1-11eb-98aa-bd5f207cdedb.png)

@brskq
Hi, not sure if you got the previous reply. I'd still like to connect with you on Element. My username on there is smithlabs.

Thanks

**Comment by shanemcd** [comment]
@AlanCoding @wenottingham Should we close this given the removal of inventory scripts?

**Comment by unlikelyzero** [comment]
@shanemcd i think we should add a tooltip to help users adjust to the missing field/functionality with an explanation/link to our docsite.

**Comment by brskq** [comment]
@smithlabs I messaged you. I was not in the office last week hence the late reply.

**Comment by AlanCoding** [comment]
@shanemcd Yes, https://github.com/ansible/awx/issues/7775 is very near-term, and that way we migrate these will not leave any room for a broken UI state. People trying to use their old scripts are just going to have to follow our custom migration instructions. If you need to fix it before that lands, you just have to navigate to the `/api/v2/inventory_scripts/` endpoint in the browser and recover your content from there.

**Comment by pxsc437** [comment]
Hi,
I read this issue and I didn't understand how it was resolved?
I have AWX version 17.1.0 and this bug is still present.

ENVIRONMENT

    AWX version: 17.1.0
    AWX install method: docker on linux
    Ansible version: 2.9.17
    Operating System: RHEL 7.9 / CentOS Linux 7.9.2009
    Web Browser: Firefox

**Comment by azbuka827** [comment]
> @smithlabs It works in both AWX and Ansible. I'm only reachable through https://element.io/. Send me your username and I'll message you.
> 
> ![ansible_awx-15](https://user-images.githubusercontent.com/64258427/113105425-16c3ab00-91f1-11eb-98aa-bd5f207cdedb.png)

Hi, need your help dear community, suddenly  i dont understand how to fix it(
