### ISSUE TITLE
What happened to the forks/cpu slider tool in Instance Group->Tower->Instances ?

### ISSUE THREAD

**Issue by ntlartey** [ansible/awx#9269]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

The forks/cpu slider seems to be missing in the 17.0.x UI as compared to 15.x or earlier.
Is this intentional or a job still to be done?

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: openshift OCP3.x
* Ansible version:  2.9.17
* Operating System: centos 8
* Web Browser: chrome 

##### STEPS TO REPRODUCE

Basic installation on openshift using gitea helm chart

##### EXPECTED RESULTS

Expected to see the same slider as in the 15.x UI

##### ACTUAL RESULTS

No slider for forks/cpu is visible in
Instance Group->Tower->Instances

**Comment by ntlartey** [comment]
![forkcpuslider](https://user-images.githubusercontent.com/6302910/107348348-2ebb6000-6ac7-11eb-8bda-b7fb58d12c23.png)
![missing slider](https://user-images.githubusercontent.com/6302910/107348385-3844c800-6ac7-11eb-8cf8-47c489825a52.png)

**Comment by AlexSCorey** [comment]
@ntlartey thanks for reach out to use. The good news is that the slider is coming but we were trying to wait for patternfly to release a stable version (https://www.patternfly.org/v4/components/slider).  Follow #7777  for this work.
