### ISSUE TITLE
Multi select in credential form not showing all credential types

### ISSUE THREAD

**Issue by ghost** [ansible/awx#9270]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When having 5 or more custom credential types there is a second credential type page that doesn't get called when calling the api. The current credential form only seems to work correctly when there is one page. When trying to edit a credential with a credential type on the second page this creates a exception and the webpage goes blank.

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.15
* Operating System: RHEL 8.3
* Web Browser: Mozilla, Chrome

##### STEPS TO REPRODUCE

Create more than 5 custom credential types.

##### EXPECTED RESULTS

Create new credential with credential type or edit existing credentials.

##### ACTUAL RESULTS

Can't add new credential with type on the second api page and also can't edit existing.

##### ADDITIONAL INFORMATION

API call to credential type:
![afbeelding](https://user-images.githubusercontent.com/75235183/107359056-7eecef00-6ad4-11eb-932c-5792dbfc624a.png)

Error when trying to edit existing credential:
![afbeelding](https://user-images.githubusercontent.com/75235183/107359138-9d52ea80-6ad4-11eb-9f58-f9d921392744.png)

**Comment by AlexSCorey** [comment]
@arnecovensarx check out this PR to solve the issue https://github.com/ansible/awx/pull/9116
