### ISSUE TITLE
AWX 17.0.1 Create new schedule missing promt button for surveys

### ISSUE THREAD

**Issue by USUTL** [ansible/awx#9272]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The "promt"-button is missing in "Create New Schedule" window, so it's not possible to answer survey questions.

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.17
* Operating System: CentOS 7
* Web Browser: Firefox, Chrome

##### STEPS TO REPRODUCE

1. Add a survey to a job template with at least one required question (without a default answer)
2. Create a schedule for this template

##### EXPECTED RESULTS

Popup with survey questions should appear, when clicking the "save"-button respectively the "promt"-button

##### ACTUAL RESULTS

When trying to save the new schedule, an error message appears that a value is missing (the value which was specified in the survey)

##### ADDITIONAL INFORMATION

In older versions there was a promt-button to answer the survey questions:

AWX 17.0.1:
![grafik](https://user-images.githubusercontent.com/78800625/107369066-97173b00-6ae1-11eb-8f3f-4e9aba72ce83.png)

AWX 6.1.0.0:
![grafik](https://user-images.githubusercontent.com/78800625/107370780-b747f980-6ae3-11eb-8755-7e633b3fc8c7.png)

**Comment by mabashian** [comment]
This is being implemented now.  See #7692 and #9210
