### ISSUE TITLE
Missing symlinks to /usr/bin for awx-manage

### ISSUE THREAD

**Issue by ghost** [ansible/awx#9273]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: devel
* AWX install method: docker on linux
* Ansible version:  2.10
* Operating System: Linux
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Running migrations in task container fails citing awx-manage not found

##### EXPECTED RESULTS

Migrations to complete successfully

##### ACTUAL RESULTS

`fatal: [localhost]: FAILED! => {"changed": true, "cmd": "docker-compose run --rm --service-ports task awx-manage migrate --no-input", "delta": "0:00:04.612415", "end": "2021-02-09 15:00:33.874184", "msg": "non-zero return code", "rc": 127, "start": "2021-02-09 15:00:29.261769", "stderr": "Creating network \"awxcompose_default\" with the default driver\nCreating awx_redis ... \r\nCreating awx_postgres ... \r\nCreating awx_redis    ... done\r\nCreating awx_postgres ... done\r\nCreating awx_web      ... \r\nCreating awx_web      ... done\r\nCreating awxcompose_task_run ... \r\nCreating awxcompose_task_run ... done\r\n[FATAL tini (8)] exec awx-manage failed: No such file or directory\n127", "stderr_lines": ["Creating network \"awxcompose_default\" with the default driver", "Creating awx_redis ... ", "Creating awx_postgres ... ", "Creating awx_redis    ... done", "Creating awx_postgres ... done", "Creating awx_web      ... ", "Creating awx_web      ... done", "Creating awxcompose_task_run ... ", "Creating awxcompose_task_run ... done", "[FATAL tini (8)] exec awx-manage failed: No such file or directory", "127"], "stdout": "", "stdout_lines": []}`

**Comment by ghost** [comment]
CC @shanemcd, I have a PR for the same, could you review it please, https://github.com/ansible/awx/pull/9274

**Comment by ryanpetrello** [comment]
Thanks for the PR @constreference!
