### ISSUE TITLE
Add free strategy support to the builtin add_host module

### ISSUE THREAD

**Issue by mrmibrown** [ansible/awx#9280]
This is a request to add free strategy support to the builtin add_host module

##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
When the add_host module is used in free mode the following error is received:
"ERROR! The 'add_host' module bypasses the host loop, which is currently not supported in the free strategy and would instead execute for every host in the inventory list."

##### Playbook used:
---
- hosts: localhost
  gather_facts: no
  strategy: free
  tasks:
    - add_host:
         name: test-host
         ansible_connection: local

**Comment by wenottingham** [comment]
This needs to go in https://github.com/ansible/ansible - this isn't done in AWX.
