### ISSUE TITLE
Postgres upgrade failed, upgrading awx 16.0.0 > 17.0.1

### ISSUE THREAD

**Issue by Thomastouma** [ansible/awx#9282]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Problem: The Local Docker installer fails to upgrade the postgres data in a temporary spun up container based on image tianon/postgres-upgrade:10-to-12.  I've made sure that the postgres data dir has the correct permissions corresponding to the user running the playbook.

Result:  Rendered our awx-environment in a bricked state as playbook failed mid upgrade

Playbook step:
`TASK [local_docker : Upgrade Postgres] *****************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "docker run --rm  -v /data/awx/pg/10/data:/var/lib/postgresql/10/data  -v /data/awx/pg/12/data:/var/lib/postgresql/12/data  -e PGUSER=awx -e POSTGRES_INITDB_ARGS=\"-U awx\"  tianon/postgres-upgrade:10-to-12 --username=awx\n"`

Task stdout:
`Checking cluster versions ok
connection to database failed: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Failure, exiting`

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Operating System: Centos 8

##### ADDITIONAL INFORMATION

Im also seeing  the same problem in an open issue opened  Sep 9, 2020 on the docker images author's repository [#31](https://github.com/tianon/docker-postgres-upgrade/issues/31)

**Comment by lgrullon-gilead** [comment]
I performed an upgrade from 16 to 17.1 and my entire DB got wipe out. 

Can someone shine some light as to why this is happening, perhaps a bug that needs to be review, I had to roll it back to 16 against until issue is fix.

**Comment by ryanpetrello** [comment]
Hey @lgrullon-gilead,

I'm unaware of any endemic issues related to database loss on 16 -> 17 upgrades.  It's possible that it's a bug related to the link you posted, though (https://github.com/tianon/docker-postgres-upgrade/issues/31)?

That said, this issue tracker is for tracking feature enhancements and bugs to AWX itself - you might have luck troubleshooting this on the mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by Thomastouma** [comment]
@ryanpetrello 

The link I posted is a link to an issue on the main repository for the Docker image that is being used in the current AWX installer playbook since AWX version 17.0 , used to perform  an in place upgrade on the Postgres data to conform with Postgres version 12.
I understand that my troubles are not a bug in AWX as an automation plattform itself, though i do belive that this is something that has to be dealt with as it's causing troubles for AWX users upgrading their plattform.

**Comment by Thomastouma** [comment]
### Problem resolved
The problem on our behalf was that the LV on our host machine representing the postgresql data dir path became 100% full when trying to upgrade the DB, so the solution for us was to increase the disk space.

### Feedback
I think it would be worth mentioning in upcoming Changelog that the postgresql upgrade requires a temporary 100% increase on the space available in the postgresql data dir path

**Comment by lgrullon-gilead** [comment]
Hi Thomastouma,
Thank you for providing those details, very helpful for those of us that got impacted.
