### ISSUE TITLE
Add ability to import Azure hosts by private IP address

### ISSUE THREAD

**Issue by ghost** [ansible/awx#929]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Add functionality to Azure inventory import similar to the AWS `vpc_destination_variable: private_ip_address' source variable setting, that would allow the importing of Azure hosts by private IP address.

##### ENVIRONMENT
* AWX version: 1.0.1

##### STEPS TO REPRODUCE

Currently, if a default public IP address is not available, the hosts are imported by hostname in that circumstance, and the hostname is often not resolvable, so playbooks fail.

**Comment by matburt** [comment]
This is the kind of thing that you should raise on the ansible core inventory script as we source our own azure script from there: https://github.com/ansible/ansible/blob/devel/contrib/inventory/azure_rm.py
