### ISSUE TITLE
Failed to update job template - Error: "Failed to update job template. PATCH returned status: 503"

### ISSUE THREAD

**Issue by Gopinath-G** [ansible/awx#9293]
##### ISSUE TYPE
 - Bug Report
 
##### Component
- UI

##### SUMMARY
- Unable to update exiting template in UI, getting below error while I hit Save button
- Error: "Failed to update job template. PATCH returned status: 503"

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method:  docker on linux
* Ansible version:  2.9.14
* Operating System: RHEL 7
* Web Browser: Google Chrome Version 88.0.4324.150

##### STEPS TO REPRODUCE

Create a new job template and save
Edit the template to change any parameter and hit save
This will report the given error

##### EXPECTED RESULTS

Template get updated with changes

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/65112067/107658303-017bd700-6cac-11eb-80b8-8218f8bdc612.png)

##### Additional information

Noticed below logs in awx_web container

awx_web     | 2021-02-11 16:15:00,018 WARNING  django.request Not Found: /websocket/
awx_web     | 2021-02-11 16:15:00,018 WARNING  django.request Not Found: /websocket/
awx_web     | 2021-02-11 16:15:00,018 WARNING  Not Found: /websocket/
awx_web     | 10.14.51.12 - - [11/Feb/2021:16:15:00 +0000] "GET /websocket/ HTTP/1.1" 404 3880 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36" "10.246.3.249"

**Comment by blomquisg** [comment]
Can you try to reproduce in AWX 17?

Also check if supervisord is running.

**Comment by Gopinath-G** [comment]
I faced the same issue after upgrading to AWX17..

Yes, supervisord is running.

bash-4.4# ps -ef | grep -i supervisord
root         69      6  0 Feb12 ?        00:01:32 /usr/bin/python3.6 /usr/local/bin/supervisord -c /etc/supervisord.conf

**Comment by Gopinath-G** [comment]
Seems issue with RHEL OS, Issue resolved after recent OS patching RHEL 7.9
