### ISSUE TITLE
What year is it ?!

### ISSUE THREAD

**Issue by hacko2** [ansible/awx#9296]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Update year version

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.17
* Operating System: Ubuntu 20.04
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Info --> About

##### EXPECTED RESULTS

Change from 2019 to 2021

##### ACTUAL RESULTS

2019

**Comment by ryanpetrello** [comment]
![image](https://user-images.githubusercontent.com/214912/107794700-bdc5b380-6d25-11eb-8997-f7a1af5dc61a.png)

@marshmalien @jakemcdermott @mabashian is this a simple thing to template out to `$currentYear` ?

**Comment by jakemcdermott** [comment]
Yep - using `new Date().getFullYear()` [here](https://github.com/ansible/awx/blob/devel/awx/ui_next/src/components/About/About.jsx#L40) should do it.

**Comment by ryanpetrello** [comment]
also:
![](http://gifrific.com/wp-content/uploads/2014/01/Robin-Williams-What-Year-Is-It-Jumanji.gif)

**Comment by ghost** [comment]
If you want `2019 - 2021`, might as well add this:
```js
`Copyright ${new Date(/* 2019 timestamp */).getFullYear()} - ${new Date().getFullYear()}
Red Hat, Inc.`
```

If you just want `2019`, this should do it:
```js
`Copyright ${new Date().getFullYear()} Red Hat, Inc.`
```

**Comment by balonik** [comment]
still not fixed. with AWX 19.0.0 on k8 I get `Copyright {0} Red Hat, Inc.`

**Comment by jakemcdermott** [comment]
Yep, you're right - there appears to be a translation issue with the production build. I will look into it.

**development environment**
![Screenshot from 2021-04-08 18-52-25](https://user-images.githubusercontent.com/9753817/114105864-97427580-989b-11eb-8ed8-1492fc157145.png)


**production build**
![Screenshot from 2021-04-08 18-46-13](https://user-images.githubusercontent.com/9753817/114105492-d91eec00-989a-11eb-9fc3-6faec2bcc415.png)

**Comment by jakemcdermott** [comment]
https://github.com/ansible/awx/pull/9861

**Comment by tiagodread** [comment]
![image](https://user-images.githubusercontent.com/12464858/114590608-5bbef700-9c5f-11eb-9598-67daee1599cb.png)

Done
