### ISSUE TITLE
custom_venvs fails in kubernetes due to cryptography dependency 

### ISSUE THREAD

**Issue by darrenjones24** [ansible/awx#9298]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When using custom_venvs in kubernetes, the initcontainer fails to install ansible. This is because pip cannot install the cryptography module which is due to a change in the cryptography module requiring rust. (see https://github.com/pyca/cryptography/issues/5771) 

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: Kubernetes
* Ansible version:  
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

    custom_venvs:
    - name: techops
      python: python3
      python_modules:
        - pyvmomi
        - mysql-connector
        - argparse
        - apypie
      python_ansible_version: 2.9.17

##### EXPECTED RESULTS

Build completes

##### ACTUAL RESULTS
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ud_ezxyu/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    
##### ADDITIONAL INFORMATION

This can be fixed by upgrading pip in the file awx-17.0.1/installer/roles/kubernetes/templates.deployment.yml.j2

--- deployment.yml.j2	2021-02-12 14:03:25.353805414 +0000
+++ deployment-new.yml.j2	2021-02-12 14:56:47.389720404 +0000
@@ -150,6 +150,7 @@
               virtualenv -p {{ custom_venv.python | default(custom_venvs_python) }} \
                 {{ custom_venvs_path }}/{{ custom_venv.name }} &&
               source {{ custom_venvs_path }}/{{ custom_venv.name }}/bin/activate &&
+              {{ custom_venvs_path }}/{{ custom_venv.name }}/bin/pip install {{ trusted_hosts }} -U psutil --upgrade pip  &&
               {{ custom_venvs_path }}/{{ custom_venv.name }}/bin/pip install {{ trusted_hosts }} -U psutil \
                 "ansible=={{ custom_venv.python_ansible_version }}" &&
 {% if custom_venv.python_modules is defined %}

**Comment by ryanpetrello** [comment]
Hey @darrenjones24,

Sounds like an opportunity for a pull request 😄

**Comment by ryanpetrello** [comment]
addressed via: https://github.com/ansible/awx/pull/9300
