### ISSUE TITLE
Ansible Environment no longer appears as an option in job templates

### ISSUE THREAD

**Issue by stefanjarina** [ansible/awx#9299]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Missing option to choose our custom virtual environment from Job Template screen.
It is visible for Organization and Project screens.

We are now planning to migrate from 15.x to 17.x and it was working in version 15, so this seems to be a bug, unless something changed.

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.17
* Web Browser: Microsoft's new Edge, Chrome

##### STEPS TO REPRODUCE

Fresh installation of AWX in docker on linux
Create custom venv on both awx_web, awx_task (bind mount in docker-compose)
add path to system settings
e.g. [ "/opt/custom-envs" ]
verify via /api/v2/config

##### EXPECTED RESULTS

Option to choose from list of venvs should appear not only on new Organization and Project, but also on Job Template screen

##### ACTUAL RESULTS

Option "Ansible Environemnt" is missing in Job Template

##### ADDITIONAL INFORMATION

I checked also /api/v2/config

```json
"custom_virtualenvs": [
    "/var/lib/awx/venv/ansible/",
    "/opt/custom-envs/sws-venv/"
]
```

**Comment by stefanjarina** [comment]
OK, after searching a bit more thoroughly, it looks like that field will be replaced by https://github.com/ansible/awx/issues/9189

So looks like we need to stay on version 15.x for now

**Comment by wenottingham** [comment]
Yes, this won't be back in the UI going forwards.
