### ISSUE TITLE
Translating the project

### ISSUE THREAD

**Issue by aoyawale** [ansible/awx#93]
### Summary

I noticed in the CONTRIBUTING.md mentioning translating. Is that something that is going to be done using PR's? or a external system?

**Comment by Zokormazo** [comment]
I'm interested on it too.

Are you going to use an external service to manage translations or we have to PR directly here?

**Comment by AlexGluck** [comment]
I'm interested on it too.

**Comment by wenottingham** [comment]
Yes, there will be something, it's just not set up yet. More soon.

**Comment by docschick** [comment]
We are setting up an external service to manage translations. Currently, we're running this idea by the IP lawyers to ensure we're okay to go before pushing it out for use.

**Comment by wenottingham** [comment]
As you can see, this external service did not materialize. We have reconsidered and for the forseeable future, please just send pull requests for new translations.
