### ISSUE TITLE
Place to control the user permission for job template?

### ISSUE THREAD

**Issue by emailvenkatm** [ansible/awx#930]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME

 - API
 

##### SUMMARY
Can anyone please tell me where is the place to control the user permissions to create a new job template. I was overwriting the authorization part integrating with our internal api.  I tried changing the few classes in api/permissions.py, main/access.py but none of them worked for creating a Job template. Not really sure where I am missing.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by matburt** [comment]
Currently organization admins are the only ones able to create job templates. Our plan is to extend that in the near future so that creation of job templates can be further delegated: https://github.com/ansible/awx/issues/166
