### ISSUE TITLE
[ui_next] Direct Links to awx do not reroute the user after authentication

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#9311]
##### ISSUE TYPE
 - Feature

##### SUMMARY
I might be wrong, but i _believe_ that _some point_ in the classic experience, if a user had a direct link to a resource, (like a from a slack notification) and they had not authenticated, we would reroute the user to the original requested page i.e. https://localhost:3001/#/credentials/1/details. 

Note: https://github.com/ansible/awx/issues/8155 is an example of expected behavior

##### STEPS TO REPRODUCE
1. Take a link
2. Rerouted to Login Page. Login
3. Taken to dashboard instead of original link

**Comment by mabashian** [comment]
I thought we had an issue tracking this but I can't find it.  Along the same lines, I _think_ we used to track the page that a user was viewing before their session timed out but this will need to be confirmed.

Steps: 

1) Navigate to a random page
2) Let the tab time out (kicked back to login)
3) Log back in

IIRC the expectation would be the user is taken back to the page they were last viewing (as long as they're logging in on the same browser).

If a different user were to log in, we would not want to redirect to the last viewed page.

**Comment by djj106** [comment]
@unlikelyzero - that is correct. In 15.0.1, the user would be routed to the page in the link after authentication rather than to the dashboard.

**Comment by unlikelyzero** [comment]
@marshmalien please pair with @tiagodread while developing this.

@tiagodread , i think we could automate one or two tests on this and do a complete audit by _manually_ modifying the BeforeEach and AfterEach in index.js such that we are logged out before starting the tests

**Comment by tiagodread** [comment]
This is being added by #9908, now working with SAML or username/password

https://user-images.githubusercontent.com/12464858/120550518-5bbfb580-c3cb-11eb-9788-2577125953f8.mp4
