### ISSUE TITLE
Can't find extra vars in schedule level

### ISSUE THREAD

**Issue by doryanmzr** [ansible/awx#9314]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

When I try to add extra vars in the schedule level, I can't see the extra vars field.
the "Prompt on launch" of the variables in the template level is checked.

##### ENVIRONMENT
* AWX version:16.0.0
* AWX install method: docker compose 
* Ansible version: 2.9.15
* Operating System: centos 7 
* Web Browser: chrome 

##### STEPS TO REPRODUCE

once the template is created and the "Prompt on launch" in variable is checked, try to add new schedule with extra vars,
but the extra vars field is missing.

##### EXPECTED RESULTS

add extra vars in schedule level.

##### ACTUAL RESULTS

it's missing

##### ADDITIONAL INFORMATION

16.0.0 version:

![image](https://user-images.githubusercontent.com/35372228/107931795-6faeeb00-6f85-11eb-8672-e126d8b77bf6.png)

 version 6.1.0.0

![image](https://user-images.githubusercontent.com/35372228/107932237-ffed3000-6f85-11eb-8c48-1c27fa17eef0.png)

**Comment by unlikelyzero** [comment]
@doryanmzr thanks for filing this issue, we're tracking this functionality in this issue here: https://github.com/ansible/awx/issues/7692

Please subscribe to the updates to see when it lands in the next available release!
