### ISSUE TITLE
StatusLabel displays empty tooltip

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#9323]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
StatusLabel displays empty tooltip.

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/9053044/108076698-b6f6b380-7039-11eb-90f7-1914ee1efaae.png">

**Comment by mabashian** [comment]
Yea I noticed this as well.  I don't think that all instances of StatusLabel need a tooltip so we may want to make this optional.

**Comment by nixocio** [comment]
This issue was already addressed.
