### ISSUE TITLE
improve CUSTOM_VENV_PATH documentation

### ISSUE THREAD

**Issue by azrdev** [ansible/awx#9330]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
There is support and documentation for configuring a path containing additional virtualenvs, which can be used to run Jobs with python dependencies differing from the default installation.
However, the documentation appears to me inconsistent and incomplete:

* https://github.com/ansible/awx/blob/9d53bab/INSTALL.md#inventory-variables  (at current HEAD) mentions an installer inventory variable `custom_venv_dir` *for docker-compose installs only* (which apparently is mounted from the awx host into the awx_task and awx_web containers -- seems like the cleanest solution for long-term modifications. why not configure it by default instead?)
* https://github.com/ansible/awx/blob/22aaf76/docs/custom_virtualenvs.md (at current HEAD) documents how to create a new venv and set CUSTOM_VENV_PATHS by issuing a HTTP PATCH against the API. It mentions (since recently) that the venv has to exist in awx_web and awx_task containers, but actually in awx_web it only has to exist, but is not used (i.e. it doesn't matter what's installed inside).
* Instead of HTTP PATCHing one can simply set CUSTOM_VENV_PATHS in the GUI at Settings>System (provided the path exists in awx_web container)

**Comment by wenottingham** [comment]
Hi -

I do understand what you're saying here, but that feature is going to be removed soon. See https://groups.google.com/g/awx-project/c/47MjWSUQaOc/m/1-Jh0fy3AgAJ for a description of where we're going, and https://github.com/ansible/awx/issues/5157 for more details..
