### ISSUE TITLE
Document Backup/Restore procedure

### ISSUE THREAD

**Issue by azrdev** [ansible/awx#9337]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
How to backup all data (assets?) created in AWX, like Projects, Users, Credentials, Job Templates, etc ?
There seems to be no documentation about it:

* It seems to be possible: #5109 #5469 #3062
* https://github.com/ansible/awx/blob/4cb0366/INSTALL.md (current HEAD) does not mention it. There is DATA_MIGRATION.md which [used to](https://github.com/ansible/awx/commit/829e9054d6a13adeea86fc80d1a33e41ace8c19e) refer to `tower-cli receive/send` (see below), but now only links the installer. I suppose the installer just creates a persistent volume (k8s) / volume mount (docker compose) for the database.

    Though related, keeping data across updates is not the scope here, but backing it up offsite
* for k8s installs (only), there are [backup](https://github.com/ansible/awx/blob/f1d2d79/installer/roles/kubernetes/tasks/backup.yml)/[restore](https://github.com/ansible/awx/blob/f1d2d79/installer/roles/kubernetes/tasks/restore.yml) task files, though I cannot see them called/included anywhere
* #1745 mentions that
  * ansible tower does not use containers and has a `setup.sh` install script, which also handles backups
  * there is `tower-cli receive` / `tower-cli send` to get data out of and into a running awx instance. All data?
* By now, `tower-cli receive|send` seems to have been replaced by **`awxkit` commands `awx export`/`awx import` ([doc](https://github.com/ansible/awx/blob/393369a/awxkit/awxkit/cli/docs/source/examples.rst), [tower doc](https://docs.ansible.com/ansible-tower/3.8.1/html/towercli/examples.html#import-export))-- These seem to be the way to go**, but again, do they cover all data?

**Comment by ckozler** [comment]
While we wait for documentation on this component, could you provide an unofficial method that would be the best way to do it when using AWX in a container? Would the backup/restore playbooks that are linked here probably the best?
  
I would have to imagine AWX developers have something on hand and can maybe provide some general direction, no?

**Comment by ckozler** [comment]
The best I can deduce is using this - https://github.com/ansible/awx/blob/devel/INSTALL.md#installing-the-awx-cli

**Comment by craph** [comment]
@azrdev , @ckozler , Hi,
I have just open this : https://github.com/ansible/awx/issues/10448

And I'm unable to have awx cli working correctly to export / import data from AWX 17.x (docker) to AWX 19.x (k8s)

**Comment by ghost** [comment]
So you still have NO backup/restore procedure or even a documentation on this?
Unbelievable.

**Comment by ernie18a** [comment]
You can use the backup and restore roles with doc. in the [awx-operator](https://github.com/ansible/awx-operator) to accomplish this.  
[backup](https://github.com/ansible/awx-operator/blob/devel/roles/backup/README.md)
[restore](https://github.com/ansible/awx-operator/blob/devel/roles/restore/README.md)
