### ISSUE TITLE
RFE: Add an activity stream button from the Schedules View

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#9339]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add a shortcut to the activity stream when at the Schedules view. A schedules filter exists in the drop down but in order to get to the stream from that view you need to navigate away from it first.

**Comment by wenottingham** [comment]
@mabashian is this in ui-next already?

**Comment by mabashian** [comment]
Yep

<img width="1680" alt="Screen Shot 2021-02-19 at 11 27 13 AM" src="https://user-images.githubusercontent.com/9889020/108532152-8c109780-72a5-11eb-9bab-7654901afcb1.png">

**Comment by tiagodread** [comment]
This already exists in the new UI:

![schedule](https://user-images.githubusercontent.com/12464858/109974996-e6175100-7cd8-11eb-8c11-cce2065cdafd.gif)
