### ISSUE TITLE
Running AWX as Hot-Hot in Primary and Secondary Site

### ISSUE THREAD

**Issue by anujbansal31** [ansible/awx#9353]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

We are using AWX application and setup in both Primary and Secondary Site. But at one time only one Site is active and AWX runs there. We are using external PostgreSQL database which has been setup on other host.  If there are any issue in our Primary site, we have to manually start the application in secondary site after data replication completed.

So how if we can run AWX in both site at same time. If there is any issue with Primary site then it automatically failed over to Secondary site and keep working without any outage?  This High Availability (HA) option is available in Ansible Tower which is paid version but how we can leverage this here?

**Comment by wenottingham** [comment]
This is not a feature we plan to add in AWX.

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
