### ISSUE TITLE
Problem when migrating from 15.0.1 to 17.01

### ISSUE THREAD

**Issue by tassin76** [ansible/awx#9354]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX 

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker on linux
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Migrate from 15.0.1 to 17.0.1 (without applying version 16.0.0)

##### EXPECTED RESULTS

Got AWX up and running and so got the login page

##### ACTUAL RESULTS

When migration is completed or seems to be, the login page stays on "AWX is installing ..."

##### ADDITIONAL INFORMATION

We solved the problem by reverting to version 15.0.1 then migrating to 16.0.0 and finally to 17.0.1.
It seems that the NGINX configuration file (nginx.conf) generated by the installer is modified by the installer of version 16.0.0 but not by the installer of version 17.0.1.

**Comment by mattschwen** [comment]
Looks like it might be because on version 16 you move from `Postgres 9.6` to `Postgres 10` and you cannot do a database migration between major versions.

**Comment by tassin76** [comment]
> Looks like it might be because on version 16 you move from `Postgres 9.6` to `Postgres 10` and you cannot do a database migration between major versions.

No ... my v15.0.1 instance already used a Postgres 10 container created by the AWX installer

**Comment by cinpol** [comment]
> Looks like it might be because on version 16 you move from `Postgres 9.6` to `Postgres 10` and you cannot do a database migration between major versions.

I upgraded from 6.1.0 to 9.3.0 (Postgres 9 to 10), so a major database upgrade does work. However, I was not able to upgrade from 9.3.0 to 15.0.1, while I was able to upgrade from 9.3.0 to 17.0.1 (Postgres 10 to 12).

Above is on docker-compose.
