### ISSUE TITLE
UI_NEXT - Cannot access Management Jobs or Cleanup jobs

### ISSUE THREAD

**Issue by tonyhogsten** [ansible/awx#9357]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
We cannot access the page Management Jobs or Cleanup Jobs. We are met with an empty page:

![image](https://user-images.githubusercontent.com/20438742/108371255-dc341f00-71fd-11eb-8c83-16eb65f26efb.png)

And if we try to access these through schedules -> click on any of the cleanup jobs, the page is empty as well.

![image](https://user-images.githubusercontent.com/20438742/108371436-07b70980-71fe-11eb-9f5e-dddd4a01d601.png)

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.17
* Operating System:  CentOS 8
* Web Browser: Chrome & Firefox

##### STEPS TO REPRODUCE
Login to the page and access any of the links. 

##### EXPECTED RESULTS

I expect a page where I can modify how many days we want to keep the data and adjust the schedule interval

##### ACTUAL RESULTS

Page is empty

##### ADDITIONAL INFORMATION

Screenshots are above

**Comment by jakemcdermott** [comment]
:wave: Hello, @tonyhogsten! This feature is under development. It will be included in one of the upcoming AWX community releases.

see: https://github.com/ansible/awx/issues/8488 -> https://github.com/ansible/awx/pull/9224
