### ISSUE TITLE
"x" button next to existing filter in smart host filters doesn't do anything

### ISSUE THREAD

**Issue by agaffney** [ansible/awx#936]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
In the dialog box for creating a smart host filter, clicking the "x" next to an existing filter (just below the search box) doesn't seem to do anything.

##### ENVIRONMENT
* AWX version: 1.0.2.327
* AWX install method: docker on linux
* Ansible version:  2.4.2.0 (from inside `awx_task` Docker container)
* Operating System: Ubuntu 16.04
* Web Browser: Chrome 63

##### STEPS TO REPRODUCE

1. Create new smart inventory
2. Click magnifying glass button next to "SMART HOST FILTER" box
3. Type "name:foo" and hit return in "SEARCH" box at top of "DYNAMIC HOSTS" dialog
4. Click "x" next to "name.icontains:foo" search filter that appears below the "SEARCH" box
5. Become perplexed when it doesn't disappear

##### EXPECTED RESULTS

The filter disappears

##### ACTUAL RESULTS

The filter doesn't disappear

##### ADDITIONAL INFORMATION

N/A

**Comment by jaredevantabor** [comment]
this is fixed in devel now
