### ISSUE TITLE
Show host description attribute on more places

### ISSUE THREAD

**Issue by Commifreak** [ansible/awx#9363]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Please add the Host description attribute to at least one (or all?) places:

* Job output: There, ansible only shows the IP address (if no real hostname given) - maybe not possible here but:
* Show the host description inside the host task result modal, next to its name:

![grafik](https://user-images.githubusercontent.com/87267/108463917-899b4700-727f-11eb-8abc-081346b53980.png)

That would be great :)

**Comment by wenottingham** [comment]
The first of these cannot happen - it would be making an extra REST request for every line of playbook output, which really isn't practical.

The second of these could potentially be possible (although it's still an extra request when loading the event details.)

**Comment by InnocentK** [comment]
Resolved
