### ISSUE TITLE
In AWX, I want to execute 8 jobs at the same time, but only 2 jobs are running at the same time. How should I set this limit to be turned on?

### ISSUE THREAD

**Issue by afucat** [ansible/awx#9375]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME

 - API

##### ENVIRONMENT
* AWX version: 17.0.0
* AWX install method:  docker on linux
* Ansible version:  2.9
* Operating System: CentOS7.6
* Web Browser:

**Comment by ryanpetrello** [comment]
Hey @zhengyionline,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
