### ISSUE TITLE
Smart Inventory host-filter (advanced search) UI produce search failure

### ISSUE THREAD

**Issue by ReneCamu** [ansible/awx#9389]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Smart inventory host filter "**advanced**" is not working in the UI after saving.

The selected "**or**" is changed to "**and**" after the host filter creation is selected.

Error: Invalid query groups__search=ubuntu and groups__search=centos

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker
* Ansible version:  2.9.17
* Operating System: CentOS
* Web Browser: Firefox, Chrome

##### STEPS TO REPRODUCE

Prequisites: one inventory with one group "centos" and a second group "ubuntu" server

1. Create a smart inventory based upon existing groups (ie. "centos" or "ubuntu")
2. Create a host filter advanced search with an "or" selection
   1. Name --> advanced
   2. Key --> groups
   3. LookupType --> icontains --> centos --> search
   4. LookupType --> icontains --> ubuntu --> search
   5. Result: all linux centos and ubuntu hosts
   6. Select
3. Save --> Error: Invalid query groups__search=ubuntu and groups__search=centos

With the use of the AWX cli the following search filter is working
awx-cli inventory create --name "Linux_Test_Group_OR" --organization 5  --kind smart --host-filter "groups__name__icontains=centos or groups__name__icontains=ubuntu" -d "All Linux server" -v

After the execution this Smart inventory is visible and can be used on the related hosts

##### EXPECTED RESULTS
The query created within the popup "Smart host filter" should be visible in the search field.

##### ACTUAL RESULTS
The host filter search field stays empty.

After trying to save the following error occurs: "Invalid query groups__search=ubuntu and groups__search=centos" below of the "Smart host filter"

**Comment by unlikelyzero** [comment]
@ReneCamu thanks for finding and filing this issue. We're tracking the failure here: https://github.com/ansible/awx/issues/9389

I've included your description in the issue before better discoverability

**Comment by ReneCamu** [comment]
Refering to issue: https://github.com/ansible/awx/issues/9232

**Comment by ReneCamu** [comment]
> @ReneCamu thanks for finding and filing this issue. We're tracking the failure here: #9389
> 
> I've included your description in the issue before better discoverability

@unlikelyzero Refering to https://github.com/ansible/awx/issues/9232
