### ISSUE TITLE
Network visualization fails to show hosts missing name hostvar

### ISSUE THREAD

**Issue by jladdjr** [ansible/awx#939]
### Summary

Network visualization fails to show hosts missing `name` hostvar.

### Environment

Branch network_ui_3_3
AWX 1.0.2-596-g6f9d0b7

### Steps To Reproduce:

1. Create an inventory
2. Add a host. Do not create any hostvars.
3. With the browser console open, return to the inventory list page. Click on the network topology icon for the inventory.

### Expected Results:

Canvas showing generic box representing host.

### Actual Results:

```
angular.js:14791 TypeError: Cannot read property 'name' of undefined
    at network.ui.controller.js:189
    at processQueue (angular.js:17160)
    at angular.js:17208
    at Scope.$digest (angular.js:18343)
    at Scope.$apply (angular.js:18640)
    at done (angular.js:12618)
    at completeRequest (angular.js:12862)
    at XMLHttpRequest.requestLoaded (angular.js:12779) "Possibly unhandled rejection: {}"
```

**Comment by abatista75** [comment]
What could be the workaround?

**Comment by jaredevantabor** [comment]
This has been fixed. The host will default to the name set in the host form.
