### ISSUE TITLE
unable to deploy awx on Ubuntu 20.04 since commit "af6af052d010240ed8a505e914d685bb2acb7283"

### ISSUE THREAD

**Issue by cic-hc** [ansible/awx#9393]
- ##### SUMMARY
with the current source, i am not able to install awx anymore on Ubuntu 20.04. It worked perfectly since the last commit "af6af052d010240ed8a505e914d685bb2acb7283".

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.6
* Operating System: Ubuntu 20.4
* Web Browser: firefox

##### STEPS TO REPRODUCE

sudo ansible-playbook -i inventory install.yml  -vvvv

[ansible_awx_install_OK.log](https://github.com/ansible/awx/files/6030979/ansible_awx_install_OK.log)
--> deployment from previous source

##### ACTUAL RESULTS
[ansible.log](https://github.com/ansible/awx/files/6030981/ansible.log)
--> deployment from actual source which does not work

**Comment by wenottingham** [comment]
Yes, this is intentional.

See https://groups.google.com/g/awx-project/c/47MjWSUQaOc/m/1-Jh0fy3AgAJ

**Comment by rooftopcellist** [comment]
@cslinuxfr Please see these docs for getting the development environment set up - https://github.com/ansible/awx/blob/devel/tools/docker-compose/README.md

**Comment by LokiOfNorse** [comment]
@cslinuxfr you can install v17.0.0.0 and it works fine. If your user credentials doesn't follow in the build, create the admin user manually within the web container cli.
