### ISSUE TITLE
ad-hoc commands don't show what they'll run on before hitting 'launch'

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#9399]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
1. Go to an inventory
2. Click 'Groups'
3. Click 'Run command'
4. Start filling out wizard
5. Go to credential page

You now have a 'Launch' button that only shows you what credential you've selected, not:
- the command and args
- the inventory
- any limit

This probably needs a review/preview step.

##### ENVIRONMENT
* AWX version: devel

**Comment by jakemcdermott** [comment]
(Note: If this ends up being more work than expected we can consider punting for later)
