### ISSUE TITLE
AWX Installation on Kubernetes with External PostgreSQL 

### ISSUE THREAD

**Issue by kapilkumartrivedi** [ansible/awx#9405]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

I am trying to install AWX on Kubernetes(new to ansible/awx). Installation fails on task migrate database.

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: Kubernetes 
* Ansible version:  2.9.17
* Operating System: CentOS 7
* Web Browser: NA

##### STEPS TO REPRODUCE

1. Clone the Repo
2. Make the following changes to installer/inventory
> localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python3"
> [all:vars]
> dockerhub_base=ansible
> 
> kubernetes_context=kubernetes-admin@kubernetes
> kubernetes_namespace=awx
> kubernetes_web_svc_type=NodePort
> 
> awx_task_hostname=awx
> awx_web_hostname=awxweb
> host_port=80
> host_port_ssl=443
> 
> pg_hostname=<server fqdn> # awxpsql.example.com
> pg_username=awxk
> pg_password="password"
> pg_database=awx
> pg_port=5432
> 
> admin_user=admin
> admin_password=password
> 
> create_preload_data=false
> 
> secret_key=awxsecret1234
> 
> broadcast_websocket_secret=awxsecret1234
> 
> awx_official=true

3. RUN **ansible-playbook -i installer/inventory installer/install.yml**

##### EXPECTED RESULTS

No error on installation. deployment to kubernetes successfully complete.

##### ACTUAL RESULTS

Got the error as below:

> fatal: [localhost]: FAILED! => {"changed": true, "cmd": "kubectl -n awx exec ansible-tower-management --  bash -c \"awx-manage migrate --noinput\"\n", "delta": "0:00:00.966584", "end": "2021-02-24 07:06:34.908655", "msg": "non-zero return code", "rc": 1, "start": "2021-02-24 07:06:33.942071", "stderr": "Traceback (most recent call last):\n  File \"/usr/lib64/python3.6/logging/config.py\", line 692, in add_filters\n    filterer.addFilter(self.config['filters'][f])\n  File \"/usr/lib64/python3.6/logging/config.py\", line 326, in __getitem__\n    value = dict.__getitem__(self, key)\nKeyError: 'guid'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib64/python3.6/logging/config.py\", line 565, in configure\n    handler = self.configure_handler(handlers[name])\n  File \"/usr/lib64/python3.6/logging/config.py\", line 753, in configure_handler\n    self.add_filters(result, filters)\n  File \"/usr/lib64/python3.6/logging/config.py\", line 694, in add_filters\n    raise ValueError('Unable to add filter %r: %s' % (f, e))\nValueError: Unable to add filter 'guid': 'guid'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/bin/awx-manage\", line 8, in <module>\n    sys.exit(manage())\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py\", line 154, in manage\n    execute_from_command_line(sys.argv)\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py\", line 381, in execute_from_command_line\n    utility.execute()\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py\", line 357, in execute\n    django.setup()\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/__init__.py\", line 19, in setup\n    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/utils/log.py\", line 76, in configure_logging\n    logging_config_func(logging_settings)\n  File \"/usr/lib64/python3.6/logging/config.py\", line 802, in dictConfig\n    dictConfigClass(config).configure()\n  File \"/usr/lib64/python3.6/logging/config.py\", line 573, in configure\n    '%r: %s' % (name, e))\nValueError: Unable to configure handler 'console': Unable to add filter 'guid': 'guid'\ncommand terminated with exit code 1", "stderr_lines": ["Traceback (most recent call last):", "  File \"/usr/lib64/python3.6/logging/config.py\", line 692, in add_filters", "    filterer.addFilter(self.config['filters'][f])", "  File \"/usr/lib64/python3.6/logging/config.py\", line 326, in __getitem__", "    value = dict.__getitem__(self, key)", "KeyError: 'guid'", "", "During handling of the above exception, another exception occurred:", "", "Traceback (most recent call last):", "  File \"/usr/lib64/python3.6/logging/config.py\", line 565, in configure", "    handler = self.configure_handler(handlers[name])", "  File \"/usr/lib64/python3.6/logging/config.py\", line 753, in configure_handler", "    self.add_filters(result, filters)", "  File \"/usr/lib64/python3.6/logging/config.py\", line 694, in add_filters", "    raise ValueError('Unable to add filter %r: %s' % (f, e))", "ValueError: Unable to add filter 'guid': 'guid'", "", "During handling of the above exception, another exception occurred:", "", "Traceback (most recent call last):", "  File \"/usr/bin/awx-manage\", line 8, in <module>", "    sys.exit(manage())", "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py\", line 154, in manage", "    execute_from_command_line(sys.argv)", "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py\", line 381, in execute_from_command_line", "    utility.execute()", "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py\", line 357, in execute", "    django.setup()", "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/__init__.py\", line 19, in setup", "    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)", "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/utils/log.py\", line 76, in configure_logging", "    logging_config_func(logging_settings)", "  File \"/usr/lib64/python3.6/logging/config.py\", line 802, in dictConfig", "    dictConfigClass(config).configure()", "  File \"/usr/lib64/python3.6/logging/config.py\", line 573, in configure", "    '%r: %s' % (name, e))", "ValueError: Unable to configure handler 'console': Unable to add filter 'guid': 'guid'", "command terminated with exit code 1"], "stdout": "", "stdout_lines": []}

Error Formatted:

> Traceback (most recent call last):
>   File "/usr/lib64/python3.6/logging/config.py", line 692, in add_filters
>     filterer.addFilter(self.config['filters'][f])
>   File "/usr/lib64/python3.6/logging/config.py", line 326, in __getitem__
>     value = dict.__getitem__(self, key)
> KeyError: 'guid'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib64/python3.6/logging/config.py", line 565, in configure
>     handler = self.configure_handler(handlers[name])
>   File "/usr/lib64/python3.6/logging/config.py", line 753, in configure_handler
>     self.add_filters(result, filters)
>   File "/usr/lib64/python3.6/logging/config.py", line 694, in add_filters
>     raise ValueError('Unable to add filter %r: %s' % (f, e))
> ValueError: Unable to add filter 'guid': 'guid'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/bin/awx-manage", line 8, in <module>
>     sys.exit(manage())
>   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 154, in manage
>     execute_from_command_line(sys.argv)
>   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
>     utility.execute()
>   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
>     django.setup()
>   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
>     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
>   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/utils/log.py", line 76, in configure_logging
>     logging_config_func(logging_settings)
>   File "/usr/lib64/python3.6/logging/config.py", line 802, in dictConfig
>     dictConfigClass(config).configure()
>   File "/usr/lib64/python3.6/logging/config.py", line 573, in configure
>     '%r: %s' % (name, e))
> ValueError: Unable to configure handler 'console': Unable to add filter 'guid': 'guid'
> 

##### ADDITIONAL INFORMATION

its a simple 2 nodes kubernetes cluster.

**Comment by ryanpetrello** [comment]
@kapilkumartrivedi,

Make sure you're actually using the 17.0.1 tag, and not `devel` (it sounds like you're running into a bug in `devel` that was fixed the other day: https://github.com/ansible/awx/pull/9378)
