### ISSUE TITLE
RFE: Add flag to skip firewall role during install

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#9408]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Not all environments utilize iptables or firewalld. Adding an option to skip this as part of the installer would remove this extra step when not necessary.

**Comment by wenottingham** [comment]
... is the issue that the role is loaded and a set of tasks are then skipped? Is there any functionality loss that is caused by this?

**Comment by wenottingham** [comment]
There's no firewall role in the awx installer.
