### ISSUE TITLE
Logger test button doesn't function (and may not make sense)

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#9409]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

The 'test' button for logging aggregations is currently inactive by default:
![Screenshot from 2021-02-24 12-40-04](https://user-images.githubusercontent.com/5208768/109041873-83510480-769d-11eb-83b3-da4120f9527d.png)

However, since it only appears on the 'Edit' view, that means it never functions right away - once you save, you don't see the button, and you have to go back to the 'Edit' view to click it..

In addition, the 'test' feature only ever tested that the event was sent to the intermediary rsyslog - it does not test the proper receipt of the message on the configured logging server.

Recommendation: remove the button in the UI

##### ENVIRONMENT
* AWX version: head 0f6d2c36a03787ed5ca0c8084815d13e49b344e1, 2021-02-22

**Comment by tiagodread** [comment]
Removed!
![image](https://user-images.githubusercontent.com/12464858/122451965-1bda0000-cf7f-11eb-8f0f-f98d68bd8ec3.png)
