### ISSUE TITLE
RFE: Openstack Credential Expansion

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/awx#941]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
Expand UI openstack credential with other os-client-config options available for [clouds.yaml](https://docs.openstack.org/os-client-config/latest/user/configuration.html#config-files). For example `verify` for SSL verification.

##### ENVIRONMENT
* AWX version: 1

**Comment by Durburz** [comment]
This is really needed. Because the OpenStack modules are falling back to Identity API version 2 which is deprecated. This could be changed, when there is a option for setting the Identity version in AWX.

**Comment by AlanCoding** [comment]
Looks like this was resolved by https://github.com/ansible/awx/pull/3262, @ryanpetrello does that sound right?

**Comment by ryanpetrello** [comment]
Yep, I agree.
