### ISSUE TITLE
Prevent users from selecting job templates that are missing a project or inventory when creating workflow node

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#9410]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
In the old UI we would disable rows that were missing a project/inv and didn't prompt for inventory:

<img width="1673" alt="Screen Shot 2021-02-24 at 1 00 46 PM" src="https://user-images.githubusercontent.com/9889020/109044677-ad57f600-76a0-11eb-90cc-b89735c86d58.png">

We should do something similar in the new UI since selecting a JT like this will result in the API returning an error when we attempt to save the workflow.

It would be nice if we could also add a tooltip or something like that to the row explaining why it can't be selected.

For existing nodes, the row will be selected on edit but it will still be disabled:

<img width="1674" alt="Screen Shot 2021-02-24 at 1 05 00 PM" src="https://user-images.githubusercontent.com/9889020/109044872-ebedb080-76a0-11eb-959e-b8d9c037e91f.png">

**Comment by unlikelyzero** [comment]
covered by https://github.com/ansible/tower-qa/pull/6060
