### ISSUE TITLE
Add prompt on launch to username of credentials

### ISSUE THREAD

**Issue by gamethis** [ansible/awx#9411]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

add option to prompt on launch for credential object username field.
Use case:
Multiple OS's managed with same ssh key but different user names on different platforms for managing the various platforms.
Add option to prompt on launch to credential item so it can leverage the key while being flexible about the username. Which reduces the number of credential objects that have to be maintained.

**Comment by wenottingham** [comment]
ansible_user can be set at the host/group level as well, if that simplifies it. That should override what is passed in the credential.

**Comment by gamethis** [comment]
thank you I will test that out.

**Comment by blomquisg** [comment]
If you still have problems with this, please reopen this issue.
