### ISSUE TITLE
Installation of AWX skip all tasks even if they are met ( Centos7.9 Docker 20.X Python >3.6)

### ISSUE THREAD

**Issue by rdzielicki** [ansible/awx#9413]
##### ISSUE TYPE
 - Bug Report all Playbook installation are skipped

##### SUMMARY
-After preparing a new Centos 7.9 with Docker 20.X, Python 3.6, all tasks of installation are skipped 
In the installation guide, requierement are met ( recent version of Docker Python 3.6 ..)

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: Docker
* Ansible version:  2.9
* Operating System: Centos7.9
* Web Browser:

##### STEPS TO REPRODUCE

Fresh installation of Centos 7.9 with Docker repo
Start AWX installation no erros but no containers at the ends created

##### EXPECTED RESULTS

AWX containers are running

##### ACTUAL RESULTS

The Playbook  returns no erros and most of the tasks are skipped

**Comment by rdzielicki** [comment]
tried an AWX N-2 version, worked perfectly the first time, seems like it may concern only this version

**Comment by yigitpolat** [comment]
it seems like they have moved the docker-compose installation steps to https://github.com/ansible/awx/tree/devel/tools/docker-compose
But couldn't make it work. What you mean with N-2 version by the way, let me give a try to that one.

**Comment by rdzielicki** [comment]
in fact more than n-2 version, AWX 14.0.1 works perfectly in my environnement
Also a big warning regarding 17.X version: AWX interface configuration is not implemented yet ( showing screen coming soon), so if you need extra vars global vars, you cant use them with AWX 17.X ( ie SSL verify disable)

**Comment by LokiOfNorse** [comment]
@rdzielicki @yigitpolat i have been trying this myself for a few days with different versions. 
Latest is to be compiled in docker compose as a dev environment or use Kubernetes for prod. 

I found that installing v17.0.0 and migrate db and create admin user within the web docker itself worked. There is absolute a lack of documentation.

**Comment by yigitpolat** [comment]
@LokiOfNorse It seems they have just took docker-compose documentation from main README.md file to tools/docker-compose/README.md. Probably it will be more clear in the following days.

Besides, I followed the documentation and executed the make docker-compose build, make docker-compose, created admin user, however still cannot connect to the frontend. 

On the left hand-side make docker-compose is running and on the right hand-side you can see the containers running. However I am receiving connection reset by peer when I try to reach out to the home path. It is a centos environment running on vagrant box and awx v17.0.0. How did you achieve to run it? 

<img width="1792" alt="Screen Shot 2021-02-28 at 01 38 21" src="https://user-images.githubusercontent.com/15480459/109402339-26d43a80-7966-11eb-9daf-d490558f2b9c.png">

**Comment by LokiOfNorse** [comment]
@yigitpolat Hi, 
Follow this guide until the git clone (don't do that) https://computingforgeeks.com/how-to-install-ansible-awx-on-ubuntu-linux/ . (next steps as sudo)
`wget https://github.com/ansible/awx/releases/tag/17.0.0`
`tar -xvzf 17.0.0.tar.gz`
`mv awx-17.0.0 awx`
cd into awx/installer and run the playbook. If it stops at the last step: migrate task container or what it was. hit ctrl - c. 
Check if the container is running: docker ps. If the container is running and run the following commands in the web container:
`docker container exec -it 'container id' awx-manage migrate --noinput` - to migrate manually
`docker container exec -it 'container id' awx-manage createsuperuser --username admin` - to create admin user and follow steps. 

PS: Im installing on ubuntu. I guess centOS commands is different.

**Comment by yigitpolat** [comment]
Yes, this definitely works, Thanks! My problem is with 17.0.1 release. Been working on it but couldn't make it run.

**Comment by LokiOfNorse** [comment]
@yigitpolat  no problem. 
Im now having some issues with "Sync for Revision" when trying to connect to local hosted gitlab. 
Is there any stable version of this that is working? hehe

**Comment by LokiOfNorse** [comment]
Jobs is stuck at pending and I can't see any containers named "Task". Only web, Postgress and rediss.

**Comment by yigitpolat** [comment]
Let me know if you give a chance to https://github.com/ansible/awx/tree/devel/tools/docker-compose

**Comment by LokiOfNorse** [comment]
@yigitpolat  i have followed the steps in that url very carefully but it doesn't work. I only get stuck in the dubbed lines and it can run forever (multiple hours) until I stop it.

**Comment by LokiOfNorse** [comment]
@yigitpolat 
What I figured out was that the debug start when it can't start the one container. Hit ctrl + c and you will see an error" can't kill ´container ID´because ´container ID´ is not running. 
Run `docker start 'container id' ` (of the container that can't start) and awx_tools is good. 

Then run: docker exec tools_awx_1 make clean-ui ui-devel
The awx will then run in the localhost as documented https://github.com/ansible/awx/blob/devel/awx/ui_next/README.md

To run it from a separate server: `TARGET='https://SERVER_IP:8043' npm --prefix awx/ui_next start` 
The server ip and port will be printed. I then will get apiv2 error running down the screen. 

But gain: its for dev, local deployment etc. 
I think trying it for Kubernetes cluster would be better

**Comment by yigitpolat** [comment]
@LokiOfNorse 

What is says here (https://github.com/ansible/awx/tree/devel/tools/docker-compose) is after running `docker exec tools_awx_1 make clean-ui ui-devel`, the UI can be reached in your browser at https://localhost:8043/#/home

Checkout my screenshot above. After I run `docker exec tools_awx_1 make clean-ui ui-devel`, I show the running containers with docker ps and then try to curl localhost with ports and no answer returns back.

Later on, I run `TARGET='https://awx.local:8043' npm --prefix awx/ui_next start` on my localhost, the UI started, however, it was listening on 3001. 

So It works somehow with workarounds but what I didn't understand is the documentation here (https://github.com/ansible/awx/tree/devel/tools/docker-compose) does not work how I expected.

**Comment by LokiOfNorse** [comment]
@yigitpolat The line I wrote is for development.

Im in this process now: https://github.com/ansible/awx/blob/devel/awx/ui_next/README.md#building-for-production building for production and changes the ip address all the way down. 

Im not sure if it will work but the build for production is out of date and this needs a new guide I guess? I don't understand the documentation rules or guides here.

**Comment by yigitpolat** [comment]
Nice idea. Lets see if that works.

I will later on try to deployment to Kubernetes or OpenShift. Hope those will be run as expected.

**Comment by LokiOfNorse** [comment]
@yigitpolat  well as I understand awx documentation after a week of working with it from every angle. 
Docker deployments are for development, and you can build for production but you need to secure it and configure it your self first. 

Kubernetes is for prod.

**Comment by yigitpolat** [comment]
@LokiOfNorse yep that is what I thought as well. But at the same time I thought development environment will be enough for me as I will use that just for learning and trying stuff. So docker-compose up is really simplified and fast method. However, I still wonder why I couldnt make it work.

**Comment by LokiOfNorse** [comment]
@yigitpolat followed the dev guides to the point. didn't work. 
I guess cabernets cluster there is since the other guides doesn't work.

**Comment by rdzielicki** [comment]
hope the support with Docker will be still maintained, in the requierements it should be still supported

**Comment by jonathan2324** [comment]
Hi Everyone,

Did anyone on here end up figuring out how to make this work? I am trying to install awx on Ubuntu but it is not working correctly. I see the skipping on all tasks as well and I even tried to use the docker guide in the repo with no success.

**Comment by yigitpolat** [comment]
I later realized the devel branch is the master and get the latest commits. So many documentations on the web outdated. The best way to work with the awx version is releases https://github.com/ansible/awx/releases
However, I couldn't make it work with the latest versions since I am facing with awx_task container created but never running. The release version 12.0.0 works fine.

**Comment by LokiOfNorse** [comment]
@yigitpolat Anything you miss in the 12 version? Do you deploy it regular way or do you have any guide on this?

**Comment by yigitpolat** [comment]
@LokiOfNorse Follow this https://medium.com/wxit/install-ansible-awx-on-centos-8-62c12b39890

**Comment by LokiOfNorse** [comment]
@yigitpolat its cents. well I guess I need to learn that one day also :) Thank you

**Comment by yigitpolat** [comment]
@LokiOfNorse Sorry, yes I was using cents. Probably very familiar with similar packages on ubuntu.

**Comment by jonathan2324** [comment]
@yigitpolat Do you have an example of the commands you are using with the releases? I am trying to use the version 16.0.0 but for some reason I cannot figure out how to do this.

**Comment by LokiOfNorse** [comment]
@yigitpolat finally!!! :D After soon two weeks your guide did the job with ease! 
So running Proxmox (brand new to it, love it) and awx in a container deployment. 

Writing jobs on my Mac, pushing the code to my local gitlab server, connected local gitlab server to AWX and it works like a dream! Thank you so much :)

**Comment by yigitpolat** [comment]
Nice to hear that mate. Cheers !
