### ISSUE TITLE
Getting skipping: [localhost] error & almost all tasks are skipped.

### ISSUE THREAD

**Issue by pipinstallyogi** [ansible/awx#9415]
Hallo Everyone,

**After every configuration when I am running the following command:
#  ansible-playbook -i inventory install.yml
I am getting the following error :**

PLAY [Build and deploy AWX] **********************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [localhost]

TASK [check_vars : admin_password should be defined] *********************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [check_vars : include_tasks] ****************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Generate broadcast websocket secret] ******************************************************************************************************
skipping: [localhost]

TASK [kubernetes : fail] *************************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : include_tasks] ****************************************************************************************************************************
skipping: [localhost] => (item=openshift_auth.yml)
skipping: [localhost] => (item=openshift.yml)

TASK [kubernetes : include_tasks] ****************************************************************************************************************************
skipping: [localhost] => (item=kubernetes_auth.yml)
skipping: [localhost] => (item=kubernetes.yml)

TASK [kubernetes : Use kubectl or oc] ************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : set_fact] *********************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Record deployment size] *******************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Set expected post-deployment Replicas value] **********************************************************************************************
skipping: [localhost]

TASK [kubernetes : Delete existing Deployment (or StatefulSet)] **********************************************************************************************
skipping: [localhost]

TASK [kubernetes : Get Postgres Service Detail] **************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Template PostgreSQL Deployment (OpenShift)] ***********************************************************************************************
skipping: [localhost]

TASK [kubernetes : Deploy and Activate Postgres (OpenShift)] *************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Create Temporary Values File (Kubernetes)] ************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Populate Temporary Values File (Kubernetes)] **********************************************************************************************
skipping: [localhost]

TASK [kubernetes : Deploy and Activate Postgres (Kubernetes)] ************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Remove tempfile] **************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Set postgresql hostname to helm package service (Kubernetes)] *****************************************************************************
skipping: [localhost]

TASK [kubernetes : Wait for Postgres to activate] ************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Check if Postgres 10 is being used] *******************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Set new pg image] *************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Wait for change to take affect] ***********************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Set env var for pg upgrade] ***************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Wait for change to take affect] ***********************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Set env var for new pg version] ***********************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Wait for Postgres to redeploy] ************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Wait for Postgres to finish upgrading] ****************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Unset upgrade env var] ********************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Wait for Postgres to redeploy] ************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Set awx image name] ***********************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Determine Deployment api version] *********************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Get Root CA file contents] ****************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Render Root CA template] ******************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Apply Root CA template] *******************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Set Root CA file name] ********************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Set Root CA file location] ****************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Render deployment templates] **************************************************************************************************************
skipping: [localhost] => (item=None)
skipping: [localhost] => (item=None)
skipping: [localhost] => (item=None)
skipping: [localhost] => (item=None)
skipping: [localhost]

TASK [kubernetes : Apply Deployment] *************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Delete any existing management pod] *******************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Template management pod] ******************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Create management pod] ********************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Wait for management pod to start] *********************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Migrate database] *************************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Check for Tower Super users] **************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : create django super user if it does not exist] ********************************************************************************************
skipping: [localhost]

TASK [kubernetes : update django super user password] ********************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Create the default organization if it is needed.] *****************************************************************************************
skipping: [localhost]

TASK [kubernetes : Delete management pod] ********************************************************************************************************************
skipping: [localhost]

TASK [kubernetes : Scale up deployment] **********************************************************************************************************************
skipping: [localhost]

PLAY RECAP ***************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=49   rescued=0    ignored=0

**System Config:
Ubuntu 18.04.5 LTS
ansible 2.10.6
Docker Compose: 1.28.4
Docker CE: 20.10.3**

I have tried from changing the versions from dockers to changing version of ansible but nothing worked out for me. Any help will be highly appreciated. Thanks in advance.

**Comment by ryanpetrello** [comment]
Hey @pipinstallyogi,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by LokiOfNorse** [comment]
@pipinstallyogi 
Same here. I installed version 17.0.0 I stead. Worked but didn't find the version that stabile. 
I had to create the admin user afterwords from within the docker.

**Comment by pipinstallyogi** [comment]
@LokiOfNorse So when you created admin user from within the Docker, did it work as expected? Thanks

**Comment by LokiOfNorse** [comment]
@pipinstallyogi 
Yes, for some reason the build would not take my user creds with it and installation halted in the last task. So I had to migrate db and create user in the web container manually after some hours of searching in forums. 

I can now login, but I have not yet to test AWX to see if its works with any playbooks but, I hope to have time tomorrow. Let me note that im new to both DevOps and ansible.

**Comment by Mikhail42** [comment]
In my case it's was because of `when` condition, not because of localhost
