### ISSUE TITLE
Re-evaluate RBAC for EE as per latest API changes

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#9416]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Re-evaluate RBAC for EE as per latest API changes. Since the last time RBAC was evaluated on the UI side, the API RBAC has been updated. Evaluate those changes and apply to the UI.

See: https://github.com/ansible/awx/issues/9518

**Comment by jbradberry** [comment]
Related #9346
