### ISSUE TITLE
RFE: Re-introduce Fact Cleanup Job

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#9418]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The fact cleanup job was deprecated in 3.3 and removed in 3.5. Currently, the only way to purge facts on a host is to run the clean_facts meta task in a playbook:

- hosts: all
  gather_facts: false
  tasks:
    - name: Clear gathered facts from all currently targeted hosts
      meta: clear_facts

There should be a quick method in the UI to clean facts from hosts when required by users outside of running a job template.

**Comment by gamuniz** [comment]
@msilmser Is there any reason that fact cache timeout can't be used to automatically remove facts older than X time?

**Comment by msilmser** [comment]
thanks @gamuniz! that works for me!
