### ISSUE TITLE
'Kubernetes: Migrate Database' Fails with 'ValueError: Unable to configure handler 'console''

### ISSUE THREAD

**Issue by beny18241** [ansible/awx#9419]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Using the Kubernetes install method, the "Migrate database" step fails within the error: "ValueError: Unable to configure handler 'console': Unable to add filter 'guid': 'guid'", "command terminated with exit code 1"]"

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: kubernetes
* Ansible version:  2.9.18
* Operating System: SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

##### STEPS TO REPRODUCE

1)Create an inventory file for a K8s installation.
2)Run: ansible-playbook -i inventory install.yml 

##### EXPECTED RESULTS

complete installation

##### ACTUAL RESULTS

The following error appears using verbose mode:
TASK [kubernetes : Migrate database] *************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "kubectl -n default exec ansible-tower-management --  bash -c \"awx-manage migrate --noinput\"\n", "delta": "0:00:06.230120", "end": "2021-02-26 07:40:12.154488", "msg": "non-zero return code", "rc": 1, "start": "2021-02-26 07:40:05.924368", "stderr": "Traceback (most recent call last):\n  File \"/usr/lib64/python3.6/logging/config.py\", line 692, in add_filters\n    filterer.addFilter(self.config['filters'][f])\n  File \"/usr/lib64/python3.6/logging/config.py\", line 326, in __getitem__\n    value = dict.__getitem__(self, key)\nKeyError: 'guid'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib64/python3.6/logging/config.py\", line 565, in configure\n    handler = self.configure_handler(handlers[name])\n  File \"/usr/lib64/python3.6/logging/config.py\", line 753, in configure_handler\n    self.add_filters(result, filters)\n  File \"/usr/lib64/python3.6/logging/config.py\", line 694, in add_filters\n    raise ValueError('Unable to add filter %r: %s' % (f, e))\nValueError: Unable to add filter 'guid': 'guid'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/bin/awx-manage\", line 8, in <module>\n    sys.exit(manage())\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py\", line 154, in manage\n    execute_from_command_line(sys.argv)\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py\", line 381, in execute_from_command_line\n    utility.execute()\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py\", line 357, in execute\n    django.setup()\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/__init__.py\", line 19, in setup\n    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/utils/log.py\", line 76, in configure_logging\n    logging_config_func(logging_settings)\n  File \"/usr/lib64/python3.6/logging/config.py\", line 802, in dictConfig\n    dictConfigClass(config).configure()\n  File \"/usr/lib64/python3.6/logging/config.py\", line 573, in configure\n    '%r: %s' % (name, e))\nValueError: Unable to configure handler 'console': Unable to add filter 'guid': 'guid'\ncommand terminated with exit code 1", "stderr_lines": ["Traceback (most recent call last):", "  File \"/usr/lib64/python3.6/logging/config.py\", line 692, in add_filters", "    filterer.addFilter(self.config['filters'][f])", "  File \"/usr/lib64/python3.6/logging/config.py\", line 326, in __getitem__", "    value = dict.__getitem__(self, key)", "KeyError: 'guid'", "", "During handling of the above exception, another exception occurred:", "", "Traceback (most recent call last):", "  File \"/usr/lib64/python3.6/logging/config.py\", line 565, in configure", "    handler = self.configure_handler(handlers[name])", "  File \"/usr/lib64/python3.6/logging/config.py\", line 753, in configure_handler", "    self.add_filters(result, filters)", "  File \"/usr/lib64/python3.6/logging/config.py\", line 694, in add_filters", "    raise ValueError('Unable to add filter %r: %s' % (f, e))", "ValueError: Unable to add filter 'guid': 'guid'", "", "During handling of the above exception, another exception occurred:", "", "Traceback (most recent call last):", "  File \"/usr/bin/awx-manage\", line 8, in <module>", "    sys.exit(manage())", "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py\", line 154, in manage", "    execute_from_command_line(sys.argv)", "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py\", line 381, in execute_from_command_line", "    utility.execute()", "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py\", line 357, in execute", "    django.setup()", "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/__init__.py\", line 19, in setup", "    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)", "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/utils/log.py\", line 76, in configure_logging", "    logging_config_func(logging_settings)", "  File \"/usr/lib64/python3.6/logging/config.py\", line 802, in dictConfig", "    dictConfigClass(config).configure()", "  File \"/usr/lib64/python3.6/logging/config.py\", line 573, in configure", "    '%r: %s' % (name, e))", "ValueError: Unable to configure handler 'console': Unable to add filter 'guid': 'guid'", "command terminated with exit code 1"], "stdout": "", "stdout_lines": []}

##### ADDITIONAL INFORMATION

running local minikube

**Comment by RosarioVinoth** [comment]
I ran into the same problem when deploying awx (v17.0.1) in kubernetes.




bash-4.4$ awx-manage migrate --noinput
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/config.py", line 692, in add_filters
    filterer.addFilter(self.config['filters'][f])
  File "/usr/lib64/python3.6/logging/config.py", line 326, in __getitem__
    value = dict.__getitem__(self, key)
KeyError: 'guid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/config.py", line 565, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib64/python3.6/logging/config.py", line 753, in configure_handler
    self.add_filters(result, filters)
  File "/usr/lib64/python3.6/logging/config.py", line 694, in add_filters
    raise ValueError('Unable to add filter %r: %s' % (f, e))
ValueError: Unable to add filter 'guid': 'guid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 154, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib64/python3.6/logging/config.py", line 802, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib64/python3.6/logging/config.py", line 573, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'console': Unable to add filter 'guid': 'guid'
bash-4.4$

**Comment by mlowery84** [comment]
copy of another issue 9419

**Comment by mlowery84** [comment]
Getting the same issues with my install on microk8s.   wondering if its related to the most recent pull request about guids ?

**Comment by Julieeeen** [comment]
I have the same issue when I try to install on AKS

**Comment by wenottingham** [comment]
You're installing with a mismatched installer version (devel) and image version (17.0.x).

Make sure you check out the tag for the version you want to install.

**Comment by Vagrantin** [comment]
Hello 
I'm experiencing the same issue and I have cloned AWX (devel) and AWX latest image ( no version specified )
I'm installing AWX within minikub based on virtualbox hypervisor

ISSUE TYPE

    Bug Report

SUMMARY

Using the Kubernetes install method, the "Migrate database" step fails within the error: "ValueError: Unable to configure handler 'console': Unable to add filter 'guid': 'guid'", "command terminated with exit code 1"]"
ENVIRONMENT

    AWX version: devel
    AWX image: latest
    AWX install method: kubernetes
    Ansible version: 2.10.6
    Operating System: ElementaryOS 5.1.7 Hera Built on Ubuntu 18.04.4 LTS

STEPS TO REPRODUCE

1)Create an inventory file for a K8s installation.
2)Run: ansible-playbook -i inventory install.yml

`dockerhub_base=ansible` <-- I guess it means latest AWX image on Dockerhube

EXPECTED RESULTS

complete installation
ACTUAL RESULTS

```
{
  "changed": true,
  "cmd": "kubectl -n awx exec ansible-tower-management --  bash -c \"awx-manage migrate --noinput\"\n",
  "delta": "0:00:00.939722",
  "end": "2021-03-02 23:17:30.080586",
  "msg": "non-zero return code",
  "rc": 1,
  "start": "2021-03-02 23:17:29.140864",
  "stderr": "Traceback (most recent call last):\n  File \"/usr/lib64/python3.6/logging/config.py\", line 692, in add_filters\n    filterer.addFilter(self.config['filters'][f])\n  File \"/usr/lib64/python3.6/logging/config.py\", line 326, in __getitem__\n    value = dict.__getitem__(self, key)\nKeyError: 'guid'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib64/python3.6/logging/config.py\", line 565, in configure\n    handler = self.configure_handler(handlers[name])\n  File \"/usr/lib64/python3.6/logging/config.py\", line 753, in configure_handler\n    self.add_filters(result, filters)\n  File \"/usr/lib64/python3.6/logging/config.py\", line 694, in add_filters\n    raise ValueError('Unable to add filter %r: %s' % (f, e))\nValueError: Unable to add filter 'guid': 'guid'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/bin/awx-manage\", line 8, in <module>\n    sys.exit(manage())\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py\", line 154, in manage\n    execute_from_command_line(sys.argv)\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py\", line 381, in execute_from_command_line\n    utility.execute()\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py\", line 357, in execute\n    django.setup()\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/__init__.py\", line 19, in setup\n    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)\n  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/utils/log.py\", line 76, in configure_logging\n    logging_config_func(logging_settings)\n  File \"/usr/lib64/python3.6/logging/config.py\", line 802, in dictConfig\n    dictConfigClass(config).configure()\n  File \"/usr/lib64/python3.6/logging/config.py\", line 573, in configure\n    '%r: %s' % (name, e))\nValueError: Unable to configure handler 'console': Unable to add filter 'guid': 'guid'\ncommand terminated with exit code 1",
  "stderr_lines": [
    "Traceback (most recent call last):",
    "  File \"/usr/lib64/python3.6/logging/config.py\", line 692, in add_filters",
    "    filterer.addFilter(self.config['filters'][f])",
    "  File \"/usr/lib64/python3.6/logging/config.py\", line 326, in __getitem__",
    "    value = dict.__getitem__(self, key)",
    "KeyError: 'guid'",
    "",
    "During handling of the above exception, another exception occurred:",
    "",
    "Traceback (most recent call last):",
    "  File \"/usr/lib64/python3.6/logging/config.py\", line 565, in configure",
    "    handler = self.configure_handler(handlers[name])",
    "  File \"/usr/lib64/python3.6/logging/config.py\", line 753, in configure_handler",
    "    self.add_filters(result, filters)",
    "  File \"/usr/lib64/python3.6/logging/config.py\", line 694, in add_filters",
    "    raise ValueError('Unable to add filter %r: %s' % (f, e))",
    "ValueError: Unable to add filter 'guid': 'guid'",
    "",
    "During handling of the above exception, another exception occurred:",
    "",
    "Traceback (most recent call last):",
    "  File \"/usr/bin/awx-manage\", line 8, in <module>",
    "    sys.exit(manage())",
    "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py\", line 154, in manage",
    "    execute_from_command_line(sys.argv)",
    "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py\", line 381, in execute_from_command_line",
    "    utility.execute()",
    "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py\", line 357, in execute",
    "    django.setup()",
    "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/__init__.py\", line 19, in setup",
    "    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)",
    "  File \"/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/utils/log.py\", line 76, in configure_logging",
    "    logging_config_func(logging_settings)",
    "  File \"/usr/lib64/python3.6/logging/config.py\", line 802, in dictConfig",
    "    dictConfigClass(config).configure()",
    "  File \"/usr/lib64/python3.6/logging/config.py\", line 573, in configure",
    "    '%r: %s' % (name, e))",
    "ValueError: Unable to configure handler 'console': Unable to add filter 'guid': 'guid'",
    "command terminated with exit code 1"
  ],
  "stdout": "",
  "stdout_lines": []
}
```
Thank you for the help
