### ISSUE TITLE
Unable to copy job templates with Normal User

### ISSUE THREAD

**Issue by 0xbentang** [ansible/awx#9420]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
A normal user can't copy job templates. 

The user already has admin permission on the inventory and project (the template doesn't need credentials)

I can create a new template with exactly the same inventory and project, but there isn't even a copy button for the new template.

This has been asked in below but still no concrete answers.

https://github.com/ansible/awx/issues/8137

https://groups.google.com/g/awx-project/c/guxEogZg3QM/m/GKN8hDVtBQAJ

I also dig through all the docs but can't see relevant solutions.

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.14
* Operating System: Ubuntu
* Web Browser: Firefox

##### STEPS TO REPRODUCE

1. Create a user as `Normal User`
2. Create an inventory and a project by System Admin
2. Give the user admin permission to the above inventory and project 
3. Create a template with the above inventory and project (create by Normal User)
4. No copy button for this template

##### EXPECTED RESULTS

![image](https://user-images.githubusercontent.com/33242068/109267375-6c98e200-7844-11eb-940b-6551d9f29fdd.png)

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/33242068/109267384-73bff000-7844-11eb-9001-e51a412ef0c5.png)

The Normal User can't even copy the template created by its own

**Comment by 0xbentang** [comment]
More testing:

Initially the user only has `Member` role in the organization.

After adding `workflow admin` now I can copy

I think this is very likely a bug

**Comment by blomquisg** [comment]
@btck30351 can you try in AWX 17.0?  It's possible this was fixed since 15.

**Comment by jakemcdermott** [comment]
> AWX version: 15.0.1

Yep, this was fixed in a later version. Please upgrade and give it a try - thank you!
