### ISSUE TITLE
[17.0.1] UI: Broken link: Clicking on "User Details" gives 404 Page Not Found

### ISSUE THREAD

**Issue by emulanob** [ansible/awx#9431]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
Clicking on "User Details" in the upper right page corner gives 404 Page Not Found.

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker (deployment on Nomad)
* Ansible version:  2.9.17
* Operating System: ubuntu 20.04
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. login into AWX
1. click on the user name in the top right corner
1. select User Details from the dropdown menu

##### EXPECTED RESULTS

User Details page, same as using the menu Users > clicking your username

##### ACTUAL RESULTS

404 Page Not Found

##### ADDITIONAL INFORMATION

This issue was fixed on 16.0.0 (https://github.com/ansible/awx/issues/8998) but apparently ported to 17.0.0.

**Comment by dR3b** [comment]
This Bug is also present in v17.1.0

**Comment by bendem** [comment]
It's missing a `#` in the url.

**Comment by unlikelyzero** [comment]
this has been fixed in the latest release!
