### ISSUE TITLE
Checkbox misaligned with items on final build Organization Lookup

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#9433]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Checkbox misaligned with items on final build Organization Lookup. This misalignment is not noticeable on devel environment, but as part of the final build. `make ui-devel`.

![image (7)](https://user-images.githubusercontent.com/9053044/109513547-38573880-7a73-11eb-8485-834c645d2e7d.png)

**Comment by tiagodread** [comment]
Fixed
