### ISSUE TITLE
request_tower_configuration.ps1 problem windows 2012 and 2016

### ISSUE THREAD

**Issue by lucab85** [ansible/awx#9434]
We have to limit this because of limited volunteer time to respond to issues! -->

##### ISSUE TYPE
 - Bug Report

##### SUMMARY
`request_tower_configuration.ps1` doesn't run on windows 2012 and 2016

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: ansible tower
* Ansible version:  2.9.15
* Operating System: Red Hat Enterprise Linux release 8.3 (Ootpa)
* Web Browser: Firefox 85.0.1

##### STEPS TO REPRODUCE

1. download  the latest version of request_tower_configuration.ps1
https://github.com/ansible/awx/blob/devel/tools/scripts/request_tower_configuration.ps1

2. Execute Powershell
3. Set Execution policy to Unrestricted (ref http://go.microsoft.com/fwlink/?LinkID=135170 )
$ `Set-ExecutionPolicy -ExecutionPolicy Unrestricted`
(confirm yes at the request)
```
PS C:\Users\Administrator> Set-ExecutionPolicy -ExecutionPolicy Unrestricted

Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose you to the security risks described in the about_Execution_Policies help topic at http://go.microsoft.com/fwlink/?LinkID=135170. Do you want to
change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
```
4. Execute request_tower_configuration.ps1
`$ C:\Users\Administrator\Desktop\request_tower_configuration.ps1 -s https://10.0.121.63 -k -c fc951820-04eb-4a27-9c9c-d9a1c01f48ff -t 42
`
5. Get Powershell version with
`$ (Get-Host).Version
`

##### EXPECTED RESULTS

Like windows 2019
```
PS C:\Users\Administrator> C:\Users\Administrator\Desktop\request_tower_configuration.ps1 -s https://10.0.121.63 -k -c f c951820-04eb-4a27-9c9c-d9a1c01f48ff -t 42
403 received... retrying in 1 minute (Attempt 1)
PS C:\Users\Administrator> 

```

##### ACTUAL RESULTS

- Windows 2012 - Powershell version (5.1.14409.1018)
```

Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\Administrator> C:\Users\Administrator\Desktop\request_tower_configuration.ps1 -s https://10.0.121.63 -k -c fc951820-04eb-4a27-9c9c-d9a1c01f48ff -t 42
C:\Users\Administrator\Desktop\request_tower_configuration.ps1 : The property 'StatusCode' cannot be found on this
object. Verify that the property exists.
At line:1 char:1
+ C:\Users\Administrator\Desktop\request_tower_configuration.ps1 -s htt ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [request_tower_configuration.ps1], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,request_tower_configuration.ps1

PS C:\Users\Administrator>
```
- Windows 2016 - Powershell version (5.1.14393.3866)

```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\Administrator> C:\Users\Administrator\Desktop\request_tower_configuration.ps1 -s https://10.0.121.63 -k -c f c951820-04eb-4a27-9c9c-d9a1c01f48ff -t 42
C:\Users\Administrator\Desktop\request_tower_configuration.ps1 : The property 'StatusCode' cannot be found on this object. Verify that the property exists.
At line:1 char:1
+ C:\Users\Administrator\Desktop\request_tower_configuration.ps1 -s htt ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [request_tower_configuration.ps1], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,request_tower_configuration.ps1

PS C:\Users\Administrator>

```
##### ADDITIONAL INFORMATION

It runs without errors when run without arguments:
```
PS C:\Users\Administrator> C:\Users\Administrator\Desktop\request_tower_configuration.ps1
Request server configuration from Ansible Tower

Usage:
    Execution using positional parameters:
    request_tower_configuration.ps1 https://example.towerhost.net 44d7507f2ead49af5fca80aa18fd24bc 38

    Ignore self-signed certificates using named parameters:
    request_tower_configuration.ps1 -k -s https://example.towerhost.local -c 44d7507f2ead49af5fca80aa18fd24bc -t 38

    Execution using optional extra_vars:
    request_tower_configuration.ps1 https://example.towerhost.net 44d7507f2ead49af5fca80aa18fd24bc 38 '{ key: value, dic
t: { key: value }}'

Options:
    -help, -h                                Show this message
    -tower_url, -s                           Tower server (e.g. https://<server address>[:server port]) (required)
    -insecure, -k                            Allow insecure SSL connections and transfers
    -host_config_key, -c <host config key>   Host config key (required)
    -job_template_id, -t <job template id>   Job template ID (required)
    -extra_vars, -e [<extra vars>]           Extra variables
```

**Comment by blomquisg** [comment]
@jborean93 Can you take a look at this from a powershell perspective?

**Comment by jborean93** [comment]
There could be a few reasons why this is happening, my guess is either

* Cert validation issues
* Tower only offers TLS 1.2+ which can cause issues out of the box on some Windows PowerShell setups

The error message is a cause of `Set-StrictMode -Version 2` where invalid properties are now an error and the catch block could catch all sorts of exceptions, e.g. ones without a `Response`.

I've submitted a PR that should fix this particular problem and expose the proper exception message in the case of an exception not having a `Response`. It also fixes those validation and TLS 1.2 problems I mentioned above so it might even fix the issue if that was the cause.

It would be great if you could try it out and see if it either fixes your problem or gives you a better error of the underlying problem https://github.com/ansible/awx/pull/9673

**Comment by lucab85** [comment]
I confirm that with #9673 solves the issue.
I was able to test the reproducer on Windows 2012 and Windows 2016 machines and this is the output after #9673:
```
C:\Users\Administrator\Desktop\request_tower_configuration_9673.ps1 -s https://10.0.121.63 -k -c fc951820-04eb-4a27-9c9c-d9a1c01f48ff -t 42
400 (BadRequest) received...  retrying in 1 minute (Attempt 1)
```
The connection was successful after the first try on Windows 2012 and Windows 2016 machines.

**Comment by ryanpetrello** [comment]
Thanks @lucab85!
