### ISSUE TITLE
[LDAP] No unbind after credentials verification

### ISSUE THREAD

**Issue by rockandska** [ansible/awx#9436]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When using LDAP connection, AWX doesn't send an `unbind` command to the LDAP server after checking the credentials.

##### ENVIRONMENT
* AWX version: 3.0.1.0
* AWX install method: docker
* Ansible version:  2.7.7
* Operating System: centos 7
* Web Browser: firefox

##### STEPS TO REPRODUCE

Configure ldap authentication and use it

##### EXPECTED RESULTS

```
Jul 17 16:53:53 server1 slapd[1010]: conn=7448 fd=43 connection from IP=X.X.X.X:40629 (IP=:: 389) accepted.
Jul 17 16:53:53 server1 slapd[1010]: conn=7448 op=0 BIND dn="uid=user1,ou=people,dc=example,dc=com" method=128
Jul 17 16:53:53 server1 slapd[1010]: conn=7448 op=0 RESULT tag=97 err=0 text=
Jul 17 16:53:53 server1 slapd[1010]: conn=7448 op=1 SRCH base="ou=people,dc=example,dc=com" scope=2 filter="(objectClass=*)"
Jul 17 16:53:53 server1 slapd[1010]: conn=7448 op=1 SEARCH RESULT tag=101 err=0 text=
Jul 17 16:53:54 server1 slapd[1010]: conn=7448 op=2 UNBIND
Jul 17 16:53:54 server1 slapd[1010]: conn=-1 fd=43 closed
```

##### ACTUAL RESULTS

Not the real log but equivalent to what we see

```
Jul 17 16:53:53 server1 slapd[1010]: conn=7448 fd=43 connection from IP=X.X.X.XX:40629 (IP=:: 389) accepted.
Jul 17 16:53:53 server1 slapd[1010]: conn=7448 op=0 BIND dn="uid=user1,ou=people,dc=example,dc=com" method=128
Jul 17 16:53:53 server1 slapd[1010]: conn=7448 op=0 RESULT tag=97 err=0 text=
Jul 17 16:53:53 server1 slapd[1010]: conn=7448 op=1 SRCH base="ou=people,dc=example,dc=com" scope=2 filter="(objectClass=*)"
Jul 17 16:53:53 server1 slapd[1010]: conn=7448 op=1 SEARCH RESULT tag=101 err=0 text=
Jul 17 16:54:54 server1 slapd[1010]: conn=7448 op=-1 - closing from X.X.X.X:40629 - T1 - Connection idle timeout exceeded -
Jul 17 16:54:54 server1 slapd[1010]: conn=-1 fd=43 closed
```

**Comment by ryanpetrello** [comment]
Hey @rockandska,

This might be a good thing to report to the folks that write https://github.com/django-auth-ldap/django-auth-ldap (AWX just makes use of this library).

If you see any movement upstream, or if a newer version already does this, let me know and when can update AWX to make use of it.

**Comment by rockandska** [comment]
Seems there is a PR on its way django-auth-ldap/django-auth-ldap/pull/174
