### ISSUE TITLE
Advanced search for type returns 400

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#9441]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Trying to do an advanced search by `type` the results are always `ExecutionEnvironment has no field named 'type'`:

![image](https://user-images.githubusercontent.com/12464858/109544586-83d70a00-7aa6-11eb-994c-dedcbce8801a.png)

**Comment by nixocio** [comment]
This is not just an issue with EE.  It seems like we will need to re-evaluate the `type` search for other resources as well. See Organization.

<img width="1451" alt="image" src="https://user-images.githubusercontent.com/9053044/109999983-cc7a0780-7ce0-11eb-8666-9433085a2d2b.png">

**Comment by mabashian** [comment]
Lets look and see if this is a dupe

**Comment by tiagodread** [comment]
Related: https://github.com/ansible/awx/issues/8480

**Comment by jakemcdermott** [comment]
On a second look-through this _appears_ to be api related - the `type` field shouldn't be populated in the first place if it isn't filterable.

**Comment by wenottingham** [comment]
See community PR https://github.com/ansible/awx/pull/9899 ?
