### ISSUE TITLE
s3 object decryption doesn't work with aws-encryption-sdk-cli/2.1.0 using shell module in AWX

### ISSUE THREAD

**Issue by vamsidvk09** [ansible/awx#9444]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
As part of the playbook execution , Playbook downloads s3 objects (basically acm certificates stored in s3 bucket with customer master key encryption enabled)  and decrypts using aws-encryption-cli (shell module used). Decryption operation is working fine in the task container where as AWX UI somehow fails the operation.
##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker compose on linux
* Ansible version:  2.9.18
* Operating System: centos7
* aws-encryption-sdk-cli/2.1.0
* aws-encryption-sdk/2.0.0

##### STEPS TO REPRODUCE
1.  Create a template in AWX with git as a source where playbook code reside
2. Playbook should consists of below tasks
- name: Download client certificates from s3 bucket
  aws_s3:
    region: eu-central-1
    bucket: "{{ certificates_s3_bucket }}"
    object: "{{ object }}"
    dest: "{{ temp_path }}"
    mode: get
    overwrite: different

- name: Decrypt the downloaded client ceritificates
  shell: >
    aws-encryption-cli --decrypt --input {{ temp_path }}\
    				  --wrapping-keys key=$key-arn \
                      --metadata-output ~/metadata \
                      --commitment-policy=forbid-encrypt-allow-decrypt \
                      --output {{ temp_path }} -vvv
3. Launch the template job
##### EXPECTED RESULTS

Decryption of the s3 object

##### ACTUAL RESULTS

Operation failed with below error

2021-03-02 11:56:02,175 - MainThread - aws_encryption_sdk_cli - DEBUG - Encryption mode: decrypt
2021-03-02 11:56:02,176 - MainThread - aws_encryption_sdk_cli - DEBUG - Encryption source: /tmp/
2021-03-02 11:56:02,176 - MainThread - aws_encryption_sdk_cli - DEBUG - Encryption destination: /tmp/
2021-03-02 11:56:02,176 - MainThread - aws_encryption_sdk_cli - DEBUG - Wrapping key provider configuration: [{&apos;key&apos;: [&apos;arn:aws:kms:eu-central-1:$account-id:key/$key-id;], &apos;region&apos;: [&apos;eu-central-1&apos;], &apos;provider&apos;: &apos;aws-encryption-sdk-cli::aws-kms&apos;, &apos;discovery&apos;: False}]
2021-03-02 11:56:02,176 - MainThread - aws_encryption_sdk_cli - DEBUG - Suffix requested: None
2021-03-02 11:56:02,177 - MainThread - aws_encryption_sdk_cli - DEBUG - Loading provider: aws-encryption-sdk-cli::aws-kms
2021-03-02 11:56:02,177 - MainThread - aws_encryption_sdk_cli - DEBUG - Discovering master key provider plugins
2021-03-02 11:56:02,183 - MainThread - aws_encryption_sdk_cli - INFO - Collecting plugin &quot;aws-kms&quot; registered by &quot;aws-encryption-sdk-cli 2.1.0&quot;
2021-03-02 11:56:02,184 - MainThread - aws_encryption_sdk_cli - DEBUG - Plugin details: {&apos;name&apos;: &apos;aws-kms&apos;, &apos;module_name&apos;: &apos;aws_encryption_sdk_cli.key_providers&apos;, &apos;attrs&apos;: (&apos;aws_kms_master_key_provider&apos;,), &apos;extras&apos;: (), &apos;dist&apos;: aws-encryption-sdk-cli 2.1.0 (/usr/local/lib/python3.6/site-packages)}
2021-03-02 11:56:02,300 - MainThread - aws_encryption_sdk_cli - DEBUG - Requested source: /tmp/
2021-03-02 11:56:02,300 - MainThread - aws_encryption_sdk_cli - DEBUG - Expanded source: [&apos;/tmp/&apos;]
2021-03-02 11:56:02,301 - MainThread - aws_encryption_sdk_cli - DEBUG - Duplicating filename $filename into /tmp/
2021-03-02 11:56:02,301 - MainThread - aws_encryption_sdk_cli - INFO - decrypting file /tmp/ to /tmp/$filename.decrypted
2021-03-02 11:56:02,302 - MainThread - aws_encryption_sdk.key_providers.base - INFO - decrypting data key with encryption context: {&apos;aws-crypto-public-key&apos;: &apos;$contextapos;}
2021-03-02 11:56:02,302 - MainThread - aws_encryption_sdk.key_providers.kms - ERROR - Removing regional client &quot;eu-central-1&quot; from cache due to BotoCoreError on decrypt call
--- Logging error ---
Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk_cli/internal/io_handling.py&quot;, line 216, in _single_io_write
    header=json_ready_header(handler.header),
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/streaming_client.py&quot;, line 204, in header
    self._prep_message()
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/streaming_client.py&quot;, line 774, in _prep_message
    self._header, self.header_auth = self._read_header()
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/streaming_client.py&quot;, line 810, in _read_header
    decryption_materials = self.config.materials_manager.decrypt_materials(request=decrypt_materials_request)
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/materials_managers/default.py&quot;, line 153, in decrypt_materials
    encryption_context=request.encryption_context,
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/key_providers/base.py&quot;, line 280, in decrypt_data_key_from_list
    data_key = self.decrypt_data_key(encrypted_data_key, algorithm, encryption_context)
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/key_providers/base.py&quot;, line 252, in decrypt_data_key
    data_key = master_key.decrypt_data_key(encrypted_data_key, algorithm, encryption_context)
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/key_providers/base.py&quot;, line 489, in decrypt_data_key
    encrypted_data_key=encrypted_data_key, algorithm=algorithm, encryption_context=encryption_context
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/key_providers/kms.py&quot;, line 458, in _decrypt_data_key
    response = self.config.client.decrypt(**kms_params)
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/key_providers/kms.py&quot;, line 159, in _wrap_client
    return method(*args, **kwargs)
  File &quot;/var/lib/awx/venv/ansible/lib/python3.6/site-packages/botocore/client.py&quot;, line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File &quot;/var/lib/awx/venv/ansible/lib/python3.6/site-packages/botocore/client.py&quot;, line 634, in _make_api_call
    api_params, operation_model, context=request_context)
  File &quot;/var/lib/awx/venv/ansible/lib/python3.6/site-packages/botocore/client.py&quot;, line 682, in _convert_to_request_dict
    api_params, operation_model)
  File &quot;/var/lib/awx/venv/ansible/lib/python3.6/site-packages/botocore/validate.py&quot;, line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: &quot;KeyId&quot;, must be one of: CiphertextBlob, EncryptionContext, GrantTokens

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/streaming_client.py&quot;, line 214, in __exit__
    self.close()
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/streaming_client.py&quot;, line 975, in close
    raise SerializationError(&quot;Footer not read&quot;)
aws_encryption_sdk.exceptions.SerializationError: Footer not read

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &quot;/usr/lib64/python3.6/logging/__init__.py&quot;, line 994, in emit
    msg = self.format(record)
  File &quot;/usr/lib64/python3.6/logging/__init__.py&quot;, line 840, in format
    return fmt.format(record)
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk_cli/internal/logging_utils.py&quot;, line 137, in format
    _record = self.__redact_record(record)
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk_cli/internal/logging_utils.py&quot;, line 123, in __redact_record
    _record = copy.deepcopy(record)
  File &quot;/usr/lib64/python3.6/copy.py&quot;, line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File &quot;/usr/lib64/python3.6/copy.py&quot;, line 280, in _reconstruct
    state = deepcopy(state, memo)
  File &quot;/usr/lib64/python3.6/copy.py&quot;, line 150, in deepcopy
    y = copier(x, memo)
  File &quot;/usr/lib64/python3.6/copy.py&quot;, line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File &quot;/usr/lib64/python3.6/copy.py&quot;, line 150, in deepcopy
    y = copier(x, memo)
  File &quot;/usr/lib64/python3.6/copy.py&quot;, line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File &quot;/usr/lib64/python3.6/copy.py&quot;, line 220, in &lt;listcomp&gt;
    y = [deepcopy(a, memo) for a in x]
  File &quot;/usr/lib64/python3.6/copy.py&quot;, line 169, in deepcopy
    rv = reductor(4)
TypeError: can&apos;t pickle traceback objects
Call stack:
  File &quot;/usr/local/bin/aws-encryption-cli&quot;, line 11, in &lt;module&gt;
    sys.exit(cli())
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk_cli/__init__.py&quot;, line 283, in cli
    process_cli_request(stream_args, args)
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk_cli/__init__.py&quot;, line 222, in process_cli_request
    handler.process_single_file(stream_args=stream_args, source=_source, destination=_destination)
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk_cli/internal/io_handling.py&quot;, line 343, in process_single_file
    stream_args=_stream_args, source=source_reader, destination=destination
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk_cli/internal/io_handling.py&quot;, line 275, in process_single_operation
    stream_args=stream_args, source=cast(IO, source), destination_writer=destination_writer
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk_cli/internal/io_handling.py&quot;, line 248, in _single_io_write
    _destination.flush()
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/streaming_client.py&quot;, line 218, in __exit__
    _LOGGER.exception(&quot;Error on closing&quot;)
Message: &apos;Error on closing&apos;
Arguments: ()
2021-03-02 11:56:02,305 - MainThread - aws_encryption_sdk_cli - WARNING - Operation failed: deleting output file: /tmp/$filename.decrypted
2021-03-02 11:56:02,305 - MainThread - aws_encryption_sdk_cli - DEBUG - Encountered unexpected error: increase verbosity to see details.
ParamValidationError(&quot;Parameter validation failed:
Unknown parameter in input: &quot;KeyId&quot;, must be one of: CiphertextBlob, EncryptionContext, GrantTokens&quot;)
2021-03-02 11:56:02,305 - MainThread - aws_encryption_sdk_cli - DEBUG - Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk_cli/__init__.py&quot;, line 283, in cli
    process_cli_request(stream_args, args)
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk_cli/__init__.py&quot;, line 222, in process_cli_request
    handler.process_single_file(stream_args=stream_args, source=_source, destination=_destination)
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk_cli/internal/io_handling.py&quot;, line 343, in process_single_file
    stream_args=_stream_args, source=source_reader, destination=destination
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk_cli/internal/io_handling.py&quot;, line 275, in process_single_operation
    stream_args=stream_args, source=cast(IO, source), destination_writer=destination_writer
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk_cli/internal/io_handling.py&quot;, line 216, in _single_io_write
    header=json_ready_header(handler.header),
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/streaming_client.py&quot;, line 204, in header
    self._prep_message()
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/streaming_client.py&quot;, line 774, in _prep_message
    self._header, self.header_auth = self._read_header()
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/streaming_client.py&quot;, line 810, in _read_header
    decryption_materials = self.config.materials_manager.decrypt_materials(request=decrypt_materials_request)
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/materials_managers/default.py&quot;, line 153, in decrypt_materials
    encryption_context=request.encryption_context,
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/key_providers/base.py&quot;, line 280, in decrypt_data_key_from_list
    data_key = self.decrypt_data_key(encrypted_data_key, algorithm, encryption_context)
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/key_providers/base.py&quot;, line 252, in decrypt_data_key
    data_key = master_key.decrypt_data_key(encrypted_data_key, algorithm, encryption_context)
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/key_providers/base.py&quot;, line 489, in decrypt_data_key
    encrypted_data_key=encrypted_data_key, algorithm=algorithm, encryption_context=encryption_context
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/key_providers/kms.py&quot;, line 458, in _decrypt_data_key
    response = self.config.client.decrypt(**kms_params)
  File &quot;/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/key_providers/kms.py&quot;, line 159, in _wrap_client
    return method(*args, **kwargs)
  File &quot;/var/lib/awx/venv/ansible/lib/python3.6/site-packages/botocore/client.py&quot;, line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File &quot;/var/lib/awx/venv/ansible/lib/python3.6/site-packages/botocore/client.py&quot;, line 634, in _make_api_call
    api_params, operation_model, context=request_context)
  File &quot;/var/lib/awx/venv/ansible/lib/python3.6/site-packages/botocore/client.py&quot;, line 682, in _convert_to_request_dict
    api_params, operation_model)
  File &quot;/var/lib/awx/venv/ansible/lib/python3.6/site-packages/botocore/validate.py&quot;, line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: &quot;KeyId&quot;, must be one of: CiphertextBlob, EncryptionContext, GrantTokens

Encountered unexpected error: increase verbosity to see details.
ParamValidationError(&quot;Parameter validation failed:
Unknown parameter in input: &quot;KeyId&quot;, must be one of: CiphertextBlob, EncryptionContext, GrantTokens&quot;)

##### ADDITIONAL INFORMATION

The above tasks are failing only through AWX as they are working as expected through terminal execution or terminal playbook execution

**Comment by john-westcott-iv** [comment]
Thanks for bring this up. With the introduction of Execution Environments you should now be able to customize whatever version of libraries you want ansible to run with. Please reach out to us on the mailing list or Matrix if you need help setting up an Execution Environment.
