### ISSUE TITLE
SCM Branch missing Job Details

### ISSUE THREAD

**Issue by sangdrax8** [ansible/awx#9445]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The SCM Branch does not show up in job Details.  As branches can be overridden as a selection when launching a template, being able to confirm the branch is important to understanding  a job.

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.17
* Operating System: Windows 10
* Web Browser: Chrome

##### STEPS TO REPRODUCE

View any job's Details tab.

##### EXPECTED RESULTS

SCM Branch field displayed in details.

##### ACTUAL RESULTS

SCM Branch is missing.

**Comment by unlikelyzero** [comment]
@sangdrax8 thanks for filing this issue, we're tracking this functionality in this issue here: #8788

Please subscribe to the updates to see when it lands in the next available release!
