### ISSUE TITLE
SCM Branch missing from Template Edits

### ISSUE THREAD

**Issue by sangdrax8** [ansible/awx#9446]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
SCM Branch only available when creating a template.  After selecting a project for a template, the SCM Branch option will be available, as well as the check box for allowing override.  Once saved, the Source Control Branch shows up but is missing the "Prompt on Launch) indication.  When the job is edited, the SCM filed is missing completely from the edit.  The only work around is to change the project, at which point the SCM field is provided again and can be edited.

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.17
* Operating System: Windows 10
* Web Browser: Chrome

##### STEPS TO REPRODUCE

* Create a SCM project and allow branch override
* Create a template from the above project, and save it
* Edit the project, and the SCM branch options are missing
* 

##### EXPECTED RESULTS

When editing the template, SCM branch should always be available to be edited like other settings.

##### ACTUAL RESULTS

SCM Branch is not available with out changing the project.

**Comment by unlikelyzero** [comment]
@sangdrax8  thanks for filing this issue, we're tracking this functionality in this issue here: #8788 

Please subscribe to the updates to see when it lands in the next available release!
