### ISSUE TITLE
Execution Environments - Activity Stream

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#9448]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Clicking on the right top button for Execution Environment Activity Stream the option displayed on select component, isn't following the actual pattern (sub items)

##### STEPS TO REPRODUCE

1. Click on Activity stream button
2. Open the Activity Stream type select

##### EXPECTED RESULTS

The item Execution Environment should be present inside of `Administration`

##### ACTUAL RESULTS

Not displayed

##### ADDITIONAL INFORMATION

![ee-as](https://user-images.githubusercontent.com/12464858/109661817-23e56f80-7b49-11eb-8326-a4e6d835eabb.gif)

**Comment by nixocio** [comment]
This work has not been done yet - https://github.com/ansible/awx/issues/9308

**Comment by tiagodread** [comment]
@nixocio sorry for the confusion, closing this as a duple
