### ISSUE TITLE
Unable to run project update: `No module named websocket`

### ISSUE THREAD

**Issue by jladdjr** [ansible/awx#945]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
On the current network visualization branch (network_ui_3_3), running a project update fails with `No module named websocket`.

##### ENVIRONMENT
* AWX version: 1.0.2-596-g6f9d0b7
* AWX install method: docker for mac
* Ansible version:  2.4.2.0
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. After deploying the container (from branch `network_ui_3_3`), use `awx-manage create_preload_data` to load the Demo Inventory, Project and Job Template.
2. Open the Tower UI, and run an update for the Demo Project

##### EXPECTED RESULTS

Update is successful.

##### ACTUAL RESULTS

Project update fails. The update's stdout shows:
`ERROR! Unexpected Exception, this is probably a bug: No module named websocket`

##### ADDITIONAL INFORMATION

Workaround:
```
docker exec -it tools_awx_1 bash
. /venv/ansible/bin/activate
pip install websocket-client==0.44.0
```

Seems like the new dependency may have been introduced by:
https://github.com/ansible/awx/blob/network_ui_3_3/awx/plugins/callback/network_ui.py#L22

**Comment by benthomasson** [comment]
I'd like to see this reproduced in another development environment.   I a few more data points to determine if this is a problem with docker reusing old containers or a problem with the building of the containers.

**Comment by benthomasson** [comment]
The network_ui callback plugin will be replaced at some point with fact processing code that uses the normal method of pushing facts to Tower instead of using a websocket.

**Comment by benthomasson** [comment]
> Seems like the new dependency may have been introduced by:
https://github.com/ansible/awx/blob/network_ui_3_3/awx/plugins/callback/network_ui.py#L22

This dependency was already in Tower added by `97846337 (Ryan Petrello    2017-07-17 11:59:37 -0400 189) websocket-client==0.44.0  # via slackclient`

**Comment by benthomasson** [comment]
Removed the websocket dependency from the ansible venv.
