### ISSUE TITLE
Login using PassFF plugin, AWX reveals password in URL

### ISSUE THREAD

**Issue by mem-** [ansible/awx#9463]
I use "pass" (http://www.passwordstore.org/) as password manager together with the PassFF plugin in Firefox (https://github.com/passff/passff). When PassFF fills the login form I'm "redirected" with both username and password in the URL and not logged in to AWX. If I manually cut'n'paste my password I get in, so my password is correct.

Except the inconvenience to not get in, the main bug is that the URL with my password is stored in the browser's URL history and has to be clean out manually.

AWX 14.1.0
Ansible 2.9.11
Firefox 78.8.0ers (Debian Buster)

Regards,
// mem-

![AWX-login](https://user-images.githubusercontent.com/7677703/109777138-ab8fb480-7c03-11eb-9c54-1db3d585bcff.png)

**Comment by wenottingham** [comment]
The only way you'd be redirected is if the plugin is passing that as form items; the application is passing the form items that's passed to it.

You'd have to figure out what's going on in PassFF that's causing it to try and send the login info as form parameters that way.

**Comment by mem-** [comment]
I have 200+ passwords in "pass"/PassFF. AWX is the first and only site acted in this way. If PassFF had problems handling login forms the problem should show up on other sites, too.

I will file a bug report for pass/PassFF but I doubt that it is a PassFF problem.

**Comment by wenottingham** [comment]
I would also note that AWX 14.1 is an older version, and the UI has been entirely replaced since then. You may want to try on 17.x.
