### ISSUE TITLE
Updated Locators Needed: Teams Access Tab- Add Teams Modal

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#9470]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When reviewing coverage and adding stubs for the Teams Access tab, and checking to see if I would have the locators I need- I notice that the Add User/Team modal is missing some critical locators for me to be able to add coverage later. Please add these locators, thank you!

##### ENVIRONMENT
* AWX version: Devel 3/3/21

**Comment by tiagodread** [comment]
Closing to keep track on https://github.com/ansible/awx/issues/10241
