### ISSUE TITLE
awx.main.utils.common.get_ansible_version breaks with ansible-core

### ISSUE THREAD

**Issue by elyezer** [ansible/awx#9472]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

The `awx.main.utils.common.get_ansible_version` helper breaks with new `ansible --version` when ansible-core is installed. This also changes the format the `api/v2/config` returns for the `ansible_version` field. What breaks tools that relies on this field to check the current ansible version used by AWX.

##### ENVIRONMENT
* AWX version: devel
* AWX install method: vm
* Ansible version:  ansible-core 2.11
* Operating System: RHEL8.3
* Web Browser:

##### STEPS TO REPRODUCE

Install AWX with ansible-core and perform a GET request to `/api/v2/config` and check the `ansible_version` field format.

##### EXPECTED RESULTS

The ansible version format should be something like `X.Y.Z` (format capable to be parsed by tools like `distutils.version.LooseVersion`)

##### ACTUAL RESULTS

Returning something like `"ansible_version": "[core 2.11.0.dev0]"`

##### ADDITIONAL INFORMATION

Output of `ansible --version` for ansible-core 2.11:

```console
$ ansible --version
ansible [core 2.11.0b1]
  config file = /home/elyezer/code/ansible/ansible-core/ansible.cfg
  configured module search path = ['/home/elyezer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/elyezer/.virtualenvs/ansible-core/lib/python3.9/site-packages/ansible
  ansible collection location = /home/elyezer/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/elyezer/.virtualenvs/ansible-core/bin/ansible
  python version = 3.9.0 (default, Oct  6 2020, 00:00:00) [GCC 10.2.1 20200826 (Red Hat 10.2.1-3)]
  jinja version = 2.11.3
  libyaml = True
```

For ansible 2.9:

```
ansible 2.9.16
  config file = /home/elyezer/code/ansible/ansible/ansible.cfg
  configured module search path = ['/home/elyezer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/elyezer/.virtualenvs/ansible/lib/python3.9/site-packages/ansible
  executable location = /home/elyezer/.virtualenvs/ansible/bin/ansible
  python version = 3.9.0 (default, Oct  6 2020, 00:00:00) [GCC 10.2.1 20200826 (Red Hat 10.2.1-3)]
```

**Comment by ryanpetrello** [comment]
@elyezer I think we should be able to close this once https://github.com/ansible/awx/pull/9697/ merges.

**Comment by kdelee** [comment]
Closing as obsoleted by https://github.com/ansible/awx/pull/9697
