### ISSUE TITLE
Specifying nodeselector during installation

### ISSUE THREAD

**Issue by CatchKarthik** [ansible/awx#9475]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

While trying to install Ansible AWX in kubernetes, I am trying to specify the node_selector variable in the below format

`node_selector="purpose: awx"`

I am getting the below error while installing
`
stderr": "error: error validating \"STDIN\": error validating data: ValidationError(Deployment.spec.template.spec.nodeSelector): invalid type for io.k8s.api.core.v1.PodSpec.nodeSelector: got \"string\", expected \"map\"; if you choose to ignore these errors, turn validation off with --validate=false", "stderr_lines": ["error: error validating \"STDIN\": error validating data: ValidationError(Deployment.spec.template.spec.nodeSelector): invalid type for io.k8s.api.core.v1.PodSpec.nodeSelector: got \"string\", expected \"map\"; if you choose to ignore these errors, turn validation off with --validate=false"], "stdout": "serviceaccount/awx unchanged", "stdout_lines": ["serviceaccount/awx unchanged"]}​​​​​​​​`

I see that the ansible resolves the parameter passed in the below format

```
nodeSelector:
        'purpose: ansible-cicd'
```

Because it is adding quotes to the key value passed, it is considering it as string instead of map.

Please let me know if I am passing the parameter wrong.

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: kubernetes
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

In the inventory.yaml, try adding the below parameter and do the installation in kubernetes

`node_selector="purpose: awx"`

##### EXPECTED RESULTS

Ansible should consider the value passed as map instead of string.

##### ACTUAL RESULTS

installation fails with the below error

`
stderr": "error: error validating \"STDIN\": error validating data: ValidationError(Deployment.spec.template.spec.nodeSelector): invalid type for io.k8s.api.core.v1.PodSpec.nodeSelector: got \"string\", expected \"map\"; if you choose to ignore these errors, turn validation off with --validate=false", "stderr_lines": ["error: error validating \"STDIN\": error validating data: ValidationError(Deployment.spec.template.spec.nodeSelector): invalid type for io.k8s.api.core.v1.PodSpec.nodeSelector: got \"string\", expected \"map\"; if you choose to ignore these errors, turn validation off with --validate=false"], "stdout": "serviceaccount/awx unchanged", "stdout_lines": ["serviceaccount/awx unchanged"]}​​​​​​​​`

**Comment by blomquisg** [comment]
@shanemcd does this look like a bug?  Or, just passing in a badly formatted parameter?  And, does this change with the operator?

**Comment by ryanpetrello** [comment]
Hey @CatchKarthik,

The current K8S installer is going to be removed very soon in favor of https://github.com/ansible/awx-operator.  When AWX is released (soon), could you give this a whirl over there and report back?  Thanks.
