### ISSUE TITLE
Upgrade AWX

### ISSUE THREAD

**Issue by dburns-vistra** [ansible/awx#9476]
##### ISSUE TYPE
 - AWX upgrade documentation

##### SUMMARY
In the last version I updated to excluding 17.0.1, the install doc had a straight forward upgrade section.  Is this intention not to update?  Also I was able to use a file called vars.yml preceeded by and @ sign, when I tried it on 17.0.1, I got an error message, so I made sure that the inventory file had all the entries that were suggested to have in the vars.yml file.

**Comment by ryanpetrello** [comment]
Hey @dburns-vistra,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by dburns-vistra** [comment]
This is not a support issue.  Here on this site, it points to a place in the documents about upgrades.. https://www.ansible.com/products/awx-project/faq and says this...To migrate between different instances of AWX, please follow the instructions at https://github.com/ansible/awx/blob/devel/DATA_MIGRATION.md.  Which then following the links it says this... Users who wish to upgrade modern AWX installations should follow the instructions at:

https://github.com/ansible/awx/blob/devel/INSTALL.md#upgrading-from-previous-versions 
I'm suggesting that the documents should have the section back.  Your the one that updated this in January 2020.  That is all.  My company's IT and I are big on documentation, so I do have detailed docs on upgrade for us.  I just like to check every upgrade to make sure things have not changed.

**Comment by ryanpetrello** [comment]
@rooftopcellist,

Can you add back in a short blurb like this one:

https://github.com/ansible/awx/blob/17.0.1/INSTALL.md#upgrading-from-previous-versions

...specific to the process for upgrading?  It looks like this was accidentally removed as part of https://github.com/ansible/awx/commit/9672e7283404f608abcf9f2a1489db7867d672a4

**Comment by dburns-vistra** [comment]
Thank you... I don't want to be a pain.

**Comment by dburns-vistra** [comment]
Thank you.  Given that will come back into the documents, why did the command:
ansible-playbook -i inventory install.yml -e @vars.yml - the @vars.yml not work?  Do I need to open a new issue?

**Comment by ryanpetrello** [comment]
@dburns-vistra we're changing the way the docker-compose based installation works in the next major version of AWX.

https://groups.google.com/g/awx-project/c/47MjWSUQaOc/m/bCjSDn0eBQAJ

...but this isn't released yet.  If you're deploying/upgrading to the unstable `devel` build, there's instructions here, but we haven't announced this and fully finished documenting it yet (which is why details are sparse):

https://github.com/ansible/awx/tree/devel/tools/docker-compose
https://github.com/ansible/awx/blob/devel/tools/docker-compose/docs/data_migration.md

Additionally, in the near future, we're moving K8S-based deployment to use an operator, which lives here:

https://github.com/ansible/awx-operator

Similarly, this is still in-flight, and we haven't released it yet, so you'll find that the `devel` branches of these repositories are unstable and light on documentation.

If you want a stable release, stick with the latest stable tag:

https://github.com/ansible/awx/tree/17.0.1

**Comment by dburns-vistra** [comment]
No, I am only moving up to the stable releases.  My company went with Chef open-source in 2017, since they changed their charging model, we are moving to Ansible AWX.  I was in the group that went with Chef in 2017, I was moved out of the group to work on ServiceNow and JavaScript, I came back to a different infrastructure group, however, they are giving me all of the "CI/CD" or "Devops" tools and I am building out the Ansible Config Mgmt stuff.  Thus, I am trying to mimic what we did with Chef in pipelines for linting and testing Chef thus my other enhancement request.  I will probably be posting more about enhancements since we are using in DEV/Non-PROD and PROD.  The sector my company is in, is low-margin, so any corners we can cut we do.  I would be happy to contribute to the project where I can.

**Comment by rooftopcellist** [comment]
Hi @dburns-vistra if you are wanting to use stable releases, the docs for that specific release will be more useful to you.  In this case, the 17.0.1 install docs can be found here: https://github.com/ansible/awx/blob/17.0.1/INSTALL.md

As @ryanpetrello mentioned, there are currently major changes to the installation paths underway.  Specifically, the k8s/openshift install playbooks will use an operator to deploy AWX instead.

**Comment by dburns-vistra** [comment]
Oh, I get it, I am just doing a web search for Ansible AWX so it takes me to https://github.com/ansible/awx, which is showing the dev branch, but I am doing the git pull from here:   "and clone the latest stable release, e.g.,

git clone -b x.y.z https://github.com/ansible/awx.git" which is stable.  So I need to read the docs in the same location.  So in the dev branch the upgrade is gone, in the stable it is still there.  I'm Sorry.  The @VARS.YAML still did not work.

**Comment by ryanpetrello** [comment]
Hey @dburns-vistra,

We've just revamped the `devel` install instructions to reflect these upcoming changes (https://github.com/ansible/awx/pull/9490), and I've also added a note hopefully point people in the right direction for current stable releases:

https://github.com/ansible/awx/pull/9494

Thanks for the feedback!
