### ISSUE TITLE
AWX Project using SCM, limit to a specific branch name

### ISSUE THREAD

**Issue by dburns-vistra** [ansible/awx#9477]
##### ISSUE TYPE
 - Feature Idea - Limit AWX Project to use a specific branch name

##### SUMMARY
I have Ansible AWX in both DEV (non-PROD) and PROD.  I am building a pipeline to mimic a previous configuration mgmt tool.  It has a concept of housing config "playbooks" on the server and supermarket.  With that, only code that passes the pipeline is promoted to PROD.  With Ansible AWX, using the SCM directly, I only want code to be used in our AWX DEV that is in the "development" branch and for AWX PROD, only code that has passed the pipeline linting and other checks to be used in MASTER, therefore, the AWX PROD would be limited to using MASTER.  Only like SuperUsers could change the Branch name to something else.  Make sense?  This is like feature #282 that I found, that was not approved to go forward.

**Comment by wenottingham** [comment]
This isn't something we'd really add to have a sysadmin-only field on the project. The way we'd recommend this is to just set the value on the project branch/tag/rev field, and ensure that only the proper people have access to that project via RBAC.
