### ISSUE TITLE
Job Template loads twice if autopopulate is triggered

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#9479]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Job Template loads twice if the project auto populate is triggered. 

Right now, if there is just one project available - the auto populate will be triggered on the the Job Template Add screen, and the page will load twice.

This issue is being sorted out.

**Comment by unlikelyzero** [comment]
Note: this is showing up in the visual tests

**Comment by tiagodread** [comment]
Verified manually and all e2e tests are green
