### ISSUE TITLE
13 or more custom credential types breaks template job

### ISSUE THREAD

**Issue by ColmMcBarron** [ansible/awx#948]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
If an installation has 13 or more custom credential types, the job template UI is broken.

And when I mean broken, there are no credentials in the box, and you can't add/remove any. This applies to any existing templates.

If you click on the search icon for the credentials field you get another error.

##### ENVIRONMENT
* AWX version: 1.0.2.315
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: Windows 7 Enterprise
* Web Browser: Chrome

##### STEPS TO REPRODUCE

> Add 12 new credential types
> Open existing template
> Credentials are present in UI
> Add 1 more additional credential type
> Credentials are not present in UI

##### EXPECTED RESULTS

Credentials would be present

##### ACTUAL RESULTS

Credentials are not present in UI

##### ADDITIONAL INFORMATION

There is also a javascript console error, which is likely the root cause of it not displaying.

**Comment by jakemcdermott** [comment]
👋 
This should be resolved by https://github.com/ansible/awx/pull/1044
