### ISSUE TITLE
Job template form being loaded twice

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#9484]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Job template form is now being loaded twice because of extra requests

##### ENVIRONMENT
Devel https://github.com/ansible/awx/commit/eb131f64ccdf3fb5750528ef41cc8941efba5118

##### STEPS TO REPRODUCE

1. Navigate to job template form
2. change the network throttling to fast 3g 
3. refresh the page

##### EXPECTED RESULTS

The page should be displayed after xhr requests and loading spinner disappeared 

##### ACTUAL RESULTS

![jt](https://user-images.githubusercontent.com/12464858/110004445-32bd5500-7cf6-11eb-8282-179c9fd11538.gif)

**Comment by nixocio** [comment]
Closing this one as duplicated. See https://github.com/ansible/awx/issues/9479
