### ISSUE TITLE
Job template form - Project field validation

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#9485]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After selecting a project, another request is made to fetch EE information but the error `Select a value for this field` still being displayed and only disappear when filling in another field

##### ENVIRONMENT
Devel https://github.com/ansible/awx/commit/eb131f64ccdf3fb5750528ef41cc8941efba5118

##### STEPS TO REPRODUCE

1. Navigate to Job template form
2. Select a project

##### EXPECTED RESULTS

No field error message

##### ACTUAL RESULTS

The message was displayed after selecting a project

##### ADDITIONAL INFORMATION

![jt1](https://user-images.githubusercontent.com/12464858/110006155-102c3b80-7cf8-11eb-8375-37fbb98def85.gif)

**Comment by nixocio** [comment]
This is probably related to https://github.com/ansible/awx/issues/9479
