### ISSUE TITLE
EE can not be disassociated from a Job template

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#9487]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

The user can not remove an Execution Environment from the Job template
##### ENVIRONMENT
Devel

##### STEPS TO REPRODUCE

1. Create an Execution Environment
2. Create a JT using this EE
3. Edit the JT to remove the EE

##### EXPECTED RESULTS

The EE to be removed from the JT

##### ACTUAL RESULTS

The JT still have the EE associated  
##### ADDITIONAL INFORMATION

![jt2](https://user-images.githubusercontent.com/12464858/110033828-a5d7c300-7d18-11eb-8210-c6e09ae11555.gif)

**Comment by nixocio** [comment]
Same issue was also present on WFJT, and addressed as part of this issue.

**Comment by tiagodread** [comment]
Fixed
