### ISSUE TITLE
Git SCM Update sometimes hungs

### ISSUE THREAD

**Issue by shortsteps** [ansible/awx#949]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Git SCM Update sometimes hungs with no apparent reason and get stuck in running.

##### ENVIRONMENT
- AWX version: 1.0.2.327
- AWX install method: docker on linux
- Ansible version: 2.4.2.0
- Operating System: Centos 7
- Web Browser: Chrome/Firefox on Ubuntu

##### STEPS TO REPRODUCE
Launch SCM Update on a Project (both manually, or scheduled, or invoked by a job with 'Update on launch' option).

##### EXPECTED RESULTS
The job ends (success/failure).

##### ACTUAL RESULTS
The job stays in running state.
I then cancel it, and one of the following situation happens:
- sometimes rerun it some minutes/hours later helps
- sometimes if I run a different job/project update and I rerun the hunging one, it completes
- sometimes I have to restart all containers or reboot the whole server to get it work.

##### ADDITIONAL INFORMATION
There is no a precise scheme.
While hunging:
- Git server is reacheable
- AWX host resources seem ok (ram, disk, I/O, ..)
- No specific errors in UI o awx_task logs 
- Job standard out:

```
Using /etc/ansible/ansible.cfg as config file

PLAY [all] *********************************************************************


TASK [delete project directory before update] **********************************
skipping: [localhost]

TASK [check repo using git] ****************************************************
skipping: [localhost]

TASK [update project using git] ************************************************
```

Did anybody experience the same?

**Comment by cchurch** [comment]
Are you using SSH or HTTPS, and is your git URL to github or another git server?

You can define a custom setting, `PROJECT_UPDATE_VVV=True` in a Python settings file, restart AWX, and try the project update again. This should run the project update with additional verbosity, which may also help to determine why it's hanging.

**Comment by shortsteps** [comment]
I'm using https and my url is to the company GitLab server.

Where should I put the Python setting file?
Additional verbosity could help, since it is very odd and intermittent.

**Comment by shortsteps** [comment]
I upgraded to 1.0.2.72 to fix other issues and this behaviour seems to be disappeared. Maybe it was something hidden and related to older versions.
