### ISSUE TITLE
Updated Locators on Job Output Tab

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#9495]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When reviewing coverage and adding stubs for the Job Output tab, and checking to see if I would have the locators I need- I notice that the Relaunch, Download, Delete, and Cancel buttons are missing some critical locators for me to be able to add coverage later. Please add these locators, thank you!

##### ENVIRONMENT
* AWX version: Devel 3/5/21

![image](https://user-images.githubusercontent.com/63685497/110148627-0ca5bc80-7dab-11eb-882b-e4f16bd3f690.png)

**Comment by mabashian** [comment]
See https://github.com/ansible/awx/pull/9208#issuecomment-802183668.  This can be closed when #9208 gets merged.

**Comment by akus062381** [comment]
all set
