### ISSUE TITLE
Fresh install "awx-admin-password" not found

### ISSUE THREAD

**Issue by vperilla** [ansible/awx#9501]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Hey community,

I have followed the install documentation, with success, but when I run this command:
minikube kubectl -- get secret awx-admin-password -o jsonpath='{.data.password}' | base64 --decode

I get this error:
Error from server (NotFound): secrets "awx-admin-password" not found

For that reason I can't login on AWX web interface,  have looked on kubectl secrets and there isn't that secret.
I think the installation instructions should be updated.

##### ENVIRONMENT
* AWX install method: minikube on linux 
* Operating System: Archlinux

##### STEPS TO REPRODUCE
Follow install steps described on documentation

**Comment by shanemcd** [comment]
H @vperilla. We haven't yet published a version of the operator that works with the upcoming version of AWX. 

The devel branch is currently going through a period of instability. Please use the latest tagged release.

These docs will work by the time AWX 18 is released.

**Comment by phemmer** [comment]
So AWX 18 is released and this is still an issue.

I tried deploying with quay.io/ansible/awx:18.0.0 and https://github.com/ansible/awx-operator/blob/693ce5a17ecb44c00264cea66922c5621ec1592e/deploy/awx-operator.yaml and I still get:

```
kubectl get secret awx-admin-password -o jsonpath='{.data.password}' | base64 --decode
Error from server (NotFound): secrets "awx-admin-password" not found
```

And the container is fully up and loading in the browser.

**Comment by MattW42** [comment]
I had the same issue as above.
Try specifying the namespace in the command.
In my case, I used "awx" as the installed namespace, and this command worked to get the secret.

`kubectl get secret --namespace awx awx-admin-password -o jsonpath="{.data.password}" | base64 --decode`

By default kubectl is looking in the 'default' namespace. 
If your AWX install is in a different namespace you'll need to specify that in the command.

Works the same as `kubectl get pods -A` for all namespaces or `kubectl get pods --namespace awx` for only those in the AWX namespace.

**Comment by atalz163** [comment]
> --namespace awx

Hi! thanks for sharing this answer. i am getting "mysuperlongpassword" which is not decoded. i dont know where exactly i am doing wrong.

**Comment by rmitura** [comment]
in my case running 
`kubectl get secret --namespace=awx`
returned list of names to choose from.
The object I should query for password is **awx-demo-admin-password** as in:
`kubectl get secret -n awx  awx-demo-admin-password -o jsonpath="{.data.password}" | base64 --decode`

**Comment by MattW42** [comment]
There is another way to get this info.. 
Install  Portainer onto your microk8s/docker etc installation.
This will then show you the all of the info under the menu option 'ConfigMaps & Secrets'

Attached images from my test/dev build.

![image](https://user-images.githubusercontent.com/61036788/205236871-06fa6674-b37c-4994-bcaf-25e1b597aebd.png)

![image](https://user-images.githubusercontent.com/61036788/205236949-e3afb784-7158-4783-8dc9-d61cfd6f71e7.png)

![image](https://user-images.githubusercontent.com/61036788/205237109-672575f9-8337-44d6-9dfe-fc8e48153e36.png)

You can also use Portainer (Helm) to install the awx operator.
