### ISSUE TITLE
Update locators on the Dashboard

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#9502]
##### ISSUE TYPE
 - Task
 
##### SUMMARY
The tables and tabs on the Dashboard view need to be updated with new locators.

<img width="1190" alt="Screen Shot 2021-03-06 at 10 43 19 AM" src="https://user-images.githubusercontent.com/12446869/110212308-c9118800-7e68-11eb-9900-38b4b6721a69.png">

**Comment by tiagodread** [comment]
Closing to keep track on https://github.com/ansible/awx/issues/10241
