### ISSUE TITLE
Update awx-manage inventory_import to use an Execution Environment

### ISSUE THREAD

**Issue by shanemcd** [ansible/awx#9504]
This is one of the things we missed in https://github.com/ansible/awx/pull/8030.

I originally thought this was going to be easy to resolve, but I was wrong.

My first intuition was to use ansible-runner's ability to execute arbitrary commands. There are multiple problems with this idea:

- Ansible Runner [sends stderr to stdout](https://github.com/ansible/ansible-runner/issues/96)
  - We parse json returned by `ansible-inventory`. By default, Ansible sends all verbose output to stdout. We use [`ANSIBLE_VERBOSE_TO_STDERR`](https://github.com/ansible/awx/blob/devel/awx/main/constants.py#L29) to get around this.
- Ansible Runner invokes `ansible-inventory` (either locally or via podman)
  - `ansible-inventory` is no longer installed directly on the control plan.
- We could call `podman run` directly, but this would only work on VM based installations.

The next thought-hop might be to consider using Receptor for this. This is not currently possible because we did not build the new `transmit` / `worker` / `process` code with the use case in mind where we point `ansible-inventory` to a file / directory provided by the user.

These are the options I have been able to identify, in order of my preference:

- Remove `ansible-manage inventory_import` completely.
- Update `ansible-manage inventory_import` to call `ansible-inventory` via `podman`. This would only work on VM-based installations.
- Explore what would be needed to support submitting this as a task via Receptor.

**Comment by shanemcd** [comment]
Ping @wenottingham @ryanpetrello

**Comment by shanemcd** [comment]
Option 2 has been implemented in https://github.com/ansible/awx/pull/9505

**Comment by wenottingham** [comment]
> Update ansible-manage inventory_import to call ansible-inventory via podman. This would only work on VM-based installations.

Assuming that it worked (as you said, it doesn't), is there a coherent way to get into the pod to run `awx-manage inventory_import` on K8S-based installs to begin with?

**Comment by ryanpetrello** [comment]
Yea, I think option #2 makes the most sense.  I don't know the full history of `awx-manage inventory_import` or how we've communicated its usage to customers (it **is** referenced as a supported thing in multiple locations in our docs), but I could see making an argument that this is an a-la-carte type of thing that people run by ssh'ing into a VM and manually doing it.

**Comment by kdelee** [comment]
This is working now! Closing. thanks
