### ISSUE TITLE
Template search not working as expected

### ISSUE THREAD

**Issue by hs-hub-world** [ansible/awx#9507]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When searching for templates with an underscore (i.e. _validate) we are also seeing the ones that do not start with an underscore.
![image](https://user-images.githubusercontent.com/20629911/110222233-9fb32500-7e85-11eb-86ee-1c9a4a3c647d.png)

##### ENVIRONMENT
![image](https://user-images.githubusercontent.com/20629911/110222165-2a475480-7e85-11eb-8ef9-1f6275436148.png)

**Comment by unlikelyzero** [comment]
@hs-hub-world this is fixed in the latest version of AWX (17.0.1). Please give it a shot!
