### ISSUE TITLE
[ui_next] Possible to create a JT without selecting a playbook

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#9508]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Possible to create a JT without selecting a playbook and leaves Add Form in a corrupted sate

##### ENVIRONMENT
* AWX version: devel 3/6/21

##### STEPS TO REPRODUCE
1. Create a JT by selecting the minimum required fields _except_ Playbook Select
2. Save button
Note: JT created without Playbook

##### EXPECTED RESULTS
1. No JT Created without required fields

##### ACTUAL RESULTS
1. Playbook create without required fields.
2. Once in this state, it's not possible to fix the form errors without changing the name of the new JT. (Because one was technically created)

##### ADDITIONAL INFORMATION

https://user-images.githubusercontent.com/12446869/110224171-5b388100-7ea7-11eb-8d11-ee0274d4ff66.mp4

**Comment by mabashian** [comment]
I just tested this out and am no longer able to reproduce this.  We now show an error under the playbook field saying that one must be selected.

**Comment by tiagodread** [comment]
I also tried to reproduce this bug without success, this is not happening anymore.
