### ISSUE TITLE
Inventory sync fails with UnboundLocalError when using NetBox Inventory

### ISSUE THREAD

**Issue by AWegner1** [ansible/awx#9515]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

When using the NetBox inventory plugin, the inventory script fails with an `UnboundLocalError: local variable 'failures' referenced before assignment`
This has been tested with ansible-base 2.10.6, works well in 2.10.5

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on Linux (Debian 10 Buster)
* Ansible version:  2.10.6
* Operating System: Debian 10 Buster
* Web Browser: Firefox 85.0.2

##### STEPS TO REPRODUCE

1. Create an inventory script that retrieves the inventory from a NetBox instance
```
plugin: netbox
api_endpoint: https://net.box.instance/
token: "xxx"
validate_certs: True
config_context: True
interfaces: True
group_by:
  - device_roles
device_query_filters:
  - has_primary_ip: 'true'
```
2. Create an inventory source of type "sourced from project" which points to the inventory file created in step 1
3. Run an inventory sync

##### EXPECTED RESULTS

Hosts get created by the inventory source

##### ACTUAL RESULTS

Retrieval fails with `UnboundLocalError: local variable 'failures' referenced before assignment`
Job-Log is attached

##### ADDITIONAL INFORMATION

Job-Log of the failed job
[inventory_update_44.txt](https://github.com/ansible/awx/files/6100701/inventory_update_44.txt)

**Comment by wenottingham** [comment]
This issue tracker is for tracking feature enhancements and bugs to AWX itself.

This issue looks to be in ansible itself, and needs filed at https://github.com/ansible/ansible.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
