### ISSUE TITLE
FEATURE REQUEST: Run playbook after SCM update

### ISSUE THREAD

**Issue by bjrass** [ansible/awx#952]
- Feature Idea

 - API
 - UI

##### SUMMARY

I have some requirements that needs to be installed for my playbooks to run. These requirements may change depending on SCM updates. It would be nice to be able to run a playbook to do setup after a SCM update has been completed rather than add an extra task, to make sure all dependencies are installed, to all my playbooks.

It also seems to me that this would be very useful if you e.g. have a project with git submodule dependencies.

Something like a top-level requirements.yml playbook would suffice for my purposes.

**Comment by matburt** [comment]
requirements.yml *is* supported for downloading roles/etc: http://docs.ansible.com/ansible-tower/latest/html/userguide/projects.html#ansible-galaxy-support

Is this what you are thinking about?

**Comment by bjrass** [comment]
No. I need to install/update some packages with pip.

**Comment by jakemcdermott** [comment]
Hello bjrass,

If you need an scm update to occur prior to a job template run, you can create a workflow job template with an scm/project update block that occurs before running the job template.

If you have any questions please reach out to our mailing list or stop by our irc channel (`#ansible-awx` on freenode)
