### ISSUE TITLE
Unable to save inventory source form

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#9521]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

When creating an inventory source from project,  I click the "save" button but nothing happens

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Try and create an inventory source

I chose "Sourced from Project"

Fill out required fields and click "Save"

##### EXPECTED RESULTS

Save the inventory source or show me error why it cannot

##### ACTUAL RESULTS

Nothing

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/29239279/110373403-74633e00-801d-11eb-9a82-226cac0f0daf.png)

request :
```
{"credential":null,"inventory":1,"source_script":null,"execution_environment":null,"source_path":"inventories/create_10_hosts.ini/","source_project":9,"custom_virtualenv":"","description":"","name":"inventory2","overwrite":false,"overwrite_vars":false,"source":"scm","source_vars":"---\n","update_cache_timeout":0,"update_on_launch":true,"update_on_project_update":true,"verbosity":1,"enabled_var":"","enabled_value":"","host_filter":""}
```

![image (1)](https://user-images.githubusercontent.com/29239279/110373531-98268400-801d-11eb-9e7a-e111d04bb9c8.png)

Seems like we just need to surface this error, because when we followed the advice of the error message it then worked

**Comment by unlikelyzero** [comment]
@kdelee  thanks for filing this issue, we're tracking this functionality in this issue here: https://github.com/ansible/awx/issues/9373

Please subscribe to the updates to see when it lands in the next available release!
