### ISSUE TITLE
Variables requested via survey always overwrite template defaults

### ISSUE THREAD

**Issue by emulanob** [ansible/awx#9525]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

_This issue was first discussed here: https://groups.google.com/g/awx-project/c/ABjOJ9uKVvY/m/Iw2JuUI5AQAJ_

I'm running AWX 17.0.1, recently upgraded from 15.x.

Now, suppose you have a template whose default extra_vars are
```yaml
foo: bar
username: "{{ awx_user_name }}"
```

Now consider that this template has a survey to read the user's input to the username variable. The survey doesn't have a default value, therefore unless the user types in anything, the value returned by the survey will be an empty variable.

It seems that before version 17.x (didn't test this on 16.x), AWX would preserve the template's default extra_vars value but now I see that the empty string gets sent instead.

As a workaround, I'm setting a default of "{{ awx_user_name }}" to that particular survey.

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.17
* Operating System: Ubuntu 20.04 LTS / macOS 11.2.2 (AWX server / my local)
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Take a template that contains extra variables with default values in them
2. Create an optional survey for that variable
3. Launch the template and don't type anything in the survey's input form

##### EXPECTED RESULTS

The playbook would run using the default value from the template

##### ACTUAL RESULTS

The playbook runs with an empty string as the value for the variable surveyed.

##### ADDITIONAL INFORMATION

Adding a default value to the survey fixes the problem, but in that case, the template's default extra variable is not needed.

**Comment by emulanob** [comment]
Similar behavior reported here https://github.com/ansible/awx/issues/9176#issuecomment-781948806

**Comment by nicosalvadore** [comment]
I reported the same behaviour in [#9176](https://github.com/ansible/awx/issues/9176#issuecomment-781948806), In my case, the default variable is directly in the Ansible project folder in default/main.yml. And this default value is indeed overwritten by the empty value passed via the survey.

**Comment by mabashian** [comment]
I just tried this out in `devel` and wasn't reproducing the overwriting behavior.  Can you try in v20+?  If you're still seeing this behavior please reopen.
