### ISSUE TITLE
Extend Audit Trail For Running Plays On Endpoints

### ISSUE THREAD

**Issue by swatinarvekar** [ansible/awx#9526]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Currently an Activity Stream shows all changes for a particular object. For each change, the Activity Stream shows the time of the event, the user that initiated the event, and the action.

But there is a missing link in an audit trail from the controller to the remote.  No actual audit trail that links the Ansible Job Id with the ssh session ID found in messages/secure log. (E.g. Which ssh session ID executed the job template with the module ansible-ping)

##### Customer Explanation:

We want to operate our RedHatTower Environment running on Openshift 4.6 with PCI security Level. We are struggeling with the log files created in RedHat Tower and the Log File created from the local RedHat Linux Endpoint. There is no ID we can link on Tower Audit Log to Audit Log on Endpoint. Our Feature Request would be to have a ID written in the Endpoint Audit Log during connection from Tower to have a more precise mapping and not only mapping by timestamp for audit reasons.

**Comment by wenottingham** [comment]
This is not something that can be done consistently and reliably. Ansible, as an automation framework, automates different devices through different methods - SSH (not just on Linux, but also on network operating systems such as Cisco IOS), Windows (remote powershell), APIs (talking to Azure or Amazon APIs, or things like Cisco ACI). In most all of these situations, we do not control how the endpoints log and audit local actions, in a way that we can provide that information in the Tower API.

Our recommendation is to ensure that all automation uses an account and credential solely tied to that automation and/or the automation platform; using that, a combination of account tracking and timestamping should be sufficient to correlate in most cases.
