### ISSUE TITLE
Minikube deploy fail to get secret

### ISSUE THREAD

**Issue by rdzielicki** [ansible/awx#9529]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: latest
* AWX install method: MiniKube

##### STEPS TO REPRODUCE
Follow tutorial: https://github.com/ansible/awx/blob/devel/INSTALL.md
minikube kubectl -- get secret awx-admin-password -o jsonpath='{.data.password}' | base64 --decode
Error from server (NotFound): secrets "awx-admin-password" not found

##### EXPECTED RESULTS

Get the secrets

##### ACTUAL RESULTS
probably a mispelled command or a mistake but system says that secret awx-admin-password not found

**Comment by rdzielicki** [comment]
Got weird pods  ( upgrade check)with status failed:

k get pods
NAME                                READY   STATUS      RESTARTS   AGE
awx-5ffbfd489c-g88k2                3/3     Running     0          90m
awx-operator-7c78bfbfd-qnr2g        1/1     Running     12         99m
awx-postgres-0                      1/1     Running     0          91m
gitlab-gitlab-upgrade-check-9nxrh   0/1     Error       0          11m
gitlab-gitlab-upgrade-check-g98jr   0/1     Error       0          10m
gitlab-gitlab-upgrade-check-xb9gl   0/1     Error       0          9m6s
gitlab-shared-secrets-1-wqn-wdvpb   0/1     Completed   0          22m

but able to see the login page

**Comment by rdzielicki** [comment]
also here the secret on the system:

xxxx@awx:~$ k get secrets|grep awx
awx-operator-token-w6khr              kubernetes.io/service-account-token   3      107m
awx-postgres-configuration            Opaque                                5      99m
awx-secret-key                        Opaque                                1      98m
awx-secrets                           Opaque                                2      98m
xxxx@awx:~$ k describe secrets/awx-secrets
Name:         awx-secrets
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
environment_sh:  133 bytes
credentials_py:  445 bytes

**Comment by rdzielicki** [comment]
for i in `k get secret  --no-headers --output=jsonpath={.items..metadata.name}`;do k get secret $i -o yaml;done|grep -i awx-admin-password  --> returns nothing

**Comment by ryanpetrello** [comment]
Hey @rdzielicki,

`devel` is unstable, try the latest released version of AWX:

https://github.com/ansible/awx/releases/tag/17.1.0
https://github.com/ansible/awx/blob/17.1.0/INSTALL.md

An official release of the operator-based deployment is coming soon, but it's not ready yet.

**Comment by ryanpetrello** [comment]
Duplicate of https://github.com/ansible/awx/issues/9501
