### ISSUE TITLE
Auth token header name

### ISSUE THREAD

**Issue by ColmMcBarron** [ansible/awx#953]
##### ISSUE TYPE
 - Bug Report
 - Documentation

##### COMPONENT NAME
 - API

##### SUMMARY
In the tower docs, the header for authentication is referenced as 'Authorization', when in fact this doesn't work and it requires using the header 'X-Auth-Token'

##### ENVIRONMENT
* AWX version: 1.0.2.315
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: n/a
* Web Browser: n/a

##### STEPS TO REPRODUCE

Call an API with the Authorization header (and a valid token)

##### EXPECTED RESULTS

Request should respond appropriately

##### ACTUAL RESULTS

Request responds with an error about credentials

##### ADDITIONAL INFORMATION

Not sure if this is a bug or a documentation issue, i.e. this is the correct header, but docs are out of date, or this is the wrong header and the code should be updated.

**Comment by shanemcd** [comment]
> Request responds with an error about credentials

Can you please tell us the exact error you're seeing?

**Comment by ColmMcBarron** [comment]
Generic api authentication error:

`{
  "detail" : "Authentication credentials were not provided"
}`

**Comment by ryanpetrello** [comment]
I'm having trouble reproducing this, @ColmMcBarron - can you show an example of how you're fetching and using your auth token?

```shell
curl -isk "https://tower.example.org/api/v2/settings/all/" -H "Authorization:Token `curl -sk "https://tower.example.org/api/v2/authtoken/" -H "Content-Type: application/json" -X POST -d '{"username": "admin", "password": "password"}' | grep '"token":' | cut -d '"' -f4`" | head
HTTP/1.1 200 OK
Server: nginx/1.12.2
Date: Wed, 10 Jan 2018 19:12:25 GMT
Content-Type: application/json
Content-Length: 6796
Connection: keep-alive
X-API-Time: 0.076s
X-API-Total-Time: 0.085s
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Content-Language: en
```

**Comment by ColmMcBarron** [comment]
Weird, I can't reproduce this now, closing.
