### ISSUE TITLE
loosen collection version check

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#9532]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
https://github.com/ansible/awx/blob/devel/awx_collection/plugins/module_utils/tower_api.py
```
            if self._COLLECTION_TYPE not in self.collection_to_version or self.collection_to_version[self._COLLECTION_TYPE] != tower_type:
                self.warn("You are using the {0} version of this collection but connecting to {1}".format(
                    self._COLLECTION_TYPE, tower_type
                ))
            elif self._COLLECTION_VERSION != tower_version:
                self.warn("You are running collection version {0} but connecting to tower version {1}".format(
                    self._COLLECTION_VERSION, tower_version
                ))
            self.version_checked = True
```

This is too strict - we should not warn when using 17.0 to connect to 17.1, or in other places where there are sub-minor version updates that do not change the API.

##### ENVIRONMENT
* AWX version: current

**Comment by ryanpetrello** [comment]
cc @beeankha @john-westcott-iv

**Comment by john-westcott-iv** [comment]
@wenottingham can you confirm that API changes will only happen in major versions? Or could the API change from 17.1 to 17.2?

**Comment by wenottingham** [comment]
It shouldn't change from 17.1 to 17.2 if we're following semantic versioning right.

**Comment by kdelee** [comment]
This is well covered in tests inside the collection, closing
https://github.com/ansible/awx/blob/devel/awx_collection/test/awx/test_module_utils.py
