### ISSUE TITLE
[ui_next] Many XHR Network Requests are sent/received when visiting JT Edit Form

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#9534]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Many XHR Network Requests are sent/received when visiting JT Edit Form. At the time of this filing, I count 58. This has been growing over time and would be worth auditing for duplicate or unnecessary requests.

Note: elements are disabled until the response is received from the API

##### ENVIRONMENT
* AWX version: devel 03/09/21

##### ADDITIONAL INFORMATION
It looks like there are several duplicates:
<img width="391" alt="Screen Shot 2021-03-09 at 3 33 14 PM" src="https://user-images.githubusercontent.com/12446869/110534399-05edb100-80ed-11eb-8742-de2f6aec65e2.png">

**Comment by mabashian** [comment]
@keithjgrant checking in - is this one currently in progress?

**Comment by keithjgrant** [comment]
@mabashian Just wrapping up the final Tables PR and I'll be picking this one up after
