### ISSUE TITLE
Cannot Checkout Latest Release (17.1.0)

### ISSUE THREAD

**Issue by gaia** [ansible/awx#9538]
![image](https://user-images.githubusercontent.com/87547/110573994-20398600-8111-11eb-9e83-be9a6c33caab.png)

**Comment by beenje** [comment]
When looking at https://github.com/ansible/awx/commit/9c573abaefd4ea60dddbbc20ab2bd1e18313cc0d (Bump version to 17.1.0), I get this warning:

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

**Comment by ryanpetrello** [comment]
@gaia @beenje mind giving this another whirl?  I've just republished this tag.

**Comment by ryanpetrello** [comment]
```shell
~ git clone -b 17.1.0 git@github.com:ansible/awx.git
~ cd awx
~  tmp-97835d20194f2b6  [yossarian] [tags/17.1.0:] ~/venvs/tmp-97835d20194f2b6/awx git show
commit c1ab815c80cac96508d9779d92bc1280d0347627 (HEAD, tag: 17.1.0)
Author: Ryan Petrello <rpetrell@redhat.com>
Date:   Wed Mar 10 08:53:09 2021 -0500

    Bump version to 17.1.0
```

**Comment by beenje** [comment]
Looks OK now. Thanks!

**Comment by gaia** [comment]
`git pull` didn't do it. had to `git clone -b 17.1.0 git@github.com:ansible/awx.git`

ran the upgrade, help>about still shows 17.0.1

PS: it would be helpful to show version on the login screen.
