### ISSUE TITLE
Can not use custom directory as inventory source

### ISSUE THREAD

**Issue by alexandrovas** [ansible/awx#9539]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Can not choose custom directory as inventory source. In previous versions it was possible.

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Operating System: Ubuntu 18
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Create inventory source
2. Try to input path to inventory directory to **Inventory file** fied

##### EXPECTED RESULTS

Custom path must be accepted by field.

##### ACTUAL RESULTS

A drop-down list of inventory files is displayed.
![image](https://user-images.githubusercontent.com/49055338/110610831-ab615d00-819f-11eb-85e4-d4377598605f.png)

**Comment by AlexSCorey** [comment]
@alexandrovas this issue was resolved with https://github.com/ansible/awx/pull/9120. Feel free to pull down the latest devel branch, or that PR and see if it fixes your issue.
