### ISSUE TITLE
Editing a credential that prompts for password shows ASK in input instead of checking checkbox

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#9541]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
![cred_that_prompts](https://user-images.githubusercontent.com/9889020/110661345-7995c980-8192-11eb-8124-9c8e7cc131e9.gif)

##### STEPS TO REPRODUCE
1. Create a machine credential that prompts for password on launch
2. Go to the edit form for this credential

##### EXPECTED RESULTS
Prompt checkbox to be checked and field disabled

##### ACTUAL RESULTS
Field populated with `ASK`

**Comment by mabashian** [comment]
OK so devel is slightly different now - the checkbox is checked but the input still shows ASK

**Comment by tiagodread** [comment]
Fixed.
