### ISSUE TITLE
Git With Ansible 2.9.6 is Getting error regardless of what we do 

### ISSUE THREAD

**Issue by ITAutomationNLS** [ansible/awx#9543]
##### ISSUE TYPE

 - Bug Report: Git is getting Error! Git is not a valid attribute for a play  
 - Feature Idea
 - Documentation

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY
Using git or ansible.builtin.git, I get the same error that it is not a valid attribute for a play even though I have even copied and pasted examples into the yaml file from the website and it is still giving the same error 

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.9.6
* Operating System: Ubuntu 20.04
* Web Browser: N/A

##### STEPS TO REPRODUCE

---
- name: Git checkout
  git:
   repo: 'https://foosball.example.org/path/to/repo.git'
   dest: /srv/checkout
   version: release-0.22

##### EXPECTED RESULTS

Clone Git Repo (Even though it is fake it should still give me 404 error but doesn't) 

##### ACTUAL RESULTS

ERROR! Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to be in '/home/AnsibleAdmin/project/playbooks/repoclone.yml': line 3, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - name: Git checkout
     git:
        ^ here

##### ADDITIONAL INFORMATION

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html -- Copied Example from Here 
https://docs.ansible.com/ansible/2.9/modules/git_module.html --- Copied Example from here as well 

I have updated the information in for it to do a live repo clone. I have installed all of the modules and base on to this machine and I get the error no matter what I have tried

**Comment by wenottingham** [comment]
This issue tracker is for tracking feature enhancements and bugs to AWX itself, not with Ansible.

This looks like an issue with your playbook in ansible itself.
Try the mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible
https://groups.google.com/forum/#!forum/ansible-project
