### ISSUE TITLE
I can't see the awx / ansible interface

### ISSUE THREAD

**Issue by gpillaca91** [ansible/awx#9546]
##### CONTEXT
install awx on a server with proxies that has ips x.x.x.x
trouble:
-I followed the guide "https://github.com/ansible/awx/blob/devel/INSTALL.md" and it gives me a minikube IP of 200.23.32.5, for example I would expect to be able to enter with 200.23 .32.5: <PORT> from my machine without

##### PROBLEMS

-When the listening ports are ready, the delivery does not appear in the URL, which I get by running 
**"minikube service awx-service --url".**

-I have tried to find if it is my problem to be on a server behind a proxy (but I am connected to my vpn), the problem is that minikube gives me an IP and I would think that it is correct to enter with the IP of the server and some port that is listening.
Based on what I found is that I should expose a pod as a service. I already have it exposed 
**"awx-service       NodePort        x.x.x.x <none>      80: 30150 / TCP 159m",**
however I still can't see the interface on the web.
_I am attentive to your comments._

##### ADDITIONAL INFORMATION
minikube version: v1.18.1

**Comment by ryanpetrello** [comment]
Hey @gpillaca91,

It sounds like you're trying to install from`devel`, which is unstable.  Try the latest released version of AWX:

https://github.com/ansible/awx/releases/tag/17.1.0
https://github.com/ansible/awx/blob/17.1.0/INSTALL.md#clone-the-repo
