### ISSUE TITLE
[db_partitioning] investigate job_event partition migration optimizations

### ISSUE THREAD

**Issue by jladdjr** [ansible/awx#9547]
follow up on some ideas @Ladas and @ryanpetrello discussed that may make the db partition migration more efficient:

![image](https://user-images.githubusercontent.com/4440360/110685662-5ddef300-8193-11eb-8b85-25836d605b62.png)

![image](https://user-images.githubusercontent.com/4440360/110685689-6800f180-8193-11eb-94de-293317a335f1.png)

cc @kdelee @mcharanrm

**Comment by jladdjr** [comment]
common table expressions:
https://www.postgresql.org/docs/12/queries-with.html

**Comment by jladdjr** [comment]
> Also we don't need to do the delete. We can just insert data with marker based pagination (storing last id inserted) and inserting id > stored_id LIMIT 1000000 , then we can omit the costly DELETE and just drop the table in the end

@ryanpetrello trying to grok the ideas from this morning. One of the main ideas I saw mentioned was to wait to delete `_unpartitioned_main_jobevents` until the very end. If we do that, though, then customers will need to be able to temporarily double their storage, right? I thought we said this wasn’t an option at one point, iirc. I'm wondering if we can just assume customers will have that kind of storage on hand.

**Comment by jladdjr** [comment]
The other idea I'm seeing involves various ways to avoid having to do [this](https://github.com/jladdjr/awx/blob/47af250c33cca4f75500ec56de2a616b1f27c317/awx/main/tasks.py#L758):
![image](https://user-images.githubusercontent.com/4440360/110708532-ae644980-81af-11eb-9bf0-ad96110e6aaf.png)

That does seem like something we can do - looking into this.

**Comment by jladdjr** [comment]
Approaches mentioned this morning for not having to retrieve `MAX(id) FROM _old_{tblname}`:

## Approach 1: get last ID from CTE

we can do the insert inside of CTE and just grab the last ID there 
(the RETURNING id for 1M records is also very expensive)

something like (pseudo sql):
```
WITH insert_cte AS (
  INSERT INTO job_events (<cols>) 
    SELECT * FROM non_partitioned_job_events WHERE id < (<last_id>) ORDER BY id DESC LIMIT 1000000
  RETURNING id
)
SELECT MIN(id) FROM insert_cte;
```

Documentation on the use of `RETURNING`:
https://www.postgresql.org/docs/12/dml-returning.html

## Approach 2: Ask new partition for `id`

theoretically we don't need to store the last id at all, since we can just ask the new partition

so:
```
INSERT INTO job_events (<cols>) 
SELECT * FROM non_partitioned_job_events WHERE id < (SELECT MIN(id)
FROM job_events_<the_hardcoded_partition_date>) ORDER BY id DESC LIMIT 1000000
```

then repeat this until the psycopg rowcols return we've inserted something 
(or we can recognize that rowcols < 1M is the last page) and after that we 
can just DROP the `_unpartitioned_job_events` table

The `SELECT MIN(id) FROM job_events_<the_hardcoded_partition_date` inside of a condition of insert that modifies the table might be problematic, so probably having it as separate query or CTE might be better.
^ should be safe if anybody kills it in the middle (the query is a transaction). If anybody kills it it should continue from last inserted batch.

**Comment by jladdjr** [comment]
Suggestion for how to test this in our current scale environment:

> ideally we'll just sign into the DB env and go to PSQL. 
Then we can create more tables like job events and just EXPLAIN ANALYZE the 3 queries 
we used before, vs. 1 or 2 queries like ^ (given the final drop is quick)

> that should give us a nice insight a about a speedup of 1 batch
(we can test this by copying from 1970-01-01 partition directly, since we're deleting from the original table)
(removing the DELETE and RETURNING, I'd expect it should be at least 2-3 times faster -> 
but if we have a slow disk and the insert of new data takes majority of time, it'll be less )

**Comment by jladdjr** [comment]
Getting some datapoints:

cost of our current method of getting the MAX(id):
```
awx=> EXPLAIN ANALYZE select MAX(id) from _unpartitioned_main_jobevent;                                                                                                                               
                                                                                             QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Result  (cost=0.83..0.84 rows=1 width=8) (actual time=2991.615..2991.616 rows=1 loops=1)
   InitPlan 1 (returns $0)
     ->  Limit  (cost=0.58..0.83 rows=1 width=8) (actual time=2991.607..2991.609 rows=1 loops=1)
           ->  Index Only Scan Backward using main_jobevent_pkey1 on _unpartitioned_main_jobevent  (cost=0.58..401107078.18 rows=1597451520 width=8) (actual time=2991.604..2991.604 rows=1 loops=1)
                 Index Cond: (id IS NOT NULL)
                 Heap Fetches: 1000001
 Planning Time: 1181.297 ms
 Execution Time: 2991.665 ms
(8 rows)
```

**Comment by jladdjr** [comment]
Stopped all tower instances so I can poke around the db, copy tables, experiment, etc.

**Comment by jladdjr** [comment]
Getting some datapoints (note: these were executed on a silent db, with tower services shut down)

cost of our current method of getting the MAX(id):

```
awx=> EXPLAIN ANALYZE select MAX(id) from _unpartitioned_main_jobevent;
                                                                                             QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Result  (cost=0.83..0.84 rows=1 width=8) (actual time=2212.774..2212.776 rows=1 loops=1)
   InitPlan 1 (returns $0)
     ->  Limit  (cost=0.58..0.83 rows=1 width=8) (actual time=2212.758..2212.760 rows=1 loops=1)
           ->  Index Only Scan Backward using main_jobevent_pkey1 on _unpartitioned_main_jobevent  (cost=0.58..401107078.18 rows=1597451520 width=8) (actual time=2212.753..2212.753 rows=1 loops=1)
                 Index Cond: (id IS NOT NULL)
                 Heap Fetches: 1000001
 Planning Time: 0.552 ms
 Execution Time: 2212.897 ms
(8 rows)

```

**Comment by jladdjr** [comment]
Creating `test_main_jobevent` table that can we use for measuring cost of inserting rows using different methods we're talking about:

```sql
CREATE TABLE tmp_main_jobevent (LIKE _unpartitioned_main_jobevent INCLUDING ALL);

ALTER TABLE tmp_main_jobevent DROP CONSTRAINT tmp_main_jobevent_pkey;

CREATE TABLE test_main_jobevent (LIKE tmp_main_jobevent INCLUDING ALL, job_created TIMESTAMP WITH TIME ZONE NOT NULL) PARTITION BY RANGE(job_created);
```

**Comment by jladdjr** [comment]
@Ladas @ryanpetrello we’re talking about reducing the cost of `SELECT MAX(id) from _unpartitioned_main_jobevent`, but it looks like that query is only taking three seconds [1]. When I looked at the migrations yesterday, the task manager was running the `migrate_legacy_event_data` something like 17 times an hour [2]. So, based on what `EXPLAIN ANALYZE` is showing, that only accounts for about a minute’s worth of computation each hour. Doesn’t seem like that’s where we’re spending the majority of our time.

[1] https://github.com/ansible/awx/issues/9547#issuecomment-796273041
[2] https://github.com/ansible/awx/issues/9520#issuecomment-794938798

**Comment by jladdjr** [comment]
I'd like to get a better sense of where the migrate function is actually spending its time. I have two ideas:

1. Turn on [auto-explain](https://www.postgresql.org/docs/12/auto-explain.html) on the database
2. Add some logging to migrate_legacy_event_data that prints some basic time deltas for each query we're running in that method

Working on that first item now.

**Comment by jladdjr** [comment]
Just got auto-explain turned on
.. started tower services
.. and I'm starting to see EXPLAIN ANALYZE results dropped in `/var/lib/pgsql/data/pg_log/postgresql-Thu.log`.

I need to hop off for now, but I'm curious about what kind of log info will see after tower has a chance to run through some of the jobevent migration a few times.

**Comment by jladdjr** [comment]
Looks like first migration since restart is going through - these EXPLAIN ANALYZE logs just popped up:

```
< 2021-03-11 00:58:11.560 UTC f12-h20-b08-5039ms.rdu2.scalelab.redhat.com-2624133-/usr/bin/aw >
LOG:  duration: 28055.305 ms  plan:
        Query Text: SELECT MAX(id) FROM _unpartitioned_main_jobevent;
        Result  (cost=0.83..0.84 rows=1 width=8) (actual time=28055.136..28055.149 rows=1 loops=1)
          InitPlan 1 (returns $0)
            ->  Limit  (cost=0.58..0.83 rows=1 width=8) (actual time=28055.111..28055.114 rows=1 loops=1)
                  ->  Index Only Scan Backward using main_jobevent_pkey1 on _unpartitioned_main_jobevent  (cost=0.58..401107078.18 rows=1597451520 width=8) (actual time=28055.085..28055.086 rows=1 loops=1)
                        Index Cond: (id IS NOT NULL)
                        Heap Fetches: 1
```

```
< 2021-03-11 01:02:36.611 UTC f12-h20-b08-5039ms.rdu2.scalelab.redhat.com-2624133-/usr/bin/aw >
LOG:  duration: 264993.834 ms  plan:
        Query Text: INSERT INTO main_jobevent SELECT *, '1970-01-01' as job_created FROM _unpartitioned_main_jobevent ORDER BY id DESC LIMIT 1000000 RETURNING id;
        Insert on main_jobevent  (cost=0.58..258592.44 rows=1000000 width=1397) (actual time=1667.550..263749.297 rows=1000000 loops=1)
          ->  Subquery Scan on "*SELECT*"  (cost=0.58..258592.44 rows=1000000 width=1397) (actual time=1282.936..111813.837 rows=1000000 loops=1)
                ->  Limit  (cost=0.58..248592.44 rows=1000000 width=1421) (actual time=1282.933..110841.467 rows=1000000 loops=1)
                      ->  Index Scan Backward using main_jobevent_pkey1 on _unpartitioned_main_jobevent  (cost=0.58..397113449.38 rows=1597451520 width=1421) (actual time=1282.930..110407.577 rows=1000000 loops=1)
```

```
< 2021-03-11 01:02:52.407 UTC  >LOG:  checkpoints are occurring too frequently (10 seconds apart)
< 2021-03-11 01:02:52.407 UTC  >HINT:  Consider increasing the configuration parameter "max_wal_size".
```

```
< 2021-03-11 01:03:04.038 UTC f12-h20-b08-5039ms.rdu2.scalelab.redhat.com-2624133-/usr/bin/aw >
LOG:  duration: 25410.079 ms  plan:
        Query Text: DELETE FROM _unpartitioned_main_jobevent WHERE id IN (SELECT id FROM _unpartitioned_main_jobevent ORDER BY id DESC LIMIT 1000000);
        Delete on _unpartitioned_main_jobevent  (cost=261093.02..8850926.12 rows=1000000 width=38) (actual time=25410.075..25410.075 rows=0 loops=1)
          ->  Nested Loop  (cost=261093.02..8850926.12 rows=1000000 width=38) (actual time=2707.056..11993.418 rows=1000000 loops=1)
                ->  HashAggregate  (cost=261092.44..271092.44 rows=1000000 width=40) (actual time=2494.959..3644.771 rows=1000000 loops=1)
                      Group Key: "ANY_subquery".id
                      ->  Subquery Scan on "ANY_subquery"  (cost=0.58..258592.44 rows=1000000 width=40) (actual time=1104.002..2032.964 rows=1000000 loops=1)
                            ->  Limit  (cost=0.58..248592.44 rows=1000000 width=8) (actual time=1103.946..1797.558 rows=1000000 loops=1)
                                  ->  Index Only Scan Backward using main_jobevent_pkey1 on _unpartitioned_main_jobevent _unpartitioned_main_jobevent_1  (cost=0.58..397113449.38 rows=1597451520 width=8) (actual time=1103.943..1712.565 rows=1000000 loops=1)
                                        Heap Fetches: 1000000
                ->  Index Scan using main_jobevent_pkey1 on _unpartitioned_main_jobevent  (cost=0.58..8.58 rows=1 width=14) (actual time=0.008..0.008 rows=1 loops=1000000)
                      Index Cond: (id = "ANY_subquery".id)
```

**Comment by jladdjr** [comment]
Pulling out some highlights from those logs:
* `SELECT MAX(id) FROM _unpartitioned_main_jobevent` => 28 seconds (ouch)
* `INSERT INTO main_jobevent SELECT *, '1970-01-01' as job_created FROM _unpartitioned_main_jobevent ORDER BY id DESC LIMIT 1000000 RETURNING id;` => 4 min, 25 seconds
* `DELETE FROM _unpartitioned_main_jobevent WHERE id IN (SELECT id FROM _unpartitioned_main_jobevent ORDER BY id DESC LIMIT 1000000);` => 25.4 seconds

As percentages:
`SELECT MAX(id)` => 8.9%
`INSERT` => 83.2%
`DELETE` => 8.0%

**Comment by jladdjr** [comment]
The insert is by far where we spend most of our time. So we _can_ optimize the `select MAX(id)`, but at best we're going to shave 8.5 hours off of a 4 day 3 hour long migration. Same story for the delete statement.

**Comment by jladdjr** [comment]
@Ladas - I thought this log entry was interesting - could this be causing any kind of performance hit?
```
< 2021-03-11 01:02:52.407 UTC  >LOG:  checkpoints are occurring too frequently (10 seconds apart)
< 2021-03-11 01:02:52.407 UTC  >HINT:  Consider increasing the configuration parameter "max_wal_size".
```

**Comment by jladdjr** [comment]
Turning off auto-explain, otherwise this log file is going to get massive. Also, going to put a bookmark in things for now. 👋

**Comment by jladdjr** [comment]
Another thought that just came to mind. Could db vacuuming be killing us while we're doing the migration? Wondering if turning it off (possibly just for some tables) would help us at all (cc @Ladas, @ryanpetrello ).

**Comment by Ladas** [comment]
summary from slack:

@jladdjr re: `max_wal_size`, yes. We should always do at least basic tuning based on the DB specs, e.g. with https://www.pgconfig.org/#/tuning?max_connections=100&pg_version=13&environment_name=WEB&total_ram=4&cpus=2&drive_type=SSD&arch=x86-64&os_type=linux  (fill in your DB specs)

--------------

@jladdjr if we'd disable vacuuming, the migration would take 2x space on disk. (DELETE query doesn't free up disk, disk is freed only after the deleted rows are vacuumed)

------

@jladdjr MAX(id) is likely broken due to removing primary key and just adding index, primary key has NOT NULL constraint, so it wouldn't be doing the extra Index Cond: (id IS NOT NULL) , so it should be faster.

It would be interesting to compare MAX(id) to `SELECT id FROM main_jobevent ORDER BY id DESC LIMIT 1; `, cause I'd expect that fetching last value of the index should be faster. (same operation as MAX(id) does). It should have the same explain.

-----

@ryanpetrello @jladdjr given we don't control speed of SSDs used for the DB at customer's side, I think it's ok to keep the migration as it is. (removing the slow places, we'd be tuning it only if the INSERT takes less time -> faster disk IO)

Since it's background op and the latest events should pop up in minutes, it's ok if this runs on background for days (not affecting AWX/Tower perf in the process)

**Comment by Ladas** [comment]
summary from slack:

@jladdjr btw. we should always to at least basic tuning based on the DB specs, e.g. with https://www.pgconfig.org/#/tuning?max_connections=100&pg_version=13&environment_name=WEB&total_ram=4&cpus=2&drive_type=SSD&arch=x86-64&os_type=linux  (fill in your DB specs)

--------------

@jladdjr if we'd disable vacuuming, the migration would take 2x space on disk. (DELETE query doesn't free up disk, disk is freed only after the deleted rows are vacuumed)

------

@jladdjr MAX(id) is likely broken due to removing primary key and just adding index, primary key has NOT NULL constraint, so it wouldn't be doing the extra Index Cond: (id IS NOT NULL) , so it should be faster.

It would be interesting to compare MAX(id) to `SELECT id FROM main_jobevent ORDER BY id DESC LIMIT 1; `, cause I'd expect that fetching last value of the index should be faster. (same operation as MAX(id) does). It should have the same explain.

-----

@ryanpetrello @jladdjr given we don't control speed of SSDs used for the DB at customer's side, I think it's ok to keep the migration as it is. (removing the slow places, we'd be tuning it only if the INSERT takes less time -> faster disk IO)

Since it's background op and the latest events should pop up in minutes, it's ok if this runs on background for days (not affecting AWX/Tower perf in the process)

**Comment by jladdjr** [comment]
> It would be interesting to compare MAX(id) to SELECT id FROM main_jobevent ORDER BY id DESC LIMIT 1;

Going to investigate ^, otherwise sounds like we can keep the migration in its current form

**Comment by jladdjr** [comment]
`max(id)` => 34 seconds

```
awx=# explain analyze select max(id) from main_jobevent;
                                                                                                QUERY PLAN

--------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------
 Result  (cost=31.48..31.49 rows=1 width=8) (actual time=6.399..6.400 rows=1 loops=1)
   InitPlan 1 (returns $0)
     ->  Limit  (cost=29.55..31.48 rows=1 width=8) (actual time=6.368..6.391 rows=1 loops=1)
           ->  Merge Append  (cost=29.55..3394609345.24 rows=1756803499 width=8) (actual time=6.365..6.365 rows=1 loops=1)
                 Sort Key: main_jobevent_old_events.id DESC
                 ->  Index Only Scan Backward using main_jobevent_old_events_pkey on main_jobevent_old_events  (cost=0.57..1315272977.38 rows=690628796 width=
8) (actual time=0.086..0.086 rows=1 loops=1)
                       Index Cond: (id IS NOT NULL)
                       Heap Fetches: 1
                 ->  Index Only Scan Backward using main_jobevent_20210308_16_pkey on main_jobevent_20210308_16  (cost=0.14..80.49 rows=20 width=8) (actual ti
me=0.025..0.025 rows=0 loops=1)
                       Index Cond: (id IS NOT NULL)
                       Heap Fetches: 0
                 ->  Index Only Scan Backward using main_jobevent_20210310_05_pkey on main_jobevent_20210310_05  (cost=0.29..193031.16 rows=102004 width=8) (a
ctual time=0.058..0.058 rows=1 loops=1)
                       Index Cond: (id IS NOT NULL)
                       Heap Fetches: 1
                 ->  Index Only Scan Backward using main_jobevent_20210310_12_pkey on main_jobevent_20210310_12  (cost=0.43..6177865.61 rows=3264453 width=8)
(actual time=0.073..0.073 rows=1 loops=1)
                       Index Cond: (id IS NOT NULL)
                       Heap Fetches: 1
                 ->  Index Only Scan Backward using main_jobevent_20210310_13_pkey on main_jobevent_20210310_13  (cost=0.44..37041386.37 rows=19571380 width=8
) (actual time=0.065..0.065 rows=1 loops=1)
                       Index Cond: (id IS NOT NULL)
                       Heap Fetches: 1
                 ->  Index Only Scan Backward using main_jobevent_20210310_14_pkey on main_jobevent_20210310_14  (cost=0.44..37065592.95 rows=19586104 width=8
) (actual time=0.060..0.061 rows=1 loops=1)
                       Index Cond: (id IS NOT NULL)
                       Heap Fetches: 1
                 ->  Index Only Scan Backward using main_jobevent_20210310_15_pkey on main_jobevent_20210310_15  (cost=0.43..30886493.38 rows=16321871 width=8
) (actual time=0.084..0.084 rows=1 loops=1)
                       Index Cond: (id IS NOT NULL)
                       Heap Fetches: 1
awx=# explain analyze select max(id) from _unpartitioned_main_jobevent;
^CCancel request sent
ERROR:  canceling statement due to user request
awx=# explain analyze select max(id) from _unpartitioned_main_jobevent;
                                                                                              QUERY PLAN

--------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------
 Result  (cost=0.83..0.84 rows=1 width=8) (actual time=34280.961..34280.967 rows=1 loops=1)
   InitPlan 1 (returns $0)
     ->  Limit  (cost=0.58..0.83 rows=1 width=8) (actual time=34280.947..34280.950 rows=1 loops=1)
           ->  Index Only Scan Backward using main_jobevent_pkey1 on _unpartitioned_main_jobevent  (cost=0.58..401107078.18 rows=1597451520 width=8) (actual t
ime=34280.945..34280.945 rows=1 loops=1)
                 Index Cond: (id IS NOT NULL)
                 Heap Fetches: 1
 Planning Time: 38.675 ms
 Execution Time: 34281.036 ms
(8 rows)
```

`select id .. limit 1` => 3.5 minutes
```
awx=# explain analyze select id from main_jobevent order by id desc limit 1;
                                                                                            QUERY PLAN

--------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------
 Limit  (cost=29.55..31.47 rows=1 width=8) (actual time=15.144..15.172 rows=1 loops=1)
   ->  Merge Append  (cost=29.55..3390045428.09 rows=1756714339 width=8) (actual time=15.140..15.140 rows=1 loops=1)
         Sort Key: main_jobevent_old_events.id DESC
         ->  Index Only Scan Backward using main_jobevent_old_events_pkey on main_jobevent_old_events  (cost=0.57..1313546317.89 rows=690628796 width=8) (actu
al time=0.162..0.162 rows=1 loops=1)
               Heap Fetches: 1
         ->  Index Only Scan Backward using main_jobevent_20210308_16_pkey on main_jobevent_20210308_16  (cost=0.14..80.44 rows=20 width=8) (actual time=0.025
..0.025 rows=0 loops=1)
               Heap Fetches: 0
         ->  Index Only Scan Backward using main_jobevent_20210310_05_pkey on main_jobevent_20210310_05  (cost=0.29..192776.15 rows=102004 width=8) (actual ti
me=0.134..0.134 rows=1 loops=1)
               Heap Fetches: 1
         ->  Index Only Scan Backward using main_jobevent_20210310_12_pkey on main_jobevent_20210310_12  (cost=0.43..6169704.47 rows=3264453 width=8) (actual
time=0.184..0.184 rows=1 loops=1)
               Heap Fetches: 1
         ->  Index Only Scan Backward using main_jobevent_20210310_13_pkey on main_jobevent_20210310_13  (cost=0.44..36992457.92 rows=19571380 width=8) (actua
l time=0.142..0.142 rows=1 loops=1)
               Heap Fetches: 1
         ->  Index Only Scan Backward using main_jobevent_20210310_14_pkey on main_jobevent_20210310_14  (cost=0.44..37016627.69 rows=19586104 width=8) (actua
l time=0.159..0.160 rows=1 loops=1)
               Heap Fetches: 1
         ->  Index Only Scan Backward using main_jobevent_20210310_15_pkey on main_jobevent_20210310_15  (cost=0.43..30845688.70 rows=16321871 width=8) (actua
l time=0.159..0.159 rows=1 loops=1)
               Heap Fetches: 1
         ->  Index Only Scan Backward using main_jobevent_20210310_16_pkey on main_jobevent_20210310_16  (cost=0.42..1348768.65 rows=713104 width=8) (actual t
ime=0.172..0.172 rows=1 loops=1)
               Heap Fetches: 1
         ->  Index Only Scan Backward using main_jobevent_20210310_18_pkey on main_jobevent_20210310_18  (cost=0.43..3083734.12 rows=1631585 width=8) (actual
time=0.147..0.147 rows=1 loops=1)
               Heap Fetches: 1
         ->  Index Only Scan Backward using main_jobevent_20210310_19_pkey on main_jobevent_20210310_19  (cost=0.44..37027104.39 rows=19591680 width=8) (actua
l time=0.156..0.157 rows=1 loops=1)
               Heap Fetches: 1
awx=#
awx=# explain analyze select id from _unpartitioned_main_jobevent order by id desc limit 1;
                                                                                           QUERY PLAN

--------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------
 Limit  (cost=0.58..0.83 rows=1 width=8) (actual time=212608.518..212608.545 rows=1 loops=1)
   ->  Index Only Scan Backward using main_jobevent_pkey1 on _unpartitioned_main_jobevent  (cost=0.58..397113449.38 rows=1597451520 width=8) (actual time=2126
08.515..212608.515 rows=1 loops=1)
         Heap Fetches: 1000001
 Planning Time: 40.403 ms
 Execution Time: 212608.643 ms
(5 rows)
```

**Comment by jladdjr** [comment]
`max(id)` => 17 seconds

```
explain analyze select max(id) from _unpartitioned_main_jobevent;



                                                                                              QUERY PLAN

--------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------
 Result  (cost=0.83..0.84 rows=1 width=8) (actual time=17650.145..17650.147 rows=1 loops=1)
   InitPlan 1 (returns $0)
     ->  Limit  (cost=0.58..0.83 rows=1 width=8) (actual time=17650.134..17650.136 rows=1 loops=1)
           ->  Index Only Scan Backward using main_jobevent_pkey1 on _unpartitioned_main_jobevent  (cost=0.58..401107078.18 rows=1597451520 width=8) (actual t
ime=17650.132..17650.132 rows=1 loops=1)
                 Index Cond: (id IS NOT NULL)
                 Heap Fetches: 1
 Planning Time: 21.803 ms
 Execution Time: 17650.205 ms
(8 rows)
```

`select id .. limit 1` => 6.6 seconds
```
awx=# explain analyze select id from _unpartitioned_main_jobevent order by id desc limit 1;
                                                                                         QUERY PLAN

--------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------
 Limit  (cost=0.58..0.83 rows=1 width=8) (actual time=6624.957..6624.958 rows=1 loops=1)
   ->  Index Only Scan Backward using main_jobevent_pkey1 on _unpartitioned_main_jobevent  (cost=0.58..397113449.38 rows=1597451520 width=8) (actual time=6624
.954..6624.954 rows=1 loops=1)
         Heap Fetches: 1000001
 Planning Time: 35.794 ms
 Execution Time: 6625.007 ms
(5 rows)
```

**Comment by jladdjr** [comment]
So `select id .. limit 1` runs in about a third of the time as `max(id)`.

- [ ] Hopping off to help with kids, but will update the branch to use ^
