### ISSUE TITLE
Advanced Search by key: Type results in a drop-down menu error

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#9549]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When performing an advanced search in the Schedules tab of a Job Template, and searching by the Type key, when search results are not successfully returned, the Key drop down menu shows no values (see screenshot). When filters are cleared, the menu items reappear.

##### ENVIRONMENT
* AWX version: Devel 3-10-21

##### STEPS TO REPRODUCE

Click on templates, select a specific template, and click the Schedules tab.
Click on Name to change the search identifier to Advanced. Leave Set Type blank.
Change the key to Type. Change the Lookup Type to Contains.
In the input field, enter a value you know to be true. I chose Run. Click on the search magnifying glass.
Click the drop-down that shows Type. You'll notice the list is empty. 
Clear the filters. If you click on that same drop down again, you'll notice that the list has reappeared.

##### EXPECTED RESULTS

That all drop-down menus would continue to have the same available selections.

##### ACTUAL RESULTS

One of the drop-down menu's choices disappeared temporarily.

##### ADDITIONAL INFORMATION
![image](https://user-images.githubusercontent.com/63685497/110690222-aa392b80-81b1-11eb-905a-19a74f464e53.png)

**Comment by nixocio** [comment]
Closing this one as a duplicated. See: https://github.com/ansible/awx/issues/9441
