### ISSUE TITLE
Clicking "Back" after Schedule deletion causes page reload error

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#9550]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Immediately after deleting one or more schedules from the schedules tab of a job template, clicking the back button results in a reload error where the page will not load, but stays blank and displays a spinning circIe indefinitely. Clicking refresh doesn't work. Only clicking one of the links in the app, in order to navigate elsewhere, works.

##### ENVIRONMENT
* AWX version: Devel 3-10-21

##### STEPS TO REPRODUCE

Click Templates, select a template, and click Schedules.
Click the checkbox next to one or more schedules and click Delete.
Right away, click the browser's Back button (I was trying to mimic a user who accidentally deleted something and in a silly way, tries clicking back to see if that helps).
You will notice a spinning circle on the page that will stay that way until you click another of the app's links. Clicking refresh doesn't work.

##### EXPECTED RESULTS

Clicking Back after deleting would bring the user to that page, showing that whatever schedules had just been deleted were still deleted.

##### ACTUAL RESULTS

The page went mostly blank and a reload circle spun and spun until I clicked one of the app's links to redirect the page.

##### ADDITIONAL INFORMATION

![Reload error](https://user-images.githubusercontent.com/63685497/110692868-d30ef000-81b4-11eb-8d7e-0312cc0fa084.gif)

**Comment by jakemcdermott** [comment]
The fix should focus on this behavior:

> The page went mostly blank and a reload circle spun and spun until I clicked one of the app's links to redirect the page.

^ It's ok to show an error for a deleted resource that no longer exists but we need to address the blank page.

**Comment by nixocio** [comment]
The same issue is also present on projects screen.

<img width="1780" alt="image" src="https://user-images.githubusercontent.com/9053044/123459247-059df680-d5b4-11eb-8502-90e60c21a900.png">

**Comment by akus062381** [comment]
resolved
