### ISSUE TITLE
Build Docker containers within AWX

### ISSUE THREAD

**Issue by hypery2k** [ansible/awx#9553]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Would be great if it's possible to build docker images within AWX using the docker module. Therefore DinD is needed.
Any plans to add support for that?

**Comment by wenottingham** [comment]
No, we don't have plans for this. See https://groups.google.com/g/awx-project/c/47MjWSUQaOc/m/1-Jh0fy3AgAJ for some architectural discussion here on how we're  moving to a more K8S-native deployment.
