### ISSUE TITLE
login page - bigger Single Sign-on icons in Next UI

### ISSUE THREAD

**Issue by balonik** [ansible/awx#9554]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Please make the Single Sign-on/SAML/Azure AD icons bigger (much bigger!) in the Next UI.
If enabled, other login options should take at least 50% of the Login form/screen.

It is really hard to instruct users to click the smallest Login icon that is easily missed.

![image](https://user-images.githubusercontent.com/17492066/110771357-b1684400-825a-11eb-8d4d-fe222823dacb.png)

**Comment by gmtime** [comment]
Since SAML login is usually corporate, it would be really good to have an option to replace this nondescript icon with company logo - that way it would be much easier to explain to users where they need to click to login
