### ISSUE TITLE
Sign in credentials as extra vars

### ISSUE THREAD

**Issue by markatdxb** [ansible/awx#9579]
##### ISSUE TYPE
 - Feature Idea
Use AWX sign in credentials as extra vars in playbooks

##### SUMMARY

I'm not sure if this is technically even possible but it would be great to have option to be able to use the user sign in credentials in playbooks. Basically I would login to AWX using my AD credentials and then those credentials could be used for delegation of some plays within the template

**Comment by wenottingham** [comment]
There's no connection that would allow for this, and it become unworkable once things such as scheduled jobs or workflows get in the mix.
