### ISSUE TITLE
All jobs in a Workflow Job Template should be expected to run in the same execution node

### ISSUE THREAD

**Issue by sugitk** [ansible/awx#9601]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Assume Ansible Tower/AWX has a cluster installation like node01, node02 and node03.
And we defined a workflow job template with the job node A -> B -> C.

When we run the WFJT, the job execution node is determined for each job node.   Hence the WFJT will be inconsistent situation because job A runs on the node01 and job B runs on the node02 and something like that.  For example, artifacts from the job A cannot be referred from the job B.

Once the Tower starts to run a WFJT, the customer wants to run all the jobs in the WF on the same execution node as sticky.

I proposed to define a single instance group and to specify the instance group at all JT in the WFJT.  However the customer wants not to specify a single IG.

1. Click a WFJT, the Tower/AWX determines an execution node in the cluster to be run for all JT in the WFJT
2. Next another workflow job can be run on other node in the cluster

When a JT in a WFJT is connected to a project, the project update and JT run in the same execution node.  I understand that the requirements from the customer is the same behavior as that.

**Comment by wenottingham** [comment]
This will not be implemented. Jobs are isolated from each other, and if artifacts need to be passed from job to job, it should be done via `set_stats` (in playbook/workflow) or via some other storage.

Future execution will be inside of containers which makes what is suggested completely impossible.
