### ISSUE TITLE
Documentation for Learners

### ISSUE THREAD

**Issue by LokiOfNorse** [ansible/awx#9602]
After some time of trying to install awx in multiple ways but most of them doesn't work. 

I know this is not a bug and there is a other forums to get "support", but I think the documentation here in the awx project is all over the place and doesn't work for someone trying to learn awx and ansible. 

There should be a standard documentation that point out every step and on which platform. No you can get lost in: awx Operator in Minikube that is only local, Kubernetes, open shift, docker (that doesn't work), docker compose etc. 

There should be an absolute user friendly documentation somewhere for which platform you want to deploy or to learn how to deploy it correctly. The latest builds doesn't work, the only one me and other newcomers successfully deployed it on was from the 12 release on a docker on cents. Which died after a restart. 

I would love to write the documentation for this for other people to learn how to deploy, use, learn and have fun with it. But first I need help deploying it from ONE correct documentation. Guides on internet is out of date since the deployment methods isn't working anymore. 

Awx should also 100% be a application capable to run directly on a VM and not limited to containers.

**Comment by kfiresmith** [comment]
I think the problem here is one of priorities and incentives.  
IBM/Red Hat provide AWX as a development codebaase for downstream Ansible Tower.  They are not doing this to give folks a free & easy alternative to Ansible Tower.  They expect learners to use the free 10-host Ansible Tower license for learning and demoing Tower, not AWX, so there is an incentive to not make AWX easy to deploy and lifecycle for new users.  

Personally I also wish that AWX was still easy-ish to deploy like older versions, and think that providing this would help Tower compete for market share against easier to deploy tools like Rundeck Open which deploys as a single package set or Docker container.  

If you truly just want to learn Ansible+Tower, hands down the easiest way will be to go get the 10-host free license from Red Hat.  If you want to run AWX for $0 in production, that's probably always going to be difficult to do.

**Comment by nicosalvadore** [comment]
> Personally I also wish that AWX was still easy-ish to deploy like older versions.

Yep I agree, the docker-compose method was quite easy to install and upgrade as new versions were released.
I understand that it was too much work to maintain for the small AWX team.

Maybe the community could come together and propose an alternative installation process still based on docker-compose. I really don't know the process behind the scenes and the work that it would need though, I guess it's pretty important...

**Comment by ryanpetrello** [comment]
@nicosalvadore,

> Maybe the community could come together and propose an alternative installation process still based on docker-compose

You can still install AWX using docker-compose, there just aren't official images published:

https://github.com/ansible/awx/tree/devel/tools/docker-compose

```shell
~ git clone -b 18.0.0 git@github.com:ansible/awx.git
~ make docker-compose-build
~ make docker-compose
```

**Comment by nicosalvadore** [comment]
@ryanpetrello Thank you for your insight, I've read the new docs a second time and I guess it should indeed be okay for most of us with tiny deployment.

**Comment by ryanpetrello** [comment]
@nicosalvadore,

Yes, the docker-compose has always been something we've only recommended for a minimal deployment for testing AWX - it's what most of the maintainers run on their laptops for development purposes.

It's not (and never will be) intended for production environments.

**Comment by LokiOfNorse** [comment]
@ryanpetrello i dont think its been clear that all should be installed in virtual environment in The docks. The docks Are written by really good people, but they Are not understandable for people that is not that good

**Comment by Rylon** [comment]
I have a similar problem with the current version. Previously, upgrading AWX has been painful and fragile, so we've avoided doing it. I decided to finally look at the latest version and have a go at upgrading only to find the recommended approach is to use AWX Operator to deploy to Kubernetes. 

We're not using Kubernetes, so this is not an option for us. Looking at the compose approach it seems to now be only for development purposes?

Previously we deployed AWX via Ansible using Docker. It seems the steps for running it now involve cloning a repository from a specific tag, then running `make` commands in the route that run Ansible playbooks to generate Docker Compose files? 

None of this is nice to automate via Ansible itself in a repeatable/idempotent way.

Following the paper trail from the old Docker release (https://hub.docker.com/r/ansible/awx_web) warns that this is no longer maintained and sends you to https://hub.docker.com/r/ansible/awx instead, which is for version <18, and sends you to https://quay.io/repository/ansible/awx instead for version >=18.

Is it possible to run AWX from the https://quay.io/repository/ansible/awx image?

Even simpler would be to publish AWX itself to PyPi, so people can install via Pip, provide a config file, and run it via whatever mechanism they have available.

**Comment by shanemcd** [comment]
Hi folks. Thank you for the feedback. 

AWX is a free project, with no guarantee of stability. While we have a lot of users, our team is fairly small and we simply do not have the resources to produce and maintain comprehensive documentation for the upstream community.

That being said, this is an open source project and you are free to contribute in areas you feel is lacking.

If you are unable to figure something out, we have a very active community that you can become involved with via our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
