### ISSUE TITLE
Job template add/edit form duplicate requests

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#9609]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The e2e test `can edit a job template` is failing because of the number of requests being made when the user access the Job template add or edit form

##### STEPS TO REPRODUCE

1. [Instal this chrome extension to help](https://chrome.google.com/webstore/detail/network-duplicates/pdaabiikfpfhfgiodfjfiobdmegjhnmo/related?hl=en)
2. Navigate to JT form (add or edit)
3. Refresh the page

##### EXPECTED RESULTS
unique requests being made
Uniques 
##### ACTUAL RESULTS

Edit form:
![image](https://user-images.githubusercontent.com/12464858/111520216-a6b81e00-8736-11eb-8bd2-78c6ef09b203.png)

Add form:
![image](https://user-images.githubusercontent.com/12464858/111520310-be8fa200-8736-11eb-933f-1fb11a6a11b6.png)

**Comment by nixocio** [comment]
Closing this one as duplicated issue of https://github.com/ansible/awx/issues/9534.
