### ISSUE TITLE
Missing AWX  installer directory after cloning

### ISSUE THREAD

**Issue by kodewise** [ansible/awx#9611]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 17.1
* AWX install method: Linux
* Ansible version 2.9.6
* Operating System: Ubuntu 20.04
* Web Browser:

##### STEPS TO REPRODUCE

git clone https://github.com/ansible/awx.git
cd awx/installer/

##### EXPECTED RESULTS

After cloning the latest AWX git repository, I can no longer find the Installer directory, What happened?

##### ACTUAL RESULTS

Missing 'installer directory

**Comment by ryanpetrello** [comment]
Hey @kodewise,

`devel` is unstable, try the latest released version of AWX:

https://github.com/ansible/awx/releases/tag/17.1.0
https://github.com/ansible/awx/blob/17.1.0/INSTALL.md

`./installer` is going away in the next version of AWX:

https://groups.google.com/g/awx-project/c/47MjWSUQaOc/m/bCjSDn0eBQAJ
https://github.com/ansible/awx/blob/devel/tools/docker-compose/docs/data_migration.md
