### ISSUE TITLE
add custom script to inventory

### ISSUE THREAD

**Issue by papillonyi** [ansible/awx#9621]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
can't add custom script to inventory

##### ENVIRONMENT
* AWX version: 17.1.0
* AWX install method: k8s
* Ansible version:  2.9.18
* Operating System: linux
* Web Browser: chrome

##### STEPS TO REPRODUCE

when i try to add source to inventory and select custom script, the web show no thing, and i can't upload or write anything;
![image](https://user-images.githubusercontent.com/17263630/111760464-b58b0600-88d9-11eb-9115-52b4f6bf7e89.png)

##### EXPECTED RESULTS

what i do is to upload or input a script to awx, but i can't do it.

**Comment by ryanpetrello** [comment]
Hey @papillonyi,

This view is being removed in the next major version of AWX - in the meantime, this UI is just busted.

More generally, we've deprecated and are removing this feature - instead, define custom inventory scripts in your SCM/Project.
