### ISSUE TITLE
AWX doesn't appear to install collections automatically based on collections/requirements.yml

### ISSUE THREAD

**Issue by shenqinb-star** [ansible/awx#9625]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX doesn't appear to install collections automatically based on collections/requirements.yml

##### ENVIRONMENT
* AWX version: 17.1.0
* AWX install method: Kubernetes
* Ansible version:  2.9.18
* Operating System: 
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create a AWX project and link to a git project with following structure:

/-playbook.yml
 -**collections/requirements.yml**

##### EXPECTED RESULTS

When running project sync, I expected that it would to run `ansible-galaxy` against the requirements.yml to install the collections.

##### ACTUAL RESULTS
Install was skipped
![image](https://user-images.githubusercontent.com/79623318/111789063-ba60b180-88fb-11eb-8045-99bc777b3b23.png)

##### ADDITIONAL INFORMATION

1. Collection(s) Download are enabled
![image](https://user-images.githubusercontent.com/79623318/111789246-e2501500-88fb-11eb-955d-3fca0043dbe9.png)

**Comment by ryanpetrello** [comment]
@shenqinb-star usually this means that your Organization doesn't have a credential defined pointed at Ansible Galaxy.  Can you share your Organization's "edit" view?

**Comment by shenqinb-star** [comment]
@ryanpetrello, thanks for your replay. I'm new to AWX/Ansible, I didn't setup any credentials for my organization. but I don't think credentials is needed to install collections from official galaxy repo https://galaxy.ansible.com. I'm able to install the collections via running `ansible-galaxy collection install -r requirements.yml` manually.

**Comment by shenqinb-star** [comment]
if credentials is required, would please guide me how to setup credentials for official galaxy repo https://galaxy.ansible.com. many thanks!

**Comment by avgKol** [comment]
@shenqinb-star  I have the same error . Did you find out what needs to be fixed here to install the collections and requirements ?

**Comment by ryanpetrello** [comment]
You all want to make sure you see something like this on your Organization:

<img width="908" alt="image" src="https://user-images.githubusercontent.com/214912/112335563-ba153d00-8c92-11eb-9580-9662e5ec3429.png">

(...that a credential is defined here that points at galaxy.ansible.com):

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/214912/112335643-ca2d1c80-8c92-11eb-917a-30fcdf5dc310.png">

**Comment by avgKol** [comment]
> You all want to make sure you see something like this on your Organization:
> 
> <img alt="image" width="908" src="https://user-images.githubusercontent.com/214912/112335563-ba153d00-8c92-11eb-9580-9662e5ec3429.png">
> 
> (...that a credential is defined here that points at galaxy.ansible.com):
> 
> <img alt="image" width="1281" src="https://user-images.githubusercontent.com/214912/112335643-ca2d1c80-8c92-11eb-917a-30fcdf5dc310.png">

Thanks @ryanpetrello  . Do we also need to run these inside the awx-task container ?
```shell
source /var/lib/awx/venv/ansible/bin/activate
pip install openshift
```

I am following the steps in this [post](http://blog.networktocode.com/post/kubernetes-collection-ansible) to run Kubernetes tasks in AWX.

**Comment by shenqinb-star** [comment]
@ryanpetrello , it works after adding Galaxy credential to our Organization. thanks a lot.

**Comment by ryanpetrello** [comment]
@avgKol,

I'm not sure why that blog article suggests you need to manually install `openshift`; it should already be available in the default virtual environment in recent versions of AWX (https://github.com/ansible/awx/blob/17.1.0/requirements/requirements_ansible.txt#L79)

**Comment by amg-web** [comment]
my requirements.yml and placed in roles folder.

```
collections:
- name: community.general
- name: community.postgresql
- name: community.docker
- name: community.grafana
- name: community.zabbix
- name: community.crypto
```

AWX reads the file but:
"Skipping install, no requirements found"

What is wrong here?

**Comment by shenqinb-star** [comment]
@amg-web  you need to add Galaxy credential to our Organization in AWX. detail to see below:
![image](https://user-images.githubusercontent.com/79623318/114335919-648ccb80-9b80-11eb-9509-1c905ee33e8b.png)
