### ISSUE TITLE
Filter by container registry credential to be associated with EE

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#9628]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Filter by container registry credential to be associated with EE

**Comment by ryanpetrello** [comment]
Additionally, at the API level, we want to make sure that *only* container registry credentials can be associated with an EE cc @rebeccahhh

**Comment by tiagodread** [comment]
The lookup field is filtering by container registry:

![image](https://user-images.githubusercontent.com/12464858/119715944-f1db6500-be3a-11eb-80b8-99c86856bc9c.png)
