### ISSUE TITLE
[ui_next] JT Edit Form's Playbook Typeahead does not have constrained height

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#9629]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
JT Edit Form's Playbook Typeahead does not have constrained height. Renders beyond the length of the page

##### STEPS TO REPRODUCE
1. Navigate to JT Edit Form
2. Open Playbook Typeahead.
Note: 200 returned and renders offscreen

##### EXPECTED RESULTS
1. maxheight calculated to fit on page for our 1024x768 user before scrolling kicks in

##### ACTUAL RESULTS
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
halp

##### ADDITIONAL INFORMATION

https://user-images.githubusercontent.com/12446869/111798476-7a201580-88a0-11eb-97ff-3548641589c9.mp4

**Comment by jakemcdermott** [comment]
https://github.com/ansible/awx/pull/9827
