### ISSUE TITLE
Mouse events sent to Tower continuously via websockets during record mode (behavior only present on feature branch - network_ui_3_3)

### ISSUE THREAD

**Issue by jladdjr** [ansible/awx#963]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

When record-mode is enabled on the network visualization page, a stead stream of mouse events is sent to Tower via websockets:

![repro](https://user-images.githubusercontent.com/4440360/34797367-2d0aafe0-f626-11e7-9ec9-97fbb05ef1b2.gif)

##### ENVIRONMENT
* AWX version: 1.0.2-596-g6f9d0b7
* AWX install method: docker for mac

##### STEPS TO REPRODUCE

1. Create an inventory
2. On the inventory list page, click on the network icon (at right)
3. Open browser's developer console, click on network and select websocket events
4. Click on record and move mouse over canvas

##### EXPECTED RESULTS

Would expect discrete events (clicking, final position after moving an item) to be sent to tower.

##### ACTUAL RESULTS

Websocket messages are being sent for each mouse event.

##### ADDITIONAL INFORMATION

* Remember hearing that each event sent to Tower is being stored in the database. 
* While it may be unlikely that a number of people would use the network visualization page at the same time, it seems like Tower may experience an unnecessary performance hit by processing a continuous stream of mouse events.

**Comment by jladdjr** [comment]
Also wanted to note that websocket messages are sent even when record mode is off:

From [/awx/network_ui/static/network_ui/CONTRIBUTING.md](/awx/network_ui/static/network_ui/CONTRIBUTING.md):
> Mouse movements, mouse clicks, and key presses are all routed by the network UI code and not by the browser. This is done to implement interactions with the virtual graphical canvas that are not supported by the browser.

**Comment by matburt** [comment]
This currently only affects the network ui implementation branch. It seems like we shouldn't need to send these events unless there is something actually going on... like pointer movement doesn't need to be directly tracked as events (or stored) all the time.

**Comment by benthomasson** [comment]
This is a feature for development.  Record mode is only for building tests.  This will not be used by the end-user.

> Remember hearing that each event sent to Tower is being stored in the database.

This is not correct.  UI events are not stored in the database unless recording a test case during development.


> While it may be unlikely that a number of people would use the network visualization page at the same time, it seems like Tower may experience an unnecessary performance hit by processing a continuous stream of mouse events.

This claim needs to be backed up with performance measurement.    I have found the websocket to be surprisingly performant and has low overhead even over low VPN links.  I welcome data that says otherwise.

**Comment by benthomasson** [comment]
This is expected behavior for development and test and the feature will be removed for production.
