### ISSUE TITLE
[ui_next] JT Edit Form's Playbook typeahead select does not close after playbook selected

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#9630]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
 JT Edit Form's Playbook typeahead select does not collapse after playbook selected. This was fixed on the other typeahead components. This might be a dupe.

##### ENVIRONMENT
* AWX version: 03/19

##### STEPS TO REPRODUCE
1. Navigate to JT Add/Edit Form
2. Select a Playbook
Note: playbook select does not collapse after selection

##### EXPECTED RESULTS
1. Consistency with typeahead selection across the app
2. Playbook select dropdown closes after selection

##### ACTUAL RESULTS
1. Playbook remains highlighted and user must clickaway. Inconsistent with other typehead implementations

##### ADDITIONAL INFORMATION

![Screen Recording 2021-03-19 at 10 51 55 AM](https://user-images.githubusercontent.com/12446869/111799252-3a0d6280-88a1-11eb-8392-48a8d2eb99d5.gif)

**Comment by unlikelyzero** [comment]
@AlexSCorey do you think you could fix this one really quick?

**Comment by nixocio** [comment]
This one is now fixed on the new UI.
