### ISSUE TITLE
[RFE] Organisation should show the Teams permission in GUI once permission is assgin to the Team. 

### ISSUE THREAD

**Issue by ammygill** [ansible/awx#9633]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
On the organizations / {{myOrg}} / permissions view, there is no indications that team has any permission; only users are listed. I can see the "team roles" column with roles for users that are members of the team but otherwise, no indication. I think both users and teams should be listed in the permissions view

**Comment by ryanpetrello** [comment]
I think this is just a misconception - @mabashian can you comment on this?

**Comment by mabashian** [comment]
> only users are listed

Yea this is a list of users and what they're roles are.  The API does not return the data in the way you're describing.  If you want to see the team roles you'll have to go to `#/teams/:id/roles`
