### ISSUE TITLE
Editing a credential for moment will display the id of credential type

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#9636]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Editing a credential for moment will display the id of credential type, then display the proper name.

https://user-images.githubusercontent.com/9053044/111824737-f6285680-88bc-11eb-8b28-4693aeb125d1.mov

**Comment by tiagodread** [comment]
@jakemcdermott @nixocio I tried this on devel on dev or production build and with network throotling enabled/disabled and I couldn't reproduce this issue 

![chrome-capture](https://user-images.githubusercontent.com/12464858/113922332-8cb1ae80-97bd-11eb-926b-6347b93746b9.gif)

**Comment by nixocio** [comment]
This issue was already addressed as part of https://github.com/ansible/awx/pull/9662 - that is probably why we can not recreate anymore on devel.
