### ISSUE TITLE
Missing Management Jobs GUI

### ISSUE THREAD

**Issue by LokiOfNorse** [ansible/awx#9643]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Missing Management Jobs in the tab: "Management Jobs" while the jobs are running in schedules and jobs. 

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: Virtual Environment / Docker
* Ansible version:  latest
* Operating System: Ubuntu 20.04
* Web Browser: Firefox (Apple m1 machine)
* Other: Worked on earlier versions of awx. 

##### STEPS TO REPRODUCE

GUI

##### EXPECTED RESULTS

See the manegement jobs running

##### ACTUAL RESULTS

Blanc Screen

**Comment by jakemcdermott** [comment]
:wave: It'll be included in the upcoming awx release
