### ISSUE TITLE
Workflow approvals shows blank page when delete user

### ISSUE THREAD

**Issue by Davidffry** [ansible/awx#9645]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Workflow approvals blank page when delete user

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.17
* Operating System: Debian
* Web Browser: All

##### STEPS TO REPRODUCE

launch or approve many wokflow on workflow page
Delete the user from the workflow come from 

##### EXPECTED RESULTS

let the approve workflow waiting or let the displaying approval item

##### ACTUAL RESULTS
blank page

**Comment by mabashian** [comment]
Closing - will provide a link to fix

**Comment by mabashian** [comment]
https://github.com/ansible/awx/pull/9988
