### ISSUE TITLE
Hipchat notification is not working for job completion (success or failure)

### ISSUE THREAD

**Issue by one1zero1one** [ansible/awx#965]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY
Hipchat notification not working

##### ENVIRONMENT
* AWX version: 1.0.2.322
* AWX install method: docker
* Ansible version:  2.4.2.0 
* Operating System: Ubuntu 16.04
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Configure alerting to hipchat, test alert (works OK), setup notification (fail&success) for template, run job.

##### EXPECTED RESULTS

Entries in hipchat channel.

##### ACTUAL RESULTS

No alerts in hipchat channel (apart from test alert).

Worked before, updated from devel latest, seems broken. 

##### ADDITIONAL INFORMATION

Most probably related to:
- https://github.com/ansible/awx/issues/933 (slack notification broken in the same way)
- https://github.com/ansible/awx/issues/935 (email notification broken in the same way)

All of which seem to be linked to the way flags for firing notifications work.
- https://github.com/ansible/awx/issues/711

**Comment by jopaik** [comment]
test notification work but the job completion or success doesn't work.  Reconfirming bug
