### ISSUE TITLE
Ansible AWX and Okta SAML

### ISSUE THREAD

**Issue by dburns-vistra** [ansible/awx#9657]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker on linux
* Ansible version:  2.9
* Operating System: Amazon Linux 2
* Web Browser: Chrome

##### STEPS TO REPRODUCE

I get the information from my Security Dept for Okta SAML SSO integration.  I put in the information into AWX as documented.  I get the S at the bottom of the screen, however when I try to access it just gives me a login screen over and over.  If I go from the Okta chicklet, nothing happens.

##### EXPECTED RESULTS

Okta SSO works from the chicklet

##### ACTUAL RESULTS

Nothing happens

##### ADDITIONAL INFORMATION

I don't know where to get the logs, I have looked at the Nginx stuff for the container.  
I do have NGINX running as a reverse proxy to get SSL, do I also need to have SSL in the container.  Could that be causing the issue?  Passing data from SSL to non-SSL for a secure passage?

I am going to have a time slice for security again for a sprint we are doing at first of April.  I have spent time on this off and on for months.  I have also query the user group with no help.

**Comment by ryanpetrello** [comment]
Hey @dburns-vistra,

This issue tracker is for tracking feature enhancements and bugs to AWX itself, not for help troubleshooting issues.

Unfortunately, we have to limit this because of limited volunteer time to respond to issues - If you need help troubleshooting an AWX install, the options are our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by ryanpetrello** [comment]
@one-t @jakemcdermott et al, any of you know of any endemic issues in AWX 15.x that would affect SAML login integration support across the board (and which could've been addressed in newer versions of AWX?)

**Comment by dburns-vistra** [comment]
Ryan, I may have emailed you before when I was trying to point out some documentation stuff.

I am not really trying to get support, I have tried to go down the community group.

I don’t own the Okta piece that is in another group.  I did do all the steps in the Ansible Tower documentation, to no avail.  I reached out the community, all I basically got was it should work.

I will be happy to work with whomever to make sure or help with better documenting that needs to be done or whatever.

Thank you
Daniel

Daniel R. Burns |Lead Cloud Platform Engineer – Platform Services |[A picture containing clock  Description automatically generated] | CFB #2273| Phone: 214-812-2277<tel:+1(214)%20812-2277>|Mobile: 469-298-8917<tel:+1(469)298-8917>|Email: ***@***.******@***.***>

Please direct all issues and requests to ServiceNow<https://vistra.service-now.com/sp?id=vistra_index>.

From: Ryan Petrello ***@***.***>
Reply-To: ansible/awx ***@***.***>
Date: Monday, March 22, 2021 at 3:15 PM
To: ansible/awx ***@***.***>
Cc: "Burns, Daniel" ***@***.***>, Mention ***@***.***>
Subject: Re: [ansible/awx] Ansible AWX and Okta SAML (#9657)

EXTERNAL EMAIL


@one-t<https://github.com/one-t> @jakemcdermott<https://github.com/jakemcdermott> et al, any of you know of any endemic issues in AWX 15.x that would affect SAML login integration across the board (and which could've been addressed in newer versions of AWX?)

**Comment by ryanpetrello** [comment]
Hey @dburns-vistra,

Yep, I remember updating the developer docs recently.  Unfortunately, I don't know much about configuring SAML, so I can't really help personally.  If you do uncover whatever the issue is (I _suspect_ it's probably a misconfigured URL or somesuch?), I'd be glad to review a pull request with documentation.  Also, if you've found some error in Red Hat's documentation, I can probably put you in touch with folks at Red Hat who can correct it.

**Comment by egmar** [comment]
I'd suggest installing this extension https://chrome.google.com/webstore/detail/saml-tracer/mpdajninpobndbfcldcmbpnnbhibjmch?hl=en and see where SAML flow fails. Also, when opening `https://<awxhost>/sso/metadata/saml/` validate if `Location` in `md:AssertionConsumerService` is with `https`

**Comment by dburns-vistra** [comment]
With that tracer I see some errors.  Would you be able to assist Egor?

Thank you
Daniel

Daniel R. Burns |Lead Cloud Platform Engineer – Platform Services |[A picture containing clock  Description automatically generated] | CFB #2273| Phone: 214-812-2277<tel:+1(214)%20812-2277>|Mobile: 469-298-8917<tel:+1(469)298-8917>|Email: ***@***.******@***.***>

Please direct all issues and requests to ServiceNow<https://vistra.service-now.com/sp?id=vistra_index>.

From: Egor Margineanu ***@***.***>
Reply-To: ansible/awx ***@***.***>
Date: Tuesday, March 23, 2021 at 3:53 AM
To: ansible/awx ***@***.***>
Cc: "Burns, Daniel" ***@***.***>, Mention ***@***.***>
Subject: Re: [ansible/awx] Ansible AWX and Okta SAML (#9657)

EXTERNAL EMAIL


I'd suggest installing this extension https://chrome.google.com/webstore/detail/saml-tracer/mpdajninpobndbfcldcmbpnnbhibjmch?hl=en and see where SAML flow fails. Also, when opening https:///sso/metadata/saml/ validate if Location in md:AssertionConsumerService is with https
