### ISSUE TITLE
Propose a few spelling corrections to the markdown

### ISSUE THREAD

**Issue by jeis2497052** [ansible/awx#966]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY

I propose a few spelling corrections listed below

```
diff --git a/docs/clustering.md b/docs/clustering.md
index df52cbadd..84245c7d7 100644
--- a/docs/clustering.md
+++ b/docs/clustering.md
@@ -60,7 +60,7 @@ The current standalone instance configuration doesn't change for a 3.1+ deploy.
   hostD
   ```
 
-  The `database` group remains for specifying an external postgres. If the database host is provisioned seperately this group should be empty
+  The `database` group remains for specifying an external postgres. If the database host is provisioned separately this group should be empty
   ```
   [tower]
   hostA
@@ -97,7 +97,7 @@ The current standalone instance configuration doesn't change for a 3.1+ deploy.
 
 The most important field to point out for variability is `rabbitmq_use_long_name`. That's something we can't detect or provide a reasonable
 default for so it's important to point out when it needs to be changed. If instances are provisioned to where they reference other instances
-internally and not on external addressess then `rabbitmq_use_long_name` semantics should follow the internal addressing (aka `rabbitmq_host`.
+internally and not on external addresses then `rabbitmq_use_long_name` semantics should follow the internal addressing (aka `rabbitmq_host`.
 
 Other than `rabbitmq_use_long_name` the defaults are pretty reasonable:
 ```
@@ -246,7 +246,7 @@ Each Tower instance is made up of several different services working collaborati
 * HTTP Services - This includes the Tower application itself as well as external web services.
 * Callback Receiver - Whose job it is to receive job events from running Ansible jobs.
 * Celery - The worker queue, that processes and runs all jobs.
-* RabbitMQ - Message Broker, this is used as a signaling mechanism for Celery as well as any event data propogated to the application.
+* RabbitMQ - Message Broker, this is used as a signaling mechanism for Celery as well as any event data propagated to the application.
 * Memcached - local caching service for the instance it lives on.
 
 Tower is configured in such a way that if any of these services or their components fail then all services are restarted. If these fail sufficiently
@@ -326,7 +326,7 @@ When verifying acceptance we should ensure the following statements are true
   only run on instances in those Instance Groups.
 * Project updates should manifest their data on the host that will run the job immediately prior to the job running
 * Tower should be able to reasonably survive the removal of all instances in the cluster
-* Tower should behave in a predictable fashiong during network partitioning
+* Tower should behave in a predictable fashion during network partitioning
 
 ## Testing Considerations
 
diff --git a/docs/custom_credential_types.md b/docs/custom_credential_types.md
index c1b538756..905c43aa7 100644
--- a/docs/custom_credential_types.md
+++ b/docs/custom_credential_types.md
@@ -255,7 +255,7 @@ endpoint:
     }
 
 
-API Backwards Compatability
+API Backwards Compatibility
 ---------------------------
 
 `/api/v1/credentials/` still exists in Tower 3.2, and it transparently works as
diff --git a/docs/inventory_refresh.md b/docs/inventory_refresh.md
index a623840ed..250bb4e17 100644
--- a/docs/inventory_refresh.md
+++ b/docs/inventory_refresh.md
@@ -18,7 +18,7 @@ facts and are per-host. These stored facts can be used to filter hosts via the
 `/api/v2/hosts` endpoint, using the GET query parameter `host_filter` i.e.
 `/api/v2/hosts?host_filter=ansible_facts__ansible_processor_vcpus=8`
 
-The grammer of `host_filter` allows for:
+The grammar of `host_filter` allows for:
 * grouping via `()`
 * the boolean `and` operator
 * `__` to reference related fields in relational fields
@@ -100,7 +100,7 @@ In the above example, you are limiting the search to the "US-East" inventory and
 hosts with a name containing "nyc".
 
 
-### Acceptance Critera
+### Acceptance Criteria
 When verifying acceptance we should ensure the following statements are true:
 ``
 
diff --git a/docs/rbac.md b/docs/rbac.md
index c0bcb6860..540729e24 100644
--- a/docs/rbac.md
+++ b/docs/rbac.md
@@ -9,7 +9,7 @@ The intended audience of this document is the Ansible Tower developer.
 
 There are three main concepts to be familiar with, Roles, Resources, and Users.
 Users can be members of a role, which gives them certain access to any
-resources associated with that role, or any resources associated with "descendent"
+resources associated with that role, or any resources associated with "descendant"
 roles.
 
 For example, if I have an organization named "MyCompany" and I want to allow
@@ -72,7 +72,7 @@ The RBAC system defines a few new models. These models represent the underlying
 
 ##### `visible_roles(cls, user)`
 
-`visible_roles` is a class method that will lookup all of the `Role` instances a user can "see". This includes any roles the user is a direct decendent of as well as any ancestor roles.
+`visible_roles` is a class method that will lookup all of the `Role` instances a user can "see". This includes any roles the user is a direct decedent of as well as any ancestor roles.
 
 ##### `singleton(cls, name)`
 
diff --git a/docs/task_manager_system.md b/docs/task_manager_system.md
index 4d1dd8dae..3b983fe15 100644
--- a/docs/task_manager_system.md
+++ b/docs/task_manager_system.md
@@ -6,11 +6,11 @@ Independent jobs are ran in order of creation time, earliest first. Jobs with de
 
 ## Task Manager Architecture
 
e()`.
dule()`.
 
 ### Hybrid Scheduler: Periodic + Event
 in the present and future, that change the 3 scheduling considerations for which we should call `schedule()` (i.e. adding new nodes to tower changes the capacity, obscure job error handling that fails a job)
- Emperically, the periodic task manager has served us well in the past and we will continue to rely on it with the added event-triggered `schedule()`.
+ Empirically, the periodic task manager has served us well in the past and we will continue to rely on it with the added event-triggered `schedule()`.
 
 ### Scheduler Algorithm
  * Get all non-completed jobs, `all_tasks`

```




##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

<!-- For bugs, please show exactly how to reproduce the problem. For new
features, show how the feature would be used.  -->

##### EXPECTED RESULTS

<!-- For bug reports, what did you expect to happen when running the steps
above? -->

##### ACTUAL RESULTS

<!-- For bug reports, what actually happened? -->

##### ADDITIONAL INFORMATION

<!-- Include any links to sosreport, database dumps, screenshots or other
information. -->

**Comment by wenottingham** [comment]
Can you send this diff as an actual pull request?

**Comment by ryanpetrello** [comment]
related: https://github.com/ansible/awx/pull/997

**Comment by matburt** [comment]
Submit a PR for improvements. This doesn't need an issue, closing.
