### ISSUE TITLE
User still see previous session info upon click on new job link

### ISSUE THREAD

**Issue by anujbansal31** [ansible/awx#9660]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 14.0.0
* AWX install method: openshift on linux
* Ansible version:  
* Operating System: Linux
* Web Browser: Chrome, MicroSoft Edge 

##### STEPS TO REPRODUCE

1. Login on AWX url.
2. Browse/open anything such Users, Jobs or any playbook.
3. Logout explicitly or automatic logout after session expire. 
4. Click on awx link provided by any user, example : https://awx.com/#/jobs/project/1470
5.  User will still see his old session detail where he logged out. 
means, if user had opened last link and was present on any pgae, he will still see the same page instead of new link: https://awx.com/#/jobs/project/1470

##### EXPECTED RESULTS

Once User get logged out from AWX, he/she should be able to land on new page which they recently opened. In our example, they should see https://awx.com/#/jobs/project/1470  instead of their last expired session detail.

##### ACTUAL RESULTS

When user logged In AWX again, they still land on old opened page.

**Comment by anujbansal31** [comment]
I am using SSO with SAML and LDAP authentication. AWX should forget the user's old session detail once they logged out.

If AWX will not keep old session detail, then it will open the new link directly.

**Comment by jakemcdermott** [comment]
:wave: 
Hello. Thanks for creating this issue. This bug has been addressed in a more recent version of AWX: https://github.com/ansible/awx/pull/8299

This should be fixed by updating to a later version of AWX (16.0.1+).
