### ISSUE TITLE
Cannot save Miscellaneous System Settings on new cluster

### ISSUE THREAD

**Issue by lachesis** [ansible/awx#9669]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I cannot save my changes to the Miscellaneous System settings of a newly created AWX Tower install. I receive no UI feedback but the network tab shows `{"CUSTOM_VENV_PATHS":["Expected list of strings but got <class 'str'> instead."]}`. I have not attempted to set up custom venvs, nor can I find that setting in the UI.

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: minikube following https://github.com/ansible/awx/blob/devel/INSTALL.md
* Ansible version:  unknown
* Operating System: ArchLinux
* Web Browser: Firefox 87

##### STEPS TO REPRODUCE

1. Install a new instance of AWX using the instructions given in the INSTALL.md file
2. Log in as admin
3. Edit settings under /#/settings/miscellaneous_system/details
4. Attempt to change the base url from "https://towerhost" to my actual base URL.
5. Hit save

##### EXPECTED RESULTS

Settings save and UI reverts to the details page.

##### ACTUAL RESULTS

No UI feedback at all, following error in network tab.
```
{"CUSTOM_VENV_PATHS":["Expected list of strings but got <class 'str'> instead."]}
```
The PATCH request is sent to https://MYDOMAIN/api/v2/settings/all/ and has the following relevant data:
```
"CUSTOM_VENV_PATHS":"[]"
```

**Comment by tiagodread** [comment]
#9653 fixed this bug
