### ISSUE TITLE
Multiple logger support

### ISSUE THREAD

**Issue by cesarfn4** [ansible/awx#967]
##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY

Currently Tower only allows a single configurable method for logging data, please allow for multi-server / multi-method logging configuration.

##### ENVIRONMENT

* AWX version: 1.0.0
* Ansible version:  2.4.0

##### EXPECTED RESULTS

Support multiple logger aggregation

**Comment by ryanpetrello** [comment]
Note that if this implemented _in_ awx, it's unlikely to scale well for large amounts of log output with multiple loggers.  I'd argue that this is the type of problem best solved in external log aggregation software like https://www.elastic.co/products/logstash (which awx already integrates with).

**Comment by shanemcd** [comment]
I don't think we intend to do this. Closing.
