### ISSUE TITLE
What is the path to serve the app from?

### ISSUE THREAD

**Issue by gaia** [ansible/awx#9672]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX home page displays html source code OR is not functional. migrated/upgraded from 17.x on Docker for Windows with WSL

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: docker?
* Ansible version:  2.9.6
* Operating System: Ubuntu 20.04.2 LTS (under Windows 10, WSL2)
* Web Browser: doesn't make a difference

##### STEPS TO REPRODUCE

after migrating from docker 17.x, I am trying to run the web server. I tried both npm's serve and python3's http.server, no difference. I had to guess the directory to start the server from, the instructions do not show. It seems that they are either

`ui_next/public`, which shows me:
```
<% if (process.env.NODE_ENV === 'production') { %> <% } %> <% if (process.env.NODE_ENV === 'production') { %>
<% } else { %>
<% } %>
```
`ui_next/build`, which shows me (entering login info and pressing submit does nothing)
![image](https://user-images.githubusercontent.com/87547/112237284-95bc5080-8bff-11eb-9cde-aa7b4fd47fa7.png)

Am I starting the server on the wrong folder? If yes, what is the right folder? If not, which is the correct folders, and why doesn't it work?

##### EXPECTED RESULTS

login into the app

##### ACTUAL RESULTS

no functional app

##### ADDITIONAL INFORMATION

**Comment by lemmy04** [comment]
Did you follow the migration instructions on https://github.com/ansible/awx/blob/devel/tools/docker-compose/docs/data_migration.md?

I had the same thing, until i ran the last step - the "docker exec..." one. Also: #9675 - you might have to actually run the migration play twice.

**Comment by shanemcd** [comment]
The steps for building the UI are documented here: https://github.com/ansible/awx/tree/devel/tools/docker-compose#clean-and-build-ui

**Comment by gaia** [comment]
> Did you follow the migration instructions on https://github.com/ansible/awx/blob/devel/tools/docker-compose/docs/data_migration.md?
> 
> I had the same thing, until i ran the last step - the "docker exec..." one. Also: #9675 - you might have to actually run the migration play twice.

I did complete the last step. I completed all the steps*. **I am only asking WHICH PATH do i run the server from - can I pls get a straight answer to that?** It can't be that I have to run `docker exec tools_awx_1 make clean-ui ui-devel` every time I want to start the server, especially since the purpose is to do away with docker.

*Had to run some things twice (for example, step 2 hangs bc the script cannot modify the hosts file, so it finds nothing at `awx:8043` and keeps trying to connect to it)

**Comment by gaia** [comment]
this is what i get after i finish the 3rd step: 
![image](https://user-images.githubusercontent.com/87547/112410556-9a086c80-8cd8-11eb-8a70-469067f78e49.png)

if i cloned awx to `~/awx`, where do I serve the app from? I've been trying every path, and I either get a login screen with a little angry cartoon on it, or i get the

```
<% if (process.env.NODE_ENV === 'production') { %> <% } %> <% if (process.env.NODE_ENV === 'production') { %>
<% } else { %>
<% } %>
```

let me say it again, though IDK if this is to blame: I am using WSL.

**Comment by lemmy04** [comment]
- are you running WSL1 or WSL2?
- which linux distro are you using inside WSL?
- can that WSL session run linux containers?

**Comment by gaia** [comment]
> * are you running WSL1 or WSL2?
> * which linux distro are you using inside WSL?
> * can that WSL session run linux containers?

![image](https://user-images.githubusercontent.com/87547/112506464-0623b880-8d4b-11eb-809f-73aaba9de9cd.png)

Minikube on WSL is funky. It seems that kubernetes will be easier as there is an official method to enable them:
https://kubernetes.io/blog/2020/05/21/wsl-docker-kubernetes-on-the-windows-desktop/

I got kubernetes working

![image](https://user-images.githubusercontent.com/87547/112516749-d4afea80-8d54-11eb-9280-c2af23a8297c.png)

When I ask where to run the server from, I meant to run the server via npm serve or python3 http.server. If it runs inside a container, the question is how do i start the container after migration?

thanks!
