### ISSUE TITLE
Running 18.0.0 in local docker with migrated data from 17.1.0: migration script didn't wait long enough for postgres to start

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx#9675]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I tried to migrate the database from my docker based 17.1.0 AWX instance into the news 18.0 following the instructions in https://github.com/ansible/awx/blob/devel/tools/docker-compose/docs/data_migration.md but at the end of the play this happened:

TASK [migrate : Restore to new postgres container] *****************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "COMPOSE_PROJECT_NAME=tools docker-compose -f /home/mathias/work/ansible/awx/tools/docker-compose/ansible/../_sources/docker-compose.yml exec -T postgres psql -U awx -d awx -p 5432 < awx_dump.sql\n", "delta": "0:00:01.240442", "end": "2021-03-24 13:36:12.312124", "msg": "non-zero return code", "rc": 1, "start": "2021-03-24 13:36:11.071682", "stderr": "psql: error: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket \"/var/run/postgresql/.s.PGSQL.5432\"?\nread unix @->/var/run/docker.sock: read: connection reset by peer", "stderr_lines": ["psql: error: could not connect to server: No such file or directory", "\tIs the server running locally and accepting", "\tconnections on Unix domain socket \"/var/run/postgresql/.s.PGSQL.5432\"?", "read unix @->/var/run/docker.sock: read: connection reset by peer"], "stdout": "", "stdout_lines": []}

Running the same playbook a second time succeeded - seems that the "wait for postgres to initialize" task doesn't wait long enough.

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.19
* Operating System: openSUSE Leap 15.2
* Web Browser: Firefox + Chromium

##### STEPS TO REPRODUCE

- stopped my regular awx instance
- copied the pgdata folder of my database to my test system
- ran the migrate.yml playbook as instructed on the URL above

##### EXPECTED RESULTS

I expected it to work...

##### ACTUAL RESULTS
see above: the first time around the postgres container wasn't running yet.
Had to run it a second time, that time around the database was up and the data got imported.

##### ADDITIONAL INFORMATION

my test system is a intel core 5 with 16 gig ram and SSD disks...

**Comment by TheRealHaoLiu** [comment]
From the brief look at this issue `psql: error: could not connect to server` it sounds like postgres is not up and running yet 

In the playbook we have a configurable wait time for how long we wait for postgres to come up

If you are still having problem migrating AWX to newer version please open a new issue
