### ISSUE TITLE
Regression: Running 18.0.0 on docker: no obvious way to use own certificate instead of the self signed one

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx#9677]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I've installed 18.0.0 with migrated data from 17.1.0 in docker as described in https://github.com/ansible/awx/blob/devel/tools/docker-compose/docs/data_migration.md.
Accessing the tower url on my test host gives me certificate warnings, and since my local intranet uses HSTS I can't add an exception - hence no tests.

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.19
* Operating System: openSUSE Leap 15.2
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Install AWX 18.0.0 in docker as described in the documentation, with the variables in my inventory to point at my local certificats the way it used to work in 17.1.0

##### EXPECTED RESULTS

I expect https://tower_host:8043/ to use my certificate

##### ACTUAL RESULTS

the awx instance uses a self signed certificate

**Comment by shanemcd** [comment]
I could see us merging a PR for this, but I do not consider this a regression. The development environment was not intended to be a drop-in replacement for the local docker installer. If you are looking for a more complete solution, you should use the awx-operator.
