### ISSUE TITLE
Pause for user input as a step during workflow job

### ISSUE THREAD

**Issue by alexander-bauer** [ansible/awx#968]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - UI

##### SUMMARY
I have a number of patterns in my environment that are (Automated Step) -> (User Action or Input) -> (Automated Step). Some kinds of machine provisioning, for example, or user onboarding.

I would like to build these patterns as Workflow jobs, with a "Confirmation" or "Input" step in the middle, which waits forever for user input, and then is passed or failed, to trigger other steps in the workflow.

This would also let us capture processes that are *currently* manual, which we are looking to transform into automated processes as time goes on. It would be an extremely valuable capability that AWX does not currently offer us.

**Comment by steaksauce-** [comment]
As an alternative, would it be useful for a workflow to present a survey that is attached to a job template when the template is run? I can see that being useful. It might be worth adding a checkbox to the workflow to present the job's surveys or not.

**Comment by alexander-bauer** [comment]
@steaksauce- 
I think workflows should definitely present surveys, probably when the workflow is started. That is a separate problem I currently have, because some multi-step workflows (user onboarding, for example) rely on individual job templates that use surveys to prompt for their variables. Because workflows don't do this, I have to create a survey for that whole workflow that sets all the right variables, and this duplicates a lot of work for me, and then leaves multiple places for me to make changes in the future.

However, that's a separate issue for me -- sometimes my manual steps have to happen between automated jobs, and the workflow *still* needs to pause to wait for an operator. If that's accomplished by attaching a survey to the job that needs confirmation beforehand, I guess that could be made to work, but it would be a lot less elegant in my usecase than a "Confirm Pass/Fail" step in the workflow.

**Comment by jaredevantabor** [comment]
Setting workflow node parameters via surveys is a feature we're currently working on, the discussion is happening in https://github.com/ansible/awx/issues/169. I'm going to close this ticket, and if 169 doesn't address your needs, feel free to ping me and I'll re-open this.
