### ISSUE TITLE
AWX is listening on 0.0.0.0 when the docs say localhost

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx#9680]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

When installing AWX < 18.0.0 in a local docker setup it was possible to specify the listen address. This is not possible anymore (or not documented).
Also: AWX is listening on 0.0.0.0 instead of 127.0.0.1 as it says in the docs.

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.19

##### STEPS TO REPRODUCE

Install 18.0.0 in docker as described in the docs

##### EXPECTED RESULTS

I'd expect AWX on https://localhost:8043 as documented

##### ACTUAL RESULTS

awx is on https://0.0.0.0 on over a hundred different ports which might actually be in use by other services.

**Comment by ryanpetrello** [comment]
Hey @lemmy04,

The docker-compose method outlined at https://github.com/ansible/awx/tree/devel/tools/docker-compose is an environment the AWX maintainers also use as a development environment, and (by default) it exposes a port range used by an interactive debugger we utilize.  We could maybe come up with a way to turn off this behavior by default.

**Comment by shanemcd** [comment]
Personal opinion: I dont like the idea of us trying to make our development environment more friendly for people trying to use it in production. Don't do that.

**Comment by ryanpetrello** [comment]
@lemmy04,

If you want to change the behavior in your environment, the file you'll want to modify is here:

https://github.com/ansible/awx/blob/devel/tools/docker-compose/ansible/roles/sources/templates/docker-compose.yml.j2
