### ISSUE TITLE
[ui_next] Add testability- Filter by Job Type/Status In Dashboard and Jobs List

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#9681]
ISSUE TYPE
Task

SUMMARY
This task ticket tracks the work to add testability to the filter by Job Type/Status In the Dashboard Recent Jobs List and the Jobs Tab.

**Comment by tiagodread** [comment]
Each option in filter by status has IDs.

![image](https://user-images.githubusercontent.com/12464858/115310351-0e052b80-a144-11eb-8043-bfbdfaf9dea4.png)
