### ISSUE TITLE
Running Ad-hoc command through shell module is not executing against all given hosts

### ISSUE THREAD

**Issue by prantikb** [ansible/awx#9685]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When running an ad-hoc command (e.g. hostname) using the shell module against an inventory's hosts, it seems the command is executing only against a single host. However, the command is running properly when ran as tasks within a playbook. 

e.g. running hostname using the shell module as an ad-hoc command against 192.168.100.112 and 192.168.100.113 is producing the following output.
```
No config file found; using defaults
SSH password: 
192.168.100.112 | CHANGED | rc=0 >>
ansible-target-1
192.168.100.113 | CHANGED | rc=0 >>
ansible-target-1
```
The output when ran against the same set of hosts (192.168.100.112 and 192.168.100.113) through a playbook task:
Playbook Tasks:
```
  - name: Test running a command on Linux
    shell:
      hostname
    register: cmd_output
    changed_when: false
    
  - debug:
      var: cmd_output
```
Output:
```
ok: [192.168.100.112] => {
    "cmd_output": {
        "changed": false,
        "cmd": "hostname",
        "delta": "0:00:00.006624",
        "end": "2021-03-24 12:32:21.732695",
        "failed": false,
        "rc": 0,
        "start": "2021-03-24 12:32:21.726071",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "ansible-target-1",
        "stdout_lines": [
            "ansible-target-1"
        ]
    }
}
ok: [192.168.100.113] => {
    "cmd_output": {
        "changed": false,
        "cmd": "hostname",
        "delta": "0:00:00.004691",
        "end": "2021-03-24 12:32:21.732708",
        "failed": false,
        "rc": 0,
        "start": "2021-03-24 12:32:21.728017",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "ansible-target-2",
        "stdout_lines": [
            "ansible-target-2"
        ]
    }
}
```

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: On a Kubernetes Cluster using the Kubernetes Operator mentioned in the installation documentation
* Ansible version:  Default Execution Environment
* Operating System: Ubuntu 18.04.5 LTS
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Run Ad-hoc command using the shell module in AWX:
![image](https://user-images.githubusercontent.com/28568237/112347999-c652c780-8c9d-11eb-894d-e807a71c07a7.png)

##### EXPECTED RESULTS
The hostname command should return the hostname of the target against which it is being executed.
```
SSH password: 
192.168.100.113 | CHANGED | rc=0 >>
ansible-target-2
192.168.100.112 | CHANGED | rc=0 >>
ansible-target-1
```

##### ACTUAL RESULTS
The hostname of 192.168.100.112 is being returned for both hosts.
```
SSH password: 
192.168.100.113 | CHANGED | rc=0 >>
ansible-target-1
192.168.100.112 | CHANGED | rc=0 >>
ansible-target-1
```

##### ADDITIONAL INFORMATION

This is the first time I deployed AWX on a Kubernetes cluster using the operator. Please suggest if there is any settings which may need to be modified or if any specific logs are needed to debug this issue further.

**Comment by shanemcd** [comment]
@prantikb Would it be possible for you to pop open the network tab in your dev tools and paste the payload for the POST to `/api/v2/ad_hoc_commands`

**Comment by prantikb** [comment]
@shanemcd Sure. Have copied the request payload below. Please let me know if this is what you are looking for.

`{"credential":3,"limit":"192.168.100.112, 192.168.100.113","module_args":"hostname","verbosity":"0","forks":0,"diff_mode":false,"become_enabled":"","module_name":"shell","extra_vars":"---","job_type":"run"}`

**Comment by jakemcdermott** [comment]
> 192.168.100.112, 192.168.100.113

Note: relabeling as API. As far as I can tell this would be the expected host list string sent from the client

**Comment by shanemcd** [comment]
Interesting note: I've been able to reproduce this, but only when the AWX is deployed via the Operator. I don't see this in the dev env.
