### ISSUE TITLE
Windows collection not included in default EE

### ISSUE THREAD

**Issue by menjaben** [ansible/awx#9692]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
(Apologies if "Bug Report" is not the best description of this issue)

Hello, I'm probably one of very few who will have this issue, but it seems the default awx-ee image installed with 18.0.0 does not contain the ansible.windows collection. I've tried (and failed) to build a custom EE using ansible-builder and listing the collection in requirements.yml, but I noticed in issue #7058 that the goal of the default EE was to include collections available in previous releases (currently running 14.0.0 in production without this issue). If your recommendation is to build the EE then I will figure it out, but I would like to see this included by default if possible. I understand if automating Windows with Ansible is not a very common use case, and if this is low priority. 🙂 

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: awx-operator (using microk8s)
* Operating System: Ubuntu 18.04

##### STEPS TO REPRODUCE

Running any playbook that includes a module in the ansible.windows collection (e.g. win_ping)

##### EXPECTED RESULTS

Module to work as it has in previous releases.

##### ACTUAL RESULTS

`{
  "msg": "The module win_ping was redirected to ansible.windows.win_ping, which could not be loaded.",
  "_ansible_no_log": false
}`

**Comment by shanemcd** [comment]
Fixed by https://github.com/ansible/awx-ee/pull/51. Will be in the default EE for the next AWX release.
