### ISSUE TITLE
[17.0.1] - Multiple choice survey fields are auto populated with the first item in the dropdown list

### ISSUE THREAD

**Issue by roddick-mark** [ansible/awx#9694]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Multiple choice survey fields are auto populated with the first item in the dropdown list.
Before the UI change if the default value was blank, the field wasn't auto populated. This made it easier to see what questions you have answered and what you have not.

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.17
* Operating System: RHEL7
* Web Browser: Edge

##### STEPS TO REPRODUCE

Create a survey with a multiple choice question.

##### EXPECTED RESULTS

Default empty:

<img width="681" alt="Screenshot 2021-03-25 at 09 57 07" src="https://user-images.githubusercontent.com/71375821/112454444-97495e00-8d50-11eb-9e4c-3419b2fd7872.png">

##### ACTUAL RESULTS

Default auto populated:

<img width="836" alt="Screenshot 2021-03-25 at 09 52 05" src="https://user-images.githubusercontent.com/71375821/112454052-34f05d80-8d50-11eb-9f1a-f0883feba3cd.png">

##### ADDITIONAL INFORMATION

**Comment by mabashian** [comment]
https://github.com/ansible/awx/issues/10128 is something that we should fix at the same time. (single select)

**Comment by mabashian** [comment]
Lets make sure that we're not forcing a user to select a value when the question is not required.

**Comment by azrdev** [comment]
apparently this was fixed in https://github.com/ansible/awx/pull/10490/commits/560b4ebf71b1b787126bdc4513a6f4287ce21a98 as part of #10490 and therefore in 19.2.2 and 19.3.0
