### ISSUE TITLE
Wrong prefix for Docker volumes

### ISSUE THREAD

**Issue by dhoppe** [ansible/awx#9695]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

The Ansible playbook ```migrate.yml``` creates Docker volumes with the prefix ```tools_```. However, when the command ```make docker-compose``` is executed, Docker volumes with the prefix ```sources_``` are created. 

##### ENVIRONMENT

* AWX version: 18.0.0
* AWX install method: docker for mac
* Ansible version:  2.10.7
* Operating System: macOS Catalina (10.15.7)
* Web Browser: Safari

##### STEPS TO REPRODUCE

Migrate PostgreSQL data:
```
$ ansible-playbook  -i tools/docker-compose/inventory tools/docker-compose/ansible/migrate.yml -e "migrate_local_docker=true" -e "postgres_data_dir=~/.awx/pgdocker" -e "old_docker_compose_dir=~/.awx/awxcompose"
```

Build Docker image:
```
$ make docker-compose-build
$ make docker-compose
$ docker exec tools_awx_1 make clean-ui ui-devel
```

##### EXPECTED RESULTS

$ docker volume ls
DRIVER    VOLUME NAME
local     awxcompose_rsyslog-config
local     awxcompose_rsyslog-socket
local     awxcompose_supervisor-socket
local     tools_awx_db
local     tools_receptor_1
local     tools_redis_socket_1

##### ACTUAL RESULTS

$ docker volume ls
DRIVER    VOLUME NAME
local     awxcompose_rsyslog-config
local     awxcompose_rsyslog-socket
local     awxcompose_supervisor-socket
local     sources_awx_db
local     sources_receptor_1
local     sources_redis_socket_1
local     tools_awx_db
local     tools_receptor_1
local     tools_redis_socket_1

##### ADDITIONAL INFORMATION

It is necessary to set a custom name for Docker volumes.

```
$ colordiff -Naur docker-compose.yml /tmp/docker-compose.yml
--- docker-compose.yml	2021-03-25 12:13:01.000000000 +0100
+++ /tmp/docker-compose.yml	2021-03-25 11:56:31.000000000 +0100
@@ -65,5 +65,8 @@
       - "awx_db:/var/lib/postgresql/data"
 volumes:
   awx_db:
+    name: tools_awx_db
   receptor_1:
+    name: tools_receptor_1
   redis_socket_1:
+    name: tools_redis_socket_1
```

**Comment by shanemcd** [comment]
Merging your PR. Thanks.
