### ISSUE TITLE
error when i try to use a  developped collection

### ISSUE THREAD

**Issue by abdel-ops** [ansible/awx#9698]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux, docker for mac, boot2docker
* Ansible version:  2.10.7
* Operating System: Linux centos 
* Web Browser:

##### STEPS TO REPRODUCE

developp collection , 

##### EXPECTED RESULTS

use lookup plugins

##### ACTUAL RESULTS
collection loaded but the playbook doesn't found the plugins 

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/60286045/112482249-24ec7400-8d78-11eb-85e0-42e71ac50064.png)

![image](https://user-images.githubusercontent.com/60286045/112482855-c4aa0200-8d78-11eb-8103-562e0056db2d.png)

i try both paths for the lookup :
![image](https://user-images.githubusercontent.com/60286045/112483014-ec00cf00-8d78-11eb-82dd-3419aafe769d.png)

and both give me the same error message 

![image](https://user-images.githubusercontent.com/60286045/112483147-0cc92480-8d79-11eb-866f-5778186482d3.png)

**Comment by ryanpetrello** [comment]
Hey @abdel-ops,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by abdel-ops** [comment]
Hello, thanks for the answer
the goal from my issue is to mention that i when i use awx 17.0.1 to launch plugin from a collection not in core ansible, it doesn't work as it suppose to be. 
i thought that it's awx bug .
