### ISSUE TITLE
issue running the install playbook on fedora 26

### ISSUE THREAD

**Issue by AlexGluck** [ansible/awx#97]
### Summary
Selinux error when install playbook on fedora 26.
SELinux is preventing chown from 'read' accesses on the directory pgdocker.

### Environment

* Operating System: Fedora 26 workstation

### Steps To Reproduce:
1. Install fedora 26 workstation
2. `dnf install -y docker git`
3. Enable selinux enforcing active
4.
```
cd /home/$USER/Downloads/
git clone https://github.com/ansible/awx.git
cd awx/installer
ansible-playbook -i inventory install.yml
```
### Expected Results:
Installed Ansible AWX

### Actual Results:
SELinux is preventing chown from 'read' accesses on the directory pgdocker.

### Additional Information:
More info in bugtracker
https://bugzilla.redhat.com/show_bug.cgi?id=1489972

**Comment by matburt** [comment]
Hi @AlexGluck ... if that directory doesn't work for you then you can select another directory for postgres docker persistence. The installer inventory file is meant to be an example and modified to suit your system.

**Comment by AlexGluck** [comment]
@matburt another directory in /home/$USER or /var/lib/ too not working. For testing i look into playbook task after that disable selinux, reboot laptop, install awx normally. On fedora your playbook does not working properly.
