### ISSUE TITLE
[ui-next] Add testability for JT survey prompt on launch modal

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#9702]
Testability needs to be added for the modal that appears when a JT has a survey and the user is prompted for variables on launch:
![image](https://user-images.githubusercontent.com/63685497/112496924-84885680-8d5b-11eb-84fa-29483f81c3ad.png)
![image](https://user-images.githubusercontent.com/63685497/112496965-8c47fb00-8d5b-11eb-81ff-edbe4b7b1019.png)

**Comment by tiagodread** [comment]
Closing to keep track on https://github.com/ansible/awx/issues/10241
