### ISSUE TITLE
Unable to cancel job - method POST not allowed

### ISSUE THREAD

**Issue by phemmer** [ansible/awx#9714]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I had an inventory sync job that was stuck. Upon trying to cancel it, I got an error saying `Method "POST" not allowed`

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: minishift
* Ansible version:  
* Operating System: Debian 10
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Get a stuck job?
2. Try to cancel job.

##### EXPECTED RESULTS

job to cancel

##### ACTUAL RESULTS

```
POST /api/v2/inventory_updates/2/cancel/ 405
Method "POST" not allowed.
```
![image](https://user-images.githubusercontent.com/1826947/112569343-630a8780-8dba-11eb-8d24-6a5b8931e631.png)

**Comment by nixocio** [comment]
I believe this issue was addressed in the last couple of days. Fix present on devel.  See: https://github.com/ansible/awx/pull/9659

**Comment by shanemcd** [comment]
Should be fixed in the PR mentioned above, and will be in the next version of AWX.
