### ISSUE TITLE
Reopen please: Migrating Data from Local Docker - Not connecting to awx:8013

### ISSUE THREAD

**Issue by stefanpinter** [ansible/awx#9717]
@ryanpetrello 
Hi! I cloned 18.0 now and I have the same problem. I guess it is because it can't start a container called "awx" because there is already a container called "awx_tools_1" that is listening on 8013...

_Originally posted by @stefanpinter in https://github.com/ansible/awx/issues/9540#issuecomment-808099539_

**Comment by ryanpetrello** [comment]
see: https://github.com/ansible/awx/issues/9540#issuecomment-808210417
