### ISSUE TITLE
Add screen to represent EE unified job templates endpoint

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#9723]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add screen to represent EE unified job templates endpoint.
 
See:
![image (12)](https://user-images.githubusercontent.com/9053044/112685919-9c3f0800-8e4b-11eb-938d-d5471de4cc7c.png)

**Comment by tiagodread** [comment]
PR merged and test in place
