### ISSUE TITLE
Slack private channel (channel_not_found)

### ISSUE THREAD

**Issue by nickjmv** [ansible/awx#9727]
I'm trying to add the Slack notification via the new Slack apps way. When trying this on public channels it is working as expected. While trying this on a private channel I get the following error in my awx_task container:

`2021-03-27 14:07:11,709 ERROR    awx.main.tasks Send Notification Failed Slack Notification unable to send it-infra: Tower Notification Test 36 https://awx.myorgurl.com (channel_not_found)
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 336, in send_notifications
    sent = notification.notification_template.send(notification.subject, notification.body)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/notifications.py", line 194, in send
    return backend_obj.send_messages([notification_obj])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/notifications/slack_backend.py", line 56, in send_messages
    raise RuntimeError("Slack Notification unable to send {}: {} ({})".format(r, m.subject, ret['error']))
RuntimeError: Slack Notification unable to send it-infra: Tower Notification Test 36 https://awx.myorgurl.com (channel_not_found)`

Is this intended? Because while using the old slack way and create a standalone bot I am able to send to this private channel.

I have to following OAuth permissions on my Slack app:

- chat:write
- chat:write.public
- groups:history
- groups:read
- groups:write
- incoming-webhook

Is there something I am missing for this to work?

**Comment by shanemcd** [comment]
> `(channel_not_found)`

Sounds like a permissions issue with the token you generated. Not something we can help with.

**Comment by josem-vexcel** [comment]
It works for public channels but does not work for private channels.
what do you mean by "permissions issue" @shanemcd?

**Comment by vadirajks** [comment]
@josem-vexcel i had the same problem. Follow this https://stackoverflow.com/questions/60198159/slack-api-conversations-history-returns-error-not-in-channel to invite bot to the private channel.
