### ISSUE TITLE
Password from install procedure does not work

### ISSUE THREAD

**Issue by crouthamela** [ansible/awx#9728]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Password retrieved during install procedure does not work when attempting to login to web interface.

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: minikube
* Ansible version:  2.9.19
* Operating System: Debian 10
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Follow install procedure from INSTALL.md
2. Perform the password retrieval step: `minikube kubectl -- get secret awx-admin-password -o jsonpath='{.data.password}' | base64 --decode`
3. Use the provided password to attempt to login

##### EXPECTED RESULTS

Login to process and be presented with the AWX GUI.

##### ACTUAL RESULTS

Login error: `There was a problem signing in. Please try again.`

**Comment by shanemcd** [comment]
I have not seen any other reports of this. Can you try again and let me know if the problem is still happening?

**Comment by crouthamela** [comment]
I took a deeper look and oddly enough I tracked this down to an issue with nginx. Thanks for checking in on this.
