### ISSUE TITLE
[17.1.0] awx will not read and process requirements.yml

### ISSUE THREAD

**Issue by ronjarrell** [ansible/awx#9730]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

I set up a 17.1.0 server using a repo that previous worked in 10.0.0.  Awx pulls the right repo associated with the project.  If I get into the docker container and look in /var/lib/awx/projects/_10__my_project I find the contents of the repo.  Repo includes a "roles" directory, which is there.  In the "roles' directory is a requirements.yml file (which ansible-galaxy is happy to process if I run it on my desktop).  

If I look into the job output from the sync, I see:
```PLAY [Install content with ansible-galaxy command if necessary] ****************
META: ran handlers
TASK [detect roles/requirements.(yml/yaml)] ************************************
task path: /tmp/bwrap_28_tyvetkqk/awx_28_b_92m6jo/project/project_update.yml:162
skipping: [localhost] => (item={'ext': '.yml'})  => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "ext": ".yml"
    },
    "skip_reason": "Conditional result was False"
}
skipping: [localhost] => (item={'ext': '.yaml'})  => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "ext": ".yaml"
    },
    "skip_reason": "Conditional result was False"
}
```

If I then run a job against that inventory, it complains none of the roles are there.  In 10 ISTR it wouldn't pull the roles on an update of the project, but would when it was called by a template, but not anymore it seems.  The project is set for update revision on launch.

##### ENVIRONMENT
* AWX version: 17.1.0
* AWX install method: docker on linux
* Ansible version:   2.9.18
* Operating System: centos7 (client mac osx).
* Web Browser: chrome and safari

##### STEPS TO REPRODUCE

Create project to pull repo that includes roles/requirements.yml

##### EXPECTED RESULTS

All my other repos to be pulled in.
##### ACTUAL RESULTS

None of my repos are pulled in.

**Comment by abcqwertz** [comment]
Hi,
I had the same problem on the same version. Did you generate preload data? If not, the installer won't generate the default Ansible Galaxy API token. To solve that I created a new credential of type ``Ansible Galaxy/Automation Hub API Token`` and the Galaxy Server URL ``https://galaxy.ansible.com``. Assign this credential to your organization. After that I was able to download roles and collections from Galaxy via requirements.yml/yaml

Edit: I also meant requirements.yml/yaml

**Comment by shanemcd** [comment]
You say `requirements.txt` multiple times, but did you mean `requirements.yml`?

**Comment by ronjarrell** [comment]
> You say `requirements.txt` multiple times, but did you mean `requirements.yml`?

Yea, sorry, late night brain failure.  The file is definitely requirements.yml, and I updated the original comments

**Comment by ronjarrell** [comment]
> Hi,
> I had the same problem on the same version. Did you generate preload data? If not, the installer won't generate the default Ansible Galaxy API token. To solve that I created a new credential of type `Ansible Galaxy/Automation Hub API Token` and the Galaxy Server URL `https://galaxy.ansible.com`. Assign this credential to your organization. After that I was able to download roles and collections from Galaxy via requirements.txt

Thanks for the hint, there are 2 galaxy roles in there that I'll keep this in mind for.  The other dozen or so I just references to github.com repos of our that aren't on galaxy.  I don't think this is the same problem, because I hunted down the source to project_update.yml that awx is running, and that code around line 162 is literally just checking to see if the file requirements.yml or the file requirements.yaml exist, and if they do, process them, otherwise skip on past, so for some reason it's not even seeing the file.

**Comment by ronjarrell** [comment]
Any thoughts how to track this down?  My first thought is that there's a variable set wrong and project_update.yml is looking at the wrong base dir.  I know I had to use the api to set the location of my inventory file because when I went to the inventory file pulldown it only listed the files in the root, and wouldn't let me type in "inventories/projectname" which is the inventory directory for that project and has the gcp.yml files for the auto-inventory.  So hopefully it's not trying to look for the requirements.yml file in that directory?

**Comment by abcqwertz** [comment]
According to the tower docs (https://docs.ansible.com/ansible-tower/latest/html/userguide/projects.html) this command is executed, when syncing projects with requirments:
```
ansible-galaxy role install -r roles/requirements.yml -p <project-specific cache location>/requirements_roles -vvv
```
Can you try that and paste the output here? Also how does your requirements.yml file look like?
For myself I only use collections from Ansible Galaxy in a folder collections/requirements.yml, which works fine.

**Comment by ronjarrell** [comment]
The problem is we never get *to* trying the ansible-galaxy command because it swears the requirements.yml file isn't there.  The debug snippet above is from project_update.yml, the code in question is below:
```
- block:
        - name: detect roles/requirements.(yml/yaml)
          stat:
            path: "{{project_path|quote}}/roles/requirements{{ item.ext }}
"
          with_items: "{{ yaml_exts }}"
          register: doesRequirementsExist
        - name: fetch galaxy roles from requirements.(yml/yaml)
          command: >
            ansible-galaxy role install -r {{ item.stat.path }}
            --roles-path {{projects_root}}/.__awx_cache/{{local_path}}/sta
ge/requirements_roles
            {{ ' -' + 'v' * ansible_verbosity if ansible_verbosity else ''
 }}
 args:
            chdir: "{{project_path|quote}}"
          register: galaxy_result
          with_items: "{{ doesRequirementsExist.results }}"
          when: item.stat.exists
          changed_when: "'was installed successfully' in galaxy_result.std
out"
```

It's looking to see if there's a requirements.yml or a requiremens.yaml file, and if so, ansible-galaxy them.  It's registering false for both, despite the fact that if I go to /var/lib/awx/_9__myproject/roles there's a requirements.yml file there.

**Comment by shanemcd** [comment]
Can you try this on AWX 19?

**Comment by ronjarrell** [comment]
Not anytime soon, jumping to the kubernetes installation isn’t something
 to do, we’re happy with the docker container version.

On Wed, Apr 7, 2021 at 6:49 PM Shane McDonald ***@***.***>
wrote:

> ------------------------------
> *[External Email: Use caution with links and attachments]*
> ------------------------------
>
> Can you try this on AWX 19?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ansible_awx_issues_9730-23issuecomment-2D815310755&d=DwMCaQ&c=sSVGO1PAPMGyxGLZsRfH-A&r=9lyV7TykEltBoVDCdAir9kaf0RSyx00RmGYd-7qRq8Y&m=RUeZglczD3ZDx2W--RxZSKivem6ylccuOzZc1TLofqo&s=BZQCULaUeJ9M6cTjOW8PsgGcA659dX15mPXIWlEqtPo&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AMTZOM4VUIWUJSTZ5AZQE73THTOPLANCNFSM4Z67AREA&d=DwMCaQ&c=sSVGO1PAPMGyxGLZsRfH-A&r=9lyV7TykEltBoVDCdAir9kaf0RSyx00RmGYd-7qRq8Y&m=RUeZglczD3ZDx2W--RxZSKivem6ylccuOzZc1TLofqo&s=5i39Re9677s0blz-Luuy8nSbiZeh8vxLmnDCWF6YvRE&e=>
> .
>
-- 

*Ron Jarrell*
*Software Engineer, Exchange Infrastructure*
***@***.***

*The information contained in this email is confidential together with any
information contained in any attachments to this email. You should not
disclose, give or copy the information to anyone other than the person(s)
who are named or referenced above. The law may also protect the information
as a legally privileged document and/or as a copyright work. If you have
received this email and you are not the person named or referenced above,
please let the sender know and delete the email from your computer (and, if
applicable, your computer system(s) and server(s)). For information about
how we process personal data and monitor communications please see our
**privacy
policy <https://block.one/privacy-policy/> and for terms of use please see
our terms of use here. <https://block.one/terms-of-use/>*

**Comment by shanemcd** [comment]
We don’t support older versions so I’m going to close this. Open another issues if you experience this after upgrading.

**Comment by balonik** [comment]
@ronjarrell see https://github.com/ansible/awx/issues/8341#issuecomment-707310633

**Comment by ckozler** [comment]
@shanemcd this is happening for me as well on 19. Should I open a new issue? Same problem, swears requirements.yml is not there. Source repo sync just skips over it saying conditional was false and my individual job runs don't show it trying to pull in collections from galaxy

**Comment by ckozler** [comment]
@shanemcd  Still the same issue here too and upgraded on 19.1. Seems to be reported here has well - #10236 - is there something non obvious that needs to be configured elsewhere?

**Comment by ckozler** [comment]
For anyone else who reads this - this is how I fixed it: Copy the default "Ansible Galaxy" credential that you cannot edit from the UI. Go to galaxy.ansible.com, login/link GH account, and then get your API token from your preferences in the top right. Copy that, edit the copied credential in AWX, add the API token you copied, assign your org to the token, then go to organizations and change the credentials to that of your copy. This worked for me

**Comment by FredPocai** [comment]
This worked for me as well -- it will not look unless you have a set of credentials configured and assigned to the organization.  

https://github.com/ansible/awx/blob/fb7c827bff6462120385be321f568ccc32364af6/awx/playbooks/project_update.yml#L220

https://github.com/ansible/awx/blob/467a37f8fe6742e81e2b356078938a78961c302b/awx/main/tasks.py#L2116

https://github.com/ansible/awx/blob/467a37f8fe6742e81e2b356078938a78961c302b/awx/main/tasks.py#L2099

**Comment by jorgemarti** [comment]
> 

I'm afraid this solution didn't work for me in 17.1.0 or maybe I didn't follow correctly the steps indicated here. If tried creating credentials pointing both to galaxy.ansible.com  and using _Galaxy Server URL_, _AUTH SEVER URL_ and _token_ from Automation Hub , but the project_update.yml playbook always skips the collections/roles sync. 

And I have checked that both project and credentials are configured for the same organization. Any clues? Many thanks!

**Comment by jorgemarti** [comment]
> > 
> 
> I'm afraid this solution didn't work for me in 17.1.0 or maybe I didn't follow correctly the steps indicated here. If tried creating credentials pointing both to galaxy.ansible.com and using _Galaxy Server URL_, _AUTH SEVER URL_ and _token_ from Automation Hub , but the project_update.yml playbook always skips the collections/roles sync.
> 
> And I have checked that both project and credentials are configured for the same organization. Any clues? Many thanks!

Ok, after asking a colleague and get a second pair of eyes, we found out that the credential had to be assigned to the Organization in the **Access** section, by editing the organization. Thanks for the tip.

**Comment by LennyPedersen-FoodTech** [comment]
> For anyone else who reads this - this is how I fixed it: Copy the default "Ansible Galaxy" credential that you cannot edit from the UI. Go to galaxy.ansible.com, login/link GH account, and then get your API token from your preferences in the top right. Copy that, edit the copied credential in AWX, add the API token you copied, assign your org to the token, then go to organizations and change the credentials to that of your copy. This worked for me

Thanks! This did it!
