### ISSUE TITLE
Not able to execute playbooks with the latest version of AWX(18.0.0) with minikube

### ISSUE THREAD

**Issue by dimovstanimir** [ansible/awx#9734]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I am not able to execute playbooks successfully with AWX release 18.0.0

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: minikube
* Ansible version:  2.9.13
* Operating System: Ubuntu
* Web Browser: ALL

![image](https://user-images.githubusercontent.com/29769671/112853306-62713a00-90b5-11eb-8afd-ea37372994c8.png)

The same playbook worked with all previous AWX releases.

Playbook content:
---
- name: "Chocolatey"
  hosts: Windows
  tasks:
    - name: Install chocolatey
      win_chocolatey:
          name:
           - chocolatey
           - chocolatey-core.extension
          state: present
    - name: Refresh environment
      win_shell: |
        refreshenv

**Comment by shanemcd** [comment]
The default Execution Environment is using Ansible 2.11. The module you are trying to use has been moved into a collection.

You need to build a custom Execution Environment that contains https://galaxy.ansible.com/chocolatey/chocolatey.

For steps on building a custom EE, see https://ansible-builder.readthedocs.io/en/latest/index.html

... or you can build your EE on top of 2.9 using quay.io/ansible/ansible-runner:stable-2.9-devel

Instructions for overriding the base image are here: https://ansible-builder.readthedocs.io/en/latest/usage.html#build-arg

**Comment by dimovstanimir** [comment]
> The default Execution Environment is using Ansible 2.11. The module you are trying to use has been moved into a collection.
> 
> You need to build a custom Execution Environment that contains https://galaxy.ansible.com/chocolatey/chocolatey.
> 
> For steps on building a custom EE, see https://ansible-builder.readthedocs.io/en/latest/index.html
> 
> ... or you can build your EE on top of 2.9 using quay.io/ansible/ansible-runner:stable-2.9-devel
> 
> Instructions for overriding the base image are here: https://ansible-builder.readthedocs.io/en/latest/usage.html#build-arg

Thanks @shanemcd but I am wondering why would Ansible make this step to make our lives harder. Now I have to go and learn from now on how should I be able to adapt to their changes and start thinking of how to build my playbooks from now on in a new way. Why do people tend to break things that are working perfectly? :(

**Comment by dimovstanimir** [comment]
> The default Execution Environment is using Ansible 2.11. The module you are trying to use has been moved into a collection.
> 
> You need to build a custom Execution Environment that contains https://galaxy.ansible.com/chocolatey/chocolatey.
> 
> For steps on building a custom EE, see https://ansible-builder.readthedocs.io/en/latest/index.html
> 
> ... or you can build your EE on top of 2.9 using quay.io/ansible/ansible-runner:stable-2.9-devel
> 
> Instructions for overriding the base image are here: https://ansible-builder.readthedocs.io/en/latest/usage.html#build-arg

@shanemcd I created the file execution-environment.yml
dimov@vmeuwansm01:~/test_ee$ **cat execution-environment.yml**
**---
version: 1
dependencies:
  galaxy: requirements.yml**

and I also created the file requirements.yml

dimov@vmeuwansm01:~/test_ee$ **cat requirements.yml** 
collections:
- name: chocolatey.chocolatey

but when I try to build the EE I am getting the below error.

dimov@vmeuwansm01:~/test_ee$ **ansible-builder build --tag my-exec-env**
Running command:
  podman build -f context/Containerfile -t my-exec-env context

STEP 1: FROM quay.io/ansible/ansible-runner:devel AS galaxy
Getting image source signatures
Copying blob sha256:566dbb7b581329a558949d5db5bf737d7e41b96269bda5f4ba5e464708bfbac0
Copying blob sha256:735800ad2c761b160417d49a68d6bf6b073f0beb94cce6943437688204f0df6c
Copying blob sha256:14d5f30b982f58e13b8dbdbdc03b95cbb3bf54a809f39cf89503ffc9b257b5ef
Copying blob sha256:2e79ba35dea3ddc56817f530aaa79f25de9f4ffce9be50035faa0916767a7573
Copying blob sha256:8ed2739799b0d96ccb321458f5487e26631ea3d4ca73299599729bbaf8fec543
Copying blob sha256:b919b1324052f5b686e33dc7c938ec6e7efcf20c4519729806654c101c790070
Copying blob sha256:df25a42285a5f6f47f63f0062c01af56d141ec65e7a04adb2c205940549a2a31
Copying blob sha256:57793b171b09e0421a72bc051b578a73ba04653e9717c6764cf03f5eb6bbe27d
Copying blob sha256:ec548dcddf69195d7075bbdd87efdf0eaf50b55fa06a2e37803a80e32c8986de
Copying blob sha256:02971befe58f3614e78e8db27119eee71cdd0d1df9409379b7f850aa5aa5713b
Copying blob sha256:8a01c64abca558fd87b1a5cf870587643e8e03c6b863556c8c4b4595b6a1baa6
Copying blob sha256:1b6d5fd720d29f9cda2cb2d163a6b4b8d708f7f603b71f31c2abf24b7cf9d36c
Copying blob sha256:1dbcab28ce46b65c0174e5e82658492107396fead31e9144c343e6bc96e471c7
Copying config sha256:2d77013e8fc971be62290d90c4990ac721bdbc38bc2367f6f670619d2c536dd6
Writing manifest to image destination
Storing signatures
STEP 2: ARG ANSIBLE_GALAXY_CLI_COLLECTION_OPTS=
--> f206bd15fca
STEP 3: ADD _build /build
--> cb5c270a785
STEP 4: WORKDIR /build
--> 7b236e7ff9d
STEP 5: RUN ansible-galaxy role install -r requirements.yml --roles-path /usr/share/ansible/roles
Skipping install, no requirements found
--> 53d83dba2b9
STEP 6: RUN ansible-galaxy collection install $ANSIBLE_GALAXY_CLI_COLLECTION_OPTS -r requirements.yml --collections-path /usr/share/ansible/collections
Starting galaxy collection install process
Process install dependency map
ERROR! Error when getting available collection versions for chocolatey.chocolatey from default (https://galaxy.ansible.com/api/) (HTTP Code: 520, Message: Origin Error Code: Unknown)
Error: error building at STEP "RUN ansible-galaxy collection install $ANSIBLE_GALAXY_CLI_COLLECTION_OPTS -r requirements.yml --collections-path /usr/share/ansible/collections": error while running runtime: exit status 1

An error occured (rc=125), see output line(s) above for details.

Can you tell me what I might be missing. I filled the requirements.yml file like it is showed in the link for the choco collection.
I.e https://galaxy.ansible.com/chocolatey/chocolatey
![image](https://user-images.githubusercontent.com/29769671/113298666-bb82dd00-9304-11eb-90d1-4ab7df3e2dc8.png)

**Comment by dimovstanimir** [comment]
@shanemcd Is there a way to work with the latest Ansible AWX 18.0.0 but without the Execution Environments as it seems too complicated for me?
