### ISSUE TITLE
AWX 18.0.0: Inventory Source VMware vCenter doesn't work

### ISSUE THREAD

**Issue by dimatha** [ansible/awx#9746]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: kubernetes via awx operator 0.7.0
* Ansible version:  2.11.0b3.post0
* Operating System: 

##### STEPS TO REPRODUCE

1. Add an Inventory in AWX
2. Add Inventory Source as VMware vCenter + set appropriate credentials
3. Sync the inventory

##### EXPECTED RESULTS

Inventory synced from VMware vCenter

##### ACTUAL RESULTS

The error when triggered from the UI:

> ansible-inventory [core 2.11.0b3.post0] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
setting up inventory plugins
Skipping due to inventory source not existing or not being readable by the current user
auto declined parsing /runner/vmware_vm_inventory.yml as it did not pass its verify_file() method
[WARNING]: Unable to parse /runner/vmware_vm_inventory.yml as an inventory
source
ERROR! No inventory was parsed, please check your configuration and options.

##### ADDITIONAL INFORMATION

The inventory is running via built-in awx-ee container and it is expecting vmware_vm_inventory.yml file in /runner folder:

> ansible-inventory --list --export -i /runner/vmware_vm_inventory.yml --output /runner/artifacts/output.json --playbook-dir /runner

Where the actual data is stored in a tmp directory. The command below runs just fine in the container isolated dir (and the env vars are set accordingly from the json payload):

> /tmp/pdd_wrapper_33_b65zji3y/awx_33_zi5340pu$ ansible-inventory -i ./vmware_vm_inventory.yml --graph -vvvv

Assuming other external inventories are also affected. 
Similar issue https://github.com/ansible/awx/issues/9704
Potential fix WIP: https://github.com/ansible/awx/pull/9741

**Comment by shanemcd** [comment]
Can you try this again in AWX 19? We fixed some other problems related to inventories, this might work now.

**Comment by dimatha** [comment]
Hi @shanemcd ! 

Had some troubles with upgrading the operator. After upgrading the operator, it was throwing some errors while trying to update the postgress stateful set. 

> [installer : Create Database if no database is specified] *****************\r\ntask path: /opt/ansible/roles/installer/tasks/database_configuration.yml:67\nfatal: [localhos │
│ []: FAILED! => {\"changed\": false, \"error\": 422, \"msg\": \"Failed to apply object: b'{\\\"kind\\\":\\\"Status\\\",\\\"apiVersion\\\":\\\"v1\\\",\\\"metadata\\\":{},\\\"status\\\":\\\"Failure\\\",\\\"message\\\":\\\"StatefulSet.apps \\\\\\\\\\\"awx-postgres\\\\\\ ││ \\\\\" is invalid: spec: Forbidden: updates to statefulset spec for fields other 2021-04-08T10:46:45.740889916Z than \\\\'replicas\\\\', \\\\'template\\\\', and \\\\'updateStrategy\\\\' are forbidden\\\",\\\"reason\\\":\\\"Invalid\\\",\\\"details\\\":{\\\"name\\\":\ │
│ \\"awx-postgres\\\",\\\"group\\\":\\\"apps\\\",\\\"kind\\\":\\\"StatefulSet\\\",\\\"causes\\\":[{\\\"reason\\\":\\\"FieldValueForbidden\\\",\\\"message\\\":\\\"Forbidden: updates to statefulset spec for fields other than \\\\'replicas\\\\', \\\\'template\\\\', and \ ││ \\\'updateStrategy\\\\' are forbidden\\\",\\\"field\\\":\\\"spec\\\"}]},\\\"code\\\":422}\\\\n'\", \"reason\": \"Unprocessable Entity\", \"status\": 422}\n\r\nPLAY RECAP

Decided to delete the current AWX instance and redeploy with the new operator (kept the PV).
Current versions: operator - Devel; AWX - 19.0.0

Quick analyses. Now indeed it looks different! Had to change the EE in the sync task to "AWX EE 0.1.1" from Default.

Result: sync successful ! 

Thanks a lot for your quick help!

**Comment by wenottingham** [comment]
THanks for the confirmation!
