### ISSUE TITLE
Rsyslog Fails to Start due to Conflicting PID

### ISSUE THREAD

**Issue by james-crowley** [ansible/awx#9751]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
While bring up a docker-compose instance, rsyslog fails to start. The task container tries to restart the service but it keeps crashing over and over again. Thus causing the service to enter a fatal state. 

##### ENVIRONMENT
* AWX version: 17.1.0
* AWX install method: Docker-Compose on Linux
* Ansible version:  N/A
* Operating System: Ubuntu 20.04
* Web Browser: N/A

##### STEPS TO REPRODUCE

1. Checkout/Download the 17.1.0 Release
2. Customize your inventory file to force AWX to build the images
3. After images are built run the docker-compose file, `docker-compose up`

##### EXPECTED RESULTS

I expected rsyslog to start fine without issue. Seems like this issue was documented in #6794. In the logs of the user you can see the same issue about conflicting PIDs.

##### ACTUAL RESULTS

Logs from failed rsyslogd service.

```
web_1        | 2021-03-29 17:57:36,410 INFO exited: awx-rsyslogd (exit status 1; not expected)
web_1        | 2021-03-29 17:57:36,410 INFO exited: awx-rsyslogd (exit status 1; not expected)
web_1        | 2021-03-29 17:57:39,417 INFO spawned: 'awx-rsyslogd' with pid 122
web_1        | 2021-03-29 17:57:39,417 INFO spawned: 'awx-rsyslogd' with pid 122
web_1        | rsyslogd: pidfile '/var/run/awx-rsyslog/rsyslog.pid' and pid 122 already exist.
web_1        | If you want to run multiple instances of rsyslog, you need to specify
web_1        | different pid files for them (-i option).
web_1        | rsyslogd: run failed with error -3000 (see rsyslog.h or try https://www.rsyslog.com/e/3000 to learn what that number means)
```

##### ADDITIONAL INFORMATION

Doing what @ryanpetrello suggested in issue #6794, kind of worked but not for the reason that issue was closed/PR merged. 

Execting into the the web container, you can remove the file, `/var/run/awx-rsyslog/rsyslog.pid`. Once removed you then can issue, `supervisorctl -c /etc/supervisord.conf start tower-processes:awx-rsyslogd`, which restarts the rsyslog service. 

Once the service is running correctly, you can bring down the docker-compose instance and restart it. Upon restarting it rsyslog does come up fine. 

Maybe the issue has to do with permissions or the "magic" of using a docker volume instead of a bind mount?

**Comment by shanemcd** [comment]
@james-crowley The old docker-compose installer has been removed and is not something we will be providing fixes / updates for. Can you reproduce this on AWX 18?

**Comment by james-crowley** [comment]
@shanemcd I did see the removal of the local-docker install. But I happen to look at AWX the day before your AWX 18.0 release :joy: .

As for testing the issue on AWX 18, do you want me to build the containers and use the dev environment? At the moment I do not have an OCP cluster spun up. 

I can try to hack something together but I guess I see your point. If it is an issue with docker's volumes vs bind mount, there is not an install path that supports that anymore.

I figure the answer is no since you guys cut releases pretty quick, but do you ever backport fixes to older releases?
