### ISSUE TITLE
Remove isolated and controller nodes from the UI

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#9752]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Remove isolated and controller nodes to be shown on the UI.

See: https://github.com/ansible/awx/issues/8740

**Comment by unlikelyzero** [comment]
note: this is blocked until job settings related to isolated nodes are updated from the API

**Comment by unlikelyzero** [comment]
tests green and we have coverage in this area
