### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by dugs951** [ansible/awx#9757]
HI,
where i can found manual how install awx 18.0 on Ubuntu 20.04?
I never install minikube and it not working anymore.

**Comment by shanemcd** [comment]
For a quick guide: https://github.com/ansible/awx/blob/devel/INSTALL.md

More comprehensive information can be found at: https://github.com/ansible/awx-operator

If you need additional help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
