### ISSUE TITLE
Installation from packages/ no containers

### ISSUE THREAD

**Issue by KazimierzKurz** [ansible/awx#9761]
ISSUE TYPE

    Documentation

COMPONENT NAME

    Installer

SUMMARY

As supply chain attacks are common this days, installation by "downloading containers" with unknown dependencies and creator motivation is no longer option. In production environment all pieces of software should be reviewed, and using docker or kubernetes platform for such central tool like Ansible store is a thread making attack surface bugger than needed. 

It is also preferred that the database (if there is one) is installed or created on a separate host.

We have sound security reasons for this, and this is not a forum to challenge policies everyone should put in place this days.

It would be acceptable if this process was an Ansible play.
ENVIRONMENT

    AWX version: All
    AWX install method: no-containers (requesting direct host installation)
    Ansible version: Any
    Operating System: CentOS/RHEL/Debian/Slackware/Generic Linux istribution
    Web Browser: Any

STEPS TO REPRODUCE

Search for installation method that does not use container technologies.
EXPECTED RESULTS

Expect there to be documentation for non-container based installations.
ACTUAL RESULTS

No documentation found, not even googling.
ADDITIONAL INFORMATION

N/A

**Comment by egmar** [comment]
You can build your own image with `make Dockerfile` followed by `docker build`. The template for Dockerfile is in https://github.com/ansible/awx/blob/devel/tools/ansible/roles/dockerfile/templates/Dockerfile.j2 and you can review everything is used there.

**Comment by KazimierzKurz** [comment]
While it is clear we we can do it as this, it is still no documentation nor procedure.
Using docker is useful, but due to security consideration, not accessible for everyone.
I appreciate Your answer, but it is not resolution of the problem - it still installs components not related to AWX itself like helm, kubernetes etc making enormous attack space, and what is even worse, having to deploy such complicated things for something ( say...) simple as management portal for particular scripting thing. Particularly not everyone has resources and ability to run kubernetes nor docker, which is plain wrong to use in this case. Simple rule: not know - do not use.

I suppose it is just plain wrong approach ( however ruseful for developers in testing  who usually want to deploy something without knowledge how it works), specially if You are responsible for Operations aspect of things. 

Of course You may said: if You cannot use kubernetes - do not use AWX. If so - please put it as a simple statement at the headline page. Why not? If You do not see as limiting adoption of the tool, You can definitely do it.

**Comment by KazimierzKurz** [comment]
Maybe this is an answer - https://awx.wiki/installation

**Comment by shanemcd** [comment]
We have no plans to provide a non-containerized solution for AWX.
