### ISSUE TITLE
pg_dump included in awx_task/awx_web is old 9.2.23 incompatible

### ISSUE THREAD

**Issue by akcrisp** [ansible/awx#977]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Unable to dump postgres database because of a missing option.

The version of pg_dump on awx_task and awx_web is 9.2.23. There version with the postgres container is 9.6.6.

9.6.6 has a --dbname option which is missing from the 9.2.23 

##### ENVIRONMENT
* AWX version: 1.0.1.173
* AWX install method: docker on linux
* Ansible version:  2.4.2
* Operating System: RHEL 7.4
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create a playbook with task to backup db (using the settings obtained via awx-manage command)

``
- name: Perform a PostgreSQL dump.
  shell: "pg_dump --clean --create --host='{{ tower_db_settings.default.HOST }}' --port={{ tower_db_settings.default.PORT }} --username='{{ tower_db_settings.default.USER  }}' --dbname='{{ tower_db_settings.default.NAME }}' > tower.db"
  args:
    chdir: '{{ backup_tmp.rstrip("/") }}/{{ now }}/'
  environment:
    PGPASSWORD: "{{ tower_db_settings.default.PASSWORD }}"
  no_log: True
``

##### EXPECTED RESULTS

Backup to be dumped, no errors

##### ACTUAL RESULTS

fatal: [awx_task]: FAILED! => {"changed": true, "cmd": "pg_dump --clean --create --host='postgres' --port=5432 --username='awx' --dbname='awx' > tower.db", "delta": "0:00:00.248242", "end": "2018-01-12 13:57:38.853204", "msg": "non-zero return code", "rc": 1, "start": "2018-01-12 13:57:38.604962", "stderr": "pg_dump: unrecognized option '--dbname=awx'\nTry \"pg_dump --help\" for more information.", "stderr_lines": ["pg_dump: unrecognized option '--dbname=awx'", "Try \"pg_dump --help\" for more information."], "stdout": "", "stdout_lines": []}

**Comment by matburt** [comment]
I guess I'm surprised by this because we are installing the 9.6  yum repo here: https://github.com/ansible/awx/blob/devel/installer/image_build/templates/Dockerfile.j2#L32

Are we just not sourcing the right utils from the right repo?

**Comment by shanemcd** [comment]
We need to install the `postgresql96` package from the `pgdg96` repo. `postgresql` is pulled in from the centos repos.

**Comment by ryanpetrello** [comment]
Closing due to age - we've moved on to pg10 at this point.
