### ISSUE TITLE
Job output paginator can make requests to page 0 of job_events endpoint, resulting in unhandled 404

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#9772]
It's possible for the job output paginator to produce a request to page 0, which returns an unhandled 404:

![Screenshot from 2021-03-31 11-48-29](https://user-images.githubusercontent.com/9753817/113173073-0b837600-9217-11eb-9962-eccdd4e1785f.png)

**Comment by tiagodread** [comment]
PR already merged, verified locally and no requests happenning to page 0 anymore.
