### ISSUE TITLE
[ui_next] Add edit button to workflow job output page

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#9778]
##### ISSUE TYPE
 - Enhancement

##### SUMMARY
I was working with constructing a complicated workflow and needed two tabs open to make quick adjustments to the layout of a workflow from the workflow output page. A simple workflow viz editor button would have saved me some steps.

<img width="1037" alt="Screen Shot 2021-03-31 at 6 31 53 PM" src="https://user-images.githubusercontent.com/12446869/113219514-85cfec80-924f-11eb-86f4-f4c6eb404b19.png">

**Comment by akus062381** [comment]
resolved
