### ISSUE TITLE
AWX 18.0.0: Provide documentation about how to migrate an existing "local docker" install into a K9S-Based 18.0.0

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx#9784]
##### ISSUE TYPE
 - Documentation request

##### SUMMARY
There are no instructions provided about how would one migrate an existing "local docker" setup into a new AWX 18.0.0 setup.

##### ENVIRONMENT
* AWX version: Migration from 17.1.0 to 18.0.0
* AWX install method: mixed: 17.1.0 is "local docker", 18.0.0 is inside K9S with the AWX operator

**Comment by Lejooohn** [comment]
Ya agree it's should be good if an accurate documentation can be existed because i'm on the same situation (from local docker in 17.1.0) and i don't know how to migrate step-by-step without data lost.

Regards,

**Comment by ghost** [comment]
Same situation here

**Comment by shanemcd** [comment]
There is no supported migration path here. You'll have to do it manually by dumping / restoring your database, or automate the creation of your AWX.

**Comment by lemmy04** [comment]
I just found instructions https://github.com/ansible/awx-operator/blob/devel/docs/migration.md, but how can I access the database that is located in a standalone docker on a different host - I'd have to reconfigure that first, to be accessible from the outside.
Is the database scheme still the same as in 17.1.0?
