### ISSUE TITLE
Configure individual nodes in a cluster for mutli-datacenter setup

### ISSUE THREAD

**Issue by minsis** [ansible/awx#9790]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
When you have a cluster in multiple datacenters you should be able to configure each node's settings individually. Maybe not all settings need to be this way but things like logging, authentication, and optionally database maybe a few others should be.

As an example we have 3 nodes in our cluster all in different datacenters, but for auth it all points to a single LDAP server in one of those datacenters when each one should point to its local datacenter. 

For the database someone could use something like percona or your own cluster solution where each node can connect to its own local database or a clustered SQL proxy solution that spans the datacenters.

The database part could be a bit far fetched, but the other two with auth and logging I think would be valid.

**Comment by ryanpetrello** [comment]
Hey @minsis,

I'm not totally sure what your setup is, but whatever you're trying to do here isn't going to work.

**Comment by minsis** [comment]
I know it doesn't work thats why its a feature idea =)

Basically we have multiple datacenters with an AWX instance in each one. They're all clustered together so we can manage it all from a single interface. The need is to allow configuration for each node in the cluster to access local resources.

An example is two nodes, one in each datacenter: We configure splunk logging, or AD login. All nodes in the cluster will have to connect to a single source that we configure. But each datacenter has a domain controller or a splunk collector. Each node should be accessing that resource in its own individual datacenter, not cross datacenters.

This is currently how you have to configure a cluster:
![image](https://user-images.githubusercontent.com/11248197/114225624-2ac98400-9938-11eb-98bf-8cc0e54ebf6e.png)

This is the way it should be:
![image](https://user-images.githubusercontent.com/11248197/114225681-3d43bd80-9938-11eb-8955-cce2ded813ae.png)

**Comment by wenottingham** [comment]
AWX clusters are confined to a single kubernetes/openshfit cluster. Even if you're using something that isn't AWX as released on quay.io, it does *not* support cross-DC clustering.

**Comment by minsis** [comment]
Fair enough. The issue is we're now stuck to being on 15 for who knows how long because of the k8s requirement that is imposed on AWX has made it unusable for us.
