### ISSUE TITLE
[ui_next] Approval Node Min and Seconds are not properly formatted on workflow viz node editor wizard

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#9793]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
<img width="1125" alt="Screen Shot 2021-03-31 at 2 41 11 PM" src="https://user-images.githubusercontent.com/12446869/113435788-82547680-93b1-11eb-8761-c81c46162bc1.png">

**Comment by AlexSCorey** [comment]
![Screen Shot 2021-08-12 at 1 43 03 PM](https://user-images.githubusercontent.com/39280967/129243616-f14376f4-6468-4c7f-b642-ea7b4c89a6e6.png)
Looks like this has been resolved.
