### ISSUE TITLE
you can not add a new schedule for template [ no add available]

### ISSUE THREAD

**Issue by wardcomm** [ansible/awx#9799]
you can not add a new schedule for template [ no add available]

**Comment by AlexSCorey** [comment]
@wardcomm f you are filing a bug please use the bug template so that we can better understand and solve the problem. 
 https://github.com/ansible/awx/issues/new?assignees=&labels=&template=bug_report.md

**Comment by jakemcdermott** [comment]
@wardcomm Not sure how to reproduce. Adding a schedule to a template seems to work fine when I tried:

![add_schedule](https://user-images.githubusercontent.com/9753817/113620311-27788480-9628-11eb-8ebb-e393e16e43f6.gif)
