### ISSUE TITLE
Inventory Handling

### ISSUE THREAD

**Issue by LokiOfNorse** [ansible/awx#9805]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Groups:
Not able to create universal groups or to add more then on inventory to one group. 
Can not create group to add hosts

Smart Inventory:
Doesnt work. 

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker in virtual environment
* Ansible version:  2.9
* Operating System: Ubuntu 20.04
* Web Browser: Firefox and Safari

##### STEPS TO REPRODUCE
- Create a group when in Hosts
- Try to add advanced filter to Smart Inventory
- Try to add other inventorys to a group

##### EXPECTED RESULTS

Be able to group more then one inventory. 
Example: I have multi linux machines, i want to run jobs on many of them (push a config), they are seperated in different inventorys like: 
Devops, security, network etc. 
Trying to use the smart inventory ot "group" them or add hosts to a Linux group so i can for example run a job on all. 

##### ACTUAL RESULTS

Doesnt work/ glitches out. 
##### ADDITIONAL INFORMATION

Workaround is to create multiple inventorys:
example: 
inventorys: 
 - Web
 - network
 - monitor
 - kubernetes

and create a inventory with all the same hosts in it. 
Downside, the Host menu on the left is no longer worth anything since you have duplicate hosts.

**Comment by LokiOfNorse** [comment]
Inventory Groups is ok. (I misunderstood this).
Issue just regards Smart Inventory.

**Comment by wenottingham** [comment]
-> #1999
