### ISSUE TITLE
how to use this minikube-awx?

### ISSUE THREAD

**Issue by someconservator** [ansible/awx#9808]
Ok, I installed awx on the minikube using the provided tutorial. Now I have it running in a container with a cni podman local IP address accessible from the local server. And I can look at this using my local browser. Nice! And what to do next? What is the recommended way to get access from/to other servers? Especially when awx starts with different cni addresses each time. Do I need to log into this server every time to access the web interface? And do I need to rewrite /etc/hosts (in 21 century????) for ingress every time? And how to access manual playbook catalogs? And how to build inventory? Unclear.

**Comment by wenottingham** [comment]
This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by someconservator** [comment]
Yes, it’s a question of the popularity of your application and the number of users who are interested in it, and not passed by. The tower is expensive, this is not working. Well, why waste time about him? There will be a lot of people who think so, especially if there are competitors. Instead, the team can add a couple, another paragraphs to the manual. But whatever you like, of course. usually people don't think ahead, and then they are surprised.
