### ISSUE TITLE
Issue with Job Templates page under Projects

### ISSUE THREAD

**Issue by palmar** [ansible/awx#981]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
Attempting to load the "JOB TEMPLATES" tab under "Projects" fails. The UI displays a "Loading" error message alongside multiple instance of placeholder labels such as: 

{{columnLabel \| translate}} | {{columnLabel \| translate}} | {{columnLabel \| translate}} | {{columnLabel \| translate}}

Additionally an error is thrown in the web console:

Error: [$controller:ctrlreg] The controller with the name 'TemplatesListController' is not registered.
http://errors.angularjs.org/1.6.8/$controller/ctrlreg?p0=TemplatesListController

##### ENVIRONMENT
* AWX version: 1.0.2.370
* AWX install method: docker
* Ansible version:  2.4.2.0 
* Operating System: Centos 7
* Web Browser: Firefox, also tested in Chrome

##### STEPS TO REPRODUCE

See above. Simply clicking the tab immediately fails

##### EXPECTED RESULTS

The tab works correctly and lists existing job templates

##### ACTUAL RESULTS

See above

##### ADDITIONAL INFORMATION

https://i.imgur.com/Isuj7Fz.png

Error
columnNumber: 996
fileName: "https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js"
lineNumber: 570
message: "[$controller:ctrlreg] The controller with the name 'TemplatesListController' is not registered.\nhttp://errors.angularjs.org/1.6.8/$controller/ctrlreg?p0=TemplatesListController"
stack: "minErr/<@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:570:996\n$ControllerProvider/this.$get</<@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:570:92130\ncompile/<@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:603:6831\nbind/<@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:570:9425\ninvokeLinkFn@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:570:82131\nnodeLinkFn@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:570:64012\ncompositeLinkFn@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:570:52824\ncompile/<@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:570:51480\ncompilationGenerator/<@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:570:58584\nupdateView@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:603:28827\nconfigUpdatedCallback@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:603:27998\nconfigureUIView@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:443:48287\nViewService</ViewService.prototype.sync@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:443:48684\nactivateViews@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:603:37895\nTransitionHook</TransitionHook.prototype.invokeHook/result<@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:37:576736\nTransitionHook</TransitionHook.prototype.invokeHook@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:37:576718\nTransitionHook</TransitionHook.runAllHooks/<@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:37:576039\nTransitionHook</TransitionHook.runAllHooks@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:37:576003\ntransitionSuccess@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:53:13069\nprocessQueue@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:570:134250\nscheduleProcessQueue/<@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:570:135199\n$digest@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:570:146075\n$apply@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:570:148843\ndone@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:570:101111\ncompleteRequest@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:570:106022\ncreateHttpBackend/</xhr.onload@https://REDACTED-FOR-PRIVACY/static/js/vendor.bd5b7932827855e6a213.js:570:106781\n"
__proto__: Object { … }

**Comment by jaredevantabor** [comment]
@jlmitch5 likely fallout from the expanded list feature merge? seems likely

**Comment by jlmitch5** [comment]
yep!  here's the issue I'm working off of https://github.com/ansible/awx/issues/960
