### ISSUE TITLE
AWX Execute Playbook temp directory no save file 

### ISSUE THREAD

**Issue by renat473** [ansible/awx#9816]
When the job and release it saves everything in the tmp and in the dest parameter it puts the full path next to the dest
ends up being like this "dest": "/ tmp / awx_47__hm6f5ms / project / opt / backup_pfsense"
when the correct one would be "this": "/ opt / backup pfsense"

##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by wenottingham** [comment]
This is not a bug, playbooks run in a private namespace (and in AWX 18, their own container).
