### ISSUE TITLE
CSP violation errors on job details and job settings views

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#9817]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
- dev environment, `make ui-devel`, port `8043`

##### STEPS TO REPRODUCE
- run `make ui-devel` to create a production bundle of the ui
- using port `8043` in the dev environment, navigate to the job details panel of a job template run or go to the job settings page

##### EXPECTED RESULTS
- no CSP errors in console

##### ACTUAL RESULTS
- CSP error in console

##### ADDITIONAL INFORMATION
After some debugging by @jbradberry @ryanpetrello , appears to be related to [this code](https://github.com/ajaxorg/ace/blob/94422a4a892495564c56089af85019a8f8f24673/lib/ace/worker/worker_client.js#L46) cc @ryanpetrello @keithjgrant

**Comment by tiagodread** [comment]
I can't see these CSP errors in console anymore
