### ISSUE TITLE
Documentation for existing Kubernetes and external DB

### ISSUE THREAD

**Issue by dburns-vistra** [ansible/awx#9826]
##### ISSUE TYPE
 - Bug Report - Docs

##### SUMMARY
Assistance for using an existing Kubernetes and external DB

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: kubernetes
* Ansible version:  2.9.x?
* Operating System:AWS Linux2
* Web Browser:Chrome

##### STEPS TO REPRODUCE

I plan to spin up an EKS cluster and Postgres SQL AWS RDS

##### EXPECTED RESULTS

I don't plan to install Minikube

##### ACTUAL RESULTS

I will be happy to write up and help to keep up to date the installation for this scenario.  I noticed some documentation before.  I am an active user of AWX and will help out where I can.

**Comment by shanemcd** [comment]
This is documented here: https://github.com/ansible/awx-operator#external-postgresql-service
