### ISSUE TITLE
Parameterize Version in Requirements.yml

### ISSUE THREAD

**Issue by pmanno** [ansible/awx#9828]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
I have a base project with all my playbooks.  In that repo I have a roles/requirements.yml file that references all my custom roles. Everything is on the master branch at the moment. Now I want to support branching in my ansible roles.  I would love it if I could just pass in a branch name to the main project sync and have that branch name apply not only to the project repo, but also the roles/requirements.yml projects that are sourced in via git.  This way I could maintain a long lived branch in each role for devs to update and just switch from develop to master by passing in the branch to the project sync and have all my roles auto-flip to that branch also.  The only other option would be to have a long-lived branch of the project, and add in `version: develop` in the roles/requirements.yml there... but having it be parameterized or something would be preferred.

Maybe I'm way off on this and someone else has a better idea.  Please let me know.

Thanks!
Paul

**Comment by ryanpetrello** [comment]
Hey @pmanno,

Thanks for the suggestion.  This is going to be hard for us to support, because the `ansible-galaxy` tool itself doesn't actually support this.

**Comment by pmanno** [comment]
No way to just add support to template out the requirements.yml file?
i.e. 
```
- src: ssh://git@somerepo
  path: roles
  scm: git
  version: "{{ scm_branch | default('master') }}"
```
