### ISSUE TITLE
JT schedule POST throws 400 when new variable included in extra_data

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#983]
##### ISSUE TYPE
 - Bug Report (I think?)

##### COMPONENT NAME
 - API

##### SUMMARY
1) Create a Job Template without any extra vars or survey
2) POST to `/api/v2/job_templates/:id/schedules` and include something in `extra_data` like so:

```
{
    ...
    extra_data: {
        foo: "bar"
    }
}
```

The api will respond with a 400 error in this case, saying:

`{extra_data: ["Variables foo are not allowed on launch."]}`

I guess I'm looking for clarification on what the expected behavior here is.  I would have expected that the variables supplied at the schedule level would merge with those supplied at the job template level, allowing the user to supply additional variables that may not have been specified in the JT.

**Comment by AlanCoding** [comment]
Job template needs `ask_variables_on_launch` to be True to accept user-provided variables.

**Comment by AlanCoding** [comment]
Suggest making an API issue to expand wording of error message to answer this question

**Comment by rooftopcellist** [comment]
Thank you for clarifying Alan, I can just put in a PR for that off of this issue.

**Comment by rooftopcellist** [comment]
@mabashian mentioned that we should hide the `Extra Vars` section in the UI on the Schedules creation/edit page if the `ask_variables_on_launch` flag is False.  I think that would help the UX.

**Comment by mabashian** [comment]
@rooftopcellist yea I've already made those changes locally to handle extra vars on the UI side 👍
