### ISSUE TITLE
Branding issue: AWX 18 in K3s uses the awx icons and logos everywhere except "info->about"

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx#9830]
##### ISSUE TYPE
 - Bug Report (branding)

##### SUMMARY
When I look at "Info->About" I see the "angry potato" logo instead of the AWX logo

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: K3s using awx-operator
* Ansible version:  unknown (see #9829)
* Operating System: K3s on debian buster
* Web Browser: Firefox 87

##### STEPS TO REPRODUCE

Deploy AWX 18.0.0 on K3s using the awx operator, then after logging in open "info->About"

##### EXPECTED RESULTS

I expect the AWX logo since it's used everywhere else

##### ACTUAL RESULTS

I see the development version logo (the "angry potato")

**Comment by jakemcdermott** [comment]
@unlikelyzero This relates to branding, so I'm re-assigning the original priority of `high`

**Comment by unlikelyzero** [comment]
Got it. I have been using severity=priority but that makes more sense

**Comment by unlikelyzero** [comment]
this will need a visual test

**Comment by lemmy04** [comment]
I just checked - now I see the awx icon in about, instead of the angry potato.

...but I also see that we now have the year 0.

**Comment by jakemcdermott** [comment]
> I just checked - now I see the awx icon in about, instead of the angry potato.

:+1: This sounds like the original issue has been addressed.

> but I also see that we now have the year 0.

Indeed... we merged a pr to devel this morning to fix that. If you pull in latest you should see the right date.

**Comment by jakemcdermott** [comment]
> this will need a visual test

@unlikelyzero Sounds good - I can leave the issue open or close, lmk your preference.

**Comment by lemmy04** [comment]
I would say this one can be closed now.
