### ISSUE TITLE
Web interface doesn't refresh automatically job progress

### ISSUE THREAD

**Issue by But4ler** [ansible/awx#9831]
##### ISSUE TYPE
Bug Report

##### SUMMARY
I don't have real time job logs like in the previous version we had (v11)

a refresh of the page is necessary, the tasks already executed, but not the one in progress and the following ones. 

##### ENVIRONMENT
AWX version: 17.1.0
AWX install method: kuberntes
Web Browser: chrome and firefox

##### STEPS TO REPRODUCE
It can happen when submitting any jobs.
SCM update, job execution, inventory update etc

Now you can refresh your browser

##### EXPECTED RESULTS
real time display of logs, as in previous versions

##### ADDITIONAL INFORMATION
I have the same result, with or without using a virtual environment

**Comment by fabfabbar** [comment]
+1

**Comment by jakemcdermott** [comment]
:wave: Hello This should be resolved in the latest version (18.0.0+). Can you try it there?

**Comment by jakemcdermott** [comment]
This appears to still be a problem for some. There's [another issue](https://github.com/ansible/awx/issues/9747) open so we'll track the work there.

**Comment by my2ter** [comment]
See my comment here for solution https://github.com/ansible/awx/issues/8596#issuecomment-2066069005
