### ISSUE TITLE
Add the support for workflow job templates in tower_schedule module

### ISSUE THREAD

**Issue by alankuras** [ansible/awx#9832]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

awx.awx.tower_schedule doesn't support the workflow job template, while the API supports that :
https://docs.ansible.com/ansible-tower/latest/html/towerapi/api_ref.html#/Workflow_Job_Templates/Workflow_Job_Templates_workflow_job_templates_schedules_create

**Comment by keilr** [comment]
@alankuras 
I just wanted to open the very same feature request as you did. But the module is already able to create schedules for workflows.

It looks like we misunderstood the doc: the `/api/v2/unified_job_template` endpoint contains workflows as well. So the `tower_schedule` module is able to lookup the workflow-id.

I'm using the following Tower and Ansible versions:
```
ansible: 3.2.0
ansible-base: 2.10.8
tower: 3.6.4
```

**Comment by sean-m-sullivan** [comment]
I just tested on both awx 19.0.0 and tower 3.8.2 and they are able to create schedules using the current module when you provide the workflow job template name as the unified job template name.

**Comment by beeankha** [comment]
I second what @sean-m-sullivan said, I was also able to successfully create a schedule for a WFJT using the `tower_schedule` module in a playbook (on `AWX 19.0.0`).

**Comment by beeankha** [comment]
Closing this issue since schedules can be created for WFJTs via the `tower_schedule` module.
