### ISSUE TITLE
18.0.0 Inventory with Satellite 6 don't sync

### ISSUE THREAD

**Issue by dperez-sct** [ansible/awx#9833]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Trying to sync Satellite 6.8.4 inventory to AWX 18.0.0 fail.
With 17.1.0 works without problem

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: openshift
* Ansible version:  ansible-inventory [core 2.11.0b3.post0]?
* Operating System: Openshift 4

##### STEPS TO REPRODUCE

Create Satellite credentials
Create a inventory
Create a Source using Satellite credentials
Sync

##### EXPECTED RESULTS

Newly created inventory populated with hosts of Satellite
##### ACTUAL RESULTS

`ansible-inventory [core 2.11.0b3.post0] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
setting up inventory plugins
Skipping due to inventory source not existing or not being readable by the current user
auto declined parsing /runner/foreman.yml as it did not pass its verify_file() method
[WARNING]: Unable to parse /runner/foreman.yml as an inventory source
ERROR! No inventory was parsed, please check your configuration and options.`

##### ADDITIONAL INFORMATION

With 17.1.0 we haven't any problems with this inventory sync, same satellite and credentials used.

**Comment by ryanpetrello** [comment]
@dperez-sct can you give this a whirl in AWX 19.0.0?  We fixed some issues related to inventory syncing that occurred in AWX 18.

**Comment by dperez-sct** [comment]
With 19 work without problem!
