### ISSUE TITLE
AWX - Manual Projects

### ISSUE THREAD

**Issue by diogoattall** [ansible/awx#9837]
Hi,

I have installed AWX following the documentation in https://github.com/ansible/awx/blob/devel/INSTALL.md, so with docker + minikube.

I'm trying to setup the awx according to my current ansible environment, but I'm facing an issue regarding manual projects.

When I try to create new projects and select Source Control Credential Type as Manual, it doesn't allow me to select playbook directory:
WARNING:
There are no available playbook directories in /var/lib/awx/projects. Either that directory is empty, or all of the contents are already assigned to other projects. Create a new directory there and make sure the playbook files can be read by the "awx" system user, or have AWX directly retrieve your playbooks from source control using the Source Control Type option above.

The path /var/lib/awx/projects exists and I've created a subfolder with some playbooks:
~]$ ll /var/lib/awx/projects/playbooks/
total 20
-rw-rw-r-- 1 ansible ansible  322 Mar 31 23:03 alterar_ssh.yml
-rw-rw-r-- 1 ansible ansible  225 Dec 14 22:00 disable_selinux.yml
-rw-rw-r-- 1 ansible ansible  549 Dec 14 22:57 setup_firewalld.yml
-rw-rw-r-- 1 ansible ansible 1660 Dec 14 23:32 setup_ssh.yml
-rw-rw-r-- 1 ansible ansible  153 Dec 15 21:46 update_system_yum.yml

However awx seems to be not fetching them...

How can I solve this issue? Am I doing something wrong? Honestly I don't know, as it's my first time using kubernetes.

Thanks in advance.

**Comment by shanemcd** [comment]
A PR for this just merged and should be out in a release later today: https://github.com/ansible/awx-operator/pull/177

Even then, if you're just creating those files on the host and expecting them to show up inside of your Kubernetes pods, that won't work. You will need to do something like:

```
minikube start --mount --mount-string="/var/lib/awx/projects/playbooks/:/var/lib/awx/projects/playbooks/"
```

**Comment by diogoattall** [comment]
Hi,

Sorry about to re-open this... But I'm not figuring out how to fix the issue. I've waited for the new release, and tried to installed it from scratch today, but the problem persists.

Maybe the issue it's between the keyboard and chair, maybe not. I'm following all the steps from documentation https://github.com/ansible/awx/blob/devel/INSTALL.md to install awx, what am I doing wrong?

Thanks in advance.
