### ISSUE TITLE
Installing the latest AWX on a VMWare guest

### ISSUE THREAD

**Issue by ntui** [ansible/awx#9845]
We use VMWare for almost all of the servers we have at my organization.  minikube does not work on our guest machines because of the lack of VT-X/AMD-v support in the guest VMs.

What do you recommend for installing the latest version of AWX on a non-bare metal server?

While Semaphore doesn't have all the features that AWX does, it does install directly onto the machine so it's an option. I would prefer AWX. We are very tight on funds to buying Tower is likely not an option.

**Comment by ryanpetrello** [comment]
Hey @ntui,

If minikube isn't an option, you could try running AWX in Docker via `docker-compose`:

https://github.com/ansible/awx/tree/devel/tools/docker-compose

...but note that this install method is not something we rigorously test; it's primarily used as a development environment by the AWX core team.

**Comment by shanemcd** [comment]
Hello,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by fiftin** [comment]
Hi @ntui Do you use Semaphore or AWX now?

**Comment by fiftin** [comment]
Hi @ntui Did you migrate to Semaphore?
