### ISSUE TITLE
Add link to the docs in how to replace a custom virtual env with an EE

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#9846]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Right now we are displaying a warning message if a previous resource had a custom virtual env, that was not replace by an EE. It would nice to have a link to the doc in how to do that as part of the warning.

**Comment by mabashian** [comment]
@tvo318 do you know if we have a landing place for this in the docs yet?

**Comment by tvo318** [comment]
> @tvo318 do you know if we have a landing place for this in the docs yet?

Yes, see: PR #[1508](url): https://github.com/ansible/product-docs/pull/1508
https://github.com/ansible/product-docs/blob/62bed9be5ce41585584d8dad1853ce34c5525dc3/common/source/virtualenv.rst

**Comment by tiagodread** [comment]
This is now merged
