### ISSUE TITLE
Documentation missing: How to upgrade AWX in Kubernetes

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx#9849]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

AWX 19.0.0 was released, there is no documentation about how to upgrade from 18.0.0

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: k3s, awx-operator
* Ansible version:  
* Operating System: debian buster
* Web Browser:

##### STEPS TO REPRODUCE

have a working AWX 18.0.0 in Kubernetes, try to find documentation about how to upgrade to 19.0.0

##### EXPECTED RESULTS

I would expect to see upgrade instructions somewhere.

**Comment by shanemcd** [comment]
Process should just involve re-running this command: https://github.com/ansible/awx-operator#basic-install

**Comment by shanemcd** [comment]
Happy to review a PR that adds a note for this somewhere in INSTALL.md.

**Comment by Commifreak** [comment]
"Upgrading" by this method keeps all volumes/data?

**Comment by lemmy04** [comment]
> Process should just involve re-running this command: https://github.com/ansible/awx-operator#basic-install

all that I got from this is a second awx-operator pod that is stuck in ErrImagePull, the latest awx-operator yaml file expects 0.8.0 of the container image which is not available.

**Comment by cr0cdev** [comment]
> > Process should just involve re-running this command: https://github.com/ansible/awx-operator#basic-install
> 
> all that I got from this is a second awx-operator pod that is stuck in ErrImagePull, the latest awx-operator yaml file expects 0.8.0 of the container image which is not available.

Looking at the images, I guess the new image is named "devel" and just downloading the awx-operator.yaml to your server and modifying the image number from 0.8.0 to devel does the trick right now.

**Comment by Commifreak** [comment]
Maybe the Docker images are still being generated. But why they dont wait until this is done? Every install/upgrade will fail in the meantime?

**Comment by cr0cdev** [comment]
After a bit of hassle I was able to upgrade the AWX, but I lost all my data because just running kubectl commands again does not do the trick because it will keep the old containers up. Had to clean all the containers and rebuild it. I guess the easier way is to setup a external postgresql server and configure AWX against that so you do not lose data.

**Comment by balonik** [comment]
> After a bit of hassle I was able to upgrade the AWX, but I lost all my data because just running kubectl commands again does not do the trick because it will keep the old containers up. Had to clean all the containers and rebuild it. I guess the easier way is to setup a external postgresql server and configure AWX against that so you do not lose data.

Yes, I am running with external postgresql (deployed using the bitnami Helm chart) and you won't loose data this way.
If you need persistent `projects` folder you can also use the `tower_projects_*` properties available in awx-operator 0.8.0

**Comment by cr0cdev** [comment]
> > After a bit of hassle I was able to upgrade the AWX, but I lost all my data because just running kubectl commands again does not do the trick because it will keep the old containers up. Had to clean all the containers and rebuild it. I guess the easier way is to setup a external postgresql server and configure AWX against that so you do not lose data.
> 
> Yes, I am running with external postgresql (deployed using the bitnami Helm chart) and you won't loose data this way.
> If you need persistent `projects` folder you can also use the `tower_projects_*` properties available in awx-operator 0.8.0

Can you give me a example of your DB connection config? I'm trying to set it up but it does not like the information I throw at him.
Error:
"Secret in version "v1" cannot be handled as a Secret: v1.Secret.StringData: ReadString: expects " or n, but found 5"

**Comment by shanemcd** [comment]
@lemmy04 Sorry about that. See https://github.com/ansible/awx-operator/issues/190

**Comment by balonik** [comment]
@mYzk 
here it is

```
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres
type: Opaque
stringData:
  host: "1.2.3.4"
  port: "5432"
  database: awx
  username: awx
  password: mypassword

---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  tower_postgres_configuration_secret: awx-postgres
...
```

**Comment by andy-hcc** [comment]
Just to clarify, what would the expectation be if you were originally not using an external Postgres database, so one was created during the initial AWX install, but you were now looking to upgrade?

The `awx-postgres` secret now exists (as it was setup during initial AWX install) so would it be safe to just use the `tower_postgres_configuration_secret: awx-postgres` option in the yaml file when attempting to install a newer AWX version?

**Comment by lemmy04** [comment]
my personal expectation would be, if there's already an existing AWX deployment inside the namespace, do not throw away volumes.

**Comment by lemmy04** [comment]
so - how DOES one upgrade an already existing awx from x.y.z to x+1.?.? ? *without* loosing all data?

**Comment by cr0cdev** [comment]
> so - how DOES one upgrade an already existing awx from x.y.z to x+1.?.? ? _without_ loosing all data?

I recommend you to backup postgres database and setup a external one and import the backup. Then you can upgrade AWX at any given time without losing any valuable data.

**Comment by lemmy04** [comment]
so basically, the postgres database that is part of the setup is not to be used? o.0 :eyeroll:

**Comment by shanemcd** [comment]
@lemmy04 It's been rather unpleasant interacting with you over the past couple weeks. This is an open source project that we make available _for free_. 

As you've noticed, we have made some pretty big changes recently and are currently trying to work through some issues.

If you want to contribute and make things better, great. If you feel a sense of entitlement to a piece of software that never changes or breaks, then maybe go somewhere else.

**Comment by lemmy04** [comment]
I guess I've put my foot in my mouth here, sincere apologies for that.

**Comment by shanemcd** [comment]
@lemmy04 Thanks for that. We really do value people taking the time to report issues, and we'll try our best to fix them. It's just a **lot** less fun when folks are leaving snide or disrespectful comments. Hopefully we can collaborate in a more productive way going forward.

**Comment by lemmy04** [comment]
Back to the original question: If I want the database to "survive" an upgrade (or redeployment for whatever reason), I'll basically have to manually deploy a postgres pod and point the operator at it, or just run a postgres server somewhere and point the operator at it? ... would it be possible to have more than one AWX use the same database, or would that be a Very Bad Idea?

**Comment by shanemcd** [comment]
@lemmy04 So, the underlying [Ansible Operator ](https://sdk.operatorframework.io/docs/building-operators/ansible/) does *not* delete PVs (Persistent Volumes) when deleting a CR (Custom Resource - like your `awx` object). I very often will delete my `awx`, redeploy, and it will reuse the old PV.

If you want to go the external database route, one thing to be mindful of would be to ensure you're always using the correct secret key. That is somewhat documented here: https://github.com/ansible/awx-operator/blob/devel/docs/migration.md#secret-key

**Comment by lemmy04** [comment]
> @lemmy04 So, the underlying [Ansible Operator ](https://sdk.operatorframework.io/docs/building-operators/ansible/) does
> _not_ delete PVs (Persistent Volumes) when deleting a CR (Custom Resource - like your `awx` object). I very often will delete my
>  `awx`, redeploy, and it will reuse the old PV.

that explains a lot - until now I've "redeployed" by deleting the whole namespace that I've put awx in - of course that would also wipe the PV and PVC... 🤦‍♂️

**Comment by shanemcd** [comment]
Closing, will track in https://github.com/ansible/awx-operator/issues/300
