### ISSUE TITLE
Get HTTP 403 error when testing a HashiCorp Vault Secret Lookup Credential

### ISSUE THREAD

**Issue by shenqinb-star** [ansible/awx#9850]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Get HTTP 403 error when testing a HashiCorp Vault Secret Lookup Credential:
![image](https://user-images.githubusercontent.com/79623318/114003346-411c0500-9890-11eb-9eae-89fe98a35515.png)

##### ENVIRONMENT
* AWX version: 17.1.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.9.18
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

1. Create HashiCorp Vault Secret Look Credential in AWX with following info:
![image](https://user-images.githubusercontent.com/79623318/114004270-12525e80-9891-11eb-8039-c3adc66c5496.png)
2. Click Test and Input following info:
![image](https://user-images.githubusercontent.com/79623318/114004372-2c8c3c80-9891-11eb-867f-cee913dfcdd6.png)
3. Click Run 

##### EXPECTED RESULTS

Run Successfully
##### ACTUAL RESULTS

Get Http 403 error
##### ADDITIONAL INFORMATION

1. This AppRole only has read permission to the secret path. I have tested via Vault CLI, it works.

**Comment by balonik** [comment]
If you mean the `CA CERTIFICATE` field when you configure Credential of type `HashiCorp Vault Secret Lookup` then it is not required if the CA is in system's truststore/ca-bundle.

**Comment by shenqinb-star** [comment]
@balonik thanks for your reply. I have updated the issue. now I got Http 403 error after providing CA. please read the updated description. The AppRole I provided has read permission to the secret path. I have tested via Vault CLI and it works. but I got 403 error in AWX.

**Comment by balonik** [comment]
@shenqinb-star 
HTTP 403 was returned by Vault. It means Vault denied you access to that secret or to login. Make sure your AppRole role has correct `token_policies` assigned to access that secret. Also make sure your AppRole doesn't limit CIDRs using `secret_id_bound_cidrs`
You can also look in Vault logs to see the details.

**Comment by jakemcdermott** [comment]
Yes to what @balonik said -  the 403 is from the vault and it likely means the details or access credentials you're providing to vault via the plugin aren't exactly right.
