### ISSUE TITLE
error when removing single Source from inventory

### ISSUE THREAD

**Issue by balonik** [ansible/awx#9852]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
It is not possible to delete single Source from Inventory. When trying to delete single inventory source following error occurs

```
Error: TypeError: Cannot read property 'count' of undefined at https://awx.example.com/static/js/main.2594bb50.chunk.js:1:148664 at c (https://awx.example.com/static/js/2.89b6cada.chunk.js:2:1469770) at Generator._invoke (https://awx.example.com/static/js/2.89b6cada.chunk.js:2:1469523) at Generator.next (https://awx.example.com/static/js/2.89b6cada.chunk.js:2:1470129) at r (https://awx.example.com/static/js/2.89b6cada.chunk.js:2:729) at s (https://awx.example.com/static/js/2.89b6cada.chunk.js:2:932)
```

##### ENVIRONMENT
* AWX version: 19.0.0
* AWX install method: awx-operator 0.8.0 on RKE
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Create Inventory
Create Inventory source
Delete Inventory source

##### EXPECTED RESULTS

Source is deleted.

##### ACTUAL RESULTS

Source is not deleted. See error above.

##### ADDITIONAL INFORMATION

Currently as a workaround it is possible to create a dummy Source and select it as well. Multiple Source deletion is working. The warning message is broken, tho.

```
{numItemsToDelete, plural, one {This inventory source is currently being used by other resources that rely on it. Are you sure you want to delete it?} other {Deleting these inventory sources could impact other resources that rely on them. Are you sure you want to delete anyway?}}
```

**Comment by mabashian** [comment]
Slight tweak to the reproduction steps:

Create Inventory
Create _two_ Inventory sources
Delete _one of the_ Inventory sources

If you only have one inventory source on the inventory then you can delete it without issue.

**Comment by tiagodread** [comment]
PR merged, added a e2e test case for it
