### ISSUE TITLE
quay.io/ansible/awx-operator:0.8.0 / missing image

### ISSUE THREAD

**Issue by gajda-b** [ansible/awx#9853]
There is no image 
quay.io/ansible/awx-operator:0.8.0 

required to operate awx-operator  on
https://quay.io/repository/ansible/awx-operator?tag=0.8.0&tab=tags

##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by balonik** [comment]
this is already reported in the awx-operator repository https://github.com/ansible/awx-operator/issues/190

**Comment by shanemcd** [comment]
Oops. Sorry folks. This has been addressed. I'll automate the problem so I don't forget next time.
