### ISSUE TITLE
Project Data Dir in AWX 19.0.0

### ISSUE THREAD

**Issue by sudoerss** [ansible/awx#9855]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME

 - UI
 - Installer

##### SUMMARY

I installed awx 19.0.0 by following the official procedure with minikube and when I want to create a new project I have this message:

``
There are no available playbook directories in /var/lib/awx/projects. Either that directory is empty, or all of the contents are already assigned to other projects. Create a new directory there and make sure the playbook files can be read by the "awx" system user, or have AWX directly retrieve your playbooks from source control using the Source Control Type option above.
``

in versions prior to 18.0.0 via docker there was the project_data_dir variable which mounted the volume of the host machine directly in the awx_task docker but I admit that I don't quite understand how this is done now 

##### ENVIRONMENT
* AWX version: 19.0.0
* AWX install method: k3s, awx-operator

**Comment by shanemcd** [comment]
Hello. A release just went out yesterday that added support for this. See https://github.com/ansible/awx/issues/9837

**Comment by sudoerss** [comment]
Thank you very much for the quick response
sorry to have created this issue for nothing

**Comment by sudoerss** [comment]
Hello, 
After editing the volume by hand
`minikube start --mount --mount-string="/var/lib/awx/projects/playbooks/:/var/lib/awx/projects/playbooks/"
`

I still can't get my playbooks from the webui, I still get the same error message

However, when I do a `minikube ssh`, I can see the volume mounted in the container with my playbooks inside
`docker@minikube:/var/lib/awx/projects$`

I also did a ssh on the docker present in the minukube container and in particular the one which is similar to awx_task but I do not see anything in it either

Could you tell me if there is any other subtlety that I might have overlooked ?

Thanks
