### ISSUE TITLE
AWX 18.0.0 ++: Provided EE can't run more demanding plays - collections are missing that used to be included in ansible itself

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx#9863]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I'm trying to run several plays that work just fine with ansible 2.9.0, in AWX 18 and 19 they fail because the modules they use have been moved into collections.
I believe for the sake of compatibility between AWX >= 18.0 and AWX <= 17.1 these collections should be included in the default execution environment.

The two collections that I'm missing are:
- ansible.windows
- community.general

Of course the relevant python modules also need to be part of the EE:
- winrm and dependencies

There might be more, please list them in comments.

##### ENVIRONMENT
* AWX version: 19.0.0
* AWX install method: k3s, awx-operator
* Ansible version:  unknown
* Operating System: debian buster
* Web Browser: n.a.

##### STEPS TO REPRODUCE

- deploy AWX 18 or 19
- configure a windows host (I've used the same credentials for the host as in my AWX 17.1 setup, so "it should just work")
- run win_ping against that host as an ad hoc command

##### EXPECTED RESULTS

win_ping should work just fine

##### ACTUAL RESULTS

win_ping fails with this output:
```
Enter passphrase for /runner/artifacts/9634/ssh_key_data: 
Identity added: /runner/artifacts/9634/ssh_key_data (/runner/artifacts/9634/ssh_key_data)
SSH password: 
BECOME password[defaults to SSH password]: 
cripple-windows | FAILED! => {
    "msg": "The module win_ping was redirected to ansible.windows.win_ping, which could not be loaded."
}
```

**Comment by shanemcd** [comment]
Hello, thanks for opening this. I've opened a PR here that adds `ansible.windows` to awx-ee: https://github.com/ansible/awx-ee/pull/51. This will be the default image in the next release of AWX.

**Comment by shanemcd** [comment]
Going to close this, since this specific problem will be addressed in the next release. Follow https://github.com/ansible/awx/issues/9864 for updates on the bigger problem with ad-hoc commands.

**Comment by lemmy04** [comment]
> 
> 
> Hello, thanks for opening this. I've opened a PR here that adds `ansible.windows` to awx-ee: [ansible/awx-ee#51](https://github.com/ansible/awx-ee/pull/51). This will be the default image in the next release of AWX.

can we please include ALL collections that are missing? I'd think that "the ansible" in the default EE should be able to run everything that "the ansible" in AWX before 18.0.0 was able to do, without having to change plays / projects in ways that might break them if you use them with an older tower.

Just imagine a developer using AWX as their testbed / development environment, and a RHEL8 with ansible 2.9 or ansible tower is the production environment. What would happen if ansible 2.9.x came across something that first tries to pull in collections?
would that work?

**Comment by wenottingham** [comment]
ansible itself is moving to remove content from the main distribution, and we are following that lead. While there is the ansible community distribution that includes a set of collections, at the moment we're prioritizing the flexibility of starting smaller with the minimal set.

I do realize that there are a set of collections in that EE - they're there for inventory purposes and we're working on how we might separate those out more cleanly. I'd expect other EEs may be created and maintained outside of AWX itself if people see fit and have a need.

**Comment by lemmy04** [comment]
So basically there will have to be two sets of plays for the same purpose - one for ansible 2.9.x and one for ansible 2.10 or 2.11, until ansible 2.11 has reached the distributions?
Take RHEL8 for example - what would happen to a playbook that is running under 2.9 or earlier, when it suddenly tries to install collections that might not even exist for that version?

**Comment by lemmy04** [comment]
I think the default EE should be one that contains the latest **release** of ansible... preferrably one that is compatible with what people have on the commandline, so someone developing plays on the CLI would be able to simply run the play on their development workstation with ansible-playbook, and if that runs without errors it should be safe to assume that it will run inside AWX as well.

I have 2.9.6 on openSUSE Leap 15.2,  ansible 2.7.7 on debian buster, and 2.9.19 on RHEL 8, but the current default EE image has ansible-core 2.11 which wasn't even installed from rpm... and has about three quarter of the modules missing:

```
[root@69f1b399a427 ~]# ansible-doc -l|wc -l
966
[root@69f1b399a427 ~]# logout
lemmy@kumiko:~> ansible-doc -l |wc -l
3387
```
