### ISSUE TITLE
Add option to select EE when launching ad-hoc commands

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx#9864]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I'm trying to run jobs or plays in my own EE to get around #9863 but it fails
It used to work doing it the way I'm doing in 18.0.0 with the EE image I made

##### ENVIRONMENT
* AWX version: 19.0.0
* AWX install method: k3s, awx-operator
* Ansible version:  unknown
* Operating System: debian buster
* Web Browser: n.a.

##### STEPS TO REPRODUCE

- deploy 19.0.0 (with database migration from my "live" 17.1 awx, as described in https://github.com/ansible/awx-operator/blob/devel/docs/migration.md - that worked like a charm)
- create a new execution environment using quay.io/mhomann/awx-ee-community:latest as the image
- Set that execution environment as the default for your organization
- try running win_ping adhoc against a windows host
- observe as it fails with the above output
- If you monitor your pod during this you will see that the worker spawns with the default EE image, not your custom one.

##### EXPECTED RESULTS

A job should use the EE that is set as the default for the organization it is run in, if there is one specified in the organization

##### ACTUAL RESULTS

see above: job uses default EE and fails due to #9863

**Comment by banshee091** [comment]
Just to be sure: The error is, it fails due to missing modules? I struggle with EEs myself, but here you say your EE works in 18, but fails with the same error it throws in 18...?

**Comment by lemmy04** [comment]
nope, that's not it... 

what happens is this: my custom EE works fine in AWX 18, bun in AWX 19 I get a seemingly random mix between the worker does not start with my custom EE, but uses the default instead and then the plays fail, or the worker does not even start at all, with some weird "runtime error" with no further info.

**Comment by banshee091** [comment]
>  or the worker does not even start at all, with some weird "runtime error" with no further info.

This is the same error I get.... I'm trying to debug it right now. Using the same EE worked like a charm in 18, but I can't pinpoint why it's not working in 19.... did you already try building you awx with a customized EE? I get this error every time, regardless of what I try to do.

**Comment by lemmy04** [comment]
Yep, tried that, in that case the deployment itself fails because the "default worker" container inside the AWX pod doesn't start...

**Comment by banshee091** [comment]
Just for research purposes: What specs did you give your pod?

**Comment by shanemcd** [comment]
There are a couple things going on here:

- Ad-hoc commands do not currently support using custom EEs. This is something we need to discuss and make a decision about.
- The default awx-ee is missing the `ansible.windows` collection, as mentioned in https://github.com/ansible/awx/issues/9863

**Comment by lemmy04** [comment]
> 
> 
> Just for research purposes: What specs did you give your pod?

the default specs from the operator.

**Comment by ryanpetrello** [comment]
So it sounds like we should make this properly use an EE defined on the inventory, if it's available?

**Comment by lemmy04** [comment]
I suggest that ad hoc commands simply use the same logic for determining the EE to use that job templates do - after all, nothing else would make much sense. I mean, would you *expect* ad hoc commands to behave differently from templated jobs?

**Comment by jbradberry** [comment]
> There are a couple things going on here:
> 
>     * Ad-hoc commands do not currently support using custom EEs. This is something we need to discuss and make a decision about.

That's not quite true.  They are still a `UnifiedJob`, which means that they do have the ability to have an EE attached.  I had originally thought that ad-hoc commands would have to have the user pick the EE when they create it, but it does make sense to have a simplified resolver (since an ad-hoc command doesn't _have_ a template, it has to skip those steps).

**Comment by AlexSCorey** [comment]
We can put a field on the ad-hoc commands form in the ui to allow/require the user to select an EE as well.

**Comment by jbradberry** [comment]
@AlexSCorey yes, that absolutely should be done.

**Comment by jbradberry** [comment]
I've just done some investigation, and I find that the resolver correctly picks out the Organization's Default EE for me.

![Screenshot_2021-04-19 Ansible AWX(1)](https://user-images.githubusercontent.com/685957/115262384-7cc19500-a102-11eb-834d-cddfe31af0b6.png)

![Screenshot_2021-04-19 Ansible AWX](https://user-images.githubusercontent.com/685957/115262395-7fbc8580-a102-11eb-8678-bce73f5a2628.png)

@lemmy04 are you certain that you set the Org's Default Execution Environment field?  It is not sufficient to assign a newly created EE to an Organization, it has to be set as the default on that Org.

**Comment by tiagodread** [comment]
While running Adhoc commands, now is possible to select an EE globally available or any other EE associated with the organization in which the inventory is is part of.
