### ISSUE TITLE
Inventory with multiple sources: groups are overwritten

### ISSUE THREAD

**Issue by lukasertl** [ansible/awx#9867]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I have an inventory with two sources:
* Sourced from a project (inventory.yml)
* Red Hat Satellite

The inventory.yml has a subset of the Satellite hosts, but groups them together differently.  Syncing the inventory.yml adds the hosts to the correct group defined in the inventory.yml.

Syncing the Satellite source empties all groups from the inventory.yml, leaving hosts only in groups that are defined on the Satellite.

The groups themselves are still there, also all group_vars, there are just no host members.

This has worked without problems up until 17.1.0, and also with the ansible CLI.

##### ENVIRONMENT
* AWX version: 19.0.0
* AWX install method: openshift

##### STEPS TO REPRODUCE

Define inventory with two sources - sourced from a project and Red Hat Satellite.  Sync them both.

##### EXPECTED RESULTS

The hosts should be members of all groups defined in inventory.yml and on Satellite.

##### ACTUAL RESULTS

The hosts are only members of the Satellite groups.

##### ADDITIONAL INFORMATION

Settings on inventory file:
Overwrite
Update on project update

Settings on Satellite:
Overwrite
Overwrite variables
Update on launch

The same settings work with AWX 17.1.0.

**Comment by shanemcd** [comment]
@AlanCoding Can you take a look at this and provide any insight you may have?

**Comment by lukasertl** [comment]
Comparing the debug output of Satellite sync in Version 17.1.0 and 19.0.0 I noticed the following - in the new version I get lots of:

```
WARNING  Host "host_xyz" has no "foreman_id" variable(s)
```

followed by lots of:

```
DEBUG    Deleted host "host_xyz"
```

**Comment by lukasertl** [comment]
Could be related to #9037 and #9749

**Comment by lukasertl** [comment]
I think I figured it out.

The field instance_id in the PostgreSQL table main_host was empty for all affected hosts.  Maybe some initial sync didn't set that correctly, I don't know.

After removing the Satellite inventory and recreating it the instance_ids were correct, and as such, subsequent inventory syncs would add hosts to the correct groups respectively wouldn't remove them from the wrong groups.
