### ISSUE TITLE
Add ability to associate other credential types to adhoc commands to enable using cloud modules that require auth

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#9870]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Right now, it appears to be possible to create an adhoc command with NO credential (this makes sense when `ansible_connection: local`) OR with an ssh/machine credential.

When `ansible_connection: local` it also makes sense that we would want a different credential type. For example, if I want to run an individual command from a cloud module using a credential I have in Tower that defines my authentication credentials for AWS, or google cloud, or another Tower itself if I am using the awx/tower collection.

For `ansible_connection: local` this means I could still get by with just 1 credential.

Otherwise, I may need multiple credentials (e.g., a machine credential to access the host, and then another credential for doing something with my cloud module).

**Comment by kdelee** [comment]
@yagomarques and I ran into this when we were trying to use the adhoc command feature in combination with the awx.awx collection

**Comment by ryanpetrello** [comment]
Bill says:

<img src="https://media.giphy.com/media/l3mZ2EGsiLy1m31wk/giphy.gif" />

**Comment by wenottingham** [comment]
More verbosely: I'd like to think about how we surface ad-hoc automation in general when it comes to things that aren't tied to "do this task to this machine in inventory" (as that's how it's surfaced now)
