### ISSUE TITLE
[ui_next] Datetime component does not load in Firefox

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#9871]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Datetime component does not load in Firefox

##### ENVIRONMENT
* AWX version:04/09/21
* AWX install method: yolo and docker
* Ansible version:  X.Y.Z
* Operating System: macOS
* Web Browser: Firefox ESR (maybe more recent versions, too)

##### STEPS TO REPRODUCE
1. Edit a schedule
2. Click on datetime field

##### EXPECTED RESULTS
HTML datetime picker to load

##### ACTUAL RESULTS
😭 

##### ADDITIONAL INFORMATION
<img width="444" alt="Screen Shot 2021-04-09 at 5 22 24 PM" src="https://user-images.githubusercontent.com/12446869/114242234-8b68b900-9958-11eb-8ef0-160090bb2816.png">

**Comment by jakemcdermott** [comment]
Just reproduced this on non-esr as well

**Comment by unlikelyzero** [comment]
To the interested QE member who picks this up for needs_test: Cypress doesn't allow for testing the HTML native datetime picker so this will have to be stubbed until the patternfly implementation lands

**Comment by jakemcdermott** [comment]
Note: Will need to double-check on the status of the related patternfly component

**Comment by jakemcdermott** [comment]
I'm removing the `waiting_for_pf` label - I think we may just need to use the pf-react datepicker component.

@keithjgrant noticed that we're still using a raw `input` field in parts of the schedule component, so it may just be that we need to replace it with the pf-react component.

**Comment by mabashian** [comment]
Fixed by https://github.com/ansible/awx/pull/10291
