### ISSUE TITLE
ERROR importing cache manifest from quay.io/awx/awx_devel:devel  AWX 19.0.0 ; docker-compose-build centos ; CentOS Linux release 8.3.2011; chrome

### ISSUE THREAD

**Issue by crupib** [ansible/awx#9880]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by ryanpetrello** [comment]
Please reopen this with the details in our bug report template:

https://github.com/ansible/awx/issues/new?assignees=&labels=&template=bug_report.md

**Comment by andyctnt** [comment]
make[1]: Entering directory '/root/awx'
docker compose -f tools/docker-compose/_sources/docker-compose.yml  up  --remove-orphans
WARN[0000] /root/awx/tools/docker-compose/_sources/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Running 2/3
 ⠙ redis_1 Pulling         0.2s
 ✘ postgres Error  context canceled   0.2s
 ✘ awx_1 Error     manifest unknown  0.2s
Error response from daemon: manifest unknown
make[1]: *** [Makefile:576: docker-compose-up] Error 18
make[1]: Leaving directory '/root/awx'
make: *** [Makefile:569: docker-compose] Error 2
