### ISSUE TITLE
/var/lib/awx directory does not exist after AWX installation.

### ISSUE THREAD

**Issue by sdlinden** [ansible/awx#9887]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME

 - Installer

##### SUMMARY

Installed AWX 18.0.0.  /var/lib/awx does not exist.

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: operator
* AWX deployment target: minikube
* Operating System: RHEL 8
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Follow the AWX documentation

##### EXPECTED RESULTS

AWX to see my projects.

##### ACTUAL RESULTS

AWX does not see the project

##### ADDITIONAL INFORMATION

The /var/lib/awx directory does not exist on my VM after installation. I do not know Docker or Kubernetes.  If the /var/lib/awx directory is supposed to exist in one of the containers, I have not found the documentation that states how I am supposed to modify it.  I have manually added the /var/lib/awx/projects directory on my test VM and then created a project directory with a test YML file but AWX does not see the project directory.  Can someone please direct me to the documentation on how to do this?

Thanks,

**Comment by ryanpetrello** [comment]
Hey @sdlinden,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by sdlinden** [comment]
Thanks
