### ISSUE TITLE
Allow webhook notification to launch Tower JOB Template

### ISSUE THREAD

**Issue by saifelyzal** [ansible/awx#9888]
##### ISSUE TYPE
 - Allow webhook notification to launch Tower JOB Template

##### SUMMARY
Currently launching Job Template from webhook notification fail to pass the inventory ID to the JOB 
The issue is that the launch api endpoint expects that the inventory be passed as an INTEGER type and not as a string. 
As workaround adding inventory ID to the customized messages launched the job

**Comment by spsingh1982** [comment]
Note: Workaround does not work as jobs are getting launched without any variables. So there is no use of this workaround.

**Comment by wenottingham** [comment]
If you are trying to launch a job on the success of another job, that is what workflows are for (or even, having a step in the job that calls the REST API).

This isn't what the job notifications are designed for.

**Comment by spsingh1982** [comment]
Wenottingham, we understand the purpose of the workflows and know how to use it. But here we needed out of band capability to update external nodes. Hence we are leveraging webhook capability whenever anyone invokes these workflows. Also these workflows are not owned by us and we do not have edit permissions. Only thing we could think of without asking other team to modify their code and without affecting outcome of their workflows is to use notifications. 
Also, if Tower is giving capability to invoke webhook there should be no limitation to call any API, be it for Tower API. I can call tower API from other tools which offer webhook. This is a gap in product whether you accept it or not.

**Comment by wenottingham** [comment]
This works today with notifications, though, if you need it - you point to the /launch/ endpoint, and send any needed variables in the success message under `extra_vars`.

You can't send the whole job_metadata dictionary due to json quoting issues, but you can send however many individual variables that you need.
