### ISSUE TITLE
Invalid `type` field in key select filter column in advanced search

### ISSUE THREAD

**Issue by seiwailai** [ansible/awx#9898]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Some model's classes do not contain `type` attributes or fields. Thus, filterable `type` should not be displayed in the key select filter in the advanced search.

Affected classes are as follows:
1. ActivityStream
2. CredentialType
3. ExecutionEnvironment
4. Host
5. InstanceGroup
6. Inventory
7. NotificationTemplate
8. OAuth2Application
9. Organization
10. Schedule
11. Team
12. Users

##### ENVIRONMENT
* AWX version: `devel`

##### STEPS TO REPRODUCE
1. Go to `schedules` section
2. Select advanced search
3. Select `type` key from the key select filter column
4. Type in any characters in the text input field
5. Click search

##### EXPECTED RESULTS
Should only display filterable key in the key select filter column

##### ACTUAL RESULTS
Display non-filterable key in the key select filter column

##### ADDITIONAL INFORMATION
![Invalid_field_bug](https://user-images.githubusercontent.com/67208821/114610045-0ff96580-9cd2-11eb-8cd2-25287cbaf43e.gif)

#### Potential Solution
Set the `type` field's filterable as `True` only if the model class consists of the `type` attribute.

**Comment by wenottingham** [comment]
-> #9441
