### ISSUE TITLE
/etc/tower/SECRET_KEY is hardcoded in Docker Image

### ISSUE THREAD

**Issue by JohnHouwer** [ansible/awx#99]
### Summary

/etc/tower/SECRET_KEY is hard-coded in Dockerfile
https://github.com/ansible/awx/blob/devel/installer/image_build/templates/Dockerfile.j2#L42
https://github.com/ansible/awx/blob/devel/installer/image_build/files/settings.py#L6
See: https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-SECRET_KEY

### Environment

* AWX version: DEVEL - Today
* Ansible version:  2.3.2.0
* Operating System: Ubuntu 16.04 LTS

### Steps To Reproduce:

Install to local Docker. Follow the Install instructions.

### Expected Results:

/etc/tower/SECRET_KEY should get the value of awx_secret_key from the inventory file.

### Actual Results:

/etc/tower/SECRET_KEY is a hard-coded string from the Dockerfile.

### Additional Information:

**Comment by matburt** [comment]
Need to refactor the standalone image build a bit... this is going to be tricky because folks who already have encrypted secrets could get locked out of them if we change it. I'll probably look at changing the default inventory variable to what we put in there in the process of changing this.

**Comment by leifmadsen** [comment]
Running into a similar problem with the hostname, so this is really a larger task than just the SECRETs. The `settings.py` being a static file causes some issues when deploying. Is there an idea around how this should be refactored?

**Comment by matburt** [comment]
Yes, though the hostname is fine I just think it's mis-typed in a particular location.

The secret key just needs to be populated from the environment given at container start time, but care must be taken because it will lock folks out of their credentials if it all of a sudden starts giving people a different value.

**Comment by daswars** [comment]
Do any of you know how to manually decrypt the passwords and SSH keys from the awx database with openssl?

I have the SECRET_KEY: cat /etc/tower/SECRET_KEY

and also all data from the database -> main_credential

Didn't get decrypted with the command:
openssl enc -e -aes-128-ecb -in encrypted. data -out decrypt. txt

**Comment by matburt** [comment]
@daswars this is out of scope for discussing this issue. Having said that... you can't use openssl to decrypt the credentials stored in the database.

**Comment by leifmadsen** [comment]
@matburt I think if the intention is for the value of the hostname to be hardcoded is fine, then yes, it is. My issue is that this whole file should be a template that allows you to override values, such as hostname, secret key, etc.

**Comment by leifmadsen** [comment]
So while part of the issue here is that one particular field is hard coded, I would prefer to see this whole file made into a template so that all the values are dynamic, and thus increases the original scope of this issue.

**Comment by matburt** [comment]
https://github.com/ansible/awx/blob/devel/installer/image_build/files/settings.py

As you can see, a lot of stuff is templated out to the environment. Secret key *should* be which is what I'd focus on here.

You can totally expand on that if you want to but I'd probably resist customization for customization sake without providing a lot of real value.

Most of the specific application configuration is managed in the database/api now. The things that are left are mostly things that aren't super useful to tune given a constrained environment.

**Comment by matburt** [comment]
fixed in #197
