### ISSUE TITLE
'overlay' is not supported over overlayfs

### ISSUE THREAD

**Issue by Jonaswinz** [ansible/awx#9900]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
My jobs are failing (sync example project from github) with this error:

```
WARN[0000] Found deprecated file /etc/containers/libpod.conf, please remove. Use /etc/containers/containers.conf to override defaults. 
WARN[0000] Found deprecated file /etc/containers/libpod.conf, please remove. Use /etc/containers/containers.conf to override defaults. 
Error: 'overlay' is not supported over overlayfs, a mount_program is required: backing file system is unsupported for this graph driver
```

Is awx trying to run docker inside docker ? 🤔

##### ENVIRONMENT
* AWX version: 19.0.0
* AWX install method: docker on linux (make docker-compose with #9552 solution)
* Ansible version:  2.9.19
* Operating System: Ubuntu 18.04
* Web Browser: Edge (chromium)

##### STEPS TO REPRODUCE

- make docker-compose with modification of Makefile (#9552)
- docker exec tools_awx_1 make clean-ui ui-devel
- docker exec -ti tools_awx_1 awx-manage createsuperuser
- sync demo project

##### EXPECTED RESULTS

sync demo project / run demo template without error

##### ACTUAL RESULTS

```
WARN[0000] Found deprecated file /etc/containers/libpod.conf, please remove. Use /etc/containers/containers.conf to override defaults. 
WARN[0000] Found deprecated file /etc/containers/libpod.conf, please remove. Use /etc/containers/containers.conf to override defaults. 
Error: 'overlay' is not supported over overlayfs, a mount_program is required: backing file system is unsupported for this graph driver
```

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/77646919/114612606-a31aa700-9ca2-11eb-8bed-ac494fc75b69.png)

**Comment by shanemcd** [comment]
> Is awx trying to run docker inside docker ? 

It's actually trying to run Podman inside of Docker. Our development environment is a set of hacks that mimic our downstream product when deployed on VMs. Dont use it for anything serious.

If you want something a little more "proper", check out the awx-operator.

**Comment by Jonaswinz** [comment]
Why are VMs / K8s the "proper" way to use AWX and not docker ? Version 17.0.0 was very leightweight and easy to run, but with a minikube instance the VMs themselves are using alot more system resources. I only want to manage few servers. Maybe someone can sum up some reasons.

**Comment by wenottingham** [comment]
The docker-compose installation method was intentionally removed in favor of a k8s-native installation. See https://groups.google.com/g/awx-project/c/47MjWSUQaOc/m/1-Jh0fy3AgAJ

The dev environment remains for testing purposes, but is not intended for production use.

**Comment by Jonaswinz** [comment]
Ok I tried to fix this issue 😅. I switched the podmans storage driver to vfs with `RUN podman --storage-driver=vfs info`  in tools/ansible/roles/dockerfile/templates/Dockerfile.j2. The error message changed to: `User-selected graph driver "overlay" overwritten by graph driver "vfs" from database - delete libpod local files to resolve `. I should clean / reset podman as mentioned here : https://github.com/containers/podman/issues/5114. But how do I do this? I couldnt find any storage.conf. Recloning of awx git and redoing the installation process didnt do the trick.

**Comment by Jonaswinz** [comment]
Ok I fixed this problem, by deleting oder editing storage.conf inside the container (/etc/containers) and restarting the container.

**Comment by shanemcd** [comment]
JFYI - Performance with VFS is going to be atrocious. If you do anything that involves heavy IO, you're going to have a bad time.

**Comment by renehasp** [comment]
> Ok I fixed this problem, by deleting oder editing storage.conf inside the container (/etc/containers) and restarting the container.

What does this mean? Did you delete storage.conf? I don't see "oder" editing

**Comment by Jonaswinz** [comment]
Sorry I meant "or". The storage.conf file still contained overlay as the storage driver. Therefore Podman was confused. @renehasp
