### ISSUE TITLE
Unable to cancel job - method POST not allowed - awx19

### ISSUE THREAD

**Issue by phemmer** [ansible/awx#9905]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I had an inventory sync job that was stuck. Upon trying to cancel it, I got an error saying `Method "POST" not allowed`

This is a refile of #9714 as the issue is still not fixed.

##### ENVIRONMENT
* AWX version: 19.0.0
* AWX install method: minishift
* Ansible version:  
* Operating System: Debian 10
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Get a stuck job?
2. Try to cancel job.

##### EXPECTED RESULTS

job to cancel

##### ACTUAL RESULTS

```
POST /api/v2/inventory_updates/11/cancel/ 405
Method "POST" not allowed.
```
![image](https://user-images.githubusercontent.com/1826947/114759279-f7b63480-9d2b-11eb-96ff-2d5669e4c4a1.png)

**Comment by phemmer** [comment]
Ok, so this looks to be a UI issue. The first time you click cancel, nothing visible happens. Then you click it again and you get the error. However the first cancel actually succeeded, and the second cancel is failing.

**Comment by shanemcd** [comment]
Need to handle the case where the user tries to cancel an already canceled job.

**Comment by phemmer** [comment]
While possibly true, I think making the "cancel" dialog go away when cancelled would be a higher priority.

**Comment by jakemcdermott** [comment]
On which screen are you attempting to cancel the job? Is it a job list, the details panel for the job, the output page, or somewhere else?

**Comment by phemmer** [comment]
The job output page.

**Comment by akus062381** [comment]
this is resolved.
