### ISSUE TITLE
Management Jobs - blank page

### ISSUE THREAD

**Issue by diogoattall** [ansible/awx#9909]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I cannot access Management Jobs menu, it shows only a blank page with the AWX navigation menu on the left side.

##### ENVIRONMENT
* AWX version: 17.1.0
* AWX install method: docker on linux
* Ansible version:  2.9.18
* Operating System: CentOS 7
* Web Browser: Chrome/Firefox

##### STEPS TO REPRODUCE

Login into AWX, and click on Management Jobs menu

##### EXPECTED RESULTS

Show the management jobs, and manage them

##### ACTUAL RESULTS

It does not show the management jobs, only a blank page.

**Comment by shanemcd** [comment]
I think the new UI didn't have management jobs until 18 or 19. Can you try again?

**Comment by Erick-shi** [comment]
I occur the same problem in awx 17.10，and can you solve it?
