### ISSUE TITLE
Job template with survey does not show popup with survey questions

### ISSUE THREAD

**Issue by eschek87** [ansible/awx#9918]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Job template with survey does not show popup for survey questions

##### ENVIRONMENT
* AWX version: 19.0.0
* AWX install method: operator
* AWX deployment target: minikube
* Operating System: Ubuntu 18
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Create job template, create surveys and mark "required"., run job template, survey is not shown.

##### EXPECTED RESULTS
Show survey popup

##### ACTUAL RESULTS
no survey popup

**Comment by AlexSCorey** [comment]
I just ran through those steps and was not able to reproduce. Maybe a silly question, but is your survey on?
![Screen Shot 2021-04-15 at 3 58 41 PM](https://user-images.githubusercontent.com/39280967/114930995-a5484700-9e03-11eb-8686-d17644f7bdf2.png)

**Comment by eschek87** [comment]
Save my day! Your are right. I forgot to activate it.
