### ISSUE TITLE
awx.awx.tower_user list existing user

### ISSUE THREAD

**Issue by roumano** [ansible/awx#9919]
##### ISSUE TYPE
 - Feature Idea
Actually it's not possible to use this module (`awx.awx.tower_user`) to have a up2date user in AWX as it's not possible to list existing account and set none personnal password is not a option and password is a mandatory field for new user.

##### SUMMARY

- Need a option to get the list of existng user (like via cli : `tower-cli user list`

**Comment by john-westcott-iv** [comment]
There is now an option to not set the password for users in the module. But the modules were not intended to "list things" in general. If you want a list of users look at lookup plugin `awx.awx.controller_api`.
