### ISSUE TITLE
Sort host groups by priority

### ISSUE THREAD

**Issue by phemmer** [ansible/awx#9921]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Currently when viewing a host's groups, the groups can only be sorted alphabetically. It would make sense to be able to sort them by priority as well. This way you know which group will have precedence when adding variables.

**Comment by wenottingham** [comment]
alphabetical *is* how they are merged by default.

If you mean sort by the `ansible_group_priority` var, as described here: https://docs.ansible.com/ansible/devel/user_guide/intro_inventory.html#how-variables-are-merged... those group vars aren't indexed in a way that the API can order the groups, which is what would be required for them to be displayed in a particular order.

From a UX perspective, I'm not sure that just sorting the groups is the right way here, in favor of something like #2524

**Comment by phemmer** [comment]
Why was this closed?

> those group vars aren't indexed in a way that the API can order the groups

Isn't that what feature requests are for? To add functionality that doesn't currently exist?
