### ISSUE TITLE
Installing New AWX 19.0 Migrations failing.

### ISSUE THREAD

**Issue by Tyler-Ouellette** [ansible/awx#9927]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When installing awx I am getting this error:
![image](https://user-images.githubusercontent.com/47769996/115020686-ed5d7d00-9e88-11eb-95c0-cf57e51c295b.png)

Internal 500 error due to zapper?

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE
From a fresh Ubuntu 20.04 instance with Virtualization.
sudo apt-get update
sudo apt upgrade -y
sudo apt install docker.io -y
sudo systemctl enable --now docker

if you need to Disable Docker at startup:
	sudo systemctl disable --now docker
sudo usermod -aG docker tyler
docker –version

Docker is good. Next install Kubectl
sudo apt-get update
sudo apt-get install apt-transport-https
sudo apt-get upgrade
sudo apt install virtualbox virtualbox-ext-pack

wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
chmod +x minikube-linux-amd64 
sudo mv minikube-linux-amd64 /usr/local/bin/minikube
minikube version

sudo apt install curl
curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
chmod +x ./kubectl

sudo mv ./kubectl /usr/local/bin/kubectl

kubectl version -o json

Good to use minikube

minikube start

Start minikube for AWX
minikube start --cpus=4 --memory=8g --addons=ingress

minikube kubectl -- apply -f https://raw.githubusercontent.com/ansible/awx-operator/devel/deploy/awx-operator.yaml

 

Wait until it is ready
Nano install-awx-playbook.yml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  tower_ingress_type: Ingress

minikube kubectl apply -- -f install-awx-playbook.yml

To see logs of the install run this:
minikube kubectl logs -- -f awx-operator-ID from your pod
minikube kubectl logs -- -f awx-operator-f768499d-zn7zc

After running you should run

minikube kubectl get pods
 
To Access AWX
minikube service awx-service –url 
http://192.168.49.2:31417
Once you go to the IP:Port address you probably see AWX is currently upgrading. Once it does, you will be redirected to a login screen. To get login info run:

minikube kubectl -- get secret awx-admin-password -o jsonpath='{.data.password}' | base64 –decode

##### EXPECTED RESULTS

AWX to work, instead I am stuck on upgrading AWX screen:

##### ACTUAL RESULTS

Stuck as this screen won't update. 
![image](https://user-images.githubusercontent.com/47769996/115021067-78d70e00-9e89-11eb-982d-ea924bc45f38.png)

**Comment by shanemcd** [comment]
A few things:

- Please reopen this at awx-operator.
- When you do so, copy / paste the text instead of a screenshot.
- Please use markdown to format your code snippets.
