### ISSUE TITLE
When editing a survey another tab is highlighted

### ISSUE THREAD

**Issue by nixocio** [ansible/awx#9929]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When editing a survey the another tab is selected. Survey tab should be the one highlighted.

<img width="1453" alt="image" src="https://user-images.githubusercontent.com/9053044/115030830-85f9fa00-9e95-11eb-9cb4-6e17a0f7874e.png">

**Comment by nixocio** [comment]
~Maybe related to https://github.com/ansible/awx/issues/9868~

**Comment by shilpeePrasad** [comment]
Hi, I would like to work on this issue. Thanks

**Comment by mabashian** [comment]
We don't show that nav when adding/editing an item anymore - closing

<img width="1670" alt="Screen Shot 2022-04-05 at 11 44 10 AM" src="https://user-images.githubusercontent.com/9889020/161793145-1485d127-5908-47c3-bce9-38afd6011e66.png">
