### ISSUE TITLE
Allow execution environments to inherit other files in project structure

### ISSUE THREAD

**Issue by dsmaugy** [ansible/awx#9930]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

My project structure is as follows:
```
playbooks/
   - ansible.cfg
   - playbook1.yml
   - playbook2.yml
   - playbook3.yml
   - ...
roles/
   - role1/
   - role2/
   - role3/
   - ...
```

I have my multiple playbooks in a subdirectory as to not clutter the root directory and my `ansible.cfg` adds the `roles/` directory to the roles_path variable so Ansible knows where to find them.

This works fine when running locally, but when run in AWX, the execution environment only contains the files on the same level as the playbook:

```
/runner/project/playbooks
   - ansible.cfg
   - playbook1.yml
   - playbook2.yml
   - playbook3.yml
   - ...
```

It would be great if the EE were able to include my roles/ folder as well even though it's one level higher than the playbooks.

**Comment by shanemcd** [comment]
@dsmaugy Are you doing anything weird like symlinking inside your repo?

**Comment by dsmaugy** [comment]
@shanemcd Yeah, the `playbooks/ansible.cfg` is symlinked to a `ansible.cfg` at the root folder of the repo

**Comment by AlanCoding** [comment]
I don't understand what's not working here. The folder `/runner/project/roles` should be available. What error are you encountering?

Did you give `roles_path` setting in `ansible.cfg` as a relative path? Because that's the only thing that can be expected to work.

**Comment by dsmaugy** [comment]
@AlanCoding You're right, the `/runner/project/roles` folder actually was available, it was my `ansible.cfg` that was messed up and unable to link to the roles directory. Thanks!
