### ISSUE TITLE
Invalid username or password. Please try again. 

### ISSUE THREAD

**Issue by tetesh** [ansible/awx#9936]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Invalid username or password. Please try again.

##### ENVIRONMENT
* AWX version: 17.1.0
* AWX install method: docker on linux
* Ansible version:  2.9.6
* Operating System: Ubuntu server
* Web Browser: Chrome, Firefox

##### STEPS TO REPRODUCE

i have installed awx using playbook in docker container.
Changed in advance admin_password = Sespassword

##### ACTUAL RESULTS

When entering login / password (admin / Sespassword)
I get an error:
Invalid username or password. Please try again.
I also tried to set different passwords and versions

**Comment by wenottingham** [comment]
This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
