### ISSUE TITLE
Installation without Docker or K8S Cluster

### ISSUE THREAD

**Issue by Craftoncu** [ansible/awx#9937]
Not much to say.
Title describes it.

Why to setup a clean cluster or use a development environment for awx? 

Add support for local installations!
That would be a pleasure of many many users.

**Comment by shanemcd** [comment]
Hello. We are a small team and simply do not have the resources to maintain other installation methods. If someone in the community wants to do this, that's fine, but we have no plans for it.

**Comment by Craftoncu** [comment]
Then let this issue open. Im currently working on it
