### ISSUE TITLE
Public expose port from Minikube cluster

### ISSUE THREAD

**Issue by Craftoncu** [ansible/awx#9938]
Add port export to documentation.
Im running awx with minikube on single server.

How to export the port from awx to 0.0.0.0.

I don't want security advises. Im working behind a firewall + reverse proxy.

**Comment by shanemcd** [comment]
You may want to look into running Kubernetes outside of Minikube. The AWX Operator provides several options for customizing ingress, all of which are documented in the readme: https://github.com/ansible/awx-operator
