### ISSUE TITLE
Boolean fields on credential inputs sometimes display as true even when they're false

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/awx#9955]
##### ISSUE TYPE
 - Bug Report

##### STEPS TO REPRODUCE
- check out [this pr](https://github.com/ansible/awx/pull/9951)
- make a container registry credential
- after making the cred, edit it and change the tls flag to false and save again
- Note that when you return to the form it'll still display as a checked box but the api value is actually false
- Observation: if you log the value of credential.inputs [in the form component](https://github.com/ansible/awx/blob/devel/awx/ui_next/src/screens/Credential/shared/CredentialForm.jsx#L240), it changes to true somehow during initialization.

**Comment by mabashian** [comment]
You can reproduce this bug on devel.  Just create a Tower credential and leave the Verify SSL option unchecked.  After saving, attempt to edit the credential and you'll see Verify SSL checked.

**Comment by tiagodread** [comment]
The bug was fixed by #9960, now the UI is properly displaying the current state of the API data for options. We had some e2e broken tests, however, none of them is related to this change.
