### ISSUE TITLE
AWX with external postgres database - docker compose

### ISSUE THREAD

**Issue by v2kiran** [ansible/awx#9959]
##### ISSUE TYPE
 - Question

##### COMPONENT NAME
 - Installer

##### SUMMARY
The External database settings of the [inventory](https://github.com/ansible/awx/blob/devel/tools/docker-compose/inventory) file contains :
`pg_host` &
`pg_hostname`

what is the difference between these two? and should we use them both or will using pg_hostname suffice

Also the inventory file does not containv ariables for :
`pg_port` &
`pg_database`

I assume we can add these ourselves but not sure if they will be used by the installer so need some clarification.

##### ENVIRONMENT
* AWX version: 19
* AWX install method: developer environment
* AWX deployment target: docker compose
* Operating System: RHEL 8
* Web Browser:

**Comment by wenottingham** [comment]
This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
