### ISSUE TITLE
Run a specific task of a playbook from a job template

### ISSUE THREAD

**Issue by cesarfn4** [ansible/awx#996]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API

##### SUMMARY

Add a field to a job template that would allow a user to start a playbook at the task specified. This would be analogous to the '--start-at-task' option from the ansible-playbook command.

##### EXPECTED RESULTS

Be able to select in a job template the task of the playbook that you want to launch without having to use tags.

**Comment by wenottingham** [comment]
This is not really practical from a UX standpoint as we don't have this information (at a minimum, it would be very prone to error.)

**Comment by cchurch** [comment]
The API already supports `start_at_task` for job templates.
