### ISSUE TITLE
installer folder missing

### ISSUE THREAD

**Issue by rockymiho** [ansible/awx#9966]
Hi 

following the steps from the below url: I dont see installer directory in awx 

https://computingforgeeks.com/how-to-install-ansible-awx-on-ubuntu-linux/

##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by Valvos420** [comment]
the type of installation change, if you want to install with the github, you need to follow this documentation : https://www.howtoforge.com/how-to-install-ansible-awx-on-debian-10/
This is the same but with the version 17.0.0
If you want to install the last version, you need to follow this documentation:
https://github.com/ansible/awx/blob/devel/INSTALL.md
You can also install with docker:
https://github.com/ansible/awx/blob/devel/tools/docker-compose/README.md

**Comment by shanemcd** [comment]
Yep, the old installer went away. For more context:

- https://groups.google.com/g/awx-project/c/47MjWSUQaOc/m/1-Jh0fy3AgAJ
- https://groups.google.com/g/awx-project/c/AllI1i0YqHE/m/MS8uDFWzCAAJ
