### ISSUE TITLE
unable to find https://github.com/ansible/awx/blob/devel/tools/inventory

### ISSUE THREAD

**Issue by unixplex** [ansible/awx#9976]
Unable to find 
https://github.com/ansible/awx/blob/devel/tools/inventory

**Comment by unixplex** [comment]
Please assist

**Comment by wenottingham** [comment]
This issue tracker is for tracking feature enhancements and bugs to AWX itself.

We recently changed how AWX is installed. See https://groups.google.com/g/awx-project/c/47MjWSUQaOc/m/1-Jh0fy3AgAJ

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
