### ISSUE TITLE
Schedule requires users to open survey prompt before they can save

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#9977]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
If all the required survey questions on a JT have default answers then the user shouldn't have to open the prompt modal to create a schedule.

![schedule_add](https://user-images.githubusercontent.com/9889020/115620006-a2959800-a2c2-11eb-8aa9-5c3c9f4c93f4.gif)

##### STEPS TO REPRODUCE
Create a JT
Create a required survey question for JT with a default answer
Attempt to create a schedule for JT without clicking on the prompt button

**Comment by tiagodread** [comment]
Verified manually, all e2e tests are 🟢
