### ISSUE TITLE
AWS UI is blank

### ISSUE THREAD

**Issue by maxifox79** [ansible/awx#9978]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
UI Interface is blank

##### ENVIRONMENT
* AWX version: 19.0.0
* AWX install method: Docker on linux
* Ansible version:  2.9.18
* Operating System: Centos 7.9
* Web Browser: Chrome

##### STEPS TO REPRODUCE
While building the UI interface everything works ok, but we cannot access the UI interface page

##### EXPECTED RESULTS

Access UI interface

##### ACTUAL RESULTS

UI page is blank

##### ADDITIONAL INFORMATION

while trying to build de User Interface using command <> I get this messages:
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

597.29 KB build/static/js/2.2dec5330.chunk.js
303.19 KB build/static/js/main.2767e07e.chunk.js
64.95 KB build/static/css/2.4f9d8bcb.chunk.css
770 B build/static/js/runtime-main.a1234c1a.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

npm install -g serve
serve -s build

Find out more about deployment here:

bit.ly/CRA-deploy

mkdir -p awx/public/static/css
mkdir -p awx/public/static/js
mkdir -p awx/public/static/media
cp -r awx/ui_next/build/static/css/* awx/public/static/css
cp -r awx/ui_next/build/static/js/* awx/public/static/js
cp -r awx/ui_next/build/static/media/* awx/public/static/media
touch awx/ui_next/.ui-built
make[1]: Leaving directory '/awx_devel'

When trying to reach api at https://localhost:8043/api/v2 everything works as expected
When trying to reach UI at https://localhost:8043/#/home screen stays blank.

What I am missing?

**Comment by Valvos420** [comment]
For me, i just use this command : npm --prefix awx/ui_next start
Then the server start and give me an URL so i can connect to the UI

**Comment by maxifox79** [comment]
when I run the same command I get:

{root@awx]# npm --prefix awx/ui_next start

> ui_next@0.1.0 prestart /root/awx/awx/ui_next
> lingui compile

Compiling message catalogs…
Done!

> ui_next@0.1.0 start /root/awx/awx/ui_next
> PORT=3001 HTTPS=true DANGEROUSLY_DISABLE_HOST_CHECK=true react-scripts start

/root/awx/awx/ui_next/node_modules/react-dev-utils/WebpackDevServerUtils.js:167
  compiler.hooks.done.tap('done', async stats => {
                                  ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/awx/awx/ui_next/node_modules/react-scripts/scripts/start.js:45:5)

npm ERR! Linux 3.10.0-1160.24.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "--prefix" "awx/ui_next" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ui_next@0.1.0 start: `PORT=3001 HTTPS=true DANGEROUSLY_DISABLE_HOST_CHECK=true react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ui_next@0.1.0 start script 'PORT=3001 HTTPS=true DANGEROUSLY_DISABLE_HOST_CHECK=true react-scripts start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ui_next package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     PORT=3001 HTTPS=true DANGEROUSLY_DISABLE_HOST_CHECK=true react-scripts start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ui_next
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ui_next
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/awx/npm-debug.log

**Comment by shanemcd** [comment]
Are you trying to run these commands on the host machine rather than following the steps outlined here? https://github.com/ansible/awx/blob/devel/tools/docker-compose/README.md#clean-and-build-ui

**Comment by maxifox79** [comment]
We detected that we have old versions of node.js and npm, we updated with instructions from here
https://linuxize.com/post/how-to-install-node-js-on-centos-7/
 Finally, we get this working, thank you all for your help
