### ISSUE TITLE
AWX - run Job on single host 

### ISSUE THREAD

**Issue by ayyappabani** [ansible/awx#9984]
while executing job_template with current options, one has to select target group and no option to run Job on single hos.
 The host not necessarily be part of any groups.

### Survey form
the issue could be addressed thru the option using Survey to create a prompt to enter hostname/ip-address
the var should be "ansible_host"

<img width="550" alt="image" src="https://user-images.githubusercontent.com/52236829/115682820-7423c580-a373-11eb-9643-29478aa5caab.png">

### while executing
keep target inventory with dummy host added as "hostname"

<img width="678" alt="image" src="https://user-images.githubusercontent.com/52236829/115683059-b220e980-a373-11eb-9cd2-e71b5e8cbec8.png">

**Comment by shanemcd** [comment]
This is what you are looking for: 
<img width="739" alt="Ansible AWX 2021-04-22 09-00-23" src="https://user-images.githubusercontent.com/773186/115718553-3611ac00-a349-11eb-94d8-89f6f250edfd.png">

**Comment by ayyappabani** [comment]
no .. for limit option to use, host should be part of inventory . I was looking for an option to enter hostname without an inventory. so I could do that with survey option as mentioned in about issue/post. thanks for the post :)
