### ISSUE TITLE
Best practice to migrate from 17.x (docker production) to 19.x ?

### ISSUE THREAD

**Issue by craph** [ansible/awx#9985]
Hello,

For the moment I have an AWX production environment (AWX 17.0.1) and I'm using with Docker.

So how can I proceed to upgrade my version to the latest one ? 
The best practice is to deploy it on a k8s cluster ?

Why Docker is not supported anymore for an AWX production environment ?
Why now it's only for development / tests ?

Thank you very much for your help.

**Comment by shanemcd** [comment]
Hello. We are small team and just don't have the resources to maintain an installation path that we ourselves never used.

While we didn't develop it with this exact use case in mind, you may have some luck following these steps: https://github.com/ansible/awx-operator/blob/devel/docs/migration.md

If you need any more help troubleshooting as you make your way through this, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by craph** [comment]
@shanemcd Thank you for the update but sorry you don't answered my questions.

The link you gave me doesn't explain all the prerequisites to install the latest version of AWX. Moreover, I don't understand why you said you never used this path of installation because in all the revious release prior to 18.x all the steps to install via docker are in the documentation.

It would be very appreciate for all the community who have an AWX with Docker in Production to have the best practive and all the prerequisite to migrate from 17.x to 18.x or 19.x.

Should we have to install K8S or Minikube or OpenShift ... ?

Please re-open the ticket, I guess I'm not the only one in this case.

Thank you very much.

**Comment by shanemcd** [comment]
The documentation on how to install AWX 19 is already pretty clear: https://github.com/ansible/awx/blob/devel/INSTALL.md. If you run into anything you feel is unclear, please open a PR.

While _most_ versions of AWX will upgrade seamlessly, this is a fast-moving upstream open source project. Things will break occasionally. Instead of expecting endless stability, maybe invest some time in automating the provisioning process of your AWX.

**Comment by craph** [comment]
@shanemcd, thank you for the link.

I have already invest some time in automating the provisioning process for my AWX in production. All was done with Docker. And now I see that it's not supported anymore for production but only for development and tests.

In the documentation I see only a reference to minikube so my question was : what are all the prerequisites to migrate to the latest version.

**Comment by mboehm21** [comment]
I'm in the same situation as @craph and also need some clarity on this. AWX is the only application we would need Kubernetes for. It generates so much overhead for just a single application.

**Comment by shanemcd** [comment]
@craph  The page I linked to says:

> If you don't have an existing OpenShift or Kubernetes cluster, minikube is a fast and easy way to get up and running.

> For a comprehensive overview of features, see README.md in the awx-operator repo. The following steps are the bare minimum to get AWX up and running.

@mboehm21 What kind of clarity are you looking for? Yes, outside of the development environment, AWX requires Kubernetes.

**Comment by azrdev** [comment]
related to #9337

**Comment by mboehm21** [comment]
@shanemcd Just a few comments from me:

* It is not a good idea to run the automation tool inside of the platform people want to automate. When the platform (k8s) breaks, your automation tool to restore it might be unoperational as well. So you’d need a second cluster just for AWX.
* It is a good idea to have a automation tool with such high privileges in a DMZ on a firewalled host and not next to your production apps in a Kubernetes cluster.
* Not every AWX user / admin is familiar with Kubernetes, especially in network automation.
* Minikube’s overhead is immense compared to docker-compose when used on a single host.

I know that won’t change your opinion to make Kubernetes mandatory but I still wanted to write that down here.

**Comment by gruselglatz** [comment]
Did someone found a solution?

Sometimes i think, opensource for companies is only here to get free work from the outside and when you are funny you go the way like cloudera and call it opensource (find the source behind a paywall)...

So obviously the easiest way to use awx was canceled to drive you into a service contract to get the "easy one click install", like documented @ redhat.

It's definitely no good way to depend on a full cluster or "minicluster" system to run only ONE container for ONE application.
Maybe big redhat can give something back to the community by releasing a human way to install it?

**Comment by girish-cheedala** [comment]
I am in the same situation as @craph. 
can you please explain why we have stopped supporting deployment on docker ?

**Comment by gnulux** [comment]
Hi, i agree with @girish97115 and @craph , Why not provide at least a deployment with master , broker instance on docker ?
I had planned to use version 23.9.0 in production on docker but now i'm looking for another solution.
