### ISSUE TITLE
Compiling AWX UI interface does not work

### ISSUE THREAD

**Issue by maxifox79** [ansible/awx#9989]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After executing "docker exec tools_awx_1 make clean-ui ui-devel" command, UI is unavailable.

##### ENVIRONMENT
* AWX version: 19.0.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.9.18
* Operating System: Centos 7.9  
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE
execute "docker exec tools_awx_1 make clean-ui ui-devel"

##### EXPECTED RESULTS
UI Interface available

##### ACTUAL RESULTS
UI page at "http://<localhost>:31868" is blank

##### ADDITIONAL INFORMATION
While executing make to build UI... 

]# docker exec tools_awx_1 make clean-ui ui-devel
rm -rf node_modules
rm -rf awx/ui_next/node_modules
rm -rf awx/ui_next/build
rm -rf awx/ui_next/src/locales/_build
rm -rf awx/ui_next/.ui-built
npm --prefix awx/ui_next --loglevel warn --ignore-scripts install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 2048 packages from 889 contributors and audited 2056 packages in 35.471s

108 packages are looking for funding
  run `npm fund` for details

found 7 vulnerabilities (6 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
make[1]: Entering directory '/awx_devel'
npm --prefix awx/ui_next --loglevel warn run compile-strings

> ui_next@0.1.0 compile-strings /awx_devel/awx/ui_next
> lingui compile

Compiling message catalogs…
Done!
npm --prefix awx/ui_next --loglevel warn run build

> ui_next@0.1.0 build /awx_devel/awx/ui_next
> INLINE_RUNTIME_CHUNK=false react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  597.29 KB  build/static/js/2.2dec5330.chunk.js
  303.19 KB  build/static/js/main.2767e07e.chunk.js
  64.95 KB   build/static/css/2.4f9d8bcb.chunk.css
  770 B      build/static/js/runtime-main.a1234c1a.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  bit.ly/CRA-deploy

mkdir -p awx/public/static/css
mkdir -p awx/public/static/js
mkdir -p awx/public/static/media
cp -r awx/ui_next/build/static/css/* awx/public/static/css
cp -r awx/ui_next/build/static/js/* awx/public/static/js
cp -r awx/ui_next/build/static/media/* awx/public/static/media
touch awx/ui_next/.ui-built
make[1]: Leaving directory '/awx_devel'

Thanks for your help!

**Comment by shanemcd** [comment]
Please, stop spamming our issue queue. This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
