### ISSUE TITLE
Add globally available custom modules for clustered nodes.

### ISSUE THREAD

**Issue by gamuniz** [ansible/awx#999]
##### ISSUE TYPE

 - Feature Idea
 
##### COMPONENT NAME

 - API
 - UI
 

##### SUMMARY

Using custom modules becomes cumbersome when trying to use them across nodes in a cluster. There isn't currently a good solution for making sure that these modules are available on all clusters that don't involve manual intervention. 

##### ENVIRONMENT
* AWX version: latest
* AWX install method: NA
* Ansible version:  2.4.2
* Operating System: RHEL 7
* Web Browser: NA

##### STEPS TO REPRODUCE
1. create custom module directory on only one node of AWX
2. run playbook a few times to ensure it hits another node 

##### EXPECTED RESULTS
With the globally available feature it would allow for the custom modules to be shared across x nodes.

##### ACTUAL RESULTS
Currently fails unless you use custom library/ or rsync the module directory across nodes.

**Comment by wenottingham** [comment]
For AWX, this is best done by customizing the container image, or potentially the venv; this should not be done within the AWX service.
