### ISSUE TITLE
Visual differences on the same component between dev and production builds

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#9997]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Looking at the visual tests diffs we realized that there is a visual diff between the same component on dev and prod builds
This may or may not be introduced by https://github.com/ansible/awx/pull/9649

##### ENVIRONMENT
* Devel

##### STEPS TO REPRODUCE

Run the dev server and production build and compare the component above

Before:
![image](https://user-images.githubusercontent.com/12464858/115785371-bbbb4900-a395-11eb-95e8-ef8e4f944c20.png)

After:
![image (1)](https://user-images.githubusercontent.com/12464858/115785367-bb22b280-a395-11eb-89a3-ab0308fd49d2.png)

Note the missing border of the select component

**Comment by nixocio** [comment]
Related to patternfly/patternfly-react#5882

Also see: patternfly/patternfly-react#5650

**Comment by tiagodread** [comment]
fixed!
